# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: daily
    labels:
      - Dependencies
    groups:
      HotChocolate:
        applies-to: version-updates
        patterns:
          - "HotChocolate.*"
      Swashbuckle:
        applies-to: version-updates
        patterns:
          - "Swashbuckle.*"
    open-pull-requests-limit: 100
  - package-ecosystem: github-actions
    directory: /
    target-branch: master
    schedule:
      interval: daily
    labels:
      - Dependencies
      - CI/CD
    open-pull-requests-limit: 100
