codecov:
  strict_yaml_branch: dev
ignore:
  - "src/Tgstation.Server.Host/Database/Migrations"
  - "src/Tgstation.Server.Host/Database/Design"
coverage:
  status:
    project:
      default:
        threshold: 0
        if_no_uploads: failure
        if_ci_failed: failure
comment:
  layout: "header, diff, changes"
