os: linux
dist: xenial
language: generic
git:
  depth: 1

branches:
  only:
  - dev
  - master

jobs:
  include:
    - env:
      name: "Dox Generation"
      addons:
        apt:
          packages:
            - doxygen
            - graphviz

script:
  - build/build_dox.sh
