os: linux
dist: xenial
language: csharp
git:
  depth: 1
branches:
  only:
  - dev
  - master
jobs:
  include:
    - env:
      - DockerBuild=false
      - DMAPI=true
      - BYOND_MAJOR="513"
      - BYOND_MINOR="1517"
      - DMEName="tests/DMAPI/travistester.dme"
      - DoxBuild=false
      name: "DMAPI Unit Tests"
      language: generic
      cache:
        directories:
          - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

      addons:
        apt:
          packages:
            - libc6-i386
            - libstdc++6:i386
    - env:
      - DockerBuild=false
      - DMAPI=false
      - CONFIG=Debug
      - DoxBuild=false
      name: "Test Server Debug"
      mono: none
      dotnet: 2.2.207
      services:
        - mysql
      cache:
        directories:
          - $HOME/.nuget/packages:
    - env:
      - DockerBuild=false
      - DMAPI=false
      - CONFIG=Release
      - DoxBuild=false
      name: "Test Server Release"
      mono: none
      dotnet: 2.2.207
      services:
        - mysql
      cache:
        directories:
          - $HOME/.nuget/packages:
    - env:
      - DockerBuild=true
      - DoxBuild=false
      name: "Docker Build"
      language: generic
      services:
        - docker
    - env:
      - DoxBuild=true
      name: "Dox Build"
      language: generic
      os: windows
install:
  - if [ $DoxBuild = false ] && [ $DockerBuild = false ] && [ $DMAPI = true ]; then build/install_byond.sh; fi
  - if [ $DoxBuild = false ] && [ $DockerBuild = false ] && [ $DMAPI = false ]; then dotnet restore tgstation-server.sln; fi
  - if [ $DoxBuild = true ]; then choco install doxygen.install codecov graphviz.portable; fi
script:
  - if [ $DoxBuild = false ] && [ $DockerBuild = false ] && [ $DMAPI = true ]; then tests/DMAPI/build_byond.sh || travis_terminate 1; fi
  - if [ $DoxBuild = false ] && [ $DockerBuild = false ] && [ $DMAPI = false ]; then build/test_core.sh; fi
  - if [ $DoxBuild = false ] && [ $DockerBuild = true ]; then docker build . -f build/Dockerfile; fi
  - if [ $DoxBuild = true ]; then powershell -File build/BuildDox.ps1; fi
