tgstation-server: src/Tgstation.Server.Host.Service/Program.cs File Reference
Program.cs File Reference
Classes
class Tgstation.Server.Host.Service.Program
Contains the entrypoint for the application.
Namespaces
namespace Tgstation
namespace Tgstation.Server
namespace Tgstation.Server.Host
namespace Tgstation.Server.Host.Service
Functions
Tgstation.Server.Host.Service.InvokeSC (null)
void RestartService (ServiceController serviceController)
Restarts a service using a given serviceController .
async ValueTask RunConfigure (CancellationToken cancellationToken)
Runs the host application with the setup wizard.
string[] GetPassthroughArgs ()
Format PassthroughArgs into an Array.
Variables
return Tgstation.Server.Host.Service.serviceStopped
Function Documentation
GetPassthroughArgs()
string[] GetPassthroughArgs ()
Format PassthroughArgs into an Array.
Returns
PassthroughArgs formatted as a string Array.
Referenced by Tgstation.Server.Host.Service.Program.OnExecuteAsync(), and RunConfigure().
RestartService()
void RestartService (ServiceController serviceController)
Restarts a service using a given serviceController .
Parameters
serviceController The ServiceController for the service to restart.
Definition at line 260 of file Program.cs.
        {
            if (serviceController.Status != ServiceControllerStatus.Running)
                return;
            var stop = !Detach;
            if (!stop)
            {
                var serviceControllerCommand = PipeCommands.GetServiceCommandId(PipeCommands.CommandDetachingShutdown);
                serviceController.ExecuteCommand(serviceControllerCommand!.Value);
                serviceController.WaitForStatus(ServiceControllerStatus.Stopped, TimeSpan.FromSeconds(30));
                if (serviceController.Status != ServiceControllerStatus.Stopped)
                    stop = true;
            }
            if (stop)
            {
                serviceController.Stop();
                serviceController.WaitForStatus(ServiceControllerStatus.Stopped);
            }
        }
References Tgstation.Server.Host.Common.PipeCommands.CommandDetachingShutdown, and Tgstation.Server.Host.Common.PipeCommands.GetServiceCommandId().
Referenced by Tgstation.Server.Host.Service.Program.InvokeSC(), and Tgstation.Server.Host.Service.Program.OnExecuteAsync().
RunConfigure()
async ValueTask RunConfigure (CancellationToken cancellationToken)
Runs the host application with the setup wizard.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Definition at line 287 of file Program.cs.
        {
            using var loggerFactory = LoggerFactory.Create(builder =>
            {
                if (!Silent)
                    builder.AddConsole();
            });
            var watchdog = WatchdogFactory.CreateWatchdog(new NoopSignalChecker(), loggerFactory);
            await watchdog.RunAsync(true, GetPassthroughArgs(), cancellationToken);
        }
References Tgstation.Server.Host.Watchdog.WatchdogFactory.CreateWatchdog(), GetPassthroughArgs(), and Tgstation.Server.Host.Watchdog.IWatchdog.RunAsync().
Referenced by Tgstation.Server.Host.Service.Program.OnExecuteAsync().