tgstation-server: TGServerService.TGStationServer.RepoConfig Class Reference
TGServerService.TGStationServer.RepoConfig Class Reference
Repo specific information about the installation Requires RepoLock and !RepoBusy to be instantiated
Public Member Functions
RepoConfig (bool FromRepository)
override bool Equals (object obj)
bool Equals (RepoConfig other)
override int GetHashCode ()
Static Public Member Functions
static bool operator== (RepoConfig config1, RepoConfig config2)
static bool operator!= (RepoConfig config1, RepoConfig config2)
Public Attributes
readonly bool ChangelogSupport
readonly string PathToChangelogPy
readonly string ChangelogPyArguments
readonly IList< string > PipDependancies = new List<string>()
readonly IList< string > PathsToStage = new List<string>()
readonly IList< string > StaticDirectoryPaths = new List<string>()
readonly IList< string > DLLPaths = new List<string>()
Static Private Member Functions
static IList< string > LoadArray (object o)
static bool ListEquals (IList< string > A, IList< string > B)
Detailed Description
Repo specific information about the installation Requires RepoLock and !RepoBusy to be instantiated
Definition at line 44 of file Repository.cs.
Constructor & Destructor Documentation
TGServerService.TGStationServer.RepoConfig.RepoConfig (bool FromRepository)
Definition at line 54 of file Repository.cs.
References TGServerService.TGStationServer.CachedTGS3SettingsPath, and TGServerService.TGStationServer.RepoConfig.LoadArray().
Referenced by TGServerService.TGStationServer.GenerateChangelogImpl(), TGServerService.TGStationServer.InitialConfigureRepository(), TGServerService.TGStationServer.RepoConfigsMatch(), and TGServerService.TGStationServer.SynchronizePush().
             {
                 var path = FromRepository ? RepoTGS3SettingsPath : CachedTGS3SettingsPath;
                 if (!File.Exists(path))
                     return;
                 var rawdata = File.ReadAllText(path);
                 var Deserializer = new JavaScriptSerializer();
                 var json = Deserializer.Deserialize<IDictionary<string, object>>(rawdata);
                 try
                 {
                     var details = (IDictionary<string, object>)json["changelog"];
                     PathToChangelogPy = (string)details["script"];
                     ChangelogPyArguments = (string)details["arguments"];
                     ChangelogSupport = true;
                     try
                     {
                         PipDependancies = LoadArray(details["pip_dependancies"]);
                     }
                     catch { }
                 }
                 catch {
                     ChangelogSupport = false;
                 }
                 try
                 {
                     PathsToStage = LoadArray(json["synchronize_paths"]);
                 }
                 catch { }
                 try
                 {
                     StaticDirectoryPaths = LoadArray(json["static_directories"]);
                 }
                 catch { }
                 try
                 {
                     DLLPaths = LoadArray(json["dlls"]);
                 }
                 catch { }
             }
Member Function Documentation
override bool TGServerService.TGStationServer.RepoConfig.Equals (object obj)
Definition at line 102 of file Repository.cs.
             {
                 return Equals(obj as RepoConfig);
             }
bool TGServerService.TGStationServer.RepoConfig.Equals (RepoConfig other)
Definition at line 112 of file Repository.cs.
References TGServerService.TGStationServer.RepoConfig.ChangelogPyArguments, TGServerService.TGStationServer.RepoConfig.ChangelogSupport, TGServerService.TGStationServer.RepoConfig.DLLPaths, TGServerService.TGStationServer.RepoConfig.ListEquals(), TGServerService.TGStationServer.RepoConfig.PathsToStage, TGServerService.TGStationServer.RepoConfig.PathToChangelogPy, TGServerService.TGStationServer.RepoConfig.PipDependancies, and TGServerService.TGStationServer.RepoConfig.StaticDirectoryPaths.
             {
                 return ChangelogSupport == other.ChangelogSupport
                     && PathToChangelogPy == other.PathToChangelogPy
                     && ChangelogPyArguments == other.ChangelogPyArguments
                     && ListEquals(PipDependancies, other.PipDependancies)
                     && ListEquals(PathsToStage, other.PathsToStage)
                     && ListEquals(StaticDirectoryPaths, other.StaticDirectoryPaths)
                     && ListEquals(DLLPaths, other.DLLPaths);
             }
override int TGServerService.TGStationServer.RepoConfig.GetHashCode ()
Definition at line 123 of file Repository.cs.
             {
                 var hashCode = 1890628544;
                 hashCode = hashCode * -1521134295 + ChangelogSupport.GetHashCode();
                 hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(PathToChangelogPy);
                 hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(ChangelogPyArguments);
                 hashCode = hashCode * -1521134295 + EqualityComparer<IList<string>>.Default.GetHashCode(PipDependancies);
                 hashCode = hashCode * -1521134295 + EqualityComparer<IList<string>>.Default.GetHashCode(PathsToStage);
                 hashCode = hashCode * -1521134295 + EqualityComparer<IList<string>>.Default.GetHashCode(StaticDirectoryPaths);
                 hashCode = hashCode * -1521134295 + EqualityComparer<IList<string>>.Default.GetHashCode(DLLPaths);
                 return hashCode;
             }
static bool TGServerService.TGStationServer.RepoConfig.ListEquals (IList< string > A, IList< string > B) static private
Definition at line 107 of file Repository.cs.
Referenced by TGServerService.TGStationServer.RepoConfig.Equals().
             {
                 return A.All(B.Contains) && A.Count == B.Count;
             }
static IList<string> TGServerService.TGStationServer.RepoConfig.LoadArray (object o) static private
Definition at line 93 of file Repository.cs.
Referenced by TGServerService.TGStationServer.RepoConfig.RepoConfig().
             {
                 var array = (object[])o;
                 var res = new List<string>();
                 foreach (var I in array)
                     res.Add((string)I);
                 return res;
             }
static bool TGServerService.TGStationServer.RepoConfig.operator!= (RepoConfig config1, RepoConfig config2) static
Definition at line 141 of file Repository.cs.
             {
                 return !(config1 == config2);
             }
static bool TGServerService.TGStationServer.RepoConfig.operator== (RepoConfig config1, RepoConfig config2) static
Definition at line 136 of file Repository.cs.
             {
                 return EqualityComparer<RepoConfig>.Default.Equals(config1, config2);
             }
Member Data Documentation
readonly string TGServerService.TGStationServer.RepoConfig.ChangelogPyArguments
Definition at line 48 of file Repository.cs.
Referenced by TGServerService.TGStationServer.RepoConfig.Equals().
readonly bool TGServerService.TGStationServer.RepoConfig.ChangelogSupport
Definition at line 46 of file Repository.cs.
Referenced by TGServerService.TGStationServer.RepoConfig.Equals().
readonly IList<string> TGServerService.TGStationServer.RepoConfig.DLLPaths = new List<string>()
Definition at line 52 of file Repository.cs.
Referenced by TGServerService.TGStationServer.RepoConfig.Equals().
readonly IList<string> TGServerService.TGStationServer.RepoConfig.PathsToStage = new List<string>()
Definition at line 50 of file Repository.cs.
Referenced by TGServerService.TGStationServer.Commit(), and TGServerService.TGStationServer.RepoConfig.Equals().
readonly string TGServerService.TGStationServer.RepoConfig.PathToChangelogPy
Definition at line 47 of file Repository.cs.
Referenced by TGServerService.TGStationServer.RepoConfig.Equals().
readonly IList<string> TGServerService.TGStationServer.RepoConfig.PipDependancies = new List<string>()
Definition at line 49 of file Repository.cs.
Referenced by TGServerService.TGStationServer.RepoConfig.Equals().
readonly IList<string> TGServerService.TGStationServer.RepoConfig.StaticDirectoryPaths = new List<string>()
Definition at line 51 of file Repository.cs.
Referenced by TGServerService.TGStationServer.RepoConfig.Equals().
The documentation for this class was generated from the following file:
TGServerService/Repository.cs