tgstation-server: TGControlPanel.InstanceSelector Class Reference
TGControlPanel.InstanceSelector Class Reference
Form used for managing ITGSService ITGInstance manipulation functions
Public Member Functions
InstanceSelector (IInterface I)
Construct an InstanceSelector
Public Member Functions inherited from TGControlPanel.CountedForm
CountedForm ()
Construct a CountedForm. Increments FormCount
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
Task WrapServerOp (Action action)
Used to wrap Interface calls in a non-blocking fashion
void InstanceListBox_MouseDoubleClick (object sender, MouseEventArgs e)
Connects to a ITGInstance if it is double clicked in InstanceListBox
InstanceMetadata GetSelectedInstanceMetadata ()
Returns the InstanceMetadata associated with InstanceListBox's current selected index
void Cleanup ()
Called by Dispose(bool)
async void RefreshInstances ()
Loads the InstanceListBox using ITGLanding.ListInstances
async void TryConnectToIndexInstance (int index)
Tries to start a ControlPanel for a given InstanceListBox index
async void DetachInstanceButton_Click (object sender, EventArgs e)
Prompts the user for parameters to ITGInstanceManager.DetachInstance(string)
void RefreshButton_Click (object sender, EventArgs e)
Calls RefreshInstances
async void RenameInstanceButton_Click (object sender, EventArgs e)
Prompts the user for parameters to ITGInstanceManager.RenameInstance(string, string)
async void ImportInstanceButton_Click (object sender, EventArgs e)
Prompts the user for parameters to ITGInstanceManager.ImportInstance(string)
async void CreateInstanceButton_Click (object sender, EventArgs e)
Prompts the user for parameters to ITGInstanceManager.CreateInstance(string, string)
void ConnectButton_Click (object sender, EventArgs e)
Attempts to connect the user to an ITGInstance based on the ListBox.SelectedIndex of InstanceListBox
async void EnabledCheckBox_CheckedChanged (object sender, EventArgs e)
Prompts the user if they want to call ITGInstanceManager.SetInstanceEnabled(string, bool) to either online or offline an ITGInstance based on its current state
void InstanceListBox_SelectedIndexChanged (object sender, EventArgs e)
Update EnabledCheckBox based on the selected ITGInstance's InstanceMetadata.Enabled property
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
readonly IInterface masterInterface
The IInterface we build instance connections from
IList< InstanceMetadata > InstanceData
List of InstanceMetadata from masterInterface
bool UpdatingEnabledCheckbox = false
Used for modifying EnabledCheckBox without invoking its side effects
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.ListBox InstanceListBox
System.Windows.Forms.Button CreateInstanceButton
System.Windows.Forms.Button ImportInstanceButton
System.Windows.Forms.Button RenameInstanceButton
System.Windows.Forms.Button DetachInstanceButton
System.Windows.Forms.Button RefreshButton
System.Windows.Forms.Button ConnectButton
System.Windows.Forms.CheckBox EnabledCheckBox
Detailed Description
Form used for managing ITGSService ITGInstance manipulation functions
Definition at line 13 of file InstanceSelector.cs.
Constructor & Destructor Documentation
TGControlPanel.InstanceSelector.InstanceSelector (IInterface I)
Construct an InstanceSelector
Parameters
I An IInterface connected a the ITGSService
Definition at line 32 of file InstanceSelector.cs.
References TGControlPanel.InstanceSelector.InitializeComponent(), TGControlPanel.InstanceSelector.InstanceListBox, TGControlPanel.InstanceSelector.InstanceListBox_MouseDoubleClick(), and TGControlPanel.InstanceSelector.RefreshInstances().
         {
             InitializeComponent();
             InstanceListBox.MouseDoubleClick += InstanceListBox_MouseDoubleClick;
             masterInterface = I;
             RefreshInstances();
         }
Member Function Documentation
void TGControlPanel.InstanceSelector.Cleanup () private
Called by Dispose(bool)
Definition at line 82 of file InstanceSelector.cs.
Referenced by TGControlPanel.InstanceSelector.Dispose().
         {
             masterInterface.Dispose();
         }
void TGControlPanel.InstanceSelector.ConnectButton_Click (object sender, EventArgs e) private
Attempts to connect the user to an ITGInstance based on the ListBox.SelectedIndex of InstanceListBox
Parameters
sender The sender of the event
e The EventArgs
Definition at line 237 of file InstanceSelector.cs.
References TGControlPanel.InstanceSelector.InstanceListBox, and TGControlPanel.InstanceSelector.TryConnectToIndexInstance().
Referenced by TGControlPanel.InstanceSelector.InitializeComponent().
         {
             TryConnectToIndexInstance(InstanceListBox.SelectedIndex);
         }
async void TGControlPanel.InstanceSelector.CreateInstanceButton_Click (object sender, EventArgs e) private
Prompts the user for parameters to ITGInstanceManager.CreateInstance(string, string)
Parameters
sender The sender of the event
e The EventArgs
Definition at line 217 of file InstanceSelector.cs.
References TGServiceInterface.Components.ITGInstanceManager.CreateInstance(), TGControlPanel.InstanceSelector.RefreshInstances(), TGControlPanel.Program.TextPrompt(), and TGControlPanel.InstanceSelector.WrapServerOp().
Referenced by TGControlPanel.InstanceSelector.InitializeComponent().
         {
             var instance_name = Program.TextPrompt("Instance Creation", "Enter the name of the instance:");
             if (instance_name == null)
                 return;
             var instance_path = Program.TextPrompt("Instance Creation", "Enter the full path to the instance:");
             if (instance_path == null)
                 return;
             string res = null;
             await WrapServerOp(() => res = masterInterface.GetServiceComponent<ITGInstanceManager>().CreateInstance(instance_name, instance_path));
             if (res != null)
                 MessageBox.Show(res);
             RefreshInstances();
         }
async void TGControlPanel.InstanceSelector.DetachInstanceButton_Click (object sender, EventArgs e) private
Prompts the user for parameters to ITGInstanceManager.DetachInstance(string)
Parameters
sender The sender of the event
e The EventArgs
Definition at line 149 of file InstanceSelector.cs.
References TGServiceInterface.Components.ITGInstanceManager.DetachInstance(), TGControlPanel.InstanceSelector.GetSelectedInstanceMetadata(), TGControlPanel.InstanceSelector.RefreshInstances(), and TGControlPanel.InstanceSelector.WrapServerOp().
Referenced by TGControlPanel.InstanceSelector.InitializeComponent().
         {
             var imd = GetSelectedInstanceMetadata();
             if (imd == null)
                 return;
             if (MessageBox.Show(String.Format("This will dissociate the server instance at \"{0}\"! Are you sure?", imd.Path), "Instance Detach", MessageBoxButtons.YesNo) != DialogResult.Yes)
                 return;
             string res = null;
             await WrapServerOp(() => res = masterInterface.GetServiceComponent<ITGInstanceManager>().DetachInstance(imd.Name));
             if (res != null)
                 MessageBox.Show(res);
             RefreshInstances();
         }
override void TGControlPanel.InstanceSelector.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file InstanceSelector.Designer.cs.
References TGControlPanel.InstanceSelector.Cleanup(), and TGControlPanel.InstanceSelector.components.
         {
             if (disposing && (components != null))
             {
                 Cleanup();
                 components.Dispose();
             }
             base.Dispose(disposing);
         }
async void TGControlPanel.InstanceSelector.EnabledCheckBox_CheckedChanged (object sender, EventArgs e) private
Prompts the user if they want to call ITGInstanceManager.SetInstanceEnabled(string, bool) to either online or offline an ITGInstance based on its current state
Parameters
sender The sender of the event
e The EventArgs
Definition at line 247 of file InstanceSelector.cs.
References TGControlPanel.InstanceSelector.EnabledCheckBox, TGControlPanel.InstanceSelector.InstanceListBox, TGControlPanel.InstanceSelector.RefreshInstances(), TGServiceInterface.Components.ITGInstanceManager.SetInstanceEnabled(), and TGControlPanel.InstanceSelector.WrapServerOp().
Referenced by TGControlPanel.InstanceSelector.InitializeComponent().
         {
             if (UpdatingEnabledCheckbox)
                 return;
             var enabling = EnabledCheckBox.Checked;
             try
             {
                 if (MessageBox.Show(String.Format("Are you sure you want to {0} this instance?", enabling ? "online" : "offline"), "Instance Status Change", MessageBoxButtons.YesNo) != DialogResult.Yes)
                     return;
                 string res = null;
                 var index = InstanceListBox.SelectedIndex;
                 await WrapServerOp(() => res = masterInterface.GetServiceComponent<ITGInstanceManager>().SetInstanceEnabled(InstanceData[index].Name, enabling));
                 if (res != null)
                     MessageBox.Show(res);
             }
             finally
             {
                 RefreshInstances();
             }
         }
InstanceMetadata TGControlPanel.InstanceSelector.GetSelectedInstanceMetadata () private
Returns the InstanceMetadata associated with InstanceListBox's current selected index
Returns
The InstanceMetadata associated with InstanceListBox's current selected index if it exists, otherwise
Definition at line 73 of file InstanceSelector.cs.
References TGControlPanel.InstanceSelector.InstanceListBox.
Referenced by TGControlPanel.InstanceSelector.DetachInstanceButton_Click(), and TGControlPanel.InstanceSelector.RenameInstanceButton_Click().
         {
             var index = InstanceListBox.SelectedIndex;
             return index != ListBox.NoMatches ? InstanceData[index] : null;
         }
async void TGControlPanel.InstanceSelector.ImportInstanceButton_Click (object sender, EventArgs e) private
Prompts the user for parameters to ITGInstanceManager.ImportInstance(string)
Parameters
sender The sender of the event
e The EventArgs
Definition at line 200 of file InstanceSelector.cs.
References TGServiceInterface.Components.ITGInstanceManager.ImportInstance(), TGControlPanel.InstanceSelector.RefreshInstances(), TGControlPanel.Program.TextPrompt(), and TGControlPanel.InstanceSelector.WrapServerOp().
Referenced by TGControlPanel.InstanceSelector.InitializeComponent().
         {
             var instance_path = Program.TextPrompt("Instance Import", "Enter the full path to the instance:");
             if (instance_path == null)
                 return;
             string res = null;
             await WrapServerOp(() => res = masterInterface.GetServiceComponent<ITGInstanceManager>().ImportInstance(instance_path));
             if (res != null)
                 MessageBox.Show(res);
             RefreshInstances();
         }
void TGControlPanel.InstanceSelector.InitializeComponent () private
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 30 of file InstanceSelector.Designer.cs.
References TGControlPanel.InstanceSelector.ConnectButton, TGControlPanel.InstanceSelector.ConnectButton_Click(), TGControlPanel.InstanceSelector.CreateInstanceButton, TGControlPanel.InstanceSelector.CreateInstanceButton_Click(), TGControlPanel.InstanceSelector.DetachInstanceButton, TGControlPanel.InstanceSelector.DetachInstanceButton_Click(), TGControlPanel.InstanceSelector.EnabledCheckBox, TGControlPanel.InstanceSelector.EnabledCheckBox_CheckedChanged(), TGControlPanel.InstanceSelector.ImportInstanceButton, TGControlPanel.InstanceSelector.ImportInstanceButton_Click(), TGControlPanel.InstanceSelector.InstanceListBox, TGControlPanel.InstanceSelector.InstanceListBox_SelectedIndexChanged(), TGControlPanel.InstanceSelector.RefreshButton, TGControlPanel.InstanceSelector.RefreshButton_Click(), TGControlPanel.InstanceSelector.RenameInstanceButton, and TGControlPanel.InstanceSelector.RenameInstanceButton_Click().
Referenced by TGControlPanel.InstanceSelector.InstanceSelector().
         {
             System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(InstanceSelector));
             this.InstanceListBox = new System.Windows.Forms.ListBox();
             this.CreateInstanceButton = new System.Windows.Forms.Button();
             this.ImportInstanceButton = new System.Windows.Forms.Button();
             this.RenameInstanceButton = new System.Windows.Forms.Button();
             this.DetachInstanceButton = new System.Windows.Forms.Button();
             this.RefreshButton = new System.Windows.Forms.Button();
             this.ConnectButton = new System.Windows.Forms.Button();
             this.EnabledCheckBox = new System.Windows.Forms.CheckBox();
             this.SuspendLayout();
             //
             // InstanceListBox
             //
             this.InstanceListBox.Anchor = System.Windows.Forms.AnchorStyles.Left;
             this.InstanceListBox.FormattingEnabled = true;
             this.InstanceListBox.Location = new System.Drawing.Point(13, 13);
             this.InstanceListBox.Name = "InstanceListBox";
             this.InstanceListBox.Size = new System.Drawing.Size(339, 238);
             this.InstanceListBox.TabIndex = 0;
             this.InstanceListBox.SelectedIndexChanged += new System.EventHandler(this.InstanceListBox_SelectedIndexChanged);
             //
             // CreateInstanceButton
             //
             this.CreateInstanceButton.Anchor = System.Windows.Forms.AnchorStyles.Right;
             this.CreateInstanceButton.Location = new System.Drawing.Point(358, 15);
             this.CreateInstanceButton.Name = "CreateInstanceButton";
             this.CreateInstanceButton.Size = new System.Drawing.Size(148, 25);
             this.CreateInstanceButton.TabIndex = 14;
             this.CreateInstanceButton.Text = "Create Instance";
             this.CreateInstanceButton.UseVisualStyleBackColor = true;
             this.CreateInstanceButton.Click += new System.EventHandler(this.CreateInstanceButton_Click);
             //
             // ImportInstanceButton
             //
             this.ImportInstanceButton.Anchor = System.Windows.Forms.AnchorStyles.Right;
             this.ImportInstanceButton.Location = new System.Drawing.Point(358, 45);
             this.ImportInstanceButton.Name = "ImportInstanceButton";
             this.ImportInstanceButton.Size = new System.Drawing.Size(148, 25);
             this.ImportInstanceButton.TabIndex = 15;
             this.ImportInstanceButton.Text = "Import Instance";
             this.ImportInstanceButton.UseVisualStyleBackColor = true;
             this.ImportInstanceButton.Click += new System.EventHandler(this.ImportInstanceButton_Click);
             //
             // RenameInstanceButton
             //
             this.RenameInstanceButton.Anchor = System.Windows.Forms.AnchorStyles.Right;
             this.RenameInstanceButton.Location = new System.Drawing.Point(358, 76);
             this.RenameInstanceButton.Name = "RenameInstanceButton";
             this.RenameInstanceButton.Size = new System.Drawing.Size(148, 25);
             this.RenameInstanceButton.TabIndex = 16;
             this.RenameInstanceButton.Text = "Rename Instance";
             this.RenameInstanceButton.UseVisualStyleBackColor = true;
             this.RenameInstanceButton.Click += new System.EventHandler(this.RenameInstanceButton_Click);
             //
             // DetachInstanceButton
             //
             this.DetachInstanceButton.Anchor = System.Windows.Forms.AnchorStyles.Right;
             this.DetachInstanceButton.Location = new System.Drawing.Point(358, 107);
             this.DetachInstanceButton.Name = "DetachInstanceButton";
             this.DetachInstanceButton.Size = new System.Drawing.Size(148, 25);
             this.DetachInstanceButton.TabIndex = 17;
             this.DetachInstanceButton.Text = "Detach Instance";
             this.DetachInstanceButton.UseVisualStyleBackColor = true;
             this.DetachInstanceButton.Click += new System.EventHandler(this.DetachInstanceButton_Click);
             //
             // RefreshButton
             //
             this.RefreshButton.Anchor = System.Windows.Forms.AnchorStyles.Right;
             this.RefreshButton.Location = new System.Drawing.Point(358, 195);
             this.RefreshButton.Name = "RefreshButton";
             this.RefreshButton.Size = new System.Drawing.Size(148, 25);
             this.RefreshButton.TabIndex = 19;
             this.RefreshButton.Text = "Refresh";
             this.RefreshButton.UseVisualStyleBackColor = true;
             this.RefreshButton.Click += new System.EventHandler(this.RefreshButton_Click);
             //
             // ConnectButton
             //
             this.ConnectButton.Anchor = System.Windows.Forms.AnchorStyles.Right;
             this.ConnectButton.Location = new System.Drawing.Point(358, 226);
             this.ConnectButton.Name = "ConnectButton";
             this.ConnectButton.Size = new System.Drawing.Size(148, 25);
             this.ConnectButton.TabIndex = 20;
             this.ConnectButton.Text = "Connect";
             this.ConnectButton.UseVisualStyleBackColor = true;
             this.ConnectButton.Click += new System.EventHandler(this.ConnectButton_Click);
             //
             // EnabledCheckBox
             //
             this.EnabledCheckBox.AutoSize = true;
             this.EnabledCheckBox.ForeColor = System.Drawing.Color.White;
             this.EnabledCheckBox.Location = new System.Drawing.Point(396, 149);
             this.EnabledCheckBox.Name = "EnabledCheckBox";
             this.EnabledCheckBox.Size = new System.Drawing.Size(65, 17);
             this.EnabledCheckBox.TabIndex = 21;
             this.EnabledCheckBox.Text = "Enabled";
             this.EnabledCheckBox.UseVisualStyleBackColor = true;
             this.EnabledCheckBox.CheckedChanged += new System.EventHandler(this.EnabledCheckBox_CheckedChanged);
             //
             // InstanceSelector
             //
             this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
             this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
             this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(40)))), ((int)(((byte)(34)))));
             this.ClientSize = new System.Drawing.Size(518, 261);
             this.Controls.Add(this.EnabledCheckBox);
             this.Controls.Add(this.ConnectButton);
             this.Controls.Add(this.RefreshButton);
             this.Controls.Add(this.DetachInstanceButton);
             this.Controls.Add(this.RenameInstanceButton);
             this.Controls.Add(this.ImportInstanceButton);
             this.Controls.Add(this.CreateInstanceButton);
             this.Controls.Add(this.InstanceListBox);
             this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
             this.Name = "InstanceSelector";
             this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
             this.Text = "Server Instances";
             this.ResumeLayout(false);
             this.PerformLayout();
         }
void TGControlPanel.InstanceSelector.InstanceListBox_MouseDoubleClick (object sender, MouseEventArgs e) private
Connects to a ITGInstance if it is double clicked in InstanceListBox
Parameters
sender The sender of the event
e The MouseEventArgs
Definition at line 64 of file InstanceSelector.cs.
References TGControlPanel.InstanceSelector.InstanceListBox, and TGControlPanel.InstanceSelector.TryConnectToIndexInstance().
Referenced by TGControlPanel.InstanceSelector.InstanceSelector().
         {
             TryConnectToIndexInstance(InstanceListBox.IndexFromPoint(e.Location));
         }
void TGControlPanel.InstanceSelector.InstanceListBox_SelectedIndexChanged (object sender, EventArgs e) private
Update EnabledCheckBox based on the selected ITGInstance's InstanceMetadata.Enabled property
Parameters
sender The sender of the event
e The EventArgs
Definition at line 273 of file InstanceSelector.cs.
References TGControlPanel.InstanceSelector.EnabledCheckBox, and TGControlPanel.InstanceSelector.InstanceListBox.
Referenced by TGControlPanel.InstanceSelector.InitializeComponent().
         {
             var index = InstanceListBox.SelectedIndex;
             if (index != ListBox.NoMatches)
             {
                 UpdatingEnabledCheckbox = true;
                 EnabledCheckBox.Checked = InstanceData[index].Enabled;
                 UpdatingEnabledCheckbox = false;
             }
         }
void TGControlPanel.InstanceSelector.RefreshButton_Click (object sender, EventArgs e) private
Calls RefreshInstances
Parameters
sender The sender of the event
e The EventArgs
Definition at line 168 of file InstanceSelector.cs.
References TGControlPanel.InstanceSelector.RefreshInstances().
Referenced by TGControlPanel.InstanceSelector.InitializeComponent().
         {
             RefreshInstances();
         }
async void TGControlPanel.InstanceSelector.RefreshInstances () private
Loads the InstanceListBox using ITGLanding.ListInstances
Definition at line 90 of file InstanceSelector.cs.
References TGControlPanel.InstanceSelector.CreateInstanceButton, TGControlPanel.InstanceSelector.DetachInstanceButton, TGControlPanel.InstanceSelector.EnabledCheckBox, TGControlPanel.InstanceSelector.ImportInstanceButton, TGControlPanel.InstanceSelector.InstanceListBox, TGControlPanel.InstanceSelector.RenameInstanceButton, and TGControlPanel.InstanceSelector.WrapServerOp().
Referenced by TGControlPanel.InstanceSelector.CreateInstanceButton_Click(), TGControlPanel.InstanceSelector.DetachInstanceButton_Click(), TGControlPanel.InstanceSelector.EnabledCheckBox_CheckedChanged(), TGControlPanel.InstanceSelector.ImportInstanceButton_Click(), TGControlPanel.InstanceSelector.InstanceSelector(), TGControlPanel.InstanceSelector.RefreshButton_Click(), TGControlPanel.InstanceSelector.RenameInstanceButton_Click(), and TGControlPanel.InstanceSelector.TryConnectToIndexInstance().
         {
             InstanceListBox.Items.Clear();
             await WrapServerOp(() => {
                 InstanceData = masterInterface.GetServiceComponent<ITGLanding>().ListInstances();
             });
             foreach(var I in InstanceData)
                 InstanceListBox.Items.Add(String.Format("{0}: {1} - {2} - {3}", I.LoggingID, I.Name, I.Path, I.Enabled ? "ONLINE" : "OFFLINE"));
             var HasServerAdmin = masterInterface.ConnectionStatus().HasFlag(ConnectivityLevel.Administrator);
             CreateInstanceButton.Enabled = HasServerAdmin;
             ImportInstanceButton.Enabled = HasServerAdmin;
             RenameInstanceButton.Enabled = HasServerAdmin;
             DetachInstanceButton.Enabled = HasServerAdmin;
             EnabledCheckBox.Enabled = HasServerAdmin;
             if(InstanceData.Count > 0)
                 InstanceListBox.SelectedIndex = 0;
         }
async void TGControlPanel.InstanceSelector.RenameInstanceButton_Click (object sender, EventArgs e) private
Prompts the user for parameters to ITGInstanceManager.RenameInstance(string, string)
Parameters
sender The sender of the event
e The EventArgs
Definition at line 178 of file InstanceSelector.cs.
References TGControlPanel.InstanceSelector.GetSelectedInstanceMetadata(), TGControlPanel.InstanceSelector.RefreshInstances(), TGServiceInterface.Components.ITGInstanceManager.RenameInstance(), TGControlPanel.Program.TextPrompt(), and TGControlPanel.InstanceSelector.WrapServerOp().
Referenced by TGControlPanel.InstanceSelector.InitializeComponent().
         {
             var imd = GetSelectedInstanceMetadata();
             if (imd == null)
                 return;
             var new_name = Program.TextPrompt("Instance Rename", "Enter a new name for the instance:");
             if (new_name == null)
                 return;
             if (imd.Enabled && MessageBox.Show(String.Format("This will temporarily offline the server instance! Are you sure?", imd.Path), "Instance Restart", MessageBoxButtons.YesNo) != DialogResult.Yes)
                 return;
             string res = null;
             await WrapServerOp(() => res = masterInterface.GetServiceComponent<ITGInstanceManager>().RenameInstance(imd.Name, new_name));
             if (res != null)
                 MessageBox.Show(res);
             RefreshInstances();
         }
async void TGControlPanel.InstanceSelector.TryConnectToIndexInstance (int index) private
Tries to start a ControlPanel for a given InstanceListBox index
Parameters
index The ListBox.SelectedIndex of InstanceListBox to connect to
Definition at line 112 of file InstanceSelector.cs.
References TGControlPanel.ControlPanel.Dispose(), TGControlPanel.ControlPanel.InstancesInUse, TGControlPanel.InstanceSelector.RefreshInstances(), and TGControlPanel.InstanceSelector.WrapServerOp().
Referenced by TGControlPanel.InstanceSelector.ConnectButton_Click(), and TGControlPanel.InstanceSelector.InstanceListBox_MouseDoubleClick().
         {
             if (index == ListBox.NoMatches)
                 return;
             var instanceName = InstanceData[index].Name;
             if (ControlPanel.InstancesInUse.TryGetValue(instanceName, out ControlPanel activeCP))
             {
                 activeCP.BringToFront();
                 return;
             }
             var InstanceAccessor = new Interface(masterInterface as Interface);
             try
             {
                 ConnectivityLevel res = ConnectivityLevel.None;
                 await WrapServerOp(() => { res = InstanceAccessor.ConnectToInstance(instanceName); });
                 if (!res.HasFlag(ConnectivityLevel.Connected))
                 {
                     MessageBox.Show("Unable to connect to instance! Does it exist?");
                     RefreshInstances();
                 }
                 else if (!res.HasFlag(ConnectivityLevel.Authenticated))
                     MessageBox.Show("The current user is not authorized to access this instance!");
                 else
                     new ControlPanel(InstanceAccessor).Show();
             }
             catch
             {
                 InstanceAccessor.Dispose();
                 throw;
             }
         }
Task TGControlPanel.InstanceSelector.WrapServerOp (Action action) private
Used to wrap Interface calls in a non-blocking fashion
Parameters
action The Interface operation to wrap
Definition at line 44 of file InstanceSelector.cs.
Referenced by TGControlPanel.InstanceSelector.CreateInstanceButton_Click(), TGControlPanel.InstanceSelector.DetachInstanceButton_Click(), TGControlPanel.InstanceSelector.EnabledCheckBox_CheckedChanged(), TGControlPanel.InstanceSelector.ImportInstanceButton_Click(), TGControlPanel.InstanceSelector.RefreshInstances(), TGControlPanel.InstanceSelector.RenameInstanceButton_Click(), and TGControlPanel.InstanceSelector.TryConnectToIndexInstance().
         {
             Enabled = false;
             UseWaitCursor = true;
             try
             {
                 return Task.Factory.StartNew(action);
             }
             finally
             {
                 Enabled = true;
                 UseWaitCursor = false;
             }
         }
Member Data Documentation
System.ComponentModel.IContainer TGControlPanel.InstanceSelector.components = null private
Required designer variable.
Definition at line 8 of file InstanceSelector.Designer.cs.
Referenced by TGControlPanel.InstanceSelector.Dispose().
System.Windows.Forms.Button TGControlPanel.InstanceSelector.ConnectButton private
Definition at line 162 of file InstanceSelector.Designer.cs.
Referenced by TGControlPanel.InstanceSelector.InitializeComponent().
System.Windows.Forms.Button TGControlPanel.InstanceSelector.CreateInstanceButton private
Definition at line 157 of file InstanceSelector.Designer.cs.
Referenced by TGControlPanel.InstanceSelector.InitializeComponent(), and TGControlPanel.InstanceSelector.RefreshInstances().
System.Windows.Forms.Button TGControlPanel.InstanceSelector.DetachInstanceButton private
Definition at line 160 of file InstanceSelector.Designer.cs.
Referenced by TGControlPanel.InstanceSelector.InitializeComponent(), and TGControlPanel.InstanceSelector.RefreshInstances().
System.Windows.Forms.CheckBox TGControlPanel.InstanceSelector.EnabledCheckBox private
Definition at line 163 of file InstanceSelector.Designer.cs.
Referenced by TGControlPanel.InstanceSelector.EnabledCheckBox_CheckedChanged(), TGControlPanel.InstanceSelector.InitializeComponent(), TGControlPanel.InstanceSelector.InstanceListBox_SelectedIndexChanged(), and TGControlPanel.InstanceSelector.RefreshInstances().
System.Windows.Forms.Button TGControlPanel.InstanceSelector.ImportInstanceButton private
Definition at line 158 of file InstanceSelector.Designer.cs.
Referenced by TGControlPanel.InstanceSelector.InitializeComponent(), and TGControlPanel.InstanceSelector.RefreshInstances().
IList<InstanceMetadata> TGControlPanel.InstanceSelector.InstanceData private
List of InstanceMetadata from masterInterface
Definition at line 22 of file InstanceSelector.cs.
System.Windows.Forms.ListBox TGControlPanel.InstanceSelector.InstanceListBox private
Definition at line 156 of file InstanceSelector.Designer.cs.
Referenced by TGControlPanel.InstanceSelector.ConnectButton_Click(), TGControlPanel.InstanceSelector.EnabledCheckBox_CheckedChanged(), TGControlPanel.InstanceSelector.GetSelectedInstanceMetadata(), TGControlPanel.InstanceSelector.InitializeComponent(), TGControlPanel.InstanceSelector.InstanceListBox_MouseDoubleClick(), TGControlPanel.InstanceSelector.InstanceListBox_SelectedIndexChanged(), TGControlPanel.InstanceSelector.InstanceSelector(), and TGControlPanel.InstanceSelector.RefreshInstances().
readonly IInterface TGControlPanel.InstanceSelector.masterInterface private
The IInterface we build instance connections from
Definition at line 18 of file InstanceSelector.cs.
System.Windows.Forms.Button TGControlPanel.InstanceSelector.RefreshButton private
Definition at line 161 of file InstanceSelector.Designer.cs.
Referenced by TGControlPanel.InstanceSelector.InitializeComponent().
System.Windows.Forms.Button TGControlPanel.InstanceSelector.RenameInstanceButton private
Definition at line 159 of file InstanceSelector.Designer.cs.
Referenced by TGControlPanel.InstanceSelector.InitializeComponent(), and TGControlPanel.InstanceSelector.RefreshInstances().
bool TGControlPanel.InstanceSelector.UpdatingEnabledCheckbox = false private
Used for modifying EnabledCheckBox without invoking its side effects
Definition at line 26 of file InstanceSelector.cs.
The documentation for this class was generated from the following files:
TGControlPanel/InstanceSelector.cs
TGControlPanel/InstanceSelector.Designer.cs