tgstation-server: Tgstation.Server.Host.Components.Byond.WindowsByondInstaller Class Reference
Tgstation.Server.Host.Components.Byond.WindowsByondInstaller Class Reference
IByondInstaller for windows systems.
Public Member Functions
WindowsByondInstaller (IProcessExecutor processExecutor, IIOManager ioManager, IOptions< GeneralConfiguration > generalConfigurationOptions, ILogger< WindowsByondInstaller > logger)
Initializes a new instance of the WindowsByondInstaller class.
void Dispose ()
override string GetDreamDaemonName (Version version, out bool supportsCli)
Get the file name of the DreamDaemon executable.
Parameters
version The Version of BYOND to select the executable name for.
supportsCli Whether or not the returned path supports being run as a command-line application.
Returns
The file name of the DreamDaemon executable.
override Task InstallByond (Version version, string path, CancellationToken cancellationToken)
Does actions necessary to get an extracted BYOND installation working.
Parameters
version The Version of BYOND being installed.
path The path to the BYOND installation.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
override async Task UpgradeInstallation (Version version, string path, CancellationToken cancellationToken)
Does actions necessary to get upgrade a BYOND version installed by a previous version of TGS.
Parameters
version The Version of BYOND being installed.
path The path to the BYOND installation.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Public Member Functions inherited from Tgstation.Server.Host.Components.Byond.ByondInstallerBase
abstract string GetDreamDaemonName (Version version, out bool supportsCli)
Get the file name of the DreamDaemon executable.
Parameters
version The Version of BYOND to select the executable name for.
supportsCli Whether or not the returned path supports being run as a command-line application.
Returns
The file name of the DreamDaemon executable.
async Task CleanCache (CancellationToken cancellationToken)
Attempts to cleans the BYOND cache folder for the system.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
abstract Task InstallByond (Version version, string path, CancellationToken cancellationToken)
Does actions necessary to get an extracted BYOND installation working.
Parameters
version The Version of BYOND being installed.
path The path to the BYOND installation.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
abstract Task UpgradeInstallation (Version version, string path, CancellationToken cancellationToken)
Does actions necessary to get upgrade a BYOND version installed by a previous version of TGS.
Parameters
version The Version of BYOND being installed.
path The path to the BYOND installation.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Task< MemoryStream > DownloadVersion (Version version, CancellationToken cancellationToken)
Download a given BYOND version .
Parameters
version The Version of BYOND to download.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in a MemoryStream of the zipfile.
string GetDreamDaemonName (Version version, out bool supportsCli)
Get the file name of the DreamDaemon executable.
Task< MemoryStream > DownloadVersion (Version version, CancellationToken cancellationToken)
Download a given BYOND version .
Task InstallByond (Version version, string path, CancellationToken cancellationToken)
Does actions necessary to get an extracted BYOND installation working.
Task UpgradeInstallation (Version version, string path, CancellationToken cancellationToken)
Does actions necessary to get upgrade a BYOND version installed by a previous version of TGS.
Task CleanCache (CancellationToken cancellationToken)
Attempts to cleans the BYOND cache folder for the system.
Properties
override string DreamMakerName [get]
Get the file name of the DreamMaker executable.
override string PathToUserByondFolder [get]
The path to the BYOND folder for the user.
override string ByondRevisionsUrlTemplate [get]
Properties inherited from Tgstation.Server.Host.Components.Byond.ByondInstallerBase
abstract string DreamMakerName [get]
Get the file name of the DreamMaker executable.
abstract string PathToUserByondFolder [get]
The path to the BYOND folder for the user.
abstract string ByondRevisionsUrlTemplate [get]
Gets the URL formatter string for downloading a byond version of {0:Major} {1:Minor}.
IIOManager IOManager [get]
Gets the IIOManager for the ByondInstallerBase.
ILogger< ByondInstallerBase > Logger [get]
Gets the ILogger for the ByondInstallerBase.
Properties inherited from Tgstation.Server.Host.Components.Byond.IByondInstaller
string DreamMakerName [get]
Get the file name of the DreamMaker executable.
string PathToUserByondFolder [get]
The path to the BYOND folder for the user.
Private Member Functions
async Task SetNoPromptTrusted (string path, CancellationToken cancellationToken)
Creates the BYOND cfg file that prevents the trusted mode dialog from appearing when launching DreamDaemon.
async Task InstallDirectX (string path, CancellationToken cancellationToken)
Attempt to install the DirectX redistributable included with BYOND.
async Task AddDreamDaemonToFirewall (Version version, string path, CancellationToken cancellationToken)
Attempt to add the DreamDaemon executable as an exception to the Windows firewall.
Private Attributes
readonly IProcessExecutor processExecutor
The IProcessExecutor for the WindowsByondInstaller.
readonly GeneralConfiguration generalConfiguration
The GeneralConfiguration for the WindowsByondInstaller.
readonly SemaphoreSlim semaphore
The SemaphoreSlim for the WindowsByondInstaller.
bool installedDirectX
If DirectX was installed.
Static Private Attributes
const string ByondConfigDirectory = "byond/cfg"
Directory to byond installation configuration.
const string ByondDreamDaemonConfigFilename = "daemon.txt"
BYOND's DreamDaemon config file.
const string ByondNoPromptTrustedMode = "trusted-check 0"
Setting to add to ByondDreamDaemonConfigFilename to suppress an invisible user prompt for running a trusted mode .dmb.
const string ByondDXDir = "byond/directx"
The directory that contains the BYOND directx redistributable.
const string TgsFirewalledDDFile = "TGSFirewalledDD"
The file TGS uses to determine if dd.exe has been firewalled.
Additional Inherited Members
Protected Member Functions inherited from Tgstation.Server.Host.Components.Byond.ByondInstallerBase
ByondInstallerBase (IIOManager ioManager, ILogger< ByondInstallerBase > logger)
Initializes a new instance of the ByondInstallerBase class.
Detailed Description
IByondInstaller for windows systems.
Definition at line 22 of file WindowsByondInstaller.cs.
Constructor & Destructor Documentation
WindowsByondInstaller()
Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.WindowsByondInstaller (IProcessExecutor processExecutor, IIOManager ioManager, IOptions< GeneralConfiguration > generalConfigurationOptions, ILogger< WindowsByondInstaller > logger)
Initializes a new instance of the WindowsByondInstaller class.
Parameters
processExecutor The value of processExecutor.
generalConfigurationOptions The IOptions<TOptions> containing the value of generalConfiguration.
ioManager The IIOManager for the ByondInstallerBase.
logger The ILogger for the ByondInstallerBase.
Definition at line 85 of file WindowsByondInstaller.cs.
            : base(ioManager, logger)
        {
            this.processExecutor = processExecutor ?? throw new ArgumentNullException(nameof(processExecutor));
            generalConfiguration = generalConfigurationOptions?.Value ?? throw new ArgumentNullException(nameof(generalConfigurationOptions));
            PathToUserByondFolder = IOManager.ResolvePath(IOManager.ConcatPath(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments), "BYOND"));
            semaphore = new SemaphoreSlim(1);
            installedDirectX = false;
        }
References Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.generalConfiguration, Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.installedDirectX, Tgstation.Server.Host.Components.Byond.ByondInstallerBase.IOManager, Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.PathToUserByondFolder, Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.processExecutor, Tgstation.Server.Host.IO.IIOManager.ResolvePath(), and Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.semaphore.
Member Function Documentation
AddDreamDaemonToFirewall()
async Task Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.AddDreamDaemonToFirewall (Version version, string path, CancellationToken cancellationToken) private
Attempt to add the DreamDaemon executable as an exception to the Windows firewall.
Parameters
version The BYOND Version.
path The path to the BYOND installation.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Definition at line 218 of file WindowsByondInstaller.cs.
        {
            var dreamDaemonName = GetDreamDaemonName(version, out var supportsCli);
            var dreamDaemonPath = IOManager.ResolvePath(
                IOManager.ConcatPath(
                    path,
                    ByondManager.BinPath,
                    dreamDaemonName));
            Logger.LogInformation("Adding Windows Firewall exception for {path}...", dreamDaemonPath);
            try
            {
                await using var netshProcess = await processExecutor.LaunchProcess(
                    "netsh.exe",
                    IOManager.ResolvePath(),
                    $"advfirewall firewall add rule name=\"TGS DreamDaemon\" program=\"{dreamDaemonPath}\" protocol=tcp dir=in enable=yes action=allow",
                    readStandardHandles: true,
                    noShellExecute: true);
                int exitCode;
                using (cancellationToken.Register(() => netshProcess.Terminate()))
                    exitCode = await netshProcess.Lifetime;
                cancellationToken.ThrowIfCancellationRequested();
                Logger.LogDebug(
                    "netsh.exe output:{newLine}{output}",
                    Environment.NewLine,
                    await netshProcess.GetCombinedOutput(cancellationToken));
                if (exitCode != 0)
                    throw new JobException(ErrorCode.ByondDreamDaemonFirewallFail, new JobException($"Invalid exit code: {exitCode}"));
                if (supportsCli)
                    await IOManager.WriteAllBytes(
                        IOManager.ConcatPath(path, TgsFirewalledDDFile),
                        Array.Empty<byte>(),
                        cancellationToken);
            }
            catch (Exception ex)
            {
                throw new JobException(ErrorCode.ByondDreamDaemonFirewallFail, ex);
            }
        }
References Tgstation.Server.Host.Components.Byond.ByondManager.BinPath, Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.GetDreamDaemonName(), Tgstation.Server.Host.Components.Byond.ByondInstallerBase.IOManager, Tgstation.Server.Host.System.IProcessExecutor.LaunchProcess(), Tgstation.Server.Host.Components.Byond.ByondInstallerBase.Logger, Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.processExecutor, Tgstation.Server.Host.IO.IIOManager.ResolvePath(), Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.TgsFirewalledDDFile, and Tgstation.Server.Host.IO.IIOManager.WriteAllBytes().
Referenced by Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.InstallByond(), and Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.UpgradeInstallation().
Dispose()
void Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.Dispose ()
GetDreamDaemonName()
override string Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.GetDreamDaemonName (Version version, out bool supportsCli) virtual
Get the file name of the DreamDaemon executable.
Parameters
version The Version of BYOND to select the executable name for.
supportsCli Whether or not the returned path supports being run as a command-line application.
Returns
The file name of the DreamDaemon executable.
Implements Tgstation.Server.Host.Components.Byond.ByondInstallerBase.
Definition at line 101 of file WindowsByondInstaller.cs.
        {
            if (version == null)
                throw new ArgumentNullException(nameof(version));
            supportsCli = version.Major >= 515 && version.Minor >= 1598;
            return supportsCli ? "dd.exe" : "dreamdaemon.exe";
        }
Referenced by Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.AddDreamDaemonToFirewall(), and Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.UpgradeInstallation().
InstallByond()
override Task Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.InstallByond (Version version, string path, CancellationToken cancellationToken) virtual
Does actions necessary to get an extracted BYOND installation working.
Parameters
version The Version of BYOND being installed.
path The path to the BYOND installation.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implements Tgstation.Server.Host.Components.Byond.ByondInstallerBase.
Definition at line 111 of file WindowsByondInstaller.cs.
        {
            var tasks = new List<Task>
            {
                SetNoPromptTrusted(path, cancellationToken),
                InstallDirectX(path, cancellationToken),
            };
            if (!generalConfiguration.SkipAddingByondFirewallException)
                tasks.Add(AddDreamDaemonToFirewall(version, path, cancellationToken));
            return Task.WhenAll(tasks);
        }
References Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.AddDreamDaemonToFirewall(), Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.generalConfiguration, Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.InstallDirectX(), Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.SetNoPromptTrusted(), and Tgstation.Server.Host.Configuration.GeneralConfiguration.SkipAddingByondFirewallException.
InstallDirectX()
async Task Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.InstallDirectX (string path, CancellationToken cancellationToken) private
Attempt to install the DirectX redistributable included with BYOND.
Parameters
path The path to the BYOND installation.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Definition at line 173 of file WindowsByondInstaller.cs.
        {
            using var lockContext = await SemaphoreSlimContext.Lock(semaphore, cancellationToken);
            if (installedDirectX)
            {
                Logger.LogTrace("DirectX already installed.");
                return;
            }
            Logger.LogTrace("Installing DirectX redistributable...");
            // always install it, it's pretty fast and will do better redundancy checking than us
            var rbdx = IOManager.ConcatPath(path, ByondDXDir);
            try
            {
                // noShellExecute because we aren't doing runas shennanigans
                await using var directXInstaller = await processExecutor.LaunchProcess(
                    IOManager.ConcatPath(rbdx, "DXSETUP.exe"),
                    rbdx,
                    "/silent",
                    noShellExecute: true);
                int exitCode;
                using (cancellationToken.Register(() => directXInstaller.Terminate()))
                    exitCode = await directXInstaller.Lifetime;
                cancellationToken.ThrowIfCancellationRequested();
                if (exitCode != 0)
                    throw new JobException(ErrorCode.ByondDirectXInstallFail, new JobException($"Invalid exit code: {exitCode}"));
                installedDirectX = true;
            }
            catch (Exception e)
            {
                throw new JobException(ErrorCode.ByondDirectXInstallFail, e);
            }
        }
References Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.ByondDXDir, Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.installedDirectX, Tgstation.Server.Host.Components.Byond.ByondInstallerBase.IOManager, Tgstation.Server.Host.System.IProcessExecutor.LaunchProcess(), Tgstation.Server.Host.Core.SemaphoreSlimContext.Lock(), Tgstation.Server.Host.Components.Byond.ByondInstallerBase.Logger, Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.processExecutor, and Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.semaphore.
Referenced by Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.InstallByond().
SetNoPromptTrusted()
async Task Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.SetNoPromptTrusted (string path, CancellationToken cancellationToken) private
Creates the BYOND cfg file that prevents the trusted mode dialog from appearing when launching DreamDaemon.
Parameters
path The path to the BYOND installation.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Definition at line 153 of file WindowsByondInstaller.cs.
        {
            var configPath = IOManager.ConcatPath(path, ByondConfigDirectory);
            await IOManager.CreateDirectory(configPath, cancellationToken);
            var configFilePath = IOManager.ConcatPath(configPath, ByondDreamDaemonConfigFilename);
            Logger.LogTrace("Disabling trusted prompts in {configFilePath}...", configFilePath);
            await IOManager.WriteAllBytes(
                configFilePath,
                Encoding.UTF8.GetBytes(ByondNoPromptTrustedMode),
                cancellationToken)
                ;
        }
References Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.ByondConfigDirectory, Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.ByondDreamDaemonConfigFilename, Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.ByondNoPromptTrustedMode, Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.IO.IIOManager.CreateDirectory(), Tgstation.Server.Host.Components.Byond.ByondInstallerBase.IOManager, Tgstation.Server.Host.Components.Byond.ByondInstallerBase.Logger, and Tgstation.Server.Host.IO.IIOManager.WriteAllBytes().
Referenced by Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.InstallByond().
UpgradeInstallation()
override async Task Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.UpgradeInstallation (Version version, string path, CancellationToken cancellationToken) virtual
Does actions necessary to get upgrade a BYOND version installed by a previous version of TGS.
Parameters
version The Version of BYOND being installed.
path The path to the BYOND installation.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implements Tgstation.Server.Host.Components.Byond.ByondInstallerBase.
Definition at line 126 of file WindowsByondInstaller.cs.
        {
            if (version == null)
                throw new ArgumentNullException(nameof(version));
            if (path == null)
                throw new ArgumentNullException(nameof(path));
            if (generalConfiguration.SkipAddingByondFirewallException)
                return;
            GetDreamDaemonName(version, out var usesDDExe);
            if (!usesDDExe)
                return;
            if (await IOManager.FileExists(IOManager.ConcatPath(path, TgsFirewalledDDFile), cancellationToken))
                return;
            Logger.LogInformation("BYOND Version {version} needs dd.exe added to firewall", version);
            await AddDreamDaemonToFirewall(version, path, cancellationToken);
        }
References Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.AddDreamDaemonToFirewall(), Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.IO.IIOManager.FileExists(), Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.generalConfiguration, Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.GetDreamDaemonName(), Tgstation.Server.Host.Components.Byond.ByondInstallerBase.IOManager, Tgstation.Server.Host.Components.Byond.ByondInstallerBase.Logger, Tgstation.Server.Host.Configuration.GeneralConfiguration.SkipAddingByondFirewallException, and Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.TgsFirewalledDDFile.
Member Data Documentation
ByondConfigDirectory
const string Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.ByondConfigDirectory = "byond/cfg" static private
Directory to byond installation configuration.
Definition at line 27 of file WindowsByondInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.SetNoPromptTrusted().
ByondDreamDaemonConfigFilename
const string Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.ByondDreamDaemonConfigFilename = "daemon.txt" static private
BYOND's DreamDaemon config file.
Definition at line 32 of file WindowsByondInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.SetNoPromptTrusted().
ByondDXDir
const string Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.ByondDXDir = "byond/directx" static private
The directory that contains the BYOND directx redistributable.
Definition at line 42 of file WindowsByondInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.InstallDirectX().
ByondNoPromptTrustedMode
const string Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.ByondNoPromptTrustedMode = "trusted-check 0" static private
Setting to add to ByondDreamDaemonConfigFilename to suppress an invisible user prompt for running a trusted mode .dmb.
Definition at line 37 of file WindowsByondInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.SetNoPromptTrusted().
generalConfiguration
readonly GeneralConfiguration Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.generalConfiguration private
The GeneralConfiguration for the WindowsByondInstaller.
Definition at line 66 of file WindowsByondInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.InstallByond(), Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.UpgradeInstallation(), and Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.WindowsByondInstaller().
installedDirectX
bool Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.installedDirectX private
If DirectX was installed.
Definition at line 76 of file WindowsByondInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.InstallDirectX(), and Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.WindowsByondInstaller().
processExecutor
readonly IProcessExecutor Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.processExecutor private
The IProcessExecutor for the WindowsByondInstaller.
Definition at line 61 of file WindowsByondInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.AddDreamDaemonToFirewall(), Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.InstallDirectX(), and Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.WindowsByondInstaller().
semaphore
readonly SemaphoreSlim Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.semaphore private
The SemaphoreSlim for the WindowsByondInstaller.
Definition at line 71 of file WindowsByondInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.InstallDirectX(), and Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.WindowsByondInstaller().
TgsFirewalledDDFile
const string Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.TgsFirewalledDDFile = "TGSFirewalledDD" static private
The file TGS uses to determine if dd.exe has been firewalled.
Definition at line 47 of file WindowsByondInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.AddDreamDaemonToFirewall(), and Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.UpgradeInstallation().
Property Documentation
ByondRevisionsUrlTemplate
override string Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.ByondRevisionsUrlTemplate get protected
Definition at line 56 of file WindowsByondInstaller.cs.
DreamMakerName
override string Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.DreamMakerName get
Get the file name of the DreamMaker executable.
Implements Tgstation.Server.Host.Components.Byond.IByondInstaller.
Definition at line 50 of file WindowsByondInstaller.cs.
PathToUserByondFolder
override string Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.PathToUserByondFolder get
The path to the BYOND folder for the user.
Implements Tgstation.Server.Host.Components.Byond.IByondInstaller.
Definition at line 53 of file WindowsByondInstaller.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.WindowsByondInstaller().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Byond/WindowsByondInstaller.cs