tgstation-server: Tgstation.Server.Host.Components.Session.SessionController Class Reference
Tgstation.Server.Host.Components.Session.SessionController Class Reference sealed
Public Member Functions
SessionController (ReattachInformation reattachInformation, Api.Models.Instance metadata, IProcess process, IEngineExecutableLock engineLock, Byond.TopicSender.ITopicClient byondTopicSender, IChatTrackingContext chatTrackingContext, IBridgeRegistrar bridgeRegistrar, IChatManager chat, IAssemblyInformationProvider assemblyInformationProvider, IAsyncDelayer asyncDelayer, IDotnetDumpService dotnetDumpService, IEventConsumer eventConsumer, IJobManager jobManager, IDreamMaker dreamMaker, ILogger< SessionController > logger, Func< ValueTask > postLifetimeCallback, uint? startupTimeout, bool reattached, bool apiValidate)
Initializes a new instance of the SessionController class.
async ValueTask DisposeAsync ()
async ValueTask< BridgeResponse?> ProcessBridgeRequest (BridgeParameters parameters, CancellationToken cancellationToken)
Handle a set of bridge parameters .
Parameters
parameters The BridgeParameters to handle.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the BridgeResponse for the request or null if the request could not be dispatched.
ValueTask Release ()
Releases the IProcess without terminating it. Also calls IDisposable.Dispose.
Returns
A ValueTask representing the running operation.
ValueTask< TopicResponse?> SendCommand (TopicParameters parameters, CancellationToken cancellationToken)
Sends a command to DreamDaemon through /world/Topic().
Parameters
parameters The TopicParameters to send.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the TopicResponse of /world/Topic().
async ValueTask< bool > SetRebootState (RebootState newRebootState, CancellationToken cancellationToken)
Attempts to change the current RebootState to newRebootState .
Parameters
newRebootState The new RebootState.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in true if the operation succeeded, false otherwise.
void ResetRebootState ()
Changes RebootState to RebootState.Normal without telling the DMAPI.
void AdjustPriority (bool higher)
Set's the owned global::System.Diagnostics.Process.PriorityClass to a non-normal value.
Parameters
higher If true will be set to global::System.Diagnostics.ProcessPriorityClass.AboveNormal otherwise, will be set to global::System.Diagnostics.ProcessPriorityClass.BelowNormal.
void SuspendProcess ()
Suspends the process.
void ResumeProcess ()
Resumes the process.
IAsyncDisposable ReplaceDmbProvider (IDmbProvider dmbProvider)
Replace the IDmbProvider in use with a given newProvider , disposing the old one.
Parameters
newProvider The new IDmbProvider.
Returns
An IAsyncDisposable to be disposed once certain that the original IDmbProvider is no longer in use.
async ValueTask InstanceRenamed (string newInstanceName, CancellationToken cancellationToken)
Called when the owning Instance is renamed.
Parameters
newInstanceName The new Api.Models.NamedEntity.Name.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
async ValueTask UpdateChannels (IEnumerable< ChannelRepresentation > newChannels, CancellationToken cancellationToken)
Called when newChannels are set.
Parameters
newChannels The IEnumerable<T> of new ChannelRepresentations.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
ValueTask CreateDump (string outputFile, bool minidump, CancellationToken cancellationToken)
Create a dump file of the process.
Parameters
outputFile The full path to the output file.
minidump If a minidump should be taken as opposed to a full dump.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
double MeasureProcessorTimeDelta ()
Gets the estimated CPU usage fraction of the process based on the last time this was called.
Returns
The CPU's estimated usage as a value between 0 and 1.
Properties
DMApiParameters DMApiParameters [get]
The DMApiParameters for the IBridgeHandler.
ApiValidationStatus ApiValidationStatus [get]
The DMAPI Session.ApiValidationStatus.
Models.CompileJob CompileJob [get]
Gets the CompileJob associated with the ISessionController.
EngineVersion EngineVersion [get]
Gets the Api.Models.EngineVersion associated with the ISessionController.
RebootState RebootState [get]
The current RebootState.
Version? DMApiVersion [get, private set]
The DMAPI Version.
bool TerminationWasIntentional [get]
If the DreamDaemon instance sent a.
Task< LaunchResult > LaunchResult [get]
A Task that completes when DreamDaemon starts pumping the windows message queue after loading a .dmb or when it crashes.
Task< int?> Lifetime [get]
The Task<TResult> resulting in the exit code of the process or null if the process was detached.
Task OnStartup [get]
A Task that completes when the server calls /world/TgsNew().
Task OnReboot [get]
A Task that completes when the server calls /world/TgsReboot().
long? StartupBridgeRequestsReceived [get, private set]
The number of times a startup bridge request has been received. null if DMApiAvailable is false.
Task RebootGate [get, set]
A Task that must complete before a TgsReboot() bridge request can complete.
Task OnPrime [get]
A Task that completes when the server calls /world/TgsInitializationComplete().
bool DMApiAvailable [get]
If the DMAPI may be used this session.
bool ProcessingRebootBridgeRequest [get]
If the ISessionController is currently processing a bridge request from TgsReboot().
string DumpFileExtension [get]
The file extension to use for process dumps created from this session.
ReattachInformation ReattachInformation [get]
The up to date Session.ReattachInformation.
FifoSemaphore TopicSendSemaphore [get]
The FifoSemaphore used to prevent concurrent calls into /world/Topic().
long? MemoryUsage [get]
Gets the process' memory usage in bytes.
DateTimeOffset? LaunchTime [get]
When the process was started.
Properties inherited from Tgstation.Server.Host.Components.Interop.Chunker
ILogger< Chunker > Logger [get]
The ILogger for the Chunker.
uint NextPayloadId [get]
Gets a payload ID for use in a new ChunkSetInfo.
Properties inherited from Tgstation.Server.Host.Components.Session.ISessionController
Properties inherited from Tgstation.Server.Host.System.IProcessBase
Properties inherited from Tgstation.Server.Host.Components.Interop.Bridge.IBridgeHandler
Private Member Functions
async Task< LaunchResult > GetLaunchResult (IAssemblyInformationProvider assemblyInformationProvider, IAsyncDelayer asyncDelayer, uint? startupTimeout, bool reattached, bool apiValidate)
The Task<TResult> for LaunchResult.
void CheckDisposed ()
Throws an ObjectDisposedException if DisposeAsync has been called.
async Task PostValidationShutdown (Task< bool > proceedTask)
Terminates the server after ten seconds if it does not exit.
async ValueTask< BridgeResponse?> ProcessBridgeCommand (BridgeParameters parameters, CancellationToken cancellationToken)
Handle a set of bridge parameters .
BridgeResponse BridgeError (string message)
Log and return a BridgeResponse for a given message .
async ValueTask< CombinedTopicResponse?> SendTopicRequest (TopicParameters parameters, CancellationToken cancellationToken)
Send a topic request for given parameters to DreamDaemon, chunking it if necessary.
string GenerateQueryString (TopicParameters parameters, out string json)
Generates a Byond.TopicSender.ITopicClient query string for a given set of parameters .
async ValueTask< CombinedTopicResponse?> SendRawTopic (string queryString, bool priority, CancellationToken cancellationToken)
Send a given queryString to DreamDaemon's /world/Topic.
async ValueTask< TopicResponse?> SendCommand (TopicParameters parameters, bool bypassLaunchResult, CancellationToken cancellationToken)
Sends a command to DreamDaemon through /world/Topic().
BridgeResponse TriggerCustomEvent (CustomEventInvocation? invocation)
Trigger a custom event from a given invocation .
Private Attributes
readonly Byond.TopicSender.ITopicClient byondTopicSender
The Byond.TopicSender.ITopicClient for the SessionController.
readonly? IBridgeRegistration bridgeRegistration
The IBridgeRegistration for the SessionController.
readonly IProcess process
The IProcess for the SessionController.
readonly IEngineExecutableLock engineLock
The IEngineExecutableLock for the SessionController.
readonly IChatTrackingContext chatTrackingContext
The IChatTrackingContext for the SessionController.
readonly IChatManager chat
The IChatManager for the SessionController.
readonly IAsyncDelayer asyncDelayer
The IAsyncDelayer for the SessionController.
readonly IDotnetDumpService dotnetDumpService
The IDotnetDumpService for the SessionController.
readonly IEventConsumer eventConsumer
The IEventConsumer for the SessionController.
readonly IJobManager jobManager
The IJobManager for the SessionController.
readonly IDreamMaker dreamMaker
The IDreamMaker for the SessionController.
readonly TaskCompletionSource initialBridgeRequestTcs
The TaskCompletionSource that completes when DD makes it's first bridge request.
readonly Api.Models.Instance metadata
The Instance metadata.
readonly CancellationTokenSource sessionDurationCts
A CancellationTokenSource used for tasks that should not exceed the lifetime of the session.
readonly object synchronizationLock
lock object for port updates and disposed.
readonly bool apiValidationSession
If this session is meant to validate the presence of the DMAPI.
volatile TaskCompletionSource startupTcs
The TaskCompletionSource that completes when DD sends a valid startup bridge request.
volatile TaskCompletionSource rebootTcs
The TaskCompletionSource that completes when DD tells us about a reboot.
volatile TaskCompletionSource primeTcs
The TaskCompletionSource that completes when DD tells us it's primed.
volatile Task rebootGate
Backing field for RebootGate.
volatile Task customEventProcessingTask
The Task representing calls to TriggerCustomEvent(CustomEventInvocation?).
volatile? Task postValidationShutdownTask
Task for shutting down the server if it is taking too long after validation.
volatile uint rebootBridgeRequestsProcessing
The number of currently active calls to ProcessBridgeRequest(BridgeParameters, CancellationToken) from TgsReboot().
ApiValidationStatus apiValidationStatus
The ApiValidationStatus for the SessionController.
bool disposed
If the SessionController has been disposed.
bool released
If process should be kept alive instead.
bool terminationWasIntentionalForced
Backing field for overriding TerminationWasIntentional.
Additional Inherited Members
Protected Member Functions inherited from Tgstation.Server.Host.Components.Interop.Chunker
Chunker (ILogger< Chunker > logger)
Initializes a new instance of the Chunker class.
async ValueTask< TResponse?> ProcessChunk< TCommunication, TResponse > (Func< TCommunication, CancellationToken, ValueTask< TResponse?> > completionCallback, Func< string, TResponse?> chunkErrorCallback, ChunkData? chunk, CancellationToken cancellationToken)
Process a given chunk .
Detailed Description
Definition at line 37 of file SessionController.cs.
Constructor & Destructor Documentation
SessionController()
Tgstation.Server.Host.Components.Session.SessionController.SessionController (ReattachInformation reattachInformation, Api::Models::Instance metadata, IProcess process, IEngineExecutableLock engineLock, Byond::TopicSender::ITopicClient byondTopicSender, IChatTrackingContext chatTrackingContext, IBridgeRegistrar bridgeRegistrar, IChatManager chat, IAssemblyInformationProvider assemblyInformationProvider, IAsyncDelayer asyncDelayer, IDotnetDumpService dotnetDumpService, IEventConsumer eventConsumer, IJobManager jobManager, IDreamMaker dreamMaker, ILogger< SessionController > logger, Func< ValueTask > postLifetimeCallback, uint? startupTimeout, bool reattached, bool apiValidate)
Initializes a new instance of the SessionController class.
Parameters
reattachInformation The value of ReattachInformation.
metadata The owning Instance.
process The value of process.
engineLock The value of engineLock.
byondTopicSender The value of byondTopicSender.
bridgeRegistrar The IBridgeRegistrar used to populate bridgeRegistration.
chat The value of chat.
chatTrackingContext The value of chatTrackingContext.
assemblyInformationProvider The IAssemblyInformationProvider for the SessionController.
asyncDelayer The value of asyncDelayer.
dotnetDumpService The value of dotnetDumpService.
eventConsumer The value of eventConsumer.
jobManager The value of jobManager.
dreamMaker The value of dreamMaker.
logger The value of Chunker.Logger.
postLifetimeCallback The Func<TResult> returning a ValueTask to be run after the process ends.
startupTimeout The optional time to wait before failing the LaunchResult.
reattached If this is a reattached session.
apiValidate The value of apiValidationSession.
Definition at line 294 of file SessionController.cs.
            : base(logger)
        {
            ReattachInformation = reattachInformation ?? throw new ArgumentNullException(nameof(reattachInformation));
            this.metadata = metadata ?? throw new ArgumentNullException(nameof(metadata));
            this.process = process ?? throw new ArgumentNullException(nameof(process));
            this.engineLock = engineLock ?? throw new ArgumentNullException(nameof(engineLock));
            this.byondTopicSender = byondTopicSender ?? throw new ArgumentNullException(nameof(byondTopicSender));
            this.chatTrackingContext = chatTrackingContext ?? throw new ArgumentNullException(nameof(chatTrackingContext));
            ArgumentNullException.ThrowIfNull(bridgeRegistrar);
            this.chat = chat ?? throw new ArgumentNullException(nameof(chat));
            ArgumentNullException.ThrowIfNull(assemblyInformationProvider);
            this.asyncDelayer = asyncDelayer ?? throw new ArgumentNullException(nameof(asyncDelayer));
            this.dotnetDumpService = dotnetDumpService ?? throw new ArgumentNullException(nameof(dotnetDumpService));
            this.eventConsumer = eventConsumer ?? throw new ArgumentNullException(nameof(eventConsumer));
            this.jobManager = jobManager ?? throw new ArgumentNullException(nameof(jobManager));
            this.dreamMaker = dreamMaker ?? throw new ArgumentNullException(nameof(dreamMaker));
            apiValidationSession = apiValidate;
            disposed = false;
            apiValidationStatus = ApiValidationStatus.NeverValidated;
            released = false;
            startupTcs = new TaskCompletionSource();
            rebootTcs = new TaskCompletionSource();
            primeTcs = new TaskCompletionSource();
            rebootGate = Task.CompletedTask;
            customEventProcessingTask = Task.CompletedTask;
            // Run this asynchronously because we want to try to avoid any effects sending topics to the server while the initial bridge request is processing
            // It MAY be the source of a DD crash. See this gist https://gist.github.com/Cyberboss/7776bbeff3a957d76affe0eae95c9f14
            // Worth further investigation as to if that sequence of events is a reliable crash vector and opening a BYOND bug if it is
            initialBridgeRequestTcs = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
            sessionDurationCts = new CancellationTokenSource();
            TopicSendSemaphore = new FifoSemaphore();
            synchronizationLock = new object();
            if (DMApiAvailable)
            {
                StartupBridgeRequestsReceived = 0;
            }
            if (apiValidationSession || DMApiAvailable)
            {
                bridgeRegistration = bridgeRegistrar.RegisterHandler(this);
                this.chatTrackingContext.SetChannelSink(this);
            }
            else
                logger.LogTrace(
                    "Not registering session with {reasonWhyDmApiIsBad} DMAPI version for interop!",
                    reattachInformation.Dmb.CompileJob.DMApiVersion == null
                        ? "no"
                        : $"incompatible ({reattachInformation.Dmb.CompileJob.DMApiVersion})");
            async Task<int?> WrapLifetime()
            {
                var exitCode = await process.Lifetime;
                await postLifetimeCallback();
                if (postValidationShutdownTask != null)
                    await postValidationShutdownTask;
                return exitCode;
            }
            Lifetime = WrapLifetime();
            LaunchResult = GetLaunchResult(
                assemblyInformationProvider,
                asyncDelayer,
                startupTimeout,
                reattached,
                apiValidate);
            logger.LogDebug(
                "Created session controller. CommsKey: {accessIdentifier}, Port: {port}",
                reattachInformation.AccessIdentifier,
                reattachInformation.Port);
        }
References Tgstation.Server.Host.Components.Session.SessionController.apiValidationSession, Tgstation.Server.Host.Components.Session.SessionController.apiValidationStatus, Tgstation.Server.Host.Components.Session.SessionController.asyncDelayer, Tgstation.Server.Host.Components.Session.SessionController.bridgeRegistration, Tgstation.Server.Host.Components.Session.SessionController.byondTopicSender, Tgstation.Server.Host.Components.Session.SessionController.chat, Tgstation.Server.Host.Components.Session.SessionController.chatTrackingContext, Tgstation.Server.Host.Components.Session.SessionController.customEventProcessingTask, Tgstation.Server.Host.Components.Session.SessionController.disposed, Tgstation.Server.Host.Components.Session.SessionController.DMApiAvailable, Tgstation.Server.Host.Components.Session.SessionController.dotnetDumpService, Tgstation.Server.Host.Components.Session.SessionController.dreamMaker, Tgstation.Server.Host.Components.Session.SessionController.engineLock, Tgstation.Server.Host.Components.Session.SessionController.eventConsumer, Tgstation.Server.Host.Components.Session.SessionController.GetLaunchResult(), Tgstation.Server.Host.Components.Session.SessionController.initialBridgeRequestTcs, Tgstation.Server.Host.Components.Session.SessionController.jobManager, Tgstation.Server.Host.Components.Session.SessionController.Lifetime, Tgstation.Server.Host.System.IProcessBase.Lifetime, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Components.Session.SessionController.metadata, Tgstation.Server.Host.Components.Session.SessionController.postValidationShutdownTask, Tgstation.Server.Host.Components.Session.SessionController.primeTcs, Tgstation.Server.Host.Components.Session.SessionController.process, Tgstation.Server.Host.Components.Session.SessionController.rebootGate, Tgstation.Server.Host.Components.Session.SessionController.rebootTcs, Tgstation.Server.Host.Components.Interop.Bridge.IBridgeRegistrar.RegisterHandler(), Tgstation.Server.Host.Components.Session.SessionController.released, Tgstation.Server.Host.Components.Session.SessionController.sessionDurationCts, Tgstation.Server.Host.Components.Chat.IChatTrackingContext.SetChannelSink(), Tgstation.Server.Host.Components.Session.SessionController.StartupBridgeRequestsReceived, Tgstation.Server.Host.Components.Session.SessionController.startupTcs, Tgstation.Server.Host.Components.Session.SessionController.synchronizationLock, and Tgstation.Server.Host.Components.Session.SessionController.TopicSendSemaphore.
Member Function Documentation
AdjustPriority()
void Tgstation.Server.Host.Components.Session.SessionController.AdjustPriority (bool higher)
Set's the owned global::System.Diagnostics.Process.PriorityClass to a non-normal value.
Parameters
higher If true will be set to global::System.Diagnostics.ProcessPriorityClass.AboveNormal otherwise, will be set to global::System.Diagnostics.ProcessPriorityClass.BelowNormal.
Implements Tgstation.Server.Host.System.IProcessBase.
BridgeError()
BridgeResponse Tgstation.Server.Host.Components.Session.SessionController.BridgeError (string message) private
Log and return a BridgeResponse for a given message .
Parameters
message The error message.
Returns
A new errored BridgeResponse.
Definition at line 835 of file SessionController.cs.
        {
            Logger.LogWarning("Bridge request error: {message}", message);
            return new BridgeResponse
            {
                ErrorMessage = message,
            };
        }
References Tgstation.Server.Api.Rights.List, and Tgstation.Server.Host.Components.Interop.Chunker.Logger.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.ProcessBridgeCommand(), and Tgstation.Server.Host.Components.Session.SessionController.TriggerCustomEvent().
CheckDisposed()
void Tgstation.Server.Host.Components.Session.SessionController.CheckDisposed () private
Throws an ObjectDisposedException if DisposeAsync has been called.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.Release(), and Tgstation.Server.Host.Components.Session.SessionController.ResetRebootState().
CreateDump()
ValueTask Tgstation.Server.Host.Components.Session.SessionController.CreateDump (string outputFile, bool minidump, CancellationToken cancellationToken)
Create a dump file of the process.
Parameters
outputFile The full path to the output file.
minidump If a minidump should be taken as opposed to a full dump.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.System.IProcessBase.
Definition at line 548 of file SessionController.cs.
        {
            if (engineLock.UseDotnetDump)
                return dotnetDumpService.Dump(process, outputFile, minidump, cancellationToken);
            return process.CreateDump(outputFile, minidump, cancellationToken);
        }
References Tgstation.Server.Host.System.IProcessBase.CreateDump(), Tgstation.Server.Host.Components.Session.SessionController.dotnetDumpService, Tgstation.Server.Host.System.IDotnetDumpService.Dump(), Tgstation.Server.Host.Components.Session.SessionController.engineLock, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Components.Session.SessionController.process, and Tgstation.Server.Host.Components.Engine.IEngineInstallation.UseDotnetDump.
DisposeAsync()
async ValueTask Tgstation.Server.Host.Components.Session.SessionController.DisposeAsync ()
Definition at line 398 of file SessionController.cs.
        {
            lock (synchronizationLock)
            {
                if (disposed)
                    return;
                disposed = true;
            }
            Logger.LogTrace("Disposing...");
            sessionDurationCts.Cancel();
            var cancellationToken = CancellationToken.None; // DCT: None available
            var semaphoreLockTask = TopicSendSemaphore.Lock(cancellationToken);
            if (!released)
            {
                await engineLock.StopServerProcess(
                    Logger,
                    process,
                    ReattachInformation.AccessIdentifier,
                    ReattachInformation.Port,
                    cancellationToken);
            }
            await process.DisposeAsync();
            engineLock.Dispose();
            bridgeRegistration?.Dispose();
            var regularDmbDisposeTask = ReattachInformation.Dmb.DisposeAsync();
            var initialDmb = ReattachInformation.InitialDmb;
            if (initialDmb != null)
                await initialDmb.DisposeAsync();
            await regularDmbDisposeTask;
            chatTrackingContext.Dispose();
            sessionDurationCts.Dispose();
            if (!released)
                await Lifetime; // finish the async callback
            (await semaphoreLockTask).Dispose();
            TopicSendSemaphore.Dispose();
            await customEventProcessingTask;
        }
References Tgstation.Server.Host.Components.Interop.DMApiParameters.AccessIdentifier, Tgstation.Server.Host.Components.Session.SessionController.bridgeRegistration, Tgstation.Server.Host.Components.Session.SessionController.chatTrackingContext, Tgstation.Server.Host.Components.Session.SessionController.customEventProcessingTask, Tgstation.Server.Host.Utils.FifoSemaphore.Dispose(), Tgstation.Server.Host.Components.Session.SessionController.disposed, Tgstation.Server.Host.Components.Session.ReattachInformation.Dmb, Tgstation.Server.Host.Components.Session.SessionController.engineLock, Tgstation.Server.Host.Components.Session.ReattachInformation.InitialDmb, Tgstation.Server.Host.Components.Session.SessionController.Lifetime, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Utils.FifoSemaphore.Lock(), Tgstation.Server.Host.Components.Interop.Chunker.Logger, Tgstation.Server.Host.Models.ReattachInformationBase.Port, Tgstation.Server.Host.Components.Session.SessionController.process, Tgstation.Server.Host.Components.Session.SessionController.released, Tgstation.Server.Host.Components.Session.SessionController.sessionDurationCts, Tgstation.Server.Host.Components.Engine.IEngineInstallation.StopServerProcess(), Tgstation.Server.Host.Components.Session.SessionController.synchronizationLock, and Tgstation.Server.Host.Components.Session.SessionController.TopicSendSemaphore.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.Release().
GenerateQueryString()
string Tgstation.Server.Host.Components.Session.SessionController.GenerateQueryString (TopicParameters parameters, out string json) private
Generates a Byond.TopicSender.ITopicClient query string for a given set of parameters .
Parameters
parameters The TopicParameters to serialize.
json The intermediate JSON string prior to URL encoding.
Returns
The Byond.TopicSender.ITopicClient query string for the given parameters .
Definition at line 976 of file SessionController.cs.
        {
            json = JsonConvert.SerializeObject(parameters, DMApiConstants.SerializerSettings);
            var commandString = String.Format(
                CultureInfo.InvariantCulture,
                "?{0}={1}",
                byondTopicSender.SanitizeString(DMApiConstants.TopicData),
                byondTopicSender.SanitizeString(json));
            return commandString;
        }
References Tgstation.Server.Host.Components.Session.SessionController.byondTopicSender, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Components.Interop.DMApiConstants.SerializerSettings, and Tgstation.Server.Host.Components.Interop.DMApiConstants.TopicData.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.SendTopicRequest().
GetLaunchResult()
async Task< LaunchResult > Tgstation.Server.Host.Components.Session.SessionController.GetLaunchResult (IAssemblyInformationProvider assemblyInformationProvider, IAsyncDelayer asyncDelayer, uint? startupTimeout, bool reattached, bool apiValidate) private
The Task<TResult> for LaunchResult.
Parameters
assemblyInformationProvider The IAssemblyInformationProvider.
asyncDelayer The IAsyncDelayer.
startupTimeout The, optional, startup timeout in seconds.
reattached If DreamDaemon was reattached.
apiValidate If this is a DMAPI validation session.
Returns
A Task<TResult> resulting in the Session.LaunchResult for the operation.
Definition at line 569 of file SessionController.cs.
        {
            var startTime = DateTimeOffset.UtcNow;
            var useBridgeRequestForLaunchResult = !reattached && (apiValidate || DMApiAvailable);
            var startupTask = useBridgeRequestForLaunchResult
                ? initialBridgeRequestTcs.Task
                : process.Startup;
            var toAwait = Task.WhenAny(startupTask, process.Lifetime);
            if (startupTimeout.HasValue)
                toAwait = Task.WhenAny(
                    toAwait,
                    asyncDelayer.Delay(
                        TimeSpan.FromSeconds(startupTimeout.Value),
                        CancellationToken.None)
                    .AsTask()); // DCT: None available, task will clean up after delay
            Logger.LogTrace(
                "Waiting for LaunchResult based on {launchResultCompletionCause}{possibleTimeout}...",
                useBridgeRequestForLaunchResult ? "initial bridge request" : "process startup",
                startupTimeout.HasValue ? $" with a timeout of {startupTimeout.Value}s" : String.Empty);
            await toAwait;
            var result = new LaunchResult
            {
                ExitCode = process.Lifetime.IsCompleted ? await process.Lifetime : null,
                StartupTime = startupTask.IsCompleted ? (DateTimeOffset.UtcNow - startTime) : null,
            };
            Logger.LogTrace("Launch result: {launchResult}", result);
            if (!result.ExitCode.HasValue && reattached && !disposed)
            {
                var reattachResponse = await SendCommand(
                    new TopicParameters(
                        assemblyInformationProvider.Version,
                        ReattachInformation.RuntimeInformation!.ServerPort),
                    true,
                    sessionDurationCts.Token);
                if (reattachResponse != null)
                {
                    if (reattachResponse?.CustomCommands != null)
                        chatTrackingContext.CustomCommands = reattachResponse.CustomCommands;
                    else if (reattachResponse != null)
                        Logger.Log(
                            CompileJob.DMApiVersion >= new Version(5, 2, 0)
                                ? LogLevel.Warning
                                : LogLevel.Debug,
                            "DMAPI Interop v{interopVersion} isn't returning the TGS custom commands list. Functionality added in v5.2.0.",
                            CompileJob.DMApiVersion!.Semver());
                }
            }
            return result;
        }
References Tgstation.Server.Host.Components.Session.SessionController.asyncDelayer, Tgstation.Server.Host.Utils.IAsyncDelayer.Delay(), Tgstation.Server.Host.Components.Session.SessionController.disposed, Tgstation.Server.Host.Components.Session.SessionController.DMApiAvailable, Tgstation.Server.Host.Models.CompileJob.DMApiVersion, Tgstation.Server.Host.System.IProcessBase.Lifetime, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Components.Interop.Chunker.Logger, Tgstation.Server.Host.Components.Session.SessionController.process, Tgstation.Server.Host.Components.Session.ReattachInformation.RuntimeInformation, Tgstation.Server.Host.Components.Session.SessionController.SendCommand(), Tgstation.Server.Host.Components.Interop.Bridge.RuntimeInformation.ServerPort, Tgstation.Server.Host.Components.Session.SessionController.sessionDurationCts, Tgstation.Server.Host.System.IProcess.Startup, and Tgstation.Server.Host.System.IAssemblyInformationProvider.Version.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.SessionController().
InstanceRenamed()
async ValueTask Tgstation.Server.Host.Components.Session.SessionController.InstanceRenamed (string newInstanceName, CancellationToken cancellationToken)
Called when the owning Instance is renamed.
Parameters
newInstanceName The new Api.Models.NamedEntity.Name.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.IRenameNotifyee.
Definition at line 529 of file SessionController.cs.
        {
            var runtimeInformation = ReattachInformation.RuntimeInformation;
            if (runtimeInformation != null)
                runtimeInformation.InstanceName = newInstanceName;
            await SendCommand(
                TopicParameters.CreateInstanceRenamedTopicParameters(newInstanceName),
                cancellationToken);
        }
References Tgstation.Server.Host.Components.Interop.Topic.TopicParameters.CreateInstanceRenamedTopicParameters(), Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Components.Session.ReattachInformation.RuntimeInformation, and Tgstation.Server.Host.Components.Session.SessionController.SendCommand().
MeasureProcessorTimeDelta()
double Tgstation.Server.Host.Components.Session.SessionController.MeasureProcessorTimeDelta ()
Gets the estimated CPU usage fraction of the process based on the last time this was called.
Returns
The CPU's estimated usage as a value between 0 and 1.
Implements Tgstation.Server.Host.System.IProcessBase.
PostValidationShutdown()
async Task Tgstation.Server.Host.Components.Session.SessionController.PostValidationShutdown (Task< bool > proceedTask) private
Terminates the server after ten seconds if it does not exit.
Parameters
proceedTask A Task<TResult> that this method awaits before executing. If the Task<TResult>.Result is false, this method will return immediately.
Returns
A Task representing the running operation.
Definition at line 642 of file SessionController.cs.
        {
            Logger.LogTrace("Entered post validation terminate task.");
            if (!await proceedTask)
            {
                Logger.LogTrace("Not running post validation terminate task for repeated bridge request.");
                return;
            }
            const int GracePeriodSeconds = 30;
            Logger.LogDebug("Server will terminated in {gracePeriodSeconds}s if it does not exit...", GracePeriodSeconds);
            var delayTask = asyncDelayer.Delay(TimeSpan.FromSeconds(GracePeriodSeconds), CancellationToken.None).AsTask(); // DCT: None available
            await Task.WhenAny(process.Lifetime, delayTask);
            if (!process.Lifetime.IsCompleted)
            {
                Logger.LogWarning("DMAPI took too long to shutdown server after validation request!");
                process.Terminate();
                apiValidationStatus = ApiValidationStatus.BadValidationRequest;
            }
            else
                Logger.LogTrace("Server exited properly post validation.");
        }
References Tgstation.Server.Host.Components.Session.SessionController.apiValidationStatus, Tgstation.Server.Host.Components.Session.SessionController.asyncDelayer, Tgstation.Server.Host.Utils.IAsyncDelayer.Delay(), Tgstation.Server.Host.System.IProcessBase.Lifetime, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Components.Interop.Chunker.Logger, Tgstation.Server.Host.Components.Session.SessionController.process, and Tgstation.Server.Host.System.IProcess.Terminate().
Referenced by Tgstation.Server.Host.Components.Session.SessionController.ProcessBridgeCommand().
ProcessBridgeCommand()
async ValueTask< BridgeResponse?> Tgstation.Server.Host.Components.Session.SessionController.ProcessBridgeCommand (BridgeParameters parameters, CancellationToken cancellationToken) private
Handle a set of bridge parameters .
Parameters
parameters The BridgeParameters to handle.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the BridgeResponse for the request or null if the request could not be dispatched.
Definition at line 674 of file SessionController.cs.
        {
            var response = new BridgeResponse();
            switch (parameters.CommandType)
            {
                case BridgeCommandType.ChatSend:
                    if (parameters.ChatMessage == null)
                        return BridgeError("Missing chatMessage field!");
                    if (parameters.ChatMessage.ChannelIds == null)
                        return BridgeError("Missing channelIds field in chatMessage!");
                    if (parameters.ChatMessage.ChannelIds.Any(channelIdString => !UInt64.TryParse(channelIdString, out var _)))
                        return BridgeError("Invalid channelIds in chatMessage!");
                    if (parameters.ChatMessage.Text == null)
                        return BridgeError("Missing message field in chatMessage!");
                    var anyFailed = false;
                    var parsedChannels = parameters.ChatMessage.ChannelIds.Select(
                        channelString =>
{
                            anyFailed |= !UInt64.TryParse(channelString, out var channelId);
                            return channelId;
                        });
                    if (anyFailed)
                        return BridgeError("Failed to parse channelIds as U64!");
                    chat.QueueMessage(
                        parameters.ChatMessage,
                        parsedChannels);
                    break;
                case BridgeCommandType.Prime:
                    Interlocked.Exchange(ref primeTcs, new TaskCompletionSource()).SetResult();
                    break;
                case BridgeCommandType.Kill:
                    Logger.LogInformation("Bridge requested process termination!");
                    chatTrackingContext.Active = false;
                    terminationWasIntentionalForced = true;
                    process.Terminate();
                    break;
                case BridgeCommandType.DeprecatedPortUpdate:
                    return BridgeError("Port switching is no longer supported!");
                case BridgeCommandType.Startup:
                    apiValidationStatus = ApiValidationStatus.BadValidationRequest;
                    ++StartupBridgeRequestsReceived;
                    if (apiValidationSession)
                    {
                        var proceedTcs = new TaskCompletionSource<bool>();
                        var firstValidationRequest = Interlocked.CompareExchange(ref postValidationShutdownTask, PostValidationShutdown(proceedTcs.Task), null) == null;
                        proceedTcs.SetResult(firstValidationRequest);
                        if (!firstValidationRequest)
                            return BridgeError("Startup bridge request was repeated!");
                    }
                    if (parameters.Version == null)
                        return BridgeError("Missing dmApiVersion field!");
                    DMApiVersion = parameters.Version;
                    // TODO: When OD figures out how to unite port and topic_port, set an upper version bound on OD for this check
                    if (DMApiVersion.Major != DMApiConstants.InteropVersion.Major
                        || (EngineVersion.Engine == EngineType.OpenDream && DMApiVersion < new Version(5, 7)))
                    {
                        apiValidationStatus = ApiValidationStatus.Incompatible;
                        return BridgeError("Incompatible dmApiVersion!");
                    }
                    switch (parameters.MinimumSecurityLevel)
                    {
                        case DreamDaemonSecurity.Ultrasafe:
                            apiValidationStatus = ApiValidationStatus.RequiresUltrasafe;
                            break;
                        case DreamDaemonSecurity.Safe:
                            apiValidationStatus = ApiValidationStatus.RequiresSafe;
                            break;
                        case DreamDaemonSecurity.Trusted:
                            apiValidationStatus = ApiValidationStatus.RequiresTrusted;
                            break;
                        case null:
                            return BridgeError("Missing minimumSecurityLevel field!");
                        default:
                            return BridgeError("Invalid minimumSecurityLevel!");
                    }
                    Logger.LogTrace("ApiValidationStatus set to {apiValidationStatus}", apiValidationStatus);
                    // we create new runtime info here because of potential .Dmb changes (i think. i forget...)
                    response.RuntimeInformation = new RuntimeInformation(
                        chatTrackingContext,
                        ReattachInformation.Dmb,
                        ReattachInformation.RuntimeInformation!.ServerVersion,
                        ReattachInformation.RuntimeInformation.InstanceName,
                        ReattachInformation.RuntimeInformation.SecurityLevel,
                        ReattachInformation.RuntimeInformation.Visibility,
                        ReattachInformation.RuntimeInformation.ServerPort,
                        ReattachInformation.RuntimeInformation.ApiValidateOnly);
                    if (parameters.TopicPort.HasValue)
                    {
                        var newTopicPort = parameters.TopicPort.Value;
                        Logger.LogInformation("Server is requesting use of port {topicPort} for topic communications", newTopicPort);
                        ReattachInformation.TopicPort = newTopicPort;
                    }
                    // Load custom commands
                    chatTrackingContext.CustomCommands = parameters.CustomCommands ?? Array.Empty<CustomCommand>();
                    chatTrackingContext.Active = true;
                    Interlocked.Exchange(ref startupTcs, new TaskCompletionSource()).SetResult();
                    break;
                case BridgeCommandType.Reboot:
                    Interlocked.Increment(ref rebootBridgeRequestsProcessing);
                    try
                    {
                        chatTrackingContext.Active = false;
                        var rebootGate = RebootGate; // Important to read this before setting the TCS or it could change
                        Interlocked.Exchange(ref rebootTcs, new TaskCompletionSource()).SetResult();
                        await rebootGate.WaitAsync(cancellationToken);
                    }
                    finally
                    {
                        Interlocked.Decrement(ref rebootBridgeRequestsProcessing);
                    }
                    break;
                case BridgeCommandType.Chunk:
                    return await ProcessChunk<BridgeParameters, BridgeResponse>(ProcessBridgeCommand, BridgeError, parameters.Chunk, cancellationToken);
                case BridgeCommandType.Event:
                    return TriggerCustomEvent(parameters.EventInvocation);
                case BridgeCommandType.Deploy:
                    var job = Job.Create(JobCode.AutomaticDeployment, null, metadata, DreamMakerRights.CancelCompile);
                    await jobManager.RegisterOperation(
                        job,
                        (core, databaseContextFactory, job, progressReporter, jobCancellationToken) =>
                            dreamMaker.DeploymentProcess(
                                job,
                                databaseContextFactory,
                                progressReporter,
                                jobCancellationToken),
                        cancellationToken);
                    break;
                case null:
                    return BridgeError("Missing commandType!");
                default:
                    return BridgeError($"commandType {parameters.CommandType} not supported!");
            }
            return response;
        }
References Tgstation.Server.Host.Components.Interop.Bridge.RuntimeInformation.ApiValidateOnly, Tgstation.Server.Host.Components.Session.SessionController.apiValidationSession, Tgstation.Server.Host.Components.Session.SessionController.apiValidationStatus, Tgstation.Server.Host.Components.Session.SessionController.BridgeError(), Tgstation.Server.Host.Components.Session.SessionController.chat, Tgstation.Server.Host.Components.Session.SessionController.chatTrackingContext, Tgstation.Server.Host.Models.Job.Create(), Tgstation.Server.Host.Components.Deployment.IDreamMaker.DeploymentProcess(), Tgstation.Server.Host.Components.Session.SessionController.DMApiVersion, Tgstation.Server.Host.Components.Session.ReattachInformation.Dmb, Tgstation.Server.Host.Components.Session.SessionController.dreamMaker, Tgstation.Server.Api.Models.EngineVersion.Engine, Tgstation.Server.Host.Components.Interop.Bridge.RuntimeInformation.InstanceName, Tgstation.Server.Host.Components.Interop.DMApiConstants.InteropVersion, Tgstation.Server.Host.Components.Session.SessionController.jobManager, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Components.Interop.Chunker.Logger, Tgstation.Server.Host.Components.Session.SessionController.metadata, Tgstation.Server.Host.Components.Session.SessionController.PostValidationShutdown(), Tgstation.Server.Host.Components.Session.SessionController.postValidationShutdownTask, Tgstation.Server.Host.Components.Session.SessionController.primeTcs, Tgstation.Server.Host.Components.Session.SessionController.process, Tgstation.Server.Host.Components.Session.SessionController.ProcessBridgeCommand(), Tgstation.Server.Host.Components.Chat.IChatManager.QueueMessage(), Tgstation.Server.Host.Components.Session.SessionController.rebootBridgeRequestsProcessing, Tgstation.Server.Host.Components.Session.SessionController.RebootGate, Tgstation.Server.Host.Components.Session.SessionController.rebootGate, Tgstation.Server.Host.Components.Session.SessionController.rebootTcs, Tgstation.Server.Host.Jobs.IJobManager.RegisterOperation(), Tgstation.Server.Host.Components.Session.ReattachInformation.RuntimeInformation, Tgstation.Server.Host.Components.Interop.Bridge.RuntimeInformation.SecurityLevel, Tgstation.Server.Host.Components.Interop.Bridge.RuntimeInformation.ServerPort, Tgstation.Server.Host.Components.Interop.Bridge.RuntimeInformation.ServerVersion, Tgstation.Server.Host.Components.Session.SessionController.StartupBridgeRequestsReceived, Tgstation.Server.Host.Components.Session.SessionController.startupTcs, Tgstation.Server.Host.System.IProcess.Terminate(), Tgstation.Server.Host.Components.Session.SessionController.terminationWasIntentionalForced, Tgstation.Server.Host.Components.Session.SessionController.TriggerCustomEvent(), and Tgstation.Server.Host.Components.Interop.Bridge.RuntimeInformation.Visibility.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.ProcessBridgeCommand(), and Tgstation.Server.Host.Components.Session.SessionController.ProcessBridgeRequest().
ProcessBridgeRequest()
async ValueTask< BridgeResponse?> Tgstation.Server.Host.Components.Session.SessionController.ProcessBridgeRequest (BridgeParameters parameters, CancellationToken cancellationToken)
Handle a set of bridge parameters .
Parameters
parameters The BridgeParameters to handle.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the BridgeResponse for the request or null if the request could not be dispatched.
Implements Tgstation.Server.Host.Components.Interop.Bridge.IBridgeDispatcher.
Definition at line 446 of file SessionController.cs.
        {
            ArgumentNullException.ThrowIfNull(parameters);
            using (LogContext.PushProperty(SerilogContextHelper.InstanceIdContextProperty, metadata.Id))
            {
                if (!DMApiAvailable && !apiValidationSession)
                {
                    Logger.LogWarning("Ignoring bridge request from session without confirmed DMAPI!");
                    return null;
                }
                Logger.LogTrace("Handling bridge request...");
                try
                {
                    return await ProcessBridgeCommand(parameters, cancellationToken);
                }
                finally
                {
                    initialBridgeRequestTcs.TrySetResult();
                }
            }
        }
References Tgstation.Server.Host.Components.Session.SessionController.apiValidationSession, Tgstation.Server.Host.Components.Session.SessionController.DMApiAvailable, Tgstation.Server.Host.Components.Session.SessionController.initialBridgeRequestTcs, Tgstation.Server.Host.Utils.SerilogContextHelper.InstanceIdContextProperty, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Components.Interop.Chunker.Logger, Tgstation.Server.Host.Components.Session.SessionController.metadata, and Tgstation.Server.Host.Components.Session.SessionController.ProcessBridgeCommand().
Release()
ValueTask Tgstation.Server.Host.Components.Session.SessionController.Release ()
Releases the IProcess without terminating it. Also calls IDisposable.Dispose.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Session.ISessionController.
Definition at line 472 of file SessionController.cs.
        {
            CheckDisposed();
            ReattachInformation.Dmb.KeepAlive();
            ReattachInformation.InitialDmb?.KeepAlive();
            engineLock.DoNotDeleteThisSession();
            released = true;
            return DisposeAsync();
        }
References Tgstation.Server.Host.Components.Session.SessionController.CheckDisposed(), Tgstation.Server.Host.Components.Session.SessionController.DisposeAsync(), Tgstation.Server.Host.Components.Session.ReattachInformation.Dmb, Tgstation.Server.Host.Components.Engine.IEngineExecutableLock.DoNotDeleteThisSession(), Tgstation.Server.Host.Components.Session.SessionController.engineLock, Tgstation.Server.Host.Components.Session.ReattachInformation.InitialDmb, Tgstation.Server.Host.Components.Deployment.IDmbProvider.KeepAlive(), and Tgstation.Server.Host.Components.Session.SessionController.released.
ReplaceDmbProvider()
IAsyncDisposable Tgstation.Server.Host.Components.Session.SessionController.ReplaceDmbProvider (IDmbProvider dmbProvider)
Replace the IDmbProvider in use with a given newProvider , disposing the old one.
Parameters
newProvider The new IDmbProvider.
Returns
An IAsyncDisposable to be disposed once certain that the original IDmbProvider is no longer in use.
Implements Tgstation.Server.Host.Components.Session.ISessionController.
Definition at line 521 of file SessionController.cs.
        {
            var oldDmb = ReattachInformation.Dmb;
            ReattachInformation.Dmb = dmbProvider ?? throw new ArgumentNullException(nameof(dmbProvider));
            return oldDmb;
        }
References Tgstation.Server.Host.Components.Session.ReattachInformation.Dmb, and Tgstation.Server.Api.Rights.List.
ResetRebootState()
void Tgstation.Server.Host.Components.Session.SessionController.ResetRebootState ()
Changes RebootState to RebootState.Normal without telling the DMAPI.
Implements Tgstation.Server.Host.Components.Session.ISessionController.
Definition at line 504 of file SessionController.cs.
        {
            CheckDisposed();
            Logger.LogTrace("Resetting reboot state...");
            ReattachInformation.RebootState = RebootState.Normal;
        }
References Tgstation.Server.Host.Components.Session.SessionController.CheckDisposed(), Tgstation.Server.Api.Rights.List, and Tgstation.Server.Host.Components.Interop.Chunker.Logger.
ResumeProcess()
void Tgstation.Server.Host.Components.Session.SessionController.ResumeProcess ()
Resumes the process.
Implements Tgstation.Server.Host.System.IProcessBase.
SendCommand() [1/2]
async ValueTask< TopicResponse?> Tgstation.Server.Host.Components.Session.SessionController.SendCommand (TopicParameters parameters, bool bypassLaunchResult, CancellationToken cancellationToken) private
Sends a command to DreamDaemon through /world/Topic().
Parameters
parameters The TopicParameters to send.
bypassLaunchResult If waiting for the LaunchResult should be bypassed.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the TopicResponse of /world/Topic().
Definition at line 1049 of file SessionController.cs.
        {
            ArgumentNullException.ThrowIfNull(parameters);
            if (Lifetime.IsCompleted || disposed)
            {
                Logger.LogWarning(
                    "Attempted to send a command to an inactive SessionController: {commandType}",
                    parameters.CommandType);
                return null;
            }
            if (!DMApiAvailable)
            {
                Logger.LogTrace("Not sending topic request {commandType} to server without/with incompatible DMAPI!", parameters.CommandType);
                return null;
            }
            var reboot = OnReboot;
            if (!bypassLaunchResult)
            {
                var launchResult = await LaunchResult.WaitAsync(cancellationToken);
                if (launchResult.ExitCode.HasValue)
                {
                    Logger.LogDebug("Not sending topic request {commandType} to server that failed to launch!", parameters.CommandType);
                    return null;
                }
            }
            // meh, this is kind of a hack, but it works
            if (!chatTrackingContext.Active)
            {
                Logger.LogDebug("Not sending topic request {commandType} to server that is rebooting/starting.", parameters.CommandType);
                return null;
            }
            using var cts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
            var combinedCancellationToken = cts.Token;
            async ValueTask CancelIfLifetimeElapses()
            {
                try
                {
                    var completed = await Task.WhenAny(Lifetime, reboot).WaitAsync(combinedCancellationToken);
                    Logger.LogDebug(
                        "Server {action}, cancelling pending command: {commandType}",
                        completed != reboot
                            ? "process ended"
                            : "rebooting",
                        parameters.CommandType);
                    cts.Cancel();
                }
                catch (OperationCanceledException)
                {
                    // expected, not even worth tracing
                }
                catch (Exception ex)
                {
                    Logger.LogError(ex, "Error in CancelIfLifetimeElapses!");
                }
            }
            TopicResponse? fullResponse = null;
            var lifetimeWatchingTask = CancelIfLifetimeElapses();
            try
            {
                var combinedResponse = await SendTopicRequest(parameters, combinedCancellationToken);
                void LogCombinedResponse()
                {
                    if (LogTopicRequests && combinedResponse != null)
                        Logger.LogTrace("Topic response: {topicString}", combinedResponse.ByondTopicResponse.StringData ?? "(NO STRING DATA)");
                }
                LogCombinedResponse();
                if (combinedResponse?.InteropResponse?.Chunk != null)
                {
                    Logger.LogTrace("Topic response is chunked...");
                    ChunkData? nextChunk = combinedResponse.InteropResponse.Chunk;
                    do
                    {
                        var nextRequest = await ProcessChunk<TopicResponse, ChunkedTopicParameters>(
                            (completedResponse, _) =>
{
                                fullResponse = completedResponse;
                                return ValueTask.FromResult<ChunkedTopicParameters?>(null);
                            },
                            error =>
{
                                Logger.LogWarning("Topic response chunking error: {message}", error);
                                return null;
                            },
                            combinedResponse?.InteropResponse?.Chunk,
                            combinedCancellationToken);
                        if (nextRequest != null)
{
                            nextRequest.PayloadId = nextChunk.PayloadId;
                            combinedResponse = await SendTopicRequest(nextRequest, combinedCancellationToken);
                            LogCombinedResponse();
                            nextChunk = combinedResponse?.InteropResponse?.Chunk;
                        }
                        else
                            nextChunk = null;
                    }
                    while (nextChunk != null);
                }
                else
                    fullResponse = combinedResponse?.InteropResponse;
            }
            catch (OperationCanceledException ex)
            {
                Logger.LogDebug(
                    ex,
                    "Topic request {cancellationType}!",
                    combinedCancellationToken.IsCancellationRequested
                        ? cancellationToken.IsCancellationRequested
                            ? "cancelled"
                            : "aborted"
                        : "timed out");
                // throw only if the original token was the trigger
                cancellationToken.ThrowIfCancellationRequested();
            }
            finally
            {
                cts.Cancel();
                await lifetimeWatchingTask;
            }
            if (fullResponse?.ErrorMessage != null)
                Logger.LogWarning(
                    "Errored topic response for command {commandType}: {errorMessage}",
                    parameters.CommandType,
                    fullResponse.ErrorMessage);
            return fullResponse;
        }
References Tgstation.Server.Host.Components.Chat.IChatTrackingContext.Active, Tgstation.Server.Host.Components.Session.SessionController.chatTrackingContext, Tgstation.Server.Host.Components.Interop.Bridge.Chunk, Tgstation.Server.Host.Components.Interop.Topic.TopicParameters.Chunk, Tgstation.Server.Host.Components.Session.SessionController.disposed, Tgstation.Server.Host.Components.Session.SessionController.DMApiAvailable, Tgstation.Server.Host.Components.Session.SessionController.Lifetime, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Components.Interop.Chunker.Logger, Tgstation.Server.Host.Components.Session.SessionController.OnReboot, Tgstation.Server.Host.Components.Interop.ChunkSetInfo.PayloadId, and Tgstation.Server.Host.Components.Session.SessionController.SendTopicRequest().
SendCommand() [2/2]
ValueTask< TopicResponse?> Tgstation.Server.Host.Components.Session.SessionController.SendCommand (TopicParameters parameters, CancellationToken cancellationToken)
Sends a command to DreamDaemon through /world/Topic().
Parameters
parameters The TopicParameters to send.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the TopicResponse of /world/Topic().
Implements Tgstation.Server.Host.Components.Session.ISessionController.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.GetLaunchResult(), Tgstation.Server.Host.Components.Session.SessionController.InstanceRenamed(), Tgstation.Server.Host.Components.Session.SessionController.SetRebootState(), and Tgstation.Server.Host.Components.Session.SessionController.TriggerCustomEvent().
SendRawTopic()
async ValueTask< CombinedTopicResponse?> Tgstation.Server.Host.Components.Session.SessionController.SendRawTopic (string queryString, bool priority, CancellationToken cancellationToken) private
Send a given queryString to DreamDaemon's /world/Topic.
Parameters
queryString The sanitized topic query string to send.
priority If this is a priority message. If so, the topic will make 5 attempts to send unless BYOND reboots or exits.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the CombinedTopicResponse of the topic request.
Definition at line 994 of file SessionController.cs.
        {
            if (disposed)
            {
                Logger.LogWarning(
                    "Attempted to send a topic on a disposed SessionController");
                return null;
            }
            var targetPort = ReattachInformation.TopicPort ?? ReattachInformation.Port;
            Byond.TopicSender.TopicResponse? byondResponse;
            using (await TopicSendSemaphore.Lock(cancellationToken))
                byondResponse = await byondTopicSender.SendWithOptionalPriority(
                    asyncDelayer,
                    LogTopicRequests
                        ? Logger
                        : NullLogger.Instance,
                    queryString,
                    targetPort,
                    priority,
                    cancellationToken);
            if (byondResponse == null)
            {
                if (priority)
                    Logger.LogError(
                        "Unable to send priority topic \"{queryString}\"!",
                        queryString);
                return null;
            }
            var topicReturn = byondResponse.StringData;
            TopicResponse? interopResponse = null;
            if (topicReturn != null)
                try
                {
                    interopResponse = JsonConvert.DeserializeObject<TopicResponse>(topicReturn, DMApiConstants.SerializerSettings);
                }
                catch (Exception ex)
                {
                    Logger.LogWarning(ex, "Invalid interop response: {topicReturnString}", topicReturn);
                }
            return new CombinedTopicResponse(byondResponse, interopResponse);
        }
References Tgstation.Server.Host.Components.Session.SessionController.asyncDelayer, Tgstation.Server.Api.Models.Byond, Tgstation.Server.Host.Components.Session.SessionController.byondTopicSender, Tgstation.Server.Host.Components.Session.SessionController.disposed, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Utils.FifoSemaphore.Lock(), Tgstation.Server.Host.Components.Interop.Chunker.Logger, Tgstation.Server.Host.Models.ReattachInformationBase.Port, Tgstation.Server.Host.Components.Interop.DMApiConstants.SerializerSettings, and Tgstation.Server.Host.Components.Session.SessionController.TopicSendSemaphore.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.SendTopicRequest().
SendTopicRequest()
async ValueTask< CombinedTopicResponse?> Tgstation.Server.Host.Components.Session.SessionController.SendTopicRequest (TopicParameters parameters, CancellationToken cancellationToken) private
Send a topic request for given parameters to DreamDaemon, chunking it if necessary.
Parameters
parameters The TopicParameters to send.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the CombinedTopicResponse of the topic request.
Definition at line 850 of file SessionController.cs.
        {
            parameters.AccessIdentifier = ReattachInformation.AccessIdentifier;
            var fullCommandString = GenerateQueryString(parameters, out var json);
            if (LogTopicRequests)
                Logger.LogTrace("Topic request: {json}", json);
            var fullCommandByteCount = Encoding.UTF8.GetByteCount(fullCommandString);
            var topicPriority = parameters.IsPriority;
            if (fullCommandByteCount <= DMApiConstants.MaximumTopicRequestLength)
                return await SendRawTopic(fullCommandString, topicPriority, cancellationToken);
            var interopChunkingVersion = new Version(5, 6, 0);
            if (ReattachInformation.Dmb.CompileJob.DMApiVersion < interopChunkingVersion)
            {
                Logger.LogWarning(
                    "Cannot send topic request as it is exceeds the single request limit of {limitBytes}B ({actualBytes}B) and requires chunking and the current compile job's interop version must be at least {chunkingVersionRequired}!",
                    DMApiConstants.MaximumTopicRequestLength,
                    fullCommandByteCount,
                    interopChunkingVersion);
                return null;
            }
            var payloadId = NextPayloadId;
            // AccessIdentifer is just noise in a chunked request
            parameters.AccessIdentifier = null!;
            GenerateQueryString(parameters, out json);
            // yes, this straight up ignores unicode, precalculating it is useless when we don't
            // even know if the UTF8 bytes of the url encoded chunk will fit the window until we do said encoding
            var fullPayloadSize = (uint)json.Length;
            List<string>? chunkQueryStrings = null;
            for (var chunkCount = 2; chunkQueryStrings == null; ++chunkCount)
            {
                var standardChunkSize = fullPayloadSize / chunkCount;
                var bigChunkSize = standardChunkSize + (fullPayloadSize % chunkCount);
                if (bigChunkSize > DMApiConstants.MaximumTopicRequestLength)
                    continue;
                chunkQueryStrings = new List<string>();
                for (var i = 0U; i < chunkCount; ++i)
                {
                    var startIndex = i * standardChunkSize;
                    var subStringLength = Math.Min(
                        fullPayloadSize - startIndex,
                        i == chunkCount - 1
                            ? bigChunkSize
                            : standardChunkSize);
                    var chunkPayload = json.Substring((int)startIndex, (int)subStringLength);
                    var chunk = new ChunkData
                    {
                        Payload = chunkPayload,
                        PayloadId = payloadId,
                        SequenceId = i,
                        TotalChunks = (uint)chunkCount,
                    };
                    var chunkParameters = new TopicParameters(chunk)
                    {
                        AccessIdentifier = ReattachInformation.AccessIdentifier,
                    };
                    var chunkCommandString = GenerateQueryString(chunkParameters, out _);
                    if (Encoding.UTF8.GetByteCount(chunkCommandString) > DMApiConstants.MaximumTopicRequestLength)
                    {
                        // too long when encoded, need more chunks
                        chunkQueryStrings = null;
                        break;
                    }
                    chunkQueryStrings.Add(chunkCommandString);
                }
            }
            Logger.LogTrace("Chunking topic request ({totalChunks} total)...", chunkQueryStrings.Count);
            CombinedTopicResponse? combinedResponse = null;
            bool LogRequestIssue(bool possiblyFromCompletedRequest)
            {
                if (combinedResponse?.InteropResponse == null || combinedResponse.InteropResponse.ErrorMessage != null)
                {
                    Logger.LogWarning(
                        "Topic request {chunkingStatus} failed!{potentialRequestError}",
                        possiblyFromCompletedRequest ? "final chunk" : "chunking",
                        combinedResponse?.InteropResponse?.ErrorMessage != null
                            ? $" Request error: {combinedResponse.InteropResponse.ErrorMessage}"
                            : String.Empty);
                    return true;
                }
                return false;
            }
            foreach (var chunkCommandString in chunkQueryStrings)
            {
                combinedResponse = await SendRawTopic(chunkCommandString, topicPriority, cancellationToken);
                if (LogRequestIssue(chunkCommandString == chunkQueryStrings.Last()))
                    return null;
            }
            while ((combinedResponse?.InteropResponse?.MissingChunks?.Count ?? 0) > 0)
            {
                Logger.LogWarning("DD is still missing some chunks of topic request P{payloadId}! Sending missing chunks...", payloadId);
                var missingChunks = combinedResponse!.InteropResponse!.MissingChunks!;
                var lastIndex = missingChunks.Last();
                foreach (var missingChunkIndex in missingChunks)
                {
                    var chunkCommandString = chunkQueryStrings[(int)missingChunkIndex];
                    combinedResponse = await SendRawTopic(chunkCommandString, topicPriority, cancellationToken);
                    if (LogRequestIssue(missingChunkIndex == lastIndex))
                        return null;
                }
            }
            return combinedResponse;
        }
References Tgstation.Server.Host.Components.Interop.DMApiParameters.AccessIdentifier, Tgstation.Server.Host.Components.Deployment.IDmbProvider.CompileJob, Tgstation.Server.Host.Models.CompileJob.DMApiVersion, Tgstation.Server.Host.Components.Session.ReattachInformation.Dmb, Tgstation.Server.Host.Components.Session.SessionController.GenerateQueryString(), Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Components.Interop.Chunker.Logger, Tgstation.Server.Host.Components.Interop.DMApiConstants.MaximumTopicRequestLength, Tgstation.Server.Host.Components.Interop.Chunker.NextPayloadId, and Tgstation.Server.Host.Components.Session.SessionController.SendRawTopic().
Referenced by Tgstation.Server.Host.Components.Session.SessionController.SendCommand().
SetRebootState()
async ValueTask< bool > Tgstation.Server.Host.Components.Session.SessionController.SetRebootState (RebootState newRebootState, CancellationToken cancellationToken)
Attempts to change the current RebootState to newRebootState .
Parameters
newRebootState The new RebootState.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in true if the operation succeeded, false otherwise.
Implements Tgstation.Server.Host.Components.Session.ISessionController.
Definition at line 488 of file SessionController.cs.
        {
            if (RebootState == newRebootState)
                return true;
            Logger.LogTrace("Changing reboot state to {newRebootState}", newRebootState);
            ReattachInformation.RebootState = newRebootState;
            var result = await SendCommand(
                new TopicParameters(newRebootState),
                cancellationToken);
            return result != null && result.ErrorMessage == null;
        }
References Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Components.Interop.Chunker.Logger, and Tgstation.Server.Host.Components.Session.SessionController.SendCommand().
SuspendProcess()
void Tgstation.Server.Host.Components.Session.SessionController.SuspendProcess ()
Suspends the process.
Implements Tgstation.Server.Host.System.IProcessBase.
TriggerCustomEvent()
BridgeResponse Tgstation.Server.Host.Components.Session.SessionController.TriggerCustomEvent (CustomEventInvocation? invocation) private
Trigger a custom event from a given invocation .
Parameters
invocation The CustomEventInvocation.
Returns
An appropriate BridgeResponse.
Definition at line 1195 of file SessionController.cs.
        {
            if (invocation == null)
                return BridgeError("Missing eventInvocation!");
            var eventName = invocation.EventName;
            if (eventName == null)
                return BridgeError("Missing eventName!");
            var notifyCompletion = invocation.NotifyCompletion;
            if (!notifyCompletion.HasValue)
                return BridgeError("Missing notifyCompletion!");
            var eventParams = new List<string>
            {
                ReattachInformation.Dmb.Directory,
            };
            eventParams.AddRange(invocation
                .Parameters?
                .Where(param => param != null)
                .Cast<string>()
                ?? Enumerable.Empty<string>());
            var eventId = Guid.NewGuid();
            Logger.LogInformation("Triggering custom event \"{eventName}\": {eventId}", eventName, eventId);
            var cancellationToken = sessionDurationCts.Token;
            ValueTask? eventTask = eventConsumer.HandleCustomEvent(eventName, eventParams, cancellationToken);
            async Task ProcessEvent()
            {
                try
                {
                    Exception? exception;
                    try
                    {
                        await eventTask.Value;
                        exception = null;
                    }
                    catch (Exception ex)
                    {
                        exception = ex;
                    }
                    if (notifyCompletion.Value)
                        await SendCommand(
                            new TopicParameters(eventId),
                            cancellationToken);
                    else if (exception == null)
                        Logger.LogTrace("Finished custom event {eventId}, not sending notification.", eventId);
                    if (exception != null)
                        throw exception;
                }
                catch (OperationCanceledException ex)
                {
                    Logger.LogDebug(ex, "Custom event invocation {eventId} aborted!", eventId);
                }
                catch (Exception ex)
                {
                    Logger.LogWarning(ex, "Custom event invocation {eventId} errored!", eventId);
                }
            }
            if (!eventTask.HasValue)
                return BridgeError("Event refused to execute due to matching a TGS event!");
            lock (sessionDurationCts)
            {
                var previousEventProcessingTask = customEventProcessingTask;
                var eventProcessingTask = ProcessEvent();
                customEventProcessingTask = Task.WhenAll(customEventProcessingTask, eventProcessingTask);
            }
            return new BridgeResponse
            {
                EventId = notifyCompletion.Value
                    ? eventId.ToString()
                    : null,
            };
        }
References Tgstation.Server.Host.Components.Session.SessionController.BridgeError(), Tgstation.Server.Host.Components.Session.SessionController.customEventProcessingTask, Tgstation.Server.Host.Components.Deployment.IDmbProvider.Directory, Tgstation.Server.Host.Components.Session.ReattachInformation.Dmb, Tgstation.Server.Host.Components.Session.SessionController.eventConsumer, Tgstation.Server.Host.Components.Events.IEventConsumer.HandleCustomEvent(), Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Components.Interop.Chunker.Logger, Tgstation.Server.Host.Components.Session.SessionController.SendCommand(), and Tgstation.Server.Host.Components.Session.SessionController.sessionDurationCts.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.ProcessBridgeCommand().
UpdateChannels()
async ValueTask Tgstation.Server.Host.Components.Session.SessionController.UpdateChannels (IEnumerable< ChannelRepresentation > newChannels, CancellationToken cancellationToken)
Called when newChannels are set.
Parameters
newChannels The IEnumerable<T> of new ChannelRepresentations.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Chat.IChannelSink.
Member Data Documentation
apiValidationSession
readonly bool Tgstation.Server.Host.Components.Session.SessionController.apiValidationSession private
If this session is meant to validate the presence of the DMAPI.
Definition at line 215 of file SessionController.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.ProcessBridgeCommand(), Tgstation.Server.Host.Components.Session.SessionController.ProcessBridgeRequest(), and Tgstation.Server.Host.Components.Session.SessionController.SessionController().
apiValidationStatus
ApiValidationStatus Tgstation.Server.Host.Components.Session.SessionController.apiValidationStatus private
The ApiValidationStatus for the SessionController.
Definition at line 255 of file SessionController.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.PostValidationShutdown(), Tgstation.Server.Host.Components.Session.SessionController.ProcessBridgeCommand(), and Tgstation.Server.Host.Components.Session.SessionController.SessionController().
asyncDelayer
readonly IAsyncDelayer Tgstation.Server.Host.Components.Session.SessionController.asyncDelayer private
The IAsyncDelayer for the SessionController.
Definition at line 170 of file SessionController.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.GetLaunchResult(), Tgstation.Server.Host.Components.Session.SessionController.PostValidationShutdown(), Tgstation.Server.Host.Components.Session.SessionController.SendRawTopic(), and Tgstation.Server.Host.Components.Session.SessionController.SessionController().
bridgeRegistration
readonly? IBridgeRegistration Tgstation.Server.Host.Components.Session.SessionController.bridgeRegistration private
The IBridgeRegistration for the SessionController.
Definition at line 145 of file SessionController.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.DisposeAsync(), and Tgstation.Server.Host.Components.Session.SessionController.SessionController().
byondTopicSender
readonly Byond.TopicSender.ITopicClient Tgstation.Server.Host.Components.Session.SessionController.byondTopicSender private
The Byond.TopicSender.ITopicClient for the SessionController.
Definition at line 140 of file SessionController.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.GenerateQueryString(), Tgstation.Server.Host.Components.Session.SessionController.SendRawTopic(), and Tgstation.Server.Host.Components.Session.SessionController.SessionController().
chat
readonly IChatManager Tgstation.Server.Host.Components.Session.SessionController.chat private
The IChatManager for the SessionController.
Definition at line 165 of file SessionController.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.ProcessBridgeCommand(), and Tgstation.Server.Host.Components.Session.SessionController.SessionController().
chatTrackingContext
readonly IChatTrackingContext Tgstation.Server.Host.Components.Session.SessionController.chatTrackingContext private
The IChatTrackingContext for the SessionController.
Definition at line 160 of file SessionController.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.DisposeAsync(), Tgstation.Server.Host.Components.Session.SessionController.ProcessBridgeCommand(), Tgstation.Server.Host.Components.Session.SessionController.SendCommand(), and Tgstation.Server.Host.Components.Session.SessionController.SessionController().
customEventProcessingTask
volatile Task Tgstation.Server.Host.Components.Session.SessionController.customEventProcessingTask private
The Task representing calls to TriggerCustomEvent(CustomEventInvocation?).
Definition at line 240 of file SessionController.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.DisposeAsync(), Tgstation.Server.Host.Components.Session.SessionController.SessionController(), and Tgstation.Server.Host.Components.Session.SessionController.TriggerCustomEvent().
disposed
bool Tgstation.Server.Host.Components.Session.SessionController.disposed private
If the SessionController has been disposed.
Definition at line 260 of file SessionController.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.DisposeAsync(), Tgstation.Server.Host.Components.Session.SessionController.GetLaunchResult(), Tgstation.Server.Host.Components.Session.SessionController.SendCommand(), Tgstation.Server.Host.Components.Session.SessionController.SendRawTopic(), and Tgstation.Server.Host.Components.Session.SessionController.SessionController().
dotnetDumpService
readonly IDotnetDumpService Tgstation.Server.Host.Components.Session.SessionController.dotnetDumpService private
The IDotnetDumpService for the SessionController.
Definition at line 175 of file SessionController.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.CreateDump(), and Tgstation.Server.Host.Components.Session.SessionController.SessionController().
dreamMaker
readonly IDreamMaker Tgstation.Server.Host.Components.Session.SessionController.dreamMaker private
The IDreamMaker for the SessionController.
Definition at line 190 of file SessionController.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.ProcessBridgeCommand(), and Tgstation.Server.Host.Components.Session.SessionController.SessionController().
engineLock
readonly IEngineExecutableLock Tgstation.Server.Host.Components.Session.SessionController.engineLock private
The IEngineExecutableLock for the SessionController.
Definition at line 155 of file SessionController.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.CreateDump(), Tgstation.Server.Host.Components.Session.SessionController.DisposeAsync(), Tgstation.Server.Host.Components.Session.SessionController.Release(), and Tgstation.Server.Host.Components.Session.SessionController.SessionController().
eventConsumer
readonly IEventConsumer Tgstation.Server.Host.Components.Session.SessionController.eventConsumer private
The IEventConsumer for the SessionController.
Definition at line 180 of file SessionController.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.SessionController(), and Tgstation.Server.Host.Components.Session.SessionController.TriggerCustomEvent().
initialBridgeRequestTcs
readonly TaskCompletionSource Tgstation.Server.Host.Components.Session.SessionController.initialBridgeRequestTcs private
The TaskCompletionSource that completes when DD makes it's first bridge request.
Definition at line 195 of file SessionController.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.ProcessBridgeRequest(), and Tgstation.Server.Host.Components.Session.SessionController.SessionController().
jobManager
readonly IJobManager Tgstation.Server.Host.Components.Session.SessionController.jobManager private
The IJobManager for the SessionController.
Definition at line 185 of file SessionController.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.ProcessBridgeCommand(), and Tgstation.Server.Host.Components.Session.SessionController.SessionController().
metadata
readonly Api.Models.Instance Tgstation.Server.Host.Components.Session.SessionController.metadata private
The Instance metadata.
Definition at line 200 of file SessionController.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.ProcessBridgeCommand(), Tgstation.Server.Host.Components.Session.SessionController.ProcessBridgeRequest(), and Tgstation.Server.Host.Components.Session.SessionController.SessionController().
postValidationShutdownTask
volatile? Task Tgstation.Server.Host.Components.Session.SessionController.postValidationShutdownTask private
Task for shutting down the server if it is taking too long after validation.
Definition at line 245 of file SessionController.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.ProcessBridgeCommand(), and Tgstation.Server.Host.Components.Session.SessionController.SessionController().
primeTcs
volatile TaskCompletionSource Tgstation.Server.Host.Components.Session.SessionController.primeTcs private
The TaskCompletionSource that completes when DD tells us it's primed.
Definition at line 230 of file SessionController.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.ProcessBridgeCommand(), and Tgstation.Server.Host.Components.Session.SessionController.SessionController().
process
readonly IProcess Tgstation.Server.Host.Components.Session.SessionController.process private
The IProcess for the SessionController.
Definition at line 150 of file SessionController.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.CreateDump(), Tgstation.Server.Host.Components.Session.SessionController.DisposeAsync(), Tgstation.Server.Host.Components.Session.SessionController.GetLaunchResult(), Tgstation.Server.Host.Components.Session.SessionController.PostValidationShutdown(), Tgstation.Server.Host.Components.Session.SessionController.ProcessBridgeCommand(), and Tgstation.Server.Host.Components.Session.SessionController.SessionController().
rebootBridgeRequestsProcessing
volatile uint Tgstation.Server.Host.Components.Session.SessionController.rebootBridgeRequestsProcessing private
The number of currently active calls to ProcessBridgeRequest(BridgeParameters, CancellationToken) from TgsReboot().
Definition at line 250 of file SessionController.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.ProcessBridgeCommand().
rebootGate
volatile Task Tgstation.Server.Host.Components.Session.SessionController.rebootGate private
Backing field for RebootGate.
Definition at line 235 of file SessionController.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.ProcessBridgeCommand(), and Tgstation.Server.Host.Components.Session.SessionController.SessionController().
rebootTcs
volatile TaskCompletionSource Tgstation.Server.Host.Components.Session.SessionController.rebootTcs private
The TaskCompletionSource that completes when DD tells us about a reboot.
Definition at line 225 of file SessionController.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.ProcessBridgeCommand(), and Tgstation.Server.Host.Components.Session.SessionController.SessionController().
released
bool Tgstation.Server.Host.Components.Session.SessionController.released private
If process should be kept alive instead.
Definition at line 265 of file SessionController.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.DisposeAsync(), Tgstation.Server.Host.Components.Session.SessionController.Release(), and Tgstation.Server.Host.Components.Session.SessionController.SessionController().
sessionDurationCts
readonly CancellationTokenSource Tgstation.Server.Host.Components.Session.SessionController.sessionDurationCts private
A CancellationTokenSource used for tasks that should not exceed the lifetime of the session.
Definition at line 205 of file SessionController.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.DisposeAsync(), Tgstation.Server.Host.Components.Session.SessionController.GetLaunchResult(), Tgstation.Server.Host.Components.Session.SessionController.SessionController(), and Tgstation.Server.Host.Components.Session.SessionController.TriggerCustomEvent().
startupTcs
volatile TaskCompletionSource Tgstation.Server.Host.Components.Session.SessionController.startupTcs private
The TaskCompletionSource that completes when DD sends a valid startup bridge request.
Definition at line 220 of file SessionController.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.ProcessBridgeCommand(), and Tgstation.Server.Host.Components.Session.SessionController.SessionController().
synchronizationLock
readonly object Tgstation.Server.Host.Components.Session.SessionController.synchronizationLock private
lock object for port updates and disposed.
Definition at line 210 of file SessionController.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.DisposeAsync(), and Tgstation.Server.Host.Components.Session.SessionController.SessionController().
terminationWasIntentionalForced
bool Tgstation.Server.Host.Components.Session.SessionController.terminationWasIntentionalForced private
Backing field for overriding TerminationWasIntentional.
Definition at line 270 of file SessionController.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.ProcessBridgeCommand().
Property Documentation
ApiValidationStatus
ApiValidationStatus Tgstation.Server.Host.Components.Session.SessionController.ApiValidationStatus get
The DMAPI Session.ApiValidationStatus.
Implements Tgstation.Server.Host.Components.Session.ISessionController.
Definition at line 49 of file SessionController.cs.
        {
            get
            {
                if (!Lifetime.IsCompleted)
                    throw new InvalidOperationException("ApiValidated cannot be checked while Lifetime is incomplete!");
                return apiValidationStatus;
            }
        }
CompileJob
Models.CompileJob Tgstation.Server.Host.Components.Session.SessionController.CompileJob get
Gets the CompileJob associated with the ISessionController.
Implements Tgstation.Server.Host.Components.Session.ISessionController.
Definition at line 60 of file SessionController.cs.
DMApiAvailable
bool Tgstation.Server.Host.Components.Session.SessionController.DMApiAvailable get
If the DMAPI may be used this session.
Implements Tgstation.Server.Host.Components.Session.ISessionController.
Definition at line 111 of file SessionController.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.GetLaunchResult(), Tgstation.Server.Host.Components.Session.SessionController.ProcessBridgeRequest(), Tgstation.Server.Host.Components.Session.SessionController.SendCommand(), and Tgstation.Server.Host.Components.Session.SessionController.SessionController().
DMApiParameters
DMApiParameters Tgstation.Server.Host.Components.Session.SessionController.DMApiParameters get
The DMApiParameters for the IBridgeHandler.
Implements Tgstation.Server.Host.Components.Interop.Bridge.IBridgeHandler.
Definition at line 46 of file SessionController.cs.
DMApiVersion
Version? Tgstation.Server.Host.Components.Session.SessionController.DMApiVersion get private set
The DMAPI Version.
Implements Tgstation.Server.Host.Components.Session.ISessionController.
Definition at line 69 of file SessionController.cs.
{ get; private set; }
Referenced by Tgstation.Server.Host.Components.Session.SessionController.ProcessBridgeCommand().
DumpFileExtension
string Tgstation.Server.Host.Components.Session.SessionController.DumpFileExtension get
The file extension to use for process dumps created from this session.
Implements Tgstation.Server.Host.Components.Session.ISessionController.
Definition at line 117 of file SessionController.cs.
EngineVersion
EngineVersion Tgstation.Server.Host.Components.Session.SessionController.EngineVersion get
Gets the Api.Models.EngineVersion associated with the ISessionController.
Implements Tgstation.Server.Host.Components.Session.ISessionController.
Definition at line 63 of file SessionController.cs.
LaunchResult
Task<LaunchResult> Tgstation.Server.Host.Components.Session.SessionController.LaunchResult get
A Task that completes when DreamDaemon starts pumping the windows message queue after loading a .dmb or when it crashes.
Implements Tgstation.Server.Host.Components.Session.ISessionController.
Definition at line 75 of file SessionController.cs.
{ get; }
LaunchTime
DateTimeOffset? Tgstation.Server.Host.Components.Session.SessionController.LaunchTime get
When the process was started.
Implements Tgstation.Server.Host.System.IProcessBase.
Definition at line 135 of file SessionController.cs.
Lifetime
Task<int?> Tgstation.Server.Host.Components.Session.SessionController.Lifetime get
The Task<TResult> resulting in the exit code of the process or null if the process was detached.
Implements Tgstation.Server.Host.System.IProcessBase.
Definition at line 78 of file SessionController.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Session.SessionController.DisposeAsync(), Tgstation.Server.Host.Components.Session.SessionController.SendCommand(), and Tgstation.Server.Host.Components.Session.SessionController.SessionController().
MemoryUsage
long? Tgstation.Server.Host.Components.Session.SessionController.MemoryUsage get
Gets the process' memory usage in bytes.
Implements Tgstation.Server.Host.System.IProcessBase.
Definition at line 132 of file SessionController.cs.
OnPrime
Task Tgstation.Server.Host.Components.Session.SessionController.OnPrime get
A Task that completes when the server calls /world/TgsInitializationComplete().
Implements Tgstation.Server.Host.Components.Session.ISessionController.
Definition at line 108 of file SessionController.cs.
OnReboot
Task Tgstation.Server.Host.Components.Session.SessionController.OnReboot get
A Task that completes when the server calls /world/TgsReboot().
Implements Tgstation.Server.Host.Components.Session.ISessionController.
Definition at line 84 of file SessionController.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.SendCommand().
OnStartup
Task Tgstation.Server.Host.Components.Session.SessionController.OnStartup get
A Task that completes when the server calls /world/TgsNew().
Implements Tgstation.Server.Host.Components.Session.ISessionController.
Definition at line 81 of file SessionController.cs.
ProcessingRebootBridgeRequest
bool Tgstation.Server.Host.Components.Session.SessionController.ProcessingRebootBridgeRequest get
If the ISessionController is currently processing a bridge request from TgsReboot().
Implements Tgstation.Server.Host.Components.Session.ISessionController.
Definition at line 114 of file SessionController.cs.
ReattachInformation
ReattachInformation Tgstation.Server.Host.Components.Session.SessionController.ReattachInformation get
The up to date Session.ReattachInformation.
Implements Tgstation.Server.Host.Components.Session.ISessionController.
Definition at line 124 of file SessionController.cs.
{ get; }
RebootGate
Task Tgstation.Server.Host.Components.Session.SessionController.RebootGate get set
A Task that must complete before a TgsReboot() bridge request can complete.
Implements Tgstation.Server.Host.Components.Session.ISessionController.
Definition at line 90 of file SessionController.cs.
        {
            get => rebootGate;
            set
            {
                var tcs = new TaskCompletionSource<Task>();
                async Task Wrap()
                {
                    var toAwait = await tcs.Task;
                    await toAwait;
                    await value;
                }
                tcs.SetResult(Interlocked.Exchange(ref rebootGate, Wrap()));
            }
        }
Referenced by Tgstation.Server.Host.Components.Session.SessionController.ProcessBridgeCommand().
RebootState
RebootState Tgstation.Server.Host.Components.Session.SessionController.RebootState get
The current RebootState.
Implements Tgstation.Server.Host.Components.Session.ISessionController.
Definition at line 66 of file SessionController.cs.
StartupBridgeRequestsReceived
long? Tgstation.Server.Host.Components.Session.SessionController.StartupBridgeRequestsReceived get private set
The number of times a startup bridge request has been received. null if DMApiAvailable is false.
Implements Tgstation.Server.Host.Components.Session.ISessionController.
Definition at line 87 of file SessionController.cs.
{ get; private set; }
Referenced by Tgstation.Server.Host.Components.Session.SessionController.ProcessBridgeCommand(), and Tgstation.Server.Host.Components.Session.SessionController.SessionController().
TerminationWasIntentional
bool Tgstation.Server.Host.Components.Session.SessionController.TerminationWasIntentional get
If the DreamDaemon instance sent a.
Implements Tgstation.Server.Host.Components.Session.ISessionController.
Definition at line 72 of file SessionController.cs.
TopicSendSemaphore
FifoSemaphore Tgstation.Server.Host.Components.Session.SessionController.TopicSendSemaphore get
The FifoSemaphore used to prevent concurrent calls into /world/Topic().
Definition at line 129 of file SessionController.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Session.SessionController.DisposeAsync(), Tgstation.Server.Host.Components.Session.SessionController.SendRawTopic(), and Tgstation.Server.Host.Components.Session.SessionController.SessionController().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Session/SessionController.cs