tgstation-server: TGServerService.Program Class Reference
TGServerService.Program Class Reference
Static Public Member Functions
static void CopyFileForceDirectories (string source, string dest, bool overwrite)
Copy a file from source to dest , but first ensure the destination directory exists
static void DeleteDirectory (string path, bool ContentsOnly=false, IList< string > excludeRoot=null)
Recursive directory deleter
static void CopyDirectory (string sourceDirName, string destDirName, IList< string > ignore=null, bool ignoreIfNotExists=false)
Recusively copy a directory
static string SanitizeTopicString (string input)
Properly escapes characters for a BYOND Topic() packet. See http://www.byond.com/docs/ref/info.html#/proc/list2params
static string NormalizePath (string path)
Normalizes different versions of a path string
Static Private Member Functions
static void Main ()
Entry point to the program
static bool CheckDeleteSymlinkDir (DirectoryInfo di)
Properly unlinks directory di if it is a symlink
static void NormalizeAndDelete (DirectoryInfo dir, IList< string > excludeRoot)
Recursively empty a directory
static void CopyDirectoryImpl (string sourceDirName, string destDirName, IList< string > ignore, bool ignoreIfNotExists)
Recusively copy a directory
Detailed Description
Definition at line 8 of file Program.cs.
Member Function Documentation
static bool TGServerService.Program.CheckDeleteSymlinkDir (DirectoryInfo di) static private
Properly unlinks directory di if it is a symlink
Parameters
di DirectoryInfo for the directory in question
Returns
if di was a symlink and deleted, otherwise
Definition at line 66 of file Program.cs.
Referenced by TGServerService.Program.DeleteDirectory(), and TGServerService.Program.NormalizeAndDelete().
         {
             if (!di.Attributes.HasFlag(FileAttributes.Directory))
             {    //this is probably a symlink
                 Directory.Delete(di.FullName);
                 return true;
             }
             return false;
         }
static void TGServerService.Program.CopyDirectory (string sourceDirName, string destDirName, IList< string > ignore = null, bool ignoreIfNotExists = false) static
Recusively copy a directory
Parameters
sourceDirName The directory to copy
destDirName The destination directory
ignore List of files and directories to ignore while copying
ignoreIfNotExists If no error will be thrown if sourceDirName does not exist
Definition at line 108 of file Program.cs.
References TGServerService.Program.CopyDirectoryImpl().
Referenced by TGServerService.ServerInstance.BackupAndDeleteStaticDirectory(), TGServerService.ServerInstance.CompileImpl(), and TGServerService.ServerInstance.InitialConfigureRepository().
         {
             IList<string> realIgnore;
             if (ignore != null)
             {
                 realIgnore = new List<string>();
                 foreach (var I in ignore)
                     realIgnore.Add(I.ToLower());
             }
             else
                 realIgnore = null;
             CopyDirectoryImpl(sourceDirName, destDirName, realIgnore, ignoreIfNotExists);
         }
static void TGServerService.Program.CopyDirectoryImpl (string sourceDirName, string destDirName, IList< string > ignore, bool ignoreIfNotExists) static private
Recusively copy a directory
Parameters
sourceDirName The directory to copy
destDirName The destination directory
ignore List of lowercase files and directories to ignore while copying
ignoreIfNotExists If no error will be thrown if sourceDirName does not exist
Definition at line 129 of file Program.cs.
Referenced by TGServerService.Program.CopyDirectory().
{
             // If the destination directory doesn't exist, create it.
             if (!Directory.Exists(destDirName))
             {
                 Directory.CreateDirectory(destDirName);
             }
             // Get the subdirectories for the specified directory.
             DirectoryInfo dir = new DirectoryInfo(sourceDirName);
             if (!dir.Exists)
             {
                 if (ignoreIfNotExists)
                     return;
                 throw new DirectoryNotFoundException(
                     "Source directory does not exist or could not be found: "
                     + sourceDirName);
             }
             DirectoryInfo[] dirs = dir.GetDirectories();
             // Get the files in the directory and copy them to the new location.
             FileInfo[] files = dir.GetFiles();
             foreach (FileInfo file in files)
             {
                 if (ignore != null && ignore.Contains(file.Name.ToLower()))
                     continue;
                 string temppath = Path.Combine(destDirName, file.Name);
                 file.CopyTo(temppath, true);
             }
             // copy them and their contents to new location.
             foreach (DirectoryInfo subdir in dirs)
             {
                 if (ignore != null && ignore.Contains(subdir.Name.ToLower()))
                     continue;
                 string temppath = Path.Combine(destDirName, subdir.Name);
                 CopyDirectoryImpl(subdir.FullName, temppath, ignore, false);
             }
         }
static void TGServerService.Program.CopyFileForceDirectories (string source, string dest, bool overwrite) static
Copy a file from source to dest , but first ensure the destination directory exists
Parameters
source The source file
dest The destination file
overwrite If , source will overwrite dest if it is a file. Otherwise, if dest exists, an exception will be thrown
Definition at line 24 of file Program.cs.
Referenced by TGServerService.ServerInstance.InitialConfigureRepository().
         {
             try
             {
                 Directory.CreateDirectory(Path.GetDirectoryName(dest));
             }
             catch { }   //we don't care if the above errors
             File.Copy(source, dest, overwrite);    //if this throws errors thats all we care about
         }
static void TGServerService.Program.DeleteDirectory (string path, bool ContentsOnly = false, IList< string > excludeRoot = null) static
Recursive directory deleter
Parameters
path The directory to delete
ContentsOnly If , an empty path will remain instead of being deleted fully. Incompatible with excludeRoot
excludeRoot If any files or directories in the root level of path match anything in this IList<T> of strings, they won't be deleted. Incompatible with ContentsOnly
Definition at line 41 of file Program.cs.
References TGServerService.Program.CheckDeleteSymlinkDir(), and TGServerService.Program.NormalizeAndDelete().
Referenced by TGServerService.ServerInstance.ApplyStagedUpdate(), TGServerService.ServerInstance.BackupAndDeleteStaticDirectory(), TGServerService.ServerInstance.CleanByondStaging(), TGServerService.ServerInstance.Clone(), TGServerService.ServerInstance.CompileImpl(), TGServerService.ServerInstance.DeleteFile(), TGServerService.ServerInstance.InitializeImpl(), and TGServerService.ServerInstance.UpdateSubmodules().
         {
             var di = new DirectoryInfo(path);
             if (!di.Exists)
                 return;
             if (excludeRoot != null)
                 for (var I = 0; I < excludeRoot.Count; ++I)
                     excludeRoot[I] = excludeRoot[I].ToLower();
             if (CheckDeleteSymlinkDir(di))
                 return;
             NormalizeAndDelete(di, excludeRoot);
             if (!ContentsOnly)
             {
                 if (excludeRoot != null && excludeRoot.Count > 0)
                     throw new Exception("Cannot fully delete folder with exclusions specified!");
                 di.Delete(true);
             }
         }
static void TGServerService.Program.Main () static private
Entry point to the program
Definition at line 13 of file Program.cs.
{
             using (var S = new Service())
                 ServiceBase.Run(S);
         }
static void TGServerService.Program.NormalizeAndDelete (DirectoryInfo dir, IList< string > excludeRoot) static private
Recursively empty a directory
Parameters
dir DirectoryInfo of the directory to empty
excludeRoot Lowercase file and directory names to skip while emptying this level. Not passed forward
Definition at line 81 of file Program.cs.
References TGServerService.Program.CheckDeleteSymlinkDir().
Referenced by TGServerService.Program.DeleteDirectory().
         {
             foreach (var subDir in dir.GetDirectories())
             {
                 if (excludeRoot != null && excludeRoot.Contains(subDir.Name.ToLower()))
                     continue;
                 if (CheckDeleteSymlinkDir(subDir))
                     continue;
                 NormalizeAndDelete(subDir, null);
                 subDir.Delete(true);
             }
             foreach (var file in dir.GetFiles())
             {
                 if (excludeRoot != null && excludeRoot.Contains(file.Name.ToLower()))
                     continue;
                 file.Attributes = FileAttributes.Normal;
                 file.Delete();
             }
         }
static string TGServerService.Program.NormalizePath (string path) static
Normalizes different versions of a path string
Parameters
path The path to normalize
Returns
The normalized path
Definition at line 184 of file Program.cs.
Referenced by TGServerService.DeprecatedInstanceConfig.CreateFromNETSettings(), TGServerService.Service.CreateInstance(), and TGServerService.Service.ImportInstance().
         {
             return Path.GetFullPath(new Uri(path).LocalPath)
                        .TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar)
                        .ToUpperInvariant();
         }
static string TGServerService.Program.SanitizeTopicString (string input) static
Properly escapes characters for a BYOND Topic() packet. See http://www.byond.com/docs/ref/info.html#/proc/list2params
Parameters
input The string to sanitize
Returns
The sanitized string
Definition at line 174 of file Program.cs.
Referenced by TGServerService.ChatCommands.ServerChatCommand.Run(), and TGServerService.ServerInstance.WorldAnnounce().
         {
             return input.Replace("%", "%25").Replace("=", "%3d").Replace(";", "%3b").Replace("&", "%26").Replace("+", "%2b");
         }
The documentation for this class was generated from the following file:
TGServerService/Program.cs