tgstation-server: Tgstation.Server.Host.Components.Chat.Providers.Provider Class Reference
Tgstation.Server.Host.Components.Chat.Providers.Provider Class Reference abstract
Public Member Functions
virtual async ValueTask DisposeAsync ()
async Task Disconnect (CancellationToken cancellationToken)
Gracefully disconnects the provider. Permanently stops the reconnection timer.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
void InitialMappingComplete ()
Indicate to the provider that at least one MapChannels(IEnumerable<ChatChannel>, CancellationToken) call has successfully completed.
async Task< Dictionary< ChatChannel, IEnumerable< ChannelRepresentation > > > MapChannels (IEnumerable< ChatChannel > channels, CancellationToken cancellationToken)
Get the ChannelRepresentations for given channels .
Parameters
channels The Api.Models.ChatChannels to map.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in a Dictionary<TKey, TValue> of the ChatChannel's ChannelRepresentations representing channels .
async Task< Message > NextMessage (CancellationToken cancellationToken)
Get a Task<TResult> resulting in the next Message the IProvider recieves or null on a disconnect.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the next available Message or null if the IProvider needed to reconnect.
Note that private messages will come in the form of ChannelRepresentations not returned in MapChannels(IEnumerable<ChatChannel>, CancellationToken). Do not IDisposable.Dispose the IProvider on continuations run from the returned Task.
Task SetReconnectInterval (uint reconnectInterval, bool connectNow)
Set the interval at which the provider starts jobs to try to reconnect.
Parameters
reconnectInterval The reconnection interval in minutes.
connectNow If a connection attempt should be made now.
Returns
A Task representing the running operation.
abstract Task SendMessage (Message replyTo, MessageContent message, ulong channelId, CancellationToken cancellationToken)
Send a message to the IProvider.
Parameters
replyTo The Message to reply to.
message The MessageContent.
channelId The ChannelRepresentation.RealId to send to.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
abstract Task< Func< string, string, Task > > SendUpdateMessage (RevisionInformation revisionInformation, Version byondVersion, DateTimeOffset? estimatedCompletionTime, string gitHubOwner, string gitHubRepo, ulong channelId, bool localCommitPushed, CancellationToken cancellationToken)
Send the message for a deployment.
Parameters
revisionInformation The RevisionInformation of the deployment.
byondVersion The BYOND Version of the deployment.
estimatedCompletionTime The optional DateTimeOffset the deployment is expected to be completed at.
gitHubOwner The repository GitHub owner, if any.
gitHubRepo The repository GitHub name, if any.
channelId The ChannelRepresentation.RealId to send to.
localCommitPushed true if the local deployment commit was pushed to the remote repository.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in a Func<T1, T2, TResult> to call to update the message at the deployment's conclusion. Parameters: Error message if any, DreamMaker output if any.
void InitialMappingComplete ()
Indicate to the provider that at least one MapChannels(IEnumerable<ChatChannel>, CancellationToken) call has successfully completed.
Task< Message > NextMessage (CancellationToken cancellationToken)
Get a Task<TResult> resulting in the next Message the IProvider recieves or null on a disconnect.
Task Disconnect (CancellationToken cancellationToken)
Gracefully disconnects the provider. Permanently stops the reconnection timer.
Task< Dictionary< ChatChannel, IEnumerable< ChannelRepresentation > > > MapChannels (IEnumerable< ChatChannel > channels, CancellationToken cancellationToken)
Get the ChannelRepresentations for given channels .
Task SendMessage (Message replyTo, MessageContent message, ulong channelId, CancellationToken cancellationToken)
Send a message to the IProvider.
Task SetReconnectInterval (uint reconnectInterval, bool connectNow)
Set the interval at which the provider starts jobs to try to reconnect.
Task< Func< string, string, Task > > SendUpdateMessage (RevisionInformation revisionInformation, Version byondVersion, DateTimeOffset? estimatedCompletionTime, string gitHubOwner, string gitHubRepo, ulong channelId, bool localCommitPushed, CancellationToken cancellationToken)
Send the message for a deployment.
Protected Member Functions
Provider (IJobManager jobManager, IAsyncDelayer asyncDelayer, ILogger< Provider > logger, ChatBot chatBot)
Initializes a new instance of the Provider class.
abstract Task Connect (CancellationToken cancellationToken)
Attempt to connect the Provider.
abstract Task DisconnectImpl (CancellationToken cancellationToken)
Gracefully disconnects the provider.
abstract Task< Dictionary< ChatChannel, IEnumerable< ChannelRepresentation > > > MapChannelsImpl (IEnumerable< ChatChannel > channels, CancellationToken cancellationToken)
Implementation of MapChannels(IEnumerable<ChatChannel>, CancellationToken).
void EnqueueMessage (Message message)
Queues a message for NextMessage(CancellationToken).
Properties
Task InitialConnectionJob [get]
A Task that completes once the IProvider finishes it's first connection attempt regardless of success.
ChatBot ChatBot [get]
The ChatBot the Provider is for.
IAsyncDelayer AsyncDelayer [get]
The IAsyncDelayer for the Provider.
ILogger< Provider > Logger [get]
The ILogger for the Provider.
abstract bool Connected [get]
If the IProvider is currently connected.
abstract string BotMention [get]
The string that indicates the IProvider was mentioned.
bool Disposed [get, private set]
If the IProvider was disposed.
Properties inherited from Tgstation.Server.Host.Components.Chat.Providers.IProvider
bool Connected [get]
If the IProvider is currently connected.
bool Disposed [get]
If the IProvider was disposed.
string BotMention [get]
The string that indicates the IProvider was mentioned.
Task InitialConnectionJob [get]
A Task that completes once the IProvider finishes it's first connection attempt regardless of success.
Private Member Functions
Task StopReconnectionTimer ()
Stops and awaits the reconnectTask.
async Task ReconnectionLoop (uint reconnectInterval, bool connectNow, CancellationToken cancellationToken)
Creates a Task that will attempt to reconnect the Provider every reconnectInterval minutes.
Private Attributes
readonly IJobManager jobManager
The IJobManager for the Provider.
readonly Queue< Message > messageQueue
Queue<T> of received Messages.
readonly TaskCompletionSource initialConnectionTcs
The backing TaskCompletionSource for InitialConnectionJob.
readonly object reconnectTaskLock
Used for synchronizing access to reconnectCts and reconnectTask.
TaskCompletionSource nextMessage
TaskCompletionSource that completes while messageQueue isn't empty.
Task reconnectTask
The auto reconnect Task.
CancellationTokenSource reconnectCts
CancellationTokenSource for reconnectTask.
Detailed Description
Definition at line 17 of file Provider.cs.
Constructor & Destructor Documentation
Provider()
Tgstation.Server.Host.Components.Chat.Providers.Provider.Provider (IJobManager jobManager, IAsyncDelayer asyncDelayer, ILogger< Provider > logger, ChatBot chatBot) protected
Initializes a new instance of the Provider class.
Parameters
jobManager The value of jobManager.
asyncDelayer The value of AsyncDelayer.
logger The value of Logger.
chatBot The value of chatBot .
Definition at line 79 of file Provider.cs.
        {
            this.jobManager = jobManager ?? throw new ArgumentNullException(nameof(jobManager));
            AsyncDelayer = asyncDelayer ?? throw new ArgumentNullException(nameof(asyncDelayer));
            Logger = logger ?? throw new ArgumentNullException(nameof(logger));
            ChatBot = chatBot ?? throw new ArgumentNullException(nameof(chatBot));
            messageQueue = new Queue<Message>();
            nextMessage = new TaskCompletionSource();
            initialConnectionTcs = new TaskCompletionSource();
            reconnectTaskLock = new object();
            logger.LogTrace("Created.");
        }
References Tgstation.Server.Host.Components.Chat.Providers.Provider.initialConnectionTcs, Tgstation.Server.Host.Components.Chat.Providers.Provider.jobManager, Tgstation.Server.Host.Components.Chat.Providers.Provider.Logger, Tgstation.Server.Host.Components.Chat.Providers.Provider.messageQueue, Tgstation.Server.Host.Components.Chat.Providers.Provider.nextMessage, and Tgstation.Server.Host.Components.Chat.Providers.Provider.reconnectTaskLock.
Member Function Documentation
Connect()
abstract Task Tgstation.Server.Host.Components.Chat.Providers.Provider.Connect (CancellationToken cancellationToken) protected pure virtual
Attempt to connect the Provider.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider, and Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.Provider.ReconnectionLoop().
Disconnect()
async Task Tgstation.Server.Host.Components.Chat.Providers.Provider.Disconnect (CancellationToken cancellationToken)
Gracefully disconnects the provider. Permanently stops the reconnection timer.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implements Tgstation.Server.Host.Components.Chat.Providers.IProvider.
Definition at line 115 of file Provider.cs.
        {
            await StopReconnectionTimer();
            if (Connected)
            {
                Logger.LogTrace("Disconnecting...");
                await DisconnectImpl(cancellationToken);
                Logger.LogTrace("Disconnected");
            }
        }
References Tgstation.Server.Host.Components.Chat.Providers.Provider.Connected, Tgstation.Server.Host.Components.Chat.Providers.Provider.DisconnectImpl(), Tgstation.Server.Host.Components.Chat.Providers.Provider.Logger, and Tgstation.Server.Host.Components.Chat.Providers.Provider.StopReconnectionTimer().
DisconnectImpl()
abstract Task Tgstation.Server.Host.Components.Chat.Providers.Provider.DisconnectImpl (CancellationToken cancellationToken) protected pure virtual
Gracefully disconnects the provider.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider, and Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.Provider.Disconnect(), and Tgstation.Server.Host.Components.Chat.Providers.Provider.ReconnectionLoop().
DisposeAsync()
virtual async ValueTask Tgstation.Server.Host.Components.Chat.Providers.Provider.DisposeAsync () virtual
Reimplemented in Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider, and Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.
Definition at line 104 of file Provider.cs.
        {
            Disposed = true;
            await StopReconnectionTimer();
            // queue a final message to shutdown the NextMessage Task
            EnqueueMessage(null);
            Logger.LogTrace("Disposed");
        }
References Tgstation.Server.Host.Components.Chat.Providers.Provider.Disposed, Tgstation.Server.Host.Components.Chat.Providers.Provider.EnqueueMessage(), Tgstation.Server.Host.Components.Chat.Providers.Provider.Logger, and Tgstation.Server.Host.Components.Chat.Providers.Provider.StopReconnectionTimer().
EnqueueMessage()
void Tgstation.Server.Host.Components.Chat.Providers.Provider.EnqueueMessage (Message message) protected
Queues a message for NextMessage(CancellationToken).
Parameters
message The Message to queue. A value of null indicates the channel mappings are out of date.
Definition at line 222 of file Provider.cs.
        {
            if (message == null)
                Logger.LogTrace("Requesting channel remap...");
            lock (messageQueue)
            {
                messageQueue.Enqueue(message);
                nextMessage.TrySetResult();
            }
        }
References Tgstation.Server.Host.Components.Chat.Providers.Provider.Logger, Tgstation.Server.Host.Components.Chat.Providers.Provider.messageQueue, and Tgstation.Server.Host.Components.Chat.Providers.Provider.nextMessage.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.Provider.DisposeAsync(), Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.MapChannelsImpl(), Tgstation.Server.Host.Components.Chat.Providers.Provider.ReconnectionLoop(), Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.RespondAsync(), and Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.SendMessage().
InitialMappingComplete()
void Tgstation.Server.Host.Components.Chat.Providers.Provider.InitialMappingComplete ()
Indicate to the provider that at least one MapChannels(IEnumerable<ChatChannel>, CancellationToken) call has successfully completed.
Implements Tgstation.Server.Host.Components.Chat.Providers.IProvider.
MapChannels()
async Task< Dictionary< ChatChannel, IEnumerable< ChannelRepresentation > > > Tgstation.Server.Host.Components.Chat.Providers.Provider.MapChannels (IEnumerable< ChatChannel > channels, CancellationToken cancellationToken)
Get the ChannelRepresentations for given channels .
Parameters
channels The Api.Models.ChatChannels to map.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in a Dictionary<TKey, TValue> of the ChatChannel's ChannelRepresentations representing channels .
Implements Tgstation.Server.Host.Components.Chat.Providers.IProvider.
Definition at line 131 of file Provider.cs.
        {
            ArgumentNullException.ThrowIfNull(channels);
            try
            {
                return await MapChannelsImpl(channels, cancellationToken);
            }
            catch
            {
                initialConnectionTcs.TrySetResult();
                throw;
            }
        }
References Tgstation.Server.Host.Components.Chat.Providers.Provider.initialConnectionTcs, and Tgstation.Server.Host.Components.Chat.Providers.Provider.MapChannelsImpl().
MapChannelsImpl()
abstract Task< Dictionary< ChatChannel, IEnumerable< ChannelRepresentation > > > Tgstation.Server.Host.Components.Chat.Providers.Provider.MapChannelsImpl (IEnumerable< ChatChannel > channels, CancellationToken cancellationToken) protected pure virtual
Implementation of MapChannels(IEnumerable<ChatChannel>, CancellationToken).
Parameters
channels The ChatChannels to map.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in a Dictionary<TKey, TValue> of the ChatChannel's ChannelRepresentations representing channels .
Referenced by Tgstation.Server.Host.Components.Chat.Providers.Provider.MapChannels().
NextMessage()
async Task< Message > Tgstation.Server.Host.Components.Chat.Providers.Provider.NextMessage (CancellationToken cancellationToken)
Get a Task<TResult> resulting in the next Message the IProvider recieves or null on a disconnect.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the next available Message or null if the IProvider needed to reconnect.
Note that private messages will come in the form of ChannelRepresentations not returned in MapChannels(IEnumerable<ChatChannel>, CancellationToken). Do not IDisposable.Dispose the IProvider on continuations run from the returned Task.
Implements Tgstation.Server.Host.Components.Chat.Providers.IProvider.
Definition at line 147 of file Provider.cs.
        {
            while (true)
            {
                await nextMessage.Task.WaitAsync(cancellationToken);
                lock (messageQueue)
                    if (messageQueue.Count > 0)
                    {
                        var result = messageQueue.Dequeue();
                        if (messageQueue.Count == 0)
                            nextMessage = new TaskCompletionSource();
                        return result;
                    }
            }
        }
References Tgstation.Server.Host.Components.Chat.Providers.Provider.messageQueue, and Tgstation.Server.Host.Components.Chat.Providers.Provider.nextMessage.
ReconnectionLoop()
async Task Tgstation.Server.Host.Components.Chat.Providers.Provider.ReconnectionLoop (uint reconnectInterval, bool connectNow, CancellationToken cancellationToken) private
Creates a Task that will attempt to reconnect the Provider every reconnectInterval minutes.
Parameters
reconnectInterval The amount of minutes to wait between reconnection attempts.
connectNow If a connection attempt should be immediately made.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Definition at line 264 of file Provider.cs.
        {
            do
            {
                try
                {
                    if (!connectNow)
                        await AsyncDelayer.Delay(TimeSpan.FromMinutes(reconnectInterval), cancellationToken);
                    else
                        connectNow = false;
                    if (!Connected)
                    {
                        var job = new Job
{
                            Description = $"Reconnect chat bot: {ChatBot.Name}",
                            CancelRight = (ulong)ChatBotRights.WriteEnabled,
                            CancelRightsType = RightsType.ChatBots,
                            Instance = ChatBot.Instance,
                        };
                        await jobManager.RegisterOperation(
                            job,
                            async (core, databaseContextFactory, paramJob, progressReporter, jobCancellationToken) =>
{
                                try
{
                                    if (Connected)
{
                                        Logger.LogTrace("Disconnecting...");
                                        await DisconnectImpl(jobCancellationToken);
                                    }
                                    else
                                        Logger.LogTrace("Already disconnected not doing disconnection attempt!");
                                    Logger.LogTrace("Connecting...");
                                    await Connect(jobCancellationToken);
                                    Logger.LogTrace("Connected successfully");
                                    EnqueueMessage(null);
                                }
                                catch
{
                                    // we set this here because otherwise there could be stuff waiting on to connect us forever
                                    initialConnectionTcs.TrySetResult();
                                    throw;
                                }
                            },
                            cancellationToken);
                        await jobManager.WaitForJobCompletion(job, null, cancellationToken, cancellationToken);
                    }
                }
                catch (OperationCanceledException e)
                {
                    Logger.LogTrace(e, "ReconnectionLoop cancelled");
                }
                catch (Exception e)
                {
                    Logger.LogError(e, "Error reconnecting!");
                }
            }
            while (!cancellationToken.IsCancellationRequested);
            Logger.LogTrace("ReconnectionLoop exiting...");
        }
References Tgstation.Server.Host.Components.Chat.Providers.Provider.Connect(), Tgstation.Server.Host.Components.Chat.Providers.Provider.Connected, Tgstation.Server.Host.Utils.AsyncDelayer.Delay(), Tgstation.Server.Host.Components.Chat.Providers.Provider.DisconnectImpl(), Tgstation.Server.Host.Components.Chat.Providers.Provider.EnqueueMessage(), Tgstation.Server.Host.Components.Chat.Providers.Provider.initialConnectionTcs, Tgstation.Server.Host.Models.ChatBot.Instance, Tgstation.Server.Host.Components.Chat.Providers.Provider.jobManager, Tgstation.Server.Host.Components.Chat.Providers.Provider.Logger, Tgstation.Server.Host.Jobs.IJobManager.RegisterOperation(), and Tgstation.Server.Host.Jobs.IJobManager.WaitForJobCompletion().
Referenced by Tgstation.Server.Host.Components.Chat.Providers.Provider.SetReconnectInterval().
SendMessage()
abstract Task Tgstation.Server.Host.Components.Chat.Providers.Provider.SendMessage (Message replyTo, MessageContent message, ulong channelId, CancellationToken cancellationToken) pure virtual
Send a message to the IProvider.
Parameters
replyTo The Message to reply to.
message The MessageContent.
channelId The ChannelRepresentation.RealId to send to.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implements Tgstation.Server.Host.Components.Chat.Providers.IProvider.
Implemented in Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider, and Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.
SendUpdateMessage()
abstract Task< Func< string, string, Task > > Tgstation.Server.Host.Components.Chat.Providers.Provider.SendUpdateMessage (RevisionInformation revisionInformation, Version byondVersion, DateTimeOffset? estimatedCompletionTime, string gitHubOwner, string gitHubRepo, ulong channelId, bool localCommitPushed, CancellationToken cancellationToken) pure virtual
Send the message for a deployment.
Parameters
revisionInformation The RevisionInformation of the deployment.
byondVersion The BYOND Version of the deployment.
estimatedCompletionTime The optional DateTimeOffset the deployment is expected to be completed at.
gitHubOwner The repository GitHub owner, if any.
gitHubRepo The repository GitHub name, if any.
channelId The ChannelRepresentation.RealId to send to.
localCommitPushed true if the local deployment commit was pushed to the remote repository.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in a Func<T1, T2, TResult> to call to update the message at the deployment's conclusion. Parameters: Error message if any, DreamMaker output if any.
Implements Tgstation.Server.Host.Components.Chat.Providers.IProvider.
SetReconnectInterval()
Task Tgstation.Server.Host.Components.Chat.Providers.Provider.SetReconnectInterval (uint reconnectInterval, bool connectNow)
Set the interval at which the provider starts jobs to try to reconnect.
Parameters
reconnectInterval The reconnection interval in minutes.
connectNow If a connection attempt should be made now.
Returns
A Task representing the running operation.
Implements Tgstation.Server.Host.Components.Chat.Providers.IProvider.
Definition at line 164 of file Provider.cs.
        {
            if (reconnectInterval == 0)
                throw new ArgumentOutOfRangeException(nameof(reconnectInterval), reconnectInterval, "Reconnect interval cannot be zero!");
            Task stopOldTimerTask;
            lock (reconnectTaskLock)
            {
                stopOldTimerTask = StopReconnectionTimer();
                reconnectCts = new CancellationTokenSource();
                reconnectTask = ReconnectionLoop(reconnectInterval, connectNow, reconnectCts.Token);
            }
            return stopOldTimerTask;
        }
References Tgstation.Server.Host.Components.Chat.Providers.Provider.reconnectCts, Tgstation.Server.Host.Components.Chat.Providers.Provider.ReconnectionLoop(), Tgstation.Server.Host.Components.Chat.Providers.Provider.reconnectTask, Tgstation.Server.Host.Components.Chat.Providers.Provider.reconnectTaskLock, and Tgstation.Server.Host.Components.Chat.Providers.Provider.StopReconnectionTimer().
StopReconnectionTimer()
Task Tgstation.Server.Host.Components.Chat.Providers.Provider.StopReconnectionTimer () private
Stops and awaits the reconnectTask.
Returns
A Task representing the running operation.
Definition at line 238 of file Provider.cs.
        {
            Logger.LogTrace("StopReconnectionTimer");
            lock (reconnectTaskLock)
                if (reconnectCts != null)
                {
                    reconnectCts.Cancel();
                    reconnectCts.Dispose();
                    reconnectCts = null;
                    Task reconnectTask = this.reconnectTask;
                    this.reconnectTask = null;
                    return reconnectTask;
                }
                else
                    Logger.LogTrace("Timer wasn't running");
            return Task.CompletedTask;
        }
References Tgstation.Server.Host.Components.Chat.Providers.Provider.Logger, Tgstation.Server.Host.Components.Chat.Providers.Provider.reconnectCts, Tgstation.Server.Host.Components.Chat.Providers.Provider.reconnectTask, and Tgstation.Server.Host.Components.Chat.Providers.Provider.reconnectTaskLock.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.Provider.Disconnect(), Tgstation.Server.Host.Components.Chat.Providers.Provider.DisposeAsync(), and Tgstation.Server.Host.Components.Chat.Providers.Provider.SetReconnectInterval().
Member Data Documentation
initialConnectionTcs
readonly TaskCompletionSource Tgstation.Server.Host.Components.Chat.Providers.Provider.initialConnectionTcs private
The backing TaskCompletionSource for InitialConnectionJob.
Definition at line 50 of file Provider.cs.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.Provider.MapChannels(), Tgstation.Server.Host.Components.Chat.Providers.Provider.Provider(), and Tgstation.Server.Host.Components.Chat.Providers.Provider.ReconnectionLoop().
jobManager
readonly IJobManager Tgstation.Server.Host.Components.Chat.Providers.Provider.jobManager private
The IJobManager for the Provider.
Definition at line 40 of file Provider.cs.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.Provider.Provider(), and Tgstation.Server.Host.Components.Chat.Providers.Provider.ReconnectionLoop().
messageQueue
readonly Queue<Message> Tgstation.Server.Host.Components.Chat.Providers.Provider.messageQueue private
Queue<T> of received Messages.
Definition at line 45 of file Provider.cs.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.Provider.EnqueueMessage(), Tgstation.Server.Host.Components.Chat.Providers.Provider.NextMessage(), and Tgstation.Server.Host.Components.Chat.Providers.Provider.Provider().
nextMessage
TaskCompletionSource Tgstation.Server.Host.Components.Chat.Providers.Provider.nextMessage private
TaskCompletionSource that completes while messageQueue isn't empty.
Definition at line 60 of file Provider.cs.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.Provider.EnqueueMessage(), Tgstation.Server.Host.Components.Chat.Providers.Provider.NextMessage(), and Tgstation.Server.Host.Components.Chat.Providers.Provider.Provider().
reconnectCts
CancellationTokenSource Tgstation.Server.Host.Components.Chat.Providers.Provider.reconnectCts private
CancellationTokenSource for reconnectTask.
Definition at line 70 of file Provider.cs.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.Provider.SetReconnectInterval(), and Tgstation.Server.Host.Components.Chat.Providers.Provider.StopReconnectionTimer().
reconnectTask
Task Tgstation.Server.Host.Components.Chat.Providers.Provider.reconnectTask private
The auto reconnect Task.
Definition at line 65 of file Provider.cs.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.Provider.SetReconnectInterval(), and Tgstation.Server.Host.Components.Chat.Providers.Provider.StopReconnectionTimer().
reconnectTaskLock
readonly object Tgstation.Server.Host.Components.Chat.Providers.Provider.reconnectTaskLock private
Used for synchronizing access to reconnectCts and reconnectTask.
Definition at line 55 of file Provider.cs.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.Provider.Provider(), Tgstation.Server.Host.Components.Chat.Providers.Provider.SetReconnectInterval(), and Tgstation.Server.Host.Components.Chat.Providers.Provider.StopReconnectionTimer().
Property Documentation
AsyncDelayer
IAsyncDelayer Tgstation.Server.Host.Components.Chat.Providers.Provider.AsyncDelayer get protected
The IAsyncDelayer for the Provider.
Definition at line 30 of file Provider.cs.
{ get; }
BotMention
abstract string Tgstation.Server.Host.Components.Chat.Providers.Provider.BotMention get
The string that indicates the IProvider was mentioned.
Implements Tgstation.Server.Host.Components.Chat.Providers.IProvider.
Definition at line 98 of file Provider.cs.
{ get; }
ChatBot
ChatBot Tgstation.Server.Host.Components.Chat.Providers.Provider.ChatBot get protected
The ChatBot the Provider is for.
Definition at line 25 of file Provider.cs.
{ get; }
Connected
abstract bool Tgstation.Server.Host.Components.Chat.Providers.Provider.Connected get
If the IProvider is currently connected.
Implements Tgstation.Server.Host.Components.Chat.Providers.IProvider.
Definition at line 95 of file Provider.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Chat.Providers.Provider.Disconnect(), and Tgstation.Server.Host.Components.Chat.Providers.Provider.ReconnectionLoop().
Disposed
bool Tgstation.Server.Host.Components.Chat.Providers.Provider.Disposed get private set
If the IProvider was disposed.
Implements Tgstation.Server.Host.Components.Chat.Providers.IProvider.
Definition at line 101 of file Provider.cs.
{ get; private set; }
Referenced by Tgstation.Server.Host.Components.Chat.Providers.Provider.DisposeAsync().
InitialConnectionJob
Task Tgstation.Server.Host.Components.Chat.Providers.Provider.InitialConnectionJob get
A Task that completes once the IProvider finishes it's first connection attempt regardless of success.
Implements Tgstation.Server.Host.Components.Chat.Providers.IProvider.
Definition at line 20 of file Provider.cs.
Logger
ILogger<Provider> Tgstation.Server.Host.Components.Chat.Providers.Provider.Logger get protected
The ILogger for the Provider.
Definition at line 35 of file Provider.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.Connect(), Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.ConvertEmbed(), Tgstation.Server.Host.Components.Chat.Providers.Provider.Disconnect(), Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.DisconnectImpl(), Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.DisposeAsync(), Tgstation.Server.Host.Components.Chat.Providers.Provider.DisposeAsync(), Tgstation.Server.Host.Components.Chat.Providers.Provider.EnqueueMessage(), Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.GetAllAccessibleTextChannels(), Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.MapChannelsImpl(), Tgstation.Server.Host.Components.Chat.Providers.Provider.Provider(), Tgstation.Server.Host.Components.Chat.Providers.Provider.ReconnectionLoop(), Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.RespondAsync(), Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.SendMessage(), Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.SendMessage(), Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.SendUpdateMessage(), and Tgstation.Server.Host.Components.Chat.Providers.Provider.StopReconnectionTimer().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Chat/Providers/Provider.cs