tgstation-server: Tgstation.Server.Host.Components.Engine.WindowsByondInstaller Class Reference
Tgstation.Server.Host.Components.Engine.WindowsByondInstaller Class Reference
IEngineInstaller for windows systems.
Public Member Functions
WindowsByondInstaller (IProcessExecutor processExecutor, IIOManager ioManager, IFileDownloader fileDownloader, IOptions< GeneralConfiguration > generalConfigurationOptions, IOptions< SessionConfiguration > sessionConfigurationOptions, ILogger< WindowsByondInstaller > logger)
Initializes a new instance of the WindowsByondInstaller class.
void Dispose ()
override ValueTask Install (EngineVersion version, string path, bool deploymentPipelineProcesses, CancellationToken cancellationToken)
Does actions necessary to get an extracted installation working.
Parameters
version The EngineVersion being installed.
path The path to the installation.
deploymentPipelineProcesses If the operation should consider processes it launches to be part of the deployment pipeline.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
override async ValueTask UpgradeInstallation (EngineVersion version, string path, CancellationToken cancellationToken)
Does actions necessary to get upgrade a version installed by a previous version of TGS.
Parameters
version The EngineVersion being installed.
path The path to the installation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
override async ValueTask TrustDmbPath (EngineVersion version, string fullDmbPath, CancellationToken cancellationToken)
Add a given fullDmbPath to the trusted DMBs list in BYOND's config.
Parameters
version The EngineVersion being used.
fullDmbPath Full path to the .dmb that should be trusted.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Public Member Functions inherited from Tgstation.Server.Host.Components.Engine.ByondInstallerBase
override IEngineInstallation CreateInstallation (EngineVersion version, string path, Task installationTask)
Creates an IEngineInstallation for a given version .
Parameters
version The EngineVersion of the installation.
path The path to the installation.
installationTask The Task representing the installation process for the installation.
Returns
The IEngineInstallation.
override async Task CleanCache (CancellationToken cancellationToken)
Attempts to cleans the engine's cache folder for the system.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
override async ValueTask< IEngineInstallationData > DownloadVersion (EngineVersion version, JobProgressReporter? progressReporter, CancellationToken cancellationToken)
Download a given engine version .
Parameters
version The EngineVersion of the engine to download.
jobProgressReporter The optional JobProgressReporter for the operation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IEngineInstallationData for the download.
abstract IEngineInstallation CreateInstallation (EngineVersion version, string path, Task installationTask)
Creates an IEngineInstallation for a given version .
Parameters
version The EngineVersion of the installation.
path The path to the installation.
installationTask The Task representing the installation process for the installation.
Returns
The IEngineInstallation.
abstract Task CleanCache (CancellationToken cancellationToken)
Attempts to cleans the engine's cache folder for the system.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
abstract ValueTask Install (EngineVersion version, string path, bool deploymentPipelineProcesses, CancellationToken cancellationToken)
Does actions necessary to get an extracted installation working.
Parameters
version The EngineVersion being installed.
path The path to the installation.
deploymentPipelineProcesses If the operation should consider processes it launches to be part of the deployment pipeline.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
abstract ValueTask UpgradeInstallation (EngineVersion version, string path, CancellationToken cancellationToken)
Does actions necessary to get upgrade a version installed by a previous version of TGS.
Parameters
version The EngineVersion being installed.
path The path to the installation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
abstract ValueTask< IEngineInstallationData > DownloadVersion (EngineVersion version, JobProgressReporter? jobProgressReporter, CancellationToken cancellationToken)
Download a given engine version .
Parameters
version The EngineVersion of the engine to download.
jobProgressReporter The optional JobProgressReporter for the operation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IEngineInstallationData for the download.
abstract ValueTask TrustDmbPath (EngineVersion version, string fullDmbPath, CancellationToken cancellationToken)
Add a given fullDmbPath to the trusted DMBs list in BYOND's config.
Parameters
version The EngineVersion being used.
fullDmbPath Full path to the .dmb that should be trusted.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
IEngineInstallation CreateInstallation (EngineVersion version, string path, Task installationTask)
Creates an IEngineInstallation for a given version .
ValueTask< IEngineInstallationData > DownloadVersion (EngineVersion version, JobProgressReporter? jobProgressReporter, CancellationToken cancellationToken)
Download a given engine version .
ValueTask Install (EngineVersion version, string path, bool deploymentPipelineProcesses, CancellationToken cancellationToken)
Does actions necessary to get an extracted installation working.
ValueTask UpgradeInstallation (EngineVersion version, string path, CancellationToken cancellationToken)
Does actions necessary to get upgrade a version installed by a previous version of TGS.
ValueTask TrustDmbPath (EngineVersion version, string fullDmbPath, CancellationToken cancellationToken)
Add a given fullDmbPath to the trusted DMBs list in BYOND's config.
Task CleanCache (CancellationToken cancellationToken)
Attempts to cleans the engine's cache folder for the system.
Protected Member Functions
override string GetDreamDaemonName (Version byondVersion, out bool supportsCli)
Get the file name of the DreamDaemon executable.
Parameters
byondVersion The Version of BYOND to select the executable name for.
supportsCli Whether or not the returned path supports being run as a command-line application.
Returns
The file name of the DreamDaemon executable.
override IEnumerable< string > AdditionalCacheCleanFilePaths (string configDirectory)
List off additional file paths in the configDirectory to delete.
Parameters
configDirectory The full path to the relevant CfgDirectoryName.
Returns
An IEnumerable<T> of paths in configDirectory to clean.
Protected Member Functions inherited from Tgstation.Server.Host.Components.Engine.ByondInstallerBase
ByondInstallerBase (IIOManager ioManager, ILogger< ByondInstallerBase > logger, IFileDownloader fileDownloader)
Initializes a new instance of the ByondInstallerBase class.
abstract string GetDreamDaemonName (Version byondVersion, out bool supportsCli)
Get the file name of the DreamDaemon executable.
virtual IEnumerable< string > AdditionalCacheCleanFilePaths (string configDirectory)
List off additional file paths in the configDirectory to delete.
Protected Member Functions inherited from Tgstation.Server.Host.Components.Engine.EngineInstallerBase
EngineInstallerBase (IIOManager ioManager, ILogger< EngineInstallerBase > logger)
Initializes a new instance of the EngineInstallerBase class.
void CheckVersionValidity (EngineVersion version)
Check that a given version is of type EngineType.Byond.
Properties
static Version DDExeVersion [get]
The first version of BYOND to ship with dd.exe on the Windows build.
override string DreamMakerName [get]
override string PathToUserFolder [get]
override string ByondRevisionsUrlTemplate [get]
Properties inherited from Tgstation.Server.Host.Components.Engine.ByondInstallerBase
override EngineType TargetEngineType [get]
abstract string PathToUserFolder [get]
Path to the system user's local BYOND folder.
abstract string DreamMakerName [get]
Path to the DreamMaker executable.
abstract string ByondRevisionsUrlTemplate [get]
Gets the URL formatter string for downloading a byond version of {0:Major} {1:Minor}.
Properties inherited from Tgstation.Server.Host.Components.Engine.EngineInstallerBase
abstract EngineType TargetEngineType [get]
The EngineType the installer supports.
IIOManager IOManager [get]
Gets the IIOManager for the EngineInstallerBase.
ILogger< EngineInstallerBase > Logger [get]
Gets the ILogger for the EngineInstallerBase.
Private Member Functions
async ValueTask SetNoPromptTrusted (string path, CancellationToken cancellationToken)
Creates the BYOND cfg file that prevents the trusted mode dialog from appearing when launching DreamDaemon.
async ValueTask InstallDirectX (string path, CancellationToken cancellationToken)
Attempt to install the DirectX redistributable included with BYOND.
async ValueTask AddDreamDaemonToFirewall (EngineVersion version, string path, bool deploymentPipelineProcesses, CancellationToken cancellationToken)
Attempt to add the DreamDaemon executable as an exception to the Windows firewall.
Private Attributes
readonly IProcessExecutor processExecutor
The IProcessExecutor for the WindowsByondInstaller.
readonly GeneralConfiguration generalConfiguration
The GeneralConfiguration for the WindowsByondInstaller.
readonly SessionConfiguration sessionConfiguration
The SessionConfiguration for the WindowsByondInstaller.
readonly SemaphoreSlim semaphore
The SemaphoreSlim for the WindowsByondInstaller.
bool installedDirectX
If DirectX was installed.
Static Private Attributes
const string ByondConfigDirectory = "byond/cfg"
Directory to byond installation configuration.
const string ByondDreamDaemonConfigFilename = "daemon.txt"
BYOND's DreamDaemon config file.
const string ByondNoPromptTrustedMode = "trusted-check 0"
Setting to add to ByondDreamDaemonConfigFilename to suppress an invisible user prompt for running a trusted mode .dmb.
const string ByondDXDir = "byond/directx"
The directory that contains the BYOND directx redistributable.
const string TgsFirewalledDDFile = "TGSFirewalledDD"
The file TGS uses to determine if dd.exe has been firewalled.
const string TrustedDmbFileName = "trusted.txt"
The name of the list of trusted .dmb files in the user's BYOND cfg directory.
static readonly SemaphoreSlim UserFilesSemaphore = new(1, 1)
SemaphoreSlim for writing to files in the user's BYOND directory.
Additional Inherited Members
Static Protected Attributes inherited from Tgstation.Server.Host.Components.Engine.ByondInstallerBase
const string ByondBinPath = "byond/bin"
The path to the BYOND bin folder.
const string CfgDirectoryName = "cfg"
The path to the cfg directory.
Detailed Description
IEngineInstaller for windows systems.
Definition at line 23 of file WindowsByondInstaller.cs.
Constructor & Destructor Documentation
WindowsByondInstaller()
Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.WindowsByondInstaller (IProcessExecutor processExecutor, IIOManager ioManager, IFileDownloader fileDownloader, IOptions< GeneralConfiguration > generalConfigurationOptions, IOptions< SessionConfiguration > sessionConfigurationOptions, ILogger< WindowsByondInstaller > logger)
Initializes a new instance of the WindowsByondInstaller class.
Parameters
processExecutor The value of processExecutor.
generalConfigurationOptions The IOptions<TOptions> containing the value of generalConfiguration.
sessionConfigurationOptions The IOptions<TOptions> containing the value of sessionConfiguration.
ioManager The IIOManager for the ByondInstallerBase.
fileDownloader The IFileDownloader for the ByondInstallerBase.
logger The ILogger for the ByondInstallerBase.
Definition at line 108 of file WindowsByondInstaller.cs.
            : base(ioManager, logger, fileDownloader)
        {
            this.processExecutor = processExecutor ?? throw new ArgumentNullException(nameof(processExecutor));
            generalConfiguration = generalConfigurationOptions?.Value ?? throw new ArgumentNullException(nameof(generalConfigurationOptions));
            sessionConfiguration = sessionConfigurationOptions?.Value ?? throw new ArgumentNullException(nameof(sessionConfigurationOptions));
            var useServiceSpecialTactics = Environment.Is64BitProcess && Environment.UserName == $"{Environment.MachineName}$";
            var documentsDirectory = useServiceSpecialTactics
                ? Environment.ExpandEnvironmentVariables("%SystemRoot%\\SysWOW64\\config\\systemprofile\\Documents")
                : Environment.GetFolderPath(
                    Environment.SpecialFolder.MyDocuments,
                    Environment.SpecialFolderOption.DoNotVerify);
            PathToUserFolder = IOManager.ResolvePath(
                IOManager.ConcatPath(documentsDirectory, "BYOND"));
            semaphore = new SemaphoreSlim(1);
            installedDirectX = false;
        }
References Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.generalConfiguration, Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.installedDirectX, Tgstation.Server.Host.Components.Engine.EngineInstallerBase.IOManager, Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.PathToUserFolder, Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.processExecutor, Tgstation.Server.Host.IO.IIOManager.ResolvePath(), Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.semaphore, and Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.sessionConfiguration.
Member Function Documentation
AddDreamDaemonToFirewall()
async ValueTask Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.AddDreamDaemonToFirewall (EngineVersion version, string path, bool deploymentPipelineProcesses, CancellationToken cancellationToken) private
Attempt to add the DreamDaemon executable as an exception to the Windows firewall.
Parameters
version The BYOND EngineVersion.
path The path to the BYOND installation.
deploymentPipelineProcesses If the operation is part of the deployment pipeline.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Definition at line 316 of file WindowsByondInstaller.cs.
        {
            var dreamDaemonName = GetDreamDaemonName(version.Version!, out var usesDDExe);
            var dreamDaemonPath = IOManager.ResolvePath(
                IOManager.ConcatPath(
                    path,
                    ByondBinPath,
                    dreamDaemonName));
            int exitCode;
            try
            {
                // I really wish we could add the instance name here but
                // 1. It'd make IByondInstaller need to be transient per-instance and WindowsByondInstaller relys on being a singleton for its DX installer call
                // 2. The instance could be renamed, so it'd have to be an unfriendly ID anyway.
                var ruleName = $"TGS DreamDaemon {version}";
                exitCode = await WindowsFirewallHelper.AddFirewallException(
                    processExecutor,
                    Logger,
                    ruleName,
                    dreamDaemonPath,
                    deploymentPipelineProcesses && sessionConfiguration.LowPriorityDeploymentProcesses,
                    cancellationToken);
            }
            catch (Exception ex)
            {
                throw new JobException(ErrorCode.EngineFirewallFail, ex);
            }
            if (exitCode != 0)
                throw new JobException(ErrorCode.EngineFirewallFail, new JobException($"Invalid exit code: {exitCode}"));
            if (usesDDExe)
                await IOManager.WriteAllBytes(
                    IOManager.ConcatPath(path, TgsFirewalledDDFile),
                    Array.Empty<byte>(),
                    cancellationToken);
        }
References Tgstation.Server.Host.System.WindowsFirewallHelper.AddFirewallException(), Tgstation.Server.Host.Components.Engine.ByondInstallerBase.ByondBinPath, Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.GetDreamDaemonName(), Tgstation.Server.Host.Components.Engine.EngineInstallerBase.IOManager, Tgstation.Server.Host.Components.Engine.EngineInstallerBase.Logger, Tgstation.Server.Host.Configuration.SessionConfiguration.LowPriorityDeploymentProcesses, Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.processExecutor, Tgstation.Server.Host.IO.IIOManager.ResolvePath(), Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.sessionConfiguration, Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.TgsFirewalledDDFile, Tgstation.Server.Api.Models.EngineVersion.Version, and Tgstation.Server.Host.IO.IIOManager.WriteAllBytes().
Referenced by Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.Install(), and Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.UpgradeInstallation().
AdditionalCacheCleanFilePaths()
override IEnumerable< string > Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.AdditionalCacheCleanFilePaths (string configDirectory) protected virtual
List off additional file paths in the configDirectory to delete.
Parameters
configDirectory The full path to the relevant CfgDirectoryName.
Returns
An IEnumerable<T> of paths in configDirectory to clean.
Reimplemented from Tgstation.Server.Host.Components.Engine.ByondInstallerBase.
Definition at line 232 of file WindowsByondInstaller.cs.
        {
            // Delete trusted.txt so it doesn't grow too large
            var trustedFilePath =
                IOManager.ConcatPath(
                    configDirectory,
                    TrustedDmbFileName);
            Logger.LogTrace("Deleting trusted .dmbs file {trustedFilePath}", trustedFilePath);
            yield return trustedFilePath;
        }
References Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.Components.Engine.EngineInstallerBase.IOManager, Tgstation.Server.Host.Components.Engine.EngineInstallerBase.Logger, and Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.TrustedDmbFileName.
Dispose()
void Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.Dispose ()
GetDreamDaemonName()
override string Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.GetDreamDaemonName (Version byondVersion, out bool supportsCli) protected virtual
Get the file name of the DreamDaemon executable.
Parameters
byondVersion The Version of BYOND to select the executable name for.
supportsCli Whether or not the returned path supports being run as a command-line application.
Returns
The file name of the DreamDaemon executable.
Implements Tgstation.Server.Host.Components.Engine.ByondInstallerBase.
Definition at line 225 of file WindowsByondInstaller.cs.
        {
            supportsCli = byondVersion >= DDExeVersion;
            return supportsCli ? "dd.exe" : "dreamdaemon.exe";
        }
References Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.DDExeVersion.
Referenced by Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.AddDreamDaemonToFirewall().
Install()
override ValueTask Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.Install (EngineVersion version, string path, bool deploymentPipelineProcesses, CancellationToken cancellationToken) virtual
Does actions necessary to get an extracted installation working.
Parameters
version The EngineVersion being installed.
path The path to the installation.
deploymentPipelineProcesses If the operation should consider processes it launches to be part of the deployment pipeline.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Engine.EngineInstallerBase.
Definition at line 140 of file WindowsByondInstaller.cs.
        {
            CheckVersionValidity(version);
            ArgumentNullException.ThrowIfNull(path);
            var noPromptTrustedTask = SetNoPromptTrusted(path, cancellationToken);
            var installDirectXTask = InstallDirectX(path, cancellationToken);
            var tasks = new List<ValueTask>(3)
            {
                noPromptTrustedTask,
                installDirectXTask,
            };
            if (!generalConfiguration.SkipAddingByondFirewallException)
            {
                var firewallTask = AddDreamDaemonToFirewall(version, path, deploymentPipelineProcesses, cancellationToken);
                tasks.Add(firewallTask);
            }
            return ValueTaskExtensions.WhenAll(tasks);
        }
References Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.AddDreamDaemonToFirewall(), Tgstation.Server.Host.Components.Engine.EngineInstallerBase.CheckVersionValidity(), Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.generalConfiguration, Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.InstallDirectX(), Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.SetNoPromptTrusted(), Tgstation.Server.Host.Configuration.GeneralConfiguration.SkipAddingByondFirewallException, and Tgstation.Server.Common.Extensions.ValueTaskExtensions.WhenAll().
InstallDirectX()
async ValueTask Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.InstallDirectX (string path, CancellationToken cancellationToken) private
Attempt to install the DirectX redistributable included with BYOND.
Parameters
path The path to the BYOND installation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Definition at line 269 of file WindowsByondInstaller.cs.
        {
            using var lockContext = await SemaphoreSlimContext.Lock(semaphore, cancellationToken);
            if (installedDirectX)
            {
                Logger.LogTrace("DirectX already installed.");
                return;
            }
            Logger.LogTrace("Installing DirectX redistributable...");
            // always install it, it's pretty fast and will do better redundancy checking than us
            var rbdx = IOManager.ConcatPath(path, ByondDXDir);
            try
            {
                // noShellExecute because we aren't doing runas shennanigans
                await using var directXInstaller = await processExecutor.LaunchProcess(
                    IOManager.ConcatPath(rbdx, "DXSETUP.exe"),
                    rbdx,
                    "/silent",
                    cancellationToken,
                    noShellExecute: true);
                int exitCode;
                using (cancellationToken.Register(() => directXInstaller.Terminate()))
                    exitCode = (await directXInstaller.Lifetime).Value;
                cancellationToken.ThrowIfCancellationRequested();
                if (exitCode != 0)
                    throw new JobException(ErrorCode.ByondDirectXInstallFail, new JobException($"Invalid exit code: {exitCode}"));
                installedDirectX = true;
            }
            catch (Exception e)
            {
                throw new JobException(ErrorCode.ByondDirectXInstallFail, e);
            }
        }
References Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.ByondDXDir, Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.installedDirectX, Tgstation.Server.Host.Components.Engine.EngineInstallerBase.IOManager, Tgstation.Server.Host.System.IProcessExecutor.LaunchProcess(), Tgstation.Server.Host.Utils.SemaphoreSlimContext.Lock(), Tgstation.Server.Host.Components.Engine.EngineInstallerBase.Logger, Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.processExecutor, and Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.semaphore.
Referenced by Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.Install().
SetNoPromptTrusted()
async ValueTask Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.SetNoPromptTrusted (string path, CancellationToken cancellationToken) private
Creates the BYOND cfg file that prevents the trusted mode dialog from appearing when launching DreamDaemon.
Parameters
path The path to the BYOND installation.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Definition at line 250 of file WindowsByondInstaller.cs.
        {
            var configPath = IOManager.ConcatPath(path, ByondConfigDirectory);
            await IOManager.CreateDirectory(configPath, cancellationToken);
            var configFilePath = IOManager.ConcatPath(configPath, ByondDreamDaemonConfigFilename);
            Logger.LogTrace("Disabling trusted prompts in {configFilePath}...", configFilePath);
            await IOManager.WriteAllBytes(
                configFilePath,
                Encoding.UTF8.GetBytes(ByondNoPromptTrustedMode),
                cancellationToken);
        }
References Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.ByondConfigDirectory, Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.ByondDreamDaemonConfigFilename, Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.ByondNoPromptTrustedMode, Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.IO.IIOManager.CreateDirectory(), Tgstation.Server.Host.Components.Engine.EngineInstallerBase.IOManager, Tgstation.Server.Host.Components.Engine.EngineInstallerBase.Logger, and Tgstation.Server.Host.IO.IIOManager.WriteAllBytes().
Referenced by Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.Install().
TrustDmbPath()
override async ValueTask Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.TrustDmbPath (EngineVersion version, string fullDmbPath, CancellationToken cancellationToken) virtual
Add a given fullDmbPath to the trusted DMBs list in BYOND's config.
Parameters
version The EngineVersion being used.
fullDmbPath Full path to the .dmb that should be trusted.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Engine.EngineInstallerBase.
Definition at line 182 of file WindowsByondInstaller.cs.
        {
            ArgumentNullException.ThrowIfNull(version);
            ArgumentNullException.ThrowIfNull(fullDmbPath);
            var byondDir = PathToUserFolder;
            var cfgDir = IOManager.ConcatPath(
                byondDir,
                CfgDirectoryName);
            var trustedFilePath = IOManager.ConcatPath(
                cfgDir,
                TrustedDmbFileName);
            Logger.LogDebug("Adding .dmb ({dmbPath}) to {trustedFilePath}", fullDmbPath, trustedFilePath);
            using (await SemaphoreSlimContext.Lock(UserFilesSemaphore, cancellationToken))
            {
                string trustedFileText;
                var filePreviouslyExisted = await IOManager.FileExists(trustedFilePath, cancellationToken);
                if (filePreviouslyExisted)
                {
                    var trustedFileBytes = await IOManager.ReadAllBytes(trustedFilePath, cancellationToken);
                    trustedFileText = Encoding.UTF8.GetString(trustedFileBytes);
                    trustedFileText = $"{trustedFileText.Trim()}{Environment.NewLine}";
                }
                else
                    trustedFileText = String.Empty;
                if (trustedFileText.Contains(fullDmbPath, StringComparison.Ordinal))
                    return;
                trustedFileText = $"{trustedFileText}{fullDmbPath}{Environment.NewLine}";
                var newTrustedFileBytes = Encoding.UTF8.GetBytes(trustedFileText);
                if (!filePreviouslyExisted)
                    await IOManager.CreateDirectory(cfgDir, cancellationToken);
                await IOManager.WriteAllBytes(trustedFilePath, newTrustedFileBytes, cancellationToken);
            }
        }
References Tgstation.Server.Host.Components.Engine.ByondInstallerBase.CfgDirectoryName, Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.IO.IIOManager.CreateDirectory(), Tgstation.Server.Host.IO.IIOManager.FileExists(), Tgstation.Server.Host.Components.Engine.EngineInstallerBase.IOManager, Tgstation.Server.Host.Utils.SemaphoreSlimContext.Lock(), Tgstation.Server.Host.Components.Engine.EngineInstallerBase.Logger, Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.PathToUserFolder, Tgstation.Server.Host.IO.IIOManager.ReadAllBytes(), Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.TrustedDmbFileName, Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.UserFilesSemaphore, and Tgstation.Server.Host.IO.IIOManager.WriteAllBytes().
UpgradeInstallation()
override async ValueTask Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.UpgradeInstallation (EngineVersion version, string path, CancellationToken cancellationToken) virtual
Does actions necessary to get upgrade a version installed by a previous version of TGS.
Parameters
version The EngineVersion being installed.
path The path to the installation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Engine.EngineInstallerBase.
Definition at line 163 of file WindowsByondInstaller.cs.
        {
            CheckVersionValidity(version);
            ArgumentNullException.ThrowIfNull(path);
            if (generalConfiguration.SkipAddingByondFirewallException)
                return;
            if (version.Version < DDExeVersion)
                return;
            if (await IOManager.FileExists(IOManager.ConcatPath(path, TgsFirewalledDDFile), cancellationToken))
                return;
            Logger.LogInformation("BYOND Version {version} needs dd.exe added to firewall", version);
            await AddDreamDaemonToFirewall(version, path, true, cancellationToken);
        }
References Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.AddDreamDaemonToFirewall(), Tgstation.Server.Host.Components.Engine.EngineInstallerBase.CheckVersionValidity(), Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.DDExeVersion, Tgstation.Server.Host.IO.IIOManager.FileExists(), Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.generalConfiguration, Tgstation.Server.Host.Components.Engine.EngineInstallerBase.IOManager, Tgstation.Server.Host.Components.Engine.EngineInstallerBase.Logger, Tgstation.Server.Host.Configuration.GeneralConfiguration.SkipAddingByondFirewallException, Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.TgsFirewalledDDFile, and Tgstation.Server.Api.Models.EngineVersion.Version.
Member Data Documentation
ByondConfigDirectory
const string Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.ByondConfigDirectory = "byond/cfg" static private
Directory to byond installation configuration.
Definition at line 28 of file WindowsByondInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.SetNoPromptTrusted().
ByondDreamDaemonConfigFilename
const string Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.ByondDreamDaemonConfigFilename = "daemon.txt" static private
BYOND's DreamDaemon config file.
Definition at line 33 of file WindowsByondInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.SetNoPromptTrusted().
ByondDXDir
const string Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.ByondDXDir = "byond/directx" static private
The directory that contains the BYOND directx redistributable.
Definition at line 43 of file WindowsByondInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.InstallDirectX().
ByondNoPromptTrustedMode
const string Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.ByondNoPromptTrustedMode = "trusted-check 0" static private
Setting to add to ByondDreamDaemonConfigFilename to suppress an invisible user prompt for running a trusted mode .dmb.
Definition at line 38 of file WindowsByondInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.SetNoPromptTrusted().
generalConfiguration
readonly GeneralConfiguration Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.generalConfiguration private
The GeneralConfiguration for the WindowsByondInstaller.
Definition at line 82 of file WindowsByondInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.Install(), Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.UpgradeInstallation(), and Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.WindowsByondInstaller().
installedDirectX
bool Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.installedDirectX private
If DirectX was installed.
Definition at line 97 of file WindowsByondInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.InstallDirectX(), and Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.WindowsByondInstaller().
processExecutor
readonly IProcessExecutor Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.processExecutor private
The IProcessExecutor for the WindowsByondInstaller.
Definition at line 77 of file WindowsByondInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.AddDreamDaemonToFirewall(), Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.InstallDirectX(), and Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.WindowsByondInstaller().
semaphore
readonly SemaphoreSlim Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.semaphore private
The SemaphoreSlim for the WindowsByondInstaller.
Definition at line 92 of file WindowsByondInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.InstallDirectX(), and Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.WindowsByondInstaller().
sessionConfiguration
readonly SessionConfiguration Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.sessionConfiguration private
The SessionConfiguration for the WindowsByondInstaller.
Definition at line 87 of file WindowsByondInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.AddDreamDaemonToFirewall(), and Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.WindowsByondInstaller().
TgsFirewalledDDFile
const string Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.TgsFirewalledDDFile = "TGSFirewalledDD" static private
The file TGS uses to determine if dd.exe has been firewalled.
Definition at line 48 of file WindowsByondInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.AddDreamDaemonToFirewall(), and Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.UpgradeInstallation().
TrustedDmbFileName
const string Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.TrustedDmbFileName = "trusted.txt" static private
The name of the list of trusted .dmb files in the user's BYOND cfg directory.
Definition at line 53 of file WindowsByondInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.AdditionalCacheCleanFilePaths(), and Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.TrustDmbPath().
UserFilesSemaphore
readonly SemaphoreSlim Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.UserFilesSemaphore = new(1, 1) static private
SemaphoreSlim for writing to files in the user's BYOND directory.
Definition at line 58 of file WindowsByondInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.TrustDmbPath().
Property Documentation
ByondRevisionsUrlTemplate
override string Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.ByondRevisionsUrlTemplate get protected
Definition at line 72 of file WindowsByondInstaller.cs.
DDExeVersion
Version Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.DDExeVersion static get
The first version of BYOND to ship with dd.exe on the Windows build.
Definition at line 63 of file WindowsByondInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.GetDreamDaemonName(), and Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.UpgradeInstallation().
DreamMakerName
override string Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.DreamMakerName get protected
Definition at line 66 of file WindowsByondInstaller.cs.
PathToUserFolder
override string Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.PathToUserFolder get protected
Definition at line 69 of file WindowsByondInstaller.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.TrustDmbPath(), and Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.WindowsByondInstaller().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Engine/WindowsByondInstaller.cs