tgstation-server: Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog Class Reference
Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog Class Reference abstract
A IWatchdog that, instead of killing servers for updates, uses the wonders of filesystem links to swap out changes without killing the server process.
Public Member Functions
AdvancedWatchdog (IChatManager chat, ISessionControllerFactory sessionControllerFactory, IDmbFactory dmbFactory, ISessionPersistor sessionPersistor, IJobManager jobManager, IServerControl serverControl, IAsyncDelayer asyncDelayer, IIOManager diagnosticsIOManager, IEventConsumer eventConsumer, IRemoteDeploymentManagerFactory remoteDeploymentManagerFactory, IIOManager gameIOManager, IFilesystemLinkFactory linkFactory, ILogger< AdvancedWatchdog > logger, DreamDaemonLaunchParameters initialLaunchParameters, Api.Models.Instance instance, bool autoStart)
Initializes a new instance of the AdvancedWatchdog class.
Public Member Functions inherited from Tgstation.Server.Host.Components.Watchdog.BasicWatchdog
BasicWatchdog (IChatManager chat, ISessionControllerFactory sessionControllerFactory, IDmbFactory dmbFactory, ISessionPersistor sessionPersistor, IJobManager jobManager, IServerControl serverControl, IAsyncDelayer asyncDelayer, IIOManager diagnosticsIOManager, IEventConsumer eventConsumer, IRemoteDeploymentManagerFactory remoteDeploymentManagerFactory, IIOManager gameIOManager, ILogger< BasicWatchdog > logger, DreamDaemonLaunchParameters initialLaunchParameters, Api.Models.Instance instance, bool autoStart)
Initializes a new instance of the BasicWatchdog class.
override ValueTask ResetRebootState (CancellationToken cancellationToken)
Cancels pending graceful actions.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
sealed override ValueTask InstanceRenamed (string newInstanceName, CancellationToken cancellationToken)
Called when the owning Instance is renamed.
Parameters
newInstanceName The new Api.Models.NamedEntity.Name.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Public Member Functions inherited from Tgstation.Server.Host.Components.Watchdog.WatchdogBase
async ValueTask DisposeAsync ()
async ValueTask< bool > ChangeSettings (DreamDaemonLaunchParameters launchParameters, CancellationToken cancellationToken)
Changes the ActiveLaunchParameters. If currently running, may trigger a graceful restart.
Parameters
launchParameters The new DreamDaemonLaunchParameters. May be modified.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in true if a reboot is required, false otherwise.
async ValueTask< MessageContent > HandleChatCommand (string commandName, string arguments, ChatUser sender, CancellationToken cancellationToken)
Handle a chat command.
Parameters
commandName The command name.
arguments Everything typed after commandName minus leading spaces.
sender The sending ChatUser.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the MessageContent text to send back.
async ValueTask Launch (CancellationToken cancellationToken)
Start the IWatchdog.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
virtual async ValueTask ResetRebootState (CancellationToken cancellationToken)
Cancels pending graceful actions.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
async ValueTask Restart (bool graceful, CancellationToken cancellationToken)
Restarts the watchdog.
Parameters
graceful If true the restart will be delayed until a reboot is detected in the active server's DMAPI and this function will retrun immediately.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
async Task StartAsync (CancellationToken cancellationToken)
async Task StopAsync (CancellationToken cancellationToken)
async ValueTask Terminate (bool graceful, CancellationToken cancellationToken)
Stops the watchdog.
Parameters
graceful If true the termination will be delayed until a reboot is detected in the active server's DMAPI and this function will return immediately.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
async ValueTask HandleRestart (Version? updateVersion, bool handlerMayDelayShutdownWithExtremelyLongRunningTasks, CancellationToken cancellationToken)
Handle a restart of the server.
Parameters
updateVersion The Version being updated to, null if not being changed.
handlerMayDelayShutdownWithExtremelyLongRunningTasks If false the IRestartHandler should aim to complete the Task returned from this function ASAP.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
abstract ValueTask InstanceRenamed (string newInstanceName, CancellationToken cancellationToken)
Called when the owning Instance is renamed.
Parameters
newInstanceName The new Api.Models.NamedEntity.Name.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
async ValueTask CreateDump (CancellationToken cancellationToken)
Attempt to create a process dump for DreamDaemon.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
async ValueTask< bool > Broadcast (string message, CancellationToken cancellationToken)
Send a broadcast message to the DMAPI.
Parameters
message The message to broadcast.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in true if the broadcast succeeded., false otherwise.
ValueTask Launch (CancellationToken cancellationToken)
Start the IWatchdog.
ValueTask< bool > ChangeSettings (DreamDaemonLaunchParameters launchParameters, CancellationToken cancellationToken)
Changes the ActiveLaunchParameters. If currently running, may trigger a graceful restart.
ValueTask Restart (bool graceful, CancellationToken cancellationToken)
Restarts the watchdog.
ValueTask Terminate (bool graceful, CancellationToken cancellationToken)
Stops the watchdog.
ValueTask ResetRebootState (CancellationToken cancellationToken)
Cancels pending graceful actions.
ValueTask CreateDump (CancellationToken cancellationToken)
Attempt to create a process dump for DreamDaemon.
ValueTask< bool > Broadcast (string message, CancellationToken cancellationToken)
Send a broadcast message to the DMAPI.
ValueTask HandleEvent (EventType eventType, IEnumerable< string?> parameters, bool deploymentPipeline, CancellationToken cancellationToken)
Handle a given eventType .
ValueTask? HandleCustomEvent (string eventName, IEnumerable< string?> parameters, CancellationToken cancellationToken)
Handles a given custom event.
ValueTask InstanceRenamed (string newInstanceName, CancellationToken cancellationToken)
Called when the owning Instance is renamed.
ValueTask< MessageContent > HandleChatCommand (string commandName, string arguments, ChatUser sender, CancellationToken cancellationToken)
Handle a chat command.
ValueTask HandleRestart (Version? updateVersion, bool handlerMayDelayShutdownWithExtremelyLongRunningTasks, CancellationToken cancellationToken)
Handle a restart of the server.
Protected Member Functions
sealed override async ValueTask DisposeAndNullControllersImpl ()
Call IDisposable.Dispose and null the fields for all ISessionControllers.
Returns
A ValueTask representing the running operation.
sealed override async ValueTask< MonitorAction > HandleNormalReboot (CancellationToken cancellationToken)
Handler for MonitorActivationReason.ActiveServerRebooted when the RebootState is RebootState.Normal.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the MonitorAction to take.
sealed override async ValueTask HandleNewDmbAvailable (CancellationToken cancellationToken)
Handler for MonitorActivationReason.NewDmbAvailable.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
sealed override async ValueTask< IDmbProvider > PrepServerForLaunch (IDmbProvider dmbToUse, CancellationToken cancellationToken)
Prepare the server to launch a new instance with the WatchdogBase.ActiveLaunchParameters and a given dmbToUse .
Parameters
dmbToUse The IDmbProvider to be launched. Will not be disposed by this function.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the modified IDmbProvider to be used.
abstract ValueTask ApplyInitialDmb (CancellationToken cancellationToken)
Set the ReattachInformation.InitialDmb for the BasicWatchdog.Server.
abstract SwappableDmbProvider CreateSwappableDmbProvider (IDmbProvider dmbProvider)
Create a SwappableDmbProvider for a given dmbProvider .
override async ValueTask SessionStartupPersist (CancellationToken cancellationToken)
Called to save the current Server into the WatchdogBase.SessionPersistor when initially launched.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
override async ValueTask< MonitorAction > HandleMonitorWakeup (MonitorActivationReason reason, CancellationToken cancellationToken)
Handles the actions to take when the monitor has to "wake up".
Parameters
activationReason The MonitorActivationReason that caused the invocation. Will never be MonitorActivationReason.HealthCheck.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the MonitorAction to take.
Protected Member Functions inherited from Tgstation.Server.Host.Components.Watchdog.BasicWatchdog
override async ValueTask< MonitorAction > HandleMonitorWakeup (MonitorActivationReason reason, CancellationToken cancellationToken)
Handles the actions to take when the monitor has to "wake up".
Parameters
activationReason The MonitorActivationReason that caused the invocation. Will never be MonitorActivationReason.HealthCheck.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the MonitorAction to take.
override async ValueTask DisposeAndNullControllersImpl ()
Call IDisposable.Dispose and null the fields for all ISessionControllers.
Returns
A ValueTask representing the running operation.
sealed override? ISessionController GetActiveController ()
Get the active ISessionController.
Returns
The active ISessionController, if any.
override async ValueTask InitController (ValueTask eventTask, ReattachInformation? reattachInfo, CancellationToken cancellationToken)
Starts all ISessionControllers.
Parameters
eventTask A, possibly active, Task for an event that's running.
reattachInfo ReattachInformation to use, if any.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
virtual ValueTask SessionStartupPersist (CancellationToken cancellationToken)
Called to save the current Server into the WatchdogBase.SessionPersistor when initially launched.
virtual ValueTask< MonitorAction > HandleNormalReboot (CancellationToken cancellationToken)
Handler for MonitorActivationReason.ActiveServerRebooted when the RebootState is RebootState.Normal.
virtual async ValueTask HandleNewDmbAvailable (CancellationToken cancellationToken)
Handler for MonitorActivationReason.NewDmbAvailable.
virtual ValueTask< IDmbProvider > PrepServerForLaunch (IDmbProvider dmbToUse, CancellationToken cancellationToken)
Prepare the server to launch a new instance with the WatchdogBase.ActiveLaunchParameters and a given dmbToUse .
Protected Member Functions inherited from Tgstation.Server.Host.Components.Watchdog.WatchdogBase
WatchdogBase (IChatManager chat, ISessionControllerFactory sessionControllerFactory, IDmbFactory dmbFactory, ISessionPersistor sessionPersistor, IJobManager jobManager, IServerControl serverControl, IAsyncDelayer asyncDelayer, IIOManager diagnosticsIOManager, IEventConsumer eventConsumer, IRemoteDeploymentManagerFactory remoteDeploymentManagerFactory, IIOManager gameIOManager, ILogger< WatchdogBase > logger, DreamDaemonLaunchParameters initialLaunchParameters, Api.Models.Instance metadata, bool autoStart)
Initializes a new instance of the WatchdogBase class.
abstract ValueTask InitController (ValueTask eventTask, ReattachInformation? reattachInfo, CancellationToken cancellationToken)
Starts all ISessionControllers.
async ValueTask LaunchNoLock (bool startMonitor, bool announce, bool announceFailure, ReattachInformation? reattachInfo, CancellationToken cancellationToken)
Launches the watchdog.
async ValueTask< bool > StopMonitor ()
Stops MonitorLifetimes(CancellationToken). Doesn't kill the servers.
async ValueTask CheckLaunchResult (ISessionController controller, string serverName, CancellationToken cancellationToken)
Check the LaunchResult of a given controller for errors and throw a JobException if any are detected.
async ValueTask ReattachFailure (CancellationToken cancellationToken)
Call from InitController(ValueTask, ReattachInformation, CancellationToken) when a reattach operation fails to attempt a fresh start.
abstract ValueTask DisposeAndNullControllersImpl ()
Call IDisposable.Dispose and null the fields for all ISessionControllers.
async ValueTask DisposeAndNullControllers (CancellationToken cancellationToken)
Wrapper for DisposeAndNullControllersImpl under a locked context.
abstract ? ISessionController GetActiveController ()
Get the active ISessionController.
abstract ValueTask< MonitorAction > HandleMonitorWakeup (MonitorActivationReason activationReason, CancellationToken cancellationToken)
Handles the actions to take when the monitor has to "wake up".
async ValueTask BeforeApplyDmb (Models.CompileJob newCompileJob, CancellationToken cancellationToken)
To be called before a given newCompileJob goes live.
async ValueTask HandleEventImpl (EventType eventType, IEnumerable< string > parameters, bool relayToSession, CancellationToken cancellationToken)
Handle a given eventType without re-throwing errors.
Properties
SwappableDmbProvider? ActiveSwappable [get, private set]
The SwappableDmbProvider for WatchdogBase.LastLaunchParameters.
IFilesystemLinkFactory LinkFactory [get]
The IFilesystemLinkFactory for the AdvancedWatchdog.
Properties inherited from Tgstation.Server.Host.Components.Watchdog.BasicWatchdog
sealed override bool AlphaIsActive [get]
If the alpha server is the active server.
sealed override? RebootState RebootState [get]
The Session.RebootState of the active server.
ISessionController? Server [get, private set]
The single ISessionController.
Properties inherited from Tgstation.Server.Host.Components.Watchdog.WatchdogBase
long? SessionId [get]
An incrementing ID for representing current server execution.
WatchdogStatus Status [get, protected set]
The current WatchdogStatus.
long? MemoryUsage [get]
Gets the memory usage of the game server in bytes.
abstract bool AlphaIsActive [get]
If the alpha server is the active server.
DreamDaemonLaunchParameters ActiveLaunchParameters [get, protected set]
The DreamDaemonLaunchParameters to be applied.
DreamDaemonLaunchParameters? LastLaunchParameters [get, protected set]
The DreamDaemonLaunchParameters the active server is using. This may not be the exact same as ActiveLaunchParameters but still be associated with the same session.
Models.? CompileJob ActiveCompileJob [get]
Retrieves the Models.CompileJob currently running on the server.
abstract ? RebootState RebootState [get]
The Session.RebootState of the active server.
ISessionPersistor SessionPersistor [get]
The ISessionPersistor for the WatchdogBase.
ILogger< WatchdogBase > Logger [get]
The ILogger for the WatchdogBase.
IChatManager Chat [get]
The IChatManager for the WatchdogBase.
ISessionControllerFactory SessionControllerFactory [get]
The ISessionControllerFactory for the WatchdogBase.
IDmbFactory DmbFactory [get]
The IDmbFactory for the WatchdogBase.
IAsyncDelayer AsyncDelayer [get]
The IAsyncDelayer for the WatchdogBase.
IIOManager GameIOManager [get]
The IIOManager for the WatchdogBase pointing to the Game directory.
Properties inherited from Tgstation.Server.Host.Components.Watchdog.IWatchdog
long? SessionId [get]
An incrementing ID for representing current server execution.
WatchdogStatus Status [get]
The current WatchdogStatus.
long? MemoryUsage [get]
Gets the memory usage of the game server in bytes.
bool AlphaIsActive [get]
If the alpha server is the active server.
Models.? CompileJob ActiveCompileJob [get]
Retrieves the Models.CompileJob currently running on the server.
DreamDaemonLaunchParameters ActiveLaunchParameters [get]
The DreamDaemonLaunchParameters to be applied.
DreamDaemonLaunchParameters? LastLaunchParameters [get]
The DreamDaemonLaunchParameters the active server is using.
RebootState? RebootState [get]
The Session.RebootState of the active server.
Private Member Functions
bool CanUseSwappableDmbProvider (IDmbProvider dmbProvider)
If the SwappableDmbProvider feature of the AdvancedWatchdog can be used with a given dmbProvider .
async ValueTask InitialLink (CancellationToken cancellationToken)
Create the initial link to the live game directory using ActiveSwappable.
async ValueTask PerformDmbSwap (SwappableDmbProvider newProvider, CancellationToken cancellationToken)
Suspends the BasicWatchdog.Server and calls SwappableDmbProvider.MakeActive(CancellationToken) on a newProvider .
Task DrainDeploymentCleanupTasks (bool blocking)
Asynchronously drain deploymentCleanupTasks.
Private Attributes
readonly List< Task > deploymentCleanupTasks
List<T> of Tasks that are waiting to clean up old deployments.
SwappableDmbProvider? pendingSwappable
The active SwappableDmbProvider for WatchdogBase.ActiveLaunchParameters.
volatile? TaskCompletionSource deploymentCleanupGate
The TaskCompletionSource representing the cleanup of an unused IDmbProvider.
Detailed Description
A IWatchdog that, instead of killing servers for updates, uses the wonders of filesystem links to swap out changes without killing the server process.
Definition at line 26 of file AdvancedWatchdog.cs.
Constructor & Destructor Documentation
AdvancedWatchdog()
Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.AdvancedWatchdog (IChatManager chat, ISessionControllerFactory sessionControllerFactory, IDmbFactory dmbFactory, ISessionPersistor sessionPersistor, IJobManager jobManager, IServerControl serverControl, IAsyncDelayer asyncDelayer, IIOManager diagnosticsIOManager, IEventConsumer eventConsumer, IRemoteDeploymentManagerFactory remoteDeploymentManagerFactory, IIOManager gameIOManager, IFilesystemLinkFactory linkFactory, ILogger< AdvancedWatchdog > logger, DreamDaemonLaunchParameters initialLaunchParameters, Api.Models.Instance instance, bool autoStart)
Initializes a new instance of the AdvancedWatchdog class.
Parameters
chat The IChatManager for the WatchdogBase.
sessionControllerFactory The ISessionControllerFactory for the WatchdogBase.
dmbFactory The IDmbFactory for the WatchdogBase.
sessionPersistor The ISessionPersistor for the WatchdogBase.
jobManager The IJobManager for the WatchdogBase.
serverControl The IServerControl for the WatchdogBase.
asyncDelayer The IAsyncDelayer for the WatchdogBase.
diagnosticsIOManager The 'Diagnostics' IIOManager for the WatchdogBase.
eventConsumer The IEventConsumer for the WatchdogBase.
remoteDeploymentManagerFactory The IRemoteDeploymentManagerFactory for the WatchdogBase.
gameIOManager The 'Game' IIOManager for the WatchdogBase.
linkFactory The value of LinkFactory.
logger The ILogger for the WatchdogBase.
initialLaunchParameters The DreamDaemonLaunchParameters for the WatchdogBase.
instance The Api.Models.Instance for the WatchdogBase.
autoStart The autostart value for the WatchdogBase.
Definition at line 72 of file AdvancedWatchdog.cs.
            : base(
                chat,
                sessionControllerFactory,
                dmbFactory,
                sessionPersistor,
                jobManager,
                serverControl,
                asyncDelayer,
                diagnosticsIOManager,
                eventConsumer,
                remoteDeploymentManagerFactory,
                gameIOManager,
                logger,
                initialLaunchParameters,
                instance,
                autoStart)
        {
            try
            {
                LinkFactory = linkFactory ?? throw new ArgumentNullException(nameof(linkFactory));
                deploymentCleanupTasks = new List<Task>();
            }
            catch
            {
                // Async dispose is for if we have controllers running, not the case here
                var disposeTask = DisposeAsync();
                Debug.Assert(disposeTask.IsCompleted, "This should always be true during construction!");
                disposeTask.GetAwaiter().GetResult();
                throw;
            }
        }
References Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.deploymentCleanupTasks, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.DisposeAsync(), and Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.LinkFactory.
Member Function Documentation
ApplyInitialDmb()
abstract ValueTask Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.ApplyInitialDmb (CancellationToken cancellationToken) protected pure virtual
Set the ReattachInformation.InitialDmb for the BasicWatchdog.Server.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implemented in Tgstation.Server.Host.Components.Watchdog.PosixWatchdog, and Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.
Referenced by Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.SessionStartupPersist().
CanUseSwappableDmbProvider()
bool Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.CanUseSwappableDmbProvider (IDmbProvider dmbProvider) private
If the SwappableDmbProvider feature of the AdvancedWatchdog can be used with a given dmbProvider .
Parameters
dmbProvider The IDmbProvider that is to be activated.
Returns
true if swapping is possible, false otherwise.
Definition at line 352 of file AdvancedWatchdog.cs.
        {
            if (dmbProvider.EngineVersion.Engine != EngineType.Byond)
            {
                Logger.LogDebug("Not using SwappableDmbProvider for engine type {engineType}", dmbProvider.EngineVersion.Engine);
                return false;
            }
            return true;
        }
References Tgstation.Server.Api.Models.EngineVersion.Engine, Tgstation.Server.Host.Components.Deployment.IDmbProvider.EngineVersion, and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Logger.
Referenced by Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.HandleNewDmbAvailable(), and Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.PrepServerForLaunch().
CreateSwappableDmbProvider()
abstract SwappableDmbProvider Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.CreateSwappableDmbProvider (IDmbProvider dmbProvider) protected pure virtual
Create a SwappableDmbProvider for a given dmbProvider .
Parameters
dmbProvider The IDmbProvider to create a SwappableDmbProvider for.
Returns
A new SwappableDmbProvider.
Implemented in Tgstation.Server.Host.Components.Watchdog.PosixWatchdog, and Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.
Referenced by Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.HandleNewDmbAvailable(), and Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.PrepServerForLaunch().
DisposeAndNullControllersImpl()
sealed override async ValueTask Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.DisposeAndNullControllersImpl () protected virtual
Call IDisposable.Dispose and null the fields for all ISessionControllers.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Watchdog.WatchdogBase.
Definition at line 124 of file AdvancedWatchdog.cs.
        {
            await base.DisposeAndNullControllersImpl();
            // If we reach this point, we can guarantee PrepServerForLaunch will be called before starting again.
            ActiveSwappable = null;
            if (pendingSwappable != null)
            {
                await pendingSwappable.DisposeAsync();
                pendingSwappable = null;
            }
            await DrainDeploymentCleanupTasks(true);
        }
References Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.ActiveSwappable, Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.DisposeAsync(), Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.DrainDeploymentCleanupTasks(), and Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.pendingSwappable.
DrainDeploymentCleanupTasks()
Task Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.DrainDeploymentCleanupTasks (bool blocking) private
Asynchronously drain deploymentCleanupTasks.
Parameters
blocking If true, all Tasks will be awaited. Otherwise, only Tasks with Task.IsCompleted set will be awaited.
Returns
A Task representing the running operation.
Definition at line 417 of file AdvancedWatchdog.cs.
        {
            Logger.LogTrace("DrainDeploymentCleanupTasks...");
            var localDeploymentCleanupGate = Interlocked.Exchange(ref deploymentCleanupGate, null);
            localDeploymentCleanupGate?.TrySetResult();
            List<Task> localDeploymentCleanupTasks;
            lock (deploymentCleanupTasks)
            {
                var totalActiveTasks = deploymentCleanupTasks.Count;
                localDeploymentCleanupTasks = new List<Task>(totalActiveTasks);
                for (var i = totalActiveTasks - 1; i >= 0; --i)
                {
                    var currentTask = deploymentCleanupTasks[i];
                    if (!blocking && !currentTask.IsCompleted)
                        continue;
                    localDeploymentCleanupTasks.Add(currentTask);
                    deploymentCleanupTasks.RemoveAt(i);
                }
            }
            return Task.WhenAll(localDeploymentCleanupTasks);
        }
References Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.deploymentCleanupGate, Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.deploymentCleanupTasks, and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Logger.
Referenced by Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.DisposeAndNullControllersImpl(), Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.HandleMonitorWakeup(), and Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.HandleNormalReboot().
HandleMonitorWakeup()
override async ValueTask< MonitorAction > Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.HandleMonitorWakeup (MonitorActivationReason reason, CancellationToken cancellationToken) protected virtual
Handles the actions to take when the monitor has to "wake up".
Parameters
activationReason The MonitorActivationReason that caused the invocation. Will never be MonitorActivationReason.HealthCheck.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the MonitorAction to take.
Implements Tgstation.Server.Host.Components.Watchdog.WatchdogBase.
Definition at line 338 of file AdvancedWatchdog.cs.
        {
            var result = await base.HandleMonitorWakeup(reason, cancellationToken);
            if (reason == MonitorActivationReason.ActiveServerStartup)
                await DrainDeploymentCleanupTasks(false);
            return result;
        }
References Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.DrainDeploymentCleanupTasks().
HandleNewDmbAvailable()
sealed override async ValueTask Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.HandleNewDmbAvailable (CancellationToken cancellationToken) protected virtual
Handler for MonitorActivationReason.NewDmbAvailable.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Reimplemented from Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.
Definition at line 233 of file AdvancedWatchdog.cs.
        {
            IDmbProvider compileJobProvider = DmbFactory.LockNextDmb("AdvancedWatchdog next compile job preload");
            bool canSeamlesslySwap = CanUseSwappableDmbProvider(compileJobProvider);
            if (canSeamlesslySwap)
                if (compileJobProvider.CompileJob.EngineVersion != ActiveCompileJob!.EngineVersion)
                {
                    // have to do a graceful restart
                    Logger.LogDebug(
                        "Not swapping to new compile job {compileJobId} as it uses a different engine version ({newEngineVersion}) than what is currently active {oldEngineVersion}.",
                        compileJobProvider.CompileJob.Id,
                        compileJobProvider.CompileJob.EngineVersion,
                        ActiveCompileJob.EngineVersion);
                    canSeamlesslySwap = false;
                }
                else if (compileJobProvider.CompileJob.DmeName != ActiveCompileJob.DmeName)
                {
                    Logger.LogDebug(
                        "Not swapping to new compile job {compileJobId} as it uses a different .dmb name ({newDmbName}) than what is currently active {oldDmbName}.",
                        compileJobProvider.CompileJob.Id,
                        compileJobProvider.CompileJob.DmeName,
                        ActiveCompileJob.DmeName);
                    canSeamlesslySwap = false;
                }
            if (!canSeamlesslySwap)
            {
                Logger.LogDebug("Queueing graceful restart instead...");
                await compileJobProvider.DisposeAsync();
                await base.HandleNewDmbAvailable(cancellationToken);
                return;
            }
            SwappableDmbProvider? swappableProvider = null;
            try
            {
                swappableProvider = CreateSwappableDmbProvider(compileJobProvider);
                if (ActiveCompileJob!.DMApiVersion == null)
                {
                    Logger.LogWarning("Active compile job has no DMAPI! Commencing immediate .dmb swap. Note this behavior is known to be buggy in some DM code contexts. See https://github.com/tgstation/tgstation-server/issues/1550");
                    await PerformDmbSwap(swappableProvider, cancellationToken);
                }
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, "Exception while swapping");
                IDmbProvider providerToDispose = swappableProvider ?? compileJobProvider;
                await providerToDispose.DisposeAsync();
                throw;
            }
            await (pendingSwappable?.DisposeAsync() ?? ValueTask.CompletedTask);
            pendingSwappable = swappableProvider;
        }
References Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ActiveCompileJob, Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.CanUseSwappableDmbProvider(), Tgstation.Server.Host.Components.Deployment.IDmbProvider.CompileJob, Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.CreateSwappableDmbProvider(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.DisposeAsync(), Tgstation.Server.Api.Models.Internal.CompileJob.DmeName, Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Host.Components.Deployment.DmbFactory.LockNextDmb(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Logger, Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.pendingSwappable, and Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.PerformDmbSwap().
HandleNormalReboot()
sealed override async ValueTask< MonitorAction > Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.HandleNormalReboot (CancellationToken cancellationToken) protected virtual
Handler for MonitorActivationReason.ActiveServerRebooted when the RebootState is RebootState.Normal.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the MonitorAction to take.
Reimplemented from Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.
Definition at line 141 of file AdvancedWatchdog.cs.
        {
            if (pendingSwappable != null)
            {
                var needToSwap = !pendingSwappable.Swapped;
                var controller = Server!;
                if (needToSwap)
                {
                    // IMPORTANT: THE SESSIONCONTROLLER SHOULD STILL BE PROCESSING THE BRIDGE REQUEST SO WE KNOW DD IS SLEEPING
                    // OTHERWISE, IT COULD RETURN TO /world/Reboot() TOO EARLY AND LOAD THE WRONG .DMB
                    if (!controller.ProcessingRebootBridgeRequest)
                    {
                        // integration test logging will catch this
                        Logger.LogError(
                            "The reboot bridge request completed before the watchdog could suspend the server! This can lead to buggy DreamDaemon behaviour and should be reported! To ensure stability, we will need to hard reboot the server");
                        return MonitorAction.Restart;
                    }
                    // DCT: Not necessary
                    if (!pendingSwappable.FinishActivationPreparation(CancellationToken.None).IsCompleted)
                    {
                        // rare pokemon
                        Logger.LogInformation("Deployed .dme is not ready to swap, delaying until next reboot!");
                        Chat.QueueWatchdogMessage("The pending deployment was not ready to be activated this reboot. It will be applied at the next one.");
                        return MonitorAction.Continue;
                    }
                }
                var updateTask = BeforeApplyDmb(pendingSwappable.CompileJob, cancellationToken);
                if (needToSwap)
                    await PerformDmbSwap(pendingSwappable, cancellationToken);
                var currentCompileJobId = controller.ReattachInformation.Dmb.CompileJob.Id;
                await DrainDeploymentCleanupTasks(false);
                IAsyncDisposable lingeringDeployment;
                var localDeploymentCleanupGate = new TaskCompletionSource();
                async Task CleanupLingeringDeployment()
                {
                    var lingeringDeploymentExpirySeconds = ActiveLaunchParameters.StartupTimeout!.Value;
                    Logger.LogDebug(
                        "Holding old deployment {compileJobId} for up to {expiry} seconds...",
                        currentCompileJobId,
                        lingeringDeploymentExpirySeconds);
                    // DCT: A cancel firing here can result in us leaving a dmbprovider undisposed, localDeploymentCleanupGate will always fire in that case
                    var timeout = AsyncDelayer.Delay(TimeSpan.FromSeconds(lingeringDeploymentExpirySeconds), CancellationToken.None);
                    var completedTask = await Task.WhenAny(
                        localDeploymentCleanupGate.Task,
                        timeout);
                    var timedOut = completedTask == timeout;
                    Logger.Log(
                        timedOut
                            ? LogLevel.Warning
                            : LogLevel.Trace,
                        "Releasing old deployment {compileJobId}{afterTimeout}",
                        currentCompileJobId,
                        timedOut
                            ? " due to timeout!"
                            : "...");
                    await lingeringDeployment.DisposeAsync();
                }
                var oldDeploymentCleanupGate = Interlocked.Exchange(ref deploymentCleanupGate, localDeploymentCleanupGate);
                oldDeploymentCleanupGate?.TrySetResult();
                Logger.LogTrace("Replacing activeSwappable with pendingSwappable...");
                lock (deploymentCleanupTasks)
                {
                    lingeringDeployment = controller.ReplaceDmbProvider(pendingSwappable);
                    deploymentCleanupTasks.Add(
                        CleanupLingeringDeployment());
                }
                ActiveSwappable = pendingSwappable;
                pendingSwappable = null;
                await SessionPersistor.Update(controller.ReattachInformation, cancellationToken);
                await updateTask;
            }
            else
                Logger.LogTrace("Nothing to do as pendingSwappable is null.");
            return await base.HandleNormalReboot(cancellationToken);
        }
References Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ActiveLaunchParameters, Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.ActiveSwappable, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.BeforeApplyDmb(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Chat, Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.CompileJob, Tgstation.Server.Host.Utils.AsyncDelayer.Delay(), Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.deploymentCleanupGate, Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.deploymentCleanupTasks, Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.DrainDeploymentCleanupTasks(), Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.FinishActivationPreparation(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Logger, Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.pendingSwappable, Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.PerformDmbSwap(), Tgstation.Server.Host.Components.Chat.IChatManager.QueueWatchdogMessage(), Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.StartupTimeout, Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.Swapped, and Tgstation.Server.Host.Components.Session.SessionPersistor.Update().
InitialLink()
async ValueTask Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.InitialLink (CancellationToken cancellationToken) private
Create the initial link to the live game directory using ActiveSwappable.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Definition at line 368 of file AdvancedWatchdog.cs.
        {
            await ActiveSwappable!.FinishActivationPreparation(cancellationToken);
            Logger.LogTrace("Linking compile job...");
            await ActiveSwappable.MakeActive(cancellationToken);
        }
References Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.ActiveSwappable, Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.FinishActivationPreparation(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Logger, and Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.MakeActive().
Referenced by Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.PrepServerForLaunch().
PerformDmbSwap()
async ValueTask Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.PerformDmbSwap (SwappableDmbProvider newProvider, CancellationToken cancellationToken) private
Suspends the BasicWatchdog.Server and calls SwappableDmbProvider.MakeActive(CancellationToken) on a newProvider .
Parameters
newProvider The SwappableDmbProvider to activate.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Definition at line 381 of file AdvancedWatchdog.cs.
        {
            Logger.LogDebug("Swapping to compile job {id}...", newProvider.CompileJob.Id);
            await newProvider.FinishActivationPreparation(cancellationToken);
            var suspended = false;
            var server = Server!;
            try
            {
                server.SuspendProcess();
                suspended = true;
            }
            catch (Exception ex)
            {
                Logger.LogWarning(ex, "Exception while suspending server!");
            }
            try
            {
                Logger.LogTrace("Making new provider {id} active...", newProvider.CompileJob.Id);
                await newProvider.MakeActive(cancellationToken);
            }
            finally
            {
                // Let this throw hard if it fails
                if (suspended)
                    server.ResumeProcess();
            }
        }
References Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.CompileJob, Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.FinishActivationPreparation(), Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Logger, and Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.MakeActive().
Referenced by Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.HandleNewDmbAvailable(), and Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.HandleNormalReboot().
PrepServerForLaunch()
sealed override async ValueTask< IDmbProvider > Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.PrepServerForLaunch (IDmbProvider dmbToUse, CancellationToken cancellationToken) protected virtual
Prepare the server to launch a new instance with the WatchdogBase.ActiveLaunchParameters and a given dmbToUse .
Parameters
dmbToUse The IDmbProvider to be launched. Will not be disposed by this function.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the modified IDmbProvider to be used.
Reimplemented from Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.
Definition at line 289 of file AdvancedWatchdog.cs.
        {
            if (ActiveSwappable != null)
                throw new InvalidOperationException("Expected activeSwappable to be null!");
            if (pendingSwappable != null)
                throw new InvalidOperationException("Expected pendingSwappable to be null!");
            Logger.LogTrace("Prep for server launch");
            if (!CanUseSwappableDmbProvider(dmbToUse))
                return dmbToUse;
            ActiveSwappable = CreateSwappableDmbProvider(dmbToUse);
            try
            {
                await InitialLink(cancellationToken);
            }
            catch (Exception ex)
            {
                // We won't worry about disposing activeSwappable here as we can't dispose dmbToUse here.
                Logger.LogTrace(ex, "Initial link error, nulling ActiveSwappable");
                ActiveSwappable = null;
                throw;
            }
            return ActiveSwappable;
        }
References Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.ActiveSwappable, Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.CanUseSwappableDmbProvider(), Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.CreateSwappableDmbProvider(), Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.InitialLink(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Logger, and Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.pendingSwappable.
SessionStartupPersist()
override async ValueTask Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.SessionStartupPersist (CancellationToken cancellationToken) protected virtual
Called to save the current Server into the WatchdogBase.SessionPersistor when initially launched.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Reimplemented from Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.
Definition at line 331 of file AdvancedWatchdog.cs.
        {
            await ApplyInitialDmb(cancellationToken);
            await base.SessionStartupPersist(cancellationToken);
        }
References Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.ApplyInitialDmb().
Member Data Documentation
deploymentCleanupGate
volatile? TaskCompletionSource Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.deploymentCleanupGate private
The TaskCompletionSource representing the cleanup of an unused IDmbProvider.
Definition at line 51 of file AdvancedWatchdog.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.DrainDeploymentCleanupTasks(), and Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.HandleNormalReboot().
deploymentCleanupTasks
readonly List<Task> Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.deploymentCleanupTasks private
List<T> of Tasks that are waiting to clean up old deployments.
Definition at line 41 of file AdvancedWatchdog.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.AdvancedWatchdog(), Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.DrainDeploymentCleanupTasks(), and Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.HandleNormalReboot().
pendingSwappable
SwappableDmbProvider? Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.pendingSwappable private
The active SwappableDmbProvider for WatchdogBase.ActiveLaunchParameters.
Definition at line 46 of file AdvancedWatchdog.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.DisposeAndNullControllersImpl(), Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.HandleNewDmbAvailable(), Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.HandleNormalReboot(), and Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.PrepServerForLaunch().
Property Documentation
ActiveSwappable
SwappableDmbProvider? Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.ActiveSwappable get private set protected
The SwappableDmbProvider for WatchdogBase.LastLaunchParameters.
Definition at line 31 of file AdvancedWatchdog.cs.
{ get; private set; }
Referenced by Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.DisposeAndNullControllersImpl(), Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.HandleNormalReboot(), Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.InitialLink(), and Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.PrepServerForLaunch().
LinkFactory
IFilesystemLinkFactory Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.LinkFactory get protected
The IFilesystemLinkFactory for the AdvancedWatchdog.
Definition at line 36 of file AdvancedWatchdog.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.AdvancedWatchdog().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Watchdog/AdvancedWatchdog.cs