tgstation-server: Tgstation.Server.Host.Controllers.ApiController Class Reference
Tgstation.Server.Host.Controllers.ApiController Class Reference
Base Controller for API functions.
Public Member Functions
override async Task OnActionExecutionAsync (ActionExecutingContext context, ActionExecutionDelegate next)
Protected Member Functions
ApiController (IDatabaseContext databaseContext, IAuthenticationContextFactory authenticationContextFactory, ILogger< ApiController > logger, bool requireHeaders)
Initializes a new instance of the ApiController class.
ObjectResult Gone ()
Generic 410 response.
new NotFoundObjectResult NotFound ()
Generic 404 response.
ObjectResult RequiresPosixSystemIdentity (NotImplementedException ex)
Generic 501 response.
StatusCodeResult StatusCode (HttpStatusCode statusCode)
Strongly type calls to ControllerBase.StatusCode(int).
ObjectResult StatusCode (HttpStatusCode statusCode, object errorMessage)
Strongly type calls to ControllerBase.StatusCode(int, object).
ObjectResult Created (object payload)
Generic 201 response with a given payload .
ObjectResult RateLimit (RateLimitExceededException rateLimitException)
429 response for a given rateLimitException .
virtual Task< IActionResult > ValidateRequest (CancellationToken cancellationToken)
Performs validation a request.
IActionResult HeadersIssue (bool ignoreMissingAuth)
Response for missing/Invalid headers.
Task< IActionResult > Paginated< TModel > (Func< Task< PaginatableResult< TModel > > > queryGenerator, Func< TModel, Task > resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
Task< IActionResult > Paginated< TModel, TApiModel > (Func< Task< PaginatableResult< TModel > > > queryGenerator, Func< TApiModel, Task > resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
Properties
ApiHeaders ApiHeaders [get, private set]
The Api.ApiHeaders for the operation.
IDatabaseContext DatabaseContext [get]
The IDatabaseContext for the operation.
IAuthenticationContext AuthenticationContext [get]
The IAuthenticationContext for the operation.
ILogger< ApiController > Logger [get]
The ILogger for the ApiController.
Models.Instance Instance [get]
The Instance for the operation.
Private Member Functions
async Task< IActionResult > PaginatedImpl< TModel, TResultModel > (Func< Task< PaginatableResult< TModel > > > queryGenerator, Func< TResultModel, Task > resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
Private Attributes
readonly bool requireHeaders
If ApiHeaders are required.
Static Private Attributes
const ushort DefaultPageSize = 10
Default size of Paginated<TModel> results.
const ushort MaximumPageSize = 100
Maximum size of Paginated<TModel> results.
Detailed Description
Base Controller for API functions.
Definition at line 35 of file ApiController.cs.
Constructor & Destructor Documentation
ApiController()
Tgstation.Server.Host.Controllers.ApiController.ApiController (IDatabaseContext databaseContext, IAuthenticationContextFactory authenticationContextFactory, ILogger< ApiController > logger, bool requireHeaders) protected
Initializes a new instance of the ApiController class.
Parameters
databaseContext The value of DatabaseContext.
authenticationContextFactory The IAuthenticationContextFactory for the ApiController.
logger The value of Logger.
requireHeaders The value of requireHeaders.
Definition at line 84 of file ApiController.cs.
        {
            DatabaseContext = databaseContext ?? throw new ArgumentNullException(nameof(databaseContext));
            if (authenticationContextFactory == null)
                throw new ArgumentNullException(nameof(authenticationContextFactory));
            Logger = logger ?? throw new ArgumentNullException(nameof(logger));
            AuthenticationContext = authenticationContextFactory.CurrentAuthenticationContext;
            Instance = AuthenticationContext?.InstancePermissionSet?.Instance;
            this.requireHeaders = requireHeaders;
        }
References Tgstation.Server.Host.Security.IAuthenticationContextFactory.CurrentAuthenticationContext, Tgstation.Server.Host.Models.InstancePermissionSet.Instance, Tgstation.Server.Host.Security.AuthenticationContext.InstancePermissionSet, Tgstation.Server.Host.Controllers.ApiController.Logger, and Tgstation.Server.Host.Controllers.ApiController.requireHeaders.
Member Function Documentation
Created()
ObjectResult Tgstation.Server.Host.Controllers.ApiController.Created (object payload) protected
Generic 201 response with a given payload .
Parameters
payload The accompanying API payload.
Returns
A HttpStatusCode.Created ObjectResult with the given payload .
Referenced by Tgstation.Server.Host.Controllers.InstancePermissionSetController.Create(), Tgstation.Server.Host.Controllers.RepositoryController.Create(), Tgstation.Server.Host.Controllers.UserController.Create(), Tgstation.Server.Host.Controllers.UserGroupController.Create(), Tgstation.Server.Host.Controllers.ConfigurationController.CreateDirectory(), and Tgstation.Server.Host.Controllers.RepositoryController.Read().
Gone()
ObjectResult Tgstation.Server.Host.Controllers.ApiController.Gone () protected
Generic 410 response.
Returns
An ObjectResult with HttpStatusCode.Gone.
Referenced by Tgstation.Server.Host.Controllers.InstancePermissionSetController.Create(), Tgstation.Server.Host.Controllers.RepositoryController.Create(), Tgstation.Server.Host.Controllers.UserController.Create(), Tgstation.Server.Host.Controllers.RepositoryController.Delete(), Tgstation.Server.Host.Controllers.InstancePermissionSetController.Delete(), Tgstation.Server.Host.Controllers.JobController.Delete(), Tgstation.Server.Host.Controllers.UserGroupController.Delete(), Tgstation.Server.Host.Controllers.ConfigurationController.Directory(), Tgstation.Server.Host.Controllers.TransferController.Download(), Tgstation.Server.Host.Controllers.ConfigurationController.File(), Tgstation.Server.Host.Controllers.ChatController.GetId(), Tgstation.Server.Host.Controllers.InstancePermissionSetController.GetId(), Tgstation.Server.Host.Controllers.UserGroupController.GetId(), Tgstation.Server.Host.Controllers.RepositoryController.Read(), Tgstation.Server.Host.Controllers.DreamDaemonController.ReadImpl(), Tgstation.Server.Host.Controllers.ChatController.Update(), Tgstation.Server.Host.Controllers.DreamDaemonController.Update(), Tgstation.Server.Host.Controllers.DreamMakerController.Update(), Tgstation.Server.Host.Controllers.InstancePermissionSetController.Update(), Tgstation.Server.Host.Controllers.RepositoryController.Update(), Tgstation.Server.Host.Controllers.AdministrationController.Update(), Tgstation.Server.Host.Controllers.UserGroupController.Update(), Tgstation.Server.Host.Controllers.UserController.Update(), and Tgstation.Server.Host.Controllers.TransferController.Upload().
HeadersIssue()
IActionResult Tgstation.Server.Host.Controllers.ApiController.HeadersIssue (bool ignoreMissingAuth) protected
Response for missing/Invalid headers.
Parameters
ignoreMissingAuth Whether or not errors due to missing HeaderNames.Authorization should be thrown.
Returns
The appropriate IActionResult.
Definition at line 282 of file ApiController.cs.
        {
            HeadersException headersException;
            try
            {
                _ = new ApiHeaders(Request.GetTypedHeaders(), ignoreMissingAuth);
                throw new InvalidOperationException("Expected a header parse exception!");
            }
            catch (HeadersException ex)
            {
                headersException = ex;
            }
            var errorMessage = new ErrorMessageResponse(ErrorCode.BadHeaders)
            {
                AdditionalData = headersException.Message,
            };
            if (headersException.MissingOrMalformedHeaders.HasFlag(HeaderTypes.Accept))
                return StatusCode(HttpStatusCode.NotAcceptable, errorMessage);
            return BadRequest(errorMessage);
        }
References Tgstation.Server.Host.Controllers.ApiController.ApiHeaders, Tgstation.Server.Api.HeadersException.MissingOrMalformedHeaders, and Tgstation.Server.Host.Controllers.ApiController.StatusCode().
Referenced by Tgstation.Server.Host.Controllers.HomeController.CreateToken(), Tgstation.Server.Host.Controllers.HomeController.Home(), and Tgstation.Server.Host.Controllers.ApiController.OnActionExecutionAsync().
NotFound()
new NotFoundObjectResult Tgstation.Server.Host.Controllers.ApiController.NotFound () protected
Generic 404 response.
Returns
An ObjectResult with HttpStatusCode.NotFound.
Referenced by Tgstation.Server.Host.Controllers.JobController.Delete(), Tgstation.Server.Host.Controllers.DreamMakerController.GetId(), Tgstation.Server.Host.Controllers.JobController.GetId(), Tgstation.Server.Host.Controllers.UserController.GetId(), and Tgstation.Server.Host.Controllers.UserController.Update().
OnActionExecutionAsync()
override async Task Tgstation.Server.Host.Controllers.ApiController.OnActionExecutionAsync (ActionExecutingContext context, ActionExecutionDelegate next)
Definition at line 101 of file ApiController.cs.
        {
            if (context == null)
                throw new ArgumentNullException(nameof(context));
            // ALL valid token and login requests that match a route go through this function
            // 404 is returned before
            if (AuthenticationContext != null && AuthenticationContext.User == null)
            {
                // valid token, expired password
                await Unauthorized().ExecuteResultAsync(context);
                return;
            }
            // validate the headers
            try
            {
                ApiHeaders = new ApiHeaders(Request.GetTypedHeaders());
                if (!ApiHeaders.Compatible())
                {
                    await StatusCode(
                        HttpStatusCode.UpgradeRequired,
                        new ErrorMessageResponse(ErrorCode.ApiMismatch))
                        .ExecuteResultAsync(context);
                    return;
                }
                var errorCase = await ValidateRequest(context.HttpContext.RequestAborted);
                if (errorCase != null)
                {
                    await errorCase.ExecuteResultAsync(context);
                    return;
                }
            }
            catch (HeadersException)
            {
                if (requireHeaders)
                {
                    await HeadersIssue(false)
                        .ExecuteResultAsync(context);
                    return;
                }
            }
            if (ModelState?.IsValid == false)
            {
                var errorMessages = ModelState
                    .SelectMany(x => x.Value.Errors)
                    .Select(x => x.ErrorMessage)
                    // We use RequiredAttributes purely for preventing properties from becoming nullable in the databases
                    // We validate missing required fields in controllers
                    // Unfortunately, we can't remove the whole validator for that as it checks other things like StringLength
                    // This is the best way to deal with it unfortunately
                    .Where(x => !x.EndsWith(" field is required.", StringComparison.Ordinal));
                if (errorMessages.Any())
                {
                    await BadRequest(
                        new ErrorMessageResponse(ErrorCode.ModelValidationFailure)
{
                            AdditionalData = String.Join(Environment.NewLine, errorMessages),
                        })
                        .ExecuteResultAsync(context);
                    return;
                }
                ModelState.Clear();
            }
            using (ApiHeaders?.InstanceId != null
                ? LogContext.PushProperty(SerilogContextHelper.InstanceIdContextProperty, ApiHeaders.InstanceId)
                : null)
            using (AuthenticationContext != null
                ? LogContext.PushProperty(SerilogContextHelper.UserIdContextProperty, AuthenticationContext.User.Id)
                : null)
            using (LogContext.PushProperty(SerilogContextHelper.RequestPathContextProperty, $"{Request.Method} {Request.Path}"))
            {
                if (ApiHeaders != null)
                {
                    var isGet = HttpMethods.IsGet(Request.Method);
                    if (!(isGet && Request.Path.StartsWithSegments(Routes.Jobs, StringComparison.OrdinalIgnoreCase)))
                        Logger.Log(
                            isGet
                                ? LogLevel.Trace
                                : LogLevel.Debug,
                            "Starting API request: Version: {clientApiVersion}. {userAgentHeaderName}: {clientUserAgent}",
                            ApiHeaders.ApiVersion.Semver(),
                            HeaderNames.UserAgent,
                            ApiHeaders.RawUserAgent);
                }
                else if (Request.Headers.TryGetValue(HeaderNames.UserAgent, out var userAgents))
                    Logger.LogDebug(
                        "Starting unauthorized API request. {userAgentHeaderName}: {allUserAgents}",
                        HeaderNames.UserAgent,
                        userAgents);
                else
                    Logger.LogDebug(
                        "Starting unauthorized API request. No {userAgentHeaderName}!",
                        HeaderNames.UserAgent);
                await base.OnActionExecutionAsync(context, next);
            }
        }
References Tgstation.Server.Host.Controllers.ApiController.ApiHeaders, Tgstation.Server.Api.ApiHeaders.ApiVersion, Tgstation.Server.Api.ApiHeaders.Compatible(), Tgstation.Server.Host.Controllers.ApiController.HeadersIssue(), Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Api.ApiHeaders.InstanceId, Tgstation.Server.Host.Utils.SerilogContextHelper.InstanceIdContextProperty, Tgstation.Server.Api.Routes.Jobs, Tgstation.Server.Host.Controllers.ApiController.Logger, Tgstation.Server.Api.ApiHeaders.RawUserAgent, Tgstation.Server.Host.Utils.SerilogContextHelper.RequestPathContextProperty, Tgstation.Server.Host.Controllers.ApiController.requireHeaders, Tgstation.Server.Host.Controllers.ApiController.StatusCode(), Tgstation.Server.Host.Security.AuthenticationContext.User, Tgstation.Server.Host.Utils.SerilogContextHelper.UserIdContextProperty, and Tgstation.Server.Host.Controllers.ApiController.ValidateRequest().
Paginated< TModel >()
Task< IActionResult > Tgstation.Server.Host.Controllers.ApiController.Paginated< TModel > (Func< Task< PaginatableResult< TModel > > > queryGenerator, Func< TModel, Task > resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken) protected
Generates a paginated response.
Template Parameters
TModel The Type of model being generated and returned.
Parameters
queryGenerator A Func<TResult> resulting in a Task<TResult> resulting in the generated PaginatableResult<TModel>.
resultTransformer A Func<T, TResult> to transform the TModel s after being queried.
pageQuery The requested page from the query.
pageSizeQuery The requested page size from the query.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the IActionResult for the operation.
Paginated< TModel, TApiModel >()
Task< IActionResult > Tgstation.Server.Host.Controllers.ApiController.Paginated< TModel, TApiModel > (Func< Task< PaginatableResult< TModel > > > queryGenerator, Func< TApiModel, Task > resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken) protected
Generates a paginated response.
Template Parameters
TModel The Type of model being generated.
TApiModel The Type of model being returned.
Parameters
queryGenerator A Func<TResult> resulting in a Task<TResult> resulting in the generated PaginatableResult<TModel>.
resultTransformer A Func<T, TResult> to transform the TApiModel s after being queried.
pageQuery The requested page from the query.
pageSizeQuery The requested page size from the query.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the IActionResult for the operation.
Type Constraints
TModel : IApiTransformable<TApiModel>
TModel : PaginatedImpl
TModel : queryGenerator
TModel : resultTransformer
TModel : pageQuery
TModel : pageSizeQuery
TModel : cancellationToken
PaginatedImpl< TModel, TResultModel >()
async Task< IActionResult > Tgstation.Server.Host.Controllers.ApiController.PaginatedImpl< TModel, TResultModel > (Func< Task< PaginatableResult< TModel > > > queryGenerator, Func< TResultModel, Task > resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken) private
Generates a paginated response.
Template Parameters
TModel The Type of model being generated. If different from TResultModel , must implement IApiTransformable<TApiModel> for TResultModel .
TResultModel The Type of model being returned.
Parameters
queryGenerator A Func<TResult> resulting in a Task<TResult> resulting in the generated PaginatableResult<TModel>.
resultTransformer A Func<T, TResult> to transform the TResultModel s after being queried.
pageQuery The requested page from the query.
pageSizeQuery The requested page size from the query.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the IActionResult for the operation.
Definition at line 364 of file ApiController.cs.
        {
            if (queryGenerator == null)
                throw new ArgumentNullException(nameof(queryGenerator));
            if (pageQuery <= 0 || pageSizeQuery <= 0)
                return BadRequest(new ErrorMessageResponse(ErrorCode.ApiInvalidPageOrPageSize));
            var pageSize = pageSizeQuery ?? DefaultPageSize;
            if (pageSize > MaximumPageSize)
                return BadRequest(new ErrorMessageResponse(ErrorCode.ApiPageTooLarge)
                {
                    AdditionalData = $"Maximum page size: {MaximumPageSize}",
                });
            var page = pageQuery ?? 1;
            var paginationResult = await queryGenerator();
            if (paginationResult.EarlyOut != null)
                return paginationResult.EarlyOut;
            var queriedResults = paginationResult
                .Results
                .Skip((page - 1) * pageSize)
                .Take(pageSize);
            int totalResults;
            List<TModel> pagedResults;
            if (queriedResults.Provider is IAsyncQueryProvider)
            {
                totalResults = await paginationResult.Results.CountAsync(cancellationToken);
                pagedResults = await queriedResults
                    .ToListAsync(cancellationToken);
            }
            else
            {
                totalResults = paginationResult.Results.Count();
                pagedResults = queriedResults.ToList();
            }
            ICollection<TResultModel> finalResults;
            if (typeof(TModel) == typeof(TResultModel))
                finalResults = (List<TResultModel>)(object)pagedResults; // clearly a safe cast
            else
                finalResults = pagedResults
                    .OfType<IApiTransformable<TResultModel>>()
                    .Select(x => x.ToApi())
                    .ToList();
            if (resultTransformer != null)
                foreach (var finalResult in finalResults)
                    await resultTransformer(finalResult);
            var carryTheOne = totalResults % pageSize != 0
                ? 1
                : 0;
            return Json(
                new PaginatedResponse<TResultModel>
                {
                    Content = finalResults,
                    PageSize = pageSize,
                    TotalPages = (ushort)(totalResults / pageSize) + carryTheOne,
                    TotalItems = totalResults,
                });
        }
References Tgstation.Server.Host.Controllers.ApiController.DefaultPageSize, and Tgstation.Server.Host.Controllers.ApiController.MaximumPageSize.
RateLimit()
ObjectResult Tgstation.Server.Host.Controllers.ApiController.RateLimit (RateLimitExceededException rateLimitException) protected
429 response for a given rateLimitException .
Parameters
rateLimitException The RateLimitExceededException that occurred.
Returns
A HttpStatusCode.TooManyRequests ObjectResult.
Definition at line 257 of file ApiController.cs.
        {
            if (rateLimitException == null)
                throw new ArgumentNullException(nameof(rateLimitException));
            Logger.LogWarning(rateLimitException, "Exceeded GitHub rate limit!");
            var secondsString = Math.Ceiling(rateLimitException.GetRetryAfterTimeSpan().TotalSeconds).ToString(CultureInfo.InvariantCulture);
            Response.Headers.Add(HeaderNames.RetryAfter, secondsString);
            return StatusCode(HttpStatusCode.TooManyRequests, new ErrorMessageResponse(ErrorCode.GitHubApiRateLimit));
        }
References Tgstation.Server.Host.Controllers.ApiController.Logger, and Tgstation.Server.Host.Controllers.ApiController.StatusCode().
Referenced by Tgstation.Server.Host.Controllers.HomeController.CreateToken(), Tgstation.Server.Host.Controllers.AdministrationController.Read(), and Tgstation.Server.Host.Controllers.AdministrationController.Update().
RequiresPosixSystemIdentity()
ObjectResult Tgstation.Server.Host.Controllers.ApiController.RequiresPosixSystemIdentity (NotImplementedException ex) protected
Generic 501 response.
Parameters
ex The NotImplementedException that was thrown.
Returns
An ObjectResult with HttpStatusCode.NotImplemented.
Definition at line 224 of file ApiController.cs.
        {
            Logger.LogTrace(ex, "System identities not implemented!");
            return StatusCode(HttpStatusCode.NotImplemented, new ErrorMessageResponse(ErrorCode.RequiresPosixSystemIdentity));
        }
References Tgstation.Server.Host.Controllers.ApiController.Logger, and Tgstation.Server.Host.Controllers.ApiController.StatusCode().
Referenced by Tgstation.Server.Host.Controllers.UserController.Create(), Tgstation.Server.Host.Controllers.ConfigurationController.CreateDirectory(), Tgstation.Server.Host.Controllers.HomeController.CreateToken(), Tgstation.Server.Host.Controllers.ConfigurationController.DeleteDirectory(), Tgstation.Server.Host.Controllers.ConfigurationController.Directory(), Tgstation.Server.Host.Controllers.ConfigurationController.File(), and Tgstation.Server.Host.Controllers.ConfigurationController.Update().
StatusCode() [1/2]
StatusCodeResult Tgstation.Server.Host.Controllers.ApiController.StatusCode (HttpStatusCode statusCode) protected
Strongly type calls to ControllerBase.StatusCode(int).
Parameters
statusCode The HttpStatusCode.
Returns
A StatusCodeResult with the given statusCode .
Referenced by Tgstation.Server.Host.Controllers.ChatController.Create(), Tgstation.Server.Host.Controllers.AdministrationController.Delete(), Tgstation.Server.Host.Controllers.TransferController.Download(), Tgstation.Server.Host.Controllers.ApiController.HeadersIssue(), Tgstation.Server.Host.Controllers.HomeController.Home(), Tgstation.Server.Host.Controllers.ApiController.OnActionExecutionAsync(), Tgstation.Server.Host.Controllers.ApiController.RateLimit(), Tgstation.Server.Host.Controllers.AdministrationController.Read(), Tgstation.Server.Host.Controllers.ApiController.RequiresPosixSystemIdentity(), and Tgstation.Server.Host.Controllers.AdministrationController.Update().
StatusCode() [2/2]
ObjectResult Tgstation.Server.Host.Controllers.ApiController.StatusCode (HttpStatusCode statusCode, object errorMessage) protected
Strongly type calls to ControllerBase.StatusCode(int, object).
Parameters
statusCode The HttpStatusCode.
errorMessage The accompanying ErrorMessageResponse payload.
Returns
A StatusCodeResult with the given statusCode .
ValidateRequest()
virtual Task< IActionResult > Tgstation.Server.Host.Controllers.ApiController.ValidateRequest (CancellationToken cancellationToken) protected virtual
Performs validation a request.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in an appropriate IActionResult on validation failure, null otherwise.
Reimplemented in Tgstation.Server.Host.Controllers.ComponentInterfacingController.
Referenced by Tgstation.Server.Host.Controllers.ApiController.OnActionExecutionAsync().
Member Data Documentation
DefaultPageSize
const ushort Tgstation.Server.Host.Controllers.ApiController.DefaultPageSize = 10 static private
Default size of Paginated<TModel> results.
Definition at line 40 of file ApiController.cs.
Referenced by Tgstation.Server.Host.Controllers.ApiController.PaginatedImpl< TModel, TResultModel >().
MaximumPageSize
const ushort Tgstation.Server.Host.Controllers.ApiController.MaximumPageSize = 100 static private
Maximum size of Paginated<TModel> results.
Definition at line 45 of file ApiController.cs.
Referenced by Tgstation.Server.Host.Controllers.ApiController.PaginatedImpl< TModel, TResultModel >().
requireHeaders
readonly bool Tgstation.Server.Host.Controllers.ApiController.requireHeaders private
If ApiHeaders are required.
Definition at line 75 of file ApiController.cs.
Referenced by Tgstation.Server.Host.Controllers.ApiController.ApiController(), and Tgstation.Server.Host.Controllers.ApiController.OnActionExecutionAsync().
Property Documentation
ApiHeaders
ApiHeaders Tgstation.Server.Host.Controllers.ApiController.ApiHeaders get private set protected
The Api.ApiHeaders for the operation.
Definition at line 50 of file ApiController.cs.
{ get; private set; }
Referenced by Tgstation.Server.Host.Controllers.ApiController.HeadersIssue(), Tgstation.Server.Host.Controllers.HomeController.Home(), and Tgstation.Server.Host.Controllers.ApiController.OnActionExecutionAsync().
AuthenticationContext
IAuthenticationContext Tgstation.Server.Host.Controllers.ApiController.AuthenticationContext get protected
The IAuthenticationContext for the operation.
Definition at line 60 of file ApiController.cs.
{ get; }
DatabaseContext
IDatabaseContext Tgstation.Server.Host.Controllers.ApiController.DatabaseContext get protected
The IDatabaseContext for the operation.
Definition at line 55 of file ApiController.cs.
{ get; }
Instance
Models.Instance Tgstation.Server.Host.Controllers.ApiController.Instance get protected
The Instance for the operation.
Definition at line 70 of file ApiController.cs.
{ get; }
Referenced by Tgstation.Server.Host.Controllers.DreamDaemonController.CreateDump(), Tgstation.Server.Host.Controllers.RepositoryController.Delete(), Tgstation.Server.Host.Controllers.DreamDaemonController.Restart(), and Tgstation.Server.Host.Controllers.RepositoryController.Update().
Logger
ILogger<ApiController> Tgstation.Server.Host.Controllers.ApiController.Logger get protected
The ILogger for the ApiController.
Definition at line 65 of file ApiController.cs.
{ get; }
Referenced by Tgstation.Server.Host.Controllers.ApiController.ApiController(), Tgstation.Server.Host.Controllers.UserController.Create(), Tgstation.Server.Host.Controllers.UserGroupController.Create(), Tgstation.Server.Host.Controllers.ConfigurationController.CreateDirectory(), Tgstation.Server.Host.Controllers.HomeController.CreateToken(), Tgstation.Server.Host.Controllers.AdministrationController.Delete(), Tgstation.Server.Host.Controllers.RepositoryController.Delete(), Tgstation.Server.Host.Controllers.ConfigurationController.File(), Tgstation.Server.Host.Controllers.HomeController.Home(), Tgstation.Server.Host.Controllers.ApiController.OnActionExecutionAsync(), Tgstation.Server.Host.Controllers.RepositoryController.PopulateApi(), Tgstation.Server.Host.Controllers.ApiController.RateLimit(), Tgstation.Server.Host.Controllers.AdministrationController.Read(), Tgstation.Server.Host.Controllers.ApiController.RequiresPosixSystemIdentity(), Tgstation.Server.Host.Controllers.ByondController.Update(), Tgstation.Server.Host.Controllers.ConfigurationController.Update(), Tgstation.Server.Host.Controllers.AdministrationController.Update(), Tgstation.Server.Host.Controllers.UserController.Update(), and Tgstation.Server.Host.Controllers.ComponentInterfacingController.ValidateInstanceOnlineStatus().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Controllers/ApiController.cs