tgstation-server: Tgstation.Server.Client.ServerClientFactory Class Reference
Tgstation.Server.Client.ServerClientFactory Class Reference
Public Member Functions
ServerClientFactory (ProductHeaderValue productHeaderValue)
Initializes a new instance of the ServerClientFactory class.
ValueTask< IServerClient > CreateFromLogin (Uri host, string username, string password, IEnumerable< IRequestLogger >? requestLoggers=null, TimeSpan? timeout=null, bool attemptLoginRefresh=true, CancellationToken cancellationToken=default)
Create a IServerClient using a password login.
Parameters
host The URL to access TGS.
username The username to for the IServerClient.
password The password for the IServerClient.
requestLoggers Optional initial IRequestLoggers to add to the IServerClient.
timeout Optional TimeSpan representing timeout for the connection.
attemptLoginRefresh Attempt to refresh the received TokenResponse when it expires or becomes invalid. username and password will be stored in memory if this is true.
cancellationToken Optional CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a new IServerClient.
ValueTask< IServerClient > CreateFromOAuth (Uri host, string oAuthCode, OAuthProvider oAuthProvider, IEnumerable< IRequestLogger >? requestLoggers=null, TimeSpan? timeout=null, CancellationToken cancellationToken=default)
Create a IServerClient using am OAuth login.
Parameters
host The URL to access TGS.
oAuthCode The OAuth code used to complete the flow.
oAuthProvider The OAuthProvider.
requestLoggers Optional initial IRequestLoggers to add to the IServerClient.
timeout Optional TimeSpan representing timeout for the connection.
cancellationToken Optional CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a new IServerClient.
IServerClient CreateFromToken (Uri host, TokenResponse token)
Create a IServerClient.
Parameters
host The URL to access TGS.
token The TokenResponse to access the API with.
Returns
A new IServerClient.
async ValueTask< ServerInformationResponse > GetServerInformation (Uri host, IEnumerable< IRequestLogger >? requestLoggers=null, TimeSpan? timeout=null, CancellationToken cancellationToken=default)
Gets the ServerInformationResponse for a given host .
Parameters
host The URL to access TGS.
requestLoggers Optional IRequestLoggers.
timeout Optional TimeSpan representing timeout for the HTTP request.
cancellationToken Optional CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the ServerInformationResponse.
ValueTask< ServerInformationResponse > GetServerInformation (Uri host, IEnumerable< IRequestLogger >? requestLoggers=null, TimeSpan? timeout=null, CancellationToken cancellationToken=default)
Gets the ServerInformationResponse for a given host .
ValueTask< IServerClient > CreateFromLogin (Uri host, string username, string password, IEnumerable< IRequestLogger >? requestLoggers=null, TimeSpan? timeout=null, bool attemptLoginRefresh=true, CancellationToken cancellationToken=default)
Create a IServerClient using a password login.
ValueTask< IServerClient > CreateFromOAuth (Uri host, string oAuthCode, OAuthProvider oAuthProvider, IEnumerable< IRequestLogger >? requestLoggers=null, TimeSpan? timeout=null, CancellationToken cancellationToken=default)
Create a IServerClient using am OAuth login.
IServerClient CreateFromToken (Uri host, TokenResponse token)
Create a IServerClient.
Private Member Functions
async ValueTask< IServerClient > CreateWithNewToken (Uri host, ApiHeaders loginHeaders, IEnumerable< IRequestLogger >? requestLoggers, TimeSpan? timeout, bool attemptLoginRefresh, CancellationToken cancellationToken)
Creates a IServerClient from a login operation.
Static Private Member Functions
static ServerClientFactory ()
Initializes static members of the ServerClientFactory class.
Private Attributes
readonly ProductHeaderValue productHeaderValue
The ProductHeaderValue for the ServerClientFactory.
Detailed Description
Definition at line 15 of file ServerClientFactory.cs.
Constructor & Destructor Documentation
ServerClientFactory() [1/2]
static Tgstation.Server.Client.ServerClientFactory.ServerClientFactory () static private
Initializes static members of the ServerClientFactory class.
Definition at line 30 of file ServerClientFactory.cs.
        {
            ApiClientFactory = new ApiClientFactory();
        }
ServerClientFactory() [2/2]
Tgstation.Server.Client.ServerClientFactory.ServerClientFactory (ProductHeaderValue productHeaderValue)
Initializes a new instance of the ServerClientFactory class.
Parameters
productHeaderValue The value of productHeaderValue.
Definition at line 39 of file ServerClientFactory.cs.
        {
            this.productHeaderValue = productHeaderValue ?? throw new ArgumentNullException(nameof(productHeaderValue));
        }
References Tgstation.Server.Client.ServerClientFactory.productHeaderValue.
Member Function Documentation
CreateFromLogin()
ValueTask< IServerClient > Tgstation.Server.Client.ServerClientFactory.CreateFromLogin (Uri host, string username, string password, IEnumerable< IRequestLogger >? requestLoggers = null, TimeSpan? timeout = null, bool attemptLoginRefresh = true, CancellationToken cancellationToken = default)
Create a IServerClient using a password login.
Parameters
host The URL to access TGS.
username The username to for the IServerClient.
password The password for the IServerClient.
requestLoggers Optional initial IRequestLoggers to add to the IServerClient.
timeout Optional TimeSpan representing timeout for the connection.
attemptLoginRefresh Attempt to refresh the received TokenResponse when it expires or becomes invalid. username and password will be stored in memory if this is true.
cancellationToken Optional CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a new IServerClient.
Implements Tgstation.Server.Client.IServerClientFactory.
Definition at line 45 of file ServerClientFactory.cs.
        {
            if (host == null)
                throw new ArgumentNullException(nameof(host));
            if (username == null)
                throw new ArgumentNullException(nameof(username));
            if (password == null)
                throw new ArgumentNullException(nameof(password));
            var loginHeaders = new ApiHeaders(productHeaderValue, username, password);
            return CreateWithNewToken(
                host,
                loginHeaders,
                requestLoggers,
                timeout,
                attemptLoginRefresh,
                cancellationToken);
        }
References Tgstation.Server.Client.ServerClientFactory.CreateWithNewToken(), and Tgstation.Server.Client.ServerClientFactory.productHeaderValue.
CreateFromOAuth()
ValueTask< IServerClient > Tgstation.Server.Client.ServerClientFactory.CreateFromOAuth (Uri host, string oAuthCode, OAuthProvider oAuthProvider, IEnumerable< IRequestLogger >? requestLoggers = null, TimeSpan? timeout = null, CancellationToken cancellationToken = default)
Create a IServerClient using am OAuth login.
Parameters
host The URL to access TGS.
oAuthCode The OAuth code used to complete the flow.
oAuthProvider The OAuthProvider.
requestLoggers Optional initial IRequestLoggers to add to the IServerClient.
timeout Optional TimeSpan representing timeout for the connection.
cancellationToken Optional CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a new IServerClient.
Implements Tgstation.Server.Client.IServerClientFactory.
Definition at line 72 of file ServerClientFactory.cs.
        {
            if (host == null)
                throw new ArgumentNullException(nameof(host));
            if (oAuthCode == null)
                throw new ArgumentNullException(nameof(oAuthCode));
            var loginHeaders = new ApiHeaders(productHeaderValue, oAuthCode, oAuthProvider);
            return CreateWithNewToken(
                host,
                loginHeaders,
                requestLoggers,
                timeout,
                false,
                cancellationToken);
        }
References Tgstation.Server.Client.ServerClientFactory.CreateWithNewToken(), and Tgstation.Server.Client.ServerClientFactory.productHeaderValue.
CreateFromToken()
IServerClient Tgstation.Server.Client.ServerClientFactory.CreateFromToken (Uri host, TokenResponse token)
Create a IServerClient.
Parameters
host The URL to access TGS.
token The TokenResponse to access the API with.
Returns
A new IServerClient.
Implements Tgstation.Server.Client.IServerClientFactory.
Definition at line 96 of file ServerClientFactory.cs.
        {
            if (host == null)
                throw new ArgumentNullException(nameof(host));
            if (token == null)
                throw new ArgumentNullException(nameof(token));
            if (token.Bearer == null)
                throw new InvalidOperationException("token.Bearer should not be null!");
            var serverClient = new ServerClient(
                ApiClientFactory.CreateApiClient(
                    host,
                    new ApiHeaders(
                        productHeaderValue,
                        token),
                    null,
                    false));
            return serverClient;
        }
References Tgstation.Server.Api.Models.Response.TokenResponse.Bearer, Tgstation.Server.Client.ApiClientFactory.CreateApiClient(), and Tgstation.Server.Client.ServerClientFactory.productHeaderValue.
CreateWithNewToken()
async ValueTask< IServerClient > Tgstation.Server.Client.ServerClientFactory.CreateWithNewToken (Uri host, ApiHeaders loginHeaders, IEnumerable< IRequestLogger >? requestLoggers, TimeSpan? timeout, bool attemptLoginRefresh, CancellationToken cancellationToken) private
Creates a IServerClient from a login operation.
Parameters
host The URL to access TGS.
loginHeaders The ApiHeaders to use for the login operation.
requestLoggers Optional initial IRequestLoggers to add to the IServerClient.
timeout Optional TimeSpan representing timeout for the connection.
attemptLoginRefresh If loginHeaders may be used to re-login in the future.
cancellationToken Optional CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a new IServerClient.
Definition at line 154 of file ServerClientFactory.cs.
        {
            requestLoggers ??= Enumerable.Empty<IRequestLogger>();
            TokenResponse token;
            await using (var api = ApiClientFactory.CreateApiClient(host, loginHeaders, null, false))
            {
                foreach (var requestLogger in requestLoggers)
                    api.AddRequestLogger(requestLogger);
                if (timeout.HasValue)
                    api.Timeout = timeout.Value;
                token = await api.Update<TokenResponse>(Routes.ApiRoot, cancellationToken).ConfigureAwait(false);
            }
            var apiHeaders = new ApiHeaders(productHeaderValue, token);
            var client = new ServerClient(
                ApiClientFactory.CreateApiClient(
                    host,
                    apiHeaders,
                    attemptLoginRefresh ? loginHeaders : null,
                    false));
            if (timeout.HasValue)
                client.Timeout = timeout.Value;
            foreach (var requestLogger in requestLoggers)
                client.AddRequestLogger(requestLogger);
            return client;
        }
References Tgstation.Server.Api.Routes.ApiRoot, Tgstation.Server.Client.ApiClientFactory.CreateApiClient(), and Tgstation.Server.Client.ServerClientFactory.productHeaderValue.
Referenced by Tgstation.Server.Client.ServerClientFactory.CreateFromLogin(), and Tgstation.Server.Client.ServerClientFactory.CreateFromOAuth().
GetServerInformation()
async ValueTask< ServerInformationResponse > Tgstation.Server.Client.ServerClientFactory.GetServerInformation (Uri host, IEnumerable< IRequestLogger >? requestLoggers = null, TimeSpan? timeout = null, CancellationToken cancellationToken = default)
Gets the ServerInformationResponse for a given host .
Parameters
host The URL to access TGS.
requestLoggers Optional IRequestLoggers.
timeout Optional TimeSpan representing timeout for the HTTP request.
cancellationToken Optional CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the ServerInformationResponse.
Implements Tgstation.Server.Client.IServerClientFactory.
Definition at line 117 of file ServerClientFactory.cs.
        {
            await using var api = ApiClientFactory.CreateApiClient(
                host,
                new ApiHeaders(
                    productHeaderValue,
                    new TokenResponse
                    {
                        Bearer = "unused",
                    }),
                null,
                true);
            if (requestLoggers != null)
                foreach (var requestLogger in requestLoggers)
                    api.AddRequestLogger(requestLogger);
            if (timeout.HasValue)
                api.Timeout = timeout.Value;
            return await api.Read<ServerInformationResponse>(Routes.ApiRoot, cancellationToken).ConfigureAwait(false);
        }
References Tgstation.Server.Client.IApiClient.AddRequestLogger(), Tgstation.Server.Api.Routes.ApiRoot, Tgstation.Server.Client.ApiClientFactory.CreateApiClient(), and Tgstation.Server.Client.ServerClientFactory.productHeaderValue.
Member Data Documentation
productHeaderValue
readonly ProductHeaderValue Tgstation.Server.Client.ServerClientFactory.productHeaderValue private
The ProductHeaderValue for the ServerClientFactory.
Definition at line 25 of file ServerClientFactory.cs.
Referenced by Tgstation.Server.Client.ServerClientFactory.CreateFromLogin(), Tgstation.Server.Client.ServerClientFactory.CreateFromOAuth(), Tgstation.Server.Client.ServerClientFactory.CreateFromToken(), Tgstation.Server.Client.ServerClientFactory.CreateWithNewToken(), Tgstation.Server.Client.ServerClientFactory.GetServerInformation(), and Tgstation.Server.Client.ServerClientFactory.ServerClientFactory().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Client/ServerClientFactory.cs