tgstation-server: Tgstation.Server.Host.Components.Repository.GitRemoteFeaturesFactory Class Reference
Tgstation.Server.Host.Components.Repository.GitRemoteFeaturesFactory Class Reference sealed
Public Member Functions
GitRemoteFeaturesFactory (IGitHubServiceFactory gitHubServiceFactory, ILoggerFactory loggerFactory, ILogger< GitRemoteFeaturesFactory > logger)
Initializes a new instance of the GitRemoteFeaturesFactory class.
IGitRemoteFeatures CreateGitRemoteFeatures (IRepository repository)
Create the IGitRemoteFeatures for a given repository .
Parameters
repository The IRepository containing the IRepository.Origin to create IGitRemoteFeatures for.
Returns
A new IGitRemoteFeatures instance.
IGitRemoteFeatures CreateGitRemoteFeatures (Uri origin)
Create the IGitRemoteFeatures for a given origin .
Parameters
origin The Uri of the IGitRemoteFeatures origing URL.
Returns
A new IGitRemoteFeatures instance.
RemoteGitProvider ParseRemoteGitProviderFromOrigin (Uri origin)
Gets the RemoteGitProvider for a given origin .
Parameters
origin The Uri of the origin.
Returns
The RemoteGitProvider of the origin .
Private Attributes
readonly IGitHubServiceFactory gitHubServiceFactory
The IGitHubServiceFactory for the GitRemoteFeaturesFactory.
readonly ILoggerFactory loggerFactory
The ILoggerFactory for the GitRemoteFeaturesFactory.
readonly ILogger< GitRemoteFeaturesFactory > logger
The ILogger for the GitRemoteFeaturesFactory.
Detailed Description
Definition at line 11 of file GitRemoteFeaturesFactory.cs.
Constructor & Destructor Documentation
GitRemoteFeaturesFactory()
Tgstation.Server.Host.Components.Repository.GitRemoteFeaturesFactory.GitRemoteFeaturesFactory (IGitHubServiceFactory gitHubServiceFactory, ILoggerFactory loggerFactory, ILogger< GitRemoteFeaturesFactory > logger)
Initializes a new instance of the GitRemoteFeaturesFactory class.
Parameters
gitHubServiceFactory The value of gitHubServiceFactory.
loggerFactory The value of loggerFactory.
logger The value of logger.
Definition at line 34 of file GitRemoteFeaturesFactory.cs.
        {
            this.gitHubServiceFactory = gitHubServiceFactory ?? throw new ArgumentNullException(nameof(gitHubServiceFactory));
            this.loggerFactory = loggerFactory ?? throw new ArgumentNullException(nameof(loggerFactory));
            this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }
References Tgstation.Server.Host.Components.Repository.GitRemoteFeaturesFactory.gitHubServiceFactory, Tgstation.Server.Host.Components.Repository.GitRemoteFeaturesFactory.logger, and Tgstation.Server.Host.Components.Repository.GitRemoteFeaturesFactory.loggerFactory.
Member Function Documentation
CreateGitRemoteFeatures() [1/2]
IGitRemoteFeatures Tgstation.Server.Host.Components.Repository.GitRemoteFeaturesFactory.CreateGitRemoteFeatures (IRepository repository)
Create the IGitRemoteFeatures for a given repository .
Parameters
repository The IRepository containing the IRepository.Origin to create IGitRemoteFeatures for.
Returns
A new IGitRemoteFeatures instance.
Implements Tgstation.Server.Host.Components.Repository.IGitRemoteFeaturesFactory.
Definition at line 45 of file GitRemoteFeaturesFactory.cs.
        {
            ArgumentNullException.ThrowIfNull(repository);
            return CreateGitRemoteFeatures(repository.Origin);
        }
References Tgstation.Server.Host.Components.Repository.GitRemoteFeaturesFactory.CreateGitRemoteFeatures(), and Tgstation.Server.Host.Components.Repository.IRepository.Origin.
Referenced by Tgstation.Server.Host.Components.Repository.GitRemoteFeaturesFactory.CreateGitRemoteFeatures().
CreateGitRemoteFeatures() [2/2]
IGitRemoteFeatures Tgstation.Server.Host.Components.Repository.GitRemoteFeaturesFactory.CreateGitRemoteFeatures (Uri origin)
Create the IGitRemoteFeatures for a given origin .
Parameters
origin The Uri of the IGitRemoteFeatures origing URL.
Returns
A new IGitRemoteFeatures instance.
Implements Tgstation.Server.Host.Components.Repository.IGitRemoteFeaturesFactory.
Definition at line 52 of file GitRemoteFeaturesFactory.cs.
        {
            ArgumentNullException.ThrowIfNull(origin);
            var remoteGitProvider = ParseRemoteGitProviderFromOrigin(origin);
            return remoteGitProvider switch
            {
                RemoteGitProvider.GitHub => new GitHubRemoteFeatures(
                    gitHubServiceFactory,
                    loggerFactory.CreateLogger<GitHubRemoteFeatures>(),
                    origin),
                RemoteGitProvider.GitLab => new GitLabRemoteFeatures(
                    loggerFactory.CreateLogger<GitLabRemoteFeatures>(),
                    origin),
                RemoteGitProvider.Unknown => new DefaultGitRemoteFeatures(),
                _ => throw new InvalidOperationException($"Unknown RemoteGitProvider: {remoteGitProvider}!"),
            };
        }
References Tgstation.Server.Host.Components.Repository.GitRemoteFeaturesFactory.gitHubServiceFactory, Tgstation.Server.Host.Components.Repository.GitRemoteFeaturesFactory.loggerFactory, and Tgstation.Server.Host.Components.Repository.GitRemoteFeaturesFactory.ParseRemoteGitProviderFromOrigin().
ParseRemoteGitProviderFromOrigin()
RemoteGitProvider Tgstation.Server.Host.Components.Repository.GitRemoteFeaturesFactory.ParseRemoteGitProviderFromOrigin (Uri origin)
Gets the RemoteGitProvider for a given origin .
Parameters
origin The Uri of the origin.
Returns
The RemoteGitProvider of the origin .
Implements Tgstation.Server.Host.Components.Repository.IGitRemoteFeaturesFactory.
Definition at line 72 of file GitRemoteFeaturesFactory.cs.
        {
            ArgumentNullException.ThrowIfNull(origin);
            switch (origin.Host.ToUpperInvariant())
            {
                case "GITHUB.COM":
                case "WWW.GITHUB.COM":
                case "GIT.GITHUB.COM":
                    return RemoteGitProvider.GitHub;
                case "GITLAB.COM":
                case "WWW.GITLAB.COM":
                case "GIT.GITLAB.COM":
                    return RemoteGitProvider.GitLab;
                default:
                    logger.LogDebug("Unknown git remote: {origin}", origin);
                    return RemoteGitProvider.Unknown;
            }
        }
References Tgstation.Server.Host.Components.Repository.GitRemoteFeaturesFactory.logger.
Referenced by Tgstation.Server.Host.Components.Repository.GitRemoteFeaturesFactory.CreateGitRemoteFeatures().
Member Data Documentation
gitHubServiceFactory
readonly IGitHubServiceFactory Tgstation.Server.Host.Components.Repository.GitRemoteFeaturesFactory.gitHubServiceFactory private
The IGitHubServiceFactory for the GitRemoteFeaturesFactory.
Definition at line 16 of file GitRemoteFeaturesFactory.cs.
Referenced by Tgstation.Server.Host.Components.Repository.GitRemoteFeaturesFactory.CreateGitRemoteFeatures(), and Tgstation.Server.Host.Components.Repository.GitRemoteFeaturesFactory.GitRemoteFeaturesFactory().
logger
readonly ILogger<GitRemoteFeaturesFactory> Tgstation.Server.Host.Components.Repository.GitRemoteFeaturesFactory.logger private
The ILogger for the GitRemoteFeaturesFactory.
Definition at line 26 of file GitRemoteFeaturesFactory.cs.
Referenced by Tgstation.Server.Host.Components.Repository.GitRemoteFeaturesFactory.GitRemoteFeaturesFactory(), and Tgstation.Server.Host.Components.Repository.GitRemoteFeaturesFactory.ParseRemoteGitProviderFromOrigin().
loggerFactory
readonly ILoggerFactory Tgstation.Server.Host.Components.Repository.GitRemoteFeaturesFactory.loggerFactory private
The ILoggerFactory for the GitRemoteFeaturesFactory.
Definition at line 21 of file GitRemoteFeaturesFactory.cs.
Referenced by Tgstation.Server.Host.Components.Repository.GitRemoteFeaturesFactory.CreateGitRemoteFeatures(), and Tgstation.Server.Host.Components.Repository.GitRemoteFeaturesFactory.GitRemoteFeaturesFactory().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Repository/GitRemoteFeaturesFactory.cs