tgstation-server: Tgstation.Server.Host.System.WindowsNetworkPromptReaper Class Reference
Tgstation.Server.Host.System.WindowsNetworkPromptReaper Class Reference
Public Member Functions
WindowsNetworkPromptReaper (IAsyncDelayer asyncDelayer, ILogger< WindowsNetworkPromptReaper > logger)
Initializes a new instance of the WindowsNetworkPromptReaper class.
void Dispose ()
Task StartAsync (CancellationToken cancellationToken)
async Task StopAsync (CancellationToken cancellationToken)
void RegisterProcess (IProcess process)
Register a given process for network prompt reaping.
Parameters
process The IProcess to register.
void RegisterProcess (IProcess process)
Register a given process for network prompt reaping.
Private Member Functions
async Task Run (CancellationToken cancellationToken)
Main loop for the WindowsNetworkPromptReaper.
Static Private Member Functions
static bool EnumWindow (IntPtr hWnd, IntPtr lParam)
Callback for NativeMethods.EnumChildWindows(IntPtr, NativeMethods.EnumWindowProc, IntPtr).
static List< IntPtr > GetAllChildHandles (IntPtr mainWindow)
Get all the child windows handles of a given mainWindow .
Private Attributes
readonly IAsyncDelayer asyncDelayer
The IAsyncDelayer for the WindowsNetworkPromptReaper.
readonly ILogger< WindowsNetworkPromptReaper > logger
The ILogger for the WindowsNetworkPromptReaper.
readonly CancellationTokenSource cancellationTokenSource
The CancellationTokenSource for the WindowsNetworkPromptReaper.
readonly List< IProcess > registeredProcesses
The list of IProcesss registered.
Task runTask
The Task representing the lifetime of the WindowsNetworkPromptReaper.
Static Private Attributes
const int SendMessageCount = 5
Number of times to send the button click message. Should be at least 2 or it may fail to focus the window.
const int RecheckDelayMs = 250
Check for prompts each time this amount of milliseconds pass.
Detailed Description
Definition at line 18 of file WindowsNetworkPromptReaper.cs.
Constructor & Destructor Documentation
WindowsNetworkPromptReaper()
Tgstation.Server.Host.System.WindowsNetworkPromptReaper.WindowsNetworkPromptReaper (IAsyncDelayer asyncDelayer, ILogger< WindowsNetworkPromptReaper > logger)
Initializes a new instance of the WindowsNetworkPromptReaper class.
Parameters
asyncDelayer The value of asyncDelayer.
logger The value of logger.
Definition at line 102 of file WindowsNetworkPromptReaper.cs.
        {
            this.asyncDelayer = asyncDelayer ?? throw new ArgumentNullException(nameof(asyncDelayer));
            this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
            registeredProcesses = new List<IProcess>();
            cancellationTokenSource = new CancellationTokenSource();
        }
References Tgstation.Server.Host.System.WindowsNetworkPromptReaper.asyncDelayer, Tgstation.Server.Host.System.WindowsNetworkPromptReaper.cancellationTokenSource, Tgstation.Server.Host.System.WindowsNetworkPromptReaper.logger, and Tgstation.Server.Host.System.WindowsNetworkPromptReaper.registeredProcesses.
Member Function Documentation
Dispose()
void Tgstation.Server.Host.System.WindowsNetworkPromptReaper.Dispose ()
EnumWindow()
static bool Tgstation.Server.Host.System.WindowsNetworkPromptReaper.EnumWindow (IntPtr hWnd, IntPtr lParam) static private
Callback for NativeMethods.EnumChildWindows(IntPtr, NativeMethods.EnumWindowProc, IntPtr).
Parameters
hWnd The window handle.
lParam Unused.
Returns
true if enumeration should continue, false otherwise.
Definition at line 61 of file WindowsNetworkPromptReaper.cs.
        {
            var gcChildhandlesList = GCHandle.FromIntPtr(lParam);
            if (gcChildhandlesList.Target == null)
                return false;
            var childHandles = (List<IntPtr>)gcChildhandlesList.Target;
            childHandles.Add(hWnd);
            return true;
        }
Referenced by Tgstation.Server.Host.System.WindowsNetworkPromptReaper.GetAllChildHandles().
GetAllChildHandles()
static List< IntPtr > Tgstation.Server.Host.System.WindowsNetworkPromptReaper.GetAllChildHandles (IntPtr mainWindow) static private
Get all the child windows handles of a given mainWindow .
Parameters
mainWindow The handle of the window to enumerate.
Returns
A List<T> of all the child handles of mainWindow .
Definition at line 79 of file WindowsNetworkPromptReaper.cs.
        {
            var childHandles = new List<IntPtr>();
            var gcChildhandlesList = GCHandle.Alloc(childHandles);
            try
            {
                var pointerChildHandlesList = GCHandle.ToIntPtr(gcChildhandlesList);
                NativeMethods.EnumWindowProc childProc = new NativeMethods.EnumWindowProc(EnumWindow);
                NativeMethods.EnumChildWindows(mainWindow, childProc, pointerChildHandlesList);
            }
            finally
            {
                gcChildhandlesList.Free();
            }
            return childHandles;
        }
References Tgstation.Server.Host.NativeMethods.EnumChildWindows(), Tgstation.Server.Host.System.WindowsNetworkPromptReaper.EnumWindow(), and Tgstation.Server.Host.NativeMethods.EnumWindowProc().
Referenced by Tgstation.Server.Host.System.WindowsNetworkPromptReaper.Run().
RegisterProcess()
void Tgstation.Server.Host.System.WindowsNetworkPromptReaper.RegisterProcess (IProcess process)
Register a given process for network prompt reaping.
Parameters
process The IProcess to register.
Implements Tgstation.Server.Host.System.INetworkPromptReaper.
Definition at line 131 of file WindowsNetworkPromptReaper.cs.
        {
            if (process == null)
                throw new ArgumentNullException(nameof(process));
            lock (registeredProcesses)
            {
                if (registeredProcesses.Contains(process))
                    throw new InvalidOperationException("This process has already been registered for network prompt reaping!");
                logger.LogTrace("Registering process {0}...", process.Id);
                registeredProcesses.Add(process);
            }
            process.Lifetime.ContinueWith(
                x =>
            {
                logger.LogTrace("Unregistering process {0}...", process.Id);
                lock (registeredProcesses)
                    registeredProcesses.Remove(process);
            }, TaskScheduler.Current);
        }
References Tgstation.Server.Host.System.IProcess.Id, Tgstation.Server.Host.System.IProcessBase.Lifetime, Tgstation.Server.Host.System.WindowsNetworkPromptReaper.logger, and Tgstation.Server.Host.System.WindowsNetworkPromptReaper.registeredProcesses.
Run()
async Task Tgstation.Server.Host.System.WindowsNetworkPromptReaper.Run (CancellationToken cancellationToken) private
Main loop for the WindowsNetworkPromptReaper.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Definition at line 158 of file WindowsNetworkPromptReaper.cs.
        {
            logger.LogDebug("Starting network prompt reaper...");
            try
            {
                while (!cancellationToken.IsCancellationRequested)
                {
                    await asyncDelayer.Delay(TimeSpan.FromMilliseconds(RecheckDelayMs), cancellationToken);
                    IntPtr window;
                    int processId;
                    lock (registeredProcesses)
                    {
                        if (registeredProcesses.Count == 0)
                            continue;
                        window = NativeMethods.FindWindow(null, "Network Accessibility");
                        if (window == IntPtr.Zero)
                            continue;
                        // found a bitch
                        var threadId = NativeMethods.GetWindowThreadProcessId(window, out processId);
                        if (!registeredProcesses.Any(x => x.Id == processId))
                            continue; // not our bitch
                    }
                    logger.LogTrace("Identified \"Network Accessibility\" window in owned process {0}", processId);
                    var found = false;
                    foreach (var childHandle in GetAllChildHandles(window))
                    {
                        const int MaxLength = 10;
                        var stringBuilder = new StringBuilder(MaxLength + 1);
                        if (NativeMethods.GetWindowText(childHandle, stringBuilder, MaxLength) == 0)
{
                            logger.LogWarning(new Win32Exception(), "Error calling GetWindowText!");
                            continue;
                        }
                        var windowText = stringBuilder.ToString();
                        if (windowText == "Yes")
{
                            // smash_button_meme.jpg
                            logger.LogTrace("Sending \"Yes\" button clicks...");
                            for (var iteration = 0; iteration < SendMessageCount; ++iteration)
{
                                const int BM_CLICK = 0x00F5;
                                var result = NativeMethods.SendMessage(childHandle, BM_CLICK, IntPtr.Zero, IntPtr.Zero);
                            }
                            found = true;
                            break;
                        }
                    }
                    if (!found)
                        logger.LogDebug("Unable to find \"Yes\" button for \"Network Accessibility\" window in owned process {0}!", processId);
                }
            }
            catch (OperationCanceledException ex)
            {
                logger.LogTrace(ex, "Cancelled!");
            }
            finally
            {
                logger.LogDebug("Exiting network prompt reaper...");
            }
        }
References Tgstation.Server.Host.System.WindowsNetworkPromptReaper.asyncDelayer, Tgstation.Server.Host.Core.IAsyncDelayer.Delay(), Tgstation.Server.Host.NativeMethods.FindWindow(), Tgstation.Server.Host.System.WindowsNetworkPromptReaper.GetAllChildHandles(), Tgstation.Server.Host.NativeMethods.GetWindowText(), Tgstation.Server.Host.NativeMethods.GetWindowThreadProcessId(), Tgstation.Server.Host.System.WindowsNetworkPromptReaper.logger, Tgstation.Server.Host.System.WindowsNetworkPromptReaper.RecheckDelayMs, Tgstation.Server.Host.System.WindowsNetworkPromptReaper.registeredProcesses, Tgstation.Server.Host.NativeMethods.SendMessage(), and Tgstation.Server.Host.System.WindowsNetworkPromptReaper.SendMessageCount.
Referenced by Tgstation.Server.Host.System.WindowsNetworkPromptReaper.StartAsync().
StartAsync()
Task Tgstation.Server.Host.System.WindowsNetworkPromptReaper.StartAsync (CancellationToken cancellationToken)
Definition at line 115 of file WindowsNetworkPromptReaper.cs.
        {
            runTask = Run(cancellationTokenSource.Token);
            return Task.CompletedTask;
        }
References Tgstation.Server.Host.System.WindowsNetworkPromptReaper.cancellationTokenSource, Tgstation.Server.Host.System.WindowsNetworkPromptReaper.Run(), and Tgstation.Server.Host.System.WindowsNetworkPromptReaper.runTask.
StopAsync()
async Task Tgstation.Server.Host.System.WindowsNetworkPromptReaper.StopAsync (CancellationToken cancellationToken)
Definition at line 122 of file WindowsNetworkPromptReaper.cs.
        {
            logger.LogTrace("Stopping network prompt reaper...");
            cancellationTokenSource.Cancel();
            await runTask;
            registeredProcesses.Clear();
        }
References Tgstation.Server.Host.System.WindowsNetworkPromptReaper.cancellationTokenSource, Tgstation.Server.Host.System.WindowsNetworkPromptReaper.logger, Tgstation.Server.Host.System.WindowsNetworkPromptReaper.registeredProcesses, and Tgstation.Server.Host.System.WindowsNetworkPromptReaper.runTask.
Member Data Documentation
asyncDelayer
readonly IAsyncDelayer Tgstation.Server.Host.System.WindowsNetworkPromptReaper.asyncDelayer private
The IAsyncDelayer for the WindowsNetworkPromptReaper.
Definition at line 33 of file WindowsNetworkPromptReaper.cs.
Referenced by Tgstation.Server.Host.System.WindowsNetworkPromptReaper.Run(), and Tgstation.Server.Host.System.WindowsNetworkPromptReaper.WindowsNetworkPromptReaper().
cancellationTokenSource
readonly CancellationTokenSource Tgstation.Server.Host.System.WindowsNetworkPromptReaper.cancellationTokenSource private
The CancellationTokenSource for the WindowsNetworkPromptReaper.
Definition at line 43 of file WindowsNetworkPromptReaper.cs.
Referenced by Tgstation.Server.Host.System.WindowsNetworkPromptReaper.StartAsync(), Tgstation.Server.Host.System.WindowsNetworkPromptReaper.StopAsync(), and Tgstation.Server.Host.System.WindowsNetworkPromptReaper.WindowsNetworkPromptReaper().
logger
readonly ILogger<WindowsNetworkPromptReaper> Tgstation.Server.Host.System.WindowsNetworkPromptReaper.logger private
The ILogger for the WindowsNetworkPromptReaper.
Definition at line 38 of file WindowsNetworkPromptReaper.cs.
Referenced by Tgstation.Server.Host.System.WindowsNetworkPromptReaper.RegisterProcess(), Tgstation.Server.Host.System.WindowsNetworkPromptReaper.Run(), Tgstation.Server.Host.System.WindowsNetworkPromptReaper.StopAsync(), and Tgstation.Server.Host.System.WindowsNetworkPromptReaper.WindowsNetworkPromptReaper().
RecheckDelayMs
const int Tgstation.Server.Host.System.WindowsNetworkPromptReaper.RecheckDelayMs = 250 static private
Check for prompts each time this amount of milliseconds pass.
Definition at line 28 of file WindowsNetworkPromptReaper.cs.
Referenced by Tgstation.Server.Host.System.WindowsNetworkPromptReaper.Run().
registeredProcesses
readonly List<IProcess> Tgstation.Server.Host.System.WindowsNetworkPromptReaper.registeredProcesses private
The list of IProcesss registered.
Definition at line 48 of file WindowsNetworkPromptReaper.cs.
Referenced by Tgstation.Server.Host.System.WindowsNetworkPromptReaper.RegisterProcess(), Tgstation.Server.Host.System.WindowsNetworkPromptReaper.Run(), Tgstation.Server.Host.System.WindowsNetworkPromptReaper.StopAsync(), and Tgstation.Server.Host.System.WindowsNetworkPromptReaper.WindowsNetworkPromptReaper().
runTask
Task Tgstation.Server.Host.System.WindowsNetworkPromptReaper.runTask private
The Task representing the lifetime of the WindowsNetworkPromptReaper.
Definition at line 53 of file WindowsNetworkPromptReaper.cs.
Referenced by Tgstation.Server.Host.System.WindowsNetworkPromptReaper.StartAsync(), and Tgstation.Server.Host.System.WindowsNetworkPromptReaper.StopAsync().
SendMessageCount
const int Tgstation.Server.Host.System.WindowsNetworkPromptReaper.SendMessageCount = 5 static private
Number of times to send the button click message. Should be at least 2 or it may fail to focus the window.
Definition at line 23 of file WindowsNetworkPromptReaper.cs.
Referenced by Tgstation.Server.Host.System.WindowsNetworkPromptReaper.Run().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/System/WindowsNetworkPromptReaper.cs