tgstation-server: TGServerService.DeprecatedInstanceConfig Class Reference
TGServerService.DeprecatedInstanceConfig Class Reference
Used to migrate old config settings
Public Member Functions
DeprecatedInstanceConfig ()
Construct a DeprecatedInstanceConfig. Used by the deserializer
DeprecatedInstanceConfig (string path)
Construct a DeprecatedInstanceConfig for a ServerInstance at path
void MigrateToCurrentVersion ()
Migrates the DeprecatedInstanceConfig from Version to MigrateToCurrentVersion
Public Member Functions inherited from TGServerService.InstanceConfig
InstanceConfig (string path)
Construct a InstanceConfig for a ServerInstance at path
void Save ()
Saves the IInstanceConfig to it's ServerInstance Directory
Static Public Member Functions
static IInstanceConfig CreateFromNETSettings ()
Convert the settings version 6 .NET settings file to a config json
Static Public Member Functions inherited from TGServerService.InstanceConfig
static IInstanceConfig Load (string path)
Loads and migrates an IInstanceConfig from a ServerInstance at path
Private Member Functions
void Migrate ()
Migrates the DeprecatedInstanceConfig from Version to Version + 1
Static Private Member Functions
static T LoadPreviousNetPropertyOrDefault< T > (string property, T defaultValue)
Loads a previous .NET config property and returns it or some defaultValue if it wasn't set
Private Attributes
const string DefaultInstallationPath = "C:\\tgstation-server-3"
The default ServerInstance directory
Additional Inherited Members
Public Attributes inherited from TGServerService.InstanceConfig
const string JSONFilename = "Instance.json"
The name the file is saved as in the Directory
Protected Attributes inherited from TGServerService.InstanceConfig
const ulong CurrentVersion = 0
The current version of the config
Properties inherited from TGServerService.InstanceConfig
string Directory [get, private set]
ulong Version [get, protected set]
string Name = CurrentVersion [get, set]
bool Enabled = "TG Station Server" [get, set]
string ProjectName = true [get, set]
ushort Port = "tgstation" [get, set]
DreamDaemonSecurity Security = 1337 [get, set]
bool Autostart = DreamDaemonSecurity.Trusted [get, set]
bool Webclient = false [get, set]
string CommitterName = false [get, set]
string CommitterEmail = "tgstation-server" [get, set]
string ChatProviderData = "tgstation-server@tgstation13.org" [get, set]
string ChatProviderEntropy = ServerInstance.UninitializedString [get, set]
bool ReattachRequired [get, set]
int ReattachProcessID = false [get, set]
ushort ReattachPort [get, set]
string ReattachCommsKey [get, set]
string ReattachAPIVersion [get, set]
string AuthorizedUserGroupSID [get, set]
ulong AutoUpdateInterval = null [get, set]
bool PushTestmergeCommits = 0 [get, set]
Properties inherited from TGServerService.IInstanceConfig
string Directory [get]
The ServerInstance directory this IInstanceConfig is for
ulong Version [get]
Actual version of the IInstanceConfig. Migrated up via DeprecatedInstanceConfig
string Name [get, set]
The name of the ServerInstance
bool Enabled [get, set]
If the ServerInstance is active
string ProjectName [get, set]
The name of the .dme/.dmb the ServerInstance uses
ushort Port [get, set]
The port the ServerInstance runs on
DreamDaemonSecurity Security [get, set]
The DreamDaemonSecurity level for the ServerInstance
bool Autostart [get, set]
Whether or not the ServerInstance should immediately start DreamDaemon when activated
bool Webclient [get, set]
Whether or not DreamDaemon allows connections from webclients
string CommitterName [get, set]
Author and committer name for synchronize commits
string CommitterEmail [get, set]
Author and committer e-mail for synchronize commits
string ChatProviderData [get, set]
Encrypted serialized ChatSetupInfos
string ChatProviderEntropy [get, set]
Entropy for ChatProviderData
bool ReattachRequired [get, set]
If the ServerInstance should reattach to a running DreamDaemon System.Diagnostics.Process
int ReattachProcessID [get, set]
The System.Diagnostics.Process.Id of the runnning DreamDaemon System.Diagnostics.Process
ushort ReattachPort [get, set]
The port the runnning DreamDaemon System.Diagnostics.Process was launched on
string ReattachCommsKey [get, set]
The serviceCommsKey the runnning DreamDaemon System.Diagnostics.Process was launched on
string ReattachAPIVersion [get, set]
The API version of the runnning DreamDaemon System.Diagnostics.Process
string AuthorizedUserGroupSID [get, set]
The user group allowed to use the ServerInstance
ulong AutoUpdateInterval [get, set]
The auto update interval for the ServerInstance
bool PushTestmergeCommits [get, set]
Whether or not testmerge commits are published to a temporary remote branch
Detailed Description
Used to migrate old config settings
Definition at line 9 of file DeprecatedInstanceConfig.cs.
Constructor & Destructor Documentation
TGServerService.DeprecatedInstanceConfig.DeprecatedInstanceConfig ()
Construct a DeprecatedInstanceConfig. Used by the deserializer
Definition at line 94 of file DeprecatedInstanceConfig.cs.
Referenced by TGServerService.DeprecatedInstanceConfig.CreateFromNETSettings().
 : base(DefaultInstallationPath) { }
TGServerService.DeprecatedInstanceConfig.DeprecatedInstanceConfig (string path)
Construct a DeprecatedInstanceConfig for a ServerInstance at path
Parameters
path The path to the ServerInstance
Definition at line 100 of file DeprecatedInstanceConfig.cs.
 : base(path) { }
Member Function Documentation
static IInstanceConfig TGServerService.DeprecatedInstanceConfig.CreateFromNETSettings () static
Convert the settings version 6 .NET settings file to a config json
Returns
An IInstanceConfig based off the old .NET setting file
Definition at line 20 of file DeprecatedInstanceConfig.cs.
References TGServerService.InstanceConfig.AutoUpdateInterval, TGServerService.InstanceConfig.ChatProviderData, TGServerService.InstanceConfig.ChatProviderEntropy, TGServerService.InstanceConfig.CommitterEmail, TGServerService.InstanceConfig.CommitterName, TGServerService.DeprecatedInstanceConfig.DeprecatedInstanceConfig(), TGServerService.Program.NormalizePath(), TGServerService.InstanceConfig.ProjectName, TGServerService.InstanceConfig.ReattachAPIVersion, TGServerService.InstanceConfig.ReattachCommsKey, and TGServerService.InstanceConfig.ReattachPort.
Referenced by TGServerService.Service.MigrateSettings().
         {
             var Config = Properties.Settings.Default;
             var result = new DeprecatedInstanceConfig(Program.NormalizePath(LoadPreviousNetPropertyOrDefault("ServerDirectory", "C:\\tgstation-server-3")));
             // using nameof for sanity where possible
             result.ProjectName = LoadPreviousNetPropertyOrDefault(nameof(ProjectName), result.ProjectName);
             result.Port = LoadPreviousNetPropertyOrDefault("ServerPort", result.Port);
             result.CommitterName = LoadPreviousNetPropertyOrDefault(nameof(CommitterName), result.CommitterName);
             result.CommitterEmail = LoadPreviousNetPropertyOrDefault(nameof(CommitterEmail), result.CommitterEmail);
             result.Security = LoadPreviousNetPropertyOrDefault("ServerSecurity", result.Security);
             result.Autostart = LoadPreviousNetPropertyOrDefault("DDAutoStart", result.Autostart);
             result.ChatProviderData = LoadPreviousNetPropertyOrDefault(nameof(ChatProviderData), result.ChatProviderData);
             result.ChatProviderEntropy = LoadPreviousNetPropertyOrDefault(nameof(ChatProviderEntropy), result.ChatProviderEntropy);
             result.ReattachRequired = LoadPreviousNetPropertyOrDefault("ReattachToDD", result.ReattachRequired);
             result.ReattachProcessID = LoadPreviousNetPropertyOrDefault("ReattachPID", result.ReattachProcessID);
             result.ReattachPort = LoadPreviousNetPropertyOrDefault(nameof(ReattachPort), result.ReattachPort);
             result.ReattachCommsKey = LoadPreviousNetPropertyOrDefault(nameof(ReattachCommsKey), result.ReattachCommsKey);
             result.ReattachAPIVersion = LoadPreviousNetPropertyOrDefault(nameof(ReattachAPIVersion), result.ReattachAPIVersion);
             result.AutoUpdateInterval = LoadPreviousNetPropertyOrDefault(nameof(AutoUpdateInterval), result.AutoUpdateInterval);
             result.AuthorizedUserGroupSID = LoadPreviousNetPropertyOrDefault("AuthorizedGroupSID", result.AuthorizedUserGroupSID);
             result.MigrateToCurrentVersion();
             return result;
         }
static T TGServerService.DeprecatedInstanceConfig.LoadPreviousNetPropertyOrDefault< T > (string property, T defaultValue) static private
Loads a previous .NET config property and returns it or some defaultValue if it wasn't set
Template Parameters
T The type of the property
Parameters
property The config key of the property
defaultValue The default value of the property
Returns
The property if it exists, otherwise the defaultValue
Definition at line 51 of file DeprecatedInstanceConfig.cs.
         {
             //try it the simple way first
             try
             {
                 var result = (T)Properties.Settings.Default.GetPreviousVersion(property);
                 return result == null ? defaultValue : result;
             }
             catch
             {
                 try
                 {
                     //.NET is fucking stupid
                     //If we don't have the correct property in our *CURRENT* .settings file it will automatically throw an exception when it tries to load it
                     //Which means we can never fucking delete config settings
                     //Which is fucking retarded
                     //This hooks into the settings provider and forces it to load it anyway
                     var Config = Properties.Settings.Default;
                     var Provider = Config.Properties[nameof(Config.SettingsVersion)].Provider;  //nameof for sanity
                     var sp = new SettingsProperty(property)
                     {
                         PropertyType = typeof(T),
                         DefaultValue = defaultValue,
                         Provider = Provider
                     };
                     var ProviderInterface = Provider as IApplicationSettingsProvider;
                     var result = ProviderInterface.GetPreviousVersion(Config.Context, sp);
                     if (result != null && result.PropertyValue != null)
                         return (T)result.PropertyValue;
                 }
                 catch { }
                 //f u c k   i t
                 return defaultValue;
             }
         }
void TGServerService.DeprecatedInstanceConfig.Migrate () private
Migrates the DeprecatedInstanceConfig from Version to Version + 1
Definition at line 114 of file DeprecatedInstanceConfig.cs.
Referenced by TGServerService.DeprecatedInstanceConfig.MigrateToCurrentVersion().
         {
             //Not needed so far
         }
void TGServerService.DeprecatedInstanceConfig.MigrateToCurrentVersion ()
Migrates the DeprecatedInstanceConfig from Version to MigrateToCurrentVersion
Definition at line 105 of file DeprecatedInstanceConfig.cs.
References TGServerService.InstanceConfig.CurrentVersion, TGServerService.DeprecatedInstanceConfig.Migrate(), and TGServerService.InstanceConfig.Version.
         {
             for (; Version < CurrentVersion; ++Version)
                 Migrate();
         }
Member Data Documentation
const string TGServerService.DeprecatedInstanceConfig.DefaultInstallationPath = "C:\\tgstation-server-3" private
The default ServerInstance directory
Definition at line 14 of file DeprecatedInstanceConfig.cs.
The documentation for this class was generated from the following file:
TGServerService/DeprecatedInstanceConfig.cs