tgstation-server: Tgstation.Server.Host.Controllers.ChatController Class Reference
Tgstation.Server.Host.Controllers.ChatController Class Reference
ApiController for managing ChatBots.
Public Member Functions
ChatController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ILogger< ChatController > logger, IInstanceManager instanceManager, IApiHeadersProvider apiHeaders)
Initializes a new instance of the ChatController class.
async ValueTask< IActionResult > Create ([FromBody] ChatBotCreateRequest model, CancellationToken cancellationToken)
Create a new chat bot model .
async ValueTask< IActionResult > Delete (long id, CancellationToken cancellationToken)
Delete a ChatBot.
ValueTask< IActionResult > List ([FromQuery] int? page, [FromQuery] int? pageSize, CancellationToken cancellationToken)
List ChatBots.
async ValueTask< IActionResult > GetId (long id, CancellationToken cancellationToken)
Get a specific ChatBot.
async ValueTask< IActionResult > Update ([FromBody] ChatBotUpdateRequest model, CancellationToken cancellationToken)
Updates a chat bot model .
Public Member Functions inherited from Tgstation.Server.Host.Controllers.ApiControllerBase
sealed override async Task OnActionExecutionAsync (ActionExecutingContext context, ActionExecutionDelegate next)
Private Member Functions
BadRequestObjectResult? StandardModelChecks (ChatBotApiBase model, bool forCreation)
Perform some basic validation of a given model .
Static Private Member Functions
static Models.ChatChannel ConvertApiChatChannel (Api.Models.ChatChannel api, ChatProvider chatProvider)
Converts api to a ChatChannel.
Additional Inherited Members
Protected Member Functions inherited from Tgstation.Server.Host.Controllers.InstanceRequiredController
InstanceRequiredController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ILogger< InstanceRequiredController > logger, IInstanceManager instanceManager, IApiHeadersProvider apiHeaders)
Initializes a new instance of the InstanceRequiredController class.
Protected Member Functions inherited from Tgstation.Server.Host.Controllers.ComponentInterfacingController
ComponentInterfacingController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ILogger< ComponentInterfacingController > logger, IInstanceManager instanceManager, IApiHeadersProvider apiHeaders, bool useInstanceRequestHeader)
Initializes a new instance of the ComponentInterfacingController class.
override async ValueTask< IActionResult?> ValidateRequest (CancellationToken cancellationToken)
Performs validation a request.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in an appropriate IActionResult on validation failure, null otherwise.
bool ValidateInstanceOnlineStatus (Api.Models.Instance metadata)
Corrects discrepencies between the Api.Models.Instance.Online status of IInstances in the database vs the service.
async ValueTask< IActionResult?> WithComponentInstanceNullable (Func< IInstanceCore, ValueTask< IActionResult?> > action, Models.Instance? instance=null)
Run a given action with the relevant IInstance.
async ValueTask< IActionResult > WithComponentInstance (Func< IInstanceCore, ValueTask< IActionResult > > action, Models.Instance? instance=null)
Run a given action with the relevant IInstance.
Protected Member Functions inherited from Tgstation.Server.Host.Controllers.ApiController
ApiController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, IApiHeadersProvider apiHeadersProvider, ILogger< ApiController > logger, bool requireHeaders)
Initializes a new instance of the ApiController class.
override async ValueTask< IActionResult?> HookExecuteAction (Func< Task > executeAction, CancellationToken cancellationToken)
Hook for executing a request.
Parameters
executeAction A Func<TResult> that should be invoked and its response awaited to continue normal execution of the request. Should NOT be called if this method returns a non-null value.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in an IActionResult that, if not null, is executed.
new NotFoundObjectResult NotFound ()
Generic 404 response.
new ObjectResult Unauthorized ()
Generic 401 response.
ObjectResult RequiresPosixSystemIdentity (NotImplementedException ex)
Generic 501 response.
StatusCodeResult StatusCode (HttpStatusCode statusCode)
Strongly type calls to ControllerBase.StatusCode(int).
ObjectResult Created (object payload)
Generic 201 response with a given payload .
ObjectResult RateLimit (RateLimitExceededException rateLimitException)
429 response for a given rateLimitException .
virtual ValueTask< IActionResult?> ValidateRequest (CancellationToken cancellationToken)
Performs validation a request.
IActionResult HeadersIssue (HeadersException headersException)
Response for missing/Invalid headers.
ValueTask< IActionResult > Paginated< TModel > (Func< ValueTask< PaginatableResult< TModel > > > queryGenerator, Func< TModel, ValueTask >? resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
ValueTask< IActionResult > Paginated< TModel, TApiModel > (Func< ValueTask< PaginatableResult< TModel > > > queryGenerator, Func< TApiModel, ValueTask >? resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
virtual async ValueTask< IActionResult?> HookExecuteAction (Func< Task > executeAction, CancellationToken cancellationToken)
Hook for executing a request.
Properties inherited from Tgstation.Server.Host.Controllers.InstanceRequiredController
new Models.Instance Instance [get]
The ApiController.Instance.
Models.InstancePermissionSet InstancePermissionSet [get]
The Models.InstancePermissionSet for the request.
Properties inherited from Tgstation.Server.Host.Controllers.ComponentInterfacingController
IInstanceOperations InstanceOperations [get]
Access the IInstanceOperations instance.
Properties inherited from Tgstation.Server.Host.Controllers.ApiController
ApiHeaders? ApiHeaders [get]
The Api.ApiHeaders for the operation.
IApiHeadersProvider ApiHeadersProvider [get]
The IApiHeadersProvider containing value of ApiHeaders.
IDatabaseContext DatabaseContext [get]
The IDatabaseContext for the operation.
IAuthenticationContext AuthenticationContext [get]
The IAuthenticationContext for the operation.
ILogger< ApiController > Logger [get]
The ILogger for the ApiController.
Models.? Instance Instance [get]
The Instance for the operation.
Detailed Description
ApiController for managing ChatBots.
Definition at line 36 of file ChatController.cs.
Constructor & Destructor Documentation
ChatController()
Tgstation.Server.Host.Controllers.ChatController.ChatController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ILogger< ChatController > logger, IInstanceManager instanceManager, IApiHeadersProvider apiHeaders)
Initializes a new instance of the ChatController class.
Parameters
databaseContext The IDatabaseContext for the InstanceRequiredController.
authenticationContext The IAuthenticationContext for the InstanceRequiredController.
logger The ILogger for the InstanceRequiredController.
instanceManager The IInstanceManager for the InstanceRequiredController.
apiHeaders The IApiHeadersProvider for the InstanceRequiredController.
Definition at line 46 of file ChatController.cs.
            : base(
                  databaseContext,
                  authenticationContext,
                  logger,
                  instanceManager,
                  apiHeaders)
        {
        }
Member Function Documentation
ConvertApiChatChannel()
static Models.ChatChannel Tgstation.Server.Host.Controllers.ChatController.ConvertApiChatChannel (Api.Models.ChatChannel api, ChatProvider chatProvider) static private
Converts api to a ChatChannel.
Parameters
api The Api.Models.ChatChannel.
chatProvider The channel's ChatProvider.
Returns
A ChatChannel based on api .
Definition at line 67 of file ChatController.cs.
        {
            var result = new Models.ChatChannel
            {
                IsAdminChannel = api.IsAdminChannel ?? false,
                IsWatchdogChannel = api.IsWatchdogChannel ?? false,
                IsUpdatesChannel = api.IsUpdatesChannel ?? false,
                IsSystemChannel = api.IsSystemChannel ?? false,
                Tag = api.Tag,
            };
            if (api.ChannelData != null)
            {
                switch (chatProvider)
                {
                    case ChatProvider.Discord:
                        result.DiscordChannelId = ulong.Parse(api.ChannelData, CultureInfo.InvariantCulture);
                        break;
                    case ChatProvider.Irc:
                        result.IrcChannel = api.ChannelData;
                        break;
                    default:
                        throw new InvalidOperationException($"Invalid chat provider: {chatProvider}");
                }
            }
            return result;
        }
References Tgstation.Server.Api.Models.Internal.ChatChannelBase.Tag.
Referenced by Tgstation.Server.Host.Controllers.ChatController.Create(), and Tgstation.Server.Host.Controllers.ChatController.Update().
Create()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.ChatController.Create ([FromBody] ChatBotCreateRequest model, CancellationToken cancellationToken)
Create a new chat bot model .
Parameters
model The ChatBotCreateRequest.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult for the operation.
<response code="201">Created ChatBot successfully.</response>
Definition at line 106 of file ChatController.cs.
        {
            ArgumentNullException.ThrowIfNull(model);
            var earlyOut = StandardModelChecks(model, true);
            if (earlyOut != null)
                return earlyOut;
            var countOfExistingBotsInInstance = await DatabaseContext
                .ChatBots
                .AsQueryable()
                .Where(x => x.InstanceId == Instance.Id)
                .CountAsync(cancellationToken);
            if (countOfExistingBotsInInstance >= Instance.ChatBotLimit!.Value)
                return Conflict(new ErrorMessageResponse(ErrorCode.ChatBotMax));
            model.Enabled ??= false;
            model.ReconnectionInterval ??= 1;
            // try to update das db first
            var newChannels = model.Channels?.Select(x => ConvertApiChatChannel(x, model.Provider!.Value)).ToList() ?? new List<Models.ChatChannel>(); // important that this isn't null
            var dbModel = new ChatBot(newChannels)
            {
                Name = model.Name,
                ConnectionString = model.ConnectionString,
                Enabled = model.Enabled,
                InstanceId = Instance.Id!.Value,
                Provider = model.Provider,
                ReconnectionInterval = model.ReconnectionInterval,
                ChannelLimit = model.ChannelLimit,
            };
            DatabaseContext.ChatBots.Add(dbModel);
            await DatabaseContext.Save(cancellationToken);
            return await WithComponentInstanceNullable(
                async instance =>
                {
                    try
                    {
                        // try to create it
                        await instance.Chat.ChangeSettings(dbModel, cancellationToken);
                        if (dbModel.Channels.Count > 0)
                            await instance.Chat.ChangeChannels(dbModel.Id!.Value, dbModel.Channels, cancellationToken);
                    }
                    catch
                    {
                        // undo the add
                        DatabaseContext.ChatBots.Remove(dbModel);
                        // DCTx2: Operations must always run
                        await DatabaseContext.Save(default);
                        await instance.Chat.DeleteConnection(dbModel.Id!.Value, default);
                        throw;
                    }
                    return null;
                })
                ?? this.StatusCode(HttpStatusCode.Created, dbModel.ToApi());
        }
References Tgstation.Server.Api.Models.Instance.ChatBotLimit, Tgstation.Server.Host.Database.DatabaseContext.ChatBots, Tgstation.Server.Host.Controllers.ChatController.ConvertApiChatChannel(), Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Host.Controllers.ChatController.List(), Tgstation.Server.Api.Models.NamedEntity.Name, Tgstation.Server.Host.Database.DatabaseContext.Save(), Tgstation.Server.Host.Controllers.ChatController.StandardModelChecks(), Tgstation.Server.Host.Controllers.ApiController.StatusCode(), and Tgstation.Server.Host.Controllers.ComponentInterfacingController.WithComponentInstanceNullable().
Delete()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.ChatController.Delete (long id, CancellationToken cancellationToken)
Delete a ChatBot.
Parameters
id The EntityId.Id to delete.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult for the operation.
<response code="204">Chat bot deleted or does not exist.</response>
References Tgstation.Server.Host.Database.DatabaseContext.ChatBots.
GetId()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.ChatController.GetId (long id, CancellationToken cancellationToken)
Get a specific ChatBot.
Parameters
id The EntityId.Id to retrieve.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult for the operation.
<response code="200">Retrieved ChatBot successfully.</response> <response code="410">The ChatBot with the given ID does not exist in this instance.</response>
Definition at line 243 of file ChatController.cs.
        {
            var query = DatabaseContext.ChatBots
                .AsQueryable()
                .Where(x => x.Id == id && x.InstanceId == Instance.Id)
                .Include(x => x.Channels);
            var results = await query.FirstOrDefaultAsync(cancellationToken);
            if (results == default)
                return this.Gone();
            var connectionStrings = (AuthenticationContext.GetRight(RightsType.ChatBots) & (ulong)ChatBotRights.ReadConnectionString) != 0;
            if (!connectionStrings)
                results.ConnectionString = null;
            return Json(results.ToApi());
        }
References Tgstation.Server.Host.Security.AuthenticationContext.GetRight(), and Tgstation.Server.Api.Models.EntityId.Id.
List()
ValueTask< IActionResult > Tgstation.Server.Host.Controllers.ChatController.List ([FromQuery] int? page, [FromQuery] int? pageSize, CancellationToken cancellationToken)
List ChatBots.
Parameters
page The current page.
pageSize The page size.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult for the operation.
<response code="200">Listed chat bots successfully.</response>
Definition at line 207 of file ChatController.cs.
        {
            var connectionStrings = (AuthenticationContext.GetRight(RightsType.ChatBots) & (ulong)ChatBotRights.ReadConnectionString) != 0;
            return Paginated<ChatBot, ChatBotResponse>(
                () => ValueTask.FromResult(
                    new PaginatableResult<ChatBot>(
                        DatabaseContext
                            .ChatBots
                            .AsQueryable()
                            .Where(x => x.InstanceId == Instance.Id)
                            .Include(x => x.Channels)
                            .OrderBy(x => x.Id))),
                chatBot =>
                {
                    if (!connectionStrings)
                        chatBot.ConnectionString = null;
                    return ValueTask.CompletedTask;
                },
                page,
                pageSize,
                cancellationToken);
        }
References Tgstation.Server.Host.Database.DatabaseContext.ChatBots, Tgstation.Server.Host.Security.AuthenticationContext.GetRight(), and Tgstation.Server.Api.Models.EntityId.Id.
Referenced by Tgstation.Server.Host.Controllers.ChatController.Create().
StandardModelChecks()
BadRequestObjectResult? Tgstation.Server.Host.Controllers.ChatController.StandardModelChecks (ChatBotApiBase model, bool forCreation) private
Perform some basic validation of a given model .
Parameters
model The ChatBotApiBase to validate.
forCreation If the model is being created.
Returns
An BadRequestObjectResult to respond with or null.
Definition at line 384 of file ChatController.cs.
        {
            if (model.ReconnectionInterval == 0)
                throw new InvalidOperationException("RecconnectionInterval cannot be zero!");
            if (forCreation && !model.Provider.HasValue)
                return BadRequest(new ErrorMessageResponse(ErrorCode.ChatBotProviderMissing));
            if (model.Name != null && String.IsNullOrWhiteSpace(model.Name))
                return BadRequest(new ErrorMessageResponse(ErrorCode.ChatBotWhitespaceName));
            if (model.ConnectionString != null && String.IsNullOrWhiteSpace(model.ConnectionString))
                return BadRequest(new ErrorMessageResponse(ErrorCode.ChatBotWhitespaceConnectionString));
            if (!model.ValidateProviderChannelTypes())
                return BadRequest(new ErrorMessageResponse(ErrorCode.ChatBotWrongChannelType));
            var defaultMaxChannels = (ulong)Math.Max(ChatBot.DefaultChannelLimit, model.Channels?.Count ?? 0);
            if (defaultMaxChannels > UInt16.MaxValue)
                return BadRequest(new ErrorMessageResponse(ErrorCode.ChatBotMaxChannels));
            if (forCreation)
                model.ChannelLimit ??= (ushort)defaultMaxChannels;
            return null;
        }
References Tgstation.Server.Api.Models.Internal.ChatBotApiBase.Channels, Tgstation.Server.Api.Models.Internal.ChatBotSettings.ConnectionString, Tgstation.Server.Host.Models.ChatBot.DefaultChannelLimit, Tgstation.Server.Api.Models.NamedEntity.Name, Tgstation.Server.Api.Models.Internal.ChatBotSettings.Provider, Tgstation.Server.Api.Models.Internal.ChatBotSettings.ReconnectionInterval, and Tgstation.Server.Api.Models.Internal.ChatBotApiBase.ValidateProviderChannelTypes().
Referenced by Tgstation.Server.Host.Controllers.ChatController.Create(), and Tgstation.Server.Host.Controllers.ChatController.Update().
Update()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.ChatController.Update ([FromBody] ChatBotUpdateRequest model, CancellationToken cancellationToken)
Updates a chat bot model .
Parameters
model The ChatBotUpdateRequest.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult for the operation.
<response code="200">Update applied successfully.</response> <response code="204">Update applied successfully. ChatBot not returned based on user permissions.</response> <response code="410">The ChatBot with the given ID does not exist in this instance.</response>
Definition at line 277 of file ChatController.cs.
        {
            ArgumentNullException.ThrowIfNull(model);
            IActionResult? earlyOut = StandardModelChecks(model, false);
            if (earlyOut != null)
                return earlyOut;
            var query = DatabaseContext
                .ChatBots
                .AsQueryable()
                .Where(x => x.InstanceId == Instance.Id && x.Id == model.Id)
                .Include(x => x.Channels);
            var current = await query.FirstOrDefaultAsync(cancellationToken);
            if (current == default)
                return this.Gone();
            if ((model.Channels?.Count ?? current.Channels!.Count) > (model.ChannelLimit ?? current.ChannelLimit!.Value))
            {
                // 400 or 409 depends on if the client sent both
                var errorMessage = new ErrorMessageResponse(ErrorCode.ChatBotMaxChannels);
                if (model.Channels != null && model.ChannelLimit.HasValue)
                    return BadRequest(errorMessage);
                return Conflict(errorMessage);
            }
            var userRights = (ChatBotRights)AuthenticationContext.GetRight(RightsType.ChatBots);
            bool anySettingsModified = false;
            bool CheckModified<T>(Expression<Func<ChatBotSettings, T>> expression, ChatBotRights requiredRight)
            {
                var memberSelectorExpression = (MemberExpression)expression.Body;
                var property = (PropertyInfo)memberSelectorExpression.Member;
                var newVal = property.GetValue(model);
                if (newVal == null)
                    return false;
                if (!userRights.HasFlag(requiredRight) && property.GetValue(current) != newVal)
                    return true;
                property.SetValue(current, newVal);
                anySettingsModified = true;
                return false;
            }
            var oldProvider = current.Provider;
            if (CheckModified(x => x.ConnectionString, ChatBotRights.WriteConnectionString)
                || CheckModified(x => x.Enabled, ChatBotRights.WriteEnabled)
                || CheckModified(x => x.Name, ChatBotRights.WriteName)
                || CheckModified(x => x.Provider, ChatBotRights.WriteProvider)
                || CheckModified(x => x.ReconnectionInterval, ChatBotRights.WriteReconnectionInterval)
                || CheckModified(x => x.ChannelLimit, ChatBotRights.WriteChannelLimit)
                || (model.Channels != null && !userRights.HasFlag(ChatBotRights.WriteChannels)))
                return Forbid();
            var hasChannels = model.Channels != null;
            if (hasChannels || (model.Provider.HasValue && model.Provider != oldProvider))
            {
                DatabaseContext.ChatChannels.RemoveRange(current.Channels!);
                if (hasChannels)
                {
                    var dbChannels = model.Channels!.Select(x => ConvertApiChatChannel(x, model.Provider ?? current.Provider!.Value)).ToList();
                    DatabaseContext.ChatChannels.AddRange(dbChannels);
                    current.Channels = dbChannels;
                }
                else
                    current.Channels!.Clear();
            }
            await DatabaseContext.Save(cancellationToken);
            earlyOut = await WithComponentInstanceNullable(
                async instance =>
                {
                    var chat = instance.Chat;
                    if (anySettingsModified)
                        await chat.ChangeSettings(current, cancellationToken); // have to rebuild the thing first
                    if ((model.Channels != null || anySettingsModified) && current.Enabled!.Value)
                        await chat.ChangeChannels(current.Id!.Value, current.Channels, cancellationToken);
                    return null;
                });
            if (earlyOut != null)
                return earlyOut;
            if (userRights.HasFlag(ChatBotRights.Read))
            {
                if (!userRights.HasFlag(ChatBotRights.ReadConnectionString))
                    current.ConnectionString = null;
                return Json(current.ToApi());
            }
            return NoContent();
        }
References Tgstation.Server.Host.Database.DatabaseContext.ChatBots, Tgstation.Server.Host.Database.DatabaseContext.ChatChannels, Tgstation.Server.Host.Controllers.ChatController.ConvertApiChatChannel(), Tgstation.Server.Host.Security.AuthenticationContext.GetRight(), Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Host.Database.DatabaseContext.Save(), Tgstation.Server.Host.Controllers.ChatController.StandardModelChecks(), and Tgstation.Server.Host.Controllers.ComponentInterfacingController.WithComponentInstanceNullable().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Controllers/ChatController.cs