tgstation-server: Common Class Reference
Common Class Reference
Static Public Member Functions
static void Log (string format, params object[] args)
static string CalculateChecksum (string filename)
static Assembly ReadExistingAssembly (AssemblyName name)
static Assembly ReadFromDiskCache (string tempBasePath, AssemblyName requestedAssemblyName)
static Assembly ReadFromEmbeddedResources (Dictionary< string, string > assemblyNames, Dictionary< string, string > symbolNames, AssemblyName requestedAssemblyName)
static void PreloadUnmanagedLibraries (string hash, string tempBasePath, IEnumerable< string > libs, Dictionary< string, string > checksums)
static void Log (string format, params object[] args)
static string CalculateChecksum (string filename)
static Assembly ReadExistingAssembly (AssemblyName name)
static Assembly ReadFromDiskCache (string tempBasePath, AssemblyName requestedAssemblyName)
static Assembly ReadFromEmbeddedResources (Dictionary< string, string > assemblyNames, Dictionary< string, string > symbolNames, AssemblyName requestedAssemblyName)
static void PreloadUnmanagedLibraries (string hash, string tempBasePath, IEnumerable< string > libs, Dictionary< string, string > checksums)
Private Member Functions
static bool MoveFileEx (string lpExistingFileName, string lpNewFileName, int dwFlags)
static IntPtr LoadLibrary (string dllToLoad)
static bool SetDllDirectory (string lpPathName)
static bool MoveFileEx (string lpExistingFileName, string lpNewFileName, int dwFlags)
static IntPtr LoadLibrary (string dllToLoad)
static bool SetDllDirectory (string lpPathName)
Static Private Member Functions
static void CopyTo (Stream source, Stream destination)
static void CreateDirectory (string tempBasePath)
static byte[] ReadStream (Stream stream)
static string CultureToString (CultureInfo culture)
static Stream LoadStream (Dictionary< string, string > resourceNames, string name)
static Stream LoadStream (string fullname)
static void InternalPreloadUnmanagedLibraries (string tempBasePath, IEnumerable< string > libs, Dictionary< string, string > checksums)
static string ResourceNameToPath (string lib)
static void CopyTo (Stream source, Stream destination)
static void CreateDirectory (string tempBasePath)
static byte[] ReadStream (Stream stream)
static string CultureToString (CultureInfo culture)
static Stream LoadStream (Dictionary< string, string > resourceNames, string name)
static Stream LoadStream (string fullname)
static void InternalPreloadUnmanagedLibraries (string tempBasePath, IEnumerable< string > libs, Dictionary< string, string > checksums)
static string ResourceNameToPath (string lib)
Private Attributes
const int DelayUntilReboot = 4
Detailed Description
Definition at line 15 of file Common.cs.
Member Function Documentation
static string Common.CalculateChecksum (string filename) static
Definition at line 61 of file Common.cs.
Referenced by InternalPreloadUnmanagedLibraries().
     {
         using (var fs = new FileStream(filename, FileMode.Open, FileAccess.Read, FileShare.ReadWrite | FileShare.Delete))
         using (var bs = new BufferedStream(fs))
         using (var sha1 = new SHA1CryptoServiceProvider())
         {
             var hash = sha1.ComputeHash(bs);
             var formatted = new StringBuilder(2 * hash.Length);
             foreach (var b in hash)
             {
                 formatted.AppendFormat("{0:X2}", b);
             }
             return formatted.ToString();
         }
     }
static string Common.CalculateChecksum (string filename) static
Definition at line 61 of file Common.cs.
     {
         using (var fs = new FileStream(filename, FileMode.Open, FileAccess.Read, FileShare.ReadWrite | FileShare.Delete))
         using (var bs = new BufferedStream(fs))
         using (var sha1 = new SHA1CryptoServiceProvider())
         {
             var hash = sha1.ComputeHash(bs);
             var formatted = new StringBuilder(2 * hash.Length);
             foreach (var b in hash)
             {
                 formatted.AppendFormat("{0:X2}", b);
             }
             return formatted.ToString();
         }
     }
static void Common.CopyTo (Stream source, Stream destination) static private
Definition at line 36 of file Common.cs.
Referenced by InternalPreloadUnmanagedLibraries(), and LoadStream().
     {
         var array = new byte[81920];
         int count;
         while ((count = source.Read(array, 0, array.Length)) != 0)
         {
             destination.Write(array, 0, count);
         }
     }
static void Common.CopyTo (Stream source, Stream destination) static private
Definition at line 36 of file Common.cs.
     {
         var array = new byte[81920];
         int count;
         while ((count = source.Read(array, 0, array.Length)) != 0)
         {
             destination.Write(array, 0, count);
         }
     }
static void Common.CreateDirectory (string tempBasePath) static private
Definition at line 46 of file Common.cs.
     {
         if (!Directory.Exists(tempBasePath))
         {
             Directory.CreateDirectory(tempBasePath);
         }
     }
static void Common.CreateDirectory (string tempBasePath) static private
Definition at line 46 of file Common.cs.
Referenced by PreloadUnmanagedLibraries().
     {
         if (!Directory.Exists(tempBasePath))
         {
             Directory.CreateDirectory(tempBasePath);
         }
     }
static string Common.CultureToString (CultureInfo culture) static private
Definition at line 95 of file Common.cs.
Referenced by ReadExistingAssembly().
     {
         if (culture == null)
             return "";
         return culture.Name;
     }
static string Common.CultureToString (CultureInfo culture) static private
Definition at line 95 of file Common.cs.
     {
         if (culture == null)
             return "";
         return culture.Name;
     }
static void Common.InternalPreloadUnmanagedLibraries (string tempBasePath, IEnumerable< string > libs, Dictionary< string, string > checksums) static private
Definition at line 229 of file Common.cs.
References CalculateChecksum(), CopyTo(), LoadLibrary(), LoadStream(), MoveFileEx(), ResourceNameToPath(), and SetDllDirectory().
Referenced by PreloadUnmanagedLibraries().
     {
         string name;
         foreach (var lib in libs)
         {
             name = ResourceNameToPath(lib);
             var assemblyTempFilePath = Path.Combine(tempBasePath, name);
             if (File.Exists(assemblyTempFilePath))
             {
                 var checksum = CalculateChecksum(assemblyTempFilePath);
                 if (checksum != checksums[lib])
                     File.Delete(assemblyTempFilePath);
             }
             if (!File.Exists(assemblyTempFilePath))
             {
                 using (var copyStream = LoadStream(lib))
                 using (var assemblyTempFile = File.OpenWrite(assemblyTempFilePath))
                 {
                     CopyTo(copyStream, assemblyTempFile);
                 }
                 if (!MoveFileEx(assemblyTempFilePath, null, DelayUntilReboot))
                 {
                     //TODO: for now we ignore the return value.
                 }
             }
         }
         SetDllDirectory(tempBasePath);
         foreach (var lib in libs)
         {
             name = ResourceNameToPath(lib);
             if (name.EndsWith(".dll"))
             {
                 var assemblyTempFilePath = Path.Combine(tempBasePath, name);
                 LoadLibrary(assemblyTempFilePath);
             }
         }
     }
static void Common.InternalPreloadUnmanagedLibraries (string tempBasePath, IEnumerable< string > libs, Dictionary< string, string > checksums) static private
Definition at line 229 of file Common.cs.
References CalculateChecksum(), CopyTo(), LoadLibrary(), LoadStream(), MoveFileEx(), ResourceNameToPath(), and SetDllDirectory().
     {
         string name;
         foreach (var lib in libs)
         {
             name = ResourceNameToPath(lib);
             var assemblyTempFilePath = Path.Combine(tempBasePath, name);
             if (File.Exists(assemblyTempFilePath))
             {
                 var checksum = CalculateChecksum(assemblyTempFilePath);
                 if (checksum != checksums[lib])
                     File.Delete(assemblyTempFilePath);
             }
             if (!File.Exists(assemblyTempFilePath))
             {
                 using (var copyStream = LoadStream(lib))
                 using (var assemblyTempFile = File.OpenWrite(assemblyTempFilePath))
                 {
                     CopyTo(copyStream, assemblyTempFile);
                 }
                 if (!MoveFileEx(assemblyTempFilePath, null, DelayUntilReboot))
                 {
                     //TODO: for now we ignore the return value.
                 }
             }
         }
         SetDllDirectory(tempBasePath);
         foreach (var lib in libs)
         {
             name = ResourceNameToPath(lib);
             if (name.EndsWith(".dll"))
             {
                 var assemblyTempFilePath = Path.Combine(tempBasePath, name);
                 LoadLibrary(assemblyTempFilePath);
             }
         }
     }
static IntPtr Common.LoadLibrary (string dllToLoad) private
Referenced by InternalPreloadUnmanagedLibraries().
static IntPtr Common.LoadLibrary (string dllToLoad) private
static Stream Common.LoadStream (Dictionary< string, string > resourceNames, string name) static private
Definition at line 163 of file Common.cs.
Referenced by InternalPreloadUnmanagedLibraries(), LoadStream(), and ReadFromEmbeddedResources().
     {
         string value;
         if (resourceNames.TryGetValue(name, out value))
             return LoadStream(value);
         return null;
     }
static Stream Common.LoadStream (Dictionary< string, string > resourceNames, string name) static private
Definition at line 163 of file Common.cs.
References LoadStream().
     {
         string value;
         if (resourceNames.TryGetValue(name, out value))
             return LoadStream(value);
         return null;
     }
static Stream Common.LoadStream (string fullname) static private
Definition at line 172 of file Common.cs.
References CopyTo().
     {
         var executingAssembly = Assembly.GetExecutingAssembly();
         if (fullname.EndsWith(".compressed"))
         {
             using (var stream = executingAssembly.GetManifestResourceStream(fullname))
             using (var compressStream = new DeflateStream(stream, CompressionMode.Decompress))
             {
                 var memStream = new MemoryStream();
                 CopyTo(compressStream, memStream);
                 memStream.Position = 0;
                 return memStream;
             }
         }
         return executingAssembly.GetManifestResourceStream(fullname);
     }
static Stream Common.LoadStream (string fullname) static private
Definition at line 172 of file Common.cs.
References CopyTo().
     {
         var executingAssembly = Assembly.GetExecutingAssembly();
         if (fullname.EndsWith(".compressed"))
         {
             using (var stream = executingAssembly.GetManifestResourceStream(fullname))
             using (var compressStream = new DeflateStream(stream, CompressionMode.Decompress))
             {
                 var memStream = new MemoryStream();
                 CopyTo(compressStream, memStream);
                 memStream.Position = 0;
                 return memStream;
             }
         }
         return executingAssembly.GetManifestResourceStream(fullname);
     }
static void Common.Log (string format, params object[] args) static
Definition at line 30 of file Common.cs.
Referenced by ReadExistingAssembly(), and ILTemplate.ResolveAssembly().
     {
         // Should this be trace?
         Debug.WriteLine("=== COSTURA === " + string.Format(format, args));
     }
static void Common.Log (string format, params object[] args) static
Definition at line 30 of file Common.cs.
     {
         // Should this be trace?
         Debug.WriteLine("=== COSTURA === " + string.Format(format, args));
     }
static bool Common.MoveFileEx (string lpExistingFileName, string lpNewFileName, int dwFlags) private
static bool Common.MoveFileEx (string lpExistingFileName, string lpNewFileName, int dwFlags) private
Referenced by InternalPreloadUnmanagedLibraries().
static void Common.PreloadUnmanagedLibraries (string hash, string tempBasePath, IEnumerable< string > libs, Dictionary< string, string > checksums) static
Definition at line 192 of file Common.cs.
References CreateDirectory(), and InternalPreloadUnmanagedLibraries().
     {
         var mutexId = $"Global\\Costura{hash}";
         using (var mutex = new Mutex(false, mutexId))
         {
             var allowEveryoneRule = new MutexAccessRule(new SecurityIdentifier(WellKnownSidType.WorldSid, null), MutexRights.FullControl, AccessControlType.Allow);
             var securitySettings = new MutexSecurity();
             securitySettings.AddAccessRule(allowEveryoneRule);
             mutex.SetAccessControl(securitySettings);
             var hasHandle = false;
             try
             {
                 try
                 {
                     hasHandle = mutex.WaitOne(60000, false);
                     if (hasHandle == false)
                         throw new TimeoutException("Timeout waiting for exclusive access");
                 }
                 catch (AbandonedMutexException)
                 {
                     hasHandle = true;
                 }
                 var bittyness = IntPtr.Size == 8 ? "64" : "32";
                 CreateDirectory(Path.Combine(tempBasePath, bittyness));
                 InternalPreloadUnmanagedLibraries(tempBasePath, libs, checksums);
             }
             finally
             {
                 if (hasHandle)
                     mutex.ReleaseMutex();
             }
         }
     }
static void Common.PreloadUnmanagedLibraries (string hash, string tempBasePath, IEnumerable< string > libs, Dictionary< string, string > checksums) static
Definition at line 192 of file Common.cs.
References CreateDirectory(), and InternalPreloadUnmanagedLibraries().
     {
         var mutexId = $"Global\\Costura{hash}";
         using (var mutex = new Mutex(false, mutexId))
         {
             var allowEveryoneRule = new MutexAccessRule(new SecurityIdentifier(WellKnownSidType.WorldSid, null), MutexRights.FullControl, AccessControlType.Allow);
             var securitySettings = new MutexSecurity();
             securitySettings.AddAccessRule(allowEveryoneRule);
             mutex.SetAccessControl(securitySettings);
             var hasHandle = false;
             try
             {
                 try
                 {
                     hasHandle = mutex.WaitOne(60000, false);
                     if (hasHandle == false)
                         throw new TimeoutException("Timeout waiting for exclusive access");
                 }
                 catch (AbandonedMutexException)
                 {
                     hasHandle = true;
                 }
                 var bittyness = IntPtr.Size == 8 ? "64" : "32";
                 CreateDirectory(Path.Combine(tempBasePath, bittyness));
                 InternalPreloadUnmanagedLibraries(tempBasePath, libs, checksums);
             }
             finally
             {
                 if (hasHandle)
                     mutex.ReleaseMutex();
             }
         }
     }
static Assembly Common.ReadExistingAssembly (AssemblyName name) static
Definition at line 77 of file Common.cs.
References CultureToString(), and Log().
Referenced by ILTemplate.ResolveAssembly().
     {
         var currentDomain = AppDomain.CurrentDomain;
         var assemblies = currentDomain.GetAssemblies();
         foreach (var assembly in assemblies)
         {
             var currentName = assembly.GetName();
             if (string.Equals(currentName.Name, name.Name, StringComparison.InvariantCultureIgnoreCase) &&
                 string.Equals(CultureToString(currentName.CultureInfo), CultureToString(name.CultureInfo), StringComparison.InvariantCultureIgnoreCase))
             {
                 Log("Assembly '{0}' already loaded, returning existing assembly", assembly.FullName);
                 return assembly;
             }
         }
         return null;
     }
static Assembly Common.ReadExistingAssembly (AssemblyName name) static
Definition at line 77 of file Common.cs.
References CultureToString(), and Log().
     {
         var currentDomain = AppDomain.CurrentDomain;
         var assemblies = currentDomain.GetAssemblies();
         foreach (var assembly in assemblies)
         {
             var currentName = assembly.GetName();
             if (string.Equals(currentName.Name, name.Name, StringComparison.InvariantCultureIgnoreCase) &&
                 string.Equals(CultureToString(currentName.CultureInfo), CultureToString(name.CultureInfo), StringComparison.InvariantCultureIgnoreCase))
             {
                 Log("Assembly '{0}' already loaded, returning existing assembly", assembly.FullName);
                 return assembly;
             }
         }
         return null;
     }
static Assembly Common.ReadFromDiskCache (string tempBasePath, AssemblyName requestedAssemblyName) static
Definition at line 103 of file Common.cs.
     {
         var name = requestedAssemblyName.Name.ToLowerInvariant();
         if (requestedAssemblyName.CultureInfo != null && !String.IsNullOrEmpty(requestedAssemblyName.CultureInfo.Name))
             name = $"{requestedAssemblyName.CultureInfo.Name}.{name}";
         var bittyness = IntPtr.Size == 8 ? "64" : "32";
         var assemblyTempFilePath = Path.Combine(tempBasePath, String.Concat(name, ".dll"));
         if (File.Exists(assemblyTempFilePath))
         {
             return Assembly.LoadFile(assemblyTempFilePath);
         }
         assemblyTempFilePath = Path.ChangeExtension(assemblyTempFilePath, "exe");
         if (File.Exists(assemblyTempFilePath))
         {
             return Assembly.LoadFile(assemblyTempFilePath);
         }
         assemblyTempFilePath = Path.Combine(Path.Combine(tempBasePath, bittyness), String.Concat(name, ".dll"));
         if (File.Exists(assemblyTempFilePath))
         {
             return Assembly.LoadFile(assemblyTempFilePath);
         }
         assemblyTempFilePath = Path.ChangeExtension(assemblyTempFilePath, "exe");
         if (File.Exists(assemblyTempFilePath))
         {
             return Assembly.LoadFile(assemblyTempFilePath);
         }
         return null;
     }
static Assembly Common.ReadFromDiskCache (string tempBasePath, AssemblyName requestedAssemblyName) static
Definition at line 103 of file Common.cs.
     {
         var name = requestedAssemblyName.Name.ToLowerInvariant();
         if (requestedAssemblyName.CultureInfo != null && !String.IsNullOrEmpty(requestedAssemblyName.CultureInfo.Name))
             name = $"{requestedAssemblyName.CultureInfo.Name}.{name}";
         var bittyness = IntPtr.Size == 8 ? "64" : "32";
         var assemblyTempFilePath = Path.Combine(tempBasePath, String.Concat(name, ".dll"));
         if (File.Exists(assemblyTempFilePath))
         {
             return Assembly.LoadFile(assemblyTempFilePath);
         }
         assemblyTempFilePath = Path.ChangeExtension(assemblyTempFilePath, "exe");
         if (File.Exists(assemblyTempFilePath))
         {
             return Assembly.LoadFile(assemblyTempFilePath);
         }
         assemblyTempFilePath = Path.Combine(Path.Combine(tempBasePath, bittyness), String.Concat(name, ".dll"));
         if (File.Exists(assemblyTempFilePath))
         {
             return Assembly.LoadFile(assemblyTempFilePath);
         }
         assemblyTempFilePath = Path.ChangeExtension(assemblyTempFilePath, "exe");
         if (File.Exists(assemblyTempFilePath))
         {
             return Assembly.LoadFile(assemblyTempFilePath);
         }
         return null;
     }
static Assembly Common.ReadFromEmbeddedResources (Dictionary< string, string > assemblyNames, Dictionary< string, string > symbolNames, AssemblyName requestedAssemblyName) static
Definition at line 134 of file Common.cs.
References LoadStream(), and ReadStream().
     {
         var name = requestedAssemblyName.Name.ToLowerInvariant();
         if (requestedAssemblyName.CultureInfo != null && !String.IsNullOrEmpty(requestedAssemblyName.CultureInfo.Name))
             name = $"{requestedAssemblyName.CultureInfo.Name}.{name}";
         byte[] assemblyData;
         using (var assemblyStream = LoadStream(assemblyNames, name))
         {
             if (assemblyStream == null)
             {
                 return null;
             }
             assemblyData = ReadStream(assemblyStream);
         }
         using (var pdbStream = LoadStream(symbolNames, name))
         {
             if (pdbStream != null)
             {
                 var pdbData = ReadStream(pdbStream);
                 return Assembly.Load(assemblyData, pdbData);
             }
         }
         return Assembly.Load(assemblyData);
     }
static Assembly Common.ReadFromEmbeddedResources (Dictionary< string, string > assemblyNames, Dictionary< string, string > symbolNames, AssemblyName requestedAssemblyName) static
Definition at line 134 of file Common.cs.
References LoadStream(), and ReadStream().
Referenced by ILTemplate.ResolveAssembly().
     {
         var name = requestedAssemblyName.Name.ToLowerInvariant();
         if (requestedAssemblyName.CultureInfo != null && !String.IsNullOrEmpty(requestedAssemblyName.CultureInfo.Name))
             name = $"{requestedAssemblyName.CultureInfo.Name}.{name}";
         byte[] assemblyData;
         using (var assemblyStream = LoadStream(assemblyNames, name))
         {
             if (assemblyStream == null)
             {
                 return null;
             }
             assemblyData = ReadStream(assemblyStream);
         }
         using (var pdbStream = LoadStream(symbolNames, name))
         {
             if (pdbStream != null)
             {
                 var pdbData = ReadStream(pdbStream);
                 return Assembly.Load(assemblyData, pdbData);
             }
         }
         return Assembly.Load(assemblyData);
     }
static byte [] Common.ReadStream (Stream stream) static private
Definition at line 54 of file Common.cs.
     {
         var data = new Byte[stream.Length];
         stream.Read(data, 0, data.Length);
         return data;
     }
static byte [] Common.ReadStream (Stream stream) static private
Definition at line 54 of file Common.cs.
Referenced by ReadFromEmbeddedResources().
     {
         var data = new Byte[stream.Length];
         stream.Read(data, 0, data.Length);
         return data;
     }
static string Common.ResourceNameToPath (string lib) static private
Definition at line 275 of file Common.cs.
Referenced by InternalPreloadUnmanagedLibraries().
     {
         var bittyness = IntPtr.Size == 8 ? "64" : "32";
         var name = lib;
         if (lib.StartsWith(String.Concat("costura", bittyness, ".")))
         {
             name = Path.Combine(bittyness, lib.Substring(10));
         }
         else if (lib.StartsWith("costura."))
         {
             name = lib.Substring(8);
         }
         if (name.EndsWith(".compressed"))
         {
             name = name.Substring(0, name.Length - 11);
         }
         return name;
     }
static string Common.ResourceNameToPath (string lib) static private
Definition at line 275 of file Common.cs.
     {
         var bittyness = IntPtr.Size == 8 ? "64" : "32";
         var name = lib;
         if (lib.StartsWith(String.Concat("costura", bittyness, ".")))
         {
             name = Path.Combine(bittyness, lib.Substring(10));
         }
         else if (lib.StartsWith("costura."))
         {
             name = lib.Substring(8);
         }
         if (name.EndsWith(".compressed"))
         {
             name = name.Substring(0, name.Length - 11);
         }
         return name;
     }
static bool Common.SetDllDirectory (string lpPathName) private
Referenced by InternalPreloadUnmanagedLibraries().
static bool Common.SetDllDirectory (string lpPathName) private
Member Data Documentation
const int Common.DelayUntilReboot = 4 private
Definition at line 17 of file Common.cs.
The documentation for this class was generated from the following file:
TGS.Installer.UI/obj/Release/Common.cs