tgstation-server: Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider Class Reference
Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider Class Reference
A IDmbProvider that uses symlinks.
Public Member Functions
SwappableDmbProvider (IDmbProvider baseProvider, IIOManager ioManager, ISymlinkFactory symlinkFactory)
Initializes a new instance of the SwappableDmbProvider class.
void Dispose ()
void KeepAlive ()
Disposing the IDmbProvider won't cause a cleanup of the working directory.
async Task MakeActive (CancellationToken cancellationToken)
Make the SwappableDmbProvider active by replacing the live link with our CompileJob.
void KeepAlive ()
Disposing the IDmbProvider won't cause a cleanup of the working directory.
Static Public Attributes
const string LiveGameDirectory = "Live"
The directory where the baseProvider is symlinked to.
Properties
string DmbName [get]
The file name of the .dmb.
string Directory [get]
The primary game directory with a trailing directory separator.
CompileJob CompileJob [get]
The CompileJob of the .dmb.
bool Swapped [get]
If MakeActive(CancellationToken) has been run.
Properties inherited from Tgstation.Server.Host.Components.Deployment.IDmbProvider
string DmbName [get]
The file name of the .dmb.
string Directory [get]
The primary game directory with a trailing directory separator.
CompileJob CompileJob [get]
The CompileJob of the .dmb.
Private Attributes
readonly IDmbProvider baseProvider
The IDmbProvider we are swapping for.
readonly IIOManager ioManager
The IIOManager to use.
readonly ISymlinkFactory symlinkFactory
The ISymlinkFactory to use.
volatile int swapped
Backing field for Swapped.
Detailed Description
A IDmbProvider that uses symlinks.
Definition at line 13 of file SwappableDmbProvider.cs.
Constructor & Destructor Documentation
SwappableDmbProvider()
Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.SwappableDmbProvider (IDmbProvider baseProvider, IIOManager ioManager, ISymlinkFactory symlinkFactory)
Initializes a new instance of the SwappableDmbProvider class.
Parameters
baseProvider The value of baseProvider.
ioManager The value of ioManager.
symlinkFactory The value of symlinkFactory.
Definition at line 60 of file SwappableDmbProvider.cs.
        {
            this.baseProvider = baseProvider ?? throw new ArgumentNullException(nameof(baseProvider));
            this.ioManager = ioManager ?? throw new ArgumentNullException(nameof(ioManager));
            this.symlinkFactory = symlinkFactory ?? throw new ArgumentNullException(nameof(symlinkFactory));
        }
References Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.baseProvider, Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.ioManager, and Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.symlinkFactory.
Member Function Documentation
Dispose()
void Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.Dispose ()
Referenced by Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.DisposeAndNullControllersImpl(), and Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.HandleNewDmbAvailable().
KeepAlive()
void Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.KeepAlive ()
Disposing the IDmbProvider won't cause a cleanup of the working directory.
Implements Tgstation.Server.Host.Components.Deployment.IDmbProvider.
MakeActive()
async Task Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.MakeActive (CancellationToken cancellationToken)
Make the SwappableDmbProvider active by replacing the live link with our CompileJob.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Definition at line 78 of file SwappableDmbProvider.cs.
        {
            if (Interlocked.Exchange(ref swapped, 1) != 0)
                throw new InvalidOperationException("Already swapped!");
            if (symlinkFactory.SymlinkedDirectoriesAreDeletedAsFiles)
                await ioManager.DeleteFile(LiveGameDirectory, cancellationToken);
            else
                await ioManager.DeleteDirectory(LiveGameDirectory, cancellationToken);
            await symlinkFactory.CreateSymbolicLink(
                ioManager.ResolvePath(baseProvider.Directory),
                ioManager.ResolvePath(LiveGameDirectory),
                cancellationToken);
        }
References Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.baseProvider, Tgstation.Server.Host.IO.ISymlinkFactory.CreateSymbolicLink(), Tgstation.Server.Host.IO.IIOManager.DeleteDirectory(), Tgstation.Server.Host.IO.IIOManager.DeleteFile(), Tgstation.Server.Host.Components.Deployment.IDmbProvider.Directory, Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.ioManager, Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.LiveGameDirectory, Tgstation.Server.Host.IO.IIOManager.ResolvePath(), Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.swapped, Tgstation.Server.Host.IO.ISymlinkFactory.SymlinkedDirectoriesAreDeletedAsFiles, and Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.symlinkFactory.
Referenced by Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.InitialLink(), and Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.PerformDmbSwap().
Member Data Documentation
baseProvider
readonly IDmbProvider Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.baseProvider private
The IDmbProvider we are swapping for.
Definition at line 37 of file SwappableDmbProvider.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.MakeActive(), and Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.SwappableDmbProvider().
ioManager
readonly IIOManager Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.ioManager private
The IIOManager to use.
Definition at line 42 of file SwappableDmbProvider.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.MakeActive(), and Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.SwappableDmbProvider().
LiveGameDirectory
const string Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.LiveGameDirectory = "Live" static
The directory where the baseProvider is symlinked to.
Definition at line 18 of file SwappableDmbProvider.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DmbFactory.CleanUnusedCompileJobs(), and Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.MakeActive().
swapped
volatile int Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.swapped private
Backing field for Swapped.
Definition at line 52 of file SwappableDmbProvider.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.MakeActive().
symlinkFactory
readonly ISymlinkFactory Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.symlinkFactory private
The ISymlinkFactory to use.
Definition at line 47 of file SwappableDmbProvider.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.MakeActive(), and Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.SwappableDmbProvider().
Property Documentation
CompileJob
CompileJob Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.CompileJob get
The CompileJob of the .dmb.
Implements Tgstation.Server.Host.Components.Deployment.IDmbProvider.
Definition at line 27 of file SwappableDmbProvider.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.HandleNormalReboot(), and Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.PerformDmbSwap().
Directory
string Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.Directory get
The primary game directory with a trailing directory separator.
Implements Tgstation.Server.Host.Components.Deployment.IDmbProvider.
Definition at line 24 of file SwappableDmbProvider.cs.
DmbName
string Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.DmbName get
The file name of the .dmb.
Implements Tgstation.Server.Host.Components.Deployment.IDmbProvider.
Definition at line 21 of file SwappableDmbProvider.cs.
Swapped
bool Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.Swapped get
If MakeActive(CancellationToken) has been run.
Definition at line 32 of file SwappableDmbProvider.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.HandleNormalReboot().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Deployment/SwappableDmbProvider.cs