tgstation-server: Tgstation.Server.Host.Jobs.JobProgressReporter Class Reference
Tgstation.Server.Host.Jobs.JobProgressReporter Class Reference
Progress reporter for a Job.
Public Member Functions
JobProgressReporter ()
Initializes a new instance of the JobProgressReporter class.
JobProgressReporter (ILogger< JobProgressReporter > logger, string? stageName, Action< string?, double?> callback)
Initializes a new instance of the JobProgressReporter class.
void Dispose ()
void ReportProgress (double? progress)
Report progress.
JobProgressReporter CreateSection (string? newStageName, double percentage)
Create a subsection of the JobProgressReporter with its optional own stage name.
Properties
string? StageName [get, set]
The name of the current stage.
Private Member Functions
JobProgressReporter (ILogger< JobProgressReporter > logger, string? stageName, Action< string?, double?> callback, bool setStageName)
Initializes a new instance of the JobProgressReporter class.
Private Attributes
readonly ILogger< JobProgressReporter > logger
The ILogger<TCategoryName> for the JobProgressReporter.
readonly Action< string?, double?> callback
Progress reporter callback taking a description of what the job is currently doing and the (optional) progress of the job on a scale from 0.0-1.0.
string? stageName
Backing field for StageName.
double? lastProgress
The last progress value pushed into the callback.
double sectionProgression
The total progress reported so far in this section.
double? sectionReservations
The total progress reserved for use in this section.
Detailed Description
Progress reporter for a Job.
Definition at line 13 of file JobProgressReporter.cs.
Constructor & Destructor Documentation
JobProgressReporter() [1/3]
Tgstation.Server.Host.Jobs.JobProgressReporter.JobProgressReporter ()
Initializes a new instance of the JobProgressReporter class.
This variant has no function.
Definition at line 65 of file JobProgressReporter.cs.
            : this(
                 NullLogger<JobProgressReporter>.Instance,
                 null,
                 (_, _) => { },
                 false)
        {
        }
Referenced by Tgstation.Server.Host.Jobs.JobProgressReporter.CreateSection().
JobProgressReporter() [2/3]
Tgstation.Server.Host.Jobs.JobProgressReporter.JobProgressReporter (ILogger< JobProgressReporter > logger, string? stageName, Action< string?, double?> callback)
Initializes a new instance of the JobProgressReporter class.
Parameters
logger The value of logger.
stageName The value of StageName.
callback The value of callback.
Definition at line 80 of file JobProgressReporter.cs.
            : this(
                 logger,
                 stageName,
                 callback,
                 true)
        {
        }
JobProgressReporter() [3/3]
Tgstation.Server.Host.Jobs.JobProgressReporter.JobProgressReporter (ILogger< JobProgressReporter > logger, string? stageName, Action< string?, double?> callback, bool setStageName) private
Initializes a new instance of the JobProgressReporter class.
Parameters
logger The value of logger.
stageName The value of StageName.
callback The value of callback.
setStageName If true an initial call to callback will be made with only the stageName .
Definition at line 96 of file JobProgressReporter.cs.
        {
            this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
            this.callback = callback ?? throw new ArgumentNullException(nameof(callback));
            if (setStageName)
            {
                StageName = stageName;
            }
            else
            {
                this.stageName = stageName;
            }
            logger.LogDebug("Job progress reporter created. Stage: {stageName}", stageName ?? "(null)");
        }
References Tgstation.Server.Host.Jobs.JobProgressReporter.callback, Tgstation.Server.Host.Jobs.JobProgressReporter.logger, Tgstation.Server.Host.Jobs.JobProgressReporter.StageName, and Tgstation.Server.Host.Jobs.JobProgressReporter.stageName.
Member Function Documentation
CreateSection()
JobProgressReporter Tgstation.Server.Host.Jobs.JobProgressReporter.CreateSection (string? newStageName, double percentage)
Create a subsection of the JobProgressReporter with its optional own stage name.
Parameters
newStageName The optional StageName of the new JobProgressReporter.
percentage The 0.0f-1.0f percentage of the current JobProgressReporter's percentage should be given to the section.
Returns
A new JobProgressReporter that is a subsection of this one.
A JobProgressReporter should only have one active child at a time.
Definition at line 176 of file JobProgressReporter.cs.
        {
            if (percentage > 1 || percentage < 0)
            {
                logger.LogError(
                    new ArgumentOutOfRangeException(nameof(percentage), percentage, "Percentage must be a value from 0-1!"),
                    "TGS BUG: Invalid percentage value for stage {newStageName}! Clamping...",
                    newStageName ?? "(null)");
                percentage = Math.Min(Math.Max(percentage, 0.0), 1.0);
            }
            if (!sectionReservations.HasValue)
            {
                if (sectionProgression != 0)
                {
                    logger.LogError(
                        new InvalidOperationException("Progress reporter is creating a section with local progress!"),
                        "TGS BUG: A progress reporter is using mixed local and nested progress, this is not supported");
                }
                sectionReservations = 0;
            }
            // floating point >.<
            if (percentage + sectionReservations.Value > 1.0001)
            {
                var remainingPercentage = 1.0 - sectionReservations.Value;
                logger.LogError(
                    "Stage {newStageName} is overbudgeted ({budget}/{remainingPercentage})! Clamping...",
                    newStageName,
                    percentage,
                    remainingPercentage);
                percentage = remainingPercentage;
            }
            Math.Min(sectionReservations.Value + percentage, 1);
            var childLocalProgress = 0.0;
            var newReporter = new JobProgressReporter(
                logger,
                newStageName,
                (currentStage, progress) =>
                {
                    currentStage ??= StageName;
                    if (!progress.HasValue)
                    {
                        callback(currentStage, null);
                        return;
                    }
                    var progressWithoutChild = sectionProgression - childLocalProgress;
                    childLocalProgress = progress.Value * percentage;
                    // floating point >.<
                    sectionProgression = Math.Min(progressWithoutChild + childLocalProgress, 1);
                    if (sectionProgression > 9.9999)
                        sectionProgression = 1;
                    callback(currentStage, sectionProgression);
                },
                false);
            newReporter.ReportProgress(0);
            return newReporter;
        }
References Tgstation.Server.Host.Jobs.JobProgressReporter.callback, Tgstation.Server.Host.Jobs.JobProgressReporter.JobProgressReporter(), Tgstation.Server.Host.Jobs.JobProgressReporter.logger, Tgstation.Server.Host.Jobs.JobProgressReporter.sectionProgression, Tgstation.Server.Host.Jobs.JobProgressReporter.sectionReservations, and Tgstation.Server.Host.Jobs.JobProgressReporter.StageName.
Referenced by Tgstation.Server.Host.Components.Repository.Repository.AddTestMerge(), Tgstation.Server.Host.Components.Repository.Repository.CheckoutObject(), Tgstation.Server.Host.Components.Repository.RepositoryManager.CloneRepository(), Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.DownloadVersion(), Tgstation.Server.Host.Components.Repository.Repository.FetchOrigin(), Tgstation.Server.Host.Components.Repository.Repository.GeneratePushOptions(), Tgstation.Server.Host.Components.Engine.EngineManager.InstallVersionFiles(), Tgstation.Server.Host.Components.Repository.Repository.RawCheckout(), Tgstation.Server.Host.Components.Instance.RepositoryAutoUpdateJob(), Tgstation.Server.Host.Components.Repository.RepositoryUpdateService.RepositoryRecloneJob(), Tgstation.Server.Host.Components.Repository.RepositoryUpdateService.RepositoryUpdateJob(), Tgstation.Server.Host.Components.Repository.Repository.ResetToOrigin(), Tgstation.Server.Host.Components.Repository.Repository.Synchronize(), and Tgstation.Server.Host.Components.Repository.Repository.UpdateSubmodules().
Dispose()
void Tgstation.Server.Host.Jobs.JobProgressReporter.Dispose ()
Definition at line 113 of file JobProgressReporter.cs.
        {
            if (sectionReservations.HasValue)
                if (sectionReservations.Value != 1.0)
                {
                    // not an error, processes can throw
                    sectionReservations = null;
                }
                else if (sectionProgression < 1.0)
                {
                    logger.LogError(
                        new InvalidOperationException($"Parent progress reporter has child sections that didn't complete! Current: {sectionProgression}"),
                        "TGS BUG: Progress reporter children didn't complete!");
                    sectionReservations = null;
                }
            if (!sectionReservations.HasValue)
                ReportProgress(1);
        }
References Tgstation.Server.Host.Jobs.JobProgressReporter.logger, Tgstation.Server.Host.Jobs.JobProgressReporter.ReportProgress(), Tgstation.Server.Host.Jobs.JobProgressReporter.sectionProgression, and Tgstation.Server.Host.Jobs.JobProgressReporter.sectionReservations.
ReportProgress()
void Tgstation.Server.Host.Jobs.JobProgressReporter.ReportProgress (double? progress)
Report progress.
Parameters
progress A percentage value from 0.0f-1.0f.
Definition at line 137 of file JobProgressReporter.cs.
        {
            if (sectionReservations.HasValue)
                if (progress == 0)
                {
                    // might be a stage reset
                    sectionReservations = null;
                }
                else
                {
                    logger.LogError(
                        new InvalidOperationException("Progress reporter is reporting progress with existing nested sections!"),
                        "TGS BUG: A progress reporter is using mixed local and nested progress, this is not supported");
                }
            var clampedProgress = progress;
            if (progress.HasValue)
                if (progress > 1 || progress < 0)
                {
                    logger.LogError(
                        new ArgumentOutOfRangeException(nameof(progress), progress, "Progress must be a value from 0-1!"),
                        "TGS BUG: Invalid progress value for stage {stageName}",
                        StageName ?? "(null)");
                    clampedProgress = null;
                }
                else
                    sectionProgression = progress.Value;
            callback(StageName, clampedProgress);
            lastProgress = clampedProgress;
        }
References Tgstation.Server.Host.Jobs.JobProgressReporter.callback, Tgstation.Server.Host.Jobs.JobProgressReporter.lastProgress, Tgstation.Server.Host.Jobs.JobProgressReporter.logger, Tgstation.Server.Host.Jobs.JobProgressReporter.sectionProgression, Tgstation.Server.Host.Jobs.JobProgressReporter.sectionReservations, and Tgstation.Server.Host.Jobs.JobProgressReporter.StageName.
Referenced by Tgstation.Server.Host.Components.Repository.Repository.CheckoutProgressHandler(), Tgstation.Server.Host.Components.Repository.RepositoryManager.CloneRepository(), Tgstation.Server.Host.Jobs.JobProgressReporter.Dispose(), Tgstation.Server.Host.Extensions.FetchOptionsExtensions.Hydrate(), Tgstation.Server.Host.Components.Engine.EngineManager.InstallVersionFiles(), Tgstation.Server.Host.Components.Deployment.DreamMaker.ProgressTask(), Tgstation.Server.Host.Components.Repository.Repository.RawCheckout(), Tgstation.Server.Host.Components.Repository.RepositoryUpdateService.RepositoryUpdateJob(), and Tgstation.Server.Host.Components.Repository.Repository.UpdateSubmodules().
Member Data Documentation
callback
readonly Action<string?, double?> Tgstation.Server.Host.Jobs.JobProgressReporter.callback private
Progress reporter callback taking a description of what the job is currently doing and the (optional) progress of the job on a scale from 0.0-1.0.
Definition at line 39 of file JobProgressReporter.cs.
Referenced by Tgstation.Server.Host.Jobs.JobProgressReporter.CreateSection(), Tgstation.Server.Host.Jobs.JobProgressReporter.JobProgressReporter(), and Tgstation.Server.Host.Jobs.JobProgressReporter.ReportProgress().
lastProgress
double? Tgstation.Server.Host.Jobs.JobProgressReporter.lastProgress private
The last progress value pushed into the callback.
Definition at line 49 of file JobProgressReporter.cs.
Referenced by Tgstation.Server.Host.Jobs.JobProgressReporter.ReportProgress().
logger
readonly ILogger<JobProgressReporter> Tgstation.Server.Host.Jobs.JobProgressReporter.logger private
The ILogger<TCategoryName> for the JobProgressReporter.
Definition at line 34 of file JobProgressReporter.cs.
Referenced by Tgstation.Server.Host.Jobs.JobProgressReporter.CreateSection(), Tgstation.Server.Host.Jobs.JobProgressReporter.Dispose(), Tgstation.Server.Host.Jobs.JobProgressReporter.JobProgressReporter(), and Tgstation.Server.Host.Jobs.JobProgressReporter.ReportProgress().
sectionProgression
double Tgstation.Server.Host.Jobs.JobProgressReporter.sectionProgression private
The total progress reported so far in this section.
Definition at line 54 of file JobProgressReporter.cs.
Referenced by Tgstation.Server.Host.Jobs.JobProgressReporter.CreateSection(), Tgstation.Server.Host.Jobs.JobProgressReporter.Dispose(), and Tgstation.Server.Host.Jobs.JobProgressReporter.ReportProgress().
sectionReservations
double? Tgstation.Server.Host.Jobs.JobProgressReporter.sectionReservations private
The total progress reserved for use in this section.
Definition at line 59 of file JobProgressReporter.cs.
Referenced by Tgstation.Server.Host.Jobs.JobProgressReporter.CreateSection(), Tgstation.Server.Host.Jobs.JobProgressReporter.Dispose(), and Tgstation.Server.Host.Jobs.JobProgressReporter.ReportProgress().
stageName
string? Tgstation.Server.Host.Jobs.JobProgressReporter.stageName private
Backing field for StageName.
Definition at line 44 of file JobProgressReporter.cs.
Referenced by Tgstation.Server.Host.Jobs.JobProgressReporter.JobProgressReporter().
Property Documentation
StageName
string? Tgstation.Server.Host.Jobs.JobProgressReporter.StageName get set
The name of the current stage.
Definition at line 18 of file JobProgressReporter.cs.
        {
            get => stageName;
            set
            {
                if (stageName == value)
                    return;
                stageName = value;
                callback(stageName, lastProgress);
            }
        }
Referenced by Tgstation.Server.Host.Jobs.JobProgressReporter.CreateSection(), Tgstation.Server.Host.Jobs.JobProgressReporter.JobProgressReporter(), and Tgstation.Server.Host.Jobs.JobProgressReporter.ReportProgress().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Jobs/JobProgressReporter.cs