tgstation-server: Tgstation.Server.Host.Security.OAuth.BaseOAuthValidator Class Reference
Tgstation.Server.Host.Security.OAuth.BaseOAuthValidator Class Reference abstract
Base class for IOAuthValidators.
Public Member Functions
BaseOAuthValidator (IHttpClientFactory httpClientFactory, IAssemblyInformationProvider assemblyInformationProvider, ILogger< BaseOAuthValidator > logger, OAuthConfiguration oAuthConfiguration)
Initializes a new instance of the GenericOAuthValidator class.
abstract Task< OAuthProviderInfo > GetProviderInfo (CancellationToken cancellationToken)
Gets the OAuthProvider of validator.
abstract Task< string > ValidateResponseCode (string code, CancellationToken cancellationToken)
Validate a given OAuth response code .
Protected Member Functions
HttpClient CreateHttpClient ()
Create a new configured HttpClient.
Static Protected Member Functions
static JsonSerializerSettings SerializerSettings ()
Gets JsonSerializerSettings that should be used.
Properties
abstract OAuthProvider Provider [get]
ILogger< BaseOAuthValidator > Logger [get]
The ILogger for the BaseOAuthValidator.
OAuthConfiguration OAuthConfiguration [get]
The OAuthConfiguration for the BaseOAuthValidator.
Properties inherited from Tgstation.Server.Host.Security.OAuth.IOAuthValidator
OAuthProvider Provider [get]
The OAuthProvider this validator is for.
Private Attributes
readonly IHttpClientFactory httpClientFactory
The IHttpClientFactory for the BaseOAuthValidator.
readonly IAssemblyInformationProvider assemblyInformationProvider
The IAssemblyInformationProvider for the BaseOAuthValidator.
Detailed Description
Base class for IOAuthValidators.
Definition at line 19 of file BaseOAuthValidator.cs.
Constructor & Destructor Documentation
BaseOAuthValidator()
Tgstation.Server.Host.Security.OAuth.BaseOAuthValidator.BaseOAuthValidator (IHttpClientFactory httpClientFactory, IAssemblyInformationProvider assemblyInformationProvider, ILogger< BaseOAuthValidator > logger, OAuthConfiguration oAuthConfiguration)
Initializes a new instance of the GenericOAuthValidator class.
Parameters
httpClientFactory The value of httpClientFactory.
assemblyInformationProvider The value of assemblyInformationProvider.
logger The value of Logger.
oAuthConfiguration The value of OAuthConfiguration.
Definition at line 63 of file BaseOAuthValidator.cs.
         {
             this.httpClientFactory = httpClientFactory ?? throw new ArgumentNullException(nameof(httpClientFactory));
             this.assemblyInformationProvider = assemblyInformationProvider ?? throw new ArgumentNullException(nameof(assemblyInformationProvider));
             Logger = logger ?? throw new ArgumentNullException(nameof(logger));
             OAuthConfiguration = oAuthConfiguration ?? throw new ArgumentNullException(nameof(oAuthConfiguration));
         }
References Tgstation.Server.Host.Security.OAuth.BaseOAuthValidator.assemblyInformationProvider, Tgstation.Server.Host.Security.OAuth.BaseOAuthValidator.httpClientFactory, and Tgstation.Server.Host.Security.OAuth.BaseOAuthValidator.Logger.
Member Function Documentation
CreateHttpClient()
HttpClient Tgstation.Server.Host.Security.OAuth.BaseOAuthValidator.CreateHttpClient () protected
Create a new configured HttpClient.
Returns
A new configured HttpClient.
Definition at line 85 of file BaseOAuthValidator.cs.
         {
             var httpClient = httpClientFactory.CreateClient();
             try
             {
                 httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue(MediaTypeNames.Application.Json));
                 httpClient.DefaultRequestHeaders.UserAgent.Add(assemblyInformationProvider.ProductInfoHeaderValue);
                 return httpClient;
             }
             catch
             {
                 httpClient.Dispose();
                 throw;
             }
         }
References Tgstation.Server.Host.Security.OAuth.BaseOAuthValidator.assemblyInformationProvider, Tgstation.Server.Host.Security.OAuth.BaseOAuthValidator.httpClientFactory, and Tgstation.Server.Host.System.IAssemblyInformationProvider.ProductInfoHeaderValue.
Referenced by Tgstation.Server.Host.Security.OAuth.TGForumsOAuthValidator.GetProviderInfo(), Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.ValidateResponseCode(), and Tgstation.Server.Host.Security.OAuth.TGForumsOAuthValidator.ValidateResponseCode().
GetProviderInfo()
abstract Task<OAuthProviderInfo> Tgstation.Server.Host.Security.OAuth.BaseOAuthValidator.GetProviderInfo (CancellationToken cancellationToken) pure virtual
Gets the OAuthProvider of validator.
Implements Tgstation.Server.Host.Security.OAuth.IOAuthValidator.
Implemented in Tgstation.Server.Host.Security.OAuth.TGForumsOAuthValidator, and Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.
SerializerSettings()
static JsonSerializerSettings Tgstation.Server.Host.Security.OAuth.BaseOAuthValidator.SerializerSettings () static protected
Gets JsonSerializerSettings that should be used.
Returns
A new JsonSerializerSettings object.
Referenced by Tgstation.Server.Host.Security.OAuth.TGForumsOAuthValidator.GetProviderInfo(), Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.ValidateResponseCode(), and Tgstation.Server.Host.Security.OAuth.TGForumsOAuthValidator.ValidateResponseCode().
ValidateResponseCode()
abstract Task<string> Tgstation.Server.Host.Security.OAuth.BaseOAuthValidator.ValidateResponseCode (string code, CancellationToken cancellationToken) pure virtual
Validate a given OAuth response code .
Implements Tgstation.Server.Host.Security.OAuth.IOAuthValidator.
Implemented in Tgstation.Server.Host.Security.OAuth.TGForumsOAuthValidator, and Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.
Member Data Documentation
assemblyInformationProvider
readonly IAssemblyInformationProvider Tgstation.Server.Host.Security.OAuth.BaseOAuthValidator.assemblyInformationProvider private
The IAssemblyInformationProvider for the BaseOAuthValidator.
Definition at line 42 of file BaseOAuthValidator.cs.
Referenced by Tgstation.Server.Host.Security.OAuth.BaseOAuthValidator.BaseOAuthValidator(), and Tgstation.Server.Host.Security.OAuth.BaseOAuthValidator.CreateHttpClient().
httpClientFactory
readonly IHttpClientFactory Tgstation.Server.Host.Security.OAuth.BaseOAuthValidator.httpClientFactory private
The IHttpClientFactory for the BaseOAuthValidator.
Definition at line 37 of file BaseOAuthValidator.cs.
Referenced by Tgstation.Server.Host.Security.OAuth.BaseOAuthValidator.BaseOAuthValidator(), and Tgstation.Server.Host.Security.OAuth.BaseOAuthValidator.CreateHttpClient().
Property Documentation
Logger
ILogger<BaseOAuthValidator> Tgstation.Server.Host.Security.OAuth.BaseOAuthValidator.Logger get protected
The ILogger for the BaseOAuthValidator.
Definition at line 27 of file BaseOAuthValidator.cs.
 { get; }
Referenced by Tgstation.Server.Host.Security.OAuth.BaseOAuthValidator.BaseOAuthValidator(), Tgstation.Server.Host.Security.OAuth.TGForumsOAuthValidator.GetProviderInfo(), Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.ValidateResponseCode(), and Tgstation.Server.Host.Security.OAuth.TGForumsOAuthValidator.ValidateResponseCode().
OAuthConfiguration
OAuthConfiguration Tgstation.Server.Host.Security.OAuth.BaseOAuthValidator.OAuthConfiguration get protected
The OAuthConfiguration for the BaseOAuthValidator.
Definition at line 32 of file BaseOAuthValidator.cs.
 { get; }
Provider
abstract OAuthProvider Tgstation.Server.Host.Security.OAuth.BaseOAuthValidator.Provider get
Definition at line 22 of file BaseOAuthValidator.cs.
 { get; }
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Security/OAuth/BaseOAuthValidator.cs