tgstation-server: TGCommandLine.CLICommand Class Reference
TGCommandLine.CLICommand Class Reference
Public Member Functions
CLICommand (Interface I)
override void PrintHelp ()
Prints usage text of the Command to the invoker
Public Member Functions inherited from TGServiceInterface.RootCommand
override void PrintHelp ()
Prints usage text of the Command to the invoker
override string GetHelpText ()
Override to add usage text to the Command
Public Member Functions inherited from TGServiceInterface.Command
virtual ExitCode DoRun (IList< string > parameters)
Caller of Run(IList<string>), can be used to modify the root behaviour of the Command
virtual string GetArgumentString ()
Override to add argument text to the Command Format is <required> <arguments> [optional] [arguments]
Additional Inherited Members
Public Types inherited from TGServiceInterface.Command
enum ExitCode : int { ExitCode.Normal = 0, ExitCode.ConnectionError = 1, ExitCode.BadCommand = 2, ExitCode.ServerError = 3 }
Exit codes for Commands
Static Public Attributes inherited from TGServiceInterface.RootCommand
static bool PrintHelpList = false
If set to a multiline, detailed list of Commands will be printed. Otherwise a singleline list of Commands will be printed
Static Public Attributes inherited from TGServiceInterface.Command
static ThreadLocal< Action< string > > OutputProcVar = new ThreadLocal<Action<string>>()
Proc that will show a message to the Command invoker. Do not call directly, use OutputProc(string) instead
Protected Member Functions inherited from TGServiceInterface.RootCommand
override ExitCode Run (IList< string > parameters)
Forward parameters to commands further down the tree
Static Protected Member Functions inherited from TGServiceInterface.Command
static void OutputProc (string message)
Write output to the Command invoker
Properties inherited from TGServiceInterface.RootCommand
Command[] Children [get, protected set]
Commands further down the tree from this one. Set in Constructor
Properties inherited from TGServiceInterface.Command
string Keyword [get, protected set]
The text that invokes this Command. Set in constructor
int RequiredParameters [get, protected set]
The number of parameters this Command requires. Set in Constructor
Detailed Description
Definition at line 8 of file RootCommands.cs.
Constructor & Destructor Documentation
TGCommandLine.CLICommand.CLICommand (Interface I)
Definition at line 10 of file RootCommands.cs.
References TGServiceInterface.RootCommand.Children, TGServiceInterface.Interface.ConnectionStatus(), and TGServiceInterface.Interface.ConnectToInstance().
         {
             var tmp = new List<Command> { new UpdateCommand(), new TestmergeCommand(), new RepoCommand(), new BYONDCommand(), new DMCommand(), new DDCommand(), new ConfigCommand(), new IRCCommand(), new DiscordCommand(), new AutoUpdateCommand(), new SetAutoUpdateCommand() };
             if (I.ConnectToInstance().HasFlag(ConnectivityLevel.Administrator))
                 tmp.Add(new AdminCommand());
             if (I.ConnectionStatus().HasFlag(ConnectivityLevel.Administrator))
                 tmp.Add(new ServiceCommand());
             Children = tmp.ToArray();
         }
Member Function Documentation
override void TGCommandLine.CLICommand.PrintHelp () virtual
Prints usage text of the Command to the invoker
Reimplemented from TGServiceInterface.Command.
Definition at line 20 of file RootCommands.cs.
References TGServiceInterface.Command.OutputProc().
         {
             OutputProc("/tg/station 13 Server Command Line");
             base.PrintHelp();
         }
The documentation for this class was generated from the following file:
TGCommandLine/RootCommands.cs