tgstation-server: Tgstation.Server.Client.GraphQL.GraphQLServerClientFactory Class Reference
Tgstation.Server.Client.GraphQL.GraphQLServerClientFactory Class Reference sealed
Public Member Functions
GraphQLServerClientFactory (IRestServerClientFactory restClientFactory)
Initializes a new instance of the GraphQLServerClientFactory class.
ValueTask< IAuthenticatedGraphQLServerClient > CreateFromLogin (Uri host, string username, string password, bool attemptLoginRefresh=true, CancellationToken cancellationToken=default)
Create a IGraphQLServerClient using a password login.
Parameters
host The URL to access TGS.
username The username to for the IGraphQLServerClient.
password The password for the IGraphQLServerClient.
attemptLoginRefresh Attempt to refresh the received bearer token when it expires or becomes invalid. username and password will be stored in memory if this is true.
cancellationToken Optional CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a new IAuthenticatedGraphQLServerClient.
Exceptions
AuthenticationException Thrown when authentication fails.
ValueTask< IAuthenticatedGraphQLServerClient > CreateFromOAuth (Uri host, string oAuthCode, OAuthProvider oAuthProvider, CancellationToken cancellationToken=default)
Create a IGraphQLServerClient using an OAuth login.
Parameters
host The URL to access TGS.
oAuthCode The OAuth code used to complete the flow.
oAuthProvider The OAuthProvider.
cancellationToken Optional CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a new IAuthenticatedGraphQLServerClient.
Exceptions
AuthenticationException Thrown when authentication fails.
IAuthenticatedGraphQLServerClient CreateFromToken (Uri host, string token)
Create a IRestServerClient.
Parameters
host The URL to access TGS.
token The bearer token to access the API with.
Returns
A new IGraphQLServerClient.
IGraphQLServerClient CreateUnauthenticated (Uri host)
Create an unauthenticated IGraphQLServerClient.
Parameters
host The Uri of tgstation-server.
Returns
A new IGraphQLServerClient.
Private Member Functions
async ValueTask< IAuthenticatedGraphQLServerClient > CreateWithAuthCall (Uri host, AuthenticationHeaderValue initialCredentials, OAuthProvider? oAuthProvider, bool attemptLoginRefresh, CancellationToken cancellationToken)
Create an IAuthenticatedGraphQLServerClient from a remote login call.
IRestServerClient CreateAuthenticatedTransferClient (Uri host, string bearer)
Create a ITransferClient for a given host and bearer token.
Static Private Member Functions
static ServiceProvider SetupServiceProvider (Uri host, bool addAuthorizationHandler, AuthenticationHeaderValue? headerOverride=null, OAuthProvider? oAuthProvider=null)
Sets up a ServiceProvider for providing the IGraphQLClient.
Private Attributes
readonly IRestServerClientFactory restClientFactory
The IRestServerClientFactory for the GraphQLServerClientFactory.
Detailed Description
Definition at line 20 of file GraphQLServerClientFactory.cs.
Constructor & Destructor Documentation
GraphQLServerClientFactory()
Tgstation.Server.Client.GraphQL.GraphQLServerClientFactory.GraphQLServerClientFactory (IRestServerClientFactory restClientFactory)
Initializes a new instance of the GraphQLServerClientFactory class.
Parameters
restClientFactory The value of restClientFactory.
Definition at line 70 of file GraphQLServerClientFactory.cs.
        {
            this.restClientFactory = restClientFactory ?? throw new ArgumentNullException(nameof(restClientFactory));
        }
References Tgstation.Server.Client.GraphQL.GraphQLServerClientFactory.restClientFactory.
Member Function Documentation
CreateAuthenticatedTransferClient()
IRestServerClient Tgstation.Server.Client.GraphQL.GraphQLServerClientFactory.CreateAuthenticatedTransferClient (Uri host, string bearer) private
Create a ITransferClient for a given host and bearer token.
Parameters
host The URL to access TGS.
bearer The bearer token to access the API with.
Returns
A new IRestServerClient.
Definition at line 200 of file GraphQLServerClientFactory.cs.
        {
            var restClient = restClientFactory.CreateFromToken(
                host,
                new TokenResponse
                {
                    Bearer = bearer,
                });
            return restClient;
        }
References Tgstation.Server.Client.IRestServerClientFactory.CreateFromToken(), and Tgstation.Server.Client.GraphQL.GraphQLServerClientFactory.restClientFactory.
Referenced by Tgstation.Server.Client.GraphQL.GraphQLServerClientFactory.CreateFromToken(), and Tgstation.Server.Client.GraphQL.GraphQLServerClientFactory.CreateWithAuthCall().
CreateFromLogin()
ValueTask< IAuthenticatedGraphQLServerClient > Tgstation.Server.Client.GraphQL.GraphQLServerClientFactory.CreateFromLogin (Uri host, string username, string password, bool attemptLoginRefresh = true, CancellationToken cancellationToken = default)
Create a IGraphQLServerClient using a password login.
Parameters
host The URL to access TGS.
username The username to for the IGraphQLServerClient.
password The password for the IGraphQLServerClient.
attemptLoginRefresh Attempt to refresh the received bearer token when it expires or becomes invalid. username and password will be stored in memory if this is true.
cancellationToken Optional CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a new IAuthenticatedGraphQLServerClient.
Exceptions
AuthenticationException Thrown when authentication fails.
Implements Tgstation.Server.Client.GraphQL.IGraphQLServerClientFactory.
Definition at line 76 of file GraphQLServerClientFactory.cs.
        {
            var basicCredentials = new AuthenticationHeaderValue(
                ApiHeaders.BasicAuthenticationScheme,
                Convert.ToBase64String(
                    Encoding.UTF8.GetBytes($"{username}:{password}")));
            return CreateWithAuthCall(
                host,
                basicCredentials,
                null,
                attemptLoginRefresh,
                cancellationToken);
        }
References Tgstation.Server.Api.ApiHeaders.BasicAuthenticationScheme, and Tgstation.Server.Client.GraphQL.GraphQLServerClientFactory.CreateWithAuthCall().
CreateFromOAuth()
ValueTask< IAuthenticatedGraphQLServerClient > Tgstation.Server.Client.GraphQL.GraphQLServerClientFactory.CreateFromOAuth (Uri host, string oAuthCode, OAuthProvider oAuthProvider, CancellationToken cancellationToken = default)
Create a IGraphQLServerClient using an OAuth login.
Parameters
host The URL to access TGS.
oAuthCode The OAuth code used to complete the flow.
oAuthProvider The OAuthProvider.
cancellationToken Optional CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a new IAuthenticatedGraphQLServerClient.
Exceptions
AuthenticationException Thrown when authentication fails.
Implements Tgstation.Server.Client.GraphQL.IGraphQLServerClientFactory.
Definition at line 92 of file GraphQLServerClientFactory.cs.
        {
            var oAuthCredentials = new AuthenticationHeaderValue(
                ApiHeaders.OAuthAuthenticationScheme,
                oAuthCode);
            return CreateWithAuthCall(
                host,
                oAuthCredentials,
                oAuthProvider,
                false,
                cancellationToken);
        }
References Tgstation.Server.Client.GraphQL.GraphQLServerClientFactory.CreateWithAuthCall(), and Tgstation.Server.Api.ApiHeaders.OAuthAuthenticationScheme.
CreateFromToken()
IAuthenticatedGraphQLServerClient Tgstation.Server.Client.GraphQL.GraphQLServerClientFactory.CreateFromToken (Uri host, string token)
Create a IRestServerClient.
Parameters
host The URL to access TGS.
token The bearer token to access the API with.
Returns
A new IGraphQLServerClient.
Implements Tgstation.Server.Client.GraphQL.IGraphQLServerClientFactory.
Definition at line 107 of file GraphQLServerClientFactory.cs.
        {
            var authenticationHeader = new AuthenticationHeaderValue(
                ApiHeaders.BearerAuthenticationScheme,
                token);
            var serviceProvider = SetupServiceProvider(
                host,
                true,
                authenticationHeader);
            return new AuthenticatedGraphQLServerClient(
                serviceProvider.GetRequiredService<IGraphQLClient>(),
                serviceProvider,
                serviceProvider.GetRequiredService<ILogger<GraphQLServerClient>>(),
                CreateAuthenticatedTransferClient(host, token));
        }
References Tgstation.Server.Api.ApiHeaders.BearerAuthenticationScheme, Tgstation.Server.Client.GraphQL.GraphQLServerClientFactory.CreateAuthenticatedTransferClient(), and Tgstation.Server.Client.GraphQL.GraphQLServerClientFactory.SetupServiceProvider().
CreateUnauthenticated()
IGraphQLServerClient Tgstation.Server.Client.GraphQL.GraphQLServerClientFactory.CreateUnauthenticated (Uri host)
Create an unauthenticated IGraphQLServerClient.
Parameters
host The Uri of tgstation-server.
Returns
A new IGraphQLServerClient.
Implements Tgstation.Server.Client.GraphQL.IGraphQLServerClientFactory.
Definition at line 126 of file GraphQLServerClientFactory.cs.
        {
            var serviceProvider = SetupServiceProvider(host, false);
            return new GraphQLServerClient(
                serviceProvider.GetRequiredService<IGraphQLClient>(),
                serviceProvider,
                serviceProvider.GetRequiredService<ILogger<GraphQLServerClient>>());
        }
References Tgstation.Server.Client.GraphQL.GraphQLServerClientFactory.SetupServiceProvider().
CreateWithAuthCall()
async ValueTask< IAuthenticatedGraphQLServerClient > Tgstation.Server.Client.GraphQL.GraphQLServerClientFactory.CreateWithAuthCall (Uri host, AuthenticationHeaderValue initialCredentials, OAuthProvider? oAuthProvider, bool attemptLoginRefresh, CancellationToken cancellationToken) private
Create an IAuthenticatedGraphQLServerClient from a remote login call.
Parameters
host The URL to access TGS.
initialCredentials The initial AuthenticationHeaderValue to use to login.
oAuthProvider The OAuthProvider, if any.
attemptLoginRefresh If the client should attempt to renew its sessions with the initialCredentials .
cancellationToken Optional CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a new IAuthenticatedGraphQLServerClient.
Exceptions
AuthenticationException Thrown when authentication fails.
Definition at line 146 of file GraphQLServerClientFactory.cs.
        {
            var serviceProvider = SetupServiceProvider(
                host,
                true,
                oAuthProvider: oAuthProvider);
            try
            {
                var client = serviceProvider.GetRequiredService<IGraphQLClient>();
                IOperationResult<ILoginResult> result;
                var previousAuthHeader = AuthorizationMessageHandler.Header.Value;
                AuthorizationMessageHandler.Header.Value = initialCredentials;
                try
                {
                    result = await client.Login.ExecuteAsync(cancellationToken).ConfigureAwait(false);
                }
                finally
                {
                    AuthorizationMessageHandler.Header.Value = previousAuthHeader;
                }
                var serverClient = new AuthenticatedGraphQLServerClient(
                    client,
                    serviceProvider,
                    serviceProvider.GetRequiredService<ILogger<GraphQLServerClient>>(),
                    newHeader => AuthorizationMessageHandler.Header.Value = newHeader,
                    attemptLoginRefresh ? initialCredentials : null,
                    result,
                    bearer => CreateAuthenticatedTransferClient(host, bearer));
                await Task.Yield();
                return serverClient;
            }
            catch
            {
                await serviceProvider.DisposeAsync().ConfigureAwait(false);
                throw;
            }
        }
References Tgstation.Server.Client.GraphQL.GraphQLServerClientFactory.CreateAuthenticatedTransferClient(), Tgstation.Server.Client.GraphQL.AuthenticatedGraphQLServerClient.DisposeAsync(), Tgstation.Server.Client.GraphQL.AuthorizationMessageHandler.Header, and Tgstation.Server.Client.GraphQL.GraphQLServerClientFactory.SetupServiceProvider().
Referenced by Tgstation.Server.Client.GraphQL.GraphQLServerClientFactory.CreateFromLogin(), and Tgstation.Server.Client.GraphQL.GraphQLServerClientFactory.CreateFromOAuth().
SetupServiceProvider()
static ServiceProvider Tgstation.Server.Client.GraphQL.GraphQLServerClientFactory.SetupServiceProvider (Uri host, bool addAuthorizationHandler, AuthenticationHeaderValue? headerOverride = null, OAuthProvider? oAuthProvider = null) static private
Sets up a ServiceProvider for providing the IGraphQLClient.
Parameters
host The Uri of the target tgstation-server.
addAuthorizationHandler If the AuthorizationMessageHandler should be configured.
headerOverride The AuthenticationHeaderValue override for the AuthorizationMessageHandler.
oAuthProvider The OAuthProvider, if any.
Returns
A new ServiceProvider.
Definition at line 35 of file GraphQLServerClientFactory.cs.
        {
            var serviceCollection = new ServiceCollection();
            var clientBuilder = serviceCollection
                .AddGraphQLClient();
            var graphQLEndpoint = new Uri(host, Routes.GraphQL);
            clientBuilder.ConfigureHttpClient(
                client =>
                {
                    client.BaseAddress = graphQLEndpoint;
                    client.DefaultRequestHeaders.Add(ApiHeaders.ApiVersionHeader, $"Tgstation.Server.Api/{ApiHeaders.Version.Semver()}");
                    if (oAuthProvider.HasValue)
                    {
                        client.DefaultRequestHeaders.Add(ApiHeaders.OAuthProviderHeader, oAuthProvider.ToString());
                    }
                },
                clientBuilder =>
                {
                    if (addAuthorizationHandler)
                        clientBuilder.AddHttpMessageHandler(() => new AuthorizationMessageHandler(headerOverride));
                });
            serviceCollection.AddSerializer<UnsignedIntSerializer>();
            serviceCollection.AddSerializer<SemverSerializer>();
            serviceCollection.AddSerializer<JwtSerializer>();
            return serviceCollection.BuildServiceProvider();
        }
References Tgstation.Server.Api.ApiHeaders.ApiVersionHeader, Tgstation.Server.Api.Routes.GraphQL, and Tgstation.Server.Api.ApiHeaders.OAuthProviderHeader.
Referenced by Tgstation.Server.Client.GraphQL.GraphQLServerClientFactory.CreateFromToken(), Tgstation.Server.Client.GraphQL.GraphQLServerClientFactory.CreateUnauthenticated(), and Tgstation.Server.Client.GraphQL.GraphQLServerClientFactory.CreateWithAuthCall().
Member Data Documentation
restClientFactory
readonly IRestServerClientFactory Tgstation.Server.Client.GraphQL.GraphQLServerClientFactory.restClientFactory private
The IRestServerClientFactory for the GraphQLServerClientFactory.
Definition at line 25 of file GraphQLServerClientFactory.cs.
Referenced by Tgstation.Server.Client.GraphQL.GraphQLServerClientFactory.CreateAuthenticatedTransferClient(), and Tgstation.Server.Client.GraphQL.GraphQLServerClientFactory.GraphQLServerClientFactory().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Client.GraphQL/GraphQLServerClientFactory.cs