tgstation-server: Tgstation.Server.Host.Controllers.ByondController Class Reference
Tgstation.Server.Host.Controllers.ByondController Class Reference
Controller for managing BYOND installations.
Public Member Functions
ByondController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ILogger< ByondController > logger, IInstanceManager instanceManager, IJobManager jobManager, IFileTransferTicketProvider fileTransferService, IApiHeadersProvider apiHeadersProvider)
Initializes a new instance of the ByondController class.
ValueTask< IActionResult > Read ()
Gets the active ByondResponse.Version.
ValueTask< IActionResult > List ([FromQuery] int? page, [FromQuery] int? pageSize, CancellationToken cancellationToken)
Lists installed ByondResponse.Versions.
async ValueTask< IActionResult > Update ([FromBody] ByondVersionRequest model, CancellationToken cancellationToken)
Changes the active BYOND version to the one specified in a given model .
async ValueTask< IActionResult > Delete ([FromBody] ByondVersionDeleteRequest model, CancellationToken cancellationToken)
Attempts to delete the BYOND version specified in a given model from the instance.
Public Member Functions inherited from Tgstation.Server.Host.Controllers.ApiControllerBase
sealed override async Task OnActionExecutionAsync (ActionExecutingContext context, ActionExecutionDelegate next)
Static Private Member Functions
static Version NormalizeVersion (Version version)
Remove the Version.Build from a given version if present.
Private Attributes
readonly IJobManager jobManager
The IJobManager for the ByondController.
readonly IFileTransferTicketProvider fileTransferService
The IFileTransferTicketProvider for the ByondController.
Additional Inherited Members
Protected Member Functions inherited from Tgstation.Server.Host.Controllers.InstanceRequiredController
InstanceRequiredController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ILogger< InstanceRequiredController > logger, IInstanceManager instanceManager, IApiHeadersProvider apiHeaders)
Initializes a new instance of the InstanceRequiredController class.
Protected Member Functions inherited from Tgstation.Server.Host.Controllers.ComponentInterfacingController
ComponentInterfacingController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ILogger< ComponentInterfacingController > logger, IInstanceManager instanceManager, IApiHeadersProvider apiHeaders, bool useInstanceRequestHeader)
Initializes a new instance of the ComponentInterfacingController class.
override async ValueTask< IActionResult > ValidateRequest (CancellationToken cancellationToken)
Performs validation a request.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in an appropriate IActionResult on validation failure, null otherwise.
bool ValidateInstanceOnlineStatus (Api.Models.Instance metadata)
Corrects discrepencies between the Api.Models.Instance.Online status of IInstances in the database vs the service.
async ValueTask< IActionResult > WithComponentInstance (Func< IInstanceCore, ValueTask< IActionResult > > action, Models.Instance instance=null)
Run a given action with the relevant IInstance.
Protected Member Functions inherited from Tgstation.Server.Host.Controllers.ApiController
ApiController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, IApiHeadersProvider apiHeadersProvider, ILogger< ApiController > logger, bool requireHeaders)
Initializes a new instance of the ApiController class.
override async ValueTask< IActionResult > HookExecuteAction (Func< Task > executeAction, CancellationToken cancellationToken)
Hook for executing a request.
Parameters
executeAction A Func<TResult> that should be invoked and its response awaited to continue normal execution of the request. Should NOT be called if this method returns a non-null value.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in an IActionResult that, if not null, is executed.
new NotFoundObjectResult NotFound ()
Generic 404 response.
new ObjectResult Unauthorized ()
Generic 401 response.
ObjectResult RequiresPosixSystemIdentity (NotImplementedException ex)
Generic 501 response.
StatusCodeResult StatusCode (HttpStatusCode statusCode)
Strongly type calls to ControllerBase.StatusCode(int).
ObjectResult Created (object payload)
Generic 201 response with a given payload .
ObjectResult RateLimit (RateLimitExceededException rateLimitException)
429 response for a given rateLimitException .
virtual ValueTask< IActionResult > ValidateRequest (CancellationToken cancellationToken)
Performs validation a request.
IActionResult HeadersIssue (HeadersException headersException)
Response for missing/Invalid headers.
ValueTask< IActionResult > Paginated< TModel > (Func< ValueTask< PaginatableResult< TModel > > > queryGenerator, Func< TModel, ValueTask > resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
ValueTask< IActionResult > Paginated< TModel, TApiModel > (Func< ValueTask< PaginatableResult< TModel > > > queryGenerator, Func< TApiModel, ValueTask > resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
virtual async ValueTask< IActionResult > HookExecuteAction (Func< Task > executeAction, CancellationToken cancellationToken)
Hook for executing a request.
Properties inherited from Tgstation.Server.Host.Controllers.ComponentInterfacingController
IInstanceOperations InstanceOperations [get]
Access the IInstanceOperations instance.
Properties inherited from Tgstation.Server.Host.Controllers.ApiController
ApiHeaders ApiHeaders [get]
The Api.ApiHeaders for the operation.
IApiHeadersProvider ApiHeadersProvider [get]
The IApiHeadersProvider containing value of ApiHeaders.
IDatabaseContext DatabaseContext [get]
The IDatabaseContext for the operation.
IAuthenticationContext AuthenticationContext [get]
The IAuthenticationContext for the operation.
ILogger< ApiController > Logger [get]
The ILogger for the ApiController.
Models.Instance Instance [get]
The Instance for the operation.
Detailed Description
Controller for managing BYOND installations.
Definition at line 31 of file ByondController.cs.
Constructor & Destructor Documentation
ByondController()
Tgstation.Server.Host.Controllers.ByondController.ByondController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ILogger< ByondController > logger, IInstanceManager instanceManager, IJobManager jobManager, IFileTransferTicketProvider fileTransferService, IApiHeadersProvider apiHeadersProvider)
Initializes a new instance of the ByondController class.
Parameters
databaseContext The IDatabaseContext for the InstanceRequiredController.
authenticationContext The IAuthenticationContext for the InstanceRequiredController.
logger The ILogger for the InstanceRequiredController.
instanceManager The IInstanceManager for the InstanceRequiredController.
jobManager The value of jobManager.
fileTransferService The value of fileTransferService.
apiHeadersProvider The IApiHeadersProvider for the InstanceRequiredController.
Definition at line 60 of file ByondController.cs.
            : base(
                  databaseContext,
                  authenticationContext,
                  logger,
                  instanceManager,
                  apiHeadersProvider)
        {
            this.jobManager = jobManager ?? throw new ArgumentNullException(nameof(jobManager));
            this.fileTransferService = fileTransferService ?? throw new ArgumentNullException(nameof(fileTransferService));
        }
References Tgstation.Server.Host.Controllers.ByondController.fileTransferService, and Tgstation.Server.Host.Controllers.ByondController.jobManager.
Member Function Documentation
Delete()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.ByondController.Delete ([FromBody] ByondVersionDeleteRequest model, CancellationToken cancellationToken)
Attempts to delete the BYOND version specified in a given model from the instance.
Parameters
model The ByondVersionDeleteRequest containing the Version to delete.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult for the operation.
<response code="202">Created Job to delete target version successfully.</response> <response code="409">Attempted to delete the active BYOND Version.</response> <response code="410">The ByondVersionDeleteRequest.Version specified was not installed.</response>
Definition at line 274 of file ByondController.cs.
        {
            ArgumentNullException.ThrowIfNull(model);
            if (model.Version == null
                || model.Version.Revision != -1)
                return BadRequest(new ErrorMessageResponse(ErrorCode.ModelValidationFailure));
            var version = NormalizeVersion(model.Version);
            var notInstalledResponse = await WithComponentInstance(
                instance =>
                {
                    var byondManager = instance.ByondManager;
                    if (version == byondManager.ActiveVersion)
                        return ValueTask.FromResult<IActionResult>(
                            Conflict(new ErrorMessageResponse(ErrorCode.ByondCannotDeleteActiveVersion)));
                    var versionNotInstalled = !byondManager.InstalledVersions.Any(x => x == version);
                    return ValueTask.FromResult<IActionResult>(
                        versionNotInstalled
                            ? this.Gone()
                            : null);
                });
            if (notInstalledResponse != null)
                return notInstalledResponse;
            var isCustomVersion = version.Build != -1;
            // run the install through the job manager
            var job = Job.Create(JobCode.ByondDelete, AuthenticationContext.User, Instance, isCustomVersion ? ByondRights.InstallOfficialOrChangeActiveVersion : ByondRights.InstallCustomVersion);
            job.Description += $" {version}";
            await jobManager.RegisterOperation(
                job,
                (instanceCore, databaseContextFactory, job, progressReporter, jobCancellationToken)
                    => instanceCore.ByondManager.DeleteVersion(progressReporter, version, jobCancellationToken),
                cancellationToken);
            var apiResponse = job.ToApi();
            return Accepted(apiResponse);
        }
References Tgstation.Server.Host.Models.Job.Create(), Tgstation.Server.Host.Models.Job.ToApi(), and Tgstation.Server.Host.Security.AuthenticationContext.User.
List()
ValueTask< IActionResult > Tgstation.Server.Host.Controllers.ByondController.List ([FromQuery] int? page, [FromQuery] int? pageSize, CancellationToken cancellationToken)
Lists installed ByondResponse.Versions.
Parameters
page The current page.
pageSize The page size.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult for the operation.
<response code="200">Retrieved version information successfully.</response>
NormalizeVersion()
static Version Tgstation.Server.Host.Controllers.ByondController.NormalizeVersion (Version version) static private
Remove the Version.Build from a given version if present.
Parameters
version The Version to normalize.
Returns
The normalized Version. May be a reference to version .
Referenced by Tgstation.Server.Host.Controllers.ByondController.Update().
Read()
ValueTask< IActionResult > Tgstation.Server.Host.Controllers.ByondController.Read ()
Gets the active ByondResponse.Version.
Returns
A ValueTask<TResult> resulting in the IActionResult for the operation.
<response code="200">Retrieved version information successfully.</response>
Update()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.ByondController.Update ([FromBody] ByondVersionRequest model, CancellationToken cancellationToken)
Changes the active BYOND version to the one specified in a given model .
Parameters
model The ByondVersionRequest containing the Version to switch to.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult for the operation.
<response code="200">Switched active version successfully.</response> <response code="202">Created Job to install and switch active version successfully.</response>
Definition at line 138 of file ByondController.cs.
        {
            ArgumentNullException.ThrowIfNull(model);
            var uploadingZip = model.UploadCustomZip == true;
            if (model.Version == null
                || model.Version.Revision != -1
                || (uploadingZip && model.Version.Build > 0))
                return BadRequest(new ErrorMessageResponse(ErrorCode.ModelValidationFailure));
            var version = NormalizeVersion(model.Version);
            var userByondRights = AuthenticationContext.InstancePermissionSet.ByondRights.Value;
            if ((!userByondRights.HasFlag(ByondRights.InstallOfficialOrChangeActiveVersion) && !uploadingZip)
                || (!userByondRights.HasFlag(ByondRights.InstallCustomVersion) && uploadingZip))
                return Forbid();
            // remove cruff fields
            var result = new ByondInstallResponse();
            return await WithComponentInstance(
                async instance =>
                {
                    var byondManager = instance.ByondManager;
                    var versionAlreadyInstalled = !uploadingZip && byondManager.InstalledVersions.Any(x => x == version);
                    if (versionAlreadyInstalled)
                    {
                        Logger.LogInformation(
                            "User ID {userId} changing instance ID {instanceId} BYOND version to {newByondVersion}",
                            AuthenticationContext.User.Id,
                            Instance.Id,
                            version);
                        try
{
                            await byondManager.ChangeVersion(null, version, null, false, cancellationToken);
                        }
                        catch (InvalidOperationException ex)
{
                            Logger.LogDebug(
                                ex,
                                "Race condition: BYOND version {version} uninstalled before we could switch to it. Creating install job instead...",
                                version);
                            versionAlreadyInstalled = false;
                        }
                    }
                    if (!versionAlreadyInstalled)
                    {
                        if (version.Build > 0)
                            return BadRequest(new ErrorMessageResponse(ErrorCode.ByondNonExistentCustomVersion));
                        Logger.LogInformation(
                            "User ID {userId} installing BYOND version to {newByondVersion} on instance ID {instanceId}",
                            AuthenticationContext.User.Id,
                            version,
                            Instance.Id);
                        // run the install through the job manager
                        var job = Job.Create(
                            uploadingZip
                                ? JobCode.ByondCustomInstall
                                : JobCode.ByondOfficialInstall,
                            AuthenticationContext.User,
                            Instance,
                            ByondRights.CancelInstall);
                        job.Description += $" {version}";
                        IFileUploadTicket fileUploadTicket = null;
                        if (uploadingZip)
                            fileUploadTicket = fileTransferService.CreateUpload(FileUploadStreamKind.None);
                        try
{
                            await jobManager.RegisterOperation(
                                job,
                                async (core, databaseContextFactory, paramJob, progressHandler, jobCancellationToken) =>
{
                                    Stream zipFileStream = null;
                                    if (fileUploadTicket != null)
                                        await using (fileUploadTicket)
{
                                            var uploadStream = await fileUploadTicket.GetResult(jobCancellationToken) ?? throw new JobException(ErrorCode.FileUploadExpired);
                                            zipFileStream = new MemoryStream();
                                            try
{
                                                await uploadStream.CopyToAsync(zipFileStream, jobCancellationToken);
                                            }
                                            catch
{
                                                await zipFileStream.DisposeAsync();
                                                throw;
                                            }
                                        }
                                    await using (zipFileStream)
                                        await core.ByondManager.ChangeVersion(
                                            progressHandler,
                                            version,
                                            zipFileStream,
                                            true,
                                            jobCancellationToken);
                                },
                                cancellationToken);
                            result.InstallJob = job.ToApi();
                            result.FileTicket = fileUploadTicket?.Ticket.FileTicket;
                        }
                        catch
{
                            if (fileUploadTicket != null)
                                await fileUploadTicket.DisposeAsync();
                            throw;
                        }
                    }
                    return result.InstallJob != null ? Accepted(result) : Json(result);
                });
        }
References Tgstation.Server.Api.Models.Internal.InstancePermissionSet.ByondRights, Tgstation.Server.Host.Models.Job.Create(), Tgstation.Server.Host.Transfer.IFileTransferTicketProvider.CreateUpload(), Tgstation.Server.Api.Models.Internal.Job.Description, Tgstation.Server.Host.Controllers.ByondController.fileTransferService, Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Host.Security.AuthenticationContext.InstancePermissionSet, Tgstation.Server.Host.Controllers.ApiController.Logger, Tgstation.Server.Host.Controllers.ByondController.NormalizeVersion(), Tgstation.Server.Host.Security.AuthenticationContext.User, and Tgstation.Server.Host.Controllers.ComponentInterfacingController.WithComponentInstance().
Member Data Documentation
fileTransferService
readonly IFileTransferTicketProvider Tgstation.Server.Host.Controllers.ByondController.fileTransferService private
The IFileTransferTicketProvider for the ByondController.
Definition at line 41 of file ByondController.cs.
Referenced by Tgstation.Server.Host.Controllers.ByondController.ByondController(), and Tgstation.Server.Host.Controllers.ByondController.Update().
jobManager
readonly IJobManager Tgstation.Server.Host.Controllers.ByondController.jobManager private
The IJobManager for the ByondController.
Definition at line 36 of file ByondController.cs.
Referenced by Tgstation.Server.Host.Controllers.ByondController.ByondController().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Controllers/ByondController.cs