tgstation-server: Tgstation.Server.Host.IO.BufferedFileStreamProvider Class Reference
Tgstation.Server.Host.IO.BufferedFileStreamProvider Class Reference
IFileStreamProvider that provides a ISeekableFileStreamProvider from an input Stream.
Public Member Functions
BufferedFileStreamProvider (Stream input)
Initializes a new instance of the BufferedFileStreamProvider class.
async ValueTask DisposeAsync ()
async ValueTask< Stream > GetResult (CancellationToken cancellationToken)
Gets the provided Stream. May be called multiple times, though cancelling any may cause all calls to be cancelled. All calls yield the same Stream reference.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the provided Stream.
The resulting Stream is owned by the IFileStreamProvider and is short lived unless otherwise specified. It should be buffered if it needs use outside the lifetime of the IFileStreamProvider.
async ValueTask< MemoryStream > GetOwnedResult (CancellationToken cancellationToken)
Gets the provided MemoryStream. May be called multiple times, though cancelling any may cause all calls to be cancelled.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the provided MemoryStream on success.
Task EnsureBuffered (CancellationToken cancellationToken)
Ensures the input Stream has been copied to the buffer.
ValueTask< MemoryStream > GetOwnedResult (CancellationToken cancellationToken)
Gets the provided MemoryStream. May be called multiple times, though cancelling any may cause all calls to be cancelled.
ValueTask< Stream > GetResult (CancellationToken cancellationToken)
Gets the provided Stream. May be called multiple times, though cancelling any may cause all calls to be cancelled. All calls yield the same Stream reference.
Properties
bool Disposed [get]
If the ISeekableFileStreamProvider has had global::System.IAsyncDisposable.DisposeAsync called on it.
Properties inherited from Tgstation.Server.Host.IO.ISeekableFileStreamProvider
bool Disposed [get]
If the ISeekableFileStreamProvider has had global::System.IAsyncDisposable.DisposeAsync called on it.
Private Member Functions
async ValueTask<(MemoryStream Stream, long StreamLength)> GetResultInternal (CancellationToken cancellationToken)
Gets the shared MemoryStream and its Stream.Length.
Private Attributes
readonly Stream input
The original input Stream must remain valid for the lifetime of the BufferedFileStreamProvider or until GetResult(CancellationToken) first returns.
readonly SemaphoreSlim semaphore
The SemaphoreSlim used to synchronize writes to buffer.
volatile? MemoryStream buffer
The backing Stream.
volatile bool buffered
If buffer has been populated.
Detailed Description
IFileStreamProvider that provides a ISeekableFileStreamProvider from an input Stream.
Definition at line 13 of file BufferedFileStreamProvider.cs.
Constructor & Destructor Documentation
BufferedFileStreamProvider()
Tgstation.Server.Host.IO.BufferedFileStreamProvider.BufferedFileStreamProvider (Stream input)
Initializes a new instance of the BufferedFileStreamProvider class.
Parameters
input The value of input.
Definition at line 42 of file BufferedFileStreamProvider.cs.
        {
            this.input = input ?? throw new ArgumentNullException(nameof(input));
            semaphore = new SemaphoreSlim(1);
            try
            {
                buffer = new MemoryStream();
            }
            catch
            {
                semaphore.Dispose();
                throw;
            }
        }
References Tgstation.Server.Host.IO.BufferedFileStreamProvider.buffer, Tgstation.Server.Host.IO.BufferedFileStreamProvider.input, and Tgstation.Server.Host.IO.BufferedFileStreamProvider.semaphore.
Member Function Documentation
DisposeAsync()
async ValueTask Tgstation.Server.Host.IO.BufferedFileStreamProvider.DisposeAsync ()
Definition at line 59 of file BufferedFileStreamProvider.cs.
        {
            MemoryStream? localBuffer;
            lock (semaphore)
            {
                localBuffer = buffer;
                if (localBuffer == null)
                    return;
                // important to drop the reference so it can properly GC
                // The implementation of MemoryStream doesn't fucking do this for some reason
                buffer = null;
                buffered = true;
            }
            var bufferDispose = localBuffer.DisposeAsync();
            semaphore.Dispose();
            await bufferDispose;
        }
References Tgstation.Server.Host.IO.BufferedFileStreamProvider.buffer, Tgstation.Server.Host.IO.BufferedFileStreamProvider.buffered, and Tgstation.Server.Host.IO.BufferedFileStreamProvider.semaphore.
EnsureBuffered()
Task Tgstation.Server.Host.IO.BufferedFileStreamProvider.EnsureBuffered (CancellationToken cancellationToken)
Ensures the input Stream has been copied to the buffer.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
GetOwnedResult()
async ValueTask< MemoryStream > Tgstation.Server.Host.IO.BufferedFileStreamProvider.GetOwnedResult (CancellationToken cancellationToken)
Gets the provided MemoryStream. May be called multiple times, though cancelling any may cause all calls to be cancelled.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the provided MemoryStream on success.
Implements Tgstation.Server.Host.IO.ISeekableFileStreamProvider.
Definition at line 87 of file BufferedFileStreamProvider.cs.
        {
            var (sharedStream, length) = await GetResultInternal(cancellationToken);
            return new MemoryStream(sharedStream.GetBuffer(), 0, (int)length, false, true);
        }
References Tgstation.Server.Host.IO.BufferedFileStreamProvider.GetResultInternal().
GetResult()
async ValueTask< Stream > Tgstation.Server.Host.IO.BufferedFileStreamProvider.GetResult (CancellationToken cancellationToken)
Gets the provided Stream. May be called multiple times, though cancelling any may cause all calls to be cancelled. All calls yield the same Stream reference.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the provided Stream.
The resulting Stream is owned by the IFileStreamProvider and is short lived unless otherwise specified. It should be buffered if it needs use outside the lifetime of the IFileStreamProvider.
Implements Tgstation.Server.Host.IO.IFileStreamProvider.
Definition at line 80 of file BufferedFileStreamProvider.cs.
        {
            var (sharedStream, _) = await GetResultInternal(cancellationToken);
            return sharedStream;
        }
References Tgstation.Server.Host.IO.BufferedFileStreamProvider.GetResultInternal().
GetResultInternal()
async ValueTask<(MemoryStream Stream, long StreamLength)> Tgstation.Server.Host.IO.BufferedFileStreamProvider.GetResultInternal (CancellationToken cancellationToken) private
Gets the shared MemoryStream and its Stream.Length.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in buffer and its Stream.Length.
Definition at line 105 of file BufferedFileStreamProvider.cs.
        {
            if (!buffered)
                using (await SemaphoreSlimContext.Lock(semaphore, cancellationToken))
                    if (!buffered)
                    {
                        MemoryStream localBuffer;
                        lock (semaphore)
                            localBuffer = buffer ?? throw new ObjectDisposedException(nameof(BufferedFileStreamProvider));
                        await input.CopyToAsync(localBuffer, cancellationToken);
                        localBuffer.Seek(0, SeekOrigin.Begin);
                        buffered = true;
                        return (Stream: localBuffer, StreamLength: localBuffer.Length);
                    }
            lock (semaphore)
            {
                var localBuffer = buffer ?? throw new ObjectDisposedException(nameof(BufferedFileStreamProvider));
                return (
                    Stream: localBuffer,
                    StreamLength: localBuffer.Length);
            }
        }
References Tgstation.Server.Host.IO.BufferedFileStreamProvider.buffer, Tgstation.Server.Host.IO.BufferedFileStreamProvider.buffered, Tgstation.Server.Host.IO.BufferedFileStreamProvider.input, Tgstation.Server.Host.Utils.SemaphoreSlimContext.Lock(), and Tgstation.Server.Host.IO.BufferedFileStreamProvider.semaphore.
Referenced by Tgstation.Server.Host.IO.BufferedFileStreamProvider.GetOwnedResult(), and Tgstation.Server.Host.IO.BufferedFileStreamProvider.GetResult().
Member Data Documentation
buffer
volatile? MemoryStream Tgstation.Server.Host.IO.BufferedFileStreamProvider.buffer private
The backing Stream.
Definition at line 31 of file BufferedFileStreamProvider.cs.
Referenced by Tgstation.Server.Host.IO.BufferedFileStreamProvider.BufferedFileStreamProvider(), Tgstation.Server.Host.IO.BufferedFileStreamProvider.DisposeAsync(), and Tgstation.Server.Host.IO.BufferedFileStreamProvider.GetResultInternal().
buffered
volatile bool Tgstation.Server.Host.IO.BufferedFileStreamProvider.buffered private
If buffer has been populated.
Definition at line 36 of file BufferedFileStreamProvider.cs.
Referenced by Tgstation.Server.Host.IO.BufferedFileStreamProvider.DisposeAsync(), and Tgstation.Server.Host.IO.BufferedFileStreamProvider.GetResultInternal().
input
readonly Stream Tgstation.Server.Host.IO.BufferedFileStreamProvider.input private
The original input Stream must remain valid for the lifetime of the BufferedFileStreamProvider or until GetResult(CancellationToken) first returns.
Definition at line 21 of file BufferedFileStreamProvider.cs.
Referenced by Tgstation.Server.Host.IO.BufferedFileStreamProvider.BufferedFileStreamProvider(), and Tgstation.Server.Host.IO.BufferedFileStreamProvider.GetResultInternal().
semaphore
readonly SemaphoreSlim Tgstation.Server.Host.IO.BufferedFileStreamProvider.semaphore private
The SemaphoreSlim used to synchronize writes to buffer.
Definition at line 26 of file BufferedFileStreamProvider.cs.
Referenced by Tgstation.Server.Host.IO.BufferedFileStreamProvider.BufferedFileStreamProvider(), Tgstation.Server.Host.IO.BufferedFileStreamProvider.DisposeAsync(), and Tgstation.Server.Host.IO.BufferedFileStreamProvider.GetResultInternal().
Property Documentation
Disposed
bool Tgstation.Server.Host.IO.BufferedFileStreamProvider.Disposed get
If the ISeekableFileStreamProvider has had global::System.IAsyncDisposable.DisposeAsync called on it.
Implements Tgstation.Server.Host.IO.ISeekableFileStreamProvider.
Definition at line 16 of file BufferedFileStreamProvider.cs.
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/IO/BufferedFileStreamProvider.cs