tgstation-server: Tgstation.Server.Tests.TestingServer Class Reference
Tgstation.Server.Tests.TestingServer Class Reference
Public Member Functions
TestingServer ()
void Dispose ()
async Task Run (CancellationToken cancellationToken)
Runs the IServer
Public Attributes
bool RestartRequested => realServer.RestartRequested
Properties
Uri Url [get]
string Directory [get]
string UpdatePath [get]
string DatabaseType [get]
bool DumpOpenApiSpecpath [get]
Properties inherited from Tgstation.Server.Host.IServer
bool RestartRequested [get]
If the IServer should restart
Private Attributes
string[] args
IServer realServer
Detailed Description
Definition at line 15 of file TestingServer.cs.
Constructor & Destructor Documentation
Tgstation.Server.Tests.TestingServer.TestingServer ()
Definition at line 33 of file TestingServer.cs.
         {
             Directory = Environment.GetEnvironmentVariable("TGS4_TEST_TEMP_DIRECTORY");
             if (String.IsNullOrWhiteSpace(Directory))
             {
                 Directory = Path.Combine(Path.GetTempPath(), "TGS4_INTEGRATION_TEST");
                 if(System.IO.Directory.Exists(Directory))
                     try
                     {
                         System.IO.Directory.Delete(Directory, true);
                     }
                     catch
                     {
                         Directory = Path.Combine(Directory, Guid.NewGuid().ToString());
                     }
             }
             System.IO.Directory.CreateDirectory(Directory);
             const string UrlString = "http://localhost:5010";
             Url = new Uri(UrlString);
             //so we need a db
             //we have to rely on env vars
             DatabaseType = Environment.GetEnvironmentVariable("TGS4_TEST_DATABASE_TYPE");
             var connectionString = Environment.GetEnvironmentVariable("TGS4_TEST_CONNECTION_STRING");
             var gitHubAccessToken = Environment.GetEnvironmentVariable("TGS4_TEST_GITHUB_TOKEN");
             var dumpOpenAPISpecPathEnvVar = Environment.GetEnvironmentVariable("TGS4_TEST_DUMP_API_SPEC");
             if (String.IsNullOrEmpty(DatabaseType))
                 Assert.Inconclusive("No database type configured in env var TGS4_TEST_DATABASE_TYPE!");
             if (String.IsNullOrEmpty(connectionString))
                 Assert.Inconclusive("No connection string configured in env var TGS4_TEST_CONNECTION_STRING!");
             if (String.IsNullOrEmpty(gitHubAccessToken))
                 Console.WriteLine("WARNING: No GitHub access token configured, test may fail due to rate limits!");
             DumpOpenApiSpecpath = !String.IsNullOrEmpty(dumpOpenAPISpecPathEnvVar);
             var args = new List<string>()
             {
                 String.Format(CultureInfo.InvariantCulture, "Database:DropDatabase={0}", true),
                 String.Format(CultureInfo.InvariantCulture, "Kestrel:EndPoints:Http:Url={0}", UrlString),
                 String.Format(CultureInfo.InvariantCulture, "Database:DatabaseType={0}", DatabaseType),
                 String.Format(CultureInfo.InvariantCulture, "Database:ConnectionString={0}", connectionString),
                 String.Format(CultureInfo.InvariantCulture, "General:SetupWizardMode={0}", SetupWizardMode.Never),
                 String.Format(CultureInfo.InvariantCulture, "General:MinimumPasswordLength={0}", 10),
                 String.Format(CultureInfo.InvariantCulture, "General:InstanceLimit={0}", 11),
                 String.Format(CultureInfo.InvariantCulture, "General:UserLimit={0}", 150),
                 String.Format(CultureInfo.InvariantCulture, "General:ValidInstancePaths:0={0}", Directory),
                 "General:ByondTopicTimeout=3000"
             };
             if (!String.IsNullOrEmpty(gitHubAccessToken))
                 args.Add(String.Format(CultureInfo.InvariantCulture, "General:GitHubAccessToken={0}", gitHubAccessToken));
             if (DumpOpenApiSpecpath)
                 Environment.SetEnvironmentVariable("ASPNETCORE_ENVIRONMENT", "Development");
             UpdatePath = Path.Combine(Directory, Guid.NewGuid().ToString());
             this.args = args.ToArray();
         }
Member Function Documentation
void Tgstation.Server.Tests.TestingServer.Dispose ()
Definition at line 96 of file TestingServer.cs.
         {
             for (int i = 0; i < 5; ++i)
                 try
                 {
                     System.IO.Directory.Delete(Directory, true);
                 }
                 catch
                 {
                     GC.Collect(Int32.MaxValue, GCCollectionMode.Forced, false);
                     Thread.Sleep(3000);
                 }
         }
async Task Tgstation.Server.Tests.TestingServer.Run (CancellationToken cancellationToken)
Runs the IServer
Parameters
cancellationToken The CancellationToken for the operation
Returns
A Task representing the running operation
Implements Tgstation.Server.Host.IServer.
Definition at line 110 of file TestingServer.cs.
References Tgstation.Server.Host.Core.Application.CreateDefaultServerFactory(), Tgstation.Server.Host.IServerFactory.CreateServer(), and Tgstation.Server.Host.IServer.Run().
         {
             var firstRun = realServer == null;
             realServer = await Application
                 .CreateDefaultServerFactory()
                 .CreateServer(
                     args,
                     UpdatePath,
                     default);
             if (firstRun)
             {
                 var tmp = args.Skip(1).ToList();
                 tmp.Add(String.Format(CultureInfo.InvariantCulture, "Database:DropDatabase={0}", false));
                 args = tmp.ToArray();
             }
             await realServer.Run(cancellationToken);
         }
Member Data Documentation
string [] Tgstation.Server.Tests.TestingServer.args private
Definition at line 29 of file TestingServer.cs.
IServer Tgstation.Server.Tests.TestingServer.realServer private
Definition at line 31 of file TestingServer.cs.
bool Tgstation.Server.Tests.TestingServer.RestartRequested => realServer.RestartRequested
Definition at line 27 of file TestingServer.cs.
Property Documentation
string Tgstation.Server.Tests.TestingServer.DatabaseType get
Definition at line 23 of file TestingServer.cs.
string Tgstation.Server.Tests.TestingServer.Directory get
Definition at line 19 of file TestingServer.cs.
bool Tgstation.Server.Tests.TestingServer.DumpOpenApiSpecpath get
Definition at line 25 of file TestingServer.cs.
string Tgstation.Server.Tests.TestingServer.UpdatePath get
Definition at line 21 of file TestingServer.cs.
Uri Tgstation.Server.Tests.TestingServer.Url get
Definition at line 17 of file TestingServer.cs.
The documentation for this class was generated from the following file:
tests/Tgstation.Server.Tests/TestingServer.cs