tgstation-server: Tgstation.Server.Tests.Instance.WatchdogTest Class Reference
Tgstation.Server.Tests.Instance.WatchdogTest Class Reference
Public Member Functions
WatchdogTest (IInstanceClient instanceClient)
async Task Run (CancellationToken cancellationToken)
Private Member Functions
async Task RunBasicTest (CancellationToken cancellationToken)
async Task RunLongRunningTestThenUpdate (CancellationToken cancellationToken)
async Task RunLongRunningTestThenUpdateWithByondVersionSwitch (CancellationToken cancellationToken)
async Task StartAndLeaveRunning (CancellationToken cancellationToken)
async Task TellWorldToReboot (CancellationToken cancellationToken)
async Task< DreamDaemon > DeployTestDme (string dmeName, DreamDaemonSecurity deploymentSecurity, CancellationToken cancellationToken)
async Task GracefulWatchdogShutdown (uint timeout, CancellationToken cancellationToken)
async Task CheckDMApiFail (CompileJob compileJob, CancellationToken cancellationToken)
Private Attributes
readonly IInstanceClient instanceClient
Additional Inherited Members
Protected Member Functions inherited from Tgstation.Server.Tests.Instance.JobsRequiredTest
JobsRequiredTest (IJobsClient jobsClient)
async Task< Job > WaitForJob (Job originalJob, int timeout, bool expectFailure, CancellationToken cancellationToken)
async Task< Job > WaitForJobProgressThenCancel (Job originalJob, int timeout, CancellationToken cancellationToken)
Properties inherited from Tgstation.Server.Tests.Instance.JobsRequiredTest
IJobsClient JobsClient [get]
Detailed Description
Definition at line 15 of file WatchdogTest.cs.
Constructor & Destructor Documentation
WatchdogTest()
Tgstation.Server.Tests.Instance.WatchdogTest.WatchdogTest (IInstanceClient instanceClient)
Definition at line 19 of file WatchdogTest.cs.
             : base(instanceClient.Jobs)
         {
             this.instanceClient = instanceClient ?? throw new ArgumentNullException(nameof(instanceClient));
         }
References Tgstation.Server.Tests.Instance.WatchdogTest.instanceClient.
Member Function Documentation
CheckDMApiFail()
async Task Tgstation.Server.Tests.Instance.WatchdogTest.CheckDMApiFail (CompileJob compileJob, CancellationToken cancellationToken) private
Definition at line 224 of file WatchdogTest.cs.
         {
             var failFile = Path.Combine(instanceClient.Metadata.Path, "Game", compileJob.DirectoryName.Value.ToString(), "A", Path.GetDirectoryName(compileJob.DmeName), "test_fail_reason.txt");
             if (!File.Exists(failFile))
                 return;
             var text = await File.ReadAllTextAsync(failFile, cancellationToken);
             Assert.Fail(text);
         }
References Tgstation.Server.Api.Models.Internal.CompileJob.DirectoryName, Tgstation.Server.Api.Models.Internal.CompileJob.DmeName, Tgstation.Server.Tests.Instance.WatchdogTest.instanceClient, Tgstation.Server.Client.Components.IInstanceClient.Metadata, and Tgstation.Server.Api.Models.Instance.Path.
Referenced by Tgstation.Server.Tests.Instance.WatchdogTest.RunBasicTest().
DeployTestDme()
async Task<DreamDaemon> Tgstation.Server.Tests.Instance.WatchdogTest.DeployTestDme (string dmeName, DreamDaemonSecurity deploymentSecurity, CancellationToken cancellationToken) private
Definition at line 186 of file WatchdogTest.cs.
         {
             await instanceClient.DreamMaker.Update(new DreamMaker
             {
                 ApiValidationSecurityLevel = deploymentSecurity,
                 ProjectName = $"tests/DMAPI/{dmeName}"
             }, cancellationToken);
             var compileJobJob = await instanceClient.DreamMaker.Compile(cancellationToken);
             await WaitForJob(compileJobJob, 90, false, cancellationToken);
             return await instanceClient.DreamDaemon.Read(cancellationToken);
         }
References Tgstation.Server.Client.Components.IDreamMakerClient.Compile(), Tgstation.Server.Client.Components.IInstanceClient.DreamDaemon, Tgstation.Server.Client.Components.IInstanceClient.DreamMaker, Tgstation.Server.Tests.Instance.WatchdogTest.instanceClient, Tgstation.Server.Client.Components.IDreamDaemonClient.Read(), Tgstation.Server.Client.Components.IDreamMakerClient.Update(), and Tgstation.Server.Tests.Instance.JobsRequiredTest.WaitForJob().
Referenced by Tgstation.Server.Tests.Instance.WatchdogTest.RunBasicTest(), Tgstation.Server.Tests.Instance.WatchdogTest.RunLongRunningTestThenUpdate(), and Tgstation.Server.Tests.Instance.WatchdogTest.RunLongRunningTestThenUpdateWithByondVersionSwitch().
GracefulWatchdogShutdown()
async Task Tgstation.Server.Tests.Instance.WatchdogTest.GracefulWatchdogShutdown (uint timeout, CancellationToken cancellationToken) private
Definition at line 201 of file WatchdogTest.cs.
         {
             await instanceClient.DreamDaemon.Update(new DreamDaemon
             {
                 SoftShutdown = true
             }, cancellationToken);
             var newStatus = await instanceClient.DreamDaemon.Read(cancellationToken);
             Assert.IsTrue(newStatus.SoftShutdown.Value || !newStatus.Running.Value);
             do
             {
                 await Task.Delay(TimeSpan.FromSeconds(1), cancellationToken).ConfigureAwait(false);
                 var ddStatus = await instanceClient.DreamDaemon.Read(cancellationToken);
                 if (!ddStatus.Running.Value)
                     break;
                 if (--timeout == 0)
                     Assert.Fail("DreamDaemon didn't shutdown within the timeout!");
             }
             while (timeout > 0);
         }
References Tgstation.Server.Client.Components.IInstanceClient.DreamDaemon, Tgstation.Server.Tests.Instance.WatchdogTest.instanceClient, Tgstation.Server.Client.Components.IDreamDaemonClient.Read(), and Tgstation.Server.Client.Components.IDreamDaemonClient.Update().
Referenced by Tgstation.Server.Tests.Instance.WatchdogTest.RunBasicTest().
Run()
async Task Tgstation.Server.Tests.Instance.WatchdogTest.Run (CancellationToken cancellationToken)
Definition at line 25 of file WatchdogTest.cs.
         {
             // Increase startup timeout
             await instanceClient.DreamDaemon.Update(new DreamDaemon
             {
                 StartupTimeout = 45
             }, cancellationToken);
             await RunBasicTest(cancellationToken);
             // await RunLongRunningTestThenUpdate(cancellationToken);
             // await RunLongRunningTestThenUpdateWithByondVersionSwitch(cancellationToken);
             await StartAndLeaveRunning(cancellationToken);
         }
References Tgstation.Server.Client.Components.IInstanceClient.DreamDaemon, Tgstation.Server.Tests.Instance.WatchdogTest.instanceClient, Tgstation.Server.Tests.Instance.WatchdogTest.RunBasicTest(), Tgstation.Server.Tests.Instance.WatchdogTest.StartAndLeaveRunning(), and Tgstation.Server.Client.Components.IDreamDaemonClient.Update().
Referenced by Tgstation.Server.Tests.Instance.InstanceTest.RunTests().
RunBasicTest()
async Task Tgstation.Server.Tests.Instance.WatchdogTest.RunBasicTest (CancellationToken cancellationToken) private
Definition at line 40 of file WatchdogTest.cs.
         {
             var daemonStatus = await DeployTestDme("BasicOperation/basic_operation_test", DreamDaemonSecurity.Ultrasafe, cancellationToken);
             Assert.IsFalse(daemonStatus.Running.Value);
             Assert.IsNotNull(daemonStatus.ActiveCompileJob);
             Assert.IsNull(daemonStatus.StagedCompileJob);
             Assert.AreEqual(DMApiConstants.Version, daemonStatus.ActiveCompileJob.DMApiVersion);
             Assert.AreEqual(DreamDaemonSecurity.Safe, daemonStatus.ActiveCompileJob.MinimumSecurityLevel);
             var startJob = await instanceClient.DreamDaemon.Start(cancellationToken).ConfigureAwait(false);
             await WaitForJob(startJob, 10, false, cancellationToken);
             daemonStatus = await instanceClient.DreamDaemon.Read(cancellationToken);
             Assert.IsTrue(daemonStatus.Running.Value);
             Assert.AreEqual(false, daemonStatus.SoftRestart);
             Assert.AreEqual(false, daemonStatus.SoftShutdown);
             await GracefulWatchdogShutdown(30, cancellationToken);
             daemonStatus = await instanceClient.DreamDaemon.Read(cancellationToken);
             Assert.IsFalse(daemonStatus.Running.Value);
             await CheckDMApiFail(daemonStatus.ActiveCompileJob, cancellationToken);
         }
References Tgstation.Server.Tests.Instance.WatchdogTest.CheckDMApiFail(), Tgstation.Server.Tests.Instance.WatchdogTest.DeployTestDme(), Tgstation.Server.Client.Components.IInstanceClient.DreamDaemon, Tgstation.Server.Tests.Instance.WatchdogTest.GracefulWatchdogShutdown(), Tgstation.Server.Tests.Instance.WatchdogTest.instanceClient, Tgstation.Server.Client.Components.IDreamDaemonClient.Read(), Tgstation.Server.Client.Components.IDreamDaemonClient.Start(), Tgstation.Server.Host.Components.Interop.DMApiConstants.Version, and Tgstation.Server.Tests.Instance.JobsRequiredTest.WaitForJob().
Referenced by Tgstation.Server.Tests.Instance.WatchdogTest.Run().
RunLongRunningTestThenUpdate()
async Task Tgstation.Server.Tests.Instance.WatchdogTest.RunLongRunningTestThenUpdate (CancellationToken cancellationToken) private
Definition at line 67 of file WatchdogTest.cs.
         {
             const string DmeName = "LongRunning/long_running_test";
             var daemonStatus = await DeployTestDme(DmeName, DreamDaemonSecurity.Trusted, cancellationToken);
             var initialCompileJob = daemonStatus.ActiveCompileJob;
             Assert.IsFalse(daemonStatus.Running.Value);
             Assert.IsNotNull(daemonStatus.ActiveCompileJob);
             Assert.IsNull(daemonStatus.StagedCompileJob);
             Assert.AreEqual(DMApiConstants.Version, daemonStatus.ActiveCompileJob.DMApiVersion);
             Assert.AreEqual(DreamDaemonSecurity.Ultrasafe, daemonStatus.ActiveCompileJob.MinimumSecurityLevel);
             var startJob = await instanceClient.DreamDaemon.Start(cancellationToken).ConfigureAwait(false);
             await WaitForJob(startJob, 10, false, cancellationToken);
             daemonStatus = await DeployTestDme(DmeName, DreamDaemonSecurity.Safe, cancellationToken);
             Assert.IsTrue(daemonStatus.Running.Value);
             Assert.AreEqual(initialCompileJob.Id, daemonStatus.ActiveCompileJob.Id);
             var newerCompileJob = daemonStatus.StagedCompileJob;
             Assert.IsNotNull(newerCompileJob);
             Assert.AreNotEqual(initialCompileJob.Id, newerCompileJob.Id);
             Assert.AreEqual(DreamDaemonSecurity.Ultrasafe, newerCompileJob.MinimumSecurityLevel);
             await TellWorldToReboot(cancellationToken);
             daemonStatus = await instanceClient.DreamDaemon.Read(cancellationToken);
             Assert.AreNotEqual(initialCompileJob.Id, daemonStatus.ActiveCompileJob.Id);
             Assert.IsNull(daemonStatus.StagedCompileJob);
             await instanceClient.DreamDaemon.Shutdown(cancellationToken);
             daemonStatus = await instanceClient.DreamDaemon.Read(cancellationToken);
             Assert.IsFalse(daemonStatus.Running.Value);
         }
References Tgstation.Server.Tests.Instance.WatchdogTest.DeployTestDme(), Tgstation.Server.Client.Components.IInstanceClient.DreamDaemon, Tgstation.Server.Tests.Instance.WatchdogTest.instanceClient, Tgstation.Server.Client.Components.IDreamDaemonClient.Read(), Tgstation.Server.Client.Components.IDreamDaemonClient.Shutdown(), Tgstation.Server.Client.Components.IDreamDaemonClient.Start(), Tgstation.Server.Tests.Instance.WatchdogTest.TellWorldToReboot(), Tgstation.Server.Host.Components.Interop.DMApiConstants.Version, and Tgstation.Server.Tests.Instance.JobsRequiredTest.WaitForJob().
RunLongRunningTestThenUpdateWithByondVersionSwitch()
async Task Tgstation.Server.Tests.Instance.WatchdogTest.RunLongRunningTestThenUpdateWithByondVersionSwitch (CancellationToken cancellationToken) private
Definition at line 107 of file WatchdogTest.cs.
         {
             var versionToInstall = new Version(511, 1384, 0);
             var byondInstallJobTask = instanceClient.Byond.SetActiveVersion(
                 new Api.Models.Byond
                 {
                     Version = versionToInstall
                 },
                 cancellationToken);
             var initialStatus = await instanceClient.DreamDaemon.Read(cancellationToken);
             var startJob = await instanceClient.DreamDaemon.Start(cancellationToken).ConfigureAwait(false);
             var byondInstallJob = await byondInstallJobTask;
             await WaitForJob(startJob, 40, false, cancellationToken);
             await WaitForJob(byondInstallJob.InstallJob, 30, false, cancellationToken);
             const string DmeName = "LongRunning/long_running_test";
             await DeployTestDme(DmeName, DreamDaemonSecurity.Safe, cancellationToken);
             var daemonStatus = await instanceClient.DreamDaemon.Read(cancellationToken);
             Assert.IsTrue(daemonStatus.Running.Value);
             Assert.IsNotNull(daemonStatus.ActiveCompileJob);
             Assert.AreEqual(initialStatus.ActiveCompileJob.Id, daemonStatus.ActiveCompileJob.Id);
             var newerCompileJob = daemonStatus.StagedCompileJob;
             Assert.AreNotEqual(daemonStatus.ActiveCompileJob.ByondVersion, newerCompileJob.ByondVersion);
             Assert.AreEqual(versionToInstall, newerCompileJob.ByondVersion);
             Assert.AreEqual(true, daemonStatus.SoftRestart);
             await TellWorldToReboot(cancellationToken);
             daemonStatus = await instanceClient.DreamDaemon.Read(cancellationToken);
             Assert.AreEqual(versionToInstall, daemonStatus.ActiveCompileJob.ByondVersion);
             Assert.IsNull(daemonStatus.StagedCompileJob);
             await instanceClient.DreamDaemon.Shutdown(cancellationToken);
             daemonStatus = await instanceClient.DreamDaemon.Read(cancellationToken);
             Assert.IsFalse(daemonStatus.Running.Value);
         }
References Tgstation.Server.Client.Components.IInstanceClient.Byond, Tgstation.Server.Tests.Instance.WatchdogTest.DeployTestDme(), Tgstation.Server.Client.Components.IInstanceClient.DreamDaemon, Tgstation.Server.Tests.Instance.WatchdogTest.instanceClient, Tgstation.Server.Client.Components.IDreamDaemonClient.Read(), Tgstation.Server.Client.Components.IByondClient.SetActiveVersion(), Tgstation.Server.Client.Components.IDreamDaemonClient.Shutdown(), Tgstation.Server.Client.Components.IDreamDaemonClient.Start(), Tgstation.Server.Tests.Instance.WatchdogTest.TellWorldToReboot(), and Tgstation.Server.Tests.Instance.JobsRequiredTest.WaitForJob().
StartAndLeaveRunning()
async Task Tgstation.Server.Tests.Instance.WatchdogTest.StartAndLeaveRunning (CancellationToken cancellationToken) private
Definition at line 155 of file WatchdogTest.cs.
         {
             var startJob = await instanceClient.DreamDaemon.Start(cancellationToken).ConfigureAwait(false);
             await WaitForJob(startJob, 40, false, cancellationToken);
         }
References Tgstation.Server.Client.Components.IInstanceClient.DreamDaemon, Tgstation.Server.Tests.Instance.WatchdogTest.instanceClient, Tgstation.Server.Client.Components.IDreamDaemonClient.Start(), and Tgstation.Server.Tests.Instance.JobsRequiredTest.WaitForJob().
Referenced by Tgstation.Server.Tests.Instance.WatchdogTest.Run().
TellWorldToReboot()
async Task Tgstation.Server.Tests.Instance.WatchdogTest.TellWorldToReboot (CancellationToken cancellationToken) private
Definition at line 162 of file WatchdogTest.cs.
         {
             var bts = new TopicClient(new SocketParameters
             {
                 SendTimeout = 5000,
                 ReceiveTimeout = 5000
             });
             try
             {
                 var result = await bts.SendTopic(IPAddress.Loopback, "tgs_integration_test_special_tactics=1", 1337, cancellationToken);
                 Assert.AreEqual("ack", result.StringData);
                 await Task.Delay(7000, cancellationToken);
             }
             catch (OperationCanceledException)
             {
                 throw;
             }
             catch
             {
             }
         }
Referenced by Tgstation.Server.Tests.Instance.WatchdogTest.RunLongRunningTestThenUpdate(), and Tgstation.Server.Tests.Instance.WatchdogTest.RunLongRunningTestThenUpdateWithByondVersionSwitch().
Member Data Documentation
instanceClient
readonly IInstanceClient Tgstation.Server.Tests.Instance.WatchdogTest.instanceClient private
Definition at line 17 of file WatchdogTest.cs.
Referenced by Tgstation.Server.Tests.Instance.WatchdogTest.CheckDMApiFail(), Tgstation.Server.Tests.Instance.WatchdogTest.DeployTestDme(), Tgstation.Server.Tests.Instance.WatchdogTest.GracefulWatchdogShutdown(), Tgstation.Server.Tests.Instance.WatchdogTest.Run(), Tgstation.Server.Tests.Instance.WatchdogTest.RunBasicTest(), Tgstation.Server.Tests.Instance.WatchdogTest.RunLongRunningTestThenUpdate(), Tgstation.Server.Tests.Instance.WatchdogTest.RunLongRunningTestThenUpdateWithByondVersionSwitch(), Tgstation.Server.Tests.Instance.WatchdogTest.StartAndLeaveRunning(), and Tgstation.Server.Tests.Instance.WatchdogTest.WatchdogTest().
The documentation for this class was generated from the following file:
tests/Tgstation.Server.Tests/Instance/WatchdogTest.cs