tgstation-server: Tgstation.Server.Host.IO.ResolvingIOManager Class Reference
Tgstation.Server.Host.IO.ResolvingIOManager Class Reference
An IIOManager that resolve relative paths from another IIOManager to a subdirectory of that.
Public Member Functions
ResolvingIOManager (IIOManager parent, string subdirectory)
Initializes a new instance of the ResolvingIOManager class.
override string ResolvePath (string path)
Retrieve the full path of some path given a relative path. Must be used before passing relative paths to other APIs. All other operations in this interface call this internally on given paths.
Parameters
path Some path to retrieve the full path of.
Returns
path as a full path.
Public Member Functions inherited from Tgstation.Server.Host.IO.DefaultIOManager
async ValueTask CopyDirectory (IEnumerable< string >? ignore, Func< string, string, ValueTask >? postCopyCallback, string src, string dest, int? taskThrottle, CancellationToken cancellationToken)
Copies a directory from src to dest .
Parameters
ignore Files and folders to ignore at the root level.
postCopyCallback The optional callback called for each source/dest file pair post copy.
src The source directory path.
dest The destination directory path.
taskThrottle The optional maximum number of simultaneous tasks allowed to execute.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
string ConcatPath (params string[] paths)
Combines an array of strings into a path.
Parameters
paths The paths to combine.
Returns
The combined path.
async ValueTask CopyFile (string src, string dest, CancellationToken cancellationToken)
Copy a file from src to dest .
Parameters
src The source file to copy.
dest The destination path.
cancellationToken A CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Task CreateDirectory (string path, CancellationToken cancellationToken)
Create a directory at path .
Parameters
path The path of the directory to create.
cancellationToken A CancellationToken for the operation.
Returns
A Task representing the running operation.
Task DeleteDirectory (string path, CancellationToken cancellationToken)
Recursively delete a directory, removes and does not enter any symlinks encounterd.
Parameters
path The path to the directory to delete.
cancellationToken A CancellationToken for the operation.
Returns
A Task representing the running operation.
Task DeleteFile (string path, CancellationToken cancellationToken)
Deletes a file at path .
Parameters
path The path of the file to delete.
cancellationToken A CancellationToken for the operation.
Returns
A Task representing the running operation.
Task< bool > FileExists (string path, CancellationToken cancellationToken)
Check that the file at path exists.
Parameters
path The file to check for existence.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in true if the file at path exists, false otherwise.
Task< bool > DirectoryExists (string path, CancellationToken cancellationToken)
Check that the directory at path exists.
Parameters
path The directory to check for existence.
cancellationToken The CancellationToken for the operation.
Returns
A Task resulting in true if the directory at path exists, false otherwise.
string GetDirectoryName (string path)
Gets the directory portion of a given path .
Parameters
path A path to check.
Returns
The directory portion of the given path .
Exceptions
InvalidOperationException If path is rooted.
string GetFileName (string path)
Gets the file name portion of a path .
Parameters
path The path to get the file name of.
Returns
The file name portion of path .
string GetFileNameWithoutExtension (string path)
Gets the file name portion of a path with.
Parameters
path The path to get the file name of.
Returns
The file name portion of path .
Task< List< string > > GetFilesWithExtension (string path, string extension, bool recursive, CancellationToken cancellationToken)
Gets a list of files in path with the given extension .
Parameters
path The directory which contains the files.
extension The extension to look for without the preceeding ".".
recursive If the search should be recursive.
cancellationToken A CancellationToken for the operation.
Returns
A Task resulting in a list of paths to files in path with the given extension .
Task MoveFile (string source, string destination, CancellationToken cancellationToken)
Moves a file at source to destination .
Parameters
source The source file path.
destination The destination path.
cancellationToken A CancellationToken for the operation.
Returns
A Task representing the running operation.
Task MoveDirectory (string source, string destination, CancellationToken cancellationToken)
Moves a directory at source to destination .
Parameters
source The source directory path.
destination The destination path.
cancellationToken A CancellationToken for the operation.
Returns
A Task representing the running operation.
async ValueTask< byte[]> ReadAllBytes (string path, CancellationToken cancellationToken)
Returns all the contents of a file at path as a byte array.
Parameters
path The path of the file to read.
cancellationToken A CancellationToken for the operation.
Returns
A ValueTask that results in the contents of a file at path .
This function will fail to read files from the /proc filesystem on Linux.
string ResolvePath ()
Retrieve the full path of the current working directory.
Returns
The full path of the current working directory.
virtual string ResolvePath (string path)
Retrieve the full path of some path given a relative path. Must be used before passing relative paths to other APIs. All other operations in this interface call this internally on given paths.
Parameters
path Some path to retrieve the full path of.
Returns
path as a full path.
async ValueTask WriteAllBytes (string path, byte[] contents, CancellationToken cancellationToken)
Writes some contents to a file at path overwriting previous content.
Parameters
path The path of the file to write.
contents The contents of the file.
cancellationToken A CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
FileStream CreateAsyncSequentialWriteStream (string path)
Creates an asynchronous FileStream for sequential writing.
Parameters
path The path of the file to write, will be truncated.
Returns
The open FileStream.
FileStream CreateAsyncSequentialReadStream (string path)
Creates an asynchronous FileStream for sequential reading.
Parameters
path The path of the file to write, will be truncated.
Returns
The open FileStream.
Task< IReadOnlyList< string > > GetDirectories (string path, CancellationToken cancellationToken)
Returns full directory names in a given path .
Parameters
path The path to search for directories.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the directories in path .
Task< IReadOnlyList< string > > GetFiles (string path, CancellationToken cancellationToken)
Returns full file names in a given path .
Parameters
path The path to search for files.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the files in path .
Task ZipToDirectory (string path, Stream zipFile, CancellationToken cancellationToken)
Extract a set of zipFile to a given path .
Parameters
path The path to unzip to.
zipFile The Stream of the global::System.IO.Compression.ZipArchive. Must have Stream.CanSeek set to true. Will be read completely and left open. Stream.Position will be indeterminate.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
bool PathContainsParentAccess (string path)
Check if a path contains the '..' parent directory accessor.
Parameters
path The path to check.
Returns
true if path contains a '..' accessor, false otherwise.
Task< DateTimeOffset > GetLastModified (string path, CancellationToken cancellationToken)
Get the DateTimeOffset of when a given path was last modified.
Parameters
path The path to get metadata for.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the DateTimeOffset of when the file was last modified.
FileStream GetFileStream (string path, bool shareWrite)
Gets the Stream for a given file path .
Parameters
path The path of the file.
shareWrite If FileShare.Write should be used.
Returns
The FileStream of the file.
This function is sychronous.
Task< bool > PathIsChildOf (string parentPath, string childPath, CancellationToken cancellationToken)
Check if a given parentPath is a parent of a given parentPath .
Parameters
parentPath The parent path.
childPath The child path.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in true if childPath is a child of parentPath or they are equivalent.
string ResolvePath ()
Retrieve the full path of the current working directory.
string ResolvePath (string path)
Retrieve the full path of some path given a relative path. Must be used before passing relative paths to other APIs. All other operations in this interface call this internally on given paths.
string GetFileName (string path)
Gets the file name portion of a path .
string GetFileNameWithoutExtension (string path)
Gets the file name portion of a path with.
bool PathContainsParentAccess (string path)
Check if a path contains the '..' parent directory accessor.
Task< bool > PathIsChildOf (string parentPath, string childPath, CancellationToken cancellationToken)
Check if a given parentPath is a parent of a given parentPath .
ValueTask CopyDirectory (IEnumerable< string >? ignore, Func< string, string, ValueTask >? postCopyCallback, string src, string dest, int? taskThrottle, CancellationToken cancellationToken)
Copies a directory from src to dest .
Task< bool > FileExists (string path, CancellationToken cancellationToken)
Check that the file at path exists.
Task< bool > DirectoryExists (string path, CancellationToken cancellationToken)
Check that the directory at path exists.
ValueTask< byte[]> ReadAllBytes (string path, CancellationToken cancellationToken)
Returns all the contents of a file at path as a byte array.
Task< IReadOnlyList< string > > GetDirectories (string path, CancellationToken cancellationToken)
Returns full directory names in a given path .
Task< IReadOnlyList< string > > GetFiles (string path, CancellationToken cancellationToken)
Returns full file names in a given path .
FileStream CreateAsyncSequentialWriteStream (string path)
Creates an asynchronous FileStream for sequential writing.
FileStream CreateAsyncSequentialReadStream (string path)
Creates an asynchronous FileStream for sequential reading.
ValueTask WriteAllBytes (string path, byte[] contents, CancellationToken cancellationToken)
Writes some contents to a file at path overwriting previous content.
ValueTask CopyFile (string src, string dest, CancellationToken cancellationToken)
Copy a file from src to dest .
string GetDirectoryName (string path)
Gets the directory portion of a given path .
Task< List< string > > GetFilesWithExtension (string path, string extension, bool recursive, CancellationToken cancellationToken)
Gets a list of files in path with the given extension .
Task DeleteFile (string path, CancellationToken cancellationToken)
Deletes a file at path .
Task CreateDirectory (string path, CancellationToken cancellationToken)
Create a directory at path .
Task DeleteDirectory (string path, CancellationToken cancellationToken)
Recursively delete a directory, removes and does not enter any symlinks encounterd.
string ConcatPath (params string[] paths)
Combines an array of strings into a path.
Task MoveFile (string source, string destination, CancellationToken cancellationToken)
Moves a file at source to destination .
Task MoveDirectory (string source, string destination, CancellationToken cancellationToken)
Moves a directory at source to destination .
Task ZipToDirectory (string path, Stream zipFile, CancellationToken cancellationToken)
Extract a set of zipFile to a given path .
Task< DateTimeOffset > GetLastModified (string path, CancellationToken cancellationToken)
Get the DateTimeOffset of when a given path was last modified.
FileStream GetFileStream (string path, bool shareWrite)
Gets the Stream for a given file path .
Private Attributes
readonly string subdirectory
Path to the subdirectory attached to path resolutions.
Additional Inherited Members
Static Public Attributes inherited from Tgstation.Server.Host.IO.DefaultIOManager
const string CurrentDirectory = "."
Path to the current working directory for the IIOManager.
const int DefaultBufferSize = 4096
Default FileStream buffer size used by .NET.
const TaskCreationOptions BlockingTaskCreationOptions = TaskCreationOptions.None
The TaskCreationOptions used to spawn Tasks for potentially long running, blocking operations.
Detailed Description
An IIOManager that resolve relative paths from another IIOManager to a subdirectory of that.
Definition at line 9 of file ResolvingIOManager.cs.
Constructor & Destructor Documentation
ResolvingIOManager()
Tgstation.Server.Host.IO.ResolvingIOManager.ResolvingIOManager (IIOManager parent, string subdirectory)
Initializes a new instance of the ResolvingIOManager class.
Parameters
parent The IIOManager that resolves to the directory to work out of.
subdirectory The value of subdirectory.
Definition at line 21 of file ResolvingIOManager.cs.
        {
            ArgumentNullException.ThrowIfNull(parent);
            ArgumentNullException.ThrowIfNull(subdirectory);
            this.subdirectory = ConcatPath(parent.ResolvePath(), subdirectory);
        }
References Tgstation.Server.Host.IO.DefaultIOManager.ConcatPath(), Tgstation.Server.Host.IO.IIOManager.ResolvePath(), and Tgstation.Server.Host.IO.ResolvingIOManager.subdirectory.
Member Function Documentation
ResolvePath()
override string Tgstation.Server.Host.IO.ResolvingIOManager.ResolvePath (string path) virtual
Retrieve the full path of some path given a relative path. Must be used before passing relative paths to other APIs. All other operations in this interface call this internally on given paths.
Parameters
path Some path to retrieve the full path of.
Returns
path as a full path.
Reimplemented from Tgstation.Server.Host.IO.DefaultIOManager.
Definition at line 30 of file ResolvingIOManager.cs.
        {
            if (!Path.IsPathRooted(path))
                return base.ResolvePath(ConcatPath(subdirectory, path));
            return path;
        }
References Tgstation.Server.Host.IO.DefaultIOManager.ConcatPath(), and Tgstation.Server.Host.IO.ResolvingIOManager.subdirectory.
Member Data Documentation
subdirectory
readonly string Tgstation.Server.Host.IO.ResolvingIOManager.subdirectory private
Path to the subdirectory attached to path resolutions.
Definition at line 14 of file ResolvingIOManager.cs.
Referenced by Tgstation.Server.Host.IO.ResolvingIOManager.ResolvePath(), and Tgstation.Server.Host.IO.ResolvingIOManager.ResolvingIOManager().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/IO/ResolvingIOManager.cs