tgstation-server: Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager Class Reference
Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager Class Reference abstract
Base class for implementing IRemoteDeploymentManagers.
Public Member Functions
async ValueTask PostDeploymentComments (CompileJob compileJob, RevisionInformation? previousRevisionInformation, RepositorySettings repositorySettings, string? repoOwner, string? repoName, CancellationToken cancellationToken)
Post deployment comments to the test merge ticket.
Parameters
compileJob The deployed CompileJob.
previousRevisionInformation The optional RevisionInformation of the previous deployment.
repositorySettings The RepositorySettings.
repoOwner The remote repostiory owner.
repoName The remote repostiory name.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
ValueTask ApplyDeployment (CompileJob compileJob, CancellationToken cancellationToken)
Stage a given compileJob 's deployment.
Parameters
compileJob The CompileJob being applied.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
abstract ValueTask FailDeployment (CompileJob compileJob, string errorMessage, CancellationToken cancellationToken)
Fail a deployment for a given compileJob .
Parameters
compileJob The failed CompileJob.
errorMessage The error message.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
ValueTask MarkInactive (CompileJob compileJob, CancellationToken cancellationToken)
Mark the deplotment for a given compileJob as inactive.
Parameters
compileJob The inactive CompileJob.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
abstract ValueTask< IReadOnlyCollection< TestMerge > > RemoveMergedTestMerges (IRepository repository, RepositorySettings repositorySettings, RevisionInformation revisionInformation, CancellationToken cancellationToken)
Get the updated list of TestMerges for an origin merge.
Parameters
repository The IRepository to use.
repositorySettings The RepositorySettings.
revisionInformation The current RevisionInformation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IReadOnlyCollection<T> of TestMerges that should remain the new RevisionInformation.
ValueTask StageDeployment (CompileJob compileJob, Action< bool >? activationCallback, CancellationToken cancellationToken)
Stage a given compileJob 's deployment.
Parameters
compileJob The staged CompileJob.
activationCallback An optional Action<T1> to be called when the CompileJob becomes active or is discarded with true or false respectively.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
abstract ValueTask StartDeployment (Api.Models.Internal.IGitRemoteInformation remoteInformation, CompileJob compileJob, CancellationToken cancellationToken)
Start a deployment for a given compileJob .
Parameters
remoteInformation The Api.Models.Internal.IGitRemoteInformation of the repository being deployed.
compileJob The active CompileJob.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
ValueTask StartDeployment (Api.Models.Internal.IGitRemoteInformation remoteInformation, CompileJob compileJob, CancellationToken cancellationToken)
Start a deployment for a given compileJob .
ValueTask StageDeployment (CompileJob compileJob, Action< bool >? activationCallback, CancellationToken cancellationToken)
Stage a given compileJob 's deployment.
ValueTask ApplyDeployment (CompileJob compileJob, CancellationToken cancellationToken)
Stage a given compileJob 's deployment.
ValueTask FailDeployment (CompileJob compileJob, string errorMessage, CancellationToken cancellationToken)
Fail a deployment for a given compileJob .
ValueTask MarkInactive (CompileJob compileJob, CancellationToken cancellationToken)
Mark the deplotment for a given compileJob as inactive.
ValueTask PostDeploymentComments (CompileJob compileJob, RevisionInformation? previousRevisionInformation, RepositorySettings repositorySettings, string? repoOwner, string? repoName, CancellationToken cancellationToken)
Post deployment comments to the test merge ticket.
ValueTask< IReadOnlyCollection< TestMerge > > RemoveMergedTestMerges (IRepository repository, RepositorySettings repositorySettings, RevisionInformation revisionInformation, CancellationToken cancellationToken)
Get the updated list of TestMerges for an origin merge.
Protected Member Functions
BaseRemoteDeploymentManager (ILogger< BaseRemoteDeploymentManager > logger, Api.Models.Instance metadata, ConcurrentDictionary< long, Action< bool > > activationCallbacks)
Initializes a new instance of the BaseRemoteDeploymentManager class.
abstract ValueTask StageDeploymentImpl (CompileJob compileJob, CancellationToken cancellationToken)
Implementation of StageDeployment(CompileJob, Action<bool>, CancellationToken).
abstract ValueTask ApplyDeploymentImpl (CompileJob compileJob, CancellationToken cancellationToken)
Implementation of ApplyDeployment(CompileJob, CancellationToken).
abstract ValueTask MarkInactiveImpl (CompileJob compileJob, CancellationToken cancellationToken)
Implementation of MarkInactive(CompileJob, CancellationToken).
abstract string FormatTestMerge (RepositorySettings repositorySettings, CompileJob compileJob, TestMerge testMerge, string remoteRepositoryOwner, string remoteRepositoryName, bool updated)
Formats a comment for a given testMerge .
abstract ValueTask CommentOnTestMergeSource (RepositorySettings repositorySettings, string remoteRepositoryOwner, string remoteRepositoryName, string comment, int testMergeNumber, CancellationToken cancellationToken)
Create a comment of a given testMergeNumber 's source.
Properties
Api.Models.Instance Metadata [get]
The Api.Models.Instance for the BaseRemoteDeploymentManager.
ILogger< BaseRemoteDeploymentManager > Logger [get]
The ILogger for the BaseRemoteDeploymentManager.
Private Attributes
readonly ConcurrentDictionary< long, Action< bool > > activationCallbacks
A map of CompileJob Api.Models.EntityId.Ids to activation callback Action<T1>s.
Detailed Description
Base class for implementing IRemoteDeploymentManagers.
Definition at line 19 of file BaseRemoteDeploymentManager.cs.
Constructor & Destructor Documentation
BaseRemoteDeploymentManager()
Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.BaseRemoteDeploymentManager (ILogger< BaseRemoteDeploymentManager > logger, Api.Models.Instance metadata, ConcurrentDictionary< long, Action< bool > > activationCallbacks) protected
Initializes a new instance of the BaseRemoteDeploymentManager class.
Parameters
logger The value of Logger.
metadata The value of Metadata.
activationCallbacks The value of activationCallbacks.
Definition at line 42 of file BaseRemoteDeploymentManager.cs.
        {
            Logger = logger ?? throw new ArgumentNullException(nameof(logger));
            Metadata = metadata ?? throw new ArgumentNullException(nameof(metadata));
            this.activationCallbacks = activationCallbacks ?? throw new ArgumentNullException(nameof(activationCallbacks));
        }
References Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.activationCallbacks, Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.Logger, and Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.Metadata.
Member Function Documentation
ApplyDeployment()
ValueTask Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.ApplyDeployment (CompileJob compileJob, CancellationToken cancellationToken)
Stage a given compileJob 's deployment.
Parameters
compileJob The CompileJob being applied.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Deployment.Remote.IRemoteDeploymentManager.
Definition at line 165 of file BaseRemoteDeploymentManager.cs.
        {
            ArgumentNullException.ThrowIfNull(compileJob);
            if (activationCallbacks.TryGetValue(compileJob.Require(x => x.Id), out var activationCallback))
                activationCallback(true);
            return ApplyDeploymentImpl(compileJob, cancellationToken);
        }
References Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.activationCallbacks, and Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.ApplyDeploymentImpl().
ApplyDeploymentImpl()
abstract ValueTask Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.ApplyDeploymentImpl (CompileJob compileJob, CancellationToken cancellationToken) protected pure virtual
Implementation of ApplyDeployment(CompileJob, CancellationToken).
Parameters
compileJob The CompileJob being applied.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implemented in Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager, and Tgstation.Server.Host.Components.Deployment.Remote.GitLabRemoteDeploymentManager.
Referenced by Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.ApplyDeployment().
CommentOnTestMergeSource()
abstract ValueTask Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.CommentOnTestMergeSource (RepositorySettings repositorySettings, string remoteRepositoryOwner, string remoteRepositoryName, string comment, int testMergeNumber, CancellationToken cancellationToken) protected pure virtual
Create a comment of a given testMergeNumber 's source.
Parameters
repositorySettings The RepositorySettings to use.
remoteRepositoryOwner The Api.Models.Internal.IGitRemoteInformation.RemoteRepositoryOwner.
remoteRepositoryName The Api.Models.Internal.IGitRemoteInformation.RemoteRepositoryName.
comment The comment to post.
testMergeNumber The Api.Models.TestMergeParameters.Number.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implemented in Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager, and Tgstation.Server.Host.Components.Deployment.Remote.GitLabRemoteDeploymentManager.
Referenced by Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.PostDeploymentComments().
FailDeployment()
abstract ValueTask Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.FailDeployment (CompileJob compileJob, string errorMessage, CancellationToken cancellationToken) pure virtual
Fail a deployment for a given compileJob .
Parameters
compileJob The failed CompileJob.
errorMessage The error message.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Deployment.Remote.IRemoteDeploymentManager.
Implemented in Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager, and Tgstation.Server.Host.Components.Deployment.Remote.GitLabRemoteDeploymentManager.
FormatTestMerge()
abstract string Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.FormatTestMerge (RepositorySettings repositorySettings, CompileJob compileJob, TestMerge testMerge, string remoteRepositoryOwner, string remoteRepositoryName, bool updated) protected pure virtual
Formats a comment for a given testMerge .
Parameters
repositorySettings The RepositorySettings to use.
compileJob The test merge's CompileJob.
testMerge The TestMerge.
remoteRepositoryOwner The Api.Models.Internal.IGitRemoteInformation.RemoteRepositoryOwner.
remoteRepositoryName The Api.Models.Internal.IGitRemoteInformation.RemoteRepositoryName.
updated If false testMerge is new, otherwise it has been updated to a different Api.Models.TestMergeParameters.TargetCommitSha.
Returns
A formatted string for posting a informative comment about the testMerge .
Implemented in Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager, and Tgstation.Server.Host.Components.Deployment.Remote.GitLabRemoteDeploymentManager.
Referenced by Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.PostDeploymentComments().
MarkInactive()
ValueTask Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.MarkInactive (CompileJob compileJob, CancellationToken cancellationToken)
Mark the deplotment for a given compileJob as inactive.
Parameters
compileJob The inactive CompileJob.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implements Tgstation.Server.Host.Components.Deployment.Remote.IRemoteDeploymentManager.
Definition at line 179 of file BaseRemoteDeploymentManager.cs.
        {
            ArgumentNullException.ThrowIfNull(compileJob);
            if (activationCallbacks.TryRemove(compileJob.Require(x => x.Id), out var activationCallback))
                activationCallback(false);
            return MarkInactiveImpl(compileJob, cancellationToken);
        }
References Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.activationCallbacks, and Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.MarkInactiveImpl().
MarkInactiveImpl()
abstract ValueTask Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.MarkInactiveImpl (CompileJob compileJob, CancellationToken cancellationToken) protected pure virtual
Implementation of MarkInactive(CompileJob, CancellationToken).
Parameters
compileJob The inactive CompileJob.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implemented in Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager, and Tgstation.Server.Host.Components.Deployment.Remote.GitLabRemoteDeploymentManager.
Referenced by Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.MarkInactive().
PostDeploymentComments()
async ValueTask Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.PostDeploymentComments (CompileJob compileJob, RevisionInformation? previousRevisionInformation, RepositorySettings repositorySettings, string? repoOwner, string? repoName, CancellationToken cancellationToken)
Post deployment comments to the test merge ticket.
Parameters
compileJob The deployed CompileJob.
previousRevisionInformation The optional RevisionInformation of the previous deployment.
repositorySettings The RepositorySettings.
repoOwner The remote repostiory owner.
repoName The remote repostiory name.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Deployment.Remote.IRemoteDeploymentManager.
Definition at line 53 of file BaseRemoteDeploymentManager.cs.
        {
            ArgumentNullException.ThrowIfNull(compileJob);
            ArgumentNullException.ThrowIfNull(repositorySettings);
            ArgumentNullException.ThrowIfNull(repoOwner);
            ArgumentNullException.ThrowIfNull(repoName);
            if (repositorySettings.AccessToken == null)
                return;
            var deployedRevisionInformation = compileJob.RevisionInformation;
            if ((previousRevisionInformation != null && previousRevisionInformation.CommitSha == deployedRevisionInformation.CommitSha)
                || !repositorySettings.PostTestMergeComment!.Value)
                return;
            previousRevisionInformation ??= new RevisionInformation();
            previousRevisionInformation.ActiveTestMerges ??= new List<RevInfoTestMerge>();
            deployedRevisionInformation.ActiveTestMerges ??= new List<RevInfoTestMerge>();
            // added prs
            var addedTestMerges = deployedRevisionInformation
                .ActiveTestMerges
                .Select(x => x.TestMerge)
                .Where(x => !previousRevisionInformation
                    .ActiveTestMerges
                    .Any(y => y.TestMerge.Number == x.Number))
                .ToList();
            var removedTestMerges = previousRevisionInformation
                .ActiveTestMerges
                .Select(x => x.TestMerge)
                .Where(x => !deployedRevisionInformation
                    .ActiveTestMerges
                    .Any(y => y.TestMerge.Number == x.Number))
                .ToList();
            var updatedTestMerges = deployedRevisionInformation
                .ActiveTestMerges
                .Select(x => x.TestMerge)
                .Where(x => previousRevisionInformation
                    .ActiveTestMerges
                    .Any(y => y.TestMerge.Number == x.Number))
                .ToList();
            if (addedTestMerges.Count == 0 && removedTestMerges.Count == 0 && updatedTestMerges.Count == 0)
                return;
            Logger.LogTrace(
                "Commenting on {addedCount} added, {removedCount} removed, and {updatedCount} updated test merge sources...",
                addedTestMerges.Count,
                removedTestMerges.Count,
                updatedTestMerges.Count);
            var tasks = new List<ValueTask>(addedTestMerges.Count + updatedTestMerges.Count + removedTestMerges.Count);
            foreach (var addedTestMerge in addedTestMerges)
            {
                var addCommentTask = CommentOnTestMergeSource(
                    repositorySettings,
                    repoOwner,
                    repoName,
                    FormatTestMerge(
                        repositorySettings,
                        compileJob,
                        addedTestMerge,
                        repoOwner,
                        repoName,
                        false),
                    addedTestMerge.Number,
                    cancellationToken);
                tasks.Add(addCommentTask);
            }
            foreach (var removedTestMerge in removedTestMerges)
            {
                var removeCommentTask = CommentOnTestMergeSource(
                    repositorySettings,
                    repoOwner,
                    repoName,
                    "#### Test Merge Removed",
                    removedTestMerge.Number,
                    cancellationToken);
                tasks.Add(removeCommentTask);
            }
            foreach (var updatedTestMerge in updatedTestMerges)
            {
                var updateCommentTask = CommentOnTestMergeSource(
                    repositorySettings,
                    repoOwner,
                    repoName,
                    FormatTestMerge(
                        repositorySettings,
                        compileJob,
                        updatedTestMerge,
                        repoOwner,
                        repoName,
                        true),
                    updatedTestMerge.Number,
                    cancellationToken);
                tasks.Add(updateCommentTask);
            }
            if (tasks.Count > 0)
                await ValueTaskExtensions.WhenAll(tasks);
        }
References Tgstation.Server.Api.Models.Internal.RepositorySettings.AccessToken, Tgstation.Server.Host.Models.RevisionInformation.ActiveTestMerges, Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.CommentOnTestMergeSource(), Tgstation.Server.Api.Models.Internal.RevisionInformation.CommitSha, Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.FormatTestMerge(), Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.Logger, Tgstation.Server.Api.Models.Internal.RepositorySettings.PostTestMergeComment, Tgstation.Server.Host.Models.CompileJob.RevisionInformation, and Tgstation.Server.Common.Extensions.ValueTaskExtensions.WhenAll().
RemoveMergedTestMerges()
abstract ValueTask< IReadOnlyCollection< TestMerge > > Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.RemoveMergedTestMerges (IRepository repository, RepositorySettings repositorySettings, RevisionInformation revisionInformation, CancellationToken cancellationToken) pure virtual
Get the updated list of TestMerges for an origin merge.
Parameters
repository The IRepository to use.
repositorySettings The RepositorySettings.
revisionInformation The current RevisionInformation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IReadOnlyCollection<T> of TestMerges that should remain the new RevisionInformation.
Implements Tgstation.Server.Host.Components.Deployment.Remote.IRemoteDeploymentManager.
Implemented in Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager, and Tgstation.Server.Host.Components.Deployment.Remote.GitLabRemoteDeploymentManager.
StageDeployment()
ValueTask Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.StageDeployment (CompileJob compileJob, Action< bool >? activationCallback, CancellationToken cancellationToken)
Stage a given compileJob 's deployment.
Parameters
compileJob The staged CompileJob.
activationCallback An optional Action<T1> to be called when the CompileJob becomes active or is discarded with true or false respectively.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Deployment.Remote.IRemoteDeploymentManager.
Definition at line 197 of file BaseRemoteDeploymentManager.cs.
        {
            ArgumentNullException.ThrowIfNull(compileJob);
            var compileJobId = compileJob.Require(x => x.Id);
            if (activationCallback != null && !activationCallbacks.TryAdd(compileJobId, activationCallback))
                Logger.LogError("activationCallbacks conflicted on CompileJob #{id}!", compileJobId);
            return StageDeploymentImpl(compileJob, cancellationToken);
        }
References Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.activationCallbacks, Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.Logger, and Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.StageDeploymentImpl().
StageDeploymentImpl()
abstract ValueTask Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.StageDeploymentImpl (CompileJob compileJob, CancellationToken cancellationToken) protected pure virtual
Implementation of StageDeployment(CompileJob, Action<bool>, CancellationToken).
Parameters
compileJob The staged CompileJob.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implemented in Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager, and Tgstation.Server.Host.Components.Deployment.Remote.GitLabRemoteDeploymentManager.
Referenced by Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.StageDeployment().
StartDeployment()
abstract ValueTask Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.StartDeployment (Api.Models.Internal.IGitRemoteInformation remoteInformation, CompileJob compileJob, CancellationToken cancellationToken) pure virtual
Start a deployment for a given compileJob .
Parameters
remoteInformation The Api.Models.Internal.IGitRemoteInformation of the repository being deployed.
compileJob The active CompileJob.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Deployment.Remote.IRemoteDeploymentManager.
Implemented in Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager, and Tgstation.Server.Host.Components.Deployment.Remote.GitLabRemoteDeploymentManager.
Member Data Documentation
activationCallbacks
readonly ConcurrentDictionary<long, Action<bool> > Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.activationCallbacks private
A map of CompileJob Api.Models.EntityId.Ids to activation callback Action<T1>s.
Definition at line 34 of file BaseRemoteDeploymentManager.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.ApplyDeployment(), Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.BaseRemoteDeploymentManager(), Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.MarkInactive(), and Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.StageDeployment().
Property Documentation
Logger
ILogger<BaseRemoteDeploymentManager> Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.Logger get protected
The ILogger for the BaseRemoteDeploymentManager.
Definition at line 29 of file BaseRemoteDeploymentManager.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.BaseRemoteDeploymentManager(), Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.CommentOnTestMergeSource(), Tgstation.Server.Host.Components.Deployment.Remote.GitLabRemoteDeploymentManager.CommentOnTestMergeSource(), Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.PostDeploymentComments(), Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.RemoveMergedTestMerges(), Tgstation.Server.Host.Components.Deployment.Remote.GitLabRemoteDeploymentManager.RemoveMergedTestMerges(), Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.StageDeployment(), Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.StartDeployment(), and Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.UpdateDeployment().
Metadata
Api.Models.Instance Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.Metadata get protected
The Api.Models.Instance for the BaseRemoteDeploymentManager.
Definition at line 24 of file BaseRemoteDeploymentManager.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.BaseRemoteDeploymentManager(), Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.StartDeployment(), and Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.UpdateDeployment().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Deployment/Remote/BaseRemoteDeploymentManager.cs