tgstation-server: Tgstation.Server.Host.Components.Session.SessionControllerFactory Class Reference
Tgstation.Server.Host.Components.Session.SessionControllerFactory Class Reference sealed
Public Member Functions
SessionControllerFactory (IProcessExecutor processExecutor, IEngineManager engineManager, ITopicClientFactory topicClientFactory, ICryptographySuite cryptographySuite, IAssemblyInformationProvider assemblyInformationProvider, IIOManager gameIOManager, IIOManager diagnosticsIOManager, IChatManager chat, INetworkPromptReaper networkPromptReaper, IPlatformIdentifier platformIdentifier, IBridgeRegistrar bridgeRegistrar, IServerPortProvider serverPortProvider, IEventConsumer eventConsumer, IJobManager jobManager, IDreamMaker dreamMaker, IAsyncDelayer asyncDelayer, IDotnetDumpService dotnetDumpService, IMetricFactory metricFactory, ILoggerFactory loggerFactory, IOptionsMonitor< SessionConfiguration > sessionConfigurationOptions, ILogger< SessionControllerFactory > logger, Api.Models.Instance instance)
Initializes a new instance of the SessionControllerFactory class.
async ValueTask< ISessionController > LaunchNew (IDmbProvider dmbProvider, IEngineExecutableLock? currentByondLock, DreamDaemonLaunchParameters launchParameters, bool apiValidate, CancellationToken cancellationToken)
Create a ISessionController from a freshly launch DreamDaemon instance.
Parameters
dmbProvider The IDmbProvider to use.
currentByondLock The current IEngineExecutableLock. if any.
launchParameters The DreamDaemonLaunchParameters to use. DreamDaemonLaunchParameters.SecurityLevel will be updated with the minumum required security level for the launch.
apiValidate If the ISessionController should only validate the DMAPI then exit.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a new ISessionController.
async ValueTask< ISessionController?> Reattach (ReattachInformation reattachInformation, CancellationToken cancellationToken)
Create a ISessionController from an existing DreamDaemon instance.
Parameters
reattachInformation The ReattachInformation to use.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a new ISessionController on success or null on failure to reattach.
Private Member Functions
async ValueTask PortBindTest (ushort port, EngineType engineType, CancellationToken cancellationToken)
Check if a given port can be bound to.
async ValueTask< IProcess > CreateGameServerProcess (IDmbProvider dmbProvider, IEngineExecutableLock engineLock, DreamDaemonLaunchParameters launchParameters, string accessIdentifier, string? logFilePath, bool apiValidate, CancellationToken cancellationToken)
Creates the game server IProcess.
async ValueTask LogDDOutput (IProcess process, string? outputFilePath, bool cliSupported, bool preserveFile, CancellationToken cancellationToken)
Attempts to log DreamDaemon output.
RuntimeInformation CreateRuntimeInformation (IDmbProvider dmbProvider, IChatTrackingContext chatTrackingContext, DreamDaemonSecurity securityLevel, DreamDaemonVisibility visibility, bool apiValidateOnly)
Create RuntimeInformation.
async ValueTask CheckPagerIsNotRunning ()
Make sure the BYOND pager is not running.
Private Attributes
readonly IProcessExecutor processExecutor
The IProcessExecutor for the SessionControllerFactory.
readonly IEngineManager engineManager
The IEngineManager for the SessionControllerFactory.
readonly ITopicClientFactory topicClientFactory
The ITopicClientFactory for the SessionControllerFactory.
readonly ICryptographySuite cryptographySuite
The ICryptographySuite for the SessionControllerFactory.
readonly IAssemblyInformationProvider assemblyInformationProvider
The IAssemblyInformationProvider for the SessionControllerFactory.
readonly IIOManager gameIOManager
The IIOManager for the Game directory.
readonly IIOManager diagnosticsIOManager
The IIOManager for the Diagnostics directory.
readonly IChatManager chat
The IChatManager for the SessionControllerFactory.
readonly INetworkPromptReaper networkPromptReaper
The INetworkPromptReaper for the SessionControllerFactory.
readonly IPlatformIdentifier platformIdentifier
The IPlatformIdentifier for the SessionControllerFactory.
readonly IBridgeRegistrar bridgeRegistrar
The IBridgeRegistrar for the SessionControllerFactory.
readonly IServerPortProvider serverPortProvider
The IServerPortProvider for the SessionControllerFactory.
readonly IEventConsumer eventConsumer
The IEventConsumer for the SessionControllerFactory.
readonly IJobManager jobManager
The IJobManager for the SessionControllerFactory.
readonly IDreamMaker dreamMaker
The IDreamMaker for the SessionControllerFactory.
readonly IAsyncDelayer asyncDelayer
The IAsyncDelayer for the SessionControllerFactory.
readonly IDotnetDumpService dotnetDumpService
The IDotnetDumpService for the SessionControllerFactory.
readonly ILoggerFactory loggerFactory
The ILoggerFactory for the SessionControllerFactory.
readonly IOptionsMonitor< SessionConfiguration > sessionConfigurationOptions
The IOptionsMonitor<TOptions> of SessionConfiguration for the SessionControllerFactory.
readonly ILogger< SessionControllerFactory > logger
The ILogger for the SessionControllerFactory.
readonly Counter sessionsLaunched
The number of sessions launched.
readonly Gauge lastSessionLaunch
The time the current session was launched.
readonly Api.Models.Instance instance
The Api.Models.Instance for the SessionControllerFactory.
Static Private Attributes
const string DreamDaemonLogsPath = "DreamDaemonLogs"
Path in Diagnostics folder to DreamDaemon logs.
Detailed Description
Definition at line 36 of file SessionControllerFactory.cs.
Constructor & Destructor Documentation
SessionControllerFactory()
Tgstation.Server.Host.Components.Session.SessionControllerFactory.SessionControllerFactory (IProcessExecutor processExecutor, IEngineManager engineManager, ITopicClientFactory topicClientFactory, ICryptographySuite cryptographySuite, IAssemblyInformationProvider assemblyInformationProvider, IIOManager gameIOManager, IIOManager diagnosticsIOManager, IChatManager chat, INetworkPromptReaper networkPromptReaper, IPlatformIdentifier platformIdentifier, IBridgeRegistrar bridgeRegistrar, IServerPortProvider serverPortProvider, IEventConsumer eventConsumer, IJobManager jobManager, IDreamMaker dreamMaker, IAsyncDelayer asyncDelayer, IDotnetDumpService dotnetDumpService, IMetricFactory metricFactory, ILoggerFactory loggerFactory, IOptionsMonitor< SessionConfiguration > sessionConfigurationOptions, ILogger< SessionControllerFactory > logger, Api::Models::Instance instance)
Initializes a new instance of the SessionControllerFactory class.
Parameters
processExecutor The value of processExecutor.
engineManager The value of engineManager.
topicClientFactory The value of topicClientFactory.
cryptographySuite The value of cryptographySuite.
assemblyInformationProvider The value of assemblyInformationProvider.
instance The value of instance.
gameIOManager The value of gameIOManager.
diagnosticsIOManager The value of diagnosticsIOManager.
chat The value of chat.
networkPromptReaper The value of networkPromptReaper.
platformIdentifier The value of platformIdentifier.
bridgeRegistrar The value of bridgeRegistrar.
serverPortProvider The value of serverPortProvider.
eventConsumer The value of eventConsumer.
jobManager The value of jobManager.
dreamMaker The value of dreamMaker.
asyncDelayer The value of asyncDelayer.
dotnetDumpService The value of dotnetDumpService.
metricFactory The IMetricFactory used to create metrics.
sessionConfigurationOptions The value of sessionConfigurationOptions.
loggerFactory The value of loggerFactory.
logger The value of logger.
Definition at line 217 of file SessionControllerFactory.cs.
        {
            this.processExecutor = processExecutor ?? throw new ArgumentNullException(nameof(processExecutor));
            this.engineManager = engineManager ?? throw new ArgumentNullException(nameof(engineManager));
            this.topicClientFactory = topicClientFactory ?? throw new ArgumentNullException(nameof(topicClientFactory));
            this.cryptographySuite = cryptographySuite ?? throw new ArgumentNullException(nameof(cryptographySuite));
            this.assemblyInformationProvider = assemblyInformationProvider ?? throw new ArgumentNullException(nameof(assemblyInformationProvider));
            this.gameIOManager = gameIOManager ?? throw new ArgumentNullException(nameof(gameIOManager));
            this.diagnosticsIOManager = diagnosticsIOManager ?? throw new ArgumentNullException(nameof(diagnosticsIOManager));
            this.chat = chat ?? throw new ArgumentNullException(nameof(chat));
            this.networkPromptReaper = networkPromptReaper ?? throw new ArgumentNullException(nameof(networkPromptReaper));
            this.platformIdentifier = platformIdentifier ?? throw new ArgumentNullException(nameof(platformIdentifier));
            this.bridgeRegistrar = bridgeRegistrar ?? throw new ArgumentNullException(nameof(bridgeRegistrar));
            this.serverPortProvider = serverPortProvider ?? throw new ArgumentNullException(nameof(serverPortProvider));
            this.eventConsumer = eventConsumer ?? throw new ArgumentNullException(nameof(eventConsumer));
            this.jobManager = jobManager ?? throw new ArgumentNullException(nameof(jobManager));
            this.dreamMaker = dreamMaker ?? throw new ArgumentNullException(nameof(dreamMaker));
            this.asyncDelayer = asyncDelayer ?? throw new ArgumentNullException(nameof(asyncDelayer));
            this.dotnetDumpService = dotnetDumpService ?? throw new ArgumentNullException(nameof(dotnetDumpService));
            ArgumentNullException.ThrowIfNull(metricFactory);
            this.sessionConfigurationOptions = sessionConfigurationOptions ?? throw new ArgumentNullException(nameof(sessionConfigurationOptions));
            this.loggerFactory = loggerFactory ?? throw new ArgumentNullException(nameof(loggerFactory));
            this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
            this.instance = instance ?? throw new ArgumentNullException(nameof(instance));
            sessionsLaunched = metricFactory.CreateCounter("tgs_sessions_launched", "The number of game server processes created");
            lastSessionLaunch = metricFactory.CreateGauge("tgs_session_start_time", "The UTC unix timestamp the most recent session was started");
        }
References Tgstation.Server.Host.Components.Session.SessionControllerFactory.assemblyInformationProvider, Tgstation.Server.Host.Components.Session.SessionControllerFactory.asyncDelayer, Tgstation.Server.Host.Components.Session.SessionControllerFactory.bridgeRegistrar, Tgstation.Server.Host.Components.Session.SessionControllerFactory.chat, Tgstation.Server.Host.Components.Session.SessionControllerFactory.cryptographySuite, Tgstation.Server.Host.Components.Session.SessionControllerFactory.diagnosticsIOManager, Tgstation.Server.Host.Components.Session.SessionControllerFactory.dotnetDumpService, Tgstation.Server.Host.Components.Session.SessionControllerFactory.dreamMaker, Tgstation.Server.Host.Components.Session.SessionControllerFactory.engineManager, Tgstation.Server.Host.Components.Session.SessionControllerFactory.eventConsumer, Tgstation.Server.Host.Components.Session.SessionControllerFactory.gameIOManager, Tgstation.Server.Host.Components.Session.SessionControllerFactory.instance, Tgstation.Server.Host.Components.Session.SessionControllerFactory.jobManager, Tgstation.Server.Host.Components.Session.SessionControllerFactory.lastSessionLaunch, Tgstation.Server.Host.Components.Session.SessionControllerFactory.logger, Tgstation.Server.Host.Components.Session.SessionControllerFactory.loggerFactory, Tgstation.Server.Host.Components.Session.SessionControllerFactory.networkPromptReaper, Tgstation.Server.Host.Components.Session.SessionControllerFactory.platformIdentifier, Tgstation.Server.Host.Components.Session.SessionControllerFactory.processExecutor, Tgstation.Server.Host.Components.Session.SessionControllerFactory.serverPortProvider, Tgstation.Server.Host.Components.Session.SessionControllerFactory.sessionConfigurationOptions, Tgstation.Server.Host.Components.Session.SessionControllerFactory.sessionsLaunched, and Tgstation.Server.Host.Components.Session.SessionControllerFactory.topicClientFactory.
Member Function Documentation
CheckPagerIsNotRunning()
async ValueTask Tgstation.Server.Host.Components.Session.SessionControllerFactory.CheckPagerIsNotRunning () private
Make sure the BYOND pager is not running.
Returns
A ValueTask representing the running operation.
Definition at line 710 of file SessionControllerFactory.cs.
        {
            if (!platformIdentifier.IsWindows)
                return;
            await using var otherProcess = processExecutor.GetProcessByName("byond");
            if (otherProcess == null)
                return;
            var otherUsername = otherProcess.GetExecutingUsername();
            await using var ourProcess = processExecutor.GetCurrentProcess();
            var ourUsername = ourProcess.GetExecutingUsername();
            if (otherUsername.Equals(ourUsername, StringComparison.Ordinal))
                throw new JobException(ErrorCode.DreamDaemonPagerRunning);
        }
Referenced by Tgstation.Server.Host.Components.Session.SessionControllerFactory.LaunchNew().
CreateGameServerProcess()
async ValueTask< IProcess > Tgstation.Server.Host.Components.Session.SessionControllerFactory.CreateGameServerProcess (IDmbProvider dmbProvider, IEngineExecutableLock engineLock, DreamDaemonLaunchParameters launchParameters, string accessIdentifier, string? logFilePath, bool apiValidate, CancellationToken cancellationToken) private
Creates the game server IProcess.
Parameters
dmbProvider The IDmbProvider.
engineLock The IEngineExecutableLock.
launchParameters The DreamDaemonLaunchParameters.
accessIdentifier The secure string to use for the session.
logFilePath The optional full path to log DreamDaemon output to.
apiValidate If we are only validating the DMAPI then exiting.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the DreamDaemon IProcess.
Definition at line 541 of file SessionControllerFactory.cs.
        {
            var serverMayHaveDMApi = apiValidate || dmbProvider.CompileJob.DMApiVersion != null;
            var serverArguments = serverMayHaveDMApi
                ? new Dictionary<string, string>
                {
                    { DMApiConstants.ParamApiVersion, DMApiConstants.InteropVersion.Semver().ToString() },
                    { DMApiConstants.ParamServerPort, serverPortProvider.HttpApiPort.ToString(CultureInfo.InvariantCulture) },
                    { DMApiConstants.ParamAccessIdentifier, accessIdentifier },
                }
                : null;
            var environment = await engineLock.LoadEnv(logger, false, cancellationToken);
            var arguments = engineLock.FormatServerArguments(
                dmbProvider,
                serverArguments,
                launchParameters,
                accessIdentifier,
                !engineLock.HasStandardOutput || engineLock.PreferFileLogging
                    ? logFilePath
                    : null);
            // If this isnt a staging DD (From a Deployment), fire off events
            if (!apiValidate)
                await eventConsumer.HandleEvent(
                    EventType.DreamDaemonPreLaunch,
                    Enumerable.Empty<string?>(),
                    false,
                    false,
                    cancellationToken);
            var process = await processExecutor.LaunchProcess(
                engineLock.ServerExePath,
                dmbProvider.Directory,
                arguments,
                cancellationToken,
                environment,
                logFilePath,
                engineLock.HasStandardOutput,
                true);
            try
            {
                var sessionConfiguration = sessionConfigurationOptions.CurrentValue;
                if (!apiValidate)
                {
                    if (sessionConfiguration.HighPriorityLiveDreamDaemon)
                        process.AdjustPriority(true);
                }
                else if (sessionConfiguration.LowPriorityDeploymentProcesses)
                    process.AdjustPriority(false);
                if (!engineLock.HasStandardOutput)
                    networkPromptReaper.RegisterProcess(process);
                if (!apiValidate)
                    await eventConsumer.HandleEvent(
                        EventType.DreamDaemonLaunch,
                        new List<string>
{
                            process.Id.ToString(CultureInfo.InvariantCulture),
                        },
                        false,
                        false,
                        cancellationToken);
                return process;
            }
            catch
            {
                await using (process)
                {
                    process.Terminate();
                    await process.Lifetime;
                    throw;
                }
            }
        }
References Tgstation.Server.Host.Components.Deployment.IDmbProvider.Directory, Tgstation.Server.Host.Components.Session.SessionControllerFactory.eventConsumer, Tgstation.Server.Host.Components.Engine.IEngineInstallation.FormatServerArguments(), Tgstation.Server.Host.Components.Events.IEventConsumer.HandleEvent(), Tgstation.Server.Host.Components.Engine.IEngineInstallation.HasStandardOutput, Tgstation.Server.Host.Core.IServerPortProvider.HttpApiPort, Tgstation.Server.Host.Components.Interop.DMApiConstants.InteropVersion, Tgstation.Server.Host.System.IProcessExecutor.LaunchProcess(), Tgstation.Server.Host.Components.Engine.IEngineInstallation.LoadEnv(), Tgstation.Server.Host.Components.Session.SessionControllerFactory.logger, Tgstation.Server.Host.Components.Session.SessionControllerFactory.networkPromptReaper, Tgstation.Server.Host.Components.Interop.DMApiConstants.ParamAccessIdentifier, Tgstation.Server.Host.Components.Interop.DMApiConstants.ParamApiVersion, Tgstation.Server.Host.Components.Interop.DMApiConstants.ParamServerPort, Tgstation.Server.Host.Components.Engine.IEngineInstallation.PreferFileLogging, Tgstation.Server.Host.Components.Session.SessionControllerFactory.processExecutor, Tgstation.Server.Host.System.INetworkPromptReaper.RegisterProcess(), Tgstation.Server.Host.Components.Engine.IEngineInstallation.ServerExePath, Tgstation.Server.Host.Components.Session.SessionControllerFactory.serverPortProvider, and Tgstation.Server.Host.Components.Session.SessionControllerFactory.sessionConfigurationOptions.
Referenced by Tgstation.Server.Host.Components.Session.SessionControllerFactory.LaunchNew().
CreateRuntimeInformation()
RuntimeInformation Tgstation.Server.Host.Components.Session.SessionControllerFactory.CreateRuntimeInformation (IDmbProvider dmbProvider, IChatTrackingContext chatTrackingContext, DreamDaemonSecurity securityLevel, DreamDaemonVisibility visibility, bool apiValidateOnly) private
Create RuntimeInformation.
Parameters
dmbProvider The IDmbProvider.
chatTrackingContext The IChatTrackingContext.
securityLevel The DreamDaemonSecurity the server was launched with.
visibility The DreamDaemonVisibility the server was launched with.
apiValidateOnly The value of RuntimeInformation.ApiValidateOnly.
Returns
A new RuntimeInformation class.
Referenced by Tgstation.Server.Host.Components.Session.SessionControllerFactory.LaunchNew(), and Tgstation.Server.Host.Components.Session.SessionControllerFactory.Reattach().
LaunchNew()
async ValueTask< ISessionController > Tgstation.Server.Host.Components.Session.SessionControllerFactory.LaunchNew (IDmbProvider dmbProvider, IEngineExecutableLock? currentByondLock, DreamDaemonLaunchParameters launchParameters, bool apiValidate, CancellationToken cancellationToken)
Create a ISessionController from a freshly launch DreamDaemon instance.
Parameters
dmbProvider The IDmbProvider to use.
currentByondLock The current IEngineExecutableLock. if any.
launchParameters The DreamDaemonLaunchParameters to use. DreamDaemonLaunchParameters.SecurityLevel will be updated with the minumum required security level for the launch.
apiValidate If the ISessionController should only validate the DMAPI then exit.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a new ISessionController.
Implements Tgstation.Server.Host.Components.Session.ISessionControllerFactory.
Definition at line 270 of file SessionControllerFactory.cs.
        {
            logger.LogTrace("Begin session launch...");
            if (!launchParameters.Port.HasValue)
                throw new InvalidOperationException("Given port is null!");
            switch (dmbProvider.CompileJob.MinimumSecurityLevel)
            {
                case DreamDaemonSecurity.Ultrasafe:
                    break;
                case DreamDaemonSecurity.Safe:
                    if (launchParameters.SecurityLevel == DreamDaemonSecurity.Ultrasafe)
                    {
                        logger.LogTrace("Boosting security level to minimum of Safe");
                        launchParameters.SecurityLevel = DreamDaemonSecurity.Safe;
                    }
                    break;
                case DreamDaemonSecurity.Trusted:
                    if (launchParameters.SecurityLevel != DreamDaemonSecurity.Trusted)
                        logger.LogTrace("Boosting security level to minimum of Trusted");
                    launchParameters.SecurityLevel = DreamDaemonSecurity.Trusted;
                    break;
                default:
                    throw new InvalidOperationException(String.Format(CultureInfo.InvariantCulture, "Invalid DreamDaemonSecurity value: {0}", dmbProvider.CompileJob.MinimumSecurityLevel));
            }
            // get the byond lock
            var engineLock = currentByondLock ?? await engineManager.UseExecutables(
                dmbProvider.EngineVersion,
                gameIOManager.ConcatPath(dmbProvider.Directory, dmbProvider.DmbName),
                cancellationToken);
            try
            {
                logger.LogDebug(
                    "Launching session with CompileJob {compileJobId}...",
                    dmbProvider.CompileJob.Id);
                // mad this isn't abstracted but whatever
                var engineType = dmbProvider.EngineVersion.Engine!.Value;
                if (engineType == EngineType.Byond)
                    await CheckPagerIsNotRunning();
                await PortBindTest(launchParameters.Port.Value, engineType, cancellationToken);
                string? outputFilePath = null;
                var preserveLogFile = true;
                var hasStandardOutput = engineLock.HasStandardOutput;
                if (launchParameters.LogOutput!.Value)
                {
                    var now = DateTimeOffset.UtcNow;
                    var dateDirectory = diagnosticsIOManager.ConcatPath(DreamDaemonLogsPath, now.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture));
                    await diagnosticsIOManager.CreateDirectory(dateDirectory, cancellationToken);
                    outputFilePath = diagnosticsIOManager.ResolvePath(
                        diagnosticsIOManager.ConcatPath(
                            dateDirectory,
                            $"server-utc-{now.ToString("yyyy-MM-dd-HH-mm-ss", CultureInfo.InvariantCulture)}{(apiValidate ? "-dmapi" : String.Empty)}.log"));
                    logger.LogInformation("Logging server output to {path}...", outputFilePath);
                }
                else if (!hasStandardOutput)
                {
                    outputFilePath = gameIOManager.ConcatPath(dmbProvider.Directory, $"{Guid.NewGuid()}.server.log");
                    preserveLogFile = false;
                }
                var accessIdentifier = cryptographySuite.GetSecureString();
                if (!apiValidate && dmbProvider.CompileJob.DMApiVersion == null)
                    logger.LogDebug("Session will have no DMAPI support!");
                // launch dd
                var process = await CreateGameServerProcess(
                    dmbProvider,
                    engineLock,
                    launchParameters,
                    accessIdentifier,
                    outputFilePath,
                    apiValidate,
                    cancellationToken);
                try
                {
                    var chatTrackingContext = chat.CreateTrackingContext();
                    try
                    {
                        var runtimeInformation = CreateRuntimeInformation(
                            dmbProvider,
                            chatTrackingContext,
                            launchParameters.SecurityLevel!.Value,
                            launchParameters.Visibility!.Value,
                            apiValidate);
                        var reattachInformation = new ReattachInformation(
                            dmbProvider,
                            process,
                            runtimeInformation,
                            accessIdentifier,
                            launchParameters.Port.Value);
                        var byondTopicSender = topicClientFactory.CreateTopicClient(
                            TimeSpan.FromMilliseconds(
                                launchParameters.TopicRequestTimeout!.Value));
                        var sessionController = new SessionController(
                            reattachInformation,
                            instance,
                            process,
                            engineLock,
                            byondTopicSender,
                            chatTrackingContext,
                            bridgeRegistrar,
                            chat,
                            assemblyInformationProvider,
                            asyncDelayer,
                            dotnetDumpService,
                            eventConsumer,
                            jobManager,
                            dreamMaker,
                            loggerFactory.CreateLogger<SessionController>(),
                            () => LogDDOutput(
                                process,
                                outputFilePath,
                                hasStandardOutput,
                                preserveLogFile,
                                CancellationToken.None), // DCT: None available
                            launchParameters.StartupTimeout,
                            false,
                            apiValidate);
                        if (!apiValidate)
{
                            sessionsLaunched.Inc();
                            lastSessionLaunch.SetToCurrentTimeUtc();
                        }
                        return sessionController;
                    }
                    catch
                    {
                        chatTrackingContext.Dispose();
                        throw;
                    }
                }
                catch
                {
                    await using (process)
                    {
                        process.Terminate();
                        await process.Lifetime;
                        throw;
                    }
                }
            }
            catch
            {
                if (currentByondLock == null)
                    engineLock.Dispose();
                throw;
            }
        }
References Tgstation.Server.Host.Components.Session.SessionControllerFactory.assemblyInformationProvider, Tgstation.Server.Host.Components.Session.SessionControllerFactory.asyncDelayer, Tgstation.Server.Host.Components.Session.SessionControllerFactory.bridgeRegistrar, Tgstation.Server.Host.Components.Session.SessionControllerFactory.chat, Tgstation.Server.Host.Components.Session.SessionControllerFactory.CheckPagerIsNotRunning(), Tgstation.Server.Host.Components.Deployment.IDmbProvider.CompileJob, Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.IO.IIOManager.CreateDirectory(), Tgstation.Server.Host.Components.Session.SessionControllerFactory.CreateGameServerProcess(), Tgstation.Server.Host.Components.Session.SessionControllerFactory.CreateRuntimeInformation(), Tgstation.Server.Host.Components.Session.ITopicClientFactory.CreateTopicClient(), Tgstation.Server.Host.Components.Chat.IChatManager.CreateTrackingContext(), Tgstation.Server.Host.Components.Session.SessionControllerFactory.cryptographySuite, Tgstation.Server.Host.Components.Session.SessionControllerFactory.diagnosticsIOManager, Tgstation.Server.Host.Components.Deployment.IDmbProvider.Directory, Tgstation.Server.Api.Models.Internal.CompileJob.DMApiVersion, Tgstation.Server.Host.Components.Deployment.IDmbProvider.DmbName, Tgstation.Server.Host.Components.Session.SessionControllerFactory.dotnetDumpService, Tgstation.Server.Host.Components.Session.SessionControllerFactory.DreamDaemonLogsPath, Tgstation.Server.Host.Components.Session.SessionControllerFactory.dreamMaker, Tgstation.Server.Api.Models.EngineVersion.Engine, Tgstation.Server.Host.Components.Session.SessionControllerFactory.engineManager, Tgstation.Server.Host.Components.Deployment.IDmbProvider.EngineVersion, Tgstation.Server.Host.Components.Session.SessionControllerFactory.eventConsumer, Tgstation.Server.Host.Components.Session.SessionControllerFactory.gameIOManager, Tgstation.Server.Host.Security.ICryptographySuite.GetSecureString(), Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Host.Components.Session.SessionControllerFactory.instance, Tgstation.Server.Host.Components.Session.SessionControllerFactory.jobManager, Tgstation.Server.Host.Components.Session.SessionControllerFactory.lastSessionLaunch, Tgstation.Server.Host.Components.Session.SessionControllerFactory.LogDDOutput(), Tgstation.Server.Host.Components.Session.SessionControllerFactory.logger, Tgstation.Server.Host.Components.Session.SessionControllerFactory.loggerFactory, Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.LogOutput, Tgstation.Server.Api.Models.Internal.CompileJob.MinimumSecurityLevel, Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.Port, Tgstation.Server.Host.Components.Session.SessionControllerFactory.PortBindTest(), Tgstation.Server.Host.IO.IIOManager.ResolvePath(), Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.SecurityLevel, Tgstation.Server.Host.Components.Session.SessionControllerFactory.sessionsLaunched, Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.StartupTimeout, Tgstation.Server.Host.Components.Session.SessionControllerFactory.topicClientFactory, Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.TopicRequestTimeout, Tgstation.Server.Host.Components.Engine.IEngineManager.UseExecutables(), and Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.Visibility.
Referenced by Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.InitController().
LogDDOutput()
async ValueTask Tgstation.Server.Host.Components.Session.SessionControllerFactory.LogDDOutput (IProcess process, string? outputFilePath, bool cliSupported, bool preserveFile, CancellationToken cancellationToken) private
Attempts to log DreamDaemon output.
Parameters
process The DreamDaemon IProcess.
outputFilePath The path to the DreamDaemon log file. Will be deleted if preserveFile is false.
cliSupported If DreamDaemon was launched with CLI capabilities.
preserveFile If false, outputFilePath will be deleted.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Definition at line 637 of file SessionControllerFactory.cs.
        {
            try
            {
                string? ddOutput = null;
                if (cliSupported)
                    ddOutput = (await process.GetCombinedOutput(cancellationToken))!;
                if (String.IsNullOrWhiteSpace(ddOutput) && outputFilePath != null)
                    try
                    {
                        var dreamDaemonLogBytes = await gameIOManager.ReadAllBytes(
                            outputFilePath,
                            cancellationToken);
                        ddOutput = Encoding.UTF8.GetString(dreamDaemonLogBytes);
                    }
                    finally
                    {
                        if (!preserveFile)
                            try
{
                                logger.LogTrace("Deleting temporary log file {path}...", outputFilePath);
                                await gameIOManager.DeleteFile(outputFilePath, cancellationToken);
                            }
                            catch (Exception ex)
{
                                // this is expected on OD at time of the support changes.
                                // I've open a change to fix it: https://github.com/space-wizards/RobustToolbox/pull/4501
                                logger.LogWarning(ex, "Failed to delete server log file {outputFilePath}!", outputFilePath);
                            }
                    }
                logger.LogTrace(
                    "Server Output:{newLine}{output}",
                    Environment.NewLine,
                    ddOutput);
            }
            catch (Exception ex)
            {
                logger.LogWarning(ex, "Error reading server output!");
            }
        }
References Tgstation.Server.Host.System.IProcess.GetCombinedOutput().
Referenced by Tgstation.Server.Host.Components.Session.SessionControllerFactory.LaunchNew().
PortBindTest()
async ValueTask Tgstation.Server.Host.Components.Session.SessionControllerFactory.PortBindTest (ushort port, EngineType engineType, CancellationToken cancellationToken) private
Check if a given port can be bound to.
Parameters
port The port number to test.
engineType The EngineType we're bind testing for.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Definition at line 165 of file SessionControllerFactory.cs.
        {
            logger.LogTrace("Bind test: {port}", port);
            try
            {
                // GIVE ME THE FUCKING PORT BACK WINDOWS!!!!
                const int MaxAttempts = 5;
                for (var i = 0; i < MaxAttempts; ++i)
                    try
                    {
                        SocketExtensions.BindTest(platformIdentifier, port, false, engineType == EngineType.OpenDream);
                        if (i > 0)
                            logger.LogDebug("Clearing the socket took {iterations} attempts :/", i + 1);
                        break;
                    }
                    catch (SocketException ex) when (platformIdentifier.IsWindows && ex.SocketErrorCode == SocketError.AddressAlreadyInUse && i < (MaxAttempts - 1))
                    {
                        await asyncDelayer.Delay(TimeSpan.FromSeconds(1), cancellationToken);
                    }
            }
            catch (SocketException ex) when (ex.SocketErrorCode == SocketError.AddressAlreadyInUse)
            {
                throw new JobException(ErrorCode.GameServerPortInUse, ex);
            }
        }
References Tgstation.Server.Host.Components.Session.SessionControllerFactory.asyncDelayer, Tgstation.Server.Host.Extensions.SocketExtensions.BindTest(), Tgstation.Server.Host.Utils.IAsyncDelayer.Delay(), Tgstation.Server.Host.System.IPlatformIdentifier.IsWindows, Tgstation.Server.Host.Components.Session.SessionControllerFactory.logger, and Tgstation.Server.Host.Components.Session.SessionControllerFactory.platformIdentifier.
Referenced by Tgstation.Server.Host.Components.Session.SessionControllerFactory.LaunchNew().
Reattach()
async ValueTask< ISessionController?> Tgstation.Server.Host.Components.Session.SessionControllerFactory.Reattach (ReattachInformation reattachInformation, CancellationToken cancellationToken)
Create a ISessionController from an existing DreamDaemon instance.
Parameters
reattachInformation The ReattachInformation to use.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a new ISessionController on success or null on failure to reattach.
Implements Tgstation.Server.Host.Components.Session.ISessionControllerFactory.
Definition at line 442 of file SessionControllerFactory.cs.
        {
            ArgumentNullException.ThrowIfNull(reattachInformation);
            logger.LogTrace("Begin session reattach...");
            var byondTopicSender = topicClientFactory.CreateTopicClient(reattachInformation.TopicRequestTimeout);
            var engineLock = await engineManager.UseExecutables(
                reattachInformation.Dmb.EngineVersion,
                null, // Doesn't matter if it's trusted or not on reattach
                cancellationToken);
            try
            {
                logger.LogDebug(
                    "Attaching to session PID: {pid}, CompileJob: {compileJobId}...",
                    reattachInformation.ProcessId,
                    reattachInformation.Dmb.CompileJob.Id);
                var process = processExecutor.GetProcess(reattachInformation.ProcessId);
                if (process == null)
                    return null;
                try
                {
                    if (engineLock.PromptsForNetworkAccess)
                        networkPromptReaper.RegisterProcess(process);
                    var chatTrackingContext = chat.CreateTrackingContext();
                    try
                    {
                        var runtimeInformation = CreateRuntimeInformation(
                            reattachInformation.Dmb,
                            chatTrackingContext,
                            reattachInformation.LaunchSecurityLevel,
                            reattachInformation.LaunchVisibility,
                            false);
                        reattachInformation.SetRuntimeInformation(runtimeInformation);
                        var controller = new SessionController(
                            reattachInformation,
                            instance,
                            process,
                            engineLock,
                            byondTopicSender,
                            chatTrackingContext,
                            bridgeRegistrar,
                            chat,
                            assemblyInformationProvider,
                            asyncDelayer,
                            dotnetDumpService,
                            eventConsumer,
                            jobManager,
                            dreamMaker,
                            loggerFactory.CreateLogger<SessionController>(),
                            () => ValueTask.CompletedTask,
                            null,
                            true,
                            false);
                        process = null;
                        engineLock = null;
                        chatTrackingContext = null;
                        return controller;
                    }
                    catch
                    {
                        chatTrackingContext?.Dispose();
                        throw;
                    }
                }
                catch
                {
                    if (process != null)
                        await process.DisposeAsync();
                    throw;
                }
            }
            catch
            {
                engineLock?.Dispose();
                throw;
            }
        }
References Tgstation.Server.Host.Components.Session.SessionControllerFactory.assemblyInformationProvider, Tgstation.Server.Host.Components.Session.SessionControllerFactory.asyncDelayer, Tgstation.Server.Host.Components.Session.SessionControllerFactory.bridgeRegistrar, Tgstation.Server.Host.Components.Session.SessionControllerFactory.chat, Tgstation.Server.Host.Components.Deployment.IDmbProvider.CompileJob, Tgstation.Server.Host.Components.Session.SessionControllerFactory.CreateRuntimeInformation(), Tgstation.Server.Host.Components.Session.ITopicClientFactory.CreateTopicClient(), Tgstation.Server.Host.Components.Chat.IChatManager.CreateTrackingContext(), Tgstation.Server.Host.Components.Session.ReattachInformation.Dmb, Tgstation.Server.Host.Components.Session.SessionControllerFactory.dotnetDumpService, Tgstation.Server.Host.Components.Session.SessionControllerFactory.dreamMaker, Tgstation.Server.Host.Components.Session.SessionControllerFactory.engineManager, Tgstation.Server.Host.Components.Deployment.IDmbProvider.EngineVersion, Tgstation.Server.Host.Components.Session.SessionControllerFactory.eventConsumer, Tgstation.Server.Host.System.IProcessExecutor.GetProcess(), Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Host.Components.Session.SessionControllerFactory.instance, Tgstation.Server.Host.Components.Session.SessionControllerFactory.jobManager, Tgstation.Server.Host.Models.ReattachInformationBase.LaunchSecurityLevel, Tgstation.Server.Host.Models.ReattachInformationBase.LaunchVisibility, Tgstation.Server.Host.Components.Session.SessionControllerFactory.logger, Tgstation.Server.Host.Components.Session.SessionControllerFactory.loggerFactory, Tgstation.Server.Host.Components.Session.SessionControllerFactory.networkPromptReaper, Tgstation.Server.Host.Components.Session.SessionControllerFactory.processExecutor, Tgstation.Server.Host.Models.ReattachInformationBase.ProcessId, Tgstation.Server.Host.System.INetworkPromptReaper.RegisterProcess(), Tgstation.Server.Host.Components.Session.ReattachInformation.SetRuntimeInformation(), Tgstation.Server.Host.Components.Session.SessionControllerFactory.topicClientFactory, Tgstation.Server.Host.Components.Session.ReattachInformation.TopicRequestTimeout, and Tgstation.Server.Host.Components.Engine.IEngineManager.UseExecutables().
Referenced by Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.InitController().
Member Data Documentation
assemblyInformationProvider
readonly IAssemblyInformationProvider Tgstation.Server.Host.Components.Session.SessionControllerFactory.assemblyInformationProvider private
The IAssemblyInformationProvider for the SessionControllerFactory.
Definition at line 66 of file SessionControllerFactory.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionControllerFactory.LaunchNew(), Tgstation.Server.Host.Components.Session.SessionControllerFactory.Reattach(), and Tgstation.Server.Host.Components.Session.SessionControllerFactory.SessionControllerFactory().
asyncDelayer
readonly IAsyncDelayer Tgstation.Server.Host.Components.Session.SessionControllerFactory.asyncDelayer private
The IAsyncDelayer for the SessionControllerFactory.
Definition at line 121 of file SessionControllerFactory.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionControllerFactory.LaunchNew(), Tgstation.Server.Host.Components.Session.SessionControllerFactory.PortBindTest(), Tgstation.Server.Host.Components.Session.SessionControllerFactory.Reattach(), and Tgstation.Server.Host.Components.Session.SessionControllerFactory.SessionControllerFactory().
bridgeRegistrar
readonly IBridgeRegistrar Tgstation.Server.Host.Components.Session.SessionControllerFactory.bridgeRegistrar private
The IBridgeRegistrar for the SessionControllerFactory.
Definition at line 96 of file SessionControllerFactory.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionControllerFactory.LaunchNew(), Tgstation.Server.Host.Components.Session.SessionControllerFactory.Reattach(), and Tgstation.Server.Host.Components.Session.SessionControllerFactory.SessionControllerFactory().
chat
readonly IChatManager Tgstation.Server.Host.Components.Session.SessionControllerFactory.chat private
The IChatManager for the SessionControllerFactory.
Definition at line 81 of file SessionControllerFactory.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionControllerFactory.LaunchNew(), Tgstation.Server.Host.Components.Session.SessionControllerFactory.Reattach(), and Tgstation.Server.Host.Components.Session.SessionControllerFactory.SessionControllerFactory().
cryptographySuite
readonly ICryptographySuite Tgstation.Server.Host.Components.Session.SessionControllerFactory.cryptographySuite private
The ICryptographySuite for the SessionControllerFactory.
Definition at line 61 of file SessionControllerFactory.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionControllerFactory.LaunchNew(), and Tgstation.Server.Host.Components.Session.SessionControllerFactory.SessionControllerFactory().
diagnosticsIOManager
readonly IIOManager Tgstation.Server.Host.Components.Session.SessionControllerFactory.diagnosticsIOManager private
The IIOManager for the Diagnostics directory.
Definition at line 76 of file SessionControllerFactory.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionControllerFactory.LaunchNew(), and Tgstation.Server.Host.Components.Session.SessionControllerFactory.SessionControllerFactory().
dotnetDumpService
readonly IDotnetDumpService Tgstation.Server.Host.Components.Session.SessionControllerFactory.dotnetDumpService private
The IDotnetDumpService for the SessionControllerFactory.
Definition at line 126 of file SessionControllerFactory.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionControllerFactory.LaunchNew(), Tgstation.Server.Host.Components.Session.SessionControllerFactory.Reattach(), and Tgstation.Server.Host.Components.Session.SessionControllerFactory.SessionControllerFactory().
DreamDaemonLogsPath
const string Tgstation.Server.Host.Components.Session.SessionControllerFactory.DreamDaemonLogsPath = "DreamDaemonLogs" static private
Path in Diagnostics folder to DreamDaemon logs.
Definition at line 41 of file SessionControllerFactory.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionControllerFactory.LaunchNew().
dreamMaker
readonly IDreamMaker Tgstation.Server.Host.Components.Session.SessionControllerFactory.dreamMaker private
The IDreamMaker for the SessionControllerFactory.
Definition at line 116 of file SessionControllerFactory.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionControllerFactory.LaunchNew(), Tgstation.Server.Host.Components.Session.SessionControllerFactory.Reattach(), and Tgstation.Server.Host.Components.Session.SessionControllerFactory.SessionControllerFactory().
engineManager
readonly IEngineManager Tgstation.Server.Host.Components.Session.SessionControllerFactory.engineManager private
The IEngineManager for the SessionControllerFactory.
Definition at line 51 of file SessionControllerFactory.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionControllerFactory.LaunchNew(), Tgstation.Server.Host.Components.Session.SessionControllerFactory.Reattach(), and Tgstation.Server.Host.Components.Session.SessionControllerFactory.SessionControllerFactory().
eventConsumer
readonly IEventConsumer Tgstation.Server.Host.Components.Session.SessionControllerFactory.eventConsumer private
The IEventConsumer for the SessionControllerFactory.
Definition at line 106 of file SessionControllerFactory.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionControllerFactory.CreateGameServerProcess(), Tgstation.Server.Host.Components.Session.SessionControllerFactory.LaunchNew(), Tgstation.Server.Host.Components.Session.SessionControllerFactory.Reattach(), and Tgstation.Server.Host.Components.Session.SessionControllerFactory.SessionControllerFactory().
gameIOManager
readonly IIOManager Tgstation.Server.Host.Components.Session.SessionControllerFactory.gameIOManager private
The IIOManager for the Game directory.
Definition at line 71 of file SessionControllerFactory.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionControllerFactory.LaunchNew(), and Tgstation.Server.Host.Components.Session.SessionControllerFactory.SessionControllerFactory().
instance
readonly Api.Models.Instance Tgstation.Server.Host.Components.Session.SessionControllerFactory.instance private
The Api.Models.Instance for the SessionControllerFactory.
Definition at line 156 of file SessionControllerFactory.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionControllerFactory.LaunchNew(), Tgstation.Server.Host.Components.Session.SessionControllerFactory.Reattach(), and Tgstation.Server.Host.Components.Session.SessionControllerFactory.SessionControllerFactory().
jobManager
readonly IJobManager Tgstation.Server.Host.Components.Session.SessionControllerFactory.jobManager private
The IJobManager for the SessionControllerFactory.
Definition at line 111 of file SessionControllerFactory.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionControllerFactory.LaunchNew(), Tgstation.Server.Host.Components.Session.SessionControllerFactory.Reattach(), and Tgstation.Server.Host.Components.Session.SessionControllerFactory.SessionControllerFactory().
lastSessionLaunch
readonly Gauge Tgstation.Server.Host.Components.Session.SessionControllerFactory.lastSessionLaunch private
The time the current session was launched.
Definition at line 151 of file SessionControllerFactory.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionControllerFactory.LaunchNew(), and Tgstation.Server.Host.Components.Session.SessionControllerFactory.SessionControllerFactory().
logger
readonly ILogger<SessionControllerFactory> Tgstation.Server.Host.Components.Session.SessionControllerFactory.logger private
The ILogger for the SessionControllerFactory.
Definition at line 141 of file SessionControllerFactory.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionControllerFactory.CreateGameServerProcess(), Tgstation.Server.Host.Components.Session.SessionControllerFactory.LaunchNew(), Tgstation.Server.Host.Components.Session.SessionControllerFactory.PortBindTest(), Tgstation.Server.Host.Components.Session.SessionControllerFactory.Reattach(), and Tgstation.Server.Host.Components.Session.SessionControllerFactory.SessionControllerFactory().
loggerFactory
readonly ILoggerFactory Tgstation.Server.Host.Components.Session.SessionControllerFactory.loggerFactory private
The ILoggerFactory for the SessionControllerFactory.
Definition at line 131 of file SessionControllerFactory.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionControllerFactory.LaunchNew(), Tgstation.Server.Host.Components.Session.SessionControllerFactory.Reattach(), and Tgstation.Server.Host.Components.Session.SessionControllerFactory.SessionControllerFactory().
networkPromptReaper
readonly INetworkPromptReaper Tgstation.Server.Host.Components.Session.SessionControllerFactory.networkPromptReaper private
The INetworkPromptReaper for the SessionControllerFactory.
Definition at line 86 of file SessionControllerFactory.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionControllerFactory.CreateGameServerProcess(), Tgstation.Server.Host.Components.Session.SessionControllerFactory.Reattach(), and Tgstation.Server.Host.Components.Session.SessionControllerFactory.SessionControllerFactory().
platformIdentifier
readonly IPlatformIdentifier Tgstation.Server.Host.Components.Session.SessionControllerFactory.platformIdentifier private
The IPlatformIdentifier for the SessionControllerFactory.
Definition at line 91 of file SessionControllerFactory.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionControllerFactory.PortBindTest(), and Tgstation.Server.Host.Components.Session.SessionControllerFactory.SessionControllerFactory().
processExecutor
readonly IProcessExecutor Tgstation.Server.Host.Components.Session.SessionControllerFactory.processExecutor private
The IProcessExecutor for the SessionControllerFactory.
Definition at line 46 of file SessionControllerFactory.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionControllerFactory.CreateGameServerProcess(), Tgstation.Server.Host.Components.Session.SessionControllerFactory.Reattach(), and Tgstation.Server.Host.Components.Session.SessionControllerFactory.SessionControllerFactory().
serverPortProvider
readonly IServerPortProvider Tgstation.Server.Host.Components.Session.SessionControllerFactory.serverPortProvider private
The IServerPortProvider for the SessionControllerFactory.
Definition at line 101 of file SessionControllerFactory.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionControllerFactory.CreateGameServerProcess(), and Tgstation.Server.Host.Components.Session.SessionControllerFactory.SessionControllerFactory().
sessionConfigurationOptions
readonly IOptionsMonitor<SessionConfiguration> Tgstation.Server.Host.Components.Session.SessionControllerFactory.sessionConfigurationOptions private
The IOptionsMonitor<TOptions> of SessionConfiguration for the SessionControllerFactory.
Definition at line 136 of file SessionControllerFactory.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionControllerFactory.CreateGameServerProcess(), and Tgstation.Server.Host.Components.Session.SessionControllerFactory.SessionControllerFactory().
sessionsLaunched
readonly Counter Tgstation.Server.Host.Components.Session.SessionControllerFactory.sessionsLaunched private
The number of sessions launched.
Definition at line 146 of file SessionControllerFactory.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionControllerFactory.LaunchNew(), and Tgstation.Server.Host.Components.Session.SessionControllerFactory.SessionControllerFactory().
topicClientFactory
readonly ITopicClientFactory Tgstation.Server.Host.Components.Session.SessionControllerFactory.topicClientFactory private
The ITopicClientFactory for the SessionControllerFactory.
Definition at line 56 of file SessionControllerFactory.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionControllerFactory.LaunchNew(), Tgstation.Server.Host.Components.Session.SessionControllerFactory.Reattach(), and Tgstation.Server.Host.Components.Session.SessionControllerFactory.SessionControllerFactory().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Session/SessionControllerFactory.cs