tgstation-server: Tgstation.Server.Host.Controllers.InstanceUserController Class Reference
Tgstation.Server.Host.Controllers.InstanceUserController Class Reference
ApiController for managing InstanceUsers.
Public Member Functions
InstanceUserController (IDatabaseContext databaseContext, IAuthenticationContextFactory authenticationContextFactory, ILogger< InstanceUserController > logger)
Construct a UserController
async Task< IActionResult > Create ([FromBody] Api.Models.InstanceUser model, CancellationToken cancellationToken)
Create an Api.Models.InstanceUser.
async Task< IActionResult > Update ([FromBody] Api.Models.InstanceUser model, CancellationToken cancellationToken)
Update the permissions for an Api.Models.InstanceUser.
IActionResult Read ()
Read the active Api.Models.InstanceUser.
async Task< IActionResult > List (CancellationToken cancellationToken)
Lists Api.Models.InstanceUsers for the instance.
async Task< IActionResult > GetId (long id, CancellationToken cancellationToken)
Gets a specific Api.Models.InstanceUser.
async Task< IActionResult > Delete (long id, CancellationToken cancellationToken)
Delete an Api.Models.InstanceUser.
Public Member Functions inherited from Tgstation.Server.Host.Controllers.ApiController
ApiController (IDatabaseContext databaseContext, IAuthenticationContextFactory authenticationContextFactory, ILogger logger, bool requireInstance, bool requireHeaders=true)
Construct an ApiController
override async Task OnActionExecutionAsync (ActionExecutingContext context, ActionExecutionDelegate next)
Private Member Functions
IActionResult StandardModelChecks (Api.Models.InstanceUser model)
Checks a model for errors.
Additional Inherited Members
Protected Member Functions inherited from Tgstation.Server.Host.Controllers.ApiController
ObjectResult Gone ()
Generic 410 response.
new NotFoundObjectResult NotFound ()
Generic 404 response.
ObjectResult RequiresPosixSystemIdentity ()
Generic 501 response.
StatusCodeResult StatusCode (HttpStatusCode statusCode)
Strongly type calls to ControllerBase.StatusCode(int).
ObjectResult StatusCode (HttpStatusCode statusCode, object errorMessage)
Strongly type calls to ControllerBase.StatusCode(int, object).
ObjectResult Created (object payload)
Generic 201 response with a given payload .
IActionResult HeadersIssue ()
Response for missing/Invalid headers.
Properties inherited from Tgstation.Server.Host.Controllers.ApiController
ApiHeaders ApiHeaders [get, private set]
The ApiHeaders for the operation
IDatabaseContext DatabaseContext [get]
The IDatabaseContext for the operation
IAuthenticationContext AuthenticationContext [get]
The IAuthenticationContext for the operation
ILogger Logger [get]
The ILogger for the ApiController
Models.Instance Instance [get]
The Instance for the operation
Detailed Description
ApiController for managing InstanceUsers.
Definition at line 23 of file InstanceUserController.cs.
Constructor & Destructor Documentation
Tgstation.Server.Host.Controllers.InstanceUserController.InstanceUserController (IDatabaseContext databaseContext, IAuthenticationContextFactory authenticationContextFactory, ILogger< InstanceUserController > logger)
Construct a UserController
Parameters
databaseContext The IDatabaseContext for the ApiController
authenticationContextFactory The IAuthenticationContextFactory for the ApiController
logger The ILogger for the ApiController
Definition at line 31 of file InstanceUserController.cs.
             : base(
                   databaseContext,
                   authenticationContextFactory,
                   logger,
                   true)
         { }
Member Function Documentation
async Task<IActionResult> Tgstation.Server.Host.Controllers.InstanceUserController.Create ([FromBody] Api.Models.InstanceUser model, CancellationToken cancellationToken)
Create an Api.Models.InstanceUser.
Parameters
model The Api.Models.InstanceUser to create.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the IActionResult of the request.
<response code="201">Api.Models.InstanceUser created successfully.</response>
Definition at line 68 of file InstanceUserController.cs.
References Tgstation.Server.Api.Api, Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Host.Database.DatabaseContext.InstanceUsers, and Tgstation.Server.Host.Database.DatabaseContext.Save().
         {
             // Don't check the result as how can a new user have an ID
             StandardModelChecks(model);
             var dbUser = new Models.InstanceUser
             {
                 ByondRights = RightsHelper.Clamp(model.ByondRights ?? ByondRights.None),
                 ChatBotRights = RightsHelper.Clamp(model.ChatBotRights ?? ChatBotRights.None),
                 ConfigurationRights = RightsHelper.Clamp(model.ConfigurationRights ?? ConfigurationRights.None),
                 DreamDaemonRights = RightsHelper.Clamp(model.DreamDaemonRights ?? DreamDaemonRights.None),
                 DreamMakerRights = RightsHelper.Clamp(model.DreamMakerRights ?? DreamMakerRights.None),
                 RepositoryRights = RightsHelper.Clamp(model.RepositoryRights ?? RepositoryRights.None),
                 InstanceUserRights = RightsHelper.Clamp(model.InstanceUserRights ?? InstanceUserRights.None),
                 UserId = model.UserId,
                 InstanceId = Instance.Id
             };
             DatabaseContext.InstanceUsers.Add(dbUser);
             await DatabaseContext.Save(cancellationToken).ConfigureAwait(false);
             return Created(dbUser.ToApi());
         }
async Task<IActionResult> Tgstation.Server.Host.Controllers.InstanceUserController.Delete (long id, CancellationToken cancellationToken)
Delete an Api.Models.InstanceUser.
Parameters
id The Api.Models.InstanceUser.UserId to delete.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the IActionResult of the request.
<response code="204">Api.Models.InstanceUser deleted or no longer exists.</response>
Definition at line 206 of file InstanceUserController.cs.
References Tgstation.Server.Api.Models.EntityId.Id, and Tgstation.Server.Host.Database.DatabaseContext.Instances.
         {
             await DatabaseContext
                 .Instances
                 .AsQueryable()
                 .Where(x => x.Id == Instance.Id)
                 .SelectMany(x => x.InstanceUsers)
                 .Where(x => x.UserId == id)
                 .DeleteAsync(cancellationToken)
                 .ConfigureAwait(false);
             return NoContent();
         }
async Task<IActionResult> Tgstation.Server.Host.Controllers.InstanceUserController.GetId (long id, CancellationToken cancellationToken)
Gets a specific Api.Models.InstanceUser.
Parameters
id The Api.Models.InstanceUser.UserId.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the IActionResult of the request.
<response code="200">Retrieve Api.Models.InstanceUser successfully.</response> <response code="410">The requested Api.Models.InstanceUser does not currently exist.</response>
Definition at line 180 of file InstanceUserController.cs.
References Tgstation.Server.Api.Models.EntityId.Id, and Tgstation.Server.Host.Database.DatabaseContext.Instances.
         {
             // this functions as userId
             var user = await DatabaseContext
                 .Instances
                 .AsQueryable()
                 .Where(x => x.Id == Instance.Id)
                 .SelectMany(x => x.InstanceUsers)
                 .Where(x => x.UserId == id)
                 .FirstOrDefaultAsync(cancellationToken)
                 .ConfigureAwait(false);
             if (user == default)
                 return Gone();
             return Json(user.ToApi());
         }
async Task<IActionResult> Tgstation.Server.Host.Controllers.InstanceUserController.List (CancellationToken cancellationToken)
Lists Api.Models.InstanceUsers for the instance.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the IActionResult of the request.
<response code="200">Retrieved Api.Models.InstanceUsers successfully.</response>
Definition at line 156 of file InstanceUserController.cs.
References Tgstation.Server.Api.Api, Tgstation.Server.Api.Models.EntityId.Id, and Tgstation.Server.Host.Database.DatabaseContext.Instances.
         {
             var users = await DatabaseContext
                 .Instances
                 .AsQueryable()
                 .Where(x => x.Id == Instance.Id)
                 .SelectMany(x => x.InstanceUsers)
                 .ToListAsync(cancellationToken)
                 .ConfigureAwait(false);
             return Json(users.Select(x => x.ToApi()));
         }
IActionResult Tgstation.Server.Host.Controllers.InstanceUserController.Read ()
Read the active Api.Models.InstanceUser.
Returns
The IActionResult of the request.
<response code="200">Api.Models.InstanceUser retrieved successfully.</response>
IActionResult Tgstation.Server.Host.Controllers.InstanceUserController.StandardModelChecks (Api.Models.InstanceUser model) private
Checks a model for errors.
Parameters
model The Api.Models.InstanceUser to check
Returns
The IActionResult to take if this is not a new Api.Models.InstanceUser
Definition at line 47 of file InstanceUserController.cs.
References Tgstation.Server.Api.Api.
         {
             if (model == null)
                 throw new ArgumentNullException(nameof(model));
             if (!model.UserId.HasValue)
                 return BadRequest(new ErrorMessage(ErrorCode.UserMissingId));
             return null;
         }
async Task<IActionResult> Tgstation.Server.Host.Controllers.InstanceUserController.Update ([FromBody] Api.Models.InstanceUser model, CancellationToken cancellationToken)
Update the permissions for an Api.Models.InstanceUser.
Parameters
model The updated Api.Models.InstanceUser.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the IActionResult of the request.
<response code="200">Api.Models.InstanceUser updated successfully.</response> <response code="410">The requested Api.Models.InstanceUser does not currently exist.</response>
Definition at line 105 of file InstanceUserController.cs.
References Tgstation.Server.Api.Api, Tgstation.Server.Host.Security.AuthenticationContext.GetRight(), Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Api.Models.Internal.User.Id, Tgstation.Server.Host.Database.DatabaseContext.Instances, Tgstation.Server.Host.Security.AuthenticationContext.InstanceUser, Tgstation.Server.Api.Routes.List, Tgstation.Server.Api.Rights.Read, Tgstation.Server.Host.Database.DatabaseContext.Save(), and Tgstation.Server.Host.Security.AuthenticationContext.User.
         {
             var earlyOut = StandardModelChecks(model);
             if (earlyOut != null)
                 return earlyOut;
             var originalUser = await DatabaseContext
                 .Instances
                 .AsQueryable()
                 .Where(x => x.Id == Instance.Id)
                 .SelectMany(x => x.InstanceUsers)
                 .Where(x => x.UserId == model.UserId)
                 .FirstOrDefaultAsync(cancellationToken)
                 .ConfigureAwait(false);
             if (originalUser == null)
                 return Gone();
             originalUser.ByondRights = RightsHelper.Clamp(model.ByondRights ?? originalUser.ByondRights.Value);
             originalUser.RepositoryRights = RightsHelper.Clamp(model.RepositoryRights ?? originalUser.RepositoryRights.Value);
             originalUser.InstanceUserRights = RightsHelper.Clamp(model.InstanceUserRights ?? originalUser.InstanceUserRights.Value);
             originalUser.ChatBotRights = RightsHelper.Clamp(model.ChatBotRights ?? originalUser.ChatBotRights.Value);
             originalUser.ConfigurationRights = RightsHelper.Clamp(model.ConfigurationRights ?? originalUser.ConfigurationRights.Value);
             originalUser.DreamDaemonRights = RightsHelper.Clamp(model.DreamDaemonRights ?? originalUser.DreamDaemonRights.Value);
             originalUser.DreamMakerRights = RightsHelper.Clamp(model.DreamMakerRights ?? originalUser.DreamMakerRights.Value);
             await DatabaseContext.Save(cancellationToken).ConfigureAwait(false);
             return Json(originalUser.UserId == AuthenticationContext.User.Id || (AuthenticationContext.GetRight(RightsType.InstanceUser) & (ulong)InstanceUserRights.ReadUsers) != 0 ? originalUser.ToApi() : new Api.Models.InstanceUser
             {
                 UserId = originalUser.UserId
             });
         }
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Controllers/InstanceUserController.cs