tgstation-server: Tgstation.Server.Tests.UsersTest Class Reference
Tgstation.Server.Tests.UsersTest Class Reference
Public Member Functions
UsersTest (IUsersClient client)
async Task Run (CancellationToken cancellationToken)
Private Member Functions
async Task TestRetrieveCurrentUser (CancellationToken cancellationToken)
async Task TestSpamCreation (CancellationToken cancellationToken)
Private Attributes
readonly IUsersClient client
Detailed Description
Definition at line 12 of file UsersTest.cs.
Constructor & Destructor Documentation
UsersTest()
Tgstation.Server.Tests.UsersTest.UsersTest (IUsersClient client)
Definition at line 16 of file UsersTest.cs.
         {
             this.client = client ?? throw new ArgumentNullException(nameof(client));
         }
References Tgstation.Server.Tests.UsersTest.client.
Member Function Documentation
Run()
async Task Tgstation.Server.Tests.UsersTest.Run (CancellationToken cancellationToken)
Definition at line 21 of file UsersTest.cs.
         {
             await TestRetrieveCurrentUser(cancellationToken).ConfigureAwait(false);
             await TestSpamCreation(cancellationToken).ConfigureAwait(false);
         }
References Tgstation.Server.Tests.UsersTest.TestRetrieveCurrentUser(), and Tgstation.Server.Tests.UsersTest.TestSpamCreation().
Referenced by Tgstation.Server.Tests.IntegrationTest.TestFullStandardOperation().
TestRetrieveCurrentUser()
async Task Tgstation.Server.Tests.UsersTest.TestRetrieveCurrentUser (CancellationToken cancellationToken) private
Definition at line 27 of file UsersTest.cs.
         {
             var user = await this.client.Read(cancellationToken).ConfigureAwait(false);
             Assert.IsNotNull(user);
             Assert.AreEqual("Admin", user.Name);
             Assert.IsNull(user.SystemIdentifier);
             Assert.AreEqual(true, user.Enabled);
         }
Referenced by Tgstation.Server.Tests.UsersTest.Run().
TestSpamCreation()
async Task Tgstation.Server.Tests.UsersTest.TestSpamCreation (CancellationToken cancellationToken) private
Definition at line 36 of file UsersTest.cs.
         {
             ICollection<Task<User>> tasks = new List<Task<User>>();
             // Careful with this, very easy to overload the thread pool
             const int RepeatCount = 100;
             ThreadPool.GetMaxThreads(out var defaultMaxWorker, out var defaultMaxCompletion);
             ThreadPool.GetMinThreads(out var defaultMinWorker, out var defaultMinCompletion);
             try
             {
                 ThreadPool.SetMinThreads(Math.Min(RepeatCount * 4, defaultMaxWorker), Math.Min(RepeatCount * 4, defaultMaxCompletion));
                 for (int i = 0; i < RepeatCount; ++i)
                 {
                     tasks.Add(
                         client.Create(
                             new UserUpdate
{
                                 Name = $"SpamTestUser_{i}",
                                 Password = "asdfasdjfhauwiehruiy273894234jhndjkwh"
                             },
                             cancellationToken));
                 }
                 await Task.WhenAll(tasks).ConfigureAwait(false);
             }
             finally
             {
                 ThreadPool.SetMinThreads(defaultMinWorker, defaultMinCompletion);
             }
             Assert.AreEqual(RepeatCount, tasks.Select(task => task.Result.Id).Distinct().Count(), "Did not receive expected number of unique user IDs!");
         }
References Tgstation.Server.Tests.UsersTest.client, and Tgstation.Server.Client.IUsersClient.Create().
Referenced by Tgstation.Server.Tests.UsersTest.Run().
Member Data Documentation
client
readonly IUsersClient Tgstation.Server.Tests.UsersTest.client private
Definition at line 14 of file UsersTest.cs.
Referenced by Tgstation.Server.Tests.UsersTest.TestSpamCreation(), and Tgstation.Server.Tests.UsersTest.UsersTest().
The documentation for this class was generated from the following file:
tests/Tgstation.Server.Tests/UsersTest.cs