tgstation-server: Tgstation.Server.Host.System.WindowsFirewallHelper Class Reference
Tgstation.Server.Host.System.WindowsFirewallHelper Class Reference
Helper class for interacting with the Windows Firewall.
Static Public Member Functions
static async ValueTask< int > AddFirewallException (IProcessExecutor processExecutor, ILogger logger, string exceptionName, string exePath, bool lowPriority, CancellationToken cancellationToken)
Add an executable exception to the Windows firewall.
Detailed Description
Helper class for interacting with the Windows Firewall.
Definition at line 12 of file WindowsFirewallHelper.cs.
Member Function Documentation
AddFirewallException()
static async ValueTask< int > Tgstation.Server.Host.System.WindowsFirewallHelper.AddFirewallException (IProcessExecutor processExecutor, ILogger logger, string exceptionName, string exePath, bool lowPriority, CancellationToken cancellationToken) static
Add an executable exception to the Windows firewall.
Parameters
processExecutor The IProcessExecutor to use.
logger The ILogger to write to.
exceptionName The name of the rule in Windows Firewall.
exePath The path to the .exe to add a firewall exception for.
lowPriority If the "netsh.exe" process should be run with lower process priority.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the exit code of the call to netsh.exe.
Definition at line 24 of file WindowsFirewallHelper.cs.
        {
            logger.LogInformation("Adding Windows Firewall exception for {path}...", exePath);
            var arguments = $"advfirewall firewall add rule name=\"{exceptionName}\" program=\"{exePath}\" protocol=tcp dir=in enable=yes action=allow";
            await using var netshProcess = await processExecutor.LaunchProcess(
                "netsh.exe",
                Environment.CurrentDirectory,
                arguments,
                cancellationToken,
                readStandardHandles: true,
                noShellExecute: true);
            if (lowPriority)
                netshProcess.AdjustPriority(false);
            int exitCode;
            using (cancellationToken.Register(() => netshProcess.Terminate()))
                exitCode = (await netshProcess.Lifetime).Value;
            cancellationToken.ThrowIfCancellationRequested();
            logger.LogDebug(
                "netsh.exe output:{newLine}{output}",
                Environment.NewLine,
                await netshProcess.GetCombinedOutput(cancellationToken));
            return exitCode;
        }
References Tgstation.Server.Host.System.IProcessExecutor.LaunchProcess().
Referenced by Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.AddDreamDaemonToFirewall(), and Tgstation.Server.Host.Components.Engine.WindowsOpenDreamInstaller.AddServerFirewallException().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/System/WindowsFirewallHelper.cs