tgstation-server: Tgstation.Server.Host.GraphQL.Mutations.UserMutations Class Reference
Tgstation.Server.Host.GraphQL.Mutations.UserMutations Class Reference sealed
IUserAuthority related Mutations.
Public Member Functions
ValueTask< UpdatedUser > CreateUserByPasswordAndPermissionSet (string name, string password, bool? enabled, IEnumerable< OAuthConnection >? oAuthConnections, IEnumerable< OidcConnection >? oidcConnections, PermissionSetInput? permissionSet, [Service] IGraphQLAuthorityInvoker< IUserAuthority > userAuthority, CancellationToken cancellationToken)
Creates a TGS user specifying a personal PermissionSet.
ValueTask< UpdatedUser > CreateUserByPasswordAndGroup (string name, string password, bool? enabled, IEnumerable< OAuthConnection >? oAuthConnections, IEnumerable< OidcConnection >? oidcConnections, [ID(nameof(UserGroup))] long groupId, [Service] IGraphQLAuthorityInvoker< IUserAuthority > userAuthority, CancellationToken cancellationToken)
Creates a TGS user specifying the UserGroup they will belong to.
ValueTask< UpdatedUser > CreateUserByServiceConnectionAndPermissionSet (string name, IEnumerable< OAuthConnection >? oAuthConnections, IEnumerable< OidcConnection >? oidcConnections, bool? enabled, PermissionSetInput? permissionSet, [Service] IGraphQLAuthorityInvoker< IUserAuthority > userAuthority, CancellationToken cancellationToken)
Creates a TGS user authenticated with one or more OAuthConnections or OidcConnections specifying a personal PermissionSet.
ValueTask< UpdatedUser > CreateUserByServiceConnectionAndGroup (string name, IEnumerable< OAuthConnection > oAuthConnections, IEnumerable< OidcConnection > oidcConnections, [ID(nameof(UserGroup))] long groupId, bool? enabled, [Service] IGraphQLAuthorityInvoker< IUserAuthority > userAuthority, CancellationToken cancellationToken)
Creates a TGS user using OAuthConnections and/or OidcConnections specifying the UserGroup they will belong to.
ValueTask< UpdatedUser > CreateUserBySystemIDAndPermissionSet (string systemIdentifier, bool? enabled, IEnumerable< OAuthConnection >? oAuthConnections, IEnumerable< OidcConnection >? oidcConnections, PermissionSetInput permissionSet, [Service] IGraphQLAuthorityInvoker< IUserAuthority > userAuthority, CancellationToken cancellationToken)
Creates a system user specifying a personal PermissionSet.
ValueTask< UpdatedUser > CreateUserBySystemIDAndGroup (string systemIdentifier, bool? enabled, [ID(nameof(UserGroup))] long groupId, IEnumerable< OAuthConnection >? oAuthConnections, IEnumerable< OidcConnection >? oidcConnections, [Service] IGraphQLAuthorityInvoker< IUserAuthority > userAuthority, CancellationToken cancellationToken)
Creates a system user specifying the UserGroup they will belong to.
ValueTask< UpdatedUser > SetCurrentUserPassword (string newPassword, [Service] IAuthenticationContext authenticationContext, [Service] IGraphQLAuthorityInvoker< IUserAuthority > userAuthority, CancellationToken cancellationToken)
Sets the current user's password.
ValueTask< UpdatedUser > SetCurrentServiceConnections (IEnumerable< OAuthConnection >? newOAuthConnections, IEnumerable< OidcConnection >? newOidcConnections, [Service] IAuthenticationContext authenticationContext, [Service] IGraphQLAuthorityInvoker< IUserAuthority > userAuthority, CancellationToken cancellationToken)
Sets the current user's OAuthConnections and OidcConnections.
ValueTask< UpdatedUser > UpdateUser ([ID(nameof(User))] long id, string? casingOnlyNameChange, string? newPassword, bool? enabled, IEnumerable< OAuthConnection >? newOAuthConnections, IEnumerable< OidcConnection >? newOidcConnections, [Service] IGraphQLAuthorityInvoker< IUserAuthority > userAuthority, CancellationToken cancellationToken)
Updates a Users properties.
ValueTask< UpdatedUser > UpdateUserSetOwnedPermissionSet ([ID(nameof(User))] long id, string? casingOnlyNameChange, string? newPassword, bool? enabled, PermissionSetInput newPermissionSet, IEnumerable< OAuthConnection >? newOAuthConnections, IEnumerable< OidcConnection >? newOidcConnections, [Service] IGraphQLAuthorityInvoker< IUserAuthority > userAuthority, CancellationToken cancellationToken)
Updates a User, setting new values for its owned PermissionSet.
ValueTask< UpdatedUser > UpdateUserSetGroup ([ID(nameof(User))] long id, string? casingOnlyNameChange, string? newPassword, bool? enabled, [ID(nameof(UserGroup))] long newGroupId, IEnumerable< OAuthConnection >? newOAuthConnections, IEnumerable< OidcConnection >? newOidcConnections, [Service] IGraphQLAuthorityInvoker< IUserAuthority > userAuthority, CancellationToken cancellationToken)
Updates a User, setting new values for its owned PermissionSet.
Private Member Functions
ValueTask< UpdatedUser > UpdateUserCore ([ID(nameof(User))] long id, string? casingOnlyNameChange, string? newPassword, bool? enabled, PermissionSetInput? newPermissionSet, long? newGroupId, IEnumerable< OAuthConnection >? newOAuthConnections, IEnumerable< OidcConnection >? newOidcConnections, IGraphQLAuthorityInvoker< IUserAuthority > userAuthority, CancellationToken cancellationToken)
Updates a user.
ValueTask< UpdatedUser > UpdatedUserGraphQLTransformer (authority=> authority.Update(new UserUpdateRequest { Id=id, Name=casingOnlyNameChange, Password=newPassword, Enabled=enabled, PermissionSet=newPermissionSet !=null ? new Api.Models.PermissionSet { InstanceManagerRights=newPermissionSet.InstanceManagerRights, AdministrationRights=newPermissionSet.AdministrationRights, } :null, Group=newGroupId.HasValue ? new Api.Models.Internal.UserGroup { Id=newGroupId.Value, } :null, OAuthConnections=newOAuthConnections ?.Select(oAuthConnection=> new Api.Models.OAuthConnection { ExternalUserId=oAuthConnection.ExternalUserId, Provider=oAuthConnection.Provider, }) .ToList(), OidcConnections=newOidcConnections ?.Select(oidcConnection=> new Api.Models.OidcConnection { ExternalUserId=oidcConnection.ExternalUserId, SchemeKey=oidcConnection.SchemeKey, }) .ToList(), }, cancellationToken))
Private Attributes
ValueTask< UpdatedUser > UpdatedUser
Detailed Description
IUserAuthority related Mutations.
Definition at line 26 of file UserMutations.cs.
Member Function Documentation
CreateUserByPasswordAndGroup()
ValueTask< UpdatedUser > Tgstation.Server.Host.GraphQL.Mutations.UserMutations.CreateUserByPasswordAndGroup (string name, string password, bool? enabled, IEnumerable< OAuthConnection >? oAuthConnections, IEnumerable< OidcConnection >? oidcConnections, [ID(nameof(UserGroup))] long groupId, [Service] IGraphQLAuthorityInvoker< IUserAuthority > userAuthority, CancellationToken cancellationToken)
Creates a TGS user specifying the UserGroup they will belong to.
Parameters
name The NamedEntity.Name of the User.
password The password of the User.
enabled If the User is User.Enabled.
oAuthConnections The OAuthConnections for the user.
oidcConnections The OidcConnections for the user.
groupId The Entity.Id of the UserGroup the User will belong to.
userAuthority The IGraphQLAuthorityInvoker<TAuthority> for the IUserAuthority.
cancellationToken The CancellationToken for the operation.
Returns
The created User.
Definition at line 101 of file UserMutations.cs.
        {
            ArgumentNullException.ThrowIfNull(name);
            ArgumentNullException.ThrowIfNull(password);
            ArgumentNullException.ThrowIfNull(userAuthority);
            return userAuthority.InvokeTransformable<Models.UpdatedUser, UpdatedUser, UpdatedUserGraphQLTransformer>(
                authority => authority.Create(
                    new UserCreateRequest
                    {
                        Name = name,
                        Password = password,
                        Enabled = enabled,
                        Group = new Api.Models.Internal.UserGroup
{
                            Id = groupId,
                        },
                        OAuthConnections = oAuthConnections
                            ?.Select(oAuthConnection => new Api.Models.OAuthConnection
{
                                ExternalUserId = oAuthConnection.ExternalUserId,
                                Provider = oAuthConnection.Provider,
                            })
                            .ToList(),
                        OidcConnections = oidcConnections
                            ?.Select(oidcConnection => new Api.Models.OidcConnection
{
                                ExternalUserId = oidcConnection.ExternalUserId,
                                SchemeKey = oidcConnection.SchemeKey,
                            })
                            .ToList(),
                    },
                    false,
                    cancellationToken));
        }
References Tgstation.Server.Host.Enabled, Tgstation.Server.Host.Authority.Id, and Tgstation.Server.Host.GraphQL.Mutations.UserMutations.UpdatedUser.
CreateUserByPasswordAndPermissionSet()
ValueTask< UpdatedUser > Tgstation.Server.Host.GraphQL.Mutations.UserMutations.CreateUserByPasswordAndPermissionSet (string name, string password, bool? enabled, IEnumerable< OAuthConnection >? oAuthConnections, IEnumerable< OidcConnection >? oidcConnections, PermissionSetInput? permissionSet, [Service] IGraphQLAuthorityInvoker< IUserAuthority > userAuthority, CancellationToken cancellationToken)
Creates a TGS user specifying a personal PermissionSet.
Parameters
name The NamedEntity.Name of the User.
password The password of the User.
enabled If the User is User.Enabled.
oAuthConnections The OAuthConnections for the user.
oidcConnections The OidcConnections for the user.
permissionSet The owned PermissionSet of the user.
userAuthority The IGraphQLAuthorityInvoker<TAuthority> for the IUserAuthority.
cancellationToken The CancellationToken for the operation.
Returns
The created User.
Definition at line 41 of file UserMutations.cs.
        {
            ArgumentNullException.ThrowIfNull(name);
            ArgumentNullException.ThrowIfNull(password);
            ArgumentNullException.ThrowIfNull(userAuthority);
            return userAuthority.InvokeTransformable<Models.UpdatedUser, UpdatedUser, UpdatedUserGraphQLTransformer>(
                authority => authority.Create(
                    new UserCreateRequest
                    {
                        Name = name,
                        Password = password,
                        Enabled = enabled,
                        PermissionSet = permissionSet != null
                            ? new Api.Models.PermissionSet
{
                                AdministrationRights = permissionSet.AdministrationRights,
                                InstanceManagerRights = permissionSet.InstanceManagerRights,
                            }
                            : null,
                        OAuthConnections = oAuthConnections
                            ?.Select(oAuthConnection => new Api.Models.OAuthConnection
{
                                ExternalUserId = oAuthConnection.ExternalUserId,
                                Provider = oAuthConnection.Provider,
                            })
                            .ToList(),
                        OidcConnections = oidcConnections
                            ?.Select(oidcConnection => new Api.Models.OidcConnection
{
                                ExternalUserId = oidcConnection.ExternalUserId,
                                SchemeKey = oidcConnection.SchemeKey,
                            })
                            .ToList(),
                    },
                    false,
                    cancellationToken));
        }
References Tgstation.Server.Host.GraphQL.Mutations.Payloads.PermissionSetInput.AdministrationRights, Tgstation.Server.Host.Enabled, Tgstation.Server.Host.GraphQL.Mutations.Payloads.PermissionSetInput.InstanceManagerRights, and Tgstation.Server.Host.GraphQL.Mutations.UserMutations.UpdatedUser.
CreateUserByServiceConnectionAndGroup()
ValueTask< UpdatedUser > Tgstation.Server.Host.GraphQL.Mutations.UserMutations.CreateUserByServiceConnectionAndGroup (string name, IEnumerable< OAuthConnection > oAuthConnections, IEnumerable< OidcConnection > oidcConnections, [ID(nameof(UserGroup))] long groupId, bool? enabled, [Service] IGraphQLAuthorityInvoker< IUserAuthority > userAuthority, CancellationToken cancellationToken)
Creates a TGS user using OAuthConnections and/or OidcConnections specifying the UserGroup they will belong to.
Parameters
name The NamedEntity.Name of the User.
oAuthConnections The OAuthConnections for the user.
oidcConnections The OidcConnections for the user.
groupId The Entity.Id of the UserGroup the User will belong to.
enabled If the User is User.Enabled.
userAuthority The IGraphQLAuthorityInvoker<TAuthority> for the IUserAuthority.
cancellationToken The CancellationToken for the operation.
Returns
The created User.
Definition at line 215 of file UserMutations.cs.
        {
            ArgumentNullException.ThrowIfNull(name);
            ArgumentNullException.ThrowIfNull(oAuthConnections);
            ArgumentNullException.ThrowIfNull(userAuthority);
            return userAuthority.InvokeTransformable<Models.UpdatedUser, UpdatedUser, UpdatedUserGraphQLTransformer>(
                authority => authority.Create(
                    new UserCreateRequest
                    {
                        Name = name,
                        Password = String.Empty,
                        Enabled = enabled,
                        Group = new Api.Models.Internal.UserGroup
{
                            Id = groupId,
                        },
                        OAuthConnections = oAuthConnections
                            .Select(oAuthConnection => new Api.Models.OAuthConnection
{
                                ExternalUserId = oAuthConnection.ExternalUserId,
                                Provider = oAuthConnection.Provider,
                            })
                            .ToList(),
                        OidcConnections = oidcConnections
                            ?.Select(oidcConnection => new Api.Models.OidcConnection
{
                                ExternalUserId = oidcConnection.ExternalUserId,
                                SchemeKey = oidcConnection.SchemeKey,
                            })
                            .ToList(),
                    },
                    true,
                    cancellationToken));
        }
References Tgstation.Server.Host.Enabled, Tgstation.Server.Host.Authority.Id, and Tgstation.Server.Host.GraphQL.Mutations.UserMutations.UpdatedUser.
CreateUserByServiceConnectionAndPermissionSet()
ValueTask< UpdatedUser > Tgstation.Server.Host.GraphQL.Mutations.UserMutations.CreateUserByServiceConnectionAndPermissionSet (string name, IEnumerable< OAuthConnection >? oAuthConnections, IEnumerable< OidcConnection >? oidcConnections, bool? enabled, PermissionSetInput? permissionSet, [Service] IGraphQLAuthorityInvoker< IUserAuthority > userAuthority, CancellationToken cancellationToken)
Creates a TGS user authenticated with one or more OAuthConnections or OidcConnections specifying a personal PermissionSet.
Parameters
name The NamedEntity.Name of the User.
oAuthConnections The OAuthConnections for the user.
oidcConnections The OidcConnections for the user.
enabled If the User is User.Enabled.
permissionSet The owned PermissionSet of the user.
userAuthority The IGraphQLAuthorityInvoker<TAuthority> for the IUserAuthority.
cancellationToken The CancellationToken for the operation.
Returns
The created User.
Definition at line 157 of file UserMutations.cs.
        {
            ArgumentNullException.ThrowIfNull(name);
            ArgumentNullException.ThrowIfNull(oAuthConnections);
            ArgumentNullException.ThrowIfNull(userAuthority);
            return userAuthority.InvokeTransformable<Models.UpdatedUser, UpdatedUser, UpdatedUserGraphQLTransformer>(
                authority => authority.Create(
                    new UserCreateRequest
                    {
                        Name = name,
                        Password = String.Empty,
                        Enabled = enabled,
                        PermissionSet = permissionSet != null
                            ? new Api.Models.PermissionSet
{
                                AdministrationRights = permissionSet.AdministrationRights,
                                InstanceManagerRights = permissionSet.InstanceManagerRights,
                            }
                            : null,
                        OAuthConnections = oAuthConnections
                            .Select(oAuthConnection => new Api.Models.OAuthConnection
{
                                ExternalUserId = oAuthConnection.ExternalUserId,
                                Provider = oAuthConnection.Provider,
                            })
                            .ToList(),
                        OidcConnections = oidcConnections
                            ?.Select(oidcConnection => new Api.Models.OidcConnection
{
                                ExternalUserId = oidcConnection.ExternalUserId,
                                SchemeKey = oidcConnection.SchemeKey,
                            })
                            .ToList(),
                    },
                    true,
                    cancellationToken));
        }
References Tgstation.Server.Host.GraphQL.Mutations.Payloads.PermissionSetInput.AdministrationRights, Tgstation.Server.Host.Enabled, Tgstation.Server.Host.GraphQL.Mutations.Payloads.PermissionSetInput.InstanceManagerRights, and Tgstation.Server.Host.GraphQL.Mutations.UserMutations.UpdatedUser.
CreateUserBySystemIDAndGroup()
ValueTask< UpdatedUser > Tgstation.Server.Host.GraphQL.Mutations.UserMutations.CreateUserBySystemIDAndGroup (string systemIdentifier, bool? enabled, [ID(nameof(UserGroup))] long groupId, IEnumerable< OAuthConnection >? oAuthConnections, IEnumerable< OidcConnection >? oidcConnections, [Service] IGraphQLAuthorityInvoker< IUserAuthority > userAuthority, CancellationToken cancellationToken)
Creates a system user specifying the UserGroup they will belong to.
Parameters
systemIdentifier The User.SystemIdentifier of the User.
enabled If the User is User.Enabled.
groupId The Entity.Id of the UserGroup the User will belong to.
oAuthConnections The OAuthConnections for the user.
oidcConnections The OidcConnections for the user.
userAuthority The IGraphQLAuthorityInvoker<TAuthority> for the IUserAuthority.
cancellationToken The CancellationToken for the operation.
Returns
The created User.
Definition at line 326 of file UserMutations.cs.
        {
            ArgumentNullException.ThrowIfNull(systemIdentifier);
            ArgumentNullException.ThrowIfNull(userAuthority);
            return userAuthority.InvokeTransformable<Models.UpdatedUser, UpdatedUser, UpdatedUserGraphQLTransformer>(
                authority => authority.Create(
                    new UserCreateRequest
                    {
                        SystemIdentifier = systemIdentifier,
                        Enabled = enabled,
                        Group = new Api.Models.Internal.UserGroup
{
                            Id = groupId,
                        },
                        OAuthConnections = oAuthConnections
                            ?.Select(oAuthConnection => new Api.Models.OAuthConnection
{
                                ExternalUserId = oAuthConnection.ExternalUserId,
                                Provider = oAuthConnection.Provider,
                            })
                            .ToList(),
                        OidcConnections = oidcConnections
                            ?.Select(oidcConnection => new Api.Models.OidcConnection
{
                                ExternalUserId = oidcConnection.ExternalUserId,
                                SchemeKey = oidcConnection.SchemeKey,
                            })
                            .ToList(),
                    },
                    false,
                    cancellationToken));
        }
References Tgstation.Server.Host.Enabled, Tgstation.Server.Host.Authority.Id, and Tgstation.Server.Host.GraphQL.Mutations.UserMutations.UpdatedUser.
CreateUserBySystemIDAndPermissionSet()
ValueTask< UpdatedUser > Tgstation.Server.Host.GraphQL.Mutations.UserMutations.CreateUserBySystemIDAndPermissionSet (string systemIdentifier, bool? enabled, IEnumerable< OAuthConnection >? oAuthConnections, IEnumerable< OidcConnection >? oidcConnections, PermissionSetInput permissionSet, [Service] IGraphQLAuthorityInvoker< IUserAuthority > userAuthority, CancellationToken cancellationToken)
Creates a system user specifying a personal PermissionSet.
Parameters
systemIdentifier The User.SystemIdentifier of the User.
enabled If the User is User.Enabled.
oAuthConnections The OAuthConnections for the user.
oidcConnections The OidcConnections for the user.
permissionSet The owned PermissionSet of the user.
userAuthority The IGraphQLAuthorityInvoker<TAuthority> for the IUserAuthority.
cancellationToken The CancellationToken for the operation.
Returns
The created User.
Definition at line 270 of file UserMutations.cs.
        {
            ArgumentNullException.ThrowIfNull(systemIdentifier);
            ArgumentNullException.ThrowIfNull(userAuthority);
            return userAuthority.InvokeTransformable<Models.UpdatedUser, UpdatedUser, UpdatedUserGraphQLTransformer>(
                authority => authority.Create(
                    new UserCreateRequest
                    {
                        SystemIdentifier = systemIdentifier,
                        Enabled = enabled,
                        PermissionSet = permissionSet != null
                            ? new Api.Models.PermissionSet
{
                                AdministrationRights = permissionSet.AdministrationRights,
                                InstanceManagerRights = permissionSet.InstanceManagerRights,
                            }
                            : null,
                        OAuthConnections = oAuthConnections
                            ?.Select(oAuthConnection => new Api.Models.OAuthConnection
{
                                ExternalUserId = oAuthConnection.ExternalUserId,
                                Provider = oAuthConnection.Provider,
                            })
                            .ToList(),
                        OidcConnections = oidcConnections
                            ?.Select(oidcConnection => new Api.Models.OidcConnection
{
                                ExternalUserId = oidcConnection.ExternalUserId,
                                SchemeKey = oidcConnection.SchemeKey,
                            })
                            .ToList(),
                    },
                    false,
                    cancellationToken));
        }
References Tgstation.Server.Host.GraphQL.Mutations.Payloads.PermissionSetInput.AdministrationRights, Tgstation.Server.Host.Enabled, Tgstation.Server.Host.GraphQL.Mutations.Payloads.PermissionSetInput.InstanceManagerRights, and Tgstation.Server.Host.GraphQL.Mutations.UserMutations.UpdatedUser.
SetCurrentServiceConnections()
ValueTask< UpdatedUser > Tgstation.Server.Host.GraphQL.Mutations.UserMutations.SetCurrentServiceConnections (IEnumerable< OAuthConnection >? newOAuthConnections, IEnumerable< OidcConnection >? newOidcConnections, [Service] IAuthenticationContext authenticationContext, [Service] IGraphQLAuthorityInvoker< IUserAuthority > userAuthority, CancellationToken cancellationToken)
Sets the current user's OAuthConnections and OidcConnections.
Parameters
newOAuthConnections Optional new OAuthConnections for the current User.
newOidcConnections Optional new OidcConnections for the current User.
authenticationContext The IAuthenticationContext to get the Entity.Id of the user.
userAuthority The IGraphQLAuthorityInvoker<TAuthority> for the IUserAuthority.
cancellationToken The CancellationToken for the operation.
Returns
The updated current User.
Definition at line 404 of file UserMutations.cs.
        {
            ArgumentNullException.ThrowIfNull(newOAuthConnections);
            ArgumentNullException.ThrowIfNull(userAuthority);
            return userAuthority.InvokeTransformable<Models.UpdatedUser, UpdatedUser, UpdatedUserGraphQLTransformer>(
                authority => authority.Update(
                    new UserUpdateRequest
                    {
                        Id = authenticationContext.User.Id,
                        OAuthConnections = newOAuthConnections
                            .Select(oAuthConnection => new Api.Models.OAuthConnection
{
                                ExternalUserId = oAuthConnection.ExternalUserId,
                                Provider = oAuthConnection.Provider,
                            })
                            .ToList(),
                        OidcConnections = newOidcConnections
                            ?.Select(oidcConnection => new Api.Models.OidcConnection
{
                                ExternalUserId = oidcConnection.ExternalUserId,
                                SchemeKey = oidcConnection.SchemeKey,
                            })
                            .ToList(),
                    },
                    cancellationToken));
        }
References Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Host.Authority.Id, and Tgstation.Server.Host.GraphQL.Mutations.UserMutations.UpdatedUser.
SetCurrentUserPassword()
ValueTask< UpdatedUser > Tgstation.Server.Host.GraphQL.Mutations.UserMutations.SetCurrentUserPassword (string newPassword, [Service] IAuthenticationContext authenticationContext, [Service] IGraphQLAuthorityInvoker< IUserAuthority > userAuthority, CancellationToken cancellationToken)
Sets the current user's password.
Parameters
newPassword The new password for the current user.
authenticationContext The IAuthenticationContext to get the Entity.Id of the user.
userAuthority The IGraphQLAuthorityInvoker<TAuthority> for the IUserAuthority.
cancellationToken The CancellationToken for the operation.
Returns
The updated current User.
Definition at line 376 of file UserMutations.cs.
        {
            ArgumentNullException.ThrowIfNull(newPassword);
            ArgumentNullException.ThrowIfNull(userAuthority);
            return userAuthority.InvokeTransformable<Models.UpdatedUser, UpdatedUser, UpdatedUserGraphQLTransformer>(
                authority => authority.Update(
                    new UserUpdateRequest
                    {
                        Id = authenticationContext.User.Id,
                        Password = newPassword,
                    },
                    cancellationToken));
        }
References Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Host.Authority.Id, and Tgstation.Server.Host.GraphQL.Mutations.UserMutations.UpdatedUser.
UpdatedUserGraphQLTransformer()
ValueTask< UpdatedUser > Tgstation.Server.Host.GraphQL.Mutations.UserMutations.UpdatedUserGraphQLTransformer (authority , authority. Updatenew UserUpdateRequest { Id=id, Name=casingOnlyNameChange, Password=newPassword, Enabled=enabled, PermissionSet=newPermissionSet !=null ? new Api.Models.PermissionSet { InstanceManagerRights=newPermissionSet.InstanceManagerRights, AdministrationRights=newPermissionSet.AdministrationRights, } :null, Group=newGroupId.HasValue ? new Api.Models.Internal.UserGroup { Id=newGroupId.Value, } :null, OAuthConnections=newOAuthConnections ?.Select(oAuthConnection=> new Api.Models.OAuthConnection { ExternalUserId=oAuthConnection.ExternalUserId, Provider=oAuthConnection.Provider, }) .ToList(), OidcConnections=newOidcConnections ?.Select(oidcConnection=> new Api.Models.OidcConnection { ExternalUserId=oidcConnection.ExternalUserId, SchemeKey=oidcConnection.SchemeKey, }) .ToList(), }, cancellationToken) private
UpdateUser()
ValueTask< UpdatedUser > Tgstation.Server.Host.GraphQL.Mutations.UserMutations.UpdateUser ([ID(nameof(User))] long id, string? casingOnlyNameChange, string? newPassword, bool? enabled, IEnumerable< OAuthConnection >? newOAuthConnections, IEnumerable< OidcConnection >? newOidcConnections, [Service] IGraphQLAuthorityInvoker< IUserAuthority > userAuthority, CancellationToken cancellationToken)
Updates a Users properties.
Parameters
id The Entity.Id of the User to update.
casingOnlyNameChange Optional casing only change to the NamedEntity.Name of the User. Only applicable to TGS users.
newPassword Optional new password for the User. Only applicable to TGS users.
enabled Optional new User.Enabled status for the User.
newOAuthConnections Optional new OAuthConnections for the User.
newOidcConnections Optional new OidcConnections for the User.
userAuthority The IGraphQLAuthorityInvoker<TAuthority> for the IUserAuthority.
cancellationToken The CancellationToken for the operation.
Returns
The updated User.
Definition at line 449 of file UserMutations.cs.
        {
            ArgumentNullException.ThrowIfNull(userAuthority);
            return UpdateUserCore(
                id,
                casingOnlyNameChange,
                newPassword,
                enabled,
                null,
                null,
                newOAuthConnections,
                newOidcConnections,
                userAuthority,
                cancellationToken);
        }
References Tgstation.Server.Host.GraphQL.Mutations.UserMutations.UpdateUserCore().
UpdateUserCore()
ValueTask< UpdatedUser > Tgstation.Server.Host.GraphQL.Mutations.UserMutations.UpdateUserCore ([ID(nameof(User))] long id, string? casingOnlyNameChange, string? newPassword, bool? enabled, PermissionSetInput? newPermissionSet, long? newGroupId, IEnumerable< OAuthConnection >? newOAuthConnections, IEnumerable< OidcConnection >? newOidcConnections, IGraphQLAuthorityInvoker< IUserAuthority > userAuthority, CancellationToken cancellationToken) private
Updates a user.
Parameters
id The Entity.Id of the User to update.
casingOnlyNameChange Optional casing only change to the NamedEntity.Name of the User. Only applicable to TGS users.
newPassword Optional new password for the User. Only applicable to TGS users.
enabled Optional new User.Enabled status for the User.
newPermissionSet Optional updated new owned PermissionSet for the user. Note that setting this on a User in a UserGroup will remove them from that group.
newGroupId Optional Entity.Id of the UserGroup to move the User to.
newOAuthConnections Optional new OAuthConnections for the User.
newOidcConnections Optional new OidcConnections for the User.
userAuthority The IGraphQLAuthorityInvoker<TAuthority> for the IUserAuthority.
cancellationToken The CancellationToken for the operation.
Returns
The updated User.
Referenced by Tgstation.Server.Host.GraphQL.Mutations.UserMutations.UpdateUser(), Tgstation.Server.Host.GraphQL.Mutations.UserMutations.UpdateUserSetGroup(), and Tgstation.Server.Host.GraphQL.Mutations.UserMutations.UpdateUserSetOwnedPermissionSet().
UpdateUserSetGroup()
ValueTask< UpdatedUser > Tgstation.Server.Host.GraphQL.Mutations.UserMutations.UpdateUserSetGroup ([ID(nameof(User))] long id, string? casingOnlyNameChange, string? newPassword, bool? enabled, [ID(nameof(UserGroup))] long newGroupId, IEnumerable< OAuthConnection >? newOAuthConnections, IEnumerable< OidcConnection >? newOidcConnections, [Service] IGraphQLAuthorityInvoker< IUserAuthority > userAuthority, CancellationToken cancellationToken)
Updates a User, setting new values for its owned PermissionSet.
Parameters
id The Entity.Id of the User to update.
casingOnlyNameChange Optional casing only change to the NamedEntity.Name of the User. Only applicable to TGS users.
newPassword Optional new password for the User. Only applicable to TGS users.
enabled Optional new User.Enabled status for the User.
newGroupId Entity.Id of the UserGroup to move the User to.
newOAuthConnections Optional new OAuthConnections for the User.
newOidcConnections Optional new OidcConnections for the User.
userAuthority The IGraphQLAuthorityInvoker<TAuthority> for the IUserAuthority.
cancellationToken The CancellationToken for the operation.
Returns
The updated User.
Definition at line 526 of file UserMutations.cs.
        {
            ArgumentNullException.ThrowIfNull(userAuthority);
            return UpdateUserCore(
                id,
                casingOnlyNameChange,
                newPassword,
                enabled,
                null,
                newGroupId,
                newOAuthConnections,
                newOidcConnections,
                userAuthority,
                cancellationToken);
        }
References Tgstation.Server.Host.GraphQL.Mutations.UserMutations.UpdateUserCore().
UpdateUserSetOwnedPermissionSet()
ValueTask< UpdatedUser > Tgstation.Server.Host.GraphQL.Mutations.UserMutations.UpdateUserSetOwnedPermissionSet ([ID(nameof(User))] long id, string? casingOnlyNameChange, string? newPassword, bool? enabled, PermissionSetInput newPermissionSet, IEnumerable< OAuthConnection >? newOAuthConnections, IEnumerable< OidcConnection >? newOidcConnections, [Service] IGraphQLAuthorityInvoker< IUserAuthority > userAuthority, CancellationToken cancellationToken)
Updates a User, setting new values for its owned PermissionSet.
Parameters
id The Entity.Id of the User to update.
casingOnlyNameChange Optional casing only change to the NamedEntity.Name of the User. Only applicable to TGS users.
newPassword Optional new password for the User. Only applicable to TGS users.
enabled Optional new User.Enabled status for the User.
newPermissionSet Updated owned PermissionSet for the user. Note that setting this on a User in a UserGroup will remove them from that group.
newOAuthConnections Optional new OAuthConnections for the User.
newOidcConnections Optional new OidcConnections for the User.
userAuthority The IGraphQLAuthorityInvoker<TAuthority> for the IUserAuthority.
cancellationToken The CancellationToken for the operation.
Returns
The updated User.
Definition at line 487 of file UserMutations.cs.
        {
            ArgumentNullException.ThrowIfNull(userAuthority);
            return UpdateUserCore(
                id,
                casingOnlyNameChange,
                newPassword,
                enabled,
                newPermissionSet,
                null,
                newOAuthConnections,
                newOidcConnections,
                userAuthority,
                cancellationToken);
        }
References Tgstation.Server.Host.GraphQL.Mutations.UserMutations.UpdateUserCore().
Member Data Documentation
UpdatedUser
ValueTask< UpdatedUser > Tgstation.Server.Host.GraphQL.Mutations.UserMutations.UpdatedUser private
Definition at line 576 of file UserMutations.cs.
Referenced by Tgstation.Server.Host.GraphQL.Mutations.UserMutations.CreateUserByPasswordAndGroup(), Tgstation.Server.Host.GraphQL.Mutations.UserMutations.CreateUserByPasswordAndPermissionSet(), Tgstation.Server.Host.GraphQL.Mutations.UserMutations.CreateUserByServiceConnectionAndGroup(), Tgstation.Server.Host.GraphQL.Mutations.UserMutations.CreateUserByServiceConnectionAndPermissionSet(), Tgstation.Server.Host.GraphQL.Mutations.UserMutations.CreateUserBySystemIDAndGroup(), Tgstation.Server.Host.GraphQL.Mutations.UserMutations.CreateUserBySystemIDAndPermissionSet(), Tgstation.Server.Host.GraphQL.Mutations.UserMutations.SetCurrentServiceConnections(), and Tgstation.Server.Host.GraphQL.Mutations.UserMutations.SetCurrentUserPassword().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/GraphQL/Mutations/UserMutations.cs