tgstation-server: TGServerService.TGIRCChatProvider Class Reference
TGServerService.TGIRCChatProvider Class Reference
Public Member Functions
TGChatSetupInfo ProviderInfo ()
Gets the info of the provider
TGIRCChatProvider (TGChatSetupInfo info)
string SendMessageDirect (string message, string channel)
Send a message to a channel
string SetProviderInfo (TGChatSetupInfo info)
Sets info for the provider
string Connect ()
Connects the chat provider if it's enabled
string Reconnect ()
Forces a reconnection of the chat provider if it's enabled
void Disconnect ()
Disconnects the chat provider
bool Connected ()
Checks if the chat provider is connected
void SendMessage (string message, ChatMessageType mt)
Broadcast a message to appropriate channels based on the message type
void Dispose ()
Protected Member Functions
virtual void Dispose (bool disposing)
Events
OnChatMessage OnChatMessage
Events inherited from TGServerService.ITGChatProvider
OnChatMessage OnChatMessage
Called with chat message info
Private Member Functions
bool CheckAdmin (IrcMessageData e)
void Irc_OnQueryMessage (object sender, IrcEventArgs e)
void Irc_OnChannelMessage (object sender, IrcEventArgs e)
void JoinChannels ()
void Login ()
void IRCListen ()
Private Attributes
const string PrivateMessageMarker = "---PRIVATE-MSG---"
IrcFeatures irc
object IRCLock = new object()
TGIRCSetupInfo IRCConfig
bool disposedValue = false
Detailed Description
Definition at line 10 of file IRC.cs.
Constructor & Destructor Documentation
TGServerService.TGIRCChatProvider.TGIRCChatProvider (TGChatSetupInfo info)
Definition at line 26 of file IRC.cs.
References TGServerService.TGIRCChatProvider.Irc_OnChannelMessage(), and TGServerService.TGIRCChatProvider.Irc_OnQueryMessage().
         {
             IRCConfig = new TGIRCSetupInfo(info);
             irc = new IrcFeatures()
             {
                 SupportNonRfc = true,
                 CtcpUserInfo = TGServerService.Version,
                 AutoRejoin = true,
                 AutoRejoinOnKick = true,
                 AutoRelogin = true,
                 AutoRetry = true,
                 AutoRetryLimit = 5,
                 AutoRetryDelay = 5,
                 ActiveChannelSyncing = true,
             };
             irc.OnChannelMessage += Irc_OnChannelMessage;
             irc.OnQueryMessage += Irc_OnQueryMessage;
         }
Member Function Documentation
bool TGServerService.TGIRCChatProvider.CheckAdmin (IrcMessageData e) private
Definition at line 87 of file IRC.cs.
References TGServiceInterface.TGChatSetupInfo.AdminList, TGServiceInterface.TGChatSetupInfo.AdminsAreSpecial, and TGServiceInterface.TGIRCSetupInfo.AuthLevel.
Referenced by TGServerService.TGIRCChatProvider.Irc_OnChannelMessage(), and TGServerService.TGIRCChatProvider.Irc_OnQueryMessage().
         {
             if (IRCConfig.AdminsAreSpecial)
             {
                 if (e.Channel == null)
                     return false;
                 var user = (NonRfcChannelUser)irc.GetChannelUser(e.Channel, e.Nick);
                 if (user != null)
                     switch (IRCConfig.AuthLevel)
                     {
                         case IRCMode.Voice:
                             if (user.IsVoice)
                                 return true;
                             goto case IRCMode.Halfop;
                         case IRCMode.Halfop:
                             if (user.IsHalfop)
                                 return true;
                             goto case IRCMode.Op;
                         case IRCMode.Op:
                             if (user.IsOp)
                                 return true;
                             goto case IRCMode.Owner;
                         case IRCMode.Owner:
                             if (user.IsOwner)
                                 return true;
                             break;
                     }
             }
             else
             {
                 var lowerNick = e.Nick.ToLower();
                 foreach (var I in IRCConfig.AdminList)
                     if (lowerNick == I.ToLower())
                         return true;
             }
             return false;
         }
string TGServerService.TGIRCChatProvider.Connect ()
Connects the chat provider if it's enabled
Returns
null on success, error message on failure
Implements TGServerService.ITGChatProvider.
Definition at line 178 of file IRC.cs.
References TGServerService.TGIRCChatProvider.Connected(), TGServiceInterface.TGChatSetupInfo.Enabled, TGServerService.TGIRCChatProvider.IRCListen(), TGServerService.TGIRCChatProvider.JoinChannels(), TGServerService.TGIRCChatProvider.Login(), TGServiceInterface.TGIRCSetupInfo.Nickname, TGServiceInterface.TGIRCSetupInfo.Port, and TGServiceInterface.TGIRCSetupInfo.URL.
Referenced by TGServerService.TGIRCChatProvider.Reconnect().
         {
             if (Connected() || !IRCConfig.Enabled)
                 return null;
             lock (IRCLock)
             {
                 try
                 {
                     try
                     {
                         irc.Connect(IRCConfig.URL, IRCConfig.Port);
                     }
                     catch (Exception e)
                     {
                         return "IRC server unreachable: " + e.ToString();
                     }
                     try
                     {
                         irc.Login(IRCConfig.Nickname, IRCConfig.Nickname);
                     }
                     catch (Exception e)
                     {
                         return "Bot name is already taken: " + e.ToString();
                     }
                     Login();
                     JoinChannels();
                     new Thread(new ThreadStart(IRCListen)) { IsBackground = true }.Start();
                     return null;
                 }
                 catch (Exception e)
                 {
                     return e.ToString();
                 }
             }
         }
bool TGServerService.TGIRCChatProvider.Connected ()
Checks if the chat provider is connected
Returns
true if the provider is connected, false otherwise
Implements TGServerService.ITGChatProvider.
Definition at line 254 of file IRC.cs.
Referenced by TGServerService.TGIRCChatProvider.Connect(), TGServerService.TGIRCChatProvider.IRCListen(), TGServerService.TGIRCChatProvider.SendMessage(), TGServerService.TGIRCChatProvider.SendMessageDirect(), and TGServerService.TGIRCChatProvider.SetProviderInfo().
         {
             lock (IRCLock)
             {
                 return irc != null && irc.IsConnected;
             }
         }
void TGServerService.TGIRCChatProvider.Disconnect ()
Disconnects the chat provider
Implements TGServerService.ITGChatProvider.
Definition at line 235 of file IRC.cs.
Referenced by TGServerService.TGIRCChatProvider.Dispose(), TGServerService.TGIRCChatProvider.Reconnect(), and TGServerService.TGIRCChatProvider.SetProviderInfo().
         {
             try
             {
                 lock (IRCLock)
                 {
                     if (irc.IsConnected)
                     {
                         irc.RfcQuit("Twas meant to be...");
                         irc.Disconnect();
                     }
                 }
             }
             catch (Exception e)
             {
                 TGServerService.WriteError("IRC failed QnD: " + e.ToString(), TGServerService.EventID.ChatDisconnectFail);
             }
         }
virtual void TGServerService.TGIRCChatProvider.Dispose (bool disposing) protected virtual
Definition at line 284 of file IRC.cs.
References TGServerService.TGIRCChatProvider.Disconnect().
         {
             if (!disposedValue)
             {
                 if (disposing)
                 {
                     // TODO: dispose managed state (managed objects).
                     Disconnect();
                     irc = null;
                 }
                 // TODO: free unmanaged resources (unmanaged objects) and override a finalizer below.
                 // TODO: set large fields to null.
                 disposedValue = true;
             }
         }
void TGServerService.TGIRCChatProvider.Dispose ()
Definition at line 309 of file IRC.cs.
         {
             // Do not change this code. Put cleanup code in Dispose(bool disposing) above.
             Dispose(true);
             // TODO: uncomment the following line if the finalizer is overridden above.
             // GC.SuppressFinalize(this);
         }
void TGServerService.TGIRCChatProvider.Irc_OnChannelMessage (object sender, IrcEventArgs e) private
Definition at line 131 of file IRC.cs.
References TGServiceInterface.TGChatSetupInfo.AdminChannels, TGServerService.TGIRCChatProvider.CheckAdmin(), and TGServerService.TGIRCChatProvider.OnChatMessage.
Referenced by TGServerService.TGIRCChatProvider.TGIRCChatProvider().
         {
             var formattedMessage = e.Data.Message.Trim();
             var splits = new List<string>(formattedMessage.Split(' '));
             var test = splits[0];
             if (test.Length > 1 && (test[test.Length - 1] == ':' || test[test.Length - 1] == ','))
                 test = test.Substring(0, test.Length - 1);
             if (test.ToLower() != irc.Nickname.ToLower())
                 return;
             splits.RemoveAt(0);
             formattedMessage = String.Join(" ", splits);
             OnChatMessage(this, e.Data.Nick, e.Data.Channel, formattedMessage, CheckAdmin(e.Data), IRCConfig.AdminChannels.Contains(e.Data.Channel.ToLower()));
         }
void TGServerService.TGIRCChatProvider.Irc_OnQueryMessage (object sender, IrcEventArgs e) private
Definition at line 126 of file IRC.cs.
References TGServerService.TGIRCChatProvider.CheckAdmin(), and TGServerService.TGIRCChatProvider.OnChatMessage.
Referenced by TGServerService.TGIRCChatProvider.TGIRCChatProvider().
         {
             OnChatMessage(this, e.Data.Nick, e.Data.Nick + PrivateMessageMarker, e.Data.Message, CheckAdmin(e.Data), true);
         }
void TGServerService.TGIRCChatProvider.IRCListen () private
Definition at line 217 of file IRC.cs.
References TGServerService.TGIRCChatProvider.Connected().
Referenced by TGServerService.TGIRCChatProvider.Connect().
         {
             while (irc != null && Connected())
                 try
                 {
                     irc.Listen();
                 }
                 catch { }
         }
void TGServerService.TGIRCChatProvider.JoinChannels () private
Definition at line 148 of file IRC.cs.
References TGServiceInterface.TGChatSetupInfo.AdminChannels, TGServiceInterface.TGChatSetupInfo.DevChannels, TGServiceInterface.TGChatSetupInfo.GameChannels, and TGServiceInterface.TGChatSetupInfo.WatchdogChannels.
Referenced by TGServerService.TGIRCChatProvider.Connect(), and TGServerService.TGIRCChatProvider.SetProviderInfo().
         {
             var hs = new HashSet<string>(); //for unique inserts
             foreach (var I in IRCConfig.AdminChannels)
                 hs.Add(I);
             foreach (var I in IRCConfig.DevChannels)
                 hs.Add(I);
             foreach (var I in IRCConfig.GameChannels)
                 hs.Add(I);
             foreach (var I in IRCConfig.WatchdogChannels)
                 hs.Add(I);
             var ToPart = new List<string>();
             foreach (var I in irc.JoinedChannels)
                 if (!hs.Remove(I))
                     ToPart.Add(I);
             foreach (var I in ToPart)
                 irc.RfcPart(I);
             foreach (var I in hs)
                 irc.RfcJoin(I);
         }
void TGServerService.TGIRCChatProvider.Login () private
Definition at line 169 of file IRC.cs.
References TGServiceInterface.TGIRCSetupInfo.AuthMessage, and TGServiceInterface.TGIRCSetupInfo.AuthTarget.
Referenced by TGServerService.TGIRCChatProvider.Connect(), and TGServerService.TGIRCChatProvider.SetProviderInfo().
         {
             lock (IRCLock)
             {
                 if (IRCConfig.AuthTarget != null)
                     irc.SendMessage(SendType.Message, IRCConfig.AuthTarget, IRCConfig.AuthMessage);
             }
         }
TGChatSetupInfo TGServerService.TGIRCChatProvider.ProviderInfo ()
Gets the info of the provider
Returns
The info for the chat provider
Implements TGServerService.ITGChatProvider.
Definition at line 21 of file IRC.cs.
References TGServerService.TGIRCChatProvider.IRCConfig.
         {
             return IRCConfig;
         }
string TGServerService.TGIRCChatProvider.Reconnect ()
Forces a reconnection of the chat provider if it's enabled
Returns
null on success, error message on failure
Implements TGServerService.ITGChatProvider.
Definition at line 228 of file IRC.cs.
References TGServerService.TGIRCChatProvider.Connect(), and TGServerService.TGIRCChatProvider.Disconnect().
Referenced by TGServerService.TGIRCChatProvider.SetProviderInfo().
         {
             Disconnect();
             return Connect();
         }
void TGServerService.TGIRCChatProvider.SendMessage (string msg, ChatMessageType mt)
Broadcast a message to appropriate channels based on the message type
Parameters
msg The message to send
mt The message type
Implements TGServerService.ITGChatProvider.
Definition at line 262 of file IRC.cs.
References TGServiceInterface.TGChatSetupInfo.AdminChannels, TGServerService.TGIRCChatProvider.Connected(), TGServiceInterface.TGChatSetupInfo.DevChannels, TGServiceInterface.TGChatSetupInfo.GameChannels, and TGServiceInterface.TGChatSetupInfo.WatchdogChannels.
         {
             if (!Connected())
                 return;
             lock (IRCLock)
             {
                 foreach (var cid in irc.JoinedChannels)
                 {
                     bool SendToThisChannel = (mt.HasFlag(ChatMessageType.AdminInfo) && IRCConfig.AdminChannels.Contains(cid))
                         || (mt.HasFlag(ChatMessageType.DeveloperInfo) && IRCConfig.DevChannels.Contains(cid))
                         || (mt.HasFlag(ChatMessageType.GameInfo) && IRCConfig.GameChannels.Contains(cid))
                         || (mt.HasFlag(ChatMessageType.WatchdogInfo) && IRCConfig.WatchdogChannels.Contains(cid));
                     if (SendToThisChannel)
                         irc.SendMessage(SendType.Message, cid, message);
                 }
             }
         }
string TGServerService.TGIRCChatProvider.SendMessageDirect (string message, string channel)
Send a message to a channel
Parameters
message The message to send
channel The channel to send to
Returns
null on success, error message on failure
Implements TGServerService.ITGChatProvider.
Definition at line 46 of file IRC.cs.
References TGServerService.TGIRCChatProvider.Connected().
         {
             try
             {
                 if (!Connected())
                     return "Disconnected.";
                 lock (IRCLock)
                 {
                     if (channel.Contains(PrivateMessageMarker))
                         channel = channel.Replace(PrivateMessageMarker, "");
                     irc.SendMessage(SendType.Message, channel, message);
                 }
                 TGServerService.WriteInfo(String.Format("IRC Send ({0}): {1}", channel, message), TGServerService.EventID.ChatSend);
                 return null;
             }
             catch (Exception e)
             {
                 return e.ToString();
             }
         }
string TGServerService.TGIRCChatProvider.SetProviderInfo (TGChatSetupInfo info)
Sets info for the provider
Parameters
info The info to set
Returns
null on success, error message on failure
Implements TGServerService.ITGChatProvider.
Definition at line 67 of file IRC.cs.
References TGServerService.TGIRCChatProvider.Connected(), TGServerService.TGIRCChatProvider.Disconnect(), TGServiceInterface.TGChatSetupInfo.Enabled, TGServerService.TGIRCChatProvider.JoinChannels(), TGServerService.TGIRCChatProvider.Login(), TGServiceInterface.TGIRCSetupInfo.Nickname, TGServiceInterface.TGIRCSetupInfo.Port, TGServerService.TGIRCChatProvider.Reconnect(), and TGServiceInterface.TGIRCSetupInfo.URL.
         {
             var convertedInfo = (TGIRCSetupInfo)info;
             var serverChange = convertedInfo.URL != IRCConfig.URL || convertedInfo.Port != IRCConfig.Port;
             IRCConfig = convertedInfo;
             if (!IRCConfig.Enabled)
             {
                 Disconnect();
                 return null;
             }
             else if (serverChange || !Connected())
                 return Reconnect();
             if (IRCConfig.Nickname != irc.Nickname)
                 irc.RfcNick(convertedInfo.Nickname);
             Login();
             JoinChannels();
             return null;
         }
Member Data Documentation
bool TGServerService.TGIRCChatProvider.disposedValue = false private
Definition at line 282 of file IRC.cs.
IrcFeatures TGServerService.TGIRCChatProvider.irc private
Definition at line 13 of file IRC.cs.
TGIRCSetupInfo TGServerService.TGIRCChatProvider.IRCConfig private
Definition at line 17 of file IRC.cs.
Referenced by TGServerService.TGIRCChatProvider.ProviderInfo().
object TGServerService.TGIRCChatProvider.IRCLock = new object() private
Definition at line 15 of file IRC.cs.
const string TGServerService.TGIRCChatProvider.PrivateMessageMarker = "---PRIVATE-MSG---" private
Definition at line 12 of file IRC.cs.
Event Documentation
OnChatMessage TGServerService.TGIRCChatProvider.OnChatMessage
Definition at line 19 of file IRC.cs.
Referenced by TGServerService.TGIRCChatProvider.Irc_OnChannelMessage(), and TGServerService.TGIRCChatProvider.Irc_OnQueryMessage().
The documentation for this class was generated from the following file:
TGServerService/IRC.cs