tgstation-server: Tgstation.Server.Host.Swarm.SwarmService Class Reference
Tgstation.Server.Host.Swarm.SwarmService Class Reference sealed
Helps keep servers connected to the same database in sync by coordinating updates.
Public Member Functions
SwarmService (IDatabaseContextFactory databaseContextFactory, IDatabaseSeeder databaseSeeder, IAssemblyInformationProvider assemblyInformationProvider, IAbstractHttpClientFactory httpClientFactory, IAsyncDelayer asyncDelayer, IServerUpdater serverUpdater, IFileTransferTicketProvider transferService, ITokenFactory tokenFactory, IOptions< SwarmConfiguration > swarmConfigurationOptions, ILogger< SwarmService > logger)
Initializes a new instance of the SwarmService class.
void Dispose ()
async ValueTask AbortUpdate ()
Attempt to abort an uncommitted update.
Returns
A ValueTask representing the running operation.
This method does not accept a global::System.Threading.CancellationToken because aborting an update should never be cancelled.
async ValueTask< SwarmCommitResult > CommitUpdate (CancellationToken cancellationToken)
Signal to the swarm that an update is ready to be applied.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the SwarmCommitResult.
List< SwarmServerInformation >? GetSwarmServers ()
Gets the list of SwarmServerInformations in the swarm, including the current one.
Returns
A List<T> of SwarmServerInformations in the swarm. If the server is not part of a swarm, null will be returned.
ValueTask< SwarmPrepareResult > PrepareUpdate (ISeekableFileStreamProvider fileStreamProvider, Version version, CancellationToken cancellationToken)
Signal to the swarm that an update is requested.
Parameters
fileStreamProvider The ISeekableFileStreamProvider to relay to other nodes.
version The Version to update to.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in true if the update should proceed, false otherwise.
async ValueTask< bool > PrepareUpdateFromController (SwarmUpdateRequest updateRequest, CancellationToken cancellationToken)
Notify the node of an update request from the controller.
Parameters
updateRequest The SwarmUpdateRequest.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in true if the node is able to update, false otherwise.
async ValueTask< SwarmRegistrationResult > Initialize (CancellationToken cancellationToken)
Attempt to register with the swarm controller if not one, sets up the database otherwise.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the SwarmRegistrationResult.
async ValueTask Shutdown (CancellationToken cancellationToken)
Deregister with the swarm controller or put clients into querying state.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
void UpdateSwarmServersList (IEnumerable< SwarmServerInformation > swarmServers)
Pass in an updated list of swarmServers to the node.
Parameters
swarmServers An IEnumerable<T> of the updated SwarmServerInformations.
bool ValidateRegistration (Guid registrationId)
Validate a given registrationId .
Parameters
registrationId The registration Guid to validate.
Returns
true if the registration is valid, false otherwise.
async ValueTask< SwarmRegistrationResponse?> RegisterNode (SwarmServer node, Guid registrationId, CancellationToken cancellationToken)
Attempt to register a given node with the controller.
Parameters
node The SwarmServer that is registering.
registrationId The registration Guid.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a SwarmRegistrationResponse if the registration was successful, null otherwise.
async ValueTask< bool > RemoteCommitReceived (Guid registrationId, CancellationToken cancellationToken)
Notify the controller that the node with the given registrationId is ready to commit or notify the node of the controller telling it to commit.
Parameters
registrationId The registration Guid.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
async ValueTask UnregisterNode (Guid registrationId, CancellationToken cancellationToken)
Attempt to unregister a node with a given registrationId with the controller.
Parameters
registrationId The registration Guid.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Properties
bool ExpectedNumberOfNodesConnected [get]
Gets a value indicating if the expected amount of nodes are connected to the swarm.
bool SwarmMode [get]
If the swarm system is enabled.
Properties inherited from Tgstation.Server.Host.Swarm.ISwarmService
Private Member Functions
ValueTask RemoteAbortUpdate ()
Sends out remote abort update requests.
RequestFileStreamProvider CreateUpdateStreamProvider (SwarmServerInformation sourceNode, FileTicketResponse ticket)
Create the RequestFileStreamProvider for an update package retrieval from a given sourceNode .
async ValueTask< SwarmPrepareResult > PrepareUpdateImpl (ISeekableFileStreamProvider? initiatorProvider, SwarmUpdateRequest updateRequest, CancellationToken cancellationToken)
Implementation of PrepareUpdate(ISeekableFileStreamProvider, Version, CancellationToken),.
async ValueTask< SwarmPrepareResult > ControllerDistributedPrepareUpdate (ISeekableFileStreamProvider? initiatorProvider, SwarmUpdateRequest updateRequest, SwarmUpdateOperation currentUpdateOperation, CancellationToken cancellationToken)
Send a given updateRequest out to nodes from the swarm controller.
async ValueTask< Dictionary< string, FileTicketResponse > > CreateDownloadTickets (ISeekableFileStreamProvider initiatorProvider, IReadOnlyCollection< SwarmServerInformation > involvedServers, CancellationToken cancellationToken)
Create a FileTicketResponse for downloading the content of a given initiatorProvider for the rest of the swarm nodes.
async ValueTask HealthCheckNodes (CancellationToken cancellationToken)
Ping each node to see that they are still running.
void MarkServersDirty ()
Set serversDirty and complete the current forceHealthCheckTcs.
bool TriggerHealthCheck ()
Complete the current forceHealthCheckTcs.
async ValueTask HealthCheckController (CancellationToken cancellationToken)
Ping the swarm controller to see that it is still running. If need be, reregister.
async ValueTask< SwarmRegistrationResult > RegisterWithController (CancellationToken cancellationToken)
Attempt to register the node with the controller.
async ValueTask SendUpdatedServerListToNodes (CancellationToken cancellationToken)
Sends the controllers list of nodes to all nodes.
HttpRequestMessage PrepareSwarmRequest (SwarmServerInformation? swarmServer, HttpMethod httpMethod, string route, object? body, Guid? registrationIdOverride=null)
Prepares a HttpRequestMessage for swarm communication.
async Task HealthCheckLoop (CancellationToken cancellationToken)
Timed loop for calling HealthCheckNodes(CancellationToken).
string? NodeIdentifierFromRegistration (Guid registrationId)
Gets the SwarmServer.Identifier from a given registrationId .
Private Attributes
readonly IDatabaseContextFactory databaseContextFactory
The IDatabaseContextFactory for the SwarmService.
readonly IDatabaseSeeder databaseSeeder
The IDatabaseSeeder for the SwarmService.
readonly IAssemblyInformationProvider assemblyInformationProvider
The IAssemblyInformationProvider for the SwarmService.
readonly IAbstractHttpClientFactory httpClientFactory
The IAbstractHttpClientFactory for the SwarmService.
readonly IAsyncDelayer asyncDelayer
The IAsyncDelayer for the SwarmService.
readonly IServerUpdater serverUpdater
The IServerUpdater for the SwarmService.
readonly IFileTransferTicketProvider transferService
The IFileTransferTicketProvider for the SwarmService.
readonly ITokenFactory tokenFactory
The ITokenFactory for the SwarmService.
readonly ILogger< SwarmService > logger
The ILogger for the SwarmService.
readonly SwarmConfiguration swarmConfiguration
The SwarmConfiguration for the SwarmService.
readonly? CancellationTokenSource serverHealthCheckCancellationTokenSource
The CancellationTokenSource for serverHealthCheckTask.
readonly? List< SwarmServerInformation > swarmServers
List<T> of connected SwarmServerInformations.
readonly? Dictionary< string,(Guid RegistrationId, DateTimeOffset RegisteredAt)> registrationIdsAndTimes
Dictionary<TKey, TValue> of SwarmServer.Identifiers to registration Guids and when they were created.
readonly bool swarmController
If the current server is the swarm controller.
volatile? SwarmUpdateOperation updateOperation
A SwarmUpdateOperation that is currently in progress.
volatile? TaskCompletionSource forceHealthCheckTcs
A TaskCompletionSource that is used to force a health check.
Task? serverHealthCheckTask
The Task for the HealthCheckLoop(CancellationToken).
Guid? controllerRegistration
The registration Guid provided by the swarm controller.
DateTimeOffset? lastControllerHealthCheck
The last DateTimeOffset when the controller checked on this node.
bool serversDirty
If the swarmServers list has been updated and needs to be resent to clients.
Detailed Description
Helps keep servers connected to the same database in sync by coordinating updates.
Definition at line 39 of file SwarmService.cs.
Constructor & Destructor Documentation
SwarmService()
Tgstation.Server.Host.Swarm.SwarmService.SwarmService (IDatabaseContextFactory databaseContextFactory, IDatabaseSeeder databaseSeeder, IAssemblyInformationProvider assemblyInformationProvider, IAbstractHttpClientFactory httpClientFactory, IAsyncDelayer asyncDelayer, IServerUpdater serverUpdater, IFileTransferTicketProvider transferService, ITokenFactory tokenFactory, IOptions< SwarmConfiguration > swarmConfigurationOptions, ILogger< SwarmService > logger)
Initializes a new instance of the SwarmService class.
Parameters
databaseContextFactory The value of databaseContextFactory.
databaseSeeder The value of databaseSeeder.
assemblyInformationProvider The value of assemblyInformationProvider.
httpClientFactory The value of httpClientFactory.
serverUpdater The value of serverUpdater.
asyncDelayer The value of asyncDelayer.
transferService The value of transferService.
tokenFactory The value of tokenFactory.
swarmConfigurationOptions The IOptions<TOptions> containing the value of swarmConfiguration.
logger The value of logger.
Definition at line 174 of file SwarmService.cs.
        {
            this.databaseContextFactory = databaseContextFactory ?? throw new ArgumentNullException(nameof(databaseContextFactory));
            this.databaseSeeder = databaseSeeder ?? throw new ArgumentNullException(nameof(databaseSeeder));
            this.assemblyInformationProvider = assemblyInformationProvider ?? throw new ArgumentNullException(nameof(assemblyInformationProvider));
            this.httpClientFactory = httpClientFactory ?? throw new ArgumentNullException(nameof(httpClientFactory));
            this.asyncDelayer = asyncDelayer ?? throw new ArgumentNullException(nameof(asyncDelayer));
            this.serverUpdater = serverUpdater ?? throw new ArgumentNullException(nameof(serverUpdater));
            this.transferService = transferService ?? throw new ArgumentNullException(nameof(transferService));
            this.tokenFactory = tokenFactory ?? throw new ArgumentNullException(nameof(tokenFactory));
            swarmConfiguration = swarmConfigurationOptions?.Value ?? throw new ArgumentNullException(nameof(swarmConfigurationOptions));
            this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
            if (SwarmMode)
            {
                if (swarmConfiguration.Address == null)
                    throw new InvalidOperationException("Swarm configuration missing Address!");
                if (String.IsNullOrWhiteSpace(swarmConfiguration.Identifier))
                    throw new InvalidOperationException("Swarm configuration missing Identifier!");
                swarmController = swarmConfiguration.ControllerAddress == null;
                if (swarmController)
                    registrationIdsAndTimes = new();
                serverHealthCheckCancellationTokenSource = new CancellationTokenSource();
                forceHealthCheckTcs = new TaskCompletionSource();
                swarmServers = new List<SwarmServerInformation>
                {
                    new()
                    {
                        Address = swarmConfiguration.Address,
                        PublicAddress = swarmConfiguration.PublicAddress,
                        Controller = swarmController,
                        Identifier = swarmConfiguration.Identifier,
                    },
                };
            }
            else
                swarmController = true;
        }
References Tgstation.Server.Host.Configuration.SwarmConfiguration.Address, Tgstation.Server.Host.Swarm.SwarmService.assemblyInformationProvider, Tgstation.Server.Host.Swarm.SwarmService.asyncDelayer, Tgstation.Server.Host.Swarm.SwarmService.databaseContextFactory, Tgstation.Server.Host.Swarm.SwarmService.databaseSeeder, Tgstation.Server.Host.Swarm.SwarmService.forceHealthCheckTcs, Tgstation.Server.Host.Swarm.SwarmService.httpClientFactory, Tgstation.Server.Api.Models.Internal.SwarmServer.Identifier, Tgstation.Server.Host.Swarm.SwarmService.logger, Tgstation.Server.Host.Configuration.SwarmConfiguration.PublicAddress, Tgstation.Server.Host.Swarm.SwarmService.registrationIdsAndTimes, Tgstation.Server.Host.Swarm.SwarmService.serverHealthCheckCancellationTokenSource, Tgstation.Server.Host.Swarm.SwarmService.serverUpdater, Tgstation.Server.Host.Swarm.SwarmService.swarmConfiguration, Tgstation.Server.Host.Swarm.SwarmService.swarmController, Tgstation.Server.Host.Swarm.SwarmService.SwarmMode, Tgstation.Server.Host.Swarm.SwarmService.swarmServers, Tgstation.Server.Host.Swarm.SwarmService.tokenFactory, and Tgstation.Server.Host.Swarm.SwarmService.transferService.
Member Function Documentation
AbortUpdate()
async ValueTask Tgstation.Server.Host.Swarm.SwarmService.AbortUpdate ()
Attempt to abort an uncommitted update.
Returns
A ValueTask representing the running operation.
This method does not accept a global::System.Threading.CancellationToken because aborting an update should never be cancelled.
Implements Tgstation.Server.Host.Swarm.ISwarmUpdateAborter.
Definition at line 231 of file SwarmService.cs.
        {
            if (!SwarmMode)
                return;
            var localUpdateOperation = Interlocked.Exchange(ref updateOperation, null);
            var abortResult = localUpdateOperation?.Abort();
            switch (abortResult)
            {
                case SwarmUpdateAbortResult.Aborted:
                    break;
                case SwarmUpdateAbortResult.AlreadyAborted:
                    logger.LogDebug("Another context already aborted this update.");
                    return;
                case SwarmUpdateAbortResult.CantAbortCommitted:
                    logger.LogDebug("Not aborting update because we have committed!");
                    return;
                case null:
                    logger.LogTrace("Attempted update abort but no operation was found!");
                    return;
                default:
                    throw new InvalidOperationException($"Invalid return value for SwarmUpdateOperation.Abort(): {abortResult}");
            }
            await RemoteAbortUpdate();
        }
References Tgstation.Server.Host.Swarm.SwarmService.logger, Tgstation.Server.Host.Swarm.SwarmService.RemoteAbortUpdate(), Tgstation.Server.Host.Swarm.SwarmService.SwarmMode, and Tgstation.Server.Host.Swarm.SwarmService.updateOperation.
Referenced by Tgstation.Server.Host.Swarm.SwarmService.CommitUpdate(), Tgstation.Server.Host.Swarm.SwarmService.PrepareUpdateImpl(), Tgstation.Server.Host.Swarm.SwarmService.RegisterNode(), Tgstation.Server.Host.Swarm.SwarmService.RemoteCommitReceived(), and Tgstation.Server.Host.Swarm.SwarmService.UnregisterNode().
CommitUpdate()
async ValueTask< SwarmCommitResult > Tgstation.Server.Host.Swarm.SwarmService.CommitUpdate (CancellationToken cancellationToken)
Signal to the swarm that an update is ready to be applied.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the SwarmCommitResult.
Implements Tgstation.Server.Host.Swarm.ISwarmService.
Definition at line 259 of file SwarmService.cs.
        {
            if (!SwarmMode)
                return SwarmCommitResult.ContinueUpdateNonCommitted;
            // wait for the update commit TCS
            var localUpdateOperation = updateOperation;
            if (localUpdateOperation == null)
            {
                logger.LogDebug("Update commit failed, no pending operation!");
                await AbortUpdate(); // unnecessary, but can never be too safe
                return SwarmCommitResult.AbortUpdate;
            }
            logger.LogInformation("Waiting to commit update...");
            using var httpClient = httpClientFactory.CreateClient();
            if (!swarmController)
            {
                // let the controller know we're ready
                logger.LogTrace("Sending ready-commit to swarm controller...");
                using var commitReadyRequest = PrepareSwarmRequest(
                    null,
                    HttpMethod.Post,
                    SwarmConstants.UpdateRoute,
                    null);
                try
                {
                    using var commitReadyResponse = await httpClient.SendAsync(commitReadyRequest, HttpCompletionOption.ResponseContentRead, cancellationToken);
                    commitReadyResponse.EnsureSuccessStatusCode();
                }
                catch (Exception ex)
                {
                    logger.LogWarning(ex, "Unable to send ready-commit to swarm controller!");
                    await AbortUpdate();
                    return SwarmCommitResult.AbortUpdate;
                }
            }
            var timeoutTask = swarmController
                ? asyncDelayer.Delay(
                    TimeSpan.FromMinutes(SwarmConstants.UpdateCommitTimeoutMinutes),
                    cancellationToken).AsTask()
                : Extensions.TaskExtensions.InfiniteTask.WaitAsync(cancellationToken);
            var commitTask = Task.WhenAny(localUpdateOperation.CommitGate, timeoutTask);
            await commitTask;
            var commitGoAhead = localUpdateOperation.CommitGate.IsCompleted
                && localUpdateOperation.CommitGate.Result
                && localUpdateOperation == updateOperation;
            if (!commitGoAhead)
            {
                logger.LogDebug(
                    "Update commit failed!{maybeTimeout}",
                    timeoutTask.IsCompleted
                        ? " Timed out!"
                        : String.Empty);
                await AbortUpdate();
                return SwarmCommitResult.AbortUpdate;
            }
            logger.LogTrace("Update commit task complete");
            // on nodes, it means we can go straight ahead
            if (!swarmController)
                return SwarmCommitResult.MustCommitUpdate;
            // on the controller, we first need to signal for nodes to go ahead
            // if anything fails at this point, there's nothing we can do
            logger.LogDebug("Sending remote commit message to nodes...");
            async ValueTask SendRemoteCommitUpdate(SwarmServerInformation swarmServer)
            {
                using var request = PrepareSwarmRequest(
                    swarmServer,
                    HttpMethod.Post,
                    SwarmConstants.UpdateRoute,
                    null);
                try
                {
                    // I know using the cancellationToken after this point doesn't seem very sane
                    // It's the token for Ctrl+C on server's console though, so we must respect it
                    using var response = await httpClient.SendAsync(request, HttpCompletionOption.ResponseContentRead, cancellationToken);
                    response.EnsureSuccessStatusCode();
                }
                catch (Exception ex)
                {
                    logger.LogCritical(ex, "Failed to send update commit request to node {nodeId}!", swarmServer.Identifier);
                }
            }
            ValueTask task;
            lock (swarmServers)
                task = ValueTaskExtensions.WhenAll(
                    swarmServers
                        .Where(x => !x.Controller)
                        .Select(SendRemoteCommitUpdate)
                        .ToList());
            await task;
            return SwarmCommitResult.MustCommitUpdate;
        }
References Tgstation.Server.Host.Swarm.SwarmService.AbortUpdate(), Tgstation.Server.Host.Swarm.SwarmService.asyncDelayer, Tgstation.Server.Common.Http.IAbstractHttpClientFactory.CreateClient(), Tgstation.Server.Host.Utils.IAsyncDelayer.Delay(), Tgstation.Server.Host.Swarm.SwarmService.httpClientFactory, Tgstation.Server.Api.Models.Internal.SwarmServer.Identifier, Tgstation.Server.Host.Swarm.SwarmService.logger, Tgstation.Server.Host.Swarm.SwarmService.PrepareSwarmRequest(), Tgstation.Server.Host.Swarm.SwarmService.swarmController, Tgstation.Server.Host.Swarm.SwarmService.SwarmMode, Tgstation.Server.Host.Swarm.SwarmService.swarmServers, Tgstation.Server.Host.Swarm.SwarmConstants.UpdateCommitTimeoutMinutes, Tgstation.Server.Host.Swarm.SwarmService.updateOperation, Tgstation.Server.Host.Swarm.SwarmConstants.UpdateRoute, and Tgstation.Server.Common.Extensions.ValueTaskExtensions.WhenAll().
ControllerDistributedPrepareUpdate()
async ValueTask< SwarmPrepareResult > Tgstation.Server.Host.Swarm.SwarmService.ControllerDistributedPrepareUpdate (ISeekableFileStreamProvider? initiatorProvider, SwarmUpdateRequest updateRequest, SwarmUpdateOperation currentUpdateOperation, CancellationToken cancellationToken) private
Send a given updateRequest out to nodes from the swarm controller.
Parameters
initiatorProvider The ISeekableFileStreamProvider containing the update package if this is the initiating server, null otherwise.
updateRequest The SwarmUpdateRequest. Must always have SwarmUpdateRequest.UpdateVersion populated. If initiatorProvider is null, it must be fully populated.
currentUpdateOperation The current SwarmUpdateOperation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the SwarmPrepareResult.
Definition at line 964 of file SwarmService.cs.
        {
            bool abortUpdate = false;
            try
            {
                logger.LogInformation("Sending remote prepare to nodes...");
                if (currentUpdateOperation.InvolvedServers.Count - 1 < swarmConfiguration.UpdateRequiredNodeCount)
                {
                    logger.LogWarning(
                        "Aborting update, controller expects to be in sync with {requiredNodeCount} nodes but currently only has {currentNodeCount}!",
                        swarmConfiguration.UpdateRequiredNodeCount,
                        currentUpdateOperation.InvolvedServers.Count - 1);
                    abortUpdate = true;
                    return SwarmPrepareResult.Failure;
                }
                var weAreInitiator = initiatorProvider != null;
                if (currentUpdateOperation.InvolvedServers.Count == 1)
                {
                    logger.LogDebug("Controller has no nodes, setting commit-ready.");
                    if (updateOperation?.Commit() == true)
                        return SwarmPrepareResult.SuccessProviderNotRequired;
                    logger.LogDebug("Update appears to have been aborted");
                    return SwarmPrepareResult.Failure;
                }
                // The initiator node obviously doesn't create a ticket for itself
                else if (!weAreInitiator && updateRequest.DownloadTickets!.Count != currentUpdateOperation.InvolvedServers.Count - 1)
                {
                    logger.LogWarning(
                        "Aborting update, {receivedTickets} download tickets were provided but there are {nodesToUpdate} nodes in the swarm that require the package!",
                        updateRequest.DownloadTickets.Count,
                        currentUpdateOperation.InvolvedServers.Count);
                    abortUpdate = true;
                    return SwarmPrepareResult.Failure;
                }
                var downloadTicketDictionary = weAreInitiator
                    ? await CreateDownloadTickets(initiatorProvider!, currentUpdateOperation.InvolvedServers, cancellationToken)
                    : updateRequest.DownloadTickets!;
                var sourceNode = weAreInitiator
                    ? swarmConfiguration.Identifier
                    : updateRequest.SourceNode;
                using var httpClient = httpClientFactory.CreateClient();
                using var transferSemaphore = new SemaphoreSlim(1);
                bool anyFailed = false;
                var updateRequests = currentUpdateOperation
                    .InvolvedServers
                    .Where(node => !node.Controller)
                    .Select(node =>
                    {
                        // only send the necessary ticket to each node from the controller
                        Dictionary<string, FileTicketResponse>? localTicketDictionary;
                        var nodeId = node.Identifier!;
                        if (nodeId == sourceNode)
                            localTicketDictionary = null;
                        else if (!downloadTicketDictionary.TryGetValue(nodeId, out var ticket))
{
                            logger.LogError("Missing download ticket for node {missingNodeId}!", nodeId);
                            anyFailed = true;
                            return null;
                        }
                        else
                            localTicketDictionary = new Dictionary<string, FileTicketResponse>
{
                                { nodeId, ticket },
                            };
                        var request = new SwarmUpdateRequest
{
                            UpdateVersion = updateRequest.UpdateVersion,
                            SourceNode = sourceNode,
                            DownloadTickets = localTicketDictionary,
                        };
                        return Tuple.Create(node, request);
                    })
                    .ToList();
                if (anyFailed)
                    return SwarmPrepareResult.Failure;
                var tasks = updateRequests
                    .Select(async tuple =>
                    {
                        var node = tuple!.Item1;
                        var body = tuple.Item2;
                        using var request = PrepareSwarmRequest(
                            node,
                            HttpMethod.Put,
                            SwarmConstants.UpdateRoute,
                            body);
                        using var response = await httpClient.SendAsync(request, HttpCompletionOption.ResponseContentRead, cancellationToken);
                        return response.IsSuccessStatusCode;
                    })
                    .ToList();
                await Task.WhenAll(tasks);
                // if all succeeds...
                if (tasks.All(x => x.Result))
                {
                    logger.LogInformation("Distributed prepare for update to version {version} complete.", updateRequest.UpdateVersion);
                    return weAreInitiator
                        ? SwarmPrepareResult.SuccessHoldProviderUntilCommit
                        : SwarmPrepareResult.SuccessProviderNotRequired;
                }
                abortUpdate = true;
                logger.LogDebug("Distrubuted prepare failed!");
            }
            catch (Exception ex)
            {
                logger.LogWarning(ex, "Error remotely preparing updates!");
            }
            finally
            {
                if (abortUpdate)
                    await AbortUpdate();
            }
            return SwarmPrepareResult.Failure;
        }
References Tgstation.Server.Common.Http.IAbstractHttpClientFactory.CreateClient(), Tgstation.Server.Host.Swarm.SwarmService.CreateDownloadTickets(), Tgstation.Server.Host.Swarm.SwarmUpdateRequest.DownloadTickets, Tgstation.Server.Host.Swarm.SwarmService.httpClientFactory, Tgstation.Server.Host.Swarm.SwarmUpdateOperation.InvolvedServers, Tgstation.Server.Host.Swarm.SwarmService.logger, Tgstation.Server.Host.Swarm.SwarmService.PrepareSwarmRequest(), Tgstation.Server.Host.Swarm.SwarmUpdateRequest.SourceNode, Tgstation.Server.Host.Swarm.SwarmService.swarmConfiguration, Tgstation.Server.Host.Swarm.SwarmService.updateOperation, Tgstation.Server.Host.Configuration.SwarmConfiguration.UpdateRequiredNodeCount, Tgstation.Server.Host.Swarm.SwarmConstants.UpdateRoute, and Tgstation.Server.Host.Swarm.SwarmUpdateRequest.UpdateVersion.
Referenced by Tgstation.Server.Host.Swarm.SwarmService.PrepareUpdateImpl().
CreateDownloadTickets()
async ValueTask< Dictionary< string, FileTicketResponse > > Tgstation.Server.Host.Swarm.SwarmService.CreateDownloadTickets (ISeekableFileStreamProvider initiatorProvider, IReadOnlyCollection< SwarmServerInformation > involvedServers, CancellationToken cancellationToken) private
Create a FileTicketResponse for downloading the content of a given initiatorProvider for the rest of the swarm nodes.
Parameters
initiatorProvider The ISeekableFileStreamProvider containing the server update package.
involvedServers An IEnumerable<T> of the involved SwarmServerInformation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a new Dictionary<TKey, TValue> of unique FileTicketResponses keyed by their SwarmServer.Identifier.
Definition at line 1106 of file SwarmService.cs.
        {
            // we need to ensure this thing is loaded before we start providing downloads or it'll create unnecessary delays
            var streamRetrievalTask = initiatorProvider.GetResult(cancellationToken);
            var downloadProvider = new FileDownloadProvider(
                () => initiatorProvider.Disposed
                    ? Api.Models.ErrorCode.ResourceNotPresent
                    : null,
                async downloadToken => await initiatorProvider.GetOwnedResult(downloadToken), // let it throw if disposed, shouldn't happen regardless
                "<Swarm Update Package Provider>",
                false);
            var serversRequiringTickets = involvedServers
                .Where(node => node.Identifier != swarmConfiguration.Identifier)
                .ToList();
            logger.LogTrace("Creating {n} download tickets for other nodes...", serversRequiringTickets.Count);
            var downloadTickets = new Dictionary<string, FileTicketResponse>(serversRequiringTickets.Count);
            foreach (var node in serversRequiringTickets)
                downloadTickets.Add(
                    node.Identifier!,
                    transferService.CreateDownload(downloadProvider));
            await streamRetrievalTask;
            return downloadTickets;
        }
References Tgstation.Server.Host.IO.ISeekableFileStreamProvider.Disposed, Tgstation.Server.Host.IO.ISeekableFileStreamProvider.GetOwnedResult(), and Tgstation.Server.Host.IO.IFileStreamProvider.GetResult().
Referenced by Tgstation.Server.Host.Swarm.SwarmService.ControllerDistributedPrepareUpdate(), and Tgstation.Server.Host.Swarm.SwarmService.PrepareUpdateImpl().
CreateUpdateStreamProvider()
RequestFileStreamProvider Tgstation.Server.Host.Swarm.SwarmService.CreateUpdateStreamProvider (SwarmServerInformation sourceNode, FileTicketResponse ticket) private
Create the RequestFileStreamProvider for an update package retrieval from a given sourceNode .
Parameters
sourceNode The SwarmServerInformation to download the update package from.
ticket The FileTicketResponse to use for the download.
Returns
A new RequestFileStreamProvider for the update package.
Definition at line 759 of file SwarmService.cs.
        {
            var httpClient = httpClientFactory.CreateClient();
            try
            {
                var request = PrepareSwarmRequest(
                    sourceNode,
                    HttpMethod.Get,
                    $"{SwarmConstants.UpdateRoute}?ticket={HttpUtility.UrlEncode(ticket.FileTicket)}",
                    null);
                try
                {
                    request.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(MediaTypeNames.Application.Octet));
                    return new RequestFileStreamProvider(httpClient, request);
                }
                catch
                {
                    request.Dispose();
                    throw;
                }
            }
            catch
            {
                httpClient.Dispose();
                throw;
            }
        }
References Tgstation.Server.Common.Http.IAbstractHttpClientFactory.CreateClient(), Tgstation.Server.Host.Swarm.SwarmService.httpClientFactory, and Tgstation.Server.Host.Swarm.SwarmService.PrepareSwarmRequest().
Referenced by Tgstation.Server.Host.Swarm.SwarmService.PrepareUpdateImpl().
Dispose()
void Tgstation.Server.Host.Swarm.SwarmService.Dispose ()
GetSwarmServers()
List< SwarmServerInformation >? Tgstation.Server.Host.Swarm.SwarmService.GetSwarmServers ()
Gets the list of SwarmServerInformations in the swarm, including the current one.
Returns
A List<T> of SwarmServerInformations in the swarm. If the server is not part of a swarm, null will be returned.
Implements Tgstation.Server.Host.Swarm.ISwarmService.
Definition at line 365 of file SwarmService.cs.
        {
            if (!SwarmMode)
                return null;
            lock (swarmServers)
                return swarmServers.ToList();
        }
References Tgstation.Server.Host.Swarm.SwarmService.SwarmMode, and Tgstation.Server.Host.Swarm.SwarmService.swarmServers.
HealthCheckController()
async ValueTask Tgstation.Server.Host.Swarm.SwarmService.HealthCheckController (CancellationToken cancellationToken) private
Ping the swarm controller to see that it is still running. If need be, reregister.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Definition at line 1221 of file SwarmService.cs.
        {
            using var httpClient = httpClientFactory.CreateClient();
            if (controllerRegistration.HasValue)
                try
                {
                    using var request = PrepareSwarmRequest(
                        null,
                        HttpMethod.Get,
                        String.Empty,
                        null);
                    using var response = await httpClient.SendAsync(request, HttpCompletionOption.ResponseContentRead, cancellationToken);
                    response.EnsureSuccessStatusCode();
                    logger.LogTrace("Controller health check successful");
                    return;
                }
                catch (Exception ex)
                {
                    logger.LogWarning(ex, "Error during swarm controller health check! Attempting to re-register...");
                    controllerRegistration = null;
                    await AbortUpdate();
                }
            SwarmRegistrationResult registrationResult;
            for (var registrationAttempt = 1UL; ; ++registrationAttempt)
            {
                logger.LogInformation("Swarm re-registration attempt {attemptNumber}...", registrationAttempt);
                registrationResult = await RegisterWithController(cancellationToken);
                if (registrationResult == SwarmRegistrationResult.Success)
                    return;
                if (registrationResult == SwarmRegistrationResult.Unauthorized)
                {
                    logger.LogError("Swarm re-registration failed, controller's private key has changed!");
                    break;
                }
                if (registrationResult == SwarmRegistrationResult.VersionMismatch)
                {
                    logger.LogError("Swarm re-registration failed, controller's TGS version has changed!");
                    break;
                }
                await asyncDelayer.Delay(TimeSpan.FromSeconds(5), cancellationToken);
            }
            // we could do something here... but what?
            // best to just let the health check loop keep retrying... we won't be able to update at least
        }
References Tgstation.Server.Host.Swarm.AbortUpdate.
HealthCheckLoop()
async Task Tgstation.Server.Host.Swarm.SwarmService.HealthCheckLoop (CancellationToken cancellationToken) private
Timed loop for calling HealthCheckNodes(CancellationToken).
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the rinning operation.
Definition at line 1490 of file SwarmService.cs.
        {
            logger.LogTrace("Starting HealthCheckLoop...");
            try
            {
                var nextForceHealthCheckTask = forceHealthCheckTcs!.Task;
                while (!cancellationToken.IsCancellationRequested)
                {
                    TimeSpan delay;
                    if (swarmController)
                        delay = TimeSpan.FromMinutes(SwarmConstants.ControllerHealthCheckIntervalMinutes);
                    else
                    {
                        delay = TimeSpan.FromMinutes(SwarmConstants.NodeHealthCheckIntervalMinutes);
                        if (lastControllerHealthCheck.HasValue)
{
                            var recommendedTimeOfNextCheck = lastControllerHealthCheck.Value + delay;
                            if (recommendedTimeOfNextCheck > DateTimeOffset.UtcNow)
                                delay = recommendedTimeOfNextCheck - DateTimeOffset.UtcNow;
                        }
                    }
                    var delayTask = asyncDelayer.Delay(
                        delay,
                        cancellationToken)
                        .AsTask();
                    var awakeningTask = Task.WhenAny(
                        delayTask,
                        nextForceHealthCheckTask);
                    await awakeningTask;
                    if (nextForceHealthCheckTask.IsCompleted && swarmController)
                    {
                        // Intentionally wait a few seconds for the other server to start up before interogating it
                        logger.LogTrace("Next health check triggering in {delaySeconds}s...", SwarmConstants.SecondsToDelayForcedHealthChecks);
                        await asyncDelayer.Delay(TimeSpan.FromSeconds(SwarmConstants.SecondsToDelayForcedHealthChecks), cancellationToken);
                    }
                    else if (!swarmController && !nextForceHealthCheckTask.IsCompleted)
                    {
                        if (!lastControllerHealthCheck.HasValue)
{
                            logger.LogTrace("Not initially registered with controller, skipping health check.");
                            continue; // unregistered
                        }
                        if ((DateTimeOffset.UtcNow - lastControllerHealthCheck.Value).TotalMinutes < SwarmConstants.NodeHealthCheckIntervalMinutes)
{
                            logger.LogTrace("Controller seems to be active, skipping health check.");
                            continue;
                        }
                    }
                    nextForceHealthCheckTask = forceHealthCheckTcs.Task;
                    logger.LogTrace("Performing swarm health check...");
                    try
                    {
                        if (swarmController)
                            await HealthCheckNodes(cancellationToken);
                        else
                            await HealthCheckController(cancellationToken);
                    }
                    catch (Exception ex) when (ex is not OperationCanceledException)
                    {
                        logger.LogError(ex, "Health check error!");
                    }
                }
            }
            catch (OperationCanceledException ex)
            {
                logger.LogTrace(ex, "Health check loop cancelled!");
            }
            logger.LogTrace("Stopped HealthCheckLoop");
        }
References Tgstation.Server.Host.Swarm.SwarmConstants.ControllerHealthCheckIntervalMinutes, Tgstation.Server.Host.Swarm.SwarmConstants.NodeHealthCheckIntervalMinutes, and Tgstation.Server.Host.Swarm.SwarmConstants.SecondsToDelayForcedHealthChecks.
Referenced by Tgstation.Server.Host.Swarm.SwarmService.Initialize().
HealthCheckNodes()
async ValueTask Tgstation.Server.Host.Swarm.SwarmService.HealthCheckNodes (CancellationToken cancellationToken) private
Ping each node to see that they are still running.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Definition at line 1143 of file SwarmService.cs.
        {
            using var httpClient = httpClientFactory.CreateClient();
            List<SwarmServerInformation> currentSwarmServers;
            lock (swarmServers!)
                currentSwarmServers = swarmServers.ToList();
            var registrationIdsAndTimes = this.registrationIdsAndTimes!;
            async ValueTask HealthRequestForServer(SwarmServerInformation swarmServer)
            {
                using var request = PrepareSwarmRequest(
                    swarmServer,
                    HttpMethod.Get,
                    String.Empty,
                    null);
                try
                {
                    using var response = await httpClient.SendAsync(request, HttpCompletionOption.ResponseContentRead, cancellationToken);
                    response.EnsureSuccessStatusCode();
                    return;
                }
                catch (Exception ex) when (ex is not OperationCanceledException)
                {
                    logger.LogWarning(
                        ex,
                        "Error during swarm server health check on node '{nodeId}'! Unregistering...",
                        swarmServer.Identifier);
                }
                lock (swarmServers)
                {
                    swarmServers.Remove(swarmServer);
                    registrationIdsAndTimes.Remove(swarmServer.Identifier!);
                }
            }
            await ValueTaskExtensions.WhenAll(
                currentSwarmServers
                    .Where(node => !node.Controller
                        && registrationIdsAndTimes.TryGetValue(node.Identifier!, out var registrationAndTime)
                        && registrationAndTime.RegisteredAt.AddMinutes(SwarmConstants.ControllerHealthCheckIntervalMinutes) < DateTimeOffset.UtcNow)
                    .Select(HealthRequestForServer));
            lock (swarmServers)
                if (swarmServers.Count != currentSwarmServers.Count)
                    MarkServersDirty();
            if (serversDirty)
                await SendUpdatedServerListToNodes(cancellationToken);
        }
References Tgstation.Server.Host.Swarm.SwarmConstants.ControllerHealthCheckIntervalMinutes, Tgstation.Server.Api.Models.Internal.SwarmServer.Identifier, and Tgstation.Server.Common.Extensions.ValueTaskExtensions.WhenAll().
Initialize()
async ValueTask< SwarmRegistrationResult > Tgstation.Server.Host.Swarm.SwarmService.Initialize (CancellationToken cancellationToken)
Attempt to register with the swarm controller if not one, sets up the database otherwise.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the SwarmRegistrationResult.
Implements Tgstation.Server.Host.Swarm.ISwarmServiceController.
Definition at line 406 of file SwarmService.cs.
        {
            if (SwarmMode)
                logger.LogInformation(
                    "Swarm mode enabled: {nodeType} {nodeId}",
                    swarmController
                        ? "Controller"
                        : "Node",
                    swarmConfiguration.Identifier);
            else
                logger.LogTrace("Swarm mode disabled");
            SwarmRegistrationResult result;
            if (swarmController)
            {
                if (swarmConfiguration.UpdateRequiredNodeCount > 0)
                    logger.LogInformation("Expecting connections from {expectedNodeCount} nodes", swarmConfiguration.UpdateRequiredNodeCount);
                await databaseContextFactory.UseContext(
                    databaseContext => databaseSeeder.Initialize(databaseContext, cancellationToken));
                result = SwarmRegistrationResult.Success;
            }
            else
                result = await RegisterWithController(cancellationToken);
            if (SwarmMode && result == SwarmRegistrationResult.Success)
                serverHealthCheckTask = HealthCheckLoop(serverHealthCheckCancellationTokenSource.Token);
            return result;
        }
References Tgstation.Server.Host.Swarm.SwarmService.databaseContextFactory, Tgstation.Server.Host.Swarm.SwarmService.databaseSeeder, Tgstation.Server.Host.Swarm.SwarmService.HealthCheckLoop(), Tgstation.Server.Api.Models.Internal.SwarmServer.Identifier, Tgstation.Server.Host.Database.IDatabaseSeeder.Initialize(), Tgstation.Server.Host.Swarm.SwarmService.logger, Tgstation.Server.Host.Swarm.SwarmService.RegisterWithController(), Tgstation.Server.Host.Swarm.SwarmService.serverHealthCheckCancellationTokenSource, Tgstation.Server.Host.Swarm.SwarmService.serverHealthCheckTask, Tgstation.Server.Host.Swarm.SwarmService.swarmConfiguration, Tgstation.Server.Host.Swarm.SwarmService.swarmController, Tgstation.Server.Host.Swarm.SwarmService.SwarmMode, Tgstation.Server.Host.Configuration.SwarmConfiguration.UpdateRequiredNodeCount, and Tgstation.Server.Host.Database.IDatabaseContextFactory.UseContext().
MarkServersDirty()
void Tgstation.Server.Host.Swarm.SwarmService.MarkServersDirty () private
Set serversDirty and complete the current forceHealthCheckTcs.
Definition at line 1199 of file SwarmService.cs.
        {
            serversDirty = true;
            if (TriggerHealthCheck())
                logger.LogTrace("Server list is dirty!");
        }
Referenced by Tgstation.Server.Host.Swarm.SwarmService.RegisterNode(), and Tgstation.Server.Host.Swarm.SwarmService.UnregisterNode().
NodeIdentifierFromRegistration()
string? Tgstation.Server.Host.Swarm.SwarmService.NodeIdentifierFromRegistration (Guid registrationId) private
Gets the SwarmServer.Identifier from a given registrationId .
Parameters
registrationId The registration Guid.
Returns
The registered SwarmServer.Identifier or null if it does not exist.
Definition at line 1574 of file SwarmService.cs.
        {
            if (!swarmController)
                throw new InvalidOperationException("NodeIdentifierFromRegistration on node!");
            lock (swarmServers!)
            {
                var registrationIdsAndTimes = this.registrationIdsAndTimes!;
                var exists = registrationIdsAndTimes.Any(x => x.Value.RegistrationId == registrationId);
                if (!exists)
                {
                    logger.LogWarning("A node that was to be looked up ({registrationId}) disappeared from our records!", registrationId);
                    return null;
                }
                return registrationIdsAndTimes.First(x => x.Value.RegistrationId == registrationId).Key;
            }
        }
Referenced by Tgstation.Server.Host.Swarm.SwarmService.RemoteCommitReceived(), and Tgstation.Server.Host.Swarm.SwarmService.UnregisterNode().
PrepareSwarmRequest()
HttpRequestMessage Tgstation.Server.Host.Swarm.SwarmService.PrepareSwarmRequest (SwarmServerInformation? swarmServer, HttpMethod httpMethod, string route, object? body, Guid? registrationIdOverride = null) private
Prepares a HttpRequestMessage for swarm communication.
Parameters
swarmServer The SwarmServerInformation the message is for. Must have SwarmServer.Address and SwarmServer.Identifier set. If null, will be sent to swarm controller.
httpMethod The HttpMethod.
route The route on SwarmConstants.ControllerRoute to use.
body The body object if any.
registrationIdOverride An optional override to the SwarmConstants.RegistrationIdHeader.
Returns
A new HttpRequestMessage.
Definition at line 1431 of file SwarmService.cs.
        {
            swarmServer ??= new SwarmServerInformation
            {
                Address = swarmConfiguration.ControllerAddress,
            };
            var fullRoute = $"{SwarmConstants.ControllerRoute}/{route}";
            logger.LogTrace(
                "{method} {route} to swarm server {nodeIdOrAddress}",
                httpMethod,
                fullRoute,
                swarmServer.Identifier ?? swarmServer.Address!.ToString());
            var request = new HttpRequestMessage(
                httpMethod,
                swarmServer.Address + fullRoute[1..]);
            try
            {
                request.Headers.Accept.Clear();
                request.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(MediaTypeNames.Application.Json));
                request.Headers.Add(SwarmConstants.ApiKeyHeader, swarmConfiguration.PrivateKey);
                if (registrationIdOverride.HasValue)
                    request.Headers.Add(SwarmConstants.RegistrationIdHeader, registrationIdOverride.Value.ToString());
                else if (swarmController)
                {
                    lock (swarmServers!)
                        if (registrationIdsAndTimes!.TryGetValue(swarmServer.Identifier!, out var registrationIdAndTime))
                            request.Headers.Add(SwarmConstants.RegistrationIdHeader, registrationIdAndTime.RegistrationId.ToString());
                }
                else if (controllerRegistration.HasValue)
                    request.Headers.Add(SwarmConstants.RegistrationIdHeader, controllerRegistration.Value.ToString());
                if (body != null)
                    request.Content = new StringContent(
                        JsonConvert.SerializeObject(body, SwarmConstants.SerializerSettings),
                        Encoding.UTF8,
                        MediaTypeNames.Application.Json);
                return request;
            }
            catch
            {
                request.Dispose();
                throw;
            }
        }
References Tgstation.Server.Api.Models.Internal.SwarmServer.Address, Tgstation.Server.Host.Swarm.SwarmConstants.ApiKeyHeader, Tgstation.Server.Api.Models.Internal.SwarmServer.Identifier, Tgstation.Server.Host.Swarm.SwarmConstants.RegistrationIdHeader, and Tgstation.Server.Host.Swarm.SwarmConstants.SerializerSettings.
Referenced by Tgstation.Server.Host.Swarm.SwarmService.CommitUpdate(), Tgstation.Server.Host.Swarm.SwarmService.ControllerDistributedPrepareUpdate(), Tgstation.Server.Host.Swarm.SwarmService.CreateUpdateStreamProvider(), Tgstation.Server.Host.Swarm.SwarmService.PrepareUpdateImpl(), Tgstation.Server.Host.Swarm.SwarmService.RemoteAbortUpdate(), and Tgstation.Server.Host.Swarm.SwarmService.Shutdown().
PrepareUpdate()
ValueTask< SwarmPrepareResult > Tgstation.Server.Host.Swarm.SwarmService.PrepareUpdate (ISeekableFileStreamProvider fileStreamProvider, Version version, CancellationToken cancellationToken)
Signal to the swarm that an update is requested.
Parameters
fileStreamProvider The ISeekableFileStreamProvider to relay to other nodes.
version The Version to update to.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in true if the update should proceed, false otherwise.
Implements Tgstation.Server.Host.Swarm.ISwarmService.
Definition at line 375 of file SwarmService.cs.
        {
            ArgumentNullException.ThrowIfNull(fileStreamProvider);
            ArgumentNullException.ThrowIfNull(version);
            logger.LogTrace("Begin PrepareUpdate...");
            return PrepareUpdateImpl(
                fileStreamProvider,
                new SwarmUpdateRequest
                {
                    UpdateVersion = version,
                },
                cancellationToken);
        }
References Tgstation.Server.Host.Swarm.SwarmService.logger, and Tgstation.Server.Host.Swarm.SwarmService.PrepareUpdateImpl().
PrepareUpdateFromController()
async ValueTask< bool > Tgstation.Server.Host.Swarm.SwarmService.PrepareUpdateFromController (SwarmUpdateRequest updateRequest, CancellationToken cancellationToken)
Notify the node of an update request from the controller.
Parameters
updateRequest The SwarmUpdateRequest.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in true if the node is able to update, false otherwise.
Implements Tgstation.Server.Host.Swarm.ISwarmOperations.
Definition at line 392 of file SwarmService.cs.
        {
            ArgumentNullException.ThrowIfNull(updateRequest);
            logger.LogInformation("Received remote update request from {nodeType}", !swarmController ? "controller" : "node");
            var result = await PrepareUpdateImpl(
                null,
                updateRequest,
                cancellationToken);
            return result != SwarmPrepareResult.Failure;
        }
References Tgstation.Server.Host.Swarm.SwarmService.logger, Tgstation.Server.Host.Swarm.SwarmService.PrepareUpdateImpl(), and Tgstation.Server.Host.Swarm.SwarmService.swarmController.
PrepareUpdateImpl()
async ValueTask< SwarmPrepareResult > Tgstation.Server.Host.Swarm.SwarmService.PrepareUpdateImpl (ISeekableFileStreamProvider? initiatorProvider, SwarmUpdateRequest updateRequest, CancellationToken cancellationToken) private
Implementation of PrepareUpdate(ISeekableFileStreamProvider, Version, CancellationToken),.
Parameters
initiatorProvider The ISeekableFileStreamProvider containing the update package if this is the initiating server, null otherwise.
updateRequest The SwarmUpdateRequest. Must always have SwarmUpdateRequest.UpdateVersion populated. If initiatorProvider is null, it must be fully populated.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the SwarmPrepareResult.
Definition at line 795 of file SwarmService.cs.
        {
            var version = updateRequest.UpdateVersion!;
            if (!SwarmMode)
            {
                // we still need an active update operation for the TargetVersion
                updateOperation = new SwarmUpdateOperation(version);
                return SwarmPrepareResult.SuccessProviderNotRequired;
            }
            var initiator = initiatorProvider != null;
            logger.LogTrace("PrepareUpdateImpl {version}...", version);
            var shouldAbort = false;
            SwarmUpdateOperation localUpdateOperation;
            try
            {
                SwarmServerInformation? sourceNode = null;
                List<SwarmServerInformation> currentNodes;
                lock (swarmServers)
                {
                    currentNodes = swarmServers
                        .Select(node =>
{
                            if (node.Identifier == updateRequest.SourceNode)
                                sourceNode = node;
                            return node;
                        })
                        .ToList();
                    if (swarmController)
                        localUpdateOperation = new SwarmUpdateOperation(
                            version,
                            currentNodes);
                    else
                        localUpdateOperation = new SwarmUpdateOperation(version);
                }
                var existingUpdateOperation = Interlocked.CompareExchange(ref updateOperation, localUpdateOperation, null);
                if (existingUpdateOperation != null && existingUpdateOperation.TargetVersion != version)
                {
                    logger.LogWarning("Aborting update preparation, version {targetUpdateVersion} already prepared!", existingUpdateOperation.TargetVersion);
                    shouldAbort = true;
                    return SwarmPrepareResult.Failure;
                }
                if (existingUpdateOperation?.TargetVersion == version)
                {
                    logger.LogTrace("PrepareUpdateImpl early out, already prepared!");
                    return SwarmPrepareResult.SuccessProviderNotRequired;
                }
                if (!swarmController && initiator)
                {
                    var downloadTickets = await CreateDownloadTickets(initiatorProvider!, currentNodes, cancellationToken); // condition of initiator
                    logger.LogInformation("Forwarding update request to swarm controller...");
                    using var httpClient = httpClientFactory.CreateClient();
                    using var request = PrepareSwarmRequest(
                        null,
                        HttpMethod.Put,
                        SwarmConstants.UpdateRoute,
                        new SwarmUpdateRequest
{
                            UpdateVersion = version,
                            SourceNode = swarmConfiguration.Identifier,
                            DownloadTickets = downloadTickets,
                        });
                    // File transfer service will hold the necessary streams
                    using var response = await httpClient.SendAsync(request, HttpCompletionOption.ResponseContentRead, cancellationToken);
                    if (response.IsSuccessStatusCode)
                        return SwarmPrepareResult.SuccessHoldProviderUntilCommit;
                    shouldAbort = true;
                    return SwarmPrepareResult.Failure;
                }
                if (!initiator)
                {
                    logger.LogTrace("Beginning local update process...");
                    if (sourceNode == null)
                    {
                        logger.Log(
                            swarmController
                                ? LogLevel.Error
                                : LogLevel.Warning,
                            "Missing local node entry for update source node: {sourceNode}",
                            updateRequest.SourceNode);
                        shouldAbort = true;
                        return SwarmPrepareResult.Failure;
                    }
                    if (updateRequest.DownloadTickets == null)
                    {
                        logger.LogError("Missing download tickets in update request!");
                        return SwarmPrepareResult.Failure;
                    }
                    if (!updateRequest.DownloadTickets.TryGetValue(swarmConfiguration.Identifier!, out var ticket))
                    {
                        logger.Log(
                            swarmController
                                ? LogLevel.Error
                                : LogLevel.Warning,
                            "Missing node entry for download ticket in update request!");
                        shouldAbort = true;
                        return SwarmPrepareResult.Failure;
                    }
                    ServerUpdateResult updateApplyResult;
                    var downloaderStream = CreateUpdateStreamProvider(sourceNode, ticket);
                    try
                    {
                        updateApplyResult = await serverUpdater.BeginUpdate(
                            this,
                            downloaderStream,
                            version,
                            cancellationToken);
                    }
                    catch
                    {
                        await downloaderStream.DisposeAsync();
                        throw;
                    }
                    if (updateApplyResult != ServerUpdateResult.Started)
                    {
                        logger.LogWarning("Failed to prepare update! Result: {serverUpdateResult}", updateApplyResult);
                        shouldAbort = true;
                        return SwarmPrepareResult.Failure;
                    }
                }
                else
                    logger.LogTrace("No need to re-initiate update as it originated here on the swarm controller");
                logger.LogDebug("Local node prepared for update to version {version}", version);
            }
            catch (Exception ex)
            {
                logger.LogWarning(ex, "Failed to prepare update!");
                shouldAbort = true;
                return SwarmPrepareResult.Failure;
            }
            finally
            {
                if (shouldAbort)
                    await AbortUpdate();
            }
            if (!swarmController)
                return SwarmPrepareResult.SuccessProviderNotRequired;
            return await ControllerDistributedPrepareUpdate(
                initiatorProvider,
                updateRequest,
                localUpdateOperation,
                cancellationToken);
        }
References Tgstation.Server.Host.Swarm.SwarmService.AbortUpdate(), Tgstation.Server.Host.Core.IServerUpdater.BeginUpdate(), Tgstation.Server.Host.Swarm.SwarmService.ControllerDistributedPrepareUpdate(), Tgstation.Server.Common.Http.IAbstractHttpClientFactory.CreateClient(), Tgstation.Server.Host.Swarm.SwarmService.CreateDownloadTickets(), Tgstation.Server.Host.Swarm.SwarmService.CreateUpdateStreamProvider(), Tgstation.Server.Host.Swarm.SwarmUpdateRequest.DownloadTickets, Tgstation.Server.Host.Swarm.SwarmService.httpClientFactory, Tgstation.Server.Api.Models.Internal.SwarmServer.Identifier, Tgstation.Server.Host.Swarm.SwarmService.logger, Tgstation.Server.Host.Swarm.SwarmService.PrepareSwarmRequest(), Tgstation.Server.Host.Swarm.SwarmService.serverUpdater, Tgstation.Server.Host.Swarm.SwarmUpdateRequest.SourceNode, Tgstation.Server.Host.Swarm.SwarmService.swarmConfiguration, Tgstation.Server.Host.Swarm.SwarmService.swarmController, Tgstation.Server.Host.Swarm.SwarmService.SwarmMode, Tgstation.Server.Host.Swarm.SwarmService.swarmServers, Tgstation.Server.Host.Swarm.SwarmService.updateOperation, Tgstation.Server.Host.Swarm.SwarmConstants.UpdateRoute, and Tgstation.Server.Host.Swarm.SwarmUpdateRequest.UpdateVersion.
Referenced by Tgstation.Server.Host.Swarm.SwarmService.PrepareUpdate(), and Tgstation.Server.Host.Swarm.SwarmService.PrepareUpdateFromController().
RegisterNode()
async ValueTask< SwarmRegistrationResponse?> Tgstation.Server.Host.Swarm.SwarmService.RegisterNode (SwarmServer node, Guid registrationId, CancellationToken cancellationToken)
Attempt to register a given node with the controller.
Parameters
node The SwarmServer that is registering.
registrationId The registration Guid.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a SwarmRegistrationResponse if the registration was successful, null otherwise.
Implements Tgstation.Server.Host.Swarm.ISwarmOperations.
Definition at line 555 of file SwarmService.cs.
        {
            ArgumentNullException.ThrowIfNull(node);
            if (node.Identifier == null)
                throw new ArgumentException("Node missing Identifier!", nameof(node));
            if (node.Address == null)
                throw new ArgumentException("Node missing Address!", nameof(node));
            if (!SwarmMode)
                throw new InvalidOperationException("Swarm mode not enabled!");
            if (!swarmController)
                throw new InvalidOperationException("Cannot RegisterNode on swarm node!");
            logger.LogTrace("RegisterNode");
            await AbortUpdate();
            SwarmRegistrationResponse CreateResponse() => new()
            {
                TokenSigningKeyBase64 = Convert.ToBase64String(tokenFactory.SigningKeyBytes),
            };
            var registrationIdsAndTimes = this.registrationIdsAndTimes!;
            lock (swarmServers)
            {
                if (registrationIdsAndTimes.Any(x => x.Value.RegistrationId == registrationId))
                {
                    var preExistingRegistrationKvp = registrationIdsAndTimes.FirstOrDefault(x => x.Value.RegistrationId == registrationId);
                    if (preExistingRegistrationKvp.Key == node.Identifier)
                    {
                        logger.LogWarning("Node {nodeId} has already registered!", node.Identifier);
                        return CreateResponse();
                    }
                    logger.LogWarning(
                        "Registration ID collision! Node {nodeId} tried to register with {otherNodeId}'s registration ID: {registrationId}",
                        node.Identifier,
                        preExistingRegistrationKvp.Key,
                        registrationId);
                    return null;
                }
                if (registrationIdsAndTimes.TryGetValue(node.Identifier, out var oldRegistration))
                {
                    logger.LogInformation("Node {nodeId} is re-registering without first unregistering. Indicative of restart.", node.Identifier);
                    swarmServers.RemoveAll(x => x.Identifier == node.Identifier);
                    registrationIdsAndTimes.Remove(node.Identifier);
                }
                swarmServers.Add(new SwarmServerInformation
                {
                    PublicAddress = node.PublicAddress,
                    Address = node.Address,
                    Identifier = node.Identifier,
                    Controller = false,
                });
                registrationIdsAndTimes.Add(node.Identifier, (RegistrationId: registrationId, DateTimeOffset.UtcNow));
            }
            logger.LogInformation("Registered node {nodeId} ({nodeIP}) with ID {registrationId}", node.Identifier, node.Address, registrationId);
            MarkServersDirty();
            return CreateResponse();
        }
References Tgstation.Server.Host.Swarm.SwarmService.AbortUpdate(), Tgstation.Server.Api.Models.Internal.SwarmServer.Address, Tgstation.Server.Api.Models.Internal.SwarmServer.Identifier, Tgstation.Server.Host.Swarm.SwarmService.logger, Tgstation.Server.Host.Swarm.SwarmService.MarkServersDirty(), Tgstation.Server.Api.Models.Internal.SwarmServer.PublicAddress, Tgstation.Server.Host.Swarm.SwarmService.registrationIdsAndTimes, Tgstation.Server.Host.Security.ITokenFactory.SigningKeyBytes, Tgstation.Server.Host.Swarm.SwarmService.swarmController, Tgstation.Server.Host.Swarm.SwarmService.SwarmMode, Tgstation.Server.Host.Swarm.SwarmService.swarmServers, and Tgstation.Server.Host.Swarm.SwarmService.tokenFactory.
RegisterWithController()
async ValueTask< SwarmRegistrationResult > Tgstation.Server.Host.Swarm.SwarmService.RegisterWithController (CancellationToken cancellationToken) private
Attempt to register the node with the controller.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the SwarmRegistrationResult.
Definition at line 1278 of file SwarmService.cs.
        {
            logger.LogInformation("Attempting to register with swarm controller at {controllerAddress}...", swarmConfiguration.ControllerAddress);
            var requestedRegistrationId = Guid.NewGuid();
            using var httpClient = httpClientFactory.CreateClient();
            using var registrationRequest = PrepareSwarmRequest(
                null,
                HttpMethod.Post,
                SwarmConstants.RegisterRoute,
                new SwarmRegistrationRequest(Version.Parse(MasterVersionsAttribute.Instance.RawSwarmProtocolVersion))
                {
                    Identifier = swarmConfiguration.Identifier,
                    Address = swarmConfiguration.Address,
                    PublicAddress = swarmConfiguration.PublicAddress,
                },
                requestedRegistrationId);
            try
            {
                using var response = await httpClient.SendAsync(registrationRequest, HttpCompletionOption.ResponseContentRead, cancellationToken);
                if (response.IsSuccessStatusCode)
                {
                    try
                    {
                        var json = await response.Content.ReadAsStringAsync(cancellationToken);
                        if (json == null)
{
                            logger.LogDebug("Error reading registration response content stream! Text was null!");
                            return SwarmRegistrationResult.PayloadFailure;
                        }
                        var registrationResponse = JsonConvert.DeserializeObject<SwarmRegistrationResponse>(json);
                        if (registrationResponse == null)
{
                            logger.LogDebug("Error reading registration response content stream! Payload was null!");
                            return SwarmRegistrationResult.PayloadFailure;
                        }
                        if (registrationResponse.TokenSigningKeyBase64 == null)
{
                            logger.LogDebug("Error reading registration response content stream! SigningKey was null!");
                            return SwarmRegistrationResult.PayloadFailure;
                        }
                        tokenFactory.SigningKeyBytes = Convert.FromBase64String(registrationResponse.TokenSigningKeyBase64);
                    }
                    catch (Exception ex)
                    {
                        logger.LogDebug(ex, "Error reading registration response content stream!");
                        return SwarmRegistrationResult.PayloadFailure;
                    }
                    logger.LogInformation("Sucessfully registered with ID {registrationId}", requestedRegistrationId);
                    controllerRegistration = requestedRegistrationId;
                    lastControllerHealthCheck = DateTimeOffset.UtcNow;
                    return SwarmRegistrationResult.Success;
                }
                logger.LogWarning("Unable to register with swarm: HTTP {statusCode}!", response.StatusCode);
                if (response.StatusCode == HttpStatusCode.Unauthorized)
                    return SwarmRegistrationResult.Unauthorized;
                if (response.StatusCode == HttpStatusCode.UpgradeRequired)
                    return SwarmRegistrationResult.VersionMismatch;
                try
                {
                    var responseData = await response.Content.ReadAsStringAsync(cancellationToken);
                    if (!String.IsNullOrWhiteSpace(responseData))
                        logger.LogDebug("Response:{newLine}{responseData}", Environment.NewLine, responseData);
                }
                catch (Exception ex)
                {
                    logger.LogDebug(ex, "Error reading registration response content stream!");
                }
            }
            catch (Exception ex)
            {
                logger.LogWarning(ex, "Error sending registration request!");
            }
            return SwarmRegistrationResult.CommunicationFailure;
        }
References Tgstation.Server.Host.Properties.MasterVersionsAttribute.Instance, Tgstation.Server.Host.Properties.MasterVersionsAttribute.RawSwarmProtocolVersion, and Tgstation.Server.Host.Swarm.SwarmConstants.RegisterRoute.
Referenced by Tgstation.Server.Host.Swarm.SwarmService.Initialize().
RemoteAbortUpdate()
ValueTask Tgstation.Server.Host.Swarm.SwarmService.RemoteAbortUpdate () private
Sends out remote abort update requests.
Returns
A ValueTask representing the running operation.
The aborted updateOperation should be cleared out before calling this. This method does not accept a CancellationToken because aborting an update should never be cancelled.
Definition at line 709 of file SwarmService.cs.
        {
            logger.LogInformation("Aborting swarm update!");
            using var httpClient = httpClientFactory.CreateClient();
            async ValueTask SendRemoteAbort(SwarmServerInformation swarmServer)
            {
                using var request = PrepareSwarmRequest(
                    swarmServer,
                    HttpMethod.Delete,
                    SwarmConstants.UpdateRoute,
                    null);
                try
                {
                    // DCT: Intentionally should not be cancelled
                    using var response = await httpClient.SendAsync(request, HttpCompletionOption.ResponseContentRead, CancellationToken.None);
                    response.EnsureSuccessStatusCode();
                }
                catch (Exception ex)
                {
                    logger.LogWarning(
                        ex,
                        "Unable to send remote abort to {nodeOrController}!",
                        swarmController
                            ? $"node {swarmServer.Identifier}"
                            : "controller");
                }
            }
            if (!swarmController)
                return SendRemoteAbort(new SwarmServerInformation
                {
                    Address = swarmConfiguration.ControllerAddress,
                });
            lock (swarmServers!)
                return ValueTaskExtensions.WhenAll(
                    swarmServers
                        .Where(x => !x.Controller)
                        .Select(SendRemoteAbort)
                        .ToList());
        }
References Tgstation.Server.Host.Configuration.SwarmConfiguration.ControllerAddress, Tgstation.Server.Common.Http.IAbstractHttpClientFactory.CreateClient(), Tgstation.Server.Host.Swarm.SwarmService.httpClientFactory, Tgstation.Server.Host.Swarm.SwarmService.logger, Tgstation.Server.Host.Swarm.SwarmService.PrepareSwarmRequest(), Tgstation.Server.Host.Swarm.SwarmService.swarmConfiguration, Tgstation.Server.Host.Swarm.SwarmService.swarmController, Tgstation.Server.Host.Swarm.SwarmService.swarmServers, Tgstation.Server.Host.Swarm.SwarmConstants.UpdateRoute, and Tgstation.Server.Common.Extensions.ValueTaskExtensions.WhenAll().
Referenced by Tgstation.Server.Host.Swarm.SwarmService.AbortUpdate(), and Tgstation.Server.Host.Swarm.SwarmService.RemoteCommitReceived().
RemoteCommitReceived()
async ValueTask< bool > Tgstation.Server.Host.Swarm.SwarmService.RemoteCommitReceived (Guid registrationId, CancellationToken cancellationToken)
Notify the controller that the node with the given registrationId is ready to commit or notify the node of the controller telling it to commit.
Parameters
registrationId The registration Guid.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Swarm.ISwarmOperations.
Definition at line 623 of file SwarmService.cs.
        {
            var localUpdateOperation = updateOperation;
            if (!swarmController)
            {
                logger.LogDebug("Received remote commit go ahead");
                return localUpdateOperation?.Commit() == true;
            }
            var nodeIdentifier = NodeIdentifierFromRegistration(registrationId);
            if (nodeIdentifier == null)
            {
                // Something fucky is happening, take no chances.
                logger.LogError("Aborting update due to unforseen circumstances!");
                await AbortUpdate();
                return false;
            }
            if (localUpdateOperation == null)
            {
                logger.LogDebug("Ignoring ready-commit from node {nodeId} as the update appears to have been aborted.", nodeIdentifier);
                return false;
            }
            if (!localUpdateOperation.MarkNodeReady(nodeIdentifier))
            {
                logger.LogError(
                    "Attempting to mark {nodeId} as ready to commit resulted in the update being aborted!",
                    nodeIdentifier);
                // bit racy here, localUpdateOperation has already been aborted.
                // now if, FOR SOME GODFORSAKEN REASON, there's a new update operation, abort that too.
                if (Interlocked.CompareExchange(ref updateOperation, null, localUpdateOperation) == localUpdateOperation)
                    await RemoteAbortUpdate();
                else
                {
                    // marking as an error because how the actual fuck
                    logger.LogError("Aborting new update due to unforseen consequences!");
                    await AbortUpdate();
                }
                return false;
            }
            logger.LogDebug("Node {nodeId} is ready to commit.", nodeIdentifier);
            return true;
        }
References Tgstation.Server.Host.Swarm.SwarmService.AbortUpdate(), Tgstation.Server.Host.Swarm.SwarmUpdateOperation.Commit(), Tgstation.Server.Host.Swarm.SwarmService.logger, Tgstation.Server.Host.Swarm.SwarmService.NodeIdentifierFromRegistration(), Tgstation.Server.Host.Swarm.SwarmService.RemoteAbortUpdate(), Tgstation.Server.Host.Swarm.SwarmService.swarmController, and Tgstation.Server.Host.Swarm.SwarmService.updateOperation.
SendUpdatedServerListToNodes()
async ValueTask Tgstation.Server.Host.Swarm.SwarmService.SendUpdatedServerListToNodes (CancellationToken cancellationToken) private
Sends the controllers list of nodes to all nodes.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Definition at line 1369 of file SwarmService.cs.
        {
            List<SwarmServerInformation> currentSwarmServers;
            lock (swarmServers!)
            {
                serversDirty = false;
                currentSwarmServers = swarmServers.ToList();
            }
            if (currentSwarmServers.Count == 1)
            {
                logger.LogTrace("Skipping server list broadcast as no nodes are connected!");
                return;
            }
            logger.LogDebug("Sending updated server list to all {nodeCount} nodes...", currentSwarmServers.Count - 1);
            using var httpClient = httpClientFactory.CreateClient();
            async ValueTask UpdateRequestForServer(SwarmServerInformation swarmServer)
            {
                using var request = PrepareSwarmRequest(
                    swarmServer,
                    HttpMethod.Post,
                    String.Empty,
                    new SwarmServersUpdateRequest
                    {
                        SwarmServers = currentSwarmServers,
                    });
                try
                {
                    using var response = await httpClient.SendAsync(request, HttpCompletionOption.ResponseContentRead, cancellationToken);
                    response.EnsureSuccessStatusCode();
                }
                catch (Exception ex) when (ex is not OperationCanceledException)
                {
                    logger.LogWarning(ex, "Error during swarm server list update for node '{nodeId}'! Unregistering...", swarmServer.Identifier);
                    lock (swarmServers)
                    {
                        swarmServers.Remove(swarmServer);
                        registrationIdsAndTimes!.Remove(swarmServer.Identifier!);
                    }
                }
            }
            await ValueTaskExtensions.WhenAll(
                currentSwarmServers
                    .Where(x => !x.Controller)
                    .Select(UpdateRequestForServer)
                    .ToList());
        }
References Tgstation.Server.Api.Models.Internal.SwarmServer.Identifier, and Tgstation.Server.Common.Extensions.ValueTaskExtensions.WhenAll().
Shutdown()
async ValueTask Tgstation.Server.Host.Swarm.SwarmService.Shutdown (CancellationToken cancellationToken)
Deregister with the swarm controller or put clients into querying state.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Swarm.ISwarmServiceController.
Definition at line 439 of file SwarmService.cs.
        {
            logger.LogTrace("Begin Shutdown");
            async ValueTask SendUnregistrationRequest(SwarmServerInformation? swarmServer)
            {
                using var httpClient = httpClientFactory.CreateClient();
                using var request = PrepareSwarmRequest(
                    swarmServer,
                    HttpMethod.Delete,
                    SwarmConstants.RegisterRoute,
                    null);
                try
                {
                    using var response = await httpClient.SendAsync(request, HttpCompletionOption.ResponseContentRead, cancellationToken);
                    response.EnsureSuccessStatusCode();
                }
                catch (Exception ex)
                {
                    logger.LogWarning(
                        ex,
                        "Error unregistering {nodeType}!",
                        swarmServer != null
                            ? $"node {swarmServer.Identifier}"
                            : "from controller");
                }
            }
            if (SwarmMode && serverHealthCheckTask != null)
            {
                serverHealthCheckCancellationTokenSource.Cancel();
                await serverHealthCheckTask;
            }
            if (!swarmController)
            {
                if (controllerRegistration != null)
                {
                    logger.LogInformation("Unregistering from swarm controller...");
                    await SendUnregistrationRequest(null);
                }
                return;
            }
            // We're in a single-threaded-like context now so touching updateOperation directly is fine
            // downgrade the db if necessary
            if (updateOperation != null
                && updateOperation.TargetVersion < assemblyInformationProvider.Version)
                await databaseContextFactory.UseContext(
                    db => databaseSeeder.Downgrade(db, updateOperation.TargetVersion, cancellationToken));
            if (SwarmMode)
            {
                // Put the nodes into a reconnecting state
                if (updateOperation == null)
                {
                    logger.LogInformation("Unregistering nodes...");
                    ValueTask task;
                    lock (swarmServers)
                    {
                        task = ValueTaskExtensions.WhenAll(
                            swarmServers
                                .Where(x => !x.Controller)
                                .Select(SendUnregistrationRequest)
                                .ToList());
                        swarmServers.RemoveRange(1, swarmServers.Count - 1);
                        registrationIdsAndTimes!.Clear();
                    }
                    await task;
                }
                logger.LogTrace("Swarm controller shutdown");
            }
        }
References Tgstation.Server.Host.Swarm.SwarmService.assemblyInformationProvider, Tgstation.Server.Host.Swarm.SwarmService.controllerRegistration, Tgstation.Server.Common.Http.IAbstractHttpClientFactory.CreateClient(), Tgstation.Server.Host.Swarm.SwarmService.databaseContextFactory, Tgstation.Server.Host.Swarm.SwarmService.databaseSeeder, Tgstation.Server.Host.Database.IDatabaseSeeder.Downgrade(), Tgstation.Server.Host.Swarm.SwarmService.httpClientFactory, Tgstation.Server.Host.Swarm.SwarmService.logger, Tgstation.Server.Host.Swarm.SwarmService.PrepareSwarmRequest(), Tgstation.Server.Host.Swarm.SwarmConstants.RegisterRoute, Tgstation.Server.Host.Swarm.SwarmService.registrationIdsAndTimes, Tgstation.Server.Host.Swarm.SwarmService.serverHealthCheckCancellationTokenSource, Tgstation.Server.Host.Swarm.SwarmService.serverHealthCheckTask, Tgstation.Server.Host.Swarm.SwarmService.swarmController, Tgstation.Server.Host.Swarm.SwarmService.SwarmMode, Tgstation.Server.Host.Swarm.SwarmService.swarmServers, Tgstation.Server.Host.Swarm.SwarmUpdateOperation.TargetVersion, Tgstation.Server.Host.Swarm.SwarmService.updateOperation, Tgstation.Server.Host.Database.IDatabaseContextFactory.UseContext(), Tgstation.Server.Host.System.IAssemblyInformationProvider.Version, and Tgstation.Server.Common.Extensions.ValueTaskExtensions.WhenAll().
TriggerHealthCheck()
bool Tgstation.Server.Host.Swarm.SwarmService.TriggerHealthCheck () private
Complete the current forceHealthCheckTcs.
Returns
true the result of the call to TaskCompletionSource<TResult>.TrySetResult(TResult).
Definition at line 1210 of file SwarmService.cs.
        {
            var currentTcs = Interlocked.Exchange(ref forceHealthCheckTcs, new TaskCompletionSource());
            return currentTcs!.TrySetResult();
        }
Referenced by Tgstation.Server.Host.Swarm.SwarmService.UnregisterNode().
UnregisterNode()
async ValueTask Tgstation.Server.Host.Swarm.SwarmService.UnregisterNode (Guid registrationId, CancellationToken cancellationToken)
Attempt to unregister a node with a given registrationId with the controller.
Parameters
registrationId The registration Guid.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Swarm.ISwarmOperations.
Definition at line 672 of file SwarmService.cs.
        {
            if (!SwarmMode)
                throw new InvalidOperationException("Swarm mode not enabled!");
            logger.LogTrace("UnregisterNode {registrationId}", registrationId);
            await AbortUpdate();
            if (!swarmController)
            {
                // immediately trigger a health check
                logger.LogInformation("Controller unregistering, will attempt re-registration...");
                controllerRegistration = null;
                TriggerHealthCheck();
                return;
            }
            var nodeIdentifier = NodeIdentifierFromRegistration(registrationId);
            if (nodeIdentifier == null)
                return;
            logger.LogInformation("Unregistering node {nodeId}...", nodeIdentifier);
            lock (swarmServers)
            {
                swarmServers.RemoveAll(x => x.Identifier == nodeIdentifier);
                registrationIdsAndTimes!.Remove(nodeIdentifier);
            }
            MarkServersDirty();
        }
References Tgstation.Server.Host.Swarm.SwarmService.AbortUpdate(), Tgstation.Server.Host.Swarm.SwarmService.controllerRegistration, Tgstation.Server.Host.Swarm.SwarmService.logger, Tgstation.Server.Host.Swarm.SwarmService.MarkServersDirty(), Tgstation.Server.Host.Swarm.SwarmService.NodeIdentifierFromRegistration(), Tgstation.Server.Host.Swarm.SwarmService.registrationIdsAndTimes, Tgstation.Server.Host.Swarm.SwarmService.swarmController, Tgstation.Server.Host.Swarm.SwarmService.SwarmMode, Tgstation.Server.Host.Swarm.SwarmService.swarmServers, and Tgstation.Server.Host.Swarm.SwarmService.TriggerHealthCheck().
UpdateSwarmServersList()
void Tgstation.Server.Host.Swarm.SwarmService.UpdateSwarmServersList (IEnumerable< SwarmServerInformation > swarmServers)
Pass in an updated list of swarmServers to the node.
Parameters
swarmServers An IEnumerable<T> of the updated SwarmServerInformations.
Implements Tgstation.Server.Host.Swarm.ISwarmOperations.
Definition at line 519 of file SwarmService.cs.
        {
            ArgumentNullException.ThrowIfNull(swarmServers);
            if (!SwarmMode)
                throw new InvalidOperationException("Swarm mode not enabled!");
            if (swarmController)
                throw new InvalidOperationException("Cannot UpdateSwarmServersList on swarm controller!");
            lock (this.swarmServers)
            {
                this.swarmServers.Clear();
                this.swarmServers.AddRange(swarmServers);
                logger.LogDebug("Updated swarm server list with {nodeCount} total nodes", this.swarmServers.Count);
            }
        }
References Tgstation.Server.Host.Swarm.SwarmService.logger, Tgstation.Server.Host.Swarm.SwarmService.swarmController, Tgstation.Server.Host.Swarm.SwarmService.SwarmMode, and Tgstation.Server.Host.Swarm.SwarmService.swarmServers.
ValidateRegistration()
bool Tgstation.Server.Host.Swarm.SwarmService.ValidateRegistration (Guid registrationId)
Validate a given registrationId .
Parameters
registrationId The registration Guid to validate.
Returns
true if the registration is valid, false otherwise.
Implements Tgstation.Server.Host.Swarm.ISwarmOperations.
Definition at line 538 of file SwarmService.cs.
        {
            if (!SwarmMode)
                throw new InvalidOperationException("Swarm mode not enabled!");
            if (swarmController)
                lock (swarmServers)
                    return registrationIdsAndTimes!.Values.Any(x => x.RegistrationId == registrationId);
            if (registrationId != controllerRegistration)
                return false;
            lastControllerHealthCheck = DateTimeOffset.UtcNow;
            return true;
        }
References Tgstation.Server.Host.Swarm.SwarmService.controllerRegistration, Tgstation.Server.Host.Swarm.SwarmService.lastControllerHealthCheck, Tgstation.Server.Host.Swarm.SwarmService.registrationIdsAndTimes, Tgstation.Server.Host.Swarm.SwarmService.swarmController, Tgstation.Server.Host.Swarm.SwarmService.SwarmMode, and Tgstation.Server.Host.Swarm.SwarmService.swarmServers.
Member Data Documentation
assemblyInformationProvider
readonly IAssemblyInformationProvider Tgstation.Server.Host.Swarm.SwarmService.assemblyInformationProvider private
The IAssemblyInformationProvider for the SwarmService.
Definition at line 74 of file SwarmService.cs.
Referenced by Tgstation.Server.Host.Swarm.SwarmService.Shutdown(), and Tgstation.Server.Host.Swarm.SwarmService.SwarmService().
asyncDelayer
readonly IAsyncDelayer Tgstation.Server.Host.Swarm.SwarmService.asyncDelayer private
The IAsyncDelayer for the SwarmService.
Definition at line 84 of file SwarmService.cs.
Referenced by Tgstation.Server.Host.Swarm.SwarmService.CommitUpdate(), and Tgstation.Server.Host.Swarm.SwarmService.SwarmService().
controllerRegistration
Guid? Tgstation.Server.Host.Swarm.SwarmService.controllerRegistration private
The registration Guid provided by the swarm controller.
Definition at line 149 of file SwarmService.cs.
Referenced by Tgstation.Server.Host.Swarm.SwarmService.Shutdown(), Tgstation.Server.Host.Swarm.SwarmService.UnregisterNode(), and Tgstation.Server.Host.Swarm.SwarmService.ValidateRegistration().
databaseContextFactory
readonly IDatabaseContextFactory Tgstation.Server.Host.Swarm.SwarmService.databaseContextFactory private
The IDatabaseContextFactory for the SwarmService.
Definition at line 64 of file SwarmService.cs.
Referenced by Tgstation.Server.Host.Swarm.SwarmService.Initialize(), Tgstation.Server.Host.Swarm.SwarmService.Shutdown(), and Tgstation.Server.Host.Swarm.SwarmService.SwarmService().
databaseSeeder
readonly IDatabaseSeeder Tgstation.Server.Host.Swarm.SwarmService.databaseSeeder private
The IDatabaseSeeder for the SwarmService.
Definition at line 69 of file SwarmService.cs.
Referenced by Tgstation.Server.Host.Swarm.SwarmService.Initialize(), Tgstation.Server.Host.Swarm.SwarmService.Shutdown(), and Tgstation.Server.Host.Swarm.SwarmService.SwarmService().
forceHealthCheckTcs
volatile? TaskCompletionSource Tgstation.Server.Host.Swarm.SwarmService.forceHealthCheckTcs private
A TaskCompletionSource that is used to force a health check.
Definition at line 139 of file SwarmService.cs.
Referenced by Tgstation.Server.Host.Swarm.SwarmService.SwarmService().
httpClientFactory
readonly IAbstractHttpClientFactory Tgstation.Server.Host.Swarm.SwarmService.httpClientFactory private
The IAbstractHttpClientFactory for the SwarmService.
Definition at line 79 of file SwarmService.cs.
Referenced by Tgstation.Server.Host.Swarm.SwarmService.CommitUpdate(), Tgstation.Server.Host.Swarm.SwarmService.ControllerDistributedPrepareUpdate(), Tgstation.Server.Host.Swarm.SwarmService.CreateUpdateStreamProvider(), Tgstation.Server.Host.Swarm.SwarmService.PrepareUpdateImpl(), Tgstation.Server.Host.Swarm.SwarmService.RemoteAbortUpdate(), Tgstation.Server.Host.Swarm.SwarmService.Shutdown(), and Tgstation.Server.Host.Swarm.SwarmService.SwarmService().
lastControllerHealthCheck
DateTimeOffset? Tgstation.Server.Host.Swarm.SwarmService.lastControllerHealthCheck private
The last DateTimeOffset when the controller checked on this node.
Definition at line 154 of file SwarmService.cs.
Referenced by Tgstation.Server.Host.Swarm.SwarmService.ValidateRegistration().
logger
readonly ILogger<SwarmService> Tgstation.Server.Host.Swarm.SwarmService.logger private
The ILogger for the SwarmService.
Definition at line 104 of file SwarmService.cs.
Referenced by Tgstation.Server.Host.Swarm.SwarmService.AbortUpdate(), Tgstation.Server.Host.Swarm.SwarmService.CommitUpdate(), Tgstation.Server.Host.Swarm.SwarmService.ControllerDistributedPrepareUpdate(), Tgstation.Server.Host.Swarm.SwarmService.Initialize(), Tgstation.Server.Host.Swarm.SwarmService.PrepareUpdate(), Tgstation.Server.Host.Swarm.SwarmService.PrepareUpdateFromController(), Tgstation.Server.Host.Swarm.SwarmService.PrepareUpdateImpl(), Tgstation.Server.Host.Swarm.SwarmService.RegisterNode(), Tgstation.Server.Host.Swarm.SwarmService.RemoteAbortUpdate(), Tgstation.Server.Host.Swarm.SwarmService.RemoteCommitReceived(), Tgstation.Server.Host.Swarm.SwarmService.Shutdown(), Tgstation.Server.Host.Swarm.SwarmService.SwarmService(), Tgstation.Server.Host.Swarm.SwarmService.UnregisterNode(), and Tgstation.Server.Host.Swarm.SwarmService.UpdateSwarmServersList().
registrationIdsAndTimes
readonly? Dictionary<string, (Guid RegistrationId, DateTimeOffset RegisteredAt)> Tgstation.Server.Host.Swarm.SwarmService.registrationIdsAndTimes private
Dictionary<TKey, TValue> of SwarmServer.Identifiers to registration Guids and when they were created.
Definition at line 124 of file SwarmService.cs.
Referenced by Tgstation.Server.Host.Swarm.SwarmService.RegisterNode(), Tgstation.Server.Host.Swarm.SwarmService.Shutdown(), Tgstation.Server.Host.Swarm.SwarmService.SwarmService(), Tgstation.Server.Host.Swarm.SwarmService.UnregisterNode(), and Tgstation.Server.Host.Swarm.SwarmService.ValidateRegistration().
serverHealthCheckCancellationTokenSource
readonly? CancellationTokenSource Tgstation.Server.Host.Swarm.SwarmService.serverHealthCheckCancellationTokenSource private
The CancellationTokenSource for serverHealthCheckTask.
Definition at line 114 of file SwarmService.cs.
Referenced by Tgstation.Server.Host.Swarm.SwarmService.Initialize(), Tgstation.Server.Host.Swarm.SwarmService.Shutdown(), and Tgstation.Server.Host.Swarm.SwarmService.SwarmService().
serverHealthCheckTask
Task? Tgstation.Server.Host.Swarm.SwarmService.serverHealthCheckTask private
The Task for the HealthCheckLoop(CancellationToken).
Definition at line 144 of file SwarmService.cs.
Referenced by Tgstation.Server.Host.Swarm.SwarmService.Initialize(), and Tgstation.Server.Host.Swarm.SwarmService.Shutdown().
serversDirty
bool Tgstation.Server.Host.Swarm.SwarmService.serversDirty private
If the swarmServers list has been updated and needs to be resent to clients.
Definition at line 159 of file SwarmService.cs.
serverUpdater
readonly IServerUpdater Tgstation.Server.Host.Swarm.SwarmService.serverUpdater private
The IServerUpdater for the SwarmService.
Definition at line 89 of file SwarmService.cs.
Referenced by Tgstation.Server.Host.Swarm.SwarmService.PrepareUpdateImpl(), and Tgstation.Server.Host.Swarm.SwarmService.SwarmService().
swarmConfiguration
readonly SwarmConfiguration Tgstation.Server.Host.Swarm.SwarmService.swarmConfiguration private
The SwarmConfiguration for the SwarmService.
Definition at line 109 of file SwarmService.cs.
Referenced by Tgstation.Server.Host.Swarm.SwarmService.ControllerDistributedPrepareUpdate(), Tgstation.Server.Host.Swarm.SwarmService.Initialize(), Tgstation.Server.Host.Swarm.SwarmService.PrepareUpdateImpl(), Tgstation.Server.Host.Swarm.SwarmService.RemoteAbortUpdate(), and Tgstation.Server.Host.Swarm.SwarmService.SwarmService().
swarmController
readonly bool Tgstation.Server.Host.Swarm.SwarmService.swarmController private
If the current server is the swarm controller.
Definition at line 129 of file SwarmService.cs.
Referenced by Tgstation.Server.Host.Swarm.SwarmService.CommitUpdate(), Tgstation.Server.Host.Swarm.SwarmService.Initialize(), Tgstation.Server.Host.Swarm.SwarmService.PrepareUpdateFromController(), Tgstation.Server.Host.Swarm.SwarmService.PrepareUpdateImpl(), Tgstation.Server.Host.Swarm.SwarmService.RegisterNode(), Tgstation.Server.Host.Swarm.SwarmService.RemoteAbortUpdate(), Tgstation.Server.Host.Swarm.SwarmService.RemoteCommitReceived(), Tgstation.Server.Host.Swarm.SwarmService.Shutdown(), Tgstation.Server.Host.Swarm.SwarmService.SwarmService(), Tgstation.Server.Host.Swarm.SwarmService.UnregisterNode(), Tgstation.Server.Host.Swarm.SwarmService.UpdateSwarmServersList(), and Tgstation.Server.Host.Swarm.SwarmService.ValidateRegistration().
swarmServers
readonly? List<SwarmServerInformation> Tgstation.Server.Host.Swarm.SwarmService.swarmServers private
List<T> of connected SwarmServerInformations.
Definition at line 119 of file SwarmService.cs.
Referenced by Tgstation.Server.Host.Swarm.SwarmService.CommitUpdate(), Tgstation.Server.Host.Swarm.SwarmService.GetSwarmServers(), Tgstation.Server.Host.Swarm.SwarmService.PrepareUpdateImpl(), Tgstation.Server.Host.Swarm.SwarmService.RegisterNode(), Tgstation.Server.Host.Swarm.SwarmService.RemoteAbortUpdate(), Tgstation.Server.Host.Swarm.SwarmService.Shutdown(), Tgstation.Server.Host.Swarm.SwarmService.SwarmService(), Tgstation.Server.Host.Swarm.SwarmService.UnregisterNode(), Tgstation.Server.Host.Swarm.SwarmService.UpdateSwarmServersList(), and Tgstation.Server.Host.Swarm.SwarmService.ValidateRegistration().
tokenFactory
readonly ITokenFactory Tgstation.Server.Host.Swarm.SwarmService.tokenFactory private
The ITokenFactory for the SwarmService.
Definition at line 99 of file SwarmService.cs.
Referenced by Tgstation.Server.Host.Swarm.SwarmService.RegisterNode(), and Tgstation.Server.Host.Swarm.SwarmService.SwarmService().
transferService
readonly IFileTransferTicketProvider Tgstation.Server.Host.Swarm.SwarmService.transferService private
The IFileTransferTicketProvider for the SwarmService.
Definition at line 94 of file SwarmService.cs.
Referenced by Tgstation.Server.Host.Swarm.SwarmService.SwarmService().
updateOperation
volatile? SwarmUpdateOperation Tgstation.Server.Host.Swarm.SwarmService.updateOperation private
A SwarmUpdateOperation that is currently in progress.
Definition at line 134 of file SwarmService.cs.
Referenced by Tgstation.Server.Host.Swarm.SwarmService.AbortUpdate(), Tgstation.Server.Host.Swarm.SwarmService.CommitUpdate(), Tgstation.Server.Host.Swarm.SwarmService.ControllerDistributedPrepareUpdate(), Tgstation.Server.Host.Swarm.SwarmService.PrepareUpdateImpl(), Tgstation.Server.Host.Swarm.SwarmService.RemoteCommitReceived(), and Tgstation.Server.Host.Swarm.SwarmService.Shutdown().
Property Documentation
ExpectedNumberOfNodesConnected
bool Tgstation.Server.Host.Swarm.SwarmService.ExpectedNumberOfNodesConnected get
Gets a value indicating if the expected amount of nodes are connected to the swarm.
Implements Tgstation.Server.Host.Swarm.ISwarmService.
Definition at line 43 of file SwarmService.cs.
        {
            get
            {
                if (!SwarmMode)
                    return true;
                lock (swarmServers)
                    return swarmServers.Count - 1 >= swarmConfiguration.UpdateRequiredNodeCount;
            }
        }
SwarmMode
bool Tgstation.Server.Host.Swarm.SwarmService.SwarmMode get private
If the swarm system is enabled.
Definition at line 59 of file SwarmService.cs.
Referenced by Tgstation.Server.Host.Swarm.SwarmService.AbortUpdate(), Tgstation.Server.Host.Swarm.SwarmService.CommitUpdate(), Tgstation.Server.Host.Swarm.SwarmService.GetSwarmServers(), Tgstation.Server.Host.Swarm.SwarmService.Initialize(), Tgstation.Server.Host.Swarm.SwarmService.PrepareUpdateImpl(), Tgstation.Server.Host.Swarm.SwarmService.RegisterNode(), Tgstation.Server.Host.Swarm.SwarmService.Shutdown(), Tgstation.Server.Host.Swarm.SwarmService.SwarmService(), Tgstation.Server.Host.Swarm.SwarmService.UnregisterNode(), Tgstation.Server.Host.Swarm.SwarmService.UpdateSwarmServersList(), and Tgstation.Server.Host.Swarm.SwarmService.ValidateRegistration().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Swarm/SwarmService.cs