tgstation-server: Tgstation.Server.Host.Components.Byond.PosixByondInstaller Class Reference
Tgstation.Server.Host.Components.Byond.PosixByondInstaller Class Reference
IByondInstaller for Posix systems.
Public Member Functions
PosixByondInstaller (IPostWriteHandler postWriteHandler, IIOManager ioManager, ILogger< PosixByondInstaller > logger)
Initializes a new instance of the PosixByondInstaller class.
override string GetDreamDaemonName (Version version, out bool supportsCli)
Get the file name of the DreamDaemon executable.
Parameters
version The Version of BYOND to select the executable name for.
supportsCli Whether or not the returned path supports being run as a command-line application.
Returns
The file name of the DreamDaemon executable.
override Task InstallByond (Version version, string path, CancellationToken cancellationToken)
Does actions necessary to get an extracted BYOND installation working.
Parameters
version The Version of BYOND being installed.
path The path to the BYOND installation.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
override Task UpgradeInstallation (Version version, string path, CancellationToken cancellationToken)
Does actions necessary to get upgrade a BYOND version installed by a previous version of TGS.
Parameters
version The Version of BYOND being installed.
path The path to the BYOND installation.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Public Member Functions inherited from Tgstation.Server.Host.Components.Byond.ByondInstallerBase
abstract string GetDreamDaemonName (Version version, out bool supportsCli)
Get the file name of the DreamDaemon executable.
Parameters
version The Version of BYOND to select the executable name for.
supportsCli Whether or not the returned path supports being run as a command-line application.
Returns
The file name of the DreamDaemon executable.
async Task CleanCache (CancellationToken cancellationToken)
Attempts to cleans the BYOND cache folder for the system.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
abstract Task InstallByond (Version version, string path, CancellationToken cancellationToken)
Does actions necessary to get an extracted BYOND installation working.
Parameters
version The Version of BYOND being installed.
path The path to the BYOND installation.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
abstract Task UpgradeInstallation (Version version, string path, CancellationToken cancellationToken)
Does actions necessary to get upgrade a BYOND version installed by a previous version of TGS.
Parameters
version The Version of BYOND being installed.
path The path to the BYOND installation.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Task< MemoryStream > DownloadVersion (Version version, CancellationToken cancellationToken)
Download a given BYOND version .
Parameters
version The Version of BYOND to download.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in a MemoryStream of the zipfile.
string GetDreamDaemonName (Version version, out bool supportsCli)
Get the file name of the DreamDaemon executable.
Task< MemoryStream > DownloadVersion (Version version, CancellationToken cancellationToken)
Download a given BYOND version .
Task InstallByond (Version version, string path, CancellationToken cancellationToken)
Does actions necessary to get an extracted BYOND installation working.
Task UpgradeInstallation (Version version, string path, CancellationToken cancellationToken)
Does actions necessary to get upgrade a BYOND version installed by a previous version of TGS.
Task CleanCache (CancellationToken cancellationToken)
Attempts to cleans the BYOND cache folder for the system.
Properties
override string DreamMakerName [get]
Get the file name of the DreamMaker executable.
override string PathToUserByondFolder [get]
The path to the BYOND folder for the user.
override string ByondRevisionsUrlTemplate [get]
Properties inherited from Tgstation.Server.Host.Components.Byond.ByondInstallerBase
abstract string DreamMakerName [get]
Get the file name of the DreamMaker executable.
abstract string PathToUserByondFolder [get]
The path to the BYOND folder for the user.
abstract string ByondRevisionsUrlTemplate [get]
Gets the URL formatter string for downloading a byond version of {0:Major} {1:Minor}.
IIOManager IOManager [get]
Gets the IIOManager for the ByondInstallerBase.
ILogger< ByondInstallerBase > Logger [get]
Gets the ILogger for the ByondInstallerBase.
Properties inherited from Tgstation.Server.Host.Components.Byond.IByondInstaller
string DreamMakerName [get]
Get the file name of the DreamMaker executable.
string PathToUserByondFolder [get]
The path to the BYOND folder for the user.
Private Attributes
readonly IPostWriteHandler postWriteHandler
The IPostWriteHandler for the PosixByondInstaller.
Static Private Attributes
const string DreamDaemonExecutableName = "DreamDaemon"
The name of the DreamDaemon binary file.
const string DreamMakerExecutableName = "DreamMaker"
The name of the DreamMaker binary file.
const string ShellScriptExtension = ".sh"
File extension for shell scripts.
Additional Inherited Members
Protected Member Functions inherited from Tgstation.Server.Host.Components.Byond.ByondInstallerBase
ByondInstallerBase (IIOManager ioManager, ILogger< ByondInstallerBase > logger)
Initializes a new instance of the ByondInstallerBase class.
Detailed Description
IByondInstaller for Posix systems.
Definition at line 16 of file PosixByondInstaller.cs.
Constructor & Destructor Documentation
PosixByondInstaller()
Tgstation.Server.Host.Components.Byond.PosixByondInstaller.PosixByondInstaller (IPostWriteHandler postWriteHandler, IIOManager ioManager, ILogger< PosixByondInstaller > logger)
Initializes a new instance of the PosixByondInstaller class.
Parameters
postWriteHandler The value of postWriteHandler.
ioManager The IIOManager for the ByondInstallerBase.
logger The ILogger for the ByondInstallerBase.
Definition at line 53 of file PosixByondInstaller.cs.
            : base(ioManager, logger)
        {
            this.postWriteHandler = postWriteHandler ?? throw new ArgumentNullException(nameof(postWriteHandler));
            PathToUserByondFolder = IOManager.ResolvePath(
                IOManager.ConcatPath(
                    Environment.GetFolderPath(
                        Environment.SpecialFolder.UserProfile),
                    "./byond/cache"));
        }
References Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.Components.Byond.ByondInstallerBase.IOManager, Tgstation.Server.Host.Components.Byond.PosixByondInstaller.PathToUserByondFolder, Tgstation.Server.Host.Components.Byond.PosixByondInstaller.postWriteHandler, and Tgstation.Server.Host.IO.IIOManager.ResolvePath().
Member Function Documentation
GetDreamDaemonName()
override string Tgstation.Server.Host.Components.Byond.PosixByondInstaller.GetDreamDaemonName (Version version, out bool supportsCli) virtual
Get the file name of the DreamDaemon executable.
Parameters
version The Version of BYOND to select the executable name for.
supportsCli Whether or not the returned path supports being run as a command-line application.
Returns
The file name of the DreamDaemon executable.
Implements Tgstation.Server.Host.Components.Byond.ByondInstallerBase.
Definition at line 66 of file PosixByondInstaller.cs.
        {
            if (version == null)
                throw new ArgumentNullException(nameof(version));
            supportsCli = true;
            return DreamDaemonExecutableName + ShellScriptExtension;
        }
References Tgstation.Server.Host.Components.Byond.PosixByondInstaller.DreamDaemonExecutableName, and Tgstation.Server.Host.Components.Byond.PosixByondInstaller.ShellScriptExtension.
Referenced by Tgstation.Server.Host.Components.Byond.PosixByondInstaller.InstallByond().
InstallByond()
override Task Tgstation.Server.Host.Components.Byond.PosixByondInstaller.InstallByond (Version version, string path, CancellationToken cancellationToken) virtual
Does actions necessary to get an extracted BYOND installation working.
Parameters
version The Version of BYOND being installed.
path The path to the BYOND installation.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implements Tgstation.Server.Host.Components.Byond.ByondInstallerBase.
Definition at line 76 of file PosixByondInstaller.cs.
        {
            if (version == null)
                throw new ArgumentNullException(nameof(version));
            if (path == null)
                throw new ArgumentNullException(nameof(path));
            // write the scripts for running the ting
            // need to add $ORIGIN to LD_LIBRARY_PATH
            const string StandardScript = "#!/bin/sh\nexport LD_LIBRARY_PATH=\"\\$ORIGIN:$LD_LIBRARY_PATH\"\nBASEDIR=$(dirname \"$0\")\nexec \"$BASEDIR/{0}\" \"$@\"\n";
            var dreamDaemonScript = String.Format(CultureInfo.InvariantCulture, StandardScript, DreamDaemonExecutableName);
            var dreamMakerScript = String.Format(CultureInfo.InvariantCulture, StandardScript, DreamMakerExecutableName);
            async Task WriteAndMakeExecutable(string pathToScript, string script)
            {
                Logger.LogTrace("Writing script {0}:{1}{2}", pathToScript, Environment.NewLine, script);
                await IOManager.WriteAllBytes(pathToScript, Encoding.ASCII.GetBytes(script), cancellationToken);
                postWriteHandler.HandleWrite(IOManager.ResolvePath(pathToScript));
            }
            var basePath = IOManager.ConcatPath(path, ByondManager.BinPath);
            var task = Task.WhenAll(
                WriteAndMakeExecutable(
                    IOManager.ConcatPath(basePath, GetDreamDaemonName(version, out var _)),
                    dreamDaemonScript),
                WriteAndMakeExecutable(
                    IOManager.ConcatPath(basePath, DreamMakerName),
                    dreamMakerScript));
            postWriteHandler.HandleWrite(IOManager.ConcatPath(basePath, DreamDaemonExecutableName));
            postWriteHandler.HandleWrite(IOManager.ConcatPath(basePath, DreamMakerExecutableName));
            return task;
        }
References Tgstation.Server.Host.Components.Byond.ByondManager.BinPath, Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.Components.Byond.PosixByondInstaller.DreamDaemonExecutableName, Tgstation.Server.Host.Components.Byond.PosixByondInstaller.DreamMakerExecutableName, Tgstation.Server.Host.Components.Byond.PosixByondInstaller.DreamMakerName, Tgstation.Server.Host.Components.Byond.PosixByondInstaller.GetDreamDaemonName(), Tgstation.Server.Host.IO.IPostWriteHandler.HandleWrite(), Tgstation.Server.Host.Components.Byond.ByondInstallerBase.IOManager, Tgstation.Server.Host.Components.Byond.ByondInstallerBase.Logger, Tgstation.Server.Host.Components.Byond.PosixByondInstaller.postWriteHandler, Tgstation.Server.Host.IO.IIOManager.ResolvePath(), and Tgstation.Server.Host.IO.IIOManager.WriteAllBytes().
UpgradeInstallation()
override Task Tgstation.Server.Host.Components.Byond.PosixByondInstaller.UpgradeInstallation (Version version, string path, CancellationToken cancellationToken) virtual
Does actions necessary to get upgrade a BYOND version installed by a previous version of TGS.
Parameters
version The Version of BYOND being installed.
path The path to the BYOND installation.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implements Tgstation.Server.Host.Components.Byond.ByondInstallerBase.
Definition at line 114 of file PosixByondInstaller.cs.
        {
            if (version == null)
                throw new ArgumentNullException(nameof(version));
            if (path == null)
                throw new ArgumentNullException(nameof(path));
            return Task.CompletedTask;
        }
Member Data Documentation
DreamDaemonExecutableName
const string Tgstation.Server.Host.Components.Byond.PosixByondInstaller.DreamDaemonExecutableName = "DreamDaemon" static private
The name of the DreamDaemon binary file.
Definition at line 21 of file PosixByondInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Byond.PosixByondInstaller.GetDreamDaemonName(), and Tgstation.Server.Host.Components.Byond.PosixByondInstaller.InstallByond().
DreamMakerExecutableName
const string Tgstation.Server.Host.Components.Byond.PosixByondInstaller.DreamMakerExecutableName = "DreamMaker" static private
The name of the DreamMaker binary file.
Definition at line 26 of file PosixByondInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Byond.PosixByondInstaller.InstallByond().
postWriteHandler
readonly IPostWriteHandler Tgstation.Server.Host.Components.Byond.PosixByondInstaller.postWriteHandler private
The IPostWriteHandler for the PosixByondInstaller.
Definition at line 45 of file PosixByondInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Byond.PosixByondInstaller.InstallByond(), and Tgstation.Server.Host.Components.Byond.PosixByondInstaller.PosixByondInstaller().
ShellScriptExtension
const string Tgstation.Server.Host.Components.Byond.PosixByondInstaller.ShellScriptExtension = ".sh" static private
File extension for shell scripts.
Definition at line 31 of file PosixByondInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Byond.PosixByondInstaller.GetDreamDaemonName().
Property Documentation
ByondRevisionsUrlTemplate
override string Tgstation.Server.Host.Components.Byond.PosixByondInstaller.ByondRevisionsUrlTemplate get protected
Definition at line 40 of file PosixByondInstaller.cs.
DreamMakerName
override string Tgstation.Server.Host.Components.Byond.PosixByondInstaller.DreamMakerName get
Get the file name of the DreamMaker executable.
Implements Tgstation.Server.Host.Components.Byond.IByondInstaller.
Definition at line 34 of file PosixByondInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Byond.PosixByondInstaller.InstallByond().
PathToUserByondFolder
override string Tgstation.Server.Host.Components.Byond.PosixByondInstaller.PathToUserByondFolder get
The path to the BYOND folder for the user.
Implements Tgstation.Server.Host.Components.Byond.IByondInstaller.
Definition at line 37 of file PosixByondInstaller.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Byond.PosixByondInstaller.PosixByondInstaller().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Byond/PosixByondInstaller.cs