tgstation-server: Tgstation.Server.Client.AdministrationClient Class Reference
Tgstation.Server.Client.AdministrationClient Class Reference
Public Member Functions
AdministrationClient (IApiClient apiClient)
Initializes a new instance of the AdministrationClient class.
Task< AdministrationResponse > Read (CancellationToken cancellationToken)
Get the AdministrationResponse represented by the IAdministrationClient.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the AdministrationResponse represented by the IAdministrationClient.
async Task< ServerUpdateResponse > Update (ServerUpdateRequest updateRequest, Stream? zipFileStream, CancellationToken cancellationToken)
Updates the AdministrationResponse setttings.
Parameters
updateRequest The ServerUpdateRequest.
zipFileStream The Stream for the .zip file if ServerUpdateRequest.UploadZip is true. Will be ignored if it is false.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the echoed ServerUpdateResponse.
Task Restart (CancellationToken cancellationToken)
Restarts the TGS server.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Task< IReadOnlyList< LogFileResponse > > ListLogs (PaginationSettings? paginationSettings, CancellationToken cancellationToken)
Lists the log files available for download.
Parameters
paginationSettings The optional PaginationSettings for the operation.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in an IReadOnlyList<T> of LogFileResponse metadata.
async Task< Tuple< LogFileResponse, Stream > > GetLog (LogFileResponse logFile, CancellationToken cancellationToken)
Download a given logFile .
Parameters
logFile The LogFileResponse to download.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting a Tuple<T1, T2> containing the downloaded LogFileResponse and associated Stream.
Public Member Functions inherited from Tgstation.Server.Client.PaginatedClient
PaginatedClient (IApiClient apiClient)
Initializes a new instance of the PaginatedClient class.
Task< AdministrationResponse > Read (CancellationToken cancellationToken)
Get the AdministrationResponse represented by the IAdministrationClient.
Task< ServerUpdateResponse > Update (ServerUpdateRequest updateRequest, Stream? zipFileStream, CancellationToken cancellationToken)
Updates the AdministrationResponse setttings.
Task Restart (CancellationToken cancellationToken)
Restarts the TGS server.
Task< IReadOnlyList< LogFileResponse > > ListLogs (PaginationSettings? paginationSettings, CancellationToken cancellationToken)
Lists the log files available for download.
Task< Tuple< LogFileResponse, Stream > > GetLog (LogFileResponse logFile, CancellationToken cancellationToken)
Download a given logFile .
Additional Inherited Members
Protected Member Functions inherited from Tgstation.Server.Client.PaginatedClient
async Task< IReadOnlyList< TModel > > ReadPaged< TModel > (PaginationSettings? paginationSettings, string route, long? instanceId, CancellationToken cancellationToken)
Reads a given route with paged results.
Properties inherited from Tgstation.Server.Client.PaginatedClient
IApiClient ApiClient [get]
The IApiClient for the PaginatedClient.
Detailed Description
Definition at line 15 of file AdministrationClient.cs.
Constructor & Destructor Documentation
AdministrationClient()
Tgstation.Server.Client.AdministrationClient.AdministrationClient (IApiClient apiClient)
Initializes a new instance of the AdministrationClient class.
Parameters
apiClient The IApiClient for the PaginatedClient.
Definition at line 21 of file AdministrationClient.cs.
            : base(apiClient)
        {
        }
Member Function Documentation
GetLog()
async Task< Tuple< LogFileResponse, Stream > > Tgstation.Server.Client.AdministrationClient.GetLog (LogFileResponse logFile, CancellationToken cancellationToken)
Download a given logFile .
Parameters
logFile The LogFileResponse to download.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting a Tuple<T1, T2> containing the downloaded LogFileResponse and associated Stream.
Implements Tgstation.Server.Client.IAdministrationClient.
Definition at line 60 of file AdministrationClient.cs.
        {
            var resultFile = await ApiClient.Read<LogFileResponse>(
                Routes.Logs + Routes.SanitizeGetPath(
                    HttpUtility.UrlEncode(
                        logFile?.Name ?? throw new ArgumentNullException(nameof(logFile)))),
                cancellationToken)
                .ConfigureAwait(false);
            var stream = await ApiClient.Download(resultFile, cancellationToken).ConfigureAwait(false);
            try
            {
                return Tuple.Create(resultFile, stream);
            }
            catch
            {
                stream.Dispose();
                throw;
            }
        }
References Tgstation.Server.Client.ApiClient.Download(), Tgstation.Server.Api.Models.Response.LogFileResponse.Name, and Tgstation.Server.Api.Routes.SanitizeGetPath().
ListLogs()
Task< IReadOnlyList< LogFileResponse > > Tgstation.Server.Client.AdministrationClient.ListLogs (PaginationSettings? paginationSettings, CancellationToken cancellationToken)
Lists the log files available for download.
Parameters
paginationSettings The optional PaginationSettings for the operation.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in an IReadOnlyList<T> of LogFileResponse metadata.
Implements Tgstation.Server.Client.IAdministrationClient.
Read()
Task< AdministrationResponse > Tgstation.Server.Client.AdministrationClient.Read (CancellationToken cancellationToken)
Get the AdministrationResponse represented by the IAdministrationClient.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the AdministrationResponse represented by the IAdministrationClient.
Implements Tgstation.Server.Client.IAdministrationClient.
Restart()
Task Tgstation.Server.Client.AdministrationClient.Restart (CancellationToken cancellationToken)
Restarts the TGS server.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implements Tgstation.Server.Client.IAdministrationClient.
Update()
async Task< ServerUpdateResponse > Tgstation.Server.Client.AdministrationClient.Update (ServerUpdateRequest updateRequest, Stream? zipFileStream, CancellationToken cancellationToken)
Updates the AdministrationResponse setttings.
Parameters
updateRequest The ServerUpdateRequest.
zipFileStream The Stream for the .zip file if ServerUpdateRequest.UploadZip is true. Will be ignored if it is false.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the echoed ServerUpdateResponse.
Implements Tgstation.Server.Client.IAdministrationClient.
Definition at line 30 of file AdministrationClient.cs.
        {
            if (updateRequest == null)
                throw new ArgumentNullException(nameof(updateRequest));
            if (updateRequest.UploadZip == true && zipFileStream == null)
                throw new ArgumentNullException(nameof(zipFileStream));
            var result = await ApiClient.Update<ServerUpdateRequest, ServerUpdateResponse>(
                Routes.Administration,
                updateRequest,
                cancellationToken);
            if (updateRequest.UploadZip == true)
                await ApiClient.Upload(result, zipFileStream, cancellationToken).ConfigureAwait(false);
            return result;
        }
References Tgstation.Server.Api.Routes.Administration, Tgstation.Server.Client.ApiClient.Upload(), and Tgstation.Server.Api.Models.Request.ServerUpdateRequest.UploadZip.
The documentation for this class was generated from the following file:
src/Tgstation.Server.Client/AdministrationClient.cs