tgstation-server: Tgstation.Server.Client.GraphQL.GraphQLServerClient Class Reference
Tgstation.Server.Client.GraphQL.GraphQLServerClient Class Reference
Public Member Functions
GraphQLServerClient (IGraphQLClient graphQLClient, IAsyncDisposable serviceProvider, ILogger< GraphQLServerClient > logger)
Initializes a new instance of the GraphQLServerClient class.
virtual ValueTask DisposeAsync ()
ValueTask< IOperationResult< TResultData > > RunOperationAsync< TResultData > (Func< IGraphQLClient, ValueTask< IOperationResult< TResultData > > > operationExecutor, CancellationToken cancellationToken)
Runs a given operationExecutor . It may be invoked multiple times depending on the behavior of the IGraphQLServerClient if reauthentication is required.
Template Parameters
TResultData The Type of the IOperationResult<TResultData>'s IOperationResult<TResultData>.Data.
Parameters
operationExecutor A Func<T, TResult> which executes a single query on a given IGraphQLClient and returns a ValueTask<TResult> resulting in the TResultData IOperationResult<TResultData>.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IOperationResult<TResultData>.
Exceptions
AuthenticationException Thrown when automatic reauthentication fails.
ValueTask< IOperationResult< TResultData > > RunOperation< TResultData > (Func< IGraphQLClient, Task< IOperationResult< TResultData > > > operationExecutor, CancellationToken cancellationToken)
Runs a given operationExecutor . It may be invoked multiple times depending on the behavior of the IGraphQLServerClient if reauthentication is required.
Template Parameters
TResultData The Type of the IOperationResult<TResultData>'s IOperationResult<TResultData>.Data.
Parameters
operationExecutor A Func<T, TResult> which executes a single query on a given IGraphQLClient and returns a ValueTask<TResult> resulting in the TResultData IOperationResult<TResultData>.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IOperationResult<TResultData>.
Exceptions
AuthenticationException Thrown when automatic reauthentication fails.
async ValueTask< IDisposable > Subscribe< TResultData > (Func< IGraphQLClient, IObservable< IOperationResult< TResultData > > > operationExecutor, IObserver< IOperationResult< TResultData > > observer, CancellationToken cancellationToken)
Subcribes to the GraphQL subscription indicated by operationExecutor .
Template Parameters
TResultData The Type of the IOperationResult<TResultData>'s IOperationResult<TResultData>.Data.
Parameters
operationExecutor A Func<T, TResult> which initiates a single subscription on a given IGraphQLClient and returns a ValueTask<TResult> resulting in the TResultData IOperationResult<TResultData> IObservable<T>.
observer The IObserver<T> for TResultData IOperationResult<TResultData>s.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IDisposable representing the lifetime of the subscription.
Protected Member Functions
GraphQLServerClient (IGraphQLClient graphQLClient, IAsyncDisposable serviceProvider, ILogger< GraphQLServerClient > logger, Action< AuthenticationHeaderValue > setAuthenticationHeader, AuthenticationHeaderValue? basicCredentialsHeader, IOperationResult< ILoginResult > loginResult)
Initializes a new instance of the GraphQLServerClient class.
virtual ValueTask< AuthenticationHeaderValue > CreateUpdatedAuthenticationHeader (string bearer)
Create a AuthenticationHeaderValue from a given bearer token.
Properties
bool Authenticated [get]
If the GraphQLServerClient was initially authenticated.
bool CanReauthenticate [get]
If the GraphQLServerClient supports reauthentication.
Private Member Functions
async ValueTask< IOperationResult< TResultData > > WrapAuthentication< TResultData > (Func< IGraphQLClient, ValueTask< IOperationResult< TResultData > > > operationExecutor, CancellationToken cancellationToken)
Executes a given operationExecutor , potentially accounting for authentication issues.
async ValueTask< AuthenticationHeaderValue > Reauthenticate (AuthenticationHeaderValue currentToken, CancellationToken cancellationToken)
Attempt to reauthenticate.
async ValueTask<(AuthenticationHeaderValue Header, DateTime Exp)> CreateCredentialsTuple (IOperationResult< ILoginResult > loginResult)
Attempt to create the ValueTuple<T1, T2> for bearerCredentialsTask.
Static Private Member Functions
static void ThrowOtherCallerFailedAuthException ()
Throws an AuthenticationException for a login error that previously occured outside of the current call context.
Private Attributes
readonly IGraphQLClient graphQLClient
The IGraphQLClient for the GraphQLServerClient.
readonly IAsyncDisposable serviceProvider
The IAsyncDisposable to be DisposeAsync'd with the GraphQLServerClient.
readonly ILogger< GraphQLServerClient > logger
The ILogger for the GraphQLServerClient.
readonly? Action< AuthenticationHeaderValue > setAuthenticationHeader
The Action<T> which sets the AuthenticationHeaderValue for HTTP request in the current async context.
readonly? AuthenticationHeaderValue basicCredentialsHeader
The AuthenticationHeaderValue containing the authenticated user's password credentials.
readonly? object bearerCredentialsHeaderTaskLock
lock object used to synchronize access to bearerCredentialsTask.
Task<(AuthenticationHeaderValue Header, DateTime Exp)?>? bearerCredentialsTask
A Task<TResult> resulting in a ValueTuple<T1, T2> containing the current AuthenticationHeaderValue for the ApiHeaders.BearerAuthenticationScheme and the DateTime it expires.
Detailed Description
Definition at line 16 of file GraphQLServerClient.cs.
Constructor & Destructor Documentation
GraphQLServerClient() [1/2]
Tgstation.Server.Client.GraphQL.GraphQLServerClient.GraphQLServerClient (IGraphQLClient graphQLClient, IAsyncDisposable serviceProvider, ILogger< GraphQLServerClient > logger)
Initializes a new instance of the GraphQLServerClient class.
Parameters
graphQLClient The value of graphQLClient.
serviceProvider The value of serviceProvider.
logger The value of logger.
Definition at line 81 of file GraphQLServerClient.cs.
        {
            this.graphQLClient = graphQLClient ?? throw new ArgumentNullException(nameof(graphQLClient));
            this.serviceProvider = serviceProvider ?? throw new ArgumentNullException(nameof(serviceProvider));
            this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }
References Tgstation.Server.Client.GraphQL.GraphQLServerClient.graphQLClient, Tgstation.Server.Client.GraphQL.GraphQLServerClient.logger, and Tgstation.Server.Client.GraphQL.GraphQLServerClient.serviceProvider.
GraphQLServerClient() [2/2]
Tgstation.Server.Client.GraphQL.GraphQLServerClient.GraphQLServerClient (IGraphQLClient graphQLClient, IAsyncDisposable serviceProvider, ILogger< GraphQLServerClient > logger, Action< AuthenticationHeaderValue > setAuthenticationHeader, AuthenticationHeaderValue? basicCredentialsHeader, IOperationResult< ILoginResult > loginResult) protected
Initializes a new instance of the GraphQLServerClient class.
Parameters
graphQLClient The value of graphQLClient.
serviceProvider The value of serviceProvider.
logger The value of logger.
setAuthenticationHeader The value of setAuthenticationHeader.
basicCredentialsHeader The value of basicCredentialsHeader.
loginResult The ILoginResult IOperationResult<TResultData> containing the initial JWT to use.
Definition at line 100 of file GraphQLServerClient.cs.
            : this(graphQLClient, serviceProvider, logger)
        {
            this.setAuthenticationHeader = setAuthenticationHeader ?? throw new ArgumentNullException(nameof(setAuthenticationHeader));
            ArgumentNullException.ThrowIfNull(loginResult);
            this.basicCredentialsHeader = basicCredentialsHeader;
            var task = CreateCredentialsTuple(loginResult);
            if (!task.IsCompleted)
                throw new InvalidOperationException($"Expected {nameof(CreateCredentialsTuple)} to not await in constructor!");
            bearerCredentialsTask = Task.FromResult<(AuthenticationHeaderValue Header, DateTime Exp)?>(task.Result);
            if (Authenticated)
                bearerCredentialsHeaderTaskLock = new object();
        }
References Tgstation.Server.Client.GraphQL.GraphQLServerClient.Authenticated, Tgstation.Server.Client.GraphQL.GraphQLServerClient.basicCredentialsHeader, Tgstation.Server.Client.GraphQL.GraphQLServerClient.bearerCredentialsHeaderTaskLock, Tgstation.Server.Client.GraphQL.GraphQLServerClient.bearerCredentialsTask, Tgstation.Server.Client.GraphQL.GraphQLServerClient.CreateCredentialsTuple(), and Tgstation.Server.Client.GraphQL.GraphQLServerClient.setAuthenticationHeader.
Member Function Documentation
CreateCredentialsTuple()
async ValueTask<(AuthenticationHeaderValue Header, DateTime Exp)> Tgstation.Server.Client.GraphQL.GraphQLServerClient.CreateCredentialsTuple (IOperationResult< ILoginResult > loginResult) private
Attempt to create the ValueTuple<T1, T2> for bearerCredentialsTask.
Parameters
loginResult The ILoginResult IOperationResult<TResultData> to process.
Returns
A ValueTask<TResult> resulting in a new credentials ValueTuple<T1, T2>.
Exceptions
AuthenticationException Thrown if the loginResult errored.
Definition at line 281 of file GraphQLServerClient.cs.
        {
            var bearer = loginResult.EnsureSuccess(logger);
            var header = await CreateUpdatedAuthenticationHeader(bearer.EncodedToken);
            return (Header: header, Exp: bearer.ValidTo);
        }
References Tgstation.Server.Client.GraphQL.GraphQLServerClient.CreateUpdatedAuthenticationHeader(), and Tgstation.Server.Client.GraphQL.GraphQLServerClient.logger.
Referenced by Tgstation.Server.Client.GraphQL.GraphQLServerClient.GraphQLServerClient(), and Tgstation.Server.Client.GraphQL.GraphQLServerClient.Reauthenticate().
CreateUpdatedAuthenticationHeader()
virtual ValueTask< AuthenticationHeaderValue > Tgstation.Server.Client.GraphQL.GraphQLServerClient.CreateUpdatedAuthenticationHeader (string bearer) protected virtual
Create a AuthenticationHeaderValue from a given bearer token.
Parameters
bearer The ApiHeaders.BearerAuthenticationScheme string.
Returns
A new AuthenticationHeaderValue.
Reimplemented in Tgstation.Server.Client.GraphQL.AuthenticatedGraphQLServerClient.
Referenced by Tgstation.Server.Client.GraphQL.GraphQLServerClient.CreateCredentialsTuple().
DisposeAsync()
virtual ValueTask Tgstation.Server.Client.GraphQL.GraphQLServerClient.DisposeAsync () virtual
Reimplemented in Tgstation.Server.Client.GraphQL.AuthenticatedGraphQLServerClient.
Reauthenticate()
async ValueTask< AuthenticationHeaderValue > Tgstation.Server.Client.GraphQL.GraphQLServerClient.Reauthenticate (AuthenticationHeaderValue currentToken, CancellationToken cancellationToken) private
Attempt to reauthenticate.
Parameters
currentToken The current AuthenticationHeaderValue for the bearer token.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the updated AuthenticationHeaderValue to use.
Definition at line 222 of file GraphQLServerClient.cs.
        {
            if (!CanReauthenticate)
                throw new AuthenticationException("Authentication expired or invalid and cannot re-authenticate.");
            TaskCompletionSource<(AuthenticationHeaderValue Header, DateTime Exp)?>? tcs = null;
            do
            {
                var bearerCredentialsTaskLocal = bearerCredentialsTask;
                if (!bearerCredentialsTaskLocal!.IsCompleted)
                {
                    var currentTuple = await bearerCredentialsTaskLocal.ConfigureAwait(false);
                    if (!currentTuple.HasValue)
                        ThrowOtherCallerFailedAuthException();
                    return currentTuple.Value.Header;
                }
                lock (bearerCredentialsHeaderTaskLock!)
                {
                    if (bearerCredentialsTask == bearerCredentialsTaskLocal)
                    {
                        var result = bearerCredentialsTaskLocal.Result;
                        if (result?.Header != currentToken)
{
                            if (!result.HasValue)
                                ThrowOtherCallerFailedAuthException();
                            return result.Value.Header;
                        }
                        tcs = new TaskCompletionSource<(AuthenticationHeaderValue, DateTime)?>();
                        bearerCredentialsTask = tcs.Task;
                    }
                }
            }
            while (tcs == null);
            setAuthenticationHeader!(basicCredentialsHeader!);
            var loginResult = await graphQLClient.Login.ExecuteAsync(cancellationToken).ConfigureAwait(false);
            try
            {
                var tuple = await CreateCredentialsTuple(loginResult).ConfigureAwait(false);
                tcs.SetResult(tuple);
                return tuple.Header;
            }
            catch (AuthenticationException)
            {
                tcs.SetResult(null);
                throw;
            }
        }
References Tgstation.Server.Client.GraphQL.GraphQLServerClient.basicCredentialsHeader, Tgstation.Server.Client.GraphQL.GraphQLServerClient.bearerCredentialsHeaderTaskLock, Tgstation.Server.Client.GraphQL.GraphQLServerClient.bearerCredentialsTask, Tgstation.Server.Client.GraphQL.GraphQLServerClient.CanReauthenticate, Tgstation.Server.Client.GraphQL.GraphQLServerClient.CreateCredentialsTuple(), Tgstation.Server.Client.GraphQL.GraphQLServerClient.graphQLClient, Tgstation.Server.Client.GraphQL.GraphQLServerClient.setAuthenticationHeader, and Tgstation.Server.Client.GraphQL.GraphQLServerClient.ThrowOtherCallerFailedAuthException().
Referenced by Tgstation.Server.Client.GraphQL.GraphQLServerClient.Subscribe< TResultData >(), and Tgstation.Server.Client.GraphQL.GraphQLServerClient.WrapAuthentication< TResultData >().
RunOperation< TResultData >()
ValueTask< IOperationResult< TResultData > > Tgstation.Server.Client.GraphQL.GraphQLServerClient.RunOperation< TResultData > (Func< IGraphQLClient, Task< IOperationResult< TResultData > > > operationExecutor, CancellationToken cancellationToken)
Runs a given operationExecutor . It may be invoked multiple times depending on the behavior of the IGraphQLServerClient if reauthentication is required.
Template Parameters
TResultData The Type of the IOperationResult<TResultData>'s IOperationResult<TResultData>.Data.
Parameters
operationExecutor A Func<T, TResult> which executes a single query on a given IGraphQLClient and returns a ValueTask<TResult> resulting in the TResultData IOperationResult<TResultData>.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IOperationResult<TResultData>.
Exceptions
AuthenticationException Thrown when automatic reauthentication fails.
Implements Tgstation.Server.Client.GraphQL.IGraphQLServerClient.
Type Constraints
TResultData : class
Definition at line 135 of file GraphQLServerClient.cs.
                              : class
        {
            ArgumentNullException.ThrowIfNull(operationExecutor);
            return WrapAuthentication(async localClient => await operationExecutor(localClient), cancellationToken);
        }
RunOperationAsync< TResultData >()
ValueTask< IOperationResult< TResultData > > Tgstation.Server.Client.GraphQL.GraphQLServerClient.RunOperationAsync< TResultData > (Func< IGraphQLClient, ValueTask< IOperationResult< TResultData > > > operationExecutor, CancellationToken cancellationToken)
Runs a given operationExecutor . It may be invoked multiple times depending on the behavior of the IGraphQLServerClient if reauthentication is required.
Template Parameters
TResultData The Type of the IOperationResult<TResultData>'s IOperationResult<TResultData>.Data.
Parameters
operationExecutor A Func<T, TResult> which executes a single query on a given IGraphQLClient and returns a ValueTask<TResult> resulting in the TResultData IOperationResult<TResultData>.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IOperationResult<TResultData>.
Exceptions
AuthenticationException Thrown when automatic reauthentication fails.
Implements Tgstation.Server.Client.GraphQL.IGraphQLServerClient.
Type Constraints
TResultData : class
Definition at line 127 of file GraphQLServerClient.cs.
                              : class
        {
            ArgumentNullException.ThrowIfNull(operationExecutor);
            return WrapAuthentication(operationExecutor, cancellationToken);
        }
Subscribe< TResultData >()
async ValueTask< IDisposable > Tgstation.Server.Client.GraphQL.GraphQLServerClient.Subscribe< TResultData > (Func< IGraphQLClient, IObservable< IOperationResult< TResultData > > > operationExecutor, IObserver< IOperationResult< TResultData > > observer, CancellationToken cancellationToken)
Subcribes to the GraphQL subscription indicated by operationExecutor .
Template Parameters
TResultData The Type of the IOperationResult<TResultData>'s IOperationResult<TResultData>.Data.
Parameters
operationExecutor A Func<T, TResult> which initiates a single subscription on a given IGraphQLClient and returns a ValueTask<TResult> resulting in the TResultData IOperationResult<TResultData> IObservable<T>.
observer The IObserver<T> for TResultData IOperationResult<TResultData>s.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IDisposable representing the lifetime of the subscription.
Implements Tgstation.Server.Client.GraphQL.IGraphQLServerClient.
Type Constraints
TResultData : class
Definition at line 143 of file GraphQLServerClient.cs.
                              : class
        {
            ArgumentNullException.ThrowIfNull(operationExecutor);
            ArgumentNullException.ThrowIfNull(observer);
            var observable = operationExecutor(graphQLClient);
            if (Authenticated)
            {
                var tuple = await bearerCredentialsTask.ConfigureAwait(false);
                if (!tuple.HasValue)
                    ThrowOtherCallerFailedAuthException();
                var (currentAuthHeader, expires) = tuple.Value;
                if (expires <= DateTimeOffset.UtcNow)
                    currentAuthHeader = await Reauthenticate(currentAuthHeader, cancellationToken).ConfigureAwait(false);
                setAuthenticationHeader(currentAuthHeader);
            }
            // maybe make this handle reauthentication one day
            // but would need to check if lost auth results in complete events being sent
            // if so, it can't be done
            return observable.Subscribe(observer);
        }
References Tgstation.Server.Client.GraphQL.GraphQLServerClient.Authenticated, Tgstation.Server.Client.GraphQL.GraphQLServerClient.bearerCredentialsTask, Tgstation.Server.Client.GraphQL.GraphQLServerClient.graphQLClient, Tgstation.Server.Client.GraphQL.GraphQLServerClient.Reauthenticate(), Tgstation.Server.Client.GraphQL.GraphQLServerClient.setAuthenticationHeader, and Tgstation.Server.Client.GraphQL.GraphQLServerClient.ThrowOtherCallerFailedAuthException().
ThrowOtherCallerFailedAuthException()
static void Tgstation.Server.Client.GraphQL.GraphQLServerClient.ThrowOtherCallerFailedAuthException () static private
Throws an AuthenticationException for a login error that previously occured outside of the current call context.
Exceptions
AuthenticationException Always thrown.
Referenced by Tgstation.Server.Client.GraphQL.GraphQLServerClient.Reauthenticate(), Tgstation.Server.Client.GraphQL.GraphQLServerClient.Subscribe< TResultData >(), and Tgstation.Server.Client.GraphQL.GraphQLServerClient.WrapAuthentication< TResultData >().
WrapAuthentication< TResultData >()
async ValueTask< IOperationResult< TResultData > > Tgstation.Server.Client.GraphQL.GraphQLServerClient.WrapAuthentication< TResultData > (Func< IGraphQLClient, ValueTask< IOperationResult< TResultData > > > operationExecutor, CancellationToken cancellationToken) private
Executes a given operationExecutor , potentially accounting for authentication issues.
Template Parameters
TResultData The Type of the IOperationResult<TResultData>'s IOperationResult<TResultData>.Data.
Parameters
operationExecutor A Func<T, TResult> which executes a single query on a given IGraphQLClient and returns a ValueTask<TResult> resulting in the TResultData IOperationResult<TResultData>.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IOperationResult<TResultData>.
Type Constraints
TResultData : class
Definition at line 188 of file GraphQLServerClient.cs.
                              : class
        {
            if (!Authenticated)
                return await operationExecutor(graphQLClient).ConfigureAwait(false);
            var tuple = await bearerCredentialsTask.ConfigureAwait(false);
            if (!tuple.HasValue)
                ThrowOtherCallerFailedAuthException();
            var (currentAuthHeader, expires) = tuple.Value;
            if (expires <= DateTimeOffset.UtcNow)
                currentAuthHeader = await Reauthenticate(currentAuthHeader, cancellationToken).ConfigureAwait(false);
            setAuthenticationHeader(currentAuthHeader);
            var operationResult = await operationExecutor(graphQLClient);
            if (operationResult.IsAuthenticationError())
            {
                currentAuthHeader = await Reauthenticate(currentAuthHeader, cancellationToken).ConfigureAwait(false);
                setAuthenticationHeader(currentAuthHeader);
                return await operationExecutor(graphQLClient);
            }
            return operationResult;
        }
References Tgstation.Server.Client.GraphQL.GraphQLServerClient.Authenticated, Tgstation.Server.Client.GraphQL.GraphQLServerClient.bearerCredentialsTask, Tgstation.Server.Client.GraphQL.GraphQLServerClient.graphQLClient, Tgstation.Server.Client.GraphQL.GraphQLServerClient.Reauthenticate(), Tgstation.Server.Client.GraphQL.GraphQLServerClient.setAuthenticationHeader, and Tgstation.Server.Client.GraphQL.GraphQLServerClient.ThrowOtherCallerFailedAuthException().
Member Data Documentation
basicCredentialsHeader
readonly? AuthenticationHeaderValue Tgstation.Server.Client.GraphQL.GraphQLServerClient.basicCredentialsHeader private
The AuthenticationHeaderValue containing the authenticated user's password credentials.
Definition at line 55 of file GraphQLServerClient.cs.
Referenced by Tgstation.Server.Client.GraphQL.GraphQLServerClient.GraphQLServerClient(), and Tgstation.Server.Client.GraphQL.GraphQLServerClient.Reauthenticate().
bearerCredentialsHeaderTaskLock
readonly? object Tgstation.Server.Client.GraphQL.GraphQLServerClient.bearerCredentialsHeaderTaskLock private
lock object used to synchronize access to bearerCredentialsTask.
Definition at line 60 of file GraphQLServerClient.cs.
Referenced by Tgstation.Server.Client.GraphQL.GraphQLServerClient.GraphQLServerClient(), and Tgstation.Server.Client.GraphQL.GraphQLServerClient.Reauthenticate().
bearerCredentialsTask
Task<(AuthenticationHeaderValue Header, DateTime Exp)?>? Tgstation.Server.Client.GraphQL.GraphQLServerClient.bearerCredentialsTask private
A Task<TResult> resulting in a ValueTuple<T1, T2> containing the current AuthenticationHeaderValue for the ApiHeaders.BearerAuthenticationScheme and the DateTime it expires.
Definition at line 65 of file GraphQLServerClient.cs.
Referenced by Tgstation.Server.Client.GraphQL.GraphQLServerClient.GraphQLServerClient(), Tgstation.Server.Client.GraphQL.GraphQLServerClient.Reauthenticate(), Tgstation.Server.Client.GraphQL.GraphQLServerClient.Subscribe< TResultData >(), and Tgstation.Server.Client.GraphQL.GraphQLServerClient.WrapAuthentication< TResultData >().
graphQLClient
readonly IGraphQLClient Tgstation.Server.Client.GraphQL.GraphQLServerClient.graphQLClient private
The IGraphQLClient for the GraphQLServerClient.
Definition at line 35 of file GraphQLServerClient.cs.
Referenced by Tgstation.Server.Client.GraphQL.GraphQLServerClient.GraphQLServerClient(), Tgstation.Server.Client.GraphQL.GraphQLServerClient.Reauthenticate(), Tgstation.Server.Client.GraphQL.GraphQLServerClient.Subscribe< TResultData >(), and Tgstation.Server.Client.GraphQL.GraphQLServerClient.WrapAuthentication< TResultData >().
logger
readonly ILogger<GraphQLServerClient> Tgstation.Server.Client.GraphQL.GraphQLServerClient.logger private
The ILogger for the GraphQLServerClient.
Definition at line 45 of file GraphQLServerClient.cs.
Referenced by Tgstation.Server.Client.GraphQL.GraphQLServerClient.CreateCredentialsTuple(), and Tgstation.Server.Client.GraphQL.GraphQLServerClient.GraphQLServerClient().
serviceProvider
readonly IAsyncDisposable Tgstation.Server.Client.GraphQL.GraphQLServerClient.serviceProvider private
The IAsyncDisposable to be DisposeAsync'd with the GraphQLServerClient.
Definition at line 40 of file GraphQLServerClient.cs.
Referenced by Tgstation.Server.Client.GraphQL.GraphQLServerClient.GraphQLServerClient().
setAuthenticationHeader
readonly? Action<AuthenticationHeaderValue> Tgstation.Server.Client.GraphQL.GraphQLServerClient.setAuthenticationHeader private
The Action<T> which sets the AuthenticationHeaderValue for HTTP request in the current async context.
Definition at line 50 of file GraphQLServerClient.cs.
Referenced by Tgstation.Server.Client.GraphQL.GraphQLServerClient.GraphQLServerClient(), Tgstation.Server.Client.GraphQL.GraphQLServerClient.Reauthenticate(), Tgstation.Server.Client.GraphQL.GraphQLServerClient.Subscribe< TResultData >(), and Tgstation.Server.Client.GraphQL.GraphQLServerClient.WrapAuthentication< TResultData >().
Property Documentation
Authenticated
bool Tgstation.Server.Client.GraphQL.GraphQLServerClient.Authenticated get private
If the GraphQLServerClient was initially authenticated.
Definition at line 23 of file GraphQLServerClient.cs.
Referenced by Tgstation.Server.Client.GraphQL.GraphQLServerClient.GraphQLServerClient(), Tgstation.Server.Client.GraphQL.GraphQLServerClient.Subscribe< TResultData >(), and Tgstation.Server.Client.GraphQL.GraphQLServerClient.WrapAuthentication< TResultData >().
CanReauthenticate
bool Tgstation.Server.Client.GraphQL.GraphQLServerClient.CanReauthenticate get private
If the GraphQLServerClient supports reauthentication.
Definition at line 30 of file GraphQLServerClient.cs.
Referenced by Tgstation.Server.Client.GraphQL.GraphQLServerClient.Reauthenticate().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Client.GraphQL/GraphQLServerClient.cs