tgstation-server: Tgstation.Server.Host.Components.Deployment.DmbFactory Class Reference
Tgstation.Server.Host.Components.Deployment.DmbFactory Class Reference
Standard IDmbFactory.
Public Member Functions
DmbFactory (IDatabaseContextFactory databaseContextFactory, IIOManager ioManager, IRemoteDeploymentManagerFactory remoteDeploymentManagerFactory, IEventConsumer eventConsumer, IAsyncDelayer asyncDelayer, ILogger< DmbFactory > logger, Api.Models.Instance metadata)
Initializes a new instance of the DmbFactory class.
void Dispose ()
async ValueTask LoadCompileJob (CompileJob job, Action< bool >? activationAction, CancellationToken cancellationToken)
Load a new job into the ICompileJobSink.
Parameters
job The CompileJob to load.
activationAction An optional Action<T1> to be called when the CompileJob becomes active or is discarded with true or false respectively.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
IDmbProvider LockNextDmb (string reason, [CallerFilePath] string? callerFile=null, [CallerLineNumber] int callerLine=default)
Gets the next IDmbProvider. DmbAvailable is a precondition.
Parameters
reason The reason the lock is being acquired.
callerFile The file path of the calling function.
callerLine The line number of the call invocation.
Returns
A new IDmbProvider.
async Task StartAsync (CancellationToken cancellationToken)
async Task StopAsync (CancellationToken cancellationToken)
async ValueTask< IDmbProvider?> FromCompileJob (CompileJob compileJob, string reason, CancellationToken cancellationToken, [CallerFilePath] string? callerFile=null, [CallerLineNumber] int callerLine=default)
Gets a IDmbProvider for a given CompileJob.
Parameters
compileJob The CompileJob to make the IDmbProvider for.
reason The reason the compile job needed to be loaded.
cancellationToken The CancellationToken for the operation.
callerFile The file path of the calling function.
callerLine The line number of the call invocation.
Returns
A ValueTask<TResult> resulting in a new IDmbProvider representing the CompileJob on success, null on failure.
async ValueTask CleanUnusedCompileJobs (CancellationToken cancellationToken)
Deletes all compile jobs that are inactive in the Game folder.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
async ValueTask< CompileJob?> LatestCompileJob ()
Gets the latest CompileJob.
Returns
A ValueTask<TResult> resulting in the latest CompileJob or null if none are available.
IDmbProvider LockNextDmb (string reason, [CallerFilePath] string? callerFile=null, [CallerLineNumber] int callerLine=default)
Gets the next IDmbProvider. DmbAvailable is a precondition.
ValueTask< IDmbProvider?> FromCompileJob (CompileJob compileJob, string reason, CancellationToken cancellationToken, [CallerFilePath] string? callerFile=null, [CallerLineNumber] int callerLine=default)
Gets a IDmbProvider for a given CompileJob.
ValueTask CleanUnusedCompileJobs (CancellationToken cancellationToken)
Deletes all compile jobs that are inactive in the Game folder.
ValueTask< CompileJob?> LatestCompileJob ()
Gets the latest CompileJob.
ValueTask LoadCompileJob (CompileJob job, Action< bool >? activationAction, CancellationToken cancellationToken)
Load a new job into the ICompileJobSink.
Properties
Task OnNewerDmb [get]
Get a Task that completes when the result of a call to LockNextDmb will be different than the previous call if any.
Returns
A Task representing the running operation.
bool DmbAvailable [get]
If LockNextDmb will succeed.
Properties inherited from Tgstation.Server.Host.Components.Deployment.IDmbFactory
Task OnNewerDmb [get]
Get a Task that completes when the result of a call to LockNextDmb will be different than the previous call if any.
bool DmbAvailable [get]
If LockNextDmb will succeed.
Private Member Functions
async ValueTask<(IDmbProvider? DmbProvider, DeploymentLockManager? LockManager)> FromCompileJobInternal (CompileJob compileJob, string reason, CancellationToken cancellationToken, [CallerFilePath] string? callerFile=null, [CallerLineNumber] int callerLine=default)
Gets a IDmbProvider and potentially the DeploymentLockManager for a given CompileJob.
void CleanRegisteredCompileJob (CompileJob job)
Delete the Api.Models.Internal.CompileJob.DirectoryName of job .
async ValueTask DeleteCompileJobContent (string directory, CancellationToken cancellationToken)
Handles cleaning the resources of a CompileJob.
async Task LogLockStates ()
Lock all DeploymentLockManagers states.
Private Attributes
readonly IDatabaseContextFactory databaseContextFactory
The IDatabaseContextFactory for the DmbFactory.
readonly IIOManager ioManager
The IIOManager for the DmbFactory.
readonly IRemoteDeploymentManagerFactory remoteDeploymentManagerFactory
The IRemoteDeploymentManagerFactory for the DmbFactory.
readonly ILogger< DmbFactory > logger
The ILogger for the DmbFactory.
readonly IEventConsumer eventConsumer
The IEventConsumer for the DmbFactory.
readonly IAsyncDelayer asyncDelayer
The IAsyncDelayer for the DmbFactory.
readonly Api.Models.Instance metadata
The Api.Models.Instance for the DmbFactory.
readonly CancellationTokenSource cleanupCts
The CancellationTokenSource for cleanupTask.
readonly CancellationTokenSource lockLogCts
The CancellationTokenSource for LogLockStates.
readonly Dictionary< long, DeploymentLockManager > jobLockManagers
Map of CompileJob.JobIds to locks on them.
volatile TaskCompletionSource newerDmbTcs
TaskCompletionSource resulting in the latest DmbProvider yet to exist.
Task cleanupTask
Task representing calls to CleanRegisteredCompileJob(CompileJob).
DeploymentLockManager? nextLockManager
The DeploymentLockManager for the latest DmbProvider.
bool started
If the DmbFactory is "started" via IComponentService.
Detailed Description
Standard IDmbFactory.
Definition at line 28 of file DmbFactory.cs.
Constructor & Destructor Documentation
DmbFactory()
Tgstation.Server.Host.Components.Deployment.DmbFactory.DmbFactory (IDatabaseContextFactory databaseContextFactory, IIOManager ioManager, IRemoteDeploymentManagerFactory remoteDeploymentManagerFactory, IEventConsumer eventConsumer, IAsyncDelayer asyncDelayer, ILogger< DmbFactory > logger, Api.Models.Instance metadata)
Initializes a new instance of the DmbFactory class.
Parameters
databaseContextFactory The value of databaseContextFactory.
ioManager The value of ioManager.
remoteDeploymentManagerFactory The value of remoteDeploymentManagerFactory.
eventConsumer The value of eventConsumer.
asyncDelayer The value of asyncDelayer.
logger The value of logger.
metadata The value of metadata.
Definition at line 124 of file DmbFactory.cs.
        {
            this.databaseContextFactory = databaseContextFactory ?? throw new ArgumentNullException(nameof(databaseContextFactory));
            this.ioManager = ioManager ?? throw new ArgumentNullException(nameof(ioManager));
            this.remoteDeploymentManagerFactory = remoteDeploymentManagerFactory ?? throw new ArgumentNullException(nameof(remoteDeploymentManagerFactory));
            this.eventConsumer = eventConsumer ?? throw new ArgumentNullException(nameof(eventConsumer));
            this.asyncDelayer = asyncDelayer ?? throw new ArgumentNullException(nameof(asyncDelayer));
            this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
            this.metadata = metadata ?? throw new ArgumentNullException(nameof(metadata));
            cleanupTask = Task.CompletedTask;
            newerDmbTcs = new TaskCompletionSource();
            cleanupCts = new CancellationTokenSource();
            lockLogCts = new CancellationTokenSource();
            jobLockManagers = new Dictionary<long, DeploymentLockManager>();
        }
References Tgstation.Server.Host.Components.Deployment.DmbFactory.asyncDelayer, Tgstation.Server.Host.Components.Deployment.DmbFactory.cleanupCts, Tgstation.Server.Host.Components.Deployment.DmbFactory.cleanupTask, Tgstation.Server.Host.Components.Deployment.DmbFactory.databaseContextFactory, Tgstation.Server.Host.Components.Deployment.DmbFactory.eventConsumer, Tgstation.Server.Host.Components.Deployment.DmbFactory.ioManager, Tgstation.Server.Host.Components.Deployment.DmbFactory.jobLockManagers, Tgstation.Server.Host.Components.Deployment.DmbFactory.lockLogCts, Tgstation.Server.Host.Components.Deployment.DmbFactory.logger, Tgstation.Server.Host.Components.Deployment.DmbFactory.metadata, Tgstation.Server.Host.Components.Deployment.DmbFactory.newerDmbTcs, and Tgstation.Server.Host.Components.Deployment.DmbFactory.remoteDeploymentManagerFactory.
Member Function Documentation
CleanRegisteredCompileJob()
void Tgstation.Server.Host.Components.Deployment.DmbFactory.CleanRegisteredCompileJob (CompileJob job) private
Delete the Api.Models.Internal.CompileJob.DirectoryName of job .
Parameters
job The CompileJob to clean.
Definition at line 468 of file DmbFactory.cs.
        {
            Task HandleCleanup()
            {
                lock (jobLockManagers)
                    jobLockManagers.Remove(job.Require(x => x.Id));
                var otherTask = cleanupTask;
                async Task WrapThrowableTasks()
                {
                    try
                    {
                        // First kill the GitHub deployment
                        var remoteDeploymentManager = remoteDeploymentManagerFactory.CreateRemoteDeploymentManager(metadata, job);
                        var cancellationToken = cleanupCts.Token;
                        var deploymentJob = remoteDeploymentManager.MarkInactive(job, cancellationToken);
                        var deleteTask = DeleteCompileJobContent(job.DirectoryName!.Value.ToString(), cancellationToken);
                        await ValueTaskExtensions.WhenAll(deleteTask, deploymentJob);
                    }
                    catch (Exception ex) when (ex is not OperationCanceledException)
                    {
                        logger.LogWarning(ex, "Error cleaning up compile job {jobGuid}!", job.DirectoryName);
                    }
                }
                return Task.WhenAll(otherTask, WrapThrowableTasks());
            }
            lock (cleanupCts)
                cleanupTask = HandleCleanup();
        }
References Tgstation.Server.Host.Components.Deployment.DmbFactory.cleanupCts, Tgstation.Server.Host.Components.Deployment.DmbFactory.cleanupTask, Tgstation.Server.Host.Components.Deployment.Remote.IRemoteDeploymentManagerFactory.CreateRemoteDeploymentManager(), Tgstation.Server.Host.Components.Deployment.DmbFactory.DeleteCompileJobContent(), Tgstation.Server.Api.Models.Internal.CompileJob.DirectoryName, Tgstation.Server.Host.Components.Deployment.DmbFactory.jobLockManagers, Tgstation.Server.Host.Components.Deployment.DmbFactory.logger, Tgstation.Server.Host.Components.Deployment.DmbFactory.metadata, Tgstation.Server.Host.Components.Deployment.DmbFactory.remoteDeploymentManagerFactory, and Tgstation.Server.Common.Extensions.ValueTaskExtensions.WhenAll().
Referenced by Tgstation.Server.Host.Components.Deployment.DmbFactory.FromCompileJobInternal().
CleanUnusedCompileJobs()
async ValueTask Tgstation.Server.Host.Components.Deployment.DmbFactory.CleanUnusedCompileJobs (CancellationToken cancellationToken)
Deletes all compile jobs that are inactive in the Game folder.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Deployment.IDmbFactory.
Definition at line 264 of file DmbFactory.cs.
        {
            List<long> jobIdsToSkip;
            // don't clean locked directories
            lock (jobLockManagers)
                jobIdsToSkip = jobLockManagers.Keys.ToList();
            List<string>? jobUidsToNotErase = null;
            // find the uids of locked directories
            if (jobIdsToSkip.Count > 0)
            {
                await databaseContextFactory.UseContext(async db =>
                {
                    jobUidsToNotErase = (await db
                            .CompileJobs
                            .AsQueryable()
                            .Where(
                                x => x.Job.Instance!.Id == metadata.Id
                                && jobIdsToSkip.Contains(x.Id!.Value))
                            .Select(x => x.DirectoryName!.Value)
                            .ToListAsync(cancellationToken))
                        .Select(x => x.ToString())
                        .ToList();
                });
            }
            else
                jobUidsToNotErase = new List<string>();
            jobUidsToNotErase!.Add(SwappableDmbProvider.LiveGameDirectory);
            logger.LogTrace("We will not clean the following directories: {directoriesToNotClean}", String.Join(", ", jobUidsToNotErase));
            // cleanup
            var gameDirectory = ioManager.ResolvePath();
            await ioManager.CreateDirectory(gameDirectory, cancellationToken);
            var directories = await ioManager.GetDirectories(gameDirectory, cancellationToken);
            int deleting = 0;
            var tasks = directories.Select<string, ValueTask>(async x =>
            {
                var nameOnly = ioManager.GetFileName(x);
                if (jobUidsToNotErase.Contains(nameOnly))
                    return;
                logger.LogDebug("Cleaning unused game folder: {dirName}...", nameOnly);
                try
                {
                    ++deleting;
                    await DeleteCompileJobContent(x, cancellationToken);
                }
                catch (Exception e) when (e is not OperationCanceledException)
                {
                    logger.LogWarning(e, "Error deleting directory {dirName}!", x);
                }
            }).ToList();
            if (deleting > 0)
                await ValueTaskExtensions.WhenAll(tasks);
        }
References Tgstation.Server.Host.IO.IIOManager.CreateDirectory(), Tgstation.Server.Host.Components.Deployment.DmbFactory.databaseContextFactory, Tgstation.Server.Host.Components.Deployment.DmbFactory.DeleteCompileJobContent(), Tgstation.Server.Host.IO.IIOManager.GetDirectories(), Tgstation.Server.Host.IO.IIOManager.GetFileName(), Tgstation.Server.Host.Components.Deployment.DmbFactory.ioManager, Tgstation.Server.Host.Components.Deployment.DmbFactory.jobLockManagers, Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.LiveGameDirectory, Tgstation.Server.Host.Components.Deployment.DmbFactory.logger, Tgstation.Server.Host.Components.Deployment.DmbFactory.metadata, Tgstation.Server.Host.IO.IIOManager.ResolvePath(), Tgstation.Server.Host.Database.IDatabaseContextFactory.UseContext(), and Tgstation.Server.Common.Extensions.ValueTaskExtensions.WhenAll().
DeleteCompileJobContent()
async ValueTask Tgstation.Server.Host.Components.Deployment.DmbFactory.DeleteCompileJobContent (string directory, CancellationToken cancellationToken) private
Handles cleaning the resources of a CompileJob.
Parameters
directory The directory to cleanup.
cancellationToken The CancellationToken for this Task.
Returns
The deletion ValueTask.
Definition at line 510 of file DmbFactory.cs.
        {
            // Then call the cleanup event, waiting here first
            await eventConsumer.HandleEvent(EventType.DeploymentCleanup, new List<string> { ioManager.ResolvePath(directory) }, true, cancellationToken);
            await ioManager.DeleteDirectory(directory, cancellationToken);
        }
References Tgstation.Server.Host.IO.IIOManager.DeleteDirectory(), Tgstation.Server.Host.Components.Deployment.DmbFactory.eventConsumer, Tgstation.Server.Host.Components.Events.IEventConsumer.HandleEvent(), and Tgstation.Server.Host.Components.Deployment.DmbFactory.ioManager.
Referenced by Tgstation.Server.Host.Components.Deployment.DmbFactory.CleanRegisteredCompileJob(), and Tgstation.Server.Host.Components.Deployment.DmbFactory.CleanUnusedCompileJobs().
Dispose()
void Tgstation.Server.Host.Components.Deployment.DmbFactory.Dispose ()
Definition at line 149 of file DmbFactory.cs.
        {
            // we don't dispose nextDmbProvider here, since it might be the only thing we have
            lockLogCts.Dispose();
            cleanupCts.Dispose();
        }
References Tgstation.Server.Host.Components.Deployment.DmbFactory.cleanupCts, and Tgstation.Server.Host.Components.Deployment.DmbFactory.lockLogCts.
FromCompileJob()
async ValueTask< IDmbProvider?> Tgstation.Server.Host.Components.Deployment.DmbFactory.FromCompileJob (CompileJob compileJob, string reason, CancellationToken cancellationToken, [CallerFilePath] string? callerFile = null, [CallerLineNumber] int callerLine = default)
Gets a IDmbProvider for a given CompileJob.
Parameters
compileJob The CompileJob to make the IDmbProvider for.
reason The reason the compile job needed to be loaded.
cancellationToken The CancellationToken for the operation.
callerFile The file path of the calling function.
callerLine The line number of the call invocation.
Returns
A ValueTask<TResult> resulting in a new IDmbProvider representing the CompileJob on success, null on failure.
Implements Tgstation.Server.Host.Components.Deployment.IDmbFactory.
Definition at line 252 of file DmbFactory.cs.
        {
            ArgumentNullException.ThrowIfNull(compileJob);
            ArgumentNullException.ThrowIfNull(reason);
            var (dmb, _) = await FromCompileJobInternal(compileJob, reason, cancellationToken, callerFile, callerLine);
            return dmb;
        }
References Tgstation.Server.Host.Components.Deployment.DmbFactory.FromCompileJobInternal().
Referenced by Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.ApplyInitialDmb().
FromCompileJobInternal()
async ValueTask<(IDmbProvider? DmbProvider, DeploymentLockManager? LockManager)> Tgstation.Server.Host.Components.Deployment.DmbFactory.FromCompileJobInternal (CompileJob compileJob, string reason, CancellationToken cancellationToken, [CallerFilePath] string? callerFile = null, [CallerLineNumber] int callerLine = default) private
Gets a IDmbProvider and potentially the DeploymentLockManager for a given CompileJob.
Parameters
compileJob The CompileJob to make the IDmbProvider for.
reason The reason the compile job needed to be loaded.
cancellationToken The CancellationToken for the operation.
callerFile The file path of the calling function.
callerLine The line number of the call invocation.
Returns
A ValueTask<TResult> resulting in, on success, a tuple containing new IDmbProvider representing the CompileJob. If the first lock on compileJob was acquired, the DeploymentLockManager will also be returned. On failure, null Will be returned.
Definition at line 344 of file DmbFactory.cs.
        {
            // ensure we have the entire metadata tree
            var compileJobId = compileJob.Require(x => x.Id);
            lock (jobLockManagers)
                if (jobLockManagers.TryGetValue(compileJobId, out var lockManager))
                    return (DmbProvider: lockManager.AddLock(reason, callerFile, callerLine), LockManager: null); // fast path
            logger.LogTrace("Loading compile job {id}...", compileJobId);
            await databaseContextFactory.UseContext(
                async db => compileJob = await db
                    .CompileJobs
                    .AsQueryable()
                    .Where(x => x!.Id == compileJobId)
                    .Include(x => x.Job!)
                        .ThenInclude(x => x.StartedBy)
                    .Include(x => x.Job!)
                        .ThenInclude(x => x.Instance)
                    .Include(x => x.RevisionInformation!)
                        .ThenInclude(x => x.PrimaryTestMerge!)
                            .ThenInclude(x => x.MergedBy)
                    .Include(x => x.RevisionInformation!)
                        .ThenInclude(x => x.ActiveTestMerges!)
                            .ThenInclude(x => x.TestMerge!)
                                .ThenInclude(x => x.MergedBy)
                    .FirstAsync(cancellationToken)); // can't wait to see that query
            EngineVersion engineVersion;
            if (!EngineVersion.TryParse(compileJob.EngineVersion, out var engineVersionNullable))
            {
                logger.LogError("Error loading compile job, bad engine version: {engineVersion}", compileJob.EngineVersion);
                return (null, null); // omae wa mou shinderu
            }
            else
                engineVersion = engineVersionNullable!;
            if (!compileJob.Job.StoppedAt.HasValue)
            {
                // This happens when we're told to load the compile job that is currently finished up
                // It constitutes an API violation if it's returned by the DreamDaemonController so just set it here
                // Bit of a hack, but it works out to be nearly if not the same value that's put in the DB
                logger.LogTrace("Setting missing StoppedAt for CompileJob.Job #{id}...", compileJob.Job.Id);
                compileJob.Job.StoppedAt = DateTimeOffset.UtcNow;
            }
            var providerSubmitted = false;
            void CleanupAction()
            {
                if (providerSubmitted)
                    CleanRegisteredCompileJob(compileJob);
            }
            var newProvider = new DmbProvider(compileJob, engineVersion, ioManager, new DisposeInvoker(CleanupAction));
            try
            {
                const string LegacyADirectoryName = "A";
                const string LegacyBDirectoryName = "B";
                var dmbExistsAtRoot = await ioManager.FileExists(
                    ioManager.ConcatPath(
                        newProvider.Directory,
                        newProvider.DmbName),
                    cancellationToken);
                if (!dmbExistsAtRoot)
                {
                    logger.LogTrace("Didn't find .dmb at game directory root, checking A/B dirs...");
                    var primaryCheckTask = ioManager.FileExists(
                        ioManager.ConcatPath(
                            newProvider.Directory,
                            LegacyADirectoryName,
                            newProvider.DmbName),
                        cancellationToken);
                    var secondaryCheckTask = ioManager.FileExists(
                        ioManager.ConcatPath(
                            newProvider.Directory,
                            LegacyBDirectoryName,
                            newProvider.DmbName),
                        cancellationToken);
                    if (!(await primaryCheckTask && await secondaryCheckTask))
                    {
                        logger.LogWarning("Error loading compile job, .dmb missing!");
                        return (null, null); // omae wa mou shinderu
                    }
                    // rebuild the provider because it's using the legacy style directories
                    // Don't dispose it
                    logger.LogDebug("Creating legacy two folder .dmb provider targeting {aDirName} directory...", LegacyADirectoryName);
#pragma warning disable CA2000 // Dispose objects before losing scope (false positive)
                    newProvider = new DmbProvider(compileJob, engineVersion, ioManager, new DisposeInvoker(CleanupAction), Path.DirectorySeparatorChar + LegacyADirectoryName);
#pragma warning restore CA2000 // Dispose objects before losing scope
                }
                lock (jobLockManagers)
                {
                    IDmbProvider lockedProvider;
                    if (!jobLockManagers.TryGetValue(compileJobId, out var lockManager))
                    {
                        lockManager = DeploymentLockManager.Create(newProvider, logger, reason, out lockedProvider);
                        jobLockManagers.Add(compileJobId, lockManager);
                        providerSubmitted = true;
                    }
                    else
                    {
                        lockedProvider = lockManager.AddLock(reason, callerFile, callerLine); // race condition
                        lockManager = null;
                    }
                    return (DmbProvider: lockedProvider, LockManager: lockManager);
                }
            }
            finally
            {
                if (!providerSubmitted)
                    await newProvider.DisposeAsync();
            }
        }
References Tgstation.Server.Host.Components.Deployment.DmbFactory.CleanRegisteredCompileJob(), Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.Create(), Tgstation.Server.Host.Components.Deployment.DmbFactory.databaseContextFactory, Tgstation.Server.Host.Models.CompileJob.EngineVersion, Tgstation.Server.Host.IO.IIOManager.FileExists(), Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Host.Components.Deployment.DmbFactory.ioManager, Tgstation.Server.Host.Models.CompileJob.Job, Tgstation.Server.Host.Components.Deployment.DmbFactory.jobLockManagers, Tgstation.Server.Host.Components.Deployment.DmbFactory.logger, Tgstation.Server.Api.Models.Internal.Job.StoppedAt, Tgstation.Server.Api.Models.EngineVersion.TryParse(), and Tgstation.Server.Host.Database.IDatabaseContextFactory.UseContext().
Referenced by Tgstation.Server.Host.Components.Deployment.DmbFactory.FromCompileJob(), and Tgstation.Server.Host.Components.Deployment.DmbFactory.LoadCompileJob().
LatestCompileJob()
async ValueTask< CompileJob?> Tgstation.Server.Host.Components.Deployment.DmbFactory.LatestCompileJob ()
Gets the latest CompileJob.
Returns
A ValueTask<TResult> resulting in the latest CompileJob or null if none are available.
Implements Tgstation.Server.Host.Components.Deployment.ILatestCompileJobProvider.
Definition at line 325 of file DmbFactory.cs.
        {
            if (!DmbAvailable)
                return null;
            await using IDmbProvider provider = LockNextDmb("Checking latest CompileJob");
            return provider.CompileJob;
        }
References Tgstation.Server.Host.Components.Deployment.DmbFactory.DmbAvailable, and Tgstation.Server.Host.Components.Deployment.DmbFactory.LockNextDmb().
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.InitialCheckDmbUpdated().
LoadCompileJob()
async ValueTask Tgstation.Server.Host.Components.Deployment.DmbFactory.LoadCompileJob (CompileJob job, Action< bool >? activationAction, CancellationToken cancellationToken)
Load a new job into the ICompileJobSink.
Parameters
job The CompileJob to load.
activationAction An optional Action<T1> to be called when the CompileJob becomes active or is discarded with true or false respectively.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Deployment.ICompileJobSink.
Definition at line 157 of file DmbFactory.cs.
        {
            ArgumentNullException.ThrowIfNull(job);
            var (dmbProvider, lockManager) = await FromCompileJobInternal(job, "Compile job loading", cancellationToken);
            if (dmbProvider == null)
                return;
            if (lockManager == null)
                throw new InvalidOperationException($"We did not acquire the first lock for compile job {job.Id}!");
            // Do this first, because it's entirely possible when we set the tcs it will immediately need to be applied
            if (started)
            {
                var remoteDeploymentManager = remoteDeploymentManagerFactory.CreateRemoteDeploymentManager(
                    metadata,
                    job);
                await remoteDeploymentManager.StageDeployment(
                    lockManager.CompileJob,
                    activationAction,
                    cancellationToken);
            }
            ValueTask dmbDisposeTask;
            lock (jobLockManagers)
            {
                dmbDisposeTask = nextLockManager?.DisposeAsync() ?? ValueTask.CompletedTask;
                nextLockManager = lockManager;
                // Oh god dammit
                var temp = Interlocked.Exchange(ref newerDmbTcs, new TaskCompletionSource());
                temp.SetResult();
            }
            await dmbDisposeTask;
        }
References Tgstation.Server.Host.Components.Deployment.Remote.IRemoteDeploymentManagerFactory.CreateRemoteDeploymentManager(), Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.DisposeAsync(), Tgstation.Server.Host.Components.Deployment.DmbFactory.FromCompileJobInternal(), Tgstation.Server.Host.Components.Deployment.DmbFactory.jobLockManagers, Tgstation.Server.Host.Components.Deployment.DmbFactory.metadata, Tgstation.Server.Host.Components.Deployment.DmbFactory.newerDmbTcs, Tgstation.Server.Host.Components.Deployment.DmbFactory.nextLockManager, Tgstation.Server.Host.Components.Deployment.DmbFactory.remoteDeploymentManagerFactory, Tgstation.Server.Host.Components.Deployment.Remote.IRemoteDeploymentManager.StageDeployment(), and Tgstation.Server.Host.Components.Deployment.DmbFactory.started.
Referenced by Tgstation.Server.Host.Components.Deployment.DmbFactory.StartAsync().
LockNextDmb()
IDmbProvider Tgstation.Server.Host.Components.Deployment.DmbFactory.LockNextDmb (string reason, [CallerFilePath] string? callerFile = null, [CallerLineNumber] int callerLine = default)
Gets the next IDmbProvider. DmbAvailable is a precondition.
Parameters
reason The reason the lock is being acquired.
callerFile The file path of the calling function.
callerLine The line number of the call invocation.
Returns
A new IDmbProvider.
Implements Tgstation.Server.Host.Components.Deployment.IDmbFactory.
Definition at line 195 of file DmbFactory.cs.
        {
            if (!DmbAvailable)
                throw new InvalidOperationException("No .dmb available!");
            return nextLockManager.AddLock(reason, callerFile, callerLine);
        }
References Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.AddLock(), Tgstation.Server.Host.Components.Deployment.DmbFactory.DmbAvailable, and Tgstation.Server.Host.Components.Deployment.DmbFactory.nextLockManager.
Referenced by Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.HandleNewDmbAvailable(), Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.InitController(), and Tgstation.Server.Host.Components.Deployment.DmbFactory.LatestCompileJob().
LogLockStates()
async Task Tgstation.Server.Host.Components.Deployment.DmbFactory.LogLockStates () private
Lock all DeploymentLockManagers states.
Returns
A Task representing the running operation.
Definition at line 521 of file DmbFactory.cs.
        {
            logger.LogTrace("Entering lock logging loop");
            CancellationToken cancellationToken = lockLogCts.Token;
            while (!cancellationToken.IsCancellationRequested)
                try
                {
                    var builder = new StringBuilder();
                    lock (jobLockManagers)
                        foreach (var lockManager in jobLockManagers.Values)
                            lockManager.LogLockStats(builder);
                    logger.LogDebug("Periodic deployment log states report (R.e. Issue #1779):{newLine}{report}", Environment.NewLine, builder); // TODO: Reduce to trace once #1779 is fixed
                    await asyncDelayer.Delay(TimeSpan.FromMinutes(10), cancellationToken);
                }
                catch (OperationCanceledException ex)
                {
                    logger.LogTrace(ex, "Exiting lock logging loop");
                    break;
                }
        }
References Tgstation.Server.Host.Components.Deployment.DmbFactory.asyncDelayer, Tgstation.Server.Host.Utils.IAsyncDelayer.Delay(), Tgstation.Server.Host.Components.Deployment.DmbFactory.jobLockManagers, Tgstation.Server.Host.Components.Deployment.DmbFactory.lockLogCts, and Tgstation.Server.Host.Components.Deployment.DmbFactory.logger.
Referenced by Tgstation.Server.Host.Components.Deployment.DmbFactory.StartAsync().
StartAsync()
async Task Tgstation.Server.Host.Components.Deployment.DmbFactory.StartAsync (CancellationToken cancellationToken)
Definition at line 204 of file DmbFactory.cs.
        {
            CompileJob? cj = null;
            await databaseContextFactory.UseContext(
                async (db) =>
                    cj = await db
                        .CompileJobs
                        .AsQueryable()
                        .Where(x => x.Job.Instance!.Id == metadata.Id)
                        .OrderByDescending(x => x.Job.StoppedAt)
                        .FirstOrDefaultAsync(cancellationToken));
            try
            {
                if (cj == default(CompileJob))
                    return;
                await LoadCompileJob(cj, null, cancellationToken);
            }
            finally
            {
                started = true;
            }
            // we dont do CleanUnusedCompileJobs here because the watchdog may have plans for them yet
            cleanupTask = Task.WhenAll(cleanupTask, LogLockStates());
        }
References Tgstation.Server.Host.Components.Deployment.DmbFactory.cleanupTask, Tgstation.Server.Host.Components.Deployment.DmbFactory.databaseContextFactory, Tgstation.Server.Host.Components.Deployment.DmbFactory.LoadCompileJob(), Tgstation.Server.Host.Components.Deployment.DmbFactory.LogLockStates(), Tgstation.Server.Host.Components.Deployment.DmbFactory.metadata, Tgstation.Server.Host.Components.Deployment.DmbFactory.started, and Tgstation.Server.Host.Database.IDatabaseContextFactory.UseContext().
StopAsync()
async Task Tgstation.Server.Host.Components.Deployment.DmbFactory.StopAsync (CancellationToken cancellationToken)
Definition at line 232 of file DmbFactory.cs.
        {
            try
            {
                lockLogCts.Cancel();
                lock (jobLockManagers)
                    remoteDeploymentManagerFactory.ForgetLocalStateForCompileJobs(jobLockManagers.Keys);
                using (cancellationToken.Register(() => cleanupCts.Cancel()))
                    await cleanupTask;
            }
            finally
            {
                started = false;
            }
        }
References Tgstation.Server.Host.Components.Deployment.DmbFactory.cleanupCts, Tgstation.Server.Host.Components.Deployment.DmbFactory.cleanupTask, Tgstation.Server.Host.Components.Deployment.Remote.IRemoteDeploymentManagerFactory.ForgetLocalStateForCompileJobs(), Tgstation.Server.Host.Components.Deployment.DmbFactory.jobLockManagers, Tgstation.Server.Host.Components.Deployment.DmbFactory.lockLogCts, Tgstation.Server.Host.Components.Deployment.DmbFactory.remoteDeploymentManagerFactory, and Tgstation.Server.Host.Components.Deployment.DmbFactory.started.
Member Data Documentation
asyncDelayer
readonly IAsyncDelayer Tgstation.Server.Host.Components.Deployment.DmbFactory.asyncDelayer private
The IAsyncDelayer for the DmbFactory.
Definition at line 72 of file DmbFactory.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DmbFactory.DmbFactory(), and Tgstation.Server.Host.Components.Deployment.DmbFactory.LogLockStates().
cleanupCts
readonly CancellationTokenSource Tgstation.Server.Host.Components.Deployment.DmbFactory.cleanupCts private
The CancellationTokenSource for cleanupTask.
Definition at line 82 of file DmbFactory.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DmbFactory.CleanRegisteredCompileJob(), Tgstation.Server.Host.Components.Deployment.DmbFactory.Dispose(), Tgstation.Server.Host.Components.Deployment.DmbFactory.DmbFactory(), and Tgstation.Server.Host.Components.Deployment.DmbFactory.StopAsync().
cleanupTask
Task Tgstation.Server.Host.Components.Deployment.DmbFactory.cleanupTask private
Task representing calls to CleanRegisteredCompileJob(CompileJob).
Definition at line 102 of file DmbFactory.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DmbFactory.CleanRegisteredCompileJob(), Tgstation.Server.Host.Components.Deployment.DmbFactory.DmbFactory(), Tgstation.Server.Host.Components.Deployment.DmbFactory.StartAsync(), and Tgstation.Server.Host.Components.Deployment.DmbFactory.StopAsync().
databaseContextFactory
readonly IDatabaseContextFactory Tgstation.Server.Host.Components.Deployment.DmbFactory.databaseContextFactory private
The IDatabaseContextFactory for the DmbFactory.
Definition at line 47 of file DmbFactory.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DmbFactory.CleanUnusedCompileJobs(), Tgstation.Server.Host.Components.Deployment.DmbFactory.DmbFactory(), Tgstation.Server.Host.Components.Deployment.DmbFactory.FromCompileJobInternal(), and Tgstation.Server.Host.Components.Deployment.DmbFactory.StartAsync().
eventConsumer
readonly IEventConsumer Tgstation.Server.Host.Components.Deployment.DmbFactory.eventConsumer private
The IEventConsumer for the DmbFactory.
Definition at line 67 of file DmbFactory.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DmbFactory.DeleteCompileJobContent(), and Tgstation.Server.Host.Components.Deployment.DmbFactory.DmbFactory().
ioManager
readonly IIOManager Tgstation.Server.Host.Components.Deployment.DmbFactory.ioManager private
The IIOManager for the DmbFactory.
Definition at line 52 of file DmbFactory.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DmbFactory.CleanUnusedCompileJobs(), Tgstation.Server.Host.Components.Deployment.DmbFactory.DeleteCompileJobContent(), Tgstation.Server.Host.Components.Deployment.DmbFactory.DmbFactory(), and Tgstation.Server.Host.Components.Deployment.DmbFactory.FromCompileJobInternal().
jobLockManagers
readonly Dictionary<long, DeploymentLockManager> Tgstation.Server.Host.Components.Deployment.DmbFactory.jobLockManagers private
Map of CompileJob.JobIds to locks on them.
Definition at line 92 of file DmbFactory.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DmbFactory.CleanRegisteredCompileJob(), Tgstation.Server.Host.Components.Deployment.DmbFactory.CleanUnusedCompileJobs(), Tgstation.Server.Host.Components.Deployment.DmbFactory.DmbFactory(), Tgstation.Server.Host.Components.Deployment.DmbFactory.FromCompileJobInternal(), Tgstation.Server.Host.Components.Deployment.DmbFactory.LoadCompileJob(), Tgstation.Server.Host.Components.Deployment.DmbFactory.LogLockStates(), and Tgstation.Server.Host.Components.Deployment.DmbFactory.StopAsync().
lockLogCts
readonly CancellationTokenSource Tgstation.Server.Host.Components.Deployment.DmbFactory.lockLogCts private
The CancellationTokenSource for LogLockStates.
Definition at line 87 of file DmbFactory.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DmbFactory.Dispose(), Tgstation.Server.Host.Components.Deployment.DmbFactory.DmbFactory(), Tgstation.Server.Host.Components.Deployment.DmbFactory.LogLockStates(), and Tgstation.Server.Host.Components.Deployment.DmbFactory.StopAsync().
logger
readonly ILogger<DmbFactory> Tgstation.Server.Host.Components.Deployment.DmbFactory.logger private
The ILogger for the DmbFactory.
Definition at line 62 of file DmbFactory.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DmbFactory.CleanRegisteredCompileJob(), Tgstation.Server.Host.Components.Deployment.DmbFactory.CleanUnusedCompileJobs(), Tgstation.Server.Host.Components.Deployment.DmbFactory.DmbFactory(), Tgstation.Server.Host.Components.Deployment.DmbFactory.FromCompileJobInternal(), and Tgstation.Server.Host.Components.Deployment.DmbFactory.LogLockStates().
metadata
readonly Api.Models.Instance Tgstation.Server.Host.Components.Deployment.DmbFactory.metadata private
The Api.Models.Instance for the DmbFactory.
Definition at line 77 of file DmbFactory.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DmbFactory.CleanRegisteredCompileJob(), Tgstation.Server.Host.Components.Deployment.DmbFactory.CleanUnusedCompileJobs(), Tgstation.Server.Host.Components.Deployment.DmbFactory.DmbFactory(), Tgstation.Server.Host.Components.Deployment.DmbFactory.LoadCompileJob(), and Tgstation.Server.Host.Components.Deployment.DmbFactory.StartAsync().
newerDmbTcs
volatile TaskCompletionSource Tgstation.Server.Host.Components.Deployment.DmbFactory.newerDmbTcs private
TaskCompletionSource resulting in the latest DmbProvider yet to exist.
Definition at line 97 of file DmbFactory.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DmbFactory.DmbFactory(), and Tgstation.Server.Host.Components.Deployment.DmbFactory.LoadCompileJob().
nextLockManager
DeploymentLockManager? Tgstation.Server.Host.Components.Deployment.DmbFactory.nextLockManager private
The DeploymentLockManager for the latest DmbProvider.
Definition at line 107 of file DmbFactory.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DmbFactory.LoadCompileJob(), and Tgstation.Server.Host.Components.Deployment.DmbFactory.LockNextDmb().
remoteDeploymentManagerFactory
readonly IRemoteDeploymentManagerFactory Tgstation.Server.Host.Components.Deployment.DmbFactory.remoteDeploymentManagerFactory private
The IRemoteDeploymentManagerFactory for the DmbFactory.
Definition at line 57 of file DmbFactory.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DmbFactory.CleanRegisteredCompileJob(), Tgstation.Server.Host.Components.Deployment.DmbFactory.DmbFactory(), Tgstation.Server.Host.Components.Deployment.DmbFactory.LoadCompileJob(), and Tgstation.Server.Host.Components.Deployment.DmbFactory.StopAsync().
started
bool Tgstation.Server.Host.Components.Deployment.DmbFactory.started private
If the DmbFactory is "started" via IComponentService.
Definition at line 112 of file DmbFactory.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DmbFactory.LoadCompileJob(), Tgstation.Server.Host.Components.Deployment.DmbFactory.StartAsync(), and Tgstation.Server.Host.Components.Deployment.DmbFactory.StopAsync().
Property Documentation
DmbAvailable
bool Tgstation.Server.Host.Components.Deployment.DmbFactory.DmbAvailable get
If LockNextDmb will succeed.
Implements Tgstation.Server.Host.Components.Deployment.IDmbFactory.
Definition at line 42 of file DmbFactory.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DmbFactory.LatestCompileJob(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.LaunchNoLock(), and Tgstation.Server.Host.Components.Deployment.DmbFactory.LockNextDmb().
OnNewerDmb
Task Tgstation.Server.Host.Components.Deployment.DmbFactory.OnNewerDmb get
Get a Task that completes when the result of a call to LockNextDmb will be different than the previous call if any.
Returns
A Task representing the running operation.
Implements Tgstation.Server.Host.Components.Deployment.IDmbFactory.
Definition at line 31 of file DmbFactory.cs.
        {
            get
            {
                lock (jobLockManagers)
                    return newerDmbTcs.Task;
            }
        }
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.InitialCheckDmbUpdated().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Deployment/DmbFactory.cs