tgstation-server: TGServerService.TGStationServer Class Reference
TGServerService.TGStationServer Class Reference
Classes
class RepoConfig
Repo specific information about the installation Requires RepoLock and !RepoBusy to be instantiated
class TwoStrings
class VersionInfo
Public Member Functions
string GetCurrentAuthorizedGroup ()
Returns the name of the windows group allowed to use the service other than administrator
string SetAuthorizedGroup (string groupName)
Searches the windows machine for the group named groupName , sets it as the authorized group if it's found
ushort RemoteAccessPort ()
Get the port used for remote operation
string SetRemoteAccessPort (ushort port)
Set the port used for remote operation Requires a service restart to take effect
string MoveServer (string new_location)
Moves the entire server installation, requires no operations to be running
string RecreateStaticFolder ()
Renames the current static folder to a backup name and recreates is from the current repo using TGS3.json
TGByondStatus CurrentStatus ()
Gets the current status of any BYOND updates
string GetError ()
Check the last update error. Checking this will clear the value
string GetVersion (TGByondVersion type)
Get the currently installed version as a string formatted as Major.Minor
void UpdateToVersionImpl (object param)
bool UpdateToVersion (int ma, int mi)
updates the used byond version to that of version major .minor . The change won't take place until DD reboots. Calls ITGDreamDaemon.RequestRestart if blocked by a running DD instance. Runs asyncronously, use CurrentStatus to check progress
bool ApplyStagedUpdate ()
void InitChat ()
IList< TGChatSetupInfo > ProviderInfos ()
Returns TGChatSetupInfo for all TGChatProviders
string SetProviderInfo (TGChatSetupInfo info)
Sets a chat provider info
bool Connected (TGChatProvider providerType)
Checks connection status
string Reconnect (TGChatProvider providerType)
Reconnect a specific providerType to it's chat service
void SendMessage (string msg, ChatMessageType mt)
Broadcast a message to appropriate channels based on the message type
TGCompilerStatus GetStatus ()
Returns the current compiler status
string CompileError ()
Returns the error message of the last operation. Reading this will clear the stored value
bool Initialize ()
Sets up the symlinks for hotswapping game code. This will reset everything in the Game folder. Requires the repository to be set up and locks it once the compilation stage starts. Runs asyncronously from this call
void InitializeImpl ()
bool Compile (bool silent=false)
Does all the necessary actions to take the revision currently in the repository and compile it to be run on the next server reboot. Requires BYOND to be set up and the GetStatus to return TGCompilerStatus.Initialized. Runs asyncronously
string ProjectName ()
Returns the relative path of the dme the compiler will look for without the .dme part
void SetProjectName (string projectName)
Sets the relative path of the dme the compiler will look for without the .dme part
string Cancel ()
Cancels the current compilation
string ServerDirectory ()
Return the directory of the server on the host machine
string ReadText (string staticRelativePath, bool repo, out string error, out bool unauthorized)
Read from a static file
string WriteText (string staticRelativePath, string data, out bool unauthorized)
Write to a static file
string DeleteFile (string staticRelativePath, out bool unauthorized)
Deletes the target static file
IList< string > ListStaticDirectory (string subDir, out string error, out bool unauthorized)
Returns the file contents of the specified server directory Subdirectories will be prefixed with '/'
TGDreamDaemonStatus DaemonStatus ()
Gets the status of DreamDaemon
void RequestRestart ()
Restart the server after the currently running world reboots. Has no effect if the server isn't running
void RequestStop ()
Stop the server after the currently running world reboots. Has no effect if the server isn't running
string Stop ()
Immediately kills the server
void SetPort (ushort new_port)
Set the port to host DD on. Requires reboot to apply. Calls RequestRestart.
void KillMe ()
string Restart ()
Immediately kills and restarts the server
string CanStart ()
Check if a call to Start will fail. Of course, be aware of race conditions with other interfaces
string Start ()
Starts the server if it isn't running
TGDreamDaemonSecurity SecurityLevel ()
Get the configured (not necessarily running) security level
bool SetSecurityLevel (TGDreamDaemonSecurity level)
Sets the security level of the server. Requires server reboot to apply. Calls RequestRestart. Note that anything higher than Trusted will disable interop from DD
bool Autostart ()
Check if the watchdog will start when the service starts
void SetAutostart (bool on)
Set the autostart config
string StatusString (bool includeMetaInfo)
Returns a human readable string of the current server status
ushort Port ()
Get the configured port. Not necessarily the running port if it has since changed
bool ShutdownInProgress ()
Checks if a server stop has been requested
string WorldAnnounce (string message)
Sends a message to everyone on the server
bool Webclient ()
Check if the BYOND webclient is currently enabled for the server
void SetWebclient (bool on)
Set the webclient config. Calls RequestRestart
TGStationServer ()
string Version ()
Retrieve's the service's version
void VerifyConnection ()
Does nothing on the server end, but if the call completes, you can be sure you are connected. WCF won't throw until you try until you actually use the API
void PrepareForUpdate ()
Next stop of the service will not close DD and sets a flag for it to reattach once it restarts
void Dispose ()
string SendCommand (string cmd)
int PlayerCount ()
Returns the number of connected players. Requires game to use API version >= 3.1.0.1
bool InteropMessage (string command)
Called from /world/ExportService(command)
bool PrecompileHook ()
bool PostcompileHook ()
bool OperationInProgress ()
If the repo is currently undergoing an operation
int CheckoutProgress ()
Gets the progress of repository operations, not all operations are supported
bool Exists ()
Check if the repository is valid, if not Setup(string, string) must be called
string UpdateTGS3Json ()
Updates the cached TGS3.json to the repo's version. Compiles will not succeed if these two to not match
string Setup (string RepoURL, string BranchName)
Deletes whatever may be left over and clones the repo at remote and checks out branch . Will move config and data dirs to a backup location if they exist. Runs asyncronously
string GetHead (bool useTracked, out string error)
Gets the sha of the current HEAD
string GetBranch (out string error)
Gets the name of the current branch
string GetRemote (out string error)
Gets the url of the current origin
string Checkout (string sha)
Hard checks out the passed object name
string Update (bool reset)
Fetches the origin and merges it into the current branch
IDictionary< string, string > ListBackups (out string error)
List the tagged commits of the repo at which compiles took place
string Reset (bool trackedBranch)
Runs git reset –hard
string MergePullRequest (int PRNumber)
Merges the target pull request into the current branch if the remote is a github repository
IList< PullRequestInfo > MergedPullRequests (out string error)
Get the currently merged pull requests. Note that switching branches will delete this list and switching back won't restore it
string GetCommitterName ()
Gets the name of the configured git committer
void SetCommitterName (string newName)
Sets the name of the configured git committer
string GetCommitterEmail ()
Gets the email of the configured git committer
void SetCommitterEmail (string newEmail)
Sets the email of the configured git committer
string SynchronizePush ()
Pushes the paths listed in TGS3.json to the currentl git remote. No other commit differences may exist for this function to succeed
string GenerateChangelog (out string error)
Updates the html changelog
string GenerateChangelogImpl (out string error, bool recurse=false)
void SetAutoUpdateInterval (ulong newInterval)
(De)Activate and set the interval for the automatic server updater
ulong AutoUpdateInterval ()
Get the current autoupdate interval
bool SetPythonPath (string path)
Sets the path to the python 2.7 installation
string PythonPath ()
Gets the path to the python 2.7 installation
string LiveSha ()
Static Public Member Functions
static string SanitizeTopicString (string input)
Protected Member Functions
override bool CheckAccessCore (OperationContext operationContext)
virtual void Dispose (bool disposing)
Private Types
enum SymbolicLink { SymbolicLink.File = 0, SymbolicLink.Directory = 1 }
enum ShutdownRequestPhase { ShutdownRequestPhase.None, ShutdownRequestPhase.Requested, ShutdownRequestPhase.Pinged }
Private Member Functions
string FindTheDroidsWereLookingFor (string search=null)
void InitByond ()
void CleanByondStaging ()
void DisposeByond ()
bool BusyCheckNoLock ()
void ChatProvider_OnChatMessage (ITGChatProvider ChatProvider, string speaker, string channel, string message, bool isAdmin, bool isAdminChannel)
void DisposeChat ()
IList< TGChatSetupInfo > InitProviderInfos ()
void ChatConnectivityCheck ()
Reconnect servers that are enabled and disconnected
static bool CreateSymbolicLink (string lpSymlinkFileName, string lpTargetFileName, SymbolicLink dwFlags)
void InitCompiler ()
void DisposeCompiler ()
void CreateSymlink (string link, string target)
bool CompilerIdleNoLock ()
TGCompilerStatus IsInitialized ()
void CleanGameFolderList (string GameDir, IList< string > theList)
void CleanGameFolder ()
string GetStagingDir ()
string InvertDirectory (string gameDirectory)
void CompileImpl ()
void InitDreamDaemon ()
void DisposeDreamDaemon ()
void WriteCurrentDDLog (string message)
void Watchdog ()
void MemTrackTimer_Elapsed (object sender, ElapsedEventArgs e)
string CanStartImpl ()
string SecurityWord (bool starting=false)
void UpdateInterfaceDll (bool overwrite)
string StartImpl (bool watchdog)
void RunDisposals ()
void LoadServerChatCommands ()
void HandleCommand (string cmd)
bool CheckAPIVersionConstraints ()
string SendTopic (string topicdata, ushort port)
void GenCommsKey ()
string GetPath (string eventName)
bool EventHandlerExists (string eventName)
bool HandleEvent (string eventName)
void InitRepo ()
bool RepoConfigsMatch ()
string LoadRepo ()
void DisposeRepo ()
bool HandleTransferProgress (TransferProgress progress)
void HandleCheckoutProgress (string path, int completedSteps, int totalSteps)
void Clone (object twostrings)
void DisableGarbageCollectionNoLock ()
void BackupAndDeleteStaticDirectory ()
void InitialConfigureRepository ()
string GetShaOrBranch (out string error, bool branch, bool tracked)
string ResetNoLock (Branch targetBranch)
string MergeBranch (string branchname)
string UpdateImpl (bool reset, bool successOnUpToDate)
void UpdateSubmodules ()
string CreateBackup ()
Signature MakeSig ()
void DeletePRList ()
IDictionary< string, IDictionary< string, string > > GetCurrentPRList ()
void SetCurrentPRList (IDictionary< string, IDictionary< string, string >> list)
string MergePullRequestImpl (int PRNumber, bool impliedUpdate)
FetchOptions GenerateFetchOptions ()
string Fetch ()
Fetches origin
bool LocalIsRemote ()
string Commit (RepoConfig Config)
string Push ()
bool SSHAuth ()
Credentials GenerateGitCredentials (string url, string usernameFromUrl, SupportedCredentialTypes types)
void AutoUpdateTimer_Elapsed (object sender, System.Timers.ElapsedEventArgs e)
void UpdateLiveSha (string newSha)
Private Attributes
SecurityIdentifier TheDroidsWereLookingFor
object authLock = new object()
string LastSeenUser = null
readonly SecurityIdentifier ServiceSID = WindowsIdentity.GetCurrent().User
const string ByondDirectory = "BYOND"
const string StagingDirectory = "BYOND_staged"
const string StagingDirectoryInner = "BYOND_staged/byond"
const string RevisionDownloadPath = "BYONDRevision.zip"
const string VersionFile = "/byond_version.dat"
const string ByondRevisionsURL = "https://secure.byond.com/download/build/{0}/{0}.{1}_byond.zip"
const string ByondLatestURL = "https://secure.byond.com/download/build/LATEST/"
const string ByondConfigDir = "BYOND_staged/BYOND/cfg"
const string ByondDDConfig = "/daemon.txt"
const string ByondNoPromptTrustedMode = "trusted-check 0"
TGByondStatus updateStat = TGByondStatus.Idle
object ByondLock = new object()
string lastError
Thread RevisionStaging
IList< ITGChatProvider > ChatProviders
object ChatLock = new object()
const string StaticDirs = "Static"
const string StaticBackupDir = "Static_BACKUP"
const string LibMySQLFile = "/libmysql.dll"
const string GameDir = "Game"
const string GameDirA = GameDir + "/A"
const string GameDirB = GameDir + "/B"
const string GameDirLive = GameDir + "/Live"
const string LiveFile = "/TestLive.lk"
const string ADirTest = GameDirA + LiveFile
const string BDirTest = GameDirB + LiveFile
const string LiveDirTest = GameDirLive + LiveFile
const string InterfaceDLLName = "TGServiceInterface.dll"
object CompilerLock = new object()
TGCompilerStatus compilerCurrentStatus
string lastCompilerError
Thread CompilerThread
bool compilationCancellationRequestation = false
bool canCancelCompilation = false
bool silentCompile = false
bool UpdateStaged = false
object configLock = new object()
const string DiagnosticsDir = "Diagnostics"
const string ResourceDiagnosticsDir = DiagnosticsDir + "/Resources"
const int DDHangStartTime = 60
const int DDBadStartTime = 10
Process Proc
PerformanceCounter pcpu
object watchdogLock = new object()
Thread DDWatchdog
TGDreamDaemonStatus currentStatus
string CurrentDDLog
ushort currentPort = 0
object restartLock = new object()
bool RestartInProgress = false
TGDreamDaemonSecurity StartingSecurity
ShutdownRequestPhase AwaitingShutdown
bool disposedValue = false
object topicLock = new object()
const int CommsKeyLen = 64
string serviceCommsKey
readonly Version MinAPIVersion = new Version("3.1.0.0")
readonly Version MaxAPIVersion = new Version("3.1.0.99")
Version GameAPIVersion
const string SCHardReboot = "hard_reboot"
const string SCGracefulShutdown = "graceful_shutdown"
const string SCWorldAnnounce = "world_announce"
const string SCListCustomCommands = "list_custom_commands"
const string SCAPICompat = "api_compat"
const string SCPlayerCount = "client_count"
const string SRKillProcess = "killme"
const string SRIRCBroadcast = "irc"
const string SRIRCAdminChannelMessage = "send2irc"
const string SRWorldReboot = "worldreboot"
const string SRAPIVersion = "api_ver"
const string CCPHelpText = "help_text"
const string CCPAdminOnly = "admin_only"
const string CCPRequiredParameters = "required_parameters"
List< Command > ServerChatCommands
const string EventFolder = "EventHandlers/"
const string RepoPath = "Repository"
const string RepoTGS3SettingsPath = RepoPath + "/TGS3.json"
const string CachedTGS3SettingsPath = "TGS3.json"
const string RepoErrorUpToDate = "Already up to date!"
const string SSHPushRemote = "ssh_push_target"
const string RepoKeyDir = "RepoKey/"
const string PrivateKeyPath = RepoKeyDir + "private_key.txt"
const string PublicKeyPath = RepoKeyDir + "public_key.txt"
const string PRJobFile = "prtestjob.json"
const string LiveTrackingBranch = "___TGSLiveCommitTrackingBranch"
const string CommitMessage = "Automatic changelog compile, [ci skip]"
object RepoLock = new object()
bool RepoBusy = false
bool Cloning = false
Repository Repo
int currentProgress = -1
System.Timers.Timer autoUpdateTimer
Detailed Description
Definition at line 13 of file Administration.cs.
Member Enumeration Documentation
enum TGServerService.TGStationServer.ShutdownRequestPhase strong private
Enumerator
None
Requested
Pinged
Definition at line 15 of file DreamDaemon.cs.
         {
             None,
             Requested,
             Pinged,
         }
enum TGServerService.TGStationServer.SymbolicLink strong private
Enumerator
File
Directory
Definition at line 17 of file Compiler.cs.
         {
             File = 0,
             Directory = 1
         }
Constructor & Destructor Documentation
TGServerService.TGStationServer.TGStationServer ()
Definition at line 17 of file InterfaceBase.cs.
References TGServerService.TGStationServer.FindTheDroidsWereLookingFor(), TGServerService.TGStationServer.InitByond(), TGServerService.TGStationServer.InitChat(), TGServerService.TGStationServer.InitCompiler(), TGServerService.TGStationServer.InitDreamDaemon(), and TGServerService.TGStationServer.InitRepo().
         {
             FindTheDroidsWereLookingFor();
             InitChat();
             InitRepo();
             InitByond();
             InitCompiler();
             InitDreamDaemon();
         }
Member Function Documentation
bool TGServerService.TGStationServer.ApplyStagedUpdate ()
Definition at line 258 of file Byond.cs.
References TGServerService.TGStationServer.compilerCurrentStatus, TGServerService.TGStationServer.CompilerLock, TGServerService.Program.DeleteDirectory(), TGServerService.TGStationServer.GetVersion(), and TGServerService.TGStationServer.SendMessage().
Referenced by TGServerService.TGStationServer.Start(), and TGServerService.TGStationServer.UpdateToVersionImpl().
         {
             lock (CompilerLock)
             {
                 if (compilerCurrentStatus == TGCompilerStatus.Compiling)
                     return false;
                 lock (ByondLock)
                 {
                     if (updateStat != TGByondStatus.Staged)
                         return false;
                     updateStat = TGByondStatus.Updating;
                 }
                 try
                 {
                     Program.DeleteDirectory(ByondDirectory);
                     Directory.Move(StagingDirectoryInner, ByondDirectory);
                     Program.DeleteDirectory(StagingDirectory);
                     lastError = null;
                     SendMessage("BYOND: Update completed!", ChatMessageType.DeveloperInfo);
                     TGServerService.WriteInfo(String.Format("BYOND update {0} completed!", GetVersion(TGByondVersion.Installed)), TGServerService.EventID.BYONDUpdateComplete);
                     return true;
                 }
                 catch (Exception e)
                 {
                     lastError = e.ToString();
                     SendMessage("BYOND: Update failed!", ChatMessageType.DeveloperInfo);
                     TGServerService.WriteError("BYOND update failed!", TGServerService.EventID.BYONDUpdateFail);
                     return false;
                 }
                 finally
                 {
                     lock(ByondLock) {
                         updateStat = TGByondStatus.Idle;
                     }
                 }
             }
         }
bool TGServerService.TGStationServer.Autostart ()
Check if the watchdog will start when the service starts
Returns
if autostart is enabled, otherwise
Implements TGServiceInterface.ITGDreamDaemon.
Definition at line 524 of file DreamDaemon.cs.
         {
             return Properties.Settings.Default.DDAutoStart;
         }
ulong TGServerService.TGStationServer.AutoUpdateInterval ()
Get the current autoupdate interval
Returns
The current auto update interval or 0 if it's disabled
Implements TGServiceInterface.ITGRepository.
Definition at line 1218 of file Repository.cs.
         {
             return Properties.Settings.Default.AutoUpdateInterval;
         }
void TGServerService.TGStationServer.AutoUpdateTimer_Elapsed (object sender, System.Timers.ElapsedEventArgs e) private
Definition at line 1223 of file Repository.cs.
References TGServerService.TGStationServer.Compile(), and TGServerService.TGStationServer.UpdateImpl().
Referenced by TGServerService.TGStationServer.InitRepo().
         {
             if (UpdateImpl(true, false) == null)
             {
                 Compile(true);
             }
         }
void TGServerService.TGStationServer.BackupAndDeleteStaticDirectory () private
Definition at line 317 of file Repository.cs.
References TGServerService.Program.CopyDirectory(), TGServerService.Program.DeleteDirectory(), TGServerService.TGStationServer.StaticBackupDir, and TGServerService.TGStationServer.StaticDirs.
Referenced by TGServerService.TGStationServer.Clone(), and TGServerService.TGStationServer.RecreateStaticFolder().
         {
             if (Directory.Exists(StaticDirs))
             {
                 int count = 1;
                 string path = Path.GetDirectoryName(StaticBackupDir);
                 string newFullPath = StaticBackupDir;
                 while (File.Exists(newFullPath) || Directory.Exists(newFullPath))
                 {
                     string tempDirName = string.Format("{0}({1})", StaticBackupDir, count++);
                     newFullPath = Path.Combine(path, tempDirName);
                 }
                 Program.CopyDirectory(StaticDirs, newFullPath);
             }
             Program.DeleteDirectory(StaticDirs);
         }
bool TGServerService.TGStationServer.BusyCheckNoLock () private
Definition at line 59 of file Byond.cs.
Referenced by TGServerService.TGStationServer.UpdateToVersion().
         {
             switch (updateStat)
             {
                 default:
                 case TGByondStatus.Starting:
                 case TGByondStatus.Downloading:
                 case TGByondStatus.Staging:
                 case TGByondStatus.Updating:
                     return true;
                 case TGByondStatus.Idle:
                 case TGByondStatus.Staged:
                     return false;
             }
         }
string TGServerService.TGStationServer.Cancel ()
Cancels the current compilation
Returns
on success, error message on failure
Implements TGServiceInterface.ITGCompiler.
Definition at line 618 of file Compiler.cs.
         {
             lock (CompilerLock)
             {
                 if (compilerCurrentStatus != TGCompilerStatus.Compiling)
                     return "Invalid state for cancellation!";
                 compilationCancellationRequestation = true;
                 if (canCancelCompilation)
                     CompilerThread.Abort();
                 else
                     return "Compilation will be cancelled when the repo copy is complete";
                 return null;
             }
         }
string TGServerService.TGStationServer.CanStart ()
Check if a call to Start will fail. Of course, be aware of race conditions with other interfaces
Returns
The error that would occur, otherwise
Implements TGServiceInterface.ITGDreamDaemon.
Definition at line 382 of file DreamDaemon.cs.
References TGServerService.TGStationServer.CanStartImpl().
         {
             lock (watchdogLock)
             {
                 return CanStartImpl();
             }
         }
string TGServerService.TGStationServer.CanStartImpl () private
Definition at line 390 of file DreamDaemon.cs.
References TGServerService.TGStationServer.GameDirLive, and TGServerService.TGStationServer.GetVersion().
Referenced by TGServerService.TGStationServer.CanStart(), TGServerService.TGStationServer.Start(), and TGServerService.TGStationServer.StartImpl().
         {
             if (GetVersion(TGByondVersion.Installed) == null)
                 return "Byond is not installed!";
             var DMB = GameDirLive + "/" + Properties.Settings.Default.ProjectName + ".dmb";
             if (!File.Exists(DMB))
                 return String.Format("Unable to find {0}!", DMB);
             return null;
         }
void TGServerService.TGStationServer.ChatConnectivityCheck () private
Reconnect servers that are enabled and disconnected
Definition at line 258 of file Chat.cs.
References TGServerService.ITGChatProvider.Connected(), and TGServerService.ITGChatProvider.Reconnect().
Referenced by TGServerService.TGStationServer.HandleCommand().
         {
             foreach (TGChatProvider I in Enum.GetValues(typeof(TGChatProvider)))
                 if(!Connected(I))
                     Reconnect(I);
         }
void TGServerService.TGStationServer.ChatProvider_OnChatMessage (ITGChatProvider ChatProvider, string speaker, string channel, string message, bool isAdmin, bool isAdminChannel) private
Definition at line 131 of file Chat.cs.
References TGServerService.ChatCommand.CommandInfo, TGServiceInterface.Command.DoRun(), TGServiceInterface.Command.OutputProcVar, and TGServerService.ITGChatProvider.SendMessageDirect().
         {
             var splits = message.Trim().Split(' ');
             if (splits.Length == 1 && splits[0] == "")
             {
                 ChatProvider.SendMessageDirect("Hi!", channel);
                 return;
             }
             var asList = new List<string>(splits);
             Command.OutputProcVar.Value = (m) => ChatProvider.SendMessageDirect(m, channel);
             ChatCommand.CommandInfo.Value = new CommandInfo()
             {
                 IsAdmin = isAdmin,
                 IsAdminChannel = isAdminChannel,
                 Speaker = speaker,
                 Server = this,
             };
             TGServerService.WriteInfo(String.Format("Chat Command from {0} ({2}): {1}", speaker, String.Join(" ", asList), channel), TGServerService.EventID.ChatCommand);
             if (ServerChatCommands == null)
                 LoadServerChatCommands();
             new RootChatCommand(ServerChatCommands).DoRun(asList);
         }
override bool TGServerService.TGStationServer.CheckAccessCore (OperationContext operationContext) protected
Definition at line 80 of file Administration.cs.
References TGServerService.TGStationServer.ServiceSID.
         {
             var contract = operationContext.EndpointDispatcher.ContractName;
             if (contract == typeof(ITGConnectivity).Name)   //always allow connectivity checks
                 return true;
             var windowsIdent = operationContext.ServiceSecurityContext.WindowsIdentity;
             if (contract == typeof(ITGInterop).Name)    //only allow the same user the service is running as to use interop, because that's what DD is running as
                 return windowsIdent.User == ServiceSID;
             var wp = new WindowsPrincipal(windowsIdent);
             //first allow admins
             var authSuccess = wp.IsInRole(WindowsBuiltInRole.Administrator);
             //if we're not an admin, check that we aren't trying to access the admin interface
             if (!authSuccess && operationContext.EndpointDispatcher.ContractName != typeof(ITGAdministration).Name && TheDroidsWereLookingFor != null)
                 authSuccess = wp.IsInRole(new SecurityIdentifier(Properties.Settings.Default.AuthorizedGroupSID));
             lock (authLock)
             {
                 var user = windowsIdent.Name;
                 if (LastSeenUser != user)
                 {
                     LastSeenUser = user;
                     TGServerService.WriteAccess(user, authSuccess);
                 }
             }
             return authSuccess;
         }
bool TGServerService.TGStationServer.CheckAPIVersionConstraints () private
Definition at line 153 of file Interop.cs.
References TGServerService.TGStationServer.MaxAPIVersion.
Referenced by TGServerService.TGStationServer.HandleCommand(), and TGServerService.TGStationServer.SendTopic().
         {
             return !(GameAPIVersion == null || GameAPIVersion < MinAPIVersion || GameAPIVersion > MaxAPIVersion);
         }
string TGServerService.TGStationServer.Checkout (string objectName)
Hard checks out the passed object name
Parameters
objectName The branch, commit, or tag to checkout
Returns
on success, error message on failure
Implements TGServiceInterface.ITGRepository.
Definition at line 502 of file Repository.cs.
References TGServerService.TGStationServer.Fetch(), TGServerService.TGStationServer.HandleCheckoutProgress(), TGServerService.TGStationServer.LoadRepo(), TGServerService.TGStationServer.ResetNoLock(), TGServerService.TGStationServer.SendMessage(), and TGServerService.TGStationServer.UpdateSubmodules().
         {
             if (sha == LiveTrackingBranch)
                 return "I'm sorry Dave, I'm afraid I can't do that...";
             lock (RepoLock)
             {
                 var result = LoadRepo();
                 if (result != null)
                     return result;
                 SendMessage("REPO: Checking out object: " + sha, ChatMessageType.DeveloperInfo);
                 try
                 {
                     if (Repo.Branches[sha] == null)
                     {
                         //see if origin has the branch
                         result = Fetch();
                         var trackedBranch = Repo.Branches[String.Format("origin/{0}", sha)];
                         if (trackedBranch != null)
{
                             var newBranch = Repo.CreateBranch(sha, trackedBranch.Tip);
                             //track it
                             Repo.Branches.Update(newBranch, b => b.TrackedBranch = trackedBranch.CanonicalName);
                         }
                         else if (result != null)
                             return result;
                     }
                     var Opts = new CheckoutOptions()
                     {
                         CheckoutModifiers = CheckoutModifiers.Force,
                         OnCheckoutProgress = HandleCheckoutProgress,
                     };
                     Commands.Checkout(Repo, sha, Opts);
                     var res = ResetNoLock(null);
                     UpdateSubmodules();
                     SendMessage("REPO: Checkout complete!", ChatMessageType.DeveloperInfo);
                     TGServerService.WriteInfo("Repo checked out " + sha, TGServerService.EventID.RepoCheckout);
                     return res;
                 }
                 catch (Exception e)
                 {
                     SendMessage("REPO: Checkout failed!", ChatMessageType.DeveloperInfo);
                     TGServerService.WriteWarning(String.Format("Repo checkout of {0} failed: {1}", sha, e.ToString()), TGServerService.EventID.RepoCheckoutFail);
                     return e.ToString();
                 }
             }
         }
int TGServerService.TGStationServer.CheckoutProgress ()
Gets the progress of repository operations, not all operations are supported
Returns
A value between 0 and 100 inclusive representing the progress of the current operation or -1 if the operation cannot be monitored
Implements TGServiceInterface.ITGRepository.
Definition at line 184 of file Repository.cs.
References TGServerService.TGStationServer.currentProgress.
         {
             return currentProgress;
         }
void TGServerService.TGStationServer.CleanByondStaging () private
Definition at line 39 of file Byond.cs.
References TGServerService.Program.DeleteDirectory().
Referenced by TGServerService.TGStationServer.DisposeByond(), TGServerService.TGStationServer.InitByond(), and TGServerService.TGStationServer.UpdateToVersionImpl().
         {
             //linger not
             if (File.Exists(RevisionDownloadPath))
                 File.Delete(RevisionDownloadPath);
             Program.DeleteDirectory(StagingDirectory);
         }
void TGServerService.TGStationServer.CleanGameFolder () private
Definition at line 139 of file Compiler.cs.
Referenced by TGServerService.TGStationServer.InitializeImpl(), and TGServerService.TGStationServer.MoveServer().
         {
             if (Directory.Exists(Path.Combine(GameDirA, InterfaceDLLName)))
                 Directory.Delete(Path.Combine(GameDirA, InterfaceDLLName));
             if (Directory.Exists(Path.Combine(GameDirB, InterfaceDLLName)))
                 Directory.Delete(Path.Combine(GameDirB, InterfaceDLLName));
             if (Directory.Exists(GameDirLive))
                 Directory.Delete(GameDirLive);
         }
void TGServerService.TGStationServer.CleanGameFolderList (string GameDir, IList< string > theList) private
Definition at line 128 of file Compiler.cs.
         {
             foreach (var I in theList)
             {
                 var the_path = Path.Combine(GameDir, I);
                 if (Directory.Exists(the_path))
                     Directory.Delete(the_path);
             }
         }
void TGServerService.TGStationServer.Clone (object twostrings) private
Definition at line 249 of file Repository.cs.
References TGServerService.TGStationServer.BackupAndDeleteStaticDirectory(), TGServerService.TGStationServer.configLock, TGServerService.Program.DeleteDirectory(), TGServerService.TGStationServer.DeletePRList(), TGServerService.TGStationServer.DisableGarbageCollectionNoLock(), TGServerService.TGStationServer.DisposeRepo(), TGServerService.TGStationServer.GenerateGitCredentials(), TGServerService.TGStationServer.HandleCheckoutProgress(), TGServerService.TGStationServer.HandleTransferProgress(), TGServerService.TGStationServer.InitialConfigureRepository(), TGServerService.TGStationServer.LoadRepo(), and TGServerService.TGStationServer.SendMessage().
Referenced by TGServerService.TGStationServer.Setup().
         {
             //busy flag set by caller
             var ts = (TwoStrings)twostrings;
             var RepoURL = ts.a;
             var BranchName = ts.b;
             try
             {
                 SendMessage(String.Format("REPO: {2} started: Cloning {0} branch of {1} ...", BranchName, RepoURL, Repository.IsValid(RepoPath) ? "Full reset" : "Setup"), ChatMessageType.DeveloperInfo);
                 try
                 {
                     DisposeRepo();
                     Program.DeleteDirectory(RepoPath);
                     DeletePRList();
                     lock (configLock)
                     {
                         BackupAndDeleteStaticDirectory();
                     }
                     var Opts = new CloneOptions()
                     {
                         BranchName = BranchName,
                         RecurseSubmodules = true,
                         OnTransferProgress = HandleTransferProgress,
                         OnCheckoutProgress = HandleCheckoutProgress,
                         CredentialsProvider = GenerateGitCredentials,
                     };
                     Repository.Clone(RepoURL, RepoPath, Opts);
                     currentProgress = -1;
                     LoadRepo();
                     DisableGarbageCollectionNoLock();
                     //create an ssh remote for pushing
                     Repo.Network.Remotes.Add(SSHPushRemote, RepoURL.Replace("git://", "ssh://").Replace("https://", "ssh://"));
                     InitialConfigureRepository();
                     SendMessage("REPO: Clone complete!", ChatMessageType.DeveloperInfo);
                     TGServerService.WriteInfo("Repository {0}:{1} successfully cloned", TGServerService.EventID.RepoClone);
                 }
                 finally
                 {
                     currentProgress = -1;
                 }
             }
             catch (Exception e)
             {
                 SendMessage("REPO: Setup failed!", ChatMessageType.DeveloperInfo);
                 TGServerService.WriteWarning(String.Format("Failed to clone {2}:{0}: {1}", BranchName, e.ToString(), RepoURL), TGServerService.EventID.RepoCloneFail);
             }
             finally
             {
                 lock (RepoLock)
                 {
                     RepoBusy = false;
                     Cloning = false;
                 }
             }
         }
string TGServerService.TGStationServer.Commit (RepoConfig Config) private
Definition at line 1005 of file Repository.cs.
References TGServerService.TGStationServer.DeletePRList(), TGServerService.TGStationServer.LoadRepo(), TGServerService.TGStationServer.MakeSig(), and TGServerService.TGStationServer.RepoConfig.PathsToStage.
Referenced by TGServerService.TGStationServer.SynchronizePush().
         {
             lock (RepoLock)
             {
                 var result = LoadRepo();
                 if (result != null)
                     return result;
                 try
                 {
                     // Stage the file
                     foreach(var I in Config.PathsToStage)
                         Commands.Stage(Repo, I);
                     if (Repo.RetrieveStatus().Staged.Count() == 0)   //nothing to commit
                         return null;
                     // Create the committer's signature and commit
                     var authorandcommitter = MakeSig();
                     // Commit to the repository
                     TGServerService.WriteInfo(String.Format("Commit {0} created from changelogs", Repo.Commit(CommitMessage, authorandcommitter, authorandcommitter)), TGServerService.EventID.RepoCommit);
                     DeletePRList();
                     return null;
                 }
                 catch (Exception e)
                 {
                     TGServerService.WriteError("Repo commit failed: " + e.ToString(), TGServerService.EventID.RepoCommitFail);
                     return e.ToString();
                 }
             }
         }
bool TGServerService.TGStationServer.Compile (bool silent = false)
Does all the necessary actions to take the revision currently in the repository and compile it to be run on the next server reboot. Requires BYOND to be set up and the GetStatus to return TGCompilerStatus.Initialized. Runs asyncronously
Parameters
silent If no message for compilation start will be printed
Returns
if the operation began, if it could not start
Implements TGServiceInterface.ITGCompiler.
Definition at line 585 of file Compiler.cs.
References TGServerService.TGStationServer.CompileImpl().
Referenced by TGServerService.TGStationServer.AutoUpdateTimer_Elapsed().
         {
             lock (CompilerLock)
             {
                 if (compilerCurrentStatus != TGCompilerStatus.Initialized)
                     return false;
                 silentCompile = silent;
                 lastCompilerError = null;
                 compilerCurrentStatus = TGCompilerStatus.Compiling;
                 CompilerThread = new Thread(new ThreadStart(CompileImpl));
                 CompilerThread.Start();
             }
             return true;
         }
string TGServerService.TGStationServer.CompileError ()
Returns the error message of the last operation. Reading this will clear the stored value
Returns
the error message of the last operation if it failed or if it succeeded
Implements TGServiceInterface.ITGCompiler.
Definition at line 70 of file Compiler.cs.
References TGServerService.TGStationServer.lastCompilerError.
         {
             lock (CompilerLock)
             {
                 var err = lastCompilerError;
                 lastCompilerError = null;
                 return err;
             }
         }
void TGServerService.TGStationServer.CompileImpl () private
Definition at line 294 of file Compiler.cs.
References TGServerService.TGStationServer.ByondDirectory, TGServerService.Program.CopyDirectory(), TGServerService.TGStationServer.CreateBackup(), TGServerService.TGStationServer.CreateSymlink(), TGServerService.TGStationServer.currentStatus, TGServerService.TGStationServer.DaemonStatus(), TGServerService.Program.DeleteDirectory(), TGServerService.TGStationServer.GetHead(), TGServerService.TGStationServer.GetStagingDir(), TGServerService.TGStationServer.GetVersion(), TGServerService.TGStationServer.InterfaceDLLName, TGServerService.TGStationServer.IsInitialized(), TGServerService.TGStationServer.PostcompileHook(), TGServerService.TGStationServer.PrecompileHook(), TGServerService.TGStationServer.PRJobFile, TGServerService.TGStationServer.Proc, TGServerService.TGStationServer.ProjectName(), TGServerService.TGStationServer.RepoBusy, TGServerService.TGStationServer.RepoConfigsMatch(), TGServerService.TGStationServer.RepoLock, TGServerService.TGStationServer.RepoPath, TGServerService.TGStationServer.SendMessage(), TGServerService.TGStationServer.silentCompile, TGServerService.TGStationServer.UpdateLiveSha(), and TGServerService.TGStationServer.watchdogLock.
Referenced by TGServerService.TGStationServer.Compile(), and TGServerService.TGStationServer.InitializeImpl().
         {
             try
             {
                 if (GetVersion(TGByondVersion.Installed) == null)
                 {
                     lock (CompilerLock)
                     {
                         lastCompilerError = "BYOND not installed!";
                         compilerCurrentStatus = TGCompilerStatus.Initialized;
                         return;
                     }
                 }
                 if (!RepoConfigsMatch())
                 {
                     lock (CompilerLock)
                     {
                         lastCompilerError = "Repository TGS3.json does not match cached version! Please update the config appropriately!";
                         compilerCurrentStatus = IsInitialized();
                         return;
                     }
                 }
                 string resurrectee;
                 bool repobusy_check = false;
                 if (!Monitor.TryEnter(RepoLock))
                     repobusy_check = true;
                 if (!repobusy_check)
                 {
                     if (RepoBusy)
                         repobusy_check = true;
                     else
                         RepoBusy = true;
                     Monitor.Exit(RepoLock);
                 }
                 if (repobusy_check)
                 {
                     SendMessage("DM: Copy aborted, repo locked!", ChatMessageType.DeveloperInfo);
                     lock (CompilerLock)
                     {
                         lastCompilerError = "The repo could not be locked for copying";
                         compilerCurrentStatus = TGCompilerStatus.Initialized;   //still fairly valid
                         return;
                     }
                 }
                 string CurrentSha;
                 try
                 {
                     bool silent;
                     lock (CompilerLock)
                     {
                         silent = silentCompile;
                         silentCompile = false;
                     }
                     if (!silent)
                         SendMessage("DM: Compiling...", ChatMessageType.DeveloperInfo);
                     resurrectee = GetStagingDir();
                     var Config = new RepoConfig(false);
                     var deleteExcludeList = new List<string> { InterfaceDLLName };
                     deleteExcludeList.AddRange(Config.StaticDirectoryPaths);
                     deleteExcludeList.AddRange(Config.DLLPaths);
                     Program.DeleteDirectory(resurrectee, true, deleteExcludeList);
                     Directory.CreateDirectory(resurrectee + "/.git/logs");
                     foreach (var I in Config.StaticDirectoryPaths)
                     {
                         var the_path = Path.Combine(resurrectee, I);
                         if (!Directory.Exists(the_path))
                             CreateSymlink(Path.Combine(resurrectee, I), Path.Combine(StaticDirs, I));
                     }
                     foreach (var I in Config.DLLPaths)
                     {
                         var the_path = Path.Combine(resurrectee, I);
                         if (!File.Exists(the_path))
                             CreateSymlink(the_path, Path.Combine(StaticDirs, I));
                     }
                     if (!File.Exists(Path.Combine(resurrectee, InterfaceDLLName)))
                         CreateSymlink(Path.Combine(resurrectee, InterfaceDLLName), InterfaceDLLName);
                     deleteExcludeList.Add(".git");
                     Program.CopyDirectory(RepoPath, resurrectee, deleteExcludeList);
                     CurrentSha = GetHead(false, out string error);
                     //just the tip
                     const string GitLogsDir = "/.git/logs";
                     Program.CopyDirectory(RepoPath + GitLogsDir, resurrectee + GitLogsDir);
                     try
                     {
                         File.Copy(PRJobFile, resurrectee + Path.DirectorySeparatorChar + PRJobFile);
                     }
                     catch { }
                 }
                 finally
                 {
                     lock (RepoLock)
                     {
                         RepoBusy = false;
                     }
                 }
                 var res = CreateBackup();
                 if (res != null)
                     lock (CompilerLock)
                     {
                         lastCompilerError = res;
                         compilerCurrentStatus = TGCompilerStatus.Initialized;
                         return;
                     }
                 var dmeName = ProjectName() + ".dme";
                 var dmePath = resurrectee + "/" + dmeName;
                 if (!File.Exists(dmePath))
                 {
                     var errorMsg = String.Format("Could not find {0}!", dmeName);
                     SendMessage("DM: " + errorMsg, ChatMessageType.DeveloperInfo);
                     TGServerService.WriteError(errorMsg, TGServerService.EventID.DMCompileCrash);
                     lock (CompilerLock)
                     {
                         lastCompilerError = errorMsg;
                         compilerCurrentStatus = TGCompilerStatus.Initialized;
                         return;
                     }
                 }
                 if (!PrecompileHook())
                 {
                     lastCompilerError = "The precompile hook failed";
                     compilerCurrentStatus = TGCompilerStatus.Initialized;   //still fairly valid
                     TGServerService.WriteWarning("Precompile hook failed!", TGServerService.EventID.DMCompileError);
                     return;
                 }
                 using (var DM = new Process())  //will kill the process if the thread is terminated
                 {
                     DM.StartInfo.FileName = ByondDirectory + "/bin/dm.exe";
                     DM.StartInfo.Arguments = String.Format("-clean {0}", dmePath);
                     DM.StartInfo.RedirectStandardOutput = true;
                     DM.StartInfo.UseShellExecute = false;
                     var OutputList = new StringBuilder();
                     DM.OutputDataReceived += new DataReceivedEventHandler(
                         delegate (object sender, DataReceivedEventArgs e)
{
                             OutputList.Append(Environment.NewLine);
                             OutputList.Append(e.Data);
                         }
                     );
                     try
                     {
                         lock (CompilerLock)
{
                             if (compilationCancellationRequestation)
                                 return;
                             canCancelCompilation = true;
                         }
                         DM.Start();
                         DM.BeginOutputReadLine();
                         while (!DM.HasExited)
                             DM.WaitForExit(100);
                         DM.CancelOutputRead();
                         lock (CompilerLock)
{
                             canCancelCompilation = false;
                             compilationCancellationRequestation = false;
                         }
                     }
                     catch
                     {
                         if (!DM.HasExited)
{
                             DM.Kill();
                             DM.WaitForExit();
                         }
                         throw;
                     }
                     finally
                     {
                         lock (CompilerLock)
{
                             canCancelCompilation = false;
                         }
                     }
                     if (DM.ExitCode == 0)
                     {
                         lock (watchdogLock)
{
                             try
{
                                 //gotta go fast
                                 var online = currentStatus == TGDreamDaemonStatus.Online;
                                 if (online)
                                     Proc.Suspend();
                                 try
{
                                     if (Directory.Exists(GameDirLive))
                                         //these two lines should be atomic but this is the best we can do
                                         Directory.Delete(GameDirLive);
                                     CreateSymlink(GameDirLive, resurrectee);
                                 }
                                 finally
{
                                     if (online && !Proc.HasExited)
                                         Proc.Resume();
                                 }
                             }
                             finally
{
                                 if (currentStatus == TGDreamDaemonStatus.Online)
{
                                     try
{
                                         Proc.PriorityClass = ProcessPriorityClass.Normal;
                                     }
                                     catch { }
                                     Process.GetCurrentProcess().PriorityClass = ProcessPriorityClass.Normal;
                                     Thread.CurrentThread.Priority = ThreadPriority.Normal;
                                 }
                             }
                         }
                         var staged = DaemonStatus() != TGDreamDaemonStatus.Offline;
                         if (!PostcompileHook())
{
                             lastCompilerError = "The postcompile hook failed";
                             compilerCurrentStatus = TGCompilerStatus.Initialized;   //still fairly valid
                             TGServerService.WriteWarning("Postcompile hook failed!", TGServerService.EventID.DMCompileError);
                             return;
                         }
                         UpdateLiveSha(CurrentSha);
                         var msg = String.Format("Compile complete!{0}", !staged ? "" : " Server will update next round.");
                         SendMessage("DM: " + msg, ChatMessageType.DeveloperInfo);
                         TGServerService.WriteInfo(msg, TGServerService.EventID.DMCompileSuccess);
                         lock (CompilerLock)
{
                             if (staged)
                                 UpdateStaged = true;
                             lastCompilerError = null;
                             compilerCurrentStatus = TGCompilerStatus.Initialized;   //still fairly valid
                         }
                     }
                     else
                     {
                         SendMessage("DM: Compile failed!", ChatMessageType.DeveloperInfo); //Also happens for warnings
                         TGServerService.WriteWarning("Compile error: " + OutputList.ToString(), TGServerService.EventID.DMCompileError);
                         lock (CompilerLock)
{
                             lastCompilerError = "DM compile failure";
                             compilerCurrentStatus = TGCompilerStatus.Initialized;
                         }
                     }
                 }
             }
             catch (ThreadAbortException)
             {
                 return;
             }
             catch (Exception e)
             {
                 SendMessage("DM: Compiler thread crashed!", ChatMessageType.DeveloperInfo);
                 TGServerService.WriteError("Compile manager errror: " + e.ToString(), TGServerService.EventID.DMCompileCrash);
                 lock (CompilerLock)
                 {
                     lastCompilerError = e.ToString();
                     compilerCurrentStatus = TGCompilerStatus.Initialized;   //still fairly valid
                 }
             }
             finally
             {
                 lock (CompilerLock)
                 {
                     canCancelCompilation = false;
                     if (compilationCancellationRequestation)
                     {
                         compilerCurrentStatus = TGCompilerStatus.Initialized;
                         compilationCancellationRequestation = false;
                         SendMessage("DM: Compile cancelled!", ChatMessageType.DeveloperInfo);
                         TGServerService.WriteInfo("Compilation cancelled", TGServerService.EventID.DMCompileCancel);
                     }
                 }
             }
         }
bool TGServerService.TGStationServer.CompilerIdleNoLock () private
Definition at line 100 of file Compiler.cs.
Referenced by TGServerService.TGStationServer.Initialize(), and TGServerService.TGStationServer.Setup().
         {
             return compilerCurrentStatus == TGCompilerStatus.Uninitialized || compilerCurrentStatus == TGCompilerStatus.Initialized;
         }
bool TGServerService.TGStationServer.Connected (TGChatProvider providerType)
Checks connection status
Parameters
providerType The type of provider to check if connected
Returns
if connected, otherwise
Implements TGServiceInterface.ITGChat.
Definition at line 247 of file Chat.cs.
         {
             foreach (var I in ChatProviders)
                 if (I.ProviderInfo().Provider == providerType)
                     return I.Connected();
             return false;
         }
string TGServerService.TGStationServer.CreateBackup () private
Definition at line 654 of file Repository.cs.
References TGServerService.TGStationServer.LoadRepo().
Referenced by TGServerService.TGStationServer.CompileImpl().
         {
             try
             {
                 lock (RepoLock)
                 {
                     var res = LoadRepo();
                     if (res != null)
                         return res;
                     //Make sure we don't already have a backup at this commit
                     var HEAD = Repo.Head.Tip.Sha;
                     foreach (var T in Repo.Tags)
                         if (T.Target.Sha == HEAD)
                             return null;
                     var tagName = "TGS-Compile-Backup-" + DateTime.Now.ToString("yyyy-MM-dd--HH.mm.ss");
                     var tag = Repo.ApplyTag(tagName);
                     if (tag != null)
                     {
                         TGServerService.WriteInfo("Repo backup created at tag: " + tagName + " commit: " + HEAD, TGServerService.EventID.RepoBackupTag);
                         return null;
                     }
                     throw new Exception("Tag creation failed!");
                 }
             }
             catch (Exception e)
             {
                 TGServerService.WriteWarning(String.Format("Failed backup tag creation at commit {0}!", Repo.Head.Tip.Sha), TGServerService.EventID.RepoBackupTagFail);
                 return e.ToString();
             }
         }
static bool TGServerService.TGStationServer.CreateSymbolicLink (string lpSymlinkFileName, string lpTargetFileName, SymbolicLink dwFlags) private
Referenced by TGServerService.TGStationServer.CreateSymlink().
void TGServerService.TGStationServer.CreateSymlink (string link, string target) private
Definition at line 93 of file Compiler.cs.
References TGServerService.TGStationServer.CreateSymbolicLink().
Referenced by TGServerService.TGStationServer.CompileImpl(), TGServerService.TGStationServer.GetStagingDir(), and TGServerService.TGStationServer.InitializeImpl().
         {
             if (!CreateSymbolicLink(new DirectoryInfo(link).FullName, new DirectoryInfo(target).FullName, File.Exists(target) ? SymbolicLink.File : SymbolicLink.Directory))
                 throw new Exception(String.Format("Failed to create symlink from {0} to {1}! Error: {2}", target, link, Marshal.GetLastWin32Error()));
         }
TGByondStatus TGServerService.TGStationServer.CurrentStatus ()
Gets the current status of any BYOND updates
Returns
The current status of the byond updater
Implements TGServiceInterface.ITGByond.
Definition at line 76 of file Byond.cs.
References TGServerService.TGStationServer.updateStat.
Referenced by TGServerService.TGStationServer.Start().
         {
             lock (ByondLock)
             {
                 return updateStat;
             }
         }
TGDreamDaemonStatus TGServerService.TGStationServer.DaemonStatus ()
Gets the status of DreamDaemon
Returns
The appropriate TGDreamDaemonStatus
Implements TGServiceInterface.ITGDreamDaemon.
Definition at line 133 of file DreamDaemon.cs.
References TGServerService.TGStationServer.currentStatus.
Referenced by TGServerService.TGStationServer.CompileImpl(), TGServerService.TGStationServer.DisposeDreamDaemon(), TGServerService.TGStationServer.InitializeImpl(), TGServerService.TGStationServer.LoadServerChatCommands(), TGServerService.TGStationServer.Restart(), TGServerService.TGStationServer.SetSecurityLevel(), TGServerService.TGStationServer.Setup(), TGServerService.TGStationServer.StatusString(), and TGServerService.TGStationServer.UpdateToVersionImpl().
         {
             lock (watchdogLock)
             {
                 return currentStatus;
             }
         }
string TGServerService.TGStationServer.DeleteFile (string staticRelativePath, out bool unauthorized)
Deletes the target static file
Parameters
staticRelativePath The path from the Static dir. E.g. config/config.txt
unauthorized This will be true if error is set to a message that indicates the current user does not have access to the specified file
Returns
null on success, error message on failure
Implements TGServiceInterface.ITGConfig.
Definition at line 152 of file Config.cs.
References TGServerService.Program.DeleteDirectory(), and TGServerService.TGStationServer.StaticDirs.
         {
             try
             {
                 var path = StaticDirs + '/' + staticRelativePath;   //do not use path.combine or it will try and take the root
                 lock (configLock)
                 {
                     var di1 = new DirectoryInfo(StaticDirs);
                     var fi = new FileInfo(path);
                     var di2 = new DirectoryInfo(fi.Directory.FullName);
                     var good = false;
                     while (di2 != null)
                     {
                         if (di2.FullName == di1.FullName)
{
                             good = true;
                             break;
                         }
                         else di2 = di2.Parent;
                     }
                     if (!good)
                     {
                         unauthorized = false;
                         return "Cannot delete above static directories!";
                     }
                     if (fi.Exists)
                         File.Delete(path);
                     else if (Directory.Exists(path))
                         Program.DeleteDirectory(path);
                     TGServerService.CancelImpersonation();
                     TGServerService.WriteInfo("Delete of " + path, TGServerService.EventID.StaticDelete);
                     unauthorized = false;
                     return null;
                 }
             }
             catch (UnauthorizedAccessException e)
             {
                 //no need for the full stacktrace
                 unauthorized = true;
                 return e.Message;
             }
             catch (Exception e)
             {
                 unauthorized = false;
                 return e.ToString();
             }
         }
void TGServerService.TGStationServer.DeletePRList () private
Definition at line 739 of file Repository.cs.
Referenced by TGServerService.TGStationServer.Clone(), TGServerService.TGStationServer.Commit(), TGServerService.TGStationServer.Reset(), and TGServerService.TGStationServer.UpdateImpl().
         {
             if (File.Exists(PRJobFile))
                 try
                 {
                     File.Delete(PRJobFile);
                 }
                 catch (Exception e)
                 {
                     TGServerService.WriteError("Failed to delete PR list: " + e.ToString(), TGServerService.EventID.RepoPRListError);
                 }
         }
void TGServerService.TGStationServer.DisableGarbageCollectionNoLock () private
Definition at line 312 of file Repository.cs.
Referenced by TGServerService.TGStationServer.Clone(), and TGServerService.TGStationServer.InitRepo().
         {
             Repo.Config.Set("gc.auto", false);
         }
virtual void TGServerService.TGStationServer.Dispose (bool disposing) protected virtual
Definition at line 58 of file InterfaceBase.cs.
References TGServerService.TGStationServer.RunDisposals().
Referenced by TGServerService.TGServerService.OnStop().
         {
             if (!disposedValue)
             {
                 if (disposing)
                 {
                     RunDisposals();
                     // TODO: dispose managed state (managed objects).
                 }
                 // TODO: free unmanaged resources (unmanaged objects) and override a finalizer below.
                 // TODO: set large fields to null.
                 disposedValue = true;
             }
         }
void TGServerService.TGStationServer.Dispose ()
Definition at line 82 of file InterfaceBase.cs.
         {
             // Do not change this code. Put cleanup code in Dispose(bool disposing) above.
             Dispose(true);
             // TODO: uncomment the following line if the finalizer is overridden above.
             // GC.SuppressFinalize(this);
         }
void TGServerService.TGStationServer.DisposeByond () private
Definition at line 48 of file Byond.cs.
References TGServerService.TGStationServer.CleanByondStaging().
Referenced by TGServerService.TGStationServer.RunDisposals().
         {
             lock (ByondLock)
             {
                 if (RevisionStaging != null)
                     RevisionStaging.Abort();
                 CleanByondStaging();
             }
         }
void TGServerService.TGStationServer.DisposeChat () private
Definition at line 158 of file Chat.cs.
References TGServiceInterface.Helpers.EncryptData().
Referenced by TGServerService.TGStationServer.RunDisposals().
         {
             var infosList = new List<IList<string>>();
             foreach (var ChatProvider in ChatProviders)
             {
                 infosList.Add(ChatProvider.ProviderInfo().DataFields);
                 ChatProvider.Dispose();
             }
             ChatProviders = null;
             var rawdata = new JavaScriptSerializer().Serialize(infosList);
             var Config = Properties.Settings.Default;
             Config.ChatProviderData = Helpers.EncryptData(rawdata, out string entrp);
             Config.ChatProviderEntropy = entrp;
         }
void TGServerService.TGStationServer.DisposeCompiler () private
Definition at line 81 of file Compiler.cs.
References TGServerService.TGStationServer.InitCompiler().
Referenced by TGServerService.TGStationServer.RunDisposals().
         {
             lock (CompilerLock)
             {
                 if (CompilerThread == null || !CompilerThread.IsAlive)
                     return;
                 CompilerThread.Abort(); //this will safely kill dm
                 InitCompiler(); //also cleanup
             }
         }
void TGServerService.TGStationServer.DisposeDreamDaemon () private
Definition at line 101 of file DreamDaemon.cs.
References TGServerService.TGStationServer.DaemonStatus(), TGServerService.TGStationServer.SendMessage(), TGServerService.TGStationServer.Stop(), TGServerService.TGStationServer.WorldAnnounce(), and TGServerService.TGStationServer.WriteCurrentDDLog().
Referenced by TGServerService.TGStationServer.RunDisposals().
         {
             var Detach = Properties.Settings.Default.ReattachToDD;
             bool RenameLog = false;
             if (DaemonStatus() == TGDreamDaemonStatus.Online)
             {
                 if (!Detach)
                 {
                     WorldAnnounce("Server service stopped");
                     Thread.Sleep(1000);
                 }
                 else
                 {
                     RenameLog = CurrentDDLog != null;
                     SendMessage("DD: Detaching watch dog for update!", ChatMessageType.WatchdogInfo);
                     WriteCurrentDDLog("Service updating! Splitting diagnostics...");
                 }
             }
             else if (Detach)
                 Properties.Settings.Default.ReattachToDD = false;
             Stop();
             if(pcpu != null)
                 pcpu.Dispose();
             if (RenameLog)
                 try
                 {
                     File.Move(Path.Combine(ResourceDiagnosticsDir, CurrentDDLog), Path.Combine(ResourceDiagnosticsDir, "SU-" + CurrentDDLog));
                 }
                 catch { }
         }
void TGServerService.TGStationServer.DisposeRepo () private
Definition at line 208 of file Repository.cs.
Referenced by TGServerService.TGStationServer.Clone(), TGServerService.TGStationServer.MoveServer(), and TGServerService.TGStationServer.RunDisposals().
         {
             if (Repo != null)
             {
                 Repo.Dispose();
                 Repo = null;
             }
         }
bool TGServerService.TGStationServer.EventHandlerExists (string eventName) private
Definition at line 17 of file PreactionHandler.cs.
References TGServerService.TGStationServer.GetPath().
Referenced by TGServerService.TGStationServer.HandleEvent().
         {
             return File.Exists(GetPath(eventName));
         }
bool TGServerService.TGStationServer.Exists ()
Check if the repository is valid, if not Setup(string, string) must be called
Returns
if the repository is valid, otherwise
Implements TGServiceInterface.ITGRepository.
Definition at line 218 of file Repository.cs.
Referenced by TGServerService.TGStationServer.GenerateChangelogImpl(), TGServerService.TGStationServer.InitializeImpl(), and TGServerService.TGStationServer.InitRepo().
         {
             lock (RepoLock)
             {
                 return !Cloning && Repository.IsValid(RepoPath);
             }
         }
string TGServerService.TGStationServer.Fetch () private
Fetches origin
Returns
null on success, error message on failure
Definition at line 970 of file Repository.cs.
References TGServerService.TGStationServer.GenerateFetchOptions().
Referenced by TGServerService.TGStationServer.Checkout(), TGServerService.TGStationServer.LocalIsRemote(), and TGServerService.TGStationServer.UpdateImpl().
         {
             try
             {
                 string logMessage = "";
                 var R = Repo.Network.Remotes["origin"];
                 IEnumerable<string> refSpecs = R.FetchRefSpecs.Select(X => X.Specification);
                 Commands.Fetch(Repo, R.Name, refSpecs, GenerateFetchOptions(), logMessage);
                 return null;
             }
             catch (Exception e)
             {
                 return e.ToString();
             }
         }
string TGServerService.TGStationServer.FindTheDroidsWereLookingFor (string search = null) private
Definition at line 52 of file Administration.cs.
Referenced by TGServerService.TGStationServer.SetAuthorizedGroup(), and TGServerService.TGStationServer.TGStationServer().
         {
             //find the group that is authorized to use the tools
             var pc = new PrincipalContext(ContextType.Machine);
             var config = Properties.Settings.Default;
             var groupName = search ?? config.AuthorizedGroupSID;
             if (String.IsNullOrWhiteSpace(groupName))
                 return null;
             var gp = GroupPrincipal.FindByIdentity(pc, search != null ? IdentityType.Name : IdentityType.Sid, groupName);
             if (gp == null)
             {
                 if (search != null)
                     //try again with all types
                     gp = GroupPrincipal.FindByIdentity(pc, search);
                 if (gp == null)
                     return null;
             }
             TheDroidsWereLookingFor = gp.Sid;
             if (search != null)
             {
                 config.AuthorizedGroupSID = TheDroidsWereLookingFor.Value;
                 config.Save();
             }
             return gp.Name;
         }
void TGServerService.TGStationServer.GenCommsKey () private
Definition at line 224 of file Interop.cs.
Referenced by TGServerService.TGStationServer.StartImpl().
         {
             var charsToRemove = new string[] { "!", "@", "#", "$", "%", "^", "&", "*", "(", ")", "_", "-", "+", "=", "[", "{", "]", "}", ";", ":", "<", ">", "|", ".", "/", "?" };
             serviceCommsKey = String.Empty;
             do {
                 var tmp = Membership.GeneratePassword(CommsKeyLen, 0);
                 foreach (var c in charsToRemove)
                     tmp = tmp.Replace(c, String.Empty);
                 serviceCommsKey += tmp;
             } while (serviceCommsKey.Length < CommsKeyLen);
             serviceCommsKey = serviceCommsKey.Substring(0, CommsKeyLen);
             TGServerService.WriteInfo("Service Comms Key set to: " + serviceCommsKey, TGServerService.EventID.CommsKeySet);
         }
string TGServerService.TGStationServer.GenerateChangelog (out string error)
Updates the html changelog
Parameters
error on success, error on failure
Returns
The output of the python script
Implements TGServiceInterface.ITGRepository.
Definition at line 1091 of file Repository.cs.
References TGServerService.TGStationServer.GenerateChangelogImpl().
         {
             return GenerateChangelogImpl(out error);
         }
string TGServerService.TGStationServer.GenerateChangelogImpl (out string error, bool recurse = false)
Definition at line 1097 of file Repository.cs.
References TGServerService.TGStationServer.Exists(), and TGServerService.TGStationServer.RepoConfig.RepoConfig().
Referenced by TGServerService.TGStationServer.GenerateChangelog().
         {
             var RConfig = new RepoConfig(false);
             if (RConfig == null)
             {
                 error = null;
                 return "Error loading changelog config!";
             }
             if (!RConfig.ChangelogSupport)
             {
                 error = null;
                 return null;
             }
             string ChangelogPy = RConfig.PathToChangelogPy;
             if (!Exists())
             {
                 error = "Repo does not exist!";
                 return null;
             }
             lock (RepoLock)
             {
                 if (RepoBusy)
                 {
                     error = "Repo is busy!";
                     return null;
                 }
                 if (!File.Exists(Path.Combine(RepoPath, ChangelogPy)))
                 {
                     error = "Missing changelog generation script!";
                     return null;
                 }
                 var Config = Properties.Settings.Default;
                 var PythonFile = Config.PythonPath + "/python.exe";
                 if (!File.Exists(PythonFile))
                 {
                     error = "Cannot locate python!";
                     return null;
                 }
                 try
                 {
                     string result;
                     int exitCode;
                     using (var python = new Process())
                     {
                         python.StartInfo.FileName = PythonFile;
                         python.StartInfo.Arguments = String.Format("{0} {1}", ChangelogPy, RConfig.ChangelogPyArguments);
                         python.StartInfo.UseShellExecute = false;
                         python.StartInfo.WorkingDirectory = new DirectoryInfo(RepoPath).FullName;
                         python.StartInfo.RedirectStandardOutput = true;
                         python.Start();
                         using (StreamReader reader = python.StandardOutput)
{
                             result = reader.ReadToEnd();
                         }
                         python.WaitForExit();
                         exitCode = python.ExitCode;
                     }
                     if (exitCode != 0)
                     {
                         if (recurse || RConfig.PipDependancies.Count == 0)
{
                             error = "Script failed!";
                             return result;
                         }
                         //update pip deps and try again
                         string PipFile = Config.PythonPath + "/scripts/pip.exe";
                         foreach(var I in RConfig.PipDependancies)
                             using (var pip = new Process())
{
                                 pip.StartInfo.FileName = PipFile;
                                 pip.StartInfo.Arguments = "install " + I;
                                 pip.StartInfo.UseShellExecute = false;
                                 pip.StartInfo.RedirectStandardOutput = true;
                                 pip.Start();
                                 using (StreamReader reader = pip.StandardOutput)
{
                                     result += "\r\n---BEGIN-PIP-OUTPUT---\r\n" + reader.ReadToEnd();
                                 }
                                 pip.WaitForExit();
                                 if (pip.ExitCode != 0)
{
                                     error = "Script and pip failed!";
                                     return result;
                                 }
                             }
                         //and recurse
                         return GenerateChangelogImpl(out error, true);
                     }
                     error = null;
                     TGServerService.WriteInfo("Changelog generated" + error, TGServerService.EventID.RepoChangelog);
                     return result;
                 }
                 catch (Exception e)
                 {
                     error = e.ToString();
                     TGServerService.WriteWarning("Changelog generation failed: " + error, TGServerService.EventID.RepoChangelogFail);
                     return null;
                 }
             }
         }
FetchOptions TGServerService.TGStationServer.GenerateFetchOptions () private
Definition at line 956 of file Repository.cs.
References TGServerService.TGStationServer.GenerateGitCredentials(), and TGServerService.TGStationServer.HandleTransferProgress().
Referenced by TGServerService.TGStationServer.Fetch(), and TGServerService.TGStationServer.MergePullRequestImpl().
         {
             return new FetchOptions()
             {
                 CredentialsProvider = GenerateGitCredentials,
                 OnTransferProgress = HandleTransferProgress,
                 Prune = true,
             };
         }
Credentials TGServerService.TGStationServer.GenerateGitCredentials (string url, string usernameFromUrl, SupportedCredentialTypes types) private
Definition at line 1073 of file Repository.cs.
References TGServerService.TGStationServer.PrivateKeyPath, and TGServerService.TGStationServer.PublicKeyPath.
Referenced by TGServerService.TGStationServer.Clone(), TGServerService.TGStationServer.GenerateFetchOptions(), and TGServerService.TGStationServer.Push().
         {
             var user = usernameFromUrl ?? "git";
             if (types == SupportedCredentialTypes.UsernameQuery)
                 return new UsernameQueryCredentials()
                 {
                     Username = user,
                 };
             return new SshUserKeyCredentials()
             {
                 Username = user,
                 PrivateKey = PrivateKeyPath,
                 PublicKey = PublicKeyPath,
                 Passphrase = "",
             };
         }
string TGServerService.TGStationServer.GetBranch (out string error)
Gets the name of the current branch
Parameters
error on success, error message on failure
Returns
The name of the current branch on success, on failure
Implements TGServiceInterface.ITGRepository.
Definition at line 457 of file Repository.cs.
References TGServerService.TGStationServer.GetShaOrBranch().
         {
             return GetShaOrBranch(out error, true, false);
         }
string TGServerService.TGStationServer.GetCommitterEmail ()
Gets the email of the configured git committer
Returns
The email of the configured git committer
Implements TGServiceInterface.ITGRepository.
Definition at line 929 of file Repository.cs.
         {
             lock (RepoLock)
             {
                 return Properties.Settings.Default.CommitterEmail;
             }
         }
string TGServerService.TGStationServer.GetCommitterName ()
Gets the name of the configured git committer
Returns
The name of the configured git committer
Implements TGServiceInterface.ITGRepository.
Definition at line 911 of file Repository.cs.
         {
             lock (RepoLock)
             {
                 return Properties.Settings.Default.CommitterName;
             }
         }
string TGServerService.TGStationServer.GetCurrentAuthorizedGroup ()
Returns the name of the windows group allowed to use the service other than administrator
Implements TGServiceInterface.ITGAdministration.
Definition at line 22 of file Administration.cs.
         {
             try
             {
                 if (TheDroidsWereLookingFor == null)
                     return "ADMIN";
                 var pc = new PrincipalContext(ContextType.Machine);
                 return GroupPrincipal.FindByIdentity(pc, IdentityType.Sid, TheDroidsWereLookingFor.Value).Name;
             }
             catch
             {
                 return null;
             }
         }
IDictionary<string, IDictionary<string, string> > TGServerService.TGStationServer.GetCurrentPRList () private
Definition at line 753 of file Repository.cs.
Referenced by TGServerService.TGStationServer.MergedPullRequests(), and TGServerService.TGStationServer.MergePullRequestImpl().
         {
             if (!File.Exists(PRJobFile))
                 return new Dictionary<string, IDictionary<string, string>>();
             var rawdata = File.ReadAllText(PRJobFile);
             var Deserializer = new JavaScriptSerializer();
             return Deserializer.Deserialize<IDictionary<string, IDictionary<string, string>>>(rawdata);
         }
string TGServerService.TGStationServer.GetError ()
Check the last update error. Checking this will clear the value
Returns
The last update error, if any. otherwise.
Implements TGServiceInterface.ITGByond.
Definition at line 85 of file Byond.cs.
References TGServerService.TGStationServer.lastError.
         {
             lock (ByondLock)
             {
                 var error = lastError;
                 lastError = null;
                 return error;
             }
         }
string TGServerService.TGStationServer.GetHead (bool useTracked, out string error)
Gets the sha of the current HEAD
Parameters
useTracked If set to true and HEAD is currently a branch, will instead return the sha of the tracked remote branch if it exists
error on success, error message on failure
Returns
The sha of the current HEAD on success, on failure
Implements TGServiceInterface.ITGRepository.
Definition at line 451 of file Repository.cs.
References TGServerService.TGStationServer.GetShaOrBranch().
Referenced by TGServerService.TGStationServer.CompileImpl().
         {
             return GetShaOrBranch(out error, false, useTracked);
         }
string TGServerService.TGStationServer.GetPath (string eventName) private
Definition at line 12 of file PreactionHandler.cs.
Referenced by TGServerService.TGStationServer.EventHandlerExists(), and TGServerService.TGStationServer.HandleEvent().
         {
             return string.Format("{0}{1}.bat", EventFolder, eventName);
         }
string TGServerService.TGStationServer.GetRemote (out string error)
Gets the url of the current origin
Parameters
error on success, error message on failure
Returns
The url of the current origin on success, on failure
Implements TGServiceInterface.ITGRepository.
Definition at line 463 of file Repository.cs.
References TGServerService.TGStationServer.LoadRepo().
         {
             try
             {
                 var res = LoadRepo();
                 if (res != null)
                 {
                     error = res;
                     return null;
                 }
                 error = null;
                 return Repo.Network.Remotes["origin"].Url;
             }
             catch (Exception e)
             {
                 error = e.ToString();
                 return null;
             }
         }
string TGServerService.TGStationServer.GetShaOrBranch (out string error, bool branch, bool tracked) private
Definition at line 423 of file Repository.cs.
References TGServerService.TGStationServer.LoadRepo().
Referenced by TGServerService.TGStationServer.GetBranch(), and TGServerService.TGStationServer.GetHead().
         {
             lock (RepoLock)
             {
                 var result = LoadRepo();
                 if (result != null)
                 {
                     error = result;
                     return null;
                 }
                 try
                 {
                     error = null;
                     if (tracked && Repo.Head.TrackedBranch != null)
                         return Repo.Head.TrackedBranch.Tip.Sha;
                     return branch ? Repo.Head.FriendlyName : Repo.Head.Tip.Sha;
                 }
                 catch (Exception e)
                 {
                     error = e.ToString();
                     return null;
                 }
             }
         }
string TGServerService.TGStationServer.GetStagingDir () private
Definition at line 237 of file Compiler.cs.
References TGServerService.TGStationServer.CreateSymlink(), and TGServerService.TGStationServer.InvertDirectory().
Referenced by TGServerService.TGStationServer.CompileImpl().
         {
             string TheDir;
             if (!Directory.Exists(GameDirLive))
                 TheDir = GameDirA;
             else
             {
                 File.Create(LiveDirTest).Close();
                 try
                 {
                     if (File.Exists(ADirTest))
                         TheDir = GameDirA;
                     else if (File.Exists(BDirTest))
                         TheDir = GameDirB;
                     else
                         throw new Exception("Unable to determine current live directory!");
                 }
                 finally
                 {
                     File.Delete(LiveDirTest);
                 }
                 TheDir = InvertDirectory(TheDir);
             }
             //So TheDir is what the Live folder is NOT pointing to
             //Now we need to check if DD is running that folder and swap it if necessary
             var rsclock = TheDir + "/" + Properties.Settings.Default.ProjectName + ".rsc.lk";
             if (File.Exists(rsclock))
             {
                 try
                 {
                     File.Delete(rsclock);
                 }
                 catch   //held open by byond
                 {
                     //This means there is a staged update waiting to be applied, we have to unstage it before we can work
                     Directory.Delete(GameDirLive);
                     CreateSymlink(GameDirLive, TheDir);
                     return InvertDirectory(TheDir);
                 }
             }
             return TheDir;
         }
TGCompilerStatus TGServerService.TGStationServer.GetStatus ()
Returns the current compiler status
Returns
The current compiler status
Implements TGServiceInterface.ITGCompiler.
Definition at line 61 of file Compiler.cs.
References TGServerService.TGStationServer.compilerCurrentStatus.
         {
             lock (CompilerLock)
             {
                 return compilerCurrentStatus;
             }
         }
string TGServerService.TGStationServer.GetVersion (TGByondVersion type)
Get the currently installed version as a string formatted as Major.Minor
Parameters
type The type of version to retrieve
Returns
if no version is detected, the version string otherwise
Implements TGServiceInterface.ITGByond.
Definition at line 96 of file Byond.cs.
References TGServerService.TGStationServer.ByondDirectory, and TGServerService.TGStationServer.VersionFile.
Referenced by TGServerService.TGStationServer.ApplyStagedUpdate(), TGServerService.TGStationServer.CanStartImpl(), and TGServerService.TGStationServer.CompileImpl().
         {
             try
             {
                 lock (ByondLock)
                 {
                     if (type == TGByondVersion.Latest)
                     {
                         //get the latest version from the website
                         HttpWebRequest request = (HttpWebRequest)WebRequest.Create(ByondLatestURL);
                         var results = new List<string>();
                         using (HttpWebResponse response = (HttpWebResponse)request.GetResponse())
{
                             using (StreamReader reader = new StreamReader(response.GetResponseStream()))
{
                                 string html = reader.ReadToEnd();
                                 Regex regex = new Regex("\\\"([^\"]*)\\\"");
                                 MatchCollection matches = regex.Matches(html);
                                 foreach (Match match in matches)
                                     if (match.Success && match.Value.Contains("_byond.exe"))
                                         results.Add(match.Value.Replace("\"", "").Replace("_byond.exe", ""));
                             }
                         }
                         results.Sort();
                         results.Reverse();
                         return results.Count > 0 ? results[0] : null;
                     }
                     else
                     {
                         string DirToUse = type == TGByondVersion.Staged ? StagingDirectoryInner : ByondDirectory;
                         if (Directory.Exists(DirToUse))
{
                             string file = DirToUse + VersionFile;
                             if (File.Exists(file))
                                 return File.ReadAllText(file);
                         }
                     }
                     return null;
                 }
             }
             catch (Exception e)
             {
                 return "Error: " + e.ToString();
             }
         }
void TGServerService.TGStationServer.HandleCheckoutProgress (string path, int completedSteps, int totalSteps) private
Definition at line 236 of file Repository.cs.
Referenced by TGServerService.TGStationServer.Checkout(), TGServerService.TGStationServer.Clone(), and TGServerService.TGStationServer.MergeBranch().
         {
             currentProgress = (int)(((float)completedSteps / totalSteps) * 100);
         }
void TGServerService.TGStationServer.HandleCommand (string cmd) private
Definition at line 64 of file Interop.cs.
References TGServerService.TGStationServer.ChatConnectivityCheck(), TGServerService.TGStationServer.CheckAPIVersionConstraints(), TGServerService.TGStationServer.CompilerLock, TGServerService.TGStationServer.KillMe(), TGServerService.TGStationServer.SendCommand(), TGServerService.TGStationServer.SendMessage(), TGServerService.TGStationServer.UpdateStaged, TGServerService.TGStationServer.Version(), and TGServerService.TGStationServer.WriteCurrentDDLog().
Referenced by TGServerService.TGStationServer.InteropMessage().
         {
             var splits = new List<string>(cmd.Split(' '));
             cmd = splits[0];
             splits.RemoveAt(0);
             bool APIValid;
             lock (topicLock)
             {
                 APIValid = CheckAPIVersionConstraints();
             }
             if (!APIValid && cmd != SRAPIVersion)
                 return; //SPEAK THE LANGUAGE!!!
             switch (cmd)
             {
                 case SRIRCBroadcast:
                     SendMessage("GAME: " + String.Join(" ", splits), ChatMessageType.GameInfo);
                     break;
                 case SRKillProcess:
                     KillMe();
                     break;
                 case SRIRCAdminChannelMessage:
                     SendMessage("RELAY: " + String.Join(" ", splits), ChatMessageType.AdminInfo);
                     break;
                 case SRWorldReboot:
                     TGServerService.WriteInfo("World Rebooted", TGServerService.EventID.WorldReboot);
                     WriteCurrentDDLog("World rebooted");
                     ServerChatCommands = null;
                     ChatConnectivityCheck();
                     lock (CompilerLock)
                     {
                         if (UpdateStaged)
{
                             UpdateStaged = false;
                             lock (topicLock)
{
                                 GameAPIVersion = null;  //needs updating
                             }
                             TGServerService.WriteInfo("Staged update applied", TGServerService.EventID.ServerUpdateApplied);
                         }
                     }
                     break;
                 case SRAPIVersion:
                     lock (topicLock)
                     {
                         try
{
                             GameAPIVersion = new Version(splits[0]);
                             if (!CheckAPIVersionConstraints())
                                 throw new Exception();
                         }
                         catch
{
                             TGServerService.WriteWarning(String.Format("API version of the game ({0}) is incompatible with the current supported API versions (Min: {1}. Max: {2}). Interop disabled.", splits.Count > 1 ? splits[1] : "NULL", MinAPIVersion, MaxAPIVersion), TGServerService.EventID.APIVersionMismatch);
                             GameAPIVersion = null;
                             break;
                         }
                     }
                     //This needs to be done asyncronously otherwise DD won't be able to process it, because it's waiting for THIS THREAD to return
                     ThreadPool.QueueUserWorkItem(_ => SendCommand(SCAPICompat));
                     break;
             }
         }
bool TGServerService.TGStationServer.HandleEvent (string eventName) private
Definition at line 22 of file PreactionHandler.cs.
References TGServerService.TGStationServer.EventHandlerExists(), and TGServerService.TGStationServer.GetPath().
Referenced by TGServerService.TGStationServer.PostcompileHook(), and TGServerService.TGStationServer.PrecompileHook().
         {
             if (!EventHandlerExists(eventName))
             {
                 // We don't need a handler, so let's just fail silently.
                 return true;
             }
             var process = new Process
             {
                 StartInfo = new ProcessStartInfo
                 {
                     FileName = GetPath(eventName),
                     UseShellExecute = false,
                     RedirectStandardOutput = true,
                     RedirectStandardError = true,
                     CreateNoWindow = true
                 }
             };
             process.Start();
             process.WaitForExit();
             var stdout = process.StandardOutput.ReadToEnd();
             var stderr = process.StandardError.ReadToEnd();
             TGServerService.WriteInfo(
                 String.Format("Preaction Event: {0} @ {1} ran. Stdout:\n{2}\nStderr:\n{3}", eventName, GetPath(eventName), stdout, stderr),
                 process.ExitCode == 0 ? TGServerService.EventID.PreactionEvent : TGServerService.EventID.PreactionFail
            );
             return process.ExitCode == 0 ? true : false;
         }
bool TGServerService.TGStationServer.HandleTransferProgress (TransferProgress progress) private
Definition at line 228 of file Repository.cs.
Referenced by TGServerService.TGStationServer.Clone(), and TGServerService.TGStationServer.GenerateFetchOptions().
         {
             currentProgress = (int)(((float)progress.ReceivedObjects / progress.TotalObjects) * 100) / 2;
             currentProgress += (int)(((float)progress.IndexedObjects / progress.TotalObjects) * 100) / 2;
             return true;
         }
void TGServerService.TGStationServer.InitByond () private
Definition at line 34 of file Byond.cs.
References TGServerService.TGStationServer.CleanByondStaging().
Referenced by TGServerService.TGStationServer.TGStationServer().
         {
             CleanByondStaging();
         }
void TGServerService.TGStationServer.InitChat ()
Definition at line 96 of file Chat.cs.
References TGServerService.ITGChatProvider.Connect(), and TGServerService.ITGChatProvider.OnChatMessage.
Referenced by TGServerService.TGStationServer.TGStationServer().
         {
             var infos = InitProviderInfos();
             ChatProviders = new List<ITGChatProvider>(infos.Count);
             foreach (var info in infos)
             {
                 ITGChatProvider ChatProvider;
                 try
                 {
                     switch (info.Provider)
                     {
                         case TGChatProvider.Discord:
                             ChatProvider = new TGDiscordChatProvider(info);
                             break;
                         case TGChatProvider.IRC:
                             ChatProvider = new TGIRCChatProvider(info);
                             break;
                         default:
                             TGServerService.WriteError(String.Format("Invalid chat provider: {0}", info.Provider), TGServerService.EventID.InvalidChatProvider);
                             continue;
                     }
                 }
                 catch (Exception e)
                 {
                     TGServerService.WriteError(String.Format("Failed to start chat provider {0}! Error: {1}", info.Provider, e.ToString()), TGServerService.EventID.ChatProviderStartFail);
                     continue;
                 }
                 ChatProvider.OnChatMessage += ChatProvider_OnChatMessage;
                 var res = ChatProvider.Connect();
                 if (res != null)
                     TGServerService.WriteWarning(String.Format("Unable to connect to chat! Provider {0}, Error: {1}", ChatProvider.GetType().ToString(), res), TGServerService.EventID.ChatConnectFail);
                 ChatProviders.Add(ChatProvider);
             }
         }
void TGServerService.TGStationServer.InitCompiler () private
Definition at line 53 of file Compiler.cs.
References TGServerService.TGStationServer.IsInitialized().
Referenced by TGServerService.TGStationServer.DisposeCompiler(), and TGServerService.TGStationServer.TGStationServer().
         {
             if(File.Exists(LiveDirTest))
                 File.Delete(LiveDirTest);
             compilerCurrentStatus = IsInitialized();
         }
void TGServerService.TGStationServer.InitDreamDaemon () private
Definition at line 44 of file DreamDaemon.cs.
References TGServerService.TGStationServer.ByondDirectory, TGServerService.TGStationServer.GameAPIVersion, TGServerService.TGStationServer.SendMessage(), TGServerService.TGStationServer.serviceCommsKey, TGServerService.TGStationServer.Start(), TGServerService.TGStationServer.Version(), and TGServerService.TGStationServer.Watchdog().
Referenced by TGServerService.TGStationServer.TGStationServer().
         {
             Directory.CreateDirectory(DiagnosticsDir);
             Directory.CreateDirectory(ResourceDiagnosticsDir);
             var Reattach = Properties.Settings.Default.ReattachToDD;
             if (Reattach)
                 try
                 {
                     Proc = Process.GetProcessById(Properties.Settings.Default.ReattachPID);
                     if (Proc == null)
                         throw new Exception("GetProcessById returned null!");
                     TGServerService.WriteInfo("Reattached to running DD process!", TGServerService.EventID.DDReattachSuccess);
                     ThreadPool.QueueUserWorkItem(_ =>
                     {
                         Thread.Sleep(5000);
                         SendMessage("DD: Update complete. Watch dog reactivated...", ChatMessageType.WatchdogInfo);
                     });
                     //start wd
                     RestartInProgress = true;
                     currentPort = Properties.Settings.Default.ReattachPort;
                     serviceCommsKey = Properties.Settings.Default.ReattachCommsKey;
                     try
                     {
                         GameAPIVersion = new Version(Properties.Settings.Default.ReattachAPIVersion);
                     }
                     catch { }
                     currentStatus = TGDreamDaemonStatus.Online;
                     DDWatchdog = new Thread(new ThreadStart(Watchdog));
                     DDWatchdog.Start();
                 }
                 catch (Exception e)
                 {
                     TGServerService.WriteError(String.Format("Failed to reattach to DreamDaemon! PID: {0}. Exception: {1}", Properties.Settings.Default.ReattachPID, e.ToString()), TGServerService.EventID.DDReattachFail);
                 }
                 finally
                 {
                     Properties.Settings.Default.ReattachToDD = false;
                     Properties.Settings.Default.Save();
                 }
             if (Proc == null)
                 Proc = new Process();
             Proc.StartInfo.FileName = ByondDirectory + "/bin/dreamdaemon.exe";
             Proc.StartInfo.UseShellExecute = false;
             if (Reattach)
                 return;
             //autostart the server
             if (Properties.Settings.Default.DDAutoStart)
                 //break this off so we don't hold up starting the service
                 ThreadPool.QueueUserWorkItem( _ => { Start(); });
         }
void TGServerService.TGStationServer.InitialConfigureRepository () private
Definition at line 353 of file Repository.cs.
References TGServerService.Program.CopyDirectory(), TGServerService.Program.CopyFileForceDirectories(), TGServerService.TGStationServer.RepoConfig.RepoConfig(), TGServerService.TGStationServer.StaticDirs, TGServerService.TGStationServer.UpdateInterfaceDll(), and TGServerService.TGStationServer.UpdateTGS3Json().
Referenced by TGServerService.TGStationServer.Clone(), and TGServerService.TGStationServer.RecreateStaticFolder().
         {
             Directory.CreateDirectory(StaticDirs);
             UpdateInterfaceDll(false);
             UpdateTGS3Json();
             var Config = new RepoConfig(false); //RepoBusy is set if we're here
             foreach(var I in Config.StaticDirectoryPaths)
             {
                 try
                 {
                     var source = Path.Combine(RepoPath, I);
                     var dest = Path.Combine(StaticDirs, I);
                     if (Directory.Exists(source))
                         Program.CopyDirectory(source, dest);
                     else
                         Directory.CreateDirectory(dest);
                 }
                 catch
                 {
                     TGServerService.WriteWarning("Could not setup static directory: " + I, TGServerService.EventID.RepoConfigurationFail);
                 }
             }
             foreach(var I in Config.DLLPaths)
             {
                 try
                 {
                     var source = Path.Combine(RepoPath, I);
                     if (!File.Exists(source))
                     {
                         TGServerService.WriteWarning("Could not find DLL: " + I, TGServerService.EventID.RepoConfigurationFail);
                         continue;
                     }
                     var dest = Path.Combine(StaticDirs, I);
                     Program.CopyFileForceDirectories(source, dest, false);
                 }
                 catch
                 {
                     TGServerService.WriteWarning("Could not setup static DLL: " + I, TGServerService.EventID.RepoConfigurationFail);
                 }
             }
         }
bool TGServerService.TGStationServer.Initialize ()
Sets up the symlinks for hotswapping game code. This will reset everything in the Game folder. Requires the repository to be set up and locks it once the compilation stage starts. Runs asyncronously from this call
Returns
if the operation began, if it could not start
Implements TGServiceInterface.ITGCompiler.
Definition at line 106 of file Compiler.cs.
References TGServerService.TGStationServer.CompilerIdleNoLock(), and TGServerService.TGStationServer.InitializeImpl().
         {
             lock (CompilerLock)
             {
                 if (!CompilerIdleNoLock())
                     return false;
                 lastCompilerError = null;
                 compilerCurrentStatus = TGCompilerStatus.Initializing;
                 CompilerThread = new Thread(new ThreadStart(InitializeImpl));
                 CompilerThread.Start();
                 return true;
             }
         }
void TGServerService.TGStationServer.InitializeImpl ()
Definition at line 152 of file Compiler.cs.
References TGServerService.TGStationServer.CleanGameFolder(), TGServerService.TGStationServer.CompileImpl(), TGServerService.TGStationServer.CreateSymlink(), TGServerService.TGStationServer.DaemonStatus(), TGServerService.Program.DeleteDirectory(), TGServerService.TGStationServer.Exists(), TGServerService.TGStationServer.InterfaceDLLName, TGServerService.TGStationServer.IsInitialized(), TGServerService.TGStationServer.RepoConfigsMatch(), and TGServerService.TGStationServer.SendMessage().
Referenced by TGServerService.TGStationServer.Initialize().
         {
             try
             {
                 if (DaemonStatus() != TGDreamDaemonStatus.Offline)
                 {
                     lock (CompilerLock)
                     {
                         lastCompilerError = "Dream daemon must not be running";
                         compilerCurrentStatus = IsInitialized();
                         return;
                     }
                 }
                 if (!Exists()) //repo
                 {
                     lock (CompilerLock)
                     {
                         lastCompilerError = "Repository is not setup!";
                         compilerCurrentStatus = IsInitialized();
                         return;
                     }
                 }
                 if (!RepoConfigsMatch())
                 {
                     lock (CompilerLock)
                     {
                         lastCompilerError = "Repository TGS3.json does not match cached version! Please update the config appropriately!";
                         compilerCurrentStatus = IsInitialized();
                         return;
                     }
                 }
                 try
                 {
                     SendMessage("DM: Setting up symlinks...", ChatMessageType.DeveloperInfo);
                     CleanGameFolder();
                     Program.DeleteDirectory(GameDir);
                     Directory.CreateDirectory(GameDirA);
                     Directory.CreateDirectory(GameDirB);
                     var Config = new RepoConfig(false);
                     if (Config != null) {
                         foreach (var I in Config.StaticDirectoryPaths)
                             CreateSymlink(Path.Combine(GameDirA, I), Path.Combine(StaticDirs, I));
                         foreach (var I in Config.DLLPaths)
                             CreateSymlink(Path.Combine(GameDirA, I), Path.Combine(StaticDirs, I));
                     }
                     CreateSymlink(Path.Combine(GameDirA, InterfaceDLLName), InterfaceDLLName);
                     CreateSymlink(Path.Combine(GameDirB, InterfaceDLLName), InterfaceDLLName);
                     CreateSymlink(GameDirLive, GameDirA);
                     lock (CompilerLock)
                     {
                         compilerCurrentStatus = TGCompilerStatus.Compiling;
                         silentCompile = true;
                     }
                 }
                 catch (ThreadAbortException)
                 {
                     return;
                 }
                 catch (Exception e)
                 {
                     lock (CompilerLock)
                     {
                         SendMessage("DM: Setup failed!", ChatMessageType.DeveloperInfo);
                         lastCompilerError = e.ToString();
                         compilerCurrentStatus = TGCompilerStatus.Uninitialized;
                         return;
                     }
                 }
             }
             catch (ThreadAbortException)
             {
                 return;
             }
             CompileImpl();
         }
IList<TGChatSetupInfo> TGServerService.TGStationServer.InitProviderInfos () private
Definition at line 185 of file Chat.cs.
References TGServiceInterface.Helpers.DecryptData().
         {
             lock (ChatLock)
             {
                 var Config = Properties.Settings.Default;
                 var rawdata = Config.ChatProviderData;
                 if (rawdata == "NEEDS INITIALIZING")
                     return new List<TGChatSetupInfo>() { new TGIRCSetupInfo(), new TGDiscordSetupInfo() };
                 string plaintext;
                 try
                 {
                     plaintext = Helpers.DecryptData(rawdata, Config.ChatProviderEntropy);
                     var lists = new JavaScriptSerializer().Deserialize<List<List<string>>>(plaintext);
                     var output = new List<TGChatSetupInfo>(lists.Count);
                     var foundirc = 0;
                     var founddiscord = 0;
                     foreach (var l in lists)
                     {
                         var info = new TGChatSetupInfo(l);
                         if (info.Provider == TGChatProvider.Discord)
                             ++founddiscord;
                         else if (info.Provider == TGChatProvider.IRC)
                             ++foundirc;
                         output.Add(info);
                     }
                     if (foundirc != 1 || founddiscord != 1)
                         throw new Exception();
                     return output;
                 }
                 catch
                 {
                     Config.ChatProviderData = "NEEDS INITIALIZING";
                 }
             }
             //if we get here we want to retry
             return InitProviderInfos();
         }
void TGServerService.TGStationServer.InitRepo () private
Definition at line 147 of file Repository.cs.
References TGServerService.TGStationServer.autoUpdateTimer, TGServerService.TGStationServer.AutoUpdateTimer_Elapsed(), TGServerService.TGStationServer.DisableGarbageCollectionNoLock(), TGServerService.TGStationServer.Exists(), TGServerService.TGStationServer.LoadRepo(), TGServerService.TGStationServer.SetAutoUpdateInterval(), and TGServerService.TGStationServer.UpdateInterfaceDll().
Referenced by TGServerService.TGStationServer.TGStationServer().
         {
             Directory.CreateDirectory(RepoKeyDir);
             if(Exists())
                 UpdateInterfaceDll(false);
             if(LoadRepo() == null)
                 DisableGarbageCollectionNoLock();
             //start the autoupdate timer
             autoUpdateTimer.Elapsed += AutoUpdateTimer_Elapsed;
             SetAutoUpdateInterval(Properties.Settings.Default.AutoUpdateInterval);
         }
bool TGServerService.TGStationServer.InteropMessage (string command)
Called from /world/ExportService(command)
Implements TGServiceInterface.ITGInterop.
Definition at line 239 of file Interop.cs.
References TGServerService.TGStationServer.HandleCommand().
         {
             try
             {
                 HandleCommand(command);
                 return true;
             }
             catch(Exception e)
             {
                 TGServerService.WriteWarning(String.Format("Handle command for \"{0}\" failed: {1}", command, e.ToString()), TGServerService.EventID.InteropCallException);
                 return false;
             }
         }
string TGServerService.TGStationServer.InvertDirectory (string gameDirectory) private
Definition at line 285 of file Compiler.cs.
References TGServerService.TGStationServer.GameDirA, and TGServerService.TGStationServer.GameDirB.
Referenced by TGServerService.TGStationServer.GetStagingDir().
         {
             if (gameDirectory == GameDirA)
                 return GameDirB;
             else
                 return GameDirA;
         }
TGCompilerStatus TGServerService.TGStationServer.IsInitialized () private
Definition at line 121 of file Compiler.cs.
Referenced by TGServerService.TGStationServer.CompileImpl(), TGServerService.TGStationServer.InitCompiler(), and TGServerService.TGStationServer.InitializeImpl().
         {
             if (File.Exists(GameDirLive + LibMySQLFile))    //its a good tell, jim
                 return TGCompilerStatus.Initialized;
             return TGCompilerStatus.Uninitialized;
         }
void TGServerService.TGStationServer.KillMe ()
Definition at line 189 of file DreamDaemon.cs.
References TGServerService.TGStationServer.Restart(), and TGServerService.TGStationServer.Stop().
Referenced by TGServerService.TGStationServer.HandleCommand().
         {
             bool DoRestart;
             lock (watchdogLock)
             {
                 DoRestart = AwaitingShutdown == ShutdownRequestPhase.None;
                 if (!DoRestart)
                     AwaitingShutdown = ShutdownRequestPhase.Pinged;
             }
             //Do this is a seperate thread or we'll kill this thread in the middle of rebooting
             if (DoRestart)
                 ThreadPool.QueueUserWorkItem(_ => { Restart(); });
             else
                 ThreadPool.QueueUserWorkItem(_ => { Stop(); });
         }
IDictionary<string, string> TGServerService.TGStationServer.ListBackups (out string error)
List the tagged commits of the repo at which compiles took place
Parameters
error on success, error message on failure
Returns
A IDictionary<TKey, TValue> of tag name -> commit on success, on failure
Implements TGServiceInterface.ITGRepository.
Definition at line 688 of file Repository.cs.
References TGServerService.TGStationServer.LoadRepo().
         {
             try
             {
                 lock (RepoLock)
                 {
                     error = LoadRepo();
                     if (error != null)
                         return null;
                     var res = new Dictionary<string, string>();
                     foreach (var T in Repo.Tags)
                         if (T.FriendlyName.Contains("TGS"))
                             res.Add(T.FriendlyName, T.Target.Sha);
                     return res;
                 }
             }
             catch (Exception e)
             {
                 error = e.ToString();
                 return null;
             }
         }
IList<string> TGServerService.TGStationServer.ListStaticDirectory (string subpath, out string error, out bool unauthorized)
Returns the file contents of the specified server directory Subdirectories will be prefixed with '/'
Parameters
subpath Subdirectory to enumerate, enumerates the root directory if null
error null on success, error message on failure
unauthorized This will be true if error is set to a message that indicates the current user does not have access to the specified file
Returns
A list of files in the enumerated static directory on success, null on failure
Implements TGServiceInterface.ITGConfig.
Definition at line 204 of file Config.cs.
References TGServerService.TGStationServer.StaticDirs.
         {
             try
             {
                 if (!Directory.Exists(StaticDirs))
                 {
                     error = null;
                     unauthorized = false;
                     return new List<string>();
                 }
                 DirectoryInfo dirToEnum = new DirectoryInfo(StaticDirs + '/' + subDir ?? "");   //do not use path.combine or it will try and take the root
                 var result = new List<string>();
                 foreach (var I in dirToEnum.GetFiles())
                     result.Add(I.Name);
                 foreach (var I in dirToEnum.GetDirectories())
                     result.Add('/' + I.Name);
                 error = null;
                 unauthorized = false;
                 return result;
             }
             catch (UnauthorizedAccessException e)
             {
                 //no need for the full stacktrace
                 error = e.Message;
                 unauthorized = true;
                 return null;
             }
             catch (Exception e)
             {
                 error = e.ToString();
                 unauthorized = false;
                 return null;
             }
         }
string TGServerService.TGStationServer.LiveSha ()
Definition at line 1255 of file Repository.cs.
References TGServerService.TGStationServer.LiveTrackingBranch.
         {
             var B = Repo.Branches[LiveTrackingBranch];
             return B != null ? B.Tip.Sha : "UNKNOWN";
         }
string TGServerService.TGStationServer.LoadRepo () private
Definition at line 190 of file Repository.cs.
Referenced by TGServerService.TGStationServer.Checkout(), TGServerService.TGStationServer.Clone(), TGServerService.TGStationServer.Commit(), TGServerService.TGStationServer.CreateBackup(), TGServerService.TGStationServer.GetRemote(), TGServerService.TGStationServer.GetShaOrBranch(), TGServerService.TGStationServer.InitRepo(), TGServerService.TGStationServer.ListBackups(), TGServerService.TGStationServer.LocalIsRemote(), TGServerService.TGStationServer.MergedPullRequests(), TGServerService.TGStationServer.MergePullRequestImpl(), TGServerService.TGStationServer.Push(), TGServerService.TGStationServer.RepoConfigsMatch(), TGServerService.TGStationServer.Reset(), TGServerService.TGStationServer.UpdateImpl(), and TGServerService.TGStationServer.UpdateLiveSha().
         {
             if (Repo != null)
                 return null;
             if (!Repository.IsValid(RepoPath))
                 return "Repository does not exist";
             try
             {
                 Repo = new Repository(RepoPath);
             }
             catch (Exception e)
             {
                 return e.ToString();
             }
             return null;
         }
void TGServerService.TGStationServer.LoadServerChatCommands () private
Definition at line 46 of file Interop.cs.
References TGServerService.TGStationServer.DaemonStatus(), and TGServerService.TGStationServer.SendCommand().
         {
             if (DaemonStatus() != TGDreamDaemonStatus.Online)
                 return;
             var json = SendCommand(SCListCustomCommands);
             if (String.IsNullOrWhiteSpace(json))
                 return;
             List<Command> tmp = new List<Command>();
             try
             {
                 foreach(var I in new JavaScriptSerializer().Deserialize<IDictionary<string, IDictionary<string, object>>>(json))
                     tmp.Add(new ServerChatCommand(I.Key, (string)I.Value[CCPHelpText], ((int)I.Value[CCPAdminOnly]) == 1, (int)I.Value[CCPRequiredParameters]));
                 ServerChatCommands = tmp;
             }
             catch { }
         }
bool TGServerService.TGStationServer.LocalIsRemote () private
Definition at line 986 of file Repository.cs.
References TGServerService.TGStationServer.Fetch(), and TGServerService.TGStationServer.LoadRepo().
Referenced by TGServerService.TGStationServer.Push(), and TGServerService.TGStationServer.SynchronizePush().
         {
             lock (RepoLock)
             {
                 if (LoadRepo() != null)
                     return false;
                 if (Fetch() != null)
                     return false;
                 try
                 {
                     return Repo.Head.IsTracking && Repo.Head.TrackedBranch.Tip.Sha == Repo.Head.Tip.Sha;
                 }
                 catch
                 {
                     return false;
                 }
             }
         }
Signature TGServerService.TGStationServer.MakeSig () private
Definition at line 732 of file Repository.cs.
Referenced by TGServerService.TGStationServer.Commit(), and TGServerService.TGStationServer.MergeBranch().
         {
             var Config = Properties.Settings.Default;
             return new Signature(new Identity(Config.CommitterName, Config.CommitterEmail), DateTimeOffset.Now);
         }
void TGServerService.TGStationServer.MemTrackTimer_Elapsed (object sender, ElapsedEventArgs e) private
Definition at line 367 of file DreamDaemon.cs.
References TGServerService.TGStationServer.WriteCurrentDDLog().
Referenced by TGServerService.TGStationServer.Watchdog().
         {
             ulong megamem;
             float cputime;
             lock (watchdogLock)
             {
                 cputime = pcpu.NextValue();
                 using (var pcm = new PerformanceCounter("Process", "Working Set - Private", Proc.ProcessName, true))
                     megamem = Convert.ToUInt64(pcm.NextValue()) / 1024;
             }
             var PercentCpuTime = (int)Math.Round((Decimal)cputime);
             WriteCurrentDDLog(String.Format("CPU: {1}% Memory: {0}MB", megamem, PercentCpuTime.ToString("D3")));
         }
string TGServerService.TGStationServer.MergeBranch (string branchname) private
Definition at line 550 of file Repository.cs.
References TGServerService.TGStationServer.HandleCheckoutProgress(), TGServerService.TGStationServer.MakeSig(), TGServerService.TGStationServer.RepoErrorUpToDate, TGServerService.TGStationServer.ResetNoLock(), and TGServerService.TGStationServer.SendMessage().
Referenced by TGServerService.TGStationServer.MergePullRequestImpl(), and TGServerService.TGStationServer.UpdateImpl().
         {
             var mo = new MergeOptions()
             {
                 OnCheckoutProgress = HandleCheckoutProgress
             };
             var Result = Repo.Merge(branchname, MakeSig());
             currentProgress = -1;
             switch (Result.Status)
             {
                 case MergeStatus.Conflicts:
                     ResetNoLock(null);
                     SendMessage("REPO: Merge conflicted, aborted.", ChatMessageType.DeveloperInfo);
                     return "Merge conflict occurred.";
                 case MergeStatus.UpToDate:
                     return RepoErrorUpToDate;
             }
             return null;
         }
IList<PullRequestInfo> TGServerService.TGStationServer.MergedPullRequests (out string error)
Get the currently merged pull requests. Note that switching branches will delete this list and switching back won't restore it
Parameters
error on success, error message on failure
Returns
A IList<T> of PullRequestInfo
Implements TGServiceInterface.ITGRepository.
Definition at line 883 of file Repository.cs.
References TGServerService.TGStationServer.GetCurrentPRList(), and TGServerService.TGStationServer.LoadRepo().
         {
             lock (RepoLock)
             {
                 var result = LoadRepo();
                 if (result != null)
                 {
                     error = result;
                     return null;
                 }
                 try
                 {
                     var PRRawData = GetCurrentPRList();
                     IList<PullRequestInfo> output = new List<PullRequestInfo>();
                     foreach (var I in GetCurrentPRList())
                         output.Add(new PullRequestInfo(Convert.ToInt32(I.Key), I.Value["author"], I.Value["title"], I.Value["commit"]));
                     error = null;
                     return output;
                 }
                 catch (Exception e)
                 {
                     error = e.ToString();
                     return null;
                 }
             }
         }
string TGServerService.TGStationServer.MergePullRequest (int PRnumber)
Merges the target pull request into the current branch if the remote is a github repository
Parameters
PRnumber The github pull request number in the remote repository
Returns
on success, error message on failure
Implements TGServiceInterface.ITGRepository.
Definition at line 771 of file Repository.cs.
References TGServerService.TGStationServer.MergePullRequestImpl().
         {
             return MergePullRequestImpl(PRNumber, false);
         }
string TGServerService.TGStationServer.MergePullRequestImpl (int PRNumber, bool impliedUpdate) private
Definition at line 775 of file Repository.cs.
References TGServerService.TGStationServer.GenerateFetchOptions(), TGServerService.TGStationServer.GetCurrentPRList(), TGServerService.TGStationServer.LoadRepo(), TGServerService.TGStationServer.MergeBranch(), TGServerService.TGStationServer.ResetNoLock(), TGServerService.TGStationServer.SendMessage(), TGServerService.TGStationServer.SetCurrentPRList(), and TGServerService.TGStationServer.UpdateSubmodules().
Referenced by TGServerService.TGStationServer.MergePullRequest().
         {
             lock (RepoLock)
             {
                 var result = LoadRepo();
                 if (result != null)
                     return result;
                 SendMessage(String.Format("REPO: {1}erging PR #{0}...", PRNumber, impliedUpdate ? "Test m" : "M"), ChatMessageType.DeveloperInfo);
                 result = ResetNoLock(null);
                 if (result != null)
                     return result;
                 try
                 {
                     //only supported with github
                     var remoteUrl = Repo.Network.Remotes["origin"].Url;
                     if (!remoteUrl.Contains("github.com"))
                         return "Only supported with Github based repositories.";
                     var Refspec = new List<string>();
                     var PRBranchName = String.Format("pr-{0}", PRNumber);
                     var LocalBranchName = String.Format("pull/{0}/headrefs/heads/{1}", PRNumber, PRBranchName);
                     Refspec.Add(String.Format("pull/{0}/head:{1}", PRNumber, PRBranchName));
                     var logMessage = "";
                     var branch = Repo.Branches[LocalBranchName];
                     if (branch != null)
                         //Need to delete the branch first in case of rebase
                         Repo.Branches.Remove(branch);
                     Commands.Fetch(Repo, "origin", Refspec, GenerateFetchOptions(), logMessage);  //shitty api has no failure state for this
                     currentProgress = -1;
                     var Config = Properties.Settings.Default;
                     branch = Repo.Branches[LocalBranchName];
                     if (branch == null)
                     {
                         SendMessage("REPO: PR could not be fetched. Does it exist?", ChatMessageType.DeveloperInfo);
                         return String.Format("PR #{0} could not be fetched. Does it exist?", PRNumber);
                     }
                     //so we'll know if this fails
                     var Result = MergeBranch(LocalBranchName);
                     if (Result == null)
                         try
{
                             UpdateSubmodules();
                         }
                         catch (Exception e)
{
                             Result = e.ToString();
                         }
                     if (Result == null)
                     {
                         TGServerService.WriteInfo(String.Format("Merged pull request #{0}", PRNumber), TGServerService.EventID.RepoPRMerge);
                         try
{
                             var CurrentPRs = GetCurrentPRList();
                             var PRNumberString = PRNumber.ToString();
                             CurrentPRs.Remove(PRNumberString);
                             var newPR = new Dictionary<string, string>();
                             //do some excellent remote fuckery here to get the api page
                             var prAPI = remoteUrl;
                             prAPI = prAPI.Replace("/.git", "");
                             prAPI = prAPI.Replace(".git", "");
                             prAPI = prAPI.Replace("github.com", "api.github.com/repos");
                             prAPI += "/pulls/" + PRNumberString + ".json";
                             string json;
                             using (var wc = new WebClient())
{
                                 wc.Headers.Add("user-agent", "TGStationServerService");
                                 json = wc.DownloadString(prAPI);
                             }
                             var Deserializer = new JavaScriptSerializer();
                             var dick = Deserializer.DeserializeObject(json) as IDictionary<string, object>;
                             var user = dick["user"] as IDictionary<string, object>;
                             newPR.Add("commit", branch.Tip.Sha);
                             newPR.Add("author", (string)user["login"]);
                             newPR.Add("title", (string)dick["title"]);
                             CurrentPRs.Add(PRNumberString, newPR);
                             SetCurrentPRList(CurrentPRs);
                         }
                         catch (Exception e)
{
                             TGServerService.WriteError("Failed to update PR list", TGServerService.EventID.RepoPRListError);
                             return "PR Merged, JSON update failed: " + e.ToString();
                         }
                     }
                     return Result;
                 }
                 catch (Exception E)
                 {
                     SendMessage("REPO: PR merge failed!", ChatMessageType.DeveloperInfo);
                     TGServerService.WriteWarning(String.Format("Failed to merge pull request #{0}: {1}", PRNumber, E.ToString()), TGServerService.EventID.RepoPRMergeFail);
                     return E.ToString();
                 }
             }
         }
string TGServerService.TGStationServer.MoveServer (string new_location)
Moves the entire server installation, requires no operations to be running
Implements TGServiceInterface.ITGAdministration.
Definition at line 130 of file Administration.cs.
References TGServerService.TGStationServer.ByondLock, TGServerService.TGStationServer.CleanGameFolder(), TGServerService.TGStationServer.compilerCurrentStatus, TGServerService.TGStationServer.CompilerLock, TGServerService.TGStationServer.configLock, TGServerService.Program.CopyDirectory(), TGServerService.TGStationServer.currentStatus, TGServerService.Program.DeleteDirectory(), TGServerService.TGStationServer.DisposeRepo(), TGServerService.TGStationServer.GameDir, TGServerService.TGStationServer.PrivateKeyPath, TGServerService.TGStationServer.RepoBusy, TGServerService.TGStationServer.RepoLock, TGServerService.TGStationServer.updateStat, and TGServerService.TGStationServer.watchdogLock.
         {
             var Config = Properties.Settings.Default;
             try
             {
                 var di1 = new DirectoryInfo(Config.ServerDirectory);
                 var di2 = new DirectoryInfo(new_location);
                 var copy = di1.Root.FullName != di2.Root.FullName;
                 if (copy && File.Exists(PrivateKeyPath))
                     return String.Format("Unable to perform a cross drive server move with the {0}. Copy aborted!", PrivateKeyPath);
                 new_location = di2.FullName;
                 while (di2.Parent != null)
                     if (di2.Parent.FullName == di1.FullName)
                         return "Cannot move to child of current directory!";
                     else
                         di2 = di2.Parent;
                 if (!Monitor.TryEnter(RepoLock))
                     return "Repo locked!";
                 try
                 {
                     if (RepoBusy)
                         return "Repo busy!";
                     DisposeRepo();
                     if (!Monitor.TryEnter(ByondLock))
                         return "BYOND locked";
                     try
                     {
                         if (updateStat != TGByondStatus.Idle)
                             return "BYOND busy!";
                         if (!Monitor.TryEnter(CompilerLock))
                             return "Compiler locked!";
                         try
{
                             if (compilerCurrentStatus != TGCompilerStatus.Uninitialized && compilerCurrentStatus != TGCompilerStatus.Initialized)
                                 return "Compiler busy!";
                             if (!Monitor.TryEnter(watchdogLock))
                                 return "Watchdog locked!";
                             try
{
                                 if (currentStatus != TGDreamDaemonStatus.Offline)
                                     return "Watchdog running!";
                                 lock (configLock)
{
                                     CleanGameFolder();
                                     Program.DeleteDirectory(GameDir);
                                     string error = null;
                                     if (copy)
{
                                         Program.CopyDirectory(Config.ServerDirectory, new_location);
                                         Directory.CreateDirectory(new_location);
                                         Environment.CurrentDirectory = new_location;
                                         try
{
                                             Program.DeleteDirectory(Config.ServerDirectory);
                                         }
                                         catch (Exception e)
{
                                             error = "The move was successful, but the path " + Config.ServerDirectory + " was unable to be deleted fully!";
                                             TGServerService.WriteWarning(String.Format("Server move from {0} to {1} partial success: {2}", Config.ServerDirectory, new_location, e.ToString()), TGServerService.EventID.ServerMovePartial);
                                         }
                                     }
                                     else
{
                                         try
{
                                             Environment.CurrentDirectory = di2.Root.FullName;
                                             Directory.Move(Config.ServerDirectory, new_location);
                                             Environment.CurrentDirectory = new_location;
                                         }
                                         catch
{
                                             Environment.CurrentDirectory = Config.ServerDirectory;
                                             throw;
                                         }
                                     }
                                     TGServerService.WriteInfo(String.Format("Server moved from {0} to {1}", Config.ServerDirectory, new_location), TGServerService.EventID.ServerMoveComplete);
                                     Config.ServerDirectory = new_location;
                                     return null;
                                 }
                             }
                             finally
{
                                 Monitor.Exit(watchdogLock);
                             }
                         }
                         finally
{
                             Monitor.Exit(CompilerLock);
                         }
                     }
                     finally
                     {
                         Monitor.Exit(ByondLock);
                     }
                 }
                 finally
                 {
                     Monitor.Exit(RepoLock);
                 }
             }
             catch (Exception e)
             {
                 TGServerService.WriteError(String.Format("Server move from {0} to {1} failed: {2}", Config.ServerDirectory, new_location, e.ToString()), TGServerService.EventID.ServerMoveFailed);
                 return e.ToString();
             }
         }
bool TGServerService.TGStationServer.OperationInProgress ()
If the repo is currently undergoing an operation
Returns
if the repo is busy, otherwise
Implements TGServiceInterface.ITGRepository.
Definition at line 175 of file Repository.cs.
References TGServerService.TGStationServer.RepoBusy.
         {
             lock (RepoLock)
             {
                 return RepoBusy;
             }
         }
int TGServerService.TGStationServer.PlayerCount ()
Returns the number of connected players. Requires game to use API version >= 3.1.0.1
Returns
The number of connected players or -1 on error
Implements TGServiceInterface.ITGDreamDaemon.
Definition at line 140 of file Interop.cs.
References TGServerService.TGStationServer.SendCommand().
         {
             try
             {
                 return Convert.ToInt32(SendCommand(SCPlayerCount));
             }
             catch
             {
                 return -1;
             }
         }
ushort TGServerService.TGStationServer.Port ()
Get the configured port. Not necessarily the running port if it has since changed
Returns
The configured port
Implements TGServiceInterface.ITGDreamDaemon.
Definition at line 571 of file DreamDaemon.cs.
         {
             return Properties.Settings.Default.ServerPort;
         }
bool TGServerService.TGStationServer.PostcompileHook ()
Definition at line 60 of file PreactionHandler.cs.
References TGServerService.TGStationServer.HandleEvent().
Referenced by TGServerService.TGStationServer.CompileImpl().
         {
             return HandleEvent("postcompile");
         }
bool TGServerService.TGStationServer.PrecompileHook ()
Definition at line 55 of file PreactionHandler.cs.
References TGServerService.TGStationServer.HandleEvent().
Referenced by TGServerService.TGStationServer.CompileImpl().
         {
             return HandleEvent("precompile");
         }
void TGServerService.TGStationServer.PrepareForUpdate ()
Next stop of the service will not close DD and sets a flag for it to reattach once it restarts
Implements TGServiceInterface.ITGSService.
Definition at line 47 of file InterfaceBase.cs.
References TGServerService.TGStationServer.SendMessage().
         {
             Properties.Settings.Default.ReattachToDD = true;
             SendMessage("SERVICE: Update started...", ChatMessageType.DeveloperInfo);
         }
string TGServerService.TGStationServer.ProjectName ()
Returns the relative path of the dme the compiler will look for without the .dme part
Returns
The relative path of the dme the compiler will look for without the .dme part
Implements TGServiceInterface.ITGCompiler.
Definition at line 601 of file Compiler.cs.
Referenced by TGServerService.TGStationServer.CompileImpl().
         {
             lock (CompilerLock)
             {
                 return Properties.Settings.Default.ProjectName;
             }
         }
IList<TGChatSetupInfo> TGServerService.TGStationServer.ProviderInfos ()
Returns TGChatSetupInfo for all TGChatProviders
Returns
A list of all TGChatSetupInfos
Implements TGServiceInterface.ITGChat.
Definition at line 176 of file Chat.cs.
         {
             var infosList = new List<TGChatSetupInfo>();
             foreach (var ChatProvider in ChatProviders)
                 infosList.Add(ChatProvider.ProviderInfo());
             return infosList;
         }
string TGServerService.TGStationServer.Push () private
Definition at line 1038 of file Repository.cs.
References TGServerService.TGStationServer.GenerateGitCredentials(), TGServerService.TGStationServer.LoadRepo(), TGServerService.TGStationServer.LocalIsRemote(), and TGServerService.TGStationServer.SSHAuth().
Referenced by TGServerService.TGStationServer.SynchronizePush().
         {
             if (LocalIsRemote())    //nothing to push
                 return null;
             lock (RepoLock)
             {
                 var result = LoadRepo();
                 if (result != null)
                     return result;
                 try
                 {
                     if (!SSHAuth())
                         return String.Format("Either {0} or {1} is missing from the server directory. Unable to push!", PrivateKeyPath, PublicKeyPath);
                     var options = new PushOptions()
                     {
                         CredentialsProvider = GenerateGitCredentials,
                     };
                     Repo.Network.Push(Repo.Network.Remotes[SSHPushRemote], Repo.Head.CanonicalName, options);
                     TGServerService.WriteInfo("Repo pushed up to commit: " + Repo.Head.Tip.Sha, TGServerService.EventID.RepoPush);
                     return null;
                 }
                 catch (Exception e)
                 {
                     TGServerService.WriteError("Repo push failed: " + e.ToString(), TGServerService.EventID.RepoPushFail);
                     return e.ToString();
                 }
             }
         }
string TGServerService.TGStationServer.PythonPath ()
Gets the path to the python 2.7 installation
Returns
The path to the python 2.7 installation
Implements TGServiceInterface.ITGRepository.
Definition at line 1240 of file Repository.cs.
         {
             return Properties.Settings.Default.PythonPath;
         }
string TGServerService.TGStationServer.ReadText (string staticRelativePath, bool repo, out string error, out bool unauthorized)
Read from a static file
Parameters
staticRelativePath The path from the Static dir. E.g. config/config.txt
repo if true, the file will be read from the repository instead of the static dir
error null on success, error message on failure
unauthorized This will be true if error is set to a message that indicates the current user does not have access to the specified file
Returns
The full text of the file on success, null on failure
Exceptions
CommunicationException Along with implied disconnect exceptions, if the file exceeds transfer limits
Implements TGServiceInterface.ITGConfig.
Definition at line 23 of file Config.cs.
References TGServerService.TGStationServer.RepoPath, and TGServerService.TGStationServer.StaticDirs.
         {
             try
             {
                 var configDir = repo ? RepoPath : StaticDirs;
                 var path = configDir + '/' + staticRelativePath;   //do not use path.combine or it will try and take the root
                 lock (configLock)
                 {
                     var di1 = new DirectoryInfo(configDir);
                     if (repo)
                     {
                         //ensure we aren't trying to read anything outside the static dirs
                         var Config = new RepoConfig(false);
                         if (Config == null)
{
                             error = "Unable to load static directory configuration";
                             unauthorized = false;
                             return null;
                         }
                         var Found = false;
                         foreach (var I in Config.StaticDirectoryPaths)
{
                             if (di1.FullName == new DirectoryInfo(Path.Combine(RepoPath, I)).FullName)
{
                                 Found = true;
                                 break;
                             }
                         }
                         if (!Found)
{
                             error = "File is not in a configured static directory!";
                             unauthorized = false;
                             return null;
                         }
                     }
                     var di2 = new DirectoryInfo(new FileInfo(path).Directory.FullName);
                     var good = false;
                     while (di2 != null)
                     {
                         if (di2.FullName == di1.FullName)
{
                             good = true;
                             break;
                         }
                         else di2 = di2.Parent;
                     }
                     if (!good)
                     {
                         error = "Cannot read above static directories!";
                         unauthorized = false;
                         return null;
                     }
                     var output = File.ReadAllText(path);
                     TGServerService.CancelImpersonation();
                     TGServerService.WriteInfo("Read of " + path, TGServerService.EventID.StaticRead);
                     error = null;
                     unauthorized = false;
                     return output;
                 }
             }
             catch (UnauthorizedAccessException e)
             {
                 //no need for the full stacktrace
                 error = e.Message;
                 unauthorized = true;
                 return null;
             }
             catch (Exception e)
             {
                 error = e.ToString();
                 unauthorized = false;
                 return null;
             }
         }
string TGServerService.TGStationServer.Reconnect (TGChatProvider providerType)
Reconnect a specific providerType to it's chat service
Parameters
providerType The type of provider to reconnect
Returns
on success, error message string on failure
Implements TGServiceInterface.ITGChat.
Definition at line 266 of file Chat.cs.
         {
             foreach (var I in ChatProviders)
                 if (I.ProviderInfo().Provider == providerType)
                     return I.Reconnect();
             return "Could not find specified provider!";
         }
string TGServerService.TGStationServer.RecreateStaticFolder ()
Renames the current static folder to a backup name and recreates is from the current repo using TGS3.json
Returns
on success, error message on failure
Implements TGServiceInterface.ITGAdministration.
Definition at line 242 of file Administration.cs.
References TGServerService.TGStationServer.BackupAndDeleteStaticDirectory(), TGServerService.TGStationServer.configLock, TGServerService.TGStationServer.currentStatus, TGServerService.TGStationServer.InitialConfigureRepository(), TGServerService.TGStationServer.RepoLock, and TGServerService.TGStationServer.watchdogLock.
         {
             if (!Monitor.TryEnter(RepoLock))
                 return "Repo locked!";
             try
             {
                 if (!Monitor.TryEnter(watchdogLock))
                     return "Watchdog locked!";
                 try
                 {
                     if (!Monitor.TryEnter(configLock))
                         return "Static dir locked!";
                     try
                     {
                         if (currentStatus != TGDreamDaemonStatus.Offline)
                             return "Watchdog running!";
                         BackupAndDeleteStaticDirectory();
                         InitialConfigureRepository();
                     }
                     finally
                     {
                         Monitor.Exit(configLock);
                     }
                 }
                 finally
                 {
                     Monitor.Exit(watchdogLock);
                 }
             }
             catch(Exception e)
             {
                 return e.ToString();
             }
             finally
             {
                 Monitor.Exit(RepoLock);
             }
             return null;
         }
ushort TGServerService.TGStationServer.RemoteAccessPort ()
Get the port used for remote operation
Implements TGServiceInterface.ITGAdministration.
Definition at line 113 of file Administration.cs.
         {
             return Properties.Settings.Default.RemoteAccessPort;
         }
bool TGServerService.TGStationServer.RepoConfigsMatch () private
Definition at line 159 of file Repository.cs.
References TGServerService.TGStationServer.LoadRepo(), and TGServerService.TGStationServer.RepoConfig.RepoConfig().
Referenced by TGServerService.TGStationServer.CompileImpl(), and TGServerService.TGStationServer.InitializeImpl().
         {
             //this should never be called while the repo is busy
             RepoConfig I = null;
             lock (RepoLock)
             {
                 if (!RepoBusy && LoadRepo() == null)
                     I = new RepoConfig(true);
             }
             if (I == null)
                 throw new Exception("Unable to load TGS3.json from repo!");
             var J = new RepoConfig(false);
             return I == J;
         }
void TGServerService.TGStationServer.RequestRestart ()
Restart the server after the currently running world reboots. Has no effect if the server isn't running
Implements TGServiceInterface.ITGDreamDaemon.
Definition at line 142 of file DreamDaemon.cs.
References TGServerService.TGStationServer.SCHardReboot, and TGServerService.TGStationServer.SendCommand().
Referenced by TGServerService.TGStationServer.SetPort(), TGServerService.TGStationServer.SetSecurityLevel(), TGServerService.TGStationServer.SetWebclient(), and TGServerService.TGStationServer.UpdateToVersionImpl().
         {
             SendCommand(SCHardReboot);
         }
void TGServerService.TGStationServer.RequestStop ()
Stop the server after the currently running world reboots. Has no effect if the server isn't running
Implements TGServiceInterface.ITGDreamDaemon.
Definition at line 148 of file DreamDaemon.cs.
References TGServerService.TGStationServer.SCGracefulShutdown, and TGServerService.TGStationServer.SendCommand().
         {
             lock (watchdogLock)
             {
                 if (currentStatus != TGDreamDaemonStatus.Online || AwaitingShutdown != ShutdownRequestPhase.None)
                     return;
                 AwaitingShutdown = ShutdownRequestPhase.Pinged;
             }
             SendCommand(SCGracefulShutdown);
         }
string TGServerService.TGStationServer.Reset (bool tracked)
Runs git reset –hard
Parameters
tracked Changes command to git reset –hard origin/branch_name if
Returns
on success, error message on failure
Implements TGServiceInterface.ITGRepository.
Definition at line 713 of file Repository.cs.
References TGServerService.TGStationServer.DeletePRList(), TGServerService.TGStationServer.LoadRepo(), TGServerService.TGStationServer.ResetNoLock(), and TGServerService.TGStationServer.SendMessage().
         {
             lock (RepoLock)
             {
                 var res = LoadRepo() ?? ResetNoLock(trackedBranch ? (Repo.Head.TrackedBranch ?? Repo.Head) : Repo.Head);
                 if (res == null)
                 {
                     SendMessage(String.Format("REPO: Hard reset to {0}branch", trackedBranch ? "tracked " : ""), ChatMessageType.DeveloperInfo);
                     if (trackedBranch)
                         DeletePRList();
                     TGServerService.WriteInfo(String.Format("Repo branch reset{0}", trackedBranch ? " to tracked branch" : ""), trackedBranch ? TGServerService.EventID.RepoResetTracked : TGServerService.EventID.RepoReset);
                     return null;
                 }
                 TGServerService.WriteWarning(String.Format("Failed to reset{0}: {1}", trackedBranch ? " to tracked branch" : "", res), trackedBranch ? TGServerService.EventID.RepoResetTrackedFail : TGServerService.EventID.RepoResetFail);
                 return res;
             }
         }
string TGServerService.TGStationServer.ResetNoLock (Branch targetBranch) private
Definition at line 485 of file Repository.cs.
Referenced by TGServerService.TGStationServer.Checkout(), TGServerService.TGStationServer.MergeBranch(), TGServerService.TGStationServer.MergePullRequestImpl(), TGServerService.TGStationServer.Reset(), and TGServerService.TGStationServer.UpdateImpl().
         {
             try
             {
                 if (targetBranch != null)
                     Repo.Reset(ResetMode.Hard, targetBranch.Tip);
                 else
                     Repo.Reset(ResetMode.Hard);
                 return null;
             }
             catch (Exception e)
             {
                 return e.ToString();
             }
         }
string TGServerService.TGStationServer.Restart ()
Immediately kills and restarts the server
Returns
on success or error message on failure
Implements TGServiceInterface.ITGDreamDaemon.
Definition at line 206 of file DreamDaemon.cs.
References TGServerService.TGStationServer.DaemonStatus(), TGServerService.TGStationServer.SendMessage(), TGServerService.TGStationServer.Start(), and TGServerService.TGStationServer.Stop().
Referenced by TGServerService.TGStationServer.KillMe().
         {
             if (DaemonStatus() == TGDreamDaemonStatus.Offline)
                 return Start();
             lock(restartLock)
             {
                 if (RestartInProgress)
                     return "Restart already in progress";
                 RestartInProgress = true;
             }
             SendMessage("DD: Hard restart triggered", ChatMessageType.WatchdogInfo);
             Stop();
             var res = Start();
             if(res != null)
                 lock(restartLock)
                 {
                     RestartInProgress = false;
                 }
             return res;
         }
void TGServerService.TGStationServer.RunDisposals () private
Definition at line 28 of file InterfaceBase.cs.
References TGServerService.TGStationServer.DisposeByond(), TGServerService.TGStationServer.DisposeChat(), TGServerService.TGStationServer.DisposeCompiler(), TGServerService.TGStationServer.DisposeDreamDaemon(), and TGServerService.TGStationServer.DisposeRepo().
Referenced by TGServerService.TGStationServer.Dispose().
         {
             DisposeDreamDaemon();
             DisposeCompiler();
             DisposeByond();
             DisposeRepo();
             DisposeChat();
         }
static string TGServerService.TGStationServer.SanitizeTopicString (string input) static
Definition at line 158 of file Interop.cs.
Referenced by TGServerService.ServerChatCommand.Run(), and TGServerService.TGStationServer.WorldAnnounce().
         {
             return input.Replace("%", "%25").Replace("=", "%3d").Replace(";", "%3b").Replace("&", "%26").Replace("+", "%2b");
         }
TGDreamDaemonSecurity TGServerService.TGStationServer.SecurityLevel ()
Get the configured (not necessarily running) security level
Returns
The configured (not necessarily running) TGDreamDaemonSecurity
Implements TGServiceInterface.ITGDreamDaemon.
Definition at line 499 of file DreamDaemon.cs.
         {
             lock (watchdogLock)
             {
                 return (TGDreamDaemonSecurity)Properties.Settings.Default.ServerSecurity;
             }
         }
string TGServerService.TGStationServer.SecurityWord (bool starting = false) private
Definition at line 423 of file DreamDaemon.cs.
Referenced by TGServerService.TGStationServer.StartImpl(), and TGServerService.TGStationServer.StatusString().
         {
             var level = starting ? StartingSecurity : (TGDreamDaemonSecurity)Properties.Settings.Default.ServerSecurity;
             switch (level)
             {
                 case TGDreamDaemonSecurity.Safe:
                     return "safe";
                 case TGDreamDaemonSecurity.Trusted:
                     return "trusted";
                 case TGDreamDaemonSecurity.Ultrasafe:
                     return "ultrasafe";
                 default:
                     throw new Exception(String.Format("Bad DreamDaemon security level: {0}", level));
             }
         }
string TGServerService.TGStationServer.SendCommand (string cmd)
Definition at line 130 of file Interop.cs.
References TGServerService.TGStationServer.currentPort, TGServerService.TGStationServer.currentStatus, TGServerService.TGStationServer.SendTopic(), and TGServerService.TGStationServer.watchdogLock.
Referenced by TGServerService.TGStationServer.HandleCommand(), TGServerService.TGStationServer.LoadServerChatCommands(), TGServerService.TGStationServer.PlayerCount(), TGServerService.TGStationServer.RequestRestart(), TGServerService.TGStationServer.RequestStop(), TGServerService.TGStationServer.Watchdog(), and TGServerService.TGStationServer.WorldAnnounce().
         {
             lock (watchdogLock)
             {
                 if (currentStatus != TGDreamDaemonStatus.Online)
                     return "Error: Server Offline!";
                 return SendTopic(String.Format("serviceCommsKey={0};command={1}", serviceCommsKey, cmd), currentPort);
             }
         }
void TGServerService.TGStationServer.SendMessage (string msg, ChatMessageType mt)
Broadcast a message to appropriate channels based on the message type
Parameters
msg The message to send
mt The message type
Definition at line 279 of file Chat.cs.
Referenced by TGServerService.TGStationServer.ApplyStagedUpdate(), TGServerService.TGStationServer.Checkout(), TGServerService.TGStationServer.Clone(), TGServerService.TGStationServer.CompileImpl(), TGServerService.TGStationServer.DisposeDreamDaemon(), TGServerService.TGStationServer.HandleCommand(), TGServerService.TGStationServer.InitDreamDaemon(), TGServerService.TGStationServer.InitializeImpl(), TGServerService.TGStationServer.MergeBranch(), TGServerService.TGStationServer.MergePullRequestImpl(), TGServerService.TGStationServer.PrepareForUpdate(), TGServerService.TGStationServer.Reset(), TGServerService.TGStationServer.Restart(), TGServerService.TGStationServer.UpdateImpl(), TGServerService.TGStationServer.UpdateSubmodules(), TGServerService.TGStationServer.UpdateToVersionImpl(), and TGServerService.TGStationServer.Watchdog().
         {
             lock (ChatLock)
             {
                 foreach (var ChatProvider in ChatProviders)
                     try
                     {
                         ChatProvider.SendMessage(msg, mt);
                     }catch(Exception e)
                     {
                         TGServerService.WriteWarning(String.Format("Chat broadcast failed (Provider: {3}) (Flags: {0}) (Message: {1}): {2}", mt, msg, e.ToString(), ChatProvider.ProviderInfo().Provider), TGServerService.EventID.ChatBroadcastFail);
                     }
             }
         }
string TGServerService.TGStationServer.SendTopic (string topicdata, ushort port) private
Definition at line 164 of file Interop.cs.
References TGServerService.TGStationServer.CheckAPIVersionConstraints().
Referenced by TGServerService.TGStationServer.SendCommand().
         {
             //santize the escape characters in accordance with http://www.byond.com/docs/ref/info.html#/proc/params2list
             lock (topicLock) {
                 if (!CheckAPIVersionConstraints())
                     return "Incompatible API!";
                 using (var topicSender = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp) { SendTimeout = 5000, ReceiveTimeout = 5000 })
                 {
                     try
                     {
                         topicSender.Connect(IPAddress.Loopback, port);
                         StringBuilder stringPacket = new StringBuilder();
                         stringPacket.Append((char)'\x00', 8);
                         stringPacket.Append('?' + topicdata);
                         stringPacket.Append((char)'\x00');
                         string fullString = stringPacket.ToString();
                         var packet = Encoding.ASCII.GetBytes(fullString);
                         packet[1] = 0x83;
                         var FinalLength = packet.Length - 4;
                         if (FinalLength > UInt16.MaxValue)
                             return "Error: Topic too long";
                         var lengthBytes = BitConverter.GetBytes((ushort)FinalLength);
                         packet[2] = lengthBytes[1]; //fucking endianess
                         packet[3] = lengthBytes[0];
                         topicSender.Send(packet);
                         string returnedString = "NULL";
                         try
{
                             var returnedData = new byte[UInt16.MaxValue];
                             topicSender.Receive(returnedData);
                             var raw_string = Encoding.ASCII.GetString(returnedData).TrimEnd(new char[] { (char)0 }).Trim();
                             if (raw_string.Length > 6)
                                 returnedString = raw_string.Substring(5, raw_string.Length - 5).Trim();
                         }
                         catch
{
                             returnedString = "Topic recieve error!";
                         }
                         finally
{
                             topicSender.Shutdown(SocketShutdown.Both);
                         }
                         return returnedString;
                     }
                     catch
                     {
                         return "Topic delivery failed!";
                     }
                 }
             }
         }
string TGServerService.TGStationServer.ServerDirectory ()
Return the directory of the server on the host machine
Returns
The path to the directory on success, null on failure
Implements TGServiceInterface.ITGConfig.
Definition at line 16 of file Config.cs.
         {
             return Environment.CurrentDirectory;
         }
string TGServerService.TGStationServer.SetAuthorizedGroup (string groupName)
Searches the windows machine for the group named groupName , sets it as the authorized group if it's found
Implements TGServiceInterface.ITGAdministration.
Definition at line 39 of file Administration.cs.
References TGServerService.TGStationServer.FindTheDroidsWereLookingFor().
         {
             if (groupName == null)
             {
                 TheDroidsWereLookingFor = null;
                 var config = Properties.Settings.Default;
                 config.AuthorizedGroupSID = null;
                 config.Save();
                 return "ADMIN";
             }
             return FindTheDroidsWereLookingFor(groupName);
         }
void TGServerService.TGStationServer.SetAutostart (bool on)
Set the autostart config
Parameters
on to start the watchdog with the service, to disable that functionality
Implements TGServiceInterface.ITGDreamDaemon.
Definition at line 530 of file DreamDaemon.cs.
         {
             Properties.Settings.Default.DDAutoStart = on;
         }
void TGServerService.TGStationServer.SetAutoUpdateInterval (ulong newInterval)
(De)Activate and set the interval for the automatic server updater
Implements TGServiceInterface.ITGRepository.
Definition at line 1205 of file Repository.cs.
References TGServerService.TGStationServer.autoUpdateTimer.
Referenced by TGServerService.TGStationServer.InitRepo().
         {
             lock (autoUpdateTimer)
             {
                 autoUpdateTimer.Stop();
                 if (newInterval > 0) {
                     autoUpdateTimer.Interval = newInterval * 60 * 1000; //convert from minutes to ms
                     autoUpdateTimer.Start();
                 }
             }
             Properties.Settings.Default.AutoUpdateInterval = newInterval;
         }
void TGServerService.TGStationServer.SetCommitterEmail (string newEmail)
Sets the email of the configured git committer
Parameters
newEmail The email to set
Implements TGServiceInterface.ITGRepository.
Definition at line 938 of file Repository.cs.
         {
             lock (RepoLock)
             {
                 Properties.Settings.Default.CommitterEmail = newEmail;
             }
         }
void TGServerService.TGStationServer.SetCommitterName (string newName)
Sets the name of the configured git committer
Parameters
newName The name to set
Implements TGServiceInterface.ITGRepository.
Definition at line 920 of file Repository.cs.
         {
             lock (RepoLock)
             {
                 Properties.Settings.Default.CommitterName = newName;
             }
         }
void TGServerService.TGStationServer.SetCurrentPRList (IDictionary< string, IDictionary< string, string >> list) private
Definition at line 763 of file Repository.cs.
Referenced by TGServerService.TGStationServer.MergePullRequestImpl().
         {
             var Serializer = new JavaScriptSerializer();
             var rawdata = Serializer.Serialize(list);
             File.WriteAllText(PRJobFile, rawdata);
         }
void TGServerService.TGStationServer.SetPort (ushort new_port)
Set the port to host DD on. Requires reboot to apply. Calls RequestRestart.
Parameters
new_port The new port
Implements TGServiceInterface.ITGDreamDaemon.
Definition at line 179 of file DreamDaemon.cs.
References TGServerService.TGStationServer.RequestRestart().
         {
             lock (watchdogLock)
             {
                 Properties.Settings.Default.ServerPort = new_port;
                 RequestRestart();
             }
         }
void TGServerService.TGStationServer.SetProjectName (string projectName)
Sets the relative path of the dme the compiler will look for without the .dme part
Parameters
projectName The relative path of the dme the compiler will look for without the .dme part
Implements TGServiceInterface.ITGCompiler.
Definition at line 610 of file Compiler.cs.
         {
             lock (CompilerLock)
             {
                 Properties.Settings.Default.ProjectName = projectName;
             }
         }
string TGServerService.TGStationServer.SetProviderInfo (TGChatSetupInfo info)
Sets a chat provider info
Parameters
info The info to set
Implements TGServiceInterface.ITGChat.
Definition at line 228 of file Chat.cs.
References TGServiceInterface.TGChatSetupInfo.Provider.
         {
             try
             {
                 lock (ChatLock)
                 {
                     foreach (var ChatProvider in ChatProviders)
                         if (info.Provider == ChatProvider.ProviderInfo().Provider)
                             return ChatProvider.SetProviderInfo(info);
                     return "Error: Invalid provider: " + info.Provider.ToString();
                 }
             }
             catch (Exception e)
             {
                 return e.ToString();
             }
         }
bool TGServerService.TGStationServer.SetPythonPath (string path)
Sets the path to the python 2.7 installation
Parameters
path The new path
Returns
if the path exists, otherwise
Implements TGServiceInterface.ITGRepository.
Definition at line 1232 of file Repository.cs.
         {
             if (!Directory.Exists(path))
                 return false;
             Properties.Settings.Default.PythonPath = Path.GetFullPath(path);
             return true;
         }
string TGServerService.TGStationServer.SetRemoteAccessPort (ushort port)
Set the port used for remote operation Requires a service restart to take effect
Implements TGServiceInterface.ITGAdministration.
Definition at line 119 of file Administration.cs.
         {
             if (port == 0)
                 return "Cannot bind to port 0";
             var Config = Properties.Settings.Default;
             Config.RemoteAccessPort = port;
             Config.Save();
             return null;
         }
bool TGServerService.TGStationServer.SetSecurityLevel (TGDreamDaemonSecurity level)
Sets the security level of the server. Requires server reboot to apply. Calls RequestRestart. Note that anything higher than Trusted will disable interop from DD
Parameters
level The new security level
Returns
if the change was immediately applied, otherwise and a call to RequestRestart was made
Implements TGServiceInterface.ITGDreamDaemon.
Definition at line 508 of file DreamDaemon.cs.
References TGServerService.TGStationServer.DaemonStatus(), and TGServerService.TGStationServer.RequestRestart().
         {
             var Config = Properties.Settings.Default;
             var secInt = (int)level;
             bool needReboot;
             lock (watchdogLock)
             {
                 needReboot = Config.ServerSecurity != secInt;
                 Config.ServerSecurity = secInt;
             }
             if (needReboot)
                 RequestRestart();
             return DaemonStatus() != TGDreamDaemonStatus.Online;
         }
string TGServerService.TGStationServer.Setup (string remote, string branch)
Deletes whatever may be left over and clones the repo at remote and checks out branch . Will move config and data dirs to a backup location if they exist. Runs asyncronously
Parameters
remote The address of the repo to clone. If ssh protocol is used, private_key.txt and public_key.txt must exist in the server RepoKey directory.
branch The branch of the repo to checkout
Returns
on success, error message on failure
Implements TGServiceInterface.ITGRepository.
Definition at line 397 of file Repository.cs.
References TGServerService.TGStationServer.Clone(), TGServerService.TGStationServer.CompilerIdleNoLock(), TGServerService.TGStationServer.CompilerLock, TGServerService.TGStationServer.DaemonStatus(), and TGServerService.TGStationServer.SSHAuth().
         {
             lock (RepoLock)
             {
                 if (RepoBusy)
                     return "Repo is busy!";
                 lock (CompilerLock)
                 {
                     if (!CompilerIdleNoLock())
                         return "Compiler is running!";
                 }
                 if (DaemonStatus() != TGDreamDaemonStatus.Offline)
                     return "DreamDaemon is running!";
                 if (RepoURL.Contains("ssh://") && !SSHAuth())
                     return String.Format("SSH url specified but either {0} or {1} does not exist in the server directory!", PrivateKeyPath, PublicKeyPath);
                 RepoBusy = true;
                 Cloning = true;
                 new Thread(new ParameterizedThreadStart(Clone))
                 {
                     IsBackground = true //make sure we don't hold up shutdown
                 }.Start(new TwoStrings { a = RepoURL, b = BranchName });
                 return null;
             }
         }
void TGServerService.TGStationServer.SetWebclient (bool on)
Set the webclient config. Calls RequestRestart
Implements TGServiceInterface.ITGDreamDaemon.
Definition at line 601 of file DreamDaemon.cs.
References TGServerService.TGStationServer.RequestRestart().
         {
             var Config = Properties.Settings.Default;
             lock (watchdogLock) {
                 var diff = on != Config.Webclient;
                 if (diff)
                 {
                     Config.Webclient = on;
                     RequestRestart();
                 }
             }
         }
bool TGServerService.TGStationServer.ShutdownInProgress ()
Checks if a server stop has been requested
Returns
if RequestStop has been called since the last server start, otherwise
Implements TGServiceInterface.ITGDreamDaemon.
Definition at line 577 of file DreamDaemon.cs.
         {
             lock (watchdogLock)
             {
                 return AwaitingShutdown != ShutdownRequestPhase.None;
             }
         }
bool TGServerService.TGStationServer.SSHAuth () private
Definition at line 1068 of file Repository.cs.
Referenced by TGServerService.TGStationServer.Push(), TGServerService.TGStationServer.Setup(), and TGServerService.TGStationServer.SynchronizePush().
         {
             return File.Exists(PrivateKeyPath) && File.Exists(PublicKeyPath);
         }
string TGServerService.TGStationServer.Start ()
Starts the server if it isn't running
Returns
on success or error message on failure
Implements TGServiceInterface.ITGDreamDaemon.
Definition at line 401 of file DreamDaemon.cs.
References TGServerService.TGStationServer.ApplyStagedUpdate(), TGServerService.TGStationServer.CanStartImpl(), TGServerService.TGStationServer.CurrentStatus(), and TGServerService.TGStationServer.StartImpl().
Referenced by TGServerService.TGStationServer.InitDreamDaemon(), and TGServerService.TGStationServer.Restart().
         {
             if (CurrentStatus() == TGByondStatus.Staged)
             {
                 //IMPORTANT: SLEEP FOR A MOMENT OR WONDOWS WON'T RELEASE THE FUCKING BYOND DLL HANDLES!!!! REEEEEEE
                 Thread.Sleep(3000);
                 ApplyStagedUpdate();
             }
             lock (watchdogLock)
             {
                 if (currentStatus != TGDreamDaemonStatus.Offline)
                     return "Server already running";
                 var res = CanStartImpl();
                 if (res != null)
                     return res;
                 currentPort = 0;
                 currentStatus = TGDreamDaemonStatus.HardRebooting;
             }
             return StartImpl(false);
         }
string TGServerService.TGStationServer.StartImpl (bool watchdog) private
Definition at line 449 of file DreamDaemon.cs.
References TGServerService.TGStationServer.CanStartImpl(), TGServerService.TGStationServer.GameAPIVersion, TGServerService.TGStationServer.GameDirLive, TGServerService.TGStationServer.GenCommsKey(), TGServerService.TGStationServer.SecurityWord(), TGServerService.TGStationServer.serviceCommsKey, TGServerService.TGStationServer.topicLock, TGServerService.TGStationServer.UpdateInterfaceDll(), TGServerService.TGStationServer.Version(), and TGServerService.TGStationServer.Watchdog().
Referenced by TGServerService.TGStationServer.Start(), and TGServerService.TGStationServer.Watchdog().
         {
             try
             {
                 lock (watchdogLock)
                 {
                     var res = CanStartImpl();
                     if (res != null)
                         return res;
                     var Config = Properties.Settings.Default;
                     var DMB = GameDirLive + "/" + Config.ProjectName + ".dmb";
                     GenCommsKey();
                     StartingSecurity = (TGDreamDaemonSecurity)Config.ServerSecurity;
                     Proc.StartInfo.Arguments = String.Format("{0} -port {1} {5}-close -verbose -params \"server_service={3}&server_service_version={4}\" -{2} -public", DMB, Config.ServerPort, SecurityWord(), serviceCommsKey, Version(), Config.Webclient ? "-webclient " : "");
                     UpdateInterfaceDll(true);
                     lock (topicLock)
                     {
                         GameAPIVersion = null;  //needs updating
                     }
                     Proc.Start();
                     if (!Proc.WaitForInputIdle(DDHangStartTime * 1000))
                     {
                         Proc.Kill();
                         Proc.WaitForExit();
                         Proc.Close();
                         currentStatus = TGDreamDaemonStatus.Offline;
                         currentPort = 0;
                         return String.Format("Server start is taking more than {0}s! Aborting!", DDHangStartTime);
                     }
                     currentPort = Config.ServerPort;
                     currentStatus = TGDreamDaemonStatus.Online;
                     if (!watchdog)
                     {
                         DDWatchdog = new Thread(new ThreadStart(Watchdog));
                         DDWatchdog.Start();
                     }
                     return null;
                 }
             }
             catch (Exception e)
             {
                 currentStatus = TGDreamDaemonStatus.Offline;
                 return e.ToString();
             }
         }
string TGServerService.TGStationServer.StatusString (bool includeMetaInfo)
Returns a human readable string of the current server status
Parameters
includeMetaInfo If , the status will include the server's current visibility and security levels
Returns
A human readable string of the current server status
Implements TGServiceInterface.ITGDreamDaemon.
Definition at line 536 of file DreamDaemon.cs.
References TGServerService.TGStationServer.DaemonStatus(), and TGServerService.TGStationServer.SecurityWord().
         {
             const string visSecStr = " (Sec: {0})";
             string res;
             var ds = DaemonStatus();
             switch (ds)
             {
                 case TGDreamDaemonStatus.Offline:
                     res = "OFFLINE";
                     break;
                 case TGDreamDaemonStatus.HardRebooting:
                     res = "REBOOTING";
                     break;
                 case TGDreamDaemonStatus.Online:
                     res = "ONLINE";
                     if (includeMetaInfo)
                     {
                         string secandvis;
                         lock (watchdogLock)
{
                             secandvis = String.Format(visSecStr, SecurityWord(true));
                         }
                         res += secandvis;
                     }
                     break;
                 default:
                     res = "NULL AND ERRORS";
                     break;
             }
             if (includeMetaInfo && ds != TGDreamDaemonStatus.Online)
                 res += String.Format(visSecStr, SecurityWord());
             return res;
         }
string TGServerService.TGStationServer.Stop ()
Immediately kills the server
Returns
on success or error message on failure
Implements TGServiceInterface.ITGDreamDaemon.
Definition at line 160 of file DreamDaemon.cs.
References TGServerService.TGStationServer.DDWatchdog.
Referenced by TGServerService.TGStationServer.DisposeDreamDaemon(), TGServerService.TGStationServer.KillMe(), and TGServerService.TGStationServer.Restart().
         {
             Thread t;
             lock (watchdogLock)
             {
                 t = DDWatchdog;
                 DDWatchdog = null;
             }
             if (t != null && t.IsAlive)
             {
                 t.Abort();
                 t.Join();
                 return null;
             }
             else
                 return "Server not running";
         }
string TGServerService.TGStationServer.SynchronizePush ()
Pushes the paths listed in TGS3.json to the currentl git remote. No other commit differences may exist for this function to succeed
Returns
on success, error on failure
Implements TGServiceInterface.ITGRepository.
Definition at line 946 of file Repository.cs.
References TGServerService.TGStationServer.Commit(), TGServerService.TGStationServer.LocalIsRemote(), TGServerService.TGStationServer.Push(), TGServerService.TGStationServer.RepoConfig.RepoConfig(), and TGServerService.TGStationServer.SSHAuth().
         {
             var Config = new RepoConfig(false);
             if (Config == null)
                 return "Error reading changelog configuration";
             if(!Config.ChangelogSupport || !SSHAuth())
                 return null;
             return LocalIsRemote() ? Commit(Config) ?? Push() : "Can't push changelog: HEAD does not match tracked remote branch";
         }
string TGServerService.TGStationServer.Update (bool reset)
Fetches the origin and merges it into the current branch
Parameters
reset If , the operation will perform a hard reset instead of a merge
Returns
on success, error message on failure
Implements TGServiceInterface.ITGRepository.
Definition at line 571 of file Repository.cs.
References TGServerService.TGStationServer.UpdateImpl().
         {
             return UpdateImpl(reset, true);
         }
string TGServerService.TGStationServer.UpdateImpl (bool reset, bool successOnUpToDate) private
Definition at line 576 of file Repository.cs.
References TGServerService.TGStationServer.DeletePRList(), TGServerService.TGStationServer.Fetch(), TGServerService.TGStationServer.LoadRepo(), TGServerService.TGStationServer.MergeBranch(), TGServerService.TGStationServer.RepoErrorUpToDate, TGServerService.TGStationServer.ResetNoLock(), TGServerService.TGStationServer.SendMessage(), and TGServerService.TGStationServer.UpdateSubmodules().
Referenced by TGServerService.TGStationServer.AutoUpdateTimer_Elapsed(), and TGServerService.TGStationServer.Update().
         {
             lock (RepoLock)
             {
                 var result = LoadRepo();
                 if (result != null)
                     return result;
                 try
                 {
                     if (Repo.Head == null || !Repo.Head.IsTracking)
                         return "Cannot update while not on a tracked branch";
                     var res = Fetch();
                     if (res != null)
                         return res;
                     var originBranch = Repo.Head.TrackedBranch;
                     if (!successOnUpToDate && Repo.Head.Tip.Sha == originBranch.Tip.Sha)
                         return RepoErrorUpToDate;
                     SendMessage(String.Format("REPO: Updating origin branch...({0})", reset ? "Hard Reset" : "Merge"), ChatMessageType.DeveloperInfo);
                     if (reset)
                     {
                         var error = ResetNoLock(Repo.Head.TrackedBranch);
                         UpdateSubmodules();
                         if (error != null)
                             throw new Exception(error);
                         DeletePRList();
                         TGServerService.WriteInfo("Repo hard updated to " + originBranch.Tip.Sha, TGServerService.EventID.RepoHardUpdate);
                         return error;
                     }
                     res = MergeBranch(originBranch.FriendlyName);
                     if (res != null)
                         throw new Exception(res);
                     UpdateSubmodules();
                     TGServerService.WriteInfo("Repo merge updated to " + originBranch.Tip.Sha, TGServerService.EventID.RepoMergeUpdate);
                     return null;
                 }
                 catch (Exception E)
                 {
                     SendMessage("REPO: Update failed!", ChatMessageType.DeveloperInfo);
                     TGServerService.WriteWarning(String.Format("Repo{0} update failed", reset ? " hard" : ""), reset ? TGServerService.EventID.RepoHardUpdateFail : TGServerService.EventID.RepoMergeUpdateFail);
                     return E.ToString();
                 }
             }
         }
void TGServerService.TGStationServer.UpdateInterfaceDll (bool overwrite) private
Definition at line 439 of file DreamDaemon.cs.
References TGServerService.TGStationServer.InterfaceDLLName.
Referenced by TGServerService.TGStationServer.InitialConfigureRepository(), TGServerService.TGStationServer.InitRepo(), and TGServerService.TGStationServer.StartImpl().
         {
             if (File.Exists(InterfaceDLLName) && !overwrite)
                 return;
             //Copy the interface dll to the static dir
             var InterfacePath = Assembly.GetAssembly(typeof(DDInteropCallHolder)).Location;
             File.Copy(InterfacePath, InterfaceDLLName, overwrite);
         }
void TGServerService.TGStationServer.UpdateLiveSha (string newSha) private
Definition at line 1245 of file Repository.cs.
References TGServerService.TGStationServer.LiveTrackingBranch, and TGServerService.TGStationServer.LoadRepo().
Referenced by TGServerService.TGStationServer.CompileImpl().
         {
             if (LoadRepo() != null)
                 return;
             var B = Repo.Branches[LiveTrackingBranch];
             if (B != null)
                 Repo.Branches.Remove(B);
             Repo.CreateBranch(LiveTrackingBranch, newSha);
         }
void TGServerService.TGStationServer.UpdateSubmodules () private
Definition at line 624 of file Repository.cs.
References TGServerService.Program.DeleteDirectory(), and TGServerService.TGStationServer.SendMessage().
Referenced by TGServerService.TGStationServer.Checkout(), TGServerService.TGStationServer.MergePullRequestImpl(), and TGServerService.TGStationServer.UpdateImpl().
         {
             var suo = new SubmoduleUpdateOptions
             {
                 Init = true
             };
             foreach (var I in Repo.Submodules)
                 try
                 {
                     Repo.Submodules.Update(I.Name, suo);
                 }
                 catch (Exception e)
                 {
                     //workaround for https://github.com/libgit2/libgit2/issues/3820
                     //kill off the modules/ folder in .git and try again
                     try
                     {
                         Program.DeleteDirectory(String.Format("{0}/.git/modules/{1}", RepoPath, I.Path));
                     }
                     catch
                     {
                         throw e;
                     }
                     Repo.Submodules.Update(I.Name, suo);
                     var msg = String.Format("I had to reclone submodule {0}. If this is happening a lot find a better hack or fix https://github.com/libgit2/libgit2/issues/3820!", I.Name);
                     SendMessage(String.Format("REPO: {0}", msg), ChatMessageType.DeveloperInfo);
                     TGServerService.WriteWarning(msg, TGServerService.EventID.SubmoduleReclone);
                 }
         }
string TGServerService.TGStationServer.UpdateTGS3Json ()
Updates the cached TGS3.json to the repo's version. Compiles will not succeed if these two to not match
Returns
on success, error message on failure
Implements TGServiceInterface.ITGRepository.
Definition at line 337 of file Repository.cs.
Referenced by TGServerService.TGStationServer.InitialConfigureRepository().
         {
             try
             {
                 if (File.Exists(RepoTGS3SettingsPath))
                     File.Copy(RepoTGS3SettingsPath, CachedTGS3SettingsPath, true);
                 else if (File.Exists(CachedTGS3SettingsPath))
                     File.Delete(CachedTGS3SettingsPath);
             }
             catch(Exception e)
             {
                 return e.ToString();
             }
             return null;
         }
bool TGServerService.TGStationServer.UpdateToVersion (int major, int minor)
updates the used byond version to that of version major .minor . The change won't take place until DD reboots. Calls ITGDreamDaemon.RequestRestart if blocked by a running DD instance. Runs asyncronously, use CurrentStatus to check progress
Parameters
major Major BYOND version. E.g. 511
minor Minor BYOND version. E.g. 1381
Returns
if the update started, if another operation was in progress or DreamDaemon is running
Implements TGServiceInterface.ITGByond.
Definition at line 240 of file Byond.cs.
References TGServerService.TGStationServer.BusyCheckNoLock(), TGServerService.TGStationServer.VersionInfo.major, TGServerService.TGStationServer.VersionInfo.minor, and TGServerService.TGStationServer.UpdateToVersionImpl().
         {
             lock (ByondLock)
             {
                 if (!BusyCheckNoLock())
                 {
                     updateStat = TGByondStatus.Starting;
                     RevisionStaging = new Thread(new ParameterizedThreadStart(UpdateToVersionImpl))
                     {
                         IsBackground = true //don't slow me down
                     };
                     RevisionStaging.Start(new VersionInfo { major = ma, minor = mi });
                     return true;
                 }
                 return false;
             }
         }
void TGServerService.TGStationServer.UpdateToVersionImpl (object param)
Definition at line 151 of file Byond.cs.
References TGServerService.TGStationServer.ApplyStagedUpdate(), TGServerService.TGStationServer.CleanByondStaging(), TGServerService.TGStationServer.DaemonStatus(), TGServerService.TGStationServer.RequestRestart(), TGServerService.TGStationServer.RevisionDownloadPath, and TGServerService.TGStationServer.SendMessage().
Referenced by TGServerService.TGStationServer.UpdateToVersion().
         {
             lock (ByondLock) {
                 if (updateStat != TGByondStatus.Starting)
                     return;
                 updateStat = TGByondStatus.Downloading;
             }
             try
             {
                 CleanByondStaging();
                 var vi = (VersionInfo)param;
                 using (var client = new WebClient())
                 {
                     SendMessage(String.Format("BYOND: Updating to version {0}.{1}...", vi.major, vi.minor), ChatMessageType.DeveloperInfo);
                     //DOWNLOADING
                     try
                     {
                         client.DownloadFile(String.Format(ByondRevisionsURL, vi.major, vi.minor), RevisionDownloadPath);
                     }
                     catch
                     {
                         SendMessage("BYOND: Update download failed. Does the specified version exist?", ChatMessageType.DeveloperInfo);
                         lastError = String.Format("Download of BYOND version {0}.{1} failed! Does it exist?", vi.major, vi.minor);
                         TGServerService.WriteWarning(String.Format("Failed to update BYOND to version {0}.{1}!", vi.major, vi.minor), TGServerService.EventID.BYONDUpdateFail);
                         lock (ByondLock)
{
                             updateStat = TGByondStatus.Idle;
                         }
                         return;
                     }
                 }
                 lock (ByondLock)
                 {
                     updateStat = TGByondStatus.Staging;
                 }
                 //STAGING
                 ZipFile.ExtractToDirectory(RevisionDownloadPath, StagingDirectory);
                 lock (ByondLock)
                 {
                     File.WriteAllText(StagingDirectoryInner + VersionFile, String.Format("{0}.{1}", vi.major, vi.minor));
                     //IMPORTANT: SET THE BYOND CONFIG TO NOT PROMPT FOR TRUSTED MODE REEE
                     Directory.CreateDirectory(ByondConfigDir);
                     File.WriteAllText(ByondConfigDir + ByondDDConfig, ByondNoPromptTrustedMode);
                 }
                 File.Delete(RevisionDownloadPath);
                 lock (ByondLock)
                 {
                     updateStat = TGByondStatus.Staged;
                 }
                 switch (DaemonStatus())
                 {
                     case TGDreamDaemonStatus.Offline:
                         if(ApplyStagedUpdate())
                             lastError = null;
                         else
                             lastError = "Failed to apply update!";
                         break;
                     default:
                         RequestRestart();
                         lastError = "Update staged. Awaiting server restart...";
                         SendMessage(String.Format("BYOND: Staging complete. Awaiting server restart...", vi.major, vi.minor), ChatMessageType.DeveloperInfo);
                         TGServerService.WriteInfo(String.Format("BYOND update {0}.{1} staged", vi.major, vi.minor), TGServerService.EventID.BYONDUpdateStaged);
                         break;
                 }
             }
             catch (ThreadAbortException)
             {
                 return;
             }
             catch (Exception e)
             {
                 TGServerService.WriteError("Revision staging errror: " + e.ToString(), TGServerService.EventID.BYONDUpdateFail);
                 lock (ByondLock)
                 {
                     updateStat = TGByondStatus.Idle;
                     lastError = e.ToString();
                     RevisionStaging = null;
                 }
             }
         }
void TGServerService.TGStationServer.VerifyConnection ()
Does nothing on the server end, but if the call completes, you can be sure you are connected. WCF won't throw until you try until you actually use the API
Implements TGServiceInterface.ITGConnectivity.
Definition at line 44 of file InterfaceBase.cs.
 { }
string TGServerService.TGStationServer.Version ()
Retrieve's the service's version
Returns
The service's version
Implements TGServiceInterface.ITGSService.
Definition at line 38 of file InterfaceBase.cs.
Referenced by TGServerService.TGStationServer.HandleCommand(), TGServerService.TGStationServer.InitDreamDaemon(), and TGServerService.TGStationServer.StartImpl().
         {
             return TGServerService.Version;
         }
void TGServerService.TGStationServer.Watchdog () private
Definition at line 238 of file DreamDaemon.cs.
References TGServerService.TGStationServer.currentPort, TGServerService.TGStationServer.MemTrackTimer_Elapsed(), TGServerService.TGStationServer.SCGracefulShutdown, TGServerService.TGStationServer.SendCommand(), TGServerService.TGStationServer.SendMessage(), TGServerService.TGStationServer.serviceCommsKey, TGServerService.TGStationServer.StartImpl(), and TGServerService.TGStationServer.WriteCurrentDDLog().
Referenced by TGServerService.TGStationServer.InitDreamDaemon(), and TGServerService.TGStationServer.StartImpl().
         {
             try
             {
                 lock (restartLock)
                 {
                     if (!RestartInProgress)
                     {
                         SendMessage("DD: Server started, watchdog active...", ChatMessageType.WatchdogInfo);
                         TGServerService.WriteInfo("Watchdog started", TGServerService.EventID.DDWatchdogStarted);
                     }
                     else
                     {
                         RestartInProgress = false;
                         TGServerService.WriteInfo("Watchdog started", TGServerService.EventID.DDWatchdogRestarted);
                     }
                 }
                 var retries = 0;
                 var MemTrackTimer = new System.Timers.Timer
                 {
                     AutoReset = true,
                     Interval = 5000 //every 5 seconds
                 };
                 MemTrackTimer.Elapsed += MemTrackTimer_Elapsed;
                 while (true)
                 {
                     var starttime = DateTime.Now;
                     lock (watchdogLock)
                     {
                         if (AwaitingShutdown == ShutdownRequestPhase.Requested)
                             SendCommand(SCGracefulShutdown);
                     }
                     //all good to go, let's start monitoring
                     var Now = DateTime.Now;
                     lock (watchdogLock)
                     {
                         CurrentDDLog = String.Format("{0} {1} Diagnostics.txt", Now.ToLongDateString(), Now.ToLongTimeString()).Replace(':', '-');
                         WriteCurrentDDLog("Starting monitoring...");
                         pcpu = new PerformanceCounter("Process", "% Processor Time", Proc.ProcessName, true);
                     }
                     MemTrackTimer.Start();
                     Proc.WaitForExit();
                     lock (watchdogLock) //synchronize
                     {
                         MemTrackTimer.Stop();
                         pcpu.Dispose();
                     }
                     WriteCurrentDDLog("Crash detected!");
                     lock (watchdogLock)
                     {
                         currentStatus = TGDreamDaemonStatus.HardRebooting;
                         currentPort = 0;
                         Proc.Close();
                         if (AwaitingShutdown == ShutdownRequestPhase.Pinged)
                             return;
                         var BadStart = (DateTime.Now - starttime).TotalSeconds < DDBadStartTime;
                         if (BadStart)
{
                             ++retries;
                             var sleep_time = (int)Math.Min(Math.Pow(2, retries), 3600); //max of one hour
                             SendMessage(String.Format("DD: Watchdog server startup failed! Retrying in {0} seconds...", sleep_time), ChatMessageType.WatchdogInfo);
                             Thread.Sleep(sleep_time * 1000);
                         }
                         else
{
                             retries = 0;
                             var msg = "DD: DreamDaemon crashed! Watchdog rebooting DD...";
                             SendMessage(msg, ChatMessageType.WatchdogInfo);
                             TGServerService.WriteWarning(msg, TGServerService.EventID.DDWatchdogRebootingServer);
                         }
                     }
                     var res = StartImpl(true);
                     if (res != null)
                         throw new Exception("Hard restart failed: " + res);
                 }
             }
             catch (ThreadAbortException)
             {
                 //No Mr bond, I expect you to die
                 try
                 {
                     if (!Properties.Settings.Default.ReattachToDD)
                     {
                         Proc.Kill();
                         Proc.WaitForExit();
                     }
                     else
                     {
                         Properties.Settings.Default.ReattachPID = Proc.Id;
                         Properties.Settings.Default.ReattachPort = currentPort;
                         Properties.Settings.Default.ReattachCommsKey = serviceCommsKey;
                         RestartInProgress = true;
                     }
                     Proc.Close();
                 }
                 catch
                 { }
             }
             catch (Exception e)
             {
                 SendMessage("DD: Watchdog thread crashed!", ChatMessageType.WatchdogInfo);
                 TGServerService.WriteError("Watch dog thread crashed: " + e.ToString(), TGServerService.EventID.DDWatchdogCrash);
             }
             finally
             {
                 lock (watchdogLock)
                 {
                     currentStatus = TGDreamDaemonStatus.Offline;
                     currentPort = 0;
                     AwaitingShutdown = ShutdownRequestPhase.None;
                     if (!RestartInProgress)
                     {
                         if(!Properties.Settings.Default.ReattachToDD)
                             SendMessage("DD: Server stopped, watchdog exiting...", ChatMessageType.WatchdogInfo);
                         TGServerService.WriteInfo("Watch dog exited", TGServerService.EventID.DDWatchdogExit);
                     }
                     else
                         TGServerService.WriteInfo("Watch dog restarting...", TGServerService.EventID.DDWatchdogRestart);
                 }
             }
         }
bool TGServerService.TGStationServer.Webclient ()
Check if the BYOND webclient is currently enabled for the server
Implements TGServiceInterface.ITGDreamDaemon.
Definition at line 595 of file DreamDaemon.cs.
         {
             return Properties.Settings.Default.Webclient;
         }
string TGServerService.TGStationServer.WorldAnnounce (string message)
Sends a message to everyone on the server
Implements TGServiceInterface.ITGDreamDaemon.
Definition at line 586 of file DreamDaemon.cs.
References TGServerService.TGStationServer.SanitizeTopicString(), TGServerService.TGStationServer.SCWorldAnnounce, and TGServerService.TGStationServer.SendCommand().
Referenced by TGServerService.TGStationServer.DisposeDreamDaemon().
         {
             var res = SendCommand(SCWorldAnnounce + ";message=" + SanitizeTopicString(message));
             if (res == "SUCCESS")
                 return null;
             return res;
         }
void TGServerService.TGStationServer.WriteCurrentDDLog (string message) private
Definition at line 227 of file DreamDaemon.cs.
Referenced by TGServerService.TGStationServer.DisposeDreamDaemon(), TGServerService.TGStationServer.HandleCommand(), TGServerService.TGStationServer.MemTrackTimer_Elapsed(), and TGServerService.TGStationServer.Watchdog().
         {
             lock (watchdogLock)
             {
                 if (currentStatus != TGDreamDaemonStatus.Online || CurrentDDLog == null)
                     return;
                 File.AppendAllText(Path.Combine(ResourceDiagnosticsDir, CurrentDDLog), String.Format("[{0}]: {1}\n", DateTime.Now.ToLongTimeString(), message));
             }
         }
string TGServerService.TGStationServer.WriteText (string staticRelativePath, string data, out bool unauthorized)
Write to a static file
Parameters
staticRelativePath The path from the Static dir. E.g. config/config.txt
data The full text of the config file
unauthorized This will be true if error is set to a message that indicates the current user does not have access to the specified file
Returns
null on success, error message on failure
Exceptions
CommunicationException Along with implied disconnect exceptions, if the file exceeds transfer limits
Implements TGServiceInterface.ITGConfig.
Definition at line 103 of file Config.cs.
References TGServerService.TGStationServer.StaticDirs.
         {
             try
             {
                 var path = StaticDirs + '/' + staticRelativePath;   //do not use path.combine or it will try and take the root
                 lock (configLock)
                 {
                     var di1 = new DirectoryInfo(StaticDirs);
                     var destdir = new FileInfo(path).Directory.FullName;
                     var di2 = new DirectoryInfo(destdir);
                     var good = false;
                     while (di2 != null)
                     {
                         if (di2.FullName == di1.FullName)
{
                             good = true;
                             break;
                         }
                         else di2 = di2.Parent;
                     }
                     if (!good)
                     {
                         unauthorized = false;
                         return "Cannot write above static directories!";
                     }
                     Directory.CreateDirectory(destdir);
                     File.WriteAllText(path, data);
                     TGServerService.CancelImpersonation();
                     TGServerService.WriteInfo("Write to " + path, TGServerService.EventID.StaticWrite);
                     unauthorized = false;
                     return null;
                 }
             }
             catch (UnauthorizedAccessException e)
             {
                 //no need for the full stacktrace
                 unauthorized = true;
                 return e.Message;
             }
             catch (Exception e)
             {
                 unauthorized = false;
                 return e.ToString();
             }
         }
Member Data Documentation
const string TGServerService.TGStationServer.ADirTest = GameDirA + LiveFile private
Definition at line 35 of file Compiler.cs.
object TGServerService.TGStationServer.authLock = new object() private
Definition at line 16 of file Administration.cs.
System.Timers.Timer TGServerService.TGStationServer.autoUpdateTimer private
Initial value:
= new System.Timers.Timer()
        {
            AutoReset = true
        }
Definition at line 35 of file Repository.cs.
Referenced by TGServerService.TGStationServer.InitRepo(), and TGServerService.TGStationServer.SetAutoUpdateInterval().
ShutdownRequestPhase TGServerService.TGStationServer.AwaitingShutdown private
Definition at line 41 of file DreamDaemon.cs.
const string TGServerService.TGStationServer.BDirTest = GameDirB + LiveFile private
Definition at line 36 of file Compiler.cs.
const string TGServerService.TGStationServer.ByondConfigDir = "BYOND_staged/BYOND/cfg" private
Definition at line 23 of file Byond.cs.
const string TGServerService.TGStationServer.ByondDDConfig = "/daemon.txt" private
Definition at line 24 of file Byond.cs.
const string TGServerService.TGStationServer.ByondDirectory = "BYOND" private
Definition at line 15 of file Byond.cs.
Referenced by TGServerService.TGStationServer.CompileImpl(), TGServerService.TGStationServer.GetVersion(), and TGServerService.TGStationServer.InitDreamDaemon().
const string TGServerService.TGStationServer.ByondLatestURL = "https://secure.byond.com/download/build/LATEST/" private
Definition at line 21 of file Byond.cs.
object TGServerService.TGStationServer.ByondLock = new object() private
Definition at line 28 of file Byond.cs.
Referenced by TGServerService.TGStationServer.MoveServer().
const string TGServerService.TGStationServer.ByondNoPromptTrustedMode = "trusted-check 0" private
Definition at line 25 of file Byond.cs.
const string TGServerService.TGStationServer.ByondRevisionsURL = "https://secure.byond.com/download/build/{0}/{0}.{1}_byond.zip" private
Definition at line 20 of file Byond.cs.
const string TGServerService.TGStationServer.CachedTGS3SettingsPath = "TGS3.json" private
Definition at line 18 of file Repository.cs.
Referenced by TGServerService.TGStationServer.RepoConfig.RepoConfig().
bool TGServerService.TGStationServer.canCancelCompilation = false private
Definition at line 47 of file Compiler.cs.
const string TGServerService.TGStationServer.CCPAdminOnly = "admin_only" private
Definition at line 41 of file Interop.cs.
const string TGServerService.TGStationServer.CCPHelpText = "help_text" private
Definition at line 40 of file Interop.cs.
const string TGServerService.TGStationServer.CCPRequiredParameters = "required_parameters" private
Definition at line 42 of file Interop.cs.
object TGServerService.TGStationServer.ChatLock = new object() private
Definition at line 94 of file Chat.cs.
IList<ITGChatProvider> TGServerService.TGStationServer.ChatProviders private
Definition at line 93 of file Chat.cs.
bool TGServerService.TGStationServer.Cloning = false private
Definition at line 30 of file Repository.cs.
const string TGServerService.TGStationServer.CommitMessage = "Automatic changelog compile, [ci skip]" private
Definition at line 26 of file Repository.cs.
const int TGServerService.TGStationServer.CommsKeyLen = 64 private
Definition at line 18 of file Interop.cs.
bool TGServerService.TGStationServer.compilationCancellationRequestation = false private
Definition at line 46 of file Compiler.cs.
TGCompilerStatus TGServerService.TGStationServer.compilerCurrentStatus private
Definition at line 42 of file Compiler.cs.
Referenced by TGServerService.TGStationServer.ApplyStagedUpdate(), TGServerService.TGStationServer.GetStatus(), and TGServerService.TGStationServer.MoveServer().
object TGServerService.TGStationServer.CompilerLock = new object() private
Definition at line 41 of file Compiler.cs.
Referenced by TGServerService.TGStationServer.ApplyStagedUpdate(), TGServerService.TGStationServer.HandleCommand(), TGServerService.TGStationServer.MoveServer(), and TGServerService.TGStationServer.Setup().
Thread TGServerService.TGStationServer.CompilerThread private
Definition at line 45 of file Compiler.cs.
object TGServerService.TGStationServer.configLock = new object() private
Definition at line 14 of file Config.cs.
Referenced by TGServerService.TGStationServer.Clone(), TGServerService.TGStationServer.MoveServer(), and TGServerService.TGStationServer.RecreateStaticFolder().
string TGServerService.TGStationServer.CurrentDDLog private
Definition at line 33 of file DreamDaemon.cs.
ushort TGServerService.TGStationServer.currentPort = 0 private
Definition at line 34 of file DreamDaemon.cs.
Referenced by TGServerService.TGStationServer.SendCommand(), and TGServerService.TGStationServer.Watchdog().
int TGServerService.TGStationServer.currentProgress = -1 private
Definition at line 33 of file Repository.cs.
Referenced by TGServerService.TGStationServer.CheckoutProgress().
TGDreamDaemonStatus TGServerService.TGStationServer.currentStatus private
Definition at line 32 of file DreamDaemon.cs.
Referenced by TGServerService.TGStationServer.CompileImpl(), TGServerService.TGStationServer.DaemonStatus(), TGServerService.TGStationServer.MoveServer(), TGServerService.TGStationServer.RecreateStaticFolder(), and TGServerService.TGStationServer.SendCommand().
const int TGServerService.TGStationServer.DDBadStartTime = 10 private
Definition at line 25 of file DreamDaemon.cs.
const int TGServerService.TGStationServer.DDHangStartTime = 60 private
Definition at line 24 of file DreamDaemon.cs.
Thread TGServerService.TGStationServer.DDWatchdog private
Definition at line 31 of file DreamDaemon.cs.
Referenced by TGServerService.TGStationServer.Stop().
const string TGServerService.TGStationServer.DiagnosticsDir = "Diagnostics" private
Definition at line 22 of file DreamDaemon.cs.
bool TGServerService.TGStationServer.disposedValue = false private
Definition at line 56 of file InterfaceBase.cs.
const string TGServerService.TGStationServer.EventFolder = "EventHandlers/" private
Definition at line 10 of file PreactionHandler.cs.
Version TGServerService.TGStationServer.GameAPIVersion private
Definition at line 24 of file Interop.cs.
Referenced by TGServerService.TGStationServer.InitDreamDaemon(), and TGServerService.TGStationServer.StartImpl().
const string TGServerService.TGStationServer.GameDir = "Game" private
Definition at line 29 of file Compiler.cs.
Referenced by TGServerService.TGStationServer.MoveServer().
const string TGServerService.TGStationServer.GameDirA = GameDir + "/A" private
Definition at line 30 of file Compiler.cs.
Referenced by TGServerService.TGStationServer.InvertDirectory().
const string TGServerService.TGStationServer.GameDirB = GameDir + "/B" private
Definition at line 31 of file Compiler.cs.
Referenced by TGServerService.TGStationServer.InvertDirectory().
const string TGServerService.TGStationServer.GameDirLive = GameDir + "/Live" private
Definition at line 32 of file Compiler.cs.
Referenced by TGServerService.TGStationServer.CanStartImpl(), and TGServerService.TGStationServer.StartImpl().
const string TGServerService.TGStationServer.InterfaceDLLName = "TGServiceInterface.dll" private
Definition at line 39 of file Compiler.cs.
Referenced by TGServerService.TGStationServer.CompileImpl(), TGServerService.TGStationServer.InitializeImpl(), and TGServerService.TGStationServer.UpdateInterfaceDll().
string TGServerService.TGStationServer.lastCompilerError private
Definition at line 43 of file Compiler.cs.
Referenced by TGServerService.TGStationServer.CompileError().
string TGServerService.TGStationServer.lastError private
Definition at line 29 of file Byond.cs.
Referenced by TGServerService.TGStationServer.GetError().
string TGServerService.TGStationServer.LastSeenUser = null private
Definition at line 17 of file Administration.cs.
const string TGServerService.TGStationServer.LibMySQLFile = "/libmysql.dll" private
Definition at line 27 of file Compiler.cs.
const string TGServerService.TGStationServer.LiveDirTest = GameDirLive + LiveFile private
Definition at line 37 of file Compiler.cs.
const string TGServerService.TGStationServer.LiveFile = "/TestLive.lk" private
Definition at line 34 of file Compiler.cs.
const string TGServerService.TGStationServer.LiveTrackingBranch = "___TGSLiveCommitTrackingBranch" private
Definition at line 25 of file Repository.cs.
Referenced by TGServerService.TGStationServer.LiveSha(), and TGServerService.TGStationServer.UpdateLiveSha().
readonly Version TGServerService.TGStationServer.MaxAPIVersion = new Version("3.1.0.99") private
Definition at line 23 of file Interop.cs.
Referenced by TGServerService.TGStationServer.CheckAPIVersionConstraints().
readonly Version TGServerService.TGStationServer.MinAPIVersion = new Version("3.1.0.0") private
Definition at line 22 of file Interop.cs.
PerformanceCounter TGServerService.TGStationServer.pcpu private
Definition at line 28 of file DreamDaemon.cs.
const string TGServerService.TGStationServer.PrivateKeyPath = RepoKeyDir + "private_key.txt" private
Definition at line 22 of file Repository.cs.
Referenced by TGServerService.TGStationServer.GenerateGitCredentials(), and TGServerService.TGStationServer.MoveServer().
const string TGServerService.TGStationServer.PRJobFile = "prtestjob.json" private
Definition at line 24 of file Repository.cs.
Referenced by TGServerService.TGStationServer.CompileImpl().
Process TGServerService.TGStationServer.Proc private
Definition at line 27 of file DreamDaemon.cs.
Referenced by TGServerService.TGStationServer.CompileImpl().
const string TGServerService.TGStationServer.PublicKeyPath = RepoKeyDir + "public_key.txt" private
Definition at line 23 of file Repository.cs.
Referenced by TGServerService.TGStationServer.GenerateGitCredentials().
Repository TGServerService.TGStationServer.Repo private
Definition at line 32 of file Repository.cs.
bool TGServerService.TGStationServer.RepoBusy = false private
Definition at line 29 of file Repository.cs.
Referenced by TGServerService.TGStationServer.CompileImpl(), TGServerService.TGStationServer.MoveServer(), and TGServerService.TGStationServer.OperationInProgress().
const string TGServerService.TGStationServer.RepoErrorUpToDate = "Already up to date!" private
Definition at line 19 of file Repository.cs.
Referenced by TGServerService.TGStationServer.MergeBranch(), and TGServerService.TGStationServer.UpdateImpl().
const string TGServerService.TGStationServer.RepoKeyDir = "RepoKey/" private
Definition at line 21 of file Repository.cs.
object TGServerService.TGStationServer.RepoLock = new object() private
Definition at line 28 of file Repository.cs.
Referenced by TGServerService.TGStationServer.CompileImpl(), TGServerService.TGStationServer.MoveServer(), and TGServerService.TGStationServer.RecreateStaticFolder().
const string TGServerService.TGStationServer.RepoPath = "Repository" private
Definition at line 16 of file Repository.cs.
Referenced by TGServerService.TGStationServer.CompileImpl(), and TGServerService.TGStationServer.ReadText().
const string TGServerService.TGStationServer.RepoTGS3SettingsPath = RepoPath + "/TGS3.json" private
Definition at line 17 of file Repository.cs.
const string TGServerService.TGStationServer.ResourceDiagnosticsDir = DiagnosticsDir + "/Resources" private
Definition at line 23 of file DreamDaemon.cs.
bool TGServerService.TGStationServer.RestartInProgress = false private
Definition at line 37 of file DreamDaemon.cs.
object TGServerService.TGStationServer.restartLock = new object() private
Definition at line 36 of file DreamDaemon.cs.
const string TGServerService.TGStationServer.RevisionDownloadPath = "BYONDRevision.zip" private
Definition at line 18 of file Byond.cs.
Referenced by TGServerService.TGStationServer.UpdateToVersionImpl().
Thread TGServerService.TGStationServer.RevisionStaging private
Definition at line 31 of file Byond.cs.
const string TGServerService.TGStationServer.SCAPICompat = "api_compat" private
Definition at line 31 of file Interop.cs.
const string TGServerService.TGStationServer.SCGracefulShutdown = "graceful_shutdown" private
Definition at line 28 of file Interop.cs.
Referenced by TGServerService.TGStationServer.RequestStop(), and TGServerService.TGStationServer.Watchdog().
const string TGServerService.TGStationServer.SCHardReboot = "hard_reboot" private
Definition at line 27 of file Interop.cs.
Referenced by TGServerService.TGStationServer.RequestRestart().
const string TGServerService.TGStationServer.SCListCustomCommands = "list_custom_commands" private
Definition at line 30 of file Interop.cs.
const string TGServerService.TGStationServer.SCPlayerCount = "client_count" private
Definition at line 32 of file Interop.cs.
const string TGServerService.TGStationServer.SCWorldAnnounce = "world_announce" private
Definition at line 29 of file Interop.cs.
Referenced by TGServerService.TGStationServer.WorldAnnounce().
List<Command> TGServerService.TGStationServer.ServerChatCommands private
Definition at line 44 of file Interop.cs.
string TGServerService.TGStationServer.serviceCommsKey private
Definition at line 19 of file Interop.cs.
Referenced by TGServerService.TGStationServer.InitDreamDaemon(), TGServerService.TGStationServer.StartImpl(), and TGServerService.TGStationServer.Watchdog().
readonly SecurityIdentifier TGServerService.TGStationServer.ServiceSID = WindowsIdentity.GetCurrent().User private
Definition at line 19 of file Administration.cs.
Referenced by TGServerService.TGStationServer.CheckAccessCore().
bool TGServerService.TGStationServer.silentCompile = false private
Definition at line 48 of file Compiler.cs.
Referenced by TGServerService.TGStationServer.CompileImpl().
const string TGServerService.TGStationServer.SRAPIVersion = "api_ver" private
Definition at line 38 of file Interop.cs.
const string TGServerService.TGStationServer.SRIRCAdminChannelMessage = "send2irc" private
Definition at line 36 of file Interop.cs.
const string TGServerService.TGStationServer.SRIRCBroadcast = "irc" private
Definition at line 35 of file Interop.cs.
const string TGServerService.TGStationServer.SRKillProcess = "killme" private
Definition at line 34 of file Interop.cs.
const string TGServerService.TGStationServer.SRWorldReboot = "worldreboot" private
Definition at line 37 of file Interop.cs.
const string TGServerService.TGStationServer.SSHPushRemote = "ssh_push_target" private
Definition at line 20 of file Repository.cs.
const string TGServerService.TGStationServer.StagingDirectory = "BYOND_staged" private
Definition at line 16 of file Byond.cs.
const string TGServerService.TGStationServer.StagingDirectoryInner = "BYOND_staged/byond" private
Definition at line 17 of file Byond.cs.
TGDreamDaemonSecurity TGServerService.TGStationServer.StartingSecurity private
Definition at line 39 of file DreamDaemon.cs.
const string TGServerService.TGStationServer.StaticBackupDir = "Static_BACKUP" private
Definition at line 25 of file Compiler.cs.
Referenced by TGServerService.TGStationServer.BackupAndDeleteStaticDirectory().
const string TGServerService.TGStationServer.StaticDirs = "Static" private
Definition at line 24 of file Compiler.cs.
Referenced by TGServerService.TGStationServer.BackupAndDeleteStaticDirectory(), TGServerService.TGStationServer.DeleteFile(), TGServerService.TGStationServer.InitialConfigureRepository(), TGServerService.TGStationServer.ListStaticDirectory(), TGServerService.TGStationServer.ReadText(), and TGServerService.TGStationServer.WriteText().
SecurityIdentifier TGServerService.TGStationServer.TheDroidsWereLookingFor private
Definition at line 15 of file Administration.cs.
object TGServerService.TGStationServer.topicLock = new object() private
Definition at line 17 of file Interop.cs.
Referenced by TGServerService.TGStationServer.StartImpl().
bool TGServerService.TGStationServer.UpdateStaged = false private
Definition at line 50 of file Compiler.cs.
Referenced by TGServerService.TGStationServer.HandleCommand().
TGByondStatus TGServerService.TGStationServer.updateStat = TGByondStatus.Idle private
Definition at line 27 of file Byond.cs.
Referenced by TGServerService.TGStationServer.CurrentStatus(), and TGServerService.TGStationServer.MoveServer().
const string TGServerService.TGStationServer.VersionFile = "/byond_version.dat" private
Definition at line 19 of file Byond.cs.
Referenced by TGServerService.TGStationServer.GetVersion().
object TGServerService.TGStationServer.watchdogLock = new object() private
Definition at line 30 of file DreamDaemon.cs.
Referenced by TGServerService.TGStationServer.CompileImpl(), TGServerService.TGStationServer.MoveServer(), TGServerService.TGStationServer.RecreateStaticFolder(), and TGServerService.TGStationServer.SendCommand().
The documentation for this class was generated from the following files:
TGServerService/Administration.cs
TGServerService/Byond.cs
TGServerService/Chat.cs
TGServerService/Compiler.cs
TGServerService/Config.cs
TGServerService/DreamDaemon.cs
TGServerService/InterfaceBase.cs
TGServerService/Interop.cs
TGServerService/PreactionHandler.cs
TGServerService/Repository.cs