tgstation-server: TGControlPanel.Program Class Reference
TGControlPanel.Program Class Reference
Static Public Member Functions
static void ServiceDisconnectException (Exception e)
static string TextPrompt (string caption, string text)
static bool RateLimitPrompt (Octokit.GitHubClient client)
Prompts the user to open the GitHubLoginPrompt explaining the API rate limit
static bool GetRepositoryRemote (ITGRepository repo, out string owner, out string name)
Gets the owner and name of a given repo 's remote. Shows an error if the target remote isn't GitHub
Static Private Member Functions
static void Main (string[] args)
static bool BadCertificateHandler (string message)
Static Private Attributes
static bool SSLErrorPromptResult = false
Detailed Description
Definition at line 8 of file Program.cs.
Member Function Documentation
static bool TGControlPanel.Program.BadCertificateHandler (string message) static private
Definition at line 38 of file Program.cs.
Referenced by TGControlPanel.Program.Main().
         {
             if (!SSLErrorPromptResult)
             {
                 var result = MessageBox.Show(message + " IT IS HIGHLY RECCOMENDED YOU DO NOT PROCEED! Continue?", "SSL Error", MessageBoxButtons.YesNo) == DialogResult.Yes;
                 SSLErrorPromptResult = result;
                 return result;
             }
             return true;
         }
static bool TGControlPanel.Program.GetRepositoryRemote (ITGRepository repo, out string owner, out string name) static
Gets the owner and name of a given repo 's remote. Shows an error if the target remote isn't GitHub
Parameters
repo The ITGRepository to get the remote of
owner The owner of the remote Octokit.Repository
name The remote Octokit.Repository.Name
Returns
if repo 's remote was a valid GitHub Octokit.Repository, otherwise and the user was prompted
Definition at line 98 of file Program.cs.
References TGServiceInterface.Components.ITGRepository.GetRemote().
Referenced by TGControlPanel.TestMergeManager.PullRequestManager_Load(), and TGControlPanel.ControlPanel.UpdateServer().
         {
             string remote = null;
             remote = repo.GetRemote(out string error);
             if (remote == null)
             {
                 MessageBox.Show(String.Format("Error retrieving remote repository: {0}", error));
                 owner = null;
                 name = null;
                 return false;
             }
             if (!remote.Contains("github.com"))
             {
                 MessageBox.Show("Pull request support is only available for GitHub based repositories!", "Error");
                 owner = null;
                 name = null;
                 return false;
             }
             //Assume standard gh format: [(git)|(https)]://github.com/owner/repo(.git)[0-1]
             var splits = remote.Split('/');
             name = splits[splits.Length - 1];
             owner = splits[splits.Length - 2].Split('.')[0];
             return true;
         }
static void TGControlPanel.Program.Main (string[] args) static private
Definition at line 11 of file Program.cs.
References TGControlPanel.Program.BadCertificateHandler(), TGControlPanel.Program.ServiceDisconnectException(), and TGServiceInterface.Interface.SetBadCertificateHandler().
         {
             try
             {
                 if (Properties.Settings.Default.UpgradeRequired)
                 {
                     Properties.Settings.Default.Upgrade();
                     Properties.Settings.Default.UpgradeRequired = false;
                     Properties.Settings.Default.Save();
                 }
                 Application.EnableVisualStyles();
                 Application.SetCompatibleTextRenderingDefault(false);
                 Interface.SetBadCertificateHandler(BadCertificateHandler);
                 var login = new Login();
                 login.Show();
                 Application.Run();
             }
             catch (Exception e)
             {
                 ServiceDisconnectException(e);
             }
             finally
             {
                 Properties.Settings.Default.Save();
             }
         }
static bool TGControlPanel.Program.RateLimitPrompt (Octokit.GitHubClient client) static
Prompts the user to open the GitHubLoginPrompt explaining the API rate limit
Parameters
client The Octokit.GitHubClient to use
Returns
if the GitHubLoginPrompt ran and returned a DialogResult.OK, otherwise
Definition at line 83 of file Program.cs.
Referenced by TGControlPanel.TestMergeManager.LoadPullRequests(), TGControlPanel.ControlPanel.RemoveAllTestMergesButton_Click(), and TGControlPanel.ControlPanel.UpdateServer().
         {
             if (MessageBox.Show("You seem to have hit the rate limit of 60 requests per hour of the GitHub API for anonymous requests. Would you like to enter credentials to bypass this?", "Rate limited", MessageBoxButtons.YesNo) != DialogResult.Yes)
                 return false;
             using (var D = new GitHubLoginPrompt(client))
                 return D.ShowDialog() == DialogResult.OK;
         }
static void TGControlPanel.Program.ServiceDisconnectException (Exception e) static
Definition at line 49 of file Program.cs.
Referenced by TGControlPanel.Program.Main().
         {
             MessageBox.Show("An unhandled exception occurred. This usually means we lost connection to the service. Error" + e.ToString());
         }
static string TGControlPanel.Program.TextPrompt (string caption, string text) static
Definition at line 54 of file Program.cs.
Referenced by TGControlPanel.InstanceSelector.CreateInstanceButton_Click(), TGControlPanel.InstanceSelector.ImportInstanceButton_Click(), TGControlPanel.InstanceSelector.RenameInstanceButton_Click(), and TGControlPanel.ControlPanel.StaticFileCreateButton_Click().
         {
             Form prompt = new Form()
             {
                 Width = 500,
                 Height = 150,
                 FormBorderStyle = FormBorderStyle.FixedDialog,
                 Text = caption,
                 StartPosition = FormStartPosition.CenterScreen,
                 MaximizeBox = false,
                 MinimizeBox = false,
             };
             Label textLabel = new Label() { Left = 50, Top = 20, Text = text, AutoSize = true };
             TextBox textBox = new TextBox() { Left = 50, Top = 50, Width = 400 };
             Button confirmation = new Button() { Text = "Ok", Left = 350, Width = 100, Top = 70, DialogResult = DialogResult.OK };
             confirmation.Click += (sender, e) => { prompt.Close(); };
             prompt.Controls.Add(textBox);
             prompt.Controls.Add(confirmation);
             prompt.Controls.Add(textLabel);
             prompt.AcceptButton = confirmation;
             return prompt.ShowDialog() == DialogResult.OK ? textBox.Text : null;
         }
Member Data Documentation
bool TGControlPanel.Program.SSLErrorPromptResult = false static private
Definition at line 37 of file Program.cs.
The documentation for this class was generated from the following file:
TGControlPanel/Program.cs