tgstation-server: TGServiceInterface.Interface Class Reference
TGServiceInterface.Interface Class Reference
Main inteface class for the service
Public Member Functions
Interface ()
Construct an Interface for a local connection
Interface (string address, ushort port, string username, string password)
Construct an Interface for a remote connection
Interface (Interface other)
Constructs an Interface that connects to the same ITGSService as some other ITGInstance
ConnectivityLevel ConnectToInstance (string instanceName=null, bool skipChecks=false)
Targets instanceName as the instance to use with GetComponent<T>. Closes all connections to any previous instance
bool VersionMismatch (out string errorMessage)
Returns if the Interface interface being used to connect to a service does not have the same release version as the service
T GetComponent< T > ()
Returns the requested Interface component for the instance InstanceName. This does not guarantee a successful connection. ChannelFactory<TChannel>s created this way are recycled for minimum latency and bandwidth usage
ITGSService GetService ()
Returns the ITGSService component for the service
ConnectivityLevel ConnectionStatus ()
Used to test if the ITGSService is avaiable on the target machine. Note that state can change at any time and any call into the may throw an exception because of communcation errors
ConnectivityLevel ConnectionStatus (out string error)
Used to test if the ITGSService is avaiable on the target machine. Note that state can change at any time and any call into the may throw an exception because of communcation errors
void Dispose ()
Implements the IDisposable pattern
Static Public Member Functions
static void SetBadCertificateHandler (Func< string, bool > handler)
Sets the function called when a remote login fails due to the server having an invalid SSL cert
Public Attributes
const long TransferLimitLocal = Int32.MaxValue
The maximum message size to and from a local server
const long TransferLimitRemote = 10485760
The maximum message size to and from a remote server
const string MasterInterfaceName = "TGStationServerService"
Base name of communication URLs
const string InstanceInterfaceName = MasterInterfaceName + "/Instance"
Base name of instance URLs
readonly string HTTPSURL
If this is set, we will try and connect to an HTTPS server running at this address
readonly ushort HTTPSPort
The port used by the service
Static Public Attributes
static readonly IList< Type > ValidInterfaces = CollectComponents()
List of s that can be used with GetComponent<T> and CreateChannel<T>
Properties
string InstanceName [get, private set]
The name of the current instance in use. Defaults to
bool IsRemoteConnection [get]
Checks if the Interface is setup for a remote connection
Private Member Functions
void CloseAllChannels (bool includingRoot)
Closes all ChannelFactorys stored in ChannelFactoryCache and clears it
T GetComponentImpl< T > (bool useInstanceName)
ChannelFactory< T > CreateChannel< T > (string instanceName)
Directly creates a ChannelFactory<TChannel> for T without caching. This should be eventually closed by the caller
void Dispose (bool disposing)
Implements the IDisposable pattern. Calls CloseAllChannels
Static Private Member Functions
static IList< Type > CollectComponents ()
Returns a IList<T> of Types that can be used with the service
static void ChannelFactory_Closed (object sender, EventArgs e)
Disposes a closed ChannelFactory
Private Attributes
readonly string HTTPSUsername
Username for remote operations
readonly string HTTPSPassword
Password for remote operations
IDictionary< string, ChannelFactory > ChannelFactoryCache = new Dictionary<string, ChannelFactory>()
Associated list of open ChannelFactorys keyed by type name. A ChannelFactory in this list may close or fault at any time. Must be locked before being accessed
bool disposedValue = false
To detect redundant Dispose(bool) calls
Detailed Description
Main inteface class for the service
Definition at line 17 of file Interface.cs.
Constructor & Destructor Documentation
TGServiceInterface.Interface.Interface ()
Construct an Interface for a local connection
Definition at line 125 of file Interface.cs.
 { }
TGServiceInterface.Interface.Interface (string address, ushort port, string username, string password)
Construct an Interface for a remote connection
Parameters
address The address of the remote server
port The port the remote server runs on
username Windows account username for the remote server
password Windows account password for the remote server
Definition at line 134 of file Interface.cs.
         {
             HTTPSURL = address;
             HTTPSPort = port;
             HTTPSUsername = username;
             HTTPSPassword = password;
         }
TGServiceInterface.Interface.Interface (Interface other)
Constructs an Interface that connects to the same ITGSService as some other ITGInstance
Parameters
other
Definition at line 146 of file Interface.cs.
 : this(other.HTTPSURL, other.HTTPSPort, other.HTTPSUsername, other.HTTPSPassword) { }
Member Function Documentation
static void TGServiceInterface.Interface.ChannelFactory_Closed (object sender, EventArgs e) static private
Disposes a closed ChannelFactory
Parameters
sender The channel factory that was closed
e The event arguments
Definition at line 251 of file Interface.cs.
References TGServiceInterface.Interface.Dispose().
Referenced by TGServiceInterface.Interface.CloseAllChannels().
         {
             (sender as IDisposable).Dispose();
         }
void TGServiceInterface.Interface.CloseAllChannels (bool includingRoot) private
Closes all ChannelFactorys stored in ChannelFactoryCache and clears it
Parameters
includingRoot If set to , doesn't clear the channels that are used by ITGSService
Definition at line 203 of file Interface.cs.
References TGServiceInterface.Interface.ChannelFactory_Closed().
Referenced by TGServiceInterface.Interface.ConnectToInstance(), and TGServiceInterface.Interface.Dispose().
         {
             string[] RootThings = { typeof(ITGSService).Name, 'S' + typeof(ITGConnectivity).Name };
             lock (ChannelFactoryCache)
             {
                 foreach (var I in ChannelFactoryCache)
                 {
                     if (RootThings.Contains(I.Key))
                         continue;
                     var cf = I.Value;
                     try
                     {
                         cf.Closed += ChannelFactory_Closed;
                         cf.Close();
                     }
                     catch
                     {
                         cf.Abort();
                     }
                     ChannelFactoryCache.Remove(I);
                 }
             }
         }
static IList<Type> TGServiceInterface.Interface.CollectComponents () static private
Returns a IList<T> of Types that can be used with the service
Returns
A IList<T> of Types that can be used with the service
Definition at line 78 of file Interface.cs.
         {
             var ServiceComponent = typeof(ITGSService); //this is special
                                                         //find all interfaces in this assembly in this namespace that have the service contract attribute
             var query = from t in Assembly.GetExecutingAssembly().GetTypes()
                         where t.IsInterface
                         && t.Namespace == ServiceComponent.Namespace
                         && t.GetCustomAttribute(typeof(ServiceContractAttribute)) != null
                         && t != ServiceComponent
                         select t;
             return query.ToList();
         }
ConnectivityLevel TGServiceInterface.Interface.ConnectionStatus ()
Used to test if the ITGSService is avaiable on the target machine. Note that state can change at any time and any call into the may throw an exception because of communcation errors
Returns
on successful connection, error message string on failure
Definition at line 352 of file Interface.cs.
Referenced by TGInstallerWrapper.Main.CheckForExistingVersion(), TGCommandLine.CLICommand.CLICommand(), TGServiceInterface.Interface.ConnectToInstance(), TGCommandLine.Program.Main(), TGCommandLine.Program.RunCommandLine(), TGInstallerWrapper.Main.TellServiceWereComingForThem(), and TGControlPanel.Login.VerifyAndConnect().
         {
             return ConnectionStatus(out string unused);
         }
ConnectivityLevel TGServiceInterface.Interface.ConnectionStatus (out string error)
Used to test if the ITGSService is avaiable on the target machine. Note that state can change at any time and any call into the may throw an exception because of communcation errors
Parameters
error String of the error that prevented an elevated connectivity level
Returns
The apporopriate ConnectivityLevel
Definition at line 362 of file Interface.cs.
References TGServiceInterface.Interface.disposedValue, and TGServiceInterface.Interface.GetService().
         {
             try
             {
                 GetComponentImpl<ITGConnectivity>(false).VerifyConnection();
             }
             catch (CommunicationException e)
             {
                 error = e.ToString();
                 return ConnectivityLevel.None;
             }
             var service = GetService();
             try
             {
                 service.Version();
             }
             catch(Exception e)
             {
                 error = e.ToString();
                 return ConnectivityLevel.Connected;
             }
             try
             {
                 // TODO
                 error = null;
                 return ConnectivityLevel.Administrator;
             }
             catch(Exception e)
             {
                 error = e.ToString();
                 return ConnectivityLevel.Authenticated;
             }
         }
ConnectivityLevel TGServiceInterface.Interface.ConnectToInstance (string instanceName = null, bool skipChecks = false)
Targets instanceName as the instance to use with GetComponent<T>. Closes all connections to any previous instance
Parameters
instanceName The name of the instance to connect to
skipChecks If set to , skips the connectivity and authentication checks, sets InstanceName, and returns ConnectivityLevel.Connected
Returns
The apporopriate ConnectivityLevel
Definition at line 154 of file Interface.cs.
References TGServiceInterface.Interface.CloseAllChannels(), TGServiceInterface.Interface.ConnectionStatus(), and TGServiceInterface.Interface.InstanceName.
Referenced by TGCommandLine.Program.CheckInstanceConnectivity(), TGCommandLine.CLICommand.CLICommand(), TGCommandLine.InstanceRootCommand.DoRun(), TGControlPanel.ControlPanel.InitStaticPage(), and TGControlPanel.Login.VerifyAndConnect().
         {
             if (instanceName == null)
                 instanceName = InstanceName;
             if (!skipChecks && !ConnectionStatus().HasFlag(ConnectivityLevel.Connected))
                 return ConnectivityLevel.None;
             var prevInstance = InstanceName;
             if (prevInstance != instanceName)
                 CloseAllChannels(false);
             InstanceName = instanceName;
             if (skipChecks)
                 return ConnectivityLevel.Connected;
             try
             {
                 GetComponent<ITGConnectivity>().VerifyConnection();
             }
             catch
             {
                 InstanceName = prevInstance;
                 return ConnectivityLevel.None;
             }
             try
             {
                 GetComponent<ITGInstance>().ServerDirectory();
             }
             catch
             {
                 return ConnectivityLevel.Connected;
             }
             try
             {
                 GetComponent<ITGAdministration>().GetCurrentAuthorizedGroup();
                 return ConnectivityLevel.Administrator;
             }
             catch
             {
                 return ConnectivityLevel.Authenticated;
             }
         }
ChannelFactory<T> TGServiceInterface.Interface.CreateChannel< T > (string instanceName) private
Directly creates a ChannelFactory<TChannel> for T without caching. This should be eventually closed by the caller
Template Parameters
T The component of the channel to be created
Returns
The correct ChannelFactory<TChannel>
Exceptions
Exception Thrown if T isn't a valid component
Definition at line 315 of file Interface.cs.
References TGServiceInterface.Interface.HTTPSPassword, TGServiceInterface.Interface.HTTPSUsername, and TGServiceInterface.Interface.IsRemoteConnection.
Referenced by TGServiceInterface.Interface.GetComponentImpl< T >().
         {
             var accessPath = instanceName == null ? MasterInterfaceName : String.Format("{0}/{1}", InstanceInterfaceName, instanceName);
             var InterfaceName = typeof(T).Name;
             if (!IsRemoteConnection)
             {
                 var res2 = new ChannelFactory<T>(
                 new NetNamedPipeBinding { SendTimeout = new TimeSpan(0, 0, 30), MaxReceivedMessageSize = TransferLimitLocal }, new EndpointAddress(String.Format("net.pipe://localhost/{0}/{1}", accessPath, InterfaceName)));                                                      //10 megs
                 res2.Credentials.Windows.AllowedImpersonationLevel = TokenImpersonationLevel.Impersonation;
                 return res2;
             }
             //okay we're going over
             var binding = new WSHttpBinding()
             {
                 SendTimeout = new TimeSpan(0, 0, 40),
                 MaxReceivedMessageSize = TransferLimitRemote
             };
             var requireAuth = InterfaceName != typeof(ITGConnectivity).Name;
             binding.Security.Transport.ClientCredentialType = HttpClientCredentialType.None;
             binding.Security.Mode = requireAuth ? SecurityMode.TransportWithMessageCredential : SecurityMode.Transport;    //do not require auth for a connectivity check
             binding.Security.Message.ClientCredentialType = requireAuth ? MessageCredentialType.UserName : MessageCredentialType.None;
             var address = new EndpointAddress(String.Format("https://{0}:{1}/{2}/{3}", HTTPSURL, HTTPSPort, accessPath, InterfaceName));
             var res = new ChannelFactory<T>(binding, address);
             if (requireAuth)
             {
                 res.Credentials.UserName.UserName = HTTPSUsername;
                 res.Credentials.UserName.Password = HTTPSPassword;
             }
             return res;
         }
void TGServiceInterface.Interface.Dispose (bool disposing) private
Implements the IDisposable pattern. Calls CloseAllChannels
Parameters
disposing if Dispose() was called manually, if it was from the finalizer
Definition at line 407 of file Interface.cs.
References TGServiceInterface.Interface.CloseAllChannels().
Referenced by TGControlPanel.Login.VerifyAndConnect().
         {
             if (!disposedValue)
             {
                 if (disposing)
                 {
                     CloseAllChannels(true);
                 }
                 // TODO: free unmanaged resources (unmanaged objects) and override a finalizer below.
                 // TODO: set large fields to null.
                 disposedValue = true;
             }
         }
void TGServiceInterface.Interface.Dispose ()
Implements the IDisposable pattern
Definition at line 432 of file Interface.cs.
Referenced by TGServiceInterface.Interface.ChannelFactory_Closed().
         {
             // Do not change this code. Put cleanup code in Dispose(bool disposing) above.
             Dispose(true);
             // TODO: uncomment the following line if the finalizer is overridden above.
             // GC.SuppressFinalize(this);
         }
T TGServiceInterface.Interface.GetComponent< T > ()
Returns the requested Interface component for the instance InstanceName. This does not guarantee a successful connection. ChannelFactory<TChannel>s created this way are recycled for minimum latency and bandwidth usage
Template Parameters
T The component to retrieve
Returns
The correct component
Definition at line 261 of file Interface.cs.
References TGServiceInterface.Interface.GetComponentImpl< T >().
         {
             var ToT = typeof(T);
             if (!ValidInterfaces.Contains(ToT) && ToT != typeof(ITGSService))
                 throw new Exception("Invalid type!");
             return GetComponentImpl<T>(true);
         }
T TGServiceInterface.Interface.GetComponentImpl< T > (bool useInstanceName) private
Definition at line 269 of file Interface.cs.
References TGServiceInterface.Interface.CreateChannel< T >(), and TGServiceInterface.Interface.InstanceName.
Referenced by TGServiceInterface.Interface.GetComponent< T >().
         {
             if (useInstanceName & InstanceName == null)
                 throw new Exception("Instance not selected!");
             var actualToT = typeof(T);
             var tot = actualToT.Name;
             if (actualToT == typeof(ITGConnectivity) && !useInstanceName)
                 tot = 'S' + tot;
             ChannelFactory<T> cf;
             lock (ChannelFactoryCache)
             {
                 if (ChannelFactoryCache.ContainsKey(tot))
                     try
                     {
                         cf = ((ChannelFactory<T>)ChannelFactoryCache[tot]);
                         if (cf.State != CommunicationState.Opened)
                             throw new Exception();
                         return cf.CreateChannel();
                     }
                     catch
                     {
                         ChannelFactoryCache[tot].Abort();
                         ChannelFactoryCache.Remove(tot);
                     }
                 cf = CreateChannel<T>(useInstanceName ? InstanceName : null);
                 ChannelFactoryCache[tot] = cf;
             }
             return cf.CreateChannel();
         }
ITGSService TGServiceInterface.Interface.GetService ()
Returns the ITGSService component for the service
Returns
The ITGSService component for the service
Definition at line 304 of file Interface.cs.
Referenced by TGServiceInterface.Interface.ConnectionStatus(), TGCommandLine.ServiceCreateInstanceCommand.Run(), TGCommandLine.ServiceListInstancesCommand.Run(), TGCommandLine.ServiceDetachInstanceCommand.Run(), TGCommandLine.ServiceImportInstanceCommand.Run(), TGCommandLine.ServicePythonPathCommand.Run(), TGCommandLine.ServiceSetPythonPathCommand.Run(), TGCommandLine.ServiceEnableInstanceCommand.Run(), TGCommandLine.ServiceDisableInstanceCommand.Run(), TGCommandLine.ServiceRemoteAccessPortCommand.Run(), TGCommandLine.ServiceSetRemoteAccessPortCommand.Run(), TGCommandLine.ServiceRenameInstanceCommand.Run(), TGCommandLine.Program.RunCommandLine(), and TGServiceInterface.Interface.VersionMismatch().
         {
             return GetComponentImpl<ITGSService>(false);
         }
static void TGServiceInterface.Interface.SetBadCertificateHandler (Func< string, bool > handler) static
Sets the function called when a remote login fails due to the server having an invalid SSL cert
Parameters
handler The Func<T, TResult> to be called when a remote login is attempted while the server posesses a bad certificate. Passed a string of error information about the and should return if it the connection should be made anyway
Definition at line 95 of file Interface.cs.
Referenced by TGControlPanel.Program.Main(), TGCommandLine.Program.Main(), TGServiceInterface.Tests.TestInterface.TestBadCertificateHandler(), and TGServiceInterface.Tests.TestInterface.TestSetBadCertificateHandler().
         {
             ServicePointManager.ServerCertificateValidationCallback = (sender, cert, chain, error) =>
             {
                 string ErrorMessage;
                 switch (error)
                 {
                     case SslPolicyErrors.None:
                         return true;
                     case SslPolicyErrors.RemoteCertificateChainErrors:
                         ErrorMessage = "There are certificate chain errors.";
                         break;
                     case SslPolicyErrors.RemoteCertificateNameMismatch:
                         ErrorMessage = "The certificate name does not match.";
                         break;
                     case SslPolicyErrors.RemoteCertificateNotAvailable:
                         ErrorMessage = "The certificate doesn't exist in the trust store.";
                         break;
                     default:
                         ErrorMessage = "An unknown error occurred.";
                         break;
                 }
                 ErrorMessage = String.Format("The server's certificate failed to verify! Error: {0} Cert: {1}", ErrorMessage, cert.ToString());
                 return handler(ErrorMessage);
             };
         }
bool TGServiceInterface.Interface.VersionMismatch (out string errorMessage)
Returns if the Interface interface being used to connect to a service does not have the same release version as the service
Parameters
errorMessage An error message to display to the user should this function return
Returns
if the Interface interface being used to connect to a service does not have the same release version as the service
Definition at line 232 of file Interface.cs.
References TGServiceInterface.Interface.GetService(), and TGServiceInterface.Components.ITGSService.Version().
Referenced by TGCommandLine.Program.Main(), and TGCommandLine.Program.RunCommandLine().
         {
             var splits = GetService().Version().Split(' ');
             var theirs = new Version(splits[splits.Length - 1].Substring(1));
             var ours = new Version(FileVersionInfo.GetVersionInfo(System.Reflection.Assembly.GetExecutingAssembly().Location).FileVersion);
             if(theirs.Major != ours.Major || theirs.Minor != ours.Minor || theirs.Revision != ours.Revision)    //don't care about the patch level
             {
                 errorMessage = String.Format("Version mismatch between interface version ({0}) and service version ({1}). Some functionality may crash this program.", ours, theirs);
                 return true;
             }
             errorMessage = null;
             return false;
         }
Member Data Documentation
IDictionary<string, ChannelFactory> TGServiceInterface.Interface.ChannelFactoryCache = new Dictionary<string, ChannelFactory>() private
Associated list of open ChannelFactorys keyed by type name. A ChannelFactory in this list may close or fault at any time. Must be locked before being accessed
Definition at line 72 of file Interface.cs.
bool TGServiceInterface.Interface.disposedValue = false private
To detect redundant Dispose(bool) calls
Definition at line 401 of file Interface.cs.
Referenced by TGServiceInterface.Interface.ConnectionStatus().
readonly string TGServiceInterface.Interface.HTTPSPassword private
Password for remote operations
Definition at line 67 of file Interface.cs.
Referenced by TGServiceInterface.Interface.CreateChannel< T >().
readonly ushort TGServiceInterface.Interface.HTTPSPort
The port used by the service
Definition at line 57 of file Interface.cs.
readonly string TGServiceInterface.Interface.HTTPSURL
If this is set, we will try and connect to an HTTPS server running at this address
Definition at line 52 of file Interface.cs.
readonly string TGServiceInterface.Interface.HTTPSUsername private
Username for remote operations
Definition at line 62 of file Interface.cs.
Referenced by TGServiceInterface.Interface.CreateChannel< T >().
const string TGServiceInterface.Interface.InstanceInterfaceName = MasterInterfaceName + "/Instance"
Base name of instance URLs
Definition at line 41 of file Interface.cs.
Referenced by TGServerService.Service.SetupInstance().
const string TGServiceInterface.Interface.MasterInterfaceName = "TGStationServerService"
Base name of communication URLs
Definition at line 37 of file Interface.cs.
Referenced by TGServerService.Service.SetupService().
const long TGServiceInterface.Interface.TransferLimitLocal = Int32.MaxValue
The maximum message size to and from a local server
Definition at line 27 of file Interface.cs.
Referenced by TGServerService.Service.AddEndpoint().
const long TGServiceInterface.Interface.TransferLimitRemote = 10485760
The maximum message size to and from a remote server
Definition at line 32 of file Interface.cs.
Referenced by TGServerService.Service.AddEndpoint().
readonly IList<Type> TGServiceInterface.Interface.ValidInterfaces = CollectComponents() static
List of s that can be used with GetComponent<T> and CreateChannel<T>
Definition at line 22 of file Interface.cs.
Referenced by TGServerService.Service.SetupInstance().
Property Documentation
string TGServiceInterface.Interface.InstanceName get private set
The name of the current instance in use. Defaults to
Definition at line 47 of file Interface.cs.
Referenced by TGServiceInterface.Interface.ConnectToInstance(), TGControlPanel.ControlPanel.ControlPanel(), TGCommandLine.InstanceRootCommand.DoRun(), and TGServiceInterface.Interface.GetComponentImpl< T >().
bool TGServiceInterface.Interface.IsRemoteConnection get
Checks if the Interface is setup for a remote connection
Definition at line 197 of file Interface.cs.
Referenced by TGServiceInterface.Interface.CreateChannel< T >().
The documentation for this class was generated from the following file:
TGServiceInterface/Interface.cs