tgstation-server: Tgstation.Server.Host.Utils.AsyncDelayer Class Reference
Tgstation.Server.Host.Utils.AsyncDelayer Class Reference sealed
Public Member Functions
Task Delay (TimeSpan timeSpan, CancellationToken cancellationToken)
Create a Task that completes after a given timeSpan .
Parameters
timeSpan The TimeSpan that must elapse.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Detailed Description
Definition at line 8 of file AsyncDelayer.cs.
Member Function Documentation
Delay()
Task Tgstation.Server.Host.Utils.AsyncDelayer.Delay (TimeSpan timeSpan, CancellationToken cancellationToken)
Create a Task that completes after a given timeSpan .
Parameters
timeSpan The TimeSpan that must elapse.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implements Tgstation.Server.Host.Utils.IAsyncDelayer.
Referenced by Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.HandleNormalReboot(), Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.HardDisconnect(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.MonitorRestart(), Tgstation.Server.Host.Components.Chat.Providers.Provider.ReconnectionLoop(), and Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.SaslAuthenticate().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Utils/AsyncDelayer.cs