tgstation-server: Tgstation.Server.Host.Security.AuthenticationContextClaimsTransformation Class Reference
Tgstation.Server.Host.Security.AuthenticationContextClaimsTransformation Class Reference sealed
A IClaimsTransformation that maps Claims using an IAuthenticationContext.
Public Member Functions
AuthenticationContextClaimsTransformation (IAuthenticationContextFactory authenticationContextFactory, IApiHeadersProvider apiHeadersProvider)
Initializes a new instance of the AuthenticationContextClaimsTransformation class.
async Task< ClaimsPrincipal > TransformAsync (ClaimsPrincipal principal)
Private Attributes
readonly IAuthenticationContextFactory authenticationContextFactory
The IAuthenticationContextFactory for the AuthenticationContextClaimsTransformation.
readonly? ApiHeaders apiHeaders
The ApiHeaders for the AuthenticationContextClaimsTransformation.
Detailed Description
A IClaimsTransformation that maps Claims using an IAuthenticationContext.
Definition at line 21 of file AuthenticationContextClaimsTransformation.cs.
Constructor & Destructor Documentation
AuthenticationContextClaimsTransformation()
Tgstation.Server.Host.Security.AuthenticationContextClaimsTransformation.AuthenticationContextClaimsTransformation (IAuthenticationContextFactory authenticationContextFactory, IApiHeadersProvider apiHeadersProvider)
Initializes a new instance of the AuthenticationContextClaimsTransformation class.
Parameters
authenticationContextFactory The value of authenticationContextFactory.
apiHeadersProvider The IApiHeadersProvider containing the value of apiHeaders.
Definition at line 38 of file AuthenticationContextClaimsTransformation.cs.
        {
            this.authenticationContextFactory = authenticationContextFactory ?? throw new ArgumentNullException(nameof(authenticationContextFactory));
            ArgumentNullException.ThrowIfNull(apiHeadersProvider);
            apiHeaders = apiHeadersProvider.ApiHeaders;
        }
References Tgstation.Server.Api.ApiHeaders.ApiHeaders(), Tgstation.Server.Host.Security.AuthenticationContextClaimsTransformation.apiHeaders, Tgstation.Server.Host.Security.AuthenticationContextClaimsTransformation.authenticationContextFactory, and Tgstation.Server.Api.Rights.List.
Member Function Documentation
TransformAsync()
async Task< ClaimsPrincipal > Tgstation.Server.Host.Security.AuthenticationContextClaimsTransformation.TransformAsync (ClaimsPrincipal principal)
Definition at line 46 of file AuthenticationContextClaimsTransformation.cs.
        {
            ArgumentNullException.ThrowIfNull(principal);
            var userIdClaim = principal.FindFirst(JwtRegisteredClaimNames.Sub);
            if (userIdClaim == default)
                throw new InvalidOperationException($"Missing '{JwtRegisteredClaimNames.Sub}' claim!");
            long userId;
            try
            {
                userId = Int64.Parse(userIdClaim.Value, CultureInfo.InvariantCulture);
            }
            catch (Exception e)
            {
                throw new InvalidOperationException("Failed to parse user ID!", e);
            }
            var nbfClaim = principal.FindFirst(JwtRegisteredClaimNames.Nbf);
            if (nbfClaim == default)
                throw new InvalidOperationException($"Missing '{JwtRegisteredClaimNames.Nbf}' claim!");
            DateTimeOffset nbf;
            try
            {
                nbf = new DateTimeOffset(
                    EpochTime.DateTime(
                        Int64.Parse(nbfClaim.Value, CultureInfo.InvariantCulture)));
            }
            catch (Exception ex)
            {
                throw new InvalidOperationException("Failed to parse nbf!", ex);
            }
            var authenticationContext = await authenticationContextFactory.CreateAuthenticationContext(
                userId,
                apiHeaders?.InstanceId,
                nbf,
                CancellationToken.None); // DCT: None available
            var enumerator = Enum.GetValues(typeof(RightsType));
            var claims = new List<Claim>();
            foreach (RightsType rightType in enumerator)
            {
                // if there's a bad condition, do a weird thing and add all the roles
                // we need it so we can get to TgsAuthorizeAttribute where we can properly decide between BadRequest and Forbid
                var rightAsULong = !authenticationContext.Valid
                    || (RightsHelper.IsInstanceRight(rightType) && authenticationContext.InstancePermissionSet == null)
                    ? ~0UL
                    : authenticationContext.GetRight(rightType);
                var rightEnum = RightsHelper.RightToType(rightType);
                var right = (Enum)Enum.ToObject(rightEnum, rightAsULong);
                foreach (Enum enumeratedRight in Enum.GetValues(rightEnum))
                    if (right.HasFlag(enumeratedRight))
                        claims.Add(
                            new Claim(
                                ClaimTypes.Role,
                                RightsHelper.RoleName(rightType, enumeratedRight)));
            }
            principal.AddIdentity(new ClaimsIdentity(claims));
            return principal;
        }
References Tgstation.Server.Host.Security.AuthenticationContextClaimsTransformation.apiHeaders, Tgstation.Server.Host.Security.AuthenticationContextClaimsTransformation.authenticationContextFactory, Tgstation.Server.Host.Security.IAuthenticationContextFactory.CreateAuthenticationContext(), Tgstation.Server.Api.Rights.RightsHelper.IsInstanceRight(), Tgstation.Server.Api.Rights.List, Tgstation.Server.Api.Rights.RightsHelper.RightToType(), and Tgstation.Server.Api.Rights.RightsHelper.RoleName().
Member Data Documentation
apiHeaders
readonly? ApiHeaders Tgstation.Server.Host.Security.AuthenticationContextClaimsTransformation.apiHeaders private
The ApiHeaders for the AuthenticationContextClaimsTransformation.
Definition at line 31 of file AuthenticationContextClaimsTransformation.cs.
Referenced by Tgstation.Server.Host.Security.AuthenticationContextClaimsTransformation.AuthenticationContextClaimsTransformation(), and Tgstation.Server.Host.Security.AuthenticationContextClaimsTransformation.TransformAsync().
authenticationContextFactory
readonly IAuthenticationContextFactory Tgstation.Server.Host.Security.AuthenticationContextClaimsTransformation.authenticationContextFactory private
The IAuthenticationContextFactory for the AuthenticationContextClaimsTransformation.
Definition at line 26 of file AuthenticationContextClaimsTransformation.cs.
Referenced by Tgstation.Server.Host.Security.AuthenticationContextClaimsTransformation.AuthenticationContextClaimsTransformation(), and Tgstation.Server.Host.Security.AuthenticationContextClaimsTransformation.TransformAsync().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Security/AuthenticationContextClaimsTransformation.cs