tgstation-server: TGControlPanel.ServerOpForm Class Reference
TGControlPanel.ServerOpForm Class Reference
Used to provide an ATP function for calls into an TGServiceInterface.IInterface
Protected Member Functions
Task WrapServerOp (Action action)
Used to wrap TGServiceInterface.IInterface calls in a non-blocking fashion while disabling the Form and enabling the wait cursor
Detailed Description
Used to provide an ATP function for calls into an TGServiceInterface.IInterface
Definition at line 11 of file ServerOpForm.cs.
Member Function Documentation
Task TGControlPanel.ServerOpForm.WrapServerOp (Action action) protected
Used to wrap TGServiceInterface.IInterface calls in a non-blocking fashion while disabling the Form and enabling the wait cursor
Parameters
action The TGServiceInterface.IInterface operation to wrap
Returns
A Task wrapping action
Definition at line 21 of file ServerOpForm.cs.
Referenced by TGControlPanel.TestMergeManager.AddPRButton_Click(), TGControlPanel.TestMergeManager.ApplyButton_Click(), TGControlPanel.InstanceSelector.CreateInstanceButton_Click(), TGControlPanel.InstanceSelector.DetachInstanceButton_Click(), TGControlPanel.InstanceSelector.EnabledCheckBox_CheckedChanged(), TGControlPanel.TestMergeManager.GenerateChangelog(), TGControlPanel.InstanceSelector.ImportInstanceButton_Click(), TGControlPanel.InstanceSelector.RefreshInstances(), TGControlPanel.InstanceSelector.RenameInstanceButton_Click(), and TGControlPanel.InstanceSelector.TryConnectToIndexInstance().
         {
             Enabled = false;
             UseWaitCursor = true;
             try
             {
                 return Task.Factory.StartNew(action);
             }
             finally
             {
                 Enabled = true;
                 UseWaitCursor = false;
             }
         }
The documentation for this class was generated from the following file:
TGControlPanel/ServerOpForm.cs