tgstation-server: Tgstation.Server.Host.Components.Engine.EngineManager Class Reference
Tgstation.Server.Host.Components.Engine.EngineManager Class Reference sealed
Public Member Functions
EngineManager (IIOManager ioManager, IEngineInstaller engineInstaller, IEventConsumer eventConsumer, IDmbFactory dmbFactory, ILogger< EngineManager > logger)
Initializes a new instance of the EngineManager class.
void Dispose ()
async ValueTask ChangeVersion (JobProgressReporter progressReporter, EngineVersion version, Stream? customVersionStream, bool allowInstallation, CancellationToken cancellationToken)
Change the active EngineVersion.
Parameters
progressReporter The JobProgressReporter for the operation.
version The new EngineVersion.
customVersionStream Optional Stream of a custom BYOND version zip file.
allowInstallation If an installation should be performed if the version is not installed. If false and an installation is required an InvalidOperationException will be thrown.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
async ValueTask< IEngineExecutableLock > UseExecutables (EngineVersion? requiredVersion, string? trustDmbFullPath, CancellationToken cancellationToken)
Lock the current installation's location and return a IEngineExecutableLock.
Parameters
requiredVersion The EngineVersion required.
trustDmbFullPath The optional full path to .dmb to trust while using the executables.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the requested IEngineExecutableLock.
async ValueTask DeleteVersion (JobProgressReporter progressReporter, EngineVersion version, CancellationToken cancellationToken)
Deletes a given version from the disk.
Parameters
progressReporter The JobProgressReporter for the operation.
version The EngineVersion to delete.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
async Task StartAsync (CancellationToken cancellationToken)
Task StopAsync (CancellationToken cancellationToken)
Properties
EngineVersion? ActiveVersion [get, private set]
The currently active EngineVersion.
IReadOnlyList< EngineVersion > InstalledVersions [get]
The installed EngineVersions.
Properties inherited from Tgstation.Server.Host.Components.Engine.IEngineManager
Private Member Functions
async ValueTask< EngineExecutableLock > AssertAndLockVersion (JobProgressReporter progressReporter, EngineVersion version, Stream? customVersionStream, bool neededForLock, bool allowInstallation, CancellationToken cancellationToken)
Ensures a BYOND version is installed if it isn't already.
async ValueTask< string > InstallVersionFiles (JobProgressReporter progressReporter, EngineVersion version, Stream? customVersionStream, bool deploymentPipelineProcesses, CancellationToken cancellationToken)
Installs the files for a given BYOND version .
ReferenceCountingContainer< IEngineInstallation, EngineExecutableLock > AddInstallationContainer (IEngineInstallation installation)
Create and add a new IEngineInstallation to installedVersions.
Static Private Member Functions
static void CheckVersionParameter (EngineVersion version)
Validates a given version parameter.
Private Attributes
readonly IIOManager ioManager
The IIOManager for the EngineManager.
readonly IEngineInstaller engineInstaller
The IEngineInstaller for the EngineManager.
readonly IEventConsumer eventConsumer
The IEventConsumer for the EngineManager.
readonly IDmbFactory dmbFactory
The IDmbFactory for the EngineManager.
readonly ILogger< EngineManager > logger
The ILogger for the EngineManager.
readonly Dictionary< EngineVersion, ReferenceCountingContainer< IEngineInstallation, EngineExecutableLock > > installedVersions
Map of byond EngineVersions to Tasks that complete when they are installed.
readonly SemaphoreSlim changeDeleteSemaphore
The SemaphoreSlim for changing or deleting the active BYOND version.
volatile TaskCompletionSource activeVersionChanged
TaskCompletionSource that notifes when the ActiveVersion changes.
Static Private Attributes
const string VersionFileName = "Version.txt"
The file in which we store the Version for installations.
const string ActiveVersionFileName = "ActiveVersion.txt"
The file in which we store the ActiveVersion.
Detailed Description
Definition at line 23 of file EngineManager.cs.
Constructor & Destructor Documentation
EngineManager()
Tgstation.Server.Host.Components.Engine.EngineManager.EngineManager (IIOManager ioManager, IEngineInstaller engineInstaller, IEventConsumer eventConsumer, IDmbFactory dmbFactory, ILogger< EngineManager > logger)
Initializes a new instance of the EngineManager class.
Parameters
ioManager The value of ioManager.
engineInstaller The value of engineInstaller.
eventConsumer The value of eventConsumer.
dmbFactory The value of dmbFactory.
logger The value of logger.
Definition at line 111 of file EngineManager.cs.
        {
            this.ioManager = ioManager ?? throw new ArgumentNullException(nameof(ioManager));
            this.engineInstaller = engineInstaller ?? throw new ArgumentNullException(nameof(engineInstaller));
            this.eventConsumer = eventConsumer ?? throw new ArgumentNullException(nameof(eventConsumer));
            this.dmbFactory = dmbFactory ?? throw new ArgumentNullException(nameof(dmbFactory));
            this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
            installedVersions = new Dictionary<EngineVersion, ReferenceCountingContainer<IEngineInstallation, EngineExecutableLock>>();
            changeDeleteSemaphore = new SemaphoreSlim(1);
            activeVersionChanged = new TaskCompletionSource();
        }
References Tgstation.Server.Host.Components.Engine.EngineManager.activeVersionChanged, Tgstation.Server.Host.Components.Engine.EngineManager.changeDeleteSemaphore, Tgstation.Server.Host.Components.Engine.EngineManager.dmbFactory, Tgstation.Server.Host.Components.Engine.EngineManager.engineInstaller, Tgstation.Server.Host.Components.Engine.EngineManager.eventConsumer, Tgstation.Server.Host.Components.Engine.EngineManager.installedVersions, Tgstation.Server.Host.Components.Engine.EngineManager.ioManager, and Tgstation.Server.Host.Components.Engine.EngineManager.logger.
Member Function Documentation
AddInstallationContainer()
ReferenceCountingContainer< IEngineInstallation, EngineExecutableLock > Tgstation.Server.Host.Components.Engine.EngineManager.AddInstallationContainer (IEngineInstallation installation) private
Create and add a new IEngineInstallation to installedVersions.
Parameters
installation The IEngineInstallation being added.
Returns
A new ReferenceCountingContainer<TWrapped, TReference> for the IEngineInstallation/EngineExecutableLock.
Definition at line 667 of file EngineManager.cs.
        {
            var installationContainer = new ReferenceCountingContainer<IEngineInstallation, EngineExecutableLock>(installation);
            lock (installedVersions)
                installedVersions.Add(installation.Version, installationContainer);
            return installationContainer;
        }
References Tgstation.Server.Host.Components.Engine.EngineManager.installedVersions, and Tgstation.Server.Host.Components.Engine.IEngineInstallation.Version.
Referenced by Tgstation.Server.Host.Components.Engine.EngineManager.AssertAndLockVersion(), and Tgstation.Server.Host.Components.Engine.EngineManager.StartAsync().
AssertAndLockVersion()
async ValueTask< EngineExecutableLock > Tgstation.Server.Host.Components.Engine.EngineManager.AssertAndLockVersion (JobProgressReporter progressReporter, EngineVersion version, Stream? customVersionStream, bool neededForLock, bool allowInstallation, CancellationToken cancellationToken) private
Ensures a BYOND version is installed if it isn't already.
Parameters
progressReporter The JobProgressReporter for the operation.
version The EngineVersion to install.
customVersionStream Optional custom zip file Stream to use. Will cause a Version.Build number to be added.
neededForLock If this BYOND version is required as part of a locking operation.
allowInstallation If an installation should be performed if the version is not installed. If false and an installation is required an InvalidOperationException will be thrown.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the EngineExecutableLock.
Definition at line 419 of file EngineManager.cs.
        {
            var ourTcs = new TaskCompletionSource();
            IEngineInstallation installation;
            EngineExecutableLock installLock;
            bool installedOrInstalling;
            // loop is because of the race condition with potentialInstallation, installedVersions, and CustomIteration selection
            while (true)
            {
                lock (installedVersions)
                {
                    if (customVersionStream != null)
                    {
                        var customInstallationNumber = 1;
                        do
{
                            version.CustomIteration = customInstallationNumber++;
                        }
                        while (installedVersions.ContainsKey(version));
                    }
                }
                var potentialInstallation = await engineInstaller.GetInstallation(
                    version,
                    ioManager.ResolvePath(version.ToString()),
                    ourTcs.Task,
                    cancellationToken);
                lock (installedVersions)
                {
                    if (customVersionStream != null && installedVersions.ContainsKey(version))
                        continue;
                    installedOrInstalling = installedVersions.TryGetValue(version, out var installationContainerNullable);
                    ReferenceCountingContainer<IEngineInstallation, EngineExecutableLock> installationContainer;
                    if (!installedOrInstalling)
                    {
                        if (!allowInstallation)
                            throw new InvalidOperationException($"Engine version {version} not installed!");
                        installationContainer = AddInstallationContainer(potentialInstallation);
                    }
                    else
                        installationContainer = installationContainerNullable!;
                    installation = installationContainer.Instance;
                    installLock = installationContainer.AddReference();
                }
                var deploymentPipelineProcesses = !neededForLock;
                try
                {
                    if (installedOrInstalling)
                    {
                        progressReporter.StageName = "Waiting for existing installation job...";
                        if (neededForLock && !installation.InstallationTask.IsCompleted)
                            logger.LogWarning("The required engine version ({version}) is not readily available! We will have to wait for it to install.", version);
                        await installation.InstallationTask.WaitAsync(cancellationToken);
                        return installLock;
                    }
                    // okay up to us to install it then
                    string? installPath = null;
                    try
                    {
                        if (customVersionStream != null)
                            logger.LogInformation("Installing custom engine version as {version}...", version);
                        else if (neededForLock)
{
                            if (version.CustomIteration.HasValue)
                                throw new JobException(ErrorCode.EngineNonExistentCustomVersion);
                            logger.LogWarning("The required engine version ({version}) is not readily available! We will have to install it.", version);
                        }
                        else
                            logger.LogInformation("Requested engine version {version} not currently installed. Doing so now...", version);
                        progressReporter.StageName = "Running event";
                        var versionString = version.ToString();
                        await eventConsumer.HandleEvent(EventType.EngineInstallStart, new List<string> { versionString }, false, deploymentPipelineProcesses, cancellationToken);
                        installPath = await InstallVersionFiles(progressReporter, version, customVersionStream, deploymentPipelineProcesses, cancellationToken);
                        await eventConsumer.HandleEvent(EventType.EngineInstallComplete, new List<string> { versionString }, false, deploymentPipelineProcesses, cancellationToken);
                        ourTcs.SetResult();
                    }
                    catch (Exception ex)
                    {
                        if (installPath != null)
{
                            try
{
                                logger.LogDebug("Cleaning up failed installation at {path}...", installPath);
                                await ioManager.DeleteDirectory(installPath, cancellationToken);
                            }
                            catch (Exception ex2)
{
                                logger.LogError(ex2, "Error cleaning up failed installation!");
                            }
                        }
                        else if (ex is not OperationCanceledException)
                            await eventConsumer.HandleEvent(EventType.EngineInstallFail, new List<string> { ex.Message }, false, deploymentPipelineProcesses, cancellationToken);
                        lock (installedVersions)
                            installedVersions.Remove(version);
                        ourTcs.SetException(ex);
                        throw;
                    }
                    return installLock;
                }
                catch
                {
                    installLock.Dispose();
                    throw;
                }
            }
        }
References Tgstation.Server.Host.Components.Engine.EngineManager.AddInstallationContainer(), Tgstation.Server.Host.Utils.ReferenceCountingContainer< TWrapped, TReference >.AddReference(), Tgstation.Server.Api.Models.EngineVersion.CustomIteration, Tgstation.Server.Host.IO.IIOManager.DeleteDirectory(), Tgstation.Server.Host.Utils.ReferenceCounter< TInstance >.Dispose(), Tgstation.Server.Host.Components.Engine.EngineManager.engineInstaller, Tgstation.Server.Host.Components.Engine.EngineManager.eventConsumer, Tgstation.Server.Host.Components.Engine.IEngineInstaller.GetInstallation(), Tgstation.Server.Host.Components.Events.IEventConsumer.HandleEvent(), Tgstation.Server.Host.Components.Engine.IEngineInstallation.InstallationTask, Tgstation.Server.Host.Components.Engine.EngineManager.installedVersions, Tgstation.Server.Host.Components.Engine.EngineManager.InstallVersionFiles(), Tgstation.Server.Host.Utils.ReferenceCountingContainer< TWrapped, TReference >.Instance, Tgstation.Server.Host.Components.Engine.EngineManager.ioManager, Tgstation.Server.Host.Components.Engine.EngineManager.logger, Tgstation.Server.Host.IO.IIOManager.ResolvePath(), and Tgstation.Server.Api.Models.EngineVersion.ToString().
Referenced by Tgstation.Server.Host.Components.Engine.EngineManager.ChangeVersion(), and Tgstation.Server.Host.Components.Engine.EngineManager.UseExecutables().
ChangeVersion()
async ValueTask Tgstation.Server.Host.Components.Engine.EngineManager.ChangeVersion (JobProgressReporter progressReporter, EngineVersion version, Stream? customVersionStream, bool allowInstallation, CancellationToken cancellationToken)
Change the active EngineVersion.
Parameters
progressReporter The JobProgressReporter for the operation.
version The new EngineVersion.
customVersionStream Optional Stream of a custom BYOND version zip file.
allowInstallation If an installation should be performed if the version is not installed. If false and an installation is required an InvalidOperationException will be thrown.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Engine.IEngineManager.
Definition at line 133 of file EngineManager.cs.
        {
            CheckVersionParameter(version);
            using (await SemaphoreSlimContext.Lock(changeDeleteSemaphore, cancellationToken))
            {
                using var installLock = await AssertAndLockVersion(
                    progressReporter,
                    version,
                    customVersionStream,
                    false,
                    allowInstallation,
                    cancellationToken);
                // We reparse the version because it could be changed after a custom install.
                version = new EngineVersion(installLock.Version);
                var stringVersion = version.ToString();
                await ioManager.WriteAllBytes(ActiveVersionFileName, Encoding.UTF8.GetBytes(stringVersion), cancellationToken);
                await eventConsumer.HandleEvent(
                    EventType.EngineActiveVersionChange,
                    new List<string?>
                    {
                        ActiveVersion?.ToString(),
                        stringVersion,
                    },
                    false,
                    false,
                    cancellationToken);
                ActiveVersion = version;
                logger.LogInformation("Active version changed to {version}", version);
                var oldTcs = Interlocked.Exchange(ref activeVersionChanged, new TaskCompletionSource());
                oldTcs.SetResult();
            }
        }
References Tgstation.Server.Host.Components.Engine.EngineManager.ActiveVersion, Tgstation.Server.Host.Components.Engine.EngineManager.activeVersionChanged, Tgstation.Server.Host.Components.Engine.EngineManager.ActiveVersionFileName, Tgstation.Server.Host.Components.Engine.EngineManager.AssertAndLockVersion(), Tgstation.Server.Host.Components.Engine.EngineManager.changeDeleteSemaphore, Tgstation.Server.Host.Components.Engine.EngineManager.CheckVersionParameter(), Tgstation.Server.Host.Components.Engine.EngineManager.eventConsumer, Tgstation.Server.Host.Components.Events.IEventConsumer.HandleEvent(), Tgstation.Server.Host.Components.Engine.EngineManager.ioManager, Tgstation.Server.Host.Utils.SemaphoreSlimContext.Lock(), Tgstation.Server.Host.Components.Engine.EngineManager.logger, Tgstation.Server.Api.Models.EngineVersion.ToString(), and Tgstation.Server.Host.IO.IIOManager.WriteAllBytes().
CheckVersionParameter()
static void Tgstation.Server.Host.Components.Engine.EngineManager.CheckVersionParameter (EngineVersion version) static private
Validates a given version parameter.
Parameters
version The Version to validate.
Definition at line 92 of file EngineManager.cs.
        {
            ArgumentNullException.ThrowIfNull(version);
            if (!version.Engine.HasValue)
                throw new InvalidOperationException("version.Engine cannot be null!");
            if (version.CustomIteration == 0)
                throw new InvalidOperationException("version.CustomIteration cannot be 0!");
        }
References Tgstation.Server.Api.Models.EngineVersion.CustomIteration, and Tgstation.Server.Api.Models.EngineVersion.Engine.
Referenced by Tgstation.Server.Host.Components.Engine.EngineManager.ChangeVersion(), and Tgstation.Server.Host.Components.Engine.EngineManager.DeleteVersion().
DeleteVersion()
async ValueTask Tgstation.Server.Host.Components.Engine.EngineManager.DeleteVersion (JobProgressReporter progressReporter, EngineVersion version, CancellationToken cancellationToken)
Deletes a given version from the disk.
Parameters
progressReporter The JobProgressReporter for the operation.
version The EngineVersion to delete.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implements Tgstation.Server.Host.Components.Engine.IEngineManager.
Definition at line 208 of file EngineManager.cs.
        {
            ArgumentNullException.ThrowIfNull(progressReporter);
            CheckVersionParameter(version);
            logger.LogTrace("DeleteVersion {version}", version);
            var activeVersion = ActiveVersion;
            if (activeVersion != null && version.Equals(activeVersion))
                throw new JobException(ErrorCode.EngineCannotDeleteActiveVersion);
            ReferenceCountingContainer<IEngineInstallation, EngineExecutableLock> container;
            logger.LogTrace("Waiting to acquire installedVersions lock...");
            lock (installedVersions)
            {
                if (!installedVersions.TryGetValue(version, out var containerNullable))
                {
                    logger.LogTrace("Version {version} already deleted.", version);
                    return;
                }
                container = containerNullable;
                logger.LogTrace("Installation container acquired for deletion");
            }
            progressReporter.StageName = "Waiting for version to not be in use...";
            while (true)
            {
                var containerTask = container.OnZeroReferences;
                // We also want to check when the active version changes in case we need to fail the job because of that.
                Task activeVersionUpdate;
                using (await SemaphoreSlimContext.Lock(changeDeleteSemaphore, cancellationToken))
                    activeVersionUpdate = activeVersionChanged.Task;
                logger.LogTrace("Waiting for container.OnZeroReferences or switch of active version...");
                if (!containerTask.IsCompleted)
                    dmbFactory.LogLockStates();
                await Task.WhenAny(
                    containerTask,
                    activeVersionUpdate)
                    .WaitAsync(cancellationToken);
                if (containerTask.IsCompleted)
                    logger.LogTrace("All locks for version {version} are gone", version);
                else
                    logger.LogTrace("activeVersion changed, we may have to wait again. Acquiring semaphore...");
                using (await SemaphoreSlimContext.Lock(changeDeleteSemaphore, cancellationToken))
                {
                    // check again because it could have become the active version.
                    activeVersion = ActiveVersion;
                    if (activeVersion != null && version.Equals(activeVersion))
                        throw new JobException(ErrorCode.EngineCannotDeleteActiveVersion);
                    bool proceed;
                    logger.LogTrace("Locking installedVersions...");
                    lock (installedVersions)
                    {
                        proceed = container.OnZeroReferences.IsCompleted;
                        if (proceed)
                            if (!installedVersions.TryGetValue(version, out var newerContainer))
                                logger.LogWarning("Unable to remove engine installation {version} from list! Is there a duplicate job running?", version);
                            else
{
                                if (container != newerContainer)
{
                                    // Okay let me get this straight, there was a duplicate delete job, it ran before us after we grabbed the container, AND another installation of the same version completed?
                                    // I know realistically this is practically impossible, but god damn that small possiblility
                                    // best thing to do is check we exclusively own the newer container
                                    logger.LogDebug("Extreme race condition encountered, applying concentrated copium...");
                                    container = newerContainer;
                                    proceed = container.OnZeroReferences.IsCompleted;
                                }
                                if (proceed)
{
                                    logger.LogTrace("Proceeding with installation deletion...");
                                    installedVersions.Remove(version);
                                }
                            }
                    }
                    if (proceed)
                    {
                        logger.LogInformation("Deleting version {version}...", version);
                        progressReporter.StageName = "Deleting installation...";
                        // delete the version file first, because we will know not to re-discover the installation if it's not present and it will get cleaned on reboot
                        var installPath = version.ToString();
                        await ioManager.DeleteFile(
                            ioManager.ConcatPath(installPath, VersionFileName),
                            cancellationToken);
                        await ioManager.DeleteDirectory(installPath, cancellationToken);
                        return;
                    }
                    if (containerTask.IsCompleted)
                        logger.LogDebug(
                            "Another lock was acquired before we could remove version {version} from the list. We will have to wait again.",
                            version);
                    else
                        logger.LogTrace("Not proceeding for some reason or another");
                }
            }
        }
References Tgstation.Server.Host.Components.Engine.EngineManager.ActiveVersion, Tgstation.Server.Host.Components.Engine.EngineManager.activeVersionChanged, Tgstation.Server.Host.Components.Engine.EngineManager.changeDeleteSemaphore, Tgstation.Server.Host.Components.Engine.EngineManager.CheckVersionParameter(), Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.IO.IIOManager.DeleteDirectory(), Tgstation.Server.Host.IO.IIOManager.DeleteFile(), Tgstation.Server.Host.Components.Engine.EngineManager.dmbFactory, Tgstation.Server.Api.Models.EngineVersion.Equals(), Tgstation.Server.Host.Components.Engine.EngineManager.installedVersions, Tgstation.Server.Host.Components.Engine.EngineManager.ioManager, Tgstation.Server.Host.Utils.SemaphoreSlimContext.Lock(), Tgstation.Server.Host.Components.Engine.EngineManager.logger, Tgstation.Server.Host.Components.Deployment.IDmbFactory.LogLockStates(), Tgstation.Server.Host.Utils.ReferenceCountingContainer< TWrapped, TReference >.OnZeroReferences, Tgstation.Server.Api.Models.EngineVersion.ToString(), and Tgstation.Server.Host.Components.Engine.EngineManager.VersionFileName.
Dispose()
void Tgstation.Server.Host.Components.Engine.EngineManager.Dispose ()
Referenced by Tgstation.Server.Host.Components.Instance.DisposeAsync().
InstallVersionFiles()
async ValueTask< string > Tgstation.Server.Host.Components.Engine.EngineManager.InstallVersionFiles (JobProgressReporter progressReporter, EngineVersion version, Stream? customVersionStream, bool deploymentPipelineProcesses, CancellationToken cancellationToken) private
Installs the files for a given BYOND version .
Parameters
progressReporter The JobProgressReporter for the operation.
version The EngineVersion being installed with the Version.Build number set if appropriate.
customVersionStream Custom zip file Stream to use. Will cause a Version.Build number to be added.
deploymentPipelineProcesses If processes should be launched as part of the deployment pipeline.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the directory the engine was installed to.
Definition at line 558 of file EngineManager.cs.
        {
            var installFullPath = ioManager.ResolvePath(version.ToString());
            async ValueTask DirectoryCleanup()
            {
                await ioManager.DeleteDirectory(installFullPath, cancellationToken);
                await ioManager.CreateDirectory(installFullPath, cancellationToken);
            }
            var directoryCleanupTask = DirectoryCleanup();
            try
            {
                IEngineInstallationData engineInstallationData;
                var remainingProgress = 1.0;
                if (customVersionStream == null)
                {
                    using var subReporter = progressReporter.CreateSection("Downloading Version", 0.5);
                    remainingProgress -= 0.5;
                    engineInstallationData = await engineInstaller.DownloadVersion(version, subReporter, cancellationToken);
                }
                else
#pragma warning disable CA2000 // Dispose objects before losing scope, false positive
                    engineInstallationData = new ZipStreamEngineInstallationData(
                        ioManager,
                        customVersionStream);
#pragma warning restore CA2000 // Dispose objects before losing scope
                JobProgressReporter remainingReporter;
                try
                {
                    remainingReporter = progressReporter.CreateSection(null, remainingProgress);
                }
                catch
                {
                    await engineInstallationData.DisposeAsync();
                    throw;
                }
                using (remainingReporter)
                {
                    await using (engineInstallationData)
                    {
                        remainingReporter.StageName = "Cleaning target directory";
                        await directoryCleanupTask;
                        remainingReporter.ReportProgress(0.1);
                        remainingReporter.StageName = "Extracting data";
                        logger.LogTrace("Extracting engine to {extractPath}...", installFullPath);
                        await engineInstallationData.ExtractToPath(installFullPath, cancellationToken);
                        remainingReporter.ReportProgress(0.3);
                    }
                    remainingReporter.StageName = "Running installation actions";
                    var installation = await engineInstaller.Install(version, installFullPath, deploymentPipelineProcesses, cancellationToken);
                    // some minor validation
                    var serverInstallTask = ioManager.FileExists(installation.ServerExePath, cancellationToken);
                    if (!await ioManager.FileExists(installation.CompilerExePath, cancellationToken))
                    {
                        logger.LogError("Compiler executable does not exist after engine installation!");
                        throw new JobException(ErrorCode.EngineDownloadFail);
                    }
                    if (!await serverInstallTask)
                    {
                        logger.LogError("Server executable does not exist after engine installation!");
                        throw new JobException(ErrorCode.EngineDownloadFail);
                    }
                    remainingReporter.ReportProgress(0.9);
                    remainingReporter.StageName = "Writing version file";
                    // make sure to do this last because this is what tells us we have a valid version in the future
                    await ioManager.WriteAllBytes(
                        ioManager.ConcatPath(installFullPath, VersionFileName),
                        Encoding.UTF8.GetBytes(version.ToString()),
                        cancellationToken);
                }
            }
            catch (HttpRequestException ex)
            {
                // since the user can easily provide non-exitent version numbers, we'll turn this into a JobException
                throw new JobException(ErrorCode.EngineDownloadFail, ex);
            }
            catch (OperationCanceledException)
            {
                throw;
            }
            catch
            {
                await ioManager.DeleteDirectory(installFullPath, cancellationToken);
                throw;
            }
            return installFullPath;
        }
References Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.IO.IIOManager.CreateDirectory(), Tgstation.Server.Host.Jobs.JobProgressReporter.CreateSection(), Tgstation.Server.Host.IO.IIOManager.DeleteDirectory(), Tgstation.Server.Host.Components.Engine.IEngineInstaller.DownloadVersion(), Tgstation.Server.Host.Components.Engine.EngineManager.engineInstaller, Tgstation.Server.Host.Components.Engine.IEngineInstallationData.ExtractToPath(), Tgstation.Server.Host.IO.IIOManager.FileExists(), Tgstation.Server.Host.Components.Engine.IEngineInstaller.Install(), Tgstation.Server.Host.Components.Engine.EngineManager.ioManager, Tgstation.Server.Host.Components.Engine.EngineManager.logger, Tgstation.Server.Host.Jobs.JobProgressReporter.ReportProgress(), Tgstation.Server.Host.IO.IIOManager.ResolvePath(), Tgstation.Server.Api.Models.EngineVersion.ToString(), Tgstation.Server.Host.Components.Engine.EngineManager.VersionFileName, and Tgstation.Server.Host.IO.IIOManager.WriteAllBytes().
Referenced by Tgstation.Server.Host.Components.Engine.EngineManager.AssertAndLockVersion().
StartAsync()
async Task Tgstation.Server.Host.Components.Engine.EngineManager.StartAsync (CancellationToken cancellationToken)
Definition at line 318 of file EngineManager.cs.
        {
            async ValueTask<byte[]?> GetActiveVersion()
            {
                var activeVersionFileExists = await ioManager.FileExists(ActiveVersionFileName, cancellationToken);
                return !activeVersionFileExists ? null : await ioManager.ReadAllBytes(ActiveVersionFileName, cancellationToken);
            }
            var activeVersionBytesTask = GetActiveVersion();
            await ioManager.CreateDirectory(DefaultIOManager.CurrentDirectory, cancellationToken);
            var directories = await ioManager.GetDirectories(DefaultIOManager.CurrentDirectory, cancellationToken);
            var installedVersionPaths = new Dictionary<string, EngineVersion>();
            async ValueTask ReadVersion(string path)
            {
                var versionFile = ioManager.ConcatPath(path, VersionFileName);
                if (!await ioManager.FileExists(versionFile, cancellationToken))
                {
                    logger.LogWarning("Cleaning path with no version file: {versionPath}", ioManager.ResolvePath(path));
                    await ioManager.DeleteDirectory(path, cancellationToken); // cleanup
                    return;
                }
                var bytes = await ioManager.ReadAllBytes(versionFile, cancellationToken);
                var text = Encoding.UTF8.GetString(bytes);
                EngineVersion version;
                if (!EngineVersion.TryParse(text, out var versionNullable))
                {
                    logger.LogWarning("Cleaning path with unparsable version file: {versionPath}", ioManager.ResolvePath(path));
                    await ioManager.DeleteDirectory(path, cancellationToken); // cleanup
                    return;
                }
                else
                    version = versionNullable!;
                try
                {
                    var installation = await engineInstaller.GetInstallation(version, path, Task.CompletedTask, cancellationToken);
                    AddInstallationContainer(installation);
                    logger.LogDebug("Added detected BYOND version {versionKey}...", version);
                }
                catch (Exception ex)
                {
                    logger.LogWarning(
                        ex,
                        "It seems that there are multiple directories that say they contain BYOND version {version}. We're ignoring and cleaning the duplicate: {duplicatePath}",
                        version,
                        ioManager.ResolvePath(path));
                    await ioManager.DeleteDirectory(path, cancellationToken);
                    return;
                }
                lock (installedVersionPaths)
                    installedVersionPaths.Add(ioManager.ResolvePath(version.ToString()), version);
            }
            await ValueTaskExtensions.WhenAll(
                directories
                    .Select(ReadVersion));
            logger.LogTrace("Upgrading BYOND installations...");
            await ValueTaskExtensions.WhenAll(
                installedVersionPaths
                    .Select(kvp => engineInstaller.UpgradeInstallation(kvp.Value, kvp.Key, cancellationToken)));
            var activeVersionBytes = await activeVersionBytesTask;
            if (activeVersionBytes != null)
            {
                var activeVersionString = Encoding.UTF8.GetString(activeVersionBytes);
                EngineVersion? activeVersion;
                bool hasRequestedActiveVersion;
                lock (installedVersions)
                    hasRequestedActiveVersion = EngineVersion.TryParse(activeVersionString, out activeVersion)
                        && installedVersions.ContainsKey(activeVersion!);
                if (hasRequestedActiveVersion)
                    ActiveVersion = activeVersion; // not setting TCS because there's no need during init
                else
                {
                    logger.LogWarning("Failed to load saved active version {activeVersion}!", activeVersionString);
                    await ioManager.DeleteFile(ActiveVersionFileName, cancellationToken);
                }
            }
        }
References Tgstation.Server.Host.Components.Engine.EngineManager.ActiveVersion, Tgstation.Server.Host.Components.Engine.EngineManager.ActiveVersionFileName, Tgstation.Server.Host.Components.Engine.EngineManager.AddInstallationContainer(), Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.IO.IIOManager.CreateDirectory(), Tgstation.Server.Host.IO.DefaultIOManager.CurrentDirectory, Tgstation.Server.Host.IO.IIOManager.DeleteDirectory(), Tgstation.Server.Host.IO.IIOManager.DeleteFile(), Tgstation.Server.Host.Components.Engine.EngineManager.engineInstaller, Tgstation.Server.Host.IO.IIOManager.FileExists(), Tgstation.Server.Host.IO.IIOManager.GetDirectories(), Tgstation.Server.Host.Components.Engine.IEngineInstaller.GetInstallation(), Tgstation.Server.Host.Components.Engine.EngineManager.installedVersions, Tgstation.Server.Host.Components.Engine.EngineManager.ioManager, Tgstation.Server.Host.Components.Engine.EngineManager.logger, Tgstation.Server.Host.IO.IIOManager.ReadAllBytes(), Tgstation.Server.Host.IO.IIOManager.ResolvePath(), Tgstation.Server.Api.Models.EngineVersion.ToString(), Tgstation.Server.Api.Models.EngineVersion.TryParse(), Tgstation.Server.Host.Components.Engine.IEngineInstaller.UpgradeInstallation(), Tgstation.Server.Host.Components.Engine.EngineManager.VersionFileName, and Tgstation.Server.Common.Extensions.ValueTaskExtensions.WhenAll().
Referenced by Tgstation.Server.Host.Components.Instance.StartAsync().
StopAsync()
Task Tgstation.Server.Host.Components.Engine.EngineManager.StopAsync (CancellationToken cancellationToken)
Referenced by Tgstation.Server.Host.Components.Instance.StopAsync().
UseExecutables()
async ValueTask< IEngineExecutableLock > Tgstation.Server.Host.Components.Engine.EngineManager.UseExecutables (EngineVersion? requiredVersion, string? trustDmbFullPath, CancellationToken cancellationToken)
Lock the current installation's location and return a IEngineExecutableLock.
Parameters
requiredVersion The EngineVersion required.
trustDmbFullPath The optional full path to .dmb to trust while using the executables.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the requested IEngineExecutableLock.
Implements Tgstation.Server.Host.Components.Engine.IEngineManager.
Definition at line 177 of file EngineManager.cs.
        {
            logger.LogTrace(
                "Acquiring lock on BYOND version {version}...",
                requiredVersion?.ToString() ?? $"{ActiveVersion} (active)");
            var versionToUse = requiredVersion ?? ActiveVersion ?? throw new JobException(ErrorCode.EngineNoVersionsInstalled);
            using var progressReporter = new JobProgressReporter();
            var installLock = await AssertAndLockVersion(
                progressReporter,
                versionToUse,
                null,
                requiredVersion != null,
                true,
                cancellationToken);
            try
            {
                if (trustDmbFullPath != null)
                    await engineInstaller.TrustDmbPath(installLock.Version, trustDmbFullPath, cancellationToken);
                return installLock;
            }
            catch
            {
                installLock.Dispose();
                throw;
            }
        }
References Tgstation.Server.Host.Components.Engine.EngineManager.ActiveVersion, Tgstation.Server.Host.Components.Engine.EngineManager.AssertAndLockVersion(), Tgstation.Server.Host.Components.Engine.EngineManager.engineInstaller, Tgstation.Server.Host.Components.Engine.EngineManager.logger, and Tgstation.Server.Host.Components.Engine.IEngineInstaller.TrustDmbPath().
Member Data Documentation
activeVersionChanged
volatile TaskCompletionSource Tgstation.Server.Host.Components.Engine.EngineManager.activeVersionChanged private
TaskCompletionSource that notifes when the ActiveVersion changes.
Definition at line 86 of file EngineManager.cs.
Referenced by Tgstation.Server.Host.Components.Engine.EngineManager.ChangeVersion(), Tgstation.Server.Host.Components.Engine.EngineManager.DeleteVersion(), and Tgstation.Server.Host.Components.Engine.EngineManager.EngineManager().
ActiveVersionFileName
const string Tgstation.Server.Host.Components.Engine.EngineManager.ActiveVersionFileName = "ActiveVersion.txt" static private
The file in which we store the ActiveVersion.
Definition at line 33 of file EngineManager.cs.
Referenced by Tgstation.Server.Host.Components.Engine.EngineManager.ChangeVersion(), and Tgstation.Server.Host.Components.Engine.EngineManager.StartAsync().
changeDeleteSemaphore
readonly SemaphoreSlim Tgstation.Server.Host.Components.Engine.EngineManager.changeDeleteSemaphore private
The SemaphoreSlim for changing or deleting the active BYOND version.
Definition at line 81 of file EngineManager.cs.
Referenced by Tgstation.Server.Host.Components.Engine.EngineManager.ChangeVersion(), Tgstation.Server.Host.Components.Engine.EngineManager.DeleteVersion(), and Tgstation.Server.Host.Components.Engine.EngineManager.EngineManager().
dmbFactory
readonly IDmbFactory Tgstation.Server.Host.Components.Engine.EngineManager.dmbFactory private
The IDmbFactory for the EngineManager.
Definition at line 66 of file EngineManager.cs.
Referenced by Tgstation.Server.Host.Components.Engine.EngineManager.DeleteVersion(), and Tgstation.Server.Host.Components.Engine.EngineManager.EngineManager().
engineInstaller
readonly IEngineInstaller Tgstation.Server.Host.Components.Engine.EngineManager.engineInstaller private
The IEngineInstaller for the EngineManager.
Definition at line 56 of file EngineManager.cs.
Referenced by Tgstation.Server.Host.Components.Engine.EngineManager.AssertAndLockVersion(), Tgstation.Server.Host.Components.Engine.EngineManager.EngineManager(), Tgstation.Server.Host.Components.Engine.EngineManager.InstallVersionFiles(), Tgstation.Server.Host.Components.Engine.EngineManager.StartAsync(), and Tgstation.Server.Host.Components.Engine.EngineManager.UseExecutables().
eventConsumer
readonly IEventConsumer Tgstation.Server.Host.Components.Engine.EngineManager.eventConsumer private
The IEventConsumer for the EngineManager.
Definition at line 61 of file EngineManager.cs.
Referenced by Tgstation.Server.Host.Components.Engine.EngineManager.AssertAndLockVersion(), Tgstation.Server.Host.Components.Engine.EngineManager.ChangeVersion(), and Tgstation.Server.Host.Components.Engine.EngineManager.EngineManager().
installedVersions
readonly Dictionary<EngineVersion, ReferenceCountingContainer<IEngineInstallation, EngineExecutableLock> > Tgstation.Server.Host.Components.Engine.EngineManager.installedVersions private
Map of byond EngineVersions to Tasks that complete when they are installed.
Definition at line 76 of file EngineManager.cs.
Referenced by Tgstation.Server.Host.Components.Engine.EngineManager.AddInstallationContainer(), Tgstation.Server.Host.Components.Engine.EngineManager.AssertAndLockVersion(), Tgstation.Server.Host.Components.Engine.EngineManager.DeleteVersion(), Tgstation.Server.Host.Components.Engine.EngineManager.EngineManager(), and Tgstation.Server.Host.Components.Engine.EngineManager.StartAsync().
ioManager
readonly IIOManager Tgstation.Server.Host.Components.Engine.EngineManager.ioManager private
The IIOManager for the EngineManager.
Definition at line 51 of file EngineManager.cs.
Referenced by Tgstation.Server.Host.Components.Engine.EngineManager.AssertAndLockVersion(), Tgstation.Server.Host.Components.Engine.EngineManager.ChangeVersion(), Tgstation.Server.Host.Components.Engine.EngineManager.DeleteVersion(), Tgstation.Server.Host.Components.Engine.EngineManager.EngineManager(), Tgstation.Server.Host.Components.Engine.EngineManager.InstallVersionFiles(), and Tgstation.Server.Host.Components.Engine.EngineManager.StartAsync().
logger
readonly ILogger<EngineManager> Tgstation.Server.Host.Components.Engine.EngineManager.logger private
The ILogger for the EngineManager.
Definition at line 71 of file EngineManager.cs.
Referenced by Tgstation.Server.Host.Components.Engine.EngineManager.AssertAndLockVersion(), Tgstation.Server.Host.Components.Engine.EngineManager.ChangeVersion(), Tgstation.Server.Host.Components.Engine.EngineManager.DeleteVersion(), Tgstation.Server.Host.Components.Engine.EngineManager.EngineManager(), Tgstation.Server.Host.Components.Engine.EngineManager.InstallVersionFiles(), Tgstation.Server.Host.Components.Engine.EngineManager.StartAsync(), and Tgstation.Server.Host.Components.Engine.EngineManager.UseExecutables().
VersionFileName
const string Tgstation.Server.Host.Components.Engine.EngineManager.VersionFileName = "Version.txt" static private
The file in which we store the Version for installations.
Definition at line 28 of file EngineManager.cs.
Referenced by Tgstation.Server.Host.Components.Engine.EngineManager.DeleteVersion(), Tgstation.Server.Host.Components.Engine.EngineManager.InstallVersionFiles(), and Tgstation.Server.Host.Components.Engine.EngineManager.StartAsync().
Property Documentation
ActiveVersion
EngineVersion? Tgstation.Server.Host.Components.Engine.EngineManager.ActiveVersion get private set
The currently active EngineVersion.
Implements Tgstation.Server.Host.Components.Engine.IEngineManager.
Definition at line 36 of file EngineManager.cs.
{ get; private set; }
Referenced by Tgstation.Server.Host.Components.Engine.EngineManager.ChangeVersion(), Tgstation.Server.Host.Components.Engine.EngineManager.DeleteVersion(), Tgstation.Server.Host.Components.Engine.EngineManager.StartAsync(), and Tgstation.Server.Host.Components.Engine.EngineManager.UseExecutables().
InstalledVersions
IReadOnlyList<EngineVersion> Tgstation.Server.Host.Components.Engine.EngineManager.InstalledVersions get
The installed EngineVersions.
Implements Tgstation.Server.Host.Components.Engine.IEngineManager.
Definition at line 39 of file EngineManager.cs.
        {
            get
            {
                lock (installedVersions)
                    return installedVersions.Keys.ToList();
            }
        }
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Engine/EngineManager.cs