tgstation-server: Tgstation.Server.Host.IO.DefaultIOManager Class Reference
Tgstation.Server.Host.IO.DefaultIOManager Class Reference
IIOManager that resolves paths to Environment.CurrentDirectory.
Public Member Functions
DefaultIOManager (IFileSystem fileSystem)
Initializes a new instance of the DefaultIOManager class.
async ValueTask CopyDirectory (IEnumerable< string >? ignore, Func< string, string, ValueTask >? postCopyCallback, string src, string dest, int? taskThrottle, CancellationToken cancellationToken)
Copies a directory from src to dest .
Parameters
ignore Files and folders to ignore at the root level.
postCopyCallback The optional callback called for each source/dest file pair post copy.
src The source directory path.
dest The destination directory path.
taskThrottle The optional maximum number of simultaneous tasks allowed to execute.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
string ConcatPath (params string[] paths)
Combines an array of strings into a path.
Parameters
paths The paths to combine.
Returns
The combined path.
async ValueTask CopyFile (string src, string dest, CancellationToken cancellationToken)
Copy a file from src to dest .
Parameters
src The source file to copy.
dest The destination path.
cancellationToken A CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Task CreateDirectory (string path, CancellationToken cancellationToken)
Create a directory at path .
Parameters
path The path of the directory to create.
cancellationToken A CancellationToken for the operation.
Returns
A Task representing the running operation.
Task DeleteDirectory (string path, CancellationToken cancellationToken)
Recursively delete a directory, removes and does not enter any symlinks encounterd.
Parameters
path The path to the directory to delete.
cancellationToken A CancellationToken for the operation.
Returns
A Task representing the running operation.
Task DeleteFile (string path, CancellationToken cancellationToken)
Deletes a file at path .
Parameters
path The path of the file to delete.
cancellationToken A CancellationToken for the operation.
Returns
A Task representing the running operation.
Task< bool > FileExists (string path, CancellationToken cancellationToken)
Check that the file at path exists.
Parameters
path The file to check for existence.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in true if the file at path exists, false otherwise.
Task< bool > DirectoryExists (string path, CancellationToken cancellationToken)
Check that the directory at path exists.
Parameters
path The directory to check for existence.
cancellationToken The CancellationToken for the operation.
Returns
A Task resulting in true if the directory at path exists, false otherwise.
string GetDirectoryName (string path)
Gets the directory portion of a given path .
Parameters
path A path to check.
Returns
The directory portion of the given path .
Exceptions
InvalidOperationException If path is rooted.
string GetFileName (string path)
Gets the file name portion of a path .
Parameters
path The path to get the file name of.
Returns
The file name portion of path .
string GetFileNameWithoutExtension (string path)
Gets the file name portion of a path with.
Parameters
path The path to get the file name of.
Returns
The file name portion of path .
Task< List< string > > GetFilesWithExtension (string path, string extension, bool recursive, CancellationToken cancellationToken)
Gets a list of files in path with the given extension .
Parameters
path The directory which contains the files.
extension The extension to look for without the preceeding ".".
recursive If the search should be recursive.
cancellationToken A CancellationToken for the operation.
Returns
A Task resulting in a list of paths to files in path with the given extension .
Task MoveFile (string source, string destination, CancellationToken cancellationToken)
Moves a file at source to destination .
Parameters
source The source file path.
destination The destination path.
cancellationToken A CancellationToken for the operation.
Returns
A Task representing the running operation.
Task MoveDirectory (string source, string destination, CancellationToken cancellationToken)
Moves a directory at source to destination .
Parameters
source The source directory path.
destination The destination path.
cancellationToken A CancellationToken for the operation.
Returns
A Task representing the running operation.
async ValueTask< byte[]> ReadAllBytes (string path, CancellationToken cancellationToken)
Returns all the contents of a file at path as a byte array.
Parameters
path The path of the file to read.
cancellationToken A CancellationToken for the operation.
Returns
A ValueTask that results in the contents of a file at path .
This function will fail to read files from the /proc filesystem on Linux.
string ResolvePath ()
Retrieve the full path of the current working directory.
Returns
The full path of the current working directory.
string ResolvePath (string path)
Retrieve the full path of some path given a relative path. Must be used before passing relative paths to other APIs. All other operations in this interface call this internally on given paths.
Parameters
path Some path to retrieve the full path of.
Returns
path as a full path.
async ValueTask WriteAllBytes (string path, byte[] contents, CancellationToken cancellationToken)
Writes some contents to a file at path overwriting previous content.
Parameters
path The path of the file to write.
contents The contents of the file.
cancellationToken A CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Stream CreateAsyncSequentialWriteStream (string path)
Creates an asynchronous FileStream for sequential writing.
Parameters
path The path of the file to write, will be truncated.
Returns
The open Stream.
Stream CreateAsyncReadStream (string path, bool sequental, bool shareWrite)
Creates an asynchronous FileStream for sequential reading.
Parameters
path The path of the file to write, will be truncated.
sequential If the sequential read flag should be added.
shareWrite If FileShare.Write should be used.
Returns
The open Stream.
Task< IReadOnlyList< string > > GetDirectories (string path, CancellationToken cancellationToken)
Returns full directory names in a given path .
Parameters
path The path to search for directories.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the directories in path .
Task< IReadOnlyList< string > > GetFiles (string path, CancellationToken cancellationToken)
Returns full file names in a given path .
Parameters
path The path to search for files.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the files in path .
async ValueTask ZipToDirectory (string path, Stream zipFile, CancellationToken cancellationToken)
Extract a set of zipFile to a given path .
Parameters
path The path to unzip to.
zipFile The Stream of the global::System.IO.Compression.ZipArchive. Must have Stream.CanSeek set to true. Will be read completely and left open. Stream.Position will be indeterminate.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
bool PathContainsParentAccess (string path)
Check if a path contains the '..' parent directory accessor.
Parameters
path The path to check.
Returns
true if path contains a '..' accessor, false otherwise.
Task< DateTimeOffset > GetLastModified (string path, CancellationToken cancellationToken)
Get the DateTimeOffset of when a given path was last modified.
Parameters
path The path to get metadata for.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the DateTimeOffset of when the file was last modified.
Task< bool > PathIsChildOf (string parentPath, string childPath, CancellationToken cancellationToken)
Check if a given parentPath is a parent of a given parentPath .
Parameters
parentPath The parent path.
childPath The child path.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in true if childPath is a child of parentPath or they are equivalent.
Task< IDirectoryInfo > DirectoryInfo (string path, CancellationToken cancellationToken)
Gets a IDirectoryInfo for the given path .
Parameters
path The path to get IDirectoryInfo for.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the IDirectoryInfo of the path .
bool IsPathRooted (string path)
Check if a given path is at the root level of the filesystem.
Parameters
path The path to check.
Returns
true if the path is rooted, false otherwise.
IIOManager CreateResolverForSubdirectory (string subdirectoryPath)
Create a new IIOManager that resolves paths to the specified subdirectoryPath .
Parameters
subdirectoryPath A relative or absolute path that the new IIOManager will resolve as its current directory.
Returns
A new IIOManager.
Static Public Attributes
const string CurrentDirectory = "."
Path to the current working directory for the IIOManager.
const int DefaultBufferSize = 4096
Default FileStream buffer size used by .NET.
const TaskCreationOptions BlockingTaskCreationOptions = TaskCreationOptions.None
The TaskCreationOptions used to spawn Tasks for potentially long running, blocking operations.
Protected Member Functions
virtual string ResolvePathCore (string path)
Resolve a given, non-rooted, path .
Properties
char DirectorySeparatorChar [get]
Gets the primary directory separator character.
char AltDirectorySeparatorChar [get]
Gets the alternative directory separator character.
Properties inherited from Tgstation.Server.Host.IO.IIOManager
Private Member Functions
IEnumerable< Task > CopyDirectoryImpl (string src, string dest, IEnumerable< string >? ignore, Func< string, string, ValueTask >? postCopyCallback, SemaphoreSlim? semaphore, CancellationToken cancellationToken)
Copies a directory from src to dest .
Static Private Member Functions
static void NormalizeAndDelete (IDirectoryInfo dir, CancellationToken cancellationToken)
Recursively empty a directory.
Private Attributes
readonly IFileSystem fileSystem
The backing IFileSystem.
Detailed Description
IIOManager that resolves paths to Environment.CurrentDirectory.
Definition at line 18 of file DefaultIOManager.cs.
Constructor & Destructor Documentation
DefaultIOManager()
Tgstation.Server.Host.IO.DefaultIOManager.DefaultIOManager (IFileSystem fileSystem)
Initializes a new instance of the DefaultIOManager class.
Parameters
fileSystem The value of fileSystem.
Definition at line 50 of file DefaultIOManager.cs.
        {
            this.fileSystem = fileSystem ?? throw new ArgumentNullException(nameof(fileSystem));
        }
References Tgstation.Server.Host.IO.DefaultIOManager.fileSystem.
Member Function Documentation
ConcatPath()
string Tgstation.Server.Host.IO.DefaultIOManager.ConcatPath (params string[] paths)
Combines an array of strings into a path.
Parameters
paths The paths to combine.
Returns
The combined path.
Implements Tgstation.Server.Host.IO.IIOManager.
Referenced by Tgstation.Server.Host.IO.DefaultIOManager.CopyDirectoryImpl(), and Tgstation.Server.Host.IO.DefaultIOManager.CreateResolverForSubdirectory().
CopyDirectory()
async ValueTask Tgstation.Server.Host.IO.DefaultIOManager.CopyDirectory (IEnumerable< string >? ignore, Func< string, string, ValueTask >? postCopyCallback, string src, string dest, int? taskThrottle, CancellationToken cancellationToken)
Copies a directory from src to dest .
Parameters
ignore Files and folders to ignore at the root level.
postCopyCallback The optional callback called for each source/dest file pair post copy.
src The source directory path.
dest The destination directory path.
taskThrottle The optional maximum number of simultaneous tasks allowed to execute.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.IO.IIOManager.
Definition at line 114 of file DefaultIOManager.cs.
        {
            ArgumentNullException.ThrowIfNull(src);
            ArgumentNullException.ThrowIfNull(src);
            if (taskThrottle.HasValue && taskThrottle < 1)
                throw new ArgumentOutOfRangeException(nameof(taskThrottle), taskThrottle, "taskThrottle must be at least 1!");
            src = ResolvePath(src);
            dest = ResolvePath(dest);
            using var semaphore = taskThrottle.HasValue ? new SemaphoreSlim(taskThrottle.Value) : null;
            await Task.WhenAll(CopyDirectoryImpl(src, dest, ignore, postCopyCallback, semaphore, cancellationToken));
        }
References Tgstation.Server.Host.IO.DefaultIOManager.CopyDirectoryImpl(), and Tgstation.Server.Host.IO.DefaultIOManager.ResolvePath().
CopyDirectoryImpl()
IEnumerable< Task > Tgstation.Server.Host.IO.DefaultIOManager.CopyDirectoryImpl (string src, string dest, IEnumerable< string >? ignore, Func< string, string, ValueTask >? postCopyCallback, SemaphoreSlim? semaphore, CancellationToken cancellationToken) private
Copies a directory from src to dest .
Parameters
src The source directory path.
dest The destination directory path.
ignore Optional files and folders to ignore at the root level.
postCopyCallback The optional callback called for each source/dest file pair post copy.
semaphore Optional SemaphoreSlim used to limit degree of parallelism.
cancellationToken The CancellationToken for the operation.
Returns
A IEnumerable<T> of Tasks representing the running operations. The first Task returned is always the necessary call to CreateDirectory(string, CancellationToken).
Definition at line 479 of file DefaultIOManager.cs.
        {
            var dir = fileSystem.DirectoryInfo.New(src);
            Task? subdirCreationTask = null;
            foreach (var subDirectory in dir.EnumerateDirectories())
            {
                if (ignore != null && ignore.Contains(subDirectory.Name))
                    continue;
                var checkingSubdirCreationTask = true;
                foreach (var copyTask in CopyDirectoryImpl(subDirectory.FullName, fileSystem.Path.Combine(dest, subDirectory.Name), null, postCopyCallback, semaphore, cancellationToken))
                {
                    if (subdirCreationTask == null)
                    {
                        subdirCreationTask = copyTask;
                        yield return subdirCreationTask;
                    }
                    else if (!checkingSubdirCreationTask)
                        yield return copyTask;
                    checkingSubdirCreationTask = false;
                }
            }
            foreach (var fileInfo in dir.EnumerateFiles())
            {
                if (subdirCreationTask == null)
                {
                    subdirCreationTask = CreateDirectory(dest, cancellationToken);
                    yield return subdirCreationTask;
                }
                if (ignore != null && ignore.Contains(fileInfo.Name))
                    continue;
                var sourceFile = fileInfo.FullName;
                var destFile = ConcatPath(dest, fileInfo.Name);
                async Task CopyThisFile()
                {
                    await subdirCreationTask.WaitAsync(cancellationToken);
                    using var lockContext = semaphore != null
                        ? await SemaphoreSlimContext.Lock(semaphore, cancellationToken)
                        : null;
                    await CopyFile(sourceFile, destFile, cancellationToken);
                    if (postCopyCallback != null)
                        await postCopyCallback(sourceFile, destFile);
                }
                yield return CopyThisFile();
            }
        }
References Tgstation.Server.Host.IO.DefaultIOManager.ConcatPath(), Tgstation.Server.Host.IO.DefaultIOManager.CopyDirectoryImpl(), Tgstation.Server.Host.IO.DefaultIOManager.CopyFile(), Tgstation.Server.Host.IO.DefaultIOManager.CreateDirectory(), Tgstation.Server.Host.IO.DefaultIOManager.fileSystem, and Tgstation.Server.Host.Utils.SemaphoreSlimContext.Lock().
Referenced by Tgstation.Server.Host.IO.DefaultIOManager.CopyDirectory(), and Tgstation.Server.Host.IO.DefaultIOManager.CopyDirectoryImpl().
CopyFile()
async ValueTask Tgstation.Server.Host.IO.DefaultIOManager.CopyFile (string src, string dest, CancellationToken cancellationToken)
Copy a file from src to dest .
Parameters
src The source file to copy.
dest The destination path.
cancellationToken A CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.IO.IIOManager.
Definition at line 139 of file DefaultIOManager.cs.
        {
            ArgumentNullException.ThrowIfNull(src);
            ArgumentNullException.ThrowIfNull(dest);
            // tested to hell and back, these are the optimal buffer sizes
            await using var srcStream = fileSystem.FileStream.New(
                ResolvePath(src),
                FileMode.Open,
                FileAccess.Read,
                FileShare.Read | FileShare.Delete,
                DefaultBufferSize,
                FileOptions.Asynchronous | FileOptions.SequentialScan);
            await using var destStream = CreateAsyncSequentialWriteStream(dest);
            // value taken from documentation
            await srcStream.CopyToAsync(destStream, 81920, cancellationToken);
        }
References Tgstation.Server.Host.IO.DefaultIOManager.CreateAsyncSequentialWriteStream(), Tgstation.Server.Host.IO.DefaultIOManager.DefaultBufferSize, Tgstation.Server.Host.IO.DefaultIOManager.fileSystem, and Tgstation.Server.Host.IO.DefaultIOManager.ResolvePath().
Referenced by Tgstation.Server.Host.IO.DefaultIOManager.CopyDirectoryImpl().
CreateAsyncReadStream()
Stream Tgstation.Server.Host.IO.DefaultIOManager.CreateAsyncReadStream (string path, bool sequental, bool shareWrite)
Creates an asynchronous FileStream for sequential reading.
Parameters
path The path of the file to write, will be truncated.
sequential If the sequential read flag should be added.
shareWrite If FileShare.Write should be used.
Returns
The open Stream.
Implements Tgstation.Server.Host.IO.IIOManager.
Definition at line 291 of file DefaultIOManager.cs.
        {
            path = ResolvePath(path);
            return fileSystem.FileStream.New(
                path,
                FileMode.Open,
                FileAccess.Read,
                FileShare.ReadWrite | FileShare.Delete | (shareWrite ? FileShare.Write : FileShare.None),
                DefaultBufferSize,
                sequental
                    ? FileOptions.Asynchronous | FileOptions.SequentialScan
                    : FileOptions.Asynchronous);
        }
References Tgstation.Server.Host.IO.DefaultIOManager.DefaultBufferSize, Tgstation.Server.Host.IO.DefaultIOManager.fileSystem, and Tgstation.Server.Host.IO.DefaultIOManager.ResolvePath().
Referenced by Tgstation.Server.Host.IO.DefaultIOManager.ReadAllBytes().
CreateAsyncSequentialWriteStream()
Stream Tgstation.Server.Host.IO.DefaultIOManager.CreateAsyncSequentialWriteStream (string path)
Creates an asynchronous FileStream for sequential writing.
Parameters
path The path of the file to write, will be truncated.
Returns
The open Stream.
Implements Tgstation.Server.Host.IO.IIOManager.
Definition at line 278 of file DefaultIOManager.cs.
        {
            path = ResolvePath(path);
            return fileSystem.FileStream.New(
                path,
                FileMode.Create,
                FileAccess.Write,
                FileShare.Read | FileShare.Delete,
                DefaultBufferSize,
                FileOptions.Asynchronous | FileOptions.SequentialScan);
        }
References Tgstation.Server.Host.IO.DefaultIOManager.DefaultBufferSize, Tgstation.Server.Host.IO.DefaultIOManager.fileSystem, and Tgstation.Server.Host.IO.DefaultIOManager.ResolvePath().
Referenced by Tgstation.Server.Host.IO.DefaultIOManager.CopyFile(), and Tgstation.Server.Host.IO.DefaultIOManager.WriteAllBytes().
CreateDirectory()
Task Tgstation.Server.Host.IO.DefaultIOManager.CreateDirectory (string path, CancellationToken cancellationToken)
Create a directory at path .
Parameters
path The path of the directory to create.
cancellationToken A CancellationToken for the operation.
Returns
A Task representing the running operation.
Implements Tgstation.Server.Host.IO.IIOManager.
Referenced by Tgstation.Server.Host.IO.DefaultIOManager.CopyDirectoryImpl().
CreateResolverForSubdirectory()
IIOManager Tgstation.Server.Host.IO.DefaultIOManager.CreateResolverForSubdirectory (string subdirectoryPath)
Create a new IIOManager that resolves paths to the specified subdirectoryPath .
Parameters
subdirectoryPath A relative or absolute path that the new IIOManager will resolve as its current directory.
Returns
A new IIOManager.
Implements Tgstation.Server.Host.IO.IIOManager.
Definition at line 447 of file DefaultIOManager.cs.
        {
            ArgumentNullException.ThrowIfNull(subdirectoryPath);
            if (!fileSystem.Path.IsPathRooted(subdirectoryPath))
                subdirectoryPath = ConcatPath(
                    ResolvePath(),
                    subdirectoryPath);
            return new ResolvingIOManager(
                fileSystem,
                subdirectoryPath);
        }
References Tgstation.Server.Host.IO.DefaultIOManager.ConcatPath(), Tgstation.Server.Host.IO.DefaultIOManager.fileSystem, and Tgstation.Server.Host.IO.DefaultIOManager.ResolvePath().
DeleteDirectory()
Task Tgstation.Server.Host.IO.DefaultIOManager.DeleteDirectory (string path, CancellationToken cancellationToken)
Recursively delete a directory, removes and does not enter any symlinks encounterd.
Parameters
path The path to the directory to delete.
cancellationToken A CancellationToken for the operation.
Returns
A Task representing the running operation.
Implements Tgstation.Server.Host.IO.IIOManager.
References Tgstation.Server.Host.IO.DefaultIOManager.fileSystem, Tgstation.Server.Host.IO.DefaultIOManager.NormalizeAndDelete(), and Tgstation.Server.Host.IO.DefaultIOManager.ResolvePath().
DeleteFile()
Task Tgstation.Server.Host.IO.DefaultIOManager.DeleteFile (string path, CancellationToken cancellationToken)
Deletes a file at path .
Parameters
path The path of the file to delete.
cancellationToken A CancellationToken for the operation.
Returns
A Task representing the running operation.
Implements Tgstation.Server.Host.IO.IIOManager.
DirectoryExists()
Task< bool > Tgstation.Server.Host.IO.DefaultIOManager.DirectoryExists (string path, CancellationToken cancellationToken)
Check that the directory at path exists.
Parameters
path The directory to check for existence.
cancellationToken The CancellationToken for the operation.
Returns
A Task resulting in true if the directory at path exists, false otherwise.
Implements Tgstation.Server.Host.IO.IIOManager.
DirectoryInfo()
Task< IDirectoryInfo > Tgstation.Server.Host.IO.DefaultIOManager.DirectoryInfo (string path, CancellationToken cancellationToken)
Gets a IDirectoryInfo for the given path .
Parameters
path The path to get IDirectoryInfo for.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the IDirectoryInfo of the path .
Implements Tgstation.Server.Host.IO.IIOManager.
FileExists()
Task< bool > Tgstation.Server.Host.IO.DefaultIOManager.FileExists (string path, CancellationToken cancellationToken)
Check that the file at path exists.
Parameters
path The file to check for existence.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in true if the file at path exists, false otherwise.
Implements Tgstation.Server.Host.IO.IIOManager.
GetDirectories()
Task< IReadOnlyList< string > > Tgstation.Server.Host.IO.DefaultIOManager.GetDirectories (string path, CancellationToken cancellationToken)
Returns full directory names in a given path .
Parameters
path The path to search for directories.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the directories in path .
Implements Tgstation.Server.Host.IO.IIOManager.
References Tgstation.Server.Host.IO.DefaultIOManager.fileSystem, and Tgstation.Server.Host.IO.DefaultIOManager.ResolvePath().
GetDirectoryName()
string Tgstation.Server.Host.IO.DefaultIOManager.GetDirectoryName (string path)
Gets the directory portion of a given path .
Parameters
path A path to check.
Returns
The directory portion of the given path .
Exceptions
InvalidOperationException If path is rooted.
Implements Tgstation.Server.Host.IO.IIOManager.
GetFileName()
string Tgstation.Server.Host.IO.DefaultIOManager.GetFileName (string path)
Gets the file name portion of a path .
Parameters
path The path to get the file name of.
Returns
The file name portion of path .
Implements Tgstation.Server.Host.IO.IIOManager.
GetFileNameWithoutExtension()
string Tgstation.Server.Host.IO.DefaultIOManager.GetFileNameWithoutExtension (string path)
Gets the file name portion of a path with.
Parameters
path The path to get the file name of.
Returns
The file name portion of path .
Implements Tgstation.Server.Host.IO.IIOManager.
GetFiles()
Task< IReadOnlyList< string > > Tgstation.Server.Host.IO.DefaultIOManager.GetFiles (string path, CancellationToken cancellationToken)
Returns full file names in a given path .
Parameters
path The path to search for files.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the files in path .
Implements Tgstation.Server.Host.IO.IIOManager.
References Tgstation.Server.Host.IO.DefaultIOManager.fileSystem, and Tgstation.Server.Host.IO.DefaultIOManager.ResolvePath().
GetFilesWithExtension()
Task< List< string > > Tgstation.Server.Host.IO.DefaultIOManager.GetFilesWithExtension (string path, string extension, bool recursive, CancellationToken cancellationToken)
Gets a list of files in path with the given extension .
Parameters
path The directory which contains the files.
extension The extension to look for without the preceeding ".".
recursive If the search should be recursive.
cancellationToken A CancellationToken for the operation.
Returns
A Task resulting in a list of paths to files in path with the given extension .
Implements Tgstation.Server.Host.IO.IIOManager.
References Tgstation.Server.Host.IO.DefaultIOManager.fileSystem, and Tgstation.Server.Host.IO.DefaultIOManager.ResolvePath().
GetLastModified()
Task< DateTimeOffset > Tgstation.Server.Host.IO.DefaultIOManager.GetLastModified (string path, CancellationToken cancellationToken)
Get the DateTimeOffset of when a given path was last modified.
Parameters
path The path to get metadata for.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the DateTimeOffset of when the file was last modified.
Implements Tgstation.Server.Host.IO.IIOManager.
References Tgstation.Server.Host.IO.DefaultIOManager.fileSystem, and Tgstation.Server.Host.IO.DefaultIOManager.ResolvePath().
IsPathRooted()
bool Tgstation.Server.Host.IO.DefaultIOManager.IsPathRooted (string path)
Check if a given path is at the root level of the filesystem.
Parameters
path The path to check.
Returns
true if the path is rooted, false otherwise.
Implements Tgstation.Server.Host.IO.IIOManager.
MoveDirectory()
Task Tgstation.Server.Host.IO.DefaultIOManager.MoveDirectory (string source, string destination, CancellationToken cancellationToken)
Moves a directory at source to destination .
Parameters
source The source directory path.
destination The destination path.
cancellationToken A CancellationToken for the operation.
Returns
A Task representing the running operation.
Implements Tgstation.Server.Host.IO.IIOManager.
References Tgstation.Server.Host.IO.DefaultIOManager.fileSystem, and Tgstation.Server.Host.IO.DefaultIOManager.ResolvePath().
MoveFile()
Task Tgstation.Server.Host.IO.DefaultIOManager.MoveFile (string source, string destination, CancellationToken cancellationToken)
Moves a file at source to destination .
Parameters
source The source file path.
destination The destination path.
cancellationToken A CancellationToken for the operation.
Returns
A Task representing the running operation.
Implements Tgstation.Server.Host.IO.IIOManager.
References Tgstation.Server.Host.IO.DefaultIOManager.fileSystem, and Tgstation.Server.Host.IO.DefaultIOManager.ResolvePath().
NormalizeAndDelete()
static void Tgstation.Server.Host.IO.DefaultIOManager.NormalizeAndDelete (IDirectoryInfo dir, CancellationToken cancellationToken) static private
Recursively empty a directory.
Parameters
dir DirectoryInfo of the directory to empty.
cancellationToken The CancellationToken for the operation.
Definition at line 60 of file DefaultIOManager.cs.
        {
            cancellationToken.ThrowIfCancellationRequested();
            // check if we are a symbolic link
            if (!dir.Attributes.HasFlag(FileAttributes.Directory) || dir.Attributes.HasFlag(FileAttributes.ReparsePoint))
            {
                dir.Delete();
                return;
            }
            List<Exception>? exceptions = null;
            foreach (var subDir in dir.EnumerateDirectories())
                try
                {
                    NormalizeAndDelete(subDir, cancellationToken);
                }
                catch (AggregateException ex)
                {
                    exceptions ??= new List<Exception>();
                    exceptions.AddRange(ex.InnerExceptions);
                }
            foreach (var file in dir.EnumerateFiles())
            {
                cancellationToken.ThrowIfCancellationRequested();
                try
                {
                    file.Attributes = FileAttributes.Normal;
                    file.Delete();
                }
                catch (Exception ex)
                {
                    exceptions ??= new List<Exception>();
                    exceptions.Add(ex);
                }
            }
            cancellationToken.ThrowIfCancellationRequested();
            try
            {
                dir.Delete(true);
            }
            catch (Exception ex)
            {
                exceptions ??= new List<Exception>();
                exceptions.Add(ex);
            }
            if (exceptions != null)
                throw new AggregateException(exceptions);
        }
References Tgstation.Server.Host.IO.DefaultIOManager.NormalizeAndDelete().
Referenced by Tgstation.Server.Host.IO.DefaultIOManager.DeleteDirectory(), and Tgstation.Server.Host.IO.DefaultIOManager.NormalizeAndDelete().
PathContainsParentAccess()
bool Tgstation.Server.Host.IO.DefaultIOManager.PathContainsParentAccess (string path)
Check if a path contains the '..' parent directory accessor.
Parameters
path The path to check.
Returns
true if path contains a '..' accessor, false otherwise.
Implements Tgstation.Server.Host.IO.IIOManager.
PathIsChildOf()
Task< bool > Tgstation.Server.Host.IO.DefaultIOManager.PathIsChildOf (string parentPath, string childPath, CancellationToken cancellationToken)
Check if a given parentPath is a parent of a given parentPath .
Parameters
parentPath The parent path.
childPath The child path.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in true if childPath is a child of parentPath or they are equivalent.
Implements Tgstation.Server.Host.IO.IIOManager.
References Tgstation.Server.Host.IO.DefaultIOManager.fileSystem, and Tgstation.Server.Host.IO.DefaultIOManager.ResolvePath().
ReadAllBytes()
async ValueTask< byte[]> Tgstation.Server.Host.IO.DefaultIOManager.ReadAllBytes (string path, CancellationToken cancellationToken)
Returns all the contents of a file at path as a byte array.
Parameters
path The path of the file to read.
cancellationToken A CancellationToken for the operation.
Returns
A ValueTask that results in the contents of a file at path .
This function will fail to read files from the /proc filesystem on Linux.
Implements Tgstation.Server.Host.IO.IIOManager.
Definition at line 243 of file DefaultIOManager.cs.
        {
            await using var file = CreateAsyncReadStream(path, true, true);
            byte[] buf;
            buf = new byte[file.Length];
            await file.ReadAsync(buf, cancellationToken);
            return buf;
        }
References Tgstation.Server.Host.IO.DefaultIOManager.CreateAsyncReadStream().
ResolvePath() [1/2]
string Tgstation.Server.Host.IO.DefaultIOManager.ResolvePath ()
Retrieve the full path of the current working directory.
Returns
The full path of the current working directory.
Implements Tgstation.Server.Host.IO.IIOManager.
Referenced by Tgstation.Server.Host.IO.DefaultIOManager.CopyDirectory(), Tgstation.Server.Host.IO.DefaultIOManager.CopyFile(), Tgstation.Server.Host.IO.DefaultIOManager.CreateAsyncReadStream(), Tgstation.Server.Host.IO.DefaultIOManager.CreateAsyncSequentialWriteStream(), Tgstation.Server.Host.IO.DefaultIOManager.CreateResolverForSubdirectory(), Tgstation.Server.Host.IO.DefaultIOManager.DeleteDirectory(), Tgstation.Server.Host.IO.DefaultIOManager.GetDirectories(), Tgstation.Server.Host.IO.DefaultIOManager.GetFiles(), Tgstation.Server.Host.IO.DefaultIOManager.GetFilesWithExtension(), Tgstation.Server.Host.IO.DefaultIOManager.GetLastModified(), Tgstation.Server.Host.IO.DefaultIOManager.MoveDirectory(), Tgstation.Server.Host.IO.DefaultIOManager.MoveFile(), Tgstation.Server.Host.IO.DefaultIOManager.PathIsChildOf(), and Tgstation.Server.Host.IO.DefaultIOManager.ZipToDirectory().
ResolvePath() [2/2]
string Tgstation.Server.Host.IO.DefaultIOManager.ResolvePath (string path)
Retrieve the full path of some path given a relative path. Must be used before passing relative paths to other APIs. All other operations in this interface call this internally on given paths.
Parameters
path Some path to retrieve the full path of.
Returns
path as a full path.
Implements Tgstation.Server.Host.IO.IIOManager.
Definition at line 257 of file DefaultIOManager.cs.
        {
            if (fileSystem.Path.IsPathRooted(path ?? throw new ArgumentNullException(nameof(path))))
            {
                // Important to evaluate the path anyway to normalize front slashes to backslashes on Windows
                // Some tools (looking at you netsh.exe) bitch if you pass them forward slashes as directory separators
                // Can't rely on ResolvePathCore to do this either because its contract stipulates a relative path
                return fileSystem.Path.GetFullPath(path);
            }
            return ResolvePathCore(path);
        }
References Tgstation.Server.Host.IO.DefaultIOManager.fileSystem, and Tgstation.Server.Host.IO.DefaultIOManager.ResolvePathCore().
ResolvePathCore()
virtual string Tgstation.Server.Host.IO.DefaultIOManager.ResolvePathCore (string path) protected virtual
Resolve a given, non-rooted, path .
Parameters
path The non-rooted path to resolve.
Returns
The fully resolved path.
Reimplemented in Tgstation.Server.Host.IO.ResolvingIOManager.
Referenced by Tgstation.Server.Host.IO.DefaultIOManager.ResolvePath().
WriteAllBytes()
async ValueTask Tgstation.Server.Host.IO.DefaultIOManager.WriteAllBytes (string path, byte[] contents, CancellationToken cancellationToken)
Writes some contents to a file at path overwriting previous content.
Parameters
path The path of the file to write.
contents The contents of the file.
cancellationToken A CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.IO.IIOManager.
Definition at line 271 of file DefaultIOManager.cs.
        {
            await using var file = CreateAsyncSequentialWriteStream(path);
            await file.WriteAsync(contents, cancellationToken);
        }
References Tgstation.Server.Host.IO.DefaultIOManager.CreateAsyncSequentialWriteStream().
ZipToDirectory()
async ValueTask Tgstation.Server.Host.IO.DefaultIOManager.ZipToDirectory (string path, Stream zipFile, CancellationToken cancellationToken)
Extract a set of zipFile to a given path .
Parameters
path The path to unzip to.
zipFile The Stream of the global::System.IO.Compression.ZipArchive. Must have Stream.CanSeek set to true. Will be read completely and left open. Stream.Position will be indeterminate.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.IO.IIOManager.
Definition at line 344 of file DefaultIOManager.cs.
        {
            path = ResolvePath(path);
            ArgumentNullException.ThrowIfNull(zipFile);
#if NET9_0_OR_GREATER
#error Check if zip file seeking has been addressesed. See https://github.com/tgstation/tgstation-server/issues/1531
#endif
            // ZipArchive does a synchronous copy on unseekable streams we want to avoid
            if (!zipFile.CanSeek)
                throw new ArgumentException("Stream does not support seeking!", nameof(zipFile));
            using var archive = new ZipArchive(zipFile, ZipArchiveMode.Read, true);
            // start async context
            await Task.Yield();
            foreach (var entry in archive.Entries)
            {
                var entryPath = fileSystem.Path.Combine(path, entry.FullName);
                if (string.IsNullOrEmpty(entry.Name))
                {
                    fileSystem.Directory.CreateDirectory(entryPath);
                    continue;
                }
                var directoryPath = fileSystem.Path.GetDirectoryName(entryPath);
                if (directoryPath == null)
                {
                    throw new JobException("Zip archive concatenation resulted in a null directory path!");
                }
                fileSystem.Directory.CreateDirectory(directoryPath);
                using var entryStream = entry.Open();
                using var outputStream = fileSystem.File.Create(entryPath);
                await entryStream.CopyToAsync(outputStream, cancellationToken);
            }
        }
References Tgstation.Server.Host.IO.DefaultIOManager.fileSystem, and Tgstation.Server.Host.IO.DefaultIOManager.ResolvePath().
Member Data Documentation
BlockingTaskCreationOptions
const TaskCreationOptions Tgstation.Server.Host.IO.DefaultIOManager.BlockingTaskCreationOptions = TaskCreationOptions.None static
The TaskCreationOptions used to spawn Tasks for potentially long running, blocking operations.
Definition at line 33 of file DefaultIOManager.cs.
Referenced by Tgstation.Server.Host.Components.Repository.Repository.AddTestMerge(), Tgstation.Server.Host.Components.Repository.Repository.CheckoutObject(), Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.Connect(), Tgstation.Server.Host.Components.StaticFiles.Configuration.CreateDirectory(), Tgstation.Server.Host.System.WindowsProcessFeatures.CreateDump(), Tgstation.Server.Host.Components.Repository.LibGit2RepositoryFactory.CreateFromPath(), Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.DisconnectImpl(), Tgstation.Server.Host.Components.Repository.Repository.FetchOrigin(), Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.HardDisconnect(), Tgstation.Server.Host.Components.Repository.Repository.MergeOrigin(), Tgstation.Server.Host.System.Process.Process(), Tgstation.Server.Host.Components.StaticFiles.Configuration.Read(), Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.SendMessage(), Tgstation.Server.Host.Components.Repository.Repository.Synchronize(), Tgstation.Server.Host.Components.Repository.Repository.UpdateSubmodules(), and Tgstation.Server.Host.Components.StaticFiles.Configuration.Write().
CurrentDirectory
const string Tgstation.Server.Host.IO.DefaultIOManager.CurrentDirectory = "." static
Path to the current working directory for the IIOManager.
Definition at line 23 of file DefaultIOManager.cs.
Referenced by Tgstation.Server.Host.Controllers.InstanceController.Create(), Tgstation.Server.Host.Components.InstanceManager.MoveInstance(), Tgstation.Server.Host.Components.Engine.EngineManager.StartAsync(), and Tgstation.Server.Host.Components.StaticFiles.Configuration.ValidateConfigRelativePath().
DefaultBufferSize
const int Tgstation.Server.Host.IO.DefaultIOManager.DefaultBufferSize = 4096 static
Default FileStream buffer size used by .NET.
Definition at line 28 of file DefaultIOManager.cs.
Referenced by Tgstation.Server.Host.Transfer.FileUploadProvider.Completion(), Tgstation.Server.Host.IO.DefaultIOManager.CopyFile(), Tgstation.Server.Host.IO.DefaultIOManager.CreateAsyncReadStream(), and Tgstation.Server.Host.IO.DefaultIOManager.CreateAsyncSequentialWriteStream().
fileSystem
readonly IFileSystem Tgstation.Server.Host.IO.DefaultIOManager.fileSystem private
The backing IFileSystem.
Definition at line 44 of file DefaultIOManager.cs.
Referenced by Tgstation.Server.Host.IO.DefaultIOManager.CopyDirectoryImpl(), Tgstation.Server.Host.IO.DefaultIOManager.CopyFile(), Tgstation.Server.Host.IO.DefaultIOManager.CreateAsyncReadStream(), Tgstation.Server.Host.IO.DefaultIOManager.CreateAsyncSequentialWriteStream(), Tgstation.Server.Host.IO.DefaultIOManager.CreateResolverForSubdirectory(), Tgstation.Server.Host.IO.DefaultIOManager.DefaultIOManager(), Tgstation.Server.Host.IO.DefaultIOManager.DeleteDirectory(), Tgstation.Server.Host.IO.DefaultIOManager.GetDirectories(), Tgstation.Server.Host.IO.DefaultIOManager.GetFiles(), Tgstation.Server.Host.IO.DefaultIOManager.GetFilesWithExtension(), Tgstation.Server.Host.IO.DefaultIOManager.GetLastModified(), Tgstation.Server.Host.IO.DefaultIOManager.MoveDirectory(), Tgstation.Server.Host.IO.DefaultIOManager.MoveFile(), Tgstation.Server.Host.IO.DefaultIOManager.PathIsChildOf(), Tgstation.Server.Host.IO.DefaultIOManager.ResolvePath(), and Tgstation.Server.Host.IO.DefaultIOManager.ZipToDirectory().
Property Documentation
AltDirectorySeparatorChar
char Tgstation.Server.Host.IO.DefaultIOManager.AltDirectorySeparatorChar get
Gets the alternative directory separator character.
Implements Tgstation.Server.Host.IO.IIOManager.
Definition at line 39 of file DefaultIOManager.cs.
DirectorySeparatorChar
char Tgstation.Server.Host.IO.DefaultIOManager.DirectorySeparatorChar get
Gets the primary directory separator character.
Implements Tgstation.Server.Host.IO.IIOManager.
Definition at line 36 of file DefaultIOManager.cs.
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/IO/DefaultIOManager.cs