tgstation-server: Tgstation.Server.Host.IO.Console Class Reference
Tgstation.Server.Host.IO.Console Class Reference
Implementation of IConsole, uses global::System.Console.
Public Member Functions
Console (IPlatformIdentifier platformIdentifier)
Initializes a new instance of the Console class.
void Dispose ()
Task PressAnyKeyAsync (CancellationToken cancellationToken)
Wait for a key press on the IConsole.
Parameters
cancellationToken The CancellationToken for the operations.
Returns
A Task representing the running operation.
Task< string > ReadLineAsync (bool usePasswordChar, CancellationToken cancellationToken)
Read a line from the IConsole.
Parameters
usePasswordChar If the input should be retrieved using the '*' character.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the string read by the IConsole.
Task WriteAsync (string? text, bool newLine, CancellationToken cancellationToken)
Write some text to the IConsole.
Parameters
text The string to write.
newLine If there should be a new line after the text .
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
void SetTitle (string newTitle)
Sets a newTitle console window.
Parameters
newTitle The new Title.
Task WriteAsync (string? text, bool newLine, CancellationToken cancellationToken)
Write some text to the IConsole.
Task PressAnyKeyAsync (CancellationToken cancellationToken)
Wait for a key press on the IConsole.
Task< string > ReadLineAsync (bool usePasswordChar, CancellationToken cancellationToken)
Read a line from the IConsole.
void SetTitle (string newTitle)
Sets a newTitle console window.
Properties
string? Title [get]
Gets or sets the IConsole window's title. Can return null if getting the console title is not supported.
bool Available [get]
If the IConsole is visible to the user.
CancellationToken CancelKeyPress [get]
Gets a CancellationToken that triggers if Crtl+C or an equivalent is pressed.
Properties inherited from Tgstation.Server.Host.IO.IConsole
string? Title [get]
Gets or sets the IConsole window's title. Can return null if getting the console title is not supported.
bool Available [get]
If the IConsole is visible to the user.
CancellationToken CancelKeyPress [get]
Gets a CancellationToken that triggers if Crtl+C or an equivalent is pressed.
Private Member Functions
void CheckAvailable ()
Assert that the Console is available, throwing an InvalidOperationException otherwise.
Private Attributes
readonly IPlatformIdentifier platformIdentifier
The IPlatformIdentifier for the Console.
readonly CancellationTokenSource cancelKeyCts
The CancellationTokenSource for CancelKeyPress.
bool disposed
If the Console was disposed.
Detailed Description
Implementation of IConsole, uses global::System.Console.
Definition at line 13 of file Console.cs.
Constructor & Destructor Documentation
Console()
Tgstation.Server.Host.IO.Console.Console (IPlatformIdentifier platformIdentifier)
Initializes a new instance of the Console class.
Parameters
platformIdentifier The value of platformIdentifier.
Definition at line 45 of file Console.cs.
        {
            this.platformIdentifier = platformIdentifier ?? throw new ArgumentNullException(nameof(platformIdentifier));
            cancelKeyCts = new CancellationTokenSource();
            global::System.Console.CancelKeyPress += (sender, e) =>
            {
                lock (cancelKeyCts)
                {
                    if (!disposed)
                        cancelKeyCts.Cancel();
                }
            };
        }
References Tgstation.Server.Host.IO.Console.cancelKeyCts, Tgstation.Server.Host.IO.Console.disposed, and Tgstation.Server.Host.IO.Console.platformIdentifier.
Member Function Documentation
CheckAvailable()
void Tgstation.Server.Host.IO.Console.CheckAvailable () private
Assert that the Console is available, throwing an InvalidOperationException otherwise.
Definition at line 153 of file Console.cs.
        {
            if (!Available)
                throw new InvalidOperationException("Console unavailable");
        }
References Tgstation.Server.Host.IO.Console.Available.
Referenced by Tgstation.Server.Host.IO.Console.PressAnyKeyAsync(), Tgstation.Server.Host.IO.Console.ReadLineAsync(), and Tgstation.Server.Host.IO.Console.WriteAsync().
Dispose()
void Tgstation.Server.Host.IO.Console.Dispose ()
Definition at line 61 of file Console.cs.
        {
            lock (cancelKeyCts)
            {
                cancelKeyCts.Dispose();
                disposed = true;
            }
        }
References Tgstation.Server.Host.IO.Console.cancelKeyCts, and Tgstation.Server.Host.IO.Console.disposed.
PressAnyKeyAsync()
Task Tgstation.Server.Host.IO.Console.PressAnyKeyAsync (CancellationToken cancellationToken)
Wait for a key press on the IConsole.
Parameters
cancellationToken The CancellationToken for the operations.
Returns
A Task representing the running operation.
Implements Tgstation.Server.Host.IO.IConsole.
References Tgstation.Server.Host.IO.Console.CheckAvailable().
ReadLineAsync()
Task< string > Tgstation.Server.Host.IO.Console.ReadLineAsync (bool usePasswordChar, CancellationToken cancellationToken)
Read a line from the IConsole.
Parameters
usePasswordChar If the input should be retrieved using the '*' character.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the string read by the IConsole.
Implements Tgstation.Server.Host.IO.IConsole.
References Tgstation.Server.Host.IO.Console.CheckAvailable().
SetTitle()
void Tgstation.Server.Host.IO.Console.SetTitle (string newTitle)
Sets a newTitle console window.
Parameters
newTitle The new Title.
Implements Tgstation.Server.Host.IO.IConsole.
Definition at line 144 of file Console.cs.
        {
            ArgumentNullException.ThrowIfNull(newTitle);
            global::System.Console.Title = newTitle;
        }
WriteAsync()
Task Tgstation.Server.Host.IO.Console.WriteAsync (string? text, bool newLine, CancellationToken cancellationToken)
Write some text to the IConsole.
Parameters
text The string to write.
newLine If there should be a new line after the text .
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implements Tgstation.Server.Host.IO.IConsole.
References Tgstation.Server.Host.IO.Console.CheckAvailable().
Member Data Documentation
cancelKeyCts
readonly CancellationTokenSource Tgstation.Server.Host.IO.Console.cancelKeyCts private
The CancellationTokenSource for CancelKeyPress.
Definition at line 34 of file Console.cs.
Referenced by Tgstation.Server.Host.IO.Console.Console(), and Tgstation.Server.Host.IO.Console.Dispose().
disposed
bool Tgstation.Server.Host.IO.Console.disposed private
If the Console was disposed.
Definition at line 39 of file Console.cs.
Referenced by Tgstation.Server.Host.IO.Console.Console(), and Tgstation.Server.Host.IO.Console.Dispose().
platformIdentifier
readonly IPlatformIdentifier Tgstation.Server.Host.IO.Console.platformIdentifier private
The IPlatformIdentifier for the Console.
Definition at line 29 of file Console.cs.
Referenced by Tgstation.Server.Host.IO.Console.Console().
Property Documentation
Available
bool Tgstation.Server.Host.IO.Console.Available get
If the IConsole is visible to the user.
Implements Tgstation.Server.Host.IO.IConsole.
Definition at line 21 of file Console.cs.
Referenced by Tgstation.Server.Host.IO.Console.CheckAvailable().
CancelKeyPress
CancellationToken Tgstation.Server.Host.IO.Console.CancelKeyPress get
Gets a CancellationToken that triggers if Crtl+C or an equivalent is pressed.
Implements Tgstation.Server.Host.IO.IConsole.
Definition at line 24 of file Console.cs.
Title
string? Tgstation.Server.Host.IO.Console.Title get
Gets or sets the IConsole window's title. Can return null if getting the console title is not supported.
Implements Tgstation.Server.Host.IO.IConsole.
Definition at line 16 of file Console.cs.
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/IO/Console.cs