tgstation-server: Tgstation.Server.Host.Core.JobHandler Class Reference
Tgstation.Server.Host.Core.JobHandler Class Reference
Class for pairing Tasks with CancellationTokenSources
Public Member Functions
void Dispose ()
<inehritdoc>
async Task Wait (CancellationToken cancellationToken)
Wait for task to complete
void Cancel ()
Cancels task
Static Public Member Functions
static JobHandler Create (Func< CancellationToken, Task > job)
Create a JobHandler
Properties
int Progress [get, set]
The progress of the job
Private Member Functions
JobHandler (Task task, CancellationTokenSource cancellationTokenSource)
Construct a JobHandler
Private Attributes
readonly Task task
The Task being run
readonly CancellationTokenSource cancellationTokenSource
The CancellationTokenSource for task
Detailed Description
Class for pairing Tasks with CancellationTokenSources
Definition at line 10 of file JobHandler.cs.
Constructor & Destructor Documentation
Tgstation.Server.Host.Core.JobHandler.JobHandler (Task task, CancellationTokenSource cancellationTokenSource) private
Construct a JobHandler
Parameters
task The value of Task
cancellationTokenSource The value of cancellationTokenSource
Definition at line 26 of file JobHandler.cs.
         {
             this.task = task;
             this.cancellationTokenSource = cancellationTokenSource;
         }
Member Function Documentation
void Tgstation.Server.Host.Core.JobHandler.Cancel ()
Cancels task
Referenced by Tgstation.Server.Host.Core.JobManager.CancelJob().
static JobHandler Tgstation.Server.Host.Core.JobHandler.Create (Func< CancellationToken, Task > job) static
Create a JobHandler
Parameters
job A Func<T, TResult> taking a CancellationToken and returning a Task that the JobHandler will wrap
Returns
A new JobHandler
Definition at line 63 of file JobHandler.cs.
Referenced by Tgstation.Server.Host.Core.JobManager.RunJob().
         {
             var cts = new CancellationTokenSource();
             return new JobHandler(job(cts.Token), cts);
         }
void Tgstation.Server.Host.Core.JobHandler.Dispose ()
<inehritdoc>
async Task Tgstation.Server.Host.Core.JobHandler.Wait (CancellationToken cancellationToken)
Wait for task to complete
Parameters
cancellationToken The CancellationToken for the operation
Returns
A Task representing the running operation
Definition at line 45 of file JobHandler.cs.
Referenced by Tgstation.Server.Host.Core.JobManager.CancelJob(), and Tgstation.Server.Host.Core.JobManager.WaitForJobCompletion().
         {
             TaskCompletionSource<object> tcs = new TaskCompletionSource<object>();
             using (cancellationToken.Register(() => tcs.SetCanceled()))
                 await Task.WhenAny(tcs.Task, task).ConfigureAwait(false);
             cancellationToken.ThrowIfCancellationRequested();
         }
Member Data Documentation
readonly CancellationTokenSource Tgstation.Server.Host.Core.JobHandler.cancellationTokenSource private
The CancellationTokenSource for task
Definition at line 19 of file JobHandler.cs.
readonly Task Tgstation.Server.Host.Core.JobHandler.task private
The Task being run
Definition at line 15 of file JobHandler.cs.
Property Documentation
int Tgstation.Server.Host.Core.JobHandler.Progress get set
The progress of the job
Definition at line 38 of file JobHandler.cs.
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Core/JobHandler.cs