tgstation-server: Tgstation.Server.Host.Components.Deployment.DeploymentLockManager Class Reference
Tgstation.Server.Host.Components.Deployment.DeploymentLockManager Class Reference sealed
Manages locks on a given IDmbProvider.
Public Member Functions
ValueTask DisposeAsync ()
IDmbProvider AddLock (string reason, [CallerFilePath] string? callerFile=null, [CallerLineNumber]int callerLine=default)
Add a lock to the managed IDmbProvider.
void LogLockStats (StringBuilder stringBuilder)
Add lock stats to a given stringBuilder .
Static Public Member Functions
static DeploymentLockManager Create (IDmbProvider dmbProvider, ILogger logger, string initialLockReason, out IDmbProvider firstLock, [CallerFilePath] string? callerFile=null, [CallerLineNumber] int callerLine=default)
Create a DeploymentLockManager.
Properties
CompileJob CompileJob [get]
The Models.CompileJob represented by the DeploymentLockManager.
Private Member Functions
DeploymentLockManager (IDmbProvider dmbProvider, ILogger logger, string initialLockReason, string callerFile, int callerLine)
Initializes a new instance of the DeploymentLockManager class.
DmbLock CreateLock (string reason, string callerFile, int callerLine)
Creates a DmbLock and adds it to locks.
Static Private Member Functions
static string GetFullLockDescriptor (DmbLock dmbLock)
Generates a verbose description of a given dmbLock .
Private Attributes
readonly ILogger logger
The ILogger for the DeploymentLockManager.
readonly IDmbProvider dmbProvider
The IDmbProvider the DeploymentLockManager is managing.
readonly HashSet< DmbLock > locks
The DmbLocks on the dmbProvider.
readonly DmbLock firstLock
The first lock acquired by the DeploymentLockManager.
Detailed Description
Manages locks on a given IDmbProvider.
Definition at line 17 of file DeploymentLockManager.cs.
Constructor & Destructor Documentation
DeploymentLockManager()
Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.DeploymentLockManager (IDmbProvider dmbProvider, ILogger logger, string initialLockReason, string callerFile, int callerLine) private
Initializes a new instance of the DeploymentLockManager class.
Parameters
dmbProvider The value of dmbProvider.
logger The value of logger.
initialLockReason The reason for the first lock.
callerFile The file path of the calling function.
callerLine The line number of the call invocation.
Returns
A new DeploymentLockManager.
Definition at line 77 of file DeploymentLockManager.cs.
        {
            this.dmbProvider = dmbProvider ?? throw new ArgumentNullException(nameof(dmbProvider));
            this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
            logger.LogTrace("Initializing lock manager for compile job {id}", dmbProvider.CompileJob.Id);
            locks = new HashSet<DmbLock>();
            firstLock = CreateLock(initialLockReason, callerFile, callerLine);
        }
References Tgstation.Server.Host.Components.Deployment.IDmbProvider.CompileJob, Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.CreateLock(), Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.dmbProvider, Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.firstLock, Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.locks, and Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.logger.
Member Function Documentation
AddLock()
IDmbProvider Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.AddLock (string reason, [CallerFilePath] string? callerFile = null, [CallerLineNumber] int callerLine = default)
Add a lock to the managed IDmbProvider.
Parameters
reason The reason for the lock.
callerFile The file path of the calling function.
callerLine The line number of the call invocation.
Returns
A IDmbProvider whose lifetime represents the lock.
Definition at line 98 of file DeploymentLockManager.cs.
        {
            ArgumentNullException.ThrowIfNull(reason);
            lock (locks)
            {
                if (locks.Count == 0)
                    throw new InvalidOperationException($"No locks exist on the DmbProvider for CompileJob {dmbProvider.CompileJob.Id}!");
                return CreateLock(reason, callerFile!, callerLine);
            }
        }
References Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.CreateLock(), and Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.locks.
Referenced by Tgstation.Server.Host.Components.Deployment.DmbFactory.LockNextDmb().
Create()
static DeploymentLockManager Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.Create (IDmbProvider dmbProvider, ILogger logger, string initialLockReason, out IDmbProvider firstLock, [CallerFilePath] string? callerFile = null, [CallerLineNumber] int callerLine = default) static
Create a DeploymentLockManager.
Parameters
dmbProvider The value of dmbProvider.
logger The value of logger.
initialLockReason The reason for the first lock.
firstLock The IDmbProvider that represents the first lock.
callerFile The file path of the calling function.
callerLine The line number of the call invocation.
Returns
A new DeploymentLockManager.
Definition at line 54 of file DeploymentLockManager.cs.
        {
            var manager = new DeploymentLockManager(dmbProvider, logger, initialLockReason, callerFile!, callerLine);
            firstLock = manager.firstLock;
            return manager;
        }
References Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.dmbProvider, Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.firstLock, and Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.logger.
Referenced by Tgstation.Server.Host.Components.Deployment.DmbFactory.FromCompileJobInternal().
CreateLock()
DmbLock Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.CreateLock (string reason, string callerFile, int callerLine) private
Creates a DmbLock and adds it to locks.
Parameters
reason The reason for the lock.
callerFile The file path of the calling function.
callerLine The line number of the call invocation.
Returns
A new DmbLock.
Requires exclusive write access to locks be held by the caller.
Definition at line 132 of file DeploymentLockManager.cs.
        {
            DmbLock? newLock = null;
            string? descriptor = null;
            ValueTask LockCleanupAction()
            {
                ValueTask disposeTask = ValueTask.CompletedTask;
                lock (locks)
                {
                    logger.LogTrace("Removing .dmb Lock: {descriptor}", descriptor);
                    if (locks.Remove(newLock!))
                        logger.LogTrace("Lock was removed from list successfully");
                    else
                        logger.LogError("A .dmb lock was disposed more than once: {descriptor}", descriptor);
                    if (locks.Count == 0)
                        disposeTask = dmbProvider.DisposeAsync();
                    else if (newLock == firstLock)
                        logger.LogDebug("First lock on CompileJob #{compileJobId} removed, it must cleanup {remaining} remaining locks to be cleaned", CompileJob.Id, locks.Count);
                }
                return disposeTask;
            }
            newLock = new DmbLock(LockCleanupAction, dmbProvider, $"{callerFile}#{callerLine}: {reason}");
            locks.Add(newLock);
            descriptor = GetFullLockDescriptor(newLock!);
            logger.LogTrace("Created .dmb Lock: {descriptor}", descriptor);
            return newLock;
        }
References Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.dmbProvider, Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.firstLock, Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.GetFullLockDescriptor(), Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.locks, and Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.logger.
Referenced by Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.AddLock(), and Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.DeploymentLockManager().
DisposeAsync()
ValueTask Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.DisposeAsync ()
Referenced by Tgstation.Server.Host.Components.Deployment.DmbFactory.LoadCompileJob().
GetFullLockDescriptor()
static string Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.GetFullLockDescriptor (DmbLock dmbLock) static private
Generates a verbose description of a given dmbLock .
Parameters
dmbLock The DmbLock to get a description of.
Returns
A verbose description of dmbLock .
Referenced by Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.CreateLock().
LogLockStats()
void Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.LogLockStats (StringBuilder stringBuilder)
Add lock stats to a given stringBuilder .
Parameters
stringBuilder The StringBuilder to append to.
Definition at line 114 of file DeploymentLockManager.cs.
        {
            ArgumentNullException.ThrowIfNull(stringBuilder);
            stringBuilder.AppendLine(CultureInfo.InvariantCulture, $"Compile Job #{CompileJob.Id}: {CompileJob.DirectoryName}");
            lock (locks)
                foreach (var dmbLock in locks)
                    stringBuilder.AppendLine(CultureInfo.InvariantCulture, $"\t-{GetFullLockDescriptor(dmbLock)}");
        }
References Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.locks.
Member Data Documentation
dmbProvider
readonly IDmbProvider Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.dmbProvider private
The IDmbProvider the DeploymentLockManager is managing.
Definition at line 32 of file DeploymentLockManager.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.Create(), Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.CreateLock(), and Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.DeploymentLockManager().
firstLock
readonly DmbLock Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.firstLock private
The first lock acquired by the DeploymentLockManager.
Definition at line 42 of file DeploymentLockManager.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.Create(), Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.CreateLock(), and Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.DeploymentLockManager().
locks
readonly HashSet<DmbLock> Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.locks private
The DmbLocks on the dmbProvider.
Definition at line 37 of file DeploymentLockManager.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.AddLock(), Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.CreateLock(), Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.DeploymentLockManager(), and Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.LogLockStats().
logger
readonly ILogger Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.logger private
The ILogger for the DeploymentLockManager.
Definition at line 27 of file DeploymentLockManager.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.Create(), Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.CreateLock(), and Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.DeploymentLockManager().
Property Documentation
CompileJob
CompileJob Tgstation.Server.Host.Components.Deployment.DeploymentLockManager.CompileJob get
The Models.CompileJob represented by the DeploymentLockManager.
Definition at line 22 of file DeploymentLockManager.cs.
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Deployment/DeploymentLockManager.cs