tgstation-server: Tgstation.Server.Host.Jobs.JobManager Class Reference
Tgstation.Server.Host.Jobs.JobManager Class Reference
Public Member Functions
JobManager (IDatabaseContextFactory databaseContextFactory, ILogger< JobManager > logger)
Construct a JobManager
void Dispose ()
Task RegisterOperation (Job job, Func< Job, IDatabaseContextFactory, Action< int >, CancellationToken, Task > operation, CancellationToken cancellationToken)
Registers a given Job and begins running it
async Task StartAsync (CancellationToken cancellationToken)
async Task StopAsync (CancellationToken cancellationToken)
async Task< Job > CancelJob (Job job, User user, bool blocking, CancellationToken cancellationToken)
Cancels a give job
int JobProgress (Job job)
Get the Api.Models.Job.Progress for a job
async Task WaitForJobCompletion (Job job, User canceller, CancellationToken jobCancellationToken, CancellationToken cancellationToken)
Wait for a given job to complete
Private Member Functions
JobHandler CheckGetJob (Job job)
Gets the JobHandler for a given job if it exists
async Task RunJob (Job job, Func< Job, IDatabaseContextFactory, CancellationToken, Task > operation, CancellationToken cancellationToken)
Runner for JobHandlers
Private Attributes
readonly IDatabaseContextFactory databaseContextFactory
The IServiceProvider for the JobManager
readonly ILogger< JobManager > logger
The ILogger for the JobManager
readonly Dictionary< long, JobHandler > jobs
Dictionary<TKey, TValue> of Job Api.Models.EntityId.Ids to running JobHandlers
readonly object synchronizationLock
object for various operations.
Detailed Description
Definition at line 14 of file JobManager.cs.
Constructor & Destructor Documentation
Tgstation.Server.Host.Jobs.JobManager.JobManager (IDatabaseContextFactory databaseContextFactory, ILogger< JobManager > logger)
Construct a JobManager
Parameters
databaseContextFactory The value of databaseContextFactory
logger The value of logger
Definition at line 41 of file JobManager.cs.
         {
             this.databaseContextFactory = databaseContextFactory ?? throw new ArgumentNullException(nameof(databaseContextFactory));
             this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
             jobs = new Dictionary<long, JobHandler>();
             synchronizationLock = new object();
         }
Member Function Documentation
async Task<Job> Tgstation.Server.Host.Jobs.JobManager.CancelJob (Job job, User user, bool blocking, CancellationToken cancellationToken)
Cancels a give job
Implements Tgstation.Server.Host.Jobs.IJobManager.
Definition at line 219 of file JobManager.cs.
References Tgstation.Server.Host.Jobs.JobHandler.Cancel(), Tgstation.Server.Host.Models.Job.CancelledBy, Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Api.Models.Internal.User.Id, and Tgstation.Server.Host.Jobs.JobHandler.Wait().
         {
             if (job == null)
                 throw new ArgumentNullException(nameof(job));
             if (user == null)
                 throw new ArgumentNullException(nameof(user));
             JobHandler handler;
             try
             {
                 handler = CheckGetJob(job);
             }
             catch (InvalidOperationException)
             {
                 // this is fine
                 return null;
             }
             handler.Cancel(); // this will ensure the db update is only done once
             await databaseContextFactory.UseContext(async databaseContext =>
             {
                 var updatedJob = new Job { Id = job.Id };
                 databaseContext.Jobs.Attach(job);
                 var attachedUser = new User { Id = user.Id };
                 databaseContext.Users.Attach(user);
                 updatedJob.CancelledBy = attachedUser;
                 // let either startup or cancellation set job.cancelled
                 await databaseContext.Save(cancellationToken).ConfigureAwait(false);
                 job.CancelledBy = user;
             }).ConfigureAwait(false);
             if (blocking)
                 await handler.Wait(cancellationToken).ConfigureAwait(false);
             return job;
         }
JobHandler Tgstation.Server.Host.Jobs.JobManager.CheckGetJob (Job job) private
Gets the JobHandler for a given job if it exists
Parameters
job The Job to get the JobHandler for
Returns
The JobHandler
Definition at line 61 of file JobManager.cs.
References Tgstation.Server.Api.Models.EntityId.Id.
         {
             lock (synchronizationLock)
             {
                 if (!jobs.TryGetValue(job.Id, out JobHandler jobHandler))
                     throw new InvalidOperationException("Job not running!");
                 return jobHandler;
             }
         }
void Tgstation.Server.Host.Jobs.JobManager.Dispose ()
Definition at line 50 of file JobManager.cs.
         {
             foreach (var job in jobs)
                 job.Value.Dispose();
         }
int Tgstation.Server.Host.Jobs.JobManager.JobProgress (Job job)
Get the Api.Models.Job.Progress for a job
Implements Tgstation.Server.Host.Jobs.IJobManager.
Definition at line 255 of file JobManager.cs.
References Tgstation.Server.Api.Models.EntityId.Id.
         {
             if (job == null)
                 throw new ArgumentNullException(nameof(job));
             lock (synchronizationLock)
             {
                 if (!jobs.TryGetValue(job.Id, out var handler))
                     return null;
                 return handler.Progress;
             }
         }
Task Tgstation.Server.Host.Jobs.JobManager.RegisterOperation (Job job, Func< Job, IDatabaseContextFactory, Action< int >, CancellationToken, Task > operation, CancellationToken cancellationToken)
Registers a given Job and begins running it
Implements Tgstation.Server.Host.Jobs.IJobManager.
async Task Tgstation.Server.Host.Jobs.JobManager.RunJob (Job job, Func< Job, IDatabaseContextFactory, CancellationToken, Task > operation, CancellationToken cancellationToken) private
Runner for JobHandlers
Parameters
job The Job being run
operation The operation for the job
cancellationToken The CancellationToken for the operation
Returns
A Task representing the running operation
Definition at line 78 of file JobManager.cs.
References Tgstation.Server.Api.Models.Internal.Job.Cancelled, Tgstation.Server.Api.Models.Internal.Job.Description, Tgstation.Server.Host.Jobs.JobException.ErrorCode, Tgstation.Server.Api.Models.Internal.Job.ErrorCode, Tgstation.Server.Api.Models.Internal.Job.ExceptionDetails, Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Api.Models.Instance.Id, Tgstation.Server.Api.Models.Internal.User.Id, Tgstation.Server.Host.Models.Job.Instance, Tgstation.Server.Api.Models.Internal.Job.StartedAt, and Tgstation.Server.Host.Models.Job.StartedBy.
         {
             try
             {
                 void LogRegularException() => logger.LogDebug("Job {0} exited with error! Exception: {1}", job.Id, job.ExceptionDetails);
                 try
                 {
                     var oldJob = job;
                     job = new Job { Id = oldJob.Id };
                     await operation(job, databaseContextFactory, cancellationToken).ConfigureAwait(false);
                     logger.LogDebug("Job {0} completed!", job.Id);
                 }
                 catch (OperationCanceledException)
                 {
                     logger.LogDebug("Job {0} cancelled!", job.Id);
                     job.Cancelled = true;
                 }
                 catch (JobException e)
                 {
                     job.ErrorCode = e.ErrorCode;
                     job.ExceptionDetails = e.Message;
                     LogRegularException();
                     if (e.InnerException != null)
                         logger.LogDebug(
                             "Inner exception for job {0}: {1}",
                             job.Id,
                             e.InnerException is JobException
                                 ? e.InnerException.Message
                                 : e.InnerException.ToString());
                 }
                 catch (Exception e)
                 {
                     job.ExceptionDetails = e.ToString();
                     LogRegularException();
                 }
                 await databaseContextFactory.UseContext(async databaseContext =>
                 {
                     var attachedJob = new Job
                     {
                         Id = job.Id
                     };
                     databaseContext.Jobs.Attach(attachedJob);
                     attachedJob.StoppedAt = DateTimeOffset.Now;
                     attachedJob.ExceptionDetails = job.ExceptionDetails;
                     attachedJob.ErrorCode = job.ErrorCode;
                     attachedJob.Cancelled = job.Cancelled;
                     await databaseContext.Save(default).ConfigureAwait(false);
                 }).ConfigureAwait(false);
             }
             finally
             {
                 lock (synchronizationLock)
                 {
                     var handler = jobs[job.Id];
                     jobs.Remove(job.Id);
                     handler.Dispose();
                 }
             }
         }
async Task Tgstation.Server.Host.Jobs.JobManager.StartAsync (CancellationToken cancellationToken)
Definition at line 183 of file JobManager.cs.
References Tgstation.Server.Api.Models.Internal.Job.Cancelled.
         {
             logger.LogTrace("Starting job manager...");
             await databaseContextFactory.UseContext(async databaseContext =>
             {
                 // mark all jobs as cancelled
                 var badJobs = await databaseContext.Jobs.Where(y => !y.StoppedAt.HasValue).Select(y => y.Id).ToListAsync(cancellationToken).ConfigureAwait(false);
                 if (badJobs.Count > 0)
                 {
                     logger.LogTrace("Cleaning {0} unfinished jobs...", badJobs.Count);
                     foreach (var I in badJobs)
                     {
                         var job = new Job { Id = I };
                         databaseContext.Jobs.Attach(job);
                         job.Cancelled = true;
                         job.StoppedAt = DateTimeOffset.Now;
                     }
                     await databaseContext.Save(cancellationToken).ConfigureAwait(false);
                 }
             }).ConfigureAwait(false);
             logger.LogDebug("Job manager started!");
         }
async Task Tgstation.Server.Host.Jobs.JobManager.StopAsync (CancellationToken cancellationToken)
Definition at line 208 of file JobManager.cs.
         {
             var joinTasks = jobs.Select(x =>
             {
                 x.Value.Cancel();
                 return x.Value.Wait(cancellationToken);
             });
             await Task.WhenAll(joinTasks).ConfigureAwait(false);
         }
async Task Tgstation.Server.Host.Jobs.JobManager.WaitForJobCompletion (Job job, User canceller, CancellationToken jobCancellationToken, CancellationToken cancellationToken)
Wait for a given job to complete
Implements Tgstation.Server.Host.Jobs.IJobManager.
Definition at line 268 of file JobManager.cs.
References Tgstation.Server.Api.Models.EntityId.Id, and Tgstation.Server.Host.Jobs.JobHandler.Wait().
         {
             if (job == null)
                 throw new ArgumentNullException(nameof(job));
             if (canceller == null)
                 throw new ArgumentNullException(nameof(canceller));
             JobHandler handler;
             lock (synchronizationLock)
             {
                 if (!jobs.TryGetValue(job.Id, out handler))
                     return;
             }
             Task cancelTask = null;
             using (jobCancellationToken.Register(() => cancelTask = CancelJob(job, canceller, true, cancellationToken)))
                 await handler.Wait(cancellationToken).ConfigureAwait(false);
             if (cancelTask != null)
                 await cancelTask.ConfigureAwait(false);
         }
Member Data Documentation
readonly IDatabaseContextFactory Tgstation.Server.Host.Jobs.JobManager.databaseContextFactory private
The IServiceProvider for the JobManager
Definition at line 19 of file JobManager.cs.
readonly Dictionary<long, JobHandler> Tgstation.Server.Host.Jobs.JobManager.jobs private
Dictionary<TKey, TValue> of Job Api.Models.EntityId.Ids to running JobHandlers
Definition at line 29 of file JobManager.cs.
readonly ILogger<JobManager> Tgstation.Server.Host.Jobs.JobManager.logger private
The ILogger for the JobManager
Definition at line 24 of file JobManager.cs.
readonly object Tgstation.Server.Host.Jobs.JobManager.synchronizationLock private
object for various operations.
Definition at line 34 of file JobManager.cs.
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Jobs/JobManager.cs