tgstation-server: Tgstation.Server.Host.Components.Engine.OpenDreamInstaller Class Reference
Tgstation.Server.Host.Components.Engine.OpenDreamInstaller Class Reference
Implementation of IEngineInstaller for EngineType.OpenDream.
Public Member Functions
OpenDreamInstaller (IIOManager ioManager, ILogger< OpenDreamInstaller > logger, IPlatformIdentifier platformIdentifier, IProcessExecutor processExecutor, IRepositoryManager repositoryManager, IAsyncDelayer asyncDelayer, IHttpClientFactory httpClientFactory, IOptionsMonitor< GeneralConfiguration > generalConfigurationOptions, IOptionsMonitor< SessionConfiguration > sessionConfigurationOptions)
Initializes a new instance of the OpenDreamInstaller class.
override Task CleanCache (CancellationToken cancellationToken)
Attempts to cleans the engine's cache folder for the system.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
override async ValueTask< IEngineInstallation > GetInstallation (EngineVersion version, string path, Task installationTask, CancellationToken cancellationToken)
Creates an IEngineInstallation for a given version .
Parameters
version The EngineVersion of the installation.
path The path to the installation.
installationTask The Task representing the installation process for the installation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a new IEngineInstallation for the given version .
override async ValueTask< IEngineInstallationData > DownloadVersion (EngineVersion version, JobProgressReporter jobProgressReporter, CancellationToken cancellationToken)
Download a given engine version .
Parameters
version The EngineVersion of the engine to download.
jobProgressReporter The JobProgressReporter for the operation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IEngineInstallationData for the download.
override ValueTask UpgradeInstallation (EngineVersion version, string path, CancellationToken cancellationToken)
Does actions necessary to get upgrade a version installed by a previous version of TGS.
Parameters
version The EngineVersion being installed.
path The path to the installation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
override ValueTask TrustDmbPath (EngineVersion engineVersion, string fullDmbPath, CancellationToken cancellationToken)
Add a given fullDmbPath to the trusted DMBs list in BYOND's config.
Parameters
version The EngineVersion being used.
fullDmbPath Full path to the .dmb that should be trusted.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Public Member Functions inherited from Tgstation.Server.Host.Components.Engine.EngineInstallerBase
ValueTask< IEngineInstallation > GetInstallation (EngineVersion version, string path, Task installationTask, CancellationToken cancellationToken)
Creates an IEngineInstallation for a given version .
Parameters
version The EngineVersion of the installation.
path The path to the installation.
installationTask The Task representing the installation process for the installation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a new IEngineInstallation for the given version .
Task CleanCache (CancellationToken cancellationToken)
Attempts to cleans the engine's cache folder for the system.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
async ValueTask< IEngineInstallation > Install (EngineVersion version, string path, bool deploymentPipelineProcesses, CancellationToken cancellationToken)
Does actions necessary to get an extracted installation working.
Parameters
version The EngineVersion being installed.
path The path to the installation.
deploymentPipelineProcesses If the operation should consider processes it launches to be part of the deployment pipeline.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the new IEngineInstallation.
ValueTask UpgradeInstallation (EngineVersion version, string path, CancellationToken cancellationToken)
Does actions necessary to get upgrade a version installed by a previous version of TGS.
Parameters
version The EngineVersion being installed.
path The path to the installation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
ValueTask< IEngineInstallationData > DownloadVersion (EngineVersion version, JobProgressReporter jobProgressReporter, CancellationToken cancellationToken)
Download a given engine version .
Parameters
version The EngineVersion of the engine to download.
jobProgressReporter The JobProgressReporter for the operation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IEngineInstallationData for the download.
ValueTask TrustDmbPath (EngineVersion version, string fullDmbPath, CancellationToken cancellationToken)
Add a given fullDmbPath to the trusted DMBs list in BYOND's config.
Parameters
version The EngineVersion being used.
fullDmbPath Full path to the .dmb that should be trusted.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Protected Member Functions
override async ValueTask InstallImpl (EngineVersion version, string installPath, bool deploymentPipelineProcesses, CancellationToken cancellationToken)
virtual ValueTask HandleExtremelyLongPathOperation (Func< string, ValueTask > shortenedPathOperation, string originalPath, CancellationToken cancellationToken)
Perform an operation on a very long path.
void GetExecutablePaths (string installationPath, out string serverExePath, out string compilerExePath)
Gets the paths to the server and client executables.
Protected Member Functions inherited from Tgstation.Server.Host.Components.Engine.EngineInstallerBase
EngineInstallerBase (IIOManager ioManager, ILogger< EngineInstallerBase > logger)
Initializes a new instance of the EngineInstallerBase class.
void CheckVersionValidity (EngineVersion version)
Check that a given version is of type EngineType.Byond.
ValueTask InstallImpl (EngineVersion version, string path, bool deploymentPipelineProcesses, CancellationToken cancellationToken)
Does actions necessary to get an extracted installation working.
Properties
override EngineType TargetEngineType [get]
IProcessExecutor ProcessExecutor [get]
The IProcessExecutor for the OpenDreamInstaller.
IOptionsMonitor< GeneralConfiguration > GeneralConfigurationOptions [get]
The GeneralConfigurationOptions for the OpenDreamInstaller.
IOptionsMonitor< SessionConfiguration > SessionConfigurationOptions [get]
The Configuration.SessionConfiguration for the OpenDreamInstaller.
Properties inherited from Tgstation.Server.Host.Components.Engine.EngineInstallerBase
EngineType TargetEngineType [get]
The EngineType the installer supports.
IIOManager IOManager [get]
Gets the IIOManager for the EngineInstallerBase.
ILogger< EngineInstallerBase > Logger [get]
Gets the ILogger for the EngineInstallerBase.
Private Attributes
readonly IPlatformIdentifier platformIdentifier
The IPlatformIdentifier for the OpenDreamInstaller.
readonly IRepositoryManager repositoryManager
The IRepositoryManager for the OpenDream repository.
readonly IAsyncDelayer asyncDelayer
The IAsyncDelayer for the OpenDreamInstaller.
readonly IHttpClientFactory httpClientFactory
The IHttpClientFactory for the OpenDreamInstaller.
Static Private Attributes
const string BinDir = "bin"
The bin directory name.
const string ServerDir = "server"
The OD server directory name.
const string InstallationCompilerDirectory = "compiler"
The name of the subdirectory in an installation's BinDir used to store the compiler binaries.
const string InstallationSourceSubDirectory = "TgsSourceSubdir"
The name of the subdirectory used for the RepositoryEngineInstallationData's copy.
Detailed Description
Implementation of IEngineInstaller for EngineType.OpenDream.
Definition at line 24 of file OpenDreamInstaller.cs.
Constructor & Destructor Documentation
OpenDreamInstaller()
Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.OpenDreamInstaller (IIOManager ioManager, ILogger< OpenDreamInstaller > logger, IPlatformIdentifier platformIdentifier, IProcessExecutor processExecutor, IRepositoryManager repositoryManager, IAsyncDelayer asyncDelayer, IHttpClientFactory httpClientFactory, IOptionsMonitor< GeneralConfiguration > generalConfigurationOptions, IOptionsMonitor< SessionConfiguration > sessionConfigurationOptions)
Initializes a new instance of the OpenDreamInstaller class.
Parameters
ioManager The IIOManager for the EngineInstallerBase.
logger The ILogger for the EngineInstallerBase.
platformIdentifier The value of platformIdentifier.
processExecutor The value of ProcessExecutor.
repositoryManager The value of repositoryManager.
asyncDelayer The value of asyncDelayer.
httpClientFactory The value of httpClientFactory.
generalConfigurationOptions The value of GeneralConfigurationOptions.
sessionConfigurationOptions The value of SessionConfigurationOptions.
Definition at line 96 of file OpenDreamInstaller.cs.
            : base(ioManager, logger)
        {
            this.platformIdentifier = platformIdentifier ?? throw new ArgumentNullException(nameof(platformIdentifier));
            ProcessExecutor = processExecutor ?? throw new ArgumentNullException(nameof(processExecutor));
            this.repositoryManager = repositoryManager ?? throw new ArgumentNullException(nameof(repositoryManager));
            this.asyncDelayer = asyncDelayer ?? throw new ArgumentNullException(nameof(asyncDelayer));
            this.httpClientFactory = httpClientFactory ?? throw new ArgumentNullException(nameof(httpClientFactory));
            GeneralConfigurationOptions = generalConfigurationOptions ?? throw new ArgumentNullException(nameof(generalConfigurationOptions));
            SessionConfigurationOptions = sessionConfigurationOptions ?? throw new ArgumentNullException(nameof(sessionConfigurationOptions));
        }
References Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.asyncDelayer, Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.GeneralConfigurationOptions, Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.httpClientFactory, Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.platformIdentifier, Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.repositoryManager, and Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.SessionConfigurationOptions.
Member Function Documentation
CleanCache()
override Task Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.CleanCache (CancellationToken cancellationToken) sealed
Attempts to cleans the engine's cache folder for the system.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implements Tgstation.Server.Host.Components.Engine.IEngineInstaller.
DownloadVersion()
override async ValueTask< IEngineInstallationData > Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.DownloadVersion (EngineVersion version, JobProgressReporter jobProgressReporter, CancellationToken cancellationToken) sealed
Download a given engine version .
Parameters
version The EngineVersion of the engine to download.
jobProgressReporter The JobProgressReporter for the operation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IEngineInstallationData for the download.
Implements Tgstation.Server.Host.Components.Engine.IEngineInstaller.
Definition at line 140 of file OpenDreamInstaller.cs.
        {
            CheckVersionValidity(version);
            ArgumentNullException.ThrowIfNull(jobProgressReporter);
            // get a lock on a system wide OD repo
            Logger.LogTrace("Cloning OD repo...");
            var progressSection1 = jobProgressReporter.CreateSection("Updating OpenDream git repository", 0.5f);
            IRepository? repo;
            var generalConfig = GeneralConfigurationOptions.CurrentValue;
            try
            {
                repo = await repositoryManager.CloneRepository(
                    generalConfig.OpenDreamGitUrl,
                    null,
                    null,
                    null,
                    progressSection1,
                    true,
                    cancellationToken);
            }
            catch
            {
                progressSection1.Dispose();
                throw;
            }
            try
            {
                if (repo == null)
                {
                    Logger.LogTrace("OD repo seems to already exist, attempting load and fetch...");
                    repo = await repositoryManager.LoadRepository(cancellationToken);
                    if (repo == null)
                        throw new JobException("Can't load OpenDream repository! Please delete cache from disk!");
                    await repo!.FetchOrigin(
                        progressSection1,
                        null,
                        null,
                        false,
                        cancellationToken);
                }
                progressSection1.Dispose();
                progressSection1 = null;
                using (var progressSection2 = jobProgressReporter.CreateSection("Checking out OpenDream version", 0.5f))
                {
                    var committish = version.SourceSHA
                        ?? $"{generalConfig.OpenDreamGitTagPrefix}{version.Version!.Semver()}";
                    await repo.CheckoutObject(
                        committish,
                        null,
                        null,
                        true,
                        false,
                        progressSection2,
                        cancellationToken);
                }
                if (!await repo.CommittishIsParent("tgs-min-compat", cancellationToken))
                    throw new JobException(ErrorCode.OpenDreamTooOld);
                return new RepositoryEngineInstallationData(IOManager, repo, InstallationSourceSubDirectory);
            }
            catch
            {
                repo?.Dispose();
                throw;
            }
            finally
            {
                progressSection1?.Dispose();
            }
        }
References Tgstation.Server.Host.Components.Repository.IRepository.CheckoutObject(), Tgstation.Server.Host.Components.Engine.EngineInstallerBase.CheckVersionValidity(), Tgstation.Server.Host.Components.Repository.IRepositoryManager.CloneRepository(), Tgstation.Server.Host.Components.Repository.IRepository.CommittishIsParent(), Tgstation.Server.Host.Jobs.JobProgressReporter.CreateSection(), Tgstation.Server.Host.Components.Repository.IRepository.FetchOrigin(), Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.GeneralConfigurationOptions, Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.InstallationSourceSubDirectory, Tgstation.Server.Host.Components.Engine.EngineInstallerBase.IOManager, Tgstation.Server.Host.Components.Repository.IRepositoryManager.LoadRepository(), Tgstation.Server.Host.Components.Engine.EngineInstallerBase.Logger, and Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.repositoryManager.
GetExecutablePaths()
void Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.GetExecutablePaths (string installationPath, out string serverExePath, out string compilerExePath) protected
Gets the paths to the server and client executables.
Parameters
installationPath The path to the OpenDream installation.
serverExePath The path to the OpenDreamServer executable.
compilerExePath The path to the DMCompiler executable.
Definition at line 375 of file OpenDreamInstaller.cs.
        {
            const string DllExtension = ".dll";
            serverExePath = IOManager.ConcatPath(
                installationPath,
                BinDir,
                ServerDir,
                $"Robust.Server{DllExtension}");
            compilerExePath = IOManager.ConcatPath(
                installationPath,
                BinDir,
                InstallationCompilerDirectory,
                $"DMCompiler{DllExtension}");
        }
References Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.BinDir, Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.InstallationCompilerDirectory, Tgstation.Server.Host.Components.Engine.EngineInstallerBase.IOManager, and Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.ServerDir.
Referenced by Tgstation.Server.Host.Components.Engine.WindowsOpenDreamInstaller.AddServerFirewallException(), and Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.GetInstallation().
GetInstallation()
override async ValueTask< IEngineInstallation > Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.GetInstallation (EngineVersion version, string path, Task installationTask, CancellationToken cancellationToken) sealed
Creates an IEngineInstallation for a given version .
Parameters
version The EngineVersion of the installation.
path The path to the installation.
installationTask The Task representing the installation process for the installation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a new IEngineInstallation for the given version .
Implements Tgstation.Server.Host.Components.Engine.IEngineInstaller.
Definition at line 121 of file OpenDreamInstaller.cs.
        {
            CheckVersionValidity(version);
            GetExecutablePaths(path, out var serverExePath, out var compilerExePath);
            var dotnetPath = (await DotnetHelper.GetDotnetPath(platformIdentifier, IOManager, cancellationToken))
                ?? throw new JobException("Failed to find dotnet path!");
            return new OpenDreamInstallation(
                IOManager.CreateResolverForSubdirectory(path),
                asyncDelayer,
                httpClientFactory,
                dotnetPath,
                serverExePath,
                compilerExePath,
                installationTask,
                version);
        }
References Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.asyncDelayer, Tgstation.Server.Host.Components.Engine.EngineInstallerBase.CheckVersionValidity(), Tgstation.Server.Host.IO.IIOManager.CreateResolverForSubdirectory(), Tgstation.Server.Host.System.DotnetHelper.GetDotnetPath(), Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.GetExecutablePaths(), Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.httpClientFactory, Tgstation.Server.Host.Components.Engine.EngineInstallerBase.IOManager, and Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.platformIdentifier.
HandleExtremelyLongPathOperation()
virtual ValueTask Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.HandleExtremelyLongPathOperation (Func< string, ValueTask > shortenedPathOperation, string originalPath, CancellationToken cancellationToken) protected virtual
Perform an operation on a very long path.
Parameters
shortenedPathOperation A Func<T, TResult> taking a shortened path and resulting in a ValueTask representing the running operation.
originalPath The original path to the directory.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Reimplemented in Tgstation.Server.Host.Components.Engine.WindowsOpenDreamInstaller.
Referenced by Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.InstallImpl().
InstallImpl()
override async ValueTask Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.InstallImpl (EngineVersion version, string installPath, bool deploymentPipelineProcesses, CancellationToken cancellationToken) protected
Definition at line 238 of file OpenDreamInstaller.cs.
        {
            var sourcePath = IOManager.ConcatPath(installPath, InstallationSourceSubDirectory);
            if (!await IOManager.DirectoryExists(sourcePath, cancellationToken))
            {
                // a zip install that didn't come from us?
                // we want to use the bin dir, so put everything where we expect
                Logger.LogDebug("Correcting extraction location...");
                var dirsTask = IOManager.GetDirectories(installPath, cancellationToken);
                var filesTask = IOManager.GetFiles(installPath, cancellationToken);
                var dirCreateTask = IOManager.CreateDirectory(sourcePath, cancellationToken);
                await Task.WhenAll(dirsTask, filesTask, dirCreateTask);
                var dirsMoveTasks = dirsTask
                    .Result
                    .Select(
                        dirPath => IOManager.MoveDirectory(
                            dirPath,
                            IOManager.ConcatPath(
                                sourcePath,
                                IOManager.GetFileName(dirPath)),
                            cancellationToken));
                var filesMoveTask = filesTask
                    .Result
                    .Select(
                        filePath => IOManager.MoveFile(
                            filePath,
                            IOManager.ConcatPath(
                                sourcePath,
                                IOManager.GetFileName(filePath)),
                            cancellationToken));
                await Task.WhenAll(dirsMoveTasks.Concat(filesMoveTask));
            }
            var dotnetPath = (await DotnetHelper.GetDotnetPath(platformIdentifier, IOManager, cancellationToken))
                ?? throw new JobException(ErrorCode.OpenDreamCantFindDotnet);
            const string DeployDir = "tgs_deploy";
            int? buildExitCode = null;
            await HandleExtremelyLongPathOperation(
                async shortenedPath =>
                {
                    var shortenedDeployPath = IOManager.ConcatPath(shortenedPath, DeployDir);
                    var generalConfig = GeneralConfigurationOptions.CurrentValue;
                    await using var buildProcess = await ProcessExecutor.LaunchProcess(
                        dotnetPath,
                        shortenedPath,
                        $"run -c Release --project OpenDreamPackageTool -- --tgs -o {shortenedDeployPath}",
                        cancellationToken,
                        null,
                        null,
                        !generalConfig.OpenDreamSuppressInstallOutput,
                        !generalConfig.OpenDreamSuppressInstallOutput);
                    if (deploymentPipelineProcesses && SessionConfigurationOptions.CurrentValue.LowPriorityDeploymentProcesses)
                        buildProcess.AdjustPriority(false);
                    using (cancellationToken.Register(() => buildProcess.Terminate()))
                        buildExitCode = await buildProcess.Lifetime;
                    string? output;
                    if (!GeneralConfigurationOptions.CurrentValue.OpenDreamSuppressInstallOutput)
                    {
                        var buildOutputTask = buildProcess.GetCombinedOutput(cancellationToken);
                        if (!buildOutputTask.IsCompleted)
                            Logger.LogTrace("OD build complete, waiting for output...");
                        output = await buildOutputTask;
                    }
                    else
                        output = "<Build output suppressed by configuration due to not being immediately available>";
                    Logger.LogDebug(
                        "OpenDream build exited with code {exitCode}:{newLine}{output}",
                        buildExitCode,
                        Environment.NewLine,
                        output);
                },
                sourcePath,
                cancellationToken);
            if (buildExitCode != 0)
                throw new JobException("OpenDream build failed!");
            var deployPath = IOManager.ConcatPath(sourcePath, DeployDir);
            async ValueTask MoveDirs()
            {
                var dirs = await IOManager.GetDirectories(deployPath, cancellationToken);
                await Task.WhenAll(
                    dirs.Select(
                        dir => IOManager.MoveDirectory(
                            dir,
                            IOManager.ConcatPath(
                                installPath,
                                IOManager.GetFileName(dir)),
                            cancellationToken)));
            }
            async ValueTask MoveFiles()
            {
                var files = await IOManager.GetFiles(deployPath, cancellationToken);
                await Task.WhenAll(
                    files.Select(
                        file => IOManager.MoveFile(
                            file,
                            IOManager.ConcatPath(
                                installPath,
                                IOManager.GetFileName(file)),
                            cancellationToken)));
            }
            var dirsMoveTask = MoveDirs();
            var outputFilesMoveTask = MoveFiles();
            await ValueTaskExtensions.WhenAll(dirsMoveTask, outputFilesMoveTask);
            await IOManager.DeleteDirectory(sourcePath, cancellationToken);
        }
References Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.IO.IIOManager.CreateDirectory(), Tgstation.Server.Host.IO.IIOManager.DeleteDirectory(), Tgstation.Server.Host.IO.IIOManager.DirectoryExists(), Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.GeneralConfigurationOptions, Tgstation.Server.Host.IO.IIOManager.GetDirectories(), Tgstation.Server.Host.System.DotnetHelper.GetDotnetPath(), Tgstation.Server.Host.IO.IIOManager.GetFileName(), Tgstation.Server.Host.IO.IIOManager.GetFiles(), Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.HandleExtremelyLongPathOperation(), Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.InstallationSourceSubDirectory, Tgstation.Server.Host.Components.Engine.EngineInstallerBase.IOManager, Tgstation.Server.Host.System.ProcessExecutor.LaunchProcess(), Tgstation.Server.Host.Components.Engine.EngineInstallerBase.Logger, Tgstation.Server.Host.IO.IIOManager.MoveDirectory(), Tgstation.Server.Host.IO.IIOManager.MoveFile(), Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.platformIdentifier, Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.SessionConfigurationOptions, and Tgstation.Server.Common.Extensions.ValueTaskExtensions.WhenAll().
TrustDmbPath()
override ValueTask Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.TrustDmbPath (EngineVersion engineVersion, string fullDmbPath, CancellationToken cancellationToken)
Add a given fullDmbPath to the trusted DMBs list in BYOND's config.
Parameters
version The EngineVersion being used.
fullDmbPath Full path to the .dmb that should be trusted.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Engine.IEngineInstaller.
Definition at line 228 of file OpenDreamInstaller.cs.
        {
            ArgumentNullException.ThrowIfNull(engineVersion);
            ArgumentNullException.ThrowIfNull(fullDmbPath);
            Logger.LogTrace("TrustDmbPath is a no-op: {path}", fullDmbPath);
            return ValueTask.CompletedTask;
        }
References Tgstation.Server.Host.Components.Engine.EngineInstallerBase.Logger.
UpgradeInstallation()
override ValueTask Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.UpgradeInstallation (EngineVersion version, string path, CancellationToken cancellationToken)
Does actions necessary to get upgrade a version installed by a previous version of TGS.
Parameters
version The EngineVersion being installed.
path The path to the installation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Engine.IEngineInstaller.
Definition at line 220 of file OpenDreamInstaller.cs.
        {
            CheckVersionValidity(version);
            ArgumentNullException.ThrowIfNull(path);
            return ValueTask.CompletedTask;
        }
References Tgstation.Server.Host.Components.Engine.EngineInstallerBase.CheckVersionValidity().
Member Data Documentation
asyncDelayer
readonly IAsyncDelayer Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.asyncDelayer private
The IAsyncDelayer for the OpenDreamInstaller.
Definition at line 77 of file OpenDreamInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.GetInstallation(), and Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.OpenDreamInstaller().
BinDir
const string Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.BinDir = "bin" static private
The bin directory name.
Definition at line 29 of file OpenDreamInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.GetExecutablePaths().
httpClientFactory
readonly IHttpClientFactory Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.httpClientFactory private
The IHttpClientFactory for the OpenDreamInstaller.
Definition at line 82 of file OpenDreamInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.GetInstallation(), and Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.OpenDreamInstaller().
InstallationCompilerDirectory
const string Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.InstallationCompilerDirectory = "compiler" static private
The name of the subdirectory in an installation's BinDir used to store the compiler binaries.
Definition at line 39 of file OpenDreamInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.GetExecutablePaths().
InstallationSourceSubDirectory
const string Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.InstallationSourceSubDirectory = "TgsSourceSubdir" static private
The name of the subdirectory used for the RepositoryEngineInstallationData's copy.
Definition at line 44 of file OpenDreamInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.DownloadVersion(), and Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.InstallImpl().
platformIdentifier
readonly IPlatformIdentifier Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.platformIdentifier private
The IPlatformIdentifier for the OpenDreamInstaller.
Definition at line 67 of file OpenDreamInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.GetInstallation(), Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.InstallImpl(), and Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.OpenDreamInstaller().
repositoryManager
readonly IRepositoryManager Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.repositoryManager private
The IRepositoryManager for the OpenDream repository.
Definition at line 72 of file OpenDreamInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.DownloadVersion(), and Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.OpenDreamInstaller().
ServerDir
const string Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.ServerDir = "server" static private
The OD server directory name.
Definition at line 34 of file OpenDreamInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.GetExecutablePaths().
Property Documentation
GeneralConfigurationOptions
IOptionsMonitor<GeneralConfiguration> Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.GeneralConfigurationOptions get protected
The GeneralConfigurationOptions for the OpenDreamInstaller.
Definition at line 57 of file OpenDreamInstaller.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Engine.WindowsOpenDreamInstaller.AddServerFirewallException(), Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.DownloadVersion(), Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.InstallImpl(), and Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.OpenDreamInstaller().
ProcessExecutor
IProcessExecutor Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.ProcessExecutor get protected
The IProcessExecutor for the OpenDreamInstaller.
Definition at line 52 of file OpenDreamInstaller.cs.
{ get; }
SessionConfigurationOptions
IOptionsMonitor<SessionConfiguration> Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.SessionConfigurationOptions get protected
The Configuration.SessionConfiguration for the OpenDreamInstaller.
Definition at line 62 of file OpenDreamInstaller.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Engine.WindowsOpenDreamInstaller.AddServerFirewallException(), Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.InstallImpl(), and Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.OpenDreamInstaller().
TargetEngineType
override EngineType Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.TargetEngineType get protected
Definition at line 47 of file OpenDreamInstaller.cs.
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Engine/OpenDreamInstaller.cs