tgstation-server: Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator Class Reference
Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator Class Reference abstract
IOAuthValidator for generic OAuth2 endpoints.
Public Member Functions
GenericOAuthValidator (IHttpClientFactory httpClientFactory, IAssemblyInformationProvider assemblyInformationProvider, ILogger< GenericOAuthValidator > logger, OAuthConfiguration oAuthConfiguration)
Initializes a new instance of the GenericOAuthValidator class.
async Task< string > ValidateResponseCode (string code, CancellationToken cancellationToken)
Validate a given OAuth response code .
Task< OAuthProviderInfo > GetProviderInfo (CancellationToken cancellationToken)
Gets the OAuthProvider of validator.
Task< OAuthProviderInfo > GetProviderInfo (CancellationToken cancellationToken)
Gets the OAuthProvider of validator.
Task< string > ValidateResponseCode (string code, CancellationToken cancellationToken)
Validate a given OAuth response code .
Protected Member Functions
abstract string DecodeTokenPayload (dynamic responseJson)
Decode the token payload responseJson .
abstract string DecodeUserInformationPayload (dynamic responseJson)
Decode the user information payload responseJson .
abstract OAuthTokenRequest CreateTokenRequest (string code)
Create the OAuthTokenRequest for a given code .
Static Protected Member Functions
static JsonSerializerSettings SerializerSettings ()
Gets JsonSerializerSettings that should be used.
Properties
abstract OAuthProvider Provider [get]
The OAuthProvider this validator is for.
ILogger< GenericOAuthValidator > Logger [get]
The ILogger for the GenericOAuthValidator.
OAuthConfiguration OAuthConfiguration [get]
The OAuthConfiguration for the GenericOAuthValidator.
abstract Uri TokenUrl [get]
Uri to HttpMethod.Post to to get the access token.
abstract Uri UserInformationUrl [get]
Uri to HttpMethod.Get the user information payload from.
Properties inherited from Tgstation.Server.Host.Security.OAuth.IOAuthValidator
OAuthProvider Provider [get]
The OAuthProvider this validator is for.
Private Member Functions
HttpClient CreateHttpClient ()
Create a new configured HttpClient.
Private Attributes
readonly IHttpClientFactory httpClientFactory
The IHttpClientFactory for the GenericOAuthValidator.
readonly IAssemblyInformationProvider assemblyInformationProvider
The IAssemblyInformationProvider for the GenericOAuthValidator.
Detailed Description
IOAuthValidator for generic OAuth2 endpoints.
Definition at line 24 of file GenericOAuthValidator.cs.
Constructor & Destructor Documentation
GenericOAuthValidator()
Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.GenericOAuthValidator (IHttpClientFactory httpClientFactory, IAssemblyInformationProvider assemblyInformationProvider, ILogger< GenericOAuthValidator > logger, OAuthConfiguration oAuthConfiguration)
Initializes a new instance of the GenericOAuthValidator class.
Parameters
httpClientFactory The value of httpClientFactory.
assemblyInformationProvider The value of assemblyInformationProvider.
logger The value of Logger.
oAuthConfiguration The value of OAuthConfiguration.
Definition at line 78 of file GenericOAuthValidator.cs.
        {
            this.httpClientFactory = httpClientFactory ?? throw new ArgumentNullException(nameof(httpClientFactory));
            this.assemblyInformationProvider = assemblyInformationProvider ?? throw new ArgumentNullException(nameof(assemblyInformationProvider));
            Logger = logger ?? throw new ArgumentNullException(nameof(logger));
            OAuthConfiguration = oAuthConfiguration ?? throw new ArgumentNullException(nameof(oAuthConfiguration));
        }
References Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.assemblyInformationProvider, Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.httpClientFactory, and Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.Logger.
Member Function Documentation
CreateHttpClient()
HttpClient Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.CreateHttpClient () private
Create a new configured HttpClient.
Returns
A new configured HttpClient.
Definition at line 182 of file GenericOAuthValidator.cs.
        {
            var httpClient = httpClientFactory.CreateClient();
            try
            {
                httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue(MediaTypeNames.Application.Json));
                httpClient.DefaultRequestHeaders.UserAgent.Add(assemblyInformationProvider.ProductInfoHeaderValue);
                return httpClient;
            }
            catch
            {
                httpClient.Dispose();
                throw;
            }
        }
References Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.assemblyInformationProvider, Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.httpClientFactory, and Tgstation.Server.Host.System.IAssemblyInformationProvider.ProductInfoHeaderValue.
Referenced by Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.ValidateResponseCode().
CreateTokenRequest()
abstract OAuthTokenRequest Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.CreateTokenRequest (string code) protected pure virtual
Create the OAuthTokenRequest for a given code .
Parameters
code The OAuth code from the browser.
Returns
The OAuthTokenRequest to send to TokenUrl.
Implemented in Tgstation.Server.Host.Security.OAuth.DiscordOAuthValidator, Tgstation.Server.Host.Security.OAuth.InvisionCommunityOAuthValidator, Tgstation.Server.Host.Security.OAuth.KeycloakOAuthValidator, and Tgstation.Server.Host.Security.OAuth.TGForumsOAuthValidator.
Referenced by Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.ValidateResponseCode().
DecodeTokenPayload()
abstract string Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.DecodeTokenPayload (dynamic responseJson) protected pure virtual
Decode the token payload responseJson .
Parameters
responseJson The token payload JObject.
Returns
The OAuth2 bearer access token on success, null otherwise.
Implemented in Tgstation.Server.Host.Security.OAuth.DiscordOAuthValidator, Tgstation.Server.Host.Security.OAuth.InvisionCommunityOAuthValidator, Tgstation.Server.Host.Security.OAuth.KeycloakOAuthValidator, and Tgstation.Server.Host.Security.OAuth.TGForumsOAuthValidator.
Referenced by Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.ValidateResponseCode().
DecodeUserInformationPayload()
abstract string Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.DecodeUserInformationPayload (dynamic responseJson) protected pure virtual
Decode the user information payload responseJson .
Parameters
responseJson The user information payload JObject.
Returns
The user ID on success, null otherwise.
Implemented in Tgstation.Server.Host.Security.OAuth.DiscordOAuthValidator, Tgstation.Server.Host.Security.OAuth.InvisionCommunityOAuthValidator, Tgstation.Server.Host.Security.OAuth.KeycloakOAuthValidator, and Tgstation.Server.Host.Security.OAuth.TGForumsOAuthValidator.
Referenced by Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.ValidateResponseCode().
GetProviderInfo()
Task< OAuthProviderInfo > Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.GetProviderInfo (CancellationToken cancellationToken)
Gets the OAuthProvider of validator.
Implements Tgstation.Server.Host.Security.OAuth.IOAuthValidator.
References Tgstation.Server.Host.Configuration.OAuthConfigurationBase.ClientId, Tgstation.Server.Host.Configuration.OAuthConfiguration.RedirectUrl, and Tgstation.Server.Host.Configuration.OAuthConfiguration.ServerUrl.
SerializerSettings()
static JsonSerializerSettings Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.SerializerSettings () static protected
Gets JsonSerializerSettings that should be used.
Returns
A new JsonSerializerSettings object.
Referenced by Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.ValidateResponseCode().
ValidateResponseCode()
async Task< string > Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.ValidateResponseCode (string code, CancellationToken cancellationToken)
Validate a given OAuth response code .
Implements Tgstation.Server.Host.Security.OAuth.IOAuthValidator.
Definition at line 91 of file GenericOAuthValidator.cs.
        {
            using var httpClient = CreateHttpClient();
            string tokenResponsePayload = null;
            string userInformationPayload = null;
            try
            {
                Logger.LogTrace("Validating response code...");
                using var tokenRequest = new HttpRequestMessage(HttpMethod.Post, TokenUrl);
                var tokenRequestPayload = CreateTokenRequest(code);
                // roundabout but it works
                var tokenRequestJson = JsonConvert.SerializeObject(
                    tokenRequestPayload,
                    SerializerSettings());
                var tokenRequestDictionary = JsonConvert.DeserializeObject<Dictionary<string, string>>(tokenRequestJson);
                tokenRequest.Content = new FormUrlEncodedContent(tokenRequestDictionary);
                var tokenResponse = await httpClient.SendAsync(tokenRequest, cancellationToken);
                tokenResponsePayload = await tokenResponse.Content.ReadAsStringAsync();
                tokenResponse.EnsureSuccessStatusCode();
                var tokenResponseJson = JObject.Parse(tokenResponsePayload);
                var accessToken = DecodeTokenPayload(tokenResponseJson);
                if (accessToken == null)
                {
                    Logger.LogTrace("No token from DecodeTokenPayload!");
                    return null;
                }
                Logger.LogTrace("Getting user details...");
                using var userInformationRequest = new HttpRequestMessage(HttpMethod.Get, UserInformationUrl);
                userInformationRequest.Headers.Authorization = new AuthenticationHeaderValue(
                    ApiHeaders.BearerAuthenticationScheme,
                    accessToken);
                var userInformationResponse = await httpClient.SendAsync(userInformationRequest, cancellationToken);
                userInformationPayload = await userInformationResponse.Content.ReadAsStringAsync();
                userInformationResponse.EnsureSuccessStatusCode();
                var userInformationJson = JObject.Parse(userInformationPayload);
                return DecodeUserInformationPayload(userInformationJson);
            }
            catch (Exception ex)
            {
                Logger.LogWarning(
                    ex,
                    "Error while completing OAuth handshake! Payload:{newLine}{responsePayload}",
                    Environment.NewLine,
                    userInformationPayload ?? tokenResponsePayload);
                return null;
            }
        }
References Tgstation.Server.Api.ApiHeaders.BearerAuthenticationScheme, Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.CreateHttpClient(), Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.CreateTokenRequest(), Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.DecodeTokenPayload(), Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.DecodeUserInformationPayload(), Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.Logger, Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.SerializerSettings(), Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.TokenUrl, and Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.UserInformationUrl.
Member Data Documentation
assemblyInformationProvider
readonly IAssemblyInformationProvider Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.assemblyInformationProvider private
The IAssemblyInformationProvider for the GenericOAuthValidator.
Definition at line 57 of file GenericOAuthValidator.cs.
Referenced by Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.CreateHttpClient(), and Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.GenericOAuthValidator().
httpClientFactory
readonly IHttpClientFactory Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.httpClientFactory private
The IHttpClientFactory for the GenericOAuthValidator.
Definition at line 52 of file GenericOAuthValidator.cs.
Referenced by Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.CreateHttpClient(), and Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.GenericOAuthValidator().
Property Documentation
Logger
ILogger<GenericOAuthValidator> Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.Logger get protected
The ILogger for the GenericOAuthValidator.
Definition at line 32 of file GenericOAuthValidator.cs.
{ get; }
Referenced by Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.GenericOAuthValidator(), and Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.ValidateResponseCode().
OAuthConfiguration
OAuthConfiguration Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.OAuthConfiguration get protected
The OAuthConfiguration for the GenericOAuthValidator.
Definition at line 37 of file GenericOAuthValidator.cs.
{ get; }
Provider
abstract OAuthProvider Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.Provider get
The OAuthProvider this validator is for.
Implements Tgstation.Server.Host.Security.OAuth.IOAuthValidator.
Definition at line 27 of file GenericOAuthValidator.cs.
{ get; }
TokenUrl
abstract Uri Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.TokenUrl get protected
Uri to HttpMethod.Post to to get the access token.
Definition at line 42 of file GenericOAuthValidator.cs.
{ get; }
Referenced by Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.ValidateResponseCode().
UserInformationUrl
abstract Uri Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.UserInformationUrl get protected
Uri to HttpMethod.Get the user information payload from.
Definition at line 47 of file GenericOAuthValidator.cs.
{ get; }
Referenced by Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.ValidateResponseCode().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Security/OAuth/GenericOAuthValidator.cs