tgstation-server: Tgstation.Server.Host.Controllers.InstanceRequiredController Class Reference
Tgstation.Server.Host.Controllers.InstanceRequiredController Class Reference
abstract ApiController for operations on an IInstance.
Static Public Member Functions
static bool ValidateInstanceOnlineStatus (IInstanceManager instanceManager, ILogger logger, Api.Models.Instance metadata)
Corrects discrepencies between the Api.Models.Instance.Online status of IInstances in the database vs the service.
Protected Member Functions
InstanceRequiredController (IInstanceManager instanceManager, IDatabaseContext databaseContext, IAuthenticationContextFactory authenticationContextFactory, ILogger< InstanceRequiredController > logger)
Initializes a new instance of the InstanceRequiredController class.
override async Task< IActionResult > ValidateRequest (CancellationToken cancellationToken)
Performs validation a request.
async Task< IActionResult > WithComponentInstance (Func< IInstanceCore, Task< IActionResult > > action)
Run a given action with the relevant IInstance.
Protected Member Functions inherited from Tgstation.Server.Host.Controllers.ApiController
ApiController (IDatabaseContext databaseContext, IAuthenticationContextFactory authenticationContextFactory, ILogger< ApiController > logger, bool requireHeaders)
Initializes a new instance of the ApiController class.
ObjectResult Gone ()
Generic 410 response.
new NotFoundObjectResult NotFound ()
Generic 404 response.
ObjectResult RequiresPosixSystemIdentity ()
Generic 501 response.
StatusCodeResult StatusCode (HttpStatusCode statusCode)
Strongly type calls to ControllerBase.StatusCode(int).
ObjectResult StatusCode (HttpStatusCode statusCode, object errorMessage)
Strongly type calls to ControllerBase.StatusCode(int, object).
ObjectResult Created (object payload)
Generic 201 response with a given payload .
ObjectResult RateLimit (RateLimitExceededException rateLimitException)
429 response for a given rateLimitException .
virtual Task< IActionResult > ValidateRequest (CancellationToken cancellationToken)
Performs validation a request.
IActionResult HeadersIssue (bool ignoreMissingAuth)
Response for missing/Invalid headers.
Task< IActionResult > Paginated< TModel > (Func< Task< PaginatableResult< TModel > > > queryGenerator, Func< TModel, Task > resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
Task< IActionResult > Paginated< TModel, TApiModel > (Func< Task< PaginatableResult< TModel > > > queryGenerator, Func< TApiModel, Task > resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
Private Attributes
readonly IInstanceManager instanceManager
The IInstanceManager for the InstanceRequiredController.
Additional Inherited Members
Public Member Functions inherited from Tgstation.Server.Host.Controllers.ApiController
override async Task OnActionExecutionAsync (ActionExecutingContext context, ActionExecutionDelegate next)
Properties inherited from Tgstation.Server.Host.Controllers.ApiController
ApiHeaders ApiHeaders [get, private set]
The Api.ApiHeaders for the operation.
IDatabaseContext DatabaseContext [get]
The IDatabaseContext for the operation.
IAuthenticationContext AuthenticationContext [get]
The IAuthenticationContext for the operation.
ILogger< ApiController > Logger [get]
The ILogger for the ApiController.
Models.Instance Instance [get]
The Instance for the operation.
Detailed Description
abstract ApiController for operations on an IInstance.
Definition at line 20 of file InstanceRequiredController.cs.
Constructor & Destructor Documentation
InstanceRequiredController()
Tgstation.Server.Host.Controllers.InstanceRequiredController.InstanceRequiredController (IInstanceManager instanceManager, IDatabaseContext databaseContext, IAuthenticationContextFactory authenticationContextFactory, ILogger< InstanceRequiredController > logger) protected
Initializes a new instance of the InstanceRequiredController class.
Parameters
instanceManager The value of instanceManager.
databaseContext The IDatabaseContext for the ApiController.
authenticationContextFactory The IAuthenticationContextFactory for the ApiController.
logger The ILogger for the ApiController.
Definition at line 68 of file InstanceRequiredController.cs.
            : base(
                  databaseContext,
                  authenticationContextFactory,
                  logger,
                  true)
        {
            this.instanceManager = instanceManager ?? throw new ArgumentNullException(nameof(instanceManager));
        }
References Tgstation.Server.Host.Controllers.InstanceRequiredController.instanceManager.
Member Function Documentation
ValidateInstanceOnlineStatus()
static bool Tgstation.Server.Host.Controllers.InstanceRequiredController.ValidateInstanceOnlineStatus (IInstanceManager instanceManager, ILogger logger, Api.Models.Instance metadata) static
Corrects discrepencies between the Api.Models.Instance.Online status of IInstances in the database vs the service.
Parameters
instanceManager The IInstanceManager to use.
logger The ILogger to use.
metadata The Api.Models.Instance to check.
Returns
true if an unsaved DB update was made, false otherwise.
Definition at line 34 of file InstanceRequiredController.cs.
        {
            if (instanceManager == null)
                throw new ArgumentNullException(nameof(instanceManager));
            if (metadata == null)
                throw new ArgumentNullException(nameof(metadata));
            bool online;
            using (var instanceReferenceCheck = instanceManager.GetInstanceReference(metadata))
                online = instanceReferenceCheck != null;
            if (metadata.Online.Value == online)
                return false;
            const string OfflineWord = "offline";
            const string OnlineWord = "online";
            logger.LogWarning(
                "Instance {0} is says it's {1} in the database, but it is actually {2} in the service. Updating the database to reflect this...",
                metadata.Id,
                online ? OfflineWord : OnlineWord,
                online ? OnlineWord : OfflineWord);
            metadata.Online = online;
            return true;
        }
References Tgstation.Server.Host.Components.IInstanceManager.GetInstanceReference(), and Tgstation.Server.Host.Controllers.InstanceRequiredController.instanceManager.
Referenced by Tgstation.Server.Host.Controllers.InstanceController.GetId(), Tgstation.Server.Host.Controllers.InstanceController.List(), Tgstation.Server.Host.Controllers.InstanceController.Update(), and Tgstation.Server.Host.Controllers.InstanceRequiredController.ValidateRequest().
ValidateRequest()
override async Task< IActionResult > Tgstation.Server.Host.Controllers.InstanceRequiredController.ValidateRequest (CancellationToken cancellationToken) protected virtual
Performs validation a request.
Reimplemented from Tgstation.Server.Host.Controllers.ApiController.
Definition at line 83 of file InstanceRequiredController.cs.
        {
            if (!ApiHeaders.InstanceId.HasValue)
                return BadRequest(new ErrorMessageResponse(ErrorCode.InstanceHeaderRequired));
            if (AuthenticationContext.InstancePermissionSet == null)
                return Forbid();
            if (ValidateInstanceOnlineStatus(instanceManager, Logger, Instance))
                await DatabaseContext.Save(cancellationToken).ConfigureAwait(false);
            using var instanceReferenceCheck = instanceManager.GetInstanceReference(Instance);
            if (instanceReferenceCheck == null)
                return Conflict(new ErrorMessageResponse(ErrorCode.InstanceOffline));
            return null;
        }
References Tgstation.Server.Host.Controllers.ApiController.ApiHeaders, Tgstation.Server.Host.Components.IInstanceManager.GetInstanceReference(), Tgstation.Server.Host.Controllers.InstanceRequiredController.instanceManager, Tgstation.Server.Host.Security.AuthenticationContext.InstancePermissionSet, Tgstation.Server.Host.Controllers.ApiController.Logger, Tgstation.Server.Host.Database.DatabaseContext.Save(), and Tgstation.Server.Host.Controllers.InstanceRequiredController.ValidateInstanceOnlineStatus().
WithComponentInstance()
async Task< IActionResult > Tgstation.Server.Host.Controllers.InstanceRequiredController.WithComponentInstance (Func< IInstanceCore, Task< IActionResult > > action) protected
Run a given action with the relevant IInstance.
Parameters
action A Func<T, TResult> accepting the IInstance and returning a Task<TResult> with the IActionResult.
Returns
A Task<TResult> resulting in the IActionResult that should be returned.
The context of action should be as small as possinle so as to avoid race conditions.
Definition at line 105 of file InstanceRequiredController.cs.
        {
            if (action == null)
                throw new ArgumentNullException(nameof(action));
            using var instanceReference = instanceManager.GetInstanceReference(Instance);
            using (LogContext.PushProperty("InstanceReference", instanceReference.Uid))
            {
                if (instanceReference == null)
                    return Conflict(new ErrorMessageResponse(ErrorCode.InstanceOffline));
                return await action(instanceReference).ConfigureAwait(false);
            }
        }
References Tgstation.Server.Host.Components.IInstanceManager.GetInstanceReference(), and Tgstation.Server.Host.Controllers.InstanceRequiredController.instanceManager.
Referenced by Tgstation.Server.Host.Controllers.ChatController.Create(), Tgstation.Server.Host.Controllers.RepositoryController.Create(), Tgstation.Server.Host.Controllers.ConfigurationController.CreateDirectory(), Tgstation.Server.Host.Controllers.ConfigurationController.DeleteDirectory(), Tgstation.Server.Host.Controllers.ConfigurationController.File(), Tgstation.Server.Host.Controllers.RepositoryController.Read(), Tgstation.Server.Host.Controllers.ByondController.Update(), Tgstation.Server.Host.Controllers.ChatController.Update(), Tgstation.Server.Host.Controllers.ConfigurationController.Update(), Tgstation.Server.Host.Controllers.DreamDaemonController.Update(), and Tgstation.Server.Host.Controllers.RepositoryController.Update().
Member Data Documentation
instanceManager
readonly IInstanceManager Tgstation.Server.Host.Controllers.InstanceRequiredController.instanceManager private
The IInstanceManager for the InstanceRequiredController.
Definition at line 25 of file InstanceRequiredController.cs.
Referenced by Tgstation.Server.Host.Controllers.InstanceRequiredController.InstanceRequiredController(), Tgstation.Server.Host.Controllers.InstanceRequiredController.ValidateInstanceOnlineStatus(), Tgstation.Server.Host.Controllers.InstanceRequiredController.ValidateRequest(), and Tgstation.Server.Host.Controllers.InstanceRequiredController.WithComponentInstance().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Controllers/InstanceRequiredController.cs