tgstation-server: TGControlPanel.ControlPanel Class Reference
TGControlPanel.ControlPanel Class Reference
The main ControlPanel form
Public Member Functions
ControlPanel (IInterface I)
Constructs a ControlPanel
Public Member Functions inherited from TGControlPanel.CountedForm
CountedForm ()
Construct a CountedForm. Increments FormCount
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
ChatProvider ModifyingProvider [get, set]
static IDictionary< string, ControlPanel > InstancesInUse [get, private set]
List of instances being used by open control panels
Private Types
enum RepoAction {
RepoAction.Clone, RepoAction.Checkout, RepoAction.Update, RepoAction.Merge,
RepoAction.Reset, RepoAction.Test, RepoAction.Wait, RepoAction.GenCL
}
enum FullUpdateAction {
FullUpdateAction.UpdateHard, FullUpdateAction.UpdateMerge, FullUpdateAction.UpdateHardTestmerge, FullUpdateAction.Reset,
FullUpdateAction.Testmerge
}
enum EnumResult { EnumResult.Enumerated, EnumResult.Unauthorized, EnumResult.NotEnumerated, EnumResult.Error }
Private Member Functions
void InitBYONDPage ()
void UpdateButton_Click (object sender, EventArgs e)
void BYONDRefreshButton_Click (object sender, EventArgs e)
void UpdateBYONDButtons ()
void LoadChatPage ()
void ChatRefreshButton_Click (object sender, EventArgs e)
void ChatReconnectButton_Click (object sender, EventArgs e)
void DiscordProviderSwitch_CheckedChanged (object sender, EventArgs e)
void IRCProviderSwitch_CheckedChanged (object sender, EventArgs e)
void SetAdminsAreSpecial (bool value)
void AdminModeNormal_CheckedChanged (object sender, EventArgs e)
void AdminModeSpecial_CheckedChanged (object sender, EventArgs e)
void ChatApplyButton_Click (object sender, EventArgs e)
void Cleanup ()
Called from Dispose(bool)
void Main_Resize (object sender, EventArgs e)
void Panels_SelectedIndexChanged (object sender, EventArgs e)
bool CheckAdminWithWarning ()
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitRepoPage ()
void BackupTagsList_MouseDoubleClick (object sender, MouseEventArgs e)
void RepoBGW_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e)
void RepoRefreshButton_Click (object sender, EventArgs e)
void PopulateRepoFields ()
bool RepoBusyCheck ()
void RepoBGW_ProgressChanged (object sender, ProgressChangedEventArgs e)
void RepoBGW_DoWork (object sender, DoWorkEventArgs e)
void CloneRepositoryButton_Click (object sender, EventArgs e)
void CloneRepo ()
void RecloneButton_Click (object sender, EventArgs e)
void DoAsyncOp (RepoAction ra, string message)
void RepoApplyButton_Click (object sender, EventArgs e)
void UpdateRepoButton_Click (object sender, EventArgs e)
void HardReset_Click (object sender, EventArgs e)
void ResetRemote_Click (object sender, EventArgs e)
void TestMergeButton_Click (object sender, EventArgs e)
void RepoGenChangelogButton_Click (object sender, System.EventArgs e)
void TGSJsonUpdate_Click (object sender, EventArgs e)
void InitServerPage ()
void ServerStartBGW_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e)
void ProjectNameText_KeyDown (object sender, KeyEventArgs e)
void FullUpdateWorker_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e)
void CompileCancelButton_Click (object sender, EventArgs e)
void LoadServerPage ()
void ProjectNameText_LostFocus (object sender, EventArgs e)
void UpdateProjectName ()
void PortSelector_ValueChanged (object sender, EventArgs e)
void RunServerUpdate (FullUpdateAction fua, ushort tm=0)
void ServerPageRefreshButton_Click (object sender, EventArgs e)
void InitializeButton_Click (object sender, EventArgs e)
void CompileButton_Click (object sender, EventArgs e)
void AutostartCheckbox_CheckedChanged (object sender, System.EventArgs e)
void ServerStartButton_Click (object sender, System.EventArgs e)
void ServerStartBGW_DoWork (object sender, DoWorkEventArgs e)
void ServerStopButton_Click (object sender, EventArgs e)
void ServerRestartButton_Click (object sender, EventArgs e)
void ServerGStopButton_Checked (object sender, EventArgs e)
void ServerGRestartButton_Click (object sender, EventArgs e)
void FullUpdateWorker_DoWork (object sender, DoWorkEventArgs e)
void ResetTestmerge_Click (object sender, EventArgs e)
void UpdateHardButton_Click (object sender, System.EventArgs e)
void UpdateTestmergeButton_Click (object sender, System.EventArgs e)
void UpdateMergeButton_Click (object sender, System.EventArgs e)
void TestmergeButton_Click (object sender, System.EventArgs e)
void SecuritySelector_SelectedIndexChanged (object sender, EventArgs e)
void WorldAnnounceButton_Click (object sender, EventArgs e)
void WebclientCheckBox_CheckedChanged (object sender, EventArgs e)
void AutoUpdateInterval_ValueChanged (object sender, EventArgs e)
void AutoUpdateCheckbox_CheckedChanged (object sender, EventArgs e)
void InitStaticPage ()
void BuildFileList ()
EnumResult EnumeratePath (string path, ITGConfig config, int level)
string DSNTimes (int n)
void StaticFilesRefreshButton_Click (object sender, EventArgs e)
void StaticFileUploadButton_Click (object sender, EventArgs e)
void StaticFileDownloadButton_Click (object sender, EventArgs e)
void StaticFileDeleteButton_Click (object sender, EventArgs e)
void StaticFileCreateButton_Click (object sender, EventArgs e)
void StaticFileSaveButton_Click (object sender, EventArgs e)
void StaticFileListBox_SelectedIndexChanged (object sender, EventArgs e)
void UpdateEditText ()
void RecreateStaticButton_Click (object sender, EventArgs e)
Static Private Member Functions
static void AssignListToTextbox (IList< string > a, TextBox b)
static string[] SplitByLine (TextBox t)
Private Attributes
string lastReadError = null
bool updatingChat = false
readonly IInterface Interface = new Dictionary<string, ControlPanel>()
The IInterface instance for this ControlPanel
System.ComponentModel.IContainer components = null
Required designer variable.
System.ComponentModel.BackgroundWorker RepoBGW
System.ComponentModel.BackgroundWorker FullUpdateWorker
System.ComponentModel.BackgroundWorker ServerStartBGW
System.Windows.Forms.TabPage ChatPanel
System.Windows.Forms.Label label5
System.Windows.Forms.Label label4
System.Windows.Forms.Label label3
System.Windows.Forms.Label label2
System.Windows.Forms.ComboBox IRCModesComboBox
System.Windows.Forms.Label label1
System.Windows.Forms.TextBox AdminChannelsTextbox
System.Windows.Forms.TextBox WDChannelsTextbox
System.Windows.Forms.TextBox GameChannelsTextbox
System.Windows.Forms.TextBox DevChannelsTextbox
System.Windows.Forms.TextBox ChatNicknameText
System.Windows.Forms.TextBox ChatServerText
System.Windows.Forms.TextBox AuthField2
System.Windows.Forms.TextBox AuthField1
System.Windows.Forms.TextBox ChatAdminsTextBox
System.Windows.Forms.Button ChatRefreshButton
System.Windows.Forms.Label ChatNicknameTitle
System.Windows.Forms.NumericUpDown ChatPortSelector
System.Windows.Forms.Label ChatPortTitle
System.Windows.Forms.Label ChatServerTitle
System.Windows.Forms.Button ChatApplyButton
System.Windows.Forms.Label AuthField2Title
System.Windows.Forms.Label AuthField1Title
System.Windows.Forms.Button ChatReconnectButton
System.Windows.Forms.Label ChatStatusLabel
System.Windows.Forms.Label ChatStatusTitle
System.Windows.Forms.CheckBox ChatEnabledCheckbox
System.Windows.Forms.Panel ChatProviderSelectorPanel
System.Windows.Forms.RadioButton DiscordProviderSwitch
System.Windows.Forms.RadioButton IRCProviderSwitch
System.Windows.Forms.Label ChatProviderTitle
System.Windows.Forms.Label ChannelsTitle
System.Windows.Forms.Label ChatAdminsTitle
System.Windows.Forms.Panel panel1
System.Windows.Forms.RadioButton AdminModeSpecial
System.Windows.Forms.RadioButton AdminModeNormal
System.Windows.Forms.TabPage ServerPanel
System.Windows.Forms.CheckBox AutostartCheckbox
System.Windows.Forms.CheckBox WebclientCheckBox
System.Windows.Forms.Button WorldAnnounceButton
System.Windows.Forms.TextBox WorldAnnounceField
System.Windows.Forms.Label WorldAnnounceLabel
System.Windows.Forms.ComboBox SecuritySelector
System.Windows.Forms.Label SecurityTitle
System.Windows.Forms.Button ResetTestmerge
System.Windows.Forms.Label ServerPathLabel
System.Windows.Forms.Button CompileCancelButton
System.Windows.Forms.Label ProjectPathLabel
System.Windows.Forms.Label PortLabel
System.Windows.Forms.NumericUpDown PortSelector
System.Windows.Forms.Label ServerPRLabel
System.Windows.Forms.NumericUpDown ServerTestmergeInput
System.Windows.Forms.Button TestmergeButton
System.Windows.Forms.Button UpdateTestmergeButton
System.Windows.Forms.Button UpdateMergeButton
System.Windows.Forms.Button UpdateHardButton
System.Windows.Forms.Button ServerGRestartButton
System.Windows.Forms.CheckBox ServerGStopButton
System.Windows.Forms.Button ServerRestartButton
System.Windows.Forms.Button ServerStopButton
System.Windows.Forms.Button ServerStartButton
System.Windows.Forms.Label CompilerStatusLabel
System.Windows.Forms.Label CompilerLabel
System.Windows.Forms.Button compileButton
System.Windows.Forms.Button initializeButton
System.Windows.Forms.Label ServerStatusLabel
System.Windows.Forms.Label ServerStatusTitle
System.Windows.Forms.TabPage BYONDPanel
System.Windows.Forms.Label LatestVersionLabel
System.Windows.Forms.Label LatestVersionTitle
System.Windows.Forms.Label StagedVersionLabel
System.Windows.Forms.Label StagedVersionTitle
System.Windows.Forms.Label StatusLabel
System.Windows.Forms.Label VersionLabel
System.Windows.Forms.Label VersionTitle
System.Windows.Forms.Label MinorVersionLabel
System.Windows.Forms.Label MajorVersionLabel
System.Windows.Forms.Button UpdateButton
System.Windows.Forms.NumericUpDown MinorVersionNumeric
System.Windows.Forms.NumericUpDown MajorVersionNumeric
System.Windows.Forms.TabPage RepoPanel
System.Windows.Forms.Button RepoRefreshButton
System.Windows.Forms.ListBox BackupTagsList
System.Windows.Forms.Button ResetRemote
System.Windows.Forms.Button RecloneButton
System.Windows.Forms.TextBox RepoBranchTextBox
System.Windows.Forms.TextBox RepoRemoteTextBox
System.Windows.Forms.Button RepoGenChangelogButton
System.Windows.Forms.NumericUpDown TestmergeSelector
System.Windows.Forms.ListBox TestMergeListLabel
System.Windows.Forms.Label CurrentRevisionLabel
System.Windows.Forms.Button RepoApplyButton
System.Windows.Forms.Button HardReset
System.Windows.Forms.Button UpdateRepoButton
System.Windows.Forms.Button MergePRButton
System.Windows.Forms.Label IdentityLabel
System.Windows.Forms.Label TestMergeListTitle
System.Windows.Forms.Label RemoteNameTitle
System.Windows.Forms.Label BranchNameTitle
System.Windows.Forms.Label CurrentRevisionTitle
System.Windows.Forms.Button CloneRepositoryButton
System.Windows.Forms.Label RepoProgressBarLabel
System.Windows.Forms.ProgressBar RepoProgressBar
System.Windows.Forms.TabControl Panels
System.Windows.Forms.TabPage StaticPanel
System.Windows.Forms.Button StaticFileCreateButton
System.Windows.Forms.Label label6
System.Windows.Forms.ListBox StaticFileListBox
System.Windows.Forms.Button StaticFileUploadButton
System.Windows.Forms.TextBox StaticFileEditTextbox
System.Windows.Forms.Button StaticFileDeleteButton
System.Windows.Forms.Button StaticFileSaveButton
System.Windows.Forms.Button StaticFilesRefreshButton
System.Windows.Forms.Button StaticFileDownloadButton
System.Windows.Forms.Button TGSJsonUpdate
System.Windows.Forms.Button BYONDRefreshButton
System.Windows.Forms.Button ServerPageRefreshButton
System.Windows.Forms.Button RecreateStaticButton
System.Windows.Forms.NumericUpDown AutoUpdateInterval
System.Windows.Forms.CheckBox AutoUpdateCheckbox
System.Windows.Forms.Label AutoUpdateMLabel
System.Windows.Forms.TextBox projectNameText
RepoAction action
string CloneRepoURL
string CheckoutBranch
int TestPR
string repoError
FullUpdateAction fuAction
ushort testmergePR
string updateError
bool updatingFields = false
IDictionary< int, string > IndexesToPaths = new Dictionary<int, string>()
IList< string > EnumeratedPaths = new List<string>() { "" }
bool enumerating = false
Detailed Description
The main ControlPanel form
Definition at line 8 of file ByondPage.cs.
Member Enumeration Documentation
enum TGControlPanel.ControlPanel.EnumResult strong private
Enumerator
Enumerated
Unauthorized
NotEnumerated
Error
Definition at line 16 of file StaticPage.cs.
         {
             Enumerated,
             Unauthorized,
             NotEnumerated,
             Error,
         }
enum TGControlPanel.ControlPanel.FullUpdateAction strong private
Enumerator
UpdateHard
UpdateMerge
UpdateHardTestmerge
Reset
Testmerge
Definition at line 11 of file ServerPage.cs.
         {
             UpdateHard,
             UpdateMerge,
             UpdateHardTestmerge,
             Reset,
             Testmerge,
         }
enum TGControlPanel.ControlPanel.RepoAction strong private
Enumerator
Clone
Checkout
Update
Merge
Reset
Test
Wait
GenCL
Definition at line 12 of file RepoPage.cs.
{
             Clone,
             Checkout,
             Update,
             Merge,
             Reset,
             Test,
             Wait,
             GenCL,
         }
Constructor & Destructor Documentation
TGControlPanel.ControlPanel.ControlPanel (IInterface I)
Constructs a ControlPanel
Parameters
I The IInterface for the ControlPanel
Definition at line 29 of file ControlPanel.cs.
References TGControlPanel.ControlPanel.InitBYONDPage(), TGControlPanel.ControlPanel.InitializeComponent(), TGControlPanel.ControlPanel.InitRepoPage(), TGControlPanel.ControlPanel.InitServerPage(), TGControlPanel.ControlPanel.InitStaticPage(), TGServiceInterface.IInterface.InstanceName, TGControlPanel.ControlPanel.InstancesInUse, TGControlPanel.ControlPanel.LoadChatPage(), TGControlPanel.ControlPanel.Panels, and TGControlPanel.ControlPanel.Panels_SelectedIndexChanged().
         {
             InitializeComponent();
             Interface = I;
             if (Interface.IsRemoteConnection)
             {
                 var splits = Interface.GetComponent<ITGSService>().Version().Split(' ');
                 Text = String.Format("TGS {0}: {1}:{2}", splits[splits.Length - 1], Interface.HTTPSURL, Interface.HTTPSPort);
             }
             Text += " Instance: " + I.InstanceName;
             if (Interface.VersionMismatch(out string error) && MessageBox.Show(error, "Warning", MessageBoxButtons.OKCancel) == DialogResult.Cancel)
             {
                 Close();
                 return;
             }
             Panels.SelectedIndexChanged += Panels_SelectedIndexChanged;
             Panels.SelectedIndex += Math.Min(Properties.Settings.Default.LastPageIndex, Panels.TabCount - 1);
             InitRepoPage();
             InitBYONDPage();
             InitServerPage();
             LoadChatPage();
             InitStaticPage();
             InstancesInUse.Add(I.InstanceName, this);
         }
Member Function Documentation
void TGControlPanel.ControlPanel.AdminModeNormal_CheckedChanged (object sender, EventArgs e) private
Definition at line 161 of file ChatPage.cs.
References TGControlPanel.ControlPanel.AdminModeNormal, and TGControlPanel.ControlPanel.SetAdminsAreSpecial().
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             if (!updatingChat && AdminModeNormal.Checked)
                 SetAdminsAreSpecial(false);
         }
void TGControlPanel.ControlPanel.AdminModeSpecial_CheckedChanged (object sender, EventArgs e) private
Definition at line 167 of file ChatPage.cs.
References TGControlPanel.ControlPanel.AdminModeSpecial, and TGControlPanel.ControlPanel.SetAdminsAreSpecial().
         {
             if (!updatingChat && AdminModeSpecial.Checked)
                 SetAdminsAreSpecial(true);
         }
static void TGControlPanel.ControlPanel.AssignListToTextbox (IList< string > a, TextBox b) static private
Definition at line 101 of file ChatPage.cs.
Referenced by TGControlPanel.ControlPanel.LoadChatPage().
         {
             b.Text = "";
             foreach (var I in a)
                 b.Text += I + Environment.NewLine;
         }
void TGControlPanel.ControlPanel.AutostartCheckbox_CheckedChanged (object sender, System.EventArgs e) private
Definition at line 265 of file ServerPage.cs.
References TGControlPanel.ControlPanel.AutostartCheckbox.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             if (!updatingFields)
                 Interface.GetComponent<ITGDreamDaemon>().SetAutostart(AutostartCheckbox.Checked);
         }
void TGControlPanel.ControlPanel.AutoUpdateCheckbox_CheckedChanged (object sender, EventArgs e) private
Definition at line 452 of file ServerPage.cs.
References TGControlPanel.ControlPanel.AutoUpdateCheckbox, TGControlPanel.ControlPanel.AutoUpdateInterval, and TGControlPanel.ControlPanel.AutoUpdateMLabel.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             if (updatingFields)
                 return;
             var on = AutoUpdateCheckbox.Visible && AutoUpdateCheckbox.Checked;
             AutoUpdateInterval.Visible = on;
             AutoUpdateMLabel.Visible = on;
             if (!on)
                 Interface.GetComponent<ITGRepository>().SetAutoUpdateInterval(0);
             else
                 Interface.GetComponent<ITGRepository>().SetAutoUpdateInterval((ulong)AutoUpdateInterval.Value);
         }
void TGControlPanel.ControlPanel.AutoUpdateInterval_ValueChanged (object sender, EventArgs e) private
Definition at line 446 of file ServerPage.cs.
References TGControlPanel.ControlPanel.AutoUpdateInterval.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             if (!updatingFields)
                 Interface.GetComponent<ITGRepository>().SetAutoUpdateInterval((ulong)AutoUpdateInterval.Value);
         }
void TGControlPanel.ControlPanel.BackupTagsList_MouseDoubleClick (object sender, MouseEventArgs e) private
Definition at line 39 of file RepoPage.cs.
References TGControlPanel.ControlPanel.BackupTagsList, and TGControlPanel.ControlPanel.DoAsyncOp().
Referenced by TGControlPanel.ControlPanel.InitRepoPage().
         {
             int index = BackupTagsList.IndexFromPoint(e.Location);
             if (index != ListBox.NoMatches)
             {
                 var indexText = (string)BackupTagsList.Items[index];
                 if (indexText == "None" || indexText == "Unknown")
                     return;
                 var tagname = indexText.Split(':')[0];
                 var spaceSplits = indexText.Split(' ');
                 var sha = spaceSplits[spaceSplits.Length - 1];
                 if (MessageBox.Show(String.Format("Checkout tag {0} ({1})?", tagname, sha), "Restore Backup", MessageBoxButtons.YesNo) != DialogResult.Yes)
                     return;
                 CheckoutBranch = tagname;
                 DoAsyncOp(RepoAction.Checkout, "Checking out " + tagname + "...");
             }
         }
void TGControlPanel.ControlPanel.BuildFileList () private
Definition at line 31 of file StaticPage.cs.
References TGControlPanel.ControlPanel.EnumeratePath(), and TGControlPanel.ControlPanel.StaticFileListBox.
Referenced by TGControlPanel.ControlPanel.InitStaticPage(), TGControlPanel.ControlPanel.RecreateStaticButton_Click(), TGControlPanel.ControlPanel.StaticFileCreateButton_Click(), TGControlPanel.ControlPanel.StaticFileDeleteButton_Click(), TGControlPanel.ControlPanel.StaticFilesRefreshButton_Click(), TGControlPanel.ControlPanel.StaticFileUploadButton_Click(), and TGControlPanel.ControlPanel.UpdateEditText().
         {
             enumerating = true;
             IndexesToPaths.Clear();
             StaticFileListBox.Items.Clear();
             IndexesToPaths.Add(StaticFileListBox.Items.Add("/"), "/");
             if (EnumeratePath("", Interface.GetComponent<ITGConfig>(), 1) == EnumResult.Unauthorized)
             {
                 StaticFileListBox.Items[0] += " (UNAUTHORIZED)";
                 IndexesToPaths[0] = null;
             }
             StaticFileListBox.SelectedIndex = 0;
             enumerating = false;
         }
void TGControlPanel.ControlPanel.BYONDRefreshButton_Click (object sender, EventArgs e) private
Definition at line 54 of file ByondPage.cs.
References TGControlPanel.ControlPanel.UpdateBYONDButtons().
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             UpdateBYONDButtons();
         }
void TGControlPanel.ControlPanel.ChatApplyButton_Click (object sender, EventArgs e) private
Definition at line 173 of file ChatPage.cs.
References TGServiceInterface.ChatSetupInfo.AdminChannels, TGControlPanel.ControlPanel.AdminChannelsTextbox, TGServiceInterface.ChatSetupInfo.AdminList, TGControlPanel.ControlPanel.AdminModeSpecial, TGServiceInterface.ChatSetupInfo.AdminsAreSpecial, TGControlPanel.ControlPanel.AuthField1, TGControlPanel.ControlPanel.AuthField2, TGControlPanel.ControlPanel.ChatAdminsTextBox, TGControlPanel.ControlPanel.ChatEnabledCheckbox, TGControlPanel.ControlPanel.ChatNicknameText, TGControlPanel.ControlPanel.ChatPortSelector, TGControlPanel.ControlPanel.ChatServerText, TGServiceInterface.ChatSetupInfo.DevChannels, TGControlPanel.ControlPanel.DevChannelsTextbox, TGServiceInterface.ChatSetupInfo.Enabled, TGServiceInterface.ChatSetupInfo.GameChannels, TGControlPanel.ControlPanel.GameChannelsTextbox, TGControlPanel.ControlPanel.IRCModesComboBox, TGControlPanel.ControlPanel.LoadChatPage(), TGControlPanel.ControlPanel.ModifyingProvider, TGServiceInterface.ChatSetupInfo.WatchdogChannels, and TGControlPanel.ControlPanel.WDChannelsTextbox.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             string res = null;
             ChatSetupInfo wip = null;
             switch (ModifyingProvider)
             {
                 case ChatProvider.Discord:
                     wip = new DiscordSetupInfo()
                     {
                         BotToken = AuthField1.Text
                     };
                     break;
                 case ChatProvider.IRC:
                     wip = new IRCSetupInfo()
                     {
                         AuthMessage = AuthField2.Text,
                         AuthTarget = AuthField1.Text,
                         Nickname = ChatNicknameText.Text,
                         URL = ChatServerText.Text,
                         Port = (ushort)ChatPortSelector.Value,
                         AuthLevel = (IRCMode)IRCModesComboBox.SelectedIndex,
                     };
                     break;
                 default:
                     res = "You really shouldn't be able to read this.";
                     break;
             }
             if (res == null)
             {
                 wip.AdminChannels = new List<string>(AdminChannelsTextbox.Text.Split(Environment.NewLine.ToCharArray()));
                 wip.WatchdogChannels = new List<string>(WDChannelsTextbox.Text.Split(Environment.NewLine.ToCharArray()));
                 wip.DevChannels = new List<string>(DevChannelsTextbox.Text.Split(Environment.NewLine.ToCharArray()));
                 wip.GameChannels = new List<string>(GameChannelsTextbox.Text.Split(Environment.NewLine.ToCharArray()));
                 wip.AdminList = new List<string>(ChatAdminsTextBox.Text.Split(Environment.NewLine.ToCharArray()));
                 wip.Enabled = ChatEnabledCheckbox.Checked;
                 wip.AdminsAreSpecial = AdminModeSpecial.Checked;
                 res = Interface.GetComponent<ITGChat>().SetProviderInfo(wip);
             }
             if (res != null)
                 MessageBox.Show(res);
             LoadChatPage();
         }
void TGControlPanel.ControlPanel.ChatReconnectButton_Click (object sender, EventArgs e) private
Definition at line 113 of file ChatPage.cs.
References TGControlPanel.ControlPanel.LoadChatPage(), and TGControlPanel.ControlPanel.ModifyingProvider.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             Interface.GetComponent<ITGChat>().Reconnect(ModifyingProvider);
             LoadChatPage();
         }
void TGControlPanel.ControlPanel.ChatRefreshButton_Click (object sender, EventArgs e) private
Definition at line 108 of file ChatPage.cs.
References TGControlPanel.ControlPanel.LoadChatPage().
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             LoadChatPage();
         }
bool TGControlPanel.ControlPanel.CheckAdminWithWarning () private
Definition at line 90 of file ControlPanel.cs.
Referenced by TGControlPanel.ControlPanel.RecreateStaticButton_Click().
         {
             if (!Interface.ConnectToInstance().HasFlag(ConnectivityLevel.Administrator))
             {
                 MessageBox.Show("Only system administrators may use this command!");
                 return false;
             }
             return true;
         }
void TGControlPanel.ControlPanel.Cleanup () private
Called from Dispose(bool)
Definition at line 57 of file ControlPanel.cs.
References TGControlPanel.ControlPanel.InstancesInUse.
Referenced by TGControlPanel.ControlPanel.Dispose().
         {
             InstancesInUse.Remove(Interface.InstanceName);
             Interface.Dispose();
         }
void TGControlPanel.ControlPanel.CloneRepo () private
Definition at line 217 of file RepoPage.cs.
References TGControlPanel.ControlPanel.DoAsyncOp(), TGControlPanel.ControlPanel.RepoBranchTextBox, and TGControlPanel.ControlPanel.RepoRemoteTextBox.
Referenced by TGControlPanel.ControlPanel.CloneRepositoryButton_Click(), and TGControlPanel.ControlPanel.RecloneButton_Click().
         {
             CloneRepoURL = RepoRemoteTextBox.Text;
             CheckoutBranch = RepoBranchTextBox.Text;
             DoAsyncOp(RepoAction.Clone, String.Format("Cloning {0} branch of {1}...", CheckoutBranch, CloneRepoURL));
         }
void TGControlPanel.ControlPanel.CloneRepositoryButton_Click (object sender, EventArgs e) private
Definition at line 212 of file RepoPage.cs.
References TGControlPanel.ControlPanel.CloneRepo().
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.RepoApplyButton_Click().
         {
             CloneRepo();
         }
void TGControlPanel.ControlPanel.CompileButton_Click (object sender, EventArgs e) private
Definition at line 258 of file ServerPage.cs.
References TGServiceInterface.Components.ITGCompiler.Compile(), and TGControlPanel.ControlPanel.LoadServerPage().
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             if (!Interface.GetComponent<ITGCompiler>().Compile())
                 MessageBox.Show("Unable to start compilation!");
             LoadServerPage();
         }
void TGControlPanel.ControlPanel.CompileCancelButton_Click (object sender, EventArgs e) private
Definition at line 58 of file ServerPage.cs.
References TGControlPanel.ControlPanel.LoadServerPage().
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             var res = Interface.GetComponent<ITGCompiler>().Cancel();
             if (res != null)
                 MessageBox.Show(res);
             LoadServerPage();
         }
void TGControlPanel.ControlPanel.DiscordProviderSwitch_CheckedChanged (object sender, EventArgs e) private
Definition at line 133 of file ChatPage.cs.
References TGControlPanel.ControlPanel.DiscordProviderSwitch, TGControlPanel.ControlPanel.LoadChatPage(), and TGControlPanel.ControlPanel.ModifyingProvider.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             if (!updatingChat && DiscordProviderSwitch.Checked)
             {
                 ModifyingProvider = ChatProvider.Discord;
                 LoadChatPage();
             }
         }
override void TGControlPanel.ControlPanel.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file ControlPanel.Designer.cs.
References TGControlPanel.ControlPanel.Cleanup(), and TGControlPanel.ControlPanel.components.
Referenced by TGControlPanel.InstanceSelector.TryConnectToInstance().
         {
             if (disposing && (components != null))
             {
                 Cleanup();
                 components.Dispose();
             }
             base.Dispose(disposing);
         }
void TGControlPanel.ControlPanel.DoAsyncOp (RepoAction ra, string message) private
Definition at line 231 of file RepoPage.cs.
References TGControlPanel.ControlPanel.BackupTagsList, TGControlPanel.ControlPanel.BranchNameTitle, TGControlPanel.ControlPanel.CloneRepositoryButton, TGControlPanel.ControlPanel.CurrentRevisionLabel, TGControlPanel.ControlPanel.CurrentRevisionTitle, TGControlPanel.ControlPanel.HardReset, TGControlPanel.ControlPanel.IdentityLabel, TGControlPanel.ControlPanel.MergePRButton, TGControlPanel.ControlPanel.RecloneButton, TGControlPanel.ControlPanel.RemoteNameTitle, TGControlPanel.ControlPanel.RepoApplyButton, TGControlPanel.ControlPanel.RepoBGW, TGControlPanel.ControlPanel.RepoBranchTextBox, TGControlPanel.ControlPanel.RepoBusyCheck(), TGControlPanel.ControlPanel.RepoGenChangelogButton, TGControlPanel.ControlPanel.RepoPanel, TGControlPanel.ControlPanel.RepoProgressBar, TGControlPanel.ControlPanel.RepoProgressBarLabel, TGControlPanel.ControlPanel.RepoRefreshButton, TGControlPanel.ControlPanel.RepoRemoteTextBox, TGControlPanel.ControlPanel.ResetRemote, TGControlPanel.ControlPanel.TestMergeListLabel, TGControlPanel.ControlPanel.TestMergeListTitle, TGControlPanel.ControlPanel.TestmergeSelector, TGControlPanel.ControlPanel.TGSJsonUpdate, and TGControlPanel.ControlPanel.UpdateRepoButton.
Referenced by TGControlPanel.ControlPanel.BackupTagsList_MouseDoubleClick(), TGControlPanel.ControlPanel.CloneRepo(), TGControlPanel.ControlPanel.HardReset_Click(), TGControlPanel.ControlPanel.RepoApplyButton_Click(), TGControlPanel.ControlPanel.RepoBusyCheck(), TGControlPanel.ControlPanel.RepoGenChangelogButton_Click(), TGControlPanel.ControlPanel.ResetRemote_Click(), TGControlPanel.ControlPanel.TestMergeButton_Click(), and TGControlPanel.ControlPanel.UpdateRepoButton_Click().
         {
             if (RepoBGW.IsBusy || (ra != RepoAction.Wait && RepoBusyCheck()))
                 return;
             CurrentRevisionLabel.Visible = false;
             CurrentRevisionTitle.Visible = false;
             TestMergeListLabel.Visible = false;
             TestMergeListTitle.Visible = false;
             RepoApplyButton.Visible = false;
             UpdateRepoButton.Visible = false;
             MergePRButton.Visible = false;
             CloneRepositoryButton.Visible = false;
             RemoteNameTitle.Visible = false;
             RepoRemoteTextBox.Visible = false;
             BranchNameTitle.Visible = false;
             RepoBranchTextBox.Visible = false;
             RepoProgressBar.Visible = true;
             HardReset.Visible = false;
             IdentityLabel.Visible = false;
             TestmergeSelector.Visible = false;
             RepoGenChangelogButton.Visible = false;
             RecloneButton.Visible = false;
             ResetRemote.Visible = false;
             BackupTagsList.Visible = false;
             RepoRefreshButton.Visible = false;
             TGSJsonUpdate.Visible = false;
             RepoPanel.UseWaitCursor = true;
             RepoProgressBar.Value = 0;
             RepoProgressBar.Style = ProgressBarStyle.Marquee;
             RepoProgressBarLabel.Text = message;
             RepoProgressBarLabel.Visible = true;
             action = ra;
             repoError = null;
             RepoBGW.RunWorkerAsync();
         }
string TGControlPanel.ControlPanel.DSNTimes (int n) private
Definition at line 91 of file StaticPage.cs.
Referenced by TGControlPanel.ControlPanel.EnumeratePath().
         {
             var res = "";
             for (var I = 0; I < n; ++I)
                 res += "  ";
             return res;
         }
EnumResult TGControlPanel.ControlPanel.EnumeratePath (string path, ITGConfig config, int level) private
Definition at line 46 of file StaticPage.cs.
References TGControlPanel.ControlPanel.DSNTimes(), TGServiceInterface.Components.ITGConfig.ListStaticDirectory(), and TGControlPanel.ControlPanel.StaticFileListBox.
Referenced by TGControlPanel.ControlPanel.BuildFileList().
         {
             if (!EnumeratedPaths.Contains(path))
                 return EnumResult.NotEnumerated;
             var Enum = config.ListStaticDirectory(path, out string error, out bool unauthorized);
             if(Enum == null)
             {
                 if (unauthorized)
                     return EnumResult.Unauthorized;
                 else
                 {
                     MessageBox.Show(String.Format("Could not enumerate static path \"{0}\" error: {1}", path, error));
                     return EnumResult.Error;
                 }
             }
             foreach(var I in Enum)
             {
                 if(I[0] == '/')
                 {
                     var dir = I.Remove(0, 1);
                     var index = StaticFileListBox.Items.Add(DSNTimes(level) + dir + '/');
                     var fullpath = path + '/' + dir;
                     IndexesToPaths.Add(index, fullpath);
                     switch(EnumeratePath(fullpath, config, level + 1))
                     {
                         case EnumResult.Unauthorized:
                             StaticFileListBox.Items[index] += " (UNAUTHORIZED)";
                             IndexesToPaths[index] = null;
                             break;
                         case EnumResult.NotEnumerated:
                             StaticFileListBox.Items[index] += " (...)";
                             break;
                         case EnumResult.Error:
                             StaticFileListBox.Items[index] += " (ERROR)";
                             IndexesToPaths[index] = null;
                             break;
                     }
                     continue;
                 }
                 IndexesToPaths.Add(StaticFileListBox.Items.Add(DSNTimes(level) + I), Path.Combine(path, I));
             }
             return EnumResult.Enumerated;
         }
void TGControlPanel.ControlPanel.FullUpdateWorker_DoWork (object sender, DoWorkEventArgs e) private
Definition at line 328 of file ServerPage.cs.
References TGServiceInterface.Components.ITGCompiler.Compile(), and TGControlPanel.Program.ServiceDisconnectException().
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             try
             {
                 var Repo = Interface.GetComponent<ITGRepository>();
                 var DM = Interface.GetComponent<ITGCompiler>();
                 switch (fuAction)
                 {
                     case FullUpdateAction.Testmerge:
                         updateError = Repo.MergePullRequest(testmergePR);
                         if (updateError == null)
{
                             Repo.GenerateChangelog(out updateError);
                             updateError = DM.Compile(true) ? updateError : "Compilation failed!";
                         }
                         break;
                     case FullUpdateAction.UpdateHard:
                         updateError = Repo.Update(true);
                         if (updateError == null)
{
                             Repo.GenerateChangelog(out updateError);
                             if (updateError == null)
                                 updateError = Repo.SynchronizePush();
                             updateError = DM.Compile(true) ? updateError : "Compilation failed!";
                         }
                         break;
                     case FullUpdateAction.UpdateHardTestmerge:
                         updateError = Repo.Update(true);
                         if (updateError == null)
{
                             Repo.GenerateChangelog(out updateError);
                             if (updateError == null)
                                 updateError = Repo.SynchronizePush();
                             updateError = Repo.MergePullRequest(testmergePR);
                             if (updateError == null)
{
                                 Repo.GenerateChangelog(out updateError);
                                 updateError = DM.Compile(true) ? updateError : "Compilation failed!";
                             }
                         }
                         break;
                     case FullUpdateAction.UpdateMerge:
                         updateError = Repo.Update(false);
                         if (updateError == null)
{
                             Repo.GenerateChangelog(out updateError);
                             if (updateError == null)
                                 Repo.SynchronizePush();   //not an error 99% of the time if this fails, just a dirty tree
                             updateError = DM.Compile(true) ? updateError : "Compilation failed!";
                         }
                         break;
                     case FullUpdateAction.Reset:
                         updateError = Repo.Reset(true);
                         if (updateError == null)
{
                             Repo.GenerateChangelog(out updateError);
                             updateError = DM.Compile(true) ? updateError : "Compilation failed!";
                         }
                         break;
                 }
             }
             catch (Exception ex)
             {
                 Program.ServiceDisconnectException(ex);
             }
         }
void TGControlPanel.ControlPanel.FullUpdateWorker_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e) private
Definition at line 47 of file ServerPage.cs.
References TGControlPanel.ControlPanel.LoadServerPage(), TGControlPanel.ControlPanel.TestmergeButton, TGControlPanel.ControlPanel.UpdateHardButton, TGControlPanel.ControlPanel.UpdateMergeButton, and TGControlPanel.ControlPanel.UpdateTestmergeButton.
Referenced by TGControlPanel.ControlPanel.InitServerPage().
         {
             if (updateError != null)
                 MessageBox.Show(updateError);
             UpdateHardButton.Enabled = true;
             UpdateMergeButton.Enabled = true;
             TestmergeButton.Enabled = true;
             UpdateTestmergeButton.Enabled = true;
             LoadServerPage();
         }
void TGControlPanel.ControlPanel.HardReset_Click (object sender, EventArgs e) private
Definition at line 314 of file RepoPage.cs.
References TGControlPanel.ControlPanel.DoAsyncOp().
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             DoAsyncOp(RepoAction.Reset, "Resetting to origin branch...");
         }
void TGControlPanel.ControlPanel.InitBYONDPage () private
Definition at line 11 of file ByondPage.cs.
References TGServiceInterface.Components.ITGByond.GetVersion(), TGControlPanel.ControlPanel.LatestVersionLabel, TGControlPanel.ControlPanel.MajorVersionNumeric, TGControlPanel.ControlPanel.MinorVersionNumeric, and TGControlPanel.ControlPanel.UpdateBYONDButtons().
Referenced by TGControlPanel.ControlPanel.ControlPanel().
         {
             var BYOND = Interface.GetComponent<ITGByond>();
             var CV = BYOND.GetVersion(ByondVersion.Installed);
             if (CV == null)
                 CV = BYOND.GetVersion(ByondVersion.Staged);
             if (CV != null)
             {
                 var splits = CV.Split('.');
                 if(splits.Length == 2)
                 {
                     try
                     {
                         var Major = Convert.ToInt32(splits[0]);
                         var Minor = Convert.ToInt32(splits[1]);
                         MajorVersionNumeric.Value = Major;
                         MinorVersionNumeric.Value = Minor;
                     }
                     catch { }
                 }
             }
             var latestVer = Interface.GetComponent<ITGByond>().GetVersion(ByondVersion.Latest);
             LatestVersionLabel.Text = latestVer;
             try
             {
                 var splits = latestVer.Split('.');
                 var maj = Convert.ToInt32(splits[0]);
                 MinorVersionNumeric.Value = Convert.ToInt32(splits[1]);
                 MajorVersionNumeric.Value = maj;
             }
             catch { }
             UpdateBYONDButtons();
         }
void TGControlPanel.ControlPanel.InitializeButton_Click (object sender, EventArgs e) private
Definition at line 252 of file ServerPage.cs.
References TGServiceInterface.Components.ITGCompiler.Initialize(), and TGControlPanel.ControlPanel.LoadServerPage().
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             if (!Interface.GetComponent<ITGCompiler>().Initialize())
                 MessageBox.Show("Unable to start initialization!");
             LoadServerPage();
         }
void TGControlPanel.ControlPanel.InitializeComponent () private
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 30 of file ControlPanel.Designer.cs.
References TGControlPanel.ControlPanel.AdminChannelsTextbox, TGControlPanel.ControlPanel.AdminModeNormal, TGControlPanel.ControlPanel.AdminModeNormal_CheckedChanged(), TGControlPanel.ControlPanel.AdminModeSpecial, TGControlPanel.ControlPanel.AuthField1, TGControlPanel.ControlPanel.AuthField1Title, TGControlPanel.ControlPanel.AuthField2, TGControlPanel.ControlPanel.AuthField2Title, TGControlPanel.ControlPanel.AutostartCheckbox, TGControlPanel.ControlPanel.AutostartCheckbox_CheckedChanged(), TGControlPanel.ControlPanel.AutoUpdateCheckbox, TGControlPanel.ControlPanel.AutoUpdateCheckbox_CheckedChanged(), TGControlPanel.ControlPanel.AutoUpdateInterval, TGControlPanel.ControlPanel.AutoUpdateInterval_ValueChanged(), TGControlPanel.ControlPanel.AutoUpdateMLabel, TGControlPanel.ControlPanel.BackupTagsList, TGControlPanel.ControlPanel.BranchNameTitle, TGControlPanel.ControlPanel.BYONDPanel, TGControlPanel.ControlPanel.BYONDRefreshButton, TGControlPanel.ControlPanel.BYONDRefreshButton_Click(), TGControlPanel.ControlPanel.ChannelsTitle, TGControlPanel.ControlPanel.ChatAdminsTextBox, TGControlPanel.ControlPanel.ChatAdminsTitle, TGControlPanel.ControlPanel.ChatApplyButton, TGControlPanel.ControlPanel.ChatApplyButton_Click(), TGControlPanel.ControlPanel.ChatEnabledCheckbox, TGControlPanel.ControlPanel.ChatNicknameText, TGControlPanel.ControlPanel.ChatNicknameTitle, TGControlPanel.ControlPanel.ChatPanel, TGControlPanel.ControlPanel.ChatPortSelector, TGControlPanel.ControlPanel.ChatPortTitle, TGControlPanel.ControlPanel.ChatProviderSelectorPanel, TGControlPanel.ControlPanel.ChatProviderTitle, TGControlPanel.ControlPanel.ChatReconnectButton, TGControlPanel.ControlPanel.ChatReconnectButton_Click(), TGControlPanel.ControlPanel.ChatRefreshButton, TGControlPanel.ControlPanel.ChatRefreshButton_Click(), TGControlPanel.ControlPanel.ChatServerText, TGControlPanel.ControlPanel.ChatServerTitle, TGControlPanel.ControlPanel.ChatStatusLabel, TGControlPanel.ControlPanel.ChatStatusTitle, TGControlPanel.ControlPanel.CloneRepositoryButton, TGControlPanel.ControlPanel.CloneRepositoryButton_Click(), TGControlPanel.ControlPanel.compileButton, TGControlPanel.ControlPanel.CompileButton_Click(), TGControlPanel.ControlPanel.CompileCancelButton, TGControlPanel.ControlPanel.CompileCancelButton_Click(), TGControlPanel.ControlPanel.CompilerLabel, TGControlPanel.ControlPanel.CompilerStatusLabel, TGControlPanel.ControlPanel.CurrentRevisionLabel, TGControlPanel.ControlPanel.CurrentRevisionTitle, TGControlPanel.ControlPanel.DevChannelsTextbox, TGControlPanel.ControlPanel.DiscordProviderSwitch, TGControlPanel.ControlPanel.DiscordProviderSwitch_CheckedChanged(), TGControlPanel.ControlPanel.FullUpdateWorker, TGControlPanel.ControlPanel.FullUpdateWorker_DoWork(), TGControlPanel.ControlPanel.GameChannelsTextbox, TGControlPanel.ControlPanel.HardReset, TGControlPanel.ControlPanel.HardReset_Click(), TGControlPanel.ControlPanel.IdentityLabel, TGControlPanel.ControlPanel.initializeButton, TGControlPanel.ControlPanel.InitializeButton_Click(), TGControlPanel.ControlPanel.IRCModesComboBox, TGControlPanel.ControlPanel.IRCProviderSwitch, TGControlPanel.ControlPanel.IRCProviderSwitch_CheckedChanged(), TGControlPanel.ControlPanel.label1, TGControlPanel.ControlPanel.label2, TGControlPanel.ControlPanel.label3, TGControlPanel.ControlPanel.label4, TGControlPanel.ControlPanel.label5, TGControlPanel.ControlPanel.label6, TGControlPanel.ControlPanel.LatestVersionLabel, TGControlPanel.ControlPanel.LatestVersionTitle, TGControlPanel.ControlPanel.MajorVersionLabel, TGControlPanel.ControlPanel.MajorVersionNumeric, TGControlPanel.ControlPanel.MergePRButton, TGControlPanel.ControlPanel.MinorVersionLabel, TGControlPanel.ControlPanel.MinorVersionNumeric, TGControlPanel.ControlPanel.panel1, TGControlPanel.ControlPanel.Panels, TGControlPanel.ControlPanel.PortLabel, TGControlPanel.ControlPanel.PortSelector, TGControlPanel.ControlPanel.PortSelector_ValueChanged(), TGControlPanel.ControlPanel.projectNameText, TGControlPanel.ControlPanel.ProjectPathLabel, TGControlPanel.ControlPanel.RecloneButton, TGControlPanel.ControlPanel.RecloneButton_Click(), TGControlPanel.ControlPanel.RecreateStaticButton, TGControlPanel.ControlPanel.RecreateStaticButton_Click(), TGControlPanel.ControlPanel.RemoteNameTitle, TGControlPanel.ControlPanel.RepoApplyButton, TGControlPanel.ControlPanel.RepoApplyButton_Click(), TGControlPanel.ControlPanel.RepoBGW, TGControlPanel.ControlPanel.RepoBranchTextBox, TGControlPanel.ControlPanel.RepoGenChangelogButton, TGControlPanel.ControlPanel.RepoGenChangelogButton_Click(), TGControlPanel.ControlPanel.RepoPanel, TGControlPanel.ControlPanel.RepoProgressBar, TGControlPanel.ControlPanel.RepoProgressBarLabel, TGControlPanel.ControlPanel.RepoRefreshButton, TGControlPanel.ControlPanel.RepoRefreshButton_Click(), TGControlPanel.ControlPanel.RepoRemoteTextBox, TGControlPanel.ControlPanel.ResetRemote, TGControlPanel.ControlPanel.ResetRemote_Click(), TGControlPanel.ControlPanel.ResetTestmerge, TGControlPanel.ControlPanel.ResetTestmerge_Click(), TGControlPanel.ControlPanel.SecuritySelector, TGControlPanel.ControlPanel.SecuritySelector_SelectedIndexChanged(), TGControlPanel.ControlPanel.SecurityTitle, TGControlPanel.ControlPanel.ServerGRestartButton, TGControlPanel.ControlPanel.ServerGRestartButton_Click(), TGControlPanel.ControlPanel.ServerGStopButton, TGControlPanel.ControlPanel.ServerGStopButton_Checked(), TGControlPanel.ControlPanel.ServerPageRefreshButton, TGControlPanel.ControlPanel.ServerPageRefreshButton_Click(), TGControlPanel.ControlPanel.ServerPanel, TGControlPanel.ControlPanel.ServerPathLabel, TGControlPanel.ControlPanel.ServerPRLabel, TGControlPanel.ControlPanel.ServerRestartButton, TGControlPanel.ControlPanel.ServerRestartButton_Click(), TGControlPanel.ControlPanel.ServerStartBGW, TGControlPanel.ControlPanel.ServerStartBGW_DoWork(), TGControlPanel.ControlPanel.ServerStartButton, TGControlPanel.ControlPanel.ServerStartButton_Click(), TGControlPanel.ControlPanel.ServerStatusLabel, TGControlPanel.ControlPanel.ServerStatusTitle, TGControlPanel.ControlPanel.ServerStopButton, TGControlPanel.ControlPanel.ServerStopButton_Click(), TGControlPanel.ControlPanel.ServerTestmergeInput, TGControlPanel.ControlPanel.StagedVersionLabel, TGControlPanel.ControlPanel.StagedVersionTitle, TGControlPanel.ControlPanel.StaticFileCreateButton, TGControlPanel.ControlPanel.StaticFileCreateButton_Click(), TGControlPanel.ControlPanel.StaticFileDeleteButton, TGControlPanel.ControlPanel.StaticFileDeleteButton_Click(), TGControlPanel.ControlPanel.StaticFileDownloadButton, TGControlPanel.ControlPanel.StaticFileDownloadButton_Click(), TGControlPanel.ControlPanel.StaticFileEditTextbox, TGControlPanel.ControlPanel.StaticFileListBox, TGControlPanel.ControlPanel.StaticFileListBox_SelectedIndexChanged(), TGControlPanel.ControlPanel.StaticFileSaveButton, TGControlPanel.ControlPanel.StaticFileSaveButton_Click(), TGControlPanel.ControlPanel.StaticFilesRefreshButton, TGControlPanel.ControlPanel.StaticFilesRefreshButton_Click(), TGControlPanel.ControlPanel.StaticFileUploadButton, TGControlPanel.ControlPanel.StaticFileUploadButton_Click(), TGControlPanel.ControlPanel.StaticPanel, TGControlPanel.ControlPanel.StatusLabel, TGControlPanel.ControlPanel.TestmergeButton, TGControlPanel.ControlPanel.TestMergeButton_Click(), TGControlPanel.ControlPanel.TestmergeButton_Click(), TGControlPanel.ControlPanel.TestMergeListLabel, TGControlPanel.ControlPanel.TestMergeListTitle, TGControlPanel.ControlPanel.TestmergeSelector, TGControlPanel.ControlPanel.TGSJsonUpdate, TGControlPanel.ControlPanel.TGSJsonUpdate_Click(), TGControlPanel.ControlPanel.UpdateButton, TGControlPanel.ControlPanel.UpdateButton_Click(), TGControlPanel.ControlPanel.UpdateHardButton, TGControlPanel.ControlPanel.UpdateHardButton_Click(), TGControlPanel.ControlPanel.UpdateMergeButton, TGControlPanel.ControlPanel.UpdateMergeButton_Click(), TGControlPanel.ControlPanel.UpdateRepoButton, TGControlPanel.ControlPanel.UpdateRepoButton_Click(), TGControlPanel.ControlPanel.UpdateTestmergeButton, TGControlPanel.ControlPanel.UpdateTestmergeButton_Click(), TGControlPanel.ControlPanel.VersionLabel, TGControlPanel.ControlPanel.VersionTitle, TGControlPanel.ControlPanel.WDChannelsTextbox, TGControlPanel.ControlPanel.WebclientCheckBox, TGControlPanel.ControlPanel.WebclientCheckBox_CheckedChanged(), TGControlPanel.ControlPanel.WorldAnnounceButton, TGControlPanel.ControlPanel.WorldAnnounceButton_Click(), TGControlPanel.ControlPanel.WorldAnnounceField, and TGControlPanel.ControlPanel.WorldAnnounceLabel.
Referenced by TGControlPanel.ControlPanel.ControlPanel().
         {
             System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ControlPanel));
             this.RepoBGW = new System.ComponentModel.BackgroundWorker();
             this.FullUpdateWorker = new System.ComponentModel.BackgroundWorker();
             this.ServerStartBGW = new System.ComponentModel.BackgroundWorker();
             this.ChatPanel = new System.Windows.Forms.TabPage();
             this.label5 = new System.Windows.Forms.Label();
             this.label4 = new System.Windows.Forms.Label();
             this.label3 = new System.Windows.Forms.Label();
             this.label2 = new System.Windows.Forms.Label();
             this.IRCModesComboBox = new System.Windows.Forms.ComboBox();
             this.label1 = new System.Windows.Forms.Label();
             this.AdminChannelsTextbox = new System.Windows.Forms.TextBox();
             this.WDChannelsTextbox = new System.Windows.Forms.TextBox();
             this.GameChannelsTextbox = new System.Windows.Forms.TextBox();
             this.DevChannelsTextbox = new System.Windows.Forms.TextBox();
             this.ChatNicknameText = new System.Windows.Forms.TextBox();
             this.ChatServerText = new System.Windows.Forms.TextBox();
             this.AuthField2 = new System.Windows.Forms.TextBox();
             this.AuthField1 = new System.Windows.Forms.TextBox();
             this.ChatAdminsTextBox = new System.Windows.Forms.TextBox();
             this.ChatRefreshButton = new System.Windows.Forms.Button();
             this.ChatNicknameTitle = new System.Windows.Forms.Label();
             this.ChatPortSelector = new System.Windows.Forms.NumericUpDown();
             this.ChatPortTitle = new System.Windows.Forms.Label();
             this.ChatServerTitle = new System.Windows.Forms.Label();
             this.ChatApplyButton = new System.Windows.Forms.Button();
             this.AuthField2Title = new System.Windows.Forms.Label();
             this.AuthField1Title = new System.Windows.Forms.Label();
             this.ChatReconnectButton = new System.Windows.Forms.Button();
             this.ChatStatusLabel = new System.Windows.Forms.Label();
             this.ChatStatusTitle = new System.Windows.Forms.Label();
             this.ChatEnabledCheckbox = new System.Windows.Forms.CheckBox();
             this.ChatProviderSelectorPanel = new System.Windows.Forms.Panel();
             this.DiscordProviderSwitch = new System.Windows.Forms.RadioButton();
             this.IRCProviderSwitch = new System.Windows.Forms.RadioButton();
             this.ChatProviderTitle = new System.Windows.Forms.Label();
             this.ChannelsTitle = new System.Windows.Forms.Label();
             this.ChatAdminsTitle = new System.Windows.Forms.Label();
             this.panel1 = new System.Windows.Forms.Panel();
             this.AdminModeSpecial = new System.Windows.Forms.RadioButton();
             this.AdminModeNormal = new System.Windows.Forms.RadioButton();
             this.ServerPanel = new System.Windows.Forms.TabPage();
             this.AutoUpdateMLabel = new System.Windows.Forms.Label();
             this.AutoUpdateInterval = new System.Windows.Forms.NumericUpDown();
             this.AutoUpdateCheckbox = new System.Windows.Forms.CheckBox();
             this.ServerPageRefreshButton = new System.Windows.Forms.Button();
             this.AutostartCheckbox = new System.Windows.Forms.CheckBox();
             this.WebclientCheckBox = new System.Windows.Forms.CheckBox();
             this.WorldAnnounceButton = new System.Windows.Forms.Button();
             this.WorldAnnounceField = new System.Windows.Forms.TextBox();
             this.projectNameText = new System.Windows.Forms.TextBox();
             this.WorldAnnounceLabel = new System.Windows.Forms.Label();
             this.SecuritySelector = new System.Windows.Forms.ComboBox();
             this.SecurityTitle = new System.Windows.Forms.Label();
             this.ResetTestmerge = new System.Windows.Forms.Button();
             this.ServerPathLabel = new System.Windows.Forms.Label();
             this.CompileCancelButton = new System.Windows.Forms.Button();
             this.ProjectPathLabel = new System.Windows.Forms.Label();
             this.PortLabel = new System.Windows.Forms.Label();
             this.PortSelector = new System.Windows.Forms.NumericUpDown();
             this.ServerPRLabel = new System.Windows.Forms.Label();
             this.ServerTestmergeInput = new System.Windows.Forms.NumericUpDown();
             this.TestmergeButton = new System.Windows.Forms.Button();
             this.UpdateTestmergeButton = new System.Windows.Forms.Button();
             this.UpdateMergeButton = new System.Windows.Forms.Button();
             this.UpdateHardButton = new System.Windows.Forms.Button();
             this.ServerGRestartButton = new System.Windows.Forms.Button();
             this.ServerGStopButton = new System.Windows.Forms.CheckBox();
             this.ServerRestartButton = new System.Windows.Forms.Button();
             this.ServerStopButton = new System.Windows.Forms.Button();
             this.ServerStartButton = new System.Windows.Forms.Button();
             this.CompilerStatusLabel = new System.Windows.Forms.Label();
             this.CompilerLabel = new System.Windows.Forms.Label();
             this.compileButton = new System.Windows.Forms.Button();
             this.initializeButton = new System.Windows.Forms.Button();
             this.ServerStatusLabel = new System.Windows.Forms.Label();
             this.ServerStatusTitle = new System.Windows.Forms.Label();
             this.BYONDPanel = new System.Windows.Forms.TabPage();
             this.BYONDRefreshButton = new System.Windows.Forms.Button();
             this.LatestVersionLabel = new System.Windows.Forms.Label();
             this.LatestVersionTitle = new System.Windows.Forms.Label();
             this.StagedVersionLabel = new System.Windows.Forms.Label();
             this.StagedVersionTitle = new System.Windows.Forms.Label();
             this.StatusLabel = new System.Windows.Forms.Label();
             this.VersionLabel = new System.Windows.Forms.Label();
             this.VersionTitle = new System.Windows.Forms.Label();
             this.MinorVersionLabel = new System.Windows.Forms.Label();
             this.MajorVersionLabel = new System.Windows.Forms.Label();
             this.UpdateButton = new System.Windows.Forms.Button();
             this.MinorVersionNumeric = new System.Windows.Forms.NumericUpDown();
             this.MajorVersionNumeric = new System.Windows.Forms.NumericUpDown();
             this.RepoPanel = new System.Windows.Forms.TabPage();
             this.TGSJsonUpdate = new System.Windows.Forms.Button();
             this.RepoRefreshButton = new System.Windows.Forms.Button();
             this.BackupTagsList = new System.Windows.Forms.ListBox();
             this.ResetRemote = new System.Windows.Forms.Button();
             this.RecloneButton = new System.Windows.Forms.Button();
             this.RepoBranchTextBox = new System.Windows.Forms.TextBox();
             this.RepoRemoteTextBox = new System.Windows.Forms.TextBox();
             this.RepoGenChangelogButton = new System.Windows.Forms.Button();
             this.TestmergeSelector = new System.Windows.Forms.NumericUpDown();
             this.TestMergeListLabel = new System.Windows.Forms.ListBox();
             this.CurrentRevisionLabel = new System.Windows.Forms.Label();
             this.RepoApplyButton = new System.Windows.Forms.Button();
             this.HardReset = new System.Windows.Forms.Button();
             this.UpdateRepoButton = new System.Windows.Forms.Button();
             this.MergePRButton = new System.Windows.Forms.Button();
             this.IdentityLabel = new System.Windows.Forms.Label();
             this.TestMergeListTitle = new System.Windows.Forms.Label();
             this.RemoteNameTitle = new System.Windows.Forms.Label();
             this.BranchNameTitle = new System.Windows.Forms.Label();
             this.CurrentRevisionTitle = new System.Windows.Forms.Label();
             this.CloneRepositoryButton = new System.Windows.Forms.Button();
             this.RepoProgressBarLabel = new System.Windows.Forms.Label();
             this.RepoProgressBar = new System.Windows.Forms.ProgressBar();
             this.Panels = new System.Windows.Forms.TabControl();
             this.StaticPanel = new System.Windows.Forms.TabPage();
             this.RecreateStaticButton = new System.Windows.Forms.Button();
             this.StaticFileDownloadButton = new System.Windows.Forms.Button();
             this.StaticFilesRefreshButton = new System.Windows.Forms.Button();
             this.StaticFileUploadButton = new System.Windows.Forms.Button();
             this.StaticFileEditTextbox = new System.Windows.Forms.TextBox();
             this.StaticFileDeleteButton = new System.Windows.Forms.Button();
             this.StaticFileSaveButton = new System.Windows.Forms.Button();
             this.StaticFileCreateButton = new System.Windows.Forms.Button();
             this.label6 = new System.Windows.Forms.Label();
             this.StaticFileListBox = new System.Windows.Forms.ListBox();
             this.ChatPanel.SuspendLayout();
             ((System.ComponentModel.ISupportInitialize)(this.ChatPortSelector)).BeginInit();
             this.ChatProviderSelectorPanel.SuspendLayout();
             this.panel1.SuspendLayout();
             this.ServerPanel.SuspendLayout();
             ((System.ComponentModel.ISupportInitialize)(this.AutoUpdateInterval)).BeginInit();
             ((System.ComponentModel.ISupportInitialize)(this.PortSelector)).BeginInit();
             ((System.ComponentModel.ISupportInitialize)(this.ServerTestmergeInput)).BeginInit();
             this.BYONDPanel.SuspendLayout();
             ((System.ComponentModel.ISupportInitialize)(this.MinorVersionNumeric)).BeginInit();
             ((System.ComponentModel.ISupportInitialize)(this.MajorVersionNumeric)).BeginInit();
             this.RepoPanel.SuspendLayout();
             ((System.ComponentModel.ISupportInitialize)(this.TestmergeSelector)).BeginInit();
             this.Panels.SuspendLayout();
             this.StaticPanel.SuspendLayout();
             this.SuspendLayout();
             //
             // RepoBGW
             //
             this.RepoBGW.WorkerReportsProgress = true;
             this.RepoBGW.WorkerSupportsCancellation = true;
             //
             // FullUpdateWorker
             //
             this.FullUpdateWorker.DoWork += new System.ComponentModel.DoWorkEventHandler(this.FullUpdateWorker_DoWork);
             //
             // ServerStartBGW
             //
             this.ServerStartBGW.DoWork += new System.ComponentModel.DoWorkEventHandler(this.ServerStartBGW_DoWork);
             //
             // ChatPanel
             //
             this.ChatPanel.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(40)))), ((int)(((byte)(34)))));
             this.ChatPanel.Controls.Add(this.label5);
             this.ChatPanel.Controls.Add(this.label4);
             this.ChatPanel.Controls.Add(this.label3);
             this.ChatPanel.Controls.Add(this.label2);
             this.ChatPanel.Controls.Add(this.IRCModesComboBox);
             this.ChatPanel.Controls.Add(this.label1);
             this.ChatPanel.Controls.Add(this.AdminChannelsTextbox);
             this.ChatPanel.Controls.Add(this.WDChannelsTextbox);
             this.ChatPanel.Controls.Add(this.GameChannelsTextbox);
             this.ChatPanel.Controls.Add(this.DevChannelsTextbox);
             this.ChatPanel.Controls.Add(this.ChatNicknameText);
             this.ChatPanel.Controls.Add(this.ChatServerText);
             this.ChatPanel.Controls.Add(this.AuthField2);
             this.ChatPanel.Controls.Add(this.AuthField1);
             this.ChatPanel.Controls.Add(this.ChatAdminsTextBox);
             this.ChatPanel.Controls.Add(this.ChatRefreshButton);
             this.ChatPanel.Controls.Add(this.ChatNicknameTitle);
             this.ChatPanel.Controls.Add(this.ChatPortSelector);
             this.ChatPanel.Controls.Add(this.ChatPortTitle);
             this.ChatPanel.Controls.Add(this.ChatServerTitle);
             this.ChatPanel.Controls.Add(this.ChatApplyButton);
             this.ChatPanel.Controls.Add(this.AuthField2Title);
             this.ChatPanel.Controls.Add(this.AuthField1Title);
             this.ChatPanel.Controls.Add(this.ChatReconnectButton);
             this.ChatPanel.Controls.Add(this.ChatStatusLabel);
             this.ChatPanel.Controls.Add(this.ChatStatusTitle);
             this.ChatPanel.Controls.Add(this.ChatEnabledCheckbox);
             this.ChatPanel.Controls.Add(this.ChatProviderSelectorPanel);
             this.ChatPanel.Controls.Add(this.ChatProviderTitle);
             this.ChatPanel.Controls.Add(this.ChannelsTitle);
             this.ChatPanel.Controls.Add(this.ChatAdminsTitle);
             this.ChatPanel.Controls.Add(this.panel1);
             this.ChatPanel.Location = new System.Drawing.Point(4, 22);
             this.ChatPanel.Name = "ChatPanel";
             this.ChatPanel.Padding = new System.Windows.Forms.Padding(3);
             this.ChatPanel.Size = new System.Drawing.Size(868, 366);
             this.ChatPanel.TabIndex = 4;
             this.ChatPanel.Text = "Chat";
             //
             // label5
             //
             this.label5.AutoSize = true;
             this.label5.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.label5.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.label5.Location = new System.Drawing.Point(686, 219);
             this.label5.Name = "label5";
             this.label5.Size = new System.Drawing.Size(148, 18);
             this.label5.TabIndex = 43;
             this.label5.Text = "Game Messages:";
             this.label5.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // label4
             //
             this.label4.AutoSize = true;
             this.label4.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.label4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.label4.Location = new System.Drawing.Point(516, 219);
             this.label4.Name = "label4";
             this.label4.Size = new System.Drawing.Size(136, 18);
             this.label4.TabIndex = 42;
             this.label4.Text = "Developer Info:";
             this.label4.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // label3
             //
             this.label3.AutoSize = true;
             this.label3.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.label3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.label3.Location = new System.Drawing.Point(686, 61);
             this.label3.Name = "label3";
             this.label3.Size = new System.Drawing.Size(135, 18);
             this.label3.TabIndex = 41;
             this.label3.Text = "Administration:";
             this.label3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // label2
             //
             this.label2.AutoSize = true;
             this.label2.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.label2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.label2.Location = new System.Drawing.Point(516, 61);
             this.label2.Name = "label2";
             this.label2.Size = new System.Drawing.Size(153, 18);
             this.label2.TabIndex = 40;
             this.label2.Text = "Server Watchdog:";
             this.label2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // IRCModesComboBox
             //
             this.IRCModesComboBox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
             this.IRCModesComboBox.FormattingEnabled = true;
             this.IRCModesComboBox.Items.AddRange(new object[] {
             "Voice - +",
             "Halfop - %",
             "Op - @",
             "Owner - ~"});
             this.IRCModesComboBox.Location = new System.Drawing.Point(369, 170);
             this.IRCModesComboBox.Name = "IRCModesComboBox";
             this.IRCModesComboBox.Size = new System.Drawing.Size(141, 21);
             this.IRCModesComboBox.TabIndex = 38;
             this.IRCModesComboBox.Visible = false;
             //
             // label1
             //
             this.label1.AutoSize = true;
             this.label1.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.label1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.label1.Location = new System.Drawing.Point(30, 174);
             this.label1.Name = "label1";
             this.label1.Size = new System.Drawing.Size(110, 18);
             this.label1.TabIndex = 39;
             this.label1.Text = "Admin Auth:";
             this.label1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // AdminChannelsTextbox
             //
             this.AdminChannelsTextbox.Location = new System.Drawing.Point(689, 82);
             this.AdminChannelsTextbox.Multiline = true;
             this.AdminChannelsTextbox.Name = "AdminChannelsTextbox";
             this.AdminChannelsTextbox.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
             this.AdminChannelsTextbox.Size = new System.Drawing.Size(167, 120);
             this.AdminChannelsTextbox.TabIndex = 37;
             //
             // WDChannelsTextbox
             //
             this.WDChannelsTextbox.Location = new System.Drawing.Point(516, 82);
             this.WDChannelsTextbox.Multiline = true;
             this.WDChannelsTextbox.Name = "WDChannelsTextbox";
             this.WDChannelsTextbox.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
             this.WDChannelsTextbox.Size = new System.Drawing.Size(167, 120);
             this.WDChannelsTextbox.TabIndex = 36;
             //
             // GameChannelsTextbox
             //
             this.GameChannelsTextbox.Location = new System.Drawing.Point(689, 240);
             this.GameChannelsTextbox.Multiline = true;
             this.GameChannelsTextbox.Name = "GameChannelsTextbox";
             this.GameChannelsTextbox.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
             this.GameChannelsTextbox.Size = new System.Drawing.Size(167, 120);
             this.GameChannelsTextbox.TabIndex = 35;
             //
             // DevChannelsTextbox
             //
             this.DevChannelsTextbox.Location = new System.Drawing.Point(516, 240);
             this.DevChannelsTextbox.Multiline = true;
             this.DevChannelsTextbox.Name = "DevChannelsTextbox";
             this.DevChannelsTextbox.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
             this.DevChannelsTextbox.Size = new System.Drawing.Size(167, 120);
             this.DevChannelsTextbox.TabIndex = 34;
             //
             // ChatNicknameText
             //
             this.ChatNicknameText.Location = new System.Drawing.Point(174, 251);
             this.ChatNicknameText.Name = "ChatNicknameText";
             this.ChatNicknameText.Size = new System.Drawing.Size(151, 20);
             this.ChatNicknameText.TabIndex = 31;
             //
             // ChatServerText
             //
             this.ChatServerText.Location = new System.Drawing.Point(174, 199);
             this.ChatServerText.Name = "ChatServerText";
             this.ChatServerText.Size = new System.Drawing.Size(151, 20);
             this.ChatServerText.TabIndex = 27;
             //
             // AuthField2
             //
             this.AuthField2.Location = new System.Drawing.Point(174, 309);
             this.AuthField2.Name = "AuthField2";
             this.AuthField2.Size = new System.Drawing.Size(151, 20);
             this.AuthField2.TabIndex = 22;
             //
             // AuthField1
             //
             this.AuthField1.Location = new System.Drawing.Point(174, 283);
             this.AuthField1.Name = "AuthField1";
             this.AuthField1.Size = new System.Drawing.Size(151, 20);
             this.AuthField1.TabIndex = 21;
             //
             // ChatAdminsTextBox
             //
             this.ChatAdminsTextBox.Location = new System.Drawing.Point(369, 49);
             this.ChatAdminsTextBox.Multiline = true;
             this.ChatAdminsTextBox.Name = "ChatAdminsTextBox";
             this.ChatAdminsTextBox.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
             this.ChatAdminsTextBox.Size = new System.Drawing.Size(141, 311);
             this.ChatAdminsTextBox.TabIndex = 10;
             //
             // ChatRefreshButton
             //
             this.ChatRefreshButton.Location = new System.Drawing.Point(174, 335);
             this.ChatRefreshButton.Name = "ChatRefreshButton";
             this.ChatRefreshButton.Size = new System.Drawing.Size(112, 25);
             this.ChatRefreshButton.TabIndex = 32;
             this.ChatRefreshButton.Text = "Refresh";
             this.ChatRefreshButton.UseVisualStyleBackColor = true;
             this.ChatRefreshButton.Click += new System.EventHandler(this.ChatRefreshButton_Click);
             //
             // ChatNicknameTitle
             //
             this.ChatNicknameTitle.AutoSize = true;
             this.ChatNicknameTitle.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.ChatNicknameTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.ChatNicknameTitle.Location = new System.Drawing.Point(30, 250);
             this.ChatNicknameTitle.Name = "ChatNicknameTitle";
             this.ChatNicknameTitle.Size = new System.Drawing.Size(94, 18);
             this.ChatNicknameTitle.TabIndex = 30;
             this.ChatNicknameTitle.Text = "Nickname:";
             this.ChatNicknameTitle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // ChatPortSelector
             //
             this.ChatPortSelector.Location = new System.Drawing.Point(174, 225);
             this.ChatPortSelector.Maximum = new decimal(new int[] {
             65535,
             0,
             0,
             0});
             this.ChatPortSelector.Minimum = new decimal(new int[] {
             1,
             0,
             0,
             0});
             this.ChatPortSelector.Name = "ChatPortSelector";
             this.ChatPortSelector.Size = new System.Drawing.Size(151, 20);
             this.ChatPortSelector.TabIndex = 29;
             this.ChatPortSelector.Value = new decimal(new int[] {
             1,
             0,
             0,
             0});
             //
             // ChatPortTitle
             //
             this.ChatPortTitle.AutoSize = true;
             this.ChatPortTitle.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.ChatPortTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.ChatPortTitle.Location = new System.Drawing.Point(30, 227);
             this.ChatPortTitle.Name = "ChatPortTitle";
             this.ChatPortTitle.Size = new System.Drawing.Size(48, 18);
             this.ChatPortTitle.TabIndex = 28;
             this.ChatPortTitle.Text = "Port:";
             this.ChatPortTitle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // ChatServerTitle
             //
             this.ChatServerTitle.AutoSize = true;
             this.ChatServerTitle.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.ChatServerTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.ChatServerTitle.Location = new System.Drawing.Point(30, 201);
             this.ChatServerTitle.Name = "ChatServerTitle";
             this.ChatServerTitle.Size = new System.Drawing.Size(66, 18);
             this.ChatServerTitle.TabIndex = 26;
             this.ChatServerTitle.Text = "Server:";
             this.ChatServerTitle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // ChatApplyButton
             //
             this.ChatApplyButton.Location = new System.Drawing.Point(56, 335);
             this.ChatApplyButton.Name = "ChatApplyButton";
             this.ChatApplyButton.Size = new System.Drawing.Size(112, 25);
             this.ChatApplyButton.TabIndex = 25;
             this.ChatApplyButton.Text = "Apply";
             this.ChatApplyButton.UseVisualStyleBackColor = true;
             this.ChatApplyButton.Click += new System.EventHandler(this.ChatApplyButton_Click);
             //
             // AuthField2Title
             //
             this.AuthField2Title.AutoSize = true;
             this.AuthField2Title.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.AuthField2Title.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.AuthField2Title.Location = new System.Drawing.Point(30, 311);
             this.AuthField2Title.Name = "AuthField2Title";
             this.AuthField2Title.Size = new System.Drawing.Size(45, 18);
             this.AuthField2Title.TabIndex = 24;
             this.AuthField2Title.Text = "AF2:";
             this.AuthField2Title.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // AuthField1Title
             //
             this.AuthField1Title.AutoSize = true;
             this.AuthField1Title.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.AuthField1Title.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.AuthField1Title.Location = new System.Drawing.Point(30, 285);
             this.AuthField1Title.Name = "AuthField1Title";
             this.AuthField1Title.Size = new System.Drawing.Size(45, 18);
             this.AuthField1Title.TabIndex = 23;
             this.AuthField1Title.Text = "AF1:";
             this.AuthField1Title.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // ChatReconnectButton
             //
             this.ChatReconnectButton.Enabled = false;
             this.ChatReconnectButton.Location = new System.Drawing.Point(174, 141);
             this.ChatReconnectButton.Name = "ChatReconnectButton";
             this.ChatReconnectButton.Size = new System.Drawing.Size(112, 25);
             this.ChatReconnectButton.TabIndex = 18;
             this.ChatReconnectButton.Text = "Reconnect";
             this.ChatReconnectButton.UseVisualStyleBackColor = true;
             this.ChatReconnectButton.Click += new System.EventHandler(this.ChatReconnectButton_Click);
             //
             // ChatStatusLabel
             //
             this.ChatStatusLabel.AutoSize = true;
             this.ChatStatusLabel.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.ChatStatusLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.ChatStatusLabel.Location = new System.Drawing.Point(171, 113);
             this.ChatStatusLabel.Name = "ChatStatusLabel";
             this.ChatStatusLabel.Size = new System.Drawing.Size(82, 18);
             this.ChatStatusLabel.TabIndex = 17;
             this.ChatStatusLabel.Text = "Unknown";
             this.ChatStatusLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // ChatStatusTitle
             //
             this.ChatStatusTitle.AutoSize = true;
             this.ChatStatusTitle.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.ChatStatusTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.ChatStatusTitle.Location = new System.Drawing.Point(30, 113);
             this.ChatStatusTitle.Name = "ChatStatusTitle";
             this.ChatStatusTitle.Size = new System.Drawing.Size(112, 18);
             this.ChatStatusTitle.TabIndex = 16;
             this.ChatStatusTitle.Text = "Chat Status:";
             this.ChatStatusTitle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // ChatEnabledCheckbox
             //
             this.ChatEnabledCheckbox.AutoSize = true;
             this.ChatEnabledCheckbox.Font = new System.Drawing.Font("Verdana", 12F);
             this.ChatEnabledCheckbox.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.ChatEnabledCheckbox.Location = new System.Drawing.Point(32, 142);
             this.ChatEnabledCheckbox.Name = "ChatEnabledCheckbox";
             this.ChatEnabledCheckbox.Size = new System.Drawing.Size(136, 22);
             this.ChatEnabledCheckbox.TabIndex = 15;
             this.ChatEnabledCheckbox.Text = "Chat Enabled";
             this.ChatEnabledCheckbox.UseVisualStyleBackColor = true;
             //
             // ChatProviderSelectorPanel
             //
             this.ChatProviderSelectorPanel.Controls.Add(this.DiscordProviderSwitch);
             this.ChatProviderSelectorPanel.Controls.Add(this.IRCProviderSwitch);
             this.ChatProviderSelectorPanel.Location = new System.Drawing.Point(23, 49);
             this.ChatProviderSelectorPanel.Name = "ChatProviderSelectorPanel";
             this.ChatProviderSelectorPanel.Size = new System.Drawing.Size(302, 50);
             this.ChatProviderSelectorPanel.TabIndex = 14;
             //
             // DiscordProviderSwitch
             //
             this.DiscordProviderSwitch.AutoSize = true;
             this.DiscordProviderSwitch.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.DiscordProviderSwitch.Location = new System.Drawing.Point(220, 17);
             this.DiscordProviderSwitch.Name = "DiscordProviderSwitch";
             this.DiscordProviderSwitch.Size = new System.Drawing.Size(61, 17);
             this.DiscordProviderSwitch.TabIndex = 13;
             this.DiscordProviderSwitch.TabStop = true;
             this.DiscordProviderSwitch.Text = "Discord";
             this.DiscordProviderSwitch.UseVisualStyleBackColor = true;
             this.DiscordProviderSwitch.CheckedChanged += new System.EventHandler(this.DiscordProviderSwitch_CheckedChanged);
             //
             // IRCProviderSwitch
             //
             this.IRCProviderSwitch.AutoSize = true;
             this.IRCProviderSwitch.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.IRCProviderSwitch.Location = new System.Drawing.Point(14, 17);
             this.IRCProviderSwitch.Name = "IRCProviderSwitch";
             this.IRCProviderSwitch.Size = new System.Drawing.Size(116, 17);
             this.IRCProviderSwitch.TabIndex = 12;
             this.IRCProviderSwitch.TabStop = true;
             this.IRCProviderSwitch.Text = "Internet Relay Chat";
             this.IRCProviderSwitch.UseVisualStyleBackColor = true;
             this.IRCProviderSwitch.CheckedChanged += new System.EventHandler(this.IRCProviderSwitch_CheckedChanged);
             //
             // ChatProviderTitle
             //
             this.ChatProviderTitle.AutoSize = true;
             this.ChatProviderTitle.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.ChatProviderTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.ChatProviderTitle.Location = new System.Drawing.Point(20, 15);
             this.ChatProviderTitle.Name = "ChatProviderTitle";
             this.ChatProviderTitle.Size = new System.Drawing.Size(144, 18);
             this.ChatProviderTitle.TabIndex = 13;
             this.ChatProviderTitle.Text = "Editing Provider:";
             this.ChatProviderTitle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // ChannelsTitle
             //
             this.ChannelsTitle.AutoSize = true;
             this.ChannelsTitle.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.ChannelsTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.ChannelsTitle.Location = new System.Drawing.Point(565, 15);
             this.ChannelsTitle.Name = "ChannelsTitle";
             this.ChannelsTitle.Size = new System.Drawing.Size(234, 18);
             this.ChannelsTitle.TabIndex = 11;
             this.ChannelsTitle.Text = "Listen/Broadcast Channels:";
             this.ChannelsTitle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // ChatAdminsTitle
             //
             this.ChatAdminsTitle.AutoSize = true;
             this.ChatAdminsTitle.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.ChatAdminsTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.ChatAdminsTitle.Location = new System.Drawing.Point(366, 15);
             this.ChatAdminsTitle.Name = "ChatAdminsTitle";
             this.ChatAdminsTitle.Size = new System.Drawing.Size(75, 18);
             this.ChatAdminsTitle.TabIndex = 9;
             this.ChatAdminsTitle.Text = "Admins:";
             this.ChatAdminsTitle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // panel1
             //
             this.panel1.Controls.Add(this.AdminModeSpecial);
             this.panel1.Controls.Add(this.AdminModeNormal);
             this.panel1.Location = new System.Drawing.Point(174, 168);
             this.panel1.Name = "panel1";
             this.panel1.Size = new System.Drawing.Size(202, 25);
             this.panel1.TabIndex = 15;
             //
             // AdminModeSpecial
             //
             this.AdminModeSpecial.AutoSize = true;
             this.AdminModeSpecial.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.AdminModeSpecial.Location = new System.Drawing.Point(87, 8);
             this.AdminModeSpecial.Name = "AdminModeSpecial";
             this.AdminModeSpecial.Size = new System.Drawing.Size(94, 17);
             this.AdminModeSpecial.TabIndex = 13;
             this.AdminModeSpecial.TabStop = true;
             this.AdminModeSpecial.Text = "Channel Mode";
             this.AdminModeSpecial.UseVisualStyleBackColor = true;
             //
             // AdminModeNormal
             //
             this.AdminModeNormal.AutoSize = true;
             this.AdminModeNormal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.AdminModeNormal.Location = new System.Drawing.Point(3, 8);
             this.AdminModeNormal.Name = "AdminModeNormal";
             this.AdminModeNormal.Size = new System.Drawing.Size(78, 17);
             this.AdminModeNormal.TabIndex = 12;
             this.AdminModeNormal.TabStop = true;
             this.AdminModeNormal.Text = "Nicknames";
             this.AdminModeNormal.UseVisualStyleBackColor = true;
             this.AdminModeNormal.CheckedChanged += new System.EventHandler(this.AdminModeNormal_CheckedChanged);
             //
             // ServerPanel
             //
             this.ServerPanel.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(40)))), ((int)(((byte)(34)))));
             this.ServerPanel.Controls.Add(this.AutoUpdateMLabel);
             this.ServerPanel.Controls.Add(this.AutoUpdateInterval);
             this.ServerPanel.Controls.Add(this.AutoUpdateCheckbox);
             this.ServerPanel.Controls.Add(this.ServerPageRefreshButton);
             this.ServerPanel.Controls.Add(this.AutostartCheckbox);
             this.ServerPanel.Controls.Add(this.WebclientCheckBox);
             this.ServerPanel.Controls.Add(this.WorldAnnounceButton);
             this.ServerPanel.Controls.Add(this.WorldAnnounceField);
             this.ServerPanel.Controls.Add(this.projectNameText);
             this.ServerPanel.Controls.Add(this.WorldAnnounceLabel);
             this.ServerPanel.Controls.Add(this.SecuritySelector);
             this.ServerPanel.Controls.Add(this.SecurityTitle);
             this.ServerPanel.Controls.Add(this.ResetTestmerge);
             this.ServerPanel.Controls.Add(this.ServerPathLabel);
             this.ServerPanel.Controls.Add(this.CompileCancelButton);
             this.ServerPanel.Controls.Add(this.ProjectPathLabel);
             this.ServerPanel.Controls.Add(this.PortLabel);
             this.ServerPanel.Controls.Add(this.PortSelector);
             this.ServerPanel.Controls.Add(this.ServerPRLabel);
             this.ServerPanel.Controls.Add(this.ServerTestmergeInput);
             this.ServerPanel.Controls.Add(this.TestmergeButton);
             this.ServerPanel.Controls.Add(this.UpdateTestmergeButton);
             this.ServerPanel.Controls.Add(this.UpdateMergeButton);
             this.ServerPanel.Controls.Add(this.UpdateHardButton);
             this.ServerPanel.Controls.Add(this.ServerGRestartButton);
             this.ServerPanel.Controls.Add(this.ServerGStopButton);
             this.ServerPanel.Controls.Add(this.ServerRestartButton);
             this.ServerPanel.Controls.Add(this.ServerStopButton);
             this.ServerPanel.Controls.Add(this.ServerStartButton);
             this.ServerPanel.Controls.Add(this.CompilerStatusLabel);
             this.ServerPanel.Controls.Add(this.CompilerLabel);
             this.ServerPanel.Controls.Add(this.compileButton);
             this.ServerPanel.Controls.Add(this.initializeButton);
             this.ServerPanel.Controls.Add(this.ServerStatusLabel);
             this.ServerPanel.Controls.Add(this.ServerStatusTitle);
             this.ServerPanel.Location = new System.Drawing.Point(4, 22);
             this.ServerPanel.Name = "ServerPanel";
             this.ServerPanel.Padding = new System.Windows.Forms.Padding(3);
             this.ServerPanel.Size = new System.Drawing.Size(868, 366);
             this.ServerPanel.TabIndex = 2;
             this.ServerPanel.Text = "Server";
             //
             // AutoUpdateMLabel
             //
             this.AutoUpdateMLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
             this.AutoUpdateMLabel.AutoSize = true;
             this.AutoUpdateMLabel.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.AutoUpdateMLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.AutoUpdateMLabel.Location = new System.Drawing.Point(433, 136);
             this.AutoUpdateMLabel.Name = "AutoUpdateMLabel";
             this.AutoUpdateMLabel.Size = new System.Drawing.Size(21, 18);
             this.AutoUpdateMLabel.TabIndex = 47;
             this.AutoUpdateMLabel.Text = "M";
             this.AutoUpdateMLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             this.AutoUpdateMLabel.Visible = false;
             //
             // AutoUpdateInterval
             //
             this.AutoUpdateInterval.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
             this.AutoUpdateInterval.Location = new System.Drawing.Point(365, 135);
             this.AutoUpdateInterval.Maximum = new decimal(new int[] {
             276447231,
             23283,
             0,
             0});
             this.AutoUpdateInterval.Minimum = new decimal(new int[] {
             1,
             0,
             0,
             0});
             this.AutoUpdateInterval.Name = "AutoUpdateInterval";
             this.AutoUpdateInterval.Size = new System.Drawing.Size(62, 20);
             this.AutoUpdateInterval.TabIndex = 46;
             this.AutoUpdateInterval.Value = new decimal(new int[] {
             1,
             0,
             0,
             0});
             this.AutoUpdateInterval.Visible = false;
             this.AutoUpdateInterval.ValueChanged += new System.EventHandler(this.AutoUpdateInterval_ValueChanged);
             //
             // AutoUpdateCheckbox
             //
             this.AutoUpdateCheckbox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
             this.AutoUpdateCheckbox.AutoSize = true;
             this.AutoUpdateCheckbox.Font = new System.Drawing.Font("Verdana", 12F);
             this.AutoUpdateCheckbox.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.AutoUpdateCheckbox.Location = new System.Drawing.Point(228, 134);
             this.AutoUpdateCheckbox.Name = "AutoUpdateCheckbox";
             this.AutoUpdateCheckbox.Size = new System.Drawing.Size(131, 22);
             this.AutoUpdateCheckbox.TabIndex = 45;
             this.AutoUpdateCheckbox.Text = "Auto-Update";
             this.AutoUpdateCheckbox.UseVisualStyleBackColor = true;
             this.AutoUpdateCheckbox.Visible = false;
             this.AutoUpdateCheckbox.CheckedChanged += new System.EventHandler(this.AutoUpdateCheckbox_CheckedChanged);
             //
             // ServerPageRefreshButton
             //
             this.ServerPageRefreshButton.Anchor = System.Windows.Forms.AnchorStyles.Top;
             this.ServerPageRefreshButton.Location = new System.Drawing.Point(626, 13);
             this.ServerPageRefreshButton.Name = "ServerPageRefreshButton";
             this.ServerPageRefreshButton.Size = new System.Drawing.Size(118, 28);
             this.ServerPageRefreshButton.TabIndex = 43;
             this.ServerPageRefreshButton.Text = "Refresh";
             this.ServerPageRefreshButton.UseVisualStyleBackColor = true;
             this.ServerPageRefreshButton.Click += new System.EventHandler(this.ServerPageRefreshButton_Click);
             //
             // AutostartCheckbox
             //
             this.AutostartCheckbox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
             this.AutostartCheckbox.AutoSize = true;
             this.AutostartCheckbox.Font = new System.Drawing.Font("Verdana", 12F);
             this.AutostartCheckbox.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.AutostartCheckbox.Location = new System.Drawing.Point(754, 16);
             this.AutostartCheckbox.Name = "AutostartCheckbox";
             this.AutostartCheckbox.Size = new System.Drawing.Size(104, 22);
             this.AutostartCheckbox.TabIndex = 15;
             this.AutostartCheckbox.Text = "Autostart";
             this.AutostartCheckbox.UseVisualStyleBackColor = true;
             this.AutostartCheckbox.CheckedChanged += new System.EventHandler(this.AutostartCheckbox_CheckedChanged);
             //
             // WebclientCheckBox
             //
             this.WebclientCheckBox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
             this.WebclientCheckBox.AutoSize = true;
             this.WebclientCheckBox.Font = new System.Drawing.Font("Verdana", 12F);
             this.WebclientCheckBox.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.WebclientCheckBox.Location = new System.Drawing.Point(754, 57);
             this.WebclientCheckBox.Name = "WebclientCheckBox";
             this.WebclientCheckBox.Size = new System.Drawing.Size(108, 22);
             this.WebclientCheckBox.TabIndex = 42;
             this.WebclientCheckBox.Text = "Webclient";
             this.WebclientCheckBox.UseVisualStyleBackColor = true;
             this.WebclientCheckBox.CheckedChanged += new System.EventHandler(this.WebclientCheckBox_CheckedChanged);
             //
             // WorldAnnounceButton
             //
             this.WorldAnnounceButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
             this.WorldAnnounceButton.Location = new System.Drawing.Point(785, 133);
             this.WorldAnnounceButton.Name = "WorldAnnounceButton";
             this.WorldAnnounceButton.Size = new System.Drawing.Size(77, 20);
             this.WorldAnnounceButton.TabIndex = 41;
             this.WorldAnnounceButton.Text = "Send";
             this.WorldAnnounceButton.UseVisualStyleBackColor = true;
             this.WorldAnnounceButton.Click += new System.EventHandler(this.WorldAnnounceButton_Click);
             //
             // WorldAnnounceField
             //
             this.WorldAnnounceField.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
             this.WorldAnnounceField.Location = new System.Drawing.Point(566, 134);
             this.WorldAnnounceField.Name = "WorldAnnounceField";
             this.WorldAnnounceField.Size = new System.Drawing.Size(213, 20);
             this.WorldAnnounceField.TabIndex = 40;
             //
             // projectNameText
             //
             this.projectNameText.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
             this.projectNameText.Location = new System.Drawing.Point(566, 163);
             this.projectNameText.Name = "projectNameText";
             this.projectNameText.Size = new System.Drawing.Size(296, 20);
             this.projectNameText.TabIndex = 29;
             //
             // WorldAnnounceLabel
             //
             this.WorldAnnounceLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
             this.WorldAnnounceLabel.AutoSize = true;
             this.WorldAnnounceLabel.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.WorldAnnounceLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.WorldAnnounceLabel.Location = new System.Drawing.Point(466, 135);
             this.WorldAnnounceLabel.Name = "WorldAnnounceLabel";
             this.WorldAnnounceLabel.Size = new System.Drawing.Size(94, 18);
             this.WorldAnnounceLabel.TabIndex = 39;
             this.WorldAnnounceLabel.Text = "Announce:";
             this.WorldAnnounceLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // SecuritySelector
             //
             this.SecuritySelector.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
             this.SecuritySelector.FormattingEnabled = true;
             this.SecuritySelector.Items.AddRange(new object[] {
             "Trusted",
             "Safe",
             "Ultrasafe"});
             this.SecuritySelector.Location = new System.Drawing.Point(101, 134);
             this.SecuritySelector.Name = "SecuritySelector";
             this.SecuritySelector.Size = new System.Drawing.Size(121, 21);
             this.SecuritySelector.TabIndex = 38;
             this.SecuritySelector.SelectedIndexChanged += new System.EventHandler(this.SecuritySelector_SelectedIndexChanged);
             //
             // SecurityTitle
             //
             this.SecurityTitle.AutoSize = true;
             this.SecurityTitle.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.SecurityTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.SecurityTitle.Location = new System.Drawing.Point(15, 139);
             this.SecurityTitle.Name = "SecurityTitle";
             this.SecurityTitle.Size = new System.Drawing.Size(80, 18);
             this.SecurityTitle.TabIndex = 37;
             this.SecurityTitle.Text = "Security:";
             this.SecurityTitle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // ResetTestmerge
             //
             this.ResetTestmerge.Anchor = System.Windows.Forms.AnchorStyles.Top;
             this.ResetTestmerge.Location = new System.Drawing.Point(602, 95);
             this.ResetTestmerge.Name = "ResetTestmerge";
             this.ResetTestmerge.Size = new System.Drawing.Size(142, 28);
             this.ResetTestmerge.TabIndex = 36;
             this.ResetTestmerge.Text = "Reset and Recompile";
             this.ResetTestmerge.UseVisualStyleBackColor = true;
             this.ResetTestmerge.Click += new System.EventHandler(this.ResetTestmerge_Click);
             //
             // ServerPathLabel
             //
             this.ServerPathLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
             this.ServerPathLabel.AutoSize = true;
             this.ServerPathLabel.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.ServerPathLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.ServerPathLabel.Location = new System.Drawing.Point(15, 165);
             this.ServerPathLabel.Name = "ServerPathLabel";
             this.ServerPathLabel.Size = new System.Drawing.Size(109, 18);
             this.ServerPathLabel.TabIndex = 33;
             this.ServerPathLabel.Text = "Server Path:";
             this.ServerPathLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // CompileCancelButton
             //
             this.CompileCancelButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
             this.CompileCancelButton.Enabled = false;
             this.CompileCancelButton.Location = new System.Drawing.Point(382, 302);
             this.CompileCancelButton.Name = "CompileCancelButton";
             this.CompileCancelButton.Size = new System.Drawing.Size(69, 31);
             this.CompileCancelButton.TabIndex = 31;
             this.CompileCancelButton.Text = "Cancel";
             this.CompileCancelButton.UseVisualStyleBackColor = true;
             this.CompileCancelButton.Click += new System.EventHandler(this.CompileCancelButton_Click);
             //
             // ProjectPathLabel
             //
             this.ProjectPathLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
             this.ProjectPathLabel.AutoSize = true;
             this.ProjectPathLabel.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.ProjectPathLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.ProjectPathLabel.Location = new System.Drawing.Point(445, 165);
             this.ProjectPathLabel.Name = "ProjectPathLabel";
             this.ProjectPathLabel.Size = new System.Drawing.Size(115, 18);
             this.ProjectPathLabel.TabIndex = 30;
             this.ProjectPathLabel.Text = "Project Path:";
             this.ProjectPathLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // PortLabel
             //
             this.PortLabel.AutoSize = true;
             this.PortLabel.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.PortLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.PortLabel.Location = new System.Drawing.Point(4, 60);
             this.PortLabel.Name = "PortLabel";
             this.PortLabel.Size = new System.Drawing.Size(48, 18);
             this.PortLabel.TabIndex = 28;
             this.PortLabel.Text = "Port:";
             this.PortLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // PortSelector
             //
             this.PortSelector.Location = new System.Drawing.Point(59, 60);
             this.PortSelector.Maximum = new decimal(new int[] {
             65535,
             0,
             0,
             0});
             this.PortSelector.Minimum = new decimal(new int[] {
             1,
             0,
             0,
             0});
             this.PortSelector.Name = "PortSelector";
             this.PortSelector.Size = new System.Drawing.Size(60, 20);
             this.PortSelector.TabIndex = 27;
             this.PortSelector.Value = new decimal(new int[] {
             1,
             0,
             0,
             0});
             this.PortSelector.ValueChanged += new System.EventHandler(this.PortSelector_ValueChanged);
             //
             // ServerPRLabel
             //
             this.ServerPRLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
             this.ServerPRLabel.AutoSize = true;
             this.ServerPRLabel.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.ServerPRLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.ServerPRLabel.Location = new System.Drawing.Point(745, 101);
             this.ServerPRLabel.Name = "ServerPRLabel";
             this.ServerPRLabel.Size = new System.Drawing.Size(49, 18);
             this.ServerPRLabel.TabIndex = 26;
             this.ServerPRLabel.Text = "PR#:";
             this.ServerPRLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // ServerTestmergeInput
             //
             this.ServerTestmergeInput.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
             this.ServerTestmergeInput.Location = new System.Drawing.Point(806, 99);
             this.ServerTestmergeInput.Maximum = new decimal(new int[] {
             1000000,
             0,
             0,
             0});
             this.ServerTestmergeInput.Name = "ServerTestmergeInput";
             this.ServerTestmergeInput.Size = new System.Drawing.Size(62, 20);
             this.ServerTestmergeInput.TabIndex = 25;
             //
             // TestmergeButton
             //
             this.TestmergeButton.Anchor = System.Windows.Forms.AnchorStyles.Top;
             this.TestmergeButton.Location = new System.Drawing.Point(454, 95);
             this.TestmergeButton.Name = "TestmergeButton";
             this.TestmergeButton.Size = new System.Drawing.Size(142, 28);
             this.TestmergeButton.TabIndex = 24;
             this.TestmergeButton.Text = "Testmerge";
             this.TestmergeButton.UseVisualStyleBackColor = true;
             this.TestmergeButton.Click += new System.EventHandler(this.TestmergeButton_Click);
             //
             // UpdateTestmergeButton
             //
             this.UpdateTestmergeButton.Anchor = System.Windows.Forms.AnchorStyles.Top;
             this.UpdateTestmergeButton.Location = new System.Drawing.Point(306, 95);
             this.UpdateTestmergeButton.Name = "UpdateTestmergeButton";
             this.UpdateTestmergeButton.Size = new System.Drawing.Size(142, 28);
             this.UpdateTestmergeButton.TabIndex = 23;
             this.UpdateTestmergeButton.Text = "Update and Testmerge";
             this.UpdateTestmergeButton.UseVisualStyleBackColor = true;
             this.UpdateTestmergeButton.Click += new System.EventHandler(this.UpdateTestmergeButton_Click);
             //
             // UpdateMergeButton
             //
             this.UpdateMergeButton.Anchor = System.Windows.Forms.AnchorStyles.Top;
             this.UpdateMergeButton.Location = new System.Drawing.Point(158, 95);
             this.UpdateMergeButton.Name = "UpdateMergeButton";
             this.UpdateMergeButton.Size = new System.Drawing.Size(142, 28);
             this.UpdateMergeButton.TabIndex = 22;
             this.UpdateMergeButton.Text = "Update (KeepTestmerge)";
             this.UpdateMergeButton.UseVisualStyleBackColor = true;
             this.UpdateMergeButton.Click += new System.EventHandler(this.UpdateMergeButton_Click);
             //
             // UpdateHardButton
             //
             this.UpdateHardButton.Anchor = System.Windows.Forms.AnchorStyles.Top;
             this.UpdateHardButton.Location = new System.Drawing.Point(7, 95);
             this.UpdateHardButton.Name = "UpdateHardButton";
             this.UpdateHardButton.Size = new System.Drawing.Size(145, 28);
             this.UpdateHardButton.TabIndex = 21;
             this.UpdateHardButton.Text = "Update (Reset Testmerge)";
             this.UpdateHardButton.UseVisualStyleBackColor = true;
             this.UpdateHardButton.Click += new System.EventHandler(this.UpdateHardButton_Click);
             //
             // ServerGRestartButton
             //
             this.ServerGRestartButton.Anchor = System.Windows.Forms.AnchorStyles.Top;
             this.ServerGRestartButton.Location = new System.Drawing.Point(626, 54);
             this.ServerGRestartButton.Name = "ServerGRestartButton";
             this.ServerGRestartButton.Size = new System.Drawing.Size(118, 28);
             this.ServerGRestartButton.TabIndex = 20;
             this.ServerGRestartButton.Text = "Graceful Restart";
             this.ServerGRestartButton.UseVisualStyleBackColor = true;
             this.ServerGRestartButton.Click += new System.EventHandler(this.ServerGRestartButton_Click);
             //
             // ServerGStopButton
             //
             this.ServerGStopButton.Anchor = System.Windows.Forms.AnchorStyles.Top;
             this.ServerGStopButton.Appearance = System.Windows.Forms.Appearance.Button;
             this.ServerGStopButton.Location = new System.Drawing.Point(502, 54);
             this.ServerGStopButton.Name = "ServerGStopButton";
             this.ServerGStopButton.Size = new System.Drawing.Size(118, 28);
             this.ServerGStopButton.TabIndex = 19;
             this.ServerGStopButton.Text = "Graceful Stop";
             this.ServerGStopButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             this.ServerGStopButton.UseVisualStyleBackColor = true;
             this.ServerGStopButton.CheckedChanged += new System.EventHandler(this.ServerGStopButton_Checked);
             //
             // ServerRestartButton
             //
             this.ServerRestartButton.Anchor = System.Windows.Forms.AnchorStyles.Top;
             this.ServerRestartButton.Location = new System.Drawing.Point(378, 54);
             this.ServerRestartButton.Name = "ServerRestartButton";
             this.ServerRestartButton.Size = new System.Drawing.Size(118, 28);
             this.ServerRestartButton.TabIndex = 18;
             this.ServerRestartButton.Text = "Restart";
             this.ServerRestartButton.UseVisualStyleBackColor = true;
             this.ServerRestartButton.Click += new System.EventHandler(this.ServerRestartButton_Click);
             //
             // ServerStopButton
             //
             this.ServerStopButton.Anchor = System.Windows.Forms.AnchorStyles.Top;
             this.ServerStopButton.Location = new System.Drawing.Point(254, 54);
             this.ServerStopButton.Name = "ServerStopButton";
             this.ServerStopButton.Size = new System.Drawing.Size(118, 28);
             this.ServerStopButton.TabIndex = 17;
             this.ServerStopButton.Text = "Stop";
             this.ServerStopButton.UseVisualStyleBackColor = true;
             this.ServerStopButton.Click += new System.EventHandler(this.ServerStopButton_Click);
             //
             // ServerStartButton
             //
             this.ServerStartButton.Anchor = System.Windows.Forms.AnchorStyles.Top;
             this.ServerStartButton.Location = new System.Drawing.Point(130, 54);
             this.ServerStartButton.Name = "ServerStartButton";
             this.ServerStartButton.Size = new System.Drawing.Size(118, 28);
             this.ServerStartButton.TabIndex = 16;
             this.ServerStartButton.Text = "Start";
             this.ServerStartButton.UseVisualStyleBackColor = true;
             this.ServerStartButton.Click += new System.EventHandler(this.ServerStartButton_Click);
             //
             // CompilerStatusLabel
             //
             this.CompilerStatusLabel.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)
             | System.Windows.Forms.AnchorStyles.Right)));
             this.CompilerStatusLabel.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.CompilerStatusLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.CompilerStatusLabel.Location = new System.Drawing.Point(110, 271);
             this.CompilerStatusLabel.Name = "CompilerStatusLabel";
             this.CompilerStatusLabel.Size = new System.Drawing.Size(618, 28);
             this.CompilerStatusLabel.TabIndex = 14;
             this.CompilerStatusLabel.Text = "Idle";
             this.CompilerStatusLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // CompilerLabel
             //
             this.CompilerLabel.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)
             | System.Windows.Forms.AnchorStyles.Right)));
             this.CompilerLabel.AutoSize = true;
             this.CompilerLabel.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.CompilerLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.CompilerLabel.Location = new System.Drawing.Point(379, 203);
             this.CompilerLabel.Name = "CompilerLabel";
             this.CompilerLabel.Size = new System.Drawing.Size(80, 18);
             this.CompilerLabel.TabIndex = 13;
             this.CompilerLabel.Text = "Compiler";
             this.CompilerLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // compileButton
             //
             this.compileButton.Anchor = System.Windows.Forms.AnchorStyles.Bottom;
             this.compileButton.Enabled = false;
             this.compileButton.Location = new System.Drawing.Point(456, 240);
             this.compileButton.Name = "compileButton";
             this.compileButton.Size = new System.Drawing.Size(159, 28);
             this.compileButton.TabIndex = 12;
             this.compileButton.Text = "Copy from Repo and Compile";
             this.compileButton.UseVisualStyleBackColor = true;
             this.compileButton.Click += new System.EventHandler(this.CompileButton_Click);
             //
             // initializeButton
             //
             this.initializeButton.Anchor = System.Windows.Forms.AnchorStyles.Bottom;
             this.initializeButton.Enabled = false;
             this.initializeButton.Location = new System.Drawing.Point(219, 240);
             this.initializeButton.Name = "initializeButton";
             this.initializeButton.Size = new System.Drawing.Size(159, 28);
             this.initializeButton.TabIndex = 11;
             this.initializeButton.Text = "Initialize Game Folders";
             this.initializeButton.UseVisualStyleBackColor = true;
             this.initializeButton.Click += new System.EventHandler(this.InitializeButton_Click);
             //
             // ServerStatusLabel
             //
             this.ServerStatusLabel.AutoSize = true;
             this.ServerStatusLabel.Font = new System.Drawing.Font("Verdana", 10F);
             this.ServerStatusLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.ServerStatusLabel.Location = new System.Drawing.Point(136, 19);
             this.ServerStatusLabel.Name = "ServerStatusLabel";
             this.ServerStatusLabel.Size = new System.Drawing.Size(73, 17);
             this.ServerStatusLabel.TabIndex = 9;
             this.ServerStatusLabel.Text = "Unknown";
             this.ServerStatusLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // ServerStatusTitle
             //
             this.ServerStatusTitle.AutoSize = true;
             this.ServerStatusTitle.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.ServerStatusTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.ServerStatusTitle.Location = new System.Drawing.Point(15, 17);
             this.ServerStatusTitle.Name = "ServerStatusTitle";
             this.ServerStatusTitle.Size = new System.Drawing.Size(125, 18);
             this.ServerStatusTitle.TabIndex = 8;
             this.ServerStatusTitle.Text = "Server Status:";
             this.ServerStatusTitle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // BYONDPanel
             //
             this.BYONDPanel.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(40)))), ((int)(((byte)(34)))));
             this.BYONDPanel.Controls.Add(this.BYONDRefreshButton);
             this.BYONDPanel.Controls.Add(this.LatestVersionLabel);
             this.BYONDPanel.Controls.Add(this.LatestVersionTitle);
             this.BYONDPanel.Controls.Add(this.StagedVersionLabel);
             this.BYONDPanel.Controls.Add(this.StagedVersionTitle);
             this.BYONDPanel.Controls.Add(this.StatusLabel);
             this.BYONDPanel.Controls.Add(this.VersionLabel);
             this.BYONDPanel.Controls.Add(this.VersionTitle);
             this.BYONDPanel.Controls.Add(this.MinorVersionLabel);
             this.BYONDPanel.Controls.Add(this.MajorVersionLabel);
             this.BYONDPanel.Controls.Add(this.UpdateButton);
             this.BYONDPanel.Controls.Add(this.MinorVersionNumeric);
             this.BYONDPanel.Controls.Add(this.MajorVersionNumeric);
             this.BYONDPanel.Location = new System.Drawing.Point(4, 22);
             this.BYONDPanel.Name = "BYONDPanel";
             this.BYONDPanel.Size = new System.Drawing.Size(868, 366);
             this.BYONDPanel.TabIndex = 1;
             this.BYONDPanel.Text = "BYOND";
             //
             // BYONDRefreshButton
             //
             this.BYONDRefreshButton.Location = new System.Drawing.Point(462, 252);
             this.BYONDRefreshButton.Name = "BYONDRefreshButton";
             this.BYONDRefreshButton.Size = new System.Drawing.Size(118, 28);
             this.BYONDRefreshButton.TabIndex = 14;
             this.BYONDRefreshButton.Text = "Refresh";
             this.BYONDRefreshButton.UseVisualStyleBackColor = true;
             this.BYONDRefreshButton.Click += new System.EventHandler(this.BYONDRefreshButton_Click);
             //
             // LatestVersionLabel
             //
             this.LatestVersionLabel.AutoSize = true;
             this.LatestVersionLabel.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.LatestVersionLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.LatestVersionLabel.Location = new System.Drawing.Point(425, 93);
             this.LatestVersionLabel.Name = "LatestVersionLabel";
             this.LatestVersionLabel.Size = new System.Drawing.Size(82, 18);
             this.LatestVersionLabel.TabIndex = 13;
             this.LatestVersionLabel.Text = "Unknown";
             this.LatestVersionLabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
             //
             // LatestVersionTitle
             //
             this.LatestVersionTitle.AutoSize = true;
             this.LatestVersionTitle.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.LatestVersionTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.LatestVersionTitle.Location = new System.Drawing.Point(286, 93);
             this.LatestVersionTitle.Name = "LatestVersionTitle";
             this.LatestVersionTitle.Size = new System.Drawing.Size(133, 18);
             this.LatestVersionTitle.TabIndex = 12;
             this.LatestVersionTitle.Text = "Latest Version:";
             this.LatestVersionTitle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // StagedVersionLabel
             //
             this.StagedVersionLabel.AutoSize = true;
             this.StagedVersionLabel.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.StagedVersionLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.StagedVersionLabel.Location = new System.Drawing.Point(425, 131);
             this.StagedVersionLabel.Name = "StagedVersionLabel";
             this.StagedVersionLabel.Size = new System.Drawing.Size(82, 18);
             this.StagedVersionLabel.TabIndex = 11;
             this.StagedVersionLabel.Text = "Unknown";
             this.StagedVersionLabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
             this.StagedVersionLabel.Visible = false;
             //
             // StagedVersionTitle
             //
             this.StagedVersionTitle.AutoSize = true;
             this.StagedVersionTitle.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.StagedVersionTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.StagedVersionTitle.Location = new System.Drawing.Point(282, 131);
             this.StagedVersionTitle.Name = "StagedVersionTitle";
             this.StagedVersionTitle.Size = new System.Drawing.Size(137, 18);
             this.StagedVersionTitle.TabIndex = 10;
             this.StagedVersionTitle.Text = "Staged version:";
             this.StagedVersionTitle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             this.StagedVersionTitle.Visible = false;
             //
             // StatusLabel
             //
             this.StatusLabel.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.StatusLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.StatusLabel.Location = new System.Drawing.Point(303, 320);
             this.StatusLabel.Name = "StatusLabel";
             this.StatusLabel.Size = new System.Drawing.Size(253, 37);
             this.StatusLabel.TabIndex = 9;
             this.StatusLabel.Text = "Idle";
             this.StatusLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // VersionLabel
             //
             this.VersionLabel.AutoSize = true;
             this.VersionLabel.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.VersionLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.VersionLabel.Location = new System.Drawing.Point(425, 56);
             this.VersionLabel.Name = "VersionLabel";
             this.VersionLabel.Size = new System.Drawing.Size(82, 18);
             this.VersionLabel.TabIndex = 8;
             this.VersionLabel.Text = "Unknown";
             this.VersionLabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
             //
             // VersionTitle
             //
             this.VersionTitle.AutoSize = true;
             this.VersionTitle.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.VersionTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.VersionTitle.Location = new System.Drawing.Point(265, 56);
             this.VersionTitle.Name = "VersionTitle";
             this.VersionTitle.Size = new System.Drawing.Size(154, 18);
             this.VersionTitle.TabIndex = 7;
             this.VersionTitle.Text = "Installed Version:";
             this.VersionTitle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // MinorVersionLabel
             //
             this.MinorVersionLabel.AutoSize = true;
             this.MinorVersionLabel.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.MinorVersionLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.MinorVersionLabel.Location = new System.Drawing.Point(521, 180);
             this.MinorVersionLabel.Name = "MinorVersionLabel";
             this.MinorVersionLabel.Size = new System.Drawing.Size(59, 18);
             this.MinorVersionLabel.TabIndex = 6;
             this.MinorVersionLabel.Text = "Minor:";
             this.MinorVersionLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // MajorVersionLabel
             //
             this.MajorVersionLabel.AutoSize = true;
             this.MajorVersionLabel.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.MajorVersionLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.MajorVersionLabel.Location = new System.Drawing.Point(276, 180);
             this.MajorVersionLabel.Name = "MajorVersionLabel";
             this.MajorVersionLabel.Size = new System.Drawing.Size(60, 18);
             this.MajorVersionLabel.TabIndex = 5;
             this.MajorVersionLabel.Text = "Major:";
             this.MajorVersionLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // UpdateButton
             //
             this.UpdateButton.Location = new System.Drawing.Point(268, 252);
             this.UpdateButton.Name = "UpdateButton";
             this.UpdateButton.Size = new System.Drawing.Size(118, 28);
             this.UpdateButton.TabIndex = 3;
             this.UpdateButton.Text = "Update";
             this.UpdateButton.UseVisualStyleBackColor = true;
             this.UpdateButton.Click += new System.EventHandler(this.UpdateButton_Click);
             //
             // MinorVersionNumeric
             //
             this.MinorVersionNumeric.Location = new System.Drawing.Point(490, 210);
             this.MinorVersionNumeric.Maximum = new decimal(new int[] {
             10000,
             0,
             0,
             0});
             this.MinorVersionNumeric.Name = "MinorVersionNumeric";
             this.MinorVersionNumeric.Size = new System.Drawing.Size(120, 20);
             this.MinorVersionNumeric.TabIndex = 2;
             this.MinorVersionNumeric.Value = new decimal(new int[] {
             1381,
             0,
             0,
             0});
             //
             // MajorVersionNumeric
             //
             this.MajorVersionNumeric.Location = new System.Drawing.Point(245, 210);
             this.MajorVersionNumeric.Maximum = new decimal(new int[] {
             1000,
             0,
             0,
             0});
             this.MajorVersionNumeric.Name = "MajorVersionNumeric";
             this.MajorVersionNumeric.Size = new System.Drawing.Size(120, 20);
             this.MajorVersionNumeric.TabIndex = 1;
             this.MajorVersionNumeric.Value = new decimal(new int[] {
             511,
             0,
             0,
             0});
             //
             // RepoPanel
             //
             this.RepoPanel.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(40)))), ((int)(((byte)(34)))));
             this.RepoPanel.Controls.Add(this.TGSJsonUpdate);
             this.RepoPanel.Controls.Add(this.RepoRefreshButton);
             this.RepoPanel.Controls.Add(this.BackupTagsList);
             this.RepoPanel.Controls.Add(this.ResetRemote);
             this.RepoPanel.Controls.Add(this.RecloneButton);
             this.RepoPanel.Controls.Add(this.RepoBranchTextBox);
             this.RepoPanel.Controls.Add(this.RepoRemoteTextBox);
             this.RepoPanel.Controls.Add(this.RepoGenChangelogButton);
             this.RepoPanel.Controls.Add(this.TestmergeSelector);
             this.RepoPanel.Controls.Add(this.TestMergeListLabel);
             this.RepoPanel.Controls.Add(this.CurrentRevisionLabel);
             this.RepoPanel.Controls.Add(this.RepoApplyButton);
             this.RepoPanel.Controls.Add(this.HardReset);
             this.RepoPanel.Controls.Add(this.UpdateRepoButton);
             this.RepoPanel.Controls.Add(this.MergePRButton);
             this.RepoPanel.Controls.Add(this.IdentityLabel);
             this.RepoPanel.Controls.Add(this.TestMergeListTitle);
             this.RepoPanel.Controls.Add(this.RemoteNameTitle);
             this.RepoPanel.Controls.Add(this.BranchNameTitle);
             this.RepoPanel.Controls.Add(this.CurrentRevisionTitle);
             this.RepoPanel.Controls.Add(this.CloneRepositoryButton);
             this.RepoPanel.Controls.Add(this.RepoProgressBarLabel);
             this.RepoPanel.Controls.Add(this.RepoProgressBar);
             this.RepoPanel.Location = new System.Drawing.Point(4, 22);
             this.RepoPanel.Name = "RepoPanel";
             this.RepoPanel.Padding = new System.Windows.Forms.Padding(3);
             this.RepoPanel.Size = new System.Drawing.Size(868, 366);
             this.RepoPanel.TabIndex = 0;
             this.RepoPanel.Text = "Repository";
             //
             // TGSJsonUpdate
             //
             this.TGSJsonUpdate.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
             this.TGSJsonUpdate.Location = new System.Drawing.Point(722, 212);
             this.TGSJsonUpdate.Name = "TGSJsonUpdate";
             this.TGSJsonUpdate.Size = new System.Drawing.Size(140, 29);
             this.TGSJsonUpdate.TabIndex = 36;
             this.TGSJsonUpdate.Text = "Update TGS3.json";
             this.TGSJsonUpdate.UseVisualStyleBackColor = true;
             this.TGSJsonUpdate.Visible = false;
             this.TGSJsonUpdate.Click += new System.EventHandler(this.TGSJsonUpdate_Click);
             //
             // RepoRefreshButton
             //
             this.RepoRefreshButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
             this.RepoRefreshButton.Location = new System.Drawing.Point(722, 296);
             this.RepoRefreshButton.Name = "RepoRefreshButton";
             this.RepoRefreshButton.Size = new System.Drawing.Size(140, 29);
             this.RepoRefreshButton.TabIndex = 35;
             this.RepoRefreshButton.Text = "Refresh";
             this.RepoRefreshButton.UseVisualStyleBackColor = true;
             this.RepoRefreshButton.Visible = false;
             this.RepoRefreshButton.Click += new System.EventHandler(this.RepoRefreshButton_Click);
             //
             // BackupTagsList
             //
             this.BackupTagsList.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
             this.BackupTagsList.Items.AddRange(new object[] {
             "None"});
             this.BackupTagsList.Location = new System.Drawing.Point(122, 142);
             this.BackupTagsList.Name = "BackupTagsList";
             this.BackupTagsList.ScrollAlwaysVisible = true;
             this.BackupTagsList.Size = new System.Drawing.Size(535, 95);
             this.BackupTagsList.TabIndex = 34;
             this.BackupTagsList.Visible = false;
             //
             // ResetRemote
             //
             this.ResetRemote.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
             this.ResetRemote.Location = new System.Drawing.Point(722, 81);
             this.ResetRemote.Name = "ResetRemote";
             this.ResetRemote.Size = new System.Drawing.Size(140, 29);
             this.ResetRemote.TabIndex = 33;
             this.ResetRemote.Text = "Reset To Remote";
             this.ResetRemote.UseVisualStyleBackColor = true;
             this.ResetRemote.Visible = false;
             this.ResetRemote.Click += new System.EventHandler(this.ResetRemote_Click);
             //
             // RecloneButton
             //
             this.RecloneButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
             this.RecloneButton.Location = new System.Drawing.Point(722, 247);
             this.RecloneButton.Name = "RecloneButton";
             this.RecloneButton.Size = new System.Drawing.Size(140, 29);
             this.RecloneButton.TabIndex = 32;
             this.RecloneButton.Text = "Reclone";
             this.RecloneButton.UseVisualStyleBackColor = true;
             this.RecloneButton.Visible = false;
             this.RecloneButton.Click += new System.EventHandler(this.RecloneButton_Click);
             //
             // RepoBranchTextBox
             //
             this.RepoBranchTextBox.Location = new System.Drawing.Point(122, 70);
             this.RepoBranchTextBox.Name = "RepoBranchTextBox";
             this.RepoBranchTextBox.Size = new System.Drawing.Size(535, 20);
             this.RepoBranchTextBox.TabIndex = 15;
             this.RepoBranchTextBox.Visible = false;
             //
             // RepoRemoteTextBox
             //
             this.RepoRemoteTextBox.Location = new System.Drawing.Point(122, 44);
             this.RepoRemoteTextBox.Name = "RepoRemoteTextBox";
             this.RepoRemoteTextBox.Size = new System.Drawing.Size(535, 20);
             this.RepoRemoteTextBox.TabIndex = 14;
             this.RepoRemoteTextBox.Visible = false;
             //
             // RepoGenChangelogButton
             //
             this.RepoGenChangelogButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
             this.RepoGenChangelogButton.Location = new System.Drawing.Point(722, 177);
             this.RepoGenChangelogButton.Name = "RepoGenChangelogButton";
             this.RepoGenChangelogButton.Size = new System.Drawing.Size(140, 29);
             this.RepoGenChangelogButton.TabIndex = 27;
             this.RepoGenChangelogButton.Text = "Generate Changelog";
             this.RepoGenChangelogButton.UseVisualStyleBackColor = true;
             this.RepoGenChangelogButton.Visible = false;
             this.RepoGenChangelogButton.Click += new System.EventHandler(this.RepoGenChangelogButton_Click);
             //
             // TestmergeSelector
             //
             this.TestmergeSelector.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
             this.TestmergeSelector.Location = new System.Drawing.Point(722, 151);
             this.TestmergeSelector.Maximum = new decimal(new int[] {
             1000000,
             0,
             0,
             0});
             this.TestmergeSelector.Name = "TestmergeSelector";
             this.TestmergeSelector.Size = new System.Drawing.Size(140, 20);
             this.TestmergeSelector.TabIndex = 22;
             this.TestmergeSelector.Visible = false;
             //
             // TestMergeListLabel
             //
             this.TestMergeListLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
             this.TestMergeListLabel.HorizontalScrollbar = true;
             this.TestMergeListLabel.Items.AddRange(new object[] {
             "None"});
             this.TestMergeListLabel.Location = new System.Drawing.Point(122, 260);
             this.TestMergeListLabel.Name = "TestMergeListLabel";
             this.TestMergeListLabel.ScrollAlwaysVisible = true;
             this.TestMergeListLabel.Size = new System.Drawing.Size(535, 95);
             this.TestMergeListLabel.TabIndex = 21;
             this.TestMergeListLabel.Visible = false;
             //
             // CurrentRevisionLabel
             //
             this.CurrentRevisionLabel.AutoSize = true;
             this.CurrentRevisionLabel.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.CurrentRevisionLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.CurrentRevisionLabel.Location = new System.Drawing.Point(162, 14);
             this.CurrentRevisionLabel.Name = "CurrentRevisionLabel";
             this.CurrentRevisionLabel.Size = new System.Drawing.Size(82, 18);
             this.CurrentRevisionLabel.TabIndex = 20;
             this.CurrentRevisionLabel.Text = "Unknown";
             this.CurrentRevisionLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             this.CurrentRevisionLabel.Visible = false;
             //
             // RepoApplyButton
             //
             this.RepoApplyButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
             this.RepoApplyButton.Location = new System.Drawing.Point(722, 331);
             this.RepoApplyButton.Name = "RepoApplyButton";
             this.RepoApplyButton.Size = new System.Drawing.Size(140, 29);
             this.RepoApplyButton.TabIndex = 17;
             this.RepoApplyButton.Text = "Apply Changes";
             this.RepoApplyButton.UseVisualStyleBackColor = true;
             this.RepoApplyButton.Visible = false;
             this.RepoApplyButton.Click += new System.EventHandler(this.RepoApplyButton_Click);
             //
             // HardReset
             //
             this.HardReset.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
             this.HardReset.Location = new System.Drawing.Point(722, 46);
             this.HardReset.Name = "HardReset";
             this.HardReset.Size = new System.Drawing.Size(140, 29);
             this.HardReset.TabIndex = 13;
             this.HardReset.Text = "Reset To Origin Branch";
             this.HardReset.UseVisualStyleBackColor = true;
             this.HardReset.Visible = false;
             this.HardReset.Click += new System.EventHandler(this.HardReset_Click);
             //
             // UpdateRepoButton
             //
             this.UpdateRepoButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
             this.UpdateRepoButton.Location = new System.Drawing.Point(722, 11);
             this.UpdateRepoButton.Name = "UpdateRepoButton";
             this.UpdateRepoButton.Size = new System.Drawing.Size(140, 29);
             this.UpdateRepoButton.TabIndex = 12;
             this.UpdateRepoButton.Text = "Merge from Remote";
             this.UpdateRepoButton.UseVisualStyleBackColor = true;
             this.UpdateRepoButton.Visible = false;
             this.UpdateRepoButton.Click += new System.EventHandler(this.UpdateRepoButton_Click);
             //
             // MergePRButton
             //
             this.MergePRButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
             this.MergePRButton.Location = new System.Drawing.Point(722, 116);
             this.MergePRButton.Name = "MergePRButton";
             this.MergePRButton.Size = new System.Drawing.Size(140, 29);
             this.MergePRButton.TabIndex = 11;
             this.MergePRButton.Text = "Merge Pull Request";
             this.MergePRButton.UseVisualStyleBackColor = true;
             this.MergePRButton.Visible = false;
             this.MergePRButton.Click += new System.EventHandler(this.TestMergeButton_Click);
             //
             // IdentityLabel
             //
             this.IdentityLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
             this.IdentityLabel.AutoSize = true;
             this.IdentityLabel.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.IdentityLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.IdentityLabel.Location = new System.Drawing.Point(6, 142);
             this.IdentityLabel.Name = "IdentityLabel";
             this.IdentityLabel.Size = new System.Drawing.Size(116, 18);
             this.IdentityLabel.TabIndex = 8;
             this.IdentityLabel.Text = "Backup Tags:";
             this.IdentityLabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
             this.IdentityLabel.Visible = false;
             //
             // TestMergeListTitle
             //
             this.TestMergeListTitle.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
             this.TestMergeListTitle.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.TestMergeListTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.TestMergeListTitle.Location = new System.Drawing.Point(6, 260);
             this.TestMergeListTitle.Name = "TestMergeListTitle";
             this.TestMergeListTitle.Size = new System.Drawing.Size(110, 41);
             this.TestMergeListTitle.TabIndex = 6;
             this.TestMergeListTitle.Text = "Active Test Merges:";
             this.TestMergeListTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
             this.TestMergeListTitle.Visible = false;
             //
             // RemoteNameTitle
             //
             this.RemoteNameTitle.AutoSize = true;
             this.RemoteNameTitle.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.RemoteNameTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.RemoteNameTitle.Location = new System.Drawing.Point(6, 46);
             this.RemoteNameTitle.Name = "RemoteNameTitle";
             this.RemoteNameTitle.Size = new System.Drawing.Size(78, 18);
             this.RemoteNameTitle.TabIndex = 5;
             this.RemoteNameTitle.Text = "Remote:";
             this.RemoteNameTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
             this.RemoteNameTitle.Visible = false;
             //
             // BranchNameTitle
             //
             this.BranchNameTitle.AutoSize = true;
             this.BranchNameTitle.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.BranchNameTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.BranchNameTitle.Location = new System.Drawing.Point(6, 72);
             this.BranchNameTitle.Name = "BranchNameTitle";
             this.BranchNameTitle.Size = new System.Drawing.Size(70, 18);
             this.BranchNameTitle.TabIndex = 4;
             this.BranchNameTitle.Text = "Branch:";
             this.BranchNameTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
             this.BranchNameTitle.Visible = false;
             //
             // CurrentRevisionTitle
             //
             this.CurrentRevisionTitle.AutoSize = true;
             this.CurrentRevisionTitle.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.CurrentRevisionTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.CurrentRevisionTitle.Location = new System.Drawing.Point(6, 14);
             this.CurrentRevisionTitle.Name = "CurrentRevisionTitle";
             this.CurrentRevisionTitle.Size = new System.Drawing.Size(150, 18);
             this.CurrentRevisionTitle.TabIndex = 3;
             this.CurrentRevisionTitle.Text = "Current Revision:";
             this.CurrentRevisionTitle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             this.CurrentRevisionTitle.Visible = false;
             //
             // CloneRepositoryButton
             //
             this.CloneRepositoryButton.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
             | System.Windows.Forms.AnchorStyles.Left)
             | System.Windows.Forms.AnchorStyles.Right)));
             this.CloneRepositoryButton.Location = new System.Drawing.Point(311, 191);
             this.CloneRepositoryButton.Name = "CloneRepositoryButton";
             this.CloneRepositoryButton.Size = new System.Drawing.Size(229, 34);
             this.CloneRepositoryButton.TabIndex = 2;
             this.CloneRepositoryButton.Text = "Clone Repository";
             this.CloneRepositoryButton.UseVisualStyleBackColor = true;
             this.CloneRepositoryButton.Visible = false;
             this.CloneRepositoryButton.Click += new System.EventHandler(this.CloneRepositoryButton_Click);
             //
             // RepoProgressBarLabel
             //
             this.RepoProgressBarLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
             | System.Windows.Forms.AnchorStyles.Left)
             | System.Windows.Forms.AnchorStyles.Right)));
             this.RepoProgressBarLabel.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.RepoProgressBarLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.RepoProgressBarLabel.Location = new System.Drawing.Point(184, 142);
             this.RepoProgressBarLabel.Name = "RepoProgressBarLabel";
             this.RepoProgressBarLabel.Size = new System.Drawing.Size(499, 46);
             this.RepoProgressBarLabel.TabIndex = 1;
             this.RepoProgressBarLabel.Text = "Searching for Repository...";
             this.RepoProgressBarLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // RepoProgressBar
             //
             this.RepoProgressBar.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
             | System.Windows.Forms.AnchorStyles.Left)
             | System.Windows.Forms.AnchorStyles.Right)));
             this.RepoProgressBar.Location = new System.Drawing.Point(184, 191);
             this.RepoProgressBar.Name = "RepoProgressBar";
             this.RepoProgressBar.Size = new System.Drawing.Size(499, 23);
             this.RepoProgressBar.Style = System.Windows.Forms.ProgressBarStyle.Marquee;
             this.RepoProgressBar.TabIndex = 0;
             //
             // Panels
             //
             this.Panels.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
             | System.Windows.Forms.AnchorStyles.Left)
             | System.Windows.Forms.AnchorStyles.Right)));
             this.Panels.Controls.Add(this.RepoPanel);
             this.Panels.Controls.Add(this.BYONDPanel);
             this.Panels.Controls.Add(this.ServerPanel);
             this.Panels.Controls.Add(this.ChatPanel);
             this.Panels.Controls.Add(this.StaticPanel);
             this.Panels.Cursor = System.Windows.Forms.Cursors.Default;
             this.Panels.Location = new System.Drawing.Point(12, 12);
             this.Panels.Name = "Panels";
             this.Panels.SelectedIndex = 0;
             this.Panels.Size = new System.Drawing.Size(876, 392);
             this.Panels.TabIndex = 3;
             //
             // StaticPanel
             //
             this.StaticPanel.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(40)))), ((int)(((byte)(34)))));
             this.StaticPanel.Controls.Add(this.RecreateStaticButton);
             this.StaticPanel.Controls.Add(this.StaticFileDownloadButton);
             this.StaticPanel.Controls.Add(this.StaticFilesRefreshButton);
             this.StaticPanel.Controls.Add(this.StaticFileUploadButton);
             this.StaticPanel.Controls.Add(this.StaticFileEditTextbox);
             this.StaticPanel.Controls.Add(this.StaticFileDeleteButton);
             this.StaticPanel.Controls.Add(this.StaticFileSaveButton);
             this.StaticPanel.Controls.Add(this.StaticFileCreateButton);
             this.StaticPanel.Controls.Add(this.label6);
             this.StaticPanel.Controls.Add(this.StaticFileListBox);
             this.StaticPanel.Location = new System.Drawing.Point(4, 22);
             this.StaticPanel.Name = "StaticPanel";
             this.StaticPanel.Padding = new System.Windows.Forms.Padding(3);
             this.StaticPanel.Size = new System.Drawing.Size(868, 366);
             this.StaticPanel.TabIndex = 5;
             this.StaticPanel.Text = "Static Files";
             //
             // RecreateStaticButton
             //
             this.RecreateStaticButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
             this.RecreateStaticButton.Location = new System.Drawing.Point(471, 6);
             this.RecreateStaticButton.Name = "RecreateStaticButton";
             this.RecreateStaticButton.Size = new System.Drawing.Size(144, 22);
             this.RecreateStaticButton.TabIndex = 33;
             this.RecreateStaticButton.Text = "Recreate Static Directory";
             this.RecreateStaticButton.UseVisualStyleBackColor = true;
             this.RecreateStaticButton.Click += new System.EventHandler(this.RecreateStaticButton_Click);
             //
             // StaticFileDownloadButton
             //
             this.StaticFileDownloadButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
             this.StaticFileDownloadButton.Location = new System.Drawing.Point(296, 6);
             this.StaticFileDownloadButton.Name = "StaticFileDownloadButton";
             this.StaticFileDownloadButton.Size = new System.Drawing.Size(71, 22);
             this.StaticFileDownloadButton.TabIndex = 32;
             this.StaticFileDownloadButton.Text = "Download";
             this.StaticFileDownloadButton.UseVisualStyleBackColor = true;
             this.StaticFileDownloadButton.Click += new System.EventHandler(this.StaticFileDownloadButton_Click);
             //
             // StaticFilesRefreshButton
             //
             this.StaticFilesRefreshButton.Location = new System.Drawing.Point(65, 6);
             this.StaticFilesRefreshButton.Name = "StaticFilesRefreshButton";
             this.StaticFilesRefreshButton.Size = new System.Drawing.Size(71, 22);
             this.StaticFilesRefreshButton.TabIndex = 31;
             this.StaticFilesRefreshButton.Text = "Refresh";
             this.StaticFilesRefreshButton.UseVisualStyleBackColor = true;
             this.StaticFilesRefreshButton.Click += new System.EventHandler(this.StaticFilesRefreshButton_Click);
             //
             // StaticFileUploadButton
             //
             this.StaticFileUploadButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
             this.StaticFileUploadButton.Location = new System.Drawing.Point(219, 6);
             this.StaticFileUploadButton.Name = "StaticFileUploadButton";
             this.StaticFileUploadButton.Size = new System.Drawing.Size(71, 22);
             this.StaticFileUploadButton.TabIndex = 30;
             this.StaticFileUploadButton.Text = "Upload";
             this.StaticFileUploadButton.UseVisualStyleBackColor = true;
             this.StaticFileUploadButton.Click += new System.EventHandler(this.StaticFileUploadButton_Click);
             //
             // StaticFileEditTextbox
             //
             this.StaticFileEditTextbox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
             this.StaticFileEditTextbox.Location = new System.Drawing.Point(219, 31);
             this.StaticFileEditTextbox.Multiline = true;
             this.StaticFileEditTextbox.Name = "StaticFileEditTextbox";
             this.StaticFileEditTextbox.ScrollBars = System.Windows.Forms.ScrollBars.Both;
             this.StaticFileEditTextbox.Size = new System.Drawing.Size(643, 329);
             this.StaticFileEditTextbox.TabIndex = 29;
             //
             // StaticFileDeleteButton
             //
             this.StaticFileDeleteButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
             this.StaticFileDeleteButton.Location = new System.Drawing.Point(714, 6);
             this.StaticFileDeleteButton.Name = "StaticFileDeleteButton";
             this.StaticFileDeleteButton.Size = new System.Drawing.Size(71, 22);
             this.StaticFileDeleteButton.TabIndex = 28;
             this.StaticFileDeleteButton.Text = "Delete";
             this.StaticFileDeleteButton.UseVisualStyleBackColor = true;
             this.StaticFileDeleteButton.Click += new System.EventHandler(this.StaticFileDeleteButton_Click);
             //
             // StaticFileSaveButton
             //
             this.StaticFileSaveButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
             this.StaticFileSaveButton.Location = new System.Drawing.Point(791, 6);
             this.StaticFileSaveButton.Name = "StaticFileSaveButton";
             this.StaticFileSaveButton.Size = new System.Drawing.Size(71, 22);
             this.StaticFileSaveButton.TabIndex = 27;
             this.StaticFileSaveButton.Text = "Save";
             this.StaticFileSaveButton.UseVisualStyleBackColor = true;
             this.StaticFileSaveButton.Click += new System.EventHandler(this.StaticFileSaveButton_Click);
             //
             // StaticFileCreateButton
             //
             this.StaticFileCreateButton.Location = new System.Drawing.Point(142, 6);
             this.StaticFileCreateButton.Name = "StaticFileCreateButton";
             this.StaticFileCreateButton.Size = new System.Drawing.Size(71, 22);
             this.StaticFileCreateButton.TabIndex = 26;
             this.StaticFileCreateButton.Text = "Add";
             this.StaticFileCreateButton.UseVisualStyleBackColor = true;
             this.StaticFileCreateButton.Click += new System.EventHandler(this.StaticFileCreateButton_Click);
             //
             // label6
             //
             this.label6.AutoSize = true;
             this.label6.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.label6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.label6.Location = new System.Drawing.Point(6, 10);
             this.label6.Name = "label6";
             this.label6.Size = new System.Drawing.Size(53, 18);
             this.label6.TabIndex = 14;
             this.label6.Text = "Files:";
             this.label6.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // StaticFileListBox
             //
             this.StaticFileListBox.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
             | System.Windows.Forms.AnchorStyles.Left)));
             this.StaticFileListBox.FormattingEnabled = true;
             this.StaticFileListBox.HorizontalScrollbar = true;
             this.StaticFileListBox.Location = new System.Drawing.Point(6, 31);
             this.StaticFileListBox.Name = "StaticFileListBox";
             this.StaticFileListBox.Size = new System.Drawing.Size(207, 329);
             this.StaticFileListBox.TabIndex = 0;
             this.StaticFileListBox.SelectedIndexChanged += new System.EventHandler(this.StaticFileListBox_SelectedIndexChanged);
             //
             // Main
             //
             this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
             this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
             this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(40)))), ((int)(((byte)(34)))));
             this.ClientSize = new System.Drawing.Size(900, 415);
             this.Controls.Add(this.Panels);
             this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
             this.Name = "Main";
             this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
             this.Text = "/tg/station 13 Server Control Panel";
             this.ChatPanel.ResumeLayout(false);
             this.ChatPanel.PerformLayout();
             ((System.ComponentModel.ISupportInitialize)(this.ChatPortSelector)).EndInit();
             this.ChatProviderSelectorPanel.ResumeLayout(false);
             this.ChatProviderSelectorPanel.PerformLayout();
             this.panel1.ResumeLayout(false);
             this.panel1.PerformLayout();
             this.ServerPanel.ResumeLayout(false);
             this.ServerPanel.PerformLayout();
             ((System.ComponentModel.ISupportInitialize)(this.AutoUpdateInterval)).EndInit();
             ((System.ComponentModel.ISupportInitialize)(this.PortSelector)).EndInit();
             ((System.ComponentModel.ISupportInitialize)(this.ServerTestmergeInput)).EndInit();
             this.BYONDPanel.ResumeLayout(false);
             this.BYONDPanel.PerformLayout();
             ((System.ComponentModel.ISupportInitialize)(this.MinorVersionNumeric)).EndInit();
             ((System.ComponentModel.ISupportInitialize)(this.MajorVersionNumeric)).EndInit();
             this.RepoPanel.ResumeLayout(false);
             this.RepoPanel.PerformLayout();
             ((System.ComponentModel.ISupportInitialize)(this.TestmergeSelector)).EndInit();
             this.Panels.ResumeLayout(false);
             this.StaticPanel.ResumeLayout(false);
             this.StaticPanel.PerformLayout();
             this.ResumeLayout(false);
         }
void TGControlPanel.ControlPanel.InitRepoPage () private
Definition at line 30 of file RepoPage.cs.
References TGControlPanel.ControlPanel.BackupTagsList, TGControlPanel.ControlPanel.BackupTagsList_MouseDoubleClick(), TGControlPanel.ControlPanel.PopulateRepoFields(), TGControlPanel.ControlPanel.RepoBGW, TGControlPanel.ControlPanel.RepoBGW_DoWork(), TGControlPanel.ControlPanel.RepoBGW_ProgressChanged(), and TGControlPanel.ControlPanel.RepoBGW_RunWorkerCompleted().
Referenced by TGControlPanel.ControlPanel.ControlPanel().
         {
             RepoBGW.ProgressChanged += RepoBGW_ProgressChanged;
             RepoBGW.RunWorkerCompleted += RepoBGW_RunWorkerCompleted;
             RepoBGW.DoWork += RepoBGW_DoWork;
             BackupTagsList.MouseDoubleClick += BackupTagsList_MouseDoubleClick;
             PopulateRepoFields();
         }
void TGControlPanel.ControlPanel.InitServerPage () private
Definition at line 25 of file ServerPage.cs.
References TGControlPanel.ControlPanel.FullUpdateWorker, TGControlPanel.ControlPanel.FullUpdateWorker_RunWorkerCompleted(), TGControlPanel.ControlPanel.LoadServerPage(), TGControlPanel.ControlPanel.projectNameText, TGControlPanel.ControlPanel.ProjectNameText_KeyDown(), TGControlPanel.ControlPanel.ProjectNameText_LostFocus(), TGControlPanel.ControlPanel.ServerStartBGW, and TGControlPanel.ControlPanel.ServerStartBGW_RunWorkerCompleted().
Referenced by TGControlPanel.ControlPanel.ControlPanel().
         {
             LoadServerPage();
             FullUpdateWorker.RunWorkerCompleted += FullUpdateWorker_RunWorkerCompleted;
             projectNameText.LostFocus += ProjectNameText_LostFocus;
             projectNameText.KeyDown += ProjectNameText_KeyDown;
             ServerStartBGW.RunWorkerCompleted += ServerStartBGW_RunWorkerCompleted;
         }
void TGControlPanel.ControlPanel.InitStaticPage () private
Definition at line 24 of file StaticPage.cs.
References TGControlPanel.ControlPanel.BuildFileList(), TGServiceInterface.Interface.ConnectToInstance(), and TGControlPanel.ControlPanel.RecreateStaticButton.
Referenced by TGControlPanel.ControlPanel.ControlPanel().
         {
             if(!Interface.ConnectToInstance().HasFlag(ConnectivityLevel.Administrator))
                 RecreateStaticButton.Visible = false;
             BuildFileList();
         }
void TGControlPanel.ControlPanel.IRCProviderSwitch_CheckedChanged (object sender, EventArgs e) private
Definition at line 142 of file ChatPage.cs.
References TGControlPanel.ControlPanel.IRCProviderSwitch, TGControlPanel.ControlPanel.LoadChatPage(), and TGControlPanel.ControlPanel.ModifyingProvider.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             if (!updatingChat && IRCProviderSwitch.Checked)
             {
                 ModifyingProvider = ChatProvider.IRC;
                 LoadChatPage();
             }
         }
void TGControlPanel.ControlPanel.LoadChatPage () private
Definition at line 19 of file ChatPage.cs.
References TGControlPanel.ControlPanel.AdminChannelsTextbox, TGControlPanel.ControlPanel.AdminModeNormal, TGControlPanel.ControlPanel.AdminModeSpecial, TGControlPanel.ControlPanel.AssignListToTextbox(), TGControlPanel.ControlPanel.AuthField1, TGControlPanel.ControlPanel.AuthField1Title, TGControlPanel.ControlPanel.AuthField2, TGControlPanel.ControlPanel.AuthField2Title, TGControlPanel.ControlPanel.ChannelsTitle, TGControlPanel.ControlPanel.ChatAdminsTextBox, TGControlPanel.ControlPanel.ChatAdminsTitle, TGControlPanel.ControlPanel.ChatEnabledCheckbox, TGControlPanel.ControlPanel.ChatNicknameText, TGControlPanel.ControlPanel.ChatNicknameTitle, TGControlPanel.ControlPanel.ChatPortSelector, TGControlPanel.ControlPanel.ChatPortTitle, TGControlPanel.ControlPanel.ChatReconnectButton, TGControlPanel.ControlPanel.ChatServerText, TGControlPanel.ControlPanel.ChatServerTitle, TGControlPanel.ControlPanel.ChatStatusLabel, TGControlPanel.ControlPanel.DevChannelsTextbox, TGControlPanel.ControlPanel.DiscordProviderSwitch, TGControlPanel.ControlPanel.GameChannelsTextbox, TGServiceInterface.IRC, TGControlPanel.ControlPanel.IRCModesComboBox, TGControlPanel.ControlPanel.IRCProviderSwitch, TGControlPanel.ControlPanel.ModifyingProvider, TGServiceInterface.Components.ITGChat.ProviderInfos(), and TGControlPanel.ControlPanel.WDChannelsTextbox.
Referenced by TGControlPanel.ControlPanel.ChatApplyButton_Click(), TGControlPanel.ControlPanel.ChatReconnectButton_Click(), TGControlPanel.ControlPanel.ChatRefreshButton_Click(), TGControlPanel.ControlPanel.ControlPanel(), TGControlPanel.ControlPanel.DiscordProviderSwitch_CheckedChanged(), TGControlPanel.ControlPanel.IRCProviderSwitch_CheckedChanged(), TGControlPanel.ControlPanel.Panels_SelectedIndexChanged(), and TGControlPanel.ControlPanel.SetAdminsAreSpecial().
         {
             updatingChat = true;
             var Chat = Interface.GetComponent<ITGChat>();
             var PI = Chat.ProviderInfos()[(int)ModifyingProvider];
             ChatAdminsTextBox.Visible = true;
             IRCModesComboBox.Visible = false;
             switch (ModifyingProvider)
             {
                 case ChatProvider.Discord:
                     var DPI = new DiscordSetupInfo(PI);
                     DiscordProviderSwitch.Select();
                     AuthField1.Text = DPI.BotToken; //it's invisible so whatever
                     AuthField1Title.Text = "Bot Token:";
                     AuthField2.Visible = false;
                     AuthField2Title.Visible = false;
                     ChatServerText.Visible = false;
                     ChatPortSelector.Visible = false;
                     ChatServerTitle.Visible = false;
                     ChatPortTitle.Visible = false;
                     ChatNicknameText.Visible = false;
                     ChatNicknameTitle.Visible = false;
                     ChatAdminsTitle.Text = String.Format("Admin {0} IDs:", DPI.AdminsAreSpecial ? "Role" : "User");
                     ChannelsTitle.Text = "Broadcast/Listening Channel IDs:";
                     AdminModeNormal.Text = "User IDs";
                     AdminModeSpecial.Text = "Role IDs";
                     break;
                 case ChatProvider.IRC:
                     var IRC = new IRCSetupInfo(PI);
                     IRCProviderSwitch.Select();
                     AuthField1.Text = IRC.AuthTarget;
                     AuthField2.Text = IRC.AuthMessage;
                     AuthField2.Visible = true;
                     AuthField2Title.Visible = true;
                     AuthField1Title.Text = "Auth Target:";
                     AuthField2Title.Text = "Auth Message:";
                     ChatServerText.Visible = true;
                     ChatPortSelector.Visible = true;
                     ChatServerTitle.Visible = true;
                     ChatPortTitle.Visible = true;
                     ChatServerText.Text = IRC.URL;
                     ChatPortSelector.Value = IRC.Port;
                     ChatNicknameText.Visible = true;
                     ChatNicknameTitle.Visible = true;
                     ChatNicknameText.Text = IRC.Nickname;
                     ChatAdminsTitle.Text = String.Format("Admin {0}:", IRC.AdminsAreSpecial ? "Req Mode" : "Nicknames");
                     ChannelsTitle.Text = "Broadcast/Listening Channels:";
                     AdminModeNormal.Text = "Nicknames";
                     AdminModeSpecial.Text = "Channel Mode";
                     if (IRC.AdminsAreSpecial)
                     {
                         ChatAdminsTextBox.Visible = false;
                         IRCModesComboBox.Visible = true;
                         IRCModesComboBox.SelectedIndex = (int)IRC.AuthLevel;
                     }
                     break;
                 default:
                     Properties.Settings.Default.LastChatProvider = (int)ChatProvider.IRC;
                     LoadChatPage();
                     return;
             }
             AdminModeNormal.Checked = !PI.AdminsAreSpecial;
             AdminModeSpecial.Checked = PI.AdminsAreSpecial;
             ChatEnabledCheckbox.Checked = PI.Enabled;
             if (!PI.Enabled)
                 ChatStatusLabel.Text = "Disabled";
             else if (Chat.Connected(ModifyingProvider))
                 ChatStatusLabel.Text = "Connected";
             else
                 ChatStatusLabel.Text = "Disconnected";
             ChatReconnectButton.Enabled = PI.Enabled;
             AssignListToTextbox(PI.AdminList, ChatAdminsTextBox);
             AssignListToTextbox(PI.WatchdogChannels, WDChannelsTextbox);
             AssignListToTextbox(PI.AdminChannels, AdminChannelsTextbox);
             AssignListToTextbox(PI.DevChannels, DevChannelsTextbox);
             AssignListToTextbox(PI.GameChannels, GameChannelsTextbox);
             updatingChat = false;
         }
void TGControlPanel.ControlPanel.LoadServerPage () private
Definition at line 66 of file ServerPage.cs.
References TGControlPanel.ControlPanel.AutostartCheckbox, TGControlPanel.ControlPanel.AutoUpdateCheckbox, TGControlPanel.ControlPanel.AutoUpdateInterval, TGControlPanel.ControlPanel.AutoUpdateMLabel, TGControlPanel.ControlPanel.compileButton, TGControlPanel.ControlPanel.CompileCancelButton, TGControlPanel.ControlPanel.CompilerLabel, TGControlPanel.ControlPanel.CompilerStatusLabel, TGControlPanel.ControlPanel.initializeButton, TGServiceInterface.Online, TGControlPanel.ControlPanel.PortLabel, TGControlPanel.ControlPanel.PortSelector, TGControlPanel.ControlPanel.projectNameText, TGControlPanel.ControlPanel.ProjectPathLabel, TGControlPanel.ControlPanel.ResetTestmerge, TGControlPanel.ControlPanel.SecuritySelector, TGControlPanel.ControlPanel.ServerGRestartButton, TGControlPanel.ControlPanel.ServerGStopButton, TGControlPanel.ControlPanel.ServerPathLabel, TGControlPanel.ControlPanel.ServerPRLabel, TGControlPanel.ControlPanel.ServerRestartButton, TGControlPanel.ControlPanel.ServerStartButton, TGControlPanel.ControlPanel.ServerStatusLabel, TGControlPanel.ControlPanel.ServerStopButton, TGControlPanel.ControlPanel.ServerTestmergeInput, TGControlPanel.ControlPanel.TestmergeButton, TGControlPanel.ControlPanel.UpdateHardButton, TGControlPanel.ControlPanel.UpdateMergeButton, TGControlPanel.ControlPanel.UpdateTestmergeButton, TGControlPanel.ControlPanel.WebclientCheckBox, TGControlPanel.ControlPanel.WorldAnnounceButton, TGControlPanel.ControlPanel.WorldAnnounceField, and TGControlPanel.ControlPanel.WorldAnnounceLabel.
Referenced by TGControlPanel.ControlPanel.CompileButton_Click(), TGControlPanel.ControlPanel.CompileCancelButton_Click(), TGControlPanel.ControlPanel.FullUpdateWorker_RunWorkerCompleted(), TGControlPanel.ControlPanel.InitializeButton_Click(), TGControlPanel.ControlPanel.InitServerPage(), TGControlPanel.ControlPanel.Panels_SelectedIndexChanged(), TGControlPanel.ControlPanel.ServerGStopButton_Checked(), TGControlPanel.ControlPanel.ServerPageRefreshButton_Click(), and TGControlPanel.ControlPanel.ServerStartBGW_RunWorkerCompleted().
         {
             var RepoExists = Interface.GetComponent<ITGRepository>().Exists();
             compileButton.Visible = RepoExists;
             AutoUpdateCheckbox.Visible = RepoExists;
             initializeButton.Visible = RepoExists;
             AutostartCheckbox.Visible = RepoExists;
             WebclientCheckBox.Visible = RepoExists;
             PortSelector.Visible = RepoExists;
             projectNameText.Visible = RepoExists;
             CompilerStatusLabel.Visible = RepoExists;
             CompileCancelButton.Visible = RepoExists;
             CompilerLabel.Visible = RepoExists;
             ProjectPathLabel.Visible = RepoExists;
             ServerPRLabel.Visible = RepoExists;
             ServerGStopButton.Visible = RepoExists;
             ServerStartButton.Visible = RepoExists;
             ServerGRestartButton.Visible = RepoExists;
             ServerRestartButton.Visible = RepoExists;
             PortLabel.Visible = RepoExists;
             ServerStopButton.Visible = RepoExists;
             TestmergeButton.Visible = RepoExists;
             ServerTestmergeInput.Visible = RepoExists;
             UpdateHardButton.Visible = RepoExists;
             UpdateMergeButton.Visible = RepoExists;
             UpdateTestmergeButton.Visible = RepoExists;
             ResetTestmerge.Visible = RepoExists;
             WorldAnnounceField.Visible = RepoExists;
             WorldAnnounceButton.Visible = RepoExists;
             WorldAnnounceLabel.Visible = RepoExists;
             if (updatingFields)
                 return;
             var DM = Interface.GetComponent<ITGCompiler>();
             var DD = Interface.GetComponent<ITGDreamDaemon>();
             var Config = Interface.GetComponent<ITGConfig>();
             var Repo = Interface.GetComponent<ITGRepository>();
             try
             {
                 updatingFields = true;
                 ServerPathLabel.Text = "Server Path: " + Interface.GetComponent<ITGInstance>().ServerDirectory();
                 SecuritySelector.SelectedIndex = (int)DD.SecurityLevel();
                 if (!RepoExists)
                     return;
                 var interval = Repo.AutoUpdateInterval();
                 var interval_not_zero = interval != 0;
                 AutoUpdateCheckbox.Checked = interval_not_zero;
                 AutoUpdateInterval.Visible = interval_not_zero;
                 AutoUpdateMLabel.Visible = interval_not_zero;
                 if (interval_not_zero)
                     AutoUpdateInterval.Value = interval;
                 var DaeStat = DD.DaemonStatus();
                 var Online = DaeStat == DreamDaemonStatus.Online;
                 ServerStartButton.Enabled = !Online;
                 ServerGStopButton.Enabled = Online;
                 ServerGRestartButton.Enabled = Online;
                 ServerStopButton.Enabled = Online;
                 ServerRestartButton.Enabled = Online;
                 switch (DaeStat)
                 {
                     case DreamDaemonStatus.HardRebooting:
                         ServerStatusLabel.Text = "REBOOTING";
                         break;
                     case DreamDaemonStatus.Offline:
                         ServerStatusLabel.Text = "OFFLINE";
                         break;
                     case DreamDaemonStatus.Online:
                         ServerStatusLabel.Text = "ONLINE";
                         var pc = DD.PlayerCount();
                         if (pc != -1)
                             ServerStatusLabel.Text += " (" + pc + " players)";
                         break;
                 }
                 ServerGStopButton.Checked = DD.ShutdownInProgress();
                 AutostartCheckbox.Checked = DD.Autostart();
                 WebclientCheckBox.Checked = DD.Webclient();
                 if (!PortSelector.Focused)
                     PortSelector.Value = DD.Port();
                 if (!projectNameText.Focused)
                     projectNameText.Text = DM.ProjectName();
                 switch (DM.GetStatus())
                 {
                     case CompilerStatus.Compiling:
                         CompilerStatusLabel.Text = "Compiling...";
                         compileButton.Enabled = false;
                         initializeButton.Enabled = false;
                         CompileCancelButton.Enabled = true;
                         break;
                     case CompilerStatus.Initializing:
                         CompilerStatusLabel.Text = "Initializing...";
                         compileButton.Enabled = false;
                         initializeButton.Enabled = false;
                         CompileCancelButton.Enabled = false;
                         break;
                     case CompilerStatus.Initialized:
                         CompilerStatusLabel.Text = "Idle";
                         initializeButton.Enabled = true;
                         compileButton.Enabled = true;
                         CompileCancelButton.Enabled = false;
                         break;
                     case CompilerStatus.Uninitialized:
                         CompilerStatusLabel.Text = "Uninitialized";
                         compileButton.Enabled = false;
                         initializeButton.Enabled = true;
                         CompileCancelButton.Enabled = false;
                         break;
                     default:
                         CompilerStatusLabel.Text = "Unknown!";
                         initializeButton.Enabled = true;
                         compileButton.Enabled = true;
                         CompileCancelButton.Enabled = true;
                         break;
                 }
                 var error = DM.CompileError();
                 if (error != null)
                     MessageBox.Show("Error: " + error);
             }
             finally
             {
                 updatingFields = false;
             }
         }
void TGControlPanel.ControlPanel.Main_Resize (object sender, EventArgs e) private
Definition at line 63 of file ControlPanel.cs.
References TGControlPanel.ControlPanel.Panels.
         {
             Panels.Location = new Point(10, 10);
             Panels.Width = ClientSize.Width - 20;
             Panels.Height = ClientSize.Height - 20;
         }
void TGControlPanel.ControlPanel.Panels_SelectedIndexChanged (object sender, EventArgs e) private
Definition at line 70 of file ControlPanel.cs.
References TGControlPanel.ControlPanel.LoadChatPage(), TGControlPanel.ControlPanel.LoadServerPage(), TGControlPanel.ControlPanel.Panels, TGControlPanel.ControlPanel.PopulateRepoFields(), and TGControlPanel.ControlPanel.UpdateBYONDButtons().
Referenced by TGControlPanel.ControlPanel.ControlPanel().
         {
             switch (Panels.SelectedIndex)
             {
                 case 0: //repo
                     PopulateRepoFields();
                     break;
                 case 1: //byond
                     UpdateBYONDButtons();
                     break;
                 case 2: //scp
                     LoadServerPage();
                     break;
                 case 3: //chat
                     LoadChatPage();
                     break;
             }
             Properties.Settings.Default.LastPageIndex = Panels.SelectedIndex;
         }
void TGControlPanel.ControlPanel.PopulateRepoFields () private
Definition at line 72 of file RepoPage.cs.
References TGControlPanel.ControlPanel.BackupTagsList, TGControlPanel.ControlPanel.BranchNameTitle, TGControlPanel.ControlPanel.CloneRepositoryButton, TGControlPanel.ControlPanel.CurrentRevisionLabel, TGControlPanel.ControlPanel.CurrentRevisionTitle, TGControlPanel.ControlPanel.HardReset, TGControlPanel.ControlPanel.IdentityLabel, TGControlPanel.ControlPanel.MergePRButton, TGControlPanel.ControlPanel.RecloneButton, TGControlPanel.ControlPanel.RemoteNameTitle, TGControlPanel.ControlPanel.RepoApplyButton, TGControlPanel.ControlPanel.RepoBranchTextBox, TGControlPanel.ControlPanel.RepoBusyCheck(), TGControlPanel.ControlPanel.RepoGenChangelogButton, TGControlPanel.ControlPanel.RepoProgressBar, TGControlPanel.ControlPanel.RepoProgressBarLabel, TGControlPanel.ControlPanel.RepoRefreshButton, TGControlPanel.ControlPanel.RepoRemoteTextBox, TGControlPanel.ControlPanel.ResetRemote, TGControlPanel.ControlPanel.TestMergeListLabel, TGControlPanel.ControlPanel.TestMergeListTitle, TGControlPanel.ControlPanel.TestmergeSelector, TGControlPanel.ControlPanel.TGSJsonUpdate, and TGControlPanel.ControlPanel.UpdateRepoButton.
Referenced by TGControlPanel.ControlPanel.InitRepoPage(), TGControlPanel.ControlPanel.Panels_SelectedIndexChanged(), TGControlPanel.ControlPanel.RepoBGW_RunWorkerCompleted(), and TGControlPanel.ControlPanel.RepoRefreshButton_Click().
         {
             if (repoError != null)
                 MessageBox.Show("An error occured: " + repoError);
             if (RepoBusyCheck())
                 return;
             var Repo = Interface.GetComponent<ITGRepository>();
             RepoProgressBar.Style = ProgressBarStyle.Marquee;
             RepoProgressBar.Visible = false;
             RemoteNameTitle.Visible = true;
             RepoRemoteTextBox.Visible = true;
             BranchNameTitle.Visible = true;
             RepoBranchTextBox.Visible = true;
             RepoRefreshButton.Visible = true;
             if (!Repo.Exists())
             {
                 //repo unavailable
                 RepoRemoteTextBox.Text = "https://github.com/tgstation/tgstation";
                 RepoBranchTextBox.Text = "master";
                 RepoProgressBarLabel.Text = "Unable to locate repository";
                 CloneRepositoryButton.Visible = true;
             }
             else
             {
                 RepoProgressBarLabel.Visible = false;
                 CurrentRevisionLabel.Visible = true;
                 CurrentRevisionTitle.Visible = true;
                 IdentityLabel.Visible = true;
                 MergePRButton.Visible = true;
                 TestMergeListLabel.Visible = true;
                 TestMergeListTitle.Visible = true;
                 UpdateRepoButton.Visible = true;
                 BackupTagsList.Visible = true;
                 HardReset.Visible = true;
                 RepoApplyButton.Visible = true;
                 TestmergeSelector.Visible = true;
                 RepoGenChangelogButton.Visible = true;
                 RecloneButton.Visible = true;
                 ResetRemote.Visible = true;
                 TGSJsonUpdate.Visible = true;
                 CurrentRevisionLabel.Text = Repo.GetHead(false, out string error) ?? "Unknown";
                 RepoRemoteTextBox.Text = Repo.GetRemote(out error) ?? "Unknown";
                 RepoBranchTextBox.Text = Repo.GetBranch(out error) ?? "Unknown";
                 var Backups = Repo.ListBackups(out error);
                 BackupTagsList.Items.Clear();
                 if (Backups != null)
                 {
                     if (Backups.Count == 0)
                         BackupTagsList.Items.Add("None");
                     else
                         foreach (var I in Backups)
                             BackupTagsList.Items.Add(I.Key + ": " + I.Value);
                 }
                 else
                     BackupTagsList.Items.Add("Unknown");
                 var PRs = Repo.MergedPullRequests(out error);
                 TestMergeListLabel.Items.Clear();
                 if (PRs != null)
                     if (PRs.Count == 0)
                         TestMergeListLabel.Items.Add("None");
                     else
                         foreach (var I in PRs)
                             TestMergeListLabel.Items.Add(String.Format("#{0}: {2} by {3} at commit {1}\r\n", I.Number, I.Sha, I.Title, I.Author));
                 else
                     TestMergeListLabel.Items.Add("Unknown");
             }
         }
void TGControlPanel.ControlPanel.PortSelector_ValueChanged (object sender, EventArgs e) private
Definition at line 211 of file ServerPage.cs.
References TGControlPanel.ControlPanel.PortSelector.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             if (!updatingFields)
                 Interface.GetComponent<ITGDreamDaemon>().SetPort((ushort)PortSelector.Value);
         }
void TGControlPanel.ControlPanel.ProjectNameText_KeyDown (object sender, KeyEventArgs e) private
Definition at line 41 of file ServerPage.cs.
References TGControlPanel.ControlPanel.UpdateProjectName().
Referenced by TGControlPanel.ControlPanel.InitServerPage().
         {
             if (e.KeyCode == Keys.Enter)
                 UpdateProjectName();
         }
void TGControlPanel.ControlPanel.ProjectNameText_LostFocus (object sender, EventArgs e) private
Definition at line 200 of file ServerPage.cs.
References TGControlPanel.ControlPanel.UpdateProjectName().
Referenced by TGControlPanel.ControlPanel.InitServerPage().
         {
             UpdateProjectName();
         }
void TGControlPanel.ControlPanel.RecloneButton_Click (object sender, EventArgs e) private
Definition at line 224 of file RepoPage.cs.
References TGControlPanel.ControlPanel.CloneRepo().
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             var DialogResult = MessageBox.Show("This will re-clone the repository, backup, and reset the Static configuration folders. Continue?", "Confim", MessageBoxButtons.YesNo);
             if (DialogResult == DialogResult.No)
                 return;
             CloneRepo();
         }
void TGControlPanel.ControlPanel.RecreateStaticButton_Click (object sender, EventArgs e) private
Definition at line 326 of file StaticPage.cs.
References TGControlPanel.ControlPanel.BuildFileList(), TGControlPanel.ControlPanel.CheckAdminWithWarning(), and TGControlPanel.ControlPanel.RecreateStaticButton.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             if (!CheckAdminWithWarning())
             {
                 RecreateStaticButton.Visible = false;
                 return;
             }
             if (MessageBox.Show("This will rename the current static directory to a backup and recreate it. Continue?", "Confirm", MessageBoxButtons.YesNo) != DialogResult.Yes)
                 return;
             if (!CheckAdminWithWarning())
             {
                 RecreateStaticButton.Visible = false;
                 return;
             }
             var res = Interface.GetComponent<ITGAdministration>().RecreateStaticFolder();
             if (res != null)
                 MessageBox.Show(res);
             BuildFileList();
         }
void TGControlPanel.ControlPanel.RepoApplyButton_Click (object sender, EventArgs e) private
Definition at line 272 of file RepoPage.cs.
References TGControlPanel.ControlPanel.CloneRepositoryButton_Click(), TGControlPanel.ControlPanel.DoAsyncOp(), TGServiceInterface.Components.ITGRepository.GetRemote(), TGControlPanel.ControlPanel.RepoBranchTextBox, TGControlPanel.ControlPanel.RepoBusyCheck(), and TGControlPanel.ControlPanel.RepoRemoteTextBox.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             var Repo = Interface.GetComponent<ITGRepository>();
             if (RepoBusyCheck())
                 return;
             var remote = Repo.GetRemote(out string error);
             if (remote == null) {
                 MessageBox.Show("Error: " + error);
                 return;
             }
             var Reclone = remote != RepoRemoteTextBox.Text;
             if (Reclone)
             {
                 var DialogResult = MessageBox.Show("Changing the remote URL requires a re-cloning of the repository. Continue?", "Confim", MessageBoxButtons.YesNo);
                 if (DialogResult == DialogResult.No)
                     return;
             }
             if (!Reclone)
             {
                 var branch = Repo.GetBranch(out error);
                 if(branch == null)
                 {
                     MessageBox.Show("Error: " + error);
                     return;
                 }
                 CheckoutBranch = RepoBranchTextBox.Text;
                 if(branch != CheckoutBranch)
                     DoAsyncOp(RepoAction.Checkout, String.Format("Checking out {0}...", CheckoutBranch));
             }
             else
                 CloneRepositoryButton_Click(null, null);
         }
void TGControlPanel.ControlPanel.RepoBGW_DoWork (object sender, DoWorkEventArgs e) private
Definition at line 169 of file RepoPage.cs.
References TGControlPanel.ControlPanel.RepoBGW, and TGServiceInterface.Components.ITGRepository.Setup().
Referenced by TGControlPanel.ControlPanel.InitRepoPage().
         {
             //Only for clones
             var Repo = Interface.GetComponent<ITGRepository>();
             switch (action) {
                 case RepoAction.Clone:
                     repoError = Repo.Setup(CloneRepoURL, CheckoutBranch);
                     break;
                 case RepoAction.Checkout:
                     repoError = Repo.Checkout(CheckoutBranch);
                     break;
                 case RepoAction.Merge:
                     repoError = Repo.Update(false);
                     break;
                 case RepoAction.Reset:
                     repoError = Repo.Reset(true);
                     break;
                 case RepoAction.Test:
                     repoError = Repo.MergePullRequest(TestPR);
                     break;
                 case RepoAction.Update:
                     repoError = Repo.Update(true);
                     break;
                 case RepoAction.Wait:
                     break;
                 case RepoAction.GenCL:
                     var result = Repo.GenerateChangelog(out repoError);
                     if(repoError != null)
                         repoError += ": " + result;
                     break;
                 default:
                     //reeee
                     return;
             }
             do
             {
                 Thread.Sleep(1000);
                 RepoBGW.ReportProgress(Repo.CheckoutProgress());
             } while (Repo.OperationInProgress());
         }
void TGControlPanel.ControlPanel.RepoBGW_ProgressChanged (object sender, ProgressChangedEventArgs e) private
Definition at line 157 of file RepoPage.cs.
References TGControlPanel.ControlPanel.RepoProgressBar.
Referenced by TGControlPanel.ControlPanel.InitRepoPage().
         {
             var val = e.ProgressPercentage;
             if (val < 0)
             {
                 RepoProgressBar.Style = ProgressBarStyle.Marquee;
                 return;
             }
             RepoProgressBar.Style = ProgressBarStyle.Blocks;
             RepoProgressBar.Value = val;
         }
void TGControlPanel.ControlPanel.RepoBGW_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e) private
Definition at line 59 of file RepoPage.cs.
References TGControlPanel.ControlPanel.PopulateRepoFields(), TGControlPanel.ControlPanel.RepoPanel, and TGControlPanel.ControlPanel.RepoProgressBar.
Referenced by TGControlPanel.ControlPanel.InitRepoPage().
         {
             RepoProgressBar.Value = 100;
             RepoProgressBar.Style = ProgressBarStyle.Blocks;
             RepoPanel.UseWaitCursor = false;
             PopulateRepoFields();
         }
bool TGControlPanel.ControlPanel.RepoBusyCheck () private
Definition at line 148 of file RepoPage.cs.
References TGControlPanel.ControlPanel.DoAsyncOp(), and TGServiceInterface.Components.ITGRepository.OperationInProgress().
Referenced by TGControlPanel.ControlPanel.DoAsyncOp(), TGControlPanel.ControlPanel.PopulateRepoFields(), and TGControlPanel.ControlPanel.RepoApplyButton_Click().
         {
             if (Interface.GetComponent<ITGRepository>().OperationInProgress())
             {
                 DoAsyncOp(RepoAction.Wait, "Waiting for repository to finish another action...");
                 return true;
             }
             return false;
         }
void TGControlPanel.ControlPanel.RepoGenChangelogButton_Click (object sender, System.EventArgs e) private
Definition at line 335 of file RepoPage.cs.
References TGControlPanel.ControlPanel.DoAsyncOp().
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             DoAsyncOp(RepoAction.GenCL, "Generating changelog...");
         }
void TGControlPanel.ControlPanel.RepoRefreshButton_Click (object sender, EventArgs e) private
Definition at line 67 of file RepoPage.cs.
References TGControlPanel.ControlPanel.PopulateRepoFields().
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             PopulateRepoFields();
         }
void TGControlPanel.ControlPanel.ResetRemote_Click (object sender, EventArgs e) private
Definition at line 319 of file RepoPage.cs.
References TGControlPanel.ControlPanel.DoAsyncOp().
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             DoAsyncOp(RepoAction.Update, "Updating and resetting to remote branch...");
         }
void TGControlPanel.ControlPanel.ResetTestmerge_Click (object sender, EventArgs e) private
Definition at line 394 of file ServerPage.cs.
References TGControlPanel.ControlPanel.RunServerUpdate().
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             RunServerUpdate(FullUpdateAction.Reset);
         }
void TGControlPanel.ControlPanel.RunServerUpdate (FullUpdateAction fua, ushort tm = 0) private
Definition at line 217 of file ServerPage.cs.
References TGControlPanel.ControlPanel.compileButton, TGControlPanel.ControlPanel.CompilerStatusLabel, TGControlPanel.ControlPanel.FullUpdateWorker, TGControlPanel.ControlPanel.initializeButton, TGControlPanel.ControlPanel.TestmergeButton, TGControlPanel.ControlPanel.UpdateHardButton, TGControlPanel.ControlPanel.UpdateMergeButton, and TGControlPanel.ControlPanel.UpdateTestmergeButton.
Referenced by TGControlPanel.ControlPanel.ResetTestmerge_Click(), TGControlPanel.ControlPanel.TestmergeButton_Click(), TGControlPanel.ControlPanel.UpdateHardButton_Click(), TGControlPanel.ControlPanel.UpdateMergeButton_Click(), and TGControlPanel.ControlPanel.UpdateTestmergeButton_Click().
         {
             if (FullUpdateWorker.IsBusy)
                 return;
             testmergePR = tm;
             fuAction = fua;
             initializeButton.Enabled = false;
             compileButton.Enabled = false;
             UpdateHardButton.Enabled = false;
             UpdateMergeButton.Enabled = false;
             TestmergeButton.Enabled = false;
             UpdateTestmergeButton.Enabled = false;
             switch (fuAction)
             {
                 case FullUpdateAction.Testmerge:
                     CompilerStatusLabel.Text = String.Format("Testmerging pull request #{0}...", testmergePR);
                     break;
                 case FullUpdateAction.UpdateHard:
                     CompilerStatusLabel.Text = String.Format("Updating Server (RESET)...");
                     break;
                 case FullUpdateAction.UpdateMerge:
                     CompilerStatusLabel.Text = String.Format("Updating Server (MERGE)...");
                     break;
                 case FullUpdateAction.UpdateHardTestmerge:
                     CompilerStatusLabel.Text = String.Format("Updating and testmerging pull request #{0}...", testmergePR);
                     break;
             }
             FullUpdateWorker.RunWorkerAsync();
         }
void TGControlPanel.ControlPanel.SecuritySelector_SelectedIndexChanged (object sender, EventArgs e) private
Definition at line 418 of file ServerPage.cs.
References TGControlPanel.ControlPanel.SecuritySelector, and TGServiceInterface.Components.ITGDreamDaemon.SetSecurityLevel().
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             if (!updatingFields)
                 if (!Interface.GetComponent<ITGDreamDaemon>().SetSecurityLevel((DreamDaemonSecurity)SecuritySelector.SelectedIndex))
                     MessageBox.Show("Security change will be applied after next server reboot.");
         }
void TGControlPanel.ControlPanel.ServerGRestartButton_Click (object sender, EventArgs e) private
Definition at line 319 of file ServerPage.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             var DialogResult = MessageBox.Show("This will restart the server when the current round ends. Continue?", "Confim", MessageBoxButtons.YesNo);
             if (DialogResult == DialogResult.No)
                 return;
             Interface.GetComponent<ITGDreamDaemon>().RequestRestart();
         }
void TGControlPanel.ControlPanel.ServerGStopButton_Checked (object sender, EventArgs e) private
Definition at line 308 of file ServerPage.cs.
References TGControlPanel.ControlPanel.LoadServerPage().
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             if (updatingFields)
                 return;
             var DialogResult = MessageBox.Show("This will shut down the server when the current round ends. Continue?", "Confim", MessageBoxButtons.YesNo);
             if (DialogResult == DialogResult.No)
                 return;
             Interface.GetComponent<ITGDreamDaemon>().RequestStop();
             LoadServerPage();
         }
void TGControlPanel.ControlPanel.ServerPageRefreshButton_Click (object sender, EventArgs e) private
Definition at line 247 of file ServerPage.cs.
References TGControlPanel.ControlPanel.LoadServerPage().
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             LoadServerPage();
         }
void TGControlPanel.ControlPanel.ServerRestartButton_Click (object sender, EventArgs e) private
Definition at line 298 of file ServerPage.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             var DialogResult = MessageBox.Show("This will immediately restart the server. Continue?", "Confim", MessageBoxButtons.YesNo);
             if (DialogResult == DialogResult.No)
                 return;
             var res = Interface.GetComponent<ITGDreamDaemon>().Restart();
             if (res != null)
                 MessageBox.Show(res);
         }
void TGControlPanel.ControlPanel.ServerStartBGW_DoWork (object sender, DoWorkEventArgs e) private
Definition at line 276 of file ServerPage.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             try
             {
                 e.Result = Interface.GetComponent<ITGDreamDaemon>().Start();
             }
             catch (Exception ex)
             {
                 e.Result = ex.ToString();
             }
         }
void TGControlPanel.ControlPanel.ServerStartBGW_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e) private
Definition at line 34 of file ServerPage.cs.
References TGControlPanel.ControlPanel.LoadServerPage().
Referenced by TGControlPanel.ControlPanel.InitServerPage().
         {
             if (e.Result != null)
                 MessageBox.Show((string)e.Result);
             LoadServerPage();
         }
void TGControlPanel.ControlPanel.ServerStartButton_Click (object sender, System.EventArgs e) private
Definition at line 270 of file ServerPage.cs.
References TGControlPanel.ControlPanel.ServerStartBGW.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             if (!ServerStartBGW.IsBusy)
                 ServerStartBGW.RunWorkerAsync();
         }
void TGControlPanel.ControlPanel.ServerStopButton_Click (object sender, EventArgs e) private
Definition at line 288 of file ServerPage.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             var DialogResult = MessageBox.Show("This will immediately shut down the server. Continue?", "Confim", MessageBoxButtons.YesNo);
             if (DialogResult == DialogResult.No)
                 return;
             var res = Interface.GetComponent<ITGDreamDaemon>().Stop();
             if (res != null)
                 MessageBox.Show(res);
         }
void TGControlPanel.ControlPanel.SetAdminsAreSpecial (bool value) private
Definition at line 150 of file ChatPage.cs.
References TGControlPanel.ControlPanel.LoadChatPage(), TGControlPanel.ControlPanel.ModifyingProvider, and TGServiceInterface.Components.ITGChat.ProviderInfos().
Referenced by TGControlPanel.ControlPanel.AdminModeNormal_CheckedChanged(), and TGControlPanel.ControlPanel.AdminModeSpecial_CheckedChanged().
         {
             var Chat = Interface.GetComponent<ITGChat>();
             var PI = Chat.ProviderInfos()[(int)ModifyingProvider];
             PI.AdminsAreSpecial = value;
             var res = Chat.SetProviderInfo(PI);
             if (res != null)
                 MessageBox.Show(res);
             LoadChatPage();
         }
static string [] TGControlPanel.ControlPanel.SplitByLine (TextBox t) static private
Definition at line 119 of file ChatPage.cs.
         {
             var channels = t.Text.Split('\n');
             var finalChannels = new List<string>();
             foreach (var I in channels)
             {
                 var trimmed = I.Trim();
                 if(trimmed != "")
                     finalChannels.Add(trimmed);
             }
             return finalChannels.ToArray();
         }
void TGControlPanel.ControlPanel.StaticFileCreateButton_Click (object sender, EventArgs e) private
Definition at line 215 of file StaticPage.cs.
References TGControlPanel.ControlPanel.BuildFileList(), TGControlPanel.ControlPanel.StaticFileEditTextbox, TGControlPanel.ControlPanel.StaticFileListBox, TGControlPanel.Program.TextPrompt(), and TGServiceInterface.Components.ITGConfig.WriteText().
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             if(StaticFileEditTextbox.Text != "Directory")
             {
                 MessageBox.Show("Please select a directory to create the file in.");
                 return;
             }
             var FileName = Program.TextPrompt("Static File/Directory Creation", "Enter the name of the file/directory:");
             if (FileName == null)
                 return;
             var resu = MessageBox.Show("Is this the name of a directory?", "Directory", MessageBoxButtons.YesNoCancel);
             if (resu == DialogResult.Cancel)
                 return;
             var FullFileName = Path.Combine(IndexesToPaths[StaticFileListBox.SelectedIndex], FileName);
             if (resu == DialogResult.Yes)
                 FullFileName = Path.Combine(FullFileName, "__TGS3_CP_DIRECTORY_CREATOR__");
             var config = Interface.GetComponent<ITGConfig>();
             var res = config.WriteText(FullFileName, "", out bool unauthorized);
             if (res != null)
                 MessageBox.Show(res);
             if (resu == DialogResult.Yes)
             {
                 FullFileName = Path.Combine(FullFileName, "__TGS3_CP_DIRECTORY_CREATOR__");
                 config.DeleteFile(FullFileName, out unauthorized);  //don't care about this
             }
             BuildFileList();
         }
void TGControlPanel.ControlPanel.StaticFileDeleteButton_Click (object sender, EventArgs e) private
Definition at line 205 of file StaticPage.cs.
References TGControlPanel.ControlPanel.BuildFileList(), and TGControlPanel.ControlPanel.StaticFileListBox.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             if (MessageBox.Show("Are you sure you want to delete " + ((string)StaticFileListBox.SelectedItem).Trim() + "?", "Confirm", MessageBoxButtons.YesNo) != DialogResult.Yes)
                 return;
             var res = Interface.GetComponent<ITGConfig>().DeleteFile(IndexesToPaths[StaticFileListBox.SelectedIndex], out bool unauthorized);
             if (res != null)
                 MessageBox.Show(res);
             BuildFileList();
         }
void TGControlPanel.ControlPanel.StaticFileDownloadButton_Click (object sender, EventArgs e) private
Definition at line 154 of file StaticPage.cs.
References TGControlPanel.ControlPanel.StaticFileEditTextbox, and TGControlPanel.ControlPanel.StaticFileListBox.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             if (StaticFileEditTextbox.ReadOnly)
             {
                 MessageBox.Show("Cannot download this file!");
                 return;
             }
             var remotePath = IndexesToPaths[StaticFileListBox.SelectedIndex];
             if (remotePath == null)
                 return;
             string text, error;
             try
             {
                 text = Interface.GetComponent<ITGConfig>().ReadText(remotePath, false, out error, out bool unauthorized);
             }
             catch (Exception ex)
             {
                 text = null;
                 error = "Failed to read file, most likely due to it being too large. The transfer limit is much higher on non-remote connections. " + ex.ToString();
             }
             if (text != null)
             {
                 var ofd = new SaveFileDialog()
                 {
                     CheckFileExists = false,
                     CheckPathExists = true,
                     DefaultExt = ".txt",
                     Title = "Static File Download",
                     ValidateNames = true,
                     Filter = "All files (*.*)|*.*",
                     AddExtension = false,
                     CreatePrompt = false,
                     OverwritePrompt = true,
                     SupportMultiDottedExtensions = true,
                 };
                 if (ofd.ShowDialog() != DialogResult.OK)
                     return;
                 try
                 {
                     File.WriteAllText(ofd.FileName, text);
                     return;
                 }
                 catch (Exception ex)
                 {
                     error = ex.ToString();
                 }
             }
             MessageBox.Show("An error occurred: " + error);
         }
void TGControlPanel.ControlPanel.StaticFileListBox_SelectedIndexChanged (object sender, EventArgs e) private
Definition at line 268 of file StaticPage.cs.
References TGControlPanel.ControlPanel.UpdateEditText().
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             UpdateEditText();
         }
void TGControlPanel.ControlPanel.StaticFileSaveButton_Click (object sender, EventArgs e) private
Definition at line 244 of file StaticPage.cs.
References TGControlPanel.ControlPanel.StaticFileEditTextbox, TGControlPanel.ControlPanel.StaticFileListBox, and TGControlPanel.ControlPanel.UpdateEditText().
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             var index = StaticFileListBox.SelectedIndex;
             string res;
             bool unauthorized;
             try
             {
                 res = Interface.GetComponent<ITGConfig>().WriteText(IndexesToPaths[index], StaticFileEditTextbox.Text, out unauthorized);
             }
             catch (Exception ex)
             {
                 unauthorized = false;
                 res = "Failed to write file, most likely due to it being too large. The transfer limit is much higher on non-remote connections. " + ex.ToString();
             }
             if (res != null)
             {
                 MessageBox.Show("Error: " + res);
                 var title = (string)StaticFileListBox.Items[index];
                 if (unauthorized && !title.Contains(" (UNAUTHORIZED)"))
                     StaticFileListBox.Items[index] = title + " (UNAUTHORIZED)";
             }
             UpdateEditText();
         }
void TGControlPanel.ControlPanel.StaticFilesRefreshButton_Click (object sender, EventArgs e) private
Definition at line 98 of file StaticPage.cs.
References TGControlPanel.ControlPanel.BuildFileList(), and TGControlPanel.ControlPanel.UpdateEditText().
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             BuildFileList();
             UpdateEditText();
         }
void TGControlPanel.ControlPanel.StaticFileUploadButton_Click (object sender, EventArgs e) private
Definition at line 104 of file StaticPage.cs.
References TGControlPanel.ControlPanel.BuildFileList(), TGControlPanel.ControlPanel.StaticFileEditTextbox, and TGControlPanel.ControlPanel.StaticFileListBox.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             if (StaticFileEditTextbox.Text != "Directory")
             {
                 MessageBox.Show("Please select a directory to upload the file to.");
                 return;
             }
             var ofd = new OpenFileDialog()
             {
                 CheckFileExists = true,
                 CheckPathExists = true,
                 DefaultExt = ".txt",
                 Multiselect = false,
                 Title = "Static File Upload",
                 ValidateNames = true,
                 Filter = "All files (*.*)|*.*",
                 AddExtension = false,
                 SupportMultiDottedExtensions = true,
             };
             if (ofd.ShowDialog() != DialogResult.OK)
                 return;
             var fileToUpload = ofd.FileName;
             var FileName = Path.Combine(IndexesToPaths[StaticFileListBox.SelectedIndex], Path.GetFileName(fileToUpload));
             string fileContents = null;
             string error = null;
             try
             {
                 fileContents = File.ReadAllText(fileToUpload);
             }
             catch (Exception ex)
             {
                 error = ex.ToString();
             }
             if (error == null)
                 try
                 {
                     error = Interface.GetComponent<ITGConfig>().WriteText(FileName, fileContents, out bool unauthorized);
                 }
                 catch (Exception ex)
                 {
                     error = "Failed to read file, most likely due to it being too large. The transfer limit is much higher on non-remote connections. " + ex.ToString();
                 }
             if (error != null)
                 MessageBox.Show("An error occurred: " + error);
             BuildFileList();
         }
void TGControlPanel.ControlPanel.TestMergeButton_Click (object sender, EventArgs e) private
Definition at line 324 of file RepoPage.cs.
References TGControlPanel.ControlPanel.DoAsyncOp(), and TGControlPanel.ControlPanel.TestmergeSelector.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             if (TestmergeSelector.Value == 0)
             {
                 MessageBox.Show("Invalid PR number!");
                 return;
             }
             TestPR = (int)TestmergeSelector.Value;
             DoAsyncOp(RepoAction.Test, String.Format("Merging latest commit of PR #{0}...", TestPR));
         }
void TGControlPanel.ControlPanel.TestmergeButton_Click (object sender, System.EventArgs e) private
Definition at line 413 of file ServerPage.cs.
References TGControlPanel.ControlPanel.RunServerUpdate(), and TGControlPanel.ControlPanel.ServerTestmergeInput.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             RunServerUpdate(FullUpdateAction.Testmerge, (ushort)ServerTestmergeInput.Value);
         }
void TGControlPanel.ControlPanel.TGSJsonUpdate_Click (object sender, EventArgs e) private
Definition at line 340 of file RepoPage.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             if (MessageBox.Show("This will update the cached TGS3.json to the current repository version, potentially redefining symlinks. Proceed?", "Json Update", MessageBoxButtons.YesNo) != DialogResult.Yes)
                 return;
             var res = Interface.GetComponent<ITGRepository>().UpdateTGS3Json();
             if (res != null)
                 MessageBox.Show(res);
         }
void TGControlPanel.ControlPanel.UpdateButton_Click (object sender, EventArgs e) private
Definition at line 47 of file ByondPage.cs.
References TGControlPanel.ControlPanel.MajorVersionNumeric, TGControlPanel.ControlPanel.MinorVersionNumeric, TGControlPanel.ControlPanel.UpdateBYONDButtons(), and TGServiceInterface.Components.ITGByond.UpdateToVersion().
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             UpdateBYONDButtons();
             if (!Interface.GetComponent<ITGByond>().UpdateToVersion((int)MajorVersionNumeric.Value, (int)MinorVersionNumeric.Value))
                 MessageBox.Show("Unable to begin update, there is another operation in progress.");
         }
void TGControlPanel.ControlPanel.UpdateBYONDButtons () private
Definition at line 58 of file ByondPage.cs.
References TGControlPanel.ControlPanel.StagedVersionLabel, TGControlPanel.ControlPanel.StagedVersionTitle, TGControlPanel.ControlPanel.StatusLabel, TGControlPanel.ControlPanel.UpdateButton, and TGControlPanel.ControlPanel.VersionLabel.
Referenced by TGControlPanel.ControlPanel.BYONDRefreshButton_Click(), TGControlPanel.ControlPanel.InitBYONDPage(), TGControlPanel.ControlPanel.Panels_SelectedIndexChanged(), and TGControlPanel.ControlPanel.UpdateButton_Click().
         {
             var BYOND = Interface.GetComponent<ITGByond>();
             VersionLabel.Text = BYOND.GetVersion(ByondVersion.Installed) ?? "Not Installed";
             StagedVersionTitle.Visible = false;
             StagedVersionLabel.Visible = false;
             switch (BYOND.CurrentStatus())
             {
                 case ByondStatus.Idle:
                 case ByondStatus.Starting:
                     StatusLabel.Text = "Idle";
                     UpdateButton.Enabled = true;
                     break;
                 case ByondStatus.Downloading:
                     StatusLabel.Text = "Downloading...";
                     UpdateButton.Enabled = false;
                     break;
                 case ByondStatus.Staging:
                     StatusLabel.Text = "Staging...";
                     UpdateButton.Enabled = false;
                     break;
                 case ByondStatus.Staged:
                     StagedVersionTitle.Visible = true;
                     StagedVersionLabel.Visible = true;
                     StagedVersionLabel.Text = BYOND.GetVersion(ByondVersion.Staged) ?? "Unknown";
                     StatusLabel.Text = "Staged and waiting for BYOND to shutdown...";
                     UpdateButton.Enabled = true;
                     break;
                 case ByondStatus.Updating:
                     StatusLabel.Text = "Applying update...";
                     UpdateButton.Enabled = false;
                     break;
             }
             var error = Interface.GetComponent<ITGByond>().GetError();
             if (error != lastReadError)
             {
                 lastReadError = error;
                 if (error != null)
                     MessageBox.Show("An error occurred: " + lastReadError);
             }
         }
void TGControlPanel.ControlPanel.UpdateEditText () private
Definition at line 273 of file StaticPage.cs.
References TGControlPanel.ControlPanel.BuildFileList(), TGControlPanel.ControlPanel.StaticFileEditTextbox, and TGControlPanel.ControlPanel.StaticFileListBox.
Referenced by TGControlPanel.ControlPanel.StaticFileListBox_SelectedIndexChanged(), TGControlPanel.ControlPanel.StaticFileSaveButton_Click(), and TGControlPanel.ControlPanel.StaticFilesRefreshButton_Click().
         {
             if (enumerating)
                 return;
             var newIndex = StaticFileListBox.SelectedIndex;
             if (newIndex == -1)
                 return;
             var path = IndexesToPaths[newIndex];
             var title = (string)StaticFileListBox.Items[newIndex];
             var authed_title = title.Replace(" (UNAUTHORIZED)", "").Replace(" (...)", "");
             if (authed_title[authed_title.Length - 1] == '/')
             {
                 StaticFileEditTextbox.ReadOnly = true;
                 StaticFileEditTextbox.Text = "Directory";
                 if (path != null && path != "/")
                 {
                     EnumeratedPaths.Add(path);
                     BuildFileList();
                     enumerating = true;
                     StaticFileListBox.SelectedIndex = newIndex;
                     enumerating = false;
                     return;
                 }
             }
             else
             {
                 string entry, error;
                 bool unauthorized;
                 try
                 {
                     entry = Interface.GetComponent<ITGConfig>().ReadText(path, false, out error, out unauthorized);
                 }
                 catch(Exception e)
                 {
                     entry = null;
                     unauthorized = false;
                     error = "Failed to read file, most likely due to it being too large. The transfer limit is much higher on non-remote connections. " + e.ToString();
                 }
                 if (entry == null)
                 {
                     StaticFileEditTextbox.ReadOnly = true;
                     StaticFileEditTextbox.Text = "ERROR: " + error;
                     if (unauthorized && !title.Contains(" (UNAUTHORIZED)"))
                         StaticFileListBox.Items[newIndex] = title + " (UNAUTHORIZED)";
                 }
                 else
                 {
                     StaticFileEditTextbox.ReadOnly = false;
                     StaticFileEditTextbox.Text = entry.Replace("\r\n", "\n").Replace("\r", "\n").Replace("\n", Environment.NewLine);
                 }
             }
         }
void TGControlPanel.ControlPanel.UpdateHardButton_Click (object sender, System.EventArgs e) private
Definition at line 399 of file ServerPage.cs.
References TGControlPanel.ControlPanel.RunServerUpdate().
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             RunServerUpdate(FullUpdateAction.UpdateHard);
         }
void TGControlPanel.ControlPanel.UpdateMergeButton_Click (object sender, System.EventArgs e) private
Definition at line 409 of file ServerPage.cs.
References TGControlPanel.ControlPanel.RunServerUpdate().
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             RunServerUpdate(FullUpdateAction.UpdateMerge);
         }
void TGControlPanel.ControlPanel.UpdateProjectName () private
Definition at line 205 of file ServerPage.cs.
References TGControlPanel.ControlPanel.projectNameText.
Referenced by TGControlPanel.ControlPanel.ProjectNameText_KeyDown(), and TGControlPanel.ControlPanel.ProjectNameText_LostFocus().
         {
             if (!updatingFields)
                 Interface.GetComponent<ITGCompiler>().SetProjectName(projectNameText.Text);
         }
void TGControlPanel.ControlPanel.UpdateRepoButton_Click (object sender, EventArgs e) private
Definition at line 309 of file RepoPage.cs.
References TGControlPanel.ControlPanel.DoAsyncOp().
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             DoAsyncOp(RepoAction.Merge, "Merging origin branch...");
         }
void TGControlPanel.ControlPanel.UpdateTestmergeButton_Click (object sender, System.EventArgs e) private
Definition at line 404 of file ServerPage.cs.
References TGControlPanel.ControlPanel.RunServerUpdate(), and TGControlPanel.ControlPanel.ServerTestmergeInput.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             RunServerUpdate(FullUpdateAction.UpdateHardTestmerge, (ushort)ServerTestmergeInput.Value);
         }
void TGControlPanel.ControlPanel.WebclientCheckBox_CheckedChanged (object sender, EventArgs e) private
Definition at line 440 of file ServerPage.cs.
References TGControlPanel.ControlPanel.WebclientCheckBox.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             if (!updatingFields)
                 Interface.GetComponent<ITGDreamDaemon>().SetWebclient(WebclientCheckBox.Checked);
         }
void TGControlPanel.ControlPanel.WorldAnnounceButton_Click (object sender, EventArgs e) private
Definition at line 425 of file ServerPage.cs.
References TGControlPanel.ControlPanel.WorldAnnounceField.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
         {
             var msg = WorldAnnounceField.Text;
             if (!String.IsNullOrWhiteSpace(msg))
             {
                 var res = Interface.GetComponent<ITGDreamDaemon>().WorldAnnounce(msg);
                 if (res != null)
                 {
                     MessageBox.Show(res);
                     return;
                 }
             }
             WorldAnnounceField.Text = "";
         }
Member Data Documentation
RepoAction TGControlPanel.ControlPanel.action private
Definition at line 23 of file RepoPage.cs.
System.Windows.Forms.TextBox TGControlPanel.ControlPanel.AdminChannelsTextbox private
Definition at line 1816 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.ChatApplyButton_Click(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadChatPage().
System.Windows.Forms.RadioButton TGControlPanel.ControlPanel.AdminModeNormal private
Definition at line 1845 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.AdminModeNormal_CheckedChanged(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadChatPage().
System.Windows.Forms.RadioButton TGControlPanel.ControlPanel.AdminModeSpecial private
Definition at line 1844 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.AdminModeSpecial_CheckedChanged(), TGControlPanel.ControlPanel.ChatApplyButton_Click(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadChatPage().
System.Windows.Forms.TextBox TGControlPanel.ControlPanel.AuthField1 private
Definition at line 1823 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.ChatApplyButton_Click(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadChatPage().
System.Windows.Forms.Label TGControlPanel.ControlPanel.AuthField1Title private
Definition at line 1832 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadChatPage().
System.Windows.Forms.TextBox TGControlPanel.ControlPanel.AuthField2 private
Definition at line 1822 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.ChatApplyButton_Click(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadChatPage().
System.Windows.Forms.Label TGControlPanel.ControlPanel.AuthField2Title private
Definition at line 1831 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadChatPage().
System.Windows.Forms.CheckBox TGControlPanel.ControlPanel.AutostartCheckbox private
Definition at line 1847 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.AutostartCheckbox_CheckedChanged(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadServerPage().
System.Windows.Forms.CheckBox TGControlPanel.ControlPanel.AutoUpdateCheckbox private
Definition at line 1929 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.AutoUpdateCheckbox_CheckedChanged(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadServerPage().
System.Windows.Forms.NumericUpDown TGControlPanel.ControlPanel.AutoUpdateInterval private
Definition at line 1928 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.AutoUpdateCheckbox_CheckedChanged(), TGControlPanel.ControlPanel.AutoUpdateInterval_ValueChanged(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadServerPage().
System.Windows.Forms.Label TGControlPanel.ControlPanel.AutoUpdateMLabel private
Definition at line 1930 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.AutoUpdateCheckbox_CheckedChanged(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadServerPage().
System.Windows.Forms.ListBox TGControlPanel.ControlPanel.BackupTagsList private
Definition at line 1892 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.BackupTagsList_MouseDoubleClick(), TGControlPanel.ControlPanel.DoAsyncOp(), TGControlPanel.ControlPanel.InitializeComponent(), TGControlPanel.ControlPanel.InitRepoPage(), and TGControlPanel.ControlPanel.PopulateRepoFields().
System.Windows.Forms.Label TGControlPanel.ControlPanel.BranchNameTitle private
Definition at line 1908 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.DoAsyncOp(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.PopulateRepoFields().
System.Windows.Forms.TabPage TGControlPanel.ControlPanel.BYONDPanel private
Definition at line 1877 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
System.Windows.Forms.Button TGControlPanel.ControlPanel.BYONDRefreshButton private
Definition at line 1925 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
System.Windows.Forms.Label TGControlPanel.ControlPanel.ChannelsTitle private
Definition at line 1841 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadChatPage().
System.Windows.Forms.TextBox TGControlPanel.ControlPanel.ChatAdminsTextBox private
Definition at line 1824 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.ChatApplyButton_Click(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadChatPage().
System.Windows.Forms.Label TGControlPanel.ControlPanel.ChatAdminsTitle private
Definition at line 1842 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadChatPage().
System.Windows.Forms.Button TGControlPanel.ControlPanel.ChatApplyButton private
Definition at line 1830 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
System.Windows.Forms.CheckBox TGControlPanel.ControlPanel.ChatEnabledCheckbox private
Definition at line 1836 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.ChatApplyButton_Click(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadChatPage().
System.Windows.Forms.TextBox TGControlPanel.ControlPanel.ChatNicknameText private
Definition at line 1820 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.ChatApplyButton_Click(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadChatPage().
System.Windows.Forms.Label TGControlPanel.ControlPanel.ChatNicknameTitle private
Definition at line 1826 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadChatPage().
System.Windows.Forms.TabPage TGControlPanel.ControlPanel.ChatPanel private
Definition at line 1809 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
System.Windows.Forms.NumericUpDown TGControlPanel.ControlPanel.ChatPortSelector private
Definition at line 1827 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.ChatApplyButton_Click(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadChatPage().
System.Windows.Forms.Label TGControlPanel.ControlPanel.ChatPortTitle private
Definition at line 1828 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadChatPage().
System.Windows.Forms.Panel TGControlPanel.ControlPanel.ChatProviderSelectorPanel private
Definition at line 1837 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
System.Windows.Forms.Label TGControlPanel.ControlPanel.ChatProviderTitle private
Definition at line 1840 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
System.Windows.Forms.Button TGControlPanel.ControlPanel.ChatReconnectButton private
Definition at line 1833 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadChatPage().
System.Windows.Forms.Button TGControlPanel.ControlPanel.ChatRefreshButton private
Definition at line 1825 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
System.Windows.Forms.TextBox TGControlPanel.ControlPanel.ChatServerText private
Definition at line 1821 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.ChatApplyButton_Click(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadChatPage().
System.Windows.Forms.Label TGControlPanel.ControlPanel.ChatServerTitle private
Definition at line 1829 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadChatPage().
System.Windows.Forms.Label TGControlPanel.ControlPanel.ChatStatusLabel private
Definition at line 1834 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadChatPage().
System.Windows.Forms.Label TGControlPanel.ControlPanel.ChatStatusTitle private
Definition at line 1835 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
string TGControlPanel.ControlPanel.CheckoutBranch private
Definition at line 25 of file RepoPage.cs.
System.Windows.Forms.Button TGControlPanel.ControlPanel.CloneRepositoryButton private
Definition at line 1910 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.DoAsyncOp(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.PopulateRepoFields().
string TGControlPanel.ControlPanel.CloneRepoURL private
Definition at line 24 of file RepoPage.cs.
System.Windows.Forms.Button TGControlPanel.ControlPanel.compileButton private
Definition at line 1873 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), TGControlPanel.ControlPanel.LoadServerPage(), and TGControlPanel.ControlPanel.RunServerUpdate().
System.Windows.Forms.Button TGControlPanel.ControlPanel.CompileCancelButton private
Definition at line 1856 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadServerPage().
System.Windows.Forms.Label TGControlPanel.ControlPanel.CompilerLabel private
Definition at line 1872 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadServerPage().
System.Windows.Forms.Label TGControlPanel.ControlPanel.CompilerStatusLabel private
Definition at line 1871 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), TGControlPanel.ControlPanel.LoadServerPage(), and TGControlPanel.ControlPanel.RunServerUpdate().
System.ComponentModel.IContainer TGControlPanel.ControlPanel.components = null private
Required designer variable.
Definition at line 8 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.Dispose().
System.Windows.Forms.Label TGControlPanel.ControlPanel.CurrentRevisionLabel private
Definition at line 1900 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.DoAsyncOp(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.PopulateRepoFields().
System.Windows.Forms.Label TGControlPanel.ControlPanel.CurrentRevisionTitle private
Definition at line 1909 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.DoAsyncOp(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.PopulateRepoFields().
System.Windows.Forms.TextBox TGControlPanel.ControlPanel.DevChannelsTextbox private
Definition at line 1819 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.ChatApplyButton_Click(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadChatPage().
System.Windows.Forms.RadioButton TGControlPanel.ControlPanel.DiscordProviderSwitch private
Definition at line 1838 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.DiscordProviderSwitch_CheckedChanged(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadChatPage().
IList<string> TGControlPanel.ControlPanel.EnumeratedPaths = new List<string>() { "" } private
Definition at line 13 of file StaticPage.cs.
bool TGControlPanel.ControlPanel.enumerating = false private
Definition at line 14 of file StaticPage.cs.
FullUpdateAction TGControlPanel.ControlPanel.fuAction private
Definition at line 20 of file ServerPage.cs.
System.ComponentModel.BackgroundWorker TGControlPanel.ControlPanel.FullUpdateWorker private
Definition at line 1807 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), TGControlPanel.ControlPanel.InitServerPage(), and TGControlPanel.ControlPanel.RunServerUpdate().
System.Windows.Forms.TextBox TGControlPanel.ControlPanel.GameChannelsTextbox private
Definition at line 1818 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.ChatApplyButton_Click(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadChatPage().
System.Windows.Forms.Button TGControlPanel.ControlPanel.HardReset private
Definition at line 1902 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.DoAsyncOp(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.PopulateRepoFields().
System.Windows.Forms.Label TGControlPanel.ControlPanel.IdentityLabel private
Definition at line 1905 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.DoAsyncOp(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.PopulateRepoFields().
IDictionary<int, string> TGControlPanel.ControlPanel.IndexesToPaths = new Dictionary<int, string>() private
Definition at line 12 of file StaticPage.cs.
System.Windows.Forms.Button TGControlPanel.ControlPanel.initializeButton private
Definition at line 1874 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), TGControlPanel.ControlPanel.LoadServerPage(), and TGControlPanel.ControlPanel.RunServerUpdate().
readonly IInterface TGControlPanel.ControlPanel.Interface = new Dictionary<string, ControlPanel>() private
The IInterface instance for this ControlPanel
Definition at line 18 of file ControlPanel.cs.
System.Windows.Forms.ComboBox TGControlPanel.ControlPanel.IRCModesComboBox private
Definition at line 1814 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.ChatApplyButton_Click(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadChatPage().
System.Windows.Forms.RadioButton TGControlPanel.ControlPanel.IRCProviderSwitch private
Definition at line 1839 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), TGControlPanel.ControlPanel.IRCProviderSwitch_CheckedChanged(), and TGControlPanel.ControlPanel.LoadChatPage().
System.Windows.Forms.Label TGControlPanel.ControlPanel.label1 private
Definition at line 1815 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
System.Windows.Forms.Label TGControlPanel.ControlPanel.label2 private
Definition at line 1813 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
System.Windows.Forms.Label TGControlPanel.ControlPanel.label3 private
Definition at line 1812 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
System.Windows.Forms.Label TGControlPanel.ControlPanel.label4 private
Definition at line 1811 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
System.Windows.Forms.Label TGControlPanel.ControlPanel.label5 private
Definition at line 1810 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
System.Windows.Forms.Label TGControlPanel.ControlPanel.label6 private
Definition at line 1916 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
string TGControlPanel.ControlPanel.lastReadError = null private
Definition at line 10 of file ByondPage.cs.
System.Windows.Forms.Label TGControlPanel.ControlPanel.LatestVersionLabel private
Definition at line 1878 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitBYONDPage(), and TGControlPanel.ControlPanel.InitializeComponent().
System.Windows.Forms.Label TGControlPanel.ControlPanel.LatestVersionTitle private
Definition at line 1879 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
System.Windows.Forms.Label TGControlPanel.ControlPanel.MajorVersionLabel private
Definition at line 1886 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
System.Windows.Forms.NumericUpDown TGControlPanel.ControlPanel.MajorVersionNumeric private
Definition at line 1889 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitBYONDPage(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.UpdateButton_Click().
System.Windows.Forms.Button TGControlPanel.ControlPanel.MergePRButton private
Definition at line 1904 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.DoAsyncOp(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.PopulateRepoFields().
System.Windows.Forms.Label TGControlPanel.ControlPanel.MinorVersionLabel private
Definition at line 1885 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
System.Windows.Forms.NumericUpDown TGControlPanel.ControlPanel.MinorVersionNumeric private
Definition at line 1888 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitBYONDPage(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.UpdateButton_Click().
System.Windows.Forms.Panel TGControlPanel.ControlPanel.panel1 private
Definition at line 1843 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
System.Windows.Forms.TabControl TGControlPanel.ControlPanel.Panels private
Definition at line 1913 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.ControlPanel(), TGControlPanel.ControlPanel.InitializeComponent(), TGControlPanel.ControlPanel.Main_Resize(), and TGControlPanel.ControlPanel.Panels_SelectedIndexChanged().
System.Windows.Forms.Label TGControlPanel.ControlPanel.PortLabel private
Definition at line 1858 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadServerPage().
System.Windows.Forms.NumericUpDown TGControlPanel.ControlPanel.PortSelector private
Definition at line 1859 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), TGControlPanel.ControlPanel.LoadServerPage(), and TGControlPanel.ControlPanel.PortSelector_ValueChanged().
System.Windows.Forms.TextBox TGControlPanel.ControlPanel.projectNameText private
Definition at line 1931 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), TGControlPanel.ControlPanel.InitServerPage(), TGControlPanel.ControlPanel.LoadServerPage(), and TGControlPanel.ControlPanel.UpdateProjectName().
System.Windows.Forms.Label TGControlPanel.ControlPanel.ProjectPathLabel private
Definition at line 1857 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadServerPage().
System.Windows.Forms.Button TGControlPanel.ControlPanel.RecloneButton private
Definition at line 1894 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.DoAsyncOp(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.PopulateRepoFields().
System.Windows.Forms.Button TGControlPanel.ControlPanel.RecreateStaticButton private
Definition at line 1927 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), TGControlPanel.ControlPanel.InitStaticPage(), and TGControlPanel.ControlPanel.RecreateStaticButton_Click().
System.Windows.Forms.Label TGControlPanel.ControlPanel.RemoteNameTitle private
Definition at line 1907 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.DoAsyncOp(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.PopulateRepoFields().
System.Windows.Forms.Button TGControlPanel.ControlPanel.RepoApplyButton private
Definition at line 1901 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.DoAsyncOp(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.PopulateRepoFields().
System.ComponentModel.BackgroundWorker TGControlPanel.ControlPanel.RepoBGW private
Definition at line 1806 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.DoAsyncOp(), TGControlPanel.ControlPanel.InitializeComponent(), TGControlPanel.ControlPanel.InitRepoPage(), and TGControlPanel.ControlPanel.RepoBGW_DoWork().
System.Windows.Forms.TextBox TGControlPanel.ControlPanel.RepoBranchTextBox private
Definition at line 1895 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.CloneRepo(), TGControlPanel.ControlPanel.DoAsyncOp(), TGControlPanel.ControlPanel.InitializeComponent(), TGControlPanel.ControlPanel.PopulateRepoFields(), and TGControlPanel.ControlPanel.RepoApplyButton_Click().
string TGControlPanel.ControlPanel.repoError private
Definition at line 28 of file RepoPage.cs.
System.Windows.Forms.Button TGControlPanel.ControlPanel.RepoGenChangelogButton private
Definition at line 1897 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.DoAsyncOp(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.PopulateRepoFields().
System.Windows.Forms.TabPage TGControlPanel.ControlPanel.RepoPanel private
Definition at line 1890 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.DoAsyncOp(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.RepoBGW_RunWorkerCompleted().
System.Windows.Forms.ProgressBar TGControlPanel.ControlPanel.RepoProgressBar private
Definition at line 1912 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.DoAsyncOp(), TGControlPanel.ControlPanel.InitializeComponent(), TGControlPanel.ControlPanel.PopulateRepoFields(), TGControlPanel.ControlPanel.RepoBGW_ProgressChanged(), and TGControlPanel.ControlPanel.RepoBGW_RunWorkerCompleted().
System.Windows.Forms.Label TGControlPanel.ControlPanel.RepoProgressBarLabel private
Definition at line 1911 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.DoAsyncOp(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.PopulateRepoFields().
System.Windows.Forms.Button TGControlPanel.ControlPanel.RepoRefreshButton private
Definition at line 1891 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.DoAsyncOp(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.PopulateRepoFields().
System.Windows.Forms.TextBox TGControlPanel.ControlPanel.RepoRemoteTextBox private
Definition at line 1896 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.CloneRepo(), TGControlPanel.ControlPanel.DoAsyncOp(), TGControlPanel.ControlPanel.InitializeComponent(), TGControlPanel.ControlPanel.PopulateRepoFields(), and TGControlPanel.ControlPanel.RepoApplyButton_Click().
System.Windows.Forms.Button TGControlPanel.ControlPanel.ResetRemote private
Definition at line 1893 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.DoAsyncOp(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.PopulateRepoFields().
System.Windows.Forms.Button TGControlPanel.ControlPanel.ResetTestmerge private
Definition at line 1854 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadServerPage().
System.Windows.Forms.ComboBox TGControlPanel.ControlPanel.SecuritySelector private
Definition at line 1852 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), TGControlPanel.ControlPanel.LoadServerPage(), and TGControlPanel.ControlPanel.SecuritySelector_SelectedIndexChanged().
System.Windows.Forms.Label TGControlPanel.ControlPanel.SecurityTitle private
Definition at line 1853 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
System.Windows.Forms.Button TGControlPanel.ControlPanel.ServerGRestartButton private
Definition at line 1866 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadServerPage().
System.Windows.Forms.CheckBox TGControlPanel.ControlPanel.ServerGStopButton private
Definition at line 1867 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadServerPage().
System.Windows.Forms.Button TGControlPanel.ControlPanel.ServerPageRefreshButton private
Definition at line 1926 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
System.Windows.Forms.TabPage TGControlPanel.ControlPanel.ServerPanel private
Definition at line 1846 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
System.Windows.Forms.Label TGControlPanel.ControlPanel.ServerPathLabel private
Definition at line 1855 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadServerPage().
System.Windows.Forms.Label TGControlPanel.ControlPanel.ServerPRLabel private
Definition at line 1860 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadServerPage().
System.Windows.Forms.Button TGControlPanel.ControlPanel.ServerRestartButton private
Definition at line 1868 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadServerPage().
System.ComponentModel.BackgroundWorker TGControlPanel.ControlPanel.ServerStartBGW private
Definition at line 1808 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), TGControlPanel.ControlPanel.InitServerPage(), and TGControlPanel.ControlPanel.ServerStartButton_Click().
System.Windows.Forms.Button TGControlPanel.ControlPanel.ServerStartButton private
Definition at line 1870 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadServerPage().
System.Windows.Forms.Label TGControlPanel.ControlPanel.ServerStatusLabel private
Definition at line 1875 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadServerPage().
System.Windows.Forms.Label TGControlPanel.ControlPanel.ServerStatusTitle private
Definition at line 1876 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
System.Windows.Forms.Button TGControlPanel.ControlPanel.ServerStopButton private
Definition at line 1869 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadServerPage().
System.Windows.Forms.NumericUpDown TGControlPanel.ControlPanel.ServerTestmergeInput private
Definition at line 1861 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), TGControlPanel.ControlPanel.LoadServerPage(), TGControlPanel.ControlPanel.TestmergeButton_Click(), and TGControlPanel.ControlPanel.UpdateTestmergeButton_Click().
System.Windows.Forms.Label TGControlPanel.ControlPanel.StagedVersionLabel private
Definition at line 1880 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.UpdateBYONDButtons().
System.Windows.Forms.Label TGControlPanel.ControlPanel.StagedVersionTitle private
Definition at line 1881 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.UpdateBYONDButtons().
System.Windows.Forms.Button TGControlPanel.ControlPanel.StaticFileCreateButton private
Definition at line 1915 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
System.Windows.Forms.Button TGControlPanel.ControlPanel.StaticFileDeleteButton private
Definition at line 1920 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
System.Windows.Forms.Button TGControlPanel.ControlPanel.StaticFileDownloadButton private
Definition at line 1923 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
System.Windows.Forms.TextBox TGControlPanel.ControlPanel.StaticFileEditTextbox private
Definition at line 1919 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), TGControlPanel.ControlPanel.StaticFileCreateButton_Click(), TGControlPanel.ControlPanel.StaticFileDownloadButton_Click(), TGControlPanel.ControlPanel.StaticFileSaveButton_Click(), TGControlPanel.ControlPanel.StaticFileUploadButton_Click(), and TGControlPanel.ControlPanel.UpdateEditText().
System.Windows.Forms.ListBox TGControlPanel.ControlPanel.StaticFileListBox private
Definition at line 1917 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.BuildFileList(), TGControlPanel.ControlPanel.EnumeratePath(), TGControlPanel.ControlPanel.InitializeComponent(), TGControlPanel.ControlPanel.StaticFileCreateButton_Click(), TGControlPanel.ControlPanel.StaticFileDeleteButton_Click(), TGControlPanel.ControlPanel.StaticFileDownloadButton_Click(), TGControlPanel.ControlPanel.StaticFileSaveButton_Click(), TGControlPanel.ControlPanel.StaticFileUploadButton_Click(), and TGControlPanel.ControlPanel.UpdateEditText().
System.Windows.Forms.Button TGControlPanel.ControlPanel.StaticFileSaveButton private
Definition at line 1921 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
System.Windows.Forms.Button TGControlPanel.ControlPanel.StaticFilesRefreshButton private
Definition at line 1922 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
System.Windows.Forms.Button TGControlPanel.ControlPanel.StaticFileUploadButton private
Definition at line 1918 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
System.Windows.Forms.TabPage TGControlPanel.ControlPanel.StaticPanel private
Definition at line 1914 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
System.Windows.Forms.Label TGControlPanel.ControlPanel.StatusLabel private
Definition at line 1882 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.UpdateBYONDButtons().
System.Windows.Forms.Button TGControlPanel.ControlPanel.TestmergeButton private
Definition at line 1862 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.FullUpdateWorker_RunWorkerCompleted(), TGControlPanel.ControlPanel.InitializeComponent(), TGControlPanel.ControlPanel.LoadServerPage(), and TGControlPanel.ControlPanel.RunServerUpdate().
System.Windows.Forms.ListBox TGControlPanel.ControlPanel.TestMergeListLabel private
Definition at line 1899 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.DoAsyncOp(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.PopulateRepoFields().
System.Windows.Forms.Label TGControlPanel.ControlPanel.TestMergeListTitle private
Definition at line 1906 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.DoAsyncOp(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.PopulateRepoFields().
ushort TGControlPanel.ControlPanel.testmergePR private
Definition at line 21 of file ServerPage.cs.
System.Windows.Forms.NumericUpDown TGControlPanel.ControlPanel.TestmergeSelector private
Definition at line 1898 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.DoAsyncOp(), TGControlPanel.ControlPanel.InitializeComponent(), TGControlPanel.ControlPanel.PopulateRepoFields(), and TGControlPanel.ControlPanel.TestMergeButton_Click().
int TGControlPanel.ControlPanel.TestPR private
Definition at line 26 of file RepoPage.cs.
System.Windows.Forms.Button TGControlPanel.ControlPanel.TGSJsonUpdate private
Definition at line 1924 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.DoAsyncOp(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.PopulateRepoFields().
System.Windows.Forms.Button TGControlPanel.ControlPanel.UpdateButton private
Definition at line 1887 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.UpdateBYONDButtons().
string TGControlPanel.ControlPanel.updateError private
Definition at line 22 of file ServerPage.cs.
System.Windows.Forms.Button TGControlPanel.ControlPanel.UpdateHardButton private
Definition at line 1865 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.FullUpdateWorker_RunWorkerCompleted(), TGControlPanel.ControlPanel.InitializeComponent(), TGControlPanel.ControlPanel.LoadServerPage(), and TGControlPanel.ControlPanel.RunServerUpdate().
System.Windows.Forms.Button TGControlPanel.ControlPanel.UpdateMergeButton private
Definition at line 1864 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.FullUpdateWorker_RunWorkerCompleted(), TGControlPanel.ControlPanel.InitializeComponent(), TGControlPanel.ControlPanel.LoadServerPage(), and TGControlPanel.ControlPanel.RunServerUpdate().
System.Windows.Forms.Button TGControlPanel.ControlPanel.UpdateRepoButton private
Definition at line 1903 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.DoAsyncOp(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.PopulateRepoFields().
System.Windows.Forms.Button TGControlPanel.ControlPanel.UpdateTestmergeButton private
Definition at line 1863 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.FullUpdateWorker_RunWorkerCompleted(), TGControlPanel.ControlPanel.InitializeComponent(), TGControlPanel.ControlPanel.LoadServerPage(), and TGControlPanel.ControlPanel.RunServerUpdate().
bool TGControlPanel.ControlPanel.updatingChat = false private
Definition at line 11 of file ChatPage.cs.
bool TGControlPanel.ControlPanel.updatingFields = false private
Definition at line 23 of file ServerPage.cs.
System.Windows.Forms.Label TGControlPanel.ControlPanel.VersionLabel private
Definition at line 1883 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.UpdateBYONDButtons().
System.Windows.Forms.Label TGControlPanel.ControlPanel.VersionTitle private
Definition at line 1884 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent().
System.Windows.Forms.TextBox TGControlPanel.ControlPanel.WDChannelsTextbox private
Definition at line 1817 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.ChatApplyButton_Click(), TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadChatPage().
System.Windows.Forms.CheckBox TGControlPanel.ControlPanel.WebclientCheckBox private
Definition at line 1848 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), TGControlPanel.ControlPanel.LoadServerPage(), and TGControlPanel.ControlPanel.WebclientCheckBox_CheckedChanged().
System.Windows.Forms.Button TGControlPanel.ControlPanel.WorldAnnounceButton private
Definition at line 1849 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadServerPage().
System.Windows.Forms.TextBox TGControlPanel.ControlPanel.WorldAnnounceField private
Definition at line 1850 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), TGControlPanel.ControlPanel.LoadServerPage(), and TGControlPanel.ControlPanel.WorldAnnounceButton_Click().
System.Windows.Forms.Label TGControlPanel.ControlPanel.WorldAnnounceLabel private
Definition at line 1851 of file ControlPanel.Designer.cs.
Referenced by TGControlPanel.ControlPanel.InitializeComponent(), and TGControlPanel.ControlPanel.LoadServerPage().
Property Documentation
IDictionary<string, ControlPanel> TGControlPanel.ControlPanel.InstancesInUse static get private set
List of instances being used by open control panels
Definition at line 18 of file ControlPanel.cs.
Referenced by TGControlPanel.ControlPanel.Cleanup(), TGControlPanel.ControlPanel.ControlPanel(), and TGControlPanel.InstanceSelector.TryConnectToInstance().
ChatProvider TGControlPanel.ControlPanel.ModifyingProvider get set private
Definition at line 14 of file ChatPage.cs.
Referenced by TGControlPanel.ControlPanel.ChatApplyButton_Click(), TGControlPanel.ControlPanel.ChatReconnectButton_Click(), TGControlPanel.ControlPanel.DiscordProviderSwitch_CheckedChanged(), TGControlPanel.ControlPanel.IRCProviderSwitch_CheckedChanged(), TGControlPanel.ControlPanel.LoadChatPage(), and TGControlPanel.ControlPanel.SetAdminsAreSpecial().
The documentation for this class was generated from the following files:
TGControlPanel/ControlPanel/ByondPage.cs
TGControlPanel/ControlPanel/ChatPage.cs
TGControlPanel/ControlPanel/ControlPanel.cs
TGControlPanel/ControlPanel/ControlPanel.Designer.cs
TGControlPanel/ControlPanel/RepoPage.cs
TGControlPanel/ControlPanel/ServerPage.cs
TGControlPanel/ControlPanel/StaticPage.cs