tgstation-server: Tgstation.Server.Host.Security.AuthenticationContextFactory Class Reference
Tgstation.Server.Host.Security.AuthenticationContextFactory Class Reference sealed
Public Member Functions
AuthenticationContextFactory (IDatabaseContext databaseContext, IIdentityCache identityCache, IApiHeadersProvider apiHeadersProvider, IOptions< SwarmConfiguration > swarmConfigurationOptions, IOptions< SecurityConfiguration > securityConfigurationOptions, ILogger< AuthenticationContextFactory > logger)
Initializes a new instance of the AuthenticationContextFactory class.
void Dispose ()
async Task ValidateTgsToken (Microsoft.AspNetCore.Authentication.JwtBearer.TokenValidatedContext tokenValidatedContext, CancellationToken cancellationToken)
Handles TGS tokenValidatedContext s.
Parameters
tokenValidatedContext The Microsoft.AspNetCore.Authentication.JwtBearer.TokenValidatedContext.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
async Task ValidateOidcToken (RemoteAuthenticationContext< OpenIdConnectOptions > tokenValidatedContext, string schemeKey, string groupIdClaimName, CancellationToken cancellationToken)
Handles OIDC tokenValidatedContext s.
Parameters
tokenValidatedContext The RemoteAuthenticationContext<TOptions> for OpenIdConnectOptions.
schemeKey The scheme key being used to login.
groupIdClaimName The name of the global::System.Security.Claims.Claim used to set the user's group ID.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Static Public Attributes
const string OpenIDConnectAuthenticationSchemePrefix = $"{OpenIdConnectDefaults.AuthenticationScheme}."
Internal scheme prefix for OIDC schemes.
Properties
IAuthenticationContext CurrentAuthenticationContext [get]
The IAuthenticationContext the AuthenticationContextFactory created.
Static Private Member Functions
static DateTimeOffset ParseTime (ClaimsPrincipal principal, string key)
Parse a DateTimeOffset out of a Claim in a given principal .
Private Attributes
readonly IDatabaseContext databaseContext
The IDatabaseContext for the AuthenticationContextFactory.
readonly IIdentityCache identityCache
The IIdentityCache for the AuthenticationContextFactory.
readonly ILogger< AuthenticationContextFactory > logger
The ILogger for the AuthenticationContextFactory.
readonly SwarmConfiguration swarmConfiguration
The SwarmConfiguration for the AuthenticationContextFactory.
readonly SecurityConfiguration securityConfiguration
The SecurityConfiguration for the AuthenticationContextFactory.
readonly AuthenticationContext currentAuthenticationContext
Backing field for CurrentAuthenticationContext.
readonly? ApiHeaders apiHeaders
The ApiHeaders for the AuthenticationContextFactory.
int initialized
1 if currentAuthenticationContext was initialized, 0 otherwise.
Detailed Description
Definition at line 28 of file AuthenticationContextFactory.cs.
Constructor & Destructor Documentation
AuthenticationContextFactory()
Tgstation.Server.Host.Security.AuthenticationContextFactory.AuthenticationContextFactory (IDatabaseContext databaseContext, IIdentityCache identityCache, IApiHeadersProvider apiHeadersProvider, IOptions< SwarmConfiguration > swarmConfigurationOptions, IOptions< SecurityConfiguration > securityConfigurationOptions, ILogger< AuthenticationContextFactory > logger)
Initializes a new instance of the AuthenticationContextFactory class.
Parameters
databaseContext The value of databaseContext.
identityCache The value of identityCache.
apiHeadersProvider The IApiHeadersProvider containing the value of apiHeaders.
swarmConfigurationOptions The IOptions<TOptions> containing the value of swarmConfiguration.
securityConfigurationOptions The IOptions<TOptions> containing the value of securityConfiguration.
logger The value of logger.
Definition at line 113 of file AuthenticationContextFactory.cs.
        {
            this.databaseContext = databaseContext ?? throw new ArgumentNullException(nameof(databaseContext));
            this.identityCache = identityCache ?? throw new ArgumentNullException(nameof(identityCache));
            ArgumentNullException.ThrowIfNull(apiHeadersProvider);
            apiHeaders = apiHeadersProvider.ApiHeaders;
            swarmConfiguration = swarmConfigurationOptions?.Value ?? throw new ArgumentNullException(nameof(swarmConfigurationOptions));
            securityConfiguration = securityConfigurationOptions?.Value ?? throw new ArgumentNullException(nameof(securityConfigurationOptions));
            this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
            currentAuthenticationContext = new AuthenticationContext();
        }
References Tgstation.Server.Host.Security.AuthenticationContextFactory.apiHeaders, Tgstation.Server.Host.Utils.IApiHeadersProvider.ApiHeaders, Tgstation.Server.Host.Security.AuthenticationContextFactory.currentAuthenticationContext, Tgstation.Server.Host.Security.AuthenticationContextFactory.databaseContext, Tgstation.Server.Host.Security.AuthenticationContextFactory.identityCache, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Security.AuthenticationContextFactory.logger, Tgstation.Server.Host.Security.AuthenticationContextFactory.securityConfiguration, and Tgstation.Server.Host.Security.AuthenticationContextFactory.swarmConfiguration.
Member Function Documentation
Dispose()
void Tgstation.Server.Host.Security.AuthenticationContextFactory.Dispose ()
ParseTime()
static DateTimeOffset Tgstation.Server.Host.Security.AuthenticationContextFactory.ParseTime (ClaimsPrincipal principal, string key) static private
Parse a DateTimeOffset out of a Claim in a given principal .
Parameters
principal The ClaimsPrincipal containing claims.
key The Claim name to parse from.
Returns
The parsed DateTimeOffset.
Definition at line 86 of file AuthenticationContextFactory.cs.
        {
            var claim = principal.FindFirst(key);
            if (claim == default)
                throw new InvalidOperationException($"Missing '{key}' claim!");
            try
            {
                return new DateTimeOffset(
                    EpochTime.DateTime(
                        Int64.Parse(claim.Value, CultureInfo.InvariantCulture)));
            }
            catch (Exception ex)
            {
                throw new InvalidOperationException($"Failed to parse '{key}'!", ex);
            }
        }
References Tgstation.Server.Api.Rights.List.
Referenced by Tgstation.Server.Host.Security.AuthenticationContextFactory.ValidateOidcToken(), and Tgstation.Server.Host.Security.AuthenticationContextFactory.ValidateTgsToken().
ValidateOidcToken()
async Task Tgstation.Server.Host.Security.AuthenticationContextFactory.ValidateOidcToken (RemoteAuthenticationContext< OpenIdConnectOptions > tokenValidatedContext, string schemeKey, string groupIdClaimName, CancellationToken cancellationToken)
Handles OIDC tokenValidatedContext s.
Parameters
tokenValidatedContext The RemoteAuthenticationContext<TOptions> for OpenIdConnectOptions.
schemeKey The scheme key being used to login.
groupIdClaimName The name of the global::System.Security.Claims.Claim used to set the user's group ID.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implements Tgstation.Server.Host.Security.ITokenValidator.
Definition at line 232 of file AuthenticationContextFactory.cs.
        {
            ArgumentNullException.ThrowIfNull(tokenValidatedContext);
            var principal = tokenValidatedContext.Principal;
            if (principal == null)
                throw new InvalidOperationException("Expected a valid principal here!");
            var userIdClaim = principal.FindFirst(JwtRegisteredClaimNames.Sub);
            if (userIdClaim == default)
                throw new InvalidOperationException($"Missing '{JwtRegisteredClaimNames.Sub}' claim!");
            var userId = userIdClaim.Value;
            var scheme = tokenValidatedContext.Scheme.Name;
            var deprefixedScheme = scheme.Substring(OpenIDConnectAuthenticationSchemePrefix.Length);
            var connection = await databaseContext
                .OidcConnections
                .AsQueryable()
                .Where(oidcConnection => oidcConnection.ExternalUserId == userId && oidcConnection.SchemeKey == deprefixedScheme)
                .Include(oidcConnection => oidcConnection.User)
                    .ThenInclude(user => user!.Group)
                        .ThenInclude(group => group!.PermissionSet)
                .FirstOrDefaultAsync(cancellationToken);
            User user;
            if (!securityConfiguration.OidcStrictMode)
            {
                if (connection == default)
                {
                    tokenValidatedContext.Fail($"Unable to find user with OidcConnection for {deprefixedScheme}/{userId}!");
                    return;
                }
                user = connection.User!;
            }
            else
            {
                var groupClaim = principal.FindFirst(groupIdClaimName);
                long? groupId;
                if (groupClaim == default)
                    groupId = null;
                else if (Int64.TryParse(groupClaim.Value, out long groupIdParsed))
                    groupId = groupIdParsed;
                else
                {
                    tokenValidatedContext.Fail($"User has non-numeric '{groupIdClaimName}' claim!");
                    return;
                }
                UserGroup? group = groupId.HasValue
                    ? await databaseContext
                        .Groups
                        .AsQueryable()
                        .Where(group => group.Id == groupId.Value)
                        .Include(group => group.PermissionSet)
                        .FirstOrDefaultAsync(cancellationToken)
                    : null;
                var missingClaimError = $"User missing '{groupIdClaimName}' claim!";
                if (connection == default)
                {
                    var username = principal.Identity?.Name;
                    if (username == null)
                    {
                        tokenValidatedContext.Fail("Failed to retrieve user's name from retrieved claims!");
                        return;
                    }
                    if (username.Contains(':', StringComparison.Ordinal))
                    {
                        tokenValidatedContext.Fail("Cannot create users with the ':' in their name!");
                        return;
                    }
                    if (group == null)
                    {
                        tokenValidatedContext.Fail(
                            groupId.HasValue
                                ? $"'{groupIdClaimName}' does not point to a valid group!"
                                : missingClaimError);
                        return;
                    }
                    logger.LogInformation("Registering new user '{name}' via OIDC scheme '{scheme}'", username, schemeKey);
                    var tgsUser = await databaseContext
                        .Users
                        .GetTgsUser(
                            dbUser => new User
{
                                Id = dbUser.Id!.Value,
                            },
                            cancellationToken);
                    user = new User
                    {
                        CreatedAt = DateTimeOffset.UtcNow,
                        CanonicalName = User.CanonicalizeName(username),
                        Name = username,
                        CreatedById = tgsUser.Id,
                        Enabled = true,
                        GroupId = group.Id,
                        OidcConnections = new List<OidcConnection>
{
                            new()
{
                                SchemeKey = schemeKey,
                                ExternalUserId = userId,
                            },
                        },
                        PasswordHash = "_", // This can't be hashed
                    };
                    databaseContext.Users.Add(user);
                }
                else
                {
                    user = connection.User!;
                    // group update
                    if (group == null)
                    {
                        logger.LogDebug("User {id} attempted to login via OIDC scheme '{scheme}' but had no group ID claim ('{groupClaimName}') and will be disabled", user.Id, schemeKey, groupIdClaimName);
                        user.PermissionSet = new PermissionSet
{
                            AdministrationRights = AdministrationRights.None,
                            InstanceManagerRights = InstanceManagerRights.None,
                        };
                        user.GroupId = null;
                        user.Enabled = false;
                        tokenValidatedContext.Fail(missingClaimError);
                        return;
                    }
                    logger.LogDebug("User {id} mapped to group {groupId} via OIDC login on scheme '{scheme}'", user.Id, groupId, schemeKey);
                    user.Group = group;
                    if (user.PermissionSet != null)
                        databaseContext.PermissionSets.Remove(user.PermissionSet);
                    user.Enabled = true;
                }
                await databaseContext.Save(cancellationToken);
            }
            var expires = ParseTime(principal, JwtRegisteredClaimNames.Exp);
            currentAuthenticationContext.Initialize(
                user,
                expires,
                Guid.NewGuid().ToString(),
                null,
                null);
        }
References Tgstation.Server.Host.Database.IDatabaseCollection< TModel >.Add(), Tgstation.Server.Host.Models.User.CanonicalizeName(), Tgstation.Server.Host.Security.AuthenticationContextFactory.currentAuthenticationContext, Tgstation.Server.Host.Security.AuthenticationContextFactory.databaseContext, Tgstation.Server.Host.Enabled, Tgstation.Server.Host.Database.IDatabaseContext.Groups, Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Host.Security.AuthenticationContext.Initialize(), Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Security.AuthenticationContextFactory.logger, Tgstation.Server.Host.Database.IDatabaseContext.OidcConnections, Tgstation.Server.Host.Configuration.SecurityConfiguration.OidcStrictMode, Tgstation.Server.Host.Security.AuthenticationContextFactory.OpenIDConnectAuthenticationSchemePrefix, Tgstation.Server.Host.Security.AuthenticationContextFactory.ParseTime(), Tgstation.Server.Host.Models.User.PermissionSet, Tgstation.Server.Host.Database.IDatabaseContext.PermissionSets, Tgstation.Server.Host.Database.IDatabaseCollection< TModel >.Remove(), Tgstation.Server.Host.Database.IDatabaseContext.Save(), Tgstation.Server.Host.Security.AuthenticationContextFactory.securityConfiguration, and Tgstation.Server.Host.Database.IDatabaseContext.Users.
ValidateTgsToken()
async Task Tgstation.Server.Host.Security.AuthenticationContextFactory.ValidateTgsToken (Microsoft::AspNetCore::Authentication::JwtBearer::TokenValidatedContext tokenValidatedContext, CancellationToken cancellationToken)
Handles TGS tokenValidatedContext s.
Parameters
tokenValidatedContext The Microsoft.AspNetCore.Authentication.JwtBearer.TokenValidatedContext.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implements Tgstation.Server.Host.Security.ITokenValidator.
Definition at line 139 of file AuthenticationContextFactory.cs.
        {
            ArgumentNullException.ThrowIfNull(tokenValidatedContext);
            if (tokenValidatedContext.SecurityToken is not JsonWebToken jwt)
                throw new ArgumentException($"Expected {nameof(tokenValidatedContext)} to contain a {nameof(JsonWebToken)}!", nameof(tokenValidatedContext));
            if (Interlocked.Exchange(ref initialized, 1) != 0)
                throw new InvalidOperationException("Authentication context has already been loaded");
            var principal = new ClaimsPrincipal(new ClaimsIdentity(jwt.Claims));
            var userIdClaim = principal.FindFirst(JwtRegisteredClaimNames.Sub);
            if (userIdClaim == default)
                throw new InvalidOperationException($"Missing '{JwtRegisteredClaimNames.Sub}' claim!");
            long userId;
            try
            {
                userId = Int64.Parse(userIdClaim.Value, CultureInfo.InvariantCulture);
            }
            catch (Exception e)
            {
                throw new InvalidOperationException("Failed to parse user ID!", e);
            }
            var notBefore = ParseTime(principal, JwtRegisteredClaimNames.Nbf);
            var expires = ParseTime(principal, JwtRegisteredClaimNames.Exp);
            var user = await databaseContext
                .Users
                .AsQueryable()
                .Where(x => x.Id == userId)
                .Include(x => x.CreatedBy)
                .Include(x => x.PermissionSet)
                .Include(x => x.Group)
                    .ThenInclude(x => x!.PermissionSet)
                .Include(x => x.OAuthConnections)
                .FirstOrDefaultAsync(cancellationToken);
            if (user == default)
            {
                tokenValidatedContext.Fail($"Unable to find user with ID {userId}!");
                return;
            }
            ISystemIdentity? systemIdentity;
            if (user.SystemIdentifier != null)
                systemIdentity = identityCache.LoadCachedIdentity(user);
            else
            {
                if (user.LastPasswordUpdate.HasValue && user.LastPasswordUpdate >= notBefore)
                {
                    tokenValidatedContext.Fail($"Rejecting token for user {userId} created before last modification: {user.LastPasswordUpdate.Value}");
                    return;
                }
                systemIdentity = null;
            }
            var userPermissionSet = user.PermissionSet ?? user.Group!.PermissionSet;
            try
            {
                InstancePermissionSet? instancePermissionSet = null;
                var instanceId = apiHeaders?.InstanceId;
                if (instanceId.HasValue)
                {
                    instancePermissionSet = await databaseContext.InstancePermissionSets
                        .AsQueryable()
                        .Where(x => x.PermissionSetId == userPermissionSet!.Id && x.InstanceId == instanceId && x.Instance!.SwarmIdentifer == swarmConfiguration.Identifier)
                        .Include(x => x.Instance)
                        .FirstOrDefaultAsync(cancellationToken);
                    if (instancePermissionSet == null)
                        logger.LogDebug("User {userId} does not have permissions on instance {instanceId}!", userId, instanceId.Value);
                }
                currentAuthenticationContext.Initialize(
                    user,
                    expires,
                    jwt.EncodedSignature, // signature is enough to uniquely identify the session as it is composite of all the inputs
                    instancePermissionSet,
                    systemIdentity);
            }
            catch
            {
                systemIdentity?.Dispose();
                throw;
            }
        }
References Tgstation.Server.Host.Security.AuthenticationContextFactory.apiHeaders, Tgstation.Server.Host.Security.AuthenticationContextFactory.currentAuthenticationContext, Tgstation.Server.Host.Security.AuthenticationContextFactory.databaseContext, Tgstation.Server.Api.Models.Internal.SwarmServer.Identifier, Tgstation.Server.Host.Security.AuthenticationContextFactory.identityCache, Tgstation.Server.Host.Security.AuthenticationContext.Initialize(), Tgstation.Server.Host.Security.AuthenticationContextFactory.initialized, Tgstation.Server.Api.ApiHeaders.InstanceId, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Security.IIdentityCache.LoadCachedIdentity(), Tgstation.Server.Host.Security.AuthenticationContextFactory.logger, Tgstation.Server.Host.Security.AuthenticationContextFactory.ParseTime(), Tgstation.Server.Host.Security.AuthenticationContextFactory.swarmConfiguration, and Tgstation.Server.Host.Database.IDatabaseContext.Users.
Member Data Documentation
apiHeaders
readonly? ApiHeaders Tgstation.Server.Host.Security.AuthenticationContextFactory.apiHeaders private
The ApiHeaders for the AuthenticationContextFactory.
Definition at line 73 of file AuthenticationContextFactory.cs.
Referenced by Tgstation.Server.Host.Security.AuthenticationContextFactory.AuthenticationContextFactory(), and Tgstation.Server.Host.Security.AuthenticationContextFactory.ValidateTgsToken().
currentAuthenticationContext
readonly AuthenticationContext Tgstation.Server.Host.Security.AuthenticationContextFactory.currentAuthenticationContext private
Backing field for CurrentAuthenticationContext.
Definition at line 68 of file AuthenticationContextFactory.cs.
Referenced by Tgstation.Server.Host.Security.AuthenticationContextFactory.AuthenticationContextFactory(), Tgstation.Server.Host.Security.AuthenticationContextFactory.ValidateOidcToken(), and Tgstation.Server.Host.Security.AuthenticationContextFactory.ValidateTgsToken().
databaseContext
readonly IDatabaseContext Tgstation.Server.Host.Security.AuthenticationContextFactory.databaseContext private
The IDatabaseContext for the AuthenticationContextFactory.
Definition at line 43 of file AuthenticationContextFactory.cs.
Referenced by Tgstation.Server.Host.Security.AuthenticationContextFactory.AuthenticationContextFactory(), Tgstation.Server.Host.Security.AuthenticationContextFactory.ValidateOidcToken(), and Tgstation.Server.Host.Security.AuthenticationContextFactory.ValidateTgsToken().
identityCache
readonly IIdentityCache Tgstation.Server.Host.Security.AuthenticationContextFactory.identityCache private
The IIdentityCache for the AuthenticationContextFactory.
Definition at line 48 of file AuthenticationContextFactory.cs.
Referenced by Tgstation.Server.Host.Security.AuthenticationContextFactory.AuthenticationContextFactory(), and Tgstation.Server.Host.Security.AuthenticationContextFactory.ValidateTgsToken().
initialized
int Tgstation.Server.Host.Security.AuthenticationContextFactory.initialized private
1 if currentAuthenticationContext was initialized, 0 otherwise.
Definition at line 78 of file AuthenticationContextFactory.cs.
Referenced by Tgstation.Server.Host.Security.AuthenticationContextFactory.ValidateTgsToken().
logger
readonly ILogger<AuthenticationContextFactory> Tgstation.Server.Host.Security.AuthenticationContextFactory.logger private
The ILogger for the AuthenticationContextFactory.
Definition at line 53 of file AuthenticationContextFactory.cs.
Referenced by Tgstation.Server.Host.Security.AuthenticationContextFactory.AuthenticationContextFactory(), Tgstation.Server.Host.Security.AuthenticationContextFactory.ValidateOidcToken(), and Tgstation.Server.Host.Security.AuthenticationContextFactory.ValidateTgsToken().
OpenIDConnectAuthenticationSchemePrefix
const string Tgstation.Server.Host.Security.AuthenticationContextFactory.OpenIDConnectAuthenticationSchemePrefix = $"{OpenIdConnectDefaults.AuthenticationScheme}." static
Internal scheme prefix for OIDC schemes.
Definition at line 33 of file AuthenticationContextFactory.cs.
Referenced by Tgstation.Server.Host.Security.AuthenticationContextFactory.ValidateOidcToken().
securityConfiguration
readonly SecurityConfiguration Tgstation.Server.Host.Security.AuthenticationContextFactory.securityConfiguration private
The SecurityConfiguration for the AuthenticationContextFactory.
Definition at line 63 of file AuthenticationContextFactory.cs.
Referenced by Tgstation.Server.Host.Security.AuthenticationContextFactory.AuthenticationContextFactory(), and Tgstation.Server.Host.Security.AuthenticationContextFactory.ValidateOidcToken().
swarmConfiguration
readonly SwarmConfiguration Tgstation.Server.Host.Security.AuthenticationContextFactory.swarmConfiguration private
The SwarmConfiguration for the AuthenticationContextFactory.
Definition at line 58 of file AuthenticationContextFactory.cs.
Referenced by Tgstation.Server.Host.Security.AuthenticationContextFactory.AuthenticationContextFactory(), and Tgstation.Server.Host.Security.AuthenticationContextFactory.ValidateTgsToken().
Property Documentation
CurrentAuthenticationContext
IAuthenticationContext Tgstation.Server.Host.Security.AuthenticationContextFactory.CurrentAuthenticationContext get
The IAuthenticationContext the AuthenticationContextFactory created.
Definition at line 38 of file AuthenticationContextFactory.cs.
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Security/AuthenticationContextFactory.cs