tgstation-server: Tgstation.Server.Host.Components.Repository.Repository Class Reference
Tgstation.Server.Host.Components.Repository.Repository Class Reference sealed
Public Member Functions
Repository (LibGit2Sharp.IRepository libGitRepo, ILibGit2Commands commands, IIOManager ioManager, IEventConsumer eventConsumer, ICredentialsProvider credentialsProvider, IPostWriteHandler postWriteHandler, IGitRemoteFeaturesFactory gitRemoteFeaturesFactory, ILibGit2RepositoryFactory submoduleFactory, IOptionsMonitor< GeneralConfiguration > generalConfigurationOptions, ILogger< Repository > logger, Action disposeAction)
Initializes a new instance of the Repository class.
async ValueTask< TestMergeResult > AddTestMerge (TestMergeParameters testMergeParameters, string committerName, string committerEmail, string? username, string? password, bool updateSubmodules, JobProgressReporter progressReporter, CancellationToken cancellationToken)
Attempt to merge the revision specified by a given set of testMergeParameters into HEAD.
Parameters
testMergeParameters The TestMergeParameters of the pull request.
committerName The name of the merge committer.
committerEmail The e-mail of the merge committer.
username The optional username used to fetch from the origin and submodule repositories.
password The optional password used to fetch from the origin and submodule repositories.
updateSubmodules If a submodule update should be attempted after the merge.
progressReporter The JobProgressReporter to report progress of the operation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the TestMergeResult.
async ValueTask CheckoutObject (string committish, string? username, string? password, bool updateSubmodules, bool moveCurrentReference, JobProgressReporter progressReporter, CancellationToken cancellationToken)
Checks out a given committish .
Parameters
committish The sha or reference to checkout.
username The optional username used for fetching from submodule repositories.
password The optional password used for fetching from submodule repositories.
updateSubmodules If a submodule update should be attempted after the merge.
moveCurrentReference If a hard reset to the target committish should be performed instead of a checkout.
progressReporter The JobProgressReporter to report progress of the operation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
async ValueTask FetchOrigin (JobProgressReporter progressReporter, string? username, string? password, bool deploymentPipeline, CancellationToken cancellationToken)
Fetch commits from the origin repository.
Parameters
progressReporter The JobProgressReporter to report progress of the operation.
username The optional username to fetch from the origin repository.
password The optional password to fetch from the origin repository.
deploymentPipeline If any events created should be marked as part of the deployment pipeline.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
async ValueTask ResetToOrigin (JobProgressReporter progressReporter, string? username, string? password, bool updateSubmodules, bool deploymentPipeline, CancellationToken cancellationToken)
Requires the current HEAD to be a tracked reference. Hard resets the reference to what it tracks on the origin repository.
Parameters
progressReporter The JobProgressReporter to report progress of the operation.
username The optional username used for fetching from submodule repositories.
password The optional password used for fetching from submodule repositories.
updateSubmodules If a submodule update should be attempted after the merge.
deploymentPipeline If any events created should be marked as part of the deployment pipeline.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the SHA of the new HEAD.
Task ResetToSha (string sha, JobProgressReporter progressReporter, CancellationToken cancellationToken)
Requires the current HEAD to be a reference. Hard resets the reference to the given sha.
Parameters
sha The sha hash to reset to.
progressReporter The JobProgressReporter to report progress of the operation.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the SHA of the new HEAD.
async ValueTask CopyTo (string path, CancellationToken cancellationToken)
Copies the current working directory to a given path .
Parameters
path The path to copy repository contents to.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Task< string > GetOriginSha (CancellationToken cancellationToken)
Get the tracked reference's current SHA.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the tracked origin reference's SHA.
async ValueTask< bool?> MergeOrigin (JobProgressReporter progressReporter, string committerName, string committerEmail, bool deploymentPipeline, CancellationToken cancellationToken)
Requires the current HEAD to be a tracked reference. Merges the reference to what it tracks on the origin repository.
Parameters
progressReporter The JobProgressReporter to report progress of the operation.
committerName The name of the merge committer.
committerEmail The e-mail of the merge committer.
deploymentPipeline If any events created should be marked as part of the deployment pipeline.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a Nullable<T> bool representing the merge result that is true after a fast forward, false on a merge or up to date, null on a conflict.
async ValueTask< bool > Synchronize (JobProgressReporter progressReporter, string? username, string? password, string committerName, string committerEmail, bool synchronizeTrackedBranch, bool deploymentPipeline, CancellationToken cancellationToken)
Runs the synchronize event script and attempts to push any changes made to the IRepository if on a tracked branch.
Parameters
progressReporter The JobProgressReporter to report progress of the operation.
username The username to fetch from the origin repository.
password The password to fetch from the origin repository.
committerName The name of the potential committer.
committerEmail The e-mail of the potential committer.
synchronizeTrackedBranch If the synchronizations should be made to the tracked reference as opposed to a temporary branch.
deploymentPipeline If any events created should be marked as part of the deployment pipeline.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in true if commits were pushed to the tracked origin reference, false otherwise.
Task< bool > IsSha (string committish, CancellationToken cancellationToken)
Checks if a given committish is a sha.
Parameters
committish The git object to check.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in true if committish is a sha, false otherwise.
Task< bool > CommittishIsParent (string committish, CancellationToken cancellationToken)
Check if a given committish is a parent of the current Head.
Parameters
committish The committish of the SHA to check.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in true if committish is a parent of Head, false otherwise.
This function is NOT reentrant.
ValueTask< Models.TestMerge > GetTestMerge (TestMergeParameters parameters, RepositorySettings repositorySettings, CancellationToken cancellationToken)
Retrieve the Models.TestMerge representation of given test merge parameters .
Parameters
parameters The TestMergeParameters.
repositorySettings The RepositorySettings.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the Models.TestMerge of the parameters .
TestMergeApiBase.MergedAt and Models.TestMerge.MergedBy will be unset.
Task< DateTimeOffset > TimestampCommit (string sha, CancellationToken cancellationToken)
Gets the DateTimeOffset a given sha was created on.
Parameters
sha The SHA to timestamp.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the DateTimeOffset that sha was created on.
Public Member Functions inherited from Tgstation.Server.Host.Utils.DisposeInvoker
DisposeInvoker (Action disposeAction)
Initializes a new instance of the DisposeInvoker class.
void Dispose ()
Static Public Attributes
const string DefaultCommitterName = "tgstation-server"
The default username for committers.
const string DefaultCommitterEmail = "tgstation-server@users.noreply.github.com"
The default password for committers.
const string OriginTrackingErrorTemplate = "Unable to determine most recent origin commit of {sha}. Marking it as an origin commit. This may result in invalid git metadata until the next hard reset to an origin reference."
Template error message for when tracking of the most recent origin commit fails.
const string RemoteTemporaryBranchName = "___TGSTempBranch"
The branch name used for publishing testmerge commits.
const string NoReference = "(no branch)"
The value of Reference when not on a reference.
Protected Member Functions
override void DisposeImpl ()
Implementation of Dispose run after reentrancy check.
Properties
RemoteGitProvider? RemoteGitProvider [get]
The Models.RemoteGitProvider in use by the repository.
string? RemoteRepositoryOwner [get]
If RemoteGitProvider is not RemoteGitProvider.Unknown this will be set with the owner of the repository.
string? RemoteRepositoryName [get]
If RemoteGitProvider is not RemoteGitProvider.Unknown this will be set with the name of the repository.
bool Tracking [get]
If Reference tracks an upstream branch.
string Head [get]
The SHA of the IRepository HEAD.
string Reference [get]
The current reference the IRepository HEAD is using. This can be a branch or tag.
Uri Origin [get]
The current origin remote the IRepository is using.
Properties inherited from Tgstation.Server.Host.Utils.DisposeInvoker
bool IsDisposed [get]
If Dispose was called.
Properties inherited from Tgstation.Server.Host.Components.Repository.IRepository
Properties inherited from Tgstation.Server.Api.Models.Internal.IGitRemoteInformation
Private Member Functions
void RawCheckout (string committish, bool moveCurrentReference, JobProgressReporter progressReporter, CancellationToken cancellationToken)
Runs a blocking force checkout to committish .
Task PushHeadToTemporaryBranch (CredentialsHandler credentialsHandler, JobProgressReporter progressReporter, CancellationToken cancellationToken)
Force push the current repository HEAD to RemoteTemporaryBranchName;.
async ValueTask<(PushOptions PushOptions, IEnumerable< JobProgressReporter > SubProgressReporters)> GeneratePushOptions (JobProgressReporter progressReporter, string username, string password, CancellationToken cancellationToken)
Generate a standard set of PushOptions.
string GetRepositoryPath ()
Gets the path of libGitRepo.
ValueTask UpdateSubmodules (JobProgressReporter progressReporter, string? username, string? password, bool deploymentPipeline, CancellationToken cancellationToken)
Recusively update all Submodules in the libGitRepo.
ValueTask< CredentialsHandler > GenerateCredentialsHandler (string? username, string? password, CancellationToken cancellationToken)
Generate a CredentialsHandler from a given username and password .
CheckoutProgressHandler CheckoutProgressHandler (JobProgressReporter progressReporter)
Converts a given progressReporter to a LibGit2Sharp.Handlers.CheckoutProgressHandler.
Static Private Member Functions
static PushOptions IEnumerable< JobProgressReporter > SubProgressReporters GeneratePushOptions (JobProgressReporter progressReporter, CredentialsHandler credentialsHandler, CancellationToken cancellationToken)
Private Attributes
readonly LibGit2Sharp.IRepository libGitRepo
The LibGit2Sharp.IRepository for the Repository.
readonly ILibGit2Commands commands
The ILibGit2Commands for the Repository.
readonly IIOManager ioManager
The IIOManager for the Repository.
readonly IEventConsumer eventConsumer
The IEventConsumer for the Repository.
readonly ICredentialsProvider credentialsProvider
The ICredentialsProvider for the Repository.
readonly IPostWriteHandler postWriteHandler
The IPostWriteHandler for the Repository.
readonly IGitRemoteFeatures gitRemoteFeatures
The IGitRemoteFeatures for the Repository.
readonly ILibGit2RepositoryFactory submoduleFactory
The ILibGit2RepositoryFactory used for updating submodules.
readonly IOptionsMonitor< GeneralConfiguration > generalConfigurationOptions
The IOptionsMonitor<TOptions> of GeneralConfiguration for the Repository.
readonly ILogger< Repository > logger
The ILogger for the Repository.
Static Private Attributes
const string UnknownReference = "<UNKNOWN>"
Used when a reference cannot be determined.
static PushOptions PushOptions
Generate a standard set of PushOptions.
Detailed Description
Definition at line 26 of file Repository.cs.
Constructor & Destructor Documentation
Repository()
Tgstation.Server.Host.Components.Repository.Repository.Repository (LibGit2Sharp::IRepository libGitRepo, ILibGit2Commands commands, IIOManager ioManager, IEventConsumer eventConsumer, ICredentialsProvider credentialsProvider, IPostWriteHandler postWriteHandler, IGitRemoteFeaturesFactory gitRemoteFeaturesFactory, ILibGit2RepositoryFactory submoduleFactory, IOptionsMonitor< GeneralConfiguration > generalConfigurationOptions, ILogger< Repository > logger, Action disposeAction)
Initializes a new instance of the Repository class.
Parameters
libGitRepo The value of libGitRepo.
commands The value of commands.
ioManager The value of ioManager.
eventConsumer The value of eventConsumer.
credentialsProvider The value of credentialsProvider.
postWriteHandler The value of postWriteHandler.
gitRemoteFeaturesFactory The IGitRemoteFeaturesFactory to provide the value of gitRemoteFeatures.
submoduleFactory The value of submoduleFactory.
generalConfigurationOptions The value of generalConfigurationOptions.
logger The value of logger.
disposeAction The IDisposable.Dispose action for the DisposeInvoker.
Definition at line 184 of file Repository.cs.
            : base(disposeAction)
        {
            this.libGitRepo = libGitRepo ?? throw new ArgumentNullException(nameof(libGitRepo));
            this.commands = commands ?? throw new ArgumentNullException(nameof(commands));
            this.ioManager = ioManager ?? throw new ArgumentNullException(nameof(ioManager));
            this.eventConsumer = eventConsumer ?? throw new ArgumentNullException(nameof(eventConsumer));
            this.credentialsProvider = credentialsProvider ?? throw new ArgumentNullException(nameof(credentialsProvider));
            this.postWriteHandler = postWriteHandler ?? throw new ArgumentNullException(nameof(postWriteHandler));
            ArgumentNullException.ThrowIfNull(gitRemoteFeaturesFactory);
            this.submoduleFactory = submoduleFactory ?? throw new ArgumentNullException(nameof(submoduleFactory));
            this.generalConfigurationOptions = generalConfigurationOptions ?? throw new ArgumentNullException(nameof(generalConfigurationOptions));
            this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
            gitRemoteFeatures = gitRemoteFeaturesFactory.CreateGitRemoteFeatures(this);
        }
References Tgstation.Server.Host.Components.Repository.Repository.commands, Tgstation.Server.Host.Components.Repository.IGitRemoteFeaturesFactory.CreateGitRemoteFeatures(), Tgstation.Server.Host.Components.Repository.Repository.credentialsProvider, Tgstation.Server.Host.Components.Repository.Repository.eventConsumer, Tgstation.Server.Host.Components.Repository.Repository.generalConfigurationOptions, Tgstation.Server.Host.Components.Repository.Repository.gitRemoteFeatures, Tgstation.Server.Host.Components.Repository.Repository.ioManager, Tgstation.Server.Host.Components.Repository.Repository.libGitRepo, Tgstation.Server.Host.Components.Repository.Repository.logger, Tgstation.Server.Host.Components.Repository.Repository.postWriteHandler, and Tgstation.Server.Host.Components.Repository.Repository.submoduleFactory.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.DeploymentProcess(), and Tgstation.Server.Host.Components.Instance.RepositoryAutoUpdateJob().
Member Function Documentation
AddTestMerge()
async ValueTask< TestMergeResult > Tgstation.Server.Host.Components.Repository.Repository.AddTestMerge (TestMergeParameters testMergeParameters, string committerName, string committerEmail, string? username, string? password, bool updateSubmodules, JobProgressReporter progressReporter, CancellationToken cancellationToken)
Attempt to merge the revision specified by a given set of testMergeParameters into HEAD.
Parameters
testMergeParameters The TestMergeParameters of the pull request.
committerName The name of the merge committer.
committerEmail The e-mail of the merge committer.
username The optional username used to fetch from the origin and submodule repositories.
password The optional password used to fetch from the origin and submodule repositories.
updateSubmodules If a submodule update should be attempted after the merge.
progressReporter The JobProgressReporter to report progress of the operation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the TestMergeResult.
Implements Tgstation.Server.Host.Components.Repository.IRepository.
Definition at line 214 of file Repository.cs.
        {
            ArgumentNullException.ThrowIfNull(testMergeParameters);
            ArgumentNullException.ThrowIfNull(committerName);
            ArgumentNullException.ThrowIfNull(committerEmail);
            ArgumentNullException.ThrowIfNull(progressReporter);
            logger.LogDebug(
                "Begin AddTestMerge: #{prNumber} at {targetSha} ({comment}) by <{committerName} ({committerEmail})>",
                testMergeParameters.Number,
                testMergeParameters.TargetCommitSha?[..7],
                testMergeParameters.Comment,
                committerName,
                committerEmail);
            if (RemoteGitProvider == Api.Models.RemoteGitProvider.Unknown)
                throw new InvalidOperationException("Cannot test merge with an Unknown RemoteGitProvider!");
            var commitMessage = String.Format(
                CultureInfo.InvariantCulture,
                "TGS Test Merge (PR {0}){1}{2}",
                testMergeParameters.Number,
                testMergeParameters.Comment != null
                    ? Environment.NewLine
                    : String.Empty,
                testMergeParameters.Comment ?? String.Empty);
            var testMergeBranchName = String.Format(CultureInfo.InvariantCulture, "tm-{0}", testMergeParameters.Number);
            var localBranchName = String.Format(CultureInfo.InvariantCulture, gitRemoteFeatures.TestMergeLocalBranchNameFormatter, testMergeParameters.Number, testMergeBranchName);
            var refSpec = String.Format(CultureInfo.InvariantCulture, gitRemoteFeatures.TestMergeRefSpecFormatter, testMergeParameters.Number, testMergeBranchName);
            var refSpecList = new List<string> { refSpec };
            var logMessage = String.Format(CultureInfo.InvariantCulture, "Test merge #{0}", testMergeParameters.Number);
            var originalCommit = libGitRepo.Head;
            MergeResult? result = null;
            var progressFactor = 1.0 / (updateSubmodules ? 3 : 2);
            var sig = new Signature(new Identity(committerName, committerEmail), DateTimeOffset.UtcNow);
            List<string>? conflictedPaths = null;
            var credentialsHandler = await GenerateCredentialsHandler(username, password, cancellationToken);
            await Task.Factory.StartNew(
                () =>
                {
                    try
                    {
                        try
{
                            logger.LogTrace("Fetching refspec {refSpec}...", refSpec);
                            var remote = libGitRepo.Network.Remotes.First();
                            using var fetchReporter = progressReporter.CreateSection($"Fetch {refSpec}", progressFactor);
                            commands.Fetch(
                                libGitRepo,
                                refSpecList,
                                remote,
                                new FetchOptions().Hydrate(
                                    logger,
                                    fetchReporter,
                                    credentialsHandler,
                                    cancellationToken),
                                logMessage);
                        }
                        catch (UserCancelledException ex)
{
                            logger.LogTrace(ex, "Suppressing fetch cancel exception");
                        }
                        catch (LibGit2SharpException ex)
{
                            credentialsProvider.CheckBadCredentialsException(ex);
                        }
                        cancellationToken.ThrowIfCancellationRequested();
                        libGitRepo.RemoveUntrackedFiles();
                        cancellationToken.ThrowIfCancellationRequested();
                        var objectName = testMergeParameters.TargetCommitSha ?? localBranchName;
                        var gitObject = libGitRepo.Lookup(objectName) ?? throw new JobException($"Could not find object to merge: {objectName}");
                        testMergeParameters.TargetCommitSha = gitObject.Sha;
                        cancellationToken.ThrowIfCancellationRequested();
                        logger.LogTrace("Merging {targetCommitSha} into {currentReference}...", testMergeParameters.TargetCommitSha[..7], Reference);
                        using var mergeReporter = progressReporter.CreateSection($"Merge {testMergeParameters.TargetCommitSha[..7]}", progressFactor);
                        result = libGitRepo.Merge(testMergeParameters.TargetCommitSha, sig, new MergeOptions
{
                            CommitOnSuccess = commitMessage == null,
                            FailOnConflict = false, // Needed to get conflicting files
                            FastForwardStrategy = FastForwardStrategy.NoFastForward,
                            SkipReuc = true,
                            OnCheckoutProgress = CheckoutProgressHandler(mergeReporter),
                        });
                    }
                    finally
                    {
                        libGitRepo.Branches.Remove(localBranchName);
                    }
                    cancellationToken.ThrowIfCancellationRequested();
                    if (result.Status == MergeStatus.Conflicts)
                    {
                        var repoStatus = libGitRepo.RetrieveStatus();
                        conflictedPaths = new List<string>();
                        foreach (var file in repoStatus)
                            if (file.State == FileStatus.Conflicted)
                                conflictedPaths.Add(file.FilePath);
                        var revertTo = originalCommit.CanonicalName ?? originalCommit.Tip.Sha;
                        logger.LogDebug("Merge conflict, aborting and reverting to {revertTarget}", revertTo);
                        progressReporter.ReportProgress(0);
                        using var revertReporter = progressReporter.CreateSection("Hard Reset to {revertTo}", 1.0);
                        RawCheckout(revertTo, false, revertReporter, cancellationToken);
                        cancellationToken.ThrowIfCancellationRequested();
                    }
                    libGitRepo.RemoveUntrackedFiles();
                },
                cancellationToken,
                DefaultIOManager.BlockingTaskCreationOptions,
                TaskScheduler.Current);
            if (result!.Status == MergeStatus.Conflicts)
            {
                var arguments = new List<string>
                {
                    originalCommit.Tip.Sha,
                    testMergeParameters.TargetCommitSha!,
                    originalCommit.FriendlyName ?? UnknownReference,
                    testMergeBranchName,
                };
                arguments.AddRange(conflictedPaths!);
                await eventConsumer.HandleEvent(
                    EventType.RepoMergeConflict,
                    arguments,
                    false,
                    false,
                    cancellationToken);
                return new TestMergeResult
                {
                    Status = result.Status,
                    ConflictingFiles = conflictedPaths,
                };
            }
            if (result.Status != MergeStatus.UpToDate)
            {
                logger.LogTrace("Committing merge: \"{commitMessage}\"...", commitMessage);
                await Task.Factory.StartNew(
                    () => libGitRepo.Commit(commitMessage, sig, sig, new CommitOptions
                    {
                        PrettifyMessage = true,
                    }),
                    cancellationToken,
                    DefaultIOManager.BlockingTaskCreationOptions,
                    TaskScheduler.Current);
                if (updateSubmodules)
                {
                    using var progressReporter2 = progressReporter.CreateSection("Update Submodules", progressFactor);
                    await UpdateSubmodules(
                        progressReporter2,
                        username,
                        password,
                        false,
                        cancellationToken);
                }
            }
            await eventConsumer.HandleEvent(
                EventType.RepoAddTestMerge,
                new List<string?>
                {
                    testMergeParameters.Number.ToString(CultureInfo.InvariantCulture),
                    testMergeParameters.TargetCommitSha!,
                    testMergeParameters.Comment,
                },
                false,
                false,
                cancellationToken);
            return new TestMergeResult
            {
                Status = result.Status,
            };
        }
References Tgstation.Server.Host.IO.DefaultIOManager.BlockingTaskCreationOptions, Tgstation.Server.Host.Components.Repository.ICredentialsProvider.CheckBadCredentialsException(), Tgstation.Server.Host.Components.Repository.Repository.commands, Tgstation.Server.Api.Models.TestMergeParameters.Comment, Tgstation.Server.Host.Jobs.JobProgressReporter.CreateSection(), Tgstation.Server.Host.Components.Repository.Repository.credentialsProvider, Tgstation.Server.Host.Components.Repository.Repository.eventConsumer, Tgstation.Server.Host.Components.Repository.ILibGit2Commands.Fetch(), Tgstation.Server.Host.Components.Repository.Repository.GenerateCredentialsHandler(), Tgstation.Server.Host.Components.Repository.Repository.gitRemoteFeatures, Tgstation.Server.Host.Components.Events.IEventConsumer.HandleEvent(), Tgstation.Server.Host.Components.Repository.IRepository.Head, Tgstation.Server.Host.Components.Repository.Repository.libGitRepo, Tgstation.Server.Host.Components.Repository.Repository.logger, Tgstation.Server.Api.Models.TestMergeParameters.Number, Tgstation.Server.Host.Components.Repository.Repository.RawCheckout(), Tgstation.Server.Host.Components.Repository.Repository.Reference, Tgstation.Server.Host.Jobs.JobProgressReporter.ReportProgress(), Tgstation.Server.Host.Components.Repository.TestMergeResult.Status, Tgstation.Server.Api.Models.TestMergeParameters.TargetCommitSha, Tgstation.Server.Host.Components.Repository.IGitRemoteFeatures.TestMergeLocalBranchNameFormatter, Tgstation.Server.Host.Components.Repository.IGitRemoteFeatures.TestMergeRefSpecFormatter, Tgstation.Server.Host.Components.Repository.Repository.UnknownReference, and Tgstation.Server.Host.Components.Repository.Repository.UpdateSubmodules().
CheckoutObject()
async ValueTask Tgstation.Server.Host.Components.Repository.Repository.CheckoutObject (string committish, string? username, string? password, bool updateSubmodules, bool moveCurrentReference, JobProgressReporter progressReporter, CancellationToken cancellationToken)
Checks out a given committish .
Parameters
committish The sha or reference to checkout.
username The optional username used for fetching from submodule repositories.
password The optional password used for fetching from submodule repositories.
updateSubmodules If a submodule update should be attempted after the merge.
moveCurrentReference If a hard reset to the target committish should be performed instead of a checkout.
progressReporter The JobProgressReporter to report progress of the operation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Repository.IRepository.
Definition at line 420 of file Repository.cs.
        {
            ArgumentNullException.ThrowIfNull(committish);
            logger.LogDebug("Checkout object: {committish}...", committish);
            await eventConsumer.HandleEvent(EventType.RepoCheckout, new List<string> { committish, moveCurrentReference.ToString() }, false, false, cancellationToken);
            await Task.Factory.StartNew(
                () =>
                {
                    libGitRepo.RemoveUntrackedFiles();
                    using var progressReporter3 = progressReporter.CreateSection(null, updateSubmodules ? 2.0 / 3 : 1.0);
                    RawCheckout(
                        committish,
                        moveCurrentReference,
                        progressReporter3,
                        cancellationToken);
                },
                cancellationToken,
                DefaultIOManager.BlockingTaskCreationOptions,
                TaskScheduler.Current);
            if (updateSubmodules)
            {
                using var progressReporter2 = progressReporter.CreateSection(null, 1.0 / 3);
                await UpdateSubmodules(
                    progressReporter2,
                    username,
                    password,
                    false,
                    cancellationToken);
            }
        }
References Tgstation.Server.Host.IO.DefaultIOManager.BlockingTaskCreationOptions, Tgstation.Server.Host.Jobs.JobProgressReporter.CreateSection(), Tgstation.Server.Host.Components.Repository.Repository.eventConsumer, Tgstation.Server.Host.Components.Events.IEventConsumer.HandleEvent(), Tgstation.Server.Host.Components.Repository.Repository.libGitRepo, Tgstation.Server.Host.Components.Repository.Repository.logger, Tgstation.Server.Host.Components.Repository.Repository.RawCheckout(), and Tgstation.Server.Host.Components.Repository.Repository.UpdateSubmodules().
CheckoutProgressHandler()
CheckoutProgressHandler Tgstation.Server.Host.Components.Repository.Repository.CheckoutProgressHandler (JobProgressReporter progressReporter) private
Converts a given progressReporter to a LibGit2Sharp.Handlers.CheckoutProgressHandler.
Parameters
progressReporter The JobProgressReporter of the operation.
Returns
A LibGit2Sharp.Handlers.CheckoutProgressHandler based on progressReporter .
References Tgstation.Server.Host.Jobs.JobProgressReporter.ReportProgress().
CommittishIsParent()
Task< bool > Tgstation.Server.Host.Components.Repository.Repository.CommittishIsParent (string committish, CancellationToken cancellationToken)
Check if a given committish is a parent of the current Head.
Parameters
committish The committish of the SHA to check.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in true if committish is a parent of Head, false otherwise.
This function is NOT reentrant.
Implements Tgstation.Server.Host.Components.Repository.IRepository.
CopyTo()
async ValueTask Tgstation.Server.Host.Components.Repository.Repository.CopyTo (string path, CancellationToken cancellationToken)
Copies the current working directory to a given path .
Parameters
path The path to copy repository contents to.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Repository.IRepository.
Definition at line 587 of file Repository.cs.
        {
            ArgumentNullException.ThrowIfNull(path);
            logger.LogTrace("Copying to {path}...", path);
            await ioManager.CopyDirectory(
                new List<string> { ".git" },
                (src, dest) =>
                {
                    if (postWriteHandler.NeedsPostWrite(src))
                        postWriteHandler.HandleWrite(dest);
                    return ValueTask.CompletedTask;
                },
                ioManager.ResolvePath(),
                path,
                generalConfigurationOptions.CurrentValue.GetCopyDirectoryTaskThrottle(),
                cancellationToken);
        }
References Tgstation.Server.Host.IO.IIOManager.CopyDirectory(), Tgstation.Server.Host.Components.Repository.Repository.generalConfigurationOptions, Tgstation.Server.Host.IO.IPostWriteHandler.HandleWrite(), Tgstation.Server.Host.Components.Repository.Repository.ioManager, Tgstation.Server.Host.Components.Repository.Repository.logger, Tgstation.Server.Host.IO.IPostWriteHandler.NeedsPostWrite(), Tgstation.Server.Host.Components.Repository.Repository.postWriteHandler, and Tgstation.Server.Host.IO.IIOManager.ResolvePath().
DisposeImpl()
override void Tgstation.Server.Host.Components.Repository.Repository.DisposeImpl () protected virtual
Implementation of Dispose run after reentrancy check.
Reimplemented from Tgstation.Server.Host.Utils.DisposeInvoker.
Definition at line 959 of file Repository.cs.
        {
            logger.LogTrace("Disposing...");
            libGitRepo.Dispose();
            base.DisposeImpl();
        }
FetchOrigin()
async ValueTask Tgstation.Server.Host.Components.Repository.Repository.FetchOrigin (JobProgressReporter progressReporter, string? username, string? password, bool deploymentPipeline, CancellationToken cancellationToken)
Fetch commits from the origin repository.
Parameters
progressReporter The JobProgressReporter to report progress of the operation.
username The optional username to fetch from the origin repository.
password The optional password to fetch from the origin repository.
deploymentPipeline If any events created should be marked as part of the deployment pipeline.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Repository.IRepository.
Definition at line 461 of file Repository.cs.
        {
            logger.LogDebug("Fetch origin...");
            var parameters = new List<string>();
            var credentialsHandlerTask = GenerateCredentialsHandler(username, password, cancellationToken);
            if (username != null)
            {
                parameters.Add(username);
                if (password != null)
                {
                    var transformedPassword = await gitRemoteFeatures.TransformRepositoryPassword(password, cancellationToken);
                    if (transformedPassword != null)
                        parameters.Add(transformedPassword);
                }
            }
            await eventConsumer.HandleEvent(EventType.RepoFetch, parameters, true, deploymentPipeline, cancellationToken);
            var credentialsHandler = await credentialsHandlerTask;
            await Task.Factory.StartNew(
                () =>
                {
                    var remote = libGitRepo.Network.Remotes.First();
                    try
                    {
                        using var subReporter = progressReporter.CreateSection("Fetch Origin", 1.0);
                        var fetchOptions = new FetchOptions
{
                            Prune = true,
                            TagFetchMode = TagFetchMode.All,
                        }.Hydrate(
                            logger,
                            subReporter,
                            credentialsHandler,
                            cancellationToken);
                        commands.Fetch(
                            libGitRepo,
                            remote
                                .FetchRefSpecs
                                .Select(x => x.Specification),
                            remote,
                            fetchOptions,
                            "Fetch origin commits");
                    }
                    catch (UserCancelledException)
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                    }
                    catch (LibGit2SharpException ex)
                    {
                        credentialsProvider.CheckBadCredentialsException(ex);
                    }
                },
                cancellationToken,
                DefaultIOManager.BlockingTaskCreationOptions,
                TaskScheduler.Current);
        }
References Tgstation.Server.Host.IO.DefaultIOManager.BlockingTaskCreationOptions, Tgstation.Server.Host.Components.Repository.ICredentialsProvider.CheckBadCredentialsException(), Tgstation.Server.Host.Components.Repository.Repository.commands, Tgstation.Server.Host.Jobs.JobProgressReporter.CreateSection(), Tgstation.Server.Host.Components.Repository.Repository.credentialsProvider, Tgstation.Server.Host.Components.Repository.Repository.eventConsumer, Tgstation.Server.Host.Components.Repository.ILibGit2Commands.Fetch(), Tgstation.Server.Host.Components.Repository.Repository.GenerateCredentialsHandler(), Tgstation.Server.Host.Components.Repository.Repository.gitRemoteFeatures, Tgstation.Server.Host.Components.Events.IEventConsumer.HandleEvent(), Tgstation.Server.Host.Components.Repository.Repository.libGitRepo, Tgstation.Server.Host.Components.Repository.Repository.logger, and Tgstation.Server.Host.Components.Repository.IGitRemoteFeatures.TransformRepositoryPassword().
GenerateCredentialsHandler()
ValueTask< CredentialsHandler > Tgstation.Server.Host.Components.Repository.Repository.GenerateCredentialsHandler (string? username, string? password, CancellationToken cancellationToken) private
Generate a CredentialsHandler from a given username and password .
Parameters
username The optional username to use in the CredentialsHandler.
password The optional password to use in the CredentialsHandler.
cancellationToken The CancellationToken for the operation.
Returns
A new CredentialsHandler.
Referenced by Tgstation.Server.Host.Components.Repository.Repository.AddTestMerge(), and Tgstation.Server.Host.Components.Repository.Repository.FetchOrigin().
GeneratePushOptions() [1/2]
static PushOptions IEnumerable< JobProgressReporter > SubProgressReporters Tgstation.Server.Host.Components.Repository.Repository.GeneratePushOptions (JobProgressReporter progressReporter, CredentialsHandler credentialsHandler, CancellationToken cancellationToken) static private
Definition at line 136 of file Repository.cs.
        {
            var packFileCountingReporter = progressReporter.CreateSection(null, 0.25);
            var packFileDeltafyingReporter = progressReporter.CreateSection(null, 0.25);
            var transferProgressReporter = progressReporter.CreateSection(null, 0.5);
            return (
                PushOptions: new PushOptions
                {
                    OnPackBuilderProgress = (stage, current, total) =>
                    {
                        if (total < current)
                            total = current;
                        var percentage = ((double)current) / total;
                        (stage == PackBuilderStage.Counting ? packFileCountingReporter : packFileDeltafyingReporter).ReportProgress(percentage);
                        return !cancellationToken.IsCancellationRequested;
                    },
                    OnNegotiationCompletedBeforePush = (a) => !cancellationToken.IsCancellationRequested,
                    OnPushTransferProgress = (a, sentBytes, totalBytes) =>
                    {
                        packFileCountingReporter.ReportProgress((double)sentBytes / totalBytes);
                        return !cancellationToken.IsCancellationRequested;
                    },
                    CredentialsProvider = credentialsHandler,
                },
                SubProgressReporters: new List<JobProgressReporter>
                {
                    packFileCountingReporter,
                    packFileDeltafyingReporter,
                    transferProgressReporter,
                });
        }
References Tgstation.Server.Host.Jobs.JobProgressReporter.CreateSection(), and Tgstation.Server.Host.Components.Repository.Repository.PushOptions.
GeneratePushOptions() [2/2]
async ValueTask<(PushOptions PushOptions, IEnumerable< JobProgressReporter > SubProgressReporters)> Tgstation.Server.Host.Components.Repository.Repository.GeneratePushOptions (JobProgressReporter progressReporter, string username, string password, CancellationToken cancellationToken) private
Generate a standard set of PushOptions.
Parameters
progressReporter JobProgressReporter of the operation.
username The username for the credentialsProvider.
password The password for the credentialsProvider.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a new set of PushOptions and the associated JobProgressReporters based off progressReporter .
GetOriginSha()
Task< string > Tgstation.Server.Host.Components.Repository.Repository.GetOriginSha (CancellationToken cancellationToken)
Get the tracked reference's current SHA.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the tracked origin reference's SHA.
Implements Tgstation.Server.Host.Components.Repository.IRepository.
References Tgstation.Server.Host.Components.Repository.IRepository.Head, Tgstation.Server.Host.Components.Repository.Repository.libGitRepo, and Tgstation.Server.Host.Components.Repository.Repository.Tracking.
GetRepositoryPath()
string Tgstation.Server.Host.Components.Repository.Repository.GetRepositoryPath () private
Gets the path of libGitRepo.
Returns
The path of the target IRepository.
GetTestMerge()
ValueTask< Models.TestMerge > Tgstation.Server.Host.Components.Repository.Repository.GetTestMerge (TestMergeParameters parameters, RepositorySettings repositorySettings, CancellationToken cancellationToken)
Retrieve the Models.TestMerge representation of given test merge parameters .
Parameters
parameters The TestMergeParameters.
repositorySettings The RepositorySettings.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the Models.TestMerge of the parameters .
TestMergeApiBase.MergedAt and Models.TestMerge.MergedBy will be unset.
Implements Tgstation.Server.Host.Components.Repository.IGitRemoteAdditionalInformation.
IsSha()
Task< bool > Tgstation.Server.Host.Components.Repository.Repository.IsSha (string committish, CancellationToken cancellationToken)
Checks if a given committish is a sha.
Parameters
committish The git object to check.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in true if committish is a sha, false otherwise.
Implements Tgstation.Server.Host.Components.Repository.IRepository.
MergeOrigin()
async ValueTask< bool?> Tgstation.Server.Host.Components.Repository.Repository.MergeOrigin (JobProgressReporter progressReporter, string committerName, string committerEmail, bool deploymentPipeline, CancellationToken cancellationToken)
Requires the current HEAD to be a tracked reference. Merges the reference to what it tracks on the origin repository.
Parameters
progressReporter The JobProgressReporter to report progress of the operation.
committerName The name of the merge committer.
committerEmail The e-mail of the merge committer.
deploymentPipeline If any events created should be marked as part of the deployment pipeline.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a Nullable<T> bool representing the merge result that is true after a fast forward, false on a merge or up to date, null on a conflict.
Implements Tgstation.Server.Host.Components.Repository.IRepository.
Definition at line 622 of file Repository.cs.
        {
            ArgumentNullException.ThrowIfNull(progressReporter);
            MergeResult? result = null;
            Branch? trackedBranch = null;
            var oldHead = libGitRepo.Head;
            var oldTip = oldHead.Tip;
            await Task.Factory.StartNew(
                () =>
                {
                    if (!Tracking)
                        throw new JobException(ErrorCode.RepoReferenceRequired);
                    libGitRepo.RemoveUntrackedFiles();
                    cancellationToken.ThrowIfCancellationRequested();
                    trackedBranch = libGitRepo.Head.TrackedBranch;
                    logger.LogDebug(
                        "Merge origin/{trackedBranch}: <{committerName} ({committerEmail})>",
                        trackedBranch.FriendlyName,
                        committerName,
                        committerEmail);
                    result = libGitRepo.Merge(trackedBranch, new Signature(committerName, committerEmail, DateTimeOffset.UtcNow), new MergeOptions
                    {
                        CommitOnSuccess = true,
                        FailOnConflict = true,
                        FastForwardStrategy = FastForwardStrategy.Default,
                        SkipReuc = true,
                        OnCheckoutProgress = CheckoutProgressHandler(progressReporter.CreateSection("Merge Origin", 1.0)),
                    });
                    cancellationToken.ThrowIfCancellationRequested();
                    if (result.Status == MergeStatus.Conflicts)
                    {
                        logger.LogDebug("Merge conflict, aborting and reverting to {oldHeadFriendlyName}", oldHead.FriendlyName);
                        progressReporter.ReportProgress(0);
                        libGitRepo.Reset(ResetMode.Hard, oldTip, new CheckoutOptions
{
                            OnCheckoutProgress = CheckoutProgressHandler(progressReporter.CreateSection($"Hard Reset to {oldHead.FriendlyName}", 1.0)),
                        });
                        cancellationToken.ThrowIfCancellationRequested();
                    }
                    libGitRepo.RemoveUntrackedFiles();
                },
                cancellationToken,
                DefaultIOManager.BlockingTaskCreationOptions,
                TaskScheduler.Current);
            if (result!.Status == MergeStatus.Conflicts)
            {
                await eventConsumer.HandleEvent(
                    EventType.RepoMergeConflict,
                    new List<string>
                    {
                        oldTip.Sha,
                        trackedBranch!.Tip.Sha,
                        oldHead.FriendlyName ?? UnknownReference,
                        trackedBranch.FriendlyName,
                    },
                    false,
                    deploymentPipeline,
                    cancellationToken);
                return null;
            }
            return result.Status == MergeStatus.FastForward;
        }
References Tgstation.Server.Host.IO.DefaultIOManager.BlockingTaskCreationOptions, Tgstation.Server.Host.Components.Repository.Repository.eventConsumer, Tgstation.Server.Host.Components.Events.IEventConsumer.HandleEvent(), Tgstation.Server.Host.Components.Repository.IRepository.Head, Tgstation.Server.Host.Components.Repository.Repository.libGitRepo, Tgstation.Server.Host.Components.Repository.Repository.logger, Tgstation.Server.Host.Jobs.JobProgressReporter.ReportProgress(), Tgstation.Server.Host.Components.Repository.Repository.Tracking, and Tgstation.Server.Host.Components.Repository.Repository.UnknownReference.
PushHeadToTemporaryBranch()
Task Tgstation.Server.Host.Components.Repository.Repository.PushHeadToTemporaryBranch (CredentialsHandler credentialsHandler, JobProgressReporter progressReporter, CancellationToken cancellationToken) private
Force push the current repository HEAD to RemoteTemporaryBranchName;.
Parameters
credentialsHandler The CredentialsHandler for the operation.
progressReporter JobProgressReporter of the operation.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
References Tgstation.Server.Host.Jobs.JobProgressReporter.CreateSection().
RawCheckout()
void Tgstation.Server.Host.Components.Repository.Repository.RawCheckout (string committish, bool moveCurrentReference, JobProgressReporter progressReporter, CancellationToken cancellationToken) private
Runs a blocking force checkout to committish .
Parameters
committish The committish to checkout.
moveCurrentReference If a hard reset should actually be performed.
progressReporter The JobProgressReporter for the operation.
cancellationToken The CancellationToken for the operation.
Definition at line 973 of file Repository.cs.
        {
            logger.LogTrace("Checkout: {committish}", committish);
            var checkoutOptions = new CheckoutOptions
            {
                CheckoutModifiers = CheckoutModifiers.Force,
            };
            var stage = $"Checkout {committish}";
            using var newProgressReporter = progressReporter.CreateSection(stage, 1.0);
            newProgressReporter.ReportProgress(0);
            checkoutOptions.OnCheckoutProgress = CheckoutProgressHandler(newProgressReporter);
            cancellationToken.ThrowIfCancellationRequested();
            if (moveCurrentReference)
            {
                if (Reference == NoReference)
                    throw new InvalidOperationException("Cannot move current reference when not on reference!");
                var gitObject = libGitRepo.Lookup(committish);
                if (gitObject == null)
                    throw new JobException($"Could not find committish: {committish}");
                var commit = gitObject.Peel<Commit>();
                cancellationToken.ThrowIfCancellationRequested();
                libGitRepo.Reset(ResetMode.Hard, commit, checkoutOptions);
            }
            else
            {
                void RunCheckout() => commands.Checkout(
                    libGitRepo,
                    checkoutOptions,
                    committish);
                try
                {
                    RunCheckout();
                }
                catch (NotFoundException)
                {
                    // Maybe (likely) a remote?
                    var remoteName = $"origin/{committish}";
                    var remoteBranch = libGitRepo.Branches.FirstOrDefault(
                        branch => branch.FriendlyName.Equals(remoteName, StringComparison.Ordinal));
                    cancellationToken.ThrowIfCancellationRequested();
                    if (remoteBranch == default)
                        throw;
                    logger.LogDebug("Creating local branch for {remoteBranchFriendlyName}...", remoteBranch.FriendlyName);
                    var branch = libGitRepo.CreateBranch(committish, remoteBranch.Tip);
                    libGitRepo.Branches.Update(branch, branchUpdate => branchUpdate.TrackedBranch = remoteBranch.CanonicalName);
                    cancellationToken.ThrowIfCancellationRequested();
                    RunCheckout();
                }
            }
            cancellationToken.ThrowIfCancellationRequested();
            libGitRepo.RemoveUntrackedFiles();
        }
References Tgstation.Server.Host.Jobs.JobProgressReporter.CreateSection(), and Tgstation.Server.Host.Jobs.JobProgressReporter.ReportProgress().
Referenced by Tgstation.Server.Host.Components.Repository.Repository.AddTestMerge(), and Tgstation.Server.Host.Components.Repository.Repository.CheckoutObject().
ResetToOrigin()
async ValueTask Tgstation.Server.Host.Components.Repository.Repository.ResetToOrigin (JobProgressReporter progressReporter, string? username, string? password, bool updateSubmodules, bool deploymentPipeline, CancellationToken cancellationToken)
Requires the current HEAD to be a tracked reference. Hard resets the reference to what it tracks on the origin repository.
Parameters
progressReporter The JobProgressReporter to report progress of the operation.
username The optional username used for fetching from submodule repositories.
password The optional password used for fetching from submodule repositories.
updateSubmodules If a submodule update should be attempted after the merge.
deploymentPipeline If any events created should be marked as part of the deployment pipeline.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the SHA of the new HEAD.
Implements Tgstation.Server.Host.Components.Repository.IRepository.
Definition at line 526 of file Repository.cs.
        {
            ArgumentNullException.ThrowIfNull(progressReporter);
            if (!Tracking)
                throw new JobException(ErrorCode.RepoReferenceRequired);
            logger.LogTrace("Reset to origin...");
            var trackedBranch = libGitRepo.Head.TrackedBranch;
            await eventConsumer.HandleEvent(EventType.RepoResetOrigin, new List<string> { trackedBranch.FriendlyName, trackedBranch.Tip.Sha }, false, deploymentPipeline, cancellationToken);
            using (var progressReporter2 = progressReporter.CreateSection(null, updateSubmodules ? 2.0 / 3 : 1.0))
                await ResetToSha(
                    trackedBranch.Tip.Sha,
                    progressReporter2,
                    cancellationToken);
            if (updateSubmodules)
            {
                using var progressReporter3 = progressReporter.CreateSection(null, 1.0 / 3);
                await UpdateSubmodules(
                    progressReporter3,
                    username,
                    password,
                    deploymentPipeline,
                    cancellationToken);
            }
        }
References Tgstation.Server.Host.Jobs.JobProgressReporter.CreateSection(), Tgstation.Server.Host.Components.Repository.Repository.eventConsumer, Tgstation.Server.Host.Components.Events.IEventConsumer.HandleEvent(), Tgstation.Server.Host.Components.Repository.IRepository.Head, Tgstation.Server.Host.Components.Repository.Repository.libGitRepo, Tgstation.Server.Host.Components.Repository.Repository.logger, Tgstation.Server.Host.Components.Repository.Repository.ResetToSha(), Tgstation.Server.Host.Components.Repository.Repository.Tracking, and Tgstation.Server.Host.Components.Repository.Repository.UpdateSubmodules().
ResetToSha()
Task Tgstation.Server.Host.Components.Repository.Repository.ResetToSha (string sha, JobProgressReporter progressReporter, CancellationToken cancellationToken)
Requires the current HEAD to be a reference. Hard resets the reference to the given sha.
Parameters
sha The sha hash to reset to.
progressReporter The JobProgressReporter to report progress of the operation.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the SHA of the new HEAD.
Implements Tgstation.Server.Host.Components.Repository.IRepository.
References Tgstation.Server.Host.Components.Repository.Repository.libGitRepo, and Tgstation.Server.Host.Components.Repository.Repository.logger.
Referenced by Tgstation.Server.Host.Components.Repository.Repository.ResetToOrigin().
Synchronize()
async ValueTask< bool > Tgstation.Server.Host.Components.Repository.Repository.Synchronize (JobProgressReporter progressReporter, string? username, string? password, string committerName, string committerEmail, bool synchronizeTrackedBranch, bool deploymentPipeline, CancellationToken cancellationToken)
Runs the synchronize event script and attempts to push any changes made to the IRepository if on a tracked branch.
Parameters
progressReporter The JobProgressReporter to report progress of the operation.
username The username to fetch from the origin repository.
password The password to fetch from the origin repository.
committerName The name of the potential committer.
committerEmail The e-mail of the potential committer.
synchronizeTrackedBranch If the synchronizations should be made to the tracked reference as opposed to a temporary branch.
deploymentPipeline If any events created should be marked as part of the deployment pipeline.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in true if commits were pushed to the tracked origin reference, false otherwise.
Implements Tgstation.Server.Host.Components.Repository.IRepository.
Definition at line 702 of file Repository.cs.
        {
            ArgumentNullException.ThrowIfNull(committerName);
            ArgumentNullException.ThrowIfNull(committerEmail);
            ArgumentNullException.ThrowIfNull(progressReporter);
            if (username == null && password == null)
            {
                logger.LogTrace("Not synchronizing due to lack of credentials!");
                return false;
            }
            logger.LogTrace("Begin Synchronize...");
            ArgumentNullException.ThrowIfNull(username);
            ArgumentNullException.ThrowIfNull(password);
            var startHead = Head;
            logger.LogTrace("Configuring <{committerName} ({committerEmail})> as author/committer", committerName, committerEmail);
            await Task.Factory.StartNew(
                () =>
                {
                    libGitRepo.Config.Set("user.name", committerName);
                    cancellationToken.ThrowIfCancellationRequested();
                    libGitRepo.Config.Set("user.email", committerEmail);
                },
                cancellationToken,
                DefaultIOManager.BlockingTaskCreationOptions,
                TaskScheduler.Current);
            cancellationToken.ThrowIfCancellationRequested();
            try
            {
                await eventConsumer.HandleEvent(
                    EventType.RepoPreSynchronize,
                    new List<string>
                    {
                        ioManager.ResolvePath(),
                    },
                    false,
                    deploymentPipeline,
                    cancellationToken);
            }
            finally
            {
                logger.LogTrace("Resetting and cleaning untracked files...");
                await Task.Factory.StartNew(
                    () =>
                    {
                        using var resetProgress = progressReporter.CreateSection("Hard reset and remove untracked files", 0.1);
                        libGitRepo.Reset(ResetMode.Hard, libGitRepo.Head.Tip, new CheckoutOptions
{
                            OnCheckoutProgress = CheckoutProgressHandler(resetProgress),
                        });
                        cancellationToken.ThrowIfCancellationRequested();
                        libGitRepo.RemoveUntrackedFiles();
                    },
                    cancellationToken,
                    DefaultIOManager.BlockingTaskCreationOptions,
                    TaskScheduler.Current);
            }
            var remainingProgressFactor = 0.9;
            if (!synchronizeTrackedBranch)
            {
                using var progressReporter2 = progressReporter.CreateSection("Push to temporary branch", remainingProgressFactor);
                var credentialsHandler = await GenerateCredentialsHandler(username, password, cancellationToken);
                await PushHeadToTemporaryBranch(
                    credentialsHandler,
                    progressReporter2,
                    cancellationToken);
                return false;
            }
            var sameHead = Head == startHead;
            if (sameHead || !Tracking)
            {
                logger.LogTrace("Aborted synchronize due to {abortReason}!", sameHead ? "lack of changes" : "not being on tracked reference");
                return false;
            }
            logger.LogInformation("Synchronizing with origin...");
            using var pushReporter = progressReporter.CreateSection("Push to origin", remainingProgressFactor);
            var (pushOptions, progressReporters) = await GeneratePushOptions(
                pushReporter,
                username,
                password,
                cancellationToken);
            return await Task.Factory.StartNew(
                () =>
                {
                    var remote = libGitRepo.Network.Remotes.First();
                    try
                    {
                        try
{
                            libGitRepo.Network.Push(
                                libGitRepo.Head,
                                pushOptions);
                        }
                        finally
{
                            foreach (var progressReporter in progressReporters)
                                progressReporter.Dispose();
                        }
                        return true;
                    }
                    catch (NonFastForwardException)
                    {
                        logger.LogInformation("Synchronize aborted, non-fast forward!");
                        return false;
                    }
                    catch (UserCancelledException e)
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        throw new InvalidOperationException("Caught UserCancelledException without cancellationToken triggering", e);
                    }
                    catch (LibGit2SharpException e)
                    {
                        logger.LogWarning(e, "Unable to make synchronization push!");
                        return false;
                    }
                },
                cancellationToken,
                DefaultIOManager.BlockingTaskCreationOptions,
                TaskScheduler.Current);
        }
References Tgstation.Server.Host.IO.DefaultIOManager.BlockingTaskCreationOptions, and Tgstation.Server.Host.Jobs.JobProgressReporter.CreateSection().
TimestampCommit()
Task< DateTimeOffset > Tgstation.Server.Host.Components.Repository.Repository.TimestampCommit (string sha, CancellationToken cancellationToken)
Gets the DateTimeOffset a given sha was created on.
Parameters
sha The SHA to timestamp.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the DateTimeOffset that sha was created on.
Implements Tgstation.Server.Host.Components.Repository.IRepository.
UpdateSubmodules()
ValueTask Tgstation.Server.Host.Components.Repository.Repository.UpdateSubmodules (JobProgressReporter progressReporter, string? username, string? password, bool deploymentPipeline, CancellationToken cancellationToken) private
Recusively update all Submodules in the libGitRepo.
Parameters
progressReporter Optional JobProgressReporter of the operation.
username The optional username for the credentialsProvider.
password The optional password for the credentialsProvider.
deploymentPipeline If any events created should be marked as part of the deployment pipeline.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Definition at line 1145 of file Repository.cs.
        {
            logger.LogTrace("Updating submodules {withOrWithout} credentials...", username == null ? "without" : "with");
            async ValueTask RecursiveUpdateSubmodules(LibGit2Sharp.IRepository parentRepository, JobProgressReporter currentProgressReporter, string parentGitDirectory)
            {
                var submoduleCount = libGitRepo.Submodules.Count();
                if (submoduleCount == 0)
                {
                    logger.LogTrace("No submodules, skipping update");
                    return;
                }
                var factor = 1.0 / submoduleCount / 3;
                foreach (var submodule in parentRepository.Submodules)
                {
                    logger.LogTrace("Entering submodule {name} ({path}) for recursive updates...", submodule.Name, submodule.Path);
                    var submoduleUpdateOptions = new SubmoduleUpdateOptions
                    {
                        Init = true,
                        OnCheckoutNotify = (_, _) => !cancellationToken.IsCancellationRequested,
                    };
                    using var fetchReporter = currentProgressReporter.CreateSection($"Fetch submodule {submodule.Name}", factor);
                    var credentialsHandler = await GenerateCredentialsHandler(username, password, cancellationToken);
                    submoduleUpdateOptions.FetchOptions.Hydrate(
                        logger,
                        fetchReporter,
                        credentialsHandler,
                        cancellationToken);
                    using var checkoutReporter = currentProgressReporter.CreateSection($"Checkout submodule {submodule.Name}", factor);
                    submoduleUpdateOptions.OnCheckoutProgress = CheckoutProgressHandler(checkoutReporter);
                    logger.LogDebug("Updating submodule {submoduleName}...", submodule.Name);
                    Task RawSubModuleUpdate() => Task.Factory.StartNew(
                        () => parentRepository.Submodules.Update(submodule.Name, submoduleUpdateOptions),
                        cancellationToken,
                        DefaultIOManager.BlockingTaskCreationOptions,
                        TaskScheduler.Current);
                    try
                    {
                        await RawSubModuleUpdate();
                    }
                    catch (LibGit2SharpException ex) when (parentRepository == libGitRepo)
                    {
                        // workaround for https://github.com/libgit2/libgit2/issues/3820
                        // kill off the modules/ folder in .git and try again
                        currentProgressReporter.ReportProgress(0);
                        credentialsProvider.CheckBadCredentialsException(ex);
                        logger.LogWarning(ex, "Initial update of submodule {submoduleName} failed. Deleting submodule directories and re-attempting...", submodule.Name);
                        await Task.WhenAll(
                            ioManager.DeleteDirectory($".git/modules/{submodule.Path}", cancellationToken),
                            ioManager.DeleteDirectory(submodule.Path, cancellationToken));
                        logger.LogTrace("Second update attempt for submodule {submoduleName}...", submodule.Name);
                        try
{
                            await RawSubModuleUpdate();
                        }
                        catch (UserCancelledException)
{
                            cancellationToken.ThrowIfCancellationRequested();
                        }
                        catch (LibGit2SharpException ex2)
{
                            credentialsProvider.CheckBadCredentialsException(ex2);
                            logger.LogTrace(ex2, "Retried update of submodule {submoduleName} failed!", submodule.Name);
                            throw new AggregateException(ex, ex2);
                        }
                    }
                    await eventConsumer.HandleEvent(
                        EventType.RepoSubmoduleUpdate,
                        new List<string> { submodule.Name },
                        false,
                        deploymentPipeline,
                        cancellationToken);
                    var submodulePath = ioManager.ResolvePath(
                        ioManager.ConcatPath(
                            parentGitDirectory,
                            submodule.Path));
                    using var submoduleRepo = await submoduleFactory.CreateFromPath(
                        submodulePath,
                        cancellationToken);
                    using var submoduleReporter = currentProgressReporter.CreateSection($"Entering submodule \"{submodule.Name}\"...", factor);
                    await RecursiveUpdateSubmodules(
                        submoduleRepo,
                        submoduleReporter,
                        submodulePath);
                }
            }
            return RecursiveUpdateSubmodules(libGitRepo, progressReporter, GetRepositoryPath());
        }
References Tgstation.Server.Host.IO.DefaultIOManager.BlockingTaskCreationOptions, Tgstation.Server.Host.Jobs.JobProgressReporter.CreateSection(), and Tgstation.Server.Host.Jobs.JobProgressReporter.ReportProgress().
Referenced by Tgstation.Server.Host.Components.Repository.Repository.AddTestMerge(), Tgstation.Server.Host.Components.Repository.Repository.CheckoutObject(), and Tgstation.Server.Host.Components.Repository.Repository.ResetToOrigin().
Member Data Documentation
commands
readonly ILibGit2Commands Tgstation.Server.Host.Components.Repository.Repository.commands private
The ILibGit2Commands for the Repository.
Definition at line 87 of file Repository.cs.
Referenced by Tgstation.Server.Host.Components.Repository.Repository.AddTestMerge(), Tgstation.Server.Host.Components.Repository.Repository.FetchOrigin(), and Tgstation.Server.Host.Components.Repository.Repository.Repository().
credentialsProvider
readonly ICredentialsProvider Tgstation.Server.Host.Components.Repository.Repository.credentialsProvider private
The ICredentialsProvider for the Repository.
Definition at line 102 of file Repository.cs.
Referenced by Tgstation.Server.Host.Components.Repository.Repository.AddTestMerge(), Tgstation.Server.Host.Components.Repository.Repository.FetchOrigin(), and Tgstation.Server.Host.Components.Repository.Repository.Repository().
DefaultCommitterEmail
const string Tgstation.Server.Host.Components.Repository.Repository.DefaultCommitterEmail = "tgstation-server@users.noreply.github.com" static
The default password for committers.
Definition at line 36 of file Repository.cs.
DefaultCommitterName
const string Tgstation.Server.Host.Components.Repository.Repository.DefaultCommitterName = "tgstation-server" static
The default username for committers.
Definition at line 31 of file Repository.cs.
eventConsumer
readonly IEventConsumer Tgstation.Server.Host.Components.Repository.Repository.eventConsumer private
The IEventConsumer for the Repository.
Definition at line 97 of file Repository.cs.
Referenced by Tgstation.Server.Host.Components.Repository.Repository.AddTestMerge(), Tgstation.Server.Host.Components.Repository.Repository.CheckoutObject(), Tgstation.Server.Host.Components.Repository.Repository.FetchOrigin(), Tgstation.Server.Host.Components.Repository.Repository.MergeOrigin(), Tgstation.Server.Host.Components.Repository.Repository.Repository(), and Tgstation.Server.Host.Components.Repository.Repository.ResetToOrigin().
generalConfigurationOptions
readonly IOptionsMonitor<GeneralConfiguration> Tgstation.Server.Host.Components.Repository.Repository.generalConfigurationOptions private
The IOptionsMonitor<TOptions> of GeneralConfiguration for the Repository.
Definition at line 122 of file Repository.cs.
Referenced by Tgstation.Server.Host.Components.Repository.Repository.CopyTo(), and Tgstation.Server.Host.Components.Repository.Repository.Repository().
gitRemoteFeatures
readonly IGitRemoteFeatures Tgstation.Server.Host.Components.Repository.Repository.gitRemoteFeatures private
The IGitRemoteFeatures for the Repository.
Definition at line 112 of file Repository.cs.
Referenced by Tgstation.Server.Host.Components.Repository.Repository.AddTestMerge(), Tgstation.Server.Host.Components.Repository.Repository.FetchOrigin(), and Tgstation.Server.Host.Components.Repository.Repository.Repository().
ioManager
readonly IIOManager Tgstation.Server.Host.Components.Repository.Repository.ioManager private
The IIOManager for the Repository.
Definition at line 92 of file Repository.cs.
Referenced by Tgstation.Server.Host.Components.Repository.Repository.CopyTo(), and Tgstation.Server.Host.Components.Repository.Repository.Repository().
libGitRepo
readonly LibGit2Sharp.IRepository Tgstation.Server.Host.Components.Repository.Repository.libGitRepo private
The LibGit2Sharp.IRepository for the Repository.
Definition at line 82 of file Repository.cs.
Referenced by Tgstation.Server.Host.Components.Repository.Repository.AddTestMerge(), Tgstation.Server.Host.Components.Repository.Repository.CheckoutObject(), Tgstation.Server.Host.Components.Repository.Repository.FetchOrigin(), Tgstation.Server.Host.Components.Repository.Repository.GetOriginSha(), Tgstation.Server.Host.Components.Repository.Repository.MergeOrigin(), Tgstation.Server.Host.Components.Repository.Repository.Repository(), Tgstation.Server.Host.Components.Repository.Repository.ResetToOrigin(), and Tgstation.Server.Host.Components.Repository.Repository.ResetToSha().
logger
readonly ILogger<Repository> Tgstation.Server.Host.Components.Repository.Repository.logger private
The ILogger for the Repository.
Definition at line 127 of file Repository.cs.
Referenced by Tgstation.Server.Host.Components.Repository.Repository.AddTestMerge(), Tgstation.Server.Host.Components.Repository.Repository.CheckoutObject(), Tgstation.Server.Host.Components.Repository.Repository.CopyTo(), Tgstation.Server.Host.Components.Repository.Repository.FetchOrigin(), Tgstation.Server.Host.Components.Repository.Repository.MergeOrigin(), Tgstation.Server.Host.Components.Repository.Repository.Repository(), Tgstation.Server.Host.Components.Repository.Repository.ResetToOrigin(), and Tgstation.Server.Host.Components.Repository.Repository.ResetToSha().
NoReference
const string Tgstation.Server.Host.Components.Repository.Repository.NoReference = "(no branch)" static
The value of Reference when not on a reference.
Definition at line 51 of file Repository.cs.
OriginTrackingErrorTemplate
const string Tgstation.Server.Host.Components.Repository.Repository.OriginTrackingErrorTemplate = "Unable to determine most recent origin commit of {sha}. Marking it as an origin commit. This may result in invalid git metadata until the next hard reset to an origin reference." static
Template error message for when tracking of the most recent origin commit fails.
Definition at line 41 of file Repository.cs.
postWriteHandler
readonly IPostWriteHandler Tgstation.Server.Host.Components.Repository.Repository.postWriteHandler private
The IPostWriteHandler for the Repository.
Definition at line 107 of file Repository.cs.
Referenced by Tgstation.Server.Host.Components.Repository.Repository.CopyTo(), and Tgstation.Server.Host.Components.Repository.Repository.Repository().
PushOptions
PushOptions Tgstation.Server.Host.Components.Repository.Repository.PushOptions static private
Generate a standard set of PushOptions.
Parameters
progressReporter JobProgressReporter of the operation.
credentialsHandler The CredentialsHandler for the operation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a new set of PushOptions and the associated JobProgressReporters based off progressReporter .
Definition at line 136 of file Repository.cs.
Referenced by Tgstation.Server.Host.Components.Repository.Repository.GeneratePushOptions().
RemoteTemporaryBranchName
const string Tgstation.Server.Host.Components.Repository.Repository.RemoteTemporaryBranchName = "___TGSTempBranch" static
The branch name used for publishing testmerge commits.
Definition at line 46 of file Repository.cs.
submoduleFactory
readonly ILibGit2RepositoryFactory Tgstation.Server.Host.Components.Repository.Repository.submoduleFactory private
The ILibGit2RepositoryFactory used for updating submodules.
Definition at line 117 of file Repository.cs.
Referenced by Tgstation.Server.Host.Components.Repository.Repository.Repository().
UnknownReference
const string Tgstation.Server.Host.Components.Repository.Repository.UnknownReference = "<UNKNOWN>" static private
Used when a reference cannot be determined.
Definition at line 56 of file Repository.cs.
Referenced by Tgstation.Server.Host.Components.Repository.Repository.AddTestMerge(), and Tgstation.Server.Host.Components.Repository.Repository.MergeOrigin().
Property Documentation
Head
string Tgstation.Server.Host.Components.Repository.Repository.Head get
The SHA of the IRepository HEAD.
Implements Tgstation.Server.Host.Components.Repository.IRepository.
Definition at line 71 of file Repository.cs.
Origin
Uri Tgstation.Server.Host.Components.Repository.Repository.Origin get
The current origin remote the IRepository is using.
Implements Tgstation.Server.Host.Components.Repository.IRepository.
Definition at line 77 of file Repository.cs.
Reference
string Tgstation.Server.Host.Components.Repository.Repository.Reference get
The current reference the IRepository HEAD is using. This can be a branch or tag.
Implements Tgstation.Server.Host.Components.Repository.IRepository.
Definition at line 74 of file Repository.cs.
Referenced by Tgstation.Server.Host.Components.Repository.Repository.AddTestMerge().
RemoteGitProvider
RemoteGitProvider? Tgstation.Server.Host.Components.Repository.Repository.RemoteGitProvider get
The Models.RemoteGitProvider in use by the repository.
Implements Tgstation.Server.Api.Models.Internal.IGitRemoteInformation.
Definition at line 59 of file Repository.cs.
RemoteRepositoryName
string? Tgstation.Server.Host.Components.Repository.Repository.RemoteRepositoryName get
If RemoteGitProvider is not RemoteGitProvider.Unknown this will be set with the name of the repository.
Implements Tgstation.Server.Api.Models.Internal.IGitRemoteInformation.
Definition at line 65 of file Repository.cs.
RemoteRepositoryOwner
string? Tgstation.Server.Host.Components.Repository.Repository.RemoteRepositoryOwner get
If RemoteGitProvider is not RemoteGitProvider.Unknown this will be set with the owner of the repository.
Implements Tgstation.Server.Api.Models.Internal.IGitRemoteInformation.
Definition at line 62 of file Repository.cs.
Tracking
bool Tgstation.Server.Host.Components.Repository.Repository.Tracking get
If Reference tracks an upstream branch.
Implements Tgstation.Server.Host.Components.Repository.IRepository.
Definition at line 68 of file Repository.cs.
Referenced by Tgstation.Server.Host.Components.Repository.Repository.GetOriginSha(), Tgstation.Server.Host.Components.Repository.Repository.MergeOrigin(), and Tgstation.Server.Host.Components.Repository.Repository.ResetToOrigin().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Repository/Repository.cs