tgstation-server: Tgstation.Server.Host.Controllers.TransferController Class Reference
Tgstation.Server.Host.Controllers.TransferController Class Reference
ApiController for file streaming.
Public Member Functions
TransferController (IDatabaseContext databaseContext, IAuthenticationContextFactory authenticationContextFactory, IFileTransferStreamHandler fileTransferService, ILogger< ApiController > logger)
Initializes a new instance of the TransferController class.
async Task< IActionResult > Download ([Required, FromQuery] string ticket, CancellationToken cancellationToken)
Downloads a file with a given ticket .
async Task< IActionResult > Upload ([Required, FromQuery] string ticket, CancellationToken cancellationToken)
Uploads a file with a given ticket .
Public Member Functions inherited from Tgstation.Server.Host.Controllers.ApiController
override async Task OnActionExecutionAsync (ActionExecutingContext context, ActionExecutionDelegate next)
Private Attributes
readonly IFileTransferStreamHandler fileTransferService
The IFileTransferStreamHandler for the TransferController.
Additional Inherited Members
Protected Member Functions inherited from Tgstation.Server.Host.Controllers.ApiController
ApiController (IDatabaseContext databaseContext, IAuthenticationContextFactory authenticationContextFactory, ILogger< ApiController > logger, bool requireHeaders)
Construct an ApiController
ObjectResult Gone ()
Generic 410 response.
new NotFoundObjectResult NotFound ()
Generic 404 response.
ObjectResult RequiresPosixSystemIdentity ()
Generic 501 response.
StatusCodeResult StatusCode (HttpStatusCode statusCode)
Strongly type calls to ControllerBase.StatusCode(int).
ObjectResult StatusCode (HttpStatusCode statusCode, object errorMessage)
Strongly type calls to ControllerBase.StatusCode(int, object).
ObjectResult Created (object payload)
Generic 201 response with a given payload .
ObjectResult RateLimit (RateLimitExceededException rateLimitException)
429 response for a given rateLimitException .
virtual Task< IActionResult > ValidateRequest (CancellationToken cancellationToken)
Performs validation a request.
IActionResult HeadersIssue (bool ignoreMissingAuth)
Response for missing/Invalid headers.
Task< IActionResult > Paginated< TModel > (Func< Task< PaginatableResult< TModel >>> queryGenerator, Action< TModel > resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
Task< IActionResult > Paginated< TModel, TApiModel > (Func< Task< PaginatableResult< TModel >>> queryGenerator, Action< TApiModel > resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
Properties inherited from Tgstation.Server.Host.Controllers.ApiController
ApiHeaders ApiHeaders [get, private set]
The ApiHeaders for the operation
IDatabaseContext DatabaseContext [get]
The IDatabaseContext for the operation
IAuthenticationContext AuthenticationContext [get]
The IAuthenticationContext for the operation
ILogger< ApiController > Logger [get]
The ILogger for the ApiController
Models.Instance Instance [get]
The Instance for the operation
Detailed Description
ApiController for file streaming.
Definition at line 26 of file TransferController.cs.
Constructor & Destructor Documentation
TransferController()
Tgstation.Server.Host.Controllers.TransferController.TransferController (IDatabaseContext databaseContext, IAuthenticationContextFactory authenticationContextFactory, IFileTransferStreamHandler fileTransferService, ILogger< ApiController > logger)
Initializes a new instance of the TransferController class.
Parameters
databaseContext The IDatabaseContext for the ApiController
authenticationContextFactory The IAuthenticationContextFactory for the ApiController
fileTransferService The value of fileTransferService.
logger The ILogger for the ApiController
Definition at line 40 of file TransferController.cs.
             : base(
                   databaseContext,
                   authenticationContextFactory,
                   logger,
                   true)
         {
             this.fileTransferService = fileTransferService ?? throw new ArgumentNullException(nameof(fileTransferService));
         }
References Tgstation.Server.Host.Controllers.TransferController.fileTransferService.
Member Function Documentation
Download()
async Task<IActionResult> Tgstation.Server.Host.Controllers.TransferController.Download ([Required, FromQuery] string ticket, CancellationToken cancellationToken)
Downloads a file with a given ticket .
Parameters
ticket The FileTicketResponse.FileTicket for the download.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the IActionResult of the method.
<response code="200">Started streaming download successfully.</response> <response code="410">The ticket was no longer or was never valid.</response>
Definition at line 66 of file TransferController.cs.
         {
             if (ticket == null)
                 return BadRequest(new ErrorMessageResponse(ErrorCode.ModelValidationFailure));
             var streamAccept = new MediaTypeHeaderValue(MediaTypeNames.Application.Octet);
             if (!Request.GetTypedHeaders().Accept.Any(x => streamAccept.IsSubsetOf(x)))
                 return StatusCode(HttpStatusCode.NotAcceptable, new ErrorMessageResponse(ErrorCode.BadHeaders)
                 {
                     AdditionalData = $"File downloads must accept both {MediaTypeNames.Application.Octet} and {MediaTypeNames.Application.Json}!"
                 });
             var fileTicketResult = new FileTicketResponse
             {
                 FileTicket = ticket
             };
             var tuple = await fileTransferService.RetrieveDownloadStream(fileTicketResult, cancellationToken).ConfigureAwait(false);
             var stream = tuple.Item1;
             try
             {
                 if (tuple.Item2 != null)
                     return Conflict(tuple.Item2);
                 if (stream == null)
                     return Gone();
                 return new LimitedFileStreamResult(stream);
             }
             catch
             {
                 stream.Dispose();
                 throw;
             }
         }
References Tgstation.Server.Host.Controllers.TransferController.fileTransferService, Tgstation.Server.Host.Controllers.ApiController.Gone(), Tgstation.Server.Host.Transfer.IFileTransferStreamHandler.RetrieveDownloadStream(), and Tgstation.Server.Host.Controllers.ApiController.StatusCode().
Referenced by Tgstation.Server.Host.Core.SwaggerConfiguration.Apply().
Upload()
async Task<IActionResult> Tgstation.Server.Host.Controllers.TransferController.Upload ([Required, FromQuery] string ticket, CancellationToken cancellationToken)
Uploads a file with a given ticket .
Parameters
ticket The FileTicketResponse.FileTicket for the upload.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the IActionResult of the method.
<response code="204">Uploaded file successfully.</response> <response code="409">An error occurred during the upload.</response> <response code="410">The ticket was no longer or was never valid.</response>
Definition at line 115 of file TransferController.cs.
         {
             if (ticket == null)
                 return BadRequest(new ErrorMessageResponse(ErrorCode.ModelValidationFailure));
             var fileTicketResult = new FileTicketResponse
             {
                 FileTicket = ticket
             };
             var result = await fileTransferService.SetUploadStream(fileTicketResult, Request.Body, cancellationToken).ConfigureAwait(false);
             if (result != null)
                 return result.ErrorCode == ErrorCode.ResourceNotPresent
                     ? Gone()
                     : Conflict(result);
             return NoContent();
         }
References Tgstation.Server.Host.Controllers.TransferController.fileTransferService, Tgstation.Server.Host.Controllers.ApiController.Gone(), and Tgstation.Server.Host.Transfer.IFileTransferStreamHandler.SetUploadStream().
Referenced by Tgstation.Server.Host.Core.SwaggerConfiguration.Apply().
Member Data Documentation
fileTransferService
readonly IFileTransferStreamHandler Tgstation.Server.Host.Controllers.TransferController.fileTransferService private
The IFileTransferStreamHandler for the TransferController.
Definition at line 31 of file TransferController.cs.
Referenced by Tgstation.Server.Host.Controllers.TransferController.Download(), Tgstation.Server.Host.Controllers.TransferController.TransferController(), and Tgstation.Server.Host.Controllers.TransferController.Upload().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Controllers/TransferController.cs