tgstation-server: Tgstation.Server.Host.Utils.GitLab.GraphQL.GraphQLGitLabClientFactory Class Reference
Tgstation.Server.Host.Utils.GitLab.GraphQL.GraphQLGitLabClientFactory Class Reference sealed
Factory for creating IGraphQLGitLabClients.
Static Public Member Functions
static async ValueTask< IGraphQLGitLabClient > CreateClient (string? bearerToken=null)
Sets up a IGraphQLGitLabClient.
Detailed Description
Factory for creating IGraphQLGitLabClients.
Definition at line 12 of file GraphQLGitLabClientFactory.cs.
Member Function Documentation
CreateClient()
static async ValueTask< IGraphQLGitLabClient > Tgstation.Server.Host.Utils.GitLab.GraphQL.GraphQLGitLabClientFactory.CreateClient (string? bearerToken = null) static
Sets up a IGraphQLGitLabClient.
Parameters
bearerToken The token to use for authentication, if any.
Returns
A ValueTask<TResult> resulting in a new IGraphQLGitLabClient.
Definition at line 19 of file GraphQLGitLabClientFactory.cs.
        {
            var serviceCollection = new ServiceCollection();
            var clientBuilder = serviceCollection
                .AddGraphQLClient();
            var graphQLEndpoint = new Uri("https://gitlab.com/api/graphql");
            clientBuilder.ConfigureHttpClient(
                client =>
                {
                    client.BaseAddress = new Uri("https://gitlab.com/api/graphql");
                    if (bearerToken != null)
                    {
                        client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", bearerToken);
                    }
                });
            var serviceProvider = serviceCollection.BuildServiceProvider();
            try
            {
                return new GraphQLGitLabClient(serviceProvider);
            }
            catch
            {
                await serviceProvider.DisposeAsync();
                throw;
            }
        }
Referenced by Tgstation.Server.Host.Components.Deployment.Remote.GitLabRemoteDeploymentManager.CommentOnTestMergeSource(), Tgstation.Server.Host.Components.Repository.GitLabRemoteFeatures.GetTestMergeImpl(), Tgstation.Server.Host.Components.Deployment.Remote.GitLabRemoteDeploymentManager.RemoveMergedTestMerges(), and Tgstation.Server.Host.Controllers.RepositoryController.ValidateCredentials().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host.Utils.GitLab.GraphQL/GraphQLGitLabClientFactory.cs