tgstation-server: Tgstation.Server.Host.Components.Byond.ByondManager Class Reference
Tgstation.Server.Host.Components.Byond.ByondManager Class Reference
Public Member Functions
ByondManager (IIOManager ioManager, IByondInstaller byondInstaller, IEventConsumer eventConsumer, ILogger< ByondManager > logger)
Initializes a new instance of the ByondManager class.
void Dispose ()
async Task ChangeVersion (JobProgressReporter progressReporter, Version version, Stream customVersionStream, bool allowInstallation, CancellationToken cancellationToken)
Change the active BYOND version.
Parameters
progressReporter The optional JobProgressReporter for the operation.
version The new Version.
customVersionStream Optional Stream of a custom BYOND version zip file.
allowInstallation If an installation should be performed if the version is not installed. If false and an installation is required an InvalidOperationException will be thrown.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
async Task< IByondExecutableLock > UseExecutables (Version requiredVersion, string trustDmbFullPath, CancellationToken cancellationToken)
Lock the current installation's location and return a IByondExecutableLock.
Parameters
requiredVersion The BYOND Version required.
trustDmbFullPath The optional full path to .dmb to trust while using the executables.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the requested IByondExecutableLock.
async Task DeleteVersion (JobProgressReporter progressReporter, Version version, CancellationToken cancellationToken)
Deletes a given BYOND version from the disk.
Parameters
progressReporter The JobProgressReporter for the operation.
version The Version to delete.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
async Task StartAsync (CancellationToken cancellationToken)
Task StopAsync (CancellationToken cancellationToken)
Task ChangeVersion (JobProgressReporter progressReporter, Version version, Stream customVersionStream, bool allowInstallation, CancellationToken cancellationToken)
Change the active BYOND version.
Task DeleteVersion (JobProgressReporter progressReporter, Version version, CancellationToken cancellationToken)
Deletes a given BYOND version from the disk.
Task< IByondExecutableLock > UseExecutables (Version requiredVersion, string trustDmbFullPath, CancellationToken cancellationToken)
Lock the current installation's location and return a IByondExecutableLock.
Static Public Attributes
const string BinPath = "byond/bin"
The path to the BYOND bin folder.
Properties
Version ActiveVersion [get, private set]
The currently active BYOND version.
IReadOnlyList< Version > InstalledVersions [get]
The installed BYOND versions.
Properties inherited from Tgstation.Server.Host.Components.Byond.IByondManager
Version ActiveVersion [get]
The currently active BYOND version.
IReadOnlyList< Version > InstalledVersions [get]
The installed BYOND versions.
Private Member Functions
async Task< ByondExecutableLock > AssertAndLockVersion (JobProgressReporter progressReporter, Version version, Stream customVersionStream, bool neededForLock, bool allowInstallation, CancellationToken cancellationToken)
Ensures a BYOND version is installed if it isn't already.
async Task InstallVersionFiles (JobProgressReporter progressReporter, Version version, Stream customVersionStream, CancellationToken cancellationToken)
Installs the files for a given BYOND version .
ReferenceCountingContainer< ByondInstallation, ByondExecutableLock > AddInstallationContainer (Version version, Task installationTask)
Create and add a new ByondInstallation to installedVersions.
async Task TrustDmbPath (string fullDmbPath, CancellationToken cancellationToken)
Add a given fullDmbPath to the trusted DMBs list in BYOND's config.
Static Private Member Functions
static void CheckVersionParameter (Version version)
Validates a given version parameter.
Private Attributes
readonly IIOManager ioManager
The IIOManager for the ByondManager.
readonly IByondInstaller byondInstaller
The IByondInstaller for the ByondManager.
readonly IEventConsumer eventConsumer
The IEventConsumer for the ByondManager.
readonly ILogger< ByondManager > logger
The ILogger for the ByondManager.
readonly Dictionary< Version, ReferenceCountingContainer< ByondInstallation, ByondExecutableLock > > installedVersions
Map of byond Versions to Tasks that complete when they are installed.
readonly SemaphoreSlim changeDeleteSemaphore
The SemaphoreSlim for changing or deleting the active BYOND version.
TaskCompletionSource activeVersionChanged
TaskCompletionSource that notifes when the ActiveVersion changes.
Static Private Attributes
const string CfgDirectoryName = "cfg"
The path to the cfg directory.
const string TrustedDmbFileName = "trusted.txt"
The name of the list of trusted .dmb files in the user's BYOND cfg directory.
const string VersionFileName = "Version.txt"
The file in which we store the Version for installations.
const string ActiveVersionFileName = "ActiveVersion.txt"
The file in which we store the ActiveVersion.
static readonly SemaphoreSlim UserFilesSemaphore = new (1)
SemaphoreSlim for writing to files in the user's BYOND directory.
Detailed Description
Definition at line 21 of file ByondManager.cs.
Constructor & Destructor Documentation
ByondManager()
Tgstation.Server.Host.Components.Byond.ByondManager.ByondManager (IIOManager ioManager, IByondInstaller byondInstaller, IEventConsumer eventConsumer, ILogger< ByondManager > logger)
Initializes a new instance of the ByondManager class.
Parameters
ioManager The value of ioManager.
byondInstaller The value of byondInstaller.
eventConsumer The value of eventConsumer.
logger The value of logger.
Definition at line 120 of file ByondManager.cs.
        {
            this.ioManager = ioManager ?? throw new ArgumentNullException(nameof(ioManager));
            this.byondInstaller = byondInstaller ?? throw new ArgumentNullException(nameof(byondInstaller));
            this.eventConsumer = eventConsumer ?? throw new ArgumentNullException(nameof(eventConsumer));
            this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
            installedVersions = new Dictionary<Version, ReferenceCountingContainer<ByondInstallation, ByondExecutableLock>>();
            changeDeleteSemaphore = new SemaphoreSlim(1);
            activeVersionChanged = new TaskCompletionSource();
        }
References Tgstation.Server.Host.Components.Byond.ByondManager.activeVersionChanged, Tgstation.Server.Host.Components.Byond.ByondManager.byondInstaller, Tgstation.Server.Host.Components.Byond.ByondManager.changeDeleteSemaphore, Tgstation.Server.Host.Components.Byond.ByondManager.eventConsumer, Tgstation.Server.Host.Components.Byond.ByondManager.installedVersions, Tgstation.Server.Host.Components.Byond.ByondManager.ioManager, and Tgstation.Server.Host.Components.Byond.ByondManager.logger.
Member Function Documentation
AddInstallationContainer()
ReferenceCountingContainer< ByondInstallation, ByondExecutableLock > Tgstation.Server.Host.Components.Byond.ByondManager.AddInstallationContainer (Version version, Task installationTask) private
Create and add a new ByondInstallation to installedVersions.
Parameters
version The Version being added.
installationTask The Task representing the installation process.
Returns
The new ReferenceCountingContainer<TWrapped, TReference> containing the new ByondInstallation.
Definition at line 588 of file ByondManager.cs.
        {
            var binPathForVersion = ioManager.ConcatPath(version.ToString(), BinPath);
            var installation = new ByondInstallation(
                installationTask,
                version,
                ioManager.ResolvePath(
                    ioManager.ConcatPath(
                        binPathForVersion,
                        byondInstaller.GetDreamDaemonName(
                            version,
                            out var supportsCli,
                            out var supportsMapThreads))),
                ioManager.ResolvePath(
                    ioManager.ConcatPath(
                        binPathForVersion,
                        byondInstaller.DreamMakerName)),
                supportsCli,
                supportsMapThreads);
            var installationContainer = new ReferenceCountingContainer<ByondInstallation, ByondExecutableLock>(installation);
            lock (installedVersions)
                installedVersions.Add(version, installationContainer);
            return installationContainer;
        }
References Tgstation.Server.Host.Components.Byond.ByondManager.BinPath, Tgstation.Server.Host.Components.Byond.ByondManager.byondInstaller, Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.Components.Byond.IByondInstaller.DreamMakerName, Tgstation.Server.Host.Components.Byond.IByondInstaller.GetDreamDaemonName(), Tgstation.Server.Host.Components.Byond.ByondManager.installedVersions, Tgstation.Server.Host.Components.Byond.ByondManager.ioManager, and Tgstation.Server.Host.IO.IIOManager.ResolvePath().
Referenced by Tgstation.Server.Host.Components.Byond.ByondManager.AssertAndLockVersion(), and Tgstation.Server.Host.Components.Byond.ByondManager.StartAsync().
AssertAndLockVersion()
async Task< ByondExecutableLock > Tgstation.Server.Host.Components.Byond.ByondManager.AssertAndLockVersion (JobProgressReporter progressReporter, Version version, Stream customVersionStream, bool neededForLock, bool allowInstallation, CancellationToken cancellationToken) private
Ensures a BYOND version is installed if it isn't already.
Parameters
progressReporter The optional JobProgressReporter for the operation.
version The BYOND Version to install.
customVersionStream Custom zip file Stream to use. Will cause a Version.Build number to be added.
neededForLock If this BYOND version is required as part of a locking operation.
allowInstallation If an installation should be performed if the version is not installed. If false and an installation is required an InvalidOperationException will be thrown.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the ByondExecutableLock.
Definition at line 410 of file ByondManager.cs.
        {
            var ourTcs = new TaskCompletionSource();
            ByondInstallation installation;
            ByondExecutableLock installLock;
            bool installedOrInstalling;
            lock (installedVersions)
            {
                if (customVersionStream != null)
                {
                    var customInstallationNumber = 1;
                    do
                    {
                        version = new Version(version.Major, version.Minor, customInstallationNumber++);
                    }
                    while (installedVersions.ContainsKey(version));
                }
                installedOrInstalling = installedVersions.TryGetValue(version, out var installationContainer);
                if (!installedOrInstalling)
                {
                    if (!allowInstallation)
                        throw new InvalidOperationException($"BYOND version {version} not installed!");
                    installationContainer = AddInstallationContainer(version, ourTcs.Task);
                }
                installation = installationContainer.Instance;
                installLock = installationContainer.AddReference();
            }
            try
            {
                if (installedOrInstalling)
                {
                    if (progressReporter != null)
                        progressReporter.StageName = "Waiting for existing installation job...";
                    if (neededForLock && !installation.InstallationTask.IsCompleted)
                        logger.LogWarning("The required BYOND version ({version}) is not readily available! We will have to wait for it to install.", version);
                    await installation.InstallationTask.WaitAsync(cancellationToken);
                    return installLock;
                }
                // okay up to us to install it then
                try
                {
                    if (customVersionStream != null)
                        logger.LogInformation("Installing custom BYOND version as {version}...", version);
                    else if (neededForLock)
                    {
                        if (version.Build > 0)
                            throw new JobException(ErrorCode.ByondNonExistentCustomVersion);
                        logger.LogWarning("The required BYOND version ({version}) is not readily available! We will have to install it.", version);
                    }
                    else
                        logger.LogDebug("Requested BYOND version {version} not currently installed. Doing so now...", version);
                    if (progressReporter != null)
                        progressReporter.StageName = "Running event";
                    var versionString = version.ToString();
                    await eventConsumer.HandleEvent(EventType.ByondInstallStart, new List<string> { versionString }, false, cancellationToken);
                    await InstallVersionFiles(progressReporter, version, customVersionStream, cancellationToken);
                    ourTcs.SetResult();
                }
                catch (Exception ex)
                {
                    if (ex is not OperationCanceledException)
                        await eventConsumer.HandleEvent(EventType.ByondInstallFail, new List<string> { ex.Message }, false, cancellationToken);
                    lock (installedVersions)
                        installedVersions.Remove(version);
                    ourTcs.SetException(ex);
                    throw;
                }
                return installLock;
            }
            catch
            {
                installLock.Dispose();
                throw;
            }
        }
References Tgstation.Server.Host.Components.Byond.ByondManager.AddInstallationContainer(), Tgstation.Server.Host.Utils.ReferenceCounter< TInstance >.Dispose(), Tgstation.Server.Host.Components.Byond.ByondManager.eventConsumer, Tgstation.Server.Host.Components.Events.IEventConsumer.HandleEvent(), Tgstation.Server.Host.Components.Byond.ByondInstallation.InstallationTask, Tgstation.Server.Host.Components.Byond.ByondManager.installedVersions, Tgstation.Server.Host.Components.Byond.ByondManager.InstallVersionFiles(), and Tgstation.Server.Host.Components.Byond.ByondManager.logger.
Referenced by Tgstation.Server.Host.Components.Byond.ByondManager.ChangeVersion(), and Tgstation.Server.Host.Components.Byond.ByondManager.UseExecutables().
ChangeVersion()
async Task Tgstation.Server.Host.Components.Byond.ByondManager.ChangeVersion (JobProgressReporter progressReporter, Version version, Stream customVersionStream, bool allowInstallation, CancellationToken cancellationToken)
Change the active BYOND version.
Parameters
progressReporter The optional JobProgressReporter for the operation.
version The new Version.
customVersionStream Optional Stream of a custom BYOND version zip file.
allowInstallation If an installation should be performed if the version is not installed. If false and an installation is required an InvalidOperationException will be thrown.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implements Tgstation.Server.Host.Components.Byond.IByondManager.
Definition at line 136 of file ByondManager.cs.
        {
            CheckVersionParameter(version);
            using (await SemaphoreSlimContext.Lock(changeDeleteSemaphore, cancellationToken))
            {
                using var installLock = await AssertAndLockVersion(
                progressReporter,
                version,
                customVersionStream,
                false,
                allowInstallation,
                cancellationToken);
                // We reparse the version because it could be changed after a custom install.
                version = installLock.Version;
                var stringVersion = version.ToString();
                await ioManager.WriteAllBytes(ActiveVersionFileName, Encoding.UTF8.GetBytes(stringVersion), cancellationToken);
                await eventConsumer.HandleEvent(
                    EventType.ByondActiveVersionChange,
                    new List<string>
                    {
                        ActiveVersion?.ToString(),
                        stringVersion,
                    },
                    false,
                    cancellationToken);
                ActiveVersion = version;
                activeVersionChanged.SetResult();
                activeVersionChanged = new TaskCompletionSource();
            }
            logger.LogInformation("Active version changed to {version}", version);
        }
References Tgstation.Server.Host.Components.Byond.ByondManager.ActiveVersion, Tgstation.Server.Host.Components.Byond.ByondManager.activeVersionChanged, Tgstation.Server.Host.Components.Byond.ByondManager.ActiveVersionFileName, Tgstation.Server.Host.Components.Byond.ByondManager.AssertAndLockVersion(), Tgstation.Server.Host.Components.Byond.ByondManager.changeDeleteSemaphore, Tgstation.Server.Host.Components.Byond.ByondManager.CheckVersionParameter(), Tgstation.Server.Host.Components.Byond.ByondManager.eventConsumer, Tgstation.Server.Host.Components.Events.IEventConsumer.HandleEvent(), Tgstation.Server.Host.Components.Byond.ByondManager.ioManager, Tgstation.Server.Host.Utils.SemaphoreSlimContext.Lock(), Tgstation.Server.Host.Components.Byond.ByondManager.logger, and Tgstation.Server.Host.IO.IIOManager.WriteAllBytes().
CheckVersionParameter()
static void Tgstation.Server.Host.Components.Byond.ByondManager.CheckVersionParameter (Version version) static private
Validates a given version parameter.
Parameters
version The Version to validate.
Definition at line 105 of file ByondManager.cs.
        {
            ArgumentNullException.ThrowIfNull(version);
            if (version.Build == 0)
                throw new ArgumentException("version.Build cannot be 0!", nameof(version));
        }
Referenced by Tgstation.Server.Host.Components.Byond.ByondManager.ChangeVersion(), and Tgstation.Server.Host.Components.Byond.ByondManager.DeleteVersion().
DeleteVersion()
async Task Tgstation.Server.Host.Components.Byond.ByondManager.DeleteVersion (JobProgressReporter progressReporter, Version version, CancellationToken cancellationToken)
Deletes a given BYOND version from the disk.
Parameters
progressReporter The JobProgressReporter for the operation.
version The Version to delete.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implements Tgstation.Server.Host.Components.Byond.IByondManager.
Definition at line 207 of file ByondManager.cs.
        {
            ArgumentNullException.ThrowIfNull(progressReporter);
            CheckVersionParameter(version);
            logger.LogTrace("DeleteVersion {version}", version);
            if (version == ActiveVersion)
                throw new JobException(ErrorCode.ByondCannotDeleteActiveVersion);
            ReferenceCountingContainer<ByondInstallation, ByondExecutableLock> container;
            lock (installedVersions)
                if (!installedVersions.TryGetValue(version, out container))
                    return; // already "deleted"
            logger.LogInformation("Deleting BYOND version {version}...", version);
            progressReporter.StageName = "Waiting for version to not be in use...";
            while (true)
            {
                var containerTask = container.OnZeroReferences;
                // We also want to check when the active version changes in case we need to fail the job because of that.
                Task activeVersionUpdate;
                using (await SemaphoreSlimContext.Lock(changeDeleteSemaphore, cancellationToken))
                    activeVersionUpdate = activeVersionChanged.Task;
                await Task.WhenAny(
                    containerTask,
                    activeVersionUpdate)
                    .WaitAsync(cancellationToken);
                if (containerTask.IsCompleted)
                    logger.LogTrace("All BYOND locks for {version} are gone", version);
                using (await SemaphoreSlimContext.Lock(changeDeleteSemaphore, cancellationToken))
                {
                    // check again because it could have become the active version.
                    if (version == ActiveVersion)
                        throw new JobException(ErrorCode.ByondCannotDeleteActiveVersion);
                    bool proceed;
                    lock (installedVersions)
                    {
                        proceed = container.OnZeroReferences.IsCompleted;
                        if (proceed)
                            if (!installedVersions.TryGetValue(version, out var newerContainer))
                                logger.LogWarning("Unable to remove BYOND installation {version} from list! Is there a duplicate job running?", version);
                            else
{
                                if (container != newerContainer)
{
                                    // Okay let me get this straight, there was a duplicate delete job, it ran before us after we grabbed the container, AND another installation of the same version completed?
                                    // I know realistically this is practically impossible, but god damn that small possiblility
                                    // best thing to do is check we exclusively own the newer container
                                    logger.LogDebug("Extreme race condition encountered, applying concentrated copium...");
                                    container = newerContainer;
                                    proceed = container.OnZeroReferences.IsCompleted;
                                }
                                if (proceed)
                                    installedVersions.Remove(version);
                            }
                    }
                    if (proceed)
                    {
                        progressReporter.StageName = "Deleting installation...";
                        // delete the version file first, because we will know not to re-discover the installation if it's not present and it will get cleaned on reboot
                        var installPath = version.ToString();
                        await ioManager.DeleteFile(
                            ioManager.ConcatPath(installPath, VersionFileName),
                            cancellationToken);
                        await ioManager.DeleteDirectory(installPath, cancellationToken);
                        return;
                    }
                    if (containerTask.IsCompleted)
                        logger.LogDebug(
                            "Another lock was acquired before we could remove version {version} from the list. We will have to wait again.",
                            version);
                }
            }
        }
References Tgstation.Server.Host.Components.Byond.ByondManager.ActiveVersion, Tgstation.Server.Host.Components.Byond.ByondManager.activeVersionChanged, Tgstation.Server.Host.Components.Byond.ByondManager.changeDeleteSemaphore, Tgstation.Server.Host.Components.Byond.ByondManager.CheckVersionParameter(), Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.IO.IIOManager.DeleteDirectory(), Tgstation.Server.Host.IO.IIOManager.DeleteFile(), Tgstation.Server.Host.Components.Byond.ByondManager.installedVersions, Tgstation.Server.Host.Components.Byond.ByondManager.ioManager, Tgstation.Server.Host.Utils.SemaphoreSlimContext.Lock(), Tgstation.Server.Host.Components.Byond.ByondManager.logger, Tgstation.Server.Host.Utils.ReferenceCountingContainer< TWrapped, TReference >.OnZeroReferences, and Tgstation.Server.Host.Components.Byond.ByondManager.VersionFileName.
Dispose()
void Tgstation.Server.Host.Components.Byond.ByondManager.Dispose ()
Referenced by Tgstation.Server.Host.Components.Instance.DisposeAsync().
InstallVersionFiles()
async Task Tgstation.Server.Host.Components.Byond.ByondManager.InstallVersionFiles (JobProgressReporter progressReporter, Version version, Stream customVersionStream, CancellationToken cancellationToken) private
Installs the files for a given BYOND version .
Parameters
progressReporter The optional JobProgressReporter for the operation.
version The BYOND Version being installed with the Version.Build number set if appropriate.
customVersionStream Custom zip file Stream to use. Will cause a Version.Build number to be added.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Definition at line 515 of file ByondManager.cs.
        {
            var installFullPath = ioManager.ResolvePath(version.ToString());
            async Task DirectoryCleanup()
            {
                await ioManager.DeleteDirectory(installFullPath, cancellationToken);
                await ioManager.CreateDirectory(installFullPath, cancellationToken);
            }
            var directoryCleanupTask = DirectoryCleanup();
            try
            {
                Stream versionZipStream;
                if (customVersionStream == null)
                {
                    if (progressReporter != null)
                        progressReporter.StageName = "Downloading version";
                    versionZipStream = await byondInstaller.DownloadVersion(version, cancellationToken);
                }
                else
                    versionZipStream = customVersionStream;
                await using (versionZipStream)
                {
                    if (progressReporter != null)
                        progressReporter.StageName = "Cleaning target directory";
                    await directoryCleanupTask;
                    if (progressReporter != null)
                        progressReporter.StageName = "Extracting zip";
                    logger.LogTrace("Extracting downloaded BYOND zip to {extractPath}...", installFullPath);
                    await ioManager.ZipToDirectory(installFullPath, versionZipStream, cancellationToken);
                }
                if (progressReporter != null)
                    progressReporter.StageName = "Running installation actions";
                await byondInstaller.InstallByond(version, installFullPath, cancellationToken);
                if (progressReporter != null)
                    progressReporter.StageName = "Writing version file";
                // make sure to do this last because this is what tells us we have a valid version in the future
                await ioManager.WriteAllBytes(
                    ioManager.ConcatPath(installFullPath, VersionFileName),
                    Encoding.UTF8.GetBytes(version.ToString()),
                    cancellationToken);
            }
            catch (HttpRequestException e)
            {
                // since the user can easily provide non-exitent version numbers, we'll turn this into a JobException
                throw new JobException(ErrorCode.ByondDownloadFail, e);
            }
            catch (OperationCanceledException)
            {
                throw;
            }
            catch
            {
                await ioManager.DeleteDirectory(installFullPath, cancellationToken);
                throw;
            }
        }
References Tgstation.Server.Host.Components.Byond.ByondManager.byondInstaller, Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.IO.IIOManager.CreateDirectory(), Tgstation.Server.Host.IO.IIOManager.DeleteDirectory(), Tgstation.Server.Host.Components.Byond.IByondInstaller.DownloadVersion(), Tgstation.Server.Host.Components.Byond.IByondInstaller.InstallByond(), Tgstation.Server.Host.Components.Byond.ByondManager.ioManager, Tgstation.Server.Host.Components.Byond.ByondManager.logger, Tgstation.Server.Host.IO.IIOManager.ResolvePath(), Tgstation.Server.Host.Components.Byond.ByondManager.VersionFileName, Tgstation.Server.Host.IO.IIOManager.WriteAllBytes(), and Tgstation.Server.Host.IO.IIOManager.ZipToDirectory().
Referenced by Tgstation.Server.Host.Components.Byond.ByondManager.AssertAndLockVersion().
StartAsync()
async Task Tgstation.Server.Host.Components.Byond.ByondManager.StartAsync (CancellationToken cancellationToken)
Definition at line 294 of file ByondManager.cs.
        {
            async Task<byte[]> GetActiveVersion()
            {
                var activeVersionFileExists = await ioManager.FileExists(ActiveVersionFileName, cancellationToken);
                return !activeVersionFileExists ? null : await ioManager.ReadAllBytes(ActiveVersionFileName, cancellationToken);
            }
            var activeVersionBytesTask = GetActiveVersion();
            var byondDir = byondInstaller.PathToUserByondFolder;
            if (byondDir != null)
                using (await SemaphoreSlimContext.Lock(UserFilesSemaphore, cancellationToken))
                {
                    // Create local cfg directory in case it doesn't exist
                    var localCfgDirectory = ioManager.ConcatPath(
                            byondDir,
                            CfgDirectoryName);
                    await ioManager.CreateDirectory(
                        localCfgDirectory,
                        cancellationToken);
                    // Delete trusted.txt so it doesn't grow too large
                    var trustedFilePath =
                        ioManager.ConcatPath(
                            localCfgDirectory,
                            TrustedDmbFileName);
                    logger.LogTrace("Deleting trusted .dmbs file {trustedFilePath}", trustedFilePath);
                    await ioManager.DeleteFile(
                        trustedFilePath,
                        cancellationToken);
                }
            await ioManager.CreateDirectory(DefaultIOManager.CurrentDirectory, cancellationToken);
            var directories = await ioManager.GetDirectories(DefaultIOManager.CurrentDirectory, cancellationToken);
            var installedVersionPaths = new Dictionary<string, Version>();
            async Task ReadVersion(string path)
            {
                var versionFile = ioManager.ConcatPath(path, VersionFileName);
                if (!await ioManager.FileExists(versionFile, cancellationToken))
                {
                    logger.LogWarning("Cleaning path with no version file: {versionPath}", ioManager.ResolvePath(path));
                    await ioManager.DeleteDirectory(path, cancellationToken); // cleanup
                    return;
                }
                var bytes = await ioManager.ReadAllBytes(versionFile, cancellationToken);
                var text = Encoding.UTF8.GetString(bytes);
                if (!Version.TryParse(text, out var version))
                {
                    logger.LogWarning("Cleaning path with unparsable version file: {versionPath}", ioManager.ResolvePath(path));
                    await ioManager.DeleteDirectory(path, cancellationToken); // cleanup
                    return;
                }
                try
                {
                    AddInstallationContainer(version, Task.CompletedTask);
                    logger.LogDebug("Added detected BYOND version {versionKey}...", version);
                }
                catch (Exception ex)
                {
                    logger.LogWarning(
                        ex,
                        "It seems that there are multiple directories that say they contain BYOND version {version}. We're ignoring and cleaning the duplicate: {duplicatePath}",
                        version,
                        ioManager.ResolvePath(path));
                    await ioManager.DeleteDirectory(path, cancellationToken);
                    return;
                }
                lock (installedVersionPaths)
                    installedVersionPaths.Add(ioManager.ResolvePath(version.ToString()), version);
            }
            await Task.WhenAll(directories.Select(ReadVersion));
            logger.LogTrace("Upgrading BYOND installations...");
            await Task.WhenAll(installedVersionPaths.Select(kvp => byondInstaller.UpgradeInstallation(kvp.Value, kvp.Key, cancellationToken)));
            var activeVersionBytes = await activeVersionBytesTask;
            if (activeVersionBytes != null)
            {
                var activeVersionString = Encoding.UTF8.GetString(activeVersionBytes);
                Version activeVersion;
                bool hasRequestedActiveVersion;
                lock (installedVersions)
                    hasRequestedActiveVersion = Version.TryParse(activeVersionString, out activeVersion)
                        && installedVersions.ContainsKey(activeVersion);
                if (hasRequestedActiveVersion)
                    ActiveVersion = activeVersion; // not setting TCS because there's no need during init
                else
                {
                    logger.LogWarning("Failed to load saved active version {activeVersion}!", activeVersionString);
                    await ioManager.DeleteFile(ActiveVersionFileName, cancellationToken);
                }
            }
        }
References Tgstation.Server.Host.Components.Byond.ByondManager.ActiveVersion, Tgstation.Server.Host.Components.Byond.ByondManager.ActiveVersionFileName, Tgstation.Server.Host.Components.Byond.ByondManager.AddInstallationContainer(), Tgstation.Server.Host.Components.Byond.ByondManager.byondInstaller, Tgstation.Server.Host.Components.Byond.ByondManager.CfgDirectoryName, Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.IO.IIOManager.CreateDirectory(), Tgstation.Server.Host.IO.DefaultIOManager.CurrentDirectory, Tgstation.Server.Host.IO.IIOManager.DeleteDirectory(), Tgstation.Server.Host.IO.IIOManager.DeleteFile(), Tgstation.Server.Host.IO.IIOManager.FileExists(), Tgstation.Server.Host.IO.IIOManager.GetDirectories(), Tgstation.Server.Host.Components.Byond.ByondManager.installedVersions, Tgstation.Server.Host.Components.Byond.ByondManager.ioManager, Tgstation.Server.Host.Utils.SemaphoreSlimContext.Lock(), Tgstation.Server.Host.Components.Byond.ByondManager.logger, Tgstation.Server.Host.Components.Byond.IByondInstaller.PathToUserByondFolder, Tgstation.Server.Host.IO.IIOManager.ReadAllBytes(), Tgstation.Server.Host.IO.IIOManager.ResolvePath(), Tgstation.Server.Host.Components.Byond.ByondManager.TrustedDmbFileName, Tgstation.Server.Host.Components.Byond.IByondInstaller.UpgradeInstallation(), Tgstation.Server.Host.Components.Byond.ByondManager.UserFilesSemaphore, and Tgstation.Server.Host.Components.Byond.ByondManager.VersionFileName.
Referenced by Tgstation.Server.Host.Components.Instance.StartAsync().
StopAsync()
Task Tgstation.Server.Host.Components.Byond.ByondManager.StopAsync (CancellationToken cancellationToken)
Referenced by Tgstation.Server.Host.Components.Instance.StopAsync().
TrustDmbPath()
async Task Tgstation.Server.Host.Components.Byond.ByondManager.TrustDmbPath (string fullDmbPath, CancellationToken cancellationToken) private
Add a given fullDmbPath to the trusted DMBs list in BYOND's config.
Parameters
fullDmbPath Full path to the .dmb that should be trusted.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Definition at line 622 of file ByondManager.cs.
        {
            var byondDir = byondInstaller.PathToUserByondFolder;
            if (String.IsNullOrWhiteSpace(byondDir))
            {
                logger.LogTrace("No relevant user BYOND directory to install a \"{fileName}\" in", TrustedDmbFileName);
                return;
            }
            var trustedFilePath = ioManager.ConcatPath(
                byondDir,
                CfgDirectoryName,
                TrustedDmbFileName);
            logger.LogDebug("Adding .dmb ({dmbPath}) to {trustedFilePath}", fullDmbPath, trustedFilePath);
            using (await SemaphoreSlimContext.Lock(UserFilesSemaphore, cancellationToken))
            {
                string trustedFileText;
                if (await ioManager.FileExists(trustedFilePath, cancellationToken))
                {
                    var trustedFileBytes = await ioManager.ReadAllBytes(trustedFilePath, cancellationToken);
                    trustedFileText = Encoding.UTF8.GetString(trustedFileBytes);
                    trustedFileText = $"{trustedFileText.Trim()}{Environment.NewLine}";
                }
                else
                    trustedFileText = String.Empty;
                if (trustedFileText.Contains(fullDmbPath, StringComparison.Ordinal))
                    return;
                trustedFileText = $"{trustedFileText}{fullDmbPath}{Environment.NewLine}";
                var newTrustedFileBytes = Encoding.UTF8.GetBytes(trustedFileText);
                await ioManager.WriteAllBytes(trustedFilePath, newTrustedFileBytes, cancellationToken);
            }
        }
References Tgstation.Server.Host.Components.Byond.ByondManager.byondInstaller, Tgstation.Server.Host.Components.Byond.ByondManager.CfgDirectoryName, Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.IO.IIOManager.FileExists(), Tgstation.Server.Host.Components.Byond.ByondManager.ioManager, Tgstation.Server.Host.Utils.SemaphoreSlimContext.Lock(), Tgstation.Server.Host.Components.Byond.ByondManager.logger, Tgstation.Server.Host.Components.Byond.IByondInstaller.PathToUserByondFolder, Tgstation.Server.Host.IO.IIOManager.ReadAllBytes(), Tgstation.Server.Host.Components.Byond.ByondManager.TrustedDmbFileName, Tgstation.Server.Host.Components.Byond.ByondManager.UserFilesSemaphore, and Tgstation.Server.Host.IO.IIOManager.WriteAllBytes().
Referenced by Tgstation.Server.Host.Components.Byond.ByondManager.UseExecutables().
UseExecutables()
async Task< IByondExecutableLock > Tgstation.Server.Host.Components.Byond.ByondManager.UseExecutables (Version requiredVersion, string trustDmbFullPath, CancellationToken cancellationToken)
Lock the current installation's location and return a IByondExecutableLock.
Parameters
requiredVersion The BYOND Version required.
trustDmbFullPath The optional full path to .dmb to trust while using the executables.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the requested IByondExecutableLock.
Implements Tgstation.Server.Host.Components.Byond.IByondManager.
Definition at line 179 of file ByondManager.cs.
        {
            logger.LogTrace(
                "Acquiring lock on BYOND version {version}...",
                requiredVersion?.ToString() ?? $"{ActiveVersion} (active)");
            var versionToUse = requiredVersion ?? ActiveVersion ?? throw new JobException(ErrorCode.ByondNoVersionsInstalled);
            var installLock = await AssertAndLockVersion(
                null,
                versionToUse,
                null,
                requiredVersion != null,
                true,
                cancellationToken);
            try
            {
                if (trustDmbFullPath != null)
                    await TrustDmbPath(trustDmbFullPath, cancellationToken);
                return installLock;
            }
            catch
            {
                installLock.Dispose();
                throw;
            }
        }
References Tgstation.Server.Host.Components.Byond.ByondManager.ActiveVersion, Tgstation.Server.Host.Components.Byond.ByondManager.AssertAndLockVersion(), Tgstation.Server.Host.Components.Byond.ByondManager.logger, and Tgstation.Server.Host.Components.Byond.ByondManager.TrustDmbPath().
Member Data Documentation
activeVersionChanged
TaskCompletionSource Tgstation.Server.Host.Components.Byond.ByondManager.activeVersionChanged private
TaskCompletionSource that notifes when the ActiveVersion changes.
Definition at line 99 of file ByondManager.cs.
Referenced by Tgstation.Server.Host.Components.Byond.ByondManager.ByondManager(), Tgstation.Server.Host.Components.Byond.ByondManager.ChangeVersion(), and Tgstation.Server.Host.Components.Byond.ByondManager.DeleteVersion().
ActiveVersionFileName
const string Tgstation.Server.Host.Components.Byond.ByondManager.ActiveVersionFileName = "ActiveVersion.txt" static private
The file in which we store the ActiveVersion.
Definition at line 46 of file ByondManager.cs.
Referenced by Tgstation.Server.Host.Components.Byond.ByondManager.ChangeVersion(), and Tgstation.Server.Host.Components.Byond.ByondManager.StartAsync().
BinPath
const string Tgstation.Server.Host.Components.Byond.ByondManager.BinPath = "byond/bin" static
The path to the BYOND bin folder.
Definition at line 26 of file ByondManager.cs.
Referenced by Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.AddDreamDaemonToFirewall(), Tgstation.Server.Host.Components.Byond.ByondManager.AddInstallationContainer(), and Tgstation.Server.Host.Components.Byond.PosixByondInstaller.InstallByond().
byondInstaller
readonly IByondInstaller Tgstation.Server.Host.Components.Byond.ByondManager.byondInstaller private
The IByondInstaller for the ByondManager.
Definition at line 74 of file ByondManager.cs.
Referenced by Tgstation.Server.Host.Components.Byond.ByondManager.AddInstallationContainer(), Tgstation.Server.Host.Components.Byond.ByondManager.ByondManager(), Tgstation.Server.Host.Components.Byond.ByondManager.InstallVersionFiles(), Tgstation.Server.Host.Components.Byond.ByondManager.StartAsync(), and Tgstation.Server.Host.Components.Byond.ByondManager.TrustDmbPath().
CfgDirectoryName
const string Tgstation.Server.Host.Components.Byond.ByondManager.CfgDirectoryName = "cfg" static private
The path to the cfg directory.
Definition at line 31 of file ByondManager.cs.
Referenced by Tgstation.Server.Host.Components.Byond.ByondManager.StartAsync(), and Tgstation.Server.Host.Components.Byond.ByondManager.TrustDmbPath().
changeDeleteSemaphore
readonly SemaphoreSlim Tgstation.Server.Host.Components.Byond.ByondManager.changeDeleteSemaphore private
The SemaphoreSlim for changing or deleting the active BYOND version.
Definition at line 94 of file ByondManager.cs.
Referenced by Tgstation.Server.Host.Components.Byond.ByondManager.ByondManager(), Tgstation.Server.Host.Components.Byond.ByondManager.ChangeVersion(), and Tgstation.Server.Host.Components.Byond.ByondManager.DeleteVersion().
eventConsumer
readonly IEventConsumer Tgstation.Server.Host.Components.Byond.ByondManager.eventConsumer private
The IEventConsumer for the ByondManager.
Definition at line 79 of file ByondManager.cs.
Referenced by Tgstation.Server.Host.Components.Byond.ByondManager.AssertAndLockVersion(), Tgstation.Server.Host.Components.Byond.ByondManager.ByondManager(), and Tgstation.Server.Host.Components.Byond.ByondManager.ChangeVersion().
installedVersions
readonly Dictionary<Version, ReferenceCountingContainer<ByondInstallation, ByondExecutableLock> > Tgstation.Server.Host.Components.Byond.ByondManager.installedVersions private
Map of byond Versions to Tasks that complete when they are installed.
Definition at line 89 of file ByondManager.cs.
Referenced by Tgstation.Server.Host.Components.Byond.ByondManager.AddInstallationContainer(), Tgstation.Server.Host.Components.Byond.ByondManager.AssertAndLockVersion(), Tgstation.Server.Host.Components.Byond.ByondManager.ByondManager(), Tgstation.Server.Host.Components.Byond.ByondManager.DeleteVersion(), and Tgstation.Server.Host.Components.Byond.ByondManager.StartAsync().
ioManager
readonly IIOManager Tgstation.Server.Host.Components.Byond.ByondManager.ioManager private
The IIOManager for the ByondManager.
Definition at line 69 of file ByondManager.cs.
Referenced by Tgstation.Server.Host.Components.Byond.ByondManager.AddInstallationContainer(), Tgstation.Server.Host.Components.Byond.ByondManager.ByondManager(), Tgstation.Server.Host.Components.Byond.ByondManager.ChangeVersion(), Tgstation.Server.Host.Components.Byond.ByondManager.DeleteVersion(), Tgstation.Server.Host.Components.Byond.ByondManager.InstallVersionFiles(), Tgstation.Server.Host.Components.Byond.ByondManager.StartAsync(), and Tgstation.Server.Host.Components.Byond.ByondManager.TrustDmbPath().
logger
readonly ILogger<ByondManager> Tgstation.Server.Host.Components.Byond.ByondManager.logger private
The ILogger for the ByondManager.
Definition at line 84 of file ByondManager.cs.
Referenced by Tgstation.Server.Host.Components.Byond.ByondManager.AssertAndLockVersion(), Tgstation.Server.Host.Components.Byond.ByondManager.ByondManager(), Tgstation.Server.Host.Components.Byond.ByondManager.ChangeVersion(), Tgstation.Server.Host.Components.Byond.ByondManager.DeleteVersion(), Tgstation.Server.Host.Components.Byond.ByondManager.InstallVersionFiles(), Tgstation.Server.Host.Components.Byond.ByondManager.StartAsync(), Tgstation.Server.Host.Components.Byond.ByondManager.TrustDmbPath(), and Tgstation.Server.Host.Components.Byond.ByondManager.UseExecutables().
TrustedDmbFileName
const string Tgstation.Server.Host.Components.Byond.ByondManager.TrustedDmbFileName = "trusted.txt" static private
The name of the list of trusted .dmb files in the user's BYOND cfg directory.
Definition at line 36 of file ByondManager.cs.
Referenced by Tgstation.Server.Host.Components.Byond.ByondManager.StartAsync(), and Tgstation.Server.Host.Components.Byond.ByondManager.TrustDmbPath().
UserFilesSemaphore
readonly SemaphoreSlim Tgstation.Server.Host.Components.Byond.ByondManager.UserFilesSemaphore = new (1) static private
SemaphoreSlim for writing to files in the user's BYOND directory.
Definition at line 64 of file ByondManager.cs.
Referenced by Tgstation.Server.Host.Components.Byond.ByondManager.StartAsync(), and Tgstation.Server.Host.Components.Byond.ByondManager.TrustDmbPath().
VersionFileName
const string Tgstation.Server.Host.Components.Byond.ByondManager.VersionFileName = "Version.txt" static private
The file in which we store the Version for installations.
Definition at line 41 of file ByondManager.cs.
Referenced by Tgstation.Server.Host.Components.Byond.ByondManager.DeleteVersion(), Tgstation.Server.Host.Components.Byond.ByondManager.InstallVersionFiles(), and Tgstation.Server.Host.Components.Byond.ByondManager.StartAsync().
Property Documentation
ActiveVersion
Version Tgstation.Server.Host.Components.Byond.ByondManager.ActiveVersion get private set
The currently active BYOND version.
Implements Tgstation.Server.Host.Components.Byond.IByondManager.
Definition at line 49 of file ByondManager.cs.
{ get; private set; }
Referenced by Tgstation.Server.Host.Components.Byond.ByondManager.ChangeVersion(), Tgstation.Server.Host.Components.Byond.ByondManager.DeleteVersion(), Tgstation.Server.Host.Components.Byond.ByondManager.StartAsync(), and Tgstation.Server.Host.Components.Byond.ByondManager.UseExecutables().
InstalledVersions
IReadOnlyList<Version> Tgstation.Server.Host.Components.Byond.ByondManager.InstalledVersions get
The installed BYOND versions.
Implements Tgstation.Server.Host.Components.Byond.IByondManager.
Definition at line 52 of file ByondManager.cs.
        {
            get
            {
                lock (installedVersions)
                    return installedVersions.Keys.ToList();
            }
        }
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Byond/ByondManager.cs