tgstation-server: Tgstation.Server.Tests.Instance.ChatTest Class Reference
Tgstation.Server.Tests.Instance.ChatTest Class Reference
Public Member Functions
ChatTest (IChatBotsClient chatClient, IInstanceManagerClient instanceClient, Api.Models.Instance metadata)
async Task RunPreWatchdog (CancellationToken cancellationToken)
async Task RunPostWatchdog (CancellationToken cancellationToken)
Private Member Functions
async Task RunIrc (CancellationToken cancellationToken)
async Task RunDiscord (CancellationToken cancellationToken)
async Task RunLimitTests (CancellationToken cancellationToken)
Private Attributes
readonly IChatBotsClient chatClient
readonly IInstanceManagerClient instanceClient
readonly Api.Models.Instance metadata
Detailed Description
Definition at line 13 of file ChatTest.cs.
Constructor & Destructor Documentation
ChatTest()
Tgstation.Server.Tests.Instance.ChatTest.ChatTest (IChatBotsClient chatClient, IInstanceManagerClient instanceClient, Api.Models.Instance metadata)
Definition at line 19 of file ChatTest.cs.
         {
             this.chatClient = chatClient ?? throw new ArgumentNullException(nameof(chatClient));
             this.instanceClient = instanceClient ?? throw new ArgumentNullException(nameof(instanceClient));
             this.metadata = metadata ?? throw new ArgumentNullException(nameof(metadata));
         }
References Tgstation.Server.Tests.Instance.ChatTest.chatClient, Tgstation.Server.Tests.Instance.ChatTest.instanceClient, and Tgstation.Server.Tests.Instance.ChatTest.metadata.
Member Function Documentation
RunDiscord()
async Task Tgstation.Server.Tests.Instance.ChatTest.RunDiscord (CancellationToken cancellationToken) private
Definition at line 92 of file ChatTest.cs.
         {
             var firstBot = new ChatBot
             {
                 ConnectionString = Environment.GetEnvironmentVariable("TGS4_TEST_DISCORD_TOKEN"),
                 Enabled = false,
                 Name = "r4407",
                 Provider = ChatProvider.Discord,
                 ReconnectionInterval = 1,
                 ChannelLimit = 1
             };
             var csb = new DiscordConnectionStringBuilder(firstBot.ConnectionString);
             Assert.IsTrue(csb.Valid, $"Invalid Discord connection string: {firstBot.ConnectionString}");
             firstBot = await chatClient.Create(firstBot, cancellationToken);
             Assert.AreEqual(csb.ToString(), firstBot.ConnectionString);
             Assert.AreNotEqual(0, firstBot.Id);
             var bots = await chatClient.List(cancellationToken);
             Assert.AreEqual(firstBot.Id, bots.First(x => x.Provider.Value == ChatProvider.Discord).Id);
             var retrievedBot = await chatClient.GetId(firstBot, cancellationToken);
             Assert.AreEqual(firstBot.Id, retrievedBot.Id);
             firstBot.Enabled = true;
             var updatedBot = await chatClient.Update(firstBot, cancellationToken);
             Assert.AreEqual(true, updatedBot.Enabled);
             var channelId = UInt64.Parse(Environment.GetEnvironmentVariable("TGS4_TEST_DISCORD_CHANNEL"));
             firstBot.Channels = new List<ChatChannel>
             {
                 new ChatChannel
                 {
                     IsAdminChannel = true,
                     IsUpdatesChannel = false,
                     IsWatchdogChannel = true,
                     Tag = "butt",
                     DiscordChannelId = channelId
                 }
             };
             updatedBot = await chatClient.Update(firstBot, cancellationToken);
             Assert.AreEqual(true, updatedBot.Enabled);
             Assert.IsNotNull(updatedBot.Channels);
             Assert.AreEqual(1, updatedBot.Channels.Count);
             Assert.AreEqual(true, updatedBot.Channels.First().IsAdminChannel);
             Assert.AreEqual(false, updatedBot.Channels.First().IsUpdatesChannel);
             Assert.AreEqual(true, updatedBot.Channels.First().IsWatchdogChannel);
             Assert.AreEqual("butt", updatedBot.Channels.First().Tag);
             Assert.AreEqual(channelId, updatedBot.Channels.First().DiscordChannelId);
             Assert.IsNull(updatedBot.Channels.First().IrcChannel);
         }
References Tgstation.Server.Tests.Instance.ChatTest.chatClient, Tgstation.Server.Client.Components.IChatBotsClient.Create(), Tgstation.Server.Client.Components.IChatBotsClient.GetId(), Tgstation.Server.Client.Components.IChatBotsClient.List(), and Tgstation.Server.Client.Components.IChatBotsClient.Update().
Referenced by Tgstation.Server.Tests.Instance.ChatTest.RunPreWatchdog().
RunIrc()
async Task Tgstation.Server.Tests.Instance.ChatTest.RunIrc (CancellationToken cancellationToken) private
Definition at line 34 of file ChatTest.cs.
         {
             var firstBot = new ChatBot
             {
                 ConnectionString = Environment.GetEnvironmentVariable("TGS4_TEST_IRC_CONNECTION_STRING"),
                 Enabled = false,
                 Name = "tgs4_integration_test",
                 Provider = ChatProvider.Irc,
                 ReconnectionInterval = 1,
                 ChannelLimit = 1
             };
             var csb = new IrcConnectionStringBuilder(firstBot.ConnectionString);
             Assert.IsTrue(csb.Valid, $"Invalid IRC connection string: {firstBot.ConnectionString}");
             firstBot = await chatClient.Create(firstBot, cancellationToken);
             Assert.AreEqual(csb.ToString(), firstBot.ConnectionString);
             Assert.AreNotEqual(0, firstBot.Id);
             var bots = await chatClient.List(cancellationToken);
             Assert.AreEqual(firstBot.Id, bots.First(x => x.Provider.Value == ChatProvider.Irc).Id);
             var retrievedBot = await chatClient.GetId(firstBot, cancellationToken);
             Assert.AreEqual(firstBot.Id, retrievedBot.Id);
             firstBot.Enabled = true;
             var updatedBot = await chatClient.Update(firstBot, cancellationToken);
             Assert.AreEqual(true, updatedBot.Enabled);
             var channelId = Environment.GetEnvironmentVariable("TGS4_TEST_IRC_CHANNEL");
             firstBot.Channels = new List<ChatChannel>
             {
                 new ChatChannel
                 {
                     IsAdminChannel = false,
                     IsUpdatesChannel = true,
                     IsWatchdogChannel = true,
                     Tag = "butt2",
                     IrcChannel = channelId
                 }
             };
             updatedBot = await chatClient.Update(firstBot, cancellationToken);
             Assert.AreEqual(true, updatedBot.Enabled);
             Assert.IsNotNull(updatedBot.Channels);
             Assert.AreEqual(1, updatedBot.Channels.Count);
             Assert.AreEqual(false, updatedBot.Channels.First().IsAdminChannel);
             Assert.AreEqual(true, updatedBot.Channels.First().IsUpdatesChannel);
             Assert.AreEqual(true, updatedBot.Channels.First().IsWatchdogChannel);
             Assert.AreEqual("butt2", updatedBot.Channels.First().Tag);
             Assert.AreEqual(channelId, updatedBot.Channels.First().IrcChannel);
             Assert.IsNull(updatedBot.Channels.First().DiscordChannelId);
         }
References Tgstation.Server.Tests.Instance.ChatTest.chatClient, Tgstation.Server.Client.Components.IChatBotsClient.Create(), Tgstation.Server.Client.Components.IChatBotsClient.GetId(), Tgstation.Server.Client.Components.IChatBotsClient.List(), and Tgstation.Server.Client.Components.IChatBotsClient.Update().
Referenced by Tgstation.Server.Tests.Instance.ChatTest.RunPreWatchdog().
RunLimitTests()
async Task Tgstation.Server.Tests.Instance.ChatTest.RunLimitTests (CancellationToken cancellationToken) private
Definition at line 162 of file ChatTest.cs.
         {
             await ApiAssert.ThrowsException<ConflictException>(() => chatClient.Create(new ChatBot
             {
                 Name = "asdf",
                 ConnectionString = "asdf",
                 Provider = ChatProvider.Irc
             }, cancellationToken), ErrorCode.ChatBotMax);
             var bots = await chatClient.List(cancellationToken);
             var discordBot = bots.First(bot => bot.Provider.Value == ChatProvider.Discord);
             // We limited chat bots and channels to 1 and 2 respectively, try violating them
             discordBot.Channels.Add(
                 new ChatChannel
                 {
                     IsAdminChannel = true,
                     IsUpdatesChannel = false,
                     IsWatchdogChannel = true,
                     Tag = "butt",
                     DiscordChannelId = discordBot.Channels.First().DiscordChannelId
                 });
             await ApiAssert.ThrowsException<ApiConflictException>(() => chatClient.Update(discordBot, cancellationToken), ErrorCode.ChatBotMaxChannels);
             var oldChannels = discordBot.Channels;
             discordBot.Channels = null;
             discordBot.ChannelLimit = 0;
             await ApiAssert.ThrowsException<ConflictException>(() => chatClient.Update(discordBot, cancellationToken), ErrorCode.ChatBotMaxChannels);
             discordBot.Channels = oldChannels;
             discordBot.ChannelLimit = null;
             await ApiAssert.ThrowsException<ConflictException>(() => chatClient.Update(discordBot, cancellationToken), ErrorCode.ChatBotMaxChannels);
             var instance = metadata.CloneMetadata();
             instance.ChatBotLimit = 0;
             await ApiAssert.ThrowsException<ConflictException>(() => instanceClient.Update(instance, cancellationToken), ErrorCode.ChatBotMax);
         }
References Tgstation.Server.Tests.Instance.ChatTest.chatClient, and Tgstation.Server.Client.Components.IChatBotsClient.Create().
Referenced by Tgstation.Server.Tests.Instance.ChatTest.RunPreWatchdog().
RunPostWatchdog()
async Task Tgstation.Server.Tests.Instance.ChatTest.RunPostWatchdog (CancellationToken cancellationToken)
Definition at line 150 of file ChatTest.cs.
         {
             var activeBots = await chatClient.List(cancellationToken);
             Assert.AreEqual(2, activeBots.Count);
             await Task.WhenAll(activeBots.Select(bot => chatClient.Delete(bot, cancellationToken)));
             var nowBots = await chatClient.List(cancellationToken);
             Assert.AreEqual(0, nowBots.Count);
         }
References Tgstation.Server.Tests.Instance.ChatTest.chatClient, Tgstation.Server.Client.Components.IChatBotsClient.Delete(), and Tgstation.Server.Client.Components.IChatBotsClient.List().
RunPreWatchdog()
async Task Tgstation.Server.Tests.Instance.ChatTest.RunPreWatchdog (CancellationToken cancellationToken)
Definition at line 26 of file ChatTest.cs.
         {
             var ircTask = RunIrc(cancellationToken);
             await RunDiscord(cancellationToken);
             await ircTask;
             await RunLimitTests(cancellationToken);
         }
References Tgstation.Server.Tests.Instance.ChatTest.RunDiscord(), Tgstation.Server.Tests.Instance.ChatTest.RunIrc(), and Tgstation.Server.Tests.Instance.ChatTest.RunLimitTests().
Member Data Documentation
chatClient
readonly IChatBotsClient Tgstation.Server.Tests.Instance.ChatTest.chatClient private
Definition at line 15 of file ChatTest.cs.
Referenced by Tgstation.Server.Tests.Instance.ChatTest.ChatTest(), Tgstation.Server.Tests.Instance.ChatTest.RunDiscord(), Tgstation.Server.Tests.Instance.ChatTest.RunIrc(), Tgstation.Server.Tests.Instance.ChatTest.RunLimitTests(), and Tgstation.Server.Tests.Instance.ChatTest.RunPostWatchdog().
instanceClient
readonly IInstanceManagerClient Tgstation.Server.Tests.Instance.ChatTest.instanceClient private
Definition at line 16 of file ChatTest.cs.
Referenced by Tgstation.Server.Tests.Instance.ChatTest.ChatTest().
metadata
readonly Api.Models.Instance Tgstation.Server.Tests.Instance.ChatTest.metadata private
Definition at line 17 of file ChatTest.cs.
Referenced by Tgstation.Server.Tests.Instance.ChatTest.ChatTest().
The documentation for this class was generated from the following file:
tests/Tgstation.Server.Tests/Instance/ChatTest.cs