tgstation-server: Tgstation.Server.Host.GraphQL.Metadata.RightsTypeInterceptor Class Reference
Tgstation.Server.Host.GraphQL.Metadata.RightsTypeInterceptor Class Reference sealed
Fixes the names used for the default flags types in API rights.
Public Member Functions
RightsTypeInterceptor ()
Initializes a new instance of the RightsTypeInterceptor class.
override void OnAfterRegisterDependencies (ITypeDiscoveryContext discoveryContext, DefinitionBase definition)
Static Private Member Functions
static void FixFields (IBindableList< InputFieldDefinition > fields)
Fix the "is" prefix on a given set of fields .
static void FixFormatter (IInputValueFormatter inputValueFormatter)
Fix the inputValueFormatter for a tweaked field.
Private Attributes
readonly HashSet< string > inputNames
Names of rights GraphQL input types.
Static Private Attributes
const string IsPrefix = "is"
Prefix normally used by hot chocolate for flag enums.
const string NoneFieldName = $"{IsPrefix}None"
Name given to default None fields.
Detailed Description
Fixes the names used for the default flags types in API rights.
Definition at line 18 of file RightsTypeInterceptor.cs.
Constructor & Destructor Documentation
RightsTypeInterceptor()
Tgstation.Server.Host.GraphQL.Metadata.RightsTypeInterceptor.RightsTypeInterceptor ()
Initializes a new instance of the RightsTypeInterceptor class.
Definition at line 38 of file RightsTypeInterceptor.cs.
        {
            var rightTypes = Enum.GetValues<RightsType>();
            inputNames = new HashSet<string>(rightTypes.Length);
            foreach (var rightType in rightTypes)
            {
                var rightName = rightType.ToString();
                inputNames.Add($"{rightName}RightsFlagsInput");
            }
        }
References Tgstation.Server.Host.GraphQL.Metadata.RightsTypeInterceptor.inputNames, and Tgstation.Server.Api.Rights.List.
Member Function Documentation
FixFields()
static void Tgstation.Server.Host.GraphQL.Metadata.RightsTypeInterceptor.FixFields (IBindableList< InputFieldDefinition > fields) static private
Fix the "is" prefix on a given set of fields .
Parameters
fields The IBindableList<T> of InputFieldDefinitions to operate on.
Definition at line 54 of file RightsTypeInterceptor.cs.
        {
            InputFieldDefinition? noneField = null;
            foreach (var field in fields)
            {
                var fieldName = field.Name;
                if (fieldName == NoneFieldName)
                {
                    noneField = field;
                    continue;
                }
                if (!fieldName.StartsWith(IsPrefix))
                    throw new InvalidOperationException("Expected flags enum type field to start with \"is\"!");
                field.Name = $"can{fieldName[IsPrefix.Length..]}";
                field.Type = TypeReference.Parse($"{ScalarNames.Boolean}!");
            }
            if (noneField == null)
                throw new InvalidOperationException($"Expected flags enum type field to contain \"{NoneFieldName}\"!");
            fields.Remove(noneField);
        }
References Tgstation.Server.Host.GraphQL.Metadata.RightsTypeInterceptor.IsPrefix, Tgstation.Server.Api.Rights.List, and Tgstation.Server.Host.GraphQL.Metadata.RightsTypeInterceptor.NoneFieldName.
Referenced by Tgstation.Server.Host.GraphQL.Metadata.RightsTypeInterceptor.OnAfterRegisterDependencies().
FixFormatter()
static void Tgstation.Server.Host.GraphQL.Metadata.RightsTypeInterceptor.FixFormatter (IInputValueFormatter inputValueFormatter) static private
Fix the inputValueFormatter for a tweaked field.
Parameters
inputValueFormatter The IInputValueFormatter to fix.
Definition at line 84 of file RightsTypeInterceptor.cs.
        {
            // now we're hacking privates, but there's a dictionary with bad keys here that needs adjusting
            var dictionary = (Dictionary<string, object>)(inputValueFormatter
                .GetType()
                .GetField("_flags", BindingFlags.Instance | BindingFlags.NonPublic)
                ?.GetValue(inputValueFormatter)
                ?? throw new InvalidOperationException("Could not locate private enum mapping dictionary field!"));
            foreach (var key in dictionary.Keys.ToList())
            {
                if (key == NoneFieldName)
                {
                    dictionary.Remove(key);
                    continue;
                }
                var value = dictionary[key];
                var newKey = $"can{key.Substring(IsPrefix.Length)}";
                dictionary.Remove(key);
                dictionary.Add(newKey, value);
            }
        }
References Tgstation.Server.Api.Rights.List, and Tgstation.Server.Host.GraphQL.Metadata.RightsTypeInterceptor.NoneFieldName.
Referenced by Tgstation.Server.Host.GraphQL.Metadata.RightsTypeInterceptor.OnAfterRegisterDependencies().
OnAfterRegisterDependencies()
override void Tgstation.Server.Host.GraphQL.Metadata.RightsTypeInterceptor.OnAfterRegisterDependencies (ITypeDiscoveryContext discoveryContext, DefinitionBase definition)
Definition at line 109 of file RightsTypeInterceptor.cs.
        {
            ArgumentNullException.ThrowIfNull(definition);
            if (definition is InputObjectTypeDefinition inputTypeDef)
            {
                const string PermissionSetInputName = $"{nameof(PermissionSet)}Input";
                const string InstancePermissionSetInputName = $"{nameof(InstancePermissionSet)}Input";
                var name = inputTypeDef.Name;
                if (inputNames.Contains(name))
                    FixFields(inputTypeDef.Fields);
                else if (name == PermissionSetInputName || name == InstancePermissionSetInputName)
                    foreach (var field in inputTypeDef.Fields)
                        FixFormatter(field.Formatters.Single());
            }
        }
References Tgstation.Server.Host.GraphQL.Metadata.RightsTypeInterceptor.FixFields(), Tgstation.Server.Host.GraphQL.Metadata.RightsTypeInterceptor.FixFormatter(), Tgstation.Server.Host.GraphQL.Metadata.RightsTypeInterceptor.inputNames, and Tgstation.Server.Api.Rights.List.
Member Data Documentation
inputNames
readonly HashSet<string> Tgstation.Server.Host.GraphQL.Metadata.RightsTypeInterceptor.inputNames private
Names of rights GraphQL input types.
Definition at line 33 of file RightsTypeInterceptor.cs.
Referenced by Tgstation.Server.Host.GraphQL.Metadata.RightsTypeInterceptor.OnAfterRegisterDependencies(), and Tgstation.Server.Host.GraphQL.Metadata.RightsTypeInterceptor.RightsTypeInterceptor().
IsPrefix
const string Tgstation.Server.Host.GraphQL.Metadata.RightsTypeInterceptor.IsPrefix = "is" static private
Prefix normally used by hot chocolate for flag enums.
Definition at line 23 of file RightsTypeInterceptor.cs.
Referenced by Tgstation.Server.Host.GraphQL.Metadata.RightsTypeInterceptor.FixFields().
NoneFieldName
const string Tgstation.Server.Host.GraphQL.Metadata.RightsTypeInterceptor.NoneFieldName = $"{IsPrefix}None" static private
Name given to default None fields.
Definition at line 28 of file RightsTypeInterceptor.cs.
Referenced by Tgstation.Server.Host.GraphQL.Metadata.RightsTypeInterceptor.FixFields(), and Tgstation.Server.Host.GraphQL.Metadata.RightsTypeInterceptor.FixFormatter().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/GraphQL/Metadata/RightsTypeInterceptor.cs