tgstation-server: Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog Class Reference
Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog Class Reference
A IWatchdog that tries to manage 2 servers at once for maximum uptime.
Public Member Functions
ExperimentalWatchdog (IChatManager chat, ISessionControllerFactory sessionControllerFactory, IDmbFactory dmbFactory, IReattachInfoHandler reattachInfoHandler, IDatabaseContextFactory databaseContextFactory, IJobManager jobManager, IServerControl serverControl, IAsyncDelayer asyncDelayer, ILogger< ExperimentalWatchdog > logger, DreamDaemonLaunchParameters initialLaunchParameters, Api.Models.Instance instance, bool autoStart)
Initializes a new instance of the ExperimentalWatchdog .
override Task InstanceRenamed (string newInstanceName, CancellationToken cancellationToken)
Called when the owning Instance is renamed.
Public Member Functions inherited from Tgstation.Server.Host.Components.Watchdog.WatchdogBase
void Dispose ()
async Task ChangeSettings (DreamDaemonLaunchParameters launchParameters, CancellationToken cancellationToken)
Changes the ActiveLaunchParameters. If currently Running triggers a graceful restart
async Task HandleEvent (EventType eventType, IEnumerable< string > parameters, CancellationToken cancellationToken)
Handle a given eventType
async Task< string > HandleChatCommand (string commandName, string arguments, ChatUser sender, CancellationToken cancellationToken)
Handle a chat command
async Task Launch (CancellationToken cancellationToken)
Start the IWatchdog
virtual async Task ResetRebootState (CancellationToken cancellationToken)
Cancels pending graceful actions
async Task Restart (bool graceful, CancellationToken cancellationToken)
Restarts the watchdog
async Task StartAsync (CancellationToken cancellationToken)
async Task StopAsync (CancellationToken cancellationToken)
async Task Terminate (bool graceful, CancellationToken cancellationToken)
Stops the watchdog
async Task HandleRestart (Version updateVersion, CancellationToken cancellationToken)
Handle a restart of the server
Public Attributes
override bool AlphaIsActive => alphaIsActive
override Models.CompileJob ActiveCompileJob => (AlphaIsActive ? alphaServer : bravoServer)?.Dmb.CompileJob
override RebootState RebootState => Running ? (AlphaIsActive ? alphaServer?.RebootState : bravoServer?.RebootState) : null
Protected Member Functions
override async Task HandleMonitorWakeup (MonitorActivationReason activationReason, MonitorState monitorState, CancellationToken cancellationToken)
Handles the actions to take when the monitor has to "wake up"
override void DisposeAndNullControllersImpl ()
Call IDisposable.Dispose and null the fields for all ISessionControllers and set Running to .
override IReadOnlyDictionary< MonitorActivationReason, Task > GetMonitoredServerTasks (MonitorState monitorState)
Gets the tasks for the following MonitorActivationReasons: MonitorActivationReason.ActiveServerCrashed, MonitorActivationReason.ActiveServerRebooted, MonitorActivationReason.InactiveServerCrashed, MonitorActivationReason.InactiveServerRebooted, MonitorActivationReason.InactiveServerStartupComplete.
override async Task InitControllers (Action callBeforeRecurse, Task chatTask, DualReattachInformation reattachInfo, CancellationToken cancellationToken)
Starts all ISessionControllers.
override ISessionController GetActiveController ()
Get the active ISessionController.
override DualReattachInformation CreateReattachInformation ()
Create the DualReattachInformation for the ISessionControllers.
Protected Member Functions inherited from Tgstation.Server.Host.Components.Watchdog.WatchdogBase
WatchdogBase (IChatManager chat, ISessionControllerFactory sessionControllerFactory, IDmbFactory dmbFactory, IReattachInfoHandler reattachInfoHandler, IDatabaseContextFactory databaseContextFactory, IJobManager jobManager, IServerControl serverControl, IAsyncDelayer asyncDelayer, ILogger logger, DreamDaemonLaunchParameters initialLaunchParameters, Api.Models.Instance instance, bool autoStart)
Initializes a new instance of the WatchdogBase .
async Task LaunchNoLock (bool startMonitor, bool announce, DualReattachInformation reattachInfo, CancellationToken cancellationToken)
Launches the watchdog.
async Task< bool > StopMonitor ()
Stops MonitorLifetimes(CancellationToken). Doesn't kill the servers
async Task CheckLaunchResult (ISessionController controller, string serverName, CancellationToken cancellationToken)
Check the LaunchResult of a given controller for errors and throw a JobException if any are detected.
void DisposeAndNullControllers ()
Wrapper for DisposeAndNullControllersImpl under a locked context.
Private Attributes
const int AlphaBravoStartupSeperationInterval = 10
The time in seconds to wait from starting alphaServer to start bravoServer. Does not take responsiveness into account
ISessionController alphaServer
Server designation alpha
ISessionController bravoServer
Server designation bravo
bool alphaIsActive
Backing field for AlphaIsActive.
Additional Inherited Members
Properties inherited from Tgstation.Server.Host.Components.Watchdog.WatchdogBase
bool Running [get, set]
abstract bool AlphaIsActive [get]
abstract Models.CompileJob ActiveCompileJob [get]
DreamDaemonLaunchParameters ActiveLaunchParameters [get, protected set]
DreamDaemonLaunchParameters LastLaunchParameters [get, protected set]
abstract RebootState RebootState [get]
TaskCompletionSource< object > ActiveParametersUpdated [get, set]
TaskCompletionSource<TResult> that completes when ActiveLaunchParameters are changed and we are Running.
SemaphoreSlim Semaphore [get]
The SemaphoreSlim for the WatchdogBase.
ILogger Logger [get]
The ILogger for the WatchdogBase.
IChatManager Chat [get]
The IChatManager for the WatchdogBase
ISessionControllerFactory SessionControllerFactory [get]
The ISessionControllerFactory for the WatchdogBase
IDmbFactory DmbFactory [get]
The IDmbFactory for the WatchdogBase
IAsyncDelayer AsyncDelayer [get]
The IAsyncDelayer for the WatchdogBase.
Properties inherited from Tgstation.Server.Host.Components.Watchdog.IWatchdog
bool Running [get]
If the watchdog is running
bool AlphaIsActive [get]
If the alpha server is the active server
Models.CompileJob ActiveCompileJob [get]
The CompileJob currently running on the server
DreamDaemonLaunchParameters ActiveLaunchParameters [get]
The DreamDaemonLaunchParameters the active server is using
DreamDaemonLaunchParameters LastLaunchParameters [get]
The DreamDaemonLaunchParameters to be applied
RebootState RebootState [get]
The Session.RebootState of the active server
Detailed Description
A IWatchdog that tries to manage 2 servers at once for maximum uptime.
Definition at line 21 of file ExperimentalWatchdog.cs.
Constructor & Destructor Documentation
Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.ExperimentalWatchdog (IChatManager chat, ISessionControllerFactory sessionControllerFactory, IDmbFactory dmbFactory, IReattachInfoHandler reattachInfoHandler, IDatabaseContextFactory databaseContextFactory, IJobManager jobManager, IServerControl serverControl, IAsyncDelayer asyncDelayer, ILogger< ExperimentalWatchdog > logger, DreamDaemonLaunchParameters initialLaunchParameters, Api.Models.Instance instance, bool autoStart)
Initializes a new instance of the ExperimentalWatchdog .
Parameters
chat The IChatManager for the WatchdogBase.
sessionControllerFactory The ISessionControllerFactory for the WatchdogBase.
dmbFactory The IDmbFactory for the WatchdogBase.
reattachInfoHandler The IReattachInfoHandler for the WatchdogBase.
databaseContextFactory The IDatabaseContextFactory for the WatchdogBase.
jobManager The IJobManager for the WatchdogBase.
serverControl The IServerControl for the WatchdogBase.
asyncDelayer The IAsyncDelayer for the WatchdogBase.
logger The ILogger for the WatchdogBase.
initialLaunchParameters The DreamDaemonLaunchParameters for the WatchdogBase.
instance The Api.Models.Instance for the WatchdogBase.
autoStart The autostart value for the WatchdogBase.
Definition at line 67 of file ExperimentalWatchdog.cs.
             : base(
                  chat,
                  sessionControllerFactory,
                  dmbFactory,
                  reattachInfoHandler,
                  databaseContextFactory,
                  jobManager,
                  serverControl,
                  asyncDelayer,
                  logger,
                  initialLaunchParameters,
                  instance,
                  autoStart)
         {
             alphaIsActive = true;
         }
Member Function Documentation
override DualReattachInformation Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.CreateReattachInformation () protected virtual
Create the DualReattachInformation for the ISessionControllers.
Implements Tgstation.Server.Host.Components.Watchdog.WatchdogBase.
override void Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.DisposeAndNullControllersImpl () protected virtual
Call IDisposable.Dispose and null the fields for all ISessionControllers and set Running to .
Implements Tgstation.Server.Host.Components.Watchdog.WatchdogBase.
Definition at line 396 of file ExperimentalWatchdog.cs.
         {
             alphaServer?.Dispose();
             alphaServer = null;
             bravoServer?.Dispose();
             bravoServer = null;
             Running = false;
         }
override ISessionController Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.GetActiveController () protected virtual
Get the active ISessionController.
Implements Tgstation.Server.Host.Components.Watchdog.WatchdogBase.
override IReadOnlyDictionary<MonitorActivationReason, Task> Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.GetMonitoredServerTasks (MonitorState monitorState) protected virtual
Gets the tasks for the following MonitorActivationReasons: MonitorActivationReason.ActiveServerCrashed, MonitorActivationReason.ActiveServerRebooted, MonitorActivationReason.InactiveServerCrashed, MonitorActivationReason.InactiveServerRebooted, MonitorActivationReason.InactiveServerStartupComplete.
Implements Tgstation.Server.Host.Components.Watchdog.WatchdogBase.
Definition at line 406 of file ExperimentalWatchdog.cs.
References Tgstation.Server.Host.Components.Watchdog.MonitorState.ActiveServer, Tgstation.Server.Host.Components.Session.ISessionController.ClosePortOnReboot, Tgstation.Server.Host.Components.Deployment.IDmbProvider.CompileJob, Tgstation.Server.Host.Components.Session.ISessionController.Dmb, Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Host.Components.Watchdog.MonitorState.InactiveServer, Tgstation.Server.Host.System.IProcessBase.Lifetime, Tgstation.Server.Host.Components.Session.ISessionController.OnPrime, Tgstation.Server.Host.Components.Session.ISessionController.OnReboot, and Tgstation.Server.Host.Components.Watchdog.MonitorState.RebootingInactiveServer.
         {
             if (AlphaIsActive)
                 Logger.LogDebug("Alpha is the active server");
             else
                 Logger.LogDebug("Bravo is the active server");
             if (monitorState.RebootingInactiveServer)
                 Logger.LogDebug("Inactive server is rebooting");
             // update the monitor state with the inactive/active servers
             monitorState.ActiveServer = AlphaIsActive ? alphaServer : bravoServer;
             monitorState.InactiveServer = AlphaIsActive ? bravoServer : alphaServer;
             if (monitorState.ActiveServer.ClosePortOnReboot)
                 Logger.LogDebug("Active server will close port on reboot");
             if (monitorState.InactiveServer.ClosePortOnReboot)
                 Logger.LogDebug("Inactive server will close port on reboot");
             Logger.LogDebug("Active server Compile Job ID: {0}", monitorState.ActiveServer.Dmb.CompileJob.Id);
             Logger.LogDebug("Inactive server Compile Job ID: {0}", monitorState.InactiveServer.Dmb.CompileJob.Id);
             return new Dictionary<MonitorActivationReason, Task>
             {
                 { MonitorActivationReason.ActiveServerCrashed, monitorState.ActiveServer.Lifetime },
                 { MonitorActivationReason.ActiveServerRebooted, monitorState.ActiveServer.OnReboot },
                 { MonitorActivationReason.InactiveServerCrashed, monitorState.InactiveServer.Lifetime },
                 { MonitorActivationReason.InactiveServerRebooted, monitorState.InactiveServer.OnReboot },
                 { MonitorActivationReason.InactiveServerStartupComplete, monitorState.InactiveServer.OnPrime }
             };
         }
override async Task Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.HandleMonitorWakeup (MonitorActivationReason activationReason, MonitorState monitorState, CancellationToken cancellationToken) protected virtual
Handles the actions to take when the monitor has to "wake up"
Implements Tgstation.Server.Host.Components.Watchdog.WatchdogBase.
Definition at line 98 of file ExperimentalWatchdog.cs.
References Tgstation.Server.Host.Components.Watchdog.MonitorState.ActiveServer, Tgstation.Server.Host.Components.Session.ISessionController.ClosePortOnReboot, Tgstation.Server.Host.Components.Deployment.IDmbProvider.CompileJob, Tgstation.Server.Host.Components.Session.ISessionController.Dmb, Tgstation.Server.Host.Components.Session.ISessionController.EnableCustomChatCommands(), Tgstation.Server.Host.Components.Deployment.DmbFactory.FromCompileJob(), Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Host.Components.Watchdog.MonitorState.InactiveServer, Tgstation.Server.Host.Components.Watchdog.MonitorState.InactiveServerCritFail, Tgstation.Server.Host.Components.Session.ISessionController.IsPrimary, Tgstation.Server.Host.Components.Session.SessionControllerFactory.LaunchNew(), Tgstation.Server.Host.Components.Deployment.DmbFactory.LockNextDmb(), Tgstation.Server.Host.Components.Watchdog.MonitorState.NextAction, Tgstation.Server.Host.Components.Watchdog.MonitorState.RebootingInactiveServer, Tgstation.Server.Host.Components.Session.ISessionController.RebootState, Tgstation.Server.Host.Components.Session.ISessionController.ResetRebootState(), Tgstation.Server.Host.System.IProcessBase.SetHighPriority(), Tgstation.Server.Host.Components.Session.ISessionController.SetPort(), and Tgstation.Server.Host.Components.Session.ISessionController.TerminationWasRequested.
         {
             Logger.LogDebug("Monitor activation. Reason: {0}", activationReason);
             // this is where the bulk of the watchdog handling code lives and is fraught with lambdas, sorry not sorry
             // I'll do my best to walk you through it
             // returns true if the inactive server can't be used immediately
             // also sets monitor to restart if the above holds
             bool FullRestartDeadInactive()
             {
                 if (monitorState.RebootingInactiveServer || monitorState.InactiveServerCritFail)
                 {
                     Logger.LogInformation("Inactive server is {0}! Restarting monitor...", monitorState.InactiveServerCritFail ? "critically failed" : "still rebooting");
                     monitorState.NextAction = MonitorAction.Restart; // will dispose server
                     return true;
                 }
                 return false;
             }
             // trys to set inactive server's port to the public game port
             // doesn't handle closing active server's port
             // returns true on success and swaps inactiveserver and activeserver also sets LastLaunchParameters to ActiveLaunchParameters
             // on failure, sets monitor to restart
             async Task<bool> MakeInactiveActive()
             {
                 Logger.LogDebug("Setting inactive server to port {0}...", ActiveLaunchParameters.PrimaryPort.Value);
                 var result = await monitorState.InactiveServer.SetPort(ActiveLaunchParameters.PrimaryPort.Value, cancellationToken).ConfigureAwait(false);
                 if (!result)
                 {
                     Logger.LogWarning("Failed to activate inactive server! Restarting monitor...");
                     monitorState.NextAction = MonitorAction.Restart; // will dispose server
                     return false;
                 }
                 // inactive server should always be using active launch parameters
                 LastLaunchParameters = ActiveLaunchParameters;
                 var tmp = monitorState.ActiveServer;
                 monitorState.ActiveServer = monitorState.InactiveServer;
                 monitorState.InactiveServer = tmp;
                 alphaIsActive = !AlphaIsActive;
                 monitorState.ActiveServer.EnableCustomChatCommands();
                 return true;
             }
             // Kills and tries to launch inactive server with the latest dmb
             // falls back to current dmb on failure
             // Sets critfail on inactive server failing that
             // returns false if the backup dmb was used successfully, true otherwise
             async Task UpdateAndRestartInactiveServer(bool breakAfter)
             {
                 ActiveParametersUpdated = new TaskCompletionSource<object>();
                 monitorState.InactiveServer.Dispose(); // kill or recycle it
                 var desiredNextAction = breakAfter ? MonitorAction.Break : MonitorAction.Continue;
                 monitorState.NextAction = desiredNextAction;
                 Logger.LogInformation("Rebooting inactive server...");
                 var newDmb = DmbFactory.LockNextDmb(1);
                 try
                 {
                     monitorState.InactiveServer = await SessionControllerFactory.LaunchNew(
                         newDmb,
                         null,
                         ActiveLaunchParameters,
                         false,
                         !monitorState.ActiveServer.IsPrimary,
                         false,
                         cancellationToken)
                         .ConfigureAwait(false);
                     monitorState.InactiveServer.SetHighPriority();
                 }
                 catch (OperationCanceledException)
                 {
                     throw;
                 }
                 catch (Exception e)
                 {
                     Logger.LogError("Error occurred while recreating server! Attempting backup strategy of running DMB of running server! Exception: {0}", e.ToString());
                     // ahh jeez, what do we do here?
                     // this is our fault, so it should never happen but
                     // idk maybe a database error while handling the newest dmb?
                     // either way try to start it using the active server's dmb as a backup
                     try
                     {
                         var dmbBackup = await DmbFactory.FromCompileJob(monitorState.ActiveServer.Dmb.CompileJob, cancellationToken).ConfigureAwait(false);
                         if (dmbBackup == null) // NANI!?
                             throw new InvalidOperationException("Watchdog double crit-fail!"); // just give up, if THAT compile job is failing then the ActiveServer is gonna crash soon too or already has
                         monitorState.InactiveServer = await SessionControllerFactory.LaunchNew(
                             dmbBackup,
                             null,
                             ActiveLaunchParameters,
                             false,
                             !monitorState.ActiveServer.IsPrimary,
                             false,
                             cancellationToken)
                             .ConfigureAwait(false);
                         monitorState.InactiveServer.SetHighPriority();
                         await Chat.SendWatchdogMessage(
                             "Staging newest DMB on inactive server failed: {0} Falling back to previous dmb...",
                             false,
                             cancellationToken).ConfigureAwait(false);
                     }
                     catch (OperationCanceledException)
                     {
                         throw;
                     }
                     catch (Exception e2)
                     {
                         // fuuuuucckkk
                         Logger.LogError("Backup strategy failed! Monitor will restart when active server reboots! Exception: {0}", e2.ToString());
                         monitorState.InactiveServerCritFail = true;
                         await Chat.SendWatchdogMessage(
                             "Attempted reboot of inactive server failed. Watchdog will reset when active server fails or exits",
                             false,
                             cancellationToken).ConfigureAwait(false);
                         return;
                     }
                 }
                 Logger.LogInformation("Successfully relaunched inactive server!");
                 monitorState.RebootingInactiveServer = true;
             }
             static string ExitWord(ISessionController controller) => controller.TerminationWasRequested ? "exited" : "crashed";
             // reason handling
             switch (activationReason)
             {
                 case MonitorActivationReason.ActiveServerCrashed:
                     if (monitorState.ActiveServer.RebootState == Session.RebootState.Shutdown)
                     {
                         // the time for graceful shutdown is now
                         await Chat.SendWatchdogMessage(
                             String.Format(
                                 CultureInfo.InvariantCulture,
                                 "Active server {0}! Shutting down due to graceful termination request...",
                                 ExitWord(monitorState.ActiveServer)),
                             false,
                             cancellationToken).ConfigureAwait(false);
                         monitorState.NextAction = MonitorAction.Exit;
                         break;
                     }
                     if (FullRestartDeadInactive())
                     {
                         // tell chat about it and go ahead
                         await Chat.SendWatchdogMessage(
                             String.Format(
                                 CultureInfo.InvariantCulture,
                                 "Active server {0}! Inactive server unable to online!",
                                 ExitWord(monitorState.ActiveServer)),
                             false,
                             cancellationToken).ConfigureAwait(false);
                         // we've already been set to restart
                         break;
                     }
                     // tell chat about it
                     await Chat.SendWatchdogMessage(
                         String.Format(
                             CultureInfo.InvariantCulture,
                             "Active server {0}! Onlining inactive server...",
                             ExitWord(monitorState.ActiveServer)),
                         false,
                         cancellationToken)
                         .ConfigureAwait(false);
                     // try to activate the inactive server
                     if (!await MakeInactiveActive().ConfigureAwait(false))
                         break; // failing that, we've already been set to restart
                     // bring up another inactive server
                     await UpdateAndRestartInactiveServer(true).ConfigureAwait(false);
                     break;
                 case MonitorActivationReason.InactiveServerCrashed:
                     // just announce and try to bring it back
                     await Chat.SendWatchdogMessage(
                         String.Format(
                             CultureInfo.InvariantCulture,
                             "Inactive server {0}! Rebooting...",
                             ExitWord(monitorState.InactiveServer)),
                         false,
                         cancellationToken)
                         .ConfigureAwait(false);
                     await UpdateAndRestartInactiveServer(false).ConfigureAwait(false);
                     break;
                 case MonitorActivationReason.ActiveServerRebooted:
                     // ideal goal: active server just closed its port
                     // tell inactive server to open it's port and that's now the active server
                     var rebootState = monitorState.ActiveServer.RebootState;
                     monitorState.ActiveServer.ResetRebootState(); // the DMAPI has already done this internally
                     if (FullRestartDeadInactive() && rebootState != Session.RebootState.Shutdown)
                         break; // full restart if the inactive server is being fucky
                     // what matters here is the RebootState
                     var restartOnceSwapped = false;
                     switch (rebootState)
                     {
                         case Session.RebootState.Normal:
                             // life as normal
                             break;
                         case Session.RebootState.Restart:
                             // reboot the current active server once the inactive one activates
                             restartOnceSwapped = true;
                             break;
                         case Session.RebootState.Shutdown:
                             // graceful shutdown time
                             await Chat.SendWatchdogMessage(
                                 "Active server rebooted! Shutting down due to graceful termination request...",
                                 false,
                                 cancellationToken)
                                 .ConfigureAwait(false);
                             monitorState.NextAction = MonitorAction.Exit;
                             return;
                         default:
                             throw new InvalidOperationException($"Invalid reboot state: {rebootState}");
                     }
                     // are both servers now running the same CompileJob?
                     var sameCompileJob = monitorState.InactiveServer.Dmb.CompileJob.Id == monitorState.ActiveServer.Dmb.CompileJob.Id;
                     if (!sameCompileJob || ActiveLaunchParameters != LastLaunchParameters)
                         restartOnceSwapped = true; // need a new launch to update either settings or compile job
                     if (restartOnceSwapped)
                         /*
                          * we need to manually restart active server
                          * just kill it here, easier that way
                          */
                         monitorState.ActiveServer.Dispose();
                     var activeServerStillHasPortOpen = !restartOnceSwapped && !monitorState.ActiveServer.ClosePortOnReboot;
                     if (activeServerStillHasPortOpen)
                         /* we didn't want active server to swap for some reason and it still has it's port open
                          * just continue as normal
                          */
                         break;
                     if (!await MakeInactiveActive().ConfigureAwait(false))
                         break; // monitor will restart
                     // servers now swapped
                     // enable this now if inactive server is not still valid
                     monitorState.ActiveServer.ClosePortOnReboot = restartOnceSwapped;
                     if (!restartOnceSwapped)
                         /*
                          * now try to reopen it on the private port
                          * failing that, just reboot it
                          */
                         restartOnceSwapped = !await monitorState.InactiveServer.SetPort(ActiveLaunchParameters.SecondaryPort.Value, cancellationToken).ConfigureAwait(false);
                     // break either way because any issues past this point would be solved by the reboot
                     if (restartOnceSwapped) // for one reason or another
                         await UpdateAndRestartInactiveServer(true).ConfigureAwait(false); // update and reboot
                     else
                         monitorState.NextAction = MonitorAction.Skip; // only skip checking inactive server rebooted, it's guaranteed InactiveServerStartup complete wouldn't fire this iteration
                     break;
                 case MonitorActivationReason.InactiveServerRebooted:
                     // just don't let the active server close it's port if the inactive server isn't ready
                     monitorState.RebootingInactiveServer = true;
                     monitorState.InactiveServer.ResetRebootState();
                     monitorState.ActiveServer.ClosePortOnReboot = false;
                     monitorState.NextAction = MonitorAction.Continue;
                     break;
                 case MonitorActivationReason.InactiveServerStartupComplete:
                     // opposite of above case
                     monitorState.RebootingInactiveServer = false;
                     monitorState.ActiveServer.ClosePortOnReboot = true;
                     monitorState.NextAction = MonitorAction.Continue;
                     break;
                 case MonitorActivationReason.NewDmbAvailable:
                 case MonitorActivationReason.ActiveLaunchParametersUpdated:
                     // just reload the inactive server and wait for a swap to apply the changes
                     await UpdateAndRestartInactiveServer(true).ConfigureAwait(false);
                     break;
                 case MonitorActivationReason.Heartbeat:
                 default:
                     throw new InvalidOperationException(
                         String.Format(
                             CultureInfo.InvariantCulture,
                             "Invalid monitor activation reason: {0}!",
                             activationReason));
             }
         }
override async Task Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.InitControllers (Action callBeforeRecurse, Task chatTask, DualReattachInformation reattachInfo, CancellationToken cancellationToken) protected virtual
Starts all ISessionControllers.
Implements Tgstation.Server.Host.Components.Watchdog.WatchdogBase.
Definition at line 440 of file ExperimentalWatchdog.cs.
References Tgstation.Server.Host.Components.Session.DualReattachInformation.Alpha, Tgstation.Server.Host.Models.DualReattachInformationBase.AlphaIsActive, Tgstation.Server.Host.Components.Session.DualReattachInformation.Bravo, Tgstation.Server.Host.Components.Session.SessionControllerFactory.CreateDeadSession(), Tgstation.Server.Host.Core.AsyncDelayer.Delay(), Tgstation.Server.Host.Components.Session.ReattachInformation.Dmb, Tgstation.Server.Host.Components.Session.ISessionController.EnableCustomChatCommands(), Tgstation.Server.Host.Components.IRenameNotifyee.InstanceRenamed(), Tgstation.Server.Host.Components.Session.SessionControllerFactory.LaunchNew(), Tgstation.Server.Host.Components.Deployment.DmbFactory.LockNextDmb(), Tgstation.Server.Host.Components.Session.SessionControllerFactory.Reattach(), Tgstation.Server.Host.Components.Session.ISessionController.Release(), and Tgstation.Server.Host.System.IProcessBase.SetHighPriority().
         {
             Debug.Assert(alphaServer == null && bravoServer == null, "Entered LaunchNoLock with one or more of the servers not being null!");
             // don't need a new dmb if reattaching
             var doesntNeedNewDmb = reattachInfo?.Alpha != null && reattachInfo?.Bravo != null;
             var dmbToUse = doesntNeedNewDmb ? null : DmbFactory.LockNextDmb(2);
             // if this try catches something, both servers are killed
             try
             {
                 // start the alpha server task, either by launch a new process or attaching to an existing one
                 // The tasks returned are mainly for writing interop files to the directories among other things and should generally never fail
                 // The tasks pertaining to server startup times are in the ISessionControllers
                 Task<ISessionController> alphaServerTask;
                 if (!doesntNeedNewDmb)
                     alphaServerTask = SessionControllerFactory.LaunchNew(
                         dmbToUse,
                         null,
                         ActiveLaunchParameters,
                         true,
                         true,
                         false,
                         cancellationToken);
                 else
                     alphaServerTask = SessionControllerFactory.Reattach(reattachInfo.Alpha, cancellationToken);
                 // retrieve the session controller
                 var startTime = DateTimeOffset.Now;
                 alphaServer = await alphaServerTask.ConfigureAwait(false);
                 // failed reattaches will return null
                 alphaServer?.SetHighPriority();
                 // extra delay for total ordering
                 var now = DateTimeOffset.Now;
                 var delay = now - startTime;
                 // definitely not if reattaching though
                 if (reattachInfo == null && delay.TotalSeconds < AlphaBravoStartupSeperationInterval)
                     await AsyncDelayer.Delay(startTime.AddSeconds(AlphaBravoStartupSeperationInterval) - now, cancellationToken).ConfigureAwait(false);
                 // now bring bravo up
                 if (!doesntNeedNewDmb)
                     bravoServer = await SessionControllerFactory.LaunchNew(
                         dmbToUse,
                         null,
                         ActiveLaunchParameters,
                         false,
                         false,
                         false,
                         cancellationToken)
                         .ConfigureAwait(false);
                 else
                     bravoServer = await SessionControllerFactory.Reattach(reattachInfo.Bravo, cancellationToken).ConfigureAwait(false);
                 // failed reattaches will return null
                 bravoServer?.SetHighPriority();
                 // possiblity of null servers due to failed reattaches
                 if (alphaServer == null || bravoServer == null)
                 {
                     await chatTask.ConfigureAwait(false);
                     var bothServersDead = alphaServer == null && bravoServer == null;
                     if (bothServersDead
                         || (alphaServer == null && reattachInfo.AlphaIsActive)
                         || (bravoServer == null && !reattachInfo.AlphaIsActive))
                     {
                         // we lost the active server, just restart entirely
                         DisposeAndNullControllers();
                         const string FailReattachMessage = "Unable to properly reattach to active server! Restarting...";
                         Logger.LogWarning(FailReattachMessage);
                         Logger.LogDebug(bothServersDead ? "Also could not reattach to inactive server!" : "Inactive server was reattached successfully!");
                         chatTask = Chat.SendWatchdogMessage(FailReattachMessage, false, cancellationToken);
                         callBeforeRecurse();
                         await LaunchNoLock(true, false, null, cancellationToken).ConfigureAwait(false);
                         await chatTask.ConfigureAwait(false);
                         return;
                     }
                     // we still have the active server but the other one is dead to us, hand it off to the monitor to restart
                     const string InactiveReattachFailureMessage = "Unable to reattach to inactive server. Leaving for monitor to reboot...";
                     chatTask = Chat.SendWatchdogMessage(InactiveReattachFailureMessage, false, cancellationToken);
                     Logger.LogWarning(InactiveReattachFailureMessage);
                     if (reattachInfo.AlphaIsActive)
                         bravoServer = SessionControllerFactory.CreateDeadSession(reattachInfo.Bravo.Dmb);
                     else
                         alphaServer = SessionControllerFactory.CreateDeadSession(reattachInfo.Alpha.Dmb);
                 }
                 var alphaLrt = CheckLaunchResult(alphaServer, "Alpha", cancellationToken);
                 var bravoLrt = CheckLaunchResult(bravoServer, "Bravo", cancellationToken);
                 // this task completes when both serers have finished booting
                 var allTask = Task.WhenAll(alphaLrt, bravoLrt);
                 await allTask.ConfigureAwait(false);
                 // both servers are now running, alpha is the active server(unless reattach), huzzah
                 alphaIsActive = reattachInfo?.AlphaIsActive ?? true;
                 var activeServer = AlphaIsActive ? alphaServer : bravoServer;
                 activeServer.EnableCustomChatCommands();
                 activeServer.ClosePortOnReboot = true;
             }
             catch
             {
                 if (dmbToUse != null)
                 {
                     // we locked 2 dmbs
                     if (bravoServer == null)
                     {
                         // bravo didn't get control of his
                         dmbToUse.Dispose();
                         if (alphaServer == null)
                             dmbToUse.Dispose(); // alpha didn't get control of his
                     }
                 }
                 else if (doesntNeedNewDmb) // we have reattachInfo
                     if (bravoServer == null)
                     {
                         // bravo didn't get control of his
                         reattachInfo.Bravo?.Dmb.Dispose();
                         if (alphaServer == null)
                             reattachInfo.Alpha?.Dmb.Dispose(); // alpha didn't get control of his
                     }
                 // kill the controllers
                 DisposeAndNullControllers();
                 throw;
             }
         }
override Task Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.InstanceRenamed (string newInstanceName, CancellationToken cancellationToken) virtual
Called when the owning Instance is renamed.
Implements Tgstation.Server.Host.Components.Watchdog.WatchdogBase.
Member Data Documentation
override Models.CompileJob Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.ActiveCompileJob => (AlphaIsActive ? alphaServer : bravoServer)?.Dmb.CompileJob
Definition at line 32 of file ExperimentalWatchdog.cs.
const int Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.AlphaBravoStartupSeperationInterval = 10 private
The time in seconds to wait from starting alphaServer to start bravoServer. Does not take responsiveness into account
Definition at line 26 of file ExperimentalWatchdog.cs.
override bool Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.AlphaIsActive => alphaIsActive
Definition at line 29 of file ExperimentalWatchdog.cs.
bool Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.alphaIsActive private
Backing field for AlphaIsActive.
Definition at line 50 of file ExperimentalWatchdog.cs.
ISessionController Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.alphaServer private
Server designation alpha
Definition at line 40 of file ExperimentalWatchdog.cs.
ISessionController Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.bravoServer private
Server designation bravo
Definition at line 45 of file ExperimentalWatchdog.cs.
override RebootState Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.RebootState => Running ? (AlphaIsActive ? alphaServer?.RebootState : bravoServer?.RebootState) : null
Definition at line 35 of file ExperimentalWatchdog.cs.
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Watchdog/ExperimentalWatchdog.cs