tgstation-server: Tgstation.Server.Host.Core.ServerUpdater Class Reference
Tgstation.Server.Host.Core.ServerUpdater Class Reference sealed
Public Member Functions
ServerUpdater (IGitHubServiceFactory gitHubServiceFactory, IIOManager ioManager, IFileDownloader fileDownloader, IServerControl serverControl, ILogger< ServerUpdater > logger, IOptionsMonitor< GeneralConfiguration > generalConfigurationOptions, IOptionsMonitor< UpdatesConfiguration > updatesConfigurationOptions)
Initializes a new instance of the ServerUpdater class.
async ValueTask< ServerUpdateResult > BeginUpdate (ISwarmService swarmService, IFileStreamProvider? fileStreamProvider, Version version, CancellationToken cancellationToken)
Start the process of downloading and applying an update to a new server version .
Parameters
swarmService The ISwarmService to use to coordinate the update.
fileStreamProvider The optional IFileStreamProvider used to retrieve the target server version . If not provided, GitHub will be used.
version The TGS Version to update to.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the ServerUpdateResult.
async ValueTask< bool > ExecuteUpdate (string updatePath, CancellationToken cancellationToken, CancellationToken criticalCancellationToken)
Executes a pending server update by extracting the new server to a given updatePath .
Parameters
updatePath The path to extract the update zip to.
cancellationToken The CancellationToken for non-critical parts of this operation.
criticalCancellationToken The CancellationToken for the operation. Must not be trivial as it can desync swarm nodes if fired at an inappropriate time.
Returns
A ValueTask<TResult> resulting in true if the update was successful, false otherwise.
Private Member Functions
async ValueTask TryAbort (Exception exception)
Attempt to abort a prepared swarm update.
async ValueTask< Tuple< BufferedFileStreamProvider, bool >?> PrepareUpdateClearStagingAndBufferStream (string stagingDirectory, CancellationToken cancellationToken)
Prepares the swarm update, deletes the stagingDirectory , and buffers the ServerUpdateOperation.FileStreamProvider.
async ValueTask< ServerUpdateResult > BeginUpdateImpl (ISwarmService swarmService, IFileStreamProvider? fileStreamProvider, Version newVersion, bool recursed, CancellationToken cancellationToken)
Start the process of downloading and applying an update to a new server version. Doesn't perform argument checking.
Private Attributes
readonly IGitHubServiceFactory gitHubServiceFactory
The IGitHubServiceFactory for the ServerUpdater.
readonly IIOManager ioManager
The IIOManager for the ServerUpdater.
readonly IFileDownloader fileDownloader
The IFileDownloader for the ServerUpdater.
readonly IServerControl serverControl
The IServerControl for the ServerUpdater.
readonly IOptionsMonitor< GeneralConfiguration > generalConfigurationOptions
The IOptionsMonitor<TOptions> of GeneralConfiguration for the ServerUpdater.
readonly IOptionsMonitor< UpdatesConfiguration > updatesConfigurationOptions
The IOptionsMonitor<TOptions> of UpdatesConfiguration for the ServerUpdater.
readonly ILogger< ServerUpdater > logger
The ILogger for the ServerUpdater.
readonly object updateInitiationLock
Lock object used when initiating an update.
ServerUpdateOperation? serverUpdateOperation
ServerUpdateOperation for an in-progress update operation.
Detailed Description
Definition at line 17 of file ServerUpdater.cs.
Constructor & Destructor Documentation
ServerUpdater()
Tgstation.Server.Host.Core.ServerUpdater.ServerUpdater (IGitHubServiceFactory gitHubServiceFactory, IIOManager ioManager, IFileDownloader fileDownloader, IServerControl serverControl, ILogger< ServerUpdater > logger, IOptionsMonitor< GeneralConfiguration > generalConfigurationOptions, IOptionsMonitor< UpdatesConfiguration > updatesConfigurationOptions)
Initializes a new instance of the ServerUpdater class.
Parameters
gitHubServiceFactory The value of gitHubServiceFactory.
ioManager The value of ioManager.
fileDownloader The value of fileDownloader.
serverControl The value of serverControl.
logger The value of logger.
generalConfigurationOptions The value of generalConfigurationOptions.
updatesConfigurationOptions The value of updatesConfigurationOptions.
Definition at line 74 of file ServerUpdater.cs.
        {
            this.gitHubServiceFactory = gitHubServiceFactory ?? throw new ArgumentNullException(nameof(gitHubServiceFactory));
            this.ioManager = ioManager ?? throw new ArgumentNullException(nameof(ioManager));
            this.fileDownloader = fileDownloader ?? throw new ArgumentNullException(nameof(fileDownloader));
            this.serverControl = serverControl ?? throw new ArgumentNullException(nameof(serverControl));
            this.generalConfigurationOptions = generalConfigurationOptions ?? throw new ArgumentNullException(nameof(generalConfigurationOptions));
            this.updatesConfigurationOptions = updatesConfigurationOptions ?? throw new ArgumentNullException(nameof(updatesConfigurationOptions));
            this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
            updateInitiationLock = new object();
        }
References Tgstation.Server.Host.Core.ServerUpdater.fileDownloader, Tgstation.Server.Host.Core.ServerUpdater.generalConfigurationOptions, Tgstation.Server.Host.Core.ServerUpdater.gitHubServiceFactory, Tgstation.Server.Host.Core.ServerUpdater.ioManager, Tgstation.Server.Host.Core.ServerUpdater.logger, Tgstation.Server.Host.Core.ServerUpdater.serverControl, Tgstation.Server.Host.Core.ServerUpdater.updateInitiationLock, and Tgstation.Server.Host.Core.ServerUpdater.updatesConfigurationOptions.
Member Function Documentation
BeginUpdate()
async ValueTask< ServerUpdateResult > Tgstation.Server.Host.Core.ServerUpdater.BeginUpdate (ISwarmService swarmService, IFileStreamProvider? fileStreamProvider, Version version, CancellationToken cancellationToken)
Start the process of downloading and applying an update to a new server version .
Parameters
swarmService The ISwarmService to use to coordinate the update.
fileStreamProvider The optional IFileStreamProvider used to retrieve the target server version . If not provided, GitHub will be used.
version The TGS Version to update to.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the ServerUpdateResult.
Implements Tgstation.Server.Host.Core.IServerUpdater.
Definition at line 95 of file ServerUpdater.cs.
        {
            ArgumentNullException.ThrowIfNull(swarmService);
            ArgumentNullException.ThrowIfNull(version);
            if (!swarmService.ExpectedNumberOfNodesConnected)
                return ServerUpdateResult.SwarmIntegrityCheckFailed;
            return await BeginUpdateImpl(swarmService, fileStreamProvider, version, false, cancellationToken);
        }
References Tgstation.Server.Host.Core.ServerUpdater.BeginUpdateImpl(), and Tgstation.Server.Host.Swarm.ISwarmService.ExpectedNumberOfNodesConnected.
BeginUpdateImpl()
async ValueTask< ServerUpdateResult > Tgstation.Server.Host.Core.ServerUpdater.BeginUpdateImpl (ISwarmService swarmService, IFileStreamProvider? fileStreamProvider, Version newVersion, bool recursed, CancellationToken cancellationToken) private
Start the process of downloading and applying an update to a new server version. Doesn't perform argument checking.
Parameters
swarmService The ISwarmService to use to coordinate the update.
fileStreamProvider The optional IFileStreamProvider used to retrieve the target server version. If not provided, GitHub will be used.
newVersion The TGS Version to update to.
recursed If this is a recursive call.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the ServerUpdateResult.
Definition at line 277 of file ServerUpdater.cs.
        {
            ServerUpdateOperation? ourUpdateOperation = null;
            try
            {
                if (fileStreamProvider == null)
                {
                    logger.LogDebug("Looking for GitHub releases version {version}...", newVersion);
                    var gitHubService = await gitHubServiceFactory.CreateService(cancellationToken);
                    var releases = await gitHubService.GetTgsReleases(cancellationToken);
                    var updatesConfiguration = updatesConfigurationOptions.CurrentValue;
                    var generalConfiguration = generalConfigurationOptions.CurrentValue;
                    foreach (var kvp in releases)
                    {
                        var version = kvp.Key;
                        var release = kvp.Value;
                        if (version == newVersion)
{
                            var asset = release.Assets.Where(x => x.Name.Equals(updatesConfiguration.UpdatePackageAssetName, StringComparison.Ordinal)).FirstOrDefault();
                            if (asset == default)
                                continue;
                            logger.LogTrace("Creating download provider for {assetName}...", updatesConfiguration.UpdatePackageAssetName);
                            var bearerToken = generalConfiguration.GitHubAccessToken;
                            if (String.IsNullOrWhiteSpace(bearerToken))
                                bearerToken = null;
                            fileStreamProvider = fileDownloader.DownloadFile(new Uri(asset.BrowserDownloadUrl), bearerToken);
                            break;
                        }
                    }
                    if (fileStreamProvider == null)
                    {
                        if (!recursed)
{
                            logger.LogWarning("We didn't find the requested release, but GitHub has been known to just not give full results when querying all releases. We'll try one more time.");
                            return await BeginUpdateImpl(swarmService, null, newVersion, true, cancellationToken);
                        }
                        return ServerUpdateResult.ReleaseMissing;
                    }
                }
                lock (updateInitiationLock)
                {
                    if (serverUpdateOperation == null)
                    {
                        ourUpdateOperation = new ServerUpdateOperation(
                            fileStreamProvider,
                            swarmService,
                            newVersion);
                        serverUpdateOperation = ourUpdateOperation;
                        bool updateStarted = serverControl.TryStartUpdate(this, newVersion);
                        if (updateStarted)
{
                            fileStreamProvider = null; // belongs to serverUpdateOperation now
                            return ServerUpdateResult.Started;
                        }
                    }
                    return ServerUpdateResult.UpdateInProgress;
                }
            }
            catch
            {
                lock (updateInitiationLock)
                    if (serverUpdateOperation == ourUpdateOperation)
                        serverUpdateOperation = null;
                throw;
            }
            finally
            {
                if (fileStreamProvider != null)
                    await fileStreamProvider.DisposeAsync();
            }
        }
References Tgstation.Server.Host.Core.ServerUpdater.BeginUpdateImpl(), Tgstation.Server.Host.Utils.GitHub.IGitHubServiceFactory.CreateService(), Tgstation.Server.Host.IO.IFileDownloader.DownloadFile(), Tgstation.Server.Host.Core.ServerUpdater.fileDownloader, Tgstation.Server.Host.Core.ServerUpdater.generalConfigurationOptions, Tgstation.Server.Host.Core.ServerUpdater.gitHubServiceFactory, Tgstation.Server.Host.Core.ServerUpdater.logger, Tgstation.Server.Host.Core.ServerUpdater.serverControl, Tgstation.Server.Host.Core.ServerUpdater.serverUpdateOperation, Tgstation.Server.Host.Core.IServerControl.TryStartUpdate(), Tgstation.Server.Host.Core.ServerUpdater.updateInitiationLock, and Tgstation.Server.Host.Core.ServerUpdater.updatesConfigurationOptions.
Referenced by Tgstation.Server.Host.Core.ServerUpdater.BeginUpdate(), and Tgstation.Server.Host.Core.ServerUpdater.BeginUpdateImpl().
ExecuteUpdate()
async ValueTask< bool > Tgstation.Server.Host.Core.ServerUpdater.ExecuteUpdate (string updatePath, CancellationToken cancellationToken, CancellationToken criticalCancellationToken)
Executes a pending server update by extracting the new server to a given updatePath .
Parameters
updatePath The path to extract the update zip to.
cancellationToken The CancellationToken for non-critical parts of this operation.
criticalCancellationToken The CancellationToken for the operation. Must not be trivial as it can desync swarm nodes if fired at an inappropriate time.
Returns
A ValueTask<TResult> resulting in true if the update was successful, false otherwise.
Implements Tgstation.Server.Host.Core.IServerUpdateExecutor.
Definition at line 108 of file ServerUpdater.cs.
        {
            ArgumentNullException.ThrowIfNull(updatePath);
            var serverUpdateOperation = this.serverUpdateOperation;
            if (serverUpdateOperation == null)
                throw new InvalidOperationException($"{nameof(serverUpdateOperation)} was null!");
            var inMustCommitUpdate = false;
            try
            {
                var stagingDirectory = $"{updatePath}-stage";
                var tuple = await PrepareUpdateClearStagingAndBufferStream(stagingDirectory, cancellationToken);
                if (tuple == null)
                    return false;
                await using var bufferedStream = tuple.Item1;
                var needStreamUntilCommit = tuple.Item2;
                var createdStagingDirectory = false;
                try
                {
                    try
                    {
                        logger.LogTrace("Extracting zip package to {stagingDirectory}...", stagingDirectory);
                        var updateZipData = await bufferedStream.GetResult(cancellationToken);
                        createdStagingDirectory = true;
                        await ioManager.ZipToDirectory(stagingDirectory, updateZipData, cancellationToken);
                        if (!needStreamUntilCommit)
{
                            logger.LogTrace("Early disposing update stream provider...");
                            await bufferedStream.DisposeAsync(); // don't leave this in memory
                        }
                    }
                    catch (Exception ex)
                    {
                        await TryAbort(ex);
                        throw;
                    }
                    var updateCommitResult = await serverUpdateOperation.SwarmService.CommitUpdate(criticalCancellationToken);
                    if (updateCommitResult == SwarmCommitResult.AbortUpdate)
                    {
                        logger.LogError("Swarm distributed commit failed, not applying update!");
                        return false;
                    }
                    inMustCommitUpdate = updateCommitResult == SwarmCommitResult.MustCommitUpdate;
                    logger.LogTrace("Moving {stagingDirectory} to {updateDirectory}...", stagingDirectory, updatePath);
                    await ioManager.MoveDirectory(stagingDirectory, updatePath, criticalCancellationToken);
                }
                catch (Exception e) when (createdStagingDirectory)
                {
                    try
                    {
                        // important to not leave this directory around if possible
                        await ioManager.DeleteDirectory(stagingDirectory, default);
                    }
                    catch (Exception e2)
                    {
                        throw new AggregateException(e, e2);
                    }
                    throw;
                }
                return true;
            }
            catch (OperationCanceledException) when (!inMustCommitUpdate)
            {
                logger.LogInformation("Server update cancelled!");
            }
            catch (Exception ex) when (!inMustCommitUpdate)
            {
                logger.LogError(ex, "Error updating server!");
            }
            catch (Exception ex) when (inMustCommitUpdate)
            {
                logger.LogCritical(ex, "Could not complete committed swarm update!");
            }
            return false;
        }
References Tgstation.Server.Host.Swarm.ISwarmService.CommitUpdate(), Tgstation.Server.Host.IO.IIOManager.DeleteDirectory(), Tgstation.Server.Host.Core.ServerUpdater.ioManager, Tgstation.Server.Host.Core.ServerUpdater.logger, Tgstation.Server.Host.IO.IIOManager.MoveDirectory(), Tgstation.Server.Host.Core.ServerUpdater.PrepareUpdateClearStagingAndBufferStream(), Tgstation.Server.Host.Core.ServerUpdater.serverUpdateOperation, Tgstation.Server.Host.Core.ServerUpdateOperation.SwarmService, Tgstation.Server.Host.Core.ServerUpdater.TryAbort(), and Tgstation.Server.Host.IO.IIOManager.ZipToDirectory().
PrepareUpdateClearStagingAndBufferStream()
async ValueTask< Tuple< BufferedFileStreamProvider, bool >?> Tgstation.Server.Host.Core.ServerUpdater.PrepareUpdateClearStagingAndBufferStream (string stagingDirectory, CancellationToken cancellationToken) private
Prepares the swarm update, deletes the stagingDirectory , and buffers the ServerUpdateOperation.FileStreamProvider.
Parameters
stagingDirectory The directory the server update is initially extracted to.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in Tuple<T1, T2> containing a new BufferedFileStreamProvider based on the ServerUpdateOperation.FileStreamProvider of serverUpdateOperation and true if it needs to be kept active until the swarm commit. If null, the update failed to prepare.
Requires serverUpdateOperation to be populated.
Definition at line 219 of file ServerUpdater.cs.
        {
            await using var fileStreamProvider = serverUpdateOperation!.FileStreamProvider;
            var bufferedStream = new BufferedFileStreamProvider(
                await fileStreamProvider.GetResult(cancellationToken));
            try
            {
                var updatePrepareResult = await serverUpdateOperation.SwarmService.PrepareUpdate(
                    bufferedStream,
                    serverUpdateOperation.TargetVersion,
                    cancellationToken);
                if (updatePrepareResult == SwarmPrepareResult.Failure)
                {
                    await bufferedStream.DisposeAsync();
                    return null;
                }
                try
                {
                    // simply buffer the result at this point
                    var bufferingTask = bufferedStream.EnsureBuffered(cancellationToken);
                    // clear out the staging directory first
                    await ioManager.DeleteDirectory(stagingDirectory, cancellationToken);
                    // Dispose warning avoidance
                    var result = Tuple.Create(
                        bufferedStream,
                        updatePrepareResult == SwarmPrepareResult.SuccessHoldProviderUntilCommit);
                    await bufferingTask;
                    bufferedStream = null;
                    return result;
                }
                catch (Exception ex)
                {
                    await TryAbort(ex);
                    throw;
                }
            }
            finally
            {
                if (bufferedStream != null)
                    await bufferedStream.DisposeAsync();
            }
        }
References Tgstation.Server.Host.IO.IIOManager.DeleteDirectory(), Tgstation.Server.Host.Core.ServerUpdateOperation.FileStreamProvider, Tgstation.Server.Host.Core.ServerUpdater.ioManager, Tgstation.Server.Host.Swarm.ISwarmService.PrepareUpdate(), Tgstation.Server.Host.Core.ServerUpdater.serverUpdateOperation, Tgstation.Server.Host.Core.ServerUpdateOperation.SwarmService, Tgstation.Server.Host.Core.ServerUpdateOperation.TargetVersion, and Tgstation.Server.Host.Core.ServerUpdater.TryAbort().
Referenced by Tgstation.Server.Host.Core.ServerUpdater.ExecuteUpdate().
TryAbort()
async ValueTask Tgstation.Server.Host.Core.ServerUpdater.TryAbort (Exception exception) private
Attempt to abort a prepared swarm update.
Parameters
exception The Exception being thrown.
Returns
A ValueTask representing the running operation.
Exceptions
AggregateException A new AggregateException containing exception and the swarm abort Exception if thrown.
Requires serverUpdateOperation to be populated.
Definition at line 200 of file ServerUpdater.cs.
        {
            try
            {
                await serverUpdateOperation!.SwarmService.AbortUpdate();
            }
            catch (Exception e2)
            {
                throw new AggregateException(exception, e2);
            }
        }
References Tgstation.Server.Host.Swarm.ISwarmUpdateAborter.AbortUpdate(), Tgstation.Server.Host.Core.ServerUpdater.serverUpdateOperation, and Tgstation.Server.Host.Core.ServerUpdateOperation.SwarmService.
Referenced by Tgstation.Server.Host.Core.ServerUpdater.ExecuteUpdate(), and Tgstation.Server.Host.Core.ServerUpdater.PrepareUpdateClearStagingAndBufferStream().
Member Data Documentation
fileDownloader
readonly IFileDownloader Tgstation.Server.Host.Core.ServerUpdater.fileDownloader private
The IFileDownloader for the ServerUpdater.
Definition at line 32 of file ServerUpdater.cs.
Referenced by Tgstation.Server.Host.Core.ServerUpdater.BeginUpdateImpl(), and Tgstation.Server.Host.Core.ServerUpdater.ServerUpdater().
generalConfigurationOptions
readonly IOptionsMonitor<GeneralConfiguration> Tgstation.Server.Host.Core.ServerUpdater.generalConfigurationOptions private
The IOptionsMonitor<TOptions> of GeneralConfiguration for the ServerUpdater.
Definition at line 42 of file ServerUpdater.cs.
Referenced by Tgstation.Server.Host.Core.ServerUpdater.BeginUpdateImpl(), and Tgstation.Server.Host.Core.ServerUpdater.ServerUpdater().
gitHubServiceFactory
readonly IGitHubServiceFactory Tgstation.Server.Host.Core.ServerUpdater.gitHubServiceFactory private
The IGitHubServiceFactory for the ServerUpdater.
Definition at line 22 of file ServerUpdater.cs.
Referenced by Tgstation.Server.Host.Core.ServerUpdater.BeginUpdateImpl(), and Tgstation.Server.Host.Core.ServerUpdater.ServerUpdater().
ioManager
readonly IIOManager Tgstation.Server.Host.Core.ServerUpdater.ioManager private
The IIOManager for the ServerUpdater.
Definition at line 27 of file ServerUpdater.cs.
Referenced by Tgstation.Server.Host.Core.ServerUpdater.ExecuteUpdate(), Tgstation.Server.Host.Core.ServerUpdater.PrepareUpdateClearStagingAndBufferStream(), and Tgstation.Server.Host.Core.ServerUpdater.ServerUpdater().
logger
readonly ILogger<ServerUpdater> Tgstation.Server.Host.Core.ServerUpdater.logger private
The ILogger for the ServerUpdater.
Definition at line 52 of file ServerUpdater.cs.
Referenced by Tgstation.Server.Host.Core.ServerUpdater.BeginUpdateImpl(), Tgstation.Server.Host.Core.ServerUpdater.ExecuteUpdate(), and Tgstation.Server.Host.Core.ServerUpdater.ServerUpdater().
serverControl
readonly IServerControl Tgstation.Server.Host.Core.ServerUpdater.serverControl private
The IServerControl for the ServerUpdater.
Definition at line 37 of file ServerUpdater.cs.
Referenced by Tgstation.Server.Host.Core.ServerUpdater.BeginUpdateImpl(), and Tgstation.Server.Host.Core.ServerUpdater.ServerUpdater().
serverUpdateOperation
ServerUpdateOperation? Tgstation.Server.Host.Core.ServerUpdater.serverUpdateOperation private
ServerUpdateOperation for an in-progress update operation.
Definition at line 62 of file ServerUpdater.cs.
Referenced by Tgstation.Server.Host.Core.ServerUpdater.BeginUpdateImpl(), Tgstation.Server.Host.Core.ServerUpdater.ExecuteUpdate(), Tgstation.Server.Host.Core.ServerUpdater.PrepareUpdateClearStagingAndBufferStream(), and Tgstation.Server.Host.Core.ServerUpdater.TryAbort().
updateInitiationLock
readonly object Tgstation.Server.Host.Core.ServerUpdater.updateInitiationLock private
Lock object used when initiating an update.
Definition at line 57 of file ServerUpdater.cs.
Referenced by Tgstation.Server.Host.Core.ServerUpdater.BeginUpdateImpl(), and Tgstation.Server.Host.Core.ServerUpdater.ServerUpdater().
updatesConfigurationOptions
readonly IOptionsMonitor<UpdatesConfiguration> Tgstation.Server.Host.Core.ServerUpdater.updatesConfigurationOptions private
The IOptionsMonitor<TOptions> of UpdatesConfiguration for the ServerUpdater.
Definition at line 47 of file ServerUpdater.cs.
Referenced by Tgstation.Server.Host.Core.ServerUpdater.BeginUpdateImpl(), and Tgstation.Server.Host.Core.ServerUpdater.ServerUpdater().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Core/ServerUpdater.cs