tgstation-server: Tgstation.Server.Tests.AdministrationTest Class Reference
Tgstation.Server.Tests.AdministrationTest Class Reference
Public Member Functions
AdministrationTest (IAdministrationClient client)
async Task Run (CancellationToken cancellationToken)
Private Member Functions
async Task TestRead (CancellationToken cancellationToken)
Private Attributes
readonly IAdministrationClient client
Detailed Description
Definition at line 11 of file AdministrationTest.cs.
Constructor & Destructor Documentation
AdministrationTest()
Tgstation.Server.Tests.AdministrationTest.AdministrationTest (IAdministrationClient client)
Definition at line 15 of file AdministrationTest.cs.
         {
             this.client = client ?? throw new ArgumentNullException(nameof(client));
         }
References Tgstation.Server.Tests.AdministrationTest.client.
Member Function Documentation
Run()
async Task Tgstation.Server.Tests.AdministrationTest.Run (CancellationToken cancellationToken)
Definition at line 20 of file AdministrationTest.cs.
         {
             await TestRead(cancellationToken).ConfigureAwait(false);
         }
References Tgstation.Server.Tests.AdministrationTest.TestRead().
Referenced by Tgstation.Server.Tests.IntegrationTest.TestFullStandardOperation().
TestRead()
async Task Tgstation.Server.Tests.AdministrationTest.TestRead (CancellationToken cancellationToken) private
Definition at line 25 of file AdministrationTest.cs.
         {
             Administration model;
             try
             {
                 model = await client.Read(cancellationToken).ConfigureAwait(false);
             }
             catch (RateLimitException)
             {
                 Assert.Inconclusive("GitHub rate limit hit while testing administration endpoint. Set environment variable TGS4_TEST_GITHUB_TOKEN to fix this!");
                 return; //c# needs the equivalent of [noreturn]
             }
             Assert.AreEqual(RuntimeInformation.IsOSPlatform(OSPlatform.Windows), model.WindowsHost);
             //we've released a few 4.x versions now, check the release checker is at least somewhat functional
             Assert.AreEqual(4, model.LatestVersion.Major);
         }
References Tgstation.Server.Tests.AdministrationTest.client, Tgstation.Server.Api.Models.Administration.LatestVersion, Tgstation.Server.Client.IAdministrationClient.Read(), and Tgstation.Server.Api.Models.Administration.WindowsHost.
Referenced by Tgstation.Server.Tests.AdministrationTest.Run().
Member Data Documentation
client
readonly IAdministrationClient Tgstation.Server.Tests.AdministrationTest.client private
Definition at line 13 of file AdministrationTest.cs.
Referenced by Tgstation.Server.Tests.AdministrationTest.AdministrationTest(), and Tgstation.Server.Tests.AdministrationTest.TestRead().
The documentation for this class was generated from the following file:
tests/Tgstation.Server.Tests/AdministrationTest.cs