tgstation-server: Tgstation.Server.Host.Jobs.JobService Class Reference
Tgstation.Server.Host.Jobs.JobService Class Reference
Public Member Functions
JobService (IConnectionMappedHubContext< JobsHub, IJobsHub > hub, IDatabaseContextFactory databaseContextFactory, ILoggerFactory loggerFactory, ILogger< JobService > logger)
Initializes a new instance of the JobService class.
void Dispose ()
async ValueTask RegisterOperation (Job job, JobEntrypoint operation, CancellationToken cancellationToken)
Registers a given Job and begins running it.
Parameters
job The Job. Should at least have Job.Instance and Api.Models.Internal.Job.Description. If Job.StartedBy is null, the TGS user will be used.
operation The JobEntrypoint for the job .
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing a running operation.
Task StartAsync (CancellationToken cancellationToken)
Task StopAsync (CancellationToken cancellationToken)
async ValueTask< Job?> CancelJob (Job job, User? user, bool blocking, CancellationToken cancellationToken)
Cancels a give job .
Parameters
job The Job to cancel.
user The User who cancelled the job . If null the TGS user will be used.
blocking If the operation should wait until the job exits before completing.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the updated job if it was cancelled, null if it couldn't be found.
void SetJobProgress (JobResponse apiResponse)
Set the JobResponse.Progress and JobResponse.Stage for a given apiResponse .
Parameters
apiResponse The JobResponse to update.
async ValueTask< bool?> WaitForJobCompletion (Job job, User? canceller, CancellationToken jobCancellationToken, CancellationToken cancellationToken)
Wait for a given job to complete.
Parameters
job The Job to wait for.
canceller The User to cancel the job . If null the TGS user will be used.
jobCancellationToken A CancellationToken that will cancel the job .
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> representing the Job. Results in true if the Job completed without errors, false if errors occurred, or null if the job isn't registered.
void Activate (IInstanceCoreProvider instanceCoreProvider)
Activate the IJobManager.
Parameters
instanceCoreProvider The IInstanceCoreProvider for the IJobManager.
void QueueActiveJobUpdates ()
Queue a message to be sent to all clients with the current state of active jobs.
void Activate (IInstanceCoreProvider instanceCoreProvider)
Activate the IJobManager.
void SetJobProgress (JobResponse apiResponse)
Set the JobResponse.Progress and JobResponse.Stage for a given apiResponse .
ValueTask RegisterOperation (Job job, JobEntrypoint operation, CancellationToken cancellationToken)
Registers a given Job and begins running it.
ValueTask< bool?> WaitForJobCompletion (Job job, User? canceller, CancellationToken jobCancellationToken, CancellationToken cancellationToken)
Wait for a given job to complete.
ValueTask< Job?> CancelJob (Job job, User? user, bool blocking, CancellationToken cancellationToken)
Cancels a give job .
void QueueActiveJobUpdates ()
Queue a message to be sent to all clients with the current state of active jobs.
Private Member Functions
async Task< bool > RunJob (Job job, JobEntrypoint operation, CancellationToken cancellationToken)
Runner for JobHandlers.
Private Attributes
readonly IConnectionMappedHubContext< JobsHub, IJobsHub > hub
The IHubContext for the JobsHub.
readonly IDatabaseContextFactory databaseContextFactory
The IServiceProvider for the JobService.
readonly ILoggerFactory loggerFactory
The ILoggerFactory for the JobService.
readonly ILogger< JobService > logger
The ILogger for the JobService.
readonly Dictionary< long, JobHandler > jobs
Dictionary<TKey, TValue> of Job Api.Models.EntityId.Ids to running JobHandlers.
readonly Dictionary< long, Action > hubUpdateActions
Dictionary<TKey, TValue> of running Job Api.Models.EntityId.Ids to Actions that will push immediate hub updates.
readonly TaskCompletionSource< IInstanceCoreProvider > activationTcs
TaskCompletionSource<TResult> to delay starting jobs until the server is ready.
readonly object synchronizationLock
lock object for various operations.
readonly object addCancelLock
Prevents a really REALLY rare race condition between add and cancel operations.
volatile bool noMoreJobsShouldStart
Prevents jobs that are registered after shutdown from activating.
Static Private Attributes
const int MaxHubUpdatesPerSecond = 1
The maximum rate at which hub clients can receive updates.
Detailed Description
Definition at line 28 of file JobService.cs.
Constructor & Destructor Documentation
JobService()
Tgstation.Server.Host.Jobs.JobService.JobService (IConnectionMappedHubContext< JobsHub, IJobsHub > hub, IDatabaseContextFactory databaseContextFactory, ILoggerFactory loggerFactory, ILogger< JobService > logger)
Initializes a new instance of the JobService class.
Parameters
hub The value of hub.
databaseContextFactory The value of databaseContextFactory.
loggerFactory The value of loggerFactory.
logger The value of logger.
Definition at line 92 of file JobService.cs.
        {
            this.hub = hub ?? throw new ArgumentNullException(nameof(hub));
            this.databaseContextFactory = databaseContextFactory ?? throw new ArgumentNullException(nameof(databaseContextFactory));
            this.loggerFactory = loggerFactory ?? throw new ArgumentNullException(nameof(loggerFactory));
            this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
            jobs = new Dictionary<long, JobHandler>();
            hubUpdateActions = new Dictionary<long, Action>();
            activationTcs = new TaskCompletionSource<IInstanceCoreProvider>();
            synchronizationLock = new object();
            addCancelLock = new object();
        }
References Tgstation.Server.Host.Jobs.JobService.activationTcs, Tgstation.Server.Host.Jobs.JobService.addCancelLock, Tgstation.Server.Host.Jobs.JobService.databaseContextFactory, Tgstation.Server.Host.Jobs.JobService.hub, Tgstation.Server.Host.Jobs.JobService.hubUpdateActions, Tgstation.Server.Host.Jobs.JobService.jobs, Tgstation.Server.Host.Jobs.JobService.logger, Tgstation.Server.Host.Jobs.JobService.loggerFactory, and Tgstation.Server.Host.Jobs.JobService.synchronizationLock.
Member Function Documentation
Activate()
void Tgstation.Server.Host.Jobs.JobService.Activate (IInstanceCoreProvider instanceCoreProvider)
Activate the IJobManager.
Parameters
instanceCoreProvider The IInstanceCoreProvider for the IJobManager.
Implements Tgstation.Server.Host.Jobs.IJobService.
Definition at line 337 of file JobService.cs.
        {
            ArgumentNullException.ThrowIfNull(instanceCoreProvider);
            logger.LogTrace("Activating job manager...");
            activationTcs.SetResult(instanceCoreProvider);
        }
CancelJob()
async ValueTask< Job?> Tgstation.Server.Host.Jobs.JobService.CancelJob (Job job, User? user, bool blocking, CancellationToken cancellationToken)
Cancels a give job .
Parameters
job The Job to cancel.
user The User who cancelled the job . If null the TGS user will be used.
blocking If the operation should wait until the job exits before completing.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the updated job if it was cancelled, null if it couldn't be found.
Implements Tgstation.Server.Host.Jobs.IJobManager.
Definition at line 240 of file JobService.cs.
        {
            ArgumentNullException.ThrowIfNull(job);
            var jid = job.Require(x => x.Id);
            JobHandler? handler;
            lock (addCancelLock)
            {
                lock (synchronizationLock)
                    if (!jobs.TryGetValue(jid, out handler))
                        return null;
                logger.LogDebug("Cancelling job ID {jobId}...", jid);
                handler.Cancel(); // this will ensure the db update is only done once
            }
            await databaseContextFactory.UseContext(async databaseContext =>
            {
                var updatedJob = new Job(jid);
                databaseContext.Jobs.Attach(updatedJob);
                var attachedUser = user == null
                    ? await databaseContext
                        .Users
                        .GetTgsUser(
                            dbUser => new User
{
                                Id = dbUser.Id!.Value,
                            },
                            cancellationToken)
                    : new User
                    {
                        Id = user.Require(x => x.Id),
                    };
                databaseContext.Users.Attach(attachedUser);
                updatedJob.CancelledBy = attachedUser;
                // let either startup or cancellation set job.cancelled
                await databaseContext.Save(cancellationToken);
                job.CancelledBy = user;
            });
            if (blocking)
            {
                logger.LogTrace("Waiting on cancelled job #{jobId}...", job.Id);
                await handler.Wait(cancellationToken);
                logger.LogTrace("Done waiting on job #{jobId}...", job.Id);
            }
            return job;
        }
References Tgstation.Server.Host.Jobs.JobHandler.Cancel(), Tgstation.Server.Api.Models.EntityId.Id, and Tgstation.Server.Host.Jobs.JobHandler.Wait().
Dispose()
void Tgstation.Server.Host.Jobs.JobService.Dispose ()
Definition at line 111 of file JobService.cs.
        {
            foreach (var job in jobs)
                job.Value.Dispose();
        }
References Tgstation.Server.Host.Jobs.JobService.jobs.
QueueActiveJobUpdates()
void Tgstation.Server.Host.Jobs.JobService.QueueActiveJobUpdates ()
Queue a message to be sent to all clients with the current state of active jobs.
Implements Tgstation.Server.Host.Jobs.IJobsHubUpdater.
Definition at line 346 of file JobService.cs.
        {
            lock (hubUpdateActions)
                foreach (var action in hubUpdateActions.Values)
                    action();
        }
RegisterOperation()
async ValueTask Tgstation.Server.Host.Jobs.JobService.RegisterOperation (Job job, JobEntrypoint operation, CancellationToken cancellationToken)
Registers a given Job and begins running it.
Parameters
job The Job. Should at least have Job.Instance and Api.Models.Internal.Job.Description. If Job.StartedBy is null, the TGS user will be used.
operation The JobEntrypoint for the job .
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing a running operation.
Implements Tgstation.Server.Host.Jobs.IJobManager.
Definition at line 118 of file JobService.cs.
        {
            ArgumentNullException.ThrowIfNull(job);
            ArgumentNullException.ThrowIfNull(operation);
            if (job.StartedBy != null && job.StartedBy.Name == null)
                throw new InvalidOperationException("StartedBy User associated with job does not have a Name!");
            if (job.Instance == null)
                throw new InvalidOperationException("No Instance associated with job!");
            job.StartedAt = DateTimeOffset.UtcNow;
            job.Cancelled = false;
            var originalStartedBy = job.StartedBy;
            await databaseContextFactory.UseContext(
                async databaseContext =>
                {
                    job.Instance = new Models.Instance
                    {
                        Id = job.Instance.Require(x => x.Id),
                    };
                    databaseContext.Instances.Attach(job.Instance);
                    originalStartedBy ??= await databaseContext
                        .Users
                        .GetTgsUser(
                            dbUser => new User
{
                                Id = dbUser.Id!.Value,
                                Name = dbUser.Name,
                            },
                            cancellationToken);
                    job.StartedBy = new User
                    {
                        Id = originalStartedBy.Require(x => x.Id),
                    };
                    databaseContext.Users.Attach(job.StartedBy);
                    databaseContext.Jobs.Add(job);
                    await databaseContext.Save(cancellationToken);
                });
            job.StartedBy = originalStartedBy;
            logger.LogDebug("Registering job {jobId}: {jobDesc}...", job.Id, job.Description);
            var jobHandler = new JobHandler(jobCancellationToken => RunJob(job, operation, jobCancellationToken));
            try
            {
                lock (addCancelLock)
                {
                    bool jobShouldStart;
                    lock (synchronizationLock)
                    {
                        jobs.Add(job.Require(x => x.Id), jobHandler);
                        jobShouldStart = !noMoreJobsShouldStart;
                    }
                    if (jobShouldStart)
                        jobHandler.Start();
                }
            }
            catch
            {
                jobHandler.Dispose();
                throw;
            }
        }
References Tgstation.Server.Host.Jobs.JobService.addCancelLock, Tgstation.Server.Host.Jobs.JobService.databaseContextFactory, Tgstation.Server.Api.Models.Internal.Job.Description, Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Host.Models.Job.Instance, Tgstation.Server.Host.Jobs.JobService.jobs, Tgstation.Server.Host.Jobs.JobService.logger, Tgstation.Server.Api.Models.UserName.Name, Tgstation.Server.Host.Jobs.JobService.noMoreJobsShouldStart, Tgstation.Server.Host.Jobs.JobService.RunJob(), Tgstation.Server.Host.Models.Job.StartedBy, Tgstation.Server.Host.Jobs.JobService.synchronizationLock, and Tgstation.Server.Host.Database.IDatabaseContextFactory.UseContext().
RunJob()
async Task< bool > Tgstation.Server.Host.Jobs.JobService.RunJob (Job job, JobEntrypoint operation, CancellationToken cancellationToken) private
Runner for JobHandlers.
Parameters
job The Job being run. Must be fully populated.
operation The JobEntrypoint for the job .
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Definition at line 361 of file JobService.cs.
        {
            var jid = job.Require(x => x.Id);
            using (LogContext.PushProperty(SerilogContextHelper.JobIdContextProperty, jid))
                try
                {
                    void LogException(Exception ex) => logger.LogDebug(ex, "Job {jobId} exited with error!", jid);
                    var hubUpdatesTask = Task.CompletedTask;
                    var result = false;
                    var firstLogHappened = false;
                    var hubGroupName = JobsHub.HubGroupName(job);
                    Stopwatch? stopwatch = null;
                    void QueueHubUpdate(JobResponse update, bool final)
                    {
                        void NextUpdate(bool bypassRate)
{
                            var currentUpdatesTask = hubUpdatesTask;
                            async Task ChainHubUpdate()
{
                                await currentUpdatesTask;
                                if (!firstLogHappened)
{
                                    logger.LogTrace("Sending updates for job {id} to hub group {group}", jid, hubGroupName);
                                    firstLogHappened = true;
                                }
                                // DCT: Cancellation token is for job, operation should always run
                                await hub
                                    .Clients
                                    .Group(hubGroupName)
                                    .ReceiveJobUpdate(update, CancellationToken.None);
                            }
                            Stopwatch? enteredLock = null;
                            try
{
                                if (!bypassRate && stopwatch != null)
{
                                    Monitor.Enter(stopwatch);
                                    enteredLock = stopwatch;
                                    if (stopwatch.ElapsedMilliseconds * MaxHubUpdatesPerSecond < 1)
                                        return; // don't spam client
                                }
                                hubUpdatesTask = ChainHubUpdate();
                                stopwatch = Stopwatch.StartNew();
                            }
                            finally
{
                                if (enteredLock != null)
                                    Monitor.Exit(enteredLock);
                            }
                        }
                        lock (hubUpdateActions)
                            if (final)
                                hubUpdateActions.Remove(jid);
                            else
                                hubUpdateActions[jid] = () => NextUpdate(true);
                        NextUpdate(false);
                    }
                    try
                    {
                        void UpdateProgress(string? stage, double? progress)
{
                            if (progress.HasValue
                                && (progress.Value < 0 || progress.Value > 1))
{
                                var exception = new ArgumentOutOfRangeException(nameof(progress), progress, "Progress must be a value from 0-1!");
                                logger.LogError(exception, "Invalid progress value!");
                                return;
                            }
                            int? newProgress = progress.HasValue ? (int)Math.Floor(progress.Value * 100) : null;
                            lock (synchronizationLock)
                                if (jobs.TryGetValue(jid, out var handler))
{
                                    handler.Stage = stage;
                                    handler.Progress = newProgress;
                                    var updatedJob = job.ToApi();
                                    updatedJob.Stage = stage;
                                    updatedJob.Progress = newProgress;
                                    QueueHubUpdate(updatedJob, false);
                                }
                        }
                        var activationTask = activationTcs.Task;
                        Debug.Assert(activationTask.IsCompleted || job.Require(x => x.JobCode).IsServerStartupJob(), "Non-server startup job registered before activation!");
                        var instanceCoreProvider = await activationTask.WaitAsync(cancellationToken);
                        QueueHubUpdate(job.ToApi(), false);
                        logger.LogTrace("Starting job...");
                        await operation(
                            instanceCoreProvider.GetInstance(job.Instance!),
                            databaseContextFactory,
                            job,
                            new JobProgressReporter(
                                loggerFactory.CreateLogger<JobProgressReporter>(),
                                null,
                                UpdateProgress),
                            cancellationToken);
                        logger.LogDebug("Job {jobId} completed!", job.Id);
                        result = true;
                    }
                    catch (OperationCanceledException ex)
                    {
                        logger.LogDebug(ex, "Job {jobId} cancelled!", job.Id);
                        job.Cancelled = true;
                    }
                    catch (JobException e)
                    {
                        job.ErrorCode = e.ErrorCode;
                        job.ExceptionDetails = String.IsNullOrWhiteSpace(e.Message) ? e.InnerException?.Message : e.Message + $" (Inner exception: {e.InnerException?.Message})";
                        LogException(e);
                    }
                    catch (Exception e)
                    {
                        job.ExceptionDetails = e.ToString();
                        LogException(e);
                    }
                    try
                    {
                        await databaseContextFactory.UseContext(async databaseContext =>
{
                            var attachedJob = new Job(jid);
                            databaseContext.Jobs.Attach(attachedJob);
                            attachedJob.StoppedAt = DateTimeOffset.UtcNow;
                            attachedJob.ExceptionDetails = job.ExceptionDetails;
                            attachedJob.ErrorCode = job.ErrorCode;
                            attachedJob.Cancelled = job.Cancelled;
                            // DCT: Cancellation token is for job, operation should always run
                            await databaseContext.Save(CancellationToken.None);
                        });
                        // Resetting the context here because I CBA to worry if the cache is being used
                        await databaseContextFactory.UseContext(async databaseContext =>
{
                            // Cancellation might be set in another async context
                            // Also, startedby could have been renamed
                            // forced to reload here for the final hub update
                            // DCT: Cancellation token is for job, operation should always run
                            var finalJob = await databaseContext
                                .Jobs
                                .AsQueryable()
                                .Include(x => x.Instance)
                                .Include(x => x.StartedBy)
                                .Include(x => x.CancelledBy)
                                .Where(dbJob => dbJob.Id == jid)
                                .FirstAsync(CancellationToken.None);
                            QueueHubUpdate(finalJob.ToApi(), true);
                        });
                    }
                    catch
                    {
                        lock (hubUpdateActions)
                            hubUpdateActions.Remove(jid);
                        throw;
                    }
                    try
                    {
                        await hubUpdatesTask;
                    }
                    catch (Exception ex)
                    {
                        logger.LogError(ex, "Error in hub updates chain task!");
                    }
                    return result;
                }
                finally
                {
                    lock (synchronizationLock)
                    {
                        var handler = jobs[jid];
                        jobs.Remove(jid);
                        handler.Dispose();
                    }
                }
        }
References Tgstation.Server.Api.Models.Internal.Job.Cancelled, Tgstation.Server.Api.Models.Internal.Job.ErrorCode, Tgstation.Server.Host.Jobs.JobException.ErrorCode, Tgstation.Server.Api.Models.Internal.Job.ExceptionDetails, Tgstation.Server.Host.Jobs.JobsHub.HubGroupName(), Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Host.Models.Job.Instance, Tgstation.Server.Host.Utils.SerilogContextHelper.JobIdContextProperty, and Tgstation.Server.Host.Models.Job.ToApi().
Referenced by Tgstation.Server.Host.Jobs.JobService.RegisterOperation().
SetJobProgress()
void Tgstation.Server.Host.Jobs.JobService.SetJobProgress (JobResponse apiResponse)
Set the JobResponse.Progress and JobResponse.Stage for a given apiResponse .
Parameters
apiResponse The JobResponse to update.
Implements Tgstation.Server.Host.Jobs.IJobManager.
Definition at line 293 of file JobService.cs.
        {
            ArgumentNullException.ThrowIfNull(apiResponse);
            lock (synchronizationLock)
            {
                if (!jobs.TryGetValue(apiResponse.Require(x => x.Id), out var handler))
                    return;
                apiResponse.Progress = handler.Progress;
                apiResponse.Stage = handler.Stage;
            }
        }
StartAsync()
Task Tgstation.Server.Host.Jobs.JobService.StartAsync (CancellationToken cancellationToken)
StopAsync()
Task Tgstation.Server.Host.Jobs.JobService.StopAsync (CancellationToken cancellationToken)
Definition at line 221 of file JobService.cs.
        {
            List<ValueTask<Job?>> joinTasks;
            lock (addCancelLock)
                lock (synchronizationLock)
                {
                    noMoreJobsShouldStart = true;
                    joinTasks = jobs.Select(x => CancelJob(
                        new Job(x.Key),
                        null,
                        true,
                        cancellationToken))
                        .ToList();
                }
            return ValueTaskExtensions.WhenAll(joinTasks).AsTask();
        }
References Tgstation.Server.Common.Extensions.ValueTaskExtensions.WhenAll().
WaitForJobCompletion()
async ValueTask< bool?> Tgstation.Server.Host.Jobs.JobService.WaitForJobCompletion (Job job, User? canceller, CancellationToken jobCancellationToken, CancellationToken cancellationToken)
Wait for a given job to complete.
Parameters
job The Job to wait for.
canceller The User to cancel the job . If null the TGS user will be used.
jobCancellationToken A CancellationToken that will cancel the job .
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> representing the Job. Results in true if the Job completed without errors, false if errors occurred, or null if the job isn't registered.
Implements Tgstation.Server.Host.Jobs.IJobManager.
Definition at line 306 of file JobService.cs.
        {
            ArgumentNullException.ThrowIfNull(job);
            if (!cancellationToken.CanBeCanceled)
                throw new ArgumentException("A cancellable CancellationToken should be provided!", nameof(cancellationToken));
            JobHandler? handler;
            bool noMoreJobsShouldStart;
            lock (synchronizationLock)
            {
                if (!jobs.TryGetValue(job.Require(x => x.Id), out handler))
                    return null;
                noMoreJobsShouldStart = this.noMoreJobsShouldStart;
            }
            if (noMoreJobsShouldStart && !handler.Started)
                await Extensions.TaskExtensions.InfiniteTask.WaitAsync(cancellationToken);
            var cancelTask = ValueTask.FromResult<Job?>(null);
            bool result;
            using (jobCancellationToken.Register(() => cancelTask = CancelJob(job, canceller, true, cancellationToken)))
                result = await handler.Wait(cancellationToken);
            await cancelTask;
            return result;
        }
References Tgstation.Server.Host.Jobs.JobHandler.Started, and Tgstation.Server.Host.Jobs.JobHandler.Wait().
Member Data Documentation
activationTcs
readonly TaskCompletionSource<IInstanceCoreProvider> Tgstation.Server.Host.Jobs.JobService.activationTcs private
TaskCompletionSource<TResult> to delay starting jobs until the server is ready.
Definition at line 68 of file JobService.cs.
Referenced by Tgstation.Server.Host.Jobs.JobService.JobService().
addCancelLock
readonly object Tgstation.Server.Host.Jobs.JobService.addCancelLock private
Prevents a really REALLY rare race condition between add and cancel operations.
Definition at line 78 of file JobService.cs.
Referenced by Tgstation.Server.Host.Jobs.JobService.JobService(), and Tgstation.Server.Host.Jobs.JobService.RegisterOperation().
databaseContextFactory
readonly IDatabaseContextFactory Tgstation.Server.Host.Jobs.JobService.databaseContextFactory private
The IServiceProvider for the JobService.
Definition at line 43 of file JobService.cs.
Referenced by Tgstation.Server.Host.Jobs.JobService.JobService(), and Tgstation.Server.Host.Jobs.JobService.RegisterOperation().
hub
readonly IConnectionMappedHubContext<JobsHub, IJobsHub> Tgstation.Server.Host.Jobs.JobService.hub private
The IHubContext for the JobsHub.
Definition at line 38 of file JobService.cs.
Referenced by Tgstation.Server.Host.Jobs.JobService.JobService().
hubUpdateActions
readonly Dictionary<long, Action> Tgstation.Server.Host.Jobs.JobService.hubUpdateActions private
Dictionary<TKey, TValue> of running Job Api.Models.EntityId.Ids to Actions that will push immediate hub updates.
Definition at line 63 of file JobService.cs.
Referenced by Tgstation.Server.Host.Jobs.JobService.JobService().
jobs
readonly Dictionary<long, JobHandler> Tgstation.Server.Host.Jobs.JobService.jobs private
Dictionary<TKey, TValue> of Job Api.Models.EntityId.Ids to running JobHandlers.
Definition at line 58 of file JobService.cs.
Referenced by Tgstation.Server.Host.Jobs.JobService.Dispose(), Tgstation.Server.Host.Jobs.JobService.JobService(), and Tgstation.Server.Host.Jobs.JobService.RegisterOperation().
logger
readonly ILogger<JobService> Tgstation.Server.Host.Jobs.JobService.logger private
The ILogger for the JobService.
Definition at line 53 of file JobService.cs.
Referenced by Tgstation.Server.Host.Jobs.JobService.JobService(), and Tgstation.Server.Host.Jobs.JobService.RegisterOperation().
loggerFactory
readonly ILoggerFactory Tgstation.Server.Host.Jobs.JobService.loggerFactory private
The ILoggerFactory for the JobService.
Definition at line 48 of file JobService.cs.
Referenced by Tgstation.Server.Host.Jobs.JobService.JobService().
MaxHubUpdatesPerSecond
const int Tgstation.Server.Host.Jobs.JobService.MaxHubUpdatesPerSecond = 1 static private
The maximum rate at which hub clients can receive updates.
Definition at line 33 of file JobService.cs.
noMoreJobsShouldStart
volatile bool Tgstation.Server.Host.Jobs.JobService.noMoreJobsShouldStart private
Prevents jobs that are registered after shutdown from activating.
Definition at line 83 of file JobService.cs.
Referenced by Tgstation.Server.Host.Jobs.JobService.RegisterOperation().
synchronizationLock
readonly object Tgstation.Server.Host.Jobs.JobService.synchronizationLock private
lock object for various operations.
Definition at line 73 of file JobService.cs.
Referenced by Tgstation.Server.Host.Jobs.JobService.JobService(), and Tgstation.Server.Host.Jobs.JobService.RegisterOperation().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Jobs/JobService.cs