tgstation-server: Tgstation.Server.Client.CachedResponseStream Class Reference
Tgstation.Server.Client.CachedResponseStream Class Reference
Caches the Stream from a HttpResponseMessage for later use.
Public Member Functions
override void Flush ()
override int Read (byte[] buffer, int offset, int count)
override long Seek (long offset, SeekOrigin origin)
override void SetLength (long value)
override void Write (byte[] buffer, int offset, int count)
Static Public Member Functions
static async Task< CachedResponseStream > Create (HttpResponseMessage response)
Asyncronously creates a new CachedResponseStream.
Protected Member Functions
override void Dispose (bool disposing)
Properties
override bool CanRead [get]
override bool CanSeek [get]
override bool CanWrite [get]
override long Length [get]
override long Position [get, set]
Private Member Functions
CachedResponseStream (HttpResponseMessage response, Stream responseStream)
Initializes a new instance of the CachedResponseStream class.
Private Attributes
readonly HttpResponseMessage response
The HttpResponseMessage for the CachedResponseStream.
readonly Stream responseStream
The reponse content Stream.
Detailed Description
Caches the Stream from a HttpResponseMessage for later use.
Definition at line 10 of file CachedResponseStream.cs.
Constructor & Destructor Documentation
CachedResponseStream()
Tgstation.Server.Client.CachedResponseStream.CachedResponseStream (HttpResponseMessage response, Stream responseStream) private
Initializes a new instance of the CachedResponseStream class.
Parameters
response The value of response.
responseStream The value of responseStream.
Definition at line 82 of file CachedResponseStream.cs.
        {
            this.response = response;
            this.responseStream = responseStream;
        }
References Tgstation.Server.Client.CachedResponseStream.response, and Tgstation.Server.Client.CachedResponseStream.responseStream.
Referenced by Tgstation.Server.Client.CachedResponseStream.Create().
Member Function Documentation
Create()
static async Task< CachedResponseStream > Tgstation.Server.Client.CachedResponseStream.Create (HttpResponseMessage response) static
Asyncronously creates a new CachedResponseStream.
Parameters
response The HttpResponseMessage to build from.
Returns
A Task<TResult> resulting in a new CachedResponseStream.
Definition at line 27 of file CachedResponseStream.cs.
        {
            var stream = await response.Content.ReadAsStreamAsync().ConfigureAwait(false);
            return new CachedResponseStream(response, stream);
        }
References Tgstation.Server.Client.CachedResponseStream.CachedResponseStream(), and Tgstation.Server.Client.CachedResponseStream.response.
Referenced by Tgstation.Server.Client.ApiClient.RunRequest< TResult >().
Dispose()
override void Tgstation.Server.Client.CachedResponseStream.Dispose (bool disposing) protected
Definition at line 68 of file CachedResponseStream.cs.
        {
            base.Dispose(disposing);
            if (!disposing)
                return;
            responseStream.Dispose();
            response.Dispose();
        }
References Tgstation.Server.Client.CachedResponseStream.response, and Tgstation.Server.Client.CachedResponseStream.responseStream.
Flush()
override void Tgstation.Server.Client.CachedResponseStream.Flush ()
Read()
override int Tgstation.Server.Client.CachedResponseStream.Read (byte[] buffer, int offset, int count)
Seek()
override long Tgstation.Server.Client.CachedResponseStream.Seek (long offset, SeekOrigin origin)
SetLength()
override void Tgstation.Server.Client.CachedResponseStream.SetLength (long value)
Write()
override void Tgstation.Server.Client.CachedResponseStream.Write (byte[] buffer, int offset, int count)
Member Data Documentation
response
readonly HttpResponseMessage Tgstation.Server.Client.CachedResponseStream.response private
The HttpResponseMessage for the CachedResponseStream.
Definition at line 15 of file CachedResponseStream.cs.
Referenced by Tgstation.Server.Client.CachedResponseStream.CachedResponseStream(), Tgstation.Server.Client.CachedResponseStream.Create(), and Tgstation.Server.Client.CachedResponseStream.Dispose().
responseStream
readonly Stream Tgstation.Server.Client.CachedResponseStream.responseStream private
The reponse content Stream.
Definition at line 20 of file CachedResponseStream.cs.
Referenced by Tgstation.Server.Client.CachedResponseStream.CachedResponseStream(), and Tgstation.Server.Client.CachedResponseStream.Dispose().
Property Documentation
CanRead
override bool Tgstation.Server.Client.CachedResponseStream.CanRead get
Definition at line 34 of file CachedResponseStream.cs.
CanSeek
override bool Tgstation.Server.Client.CachedResponseStream.CanSeek get
Definition at line 37 of file CachedResponseStream.cs.
CanWrite
override bool Tgstation.Server.Client.CachedResponseStream.CanWrite get
Definition at line 40 of file CachedResponseStream.cs.
Length
override long Tgstation.Server.Client.CachedResponseStream.Length get
Definition at line 43 of file CachedResponseStream.cs.
Position
override long Tgstation.Server.Client.CachedResponseStream.Position get set
Definition at line 46 of file CachedResponseStream.cs.
        {
            get => responseStream.Position;
            set => responseStream.Position = value;
        }
The documentation for this class was generated from the following file:
src/Tgstation.Server.Client/CachedResponseStream.cs