tgstation-server: Tgstation.Server.Host.Core.Application Class Reference
Tgstation.Server.Host.Core.Application Class Reference sealed
Sets up dependency injection.
Public Member Functions
Application (IConfiguration configuration, IWebHostEnvironment hostingEnvironment)
Initializes a new instance of the Application class.
void ConfigureServices (IServiceCollection services, IAssemblyInformationProvider assemblyInformationProvider, IIOManager ioManager, IPostSetupServices postSetupServices)
Configure the Application's services .
void Configure (IApplicationBuilder applicationBuilder, IServerControl serverControl, ITokenFactory tokenFactory, IServerPortProvider serverPortProvider, IAssemblyInformationProvider assemblyInformationProvider, IOptions< ControlPanelConfiguration > controlPanelConfigurationOptions, IOptions< GeneralConfiguration > generalConfigurationOptions, IOptions< SwarmConfiguration > swarmConfigurationOptions, IOptions< InternalConfiguration > internalConfigurationOptions, ILogger< Application > logger)
Configure the Application.
Public Member Functions inherited from Tgstation.Server.Host.Setup.SetupApplication
SetupApplication (IConfiguration configuration)
Initializes a new instance of the SetupApplication class.
void ConfigureServices (IServiceCollection services, IAssemblyInformationProvider assemblyInformationProvider, IIOManager ioManager)
Configure dependency injected services.
Static Public Member Functions
static IServerFactory CreateDefaultServerFactory ()
Create the default IServerFactory.
Protected Member Functions
override void ConfigureHostedService (IServiceCollection services)
Configures the IHostedService.
Parameters
services The IServiceCollection to configure.
Private Member Functions
void ConfigureAuthenticationPipeline (IServiceCollection services)
Configure the services for the authentication pipeline.
Static Private Member Functions
static void AddWatchdog< TSystemWatchdogFactory > (IServiceCollection services, IPostSetupServices postSetupServices)
Adds the IWatchdogFactory implementation.
Private Attributes
readonly IWebHostEnvironment hostingEnvironment
The IWebHostEnvironment for the Application.
ITokenFactory? tokenFactory
The ITokenFactory for the Application.
Additional Inherited Members
Properties inherited from Tgstation.Server.Host.Setup.SetupApplication
IConfiguration Configuration [get]
The IConfiguration for the SetupApplication.
Detailed Description
Sets up dependency injection.
Definition at line 82 of file Application.cs.
Constructor & Destructor Documentation
Application()
Tgstation.Server.Host.Core.Application.Application (IConfiguration configuration, IWebHostEnvironment hostingEnvironment)
Initializes a new instance of the Application class.
Parameters
configuration The IConfiguration for the SetupApplication.
hostingEnvironment The IWebHostEnvironment for the SetupApplication.
Definition at line 127 of file Application.cs.
            : base(configuration)
        {
            this.hostingEnvironment = hostingEnvironment ?? throw new ArgumentNullException(nameof(hostingEnvironment));
        }
References Tgstation.Server.Host.Core.Application.hostingEnvironment.
Member Function Documentation
AddWatchdog< TSystemWatchdogFactory >()
static void Tgstation.Server.Host.Core.Application.AddWatchdog< TSystemWatchdogFactory > (IServiceCollection services, IPostSetupServices postSetupServices) static private
Adds the IWatchdogFactory implementation.
Template Parameters
TSystemWatchdogFactory The WatchdogFactory child class for the current system.
Parameters
services The IServiceCollection to configure.
postSetupServices The IPostSetupServices to use.
Type Constraints
TSystemWatchdogFactory : class
TSystemWatchdogFactory : IWatchdogFactory
Definition at line 113 of file Application.cs.
                                         : class, IWatchdogFactory
        {
            if (postSetupServices.GeneralConfiguration.UseBasicWatchdog)
                services.AddSingleton<IWatchdogFactory, WatchdogFactory>();
            else
                services.AddSingleton<IWatchdogFactory, TSystemWatchdogFactory>();
        }
Configure()
void Tgstation.Server.Host.Core.Application.Configure (IApplicationBuilder applicationBuilder, IServerControl serverControl, ITokenFactory tokenFactory, IServerPortProvider serverPortProvider, IAssemblyInformationProvider assemblyInformationProvider, IOptions< ControlPanelConfiguration > controlPanelConfigurationOptions, IOptions< GeneralConfiguration > generalConfigurationOptions, IOptions< SwarmConfiguration > swarmConfigurationOptions, IOptions< InternalConfiguration > internalConfigurationOptions, ILogger< Application > logger)
Configure the Application.
Parameters
applicationBuilder The IApplicationBuilder to configure.
serverControl The IServerControl for the Application.
tokenFactory The value of tokenFactory.
serverPortProvider The IServerPortProvider.
assemblyInformationProvider The IAssemblyInformationProvider.
controlPanelConfigurationOptions The IOptions<TOptions> containing the ControlPanelConfiguration to use.
generalConfigurationOptions The IOptions<TOptions> containing the GeneralConfiguration to use.
swarmConfigurationOptions The IOptions<TOptions> containing the SwarmConfiguration to use.
internalConfigurationOptions The IOptions<TOptions> containing the InternalConfiguration to use.
logger The Microsoft.Extensions.Logging.ILogger for the Application.
Definition at line 530 of file Application.cs.
        {
            ArgumentNullException.ThrowIfNull(applicationBuilder);
            ArgumentNullException.ThrowIfNull(serverControl);
            this.tokenFactory = tokenFactory ?? throw new ArgumentNullException(nameof(tokenFactory));
            ArgumentNullException.ThrowIfNull(serverPortProvider);
            ArgumentNullException.ThrowIfNull(assemblyInformationProvider);
            var controlPanelConfiguration = controlPanelConfigurationOptions?.Value ?? throw new ArgumentNullException(nameof(controlPanelConfigurationOptions));
            var generalConfiguration = generalConfigurationOptions?.Value ?? throw new ArgumentNullException(nameof(generalConfigurationOptions));
            var swarmConfiguration = swarmConfigurationOptions?.Value ?? throw new ArgumentNullException(nameof(swarmConfigurationOptions));
            var internalConfiguration = internalConfigurationOptions?.Value ?? throw new ArgumentNullException(nameof(internalConfigurationOptions));
            ArgumentNullException.ThrowIfNull(logger);
            logger.LogDebug("Content Root: {contentRoot}", hostingEnvironment.ContentRootPath);
            logger.LogTrace("Web Root: {webRoot}", hostingEnvironment.WebRootPath);
            // setup the HTTP request pipeline
            // Add additional logging context to the request
            applicationBuilder.UseAdditionalRequestLoggingContext(swarmConfiguration);
            // Wrap exceptions in a 500 (ErrorMessage) response
            applicationBuilder.UseServerErrorHandling();
            // Add the X-Powered-By response header
            applicationBuilder.UseServerBranding(assemblyInformationProvider);
            // Add the X-Accel-Buffering response header
            applicationBuilder.UseDisabledNginxProxyBuffering();
            // suppress OperationCancelledExceptions, they are just aborted HTTP requests
            applicationBuilder.UseCancelledRequestSuppression();
            // 503 requests made while the application is starting
            applicationBuilder.UseAsyncInitialization<IInstanceManager>(
                (instanceManager, cancellationToken) => instanceManager.Ready.WaitAsync(cancellationToken));
            if (generalConfiguration.HostApiDocumentation)
            {
                var siteDocPath = Routes.ApiRoot + $"doc/{SwaggerConfiguration.DocumentName}.json";
                if (!String.IsNullOrWhiteSpace(controlPanelConfiguration.PublicPath))
                    siteDocPath = controlPanelConfiguration.PublicPath.TrimEnd('/') + siteDocPath;
                applicationBuilder.UseSwagger(options =>
                {
                    options.RouteTemplate = Routes.ApiRoot + "doc/{documentName}.{json|yaml}";
                });
                applicationBuilder.UseSwaggerUI(options =>
                {
                    options.RoutePrefix = SwaggerConfiguration.DocumentationSiteRouteExtension;
                    options.SwaggerEndpoint(siteDocPath, "TGS API");
                });
                logger.LogTrace("Swagger API generation enabled");
            }
            // spa loading if necessary
            if (controlPanelConfiguration.Enable)
            {
                logger.LogInformation("Web control panel enabled.");
                applicationBuilder.UseFileServer(new FileServerOptions
                {
                    RequestPath = ControlPanelController.ControlPanelRoute,
                    EnableDefaultFiles = true,
                    EnableDirectoryBrowsing = false,
                    RedirectToAppendTrailingSlash = false,
                });
            }
            else
#if NO_WEBPANEL
                logger.LogDebug("Web control panel was not included in TGS build!");
#else
                logger.LogTrace("Web control panel disabled!");
#endif
            // Enable endpoint routing
            applicationBuilder.UseRouting();
            // Set up CORS based on configuration if necessary
            Action<CorsPolicyBuilder>? corsBuilder = null;
            if (controlPanelConfiguration.AllowAnyOrigin)
            {
                logger.LogTrace("Access-Control-Allow-Origin: *");
                corsBuilder = builder => builder.SetIsOriginAllowed(_ => true);
            }
            else if (controlPanelConfiguration.AllowedOrigins?.Count > 0)
            {
                logger.LogTrace("Access-Control-Allow-Origin: {allowedOrigins}", String.Join(',', controlPanelConfiguration.AllowedOrigins));
                corsBuilder = builder => builder.WithOrigins([.. controlPanelConfiguration.AllowedOrigins]);
            }
            var originalBuilder = corsBuilder;
            corsBuilder = builder =>
            {
                builder
                    .AllowAnyHeader()
                    .AllowAnyMethod()
                    .AllowCredentials()
                    .SetPreflightMaxAge(TimeSpan.FromDays(1));
                originalBuilder?.Invoke(builder);
            };
            applicationBuilder.UseCors(corsBuilder);
            // validate the API version
            applicationBuilder.UseApiCompatibility();
            // authenticate JWT tokens using our security pipeline if present, returns 401 if bad
            applicationBuilder.UseAuthentication();
            // enable authorization on endpoints
            applicationBuilder.UseAuthorization();
            // suppress and log database exceptions
            applicationBuilder.UseDbConflictHandling();
            // setup endpoints
            applicationBuilder.UseEndpoints(endpoints =>
            {
                // access to the signalR jobs hub
                endpoints.MapHub<JobsHub>(
                    Routes.JobsHub,
                    options =>
                    {
                        options.Transports = HttpTransportType.ServerSentEvents;
                        options.CloseOnAuthenticationExpiration = true;
                    })
                    .RequireAuthorization()
                    .RequireCors(corsBuilder);
                // majority of handling is done in the controllers
                endpoints.MapControllers();
                if (internalConfiguration.EnableGraphQL)
                {
                    logger.LogWarning("Enabling GraphQL. This API is experimental and breaking changes may occur at any time!");
                    var gqlOptions = new GraphQLServerOptions
                    {
                        EnableBatching = true,
                    };
                    gqlOptions.Tool.Enable = generalConfiguration.HostApiDocumentation;
                    endpoints
                        .MapGraphQL(Routes.GraphQL)
                        .WithOptions(gqlOptions);
                }
            });
            // 404 anything that gets this far
            // End of request pipeline setup
            logger.LogTrace("Configuration version: {configVersion}", GeneralConfiguration.CurrentConfigVersion);
            logger.LogTrace("DMAPI Interop version: {interopVersion}", DMApiConstants.InteropVersion);
            if (controlPanelConfiguration.Enable)
                logger.LogTrace("Webpanel version: {webCPVersion}", MasterVersionsAttribute.Instance.RawWebpanelVersion);
            logger.LogDebug("Starting hosting on port {httpApiPort}...", serverPortProvider.HttpApiPort);
        }
References Tgstation.Server.Host.Controllers.ControlPanelController.ControlPanelRoute, Tgstation.Server.Host.Configuration.GeneralConfiguration.CurrentConfigVersion, Tgstation.Server.Host.Utils.SwaggerConfiguration.DocumentationSiteRouteExtension, Tgstation.Server.Api.Routes.GraphQL, Tgstation.Server.Host.Core.Application.hostingEnvironment, Tgstation.Server.Host.Core.IServerPortProvider.HttpApiPort, Tgstation.Server.Host.Properties.MasterVersionsAttribute.Instance, Tgstation.Server.Host.Components.Interop.DMApiConstants.InteropVersion, Tgstation.Server.Api.Routes.JobsHub, Tgstation.Server.Host.Properties.MasterVersionsAttribute.RawWebpanelVersion, Tgstation.Server.Host.Components.IInstanceManager.Ready, and Tgstation.Server.Host.Core.Application.tokenFactory.
ConfigureAuthenticationPipeline()
void Tgstation.Server.Host.Core.Application.ConfigureAuthenticationPipeline (IServiceCollection services) private
Configure the services for the authentication pipeline.
Parameters
services The IServiceCollection to configure.
Definition at line 708 of file Application.cs.
        {
            services.AddHttpContextAccessor();
            services.AddScoped<IApiHeadersProvider, ApiHeadersProvider>();
            services.AddScoped<AuthenticationContextFactory>();
            services.AddScoped<ITokenValidator>(provider => provider.GetRequiredService<AuthenticationContextFactory>());
            // what if you
            // wanted to just do this:
            // return provider.GetRequiredService<AuthenticationContextFactory>().CurrentAuthenticationContext
            // But M$ said
            // https://stackoverflow.com/questions/56792917/scoped-services-in-asp-net-core-with-signalr-hubs
            services.AddScoped(provider => (provider
                .GetRequiredService<IHttpContextAccessor>()
                .HttpContext ?? throw new InvalidOperationException($"Unable to resolve {nameof(IAuthenticationContext)} due to no HttpContext being available!"))
                .RequestServices
                .GetRequiredService<AuthenticationContextFactory>()
                .CurrentAuthenticationContext);
            services.AddScoped<IClaimsTransformation, AuthenticationContextClaimsTransformation>();
            services
                .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                .AddJwtBearer(jwtBearerOptions =>
                {
                    // this line isn't actually run until the first request is made
                    // at that point tokenFactory will be populated
                    jwtBearerOptions.TokenValidationParameters = tokenFactory?.ValidationParameters ?? throw new InvalidOperationException("tokenFactory not initialized!");
                    jwtBearerOptions.MapInboundClaims = false;
                    jwtBearerOptions.Events = new JwtBearerEvents
                    {
                        OnMessageReceived = context =>
{
                            if (String.IsNullOrWhiteSpace(context.Token))
{
                                var accessToken = context.Request.Query["access_token"];
                                var path = context.HttpContext.Request.Path;
                                if (!String.IsNullOrWhiteSpace(accessToken) &&
                                    path.StartsWithSegments(Routes.HubsRoot, StringComparison.OrdinalIgnoreCase))
{
                                    context.Token = accessToken;
                                }
                            }
                            return Task.CompletedTask;
                        },
                        OnTokenValidated = context => context
                            .HttpContext
                            .RequestServices
                            .GetRequiredService<ITokenValidator>()
                            .ValidateToken(
                                context,
                                context
                                    .HttpContext
                                    .RequestAborted),
                    };
                });
        }
References Tgstation.Server.Api.Routes.HubsRoot, Tgstation.Server.Host.Core.Application.tokenFactory, and Tgstation.Server.Host.Security.ITokenFactory.ValidationParameters.
Referenced by Tgstation.Server.Host.Core.Application.ConfigureServices().
ConfigureHostedService()
override void Tgstation.Server.Host.Core.Application.ConfigureHostedService (IServiceCollection services) protected virtual
Configures the IHostedService.
Parameters
services The IServiceCollection to configure.
Reimplemented from Tgstation.Server.Host.Setup.SetupApplication.
ConfigureServices()
void Tgstation.Server.Host.Core.Application.ConfigureServices (IServiceCollection services, IAssemblyInformationProvider assemblyInformationProvider, IIOManager ioManager, IPostSetupServices postSetupServices)
Configure the Application's services .
Parameters
services The IServiceCollection to configure.
assemblyInformationProvider The IAssemblyInformationProvider needed for configuration.
ioManager The IIOManager needed for configuration.
postSetupServices The IPostSetupServices needed for configuration.
Definition at line 142 of file Application.cs.
        {
            ConfigureServices(services, assemblyInformationProvider, ioManager);
            ArgumentNullException.ThrowIfNull(postSetupServices);
            // configure configuration
            services.UseStandardConfig<UpdatesConfiguration>(Configuration);
            services.UseStandardConfig<ControlPanelConfiguration>(Configuration);
            services.UseStandardConfig<SwarmConfiguration>(Configuration);
            services.UseStandardConfig<SessionConfiguration>(Configuration);
            services.UseStandardConfig<TelemetryConfiguration>(Configuration);
            // enable options which give us config reloading
            services.AddOptions();
            // Set the timeout for IHostedService.StopAsync
            services.Configure<HostOptions>(
                opts => opts.ShutdownTimeout = TimeSpan.FromMinutes(postSetupServices.GeneralConfiguration.RestartTimeoutMinutes));
            static LogEventLevel? ConvertSeriLogLevel(LogLevel logLevel) =>
                logLevel switch
                {
                    LogLevel.Critical => LogEventLevel.Fatal,
                    LogLevel.Debug => LogEventLevel.Debug,
                    LogLevel.Error => LogEventLevel.Error,
                    LogLevel.Information => LogEventLevel.Information,
                    LogLevel.Trace => LogEventLevel.Verbose,
                    LogLevel.Warning => LogEventLevel.Warning,
                    LogLevel.None => null,
                    _ => throw new InvalidOperationException(String.Format(CultureInfo.InvariantCulture, "Invalid log level {0}", logLevel)),
                };
            var microsoftEventLevel = ConvertSeriLogLevel(postSetupServices.FileLoggingConfiguration.MicrosoftLogLevel);
            var elasticsearchConfiguration = postSetupServices.ElasticsearchConfiguration;
            services.SetupLogging(
                config =>
                {
                    if (microsoftEventLevel.HasValue)
                    {
                        config.MinimumLevel.Override("Microsoft", microsoftEventLevel.Value);
                        config.MinimumLevel.Override("System.Net.Http.HttpClient", microsoftEventLevel.Value);
                    }
                },
                sinkConfig =>
                {
                    if (postSetupServices.FileLoggingConfiguration.Disable)
                        return;
                    var logPath = postSetupServices.FileLoggingConfiguration.GetFullLogDirectory(
                        ioManager,
                        assemblyInformationProvider,
                        postSetupServices.PlatformIdentifier);
                    var logEventLevel = ConvertSeriLogLevel(postSetupServices.FileLoggingConfiguration.LogLevel);
                    var formatter = new MessageTemplateTextFormatter(
                        "{Timestamp:o} "
                        + SerilogContextHelper.Template
                        + "): [{Level:u3}] {SourceContext:l}: {Message} ({EventId:x8}){NewLine}{Exception}",
                        null);
                    logPath = ioManager.ConcatPath(logPath, "tgs-.log");
                    var rollingFileConfig = sinkConfig.File(
                        formatter,
                        logPath,
                        logEventLevel ?? LogEventLevel.Verbose,
                        50 * 1024 * 1024, // 50MB max size
                        flushToDiskInterval: TimeSpan.FromSeconds(2),
                        rollingInterval: RollingInterval.Day,
                        rollOnFileSizeLimit: true);
                },
                elasticsearchConfiguration.Enable
                    ? new ElasticsearchSinkOptions(elasticsearchConfiguration.Host ?? throw new InvalidOperationException($"Missing {ElasticsearchConfiguration.Section}:{nameof(elasticsearchConfiguration.Host)}!"))
                    {
                        // Yes I know this means they cannot use a self signed cert unless they also have authentication, but lets be real here
                        // No one is going to be doing one of those but not the other
                        ModifyConnectionSettings = connectionConfigration => (!String.IsNullOrWhiteSpace(elasticsearchConfiguration.Username) && !String.IsNullOrWhiteSpace(elasticsearchConfiguration.Password))
                            ? connectionConfigration
                                .BasicAuthentication(
                                    elasticsearchConfiguration.Username,
                                    elasticsearchConfiguration.Password)
                                .ServerCertificateValidationCallback((o, certificate, chain, errors) => true)
                            : null,
                        CustomFormatter = new EcsTextFormatter(),
                        AutoRegisterTemplate = true,
                        AutoRegisterTemplateVersion = AutoRegisterTemplateVersion.ESv7,
                        IndexFormat = "tgs-logs",
                    }
                    : null,
                postSetupServices.InternalConfiguration,
                postSetupServices.FileLoggingConfiguration);
            // configure authentication pipeline
            ConfigureAuthenticationPipeline(services);
            // add mvc, configure the json serializer settings
            var jsonVersionConverterList = new List<JsonConverter>
            {
                new VersionConverter(),
            };
            void ConfigureNewtonsoftJsonSerializerSettingsForApi(JsonSerializerSettings settings)
            {
                settings.NullValueHandling = NullValueHandling.Ignore;
                settings.CheckAdditionalContent = true;
                settings.MissingMemberHandling = MissingMemberHandling.Error;
                settings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
                settings.Converters = jsonVersionConverterList;
            }
            services
                .AddMvc(options =>
                {
                    options.ReturnHttpNotAcceptable = true;
                    options.RespectBrowserAcceptHeader = true;
                })
                .AddNewtonsoftJson(options =>
                {
                    options.AllowInputFormatterExceptionMessages = true;
                    ConfigureNewtonsoftJsonSerializerSettingsForApi(options.SerializerSettings);
                });
            services.AddSignalR(
                options =>
                {
                    options.AddFilter<AuthorizationContextHubFilter>();
                })
                .AddNewtonsoftJsonProtocol(options =>
                {
                    ConfigureNewtonsoftJsonSerializerSettingsForApi(options.PayloadSerializerSettings);
                });
            services.AddHub<JobsHub, IJobsHub>();
            if (postSetupServices.GeneralConfiguration.HostApiDocumentation)
            {
                string GetDocumentationFilePath(string assemblyLocation) => ioManager.ConcatPath(ioManager.GetDirectoryName(assemblyLocation), String.Concat(ioManager.GetFileNameWithoutExtension(assemblyLocation), ".xml"));
                var assemblyDocumentationPath = GetDocumentationFilePath(GetType().Assembly.Location);
                var apiDocumentationPath = GetDocumentationFilePath(typeof(ApiHeaders).Assembly.Location);
                services.AddSwaggerGen(genOptions => SwaggerConfiguration.Configure(genOptions, assemblyDocumentationPath, apiDocumentationPath));
                services.AddSwaggerGenNewtonsoftSupport();
            }
            // CORS conditionally enabled later
            services.AddCors();
            // Enable managed HTTP clients
            services.AddHttpClient();
            services.AddSingleton<IAbstractHttpClientFactory, AbstractHttpClientFactory>();
            // configure graphql
            if (postSetupServices.InternalConfiguration.EnableGraphQL)
                services
                    .AddScoped<GraphQL.Subscriptions.ITopicEventReceiver, ShutdownAwareTopicEventReceiver>()
                    .AddGraphQLServer()
                    .AddAuthorization()
                    .ModifyOptions(options =>
                    {
                        options.EnsureAllNodesCanBeResolved = true;
                        options.EnableFlagEnums = true;
                    })
#if DEBUG
                    .ModifyCostOptions(options =>
                    {
                        options.EnforceCostLimits = false;
                    })
#endif
                    .AddMutationConventions()
                    .AddInMemorySubscriptions(
                        new SubscriptionOptions
{
                            TopicBufferCapacity = 1024, // mainly so high for tests, not possible to DoS the server without authentication and some other access to generate messages
                        })
                    .AddGlobalObjectIdentification()
                    .AddQueryFieldToMutationPayloads()
                    .ModifyOptions(options =>
                    {
                        options.EnableDefer = true;
                    })
                    .ModifyPagingOptions(pagingOptions =>
                    {
                        pagingOptions.IncludeTotalCount = true;
                        pagingOptions.RequirePagingBoundaries = false;
                        pagingOptions.DefaultPageSize = ApiController.DefaultPageSize;
                        pagingOptions.MaxPageSize = ApiController.MaximumPageSize;
                    })
                    .AddFiltering()
                    .AddSorting()
                    .AddHostTypes()
                    .AddErrorFilter<ErrorMessageFilter>()
                    .AddType<StandaloneNode>()
                    .AddType<LocalGateway>()
                    .AddType<RemoteGateway>()
                    .AddType<GraphQL.Types.UserName>()
                    .AddType<UnsignedIntType>()
                    .BindRuntimeType<Version, SemverType>()
                    .TryAddTypeInterceptor<RightsTypeInterceptor>()
                    .AddQueryType<Query>()
                    .AddMutationType<Mutation>()
                    .AddSubscriptionType<Subscription>();
            void AddTypedContext<TContext>()
                where TContext : DatabaseContext
            {
                var configureAction = DatabaseContext.GetConfigureAction<TContext>();
                services.AddDbContextPool<TContext>((serviceProvider, builder) =>
                {
                    if (hostingEnvironment.IsDevelopment())
                        builder.EnableSensitiveDataLogging();
                    var databaseConfigOptions = serviceProvider.GetRequiredService<IOptions<DatabaseConfiguration>>();
                    var databaseConfig = databaseConfigOptions.Value ?? throw new InvalidOperationException("DatabaseConfiguration missing!");
                    configureAction(builder, databaseConfig);
                });
                services.AddScoped<IDatabaseContext>(x => x.GetRequiredService<TContext>());
            }
            // add the correct database context type
            var dbType = postSetupServices.DatabaseConfiguration.DatabaseType;
            switch (dbType)
            {
                case DatabaseType.MySql:
                case DatabaseType.MariaDB:
                    AddTypedContext<MySqlDatabaseContext>();
                    break;
                case DatabaseType.SqlServer:
                    AddTypedContext<SqlServerDatabaseContext>();
                    break;
                case DatabaseType.Sqlite:
                    AddTypedContext<SqliteDatabaseContext>();
                    break;
                case DatabaseType.PostgresSql:
                    AddTypedContext<PostgresSqlDatabaseContext>();
                    break;
                default:
                    throw new InvalidOperationException(String.Format(CultureInfo.InvariantCulture, "Invalid {0}: {1}!", nameof(DatabaseType), dbType));
            }
            // configure other database services
            services.AddSingleton<IDatabaseContextFactory, DatabaseContextFactory>();
            services.AddSingleton<IDatabaseSeeder, DatabaseSeeder>();
            // configure other security services
            services.AddSingleton<IOAuthProviders, OAuthProviders>();
            services.AddSingleton<IIdentityCache, IdentityCache>();
            services.AddSingleton<ICryptographySuite, CryptographySuite>();
            services.AddSingleton<ITokenFactory, TokenFactory>();
            services.AddSingleton<ISessionInvalidationTracker, SessionInvalidationTracker>();
            services.AddSingleton<IPasswordHasher<Models.User>, PasswordHasher<Models.User>>();
            // configure platform specific services
            if (postSetupServices.PlatformIdentifier.IsWindows)
            {
                AddWatchdog<WindowsWatchdogFactory>(services, postSetupServices);
                services.AddSingleton<ISystemIdentityFactory, WindowsSystemIdentityFactory>();
                services.AddSingleton<IFilesystemLinkFactory, WindowsFilesystemLinkFactory>();
                services.AddSingleton<ByondInstallerBase, WindowsByondInstaller>();
                services.AddSingleton<OpenDreamInstaller, WindowsOpenDreamInstaller>();
                services.AddSingleton<IPostWriteHandler, WindowsPostWriteHandler>();
                services.AddSingleton<IProcessFeatures, WindowsProcessFeatures>();
                services.AddSingleton<WindowsNetworkPromptReaper>();
                services.AddSingleton<INetworkPromptReaper>(x => x.GetRequiredService<WindowsNetworkPromptReaper>());
                services.AddSingleton<IHostedService>(x => x.GetRequiredService<WindowsNetworkPromptReaper>());
            }
            else
            {
                AddWatchdog<PosixWatchdogFactory>(services, postSetupServices);
                services.AddSingleton<ISystemIdentityFactory, PosixSystemIdentityFactory>();
                services.AddSingleton<IFilesystemLinkFactory, PosixFilesystemLinkFactory>();
                services.AddSingleton<ByondInstallerBase, PosixByondInstaller>();
                services.AddSingleton<OpenDreamInstaller>();
                services.AddSingleton<IPostWriteHandler, PosixPostWriteHandler>();
                services.AddSingleton<IProcessFeatures, PosixProcessFeatures>();
                services.AddHostedService<PosixProcessFeatures>();
                // PosixProcessFeatures also needs a IProcessExecutor for gcore
                services.AddSingleton(x => new Lazy<IProcessExecutor>(() => x.GetRequiredService<IProcessExecutor>(), true));
                services.AddSingleton<INetworkPromptReaper, PosixNetworkPromptReaper>();
                services.AddHostedService<PosixSignalHandler>();
            }
            // only global repo manager should be for the OD repo
            // god help me if we need more
            var openDreamRepositoryDirectory = ioManager.ConcatPath(
                ioManager.GetPathInLocalDirectory(assemblyInformationProvider),
                "OpenDreamRepository");
            services.AddSingleton(
                services => services
                    .GetRequiredService<IRepositoryManagerFactory>()
                    .CreateRepositoryManager(
                        new ResolvingIOManager(
                            services.GetRequiredService<IIOManager>(),
                            openDreamRepositoryDirectory),
                        new NoopEventConsumer()));
            services.AddSingleton(
                serviceProvider => new Dictionary<EngineType, IEngineInstaller>
                {
                    { EngineType.Byond, serviceProvider.GetRequiredService<ByondInstallerBase>() },
                    { EngineType.OpenDream, serviceProvider.GetRequiredService<OpenDreamInstaller>() },
                }
                .ToFrozenDictionary());
            services.AddSingleton<IEngineInstaller, DelegatingEngineInstaller>();
            if (postSetupServices.InternalConfiguration.UsingSystemD)
                services.AddHostedService<SystemDManager>();
            // configure file transfer services
            services.AddSingleton<FileTransferService>();
            services.AddSingleton<IFileTransferStreamHandler>(x => x.GetRequiredService<FileTransferService>());
            services.AddSingleton<IFileTransferTicketProvider>(x => x.GetRequiredService<FileTransferService>());
            services.AddTransient<IActionResultExecutor<LimitedStreamResult>, LimitedStreamResultExecutor>();
            // configure swarm service
            services.AddSingleton<SwarmService>();
            services.AddSingleton<ISwarmService>(x => x.GetRequiredService<SwarmService>());
            services.AddSingleton<ISwarmOperations>(x => x.GetRequiredService<SwarmService>());
            services.AddSingleton<ISwarmServiceController>(x => x.GetRequiredService<SwarmService>());
            // configure component services
            services.AddSingleton<IPortAllocator, PortAllocator>();
            services.AddSingleton<IInstanceFactory, InstanceFactory>();
            services.AddSingleton<IGitRemoteFeaturesFactory, GitRemoteFeaturesFactory>();
            services.AddSingleton<ILibGit2RepositoryFactory, LibGit2RepositoryFactory>();
            services.AddSingleton<ILibGit2Commands, LibGit2Commands>();
            services.AddSingleton<IRepositoryManagerFactory, RepostoryManagerFactory>();
            services.AddSingleton<IRemoteDeploymentManagerFactory, RemoteDeploymentManagerFactory>();
            services.AddChatProviderFactory();
            services.AddSingleton<IChatManagerFactory, ChatManagerFactory>();
            services.AddSingleton<IServerUpdater, ServerUpdater>();
            services.AddSingleton<IServerUpdateInitiator, ServerUpdateInitiator>();
            services.AddSingleton<IDotnetDumpService, DotnetDumpService>();
            // configure authorities
            services.AddScoped(typeof(IRestAuthorityInvoker<>), typeof(RestAuthorityInvoker<>));
            services.AddScoped(typeof(IGraphQLAuthorityInvoker<>), typeof(GraphQLAuthorityInvoker<>));
            services.AddScoped<ILoginAuthority, LoginAuthority>();
            services.AddScoped<IUserAuthority, UserAuthority>();
            services.AddScoped<IUserGroupAuthority, UserGroupAuthority>();
            services.AddScoped<IPermissionSetAuthority, PermissionSetAuthority>();
            // configure misc services
            services.AddSingleton<IProcessExecutor, ProcessExecutor>();
            services.AddSingleton<ISynchronousIOManager, SynchronousIOManager>();
            services.AddSingleton<IServerPortProvider, ServerPortProivder>();
            services.AddSingleton<ITopicClientFactory, TopicClientFactory>();
            services.AddHostedService<CommandPipeManager>();
            services.AddHostedService<VersionReportingService>();
            services.AddFileDownloader();
            services.AddGitHub();
            // configure root services
            services.AddSingleton<JobService>();
            services.AddSingleton<IJobService>(provider => provider.GetRequiredService<JobService>());
            services.AddSingleton<IJobsHubUpdater>(provider => provider.GetRequiredService<JobService>());
            services.AddSingleton<IJobManager>(x => x.GetRequiredService<IJobService>());
            services.AddSingleton<JobsHubGroupMapper>();
            services.AddSingleton<IPermissionsUpdateNotifyee>(provider => provider.GetRequiredService<JobsHubGroupMapper>());
            services.AddSingleton<IHostedService>(x => x.GetRequiredService<JobsHubGroupMapper>()); // bit of a hack, but we need this to load immediated
            services.AddSingleton<InstanceManager>();
            services.AddSingleton<IBridgeDispatcher>(x => x.GetRequiredService<InstanceManager>());
            services.AddSingleton<IInstanceManager>(x => x.GetRequiredService<InstanceManager>());
        }
References Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.Setup.SetupApplication.Configuration, Tgstation.Server.Host.Utils.SwaggerConfiguration.Configure(), Tgstation.Server.Host.Core.Application.ConfigureAuthenticationPipeline(), Tgstation.Server.Host.Core.Application.ConfigureServices(), Tgstation.Server.Host.Setup.IPostSetupServices.DatabaseConfiguration, Tgstation.Server.Host.Configuration.DatabaseConfiguration.DatabaseType, Tgstation.Server.Host.Controllers.ApiController.DefaultPageSize, Tgstation.Server.Host.Configuration.FileLoggingConfiguration.Disable, Tgstation.Server.Host.Setup.IPostSetupServices.ElasticsearchConfiguration, Tgstation.Server.Host.Configuration.InternalConfiguration.EnableGraphQL, Tgstation.Server.Host.Setup.IPostSetupServices.FileLoggingConfiguration, Tgstation.Server.Host.Setup.IPostSetupServices.GeneralConfiguration, Tgstation.Server.Host.IO.IIOManager.GetDirectoryName(), Tgstation.Server.Host.IO.IIOManager.GetFileNameWithoutExtension(), Tgstation.Server.Host.Configuration.FileLoggingConfiguration.GetFullLogDirectory(), Tgstation.Server.Host.Configuration.GeneralConfiguration.HostApiDocumentation, Tgstation.Server.Host.Core.Application.hostingEnvironment, Tgstation.Server.Host.Setup.IPostSetupServices.InternalConfiguration, Tgstation.Server.Host.System.IPlatformIdentifier.IsWindows, Tgstation.Server.Host.Configuration.FileLoggingConfiguration.LogLevel, Tgstation.Server.Host.Controllers.ApiController.MaximumPageSize, Tgstation.Server.Host.Configuration.FileLoggingConfiguration.MicrosoftLogLevel, Tgstation.Server.Host.Setup.IPostSetupServices.PlatformIdentifier, Tgstation.Server.Host.Configuration.GeneralConfiguration.RestartTimeoutMinutes, Tgstation.Server.Host.Utils.SerilogContextHelper.Template, and Tgstation.Server.Host.Configuration.InternalConfiguration.UsingSystemD.
Referenced by Tgstation.Server.Host.Core.Application.ConfigureServices().
CreateDefaultServerFactory()
static IServerFactory Tgstation.Server.Host.Core.Application.CreateDefaultServerFactory () static
Create the default IServerFactory.
Returns
A new IServerFactory with the default settings.
Definition at line 98 of file Application.cs.
        {
            var assemblyInformationProvider = new AssemblyInformationProvider();
            var ioManager = new DefaultIOManager();
            return new ServerFactory(
                assemblyInformationProvider,
                ioManager);
        }
Referenced by Tgstation.Server.Host.Program.Program().
Member Data Documentation
hostingEnvironment
readonly IWebHostEnvironment Tgstation.Server.Host.Core.Application.hostingEnvironment private
The IWebHostEnvironment for the Application.
Definition at line 87 of file Application.cs.
Referenced by Tgstation.Server.Host.Core.Application.Application(), Tgstation.Server.Host.Core.Application.Configure(), and Tgstation.Server.Host.Core.Application.ConfigureServices().
tokenFactory
ITokenFactory? Tgstation.Server.Host.Core.Application.tokenFactory private
The ITokenFactory for the Application.
Definition at line 92 of file Application.cs.
Referenced by Tgstation.Server.Host.Core.Application.Configure(), and Tgstation.Server.Host.Core.Application.ConfigureAuthenticationPipeline().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Core/Application.cs