tgstation-server: Tgstation.Server.Host.Components.Engine.EngineInstallationBase Class Reference
Tgstation.Server.Host.Components.Engine.EngineInstallationBase Class Reference abstract
Public Member Functions
EngineInstallationBase (IIOManager installationIOManager)
Initializes a new instance of the EngineInstallationBase class.
abstract string FormatCompilerArguments (string dmePath, string? additionalArguments)
Return the command line arguments for compiling a given dmePath if compilation is necessary.
Parameters
dmePath The full path to the .dme to compile.
additionalArguments Optional additional arguments provided to the compiler.
Returns
The formatted arguments string.
abstract string FormatServerArguments (IDmbProvider dmbProvider, IReadOnlyDictionary< string, string > parameters, DreamDaemonLaunchParameters launchParameters, string? logFilePath)
Return the command line arguments for launching with given launchParameters .
Parameters
dmbProvider The IDmbProvider.
parameters The map of parameter strings as a IReadOnlyDictionary<TKey, TValue>. MUST include Interop.DMApiConstants.ParamAccessIdentifier. Should NOT include the DreamDaemonLaunchParameters.AdditionalParameters of launchParameters .
launchParameters The DreamDaemonLaunchParameters.
logFilePath The full path to the log file, if any.
Returns
The formatted arguments string.
virtual async ValueTask StopServerProcess (ILogger logger, IProcess process, string accessIdentifier, ushort port, CancellationToken cancellationToken)
Kills a given engine server process .
Parameters
logger The ILogger to write to.
process The IProcess to be terminated.
accessIdentifier The Interop.DMApiParameters.AccessIdentifier of the session.
port The port the server is running on.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
async ValueTask< Dictionary< string, string >?> LoadEnv (ILogger logger, bool forCompiler, CancellationToken cancellationToken)
Loads the environment settings for either the server or compiler.
Parameters
logger The ILogger to write to.
forCompiler If false server.env will be loaded. If true compiler.env will be loaded.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the environment Dictionary<TKey, TValue> or null if the target environment file doesn't exist.
string FormatServerArguments (IDmbProvider dmbProvider, IReadOnlyDictionary< string, string > parameters, DreamDaemonLaunchParameters launchParameters, string? logFilePath)
Return the command line arguments for launching with given launchParameters .
string FormatCompilerArguments (string dmePath, string? additionalArguments)
Return the command line arguments for compiling a given dmePath if compilation is necessary.
ValueTask StopServerProcess (ILogger logger, IProcess process, string accessIdentifier, ushort port, CancellationToken cancellationToken)
Kills a given engine server process .
ValueTask< Dictionary< string, string >?> LoadEnv (ILogger logger, bool forCompiler, CancellationToken cancellationToken)
Loads the environment settings for either the server or compiler.
Static Protected Member Functions
static string EncodeParameters (IReadOnlyDictionary< string, string > parameters, DreamDaemonLaunchParameters launchParameters)
Encode given parameters for passing as world.params on the command line.
Properties
abstract EngineVersion Version [get]
The EngineVersion of the IEngineInstallation.
abstract string ServerExePath [get]
The full path to the game server executable.
abstract string CompilerExePath [get]
The full path to the dm/DreamMaker executable.
abstract bool HasStandardOutput [get]
If ServerExePath supports being run as a command-line application and outputs log information to be captured.
abstract bool PreferFileLogging [get]
If HasStandardOutput is set, this indicates that the engine server has good file logging that should be preferred to ours.
abstract bool PromptsForNetworkAccess [get]
If ServerExePath may create network prompts.
abstract bool UseDotnetDump [get]
If dotnet-dump should be used to create process dumps for this installation.
abstract Task InstallationTask [get]
The Task that completes when the BYOND version finished installing.
IIOManager InstallationIOManager [get]
The IIOManager pointing to the installation directory.
Properties inherited from Tgstation.Server.Host.Components.Engine.IEngineInstallation
EngineVersion Version [get]
The EngineVersion of the IEngineInstallation.
string ServerExePath [get]
The full path to the game server executable.
string CompilerExePath [get]
The full path to the dm/DreamMaker executable.
bool HasStandardOutput [get]
If ServerExePath supports being run as a command-line application and outputs log information to be captured.
bool PromptsForNetworkAccess [get]
If ServerExePath may create network prompts.
bool PreferFileLogging [get]
If HasStandardOutput is set, this indicates that the engine server has good file logging that should be preferred to ours.
bool UseDotnetDump [get]
If dotnet-dump should be used to create process dumps for this installation.
Task InstallationTask [get]
The Task that completes when the BYOND version finished installing.
Detailed Description
Definition at line 22 of file EngineInstallationBase.cs.
Constructor & Destructor Documentation
EngineInstallationBase()
Tgstation.Server.Host.Components.Engine.EngineInstallationBase.EngineInstallationBase (IIOManager installationIOManager)
Initializes a new instance of the EngineInstallationBase class.
Parameters
installationIOManager The value of InstallationIOManager.
Definition at line 75 of file EngineInstallationBase.cs.
        {
            InstallationIOManager = installationIOManager ?? throw new ArgumentNullException(nameof(installationIOManager));
        }
References Tgstation.Server.Host.Components.Engine.EngineInstallationBase.InstallationIOManager.
Member Function Documentation
EncodeParameters()
static string Tgstation.Server.Host.Components.Engine.EngineInstallationBase.EncodeParameters (IReadOnlyDictionary< string, string > parameters, DreamDaemonLaunchParameters launchParameters) static protected
Encode given parameters for passing as world.params on the command line.
Parameters
parameters IReadOnlyDictionary<TKey, TValue> of parameters to encode.
launchParameters The active DreamDaemonLaunchParameters.
Returns
The formatted parameters string.
Definition at line 59 of file EngineInstallationBase.cs.
        {
            var parametersString = String.Join('&', parameters.Select(kvp => $"{HttpUtility.UrlEncode(kvp.Key)}={HttpUtility.UrlEncode(kvp.Value)}"));
            if (!String.IsNullOrEmpty(launchParameters.AdditionalParameters))
                parametersString = $"{parametersString}&{launchParameters.AdditionalParameters}";
            return parametersString;
        }
References Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.AdditionalParameters.
Referenced by Tgstation.Server.Host.Components.Engine.ByondInstallation.FormatServerArguments(), and Tgstation.Server.Host.Components.Engine.OpenDreamInstallation.FormatServerArguments().
FormatCompilerArguments()
abstract string Tgstation.Server.Host.Components.Engine.EngineInstallationBase.FormatCompilerArguments (string dmePath, string? additionalArguments) pure virtual
Return the command line arguments for compiling a given dmePath if compilation is necessary.
Parameters
dmePath The full path to the .dme to compile.
additionalArguments Optional additional arguments provided to the compiler.
Returns
The formatted arguments string.
Implements Tgstation.Server.Host.Components.Engine.IEngineInstallation.
Implemented in Tgstation.Server.Host.Components.Engine.ByondInstallation.
FormatServerArguments()
abstract string Tgstation.Server.Host.Components.Engine.EngineInstallationBase.FormatServerArguments (IDmbProvider dmbProvider, IReadOnlyDictionary< string, string > parameters, DreamDaemonLaunchParameters launchParameters, string? logFilePath) pure virtual
Return the command line arguments for launching with given launchParameters .
Parameters
dmbProvider The IDmbProvider.
parameters The map of parameter strings as a IReadOnlyDictionary<TKey, TValue>. MUST include Interop.DMApiConstants.ParamAccessIdentifier. Should NOT include the DreamDaemonLaunchParameters.AdditionalParameters of launchParameters .
launchParameters The DreamDaemonLaunchParameters.
logFilePath The full path to the log file, if any.
Returns
The formatted arguments string.
Implements Tgstation.Server.Host.Components.Engine.IEngineInstallation.
Implemented in Tgstation.Server.Host.Components.Engine.ByondInstallation, and Tgstation.Server.Host.Components.Engine.OpenDreamInstallation.
LoadEnv()
async ValueTask< Dictionary< string, string >?> Tgstation.Server.Host.Components.Engine.EngineInstallationBase.LoadEnv (ILogger logger, bool forCompiler, CancellationToken cancellationToken)
Loads the environment settings for either the server or compiler.
Parameters
logger The ILogger to write to.
forCompiler If false server.env will be loaded. If true compiler.env will be loaded.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the environment Dictionary<TKey, TValue> or null if the target environment file doesn't exist.
Implements Tgstation.Server.Host.Components.Engine.IEngineInstallation.
Definition at line 101 of file EngineInstallationBase.cs.
        {
            ArgumentNullException.ThrowIfNull(logger);
            var envFile = forCompiler
                ? "compiler.env"
                : "server.env";
            if (!await InstallationIOManager.FileExists(envFile, cancellationToken))
            {
                logger.LogTrace("No {envFile} present in engine installation {version}", envFile, Version);
                return null;
            }
            logger.LogDebug("Loading {envFile} for engine installation {version}...", envFile, Version);
            var fileBytes = await InstallationIOManager.ReadAllBytes(envFile, cancellationToken);
            var fileContents = Encoding.UTF8.GetString(fileBytes);
            var parser = new EnvParser();
            try
            {
                var variables = parser.Parse(fileContents);
                return variables.ToDictionary();
            }
            catch (Exception ex)
            {
                logger.LogWarning(ex, "Unable to parse {envFile}!", envFile);
                return null;
            }
        }
References Tgstation.Server.Host.IO.IIOManager.FileExists(), Tgstation.Server.Host.Components.Engine.EngineInstallationBase.InstallationIOManager, Tgstation.Server.Host.IO.IIOManager.ReadAllBytes(), and Tgstation.Server.Host.Components.Engine.EngineInstallationBase.Version.
StopServerProcess()
virtual async ValueTask Tgstation.Server.Host.Components.Engine.EngineInstallationBase.StopServerProcess (ILogger logger, IProcess process, string accessIdentifier, ushort port, CancellationToken cancellationToken) virtual
Kills a given engine server process .
Parameters
logger The ILogger to write to.
process The IProcess to be terminated.
accessIdentifier The Interop.DMApiParameters.AccessIdentifier of the session.
port The port the server is running on.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Engine.IEngineInstallation.
Definition at line 91 of file EngineInstallationBase.cs.
        {
            ArgumentNullException.ThrowIfNull(logger);
            cancellationToken.ThrowIfCancellationRequested();
            logger.LogTrace("Terminating engine server process...");
            process.Terminate();
            await process.Lifetime;
        }
References Tgstation.Server.Host.System.IProcessBase.Lifetime, and Tgstation.Server.Host.System.IProcess.Terminate().
Property Documentation
CompilerExePath
abstract string Tgstation.Server.Host.Components.Engine.EngineInstallationBase.CompilerExePath get
The full path to the dm/DreamMaker executable.
Implements Tgstation.Server.Host.Components.Engine.IEngineInstallation.
Definition at line 31 of file EngineInstallationBase.cs.
{ get; }
HasStandardOutput
abstract bool Tgstation.Server.Host.Components.Engine.EngineInstallationBase.HasStandardOutput get
If ServerExePath supports being run as a command-line application and outputs log information to be captured.
Implements Tgstation.Server.Host.Components.Engine.IEngineInstallation.
Definition at line 34 of file EngineInstallationBase.cs.
{ get; }
InstallationIOManager
IIOManager Tgstation.Server.Host.Components.Engine.EngineInstallationBase.InstallationIOManager get protected
The IIOManager pointing to the installation directory.
Definition at line 51 of file EngineInstallationBase.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Engine.EngineInstallationBase.EngineInstallationBase(), and Tgstation.Server.Host.Components.Engine.EngineInstallationBase.LoadEnv().
InstallationTask
abstract Task Tgstation.Server.Host.Components.Engine.EngineInstallationBase.InstallationTask get
The Task that completes when the BYOND version finished installing.
Implements Tgstation.Server.Host.Components.Engine.IEngineInstallation.
Definition at line 46 of file EngineInstallationBase.cs.
{ get; }
PreferFileLogging
abstract bool Tgstation.Server.Host.Components.Engine.EngineInstallationBase.PreferFileLogging get
If HasStandardOutput is set, this indicates that the engine server has good file logging that should be preferred to ours.
Implements Tgstation.Server.Host.Components.Engine.IEngineInstallation.
Definition at line 37 of file EngineInstallationBase.cs.
{ get; }
PromptsForNetworkAccess
abstract bool Tgstation.Server.Host.Components.Engine.EngineInstallationBase.PromptsForNetworkAccess get
If ServerExePath may create network prompts.
Implements Tgstation.Server.Host.Components.Engine.IEngineInstallation.
Definition at line 40 of file EngineInstallationBase.cs.
{ get; }
ServerExePath
abstract string Tgstation.Server.Host.Components.Engine.EngineInstallationBase.ServerExePath get
The full path to the game server executable.
Implements Tgstation.Server.Host.Components.Engine.IEngineInstallation.
Definition at line 28 of file EngineInstallationBase.cs.
{ get; }
UseDotnetDump
abstract bool Tgstation.Server.Host.Components.Engine.EngineInstallationBase.UseDotnetDump get
If dotnet-dump should be used to create process dumps for this installation.
Implements Tgstation.Server.Host.Components.Engine.IEngineInstallation.
Definition at line 43 of file EngineInstallationBase.cs.
{ get; }
Version
abstract EngineVersion Tgstation.Server.Host.Components.Engine.EngineInstallationBase.Version get
The EngineVersion of the IEngineInstallation.
Implements Tgstation.Server.Host.Components.Engine.IEngineInstallation.
Definition at line 25 of file EngineInstallationBase.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Engine.EngineInstallationBase.LoadEnv().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Engine/EngineInstallationBase.cs