tgstation-server: Tgstation.Server.Host.Controllers.UserGroupController Class Reference
Tgstation.Server.Host.Controllers.UserGroupController Class Reference
ApiController for managing UserGroupResponses.
Public Member Functions
UserGroupController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, IOptions< GeneralConfiguration > generalConfigurationOptions, ILogger< UserGroupController > logger, IApiHeadersProvider apiHeaders)
Initializes a new instance of the UserGroupController class.
async ValueTask< IActionResult > Create ([FromBody] UserGroupCreateRequest model, CancellationToken cancellationToken)
Create a new UserGroup.
async ValueTask< IActionResult > Update ([FromBody] UserGroupUpdateRequest model, CancellationToken cancellationToken)
Update a UserGroup.
async ValueTask< IActionResult > GetId (long id, CancellationToken cancellationToken)
Gets a specific UserGroup.
ValueTask< IActionResult > List ([FromQuery] int? page, [FromQuery] int? pageSize, CancellationToken cancellationToken)
Lists all UserGroups.
async ValueTask< IActionResult > Delete (long id, CancellationToken cancellationToken)
Delete a UserGroup.
Public Member Functions inherited from Tgstation.Server.Host.Controllers.ApiControllerBase
override async Task OnActionExecutionAsync (ActionExecutingContext context, ActionExecutionDelegate next)
Private Member Functions
ValueTask< IActionResult > UserGroupResponse (()=> ValueTask.FromResult(new PaginatableResult< UserGroup >(DatabaseContext .Groups .AsQueryable() .Include(x=> x.Users) .Include(x=> x.PermissionSet) .OrderBy(x=> x.Id))), null, page, pageSize, cancellationToken)
Private Attributes
readonly GeneralConfiguration generalConfiguration
The GeneralConfiguration for the UserGroupController.
Additional Inherited Members
Protected Member Functions inherited from Tgstation.Server.Host.Controllers.ApiController
ApiController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, IApiHeadersProvider apiHeadersProvider, ILogger< ApiController > logger, bool requireHeaders)
Initializes a new instance of the ApiController class.
override async ValueTask< IActionResult?> HookExecuteAction (Func< Task > executeAction, CancellationToken cancellationToken)
Hook for executing a request.
Parameters
executeAction A Func<TResult> that should be invoked and its response awaited to continue normal execution of the request. Should NOT be called if this method returns a non-null value.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in an IActionResult that, if not null, is executed.
new NotFoundObjectResult NotFound ()
Generic 404 response.
new ObjectResult Unauthorized ()
Generic 401 response.
ObjectResult RequiresPosixSystemIdentity (NotImplementedException ex)
Generic 501 response.
StatusCodeResult StatusCode (HttpStatusCode statusCode)
Strongly type calls to ControllerBase.StatusCode(int).
ObjectResult Created (object payload)
Generic 201 response with a given payload .
ObjectResult RateLimit (RateLimitExceededException rateLimitException)
429 response for a given rateLimitException .
virtual ValueTask< IActionResult?> ValidateRequest (CancellationToken cancellationToken)
Performs validation a request.
IActionResult HeadersIssue (HeadersException headersException)
Response for missing/Invalid headers.
ValueTask< IActionResult > Paginated< TModel > (Func< ValueTask< PaginatableResult< TModel > > > queryGenerator, Func< TModel, ValueTask >? resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
ValueTask< IActionResult > Paginated< TModel, TApiModel > (Func< ValueTask< PaginatableResult< TModel > > > queryGenerator, Func< TApiModel, ValueTask >? resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
Properties inherited from Tgstation.Server.Host.Controllers.ApiController
ApiHeaders? ApiHeaders [get]
The Api.ApiHeaders for the operation.
IApiHeadersProvider ApiHeadersProvider [get]
The IApiHeadersProvider containing value of ApiHeaders.
IDatabaseContext DatabaseContext [get]
The IDatabaseContext for the operation.
IAuthenticationContext AuthenticationContext [get]
The IAuthenticationContext for the operation.
ILogger< ApiController > Logger [get]
The ILogger for the ApiController.
Models.? Instance Instance [get]
The Instance for the operation.
Detailed Description
ApiController for managing UserGroupResponses.
Definition at line 30 of file UserGroupController.cs.
Constructor & Destructor Documentation
UserGroupController()
Tgstation.Server.Host.Controllers.UserGroupController.UserGroupController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, IOptions< GeneralConfiguration > generalConfigurationOptions, ILogger< UserGroupController > logger, IApiHeadersProvider apiHeaders)
Initializes a new instance of the UserGroupController class.
Parameters
databaseContext The IDatabaseContext for the ApiController.
authenticationContext The IAuthenticationContext for the ApiController.
generalConfigurationOptions The IOptions<TOptions> containing the value of generalConfiguration.
logger The ILogger for the ApiController.
apiHeaders The IApiHeadersProvider for the ApiController.
Definition at line 45 of file UserGroupController.cs.
            : base(
                databaseContext,
                authenticationContext,
                apiHeaders,
                logger,
                true)
        {
            generalConfiguration = generalConfigurationOptions?.Value ?? throw new ArgumentNullException(nameof(generalConfigurationOptions));
        }
References Tgstation.Server.Host.Controllers.UserGroupController.generalConfiguration, and Tgstation.Server.Api.Rights.List.
Member Function Documentation
Create()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.UserGroupController.Create ([FromBody] UserGroupCreateRequest model, CancellationToken cancellationToken)
Create a new UserGroup.
Parameters
model The UserGroupCreateRequest.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the operation.
<response code="201">UserGroup created successfully.</response>
Definition at line 71 of file UserGroupController.cs.
        {
            ArgumentNullException.ThrowIfNull(model);
            if (model.Name == null)
                return BadRequest(new ErrorMessageResponse(ErrorCode.ModelValidationFailure));
            var totalGroups = await DatabaseContext
                .Groups
                .AsQueryable()
                .CountAsync(cancellationToken);
            if (totalGroups >= generalConfiguration.UserGroupLimit)
                return Conflict(new ErrorMessageResponse(ErrorCode.UserGroupLimitReached));
            var permissionSet = new Models.PermissionSet
            {
                AdministrationRights = model.PermissionSet?.AdministrationRights ?? AdministrationRights.None,
                InstanceManagerRights = model.PermissionSet?.InstanceManagerRights ?? InstanceManagerRights.None,
            };
            var dbGroup = new UserGroup
            {
                Name = model.Name,
                PermissionSet = permissionSet,
            };
            DatabaseContext.Groups.Add(dbGroup);
            await DatabaseContext.Save(cancellationToken);
            Logger.LogInformation("Created new user group {groupName} ({groupId})", dbGroup.Name, dbGroup.Id);
            return Created(dbGroup.ToApi(true));
        }
References Tgstation.Server.Api.Models.PermissionSet.AdministrationRights, Tgstation.Server.Host.Controllers.ApiController.Created(), Tgstation.Server.Host.Controllers.UserGroupController.generalConfiguration, Tgstation.Server.Host.Database.DatabaseContext.Groups, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Controllers.ApiController.Logger, Tgstation.Server.Api.Models.NamedEntity.Name, Tgstation.Server.Host.Database.DatabaseContext.Save(), and Tgstation.Server.Api.Models.Internal.ServerInformationBase.UserGroupLimit.
Delete()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.UserGroupController.Delete (long id, CancellationToken cancellationToken)
Delete a UserGroup.
Parameters
id The EntityId.Id of the UserGroup to delete.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the request.
<response code="204">UserGroup was deleted.</response> <response code="409">The UserGroup is not empty.</response> <response code="410">The UserGroup didn't exist.</response>
Definition at line 216 of file UserGroupController.cs.
        {
            var numDeleted = await DatabaseContext
                .Groups
                .AsQueryable()
                .Where(x => x.Id == id && x.Users!.Count == 0)
                .ExecuteDeleteAsync(cancellationToken);
            if (numDeleted > 0)
                return NoContent();
            // find out how we failed
            var groupExists = await DatabaseContext
                .Groups
                .AsQueryable()
                .Where(x => x.Id == id)
                .AnyAsync(cancellationToken);
            return groupExists
                ? Conflict(new ErrorMessageResponse(ErrorCode.UserGroupNotEmpty))
                : this.Gone();
        }
References Tgstation.Server.Host.Database.DatabaseContext.Groups, and Tgstation.Server.Api.Rights.List.
GetId()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.UserGroupController.GetId (long id, CancellationToken cancellationToken)
Gets a specific UserGroup.
Parameters
id The EntityId.Id of the UserGroupResponse.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the request.
<response code="200">Retrieve UserGroup successfully.</response> <response code="410">The requested UserGroup does not currently exist.</response>
Definition at line 161 of file UserGroupController.cs.
        {
            // this functions as userId
            var group = await DatabaseContext
                .Groups
                .AsQueryable()
                .Where(x => x.Id == id)
                .Include(x => x.Users)
                .Include(x => x.PermissionSet)
                .FirstOrDefaultAsync(cancellationToken);
            if (group == default)
                return this.Gone();
            return Json(group.ToApi(true));
        }
References Tgstation.Server.Host.Database.DatabaseContext.Groups, and Tgstation.Server.Api.Rights.List.
List()
ValueTask< IActionResult > Tgstation.Server.Host.Controllers.UserGroupController.List ([FromQuery] int? page, [FromQuery] int? pageSize, CancellationToken cancellationToken)
Lists all UserGroups.
Parameters
page The current page.
pageSize The page size.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the request.
<response code="200">Retrieved UserGroups successfully.</response>
Update()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.UserGroupController.Update ([FromBody] UserGroupUpdateRequest model, CancellationToken cancellationToken)
Update a UserGroup.
Parameters
model The UserGroupUpdateRequest.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the operation.
<response code="200">UserGroup updated successfully.</response> <response code="410">The requested UserGroup does not currently exist.</response>
Definition at line 115 of file UserGroupController.cs.
        {
            ArgumentNullException.ThrowIfNull(model);
            var currentGroup = await DatabaseContext
                .Groups
                .AsQueryable()
                .Where(x => x.Id == model.Id)
                .Include(x => x.PermissionSet)
                .Include(x => x.Users)
                .FirstOrDefaultAsync(cancellationToken);
            if (currentGroup == default)
                return this.Gone();
            if (model.PermissionSet != null)
            {
                currentGroup.PermissionSet!.AdministrationRights = model.PermissionSet.AdministrationRights ?? currentGroup.PermissionSet.AdministrationRights;
                currentGroup.PermissionSet.InstanceManagerRights = model.PermissionSet.InstanceManagerRights ?? currentGroup.PermissionSet.InstanceManagerRights;
            }
            currentGroup.Name = model.Name ?? currentGroup.Name;
            await DatabaseContext.Save(cancellationToken);
            if (!AuthenticationContext.PermissionSet.AdministrationRights!.Value.HasFlag(AdministrationRights.ReadUsers))
                return Json(new UserGroupResponse
                {
                    Id = currentGroup.Id,
                });
            return Json(currentGroup.ToApi(true));
        }
References Tgstation.Server.Api.Models.PermissionSet.AdministrationRights, Tgstation.Server.Host.Database.DatabaseContext.Groups, Tgstation.Server.Api.Models.Internal.UserGroup.Id, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Security.AuthenticationContext.PermissionSet, and Tgstation.Server.Host.Database.DatabaseContext.Save().
UserGroupResponse()
ValueTask< IActionResult > Tgstation.Server.Host.Controllers.UserGroupController.UserGroupResponse (() , ValueTask. FromResultnew PaginatableResult< UserGroup >(DatabaseContext .Groups .AsQueryable() .Include(x=> x.Users) .Include(x=> x.PermissionSet) .OrderBy(x=> x.Id)), null , page , pageSize , cancellationToken) private
Member Data Documentation
generalConfiguration
readonly GeneralConfiguration Tgstation.Server.Host.Controllers.UserGroupController.generalConfiguration private
The GeneralConfiguration for the UserGroupController.
Definition at line 35 of file UserGroupController.cs.
Referenced by Tgstation.Server.Host.Controllers.UserGroupController.Create(), and Tgstation.Server.Host.Controllers.UserGroupController.UserGroupController().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Controllers/UserGroupController.cs