tgstation-server: Tgstation.Server.Host.Security.AuthenticationContext Class Reference
Tgstation.Server.Host.Security.AuthenticationContext Class Reference
Public Member Functions
AuthenticationContext ()
Initializes a new instance of the AuthenticationContext class.
AuthenticationContext (ISystemIdentity systemIdentity, User user, InstancePermissionSet instanceUser)
Initializes a new instance of the AuthenticationContext class.
void Dispose ()
ulong GetRight (RightsType rightsType)
Get the value of a given rightsType .
ulong GetRight (RightsType rightsType)
Get the value of a given rightsType .
Properties
User User [get]
The authenticated user.
PermissionSet PermissionSet [get]
The User's effective PermissionSet.
InstancePermissionSet InstancePermissionSet [get]
The User's effective Models.InstancePermissionSet if applicable.
ISystemIdentity SystemIdentity [get]
The ISystemIdentity of User if applicable.
Properties inherited from Tgstation.Server.Host.Security.IAuthenticationContext
User User [get]
The authenticated user.
PermissionSet PermissionSet [get]
The User's effective PermissionSet.
InstancePermissionSet InstancePermissionSet [get]
The User's effective Models.InstancePermissionSet if applicable.
ISystemIdentity SystemIdentity [get]
The ISystemIdentity of User if applicable.
Detailed Description
Definition at line 10 of file AuthenticationContext.cs.
Constructor & Destructor Documentation
AuthenticationContext() [1/2]
Tgstation.Server.Host.Security.AuthenticationContext.AuthenticationContext ()
Initializes a new instance of the AuthenticationContext class.
Definition at line 27 of file AuthenticationContext.cs.
        {
        }
AuthenticationContext() [2/2]
Tgstation.Server.Host.Security.AuthenticationContext.AuthenticationContext (ISystemIdentity systemIdentity, User user, InstancePermissionSet instanceUser)
Initializes a new instance of the AuthenticationContext class.
Parameters
systemIdentity The value of SystemIdentity.
user The value of User.
instanceUser The value of InstancePermissionSet.
Definition at line 37 of file AuthenticationContext.cs.
        {
            User = user ?? throw new ArgumentNullException(nameof(user));
            if (systemIdentity == null && User.SystemIdentifier != null)
                throw new ArgumentNullException(nameof(systemIdentity));
            PermissionSet = user.PermissionSet
                ?? user.Group.PermissionSet
                ?? throw new ArgumentException("No PermissionSet provider", nameof(user));
            InstancePermissionSet = instanceUser;
            SystemIdentity = systemIdentity;
        }
References Tgstation.Server.Host.Models.User.Group, Tgstation.Server.Host.Models.User.PermissionSet, Tgstation.Server.Host.Models.UserGroup.PermissionSet, Tgstation.Server.Api.Models.Internal.UserModelBase.SystemIdentifier, and Tgstation.Server.Host.Security.AuthenticationContext.SystemIdentity.
Member Function Documentation
Dispose()
void Tgstation.Server.Host.Security.AuthenticationContext.Dispose ()
GetRight()
ulong Tgstation.Server.Host.Security.AuthenticationContext.GetRight (RightsType rightsType)
Get the value of a given rightsType .
Implements Tgstation.Server.Host.Security.IAuthenticationContext.
Definition at line 53 of file AuthenticationContext.cs.
        {
            var isInstance = RightsHelper.IsInstanceRight(rightsType);
            if (User == null)
                throw new InvalidOperationException("Authentication context has no user!");
            if (isInstance && InstancePermissionSet == null)
                return 0;
            var rightsEnum = RightsHelper.RightToType(rightsType);
            // use the api versions because they're the ones that contain the actual properties
            var typeToCheck = isInstance ? typeof(InstancePermissionSet) : typeof(PermissionSet);
            var nullableType = typeof(Nullable<>);
            var nullableRightsType = nullableType.MakeGenericType(rightsEnum);
            var prop = typeToCheck.GetProperties().Where(x => x.PropertyType == nullableRightsType).First();
            var right = prop.GetMethod.Invoke(isInstance ? (object)InstancePermissionSet : PermissionSet, Array.Empty<object>());
            if (right == null)
                throw new InvalidOperationException("A user right was null!");
            return (ulong)right;
        }
References Tgstation.Server.Api.Rights.RightsHelper.IsInstanceRight(), and Tgstation.Server.Api.Rights.RightsHelper.RightToType().
Referenced by Tgstation.Server.Host.Controllers.JobController.Delete(), Tgstation.Server.Host.Controllers.ChatController.GetId(), Tgstation.Server.Host.Controllers.UserController.GetId(), Tgstation.Server.Host.Controllers.ChatController.List(), Tgstation.Server.Host.Controllers.DreamDaemonController.ReadImpl(), Tgstation.Server.Host.Controllers.ChatController.Update(), Tgstation.Server.Host.Controllers.DreamDaemonController.Update(), Tgstation.Server.Host.Controllers.DreamMakerController.Update(), Tgstation.Server.Host.Controllers.InstancePermissionSetController.Update(), Tgstation.Server.Host.Controllers.InstanceController.Update(), Tgstation.Server.Host.Controllers.RepositoryController.Update(), and Tgstation.Server.Host.Controllers.UserController.Update().
Property Documentation
InstancePermissionSet
InstancePermissionSet Tgstation.Server.Host.Security.AuthenticationContext.InstancePermissionSet get
The User's effective Models.InstancePermissionSet if applicable.
Implements Tgstation.Server.Host.Security.IAuthenticationContext.
Definition at line 19 of file AuthenticationContext.cs.
{ get; }
Referenced by Tgstation.Server.Host.Controllers.ApiController.ApiController(), Tgstation.Server.Host.Controllers.ByondController.Update(), Tgstation.Server.Host.Controllers.DreamDaemonController.Update(), Tgstation.Server.Host.Controllers.DreamMakerController.Update(), and Tgstation.Server.Host.Controllers.InstanceRequiredController.ValidateRequest().
PermissionSet
PermissionSet Tgstation.Server.Host.Security.AuthenticationContext.PermissionSet get
The User's effective PermissionSet.
Implements Tgstation.Server.Host.Security.IAuthenticationContext.
Definition at line 16 of file AuthenticationContext.cs.
{ get; }
Referenced by Tgstation.Server.Host.Controllers.InstanceController.CheckAccessible(), Tgstation.Server.Host.Controllers.InstanceController.GetId(), Tgstation.Server.Host.Controllers.InstanceController.GrantPermissions(), Tgstation.Server.Host.Controllers.InstanceController.InstanceAdminPermissionSet(), Tgstation.Server.Host.Controllers.InstanceController.List(), Tgstation.Server.Host.Controllers.InstancePermissionSetController.Update(), Tgstation.Server.Host.Controllers.InstanceController.Update(), and Tgstation.Server.Host.Controllers.UserGroupController.Update().
SystemIdentity
ISystemIdentity Tgstation.Server.Host.Security.AuthenticationContext.SystemIdentity get
The ISystemIdentity of User if applicable.
Implements Tgstation.Server.Host.Security.IAuthenticationContext.
Definition at line 22 of file AuthenticationContext.cs.
{ get; }
Referenced by Tgstation.Server.Host.Security.AuthenticationContext.AuthenticationContext(), and Tgstation.Server.Host.Controllers.ConfigurationController.ForbidDueToModeConflicts().
User
User Tgstation.Server.Host.Security.AuthenticationContext.User get
The authenticated user.
Implements Tgstation.Server.Host.Security.IAuthenticationContext.
Definition at line 13 of file AuthenticationContext.cs.
{ get; }
Referenced by Tgstation.Server.Host.Controllers.DreamMakerController.Create(), Tgstation.Server.Host.Controllers.DreamDaemonController.CreateDump(), Tgstation.Server.Host.Controllers.UserController.CreateNewUserFromModel(), Tgstation.Server.Host.Controllers.RepositoryController.Delete(), Tgstation.Server.Host.Controllers.JobController.Delete(), Tgstation.Server.Host.Controllers.UserController.GetId(), Tgstation.Server.Host.Controllers.ApiController.OnActionExecutionAsync(), Tgstation.Server.Host.Controllers.DreamDaemonController.Restart(), Tgstation.Server.Host.Controllers.InstanceController.Update(), Tgstation.Server.Host.Controllers.RepositoryController.Update(), and Tgstation.Server.Host.Controllers.UserController.Update().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Security/AuthenticationContext.cs