tgstation-server: Tgstation.Server.Host.Controllers.ApiRootController Class Reference
Tgstation.Server.Host.Controllers.ApiRootController Class Reference sealed
Root ApiController for the Application.
Public Member Functions
ApiRootController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ITokenFactory tokenFactory, ISystemIdentityFactory systemIdentityFactory, ICryptographySuite cryptographySuite, IAssemblyInformationProvider assemblyInformationProvider, IIdentityCache identityCache, IOAuthProviders oAuthProviders, IPlatformIdentifier platformIdentifier, ISwarmService swarmService, IServerControl serverControl, IOptions< GeneralConfiguration > generalConfigurationOptions, ILogger< ApiRootController > logger, IApiHeadersProvider apiHeadersProvider)
Initializes a new instance of the ApiRootController class.
IActionResult ServerInfo ()
Main page of the Application.
async ValueTask< IActionResult > CreateToken (CancellationToken cancellationToken)
Attempt to authenticate a User using ApiController.ApiHeaders.
Public Member Functions inherited from Tgstation.Server.Host.Controllers.ApiControllerBase
override async Task OnActionExecutionAsync (ActionExecutingContext context, ActionExecutionDelegate next)
Private Attributes
readonly ITokenFactory tokenFactory
The ITokenFactory for the ApiRootController.
readonly ISystemIdentityFactory systemIdentityFactory
The ISystemIdentityFactory for the ApiRootController.
readonly ICryptographySuite cryptographySuite
The ICryptographySuite for the ApiRootController.
readonly IAssemblyInformationProvider assemblyInformationProvider
The IAssemblyInformationProvider for the ApiRootController.
readonly IIdentityCache identityCache
The IIdentityCache for the ApiRootController.
readonly IOAuthProviders oAuthProviders
The IOAuthProviders for the ApiRootController.
readonly IPlatformIdentifier platformIdentifier
The IPlatformIdentifier for the ApiRootController.
readonly ISwarmService swarmService
The ISwarmService for the ApiRootController.
readonly IServerControl serverControl
The IServerControl for the ApiRootController.
readonly GeneralConfiguration generalConfiguration
The GeneralConfiguration for the ApiRootController.
Additional Inherited Members
Protected Member Functions inherited from Tgstation.Server.Host.Controllers.ApiController
ApiController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, IApiHeadersProvider apiHeadersProvider, ILogger< ApiController > logger, bool requireHeaders)
Initializes a new instance of the ApiController class.
override async ValueTask< IActionResult?> HookExecuteAction (Func< Task > executeAction, CancellationToken cancellationToken)
Hook for executing a request.
Parameters
executeAction A Func<TResult> that should be invoked and its response awaited to continue normal execution of the request. Should NOT be called if this method returns a non-null value.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in an IActionResult that, if not null, is executed.
new NotFoundObjectResult NotFound ()
Generic 404 response.
new ObjectResult Unauthorized ()
Generic 401 response.
ObjectResult RequiresPosixSystemIdentity (NotImplementedException ex)
Generic 501 response.
StatusCodeResult StatusCode (HttpStatusCode statusCode)
Strongly type calls to ControllerBase.StatusCode(int).
ObjectResult Created (object payload)
Generic 201 response with a given payload .
ObjectResult RateLimit (RateLimitExceededException rateLimitException)
429 response for a given rateLimitException .
virtual ValueTask< IActionResult?> ValidateRequest (CancellationToken cancellationToken)
Performs validation a request.
IActionResult HeadersIssue (HeadersException headersException)
Response for missing/Invalid headers.
ValueTask< IActionResult > Paginated< TModel > (Func< ValueTask< PaginatableResult< TModel > > > queryGenerator, Func< TModel, ValueTask >? resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
ValueTask< IActionResult > Paginated< TModel, TApiModel > (Func< ValueTask< PaginatableResult< TModel > > > queryGenerator, Func< TApiModel, ValueTask >? resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
Properties inherited from Tgstation.Server.Host.Controllers.ApiController
ApiHeaders? ApiHeaders [get]
The Api.ApiHeaders for the operation.
IApiHeadersProvider ApiHeadersProvider [get]
The IApiHeadersProvider containing value of ApiHeaders.
IDatabaseContext DatabaseContext [get]
The IDatabaseContext for the operation.
IAuthenticationContext AuthenticationContext [get]
The IAuthenticationContext for the operation.
ILogger< ApiController > Logger [get]
The ILogger for the ApiController.
Models.? Instance Instance [get]
The Instance for the operation.
Detailed Description
Root ApiController for the Application.
Definition at line 36 of file ApiRootController.cs.
Constructor & Destructor Documentation
ApiRootController()
Tgstation.Server.Host.Controllers.ApiRootController.ApiRootController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ITokenFactory tokenFactory, ISystemIdentityFactory systemIdentityFactory, ICryptographySuite cryptographySuite, IAssemblyInformationProvider assemblyInformationProvider, IIdentityCache identityCache, IOAuthProviders oAuthProviders, IPlatformIdentifier platformIdentifier, ISwarmService swarmService, IServerControl serverControl, IOptions< GeneralConfiguration > generalConfigurationOptions, ILogger< ApiRootController > logger, IApiHeadersProvider apiHeadersProvider)
Initializes a new instance of the ApiRootController class.
Parameters
databaseContext The IDatabaseContext for the ApiController.
authenticationContext The IAuthenticationContext for the ApiController.
tokenFactory The value of tokenFactory.
systemIdentityFactory The value of systemIdentityFactory.
cryptographySuite The value of cryptographySuite.
assemblyInformationProvider The value of assemblyInformationProvider.
identityCache The value of identityCache.
oAuthProviders The value of oAuthProviders.
platformIdentifier The value of platformIdentifier.
swarmService The value of swarmService.
serverControl The value of serverControl.
generalConfigurationOptions The IOptions<TOptions> containing the value of generalConfiguration.
logger The ILogger for the ApiController.
apiHeadersProvider The IApiHeadersProvider for the ApiController.
Definition at line 105 of file ApiRootController.cs.
            : base(
                  databaseContext,
                  authenticationContext,
                  apiHeadersProvider,
                  logger,
                  false)
        {
            this.tokenFactory = tokenFactory ?? throw new ArgumentNullException(nameof(tokenFactory));
            this.systemIdentityFactory = systemIdentityFactory ?? throw new ArgumentNullException(nameof(systemIdentityFactory));
            this.cryptographySuite = cryptographySuite ?? throw new ArgumentNullException(nameof(cryptographySuite));
            this.assemblyInformationProvider = assemblyInformationProvider ?? throw new ArgumentNullException(nameof(assemblyInformationProvider));
            this.identityCache = identityCache ?? throw new ArgumentNullException(nameof(identityCache));
            this.platformIdentifier = platformIdentifier ?? throw new ArgumentNullException(nameof(platformIdentifier));
            this.oAuthProviders = oAuthProviders ?? throw new ArgumentNullException(nameof(oAuthProviders));
            this.swarmService = swarmService ?? throw new ArgumentNullException(nameof(swarmService));
            this.serverControl = serverControl ?? throw new ArgumentNullException(nameof(serverControl));
            generalConfiguration = generalConfigurationOptions?.Value ?? throw new ArgumentNullException(nameof(generalConfigurationOptions));
        }
References Tgstation.Server.Host.Controllers.ApiRootController.assemblyInformationProvider, Tgstation.Server.Host.Controllers.ApiRootController.cryptographySuite, Tgstation.Server.Host.Controllers.ApiRootController.generalConfiguration, Tgstation.Server.Host.Controllers.ApiRootController.identityCache, Tgstation.Server.Host.Controllers.ApiRootController.oAuthProviders, Tgstation.Server.Host.Controllers.ApiRootController.platformIdentifier, Tgstation.Server.Host.Controllers.ApiRootController.serverControl, Tgstation.Server.Host.Controllers.ApiRootController.swarmService, Tgstation.Server.Host.Controllers.ApiRootController.systemIdentityFactory, and Tgstation.Server.Host.Controllers.ApiRootController.tokenFactory.
Member Function Documentation
CreateToken()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.ApiRootController.CreateToken (CancellationToken cancellationToken)
Attempt to authenticate a User using ApiController.ApiHeaders.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the operation.
<response code="200">User logged in and TokenResponse generated successfully.</response> <response code="401">User authentication failed.</response> <response code="403">User authenticated but is disabled by an administrator.</response> <response code="429">OAuth authentication failed due to rate limiting.</response>
Definition at line 206 of file ApiRootController.cs.
        {
            if (ApiHeaders == null)
            {
                Response.Headers.Add(HeaderNames.WWWAuthenticate, new StringValues($"basic realm=\"Create TGS {ApiHeaders.BearerAuthenticationScheme} token\""));
                return HeadersIssue(ApiHeadersProvider.HeadersException!);
            }
            if (ApiHeaders.IsTokenAuthentication)
                return BadRequest(new ErrorMessageResponse(ErrorCode.TokenWithToken));
            var oAuthLogin = ApiHeaders.OAuthProvider.HasValue;
            ISystemIdentity? systemIdentity = null;
            if (!oAuthLogin)
                try
                {
                    // trust the system over the database because a user's name can change while still having the same SID
                    systemIdentity = await systemIdentityFactory.CreateSystemIdentity(ApiHeaders.Username!, ApiHeaders.Password!, cancellationToken);
                }
                catch (NotImplementedException)
                {
                    // Intentionally suppressed
                }
            using (systemIdentity)
            {
                // Get the user from the database
                IQueryable<Models.User> query = DatabaseContext.Users.AsQueryable();
                if (oAuthLogin)
                {
                    var oAuthProvider = ApiHeaders.OAuthProvider!.Value;
                    string? externalUserId;
                    try
                    {
                        var validator = oAuthProviders
                            .GetValidator(oAuthProvider);
                        if (validator == null)
                            return BadRequest(new ErrorMessageResponse(ErrorCode.OAuthProviderDisabled));
                        externalUserId = await validator
                            .ValidateResponseCode(ApiHeaders.OAuthCode!, cancellationToken);
                        Logger.LogTrace("External {oAuthProvider} UID: {externalUserId}", oAuthProvider, externalUserId);
                    }
                    catch (RateLimitExceededException ex)
                    {
                        return RateLimit(ex);
                    }
                    if (externalUserId == null)
                        return Unauthorized();
                    query = query.Where(
                        x => x.OAuthConnections!.Any(
                            y => y.Provider == oAuthProvider
                            && y.ExternalUserId == externalUserId));
                }
                else
                {
                    var canonicalUserName = Models.User.CanonicalizeName(ApiHeaders.Username!);
                    if (canonicalUserName == Models.User.CanonicalizeName(Models.User.TgsSystemUserName))
                        return Unauthorized();
                    if (systemIdentity == null)
                        query = query.Where(x => x.CanonicalName == canonicalUserName);
                    else
                        query = query.Where(x => x.CanonicalName == canonicalUserName || x.SystemIdentifier == systemIdentity.Uid);
                }
                var users = await query
                    .Select(x => new Models.User
                    {
                        Id = x.Id,
                        PasswordHash = x.PasswordHash,
                        Enabled = x.Enabled,
                        Name = x.Name,
                        SystemIdentifier = x.SystemIdentifier,
                    })
                    .ToListAsync(cancellationToken);
                // Pick the DB user first
                var user = users
                    .OrderByDescending(dbUser => dbUser.SystemIdentifier == null)
                    .FirstOrDefault();
                // No user? You're not allowed
                if (user == null)
                    return Unauthorized();
                // A system user may have had their name AND password changed to one in our DB...
                // Or a DB user was created that had the same user/pass as a system user
                // Dumb admins...
                // FALLBACK TO THE DB USER HERE, DO NOT REVEAL A SYSTEM LOGIN!!!
                // This of course, allows system users to discover TGS users in this (HIGHLY IMPROBABLE) case but that is not our fault
                var originalHash = user.PasswordHash;
                var isLikelyDbUser = originalHash != null;
                bool usingSystemIdentity = systemIdentity != null && !isLikelyDbUser;
                if (!oAuthLogin)
                    if (!usingSystemIdentity)
                    {
                        // DB User password check and update
                        if (!isLikelyDbUser || !cryptographySuite.CheckUserPassword(user, ApiHeaders.Password!))
                            return Unauthorized();
                        if (user.PasswordHash != originalHash)
{
                            Logger.LogDebug("User ID {userId}'s password hash needs a refresh, updating database.", user.Id);
                            var updatedUser = new Models.User
{
                                Id = user.Id,
                            };
                            DatabaseContext.Users.Attach(updatedUser);
                            updatedUser.PasswordHash = user.PasswordHash;
                            await DatabaseContext.Save(cancellationToken);
                        }
                    }
                    else
                    {
                        var usernameMismatch = systemIdentity!.Username != user.Name;
                        if (isLikelyDbUser || usernameMismatch)
{
                            DatabaseContext.Users.Attach(user);
                            if (isLikelyDbUser)
{
                                // cleanup from https://github.com/tgstation/tgstation-server/issues/1528
                                Logger.LogDebug("System user ID {userId}'s PasswordHash is polluted, updating database.", user.Id);
                                user.PasswordHash = null;
                                user.LastPasswordUpdate = DateTimeOffset.UtcNow;
                            }
                            if (usernameMismatch)
{
                                // System identity username change update
                                Logger.LogDebug("User ID {userId}'s system identity needs a refresh, updating database.", user.Id);
                                user.Name = systemIdentity.Username;
                                user.CanonicalName = Models.User.CanonicalizeName(user.Name);
                            }
                            await DatabaseContext.Save(cancellationToken);
                        }
                    }
                // Now that the bookeeping is done, tell them to fuck off if necessary
                if (!user.Enabled!.Value)
                {
                    Logger.LogTrace("Not logging in disabled user {userId}.", user.Id);
                    return Forbid();
                }
                var token = tokenFactory.CreateToken(user, oAuthLogin);
                if (usingSystemIdentity)
                {
                    // expire the identity slightly after the auth token in case of lag
                    var identExpiry = token.ParseJwt().ValidTo;
                    identExpiry += tokenFactory.ValidationParameters.ClockSkew;
                    identExpiry += TimeSpan.FromSeconds(15);
                    await identityCache.CacheSystemIdentity(user, systemIdentity!, identExpiry);
                }
                Logger.LogDebug("Successfully logged in user {userId}!", user.Id);
                return Json(token);
            }
        }
References Tgstation.Server.Host.Security.IIdentityCache.CacheSystemIdentity(), Tgstation.Server.Host.Security.ICryptographySuite.CheckUserPassword(), Tgstation.Server.Host.Security.ISystemIdentityFactory.CreateSystemIdentity(), Tgstation.Server.Host.Security.ITokenFactory.CreateToken(), Tgstation.Server.Host.Controllers.ApiRootController.cryptographySuite, Tgstation.Server.Host.Security.OAuth.IOAuthProviders.GetValidator(), Tgstation.Server.Host.Utils.ApiHeadersProvider.HeadersException, Tgstation.Server.Host.Controllers.ApiController.HeadersIssue(), Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Host.Controllers.ApiRootController.identityCache, Tgstation.Server.Api.ApiHeaders.IsTokenAuthentication, Tgstation.Server.Host.Controllers.ApiController.Logger, Tgstation.Server.Api.ApiHeaders.OAuthCode, Tgstation.Server.Api.ApiHeaders.OAuthProvider, Tgstation.Server.Host.Controllers.ApiRootController.oAuthProviders, Tgstation.Server.Api.Models.Response.TokenResponse.ParseJwt(), Tgstation.Server.Api.ApiHeaders.Password, Tgstation.Server.Host.Controllers.ApiController.RateLimit(), Tgstation.Server.Host.Database.DatabaseContext.Save(), Tgstation.Server.Host.Controllers.ApiRootController.systemIdentityFactory, Tgstation.Server.Host.Controllers.ApiRootController.tokenFactory, Tgstation.Server.Host.Security.ISystemIdentity.Uid, Tgstation.Server.Host.Controllers.ApiController.Unauthorized(), Tgstation.Server.Api.ApiHeaders.Username, Tgstation.Server.Host.Security.ISystemIdentity.Username, Tgstation.Server.Host.Database.DatabaseContext.Users, and Tgstation.Server.Host.Security.ITokenFactory.ValidationParameters.
Referenced by Tgstation.Server.Host.Utils.SwaggerConfiguration.Apply().
ServerInfo()
IActionResult Tgstation.Server.Host.Controllers.ApiRootController.ServerInfo ()
Main page of the Application.
Returns
The JsonResult containing ServerInformationResponse of the Application if a properly authenticated API request, the web control panel if on a browser and enabled, UnauthorizedResult otherwise.
<response code="200">ServerInformationResponse retrieved successfully.</response>
Definition at line 149 of file ApiRootController.cs.
        {
            // if they tried to authenticate in any form and failed, let them know immediately
            bool failIfUnauthed;
            if (ApiHeaders == null)
            {
                try
                {
                    // we only allow authorization header issues
                    ApiHeadersProvider.CreateAuthlessHeaders();
                }
                catch (HeadersException ex)
                {
                    return HeadersIssue(ex);
                }
                failIfUnauthed = Request.Headers.Authorization.Count > 0;
            }
            else
                failIfUnauthed = ApiHeaders.Token != null;
            if (failIfUnauthed && !AuthenticationContext.Valid)
                return Unauthorized();
            return Json(new ServerInformationResponse
            {
                Version = assemblyInformationProvider.Version,
                ApiVersion = ApiHeaders.Version,
                DMApiVersion = DMApiConstants.InteropVersion,
                MinimumPasswordLength = generalConfiguration.MinimumPasswordLength,
                InstanceLimit = generalConfiguration.InstanceLimit,
                UserLimit = generalConfiguration.UserLimit,
                UserGroupLimit = generalConfiguration.UserGroupLimit,
                ValidInstancePaths = generalConfiguration.ValidInstancePaths,
                WindowsHost = platformIdentifier.IsWindows,
                SwarmServers = swarmService
                    .GetSwarmServers()
                    ?.Select(swarmServerInfo => new SwarmServerResponse(swarmServerInfo))
                    .ToList(),
                OAuthProviderInfos = oAuthProviders.ProviderInfos(),
                UpdateInProgress = serverControl.UpdateInProgress,
            });
        }
References Tgstation.Server.Host.Controllers.ApiRootController.assemblyInformationProvider, Tgstation.Server.Host.Utils.ApiHeadersProvider.CreateAuthlessHeaders(), Tgstation.Server.Host.Controllers.ApiRootController.generalConfiguration, Tgstation.Server.Host.Swarm.ISwarmService.GetSwarmServers(), Tgstation.Server.Host.Controllers.ApiController.HeadersIssue(), Tgstation.Server.Api.Models.Internal.ServerInformationBase.InstanceLimit, Tgstation.Server.Host.Components.Interop.DMApiConstants.InteropVersion, Tgstation.Server.Host.System.IPlatformIdentifier.IsWindows, Tgstation.Server.Api.Models.Internal.ServerInformationBase.MinimumPasswordLength, Tgstation.Server.Host.Controllers.ApiRootController.oAuthProviders, Tgstation.Server.Host.Controllers.ApiRootController.platformIdentifier, Tgstation.Server.Host.Security.OAuth.IOAuthProviders.ProviderInfos(), Tgstation.Server.Host.Controllers.ApiRootController.serverControl, Tgstation.Server.Host.Controllers.ApiRootController.swarmService, Tgstation.Server.Host.Controllers.ApiController.Unauthorized(), Tgstation.Server.Host.Core.IServerControl.UpdateInProgress, Tgstation.Server.Host.Core.UpdateInProgress, Tgstation.Server.Api.Models.Internal.ServerInformationBase.UserGroupLimit, Tgstation.Server.Api.Models.Internal.ServerInformationBase.UserLimit, Tgstation.Server.Host.Security.AuthenticationContext.Valid, Tgstation.Server.Api.Models.Internal.ServerInformationBase.ValidInstancePaths, Tgstation.Server.Api.ApiHeaders.Version, and Tgstation.Server.Host.System.IAssemblyInformationProvider.Version.
Member Data Documentation
assemblyInformationProvider
readonly IAssemblyInformationProvider Tgstation.Server.Host.Controllers.ApiRootController.assemblyInformationProvider private
The IAssemblyInformationProvider for the ApiRootController.
Definition at line 56 of file ApiRootController.cs.
Referenced by Tgstation.Server.Host.Controllers.ApiRootController.ApiRootController(), and Tgstation.Server.Host.Controllers.ApiRootController.ServerInfo().
cryptographySuite
readonly ICryptographySuite Tgstation.Server.Host.Controllers.ApiRootController.cryptographySuite private
The ICryptographySuite for the ApiRootController.
Definition at line 51 of file ApiRootController.cs.
Referenced by Tgstation.Server.Host.Controllers.ApiRootController.ApiRootController(), and Tgstation.Server.Host.Controllers.ApiRootController.CreateToken().
generalConfiguration
readonly GeneralConfiguration Tgstation.Server.Host.Controllers.ApiRootController.generalConfiguration private
The GeneralConfiguration for the ApiRootController.
Definition at line 86 of file ApiRootController.cs.
Referenced by Tgstation.Server.Host.Controllers.ApiRootController.ApiRootController(), and Tgstation.Server.Host.Controllers.ApiRootController.ServerInfo().
identityCache
readonly IIdentityCache Tgstation.Server.Host.Controllers.ApiRootController.identityCache private
The IIdentityCache for the ApiRootController.
Definition at line 61 of file ApiRootController.cs.
Referenced by Tgstation.Server.Host.Controllers.ApiRootController.ApiRootController(), and Tgstation.Server.Host.Controllers.ApiRootController.CreateToken().
oAuthProviders
readonly IOAuthProviders Tgstation.Server.Host.Controllers.ApiRootController.oAuthProviders private
The IOAuthProviders for the ApiRootController.
Definition at line 66 of file ApiRootController.cs.
Referenced by Tgstation.Server.Host.Controllers.ApiRootController.ApiRootController(), Tgstation.Server.Host.Controllers.ApiRootController.CreateToken(), and Tgstation.Server.Host.Controllers.ApiRootController.ServerInfo().
platformIdentifier
readonly IPlatformIdentifier Tgstation.Server.Host.Controllers.ApiRootController.platformIdentifier private
The IPlatformIdentifier for the ApiRootController.
Definition at line 71 of file ApiRootController.cs.
Referenced by Tgstation.Server.Host.Controllers.ApiRootController.ApiRootController(), and Tgstation.Server.Host.Controllers.ApiRootController.ServerInfo().
serverControl
readonly IServerControl Tgstation.Server.Host.Controllers.ApiRootController.serverControl private
The IServerControl for the ApiRootController.
Definition at line 81 of file ApiRootController.cs.
Referenced by Tgstation.Server.Host.Controllers.ApiRootController.ApiRootController(), and Tgstation.Server.Host.Controllers.ApiRootController.ServerInfo().
swarmService
readonly ISwarmService Tgstation.Server.Host.Controllers.ApiRootController.swarmService private
The ISwarmService for the ApiRootController.
Definition at line 76 of file ApiRootController.cs.
Referenced by Tgstation.Server.Host.Controllers.ApiRootController.ApiRootController(), and Tgstation.Server.Host.Controllers.ApiRootController.ServerInfo().
systemIdentityFactory
readonly ISystemIdentityFactory Tgstation.Server.Host.Controllers.ApiRootController.systemIdentityFactory private
The ISystemIdentityFactory for the ApiRootController.
Definition at line 46 of file ApiRootController.cs.
Referenced by Tgstation.Server.Host.Controllers.ApiRootController.ApiRootController(), and Tgstation.Server.Host.Controllers.ApiRootController.CreateToken().
tokenFactory
readonly ITokenFactory Tgstation.Server.Host.Controllers.ApiRootController.tokenFactory private
The ITokenFactory for the ApiRootController.
Definition at line 41 of file ApiRootController.cs.
Referenced by Tgstation.Server.Host.Controllers.ApiRootController.ApiRootController(), and Tgstation.Server.Host.Controllers.ApiRootController.CreateToken().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Controllers/ApiRootController.cs