tgstation-server: Tgstation.Server.Host.GraphQL.Mutations.UserGroupMutations Class Reference
Tgstation.Server.Host.GraphQL.Mutations.UserGroupMutations Class Reference sealed
IUserGroupAuthority related Mutations.
Public Member Functions
ValueTask< UserGroup > CreateUserGroup (string name, PermissionSetInput? permissionSet, [Service] IGraphQLAuthorityInvoker< IUserGroupAuthority > userGroupAuthority, CancellationToken cancellationToken)
Creates a UserGroup.
ValueTask< UserGroup > UpdateUserGroup ([ID(nameof(UserGroup))] long id, string? newName, PermissionSetInput? newPermissionSet, [Service] IGraphQLAuthorityInvoker< IUserGroupAuthority > userGroupAuthority, CancellationToken cancellationToken)
Updates a UserGroup.
async ValueTask< Query > DeleteEmptyUserGroup ([ID(nameof(UserGroup))] long id, [Service] IGraphQLAuthorityInvoker< IUserGroupAuthority > userGroupAuthority, CancellationToken cancellationToken)
Deletes a UserGroup.
Static Private Member Functions
static Models.? PermissionSet TransformApiPermissionSet (PermissionSetInput? permissionSet)
Transform a Api.Models.PermissionSet into a PermissionSet.
Detailed Description
IUserGroupAuthority related Mutations.
Definition at line 22 of file UserGroupMutations.cs.
Member Function Documentation
CreateUserGroup()
ValueTask< UserGroup > Tgstation.Server.Host.GraphQL.Mutations.UserGroupMutations.CreateUserGroup (string name, PermissionSetInput? permissionSet, [Service] IGraphQLAuthorityInvoker< IUserGroupAuthority > userGroupAuthority, CancellationToken cancellationToken)
Creates a UserGroup.
Parameters
name The NamedEntity.Name of the UserGroup.
permissionSet The initial permission set for the UserGroup.
userGroupAuthority The IGraphQLAuthorityInvoker<TAuthority> for the IUserGroupAuthority.
cancellationToken The CancellationToken for the operation.
Returns
The created UserGroup.
Definition at line 48 of file UserGroupMutations.cs.
        {
            ArgumentNullException.ThrowIfNull(name);
            ArgumentNullException.ThrowIfNull(userGroupAuthority);
            return userGroupAuthority.InvokeTransformable<Models.UserGroup, UserGroup, UserGroupGraphQLTransformer>(
                authority => authority.Create(name, TransformApiPermissionSet(permissionSet), cancellationToken));
        }
References Tgstation.Server.Host.GraphQL.Mutations.UserGroupMutations.TransformApiPermissionSet().
DeleteEmptyUserGroup()
async ValueTask< Query > Tgstation.Server.Host.GraphQL.Mutations.UserGroupMutations.DeleteEmptyUserGroup ([ID(nameof(UserGroup))] long id, [Service] IGraphQLAuthorityInvoker< IUserGroupAuthority > userGroupAuthority, CancellationToken cancellationToken)
Deletes a UserGroup.
Parameters
id The Entity.Id of the UserGroup to update.
userGroupAuthority The IGraphQLAuthorityInvoker<TAuthority> for the IUserGroupAuthority.
cancellationToken The CancellationToken for the operation.
Returns
The Query root.
Definition at line 93 of file UserGroupMutations.cs.
        {
            ArgumentNullException.ThrowIfNull(userGroupAuthority);
            await userGroupAuthority.Invoke(
                authority => authority.DeleteEmpty(id, cancellationToken));
            return new Query();
        }
TransformApiPermissionSet()
static Models.? PermissionSet Tgstation.Server.Host.GraphQL.Mutations.UserGroupMutations.TransformApiPermissionSet (PermissionSetInput? permissionSet) static private
Transform a Api.Models.PermissionSet into a PermissionSet.
Parameters
permissionSet The Api.Models.PermissionSet to transform.
Returns
The transformed permissionSet .
Referenced by Tgstation.Server.Host.GraphQL.Mutations.UserGroupMutations.CreateUserGroup(), and Tgstation.Server.Host.GraphQL.Mutations.UserGroupMutations.UpdateUserGroup().
UpdateUserGroup()
ValueTask< UserGroup > Tgstation.Server.Host.GraphQL.Mutations.UserGroupMutations.UpdateUserGroup ([ID(nameof(UserGroup))] long id, string? newName, PermissionSetInput? newPermissionSet, [Service] IGraphQLAuthorityInvoker< IUserGroupAuthority > userGroupAuthority, CancellationToken cancellationToken)
Updates a UserGroup.
Parameters
id The Entity.Id of the UserGroup to update.
newName Optional new NamedEntity.Name for the UserGroup.
newPermissionSet Optional new permission set for the UserGroup.
userGroupAuthority The IGraphQLAuthorityInvoker<TAuthority> for the IUserGroupAuthority.
cancellationToken The CancellationToken for the operation.
Returns
The updated UserGroup.
Definition at line 72 of file UserGroupMutations.cs.
        {
            ArgumentNullException.ThrowIfNull(userGroupAuthority);
            return userGroupAuthority.InvokeTransformable<Models.UserGroup, UserGroup, UserGroupGraphQLTransformer>(
                authority => authority.Update(id, newName, TransformApiPermissionSet(newPermissionSet), cancellationToken));
        }
References Tgstation.Server.Host.GraphQL.Mutations.UserGroupMutations.TransformApiPermissionSet().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/GraphQL/Mutations/UserGroupMutations.cs