tgstation-server: Tgstation.Server.Host.Components.Chat.Providers.IrcProvider Class Reference
Tgstation.Server.Host.Components.Chat.Providers.IrcProvider Class Reference sealed
IProvider for internet relay chat.
Public Member Functions
IrcProvider (IJobManager jobManager, IAsyncDelayer asyncDelayer, ILogger< IrcProvider > logger, IAssemblyInformationProvider assemblyInformationProvider, Models.ChatBot chatBot, FileLoggingConfiguration loggingConfiguration)
Initializes a new instance of the IrcProvider class.
override async ValueTask DisposeAsync ()
override async ValueTask SendMessage (Message? replyTo, MessageContent message, ulong channelId, CancellationToken cancellationToken)
Send a message to the IProvider.
Parameters
replyTo The optional Message to reply to.
message The MessageContent.
channelId The ChannelRepresentation.RealId to send to.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
override async ValueTask< Func< string?, string, ValueTask< Func< bool, ValueTask > > > > SendUpdateMessage (Models.RevisionInformation revisionInformation, EngineVersion engineVersion, DateTimeOffset? estimatedCompletionTime, string? gitHubOwner, string? gitHubRepo, ulong channelId, bool localCommitPushed, CancellationToken cancellationToken)
Send the message for a deployment.
Parameters
revisionInformation The RevisionInformation of the deployment.
engineVersion The Api.Models.EngineVersion of the deployment.
estimatedCompletionTime The optional DateTimeOffset the deployment is expected to be completed at.
gitHubOwner The repository GitHub owner, if any.
gitHubRepo The repository GitHub name, if any.
channelId The ChannelRepresentation.RealId to send to.
localCommitPushed true if the local deployment commit was pushed to the remote repository.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a Func<T1, T2, TResult> to call to update the message at the deployment's conclusion. Parameters: Error message if any, DreamMaker output if any. Returns another callback which should be called to mark the deployment as active.
Public Member Functions inherited from Tgstation.Server.Host.Components.Chat.Providers.Provider
async ValueTask Disconnect (CancellationToken cancellationToken)
Gracefully disconnects the provider. Permanently stops the reconnection timer.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
void InitialMappingComplete ()
Indicate to the provider that at least one MapChannels(IEnumerable<ChatChannel>, CancellationToken) call has successfully completed.
async ValueTask< Dictionary< ChatChannel, IEnumerable< ChannelRepresentation > > > MapChannels (IEnumerable< ChatChannel > channels, CancellationToken cancellationToken)
Get the ChannelRepresentations for given channels .
Parameters
channels The Api.Models.ChatChannels to map.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a Dictionary<TKey, TValue> of the ChatChannel's ChannelRepresentations representing channels .
async Task< Message?> NextMessage (CancellationToken cancellationToken)
Get a Task<TResult> resulting in the next Message the IProvider receives or null on a disconnect.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the next available Message or null if the IProvider needed to reconnect.
Note that private messages will come in the form of ChannelRepresentations not returned in MapChannels(IEnumerable<ChatChannel>, CancellationToken).
Task SetReconnectInterval (uint reconnectInterval, bool connectNow)
Set the interval at which the provider starts jobs to try to reconnect.
Parameters
reconnectInterval The reconnection interval in minutes.
connectNow If a connection attempt should be made now.
Returns
A Task representing the running operation.
ValueTask SendMessage (Message? replyTo, MessageContent message, ulong channelId, CancellationToken cancellationToken)
Send a message to the IProvider.
Parameters
replyTo The optional Message to reply to.
message The MessageContent.
channelId The ChannelRepresentation.RealId to send to.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
ValueTask< Func< string?, string, ValueTask< Func< bool, ValueTask > > > > SendUpdateMessage (RevisionInformation revisionInformation, Api.Models.EngineVersion engineVersion, DateTimeOffset? estimatedCompletionTime, string? gitHubOwner, string? gitHubRepo, ulong channelId, bool localCommitPushed, CancellationToken cancellationToken)
Send the message for a deployment.
Parameters
revisionInformation The RevisionInformation of the deployment.
engineVersion The Api.Models.EngineVersion of the deployment.
estimatedCompletionTime The optional DateTimeOffset the deployment is expected to be completed at.
gitHubOwner The repository GitHub owner, if any.
gitHubRepo The repository GitHub name, if any.
channelId The ChannelRepresentation.RealId to send to.
localCommitPushed true if the local deployment commit was pushed to the remote repository.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a Func<T1, T2, TResult> to call to update the message at the deployment's conclusion. Parameters: Error message if any, DreamMaker output if any. Returns another callback which should be called to mark the deployment as active.
Protected Member Functions
override async ValueTask< Dictionary< Models.ChatChannel, IEnumerable< ChannelRepresentation > > > MapChannelsImpl (IEnumerable< Models.ChatChannel > channels, CancellationToken cancellationToken)
override async ValueTask Connect (CancellationToken cancellationToken)
override async ValueTask DisconnectImpl (CancellationToken cancellationToken)
Protected Member Functions inherited from Tgstation.Server.Host.Components.Chat.Providers.Provider
Provider (IJobManager jobManager, IAsyncDelayer asyncDelayer, ILogger< Provider > logger, ChatBot chatBot)
Initializes a new instance of the Provider class.
ValueTask Connect (CancellationToken cancellationToken)
Attempt to connect the Provider.
ValueTask DisconnectImpl (CancellationToken cancellationToken)
Gracefully disconnects the provider.
ValueTask< Dictionary< ChatChannel, IEnumerable< ChannelRepresentation > > > MapChannelsImpl (IEnumerable< ChatChannel > channels, CancellationToken cancellationToken)
Implementation of MapChannels(IEnumerable<ChatChannel>, CancellationToken).
void EnqueueMessage (Message? message)
Queues a message for NextMessage(CancellationToken).
Properties
override bool Connected [get]
If the IProvider is currently connected.
override string BotMention [get]
The string that indicates the IProvider was mentioned.
Properties inherited from Tgstation.Server.Host.Components.Chat.Providers.Provider
Task InitialConnectionJob [get]
A Task that completes once the IProvider finishes it's first connection attempt regardless of success.
ChatBot ChatBot [get]
The ChatBot the Provider is for.
IAsyncDelayer AsyncDelayer [get]
The IAsyncDelayer for the Provider.
ILogger< Provider > Logger [get]
The ILogger for the Provider.
bool Connected [get]
If the IProvider is currently connected.
string BotMention [get]
The string that indicates the IProvider was mentioned.
bool Disposed [get, private set]
If the IProvider was disposed.
Properties inherited from Tgstation.Server.Host.Components.Chat.Providers.IProvider
Private Member Functions
async ValueTask Login (IrcFeatures client, string nickname, CancellationToken cancellationToken)
Register the client on the network.
void HandleMessage (IrcEventArgs e, bool isPrivate)
Handle an IRC message.
void Client_OnQueryMessage (object sender, IrcEventArgs e)
When a query message is received in IRC.
void Client_OnChannelMessage (object sender, IrcEventArgs e)
When a channel message is received in IRC.
Task NonBlockingListen (CancellationToken cancellationToken)
Perform a non-blocking IrcConnection.Listen(bool).
async ValueTask SaslAuthenticate (CancellationToken cancellationToken)
Run SASL authentication on client.
async ValueTask HardDisconnect (CancellationToken cancellationToken)
Attempt to disconnect from IRC immediately.
IrcFeatures InstantiateClient ()
Creates a new instance of the IRC client. Reusing the same client after a disconnection seems to cause issues.
Private Attributes
readonly string address
Address of the server to connect to.
readonly ushort port
Port of the server to connect to.
readonly bool ssl
Wether or not this IRC client is to use ssl.
readonly string nickname
IRC nickname.
readonly string password
Password which will used for authentication.
readonly? IrcPasswordType passwordType
The IrcPasswordType of password.
readonly Dictionary< ulong, string?> channelIdMap
Map of ChannelRepresentation.RealIds to channel names.
readonly Dictionary< ulong, string > queryChannelIdMap
Map of ChannelRepresentation.RealIds to query users.
readonly IAssemblyInformationProvider assemblyInfo
The IAssemblyInformationProvider obtained from constructor, used for the CTCP version string.
readonly FileLoggingConfiguration loggingConfiguration
The FileLoggingConfiguration for the IrcProvider.
IrcFeatures client
The IrcFeatures client.
Task? listenTask
The ValueTask used for IrcConnection.Listen(bool).
ulong channelIdCounter
Id counter for channelIdMap.
Static Private Attributes
const int PreambleMessageLength = 12
Length of the preamble when writing a message to the server. Must be summed with the channel name to get the true value.
const int MessageBytesLimit = 512
Hard limit to sendable message size in bytes.
Additional Inherited Members
Static Protected Member Functions inherited from Tgstation.Server.Host.Components.Chat.Providers.Provider
static string GetEngineCompilerPrefix (Api.Models.EngineType engineType)
Get the prefix for messages about deployments.
Detailed Description
IProvider for internet relay chat.
Definition at line 28 of file IrcProvider.cs.
Constructor & Destructor Documentation
IrcProvider()
Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.IrcProvider (IJobManager jobManager, IAsyncDelayer asyncDelayer, ILogger< IrcProvider > logger, IAssemblyInformationProvider assemblyInformationProvider, Models::ChatBot chatBot, FileLoggingConfiguration loggingConfiguration)
Initializes a new instance of the IrcProvider class.
Parameters
jobManager The IJobManager for the Provider.
asyncDelayer The IAsyncDelayer for the Provider.
logger The ILogger for the Provider.
assemblyInformationProvider The IAssemblyInformationProvider to get the IAssemblyInformationProvider.VersionString from.
chatBot The Models.ChatBot for the Provider.
loggingConfiguration The FileLoggingConfiguration for the Provider.
Definition at line 120 of file IrcProvider.cs.
            : base(jobManager, asyncDelayer, logger, chatBot)
        {
            ArgumentNullException.ThrowIfNull(assemblyInformationProvider);
            ArgumentNullException.ThrowIfNull(loggingConfiguration);
            var builder = chatBot.CreateConnectionStringBuilder();
            if (builder == null || !builder.Valid || builder is not IrcConnectionStringBuilder ircBuilder)
                throw new InvalidOperationException("Invalid ChatConnectionStringBuilder!");
            address = ircBuilder.Address!;
            port = ircBuilder.Port!.Value;
            ssl = ircBuilder.UseSsl!.Value;
            nickname = ircBuilder.Nickname!;
            password = ircBuilder.Password!;
            passwordType = ircBuilder.PasswordType;
            assemblyInfo = assemblyInformationProvider ?? throw new ArgumentNullException(nameof(assemblyInformationProvider));
            this.loggingConfiguration = loggingConfiguration ?? throw new ArgumentNullException(nameof(loggingConfiguration));
            client = InstantiateClient();
            channelIdMap = new Dictionary<ulong, string?>();
            queryChannelIdMap = new Dictionary<ulong, string>();
            channelIdCounter = 1;
        }
References Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.address, Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.assemblyInfo, Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.channelIdCounter, Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.channelIdMap, Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.client, Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.InstantiateClient(), Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.loggingConfiguration, Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.nickname, Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.password, Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.passwordType, Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.port, Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.queryChannelIdMap, and Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.ssl.
Member Function Documentation
Client_OnChannelMessage()
void Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.Client_OnChannelMessage (object sender, IrcEventArgs e) private
When a channel message is received in IRC.
Parameters
sender The sender of the event.
e The IrcEventArgs.
Client_OnQueryMessage()
void Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.Client_OnQueryMessage (object sender, IrcEventArgs e) private
When a query message is received in IRC.
Parameters
sender The sender of the event.
e The IrcEventArgs.
Connect()
override async ValueTask Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.Connect (CancellationToken cancellationToken) protected
Definition at line 367 of file IrcProvider.cs.
        {
            cancellationToken.ThrowIfCancellationRequested();
            try
            {
                await Task.Factory.StartNew(
                    () =>
                    {
                        client = InstantiateClient();
                        client.Connect(address, port);
                    },
                    cancellationToken,
                    DefaultIOManager.BlockingTaskCreationOptions,
                    TaskScheduler.Current)
                    .WaitAsync(cancellationToken);
                cancellationToken.ThrowIfCancellationRequested();
                listenTask = Task.Factory.StartNew(
                    () =>
                    {
                        Logger.LogTrace("Starting blocking listen...");
                        try
{
                            client.Listen();
                        }
                        catch (Exception ex)
{
                            Logger.LogWarning(ex, "IRC Main Listen Exception!");
                        }
                        Logger.LogTrace("Exiting listening task...");
                    },
                    cancellationToken,
                    DefaultIOManager.BlockingTaskCreationOptions,
                    TaskScheduler.Current);
                Logger.LogTrace("Authenticating ({passwordType})...", passwordType);
                switch (passwordType)
                {
                    case IrcPasswordType.Server:
                        client.RfcPass(password);
                        await Login(client, nickname, cancellationToken);
                        break;
                    case IrcPasswordType.NickServ:
                        await Login(client, nickname, cancellationToken);
                        cancellationToken.ThrowIfCancellationRequested();
                        client.SendMessage(SendType.Message, "NickServ", String.Format(CultureInfo.InvariantCulture, "IDENTIFY {0}", password));
                        break;
                    case IrcPasswordType.Sasl:
                        await SaslAuthenticate(cancellationToken);
                        break;
                    case IrcPasswordType.Oper:
                        await Login(client, nickname, cancellationToken);
                        cancellationToken.ThrowIfCancellationRequested();
                        client.RfcOper(nickname, password, Priority.Critical);
                        break;
                    case null:
                        await Login(client, nickname, cancellationToken);
                        break;
                    default:
                        throw new InvalidOperationException($"Invalid IrcPasswordType: {passwordType.Value}");
                }
                cancellationToken.ThrowIfCancellationRequested();
                Logger.LogTrace("Connection established!");
            }
            catch (Exception e) when (e is not OperationCanceledException)
            {
                throw new JobException(ErrorCode.ChatCannotConnectProvider, e);
            }
        }
References Tgstation.Server.Host.IO.DefaultIOManager.BlockingTaskCreationOptions.
DisconnectImpl()
override async ValueTask Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.DisconnectImpl (CancellationToken cancellationToken) protected
Definition at line 442 of file IrcProvider.cs.
        {
            try
            {
                await Task.Factory.StartNew(
                    () =>
                    {
                        try
{
                            client.RfcQuit("Mr. Stark, I don't feel so good...", Priority.Critical); // priocritical otherwise it wont go through
                        }
                        catch (Exception e)
{
                            Logger.LogWarning(e, "Error quitting IRC!");
                        }
                    },
                    cancellationToken,
                    DefaultIOManager.BlockingTaskCreationOptions,
                    TaskScheduler.Current);
                await HardDisconnect(cancellationToken);
            }
            catch (OperationCanceledException)
            {
                throw;
            }
            catch (Exception e)
            {
                Logger.LogWarning(e, "Error disconnecting from IRC!");
            }
        }
References Tgstation.Server.Host.IO.DefaultIOManager.BlockingTaskCreationOptions.
DisposeAsync()
override async ValueTask Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.DisposeAsync () virtual
Reimplemented from Tgstation.Server.Host.Components.Chat.Providers.Provider.
Definition at line 155 of file IrcProvider.cs.
        {
            await base.DisposeAsync();
            // DCT: None available
            await HardDisconnect(CancellationToken.None);
        }
References Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.HardDisconnect().
HandleMessage()
void Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.HandleMessage (IrcEventArgs e, bool isPrivate) private
Handle an IRC message.
Parameters
e The IrcEventArgs.
isPrivate If this is a query message.
Definition at line 516 of file IrcProvider.cs.
        {
            if (e.Data.Nick.Equals(client.Nickname, StringComparison.OrdinalIgnoreCase))
                return;
            var username = e.Data.Nick;
            var channelName = isPrivate ? username : e.Data.Channel;
            ulong MapAndGetChannelId(Dictionary<ulong, string?> dicToCheck)
            {
                ulong? resultId = null;
                if (!dicToCheck.Any(x =>
                {
                    if (x.Value != channelName)
                        return false;
                    resultId = x.Key;
                    return true;
                }))
                {
                    resultId = channelIdCounter++;
                    dicToCheck.Add(resultId.Value, channelName);
                    if (dicToCheck == queryChannelIdMap)
                        channelIdMap.Add(resultId.Value, null);
                }
                return resultId!.Value;
            }
            ulong userId, channelId;
            lock (client)
            {
                userId = MapAndGetChannelId(new Dictionary<ulong, string?>(queryChannelIdMap
                    .Cast<KeyValuePair<ulong, string?>>())); // NRT my beloathed
                channelId = isPrivate ? userId : MapAndGetChannelId(channelIdMap);
            }
            var channelFriendlyName = isPrivate ? String.Format(CultureInfo.InvariantCulture, "PM: {0}", channelName) : channelName;
            var message = new Message(
                new ChatUser(
                    new ChannelRepresentation(address, channelFriendlyName, channelId)
                    {
                        IsPrivateChannel = isPrivate,
                        EmbedsSupported = false,
                        // isAdmin and Tag populated by manager
                    },
                    username,
                    username,
                    userId),
                e.Data.Message);
            EnqueueMessage(message);
        }
HardDisconnect()
async ValueTask Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.HardDisconnect (CancellationToken cancellationToken) private
Attempt to disconnect from IRC immediately.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Definition at line 681 of file IrcProvider.cs.
        {
            if (!Connected)
            {
                Logger.LogTrace("Not hard disconnecting, already offline");
                return;
            }
            Logger.LogTrace("Hard disconnect");
            // This call blocks permanently randomly sometimes
            // Frankly I don't give a shit
            var disconnectTask = Task.Factory.StartNew(
                () =>
                {
                    try
                    {
                        client.Disconnect();
                    }
                    catch (Exception e)
                    {
                        Logger.LogWarning(e, "Error disconnecting IRC!");
                    }
                },
                cancellationToken,
                DefaultIOManager.BlockingTaskCreationOptions,
                TaskScheduler.Current);
            await Task.WhenAny(
                Task.WhenAll(
                    disconnectTask,
                    listenTask ?? Task.CompletedTask),
                AsyncDelayer.Delay(TimeSpan.FromSeconds(5), cancellationToken).AsTask());
        }
References Tgstation.Server.Host.IO.DefaultIOManager.BlockingTaskCreationOptions, and Tgstation.Server.Host.Utils.AsyncDelayer.Delay().
Referenced by Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.DisposeAsync().
InstantiateClient()
IrcFeatures Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.InstantiateClient () private
Creates a new instance of the IRC client. Reusing the same client after a disconnection seems to cause issues.
Returns
The IrcFeatures client to use.
Definition at line 721 of file IrcProvider.cs.
        {
            var newClient = new IrcFeatures
            {
                SupportNonRfc = true,
                CtcpUserInfo = "You are going to play. And I am going to watch. And everything will be just fine...",
                AutoRejoin = true,
                AutoRejoinOnKick = true,
                AutoRelogin = false,
                AutoRetry = false,
                AutoReconnect = false,
                ActiveChannelSyncing = true,
                AutoNickHandling = true,
                CtcpVersion = assemblyInfo.VersionString,
                UseSsl = ssl,
                EnableUTF8Recode = true,
            };
            if (ssl)
                newClient.ValidateServerCertificate = true; // dunno if it defaults to that or what
            newClient.OnChannelMessage += Client_OnChannelMessage;
            newClient.OnQueryMessage += Client_OnQueryMessage;
            if (loggingConfiguration.ProviderNetworkDebug)
            {
                newClient.OnReadLine += (sender, e) => Logger.LogTrace("READ: {line}", e.Line);
                newClient.OnWriteLine += (sender, e) => Logger.LogTrace("WRITE: {line}", e.Line);
            }
            newClient.OnError += (sender, e) =>
            {
                Logger.LogError("IRC ERROR: {error}", e.ErrorMessage);
                newClient.Disconnect();
            };
            return newClient;
        }
Referenced by Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.IrcProvider().
Login()
async ValueTask Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.Login (IrcFeatures client, string nickname, CancellationToken cancellationToken) private
Register the client on the network.
Parameters
client IRC client.
nickname Nickname.
cancellationToken Cancellation token.
Returns
Task that resolves when registration has been completed.
Exceptions
TimeoutException If the IRC server fails to respond.
Definition at line 481 of file IrcProvider.cs.
        {
            var promise = new TaskCompletionSource<object>();
            void Callback(object? sender, EventArgs e)
            {
                Logger.LogTrace("IRC Registered.");
                promise.TrySetResult(e);
            }
            client.OnRegistered += Callback;
            client.Login(nickname, nickname, 0, nickname);
            using var cts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
            cts.CancelAfter(TimeSpan.FromSeconds(30));
            try
            {
                await promise.Task.WaitAsync(cts.Token);
                client.OnRegistered -= Callback;
            }
            catch (OperationCanceledException)
            {
                if (client.IsConnected)
                    client.Disconnect();
                throw new JobException("Timed out waiting for IRC Registration");
            }
        }
MapChannelsImpl()
override async ValueTask< Dictionary< Models.ChatChannel, IEnumerable< ChannelRepresentation > > > Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.MapChannelsImpl (IEnumerable< Models.ChatChannel > channels, CancellationToken cancellationToken) protected
References Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.channelIdMap, and Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.client.
NonBlockingListen()
Task Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.NonBlockingListen (CancellationToken cancellationToken) private
Perform a non-blocking IrcConnection.Listen(bool).
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
SaslAuthenticate()
async ValueTask Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.SaslAuthenticate (CancellationToken cancellationToken) private
Run SASL authentication on client.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Definition at line 611 of file IrcProvider.cs.
        {
            client.WriteLine("CAP REQ :sasl", Priority.Critical); // needs to be put in the buffer before anything else
            cancellationToken.ThrowIfCancellationRequested();
            Logger.LogTrace("Logging in...");
            client.Login(nickname, nickname, 0, nickname);
            cancellationToken.ThrowIfCancellationRequested();
            // wait for the SASL ack or timeout
            var receivedAck = false;
            var receivedPlus = false;
            void AuthenticationDelegate(object sender, ReadLineEventArgs e)
            {
                if (e.Line.Contains("ACK :sasl", StringComparison.Ordinal))
                    receivedAck = true;
                else if (e.Line.Contains("AUTHENTICATE +", StringComparison.Ordinal))
                    receivedPlus = true;
            }
            Logger.LogTrace("Performing handshake...");
            client.OnReadLine += AuthenticationDelegate;
            try
            {
                using var timeoutCts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
                timeoutCts.CancelAfter(TimeSpan.FromSeconds(25));
                var timeoutToken = timeoutCts.Token;
                var listenTimeSpan = TimeSpan.FromMilliseconds(10);
                for (; !receivedAck;
                    await AsyncDelayer.Delay(listenTimeSpan, timeoutToken))
                    await NonBlockingListen(cancellationToken);
                client.WriteLine("AUTHENTICATE PLAIN", Priority.Critical);
                timeoutToken.ThrowIfCancellationRequested();
                for (; !receivedPlus;
                    await AsyncDelayer.Delay(listenTimeSpan, timeoutToken))
                    await NonBlockingListen(cancellationToken);
            }
            finally
            {
                client.OnReadLine -= AuthenticationDelegate;
            }
            cancellationToken.ThrowIfCancellationRequested();
            // Stolen! https://github.com/znc/znc/blob/1e697580155d5a38f8b5a377f3b1d94aaa979539/modules/sasl.cpp#L196
            Logger.LogTrace("Sending credentials...");
            var authString = String.Format(
                CultureInfo.InvariantCulture,
                "{0}{1}{0}{1}{2}",
                nickname,
                '\0',
                password);
            var b64 = Convert.ToBase64String(Encoding.UTF8.GetBytes(authString));
            var authLine = $"AUTHENTICATE {b64}";
            client.WriteLine(authLine, Priority.Critical);
            cancellationToken.ThrowIfCancellationRequested();
            Logger.LogTrace("Finishing authentication...");
            client.WriteLine("CAP END", Priority.Critical);
        }
References Tgstation.Server.Host.Utils.AsyncDelayer.Delay().
SendMessage()
override async ValueTask Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.SendMessage (Message? replyTo, MessageContent message, ulong channelId, CancellationToken cancellationToken)
Send a message to the IProvider.
Parameters
replyTo The optional Message to reply to.
message The MessageContent.
channelId The ChannelRepresentation.RealId to send to.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Chat.Providers.IProvider.
Definition at line 164 of file IrcProvider.cs.
        {
            ArgumentNullException.ThrowIfNull(message);
            await Task.Factory.StartNew(
                () =>
                {
                    // IRC doesn't allow newlines
                    // Explicitly ignore embeds
                    var messageText = message.Text;
                    messageText ??= $"Embed Only: {JsonConvert.SerializeObject(message.Embed)}";
                    messageText = String.Concat(
                        messageText
                            .Where(x => x != '\r')
                            .Select(x => x == '\n' ? '|' : x));
                    var channelName = channelIdMap[channelId];
                    SendType sendType;
                    if (channelName == null)
                    {
                        channelName = queryChannelIdMap[channelId];
                        sendType = SendType.Notice;
                    }
                    else
                        sendType = SendType.Message;
                    var messageSize = Encoding.UTF8.GetByteCount(messageText) + Encoding.UTF8.GetByteCount(channelName) + PreambleMessageLength;
                    var messageTooLong = messageSize > MessageBytesLimit;
                    if (messageTooLong)
                        messageText = $"TGS: Could not send message to IRC. Line write exceeded protocol limit of {MessageBytesLimit}B.";
                    try
                    {
                        client.SendMessage(sendType, channelName, messageText);
                    }
                    catch (Exception e)
                    {
                        Logger.LogWarning(e, "Unable to send to channel {channelName}!", channelName);
                        return;
                    }
                    if (messageTooLong)
                        Logger.LogWarning(
                            "Failed to send to channel {channelId}: Message size ({messageSize}B) exceeds IRC limit of 512B",
                            channelId,
                            messageSize);
                },
                cancellationToken,
                DefaultIOManager.BlockingTaskCreationOptions,
                TaskScheduler.Current);
        }
References Tgstation.Server.Host.IO.DefaultIOManager.BlockingTaskCreationOptions, Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.channelIdMap, Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.client, Tgstation.Server.Host.Components.Chat.Providers.Provider.Logger, Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.MessageBytesLimit, Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.PreambleMessageLength, Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.queryChannelIdMap, and Tgstation.Server.Host.Components.Interop.MessageContent.Text.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.SendUpdateMessage().
SendUpdateMessage()
override async ValueTask< Func< string?, string, ValueTask< Func< bool, ValueTask > > > > Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.SendUpdateMessage (Models::RevisionInformation revisionInformation, EngineVersion engineVersion, DateTimeOffset? estimatedCompletionTime, string? gitHubOwner, string? gitHubRepo, ulong channelId, bool localCommitPushed, CancellationToken cancellationToken)
Send the message for a deployment.
Parameters
revisionInformation The RevisionInformation of the deployment.
engineVersion The Api.Models.EngineVersion of the deployment.
estimatedCompletionTime The optional DateTimeOffset the deployment is expected to be completed at.
gitHubOwner The repository GitHub owner, if any.
gitHubRepo The repository GitHub name, if any.
channelId The ChannelRepresentation.RealId to send to.
localCommitPushed true if the local deployment commit was pushed to the remote repository.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a Func<T1, T2, TResult> to call to update the message at the deployment's conclusion. Parameters: Error message if any, DreamMaker output if any. Returns another callback which should be called to mark the deployment as active.
Implements Tgstation.Server.Host.Components.Chat.Providers.IProvider.
Definition at line 218 of file IrcProvider.cs.
        {
            ArgumentNullException.ThrowIfNull(revisionInformation);
            ArgumentNullException.ThrowIfNull(engineVersion);
            ArgumentNullException.ThrowIfNull(gitHubOwner);
            ArgumentNullException.ThrowIfNull(gitHubRepo);
            var commitInsert = revisionInformation.CommitSha![..7];
            string remoteCommitInsert;
            if (revisionInformation.CommitSha == revisionInformation.OriginCommitSha)
            {
                commitInsert = String.Format(CultureInfo.InvariantCulture, localCommitPushed ? "^{0}" : "{0}", commitInsert);
                remoteCommitInsert = String.Empty;
            }
            else
                remoteCommitInsert = String.Format(CultureInfo.InvariantCulture, ". Remote commit: ^{0}", revisionInformation.OriginCommitSha![..7]);
            var testmergeInsert = (revisionInformation.ActiveTestMerges?.Count ?? 0) == 0
                ? String.Empty
                : String.Format(
                    CultureInfo.InvariantCulture,
                    " (Test Merges: {0})",
                    String.Join(
                        ", ",
                        revisionInformation
                            .ActiveTestMerges!
                            .Select(x => x.TestMerge)
                            .Select(x =>
{
                                var result = String.Format(CultureInfo.InvariantCulture, "#{0} at {1}", x.Number, x.TargetCommitSha![..7]);
                                if (x.Comment != null)
                                    result += String.Format(CultureInfo.InvariantCulture, " ({0})", x.Comment);
                                return result;
                            })));
            var prefix = GetEngineCompilerPrefix(engineVersion.Engine!.Value);
            await SendMessage(
                null,
                new MessageContent
                {
                    Text = String.Format(
                        CultureInfo.InvariantCulture,
                        $"{prefix}: Deploying revision: {0}{1}{2} BYOND Version: {3}{4}",
                        commitInsert,
                        testmergeInsert,
                        remoteCommitInsert,
                        engineVersion.ToString(),
                        estimatedCompletionTime.HasValue
                            ? $" ETA: {estimatedCompletionTime - DateTimeOffset.UtcNow}"
                            : String.Empty),
                },
                channelId,
                cancellationToken);
            return async (errorMessage, dreamMakerOutput) =>
            {
                await SendMessage(
                    null,
                    new MessageContent
                    {
                        Text = $"{prefix}: Deployment {(errorMessage == null ? "complete" : "failed")}!",
                    },
                    channelId,
                    cancellationToken);
                return active => ValueTask.CompletedTask;
            };
        }
References Tgstation.Server.Api.Models.EngineVersion.Engine, Tgstation.Server.Host.Components.Chat.Providers.Provider.GetEngineCompilerPrefix(), Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.SendMessage(), and Tgstation.Server.Api.Models.EngineVersion.ToString().
Member Data Documentation
address
readonly string Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.address private
Address of the server to connect to.
Definition at line 49 of file IrcProvider.cs.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.IrcProvider().
assemblyInfo
readonly IAssemblyInformationProvider Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.assemblyInfo private
The IAssemblyInformationProvider obtained from constructor, used for the CTCP version string.
Definition at line 89 of file IrcProvider.cs.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.IrcProvider().
channelIdCounter
ulong Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.channelIdCounter private
Id counter for channelIdMap.
Definition at line 109 of file IrcProvider.cs.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.IrcProvider().
channelIdMap
readonly Dictionary<ulong, string?> Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.channelIdMap private
Map of ChannelRepresentation.RealIds to channel names.
Definition at line 79 of file IrcProvider.cs.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.IrcProvider(), Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.MapChannelsImpl(), and Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.SendMessage().
client
IrcFeatures Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.client private
The IrcFeatures client.
Definition at line 99 of file IrcProvider.cs.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.IrcProvider(), Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.MapChannelsImpl(), and Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.SendMessage().
listenTask
Task? Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.listenTask private
The ValueTask used for IrcConnection.Listen(bool).
Definition at line 104 of file IrcProvider.cs.
loggingConfiguration
readonly FileLoggingConfiguration Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.loggingConfiguration private
The FileLoggingConfiguration for the IrcProvider.
Definition at line 94 of file IrcProvider.cs.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.IrcProvider().
MessageBytesLimit
const int Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.MessageBytesLimit = 512 static private
Hard limit to sendable message size in bytes.
Definition at line 38 of file IrcProvider.cs.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.SendMessage().
nickname
readonly string Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.nickname private
IRC nickname.
Definition at line 64 of file IrcProvider.cs.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.IrcProvider().
password
readonly string Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.password private
Password which will used for authentication.
Definition at line 69 of file IrcProvider.cs.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.IrcProvider().
passwordType
readonly? IrcPasswordType Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.passwordType private
The IrcPasswordType of password.
Definition at line 74 of file IrcProvider.cs.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.IrcProvider().
port
readonly ushort Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.port private
Port of the server to connect to.
Definition at line 54 of file IrcProvider.cs.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.IrcProvider().
PreambleMessageLength
const int Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.PreambleMessageLength = 12 static private
Length of the preamble when writing a message to the server. Must be summed with the channel name to get the true value.
Definition at line 33 of file IrcProvider.cs.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.SendMessage().
queryChannelIdMap
readonly Dictionary<ulong, string> Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.queryChannelIdMap private
Map of ChannelRepresentation.RealIds to query users.
Definition at line 84 of file IrcProvider.cs.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.IrcProvider(), and Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.SendMessage().
ssl
readonly bool Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.ssl private
Wether or not this IRC client is to use ssl.
Definition at line 59 of file IrcProvider.cs.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.IrcProvider().
Property Documentation
BotMention
override string Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.BotMention get
The string that indicates the IProvider was mentioned.
Implements Tgstation.Server.Host.Components.Chat.Providers.IProvider.
Definition at line 44 of file IrcProvider.cs.
Connected
override bool Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.Connected get
If the IProvider is currently connected.
Implements Tgstation.Server.Host.Components.Chat.Providers.IProvider.
Definition at line 41 of file IrcProvider.cs.
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Chat/Providers/IrcProvider.cs