tgstation-server: TGServerService.Service Class Reference
TGServerService.Service Class Reference
The windows service the application runs as
Public Member Functions
Service ()
Sets up ServiceName and ActiveService
void VerifyConnection ()
Does nothing on the server end, but if the call completes, you can be sure you are connected. WCF won't throw until you try until you actually use the API
void PrepareForUpdate ()
Next stop of the service will not close DD and sets a flag for it to reattach once it restarts
ushort RemoteAccessPort ()
Get the port used for remote operation
string SetRemoteAccessPort (ushort port)
Set the port used for remote operation Requires a service restart to take effect
string Version ()
Retrieve's the service's version
bool SetPythonPath (string path)
Sets the path to the python 2.7 installation
string PythonPath ()
Gets the path to the python 2.7 installation
IList< InstanceMetadata > ListInstances ()
List instances
string CreateInstance (string Name, string path)
Creates a new server instance
string ImportInstance (string path)
Registers an existing server instance
bool InstanceEnabled (string Name)
Checks if an instance is online
string SetInstanceEnabled (string Name, bool enabled)
Sets an instance's enabled status
string RenameInstance (string name, string new_name)
Renames an instance, this will restart the instance if it is enabled
string DetachInstance (string name)
Disables and unregisters an instance, allowing the folder and data to be manipulated manually
Static Public Member Functions
static void CancelImpersonation ()
Cancels WCF's user impersonation to allow clean access to writing log files
static void WriteEntry (string message, EventID id, EventLogEntryType eventType, byte loggingID)
Writes an event to Windows the event log
Public Attributes
const byte LoggingID = 0
The logging ID used for Service events
Static Public Attributes
static readonly string VersionString = "/tg/station 13 Server Service v" + FileVersionInfo.GetVersionInfo(System.Reflection.Assembly.GetExecutingAssembly().Location).FileVersion
The service version string based on the FileVersionInfo
Protected Member Functions
override void Dispose (bool disposing)
Clears ActiveService
override void OnStart (string[] args)
Called by the Windows service manager. Initializes and starts configured ServerInstances
override void OnStop ()
Shuts down all active ServiceHosts and calls IDisposable.Dispose on it's ServerInstance
Private Member Functions
void MigrateSettings (int oldVersion)
Migrates the .NET config from oldVersion to oldVersion + 1
IEnumerable< InstanceConfig > GetInstanceConfigs ()
Enumerates configured InstanceConfigs. Detaches those that fail to load
void ChangePortFromCommandLine (string[] args)
Overrides and saves the configured Properties.Settings.RemoteAccessPort if requested by command line parameters
void PrePrepConfig ()
Writes some changes to the Properties.Settings that always need to be done.
void SetupConfig ()
Upgrades up the service configuration
void SetupService ()
Creates the ServiceHost for ITGSService
void OnlineAllHosts ()
Opens all created ServiceHosts
void SetupInstances ()
Creates ServiceHosts for all ServerInstances as listed in Properties.Settings.InstancePaths, detaches bad ones
void UnlockLoggingID (byte ID)
Unlocks a ServerInstance.LoggingID acquired with LockLoggingID
byte LockLoggingID ()
Gets and locks a ServerInstance.LoggingID
ServiceHost SetupInstance (InstanceConfig config)
Creates and starts a ServiceHost for a ServerInstance at config
void AddEndpoint (ServiceHost host, Type typetype)
Adds a WCF endpoint for a component typetype
string SetupOneInstance (InstanceConfig config)
Starts and onlines an instance located at config
string SetInstanceEnabledImpl (string Name, bool enabled, out string path)
Sets a ServerInstance's enabled status
Static Private Member Functions
static string CheckInstanceName (string instanceName)
Checks an instanceName for illegal characters
static ServiceHost CreateHost (object singleton, string endpointPostfix)
Creates a ServiceHost for singleton using the default pipe, CloseTimeout for the ServiceHost, and the configured Properties.Settings.RemoteAccessPort
Private Attributes
ServiceHost serviceHost
The WCF host that contains ITGSService connects to
IDictionary< string, ServiceHost > hosts
Map of InstanceConfig.Name to the respective ServiceHost hosting the ServerInstance
IList< int > UsedLoggingIDs = new List<int>()
List of ServerInstance.LoggingIDs in use
Static Private Attributes
static Service ActiveService
Singleton instance
Detailed Description
The windows service the application runs as
Definition at line 18 of file Service.cs.
Constructor & Destructor Documentation
TGServerService.Service.Service ()
Sets up ServiceName and ActiveService
Definition at line 72 of file Service.cs.
         {
             ServiceName = "TG Station Server";
             if (ActiveService != null)
                 throw new Exception("There is already a Service instance running!");
             ActiveService = this;
         }
Member Function Documentation
void TGServerService.Service.AddEndpoint (ServiceHost host, Type typetype) private
Adds a WCF endpoint for a component typetype
Parameters
host The service host to add the component to
typetype The type of the component
Definition at line 365 of file Service.cs.
References TGServiceInterface.Interface.TransferLimitLocal, and TGServiceInterface.Interface.TransferLimitRemote.
Referenced by TGServerService.Service.SetupInstance(), and TGServerService.Service.SetupService().
         {
             var bindingName = typetype.Name;
             host.AddServiceEndpoint(typetype, new NetNamedPipeBinding() { SendTimeout = new TimeSpan(0, 0, 30), MaxReceivedMessageSize = Interface.TransferLimitLocal }, bindingName);
             var httpsBinding = new WSHttpBinding()
             {
                 SendTimeout = new TimeSpan(0, 0, 40),
                 MaxReceivedMessageSize = Interface.TransferLimitRemote
             };
             var requireAuth = typetype.Name != typeof(ITGConnectivity).Name;
             httpsBinding.Security.Transport.ClientCredentialType = HttpClientCredentialType.None;
             httpsBinding.Security.Mode = requireAuth ? SecurityMode.TransportWithMessageCredential : SecurityMode.Transport;    //do not require auth for a connectivity check
             httpsBinding.Security.Message.ClientCredentialType = requireAuth ? MessageCredentialType.UserName : MessageCredentialType.None;
             host.AddServiceEndpoint(typetype, httpsBinding, bindingName);
         }
static void TGServerService.Service.CancelImpersonation () static
Cancels WCF's user impersonation to allow clean access to writing log files
Definition at line 38 of file Service.cs.
Referenced by TGServerService.ServerInstance.DeleteFile(), TGServerService.ServerInstance.ReadText(), and TGServerService.ServerInstance.WriteText().
         {
             WindowsIdentity.Impersonate(IntPtr.Zero);
         }
void TGServerService.Service.ChangePortFromCommandLine (string[] args) private
Overrides and saves the configured Properties.Settings.RemoteAccessPort if requested by command line parameters
Parameters
args The command line parameters for the Service
Definition at line 154 of file Service.cs.
Referenced by TGServerService.Service.OnStart().
         {
             var Config = Properties.Settings.Default;
             for (var I = 0; I < args.Length - 1; ++I)
                 if (args[I].ToLower() == "-port")
                 {
                     try
                     {
                         var res = Convert.ToUInt16(args[I + 1]);
                         if (res == 0)
                             throw new Exception("Cannot bind to port 0");
                         Config.RemoteAccessPort = res;
                     }
                     catch (Exception e)
                     {
                         throw new Exception("Invalid argument for \"-port\"", e);
                     }
                     Config.Save();
                     break;
                 }
         }
static string TGServerService.Service.CheckInstanceName (string instanceName) static private
Checks an instanceName for illegal characters
Parameters
instanceName The ServerInstance name to check
Returns
if instanceName contains no illegal characters, error message otherwise
Definition at line 60 of file Service.cs.
Referenced by TGServerService.Service.CreateInstance(), and TGServerService.Service.RenameInstance().
         {
             char[] bannedCharacters = { ';', '&', '=', '%' };
             foreach (var I in bannedCharacters)
                 if (instanceName.Contains(I.ToString()))
                     return "Instance names may not contain the following characters: ';', '&', '=', or '%'";
             return null;
         }
static ServiceHost TGServerService.Service.CreateHost (object singleton, string endpointPostfix) static private
Creates a ServiceHost for singleton using the default pipe, CloseTimeout for the ServiceHost, and the configured Properties.Settings.RemoteAccessPort
Parameters
singleton The ServiceHost.SingletonInstance
endpointPostfix The URL to access components on the ServiceHost
Returns
The created ServiceHost
Definition at line 257 of file Service.cs.
Referenced by TGServerService.Service.SetupInstance(), and TGServerService.Service.SetupService().
         {
             return new ServiceHost(singleton, new Uri[] { new Uri(String.Format("net.pipe://localhost/{0}", endpointPostfix)), new Uri(String.Format("https://localhost:{0}/{1}", Properties.Settings.Default.RemoteAccessPort, endpointPostfix)) })
             {
                 CloseTimeout = new TimeSpan(0, 0, 5)
             };
         }
string TGServerService.Service.CreateInstance (string Name, string path)
Creates a new server instance
Implements TGServiceInterface.Components.ITGSService.
Definition at line 472 of file Service.cs.
References TGServerService.Service.CheckInstanceName(), TGServerService.Service.GetInstanceConfigs(), TGServerService.InstanceConfig.Save(), and TGServerService.Service.SetupOneInstance().
         {
             var res = CheckInstanceName(Name);
             if (res != null)
                 return res;
             if (File.Exists(path) || Directory.Exists(path))
                 return "Cannot create instance at pre-existing path!";
             var Config = Properties.Settings.Default;
             lock (this)
             {
                 if (Config.InstancePaths.Contains(path))
                     return String.Format("Instance at {0} already exists!", path);
                 foreach (var oic in GetInstanceConfigs())
                     if (Name == oic.Name)
                         return String.Format("Instance named {0} already exists!", oic.Name);
                 InstanceConfig ic;
                 try
                 {
                     ic = new InstanceConfig(path)
                     {
                         Name = Name
                     };
                     Directory.CreateDirectory(path);
                     ic.Save();
                     Properties.Settings.Default.InstancePaths.Add(path);
                 }
                 catch (Exception e)
                 {
                     return e.ToString();
                 }
                 return SetupOneInstance(ic);
             }
         }
string TGServerService.Service.DetachInstance (string name)
Disables and unregisters an instance, allowing the folder and data to be manipulated manually
Implements TGServiceInterface.Components.ITGSService.
Definition at line 677 of file Service.cs.
References TGServerService.Service.GetInstanceConfigs(), and TGServerService.Service.SetInstanceEnabledImpl().
         {
             lock (this)
             {
                 var res = SetInstanceEnabledImpl(name, false, out string path);
                 if (res != null)
                     return res;
                 if (path == null)    //gotta find it ourselves
                     foreach (var ic in GetInstanceConfigs())
                         if (ic.Name == name)
{
                             path = ic.Directory;
                             break;
                         }
                 if (path == null)
                     return String.Format("No instance named {0} exists!", name);
                 Properties.Settings.Default.InstancePaths.Remove(path);
                 return null;
             }
         }
override void TGServerService.Service.Dispose (bool disposing) protected
Clears ActiveService
Parameters
disposing if this method was invoked from IDisposable.Dispose, otherwise it was invoked by the finalizer
Definition at line 84 of file Service.cs.
References TGServerService.Service.Dispose().
Referenced by TGServerService.Service.Dispose(), and TGServerService.Tests.TestService.TestInstantiation().
         {
             ActiveService = null;
             base.Dispose(disposing);
         }
IEnumerable<InstanceConfig> TGServerService.Service.GetInstanceConfigs () private
Enumerates configured InstanceConfigs. Detaches those that fail to load
Returns
Each configured InstanceConfig
Definition at line 124 of file Service.cs.
References TGServerService.InstanceConfig.Load(), and TGServerService.Service.WriteEntry().
Referenced by TGServerService.Service.CreateInstance(), TGServerService.Service.DetachInstance(), TGServerService.Service.ImportInstance(), TGServerService.Service.ListInstances(), TGServerService.Service.RenameInstance(), TGServerService.Service.SetInstanceEnabledImpl(), and TGServerService.Service.SetupInstances().
         {
             var pathsToRemove = new List<string>();
             lock (this)
             {
                 var IPS = Properties.Settings.Default.InstancePaths;
                 foreach (var I in IPS)
                 {
                     InstanceConfig ic;
                     try
                     {
                         ic = InstanceConfig.Load(I);
                     }
                     catch (Exception e)
                     {
                         WriteEntry(String.Format("Unable load instance config at path {0}. Error: {1} Detaching...", I, e.ToString()), EventID.InstanceInitializationFailure, EventLogEntryType.Error, LoggingID);
                         pathsToRemove.Add(I);
                         continue;
                     }
                     yield return ic;
                 }
                 foreach (var I in pathsToRemove)
                     IPS.Remove(I);
             }
         }
string TGServerService.Service.ImportInstance (string path)
Registers an existing server instance
Implements TGServiceInterface.Components.ITGSService.
Definition at line 530 of file Service.cs.
References TGServerService.Service.GetInstanceConfigs(), TGServerService.InstanceConfig.Load(), TGServerService.InstanceConfig.Name, TGServerService.InstanceConfig.Save(), and TGServerService.Service.SetupOneInstance().
         {
             var Config = Properties.Settings.Default;
             lock (this)
             {
                 if (Config.InstancePaths.Contains(path))
                     return String.Format("Instance at {0} already exists!", path);
                 if(!Directory.Exists(path))
                     return String.Format("There is no instance located at {0}!", path);
                 InstanceConfig ic;
                 try
                 {
                     ic = InstanceConfig.Load(path);
                     foreach(var oic in GetInstanceConfigs())
                         if(ic.Name == oic.Name)
                             return String.Format("Instance named {0} already exists!", oic.Name);
                     ic.Save();
                     Properties.Settings.Default.InstancePaths.Add(path);
                 }
                 catch (Exception e)
                 {
                     return e.ToString();
                 }
                 return SetupOneInstance(ic);
             }
         }
bool TGServerService.Service.InstanceEnabled (string Name)
Checks if an instance is online
Implements TGServiceInterface.Components.ITGSService.
Definition at line 558 of file Service.cs.
Referenced by TGServerService.Service.RenameInstance().
         {
             lock(this)
             {
                 return hosts.ContainsKey(Name);
             }
         }
IList<InstanceMetadata> TGServerService.Service.ListInstances ()
List instances
Implements TGServiceInterface.Components.ITGSService.
Definition at line 456 of file Service.cs.
References TGServerService.Service.GetInstanceConfigs(), and TGServiceInterface.InstanceMetadata.Name.
         {
             var result = new List<InstanceMetadata>();
             lock (this)
                 foreach (var ic in GetInstanceConfigs())
                     result.Add(new InstanceMetadata
                     {
                         Name = ic.Name,
                         Path = ic.Directory,
                         Enabled = ic.Enabled,
                         LoggingID = (byte)(ic.Enabled ? ((ServerInstance)hosts[ic.Name].SingletonInstance).LoggingID : 0)
                     });
             return result;
         }
byte TGServerService.Service.LockLoggingID () private
Gets and locks a ServerInstance.LoggingID
Returns
A logging ID for the ServerInstance must be released using UnlockLoggingID(byte)
Definition at line 305 of file Service.cs.
Referenced by TGServerService.Service.SetupInstance().
         {
             lock (UsedLoggingIDs)
             {
                 for (byte I = 1; I < 100; ++I)
                     if (!UsedLoggingIDs.Contains(I))
                     {
                         UsedLoggingIDs.Add(I);
                         return I;
                     }
             }
             throw new Exception("All logging IDs in use!");
         }
void TGServerService.Service.MigrateSettings (int oldVersion) private
Migrates the .NET config from oldVersion to oldVersion + 1
Parameters
oldVersion The version to migrate from
Definition at line 107 of file Service.cs.
References TGServerService.DeprecatedInstanceConfig.CreateFromNETSettings(), and TGServerService.InstanceConfig.Save().
Referenced by TGServerService.Service.SetupConfig().
         {
             var Config = Properties.Settings.Default;
             switch (oldVersion)
             {
                 case 6: //switch to per-instance configs
                     var IC = DeprecatedInstanceConfig.CreateFromNETSettings();
                     IC.Save();
                     Config.InstancePaths.Add(IC.Directory);
                     break;
             }
         }
void TGServerService.Service.OnlineAllHosts () private
Opens all created ServiceHosts
Definition at line 244 of file Service.cs.
Referenced by TGServerService.Service.OnStart().
         {
             serviceHost.Open();
             foreach (var I in hosts)
                 I.Value.Open();
         }
override void TGServerService.Service.OnStart (string[] args) protected
Called by the Windows service manager. Initializes and starts configured ServerInstances
Parameters
args Command line arguments for the Service
Definition at line 181 of file Service.cs.
References TGServerService.Service.ChangePortFromCommandLine(), TGServerService.Service.OnlineAllHosts(), TGServerService.Service.SetupConfig(), TGServerService.Service.SetupInstances(), and TGServerService.Service.SetupService().
         {
             Environment.CurrentDirectory = Directory.CreateDirectory(Path.GetTempPath() + "/TGStationServerService").FullName;  //MOVE THIS POINTER BECAUSE ONE TIME I ALMOST ACCIDENTALLY NUKED MYSELF BY REFACTORING! http://imgur.com/zvGEpJD.png
             SetupConfig();
             ChangePortFromCommandLine(args);
             SetupService();
             SetupInstances();
             OnlineAllHosts();
         }
override void TGServerService.Service.OnStop () protected
Shuts down all active ServiceHosts and calls IDisposable.Dispose on it's ServerInstance
Definition at line 384 of file Service.cs.
References TGServerService.Service.LoggingID, TGServerService.Service.UnlockLoggingID(), and TGServerService.Service.WriteEntry().
         {
             lock (this)
             {
                 try
                 {
                     foreach (var I in hosts)
                     {
                         var host = I.Value;
                         var instance = (ServerInstance)host.SingletonInstance;
                         host.Close();
                         instance.Dispose();
                         UnlockLoggingID(instance.LoggingID);
                     }
                 }
                 catch (Exception e)
                 {
                     WriteEntry(e.ToString(), EventID.ServiceShutdownFail, EventLogEntryType.Error, LoggingID);
                 }
                 serviceHost.Close();
             }
             Properties.Settings.Default.Save();
             ActiveService = null;
         }
void TGServerService.Service.PrepareForUpdate ()
Next stop of the service will not close DD and sets a flag for it to reattach once it restarts
Implements TGServiceInterface.Components.ITGSService.
Definition at line 413 of file Service.cs.
         {
             foreach (var I in hosts)
                 ((ServerInstance)I.Value.SingletonInstance).Reattach(false);
         }
void TGServerService.Service.PrePrepConfig () private
Writes some changes to the Properties.Settings that always need to be done.
Definition at line 199 of file Service.cs.
Referenced by TGServerService.Service.SetupConfig().
         {
             var Config = Properties.Settings.Default;
             if (Config.InstancePaths == null)
                 Config.InstancePaths = new StringCollection();
         }
string TGServerService.Service.PythonPath ()
Gets the path to the python 2.7 installation
Implements TGServiceInterface.Components.ITGSService.
Definition at line 450 of file Service.cs.
         {
             return Properties.Settings.Default.PythonPath;
         }
ushort TGServerService.Service.RemoteAccessPort ()
Get the port used for remote operation
Implements TGServiceInterface.Components.ITGSService.
Definition at line 420 of file Service.cs.
         {
             return Properties.Settings.Default.RemoteAccessPort;
         }
string TGServerService.Service.RenameInstance (string name, string new_name)
Renames an instance, this will restart the instance if it is enabled
Implements TGServiceInterface.Components.ITGSService.
Definition at line 628 of file Service.cs.
References TGServerService.Service.CheckInstanceName(), TGServerService.Service.GetInstanceConfigs(), TGServerService.Service.InstanceEnabled(), and TGServerService.Service.SetInstanceEnabled().
         {
             if (name == new_name)
                 return null;
             var res = CheckInstanceName(new_name);
             if (res != null)
                 return res;
             lock (this)
             {
                 //we have to check em all anyway
                 InstanceConfig the_droid_were_looking_for = null;
                 foreach (var ic in GetInstanceConfigs())
                     if (ic.Name == name)
                     {
                         the_droid_were_looking_for = ic;
                         break;
                     }
                     else if (ic.Name == new_name)
                         return String.Format("There is already another instance named {0}!", new_name);
                 if (the_droid_were_looking_for == null)
                     return String.Format("There is no instance named {0}!", name);
                 var ie = InstanceEnabled(name);
                 if(ie)
                     SetInstanceEnabled(name, false);
                 the_droid_were_looking_for.Name = new_name;
                 string result = "";
                 try
                 {
                     the_droid_were_looking_for.Save();
                     result = null;
                 }
                 catch(Exception e)
                 {
                     result = "Could not save instance config! Error: " + e.ToString();
                 }
                 finally
                 {
                     if (ie)
                     {
                         var resRestore = SetInstanceEnabled(new_name, true);
                         if (resRestore != null)
                             result = (result + " " + resRestore).Trim();
                     }
                 }
                 return result;
             }
         }
string TGServerService.Service.SetInstanceEnabled (string Name, bool enabled)
Sets an instance's enabled status
Implements TGServiceInterface.Components.ITGSService.
Definition at line 567 of file Service.cs.
References TGServerService.Service.SetInstanceEnabledImpl().
Referenced by TGServerService.Service.RenameInstance().
         {
             return SetInstanceEnabledImpl(Name, enabled, out string path);
         }
string TGServerService.Service.SetInstanceEnabledImpl (string Name, bool enabled, out string path) private
Sets a ServerInstance's enabled status
Parameters
Name The ServerInstance whom's status should be changed
enabled to enable the ServerInstance, to disable it
path The path to the modified ServerInstance
Returns
on success, error message on failure
Definition at line 580 of file Service.cs.
References TGServerService.Service.GetInstanceConfigs(), TGServerService.Service.SetupOneInstance(), and TGServerService.Service.UnlockLoggingID().
Referenced by TGServerService.Service.DetachInstance(), and TGServerService.Service.SetInstanceEnabled().
         {
             path = null;
             lock (this)
             {
                 var hostIsOnline = hosts.ContainsKey(Name);
                 if (enabled)
                 {
                     if (hostIsOnline)
                         return null;
                     //now this is a bit awkward because we need to check each instance config for the one named Name
                     string LastCheckedConfig = null;
                     try
                     {
                         foreach (var ic in GetInstanceConfigs())
{
                             if (ic.Name == Name)
{
                                 path = ic.Directory;
                                 ic.Enabled = true;
                                 return SetupOneInstance(ic);
                             }
                         }
                     }
                     catch (Exception e)
                     {
                         return String.Format("An error occurred while checking instance config at {0}! Error: ", LastCheckedConfig, e.ToString());
                     }
                     return String.Format("Instance {0} does not exist!", Name);
                 }
                 else
                 {
                     if (!hostIsOnline)
                         return null;
                     var host = hosts[Name];
                     hosts.Remove(Name);
                     var inst = (ServerInstance)host.SingletonInstance;
                     host.Close();
                     path = inst.ServerDirectory();
                     inst.Offline();
                     inst.Dispose();
                     UnlockLoggingID(inst.LoggingID);
                     return null;
                 }
             }
         }
bool TGServerService.Service.SetPythonPath (string path)
Sets the path to the python 2.7 installation
Implements TGServiceInterface.Components.ITGSService.
Definition at line 441 of file Service.cs.
         {
             if (!Directory.Exists(path))
                 return false;
             Properties.Settings.Default.PythonPath = Path.GetFullPath(path);
             return true;
         }
string TGServerService.Service.SetRemoteAccessPort (ushort port)
Set the port used for remote operation Requires a service restart to take effect
Implements TGServiceInterface.Components.ITGSService.
Definition at line 426 of file Service.cs.
         {
             if (port == 0)
                 return "Cannot bind to port 0";
             Properties.Settings.Default.RemoteAccessPort = port;
             return null;
         }
void TGServerService.Service.SetupConfig () private
Upgrades up the service configuration
Definition at line 210 of file Service.cs.
References TGServerService.Service.MigrateSettings(), and TGServerService.Service.PrePrepConfig().
Referenced by TGServerService.Service.OnStart().
         {
             var Config = Properties.Settings.Default;
             if (Config.UpgradeRequired)
             {
                 var newVersion = Config.SettingsVersion;
                 Config.Upgrade();
                 for (var oldVersion = Config.SettingsVersion; oldVersion < newVersion; ++oldVersion)
                     MigrateSettings(oldVersion);
                 Config.SettingsVersion = newVersion;
                 Config.UpgradeRequired = false;
                 Config.Save();
             }
             PrePrepConfig();
         }
ServiceHost TGServerService.Service.SetupInstance (InstanceConfig config) private
Creates and starts a ServiceHost for a ServerInstance at config
Parameters
config The InstanceConfig for the ServerInstance
Returns
The inactive ServiceHost on success, on failure
Definition at line 324 of file Service.cs.
References TGServerService.Service.AddEndpoint(), TGServerService.Service.CreateHost(), TGServerService.InstanceConfig.Directory, TGServerService.InstanceConfig.Enabled, TGServiceInterface.Interface.InstanceInterfaceName, TGServerService.Service.LockLoggingID(), TGServerService.InstanceConfig.Name, TGServiceInterface.Interface.ValidInterfaces, and TGServerService.Service.WriteEntry().
Referenced by TGServerService.Service.SetupInstances(), and TGServerService.Service.SetupOneInstance().
         {
             ServerInstance instance;
             string instanceName;
             try
             {
                 if (hosts.ContainsKey(config.Directory))
                 {
                     var datInstance = ((ServerInstance)hosts[config.Directory].SingletonInstance);
                     WriteEntry(String.Format("Unable to start instance at path {0}. Has the same name as instance at path {1}. Detaching...", config.Directory, datInstance.ServerDirectory()), EventID.InstanceInitializationFailure, EventLogEntryType.Error, LoggingID);
                     Properties.Settings.Default.InstancePaths.Remove(config.Directory);
                     return null;
                 }
                 if (!config.Enabled)
                     return null;
                 var ID = LockLoggingID();
                 WriteEntry(String.Format("Instance {0} ({1}) assigned logging ID {2}", config.Name, config.Directory, ID), EventID.InstanceIDAssigned, EventLogEntryType.Information, ID);
                 instanceName = config.Name;
                 instance = new ServerInstance(config, ID);
             }
             catch (Exception e)
             {
                 WriteEntry(String.Format("Unable to start instance at path {0}. Detaching... Error: {1}", config.Directory, e.ToString()), EventID.InstanceInitializationFailure, EventLogEntryType.Error, LoggingID);
                 return null;
             }
             var host = CreateHost(instance, String.Format("{0}/{1}", Interface.InstanceInterfaceName, instanceName));
             hosts.Add(instanceName, host);
             foreach (var J in Interface.ValidInterfaces)
                 AddEndpoint(host, J);
             host.Authorization.ServiceAuthorizationManager = instance;
             return host;
         }
void TGServerService.Service.SetupInstances () private
Creates ServiceHosts for all ServerInstances as listed in Properties.Settings.InstancePaths, detaches bad ones
Definition at line 268 of file Service.cs.
References TGServerService.Service.GetInstanceConfigs(), TGServerService.Service.LoggingID, TGServerService.Service.SetupInstance(), and TGServerService.Service.WriteEntry().
Referenced by TGServerService.Service.OnStart().
         {
             hosts = new Dictionary<string, ServiceHost>();
             var pathsToRemove = new List<string>();
             var seenNames = new List<string>();
             foreach (var I in GetInstanceConfigs())
             {
                 if (seenNames.Contains(I.Name))
                 {
                     WriteEntry(String.Format("Instance at {0} has a duplicate name! Detaching...", I.Directory), EventID.InstanceInitializationFailure, EventLogEntryType.Error, LoggingID);
                     pathsToRemove.Add(I.Directory);
                 }
                 if (SetupInstance(I) == null)
                     pathsToRemove.Add(I.Directory);
                 else
                     seenNames.Add(I.Name);
             }
             foreach (var I in pathsToRemove)
                 Properties.Settings.Default.InstancePaths.Remove(I);
         }
string TGServerService.Service.SetupOneInstance (InstanceConfig config) private
Starts and onlines an instance located at config
Parameters
config The InstanceConfig for the ServerInstance
Returns
on success, error message on failure
Definition at line 511 of file Service.cs.
References TGServerService.InstanceConfig.Directory, and TGServerService.Service.SetupInstance().
Referenced by TGServerService.Service.CreateInstance(), TGServerService.Service.ImportInstance(), and TGServerService.Service.SetInstanceEnabledImpl().
         {
             try
             {
                 var host = SetupInstance(config);
                 if (host != null)
                     host.Open();
                 else
                     lock (this)
                         Properties.Settings.Default.InstancePaths.Remove(config.Directory);
                 return null;
             }
             catch (Exception e)
             {
                 return "Instance set up but an error occurred while starting it: " + e.ToString();
             }
         }
void TGServerService.Service.SetupService () private
Creates the ServiceHost for ITGSService
Definition at line 233 of file Service.cs.
References TGServerService.Service.AddEndpoint(), TGServerService.Service.CreateHost(), and TGServiceInterface.Interface.MasterInterfaceName.
Referenced by TGServerService.Service.OnStart().
         {
             serviceHost = CreateHost(this, Interface.MasterInterfaceName);
             AddEndpoint(serviceHost, typeof(ITGSService));
             AddEndpoint(serviceHost, typeof(ITGConnectivity));
             serviceHost.Authorization.ServiceAuthorizationManager = new AdministrativeAuthorizationManager();   //only admins can diddle us
         }
void TGServerService.Service.UnlockLoggingID (byte ID) private
Unlocks a ServerInstance.LoggingID acquired with LockLoggingID
Parameters
ID The ServerInstance.LoggingID to unlock
Definition at line 293 of file Service.cs.
Referenced by TGServerService.Service.OnStop(), and TGServerService.Service.SetInstanceEnabledImpl().
         {
             lock (UsedLoggingIDs)
             {
                 UsedLoggingIDs.Remove(ID);
             }
         }
void TGServerService.Service.VerifyConnection ()
Does nothing on the server end, but if the call completes, you can be sure you are connected. WCF won't throw until you try until you actually use the API
Implements TGServiceInterface.Components.ITGConnectivity.
Definition at line 410 of file Service.cs.
 { }
string TGServerService.Service.Version ()
Retrieve's the service's version
Implements TGServiceInterface.Components.ITGConnectivity.
Definition at line 435 of file Service.cs.
References TGServerService.Service.VersionString.
         {
             return VersionString;
         }
static void TGServerService.Service.WriteEntry (string message, EventID id, EventLogEntryType eventType, byte loggingID) static
Writes an event to Windows the event log
Parameters
message The log message
id The EventID of the message
eventType The EventLogEntryType of the event
loggingID The logging source ID for the event
Definition at line 50 of file Service.cs.
References TGServerService.Service.WriteEntry().
Referenced by TGServerService.AdministrativeAuthorizationManager.CheckAccessCore(), TGServerService.Service.GetInstanceConfigs(), TGServerService.Service.OnStop(), TGServerService.Service.SetupInstance(), TGServerService.Service.SetupInstances(), TGServerService.ServerInstance.WriteAccess(), TGServerService.Service.WriteEntry(), TGServerService.ServerInstance.WriteError(), TGServerService.ServerInstance.WriteInfo(), and TGServerService.ServerInstance.WriteWarning().
         {
             ActiveService.EventLog.WriteEntry(message, eventType, (int)id + loggingID);
         }
Member Data Documentation
Service TGServerService.Service.ActiveService static private
Singleton instance
Definition at line 33 of file Service.cs.
IDictionary<string, ServiceHost> TGServerService.Service.hosts private
Map of InstanceConfig.Name to the respective ServiceHost hosting the ServerInstance
Definition at line 97 of file Service.cs.
const byte TGServerService.Service.LoggingID = 0
The logging ID used for Service events
Definition at line 23 of file Service.cs.
Referenced by TGServerService.AdministrativeAuthorizationManager.CheckAccessCore(), TGServerService.Service.OnStop(), and TGServerService.Service.SetupInstances().
ServiceHost TGServerService.Service.serviceHost private
The WCF host that contains ITGSService connects to
Definition at line 93 of file Service.cs.
IList<int> TGServerService.Service.UsedLoggingIDs = new List<int>() private
List of ServerInstance.LoggingIDs in use
Definition at line 101 of file Service.cs.
readonly string TGServerService.Service.VersionString = "/tg/station 13 Server Service v" + FileVersionInfo.GetVersionInfo(System.Reflection.Assembly.GetExecutingAssembly().Location).FileVersion static
The service version string based on the FileVersionInfo
Definition at line 28 of file Service.cs.
Referenced by TGServerService.ChatProviders.IRCChatProvider.IRCChatProvider(), TGServerService.ServerInstance.Version(), and TGServerService.Service.Version().
The documentation for this class was generated from the following file:
TGServerService/Service.cs