tgstation-server: Tgstation.Server.Shared.VersionConverter Class Reference
Tgstation.Server.Shared.VersionConverter Class Reference sealed
JsonConverter and IYamlTypeConverter for serializing global::System.Versions in semver format.
Public Member Functions
override void WriteJson (JsonWriter? writer, object? value, JsonSerializer serializer)
override? object ReadJson (JsonReader? reader, Type? objectType, object? existingValue, JsonSerializer serializer)
override bool CanConvert (Type objectType)
bool Accepts (Type type)
object ReadYaml (IParser parser, Type type, ObjectDeserializer rootDeserializer)
void WriteYaml (IEmitter? emitter, object? value, Type type, ObjectSerializer serializer)
Static Private Member Functions
static bool CheckSupportsType (Type? type, bool validate)
Check if the VersionConverter supports (de)serializing a given type .
Detailed Description
JsonConverter and IYamlTypeConverter for serializing global::System.Versions in semver format.
Definition at line 16 of file VersionConverter.cs.
Member Function Documentation
Accepts()
bool Tgstation.Server.Shared.VersionConverter.Accepts (Type type)
CanConvert()
override bool Tgstation.Server.Shared.VersionConverter.CanConvert (Type objectType)
CheckSupportsType()
static bool Tgstation.Server.Shared.VersionConverter.CheckSupportsType (Type? type, bool validate) static private
Check if the VersionConverter supports (de)serializing a given type .
Parameters
type The Type to check.
validate If the method should throw if validation fails.
Returns
true if type is a global::System.Version, false otherwise.
Definition at line 24 of file VersionConverter.cs.
        {
            ArgumentNullException.ThrowIfNull(type);
            var supported = type == typeof(global::System.Version);
            if (!supported && validate)
                throw new NotSupportedException($"{nameof(VersionConverter)} does not convert {type}s!");
            return supported;
        }
Referenced by Tgstation.Server.Shared.VersionConverter.ReadJson(), and Tgstation.Server.Shared.VersionConverter.WriteYaml().
ReadJson()
override? object Tgstation.Server.Shared.VersionConverter.ReadJson (JsonReader? reader, Type? objectType, object? existingValue, JsonSerializer serializer)
Definition at line 55 of file VersionConverter.cs.
        {
            ArgumentNullException.ThrowIfNull(reader);
            CheckSupportsType(objectType, true);
            if (reader.TokenType == JsonToken.Null)
                return null;
            if (reader.TokenType == JsonToken.String)
            {
                try
                {
                    var v = global::System.Version.Parse((string)reader.Value!);
                    return v.Semver();
                }
                catch (Exception ex)
                {
                    throw new JsonSerializationException($"Error parsing version string: {reader.Value}", ex);
                }
            }
            throw new JsonSerializationException(
                $"Unexpected token or value when parsing version. Token: {reader.TokenType}, Value: {reader.Value}");
        }
References Tgstation.Server.Shared.VersionConverter.CheckSupportsType().
ReadYaml()
object Tgstation.Server.Shared.VersionConverter.ReadYaml (IParser parser, Type type, ObjectDeserializer rootDeserializer)
WriteJson()
override void Tgstation.Server.Shared.VersionConverter.WriteJson (JsonWriter? writer, object? value, JsonSerializer serializer)
Definition at line 36 of file VersionConverter.cs.
        {
            ArgumentNullException.ThrowIfNull(writer);
            if (value == null)
            {
                writer.WriteNull();
            }
            else if (value is global::System.Version version)
            {
                writer.WriteValue(version.Semver().ToString());
            }
            else
            {
                throw new ArgumentException("Expected Version object!", nameof(value));
            }
        }
WriteYaml()
void Tgstation.Server.Shared.VersionConverter.WriteYaml (IEmitter? emitter, object? value, Type type, ObjectSerializer serializer)
Definition at line 91 of file VersionConverter.cs.
        {
            ArgumentNullException.ThrowIfNull(emitter);
            CheckSupportsType(type, true);
            if (value == null)
                throw new NotSupportedException("Null values not supported!");
            var version = (global::System.Version)value;
            emitter.Emit(
                new Scalar(
                    version
                        .Semver()
                        .ToString()));
        }
References Tgstation.Server.Shared.VersionConverter.CheckSupportsType().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Shared/VersionConverter.cs