tgstation-server: Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider Class Reference
Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider Class Reference
IProvider for the Discord app.
Public Member Functions
DiscordProvider (IJobManager jobManager, IAsyncDelayer asyncDelayer, ILogger< DiscordProvider > logger, IAssemblyInformationProvider assemblyInformationProvider, ChatBot chatBot, GeneralConfiguration generalConfiguration)
Initializes a new instance of the DiscordProvider class.
override async ValueTask DisposeAsync ()
override async ValueTask SendMessage (Message? replyTo, MessageContent message, ulong channelId, CancellationToken cancellationToken)
Send a message to the IProvider.
Parameters
replyTo The optional Message to reply to.
message The MessageContent.
channelId The ChannelRepresentation.RealId to send to.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
override async ValueTask< Func< string?, string, ValueTask< Func< bool, ValueTask > > > > SendUpdateMessage (Models.RevisionInformation revisionInformation, EngineVersion engineVersion, DateTimeOffset? estimatedCompletionTime, string? gitHubOwner, string? gitHubRepo, ulong channelId, bool localCommitPushed, CancellationToken cancellationToken)
async Task< Result > RespondAsync (IMessageCreate messageCreateEvent, CancellationToken cancellationToken)
Task< Result > RespondAsync (IReady readyEvent, CancellationToken cancellationToken)
Public Member Functions inherited from Tgstation.Server.Host.Components.Chat.Providers.Provider
virtual async ValueTask DisposeAsync ()
async ValueTask Disconnect (CancellationToken cancellationToken)
Gracefully disconnects the provider. Permanently stops the reconnection timer.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
void InitialMappingComplete ()
Indicate to the provider that at least one MapChannels(IEnumerable<ChatChannel>, CancellationToken) call has successfully completed.
async ValueTask< Dictionary< ChatChannel, IEnumerable< ChannelRepresentation > > > MapChannels (IEnumerable< ChatChannel > channels, CancellationToken cancellationToken)
Get the ChannelRepresentations for given channels .
Parameters
channels The Api.Models.ChatChannels to map.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a Dictionary<TKey, TValue> of the ChatChannel's ChannelRepresentations representing channels .
async Task< Message?> NextMessage (CancellationToken cancellationToken)
Get a Task<TResult> resulting in the next Message the IProvider receives or null on a disconnect.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the next available Message or null if the IProvider needed to reconnect.
Note that private messages will come in the form of ChannelRepresentations not returned in MapChannels(IEnumerable<ChatChannel>, CancellationToken).
Task SetReconnectInterval (uint reconnectInterval, bool connectNow)
Set the interval at which the provider starts jobs to try to reconnect.
Parameters
reconnectInterval The reconnection interval in minutes.
connectNow If a connection attempt should be made now.
Returns
A Task representing the running operation.
abstract ValueTask SendMessage (Message? replyTo, MessageContent message, ulong channelId, CancellationToken cancellationToken)
Send a message to the IProvider.
Parameters
replyTo The optional Message to reply to.
message The MessageContent.
channelId The ChannelRepresentation.RealId to send to.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
abstract ValueTask< Func< string?, string, ValueTask< Func< bool, ValueTask > > > > SendUpdateMessage (RevisionInformation revisionInformation, Api.Models.EngineVersion engineVersion, DateTimeOffset? estimatedCompletionTime, string? gitHubOwner, string? gitHubRepo, ulong channelId, bool localCommitPushed, CancellationToken cancellationToken)
Public Member Functions inherited from Tgstation.Server.Host.Components.Chat.Providers.IProvider
void InitialMappingComplete ()
Indicate to the provider that at least one MapChannels(IEnumerable<ChatChannel>, CancellationToken) call has successfully completed.
Task< Message?> NextMessage (CancellationToken cancellationToken)
Get a Task<TResult> resulting in the next Message the IProvider receives or null on a disconnect.
ValueTask Disconnect (CancellationToken cancellationToken)
Gracefully disconnects the provider. Permanently stops the reconnection timer.
ValueTask< Dictionary< ChatChannel, IEnumerable< ChannelRepresentation > > > MapChannels (IEnumerable< ChatChannel > channels, CancellationToken cancellationToken)
Get the ChannelRepresentations for given channels .
ValueTask SendMessage (Message? replyTo, MessageContent message, ulong channelId, CancellationToken cancellationToken)
Send a message to the IProvider.
Task SetReconnectInterval (uint reconnectInterval, bool connectNow)
Set the interval at which the provider starts jobs to try to reconnect.
ValueTask< Func< string?, string, ValueTask< Func< bool, ValueTask > > > > SendUpdateMessage (Models.RevisionInformation revisionInformation, Api.Models.EngineVersion engineVersion, DateTimeOffset? estimatedCompletionTime, string? gitHubOwner, string? gitHubRepo, ulong channelId, bool localCommitPushed, CancellationToken cancellationToken)
Send the message for a deployment.
Protected Member Functions
override async ValueTask Connect (CancellationToken cancellationToken)
Attempt to connect the Provider.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
override async ValueTask DisconnectImpl (CancellationToken cancellationToken)
Gracefully disconnects the provider.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
override async ValueTask< Dictionary< Models.ChatChannel, IEnumerable< ChannelRepresentation > > > MapChannelsImpl (IEnumerable< Models.ChatChannel > channels, CancellationToken cancellationToken)
Protected Member Functions inherited from Tgstation.Server.Host.Components.Chat.Providers.Provider
Provider (IJobManager jobManager, IAsyncDelayer asyncDelayer, ILogger< Provider > logger, ChatBot chatBot)
Initializes a new instance of the Provider class.
abstract ValueTask Connect (CancellationToken cancellationToken)
Attempt to connect the Provider.
abstract ValueTask DisconnectImpl (CancellationToken cancellationToken)
Gracefully disconnects the provider.
abstract ValueTask< Dictionary< ChatChannel, IEnumerable< ChannelRepresentation > > > MapChannelsImpl (IEnumerable< ChatChannel > channels, CancellationToken cancellationToken)
Implementation of MapChannels(IEnumerable<ChatChannel>, CancellationToken).
void EnqueueMessage (Message? message)
Queues a message for NextMessage(CancellationToken).
Properties
override bool Connected [get]
If the IProvider is currently connected.
override string BotMention [get]
The string that indicates the IProvider was mentioned.
Properties inherited from Tgstation.Server.Host.Components.Chat.Providers.Provider
Task InitialConnectionJob [get]
A Task that completes once the IProvider finishes it's first connection attempt regardless of success.
ChatBot ChatBot [get]
The ChatBot the Provider is for.
IAsyncDelayer AsyncDelayer [get]
The IAsyncDelayer for the Provider.
ILogger< Provider > Logger [get]
The ILogger for the Provider.
abstract bool Connected [get]
If the IProvider is currently connected.
abstract string BotMention [get]
The string that indicates the IProvider was mentioned.
bool Disposed [get, private set]
If the IProvider was disposed.
Properties inherited from Tgstation.Server.Host.Components.Chat.Providers.IProvider
bool Connected [get]
If the IProvider is currently connected.
bool Disposed [get]
If the IProvider was disposed.
string BotMention [get]
The string that indicates the IProvider was mentioned.
Task InitialConnectionJob [get]
A Task that completes once the IProvider finishes it's first connection attempt regardless of success.
Private Member Functions
async ValueTask< IEnumerable< IChannel > > GetAllAccessibleTextChannels (CancellationToken cancellationToken)
Get all text IChannels accessible to and supported by the bot.
List< IEmbedField > BuildUpdateEmbedFields (Models.RevisionInformation revisionInformation, EngineVersion engineVersion, string? gitHubOwner, string? gitHubRepo, bool localCommitPushed)
Create a List<T> of IEmbedFields for a discord update embed.
Optional< IReadOnlyList< IEmbed > > ConvertEmbed (ChatEmbed? embed)
Convert a ChatEmbed to an IEmbed parameters.
Static Private Member Functions
static string NormalizeMentions (string fromDiscord)
Normalize a discord mention string.
Private Attributes
readonly IAssemblyInformationProvider assemblyInformationProvider
The IAssemblyInformationProvider for the DiscordProvider.
readonly GeneralConfiguration generalConfiguration
The GeneralConfiguration for the DiscordProvider.
readonly ServiceProvider serviceProvider
The ServiceProvider containing Discord services.
readonly List< ulong > mappedChannels
List<T> of mapped channel Snowflakes.
readonly object connectDisconnectLock
Lock object used to sychronize connect/disconnect operations.
readonly bool deploymentBranding
If the tgstation-server logo is shown in deployment embeds.
readonly DiscordDMOutputDisplayType outputDisplayType
The DiscordDMOutputDisplayType.
CancellationTokenSource? gatewayCts
The CancellationTokenSource for the gatewayTask.
TaskCompletionSource? gatewayReadyTcs
The TaskCompletionSource for the initial gateway connection event.
Task< Result >? gatewayTask
The Task representing the lifetime of the client.
Snowflake currentUserId
The bot's Snowflake.
bool disposing
If serviceProvider is being disposed.
Static Private Attributes
static readonly ChannelType[] SupportedGuildChannelTypes
The ChannelTypes supported by the DiscordProvider for mapping.
Additional Inherited Members
Static Protected Member Functions inherited from Tgstation.Server.Host.Components.Chat.Providers.Provider
static string GetEngineCompilerPrefix (Api.Models.EngineType engineType)
Get the prefix for messages about deployments.
Detailed Description
IProvider for the Discord app.
Definition at line 42 of file DiscordProvider.cs.
Constructor & Destructor Documentation
DiscordProvider()
Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.DiscordProvider (IJobManager jobManager, IAsyncDelayer asyncDelayer, ILogger< DiscordProvider > logger, IAssemblyInformationProvider assemblyInformationProvider, ChatBot chatBot, GeneralConfiguration generalConfiguration)
Initializes a new instance of the DiscordProvider class.
Parameters
jobManager The IJobManager for the Provider.
asyncDelayer The IAsyncDelayer for the Provider.
logger The ILogger for the Provider.
assemblyInformationProvider The value of assemblyInformationProvider.
chatBot The ChatBot for the Provider.
generalConfiguration The value of generalConfiguration.
Definition at line 145 of file DiscordProvider.cs.
            : base(jobManager, asyncDelayer, logger, chatBot)
        {
            this.assemblyInformationProvider = assemblyInformationProvider ?? throw new ArgumentNullException(nameof(assemblyInformationProvider));
            this.generalConfiguration = generalConfiguration ?? throw new ArgumentNullException(nameof(generalConfiguration));
            mappedChannels = new List<ulong>();
            connectDisconnectLock = new object();
            var csb = new DiscordConnectionStringBuilder(chatBot.ConnectionString!);
            var botToken = csb.BotToken!;
            outputDisplayType = csb.DMOutputDisplay;
            deploymentBranding = csb.DeploymentBranding;
            serviceProvider = new ServiceCollection()
                .AddDiscordGateway(serviceProvider => botToken)
                .Configure<DiscordGatewayClientOptions>(options => options.Intents |= GatewayIntents.MessageContents)
                .AddSingleton(serviceProvider => (IDiscordResponders)this)
                .AddResponder<DiscordForwardingResponder>()
                .BuildServiceProvider();
        }
References Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.assemblyInformationProvider, Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.connectDisconnectLock, Tgstation.Server.Api.Models.Internal.ChatBotSettings.ConnectionString, Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.deploymentBranding, Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.generalConfiguration, Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.mappedChannels, Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.outputDisplayType, and Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.serviceProvider.
Member Function Documentation
BuildUpdateEmbedFields()
List< IEmbedField > Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.BuildUpdateEmbedFields (Models.RevisionInformation revisionInformation, EngineVersion engineVersion, string? gitHubOwner, string? gitHubRepo, bool localCommitPushed) private
Create a List<T> of IEmbedFields for a discord update embed.
Parameters
revisionInformation The RevisionInformation of the deployment.
engineVersion The EngineVersion of the deployment.
gitHubOwner The repository GitHub owner, if any.
gitHubRepo The repository GitHub name, if any.
localCommitPushed true if the local deployment commit was pushed to the remote repository.
Returns
A new List<T> of IEmbedFields to use.
Definition at line 908 of file DiscordProvider.cs.
        {
            bool gitHub = gitHubOwner != null && gitHubRepo != null;
            var engineField = engineVersion.Engine!.Value switch
            {
                EngineType.Byond => new EmbedField(
                    "BYOND Version",
                    $"{engineVersion.Version!.Major}.{engineVersion.Version.Minor}{(engineVersion.CustomIteration.HasValue ? $".{engineVersion.CustomIteration.Value}" : String.Empty)}",
                    true),
                EngineType.OpenDream => new EmbedField(
                    "OpenDream Version",
                    $"[{engineVersion.SourceSHA![..7]}]({generalConfiguration.OpenDreamGitUrl}/commit/{engineVersion.SourceSHA})",
                    true),
                _ => throw new InvalidOperationException($"Invaild EngineType: {engineVersion.Engine.Value}"),
            };
            var revisionSha = revisionInformation.CommitSha!;
            var revisionOriginSha = revisionInformation.OriginCommitSha!;
            var fields = new List<IEmbedField>
            {
                engineField,
            };
            if (gitHubOwner == null || gitHubRepo == null)
                return fields;
            fields.Add(
                new EmbedField(
                    "Local Commit",
                    localCommitPushed && gitHub
                        ? $"[{revisionSha[..7]}](https://github.com/{gitHubOwner}/{gitHubRepo}/commit/{revisionSha})"
                        : revisionSha[..7],
                    true));
            fields.Add(
                new EmbedField(
                    "Branch Commit",
                    gitHub
                        ? $"[{revisionOriginSha[..7]}](https://github.com/{gitHubOwner}/{gitHubRepo}/commit/{revisionOriginSha})"
                        : revisionOriginSha[..7],
                    true));
            fields.AddRange((revisionInformation.ActiveTestMerges ?? Enumerable.Empty<RevInfoTestMerge>())
                .Select(x => x.TestMerge)
                .Select(x => new EmbedField(
                    $"#{x.Number}",
                    $"[{x.TitleAtMerge}]({x.Url}) by _[@{x.Author}](https://github.com/{x.Author})_{Environment.NewLine}Commit: [{x.TargetCommitSha![..7]}](https://github.com/{gitHubOwner}/{gitHubRepo}/commit/{x.TargetCommitSha}){(String.IsNullOrWhiteSpace(x.Comment) ? String.Empty : $"{Environment.NewLine}_**{x.Comment}**_")}",
                    false)));
            return fields;
        }
References Tgstation.Server.Api.Models.EngineVersion.CustomIteration, and Tgstation.Server.Api.Models.EngineVersion.Engine.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.SendUpdateMessage().
Connect()
override async ValueTask Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.Connect (CancellationToken cancellationToken) protected virtual
Attempt to connect the Provider.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Chat.Providers.Provider.
Definition at line 582 of file DiscordProvider.cs.
        {
            try
            {
                lock (connectDisconnectLock)
                {
                    if (gatewayCts != null)
                        throw new InvalidOperationException("Discord gateway still active!");
                    gatewayCts = new CancellationTokenSource();
                }
                var gatewayCancellationToken = gatewayCts.Token;
                var gatewayClient = serviceProvider.GetRequiredService<DiscordGatewayClient>();
                Task<Result> localGatewayTask;
                gatewayReadyTcs = new TaskCompletionSource();
                using var gatewayConnectionAbortRegistration = cancellationToken.Register(() => gatewayReadyTcs.TrySetCanceled(cancellationToken));
                gatewayCancellationToken.Register(() => Logger.LogTrace("Stopping gateway client..."));
                // reconnects keep happening until we stop or it faults, our auto-reconnector will handle the latter
                localGatewayTask = gatewayClient.RunAsync(gatewayCancellationToken);
                try
                {
                    await Task.WhenAny(gatewayReadyTcs.Task, localGatewayTask);
                    cancellationToken.ThrowIfCancellationRequested();
                    if (localGatewayTask.IsCompleted)
                        throw new JobException(ErrorCode.ChatCannotConnectProvider);
                    var userClient = serviceProvider.GetRequiredService<IDiscordRestUserAPI>();
                    using var localCombinedCts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, gatewayCancellationToken);
                    var localCombinedCancellationToken = localCombinedCts.Token;
                    var currentUserResult = await userClient.GetCurrentUserAsync(localCombinedCancellationToken);
                    if (!currentUserResult.IsSuccess)
                    {
                        localCombinedCancellationToken.ThrowIfCancellationRequested();
                        Logger.LogWarning("Unable to retrieve current user: {result}", currentUserResult.LogFormat());
                        throw new JobException(ErrorCode.ChatCannotConnectProvider);
                    }
                    currentUserId = currentUserResult.Entity.ID;
                }
                finally
                {
                    gatewayTask = localGatewayTask;
                }
            }
            catch
            {
                // will handle cleanup
                // DCT: Musn't abort
                await DisconnectImpl(CancellationToken.None);
                throw;
            }
        }
References Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.connectDisconnectLock, Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.currentUserId, Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.DisconnectImpl(), Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.gatewayCts, Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.gatewayReadyTcs, Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.gatewayTask, Tgstation.Server.Host.Components.Chat.Providers.Provider.Logger, and Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.serviceProvider.
ConvertEmbed()
Optional< IReadOnlyList< IEmbed > > Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.ConvertEmbed (ChatEmbed? embed) private
Convert a ChatEmbed to an IEmbed parameters.
Parameters
embed The ChatEmbed to convert.
Returns
The parameter for sending a single IEmbed.
Definition at line 971 of file DiscordProvider.cs.
        {
            if (embed == null)
                return default;
            var embedErrors = new List<string>();
            Optional<Color> colour = default;
            if (embed.Colour != null)
                if (Int32.TryParse(embed.Colour[1..], NumberStyles.HexNumber, CultureInfo.InvariantCulture, out var argb))
                    colour = Color.FromArgb(argb);
                else
                    embedErrors.Add(
                        String.Format(
                            CultureInfo.InvariantCulture,
                            "Invalid embed colour: {0}",
                            embed.Colour));
            if (embed.Author != null && String.IsNullOrWhiteSpace(embed.Author.Name))
            {
                embedErrors.Add("Null or whitespace embed author name!");
                embed.Author = null;
            }
            List<IEmbedField>? fields = null;
            if (embed.Fields != null)
            {
                fields = new List<IEmbedField>();
                var i = -1;
                foreach (var field in embed.Fields)
                {
                    ++i;
                    var invalid = false;
                    if (String.IsNullOrWhiteSpace(field.Name))
                    {
                        embedErrors.Add(
                            String.Format(
                                CultureInfo.InvariantCulture,
                                "Null or whitespace field name at index {0}!",
                                i));
                        invalid = true;
                    }
                    if (String.IsNullOrWhiteSpace(field.Value))
                    {
                        embedErrors.Add(
                            String.Format(
                                CultureInfo.InvariantCulture,
                                "Null or whitespace field value at index {0}!",
                                i));
                        invalid = true;
                    }
                    if (invalid)
                        continue;
                    fields.Add(new EmbedField(field.Name!, field.Value!)
                    {
                        IsInline = field.IsInline ?? default(Optional<bool>),
                    });
                }
            }
            if (embed.Footer != null && String.IsNullOrWhiteSpace(embed.Footer.Text))
            {
                embedErrors.Add("Null or whitespace embed footer text!");
                embed.Footer = null;
            }
            if (embed.Image != null && String.IsNullOrWhiteSpace(embed.Image.Url))
            {
                embedErrors.Add("Null or whitespace embed image url!");
                embed.Image = null;
            }
            if (embed.Thumbnail != null && String.IsNullOrWhiteSpace(embed.Thumbnail.Url))
            {
                embedErrors.Add("Null or whitespace embed thumbnail url!");
                embed.Thumbnail = null;
            }
            Optional<DateTimeOffset> timestampOptional = default;
            if (embed.Timestamp != null)
                if (DateTimeOffset.TryParse(embed.Timestamp, CultureInfo.InvariantCulture, DateTimeStyles.AssumeLocal, out var timestamp))
                    timestampOptional = timestamp.ToUniversalTime();
                else
                    embedErrors.Add(
                        String.Format(
                            CultureInfo.InvariantCulture,
                            "Invalid embed timestamp: {0}",
                            embed.Timestamp));
            var discordEmbed = new Embed
            {
                Author = embed.Author != null
                    ? new EmbedAuthor(embed.Author.Name!)
                    {
                        IconUrl = embed.Author.IconUrl ?? default(Optional<string>),
                        ProxyIconUrl = embed.Author.ProxyIconUrl ?? default(Optional<string>),
                        Url = embed.Author.Url ?? default(Optional<string>),
                    }
                    : default(Optional<IEmbedAuthor>),
                Colour = colour,
                Description = embed.Description ?? default(Optional<string>),
                Fields = fields ?? default(Optional<IReadOnlyList<IEmbedField>>),
                Footer = embed.Footer != null
                    ? (Optional<IEmbedFooter>)new EmbedFooter(embed.Footer.Text!)
                    {
                        IconUrl = embed.Footer.IconUrl ?? default(Optional<string>),
                        ProxyIconUrl = embed.Footer.ProxyIconUrl ?? default(Optional<string>),
                    }
                    : default,
                Image = embed.Image != null
                    ? new EmbedImage(embed.Image.Url!)
                    {
                        Width = embed.Image.Width ?? default(Optional<int>),
                        Height = embed.Image.Height ?? default(Optional<int>),
                        ProxyUrl = embed.Image.ProxyUrl ?? default(Optional<string>),
                    }
                    : default(Optional<IEmbedImage>),
                Provider = embed.Provider != null
                    ? new EmbedProvider
                    {
                        Name = embed.Provider.Name ?? default(Optional<string>),
                        Url = embed.Provider.Url ?? default(Optional<string>),
                    }
                    : default(Optional<IEmbedProvider>),
                Thumbnail = embed.Thumbnail != null
                    ? new EmbedThumbnail(embed.Thumbnail.Url!)
                    {
                        Width = embed.Thumbnail.Width ?? default(Optional<int>),
                        Height = embed.Thumbnail.Height ?? default(Optional<int>),
                        ProxyUrl = embed.Thumbnail.ProxyUrl ?? default(Optional<string>),
                    }
                    : default(Optional<IEmbedThumbnail>),
                Timestamp = timestampOptional,
                Title = embed.Title ?? default(Optional<string>),
                Url = embed.Url ?? default(Optional<string>),
                Video = embed.Video != null
                    ? new EmbedVideo
                    {
                        Url = embed.Video.Url ?? default(Optional<string>),
                        Width = embed.Video.Width ?? default(Optional<int>),
                        Height = embed.Video.Height ?? default(Optional<int>),
                        ProxyUrl = embed.Video.ProxyUrl ?? default(Optional<string>),
                    }
                    : default(Optional<IEmbedVideo>),
            };
            var result = new List<IEmbed> { discordEmbed };
            if (embedErrors.Count > 0)
            {
                var joinedErrors = String.Join(Environment.NewLine, embedErrors);
                Logger.LogError("Embed description contains errors:{newLine}{issues}", Environment.NewLine, joinedErrors);
                result.Add(new Embed
                {
                    Title = "TGS Embed Errors",
                    Description = joinedErrors,
                    Colour = Color.Red,
                    Footer = new EmbedFooter("Please report this to your codebase's maintainers."),
                    Timestamp = DateTimeOffset.UtcNow,
                });
            }
            return result;
        }
References Tgstation.Server.Host.Components.Interop.ChatEmbed.Author, Tgstation.Server.Host.Components.Interop.ChatEmbed.Colour, Tgstation.Server.Host.Components.Interop.ChatEmbed.Fields, Tgstation.Server.Host.Components.Interop.ChatEmbed.Footer, Tgstation.Server.Host.Components.Interop.ChatEmbed.Image, Tgstation.Server.Host.Components.Chat.Providers.Provider.Logger, Tgstation.Server.Host.Components.Interop.ChatEmbedProvider.Name, Tgstation.Server.Host.Components.Interop.ChatEmbedFooter.Text, Tgstation.Server.Host.Components.Interop.ChatEmbed.Thumbnail, Tgstation.Server.Host.Components.Interop.ChatEmbed.Timestamp, and Tgstation.Server.Host.Components.Interop.ChatEmbedMedia.Url.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.SendMessage().
DisconnectImpl()
override async ValueTask Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.DisconnectImpl (CancellationToken cancellationToken) protected virtual
Gracefully disconnects the provider.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Chat.Providers.Provider.
Definition at line 642 of file DiscordProvider.cs.
        {
            Task<Result> localGatewayTask;
            CancellationTokenSource localGatewayCts;
            lock (connectDisconnectLock)
            {
                localGatewayTask = gatewayTask!;
                localGatewayCts = gatewayCts!;
                gatewayTask = null;
                gatewayCts = null;
                if (localGatewayTask == null)
                    return;
            }
            localGatewayCts.Cancel();
            var gatewayResult = await localGatewayTask;
            Logger.LogTrace("Gateway task complete");
            if (!gatewayResult.IsSuccess)
                Logger.LogWarning("Gateway issue: {result}", gatewayResult.LogFormat());
            localGatewayCts.Dispose();
        }
References Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.connectDisconnectLock, Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.gatewayCts, Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.gatewayTask, and Tgstation.Server.Host.Components.Chat.Providers.Provider.Logger.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.Connect().
DisposeAsync()
override async ValueTask Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.DisposeAsync () virtual
Reimplemented from Tgstation.Server.Host.Components.Chat.Providers.Provider.
Definition at line 174 of file DiscordProvider.cs.
        {
            lock (serviceProvider)
            {
                // serviceProvider can recursively dispose us
                if (disposing)
                    return;
                disposing = true;
            }
            await base.DisposeAsync();
            await serviceProvider.DisposeAsync();
            Logger.LogTrace("ServiceProvider disposed");
            // this line is purely here to shutup CA2213. It should always be null
            gatewayCts?.Dispose();
            disposing = false;
        }
References Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.disposing, Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.gatewayCts, Tgstation.Server.Host.Components.Chat.Providers.Provider.Logger, and Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.serviceProvider.
GetAllAccessibleTextChannels()
async ValueTask< IEnumerable< IChannel > > Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.GetAllAccessibleTextChannels (CancellationToken cancellationToken) private
Get all text IChannels accessible to and supported by the bot.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in an IEnumerable<T> of accessible and compatible IChannels.
Definition at line 845 of file DiscordProvider.cs.
        {
            var usersClient = serviceProvider.GetRequiredService<IDiscordRestUserAPI>();
            var currentGuildsResponse = await usersClient.GetCurrentUserGuildsAsync(ct: cancellationToken);
            if (!currentGuildsResponse.IsSuccess)
            {
                Logger.LogWarning(
                    "Error retrieving current discord guilds: {result}",
                    currentGuildsResponse.LogFormat());
                return Enumerable.Empty<IChannel>();
            }
            var guildsClient = serviceProvider.GetRequiredService<IDiscordRestGuildAPI>();
            async ValueTask<IEnumerable<IChannel>> GetGuildChannels(IPartialGuild guild)
            {
                var channelsTask = guildsClient.GetGuildChannelsAsync(guild.ID.Value, cancellationToken);
                var threads = await guildsClient.ListActiveGuildThreadsAsync(guild.ID.Value, cancellationToken);
                if (!threads.IsSuccess)
                    Logger.LogWarning(
                        "Error retrieving discord guild threads {guildId} ({guildName}): {result}",
                        guild.ID,
                        guild.Name,
                        threads.LogFormat());
                var channels = await channelsTask;
                if (!channels.IsSuccess)
                    Logger.LogWarning(
                        "Error retrieving discord guild channels {guildId} ({guildName}): {result}",
                        guild.ID,
                        guild.Name,
                        channels.LogFormat());
                if (!channels.IsSuccess && !threads.IsSuccess)
                    return Enumerable.Empty<IChannel>();
                if (channels.IsSuccess && threads.IsSuccess)
                    return channels.Entity.Concat(threads.Entity.Threads ?? Enumerable.Empty<IChannel>());
                return channels.Entity ?? threads.Entity?.Threads ?? Enumerable.Empty<IChannel>();
            }
            var guildsChannelsTasks = currentGuildsResponse.Entity
                .Select(GetGuildChannels);
            var guildsChannels = await ValueTaskExtensions.WhenAll(guildsChannelsTasks, currentGuildsResponse.Entity.Count);
            var allAccessibleChannels = guildsChannels
                .SelectMany(channels => channels)
                .Where(guildChannel => SupportedGuildChannelTypes.Contains(guildChannel.Type));
            return allAccessibleChannels;
        }
References Tgstation.Server.Host.Components.Chat.Providers.Provider.Logger, Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.serviceProvider, Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.SupportedGuildChannelTypes, and Tgstation.Server.Common.Extensions.ValueTaskExtensions.WhenAll().
Referenced by Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.MapChannelsImpl(), and Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.SendMessage().
MapChannelsImpl()
override async ValueTask< Dictionary< Models.ChatChannel, IEnumerable< ChannelRepresentation > > > Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.MapChannelsImpl (IEnumerable< Models.ChatChannel > channels, CancellationToken cancellationToken) protected
Definition at line 667 of file DiscordProvider.cs.
        {
            ArgumentNullException.ThrowIfNull(channels);
            var remapRequired = false;
            var guildsClient = serviceProvider.GetRequiredService<IDiscordRestGuildAPI>();
            var guildTasks = new ConcurrentDictionary<Snowflake, Task<Result<IGuild>>>();
            async ValueTask<Tuple<Models.ChatChannel, IEnumerable<ChannelRepresentation>>?> GetModelChannelFromDBChannel(Models.ChatChannel channelFromDB)
            {
                if (!channelFromDB.DiscordChannelId.HasValue)
                    throw new InvalidOperationException("ChatChannel missing DiscordChannelId!");
                var channelId = channelFromDB.DiscordChannelId.Value;
                var channelsClient = serviceProvider.GetRequiredService<IDiscordRestChannelAPI>();
                var discordChannelResponse = await channelsClient.GetChannelAsync(new Snowflake(channelId), cancellationToken);
                if (!discordChannelResponse.IsSuccess)
                {
                    Logger.LogWarning(
                        "Error retrieving discord channel {channelId}: {result}",
                        channelId,
                        discordChannelResponse.LogFormat());
                    var remapConditional = !(discordChannelResponse.Error is RestResultError<RestError> restResultError
                        && (restResultError.Error?.Code == DiscordError.MissingAccess
                        || restResultError.Error?.Code == DiscordError.UnknownChannel));
                    if (remapConditional)
                    {
                        Logger.Log(
                            remapRequired
                                ? LogLevel.Trace
                                : LogLevel.Debug,
                            "Error on channel {channelId} is not an access/thread issue. Will retry remap...",
                            channelId);
                        remapRequired = true;
                    }
                    return null;
                }
                var channelType = discordChannelResponse.Entity.Type;
                if (!SupportedGuildChannelTypes.Contains(channelType))
                {
                    Logger.LogWarning("Cound not map channel {channelId}! Incorrect type: {channelType}", channelId, discordChannelResponse.Entity.Type);
                    return null;
                }
                var guildId = discordChannelResponse.Entity.GuildID.Value;
                var added = false;
                var guildsResponse = await guildTasks.GetOrAdd(
                    guildId,
                    localGuildId =>
                    {
                        added = true;
                        return guildsClient.GetGuildAsync(
                            localGuildId,
                            false,
                            cancellationToken);
                    });
                if (!guildsResponse.IsSuccess)
                {
                    if (added)
                    {
                        Logger.LogWarning(
                            "Error retrieving discord guild {guildID}: {result}",
                            guildId,
                            guildsResponse.LogFormat());
                        remapRequired = true;
                    }
                    return null;
                }
                var connectionName = guildsResponse.Entity.Name;
                var channelModel = new ChannelRepresentation(
                    guildsResponse.Entity.Name,
                    discordChannelResponse.Entity.Name.Value!,
                    channelId)
                {
                    IsAdminChannel = channelFromDB.IsAdminChannel == true,
                    IsPrivateChannel = false,
                    Tag = channelFromDB.Tag,
                    EmbedsSupported = true,
                };
                Logger.LogTrace("Mapped channel {realId}: {friendlyName}", channelModel.RealId, channelModel.FriendlyName);
                return Tuple.Create<Models.ChatChannel, IEnumerable<ChannelRepresentation>>(
                    channelFromDB,
                    new List<ChannelRepresentation> { channelModel });
            }
            var tasks = channels
                .Where(x => x.DiscordChannelId != 0)
                .Select(GetModelChannelFromDBChannel);
            var channelTuples = await ValueTaskExtensions.WhenAll(tasks.ToList());
            var list = channelTuples
                .Where(x => x != null)
                .Cast<Tuple<Models.ChatChannel, IEnumerable<ChannelRepresentation>>>() // NRT my beloathed
                .ToList();
            var channelIdZeroModel = channels.FirstOrDefault(x => x.DiscordChannelId == 0);
            if (channelIdZeroModel != null)
            {
                Logger.LogInformation("Mapping ALL additional accessible text channels");
                var allAccessibleChannels = await GetAllAccessibleTextChannels(cancellationToken);
                var unmappedTextChannels = allAccessibleChannels
                    .Where(x => !tasks.Any(task => task.Result != null && new Snowflake(task.Result.Item1.DiscordChannelId!.Value) == x.ID));
                async ValueTask<Tuple<Models.ChatChannel, IEnumerable<ChannelRepresentation>>> CreateMappingsForUnmappedChannels()
                {
                    var unmappedTasks =
                        unmappedTextChannels.Select(
                            async unmappedTextChannel =>
{
                                var fakeChannelModel = new Models.ChatChannel
{
                                    DiscordChannelId = unmappedTextChannel.ID.Value,
                                    IsAdminChannel = channelIdZeroModel.IsAdminChannel,
                                    Tag = channelIdZeroModel.Tag,
                                };
                                var tuple = await GetModelChannelFromDBChannel(fakeChannelModel);
                                return tuple?.Item2.First();
                            })
                        .ToList();
                    // Add catch-all channel
                    unmappedTasks.Add(Task.FromResult<ChannelRepresentation?>(
                        new ChannelRepresentation(
                            "(Unknown Discord Guilds)",
                            "(Unknown Discord Channels)",
                            0)
{
                            IsAdminChannel = channelIdZeroModel.IsAdminChannel!.Value,
                            EmbedsSupported = true,
                            Tag = channelIdZeroModel.Tag,
                        }));
                    await Task.WhenAll(unmappedTasks);
                    return Tuple.Create<Models.ChatChannel, IEnumerable<ChannelRepresentation>>(
                        channelIdZeroModel,
                        unmappedTasks
                            .Select(x => x.Result)
                            .Where(x => x != null)
                            .Cast<ChannelRepresentation>() // NRT my beloathed
                            .ToList());
                }
                var task = CreateMappingsForUnmappedChannels();
                var tuple = await task;
                list.Add(tuple);
            }
            lock (mappedChannels)
            {
                mappedChannels.Clear();
                mappedChannels.AddRange(list.SelectMany(x => x.Item2).Select(x => x.RealId));
            }
            if (remapRequired)
            {
                Logger.LogWarning("Some channels failed to load with unknown errors. We will request that these be remapped, but it may result in communication spam. Please check prior logs and report an issue if this occurs.");
                EnqueueMessage(null);
            }
            return new Dictionary<Models.ChatChannel, IEnumerable<ChannelRepresentation>>(list.Select(x => new KeyValuePair<Models.ChatChannel, IEnumerable<ChannelRepresentation>>(x.Item1, x.Item2)));
        }
References Tgstation.Server.Host.Components.Chat.Providers.Provider.EnqueueMessage(), Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.GetAllAccessibleTextChannels(), Tgstation.Server.Api.Models.Internal.ChatChannelBase.IsAdminChannel, Tgstation.Server.Host.Components.Chat.ChannelRepresentation.IsAdminChannel, Tgstation.Server.Host.Components.Chat.Providers.Provider.Logger, Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.mappedChannels, Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.serviceProvider, Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.SupportedGuildChannelTypes, Tgstation.Server.Host.Components.Chat.ChannelRepresentation.Tag, and Tgstation.Server.Common.Extensions.ValueTaskExtensions.WhenAll().
NormalizeMentions()
static string Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.NormalizeMentions (string fromDiscord) static private
Normalize a discord mention string.
Parameters
fromDiscord The mention string provided by the Discord library.
Returns
The normalized mention string.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.RespondAsync().
RespondAsync() [1/2]
async Task< Result > Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.RespondAsync (IMessageCreate messageCreateEvent, CancellationToken cancellationToken)
Definition at line 481 of file DiscordProvider.cs.
        {
            ArgumentNullException.ThrowIfNull(messageCreateEvent);
            if ((messageCreateEvent.Type != MessageType.Default
                && messageCreateEvent.Type != MessageType.InlineReply)
                || messageCreateEvent.Author.ID == currentUserId)
                return Result.FromSuccess();
            var messageReference = new MessageReference
            {
                ChannelID = messageCreateEvent.ChannelID,
                GuildID = messageCreateEvent.GuildID,
                MessageID = messageCreateEvent.ID,
                FailIfNotExists = false,
            };
            var channelsClient = serviceProvider.GetRequiredService<IDiscordRestChannelAPI>();
            var channelResponse = await channelsClient.GetChannelAsync(messageCreateEvent.ChannelID, cancellationToken);
            if (!channelResponse.IsSuccess)
            {
                Logger.LogWarning(
                    "Failed to get channel {channelId} in response to message {messageId}!",
                    messageCreateEvent.ChannelID,
                    messageCreateEvent.ID);
                // we'll handle the errors ourselves
                return Result.FromSuccess();
            }
            var pm = channelResponse.Entity.Type == ChannelType.DM || channelResponse.Entity.Type == ChannelType.GroupDM;
            var shouldNotAnswer = !pm;
            if (shouldNotAnswer)
                lock (mappedChannels)
                    shouldNotAnswer = !mappedChannels.Contains(messageCreateEvent.ChannelID.Value) && !mappedChannels.Contains(0);
            var content = NormalizeMentions(messageCreateEvent.Content);
            var mentionedUs = messageCreateEvent.Mentions.Any(x => x.ID == currentUserId)
                || (!shouldNotAnswer && content.Split(' ').First().Equals(ChatManager.CommonMention, StringComparison.OrdinalIgnoreCase));
            if (shouldNotAnswer)
            {
                if (mentionedUs)
                    Logger.LogTrace(
                        "Ignoring mention from {channelId} ({channelName}) by {authorId} ({authorName}). Channel not mapped!",
                        messageCreateEvent.ChannelID,
                        channelResponse.Entity.Name,
                        messageCreateEvent.Author.ID,
                        messageCreateEvent.Author.Username);
                return Result.FromSuccess();
            }
            string guildName = "UNKNOWN";
            if (!pm)
            {
                var guildsClient = serviceProvider.GetRequiredService<IDiscordRestGuildAPI>();
                var messageGuildResponse = await guildsClient.GetGuildAsync(messageCreateEvent.GuildID.Value, false, cancellationToken);
                if (messageGuildResponse.IsSuccess)
                    guildName = messageGuildResponse.Entity.Name;
                else
                    Logger.LogWarning(
                        "Failed to get channel {channelID} in response to message {messageID}: {result}",
                        messageCreateEvent.ChannelID,
                        messageCreateEvent.ID,
                        messageGuildResponse.LogFormat());
            }
            var result = new DiscordMessage(
                new ChatUser(
                    new ChannelRepresentation(
                        pm ? messageCreateEvent.Author.Username : guildName,
                        channelResponse.Entity.Name.Value!,
                        messageCreateEvent.ChannelID.Value)
                    {
                        IsPrivateChannel = pm,
                        EmbedsSupported = true,
                        // isAdmin and Tag populated by manager
                    },
                    messageCreateEvent.Author.Username,
                    NormalizeMentions($"<@{messageCreateEvent.Author.ID}>"),
                    messageCreateEvent.Author.ID.Value),
                content,
                messageReference);
            EnqueueMessage(result);
            return Result.FromSuccess();
        }
References Tgstation.Server.Host.Components.Chat.ChatManager.CommonMention, Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.currentUserId, Tgstation.Server.Host.Components.Chat.Providers.Provider.EnqueueMessage(), Tgstation.Server.Host.Components.Chat.Providers.Provider.Logger, Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.mappedChannels, Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.NormalizeMentions(), and Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.serviceProvider.
RespondAsync() [2/2]
Task< Result > Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.RespondAsync (IReady readyEvent, CancellationToken cancellationToken)
Definition at line 572 of file DiscordProvider.cs.
        {
            ArgumentNullException.ThrowIfNull(readyEvent);
            Logger.LogTrace("Gatway ready. Version: {version}", readyEvent.Version);
            gatewayReadyTcs?.TrySetResult();
            return Task.FromResult(Result.FromSuccess());
        }
References Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.gatewayReadyTcs, and Tgstation.Server.Host.Components.Chat.Providers.Provider.Logger.
SendMessage()
override async ValueTask Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.SendMessage (Message? replyTo, MessageContent message, ulong channelId, CancellationToken cancellationToken) virtual
Send a message to the IProvider.
Parameters
replyTo The optional Message to reply to.
message The MessageContent.
channelId The ChannelRepresentation.RealId to send to.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Chat.Providers.Provider.
Definition at line 197 of file DiscordProvider.cs.
        {
            ArgumentNullException.ThrowIfNull(message);
            Optional<IMessageReference> replyToReference = default;
            Optional<IAllowedMentions> allowedMentions = default;
            if (replyTo != null && replyTo is DiscordMessage discordMessage)
            {
                replyToReference = discordMessage.MessageReference;
                allowedMentions = new AllowedMentions(
                    Parse: new List<MentionType> // reset settings back to how discord acts if this is not passed (which is different than the default if empty)
                    {
                        MentionType.Everyone,
                        MentionType.Roles,
                        MentionType.Users,
                    },
                    MentionRepliedUser: false); // disable reply mentions
            }
            var embeds = ConvertEmbed(message.Embed);
            var channelsClient = serviceProvider.GetRequiredService<IDiscordRestChannelAPI>();
            async ValueTask SendToChannel(Snowflake channelId)
            {
                if (message.Text == null)
                {
                    Logger.LogWarning(
                        "Failed to send to channel {channelId}: Message was null!",
                        channelId);
                    await channelsClient.CreateMessageAsync(
                        channelId,
                        "TGS: Could not send message to Discord. Message was `null`!",
                        messageReference: replyToReference,
                        allowedMentions: allowedMentions,
                        ct: cancellationToken);
                    return;
                }
                var result = await channelsClient.CreateMessageAsync(
                    channelId,
                    message.Text,
                    embeds: embeds,
                    messageReference: replyToReference,
                    allowedMentions: allowedMentions,
                    ct: cancellationToken);
                if (!result.IsSuccess)
                {
                    Logger.LogWarning(
                        "Failed to send to channel {channelId}: {result}",
                        channelId,
                        result.LogFormat());
                    if (result.Error is RestResultError<RestError> restError && restError.Error.Code == DiscordError.InvalidFormBody)
                        await channelsClient.CreateMessageAsync(
                            channelId,
                            "TGS: Could not send message to Discord. Body was malformed or too long",
                            messageReference: replyToReference,
                            allowedMentions: allowedMentions,
                            ct: cancellationToken);
                }
            }
            try
            {
                if (channelId == 0)
                {
                    IEnumerable<IChannel> unmappedTextChannels;
                    var allAccessibleTextChannels = await GetAllAccessibleTextChannels(cancellationToken);
                    lock (mappedChannels)
                    {
                        unmappedTextChannels = allAccessibleTextChannels
                            .Where(x => !mappedChannels.Contains(x.ID.Value))
                            .ToList();
                        var remapRequired = unmappedTextChannels.Any()
                            || mappedChannels.Any(
                                mappedChannel => !allAccessibleTextChannels.Any(
                                    accessibleTextChannel => accessibleTextChannel.ID == new Snowflake(mappedChannel)));
                        if (remapRequired)
                            EnqueueMessage(null);
                    }
                    // discord API confirmed weak boned: https://stackoverflow.com/a/52462336
                    if (unmappedTextChannels.Any())
                    {
                        Logger.LogDebug("Dispatching to {count} unmapped channels...", unmappedTextChannels.Count());
                        await ValueTaskExtensions.WhenAll(
                            unmappedTextChannels.Select(
                                x => SendToChannel(x.ID)));
                    }
                    return;
                }
                await SendToChannel(new Snowflake(channelId));
            }
            catch (Exception e) when (e is not OperationCanceledException)
            {
                Logger.LogWarning(e, "Error sending discord message!");
            }
        }
References Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.ConvertEmbed(), Tgstation.Server.Host.Components.Interop.MessageContent.Embed, Tgstation.Server.Host.Components.Chat.Providers.Provider.EnqueueMessage(), Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.GetAllAccessibleTextChannels(), Tgstation.Server.Host.Components.Chat.Providers.Provider.Logger, Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.mappedChannels, Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.serviceProvider, Tgstation.Server.Host.Components.Interop.MessageContent.Text, and Tgstation.Server.Common.Extensions.ValueTaskExtensions.WhenAll().
SendUpdateMessage()
override async ValueTask< Func< string?, string, ValueTask< Func< bool, ValueTask > > > > Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.SendUpdateMessage (Models.RevisionInformation revisionInformation, EngineVersion engineVersion, DateTimeOffset? estimatedCompletionTime, string? gitHubOwner, string? gitHubRepo, ulong channelId, bool localCommitPushed, CancellationToken cancellationToken)
Definition at line 304 of file DiscordProvider.cs.
        {
            ArgumentNullException.ThrowIfNull(revisionInformation);
            ArgumentNullException.ThrowIfNull(engineVersion);
            localCommitPushed |= revisionInformation.CommitSha == revisionInformation.OriginCommitSha;
            var fields = BuildUpdateEmbedFields(revisionInformation, engineVersion, gitHubOwner, gitHubRepo, localCommitPushed);
            Optional<IEmbedAuthor> author = new EmbedAuthor(assemblyInformationProvider.VersionPrefix)
            {
                Url = "https://github.com/tgstation/tgstation-server",
                IconUrl = "https://cdn.discordapp.com/attachments/1114451486374637629/1151650846019432448/tgs.png", // 404's in browsers but works in Discord
            };
            var embed = new Embed
            {
                Author = deploymentBranding ? author : default,
                Colour = Color.FromArgb(0xF1, 0xC4, 0x0F),
                Description = "TGS has begun deploying active repository code to production.",
                Fields = fields,
                Title = "Code Deployment",
                Footer = new EmbedFooter(
                    $"In progress...{(estimatedCompletionTime.HasValue ? " ETA" : String.Empty)}"),
                Timestamp = estimatedCompletionTime ?? default,
            };
            Logger.LogTrace("Attempting to post deploy embed to channel {channelId}...", channelId);
            var channelsClient = serviceProvider.GetRequiredService<IDiscordRestChannelAPI>();
            var prefix = GetEngineCompilerPrefix(engineVersion.Engine!.Value);
            var messageResponse = await channelsClient.CreateMessageAsync(
                new Snowflake(channelId),
                $"{prefix}: Deployment in progress...",
                embeds: new List<IEmbed> { embed },
                ct: cancellationToken);
            if (!messageResponse.IsSuccess)
                Logger.LogWarning("Failed to post deploy embed to channel {channelId}: {result}", channelId, messageResponse.LogFormat());
            return async (errorMessage, dreamMakerOutput) =>
            {
                var completionString = errorMessage == null ? "Pending" : "Failed";
                Embed CreateUpdatedEmbed(string message, Color color) => new()
                {
                    Author = embed.Author,
                    Colour = color,
                    Description = message,
                    Fields = fields,
                    Title = embed.Title,
                    Footer = new EmbedFooter(
                        completionString),
                    Timestamp = DateTimeOffset.UtcNow,
                };
                if (errorMessage == null)
                    embed = CreateUpdatedEmbed(
                        "The deployment completed successfully and will be available at the next server reboot.",
                        Color.Blue);
                else
                    embed = CreateUpdatedEmbed(
                        "The deployment failed.",
                        Color.Red);
                var showDMOutput = outputDisplayType switch
                {
                    DiscordDMOutputDisplayType.Always => true,
                    DiscordDMOutputDisplayType.Never => false,
                    DiscordDMOutputDisplayType.OnError => errorMessage != null,
                    _ => throw new InvalidOperationException($"Invalid DiscordDMOutputDisplayType: {outputDisplayType}"),
                };
                if (dreamMakerOutput != null)
                {
                    // https://github.com/discord-net/Discord.Net/blob/8349cd7e1eb92e9a3baff68082c30a7b43e8e9b7/src/Discord.Net.Core/Entities/Messages/EmbedBuilder.cs#L431
                    const int MaxFieldValueLength = 1024;
                    showDMOutput = showDMOutput && dreamMakerOutput.Length < MaxFieldValueLength - (6 + Environment.NewLine.Length);
                    if (showDMOutput)
                        fields.Add(new EmbedField(
                            "Compiler Output",
                            $"```{Environment.NewLine}{dreamMakerOutput}{Environment.NewLine}```",
                            false));
                }
                if (errorMessage != null)
                    fields.Add(new EmbedField(
                        "Error Message",
                        errorMessage,
                        false));
                var updatedMessageText = errorMessage == null ? $"{prefix}: Deployment pending reboot..." : $"{prefix}: Deployment failed!";
                IMessage? updatedMessage = null;
                async ValueTask CreateUpdatedMessage()
                {
                    var createUpdatedMessageResponse = await channelsClient.CreateMessageAsync(
                        new Snowflake(channelId),
                        updatedMessageText,
                        embeds: new List<IEmbed> { embed },
                        ct: cancellationToken);
                    if (!createUpdatedMessageResponse.IsSuccess)
                        Logger.LogWarning(
                            "Creating updated deploy embed failed: {result}",
                            createUpdatedMessageResponse.LogFormat());
                    else
                        updatedMessage = createUpdatedMessageResponse.Entity;
                }
                if (!messageResponse.IsSuccess)
                    await CreateUpdatedMessage();
                else
                {
                    var editResponse = await channelsClient.EditMessageAsync(
                        new Snowflake(channelId),
                        messageResponse.Entity.ID,
                        updatedMessageText,
                        embeds: new List<IEmbed> { embed },
                        ct: cancellationToken);
                    if (!editResponse.IsSuccess)
                    {
                        Logger.LogWarning(
                            "Updating deploy embed {messageId} failed, attempting new post: {result}",
                            messageResponse.Entity.ID,
                            editResponse.LogFormat());
                        await CreateUpdatedMessage();
                    }
                    else
                        updatedMessage = editResponse.Entity;
                }
                return async (active) =>
                {
                    if (updatedMessage == null || errorMessage != null)
                        return;
                    if (active)
                    {
                        completionString = "Succeeded";
                        updatedMessageText = $"{prefix}: Deployment succeeded!";
                        embed = CreateUpdatedEmbed(
                            "The deployment completed successfully and was applied to server.",
                            Color.Green);
                    }
                    else
                    {
                        completionString = "Inactive";
                        embed = CreateUpdatedEmbed(
                            "This deployment has been superceeded by a new one.",
                            Color.Gray);
                    }
                    var editResponse = await channelsClient.EditMessageAsync(
                        new Snowflake(channelId),
                        updatedMessage.ID,
                        updatedMessageText,
                        embeds: new List<IEmbed> { embed },
                        ct: cancellationToken);
                    if (!editResponse.IsSuccess)
                        Logger.LogWarning(
                            "Finalizing deploy embed {messageId} failed: {result}",
                            messageResponse.Entity.ID,
                            editResponse.LogFormat());
                };
            };
        }
References Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.assemblyInformationProvider, Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.BuildUpdateEmbedFields(), Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.deploymentBranding, Tgstation.Server.Api.Models.EngineVersion.Engine, Tgstation.Server.Host.Components.Chat.Providers.Provider.GetEngineCompilerPrefix(), Tgstation.Server.Host.Components.Chat.Providers.Provider.Logger, Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.outputDisplayType, Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.serviceProvider, and Tgstation.Server.Host.System.IAssemblyInformationProvider.VersionPrefix.
Member Data Documentation
assemblyInformationProvider
readonly IAssemblyInformationProvider Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.assemblyInformationProvider private
The IAssemblyInformationProvider for the DiscordProvider.
Definition at line 72 of file DiscordProvider.cs.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.DiscordProvider(), and Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.SendUpdateMessage().
connectDisconnectLock
readonly object Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.connectDisconnectLock private
Lock object used to sychronize connect/disconnect operations.
Definition at line 92 of file DiscordProvider.cs.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.Connect(), Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.DisconnectImpl(), and Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.DiscordProvider().
currentUserId
Snowflake Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.currentUserId private
The bot's Snowflake.
Definition at line 122 of file DiscordProvider.cs.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.Connect(), and Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.RespondAsync().
deploymentBranding
readonly bool Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.deploymentBranding private
If the tgstation-server logo is shown in deployment embeds.
Definition at line 97 of file DiscordProvider.cs.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.DiscordProvider(), and Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.SendUpdateMessage().
disposing
bool Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.disposing private
If serviceProvider is being disposed.
Definition at line 127 of file DiscordProvider.cs.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.DisposeAsync().
gatewayCts
CancellationTokenSource? Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.gatewayCts private
The CancellationTokenSource for the gatewayTask.
Definition at line 107 of file DiscordProvider.cs.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.Connect(), Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.DisconnectImpl(), and Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.DisposeAsync().
gatewayReadyTcs
TaskCompletionSource? Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.gatewayReadyTcs private
The TaskCompletionSource for the initial gateway connection event.
Definition at line 112 of file DiscordProvider.cs.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.Connect(), and Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.RespondAsync().
gatewayTask
Task<Result>? Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.gatewayTask private
The Task representing the lifetime of the client.
Definition at line 117 of file DiscordProvider.cs.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.Connect(), and Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.DisconnectImpl().
generalConfiguration
readonly GeneralConfiguration Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.generalConfiguration private
The GeneralConfiguration for the DiscordProvider.
Definition at line 77 of file DiscordProvider.cs.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.DiscordProvider().
mappedChannels
readonly List<ulong> Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.mappedChannels private
List<T> of mapped channel Snowflakes.
Definition at line 87 of file DiscordProvider.cs.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.DiscordProvider(), Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.MapChannelsImpl(), Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.RespondAsync(), and Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.SendMessage().
outputDisplayType
readonly DiscordDMOutputDisplayType Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.outputDisplayType private
The DiscordDMOutputDisplayType.
Definition at line 102 of file DiscordProvider.cs.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.DiscordProvider(), and Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.SendUpdateMessage().
serviceProvider
readonly ServiceProvider Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.serviceProvider private
The ServiceProvider containing Discord services.
Definition at line 82 of file DiscordProvider.cs.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.Connect(), Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.DiscordProvider(), Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.DisposeAsync(), Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.GetAllAccessibleTextChannels(), Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.MapChannelsImpl(), Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.RespondAsync(), Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.SendMessage(), and Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.SendUpdateMessage().
SupportedGuildChannelTypes
readonly ChannelType [] Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.SupportedGuildChannelTypes static private
Initial value:
=
        [
            ChannelType.GuildText,
            ChannelType.GuildAnnouncement,
            ChannelType.PrivateThread,
            ChannelType.PublicThread,
        ]
The ChannelTypes supported by the DiscordProvider for mapping.
Definition at line 61 of file DiscordProvider.cs.
Referenced by Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.GetAllAccessibleTextChannels(), and Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.MapChannelsImpl().
Property Documentation
BotMention
override string Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.BotMention get
The string that indicates the IProvider was mentioned.
Implements Tgstation.Server.Host.Components.Chat.Providers.IProvider.
Definition at line 48 of file DiscordProvider.cs.
        {
            get
            {
                if (!Connected)
                    throw new InvalidOperationException("Provider not connected");
                return NormalizeMentions($"<@{currentUserId}>");
            }
        }
Connected
override bool Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.Connected get
If the IProvider is currently connected.
Implements Tgstation.Server.Host.Components.Chat.Providers.IProvider.
Definition at line 45 of file DiscordProvider.cs.
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Chat/Providers/DiscordProvider.cs