tgstation-server: Tgstation.Server.Host.System.NativeMethods Class Reference
Tgstation.Server.Host.System.NativeMethods Class Reference
Native methods used by the code.
Public Types
enum CreateSymbolicLinkFlags : int { None = 0x0 , Directory = 0x1 , AllowUnprivilegedCreate = 0x2 }
See https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-createsymboliclinka#parameters.
enum ThreadAccess : int { SuspendResume = 0x0002 }
See https://msdn.microsoft.com/en-us/library/windows/desktop/ms686769(v=vs.85).aspx.
enum MiniDumpType : uint {
WithDataSegs = 0x00000001 , WithFullMemory = 0x00000002 , WithHandleData = 0x00000004 , WithUnloadedModules = 0x00000020 ,
WithThreadInfo = 0x00001000
}
See https://docs.microsoft.com/en-us/windows/win32/api/minidumpapiset/ne-minidumpapiset-minidump_type.
Public Member Functions
static int GetWindowThreadProcessId (IntPtr hWnd, out int lpdwProcessId)
See https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-getwindowthreadprocessid.
static IntPtr FindWindow (string? lpClassName, string lpWindowName)
See https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-findwindoww.
static int SendMessage (IntPtr hWnd, int wMsg, IntPtr wParam, IntPtr lParam)
See https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-sendmessage.
delegate bool EnumWindowProc (IntPtr hwnd, IntPtr lParam)
See https://msdn.microsoft.com/en-us/library/ms633493(v=VS.85).aspx.
static bool EnumChildWindows (IntPtr window, EnumWindowProc callback, IntPtr lParam)
See https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-enumchildwindows.
static int GetWindowText (IntPtr hWnd, StringBuilder lpString, int nMaxCount)
See https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-getwindowtextw.
static bool LogonUser (string lpszUsername, string? lpszDomain, string lpszPassword, int dwLogonType, int dwLogonProvider, out IntPtr phToken)
See https://msdn.microsoft.com/en-us/library/windows/desktop/aa378184(v=vs.85).aspx.
static bool CreateSymbolicLink (string lpSymlinkFileName, string lpTargetFileName, CreateSymbolicLinkFlags dwFlags)
See https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-createsymboliclinkw.
static IntPtr OpenThread (ThreadAccess dwDesiredAccess, bool bInheritHandle, uint dwThreadId)
See https://msdn.microsoft.com/en-us/library/windows/desktop/ms684335(v=vs.85).aspx.
static bool CloseHandle (IntPtr hObject)
See https://msdn.microsoft.com/en-us/library/windows/desktop/ms724211(v=vs.85).aspx.
static uint SuspendThread (IntPtr hThread)
See https://msdn.microsoft.com/en-us/library/windows/desktop/ms686345(v=vs.85).aspx.
static uint ResumeThread (IntPtr hThread)
See https://msdn.microsoft.com/en-us/library/windows/desktop/ms685086(v=vs.85).aspx.
static bool MiniDumpWriteDump (IntPtr hProcess, uint processId, SafeHandle hFile, MiniDumpType dumpType, IntPtr expParam, IntPtr userStreamParam, IntPtr callbackParam)
See https://docs.microsoft.com/en-us/windows/win32/api/minidumpapiset/nf-minidumpapiset-minidumpwritedump.
static int sd_notify (int unset_environment, [MarshalAs(UnmanagedType.LPUTF8Str)] string state)
See https://www.freedesktop.org/software/systemd/man/sd_notify.html.
Detailed Description
Native methods used by the code.
Definition at line 13 of file NativeMethods.cs.
Member Enumeration Documentation
CreateSymbolicLinkFlags
enum Tgstation.Server.Host.System.NativeMethods.CreateSymbolicLinkFlags : int
See https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-createsymboliclinka#parameters.
Enumerator
None
Directory
AllowUnprivilegedCreate
Definition at line 19 of file NativeMethods.cs.
        {
            None = 0x0,
            Directory = 0x1,
            AllowUnprivilegedCreate = 0x2,
        }
MiniDumpType
enum Tgstation.Server.Host.System.NativeMethods.MiniDumpType : uint
See https://docs.microsoft.com/en-us/windows/win32/api/minidumpapiset/ne-minidumpapiset-minidump_type.
Enumerator
WithDataSegs
WithFullMemory
WithHandleData
WithUnloadedModules
WithThreadInfo
Definition at line 38 of file NativeMethods.cs.
        {
            WithDataSegs = 0x00000001,
            WithFullMemory = 0x00000002,
            WithHandleData = 0x00000004,
            WithUnloadedModules = 0x00000020,
            WithThreadInfo = 0x00001000,
        }
ThreadAccess
enum Tgstation.Server.Host.System.NativeMethods.ThreadAccess : int
See https://msdn.microsoft.com/en-us/library/windows/desktop/ms686769(v=vs.85).aspx.
Enumerator
SuspendResume
Definition at line 29 of file NativeMethods.cs.
        {
            SuspendResume = 0x0002,
        }
Member Function Documentation
CloseHandle()
static bool Tgstation.Server.Host.System.NativeMethods.CloseHandle (IntPtr hObject)
See https://msdn.microsoft.com/en-us/library/windows/desktop/ms724211(v=vs.85).aspx.
Referenced by Tgstation.Server.Host.System.WindowsProcessFeatures.ResumeProcess(), and Tgstation.Server.Host.System.WindowsProcessFeatures.SuspendProcess().
CreateSymbolicLink()
static bool Tgstation.Server.Host.System.NativeMethods.CreateSymbolicLink (string lpSymlinkFileName, string lpTargetFileName, CreateSymbolicLinkFlags dwFlags)
See https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-createsymboliclinkw.
Referenced by Tgstation.Server.Host.IO.WindowsFilesystemLinkFactory.CreateSymbolicLink().
EnumChildWindows()
static bool Tgstation.Server.Host.System.NativeMethods.EnumChildWindows (IntPtr window, EnumWindowProc callback, IntPtr lParam)
See https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-enumchildwindows.
Referenced by Tgstation.Server.Host.System.WindowsNetworkPromptReaper.GetAllChildHandles().
EnumWindowProc()
delegate bool Tgstation.Server.Host.System.NativeMethods.EnumWindowProc (IntPtr hwnd, IntPtr lParam)
See https://msdn.microsoft.com/en-us/library/ms633493(v=VS.85).aspx.
FindWindow()
static IntPtr Tgstation.Server.Host.System.NativeMethods.FindWindow (string? lpClassName, string lpWindowName)
See https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-findwindoww.
Referenced by Tgstation.Server.Host.System.WindowsNetworkPromptReaper.ExecuteAsync().
GetWindowText()
static int Tgstation.Server.Host.System.NativeMethods.GetWindowText (IntPtr hWnd, StringBuilder lpString, int nMaxCount)
See https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-getwindowtextw.
Referenced by Tgstation.Server.Host.System.WindowsNetworkPromptReaper.ExecuteAsync().
GetWindowThreadProcessId()
static int Tgstation.Server.Host.System.NativeMethods.GetWindowThreadProcessId (IntPtr hWnd, out int lpdwProcessId)
See https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-getwindowthreadprocessid.
Referenced by Tgstation.Server.Host.System.WindowsNetworkPromptReaper.ExecuteAsync().
LogonUser()
static bool Tgstation.Server.Host.System.NativeMethods.LogonUser (string lpszUsername, string? lpszDomain, string lpszPassword, int dwLogonType, int dwLogonProvider, out IntPtr phToken)
See https://msdn.microsoft.com/en-us/library/windows/desktop/aa378184(v=vs.85).aspx.
Referenced by Tgstation.Server.Host.Security.WindowsSystemIdentityFactory.CreateSystemIdentity().
MiniDumpWriteDump()
static bool Tgstation.Server.Host.System.NativeMethods.MiniDumpWriteDump (IntPtr hProcess, uint processId, SafeHandle hFile, MiniDumpType dumpType, IntPtr expParam, IntPtr userStreamParam, IntPtr callbackParam)
See https://docs.microsoft.com/en-us/windows/win32/api/minidumpapiset/nf-minidumpapiset-minidumpwritedump.
Referenced by Tgstation.Server.Host.System.WindowsProcessFeatures.CreateDump().
OpenThread()
static IntPtr Tgstation.Server.Host.System.NativeMethods.OpenThread (ThreadAccess dwDesiredAccess, bool bInheritHandle, uint dwThreadId)
See https://msdn.microsoft.com/en-us/library/windows/desktop/ms684335(v=vs.85).aspx.
Referenced by Tgstation.Server.Host.System.WindowsProcessFeatures.ResumeProcess(), and Tgstation.Server.Host.System.WindowsProcessFeatures.SuspendProcess().
ResumeThread()
static uint Tgstation.Server.Host.System.NativeMethods.ResumeThread (IntPtr hThread)
See https://msdn.microsoft.com/en-us/library/windows/desktop/ms685086(v=vs.85).aspx.
Referenced by Tgstation.Server.Host.System.WindowsProcessFeatures.ResumeProcess().
sd_notify()
static int Tgstation.Server.Host.System.NativeMethods.sd_notify (int unset_environment, [MarshalAs(UnmanagedType.LPUTF8Str)] string state)
See https://www.freedesktop.org/software/systemd/man/sd_notify.html.
Referenced by Tgstation.Server.Host.System.SystemDManager.SendSDNotify().
SendMessage()
static int Tgstation.Server.Host.System.NativeMethods.SendMessage (IntPtr hWnd, int wMsg, IntPtr wParam, IntPtr lParam)
See https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-sendmessage.
Referenced by Tgstation.Server.Host.System.WindowsNetworkPromptReaper.ExecuteAsync().
SuspendThread()
static uint Tgstation.Server.Host.System.NativeMethods.SuspendThread (IntPtr hThread)
See https://msdn.microsoft.com/en-us/library/windows/desktop/ms686345(v=vs.85).aspx.
Referenced by Tgstation.Server.Host.System.WindowsProcessFeatures.SuspendProcess().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/System/NativeMethods.cs