tgstation-server: Tgstation.Server.Host.Jobs.JobsHub Class Reference
Tgstation.Server.Host.Jobs.JobsHub Class Reference sealed
A SignalR Hub for pushing job updates.
Public Member Functions
JobsHub (IHubConnectionMapper< JobsHub, IJobsHub > connectionMapper, IAuthenticationContext authenticationContext)
Initializes a new instance of the JobsHub class.
Public Member Functions inherited from Tgstation.Server.Host.Utils.SignalR.ConnectionMappingHub< JobsHub, IJobsHub >
override async Task OnConnectedAsync ()
override Task OnDisconnectedAsync (Exception? exception)
Static Public Member Functions
static string HubGroupName (long instanceId)
Get the group name for a given instanceId .
static string HubGroupName (Job job)
Get the group name for a given job .
Additional Inherited Members
Protected Member Functions inherited from Tgstation.Server.Host.Utils.SignalR.ConnectionMappingHub< JobsHub, IJobsHub >
ConnectionMappingHub (IHubConnectionMapper< TChildHub, THubMethods > connectionMapper, IAuthenticationContext authenticationContext)
Initializes a new instance of the ConnectionMappingHub<TParentHub, TClientMethods> class.
Detailed Description
A SignalR Hub for pushing job updates.
Definition at line 15 of file JobsHub.cs.
Constructor & Destructor Documentation
JobsHub()
Tgstation.Server.Host.Jobs.JobsHub.JobsHub (IHubConnectionMapper< JobsHub, IJobsHub > connectionMapper, IAuthenticationContext authenticationContext)
Initializes a new instance of the JobsHub class.
Parameters
connectionMapper The IHubConnectionMapper<THub, THubMethods> for the ConnectionMappingHub<TChildHub, THubMethods>.
authenticationContext The IAuthenticationContext for the ConnectionMappingHub<TChildHub, THubMethods>.
Definition at line 45 of file JobsHub.cs.
            : base(connectionMapper, authenticationContext)
        {
        }
Member Function Documentation
HubGroupName() [1/2]
static string Tgstation.Server.Host.Jobs.JobsHub.HubGroupName (Job job) static
Get the group name for a given job .
Parameters
job The Job.
Returns
The name of the group for the job .
Definition at line 30 of file JobsHub.cs.
        {
            ArgumentNullException.ThrowIfNull(job);
            if (job.Instance == null)
                throw new InvalidOperationException("job.Instance was null!");
            return HubGroupName(job.Instance.Require(x => x.Id));
        }
References Tgstation.Server.Host.Jobs.JobsHub.HubGroupName(), and Tgstation.Server.Host.Models.Job.Instance.
HubGroupName() [2/2]
static string Tgstation.Server.Host.Jobs.JobsHub.HubGroupName (long instanceId) static
Get the group name for a given instanceId .
Parameters
instanceId The Instance Api.Models.EntityId.Id.
Returns
The name of the group for the instanceId .
Referenced by Tgstation.Server.Host.Jobs.JobsHub.HubGroupName(), Tgstation.Server.Host.Jobs.JobsHubGroupMapper.MapConnectionGroups(), Tgstation.Server.Host.Jobs.JobsHubGroupMapper.RefreshHubGroups(), and Tgstation.Server.Host.Jobs.JobService.RunJob().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Jobs/JobsHub.cs