tgstation-server: Tgstation.Server.Host.Jobs.JobHandler Class Reference
Tgstation.Server.Host.Jobs.JobHandler Class Reference
Class for pairing Tasks with CancellationTokenSources
Public Member Functions
JobHandler (Func< CancellationToken, Task > jobActivator)
Construct a JobHandler
void Dispose ()
Task Wait (CancellationToken cancellationToken)
Wait for task to complete
void Cancel ()
Cancels task
void Start ()
Starts the job.
Properties
int? Progress [get, set]
The progress of the job
Private Attributes
readonly CancellationTokenSource cancellationTokenSource
The CancellationTokenSource for task
readonly Func< CancellationToken, Task > jobActivator
A Func<T, TResult> taking a CancellationToken and returning a Task that the JobHandler will wrap
Task task
The Task being run
Detailed Description
Class for pairing Tasks with CancellationTokenSources
Definition at line 11 of file JobHandler.cs.
Constructor & Destructor Documentation
JobHandler()
Tgstation.Server.Host.Jobs.JobHandler.JobHandler (Func< CancellationToken, Task > jobActivator)
Construct a JobHandler
Parameters
jobActivator The value of jobActivator.
Definition at line 32 of file JobHandler.cs.
         {
             this.jobActivator = jobActivator ?? throw new ArgumentNullException(nameof(jobActivator));
             cancellationTokenSource = new CancellationTokenSource();
         }
References Tgstation.Server.Host.Jobs.JobHandler.cancellationTokenSource, and Tgstation.Server.Host.Jobs.JobHandler.jobActivator.
Member Function Documentation
Cancel()
void Tgstation.Server.Host.Jobs.JobHandler.Cancel ()
Cancels task
Referenced by Tgstation.Server.Host.Jobs.JobManager.CancelJob().
Dispose()
void Tgstation.Server.Host.Jobs.JobHandler.Dispose ()
Start()
void Tgstation.Server.Host.Jobs.JobHandler.Start ()
Starts the job.
Definition at line 67 of file JobHandler.cs.
         {
             lock (cancellationTokenSource)
             {
                 if (task != null)
                     throw new InvalidOperationException("Job already started");
                 task = jobActivator(cancellationTokenSource.Token);
             }
         }
References Tgstation.Server.Host.Jobs.JobHandler.cancellationTokenSource, Tgstation.Server.Host.Jobs.JobHandler.jobActivator, and Tgstation.Server.Host.Jobs.JobHandler.task.
Wait()
Task Tgstation.Server.Host.Jobs.JobHandler.Wait (CancellationToken cancellationToken)
Wait for task to complete
Parameters
cancellationToken The CancellationToken for the operation
Returns
A Task representing the running operation
Definition at line 51 of file JobHandler.cs.
         {
             if (task == null)
                 throw new InvalidOperationException("Job not started!");
             return task.WithToken(cancellationToken);
         }
References Tgstation.Server.Host.Jobs.JobHandler.task.
Referenced by Tgstation.Server.Host.Jobs.JobManager.CancelJob(), and Tgstation.Server.Host.Jobs.JobManager.WaitForJobCompletion().
Member Data Documentation
cancellationTokenSource
readonly CancellationTokenSource Tgstation.Server.Host.Jobs.JobHandler.cancellationTokenSource private
The CancellationTokenSource for task
Definition at line 16 of file JobHandler.cs.
Referenced by Tgstation.Server.Host.Jobs.JobHandler.JobHandler(), and Tgstation.Server.Host.Jobs.JobHandler.Start().
jobActivator
readonly Func<CancellationToken, Task> Tgstation.Server.Host.Jobs.JobHandler.jobActivator private
A Func<T, TResult> taking a CancellationToken and returning a Task that the JobHandler will wrap
Definition at line 21 of file JobHandler.cs.
Referenced by Tgstation.Server.Host.Jobs.JobHandler.JobHandler(), and Tgstation.Server.Host.Jobs.JobHandler.Start().
task
Task Tgstation.Server.Host.Jobs.JobHandler.task private
The Task being run
Definition at line 26 of file JobHandler.cs.
Referenced by Tgstation.Server.Host.Jobs.JobHandler.Start(), and Tgstation.Server.Host.Jobs.JobHandler.Wait().
Property Documentation
Progress
int? Tgstation.Server.Host.Jobs.JobHandler.Progress get set
The progress of the job
Definition at line 44 of file JobHandler.cs.
 { get; set; }
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Jobs/JobHandler.cs