tgstation-server: Tgstation.Server.Common.Http.CachedResponseStream Class Reference
Tgstation.Server.Common.Http.CachedResponseStream Class Reference sealed
Caches the Stream from a HttpResponseMessage for later use.
Public Member Functions
override void Flush ()
override int Read (byte[] buffer, int offset, int count)
override long Seek (long offset, SeekOrigin origin)
override void SetLength (long value)
override void Write (byte[] buffer, int offset, int count)
Static Public Member Functions
static async ValueTask< CachedResponseStream > Create (HttpResponseMessage response)
Asyncronously creates a new CachedResponseStream.
Protected Member Functions
override void Dispose (bool disposing)
Properties
override bool CanRead [get]
override bool CanSeek [get]
override bool CanWrite [get]
override long Length [get]
override long Position [get, set]
Private Member Functions
CachedResponseStream (HttpContent responseContent, Stream responseStream)
Initializes a new instance of the CachedResponseStream class.
Private Attributes
readonly HttpContent responseContent
The HttpContent for the CachedResponseStream.
readonly Stream responseStream
The reponse content Stream.
Detailed Description
Caches the Stream from a HttpResponseMessage for later use.
Definition at line 11 of file CachedResponseStream.cs.
Constructor & Destructor Documentation
CachedResponseStream()
Tgstation.Server.Common.Http.CachedResponseStream.CachedResponseStream (HttpContent responseContent, Stream responseStream) private
Initializes a new instance of the CachedResponseStream class.
Parameters
responseContent The value of responseContent.
responseStream The value of responseStream.
Definition at line 101 of file CachedResponseStream.cs.
        {
            this.responseContent = responseContent;
            this.responseStream = responseStream;
        }
References Tgstation.Server.Common.Http.CachedResponseStream.responseContent, and Tgstation.Server.Common.Http.CachedResponseStream.responseStream.
Member Function Documentation
Create()
static async ValueTask< CachedResponseStream > Tgstation.Server.Common.Http.CachedResponseStream.Create (HttpResponseMessage response) static
Asyncronously creates a new CachedResponseStream.
Parameters
response The HttpResponseMessage to build from.
Returns
A Task<TResult> resulting in a new CachedResponseStream.
Definition at line 28 of file CachedResponseStream.cs.
        {
            if (response == null)
                throw new ArgumentNullException(nameof(response));
            using (response)
            {
                var content = response.Content;
                response.Content = null;
                try
                {
                    // don't cry about the missing CancellationToken overload: https://github.com/dotnet/runtime/issues/916
                    var responseStream = await content.ReadAsStreamAsync().ConfigureAwait(false);
                    return new CachedResponseStream(content, responseStream);
                }
                catch
                {
                    content.Dispose();
                    throw;
                }
            }
        }
References Tgstation.Server.Common.Http.CachedResponseStream.responseStream.
Referenced by Tgstation.Server.Host.IO.RequestFileStreamProvider.InitiateDownload(), and Tgstation.Server.Client.ApiClient.RunRequest< TResult >().
Dispose()
override void Tgstation.Server.Common.Http.CachedResponseStream.Dispose (bool disposing) protected
Definition at line 86 of file CachedResponseStream.cs.
        {
            base.Dispose(disposing);
            if (!disposing)
                return;
            responseContent.Dispose();
            responseStream.Dispose();
        }
References Tgstation.Server.Common.Http.CachedResponseStream.responseContent, and Tgstation.Server.Common.Http.CachedResponseStream.responseStream.
Referenced by Tgstation.Server.Host.IO.RequestFileStreamProvider.DisposeAsync().
Flush()
override void Tgstation.Server.Common.Http.CachedResponseStream.Flush ()
Read()
override int Tgstation.Server.Common.Http.CachedResponseStream.Read (byte[] buffer, int offset, int count)
Seek()
override long Tgstation.Server.Common.Http.CachedResponseStream.Seek (long offset, SeekOrigin origin)
SetLength()
override void Tgstation.Server.Common.Http.CachedResponseStream.SetLength (long value)
Write()
override void Tgstation.Server.Common.Http.CachedResponseStream.Write (byte[] buffer, int offset, int count)
Member Data Documentation
responseContent
readonly HttpContent Tgstation.Server.Common.Http.CachedResponseStream.responseContent private
The HttpContent for the CachedResponseStream.
Definition at line 16 of file CachedResponseStream.cs.
Referenced by Tgstation.Server.Common.Http.CachedResponseStream.CachedResponseStream(), and Tgstation.Server.Common.Http.CachedResponseStream.Dispose().
responseStream
readonly Stream Tgstation.Server.Common.Http.CachedResponseStream.responseStream private
The reponse content Stream.
Definition at line 21 of file CachedResponseStream.cs.
Referenced by Tgstation.Server.Common.Http.CachedResponseStream.CachedResponseStream(), Tgstation.Server.Common.Http.CachedResponseStream.Create(), and Tgstation.Server.Common.Http.CachedResponseStream.Dispose().
Property Documentation
CanRead
override bool Tgstation.Server.Common.Http.CachedResponseStream.CanRead get
Definition at line 52 of file CachedResponseStream.cs.
CanSeek
override bool Tgstation.Server.Common.Http.CachedResponseStream.CanSeek get
Definition at line 55 of file CachedResponseStream.cs.
CanWrite
override bool Tgstation.Server.Common.Http.CachedResponseStream.CanWrite get
Definition at line 58 of file CachedResponseStream.cs.
Length
override long Tgstation.Server.Common.Http.CachedResponseStream.Length get
Definition at line 61 of file CachedResponseStream.cs.
Position
override long Tgstation.Server.Common.Http.CachedResponseStream.Position get set
Definition at line 64 of file CachedResponseStream.cs.
        {
            get => responseStream.Position;
            set => responseStream.Position = value;
        }
The documentation for this class was generated from the following file:
src/Tgstation.Server.Common/Http/CachedResponseStream.cs