tgstation-server: Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog Class Reference
Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog Class Reference
A IWatchdog that, instead of killing servers for updates, uses the wonders of symlinks to swap out changes without killing DreamDaemon.
Public Member Functions
WindowsWatchdog (IChatManager chat, ISessionControllerFactory sessionControllerFactory, IDmbFactory dmbFactory, ISessionPersistor sessionPersistor, IJobManager jobManager, IServerControl serverControl, IAsyncDelayer asyncDelayer, IIOManager diagnosticsIOManager, IEventConsumer eventConsumer, IRemoteDeploymentManagerFactory remoteDeploymentManagerFactory, IIOManager gameIOManager, ISymlinkFactory symlinkFactory, ILogger< WindowsWatchdog > logger, DreamDaemonLaunchParameters initialLaunchParameters, Api.Models.Instance instance, bool autoStart)
Initializes a new instance of the WindowsWatchdog class.
Public Member Functions inherited from Tgstation.Server.Host.Components.Watchdog.BasicWatchdog
BasicWatchdog (IChatManager chat, ISessionControllerFactory sessionControllerFactory, IDmbFactory dmbFactory, ISessionPersistor sessionPersistor, IJobManager jobManager, IServerControl serverControl, IAsyncDelayer asyncDelayer, IIOManager diagnosticsIOManager, IEventConsumer eventConsumer, IRemoteDeploymentManagerFactory remoteDeploymentManagerFactory, ILogger< BasicWatchdog > logger, DreamDaemonLaunchParameters initialLaunchParameters, Api.Models.Instance instance, bool autoStart)
Initializes a new instance of the BasicWatchdog class.
override ValueTask ResetRebootState (CancellationToken cancellationToken)
Cancels pending graceful actions.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
sealed override ValueTask InstanceRenamed (string newInstanceName, CancellationToken cancellationToken)
Called when the owning Instance is renamed.
Parameters
newInstanceName The new Api.Models.NamedEntity.Name.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Public Member Functions inherited from Tgstation.Server.Host.Components.Watchdog.WatchdogBase
async ValueTask DisposeAsync ()
async ValueTask ChangeSettings (DreamDaemonLaunchParameters launchParameters, CancellationToken cancellationToken)
Changes the ActiveLaunchParameters. If currently running, may trigger a graceful restart.
Parameters
launchParameters The new DreamDaemonLaunchParameters. May be modified.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
async ValueTask< MessageContent > HandleChatCommand (string commandName, string arguments, ChatUser sender, CancellationToken cancellationToken)
Handle a chat command.
Parameters
commandName The command name.
arguments Everything typed after commandName minus leading spaces.
sender The sending ChatUser.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the MessageContent text to send back.
async ValueTask Launch (CancellationToken cancellationToken)
Start the IWatchdog.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
virtual async ValueTask ResetRebootState (CancellationToken cancellationToken)
Cancels pending graceful actions.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
async ValueTask Restart (bool graceful, CancellationToken cancellationToken)
Restarts the watchdog.
Parameters
graceful If true the restart will be delayed until a reboot is detected in the active server's DMAPI and this function will retrun immediately.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
async Task StartAsync (CancellationToken cancellationToken)
async Task StopAsync (CancellationToken cancellationToken)
async ValueTask Terminate (bool graceful, CancellationToken cancellationToken)
Stops the watchdog.
Parameters
graceful If true the termination will be delayed until a reboot is detected in the active server's DMAPI and this function will return immediately.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
async ValueTask HandleRestart (Version updateVersion, bool handlerMayDelayShutdownWithExtremelyLongRunningTasks, CancellationToken cancellationToken)
Handle a restart of the server.
Parameters
updateVersion The Version being updated to, null if not being changed.
handlerMayDelayShutdownWithExtremelyLongRunningTasks If false the IRestartHandler should aim to complete the Task returned from this function ASAP.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
abstract ValueTask InstanceRenamed (string newInstanceName, CancellationToken cancellationToken)
Called when the owning Instance is renamed.
Parameters
newInstanceName The new Api.Models.NamedEntity.Name.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
async ValueTask CreateDump (CancellationToken cancellationToken)
Attempt to create a process dump for DreamDaemon.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
ValueTask Launch (CancellationToken cancellationToken)
Start the IWatchdog.
ValueTask ChangeSettings (DreamDaemonLaunchParameters launchParameters, CancellationToken cancellationToken)
Changes the ActiveLaunchParameters. If currently running, may trigger a graceful restart.
ValueTask Restart (bool graceful, CancellationToken cancellationToken)
Restarts the watchdog.
ValueTask Terminate (bool graceful, CancellationToken cancellationToken)
Stops the watchdog.
ValueTask ResetRebootState (CancellationToken cancellationToken)
Cancels pending graceful actions.
ValueTask CreateDump (CancellationToken cancellationToken)
Attempt to create a process dump for DreamDaemon.
ValueTask HandleEvent (EventType eventType, IEnumerable< string > parameters, bool deploymentPipeline, CancellationToken cancellationToken)
Handle a given eventType .
ValueTask InstanceRenamed (string newInstanceName, CancellationToken cancellationToken)
Called when the owning Instance is renamed.
ValueTask< MessageContent > HandleChatCommand (string commandName, string arguments, ChatUser sender, CancellationToken cancellationToken)
Handle a chat command.
ValueTask HandleRestart (Version updateVersion, bool handlerMayDelayShutdownWithExtremelyLongRunningTasks, CancellationToken cancellationToken)
Handle a restart of the server.
Protected Member Functions
override async ValueTask DisposeAndNullControllersImpl ()
Call IDisposable.Dispose and null the fields for all ISessionControllers.
Returns
A ValueTask representing the running operation.
override async ValueTask< MonitorAction > HandleNormalReboot (CancellationToken cancellationToken)
Handler for MonitorActivationReason.ActiveServerRebooted when the RebootState is RebootState.Normal.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the MonitorAction to take.
override async ValueTask HandleNewDmbAvailable (CancellationToken cancellationToken)
Handler for MonitorActivationReason.NewDmbAvailable.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
sealed override async ValueTask< IDmbProvider > PrepServerForLaunch (IDmbProvider dmbToUse, CancellationToken cancellationToken)
Prepare the server to launch a new instance with the WatchdogBase.ActiveLaunchParameters and a given dmbToUse .
Parameters
dmbToUse The IDmbProvider to be launched. Will not be disposed by this function.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the modified IDmbProvider to be used.
virtual async ValueTask ApplyInitialDmb (CancellationToken cancellationToken)
Set the ReattachInformation.InitialDmb for the BasicWatchdog.Server.
override async ValueTask SessionStartupPersist (CancellationToken cancellationToken)
Called to save the current Server into the WatchdogBase.SessionPersistor when initially launched.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
override async ValueTask< MonitorAction > HandleMonitorWakeup (MonitorActivationReason reason, CancellationToken cancellationToken)
Handles the actions to take when the monitor has to "wake up".
Parameters
activationReason The MonitorActivationReason that caused the invocation. Will never be MonitorActivationReason.HealthCheck.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the MonitorAction to take.
Protected Member Functions inherited from Tgstation.Server.Host.Components.Watchdog.BasicWatchdog
override async ValueTask< MonitorAction > HandleMonitorWakeup (MonitorActivationReason reason, CancellationToken cancellationToken)
Handles the actions to take when the monitor has to "wake up".
Parameters
activationReason The MonitorActivationReason that caused the invocation. Will never be MonitorActivationReason.HealthCheck.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the MonitorAction to take.
override async ValueTask DisposeAndNullControllersImpl ()
Call IDisposable.Dispose and null the fields for all ISessionControllers.
Returns
A ValueTask representing the running operation.
sealed override ISessionController GetActiveController ()
Get the active ISessionController.
Returns
The active ISessionController.
override async ValueTask InitController (ValueTask eventTask, ReattachInformation reattachInfo, CancellationToken cancellationToken)
Starts all ISessionControllers.
Parameters
eventTask A, possibly active, Task for an event that's running.
reattachInfo ReattachInformation to use, if any.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
virtual ValueTask SessionStartupPersist (CancellationToken cancellationToken)
Called to save the current Server into the WatchdogBase.SessionPersistor when initially launched.
virtual ValueTask< MonitorAction > HandleNormalReboot (CancellationToken cancellationToken)
Handler for MonitorActivationReason.ActiveServerRebooted when the RebootState is RebootState.Normal.
virtual async ValueTask HandleNewDmbAvailable (CancellationToken cancellationToken)
Handler for MonitorActivationReason.NewDmbAvailable.
virtual ValueTask< IDmbProvider > PrepServerForLaunch (IDmbProvider dmbToUse, CancellationToken cancellationToken)
Prepare the server to launch a new instance with the WatchdogBase.ActiveLaunchParameters and a given dmbToUse .
Protected Member Functions inherited from Tgstation.Server.Host.Components.Watchdog.WatchdogBase
WatchdogBase (IChatManager chat, ISessionControllerFactory sessionControllerFactory, IDmbFactory dmbFactory, ISessionPersistor sessionPersistor, IJobManager jobManager, IServerControl serverControl, IAsyncDelayer asyncDelayer, IIOManager diagnosticsIOManager, IEventConsumer eventConsumer, IRemoteDeploymentManagerFactory remoteDeploymentManagerFactory, ILogger< WatchdogBase > logger, DreamDaemonLaunchParameters initialLaunchParameters, Api.Models.Instance metadata, bool autoStart)
Initializes a new instance of the WatchdogBase class.
abstract ValueTask InitController (ValueTask eventTask, ReattachInformation reattachInfo, CancellationToken cancellationToken)
Starts all ISessionControllers.
async ValueTask LaunchNoLock (bool startMonitor, bool announce, bool announceFailure, ReattachInformation reattachInfo, CancellationToken cancellationToken)
Launches the watchdog.
async ValueTask< bool > StopMonitor ()
Stops MonitorLifetimes(CancellationToken). Doesn't kill the servers.
async ValueTask CheckLaunchResult (ISessionController controller, string serverName, CancellationToken cancellationToken)
Check the LaunchResult of a given controller for errors and throw a JobException if any are detected.
async ValueTask ReattachFailure (CancellationToken cancellationToken)
Call from InitController(ValueTask, ReattachInformation, CancellationToken) when a reattach operation fails to attempt a fresh start.
abstract ValueTask DisposeAndNullControllersImpl ()
Call IDisposable.Dispose and null the fields for all ISessionControllers.
async ValueTask DisposeAndNullControllers (CancellationToken cancellationToken)
Wrapper for DisposeAndNullControllersImpl under a locked context.
abstract ISessionController GetActiveController ()
Get the active ISessionController.
abstract ValueTask< MonitorAction > HandleMonitorWakeup (MonitorActivationReason activationReason, CancellationToken cancellationToken)
Handles the actions to take when the monitor has to "wake up".
async ValueTask BeforeApplyDmb (Models.CompileJob newCompileJob, CancellationToken cancellationToken)
To be called before a given newCompileJob goes live.
async ValueTask HandleEventImpl (EventType eventType, IEnumerable< string > parameters, bool relayToSession, CancellationToken cancellationToken)
Handle a given eventType without re-throwing errors.
Properties
SwappableDmbProvider ActiveSwappable [get, private set]
The SwappableDmbProvider for WatchdogBase.LastLaunchParameters.
IIOManager GameIOManager [get]
The IIOManager for the WindowsWatchdog pointing to the Game directory.
Properties inherited from Tgstation.Server.Host.Components.Watchdog.BasicWatchdog
sealed override bool AlphaIsActive [get]
If the alpha server is the active server.
sealed override? RebootState RebootState [get]
The Session.RebootState of the active server.
ISessionController Server [get, private set]
The single ISessionController.
Properties inherited from Tgstation.Server.Host.Components.Watchdog.WatchdogBase
WatchdogStatus Status [get, set]
The current WatchdogStatus.
abstract bool AlphaIsActive [get]
If the alpha server is the active server.
DreamDaemonLaunchParameters ActiveLaunchParameters [get, protected set]
The DreamDaemonLaunchParameters to be applied.
DreamDaemonLaunchParameters LastLaunchParameters [get, protected set]
The DreamDaemonLaunchParameters the active server is using.
Models.CompileJob ActiveCompileJob [get]
Retrieves the Models.CompileJob currently running on the server.
abstract ? RebootState RebootState [get]
The Session.RebootState of the active server.
TaskCompletionSource ActiveParametersUpdated [get, set]
TaskCompletionSource that completes when ActiveLaunchParameters are changed and we are running.
ISessionPersistor SessionPersistor [get]
The ISessionPersistor for the WatchdogBase.
ILogger< WatchdogBase > Logger [get]
The ILogger for the WatchdogBase.
IChatManager Chat [get]
The IChatManager for the WatchdogBase.
ISessionControllerFactory SessionControllerFactory [get]
The ISessionControllerFactory for the WatchdogBase.
IDmbFactory DmbFactory [get]
The IDmbFactory for the WatchdogBase.
IAsyncDelayer AsyncDelayer [get]
The IAsyncDelayer for the WatchdogBase.
Properties inherited from Tgstation.Server.Host.Components.Watchdog.IWatchdog
WatchdogStatus Status [get]
The current WatchdogStatus.
bool AlphaIsActive [get]
If the alpha server is the active server.
Models.CompileJob ActiveCompileJob [get]
Retrieves the Models.CompileJob currently running on the server.
DreamDaemonLaunchParameters ActiveLaunchParameters [get]
The DreamDaemonLaunchParameters to be applied.
DreamDaemonLaunchParameters LastLaunchParameters [get]
The DreamDaemonLaunchParameters the active server is using.
RebootState? RebootState [get]
The Session.RebootState of the active server.
Private Member Functions
ValueTask InitialLink (CancellationToken cancellationToken)
Create the initial link to the live game directory using ActiveSwappable.
async ValueTask PerformDmbSwap (SwappableDmbProvider newProvider, CancellationToken cancellationToken)
Suspends the BasicWatchdog.Server and calls SwappableDmbProvider.MakeActive(CancellationToken) on a newProvider .
Task DrainDeploymentCleanupTasks (bool blocking)
Asynchronously drain deploymentCleanupTasks.
Private Attributes
readonly ISymlinkFactory symlinkFactory
The ISymlinkFactory for the WindowsWatchdog.
readonly List< Task > deploymentCleanupTasks
List<T> of Tasks that are waiting to clean up old deployments.
SwappableDmbProvider pendingSwappable
The active SwappableDmbProvider for WatchdogBase.ActiveLaunchParameters.
volatile TaskCompletionSource deploymentCleanupGate
The TaskCompletionSource representing the cleanup of an unused IDmbProvider.
Detailed Description
A IWatchdog that, instead of killing servers for updates, uses the wonders of symlinks to swap out changes without killing DreamDaemon.
Definition at line 25 of file WindowsWatchdog.cs.
Constructor & Destructor Documentation
WindowsWatchdog()
Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.WindowsWatchdog (IChatManager chat, ISessionControllerFactory sessionControllerFactory, IDmbFactory dmbFactory, ISessionPersistor sessionPersistor, IJobManager jobManager, IServerControl serverControl, IAsyncDelayer asyncDelayer, IIOManager diagnosticsIOManager, IEventConsumer eventConsumer, IRemoteDeploymentManagerFactory remoteDeploymentManagerFactory, IIOManager gameIOManager, ISymlinkFactory symlinkFactory, ILogger< WindowsWatchdog > logger, DreamDaemonLaunchParameters initialLaunchParameters, Api.Models.Instance instance, bool autoStart)
Initializes a new instance of the WindowsWatchdog class.
Parameters
chat The IChatManager for the WatchdogBase.
sessionControllerFactory The ISessionControllerFactory for the WatchdogBase.
dmbFactory The IDmbFactory for the WatchdogBase.
sessionPersistor The ISessionPersistor for the WatchdogBase.
jobManager The IJobManager for the WatchdogBase.
serverControl The IServerControl for the WatchdogBase.
asyncDelayer The IAsyncDelayer for the WatchdogBase.
diagnosticsIOManager The IIOManager for the WatchdogBase.
eventConsumer The IEventConsumer for the WatchdogBase.
remoteDeploymentManagerFactory The IRemoteDeploymentManagerFactory for the WatchdogBase.
gameIOManager The value of GameIOManager.
symlinkFactory The value of symlinkFactory.
logger The ILogger for the WatchdogBase.
initialLaunchParameters The DreamDaemonLaunchParameters for the WatchdogBase.
instance The Api.Models.Instance for the WatchdogBase.
autoStart The autostart value for the WatchdogBase.
Definition at line 76 of file WindowsWatchdog.cs.
            : base(
                chat,
                sessionControllerFactory,
                dmbFactory,
                sessionPersistor,
                jobManager,
                serverControl,
                asyncDelayer,
                diagnosticsIOManager,
                eventConsumer,
                remoteDeploymentManagerFactory,
                logger,
                initialLaunchParameters,
                instance,
                autoStart)
        {
            try
            {
                GameIOManager = gameIOManager ?? throw new ArgumentNullException(nameof(gameIOManager));
                this.symlinkFactory = symlinkFactory ?? throw new ArgumentNullException(nameof(symlinkFactory));
                deploymentCleanupTasks = new List<Task>();
            }
            catch
            {
                // Async dispose is for if we have controllers running, not the case here
                var disposeTask = DisposeAsync();
                Debug.Assert(disposeTask.IsCompleted, "This should always be true during construction!");
                disposeTask.GetAwaiter().GetResult();
                throw;
            }
        }
References Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.deploymentCleanupTasks, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.DisposeAsync(), Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.GameIOManager, and Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.symlinkFactory.
Member Function Documentation
ApplyInitialDmb()
virtual async ValueTask Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.ApplyInitialDmb (CancellationToken cancellationToken) protected virtual
Set the ReattachInformation.InitialDmb for the BasicWatchdog.Server.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Reimplemented in Tgstation.Server.Host.Components.Watchdog.PosixWatchdog.
Definition at line 308 of file WindowsWatchdog.cs.
        {
            Server.ReattachInformation.InitialDmb = await DmbFactory.FromCompileJob(Server.CompileJob, cancellationToken);
        }
References Tgstation.Server.Host.Components.Deployment.DmbFactory.FromCompileJob().
Referenced by Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.SessionStartupPersist().
DisposeAndNullControllersImpl()
override async ValueTask Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.DisposeAndNullControllersImpl () protected virtual
Call IDisposable.Dispose and null the fields for all ISessionControllers.
Returns
A ValueTask representing the running operation.
Reimplemented from Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.
Definition at line 128 of file WindowsWatchdog.cs.
        {
            await base.DisposeAndNullControllersImpl();
            // If we reach this point, we can guarantee PrepServerForLaunch will be called before starting again.
            ActiveSwappable = null;
            pendingSwappable?.Dispose();
            pendingSwappable = null;
            await DrainDeploymentCleanupTasks(true);
        }
References Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.ActiveSwappable, Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.Dispose(), Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.DrainDeploymentCleanupTasks(), and Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.pendingSwappable.
DrainDeploymentCleanupTasks()
Task Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.DrainDeploymentCleanupTasks (bool blocking) private
Asynchronously drain deploymentCleanupTasks.
Parameters
blocking If true, all Tasks will be awaited. Otherwise, only Tasks with Task.IsCompleted set will be awaited.
Returns
A Task representing the running operation.
Definition at line 380 of file WindowsWatchdog.cs.
        {
            Logger.LogTrace("DrainDeploymentCleanupTasks...");
            var localDeploymentCleanupGate = Interlocked.Exchange(ref deploymentCleanupGate, null);
            localDeploymentCleanupGate?.TrySetResult();
            List<Task> localDeploymentCleanupTasks;
            lock (deploymentCleanupTasks)
            {
                var totalActiveTasks = deploymentCleanupTasks.Count;
                localDeploymentCleanupTasks = new List<Task>(totalActiveTasks);
                for (var i = totalActiveTasks - 1; i >= 0; --i)
                {
                    var currentTask = deploymentCleanupTasks[i];
                    if (!blocking && !currentTask.IsCompleted)
                        continue;
                    localDeploymentCleanupTasks.Add(currentTask);
                    deploymentCleanupTasks.RemoveAt(i);
                }
            }
            return Task.WhenAll(localDeploymentCleanupTasks);
        }
References Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.deploymentCleanupGate, Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.deploymentCleanupTasks, and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Logger.
Referenced by Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.DisposeAndNullControllersImpl(), Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.HandleMonitorWakeup(), and Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.HandleNormalReboot().
HandleMonitorWakeup()
override async ValueTask< MonitorAction > Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.HandleMonitorWakeup (MonitorActivationReason reason, CancellationToken cancellationToken) protected virtual
Handles the actions to take when the monitor has to "wake up".
Parameters
activationReason The MonitorActivationReason that caused the invocation. Will never be MonitorActivationReason.HealthCheck.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the MonitorAction to take.
Reimplemented from Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.
Definition at line 321 of file WindowsWatchdog.cs.
        {
            var result = await base.HandleMonitorWakeup(reason, cancellationToken);
            if (reason == MonitorActivationReason.ActiveServerStartup)
                await DrainDeploymentCleanupTasks(false);
            return result;
        }
References Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.DrainDeploymentCleanupTasks().
HandleNewDmbAvailable()
override async ValueTask Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.HandleNewDmbAvailable (CancellationToken cancellationToken) protected virtual
Handler for MonitorActivationReason.NewDmbAvailable.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Reimplemented from Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.
Definition at line 222 of file WindowsWatchdog.cs.
        {
            IDmbProvider compileJobProvider = DmbFactory.LockNextDmb(1);
            bool canSeamlesslySwap = true;
            if (compileJobProvider.CompileJob.ByondVersion != ActiveCompileJob.ByondVersion)
            {
                // have to do a graceful restart
                Logger.LogDebug(
                    "Not swapping to new compile job {0} as it uses a different BYOND version ({1}) than what is currently active {2}. Queueing graceful restart instead...",
                    compileJobProvider.CompileJob.Id,
                    compileJobProvider.CompileJob.ByondVersion,
                    ActiveCompileJob.ByondVersion);
                canSeamlesslySwap = false;
            }
            if (compileJobProvider.CompileJob.DmeName != ActiveCompileJob.DmeName)
            {
                Logger.LogDebug(
                    "Not swapping to new compile job {0} as it uses a different .dmb name ({1}) than what is currently active {2}. Queueing graceful restart instead...",
                    compileJobProvider.CompileJob.Id,
                    compileJobProvider.CompileJob.DmeName,
                    ActiveCompileJob.DmeName);
                canSeamlesslySwap = false;
            }
            if (!canSeamlesslySwap)
            {
                compileJobProvider.Dispose();
                await base.HandleNewDmbAvailable(cancellationToken);
                return;
            }
            SwappableDmbProvider windowsProvider = null;
            try
            {
                windowsProvider = new SwappableDmbProvider(compileJobProvider, GameIOManager, symlinkFactory);
                if (ActiveCompileJob.DMApiVersion == null)
                {
                    Logger.LogWarning("Active compile job has no DMAPI! Commencing immediate .dmb swap. Note this behavior is known to be buggy in some DM code contexts. See https://github.com/tgstation/tgstation-server/issues/1550");
                    await PerformDmbSwap(windowsProvider, cancellationToken);
                }
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, "Exception while swapping");
                IDmbProvider providerToDispose = windowsProvider ?? compileJobProvider;
                providerToDispose.Dispose();
                throw;
            }
            pendingSwappable?.Dispose();
            pendingSwappable = windowsProvider;
        }
References Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ActiveCompileJob, Tgstation.Server.Host.Components.Deployment.IDmbProvider.CompileJob, Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.Dispose(), Tgstation.Server.Api.Models.Internal.CompileJob.DMApiVersion, Tgstation.Server.Api.Models.Internal.CompileJob.DmeName, Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.GameIOManager, Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Host.Components.Deployment.DmbFactory.LockNextDmb(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Logger, Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.pendingSwappable, Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.PerformDmbSwap(), and Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.symlinkFactory.
HandleNormalReboot()
override async ValueTask< MonitorAction > Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.HandleNormalReboot (CancellationToken cancellationToken) protected virtual
Handler for MonitorActivationReason.ActiveServerRebooted when the RebootState is RebootState.Normal.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the MonitorAction to take.
Reimplemented from Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.
Definition at line 141 of file WindowsWatchdog.cs.
        {
            if (pendingSwappable != null)
            {
                var updateTask = BeforeApplyDmb(pendingSwappable.CompileJob, cancellationToken);
                if (!pendingSwappable.Swapped)
                {
                    // IMPORTANT: THE SESSIONCONTROLLER SHOULD STILL BE PROCESSING THE BRIDGE REQUEST SO WE KNOW DD IS SLEEPING
                    // OTHERWISE, IT COULD RETURN TO /world/Reboot() TOO EARLY AND LOAD THE WRONG .DMB
                    if (!Server.ProcessingRebootBridgeRequest)
                    {
                        // integration test logging will catch this
                        Logger.LogError(
                            "The reboot bridge request completed before the watchdog could suspend the server! This can lead to buggy DreamDaemon behaviour and should be reported! To ensure stability, we will need to hard reboot the server");
                        await updateTask;
                        return MonitorAction.Restart;
                    }
                    await PerformDmbSwap(pendingSwappable, cancellationToken);
                }
                var currentCompileJobId = Server.ReattachInformation.Dmb.CompileJob.Id;
                await DrainDeploymentCleanupTasks(false);
                IDisposable lingeringDeployment;
                var localDeploymentCleanupGate = new TaskCompletionSource();
                async Task CleanupLingeringDeployment()
                {
                    var lingeringDeploymentExpirySeconds = ActiveLaunchParameters.StartupTimeout.Value;
                    Logger.LogDebug(
                        "Holding old deployment {compileJobId} for up to {expiry} seconds...",
                        currentCompileJobId,
                        lingeringDeploymentExpirySeconds);
                    var timeout = AsyncDelayer.Delay(TimeSpan.FromSeconds(lingeringDeploymentExpirySeconds), cancellationToken);
                    var completedTask = await Task.WhenAny(
                        localDeploymentCleanupGate.Task,
                        timeout);
                    var timedOut = completedTask == timeout;
                    Logger.Log(
                        timedOut
                            ? LogLevel.Warning
                            : LogLevel.Trace,
                        "Releasing old deployment {compileJobId}{afterTimeout}",
                        currentCompileJobId,
                        timedOut
                            ? " due to timeout!"
                            : "...");
                    lingeringDeployment.Dispose();
                }
                var oldDeploymentCleanupGate = Interlocked.Exchange(ref deploymentCleanupGate, localDeploymentCleanupGate);
                oldDeploymentCleanupGate?.TrySetResult();
                Logger.LogTrace("Replacing activeSwappable with pendingSwappable...");
                lock (deploymentCleanupTasks)
                {
                    lingeringDeployment = Server.ReplaceDmbProvider(pendingSwappable);
                    deploymentCleanupTasks.Add(
                        CleanupLingeringDeployment());
                }
                ActiveSwappable = pendingSwappable;
                pendingSwappable = null;
                await SessionPersistor.Save(Server.ReattachInformation, cancellationToken);
                await updateTask;
            }
            else
                Logger.LogTrace("Nothing to do as pendingSwappable is null.");
            return MonitorAction.Continue;
        }
References Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ActiveLaunchParameters, Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.ActiveSwappable, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.BeforeApplyDmb(), Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.CompileJob, Tgstation.Server.Host.Utils.AsyncDelayer.Delay(), Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.deploymentCleanupGate, Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.deploymentCleanupTasks, Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.DrainDeploymentCleanupTasks(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Logger, Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.pendingSwappable, Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.PerformDmbSwap(), Tgstation.Server.Host.Components.Session.SessionPersistor.Save(), Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.StartupTimeout, and Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.Swapped.
InitialLink()
ValueTask Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.InitialLink (CancellationToken cancellationToken) private
Create the initial link to the live game directory using ActiveSwappable.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Definition at line 335 of file WindowsWatchdog.cs.
        {
            Logger.LogTrace("Symlinking compile job...");
            return ActiveSwappable.MakeActive(cancellationToken);
        }
References Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.ActiveSwappable, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Logger, and Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.MakeActive().
Referenced by Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.PrepServerForLaunch().
PerformDmbSwap()
async ValueTask Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.PerformDmbSwap (SwappableDmbProvider newProvider, CancellationToken cancellationToken) private
Suspends the BasicWatchdog.Server and calls SwappableDmbProvider.MakeActive(CancellationToken) on a newProvider .
Parameters
newProvider The SwappableDmbProvider to activate.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Definition at line 347 of file WindowsWatchdog.cs.
        {
            Logger.LogDebug("Swapping to compile job {id}...", newProvider.CompileJob.Id);
            var suspended = false;
            var server = Server;
            try
            {
                server.Suspend();
                suspended = true;
            }
            catch (Exception ex)
            {
                Logger.LogWarning(ex, "Exception while suspending server!");
            }
            try
            {
                await newProvider.MakeActive(cancellationToken);
            }
            finally
            {
                // Let this throw hard if it fails
                if (suspended)
                    server.Resume();
            }
        }
References Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.CompileJob, Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Logger, Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.MakeActive(), Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.Server, and Tgstation.Server.Host.System.IProcessBase.Suspend().
Referenced by Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.HandleNewDmbAvailable(), and Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.HandleNormalReboot().
PrepServerForLaunch()
sealed override async ValueTask< IDmbProvider > Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.PrepServerForLaunch (IDmbProvider dmbToUse, CancellationToken cancellationToken) protected virtual
Prepare the server to launch a new instance with the WatchdogBase.ActiveLaunchParameters and a given dmbToUse .
Parameters
dmbToUse The IDmbProvider to be launched. Will not be disposed by this function.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the modified IDmbProvider to be used.
Reimplemented from Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.
Definition at line 278 of file WindowsWatchdog.cs.
        {
            if (ActiveSwappable != null)
                throw new InvalidOperationException("Expected activeSwappable to be null!");
            if (pendingSwappable != null)
                throw new InvalidOperationException("Expected pendingSwappable to be null!");
            Logger.LogTrace("Prep for server launch");
            ActiveSwappable = new SwappableDmbProvider(dmbToUse, GameIOManager, symlinkFactory);
            try
            {
                await InitialLink(cancellationToken);
            }
            catch (Exception ex)
            {
                // We won't worry about disposing activeSwappable here as we can't dispose dmbToUse here.
                Logger.LogTrace(ex, "Initial link error, nulling ActiveSwappable");
                ActiveSwappable = null;
                throw;
            }
            return ActiveSwappable;
        }
References Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.ActiveSwappable, Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.GameIOManager, Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.InitialLink(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Logger, Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.pendingSwappable, and Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.symlinkFactory.
SessionStartupPersist()
override async ValueTask Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.SessionStartupPersist (CancellationToken cancellationToken) protected virtual
Called to save the current Server into the WatchdogBase.SessionPersistor when initially launched.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Reimplemented from Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.
Definition at line 314 of file WindowsWatchdog.cs.
        {
            await ApplyInitialDmb(cancellationToken);
            await base.SessionStartupPersist(cancellationToken);
        }
References Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.ApplyInitialDmb().
Member Data Documentation
deploymentCleanupGate
volatile TaskCompletionSource Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.deploymentCleanupGate private
The TaskCompletionSource representing the cleanup of an unused IDmbProvider.
Definition at line 55 of file WindowsWatchdog.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.DrainDeploymentCleanupTasks(), and Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.HandleNormalReboot().
deploymentCleanupTasks
readonly List<Task> Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.deploymentCleanupTasks private
List<T> of Tasks that are waiting to clean up old deployments.
Definition at line 45 of file WindowsWatchdog.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.DrainDeploymentCleanupTasks(), Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.HandleNormalReboot(), and Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.WindowsWatchdog().
pendingSwappable
SwappableDmbProvider Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.pendingSwappable private
The active SwappableDmbProvider for WatchdogBase.ActiveLaunchParameters.
Definition at line 50 of file WindowsWatchdog.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.DisposeAndNullControllersImpl(), Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.HandleNewDmbAvailable(), Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.HandleNormalReboot(), and Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.PrepServerForLaunch().
symlinkFactory
readonly ISymlinkFactory Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.symlinkFactory private
The ISymlinkFactory for the WindowsWatchdog.
Definition at line 40 of file WindowsWatchdog.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.HandleNewDmbAvailable(), Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.PrepServerForLaunch(), and Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.WindowsWatchdog().
Property Documentation
ActiveSwappable
SwappableDmbProvider Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.ActiveSwappable get private set protected
The SwappableDmbProvider for WatchdogBase.LastLaunchParameters.
Definition at line 30 of file WindowsWatchdog.cs.
{ get; private set; }
Referenced by Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.DisposeAndNullControllersImpl(), Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.HandleNormalReboot(), Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.InitialLink(), and Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.PrepServerForLaunch().
GameIOManager
IIOManager Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.GameIOManager get protected
The IIOManager for the WindowsWatchdog pointing to the Game directory.
Definition at line 35 of file WindowsWatchdog.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.HandleNewDmbAvailable(), Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.PrepServerForLaunch(), and Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.WindowsWatchdog().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Watchdog/WindowsWatchdog.cs