tgstation-server: Tgstation.Server.Host.Components.Deployment.SymlinkDmbProvider Class Reference
Tgstation.Server.Host.Components.Deployment.SymlinkDmbProvider Class Reference sealed
A IDmbProvider that uses symlinks.
Public Member Functions
SymlinkDmbProvider (IDmbProvider baseProvider, IIOManager ioManager, IFilesystemLinkFactory linkFactory)
Initializes a new instance of the SymlinkDmbProvider class.
override Task FinishActivationPreparation (CancellationToken cancellationToken)
Public Member Functions inherited from Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider
SwappableDmbProvider (IDmbProvider baseProvider, IIOManager ioManager, IFilesystemLinkFactory symlinkFactory)
Initializes a new instance of the SwappableDmbProvider class.
virtual ValueTask DisposeAsync ()
void KeepAlive ()
Disposing the IDmbProvider won't cause a cleanup of the working directory.
ValueTask MakeActive (CancellationToken cancellationToken)
Make the SwappableDmbProvider active by replacing the live link with our CompileJob.
Task FinishActivationPreparation (CancellationToken cancellationToken)
Should be awaited. before calling MakeActive(CancellationToken) to ensure the SwappableDmbProvider is ready to instantly swap. Can be called multiple times.
Protected Member Functions
override async ValueTask DoSwap (CancellationToken cancellationToken)
Protected Member Functions inherited from Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider
ValueTask DoSwap (CancellationToken cancellationToken)
Perform the swapping action.
Additional Inherited Members
Static Public Attributes inherited from Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider
const string LiveGameDirectory = "Live"
The directory where the BaseProvider is symlinked to.
Properties inherited from Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider
string DmbName [get]
The file name of the .dmb.
string Directory [get]
The primary game directory.
Models.CompileJob CompileJob [get]
The CompileJob of the .dmb.
EngineVersion EngineVersion [get]
The Api.Models.EngineVersion used to build the .dmb.
bool Swapped [get]
If MakeActive(CancellationToken) has been run.
IDmbProvider BaseProvider [get]
The IDmbProvider we are swapping for.
IIOManager IOManager [get]
The IIOManager to use.
IFilesystemLinkFactory LinkFactory [get]
The IFilesystemLinkFactory to use.
Properties inherited from Tgstation.Server.Host.Components.Deployment.IDmbProvider
Detailed Description
A IDmbProvider that uses symlinks.
Definition at line 11 of file SymlinkDmbProvider.cs.
Constructor & Destructor Documentation
SymlinkDmbProvider()
Tgstation.Server.Host.Components.Deployment.SymlinkDmbProvider.SymlinkDmbProvider (IDmbProvider baseProvider, IIOManager ioManager, IFilesystemLinkFactory linkFactory)
Initializes a new instance of the SymlinkDmbProvider class.
Parameters
baseProvider The IDmbProvider for the SwappableDmbProvider.
ioManager The IIOManager for the SwappableDmbProvider.
linkFactory The IFilesystemLinkFactory for the SwappableDmbProvider.
Definition at line 19 of file SymlinkDmbProvider.cs.
            : base(baseProvider, ioManager, linkFactory)
        {
        }
Member Function Documentation
DoSwap()
override async ValueTask Tgstation.Server.Host.Components.Deployment.SymlinkDmbProvider.DoSwap (CancellationToken cancellationToken) protected
Definition at line 31 of file SymlinkDmbProvider.cs.
        {
            if (LinkFactory.SymlinkedDirectoriesAreDeletedAsFiles)
                await IOManager.DeleteFile(LiveGameDirectory, cancellationToken);
            else
                await IOManager.DeleteDirectory(LiveGameDirectory, cancellationToken);
            await LinkFactory.CreateSymbolicLink(
                IOManager.ResolvePath(BaseProvider.Directory),
                IOManager.ResolvePath(LiveGameDirectory),
                cancellationToken);
        }
References Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.BaseProvider, Tgstation.Server.Host.IO.IFilesystemLinkFactory.CreateSymbolicLink(), Tgstation.Server.Host.IO.IIOManager.DeleteDirectory(), Tgstation.Server.Host.IO.IIOManager.DeleteFile(), Tgstation.Server.Host.Components.Deployment.IDmbProvider.Directory, Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.IOManager, Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.LinkFactory, Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.LiveGameDirectory, Tgstation.Server.Host.IO.IIOManager.ResolvePath(), and Tgstation.Server.Host.IO.IFilesystemLinkFactory.SymlinkedDirectoriesAreDeletedAsFiles.
FinishActivationPreparation()
override Task Tgstation.Server.Host.Components.Deployment.SymlinkDmbProvider.FinishActivationPreparation (CancellationToken cancellationToken)
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Deployment/SymlinkDmbProvider.cs