tgstation-server: Tgstation.Server.Host.Components.Deployment.DreamMaker Class Reference
Tgstation.Server.Host.Components.Deployment.DreamMaker Class Reference sealed
Public Member Functions
DreamMaker (IEngineManager engineManager, IIOManager ioManager, StaticFiles.IConfiguration configuration, IEventConsumer eventConsumer, IChatManager chatManager, IProcessExecutor processExecutor, ICompileJobSink compileJobConsumer, IRepositoryManager repositoryManager, IRemoteDeploymentManagerFactory remoteDeploymentManagerFactory, IAsyncDelayer asyncDelayer, IMetricFactory metricFactory, IOptionsMonitor< SessionConfiguration > sessionConfigurationOptions, ILogger< DreamMaker > logger, Api.Models.Instance metadata)
Initializes a new instance of the DreamMaker class.
async ValueTask DeploymentProcess (Models.Job job, IDatabaseContextFactory databaseContextFactory, JobProgressReporter progressReporter, CancellationToken cancellationToken)
Create and a compile job and insert it into the database. Meant to be called by a IJobManager.
Parameters
job The running Job.
databaseContextFactory The IDatabaseContextFactory for the operation.
progressReporter The JobProgressReporter to report compilation progress.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
void SetSessionControllerFactory (ISessionControllerFactory sessionControllerFactory)
Set the sessionControllerFactory for the DreamMaker. Must be called exactly once after construction before use.
Private Member Functions
async ValueTask< TimeSpan?> CalculateExpectedDeploymentTime (IDatabaseContext databaseContext, CancellationToken cancellationToken)
Calculate the average length of a deployment using a given databaseContext .
async ValueTask< Models.CompileJob > Compile (Models.Job job, Models.CompileJob? oldCompileJob, Models.RevisionInformation revisionInformation, Api.Models.Internal.DreamMakerSettings dreamMakerSettings, DreamDaemonLaunchParameters launchParameters, IRepository repository, IRemoteDeploymentManager remoteDeploymentManager, JobProgressReporter progressReporter, TimeSpan? estimatedDuration, bool localCommitExistsOnRemote, CancellationToken cancellationToken)
Run the compile implementation.
async ValueTask RunCompileJob (JobProgressReporter progressReporter, Models.CompileJob job, Api.Models.Internal.DreamMakerSettings dreamMakerSettings, DreamDaemonLaunchParameters launchParameters, IEngineExecutableLock engineLock, IRepository repository, IRemoteDeploymentManager remoteDeploymentManager, CancellationToken cancellationToken)
Executes and populate a given job .
async ValueTask ProgressTask (JobProgressReporter progressReporter, TimeSpan? estimatedDuration, CancellationToken cancellationToken)
Gradually triggers a given progressReporter over a given estimatedDuration .
async ValueTask VerifyApi (uint timeout, DreamDaemonSecurity securityLevel, Models.CompileJob job, JobProgressReporter progressReporter, IEngineExecutableLock engineLock, ushort portToUse, DMApiValidationMode validationMode, bool logOutput, CancellationToken cancellationToken)
Run a quick DD instance to test the DMAPI is installed on the target code.
async ValueTask< bool > RunDreamMaker (IEngineExecutableLock engineLock, Models.CompileJob job, string? additionalCompilerArguments, CancellationToken cancellationToken)
Compiles a .dme with DreamMaker.
async ValueTask ModifyDme (Models.CompileJob job, CancellationToken cancellationToken)
Adds server side includes to the .dme being compiled.
ValueTask CleanupFailedCompile (Models.CompileJob job, IRemoteDeploymentManager remoteDeploymentManager, Exception exception)
Cleans up a failed compile job .
Static Private Member Functions
static string FormatExceptionForUsers (Exception exception)
Format a given Exception for display to users.
Private Attributes
readonly IEngineManager engineManager
The IEngineManager for DreamMaker.
readonly IIOManager ioManager
The IIOManager for DreamMaker.
readonly StaticFiles.IConfiguration configuration
The StaticFiles.IConfiguration for DreamMaker.
readonly IEventConsumer eventConsumer
The IEventConsumer for DreamMaker.
readonly IChatManager chatManager
The IChatManager for DreamMaker.
readonly IProcessExecutor processExecutor
The IProcessExecutor for DreamMaker.
readonly IRepositoryManager repositoryManager
The IRepositoryManager for DreamMaker.
readonly ICompileJobSink compileJobConsumer
The ICompileJobSink for DreamMaker.
readonly IRemoteDeploymentManagerFactory remoteDeploymentManagerFactory
The IRemoteDeploymentManagerFactory for DreamMaker.
readonly IAsyncDelayer asyncDelayer
The IAsyncDelayer for DreamMaker.
readonly IOptionsMonitor< SessionConfiguration > sessionConfigurationOptions
The IOptionsMonitor<TOptions> of SessionConfiguration for DreamMaker.
readonly ILogger< DreamMaker > logger
The ILogger for DreamMaker.
readonly Api.Models.Instance metadata
The Instance DreamMaker belongs to.
readonly Counter attemptedDeployments
The number of attempted deployments.
readonly Counter successfulDeployments
The number of successful deployments.
readonly Counter failedDeployments
The number of failed deployments.
readonly object deploymentLock
lock object for deploying.
ISessionControllerFactory? sessionControllerFactory
The ISessionControllerFactory for DreamMaker.
Func< string?, string, Action< bool > >? currentChatCallback
The active callback from IChatManager.QueueDeploymentMessage.
string? currentDreamMakerOutput
Cached for currentChatCallback.
bool deploying
If a compile job is running.
Static Private Attributes
const string DmeExtension = "dme"
Extension for .dmes.
Detailed Description
Definition at line 35 of file DreamMaker.cs.
Constructor & Destructor Documentation
DreamMaker()
Tgstation.Server.Host.Components.Deployment.DreamMaker.DreamMaker (IEngineManager engineManager, IIOManager ioManager, StaticFiles::IConfiguration configuration, IEventConsumer eventConsumer, IChatManager chatManager, IProcessExecutor processExecutor, ICompileJobSink compileJobConsumer, IRepositoryManager repositoryManager, IRemoteDeploymentManagerFactory remoteDeploymentManagerFactory, IAsyncDelayer asyncDelayer, IMetricFactory metricFactory, IOptionsMonitor< SessionConfiguration > sessionConfigurationOptions, ILogger< DreamMaker > logger, Api::Models::Instance metadata)
Initializes a new instance of the DreamMaker class.
Parameters
engineManager The value of engineManager.
ioManager The value of ioManager.
configuration The value of configuration.
eventConsumer The value of eventConsumer.
chatManager The value of chatManager.
processExecutor The value of processExecutor.
compileJobConsumer The value of compileJobConsumer.
repositoryManager The value of repositoryManager.
remoteDeploymentManagerFactory The value of remoteDeploymentManagerFactory.
asyncDelayer The value of asyncDelayer.
metricFactory The IMetricFactory to use.
sessionConfigurationOptions The value of sessionConfigurationOptions.
logger The value of logger.
metadata The value of metadata.
Definition at line 175 of file DreamMaker.cs.
        {
            this.engineManager = engineManager ?? throw new ArgumentNullException(nameof(engineManager));
            this.ioManager = ioManager ?? throw new ArgumentNullException(nameof(ioManager));
            this.configuration = configuration ?? throw new ArgumentNullException(nameof(configuration));
            this.eventConsumer = eventConsumer ?? throw new ArgumentNullException(nameof(eventConsumer));
            this.chatManager = chatManager ?? throw new ArgumentNullException(nameof(chatManager));
            this.processExecutor = processExecutor ?? throw new ArgumentNullException(nameof(processExecutor));
            this.compileJobConsumer = compileJobConsumer ?? throw new ArgumentNullException(nameof(compileJobConsumer));
            this.repositoryManager = repositoryManager ?? throw new ArgumentNullException(nameof(repositoryManager));
            this.remoteDeploymentManagerFactory = remoteDeploymentManagerFactory ?? throw new ArgumentNullException(nameof(remoteDeploymentManagerFactory));
            this.asyncDelayer = asyncDelayer ?? throw new ArgumentNullException(nameof(asyncDelayer));
            ArgumentNullException.ThrowIfNull(metricFactory);
            this.sessionConfigurationOptions = sessionConfigurationOptions ?? throw new ArgumentNullException(nameof(sessionConfigurationOptions));
            this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
            this.metadata = metadata ?? throw new ArgumentNullException(nameof(metadata));
            successfulDeployments = metricFactory.CreateCounter("tgs_successful_deployments", "The number of deployments that have completed successfully");
            failedDeployments = metricFactory.CreateCounter("tgs_failed_deployments", "The number of deployments that have failed");
            attemptedDeployments = metricFactory.CreateCounter("tgs_total_deployments", "The number of deployments that have been attempted");
            deploymentLock = new object();
        }
References Tgstation.Server.Host.Components.Deployment.DreamMaker.asyncDelayer, Tgstation.Server.Host.Components.Deployment.DreamMaker.attemptedDeployments, Tgstation.Server.Host.Components.Deployment.DreamMaker.chatManager, Tgstation.Server.Host.Components.Deployment.DreamMaker.compileJobConsumer, Tgstation.Server.Host.Components.Deployment.DreamMaker.configuration, Tgstation.Server.Host.Components.Deployment.DreamMaker.deploymentLock, Tgstation.Server.Host.Components.Deployment.DreamMaker.engineManager, Tgstation.Server.Host.Components.Deployment.DreamMaker.eventConsumer, Tgstation.Server.Host.Components.Deployment.DreamMaker.failedDeployments, Tgstation.Server.Host.Components.Deployment.DreamMaker.ioManager, Tgstation.Server.Host.Components.Deployment.DreamMaker.logger, Tgstation.Server.Host.Components.Deployment.DreamMaker.metadata, Tgstation.Server.Host.Components.Deployment.DreamMaker.processExecutor, Tgstation.Server.Host.Components.Deployment.DreamMaker.remoteDeploymentManagerFactory, Tgstation.Server.Host.Components.Deployment.DreamMaker.repositoryManager, Tgstation.Server.Host.Components.Deployment.DreamMaker.sessionConfigurationOptions, and Tgstation.Server.Host.Components.Deployment.DreamMaker.successfulDeployments.
Member Function Documentation
CalculateExpectedDeploymentTime()
async ValueTask< TimeSpan?> Tgstation.Server.Host.Components.Deployment.DreamMaker.CalculateExpectedDeploymentTime (IDatabaseContext databaseContext, CancellationToken cancellationToken) private
Calculate the average length of a deployment using a given databaseContext .
Parameters
databaseContext The IDatabaseContext to retrieve previous deployment Jobs from.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the average TimeSpan of the 10 previous deployments or null if there are none.
Definition at line 462 of file DreamMaker.cs.
        {
            var previousCompileJobs = await databaseContext
                .CompileJobs
                .Where(x => x.Job.Instance!.Id == metadata.Id)
                .OrderByDescending(x => x.Job.StoppedAt)
                .Take(10)
                .Select(x => new
                {
                    StoppedAt = x.Job.StoppedAt!.Value,
                    StartedAt = x.Job.StartedAt!.Value,
                })
                .ToListAsync(cancellationToken);
            TimeSpan? averageSpan = null;
            if (previousCompileJobs.Count != 0)
            {
                var totalSpan = TimeSpan.Zero;
                foreach (var previousCompileJob in previousCompileJobs)
                    totalSpan += previousCompileJob.StoppedAt - previousCompileJob.StartedAt;
                averageSpan = totalSpan / previousCompileJobs.Count;
            }
            return averageSpan;
        }
References Tgstation.Server.Host.Database.IDatabaseContext.CompileJobs, and Tgstation.Server.Host.Components.Deployment.DreamMaker.metadata.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.DeploymentProcess().
CleanupFailedCompile()
ValueTask Tgstation.Server.Host.Components.Deployment.DreamMaker.CleanupFailedCompile (Models::CompileJob job, IRemoteDeploymentManager remoteDeploymentManager, Exception exception) private
Cleans up a failed compile job .
Parameters
job The running CompileJob.
remoteDeploymentManager The IRemoteDeploymentManager associated with the job .
exception The Exception that was thrown.
Returns
A ValueTask representing the running operation.
Definition at line 1030 of file DreamMaker.cs.
        {
            async ValueTask CleanDir()
            {
                if (sessionConfigurationOptions.CurrentValue.DelayCleaningFailedDeployments)
                {
                    logger.LogDebug("Not cleaning up errored deployment directory {guid} due to config.", job.DirectoryName);
                    return;
                }
                logger.LogTrace("Cleaning compile directory...");
                var jobPath = job.DirectoryName!.Value.ToString();
                try
                {
                    // DCT: None available
                    await eventConsumer.HandleEvent(EventType.DeploymentCleanup, new List<string> { jobPath }, false, true, CancellationToken.None);
                    await ioManager.DeleteDirectory(jobPath, CancellationToken.None);
                }
                catch (Exception e)
                {
                    logger.LogWarning(e, "Error cleaning up compile directory {path}!", ioManager.ResolvePath(jobPath));
                }
            }
            var dirCleanTask = CleanDir();
            var failRemoteDeployTask = remoteDeploymentManager.FailDeployment(
                job,
                FormatExceptionForUsers(exception),
                CancellationToken.None); // DCT: None available
            return ValueTaskExtensions.WhenAll(
                dirCleanTask,
                failRemoteDeployTask);
        }
References Tgstation.Server.Host.Components.Deployment.Remote.IRemoteDeploymentManager.FailDeployment(), and Tgstation.Server.Common.Extensions.ValueTaskExtensions.WhenAll().
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.DeploymentProcess().
Compile()
async ValueTask< Models.CompileJob > Tgstation.Server.Host.Components.Deployment.DreamMaker.Compile (Models::Job job, Models::CompileJob? oldCompileJob, Models::RevisionInformation revisionInformation, Api::Models::Internal::DreamMakerSettings dreamMakerSettings, DreamDaemonLaunchParameters launchParameters, IRepository repository, IRemoteDeploymentManager remoteDeploymentManager, JobProgressReporter progressReporter, TimeSpan? estimatedDuration, bool localCommitExistsOnRemote, CancellationToken cancellationToken) private
Run the compile implementation.
Parameters
job The currently running Job.
oldCompileJob The optional CompileJob of the previous deployment.
revisionInformation The RevisionInformation.
dreamMakerSettings The Api.Models.Internal.DreamMakerSettings.
launchParameters The DreamDaemonLaunchParameters.
repository The IRepository.
remoteDeploymentManager The IRemoteDeploymentManager.
progressReporter The JobProgressReporter to report progress of the operation.
estimatedDuration The optional estimated TimeSpan of the compilation.
localCommitExistsOnRemote Whether or not the repository 's current commit exists on the remote repository.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the completed CompileJob.
Definition at line 503 of file DreamMaker.cs.
        {
            logger.LogTrace("Begin Compile");
            using var progressCts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
            progressReporter.StageName = "Reserving BYOND version";
            var progressTask = ProgressTask(progressReporter, estimatedDuration, progressCts.Token);
            try
            {
                using var engineLock = await engineManager.UseExecutables(null, null, cancellationToken);
                currentChatCallback = chatManager.QueueDeploymentMessage(
                    revisionInformation,
                    oldCompileJob?.RevisionInformation,
                    engineLock.Version,
                    DateTimeOffset.UtcNow + estimatedDuration,
                    repository.RemoteRepositoryOwner,
                    repository.RemoteRepositoryName,
                    localCommitExistsOnRemote);
                var compileJob = new Models.CompileJob(job, revisionInformation, engineLock.Version.ToString())
                {
                    DirectoryName = Guid.NewGuid(),
                    DmeName = dreamMakerSettings.ProjectName,
                    RepositoryOrigin = repository.Origin.ToString(),
                };
                progressReporter.StageName = "Creating remote deployment notification";
                await remoteDeploymentManager.StartDeployment(
                    repository,
                    compileJob,
                    cancellationToken);
                logger.LogTrace("Deployment will timeout at {timeoutTime}", DateTimeOffset.UtcNow + dreamMakerSettings.Timeout!.Value);
                using var timeoutTokenSource = new CancellationTokenSource(dreamMakerSettings.Timeout.Value);
                var timeoutToken = timeoutTokenSource.Token;
                using (timeoutToken.Register(() => logger.LogWarning("Deployment timed out!")))
                {
                    using var combinedTokenSource = CancellationTokenSource.CreateLinkedTokenSource(timeoutToken, cancellationToken);
                    try
                    {
                        await RunCompileJob(
                            progressReporter,
                            compileJob,
                            dreamMakerSettings,
                            launchParameters,
                            engineLock,
                            repository,
                            remoteDeploymentManager,
                            combinedTokenSource.Token);
                    }
                    catch (OperationCanceledException) when (timeoutToken.IsCancellationRequested)
                    {
                        throw new JobException(ErrorCode.DeploymentTimeout);
                    }
                }
                return compileJob;
            }
            catch (OperationCanceledException)
            {
                // DCT: Cancellation token is for job, delaying here is fine
                progressReporter.StageName = "Running CompileCancelled event";
                await eventConsumer.HandleEvent(EventType.CompileCancelled, Enumerable.Empty<string>(), false, true, CancellationToken.None);
                throw;
            }
            finally
            {
                progressCts.Cancel();
                await progressTask;
            }
        }
References Tgstation.Server.Host.Components.Deployment.DreamMaker.chatManager, Tgstation.Server.Host.Components.Deployment.DreamMaker.currentChatCallback, Tgstation.Server.Host.Components.Deployment.DreamMaker.engineManager, Tgstation.Server.Host.Components.Deployment.DreamMaker.eventConsumer, Tgstation.Server.Host.Components.Events.IEventConsumer.HandleEvent(), Tgstation.Server.Host.Components.Deployment.DreamMaker.logger, Tgstation.Server.Host.Components.Repository.IRepository.Origin, Tgstation.Server.Host.Components.Deployment.DreamMaker.ProgressTask(), Tgstation.Server.Host.Components.Chat.IChatManager.QueueDeploymentMessage(), Tgstation.Server.Api.Models.Internal.IGitRemoteInformation.RemoteRepositoryName, Tgstation.Server.Api.Models.Internal.IGitRemoteInformation.RemoteRepositoryOwner, Tgstation.Server.Host.Components.Deployment.DreamMaker.RunCompileJob(), Tgstation.Server.Host.Components.Deployment.Remote.IRemoteDeploymentManager.StartDeployment(), and Tgstation.Server.Host.Components.Engine.IEngineManager.UseExecutables().
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.DeploymentProcess().
DeploymentProcess()
async ValueTask Tgstation.Server.Host.Components.Deployment.DreamMaker.DeploymentProcess (Models::Job job, IDatabaseContextFactory databaseContextFactory, JobProgressReporter progressReporter, CancellationToken cancellationToken)
Create and a compile job and insert it into the database. Meant to be called by a IJobManager.
Parameters
job The running Job.
databaseContextFactory The IDatabaseContextFactory for the operation.
progressReporter The JobProgressReporter to report compilation progress.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Deployment.IDreamMaker.
Definition at line 215 of file DreamMaker.cs.
        {
            ArgumentNullException.ThrowIfNull(job);
            ArgumentNullException.ThrowIfNull(databaseContextFactory);
            ArgumentNullException.ThrowIfNull(progressReporter);
            lock (deploymentLock)
            {
                if (deploying)
                    throw new JobException(ErrorCode.DeploymentInProgress);
                deploying = true;
            }
            attemptedDeployments.Inc();
            currentChatCallback = null;
            currentDreamMakerOutput = null;
            Models.CompileJob? compileJob = null;
            bool success = false;
            try
            {
                string? repoOwner = null;
                string? repoName = null;
                TimeSpan? averageSpan = null;
                Models.RepositorySettings? repositorySettings = null;
                Models.DreamDaemonSettings? ddSettings = null;
                Models.DreamMakerSettings? dreamMakerSettings = null;
                IRepository? repo = null;
                IRemoteDeploymentManager? remoteDeploymentManager = null;
                Models.RevisionInformation? revInfo = null;
                await databaseContextFactory.UseContext(
                    async databaseContext =>
                    {
                        averageSpan = await CalculateExpectedDeploymentTime(databaseContext, cancellationToken);
                        ddSettings = await databaseContext
                            .DreamDaemonSettings
                            .Where(x => x.InstanceId == metadata.Id)
                            .Select(x => new Models.DreamDaemonSettings
{
                                StartupTimeout = x.StartupTimeout,
                                LogOutput = x.LogOutput,
                            })
                            .FirstOrDefaultAsync(cancellationToken);
                        if (ddSettings == default)
                            throw new JobException(ErrorCode.InstanceMissingDreamDaemonSettings);
                        dreamMakerSettings = await databaseContext
                            .DreamMakerSettings
                            .Where(x => x.InstanceId == metadata.Id)
                            .FirstAsync(cancellationToken);
                        if (dreamMakerSettings == default)
                            throw new JobException(ErrorCode.InstanceMissingDreamMakerSettings);
                        repositorySettings = await databaseContext
                            .RepositorySettings
                            .Where(x => x.InstanceId == metadata.Id)
                            .Select(x => new Models.RepositorySettings
{
                                AccessToken = x.AccessToken,
                                AccessUser = x.AccessUser,
                                ShowTestMergeCommitters = x.ShowTestMergeCommitters,
                                PushTestMergeCommits = x.PushTestMergeCommits,
                                PostTestMergeComment = x.PostTestMergeComment,
                            })
                            .FirstOrDefaultAsync(cancellationToken);
                        if (repositorySettings == default)
                            throw new JobException(ErrorCode.InstanceMissingRepositorySettings);
                        repo = await repositoryManager.LoadRepository(cancellationToken);
                        try
{
                            if (repo == null)
                                throw new JobException(ErrorCode.RepoMissing);
                            remoteDeploymentManager = remoteDeploymentManagerFactory
                                .CreateRemoteDeploymentManager(metadata, repo.RemoteGitProvider!.Value);
                            var repoSha = repo.Head;
                            repoOwner = repo.RemoteRepositoryOwner;
                            repoName = repo.RemoteRepositoryName;
                            revInfo = await databaseContext
                                .RevisionInformations
                                .Where(x => x.CommitSha == repoSha && x.InstanceId == metadata.Id)
                                .Include(x => x.ActiveTestMerges!)
                                    .ThenInclude(x => x.TestMerge!)
                                        .ThenInclude(x => x.MergedBy)
                                .FirstOrDefaultAsync(cancellationToken);
                            if (revInfo == null)
{
                                revInfo = new Models.RevisionInformation
{
                                    CommitSha = repoSha,
                                    Timestamp = await repo.TimestampCommit(repoSha, cancellationToken),
                                    OriginCommitSha = repoSha,
                                    Instance = new Models.Instance
{
                                        Id = metadata.Id,
                                    },
                                    ActiveTestMerges = new List<RevInfoTestMerge>(),
                                };
                                logger.LogInformation(Repository.Repository.OriginTrackingErrorTemplate, repoSha);
                                databaseContext.RevisionInformations.Add(revInfo);
                                databaseContext.Instances.Attach(revInfo.Instance);
                                await databaseContext.Save(cancellationToken);
                            }
                        }
                        catch
{
                            repo?.Dispose();
                            throw;
                        }
                    });
                Models.CompileJob? oldCompileJob;
                using (repo)
                {
                    var likelyPushedTestMergeCommit =
                        repositorySettings!.PushTestMergeCommits!.Value
                        && repositorySettings.AccessToken != null
                        && repositorySettings.AccessUser != null;
                    oldCompileJob = await compileJobConsumer.LatestCompileJob();
                    compileJob = await Compile(
                        job,
                        oldCompileJob,
                        revInfo!,
                        dreamMakerSettings!,
                        ddSettings!,
                        repo!,
                        remoteDeploymentManager!,
                        progressReporter,
                        averageSpan,
                        likelyPushedTestMergeCommit,
                        cancellationToken);
                }
                try
                {
                    await databaseContextFactory.UseContext(
                        async databaseContext =>
{
                            var fullJob = compileJob.Job;
                            compileJob.Job = new Models.Job(job.Require(x => x.Id));
                            var fullRevInfo = compileJob.RevisionInformation;
                            compileJob.RevisionInformation = new Models.RevisionInformation
{
                                Id = revInfo!.Id,
                            };
                            databaseContext.Jobs.Attach(compileJob.Job);
                            databaseContext.RevisionInformations.Attach(compileJob.RevisionInformation);
                            databaseContext.CompileJobs.Add(compileJob);
                            // The difficulty with compile jobs is they have a two part commit
                            await databaseContext.Save(cancellationToken);
                            logger.LogTrace("Created CompileJob {compileJobId}", compileJob.Id);
                            try
{
                                var chatNotificationAction = currentChatCallback!(null, compileJob.Output!);
                                await compileJobConsumer.LoadCompileJob(compileJob, chatNotificationAction, cancellationToken);
                                success = true;
                            }
                            catch
{
                                // So we need to un-commit the compile job if the above throws
                                databaseContext.CompileJobs.Remove(compileJob);
                                // DCT: Cancellation token is for job, operation must run regardless
                                await databaseContext.Save(CancellationToken.None);
                                throw;
                            }
                            compileJob.Job = fullJob;
                            compileJob.RevisionInformation = fullRevInfo;
                        });
                }
                catch (Exception ex)
                {
                    await CleanupFailedCompile(compileJob, remoteDeploymentManager!, ex);
                    throw;
                }
                var commentsTask = remoteDeploymentManager!.PostDeploymentComments(
                    compileJob,
                    oldCompileJob?.RevisionInformation,
                    repositorySettings,
                    repoOwner,
                    repoName,
                    cancellationToken);
                var eventTask = eventConsumer.HandleEvent(EventType.DeploymentComplete, Enumerable.Empty<string>(), false, false, cancellationToken);
                try
                {
                    await ValueTaskExtensions.WhenAll(commentsTask, eventTask);
                }
                catch (Exception ex)
                {
                    throw new JobException(ErrorCode.PostDeployFailure, ex);
                }
                finally
                {
                    currentChatCallback = null;
                }
            }
            catch (Exception ex)
            {
                currentChatCallback?.Invoke(
                    FormatExceptionForUsers(ex),
                    currentDreamMakerOutput!);
                throw;
            }
            finally
            {
                deploying = false;
                if (success)
                    successfulDeployments.Inc();
                else
                    failedDeployments.Inc();
            }
        }
References Tgstation.Server.Host.Components.Deployment.DreamMaker.attemptedDeployments, Tgstation.Server.Host.Components.Deployment.DreamMaker.CalculateExpectedDeploymentTime(), Tgstation.Server.Host.Components.Deployment.DreamMaker.CleanupFailedCompile(), Tgstation.Server.Host.Components.Deployment.DreamMaker.Compile(), Tgstation.Server.Host.Components.Deployment.DreamMaker.compileJobConsumer, Tgstation.Server.Host.Components.Deployment.Remote.IRemoteDeploymentManagerFactory.CreateRemoteDeploymentManager(), Tgstation.Server.Host.Components.Deployment.DreamMaker.currentChatCallback, Tgstation.Server.Host.Components.Deployment.DreamMaker.currentDreamMakerOutput, Tgstation.Server.Host.Components.Deployment.DreamMaker.deploying, Tgstation.Server.Host.Components.Deployment.DreamMaker.deploymentLock, Tgstation.Server.Host.Components.Deployment.DreamMaker.eventConsumer, Tgstation.Server.Host.Components.Deployment.DreamMaker.failedDeployments, Tgstation.Server.Host.Components.Deployment.DreamMaker.FormatExceptionForUsers(), Tgstation.Server.Host.Components.Events.IEventConsumer.HandleEvent(), Tgstation.Server.Host.Components.Repository.IRepository.Head, Tgstation.Server.Host.Components.Deployment.ILatestCompileJobProvider.LatestCompileJob(), Tgstation.Server.Host.Components.Deployment.ICompileJobSink.LoadCompileJob(), Tgstation.Server.Host.Components.Repository.IRepositoryManager.LoadRepository(), Tgstation.Server.Host.Components.Deployment.DreamMaker.logger, Tgstation.Server.Host.Components.Deployment.DreamMaker.metadata, Tgstation.Server.Host.Components.Deployment.Remote.IRemoteDeploymentManager.PostDeploymentComments(), Tgstation.Server.Host.Components.Deployment.DreamMaker.remoteDeploymentManagerFactory, Tgstation.Server.Api.Models.Internal.IGitRemoteInformation.RemoteGitProvider, Tgstation.Server.Api.Models.Internal.IGitRemoteInformation.RemoteRepositoryName, Tgstation.Server.Api.Models.Internal.IGitRemoteInformation.RemoteRepositoryOwner, Tgstation.Server.Host.Components.Repository.Repository.Repository(), Tgstation.Server.Host.Components.Deployment.DreamMaker.repositoryManager, Tgstation.Server.Host.Components.Deployment.DreamMaker.successfulDeployments, Tgstation.Server.Host.Components.Repository.IRepository.TimestampCommit(), Tgstation.Server.Host.Database.IDatabaseContextFactory.UseContext(), and Tgstation.Server.Common.Extensions.ValueTaskExtensions.WhenAll().
Referenced by Tgstation.Server.Host.Components.Instance.AutoUpdateAction().
FormatExceptionForUsers()
static string Tgstation.Server.Host.Components.Deployment.DreamMaker.FormatExceptionForUsers (Exception exception) static private
Format a given Exception for display to users.
Parameters
exception The Exception to format.
Returns
An error string for end users.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.DeploymentProcess().
ModifyDme()
async ValueTask Tgstation.Server.Host.Components.Deployment.DreamMaker.ModifyDme (Models::CompileJob job, CancellationToken cancellationToken) private
Adds server side includes to the .dme being compiled.
Parameters
job The CompileJob for the operation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Definition at line 965 of file DreamMaker.cs.
        {
            var dmeFileName = String.Join('.', job.DmeName, DmeExtension);
            var stringDirectoryName = job.DirectoryName!.Value.ToString();
            var dmePath = ioManager.ConcatPath(stringDirectoryName, dmeFileName);
            var dmeReadTask = ioManager.ReadAllBytes(dmePath, cancellationToken);
            var dmeModificationsTask = configuration.CopyDMFilesTo(
                dmeFileName,
                ioManager.ResolvePath(
                    ioManager.ConcatPath(
                        stringDirectoryName,
                        ioManager.GetDirectoryName(dmeFileName))),
                cancellationToken);
            var dmeBytes = await dmeReadTask;
            var dme = Encoding.UTF8.GetString(dmeBytes);
            var dmeModifications = await dmeModificationsTask;
            if (dmeModifications == null || dmeModifications.TotalDmeOverwrite)
            {
                if (dmeModifications != null)
                    logger.LogDebug(".dme replacement configured!");
                else
                    logger.LogTrace("No .dme modifications required.");
                return;
            }
            var dmeLines = new List<string>(dme.Split('\n', StringSplitOptions.None));
            for (var dmeLineIndex = 0; dmeLineIndex < dmeLines.Count; ++dmeLineIndex)
            {
                var line = dmeLines[dmeLineIndex];
                if (line.Contains("BEGIN_INCLUDE", StringComparison.Ordinal) && dmeModifications.HeadIncludeLine != null)
                {
                    var headIncludeLineNumber = dmeLineIndex + 1;
                    logger.LogDebug(
                        "Inserting HeadInclude.dm at line {lineNumber}: {includeLine}",
                        headIncludeLineNumber,
                        dmeModifications.HeadIncludeLine);
                    dmeLines.Insert(headIncludeLineNumber, dmeModifications.HeadIncludeLine);
                    ++dmeLineIndex;
                }
                else if (line.Contains("END_INCLUDE", StringComparison.Ordinal) && dmeModifications.TailIncludeLine != null)
                {
                    logger.LogDebug(
                        "Inserting TailInclude.dm at line {lineNumber}: {includeLine}",
                        dmeLineIndex,
                        dmeModifications.TailIncludeLine);
                    dmeLines.Insert(dmeLineIndex, dmeModifications.TailIncludeLine);
                    break;
                }
            }
            dmeBytes = Encoding.UTF8.GetBytes(String.Join('\n', dmeLines));
            await ioManager.WriteAllBytes(dmePath, dmeBytes, cancellationToken);
        }
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.RunCompileJob().
ProgressTask()
async ValueTask Tgstation.Server.Host.Components.Deployment.DreamMaker.ProgressTask (JobProgressReporter progressReporter, TimeSpan? estimatedDuration, CancellationToken cancellationToken) private
Gradually triggers a given progressReporter over a given estimatedDuration .
Parameters
progressReporter The JobProgressReporter to report progress of the operation.
estimatedDuration A TimeSpan representing the duration to give progress over if any.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Definition at line 762 of file DreamMaker.cs.
        {
            double? lastReport = estimatedDuration.HasValue ? 0 : null;
            progressReporter.ReportProgress(lastReport);
            var minimumSleepInterval = TimeSpan.FromMilliseconds(250);
            var sleepInterval = estimatedDuration.HasValue ? estimatedDuration.Value / 100 : minimumSleepInterval;
            if (estimatedDuration.HasValue)
            {
                logger.LogDebug("Compile is expected to take: {estimatedDuration}", estimatedDuration);
            }
            else
            {
                logger.LogTrace("No metric to estimate compile time.");
            }
            try
            {
                for (var iteration = 0; iteration < (estimatedDuration.HasValue ? 99 : Int32.MaxValue); ++iteration)
                {
                    if (estimatedDuration.HasValue)
                    {
                        var nextInterval = DateTimeOffset.UtcNow + sleepInterval;
                        do
{
                            var remainingSleepThisInterval = nextInterval - DateTimeOffset.UtcNow;
                            var nextSleepSpan = remainingSleepThisInterval < minimumSleepInterval ? minimumSleepInterval : remainingSleepThisInterval;
                            await asyncDelayer.Delay(nextSleepSpan, cancellationToken);
                            progressReporter.ReportProgress(lastReport);
                        }
                        while (DateTimeOffset.UtcNow < nextInterval);
                    }
                    else
                        await asyncDelayer.Delay(minimumSleepInterval, cancellationToken);
                    lastReport = estimatedDuration.HasValue ? sleepInterval * (iteration + 1) / estimatedDuration.Value : null;
                    progressReporter.ReportProgress(lastReport);
                }
            }
            catch (OperationCanceledException ex)
            {
                logger.LogTrace(ex, "ProgressTask aborted.");
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "ProgressTask crashed!");
            }
        }
References Tgstation.Server.Host.Jobs.JobProgressReporter.ReportProgress().
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.Compile().
RunCompileJob()
async ValueTask Tgstation.Server.Host.Components.Deployment.DreamMaker.RunCompileJob (JobProgressReporter progressReporter, Models::CompileJob job, Api::Models::Internal::DreamMakerSettings dreamMakerSettings, DreamDaemonLaunchParameters launchParameters, IEngineExecutableLock engineLock, IRepository repository, IRemoteDeploymentManager remoteDeploymentManager, CancellationToken cancellationToken) private
Executes and populate a given job .
Parameters
progressReporter The JobProgressReporter for the operation.
job The CompileJob to run and populate.
dreamMakerSettings The Api.Models.Internal.DreamMakerSettings to use.
launchParameters The DreamDaemonLaunchParameters to use.
engineLock The IEngineExecutableLock to use.
repository The IRepository to use.
remoteDeploymentManager The IRemoteDeploymentManager to use.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Definition at line 599 of file DreamMaker.cs.
        {
            var outputDirectory = job.DirectoryName!.Value.ToString();
            logger.LogTrace("Compile output GUID: {dirGuid}", outputDirectory);
            try
            {
                // copy the repository
                logger.LogTrace("Copying repository to game directory");
                progressReporter.StageName = "Copying repository";
                var resolvedOutputDirectory = ioManager.ResolvePath(outputDirectory);
                var repoOrigin = repository.Origin;
                var repoReference = repository.Reference;
                using (repository)
                    await repository.CopyTo(resolvedOutputDirectory, cancellationToken);
                // repository closed now
                // run precompile scripts
                progressReporter.StageName = "Running PreCompile event";
                await eventConsumer.HandleEvent(
                    EventType.CompileStart,
                    new List<string>
                    {
                        resolvedOutputDirectory,
                        repoOrigin.ToString(),
                        engineLock.Version.ToString(),
                        repoReference,
                    },
                    false,
                    true,
                    cancellationToken);
                // determine the dme
                progressReporter.StageName = "Determining .dme";
                if (job.DmeName == null)
                {
                    logger.LogTrace("Searching for available .dmes");
                    var foundPaths = await ioManager.GetFilesWithExtension(resolvedOutputDirectory, DmeExtension, true, cancellationToken);
                    var foundPath = foundPaths.FirstOrDefault();
                    if (foundPath == default)
                        throw new JobException(ErrorCode.DeploymentNoDme);
                    job.DmeName = foundPath.Substring(
                        resolvedOutputDirectory.Length + 1,
                        foundPath.Length - resolvedOutputDirectory.Length - DmeExtension.Length - 2); // +1 for . in extension
                }
                else
                {
                    var targetDme = ioManager.ConcatPath(outputDirectory, String.Join('.', job.DmeName, DmeExtension));
                    if (!await ioManager.PathIsChildOf(outputDirectory, targetDme, cancellationToken))
                        throw new JobException(ErrorCode.DeploymentWrongDme);
                    var targetDmeExists = await ioManager.FileExists(targetDme, cancellationToken);
                    if (!targetDmeExists)
                        throw new JobException(ErrorCode.DeploymentMissingDme);
                }
                logger.LogDebug("Selected \"{dmeName}.dme\" for compilation!", job.DmeName);
                progressReporter.StageName = "Modifying .dme";
                await ModifyDme(job, cancellationToken);
                // run precompile scripts
                progressReporter.StageName = "Running PreDreamMaker event";
                await eventConsumer.HandleEvent(
                    EventType.PreDreamMaker,
                    new List<string>
                    {
                        resolvedOutputDirectory,
                        repoOrigin.ToString(),
                        engineLock.Version.ToString(),
                    },
                    false,
                    true,
                    cancellationToken);
                // run compiler
                progressReporter.StageName = "Running Compiler";
                var compileSuceeded = await RunDreamMaker(engineLock, job, dreamMakerSettings.CompilerAdditionalArguments, cancellationToken);
                // Session takes ownership of the lock and Disposes it so save this for later
                var engineVersion = engineLock.Version;
                // verify api
                try
                {
                    if (!compileSuceeded)
                        throw new JobException(
                            ErrorCode.DeploymentExitCode,
                            new JobException($"Compilation failed:{Environment.NewLine}{Environment.NewLine}{job.Output}"));
                    await VerifyApi(
                        launchParameters.StartupTimeout!.Value,
                        dreamMakerSettings.ApiValidationSecurityLevel!.Value,
                        job,
                        progressReporter,
                        engineLock,
                        dreamMakerSettings.ApiValidationPort!.Value,
                        dreamMakerSettings.DMApiValidationMode!.Value,
                        launchParameters.LogOutput!.Value,
                        cancellationToken);
                }
                catch (JobException)
                {
                    // DD never validated or compile failed
                    progressReporter.StageName = "Running CompileFailure event";
                    await eventConsumer.HandleEvent(
                        EventType.CompileFailure,
                        new List<string>
{
                            resolvedOutputDirectory,
                            compileSuceeded ? "1" : "0",
                            engineVersion.ToString(),
                        },
                        false,
                        true,
                        cancellationToken);
                    throw;
                }
                progressReporter.StageName = "Running CompileComplete event";
                await eventConsumer.HandleEvent(
                    EventType.CompileComplete,
                    new List<string>
                    {
                        resolvedOutputDirectory,
                        engineVersion.ToString(),
                    },
                    false,
                    true,
                    cancellationToken);
                logger.LogTrace("Applying static game file symlinks...");
                progressReporter.StageName = "Symlinking GameStaticFiles";
                // symlink in the static data
                await configuration.SymlinkStaticFilesTo(resolvedOutputDirectory, cancellationToken);
                logger.LogDebug("Compile complete!");
            }
            catch (Exception ex)
            {
                progressReporter.StageName = "Cleaning output directory";
                await CleanupFailedCompile(job, remoteDeploymentManager, ex);
                throw;
            }
        }
References Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.Components.Deployment.DreamMaker.configuration, Tgstation.Server.Host.Components.Repository.IRepository.CopyTo(), Tgstation.Server.Host.Components.Deployment.DreamMaker.DmeExtension, Tgstation.Server.Host.Components.Deployment.DreamMaker.eventConsumer, Tgstation.Server.Host.IO.IIOManager.FileExists(), Tgstation.Server.Host.IO.IIOManager.GetFilesWithExtension(), Tgstation.Server.Host.Components.Events.IEventConsumer.HandleEvent(), Tgstation.Server.Host.Components.Deployment.DreamMaker.ioManager, Tgstation.Server.Host.Components.Deployment.DreamMaker.logger, Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.LogOutput, Tgstation.Server.Host.Components.Deployment.DreamMaker.ModifyDme(), Tgstation.Server.Host.Components.Repository.IRepository.Origin, Tgstation.Server.Host.IO.IIOManager.PathIsChildOf(), Tgstation.Server.Host.Components.Repository.IRepository.Reference, Tgstation.Server.Host.IO.IIOManager.ResolvePath(), Tgstation.Server.Host.Components.Deployment.DreamMaker.RunDreamMaker(), Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.StartupTimeout, Tgstation.Server.Api.Models.EngineVersion.ToString(), Tgstation.Server.Host.Components.Deployment.DreamMaker.VerifyApi(), and Tgstation.Server.Host.Components.Engine.IEngineInstallation.Version.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.Compile().
RunDreamMaker()
async ValueTask< bool > Tgstation.Server.Host.Components.Deployment.DreamMaker.RunDreamMaker (IEngineExecutableLock engineLock, Models::CompileJob job, string? additionalCompilerArguments, CancellationToken cancellationToken) private
Compiles a .dme with DreamMaker.
Parameters
engineLock The IEngineExecutableLock to use.
job The CompileJob for the operation.
additionalCompilerArguments Additional arguments to be added to the compiler.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in true if compilation succeeded, false otherwise.
Definition at line 924 of file DreamMaker.cs.
        {
            var environment = await engineLock.LoadEnv(logger, true, cancellationToken);
            var arguments = engineLock.FormatCompilerArguments($"{job.DmeName}.{DmeExtension}", additionalCompilerArguments);
            await using var dm = await processExecutor.LaunchProcess(
                engineLock.CompilerExePath,
                ioManager.ResolvePath(
                    job.DirectoryName!.Value.ToString()),
                arguments,
                cancellationToken,
                environment,
                readStandardHandles: true,
                noShellExecute: true);
            if (sessionConfigurationOptions.CurrentValue.LowPriorityDeploymentProcesses)
                dm.AdjustPriority(false);
            int exitCode;
            using (cancellationToken.Register(() => dm.Terminate()))
                exitCode = (await dm.Lifetime).Value;
            cancellationToken.ThrowIfCancellationRequested();
            logger.LogDebug("DreamMaker exit code: {exitCode}", exitCode);
            job.Output = $"{await dm.GetCombinedOutput(cancellationToken)}{Environment.NewLine}{Environment.NewLine}Exit Code: {exitCode}";
            logger.LogDebug("DreamMaker output: {newLine}{output}", Environment.NewLine, job.Output);
            currentDreamMakerOutput = job.Output;
            return exitCode == 0;
        }
References Tgstation.Server.Host.Components.Engine.IEngineInstallation.CompilerExePath, Tgstation.Server.Host.Components.Engine.IEngineInstallation.FormatCompilerArguments(), and Tgstation.Server.Host.Components.Engine.IEngineInstallation.LoadEnv().
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.RunCompileJob().
SetSessionControllerFactory()
void Tgstation.Server.Host.Components.Deployment.DreamMaker.SetSessionControllerFactory (ISessionControllerFactory sessionControllerFactory)
Set the sessionControllerFactory for the DreamMaker. Must be called exactly once after construction before use.
Parameters
sessionControllerFactory The value of sessionControllerFactory.
Definition at line 449 of file DreamMaker.cs.
        {
            ArgumentNullException.ThrowIfNull(sessionControllerFactory);
            if (Interlocked.CompareExchange(ref this.sessionControllerFactory, sessionControllerFactory, null) != null)
                throw new InvalidOperationException($"{nameof(SetSessionControllerFactory)} called multiple times!");
        }
References Tgstation.Server.Host.Components.Deployment.DreamMaker.sessionControllerFactory.
VerifyApi()
async ValueTask Tgstation.Server.Host.Components.Deployment.DreamMaker.VerifyApi (uint timeout, DreamDaemonSecurity securityLevel, Models::CompileJob job, JobProgressReporter progressReporter, IEngineExecutableLock engineLock, ushort portToUse, DMApiValidationMode validationMode, bool logOutput, CancellationToken cancellationToken) private
Run a quick DD instance to test the DMAPI is installed on the target code.
Parameters
timeout The timeout in seconds for validation.
securityLevel The DreamDaemonSecurity level to use to validate the API.
job The CompileJob for the operation.
progressReporter The JobProgressReporter.
engineLock The current IEngineExecutableLock.
portToUse The port to use for API validation.
validationMode The DMApiValidationMode.
logOutput If output should be logged to the DreamDaemon Diagnostics folder.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Definition at line 826 of file DreamMaker.cs.
        {
            if (validationMode == DMApiValidationMode.Skipped)
            {
                logger.LogDebug("Skipping DMAPI validation");
                job.MinimumSecurityLevel = DreamDaemonSecurity.Ultrasafe;
                return;
            }
            progressReporter.StageName = "Validating DMAPI";
            var requireValidate = validationMode == DMApiValidationMode.Required;
            logger.LogTrace("Verifying {possiblyRequired}DMAPI...", requireValidate ? "required " : String.Empty);
            var launchParameters = new DreamDaemonLaunchParameters
            {
                AllowWebClient = false,
                Port = portToUse,
                OpenDreamTopicPort = 0,
                SecurityLevel = securityLevel,
                Visibility = DreamDaemonVisibility.Invisible,
                StartupTimeout = timeout,
                TopicRequestTimeout = 0, // not used
                HealthCheckSeconds = 0, // not used
                StartProfiler = false,
                LogOutput = logOutput,
                MapThreads = 1, // lowest possible amount
            };
            job.MinimumSecurityLevel = securityLevel; // needed for the TempDmbProvider
            if (sessionControllerFactory == null)
                throw new InvalidOperationException($"{nameof(SetSessionControllerFactory)} was not called!");
            ApiValidationStatus validationStatus;
            await using (var provider = new TemporaryDmbProvider(
                ioManager.ResolvePath(job.DirectoryName!.Value.ToString()),
                job,
                engineLock.Version))
            await using (var controller = await sessionControllerFactory.LaunchNew(provider, engineLock, launchParameters, true, cancellationToken))
            {
                var launchResult = await controller.LaunchResult.WaitAsync(cancellationToken);
                if (launchResult.StartupTime.HasValue)
                    await controller.Lifetime.WaitAsync(cancellationToken);
                if (!controller.Lifetime.IsCompleted)
                    await controller.DisposeAsync();
                validationStatus = controller.ApiValidationStatus;
                logger.LogTrace("API validation status: {validationStatus}", validationStatus);
                job.DMApiVersion = controller.DMApiVersion;
            }
            switch (validationStatus)
            {
                case ApiValidationStatus.RequiresUltrasafe:
                    job.MinimumSecurityLevel = DreamDaemonSecurity.Ultrasafe;
                    return;
                case ApiValidationStatus.RequiresSafe:
                    job.MinimumSecurityLevel = DreamDaemonSecurity.Safe;
                    return;
                case ApiValidationStatus.RequiresTrusted:
                    job.MinimumSecurityLevel = DreamDaemonSecurity.Trusted;
                    return;
                case ApiValidationStatus.NeverValidated:
                    if (requireValidate)
                        throw new JobException(ErrorCode.DeploymentNeverValidated);
                    job.MinimumSecurityLevel = DreamDaemonSecurity.Ultrasafe;
                    break;
                case ApiValidationStatus.BadValidationRequest:
                case ApiValidationStatus.Incompatible:
                    throw new JobException(ErrorCode.DeploymentInvalidValidation);
                case ApiValidationStatus.UnaskedValidationRequest:
                default:
                    throw new InvalidOperationException(
                        $"Session controller returned unexpected ApiValidationStatus: {validationStatus}");
            }
        }
References Tgstation.Server.Host.Components.Session.ISessionControllerFactory.LaunchNew(), and Tgstation.Server.Host.Components.Engine.IEngineInstallation.Version.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.RunCompileJob().
Member Data Documentation
asyncDelayer
readonly IAsyncDelayer Tgstation.Server.Host.Components.Deployment.DreamMaker.asyncDelayer private
The IAsyncDelayer for DreamMaker.
Definition at line 91 of file DreamMaker.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.DreamMaker().
attemptedDeployments
readonly Counter Tgstation.Server.Host.Components.Deployment.DreamMaker.attemptedDeployments private
The number of attempted deployments.
Definition at line 111 of file DreamMaker.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.DeploymentProcess(), and Tgstation.Server.Host.Components.Deployment.DreamMaker.DreamMaker().
chatManager
readonly IChatManager Tgstation.Server.Host.Components.Deployment.DreamMaker.chatManager private
The IChatManager for DreamMaker.
Definition at line 66 of file DreamMaker.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.Compile(), and Tgstation.Server.Host.Components.Deployment.DreamMaker.DreamMaker().
compileJobConsumer
readonly ICompileJobSink Tgstation.Server.Host.Components.Deployment.DreamMaker.compileJobConsumer private
The ICompileJobSink for DreamMaker.
Definition at line 81 of file DreamMaker.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.DeploymentProcess(), and Tgstation.Server.Host.Components.Deployment.DreamMaker.DreamMaker().
configuration
readonly StaticFiles.IConfiguration Tgstation.Server.Host.Components.Deployment.DreamMaker.configuration private
The StaticFiles.IConfiguration for DreamMaker.
Definition at line 56 of file DreamMaker.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.DreamMaker(), and Tgstation.Server.Host.Components.Deployment.DreamMaker.RunCompileJob().
currentChatCallback
Func<string?, string, Action<bool> >? Tgstation.Server.Host.Components.Deployment.DreamMaker.currentChatCallback private
The active callback from IChatManager.QueueDeploymentMessage.
Definition at line 136 of file DreamMaker.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.Compile(), and Tgstation.Server.Host.Components.Deployment.DreamMaker.DeploymentProcess().
currentDreamMakerOutput
string? Tgstation.Server.Host.Components.Deployment.DreamMaker.currentDreamMakerOutput private
Cached for currentChatCallback.
Definition at line 141 of file DreamMaker.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.DeploymentProcess().
deploying
bool Tgstation.Server.Host.Components.Deployment.DreamMaker.deploying private
If a compile job is running.
Definition at line 146 of file DreamMaker.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.DeploymentProcess().
deploymentLock
readonly object Tgstation.Server.Host.Components.Deployment.DreamMaker.deploymentLock private
lock object for deploying.
Definition at line 126 of file DreamMaker.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.DeploymentProcess(), and Tgstation.Server.Host.Components.Deployment.DreamMaker.DreamMaker().
DmeExtension
const string Tgstation.Server.Host.Components.Deployment.DreamMaker.DmeExtension = "dme" static private
Extension for .dmes.
Definition at line 41 of file DreamMaker.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.RunCompileJob().
engineManager
readonly IEngineManager Tgstation.Server.Host.Components.Deployment.DreamMaker.engineManager private
The IEngineManager for DreamMaker.
Definition at line 46 of file DreamMaker.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.Compile(), and Tgstation.Server.Host.Components.Deployment.DreamMaker.DreamMaker().
eventConsumer
readonly IEventConsumer Tgstation.Server.Host.Components.Deployment.DreamMaker.eventConsumer private
The IEventConsumer for DreamMaker.
Definition at line 61 of file DreamMaker.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.Compile(), Tgstation.Server.Host.Components.Deployment.DreamMaker.DeploymentProcess(), Tgstation.Server.Host.Components.Deployment.DreamMaker.DreamMaker(), and Tgstation.Server.Host.Components.Deployment.DreamMaker.RunCompileJob().
failedDeployments
readonly Counter Tgstation.Server.Host.Components.Deployment.DreamMaker.failedDeployments private
The number of failed deployments.
Definition at line 121 of file DreamMaker.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.DeploymentProcess(), and Tgstation.Server.Host.Components.Deployment.DreamMaker.DreamMaker().
ioManager
readonly IIOManager Tgstation.Server.Host.Components.Deployment.DreamMaker.ioManager private
The IIOManager for DreamMaker.
Definition at line 51 of file DreamMaker.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.DreamMaker(), and Tgstation.Server.Host.Components.Deployment.DreamMaker.RunCompileJob().
logger
readonly ILogger<DreamMaker> Tgstation.Server.Host.Components.Deployment.DreamMaker.logger private
The ILogger for DreamMaker.
Definition at line 101 of file DreamMaker.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.Compile(), Tgstation.Server.Host.Components.Deployment.DreamMaker.DeploymentProcess(), Tgstation.Server.Host.Components.Deployment.DreamMaker.DreamMaker(), and Tgstation.Server.Host.Components.Deployment.DreamMaker.RunCompileJob().
metadata
readonly Api.Models.Instance Tgstation.Server.Host.Components.Deployment.DreamMaker.metadata private
The Instance DreamMaker belongs to.
Definition at line 106 of file DreamMaker.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.CalculateExpectedDeploymentTime(), Tgstation.Server.Host.Components.Deployment.DreamMaker.DeploymentProcess(), and Tgstation.Server.Host.Components.Deployment.DreamMaker.DreamMaker().
processExecutor
readonly IProcessExecutor Tgstation.Server.Host.Components.Deployment.DreamMaker.processExecutor private
The IProcessExecutor for DreamMaker.
Definition at line 71 of file DreamMaker.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.DreamMaker().
remoteDeploymentManagerFactory
readonly IRemoteDeploymentManagerFactory Tgstation.Server.Host.Components.Deployment.DreamMaker.remoteDeploymentManagerFactory private
The IRemoteDeploymentManagerFactory for DreamMaker.
Definition at line 86 of file DreamMaker.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.DeploymentProcess(), and Tgstation.Server.Host.Components.Deployment.DreamMaker.DreamMaker().
repositoryManager
readonly IRepositoryManager Tgstation.Server.Host.Components.Deployment.DreamMaker.repositoryManager private
The IRepositoryManager for DreamMaker.
Definition at line 76 of file DreamMaker.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.DeploymentProcess(), and Tgstation.Server.Host.Components.Deployment.DreamMaker.DreamMaker().
sessionConfigurationOptions
readonly IOptionsMonitor<SessionConfiguration> Tgstation.Server.Host.Components.Deployment.DreamMaker.sessionConfigurationOptions private
The IOptionsMonitor<TOptions> of SessionConfiguration for DreamMaker.
Definition at line 96 of file DreamMaker.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.DreamMaker().
sessionControllerFactory
ISessionControllerFactory? Tgstation.Server.Host.Components.Deployment.DreamMaker.sessionControllerFactory private
The ISessionControllerFactory for DreamMaker.
Definition at line 131 of file DreamMaker.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.SetSessionControllerFactory().
successfulDeployments
readonly Counter Tgstation.Server.Host.Components.Deployment.DreamMaker.successfulDeployments private
The number of successful deployments.
Definition at line 116 of file DreamMaker.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.DeploymentProcess(), and Tgstation.Server.Host.Components.Deployment.DreamMaker.DreamMaker().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Deployment/DreamMaker.cs