tgstation-server: TGServerService.ProcessExtension Class Reference
TGServerService.ProcessExtension Class Reference
Helpers to Suspend(Process)ing and Resume(Process) a Process. Lightly massaged code from https://stackoverflow.com/a/13109774. Documentation linked from MSDN on 20/10/2017
Static Public Member Functions
static void Suspend (this Process process)
Suspends all threads for a running Process
static void Resume (this Process process)
Resumes all threads for a running Process
Private Types
enum ThreadAccess : int { ThreadAccess.SUSPEND_RESUME = (0x0002) }
https://msdn.microsoft.com/en-us/library/windows/desktop/ms686769(v=vs.85).aspx
Private Member Functions
static IntPtr OpenThread (ThreadAccess dwDesiredAccess, bool bInheritHandle, uint dwThreadId)
https://msdn.microsoft.com/en-us/library/windows/desktop/ms684335(v=vs.85).aspx
static bool CloseHandle (IntPtr hObject)
https://msdn.microsoft.com/en-us/library/windows/desktop/ms724211(v=vs.85).aspx
static uint SuspendThread (IntPtr hThread)
https://msdn.microsoft.com/en-us/library/windows/desktop/ms686345(v=vs.85).aspx
static int ResumeThread (IntPtr hThread)
https://msdn.microsoft.com/en-us/library/windows/desktop/ms685086(v=vs.85).aspx
Detailed Description
Helpers to Suspend(Process)ing and Resume(Process) a Process. Lightly massaged code from https://stackoverflow.com/a/13109774. Documentation linked from MSDN on 20/10/2017
Definition at line 10 of file ProcessExtension.cs.
Member Enumeration Documentation
enum TGServerService.ProcessExtension.ThreadAccess : int strong private
https://msdn.microsoft.com/en-us/library/windows/desktop/ms686769(v=vs.85).aspx
Enumerator
SUSPEND_RESUME
Definition at line 15 of file ProcessExtension.cs.
                           : int
         {
             SUSPEND_RESUME = (0x0002),
         }
Member Function Documentation
static bool TGServerService.ProcessExtension.CloseHandle (IntPtr hObject) private
https://msdn.microsoft.com/en-us/library/windows/desktop/ms724211(v=vs.85).aspx
Referenced by TGServerService.ProcessExtension.Resume(), and TGServerService.ProcessExtension.Suspend().
static IntPtr TGServerService.ProcessExtension.OpenThread (ThreadAccess dwDesiredAccess, bool bInheritHandle, uint dwThreadId) private
https://msdn.microsoft.com/en-us/library/windows/desktop/ms684335(v=vs.85).aspx
Referenced by TGServerService.ProcessExtension.Resume(), and TGServerService.ProcessExtension.Suspend().
static void TGServerService.ProcessExtension.Resume (this Process process) static
Resumes all threads for a running Process
Parameters
process The Process to suspend
Definition at line 60 of file ProcessExtension.cs.
References TGServerService.ProcessExtension.CloseHandle(), TGServerService.ProcessExtension.OpenThread(), and TGServerService.ProcessExtension.ResumeThread().
         {
             foreach (ProcessThread thread in process.Threads)
             {
                 var pOpenThread = OpenThread(ThreadAccess.SUSPEND_RESUME, false, (uint)thread.Id);
                 if (pOpenThread == IntPtr.Zero)
                     continue;
                 ResumeThread(pOpenThread);
                 CloseHandle(pOpenThread);
             }
         }
static int TGServerService.ProcessExtension.ResumeThread (IntPtr hThread) private
https://msdn.microsoft.com/en-us/library/windows/desktop/ms685086(v=vs.85).aspx
Referenced by TGServerService.ProcessExtension.Resume().
static void TGServerService.ProcessExtension.Suspend (this Process process) static
Suspends all threads for a running Process
Parameters
process The Process to suspend
Definition at line 44 of file ProcessExtension.cs.
References TGServerService.ProcessExtension.CloseHandle(), TGServerService.ProcessExtension.OpenThread(), and TGServerService.ProcessExtension.SuspendThread().
         {
             foreach (ProcessThread thread in process.Threads)
             {
                 var pOpenThread = OpenThread(ThreadAccess.SUSPEND_RESUME, false, (uint)thread.Id);
                 if (pOpenThread == IntPtr.Zero)
                     continue;
                 SuspendThread(pOpenThread);
                 CloseHandle(pOpenThread);
             }
         }
static uint TGServerService.ProcessExtension.SuspendThread (IntPtr hThread) private
https://msdn.microsoft.com/en-us/library/windows/desktop/ms686345(v=vs.85).aspx
Referenced by TGServerService.ProcessExtension.Suspend().
The documentation for this class was generated from the following file:
TGServerService/ProcessExtension.cs