tgstation-server: TGS.Interface.Server Class Reference
TGS.Interface.Server Class Reference
Public Member Functions
Server (Client _serverInterface)
Construct an Server
IInstance GetInstance (string name)
Gets the specified IInstance without connectivity checks
Public Attributes
Version Version => serverInterface.ServerVersion
ITGInstanceManager InstanceManager => UserIsAdministrator ? serverInterface.GetComponent<ITGInstanceManager>(null) : null
ITGSService Management => UserIsAdministrator ? serverInterface.GetComponent<ITGSService>(null) : null
Properties
IEnumerable< IInstance > Instances [get]
bool UserIsAdministrator [get]
If the connected user is an administrator of the IServer
Properties inherited from TGS.Interface.IServer
Version Version [get]
The System.Version of the IServer
IEnumerable< IInstance > Instances [get]
Get the IInstances the IServer contains that the current user can access and connect to
ITGInstanceManager InstanceManager [get]
The ITGInstanceManager component. Will be if the connected user is not an administrator of the IServer
ITGSService Management [get]
The ITGSService component. Will be if the connected user is not an administrator of the IServer
Private Attributes
readonly Client serverInterface
The backing Client
IList< InstanceMetadata > knownInstances
Result of a call to ITGLanding.ListInstances
bool isAdministrator
Backing field for UserIsAdministrator
Detailed Description
Definition at line 8 of file Server.cs.
Constructor & Destructor Documentation
TGS.Interface.Server.Server (Client _serverInterface)
Construct an Server
Parameters
_serverInterface The Client to use
Definition at line 85 of file Server.cs.
Referenced by TGS.Installer.UI.Main.AttemptMigrationOfNetSettings().
         {
             serverInterface = _serverInterface;
         }
Member Function Documentation
IInstance TGS.Interface.Server.GetInstance (string name)
Gets the specified IInstance without connectivity checks
Implements TGS.Interface.IServer.
Definition at line 91 of file Server.cs.
         {
             return new Instance(serverInterface, new InstanceMetadata { Name = name, Enabled = false });
         }
Member Data Documentation
ITGInstanceManager TGS.Interface.Server.InstanceManager => UserIsAdministrator ? serverInterface.GetComponent<ITGInstanceManager>(null) : null
Definition at line 36 of file Server.cs.
Referenced by TGS.CommandLine.ServiceCreateInstanceCommand.Run(), TGS.CommandLine.ServiceDetachInstanceCommand.Run(), TGS.CommandLine.ServiceImportInstanceCommand.Run(), TGS.CommandLine.ServiceEnableInstanceCommand.Run(), TGS.CommandLine.ServiceDisableInstanceCommand.Run(), and TGS.CommandLine.ServiceRenameInstanceCommand.Run().
bool TGS.Interface.Server.isAdministrator private
Backing field for UserIsAdministrator
Definition at line 79 of file Server.cs.
IList<InstanceMetadata> TGS.Interface.Server.knownInstances private
Result of a call to ITGLanding.ListInstances
Definition at line 74 of file Server.cs.
ITGSService TGS.Interface.Server.Management => UserIsAdministrator ? serverInterface.GetComponent<ITGSService>(null) : null
Definition at line 39 of file Server.cs.
Referenced by TGS.CommandLine.ServicePythonPathCommand.Run(), TGS.CommandLine.ServiceSetPythonPathCommand.Run(), TGS.CommandLine.ServiceRemoteAccessPortCommand.Run(), and TGS.CommandLine.ServiceSetRemoteAccessPortCommand.Run().
readonly Client TGS.Interface.Server.serverInterface private
The backing Client
Definition at line 69 of file Server.cs.
Version TGS.Interface.Server.Version => serverInterface.ServerVersion
Definition at line 11 of file Server.cs.
Property Documentation
IEnumerable<IInstance> TGS.Interface.Server.Instances get
Definition at line 14 of file Server.cs.
Referenced by TGS.CommandLine.ServiceListInstancesCommand.Run().
bool TGS.Interface.Server.UserIsAdministrator get private
If the connected user is an administrator of the IServer
Definition at line 45 of file Server.cs.
The documentation for this class was generated from the following file:
TGS.Interface/Server.cs