tgstation-server: TGInstallerWrapper.Main Class Reference
TGInstallerWrapper.Main Class Reference
Public Member Functions
Main ()
Construct an installer form
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Types
enum PKillType { PKillType.Killed, PKillType.Aborted, PKillType.NoneFound }
Private Member Functions
void SetupTempDir ()
void LoadInterfaceFromReflection ()
void CheckForExistingVersion ()
bool ConfirmDangerousUpgrade ()
bool TellServiceWereComingForThem ()
void Main_FormClosing (object sender, FormClosingEventArgs e)
PKillType PromptKillProcesses (string name)
async void DoInstall ()
MessageResult OnUIUpdate (InstallMessage messageType, string message, MessageButtons buttons, MessageIcon icon, MessageDefaultButton defaultButton)
void InstallButton_Click (object sender, EventArgs e)
void SelectPathButton_Click (object sender, EventArgs e)
void CancelButton_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
const string DefaultInstallDir = "TG Station Server"
const string InterfaceDLL = "TGServiceInterface.dll"
const string InterfaceNamespace = "TGServiceInterface"
const string InterfaceComponentsNamespace = InterfaceNamespace + ".Components"
const string InterfaceClass = InterfaceNamespace + ".Server"
const string InterfaceServiceInterface = InterfaceComponentsNamespace + ".ITGSService"
const string InterfaceClassVerifyConnection = "VerifyConnection"
const string InterfaceClassGetComponent = "GetComponent"
const string InterfaceServiceInterfaceVersion = "Version"
const string InterfaceServiceInterfacePrepareForUpdate = "PrepareForUpdate"
Assembly InterfaceAssembly
Type Server
Type ITGSService
MethodInfo VerifyConnection
MethodInfo GetComponentITGSService
MethodInfo Version
MethodInfo PrepareForUpdate
string tempDir
bool installing = false
bool cancelled = false
bool pathIsDefault = true
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.ProgressBar ProgressBar
System.Windows.Forms.CheckBox DeskShortcutsCheckbox
System.Windows.Forms.CheckBox StartShortcutsCheckbox
System.Windows.Forms.Label InstallingLabel
System.Windows.Forms.TextBox PathTextBox
System.Windows.Forms.Button SelectPathButton
System.Windows.Forms.Label label1
System.Windows.Forms.Label VersionLabel
System.Windows.Forms.Button InstallButton
System.Windows.Forms.CheckBox ShowLogCheckbox
System.Windows.Forms.Label TargetVersionLabel
System.Windows.Forms.Button InstallCancelButton
Detailed Description
Definition at line 13 of file Main.cs.
Member Enumeration Documentation
enum TGInstallerWrapper.Main.PKillType strong private
Enumerator
Killed
Aborted
NoneFound
Definition at line 133 of file Main.cs.
         {
             Killed,
             Aborted,
             NoneFound,
         }
Constructor & Destructor Documentation
TGInstallerWrapper.Main.Main ()
Construct an installer form
Definition at line 40 of file Main.cs.
References TGInstallerWrapper.Main.CheckForExistingVersion(), TGInstallerWrapper.Main.DefaultInstallDir, TGInstallerWrapper.Main.InitializeComponent(), TGInstallerWrapper.Main.LoadInterfaceFromReflection(), TGInstallerWrapper.Main.PathTextBox, and TGInstallerWrapper.Main.SetupTempDir().
         {
             InitializeComponent();
             SetupTempDir();
             LoadInterfaceFromReflection();
             CheckForExistingVersion();
             PathTextBox.Text = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86), DefaultInstallDir);
         }
Member Function Documentation
void TGInstallerWrapper.Main.CancelButton_Click (object sender, EventArgs e) private
Definition at line 284 of file Main.cs.
References TGInstallerWrapper.Main.InstallCancelButton.
Referenced by TGInstallerWrapper.Main.InitializeComponent().
         {
             cancelled = true;
             InstallCancelButton.Enabled = false;
         }
void TGInstallerWrapper.Main.CheckForExistingVersion () private
Definition at line 91 of file Main.cs.
References TGInstallerWrapper.Main.VersionLabel.
Referenced by TGInstallerWrapper.Main.Main().
{
             if (InterfaceAssembly == null)
                 return;
             var verifiedConnection = VerifyConnection.Invoke(null, null) == null;
             try
             {
                 VersionLabel.Text = (string)Version.Invoke(GetComponentITGSService.Invoke(null, null), null);
             }
             catch
             {
                 if (verifiedConnection)
                     VersionLabel.Text = "< v3.0.85.0 (Missing ITGService.Version())";
             }
         }
bool TGInstallerWrapper.Main.ConfirmDangerousUpgrade () private
Definition at line 106 of file Main.cs.
Referenced by TGInstallerWrapper.Main.TellServiceWereComingForThem().
         {
             return MessageBox.Show("Unable connect to service! Existing DreamDaemon instances will be terminated. Continue?", "Warning", MessageBoxButtons.YesNo) == DialogResult.Yes;
         }
override void TGInstallerWrapper.Main.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 18 of file Main.Designer.cs.
References TGInstallerWrapper.Main.components.
         {
             if (disposing && (components != null))
             {
                 components.Dispose();
             }
             base.Dispose(disposing);
         }
async void TGInstallerWrapper.Main.DoInstall () private
Definition at line 162 of file Main.cs.
References TGInstallerWrapper.Main.DeskShortcutsCheckbox, TGInstallerWrapper.Main.InstallButton, TGInstallerWrapper.Main.InstallCancelButton, TGInstallerWrapper.Main.OnUIUpdate(), TGInstallerWrapper.Main.PathTextBox, TGInstallerWrapper.Main.ProgressBar, TGInstallerWrapper.Main.PromptKillProcesses(), TGInstallerWrapper.Main.SelectPathButton, TGInstallerWrapper.Main.ShowLogCheckbox, TGInstallerWrapper.Main.StartShortcutsCheckbox, and TGInstallerWrapper.Main.TellServiceWereComingForThem().
Referenced by TGInstallerWrapper.Main.InstallButton_Click().
         {
             string logfile = null;
             try
             {
                 while (true)
                 {
                     var res = PromptKillProcesses("TGCommandLine");
                     if (res == PKillType.Aborted)
                         return;
                     else if (res == PKillType.Killed)
                         continue;
                     res = PromptKillProcesses("TGControlPanel");
                     if (res == PKillType.Aborted)
                         return;
                     else if (res == PKillType.Killed)
                         continue;
                     break;
                 }
                 if (!TellServiceWereComingForThem())
                     return;
                 var args = new List<string>();
                 if (!pathIsDefault)
                     args.Add(String.Format("INSTALLFOLDER=\"{0}\"", PathTextBox.Text));
                 if (StartShortcutsCheckbox.Checked)
                     args.Add("INSTALLSHORTCUTSTART=1");
                 if (DeskShortcutsCheckbox.Checked)
                     args.Add("INSTALLSHORTCUTDESK=1");
                 args.Add("REBOOT=R");
                 SelectPathButton.Enabled = false;
                 PathTextBox.Enabled = false;
                 DeskShortcutsCheckbox.Enabled = false;
                 StartShortcutsCheckbox.Enabled = false;
                 InstallButton.Enabled = false;
                 ShowLogCheckbox.Enabled = false;
                 InstallButton.Text = "Installing...";
                 var msipath = Path.Combine(tempDir, "TGServiceInstaller.msi");
                 File.WriteAllBytes(msipath, Properties.Resources.TGServiceInstaller);
                 File.WriteAllBytes(Path.Combine(tempDir, "cab1.cab"), Properties.Resources.cab1);
                 ProgressBar.Style = ProgressBarStyle.Marquee;
                 InstallCancelButton.Enabled = true;
                 if (ShowLogCheckbox.Checked)
                 {
                     logfile = Path.Combine(tempDir, "tgsinstall.log");
                     Installer.EnableLog(InstallLogModes.Verbose | InstallLogModes.PropertyDump, logfile);
                 }
                 var cl = String.Join(" ", args);
                 Installer.SetInternalUI(InstallUIOptions.Silent);
                 Installer.SetExternalUI(OnUIUpdate, InstallLogModes.Progress);
                 await Task.Factory.StartNew(() => Installer.InstallProduct(msipath, cl));
                 if (cancelled)
                 {
                     MessageBox.Show("Operation cancelled!");
                     return;
                 }
             }
             catch (Exception ex)
             {
                 MessageBox.Show("Error: " + ex.ToString());
                 return;
             }
             finally
             {
                 InstallCancelButton.Enabled = false;
                 ShowLogCheckbox.Enabled = true;
                 SelectPathButton.Enabled = true;
                 PathTextBox.Enabled = true;
                 DeskShortcutsCheckbox.Enabled = true;
                 StartShortcutsCheckbox.Enabled = true;
                 ProgressBar.Style = ProgressBarStyle.Blocks;
                 InstallButton.Enabled = true;
                 InstallButton.Text = "Install";
                 installing = false;
                 cancelled = false;
                 if (ShowLogCheckbox.Checked && logfile != null)
                     try
                     {
                         Process.Start(logfile).WaitForInputIdle();
                     }
                     catch { }
             }
             MessageBox.Show("Success!");
             Application.Exit();
         }
void TGInstallerWrapper.Main.InitializeComponent () private
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 33 of file Main.Designer.cs.
References TGInstallerWrapper.Main.CancelButton_Click(), TGInstallerWrapper.Main.DeskShortcutsCheckbox, TGInstallerWrapper.Main.InstallButton, TGInstallerWrapper.Main.InstallButton_Click(), TGInstallerWrapper.Main.InstallCancelButton, TGInstallerWrapper.Main.InstallingLabel, TGInstallerWrapper.Main.label1, TGInstallerWrapper.Main.Main_FormClosing(), TGInstallerWrapper.Main.PathTextBox, TGInstallerWrapper.Main.ProgressBar, TGInstallerWrapper.Main.SelectPathButton, TGInstallerWrapper.Main.SelectPathButton_Click(), TGInstallerWrapper.Main.ShowLogCheckbox, TGInstallerWrapper.Main.StartShortcutsCheckbox, TGInstallerWrapper.Main.TargetVersionLabel, and TGInstallerWrapper.Main.VersionLabel.
Referenced by TGInstallerWrapper.Main.Main().
         {
             System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Main));
             this.ProgressBar = new System.Windows.Forms.ProgressBar();
             this.DeskShortcutsCheckbox = new System.Windows.Forms.CheckBox();
             this.StartShortcutsCheckbox = new System.Windows.Forms.CheckBox();
             this.InstallingLabel = new System.Windows.Forms.Label();
             this.PathTextBox = new System.Windows.Forms.TextBox();
             this.SelectPathButton = new System.Windows.Forms.Button();
             this.label1 = new System.Windows.Forms.Label();
             this.VersionLabel = new System.Windows.Forms.Label();
             this.InstallButton = new System.Windows.Forms.Button();
             this.ShowLogCheckbox = new System.Windows.Forms.CheckBox();
             this.TargetVersionLabel = new System.Windows.Forms.Label();
             this.InstallCancelButton = new System.Windows.Forms.Button();
             this.SuspendLayout();
             //
             // ProgressBar
             //
             this.ProgressBar.Location = new System.Drawing.Point(11, 119);
             this.ProgressBar.Name = "ProgressBar";
             this.ProgressBar.Size = new System.Drawing.Size(386, 22);
             this.ProgressBar.TabIndex = 0;
             //
             // DeskShortcutsCheckbox
             //
             this.DeskShortcutsCheckbox.AutoSize = true;
             this.DeskShortcutsCheckbox.Checked = true;
             this.DeskShortcutsCheckbox.CheckState = System.Windows.Forms.CheckState.Checked;
             this.DeskShortcutsCheckbox.Font = new System.Drawing.Font("Verdana", 12F);
             this.DeskShortcutsCheckbox.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.DeskShortcutsCheckbox.Location = new System.Drawing.Point(12, 61);
             this.DeskShortcutsCheckbox.Name = "DeskShortcutsCheckbox";
             this.DeskShortcutsCheckbox.Size = new System.Drawing.Size(214, 22);
             this.DeskShortcutsCheckbox.TabIndex = 2;
             this.DeskShortcutsCheckbox.Text = "Add Desktop Shortcuts";
             this.DeskShortcutsCheckbox.UseVisualStyleBackColor = true;
             //
             // StartShortcutsCheckbox
             //
             this.StartShortcutsCheckbox.AutoSize = true;
             this.StartShortcutsCheckbox.Checked = true;
             this.StartShortcutsCheckbox.CheckState = System.Windows.Forms.CheckState.Checked;
             this.StartShortcutsCheckbox.Font = new System.Drawing.Font("Verdana", 12F);
             this.StartShortcutsCheckbox.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.StartShortcutsCheckbox.Location = new System.Drawing.Point(289, 61);
             this.StartShortcutsCheckbox.Name = "StartShortcutsCheckbox";
             this.StartShortcutsCheckbox.Size = new System.Drawing.Size(236, 22);
             this.StartShortcutsCheckbox.TabIndex = 3;
             this.StartShortcutsCheckbox.Text = "Add Start Menu Shortcuts";
             this.StartShortcutsCheckbox.UseVisualStyleBackColor = true;
             //
             // InstallingLabel
             //
             this.InstallingLabel.AutoSize = true;
             this.InstallingLabel.Font = new System.Drawing.Font("Verdana", 12F);
             this.InstallingLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.InstallingLabel.Location = new System.Drawing.Point(8, 37);
             this.InstallingLabel.Name = "InstallingLabel";
             this.InstallingLabel.Size = new System.Drawing.Size(52, 18);
             this.InstallingLabel.TabIndex = 1;
             this.InstallingLabel.Text = "Path:";
             //
             // PathTextBox
             //
             this.PathTextBox.Location = new System.Drawing.Point(66, 35);
             this.PathTextBox.Name = "PathTextBox";
             this.PathTextBox.ReadOnly = true;
             this.PathTextBox.Size = new System.Drawing.Size(413, 20);
             this.PathTextBox.TabIndex = 4;
             //
             // SelectPathButton
             //
             this.SelectPathButton.Location = new System.Drawing.Point(485, 35);
             this.SelectPathButton.Name = "SelectPathButton";
             this.SelectPathButton.Size = new System.Drawing.Size(40, 20);
             this.SelectPathButton.TabIndex = 6;
             this.SelectPathButton.Text = "...";
             this.SelectPathButton.UseVisualStyleBackColor = true;
             this.SelectPathButton.Click += new System.EventHandler(this.SelectPathButton_Click);
             //
             // label1
             //
             this.label1.AutoSize = true;
             this.label1.Font = new System.Drawing.Font("Verdana", 12F);
             this.label1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.label1.Location = new System.Drawing.Point(8, 9);
             this.label1.Name = "label1";
             this.label1.Size = new System.Drawing.Size(155, 18);
             this.label1.TabIndex = 7;
             this.label1.Text = "Detected Version:";
             //
             // VersionLabel
             //
             this.VersionLabel.AutoSize = true;
             this.VersionLabel.Font = new System.Drawing.Font("Verdana", 12F);
             this.VersionLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.VersionLabel.Location = new System.Drawing.Point(169, 9);
             this.VersionLabel.Name = "VersionLabel";
             this.VersionLabel.Size = new System.Drawing.Size(228, 18);
             this.VersionLabel.TabIndex = 8;
             this.VersionLabel.Text = "Unknown (No service running)";
             //
             // InstallButton
             //
             this.InstallButton.Location = new System.Drawing.Point(400, 89);
             this.InstallButton.Name = "InstallButton";
             this.InstallButton.Size = new System.Drawing.Size(125, 22);
             this.InstallButton.TabIndex = 9;
             this.InstallButton.Text = "Install";
             this.InstallButton.UseVisualStyleBackColor = true;
             this.InstallButton.Click += new System.EventHandler(this.InstallButton_Click);
             //
             // ShowLogCheckbox
             //
             this.ShowLogCheckbox.AutoSize = true;
             this.ShowLogCheckbox.Font = new System.Drawing.Font("Verdana", 12F);
             this.ShowLogCheckbox.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.ShowLogCheckbox.Location = new System.Drawing.Point(289, 90);
             this.ShowLogCheckbox.Name = "ShowLogCheckbox";
             this.ShowLogCheckbox.Size = new System.Drawing.Size(105, 22);
             this.ShowLogCheckbox.TabIndex = 10;
             this.ShowLogCheckbox.Text = "Show Log";
             this.ShowLogCheckbox.UseVisualStyleBackColor = true;
             //
             // TargetVersionLabel
             //
             this.TargetVersionLabel.AutoSize = true;
             this.TargetVersionLabel.Font = new System.Drawing.Font("Verdana", 12F);
             this.TargetVersionLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.TargetVersionLabel.Location = new System.Drawing.Point(8, 90);
             this.TargetVersionLabel.Name = "TargetVersionLabel";
             this.TargetVersionLabel.Size = new System.Drawing.Size(132, 18);
             this.TargetVersionLabel.TabIndex = 11;
             this.TargetVersionLabel.Text = "Target Version: v" + FileVersionInfo.GetVersionInfo(Assembly.GetExecutingAssembly().Location).FileVersion;
             //
             // InstallCancelButton
             //
             this.InstallCancelButton.Enabled = false;
             this.InstallCancelButton.Location = new System.Drawing.Point(400, 119);
             this.InstallCancelButton.Name = "InstallCancelButton";
             this.InstallCancelButton.Size = new System.Drawing.Size(125, 22);
             this.InstallCancelButton.TabIndex = 12;
             this.InstallCancelButton.Text = "Cancel";
             this.InstallCancelButton.UseVisualStyleBackColor = true;
             this.InstallCancelButton.Click += new System.EventHandler(this.CancelButton_Click);
             //
             // Main
             //
             this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
             this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
             this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(40)))), ((int)(((byte)(34)))));
             this.ClientSize = new System.Drawing.Size(537, 153);
             this.FormClosing += Main_FormClosing;
             this.Controls.Add(this.InstallCancelButton);
             this.Controls.Add(this.TargetVersionLabel);
             this.Controls.Add(this.ShowLogCheckbox);
             this.Controls.Add(this.InstallButton);
             this.Controls.Add(this.VersionLabel);
             this.Controls.Add(this.label1);
             this.Controls.Add(this.SelectPathButton);
             this.Controls.Add(this.PathTextBox);
             this.Controls.Add(this.StartShortcutsCheckbox);
             this.Controls.Add(this.DeskShortcutsCheckbox);
             this.Controls.Add(this.InstallingLabel);
             this.Controls.Add(this.ProgressBar);
             this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
             this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
             this.MaximizeBox = false;
             this.MinimizeBox = false;
             this.Name = "Main";
             this.Text = "/tg/station Server Installer";
             this.ResumeLayout(false);
             this.PerformLayout();
         }
void TGInstallerWrapper.Main.InstallButton_Click (object sender, EventArgs e) private
Definition at line 266 of file Main.cs.
References TGInstallerWrapper.Main.DoInstall().
Referenced by TGInstallerWrapper.Main.InitializeComponent().
         {
             DoInstall();
         }
void TGInstallerWrapper.Main.LoadInterfaceFromReflection () private
Definition at line 68 of file Main.cs.
References TGInstallerWrapper.Main.VersionLabel.
Referenced by TGInstallerWrapper.Main.Main().
         {
             //so this is where we expect to find the interface dll
             try
             {
                 var tmppath = Path.Combine(tempDir, InterfaceDLL);
                 File.WriteAllBytes(tmppath, Properties.Resources.TGServiceInterface);
                 InterfaceAssembly = Assembly.LoadFrom(tmppath); //we can't link to it, or load the bytes directly because the thing will complain about mixing the DLLExport code and IL code
                 Server = InterfaceAssembly.GetType(InterfaceClass);
                 ITGSService = InterfaceAssembly.GetType(InterfaceServiceInterface);
                 VerifyConnection = Server.GetMethod(InterfaceClassVerifyConnection);
                 GetComponentITGSService = Server.GetMethod(InterfaceClassGetComponent).MakeGenericMethod(ITGSService);
                 Version = ITGSService.GetMethod(InterfaceServiceInterfaceVersion);
                 PrepareForUpdate = ITGSService.GetMethod(InterfaceServiceInterfacePrepareForUpdate);
             }
             catch
             {
                 InterfaceAssembly = null;
                 VersionLabel.Text = "Error: (Could not load interface dll)";
                 return;
             }
         }
void TGInstallerWrapper.Main.Main_FormClosing (object sender, FormClosingEventArgs e) private
Definition at line 128 of file Main.cs.
References TGInstallerWrapper.Main.installing.
Referenced by TGInstallerWrapper.Main.InitializeComponent().
         {
             e.Cancel = installing;  //not allowed, nununu
         }
MessageResult TGInstallerWrapper.Main.OnUIUpdate (InstallMessage messageType, string message, MessageButtons buttons, MessageIcon icon, MessageDefaultButton defaultButton) private
Definition at line 256 of file Main.cs.
Referenced by TGInstallerWrapper.Main.DoInstall().
         {
             if (cancelled && installing)
             {
                 installing = false;
                 return MessageResult.Cancel;
             }
             return MessageResult.OK;
         }
PKillType TGInstallerWrapper.Main.PromptKillProcesses (string name) private
Definition at line 140 of file Main.cs.
Referenced by TGInstallerWrapper.Main.DoInstall().
         {
             var processes = new List<Process>(Process.GetProcessesByName(name));
             processes.RemoveAll(x => x.HasExited);
             if(processes.Count > 0)
             {
                 if (MessageBox.Show(String.Format("Found {1} running instance{2} of {0}.exe! Shall I terminate {3}?", name, processes.Count, processes.Count > 1 ? "s" : "", processes.Count > 1 ? "them" : "it"), "Warning", MessageBoxButtons.YesNo) != DialogResult.Yes)
                     return PKillType.Aborted;
                 foreach (var P in processes)
                 {
                     if (!P.HasExited)
                     {
                         P.Kill();
                         P.WaitForExit();
                     }
                     P.Dispose();
                 }
                 return PKillType.Killed;
             }
             return PKillType.NoneFound;
         }
void TGInstallerWrapper.Main.SelectPathButton_Click (object sender, EventArgs e) private
Definition at line 271 of file Main.cs.
References TGInstallerWrapper.Main.DefaultInstallDir, and TGInstallerWrapper.Main.PathTextBox.
Referenced by TGInstallerWrapper.Main.InitializeComponent().
         {
             var fbd = new FolderBrowserDialog()
             {
                 Description = "Select where you would like to install the service executables. This isn't where an actual server instance is created.",
                 ShowNewFolderButton = true
             };
             if (fbd.ShowDialog() != DialogResult.OK)
                 return;
             pathIsDefault = false;
             PathTextBox.Text = fbd.SelectedPath + Path.DirectorySeparatorChar + DefaultInstallDir;
         }
void TGInstallerWrapper.Main.SetupTempDir () private
Definition at line 49 of file Main.cs.
Referenced by TGInstallerWrapper.Main.Main().
         {
             tempDir = Path.Combine(Path.GetTempPath(), "TGS3InstallerTempDir");
             try
             {
                 if (File.Exists(tempDir))
                     File.Delete(tempDir);
                 else if (Directory.Exists(tempDir))
                     Directory.Delete(tempDir);
             }
             catch { }
             if (File.Exists(tempDir) || Directory.Exists(tempDir))
             {
                 tempDir = Path.GetTempFileName();
                 File.Delete(tempDir);  //we want a dir not a file
             }
             Directory.CreateDirectory(tempDir);
         }
bool TGInstallerWrapper.Main.TellServiceWereComingForThem () private
Definition at line 111 of file Main.cs.
References TGInstallerWrapper.Main.ConfirmDangerousUpgrade().
Referenced by TGInstallerWrapper.Main.DoInstall().
         {
             if (InterfaceAssembly == null)
                 return ConfirmDangerousUpgrade();
             var connectionVerified = VerifyConnection.Invoke(null, null) == null;
             try
             {
                 PrepareForUpdate.Invoke(GetComponentITGSService.Invoke(null, null), null);
                 Thread.Sleep(3000); //chat messages
                 return true;
             }
             catch
             {
                 return ConfirmDangerousUpgrade();
             }
         }
Member Data Documentation
bool TGInstallerWrapper.Main.cancelled = false private
Definition at line 34 of file Main.cs.
System.ComponentModel.IContainer TGInstallerWrapper.Main.components = null private
Required designer variable.
Definition at line 12 of file Main.Designer.cs.
Referenced by TGInstallerWrapper.Main.Dispose().
const string TGInstallerWrapper.Main.DefaultInstallDir = "TG Station Server" private
Definition at line 15 of file Main.cs.
Referenced by TGInstallerWrapper.Main.Main(), and TGInstallerWrapper.Main.SelectPathButton_Click().
System.Windows.Forms.CheckBox TGInstallerWrapper.Main.DeskShortcutsCheckbox private
Definition at line 213 of file Main.Designer.cs.
Referenced by TGInstallerWrapper.Main.DoInstall(), and TGInstallerWrapper.Main.InitializeComponent().
MethodInfo TGInstallerWrapper.Main.GetComponentITGSService private
Definition at line 30 of file Main.cs.
System.Windows.Forms.Button TGInstallerWrapper.Main.InstallButton private
Definition at line 220 of file Main.Designer.cs.
Referenced by TGInstallerWrapper.Main.DoInstall(), and TGInstallerWrapper.Main.InitializeComponent().
System.Windows.Forms.Button TGInstallerWrapper.Main.InstallCancelButton private
Definition at line 223 of file Main.Designer.cs.
Referenced by TGInstallerWrapper.Main.CancelButton_Click(), TGInstallerWrapper.Main.DoInstall(), and TGInstallerWrapper.Main.InitializeComponent().
bool TGInstallerWrapper.Main.installing = false private
Definition at line 33 of file Main.cs.
Referenced by TGInstallerWrapper.Main.Main_FormClosing().
System.Windows.Forms.Label TGInstallerWrapper.Main.InstallingLabel private
Definition at line 215 of file Main.Designer.cs.
Referenced by TGInstallerWrapper.Main.InitializeComponent().
Assembly TGInstallerWrapper.Main.InterfaceAssembly private
Definition at line 28 of file Main.cs.
const string TGInstallerWrapper.Main.InterfaceClass = InterfaceNamespace + ".Server" private
Definition at line 21 of file Main.cs.
const string TGInstallerWrapper.Main.InterfaceClassGetComponent = "GetComponent" private
Definition at line 24 of file Main.cs.
const string TGInstallerWrapper.Main.InterfaceClassVerifyConnection = "VerifyConnection" private
Definition at line 23 of file Main.cs.
const string TGInstallerWrapper.Main.InterfaceComponentsNamespace = InterfaceNamespace + ".Components" private
Definition at line 20 of file Main.cs.
const string TGInstallerWrapper.Main.InterfaceDLL = "TGServiceInterface.dll" private
Definition at line 18 of file Main.cs.
const string TGInstallerWrapper.Main.InterfaceNamespace = "TGServiceInterface" private
Definition at line 19 of file Main.cs.
const string TGInstallerWrapper.Main.InterfaceServiceInterface = InterfaceComponentsNamespace + ".ITGSService" private
Definition at line 22 of file Main.cs.
const string TGInstallerWrapper.Main.InterfaceServiceInterfacePrepareForUpdate = "PrepareForUpdate" private
Definition at line 26 of file Main.cs.
const string TGInstallerWrapper.Main.InterfaceServiceInterfaceVersion = "Version" private
Definition at line 25 of file Main.cs.
Type TGInstallerWrapper.Main.ITGSService private
Definition at line 29 of file Main.cs.
System.Windows.Forms.Label TGInstallerWrapper.Main.label1 private
Definition at line 218 of file Main.Designer.cs.
Referenced by TGInstallerWrapper.Main.InitializeComponent().
bool TGInstallerWrapper.Main.pathIsDefault = true private
Definition at line 35 of file Main.cs.
System.Windows.Forms.TextBox TGInstallerWrapper.Main.PathTextBox private
Definition at line 216 of file Main.Designer.cs.
Referenced by TGInstallerWrapper.Main.DoInstall(), TGInstallerWrapper.Main.InitializeComponent(), TGInstallerWrapper.Main.Main(), and TGInstallerWrapper.Main.SelectPathButton_Click().
MethodInfo TGInstallerWrapper.Main.PrepareForUpdate private
Definition at line 30 of file Main.cs.
System.Windows.Forms.ProgressBar TGInstallerWrapper.Main.ProgressBar private
Definition at line 212 of file Main.Designer.cs.
Referenced by TGInstallerWrapper.Main.DoInstall(), and TGInstallerWrapper.Main.InitializeComponent().
System.Windows.Forms.Button TGInstallerWrapper.Main.SelectPathButton private
Definition at line 217 of file Main.Designer.cs.
Referenced by TGInstallerWrapper.Main.DoInstall(), and TGInstallerWrapper.Main.InitializeComponent().
Type TGInstallerWrapper.Main.Server private
Definition at line 29 of file Main.cs.
System.Windows.Forms.CheckBox TGInstallerWrapper.Main.ShowLogCheckbox private
Definition at line 221 of file Main.Designer.cs.
Referenced by TGInstallerWrapper.Main.DoInstall(), and TGInstallerWrapper.Main.InitializeComponent().
System.Windows.Forms.CheckBox TGInstallerWrapper.Main.StartShortcutsCheckbox private
Definition at line 214 of file Main.Designer.cs.
Referenced by TGInstallerWrapper.Main.DoInstall(), and TGInstallerWrapper.Main.InitializeComponent().
System.Windows.Forms.Label TGInstallerWrapper.Main.TargetVersionLabel private
Definition at line 222 of file Main.Designer.cs.
Referenced by TGInstallerWrapper.Main.InitializeComponent().
string TGInstallerWrapper.Main.tempDir private
Definition at line 32 of file Main.cs.
MethodInfo TGInstallerWrapper.Main.VerifyConnection private
Definition at line 30 of file Main.cs.
MethodInfo TGInstallerWrapper.Main.Version private
Definition at line 30 of file Main.cs.
System.Windows.Forms.Label TGInstallerWrapper.Main.VersionLabel private
Definition at line 219 of file Main.Designer.cs.
Referenced by TGInstallerWrapper.Main.CheckForExistingVersion(), TGInstallerWrapper.Main.InitializeComponent(), and TGInstallerWrapper.Main.LoadInterfaceFromReflection().
The documentation for this class was generated from the following files:
TGInstallerWrapper/Main.cs
TGInstallerWrapper/Main.Designer.cs