tgstation-server: Tgstation.Server.Client.ApiClientFactory Class Reference
Tgstation.Server.Client.ApiClientFactory Class Reference
Public Member Functions
IApiClient CreateApiClient (Uri url, ApiHeaders apiHeaders, ApiHeaders? tokenRefreshHeaders, bool authless)
Create an IApiClient.
Parameters
url The base Uri.
apiHeaders The ApiHeaders for the IApiClient.
tokenRefreshHeaders The ApiHeaders to use to generate a new Api.Models.Response.TokenResponse.
authless If there should be no authentication performed.
Returns
A new IApiClient.
IApiClient CreateApiClient (Uri url, ApiHeaders apiHeaders, ApiHeaders? tokenRefreshHeaders, bool authless)
Create an IApiClient.
Detailed Description
Definition at line 9 of file ApiClientFactory.cs.
Member Function Documentation
CreateApiClient()
IApiClient Tgstation.Server.Client.ApiClientFactory.CreateApiClient (Uri url, ApiHeaders apiHeaders, ApiHeaders? tokenRefreshHeaders, bool authless)
Create an IApiClient.
Parameters
url The base Uri.
apiHeaders The ApiHeaders for the IApiClient.
tokenRefreshHeaders The ApiHeaders to use to generate a new Api.Models.Response.TokenResponse.
authless If there should be no authentication performed.
Returns
A new IApiClient.
Implements Tgstation.Server.Client.IApiClientFactory.
Referenced by Tgstation.Server.Client.ServerClientFactory.CreateFromToken(), Tgstation.Server.Client.ServerClientFactory.CreateWithNewToken(), and Tgstation.Server.Client.ServerClientFactory.GetServerInformation().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Client/ApiClientFactory.cs