tgstation-server: Tgstation.Server.Host.Controllers.SwarmController Class Reference
Tgstation.Server.Host.Controllers.SwarmController Class Reference
For swarm server communication.
Public Member Functions
SwarmController (ISwarmOperations swarmOperations, IAssemblyInformationProvider assemblyInformationProvider, IFileTransferStreamHandler transferService, IOptions< SwarmConfiguration > swarmConfigurationOptions, ILogger< SwarmController > logger)
Initializes a new instance of the SwarmController class.
async ValueTask< IActionResult > Register ([FromBody] SwarmRegistrationRequest registrationRequest, CancellationToken cancellationToken)
Registration endpoint.
async ValueTask< IActionResult > UnregisterNode (CancellationToken cancellationToken)
Deregistration endpoint.
IActionResult HealthCheck ()
Health check endpoint.
ValueTask< IActionResult > GetUpdatePackage ([FromQuery] string ticket, CancellationToken cancellationToken)
Endpoint to retrieve server update packages.
IActionResult UpdateNodeList ([FromBody] SwarmServersUpdateRequest serversUpdateRequest)
Node list update endpoint.
async ValueTask< IActionResult > PrepareUpdate ([FromBody] SwarmUpdateRequest updateRequest, CancellationToken cancellationToken)
Update initiation endpoint.
async ValueTask< IActionResult > CommitUpdate (CancellationToken cancellationToken)
Update commit endpoint.
async ValueTask< IActionResult > AbortUpdate ()
Update abort endpoint.
Public Member Functions inherited from Tgstation.Server.Host.Controllers.ApiControllerBase
sealed override async Task OnActionExecutionAsync (ActionExecutingContext context, ActionExecutionDelegate next)
Protected Member Functions
override async ValueTask< IActionResult?> HookExecuteAction (Func< Task > executeAction, CancellationToken cancellationToken)
Hook for executing a request.
Parameters
executeAction A Func<TResult> that should be invoked and its response awaited to continue normal execution of the request. Should NOT be called if this method returns a non-null value.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in an IActionResult that, if not null, is executed.
virtual async ValueTask< IActionResult?> HookExecuteAction (Func< Task > executeAction, CancellationToken cancellationToken)
Hook for executing a request.
Private Member Functions
bool ValidateRegistration ()
Check that the RequestRegistrationId is valid.
Private Attributes
readonly ISwarmOperations swarmOperations
The ISwarmOperations for the SwarmController.
readonly IFileTransferStreamHandler transferService
The IFileTransferStreamHandler for the SwarmController.
readonly IAssemblyInformationProvider assemblyInformationProvider
The IAssemblyInformationProvider for the SwarmController.
readonly ILogger< SwarmController > logger
The ILogger for the SwarmController.
readonly SwarmConfiguration swarmConfiguration
The SwarmConfiguration for the SwarmController.
Detailed Description
For swarm server communication.
Definition at line 30 of file SwarmController.cs.
Constructor & Destructor Documentation
SwarmController()
Tgstation.Server.Host.Controllers.SwarmController.SwarmController (ISwarmOperations swarmOperations, IAssemblyInformationProvider assemblyInformationProvider, IFileTransferStreamHandler transferService, IOptions< SwarmConfiguration > swarmConfigurationOptions, ILogger< SwarmController > logger)
Initializes a new instance of the SwarmController class.
Parameters
swarmOperations The value of swarmOperations.
assemblyInformationProvider The value of assemblyInformationProvider.
transferService The value of transferService.
swarmConfigurationOptions The IOptions<TOptions> containing the value of swarmConfiguration.
logger The value of logger.
Definition at line 70 of file SwarmController.cs.
        {
            this.swarmOperations = swarmOperations ?? throw new ArgumentNullException(nameof(swarmOperations));
            this.assemblyInformationProvider = assemblyInformationProvider ?? throw new ArgumentNullException(nameof(assemblyInformationProvider));
            this.transferService = transferService ?? throw new ArgumentNullException(nameof(transferService));
            swarmConfiguration = swarmConfigurationOptions?.Value ?? throw new ArgumentNullException(nameof(swarmConfigurationOptions));
            this.logger = logger;
        }
References Tgstation.Server.Host.Controllers.SwarmController.assemblyInformationProvider, Tgstation.Server.Host.Controllers.SwarmController.logger, Tgstation.Server.Host.Controllers.SwarmController.swarmConfiguration, Tgstation.Server.Host.Controllers.SwarmController.swarmOperations, and Tgstation.Server.Host.Controllers.SwarmController.transferService.
Member Function Documentation
AbortUpdate()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.SwarmController.AbortUpdate ()
Update abort endpoint.
Returns
A ValueTask<TResult> resulting in the IActionResult of the operation.
Definition at line 206 of file SwarmController.cs.
        {
            if (!ValidateRegistration())
                return Forbid();
            await swarmOperations.AbortUpdate();
            return NoContent();
        }
References Tgstation.Server.Host.Swarm.ISwarmUpdateAborter.AbortUpdate(), Tgstation.Server.Host.Controllers.SwarmController.swarmOperations, and Tgstation.Server.Host.Controllers.SwarmController.ValidateRegistration().
CommitUpdate()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.SwarmController.CommitUpdate (CancellationToken cancellationToken)
Update commit endpoint.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the operation.
Definition at line 190 of file SwarmController.cs.
        {
            if (!ValidateRegistration())
                return Forbid();
            var result = await swarmOperations.RemoteCommitReceived(RequestRegistrationId, cancellationToken);
            if (!result)
                return Conflict();
            return NoContent();
        }
References Tgstation.Server.Host.Swarm.ISwarmOperations.RemoteCommitReceived(), Tgstation.Server.Host.Controllers.SwarmController.swarmOperations, and Tgstation.Server.Host.Controllers.SwarmController.ValidateRegistration().
GetUpdatePackage()
ValueTask< IActionResult > Tgstation.Server.Host.Controllers.SwarmController.GetUpdatePackage ([FromQuery] string ticket, CancellationToken cancellationToken)
Endpoint to retrieve server update packages.
Parameters
ticket The Api.Models.Response.FileTicketResponse.FileTicket.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the IActionResult of the operation.
HealthCheck()
IActionResult Tgstation.Server.Host.Controllers.SwarmController.HealthCheck ()
Health check endpoint.
Returns
The IActionResult of the operation.
Definition at line 124 of file SwarmController.cs.
        {
            if (!ValidateRegistration())
                return Forbid();
            return NoContent();
        }
References Tgstation.Server.Host.Controllers.SwarmController.ValidateRegistration().
HookExecuteAction()
override async ValueTask< IActionResult?> Tgstation.Server.Host.Controllers.SwarmController.HookExecuteAction (Func< Task > executeAction, CancellationToken cancellationToken) protected virtual
Hook for executing a request.
Parameters
executeAction A Func<TResult> that should be invoked and its response awaited to continue normal execution of the request. Should NOT be called if this method returns a non-null value.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in an IActionResult that, if not null, is executed.
Reimplemented from Tgstation.Server.Host.Controllers.ApiControllerBase.
Definition at line 216 of file SwarmController.cs.
        {
            using (LogContext.PushProperty(SerilogContextHelper.RequestPathContextProperty, $"{Request.Method} {Request.Path}"))
            {
                logger.LogTrace("Swarm request from {remoteIP}...", Request.HttpContext.Connection.RemoteIpAddress);
                if (swarmConfiguration.PrivateKey == null)
                {
                    logger.LogDebug("Attempted swarm request without private key configured!");
                    return Forbid();
                }
                if (!(Request.Headers.TryGetValue(SwarmConstants.ApiKeyHeader, out var apiKeyHeaderValues)
                    && apiKeyHeaderValues.Count == 1
                    && apiKeyHeaderValues.First() == swarmConfiguration.PrivateKey))
                {
                    logger.LogDebug("Unauthorized swarm request!");
                    return Unauthorized();
                }
                if (!(Request.Headers.TryGetValue(SwarmConstants.RegistrationIdHeader, out var registrationHeaderValues)
                    && registrationHeaderValues.Count == 1
                    && Guid.TryParse(registrationHeaderValues.First(), out var registrationId)))
                {
                    logger.LogDebug("Swarm request without registration ID!");
                    return BadRequest();
                }
                // we validate the registration itself on a case-by-case basis
                if (ModelState?.IsValid == false)
                {
                    var errorMessages = ModelState
                        .SelectMany(x => x.Value!.Errors)
                        .Select(x => x.ErrorMessage);
                    logger.LogDebug(
                        "Swarm request model validation failed!{newLine}{messages}",
                        Environment.NewLine,
                        String.Join(Environment.NewLine, errorMessages));
                    return BadRequest();
                }
                logger.LogTrace("Starting swarm request processing...");
                await executeAction();
                return null;
            }
        }
References Tgstation.Server.Host.Swarm.SwarmConstants.ApiKeyHeader, Tgstation.Server.Host.Controllers.SwarmController.logger, Tgstation.Server.Host.Configuration.SwarmConfiguration.PrivateKey, Tgstation.Server.Host.Swarm.SwarmConstants.RegistrationIdHeader, Tgstation.Server.Host.Utils.SerilogContextHelper.RequestPathContextProperty, and Tgstation.Server.Host.Controllers.SwarmController.swarmConfiguration.
PrepareUpdate()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.SwarmController.PrepareUpdate ([FromBody] SwarmUpdateRequest updateRequest, CancellationToken cancellationToken)
Update initiation endpoint.
Parameters
updateRequest The SwarmUpdateRequest.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the operation.
Definition at line 170 of file SwarmController.cs.
        {
            ArgumentNullException.ThrowIfNull(updateRequest);
            if (!ValidateRegistration())
                return Forbid();
            var prepareResult = await swarmOperations.PrepareUpdateFromController(updateRequest, cancellationToken);
            if (!prepareResult)
                return Conflict();
            return NoContent();
        }
References Tgstation.Server.Host.Swarm.ISwarmOperations.PrepareUpdateFromController(), Tgstation.Server.Host.Controllers.SwarmController.swarmOperations, and Tgstation.Server.Host.Controllers.SwarmController.ValidateRegistration().
Register()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.SwarmController.Register ([FromBody] SwarmRegistrationRequest registrationRequest, CancellationToken cancellationToken)
Registration endpoint.
Parameters
registrationRequest The SwarmRegistrationRequest.
cancellationToken The CancellationToken for the operation.
Returns
The IActionResult of the operation.
Definition at line 91 of file SwarmController.cs.
        {
            ArgumentNullException.ThrowIfNull(registrationRequest);
            if (registrationRequest.ServerVersion != assemblyInformationProvider.Version)
                return StatusCode((int)HttpStatusCode.UpgradeRequired);
            var registrationResult = await swarmOperations.RegisterNode(registrationRequest, RequestRegistrationId, cancellationToken);
            if (!registrationResult)
                return Conflict();
            return NoContent();
        }
References Tgstation.Server.Host.Controllers.SwarmController.assemblyInformationProvider, Tgstation.Server.Host.Swarm.ISwarmOperations.RegisterNode(), Tgstation.Server.Host.Controllers.SwarmController.swarmOperations, and Tgstation.Server.Host.System.IAssemblyInformationProvider.Version.
UnregisterNode()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.SwarmController.UnregisterNode (CancellationToken cancellationToken)
Deregistration endpoint.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the IActionResult of the operation.
Definition at line 110 of file SwarmController.cs.
        {
            if (!ValidateRegistration())
                return Forbid();
            await swarmOperations.UnregisterNode(RequestRegistrationId, cancellationToken);
            return NoContent();
        }
References Tgstation.Server.Host.Controllers.SwarmController.swarmOperations, Tgstation.Server.Host.Swarm.ISwarmOperations.UnregisterNode(), and Tgstation.Server.Host.Controllers.SwarmController.ValidateRegistration().
UpdateNodeList()
IActionResult Tgstation.Server.Host.Controllers.SwarmController.UpdateNodeList ([FromBody] SwarmServersUpdateRequest serversUpdateRequest)
Node list update endpoint.
Parameters
serversUpdateRequest The SwarmServersUpdateRequest.
Returns
The IActionResult of the operation.
Definition at line 149 of file SwarmController.cs.
        {
            ArgumentNullException.ThrowIfNull(serversUpdateRequest);
            if (serversUpdateRequest.SwarmServers == null)
                return BadRequest();
            if (!ValidateRegistration())
                return Forbid();
            swarmOperations.UpdateSwarmServersList(serversUpdateRequest.SwarmServers);
            return NoContent();
        }
References Tgstation.Server.Host.Controllers.SwarmController.swarmOperations, Tgstation.Server.Host.Swarm.ISwarmOperations.UpdateSwarmServersList(), and Tgstation.Server.Host.Controllers.SwarmController.ValidateRegistration().
ValidateRegistration()
bool Tgstation.Server.Host.Controllers.SwarmController.ValidateRegistration () private
Check that the RequestRegistrationId is valid.
Returns
true if the RequestRegistrationId is valid, false otherwise.
Referenced by Tgstation.Server.Host.Controllers.SwarmController.AbortUpdate(), Tgstation.Server.Host.Controllers.SwarmController.CommitUpdate(), Tgstation.Server.Host.Controllers.SwarmController.HealthCheck(), Tgstation.Server.Host.Controllers.SwarmController.PrepareUpdate(), Tgstation.Server.Host.Controllers.SwarmController.UnregisterNode(), and Tgstation.Server.Host.Controllers.SwarmController.UpdateNodeList().
Member Data Documentation
assemblyInformationProvider
readonly IAssemblyInformationProvider Tgstation.Server.Host.Controllers.SwarmController.assemblyInformationProvider private
The IAssemblyInformationProvider for the SwarmController.
Definition at line 50 of file SwarmController.cs.
Referenced by Tgstation.Server.Host.Controllers.SwarmController.Register(), and Tgstation.Server.Host.Controllers.SwarmController.SwarmController().
logger
readonly ILogger<SwarmController> Tgstation.Server.Host.Controllers.SwarmController.logger private
The ILogger for the SwarmController.
Definition at line 55 of file SwarmController.cs.
Referenced by Tgstation.Server.Host.Controllers.SwarmController.HookExecuteAction(), and Tgstation.Server.Host.Controllers.SwarmController.SwarmController().
swarmConfiguration
readonly SwarmConfiguration Tgstation.Server.Host.Controllers.SwarmController.swarmConfiguration private
The SwarmConfiguration for the SwarmController.
Definition at line 60 of file SwarmController.cs.
Referenced by Tgstation.Server.Host.Controllers.SwarmController.HookExecuteAction(), and Tgstation.Server.Host.Controllers.SwarmController.SwarmController().
swarmOperations
readonly ISwarmOperations Tgstation.Server.Host.Controllers.SwarmController.swarmOperations private
The ISwarmOperations for the SwarmController.
Definition at line 40 of file SwarmController.cs.
Referenced by Tgstation.Server.Host.Controllers.SwarmController.AbortUpdate(), Tgstation.Server.Host.Controllers.SwarmController.CommitUpdate(), Tgstation.Server.Host.Controllers.SwarmController.PrepareUpdate(), Tgstation.Server.Host.Controllers.SwarmController.Register(), Tgstation.Server.Host.Controllers.SwarmController.SwarmController(), Tgstation.Server.Host.Controllers.SwarmController.UnregisterNode(), and Tgstation.Server.Host.Controllers.SwarmController.UpdateNodeList().
transferService
readonly IFileTransferStreamHandler Tgstation.Server.Host.Controllers.SwarmController.transferService private
The IFileTransferStreamHandler for the SwarmController.
Definition at line 45 of file SwarmController.cs.
Referenced by Tgstation.Server.Host.Controllers.SwarmController.SwarmController().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Controllers/SwarmController.cs