tgstation-server: Tgstation.Server.Host.Utils.DisposeInvoker Class Reference
Tgstation.Server.Host.Utils.DisposeInvoker Class Reference
Runs a given disposeAction on Dispose.
Public Member Functions
DisposeInvoker (Action disposeAction)
Initializes a new instance of the DisposeInvoker class.
void Dispose ()
Protected Member Functions
virtual void DisposeImpl ()
Implementation of Dispose run after reentrancy check.
Properties
bool IsDisposed [get]
If Dispose was called.
Private Attributes
readonly Action disposeAction
The Action to run on Dispose.
volatile int disposeRan
An int representation of a bool indicating if Dispose has ran.
Detailed Description
Runs a given disposeAction on Dispose.
Definition at line 9 of file DisposeInvoker.cs.
Constructor & Destructor Documentation
DisposeInvoker()
Tgstation.Server.Host.Utils.DisposeInvoker.DisposeInvoker (Action disposeAction)
Initializes a new instance of the DisposeInvoker class.
Parameters
disposeAction The value of disposeAction.
Definition at line 30 of file DisposeInvoker.cs.
        {
            this.disposeAction = disposeAction ?? throw new ArgumentNullException(nameof(disposeAction));
        }
References Tgstation.Server.Host.Utils.DisposeInvoker.disposeAction.
Member Function Documentation
Dispose()
void Tgstation.Server.Host.Utils.DisposeInvoker.Dispose ()
Definition at line 36 of file DisposeInvoker.cs.
        {
            if (Interlocked.Exchange(ref disposeRan, 1) != 0)
                return;
            DisposeImpl();
        }
References Tgstation.Server.Host.Utils.DisposeInvoker.DisposeImpl(), and Tgstation.Server.Host.Utils.DisposeInvoker.disposeRan.
Referenced by Tgstation.Server.Host.Components.Deployment.DmbProvider.DisposeAsync().
DisposeImpl()
virtual void Tgstation.Server.Host.Utils.DisposeInvoker.DisposeImpl () protected virtual
Implementation of Dispose run after reentrancy check.
Reimplemented in Tgstation.Server.Host.Components.Repository.Repository.
Referenced by Tgstation.Server.Host.Utils.DisposeInvoker.Dispose().
Member Data Documentation
disposeAction
readonly Action Tgstation.Server.Host.Utils.DisposeInvoker.disposeAction private
The Action to run on Dispose.
Definition at line 19 of file DisposeInvoker.cs.
Referenced by Tgstation.Server.Host.Utils.DisposeInvoker.DisposeInvoker().
disposeRan
volatile int Tgstation.Server.Host.Utils.DisposeInvoker.disposeRan private
An int representation of a bool indicating if Dispose has ran.
Definition at line 24 of file DisposeInvoker.cs.
Referenced by Tgstation.Server.Host.Utils.DisposeInvoker.Dispose().
Property Documentation
IsDisposed
bool Tgstation.Server.Host.Utils.DisposeInvoker.IsDisposed get
If Dispose was called.
Definition at line 14 of file DisposeInvoker.cs.
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Utils/DisposeInvoker.cs