tgstation-server: Tgstation.Server.Host.Setup.SetupWizard Class Reference
Tgstation.Server.Host.Setup.SetupWizard Class Reference
Public Member Functions
SetupWizard (IIOManager ioManager, IConsole console, IHostEnvironment hostingEnvironment, IAssemblyInformationProvider assemblyInformationProvider, IDatabaseConnectionFactory dbConnectionFactory, IPlatformIdentifier platformIdentifier, IAsyncDelayer asyncDelayer, IHostApplicationLifetime applicationLifetime, IConfiguration configuration, IOptions< GeneralConfiguration > generalConfigurationOptions)
Initializes a new instance of the SetupWizard class.
async Task StartAsync (CancellationToken cancellationToken)
Task StopAsync (CancellationToken cancellationToken)
Private Member Functions
async Task< bool > PromptYesNo (string question, CancellationToken cancellationToken)
A prompt for a yes or no value.
async Task< ushort?> PromptForHostingPort (CancellationToken cancellationToken)
Prompts the user to enter the port to host TGS on.
async Task TestDatabaseConnection (DbConnection testConnection, DatabaseConfiguration databaseConfiguration, string databaseName, bool dbExists, CancellationToken cancellationToken)
Ensure a given testConnection works.
async Task< string > ValidateNonExistantSqliteDBName (string databaseName, CancellationToken cancellationToken)
Check that a given SQLite databaseName is can be accessed. Also prompts the user if they want to use a relative or absolute path.
async Task< DatabaseType > PromptDatabaseType (bool firstTime, CancellationToken cancellationToken)
Prompt the user for the DatabaseType.
async Task< DatabaseConfiguration > ConfigureDatabase (CancellationToken cancellationToken)
Prompts the user to create a DatabaseConfiguration.
async Task< GeneralConfiguration > ConfigureGeneral (CancellationToken cancellationToken)
Prompts the user to create a GeneralConfiguration.
async Task< FileLoggingConfiguration > ConfigureLogging (CancellationToken cancellationToken)
Prompts the user to create a FileLoggingConfiguration.
async Task< ElasticsearchConfiguration > ConfigureElasticsearch (CancellationToken cancellationToken)
Prompts the user to create a ElasticsearchConfiguration.
async Task< ControlPanelConfiguration > ConfigureControlPanel (CancellationToken cancellationToken)
Prompts the user to create a ControlPanelConfiguration.
async Task< SwarmConfiguration > ConfigureSwarm (CancellationToken cancellationToken)
Prompts the user to create a SwarmConfiguration.
async Task SaveConfiguration (string userConfigFileName, ushort? hostingPort, DatabaseConfiguration databaseConfiguration, GeneralConfiguration newGeneralConfiguration, FileLoggingConfiguration fileLoggingConfiguration, ElasticsearchConfiguration elasticsearchConfiguration, ControlPanelConfiguration controlPanelConfiguration, SwarmConfiguration swarmConfiguration, CancellationToken cancellationToken)
Saves a given Configuration set to userConfigFileName .
async Task RunWizard (string userConfigFileName, CancellationToken cancellationToken)
Runs the SetupWizard.
async Task CheckRunWizard (CancellationToken cancellationToken)
Check if it should and run the SetupWizard if necessary.
Private Attributes
readonly IIOManager ioManager
The IIOManager for the SetupWizard.
readonly IConsole console
The IConsole for the SetupWizard.
readonly IHostEnvironment hostingEnvironment
The IHostEnvironment for the SetupWizard.
readonly IAssemblyInformationProvider assemblyInformationProvider
The IAssemblyInformationProvider for the SetupWizard.
readonly IDatabaseConnectionFactory dbConnectionFactory
The IDatabaseConnectionFactory for the SetupWizard.
readonly IPlatformIdentifier platformIdentifier
The IPlatformIdentifier for the SetupWizard.
readonly IAsyncDelayer asyncDelayer
The IAsyncDelayer for the SetupWizard.
readonly IHostApplicationLifetime applicationLifetime
The IHostApplicationLifetime for the SetupWizard.
readonly GeneralConfiguration generalConfiguration
The GeneralConfiguration for the SetupWizard.
TaskCompletionSource< object > reloadTcs
A TaskCompletionSource<TResult> that will complete when the IConfiguration is reloaded.
Detailed Description
Definition at line 33 of file SetupWizard.cs.
Constructor & Destructor Documentation
SetupWizard()
Tgstation.Server.Host.Setup.SetupWizard.SetupWizard (IIOManager ioManager, IConsole console, IHostEnvironment hostingEnvironment, IAssemblyInformationProvider assemblyInformationProvider, IDatabaseConnectionFactory dbConnectionFactory, IPlatformIdentifier platformIdentifier, IAsyncDelayer asyncDelayer, IHostApplicationLifetime applicationLifetime, IConfiguration configuration, IOptions< GeneralConfiguration > generalConfigurationOptions)
Initializes a new instance of the SetupWizard class.
Parameters
ioManager The value of ioManager.
console The value of console.
hostingEnvironment The value of hostingEnvironment.
assemblyInformationProvider The value of assemblyInformationProvider.
dbConnectionFactory The value of dbConnectionFactory.
platformIdentifier The value of platformIdentifier.
asyncDelayer The value of asyncDelayer.
applicationLifetime The value of applicationLifetime.
configuration The IConfiguration in use.
generalConfigurationOptions The IOptions<TOptions> containing the value of generalConfiguration.
Definition at line 98 of file SetupWizard.cs.
         {
             this.ioManager = ioManager ?? throw new ArgumentNullException(nameof(ioManager));
             this.console = console ?? throw new ArgumentNullException(nameof(console));
             this.hostingEnvironment = hostingEnvironment ?? throw new ArgumentNullException(nameof(hostingEnvironment));
             this.assemblyInformationProvider = assemblyInformationProvider ?? throw new ArgumentNullException(nameof(assemblyInformationProvider));
             this.dbConnectionFactory = dbConnectionFactory ?? throw new ArgumentNullException(nameof(dbConnectionFactory));
             this.platformIdentifier = platformIdentifier ?? throw new ArgumentNullException(nameof(platformIdentifier));
             this.asyncDelayer = asyncDelayer ?? throw new ArgumentNullException(nameof(asyncDelayer));
             this.applicationLifetime = applicationLifetime ?? throw new ArgumentNullException(nameof(applicationLifetime));
             if (configuration == null)
                 throw new ArgumentNullException(nameof(configuration));
             generalConfiguration = generalConfigurationOptions?.Value ?? throw new ArgumentNullException(nameof(generalConfigurationOptions));
             configuration
                 .GetReloadToken()
                 .RegisterChangeCallback(
                     state => reloadTcs?.TrySetResult(null),
                     null);
         }
References Tgstation.Server.Host.Setup.SetupWizard.applicationLifetime, Tgstation.Server.Host.Setup.SetupWizard.assemblyInformationProvider, Tgstation.Server.Host.Setup.SetupWizard.asyncDelayer, Tgstation.Server.Host.Setup.SetupWizard.console, Tgstation.Server.Host.Setup.SetupWizard.dbConnectionFactory, Tgstation.Server.Host.Setup.SetupWizard.generalConfiguration, Tgstation.Server.Host.Setup.SetupWizard.hostingEnvironment, Tgstation.Server.Host.Setup.SetupWizard.ioManager, Tgstation.Server.Host.Setup.SetupWizard.platformIdentifier, and Tgstation.Server.Host.Setup.SetupWizard.reloadTcs.
Member Function Documentation
CheckRunWizard()
async Task Tgstation.Server.Host.Setup.SetupWizard.CheckRunWizard (CancellationToken cancellationToken) private
Check if it should and run the SetupWizard if necessary.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Definition at line 1013 of file SetupWizard.cs.
         {
             var setupWizardMode = generalConfiguration.SetupWizardMode;
             if (setupWizardMode == SetupWizardMode.Never)
                 return;
             var forceRun = setupWizardMode == SetupWizardMode.Force || setupWizardMode == SetupWizardMode.Only;
             if (!console.Available)
             {
                 if (forceRun)
                     throw new InvalidOperationException("Asked to run setup wizard with no console avaliable!");
                 return;
             }
             var userConfigFileName = String.Format(CultureInfo.InvariantCulture, "appsettings.{0}.yml", hostingEnvironment.EnvironmentName);
             async Task HandleSetupCancel()
             {
                 // DCTx2: Operation should always run
                 await console.WriteAsync(String.Empty, true, default).ConfigureAwait(false);
                 await console.WriteAsync("Aborting setup!", true, default).ConfigureAwait(false);
             }
             // Link passed cancellationToken with cancel key press
             Task finalTask = Task.CompletedTask;
             using (var cts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, console.CancelKeyPress))
             using ((cancellationToken = cts.Token).Register(() => finalTask = HandleSetupCancel()))
                 try
                 {
                     var exists = await ioManager.FileExists(userConfigFileName, cancellationToken).ConfigureAwait(false);
                     if (!exists)
                     {
                         var legacyJsonFileName = $"appsettings.{hostingEnvironment.EnvironmentName}.json";
                         exists = await ioManager.FileExists(legacyJsonFileName, cancellationToken).ConfigureAwait(false);
                         if (exists)
                             userConfigFileName = legacyJsonFileName;
                     }
                     bool shouldRunBasedOnAutodetect;
                     if (exists)
                     {
                         var bytes = await ioManager.ReadAllBytes(userConfigFileName, cancellationToken).ConfigureAwait(false);
                         var contents = Encoding.UTF8.GetString(bytes);
                         var existingConfigIsEmpty = String.IsNullOrWhiteSpace(contents) || contents.Trim() == "{}";
                         shouldRunBasedOnAutodetect = existingConfigIsEmpty;
                     }
                     else
                         shouldRunBasedOnAutodetect = true;
                     if (!shouldRunBasedOnAutodetect)
                     {
                         if (forceRun)
{
                             await console.WriteAsync(String.Format(CultureInfo.InvariantCulture, "The configuration settings are requesting the setup wizard be run, but you already appear to have a configuration file ({0})!", userConfigFileName), true, cancellationToken).ConfigureAwait(false);
                             forceRun = await PromptYesNo("Continue running setup wizard? (y/n): ", cancellationToken).ConfigureAwait(false);
                         }
                         if (!forceRun)
                             return;
                     }
                     // flush the logs to prevent console conflicts
                     await asyncDelayer.Delay(TimeSpan.FromSeconds(1), cancellationToken).ConfigureAwait(false);
                     await RunWizard(userConfigFileName, cancellationToken).ConfigureAwait(false);
                 }
                 finally
                 {
                     await finalTask.ConfigureAwait(false);
                 }
         }
References Tgstation.Server.Host.Setup.SetupWizard.asyncDelayer, Tgstation.Server.Host.IO.IConsole.Available, Tgstation.Server.Host.IO.IConsole.CancelKeyPress, Tgstation.Server.Host.Setup.SetupWizard.console, Tgstation.Server.Host.Core.IAsyncDelayer.Delay(), Tgstation.Server.Host.IO.IIOManager.FileExists(), Tgstation.Server.Host.Setup.SetupWizard.generalConfiguration, Tgstation.Server.Host.Setup.SetupWizard.hostingEnvironment, Tgstation.Server.Host.Setup.SetupWizard.ioManager, Tgstation.Server.Host.Setup.SetupWizard.PromptYesNo(), Tgstation.Server.Host.IO.IIOManager.ReadAllBytes(), Tgstation.Server.Host.Setup.SetupWizard.RunWizard(), Tgstation.Server.Host.Configuration.GeneralConfiguration.SetupWizardMode, and Tgstation.Server.Host.IO.IConsole.WriteAsync().
Referenced by Tgstation.Server.Host.Setup.SetupWizard.StartAsync().
ConfigureControlPanel()
async Task<ControlPanelConfiguration> Tgstation.Server.Host.Setup.SetupWizard.ConfigureControlPanel (CancellationToken cancellationToken) private
Prompts the user to create a ControlPanelConfiguration.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the new ControlPanelConfiguration.
Definition at line 798 of file SetupWizard.cs.
         {
             var config = new ControlPanelConfiguration
             {
                 Enable = await PromptYesNo("Enable the web control panel (Incomplete)? (y/n): ", cancellationToken).ConfigureAwait(false),
                 AllowAnyOrigin = await PromptYesNo("Allow web control panels hosted elsewhere to access the server? (Access-Control-Allow-Origin: *) (y/n): ", cancellationToken).ConfigureAwait(false),
             };
             if (!config.AllowAnyOrigin)
             {
                 await console.WriteAsync("Enter a comma seperated list of CORS allowed origins (optional): ", false, cancellationToken).ConfigureAwait(false);
                 var commaSeperatedOrigins = await console.ReadLineAsync(false, cancellationToken).ConfigureAwait(false);
                 if (!String.IsNullOrWhiteSpace(commaSeperatedOrigins))
                 {
                     var splits = commaSeperatedOrigins.Split(',');
                     config.AllowedOrigins = new List<string>(splits.Select(x => x.Trim()));
                 }
             }
             return config;
         }
References Tgstation.Server.Host.Setup.SetupWizard.console, Tgstation.Server.Host.Setup.SetupWizard.PromptYesNo(), Tgstation.Server.Host.IO.IConsole.ReadLineAsync(), and Tgstation.Server.Host.IO.IConsole.WriteAsync().
Referenced by Tgstation.Server.Host.Setup.SetupWizard.RunWizard().
ConfigureDatabase()
async Task<DatabaseConfiguration> Tgstation.Server.Host.Setup.SetupWizard.ConfigureDatabase (CancellationToken cancellationToken) private
Prompts the user to create a DatabaseConfiguration.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the new DatabaseConfiguration.
Definition at line 393 of file SetupWizard.cs.
         {
             bool firstTime = true;
             do
             {
                 await console.WriteAsync(null, true, cancellationToken).ConfigureAwait(false);
                 var databaseConfiguration = new DatabaseConfiguration
                 {
                     DatabaseType = await PromptDatabaseType(firstTime, cancellationToken).ConfigureAwait(false),
                 };
                 firstTime = false;
                 string serverAddress = null;
                 ushort? serverPort = null;
                 bool isSqliteDB = databaseConfiguration.DatabaseType == DatabaseType.Sqlite;
                 if (!isSqliteDB)
                     do
                     {
                         await console.WriteAsync(null, true, cancellationToken).ConfigureAwait(false);
                         await console.WriteAsync("Enter the server's address and port [<server>:<port> or <server>] (blank for local): ", false, cancellationToken).ConfigureAwait(false);
                         serverAddress = await console.ReadLineAsync(false, cancellationToken).ConfigureAwait(false);
                         if (String.IsNullOrWhiteSpace(serverAddress))
                             serverAddress = null;
                         else if (databaseConfiguration.DatabaseType == DatabaseType.SqlServer)
{
                             var match = Regex.Match(serverAddress, @"^(?<server>.+):(?<port>.+)$");
                             if (match.Success)
{
                                 serverAddress = match.Groups["server"].Value;
                                 var portString = match.Groups["port"].Value;
                                 if (UInt16.TryParse(portString, out var port))
                                     serverPort = port;
                                 else
{
                                     await console.WriteAsync($"Failed to parse port \"{portString}\", please try again.", true, cancellationToken).ConfigureAwait(false);
                                     continue;
                                 }
                             }
                         }
                         break;
                     }
                     while (true);
                 await console.WriteAsync(null, true, cancellationToken).ConfigureAwait(false);
                 await console.WriteAsync($"Enter the database {(isSqliteDB ? "file path" : "name")} (Can be from previous installation. Otherwise, should not exist): ", false, cancellationToken).ConfigureAwait(false);
                 string databaseName;
                 bool dbExists = false;
                 do
                 {
                     databaseName = await console.ReadLineAsync(false, cancellationToken).ConfigureAwait(false);
                     if (!String.IsNullOrWhiteSpace(databaseName))
                     {
                         if (isSqliteDB)
{
                             dbExists = await ioManager.FileExists(databaseName, cancellationToken).ConfigureAwait(false);
                             if (!dbExists)
                                 databaseName = await ValidateNonExistantSqliteDBName(databaseName, cancellationToken).ConfigureAwait(false);
                         }
                         else
                             dbExists = await PromptYesNo("Does this database already exist? If not, we will attempt to CREATE it. (y/n): ", cancellationToken).ConfigureAwait(false);
                     }
                     if (String.IsNullOrWhiteSpace(databaseName))
                         await console.WriteAsync("Invalid database name!", true, cancellationToken).ConfigureAwait(false);
                     else
                         break;
                 }
                 while (true);
                 bool useWinAuth;
                 if (databaseConfiguration.DatabaseType == DatabaseType.SqlServer && platformIdentifier.IsWindows)
                     useWinAuth = await PromptYesNo("Use Windows Authentication? (y/n): ", cancellationToken).ConfigureAwait(false);
                 else
                     useWinAuth = false;
                 await console.WriteAsync(null, true, cancellationToken).ConfigureAwait(false);
                 string username = null;
                 string password = null;
                 if (!isSqliteDB)
                     if (!useWinAuth)
                     {
                         await console.WriteAsync("Enter username: ", false, cancellationToken).ConfigureAwait(false);
                         username = await console.ReadLineAsync(false, cancellationToken).ConfigureAwait(false);
                         await console.WriteAsync("Enter password: ", false, cancellationToken).ConfigureAwait(false);
                         password = await console.ReadLineAsync(true, cancellationToken).ConfigureAwait(false);
                     }
                     else
                     {
                         await console.WriteAsync("IMPORTANT: If using the service runner, ensure this computer's LocalSystem account has CREATE DATABASE permissions on the target server!", true, cancellationToken).ConfigureAwait(false);
                         await console.WriteAsync("The account it uses in MSSQL is usually \"NT AUTHORITY\\SYSTEM\" and the role it needs is usually \"dbcreator\".", true, cancellationToken).ConfigureAwait(false);
                         await console.WriteAsync("We'll run a sanity test here, but it won't be indicative of the service's permissions if that is the case", true, cancellationToken).ConfigureAwait(false);
                     }
                 await console.WriteAsync(null, true, cancellationToken).ConfigureAwait(false);
                 DbConnection testConnection;
                 void CreateTestConnection(string connectionString) =>
                     testConnection = dbConnectionFactory.CreateConnection(
                         connectionString,
                         databaseConfiguration.DatabaseType);
                 switch (databaseConfiguration.DatabaseType)
                 {
                     case DatabaseType.SqlServer:
{
                             var csb = new SqlConnectionStringBuilder
{
                                 ApplicationName = assemblyInformationProvider.VersionPrefix,
                                 DataSource = serverAddress ?? "(local)",
                             };
                             if (useWinAuth)
                                 csb.IntegratedSecurity = true;
                             else
{
                                 csb.UserID = username;
                                 csb.Password = password;
                             }
                             CreateTestConnection(csb.ConnectionString);
                             csb.InitialCatalog = databaseName;
                             databaseConfiguration.ConnectionString = csb.ConnectionString;
                         }
                         break;
                     case DatabaseType.MariaDB:
                     case DatabaseType.MySql:
{
                             // MySQL/MariaDB
                             var csb = new MySqlConnectionStringBuilder
{
                                 Server = serverAddress ?? "127.0.0.1",
                                 UserID = username,
                                 Password = password,
                             };
                             if (serverPort.HasValue)
                                 csb.Port = serverPort.Value;
                             CreateTestConnection(csb.ConnectionString);
                             csb.Database = databaseName;
                             databaseConfiguration.ConnectionString = csb.ConnectionString;
                         }
                         break;
                     case DatabaseType.Sqlite:
{
                             var csb = new SqliteConnectionStringBuilder
{
                                 DataSource = databaseName,
                                 Mode = dbExists ? SqliteOpenMode.ReadOnly : SqliteOpenMode.ReadWriteCreate,
                             };
                             CreateTestConnection(csb.ConnectionString);
                             databaseConfiguration.ConnectionString = csb.ConnectionString;
                         }
                         break;
                     case DatabaseType.PostgresSql:
{
                             var csb = new NpgsqlConnectionStringBuilder
{
                                 ApplicationName = assemblyInformationProvider.VersionPrefix,
                                 Host = serverAddress ?? "127.0.0.1",
                                 Password = password,
                                 Username = username,
                             };
                             if (serverPort.HasValue)
                                 csb.Port = serverPort.Value;
                             CreateTestConnection(csb.ConnectionString);
                             csb.Database = databaseName;
                             databaseConfiguration.ConnectionString = csb.ConnectionString;
                         }
                         break;
                     default:
                         throw new InvalidOperationException("Invalid DatabaseType!");
                 }
                 try
                 {
                     await TestDatabaseConnection(testConnection, databaseConfiguration, databaseName, dbExists, cancellationToken).ConfigureAwait(false);
                     return databaseConfiguration;
                 }
                 catch (OperationCanceledException)
                 {
                     throw;
                 }
                 catch (Exception e)
                 {
                     await console.WriteAsync(e.Message, true, cancellationToken).ConfigureAwait(false);
                     await console.WriteAsync(null, true, cancellationToken).ConfigureAwait(false);
                     await console.WriteAsync("Retrying database configuration...", true, cancellationToken).ConfigureAwait(false);
                 }
             }
             while (true);
         }
References Tgstation.Server.Host.Setup.SetupWizard.assemblyInformationProvider, Tgstation.Server.Host.Setup.SetupWizard.console, Tgstation.Server.Host.Database.IDatabaseConnectionFactory.CreateConnection(), Tgstation.Server.Host.Setup.SetupWizard.dbConnectionFactory, Tgstation.Server.Host.IO.IIOManager.FileExists(), Tgstation.Server.Host.Setup.SetupWizard.ioManager, Tgstation.Server.Host.System.IPlatformIdentifier.IsWindows, Tgstation.Server.Host.Setup.SetupWizard.platformIdentifier, Tgstation.Server.Host.Setup.SetupWizard.PromptDatabaseType(), Tgstation.Server.Host.Setup.SetupWizard.PromptYesNo(), Tgstation.Server.Host.IO.IConsole.ReadLineAsync(), Tgstation.Server.Host.Setup.SetupWizard.TestDatabaseConnection(), Tgstation.Server.Host.Setup.SetupWizard.ValidateNonExistantSqliteDBName(), Tgstation.Server.Host.System.IAssemblyInformationProvider.VersionPrefix, and Tgstation.Server.Host.IO.IConsole.WriteAsync().
Referenced by Tgstation.Server.Host.Setup.SetupWizard.RunWizard().
ConfigureElasticsearch()
async Task<ElasticsearchConfiguration> Tgstation.Server.Host.Setup.SetupWizard.ConfigureElasticsearch (CancellationToken cancellationToken) private
Prompts the user to create a ElasticsearchConfiguration.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the new ElasticsearchConfiguration.
Definition at line 748 of file SetupWizard.cs.
         {
             var elasticsearchConfiguration = new ElasticsearchConfiguration();
             await console.WriteAsync(null, true, cancellationToken).ConfigureAwait(false);
             elasticsearchConfiguration.Enable = await PromptYesNo("Enable logging to an external ElasticSearch server? (y/n): ", cancellationToken).ConfigureAwait(false);
             if (elasticsearchConfiguration.Enable)
             {
                 do
                 {
                     await console.WriteAsync("ElasticSearch server endpoint (Include protocol and port, leave blank for http://127.0.0.1:9200): ", false, cancellationToken).ConfigureAwait(false);
                     elasticsearchConfiguration.Host = await console.ReadLineAsync(false, cancellationToken).ConfigureAwait(false);
                     if (!String.IsNullOrWhiteSpace(elasticsearchConfiguration.Host))
                     {
                         break;
                     }
                 }
                 while (true);
                 do
                 {
                     await console.WriteAsync("Enter Elasticsearch username: ", false, cancellationToken).ConfigureAwait(false);
                     elasticsearchConfiguration.Username = await console.ReadLineAsync(false, cancellationToken).ConfigureAwait(false);
                     if (!String.IsNullOrWhiteSpace(elasticsearchConfiguration.Username))
                     {
                         break;
                     }
                 }
                 while (true);
                 do
                 {
                     await console.WriteAsync("Enter password: ", false, cancellationToken).ConfigureAwait(false);
                     elasticsearchConfiguration.Password = await console.ReadLineAsync(true, cancellationToken).ConfigureAwait(false);
                     if (!String.IsNullOrWhiteSpace(elasticsearchConfiguration.Username))
                     {
                         break;
                     }
                 }
                 while (true);
             }
             return elasticsearchConfiguration;
         }
References Tgstation.Server.Host.Setup.SetupWizard.console, Tgstation.Server.Host.Setup.SetupWizard.PromptYesNo(), Tgstation.Server.Host.IO.IConsole.ReadLineAsync(), and Tgstation.Server.Host.IO.IConsole.WriteAsync().
Referenced by Tgstation.Server.Host.Setup.SetupWizard.RunWizard().
ConfigureGeneral()
async Task<GeneralConfiguration> Tgstation.Server.Host.Setup.SetupWizard.ConfigureGeneral (CancellationToken cancellationToken) private
Prompts the user to create a GeneralConfiguration.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the new GeneralConfiguration.
Definition at line 605 of file SetupWizard.cs.
         {
             var newGeneralConfiguration = new GeneralConfiguration
             {
                 SetupWizardMode = SetupWizardMode.Never,
             };
             do
             {
                 await console.WriteAsync(null, true, cancellationToken).ConfigureAwait(false);
                 await console.WriteAsync(String.Format(CultureInfo.InvariantCulture, "Minimum database user password length (leave blank for default of {0}): ", newGeneralConfiguration.MinimumPasswordLength), false, cancellationToken).ConfigureAwait(false);
                 var passwordLengthString = await console.ReadLineAsync(false, cancellationToken).ConfigureAwait(false);
                 if (String.IsNullOrWhiteSpace(passwordLengthString))
                     break;
                 if (UInt32.TryParse(passwordLengthString, out var passwordLength) && passwordLength >= 0)
                 {
                     newGeneralConfiguration.MinimumPasswordLength = passwordLength;
                     break;
                 }
                 await console.WriteAsync("Please enter a positive integer!", true, cancellationToken).ConfigureAwait(false);
             }
             while (true);
             do
             {
                 await console.WriteAsync(null, true, cancellationToken).ConfigureAwait(false);
                 await console.WriteAsync(String.Format(CultureInfo.InvariantCulture, "Default timeout for sending and receiving BYOND topics (ms, 0 for infinite, leave blank for default of {0}): ", newGeneralConfiguration.ByondTopicTimeout), false, cancellationToken).ConfigureAwait(false);
                 var topicTimeoutString = await console.ReadLineAsync(false, cancellationToken).ConfigureAwait(false);
                 if (String.IsNullOrWhiteSpace(topicTimeoutString))
                     break;
                 if (UInt32.TryParse(topicTimeoutString, out var topicTimeout) && topicTimeout >= 0)
                 {
                     newGeneralConfiguration.ByondTopicTimeout = topicTimeout;
                     break;
                 }
                 await console.WriteAsync("Please enter a positive integer!", true, cancellationToken).ConfigureAwait(false);
             }
             while (true);
             await console.WriteAsync(null, true, cancellationToken).ConfigureAwait(false);
             await console.WriteAsync("Enter a GitHub personal access token to bypass some rate limits (this is optional and does not require any scopes)", true, cancellationToken).ConfigureAwait(false);
             await console.WriteAsync("GitHub personal access token: ", false, cancellationToken).ConfigureAwait(false);
             newGeneralConfiguration.GitHubAccessToken = await console.ReadLineAsync(true, cancellationToken).ConfigureAwait(false);
             if (String.IsNullOrWhiteSpace(newGeneralConfiguration.GitHubAccessToken))
                 newGeneralConfiguration.GitHubAccessToken = null;
             newGeneralConfiguration.HostApiDocumentation = await PromptYesNo("Host API Documentation? (y/n): ", cancellationToken).ConfigureAwait(false);
             return newGeneralConfiguration;
         }
References Tgstation.Server.Host.Setup.SetupWizard.console, Tgstation.Server.Host.Setup.SetupWizard.PromptYesNo(), Tgstation.Server.Host.IO.IConsole.ReadLineAsync(), and Tgstation.Server.Host.IO.IConsole.WriteAsync().
Referenced by Tgstation.Server.Host.Setup.SetupWizard.RunWizard().
ConfigureLogging()
async Task<FileLoggingConfiguration> Tgstation.Server.Host.Setup.SetupWizard.ConfigureLogging (CancellationToken cancellationToken) private
Prompts the user to create a FileLoggingConfiguration.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the new FileLoggingConfiguration.
Definition at line 663 of file SetupWizard.cs.
         {
             var fileLoggingConfiguration = new FileLoggingConfiguration();
             await console.WriteAsync(null, true, cancellationToken).ConfigureAwait(false);
             fileLoggingConfiguration.Disable = !await PromptYesNo("Enable file logging? (y/n): ", cancellationToken).ConfigureAwait(false);
             if (!fileLoggingConfiguration.Disable)
             {
                 do
                 {
                     await console.WriteAsync("Log file directory path (leave blank for default): ", false, cancellationToken).ConfigureAwait(false);
                     fileLoggingConfiguration.Directory = await console.ReadLineAsync(false, cancellationToken).ConfigureAwait(false);
                     if (String.IsNullOrWhiteSpace(fileLoggingConfiguration.Directory))
                     {
                         fileLoggingConfiguration.Directory = null;
                         break;
                     }
                     // test a write of it
                     await console.WriteAsync(null, true, cancellationToken).ConfigureAwait(false);
                     await console.WriteAsync("Testing directory access...", true, cancellationToken).ConfigureAwait(false);
                     try
                     {
                         await ioManager.CreateDirectory(fileLoggingConfiguration.Directory, cancellationToken).ConfigureAwait(false);
                         var testFile = ioManager.ConcatPath(fileLoggingConfiguration.Directory, String.Format(CultureInfo.InvariantCulture, "WizardAccesTest.{0}.deleteme", Guid.NewGuid()));
                         await ioManager.WriteAllBytes(testFile, Array.Empty<byte>(), cancellationToken).ConfigureAwait(false);
                         try
{
                             await ioManager.DeleteFile(testFile, cancellationToken).ConfigureAwait(false);
                         }
                         catch (OperationCanceledException)
{
                             throw;
                         }
                         catch (Exception e)
{
                             await console.WriteAsync(String.Format(CultureInfo.InvariantCulture, "Error deleting test log file: {0}", testFile), true, cancellationToken).ConfigureAwait(false);
                             await console.WriteAsync(e.Message, true, cancellationToken).ConfigureAwait(false);
                             await console.WriteAsync(null, true, cancellationToken).ConfigureAwait(false);
                         }
                         break;
                     }
                     catch (OperationCanceledException)
                     {
                         throw;
                     }
                     catch (Exception e)
                     {
                         await console.WriteAsync(e.Message, true, cancellationToken).ConfigureAwait(false);
                         await console.WriteAsync(null, true, cancellationToken).ConfigureAwait(false);
                         await console.WriteAsync("Please verify the path is valid and you have access to it!", true, cancellationToken).ConfigureAwait(false);
                     }
                 }
                 while (true);
                 async Task<LogLevel?> PromptLogLevel(string question)
                 {
                     do
                     {
                         await console.WriteAsync(null, true, cancellationToken).ConfigureAwait(false);
                         await console.WriteAsync(question, true, cancellationToken).ConfigureAwait(false);
                         await console.WriteAsync(String.Format(CultureInfo.InvariantCulture, "Enter one of {0}/{1}/{2}/{3}/{4}/{5} (leave blank for default): ", nameof(LogLevel.Trace), nameof(LogLevel.Debug), nameof(LogLevel.Information), nameof(LogLevel.Warning), nameof(LogLevel.Error), nameof(LogLevel.Critical)), false, cancellationToken).ConfigureAwait(false);
                         var responseString = await console.ReadLineAsync(false, cancellationToken).ConfigureAwait(false);
                         if (String.IsNullOrWhiteSpace(responseString))
                             return null;
                         if (Enum.TryParse<LogLevel>(responseString, out var logLevel) && logLevel != LogLevel.None)
                             return logLevel;
                         await console.WriteAsync("Invalid log level!", true, cancellationToken).ConfigureAwait(false);
                     }
                     while (true);
                 }
                 fileLoggingConfiguration.LogLevel = await PromptLogLevel(String.Format(CultureInfo.InvariantCulture, "Enter the level limit for normal logs (default {0}).", fileLoggingConfiguration.LogLevel)).ConfigureAwait(false) ?? fileLoggingConfiguration.LogLevel;
                 fileLoggingConfiguration.MicrosoftLogLevel = await PromptLogLevel(String.Format(CultureInfo.InvariantCulture, "Enter the level limit for Microsoft logs (VERY verbose, default {0}).", fileLoggingConfiguration.MicrosoftLogLevel)).ConfigureAwait(false) ?? fileLoggingConfiguration.MicrosoftLogLevel;
             }
             return fileLoggingConfiguration;
         }
References Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.Setup.SetupWizard.console, Tgstation.Server.Host.IO.IIOManager.CreateDirectory(), Tgstation.Server.Host.IO.IIOManager.DeleteFile(), Tgstation.Server.Host.Setup.SetupWizard.ioManager, Tgstation.Server.Host.Setup.SetupWizard.PromptYesNo(), Tgstation.Server.Host.IO.IConsole.ReadLineAsync(), Tgstation.Server.Host.IO.IIOManager.WriteAllBytes(), and Tgstation.Server.Host.IO.IConsole.WriteAsync().
Referenced by Tgstation.Server.Host.Setup.SetupWizard.RunWizard().
ConfigureSwarm()
async Task<SwarmConfiguration> Tgstation.Server.Host.Setup.SetupWizard.ConfigureSwarm (CancellationToken cancellationToken) private
Prompts the user to create a SwarmConfiguration.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the new SwarmConfiguration.
Definition at line 825 of file SetupWizard.cs.
         {
             var enable = await PromptYesNo("Enable swarm mode? (y/n): ", cancellationToken).ConfigureAwait(false);
             if (!enable)
                 return null;
             string identifer;
             do
             {
                 await console.WriteAsync("Enter this server's identifer: ", false, cancellationToken).ConfigureAwait(false);
                 identifer = await console.ReadLineAsync(false, cancellationToken).ConfigureAwait(false);
             }
             while (String.IsNullOrWhiteSpace(identifer));
             async Task<Uri> ParseAddress(string question)
             {
                 Uri address;
                 do
                 {
                     await console.WriteAsync(question, false, cancellationToken).ConfigureAwait(false);
                     var addressString = await console.ReadLineAsync(false, cancellationToken).ConfigureAwait(false);
                     if (Uri.TryCreate(addressString, UriKind.Absolute, out address)
                         && address.Scheme != Uri.UriSchemeHttp
                         && address.Scheme != Uri.UriSchemeHttps)
                         address = null;
                 }
                 while (address == null);
                 return address;
             }
             var address = await ParseAddress("Enter this server's HTTP(S) address: ").ConfigureAwait(false);
             string privateKey;
             do
             {
                 await console.WriteAsync("Enter the swarm private key: ", false, cancellationToken).ConfigureAwait(false);
                 privateKey = await console.ReadLineAsync(false, cancellationToken).ConfigureAwait(false);
             }
             while (String.IsNullOrWhiteSpace(privateKey));
             var controller = await PromptYesNo("Is this server the swarm's controller? (y/n): ", cancellationToken).ConfigureAwait(false);
             Uri controllerAddress = null;
             if (!controller)
                 controllerAddress = await ParseAddress("Enter the swarm controller's HTTP(S) address: ").ConfigureAwait(false);
             return new SwarmConfiguration
             {
                 Address = address,
                 ControllerAddress = controllerAddress,
                 Identifier = identifer,
                 PrivateKey = privateKey,
             };
         }
References Tgstation.Server.Host.Setup.SetupWizard.console, Tgstation.Server.Host.Setup.SetupWizard.PromptYesNo(), Tgstation.Server.Host.IO.IConsole.ReadLineAsync(), and Tgstation.Server.Host.IO.IConsole.WriteAsync().
Referenced by Tgstation.Server.Host.Setup.SetupWizard.RunWizard().
PromptDatabaseType()
async Task<DatabaseType> Tgstation.Server.Host.Setup.SetupWizard.PromptDatabaseType (bool firstTime, CancellationToken cancellationToken) private
Prompt the user for the DatabaseType.
Parameters
firstTime If this is the user's first time here.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the input DatabaseType.
Definition at line 333 of file SetupWizard.cs.
         {
             if (firstTime)
             {
                 await console.WriteAsync(String.Empty, true, cancellationToken).ConfigureAwait(false);
                 await console.WriteAsync(
                     "NOTE: It is HIGHLY reccommended that TGS runs on a complete relational database, specfically *NOT* Sqlite.",
                     true,
                     cancellationToken)
                     .ConfigureAwait(false);
                 await console.WriteAsync(
                     "Sqlite, by nature cannot perform several DDL operations. Because of this future compatiblility cannot be guaranteed.",
                     true,
                     cancellationToken)
                     .ConfigureAwait(false);
                 await console.WriteAsync(
                     "This means that you may not be able to update to the next minor version of TGS4 without a clean re-installation!",
                     true,
                     cancellationToken)
                     .ConfigureAwait(false);
                 await console.WriteAsync(
                     "Please consider taking the time to set up a relational database if this is meant to be a long-standing server.",
                     true,
                     cancellationToken)
                     .ConfigureAwait(false);
                 await console.WriteAsync(String.Empty, true, cancellationToken).ConfigureAwait(false);
                 await asyncDelayer.Delay(TimeSpan.FromSeconds(3), cancellationToken).ConfigureAwait(false);
             }
             await console.WriteAsync("What SQL database type will you be using?", true, cancellationToken).ConfigureAwait(false);
             do
             {
                 await console.WriteAsync(
                     String.Format(
                         CultureInfo.InvariantCulture,
                         "Please enter one of {0}, {1}, {2}, {3} or {4}: ",
                         DatabaseType.MariaDB,
                         DatabaseType.MySql,
                         DatabaseType.PostgresSql,
                         DatabaseType.SqlServer,
                         DatabaseType.Sqlite),
                     false,
                     cancellationToken)
                     .ConfigureAwait(false);
                 var databaseTypeString = await console.ReadLineAsync(false, cancellationToken).ConfigureAwait(false);
                 if (Enum.TryParse<DatabaseType>(databaseTypeString, out var databaseType))
                     return databaseType;
                 await console.WriteAsync("Invalid database type!", true, cancellationToken).ConfigureAwait(false);
             }
             while (true);
         }
References Tgstation.Server.Host.Setup.SetupWizard.asyncDelayer, Tgstation.Server.Host.Setup.SetupWizard.console, Tgstation.Server.Host.Core.IAsyncDelayer.Delay(), Tgstation.Server.Host.IO.IConsole.ReadLineAsync(), and Tgstation.Server.Host.IO.IConsole.WriteAsync().
Referenced by Tgstation.Server.Host.Setup.SetupWizard.ConfigureDatabase().
PromptForHostingPort()
async Task<ushort?> Tgstation.Server.Host.Setup.SetupWizard.PromptForHostingPort (CancellationToken cancellationToken) private
Prompts the user to enter the port to host TGS on.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task resulting in the hosting port, or null to use the default.
Definition at line 167 of file SetupWizard.cs.
         {
             await console.WriteAsync(null, true, cancellationToken).ConfigureAwait(false);
             await console.WriteAsync("What port would you like to connect to TGS on?", true, cancellationToken).ConfigureAwait(false);
             await console.WriteAsync("Note: If this is a docker container with the default port already mapped, use the default.", true, cancellationToken).ConfigureAwait(false);
             do
             {
                 await console.WriteAsync(
                     $"API Port (leave blank for default of {GeneralConfiguration.DefaultApiPort}): ",
                     false,
                     cancellationToken)
                     .ConfigureAwait(false);
                 var portString = await console.ReadLineAsync(false, cancellationToken).ConfigureAwait(false);
                 if (String.IsNullOrWhiteSpace(portString))
                     return null;
                 if (UInt16.TryParse(portString, out var port) && port != 0)
                     return port;
                 await console.WriteAsync("Invalid port! Please enter a value between 1 and 65535", true, cancellationToken).ConfigureAwait(false);
             }
             while (true);
         }
References Tgstation.Server.Host.Setup.SetupWizard.console, Tgstation.Server.Host.IO.IConsole.ReadLineAsync(), and Tgstation.Server.Host.IO.IConsole.WriteAsync().
Referenced by Tgstation.Server.Host.Setup.SetupWizard.RunWizard().
PromptYesNo()
async Task<bool> Tgstation.Server.Host.Setup.SetupWizard.PromptYesNo (string question, CancellationToken cancellationToken) private
A prompt for a yes or no value.
Parameters
question The question string.
cancellationToken The CancellationToken for the operation.
Returns
A Task resulting in true if the user replied yes, false otherwise.
Definition at line 146 of file SetupWizard.cs.
         {
             do
             {
                 await console.WriteAsync(question, false, cancellationToken).ConfigureAwait(false);
                 var responseString = await console.ReadLineAsync(false, cancellationToken).ConfigureAwait(false);
                 var upperResponse = responseString.ToUpperInvariant();
                 if (upperResponse == "Y" || upperResponse == "YES")
                     return true;
                 else if (upperResponse == "N" || upperResponse == "NO")
                     return false;
                 await console.WriteAsync("Invalid response!", true, cancellationToken).ConfigureAwait(false);
             }
             while (true);
         }
References Tgstation.Server.Host.Setup.SetupWizard.console, Tgstation.Server.Host.IO.IConsole.ReadLineAsync(), and Tgstation.Server.Host.IO.IConsole.WriteAsync().
Referenced by Tgstation.Server.Host.Setup.SetupWizard.CheckRunWizard(), Tgstation.Server.Host.Setup.SetupWizard.ConfigureControlPanel(), Tgstation.Server.Host.Setup.SetupWizard.ConfigureDatabase(), Tgstation.Server.Host.Setup.SetupWizard.ConfigureElasticsearch(), Tgstation.Server.Host.Setup.SetupWizard.ConfigureGeneral(), Tgstation.Server.Host.Setup.SetupWizard.ConfigureLogging(), Tgstation.Server.Host.Setup.SetupWizard.ConfigureSwarm(), and Tgstation.Server.Host.Setup.SetupWizard.ValidateNonExistantSqliteDBName().
RunWizard()
async Task Tgstation.Server.Host.Setup.SetupWizard.RunWizard (string userConfigFileName, CancellationToken cancellationToken) private
Runs the SetupWizard.
Parameters
userConfigFileName The path to the settings json to build.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Definition at line 973 of file SetupWizard.cs.
         {
             // welcome message
             await console.WriteAsync("Welcome to tgstation-server 4!", true, cancellationToken).ConfigureAwait(false);
             await console.WriteAsync("This wizard will help you configure your server.", true, cancellationToken).ConfigureAwait(false);
             var hostingPort = await PromptForHostingPort(cancellationToken).ConfigureAwait(false);
             var databaseConfiguration = await ConfigureDatabase(cancellationToken).ConfigureAwait(false);
             var newGeneralConfiguration = await ConfigureGeneral(cancellationToken).ConfigureAwait(false);
             var fileLoggingConfiguration = await ConfigureLogging(cancellationToken).ConfigureAwait(false);
             var elasticSearchConfiguration = await ConfigureElasticsearch(cancellationToken).ConfigureAwait(false);
             var controlPanelConfiguration = await ConfigureControlPanel(cancellationToken).ConfigureAwait(false);
             var swarmConfiguration = await ConfigureSwarm(cancellationToken).ConfigureAwait(false);
             await console.WriteAsync(null, true, cancellationToken).ConfigureAwait(false);
             await SaveConfiguration(
                 userConfigFileName,
                 hostingPort,
                 databaseConfiguration,
                 newGeneralConfiguration,
                 fileLoggingConfiguration,
                 elasticSearchConfiguration,
                 controlPanelConfiguration,
                 swarmConfiguration,
                 cancellationToken)
                 .ConfigureAwait(false);
         }
References Tgstation.Server.Host.Setup.SetupWizard.ConfigureControlPanel(), Tgstation.Server.Host.Setup.SetupWizard.ConfigureDatabase(), Tgstation.Server.Host.Setup.SetupWizard.ConfigureElasticsearch(), Tgstation.Server.Host.Setup.SetupWizard.ConfigureGeneral(), Tgstation.Server.Host.Setup.SetupWizard.ConfigureLogging(), Tgstation.Server.Host.Setup.SetupWizard.ConfigureSwarm(), Tgstation.Server.Host.Setup.SetupWizard.console, Tgstation.Server.Host.Setup.SetupWizard.PromptForHostingPort(), Tgstation.Server.Host.Setup.SetupWizard.SaveConfiguration(), and Tgstation.Server.Host.IO.IConsole.WriteAsync().
Referenced by Tgstation.Server.Host.Setup.SetupWizard.CheckRunWizard().
SaveConfiguration()
async Task Tgstation.Server.Host.Setup.SetupWizard.SaveConfiguration (string userConfigFileName, ushort? hostingPort, DatabaseConfiguration databaseConfiguration, GeneralConfiguration newGeneralConfiguration, FileLoggingConfiguration fileLoggingConfiguration, ElasticsearchConfiguration elasticsearchConfiguration, ControlPanelConfiguration controlPanelConfiguration, SwarmConfiguration swarmConfiguration, CancellationToken cancellationToken) private
Saves a given Configuration set to userConfigFileName .
Parameters
userConfigFileName The file to save the Configuration to.
hostingPort The hosting port to save.
databaseConfiguration The DatabaseConfiguration to save.
newGeneralConfiguration The GeneralConfiguration to save.
fileLoggingConfiguration The FileLoggingConfiguration to save.
elasticsearchConfiguration The ElasticsearchConfiguration to save.
controlPanelConfiguration The ControlPanelConfiguration to save.
swarmConfiguration The SwarmConfiguration to save.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Definition at line 892 of file SetupWizard.cs.
         {
             await console.WriteAsync(String.Format(CultureInfo.InvariantCulture, "Configuration complete! Saving to {0}", userConfigFileName), true, cancellationToken).ConfigureAwait(false);
             newGeneralConfiguration.ApiPort = hostingPort ?? GeneralConfiguration.DefaultApiPort;
             newGeneralConfiguration.ConfigVersion = GeneralConfiguration.CurrentConfigVersion;
             var map = new Dictionary<string, object>()
             {
                 { DatabaseConfiguration.Section, databaseConfiguration },
                 { GeneralConfiguration.Section, newGeneralConfiguration },
                 { FileLoggingConfiguration.Section, fileLoggingConfiguration },
                 { ElasticsearchConfiguration.Section, elasticsearchConfiguration },
                 { ControlPanelConfiguration.Section, controlPanelConfiguration },
                 { SwarmConfiguration.Section, swarmConfiguration },
             };
             var builder = new SerializerBuilder()
                 .WithTypeConverter(new VersionConverter());
             if (userConfigFileName.EndsWith(".json", StringComparison.OrdinalIgnoreCase))
                 builder.JsonCompatible();
             var serializer = new SerializerBuilder()
                 .WithTypeConverter(new VersionConverter())
                 .Build();
             var serializedYaml = serializer.Serialize(map);
             // big hack, but, prevent the default control panel channel from being overridden
             serializedYaml = serializedYaml.Replace(
                 $"\n  {nameof(ControlPanelConfiguration.Channel)}: ",
                 String.Empty,
                 StringComparison.Ordinal)
                 .Replace("\r", String.Empty, StringComparison.Ordinal);
             var configBytes = Encoding.UTF8.GetBytes(serializedYaml);
             reloadTcs = new TaskCompletionSource<object>();
             try
             {
                 await ioManager.WriteAllBytes(userConfigFileName, configBytes, cancellationToken).ConfigureAwait(false);
                 // Ensure the reload
                 if (generalConfiguration.SetupWizardMode != SetupWizardMode.Only)
                     using (cancellationToken.Register(() => reloadTcs.TrySetCanceled()))
                         await reloadTcs.Task.ConfigureAwait(false);
             }
             catch (OperationCanceledException)
             {
                 throw;
             }
             catch (Exception e)
             {
                 await console.WriteAsync(e.Message, true, cancellationToken).ConfigureAwait(false);
                 await console.WriteAsync(null, true, cancellationToken).ConfigureAwait(false);
                 await console.WriteAsync("For your convienence, here's the yaml we tried to write out:", true, cancellationToken).ConfigureAwait(false);
                 await console.WriteAsync(null, true, cancellationToken).ConfigureAwait(false);
                 await console.WriteAsync(serializedYaml, true, cancellationToken).ConfigureAwait(false);
                 await console.WriteAsync(null, true, cancellationToken).ConfigureAwait(false);
                 await console.WriteAsync("Press any key to exit...", true, cancellationToken).ConfigureAwait(false);
                 await console.PressAnyKeyAsync(cancellationToken).ConfigureAwait(false);
                 throw new OperationCanceledException();
             }
         }
References Tgstation.Server.Host.Configuration.GeneralConfiguration.ApiPort, Tgstation.Server.Host.Configuration.GeneralConfiguration.ConfigVersion, Tgstation.Server.Host.Setup.SetupWizard.console, Tgstation.Server.Host.Configuration.GeneralConfiguration.CurrentConfigVersion, Tgstation.Server.Host.Configuration.GeneralConfiguration.DefaultApiPort, Tgstation.Server.Host.Setup.SetupWizard.generalConfiguration, Tgstation.Server.Host.Setup.SetupWizard.ioManager, Tgstation.Server.Host.IO.IConsole.PressAnyKeyAsync(), Tgstation.Server.Host.Setup.SetupWizard.reloadTcs, Tgstation.Server.Host.Configuration.ControlPanelConfiguration.Section, Tgstation.Server.Host.Configuration.DatabaseConfiguration.Section, Tgstation.Server.Host.Configuration.ElasticsearchConfiguration.Section, Tgstation.Server.Host.Configuration.FileLoggingConfiguration.Section, Tgstation.Server.Host.Configuration.GeneralConfiguration.Section, Tgstation.Server.Host.Configuration.SwarmConfiguration.Section, Tgstation.Server.Host.Configuration.GeneralConfiguration.SetupWizardMode, Tgstation.Server.Host.IO.IIOManager.WriteAllBytes(), and Tgstation.Server.Host.IO.IConsole.WriteAsync().
Referenced by Tgstation.Server.Host.Setup.SetupWizard.RunWizard().
StartAsync()
async Task Tgstation.Server.Host.Setup.SetupWizard.StartAsync (CancellationToken cancellationToken)
Definition at line 131 of file SetupWizard.cs.
         {
             await CheckRunWizard(cancellationToken).ConfigureAwait(false);
             applicationLifetime.StopApplication();
         }
References Tgstation.Server.Host.Setup.SetupWizard.applicationLifetime, and Tgstation.Server.Host.Setup.SetupWizard.CheckRunWizard().
StopAsync()
Task Tgstation.Server.Host.Setup.SetupWizard.StopAsync (CancellationToken cancellationToken)
TestDatabaseConnection()
async Task Tgstation.Server.Host.Setup.SetupWizard.TestDatabaseConnection (DbConnection testConnection, DatabaseConfiguration databaseConfiguration, string databaseName, bool dbExists, CancellationToken cancellationToken) private
Ensure a given testConnection works.
Parameters
testConnection The test DbConnection.
databaseConfiguration The DatabaseConfiguration may have derived data populated.
databaseName The database name (or path in the case of a DatabaseType.Sqlite database).
dbExists Whether or not the database exists.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Definition at line 199 of file SetupWizard.cs.
         {
             bool isSqliteDB = databaseConfiguration.DatabaseType == DatabaseType.Sqlite;
             using (testConnection)
             {
                 await console.WriteAsync("Testing connection...", true, cancellationToken).ConfigureAwait(false);
                 await testConnection.OpenAsync(cancellationToken).ConfigureAwait(false);
                 await console.WriteAsync("Connection successful!", true, cancellationToken).ConfigureAwait(false);
                 if (databaseConfiguration.DatabaseType == DatabaseType.MariaDB
                     || databaseConfiguration.DatabaseType == DatabaseType.MySql
                     || databaseConfiguration.DatabaseType == DatabaseType.PostgresSql)
                 {
                     await console.WriteAsync($"Checking {databaseConfiguration.DatabaseType} version...", true, cancellationToken).ConfigureAwait(false);
                     using var command = testConnection.CreateCommand();
                     command.CommandText = "SELECT VERSION()";
                     var fullVersion = (string)await command.ExecuteScalarAsync(cancellationToken).ConfigureAwait(false);
                     await console.WriteAsync(String.Format(CultureInfo.InvariantCulture, "Found {0}", fullVersion), true, cancellationToken).ConfigureAwait(false);
                     if (databaseConfiguration.DatabaseType == DatabaseType.PostgresSql)
                     {
                         var splits = fullVersion.Split(' ');
                         databaseConfiguration.ServerVersion = splits[1].TrimEnd(',');
                     }
                     else
                     {
                         var splits = fullVersion.Split('-');
                         databaseConfiguration.ServerVersion = splits.First();
                     }
                 }
                 if (!isSqliteDB && !dbExists)
                 {
                     await console.WriteAsync("Testing create DB permission...", true, cancellationToken).ConfigureAwait(false);
                     using (var command = testConnection.CreateCommand())
                     {
                         // I really don't care about user sanitization here, they want to fuck their own DB? so be it
 #pragma warning disable CA2100 // Review SQL queries for security vulnerabilities
                         command.CommandText = $"CREATE DATABASE {databaseName}";
 #pragma warning restore CA2100 // Review SQL queries for security vulnerabilities
                         await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
                     }
                     await console.WriteAsync("Success!", true, cancellationToken).ConfigureAwait(false);
                     await console.WriteAsync("Dropping test database...", true, cancellationToken).ConfigureAwait(false);
                     using (var command = testConnection.CreateCommand())
                     {
 #pragma warning disable CA2100 // Review SQL queries for security vulnerabilities
                         command.CommandText = $"DROP DATABASE {databaseName}";
 #pragma warning restore CA2100 // Review SQL queries for security vulnerabilities
                         try
{
                             await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
                         }
                         catch (OperationCanceledException)
{
                             throw;
                         }
                         catch (Exception e)
{
                             await console.WriteAsync(e.Message, true, cancellationToken).ConfigureAwait(false);
                             await console.WriteAsync(null, true, cancellationToken).ConfigureAwait(false);
                             await console.WriteAsync("This should be okay, but you may want to manually drop the database before continuing!", true, cancellationToken).ConfigureAwait(false);
                             await console.WriteAsync("Press any key to continue...", true, cancellationToken).ConfigureAwait(false);
                             await console.PressAnyKeyAsync(cancellationToken).ConfigureAwait(false);
                         }
                     }
                 }
             }
             if (isSqliteDB && !dbExists)
                 await Task.WhenAll(
                     console.WriteAsync("Deleting test database file...", true, cancellationToken),
                     ioManager.DeleteFile(databaseName, cancellationToken)).ConfigureAwait(false);
         }
References Tgstation.Server.Host.Setup.SetupWizard.console, Tgstation.Server.Host.Configuration.DatabaseConfiguration.DatabaseType, Tgstation.Server.Host.IO.IIOManager.DeleteFile(), Tgstation.Server.Host.Setup.SetupWizard.ioManager, Tgstation.Server.Host.IO.IConsole.PressAnyKeyAsync(), Tgstation.Server.Host.Configuration.DatabaseConfiguration.ServerVersion, and Tgstation.Server.Host.IO.IConsole.WriteAsync().
Referenced by Tgstation.Server.Host.Setup.SetupWizard.ConfigureDatabase().
ValidateNonExistantSqliteDBName()
async Task<string> Tgstation.Server.Host.Setup.SetupWizard.ValidateNonExistantSqliteDBName (string databaseName, CancellationToken cancellationToken) private
Check that a given SQLite databaseName is can be accessed. Also prompts the user if they want to use a relative or absolute path.
Parameters
databaseName The path to the potential SQLite database file.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the SQLite database path to store in the configuration.
Definition at line 286 of file SetupWizard.cs.
         {
             var resolvedPath = ioManager.ResolvePath(databaseName);
             try
             {
                 var directoryName = ioManager.GetDirectoryName(resolvedPath);
                 bool directoryExisted = await ioManager.DirectoryExists(directoryName, cancellationToken).ConfigureAwait(false);
                 await ioManager.CreateDirectory(directoryName, cancellationToken).ConfigureAwait(false);
                 try
                 {
                     await ioManager.WriteAllBytes(resolvedPath, Array.Empty<byte>(), cancellationToken).ConfigureAwait(false);
                 }
                 catch
                 {
                     if (!directoryExisted)
                         await ioManager.DeleteDirectory(directoryName, cancellationToken).ConfigureAwait(false);
                     throw;
                 }
             }
             catch (IOException)
             {
                 return null;
             }
             if (!Path.IsPathRooted(databaseName))
             {
                 await console.WriteAsync("Note, this relative path (currently) resolves to the following:", true, cancellationToken).ConfigureAwait(false);
                 await console.WriteAsync(resolvedPath, true, cancellationToken).ConfigureAwait(false);
                 bool writeResolved = await PromptYesNo(
                     "Would you like to save the relative path in the configuration? If not, the full path will be saved. (y/n): ",
                     cancellationToken)
                     .ConfigureAwait(false);
                 if (writeResolved)
                     databaseName = resolvedPath;
             }
             await ioManager.DeleteFile(databaseName, cancellationToken).ConfigureAwait(false);
             return databaseName;
         }
References Tgstation.Server.Host.Setup.SetupWizard.console, Tgstation.Server.Host.IO.IIOManager.CreateDirectory(), Tgstation.Server.Host.IO.IIOManager.DeleteDirectory(), Tgstation.Server.Host.IO.IIOManager.DeleteFile(), Tgstation.Server.Host.IO.IIOManager.DirectoryExists(), Tgstation.Server.Host.IO.IIOManager.GetDirectoryName(), Tgstation.Server.Host.Setup.SetupWizard.ioManager, Tgstation.Server.Host.Setup.SetupWizard.PromptYesNo(), Tgstation.Server.Host.IO.IIOManager.ResolvePath(), Tgstation.Server.Host.IO.IIOManager.WriteAllBytes(), and Tgstation.Server.Host.IO.IConsole.WriteAsync().
Referenced by Tgstation.Server.Host.Setup.SetupWizard.ConfigureDatabase().
Member Data Documentation
applicationLifetime
readonly IHostApplicationLifetime Tgstation.Server.Host.Setup.SetupWizard.applicationLifetime private
The IHostApplicationLifetime for the SetupWizard.
Definition at line 73 of file SetupWizard.cs.
Referenced by Tgstation.Server.Host.Setup.SetupWizard.SetupWizard(), and Tgstation.Server.Host.Setup.SetupWizard.StartAsync().
assemblyInformationProvider
readonly IAssemblyInformationProvider Tgstation.Server.Host.Setup.SetupWizard.assemblyInformationProvider private
The IAssemblyInformationProvider for the SetupWizard.
Definition at line 53 of file SetupWizard.cs.
Referenced by Tgstation.Server.Host.Setup.SetupWizard.ConfigureDatabase(), and Tgstation.Server.Host.Setup.SetupWizard.SetupWizard().
asyncDelayer
readonly IAsyncDelayer Tgstation.Server.Host.Setup.SetupWizard.asyncDelayer private
The IAsyncDelayer for the SetupWizard.
Definition at line 68 of file SetupWizard.cs.
Referenced by Tgstation.Server.Host.Setup.SetupWizard.CheckRunWizard(), Tgstation.Server.Host.Setup.SetupWizard.PromptDatabaseType(), and Tgstation.Server.Host.Setup.SetupWizard.SetupWizard().
console
readonly IConsole Tgstation.Server.Host.Setup.SetupWizard.console private
The IConsole for the SetupWizard.
Definition at line 43 of file SetupWizard.cs.
Referenced by Tgstation.Server.Host.Setup.SetupWizard.CheckRunWizard(), Tgstation.Server.Host.Setup.SetupWizard.ConfigureControlPanel(), Tgstation.Server.Host.Setup.SetupWizard.ConfigureDatabase(), Tgstation.Server.Host.Setup.SetupWizard.ConfigureElasticsearch(), Tgstation.Server.Host.Setup.SetupWizard.ConfigureGeneral(), Tgstation.Server.Host.Setup.SetupWizard.ConfigureLogging(), Tgstation.Server.Host.Setup.SetupWizard.ConfigureSwarm(), Tgstation.Server.Host.Setup.SetupWizard.PromptDatabaseType(), Tgstation.Server.Host.Setup.SetupWizard.PromptForHostingPort(), Tgstation.Server.Host.Setup.SetupWizard.PromptYesNo(), Tgstation.Server.Host.Setup.SetupWizard.RunWizard(), Tgstation.Server.Host.Setup.SetupWizard.SaveConfiguration(), Tgstation.Server.Host.Setup.SetupWizard.SetupWizard(), Tgstation.Server.Host.Setup.SetupWizard.TestDatabaseConnection(), and Tgstation.Server.Host.Setup.SetupWizard.ValidateNonExistantSqliteDBName().
dbConnectionFactory
readonly IDatabaseConnectionFactory Tgstation.Server.Host.Setup.SetupWizard.dbConnectionFactory private
The IDatabaseConnectionFactory for the SetupWizard.
Definition at line 58 of file SetupWizard.cs.
Referenced by Tgstation.Server.Host.Setup.SetupWizard.ConfigureDatabase(), and Tgstation.Server.Host.Setup.SetupWizard.SetupWizard().
generalConfiguration
readonly GeneralConfiguration Tgstation.Server.Host.Setup.SetupWizard.generalConfiguration private
The GeneralConfiguration for the SetupWizard.
Definition at line 78 of file SetupWizard.cs.
Referenced by Tgstation.Server.Host.Setup.SetupWizard.CheckRunWizard(), Tgstation.Server.Host.Setup.SetupWizard.SaveConfiguration(), and Tgstation.Server.Host.Setup.SetupWizard.SetupWizard().
hostingEnvironment
readonly IHostEnvironment Tgstation.Server.Host.Setup.SetupWizard.hostingEnvironment private
The IHostEnvironment for the SetupWizard.
Definition at line 48 of file SetupWizard.cs.
Referenced by Tgstation.Server.Host.Setup.SetupWizard.CheckRunWizard(), and Tgstation.Server.Host.Setup.SetupWizard.SetupWizard().
ioManager
readonly IIOManager Tgstation.Server.Host.Setup.SetupWizard.ioManager private
The IIOManager for the SetupWizard.
Definition at line 38 of file SetupWizard.cs.
Referenced by Tgstation.Server.Host.Setup.SetupWizard.CheckRunWizard(), Tgstation.Server.Host.Setup.SetupWizard.ConfigureDatabase(), Tgstation.Server.Host.Setup.SetupWizard.ConfigureLogging(), Tgstation.Server.Host.Setup.SetupWizard.SaveConfiguration(), Tgstation.Server.Host.Setup.SetupWizard.SetupWizard(), Tgstation.Server.Host.Setup.SetupWizard.TestDatabaseConnection(), and Tgstation.Server.Host.Setup.SetupWizard.ValidateNonExistantSqliteDBName().
platformIdentifier
readonly IPlatformIdentifier Tgstation.Server.Host.Setup.SetupWizard.platformIdentifier private
The IPlatformIdentifier for the SetupWizard.
Definition at line 63 of file SetupWizard.cs.
Referenced by Tgstation.Server.Host.Setup.SetupWizard.ConfigureDatabase(), and Tgstation.Server.Host.Setup.SetupWizard.SetupWizard().
reloadTcs
TaskCompletionSource<object> Tgstation.Server.Host.Setup.SetupWizard.reloadTcs private
A TaskCompletionSource<TResult> that will complete when the IConfiguration is reloaded.
Definition at line 83 of file SetupWizard.cs.
Referenced by Tgstation.Server.Host.Setup.SetupWizard.SaveConfiguration(), and Tgstation.Server.Host.Setup.SetupWizard.SetupWizard().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Setup/SetupWizard.cs