tgstation-server: TGS.Server.Helpers Class Reference
TGS.Server.Helpers Class Reference
Generic helpers for the Server
Static Public Member Functions
static void CopyFileForceDirectories (string source, string dest, bool overwrite)
Copy a file from source to dest , but first ensure the destination directory exists
static void DeleteDirectory (string path, bool ContentsOnly=false, IList< string > excludeRoot=null)
Recursive directory deleter
static IEnumerable< string > GetFilesWithExtensionInDirectory (string directory, string extension)
Find all files in a directory with a given extension
static void CopyDirectory (string sourceDirName, string destDirName, IList< string > ignore=null, bool ignoreIfNotExists=false)
Recusively copy a directory
static string SanitizeTopicString (string input)
Properly escapes characters for a BYOND Topic() packet. See http://www.byond.com/docs/ref/info.html#/proc/list2params
static string NormalizePath (string path)
Normalizes different versions of a path string
Static Private Member Functions
static bool CheckDeleteSymlinkDir (DirectoryInfo di)
Properly unlinks directory di if it is a symlink
static async Task NormalizeAndDelete (DirectoryInfo dir, IList< string > excludeRoot, bool deleteRoot)
Recursively empty a directory
static async Task CopyDirectoryImpl (string sourceDirName, string destDirName, IList< string > ignore, bool ignoreIfNotExists)
Recusively copy a directory
Detailed Description
Generic helpers for the Server
Definition at line 13 of file Helpers.cs.
Member Function Documentation
static bool TGS.Server.Helpers.CheckDeleteSymlinkDir (DirectoryInfo di) static private
Properly unlinks directory di if it is a symlink
Parameters
di DirectoryInfo for the directory in question
Returns
if di was a symlink and deleted, otherwise
Definition at line 79 of file Helpers.cs.
         {
             if (!di.Attributes.HasFlag(FileAttributes.Directory) || di.Attributes.HasFlag(FileAttributes.ReparsePoint))
             {    //this is probably a symlink
                 Directory.Delete(di.FullName);
                 return true;
             }
             return false;
         }
static void TGS.Server.Helpers.CopyDirectory (string sourceDirName, string destDirName, IList< string > ignore = null, bool ignoreIfNotExists = false) static
Recusively copy a directory
Parameters
sourceDirName The directory to copy
destDirName The destination directory
ignore List of files and directories to ignore while copying
ignoreIfNotExists If no error will be thrown if sourceDirName does not exist
Definition at line 128 of file Helpers.cs.
Referenced by TGS.Server.Instance.BackupAndDeleteStaticDirectory(), TGS.Server.Instance.CompileImpl(), and TGS.Server.Instance.InitialConfigureRepository().
         {
             IList<string> realIgnore;
             if (ignore != null)
             {
                 realIgnore = new List<string>();
                 foreach (var I in ignore)
                     realIgnore.Add(I.ToLower());
             }
             else
                 realIgnore = null;
             CopyDirectoryImpl(sourceDirName, destDirName, realIgnore, ignoreIfNotExists).Wait();
         }
static async Task TGS.Server.Helpers.CopyDirectoryImpl (string sourceDirName, string destDirName, IList< string > ignore, bool ignoreIfNotExists) static private
Recusively copy a directory
Parameters
sourceDirName The directory to copy
destDirName The destination directory
ignore List of lowercase files and directories to ignore while copying
ignoreIfNotExists If no error will be thrown if sourceDirName does not exist
Returns
A Task representing the operation
Definition at line 150 of file Helpers.cs.
{
             // If the destination directory doesn't exist, create it.
             Directory.CreateDirectory(destDirName);
             // Get the subdirectories for the specified directory.
             DirectoryInfo dir = new DirectoryInfo(sourceDirName);
             if (!dir.Exists)
             {
                 if (ignoreIfNotExists)
                     return;
                 throw new DirectoryNotFoundException(
                     "Source directory does not exist or could not be found: "
                     + sourceDirName);
             }
             var tasks = new List<Task>();
             DirectoryInfo[] dirs = dir.GetDirectories();
             // copy them and their contents to new location.
             foreach (DirectoryInfo subdir in dirs)
             {
                 var upperName = subdir.Name.ToUpperInvariant();
                 if (ignore != null && ignore.Any(x => x.ToUpperInvariant() == upperName))
                     continue;
                 string temppath = Path.Combine(destDirName, subdir.Name);
                 tasks.Add(CopyDirectoryImpl(subdir.FullName, temppath, ignore, false));
             }
             // Get the files in the directory and copy them to the new location.
             FileInfo[] files = dir.GetFiles();
             foreach (FileInfo file in files)
             {
                 var upperName = file.Name.ToUpperInvariant();
                 if (ignore != null && ignore.Any(x => x.ToUpperInvariant() == upperName))
                     continue;
                 string temppath = Path.Combine(destDirName, file.Name);
                 file.CopyTo(temppath, true);
             }
             await Task.WhenAll(tasks);
         }
static void TGS.Server.Helpers.CopyFileForceDirectories (string source, string dest, bool overwrite) static
Copy a file from source to dest , but first ensure the destination directory exists
Parameters
source The source file
dest The destination file
overwrite If , source will overwrite dest if it is a file. Otherwise, if dest exists, an exception will be thrown
Definition at line 21 of file Helpers.cs.
Referenced by TGS.Server.Instance.InitialConfigureRepository().
         {
             try
             {
                 Directory.CreateDirectory(Path.GetDirectoryName(dest));
             }
             catch { }   //we don't care if the above errors
             File.Copy(source, dest, overwrite);    //if this throws errors thats all we care about
         }
static void TGS.Server.Helpers.DeleteDirectory (string path, bool ContentsOnly = false, IList< string > excludeRoot = null) static
Recursive directory deleter
Parameters
path The directory to delete
ContentsOnly If , an empty path will remain instead of being deleted fully. Incompatible with excludeRoot
excludeRoot If any files or directories in the root level of path match anything in this IList<T> of strings, they won't be deleted. Incompatible with ContentsOnly
Definition at line 38 of file Helpers.cs.
Referenced by TGS.Server.Instance.ApplyStagedUpdate(), TGS.Server.Instance.BackupAndDeleteStaticDirectory(), TGS.Server.Instance.CleanByondStaging(), TGS.Server.Instance.ClearCacheFolder(), TGS.Server.Instance.Clone(), TGS.Server.Instance.CompileImpl(), TGS.Server.Instance.DeleteFile(), TGS.Server.Instance.InitializeImpl(), TGS.Server.Server.SetupConfig(), and TGS.Server.Instance.UpdateSubmodules().
         {
             if (!ContentsOnly && excludeRoot != null && excludeRoot.Count > 0)
                 throw new ArgumentException("Cannot fully delete folder with exclusions specified!");
             var di = new DirectoryInfo(path);
             if (!di.Exists)
                 return;
             if (excludeRoot != null)
                 for (var I = 0; I < excludeRoot.Count; ++I)
                     excludeRoot[I] = excludeRoot[I].ToLower();
             if (CheckDeleteSymlinkDir(di))
                 return;
             NormalizeAndDelete(di, excludeRoot, !ContentsOnly).Wait();
         }
static IEnumerable<string> TGS.Server.Helpers.GetFilesWithExtensionInDirectory (string directory, string extension) static
Find all files in a directory with a given extension
Parameters
directory The directory to search
extension The extension to look for
Returns
An IEnumerable<T> of strings containing the full paths to files with the given extension in directory
Definition at line 59 of file Helpers.cs.
Referenced by TGS.Server.Instance.GetAndCopyIncludeLines(), and TGS.Server.Tests.TestHelpers.TestGetFilesWithExtensionInDirectory().
         {
             if (directory == null)
                 throw new ArgumentNullException(nameof(directory));
             if (extension == null)
                 throw new ArgumentNullException(nameof(extension));
             var di = new DirectoryInfo(directory);
             if (!di.Exists)
                 yield break;
             foreach (var F in di.EnumerateFiles(String.Format(CultureInfo.InvariantCulture, "*.{0}", extension)))
                 yield return F.FullName;
         }
static async Task TGS.Server.Helpers.NormalizeAndDelete (DirectoryInfo dir, IList< string > excludeRoot, bool deleteRoot) static private
Recursively empty a directory
Parameters
dir DirectoryInfo of the directory to empty
excludeRoot Lowercase file and directory names to skip while emptying this level. Not passed forward
deleteRoot If , deletes dir on completion
Returns
A Task representing the operation
Definition at line 96 of file Helpers.cs.
         {
             var tasks = new List<Task>();
             foreach (var subDir in dir.GetDirectories())
             {
                 var upperName = subDir.Name.ToUpperInvariant();
                 if (excludeRoot != null && excludeRoot.Any(x => x.ToUpperInvariant() == upperName))
                     continue;
                 if (CheckDeleteSymlinkDir(subDir))
                     continue;
                 tasks.Add(NormalizeAndDelete(subDir, null, true));
             }
             foreach (var file in dir.GetFiles())
             {
                 var upperName = file.Name.ToUpperInvariant();
                 if (excludeRoot != null && excludeRoot.Any(x => x.ToUpperInvariant() == upperName))
                     continue;
                 file.Attributes = FileAttributes.Normal;
                 file.Delete();
             }
             await Task.WhenAll(tasks);
             if(deleteRoot)
                 dir.Delete(true);
         }
static string TGS.Server.Helpers.NormalizePath (string path) static
Normalizes different versions of a path string
Parameters
path The path to normalize
Returns
The normalized path
Definition at line 206 of file Helpers.cs.
Referenced by TGS.Server.Server.CreateInstance(), and TGS.Server.Server.ImportInstance().
         {
             return Path.GetFullPath(new Uri(path).LocalPath)
                        .TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar)
                        .ToUpperInvariant();
         }
static string TGS.Server.Helpers.SanitizeTopicString (string input) static
Properly escapes characters for a BYOND Topic() packet. See http://www.byond.com/docs/ref/info.html#/proc/list2params
Parameters
input The string to sanitize
Returns
The sanitized string
Definition at line 196 of file Helpers.cs.
Referenced by TGS.Server.ChatCommands.ServerChatCommand.Run(), and TGS.Server.Instance.WorldAnnounce().
         {
             return input.Replace("%", "%25").Replace("=", "%3d").Replace(";", "%3b").Replace("&", "%26").Replace("+", "%2b");
         }
The documentation for this class was generated from the following file:
TGS.Server/Helpers.cs