tgstation-server: Tgstation.Server.Host.Security.ClaimsInjector Class Reference
Tgstation.Server.Host.Security.ClaimsInjector Class Reference
Public Member Functions
ClaimsInjector (IAuthenticationContextFactory authenticationContextFactory)
Initializes a new instance of the ClaimsInjector class.
async Task InjectClaimsIntoContext (TokenValidatedContext tokenValidatedContext, CancellationToken cancellationToken)
Setup the global::System.Security.Claims.Claims for a given tokenValidatedContext .
Task InjectClaimsIntoContext (TokenValidatedContext tokenValidatedContext, CancellationToken cancellationToken)
Setup the global::System.Security.Claims.Claims for a given tokenValidatedContext .
Private Attributes
readonly IAuthenticationContextFactory authenticationContextFactory
The IAuthenticationContextFactory for the ClaimsInjector.
Detailed Description
Definition at line 18 of file ClaimsInjector.cs.
Constructor & Destructor Documentation
ClaimsInjector()
Tgstation.Server.Host.Security.ClaimsInjector.ClaimsInjector (IAuthenticationContextFactory authenticationContextFactory)
Initializes a new instance of the ClaimsInjector class.
Parameters
authenticationContextFactory The value of authenticationContextFactory.
Definition at line 29 of file ClaimsInjector.cs.
        {
            this.authenticationContextFactory = authenticationContextFactory ?? throw new ArgumentNullException(nameof(authenticationContextFactory));
        }
References Tgstation.Server.Host.Security.ClaimsInjector.authenticationContextFactory.
Member Function Documentation
InjectClaimsIntoContext()
async Task Tgstation.Server.Host.Security.ClaimsInjector.InjectClaimsIntoContext (TokenValidatedContext tokenValidatedContext, CancellationToken cancellationToken)
Setup the global::System.Security.Claims.Claims for a given tokenValidatedContext .
Implements Tgstation.Server.Host.Security.IClaimsInjector.
Definition at line 35 of file ClaimsInjector.cs.
        {
            if (tokenValidatedContext == null)
                throw new ArgumentNullException(nameof(tokenValidatedContext));
            // Find the user id in the token
            var userIdClaim = tokenValidatedContext.Principal.FindFirst(JwtRegisteredClaimNames.Sub);
            if (userIdClaim == default)
                throw new InvalidOperationException("Missing required claim!");
            long userId;
            try
            {
                userId = Int64.Parse(userIdClaim.Value, CultureInfo.InvariantCulture);
            }
            catch (Exception e)
            {
                throw new InvalidOperationException("Failed to parse user ID!", e);
            }
            ApiHeaders apiHeaders;
            try
            {
                apiHeaders = new ApiHeaders(tokenValidatedContext.HttpContext.Request.GetTypedHeaders());
            }
            catch (HeadersException)
            {
                // we are not responsible for handling header validation issues
                return;
            }
            // This populates the CurrentAuthenticationContext field for use by us and subsequent controllers
            await authenticationContextFactory.CreateAuthenticationContext(
                userId,
                apiHeaders.InstanceId,
                tokenValidatedContext.SecurityToken.ValidFrom,
                cancellationToken)
                ;
            var authenticationContext = authenticationContextFactory.CurrentAuthenticationContext;
            var enumerator = Enum.GetValues(typeof(RightsType));
            var claims = new List<Claim>();
            foreach (RightsType rightType in enumerator)
            {
                // if there's no instance user, do a weird thing and add all the instance roles
                // we need it so we can get to OnActionExecutionAsync where we can properly decide between BadRequest and Forbid
                // if user is null that means they got the token with an expired password
                var rightAsULong = authenticationContext.User == null
                    || (RightsHelper.IsInstanceRight(rightType) && authenticationContext.InstancePermissionSet == null)
                    ? ~0UL
                    : authenticationContext.GetRight(rightType);
                var rightEnum = RightsHelper.RightToType(rightType);
                var right = (Enum)Enum.ToObject(rightEnum, rightAsULong);
                foreach (Enum enumeratedRight in Enum.GetValues(rightEnum))
                    if (right.HasFlag(enumeratedRight))
                        claims.Add(new Claim(ClaimTypes.Role, RightsHelper.RoleName(rightType, enumeratedRight)));
            }
            tokenValidatedContext.Principal.AddIdentity(new ClaimsIdentity(claims));
        }
References Tgstation.Server.Host.Security.ClaimsInjector.authenticationContextFactory, Tgstation.Server.Host.Security.IAuthenticationContextFactory.CreateAuthenticationContext(), Tgstation.Server.Host.Security.IAuthenticationContextFactory.CurrentAuthenticationContext, Tgstation.Server.Api.ApiHeaders.InstanceId, Tgstation.Server.Api.Rights.RightsHelper.IsInstanceRight(), Tgstation.Server.Api.Rights.RightsHelper.RightToType(), and Tgstation.Server.Api.Rights.RightsHelper.RoleName().
Member Data Documentation
authenticationContextFactory
readonly IAuthenticationContextFactory Tgstation.Server.Host.Security.ClaimsInjector.authenticationContextFactory private
The IAuthenticationContextFactory for the ClaimsInjector.
Definition at line 23 of file ClaimsInjector.cs.
Referenced by Tgstation.Server.Host.Security.ClaimsInjector.ClaimsInjector(), and Tgstation.Server.Host.Security.ClaimsInjector.InjectClaimsIntoContext().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Security/ClaimsInjector.cs