tgstation-server: Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper Class Reference
Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper Class Reference
Public Member Functions
WindowsNetworkPromptReaper (IAsyncDelayer asyncDelayer, ILogger< WindowsNetworkPromptReaper > logger)
Construct a WindowsNetworkPromptReaper
void Dispose ()
Task StartAsync (CancellationToken cancellationToken)
async Task StopAsync (CancellationToken cancellationToken)
void RegisterProcess (IProcess process)
Register a given process for network prompt reaping
Private Member Functions
async Task Run (CancellationToken cancellationToken)
Static Private Member Functions
static bool EnumWindow (IntPtr hWnd, IntPtr lParam)
static List< IntPtr > GetAllChildHandles (IntPtr main)
Private Attributes
readonly IAsyncDelayer asyncDelayer
The IAsyncDelayer for the WindowsNetworkPromptReaper
readonly ILogger< WindowsNetworkPromptReaper > logger
The ILogger for the WindowsNetworkPromptReaper
readonly CancellationTokenSource cancellationTokenSource
The CancellationTokenSource for the WindowsNetworkPromptReaper
readonly List< IProcess > registeredProcesses
The list of IProcesss registered
Task runTask
The Task representing the lifetime of the WindowsNetworkPromptReaper
Static Private Attributes
const int SendMessageCount = 5
Number of times to send the button click message. Should be at least 2 or it may fail to focus the window
const int RecheckDelayMs = 250
Check for prompts each time this amount of milliseconds pass
Detailed Description
Definition at line 17 of file WindowsNetworkPromptReaper.cs.
Constructor & Destructor Documentation
WindowsNetworkPromptReaper()
Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.WindowsNetworkPromptReaper (IAsyncDelayer asyncDelayer, ILogger< WindowsNetworkPromptReaper > logger)
Construct a WindowsNetworkPromptReaper
Parameters
asyncDelayer The value of asyncDelayer
logger The value of logger
Definition at line 90 of file WindowsNetworkPromptReaper.cs.
         {
             this.asyncDelayer = asyncDelayer ?? throw new ArgumentNullException(nameof(asyncDelayer));
             this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
             registeredProcesses = new List<IProcess>();
             cancellationTokenSource = new CancellationTokenSource();
         }
References Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.asyncDelayer, Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.cancellationTokenSource, Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.logger, and Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.registeredProcesses.
Member Function Documentation
Dispose()
void Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.Dispose ()
EnumWindow()
static bool Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.EnumWindow (IntPtr hWnd, IntPtr lParam) static private
Definition at line 54 of file WindowsNetworkPromptReaper.cs.
         {
             var gcChildhandlesList = GCHandle.FromIntPtr(lParam);
             if (gcChildhandlesList.Target == null)
                 return false;
             var childHandles = (List<IntPtr>)gcChildhandlesList.Target;
             childHandles.Add(hWnd);
             return true;
         }
Referenced by Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.GetAllChildHandles().
GetAllChildHandles()
static List<IntPtr> Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.GetAllChildHandles (IntPtr main) static private
Definition at line 67 of file WindowsNetworkPromptReaper.cs.
         {
             var childHandles = new List<IntPtr>();
             var gcChildhandlesList = GCHandle.Alloc(childHandles);
             try
             {
                 var pointerChildHandlesList = GCHandle.ToIntPtr(gcChildhandlesList);
                 NativeMethods.EnumWindowProc childProc = new NativeMethods.EnumWindowProc(EnumWindow);
                 NativeMethods.EnumChildWindows(main, childProc, pointerChildHandlesList);
             }
             finally
             {
                 gcChildhandlesList.Free();
             }
             return childHandles;
         }
References Tgstation.Server.Host.NativeMethods.EnumChildWindows(), Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.EnumWindow(), and Tgstation.Server.Host.NativeMethods.EnumWindowProc().
Referenced by Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.Run().
RegisterProcess()
void Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.RegisterProcess (IProcess process)
Register a given process for network prompt reaping
Implements Tgstation.Server.Host.Components.Watchdog.INetworkPromptReaper.
Definition at line 189 of file WindowsNetworkPromptReaper.cs.
         {
             if (process == null)
                 throw new ArgumentNullException(nameof(process));
             lock (registeredProcesses)
             {
                 if (registeredProcesses.Contains(process))
                     throw new InvalidOperationException("This process has already been registered for network prompt reaping!");
                 logger.LogTrace("Registering process {0}...", process.Id);
                 registeredProcesses.Add(process);
             }
             process.Lifetime.ContinueWith(x =>
             {
                 logger.LogTrace("Unregistering process {0}...", process.Id);
                 lock (registeredProcesses)
                     registeredProcesses.Remove(process);
             }, TaskScheduler.Current);
         }
References Tgstation.Server.Host.System.IProcess.Id, Tgstation.Server.Host.System.IProcessBase.Lifetime, Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.logger, and Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.registeredProcesses.
Run()
async Task Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.Run (CancellationToken cancellationToken) private
Definition at line 102 of file WindowsNetworkPromptReaper.cs.
         {
             logger.LogDebug("Starting network prompt reaper...");
             try
             {
                 while (!cancellationToken.IsCancellationRequested)
                 {
                     await asyncDelayer.Delay(TimeSpan.FromMilliseconds(RecheckDelayMs), cancellationToken).ConfigureAwait(false);
                     IntPtr window;
                     int processId;
                     lock (registeredProcesses)
                     {
                         if (registeredProcesses.Count == 0)
                             continue;
                         window = NativeMethods.FindWindow(null, "Network Accessibility");
                         if (window == IntPtr.Zero)
                             continue;
                         // found a bitch
                         var threadId = NativeMethods.GetWindowThreadProcessId(window, out processId);
                         if (!registeredProcesses.Any(x => x.Id == processId))
                             continue; // not our bitch
                     }
                     logger.LogTrace("Identified \"Network Accessibility\" window in owned process {0}", processId);
                     var found = false;
                     foreach (var I in GetAllChildHandles(window))
                     {
                         const int MaxLength = 10;
                         var stringBuilder = new StringBuilder(MaxLength + 1);
                         if (NativeMethods.GetWindowText(I, stringBuilder, MaxLength) == 0)
{
                             logger.LogWarning("Error calling GetWindowText! Exception: {0}", new Win32Exception());
                             continue;
                         }
                         var windowText = stringBuilder.ToString();
                         if (windowText == "Yes")
{
                             // smash_button_meme.jpg
                             logger.LogTrace("Sending \"Yes\" button clicks...");
                             for (var J = 0; J < SendMessageCount; ++J)
{
                                 const int BM_CLICK = 0x00F5;
                                 var result = NativeMethods.SendMessage(I, BM_CLICK, IntPtr.Zero, IntPtr.Zero);
                             }
                             found = true;
                             break;
                         }
                     }
                     if (!found)
                         logger.LogDebug("Unable to find \"Yes\" button for \"Network Accessibility\" window in owned process {0}!", processId);
                 }
             }
             catch (OperationCanceledException)
             {
                 logger.LogTrace("Cancelled!");
             }
             finally
             {
                 logger.LogDebug("Exiting network prompt reaper...");
             }
         }
References Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.asyncDelayer, Tgstation.Server.Host.Core.IAsyncDelayer.Delay(), Tgstation.Server.Host.NativeMethods.FindWindow(), Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.GetAllChildHandles(), Tgstation.Server.Host.NativeMethods.GetWindowText(), Tgstation.Server.Host.NativeMethods.GetWindowThreadProcessId(), Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.logger, Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.RecheckDelayMs, Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.registeredProcesses, Tgstation.Server.Host.NativeMethods.SendMessage(), and Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.SendMessageCount.
Referenced by Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.StartAsync().
StartAsync()
Task Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.StartAsync (CancellationToken cancellationToken)
Definition at line 173 of file WindowsNetworkPromptReaper.cs.
         {
             runTask = Run(cancellationTokenSource.Token);
             return Task.CompletedTask;
         }
References Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.cancellationTokenSource, Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.Run(), and Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.runTask.
StopAsync()
async Task Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.StopAsync (CancellationToken cancellationToken)
Definition at line 180 of file WindowsNetworkPromptReaper.cs.
         {
             logger.LogTrace("Stopping network prompt reaper...");
             cancellationTokenSource.Cancel();
             await runTask.ConfigureAwait(false);
             registeredProcesses.Clear();
         }
References Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.cancellationTokenSource, Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.logger, Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.registeredProcesses, and Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.runTask.
Member Data Documentation
asyncDelayer
readonly IAsyncDelayer Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.asyncDelayer private
The IAsyncDelayer for the WindowsNetworkPromptReaper
Definition at line 32 of file WindowsNetworkPromptReaper.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.Run(), and Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.WindowsNetworkPromptReaper().
cancellationTokenSource
readonly CancellationTokenSource Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.cancellationTokenSource private
The CancellationTokenSource for the WindowsNetworkPromptReaper
Definition at line 42 of file WindowsNetworkPromptReaper.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.StartAsync(), Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.StopAsync(), and Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.WindowsNetworkPromptReaper().
logger
readonly ILogger<WindowsNetworkPromptReaper> Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.logger private
The ILogger for the WindowsNetworkPromptReaper
Definition at line 37 of file WindowsNetworkPromptReaper.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.RegisterProcess(), Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.Run(), Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.StopAsync(), and Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.WindowsNetworkPromptReaper().
RecheckDelayMs
const int Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.RecheckDelayMs = 250 static private
Check for prompts each time this amount of milliseconds pass
Definition at line 27 of file WindowsNetworkPromptReaper.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.Run().
registeredProcesses
readonly List<IProcess> Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.registeredProcesses private
The list of IProcesss registered
Definition at line 47 of file WindowsNetworkPromptReaper.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.RegisterProcess(), Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.Run(), Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.StopAsync(), and Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.WindowsNetworkPromptReaper().
runTask
Task Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.runTask private
The Task representing the lifetime of the WindowsNetworkPromptReaper
Definition at line 52 of file WindowsNetworkPromptReaper.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.StartAsync(), and Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.StopAsync().
SendMessageCount
const int Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.SendMessageCount = 5 static private
Number of times to send the button click message. Should be at least 2 or it may fail to focus the window
Definition at line 22 of file WindowsNetworkPromptReaper.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.WindowsNetworkPromptReaper.Run().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Watchdog/WindowsNetworkPromptReaper.cs