tgstation-server: Tgstation.Server.Tests.Instance.ByondTest Class Reference
Tgstation.Server.Tests.Instance.ByondTest Class Reference
Public Member Functions
ByondTest (IByondClient byondClient, IJobsClient jobsClient, Api.Models.Instance metadata)
async Task Run (CancellationToken cancellationToken)
Private Member Functions
async Task TestInstallFakeVersion (CancellationToken cancellationToken)
async Task TestInstall511 (CancellationToken cancellationToken)
async Task TestNoVersion (CancellationToken cancellationToken)
Private Attributes
readonly IByondClient byondClient
readonly Api.Models.Instance metadata
Additional Inherited Members
Protected Member Functions inherited from Tgstation.Server.Tests.Instance.JobsRequiredTest
JobsRequiredTest (IJobsClient jobsClient)
async Task< Job > WaitForJob (Job originalJob, int timeout, bool expectFailure, CancellationToken cancellationToken)
async Task< Job > WaitForJobProgressThenCancel (Job originalJob, int timeout, CancellationToken cancellationToken)
Properties inherited from Tgstation.Server.Tests.Instance.JobsRequiredTest
IJobsClient JobsClient [get]
Detailed Description
Definition at line 12 of file ByondTest.cs.
Constructor & Destructor Documentation
ByondTest()
Tgstation.Server.Tests.Instance.ByondTest.ByondTest (IByondClient byondClient, IJobsClient jobsClient, Api.Models.Instance metadata)
Definition at line 18 of file ByondTest.cs.
             : base(jobsClient)
         {
             this.byondClient = byondClient ?? throw new ArgumentNullException(nameof(byondClient));
             this.metadata = metadata ?? throw new ArgumentNullException(nameof(metadata));
         }
References Tgstation.Server.Tests.Instance.ByondTest.byondClient, and Tgstation.Server.Tests.Instance.ByondTest.metadata.
Member Function Documentation
Run()
async Task Tgstation.Server.Tests.Instance.ByondTest.Run (CancellationToken cancellationToken)
Definition at line 25 of file ByondTest.cs.
         {
             await TestNoVersion(cancellationToken).ConfigureAwait(false);
             await TestInstall511(cancellationToken).ConfigureAwait(false);
             await TestInstallFakeVersion(cancellationToken).ConfigureAwait(false);
         }
References Tgstation.Server.Tests.Instance.ByondTest.TestInstall511(), Tgstation.Server.Tests.Instance.ByondTest.TestInstallFakeVersion(), and Tgstation.Server.Tests.Instance.ByondTest.TestNoVersion().
TestInstall511()
async Task Tgstation.Server.Tests.Instance.ByondTest.TestInstall511 (CancellationToken cancellationToken) private
Definition at line 43 of file ByondTest.cs.
         {
             var newModel = new Api.Models.Byond
             {
                 Version = new Version(511, 1385)
             };
             var test = await byondClient.SetActiveVersion(newModel, cancellationToken).ConfigureAwait(false);
             Assert.IsNotNull(test.InstallJob);
             Assert.IsNull(test.Version);
             await WaitForJob(test.InstallJob, 60, false, cancellationToken).ConfigureAwait(false);
             var currentShit = await byondClient.ActiveVersion(cancellationToken).ConfigureAwait(false);
             Assert.AreEqual(newModel.Version.Semver(), currentShit.Version);
             var dreamMaker = "DreamMaker";
             if (new PlatformIdentifier().IsWindows)
                 dreamMaker += ".exe";
             var dreamMakerDir = Path.Combine(metadata.Path, "Byond", "511.1385", "byond", "bin");
             Assert.IsTrue(Directory.Exists(dreamMakerDir), $"Directory {dreamMakerDir} does not exist!");
             Assert.IsTrue(File.Exists(Path.Combine(dreamMakerDir, dreamMaker)), $"Missing DreamMaker executable! Dir contents: {String.Join(", ", Directory.GetFileSystemEntries(dreamMakerDir))}");
         }
References Tgstation.Server.Client.Components.IByondClient.ActiveVersion(), Tgstation.Server.Tests.Instance.ByondTest.byondClient, Tgstation.Server.Tests.Instance.ByondTest.metadata, Tgstation.Server.Client.Components.IByondClient.SetActiveVersion(), and Tgstation.Server.Tests.Instance.JobsRequiredTest.WaitForJob().
Referenced by Tgstation.Server.Tests.Instance.ByondTest.Run().
TestInstallFakeVersion()
async Task Tgstation.Server.Tests.Instance.ByondTest.TestInstallFakeVersion (CancellationToken cancellationToken) private
Definition at line 32 of file ByondTest.cs.
         {
             var newModel = new Api.Models.Byond
             {
                 Version = new Version(5011, 1385)
             };
             var test = await byondClient.SetActiveVersion(newModel, cancellationToken).ConfigureAwait(false);
             Assert.IsNotNull(test.InstallJob);
             await WaitForJob(test.InstallJob, 60, true, cancellationToken).ConfigureAwait(false);
         }
References Tgstation.Server.Tests.Instance.ByondTest.byondClient, Tgstation.Server.Client.Components.IByondClient.SetActiveVersion(), and Tgstation.Server.Tests.Instance.JobsRequiredTest.WaitForJob().
Referenced by Tgstation.Server.Tests.Instance.ByondTest.Run().
TestNoVersion()
async Task Tgstation.Server.Tests.Instance.ByondTest.TestNoVersion (CancellationToken cancellationToken) private
Definition at line 66 of file ByondTest.cs.
         {
             var allVersionsTask = byondClient.InstalledVersions(cancellationToken);
             var currentShit = await byondClient.ActiveVersion(cancellationToken).ConfigureAwait(false);
             Assert.IsNotNull(currentShit);
             Assert.IsNull(currentShit.InstallJob);
             Assert.IsNull(currentShit.Version);
             var otherShit = await allVersionsTask.ConfigureAwait(false);
             Assert.IsNotNull(otherShit);
             Assert.AreEqual(0, otherShit.Count);
         }
References Tgstation.Server.Client.Components.IByondClient.ActiveVersion(), Tgstation.Server.Tests.Instance.ByondTest.byondClient, and Tgstation.Server.Client.Components.IByondClient.InstalledVersions().
Referenced by Tgstation.Server.Tests.Instance.ByondTest.Run().
Member Data Documentation
byondClient
readonly IByondClient Tgstation.Server.Tests.Instance.ByondTest.byondClient private
Definition at line 14 of file ByondTest.cs.
Referenced by Tgstation.Server.Tests.Instance.ByondTest.ByondTest(), Tgstation.Server.Tests.Instance.ByondTest.TestInstall511(), Tgstation.Server.Tests.Instance.ByondTest.TestInstallFakeVersion(), and Tgstation.Server.Tests.Instance.ByondTest.TestNoVersion().
metadata
readonly Api.Models.Instance Tgstation.Server.Tests.Instance.ByondTest.metadata private
Definition at line 16 of file ByondTest.cs.
Referenced by Tgstation.Server.Tests.Instance.ByondTest.ByondTest(), and Tgstation.Server.Tests.Instance.ByondTest.TestInstall511().
The documentation for this class was generated from the following file:
tests/Tgstation.Server.Tests/Instance/ByondTest.cs