tgstation-server: Tgstation.Server.Api.Rights.RightsHelper Class Reference
Tgstation.Server.Api.Rights.RightsHelper Class Reference
Helper for RightsTypes.
Static Public Member Functions
static Type RightToType (RightsType rightsType)
Map a given rightsType to its respective Enum Type.
static IEnumerable< Type > AllRightTypes ()
Iterate the Type of each right.
static RightsType TypeToRight< TRight > ()
Map a given TRight to its respective RightsType.
static IEnumerable< string > RoleNames< TRight > (TRight right)
Gets the role claim name used for a given right .
static string RoleName (RightsType rightsType, Enum right)
Gets the role claim name used for a given rightsType and right .
static bool IsInstanceRight (RightsType rightsType)
Check if a given rightsType is meant for an Models.Instance.
static TRight AllRights< TRight > ()
Get all rights for a given TRight .
static TRight Clamp< TRight > (TRight rights)
Clamps a given set of rights to their valid range.
Static Private Attributes
static readonly IReadOnlyDictionary< RightsType, Type > TypeMap
Map of RightsTypes to their respective flag Enums.
Detailed Description
Helper for RightsTypes.
Definition at line 11 of file RightsHelper.cs.
Member Function Documentation
AllRights< TRight >()
static TRight Tgstation.Server.Api.Rights.RightsHelper.AllRights< TRight > () static
Get all rights for a given TRight .
Template Parameters
TRight The RightsType.
Returns
All rights for the given TRight .
Type Constraints
TRight : Enum
Definition at line 89 of file RightsHelper.cs.
                         : Enum
        {
            ulong rights = 0;
            foreach (Enum right in Enum.GetValues(typeof(TRight)))
                rights |= Convert.ToUInt64(right, CultureInfo.InvariantCulture);
            // cri evertim
            return (TRight)(object)rights;
        }
References Tgstation.Server.Api.Rights.List.
Referenced by Tgstation.Server.Api.Rights.RightsHelper.Clamp< TRight >().
AllRightTypes()
static IEnumerable< Type > Tgstation.Server.Api.Rights.RightsHelper.AllRightTypes () static
Iterate the Type of each right.
Returns
An IEnumerable<T> of each Type of right.
Referenced by Tgstation.Server.Host.Security.AuthorizationHandler.HandleAsync().
Clamp< TRight >()
static TRight Tgstation.Server.Api.Rights.RightsHelper.Clamp< TRight > (TRight rights) static
Clamps a given set of rights to their valid range.
Template Parameters
TRight The RightsType.
Parameters
rights The TRight s to clamp.
Returns
The clamped rights .
Type Constraints
TRight : Enum
Definition at line 106 of file RightsHelper.cs.
                         : Enum
        {
            var allRights = AllRights<TRight>();
            var allAsUlong = Convert.ToUInt64(allRights, CultureInfo.InvariantCulture);
            var rightsAsUlong = Convert.ToUInt64(rights, CultureInfo.InvariantCulture);
            return (TRight)(object)(allAsUlong & rightsAsUlong);
        }
References Tgstation.Server.Api.Rights.RightsHelper.AllRights< TRight >(), and Tgstation.Server.Api.Rights.List.
IsInstanceRight()
static bool Tgstation.Server.Api.Rights.RightsHelper.IsInstanceRight (RightsType rightsType) static
Check if a given rightsType is meant for an Models.Instance.
Parameters
rightsType The RightsType to check.
Returns
true if rightsType is an instance right, false otherwise.
Referenced by Tgstation.Server.Host.Security.AuthenticationContext.GetRight(), Tgstation.Server.Host.Security.AuthorizationHandler.HandleRightsConditionalRequirement< TRights >(), and Tgstation.Server.Host.Security.AuthenticationContextClaimsTransformation.TransformAsync().
RightToType()
static Type Tgstation.Server.Api.Rights.RightsHelper.RightToType (RightsType rightsType) static
Map a given rightsType to its respective Enum Type.
Parameters
rightsType The RightsType to lookup.
Returns
The Enum Type of the given rightsType .
Referenced by Tgstation.Server.Host.Security.AuthenticationContext.GetRight(), Tgstation.Server.Api.Rights.RightsHelper.RoleName(), and Tgstation.Server.Host.Security.AuthenticationContextClaimsTransformation.TransformAsync().
RoleName()
static string Tgstation.Server.Api.Rights.RightsHelper.RoleName (RightsType rightsType, Enum right) static
Gets the role claim name used for a given rightsType and right .
Parameters
rightsType The RightsType.
right The right value.
Returns
A string representing the claim role name.
Definition at line 71 of file RightsHelper.cs.
        {
            var enumType = RightToType(rightsType);
            return String.Concat(enumType.Name, '.', Enum.GetName(enumType, right));
        }
References Tgstation.Server.Api.Rights.List, and Tgstation.Server.Api.Rights.RightsHelper.RightToType().
Referenced by Tgstation.Server.Host.Security.AuthenticationContextClaimsTransformation.TransformAsync().
RoleNames< TRight >()
static IEnumerable< string > Tgstation.Server.Api.Rights.RightsHelper.RoleNames< TRight > (TRight right) static
Gets the role claim name used for a given right .
Template Parameters
TRight The RightsType.
Parameters
right The TRight .
Returns
Am IEnumerable<T> of strings representing the claim role names.
Type Constraints
TRight : Enum
Definition at line 57 of file RightsHelper.cs.
                         : Enum
        {
            foreach (Enum rightValue in Enum.GetValues(right.GetType()))
                if (Convert.ToInt32(rightValue, CultureInfo.InvariantCulture) != 0 && right.HasFlag(rightValue))
                    yield return String.Concat(typeof(TRight).Name, '.', rightValue.ToString());
        }
References Tgstation.Server.Api.Rights.List.
TypeToRight< TRight >()
static RightsType Tgstation.Server.Api.Rights.RightsHelper.TypeToRight< TRight > () static
Map a given TRight to its respective RightsType.
Template Parameters
TRight The Type of the right.
Returns
The RightsType of TRight .
Type Constraints
TRight : Enum
TRight : TypeMap.First
TRight : kvp
TRight : kvp.Value
TRight : typeof
TRight : TRight
TRight : Key
Member Data Documentation
TypeMap
readonly IReadOnlyDictionary<RightsType, Type> Tgstation.Server.Api.Rights.RightsHelper.TypeMap static private
Initial value:
= new Dictionary<RightsType, Type>
        {
            { RightsType.Administration, typeof(AdministrationRights) },
            { RightsType.InstanceManager, typeof(InstanceManagerRights) },
            { RightsType.Repository, typeof(RepositoryRights) },
            { RightsType.Engine, typeof(EngineRights) },
            { RightsType.DreamMaker, typeof(DreamMakerRights) },
            { RightsType.DreamDaemon, typeof(DreamDaemonRights) },
            { RightsType.ChatBots, typeof(ChatBotRights) },
            { RightsType.Configuration, typeof(ConfigurationRights) },
            { RightsType.InstancePermissionSet, typeof(InstancePermissionSetRights) },
        }
Map of RightsTypes to their respective flag Enums.
Definition at line 16 of file RightsHelper.cs.
        {
            { RightsType.Administration, typeof(AdministrationRights) },
            { RightsType.InstanceManager, typeof(InstanceManagerRights) },
            { RightsType.Repository, typeof(RepositoryRights) },
            { RightsType.Engine, typeof(EngineRights) },
            { RightsType.DreamMaker, typeof(DreamMakerRights) },
            { RightsType.DreamDaemon, typeof(DreamDaemonRights) },
            { RightsType.ChatBots, typeof(ChatBotRights) },
            { RightsType.Configuration, typeof(ConfigurationRights) },
            { RightsType.InstancePermissionSet, typeof(InstancePermissionSetRights) },
        };
The documentation for this class was generated from the following file:
src/Tgstation.Server.Api/Rights/RightsHelper.cs