tgstation-server: TGS.Server.RootAuthorizationManager Class Reference
TGS.Server.RootAuthorizationManager Class Reference
A ServiceAuthorizationManager used to determine only if the caller is an admin
Static Public Attributes
static readonly IList< ServiceAuthorizationManager > InstanceAuthManagers = new List<ServiceAuthorizationManager>()
Protected Member Functions
override bool CheckAccessCore (OperationContext operationContext)
Private Attributes
string LastSeenUser
Detailed Description
A ServiceAuthorizationManager used to determine only if the caller is an admin
Definition at line 13 of file RootAuthorizationManager.cs.
Member Function Documentation
override bool TGS.Server.RootAuthorizationManager.CheckAccessCore (OperationContext operationContext) protected
Definition at line 17 of file RootAuthorizationManager.cs.
References TGS.Server.Server.Logger, TGS.Server.Server.LoggingID, and TGS.Server.ILogger.WriteAccess().
         {
             var contract = operationContext.EndpointDispatcher.ContractName;
             if (contract == typeof(ITGConnectivity).Name)   //always allow connectivity checks
                 return true;
             var windowsIdent = operationContext.ServiceSecurityContext.WindowsIdentity;
             var wp = new WindowsPrincipal(windowsIdent);
             //first allow admins
             var authSuccess = wp.IsInRole(WindowsBuiltInRole.Administrator);
             if(!authSuccess && contract == typeof(ITGLanding).Name)
                 lock(InstanceAuthManagers)
                     return InstanceAuthManagers.Any(x => x.CheckAccess(operationContext));
             var user = windowsIdent.Name;
             if (LastSeenUser != user)
             {
                 LastSeenUser = user;
                 Server.Logger.WriteAccess(String.Format("Root access from: {0}", user), authSuccess, Server.LoggingID);
             }
             return authSuccess;
         }
Member Data Documentation
readonly IList<ServiceAuthorizationManager> TGS.Server.RootAuthorizationManager.InstanceAuthManagers = new List<ServiceAuthorizationManager>() static
Definition at line 16 of file RootAuthorizationManager.cs.
Referenced by TGS.Server.Instance.DisposeAdministration(), and TGS.Server.Instance.InitAdministration().
string TGS.Server.RootAuthorizationManager.LastSeenUser private
Definition at line 15 of file RootAuthorizationManager.cs.
The documentation for this class was generated from the following file:
TGS.Server/RootAuthorizationManager.cs