tgstation-server: Tgstation.Server.Host.Security.WindowsSystemIdentityFactory Class Reference
Tgstation.Server.Host.Security.WindowsSystemIdentityFactory Class Reference sealed
ISystemIdentityFactory for windows systems. Uses long running tasks due to potential networked domains.
Public Member Functions
WindowsSystemIdentityFactory (ILogger< WindowsSystemIdentityFactory > logger)
Initializes a new instance of the WindowsSystemIdentityFactory class.
ISystemIdentity GetCurrent ()
Retrieves a ISystemIdentity representing the user executing tgstation-server.
Returns
A ISystemIdentity representing the user executing tgstation-server.
Task< ISystemIdentity?> CreateSystemIdentity (User user, CancellationToken cancellationToken)
Create a ISystemIdentity for a given user .
Parameters
user The user to create a ISystemIdentity for.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in a new ISystemIdentity based on the given user or null if the user has no ISystemIdentity.
Task< ISystemIdentity?> CreateSystemIdentity (string username, string password, CancellationToken cancellationToken)
Create a ISystemIdentity for a given username and password.
Parameters
username The username of the user.
password The password of the user.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in a new ISystemIdentity based on the given credentials on success, null on failure.
Static Private Member Functions
static void GetUserAndDomainName (string input, out string username, out string? domainName)
Extract the username and domain name from a string in the format "username\\domainname".
Private Attributes
readonly ILogger< WindowsSystemIdentityFactory > logger
The ILogger for the WindowsSystemIdentityFactory.
Detailed Description
ISystemIdentityFactory for windows systems. Uses long running tasks due to potential networked domains.
Definition at line 22 of file WindowsSystemIdentityFactory.cs.
Constructor & Destructor Documentation
WindowsSystemIdentityFactory()
Tgstation.Server.Host.Security.WindowsSystemIdentityFactory.WindowsSystemIdentityFactory (ILogger< WindowsSystemIdentityFactory > logger)
Initializes a new instance of the WindowsSystemIdentityFactory class.
Parameters
logger The value of logger.
Definition at line 46 of file WindowsSystemIdentityFactory.cs.
        {
            this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }
References Tgstation.Server.Host.Security.WindowsSystemIdentityFactory.logger.
Member Function Documentation
CreateSystemIdentity() [1/2]
Task< ISystemIdentity?> Tgstation.Server.Host.Security.WindowsSystemIdentityFactory.CreateSystemIdentity (string username, string password, CancellationToken cancellationToken)
Create a ISystemIdentity for a given username and password.
Parameters
username The username of the user.
password The password of the user.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in a new ISystemIdentity based on the given credentials on success, null on failure.
Implements Tgstation.Server.Host.Security.ISystemIdentityFactory.
References Tgstation.Server.Host.Security.WindowsSystemIdentityFactory.GetUserAndDomainName(), Tgstation.Server.Host.Security.WindowsSystemIdentityFactory.logger, and Tgstation.Server.Host.System.NativeMethods.LogonUser().
CreateSystemIdentity() [2/2]
Task< ISystemIdentity?> Tgstation.Server.Host.Security.WindowsSystemIdentityFactory.CreateSystemIdentity (User user, CancellationToken cancellationToken)
Create a ISystemIdentity for a given user .
Parameters
user The user to create a ISystemIdentity for.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in a new ISystemIdentity based on the given user or null if the user has no ISystemIdentity.
Implements Tgstation.Server.Host.Security.ISystemIdentityFactory.
References Tgstation.Server.Host.Security.WindowsSystemIdentityFactory.GetUserAndDomainName(), and Tgstation.Server.Host.Security.WindowsSystemIdentityFactory.logger.
GetCurrent()
ISystemIdentity Tgstation.Server.Host.Security.WindowsSystemIdentityFactory.GetCurrent ()
Retrieves a ISystemIdentity representing the user executing tgstation-server.
Returns
A ISystemIdentity representing the user executing tgstation-server.
Implements Tgstation.Server.Host.Security.ISystemIdentityFactory.
GetUserAndDomainName()
static void Tgstation.Server.Host.Security.WindowsSystemIdentityFactory.GetUserAndDomainName (string input, out string username, out string? domainName) static private
Extract the username and domain name from a string in the format "username\\domainname".
Parameters
input The input string.
username The output username.
domainName The output domain name. May be null.
Definition at line 35 of file WindowsSystemIdentityFactory.cs.
        {
            var splits = input.Split('\\');
            username = splits.Length > 1 ? splits[1] : splits[0];
            domainName = splits.Length > 1 ? splits[0] : null;
        }
Referenced by Tgstation.Server.Host.Security.WindowsSystemIdentityFactory.CreateSystemIdentity(), and Tgstation.Server.Host.Security.WindowsSystemIdentityFactory.CreateSystemIdentity().
Member Data Documentation
logger
readonly ILogger<WindowsSystemIdentityFactory> Tgstation.Server.Host.Security.WindowsSystemIdentityFactory.logger private
The ILogger for the WindowsSystemIdentityFactory.
Definition at line 27 of file WindowsSystemIdentityFactory.cs.
Referenced by Tgstation.Server.Host.Security.WindowsSystemIdentityFactory.CreateSystemIdentity(), Tgstation.Server.Host.Security.WindowsSystemIdentityFactory.CreateSystemIdentity(), and Tgstation.Server.Host.Security.WindowsSystemIdentityFactory.WindowsSystemIdentityFactory().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Security/WindowsSystemIdentityFactory.cs