tgstation-server: Tgstation.Server.Host.Components.Compiler.DmbFactory Class Reference
Tgstation.Server.Host.Components.Compiler.DmbFactory Class Reference
Standard IDmbFactory
Public Member Functions
DmbFactory (IDatabaseContextFactory databaseContextFactory, IIOManager ioManager, ILogger< DmbFactory > logger, Api.Models.Instance instance)
Construct a DmbFactory
void Dispose ()
async Task LoadCompileJob (CompileJob job, CancellationToken cancellationToken)
Load a new job into the ICompileJobConsumer
IDmbProvider LockNextDmb (int lockCount)
Gets the next IDmbProvider
Task StartAsync (CancellationToken cancellationToken)
async Task StopAsync (CancellationToken cancellationToken)
async Task< IDmbProvider > FromCompileJob (CompileJob compileJob, CancellationToken cancellationToken)
Gets a IDmbProvider for a given CompileJob
async Task CleanUnusedCompileJobs (CompileJob exceptThisOne, CancellationToken cancellationToken)
Deletes all compile jobs that are inactive in the Game folder exceptThisOne
Public Attributes
bool DmbAvailable => nextDmbProvider != null
Properties
Task OnNewerDmb [get]
Properties inherited from Tgstation.Server.Host.Components.Compiler.IDmbFactory
Task OnNewerDmb [get]
Get a Task that completes when the result of a call to LockNextDmb will be different than the previous call if any
bool DmbAvailable [get]
If LockNextDmb will succeed
Private Member Functions
void CleanJob (CompileJob job)
Delete the Api.Models.Internal.CompileJob.DirectoryName of job
Private Attributes
readonly IDatabaseContextFactory databaseContextFactory
The IDatabaseContextFactory for the DmbFactory
readonly IIOManager ioManager
The IIOManager for the DmbFactory
readonly ILogger< DmbFactory > logger
The ILogger for the DmbFactory
readonly Api.Models.Instance instance
The Api.Models.Instance for the DmbFactory
readonly CancellationTokenSource cleanupCts
The CancellationTokenSource for cleanupTask
readonly IDictionary< long, int > jobLockCounts
Map of CompileJob.JobIds to locks on them.
Task cleanupTask
Task representing calls to CleanJob(CompileJob)
TaskCompletionSource< object > newerDmbTcs
TaskCompletionSource<TResult> resulting in the latest DmbProvider yet to exist
IDmbProvider nextDmbProvider
The latest DmbProvider
Detailed Description
Standard IDmbFactory
Definition at line 17 of file DmbFactory.cs.
Constructor & Destructor Documentation
DmbFactory()
Tgstation.Server.Host.Components.Compiler.DmbFactory.DmbFactory (IDatabaseContextFactory databaseContextFactory, IIOManager ioManager, ILogger< DmbFactory > logger, Api.Models.Instance instance)
Construct a DmbFactory
Parameters
databaseContextFactory The value of databaseContextFactory
ioManager The value of ioManager
logger The value of logger
instance The value of instance
Definition at line 84 of file DmbFactory.cs.
         {
             this.databaseContextFactory = databaseContextFactory ?? throw new ArgumentNullException(nameof(databaseContextFactory));
             this.ioManager = ioManager ?? throw new ArgumentNullException(nameof(ioManager));
             this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
             this.instance = instance ?? throw new ArgumentNullException(nameof(instance));
             cleanupTask = Task.CompletedTask;
             newerDmbTcs = new TaskCompletionSource<object>();
             cleanupCts = new CancellationTokenSource();
             jobLockCounts = new Dictionary<long, int>();
         }
References Tgstation.Server.Host.Components.Compiler.DmbFactory.cleanupCts, Tgstation.Server.Host.Components.Compiler.DmbFactory.cleanupTask, Tgstation.Server.Host.Components.Compiler.DmbFactory.databaseContextFactory, Tgstation.Server.Host.Components.Compiler.DmbFactory.instance, Tgstation.Server.Host.Components.Compiler.DmbFactory.ioManager, Tgstation.Server.Host.Components.Compiler.DmbFactory.jobLockCounts, Tgstation.Server.Host.Components.Compiler.DmbFactory.logger, and Tgstation.Server.Host.Components.Compiler.DmbFactory.newerDmbTcs.
Member Function Documentation
CleanJob()
void Tgstation.Server.Host.Components.Compiler.DmbFactory.CleanJob (CompileJob job) private
Delete the Api.Models.Internal.CompileJob.DirectoryName of job
Parameters
job The CompileJob to clean
Definition at line 104 of file DmbFactory.cs.
         {
             async Task HandleCleanup()
             {
                 var deleteJob = ioManager.DeleteDirectory(job.DirectoryName.ToString(), cleanupCts.Token);
                 Task otherTask;
                 // lock (this) //already locked below
                 otherTask = cleanupTask;
                 await Task.WhenAll(otherTask, deleteJob).ConfigureAwait(false);
             }
             lock (this)
                 if (!jobLockCounts.TryGetValue(job.Id, out var currentVal) || currentVal == 1)
                 {
                     jobLockCounts.Remove(job.Id);
                     logger.LogDebug("Cleaning compile job {0} => {1}", job.Id, job.DirectoryName);
                     cleanupTask = HandleCleanup();
                 }
                 else
                 {
                     var decremented = --jobLockCounts[job.Id];
                     logger.LogTrace("Compile job {0} lock count now: {1}", job.Id, decremented);
                 }
         }
References Tgstation.Server.Host.Components.Compiler.DmbFactory.cleanupCts, Tgstation.Server.Host.Components.Compiler.DmbFactory.cleanupTask, Tgstation.Server.Host.IO.IIOManager.DeleteDirectory(), Tgstation.Server.Api.Models.Internal.CompileJob.DirectoryName, Tgstation.Server.Api.Models.Internal.CompileJob.Id, Tgstation.Server.Host.Components.Compiler.DmbFactory.ioManager, Tgstation.Server.Host.Components.Compiler.DmbFactory.jobLockCounts, and Tgstation.Server.Host.Components.Compiler.DmbFactory.logger.
Referenced by Tgstation.Server.Host.Components.Compiler.DmbFactory.FromCompileJob().
CleanUnusedCompileJobs()
async Task Tgstation.Server.Host.Components.Compiler.DmbFactory.CleanUnusedCompileJobs (CompileJob exceptThisOne, CancellationToken cancellationToken)
Deletes all compile jobs that are inactive in the Game folder exceptThisOne
Implements Tgstation.Server.Host.Components.Compiler.IDmbFactory.
Definition at line 243 of file DmbFactory.cs.
         {
             List<long> jobIdsToSkip;
             // don't clean locked directories
             lock (this)
                 jobIdsToSkip = jobLockCounts.Select(x => x.Key).ToList();
             List<string> jobUidsToNotErase = null;
             // find the uids of locked directories
             await databaseContextFactory.UseContext(async db =>
             {
                 jobUidsToNotErase = await db.CompileJobs.Where(x => x.Job.Instance.Id == instance.Id && jobIdsToSkip.Contains(x.Id)).Select(x => x.DirectoryName.Value.ToString().ToUpperInvariant()).ToListAsync(cancellationToken).ConfigureAwait(false);
             }).ConfigureAwait(false);
             // add the other exemption
             if (exceptThisOne != null)
                 jobUidsToNotErase.Add(exceptThisOne.DirectoryName.Value.ToString().ToUpperInvariant());
             // cleanup
             await ioManager.CreateDirectory(".", cancellationToken).ConfigureAwait(false);
             var directories = await ioManager.GetDirectories(".", cancellationToken).ConfigureAwait(false);
             int deleting = 0;
             var tasks = directories.Select(async x =>
             {
                 var nameOnly = ioManager.GetFileName(x);
                 if (jobUidsToNotErase.Contains(nameOnly.ToUpperInvariant()))
                     return;
                 try
                 {
                     ++deleting;
                     await ioManager.DeleteDirectory(x, cancellationToken).ConfigureAwait(false);
                 }
                 catch (OperationCanceledException)
                 {
                     throw;
                 }
                 catch (Exception e)
                 {
                     logger.LogWarning("Error deleting directory {0}! Exception: {1}", x, e);
                 }
             }).ToList();
             if (deleting > 0)
             {
                 logger.LogDebug("Cleaning {0} unused game folders...", deleting);
                 await Task.WhenAll().ConfigureAwait(false);
             }
         }
References Tgstation.Server.Host.IO.IIOManager.CreateDirectory(), Tgstation.Server.Host.Components.Compiler.DmbFactory.databaseContextFactory, Tgstation.Server.Host.IO.IIOManager.DeleteDirectory(), Tgstation.Server.Api.Models.Internal.CompileJob.DirectoryName, Tgstation.Server.Host.IO.IIOManager.GetDirectories(), Tgstation.Server.Host.IO.IIOManager.GetFileName(), Tgstation.Server.Host.Components.Compiler.DmbFactory.instance, Tgstation.Server.Host.Components.Compiler.DmbFactory.ioManager, Tgstation.Server.Host.Components.Compiler.DmbFactory.jobLockCounts, Tgstation.Server.Host.Components.Compiler.DmbFactory.logger, and Tgstation.Server.Host.Core.IDatabaseContextFactory.UseContext().
Dispose()
void Tgstation.Server.Host.Components.Compiler.DmbFactory.Dispose ()
FromCompileJob()
async Task<IDmbProvider> Tgstation.Server.Host.Components.Compiler.DmbFactory.FromCompileJob (CompileJob compileJob, CancellationToken cancellationToken)
Gets a IDmbProvider for a given CompileJob
Implements Tgstation.Server.Host.Components.Compiler.IDmbFactory.
Definition at line 186 of file DmbFactory.cs.
         {
             if (compileJob == null)
                 throw new ArgumentNullException(nameof(compileJob));
             // ensure we have the entire compile job tree
             await databaseContextFactory.UseContext(async db => compileJob = await db.CompileJobs.Where(x => x.Id == compileJob.Id)
                 .Include(x => x.Job).ThenInclude(x => x.StartedBy)
                 .Include(x => x.RevisionInformation).ThenInclude(x => x.PrimaryTestMerge).ThenInclude(x => x.MergedBy)
                 .Include(x => x.RevisionInformation).ThenInclude(x => x.ActiveTestMerges).ThenInclude(x => x.TestMerge).ThenInclude(x => x.MergedBy)
                 .FirstAsync(cancellationToken).ConfigureAwait(false)).ConfigureAwait(false); // can't wait to see that query
             logger.LogTrace("Loading compile job {0}...", compileJob.Id);
             var providerSubmitted = false;
             var newProvider = new DmbProvider(compileJob, ioManager, () =>
             {
                 if (providerSubmitted)
                     CleanJob(compileJob);
             });
             try
             {
                 var primaryCheckTask = ioManager.FileExists(ioManager.ConcatPath(newProvider.PrimaryDirectory, newProvider.DmbName), cancellationToken);
                 var secondaryCheckTask = ioManager.FileExists(ioManager.ConcatPath(newProvider.PrimaryDirectory, newProvider.DmbName), cancellationToken);
                 if (!(await primaryCheckTask.ConfigureAwait(false) && await secondaryCheckTask.ConfigureAwait(false)))
                 {
                     logger.LogWarning("Error loading compile job, .dmb missing!");
                     return null; // omae wa mou shinderu
                 }
                 lock (this)
                 {
                     if (!jobLockCounts.TryGetValue(compileJob.Id, out int value))
                     {
                         value = 1;
                         jobLockCounts.Add(compileJob.Id, 1);
                     }
                     else
                         jobLockCounts[compileJob.Id] = ++value;
                     logger.LogTrace("Compile job {0} lock count now: {1}", compileJob.Id, value);
                     providerSubmitted = true;
                     return newProvider;
                 }
             }
             finally
             {
                 if (!providerSubmitted)
                     newProvider.Dispose();
             }
         }
References Tgstation.Server.Host.Components.Compiler.DmbFactory.CleanJob(), Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.Components.Compiler.DmbFactory.databaseContextFactory, Tgstation.Server.Host.IO.IIOManager.FileExists(), Tgstation.Server.Api.Models.Internal.CompileJob.Id, Tgstation.Server.Host.Components.Compiler.DmbFactory.ioManager, Tgstation.Server.Host.Components.Compiler.DmbFactory.jobLockCounts, Tgstation.Server.Host.Components.Compiler.DmbFactory.logger, and Tgstation.Server.Host.Core.IDatabaseContextFactory.UseContext().
Referenced by Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.HandlerMonitorWakeup(), and Tgstation.Server.Host.Components.Compiler.DmbFactory.LoadCompileJob().
LoadCompileJob()
async Task Tgstation.Server.Host.Components.Compiler.DmbFactory.LoadCompileJob (CompileJob job, CancellationToken cancellationToken)
Load a new job into the ICompileJobConsumer
Implements Tgstation.Server.Host.Components.Compiler.ICompileJobConsumer.
Definition at line 131 of file DmbFactory.cs.
         {
             if (job == null)
                 throw new ArgumentNullException(nameof(job));
             var newProvider = await FromCompileJob(job, cancellationToken).ConfigureAwait(false);
             if (newProvider == null)
                 return;
             lock (this)
             {
                 nextDmbProvider?.Dispose();
                 nextDmbProvider = newProvider;
                 newerDmbTcs.SetResult(nextDmbProvider);
                 newerDmbTcs = new TaskCompletionSource<object>();
             }
         }
References Tgstation.Server.Host.Components.Compiler.DmbFactory.FromCompileJob(), Tgstation.Server.Host.Components.Compiler.DmbFactory.newerDmbTcs, and Tgstation.Server.Host.Components.Compiler.DmbFactory.nextDmbProvider.
LockNextDmb()
IDmbProvider Tgstation.Server.Host.Components.Compiler.DmbFactory.LockNextDmb (int lockCount)
Gets the next IDmbProvider
Implements Tgstation.Server.Host.Components.Compiler.IDmbFactory.
Definition at line 149 of file DmbFactory.cs.
         {
             if (!DmbAvailable)
                 throw new InvalidOperationException("No .dmb available!");
             if (lockCount < 0)
                 throw new ArgumentOutOfRangeException(nameof(lockCount), lockCount, "lockCount must be greater than or equal to 0!");
             lock (this)
             {
                 var jobId = nextDmbProvider.CompileJob.Id;
                 var incremented = jobLockCounts[jobId] += lockCount;
                 logger.LogTrace("Compile job {0} lock count now: {1}", jobId, incremented);
                 return nextDmbProvider;
             }
         }
References Tgstation.Server.Host.Components.IDmbProvider.CompileJob, Tgstation.Server.Host.Components.Compiler.DmbFactory.DmbAvailable, Tgstation.Server.Api.Models.Internal.CompileJob.Id, Tgstation.Server.Host.Components.Compiler.DmbFactory.jobLockCounts, Tgstation.Server.Host.Components.Compiler.DmbFactory.logger, and Tgstation.Server.Host.Components.Compiler.DmbFactory.nextDmbProvider.
Referenced by Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.HandlerMonitorWakeup(), Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.InitControllers(), and Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.InitControllers().
StartAsync()
Task Tgstation.Server.Host.Components.Compiler.DmbFactory.StartAsync (CancellationToken cancellationToken)
StopAsync()
async Task Tgstation.Server.Host.Components.Compiler.DmbFactory.StopAsync (CancellationToken cancellationToken)
Definition at line 178 of file DmbFactory.cs.
         {
             using (cancellationToken.Register(() => cleanupCts.Cancel()))
                 await cleanupTask.ConfigureAwait(false);
         }
References Tgstation.Server.Host.Components.Compiler.DmbFactory.cleanupCts, and Tgstation.Server.Host.Components.Compiler.DmbFactory.cleanupTask.
Member Data Documentation
cleanupCts
readonly CancellationTokenSource Tgstation.Server.Host.Components.Compiler.DmbFactory.cleanupCts private
The CancellationTokenSource for cleanupTask
Definition at line 55 of file DmbFactory.cs.
Referenced by Tgstation.Server.Host.Components.Compiler.DmbFactory.CleanJob(), Tgstation.Server.Host.Components.Compiler.DmbFactory.DmbFactory(), and Tgstation.Server.Host.Components.Compiler.DmbFactory.StopAsync().
cleanupTask
Task Tgstation.Server.Host.Components.Compiler.DmbFactory.cleanupTask private
Task representing calls to CleanJob(CompileJob)
Definition at line 65 of file DmbFactory.cs.
Referenced by Tgstation.Server.Host.Components.Compiler.DmbFactory.CleanJob(), Tgstation.Server.Host.Components.Compiler.DmbFactory.DmbFactory(), and Tgstation.Server.Host.Components.Compiler.DmbFactory.StopAsync().
databaseContextFactory
readonly IDatabaseContextFactory Tgstation.Server.Host.Components.Compiler.DmbFactory.databaseContextFactory private
The IDatabaseContextFactory for the DmbFactory
Definition at line 35 of file DmbFactory.cs.
Referenced by Tgstation.Server.Host.Components.Compiler.DmbFactory.CleanUnusedCompileJobs(), Tgstation.Server.Host.Components.Compiler.DmbFactory.DmbFactory(), and Tgstation.Server.Host.Components.Compiler.DmbFactory.FromCompileJob().
DmbAvailable
bool Tgstation.Server.Host.Components.Compiler.DmbFactory.DmbAvailable => nextDmbProvider != null
Definition at line 30 of file DmbFactory.cs.
Referenced by Tgstation.Server.Host.Components.Compiler.DmbFactory.LockNextDmb().
instance
readonly Api.Models.Instance Tgstation.Server.Host.Components.Compiler.DmbFactory.instance private
The Api.Models.Instance for the DmbFactory
Definition at line 50 of file DmbFactory.cs.
Referenced by Tgstation.Server.Host.Components.Compiler.DmbFactory.CleanUnusedCompileJobs(), and Tgstation.Server.Host.Components.Compiler.DmbFactory.DmbFactory().
ioManager
readonly IIOManager Tgstation.Server.Host.Components.Compiler.DmbFactory.ioManager private
The IIOManager for the DmbFactory
Definition at line 40 of file DmbFactory.cs.
Referenced by Tgstation.Server.Host.Components.Compiler.DmbFactory.CleanJob(), Tgstation.Server.Host.Components.Compiler.DmbFactory.CleanUnusedCompileJobs(), Tgstation.Server.Host.Components.Compiler.DmbFactory.DmbFactory(), and Tgstation.Server.Host.Components.Compiler.DmbFactory.FromCompileJob().
jobLockCounts
readonly IDictionary<long, int> Tgstation.Server.Host.Components.Compiler.DmbFactory.jobLockCounts private
Map of CompileJob.JobIds to locks on them.
Definition at line 60 of file DmbFactory.cs.
Referenced by Tgstation.Server.Host.Components.Compiler.DmbFactory.CleanJob(), Tgstation.Server.Host.Components.Compiler.DmbFactory.CleanUnusedCompileJobs(), Tgstation.Server.Host.Components.Compiler.DmbFactory.DmbFactory(), Tgstation.Server.Host.Components.Compiler.DmbFactory.FromCompileJob(), and Tgstation.Server.Host.Components.Compiler.DmbFactory.LockNextDmb().
logger
readonly ILogger<DmbFactory> Tgstation.Server.Host.Components.Compiler.DmbFactory.logger private
The ILogger for the DmbFactory
Definition at line 45 of file DmbFactory.cs.
Referenced by Tgstation.Server.Host.Components.Compiler.DmbFactory.CleanJob(), Tgstation.Server.Host.Components.Compiler.DmbFactory.CleanUnusedCompileJobs(), Tgstation.Server.Host.Components.Compiler.DmbFactory.DmbFactory(), Tgstation.Server.Host.Components.Compiler.DmbFactory.FromCompileJob(), and Tgstation.Server.Host.Components.Compiler.DmbFactory.LockNextDmb().
newerDmbTcs
TaskCompletionSource<object> Tgstation.Server.Host.Components.Compiler.DmbFactory.newerDmbTcs private
TaskCompletionSource<TResult> resulting in the latest DmbProvider yet to exist
Definition at line 70 of file DmbFactory.cs.
Referenced by Tgstation.Server.Host.Components.Compiler.DmbFactory.DmbFactory(), and Tgstation.Server.Host.Components.Compiler.DmbFactory.LoadCompileJob().
nextDmbProvider
IDmbProvider Tgstation.Server.Host.Components.Compiler.DmbFactory.nextDmbProvider private
The latest DmbProvider
Definition at line 75 of file DmbFactory.cs.
Referenced by Tgstation.Server.Host.Components.Compiler.DmbFactory.LoadCompileJob(), and Tgstation.Server.Host.Components.Compiler.DmbFactory.LockNextDmb().
Property Documentation
OnNewerDmb
Task Tgstation.Server.Host.Components.Compiler.DmbFactory.OnNewerDmb get
Definition at line 21 of file DmbFactory.cs.
         {
             get
             {
                 lock (this)
                     return newerDmbTcs.Task;
             }
         }
Referenced by Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.MonitorLifetimes(), and Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.MonitorLifetimes().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Compiler/DmbFactory.cs