tgstation-server: Tgstation.Server.Host.Components.Chat.ChatManager Class Reference
Tgstation.Server.Host.Components.Chat.ChatManager Class Reference
Public Member Functions
ChatManager (IProviderFactory providerFactory, IIOManager ioManager, ICommandFactory commandFactory, IServerControl serverControl, IAsyncDelayer asyncDelayer, ILoggerFactory loggerFactory, ILogger< ChatManager > logger, IEnumerable< Models.ChatBot > initialChatBots)
Construct a ChatManager
void Dispose ()
async Task ChangeChannels (long connectionId, IEnumerable< Api.Models.ChatChannel > newChannels, CancellationToken cancellationToken)
Change chat channels
async Task ChangeSettings (ChatBot newSettings, CancellationToken cancellationToken)
Change chat settings. If the ChatBot.Id is not currently in use, a new connection will be made instead
Task SendMessage (string message, IEnumerable< ulong > channelIds, CancellationToken cancellationToken)
Send a chat message to a given set of channelIds
Task SendWatchdogMessage (string message, bool adminOnly, CancellationToken cancellationToken)
Send a chat message to configured watchdog channels
async Task< Func< string, string, Task > > SendDeploymentMessage (Models.RevisionInformation revisionInformation, Version byondVersion, DateTimeOffset?estimatedCompletionTime, string gitHubOwner, string gitHubRepo, bool localCommitPushed, CancellationToken cancellationToken)
Send the message for a deployment to configured deployment channels.
async Task StartAsync (CancellationToken cancellationToken)
async Task StopAsync (CancellationToken cancellationToken)
IChatTrackingContext CreateTrackingContext ()
Start tracking Commands.CustomCommands and ChannelRepresentations.
void RegisterCommandHandler (ICustomCommandHandler customCommandHandler)
Registers a customCommandHandler to use
async Task DeleteConnection (long connectionId, CancellationToken cancellationToken)
Disconnects and deletes a given connection
Task HandleRestart (Version updateVersion, CancellationToken cancellationToken)
Handle a restart of the server
Private Member Functions
async Task< IProvider > RemoveProvider (long connectionId, bool updateTrackings, CancellationToken cancellationToken)
Remove a IProvider from providers and mappedChannels optionally updating the trackingContexts as well
async Task ProcessMessage (IProvider provider, Message message, CancellationToken cancellationToken)
Processes a message
async Task MonitorMessages (CancellationToken cancellationToken)
Monitors active providers for new Messages
Private Attributes
const string CommonMention = "!tgs"
readonly IProviderFactory providerFactory
The IProviderFactory for the ChatManager
readonly IIOManager ioManager
The IIOManager for the ChatManager
readonly ICommandFactory commandFactory
The ICommandFactory for the ChatManager
readonly IRestartRegistration restartRegistration
The IRestartRegistration for the ChatManager
readonly IAsyncDelayer asyncDelayer
The IAsyncDelayer for the ChatManager
readonly ILoggerFactory loggerFactory
The ILoggerFactory for the ChatManager
readonly ILogger< ChatManager > logger
The ILogger for the ChatManager
readonly IDictionary< string, ICommand > builtinCommands
Unchanging ICommands in the ChatManager mapped by ICommand.Name
readonly IDictionary< long, IProvider > providers
Map of IProviders in use, keyed by ChatBot.Id
readonly IDictionary< ulong, ChannelMapping > mappedChannels
Map of ChannelRepresentation.RealIds to ChannelMappings
readonly IList< IChatTrackingContext > trackingContexts
The active IChatTrackingContexts for the ChatManager
readonly CancellationTokenSource handlerCts
The CancellationTokenSource for chatHandler
readonly List< Models.ChatBot > activeChatBots
The active Models.ChatBot for the ChatManager
readonly object synchronizationLock
Used for various lock statements throughout this .
ICustomCommandHandler customCommandHandler
The ICustomCommandHandler for the ChangeChannels(long, IEnumerable<Api.Models.ChatChannel>, CancellationToken)
Task chatHandler
The Task that monitors incoming chat messages
TaskCompletionSource< object > connectionsUpdated
The TaskCompletionSource<TResult> that completes when ChatBots change
ulong channelIdCounter
Used for remapping ChannelRepresentation.RealIds
long messagesProcessed
The number of Messages processed.
bool started
If StartAsync(CancellationToken) has been called
Detailed Description
Definition at line 21 of file ChatManager.cs.
Constructor & Destructor Documentation
Tgstation.Server.Host.Components.Chat.ChatManager.ChatManager (IProviderFactory providerFactory, IIOManager ioManager, ICommandFactory commandFactory, IServerControl serverControl, IAsyncDelayer asyncDelayer, ILoggerFactory loggerFactory, ILogger< ChatManager > logger, IEnumerable< Models.ChatBot > initialChatBots)
Construct a ChatManager
Parameters
providerFactory The value of providerFactory
ioManager The value of ioManager
commandFactory The value of commandFactory
serverControl The IServerControl to populate restartRegistration with
asyncDelayer The value of asyncDelayer
loggerFactory The value of loggerFactory
logger The value of logger
initialChatBots The IEnumerable<T> used to populate activeChatBots
Definition at line 136 of file ChatManager.cs.
References Tgstation.Server.Host.Core.IServerControl.RegisterForRestart().
         {
             this.providerFactory = providerFactory ?? throw new ArgumentNullException(nameof(providerFactory));
             this.ioManager = ioManager ?? throw new ArgumentNullException(nameof(ioManager));
             this.commandFactory = commandFactory ?? throw new ArgumentNullException(nameof(commandFactory));
             if (serverControl == null)
                 throw new ArgumentNullException(nameof(serverControl));
             this.asyncDelayer = asyncDelayer ?? throw new ArgumentNullException(nameof(asyncDelayer));
             this.loggerFactory = loggerFactory ?? throw new ArgumentNullException(nameof(loggerFactory));
             this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
             activeChatBots = initialChatBots?.ToList() ?? throw new ArgumentNullException(nameof(initialChatBots));
             restartRegistration = serverControl.RegisterForRestart(this);
             synchronizationLock = new object();
             builtinCommands = new Dictionary<string, ICommand>();
             providers = new Dictionary<long, IProvider>();
             mappedChannels = new Dictionary<ulong, ChannelMapping>();
             trackingContexts = new List<IChatTrackingContext>();
             handlerCts = new CancellationTokenSource();
             connectionsUpdated = new TaskCompletionSource<object>();
             channelIdCounter = 1;
         }
Member Function Documentation
async Task Tgstation.Server.Host.Components.Chat.ChatManager.ChangeChannels (long connectionId, IEnumerable< Api.Models.ChatChannel > newChannels, CancellationToken cancellationToken)
Change chat channels
Implements Tgstation.Server.Host.Components.Chat.IChatManager.
Definition at line 434 of file ChatManager.cs.
References Tgstation.Server.Host.Components.Chat.ChannelMapping.IsWatchdogChannel, and Tgstation.Server.Host.Components.Chat.Providers.IProvider.MapChannels().
         {
             if (newChannels == null)
                 throw new ArgumentNullException(nameof(newChannels));
             var provider = await RemoveProvider(connectionId, false, cancellationToken).ConfigureAwait(false);
             if (provider == null)
                 return;
             var results = await provider.MapChannels(newChannels, cancellationToken).ConfigureAwait(false);
             lock (activeChatBots)
             {
                 var botToUpdate = activeChatBots.FirstOrDefault(bot => bot.Id == connectionId);
                 if (botToUpdate != null)
                     botToUpdate.Channels = newChannels
                         .Select(apiModel => new Models.ChatChannel
{
                             DiscordChannelId = apiModel.DiscordChannelId,
                             IrcChannel = apiModel.IrcChannel,
                             IsAdminChannel = apiModel.IsAdminChannel,
                             IsUpdatesChannel = apiModel.IsUpdatesChannel,
                             IsWatchdogChannel = apiModel.IsWatchdogChannel,
                             Tag = apiModel.Tag
                         })
                         .ToList();
             }
             var mappings = Enumerable.Zip(newChannels, results, (x, y) => new ChannelMapping
             {
                 IsWatchdogChannel = x.IsWatchdogChannel == true,
                 IsUpdatesChannel = x.IsUpdatesChannel == true,
                 IsAdminChannel = x.IsAdminChannel == true,
                 ProviderChannelId = y.RealId,
                 ProviderId = connectionId,
                 Channel = y
             });
             ulong baseId;
             lock (synchronizationLock)
             {
                 baseId = channelIdCounter;
                 channelIdCounter += (ulong)results.Count;
             }
             Task trackingContextUpdateTask;
             lock (mappedChannels)
             {
                 lock (providers)
                     if (!providers.TryGetValue(connectionId, out IProvider verify) || verify != provider) // aborted again
                         return;
                 foreach (var I in mappings)
                 {
                     var newId = baseId++;
                     logger.LogTrace("Mapping channel {0}:{1} as {2}", I.Channel.ConnectionName, I.Channel.FriendlyName, newId);
                     mappedChannels.Add(newId, I);
                     I.Channel.RealId = newId;
                 }
                 lock (trackingContexts)
                     trackingContextUpdateTask = Task.WhenAll(
                         trackingContexts.Select(
                             x => x.UpdateChannels(
                                 mappedChannels.Select(y => y.Value.Channel).ToList(),
                                 cancellationToken)));
             }
             await trackingContextUpdateTask.ConfigureAwait(false);
         }
async Task Tgstation.Server.Host.Components.Chat.ChatManager.ChangeSettings (ChatBot newSettings, CancellationToken cancellationToken)
Change chat settings. If the ChatBot.Id is not currently in use, a new connection will be made instead
Implements Tgstation.Server.Host.Components.Chat.IChatManager.
Definition at line 502 of file ChatManager.cs.
References Tgstation.Server.Host.Components.Chat.Providers.IProvider.Connect(), Tgstation.Server.Host.Components.Chat.Providers.IProvider.Disconnect(), Tgstation.Server.Api.Models.Internal.ChatBot.Enabled, Tgstation.Server.Api.Models.Internal.ChatBot.Id, and Tgstation.Server.Host.Components.Chat.Providers.IProvider.SetReconnectInterval().
         {
             if (newSettings == null)
                 throw new ArgumentNullException(nameof(newSettings));
             IProvider provider;
             async Task DisconnectProvider(IProvider p)
             {
                 try
                 {
                     await p.Disconnect(cancellationToken).ConfigureAwait(false);
                 }
                 finally
                 {
                     p.Dispose();
                 }
             }
             Task disconnectTask;
             lock (providers)
             {
                 // raw settings changes forces a rebuild of the provider
                 if (providers.TryGetValue(newSettings.Id, out provider))
                 {
                     providers.Remove(newSettings.Id);
                     disconnectTask = DisconnectProvider(provider);
                 }
                 else
                     disconnectTask = Task.CompletedTask;
                 if (newSettings.Enabled.Value)
                 {
                     provider = providerFactory.CreateProvider(newSettings);
                     providers.Add(newSettings.Id, provider);
                 }
             }
             lock (mappedChannels)
                 foreach (var I in mappedChannels.Where(x => x.Value.ProviderId == newSettings.Id).Select(x => x.Key).ToList())
                     mappedChannels.Remove(I);
             await disconnectTask.ConfigureAwait(false);
             if (started)
             {
                 if (newSettings.Enabled.Value)
                     await provider.Connect(cancellationToken).ConfigureAwait(false);
                 lock (synchronizationLock)
                 {
                     // same thread shennanigans
                     var oldOne = connectionsUpdated;
                     connectionsUpdated = new TaskCompletionSource<object>();
                     oldOne.SetResult(null);
                 }
             }
             Task reconnectionUpdateTask = Task.CompletedTask;
             lock (activeChatBots)
             {
                 var originalChatBot = activeChatBots.FirstOrDefault(bot => bot.Id == newSettings.Id);
                 if (originalChatBot != null)
                 {
                     if (originalChatBot.ReconnectionInterval != newSettings.ReconnectionInterval)
                         reconnectionUpdateTask = provider.SetReconnectInterval(newSettings.ReconnectionInterval.Value);
                     activeChatBots.Remove(originalChatBot);
                 }
                 activeChatBots.Add(new Models.ChatBot
                 {
                     Id = newSettings.Id,
                     ConnectionString = newSettings.ConnectionString,
                     Enabled = newSettings.Enabled,
                     Name = newSettings.Name,
                     ReconnectionInterval = newSettings.ReconnectionInterval,
                     Provider = newSettings.Provider
                 });
             }
             await reconnectionUpdateTask.ConfigureAwait(false);
         }
IChatTrackingContext Tgstation.Server.Host.Components.Chat.ChatManager.CreateTrackingContext ()
Start tracking Commands.CustomCommands and ChannelRepresentations.
Implements Tgstation.Server.Host.Components.Chat.IChatManager.
Definition at line 711 of file ChatManager.cs.
         {
             if (customCommandHandler == null)
                 throw new InvalidOperationException("RegisterCommandHandler() hasn't been called!");
             IChatTrackingContext context = null;
             lock (mappedChannels)
                 context = new ChatTrackingContext(
                     customCommandHandler,
                     mappedChannels.Select(y => y.Value.Channel),
                     loggerFactory.CreateLogger<ChatTrackingContext>(),
                     () =>
                     {
                         lock (trackingContexts)
                             trackingContexts.Remove(context);
                     });
             lock (trackingContexts)
                 trackingContexts.Add(context);
             return context;
         }
async Task Tgstation.Server.Host.Components.Chat.ChatManager.DeleteConnection (long connectionId, CancellationToken cancellationToken)
Disconnects and deletes a given connection
Implements Tgstation.Server.Host.Components.Chat.IChatManager.
Definition at line 743 of file ChatManager.cs.
         {
             var provider = await RemoveProvider(connectionId, true, cancellationToken).ConfigureAwait(false);
             if (provider != null)
                 try
                 {
                     await provider.Disconnect(cancellationToken).ConfigureAwait(false);
                 }
                 finally
                 {
                     provider.Dispose();
                 }
         }
void Tgstation.Server.Host.Components.Chat.ChatManager.Dispose ()
Definition at line 162 of file ChatManager.cs.
         {
             restartRegistration.Dispose();
             handlerCts.Dispose();
             foreach (var I in providers)
                 I.Value.Dispose();
         }
Task Tgstation.Server.Host.Components.Chat.ChatManager.HandleRestart (Version updateVersion, CancellationToken cancellationToken)
Handle a restart of the server
Implements Tgstation.Server.Host.Core.IRestartHandler.
Definition at line 758 of file ChatManager.cs.
         {
             var message = updateVersion == null ? "TGS: Restart requested..." : String.Format(CultureInfo.InvariantCulture, "TGS: Updating to version {0}...", updateVersion);
             List<ulong> wdChannels;
             lock (mappedChannels) // so it doesn't change while we're using it
                 wdChannels = mappedChannels.Select(x => x.Key).ToList();
             return SendMessage(message, wdChannels, cancellationToken);
         }
async Task Tgstation.Server.Host.Components.Chat.ChatManager.MonitorMessages (CancellationToken cancellationToken) private
Monitors active providers for new Messages
Parameters
cancellationToken The CancellationToken for the operation
Returns
A Task representing the running operation
Definition at line 383 of file ChatManager.cs.
         {
             var messageTasks = new Dictionary<IProvider, Task<Message>>();
             try
             {
                 while (!cancellationToken.IsCancellationRequested)
                 {
                     // prune disconnected providers
                     foreach (var I in messageTasks.Where(x => !x.Key.Connected).ToList())
                         messageTasks.Remove(I.Key);
                     // add new ones
                     Task updatedTask;
                     lock (synchronizationLock)
                         updatedTask = connectionsUpdated.Task;
                     lock (providers)
                         foreach (var I in providers)
                             if (I.Value.Connected && !messageTasks.ContainsKey(I.Value))
                                 messageTasks.Add(I.Value, I.Value.NextMessage(cancellationToken));
                     if (messageTasks.Count == 0)
                     {
                         await asyncDelayer.Delay(TimeSpan.FromSeconds(1), cancellationToken).ConfigureAwait(false);
                         continue;
                     }
                     // wait for a message
                     await Task.WhenAny(updatedTask, Task.WhenAny(messageTasks.Select(x => x.Value))).ConfigureAwait(false);
                     // process completed ones
                     foreach (var I in messageTasks.Where(x => x.Value.IsCompleted).ToList())
                     {
                         var message = await I.Value.ConfigureAwait(false);
                         var messageNumber = Interlocked.Increment(ref messagesProcessed);
                         using (LogContext.PushProperty("ChatMessage", messageNumber))
                             await ProcessMessage(I.Key, message, cancellationToken).ConfigureAwait(false);
                         messageTasks.Remove(I.Key);
                     }
                 }
             }
             catch (OperationCanceledException)
             {
                 logger.LogTrace("Message processing loop cancelled!");
             }
             catch (Exception e)
             {
                 logger.LogError("Message monitor crashed! Exception: {0}", e);
             }
         }
async Task Tgstation.Server.Host.Components.Chat.ChatManager.ProcessMessage (IProvider provider, Message message, CancellationToken cancellationToken) private
Processes a message
Parameters
provider The IProvider who recevied message
message The Message to process. If , this indicates the provider reconnected.
cancellationToken The CancellationToken for the operation
Returns
A Task representing the running operation
Definition at line 212 of file ChatManager.cs.
References Tgstation.Server.Host.Components.Chat.Providers.IProvider.BotMention, Tgstation.Server.Host.Components.Chat.ChatUser.Channel, Tgstation.Server.Host.Components.Chat.Providers.IProvider.Connected, Tgstation.Server.Host.Components.Chat.ChannelRepresentation.ConnectionName, Tgstation.Server.Host.Components.Chat.Providers.Message.Content, Tgstation.Server.Host.Components.Chat.ChatUser.FriendlyName, Tgstation.Server.Host.Components.Chat.ChannelRepresentation.Id, Tgstation.Server.Host.Components.Chat.ChannelRepresentation.IsAdminChannel, Tgstation.Server.Host.Components.Chat.ChannelRepresentation.IsPrivateChannel, Tgstation.Server.Host.Components.Chat.ChannelRepresentation.RealId, Tgstation.Server.Host.Components.Chat.ChannelRepresentation.Tag, and Tgstation.Server.Host.Components.Chat.Providers.Message.User.
         {
             // provider reconnected, remap channels.
             if (message == null)
             {
                 IEnumerable<Api.Models.ChatChannel> channelsToMap;
                 lock (activeChatBots)
                     channelsToMap = activeChatBots.FirstOrDefault()?.Channels;
                 if (channelsToMap?.Any() ?? false)
                 {
                     long providerId;
                     lock (providers)
                         providerId = providers.Where(x => x.Value == provider).Select(x => x.Key).First();
                     await ChangeChannels(providerId, channelsToMap, cancellationToken).ConfigureAwait(false);
                 }
                 return;
             }
             // map the channel if it's private and we haven't seen it
             lock (providers)
             {
                 var providerId = providers.Where(x => x.Value == provider).Select(x => x.Key).First();
                 var enumerable = mappedChannels.Where(x => x.Value.ProviderId == providerId && x.Value.ProviderChannelId == message.User.Channel.RealId);
                 if (message.User.Channel.IsPrivateChannel)
                     lock (mappedChannels)
                     {
                         if (!provider.Connected)
                             return;
                         if (!enumerable.Any())
{
                             ulong newId;
                             lock (synchronizationLock)
                                 newId = channelIdCounter++;
                             logger.LogTrace(
                                 "Mapping private channel {0}:{1} as {2}",
                                 message.User.Channel.ConnectionName,
                                 message.User.FriendlyName,
                                 newId);
                             mappedChannels.Add(newId, new ChannelMapping
{
                                 IsWatchdogChannel = false,
                                 ProviderChannelId = message.User.Channel.RealId,
                                 ProviderId = providerId,
                                 Channel = message.User.Channel
                             });
                             message.User.Channel.RealId = newId;
                         }
                         else
                             message.User.Channel.RealId = enumerable.First().Key;
                     }
                 else
                 {
                     // need to add tag and isAdminChannel
                     var mapping = enumerable.First().Value;
                     message.User.Channel.Id = mapping.Channel.Id;
                     message.User.Channel.Tag = mapping.Channel.Tag;
                     message.User.Channel.IsAdminChannel = mapping.Channel.IsAdminChannel;
                 }
             }
             var splits = new List<string>(message.Content.Trim().Split(' '));
             var address = splits[0];
             if (address.Length > 1 && (address.Last() == ':' || address.Last() == ','))
                 address = address[0..^1];
             address = address.ToUpperInvariant();
             var addressed = address == CommonMention.ToUpperInvariant() || address == provider.BotMention.ToUpperInvariant();
             // no mention
             if (!addressed && !message.User.Channel.IsPrivateChannel)
                 return;
             logger.LogTrace("Chat command: {0}. User (True provider Id): {1}", message.Content, JsonConvert.SerializeObject(message.User));
             if (addressed)
                 splits.RemoveAt(0);
             if (splits.Count == 0)
             {
                 // just a mention
                 await SendMessage("Hi!", new List<ulong> { message.User.Channel.RealId }, cancellationToken).ConfigureAwait(false);
                 return;
             }
             var command = splits[0].ToUpperInvariant();
             splits.RemoveAt(0);
             var arguments = String.Join(" ", splits);
             try
             {
                 ICommand GetCommand(string commandName)
                 {
                     if (!builtinCommands.TryGetValue(commandName, out var handler))
                     {
                         handler = trackingContexts
                             .Where(x => x.CustomCommands != null)
                             .SelectMany(x => x.CustomCommands)
                             .Where(x => x.Name.ToUpperInvariant() == commandName)
                             .FirstOrDefault();
                     }
                     return handler;
                 }
                 const string UnknownCommandMessage = "Unknown command! Type '?' or 'help' for available commands.";
                 if (command == "HELP" || command == "?")
                 {
                     string helpText;
                     if (splits.Count == 0)
                     {
                         var allCommands = builtinCommands.Select(x => x.Value).ToList();
                         allCommands.AddRange(
                             trackingContexts
                                 .Where(x => x.CustomCommands != null)
                                 .SelectMany(
                                     x => x.CustomCommands));
                         helpText = String.Format(CultureInfo.InvariantCulture, "Available commands (Type '?' or 'help' and then a command name for more details): {0}", String.Join(", ", allCommands.Select(x => x.Name)));
                     }
                     else
                     {
                         var helpHandler = GetCommand(splits[0].ToUpperInvariant());
                         if (helpHandler != default)
                             helpText = String.Format(CultureInfo.InvariantCulture, "{0}: {1}{2}", helpHandler.Name, helpHandler.HelpText, helpHandler.AdminOnly ? " - May only be used in admin channels" : String.Empty);
                         else
                             helpText = UnknownCommandMessage;
                     }
                     await SendMessage(helpText, new List<ulong> { message.User.Channel.RealId }, cancellationToken).ConfigureAwait(false);
                     return;
                 }
                 var commandHandler = GetCommand(command);
                 if (commandHandler == default)
                 {
                     await SendMessage(UnknownCommandMessage, new List<ulong> { message.User.Channel.RealId }, cancellationToken).ConfigureAwait(false);
                     return;
                 }
                 if (commandHandler.AdminOnly && !message.User.Channel.IsAdminChannel)
                 {
                     await SendMessage("Use this command in an admin channel!", new List<ulong> { message.User.Channel.RealId }, cancellationToken).ConfigureAwait(false);
                     return;
                 }
                 var result = await commandHandler.Invoke(arguments, message.User, cancellationToken).ConfigureAwait(false);
                 if (result != null)
                     await SendMessage(result, new List<ulong> { message.User.Channel.RealId }, cancellationToken).ConfigureAwait(false);
             }
             catch (OperationCanceledException)
             {
                 throw;
             }
             catch (Exception e)
             {
                 // error bc custom commands should reply about why it failed
                 logger.LogError("Error processing chat command: {0}", e);
                 await SendMessage("Internal error processing command!", new List<ulong> { message.User.Channel.RealId }, cancellationToken).ConfigureAwait(false);
             }
         }
void Tgstation.Server.Host.Components.Chat.ChatManager.RegisterCommandHandler (ICustomCommandHandler customCommandHandler)
Registers a customCommandHandler to use
Implements Tgstation.Server.Host.Components.Chat.IChatManager.
Definition at line 735 of file ChatManager.cs.
         {
             if (this.customCommandHandler != null)
                 throw new InvalidOperationException("RegisterCommandHandler() already called!");
             this.customCommandHandler = customCommandHandler ?? throw new ArgumentNullException(nameof(customCommandHandler));
         }
async Task<IProvider> Tgstation.Server.Host.Components.Chat.ChatManager.RemoveProvider (long connectionId, bool updateTrackings, CancellationToken cancellationToken) private
Remove a IProvider from providers and mappedChannels optionally updating the trackingContexts as well
Parameters
connectionId The ChatBot.Id of the IProvider to delete
updateTrackings If trackingContexts should be update
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the IProvider being removed if it exists, otherwise.
Definition at line 177 of file ChatManager.cs.
         {
             IProvider provider;
             lock (providers)
                 if (!providers.TryGetValue(connectionId, out provider))
                     return null;
             Task trackingContextsUpdateTask;
             lock (mappedChannels)
             {
                 foreach (var I in mappedChannels.Where(x => x.Value.ProviderId == connectionId).Select(x => x.Key).ToList())
                     mappedChannels.Remove(I);
                 var newMappedChannels = mappedChannels.Select(y => y.Value.Channel).ToList();
                 if (updateTrackings)
                     lock (trackingContexts)
                         trackingContextsUpdateTask = Task.WhenAll(trackingContexts.Select(x => x.UpdateChannels(newMappedChannels, cancellationToken)));
                 else
                     trackingContextsUpdateTask = Task.CompletedTask;
             }
             await trackingContextsUpdateTask.ConfigureAwait(false);
             return provider;
         }
async Task<Func<string, string, Task> > Tgstation.Server.Host.Components.Chat.ChatManager.SendDeploymentMessage (Models.RevisionInformation revisionInformation, Version byondVersion, DateTimeOffset? estimatedCompletionTime, string gitHubOwner, string gitHubRepo, bool localCommitPushed, CancellationToken cancellationToken)
Send the message for a deployment to configured deployment channels.
Implements Tgstation.Server.Host.Components.Chat.IChatManager.
Definition at line 631 of file ChatManager.cs.
         {
             List<ulong> wdChannels;
             lock (mappedChannels) // so it doesn't change while we're using it
                 wdChannels = mappedChannels.Where(x => x.Value.IsUpdatesChannel).Select(x => x.Key).ToList();
             logger.LogTrace("Sending deployment message for RevisionInformation: {0}", revisionInformation.Id);
             var callbacks = new List<Func<string, string, Task>>();
             await Task.WhenAll(
                 wdChannels.Select(
                     async x =>
                     {
                         ChannelMapping channelMapping;
                         lock (mappedChannels)
                             if (!mappedChannels.TryGetValue(x, out channelMapping))
                                 return;
                         IProvider provider;
                         lock (providers)
                             if (!providers.TryGetValue(channelMapping.ProviderId, out provider))
                                 return;
                         try
{
                             var callback = await provider.SendUpdateMessage(
                                 revisionInformation,
                                 byondVersion,
                                 estimatedCompletionTime,
                                 gitHubOwner,
                                 gitHubRepo,
                                 channelMapping.ProviderChannelId,
                                 localCommitPushed,
                                 cancellationToken)
                                 .ConfigureAwait(false);
                             callbacks.Add(callback);
                         }
                         catch (Exception ex)
{
                             logger.LogWarning(
                                 "Error sending deploy message to provider {0}! Exception: {1}",
                                 channelMapping.ProviderId,
                                 ex);
                         }
                     }))
                 .ConfigureAwait(false);
             return (errorMessage, dreamMakerOutput) => Task.WhenAll(callbacks.Select(x => x(errorMessage, dreamMakerOutput)));
         }
Task Tgstation.Server.Host.Components.Chat.ChatManager.SendMessage (string message, IEnumerable< ulong > channelIds, CancellationToken cancellationToken)
Send a chat message to a given set of channelIds
Implements Tgstation.Server.Host.Components.Chat.IChatManager.
Definition at line 584 of file ChatManager.cs.
         {
             if (message == null)
                 throw new ArgumentNullException(nameof(message));
             if (channelIds == null)
                 throw new ArgumentNullException(nameof(channelIds));
             logger.LogTrace("Chat send \"{0}\" to channels: {1}", message, String.Join(", ", channelIds));
             return Task.WhenAll(channelIds.Select(x =>
             {
                 ChannelMapping channelMapping;
                 lock (mappedChannels)
                     if (!mappedChannels.TryGetValue(x, out channelMapping))
                         return Task.CompletedTask;
                 IProvider provider;
                 lock (providers)
                     if (!providers.TryGetValue(channelMapping.ProviderId, out provider))
                         return Task.CompletedTask;
                 return provider.SendMessage(channelMapping.ProviderChannelId, message, cancellationToken);
             }));
         }
Task Tgstation.Server.Host.Components.Chat.ChatManager.SendWatchdogMessage (string message, bool adminOnly, CancellationToken cancellationToken)
Send a chat message to configured watchdog channels
Implements Tgstation.Server.Host.Components.Chat.IChatManager.
Definition at line 608 of file ChatManager.cs.
         {
             List<ulong> wdChannels = null;
             message = String.Format(CultureInfo.InvariantCulture, "WD: {0}", message);
             // so it doesn't change while we're using it
             lock (mappedChannels)
             {
                 if (adminOnly)
                 {
                     wdChannels = mappedChannels.Where(x => x.Value.IsAdminChannel).Select(x => x.Key).ToList();
                     if (wdChannels.Count == 0)
                         adminOnly = false;
                 }
                 if (!adminOnly)
                     wdChannels = mappedChannels.Where(x => x.Value.IsWatchdogChannel).Select(x => x.Key).ToList();
             }
             return SendMessage(message, wdChannels, cancellationToken);
         }
async Task Tgstation.Server.Host.Components.Chat.ChatManager.StartAsync (CancellationToken cancellationToken)
Definition at line 689 of file ChatManager.cs.
         {
             foreach (var I in commandFactory.GenerateCommands())
                 builtinCommands.Add(I.Name.ToUpperInvariant(), I);
             var initialChatBots = activeChatBots.ToList();
             await Task.WhenAll(initialChatBots.Select(x => ChangeSettings(x, cancellationToken))).ConfigureAwait(false);
             await Task.WhenAll(providers.Select(x => x.Value).Select(x => x.Connect(cancellationToken))).ConfigureAwait(false);
             await Task.WhenAll(initialChatBots.Select(x => ChangeChannels(x.Id, x.Channels, cancellationToken))).ConfigureAwait(false);
             chatHandler = MonitorMessages(handlerCts.Token);
             started = true;
         }
async Task Tgstation.Server.Host.Components.Chat.ChatManager.StopAsync (CancellationToken cancellationToken)
Definition at line 702 of file ChatManager.cs.
         {
             handlerCts.Cancel();
             if (chatHandler != null)
                 await chatHandler.ConfigureAwait(false);
             await Task.WhenAll(providers.Select(x => x.Value).Select(x => x.Disconnect(cancellationToken))).ConfigureAwait(false);
         }
Member Data Documentation
readonly List<Models.ChatBot> Tgstation.Server.Host.Components.Chat.ChatManager.activeChatBots private
The active Models.ChatBot for the ChatManager
Definition at line 88 of file ChatManager.cs.
readonly IAsyncDelayer Tgstation.Server.Host.Components.Chat.ChatManager.asyncDelayer private
The IAsyncDelayer for the ChatManager
Definition at line 48 of file ChatManager.cs.
readonly IDictionary<string, ICommand> Tgstation.Server.Host.Components.Chat.ChatManager.builtinCommands private
Unchanging ICommands in the ChatManager mapped by ICommand.Name
Definition at line 63 of file ChatManager.cs.
ulong Tgstation.Server.Host.Components.Chat.ChatManager.channelIdCounter private
Used for remapping ChannelRepresentation.RealIds
Definition at line 113 of file ChatManager.cs.
Task Tgstation.Server.Host.Components.Chat.ChatManager.chatHandler private
The Task that monitors incoming chat messages
Definition at line 103 of file ChatManager.cs.
readonly ICommandFactory Tgstation.Server.Host.Components.Chat.ChatManager.commandFactory private
The ICommandFactory for the ChatManager
Definition at line 38 of file ChatManager.cs.
const string Tgstation.Server.Host.Components.Chat.ChatManager.CommonMention = "!tgs" private
Definition at line 23 of file ChatManager.cs.
TaskCompletionSource<object> Tgstation.Server.Host.Components.Chat.ChatManager.connectionsUpdated private
The TaskCompletionSource<TResult> that completes when ChatBots change
Definition at line 108 of file ChatManager.cs.
ICustomCommandHandler Tgstation.Server.Host.Components.Chat.ChatManager.customCommandHandler private
The ICustomCommandHandler for the ChangeChannels(long, IEnumerable<Api.Models.ChatChannel>, CancellationToken)
Definition at line 98 of file ChatManager.cs.
readonly CancellationTokenSource Tgstation.Server.Host.Components.Chat.ChatManager.handlerCts private
The CancellationTokenSource for chatHandler
Definition at line 83 of file ChatManager.cs.
readonly IIOManager Tgstation.Server.Host.Components.Chat.ChatManager.ioManager private
The IIOManager for the ChatManager
Definition at line 33 of file ChatManager.cs.
readonly ILogger<ChatManager> Tgstation.Server.Host.Components.Chat.ChatManager.logger private
The ILogger for the ChatManager
Definition at line 58 of file ChatManager.cs.
readonly ILoggerFactory Tgstation.Server.Host.Components.Chat.ChatManager.loggerFactory private
The ILoggerFactory for the ChatManager
Definition at line 53 of file ChatManager.cs.
readonly IDictionary<ulong, ChannelMapping> Tgstation.Server.Host.Components.Chat.ChatManager.mappedChannels private
Map of ChannelRepresentation.RealIds to ChannelMappings
Definition at line 73 of file ChatManager.cs.
long Tgstation.Server.Host.Components.Chat.ChatManager.messagesProcessed private
The number of Messages processed.
Definition at line 118 of file ChatManager.cs.
readonly IProviderFactory Tgstation.Server.Host.Components.Chat.ChatManager.providerFactory private
The IProviderFactory for the ChatManager
Definition at line 28 of file ChatManager.cs.
readonly IDictionary<long, IProvider> Tgstation.Server.Host.Components.Chat.ChatManager.providers private
Map of IProviders in use, keyed by ChatBot.Id
Definition at line 68 of file ChatManager.cs.
readonly IRestartRegistration Tgstation.Server.Host.Components.Chat.ChatManager.restartRegistration private
The IRestartRegistration for the ChatManager
Definition at line 43 of file ChatManager.cs.
bool Tgstation.Server.Host.Components.Chat.ChatManager.started private
If StartAsync(CancellationToken) has been called
Definition at line 123 of file ChatManager.cs.
readonly object Tgstation.Server.Host.Components.Chat.ChatManager.synchronizationLock private
Used for various lock statements throughout this .
Definition at line 93 of file ChatManager.cs.
readonly IList<IChatTrackingContext> Tgstation.Server.Host.Components.Chat.ChatManager.trackingContexts private
The active IChatTrackingContexts for the ChatManager
Definition at line 78 of file ChatManager.cs.
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Chat/ChatManager.cs