tgstation-server: Tgstation.Server.Host.GraphQL.Subscriptions.UserSubscriptions Class Reference
Tgstation.Server.Host.GraphQL.Subscriptions.UserSubscriptions Class Reference sealed
Subscriptions for User.
Public Member Functions
ValueTask< ISourceStream< User > > UserUpdatedStream ([ID(nameof(User))] long? userId, [Service] ITopicEventReceiver receiver, CancellationToken cancellationToken)
ISourceStream for UserUpdated(User).
User UserUpdated ([EventMessage] User user)
Receive an update for all User changes.
ValueTask< ISourceStream< User > > CurrentUserUpdatedStream ([Service] ITopicEventReceiver receiver, [Service] IAuthenticationContext authenticationContext, CancellationToken cancellationToken)
ISourceStream for CurrentUserUpdated(User).
User CurrentUserUpdated ([EventMessage] User user)
Receive an update to the logged in User when it is changed.
Static Public Member Functions
static IEnumerable< string > UserUpdatedTopics (long userId)
Get the names of the topics to send to when a Models.User is updated.
Static Private Member Functions
static string SpecificUserUpdatedTopic (long userId)
The name of the topic for when a specific Models.User is updated.
Static Private Attributes
const string UserUpdatedTopic = "UserUpdated"
The name of the topic for when any user is updated.
Detailed Description
Subscriptions for User.
Definition at line 22 of file UserSubscriptions.cs.
Member Function Documentation
CurrentUserUpdated()
User Tgstation.Server.Host.GraphQL.Subscriptions.UserSubscriptions.CurrentUserUpdated ([EventMessage] User user)
Receive an update to the logged in User when it is changed.
Parameters
user The Models.User received from the publisher.
Returns
The updated User.
Definition at line 102 of file UserSubscriptions.cs.
        {
            ArgumentNullException.ThrowIfNull(user);
            return user;
        }
References Tgstation.Server.Api.Rights.List.
CurrentUserUpdatedStream()
ValueTask< ISourceStream< User > > Tgstation.Server.Host.GraphQL.Subscriptions.UserSubscriptions.CurrentUserUpdatedStream ([Service] ITopicEventReceiver receiver, [Service] IAuthenticationContext authenticationContext, CancellationToken cancellationToken)
ISourceStream for CurrentUserUpdated(User).
Parameters
receiver The ITopicEventReceiver.
authenticationContext The IAuthenticationContext for the request.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in updates for the current User.
Definition at line 85 of file UserSubscriptions.cs.
        {
            ArgumentNullException.ThrowIfNull(receiver);
            ArgumentNullException.ThrowIfNull(authenticationContext);
            return receiver.SubscribeAsync<User>(SpecificUserUpdatedTopic(Models.ModelExtensions.Require(authenticationContext.User, user => user.Id)), cancellationToken);
        }
References Tgstation.Server.Api.Rights.List, and Tgstation.Server.Host.GraphQL.Subscriptions.UserSubscriptions.SpecificUserUpdatedTopic().
SpecificUserUpdatedTopic()
static string Tgstation.Server.Host.GraphQL.Subscriptions.UserSubscriptions.SpecificUserUpdatedTopic (long userId) static private
The name of the topic for when a specific Models.User is updated.
Parameters
userId The Api.Models.EntityId.Id of the updated Models.User.
Returns
The topic string.
Referenced by Tgstation.Server.Host.GraphQL.Subscriptions.UserSubscriptions.CurrentUserUpdatedStream(), Tgstation.Server.Host.GraphQL.Subscriptions.UserSubscriptions.UserUpdatedStream(), and Tgstation.Server.Host.GraphQL.Subscriptions.UserSubscriptions.UserUpdatedTopics().
UserUpdated()
User Tgstation.Server.Host.GraphQL.Subscriptions.UserSubscriptions.UserUpdated ([EventMessage] User user)
Receive an update for all User changes.
Parameters
user The Models.User received from the publisher.
Returns
The updated User.
Definition at line 72 of file UserSubscriptions.cs.
        {
            ArgumentNullException.ThrowIfNull(user);
            return user;
        }
References Tgstation.Server.Api.Rights.List.
UserUpdatedStream()
ValueTask< ISourceStream< User > > Tgstation.Server.Host.GraphQL.Subscriptions.UserSubscriptions.UserUpdatedStream ([ID(nameof(User))] long? userId, [Service] ITopicEventReceiver receiver, CancellationToken cancellationToken)
ISourceStream for UserUpdated(User).
Parameters
userId The optional Entity.Id of the User to scope updates to.
receiver The ITopicEventReceiver.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the requested User updates.
Definition at line 55 of file UserSubscriptions.cs.
        {
            ArgumentNullException.ThrowIfNull(receiver);
            var topic = userId.HasValue ? SpecificUserUpdatedTopic(userId.Value) : UserUpdatedTopic;
            return receiver.SubscribeAsync<User>(topic, cancellationToken);
        }
References Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.GraphQL.Subscriptions.UserSubscriptions.SpecificUserUpdatedTopic(), and Tgstation.Server.Host.GraphQL.Subscriptions.UserSubscriptions.UserUpdatedTopic.
UserUpdatedTopics()
static IEnumerable< string > Tgstation.Server.Host.GraphQL.Subscriptions.UserSubscriptions.UserUpdatedTopics (long userId) static
Get the names of the topics to send to when a Models.User is updated.
Parameters
userId The Api.Models.EntityId.Id of the updated Models.User.
Returns
An IEnumerable<T> of topic strings.
Definition at line 34 of file UserSubscriptions.cs.
        {
            yield return UserUpdatedTopic;
            yield return SpecificUserUpdatedTopic(userId);
        }
References Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.GraphQL.Subscriptions.UserSubscriptions.SpecificUserUpdatedTopic(), and Tgstation.Server.Host.GraphQL.Subscriptions.UserSubscriptions.UserUpdatedTopic.
Member Data Documentation
UserUpdatedTopic
const string Tgstation.Server.Host.GraphQL.Subscriptions.UserSubscriptions.UserUpdatedTopic = "UserUpdated" static private
The name of the topic for when any user is updated.
Definition at line 27 of file UserSubscriptions.cs.
Referenced by Tgstation.Server.Host.GraphQL.Subscriptions.UserSubscriptions.UserUpdatedStream(), and Tgstation.Server.Host.GraphQL.Subscriptions.UserSubscriptions.UserUpdatedTopics().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/GraphQL/Subscriptions/UserSubscriptions.cs