tgstation-server: TGServerService.TGDiscordChatProvider Class Reference
TGServerService.TGDiscordChatProvider Class Reference
Public Member Functions
TGDiscordChatProvider (TGChatSetupInfo info)
TGChatSetupInfo ProviderInfo ()
Gets the info of the provider
string Connect ()
Connects the chat provider if it's enabled
bool Connected ()
Checks if the chat provider is connected
void Disconnect ()
Disconnects the chat provider
string Reconnect ()
Forces a reconnection of the chat provider if it's enabled
void SendMessage (string msg, ChatMessageType mt)
Broadcast a message to appropriate channels based on the message type
string SendMessageDirect (string message, string channelname)
Send a message to a channel
string SetProviderInfo (TGChatSetupInfo info)
Sets info for the provider
void Dispose ()
Protected Member Functions
virtual void Dispose (bool disposing)
Events
OnChatMessage OnChatMessage
Events inherited from TGServerService.ITGChatProvider
OnChatMessage OnChatMessage
Called with chat message info
Private Member Functions
void Init (TGChatSetupInfo info)
bool CheckAdmin (SocketUser u)
async Task Client_MessageReceived (SocketMessage e)
void DisconnectAndDispose ()
Private Attributes
DiscordSocketClient client
TGDiscordSetupInfo DiscordConfig
object DiscordLock = new object()
IDictionary< ulong, ISocketMessageChannel > SeenPrivateChannels = new Dictionary<ulong, ISocketMessageChannel>()
bool disposedValue = false
Detailed Description
Definition at line 11 of file Discord.cs.
Constructor & Destructor Documentation
TGServerService.TGDiscordChatProvider.TGDiscordChatProvider (TGChatSetupInfo info)
Definition at line 20 of file Discord.cs.
References TGServerService.TGDiscordChatProvider.Init().
         {
             Init(info);
         }
Member Function Documentation
bool TGServerService.TGDiscordChatProvider.CheckAdmin (SocketUser u) private
Definition at line 37 of file Discord.cs.
References TGServiceInterface.TGChatSetupInfo.AdminList, and TGServiceInterface.TGChatSetupInfo.AdminsAreSpecial.
Referenced by TGServerService.TGDiscordChatProvider.Client_MessageReceived().
         {
             if (!DiscordConfig.AdminsAreSpecial)
                 return DiscordConfig.AdminList.Contains(u.Id.ToString());
             if(u is SocketGuildUser sgu)
                 foreach (var I in sgu.Roles)
                     if (DiscordConfig.AdminList.Contains(I.Id.ToString()))
                         return true;
             return false;
         }
async Task TGServerService.TGDiscordChatProvider.Client_MessageReceived (SocketMessage e) private
Definition at line 48 of file Discord.cs.
References TGServiceInterface.TGChatSetupInfo.AdminChannels, TGServerService.TGDiscordChatProvider.CheckAdmin(), and TGServerService.TGDiscordChatProvider.OnChatMessage.
Referenced by TGServerService.TGDiscordChatProvider.Init().
         {
             await Task.Run(() =>
             {
                 if (e.Author.Id == client.CurrentUser.Id)
                     return;
                 var pm = e.Channel is IPrivateChannel;
                 if (pm && !SeenPrivateChannels.ContainsKey(e.Channel.Id))
                     SeenPrivateChannels.Add(e.Channel.Id, e.Channel);
                 bool found = false;
                 var formattedMessage = e.Content;
                 foreach (var u in e.MentionedUsers)
                     if (u.Id == client.CurrentUser.Id)
                     {
                         found = true;
                         formattedMessage = formattedMessage.Replace(u.Mention, "");
                         var nicknameMention = u.Mention.Replace("!", "");
                         formattedMessage = formattedMessage.Replace(nicknameMention, "");
                         break;
                     }
                 if (!found && !pm)
                     return;
                 formattedMessage = formattedMessage.Trim();
                 var cid = e.Channel.Id.ToString();
                 OnChatMessage(this, e.Author.Id.ToString(), cid, formattedMessage, CheckAdmin(e.Author), pm || DiscordConfig.AdminChannels.Contains(cid));
             });
         }
string TGServerService.TGDiscordChatProvider.Connect ()
Connects the chat provider if it's enabled
Returns
null on success, error message on failure
Implements TGServerService.ITGChatProvider.
Definition at line 84 of file Discord.cs.
References TGServiceInterface.TGDiscordSetupInfo.BotToken, TGServerService.TGDiscordChatProvider.Connected(), and TGServiceInterface.TGChatSetupInfo.Enabled.
Referenced by TGServerService.TGDiscordChatProvider.Reconnect().
         {
             try
             {
                 if (Connected() || !DiscordConfig.Enabled)
                     return null;
                 lock (DiscordLock)
                 {
                     SeenPrivateChannels.Clear();
                     client.LoginAsync(TokenType.Bot, DiscordConfig.BotToken).Wait();
                     client.StartAsync().Wait();
                     Thread.Sleep(1000); //wait for ConnectionState to update
                 }
                 return !Connected() ? "Connection failed!" : null;
             }
             catch (Exception e)
             {
                 return e.ToString();
             }
         }
bool TGServerService.TGDiscordChatProvider.Connected ()
Checks if the chat provider is connected
Returns
true if the provider is connected, false otherwise
Implements TGServerService.ITGChatProvider.
Definition at line 105 of file Discord.cs.
Referenced by TGServerService.TGDiscordChatProvider.Connect(), TGServerService.TGDiscordChatProvider.Disconnect(), TGServerService.TGDiscordChatProvider.SendMessage(), TGServerService.TGDiscordChatProvider.SendMessageDirect(), and TGServerService.TGDiscordChatProvider.SetProviderInfo().
         {
             lock (DiscordLock)
             {
                 return client.ConnectionState == ConnectionState.Connected;
             }
         }
void TGServerService.TGDiscordChatProvider.Disconnect ()
Disconnects the chat provider
Implements TGServerService.ITGChatProvider.
Definition at line 113 of file Discord.cs.
References TGServerService.TGDiscordChatProvider.Connected().
Referenced by TGServerService.TGDiscordChatProvider.Reconnect(), and TGServerService.TGDiscordChatProvider.SetProviderInfo().
         {
             try
             {
                 if (!Connected())
                     return;
                 lock (DiscordLock)
                 {
                     SeenPrivateChannels.Clear();
                     client.StopAsync().Wait();
                     client.LogoutAsync().Wait();
                 }
             }
             catch { }
         }
void TGServerService.TGDiscordChatProvider.DisconnectAndDispose () private
Definition at line 188 of file Discord.cs.
Referenced by TGServerService.TGDiscordChatProvider.Dispose(), and TGServerService.TGDiscordChatProvider.SetProviderInfo().
         {
             try
             {
                 client.StopAsync().Wait();
                 client.LogoutAsync().Wait();
             }
             catch (Exception e) {
                 TGServerService.WriteError("Discord failed DnD: " + e.ToString(), TGServerService.EventID.ChatDisconnectFail);
             }
             client.Dispose();
         }
virtual void TGServerService.TGDiscordChatProvider.Dispose (bool disposing) protected virtual
Definition at line 233 of file Discord.cs.
References TGServerService.TGDiscordChatProvider.DisconnectAndDispose().
         {
             if (!disposedValue)
             {
                 if (disposing)
                 {
                     DisconnectAndDispose();
                     // TODO: dispose managed state (managed objects).
                 }
                 // TODO: free unmanaged resources (unmanaged objects) and override a finalizer below.
                 // TODO: set large fields to null.
                 disposedValue = true;
             }
         }
void TGServerService.TGDiscordChatProvider.Dispose ()
Definition at line 257 of file Discord.cs.
         {
             // Do not change this code. Put cleanup code in Dispose(bool disposing) above.
             Dispose(true);
             // TODO: uncomment the following line if the finalizer is overridden above.
             // GC.SuppressFinalize(this);
         }
void TGServerService.TGDiscordChatProvider.Init (TGChatSetupInfo info) private
Definition at line 30 of file Discord.cs.
References TGServerService.TGDiscordChatProvider.Client_MessageReceived().
Referenced by TGServerService.TGDiscordChatProvider.SetProviderInfo(), and TGServerService.TGDiscordChatProvider.TGDiscordChatProvider().
         {
             DiscordConfig = new TGDiscordSetupInfo(info);
             client = new DiscordSocketClient();
             client.MessageReceived += Client_MessageReceived;
         }
TGChatSetupInfo TGServerService.TGDiscordChatProvider.ProviderInfo ()
Gets the info of the provider
Returns
The info for the chat provider
Implements TGServerService.ITGChatProvider.
Definition at line 25 of file Discord.cs.
References TGServerService.TGDiscordChatProvider.DiscordConfig.
         {
             return DiscordConfig;
         }
string TGServerService.TGDiscordChatProvider.Reconnect ()
Forces a reconnection of the chat provider if it's enabled
Returns
null on success, error message on failure
Implements TGServerService.ITGChatProvider.
Definition at line 129 of file Discord.cs.
References TGServerService.TGDiscordChatProvider.Connect(), and TGServerService.TGDiscordChatProvider.Disconnect().
Referenced by TGServerService.TGDiscordChatProvider.SetProviderInfo().
         {
             Disconnect();
             return Connect();
         }
void TGServerService.TGDiscordChatProvider.SendMessage (string msg, ChatMessageType mt)
Broadcast a message to appropriate channels based on the message type
Parameters
msg The message to send
mt The message type
Implements TGServerService.ITGChatProvider.
Definition at line 135 of file Discord.cs.
References TGServiceInterface.TGChatSetupInfo.AdminChannels, TGServerService.TGDiscordChatProvider.Connected(), TGServiceInterface.TGChatSetupInfo.DevChannels, TGServiceInterface.TGChatSetupInfo.GameChannels, and TGServiceInterface.TGChatSetupInfo.WatchdogChannels.
         {
             if (!Connected())
                 return;
             lock (DiscordLock)
             {
                 var tasks = new List<Task>();
                 var Config = Properties.Settings.Default;
                 foreach (var I in client.Guilds)
                     foreach (var J in I.TextChannels)
                     {
                         var cid = J.Id.ToString();
                         var wdc = DiscordConfig.WatchdogChannels;
                         bool SendToThisChannel = (mt.HasFlag(ChatMessageType.AdminInfo) && DiscordConfig.AdminChannels.Contains(cid))
                             || (mt.HasFlag(ChatMessageType.DeveloperInfo) && DiscordConfig.DevChannels.Contains(cid))
                             || (mt.HasFlag(ChatMessageType.GameInfo) && DiscordConfig.GameChannels.Contains(cid))
                             || (mt.HasFlag(ChatMessageType.WatchdogInfo) && DiscordConfig.WatchdogChannels.Contains(cid));
                         if (SendToThisChannel)
                             tasks.Add(J.SendMessageAsync(msg));
                     }
                 foreach (var I in tasks)
                     I.Wait();
             }
         }
string TGServerService.TGDiscordChatProvider.SendMessageDirect (string message, string channel)
Send a message to a channel
Parameters
message The message to send
channel The channel to send to
Returns
null on success, error message on failure
Implements TGServerService.ITGChatProvider.
Definition at line 161 of file Discord.cs.
References TGServerService.TGDiscordChatProvider.Connected().
         {
             if (!Connected())
                 return "Disconnected.";
             try
             {
                 lock (DiscordLock)
                 {
                     var tasks = new List<Task>();
                     var Config = Properties.Settings.Default;
                     var channel = Convert.ToUInt64(channelname);
                     if (SeenPrivateChannels.ContainsKey(channel))
                         SeenPrivateChannels[channel].SendMessageAsync(message).Wait();
                     else
                         foreach (var I in client.Guilds)
                             foreach (var J in I.TextChannels)
                                 if (J.Id == channel)
                                     J.SendMessageAsync(message).Wait();
                     TGServerService.WriteInfo(String.Format("Discord Send ({0}): {1}", channelname, message), TGServerService.EventID.ChatSend);
                     return null;
                 }
             }
             catch (Exception e)
             {
                 return e.ToString();
             }
         }
string TGServerService.TGDiscordChatProvider.SetProviderInfo (TGChatSetupInfo info)
Sets info for the provider
Parameters
info The info to set
Returns
null on success, error message on failure
Implements TGServerService.ITGChatProvider.
Definition at line 201 of file Discord.cs.
References TGServiceInterface.TGDiscordSetupInfo.BotToken, TGServerService.TGDiscordChatProvider.Connected(), TGServerService.TGDiscordChatProvider.Disconnect(), TGServerService.TGDiscordChatProvider.DisconnectAndDispose(), TGServerService.TGDiscordChatProvider.DiscordConfig, TGServiceInterface.TGChatSetupInfo.Enabled, TGServerService.TGDiscordChatProvider.Init(), and TGServerService.TGDiscordChatProvider.Reconnect().
         {
             try
             {
                 lock (DiscordLock)
                 {
                     var odc = DiscordConfig;
                     DiscordConfig = new TGDiscordSetupInfo(info);
                     if (DiscordConfig.BotToken != odc.BotToken)
                     {
                         DisconnectAndDispose();
                         Init(info);
                     }
                     if (DiscordConfig.Enabled)
                     {
                         if (!Connected())
                             return Reconnect();
                     }
                     else
                         Disconnect();
                 }
                 return null;
             }
             catch (Exception e)
             {
                 return e.ToString();
             }
         }
Member Data Documentation
DiscordSocketClient TGServerService.TGDiscordChatProvider.client private
Definition at line 14 of file Discord.cs.
TGDiscordSetupInfo TGServerService.TGDiscordChatProvider.DiscordConfig private
Definition at line 15 of file Discord.cs.
Referenced by TGServerService.TGDiscordChatProvider.ProviderInfo(), and TGServerService.TGDiscordChatProvider.SetProviderInfo().
object TGServerService.TGDiscordChatProvider.DiscordLock = new object() private
Definition at line 16 of file Discord.cs.
bool TGServerService.TGDiscordChatProvider.disposedValue = false private
Definition at line 231 of file Discord.cs.
IDictionary<ulong, ISocketMessageChannel> TGServerService.TGDiscordChatProvider.SeenPrivateChannels = new Dictionary<ulong, ISocketMessageChannel>() private
Definition at line 18 of file Discord.cs.
Event Documentation
OnChatMessage TGServerService.TGDiscordChatProvider.OnChatMessage
Definition at line 13 of file Discord.cs.
Referenced by TGServerService.TGDiscordChatProvider.Client_MessageReceived().
The documentation for this class was generated from the following file:
TGServerService/Discord.cs