tgstation-server: Tgstation.Server.Client.RestServerClientFactory Class Reference
Tgstation.Server.Client.RestServerClientFactory Class Reference sealed
Public Member Functions
RestServerClientFactory (ProductHeaderValue productHeaderValue)
Initializes a new instance of the RestServerClientFactory class.
ValueTask< IRestServerClient > CreateFromLogin (Uri host, string username, string password, IEnumerable< IRequestLogger >? requestLoggers=null, TimeSpan? timeout=null, bool attemptLoginRefresh=true, CancellationToken cancellationToken=default)
Create a IRestServerClient using a password login.
Parameters
host The URL to access TGS.
username The username to for the IRestServerClient.
password The password for the IRestServerClient.
requestLoggers Optional initial IRequestLoggers to add to the IRestServerClient.
timeout Optional TimeSpan representing timeout for the connection.
attemptLoginRefresh Attempt to refresh the received TokenResponse when it expires or becomes invalid. username and password will be stored in memory if this is true.
cancellationToken Optional CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a new IRestServerClient.
ValueTask< IRestServerClient > CreateFromOAuth (Uri host, string oAuthCode, OAuthProvider oAuthProvider, IEnumerable< IRequestLogger >? requestLoggers=null, TimeSpan? timeout=null, CancellationToken cancellationToken=default)
Create a IRestServerClient using an OAuth login.
Parameters
host The URL to access TGS.
oAuthCode The OAuth code used to complete the flow.
oAuthProvider The OAuthProvider.
requestLoggers Optional initial IRequestLoggers to add to the IRestServerClient.
timeout Optional TimeSpan representing timeout for the connection.
cancellationToken Optional CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a new IRestServerClient.
IRestServerClient CreateFromToken (Uri host, TokenResponse token)
Create a IRestServerClient.
Parameters
host The URL to access TGS.
token The TokenResponse to access the API with.
Returns
A new IRestServerClient.
async ValueTask< ServerInformationResponse > GetServerInformation (Uri host, IEnumerable< IRequestLogger >? requestLoggers=null, TimeSpan? timeout=null, CancellationToken cancellationToken=default)
Gets the ServerInformationResponse for a given host .
Parameters
host The URL to access TGS.
requestLoggers Optional IRequestLoggers.
timeout Optional TimeSpan representing timeout for the HTTP request.
cancellationToken Optional CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the ServerInformationResponse.
Private Member Functions
async ValueTask< IRestServerClient > CreateWithNewToken (Uri host, ApiHeaders loginHeaders, IEnumerable< IRequestLogger >? requestLoggers, TimeSpan? timeout, bool attemptLoginRefresh, CancellationToken cancellationToken)
Creates a IRestServerClient from a login operation.
Static Private Member Functions
static RestServerClientFactory ()
Initializes static members of the RestServerClientFactory class.
Private Attributes
readonly ProductHeaderValue productHeaderValue
The ProductHeaderValue for the RestServerClientFactory.
Detailed Description
Definition at line 15 of file RestServerClientFactory.cs.
Constructor & Destructor Documentation
RestServerClientFactory() [1/2]
static Tgstation.Server.Client.RestServerClientFactory.RestServerClientFactory () static private
Initializes static members of the RestServerClientFactory class.
Definition at line 30 of file RestServerClientFactory.cs.
        {
            ApiClientFactory = new ApiClientFactory();
        }
RestServerClientFactory() [2/2]
Tgstation.Server.Client.RestServerClientFactory.RestServerClientFactory (ProductHeaderValue productHeaderValue)
Initializes a new instance of the RestServerClientFactory class.
Parameters
productHeaderValue The value of productHeaderValue.
Definition at line 39 of file RestServerClientFactory.cs.
        {
            this.productHeaderValue = productHeaderValue ?? throw new ArgumentNullException(nameof(productHeaderValue));
        }
References Tgstation.Server.Client.RestServerClientFactory.productHeaderValue.
Member Function Documentation
CreateFromLogin()
ValueTask< IRestServerClient > Tgstation.Server.Client.RestServerClientFactory.CreateFromLogin (Uri host, string username, string password, IEnumerable< IRequestLogger >? requestLoggers = null, TimeSpan? timeout = null, bool attemptLoginRefresh = true, CancellationToken cancellationToken = default)
Create a IRestServerClient using a password login.
Parameters
host The URL to access TGS.
username The username to for the IRestServerClient.
password The password for the IRestServerClient.
requestLoggers Optional initial IRequestLoggers to add to the IRestServerClient.
timeout Optional TimeSpan representing timeout for the connection.
attemptLoginRefresh Attempt to refresh the received TokenResponse when it expires or becomes invalid. username and password will be stored in memory if this is true.
cancellationToken Optional CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a new IRestServerClient.
Implements Tgstation.Server.Client.IRestServerClientFactory.
Definition at line 45 of file RestServerClientFactory.cs.
        {
            if (host == null)
                throw new ArgumentNullException(nameof(host));
            if (username == null)
                throw new ArgumentNullException(nameof(username));
            if (password == null)
                throw new ArgumentNullException(nameof(password));
            var loginHeaders = new ApiHeaders(productHeaderValue, username, password);
            return CreateWithNewToken(
                host,
                loginHeaders,
                requestLoggers,
                timeout,
                attemptLoginRefresh,
                cancellationToken);
        }
References Tgstation.Server.Client.RestServerClientFactory.CreateWithNewToken(), and Tgstation.Server.Client.RestServerClientFactory.productHeaderValue.
CreateFromOAuth()
ValueTask< IRestServerClient > Tgstation.Server.Client.RestServerClientFactory.CreateFromOAuth (Uri host, string oAuthCode, OAuthProvider oAuthProvider, IEnumerable< IRequestLogger >? requestLoggers = null, TimeSpan? timeout = null, CancellationToken cancellationToken = default)
Create a IRestServerClient using an OAuth login.
Parameters
host The URL to access TGS.
oAuthCode The OAuth code used to complete the flow.
oAuthProvider The OAuthProvider.
requestLoggers Optional initial IRequestLoggers to add to the IRestServerClient.
timeout Optional TimeSpan representing timeout for the connection.
cancellationToken Optional CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a new IRestServerClient.
Implements Tgstation.Server.Client.IRestServerClientFactory.
Definition at line 72 of file RestServerClientFactory.cs.
        {
            if (host == null)
                throw new ArgumentNullException(nameof(host));
            if (oAuthCode == null)
                throw new ArgumentNullException(nameof(oAuthCode));
            var loginHeaders = new ApiHeaders(productHeaderValue, oAuthCode, oAuthProvider);
            return CreateWithNewToken(
                host,
                loginHeaders,
                requestLoggers,
                timeout,
                false,
                cancellationToken);
        }
References Tgstation.Server.Client.RestServerClientFactory.CreateWithNewToken(), and Tgstation.Server.Client.RestServerClientFactory.productHeaderValue.
CreateFromToken()
IRestServerClient Tgstation.Server.Client.RestServerClientFactory.CreateFromToken (Uri host, TokenResponse token)
Create a IRestServerClient.
Parameters
host The URL to access TGS.
token The TokenResponse to access the API with.
Returns
A new IRestServerClient.
Implements Tgstation.Server.Client.IRestServerClientFactory.
Definition at line 96 of file RestServerClientFactory.cs.
        {
            if (host == null)
                throw new ArgumentNullException(nameof(host));
            if (token == null)
                throw new ArgumentNullException(nameof(token));
            if (token.Bearer == null)
                throw new InvalidOperationException("token.Bearer should not be null!");
            var serverClient = new RestServerClient(
                ApiClientFactory.CreateApiClient(
                    host,
                    new ApiHeaders(
                        productHeaderValue,
                        token),
                    null,
                    false));
            return serverClient;
        }
References Tgstation.Server.Api.Models.Response.TokenResponse.Bearer, Tgstation.Server.Client.ApiClientFactory.CreateApiClient(), and Tgstation.Server.Client.RestServerClientFactory.productHeaderValue.
CreateWithNewToken()
async ValueTask< IRestServerClient > Tgstation.Server.Client.RestServerClientFactory.CreateWithNewToken (Uri host, ApiHeaders loginHeaders, IEnumerable< IRequestLogger >? requestLoggers, TimeSpan? timeout, bool attemptLoginRefresh, CancellationToken cancellationToken) private
Creates a IRestServerClient from a login operation.
Parameters
host The URL to access TGS.
loginHeaders The ApiHeaders to use for the login operation.
requestLoggers Optional initial IRequestLoggers to add to the IRestServerClient.
timeout Optional TimeSpan representing timeout for the connection.
attemptLoginRefresh If loginHeaders may be used to re-login in the future.
cancellationToken Optional CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a new IRestServerClient.
Definition at line 154 of file RestServerClientFactory.cs.
        {
            requestLoggers ??= Enumerable.Empty<IRequestLogger>();
            TokenResponse token;
            await using (var api = ApiClientFactory.CreateApiClient(host, loginHeaders, null, false))
            {
                foreach (var requestLogger in requestLoggers)
                    api.AddRequestLogger(requestLogger);
                if (timeout.HasValue)
                    api.Timeout = timeout.Value;
                token = await api.Update<TokenResponse>(Routes.ApiRoot, cancellationToken).ConfigureAwait(false);
            }
            var apiHeaders = new ApiHeaders(productHeaderValue, token);
            var client = new RestServerClient(
                ApiClientFactory.CreateApiClient(
                    host,
                    apiHeaders,
                    attemptLoginRefresh ? loginHeaders : null,
                    false));
            if (timeout.HasValue)
                client.Timeout = timeout.Value;
            foreach (var requestLogger in requestLoggers)
                client.AddRequestLogger(requestLogger);
            return client;
        }
References Tgstation.Server.Api.Routes.ApiRoot, Tgstation.Server.Client.ApiClientFactory.CreateApiClient(), and Tgstation.Server.Client.RestServerClientFactory.productHeaderValue.
Referenced by Tgstation.Server.Client.RestServerClientFactory.CreateFromLogin(), and Tgstation.Server.Client.RestServerClientFactory.CreateFromOAuth().
GetServerInformation()
async ValueTask< ServerInformationResponse > Tgstation.Server.Client.RestServerClientFactory.GetServerInformation (Uri host, IEnumerable< IRequestLogger >? requestLoggers = null, TimeSpan? timeout = null, CancellationToken cancellationToken = default)
Gets the ServerInformationResponse for a given host .
Parameters
host The URL to access TGS.
requestLoggers Optional IRequestLoggers.
timeout Optional TimeSpan representing timeout for the HTTP request.
cancellationToken Optional CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the ServerInformationResponse.
Implements Tgstation.Server.Client.IRestServerClientFactory.
Definition at line 117 of file RestServerClientFactory.cs.
        {
            await using var api = ApiClientFactory.CreateApiClient(
                host,
                new ApiHeaders(
                    productHeaderValue,
                    new TokenResponse
                    {
                        Bearer = "unused",
                    }),
                null,
                true);
            if (requestLoggers != null)
                foreach (var requestLogger in requestLoggers)
                    api.AddRequestLogger(requestLogger);
            if (timeout.HasValue)
                api.Timeout = timeout.Value;
            return await api.Read<ServerInformationResponse>(Routes.ApiRoot, cancellationToken).ConfigureAwait(false);
        }
References Tgstation.Server.Client.IApiClient.AddRequestLogger(), Tgstation.Server.Api.Routes.ApiRoot, Tgstation.Server.Client.ApiClientFactory.CreateApiClient(), and Tgstation.Server.Client.RestServerClientFactory.productHeaderValue.
Member Data Documentation
productHeaderValue
readonly ProductHeaderValue Tgstation.Server.Client.RestServerClientFactory.productHeaderValue private
The ProductHeaderValue for the RestServerClientFactory.
Definition at line 25 of file RestServerClientFactory.cs.
Referenced by Tgstation.Server.Client.RestServerClientFactory.CreateFromLogin(), Tgstation.Server.Client.RestServerClientFactory.CreateFromOAuth(), Tgstation.Server.Client.RestServerClientFactory.CreateFromToken(), Tgstation.Server.Client.RestServerClientFactory.CreateWithNewToken(), Tgstation.Server.Client.RestServerClientFactory.GetServerInformation(), and Tgstation.Server.Client.RestServerClientFactory.RestServerClientFactory().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Client/RestServerClientFactory.cs