tgstation-server: Tgstation.Server.Tests.Instance.JobsRequiredTest Class Reference
Tgstation.Server.Tests.Instance.JobsRequiredTest Class Reference
Public Member Functions
JobsRequiredTest (IJobsClient jobsClient)
async Task< Job > WaitForJob (Job originalJob, int timeout, bool expectFailure, CancellationToken cancellationToken)
Protected Member Functions
async Task< Job > WaitForJobProgressThenCancel (Job originalJob, int timeout, CancellationToken cancellationToken)
Properties
IJobsClient JobsClient [get]
Detailed Description
Definition at line 12 of file JobsRequiredTest.cs.
Constructor & Destructor Documentation
Tgstation.Server.Tests.Instance.JobsRequiredTest.JobsRequiredTest (IJobsClient jobsClient)
Definition at line 16 of file JobsRequiredTest.cs.
         {
             this.JobsClient = jobsClient;
         }
Member Function Documentation
async Task<Job> Tgstation.Server.Tests.Instance.JobsRequiredTest.WaitForJob (Job originalJob, int timeout, bool expectFailure, CancellationToken cancellationToken)
Definition at line 21 of file JobsRequiredTest.cs.
References Tgstation.Server.Client.Components.JobsClient.Cancel(), and Tgstation.Server.Client.Components.JobsClient.GetId().
Referenced by Tgstation.Server.Tests.IntegrationTest.TestServer().
         {
             var job = originalJob;
             do
             {
                 await Task.Delay(TimeSpan.FromSeconds(1), cancellationToken).ConfigureAwait(false);
                 job = await JobsClient.GetId(job, cancellationToken).ConfigureAwait(false);
                 --timeout;
             }
             while (!job.StoppedAt.HasValue && timeout > 0);
             if (!job.StoppedAt.HasValue)
             {
                 await JobsClient.Cancel(job, cancellationToken).ConfigureAwait(false);
                 Assert.Fail($"Job ID {job.Id} \"{job.Description}\" timed out!");
             }
             if (expectFailure ^ job.ExceptionDetails != null)
                 Assert.Fail(job.ExceptionDetails ?? $"Expected job \"{job.Id}\" \"{job.Description}\" to fail but it didn't");
             return job;
         }
async Task<Job> Tgstation.Server.Tests.Instance.JobsRequiredTest.WaitForJobProgressThenCancel (Job originalJob, int timeout, CancellationToken cancellationToken) protected
Definition at line 44 of file JobsRequiredTest.cs.
References Tgstation.Server.Client.Components.JobsClient.Cancel(), and Tgstation.Server.Client.Components.JobsClient.GetId().
         {
             var job = originalJob;
             do
             {
                 await Task.Delay(TimeSpan.FromSeconds(1), cancellationToken).ConfigureAwait(false);
                 job = await JobsClient.GetId(job, cancellationToken).ConfigureAwait(false);
                 --timeout;
             }
             while (!job.Progress.HasValue && timeout > 0);
             if (job.StoppedAt.HasValue)
             {
                 await JobsClient.Cancel(job, cancellationToken).ConfigureAwait(false);
                 Assert.Fail($"Job ID {job.Id} \"{job.Description}\" completed when we wanted it to just progress!");
             }
             if (job.ExceptionDetails != null)
                 Assert.Fail(job.ExceptionDetails);
             await JobsClient.Cancel(job, cancellationToken);
             return await WaitForJob(job, timeout, false, cancellationToken).ConfigureAwait(false);
         }
Property Documentation
IJobsClient Tgstation.Server.Tests.Instance.JobsRequiredTest.JobsClient get protected
Definition at line 14 of file JobsRequiredTest.cs.
The documentation for this class was generated from the following file:
tests/Tgstation.Server.Tests/Instance/JobsRequiredTest.cs