tgstation-server: Tgstation.Server.Host.System.PosixProcessFeatures Class Reference
Tgstation.Server.Host.System.PosixProcessFeatures Class Reference sealed
Public Member Functions
PosixProcessFeatures (Lazy< IProcessExecutor > lazyLoadedProcessExecutor, IIOManager ioManager, ILogger< PosixProcessFeatures > logger)
Initializes a new instance of the PosixProcessFeatures class.
void ResumeProcess (global::System.Diagnostics.Process process)
Resume a given suspended global::System.Diagnostics.Process.
Parameters
process The Process to suspended.
void SuspendProcess (global::System.Diagnostics.Process process)
Suspend a given process .
Parameters
process The global::System.Diagnostics.Process to suspend.
string GetExecutingUsername (global::System.Diagnostics.Process process)
Get the name of the user executing a given process .
Parameters
process The global::System.Diagnostics.Process.
Returns
The name of the user executing process .
async ValueTask CreateDump (global::System.Diagnostics.Process process, string outputFile, bool minidump, CancellationToken cancellationToken)
Create a dump file for a given process .
Parameters
process The global::System.Diagnostics.Process to dump.
outputFile The full path to the output file.
minidump If a minidump should be taken as opposed to a full dump.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
async ValueTask< int > HandleProcessStart (global::System.Diagnostics.Process process, CancellationToken cancellationToken)
Run events on starting a process.
Parameters
process The global::System.Diagnostics.Process that was started.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the process ID.
async Task StartAsync (CancellationToken cancellationToken)
Task StopAsync (CancellationToken cancellationToken)
Private Member Functions
ValueTask AdjustOutOfMemoryScore (int? pid, short adjustment, CancellationToken cancellationToken)
Set oom_score_adj for a given pid .
Private Attributes
readonly Lazy< IProcessExecutor > lazyLoadedProcessExecutor
Lazy<T> loaded IProcessExecutor.
readonly IIOManager ioManager
The IIOManager for the PosixProcessFeatures.
readonly ILogger< PosixProcessFeatures > logger
The ILogger<TCategoryName> for the PosixProcessFeatures.
short baselineOomAdjust
The original value of oom_score_adj as read from the /proc/ filesystem. Inherited from parent process.
Static Private Attributes
const short SelfOomAdjust = 1
Difference from baselineOomAdjust to set our own oom_score_adj to. 1 higher host watchdog.
const short ChildProcessOomAdjust = SelfOomAdjust + 1
Difference from baselineOomAdjust to set the oom_score_adj of child processes to. 1 higher than ourselves.
Detailed Description
Definition at line 20 of file PosixProcessFeatures.cs.
Constructor & Destructor Documentation
PosixProcessFeatures()
Tgstation.Server.Host.System.PosixProcessFeatures.PosixProcessFeatures (Lazy< IProcessExecutor > lazyLoadedProcessExecutor, IIOManager ioManager, ILogger< PosixProcessFeatures > logger)
Initializes a new instance of the PosixProcessFeatures class.
Parameters
lazyLoadedProcessExecutor The value of lazyLoadedProcessExecutor.
ioManager The value of ioManager.
logger The value of logger.
Definition at line 58 of file PosixProcessFeatures.cs.
        {
            this.lazyLoadedProcessExecutor = lazyLoadedProcessExecutor ?? throw new ArgumentNullException(nameof(lazyLoadedProcessExecutor));
            this.ioManager = ioManager ?? throw new ArgumentNullException(nameof(ioManager));
            this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }
References Tgstation.Server.Host.System.PosixProcessFeatures.ioManager, Tgstation.Server.Host.System.PosixProcessFeatures.lazyLoadedProcessExecutor, and Tgstation.Server.Host.System.PosixProcessFeatures.logger.
Member Function Documentation
AdjustOutOfMemoryScore()
ValueTask Tgstation.Server.Host.System.PosixProcessFeatures.AdjustOutOfMemoryScore (int? pid, short adjustment, CancellationToken cancellationToken) private
Set oom_score_adj for a given pid .
Parameters
pid The global::System.Diagnostics.Process.Id or null to self adjust.
adjustment The value being written to the adjustment file.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Definition at line 202 of file PosixProcessFeatures.cs.
        {
            var adjustedValue = Math.Clamp(baselineOomAdjust + adjustment, -1000, 1000);
            var pidStr = pid.HasValue
                ? pid.Value.ToString(CultureInfo.InvariantCulture)
                : "self";
            logger.LogTrace(
                "Setting oom_score_adj of {pid} to {adjustment}...", pidStr, adjustedValue);
            return ioManager.WriteAllBytes(
                $"/proc/{pidStr}/oom_score_adj",
                Encoding.UTF8.GetBytes(adjustedValue.ToString(CultureInfo.InvariantCulture)),
                cancellationToken);
        }
References Tgstation.Server.Host.System.PosixProcessFeatures.baselineOomAdjust, Tgstation.Server.Host.System.PosixProcessFeatures.ioManager, Tgstation.Server.Host.System.PosixProcessFeatures.logger, and Tgstation.Server.Host.IO.IIOManager.WriteAllBytes().
Referenced by Tgstation.Server.Host.System.PosixProcessFeatures.HandleProcessStart(), and Tgstation.Server.Host.System.PosixProcessFeatures.StartAsync().
CreateDump()
async ValueTask Tgstation.Server.Host.System.PosixProcessFeatures.CreateDump (global::System::Diagnostics::Process process, string outputFile, bool minidump, CancellationToken cancellationToken)
Create a dump file for a given process .
Parameters
process The global::System.Diagnostics.Process to dump.
outputFile The full path to the output file.
minidump If a minidump should be taken as opposed to a full dump.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.System.IProcessFeatures.
Definition at line 86 of file PosixProcessFeatures.cs.
        {
            ArgumentNullException.ThrowIfNull(process);
            ArgumentNullException.ThrowIfNull(outputFile);
            const string GCorePath = "/usr/bin/gcore";
            if (!await ioManager.FileExists(GCorePath, cancellationToken))
                throw new JobException(ErrorCode.MissingGCore);
            int pid;
            try
            {
                if (process.HasExited)
                    throw new JobException(ErrorCode.GameServerOffline);
                pid = process.Id;
            }
            catch (InvalidOperationException ex)
            {
                throw new JobException(ErrorCode.GameServerOffline, ex);
            }
            string? output;
            int exitCode;
            await using (var gcoreProc = await lazyLoadedProcessExecutor.Value.LaunchProcess(
                GCorePath,
                Environment.CurrentDirectory,
                $"{(!minidump ? "-a " : String.Empty)}-o {outputFile} {process.Id}",
                cancellationToken,
                readStandardHandles: true,
                noShellExecute: true))
            {
                using (cancellationToken.Register(() => gcoreProc.Terminate()))
                    exitCode = (await gcoreProc.Lifetime).Value;
                output = await gcoreProc.GetCombinedOutput(cancellationToken);
                logger.LogDebug("gcore output:{newline}{output}", Environment.NewLine, output);
            }
            if (exitCode != 0)
                throw new JobException(
                    ErrorCode.GCoreFailure,
                    new JobException(
                        $"Exit Code: {exitCode}{Environment.NewLine}Output:{Environment.NewLine}{output}"));
            // gcore outputs name.pid so remove the pid part
            var generatedGCoreFile = $"{outputFile}.{pid}";
            await ioManager.MoveFile(generatedGCoreFile, outputFile, cancellationToken);
        }
References Tgstation.Server.Host.IO.IIOManager.FileExists(), Tgstation.Server.Host.System.PosixProcessFeatures.ioManager, Tgstation.Server.Host.System.PosixProcessFeatures.lazyLoadedProcessExecutor, Tgstation.Server.Host.System.PosixProcessFeatures.logger, and Tgstation.Server.Host.IO.IIOManager.MoveFile().
GetExecutingUsername()
string Tgstation.Server.Host.System.PosixProcessFeatures.GetExecutingUsername (global::System.Diagnostics.Process process)
Get the name of the user executing a given process .
Parameters
process The global::System.Diagnostics.Process.
Returns
The name of the user executing process .
Implements Tgstation.Server.Host.System.IProcessFeatures.
HandleProcessStart()
async ValueTask< int > Tgstation.Server.Host.System.PosixProcessFeatures.HandleProcessStart (global::System::Diagnostics::Process process, CancellationToken cancellationToken)
Run events on starting a process.
Parameters
process The global::System.Diagnostics.Process that was started.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the process ID.
Implements Tgstation.Server.Host.System.IProcessFeatures.
Definition at line 137 of file PosixProcessFeatures.cs.
        {
            ArgumentNullException.ThrowIfNull(process);
            var pid = process.Id;
            try
            {
                // make sure all processes we spawn are killed _before_ us
                await AdjustOutOfMemoryScore(pid, ChildProcessOomAdjust, cancellationToken);
            }
            catch (Exception ex) when (ex is not OperationCanceledException)
            {
                logger.LogWarning(ex, "Failed to adjust OOM killer score for pid {pid}!", pid);
            }
            return pid;
        }
References Tgstation.Server.Host.System.PosixProcessFeatures.AdjustOutOfMemoryScore(), Tgstation.Server.Host.System.PosixProcessFeatures.ChildProcessOomAdjust, and Tgstation.Server.Host.System.PosixProcessFeatures.logger.
ResumeProcess()
void Tgstation.Server.Host.System.PosixProcessFeatures.ResumeProcess (global::System::Diagnostics::Process process)
Resume a given suspended global::System.Diagnostics.Process.
Parameters
process The Process to suspended.
Implements Tgstation.Server.Host.System.IProcessFeatures.
Definition at line 66 of file PosixProcessFeatures.cs.
        {
            var result = Syscall.kill(process.Id, Signum.SIGCONT);
            if (result != 0)
                throw new UnixIOException(Stdlib.GetLastError());
        }
StartAsync()
async Task Tgstation.Server.Host.System.PosixProcessFeatures.StartAsync (CancellationToken cancellationToken)
Definition at line 155 of file PosixProcessFeatures.cs.
        {
            // let this all throw
            string originalString;
            {
                // can't use ReadAllBytes here, /proc files have 0 length so the buffer is initialized to empty
                // https://stackoverflow.com/questions/12237712/how-can-i-show-the-size-of-files-in-proc-it-should-not-be-size-zero
                await using var fileStream = ioManager.CreateAsyncSequentialReadStream(
                    "/proc/self/oom_score_adj");
                using var reader = new StreamReader(fileStream, Encoding.UTF8, leaveOpen: true);
                originalString = await reader.ReadToEndAsync(cancellationToken);
            }
            var trimmedString = originalString.Trim();
            logger.LogTrace("Original oom_score_adj is \"{original}\"", trimmedString);
            var originalOomAdjust = Int16.Parse(trimmedString, CultureInfo.InvariantCulture);
            baselineOomAdjust = Math.Clamp(originalOomAdjust, (short)-1000, (short)1000);
            if (baselineOomAdjust == 1000)
                if (originalOomAdjust != baselineOomAdjust)
                    logger.LogWarning("oom_score_adj is at it's limit of 1000 (Clamped from {original}). TGS cannot guarantee the kill order of its parent/child processes!", originalOomAdjust);
                else
                    logger.LogWarning("oom_score_adj is at it's limit of 1000. TGS cannot guarantee the kill order of its parent/child processes!");
            try
            {
                // we do not want to be killed before the host watchdog
                await AdjustOutOfMemoryScore(null, SelfOomAdjust, cancellationToken);
            }
            catch (Exception ex) when (ex is not OperationCanceledException)
            {
                logger.LogWarning(ex, "Could not increase oom_score_adj!");
            }
        }
References Tgstation.Server.Host.System.PosixProcessFeatures.AdjustOutOfMemoryScore(), Tgstation.Server.Host.System.PosixProcessFeatures.baselineOomAdjust, Tgstation.Server.Host.IO.IIOManager.CreateAsyncSequentialReadStream(), Tgstation.Server.Host.System.PosixProcessFeatures.ioManager, Tgstation.Server.Host.System.PosixProcessFeatures.logger, and Tgstation.Server.Host.System.PosixProcessFeatures.SelfOomAdjust.
StopAsync()
Task Tgstation.Server.Host.System.PosixProcessFeatures.StopAsync (CancellationToken cancellationToken)
SuspendProcess()
void Tgstation.Server.Host.System.PosixProcessFeatures.SuspendProcess (global::System::Diagnostics::Process process)
Suspend a given process .
Parameters
process The global::System.Diagnostics.Process to suspend.
Implements Tgstation.Server.Host.System.IProcessFeatures.
Definition at line 74 of file PosixProcessFeatures.cs.
        {
            var result = Syscall.kill(process.Id, Signum.SIGSTOP);
            if (result != 0)
                throw new UnixIOException(Stdlib.GetLastError());
        }
Member Data Documentation
baselineOomAdjust
short Tgstation.Server.Host.System.PosixProcessFeatures.baselineOomAdjust private
The original value of oom_score_adj as read from the /proc/ filesystem. Inherited from parent process.
Definition at line 50 of file PosixProcessFeatures.cs.
Referenced by Tgstation.Server.Host.System.PosixProcessFeatures.AdjustOutOfMemoryScore(), and Tgstation.Server.Host.System.PosixProcessFeatures.StartAsync().
ChildProcessOomAdjust
const short Tgstation.Server.Host.System.PosixProcessFeatures.ChildProcessOomAdjust = SelfOomAdjust + 1 static private
Difference from baselineOomAdjust to set the oom_score_adj of child processes to. 1 higher than ourselves.
Definition at line 30 of file PosixProcessFeatures.cs.
Referenced by Tgstation.Server.Host.System.PosixProcessFeatures.HandleProcessStart().
ioManager
readonly IIOManager Tgstation.Server.Host.System.PosixProcessFeatures.ioManager private
The IIOManager for the PosixProcessFeatures.
Definition at line 40 of file PosixProcessFeatures.cs.
Referenced by Tgstation.Server.Host.System.PosixProcessFeatures.AdjustOutOfMemoryScore(), Tgstation.Server.Host.System.PosixProcessFeatures.CreateDump(), Tgstation.Server.Host.System.PosixProcessFeatures.PosixProcessFeatures(), and Tgstation.Server.Host.System.PosixProcessFeatures.StartAsync().
lazyLoadedProcessExecutor
readonly Lazy<IProcessExecutor> Tgstation.Server.Host.System.PosixProcessFeatures.lazyLoadedProcessExecutor private
Lazy<T> loaded IProcessExecutor.
Definition at line 35 of file PosixProcessFeatures.cs.
Referenced by Tgstation.Server.Host.System.PosixProcessFeatures.CreateDump(), and Tgstation.Server.Host.System.PosixProcessFeatures.PosixProcessFeatures().
logger
readonly ILogger<PosixProcessFeatures> Tgstation.Server.Host.System.PosixProcessFeatures.logger private
The ILogger<TCategoryName> for the PosixProcessFeatures.
Definition at line 45 of file PosixProcessFeatures.cs.
Referenced by Tgstation.Server.Host.System.PosixProcessFeatures.AdjustOutOfMemoryScore(), Tgstation.Server.Host.System.PosixProcessFeatures.CreateDump(), Tgstation.Server.Host.System.PosixProcessFeatures.HandleProcessStart(), Tgstation.Server.Host.System.PosixProcessFeatures.PosixProcessFeatures(), and Tgstation.Server.Host.System.PosixProcessFeatures.StartAsync().
SelfOomAdjust
const short Tgstation.Server.Host.System.PosixProcessFeatures.SelfOomAdjust = 1 static private
Difference from baselineOomAdjust to set our own oom_score_adj to. 1 higher host watchdog.
Definition at line 25 of file PosixProcessFeatures.cs.
Referenced by Tgstation.Server.Host.System.PosixProcessFeatures.StartAsync().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/System/PosixProcessFeatures.cs