tgstation-server: Tgstation.Server.Host.Controllers.RepositoryController Class Reference
Tgstation.Server.Host.Controllers.RepositoryController Class Reference
ApiController for managing the git repository.
Public Member Functions
RepositoryController (IDatabaseContext databaseContext, IAuthenticationContextFactory authenticationContextFactory, IInstanceManager instanceManager, IGitHubClientFactory gitHubClientFactory, IJobManager jobManager, ILogger< RepositoryController > logger)
Initializes a new instance of the RepositoryController class.
async Task< IActionResult > Create ([FromBody] RepositoryCreateRequest model, CancellationToken cancellationToken)
Begin cloning the repository if it doesn't exist.
async Task< IActionResult > Delete (CancellationToken cancellationToken)
Delete the repository.
async Task< IActionResult > Read (CancellationToken cancellationToken)
Get the repository's status.
async Task< IActionResult > Update ([FromBody] RepositoryUpdateRequest model, CancellationToken cancellationToken)
Perform updates to the repository.
Public Member Functions inherited from Tgstation.Server.Host.Controllers.ApiController
override async Task OnActionExecutionAsync (ActionExecutingContext context, ActionExecutionDelegate next)
Private Member Functions
async Task< bool > LoadRevisionInformation (Components.Repository.IRepository repository, IDatabaseContext databaseContext, Models.Instance instance, string lastOriginCommitSha, Action< Models.RevisionInformation > revInfoSink, CancellationToken cancellationToken)
Load the RevisionInformation for the current repository state into a given databaseContext .
async Task< bool > PopulateApi (RepositoryResponse apiResponse, Components.Repository.IRepository repository, IDatabaseContext databaseContext, Models.Instance instance, CancellationToken cancellationToken)
Populate a given apiResponse with the current state of a given repository .
Private Attributes
readonly IGitHubClientFactory gitHubClientFactory
The IGitHubClientFactory for the RepositoryController.
readonly IJobManager jobManager
The IJobManager for the RepositoryController.
Additional Inherited Members
Static Public Member Functions inherited from Tgstation.Server.Host.Controllers.InstanceRequiredController
static bool ValidateInstanceOnlineStatus (IInstanceManager instanceManager, ILogger logger, Api.Models.Instance metadata)
Corrects discrepencies between the Api.Models.Instance.Online status of IInstances in the database vs the service.
Protected Member Functions inherited from Tgstation.Server.Host.Controllers.InstanceRequiredController
InstanceRequiredController (IInstanceManager instanceManager, IDatabaseContext databaseContext, IAuthenticationContextFactory authenticationContextFactory, ILogger< InstanceRequiredController > logger)
Initializes a new instance of the InstanceRequiredController class.
override async Task< IActionResult > ValidateRequest (CancellationToken cancellationToken)
Performs validation a request.
async Task< IActionResult > WithComponentInstance (Func< IInstanceCore, Task< IActionResult > > action)
Run a given action with the relevant IInstance.
Protected Member Functions inherited from Tgstation.Server.Host.Controllers.ApiController
ApiController (IDatabaseContext databaseContext, IAuthenticationContextFactory authenticationContextFactory, ILogger< ApiController > logger, bool requireHeaders)
Initializes a new instance of the ApiController class.
ObjectResult Gone ()
Generic 410 response.
new NotFoundObjectResult NotFound ()
Generic 404 response.
ObjectResult RequiresPosixSystemIdentity ()
Generic 501 response.
StatusCodeResult StatusCode (HttpStatusCode statusCode)
Strongly type calls to ControllerBase.StatusCode(int).
ObjectResult StatusCode (HttpStatusCode statusCode, object errorMessage)
Strongly type calls to ControllerBase.StatusCode(int, object).
ObjectResult Created (object payload)
Generic 201 response with a given payload .
ObjectResult RateLimit (RateLimitExceededException rateLimitException)
429 response for a given rateLimitException .
virtual Task< IActionResult > ValidateRequest (CancellationToken cancellationToken)
Performs validation a request.
IActionResult HeadersIssue (bool ignoreMissingAuth)
Response for missing/Invalid headers.
Task< IActionResult > Paginated< TModel > (Func< Task< PaginatableResult< TModel > > > queryGenerator, Func< TModel, Task > resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
Task< IActionResult > Paginated< TModel, TApiModel > (Func< Task< PaginatableResult< TModel > > > queryGenerator, Func< TApiModel, Task > resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
Properties inherited from Tgstation.Server.Host.Controllers.ApiController
ApiHeaders ApiHeaders [get, private set]
The Api.ApiHeaders for the operation.
IDatabaseContext DatabaseContext [get]
The IDatabaseContext for the operation.
IAuthenticationContext AuthenticationContext [get]
The IAuthenticationContext for the operation.
ILogger< ApiController > Logger [get]
The ILogger for the ApiController.
Models.Instance Instance [get]
The Instance for the operation.
Detailed Description
ApiController for managing the git repository.
Definition at line 33 of file RepositoryController.cs.
Constructor & Destructor Documentation
RepositoryController()
Tgstation.Server.Host.Controllers.RepositoryController.RepositoryController (IDatabaseContext databaseContext, IAuthenticationContextFactory authenticationContextFactory, IInstanceManager instanceManager, IGitHubClientFactory gitHubClientFactory, IJobManager jobManager, ILogger< RepositoryController > logger)
Initializes a new instance of the RepositoryController class.
Parameters
databaseContext The IDatabaseContext for the ApiController.
authenticationContextFactory The IAuthenticationContextFactory for the ApiController.
instanceManager The IInstanceManager for the InstanceRequiredController.
gitHubClientFactory The value of gitHubClientFactory.
jobManager The value of jobManager.
logger The ILogger for the ApiController.
Definition at line 54 of file RepositoryController.cs.
            : base(
                  instanceManager,
                  databaseContext,
                  authenticationContextFactory,
                  logger)
        {
            this.gitHubClientFactory = gitHubClientFactory ?? throw new ArgumentNullException(nameof(gitHubClientFactory));
            this.jobManager = jobManager ?? throw new ArgumentNullException(nameof(jobManager));
        }
References Tgstation.Server.Host.Controllers.RepositoryController.gitHubClientFactory, and Tgstation.Server.Host.Controllers.RepositoryController.jobManager.
Member Function Documentation
Create()
async Task< IActionResult > Tgstation.Server.Host.Controllers.RepositoryController.Create ([FromBody] RepositoryCreateRequest model, CancellationToken cancellationToken)
Begin cloning the repository if it doesn't exist.
Parameters
model The RepositoryCreateRequest.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the IActionResult of the request.
<response code="201">The repository was created successfully and the JobResponse to clone it has begun.</response> <response code="410">The database entity for the requested instance could not be retrieved. The instance was likely detached.</response>
Definition at line 83 of file RepositoryController.cs.
        {
            if (model == null)
                throw new ArgumentNullException(nameof(model));
            if (model.Origin == null)
                return BadRequest(ErrorCode.ModelValidationFailure);
            if (model.AccessUser == null ^ model.AccessToken == null)
                return BadRequest(ErrorCode.RepoMismatchUserAndAccessToken);
            var userRights = (RepositoryRights)AuthenticationContext.GetRight(RightsType.Repository);
            if (((model.AccessUser ?? model.AccessToken) != null && !userRights.HasFlag(RepositoryRights.ChangeCredentials))
                || ((model.CommitterEmail ?? model.CommitterName) != null && !userRights.HasFlag(RepositoryRights.ChangeCommitter)))
                return Forbid();
            #pragma warning disable CS0618 // Support for obsolete API field
            model.UpdateSubmodules ??= model.RecurseSubmodules;
            #pragma warning restore CS0618
            var currentModel = await DatabaseContext
                .RepositorySettings
                .AsQueryable()
                .Where(x => x.InstanceId == Instance.Id)
                .FirstOrDefaultAsync(cancellationToken)
                .ConfigureAwait(false);
            if (currentModel == default)
                return Gone();
            currentModel.UpdateSubmodules = model.UpdateSubmodules ?? true;
            currentModel.AccessToken = model.AccessToken;
            currentModel.AccessUser = model.AccessUser;
            currentModel.CommitterEmail = model.CommitterEmail ?? currentModel.CommitterEmail;
            currentModel.CommitterName = model.CommitterName ?? currentModel.CommitterName;
            var cloneBranch = model.Reference;
            var origin = model.Origin;
            return await WithComponentInstance(
                async instance =>
                {
                    var repoManager = instance.RepositoryManager;
                    if (repoManager.CloneInProgress)
                        return Conflict(new ErrorMessageResponse(ErrorCode.RepoCloning));
                    if (repoManager.InUse)
                        return Conflict(new ErrorMessageResponse(ErrorCode.RepoBusy));
                    using var repo = await repoManager.LoadRepository(cancellationToken).ConfigureAwait(false);
                    // clone conflict
                    if (repo != null)
                        return Conflict(new ErrorMessageResponse(ErrorCode.RepoExists));
                    var job = new Job
                    {
                        Description = String.Format(
                            CultureInfo.InvariantCulture,
                            "Clone{1} repository {0}",
                            origin,
                            cloneBranch != null
                                ? $"\"{cloneBranch}\" branch of"
                                : String.Empty),
                        StartedBy = AuthenticationContext.User,
                        CancelRightsType = RightsType.Repository,
                        CancelRight = (ulong)RepositoryRights.CancelClone,
                        Instance = Instance,
                    };
                    var api = currentModel.ToApi();
                    await DatabaseContext.Save(cancellationToken).ConfigureAwait(false);
                    await jobManager.RegisterOperation(
                        job,
                        async (core, databaseContextFactory, paramJob, progressReporter, ct) =>
{
                            var repoManager = core.RepositoryManager;
                            using var repos = await repoManager.CloneRepository(
                                origin,
                                cloneBranch,
                                currentModel.AccessUser,
                                currentModel.AccessToken,
                                progressReporter,
                                currentModel.UpdateSubmodules.Value,
                                ct)
                                .ConfigureAwait(false);
                            if (repos == null)
                                throw new JobException(ErrorCode.RepoExists);
                            var instance = new Models.Instance
{
                                Id = Instance.Id,
                            };
                            await databaseContextFactory.UseContext(
                                async databaseContext =>
{
                                    databaseContext.Instances.Attach(instance);
                                    if (await PopulateApi(api, repos, databaseContext, instance, ct).ConfigureAwait(false))
                                        await databaseContext.Save(ct).ConfigureAwait(false);
                                })
                                .ConfigureAwait(false);
                        },
                        cancellationToken)
                        .ConfigureAwait(false);
                    api.Origin = model.Origin;
                    api.Reference = model.Reference;
                    api.ActiveJob = job.ToApi();
                    return Created(api);
                })
                .ConfigureAwait(false);
        }
References Tgstation.Server.Host.Controllers.ApiController.Created(), Tgstation.Server.Host.Security.AuthenticationContext.GetRight(), Tgstation.Server.Host.Controllers.ApiController.Gone(), Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Host.Controllers.RepositoryController.jobManager, Tgstation.Server.Host.Jobs.IJobManager.RegisterOperation(), Tgstation.Server.Host.Database.DatabaseContext.RepositorySettings, Tgstation.Server.Host.Database.DatabaseContext.Save(), Tgstation.Server.Host.Models.Job.ToApi(), and Tgstation.Server.Host.Controllers.InstanceRequiredController.WithComponentInstance().
Delete()
async Task< IActionResult > Tgstation.Server.Host.Controllers.RepositoryController.Delete (CancellationToken cancellationToken)
Delete the repository.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the IActionResult of the operation.
<response code="202">Job to delete the repository created successfully.</response> <response code="410">The database entity for the requested instance could not be retrieved. The instance was likely detached.</response>
Definition at line 209 of file RepositoryController.cs.
        {
            var currentModel = await DatabaseContext
                .RepositorySettings
                .AsQueryable()
                .Where(x => x.InstanceId == Instance.Id)
                .FirstOrDefaultAsync(cancellationToken)
                .ConfigureAwait(false);
            if (currentModel == default)
                return Gone();
            currentModel.AccessToken = null;
            currentModel.AccessUser = null;
            await DatabaseContext.Save(cancellationToken).ConfigureAwait(false);
            Logger.LogInformation("Instance {0} repository delete initiated by user {1}", Instance.Id, AuthenticationContext.User.Id.Value);
            var job = new Job
            {
                Description = "Delete repository",
                StartedBy = AuthenticationContext.User,
                Instance = Instance,
            };
            var api = currentModel.ToApi();
            await jobManager.RegisterOperation(
                job,
                (core, databaseContextFactory, paramJob, progressReporter, ct) => core.RepositoryManager.DeleteRepository(ct),
                cancellationToken)
            .ConfigureAwait(false);
            api.ActiveJob = job.ToApi();
            return Accepted(api);
        }
References Tgstation.Server.Host.Controllers.ApiController.Gone(), Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Host.Controllers.ApiController.Instance, Tgstation.Server.Host.Controllers.RepositoryController.jobManager, Tgstation.Server.Host.Controllers.ApiController.Logger, Tgstation.Server.Host.Jobs.IJobManager.RegisterOperation(), Tgstation.Server.Host.Database.DatabaseContext.RepositorySettings, Tgstation.Server.Host.Database.DatabaseContext.Save(), and Tgstation.Server.Host.Security.AuthenticationContext.User.
LoadRevisionInformation()
async Task< bool > Tgstation.Server.Host.Controllers.RepositoryController.LoadRevisionInformation (Components.Repository.IRepository repository, IDatabaseContext databaseContext, Models.Instance instance, string lastOriginCommitSha, Action< Models.RevisionInformation > revInfoSink, CancellationToken cancellationToken) private
Load the RevisionInformation for the current repository state into a given databaseContext .
Parameters
repository The Components.Repository.IRepository.
databaseContext The active IDatabaseContext.
instance The active Models.Instance.
lastOriginCommitSha The last known origin commit SHA of the repository if any.
revInfoSink An optional Action<T> to receive the loaded RevisionInformation.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in true if the databaseContext was modified in a way that requires saving, false otherwise.
Definition at line 939 of file RepositoryController.cs.
        {
            var repoSha = repository.Head;
            IQueryable<Models.RevisionInformation> ApplyQuery(IQueryable<Models.RevisionInformation> query) => query
                .Where(x => x.CommitSha == repoSha && x.Instance.Id == instance.Id)
                .Include(x => x.CompileJobs)
                .Include(x => x.ActiveTestMerges).ThenInclude(x => x.TestMerge).ThenInclude(x => x.MergedBy);
            var revisionInfo = await ApplyQuery(databaseContext.RevisionInformations).FirstOrDefaultAsync(cancellationToken).ConfigureAwait(false);
            // If the DB doesn't have it, check the local set
            if (revisionInfo == default)
                revisionInfo = databaseContext
                    .RevisionInformations
                    .Local
                    .Where(x => x.CommitSha == repoSha && x.Instance.Id == instance.Id)
                    .FirstOrDefault();
            var needsDbUpdate = revisionInfo == default;
            if (needsDbUpdate)
            {
                // needs insertion
                revisionInfo = new Models.RevisionInformation
                {
                    Instance = instance,
                    CommitSha = repoSha,
                    Timestamp = await repository.TimestampCommit(repoSha, cancellationToken).ConfigureAwait(false),
                    CompileJobs = new List<CompileJob>(),
                    ActiveTestMerges = new List<RevInfoTestMerge>(), // non null vals for api returns
                };
                lock (databaseContext) // cleaner this way
                    databaseContext.RevisionInformations.Add(revisionInfo);
            }
            revisionInfo.OriginCommitSha ??= lastOriginCommitSha;
            if (revisionInfo.OriginCommitSha == null)
            {
                revisionInfo.OriginCommitSha = repoSha;
                Logger.LogInformation(Components.Repository.Repository.OriginTrackingErrorTemplate, repoSha);
            }
            revInfoSink?.Invoke(revisionInfo);
            return needsDbUpdate;
        }
References Tgstation.Server.Host.Database.IDatabaseCollection< TModel >.Add(), Tgstation.Server.Api.Rights.CompileJobs, Tgstation.Server.Host.Database.IDatabaseCollection< TModel >.Local, Tgstation.Server.Host.Controllers.ApiController.Logger, and Tgstation.Server.Host.Database.IDatabaseContext.RevisionInformations.
Referenced by Tgstation.Server.Host.Controllers.RepositoryController.PopulateApi(), and Tgstation.Server.Host.Controllers.RepositoryController.Update().
PopulateApi()
async Task< bool > Tgstation.Server.Host.Controllers.RepositoryController.PopulateApi (RepositoryResponse apiResponse, Components.Repository.IRepository repository, IDatabaseContext databaseContext, Models.Instance instance, CancellationToken cancellationToken) private
Populate a given apiResponse with the current state of a given repository .
Parameters
apiResponse The RepositoryResponse to populate.
repository The Components.Repository.IRepository.
databaseContext The active IDatabaseContext.
instance The active Models.Instance.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in true if the databaseContext was modified in a way that requires saving, false otherwise.
Definition at line 1001 of file RepositoryController.cs.
        {
            apiResponse.RemoteGitProvider = repository.RemoteGitProvider;
            apiResponse.RemoteRepositoryOwner = repository.RemoteRepositoryOwner;
            apiResponse.RemoteRepositoryName = repository.RemoteRepositoryName;
            apiResponse.Origin = repository.Origin;
            apiResponse.Reference = repository.Reference;
            // rev info stuff
            Models.RevisionInformation revisionInfo = null;
            var needsDbUpdate = await LoadRevisionInformation(repository, databaseContext, instance, null, x => revisionInfo = x, cancellationToken).ConfigureAwait(false);
            apiResponse.RevisionInformation = revisionInfo.ToApi();
            return needsDbUpdate;
        }
References Tgstation.Server.Host.Controllers.RepositoryController.LoadRevisionInformation(), Tgstation.Server.Api.Models.Response.RepositoryResponse.Origin, Tgstation.Server.Api.Models.Internal.RepositoryApiBase.Reference, Tgstation.Server.Api.Models.Response.RepositoryResponse.RemoteGitProvider, Tgstation.Server.Api.Models.Response.RepositoryResponse.RemoteRepositoryName, Tgstation.Server.Api.Models.Response.RepositoryResponse.RemoteRepositoryOwner, and Tgstation.Server.Api.Models.Response.RepositoryResponse.RevisionInformation.
Referenced by Tgstation.Server.Host.Controllers.RepositoryController.Read(), and Tgstation.Server.Host.Controllers.RepositoryController.Update().
Read()
async Task< IActionResult > Tgstation.Server.Host.Controllers.RepositoryController.Read (CancellationToken cancellationToken)
Get the repository's status.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the IActionResult of the operation.
<response code="200">Retrieved the repository settings successfully.</response> <response code="201">Retrieved the repository settings successfully, though they did not previously exist.</response> <response code="410">The database entity for the requested instance could not be retrieved. The instance was likely detached.</response>
Definition at line 257 of file RepositoryController.cs.
        {
            var currentModel = await DatabaseContext
                .RepositorySettings
                .AsQueryable()
                .Where(x => x.InstanceId == Instance.Id)
                .FirstOrDefaultAsync(cancellationToken)
                .ConfigureAwait(false);
            if (currentModel == default)
                return Gone();
            var api = currentModel.ToApi();
            return await WithComponentInstance(
                async instance =>
                {
                    var repoManager = instance.RepositoryManager;
                    if (repoManager.CloneInProgress)
                        return Conflict(new ErrorMessageResponse(ErrorCode.RepoCloning));
                    if (repoManager.InUse)
                        return Conflict(new ErrorMessageResponse(ErrorCode.RepoBusy));
                    using var repo = await repoManager.LoadRepository(cancellationToken).ConfigureAwait(false);
                    if (repo != null && await PopulateApi(api, repo, DatabaseContext, Instance, cancellationToken).ConfigureAwait(false))
                    {
                        // user may have fucked with the repo manually, do what we can
                        await DatabaseContext.Save(cancellationToken).ConfigureAwait(false);
                        return Created(api);
                    }
                    return Json(api);
                })
                .ConfigureAwait(false);
        }
References Tgstation.Server.Host.Controllers.ApiController.Created(), Tgstation.Server.Host.Controllers.ApiController.Gone(), Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Host.Controllers.RepositoryController.PopulateApi(), Tgstation.Server.Host.Database.DatabaseContext.RepositorySettings, Tgstation.Server.Host.Database.DatabaseContext.Save(), and Tgstation.Server.Host.Controllers.InstanceRequiredController.WithComponentInstance().
Update()
async Task< IActionResult > Tgstation.Server.Host.Controllers.RepositoryController.Update ([FromBody] RepositoryUpdateRequest model, CancellationToken cancellationToken)
Perform updates to the repository.
Parameters
model The RepositoryUpdateRequest.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the IActionResult of the operation.
<response code="200">Updated the repository settings successfully.</response> <response code="202">Updated the repository settings successfully and a JobResponse was created to make the requested git changes.</response> <response code="410">The database entity for the requested instance could not be retrieved. The instance was likely detached.</response>
Definition at line 319 of file RepositoryController.cs.
        {
            if (model == null)
                throw new ArgumentNullException(nameof(model));
            if (model.AccessUser == null ^ model.AccessToken == null)
                return BadRequest(new ErrorMessageResponse(ErrorCode.RepoMismatchUserAndAccessToken));
            if (model.CheckoutSha != null && model.Reference != null)
                return BadRequest(new ErrorMessageResponse(ErrorCode.RepoMismatchShaAndReference));
            if (model.CheckoutSha != null && model.UpdateFromOrigin == true)
                return BadRequest(new ErrorMessageResponse(ErrorCode.RepoMismatchShaAndUpdate));
            if (model.NewTestMerges?.Any(x => model.NewTestMerges.Any(y => x != y && x.Number == y.Number)) == true)
                return BadRequest(new ErrorMessageResponse(ErrorCode.RepoDuplicateTestMerge));
            if (model.CommitterName?.Length == 0)
                return BadRequest(new ErrorMessageResponse(ErrorCode.RepoWhitespaceCommitterName));
            if (model.CommitterEmail?.Length == 0)
                return BadRequest(new ErrorMessageResponse(ErrorCode.RepoWhitespaceCommitterEmail));
            var newTestMerges = model.NewTestMerges != null && model.NewTestMerges.Count > 0;
            var userRights = (RepositoryRights)AuthenticationContext.GetRight(RightsType.Repository);
            if (newTestMerges && !userRights.HasFlag(RepositoryRights.MergePullRequest))
                return Forbid();
            var currentModel = await DatabaseContext
                .RepositorySettings
                .AsQueryable()
                .Where(x => x.InstanceId == Instance.Id)
                .FirstOrDefaultAsync(cancellationToken)
                .ConfigureAwait(false);
            if (currentModel == default)
                return Gone();
            bool CheckModified<T>(Expression<Func<Api.Models.Internal.RepositorySettings, T>> expression, RepositoryRights requiredRight)
            {
                var memberSelectorExpression = (MemberExpression)expression.Body;
                var property = (PropertyInfo)memberSelectorExpression.Member;
                var newVal = property.GetValue(model);
                if (newVal == null)
                    return false;
                if (!userRights.HasFlag(requiredRight) && property.GetValue(currentModel) != newVal)
                    return true;
                property.SetValue(currentModel, newVal);
                return false;
            }
            if (CheckModified(x => x.AccessToken, RepositoryRights.ChangeCredentials)
                || CheckModified(x => x.AccessUser, RepositoryRights.ChangeCredentials)
                || CheckModified(x => x.AutoUpdatesKeepTestMerges, RepositoryRights.ChangeAutoUpdateSettings)
                || CheckModified(x => x.AutoUpdatesSynchronize, RepositoryRights.ChangeAutoUpdateSettings)
                || CheckModified(x => x.CommitterEmail, RepositoryRights.ChangeCommitter)
                || CheckModified(x => x.CommitterName, RepositoryRights.ChangeCommitter)
                || CheckModified(x => x.PushTestMergeCommits, RepositoryRights.ChangeTestMergeCommits)
                || CheckModified(x => x.CreateGitHubDeployments, RepositoryRights.ChangeTestMergeCommits)
                || CheckModified(x => x.ShowTestMergeCommitters, RepositoryRights.ChangeTestMergeCommits)
                || CheckModified(x => x.PostTestMergeComment, RepositoryRights.ChangeTestMergeCommits)
                || CheckModified(x => x.UpdateSubmodules, RepositoryRights.ChangeSubmoduleUpdate)
                || (model.UpdateFromOrigin == true && !userRights.HasFlag(RepositoryRights.UpdateBranch))
                || (model.CheckoutSha != null && !userRights.HasFlag(RepositoryRights.SetSha))
                || (model.Reference != null && model.UpdateFromOrigin != true && !userRights.HasFlag(RepositoryRights.SetReference))) // don't care if it's the same reference, we want to forbid them before starting the job
                return Forbid();
            if (model.AccessToken?.Length == 0 && model.AccessUser?.Length == 0)
            {
                // setting an empty string clears everything
                currentModel.AccessUser = null;
                currentModel.AccessToken = null;
            }
            var canRead = userRights.HasFlag(RepositoryRights.Read);
            var api = canRead ? currentModel.ToApi() : new RepositoryResponse();
            if (canRead)
            {
                var earlyOut = await WithComponentInstance(
                async instance =>
                {
                    var repoManager = instance.RepositoryManager;
                    if (repoManager.CloneInProgress)
                        return Conflict(new ErrorMessageResponse(ErrorCode.RepoCloning));
                    if (repoManager.InUse)
                        return Conflict(new ErrorMessageResponse(ErrorCode.RepoBusy));
                    using var repo = await repoManager.LoadRepository(cancellationToken).ConfigureAwait(false);
                    if (repo == null)
                        return Conflict(new ErrorMessageResponse(ErrorCode.RepoMissing));
                    await PopulateApi(api, repo, DatabaseContext, Instance, cancellationToken).ConfigureAwait(false);
                    return null;
                })
                .ConfigureAwait(false);
                if (earlyOut != null)
                    return earlyOut;
            }
            // this is just db stuf so stow it away
            await DatabaseContext.Save(cancellationToken).ConfigureAwait(false);
            // format the job description
            string description = null;
            if (model.UpdateFromOrigin == true)
                if (model.Reference != null)
                    description = String.Format(CultureInfo.InvariantCulture, "Fetch and hard reset repository to origin/{0}", model.Reference);
                else if (model.CheckoutSha != null)
                    description = String.Format(CultureInfo.InvariantCulture, "Fetch and checkout {0} in repository", model.CheckoutSha);
                else
                    description = "Pull current repository reference";
            else if (model.Reference != null || model.CheckoutSha != null)
                description = String.Format(CultureInfo.InvariantCulture, "Checkout repository {0} {1}", model.Reference != null ? "reference" : "SHA", model.Reference ?? model.CheckoutSha);
            if (newTestMerges)
                description = String.Format(
                    CultureInfo.InvariantCulture,
                    "{0}est merge(s) {1}{2}",
                    description != null
                        ? String.Format(CultureInfo.InvariantCulture, "{0} and t", description)
                        : "T",
                    String.Join(
                        ", ",
                        model.NewTestMerges.Select(
                            x => String.Format(
                                CultureInfo.InvariantCulture,
                                "#{0}{1}",
                                x.Number,
                                x.TargetCommitSha != null
                                    ? String.Format(
                                        CultureInfo.InvariantCulture,
                                        " at {0}",
                                        x.TargetCommitSha.Substring(0, 7))
                                    : String.Empty))),
                    description != null
                        ? String.Empty
                        : " in repository");
            if (description == null)
                return Json(api); // no git changes
            async Task<IActionResult> RepositoryUpdateJobOhGodPleaseSomeoneRefactorThisItsTooFuckingBig(
                IInstanceCore instance,
                IDatabaseContextFactory databaseContextFactory,
                JobProgressReporter progressReporter,
                CancellationToken ct)
            {
                var repoManager = instance.RepositoryManager;
                using var repo = await repoManager.LoadRepository(ct).ConfigureAwait(false);
                if (repo == null)
                    throw new JobException(ErrorCode.RepoMissing);
                var modelHasShaOrReference = model.CheckoutSha != null || model.Reference != null;
                var startReference = repo.Reference;
                var startSha = repo.Head;
                string postUpdateSha = null;
                if (newTestMerges && repo.RemoteGitProvider == RemoteGitProvider.Unknown)
                    throw new JobException(ErrorCode.RepoUnsupportedTestMergeRemote);
                var committerName = currentModel.ShowTestMergeCommitters.Value
                    ? AuthenticationContext.User.Name
                    : currentModel.CommitterName;
                var hardResettingToOriginReference = model.UpdateFromOrigin == true && model.Reference != null;
                var numSteps = (model.NewTestMerges?.Count ?? 0) + (model.UpdateFromOrigin == true ? 1 : 0) + (!modelHasShaOrReference ? 2 : (hardResettingToOriginReference ? 3 : 1));
                var doneSteps = 0;
                JobProgressReporter NextProgressReporter()
                {
                    var tmpDoneSteps = doneSteps;
                    ++doneSteps;
                    return (status, progress) => progressReporter(status, (progress + (100 * tmpDoneSteps)) / numSteps);
                }
                progressReporter(null, 0);
                // get a base line for where we are
                Models.RevisionInformation lastRevisionInfo = null;
                var attachedInstance = new Models.Instance
                {
                    Id = Instance.Id,
                };
                Task CallLoadRevInfo(Models.TestMerge testMergeToAdd = null, string lastOriginCommitSha = null) => databaseContextFactory
                    .UseContext(
                        async databaseContext =>
{
                            databaseContext.Instances.Attach(attachedInstance);
                            var previousRevInfo = lastRevisionInfo;
                            var needsUpdate = await LoadRevisionInformation(
                                repo,
                                databaseContext,
                                attachedInstance,
                                lastOriginCommitSha,
                                x => lastRevisionInfo = x,
                                ct)
                                .ConfigureAwait(false);
                            if (testMergeToAdd != null)
{
                                // rev info may have already loaded the user
                                var mergedBy = databaseContext.Users.Local.FirstOrDefault(x => x.Id == AuthenticationContext.User.Id);
                                if (mergedBy == default)
{
                                    mergedBy = new User
{
                                        Id = AuthenticationContext.User.Id,
                                    };
                                    databaseContext.Users.Attach(mergedBy);
                                }
                                testMergeToAdd.MergedBy = mergedBy;
                                foreach (var activeTestMerge in previousRevInfo.ActiveTestMerges)
                                    lastRevisionInfo.ActiveTestMerges.Add(activeTestMerge);
                                lastRevisionInfo.ActiveTestMerges.Add(new RevInfoTestMerge
{
                                    TestMerge = testMergeToAdd,
                                });
                                lastRevisionInfo.PrimaryTestMerge = testMergeToAdd;
                                needsUpdate = true;
                            }
                            if (needsUpdate)
                                await databaseContext.Save(cancellationToken).ConfigureAwait(false);
                        });
                await CallLoadRevInfo().ConfigureAwait(false);
                // apply new rev info, tracking applied test merges
                Task UpdateRevInfo(Models.TestMerge testMergeToAdd = null) => CallLoadRevInfo(testMergeToAdd, lastRevisionInfo.OriginCommitSha);
                try
                {
                    // fetch/pull
                    if (model.UpdateFromOrigin == true)
                    {
                        if (!repo.Tracking)
                            throw new JobException(ErrorCode.RepoReferenceRequired);
                        await repo.FetchOrigin(currentModel.AccessUser, currentModel.AccessToken, NextProgressReporter(), ct).ConfigureAwait(false);
                        doneSteps = 1;
                        if (!modelHasShaOrReference)
{
                            var fastForward = await repo.MergeOrigin(committerName, currentModel.CommitterEmail, NextProgressReporter(), ct).ConfigureAwait(false);
                            if (!fastForward.HasValue)
                                throw new JobException(ErrorCode.RepoMergeConflict);
                            lastRevisionInfo.OriginCommitSha = await repo.GetOriginSha(cancellationToken).ConfigureAwait(false);
                            await UpdateRevInfo().ConfigureAwait(false);
                            if (fastForward.Value)
{
                                await repo.Sychronize(
                                    currentModel.AccessUser,
                                    currentModel.AccessToken,
                                    currentModel.CommitterName,
                                    currentModel.CommitterEmail,
                                    NextProgressReporter(),
                                    true,
                                    ct)
                                    .ConfigureAwait(false);
                                postUpdateSha = repo.Head;
                            }
                            else
                                NextProgressReporter()(null, 100);
                        }
                    }
                    var updateSubmodules = currentModel.UpdateSubmodules.Value;
                    // checkout/hard reset
                    if (modelHasShaOrReference)
                    {
                        var validCheckoutSha =
                            model.CheckoutSha != null
                            && !repo.Head.StartsWith(model.CheckoutSha, StringComparison.OrdinalIgnoreCase);
                        var validCheckoutReference =
                            model.Reference != null
                            && !repo.Reference.Equals(model.Reference, StringComparison.OrdinalIgnoreCase);
                        if (validCheckoutSha || validCheckoutReference)
{
                            var committish = model.CheckoutSha ?? model.Reference;
                            var isSha = await repo.IsSha(committish, cancellationToken).ConfigureAwait(false);
                            if ((isSha && model.Reference != null) || (!isSha && model.CheckoutSha != null))
                                throw new JobException(ErrorCode.RepoSwappedShaOrReference);
                            await repo.CheckoutObject(
                                committish,
                                currentModel.AccessUser,
                                currentModel.AccessToken,
                                updateSubmodules,
                                NextProgressReporter(),
                                ct)
                                .ConfigureAwait(false);
                            await CallLoadRevInfo().ConfigureAwait(false); // we've either seen origin before or what we're checking out is on origin
                        }
                        else
                            NextProgressReporter()(null, 100);
                        if (hardResettingToOriginReference)
{
                            if (!repo.Tracking)
                                throw new JobException(ErrorCode.RepoReferenceNotTracking);
                            await repo.ResetToOrigin(
                                currentModel.AccessUser,
                                currentModel.AccessToken,
                                updateSubmodules,
                                NextProgressReporter(),
                                ct)
                                .ConfigureAwait(false);
                            await repo.Sychronize(
                                currentModel.AccessUser,
                                currentModel.AccessToken,
                                currentModel.CommitterName,
                                currentModel.CommitterEmail,
                                NextProgressReporter(),
                                true,
                                ct)
                                .ConfigureAwait(false);
                            await CallLoadRevInfo().ConfigureAwait(false);
                            // repo head is on origin so force this
                            // will update the db if necessary
                            lastRevisionInfo.OriginCommitSha = repo.Head;
                        }
                    }
                    // test merging
                    if (newTestMerges)
                    {
                        if (repo.RemoteGitProvider == RemoteGitProvider.Unknown)
                            throw new JobException(ErrorCode.RepoTestMergeInvalidRemote);
                        // bit of sanitization
                        foreach (var newTestMergeWithoutTargetCommitSha in model.NewTestMerges.Where(x => String.IsNullOrWhiteSpace(x.TargetCommitSha)))
                            newTestMergeWithoutTargetCommitSha.TargetCommitSha = null;
                        var gitHubClient = currentModel.AccessToken != null
                            ? gitHubClientFactory.CreateClient(currentModel.AccessToken)
                            : gitHubClientFactory.CreateClient();
                        var repoOwner = repo.RemoteRepositoryOwner;
                        var repoName = repo.RemoteRepositoryName;
                        // optimization: if we've already merged these exact same commits in this fashion before, just find the rev info for it and check it out
                        Models.RevisionInformation revInfoWereLookingFor = null;
                        bool needToApplyRemainingPrs = true;
                        if (lastRevisionInfo.OriginCommitSha == lastRevisionInfo.CommitSha)
{
                            bool cantSearch = false;
                            foreach (var newTestMerge in model.NewTestMerges)
{
                                if (newTestMerge.TargetCommitSha != null)
#pragma warning disable CA1308 // Normalize strings to uppercase
                                    newTestMerge.TargetCommitSha = newTestMerge.TargetCommitSha?.ToLowerInvariant(); // ala libgit2
#pragma warning restore CA1308 // Normalize strings to uppercase
                                else
                                    try
{
                                        // retrieve the latest sha
                                        var pr = await repo.GetTestMerge(newTestMerge, currentModel, ct).ConfigureAwait(false);
                                        // we want to take the earliest truth possible to prevent RCEs, if this fails AddTestMerge will set it
                                        newTestMerge.TargetCommitSha = pr.TargetCommitSha;
                                    }
                                    catch
{
                                        cantSearch = true;
                                        break;
                                    }
                            }
                            if (!cantSearch)
{
                                List<Models.RevisionInformation> dbPull = null;
                                await databaseContextFactory.UseContext(
                                    async databaseContext =>
                                        dbPull = await databaseContext.RevisionInformations
                                            .AsQueryable()
                                            .Where(x => x.Instance.Id == Instance.Id
                                            && x.OriginCommitSha == lastRevisionInfo.OriginCommitSha
                                            && x.ActiveTestMerges.Count <= model.NewTestMerges.Count
                                            && x.ActiveTestMerges.Count > 0)
                                            .Include(x => x.ActiveTestMerges)
                                            .ThenInclude(x => x.TestMerge)
                                            .ToListAsync(cancellationToken)
                                            .ConfigureAwait(false))
                                    .ConfigureAwait(false);
                                // split here cause this bit has to be done locally
                                revInfoWereLookingFor = dbPull
                                    .Where(x => x.ActiveTestMerges.Count == model.NewTestMerges.Count
                                    && x.ActiveTestMerges.Select(y => y.TestMerge)
                                    .All(y => model.NewTestMerges.Any(z =>
                                    y.Number == z.Number
                                    && y.TargetCommitSha.StartsWith(z.TargetCommitSha, StringComparison.Ordinal)
                                    && (y.Comment?.Trim().ToUpperInvariant() == z.Comment?.Trim().ToUpperInvariant() || z.Comment == null))))
                                    .FirstOrDefault();
                                if (revInfoWereLookingFor == default && model.NewTestMerges.Count > 1)
{
                                    // okay try to add at least SOME prs we've seen before
                                    var listedNewTestMerges = model.NewTestMerges.ToList();
                                    var appliedTestMergeIds = new List<long>();
                                    Models.RevisionInformation lastGoodRevInfo = null;
                                    do
{
                                        foreach (var newTestMergeParameters in listedNewTestMerges)
{
                                            revInfoWereLookingFor = dbPull
                                                .Where(testRevInfo =>
{
                                                    if (testRevInfo.PrimaryTestMerge == null)
                                                        return false;
                                                    var testMergeMatch = model.NewTestMerges.Any(testTestMerge =>
{
                                                        var numberMatch = testRevInfo.PrimaryTestMerge.Number == testTestMerge.Number;
                                                        if (!numberMatch)
                                                            return false;
                                                        var shaMatch = testRevInfo.PrimaryTestMerge.TargetCommitSha.StartsWith(
                                                            testTestMerge.TargetCommitSha,
                                                            StringComparison.Ordinal);
                                                        if (!shaMatch)
                                                            return false;
                                                        var commentMatch = testRevInfo.PrimaryTestMerge.Comment == testTestMerge.Comment;
                                                        return commentMatch;
                                                    });
                                                    if (!testMergeMatch)
                                                        return false;
                                                    var previousTestMergesMatch = testRevInfo
                                                        .ActiveTestMerges
                                                        .Select(previousRevInfoTestMerge => previousRevInfoTestMerge.TestMerge)
                                                        .All(previousTestMerge => appliedTestMergeIds.Contains(previousTestMerge.Id));
                                                    return previousTestMergesMatch;
                                                })
                                                .FirstOrDefault();
                                            if (revInfoWereLookingFor != null)
{
                                                lastGoodRevInfo = revInfoWereLookingFor;
                                                appliedTestMergeIds.Add(revInfoWereLookingFor.PrimaryTestMerge.Id);
                                                listedNewTestMerges.Remove(newTestMergeParameters);
                                                break;
                                            }
                                        }
                                    }
                                    while (revInfoWereLookingFor != null && listedNewTestMerges.Count > 0);
                                    revInfoWereLookingFor = lastGoodRevInfo;
                                    needToApplyRemainingPrs = listedNewTestMerges.Count != 0;
                                    if (needToApplyRemainingPrs)
                                        model.NewTestMerges = listedNewTestMerges;
                                }
                                else if (revInfoWereLookingFor != null)
                                    needToApplyRemainingPrs = false;
                            }
                        }
                        if (revInfoWereLookingFor != null)
{
                            // goteem
                            Logger.LogDebug("Reusing existing SHA {0}...", revInfoWereLookingFor.CommitSha);
                            await repo.ResetToSha(revInfoWereLookingFor.CommitSha, NextProgressReporter(), cancellationToken).ConfigureAwait(false);
                            lastRevisionInfo = revInfoWereLookingFor;
                        }
                        if (needToApplyRemainingPrs)
{
                            foreach (var newTestMerge in model.NewTestMerges)
{
                                if (lastRevisionInfo.ActiveTestMerges.Any(x => x.TestMerge.Number == newTestMerge.Number))
                                    throw new JobException(ErrorCode.RepoDuplicateTestMerge);
                                var fullTestMergeTask = repo.GetTestMerge(newTestMerge, currentModel, ct);
                                var mergeResult = await repo.AddTestMerge(
                                    newTestMerge,
                                    committerName,
                                    currentModel.CommitterEmail,
                                    currentModel.AccessUser,
                                    currentModel.AccessToken,
                                    updateSubmodules,
                                    NextProgressReporter(),
                                    ct).ConfigureAwait(false);
                                if (mergeResult == null)
                                    throw new JobException(
                                        ErrorCode.RepoTestMergeConflict,
                                        new JobException(
                                            $"Test Merge #{newTestMerge.Number} at {newTestMerge.TargetCommitSha.Substring(0, 7)} conflicted!"));
                                Models.TestMerge fullTestMerge;
                                try
{
                                    fullTestMerge = await fullTestMergeTask.ConfigureAwait(false);
                                }
                                catch (Exception ex)
{
                                    Logger.LogWarning("Error retrieving metadata for test merge #{0}!", newTestMerge.Number);
                                    fullTestMerge = new Models.TestMerge
{
                                        Author = ex.Message,
                                        BodyAtMerge = ex.Message,
                                        MergedAt = DateTimeOffset.UtcNow,
                                        TitleAtMerge = ex.Message,
                                        Comment = newTestMerge.Comment,
                                        Number = newTestMerge.Number,
                                        Url = ex.Message,
                                    };
                                }
                                // Ensure we're getting the full sha from git itself
                                fullTestMerge.TargetCommitSha = newTestMerge.TargetCommitSha;
                                // MergedBy will be set later
                                ++doneSteps;
                                await UpdateRevInfo(fullTestMerge).ConfigureAwait(false);
                            }
                        }
                    }
                    var currentHead = repo.Head;
                    if (currentModel.PushTestMergeCommits.Value && (startSha != currentHead || (postUpdateSha != null && postUpdateSha != currentHead)))
                    {
                        await repo.Sychronize(
                            currentModel.AccessUser,
                            currentModel.AccessToken,
                            currentModel.CommitterName,
                            currentModel.CommitterEmail,
                            NextProgressReporter(),
                            false,
                            ct)
                            .ConfigureAwait(false);
                        await UpdateRevInfo().ConfigureAwait(false);
                    }
                    return null;
                }
                catch
                {
                    doneSteps = 0;
                    numSteps = 2;
                    // Forget what we've done and abort
                    // DCTx2: Cancellation token is for job, operations should always run
                    await repo.CheckoutObject(
                        startReference ?? startSha,
                        currentModel.AccessUser,
                        currentModel.AccessToken,
                        true,
                        NextProgressReporter(),
                        default)
                        .ConfigureAwait(false);
                    if (startReference != null && repo.Head != startSha)
                        await repo.ResetToSha(startSha, NextProgressReporter(), default).ConfigureAwait(false);
                    else
                        progressReporter(null, 100);
                    throw;
                }
            }
            var job = new Job
            {
                Description = description,
                StartedBy = AuthenticationContext.User,
                Instance = Instance,
                CancelRightsType = RightsType.Repository,
                CancelRight = (ulong)RepositoryRights.CancelPendingChanges,
            };
            // Time to access git, do it in a job
            await jobManager.RegisterOperation(
                job,
                (core, databaseContextFactory, paramJob, progressReporter, ct) =>
                    RepositoryUpdateJobOhGodPleaseSomeoneRefactorThisItsTooFuckingBig(
                        core,
                        databaseContextFactory,
                        progressReporter,
                        ct),
                cancellationToken)
                .ConfigureAwait(false);
            api.ActiveJob = job.ToApi();
            return Accepted(api);
        }
References Tgstation.Server.Host.Core.IGitHubClientFactory.CreateClient(), Tgstation.Server.Host.Security.AuthenticationContext.GetRight(), Tgstation.Server.Host.Controllers.RepositoryController.gitHubClientFactory, Tgstation.Server.Host.Controllers.ApiController.Gone(), Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Host.Controllers.ApiController.Instance, Tgstation.Server.Host.Controllers.RepositoryController.jobManager, Tgstation.Server.Host.Jobs.JobProgressReporter(), Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Controllers.RepositoryController.LoadRevisionInformation(), Tgstation.Server.Host.Controllers.ApiController.Logger, Tgstation.Server.Api.Models.UserName.Name, Tgstation.Server.Host.Controllers.RepositoryController.PopulateApi(), Tgstation.Server.Host.Jobs.IJobManager.RegisterOperation(), Tgstation.Server.Host.Components.IInstanceCore.RepositoryManager, Tgstation.Server.Host.Database.DatabaseContext.RepositorySettings, Tgstation.Server.Host.Database.DatabaseContext.Save(), Tgstation.Server.Host.Database.IDatabaseContextFactory.UseContext(), Tgstation.Server.Host.Security.AuthenticationContext.User, and Tgstation.Server.Host.Controllers.InstanceRequiredController.WithComponentInstance().
Member Data Documentation
gitHubClientFactory
readonly IGitHubClientFactory Tgstation.Server.Host.Controllers.RepositoryController.gitHubClientFactory private
The IGitHubClientFactory for the RepositoryController.
Definition at line 38 of file RepositoryController.cs.
Referenced by Tgstation.Server.Host.Controllers.RepositoryController.RepositoryController(), and Tgstation.Server.Host.Controllers.RepositoryController.Update().
jobManager
readonly IJobManager Tgstation.Server.Host.Controllers.RepositoryController.jobManager private
The IJobManager for the RepositoryController.
Definition at line 43 of file RepositoryController.cs.
Referenced by Tgstation.Server.Host.Controllers.RepositoryController.Create(), Tgstation.Server.Host.Controllers.RepositoryController.Delete(), Tgstation.Server.Host.Controllers.RepositoryController.RepositoryController(), and Tgstation.Server.Host.Controllers.RepositoryController.Update().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Controllers/RepositoryController.cs