tgstation-server: Tgstation.Server.Host.Controllers.InstancePermissionSetController Class Reference
Tgstation.Server.Host.Controllers.InstancePermissionSetController Class Reference
ApiController for managing InstancePermissionSets.
Public Member Functions
InstancePermissionSetController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ILogger< InstancePermissionSetController > logger, IInstanceManager instanceManager, IPermissionsUpdateNotifyee permissionsUpdateNotifyee, IApiHeadersProvider apiHeaders)
Initializes a new instance of the InstancePermissionSetController class.
async ValueTask< IActionResult > Create ([FromBody] InstancePermissionSetRequest model, CancellationToken cancellationToken)
Create an InstancePermissionSet.
async ValueTask< IActionResult > Update ([FromBody] InstancePermissionSetRequest model, CancellationToken cancellationToken)
Update the permissions for an InstancePermissionSet.
IActionResult Read ()
Read the active InstancePermissionSet.
ValueTask< IActionResult > List ([FromQuery] int? page, [FromQuery] int? pageSize, CancellationToken cancellationToken)
Lists InstancePermissionSets for the instance.
async ValueTask< IActionResult > GetId (long id, CancellationToken cancellationToken)
Gets a specific Api.Models.Internal.InstancePermissionSet.
async ValueTask< IActionResult > Delete (long id, CancellationToken cancellationToken)
Delete an InstancePermissionSet.
Public Member Functions inherited from Tgstation.Server.Host.Controllers.ApiControllerBase
sealed override async Task OnActionExecutionAsync (ActionExecutingContext context, ActionExecutionDelegate next)
Private Member Functions
ValueTask< IActionResult > InstancePermissionSetResponse (()=> ValueTask.FromResult(new PaginatableResult< InstancePermissionSet >(DatabaseContext .Instances .AsQueryable() .Where(x=> x.Id==Instance.Id) .SelectMany(x=> x.InstancePermissionSets) .OrderBy(x=> x.PermissionSetId))), null, page, pageSize, cancellationToken)
Private Attributes
readonly IPermissionsUpdateNotifyee permissionsUpdateNotifyee
The IPermissionsUpdateNotifyee for the InstancePermissionSetController.
Additional Inherited Members
Protected Member Functions inherited from Tgstation.Server.Host.Controllers.InstanceRequiredController
InstanceRequiredController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ILogger< InstanceRequiredController > logger, IInstanceManager instanceManager, IApiHeadersProvider apiHeaders)
Initializes a new instance of the InstanceRequiredController class.
Protected Member Functions inherited from Tgstation.Server.Host.Controllers.ComponentInterfacingController
ComponentInterfacingController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ILogger< ComponentInterfacingController > logger, IInstanceManager instanceManager, IApiHeadersProvider apiHeaders, bool useInstanceRequestHeader)
Initializes a new instance of the ComponentInterfacingController class.
override async ValueTask< IActionResult?> ValidateRequest (CancellationToken cancellationToken)
Performs validation a request.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in an appropriate IActionResult on validation failure, null otherwise.
bool ValidateInstanceOnlineStatus (Api.Models.Instance metadata)
Corrects discrepencies between the Api.Models.Instance.Online status of IInstances in the database vs the service.
async ValueTask< IActionResult?> WithComponentInstanceNullable (Func< IInstanceCore, ValueTask< IActionResult?> > action, Models.Instance? instance=null)
Run a given action with the relevant IInstance.
async ValueTask< IActionResult > WithComponentInstance (Func< IInstanceCore, ValueTask< IActionResult > > action, Models.Instance? instance=null)
Run a given action with the relevant IInstance.
Protected Member Functions inherited from Tgstation.Server.Host.Controllers.ApiController
ApiController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, IApiHeadersProvider apiHeadersProvider, ILogger< ApiController > logger, bool requireHeaders)
Initializes a new instance of the ApiController class.
override async ValueTask< IActionResult?> HookExecuteAction (Func< Task > executeAction, CancellationToken cancellationToken)
Hook for executing a request.
Parameters
executeAction A Func<TResult> that should be invoked and its response awaited to continue normal execution of the request. Should NOT be called if this method returns a non-null value.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in an IActionResult that, if not null, is executed.
new NotFoundObjectResult NotFound ()
Generic 404 response.
new ObjectResult Unauthorized ()
Generic 401 response.
ObjectResult RequiresPosixSystemIdentity (NotImplementedException ex)
Generic 501 response.
StatusCodeResult StatusCode (HttpStatusCode statusCode)
Strongly type calls to ControllerBase.StatusCode(int).
ObjectResult Created (object payload)
Generic 201 response with a given payload .
ObjectResult RateLimit (RateLimitExceededException rateLimitException)
429 response for a given rateLimitException .
virtual ValueTask< IActionResult?> ValidateRequest (CancellationToken cancellationToken)
Performs validation a request.
IActionResult HeadersIssue (HeadersException headersException)
Response for missing/Invalid headers.
ValueTask< IActionResult > Paginated< TModel > (Func< ValueTask< PaginatableResult< TModel > > > queryGenerator, Func< TModel, ValueTask >? resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
ValueTask< IActionResult > Paginated< TModel, TApiModel > (Func< ValueTask< PaginatableResult< TModel > > > queryGenerator, Func< TApiModel, ValueTask >? resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
virtual async ValueTask< IActionResult?> HookExecuteAction (Func< Task > executeAction, CancellationToken cancellationToken)
Hook for executing a request.
Properties inherited from Tgstation.Server.Host.Controllers.InstanceRequiredController
new Models.Instance Instance [get]
The ApiController.Instance.
Models.InstancePermissionSet InstancePermissionSet [get]
The Models.InstancePermissionSet for the request.
Properties inherited from Tgstation.Server.Host.Controllers.ComponentInterfacingController
IInstanceOperations InstanceOperations [get]
Access the IInstanceOperations instance.
Properties inherited from Tgstation.Server.Host.Controllers.ApiController
ApiHeaders? ApiHeaders [get]
The Api.ApiHeaders for the operation.
IApiHeadersProvider ApiHeadersProvider [get]
The IApiHeadersProvider containing value of ApiHeaders.
IDatabaseContext DatabaseContext [get]
The IDatabaseContext for the operation.
IAuthenticationContext AuthenticationContext [get]
The IAuthenticationContext for the operation.
ILogger< ApiController > Logger [get]
The ILogger for the ApiController.
Models.? Instance Instance [get]
The Instance for the operation.
Detailed Description
ApiController for managing InstancePermissionSets.
Definition at line 29 of file InstancePermissionSetController.cs.
Constructor & Destructor Documentation
InstancePermissionSetController()
Tgstation.Server.Host.Controllers.InstancePermissionSetController.InstancePermissionSetController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ILogger< InstancePermissionSetController > logger, IInstanceManager instanceManager, IPermissionsUpdateNotifyee permissionsUpdateNotifyee, IApiHeadersProvider apiHeaders)
Initializes a new instance of the InstancePermissionSetController class.
Parameters
databaseContext The IDatabaseContext for the InstanceRequiredController.
authenticationContext The IAuthenticationContext for the InstanceRequiredController.
logger The ILogger for the InstanceRequiredController.
instanceManager The IInstanceManager for the InstanceRequiredController.
permissionsUpdateNotifyee The value of permissionsUpdateNotifyee.
apiHeaders The IApiHeadersProvider for the InstanceRequiredController.
Definition at line 45 of file InstancePermissionSetController.cs.
            : base(
                  databaseContext,
                  authenticationContext,
                  logger,
                  instanceManager,
                  apiHeaders)
        {
            this.permissionsUpdateNotifyee = permissionsUpdateNotifyee ?? throw new ArgumentNullException(nameof(permissionsUpdateNotifyee));
        }
References Tgstation.Server.Host.Controllers.InstancePermissionSetController.permissionsUpdateNotifyee.
Member Function Documentation
Create()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.InstancePermissionSetController.Create ([FromBody] InstancePermissionSetRequest model, CancellationToken cancellationToken)
Create an InstancePermissionSet.
Parameters
model The InstancePermissionSetRequest.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the request.
<response code="201">InstancePermissionSet created successfully.</response> <response code="410">The Api.Models.PermissionSet does not exist.</response>
Definition at line 75 of file InstancePermissionSetController.cs.
        {
            ArgumentNullException.ThrowIfNull(model);
            var existingPermissionSet = await DatabaseContext
                .PermissionSets
                .AsQueryable()
                .Where(x => x.Id == model.PermissionSetId)
                .Select(x => new Models.PermissionSet
                {
                    Id = x.Id,
                    UserId = x.UserId,
                })
                .FirstOrDefaultAsync(cancellationToken);
            if (existingPermissionSet == default)
                return this.Gone();
            if (existingPermissionSet.UserId.HasValue)
            {
                var userCanonicalName = await DatabaseContext
                    .Users
                    .AsQueryable()
                    .Where(x => x.Id == existingPermissionSet.UserId.Value)
                    .Select(x => x.CanonicalName)
                    .FirstAsync(cancellationToken);
                if (userCanonicalName == Models.User.CanonicalizeName(Models.User.TgsSystemUserName))
                    return Forbid();
            }
            var dbUser = new InstancePermissionSet
            {
                EngineRights = RightsHelper.Clamp(model.EngineRights ?? EngineRights.None),
                ChatBotRights = RightsHelper.Clamp(model.ChatBotRights ?? ChatBotRights.None),
                ConfigurationRights = RightsHelper.Clamp(model.ConfigurationRights ?? ConfigurationRights.None),
                DreamDaemonRights = RightsHelper.Clamp(model.DreamDaemonRights ?? DreamDaemonRights.None),
                DreamMakerRights = RightsHelper.Clamp(model.DreamMakerRights ?? DreamMakerRights.None),
                RepositoryRights = RightsHelper.Clamp(model.RepositoryRights ?? RepositoryRights.None),
                InstancePermissionSetRights = RightsHelper.Clamp(model.InstancePermissionSetRights ?? InstancePermissionSetRights.None),
                PermissionSetId = model.PermissionSetId,
                InstanceId = Instance.Require(x => x.Id),
            };
            DatabaseContext.InstancePermissionSets.Add(dbUser);
            await DatabaseContext.Save(cancellationToken);
            // needs to be set for next call
            dbUser.PermissionSet = existingPermissionSet;
            await permissionsUpdateNotifyee.InstancePermissionSetCreated(dbUser, cancellationToken);
            return Created(dbUser.ToApi());
        }
References Tgstation.Server.Host.Controllers.ApiController.Created(), Tgstation.Server.Host.Security.IPermissionsUpdateNotifyee.InstancePermissionSetCreated(), Tgstation.Server.Host.Database.DatabaseContext.InstancePermissionSets, Tgstation.Server.Host.Database.DatabaseContext.PermissionSets, Tgstation.Server.Host.Controllers.InstancePermissionSetController.permissionsUpdateNotifyee, Tgstation.Server.Host.Database.DatabaseContext.Save(), and Tgstation.Server.Host.Database.DatabaseContext.Users.
Delete()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.InstancePermissionSetController.Delete (long id, CancellationToken cancellationToken)
Delete an InstancePermissionSet.
Parameters
id The Api.Models.Internal.InstancePermissionSet.PermissionSetId to delete.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the request.
<response code="204">Target InstancePermissionSet deleted.</response> <response code="410">Target InstancePermissionSet or no longer exists.</response>
Definition at line 252 of file InstancePermissionSetController.cs.
        {
            var numDeleted = await DatabaseContext
                .Instances
                .AsQueryable()
                .Where(x => x.Id == Instance.Id)
                .SelectMany(x => x.InstancePermissionSets)
                .Where(x => x.PermissionSetId == id)
                .ExecuteDeleteAsync(cancellationToken);
            return numDeleted > 0 ? NoContent() : this.Gone();
        }
References Tgstation.Server.Api.Models.EntityId.Id, and Tgstation.Server.Host.Database.DatabaseContext.Instances.
GetId()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.InstancePermissionSetController.GetId (long id, CancellationToken cancellationToken)
Gets a specific Api.Models.Internal.InstancePermissionSet.
Parameters
id The Api.Models.Internal.InstancePermissionSet.PermissionSetId.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the request.
<response code="200">Retrieve Api.Models.Internal.InstancePermissionSet successfully.</response> <response code="410">The requested Api.Models.Internal.InstancePermissionSet does not currently exist.</response>
Definition at line 225 of file InstancePermissionSetController.cs.
        {
            // this functions as userId
            var permissionSet = await DatabaseContext
                .Instances
                .AsQueryable()
                .Where(x => x.Id == Instance.Id)
                .SelectMany(x => x.InstancePermissionSets)
                .Where(x => x.PermissionSetId == id)
                .FirstOrDefaultAsync(cancellationToken);
            if (permissionSet == default)
                return this.Gone();
            return Json(permissionSet.ToApi());
        }
References Tgstation.Server.Api.Models.EntityId.Id, and Tgstation.Server.Host.Database.DatabaseContext.Instances.
InstancePermissionSetResponse()
ValueTask< IActionResult > Tgstation.Server.Host.Controllers.InstancePermissionSetController.InstancePermissionSetResponse (() , ValueTask. FromResultnew PaginatableResult< InstancePermissionSet >(DatabaseContext .Instances .AsQueryable() .Where(x=> x.Id==Instance.Id) .SelectMany(x=> x.InstancePermissionSets) .OrderBy(x=> x.PermissionSetId)), null , page , pageSize , cancellationToken) private
List()
ValueTask< IActionResult > Tgstation.Server.Host.Controllers.InstancePermissionSetController.List ([FromQuery] int? page, [FromQuery] int? pageSize, CancellationToken cancellationToken)
Lists InstancePermissionSets for the instance.
Parameters
page The current page.
pageSize The page size.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the request.
<response code="200">Retrieved InstancePermissionSets successfully.</response>
Read()
IActionResult Tgstation.Server.Host.Controllers.InstancePermissionSetController.Read ()
Read the active InstancePermissionSet.
Returns
The IActionResult of the request.
<response code="200">InstancePermissionSet retrieved successfully.</response>
Update()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.InstancePermissionSetController.Update ([FromBody] InstancePermissionSetRequest model, CancellationToken cancellationToken)
Update the permissions for an InstancePermissionSet.
Parameters
model The InstancePermissionSetRequest.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the request.
<response code="200">InstancePermissionSet updated successfully.</response> <response code="410">The requested InstancePermissionSet does not currently exist.</response>
Definition at line 143 of file InstancePermissionSetController.cs.
        {
            ArgumentNullException.ThrowIfNull(model);
            var originalPermissionSet = await DatabaseContext
                .Instances
                .AsQueryable()
                .Where(x => x.Id == Instance.Id)
                .SelectMany(x => x.InstancePermissionSets)
                .Where(x => x.PermissionSetId == model.PermissionSetId)
                .FirstOrDefaultAsync(cancellationToken);
            if (originalPermissionSet == null)
                return this.Gone();
            originalPermissionSet.EngineRights = RightsHelper.Clamp(model.EngineRights ?? originalPermissionSet.EngineRights!.Value);
            originalPermissionSet.RepositoryRights = RightsHelper.Clamp(model.RepositoryRights ?? originalPermissionSet.RepositoryRights!.Value);
            originalPermissionSet.InstancePermissionSetRights = RightsHelper.Clamp(model.InstancePermissionSetRights ?? originalPermissionSet.InstancePermissionSetRights!.Value);
            originalPermissionSet.ChatBotRights = RightsHelper.Clamp(model.ChatBotRights ?? originalPermissionSet.ChatBotRights!.Value);
            originalPermissionSet.ConfigurationRights = RightsHelper.Clamp(model.ConfigurationRights ?? originalPermissionSet.ConfigurationRights!.Value);
            originalPermissionSet.DreamDaemonRights = RightsHelper.Clamp(model.DreamDaemonRights ?? originalPermissionSet.DreamDaemonRights!.Value);
            originalPermissionSet.DreamMakerRights = RightsHelper.Clamp(model.DreamMakerRights ?? originalPermissionSet.DreamMakerRights!.Value);
            await DatabaseContext.Save(cancellationToken);
            var showFullPermissionSet = originalPermissionSet.PermissionSetId == AuthenticationContext.PermissionSet.Require(x => x.Id)
                || (AuthenticationContext.GetRight(RightsType.InstancePermissionSet) & (ulong)InstancePermissionSetRights.Read) != 0;
            return Json(
                showFullPermissionSet
                    ? originalPermissionSet.ToApi()
                    : new InstancePermissionSetResponse
                    {
                        PermissionSetId = originalPermissionSet.PermissionSetId,
                    });
        }
References Tgstation.Server.Host.Security.AuthenticationContext.GetRight(), Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Host.Database.DatabaseContext.Instances, Tgstation.Server.Host.Security.AuthenticationContext.PermissionSet, and Tgstation.Server.Host.Database.DatabaseContext.Save().
Member Data Documentation
permissionsUpdateNotifyee
readonly IPermissionsUpdateNotifyee Tgstation.Server.Host.Controllers.InstancePermissionSetController.permissionsUpdateNotifyee private
The IPermissionsUpdateNotifyee for the InstancePermissionSetController.
Definition at line 34 of file InstancePermissionSetController.cs.
Referenced by Tgstation.Server.Host.Controllers.InstancePermissionSetController.Create(), and Tgstation.Server.Host.Controllers.InstancePermissionSetController.InstancePermissionSetController().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Controllers/InstancePermissionSetController.cs