tgstation-server: Tgstation.Server.Host.Authority.ChatAuthority Class Reference
Tgstation.Server.Host.Authority.ChatAuthority Class Reference sealed
Public Member Functions
ChatAuthority (IInstanceManager instanceManager, IDatabaseContext databaseContext, ILogger< ChatAuthority > logger)
Initializes a new instance of the ChatAuthority class.
RequirementsGated< AuthorityResponse< ChatBot > > Create (IEnumerable< Models.ChatChannel > initialChannels, string name, string connectionString, ChatProvider provider, long instanceId, uint? reconnectionInterval, ushort? channelLimit, bool enabled, CancellationToken cancellationToken)
Create a new ChatBot.
Parameters
initialChannels The initial ChatChannels for the chat bot. Must have been previously validated to be compatible with the provider .
name The name of the chat bot.
connectionString The connection string for the chat bot.
provider The ChatProvider to use.
instanceId The ID of the instance the chat bot belongs to.
reconnectionInterval The interval in minutes that TGS attempts to reconnect the chat provider if it disconnects while it is enabled.
channelLimit The maximum number of channels that can be created for the chat bot.
enabled If the chat bot is enabled.
cancellationToken The CancellationToken for operations.
Returns
A RequirementsGated<TResult> AuthorityResponse<TResult> for the created ChatBot.
Static Private Member Functions
static ? AuthorityResponse< ChatBot > StandardModelChecks (ChatBot model, bool forCreation)
Perform some basic validation of a given model .
Additional Inherited Members
Protected Member Functions inherited from Tgstation.Server.Host.Authority.Core.ComponentInterfacingAuthorityBase
ComponentInterfacingAuthorityBase (IInstanceManager instanceManager, IDatabaseContext databaseContext, ILogger< ComponentInterfacingAuthorityBase > logger)
Initializes a new instance of the ComponentInterfacingAuthorityBase class.
async ValueTask< AuthorityResponse< TResult > > WithComponentInstance< TResult > (Func< IInstanceCore, ValueTask< AuthorityResponse< TResult > > > action, long instanceId)
Run a given action with the relevant IInstance.
Protected Member Functions inherited from Tgstation.Server.Host.Authority.Core.AuthorityBase
AuthorityBase (IDatabaseContext databaseContext, ILogger< AuthorityBase > logger)
Initializes a new instance of the AuthorityBase class.
AuthorityResponse< TResult > RateLimit< TResult > (RateLimitExceededException rateLimitException)
Generates a HttpFailureResponse.RateLimited type AuthorityResponse.
Static Protected Member Functions inherited from Tgstation.Server.Host.Authority.Core.AuthorityBase
static AuthorityResponse< TResult > BadRequest< TResult > (ErrorCode errorCode)
Generates a HttpFailureResponse.BadRequest type AuthorityResponse<TResult>.
static AuthorityResponse< TResult > Unauthorized< TResult > ()
Generates a HttpFailureResponse.Unauthorized type AuthorityResponse<TResult>.
static AuthorityResponse< TResult > Gone< TResult > ()
Generates a HttpFailureResponse.Forbidden type AuthorityResponse<TResult>.
static AuthorityResponse< TResult > Forbid< TResult > ()
Generates a HttpFailureResponse.Forbidden type AuthorityResponse<TResult>.
static AuthorityResponse< TResult > NotFound< TResult > ()
Generates a HttpFailureResponse.NotFound type AuthorityResponse<TResult>.
static AuthorityResponse< TResult > Conflict< TResult > (ErrorCode errorCode, string? additionalData=null)
Generates a HttpFailureResponse.Conflict type AuthorityResponse<TResult>.
static FlagRightsConditional< TRights > Flag< TRights > (TRights flag)
Helper to quickly construct a FlagRightsConditional<TRights>.
static OrRightsConditional< TRights > Or< TRights > (RightsConditional< TRights > lhs, RightsConditional< TRights > rhs)
Helper to quickly construct an OrRightsConditional<TRights>.
static AndRightsConditional< TRights > And< TRights > (RightsConditional< TRights > lhs, RightsConditional< TRights > rhs)
Helper to quickly construct an AndRightsConditional<TRights>.
Properties inherited from Tgstation.Server.Host.Authority.Core.AuthorityBase
IDatabaseContext DatabaseContext [get]
Gets the IDatabaseContext for the AuthorityBase.
ILogger< AuthorityBase > Logger [get]
Gets the ILogger for the AuthorityBase.
Detailed Description
Definition at line 21 of file ChatAuthority.cs.
Constructor & Destructor Documentation
ChatAuthority()
Tgstation.Server.Host.Authority.ChatAuthority.ChatAuthority (IInstanceManager instanceManager, IDatabaseContext databaseContext, ILogger< ChatAuthority > logger)
Initializes a new instance of the ChatAuthority class.
Parameters
instanceManager The IInstanceManager for the ChatAuthority.
databaseContext The AuthorityBase.DatabaseContext.
logger The AuthorityBase.Logger.
Definition at line 29 of file ChatAuthority.cs.
            : base(instanceManager, databaseContext, logger)
        {
        }
Member Function Documentation
Create()
RequirementsGated< AuthorityResponse< ChatBot > > Tgstation.Server.Host.Authority.ChatAuthority.Create (IEnumerable< Models::ChatChannel > initialChannels, string name, string connectionString, ChatProvider provider, long instanceId, uint? reconnectionInterval, ushort? channelLimit, bool enabled, CancellationToken cancellationToken)
Create a new ChatBot.
Parameters
initialChannels The initial ChatChannels for the chat bot. Must have been previously validated to be compatible with the provider .
name The name of the chat bot.
connectionString The connection string for the chat bot.
provider The ChatProvider to use.
instanceId The ID of the instance the chat bot belongs to.
reconnectionInterval The interval in minutes that TGS attempts to reconnect the chat provider if it disconnects while it is enabled.
channelLimit The maximum number of channels that can be created for the chat bot.
enabled If the chat bot is enabled.
cancellationToken The CancellationToken for operations.
Returns
A RequirementsGated<TResult> AuthorityResponse<TResult> for the created ChatBot.
Implements Tgstation.Server.Host.Authority.IChatAuthority.
Definition at line 62 of file ChatAuthority.cs.
        {
            ArgumentNullException.ThrowIfNull(initialChannels);
            ArgumentNullException.ThrowIfNull(name);
            ArgumentNullException.ThrowIfNull(connectionString);
            return new(
                () => Flag(ChatBotRights.Create),
                async () =>
                {
                    var model = new ChatBot
                    {
                        Name = name,
                        ConnectionString = connectionString,
                        Enabled = enabled,
                        InstanceId = instanceId,
                        Provider = provider,
                        ReconnectionInterval = reconnectionInterval,
                        ChannelLimit = channelLimit,
                        Channels = initialChannels.ToList(),
                    };
                    var earlyOut = StandardModelChecks(model, true);
                    if (earlyOut != null)
                        return earlyOut;
                    var query = await DatabaseContext
                        .Instances
                        .Where(instance => instance.Id == instanceId)
                        .Select(instance => new
{
                            ChatBotLimit = instance.ChatBotLimit!.Value,
                            TotalChatBots = instance.ChatSettings!.Count,
                        })
                        .FirstOrDefaultAsync(cancellationToken);
                    if (query == null)
                        return Gone<ChatBot>();
                    if (query.TotalChatBots >= query.ChatBotLimit)
                        return Conflict<ChatBot>(ErrorCode.ChatBotMax);
                    model.Enabled ??= false;
                    model.ReconnectionInterval ??= 1;
                    DatabaseContext.ChatBots.Add(model);
                    await DatabaseContext.Save(cancellationToken);
                    return await WithComponentInstance(
                        async instance =>
{
                            try
{
                                // try to create it
                                await instance.Chat.ChangeSettings(model, cancellationToken);
                                if (model.Channels.Count > 0)
                                    await instance.Chat.ChangeChannels(model.Require(x => x.Id), model.Channels, cancellationToken);
                            }
                            catch (Exception ex)
{
                                Logger.LogError(ex, "Failed to complete chat bot {id} initialization after addition, removing...", model.Id);
                                // undo the add
                                DatabaseContext.ChatBots.Remove(model);
                                // DCTx2: Operations must always run
                                await DatabaseContext.Save(default);
                                await instance.Chat.DeleteConnection(model.Require(x => x.Id), default);
                                throw;
                            }
                            return new AuthorityResponse<ChatBot>(model, HttpSuccessResponse.Created);
                        },
                        instanceId);
                },
                instanceId);
        }
References Tgstation.Server.Host.Database.DatabaseContext.ChatBots, Tgstation.Server.Host.Enabled, Tgstation.Server.Host.Database.DatabaseContext.Instances, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Authority.Core.AuthorityBase.Logger, Tgstation.Server.Host.Database.DatabaseContext.Save(), and Tgstation.Server.Host.Authority.ChatAuthority.StandardModelChecks().
StandardModelChecks()
static ? AuthorityResponse< ChatBot > Tgstation.Server.Host.Authority.ChatAuthority.StandardModelChecks (ChatBot model, bool forCreation) static private
Perform some basic validation of a given model .
Parameters
model The ChatBotApiBase to validate.
forCreation If the model is being created.
Returns
An BadRequestObjectResult to respond with or null.
Definition at line 40 of file ChatAuthority.cs.
        {
            if (model.ReconnectionInterval == 0)
                throw new InvalidOperationException("RecconnectionInterval cannot be zero!");
            if (model.Name != null && String.IsNullOrWhiteSpace(model.Name))
                return BadRequest<ChatBot>(ErrorCode.ChatBotWhitespaceName);
            if (model.ConnectionString != null && String.IsNullOrWhiteSpace(model.ConnectionString))
                return BadRequest<ChatBot>(ErrorCode.ChatBotWhitespaceConnectionString);
            var defaultMaxChannels = (ulong)Math.Max(ChatBot.DefaultChannelLimit, model.Channels?.Count ?? 0);
            if (defaultMaxChannels > UInt16.MaxValue)
                return BadRequest<ChatBot>(ErrorCode.ChatBotMaxChannels);
            if (forCreation)
                model.ChannelLimit ??= (ushort)defaultMaxChannels;
            return null;
        }
References Tgstation.Server.Host.Models.ChatBot.DefaultChannelLimit, and Tgstation.Server.Api.Rights.List.
Referenced by Tgstation.Server.Host.Authority.ChatAuthority.Create().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Authority/ChatAuthority.cs