tgstation-server: Tgstation.Server.Host.Components.Engine.WindowsOpenDreamInstaller Class Reference
Tgstation.Server.Host.Components.Engine.WindowsOpenDreamInstaller Class Reference
Implementation of OpenDreamInstaller for Windows systems.
Public Member Functions
WindowsOpenDreamInstaller (IIOManager ioManager, ILogger< WindowsOpenDreamInstaller > logger, IPlatformIdentifier platformIdentifier, IProcessExecutor processExecutor, IRepositoryManager repositoryManager, IAsyncDelayer asyncDelayer, IAbstractHttpClientFactory httpClientFactory, IOptions< GeneralConfiguration > generalConfigurationOptions, IOptions< SessionConfiguration > sessionConfigurationOptions, IFilesystemLinkFactory linkFactory)
Initializes a new instance of the WindowsOpenDreamInstaller class.
override ValueTask Install (EngineVersion version, string installPath, bool deploymentPipelineProcesses, CancellationToken cancellationToken)
Does actions necessary to get an extracted installation working.
Parameters
version The EngineVersion being installed.
path The path to the installation.
deploymentPipelineProcesses If the operation should consider processes it launches to be part of the deployment pipeline.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Public Member Functions inherited from Tgstation.Server.Host.Components.Engine.OpenDreamInstaller
OpenDreamInstaller (IIOManager ioManager, ILogger< OpenDreamInstaller > logger, IPlatformIdentifier platformIdentifier, IProcessExecutor processExecutor, IRepositoryManager repositoryManager, IAsyncDelayer asyncDelayer, IAbstractHttpClientFactory httpClientFactory, IOptions< GeneralConfiguration > generalConfigurationOptions, IOptions< SessionConfiguration > sessionConfigurationOptions)
Initializes a new instance of the OpenDreamInstaller class.
override Task CleanCache (CancellationToken cancellationToken)
Attempts to cleans the engine's cache folder for the system.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
override IEngineInstallation CreateInstallation (EngineVersion version, string path, Task installationTask)
Creates an IEngineInstallation for a given version .
Parameters
version The EngineVersion of the installation.
path The path to the installation.
installationTask The Task representing the installation process for the installation.
Returns
The IEngineInstallation.
override async ValueTask< IEngineInstallationData > DownloadVersion (EngineVersion version, JobProgressReporter? jobProgressReporter, CancellationToken cancellationToken)
Download a given engine version .
Parameters
version The EngineVersion of the engine to download.
jobProgressReporter The optional JobProgressReporter for the operation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IEngineInstallationData for the download.
override async ValueTask Install (EngineVersion version, string installPath, bool deploymentPipelineProcesses, CancellationToken cancellationToken)
Does actions necessary to get an extracted installation working.
Parameters
version The EngineVersion being installed.
path The path to the installation.
deploymentPipelineProcesses If the operation should consider processes it launches to be part of the deployment pipeline.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
override ValueTask UpgradeInstallation (EngineVersion version, string path, CancellationToken cancellationToken)
Does actions necessary to get upgrade a version installed by a previous version of TGS.
Parameters
version The EngineVersion being installed.
path The path to the installation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
override ValueTask TrustDmbPath (EngineVersion engineVersion, string fullDmbPath, CancellationToken cancellationToken)
Add a given fullDmbPath to the trusted DMBs list in BYOND's config.
Parameters
version The EngineVersion being used.
fullDmbPath Full path to the .dmb that should be trusted.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
abstract IEngineInstallation CreateInstallation (EngineVersion version, string path, Task installationTask)
Creates an IEngineInstallation for a given version .
Parameters
version The EngineVersion of the installation.
path The path to the installation.
installationTask The Task representing the installation process for the installation.
Returns
The IEngineInstallation.
abstract Task CleanCache (CancellationToken cancellationToken)
Attempts to cleans the engine's cache folder for the system.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
abstract ValueTask Install (EngineVersion version, string path, bool deploymentPipelineProcesses, CancellationToken cancellationToken)
Does actions necessary to get an extracted installation working.
Parameters
version The EngineVersion being installed.
path The path to the installation.
deploymentPipelineProcesses If the operation should consider processes it launches to be part of the deployment pipeline.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
abstract ValueTask UpgradeInstallation (EngineVersion version, string path, CancellationToken cancellationToken)
Does actions necessary to get upgrade a version installed by a previous version of TGS.
Parameters
version The EngineVersion being installed.
path The path to the installation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
abstract ValueTask< IEngineInstallationData > DownloadVersion (EngineVersion version, JobProgressReporter? jobProgressReporter, CancellationToken cancellationToken)
Download a given engine version .
Parameters
version The EngineVersion of the engine to download.
jobProgressReporter The optional JobProgressReporter for the operation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IEngineInstallationData for the download.
abstract ValueTask TrustDmbPath (EngineVersion version, string fullDmbPath, CancellationToken cancellationToken)
Add a given fullDmbPath to the trusted DMBs list in BYOND's config.
Parameters
version The EngineVersion being used.
fullDmbPath Full path to the .dmb that should be trusted.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
IEngineInstallation CreateInstallation (EngineVersion version, string path, Task installationTask)
Creates an IEngineInstallation for a given version .
ValueTask< IEngineInstallationData > DownloadVersion (EngineVersion version, JobProgressReporter? jobProgressReporter, CancellationToken cancellationToken)
Download a given engine version .
ValueTask Install (EngineVersion version, string path, bool deploymentPipelineProcesses, CancellationToken cancellationToken)
Does actions necessary to get an extracted installation working.
ValueTask UpgradeInstallation (EngineVersion version, string path, CancellationToken cancellationToken)
Does actions necessary to get upgrade a version installed by a previous version of TGS.
ValueTask TrustDmbPath (EngineVersion version, string fullDmbPath, CancellationToken cancellationToken)
Add a given fullDmbPath to the trusted DMBs list in BYOND's config.
Task CleanCache (CancellationToken cancellationToken)
Attempts to cleans the engine's cache folder for the system.
Protected Member Functions
override async ValueTask HandleExtremelyLongPathOperation (Func< string, ValueTask > shortenedPathOperation, string originalPath, CancellationToken cancellationToken)
Perform an operation on a very long path.
Parameters
shortenedPathOperation A Func<T, TResult> taking a shortened path and resulting in a ValueTask representing the running operation.
originalPath The original path to the directory.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Protected Member Functions inherited from Tgstation.Server.Host.Components.Engine.OpenDreamInstaller
virtual ValueTask HandleExtremelyLongPathOperation (Func< string, ValueTask > shortenedPathOperation, string originalPath, CancellationToken cancellationToken)
Perform an operation on a very long path.
void GetExecutablePaths (string installationPath, out string serverExePath, out string compilerExePath)
Gets the paths to the server and client executables.
Protected Member Functions inherited from Tgstation.Server.Host.Components.Engine.EngineInstallerBase
EngineInstallerBase (IIOManager ioManager, ILogger< EngineInstallerBase > logger)
Initializes a new instance of the EngineInstallerBase class.
void CheckVersionValidity (EngineVersion version)
Check that a given version is of type EngineType.Byond.
Private Member Functions
async ValueTask AddServerFirewallException (EngineVersion version, string path, bool deploymentPipelineProcesses, CancellationToken cancellationToken)
Attempt to add the DreamDaemon executable as an exception to the Windows firewall.
Private Attributes
readonly IFilesystemLinkFactory linkFactory
The IFilesystemLinkFactory for the WindowsOpenDreamInstaller.
Additional Inherited Members
Properties inherited from Tgstation.Server.Host.Components.Engine.OpenDreamInstaller
override EngineType TargetEngineType [get]
IProcessExecutor ProcessExecutor [get]
The IProcessExecutor for the OpenDreamInstaller.
GeneralConfiguration GeneralConfiguration [get]
The GeneralConfiguration for the OpenDreamInstaller.
SessionConfiguration SessionConfiguration [get]
The Configuration.SessionConfiguration for the OpenDreamInstaller.
Properties inherited from Tgstation.Server.Host.Components.Engine.EngineInstallerBase
abstract EngineType TargetEngineType [get]
The EngineType the installer supports.
IIOManager IOManager [get]
Gets the IIOManager for the EngineInstallerBase.
ILogger< EngineInstallerBase > Logger [get]
Gets the ILogger for the EngineInstallerBase.
Detailed Description
Implementation of OpenDreamInstaller for Windows systems.
Definition at line 23 of file WindowsOpenDreamInstaller.cs.
Constructor & Destructor Documentation
WindowsOpenDreamInstaller()
Tgstation.Server.Host.Components.Engine.WindowsOpenDreamInstaller.WindowsOpenDreamInstaller (IIOManager ioManager, ILogger< WindowsOpenDreamInstaller > logger, IPlatformIdentifier platformIdentifier, IProcessExecutor processExecutor, IRepositoryManager repositoryManager, IAsyncDelayer asyncDelayer, IAbstractHttpClientFactory httpClientFactory, IOptions< GeneralConfiguration > generalConfigurationOptions, IOptions< SessionConfiguration > sessionConfigurationOptions, IFilesystemLinkFactory linkFactory)
Initializes a new instance of the WindowsOpenDreamInstaller class.
Parameters
ioManager The IIOManager for the OpenDreamInstaller.
logger The ILogger<TCategoryName> for the OpenDreamInstaller.
platformIdentifier The IPlatformIdentifier for the OpenDreamInstaller.
processExecutor The IProcessExecutor for the OpenDreamInstaller.
repositoryManager The IRepositoryManager for the OpenDreamInstaller.
asyncDelayer The IAsyncDelayer for the OpenDreamInstaller.
httpClientFactory The IAbstractHttpClientFactory for the OpenDreamInstaller.
generalConfigurationOptions The IOptions<TOptions> of GeneralConfiguration for the OpenDreamInstaller.
sessionConfigurationOptions The IOptions<TOptions> of SessionConfiguration for the OpenDreamInstaller.
linkFactory The value of linkFactory.
Definition at line 43 of file WindowsOpenDreamInstaller.cs.
            : base(
                ioManager,
                logger,
                platformIdentifier,
                processExecutor,
                repositoryManager,
                asyncDelayer,
                httpClientFactory,
                generalConfigurationOptions,
                sessionConfigurationOptions)
        {
            this.linkFactory = linkFactory ?? throw new ArgumentNullException(nameof(linkFactory));
        }
References Tgstation.Server.Host.Components.Engine.WindowsOpenDreamInstaller.linkFactory.
Member Function Documentation
AddServerFirewallException()
async ValueTask Tgstation.Server.Host.Components.Engine.WindowsOpenDreamInstaller.AddServerFirewallException (EngineVersion version, string path, bool deploymentPipelineProcesses, CancellationToken cancellationToken) private
Attempt to add the DreamDaemon executable as an exception to the Windows firewall.
Parameters
version The BYOND EngineVersion.
path The path to the BYOND installation.
deploymentPipelineProcesses If the operation is part of the deployment pipeline.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Definition at line 109 of file WindowsOpenDreamInstaller.cs.
        {
            if (GeneralConfiguration.SkipAddingByondFirewallException)
                return;
            GetExecutablePaths(path, out var serverExePath, out _);
            int exitCode;
            try
            {
                // I really wish we could add the instance name here but
                // 1. It'd make IByondInstaller need to be transient per-instance and WindowsByondInstaller relys on being a singleton for its DX installer call
                // 2. The instance could be renamed, so it'd have to be an unfriendly ID anyway.
                var ruleName = $"TGS OpenDream {version}";
                exitCode = await WindowsFirewallHelper.AddFirewallException(
                    ProcessExecutor,
                    Logger,
                    ruleName,
                    serverExePath,
                    deploymentPipelineProcesses && SessionConfiguration.LowPriorityDeploymentProcesses,
                    cancellationToken);
            }
            catch (Exception ex)
            {
                throw new JobException(ErrorCode.EngineFirewallFail, ex);
            }
            if (exitCode != 0)
                throw new JobException(ErrorCode.EngineFirewallFail, new JobException($"Invalid exit code: {exitCode}"));
        }
References Tgstation.Server.Host.System.WindowsFirewallHelper.AddFirewallException(), Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.GetExecutablePaths(), Tgstation.Server.Host.Components.Engine.EngineInstallerBase.Logger, Tgstation.Server.Host.Configuration.SessionConfiguration.LowPriorityDeploymentProcesses, and Tgstation.Server.Host.Configuration.GeneralConfiguration.SkipAddingByondFirewallException.
Referenced by Tgstation.Server.Host.Components.Engine.WindowsOpenDreamInstaller.Install().
HandleExtremelyLongPathOperation()
override async ValueTask Tgstation.Server.Host.Components.Engine.WindowsOpenDreamInstaller.HandleExtremelyLongPathOperation (Func< string, ValueTask > shortenedPathOperation, string originalPath, CancellationToken cancellationToken) protected virtual
Perform an operation on a very long path.
Parameters
shortenedPathOperation A Func<T, TResult> taking a shortened path and resulting in a ValueTask representing the running operation.
originalPath The original path to the directory.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Reimplemented from Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.
Definition at line 86 of file WindowsOpenDreamInstaller.cs.
        {
            var shortPath = $"C:/{Guid.NewGuid()}";
            Logger.LogDebug("Shortening path for build from {long} to {short}...", originalPath, shortPath);
            await linkFactory.CreateSymbolicLink(originalPath, shortPath, cancellationToken);
            try
            {
                await shortenedPathOperation(shortPath);
            }
            finally
            {
                await IOManager.DeleteDirectory(shortPath, CancellationToken.None); // DCT: Should always run
            }
        }
References Tgstation.Server.Host.IO.IFilesystemLinkFactory.CreateSymbolicLink(), Tgstation.Server.Host.IO.IIOManager.DeleteDirectory(), Tgstation.Server.Host.Components.Engine.EngineInstallerBase.IOManager, Tgstation.Server.Host.Components.Engine.WindowsOpenDreamInstaller.linkFactory, and Tgstation.Server.Host.Components.Engine.EngineInstallerBase.Logger.
Install()
override ValueTask Tgstation.Server.Host.Components.Engine.WindowsOpenDreamInstaller.Install (EngineVersion version, string installPath, bool deploymentPipelineProcesses, CancellationToken cancellationToken) virtual
Does actions necessary to get an extracted installation working.
Parameters
version The EngineVersion being installed.
path The path to the installation.
deploymentPipelineProcesses If the operation should consider processes it launches to be part of the deployment pipeline.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Reimplemented from Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.
Definition at line 69 of file WindowsOpenDreamInstaller.cs.
        {
            var installTask = base.Install(
                version,
                installPath,
                deploymentPipelineProcesses,
                cancellationToken);
            var firewallTask = AddServerFirewallException(
                version,
                installPath,
                deploymentPipelineProcesses,
                cancellationToken);
            return ValueTaskExtensions.WhenAll(installTask, firewallTask);
        }
References Tgstation.Server.Host.Components.Engine.WindowsOpenDreamInstaller.AddServerFirewallException(), and Tgstation.Server.Common.Extensions.ValueTaskExtensions.WhenAll().
Member Data Documentation
linkFactory
readonly IFilesystemLinkFactory Tgstation.Server.Host.Components.Engine.WindowsOpenDreamInstaller.linkFactory private
The IFilesystemLinkFactory for the WindowsOpenDreamInstaller.
Definition at line 28 of file WindowsOpenDreamInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Engine.WindowsOpenDreamInstaller.HandleExtremelyLongPathOperation(), and Tgstation.Server.Host.Components.Engine.WindowsOpenDreamInstaller.WindowsOpenDreamInstaller().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Engine/WindowsOpenDreamInstaller.cs