tgstation-server: Tgstation.Server.Host.Controllers.AdministrationController Class Reference
Tgstation.Server.Host.Controllers.AdministrationController Class Reference sealed
ApiController for TGS administration purposes.
Public Member Functions
AdministrationController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, IGitHubServiceFactory gitHubServiceFactory, IServerControl serverControl, IServerUpdateInitiator serverUpdateInitiator, IAssemblyInformationProvider assemblyInformationProvider, IIOManager ioManager, IPlatformIdentifier platformIdentifier, IFileTransferTicketProvider fileTransferService, IMemoryCache cacheService, ILogger< AdministrationController > logger, IOptions< FileLoggingConfiguration > fileLoggingConfigurationOptions, IApiHeadersProvider apiHeadersProvider)
Initializes a new instance of the AdministrationController class.
async ValueTask< IActionResult > Read ([FromQuery] bool? fresh, CancellationToken cancellationToken)
Get AdministrationResponse server information.
async ValueTask< IActionResult > Update ([FromBody] ServerUpdateRequest model, CancellationToken cancellationToken)
Attempt to perform a server upgrade.
async ValueTask< IActionResult > Delete ()
Attempts to restart the server.
ValueTask< IActionResult > ListLogs ([FromQuery] int? page, [FromQuery] int? pageSize, CancellationToken cancellationToken)
List LogFileResponses present.
async ValueTask< IActionResult > GetLog (string path, CancellationToken cancellationToken)
Download a LogFileResponse.
Public Member Functions inherited from Tgstation.Server.Host.Controllers.ApiControllerBase
override async Task OnActionExecutionAsync (ActionExecutingContext context, ActionExecutionDelegate next)
Private Member Functions
async ValueTask< IActionResult > AttemptInitiateUpdate (Version newVersion, bool attemptingUpload, CancellationToken cancellationToken)
Attempt to initiate an update.
Private Attributes
readonly IGitHubServiceFactory gitHubServiceFactory
The IGitHubServiceFactory for the AdministrationController.
readonly IServerControl serverControl
The IServerControl for the AdministrationController.
readonly IServerUpdateInitiator serverUpdateInitiator
The IServerUpdateInitiator for the AdministrationController.
readonly IAssemblyInformationProvider assemblyInformationProvider
The IAssemblyInformationProvider for the AdministrationController.
readonly IIOManager ioManager
The IIOManager for the AdministrationController.
readonly IPlatformIdentifier platformIdentifier
The IPlatformIdentifier for the AdministrationController.
readonly IFileTransferTicketProvider fileTransferService
The IFileTransferTicketProvider for the AdministrationController.
readonly IMemoryCache cacheService
The IMemoryCache for the AdministrationController.
readonly FileLoggingConfiguration fileLoggingConfiguration
The FileLoggingConfiguration for the AdministrationController.
Static Private Attributes
const string OctokitException = "Bad GitHub API response, check configuration!"
Default Exception.Message for ApiExceptions.
static readonly object ReadCacheKey = new()
The IMemoryCache key for Read(bool?, CancellationToken).
Additional Inherited Members
Protected Member Functions inherited from Tgstation.Server.Host.Controllers.ApiController
ApiController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, IApiHeadersProvider apiHeadersProvider, ILogger< ApiController > logger, bool requireHeaders)
Initializes a new instance of the ApiController class.
override async ValueTask< IActionResult?> HookExecuteAction (Func< Task > executeAction, CancellationToken cancellationToken)
Hook for executing a request.
Parameters
executeAction A Func<TResult> that should be invoked and its response awaited to continue normal execution of the request. Should NOT be called if this method returns a non-null value.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in an IActionResult that, if not null, is executed.
new NotFoundObjectResult NotFound ()
Generic 404 response.
new ObjectResult Unauthorized ()
Generic 401 response.
ObjectResult RequiresPosixSystemIdentity (NotImplementedException ex)
Generic 501 response.
StatusCodeResult StatusCode (HttpStatusCode statusCode)
Strongly type calls to ControllerBase.StatusCode(int).
ObjectResult Created (object payload)
Generic 201 response with a given payload .
ObjectResult RateLimit (RateLimitExceededException rateLimitException)
429 response for a given rateLimitException .
virtual ValueTask< IActionResult?> ValidateRequest (CancellationToken cancellationToken)
Performs validation a request.
IActionResult HeadersIssue (HeadersException headersException)
Response for missing/Invalid headers.
ValueTask< IActionResult > Paginated< TModel > (Func< ValueTask< PaginatableResult< TModel > > > queryGenerator, Func< TModel, ValueTask >? resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
ValueTask< IActionResult > Paginated< TModel, TApiModel > (Func< ValueTask< PaginatableResult< TModel > > > queryGenerator, Func< TApiModel, ValueTask >? resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
Properties inherited from Tgstation.Server.Host.Controllers.ApiController
ApiHeaders? ApiHeaders [get]
The Api.ApiHeaders for the operation.
IApiHeadersProvider ApiHeadersProvider [get]
The IApiHeadersProvider containing value of ApiHeaders.
IDatabaseContext DatabaseContext [get]
The IDatabaseContext for the operation.
IAuthenticationContext AuthenticationContext [get]
The IAuthenticationContext for the operation.
ILogger< ApiController > Logger [get]
The ILogger for the ApiController.
Models.? Instance Instance [get]
The Instance for the operation.
Detailed Description
ApiController for TGS administration purposes.
Definition at line 39 of file AdministrationController.cs.
Constructor & Destructor Documentation
AdministrationController()
Tgstation.Server.Host.Controllers.AdministrationController.AdministrationController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, IGitHubServiceFactory gitHubServiceFactory, IServerControl serverControl, IServerUpdateInitiator serverUpdateInitiator, IAssemblyInformationProvider assemblyInformationProvider, IIOManager ioManager, IPlatformIdentifier platformIdentifier, IFileTransferTicketProvider fileTransferService, IMemoryCache cacheService, ILogger< AdministrationController > logger, IOptions< FileLoggingConfiguration > fileLoggingConfigurationOptions, IApiHeadersProvider apiHeadersProvider)
Initializes a new instance of the AdministrationController class.
Parameters
databaseContext The IDatabaseContext for the ApiController.
authenticationContext The IAuthenticationContext for the ApiController.
gitHubServiceFactory The value of gitHubServiceFactory.
serverControl The value of serverControl.
serverUpdateInitiator The value of serverUpdateInitiator.
assemblyInformationProvider The value of assemblyInformationProvider.
ioManager The value of ioManager.
platformIdentifier The value of platformIdentifier.
fileTransferService The value of fileTransferService.
cacheService The value of cacheService.
logger The ILogger for the ApiController.
fileLoggingConfigurationOptions The IOptions<TOptions> containing value of fileLoggingConfiguration.
apiHeadersProvider The IApiHeadersProvider for the ApiController.
Definition at line 112 of file AdministrationController.cs.
            : base(
                databaseContext,
                authenticationContext,
                apiHeadersProvider,
                logger,
                true)
        {
            this.gitHubServiceFactory = gitHubServiceFactory ?? throw new ArgumentNullException(nameof(gitHubServiceFactory));
            this.serverControl = serverControl ?? throw new ArgumentNullException(nameof(serverControl));
            this.serverUpdateInitiator = serverUpdateInitiator ?? throw new ArgumentNullException(nameof(serverUpdateInitiator));
            this.assemblyInformationProvider = assemblyInformationProvider ?? throw new ArgumentNullException(nameof(assemblyInformationProvider));
            this.ioManager = ioManager ?? throw new ArgumentNullException(nameof(ioManager));
            this.platformIdentifier = platformIdentifier ?? throw new ArgumentNullException(nameof(platformIdentifier));
            this.fileTransferService = fileTransferService ?? throw new ArgumentNullException(nameof(fileTransferService));
            this.cacheService = cacheService ?? throw new ArgumentNullException(nameof(cacheService));
            fileLoggingConfiguration = fileLoggingConfigurationOptions?.Value ?? throw new ArgumentNullException(nameof(fileLoggingConfigurationOptions));
        }
References Tgstation.Server.Host.Controllers.AdministrationController.assemblyInformationProvider, Tgstation.Server.Host.Controllers.AdministrationController.cacheService, Tgstation.Server.Host.Controllers.AdministrationController.fileLoggingConfiguration, Tgstation.Server.Host.Controllers.AdministrationController.fileTransferService, Tgstation.Server.Host.Controllers.AdministrationController.gitHubServiceFactory, Tgstation.Server.Host.Controllers.AdministrationController.ioManager, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Controllers.AdministrationController.platformIdentifier, Tgstation.Server.Host.Controllers.AdministrationController.serverControl, and Tgstation.Server.Host.Controllers.AdministrationController.serverUpdateInitiator.
Member Function Documentation
AttemptInitiateUpdate()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.AdministrationController.AttemptInitiateUpdate (Version newVersion, bool attemptingUpload, CancellationToken cancellationToken) private
Attempt to initiate an update.
Parameters
newVersion The Version being updated to.
attemptingUpload If an upload is being attempted.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the request.
Definition at line 410 of file AdministrationController.cs.
        {
            IFileUploadTicket? uploadTicket = attemptingUpload
                ? fileTransferService.CreateUpload(FileUploadStreamKind.None)
                : null;
            ServerUpdateResult updateResult;
            try
            {
                try
                {
                    updateResult = await serverUpdateInitiator.InitiateUpdate(uploadTicket, newVersion, cancellationToken);
                }
                catch
                {
                    if (attemptingUpload)
                        await uploadTicket!.DisposeAsync();
                    throw;
                }
            }
            catch (RateLimitExceededException e)
            {
                return RateLimit(e);
            }
            catch (ApiException e)
            {
                Logger.LogWarning(e, OctokitException);
                return this.StatusCode(HttpStatusCode.FailedDependency, new ErrorMessageResponse(ErrorCode.RemoteApiError)
                {
                    AdditionalData = e.Message,
                });
            }
            return updateResult switch
            {
                ServerUpdateResult.Started => Accepted(new ServerUpdateResponse(newVersion, uploadTicket?.Ticket.FileTicket)),
                ServerUpdateResult.ReleaseMissing => this.Gone(),
                ServerUpdateResult.UpdateInProgress => BadRequest(new ErrorMessageResponse(ErrorCode.ServerUpdateInProgress)),
                ServerUpdateResult.SwarmIntegrityCheckFailed => this.StatusCode(HttpStatusCode.FailedDependency, new ErrorMessageResponse(ErrorCode.SwarmIntegrityCheckFailed)),
                _ => throw new InvalidOperationException($"Unexpected ServerUpdateResult: {updateResult}"),
            };
        }
References Tgstation.Server.Host.Transfer.IFileTransferTicketProvider.CreateUpload(), Tgstation.Server.Host.Controllers.AdministrationController.fileTransferService, Tgstation.Server.Host.Core.IServerUpdateInitiator.InitiateUpdate(), Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Controllers.ApiController.Logger, Tgstation.Server.Host.Controllers.AdministrationController.OctokitException, Tgstation.Server.Host.Controllers.ApiController.RateLimit(), Tgstation.Server.Host.Controllers.AdministrationController.serverUpdateInitiator, and Tgstation.Server.Host.Controllers.ApiController.StatusCode().
Referenced by Tgstation.Server.Host.Controllers.AdministrationController.Update().
Delete()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.AdministrationController.Delete ()
Attempts to restart the server.
Returns
A ValueTask<TResult> resulting in the IActionResult of the request.
<response code="204">Restart begun successfully.</response> <response code="422">Restart operations are unavailable due to the launch configuration of TGS.</response>
Definition at line 279 of file AdministrationController.cs.
        {
            try
            {
                if (!serverControl.WatchdogPresent)
                {
                    Logger.LogDebug("Restart request failed due to lack of host watchdog!");
                    return UnprocessableEntity(new ErrorMessageResponse(ErrorCode.MissingHostWatchdog));
                }
                await serverControl.Restart();
                return NoContent();
            }
            catch (InvalidOperationException)
            {
                return StatusCode(HttpStatusCode.ServiceUnavailable);
            }
        }
References Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Controllers.ApiController.Logger, Tgstation.Server.Host.Core.IServerControl.Restart(), Tgstation.Server.Host.Controllers.AdministrationController.serverControl, Tgstation.Server.Host.Controllers.ApiController.StatusCode(), and Tgstation.Server.Host.Core.IServerControl.WatchdogPresent.
GetLog()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.AdministrationController.GetLog (string path, CancellationToken cancellationToken)
Download a LogFileResponse.
Parameters
path The path to download.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the request.
<response code="200">Downloaded LogFileResponse successfully.</response> <response code="409">An IO error occurred while downloading.</response>
Definition at line 364 of file AdministrationController.cs.
        {
            ArgumentNullException.ThrowIfNull(path);
            path = HttpUtility.UrlDecode(path);
            // guard against directory navigation
            var sanitizedPath = ioManager.GetFileName(path);
            if (path != sanitizedPath)
                return Forbid();
            var fullPath = ioManager.ConcatPath(
                fileLoggingConfiguration.GetFullLogDirectory(ioManager, assemblyInformationProvider, platformIdentifier),
                path);
            try
            {
                var fileTransferTicket = fileTransferService.CreateDownload(
                    new FileDownloadProvider(
                        () => null,
                        null,
                        fullPath,
                        true));
                return Ok(new LogFileResponse
                {
                    Name = path,
                    LastModified = await ioManager.GetLastModified(fullPath, cancellationToken),
                    FileTicket = fileTransferTicket.FileTicket,
                });
            }
            catch (IOException ex)
            {
                return Conflict(new ErrorMessageResponse(ErrorCode.IOError)
                {
                    AdditionalData = ex.ToString(),
                });
            }
        }
References Tgstation.Server.Host.Controllers.AdministrationController.assemblyInformationProvider, Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.Transfer.IFileTransferTicketProvider.CreateDownload(), Tgstation.Server.Host.Controllers.AdministrationController.fileLoggingConfiguration, Tgstation.Server.Host.Controllers.AdministrationController.fileTransferService, Tgstation.Server.Host.IO.IIOManager.GetFileName(), Tgstation.Server.Host.Configuration.FileLoggingConfiguration.GetFullLogDirectory(), Tgstation.Server.Host.IO.IIOManager.GetLastModified(), Tgstation.Server.Host.Controllers.AdministrationController.ioManager, Tgstation.Server.Api.Rights.List, and Tgstation.Server.Host.Controllers.AdministrationController.platformIdentifier.
ListLogs()
ValueTask< IActionResult > Tgstation.Server.Host.Controllers.AdministrationController.ListLogs ([FromQuery] int? page, [FromQuery] int? pageSize, CancellationToken cancellationToken)
List LogFileResponses present.
Parameters
page The current page.
pageSize The page size.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the request.
<response code="200">Listed logs successfully.</response> <response code="409">An IO error occurred while listing.</response>
References Tgstation.Server.Host.Controllers.AdministrationController.assemblyInformationProvider, Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.Controllers.AdministrationController.fileLoggingConfiguration, Tgstation.Server.Host.IO.IIOManager.GetFileName(), Tgstation.Server.Host.IO.IIOManager.GetFiles(), Tgstation.Server.Host.Configuration.FileLoggingConfiguration.GetFullLogDirectory(), Tgstation.Server.Host.Controllers.AdministrationController.ioManager, Tgstation.Server.Api.Rights.List, and Tgstation.Server.Host.Controllers.AdministrationController.platformIdentifier.
Read()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.AdministrationController.Read ([FromQuery] bool? fresh, CancellationToken cancellationToken)
Get AdministrationResponse server information.
Parameters
fresh If true, the cache should be bypassed.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult for the operation.
<response code="200">Retrieved AdministrationResponse data successfully.</response> <response code="424">The GitHub API rate limit was hit. See response header Retry-After.</response> <response code="429">A GitHub API error occurred. See error message for details.</response>
Definition at line 158 of file AdministrationController.cs.
        {
            try
            {
                async Task<JsonResult> CacheFactory()
                {
                    Version? greatestVersion = null;
                    Uri? repoUrl = null;
                    try
                    {
                        var gitHubService = await gitHubServiceFactory.CreateService(cancellationToken);
                        var repositoryUrlTask = gitHubService.GetUpdatesRepositoryUrl(cancellationToken);
                        var releases = await gitHubService.GetTgsReleases(cancellationToken);
                        foreach (var kvp in releases)
{
                            var version = kvp.Key;
                            var release = kvp.Value;
                            if (version.Major > 3 // Forward/backward compatible but not before TGS4
                                && (greatestVersion == null || version > greatestVersion))
                                greatestVersion = version;
                        }
                        repoUrl = await repositoryUrlTask;
                    }
                    catch (NotFoundException e)
                    {
                        Logger.LogWarning(e, "Not found exception while retrieving upstream repository info!");
                    }
                    return Json(new AdministrationResponse
                    {
                        LatestVersion = greatestVersion,
                        TrackedRepositoryUrl = repoUrl,
                        GeneratedAt = DateTimeOffset.UtcNow,
                    });
                }
                var ttl = TimeSpan.FromMinutes(30);
                Task<JsonResult> task;
                if (fresh == true || !cacheService.TryGetValue(ReadCacheKey, out var rawCacheObject))
                {
                    using var entry = cacheService.CreateEntry(ReadCacheKey);
                    entry.AbsoluteExpirationRelativeToNow = ttl;
                    entry.Value = task = CacheFactory();
                }
                else
                    task = (Task<JsonResult>)rawCacheObject!;
                return await task;
            }
            catch (RateLimitExceededException e)
            {
                return RateLimit(e);
            }
            catch (ApiException e)
            {
                Logger.LogWarning(e, OctokitException);
                return this.StatusCode(HttpStatusCode.FailedDependency, new ErrorMessageResponse(ErrorCode.RemoteApiError)
                {
                    AdditionalData = e.Message,
                });
            }
        }
References Tgstation.Server.Host.Controllers.AdministrationController.cacheService, Tgstation.Server.Host.Utils.GitHub.IGitHubServiceFactory.CreateService(), Tgstation.Server.Host.Controllers.AdministrationController.gitHubServiceFactory, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Controllers.ApiController.Logger, Tgstation.Server.Host.Controllers.AdministrationController.OctokitException, Tgstation.Server.Host.Controllers.ApiController.RateLimit(), Tgstation.Server.Host.Controllers.AdministrationController.ReadCacheKey, and Tgstation.Server.Host.Controllers.ApiController.StatusCode().
Update()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.AdministrationController.Update ([FromBody] ServerUpdateRequest model, CancellationToken cancellationToken)
Attempt to perform a server upgrade.
Parameters
model The ServerUpdateRequest.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult for the operation.
<response code="202">Update has been started successfully.</response> <response code="410">The requested release version could not be found in the target GitHub repository.</response> <response code="422">Upgrade operations are unavailable due to the launch configuration of TGS.</response> <response code="424">A GitHub rate limit was encountered or the swarm integrity check failed.</response> <response code="429">A GitHub API error occurred.</response>
Definition at line 241 of file AdministrationController.cs.
        {
            ArgumentNullException.ThrowIfNull(model);
            var attemptingUpload = model.UploadZip == true;
            if (attemptingUpload)
            {
                if (!AuthenticationContext.PermissionSet.AdministrationRights!.Value.HasFlag(AdministrationRights.UploadVersion))
                    return Forbid();
            }
            else if (!AuthenticationContext.PermissionSet.AdministrationRights!.Value.HasFlag(AdministrationRights.ChangeVersion))
                return Forbid();
            if (model.NewVersion == null)
                return BadRequest(new ErrorMessageResponse(ErrorCode.ModelValidationFailure)
                {
                    AdditionalData = "newVersion is required!",
                });
            if (model.NewVersion.Major < 3)
                return BadRequest(new ErrorMessageResponse(ErrorCode.CannotChangeServerSuite));
            if (!serverControl.WatchdogPresent)
                return UnprocessableEntity(new ErrorMessageResponse(ErrorCode.MissingHostWatchdog));
            return await AttemptInitiateUpdate(model.NewVersion, attemptingUpload, cancellationToken);
        }
References Tgstation.Server.Api.Models.PermissionSet.AdministrationRights, Tgstation.Server.Host.Controllers.AdministrationController.AttemptInitiateUpdate(), Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Security.AuthenticationContext.PermissionSet, Tgstation.Server.Host.Controllers.AdministrationController.serverControl, and Tgstation.Server.Host.Core.IServerControl.WatchdogPresent.
Member Data Documentation
assemblyInformationProvider
readonly IAssemblyInformationProvider Tgstation.Server.Host.Controllers.AdministrationController.assemblyInformationProvider private
The IAssemblyInformationProvider for the AdministrationController.
Definition at line 69 of file AdministrationController.cs.
Referenced by Tgstation.Server.Host.Controllers.AdministrationController.AdministrationController(), Tgstation.Server.Host.Controllers.AdministrationController.GetLog(), and Tgstation.Server.Host.Controllers.AdministrationController.ListLogs().
cacheService
readonly IMemoryCache Tgstation.Server.Host.Controllers.AdministrationController.cacheService private
The IMemoryCache for the AdministrationController.
Definition at line 89 of file AdministrationController.cs.
Referenced by Tgstation.Server.Host.Controllers.AdministrationController.AdministrationController(), and Tgstation.Server.Host.Controllers.AdministrationController.Read().
fileLoggingConfiguration
readonly FileLoggingConfiguration Tgstation.Server.Host.Controllers.AdministrationController.fileLoggingConfiguration private
The FileLoggingConfiguration for the AdministrationController.
Definition at line 94 of file AdministrationController.cs.
Referenced by Tgstation.Server.Host.Controllers.AdministrationController.AdministrationController(), Tgstation.Server.Host.Controllers.AdministrationController.GetLog(), and Tgstation.Server.Host.Controllers.AdministrationController.ListLogs().
fileTransferService
readonly IFileTransferTicketProvider Tgstation.Server.Host.Controllers.AdministrationController.fileTransferService private
The IFileTransferTicketProvider for the AdministrationController.
Definition at line 84 of file AdministrationController.cs.
Referenced by Tgstation.Server.Host.Controllers.AdministrationController.AdministrationController(), Tgstation.Server.Host.Controllers.AdministrationController.AttemptInitiateUpdate(), and Tgstation.Server.Host.Controllers.AdministrationController.GetLog().
gitHubServiceFactory
readonly IGitHubServiceFactory Tgstation.Server.Host.Controllers.AdministrationController.gitHubServiceFactory private
The IGitHubServiceFactory for the AdministrationController.
Definition at line 54 of file AdministrationController.cs.
Referenced by Tgstation.Server.Host.Controllers.AdministrationController.AdministrationController(), and Tgstation.Server.Host.Controllers.AdministrationController.Read().
ioManager
readonly IIOManager Tgstation.Server.Host.Controllers.AdministrationController.ioManager private
The IIOManager for the AdministrationController.
Definition at line 74 of file AdministrationController.cs.
Referenced by Tgstation.Server.Host.Controllers.AdministrationController.AdministrationController(), Tgstation.Server.Host.Controllers.AdministrationController.GetLog(), and Tgstation.Server.Host.Controllers.AdministrationController.ListLogs().
OctokitException
const string Tgstation.Server.Host.Controllers.AdministrationController.OctokitException = "Bad GitHub API response, check configuration!" static private
Default Exception.Message for ApiExceptions.
Definition at line 44 of file AdministrationController.cs.
Referenced by Tgstation.Server.Host.Controllers.AdministrationController.AttemptInitiateUpdate(), and Tgstation.Server.Host.Controllers.AdministrationController.Read().
platformIdentifier
readonly IPlatformIdentifier Tgstation.Server.Host.Controllers.AdministrationController.platformIdentifier private
The IPlatformIdentifier for the AdministrationController.
Definition at line 79 of file AdministrationController.cs.
Referenced by Tgstation.Server.Host.Controllers.AdministrationController.AdministrationController(), Tgstation.Server.Host.Controllers.AdministrationController.GetLog(), and Tgstation.Server.Host.Controllers.AdministrationController.ListLogs().
ReadCacheKey
readonly object Tgstation.Server.Host.Controllers.AdministrationController.ReadCacheKey = new() static private
The IMemoryCache key for Read(bool?, CancellationToken).
Definition at line 49 of file AdministrationController.cs.
Referenced by Tgstation.Server.Host.Controllers.AdministrationController.Read().
serverControl
readonly IServerControl Tgstation.Server.Host.Controllers.AdministrationController.serverControl private
The IServerControl for the AdministrationController.
Definition at line 59 of file AdministrationController.cs.
Referenced by Tgstation.Server.Host.Controllers.AdministrationController.AdministrationController(), Tgstation.Server.Host.Controllers.AdministrationController.Delete(), and Tgstation.Server.Host.Controllers.AdministrationController.Update().
serverUpdateInitiator
readonly IServerUpdateInitiator Tgstation.Server.Host.Controllers.AdministrationController.serverUpdateInitiator private
The IServerUpdateInitiator for the AdministrationController.
Definition at line 64 of file AdministrationController.cs.
Referenced by Tgstation.Server.Host.Controllers.AdministrationController.AdministrationController(), and Tgstation.Server.Host.Controllers.AdministrationController.AttemptInitiateUpdate().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Controllers/AdministrationController.cs