tgstation-server: TGS.Server.Server Class Reference
TGS.Server.Server Class Reference
The windows service the application runs as
Public Member Functions
Server (string[] args, ILogger logger)
Construct a Server
void VerifyConnection ()
Does nothing on the server end, but if the call completes, you can be sure you are connected. WCF won't throw until you try until you actually use the API
void PrepareForUpdate ()
Next stop of the service will not close DD and sets a flag for it to reattach once it restarts
ushort RemoteAccessPort ()
Get the port used for remote operation
string SetRemoteAccessPort (ushort port)
Set the port used for remote operation Requires a service restart to take effect
string Version ()
Retrieve's the service's version
bool SetPythonPath (string path)
Sets the path to the python 2.7 installation
string PythonPath ()
Gets the path to the python 2.7 installation
IList< InstanceMetadata > ListInstances ()
List instances that the caller can access
string CreateInstance (string Name, string path)
Creates a new ITGInstance
string ImportInstance (string path)
Registers an existing server instance
bool InstanceEnabled (string Name)
Checks if an instance is online
string SetInstanceEnabled (string Name, bool enabled)
Sets an instance's enabled status
string RenameInstance (string name, string new_name)
Renames an instance, this will restart the instance if it is enabled
string DetachInstance (string name)
Disables and unregisters an instance, allowing the folder and data to be manipulated manually
void Dispose ()
Implements the IDisposable pattern
Static Public Member Functions
static WindowsImpersonationContext BeginImpersonation ()
Begins user impersonation to allow proper restricted file access
Public Attributes
const byte LoggingID = 0
The logging ID used for Server events
const string MigrationConfigDirectory = "C:\\TGSSettingUpgradeTempDir"
The directory to use when importing a .NET settings based config
Static Public Attributes
static readonly string VersionString = String.Format("/tg/station 13 Server v{0}", Assembly.GetExecutingAssembly().GetName().Version)
The service version string based on the AssemblyName's System.Version
Properties
static ILogger Logger [get, private set]
Singleton ILogger
static ServerConfig Config [get, private set]
The ServerConfig for the Server
Private Member Functions
IEnumerable< IInstanceConfig > GetInstanceConfigs ()
Enumerates configured IInstanceConfigs. Detaches those that fail to load
void ChangePortFromCommandLine (string[] args)
Overrides and saves the configured ServerConfig.RemoteAccessPort if requested by command line parameters
void SetupConfig ()
Upgrades up the service configuration
void SetupService ()
Creates the ServiceHost for ITGSService
void OnlineAllHosts ()
Opens all created ServiceHosts
void SetupInstances ()
Creates ServiceHosts for all Instances as listed in ServerConfig.InstancePaths, detaches bad ones
void UnlockLoggingID (byte ID)
Unlocks a Instance.LoggingID acquired with LockLoggingID
byte LockLoggingID ()
Gets and locks a Instance.LoggingID
ServiceHost SetupInstance (IInstanceConfig config)
Creates and starts a ServiceHost for a Instance at config
void AddEndpoint (ServiceHost host, Type typetype)
Adds a WCF endpoint for a component typetype
void OnStop ()
Shuts down all active ServiceHosts and calls IDisposable.Dispose on it's Instance
string SetupOneInstance (IInstanceConfig config)
Starts and onlines an instance located at config
string SetInstanceEnabledImpl (string Name, bool enabled, out string path)
Sets a Instance's enabled status
void Dispose (bool disposing)
Implements the IDisposable pattern. Calls OnStop
Static Private Member Functions
static string CheckInstanceName (string instanceName)
Checks an instanceName for illegal characters
static ServiceHost CreateHost (object singleton, string endpointPostfix)
Creates a ServiceHost for singleton using the default pipe, CloseTimeout for the ServiceHost, and the configured ServerConfig.RemoteAccessPort
Private Attributes
ServiceHost serviceHost
The WCF host that contains ITGSService connects to
IDictionary< string, ServiceHost > hosts
Map of InstanceConfig.Name to the respective ServiceHost hosting the Instance
IList< int > UsedLoggingIDs = new List<int>()
List of Instance.LoggingIDs in use
bool disposedValue = false
To detect redundant Dispose() calls
Static Private Attributes
static readonly string DefaultConfigDirectory = Directory.CreateDirectory(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "TGS.Server")).FullName
The directory to load and save ServerConfigs to
Detailed Description
The windows service the application runs as
Definition at line 17 of file Server.cs.
Constructor & Destructor Documentation
TGS.Server.Server.Server (string[] args, ILogger logger)
Construct a Server
Parameters
args Command line arguments for the Server
logger The ILogger to use
Definition at line 90 of file Server.cs.
         {
             Logger = logger;
             Environment.CurrentDirectory = Directory.CreateDirectory(Path.Combine(Path.GetTempPath(), Assembly.GetExecutingAssembly().GetName().Name)).FullName;  //MOVE THIS POINTER BECAUSE ONE TIME I ALMOST ACCIDENTALLY NUKED MYSELF BY REFACTORING! http://imgur.com/zvGEpJD.png
             SetupConfig();
             ChangePortFromCommandLine(args);
             SetupService();
             SetupInstances();
             OnlineAllHosts();
         }
Member Function Documentation
void TGS.Server.Server.AddEndpoint (ServiceHost host, Type typetype) private
Adds a WCF endpoint for a component typetype
Parameters
host The service host to add the component to
typetype The type of the component
Definition at line 335 of file Server.cs.
References TGS.Interface.Definitions.TransferLimitLocal, and TGS.Interface.Definitions.TransferLimitRemote.
         {
             var bindingName = typetype.Name;
             host.AddServiceEndpoint(typetype, new NetNamedPipeBinding() { SendTimeout = new TimeSpan(0, 0, 30), MaxReceivedMessageSize = Definitions.TransferLimitLocal }, bindingName);
             var httpsBinding = new BasicHttpsBinding()
             {
                 SendTimeout = new TimeSpan(0, 0, 40),
                 MaxReceivedMessageSize = Definitions.TransferLimitRemote
             };
             var requireAuth = typetype.Name != typeof(ITGConnectivity).Name;
             host.AddServiceEndpoint(typetype, httpsBinding, bindingName);
         }
static WindowsImpersonationContext TGS.Server.Server.BeginImpersonation () static
Begins user impersonation to allow proper restricted file access
Returns
A WindowsImpersonationContext representing the impersonation
Definition at line 53 of file Server.cs.
Referenced by TGS.Server.Instance.DeleteFile(), TGS.Server.Instance.ListStaticDirectory(), TGS.Server.Instance.ReadText(), and TGS.Server.Instance.WriteText().
         {
             return WindowsIdentity.Impersonate(OperationContext.Current.ServiceSecurityContext.WindowsIdentity.Token);
         }
void TGS.Server.Server.ChangePortFromCommandLine (string[] args) private
Overrides and saves the configured ServerConfig.RemoteAccessPort if requested by command line parameters
Parameters
args The command line parameters for the Server
Definition at line 141 of file Server.cs.
         {
             for (var I = 0; I < args.Length - 1; ++I)
                 if (args[I].ToLower() == "-port")
                 {
                     try
                     {
                         var res = Convert.ToUInt16(args[I + 1]);
                         if (res == 0)
                             throw new Exception("Cannot bind to port 0");
                         Config.RemoteAccessPort = res;
                     }
                     catch (Exception e)
                     {
                         throw new Exception("Invalid argument for \"-port\"", e);
                     }
                     Config.Save(DefaultConfigDirectory);
                     break;
                 }
         }
static string TGS.Server.Server.CheckInstanceName (string instanceName) static private
Checks an instanceName for illegal characters
Parameters
instanceName The Instance name to check
Returns
if instanceName contains no illegal characters, error message otherwise
Definition at line 63 of file Server.cs.
         {
             char[] bannedCharacters = { ';', '&', '=', '%' };
             foreach (var I in bannedCharacters)
                 if (instanceName.Contains(I.ToString()))
                     return "Instance names may not contain the following characters: ';', '&', '=', or '%'";
             return null;
         }
static ServiceHost TGS.Server.Server.CreateHost (object singleton, string endpointPostfix) static private
Creates a ServiceHost for singleton using the default pipe, CloseTimeout for the ServiceHost, and the configured ServerConfig.RemoteAccessPort
Parameters
singleton The ServiceHost.SingletonInstance
endpointPostfix The URL to access components on the ServiceHost
Returns
The created ServiceHost
Definition at line 219 of file Server.cs.
         {
             return new ServiceHost(singleton, new Uri[] { new Uri(String.Format("net.pipe://localhost/{0}", endpointPostfix)), new Uri(String.Format("https://localhost:{0}/{1}", Config.RemoteAccessPort, endpointPostfix)) })
             {
                 CloseTimeout = new TimeSpan(0, 0, 5)
             };
         }
string TGS.Server.Server.CreateInstance (string Name, string path)
Creates a new ITGInstance
Implements TGS.Interface.Components.ITGInstanceManager.
Definition at line 438 of file Server.cs.
References TGS.Server.Helpers.NormalizePath(), and TGS.Server.IInstanceConfig.Save().
         {
             path = Helpers.NormalizePath(path);
             var res = CheckInstanceName(Name);
             if (res != null)
                 return res;
             if (File.Exists(path) || Directory.Exists(path))
                 return "Cannot create instance at pre-existing path!";
             lock (this)
             {
                 if (Config.InstancePaths.Contains(path))
                     return String.Format("Instance at {0} already exists!", path);
                 foreach (var oic in GetInstanceConfigs())
                     if (Name == oic.Name)
                         return String.Format("Instance named {0} already exists!", oic.Name);
                 IInstanceConfig ic;
                 try
                 {
                     ic = new InstanceConfig(path)
                     {
                         Name = Name
                     };
                     Directory.CreateDirectory(path);
                     ic.Save();
                     Config.InstancePaths.Add(path);
                 }
                 catch (Exception e)
                 {
                     return e.ToString();
                 }
                 return SetupOneInstance(ic);
             }
         }
string TGS.Server.Server.DetachInstance (string name)
Disables and unregisters an instance, allowing the folder and data to be manipulated manually
Implements TGS.Interface.Components.ITGInstanceManager.
Definition at line 635 of file Server.cs.
         {
             lock (this)
             {
                 var res = SetInstanceEnabledImpl(name, false, out string path);
                 if (res != null)
                     return res;
                 if (path == null)    //gotta find it ourselves
                     foreach (var ic in GetInstanceConfigs())
                         if (ic.Name == name)
{
                             path = ic.Directory;
                             break;
                         }
                 if (path == null)
                     return String.Format("No instance named {0} exists!", name);
                 Config.InstancePaths.Remove(path);
                 return null;
             }
         }
void TGS.Server.Server.Dispose (bool disposing) private
Implements the IDisposable pattern. Calls OnStop
Parameters
disposing if Dispose() was called manually, if it was from the finalizer
Definition at line 666 of file Server.cs.
Referenced by TGS.Server.Service.Service.OnStop().
         {
             if (!disposedValue)
             {
                 if (disposing)
                 {
                     OnStop();
                 }
                 // TODO: free unmanaged resources (unmanaged objects) and override a finalizer below.
                 // TODO: set large fields to null.
                 disposedValue = true;
             }
         }
void TGS.Server.Server.Dispose ()
Implements the IDisposable pattern
Definition at line 691 of file Server.cs.
         {
             // Do not change this code. Put cleanup code in Dispose(bool disposing) above.
             Dispose(true);
             // TODO: uncomment the following line if the finalizer is overridden above.
             // GC.SuppressFinalize(this);
         }
IEnumerable<IInstanceConfig> TGS.Server.Server.GetInstanceConfigs () private
Enumerates configured IInstanceConfigs. Detaches those that fail to load
Returns
Each configured IInstanceConfig
Definition at line 111 of file Server.cs.
References TGS.Server.InstanceConfig.Load().
         {
             var pathsToRemove = new List<string>();
             lock (this)
             {
                 var IPS = Config.InstancePaths;
                 foreach (var I in IPS)
                 {
                     IInstanceConfig ic;
                     try
                     {
                         ic = InstanceConfig.Load(I);
                     }
                     catch (Exception e)
                     {
                         Logger.WriteError(String.Format("Unable load instance config at path {0}. Error: {1} Detaching...", I, e.ToString()), EventID.InstanceInitializationFailure, LoggingID);
                         pathsToRemove.Add(I);
                         continue;
                     }
                     yield return ic;
                 }
                 foreach (var I in pathsToRemove)
                     IPS.Remove(I);
             }
         }
string TGS.Server.Server.ImportInstance (string path)
Registers an existing server instance
Implements TGS.Interface.Components.ITGInstanceManager.
Definition at line 498 of file Server.cs.
References TGS.Server.InstanceConfig.Load(), TGS.Server.IInstanceConfig.Name, TGS.Server.Helpers.NormalizePath(), and TGS.Server.IInstanceConfig.Save().
         {
             path = Helpers.NormalizePath(path);
             lock (this)
             {
                 if (Config.InstancePaths.Contains(path))
                     return String.Format("Instance at {0} already exists!", path);
                 if(!Directory.Exists(path))
                     return String.Format("There is no instance located at {0}!", path);
                 IInstanceConfig ic;
                 try
                 {
                     ic = InstanceConfig.Load(path);
                     foreach(var oic in GetInstanceConfigs())
                         if(ic.Name == oic.Name)
                             return String.Format("Instance named {0} already exists!", oic.Name);
                     ic.Save();
                     Config.InstancePaths.Add(path);
                 }
                 catch (Exception e)
                 {
                     return e.ToString();
                 }
                 return SetupOneInstance(ic);
             }
         }
bool TGS.Server.Server.InstanceEnabled (string Name)
Checks if an instance is online
Implements TGS.Interface.Components.ITGInstanceManager.
Definition at line 526 of file Server.cs.
         {
             lock(this)
             {
                 return hosts.ContainsKey(Name);
             }
         }
IList<InstanceMetadata> TGS.Server.Server.ListInstances ()
List instances that the caller can access
Implements TGS.Interface.Components.ITGLanding.
Definition at line 422 of file Server.cs.
References TGS.Interface.InstanceMetadata.Name.
         {
             var result = new List<InstanceMetadata>();
             lock (this)
                 foreach (var ic in GetInstanceConfigs())
                     result.Add(new InstanceMetadata
                     {
                         Name = ic.Name,
                         Path = ic.Directory,
                         Enabled = ic.Enabled,
                         LoggingID = (byte)(ic.Enabled ? ((Instance)hosts[ic.Name].SingletonInstance).LoggingID : 0)
                     });
             return result;
         }
byte TGS.Server.Server.LockLoggingID () private
Gets and locks a Instance.LoggingID
Returns
A logging ID for the Instance must be released using UnlockLoggingID(byte)
Definition at line 267 of file Server.cs.
         {
             lock (UsedLoggingIDs)
             {
                 for (byte I = 1; I < 100; ++I)
                     if (!UsedLoggingIDs.Contains(I))
                     {
                         UsedLoggingIDs.Add(I);
                         return I;
                     }
             }
             throw new Exception("All logging IDs in use!");
         }
void TGS.Server.Server.OnlineAllHosts () private
Opens all created ServiceHosts
Definition at line 206 of file Server.cs.
         {
             serviceHost.Open();
             foreach (var I in hosts)
                 I.Value.Open();
         }
void TGS.Server.Server.OnStop () private
Shuts down all active ServiceHosts and calls IDisposable.Dispose on it's Instance
Definition at line 351 of file Server.cs.
         {
             lock (this)
             {
                 try
                 {
                     foreach (var I in hosts)
                     {
                         var host = I.Value;
                         var instance = (Instance)host.SingletonInstance;
                         host.Close();
                         instance.Dispose();
                         UnlockLoggingID(instance.LoggingID);
                     }
                 }
                 catch (Exception e)
                 {
                     Logger.WriteError(e.ToString(), EventID.ServiceShutdownFail, LoggingID);
                 }
                 serviceHost.Close();
             }
             Config.Save(DefaultConfigDirectory);
         }
void TGS.Server.Server.PrepareForUpdate ()
Next stop of the service will not close DD and sets a flag for it to reattach once it restarts
Implements TGS.Interface.Components.ITGSService.
Definition at line 379 of file Server.cs.
         {
             foreach (var I in hosts)
                 ((Instance)I.Value.SingletonInstance).Reattach(false);
         }
string TGS.Server.Server.PythonPath ()
Gets the path to the python 2.7 installation
Implements TGS.Interface.Components.ITGSService.
Definition at line 416 of file Server.cs.
         {
             return Config.PythonPath;
         }
ushort TGS.Server.Server.RemoteAccessPort ()
Get the port used for remote operation
Implements TGS.Interface.Components.ITGSService.
Definition at line 386 of file Server.cs.
         {
             return Config.RemoteAccessPort;
         }
string TGS.Server.Server.RenameInstance (string name, string new_name)
Renames an instance, this will restart the instance if it is enabled
Implements TGS.Interface.Components.ITGInstanceManager.
Definition at line 586 of file Server.cs.
         {
             if (name == new_name)
                 return null;
             var res = CheckInstanceName(new_name);
             if (res != null)
                 return res;
             lock (this)
             {
                 //we have to check em all anyway
                 IInstanceConfig the_droid_were_looking_for = null;
                 foreach (var ic in GetInstanceConfigs())
                     if (ic.Name == name)
                     {
                         the_droid_were_looking_for = ic;
                         break;
                     }
                     else if (ic.Name == new_name)
                         return String.Format("There is already another instance named {0}!", new_name);
                 if (the_droid_were_looking_for == null)
                     return String.Format("There is no instance named {0}!", name);
                 var ie = InstanceEnabled(name);
                 if(ie)
                     SetInstanceEnabled(name, false);
                 the_droid_were_looking_for.Name = new_name;
                 string result = "";
                 try
                 {
                     the_droid_were_looking_for.Save();
                     result = null;
                 }
                 catch(Exception e)
                 {
                     result = "Could not save instance config! Error: " + e.ToString();
                 }
                 finally
                 {
                     if (ie)
                     {
                         var resRestore = SetInstanceEnabled(new_name, true);
                         if (resRestore != null)
                             result = (result + " " + resRestore).Trim();
                     }
                 }
                 return result;
             }
         }
string TGS.Server.Server.SetInstanceEnabled (string Name, bool enabled)
Sets an instance's enabled status
Implements TGS.Interface.Components.ITGInstanceManager.
Definition at line 535 of file Server.cs.
         {
             return SetInstanceEnabledImpl(Name, enabled, out string path);
         }
string TGS.Server.Server.SetInstanceEnabledImpl (string Name, bool enabled, out string path) private
Sets a Instance's enabled status
Parameters
Name The Instance whom's status should be changed
enabled to enable the Instance, to disable it
path The path to the modified Instance
Returns
on success, error message on failure
Definition at line 548 of file Server.cs.
         {
             path = null;
             lock (this)
             {
                 var hostIsOnline = hosts.ContainsKey(Name);
                 if (enabled)
                 {
                     if (hostIsOnline)
                         return null;
                     foreach (var ic in GetInstanceConfigs())
                         if (ic.Name == Name)
{
                             path = ic.Directory;
                             ic.Enabled = true;
                             ic.Save();
                             return SetupOneInstance(ic);
                         }
                     return String.Format("Instance {0} does not exist!", Name);
                 }
                 else
                 {
                     if (!hostIsOnline)
                         return null;
                     var host = hosts[Name];
                     hosts.Remove(Name);
                     var inst = (Instance)host.SingletonInstance;
                     host.Close();
                     path = inst.ServerDirectory();
                     inst.Offline();
                     inst.Dispose();
                     UnlockLoggingID(inst.LoggingID);
                     return null;
                 }
             }
         }
bool TGS.Server.Server.SetPythonPath (string path)
Sets the path to the python 2.7 installation
Implements TGS.Interface.Components.ITGSService.
Definition at line 407 of file Server.cs.
         {
             if (!Directory.Exists(path))
                 return false;
             Config.PythonPath = Path.GetFullPath(path);
             return true;
         }
string TGS.Server.Server.SetRemoteAccessPort (ushort port)
Set the port used for remote operation Requires a service restart to take effect
Implements TGS.Interface.Components.ITGSService.
Definition at line 392 of file Server.cs.
         {
             if (port == 0)
                 return "Cannot bind to port 0";
             Config.RemoteAccessPort = port;
             return null;
         }
void TGS.Server.Server.SetupConfig () private
Upgrades up the service configuration
Definition at line 165 of file Server.cs.
References TGS.Server.Helpers.DeleteDirectory(), TGS.Server.ServerConfig.Load(), and TGS.Server.ServerConfig.Save().
         {
             Directory.CreateDirectory(DefaultConfigDirectory);
             try
             {
                 Config = ServerConfig.Load(DefaultConfigDirectory);
             }
             catch
             {
                 try
                 {
                     //assume we're upgrading
                     Config = ServerConfig.Load(MigrationConfigDirectory);
                     Config.Save(DefaultConfigDirectory);
                     Helpers.DeleteDirectory(MigrationConfigDirectory);
                 }
                 catch
                 {
                     //new baby
                     Config = new ServerConfig();
                 }
             }
         }
ServiceHost TGS.Server.Server.SetupInstance (IInstanceConfig config) private
Creates and starts a ServiceHost for a Instance at config
Parameters
config The IInstanceConfig for the Instance
Returns
The inactive ServiceHost on success, on failure
Definition at line 286 of file Server.cs.
References TGS.Server.IInstanceConfig.Directory, TGS.Server.IInstanceConfig.Enabled, TGS.Interface.Definitions.InstanceInterfaceName, TGS.Server.IInstanceConfig.Name, and TGS.Server.Instance.WriteError().
         {
             Instance instance;
             string instanceName;
             try
             {
                 if (hosts.ContainsKey(config.Directory))
                 {
                     var datInstance = ((Instance)hosts[config.Directory].SingletonInstance);
                     Logger.WriteError(String.Format("Unable to start instance at path {0}. Has the same name as instance at path {1}. Detaching...", config.Directory, datInstance.ServerDirectory()), EventID.InstanceInitializationFailure, LoggingID);
                     return null;
                 }
                 if (!config.Enabled)
                     return null;
                 var ID = LockLoggingID();
                 Logger.WriteInfo(String.Format("Instance {0} ({1}) assigned logging ID {2}", config.Name, config.Directory, ID), EventID.InstanceIDAssigned, ID);
                 instanceName = config.Name;
                 instance = new Instance(config, ID);
             }
             catch (Exception e)
             {
                 Logger.WriteError(String.Format("Unable to start instance at path {0}. Detaching... Error: {1}", config.Directory, e.ToString()), EventID.InstanceInitializationFailure, LoggingID);
                 return null;
             }
             var host = CreateHost(instance, String.Format("{0}/{1}", Definitions.InstanceInterfaceName, instanceName));
             hosts.Add(instanceName, host);
             AddEndpoint(host, typeof(ITGConnectivity));
             AddEndpoint(host, typeof(ITGAdministration));
             AddEndpoint(host, typeof(ITGByond));
             AddEndpoint(host, typeof(ITGChat));
             AddEndpoint(host, typeof(ITGCompiler));
             AddEndpoint(host, typeof(ITGConfig));
             AddEndpoint(host, typeof(ITGDreamDaemon));
             AddEndpoint(host, typeof(ITGInstance));
             AddEndpoint(host, typeof(ITGInterop));
             AddEndpoint(host, typeof(ITGRepository));
             host.Authorization.ServiceAuthorizationManager = instance;
             host.Authentication.ServiceAuthenticationManager = new AuthenticationHeaderDecoder();
             return host;
         }
void TGS.Server.Server.SetupInstances () private
Creates ServiceHosts for all Instances as listed in ServerConfig.InstancePaths, detaches bad ones
Definition at line 230 of file Server.cs.
         {
             hosts = new Dictionary<string, ServiceHost>();
             var pathsToRemove = new List<string>();
             var seenNames = new List<string>();
             foreach (var I in GetInstanceConfigs())
             {
                 if (seenNames.Contains(I.Name))
                 {
                     Logger.WriteError(String.Format("Instance at {0} has a duplicate name! Detaching...", I.Directory), EventID.InstanceInitializationFailure, LoggingID);
                     pathsToRemove.Add(I.Directory);
                 }
                 if (I.Enabled && SetupInstance(I) == null)
                     pathsToRemove.Add(I.Directory);
                 else
                     seenNames.Add(I.Name);
             }
             foreach (var I in pathsToRemove)
                 Config.InstancePaths.Remove(I);
         }
string TGS.Server.Server.SetupOneInstance (IInstanceConfig config) private
Starts and onlines an instance located at config
Parameters
config The IInstanceConfig for the Instance
Returns
on success, error message on failure
Definition at line 477 of file Server.cs.
References TGS.Server.IInstanceConfig.Directory, and TGS.Server.IInstanceConfig.Enabled.
         {
             if (!config.Enabled)
                 return null;
             try
             {
                 var host = SetupInstance(config);
                 if (host != null)
                     host.Open();
                 else
                     lock (this)
                         Config.InstancePaths.Remove(config.Directory);
                 return null;
             }
             catch (Exception e)
             {
                 return "Instance set up but an error occurred while starting it: " + e.ToString();
             }
         }
void TGS.Server.Server.SetupService () private
Creates the ServiceHost for ITGSService
Definition at line 192 of file Server.cs.
References TGS.Interface.Definitions.MasterInterfaceName.
         {
             serviceHost = CreateHost(this, Definitions.MasterInterfaceName);
             AddEndpoint(serviceHost, typeof(ITGConnectivity));
             AddEndpoint(serviceHost, typeof(ITGInstanceManager));
             AddEndpoint(serviceHost, typeof(ITGLanding));
             AddEndpoint(serviceHost, typeof(ITGSService));
             serviceHost.Authorization.ServiceAuthorizationManager = new RootAuthorizationManager(); //only admins can diddle us
             serviceHost.Authentication.ServiceAuthenticationManager = new AuthenticationHeaderDecoder();
         }
void TGS.Server.Server.UnlockLoggingID (byte ID) private
Unlocks a Instance.LoggingID acquired with LockLoggingID
Parameters
ID The Instance.LoggingID to unlock
Definition at line 255 of file Server.cs.
         {
             lock (UsedLoggingIDs)
             {
                 UsedLoggingIDs.Remove(ID);
             }
         }
void TGS.Server.Server.VerifyConnection ()
Does nothing on the server end, but if the call completes, you can be sure you are connected. WCF won't throw until you try until you actually use the API
Implements TGS.Interface.Components.ITGConnectivity.
Definition at line 376 of file Server.cs.
 { }
string TGS.Server.Server.Version ()
Retrieve's the service's version
Implements TGS.Interface.Components.ITGLanding.
Definition at line 401 of file Server.cs.
         {
             return VersionString;
         }
Member Data Documentation
readonly string TGS.Server.Server.DefaultConfigDirectory = Directory.CreateDirectory(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "TGS.Server")).FullName static private
The directory to load and save ServerConfigs to
Definition at line 47 of file Server.cs.
bool TGS.Server.Server.disposedValue = false private
To detect redundant Dispose() calls
Definition at line 660 of file Server.cs.
IDictionary<string, ServiceHost> TGS.Server.Server.hosts private
Map of InstanceConfig.Name to the respective ServiceHost hosting the Instance
Definition at line 79 of file Server.cs.
const byte TGS.Server.Server.LoggingID = 0
The logging ID used for Server events
Definition at line 22 of file Server.cs.
Referenced by TGS.Server.Security.RootAuthorizationManager.CheckAccessCore().
const string TGS.Server.Server.MigrationConfigDirectory = "C:\\TGSSettingUpgradeTempDir"
The directory to use when importing a .NET settings based config
Definition at line 27 of file Server.cs.
ServiceHost TGS.Server.Server.serviceHost private
The WCF host that contains ITGSService connects to
Definition at line 75 of file Server.cs.
IList<int> TGS.Server.Server.UsedLoggingIDs = new List<int>() private
List of Instance.LoggingIDs in use
Definition at line 83 of file Server.cs.
readonly string TGS.Server.Server.VersionString = String.Format("/tg/station 13 Server v{0}", Assembly.GetExecutingAssembly().GetName().Version) static
The service version string based on the AssemblyName's System.Version
Definition at line 32 of file Server.cs.
Referenced by TGS.Server.ChatProviders.IRCChatProvider.IRCChatProvider(), and TGS.Server.Instance.Version().
Property Documentation
ServerConfig TGS.Server.Server.Config static get private set
The ServerConfig for the Server
Definition at line 42 of file Server.cs.
Referenced by TGS.Server.Instance.GenerateChangelogImpl().
ILogger TGS.Server.Server.Logger static get private set
Singleton ILogger
Definition at line 37 of file Server.cs.
Referenced by TGS.Server.Security.RootAuthorizationManager.CheckAccessCore(), TGS.Server.Instance.WriteAccess(), TGS.Server.Instance.WriteError(), TGS.Server.Instance.WriteInfo(), and TGS.Server.Instance.WriteWarning().
The documentation for this class was generated from the following file:
TGS.Server/Server.cs