tgstation-server: TGS.Interface.Client Class Reference
TGS.Interface.Client Class Reference
Public Member Functions
Client ()
Construct an Client for a local connection
Client (RemoteLoginInfo loginInfo)
Construct an Client for a remote connection
void Dispose ()
Closes all ChannelFactorys stored in ChannelFactoryCache and it
bool VersionMismatch (out string errorMessage)
Returns if the IClient interface being used to connect to a service does not have the same release version as the service
ConnectivityLevel ConnectionStatus ()
See ConnectionStatus(out string) without the error argument
ConnectivityLevel ConnectionStatus (out string error)
Used to test if the Components.ITGSService is avaiable on the target machine. Note that state can change at any time and any call into the may throw an exception because of communcation errors
Static Public Member Functions
static void SetBadCertificateHandler (Func< string, bool > handler)
Sets the function called when a remote login fails due to the server having an invalid SSL cert
Public Attributes
IServer Server => server
Static Public Attributes
static readonly Version Version = Assembly.GetExecutingAssembly().GetName().Version
Version of the Client
Properties
Version ServerVersion [get]
string InstanceName [get, private set]
RemoteLoginInfo LoginInfo [get]
bool IsRemoteConnection [get]
Properties inherited from TGS.Interface.IClient
IServer Server [get]
The IServer the IClient connects to
RemoteLoginInfo LoginInfo [get]
The RemoteLoginInfo for the IClient. Is for local connections
bool IsRemoteConnection [get]
Checks if the IClient is setup for a remote connection
Private Member Functions
ChannelFactory< T > CreateChannel< T > (string instanceName)
Directly creates a ChannelFactory<TChannel> for T without caching. This should be eventually closed by the caller
ChannelFactory< T > CreateLocalChannel< T > (string instanceName, string accessPath)
Directly creates a ChannelFactory<TChannel> for on a local connection T without caching. This should be eventually closed by the caller
ChannelFactory< T > CreateRemoteChannel< T > (string instanceName, string accessPath)
Directly creates a ChannelFactory<TChannel> for on a remote connection T without caching. This should be eventually closed by the caller
Private Attributes
readonly IServer server
Backing field for Server
readonly RemoteLoginInfo _loginInfo
Backing field for LoginInfo
Version _serverVersion
The ServerVersion
IDictionary< string, ChannelFactory > ChannelFactoryCache
Associated list of open ChannelFactorys keyed by type name. A ChannelFactory in this list may close or fault at any time. must be locked before being accessed
Detailed Description
Definition at line 15 of file Client.cs.
Constructor & Destructor Documentation
TGS.Interface.Client.Client ()
Construct an Client for a local connection
Definition at line 107 of file Client.cs.
         {
             ChannelFactoryCache = new Dictionary<string, ChannelFactory>();
             server = new Server(this);
         }
TGS.Interface.Client.Client (RemoteLoginInfo loginInfo)
Construct an Client for a remote connection
Parameters
loginInfo The RemoteLoginInfo for a remote connection
Definition at line 117 of file Client.cs.
References TGS.Interface.RemoteLoginInfo.HasPassword.
                                                  : this()
         {
             if (!loginInfo.HasPassword)
                 throw new InvalidOperationException("password must be set on loginInfo!");
             _loginInfo = loginInfo;
         }
Member Function Documentation
ConnectivityLevel TGS.Interface.Client.ConnectionStatus ()
See ConnectionStatus(out string) without the error argument
Implements TGS.Interface.IClient.
Definition at line 275 of file Client.cs.
         {
             return ConnectionStatus(out string unused);
         }
ConnectivityLevel TGS.Interface.Client.ConnectionStatus (out string error)
Used to test if the Components.ITGSService is avaiable on the target machine. Note that state can change at any time and any call into the may throw an exception because of communcation errors
Implements TGS.Interface.IClient.
Definition at line 281 of file Client.cs.
         {
             try
             {
                 GetComponent<ITGConnectivity>(null).VerifyConnection();
             }
             catch (Exception e)
             {
                 error = e.ToString();
                 return ConnectivityLevel.None;
             }
             try
             {
                 GetComponent<ITGLanding>(null).Version();
             }
             catch(Exception e)
             {
                 error = e.ToString();
                 return ConnectivityLevel.Connected;
             }
             try
             {
                 GetComponent<ITGSService>(null).Version();
                 error = null;
                 return ConnectivityLevel.Administrator;
             }
             catch(Exception e)
             {
                 error = e.ToString();
                 return ConnectivityLevel.Authenticated;
             }
         }
ChannelFactory<T> TGS.Interface.Client.CreateChannel< T > (string instanceName) private
Directly creates a ChannelFactory<TChannel> for T without caching. This should be eventually closed by the caller
Template Parameters
T The component of the channel to be created
Parameters
instanceName The instance to connect to, if any
Returns
The correct ChannelFactory<TChannel>
Definition at line 207 of file Client.cs.
References TGS.Interface.Definitions.InstanceInterfaceName, and TGS.Interface.Definitions.MasterInterfaceName.
         {
             var accessPath = instanceName == null ? Definitions.MasterInterfaceName : String.Format("{0}/{1}", Definitions.InstanceInterfaceName, instanceName);
             if (!IsRemoteConnection)
                 return CreateLocalChannel<T>(instanceName, accessPath);
             return CreateRemoteChannel<T>(instanceName, accessPath);
         }
ChannelFactory<T> TGS.Interface.Client.CreateLocalChannel< T > (string instanceName, string accessPath) private
Directly creates a ChannelFactory<TChannel> for on a local connection T without caching. This should be eventually closed by the caller
Template Parameters
T The component of the channel to be created
Parameters
instanceName The instance to connect to, if any
accessPath The URL of the interface to connect to
Returns
The correct ChannelFactory<TChannel>
Definition at line 224 of file Client.cs.
References TGS.Interface.Definitions.TransferLimitLocal.
         {
             var interfaceName = typeof(T).Name;
             var res2 = new ChannelFactory<T>(
             new NetNamedPipeBinding { SendTimeout = new TimeSpan(0, 0, 30), MaxReceivedMessageSize = Definitions.TransferLimitLocal }, new EndpointAddress(String.Format("net.pipe://localhost/{0}/{1}", accessPath, interfaceName)));                                                      //10 megs
             res2.Credentials.Windows.AllowedImpersonationLevel = TokenImpersonationLevel.Impersonation;
             return res2;
         }
ChannelFactory<T> TGS.Interface.Client.CreateRemoteChannel< T > (string instanceName, string accessPath) private
Directly creates a ChannelFactory<TChannel> for on a remote connection T without caching. This should be eventually closed by the caller
Template Parameters
T The component of the channel to be created
Parameters
instanceName The instance to connect to, if any
accessPath The URL of the interface to connect to
Returns
The correct ChannelFactory<TChannel>
Definition at line 240 of file Client.cs.
References TGS.Interface.Definitions.TransferLimitRemote.
         {
             //okay we're going over
             var binding = new BasicHttpsBinding()
             {
                 SendTimeout = new TimeSpan(0, 0, 40),
                 MaxReceivedMessageSize = Definitions.TransferLimitRemote
             };
             var interfaceName = typeof(T).Name;
             var requireAuth = interfaceName != typeof(ITGConnectivity).Name;
             var url = String.Format("https://{0}:{1}/{2}/{3}", LoginInfo.IP, LoginInfo.Port, accessPath, interfaceName);
             var address = new EndpointAddress(url);
             var res = new ChannelFactory<T>(binding, address);
             if (requireAuth)
             {
                 var applicator = new AuthenticationHeaderApplicator(LoginInfo);
                 var t = Type.GetType("Mono.Runtime");
                 KeyedCollection<Type, IEndpointBehavior> behaviours;
                 if (t != null)
                 {
                     var prop = res.Endpoint.GetType()
                      .GetTypeInfo()
                      .GetDeclaredProperty("Behaviors");
                     behaviours = (KeyedCollection<Type, IEndpointBehavior>)prop
                                      .GetValue(res.Endpoint);
                 }
                 else
                     behaviours = res.Endpoint.EndpointBehaviors;
                 behaviours.Add(applicator);
             }
             return res;
         }
void TGS.Interface.Client.Dispose ()
Closes all ChannelFactorys stored in ChannelFactoryCache and it
Definition at line 130 of file Client.cs.
         {
             lock (this)
             {
                 if (ChannelFactoryCache == null)
                     return;
                 foreach (var I in ChannelFactoryCache)
                 {
                     var cf = I.Value;
                     try
                     {
                         cf.Close();
                     }
                     catch
                     {
                         cf.Abort();
                     }
                 }
                 ChannelFactoryCache = null;
             }
         }
static void TGS.Interface.Client.SetBadCertificateHandler (Func< string, bool > handler) static
Sets the function called when a remote login fails due to the server having an invalid SSL cert
Parameters
handler The Func<T, TResult> to be called when a remote login is attempted while the server posesses a bad certificate. Passed a string of error information about the and should return if it the connection should be made anyway
Definition at line 77 of file Client.cs.
Referenced by TGS.CommandLine.Program.Main(), TGS.Interface.Tests.TestInterface.TestBadCertificateHandler(), and TGS.Interface.Tests.TestInterface.TestSetBadCertificateHandler().
         {
             ServicePointManager.ServerCertificateValidationCallback = (sender, cert, chain, error) =>
             {
                 string ErrorMessage;
                 switch (error)
                 {
                     case SslPolicyErrors.None:
                         return true;
                     case SslPolicyErrors.RemoteCertificateChainErrors:
                         ErrorMessage = "There are certificate chain errors.";
                         break;
                     case SslPolicyErrors.RemoteCertificateNameMismatch:
                         ErrorMessage = "The certificate name does not match.";
                         break;
                     case SslPolicyErrors.RemoteCertificateNotAvailable:
                         ErrorMessage = "The certificate doesn't exist in the trust store.";
                         break;
                     default:
                         ErrorMessage = "An unknown error occurred.";
                         break;
                 }
                 ErrorMessage = String.Format("The server's certificate failed to verify! Error: {0} Cert: {1}", ErrorMessage, cert.ToString());
                 return handler(ErrorMessage);
             };
         }
bool TGS.Interface.Client.VersionMismatch (out string errorMessage)
Returns if the IClient interface being used to connect to a service does not have the same release version as the service
Implements TGS.Interface.IClient.
Definition at line 153 of file Client.cs.
         {
             if (ServerVersion.Major != Version.Major || ServerVersion.Minor != Version.Minor || ServerVersion.Build != Version.Build)   //don't care about the patch level
             {
                 errorMessage = String.Format("Version mismatch between interface version ({0}) and service version ({1}). Some functionality may crash this program.", Version, ServerVersion);
                 return true;
             }
             errorMessage = null;
             return false;
         }
Member Data Documentation
readonly RemoteLoginInfo TGS.Interface.Client._loginInfo private
Backing field for LoginInfo
Definition at line 61 of file Client.cs.
Version TGS.Interface.Client._serverVersion private
The ServerVersion
Definition at line 66 of file Client.cs.
IDictionary<string, ChannelFactory> TGS.Interface.Client.ChannelFactoryCache private
Associated list of open ChannelFactorys keyed by type name. A ChannelFactory in this list may close or fault at any time. must be locked before being accessed
Definition at line 71 of file Client.cs.
IServer TGS.Interface.Client.Server => server
Definition at line 23 of file Client.cs.
readonly IServer TGS.Interface.Client.server private
Backing field for Server
Definition at line 56 of file Client.cs.
readonly Version TGS.Interface.Client.Version = Assembly.GetExecutingAssembly().GetName().Version static
Version of the Client
Definition at line 20 of file Client.cs.
Property Documentation
string TGS.Interface.Client.InstanceName get private set
Definition at line 48 of file Client.cs.
bool TGS.Interface.Client.IsRemoteConnection get
Definition at line 125 of file Client.cs.
RemoteLoginInfo TGS.Interface.Client.LoginInfo get
Definition at line 51 of file Client.cs.
Version TGS.Interface.Client.ServerVersion get
Definition at line 26 of file Client.cs.
The documentation for this class was generated from the following file:
TGS.Interface/Client.cs