tgstation-server: Tgstation.Server.Host.Controllers.ConfigurationController Class Reference
Tgstation.Server.Host.Controllers.ConfigurationController Class Reference
The ApiController for IConfigurationFiles.
Public Member Functions
ConfigurationController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ILogger< ConfigurationController > logger, IInstanceManager instanceManager, IIOManager ioManager, IApiHeadersProvider apiHeaders)
Initializes a new instance of the ConfigurationController class.
async ValueTask< IActionResult > Update ([FromBody] ConfigurationFileRequest model, CancellationToken cancellationToken)
Write to a configuration file.
async ValueTask< IActionResult > File (string filePath, CancellationToken cancellationToken)
Get the contents of a file at a filePath .
ValueTask< IActionResult > Directory (string? directoryPath, [FromQuery] int? page, [FromQuery] int? pageSize, CancellationToken cancellationToken)
Get the contents of a directory at a directoryPath .
ValueTask< IActionResult > List ([FromQuery] int? page, [FromQuery] int? pageSize, CancellationToken cancellationToken)
Get the contents of the root configuration directory.
async ValueTask< IActionResult > CreateDirectory ([FromBody] ConfigurationFileRequest model, CancellationToken cancellationToken)
Create a configuration directory.
async ValueTask< IActionResult > DeleteDirectory ([FromBody] ConfigurationFileRequest directory, CancellationToken cancellationToken)
Deletes an empty directory .
Public Member Functions inherited from Tgstation.Server.Host.Controllers.ApiControllerBase
sealed override async Task OnActionExecutionAsync (ActionExecutingContext context, ActionExecutionDelegate next)
Private Member Functions
bool ForbidDueToModeConflicts (string? path, out ISystemIdentity? systemIdentityToUse)
If a ForbidResult should be returned from actions due to conflicts with one or both of the Api.Models.Instance.ConfigurationType or the IAuthenticationContext.SystemIdentity or a given path tries to access parent directories.
Private Attributes
readonly IIOManager ioManager
The IIOManager for the ConfigurationController.
Additional Inherited Members
Protected Member Functions inherited from Tgstation.Server.Host.Controllers.InstanceRequiredController
InstanceRequiredController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ILogger< InstanceRequiredController > logger, IInstanceManager instanceManager, IApiHeadersProvider apiHeaders)
Initializes a new instance of the InstanceRequiredController class.
Protected Member Functions inherited from Tgstation.Server.Host.Controllers.ComponentInterfacingController
ComponentInterfacingController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ILogger< ComponentInterfacingController > logger, IInstanceManager instanceManager, IApiHeadersProvider apiHeaders, bool useInstanceRequestHeader)
Initializes a new instance of the ComponentInterfacingController class.
override async ValueTask< IActionResult?> ValidateRequest (CancellationToken cancellationToken)
Performs validation a request.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in an appropriate IActionResult on validation failure, null otherwise.
bool ValidateInstanceOnlineStatus (Api.Models.Instance metadata)
Corrects discrepencies between the Api.Models.Instance.Online status of IInstances in the database vs the service.
async ValueTask< IActionResult?> WithComponentInstanceNullable (Func< IInstanceCore, ValueTask< IActionResult?> > action, Models.Instance? instance=null)
Run a given action with the relevant IInstance.
async ValueTask< IActionResult > WithComponentInstance (Func< IInstanceCore, ValueTask< IActionResult > > action, Models.Instance? instance=null)
Run a given action with the relevant IInstance.
Protected Member Functions inherited from Tgstation.Server.Host.Controllers.ApiController
ApiController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, IApiHeadersProvider apiHeadersProvider, ILogger< ApiController > logger, bool requireHeaders)
Initializes a new instance of the ApiController class.
override async ValueTask< IActionResult?> HookExecuteAction (Func< Task > executeAction, CancellationToken cancellationToken)
Hook for executing a request.
Parameters
executeAction A Func<TResult> that should be invoked and its response awaited to continue normal execution of the request. Should NOT be called if this method returns a non-null value.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in an IActionResult that, if not null, is executed.
new NotFoundObjectResult NotFound ()
Generic 404 response.
new ObjectResult Unauthorized ()
Generic 401 response.
ObjectResult RequiresPosixSystemIdentity (NotImplementedException ex)
Generic 501 response.
StatusCodeResult StatusCode (HttpStatusCode statusCode)
Strongly type calls to ControllerBase.StatusCode(int).
ObjectResult Created (object payload)
Generic 201 response with a given payload .
ObjectResult RateLimit (RateLimitExceededException rateLimitException)
429 response for a given rateLimitException .
virtual ValueTask< IActionResult?> ValidateRequest (CancellationToken cancellationToken)
Performs validation a request.
IActionResult HeadersIssue (HeadersException headersException)
Response for missing/Invalid headers.
ValueTask< IActionResult > Paginated< TModel > (Func< ValueTask< PaginatableResult< TModel > > > queryGenerator, Func< TModel, ValueTask >? resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
ValueTask< IActionResult > Paginated< TModel, TApiModel > (Func< ValueTask< PaginatableResult< TModel > > > queryGenerator, Func< TApiModel, ValueTask >? resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
virtual async ValueTask< IActionResult?> HookExecuteAction (Func< Task > executeAction, CancellationToken cancellationToken)
Hook for executing a request.
Properties inherited from Tgstation.Server.Host.Controllers.InstanceRequiredController
new Models.Instance Instance [get]
The ApiController.Instance.
Models.InstancePermissionSet InstancePermissionSet [get]
The Models.InstancePermissionSet for the request.
Properties inherited from Tgstation.Server.Host.Controllers.ComponentInterfacingController
IInstanceOperations InstanceOperations [get]
Access the IInstanceOperations instance.
Properties inherited from Tgstation.Server.Host.Controllers.ApiController
ApiHeaders? ApiHeaders [get]
The Api.ApiHeaders for the operation.
IApiHeadersProvider ApiHeadersProvider [get]
The IApiHeadersProvider containing value of ApiHeaders.
IDatabaseContext DatabaseContext [get]
The IDatabaseContext for the operation.
IAuthenticationContext AuthenticationContext [get]
The IAuthenticationContext for the operation.
ILogger< ApiController > Logger [get]
The ILogger for the ApiController.
Models.? Instance Instance [get]
The Instance for the operation.
Detailed Description
The ApiController for IConfigurationFiles.
Definition at line 28 of file ConfigurationController.cs.
Constructor & Destructor Documentation
ConfigurationController()
Tgstation.Server.Host.Controllers.ConfigurationController.ConfigurationController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ILogger< ConfigurationController > logger, IInstanceManager instanceManager, IIOManager ioManager, IApiHeadersProvider apiHeaders)
Initializes a new instance of the ConfigurationController class.
Parameters
databaseContext The IDatabaseContext for the InstanceRequiredController.
authenticationContext The IAuthenticationContext for the InstanceRequiredController.
logger The ILogger for the InstanceRequiredController.
instanceManager The IInstanceManager for the InstanceRequiredController.
ioManager The value of ioManager.
apiHeaders The IApiHeadersProvider for the InstanceRequiredController.
Definition at line 44 of file ConfigurationController.cs.
            : base(
                  databaseContext,
                  authenticationContext,
                  logger,
                  instanceManager,
                  apiHeaders)
        {
            this.ioManager = ioManager ?? throw new ArgumentNullException(nameof(ioManager));
        }
References Tgstation.Server.Host.Controllers.ConfigurationController.ioManager.
Member Function Documentation
CreateDirectory()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.ConfigurationController.CreateDirectory ([FromBody] ConfigurationFileRequest model, CancellationToken cancellationToken)
Create a configuration directory.
Parameters
model The ConfigurationFileRequest representing the directory.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult for the operation.
<response code="200">Directory already exists.</response> <response code="201">Directory created successfully.</response>
Definition at line 239 of file ConfigurationController.cs.
        {
            ArgumentNullException.ThrowIfNull(model);
            if (model.Path == null)
                return BadRequest(new ErrorMessageResponse(ErrorCode.ModelValidationFailure));
            if (ForbidDueToModeConflicts(model.Path, out var systemIdentity))
                return Forbid();
            try
            {
                var resultModel = new ConfigurationFileResponse
                {
                    IsDirectory = true,
                    Path = model.Path,
                };
                return await WithComponentInstance(
                    async instance =>
                    {
                        var result = await instance
                            .Configuration
                            .CreateDirectory(model.Path, systemIdentity, cancellationToken);
                        if (!result.HasValue)
                            return Conflict(new ErrorMessageResponse(ErrorCode.ConfigurationContendedAccess));
                        return result.Value
                            ? Json(resultModel)
                            : Created(resultModel);
                    });
            }
            catch (IOException e)
            {
                Logger.LogInformation(e, "IOException while creating directory {path}!", model.Path);
                return Conflict(new ErrorMessageResponse(ErrorCode.IOError)
                {
                    Message = e.Message,
                });
            }
            catch (UnauthorizedAccessException)
            {
                return Forbid();
            }
        }
References Tgstation.Server.Host.Controllers.ApiController.Created(), Tgstation.Server.Host.Controllers.ConfigurationController.ForbidDueToModeConflicts(), Tgstation.Server.Host.Controllers.ApiController.Logger, Tgstation.Server.Api.Models.Response.ConfigurationFileResponse.Path, and Tgstation.Server.Host.Controllers.ComponentInterfacingController.WithComponentInstance().
DeleteDirectory()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.ConfigurationController.DeleteDirectory ([FromBody] ConfigurationFileRequest directory, CancellationToken cancellationToken)
Deletes an empty directory .
Parameters
directory A ConfigurationFileRequest representing the path to the directory to delete.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the operation.
<response code="204">Empty directory deleted successfully.</response>
Definition at line 297 of file ConfigurationController.cs.
        {
            ArgumentNullException.ThrowIfNull(directory);
            if (directory.Path == null)
                return BadRequest(new ErrorMessageResponse(ErrorCode.ModelValidationFailure));
            if (ForbidDueToModeConflicts(directory.Path, out var systemIdentity))
                return Forbid();
            try
            {
                return await WithComponentInstance(
                    async instance =>
                    {
                        var result = await instance
                            .Configuration
                            .DeleteDirectory(directory.Path, systemIdentity, cancellationToken);
                        if (!result.HasValue)
                            return Conflict(new ErrorMessageResponse(ErrorCode.ConfigurationContendedAccess));
                        return result.Value
                            ? NoContent()
                            : Conflict(new ErrorMessageResponse(ErrorCode.ConfigurationDirectoryNotEmpty));
                    });
            }
            catch (UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (IOException ex)
            {
                Logger.LogInformation(ex, "IOException while deleting directory!");
                return Conflict(new ErrorMessageResponse(ErrorCode.IOError)
                {
                    Message = ex.Message,
                });
            }
        }
References Tgstation.Server.Host.Controllers.ConfigurationController.ForbidDueToModeConflicts(), Tgstation.Server.Host.Controllers.ApiController.Logger, and Tgstation.Server.Host.Controllers.ComponentInterfacingController.WithComponentInstance().
Directory()
ValueTask< IActionResult > Tgstation.Server.Host.Controllers.ConfigurationController.Directory (string? directoryPath, [FromQuery] int? page, [FromQuery] int? pageSize, CancellationToken cancellationToken)
Get the contents of a directory at a directoryPath .
Parameters
directoryPath The path of the directory to get.
page The current page.
pageSize The page size.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult for the operation.
<response code="200">Directory listed successfully.</response>> <response code="410">Directory does not currently exist.</response>
References Tgstation.Server.Host.Controllers.ConfigurationController.ForbidDueToModeConflicts(), and Tgstation.Server.Host.Controllers.ApiController.Logger.
File()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.ConfigurationController.File (string filePath, CancellationToken cancellationToken)
Get the contents of a file at a filePath .
Parameters
filePath The path of the file to get.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult for the operation.
> <response code="200">File read successfully.</response>> <response code="410">File does not currently exist.</response>
Definition at line 121 of file ConfigurationController.cs.
        {
            if (ForbidDueToModeConflicts(filePath, out var systemIdentity))
                return Forbid();
            try
            {
                return await WithComponentInstance(
                    async instance =>
                    {
                        var result = await instance
                            .Configuration
                            .Read(filePath, systemIdentity, cancellationToken);
                        if (result == null)
                            return Conflict(new ErrorMessageResponse(ErrorCode.ConfigurationContendedAccess));
                        return Json(result);
                    });
            }
            catch (IOException e)
            {
                Logger.LogInformation(e, "IOException while reading file {path}!", filePath);
                return Conflict(new ErrorMessageResponse(ErrorCode.IOError)
                {
                    AdditionalData = e.Message,
                });
            }
        }
References Tgstation.Server.Host.Controllers.ConfigurationController.ForbidDueToModeConflicts(), Tgstation.Server.Host.Controllers.ApiController.Logger, and Tgstation.Server.Host.Controllers.ComponentInterfacingController.WithComponentInstance().
ForbidDueToModeConflicts()
bool Tgstation.Server.Host.Controllers.ConfigurationController.ForbidDueToModeConflicts (string? path, out ISystemIdentity? systemIdentityToUse) private
If a ForbidResult should be returned from actions due to conflicts with one or both of the Api.Models.Instance.ConfigurationType or the IAuthenticationContext.SystemIdentity or a given path tries to access parent directories.
Parameters
path The path to validate if any.
systemIdentityToUse The ISystemIdentity to use when calling into Components.StaticFiles.IConfiguration.
Returns
true if a ForbidResult should be returned, false otherwise.
Definition at line 344 of file ConfigurationController.cs.
        {
            if (Instance.ConfigurationType == ConfigurationType.Disallowed
                || (Instance.ConfigurationType == ConfigurationType.SystemIdentityWrite && AuthenticationContext.SystemIdentity == null)
                || (path != null && ioManager.PathContainsParentAccess(path)))
            {
                systemIdentityToUse = null;
                return true;
            }
            systemIdentityToUse = Instance.ConfigurationType == ConfigurationType.SystemIdentityWrite ? AuthenticationContext.SystemIdentity : null;
            return false;
        }
References Tgstation.Server.Api.Models.Instance.ConfigurationType, Tgstation.Server.Host.Controllers.ConfigurationController.ioManager, Tgstation.Server.Host.IO.IIOManager.PathContainsParentAccess(), and Tgstation.Server.Host.Security.AuthenticationContext.SystemIdentity.
Referenced by Tgstation.Server.Host.Controllers.ConfigurationController.CreateDirectory(), Tgstation.Server.Host.Controllers.ConfigurationController.DeleteDirectory(), Tgstation.Server.Host.Controllers.ConfigurationController.Directory(), Tgstation.Server.Host.Controllers.ConfigurationController.File(), and Tgstation.Server.Host.Controllers.ConfigurationController.Update().
List()
ValueTask< IActionResult > Tgstation.Server.Host.Controllers.ConfigurationController.List ([FromQuery] int? page, [FromQuery] int? pageSize, CancellationToken cancellationToken)
Get the contents of the root configuration directory.
Parameters
page The current page.
pageSize The page size.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult for the operation.
Update()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.ConfigurationController.Update ([FromBody] ConfigurationFileRequest model, CancellationToken cancellationToken)
Write to a configuration file.
Parameters
model The ConfigurationFileRequest representing the file.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult for the operation.
<response code="200">File updated successfully.</response> <response code="202">File upload ticket created successfully.</response>
Definition at line 73 of file ConfigurationController.cs.
        {
            ArgumentNullException.ThrowIfNull(model);
            if (ForbidDueToModeConflicts(model.Path!, out var systemIdentity))
                return Forbid();
            try
            {
                return await WithComponentInstance(
                    async instance =>
                    {
                        var newFile = await instance
                            .Configuration
                            .Write(
                                model.Path!,
                                systemIdentity,
                                model.LastReadHash,
                                cancellationToken);
                        if (newFile == null)
                            return Conflict(new ErrorMessageResponse(ErrorCode.ConfigurationContendedAccess));
                        return model.LastReadHash == null ? Accepted(newFile) : Json(newFile);
                    });
            }
            catch (IOException e)
            {
                Logger.LogInformation(e, "IOException while updating file {path}!", model.Path);
                return Conflict(new ErrorMessageResponse(ErrorCode.IOError)
                {
                    AdditionalData = e.Message,
                });
            }
        }
References Tgstation.Server.Host.Controllers.ConfigurationController.ForbidDueToModeConflicts(), Tgstation.Server.Host.Controllers.ApiController.Logger, and Tgstation.Server.Host.Controllers.ComponentInterfacingController.WithComponentInstance().
Member Data Documentation
ioManager
readonly IIOManager Tgstation.Server.Host.Controllers.ConfigurationController.ioManager private
The IIOManager for the ConfigurationController.
Definition at line 33 of file ConfigurationController.cs.
Referenced by Tgstation.Server.Host.Controllers.ConfigurationController.ConfigurationController(), and Tgstation.Server.Host.Controllers.ConfigurationController.ForbidDueToModeConflicts().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Controllers/ConfigurationController.cs