tgstation-server: Tgstation.Server.Host.Controllers.DreamDaemonController Class Reference
Tgstation.Server.Host.Controllers.DreamDaemonController Class Reference
ApiController for managing the DreamDaemonResponse.
Public Member Functions
DreamDaemonController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ILogger< DreamDaemonController > logger, IInstanceManager instanceManager, IJobManager jobManager, IPortAllocator portAllocator, IApiHeadersProvider apiHeaders)
Initializes a new instance of the DreamDaemonController class.
ValueTask< IActionResult > Create (CancellationToken cancellationToken)
Launches the watchdog.
ValueTask< IActionResult > Read (CancellationToken cancellationToken)
Get the watchdog status.
ValueTask< IActionResult > Delete (CancellationToken cancellationToken)
Stops the Watchdog if it's running.
async ValueTask< IActionResult > Update ([FromBody] DreamDaemonRequest model, CancellationToken cancellationToken)
Update watchdog settings to be applied at next server reboot.
ValueTask< IActionResult > Restart (CancellationToken cancellationToken)
Creates a JobResponse to restart the Watchdog. It will not start if it wasn't already running.
ValueTask< IActionResult > CreateDump (CancellationToken cancellationToken)
Creates a JobResponse to generate a DreamDaemon process dump.
Public Member Functions inherited from Tgstation.Server.Host.Controllers.ApiControllerBase
sealed override async Task OnActionExecutionAsync (ActionExecutingContext context, ActionExecutionDelegate next)
Private Member Functions
ValueTask< IActionResult > ReadImpl (DreamDaemonSettings? settings, bool knownForcedReboot, CancellationToken cancellationToken)
Implementation of Read(CancellationToken).
Private Attributes
readonly IJobManager jobManager
The IJobManager for the DreamDaemonController.
readonly IPortAllocator portAllocator
The IPortAllocator for the DreamDaemonController.
Additional Inherited Members
Protected Member Functions inherited from Tgstation.Server.Host.Controllers.InstanceRequiredController
InstanceRequiredController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ILogger< InstanceRequiredController > logger, IInstanceManager instanceManager, IApiHeadersProvider apiHeaders)
Initializes a new instance of the InstanceRequiredController class.
Protected Member Functions inherited from Tgstation.Server.Host.Controllers.ComponentInterfacingController
ComponentInterfacingController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ILogger< ComponentInterfacingController > logger, IInstanceManager instanceManager, IApiHeadersProvider apiHeaders, bool useInstanceRequestHeader)
Initializes a new instance of the ComponentInterfacingController class.
override async ValueTask< IActionResult?> ValidateRequest (CancellationToken cancellationToken)
Performs validation a request.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in an appropriate IActionResult on validation failure, null otherwise.
bool ValidateInstanceOnlineStatus (Api.Models.Instance metadata)
Corrects discrepencies between the Api.Models.Instance.Online status of IInstances in the database vs the service.
async ValueTask< IActionResult?> WithComponentInstanceNullable (Func< IInstanceCore, ValueTask< IActionResult?> > action, Models.Instance? instance=null)
Run a given action with the relevant IInstance.
async ValueTask< IActionResult > WithComponentInstance (Func< IInstanceCore, ValueTask< IActionResult > > action, Models.Instance? instance=null)
Run a given action with the relevant IInstance.
Protected Member Functions inherited from Tgstation.Server.Host.Controllers.ApiController
ApiController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, IApiHeadersProvider apiHeadersProvider, ILogger< ApiController > logger, bool requireHeaders)
Initializes a new instance of the ApiController class.
override async ValueTask< IActionResult?> HookExecuteAction (Func< Task > executeAction, CancellationToken cancellationToken)
Hook for executing a request.
Parameters
executeAction A Func<TResult> that should be invoked and its response awaited to continue normal execution of the request. Should NOT be called if this method returns a non-null value.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in an IActionResult that, if not null, is executed.
new NotFoundObjectResult NotFound ()
Generic 404 response.
new ObjectResult Unauthorized ()
Generic 401 response.
ObjectResult RequiresPosixSystemIdentity (NotImplementedException ex)
Generic 501 response.
StatusCodeResult StatusCode (HttpStatusCode statusCode)
Strongly type calls to ControllerBase.StatusCode(int).
ObjectResult Created (object payload)
Generic 201 response with a given payload .
ObjectResult RateLimit (RateLimitExceededException rateLimitException)
429 response for a given rateLimitException .
virtual ValueTask< IActionResult?> ValidateRequest (CancellationToken cancellationToken)
Performs validation a request.
IActionResult HeadersIssue (HeadersException headersException)
Response for missing/Invalid headers.
ValueTask< IActionResult > Paginated< TModel > (Func< ValueTask< PaginatableResult< TModel > > > queryGenerator, Func< TModel, ValueTask >? resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
ValueTask< IActionResult > Paginated< TModel, TApiModel > (Func< ValueTask< PaginatableResult< TModel > > > queryGenerator, Func< TApiModel, ValueTask >? resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
virtual async ValueTask< IActionResult?> HookExecuteAction (Func< Task > executeAction, CancellationToken cancellationToken)
Hook for executing a request.
Properties inherited from Tgstation.Server.Host.Controllers.InstanceRequiredController
new Models.Instance Instance [get]
The ApiController.Instance.
Models.InstancePermissionSet InstancePermissionSet [get]
The Models.InstancePermissionSet for the request.
Properties inherited from Tgstation.Server.Host.Controllers.ComponentInterfacingController
IInstanceOperations InstanceOperations [get]
Access the IInstanceOperations instance.
Properties inherited from Tgstation.Server.Host.Controllers.ApiController
ApiHeaders? ApiHeaders [get]
The Api.ApiHeaders for the operation.
IApiHeadersProvider ApiHeadersProvider [get]
The IApiHeadersProvider containing value of ApiHeaders.
IDatabaseContext DatabaseContext [get]
The IDatabaseContext for the operation.
IAuthenticationContext AuthenticationContext [get]
The IAuthenticationContext for the operation.
ILogger< ApiController > Logger [get]
The ILogger for the ApiController.
Models.? Instance Instance [get]
The Instance for the operation.
Detailed Description
ApiController for managing the DreamDaemonResponse.
Definition at line 34 of file DreamDaemonController.cs.
Constructor & Destructor Documentation
DreamDaemonController()
Tgstation.Server.Host.Controllers.DreamDaemonController.DreamDaemonController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ILogger< DreamDaemonController > logger, IInstanceManager instanceManager, IJobManager jobManager, IPortAllocator portAllocator, IApiHeadersProvider apiHeaders)
Initializes a new instance of the DreamDaemonController class.
Parameters
databaseContext The IDatabaseContext for the InstanceRequiredController.
authenticationContext The IAuthenticationContext for the InstanceRequiredController.
logger The ILogger for the InstanceRequiredController.
instanceManager The IInstanceManager for the InstanceRequiredController.
jobManager The value of jobManager.
portAllocator The value of IPortAllocator.
apiHeaders The IApiHeadersProvider for the InstanceRequiredController.
Definition at line 56 of file DreamDaemonController.cs.
            : base(
                  databaseContext,
                  authenticationContext,
                  logger,
                  instanceManager,
                  apiHeaders)
        {
            this.jobManager = jobManager ?? throw new ArgumentNullException(nameof(jobManager));
            this.portAllocator = portAllocator ?? throw new ArgumentNullException(nameof(portAllocator));
        }
References Tgstation.Server.Host.Controllers.DreamDaemonController.jobManager, and Tgstation.Server.Host.Controllers.DreamDaemonController.portAllocator.
Member Function Documentation
Create()
ValueTask< IActionResult > Tgstation.Server.Host.Controllers.DreamDaemonController.Create (CancellationToken cancellationToken)
Launches the watchdog.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the operation.
<response code="202">Watchdog launch started successfully.</response>
References Tgstation.Server.Host.Models.Job.Create(), Tgstation.Server.Host.Controllers.DreamDaemonController.jobManager, Tgstation.Server.Host.Jobs.IJobManager.RegisterOperation(), and Tgstation.Server.Host.Security.AuthenticationContext.User.
CreateDump()
ValueTask< IActionResult > Tgstation.Server.Host.Controllers.DreamDaemonController.CreateDump (CancellationToken cancellationToken)
Creates a JobResponse to generate a DreamDaemon process dump.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the request.
<response code="202">Dump JobResponse started successfully.</response>
References Tgstation.Server.Host.Models.Job.Create(), Tgstation.Server.Host.Controllers.DreamDaemonController.jobManager, Tgstation.Server.Host.Jobs.IJobManager.RegisterOperation(), and Tgstation.Server.Host.Security.AuthenticationContext.User.
Delete()
ValueTask< IActionResult > Tgstation.Server.Host.Controllers.DreamDaemonController.Delete (CancellationToken cancellationToken)
Stops the Watchdog if it's running.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the operation.
<response code="204">Watchdog terminated.</response>
Read()
ValueTask< IActionResult > Tgstation.Server.Host.Controllers.DreamDaemonController.Read (CancellationToken cancellationToken)
Get the watchdog status.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the operation.
<response code="200">Read DreamDaemonResponse information successfully.</response> <response code="410">The database entity for the requested instance could not be retrieved. The instance was likely detached.</response>
ReadImpl()
ValueTask< IActionResult > Tgstation.Server.Host.Controllers.DreamDaemonController.ReadImpl (DreamDaemonSettings? settings, bool knownForcedReboot, CancellationToken cancellationToken) private
Implementation of Read(CancellationToken).
Parameters
settings The DreamDaemonSettings to operate on if any.
knownForcedReboot If there was a settings change made that forced a switch to RebootState.Restart.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the operation.
References Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.AdditionalParameters, Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.AllowWebClient, Tgstation.Server.Api.Models.Internal.DreamDaemonSettings.AutoStart, Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.DumpOnHealthCheckRestart, Tgstation.Server.Host.Security.AuthenticationContext.GetRight(), Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.HealthCheckSeconds, Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Host.Database.DatabaseContext.Instances, Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.LogOutput, Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.MapThreads, Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.Minidumps, Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.OpenDreamTopicPort, Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.Port, Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.SecurityLevel, Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.StartProfiler, Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.StartupTimeout, Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.TopicRequestTimeout, and Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.Visibility.
Referenced by Tgstation.Server.Host.Controllers.DreamDaemonController.Update().
Restart()
ValueTask< IActionResult > Tgstation.Server.Host.Controllers.DreamDaemonController.Restart (CancellationToken cancellationToken)
Creates a JobResponse to restart the Watchdog. It will not start if it wasn't already running.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the request.
<response code="202">Restart JobResponse started successfully.</response>
References Tgstation.Server.Host.Models.Job.Create(), Tgstation.Server.Host.Controllers.DreamDaemonController.jobManager, Tgstation.Server.Host.Jobs.IJobManager.RegisterOperation(), and Tgstation.Server.Host.Security.AuthenticationContext.User.
Update()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.DreamDaemonController.Update ([FromBody] DreamDaemonRequest model, CancellationToken cancellationToken)
Update watchdog settings to be applied at next server reboot.
Parameters
model The DreamDaemonRequest with updated settings.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the operation.
<response code="200">Settings applied successfully.</response> <response code="410">The database entity for the requested instance could not be retrieved. The instance was likely detached.</response>
Definition at line 158 of file DreamDaemonController.cs.
        {
            ArgumentNullException.ThrowIfNull(model);
            if (model.SoftShutdown == true && model.SoftRestart == true)
                return BadRequest(new ErrorMessageResponse(ErrorCode.GameServerDoubleSoft));
            // alias for changing DD settings
            var current = await DatabaseContext
                .Instances
                .AsQueryable()
                .Where(x => x.Id == Instance.Id)
                .Select(x => x.DreamDaemonSettings)
                .FirstOrDefaultAsync(cancellationToken);
            if (current == default)
                return this.Gone();
            if (model.Port.HasValue && model.Port.Value != current.Port!.Value)
            {
                Logger.LogTrace(
                    "Triggering port allocator for DD-I:{instanceId} because model port {modelPort} doesn't match DB port {dbPort}...",
                    Instance.Id,
                    model.Port,
                    current.Port);
                var verifiedPort = await portAllocator
                    .GetAvailablePort(
                        model.Port.Value,
                        true,
                        cancellationToken);
                if (verifiedPort != model.Port)
                    return Conflict(new ErrorMessageResponse(ErrorCode.PortNotAvailable));
            }
            var userRights = (DreamDaemonRights)AuthenticationContext.GetRight(RightsType.DreamDaemon);
            bool CheckModified<T>(Expression<Func<Api.Models.Internal.DreamDaemonSettings, T>> expression, DreamDaemonRights requiredRight)
            {
                var memberSelectorExpression = (MemberExpression)expression.Body;
                var property = (PropertyInfo)memberSelectorExpression.Member;
                var newVal = property.GetValue(model);
                if (newVal == null)
                    return false;
                if (!userRights.HasFlag(requiredRight) && property.GetValue(current) != newVal)
                    return true;
                property.SetValue(current, newVal);
                return false;
            }
            var ddRights = InstancePermissionSet.DreamDaemonRights!.Value;
            if (CheckModified(x => x.AllowWebClient, DreamDaemonRights.SetWebClient)
                || CheckModified(x => x.AutoStart, DreamDaemonRights.SetAutoStart)
                || CheckModified(x => x.Port, DreamDaemonRights.SetPort)
                || CheckModified(x => x.OpenDreamTopicPort, DreamDaemonRights.SetPort)
                || CheckModified(x => x.SecurityLevel, DreamDaemonRights.SetSecurity)
                || CheckModified(x => x.Visibility, DreamDaemonRights.SetVisibility)
                || (model.SoftRestart.HasValue && !ddRights.HasFlag(DreamDaemonRights.SoftRestart))
                || (model.SoftShutdown.HasValue && !ddRights.HasFlag(DreamDaemonRights.SoftShutdown))
                || (!String.IsNullOrWhiteSpace(model.BroadcastMessage) && !ddRights.HasFlag(DreamDaemonRights.BroadcastMessage))
                || CheckModified(x => x.StartupTimeout, DreamDaemonRights.SetStartupTimeout)
                || CheckModified(x => x.HealthCheckSeconds, DreamDaemonRights.SetHealthCheckInterval)
                || CheckModified(x => x.DumpOnHealthCheckRestart, DreamDaemonRights.CreateDump)
                || CheckModified(x => x.TopicRequestTimeout, DreamDaemonRights.SetTopicTimeout)
                || CheckModified(x => x.AdditionalParameters, DreamDaemonRights.SetAdditionalParameters)
                || CheckModified(x => x.StartProfiler, DreamDaemonRights.SetProfiler)
                || CheckModified(x => x.LogOutput, DreamDaemonRights.SetLogOutput)
                || CheckModified(x => x.MapThreads, DreamDaemonRights.SetMapThreads)
                || CheckModified(x => x.Minidumps, DreamDaemonRights.SetMinidumps))
                return Forbid();
            return await WithComponentInstance(
                async instance =>
                {
                    var watchdog = instance.Watchdog;
                    if (!String.IsNullOrWhiteSpace(model.BroadcastMessage)
                        && !await watchdog.Broadcast(model.BroadcastMessage, cancellationToken))
                        return Conflict(new ErrorMessageResponse(ErrorCode.BroadcastFailure));
                    await DatabaseContext.Save(cancellationToken);
                    // run this second because current may be modified by it
                    // slight race condition with request cancellation, but I CANNOT be assed right now
                    var rebootRequired = await watchdog.ChangeSettings(current, cancellationToken);
                    var rebootState = watchdog.RebootState;
                    var oldSoftRestart = rebootState == RebootState.Restart;
                    var oldSoftShutdown = rebootState == RebootState.Shutdown;
                    if (!oldSoftRestart && model.SoftRestart == true && watchdog.Status == WatchdogStatus.Online)
                        await watchdog.Restart(true, cancellationToken);
                    else if (!oldSoftShutdown && model.SoftShutdown == true)
                        await watchdog.Terminate(true, cancellationToken);
                    else if ((oldSoftRestart && model.SoftRestart == false) || (oldSoftShutdown && model.SoftShutdown == false))
                        await watchdog.ResetRebootState(cancellationToken);
                    return await ReadImpl(current, rebootRequired, cancellationToken);
                });
        }
References Tgstation.Server.Api.Models.Internal.InstancePermissionSet.DreamDaemonRights, Tgstation.Server.Host.Utils.IPortAllocator.GetAvailablePort(), Tgstation.Server.Host.Security.AuthenticationContext.GetRight(), Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Host.Database.DatabaseContext.Instances, Tgstation.Server.Host.Controllers.ApiController.Logger, Tgstation.Server.Host.Controllers.DreamDaemonController.portAllocator, Tgstation.Server.Host.Controllers.DreamDaemonController.ReadImpl(), Tgstation.Server.Host.Database.DatabaseContext.Save(), and Tgstation.Server.Host.Controllers.ComponentInterfacingController.WithComponentInstance().
Member Data Documentation
jobManager
readonly IJobManager Tgstation.Server.Host.Controllers.DreamDaemonController.jobManager private
The IJobManager for the DreamDaemonController.
Definition at line 39 of file DreamDaemonController.cs.
Referenced by Tgstation.Server.Host.Controllers.DreamDaemonController.Create(), Tgstation.Server.Host.Controllers.DreamDaemonController.CreateDump(), Tgstation.Server.Host.Controllers.DreamDaemonController.DreamDaemonController(), and Tgstation.Server.Host.Controllers.DreamDaemonController.Restart().
portAllocator
readonly IPortAllocator Tgstation.Server.Host.Controllers.DreamDaemonController.portAllocator private
The IPortAllocator for the DreamDaemonController.
Definition at line 44 of file DreamDaemonController.cs.
Referenced by Tgstation.Server.Host.Controllers.DreamDaemonController.DreamDaemonController(), and Tgstation.Server.Host.Controllers.DreamDaemonController.Update().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Controllers/DreamDaemonController.cs