tgstation-server: ILTemplate Class Reference
ILTemplate Class Reference
Static Public Member Functions
static void Attach ()
static Assembly ResolveAssembly (object sender, ResolveEventArgs e)
Static Private Attributes
static readonly object nullCacheLock = new object()
static readonly Dictionary< string, bool > nullCache = new Dictionary<string, bool>()
static readonly Dictionary< string, string > assemblyNames = new Dictionary<string, string>()
static readonly Dictionary< string, string > symbolNames = new Dictionary<string, string>()
static int isAttached = 0
Detailed Description
Definition at line 6 of file ILTemplate.cs.
Member Function Documentation
static void ILTemplate.Attach () static
Definition at line 16 of file ILTemplate.cs.
References ResolveAssembly().
     {
         if (Interlocked.Exchange(ref isAttached, 1) == 1)
         {
             return;
         }
         var currentDomain = AppDomain.CurrentDomain;
         currentDomain.AssemblyResolve += ResolveAssembly;
     }
static Assembly ILTemplate.ResolveAssembly (object sender, ResolveEventArgs e) static
Definition at line 27 of file ILTemplate.cs.
References Common.Log(), Common.ReadExistingAssembly(), and Common.ReadFromEmbeddedResources().
Referenced by Attach().
     {
         lock (nullCacheLock)
         {
             if (nullCache.ContainsKey(e.Name))
             {
                 return null;
             }
         }
         var requestedAssemblyName = new AssemblyName(e.Name);
         var assembly = Common.ReadExistingAssembly(requestedAssemblyName);
         if (assembly != null)
         {
             return assembly;
         }
         Common.Log("Loading assembly '{0}' into the AppDomain", requestedAssemblyName);
         assembly = Common.ReadFromEmbeddedResources(assemblyNames, symbolNames, requestedAssemblyName);
         if (assembly == null)
         {
             lock (nullCacheLock)
             {
                 nullCache[e.Name] = true;
             }
             // Handles retargeted assemblies like PCL
             if (requestedAssemblyName.Flags == AssemblyNameFlags.Retargetable)
             {
                 assembly = Assembly.Load(requestedAssemblyName);
             }
         }
         return assembly;
     }
Member Data Documentation
readonly Dictionary<string, string> ILTemplate.assemblyNames = new Dictionary<string, string>() static private
Definition at line 11 of file ILTemplate.cs.
int ILTemplate.isAttached = 0 static private
Definition at line 14 of file ILTemplate.cs.
readonly Dictionary<string, bool> ILTemplate.nullCache = new Dictionary<string, bool>() static private
Definition at line 9 of file ILTemplate.cs.
readonly object ILTemplate.nullCacheLock = new object() static private
Definition at line 8 of file ILTemplate.cs.
readonly Dictionary<string, string> ILTemplate.symbolNames = new Dictionary<string, string>() static private
Definition at line 12 of file ILTemplate.cs.
The documentation for this class was generated from the following file:
TGInstallerWrapper/obj/x86/Release/ILTemplate.cs