tgstation-server: Tgstation.Server.Host.Models.Job Class Reference
Tgstation.Server.Host.Models.Job Class Reference sealed
Public Member Functions
Job ()
Initializes a new instance of the Job class.
Job (long id)
Initializes a new instance of the Job class.
JobResponse ToApi ()
Public Member Functions inherited from Tgstation.Server.Host.Models.ILegacyApiTransformable< JobResponse >
TApiModel ToApi ()
Convert the ILegacyApiTransformable<TApiModel> to it's TApiModel .
Static Public Member Functions
static Job Create< TRight > (JobCode code, User? startedBy, Api.Models.Instance instance, TRight cancelRight)
Creates a new job for registering in the Jobs.IJobService.
static Job Create (JobCode code, User? startedBy, Api.Models.Instance instance)
Creates a new job for registering in the Jobs.IJobService.
Properties
User? StartedBy [get, set]
See JobResponse.StartedBy.
User? CancelledBy [get, set]
See JobResponse.CancelledBy.
Instance? Instance [get, set]
The Models.Instance the job belongs to if any.
Properties inherited from Tgstation.Server.Api.Models.Internal.Job
JobCode? JobCode [get, set]
The Models.JobCode.
string? Description [get, set]
English description of the Job.
ErrorCode? ErrorCode [get, set]
The Models.ErrorCode associated with the Job if any.
string? ExceptionDetails [get, set]
Details of any exceptions caught during the Job.
DateTimeOffset? StartedAt [get, set]
When the Job was started.
DateTimeOffset? StoppedAt [get, set]
When the Job stopped.
bool? Cancelled [get, set]
If the Job was cancelled.
RightsType? CancelRightsType [get, set]
The RightsType of CancelRight if it can be cancelled.
ulong? CancelRight [get, set]
The Rights required to cancel the Job.
Properties inherited from Tgstation.Server.Api.Models.EntityId
virtual ? long Id [get, set]
The ID of the entity.
Private Member Functions
Job (JobCode code, User? startedBy, Api.Models.Instance instance, RightsType? cancelRightsType, ulong? cancelRight)
Initializes a new instance of the Job class.
Detailed Description
Definition at line 14 of file Job.cs.
Constructor & Destructor Documentation
Job() [1/3]
Tgstation.Server.Host.Models.Job.Job ()
Initializes a new instance of the Job class.
Definition at line 71 of file Job.cs.
        {
        }
Job() [2/3]
Tgstation.Server.Host.Models.Job.Job (long id)
Initializes a new instance of the Job class.
Parameters
id The value of EntityId.Id.
Definition at line 79 of file Job.cs.
        {
            Id = id;
        }
References Tgstation.Server.Api.Models.EntityId.Id, and Tgstation.Server.Api.Rights.List.
Job() [3/3]
Tgstation.Server.Host.Models.Job.Job (JobCode code, User? startedBy, Api::Models::Instance instance, RightsType? cancelRightsType, ulong? cancelRight) private
Initializes a new instance of the Job class.
Parameters
code The value of Api.Models.Internal.Job.JobCode.
startedBy The value of StartedBy.
instance The value of Instance.
cancelRightsType The value of Api.Models.Internal.Job.CancelRightsType.
cancelRight The value of Api.Models.Internal.Job.CancelRight.
Definition at line 92 of file Job.cs.
        {
            StartedBy = startedBy;
            ArgumentNullException.ThrowIfNull(instance);
            Instance = new Instance
            {
                Id = instance.Id ?? throw new InvalidOperationException("Instance associated with job does not have an Id!"),
            };
            Description = typeof(JobCode)
                .GetField(code.ToString())!
                .GetCustomAttributes(false)
                .OfType<DescriptionAttribute>()
                .First()
                .Description;
            JobCode = code;
            CancelRight = cancelRight;
            CancelRightsType = cancelRightsType;
        }
References Tgstation.Server.Api.Models.Internal.Job.CancelRight, Tgstation.Server.Api.Models.Internal.Job.CancelRightsType, Tgstation.Server.Api.Models.Internal.Job.Description, Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Api.Rights.List, and Tgstation.Server.Host.Models.Job.StartedBy.
Member Function Documentation
Create()
static Job Tgstation.Server.Host.Models.Job.Create (JobCode code, User? startedBy, Api.Models.Instance instance) static
Creates a new job for registering in the Jobs.IJobService.
Parameters
code The value of Api.Models.Internal.Job.JobCode. Api.Models.Internal.Job.Description will be derived from this.
startedBy The value of StartedBy. If null, the User.TgsSystemUserName user will be used.
instance The Api.Models.Instance used to generate the value of Instance.
Returns
A new Job ready to be registered with the Jobs.IJobService.
Referenced by Tgstation.Server.Host.Components.Instance.AutoUpdateAction(), Tgstation.Server.Host.Controllers.RepositoryController.Create(), Tgstation.Server.Host.Controllers.DreamDaemonController.Create(), Tgstation.Server.Host.Controllers.DreamMakerController.Create(), Tgstation.Server.Host.Controllers.DreamDaemonController.CreateDump(), Tgstation.Server.Host.Controllers.RepositoryController.Delete(), Tgstation.Server.Host.Controllers.RepositoryController.Reclone(), Tgstation.Server.Host.Components.Chat.Providers.Provider.ReconnectionLoop(), Tgstation.Server.Host.Controllers.DreamDaemonController.Restart(), Tgstation.Server.Host.Controllers.InstanceController.Update(), and Tgstation.Server.Host.Controllers.RepositoryController.Update().
Create< TRight >()
static Job Tgstation.Server.Host.Models.Job.Create< TRight > (JobCode code, User? startedBy, Api.Models.Instance instance, TRight cancelRight) static
Creates a new job for registering in the Jobs.IJobService.
Template Parameters
TRight The RightsType of cancelRight .
Parameters
code The value of Api.Models.Internal.Job.JobCode. Api.Models.Internal.Job.Description will be derived from this.
startedBy The value of StartedBy. If null, the User.TgsSystemUserName user will be used.
instance The Api.Models.Instance used to generate the value of Instance.
cancelRight The value of Api.Models.Internal.Job.CancelRight. Api.Models.Internal.Job.CancelRightsType will be derived from this.
Returns
A new Job ready to be registered with the Jobs.IJobService.
Type Constraints
TRight : Enum
TRight : new
TRight : code
TRight : startedBy
TRight : instance
TRight : RightsHelper.TypeToRight<TRight>()
TRight : ulong
TRight : object
TRight : cancelRight
ToApi()
JobResponse Tgstation.Server.Host.Models.Job.ToApi ()
References Tgstation.Server.Api.Models.Internal.Job.Cancelled, Tgstation.Server.Host.Models.Job.CancelledBy, Tgstation.Server.Api.Models.Internal.Job.CancelRight, Tgstation.Server.Api.Models.Internal.Job.CancelRightsType, Tgstation.Server.Api.Models.UserName.CreateUserName(), Tgstation.Server.Api.Models.Internal.Job.Description, Tgstation.Server.Api.Models.Internal.Job.ErrorCode, Tgstation.Server.Api.Models.Internal.Job.ExceptionDetails, Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Api.Rights.List, Tgstation.Server.Api.Models.Internal.Job.StartedAt, Tgstation.Server.Host.Models.Job.StartedBy, and Tgstation.Server.Api.Models.Internal.Job.StoppedAt.
Referenced by Tgstation.Server.Host.Controllers.RepositoryController.Create(), Tgstation.Server.Host.Controllers.RepositoryController.Delete(), Tgstation.Server.Host.Controllers.RepositoryController.Reclone(), Tgstation.Server.Host.Jobs.JobService.RunJob(), and Tgstation.Server.Host.Models.CompileJob.ToApi().
Property Documentation
CancelledBy
User? Tgstation.Server.Host.Models.Job.CancelledBy get set
See JobResponse.CancelledBy.
Definition at line 26 of file Job.cs.
{ get; set; }
Referenced by Tgstation.Server.Host.Models.Job.ToApi().
Instance
Instance? Tgstation.Server.Host.Models.Job.Instance get set
The Models.Instance the job belongs to if any.
Definition at line 32 of file Job.cs.
{ get; set; }
Referenced by Tgstation.Server.Host.Jobs.JobsHub.HubGroupName(), Tgstation.Server.Host.Jobs.JobService.RegisterOperation(), and Tgstation.Server.Host.Jobs.JobService.RunJob().
StartedBy
User? Tgstation.Server.Host.Models.Job.StartedBy get set
See JobResponse.StartedBy.
Definition at line 21 of file Job.cs.
{ get; set; }
Referenced by Tgstation.Server.Host.Models.Job.Job(), Tgstation.Server.Host.Jobs.JobService.RegisterOperation(), and Tgstation.Server.Host.Models.Job.ToApi().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Models/Job.cs