tgstation-server: Tgstation.Server.Host.Core.SemaphoreSlimContext Class Reference
Tgstation.Server.Host.Core.SemaphoreSlimContext Class Reference
Async lock context helper.
Public Member Functions
void Dispose ()
Release the lock on lockedSemaphore.
Static Public Member Functions
static async Task< SemaphoreSlimContext > Lock (SemaphoreSlim semaphore, CancellationToken cancellationToken)
Asyncronously locks a semaphore .
Private Member Functions
SemaphoreSlimContext (SemaphoreSlim lockedSemaphore)
Initializes a new instance of the SemaphoreSlimContext class.
~SemaphoreSlimContext ()
Finalizes an instance of the SemaphoreSlimContext class.
Private Attributes
readonly SemaphoreSlim lockedSemaphore
The locked SemaphoreSlim.
readonly object disposeLock
lock object for disposed.
bool disposed
If Dispose has been called.
Detailed Description
Async lock context helper.
Definition at line 10 of file SemaphoreSlimContext.cs.
Constructor & Destructor Documentation
SemaphoreSlimContext()
Tgstation.Server.Host.Core.SemaphoreSlimContext.SemaphoreSlimContext (SemaphoreSlim lockedSemaphore) private
Initializes a new instance of the SemaphoreSlimContext class.
Parameters
lockedSemaphore The value of lockedSemaphore.
Definition at line 46 of file SemaphoreSlimContext.cs.
         {
             this.lockedSemaphore = lockedSemaphore;
             disposeLock = new object();
         }
References Tgstation.Server.Host.Core.SemaphoreSlimContext.disposeLock, and Tgstation.Server.Host.Core.SemaphoreSlimContext.lockedSemaphore.
Referenced by Tgstation.Server.Host.Core.SemaphoreSlimContext.Lock().
~SemaphoreSlimContext()
Tgstation.Server.Host.Core.SemaphoreSlimContext.~SemaphoreSlimContext () private
Finalizes an instance of the SemaphoreSlimContext class.
Member Function Documentation
Dispose()
void Tgstation.Server.Host.Core.SemaphoreSlimContext.Dispose ()
Release the lock on lockedSemaphore.
Definition at line 62 of file SemaphoreSlimContext.cs.
         {
             lock (disposeLock)
             {
                 if (disposed)
                     return;
                 disposed = true;
             }
             GC.SuppressFinalize(this);
             lockedSemaphore.Release();
         }
References Tgstation.Server.Host.Core.SemaphoreSlimContext.disposed, Tgstation.Server.Host.Core.SemaphoreSlimContext.disposeLock, and Tgstation.Server.Host.Core.SemaphoreSlimContext.lockedSemaphore.
Lock()
static async Task<SemaphoreSlimContext> Tgstation.Server.Host.Core.SemaphoreSlimContext.Lock (SemaphoreSlim semaphore, CancellationToken cancellationToken) static
Asyncronously locks a semaphore .
Parameters
semaphore The SemaphoreSlim to lock.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the SemaphoreSlimContext for the lock.
Definition at line 18 of file SemaphoreSlimContext.cs.
         {
             if (semaphore == null)
                 throw new ArgumentNullException(nameof(semaphore));
             cancellationToken.ThrowIfCancellationRequested();
             await semaphore.WaitAsync(cancellationToken).ConfigureAwait(false);
             return new SemaphoreSlimContext(semaphore);
         }
References Tgstation.Server.Host.Core.SemaphoreSlimContext.SemaphoreSlimContext().
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ChangeSettings(), Tgstation.Server.Host.Components.Byond.ByondManager.ChangeVersion(), Tgstation.Server.Host.Components.Repository.RepositoryManager.CloneRepository(), Tgstation.Server.Host.Components.StaticFiles.Configuration.CopyDMFilesTo(), Tgstation.Server.Host.Components.StaticFiles.Configuration.CreateDirectory(), Tgstation.Server.Host.Components.StaticFiles.Configuration.DeleteDirectory(), Tgstation.Server.Host.Components.Repository.RepositoryManager.DeleteRepository(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.DisposeAndNullControllers(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleChatCommand(), Tgstation.Server.Host.Components.StaticFiles.Configuration.HandleEvent(), Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.InstallDirectX(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Launch(), Tgstation.Server.Host.Components.StaticFiles.Configuration.ListDirectory(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.MonitorLifetimes(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.MonitorRestart(), Tgstation.Server.Host.Components.InstanceManager.OfflineInstance(), Tgstation.Server.Host.Components.InstanceManager.OnlineInstance(), Tgstation.Server.Host.Components.StaticFiles.Configuration.Read(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ResetRebootState(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Restart(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.StartAsync(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Terminate(), Tgstation.Server.Host.Components.Byond.ByondExecutableLock.TrustDmbPath(), and Tgstation.Server.Host.Components.StaticFiles.Configuration.Write().
Member Data Documentation
disposed
bool Tgstation.Server.Host.Core.SemaphoreSlimContext.disposed private
If Dispose has been called.
Definition at line 40 of file SemaphoreSlimContext.cs.
Referenced by Tgstation.Server.Host.Core.SemaphoreSlimContext.Dispose().
disposeLock
readonly object Tgstation.Server.Host.Core.SemaphoreSlimContext.disposeLock private
lock object for disposed.
Definition at line 35 of file SemaphoreSlimContext.cs.
Referenced by Tgstation.Server.Host.Core.SemaphoreSlimContext.Dispose(), and Tgstation.Server.Host.Core.SemaphoreSlimContext.SemaphoreSlimContext().
lockedSemaphore
readonly SemaphoreSlim Tgstation.Server.Host.Core.SemaphoreSlimContext.lockedSemaphore private
The locked SemaphoreSlim.
Definition at line 30 of file SemaphoreSlimContext.cs.
Referenced by Tgstation.Server.Host.Core.SemaphoreSlimContext.Dispose(), and Tgstation.Server.Host.Core.SemaphoreSlimContext.SemaphoreSlimContext().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Core/SemaphoreSlimContext.cs