tgstation-server: Tgstation.Server.Host.Security.AuthorizationContextHubFilter Class Reference
Tgstation.Server.Host.Security.AuthorizationContextHubFilter Class Reference sealed
An IHubFilter that denies method calls and connections if the IAuthenticationContext is not valid for an authorized user.
Public Member Functions
AuthorizationContextHubFilter (IAuthenticationContext authenticationContext, ILogger< AuthorizationContextHubFilter > logger)
Initializes a new instance of the AuthorizationContextHubFilter class.
async Task OnConnectedAsync (HubLifetimeContext context, Func< HubLifetimeContext, Task > next)
async ValueTask< object?> InvokeMethodAsync (HubInvocationContext invocationContext, Func< HubInvocationContext, ValueTask< object?> > next)
Private Member Functions
bool ValidateAuthenticationContext (Hub hub)
Validates the IAuthenticationContext for the hub event.
Private Attributes
readonly IAuthenticationContext authenticationContext
The IAuthenticationContext for the AuthorizationContextHubFilter.
readonly ILogger< AuthorizationContextHubFilter > logger
The ILogger for the AuthorizationContextHubFilter.
Detailed Description
An IHubFilter that denies method calls and connections if the IAuthenticationContext is not valid for an authorized user.
Definition at line 15 of file AuthorizationContextHubFilter.cs.
Constructor & Destructor Documentation
AuthorizationContextHubFilter()
Tgstation.Server.Host.Security.AuthorizationContextHubFilter.AuthorizationContextHubFilter (IAuthenticationContext authenticationContext, ILogger< AuthorizationContextHubFilter > logger)
Initializes a new instance of the AuthorizationContextHubFilter class.
Parameters
authenticationContext The value of authenticationContext.
logger The value of logger.
Definition at line 32 of file AuthorizationContextHubFilter.cs.
        {
            this.authenticationContext = authenticationContext ?? throw new ArgumentNullException(nameof(authenticationContext));
            this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }
References Tgstation.Server.Host.Security.AuthorizationContextHubFilter.authenticationContext, and Tgstation.Server.Host.Security.AuthorizationContextHubFilter.logger.
Member Function Documentation
InvokeMethodAsync()
async ValueTask< object?> Tgstation.Server.Host.Security.AuthorizationContextHubFilter.InvokeMethodAsync (HubInvocationContext invocationContext, Func< HubInvocationContext, ValueTask< object?> > next)
Definition at line 49 of file AuthorizationContextHubFilter.cs.
        {
            ArgumentNullException.ThrowIfNull(invocationContext);
            if (ValidateAuthenticationContext(invocationContext.Hub))
                return await next(invocationContext);
            return null;
        }
References Tgstation.Server.Host.Security.AuthorizationContextHubFilter.ValidateAuthenticationContext().
OnConnectedAsync()
async Task Tgstation.Server.Host.Security.AuthorizationContextHubFilter.OnConnectedAsync (HubLifetimeContext context, Func< HubLifetimeContext, Task > next)
Definition at line 41 of file AuthorizationContextHubFilter.cs.
        {
            ArgumentNullException.ThrowIfNull(context);
            if (ValidateAuthenticationContext(context.Hub))
                await next(context);
        }
References Tgstation.Server.Host.Security.AuthorizationContextHubFilter.ValidateAuthenticationContext().
ValidateAuthenticationContext()
bool Tgstation.Server.Host.Security.AuthorizationContextHubFilter.ValidateAuthenticationContext (Hub hub) private
Validates the IAuthenticationContext for the hub event.
Parameters
hub The current Hub.
Returns
true if the hub call should continue, false if it shouldn't and has been aborted.
Definition at line 63 of file AuthorizationContextHubFilter.cs.
        {
            if (!authenticationContext.Valid)
                logger.LogTrace("The token for connection {connectionId} is no longer authenticated! Aborting...", hub.Context.ConnectionId);
            else if (!authenticationContext.User.Require(x => x.Enabled))
                logger.LogTrace("The token for connection {connectionId} is no longer authorized! Aborting...", hub.Context.ConnectionId);
            else
                return true;
            var hubType = hub.GetType();
            var allHubProperties = hubType.GetProperties();
            var typedClientsProperty = allHubProperties.Single(
                prop => prop.PropertyType.IsConstructedGenericType
                    && prop.Name == nameof(hub.Clients));
            var clients = typedClientsProperty.GetValue(hub);
            var callerProperty = clients!.GetType().GetProperty(nameof(hub.Clients.Caller));
            var caller = callerProperty!.GetValue(clients);
            hub.Context.Abort();
            return false;
        }
References Tgstation.Server.Host.Security.AuthorizationContextHubFilter.authenticationContext, Tgstation.Server.Host.Security.AuthorizationContextHubFilter.logger, Tgstation.Server.Host.Security.IAuthenticationContext.User, and Tgstation.Server.Host.Security.IAuthenticationContext.Valid.
Referenced by Tgstation.Server.Host.Security.AuthorizationContextHubFilter.InvokeMethodAsync(), and Tgstation.Server.Host.Security.AuthorizationContextHubFilter.OnConnectedAsync().
Member Data Documentation
authenticationContext
readonly IAuthenticationContext Tgstation.Server.Host.Security.AuthorizationContextHubFilter.authenticationContext private
The IAuthenticationContext for the AuthorizationContextHubFilter.
Definition at line 20 of file AuthorizationContextHubFilter.cs.
Referenced by Tgstation.Server.Host.Security.AuthorizationContextHubFilter.AuthorizationContextHubFilter(), and Tgstation.Server.Host.Security.AuthorizationContextHubFilter.ValidateAuthenticationContext().
logger
readonly ILogger<AuthorizationContextHubFilter> Tgstation.Server.Host.Security.AuthorizationContextHubFilter.logger private
The ILogger for the AuthorizationContextHubFilter.
Definition at line 25 of file AuthorizationContextHubFilter.cs.
Referenced by Tgstation.Server.Host.Security.AuthorizationContextHubFilter.AuthorizationContextHubFilter(), and Tgstation.Server.Host.Security.AuthorizationContextHubFilter.ValidateAuthenticationContext().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Security/AuthorizationContextHubFilter.cs