tgstation-server: Tgstation.Server.Host.Extensions.ApplicationBuilderExtensions Class Reference
Tgstation.Server.Host.Extensions.ApplicationBuilderExtensions Class Reference
Extensions for IApplicationBuilder.
Static Public Member Functions
static void UseDbConflictHandling (this IApplicationBuilder applicationBuilder)
Return a ConflictObjectResult for DbUpdateExceptions.
static void UseCancelledRequestSuppression (this IApplicationBuilder applicationBuilder)
Suppress global::System.Threading.Tasks.TaskCanceledException warnings when a user aborts a request.
static void UseServerErrorHandling (this IApplicationBuilder applicationBuilder)
Suppress all in flight Exceptions for the request with error 500.
static void UseApiCompatibility (this IApplicationBuilder applicationBuilder)
Check that the API version is the current major version if it's present in the headers.
static void UseServerBranding (this IApplicationBuilder applicationBuilder, IAssemblyInformationProvider assemblyInformationProvider)
Add the X-Powered-By response header.
static void UseDisabledNginxProxyBuffering (this IApplicationBuilder applicationBuilder)
Add the X-Accel-Buffering response header.
static void UseAdditionalRequestLoggingContext (this IApplicationBuilder applicationBuilder, SwarmConfiguration swarmConfiguration)
Adds additional global LogContext to the request pipeline.
Static Private Member Functions
static ILogger GetLogger (HttpContext httpContext)
Gets a ILogger from a given httpContext .
Detailed Description
Extensions for IApplicationBuilder.
Definition at line 25 of file ApplicationBuilderExtensions.cs.
Member Function Documentation
GetLogger()
static ILogger Tgstation.Server.Host.Extensions.ApplicationBuilderExtensions.GetLogger (HttpContext httpContext) static private
Gets a ILogger from a given httpContext .
Parameters
httpContext The HttpContext to get the ILogger from.
Returns
A new ILogger.
Referenced by Tgstation.Server.Host.Extensions.ApplicationBuilderExtensions.UseCancelledRequestSuppression(), Tgstation.Server.Host.Extensions.ApplicationBuilderExtensions.UseDbConflictHandling(), and Tgstation.Server.Host.Extensions.ApplicationBuilderExtensions.UseServerErrorHandling().
UseAdditionalRequestLoggingContext()
static void Tgstation.Server.Host.Extensions.ApplicationBuilderExtensions.UseAdditionalRequestLoggingContext (this IApplicationBuilder applicationBuilder, SwarmConfiguration swarmConfiguration) static
Adds additional global LogContext to the request pipeline.
Parameters
applicationBuilder The IApplicationBuilder to configure.
swarmConfiguration The SwarmConfiguration.
Definition at line 187 of file ApplicationBuilderExtensions.cs.
        {
            ArgumentNullException.ThrowIfNull(applicationBuilder);
            ArgumentNullException.ThrowIfNull(swarmConfiguration);
            if (LogSwarmIdentifier && swarmConfiguration.Identifier != null)
                applicationBuilder.Use(async (context, next) =>
                {
                    using (LogContext.PushProperty(SerilogContextHelper.SwarmIdentifierContextProperty, swarmConfiguration.Identifier))
                        await next();
                });
        }
References Tgstation.Server.Api.Models.Internal.SwarmServer.Identifier, and Tgstation.Server.Host.Utils.SerilogContextHelper.SwarmIdentifierContextProperty.
UseApiCompatibility()
static void Tgstation.Server.Host.Extensions.ApplicationBuilderExtensions.UseApiCompatibility (this IApplicationBuilder applicationBuilder) static
Check that the API version is the current major version if it's present in the headers.
Parameters
applicationBuilder The IApplicationBuilder to configure.
Definition at line 126 of file ApplicationBuilderExtensions.cs.
        {
            ArgumentNullException.ThrowIfNull(applicationBuilder);
            applicationBuilder.Use(async (context, next) =>
            {
                var apiHeadersProvider = context.RequestServices.GetRequiredService<IApiHeadersProvider>();
                if (apiHeadersProvider.ApiHeaders?.Compatible() == false)
                {
                    await new BadRequestObjectResult(
                        new ErrorMessageResponse(ErrorCode.ApiMismatch))
                    .ExecuteResultAsync(new ActionContext
                    {
                        HttpContext = context,
                    });
                    return;
                }
                await next();
            });
        }
UseCancelledRequestSuppression()
static void Tgstation.Server.Host.Extensions.ApplicationBuilderExtensions.UseCancelledRequestSuppression (this IApplicationBuilder applicationBuilder) static
Suppress global::System.Threading.Tasks.TaskCanceledException warnings when a user aborts a request.
Parameters
applicationBuilder The IApplicationBuilder to configure.
Definition at line 71 of file ApplicationBuilderExtensions.cs.
        {
            ArgumentNullException.ThrowIfNull(applicationBuilder);
            applicationBuilder.Use(async (context, next) =>
            {
                var logger = GetLogger(context);
                try
                {
                    await next();
                }
                catch (OperationCanceledException ex)
                {
                    logger.LogDebug(ex, "Request cancelled!");
                }
            });
        }
References Tgstation.Server.Host.Extensions.ApplicationBuilderExtensions.GetLogger().
UseDbConflictHandling()
static void Tgstation.Server.Host.Extensions.ApplicationBuilderExtensions.UseDbConflictHandling (this IApplicationBuilder applicationBuilder) static
Return a ConflictObjectResult for DbUpdateExceptions.
Parameters
applicationBuilder The IApplicationBuilder to configure.
Definition at line 36 of file ApplicationBuilderExtensions.cs.
        {
            ArgumentNullException.ThrowIfNull(applicationBuilder);
            applicationBuilder.Use(async (context, next) =>
            {
                var logger = GetLogger(context);
                try
                {
                    await next();
                }
                catch (DbUpdateException e)
                {
                    if (e.InnerException is OperationCanceledException)
                    {
                        logger.LogTrace(e, "Rethrowing DbUpdateException as OperationCanceledException");
                        throw e.InnerException;
                    }
                    logger.LogDebug(e, "Database conflict!");
                    await new ConflictObjectResult(new ErrorMessageResponse(ErrorCode.DatabaseIntegrityConflict)
                    {
                        AdditionalData = String.Format(CultureInfo.InvariantCulture, (e.InnerException ?? e).Message),
                    }).ExecuteResultAsync(new ActionContext
                    {
                        HttpContext = context,
                    });
                }
            });
        }
References Tgstation.Server.Host.Extensions.ApplicationBuilderExtensions.GetLogger().
UseDisabledNginxProxyBuffering()
static void Tgstation.Server.Host.Extensions.ApplicationBuilderExtensions.UseDisabledNginxProxyBuffering (this IApplicationBuilder applicationBuilder) static
Add the X-Accel-Buffering response header.
Parameters
applicationBuilder The IApplicationBuilder to configure.
This is used to avoid interruption to SignalR streams by Nginx.
Definition at line 170 of file ApplicationBuilderExtensions.cs.
        {
            ArgumentNullException.ThrowIfNull(applicationBuilder);
            // https://www.nginx.com/resources/wiki/start/topics/examples/x-accel/#x-accel-buffering
            applicationBuilder.Use((context, next) =>
            {
                context.Response.Headers.Add("X-Accel-Buffering", "no");
                return next();
            });
        }
UseServerBranding()
static void Tgstation.Server.Host.Extensions.ApplicationBuilderExtensions.UseServerBranding (this IApplicationBuilder applicationBuilder, IAssemblyInformationProvider assemblyInformationProvider) static
Add the X-Powered-By response header.
Parameters
applicationBuilder The IApplicationBuilder to configure.
assemblyInformationProvider The IAssemblyInformationProvider to use.
Definition at line 153 of file ApplicationBuilderExtensions.cs.
        {
            ArgumentNullException.ThrowIfNull(applicationBuilder);
            ArgumentNullException.ThrowIfNull(assemblyInformationProvider);
            applicationBuilder.Use((context, next) =>
            {
                context.Response.Headers.Add("X-Powered-By", assemblyInformationProvider.VersionPrefix);
                return next();
            });
        }
References Tgstation.Server.Host.System.IAssemblyInformationProvider.VersionPrefix.
UseServerErrorHandling()
static void Tgstation.Server.Host.Extensions.ApplicationBuilderExtensions.UseServerErrorHandling (this IApplicationBuilder applicationBuilder) static
Suppress all in flight Exceptions for the request with error 500.
Parameters
applicationBuilder The IApplicationBuilder to configure.
Definition at line 92 of file ApplicationBuilderExtensions.cs.
        {
            ArgumentNullException.ThrowIfNull(applicationBuilder);
            applicationBuilder.Use(async (context, next) =>
            {
                var logger = GetLogger(context);
                try
                {
                    await next();
                }
                catch (Exception e)
                {
                    logger.LogError(e, "Failed request!");
                    await new JsonResult(
                        new ErrorMessageResponse(ErrorCode.InternalServerError)
{
                            AdditionalData = e.ToString(),
                        })
                    {
                        StatusCode = (int)HttpStatusCode.InternalServerError,
                    }
                    .ExecuteResultAsync(new ActionContext
                    {
                        HttpContext = context,
                    });
                }
            });
        }
References Tgstation.Server.Host.Extensions.ApplicationBuilderExtensions.GetLogger().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Extensions/ApplicationBuilderExtensions.cs