tgstation-server: TGS.Interface.ServerInterface Class Reference
TGS.Interface.ServerInterface Class Reference
Public Member Functions
ServerInterface ()
Construct an ServerInterface for a local connection
ServerInterface (string address, ushort port, string username, string password)
Construct an ServerInterface for a remote connection
ServerInterface (ServerInterface other)
Constructs an ServerInterface that connects to the same ITGSService as some other ITGInstance
ConnectivityLevel ConnectToInstance (string instanceName=null, bool skipChecks=false)
Targets instanceName as the instance to use with GetComponent<T>. Closes all connections to any previous instance
bool VersionMismatch (out string errorMessage)
Returns if the IServerInterface interface being used to connect to a service does not have the same release version as the service
T GetComponent< T > ()
Returns the requested IServerInterface component for the instance InstanceName. This does not guarantee a successful connection.
T GetServiceComponent< T > ()
Returns a root service component
ConnectivityLevel ConnectionStatus ()
Used to test if the ITGSService is avaiable on the target machine. Note that state can change at any time and any call into the may throw an exception because of communcation errors
ConnectivityLevel ConnectionStatus (out string error)
Used to test if the ITGSService is avaiable on the target machine. Note that state can change at any time and any call into the may throw an exception because of communcation errors
void Dispose ()
Implements the IDisposable pattern
Static Public Member Functions
static void SetBadCertificateHandler (Func< string, bool > handler)
Sets the function called when a remote login fails due to the server having an invalid SSL cert
Public Attributes
const long TransferLimitLocal = Int32.MaxValue
The maximum message size to and from a local server
const long TransferLimitRemote = 10485760
The maximum message size to and from a remote server
const string MasterInterfaceName = "TGStationServerService"
Base name of communication URLs
const string InstanceInterfaceName = MasterInterfaceName + "/Instance"
Base name of instance URLs
Static Public Attributes
static readonly IList< Type > ValidServiceInterfaces = new List<Type> { typeof(ITGSService), typeof(ITGInstanceManager), typeof(ITGConnectivity), typeof(ITGLanding) }
List of s that can be used with GetServiceComponent<T>
static readonly Version Version = Assembly.GetExecutingAssembly().GetName().Version
Version of the interface
static readonly IList< Type > ValidInstanceInterfaces = CollectComponents()
List of s that can be used with GetComponent<T>
Properties
Version ServerVersion [get]
string InstanceName [get, private set]
string HTTPSURL [get]
ushort HTTPSPort [get]
bool IsRemoteConnection [get]
Properties inherited from TGS.Interface.IServerInterface
Version ServerVersion [get]
The Version of the connected ITGSService
string InstanceName [get]
The name of the current instance in use. Defaults to
string HTTPSURL [get]
If this is set, we will try and connect to an HTTPS server running at this address
ushort HTTPSPort [get]
The port used to connect to the ITGSService
bool IsRemoteConnection [get]
Checks if the IServerInterface is setup for a remote connection
Private Member Functions
void CloseAllChannels (bool includingRoot)
Closes all ChannelFactorys stored in ChannelFactoryCache and clears it
T GetComponentImpl< T > (bool useInstanceName)
Returns the requested ServerInterface component for the instance InstanceName. This does not guarantee a successful connection. ChannelFactory<TChannel>s created this way are recycled for minimum latency and bandwidth usage
ChannelFactory< T > CreateChannel< T > (string instanceName)
Directly creates a ChannelFactory<TChannel> for T without caching. This should be eventually closed by the caller
void Dispose (bool disposing)
Implements the IDisposable pattern. Calls CloseAllChannels
Static Private Member Functions
static IList< Type > CollectComponents ()
Returns a IList<T> of Types that can be used with the service
static void ChannelFactory_Closed (object sender, EventArgs e)
Disposes a closed ChannelFactory
Private Attributes
Version _serverVersion
The ServerVersion
readonly string _HTTPSURL
If this is set, we will try and connect to an HTTPS server running at this address
readonly ushort _HTTPSPort
The port used to connect to the ITGSService
readonly string HTTPSUsername
Username for remote operations
readonly string HTTPSPassword
Password for remote operations
IDictionary< string, ChannelFactory > ChannelFactoryCache = new Dictionary<string, ChannelFactory>()
Associated list of open ChannelFactorys keyed by type name. A ChannelFactory in this list may close or fault at any time. Must be locked before being accessed
bool disposedValue = false
To detect redundant Dispose(bool) calls
Detailed Description
Definition at line 87 of file ServerInterface.cs.
Constructor & Destructor Documentation
TGS.Interface.ServerInterface.ServerInterface ()
Construct an ServerInterface for a local connection
Definition at line 235 of file ServerInterface.cs.
 { }
TGS.Interface.ServerInterface.ServerInterface (string address, ushort port, string username, string password)
Construct an ServerInterface for a remote connection
Parameters
address The address of the remote server
port The port the remote server runs on
username Windows account username for the remote server
password Windows account password for the remote server
Definition at line 244 of file ServerInterface.cs.
         {
             _HTTPSURL = address;
             _HTTPSPort = port;
             HTTPSUsername = username;
             HTTPSPassword = password;
         }
TGS.Interface.ServerInterface.ServerInterface (ServerInterface other)
Constructs an ServerInterface that connects to the same ITGSService as some other ITGInstance
Parameters
other Another ServerInterface to copy settings from
Definition at line 256 of file ServerInterface.cs.
 : this(other.HTTPSURL, other.HTTPSPort, other.HTTPSUsername, other.HTTPSPassword) { }
Member Function Documentation
static void TGS.Interface.ServerInterface.ChannelFactory_Closed (object sender, EventArgs e) static private
Disposes a closed ChannelFactory
Parameters
sender The channel factory that was closed
e The event arguments
Definition at line 350 of file ServerInterface.cs.
         {
             (sender as IDisposable).Dispose();
         }
void TGS.Interface.ServerInterface.CloseAllChannels (bool includingRoot) private
Closes all ChannelFactorys stored in ChannelFactoryCache and clears it
Parameters
includingRoot If set to , doesn't clear the channels that are used by ITGSService
Definition at line 306 of file ServerInterface.cs.
         {
             string[] RootThings = { typeof(ITGSService).Name, 'S' + typeof(ITGConnectivity).Name };
             lock (ChannelFactoryCache)
             {
                 var toRemove = new List<string>();
                 foreach (var I in ChannelFactoryCache)
                 {
                     if (RootThings.Contains(I.Key))
                         continue;
                     var cf = I.Value;
                     try
                     {
                         cf.Closed += ChannelFactory_Closed;
                         cf.Close();
                     }
                     catch
                     {
                         cf.Abort();
                     }
                     toRemove.Add(I.Key);
                 }
                 foreach (var I in toRemove)
                     ChannelFactoryCache.Remove(I);
             }
         }
static IList<Type> TGS.Interface.ServerInterface.CollectComponents () static private
Returns a IList<T> of Types that can be used with the service
Returns
A IList<T> of Types that can be used with the service
Definition at line 188 of file ServerInterface.cs.
         {
             var ConnectivityComponent = typeof(ITGConnectivity);
                                                                    //find all interfaces in this assembly in this namespace that have the service contract attribute
             var query = from t in Assembly.GetExecutingAssembly().GetTypes()
                         where t.IsInterface
                         && t.Namespace == ConnectivityComponent.Namespace
                         && t.GetCustomAttribute(typeof(ServiceContractAttribute)) != null
                         && (t == ConnectivityComponent || !ValidServiceInterfaces.Contains(t))
                         select t;
             return query.ToList();
         }
ConnectivityLevel TGS.Interface.ServerInterface.ConnectionStatus ()
Used to test if the ITGSService is avaiable on the target machine. Note that state can change at any time and any call into the may throw an exception because of communcation errors
Implements TGS.Interface.IServerInterface.
Definition at line 451 of file ServerInterface.cs.
         {
             return ConnectionStatus(out string unused);
         }
ConnectivityLevel TGS.Interface.ServerInterface.ConnectionStatus (out string error)
Used to test if the ITGSService is avaiable on the target machine. Note that state can change at any time and any call into the may throw an exception because of communcation errors
Implements TGS.Interface.IServerInterface.
Definition at line 457 of file ServerInterface.cs.
         {
             try
             {
                 GetComponentImpl<ITGConnectivity>(false).VerifyConnection();
             }
             catch (CommunicationException e)
             {
                 error = e.ToString();
                 return ConnectivityLevel.None;
             }
             try
             {
                 GetServiceComponent<ITGLanding>().Version();
             }
             catch(Exception e)
             {
                 error = e.ToString();
                 return ConnectivityLevel.Connected;
             }
             try
             {
                 GetServiceComponent<ITGSService>().Version();
                 error = null;
                 return ConnectivityLevel.Administrator;
             }
             catch(Exception e)
             {
                 error = e.ToString();
                 return ConnectivityLevel.Authenticated;
             }
         }
ConnectivityLevel TGS.Interface.ServerInterface.ConnectToInstance (string instanceName = null, bool skipChecks = false)
Targets instanceName as the instance to use with GetComponent<T>. Closes all connections to any previous instance
Implements TGS.Interface.IServerInterface.
Definition at line 259 of file ServerInterface.cs.
         {
             if (instanceName == null)
                 instanceName = InstanceName;
             if (!skipChecks && !ConnectionStatus().HasFlag(ConnectivityLevel.Connected))
                 return ConnectivityLevel.None;
             var prevInstance = InstanceName;
             if (prevInstance != instanceName)
                 CloseAllChannels(false);
             InstanceName = instanceName;
             if (skipChecks)
                 return ConnectivityLevel.Connected;
             try
             {
                 GetComponent<ITGConnectivity>().VerifyConnection();
             }
             catch
             {
                 InstanceName = prevInstance;
                 return ConnectivityLevel.None;
             }
             try
             {
                 GetComponent<ITGInstance>().ServerDirectory();
             }
             catch
             {
                 return ConnectivityLevel.Connected;
             }
             try
             {
                 GetComponent<ITGAdministration>().GetCurrentAuthorizedGroup();
                 return ConnectivityLevel.Administrator;
             }
             catch
             {
                 return ConnectivityLevel.Authenticated;
             }
         }
ChannelFactory<T> TGS.Interface.ServerInterface.CreateChannel< T > (string instanceName) private
Directly creates a ChannelFactory<TChannel> for T without caching. This should be eventually closed by the caller
Template Parameters
T The component of the channel to be created
Returns
The correct ChannelFactory<TChannel>
Exceptions
Exception Thrown if T isn't a valid component
Definition at line 416 of file ServerInterface.cs.
         {
             var accessPath = instanceName == null ? MasterInterfaceName : String.Format("{0}/{1}", InstanceInterfaceName, instanceName);
             var InterfaceName = typeof(T).Name;
             if (!IsRemoteConnection)
             {
                 var res2 = new ChannelFactory<T>(
                 new NetNamedPipeBinding { SendTimeout = new TimeSpan(0, 0, 30), MaxReceivedMessageSize = TransferLimitLocal }, new EndpointAddress(String.Format("net.pipe://localhost/{0}/{1}", accessPath, InterfaceName)));                                                      //10 megs
                 res2.Credentials.Windows.AllowedImpersonationLevel = TokenImpersonationLevel.Impersonation;
                 return res2;
             }
             //okay we're going over
             var binding = new WSHttpBinding()
             {
                 SendTimeout = new TimeSpan(0, 0, 40),
                 MaxReceivedMessageSize = TransferLimitRemote
             };
             var requireAuth = InterfaceName != typeof(ITGConnectivity).Name;
             binding.Security.Transport.ClientCredentialType = HttpClientCredentialType.None;
             binding.Security.Mode = requireAuth ? SecurityMode.TransportWithMessageCredential : SecurityMode.Transport;    //do not require auth for a connectivity check
             binding.Security.Message.ClientCredentialType = requireAuth ? MessageCredentialType.UserName : MessageCredentialType.None;
             var address = new EndpointAddress(String.Format("https://{0}:{1}/{2}/{3}", HTTPSURL, HTTPSPort, accessPath, InterfaceName));
             var res = new ChannelFactory<T>(binding, address);
             if (requireAuth)
             {
                 res.Credentials.UserName.UserName = HTTPSUsername;
                 res.Credentials.UserName.Password = HTTPSPassword;
                 res.Credentials.Windows.AllowedImpersonationLevel = TokenImpersonationLevel.Impersonation;
             }
             return res;
         }
void TGS.Interface.ServerInterface.Dispose (bool disposing) private
Implements the IDisposable pattern. Calls CloseAllChannels
Parameters
disposing if Dispose() was called manually, if it was from the finalizer
Definition at line 500 of file ServerInterface.cs.
         {
             if (!disposedValue)
             {
                 if (disposing)
                 {
                     CloseAllChannels(true);
                 }
                 // TODO: free unmanaged resources (unmanaged objects) and override a finalizer below.
                 // TODO: set large fields to null.
                 disposedValue = true;
             }
         }
void TGS.Interface.ServerInterface.Dispose ()
Implements the IDisposable pattern
Definition at line 525 of file ServerInterface.cs.
         {
             // Do not change this code. Put cleanup code in Dispose(bool disposing) above.
             Dispose(true);
             // TODO: uncomment the following line if the finalizer is overridden above.
             // GC.SuppressFinalize(this);
         }
T TGS.Interface.ServerInterface.GetComponent< T > ()
Returns the requested IServerInterface component for the instance InstanceName. This does not guarantee a successful connection.
Implements TGS.Interface.IServerInterface.
Definition at line 356 of file ServerInterface.cs.
         {
             var ToT = typeof(T);
             if (!ValidInstanceInterfaces.Contains(ToT))
                 throw new Exception("Invalid type!");
             return GetComponentImpl<T>(true);
         }
T TGS.Interface.ServerInterface.GetComponentImpl< T > (bool useInstanceName) private
Returns the requested ServerInterface component for the instance InstanceName. This does not guarantee a successful connection. ChannelFactory<TChannel>s created this way are recycled for minimum latency and bandwidth usage
Template Parameters
T The component to retrieve
Parameters
useInstanceName If InstanceName should be used to connect
Returns
The correct component
Definition at line 370 of file ServerInterface.cs.
         {
             if (useInstanceName & InstanceName == null)
                 throw new Exception("Instance not selected!");
             var actualToT = typeof(T);
             var tot = actualToT.Name;
             if (actualToT == typeof(ITGConnectivity) && !useInstanceName)
                 tot = 'S' + tot;
             ChannelFactory<T> cf;
             lock (ChannelFactoryCache)
             {
                 if (ChannelFactoryCache.ContainsKey(tot))
                     try
                     {
                         cf = ((ChannelFactory<T>)ChannelFactoryCache[tot]);
                         if (cf.State != CommunicationState.Opened)
                             throw new Exception();
                         return cf.CreateChannel();
                     }
                     catch
                     {
                         ChannelFactoryCache[tot].Abort();
                         ChannelFactoryCache.Remove(tot);
                     }
                 cf = CreateChannel<T>(useInstanceName ? InstanceName : null);
                 ChannelFactoryCache[tot] = cf;
             }
             return cf.CreateChannel();
         }
T TGS.Interface.ServerInterface.GetServiceComponent< T > ()
Returns a root service component
Implements TGS.Interface.IServerInterface.
Definition at line 402 of file ServerInterface.cs.
         {
             var ToT = typeof(T);
             if (!ValidServiceInterfaces.Contains(ToT))
                 throw new Exception("Invalid type!");
             return GetComponentImpl<T>(false);
         }
static void TGS.Interface.ServerInterface.SetBadCertificateHandler (Func< string, bool > handler) static
Sets the function called when a remote login fails due to the server having an invalid SSL cert
Parameters
handler The Func<T, TResult> to be called when a remote login is attempted while the server posesses a bad certificate. Passed a string of error information about the and should return if it the connection should be made anyway
Definition at line 205 of file ServerInterface.cs.
Referenced by TGS.ControlPanel.Program.Main(), TGS.CommandLine.Program.Main(), TGS.Interface.Tests.TestInterface.TestBadCertificateHandler(), and TGS.Interface.Tests.TestInterface.TestSetBadCertificateHandler().
         {
             ServicePointManager.ServerCertificateValidationCallback = (sender, cert, chain, error) =>
             {
                 string ErrorMessage;
                 switch (error)
                 {
                     case SslPolicyErrors.None:
                         return true;
                     case SslPolicyErrors.RemoteCertificateChainErrors:
                         ErrorMessage = "There are certificate chain errors.";
                         break;
                     case SslPolicyErrors.RemoteCertificateNameMismatch:
                         ErrorMessage = "The certificate name does not match.";
                         break;
                     case SslPolicyErrors.RemoteCertificateNotAvailable:
                         ErrorMessage = "The certificate doesn't exist in the trust store.";
                         break;
                     default:
                         ErrorMessage = "An unknown error occurred.";
                         break;
                 }
                 ErrorMessage = String.Format("The server's certificate failed to verify! Error: {0} Cert: {1}", ErrorMessage, cert.ToString());
                 return handler(ErrorMessage);
             };
         }
bool TGS.Interface.ServerInterface.VersionMismatch (out string errorMessage)
Returns if the IServerInterface interface being used to connect to a service does not have the same release version as the service
Implements TGS.Interface.IServerInterface.
Definition at line 334 of file ServerInterface.cs.
         {
             if(ServerVersion.Major != Version.Major || ServerVersion.Minor != Version.Minor || ServerVersion.Build != Version.Build)    //don't care about the patch level
             {
                 errorMessage = String.Format("Version mismatch between interface version ({0}) and service version ({1}). Some functionality may crash this program.", Version, ServerVersion);
                 return true;
             }
             errorMessage = null;
             return false;
         }
Member Data Documentation
readonly ushort TGS.Interface.ServerInterface._HTTPSPort private
The port used to connect to the ITGSService
Definition at line 164 of file ServerInterface.cs.
readonly string TGS.Interface.ServerInterface._HTTPSURL private
If this is set, we will try and connect to an HTTPS server running at this address
Definition at line 156 of file ServerInterface.cs.
Version TGS.Interface.ServerInterface._serverVersion private
The ServerVersion
Definition at line 126 of file ServerInterface.cs.
IDictionary<string, ChannelFactory> TGS.Interface.ServerInterface.ChannelFactoryCache = new Dictionary<string, ChannelFactory>() private
Associated list of open ChannelFactorys keyed by type name. A ChannelFactory in this list may close or fault at any time. Must be locked before being accessed
Definition at line 182 of file ServerInterface.cs.
bool TGS.Interface.ServerInterface.disposedValue = false private
To detect redundant Dispose(bool) calls
Definition at line 494 of file ServerInterface.cs.
readonly string TGS.Interface.ServerInterface.HTTPSPassword private
Password for remote operations
Definition at line 177 of file ServerInterface.cs.
readonly string TGS.Interface.ServerInterface.HTTPSUsername private
Username for remote operations
Definition at line 172 of file ServerInterface.cs.
const string TGS.Interface.ServerInterface.InstanceInterfaceName = MasterInterfaceName + "/Instance"
Base name of instance URLs
Definition at line 121 of file ServerInterface.cs.
Referenced by TGS.Server.Server.SetupInstance().
const string TGS.Interface.ServerInterface.MasterInterfaceName = "TGStationServerService"
Base name of communication URLs
Definition at line 117 of file ServerInterface.cs.
Referenced by TGS.Server.Server.SetupService().
const long TGS.Interface.ServerInterface.TransferLimitLocal = Int32.MaxValue
The maximum message size to and from a local server
Definition at line 107 of file ServerInterface.cs.
Referenced by TGS.Server.Server.AddEndpoint().
const long TGS.Interface.ServerInterface.TransferLimitRemote = 10485760
The maximum message size to and from a remote server
Definition at line 112 of file ServerInterface.cs.
Referenced by TGS.Server.Server.AddEndpoint().
readonly IList<Type> TGS.Interface.ServerInterface.ValidInstanceInterfaces = CollectComponents() static
List of s that can be used with GetComponent<T>
Definition at line 102 of file ServerInterface.cs.
Referenced by TGS.Server.Server.SetupInstance().
readonly IList<Type> TGS.Interface.ServerInterface.ValidServiceInterfaces = new List<Type> { typeof(ITGSService), typeof(ITGInstanceManager), typeof(ITGConnectivity), typeof(ITGLanding) } static
List of s that can be used with GetServiceComponent<T>
Definition at line 92 of file ServerInterface.cs.
Referenced by TGS.Server.Server.SetupService().
readonly Version TGS.Interface.ServerInterface.Version = Assembly.GetExecutingAssembly().GetName().Version static
Version of the interface
Definition at line 97 of file ServerInterface.cs.
Property Documentation
ushort TGS.Interface.ServerInterface.HTTPSPort get
Definition at line 167 of file ServerInterface.cs.
string TGS.Interface.ServerInterface.HTTPSURL get
Definition at line 159 of file ServerInterface.cs.
string TGS.Interface.ServerInterface.InstanceName get private set
Definition at line 151 of file ServerInterface.cs.
bool TGS.Interface.ServerInterface.IsRemoteConnection get
Definition at line 300 of file ServerInterface.cs.
Version TGS.Interface.ServerInterface.ServerVersion get
Definition at line 129 of file ServerInterface.cs.
The documentation for this class was generated from the following file:
TGS.Interface/ServerInterface.cs