tgstation-server: Tgstation.Server.Host.Components.Repository.RepositoryManager Class Reference
Tgstation.Server.Host.Components.Repository.RepositoryManager Class Reference sealed
Public Member Functions
RepositoryManager (ILibGit2RepositoryFactory repositoryFactory, ILibGit2Commands commands, IIOManager ioManager, IEventConsumer eventConsumer, IPostWriteHandler postWriteHandler, IGitRemoteFeaturesFactory gitRemoteFeaturesFactory, IOptionsMonitor< GeneralConfiguration > generalConfigurationOptions, ILogger< Repository > repositoryLogger, ILogger< RepositoryManager > logger)
Initializes a new instance of the RepositoryManager class.
void Dispose ()
async ValueTask< IRepository?> CloneRepository (Uri url, string? initialBranch, string? username, string? password, JobProgressReporter progressReporter, bool recurseSubmodules, CancellationToken cancellationToken)
Clone the repository at url .
Parameters
url The Uri of the remote repository to clone.
initialBranch The optional branch to clone.
username The optional username to clone from url .
password The optional password to clone from url .
progressReporter The JobProgressReporter for progress of the clone.
recurseSubmodules If submodules should be recusively cloned and initialized.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting i the newly cloned IRepository, null if one already exists.
async ValueTask< IRepository?> LoadRepository (CancellationToken cancellationToken)
Attempt to load the IRepository from the default location.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the loaded IRepository if it exists, null otherwise.
async ValueTask DeleteRepository (CancellationToken cancellationToken)
Delete the current repository.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Properties
bool InUse [get]
If something is holding a lock on the repository.
bool CloneInProgress [get, private set]
If a CloneRepository(Uri, string, string, string, JobProgressReporter, bool, CancellationToken) operation is in progress.
Properties inherited from Tgstation.Server.Host.Components.Repository.IRepositoryManager
Private Attributes
readonly ILibGit2RepositoryFactory repositoryFactory
The ILibGit2RepositoryFactory for the RepositoryManager.
readonly ILibGit2Commands commands
The ILibGit2Commands for the RepositoryManager.
readonly IIOManager ioManager
The IIOManager for the RepositoryManager.
readonly IEventConsumer eventConsumer
The IEventConsumer for the RepositoryManager.
readonly IPostWriteHandler postWriteHandler
The IPostWriteHandler for the RepositoryManager.
readonly IGitRemoteFeaturesFactory gitRemoteFeaturesFactory
The IGitRemoteFeaturesFactory for the RepositoryManager.
readonly IOptionsMonitor< GeneralConfiguration > generalConfigurationOptions
The IOptionsMonitor<TOptions> of GeneralConfiguration for the RepositoryManager.
readonly ILogger< Repository > repositoryLogger
The ILogger created Repositorys.
readonly ILogger< RepositoryManager > logger
The ILogger for the RepositoryManager.
readonly SemaphoreSlim semaphore
Used for controlling single access to the IRepository.
Detailed Description
Definition at line 21 of file RepositoryManager.cs.
Constructor & Destructor Documentation
RepositoryManager()
Tgstation.Server.Host.Components.Repository.RepositoryManager.RepositoryManager (ILibGit2RepositoryFactory repositoryFactory, ILibGit2Commands commands, IIOManager ioManager, IEventConsumer eventConsumer, IPostWriteHandler postWriteHandler, IGitRemoteFeaturesFactory gitRemoteFeaturesFactory, IOptionsMonitor< GeneralConfiguration > generalConfigurationOptions, ILogger< Repository > repositoryLogger, ILogger< RepositoryManager > logger)
Initializes a new instance of the RepositoryManager class.
Parameters
repositoryFactory The value of repositoryFactory.
commands The value of commands.
ioManager The value of ioManager.
eventConsumer The value of eventConsumer.
postWriteHandler The value of postWriteHandler.
gitRemoteFeaturesFactory The value of gitRemoteFeaturesFactory.
repositoryLogger The value of repositoryLogger.
generalConfigurationOptions The value of generalConfigurationOptions.
logger The value of logger.
Definition at line 91 of file RepositoryManager.cs.
        {
            this.repositoryFactory = repositoryFactory ?? throw new ArgumentNullException(nameof(repositoryFactory));
            this.commands = commands ?? throw new ArgumentNullException(nameof(commands));
            this.ioManager = ioManager ?? throw new ArgumentNullException(nameof(ioManager));
            this.eventConsumer = eventConsumer ?? throw new ArgumentNullException(nameof(eventConsumer));
            this.postWriteHandler = postWriteHandler ?? throw new ArgumentNullException(nameof(postWriteHandler));
            this.gitRemoteFeaturesFactory = gitRemoteFeaturesFactory ?? throw new ArgumentNullException(nameof(gitRemoteFeaturesFactory));
            this.repositoryLogger = repositoryLogger ?? throw new ArgumentNullException(nameof(repositoryLogger));
            this.generalConfigurationOptions = generalConfigurationOptions ?? throw new ArgumentNullException(nameof(generalConfigurationOptions));
            this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
            semaphore = new SemaphoreSlim(1);
        }
References Tgstation.Server.Host.Components.Repository.RepositoryManager.commands, Tgstation.Server.Host.Components.Repository.RepositoryManager.eventConsumer, Tgstation.Server.Host.Components.Repository.RepositoryManager.generalConfigurationOptions, Tgstation.Server.Host.Components.Repository.RepositoryManager.gitRemoteFeaturesFactory, Tgstation.Server.Host.Components.Repository.RepositoryManager.ioManager, Tgstation.Server.Host.Components.Repository.RepositoryManager.logger, Tgstation.Server.Host.Components.Repository.RepositoryManager.postWriteHandler, Tgstation.Server.Host.Components.Repository.RepositoryManager.repositoryFactory, Tgstation.Server.Host.Components.Repository.RepositoryManager.repositoryLogger, and Tgstation.Server.Host.Components.Repository.RepositoryManager.semaphore.
Member Function Documentation
CloneRepository()
async ValueTask< IRepository?> Tgstation.Server.Host.Components.Repository.RepositoryManager.CloneRepository (Uri url, string? initialBranch, string? username, string? password, JobProgressReporter progressReporter, bool recurseSubmodules, CancellationToken cancellationToken)
Clone the repository at url .
Parameters
url The Uri of the remote repository to clone.
initialBranch The optional branch to clone.
username The optional username to clone from url .
password The optional password to clone from url .
progressReporter The JobProgressReporter for progress of the clone.
recurseSubmodules If submodules should be recusively cloned and initialized.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting i the newly cloned IRepository, null if one already exists.
Implements Tgstation.Server.Host.Components.Repository.IRepositoryManager.
Definition at line 122 of file RepositoryManager.cs.
        {
            ArgumentNullException.ThrowIfNull(url);
            lock (semaphore)
            {
                if (CloneInProgress)
                    throw new JobException(ErrorCode.RepoCloning);
                CloneInProgress = true;
            }
            var repositoryPath = ioManager.ResolvePath();
            logger.LogInformation("Begin clone {url} to {path} (Branch: {initialBranch})", url, repositoryPath, initialBranch);
            try
            {
                using (await SemaphoreSlimContext.Lock(semaphore, cancellationToken))
                {
                    logger.LogTrace("Semaphore acquired for clone");
                    if (!await ioManager.DirectoryExists(repositoryPath, cancellationToken))
                        try
{
                            using var cloneProgressReporter = progressReporter.CreateSection(null, 0.75f);
                            using var checkoutProgressReporter = progressReporter.CreateSection(null, 0.25f);
                            var cloneOptions = new CloneOptions
{
                                RecurseSubmodules = recurseSubmodules,
                                OnCheckoutProgress = (path, completed, remaining) =>
{
                                    if (checkoutProgressReporter == null)
                                        return;
                                    var percentage = (double)completed / remaining;
                                    checkoutProgressReporter.ReportProgress(percentage);
                                },
                                BranchName = initialBranch,
                            };
                            cloneOptions.FetchOptions.Hydrate(
                                logger,
                                cloneProgressReporter,
                                await repositoryFactory.GenerateCredentialsHandler(
                                    gitRemoteFeaturesFactory.CreateGitRemoteFeatures(url),
                                    username,
                                    password,
                                    cancellationToken),
                                cancellationToken);
                            await repositoryFactory.Clone(
                                url,
                                cloneOptions,
                                repositoryPath,
                                cancellationToken);
                        }
                        catch
{
                            try
{
                                logger.LogTrace("Deleting partially cloned repository...");
                                // DCT: Cancellation token is for job, operation must run regardless
                                await ioManager.DeleteDirectory(repositoryPath, CancellationToken.None);
                            }
                            catch (Exception innerException)
{
                                logger.LogError(innerException, "Error deleting partially cloned repository!");
                            }
                            throw;
                        }
                    else
                    {
                        logger.LogDebug("Repository exists, clone aborted!");
                        return null;
                    }
                }
            }
            finally
            {
                logger.LogTrace("Semaphore released after clone");
                CloneInProgress = false;
            }
            logger.LogInformation("Clone complete!");
            return await LoadRepository(cancellationToken);
        }
References Tgstation.Server.Host.Components.Repository.ILibGit2RepositoryFactory.Clone(), Tgstation.Server.Host.Components.Repository.RepositoryManager.CloneInProgress, Tgstation.Server.Host.Components.Repository.IGitRemoteFeaturesFactory.CreateGitRemoteFeatures(), Tgstation.Server.Host.Jobs.JobProgressReporter.CreateSection(), Tgstation.Server.Host.IO.IIOManager.DeleteDirectory(), Tgstation.Server.Host.IO.IIOManager.DirectoryExists(), Tgstation.Server.Host.Components.Repository.ICredentialsProvider.GenerateCredentialsHandler(), Tgstation.Server.Host.Components.Repository.RepositoryManager.gitRemoteFeaturesFactory, Tgstation.Server.Host.Components.Repository.RepositoryManager.ioManager, Tgstation.Server.Host.Components.Repository.RepositoryManager.LoadRepository(), Tgstation.Server.Host.Utils.SemaphoreSlimContext.Lock(), Tgstation.Server.Host.Components.Repository.RepositoryManager.logger, Tgstation.Server.Host.Jobs.JobProgressReporter.ReportProgress(), Tgstation.Server.Host.Components.Repository.RepositoryManager.repositoryFactory, Tgstation.Server.Host.IO.IIOManager.ResolvePath(), and Tgstation.Server.Host.Components.Repository.RepositoryManager.semaphore.
DeleteRepository()
async ValueTask Tgstation.Server.Host.Components.Repository.RepositoryManager.DeleteRepository (CancellationToken cancellationToken)
Delete the current repository.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Repository.IRepositoryManager.
Definition at line 263 of file RepositoryManager.cs.
        {
            logger.LogInformation("Deleting repository...");
            try
            {
                using (await SemaphoreSlimContext.Lock(semaphore, cancellationToken))
                {
                    logger.LogTrace("Semaphore acquired, deleting Repository directory...");
                    await ioManager.DeleteDirectory(ioManager.ResolvePath(), cancellationToken);
                }
            }
            finally
            {
                logger.LogTrace("Semaphore released after delete attempt");
            }
        }
References Tgstation.Server.Host.IO.IIOManager.DeleteDirectory(), Tgstation.Server.Host.Components.Repository.RepositoryManager.ioManager, Tgstation.Server.Host.Utils.SemaphoreSlimContext.Lock(), Tgstation.Server.Host.Components.Repository.RepositoryManager.logger, Tgstation.Server.Host.IO.IIOManager.ResolvePath(), and Tgstation.Server.Host.Components.Repository.RepositoryManager.semaphore.
Referenced by Tgstation.Server.Host.Controllers.RepositoryController.Delete().
Dispose()
void Tgstation.Server.Host.Components.Repository.RepositoryManager.Dispose ()
Definition at line 115 of file RepositoryManager.cs.
        {
            logger.LogTrace("Disposing...");
            semaphore.Dispose();
        }
References Tgstation.Server.Host.Components.Repository.RepositoryManager.logger, and Tgstation.Server.Host.Components.Repository.RepositoryManager.semaphore.
Referenced by Tgstation.Server.Host.Components.Instance.DisposeAsync().
LoadRepository()
async ValueTask< IRepository?> Tgstation.Server.Host.Components.Repository.RepositoryManager.LoadRepository (CancellationToken cancellationToken)
Attempt to load the IRepository from the default location.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the loaded IRepository if it exists, null otherwise.
Implements Tgstation.Server.Host.Components.Repository.IRepositoryManager.
Definition at line 216 of file RepositoryManager.cs.
        {
            logger.LogTrace("Begin LoadRepository...");
            lock (semaphore)
                if (CloneInProgress)
                    throw new JobException(ErrorCode.RepoCloning);
            try
            {
                await semaphore.WaitAsync(cancellationToken);
                try
                {
                    logger.LogTrace("Semaphore acquired for load");
                    var libGit2Repo = await repositoryFactory.CreateFromPath(ioManager.ResolvePath(), cancellationToken);
                    return new Repository(
                        libGit2Repo,
                        commands,
                        ioManager,
                        eventConsumer,
                        repositoryFactory,
                        postWriteHandler,
                        gitRemoteFeaturesFactory,
                        repositoryFactory,
                        generalConfigurationOptions,
                        repositoryLogger,
                        () =>
{
                            logger.LogTrace("Releasing semaphore due to Repository disposal...");
                            semaphore.Release();
                        });
                }
                catch
                {
                    logger.LogTrace("Releasing semaphore as load failed");
                    semaphore.Release();
                    throw;
                }
            }
            catch (RepositoryNotFoundException e)
            {
                logger.LogTrace(e, "Repository not found!");
                return null;
            }
        }
References Tgstation.Server.Host.Components.Repository.RepositoryManager.CloneInProgress, Tgstation.Server.Host.Components.Repository.RepositoryManager.commands, Tgstation.Server.Host.Components.Repository.ILibGit2RepositoryFactory.CreateFromPath(), Tgstation.Server.Host.Components.Repository.RepositoryManager.eventConsumer, Tgstation.Server.Host.Components.Repository.RepositoryManager.generalConfigurationOptions, Tgstation.Server.Host.Components.Repository.RepositoryManager.gitRemoteFeaturesFactory, Tgstation.Server.Host.Components.Repository.RepositoryManager.ioManager, Tgstation.Server.Host.Components.Repository.RepositoryManager.logger, Tgstation.Server.Host.Components.Repository.RepositoryManager.postWriteHandler, Tgstation.Server.Host.Components.Repository.RepositoryManager.repositoryFactory, Tgstation.Server.Host.Components.Repository.RepositoryManager.repositoryLogger, Tgstation.Server.Host.IO.IIOManager.ResolvePath(), and Tgstation.Server.Host.Components.Repository.RepositoryManager.semaphore.
Referenced by Tgstation.Server.Host.Components.Instance.AutoUpdateAction(), Tgstation.Server.Host.Components.Repository.RepositoryManager.CloneRepository(), and Tgstation.Server.Host.Components.Instance.RepositoryAutoUpdateJob().
Member Data Documentation
commands
readonly ILibGit2Commands Tgstation.Server.Host.Components.Repository.RepositoryManager.commands private
The ILibGit2Commands for the RepositoryManager.
Definition at line 37 of file RepositoryManager.cs.
Referenced by Tgstation.Server.Host.Components.Repository.RepositoryManager.LoadRepository(), and Tgstation.Server.Host.Components.Repository.RepositoryManager.RepositoryManager().
eventConsumer
readonly IEventConsumer Tgstation.Server.Host.Components.Repository.RepositoryManager.eventConsumer private
The IEventConsumer for the RepositoryManager.
Definition at line 47 of file RepositoryManager.cs.
Referenced by Tgstation.Server.Host.Components.Repository.RepositoryManager.LoadRepository(), and Tgstation.Server.Host.Components.Repository.RepositoryManager.RepositoryManager().
generalConfigurationOptions
readonly IOptionsMonitor<GeneralConfiguration> Tgstation.Server.Host.Components.Repository.RepositoryManager.generalConfigurationOptions private
The IOptionsMonitor<TOptions> of GeneralConfiguration for the RepositoryManager.
Definition at line 62 of file RepositoryManager.cs.
Referenced by Tgstation.Server.Host.Components.Repository.RepositoryManager.LoadRepository(), and Tgstation.Server.Host.Components.Repository.RepositoryManager.RepositoryManager().
gitRemoteFeaturesFactory
readonly IGitRemoteFeaturesFactory Tgstation.Server.Host.Components.Repository.RepositoryManager.gitRemoteFeaturesFactory private
The IGitRemoteFeaturesFactory for the RepositoryManager.
Definition at line 57 of file RepositoryManager.cs.
Referenced by Tgstation.Server.Host.Components.Repository.RepositoryManager.CloneRepository(), Tgstation.Server.Host.Components.Repository.RepositoryManager.LoadRepository(), and Tgstation.Server.Host.Components.Repository.RepositoryManager.RepositoryManager().
ioManager
readonly IIOManager Tgstation.Server.Host.Components.Repository.RepositoryManager.ioManager private
The IIOManager for the RepositoryManager.
Definition at line 42 of file RepositoryManager.cs.
Referenced by Tgstation.Server.Host.Components.Repository.RepositoryManager.CloneRepository(), Tgstation.Server.Host.Components.Repository.RepositoryManager.DeleteRepository(), Tgstation.Server.Host.Components.Repository.RepositoryManager.LoadRepository(), and Tgstation.Server.Host.Components.Repository.RepositoryManager.RepositoryManager().
logger
readonly ILogger<RepositoryManager> Tgstation.Server.Host.Components.Repository.RepositoryManager.logger private
The ILogger for the RepositoryManager.
Definition at line 72 of file RepositoryManager.cs.
Referenced by Tgstation.Server.Host.Components.Repository.RepositoryManager.CloneRepository(), Tgstation.Server.Host.Components.Repository.RepositoryManager.DeleteRepository(), Tgstation.Server.Host.Components.Repository.RepositoryManager.Dispose(), Tgstation.Server.Host.Components.Repository.RepositoryManager.LoadRepository(), and Tgstation.Server.Host.Components.Repository.RepositoryManager.RepositoryManager().
postWriteHandler
readonly IPostWriteHandler Tgstation.Server.Host.Components.Repository.RepositoryManager.postWriteHandler private
The IPostWriteHandler for the RepositoryManager.
Definition at line 52 of file RepositoryManager.cs.
Referenced by Tgstation.Server.Host.Components.Repository.RepositoryManager.LoadRepository(), and Tgstation.Server.Host.Components.Repository.RepositoryManager.RepositoryManager().
repositoryFactory
readonly ILibGit2RepositoryFactory Tgstation.Server.Host.Components.Repository.RepositoryManager.repositoryFactory private
The ILibGit2RepositoryFactory for the RepositoryManager.
Definition at line 32 of file RepositoryManager.cs.
Referenced by Tgstation.Server.Host.Components.Repository.RepositoryManager.CloneRepository(), Tgstation.Server.Host.Components.Repository.RepositoryManager.LoadRepository(), and Tgstation.Server.Host.Components.Repository.RepositoryManager.RepositoryManager().
repositoryLogger
readonly ILogger<Repository> Tgstation.Server.Host.Components.Repository.RepositoryManager.repositoryLogger private
The ILogger created Repositorys.
Definition at line 67 of file RepositoryManager.cs.
Referenced by Tgstation.Server.Host.Components.Repository.RepositoryManager.LoadRepository(), and Tgstation.Server.Host.Components.Repository.RepositoryManager.RepositoryManager().
semaphore
readonly SemaphoreSlim Tgstation.Server.Host.Components.Repository.RepositoryManager.semaphore private
Used for controlling single access to the IRepository.
Definition at line 77 of file RepositoryManager.cs.
Referenced by Tgstation.Server.Host.Components.Repository.RepositoryManager.CloneRepository(), Tgstation.Server.Host.Components.Repository.RepositoryManager.DeleteRepository(), Tgstation.Server.Host.Components.Repository.RepositoryManager.Dispose(), Tgstation.Server.Host.Components.Repository.RepositoryManager.LoadRepository(), and Tgstation.Server.Host.Components.Repository.RepositoryManager.RepositoryManager().
Property Documentation
CloneInProgress
bool Tgstation.Server.Host.Components.Repository.RepositoryManager.CloneInProgress get private set
If a CloneRepository(Uri, string, string, string, JobProgressReporter, bool, CancellationToken) operation is in progress.
Implements Tgstation.Server.Host.Components.Repository.IRepositoryManager.
Definition at line 27 of file RepositoryManager.cs.
{ get; private set; }
Referenced by Tgstation.Server.Host.Components.Repository.RepositoryManager.CloneRepository(), and Tgstation.Server.Host.Components.Repository.RepositoryManager.LoadRepository().
InUse
bool Tgstation.Server.Host.Components.Repository.RepositoryManager.InUse get
If something is holding a lock on the repository.
Implements Tgstation.Server.Host.Components.Repository.IRepositoryManager.
Definition at line 24 of file RepositoryManager.cs.
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Repository/RepositoryManager.cs