tgstation-server: Tgstation.Server.Host.Utils.FifoSemaphore Class Reference
Tgstation.Server.Host.Utils.FifoSemaphore Class Reference sealed
A first-in first-out async semaphore.
Classes
class FifoSemaphoreTicket
class to represent a ticket in the ticketQueue and whether or not it is Abandoned.
Public Member Functions
FifoSemaphore ()
Initializes a new instance of the FifoSemaphore class.
void Dispose ()
async ValueTask< SemaphoreSlimContext > Lock (CancellationToken cancellationToken)
Locks the FifoSemaphore.
Private Attributes
readonly SemaphoreSlim semaphore
The backing SemaphoreSlim.
readonly Queue< FifoSemaphoreTicket > ticketQueue
The Queue<T> of ticket FifoSemaphoreTickets.
Detailed Description
A first-in first-out async semaphore.
This is contentious and could be re-written using TaskCompletionSources to make it promise based. However, it has a lower memory footprint without them and is fine for our uses.
Definition at line 12 of file FifoSemaphore.cs.
Constructor & Destructor Documentation
FifoSemaphore()
Tgstation.Server.Host.Utils.FifoSemaphore.FifoSemaphore ()
Initializes a new instance of the FifoSemaphore class.
Definition at line 38 of file FifoSemaphore.cs.
        {
            ticketQueue = new Queue<FifoSemaphoreTicket>();
            semaphore = new SemaphoreSlim(1);
        }
References Tgstation.Server.Host.Utils.FifoSemaphore.semaphore, and Tgstation.Server.Host.Utils.FifoSemaphore.ticketQueue.
Member Function Documentation
Dispose()
void Tgstation.Server.Host.Utils.FifoSemaphore.Dispose ()
Referenced by Tgstation.Server.Host.Components.Session.SessionController.DisposeAsync().
Lock()
async ValueTask< SemaphoreSlimContext > Tgstation.Server.Host.Utils.FifoSemaphore.Lock (CancellationToken cancellationToken)
Locks the FifoSemaphore.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the locked SemaphoreSlimContext.
Definition at line 52 of file FifoSemaphore.cs.
        {
            FifoSemaphoreTicket? ticket = null;
            using (cancellationToken.Register(
                () =>
                {
                    if (ticket != null)
                        ticket.Abandoned = true;
                }))
                while (true)
                {
                    var context = await SemaphoreSlimContext.Lock(semaphore, cancellationToken);
                    try
                    {
                        FifoSemaphoreTicket? peekedTicket = null;
                        while (ticketQueue.Count > 0)
{
                            peekedTicket = ticketQueue.Peek();
                            if (peekedTicket.Abandoned)
                                ticketQueue.Dequeue();
                            else
                                break;
                        }
                        cancellationToken.ThrowIfCancellationRequested();
                        bool goTime;
                        if (ticketQueue.Count == 0)
                            goTime = true;
                        else if (ticket == null)
{
                            ticket = new FifoSemaphoreTicket();
                            cancellationToken.ThrowIfCancellationRequested();
                            ticketQueue.Enqueue(ticket);
                            goTime = false;
                        }
                        else
{
                            goTime = peekedTicket == ticket;
                            if (goTime)
                                ticketQueue.Dequeue();
                        }
                        if (goTime)
{
                            var localContext = context;
                            context = null;
                            return localContext;
                        }
                    }
                    finally
                    {
                        context?.Dispose();
                    }
                    await Task.Yield();
                }
        }
References Tgstation.Server.Host.Utils.FifoSemaphore.FifoSemaphoreTicket.Abandoned, Tgstation.Server.Host.Utils.SemaphoreSlimContext.Lock(), Tgstation.Server.Host.Utils.FifoSemaphore.semaphore, and Tgstation.Server.Host.Utils.FifoSemaphore.ticketQueue.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.DisposeAsync(), and Tgstation.Server.Host.Components.Session.SessionController.SendRawTopic().
Member Data Documentation
semaphore
readonly SemaphoreSlim Tgstation.Server.Host.Utils.FifoSemaphore.semaphore private
The backing SemaphoreSlim.
Definition at line 28 of file FifoSemaphore.cs.
Referenced by Tgstation.Server.Host.Utils.FifoSemaphore.FifoSemaphore(), and Tgstation.Server.Host.Utils.FifoSemaphore.Lock().
ticketQueue
readonly Queue<FifoSemaphoreTicket> Tgstation.Server.Host.Utils.FifoSemaphore.ticketQueue private
The Queue<T> of ticket FifoSemaphoreTickets.
Definition at line 33 of file FifoSemaphore.cs.
Referenced by Tgstation.Server.Host.Utils.FifoSemaphore.FifoSemaphore(), and Tgstation.Server.Host.Utils.FifoSemaphore.Lock().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Utils/FifoSemaphore.cs