tgstation-server: Tgstation.Server.Host.Components.Repository.CredentialsProvider Class Reference
Tgstation.Server.Host.Components.Repository.CredentialsProvider Class Reference
Public Member Functions
CredentialsProvider (ILogger< CredentialsProvider > logger)
Construct a CredentialsProvider
CredentialsHandler GenerateHandler (string username, string password)
Generate a CredentialsHandler from a given username and password
Private Attributes
readonly ILogger< CredentialsProvider > logger
The ILogger for the CredentialsProvider
Detailed Description
Definition at line 9 of file CredentialsProvider.cs.
Constructor & Destructor Documentation
Tgstation.Server.Host.Components.Repository.CredentialsProvider.CredentialsProvider (ILogger< CredentialsProvider > logger)
Construct a CredentialsProvider
Parameters
logger The value of logger
Definition at line 20 of file CredentialsProvider.cs.
         {
             this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
         }
Member Function Documentation
CredentialsHandler Tgstation.Server.Host.Components.Repository.CredentialsProvider.GenerateHandler (string username, string password)
Generate a CredentialsHandler from a given username and password
Implements Tgstation.Server.Host.Components.Repository.ICredentialsProvider.
Referenced by Tgstation.Server.Host.Components.Repository.Repository.AddTestMerge(), Tgstation.Server.Host.Components.Repository.RepositoryManager.CloneRepository(), Tgstation.Server.Host.Components.Repository.Repository.Dispose(), and Tgstation.Server.Host.Components.Repository.Repository.FetchOrigin().
Member Data Documentation
readonly ILogger<CredentialsProvider> Tgstation.Server.Host.Components.Repository.CredentialsProvider.logger private
The ILogger for the CredentialsProvider
Definition at line 14 of file CredentialsProvider.cs.
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Repository/CredentialsProvider.cs