tgstation-server: Tgstation.Server.Host.Components.Watchdog.WatchdogBase Class Reference
Tgstation.Server.Host.Components.Watchdog.WatchdogBase Class Reference abstract
Base class for IWatchdogs.
Public Member Functions
async ValueTask DisposeAsync ()
async ValueTask< bool > ChangeSettings (DreamDaemonLaunchParameters launchParameters, CancellationToken cancellationToken)
Changes the ActiveLaunchParameters. If currently running, may trigger a graceful restart.
Parameters
launchParameters The new DreamDaemonLaunchParameters. May be modified.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in true if a reboot is required, false otherwise.
async ValueTask< MessageContent > HandleChatCommand (string commandName, string arguments, ChatUser sender, CancellationToken cancellationToken)
Handle a chat command.
Parameters
commandName The command name.
arguments Everything typed after commandName minus leading spaces.
sender The sending ChatUser.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the MessageContent text to send back.
async ValueTask Launch (CancellationToken cancellationToken)
Start the IWatchdog.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
virtual async ValueTask ResetRebootState (CancellationToken cancellationToken)
Cancels pending graceful actions.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
async ValueTask Restart (bool graceful, CancellationToken cancellationToken)
Restarts the watchdog.
Parameters
graceful If true the restart will be delayed until a reboot is detected in the active server's DMAPI and this function will retrun immediately.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
async Task StartAsync (CancellationToken cancellationToken)
async Task StopAsync (CancellationToken cancellationToken)
async ValueTask Terminate (bool graceful, CancellationToken cancellationToken)
Stops the watchdog.
Parameters
graceful If true the termination will be delayed until a reboot is detected in the active server's DMAPI and this function will return immediately.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
async ValueTask HandleRestart (Version? updateVersion, bool handlerMayDelayShutdownWithExtremelyLongRunningTasks, CancellationToken cancellationToken)
Handle a restart of the server.
Parameters
updateVersion The Version being updated to, null if not being changed.
handlerMayDelayShutdownWithExtremelyLongRunningTasks If false the IRestartHandler should aim to complete the Task returned from this function ASAP.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
ValueTask InstanceRenamed (string newInstanceName, CancellationToken cancellationToken)
Called when the owning Instance is renamed.
Parameters
newInstanceName The new Api.Models.NamedEntity.Name.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
async ValueTask CreateDump (CancellationToken cancellationToken)
Attempt to create a process dump for DreamDaemon.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
async ValueTask< bool > Broadcast (string message, CancellationToken cancellationToken)
Send a broadcast message to the DMAPI.
Parameters
message The message to broadcast.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in true if the broadcast succeeded., false otherwise.
void RunMetricsScrape ()
Callback to update transient metrics.
Protected Member Functions
WatchdogBase (IChatManager chat, ISessionControllerFactory sessionControllerFactory, IDmbFactory dmbFactory, ISessionPersistor sessionPersistor, IJobManager jobManager, IServerControl serverControl, IAsyncDelayer asyncDelayer, IIOManager diagnosticsIOManager, IEventConsumer eventConsumer, IRemoteDeploymentManagerFactory remoteDeploymentManagerFactory, IMetricFactory metricFactory, IIOManager gameIOManager, ILogger< WatchdogBase > logger, DreamDaemonLaunchParameters initialLaunchParameters, Api.Models.Instance metadata, bool autoStart)
Initializes a new instance of the WatchdogBase class.
ValueTask InitController (ValueTask eventTask, ReattachInformation? reattachInfo, CancellationToken cancellationToken)
Starts all ISessionControllers.
async ValueTask LaunchNoLock (bool startMonitor, bool announce, bool announceFailure, ReattachInformation? reattachInfo, CancellationToken cancellationToken)
Launches the watchdog.
async ValueTask< bool > StopMonitor ()
Stops MonitorLifetimes(CancellationToken). Doesn't kill the servers.
async ValueTask CheckLaunchResult (ISessionController controller, string serverName, CancellationToken cancellationToken)
Check the LaunchResult of a given controller for errors and throw a JobException if any are detected.
async ValueTask ReattachFailure (CancellationToken cancellationToken)
Call from InitController(ValueTask, ReattachInformation, CancellationToken) when a reattach operation fails to attempt a fresh start.
ValueTask DisposeAndNullControllersImpl ()
Call IDisposable.Dispose and null the fields for all ISessionControllers.
async ValueTask DisposeAndNullControllers (CancellationToken cancellationToken)
Wrapper for DisposeAndNullControllersImpl under a locked context.
ISessionController? GetActiveController ()
Get the active ISessionController.
ValueTask< MonitorAction > HandleMonitorWakeup (MonitorActivationReason activationReason, CancellationToken cancellationToken)
Handles the actions to take when the monitor has to "wake up".
async ValueTask BeforeApplyDmb (Models.CompileJob newCompileJob, CancellationToken cancellationToken)
To be called before a given newCompileJob goes live.
async ValueTask HandleEventImpl (EventType eventType, IEnumerable< string > parameters, bool relayToSession, CancellationToken cancellationToken)
Handle a given eventType without re-throwing errors.
Properties
long? SessionId [get]
An incrementing ID for representing current server execution.
long? WorldIteration [get]
A incrementing ID for representing current iteration of servers world (i.e. after calling /world/proc/Reboot). Only unique within the current SessionId. Only tracked in game sessions with the DMAPI enabled.
uint? ClientCount [get, private set]
Last known client count queried from the DMAPI. Requires health checks to be enabled to populate.
DateTimeOffset? LaunchTime [get]
When the current server executions was started.
WatchdogStatus Status [get, protected set]
The current WatchdogStatus.
long? MemoryUsage [get]
Gets the memory usage of the game server in bytes.
bool AlphaIsActive [get]
If the alpha server is the active server.
DreamDaemonLaunchParameters ActiveLaunchParameters [get, protected set]
The DreamDaemonLaunchParameters to be applied.
DreamDaemonLaunchParameters? LastLaunchParameters [get, protected set]
The DreamDaemonLaunchParameters the active server is using.This may not be the exact same as ActiveLaunchParameters but still be associated with the same session.
Models.? CompileJob ActiveCompileJob [get]
Retrieves the Models.CompileJob currently running on the server.
RebootState? RebootState [get]
The Session.RebootState of the active server.
ISessionPersistor SessionPersistor [get]
The ISessionPersistor for the WatchdogBase.
ILogger< WatchdogBase > Logger [get]
The ILogger for the WatchdogBase.
IChatManager Chat [get]
The IChatManager for the WatchdogBase.
ISessionControllerFactory SessionControllerFactory [get]
The ISessionControllerFactory for the WatchdogBase.
IDmbFactory DmbFactory [get]
The IDmbFactory for the WatchdogBase.
IAsyncDelayer AsyncDelayer [get]
The IAsyncDelayer for the WatchdogBase.
IIOManager GameIOManager [get]
The IIOManager for the WatchdogBase pointing to the Game directory.
Properties inherited from Tgstation.Server.Host.Components.Watchdog.IWatchdog
Private Member Functions
async ValueTask IEventConsumer. HandleEvent (EventType eventType, IEnumerable< string?> parameters, bool sensitiveParameters, bool deploymentPipeline, CancellationToken cancellationToken)
Handle a given eventType .
Parameters
eventType The EventType.
parameters An IEnumerable<T> of string parameters for eventType .
sensitiveParameters If parameters are considered sensitive and should not be logged.
deploymentPipeline If this event is part of the deployment pipeline.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
ValueTask? IEventConsumer. HandleCustomEvent (string eventName, IEnumerable< string?> parameters, CancellationToken cancellationToken)
Handles a given custom event.
Parameters
eventName The name of the event.
parameters An IEnumerable<T> of string parameters for the event.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation if the event was triggered successfully, null if it matched a TGS event and wasn't executed.
async ValueTask MonitorRestart (CancellationToken cancellationToken)
Attempt to restart the monitor from scratch.
async Task InitialCheckDmbUpdated (CompileJob currentCompileJob)
Check for a new IDmbProvider.
async Task MonitorLifetimes (CancellationToken cancellationToken)
The main loop of the watchdog. Ayschronously waits for events to occur and then responds to them.
async ValueTask TerminateNoLock (bool graceful, bool announce, CancellationToken cancellationToken)
Implementation of Terminate(bool, CancellationToken). Does not lock synchronizationSemaphore.
async ValueTask< MonitorAction > HandleHealthCheck (CancellationToken cancellationToken)
Handles a watchdog health check.
void HandleChatResponses (TopicResponse? result)
Handle any TopicResponse.ChatResponses in a given topic result .
async ValueTask CreateDumpNoLock (CancellationToken cancellationToken)
Attempt to create a process dump for the game server. Requires a lock on synchronizationSemaphore.
Private Attributes
readonly Api.Models.Instance metadata
The Api.Models.Instance for the WatchdogBase.
readonly SemaphoreSlim synchronizationSemaphore
The SemaphoreSlim for the WatchdogBase.
readonly SemaphoreSlim controllerDisposeSemaphore
SemaphoreSlim used for DisposeAndNullControllers.
readonly Gauge watchdogStatusMetric
The Status as a metric.
readonly Gauge cpuUsageMetric
Active session CPU usage as a metric.
readonly Gauge ramUsageMetric
MemoryUsage as a metric.
readonly IEventConsumer eventConsumer
The IEventConsumer that is not the WatchdogBase.
readonly IJobManager jobManager
The IJobManager for the WatchdogBase.
readonly IRestartRegistration restartRegistration
The IRestartRegistration for the WatchdogBase.
readonly IIOManager diagnosticsIOManager
The IIOManager pointing to the Diagnostics directory.
readonly IRemoteDeploymentManagerFactory remoteDeploymentManagerFactory
The IRemoteDeploymentManagerFactory for the WatchdogBase.
readonly bool autoStart
If the WatchdogBase should LaunchNoLock(bool, bool, bool, ReattachInformation, CancellationToken) in StartAsync(CancellationToken).
volatile TaskCompletionSource activeParametersUpdated
TaskCompletionSource that completes when ActiveLaunchParameters are changed and we are running.
CancellationTokenSource? monitorCts
The CancellationTokenSource for the monitor loop.
Task? monitorTask
The Task running the monitor loop.
WatchdogStatus status
Backing field for Status.
int healthChecksMissed
The number of hearbeats missed.
bool releaseServers
If the servers should be released instead of shutdown.
bool disposed
If the WatchdogBase has been DisposeAsync'd.
Detailed Description
Base class for IWatchdogs.
Definition at line 37 of file WatchdogBase.cs.
Constructor & Destructor Documentation
WatchdogBase()
Tgstation.Server.Host.Components.Watchdog.WatchdogBase.WatchdogBase (IChatManager chat, ISessionControllerFactory sessionControllerFactory, IDmbFactory dmbFactory, ISessionPersistor sessionPersistor, IJobManager jobManager, IServerControl serverControl, IAsyncDelayer asyncDelayer, IIOManager diagnosticsIOManager, IEventConsumer eventConsumer, IRemoteDeploymentManagerFactory remoteDeploymentManagerFactory, IMetricFactory metricFactory, IIOManager gameIOManager, ILogger< WatchdogBase > logger, DreamDaemonLaunchParameters initialLaunchParameters, Api::Models::Instance metadata, bool autoStart) protected
Initializes a new instance of the WatchdogBase class.
Parameters
chat The value of Chat.
sessionControllerFactory The value of SessionControllerFactory.
dmbFactory The value of DmbFactory.
sessionPersistor The value of SessionPersistor.
jobManager The value of jobManager.
serverControl The IServerControl to populate restartRegistration with.
asyncDelayer The value of AsyncDelayer.
diagnosticsIOManager The value of diagnosticsIOManager.
eventConsumer The value of EventConsumer.
remoteDeploymentManagerFactory The value of remoteDeploymentManagerFactory.
metricFactory The IMetricFactory used to create metrics.
gameIOManager The value of GameIOManager.
logger The value of Logger.
initialLaunchParameters The initial value of ActiveLaunchParameters. May be modified.
metadata The value of metadata.
autoStart The value of autoStart.
Definition at line 230 of file WatchdogBase.cs.
        {
            Chat = chat ?? throw new ArgumentNullException(nameof(chat));
            SessionControllerFactory = sessionControllerFactory ?? throw new ArgumentNullException(nameof(sessionControllerFactory));
            DmbFactory = dmbFactory ?? throw new ArgumentNullException(nameof(dmbFactory));
            SessionPersistor = sessionPersistor ?? throw new ArgumentNullException(nameof(sessionPersistor));
            this.jobManager = jobManager ?? throw new ArgumentNullException(nameof(jobManager));
            AsyncDelayer = asyncDelayer ?? throw new ArgumentNullException(nameof(asyncDelayer));
            this.diagnosticsIOManager = diagnosticsIOManager ?? throw new ArgumentNullException(nameof(diagnosticsIOManager));
            this.eventConsumer = eventConsumer ?? throw new ArgumentNullException(nameof(eventConsumer));
            this.remoteDeploymentManagerFactory = remoteDeploymentManagerFactory ?? throw new ArgumentNullException(nameof(remoteDeploymentManagerFactory));
            ArgumentNullException.ThrowIfNull(metricFactory);
            GameIOManager = gameIOManager ?? throw new ArgumentNullException(nameof(gameIOManager));
            Logger = logger ?? throw new ArgumentNullException(nameof(logger));
            ActiveLaunchParameters = initialLaunchParameters ?? throw new ArgumentNullException(nameof(initialLaunchParameters));
            this.metadata = metadata ?? throw new ArgumentNullException(nameof(metadata));
            this.autoStart = autoStart;
            ArgumentNullException.ThrowIfNull(serverControl);
            watchdogStatusMetric = metricFactory.CreateGauge(
                "tgs_watchdog_status",
                $"TGS Watchdog status: {(int)WatchdogStatus.Offline} = Offline, {(int)WatchdogStatus.Online} = Online, {(int)WatchdogStatus.Restoring} = Restoring, {(int)WatchdogStatus.DelayedRestart} = Delayed Restart");
            cpuUsageMetric = metricFactory.CreateGauge("tgs_game_cpu_usage", "Estimated total CPU usage time for the game process from 0-1");
            ramUsageMetric = metricFactory.CreateGauge("tgs_game_ram_usage", "Total used bytes of private memory for the game process");
            chat.RegisterCommandHandler(this);
            ActiveLaunchParameters = initialLaunchParameters;
            releaseServers = false;
            activeParametersUpdated = new TaskCompletionSource();
            restartRegistration = serverControl.RegisterForRestart(this);
            try
            {
                synchronizationSemaphore = new SemaphoreSlim(1);
                controllerDisposeSemaphore = new SemaphoreSlim(1);
            }
            catch
            {
                restartRegistration.Dispose();
                synchronizationSemaphore?.Dispose();
                throw;
            }
            Logger.LogTrace("Created watchdog");
        }
References Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ActiveLaunchParameters, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.activeParametersUpdated, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.autoStart, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Chat, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.controllerDisposeSemaphore, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.cpuUsageMetric, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.diagnosticsIOManager, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.eventConsumer, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.GameIOManager, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.jobManager, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Logger, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.metadata, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ramUsageMetric, Tgstation.Server.Host.Components.Chat.IChatManager.RegisterCommandHandler(), Tgstation.Server.Host.Core.IServerControl.RegisterForRestart(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.releaseServers, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.remoteDeploymentManagerFactory, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.restartRegistration, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.synchronizationSemaphore, and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.watchdogStatusMetric.
Member Function Documentation
BeforeApplyDmb()
async ValueTask Tgstation.Server.Host.Components.Watchdog.WatchdogBase.BeforeApplyDmb (Models::CompileJob newCompileJob, CancellationToken cancellationToken) protected
To be called before a given newCompileJob goes live.
Parameters
newCompileJob The new Models.CompileJob being applied.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Definition at line 770 of file WatchdogBase.cs.
        {
            if (newCompileJob.Id == ActiveCompileJob?.Id)
            {
                Logger.LogTrace("Same compile job, not sending deployment event");
                return;
            }
            var remoteDeploymentManager = remoteDeploymentManagerFactory.CreateRemoteDeploymentManager(
                metadata,
                newCompileJob);
            var eventTask = eventConsumer.HandleEvent(
                EventType.DeploymentActivation,
                new List<string?>
                {
                    GameIOManager.ResolvePath(newCompileJob.DirectoryName!.Value.ToString()),
                },
                false,
                false,
                cancellationToken);
            try
            {
                await remoteDeploymentManager.ApplyDeployment(newCompileJob, cancellationToken);
            }
            catch (Exception ex)
            {
                Logger.LogWarning(ex, "Failed to apply remote deployment!");
            }
            await eventTask;
        }
References Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ActiveCompileJob, Tgstation.Server.Host.Components.Deployment.Remote.IRemoteDeploymentManagerFactory.CreateRemoteDeploymentManager(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.eventConsumer, Tgstation.Server.Host.Components.Events.IEventConsumer.HandleEvent(), Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Logger, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.metadata, and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.remoteDeploymentManagerFactory.
Referenced by Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.HandleNormalReboot(), and Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.InitController().
Broadcast()
async ValueTask< bool > Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Broadcast (string message, CancellationToken cancellationToken)
Send a broadcast message to the DMAPI.
Parameters
message The message to broadcast.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in true if the broadcast succeeded., false otherwise.
Implements Tgstation.Server.Host.Components.Watchdog.IWatchdog.
Definition at line 498 of file WatchdogBase.cs.
        {
            ArgumentNullException.ThrowIfNull(message);
            var activeServer = GetActiveController();
            if (activeServer == null)
            {
                Logger.LogInformation("Attempted broadcast failed, no active server!");
                return false;
            }
            if (!activeServer.DMApiAvailable)
            {
                Logger.LogInformation("Attempted broadcast failed, no DMAPI!");
                return false;
            }
            var minimumRequiredVersion = new Version(5, 7, 0);
            if (activeServer.DMApiVersion < minimumRequiredVersion)
            {
                Logger.LogInformation(
                    "Attempted broadcast failed, insufficient interop version: {interopVersion}. Requires {minimumRequiredVersion}!",
                    activeServer.DMApiVersion,
                    minimumRequiredVersion);
                return false;
            }
            Logger.LogInformation("Broadcasting: {message}", message);
            var response = await activeServer.SendCommand(
                TopicParameters.CreateBroadcastParameters(message),
                cancellationToken);
            return response != null && response.ErrorMessage == null;
        }
References Tgstation.Server.Host.Components.Interop.Topic.TopicParameters.CreateBroadcastParameters(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.GetActiveController(), Tgstation.Server.Api.Rights.List, and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Logger.
ChangeSettings()
async ValueTask< bool > Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ChangeSettings (DreamDaemonLaunchParameters launchParameters, CancellationToken cancellationToken)
Changes the ActiveLaunchParameters. If currently running, may trigger a graceful restart.
Parameters
launchParameters The new DreamDaemonLaunchParameters. May be modified.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in true if a reboot is required, false otherwise.
Implements Tgstation.Server.Host.Components.Watchdog.IWatchdog.
Definition at line 309 of file WatchdogBase.cs.
        {
            using (await SemaphoreSlimContext.Lock(synchronizationSemaphore, cancellationToken))
            {
                var currentLaunchParameters = ActiveLaunchParameters;
                ActiveLaunchParameters = launchParameters;
                var currentEngine = GetActiveController()?.EngineVersion.Engine;
                if (!currentEngine.HasValue)
                    return false;
                bool match = launchParameters.CanApplyWithoutReboot(currentLaunchParameters, currentEngine.Value);
                if (match || Status == WatchdogStatus.Offline || Status == WatchdogStatus.DelayedRestart)
                    return false;
                var oldTcs = Interlocked.Exchange(ref activeParametersUpdated, new TaskCompletionSource());
                oldTcs.SetResult();
            }
            return true;
        }
References Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ActiveLaunchParameters, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.activeParametersUpdated, Tgstation.Server.Api.Models.EngineVersion.Engine, Tgstation.Server.Host.Components.Session.ISessionController.EngineVersion, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.GetActiveController(), Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Utils.SemaphoreSlimContext.Lock(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Status, and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.synchronizationSemaphore.
CheckLaunchResult()
async ValueTask Tgstation.Server.Host.Components.Watchdog.WatchdogBase.CheckLaunchResult (ISessionController controller, string serverName, CancellationToken cancellationToken) protected
Check the LaunchResult of a given controller for errors and throw a JobException if any are detected.
Parameters
controller The ISessionController to checkou.
serverName The name of the server being checked.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Definition at line 693 of file WatchdogBase.cs.
        {
            var launchResult = await controller.LaunchResult.WaitAsync(cancellationToken);
            // Dead sessions won't trigger this
            if (launchResult.ExitCode.HasValue) // you killed us ray...
                throw new JobException(
                    ErrorCode.WatchdogStartupFailed,
                    new JobException($"{serverName} failed to start: {launchResult}"));
            if (!launchResult.StartupTime.HasValue)
                throw new JobException(
                    ErrorCode.WatchdogStartupTimeout,
                    new JobException($"{serverName} timed out on startup: {ActiveLaunchParameters.StartupTimeout!.Value}s"));
        }
References Tgstation.Server.Api.Rights.List.
Referenced by Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.InitController().
CreateDump()
async ValueTask Tgstation.Server.Host.Components.Watchdog.WatchdogBase.CreateDump (CancellationToken cancellationToken)
Attempt to create a process dump for DreamDaemon.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Watchdog.IWatchdog.
Definition at line 491 of file WatchdogBase.cs.
        {
            using (await SemaphoreSlimContext.Lock(synchronizationSemaphore, cancellationToken))
                await CreateDumpNoLock(cancellationToken);
        }
References Tgstation.Server.Host.Components.Watchdog.WatchdogBase.CreateDumpNoLock(), Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Utils.SemaphoreSlimContext.Lock(), and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.synchronizationSemaphore.
CreateDumpNoLock()
async ValueTask Tgstation.Server.Host.Components.Watchdog.WatchdogBase.CreateDumpNoLock (CancellationToken cancellationToken) private
Attempt to create a process dump for the game server. Requires a lock on synchronizationSemaphore.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Definition at line 1291 of file WatchdogBase.cs.
        {
            const string DumpDirectory = "ProcessDumps";
            var session = GetActiveController();
            if (session?.Lifetime.IsCompleted != false)
                throw new JobException(ErrorCode.GameServerOffline);
            var dumpFileExtension = session.DumpFileExtension;
            var dumpFileNameTemplate = diagnosticsIOManager.ResolvePath(
                diagnosticsIOManager.ConcatPath(
                    DumpDirectory,
                    $"DreamDaemon-{DateTimeOffset.UtcNow.ToFileStamp()}"));
            var dumpFileName = $"{dumpFileNameTemplate}{dumpFileExtension}";
            var iteration = 0;
            while (await diagnosticsIOManager.FileExists(dumpFileName, cancellationToken))
                dumpFileName = $"{dumpFileNameTemplate} ({++iteration}){dumpFileExtension}";
            if (iteration == 0)
                await diagnosticsIOManager.CreateDirectory(DumpDirectory, cancellationToken);
            if (session.Lifetime.IsCompleted)
                throw new JobException(ErrorCode.GameServerOffline);
            Logger.LogInformation("Dumping session to {dumpFileName}...", dumpFileName);
            await session.CreateDump(dumpFileName, ActiveLaunchParameters.Minidumps!.Value, cancellationToken);
        }
References Tgstation.Server.Api.Rights.List.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.CreateDump(), and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleHealthCheck().
DisposeAndNullControllers()
async ValueTask Tgstation.Server.Host.Components.Watchdog.WatchdogBase.DisposeAndNullControllers (CancellationToken cancellationToken) protected
Wrapper for DisposeAndNullControllersImpl under a locked context.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Definition at line 737 of file WatchdogBase.cs.
        {
            Logger.LogTrace("DisposeAndNullControllers");
            using (await SemaphoreSlimContext.Lock(controllerDisposeSemaphore, cancellationToken))
            {
                await DisposeAndNullControllersImpl();
                if (!releaseServers)
                    await SessionPersistor.Clear(cancellationToken);
            }
        }
References Tgstation.Server.Host.Components.Session.SessionPersistor.Clear(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.controllerDisposeSemaphore, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.DisposeAndNullControllersImpl(), Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Utils.SemaphoreSlimContext.Lock(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Logger, and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.releaseServers.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleHealthCheck(), Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.InitController(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.MonitorLifetimes(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.MonitorRestart(), and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ReattachFailure().
DisposeAndNullControllersImpl()
ValueTask Tgstation.Server.Host.Components.Watchdog.WatchdogBase.DisposeAndNullControllersImpl () abstract protected
Call IDisposable.Dispose and null the fields for all ISessionControllers.
Returns
A ValueTask representing the running operation.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.DisposeAndNullControllers(), and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.DisposeAsync().
DisposeAsync()
async ValueTask Tgstation.Server.Host.Components.Watchdog.WatchdogBase.DisposeAsync ()
Definition at line 295 of file WatchdogBase.cs.
        {
            Logger.LogTrace("Disposing...");
            synchronizationSemaphore.Dispose();
            restartRegistration.Dispose();
            await DisposeAndNullControllersImpl();
            controllerDisposeSemaphore.Dispose();
            monitorCts?.Dispose();
            disposed = true;
        }
References Tgstation.Server.Host.Components.Watchdog.WatchdogBase.controllerDisposeSemaphore, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.DisposeAndNullControllersImpl(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.disposed, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Logger, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.monitorCts, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.restartRegistration, and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.synchronizationSemaphore.
Referenced by Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.AdvancedWatchdog(), and Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.HandleNewDmbAvailable().
GetActiveController()
ISessionController? Tgstation.Server.Host.Components.Watchdog.WatchdogBase.GetActiveController () abstract protected
Get the active ISessionController.
Returns
The active ISessionController, if any.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Broadcast(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ChangeSettings(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleChatCommand(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleEvent(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleHealthCheck(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.MonitorLifetimes(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ResetRebootState(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Restart(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.RunMetricsScrape(), and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.TerminateNoLock().
HandleChatCommand()
async ValueTask< MessageContent > Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleChatCommand (string commandName, string arguments, ChatUser sender, CancellationToken cancellationToken)
Handle a chat command.
Parameters
commandName The command name.
arguments Everything typed after commandName minus leading spaces.
sender The sending ChatUser.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the MessageContent text to send back.
Implements Tgstation.Server.Host.Components.Chat.ICustomCommandHandler.
Definition at line 331 of file WatchdogBase.cs.
        {
            using (await SemaphoreSlimContext.Lock(synchronizationSemaphore, cancellationToken))
            {
                var commandObject = new ChatCommand(sender, commandName, arguments);
                var command = new TopicParameters(commandObject);
                var activeServer = GetActiveController();
                if (Status != WatchdogStatus.Online || activeServer == null)
                    return new MessageContent
                    {
                        Text = "TGS: Server offline!",
                    };
                var commandResult = await activeServer.SendCommand(command, cancellationToken);
                if (commandResult == null)
                    return new MessageContent
                    {
                        Text = "TGS: Bad topic exchange!",
                    };
                if (commandResult == null)
                    return new MessageContent
                    {
                        Text = "TGS: Bad topic response!",
                    };
                var commandResponse = new MessageContent
                {
                    Text = commandResult.CommandResponse?.Text ?? commandResult.CommandResponseMessage,
                    Embed = commandResult.CommandResponse?.Embed,
                };
                if (commandResponse.Text == null && commandResponse.Embed == null)
                {
                    commandResponse.Text = "TGS: Command processed but no DMAPI response returned!";
                }
                HandleChatResponses(commandResult);
                return commandResponse;
            }
        }
References Tgstation.Server.Host.Components.Watchdog.WatchdogBase.GetActiveController(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleChatResponses(), Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Utils.SemaphoreSlimContext.Lock(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Status, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.synchronizationSemaphore, and Tgstation.Server.Host.Components.Interop.MessageContent.Text.
HandleChatResponses()
void Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleChatResponses (TopicResponse? result) private
Handle any TopicResponse.ChatResponses in a given topic result .
Parameters
result The TopicResponse.
Definition at line 1248 of file WatchdogBase.cs.
        {
            if (result?.ChatResponses != null)
            {
                var warnedMissingChannelIds = false;
                foreach (var response in result.ChatResponses
                    .Where(response =>
                    {
                        if (response.ChannelIds == null)
{
                            if (!warnedMissingChannelIds)
{
                                Logger.LogWarning("DMAPI response contains null channelIds!");
                                warnedMissingChannelIds = true;
                            }
                            return false;
                        }
                        return true;
                    }))
                    Chat.QueueMessage(
                        response,
                        response.ChannelIds!
                            .Select(channelIdString =>
{
                                if (UInt64.TryParse(channelIdString, out var channelId))
                                    return (ulong?)channelId;
                                else
                                    Logger.LogWarning("Could not parse chat response channel ID: {channelID}", channelIdString);
                                return null;
                            })
                            .Where(nullableChannelId => nullableChannelId.HasValue)
                            .Select(nullableChannelId => nullableChannelId!.Value));
            }
        }
References Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Chat, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Logger, and Tgstation.Server.Host.Components.Chat.IChatManager.QueueMessage().
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleChatCommand(), and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleEvent().
HandleCustomEvent()
ValueTask? IEventConsumer. Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleCustomEvent (string eventName, IEnumerable< string?> parameters, CancellationToken cancellationToken) private
Handles a given custom event.
Parameters
eventName The name of the event.
parameters An IEnumerable<T> of string parameters for the event.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation if the event was triggered successfully, null if it matched a TGS event and wasn't executed.
Implements Tgstation.Server.Host.Components.Events.IEventConsumer.
HandleEvent()
async ValueTask IEventConsumer. Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleEvent (EventType eventType, IEnumerable< string?> parameters, bool sensitiveParameters, bool deploymentPipeline, CancellationToken cancellationToken) private
Handle a given eventType .
Parameters
eventType The EventType.
parameters An IEnumerable<T> of string parameters for eventType .
sensitiveParameters If parameters are considered sensitive and should not be logged.
deploymentPipeline If this event is part of the deployment pipeline.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Events.IEventConsumer.
Definition at line 544 of file WatchdogBase.cs.
        {
            ArgumentNullException.ThrowIfNull(parameters);
            if (sensitiveParameters)
            {
                Logger.LogDebug("Not sending sensitive event parameters");
                parameters = Enumerable.Empty<string>();
            }
            // Method explicitly implemented to prevent accidental calls when this.eventConsumer should be used.
            var activeServer = GetActiveController();
            // Server may have ended
            if (activeServer == null)
                return;
            var notification = new EventNotification(eventType, parameters);
            var result = await activeServer.SendCommand(
                new TopicParameters(notification),
                cancellationToken);
            HandleChatResponses(result);
        }
References Tgstation.Server.Host.Components.Watchdog.WatchdogBase.GetActiveController(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleChatResponses(), Tgstation.Server.Api.Rights.List, and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Logger.
HandleEventImpl()
async ValueTask Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleEventImpl (EventType eventType, IEnumerable< string > parameters, bool relayToSession, CancellationToken cancellationToken) protected
Handle a given eventType without re-throwing errors.
Parameters
eventType The EventType.
parameters An IEnumerable<T> of string parameters for eventType .
relayToSession If the event should be sent to DreamDaemon.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Definition at line 812 of file WatchdogBase.cs.
        {
            try
            {
                var sessionEventTask = relayToSession ? ((IEventConsumer)this).HandleEvent(eventType, parameters, false, false, cancellationToken) : ValueTask.CompletedTask;
                var eventConsumerTask = eventConsumer.HandleEvent(eventType, parameters, false, false, cancellationToken);
                await ValueTaskExtensions.WhenAll(
                    eventConsumerTask,
                    sessionEventTask);
            }
            catch (JobException ex)
            {
                Logger.LogError(ex, "Suppressing exception triggered by event!");
            }
        }
References Tgstation.Server.Host.Components.Watchdog.WatchdogBase.eventConsumer, Tgstation.Server.Host.Components.Events.IEventConsumer.HandleEvent(), Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Logger, and Tgstation.Server.Common.Extensions.ValueTaskExtensions.WhenAll().
Referenced by Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.HandleMonitorWakeup(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.LaunchNoLock(), and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.TerminateNoLock().
HandleHealthCheck()
async ValueTask< MonitorAction > Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleHealthCheck (CancellationToken cancellationToken) private
Handles a watchdog health check.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the next MonitorAction to take.
Definition at line 1163 of file WatchdogBase.cs.
        {
            Logger.LogTrace("Sending health check to active server...");
            var activeServer = GetActiveController();
            if (activeServer == null)
                return MonitorAction.Restart; // uhhhh???
            var response = await activeServer.SendCommand(new TopicParameters(), cancellationToken);
            var shouldShutdown = activeServer.RebootState == Session.RebootState.Shutdown;
            if (response == null)
            {
                switch (++healthChecksMissed)
                {
                    case 1:
                        Logger.LogDebug("DEFCON 4: Game server missed first health check!");
                        break;
                    case 2:
                        const string message2 = "DEFCON 3: Game server has missed 2 health checks!";
                        Logger.LogInformation(message2);
                        Chat.QueueWatchdogMessage(message2);
                        break;
                    case 3:
                        var actionToTake = shouldShutdown
                            ? "shutdown"
                            : "be restarted";
                        const string logTemplate1 = "DEFCON 2: Game server has missed 3 health checks! If it does not respond to the next one, the watchdog will {actionToTake}!";
                        Logger.LogWarning(logTemplate1, actionToTake);
                        Chat.QueueWatchdogMessage(
                            logTemplate1.Replace(
                                "{actionToTake}",
                                actionToTake,
                                StringComparison.Ordinal));
                        break;
                    case 4:
                        var actionTaken = shouldShutdown
                            ? "Shutting down due to graceful termination request"
                            : "Restarting";
                        const string logTemplate2 = "DEFCON 1: Four health checks have been missed! {actionTaken}...";
                        Logger.LogWarning(logTemplate2, actionTaken);
                        Chat.QueueWatchdogMessage(
                            logTemplate2.Replace(
                                "{actionTaken}",
                                actionTaken,
                                StringComparison.Ordinal));
                        if (ActiveLaunchParameters.DumpOnHealthCheckRestart!.Value)
{
                            Logger.LogDebug("DumpOnHealthCheckRestart enabled.");
                            try
{
                                await CreateDumpNoLock(cancellationToken);
                            }
                            catch (JobException ex)
{
                                Logger.LogWarning(ex, "Creating dump failed!");
                            }
                            catch (Win32Exception ex)
{
                                Logger.LogWarning(ex, "Creating dump failed!");
                            }
                        }
                        else
                            Logger.LogTrace("DumpOnHealthCheckRestart disabled.");
                        await DisposeAndNullControllers(cancellationToken);
                        return shouldShutdown ? MonitorAction.Exit : MonitorAction.Restart;
                    default:
                        Logger.LogError("Invalid health checks missed count: {healthChecksMissed}", healthChecksMissed);
                        break;
                }
            }
            else
            {
                healthChecksMissed = 0;
                ClientCount = response.ClientCount;
            }
            return MonitorAction.Continue;
        }
References Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ActiveLaunchParameters, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Chat, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ClientCount, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.CreateDumpNoLock(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.DisposeAndNullControllers(), Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.DumpOnHealthCheckRestart, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.GetActiveController(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.healthChecksMissed, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Logger, and Tgstation.Server.Host.Components.Chat.IChatManager.QueueWatchdogMessage().
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.MonitorLifetimes().
HandleMonitorWakeup()
ValueTask< MonitorAction > Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleMonitorWakeup (MonitorActivationReason activationReason, CancellationToken cancellationToken) abstract protected
Handles the actions to take when the monitor has to "wake up".
Parameters
activationReason The MonitorActivationReason that caused the invocation. Will never be MonitorActivationReason.HealthCheck.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the MonitorAction to take.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.MonitorLifetimes().
HandleRestart()
async ValueTask Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleRestart (Version? updateVersion, bool handlerMayDelayShutdownWithExtremelyLongRunningTasks, CancellationToken cancellationToken)
Handle a restart of the server.
Parameters
updateVersion The Version being updated to, null if not being changed.
handlerMayDelayShutdownWithExtremelyLongRunningTasks If false the IRestartHandler should aim to complete the Task returned from this function ASAP.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Core.IRestartHandler.
Definition at line 463 of file WatchdogBase.cs.
        {
            if (handlerMayDelayShutdownWithExtremelyLongRunningTasks)
            {
                await Terminate(true, cancellationToken);
                if (Status != WatchdogStatus.Offline)
                {
                    Logger.LogDebug("Waiting for server to gracefully shut down.");
                    await monitorTask!.WaitAsync(cancellationToken);
                }
                else
                    Logger.LogTrace("Graceful shutdown requested but server is already offline.");
                return;
            }
            releaseServers = true;
            if (Status == WatchdogStatus.Online)
                Chat.QueueWatchdogMessage("Detaching...");
            else
                Logger.LogTrace("Not sending detach chat message as status is: {status}", Status);
        }
References Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Chat, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Logger, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.monitorTask, Tgstation.Server.Host.Components.Chat.IChatManager.QueueWatchdogMessage(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.releaseServers, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Status, and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Terminate().
InitController()
ValueTask Tgstation.Server.Host.Components.Watchdog.WatchdogBase.InitController (ValueTask eventTask, ReattachInformation? reattachInfo, CancellationToken cancellationToken) abstract protected
Starts all ISessionControllers.
Parameters
eventTask A, possibly active, Task for an event that's running.
reattachInfo ReattachInformation to use, if any.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.LaunchNoLock(), and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ReattachFailure().
InitialCheckDmbUpdated()
async Task Tgstation.Server.Host.Components.Watchdog.WatchdogBase.InitialCheckDmbUpdated (CompileJob currentCompileJob) private
Check for a new IDmbProvider.
Parameters
currentCompileJob The session's current CompileJob.
Returns
A Task that completes if and when a newer CompileJob is available.
Definition at line 879 of file WatchdogBase.cs.
        {
            var factoryTask = DmbFactory.OnNewerDmb;
            var latestCompileJob = await DmbFactory.LatestCompileJob();
            if (latestCompileJob != null && latestCompileJob.Id != currentCompileJob.Id)
            {
                Logger.LogDebug("Found new CompileJob without waiting");
                return;
            }
            await factoryTask;
        }
References Tgstation.Server.Host.Components.Deployment.DmbFactory.LatestCompileJob(), Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Logger, and Tgstation.Server.Host.Components.Deployment.DmbFactory.OnNewerDmb.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.MonitorLifetimes().
InstanceRenamed()
ValueTask Tgstation.Server.Host.Components.Watchdog.WatchdogBase.InstanceRenamed (string newInstanceName, CancellationToken cancellationToken) abstract
Called when the owning Instance is renamed.
Parameters
newInstanceName The new Api.Models.NamedEntity.Name.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.IRenameNotifyee.
Launch()
async ValueTask Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Launch (CancellationToken cancellationToken)
Start the IWatchdog.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Watchdog.IWatchdog.
Definition at line 376 of file WatchdogBase.cs.
        {
            if (Status != WatchdogStatus.Offline)
                throw new JobException(ErrorCode.WatchdogRunning);
            using (await SemaphoreSlimContext.Lock(synchronizationSemaphore, cancellationToken))
                await LaunchNoLock(true, true, true, null, cancellationToken);
        }
References Tgstation.Server.Host.Components.Watchdog.WatchdogBase.LaunchNoLock(), Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Utils.SemaphoreSlimContext.Lock(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Status, and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.synchronizationSemaphore.
LaunchNoLock()
async ValueTask Tgstation.Server.Host.Components.Watchdog.WatchdogBase.LaunchNoLock (bool startMonitor, bool announce, bool announceFailure, ReattachInformation? reattachInfo, CancellationToken cancellationToken) protected
Launches the watchdog.
Parameters
startMonitor If MonitorLifetimes(CancellationToken) should be started by this function.
announce If the launch should be announced to chat by this function.
announceFailure If launch failure should be announced to chat by this function.
reattachInfo ReattachInformation to use, if any.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Definition at line 591 of file WatchdogBase.cs.
        {
            Logger.LogTrace("Begin LaunchImplNoLock");
            if (startMonitor && Status != WatchdogStatus.Offline)
                throw new JobException(ErrorCode.WatchdogRunning);
            if (reattachInfo == null && !DmbFactory.DmbAvailable)
                throw new JobException(ErrorCode.WatchdogCompileJobCorrupted);
            // this is necessary, the monitor could be in it's sleep loop trying to restart, if so cancel THAT monitor and start our own with blackjack and hookers
            var eventTask = ValueTask.CompletedTask;
            if (announce)
            {
                Chat.QueueWatchdogMessage(
                    reattachInfo == null
                        ? "Launching..."
                        : "Reattaching..."); // simple announce
                if (reattachInfo == null)
                    eventTask = HandleEventImpl(EventType.WatchdogLaunch, Enumerable.Empty<string>(), false, cancellationToken);
            }
            // since neither server is running, this is safe to do
            LastLaunchParameters = ActiveLaunchParameters;
            healthChecksMissed = 0;
            ClientCount = null;
            try
            {
                await InitController(eventTask, reattachInfo, cancellationToken);
            }
            catch (OperationCanceledException ex)
            {
                Logger.LogTrace(ex, "Controller initialization cancelled!");
                throw;
            }
            catch (Exception e)
            {
                Logger.LogWarning(e, "Failed to start watchdog!");
                var originalChatTask = eventTask;
                async ValueTask ChainEventTaskWithErrorMessage()
                {
                    await originalChatTask;
                    if (announceFailure)
                        Chat.QueueWatchdogMessage("Startup failed!");
                }
                eventTask = ChainEventTaskWithErrorMessage();
                throw;
            }
            finally
            {
                // finish the chat task that's in flight
                try
                {
                    await eventTask;
                }
                catch (OperationCanceledException ex)
                {
                    Logger.LogTrace(ex, "Announcement task canceled!");
                }
            }
            Logger.LogInformation("Controller(s) initialized successfully");
            if (startMonitor)
            {
                monitorCts = new CancellationTokenSource();
                monitorTask = MonitorLifetimes(monitorCts.Token);
            }
        }
References Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ActiveLaunchParameters, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Chat, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ClientCount, Tgstation.Server.Host.Components.Deployment.DmbFactory.DmbAvailable, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleEventImpl(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.healthChecksMissed, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.InitController(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.LastLaunchParameters, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Logger, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.monitorCts, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.MonitorLifetimes(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.monitorTask, Tgstation.Server.Host.Components.Chat.IChatManager.QueueWatchdogMessage(), and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Status.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Launch(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.MonitorRestart(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Restart(), and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.StartAsync().
MonitorLifetimes()
async Task Tgstation.Server.Host.Components.Watchdog.WatchdogBase.MonitorLifetimes (CancellationToken cancellationToken) private
The main loop of the watchdog. Ayschronously waits for events to occur and then responds to them.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Definition at line 899 of file WatchdogBase.cs.
        {
            Logger.LogTrace("Entered MonitorLifetimes");
            Status = WatchdogStatus.Online;
            using var cancellationTokenLoggingRegistration = cancellationToken.Register(() => Logger.LogTrace("Monitor cancellationToken triggered"));
            // this function is responsible for calling HandlerMonitorWakeup when necessary and manitaining the MonitorState
            try
            {
                MonitorAction nextAction = MonitorAction.Continue;
                Task? activeServerLifetime = null,
                    activeServerReboot = null,
                    activeServerStartup = null,
                    serverPrimed = null,
                    activeLaunchParametersChanged = null,
                    newDmbAvailable = null,
                    healthCheck = null;
                ISessionController? lastController = null;
                var ranInitialDmbCheck = false;
                for (ulong iteration = 1; nextAction != MonitorAction.Exit; ++iteration)
                    using (LogContext.PushProperty(SerilogContextHelper.WatchdogMonitorIterationContextProperty, iteration))
                    {
                        var nextMonitorWakeupTcs = new TaskCompletionSource();
                        try
{
                            Logger.LogTrace("Iteration {iteration} of monitor loop", iteration);
                            nextAction = MonitorAction.Continue;
                            var controller = GetActiveController();
                            void UpdateMonitoredTasks()
{
                                var sameController = lastController == controller;
                                void TryUpdateTask(ref Task? oldTask, Func<Task> newTaskFactory)
{
                                    if (sameController && oldTask?.IsCompleted == true)
                                        return;
                                    oldTask = newTaskFactory();
                                }
                                controller!.RebootGate = nextMonitorWakeupTcs.Task;
                                TryUpdateTask(ref activeServerLifetime, () => controller.Lifetime);
                                TryUpdateTask(ref activeServerReboot, () => controller.OnReboot);
                                TryUpdateTask(ref serverPrimed, () => controller.OnPrime);
                                TryUpdateTask(ref activeServerStartup, () => controller.OnStartup);
                                if (!sameController)
                                    lastController = controller;
                                TryUpdateTask(ref activeLaunchParametersChanged, () => activeParametersUpdated.Task);
                                TryUpdateTask(
                                    ref newDmbAvailable,
                                    () =>
{
                                        var result = ranInitialDmbCheck
                                            ? DmbFactory.OnNewerDmb
                                            : InitialCheckDmbUpdated(controller.CompileJob);
                                        ranInitialDmbCheck = true;
                                        return result;
                                    });
                            }
                            if (controller != null)
{
                                UpdateMonitoredTasks();
                                var healthCheckSeconds = ActiveLaunchParameters.HealthCheckSeconds!.Value;
                                healthCheck = healthCheckSeconds == 0
                                    || !controller.DMApiAvailable
                                    ? Extensions.TaskExtensions.InfiniteTask
                                    : Task.Delay(
                                        TimeSpan.FromSeconds(healthCheckSeconds),
                                        cancellationToken);
                                // cancel waiting if requested
                                var toWaitOn = Task.WhenAny(
                                    activeServerLifetime!,
                                    activeServerReboot!,
                                    activeServerStartup!,
                                    healthCheck,
                                    newDmbAvailable!,
                                    activeLaunchParametersChanged!,
                                    serverPrimed!);
                                // wait for something to happen
                                await toWaitOn.WaitAsync(cancellationToken);
                            }
                            else
{
                                Logger.LogError("Controller was null on monitor wakeup! Attempting restart...");
                                nextAction = MonitorAction.Restart; // excuse me wtf?
                            }
                            cancellationToken.ThrowIfCancellationRequested();
                            Logger.LogTrace("Monitor activated");
                            // always run HandleMonitorWakeup from the context of the semaphore lock
                            using (await SemaphoreSlimContext.Lock(synchronizationSemaphore, cancellationToken))
{
                                // Set this sooner so chat sends don't hold us up
                                if (activeServerLifetime!.IsCompleted)
                                    Status = WatchdogStatus.Restoring;
                                // multiple things may have happened, handle them one at a time
                                for (var moreActivationsToProcess = true; moreActivationsToProcess && (nextAction == MonitorAction.Continue || nextAction == MonitorAction.Skip);)
{
                                    MonitorActivationReason activationReason = default; // this will always be assigned before being used
                                    bool CheckActivationReason(ref Task? task, MonitorActivationReason testActivationReason)
{
                                        var taskCompleted = task?.IsCompleted == true;
                                        task = null;
                                        if (nextAction == MonitorAction.Skip)
                                            nextAction = MonitorAction.Continue;
                                        else if (taskCompleted)
{
                                            activationReason = testActivationReason;
                                            return true;
                                        }
                                        return false;
                                    }
                                    // process the tasks in this order and call HandlerMonitorWakup for each depending on the new monitorState
                                    var anyActivation = CheckActivationReason(ref activeServerLifetime, MonitorActivationReason.ActiveServerCrashed)
                                        || CheckActivationReason(ref activeServerReboot, MonitorActivationReason.ActiveServerRebooted)
                                        || CheckActivationReason(ref newDmbAvailable, MonitorActivationReason.NewDmbAvailable)
                                        || CheckActivationReason(ref activeLaunchParametersChanged, MonitorActivationReason.ActiveLaunchParametersUpdated)
                                        || CheckActivationReason(ref healthCheck, MonitorActivationReason.HealthCheck)
                                        || CheckActivationReason(ref serverPrimed, MonitorActivationReason.ActiveServerPrimed)
                                        || CheckActivationReason(ref activeServerStartup, MonitorActivationReason.ActiveServerStartup);
                                    UpdateMonitoredTasks();
                                    if (!anyActivation)
                                        moreActivationsToProcess = false;
                                    else
{
                                        Logger.LogTrace("Reason: {activationReason}", activationReason);
                                        if (activationReason == MonitorActivationReason.HealthCheck)
                                            nextAction = await HandleHealthCheck(
                                                cancellationToken);
                                        else
                                            nextAction = await HandleMonitorWakeup(
                                                activationReason,
                                                cancellationToken);
                                    }
                                }
                            }
                            Logger.LogTrace("Next monitor action is to {nextAction}", nextAction);
                            // Restart if requested
                            if (nextAction == MonitorAction.Restart)
{
                                await MonitorRestart(cancellationToken);
                                nextAction = MonitorAction.Continue;
                            }
                        }
                        catch (Exception e) when (e is not OperationCanceledException)
{
                            // really, this should NEVER happen
                            Logger.LogError(
                                e,
                                "Monitor crashed! Iteration: {iteration}",
                                iteration);
                            var nextActionMessage = nextAction != MonitorAction.Exit
                                ? "Recovering"
                                : "Shutting down";
                            Chat.QueueWatchdogMessage(
                                $"Monitor crashed, this should NEVER happen! Please report this, full details in logs! {nextActionMessage}. Error: {e.Message}");
                            if (disposed)
                                nextAction = MonitorAction.Exit;
                            else if (nextAction != MonitorAction.Exit)
{
                                if (GetActiveController()?.Lifetime.IsCompleted != true)
                                    await MonitorRestart(cancellationToken);
                                else
                                    Logger.LogDebug("Server seems to be okay, not restarting");
                                nextAction = MonitorAction.Continue;
                            }
                        }
                        finally
{
                            nextMonitorWakeupTcs.SetResult();
                        }
                    }
            }
            catch (OperationCanceledException)
            {
                // stop signal
                Logger.LogDebug("Monitor cancelled");
                if (releaseServers)
                {
                    Logger.LogTrace("Detaching server...");
                    var controller = GetActiveController();
                    if (controller != null)
                        await controller.Release();
                    else
                        Logger.LogError("Controller was null on monitor shutdown!");
                }
            }
            // DCT: Operation must always run
            await DisposeAndNullControllers(CancellationToken.None);
            Status = WatchdogStatus.Offline;
            Logger.LogTrace("Monitor exiting...");
        }
References Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ActiveLaunchParameters, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.activeParametersUpdated, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Chat, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.DisposeAndNullControllers(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.disposed, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.GetActiveController(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleHealthCheck(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleMonitorWakeup(), Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.HealthCheckSeconds, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.InitialCheckDmbUpdated(), Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Utils.SemaphoreSlimContext.Lock(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Logger, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.MonitorRestart(), Tgstation.Server.Host.Components.Chat.IChatManager.QueueWatchdogMessage(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.releaseServers, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Status, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.synchronizationSemaphore, and Tgstation.Server.Host.Utils.SerilogContextHelper.WatchdogMonitorIterationContextProperty.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.LaunchNoLock().
MonitorRestart()
async ValueTask Tgstation.Server.Host.Components.Watchdog.WatchdogBase.MonitorRestart (CancellationToken cancellationToken) private
Attempt to restart the monitor from scratch.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Definition at line 833 of file WatchdogBase.cs.
        {
            Logger.LogTrace("Monitor restart!");
            await DisposeAndNullControllers(cancellationToken);
            for (var retryAttempts = 1; ; ++retryAttempts)
            {
                Status = WatchdogStatus.Restoring;
                Exception launchException;
                using (await SemaphoreSlimContext.Lock(synchronizationSemaphore, cancellationToken))
                    try
                    {
                        // use LaunchImplNoLock without announcements or restarting the monitor
                        await LaunchNoLock(false, false, false, null, cancellationToken);
                        Status = WatchdogStatus.Online;
                        Logger.LogDebug("Relaunch successful, resuming monitor...");
                        return;
                    }
                    catch (Exception e) when (e is not OperationCanceledException)
                    {
                        launchException = e;
                    }
                Logger.LogWarning(launchException, "Failed to automatically restart the watchdog! Attempt: {attemptNumber}", retryAttempts);
                Status = WatchdogStatus.DelayedRestart;
                var retryDelay = Math.Min(
                    Convert.ToInt32(
                        Math.Pow(2, retryAttempts)),
                    TimeSpan.FromHours(1).TotalSeconds); // max of one hour, increasing by a power of 2 each time
                Chat.QueueWatchdogMessage(
                    $"Failed to restart (Attempt: {retryAttempts}), retrying in {retryDelay}s...");
                await AsyncDelayer.Delay(
                    TimeSpan.FromSeconds(retryDelay),
                    cancellationToken);
            }
        }
References Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Chat, Tgstation.Server.Host.Utils.AsyncDelayer.Delay(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.DisposeAndNullControllers(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.LaunchNoLock(), Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Utils.SemaphoreSlimContext.Lock(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Logger, Tgstation.Server.Host.Components.Chat.IChatManager.QueueWatchdogMessage(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Status, and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.synchronizationSemaphore.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.MonitorLifetimes().
ReattachFailure()
async ValueTask Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ReattachFailure (CancellationToken cancellationToken) protected
Call from InitController(ValueTask, ReattachInformation, CancellationToken) when a reattach operation fails to attempt a fresh start.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Definition at line 713 of file WatchdogBase.cs.
        {
            // we lost the server, just restart entirely
            // DCT: Operation must always run
            await DisposeAndNullControllers(CancellationToken.None);
            ClientCount = null;
            const string FailReattachMessage = "Unable to properly reattach to server! Restarting watchdog...";
            Logger.LogWarning(FailReattachMessage);
            Chat.QueueWatchdogMessage(FailReattachMessage);
            await InitController(ValueTask.CompletedTask, null, cancellationToken);
        }
References Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Chat, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ClientCount, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.DisposeAndNullControllers(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.InitController(), Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Logger, and Tgstation.Server.Host.Components.Chat.IChatManager.QueueWatchdogMessage().
Referenced by Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.InitController().
ResetRebootState()
virtual async ValueTask Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ResetRebootState (CancellationToken cancellationToken) virtual
Cancels pending graceful actions.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Watchdog.IWatchdog.
Reimplemented in Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.
Definition at line 385 of file WatchdogBase.cs.
        {
            using (await SemaphoreSlimContext.Lock(synchronizationSemaphore, cancellationToken))
            {
                if (Status == WatchdogStatus.Offline)
                    return;
                var toClear = GetActiveController();
                if (toClear != null)
                    await toClear.SetRebootState(Session.RebootState.Normal, cancellationToken);
            }
        }
References Tgstation.Server.Host.Components.Watchdog.WatchdogBase.GetActiveController(), Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Utils.SemaphoreSlimContext.Lock(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Status, and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.synchronizationSemaphore.
Restart()
async ValueTask Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Restart (bool graceful, CancellationToken cancellationToken)
Restarts the watchdog.
Parameters
graceful If true the restart will be delayed until a reboot is detected in the active server's DMAPI and this function will retrun immediately.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Watchdog.IWatchdog.
Definition at line 398 of file WatchdogBase.cs.
        {
            if (Status == WatchdogStatus.Offline)
                throw new JobException(ErrorCode.WatchdogNotRunning);
            Logger.LogTrace("Begin Restart. Graceful: {gracefulFlag}", graceful);
            using (await SemaphoreSlimContext.Lock(synchronizationSemaphore, cancellationToken))
            {
                if (!graceful)
                {
                    Chat.QueueWatchdogMessage("Manual restart triggered...");
                    await TerminateNoLock(false, false, cancellationToken);
                    await LaunchNoLock(true, false, true, null, cancellationToken);
                    return;
                }
                var toReboot = GetActiveController();
                if (toReboot != null
                    && !await toReboot.SetRebootState(Session.RebootState.Restart, cancellationToken))
                    Logger.LogWarning("Unable to send reboot state change event!");
            }
        }
References Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Chat, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.GetActiveController(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.LaunchNoLock(), Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Utils.SemaphoreSlimContext.Lock(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Logger, Tgstation.Server.Host.Components.Chat.IChatManager.QueueWatchdogMessage(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Status, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.synchronizationSemaphore, and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.TerminateNoLock().
RunMetricsScrape()
void Tgstation.Server.Host.Components.Watchdog.WatchdogBase.RunMetricsScrape ()
Callback to update transient metrics.
Implements Tgstation.Server.Host.Components.Watchdog.IWatchdog.
Definition at line 535 of file WatchdogBase.cs.
        {
            watchdogStatusMetric.Set((int)Status);
            var controller = GetActiveController();
            ramUsageMetric.Set(controller?.MemoryUsage ?? 0);
            cpuUsageMetric.Set(controller?.MeasureProcessorTimeDelta() ?? 0);
        }
References Tgstation.Server.Host.Components.Watchdog.WatchdogBase.cpuUsageMetric, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.GetActiveController(), Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.MemoryUsage, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ramUsageMetric, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Status, and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.watchdogStatusMetric.
StartAsync()
async Task Tgstation.Server.Host.Components.Watchdog.WatchdogBase.StartAsync (CancellationToken cancellationToken)
Definition at line 422 of file WatchdogBase.cs.
        {
            var reattachInfo = await SessionPersistor.Load(cancellationToken);
            var reattaching = reattachInfo != null;
            if (!autoStart && !reattaching)
                return;
            var job = Models.Job.Create(
                reattaching
                    ? JobCode.StartupWatchdogReattach
                    : JobCode.StartupWatchdogLaunch,
                null,
                metadata,
                DreamDaemonRights.Shutdown);
            await jobManager.RegisterOperation(
                job,
                async (core, databaseContextFactory, paramJob, progressFunction, ct) =>
                {
                    if (core?.Watchdog != this)
                        throw new InvalidOperationException(Instance.DifferentCoreExceptionMessage);
                    using (await SemaphoreSlimContext.Lock(synchronizationSemaphore, ct))
                        await LaunchNoLock(true, true, true, reattachInfo, ct);
                    await Chat.UpdateTrackingContexts(ct);
                },
                cancellationToken);
        }
References Tgstation.Server.Host.Components.Watchdog.WatchdogBase.autoStart, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Chat, Tgstation.Server.Host.Components.Instance.DifferentCoreExceptionMessage, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.jobManager, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.LaunchNoLock(), Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Components.Session.SessionPersistor.Load(), Tgstation.Server.Host.Utils.SemaphoreSlimContext.Lock(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.metadata, Tgstation.Server.Host.Jobs.IJobManager.RegisterOperation(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.synchronizationSemaphore, and Tgstation.Server.Host.Components.Chat.IChatManager.UpdateTrackingContexts().
StopAsync()
async Task Tgstation.Server.Host.Components.Watchdog.WatchdogBase.StopAsync (CancellationToken cancellationToken)
StopMonitor()
async ValueTask< bool > Tgstation.Server.Host.Components.Watchdog.WatchdogBase.StopMonitor () protected
Stops MonitorLifetimes(CancellationToken). Doesn't kill the servers.
Returns
A ValueTask<TResult> resulting in true if the monitor was running, false otherwise.
Definition at line 671 of file WatchdogBase.cs.
        {
            Logger.LogTrace("StopMonitor");
            if (monitorTask == null)
                return false;
            var wasRunning = !monitorTask.IsCompleted;
            monitorCts!.Cancel();
            await monitorTask;
            Logger.LogTrace("Stopped Monitor");
            monitorCts.Dispose();
            monitorTask = null;
            monitorCts = null;
            return wasRunning;
        }
References Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Logger, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.monitorCts, and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.monitorTask.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.TerminateNoLock().
Terminate()
async ValueTask Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Terminate (bool graceful, CancellationToken cancellationToken)
Stops the watchdog.
Parameters
graceful If true the termination will be delayed until a reboot is detected in the active server's DMAPI and this function will return immediately.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Watchdog.IWatchdog.
Definition at line 456 of file WatchdogBase.cs.
        {
            using (await SemaphoreSlimContext.Lock(synchronizationSemaphore, cancellationToken))
                await TerminateNoLock(graceful, !releaseServers, cancellationToken);
        }
References Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Utils.SemaphoreSlimContext.Lock(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.releaseServers, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.synchronizationSemaphore, and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.TerminateNoLock().
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleRestart().
TerminateNoLock()
async ValueTask Tgstation.Server.Host.Components.Watchdog.WatchdogBase.TerminateNoLock (bool graceful, bool announce, CancellationToken cancellationToken) private
Implementation of Terminate(bool, CancellationToken). Does not lock synchronizationSemaphore.
Parameters
graceful If true the termination will be delayed until a reboot is detected in the active server's DMAPI and this function will return immediately.
announce If true the termination will be announced using Chat.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Definition at line 1122 of file WatchdogBase.cs.
        {
            if (Status == WatchdogStatus.Offline)
                return;
            if (!graceful)
            {
                var eventTask = HandleEventImpl(
                    releaseServers
                        ? EventType.WatchdogDetach
                        : EventType.WatchdogShutdown,
                    Enumerable.Empty<string>(),
                    releaseServers,
                    cancellationToken);
                if (announce)
                    Chat.QueueWatchdogMessage("Shutting down...");
                await eventTask;
                await StopMonitor();
                LastLaunchParameters = null;
                return;
            }
            // merely set the reboot state
            var toKill = GetActiveController();
            if (toKill != null)
            {
                await toKill.SetRebootState(Session.RebootState.Shutdown, cancellationToken);
                Logger.LogTrace("Graceful termination requested");
            }
            else
                Logger.LogTrace("Could not gracefully terminate as there is no active controller!");
        }
References Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Chat, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.GetActiveController(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleEventImpl(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.LastLaunchParameters, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Logger, Tgstation.Server.Host.Components.Chat.IChatManager.QueueWatchdogMessage(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.releaseServers, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Status, and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.StopMonitor().
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Restart(), and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Terminate().
Member Data Documentation
activeParametersUpdated
volatile TaskCompletionSource Tgstation.Server.Host.Components.Watchdog.WatchdogBase.activeParametersUpdated private
TaskCompletionSource that completes when ActiveLaunchParameters are changed and we are running.
Definition at line 179 of file WatchdogBase.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ChangeSettings(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.MonitorLifetimes(), and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.WatchdogBase().
autoStart
readonly bool Tgstation.Server.Host.Components.Watchdog.WatchdogBase.autoStart private
If the WatchdogBase should LaunchNoLock(bool, bool, bool, ReattachInformation, CancellationToken) in StartAsync(CancellationToken).
Definition at line 174 of file WatchdogBase.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.StartAsync(), and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.WatchdogBase().
controllerDisposeSemaphore
readonly SemaphoreSlim Tgstation.Server.Host.Components.Watchdog.WatchdogBase.controllerDisposeSemaphore private
SemaphoreSlim used for DisposeAndNullControllers.
Definition at line 129 of file WatchdogBase.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.DisposeAndNullControllers(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.DisposeAsync(), and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.WatchdogBase().
cpuUsageMetric
readonly Gauge Tgstation.Server.Host.Components.Watchdog.WatchdogBase.cpuUsageMetric private
Active session CPU usage as a metric.
Definition at line 139 of file WatchdogBase.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.RunMetricsScrape(), and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.WatchdogBase().
diagnosticsIOManager
readonly IIOManager Tgstation.Server.Host.Components.Watchdog.WatchdogBase.diagnosticsIOManager private
The IIOManager pointing to the Diagnostics directory.
Definition at line 164 of file WatchdogBase.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.WatchdogBase().
disposed
bool Tgstation.Server.Host.Components.Watchdog.WatchdogBase.disposed private
If the WatchdogBase has been DisposeAsync'd.
Definition at line 209 of file WatchdogBase.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.DisposeAsync(), and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.MonitorLifetimes().
eventConsumer
readonly IEventConsumer Tgstation.Server.Host.Components.Watchdog.WatchdogBase.eventConsumer private
The IEventConsumer that is not the WatchdogBase.
Definition at line 149 of file WatchdogBase.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.BeforeApplyDmb(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleEventImpl(), and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.WatchdogBase().
healthChecksMissed
int Tgstation.Server.Host.Components.Watchdog.WatchdogBase.healthChecksMissed private
The number of hearbeats missed.
Definition at line 199 of file WatchdogBase.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleHealthCheck(), and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.LaunchNoLock().
jobManager
readonly IJobManager Tgstation.Server.Host.Components.Watchdog.WatchdogBase.jobManager private
The IJobManager for the WatchdogBase.
Definition at line 154 of file WatchdogBase.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.StartAsync(), and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.WatchdogBase().
metadata
readonly Api.Models.Instance Tgstation.Server.Host.Components.Watchdog.WatchdogBase.metadata private
The Api.Models.Instance for the WatchdogBase.
Definition at line 119 of file WatchdogBase.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.BeforeApplyDmb(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.StartAsync(), and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.WatchdogBase().
monitorCts
CancellationTokenSource? Tgstation.Server.Host.Components.Watchdog.WatchdogBase.monitorCts private
The CancellationTokenSource for the monitor loop.
Definition at line 184 of file WatchdogBase.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.DisposeAsync(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.LaunchNoLock(), and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.StopMonitor().
monitorTask
Task? Tgstation.Server.Host.Components.Watchdog.WatchdogBase.monitorTask private
The Task running the monitor loop.
Definition at line 189 of file WatchdogBase.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleRestart(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.LaunchNoLock(), and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.StopMonitor().
ramUsageMetric
readonly Gauge Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ramUsageMetric private
MemoryUsage as a metric.
Definition at line 144 of file WatchdogBase.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.RunMetricsScrape(), and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.WatchdogBase().
releaseServers
bool Tgstation.Server.Host.Components.Watchdog.WatchdogBase.releaseServers private
If the servers should be released instead of shutdown.
Definition at line 204 of file WatchdogBase.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.DisposeAndNullControllers(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleRestart(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.MonitorLifetimes(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Terminate(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.TerminateNoLock(), and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.WatchdogBase().
remoteDeploymentManagerFactory
readonly IRemoteDeploymentManagerFactory Tgstation.Server.Host.Components.Watchdog.WatchdogBase.remoteDeploymentManagerFactory private
The IRemoteDeploymentManagerFactory for the WatchdogBase.
Definition at line 169 of file WatchdogBase.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.BeforeApplyDmb(), and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.WatchdogBase().
restartRegistration
readonly IRestartRegistration Tgstation.Server.Host.Components.Watchdog.WatchdogBase.restartRegistration private
The IRestartRegistration for the WatchdogBase.
Definition at line 159 of file WatchdogBase.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.DisposeAsync(), and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.WatchdogBase().
status
WatchdogStatus Tgstation.Server.Host.Components.Watchdog.WatchdogBase.status private
Backing field for Status.
Definition at line 194 of file WatchdogBase.cs.
synchronizationSemaphore
readonly SemaphoreSlim Tgstation.Server.Host.Components.Watchdog.WatchdogBase.synchronizationSemaphore private
The SemaphoreSlim for the WatchdogBase.
Definition at line 124 of file WatchdogBase.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ChangeSettings(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.CreateDump(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.DisposeAsync(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleChatCommand(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Launch(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.MonitorLifetimes(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.MonitorRestart(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ResetRebootState(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Restart(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.StartAsync(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Terminate(), and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.WatchdogBase().
watchdogStatusMetric
readonly Gauge Tgstation.Server.Host.Components.Watchdog.WatchdogBase.watchdogStatusMetric private
The Status as a metric.
Definition at line 134 of file WatchdogBase.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.RunMetricsScrape(), and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.WatchdogBase().
Property Documentation
ActiveCompileJob
Models.? CompileJob Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ActiveCompileJob get
Retrieves the Models.CompileJob currently running on the server.
Implements Tgstation.Server.Host.Components.Watchdog.IWatchdog.
Definition at line 76 of file WatchdogBase.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.BeforeApplyDmb(), and Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.HandleNewDmbAvailable().
ActiveLaunchParameters
DreamDaemonLaunchParameters Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ActiveLaunchParameters get protected set
The DreamDaemonLaunchParameters to be applied.
Implements Tgstation.Server.Host.Components.Watchdog.IWatchdog.
Definition at line 70 of file WatchdogBase.cs.
{ get; protected set; }
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ChangeSettings(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleHealthCheck(), Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.HandleNormalReboot(), Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.InitController(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.LaunchNoLock(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.MonitorLifetimes(), and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.WatchdogBase().
AlphaIsActive
bool Tgstation.Server.Host.Components.Watchdog.WatchdogBase.AlphaIsActive get abstract
If the alpha server is the active server.
Implements Tgstation.Server.Host.Components.Watchdog.IWatchdog.
Definition at line 67 of file WatchdogBase.cs.
{ get; }
AsyncDelayer
IAsyncDelayer Tgstation.Server.Host.Components.Watchdog.WatchdogBase.AsyncDelayer get protected
The IAsyncDelayer for the WatchdogBase.
Definition at line 109 of file WatchdogBase.cs.
{ get; }
Chat
IChatManager Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Chat get protected
The IChatManager for the WatchdogBase.
Definition at line 94 of file WatchdogBase.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleChatResponses(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleHealthCheck(), Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.HandleMonitorWakeup(), Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.HandleNewDmbAvailable(), Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.HandleNormalReboot(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleRestart(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.LaunchNoLock(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.MonitorLifetimes(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.MonitorRestart(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ReattachFailure(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Restart(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.StartAsync(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.TerminateNoLock(), and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.WatchdogBase().
ClientCount
uint? Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ClientCount get private set
Last known client count queried from the DMAPI. Requires health checks to be enabled to populate.
Implements Tgstation.Server.Host.Components.Watchdog.IWatchdog.
Definition at line 46 of file WatchdogBase.cs.
{ get; private set; }
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleHealthCheck(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.LaunchNoLock(), and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ReattachFailure().
DmbFactory
IDmbFactory Tgstation.Server.Host.Components.Watchdog.WatchdogBase.DmbFactory get protected
The IDmbFactory for the WatchdogBase.
Definition at line 104 of file WatchdogBase.cs.
{ get; }
GameIOManager
IIOManager Tgstation.Server.Host.Components.Watchdog.WatchdogBase.GameIOManager get protected
The IIOManager for the WatchdogBase pointing to the Game directory.
Definition at line 114 of file WatchdogBase.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.WatchdogBase().
LastLaunchParameters
DreamDaemonLaunchParameters? Tgstation.Server.Host.Components.Watchdog.WatchdogBase.LastLaunchParameters get protected set
The DreamDaemonLaunchParameters the active server is using.This may not be the exact same as ActiveLaunchParameters but still be associated with the same session.
Implements Tgstation.Server.Host.Components.Watchdog.IWatchdog.
Definition at line 73 of file WatchdogBase.cs.
{ get; protected set; }
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.LaunchNoLock(), and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.TerminateNoLock().
LaunchTime
DateTimeOffset? Tgstation.Server.Host.Components.Watchdog.WatchdogBase.LaunchTime get
When the current server executions was started.
Implements Tgstation.Server.Host.Components.Watchdog.IWatchdog.
Definition at line 49 of file WatchdogBase.cs.
Logger
ILogger<WatchdogBase> Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Logger get protected
The ILogger for the WatchdogBase.
Definition at line 89 of file WatchdogBase.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.ApplyInitialDmb(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.BeforeApplyDmb(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Broadcast(), Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.CanUseSwappableDmbProvider(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.DisposeAndNullControllers(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.DisposeAsync(), Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.DrainDeploymentCleanupTasks(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleChatResponses(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleEvent(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleEventImpl(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleHealthCheck(), Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.HandleMonitorWakeup(), Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.HandleNewDmbAvailable(), Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.HandleNormalReboot(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleRestart(), Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.InitController(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.InitialCheckDmbUpdated(), Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.InitialLink(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.LaunchNoLock(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.MonitorLifetimes(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.MonitorRestart(), Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.PerformDmbSwap(), Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.PrepServerForLaunch(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ReattachFailure(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Restart(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.StopMonitor(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.TerminateNoLock(), and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.WatchdogBase().
MemoryUsage
long? Tgstation.Server.Host.Components.Watchdog.WatchdogBase.MemoryUsage get
Gets the memory usage of the game server in bytes.
Implements Tgstation.Server.Host.Components.Watchdog.IWatchdog.
Definition at line 64 of file WatchdogBase.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.RunMetricsScrape().
RebootState
RebootState? Tgstation.Server.Host.Components.Watchdog.WatchdogBase.RebootState get abstract
The Session.RebootState of the active server.
Implements Tgstation.Server.Host.Components.Watchdog.IWatchdog.
Definition at line 79 of file WatchdogBase.cs.
{ get; }
SessionControllerFactory
ISessionControllerFactory Tgstation.Server.Host.Components.Watchdog.WatchdogBase.SessionControllerFactory get protected
The ISessionControllerFactory for the WatchdogBase.
Definition at line 99 of file WatchdogBase.cs.
{ get; }
SessionId
long? Tgstation.Server.Host.Components.Watchdog.WatchdogBase.SessionId get
An incrementing ID for representing current server execution.
Implements Tgstation.Server.Host.Components.Watchdog.IWatchdog.
Definition at line 40 of file WatchdogBase.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.InitController().
SessionPersistor
ISessionPersistor Tgstation.Server.Host.Components.Watchdog.WatchdogBase.SessionPersistor get protected
The ISessionPersistor for the WatchdogBase.
Definition at line 84 of file WatchdogBase.cs.
{ get; }
Status
WatchdogStatus Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Status get protected set
The current WatchdogStatus.
Implements Tgstation.Server.Host.Components.Watchdog.IWatchdog.
Definition at line 52 of file WatchdogBase.cs.
        {
            get => status;
            protected set
            {
                var oldStatus = status;
                status = value;
                Logger.LogTrace("Status set from {oldStatus} to {status}", oldStatus, status);
            }
        }
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ChangeSettings(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleChatCommand(), Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.HandleMonitorWakeup(), Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.HandleNormalReboot(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleRestart(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Launch(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.LaunchNoLock(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.MonitorLifetimes(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.MonitorRestart(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ResetRebootState(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Restart(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.RunMetricsScrape(), and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.TerminateNoLock().
WorldIteration
long? Tgstation.Server.Host.Components.Watchdog.WatchdogBase.WorldIteration get
A incrementing ID for representing current iteration of servers world (i.e. after calling /world/proc/Reboot). Only unique within the current SessionId. Only tracked in game sessions with the DMAPI enabled.
Implements Tgstation.Server.Host.Components.Watchdog.IWatchdog.
Definition at line 43 of file WatchdogBase.cs.
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Watchdog/WatchdogBase.cs