tgstation-server: TGServerService.RepoConfig Class Reference
TGServerService.RepoConfig Class Reference
Repository specific information for a ServerInstance
Public Member Functions
RepoConfig (string path)
Construct a RepoConfig
override bool Equals (object obj)
bool Equals (RepoConfig other)
override int GetHashCode ()
Static Public Member Functions
static bool operator== (RepoConfig config1, RepoConfig config2)
static bool operator!= (RepoConfig config1, RepoConfig config2)
Public Attributes
readonly bool ChangelogSupport
If this json is setup to support TGServiceInterface.Components.ITGRepository.GenerateChangelog(out string)
readonly string PathToChangelogPy
Path to the repository's changelog generator script
readonly string ChangelogPyArguments
Arguments for the changelog gennerator script
readonly IList< string > PipDependancies = new List<string>()
List of python pip dependencies for the changelog generator script
readonly IList< string > PathsToStage = new List<string>()
Paths to commit and push to the remote repository
readonly IList< string > StaticDirectoryPaths = new List<string>()
Directory's whose contents should not be touched when the ServerInstance updates
readonly IList< string > DLLPaths = new List<string>()
DLL's used by DreamDaemon call()() operations. Must be handled as symlinks to avoid lockups during update operations
Static Private Member Functions
static IList< string > LoadArray (object o)
Convert an array of strings to a IList<T> of strings
static bool ListEquals (IList< string > A, IList< string > B)
Check if two string IList<T>s have the same contents
Detailed Description
Repository specific information for a ServerInstance
Definition at line 12 of file RepoConfig.cs.
Constructor & Destructor Documentation
TGServerService.RepoConfig.RepoConfig (string path)
Construct a RepoConfig
Parameters
path Path to the config JSON to use
Definition at line 47 of file RepoConfig.cs.
References TGServerService.RepoConfig.LoadArray().
         {
             if (!File.Exists(path))
                 return;
             var rawdata = File.ReadAllText(path);
             var Deserializer = new JavaScriptSerializer();
             var json = Deserializer.Deserialize<IDictionary<string, object>>(rawdata);
             try
             {
                 var details = (IDictionary<string, object>)json["changelog"];
                 PathToChangelogPy = (string)details["script"];
                 ChangelogPyArguments = (string)details["arguments"];
                 ChangelogSupport = true;
                 try
                 {
                     PipDependancies = LoadArray(details["pip_dependancies"]);
                 }
                 catch { }
             }
             catch
             {
                 ChangelogSupport = false;
             }
             try
             {
                 PathsToStage = LoadArray(json["synchronize_paths"]);
             }
             catch { }
             try
             {
                 StaticDirectoryPaths = LoadArray(json["static_directories"]);
             }
             catch { }
             try
             {
                 DLLPaths = LoadArray(json["dlls"]);
             }
             catch { }
         }
Member Function Documentation
override bool TGServerService.RepoConfig.Equals (object obj)
Definition at line 102 of file RepoConfig.cs.
         {
             return Equals(obj as RepoConfig);
         }
bool TGServerService.RepoConfig.Equals (RepoConfig other)
Definition at line 118 of file RepoConfig.cs.
References TGServerService.RepoConfig.ChangelogPyArguments, TGServerService.RepoConfig.ChangelogSupport, TGServerService.RepoConfig.DLLPaths, TGServerService.RepoConfig.ListEquals(), TGServerService.RepoConfig.PathsToStage, TGServerService.RepoConfig.PathToChangelogPy, TGServerService.RepoConfig.PipDependancies, and TGServerService.RepoConfig.StaticDirectoryPaths.
         {
             return ChangelogSupport == other.ChangelogSupport
                 && PathToChangelogPy == other.PathToChangelogPy
                 && ChangelogPyArguments == other.ChangelogPyArguments
                 && ListEquals(PipDependancies, other.PipDependancies)
                 && ListEquals(PathsToStage, other.PathsToStage)
                 && ListEquals(StaticDirectoryPaths, other.StaticDirectoryPaths)
                 && ListEquals(DLLPaths, other.DLLPaths);
         }
override int TGServerService.RepoConfig.GetHashCode ()
Definition at line 129 of file RepoConfig.cs.
         {
             var hashCode = 1890628544;
             hashCode = hashCode * -1521134295 + ChangelogSupport.GetHashCode();
             hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(PathToChangelogPy);
             hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(ChangelogPyArguments);
             hashCode = hashCode * -1521134295 + EqualityComparer<IList<string>>.Default.GetHashCode(PipDependancies);
             hashCode = hashCode * -1521134295 + EqualityComparer<IList<string>>.Default.GetHashCode(PathsToStage);
             hashCode = hashCode * -1521134295 + EqualityComparer<IList<string>>.Default.GetHashCode(StaticDirectoryPaths);
             hashCode = hashCode * -1521134295 + EqualityComparer<IList<string>>.Default.GetHashCode(DLLPaths);
             return hashCode;
         }
static bool TGServerService.RepoConfig.ListEquals (IList< string > A, IList< string > B) static private
Check if two string IList<T>s have the same contents
Parameters
A The first string IList<T>
B The second string IList<T>
Returns
if the string IList<T>s match, otherwise
Definition at line 113 of file RepoConfig.cs.
Referenced by TGServerService.RepoConfig.Equals().
         {
             return A.All(B.Contains) && A.Count == B.Count;
         }
static IList<string> TGServerService.RepoConfig.LoadArray (object o) static private
Convert an array of strings to a IList<T> of strings
Parameters
o The string array to convert
Returns
Definition at line 92 of file RepoConfig.cs.
Referenced by TGServerService.RepoConfig.RepoConfig().
         {
             var array = (object[])o;
             var res = new List<string>();
             foreach (var I in array)
                 res.Add((string)I);
             return res;
         }
static bool TGServerService.RepoConfig.operator!= (RepoConfig config1, RepoConfig config2) static
Definition at line 147 of file RepoConfig.cs.
         {
             return !(config1 == config2);
         }
static bool TGServerService.RepoConfig.operator== (RepoConfig config1, RepoConfig config2) static
Definition at line 142 of file RepoConfig.cs.
         {
             return EqualityComparer<RepoConfig>.Default.Equals(config1, config2);
         }
Member Data Documentation
readonly string TGServerService.RepoConfig.ChangelogPyArguments
Arguments for the changelog gennerator script
Definition at line 25 of file RepoConfig.cs.
Referenced by TGServerService.RepoConfig.Equals().
readonly bool TGServerService.RepoConfig.ChangelogSupport
If this json is setup to support TGServiceInterface.Components.ITGRepository.GenerateChangelog(out string)
Definition at line 17 of file RepoConfig.cs.
Referenced by TGServerService.RepoConfig.Equals().
readonly IList<string> TGServerService.RepoConfig.DLLPaths = new List<string>()
DLL's used by DreamDaemon call()() operations. Must be handled as symlinks to avoid lockups during update operations
Definition at line 41 of file RepoConfig.cs.
Referenced by TGServerService.RepoConfig.Equals().
readonly IList<string> TGServerService.RepoConfig.PathsToStage = new List<string>()
Paths to commit and push to the remote repository
Definition at line 33 of file RepoConfig.cs.
Referenced by TGServerService.ServerInstance.Commit(), and TGServerService.RepoConfig.Equals().
readonly string TGServerService.RepoConfig.PathToChangelogPy
Path to the repository's changelog generator script
Definition at line 21 of file RepoConfig.cs.
Referenced by TGServerService.RepoConfig.Equals().
readonly IList<string> TGServerService.RepoConfig.PipDependancies = new List<string>()
List of python pip dependencies for the changelog generator script
Definition at line 29 of file RepoConfig.cs.
Referenced by TGServerService.RepoConfig.Equals().
readonly IList<string> TGServerService.RepoConfig.StaticDirectoryPaths = new List<string>()
Directory's whose contents should not be touched when the ServerInstance updates
Definition at line 37 of file RepoConfig.cs.
Referenced by TGServerService.RepoConfig.Equals().
The documentation for this class was generated from the following file:
TGServerService/RepoConfig.cs