tgstation-server: Tgstation.Server.Host.Setup.SetupApplication Class Reference
Tgstation.Server.Host.Setup.SetupApplication Class Reference
DI root for configuring a SetupWizard.
Public Member Functions
SetupApplication (IConfiguration configuration)
Initializes a new instance of the SetupApplication class.
void ConfigureServices (IServiceCollection services)
Configure dependency injected services.
Static Public Attributes
static readonly IAssemblyInformationProvider AssemblyInformationProvider = new AssemblyInformationProvider()
The IAssemblyInformationProvider for the SetupApplication.
static readonly IIOManager IOManager = new DefaultIOManager(AssemblyInformationProvider)
The IIOManager for the SetupApplication.
Protected Member Functions
virtual void ConfigureHostedService (IServiceCollection services)
Configures the IHostedService.
Properties
IConfiguration Configuration [get]
The IConfiguration for the SetupApplication.
Detailed Description
DI root for configuring a SetupWizard.
Definition at line 20 of file SetupApplication.cs.
Constructor & Destructor Documentation
SetupApplication()
Tgstation.Server.Host.Setup.SetupApplication.SetupApplication (IConfiguration configuration)
Initializes a new instance of the SetupApplication class.
Parameters
configuration The value of Configuration.
Definition at line 41 of file SetupApplication.cs.
        {
            Configuration = configuration ?? throw new ArgumentNullException(nameof(configuration));
        }
References Tgstation.Server.Host.Setup.SetupApplication.Configuration.
Member Function Documentation
ConfigureHostedService()
virtual void Tgstation.Server.Host.Setup.SetupApplication.ConfigureHostedService (IServiceCollection services) protected virtual
Configures the IHostedService.
Parameters
services The IServiceCollection to configure.
Reimplemented in Tgstation.Server.Host.Core.Application.
Definition at line 79 of file SetupApplication.cs.
        {
            services.AddSingleton(typeof(IPostSetupServices<>), typeof(PostSetupServices<>));
            services.AddSingleton<IHostedService, SetupWizard>();
        }
Referenced by Tgstation.Server.Host.Setup.SetupApplication.ConfigureServices().
ConfigureServices()
void Tgstation.Server.Host.Setup.SetupApplication.ConfigureServices (IServiceCollection services)
Configure dependency injected services.
Parameters
services The IServiceCollection to configure.
Definition at line 50 of file SetupApplication.cs.
        {
            if (services == null)
                throw new ArgumentNullException(nameof(services));
            services.SetupLogging(config => config.MinimumLevel.Override("Microsoft", LogEventLevel.Warning));
            services.AddSingleton(IOManager);
            services.AddSingleton(AssemblyInformationProvider);
            services.AddSingleton<IConsole, IO.Console>();
            services.AddSingleton<IDatabaseConnectionFactory, DatabaseConnectionFactory>();
            services.AddSingleton<IPlatformIdentifier, PlatformIdentifier>();
            services.AddSingleton<IAsyncDelayer, AsyncDelayer>();
            // these configs are what's injected into PostSetupServices
            services.UseStandardConfig<GeneralConfiguration>(Configuration);
            services.UseStandardConfig<DatabaseConfiguration>(Configuration);
            services.UseStandardConfig<SecurityConfiguration>(Configuration);
            services.UseStandardConfig<FileLoggingConfiguration>(Configuration);
            services.UseStandardConfig<ElasticsearchConfiguration>(Configuration);
            ConfigureHostedService(services);
        }
References Tgstation.Server.Host.Setup.SetupApplication.Configuration, Tgstation.Server.Host.Setup.SetupApplication.ConfigureHostedService(), and Tgstation.Server.Host.Setup.SetupApplication.IOManager.
Member Data Documentation
AssemblyInformationProvider
readonly IAssemblyInformationProvider Tgstation.Server.Host.Setup.SetupApplication.AssemblyInformationProvider = new AssemblyInformationProvider() static
The IAssemblyInformationProvider for the SetupApplication.
Definition at line 25 of file SetupApplication.cs.
IOManager
readonly IIOManager Tgstation.Server.Host.Setup.SetupApplication.IOManager = new DefaultIOManager(AssemblyInformationProvider) static
The IIOManager for the SetupApplication.
Definition at line 30 of file SetupApplication.cs.
Referenced by Tgstation.Server.Host.Setup.SetupApplication.ConfigureServices(), and Tgstation.Server.Host.Core.Application.ConfigureServices().
Property Documentation
Configuration
IConfiguration Tgstation.Server.Host.Setup.SetupApplication.Configuration get protected
The IConfiguration for the SetupApplication.
Definition at line 35 of file SetupApplication.cs.
{ get; }
Referenced by Tgstation.Server.Host.Core.Application.Configure(), Tgstation.Server.Host.Setup.SetupApplication.ConfigureServices(), Tgstation.Server.Host.Core.Application.ConfigureServices(), and Tgstation.Server.Host.Setup.SetupApplication.SetupApplication().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Setup/SetupApplication.cs