tgstation-server: Tgstation.Server.Host.Components.Deployment.WindowsSwappableDmbProvider Class Reference
Tgstation.Server.Host.Components.Deployment.WindowsSwappableDmbProvider Class Reference
A windows IDmbProvider that uses symlinks.
Public Member Functions
WindowsSwappableDmbProvider (IDmbProvider baseProvider, IIOManager ioManager, ISymlinkFactory symlinkFactory)
Initializes a new instance of the WindowsSwappableDmbProvider class.
void Dispose ()
void KeepAlive ()
Disposing the IDmbProvider won't cause a cleanup of the working directory
async Task MakeActive (CancellationToken cancellationToken)
Make the WindowsSwappableDmbProvider active by replacing the live link with our CompileJob.
Public Attributes
string DmbName => baseProvider.DmbName
string PrimaryDirectory => ioManager.ResolvePath(LiveGameDirectory)
string SecondaryDirectory => throw new NotSupportedException()
CompileJob CompileJob => baseProvider.CompileJob
Private Attributes
readonly IDmbProvider baseProvider
The IDmbProvider we are swapping for.
readonly IIOManager ioManager
The IIOManager to use.
readonly ISymlinkFactory symlinkFactory
The ISymlinkFactory to use.
Static Private Attributes
const string LiveGameDirectory = "Live"
The directory where the baseProvider is symlinked to.
Additional Inherited Members
Properties inherited from Tgstation.Server.Host.Components.Deployment.IDmbProvider
string DmbName [get]
The file name of the .dmb
string PrimaryDirectory [get]
The primary game directory with a trailing directory separator
string SecondaryDirectory [get]
The secondary game directory with a trailing directory separator
CompileJob CompileJob [get]
The CompileJob of the .dmb
Detailed Description
A windows IDmbProvider that uses symlinks.
Definition at line 12 of file WindowsSwappableDmbProvider.cs.
Constructor & Destructor Documentation
WindowsSwappableDmbProvider()
Tgstation.Server.Host.Components.Deployment.WindowsSwappableDmbProvider.WindowsSwappableDmbProvider (IDmbProvider baseProvider, IIOManager ioManager, ISymlinkFactory symlinkFactory)
Initializes a new instance of the WindowsSwappableDmbProvider class.
Parameters
baseProvider The value of baseProvider.
ioManager The value of ioManager.
symlinkFactory The value of symlinkFactory.
Definition at line 52 of file WindowsSwappableDmbProvider.cs.
         {
             this.baseProvider = baseProvider ?? throw new ArgumentNullException(nameof(baseProvider));
             this.ioManager = ioManager ?? throw new ArgumentNullException(nameof(ioManager));
             this.symlinkFactory = symlinkFactory ?? throw new ArgumentNullException(nameof(symlinkFactory));
         }
References Tgstation.Server.Host.Components.Deployment.WindowsSwappableDmbProvider.baseProvider, Tgstation.Server.Host.Components.Deployment.WindowsSwappableDmbProvider.ioManager, and Tgstation.Server.Host.Components.Deployment.WindowsSwappableDmbProvider.symlinkFactory.
Member Function Documentation
Dispose()
void Tgstation.Server.Host.Components.Deployment.WindowsSwappableDmbProvider.Dispose ()
Referenced by Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.DisposeAndNullControllers(), and Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.HandleNewDmbAvailable().
KeepAlive()
void Tgstation.Server.Host.Components.Deployment.WindowsSwappableDmbProvider.KeepAlive ()
Disposing the IDmbProvider won't cause a cleanup of the working directory
Implements Tgstation.Server.Host.Components.Deployment.IDmbProvider.
MakeActive()
async Task Tgstation.Server.Host.Components.Deployment.WindowsSwappableDmbProvider.MakeActive (CancellationToken cancellationToken)
Make the WindowsSwappableDmbProvider active by replacing the live link with our CompileJob.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Definition at line 70 of file WindowsSwappableDmbProvider.cs.
         {
             // Note this comment from TGS3:
             // These next two lines should be atomic but this is the best we can do
             await ioManager.DeleteDirectory(LiveGameDirectory, cancellationToken).ConfigureAwait(false);
             await symlinkFactory.CreateSymbolicLink(baseProvider.PrimaryDirectory, ioManager.ResolvePath(LiveGameDirectory), cancellationToken).ConfigureAwait(false);
         }
References Tgstation.Server.Host.Components.Deployment.WindowsSwappableDmbProvider.baseProvider, Tgstation.Server.Host.IO.ISymlinkFactory.CreateSymbolicLink(), Tgstation.Server.Host.IO.IIOManager.DeleteDirectory(), Tgstation.Server.Host.Components.Deployment.WindowsSwappableDmbProvider.ioManager, Tgstation.Server.Host.Components.Deployment.WindowsSwappableDmbProvider.LiveGameDirectory, Tgstation.Server.Host.Components.Deployment.IDmbProvider.PrimaryDirectory, Tgstation.Server.Host.IO.IIOManager.ResolvePath(), and Tgstation.Server.Host.Components.Deployment.WindowsSwappableDmbProvider.symlinkFactory.
Referenced by Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.HandleNewDmbAvailable(), and Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.PrepServerForLaunch().
Member Data Documentation
baseProvider
readonly IDmbProvider Tgstation.Server.Host.Components.Deployment.WindowsSwappableDmbProvider.baseProvider private
The IDmbProvider we are swapping for.
Definition at line 34 of file WindowsSwappableDmbProvider.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.WindowsSwappableDmbProvider.MakeActive(), and Tgstation.Server.Host.Components.Deployment.WindowsSwappableDmbProvider.WindowsSwappableDmbProvider().
CompileJob
CompileJob Tgstation.Server.Host.Components.Deployment.WindowsSwappableDmbProvider.CompileJob => baseProvider.CompileJob
Definition at line 29 of file WindowsSwappableDmbProvider.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.HandleNewDmbAvailable().
DmbName
string Tgstation.Server.Host.Components.Deployment.WindowsSwappableDmbProvider.DmbName => baseProvider.DmbName
Definition at line 20 of file WindowsSwappableDmbProvider.cs.
ioManager
readonly IIOManager Tgstation.Server.Host.Components.Deployment.WindowsSwappableDmbProvider.ioManager private
The IIOManager to use.
Definition at line 39 of file WindowsSwappableDmbProvider.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.WindowsSwappableDmbProvider.MakeActive(), and Tgstation.Server.Host.Components.Deployment.WindowsSwappableDmbProvider.WindowsSwappableDmbProvider().
LiveGameDirectory
const string Tgstation.Server.Host.Components.Deployment.WindowsSwappableDmbProvider.LiveGameDirectory = "Live" static private
The directory where the baseProvider is symlinked to.
Definition at line 17 of file WindowsSwappableDmbProvider.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.WindowsSwappableDmbProvider.MakeActive().
PrimaryDirectory
string Tgstation.Server.Host.Components.Deployment.WindowsSwappableDmbProvider.PrimaryDirectory => ioManager.ResolvePath(LiveGameDirectory)
Definition at line 23 of file WindowsSwappableDmbProvider.cs.
SecondaryDirectory
string Tgstation.Server.Host.Components.Deployment.WindowsSwappableDmbProvider.SecondaryDirectory => throw new NotSupportedException()
Definition at line 26 of file WindowsSwappableDmbProvider.cs.
symlinkFactory
readonly ISymlinkFactory Tgstation.Server.Host.Components.Deployment.WindowsSwappableDmbProvider.symlinkFactory private
The ISymlinkFactory to use.
Definition at line 44 of file WindowsSwappableDmbProvider.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.WindowsSwappableDmbProvider.MakeActive(), and Tgstation.Server.Host.Components.Deployment.WindowsSwappableDmbProvider.WindowsSwappableDmbProvider().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Deployment/WindowsSwappableDmbProvider.cs