tgstation-server: Tgstation.Server.Host.Utils.SemaphoreSlimContext Class Reference
Tgstation.Server.Host.Utils.SemaphoreSlimContext Class Reference sealed
Async lock context helper.
Public Member Functions
void Dispose ()
Release the lock on lockedSemaphore.
Static Public Member Functions
static async ValueTask< SemaphoreSlimContext > Lock (SemaphoreSlim semaphore, CancellationToken cancellationToken, ILogger? logger=null)
Asyncronously locks a semaphore .
static ? SemaphoreSlimContext TryLock (SemaphoreSlim semaphore, ILogger? logger, out bool locked)
Asyncronously attempts to lock a semaphore .
Private Member Functions
SemaphoreSlimContext (SemaphoreSlim lockedSemaphore, ILogger? logger)
Initializes a new instance of the SemaphoreSlimContext class.
Private Attributes
readonly? ILogger logger
An optional ILogger to write to.
readonly SemaphoreSlim lockedSemaphore
The locked SemaphoreSlim.
Detailed Description
Async lock context helper.
Definition at line 12 of file SemaphoreSlimContext.cs.
Constructor & Destructor Documentation
SemaphoreSlimContext()
Tgstation.Server.Host.Utils.SemaphoreSlimContext.SemaphoreSlimContext (SemaphoreSlim lockedSemaphore, ILogger? logger) private
Initializes a new instance of the SemaphoreSlimContext class.
Parameters
lockedSemaphore The value of lockedSemaphore.
logger The value of logger.
Definition at line 62 of file SemaphoreSlimContext.cs.
        {
            this.lockedSemaphore = lockedSemaphore;
            this.logger = logger;
        }
References Tgstation.Server.Host.Utils.SemaphoreSlimContext.lockedSemaphore, and Tgstation.Server.Host.Utils.SemaphoreSlimContext.logger.
Member Function Documentation
Dispose()
void Tgstation.Server.Host.Utils.SemaphoreSlimContext.Dispose ()
Release the lock on lockedSemaphore.
Definition at line 71 of file SemaphoreSlimContext.cs.
        {
            logger?.LogTrace("Releasing semaphore...");
            lockedSemaphore.Release();
        }
References Tgstation.Server.Host.Utils.SemaphoreSlimContext.lockedSemaphore, and Tgstation.Server.Host.Utils.SemaphoreSlimContext.logger.
Lock()
static async ValueTask< SemaphoreSlimContext > Tgstation.Server.Host.Utils.SemaphoreSlimContext.Lock (SemaphoreSlim semaphore, CancellationToken cancellationToken, ILogger? logger = null) static
Asyncronously locks a semaphore .
Parameters
semaphore The SemaphoreSlim to lock.
cancellationToken The CancellationToken for the operation.
logger An optional ILogger to write to.
Returns
A Task<TResult> resulting in the SemaphoreSlimContext for the lock.
Definition at line 21 of file SemaphoreSlimContext.cs.
        {
            ArgumentNullException.ThrowIfNull(semaphore);
            logger?.LogTrace("Acquiring semaphore...");
            await semaphore.WaitAsync(cancellationToken);
            return new SemaphoreSlimContext(semaphore, logger);
        }
References Tgstation.Server.Host.Utils.SemaphoreSlimContext.logger.
Referenced by Tgstation.Server.Host.Components.Chat.ChatManager.ChangeChannels(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ChangeSettings(), Tgstation.Server.Host.Components.Engine.EngineManager.ChangeVersion(), Tgstation.Server.Host.Components.Repository.RepositoryManager.CloneRepository(), Tgstation.Server.Host.IO.DefaultIOManager.CopyDirectoryImpl(), Tgstation.Server.Host.Components.StaticFiles.Configuration.CopyDMFilesTo(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.CreateDump(), Tgstation.Server.Host.Components.Chat.ChatManager.DeleteConnection(), Tgstation.Server.Host.Components.Repository.RepositoryManager.DeleteRepository(), Tgstation.Server.Host.Components.Engine.EngineManager.DeleteVersion(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.DisposeAndNullControllers(), Tgstation.Server.Host.Components.StaticFiles.Configuration.ExecuteEventScripts(), Tgstation.Server.Host.GraphQL.Types.UpdateInformation.GetAdministrationResponseSafe(), Tgstation.Server.Host.Utils.PortAllocator.GetAvailablePort(), Tgstation.Server.Host.Utils.GitHub.GitHubClientFactory.GetOrCreateClient(), Tgstation.Server.Host.IO.BufferedFileStreamProvider.GetResultInternal(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleChatCommand(), Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.InstallDirectX(), Tgstation.Server.Host.Components.InstanceManager.InstanceManager(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Launch(), Tgstation.Server.Host.Utils.FifoSemaphore.Lock(), Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.MirrorDirectoryImpl(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.MonitorLifetimes(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.MonitorRestart(), Tgstation.Server.Host.Components.InstanceManager.MoveInstance(), Tgstation.Server.Host.Components.InstanceManager.OfflineInstance(), Tgstation.Server.Host.Components.InstanceManager.OnlineInstance(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ResetRebootState(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Restart(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.StartAsync(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Terminate(), and Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.TrustDmbPath().
TryLock()
static ? SemaphoreSlimContext Tgstation.Server.Host.Utils.SemaphoreSlimContext.TryLock (SemaphoreSlim semaphore, ILogger? logger, out bool locked) static
Asyncronously attempts to lock a semaphore .
Parameters
semaphore The SemaphoreSlim to lock.
logger An optional ILogger to write to.
locked The bool result of the lock attempt.
Returns
A SemaphoreSlimContext for the lock on success, or null if it was not acquired.
Definition at line 36 of file SemaphoreSlimContext.cs.
        {
            ArgumentNullException.ThrowIfNull(semaphore);
            logger?.LogTrace("Trying to acquire semaphore...");
            locked = semaphore.Wait(TimeSpan.Zero);
            logger?.LogTrace("Acquired semaphore {un}successfully", locked ? String.Empty : "un");
            return locked
                ? new SemaphoreSlimContext(semaphore, logger)
                : null;
        }
References Tgstation.Server.Host.Utils.SemaphoreSlimContext.logger.
Referenced by Tgstation.Server.Host.Components.StaticFiles.Configuration.CreateDirectory(), Tgstation.Server.Host.Components.StaticFiles.Configuration.DeleteDirectory(), Tgstation.Server.Host.Components.StaticFiles.Configuration.ListDirectory(), Tgstation.Server.Host.Components.StaticFiles.Configuration.Read(), and Tgstation.Server.Host.Components.StaticFiles.Configuration.Write().
Member Data Documentation
lockedSemaphore
readonly SemaphoreSlim Tgstation.Server.Host.Utils.SemaphoreSlimContext.lockedSemaphore private
The locked SemaphoreSlim.
Definition at line 55 of file SemaphoreSlimContext.cs.
Referenced by Tgstation.Server.Host.Utils.SemaphoreSlimContext.Dispose(), and Tgstation.Server.Host.Utils.SemaphoreSlimContext.SemaphoreSlimContext().
logger
readonly? ILogger Tgstation.Server.Host.Utils.SemaphoreSlimContext.logger private
An optional ILogger to write to.
Definition at line 50 of file SemaphoreSlimContext.cs.
Referenced by Tgstation.Server.Host.Utils.SemaphoreSlimContext.Dispose(), Tgstation.Server.Host.Utils.SemaphoreSlimContext.Lock(), Tgstation.Server.Host.Utils.SemaphoreSlimContext.SemaphoreSlimContext(), and Tgstation.Server.Host.Utils.SemaphoreSlimContext.TryLock().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Utils/SemaphoreSlimContext.cs