tgstation-server: TGControlPanel.Login Class Reference
TGControlPanel.Login Class Reference
Public Member Functions
Login ()
Create a Login form
Public Member Functions inherited from TGControlPanel.CountedForm
CountedForm ()
Construct a CountedForm. Increments FormCount
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void RemoteLoginButton_Click (object sender, EventArgs e)
void LocalLoginButton_Click (object sender, EventArgs e)
void VerifyAndConnect (IInterface I)
void SavePasswordCheckBox_CheckedChanged (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.Button LocalLoginButton
System.Windows.Forms.Label CurrentRevisionTitle
System.Windows.Forms.TextBox IPTextBox
System.Windows.Forms.TextBox UsernameTextBox
System.Windows.Forms.TextBox PasswordTextBox
System.Windows.Forms.Button RemoteLoginButton
System.Windows.Forms.Label label1
System.Windows.Forms.Label label2
System.Windows.Forms.Label label3
System.Windows.Forms.Label label4
System.Windows.Forms.NumericUpDown PortSelector
System.Windows.Forms.CheckBox SavePasswordCheckBox
Detailed Description
Definition at line 7 of file Login.cs.
Constructor & Destructor Documentation
TGControlPanel.Login.Login ()
Create a Login form
Definition at line 12 of file Login.cs.
References TGServiceInterface.Helpers.DecryptData(), TGControlPanel.Login.InitializeComponent(), TGControlPanel.Login.IPTextBox, TGControlPanel.Login.PasswordTextBox, TGControlPanel.Login.PortSelector, TGControlPanel.Login.RemoteLoginButton, TGControlPanel.Login.SavePasswordCheckBox, and TGControlPanel.Login.UsernameTextBox.
         {
             InitializeComponent();
             var Config = Properties.Settings.Default;
             IPTextBox.Text = Config.RemoteIP;
             UsernameTextBox.Text = Config.RemoteUsername;
             PortSelector.Value = Config.RemotePort;
             AcceptButton = RemoteLoginButton;
             if(Config.RemoteDefault)
                 RemoteLoginButton.TabIndex = 0; //make this the first thing selected when loading
             var decrypted = Helpers.DecryptData(Config.RemotePassword, Config.RemoteEntropy);
             if (decrypted != null)
             {
                 PasswordTextBox.Text = decrypted;
                 SavePasswordCheckBox.Checked = true;
             }
         }
Member Function Documentation
override void TGControlPanel.Login.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file Login.Designer.cs.
References TGControlPanel.Login.components.
         {
             if (disposing && (components != null))
             {
                 components.Dispose();
             }
             base.Dispose(disposing);
         }
void TGControlPanel.Login.InitializeComponent () private
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 29 of file Login.Designer.cs.
References TGControlPanel.Login.CurrentRevisionTitle, TGControlPanel.Login.IPTextBox, TGControlPanel.Login.label1, TGControlPanel.Login.label2, TGControlPanel.Login.label3, TGControlPanel.Login.label4, TGControlPanel.Login.LocalLoginButton, TGControlPanel.Login.LocalLoginButton_Click(), TGControlPanel.Login.PasswordTextBox, TGControlPanel.Login.PortSelector, TGControlPanel.Login.RemoteLoginButton, TGControlPanel.Login.RemoteLoginButton_Click(), TGControlPanel.Login.SavePasswordCheckBox, TGControlPanel.Login.SavePasswordCheckBox_CheckedChanged(), and TGControlPanel.Login.UsernameTextBox.
Referenced by TGControlPanel.Login.Login().
         {
             System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Login));
             this.LocalLoginButton = new System.Windows.Forms.Button();
             this.CurrentRevisionTitle = new System.Windows.Forms.Label();
             this.IPTextBox = new System.Windows.Forms.TextBox();
             this.UsernameTextBox = new System.Windows.Forms.TextBox();
             this.PasswordTextBox = new System.Windows.Forms.TextBox();
             this.RemoteLoginButton = new System.Windows.Forms.Button();
             this.label1 = new System.Windows.Forms.Label();
             this.label2 = new System.Windows.Forms.Label();
             this.label3 = new System.Windows.Forms.Label();
             this.label4 = new System.Windows.Forms.Label();
             this.PortSelector = new System.Windows.Forms.NumericUpDown();
             this.SavePasswordCheckBox = new System.Windows.Forms.CheckBox();
             ((System.ComponentModel.ISupportInitialize)(this.PortSelector)).BeginInit();
             this.SuspendLayout();
             //
             // LocalLoginButton
             //
             this.LocalLoginButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
             this.LocalLoginButton.Location = new System.Drawing.Point(102, 12);
             this.LocalLoginButton.Name = "LocalLoginButton";
             this.LocalLoginButton.Size = new System.Drawing.Size(157, 25);
             this.LocalLoginButton.TabIndex = 13;
             this.LocalLoginButton.Text = "Connect to Local Service";
             this.LocalLoginButton.UseVisualStyleBackColor = true;
             this.LocalLoginButton.Click += new System.EventHandler(this.LocalLoginButton_Click);
             //
             // CurrentRevisionTitle
             //
             this.CurrentRevisionTitle.AutoSize = true;
             this.CurrentRevisionTitle.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.CurrentRevisionTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.CurrentRevisionTitle.Location = new System.Drawing.Point(116, 69);
             this.CurrentRevisionTitle.Name = "CurrentRevisionTitle";
             this.CurrentRevisionTitle.Size = new System.Drawing.Size(128, 18);
             this.CurrentRevisionTitle.TabIndex = 14;
             this.CurrentRevisionTitle.Text = "Remote Login:";
             this.CurrentRevisionTitle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // IPTextBox
             //
             this.IPTextBox.Location = new System.Drawing.Point(129, 99);
             this.IPTextBox.Name = "IPTextBox";
             this.IPTextBox.Size = new System.Drawing.Size(146, 20);
             this.IPTextBox.TabIndex = 15;
             //
             // UsernameTextBox
             //
             this.UsernameTextBox.Location = new System.Drawing.Point(129, 132);
             this.UsernameTextBox.Name = "UsernameTextBox";
             this.UsernameTextBox.Size = new System.Drawing.Size(233, 20);
             this.UsernameTextBox.TabIndex = 16;
             //
             // PasswordTextBox
             //
             this.PasswordTextBox.Location = new System.Drawing.Point(129, 164);
             this.PasswordTextBox.Name = "PasswordTextBox";
             this.PasswordTextBox.Size = new System.Drawing.Size(233, 20);
             this.PasswordTextBox.TabIndex = 17;
             this.PasswordTextBox.UseSystemPasswordChar = true;
             //
             // RemoteLoginButton
             //
             this.RemoteLoginButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
             this.RemoteLoginButton.Location = new System.Drawing.Point(102, 200);
             this.RemoteLoginButton.Name = "RemoteLoginButton";
             this.RemoteLoginButton.Size = new System.Drawing.Size(157, 25);
             this.RemoteLoginButton.TabIndex = 18;
             this.RemoteLoginButton.Text = "Connect to Remote Service";
             this.RemoteLoginButton.UseVisualStyleBackColor = true;
             this.RemoteLoginButton.Click += new System.EventHandler(this.RemoteLoginButton_Click);
             //
             // label1
             //
             this.label1.AutoSize = true;
             this.label1.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.label1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.label1.Location = new System.Drawing.Point(9, 99);
             this.label1.Name = "label1";
             this.label1.Size = new System.Drawing.Size(120, 18);
             this.label1.TabIndex = 19;
             this.label1.Text = "Address/Port:";
             this.label1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // label2
             //
             this.label2.AutoSize = true;
             this.label2.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.label2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.label2.Location = new System.Drawing.Point(9, 132);
             this.label2.Name = "label2";
             this.label2.Size = new System.Drawing.Size(97, 18);
             this.label2.TabIndex = 20;
             this.label2.Text = "Username:";
             this.label2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // label3
             //
             this.label3.AutoSize = true;
             this.label3.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.label3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.label3.Location = new System.Drawing.Point(9, 164);
             this.label3.Name = "label3";
             this.label3.Size = new System.Drawing.Size(92, 18);
             this.label3.TabIndex = 21;
             this.label3.Text = "Password:";
             this.label3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // label4
             //
             this.label4.AutoSize = true;
             this.label4.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.label4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.label4.Location = new System.Drawing.Point(-19, 40);
             this.label4.Name = "label4";
             this.label4.Size = new System.Drawing.Size(468, 18);
             this.label4.TabIndex = 22;
             this.label4.Text = "______________________________________________";
             this.label4.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // PortSelector
             //
             this.PortSelector.Location = new System.Drawing.Point(282, 99);
             this.PortSelector.Maximum = new decimal(new int[] {
             65535,
             0,
             0,
             0});
             this.PortSelector.Minimum = new decimal(new int[] {
             1,
             0,
             0,
             0});
             this.PortSelector.Name = "PortSelector";
             this.PortSelector.Size = new System.Drawing.Size(80, 20);
             this.PortSelector.TabIndex = 16;
             this.PortSelector.Value = new decimal(new int[] {
             1,
             0,
             0,
             0});
             //
             // SavePasswordCheckBox
             //
             this.SavePasswordCheckBox.AutoSize = true;
             this.SavePasswordCheckBox.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.SavePasswordCheckBox.Location = new System.Drawing.Point(265, 205);
             this.SavePasswordCheckBox.Name = "SavePasswordCheckBox";
             this.SavePasswordCheckBox.Size = new System.Drawing.Size(100, 17);
             this.SavePasswordCheckBox.TabIndex = 23;
             this.SavePasswordCheckBox.Text = "Save Password";
             this.SavePasswordCheckBox.UseVisualStyleBackColor = true;
             this.SavePasswordCheckBox.CheckedChanged += new System.EventHandler(this.SavePasswordCheckBox_CheckedChanged);
             //
             // Login
             //
             this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
             this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
             this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(40)))), ((int)(((byte)(34)))));
             this.ClientSize = new System.Drawing.Size(374, 237);
             this.Controls.Add(this.SavePasswordCheckBox);
             this.Controls.Add(this.PortSelector);
             this.Controls.Add(this.label4);
             this.Controls.Add(this.label3);
             this.Controls.Add(this.label2);
             this.Controls.Add(this.label1);
             this.Controls.Add(this.RemoteLoginButton);
             this.Controls.Add(this.PasswordTextBox);
             this.Controls.Add(this.UsernameTextBox);
             this.Controls.Add(this.IPTextBox);
             this.Controls.Add(this.CurrentRevisionTitle);
             this.Controls.Add(this.LocalLoginButton);
             this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
             this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
             this.MaximizeBox = false;
             this.Name = "Login";
             this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
             this.Text = "Login";
             ((System.ComponentModel.ISupportInitialize)(this.PortSelector)).EndInit();
             this.ResumeLayout(false);
             this.PerformLayout();
         }
void TGControlPanel.Login.LocalLoginButton_Click (object sender, EventArgs e) private
Definition at line 55 of file Login.cs.
References TGControlPanel.Login.VerifyAndConnect().
Referenced by TGControlPanel.Login.InitializeComponent().
         {
             Properties.Settings.Default.RemoteDefault = false;
             VerifyAndConnect(new Interface());
         }
void TGControlPanel.Login.RemoteLoginButton_Click (object sender, EventArgs e) private
Definition at line 30 of file Login.cs.
References TGServiceInterface.Helpers.EncryptData(), TGControlPanel.Login.IPTextBox, TGControlPanel.Login.PasswordTextBox, TGControlPanel.Login.PortSelector, TGControlPanel.Login.SavePasswordCheckBox, TGControlPanel.Login.UsernameTextBox, and TGControlPanel.Login.VerifyAndConnect().
Referenced by TGControlPanel.Login.InitializeComponent().
         {
             IPTextBox.Text = IPTextBox.Text.Trim();
             UsernameTextBox.Text = UsernameTextBox.Text.Trim();
             using (var I = new Interface(IPTextBox.Text, (ushort)PortSelector.Value, UsernameTextBox.Text, PasswordTextBox.Text))
             {
                 var Config = Properties.Settings.Default;
                 Config.RemoteIP = IPTextBox.Text;
                 Config.RemotePort = (ushort)PortSelector.Value;
                 Config.RemoteUsername = UsernameTextBox.Text;
                 if (SavePasswordCheckBox.Checked)
                 {
                     Config.RemotePassword = Helpers.EncryptData(PasswordTextBox.Text, out string entrop);
                     Config.RemoteEntropy = entrop;
                 }
                 else
                 {
                     Config.RemotePassword = null;
                     Config.RemoteEntropy = null;
                 }
                 Config.RemoteDefault = true;
                 VerifyAndConnect(I);
             }
         }
void TGControlPanel.Login.SavePasswordCheckBox_CheckedChanged (object sender, EventArgs e) private
Definition at line 107 of file Login.cs.
References TGControlPanel.Login.SavePasswordCheckBox.
Referenced by TGControlPanel.Login.InitializeComponent().
         {
             if (!SavePasswordCheckBox.Checked)
             {
                 var Config = Properties.Settings.Default;
                 Config.RemotePassword = null;
                 Config.RemoteEntropy = null;
             }
         }
void TGControlPanel.Login.VerifyAndConnect (IInterface I) private
Definition at line 61 of file Login.cs.
References TGServiceInterface.IInterface.ConnectionStatus(), TGServiceInterface.IInterface.ConnectToInstance(), and TGControlPanel.Program.TextPrompt().
Referenced by TGControlPanel.Login.LocalLoginButton_Click(), and TGControlPanel.Login.RemoteLoginButton_Click().
         {
             try
             {
                 var res = I.ConnectionStatus(out string error);
                 if (!res.HasFlag(ConnectivityLevel.Connected))
                 {
                     MessageBox.Show("Unable to connect to service! Error: " + error);
                     return;
                 }
                 if (!res.HasFlag(ConnectivityLevel.Authenticated))
                 {
                     MessageBox.Show("Authentication error: Username/password/windows identity is not authorized! Ensure you are a system administrator or in the correct Windows group on the service machine.");
                     return;
                 }
                 if (!res.HasFlag(ConnectivityLevel.Administrator))
                 {
                     while (true)
                     {
                         var InstanceToConnectTo = Program.TextPrompt("Select instance", "You do not have permission to list server instances. Please enter the name of the instance to connect to:");
                         if (InstanceToConnectTo == null)
                             return;
                         res = I.ConnectToInstance(InstanceToConnectTo);
                         if (!res.HasFlag(ConnectivityLevel.Connected))
                             MessageBox.Show("Unable to connect to instance! Does it exist?");
                         else if (!res.HasFlag(ConnectivityLevel.Authenticated))
                             MessageBox.Show("The current user is not authorized to access this instance!");
                         else
                             break;
                     }
                     new ControlPanel(I).Show();
                 }
                 else
                     new InstanceSelector(I).Show();
                 Close();
             }
             catch
             {
                 I.Dispose();
                 throw;
             }
         }
Member Data Documentation
System.ComponentModel.IContainer TGControlPanel.Login.components = null private
Required designer variable.
Definition at line 8 of file Login.Designer.cs.
Referenced by TGControlPanel.Login.Dispose().
System.Windows.Forms.Label TGControlPanel.Login.CurrentRevisionTitle private
Definition at line 218 of file Login.Designer.cs.
Referenced by TGControlPanel.Login.InitializeComponent().
System.Windows.Forms.TextBox TGControlPanel.Login.IPTextBox private
Definition at line 219 of file Login.Designer.cs.
Referenced by TGControlPanel.Login.InitializeComponent(), TGControlPanel.Login.Login(), and TGControlPanel.Login.RemoteLoginButton_Click().
System.Windows.Forms.Label TGControlPanel.Login.label1 private
Definition at line 223 of file Login.Designer.cs.
Referenced by TGControlPanel.Login.InitializeComponent().
System.Windows.Forms.Label TGControlPanel.Login.label2 private
Definition at line 224 of file Login.Designer.cs.
Referenced by TGControlPanel.Login.InitializeComponent().
System.Windows.Forms.Label TGControlPanel.Login.label3 private
Definition at line 225 of file Login.Designer.cs.
Referenced by TGControlPanel.Login.InitializeComponent().
System.Windows.Forms.Label TGControlPanel.Login.label4 private
Definition at line 226 of file Login.Designer.cs.
Referenced by TGControlPanel.Login.InitializeComponent().
System.Windows.Forms.Button TGControlPanel.Login.LocalLoginButton private
Definition at line 217 of file Login.Designer.cs.
Referenced by TGControlPanel.Login.InitializeComponent().
System.Windows.Forms.TextBox TGControlPanel.Login.PasswordTextBox private
Definition at line 221 of file Login.Designer.cs.
Referenced by TGControlPanel.Login.InitializeComponent(), TGControlPanel.Login.Login(), and TGControlPanel.Login.RemoteLoginButton_Click().
System.Windows.Forms.NumericUpDown TGControlPanel.Login.PortSelector private
Definition at line 227 of file Login.Designer.cs.
Referenced by TGControlPanel.Login.InitializeComponent(), TGControlPanel.Login.Login(), and TGControlPanel.Login.RemoteLoginButton_Click().
System.Windows.Forms.Button TGControlPanel.Login.RemoteLoginButton private
Definition at line 222 of file Login.Designer.cs.
Referenced by TGControlPanel.Login.InitializeComponent(), and TGControlPanel.Login.Login().
System.Windows.Forms.CheckBox TGControlPanel.Login.SavePasswordCheckBox private
Definition at line 228 of file Login.Designer.cs.
Referenced by TGControlPanel.Login.InitializeComponent(), TGControlPanel.Login.Login(), TGControlPanel.Login.RemoteLoginButton_Click(), and TGControlPanel.Login.SavePasswordCheckBox_CheckedChanged().
System.Windows.Forms.TextBox TGControlPanel.Login.UsernameTextBox private
Definition at line 220 of file Login.Designer.cs.
Referenced by TGControlPanel.Login.InitializeComponent(), TGControlPanel.Login.Login(), and TGControlPanel.Login.RemoteLoginButton_Click().
The documentation for this class was generated from the following files:
TGControlPanel/Login.cs
TGControlPanel/Login.Designer.cs