tgstation-server: Tgstation.Server.Host.Controllers.JobController Class Reference
Tgstation.Server.Host.Controllers.JobController Class Reference sealed
ApiController for Jobs.
Public Member Functions
JobController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ILogger< JobController > logger, IInstanceManager instanceManager, IJobManager jobManager, IApiHeadersProvider apiHeaders)
Initializes a new instance of the JobController class.
ValueTask< IActionResult > Read ([FromQuery] int? page, [FromQuery] int? pageSize, CancellationToken cancellationToken)
Get active JobResponses for the instance.
ValueTask< IActionResult > List ([FromQuery] int? page, [FromQuery] int? pageSize, CancellationToken cancellationToken)
List all JobResponse for the instance in reverse creation order.
async ValueTask< IActionResult > Delete (long id, CancellationToken cancellationToken)
Cancel a running JobResponse.
async ValueTask< IActionResult > GetId (long id, CancellationToken cancellationToken)
Get a specific JobResponse.
Public Member Functions inherited from Tgstation.Server.Host.Controllers.ApiControllerBase
override async Task OnActionExecutionAsync (ActionExecutingContext context, ActionExecutionDelegate next)
Private Member Functions
ValueTask< IActionResult > JobResponse (()=> ValueTask.FromResult(new PaginatableResult< Job >(DatabaseContext .Jobs .AsQueryable() .Include(x=> x.StartedBy) .Include(x=> x.CancelledBy) .Include(x=> x.Instance) .Where(x=> x.Instance!.Id==Instance.Id &&!x.StoppedAt.HasValue) .OrderByDescending(x=> x.StartedAt))), AddJobProgressResponseTransformer, page, pageSize, cancellationToken)
ValueTask< IActionResult > JobResponse (()=> ValueTask.FromResult(new PaginatableResult< Job >(DatabaseContext .Jobs .AsQueryable() .Include(x=> x.StartedBy) .Include(x=> x.CancelledBy) .Include(x=> x.Instance) .Where(x=> x.Instance!.Id==Instance.Id) .OrderByDescending(x=> x.StartedAt))), AddJobProgressResponseTransformer, page, pageSize, cancellationToken)
ValueTask AddJobProgressResponseTransformer (JobResponse jobResponse)
Supplements JobResponse PaginatedResponse<TModel>s with their JobResponse.Progress.
Private Attributes
readonly IJobManager jobManager
The IJobManager for the JobController.
Additional Inherited Members
Static Public Attributes inherited from Tgstation.Server.Host.Controllers.ApiController
const ushort DefaultPageSize = 10
Default size of Paginated<TModel> results.
const ushort MaximumPageSize = 100
Maximum size of Paginated<TModel> results.
Protected Member Functions inherited from Tgstation.Server.Host.Controllers.InstanceRequiredController
InstanceRequiredController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ILogger< InstanceRequiredController > logger, IInstanceManager instanceManager, IApiHeadersProvider apiHeaders)
Initializes a new instance of the InstanceRequiredController class.
Protected Member Functions inherited from Tgstation.Server.Host.Controllers.ComponentInterfacingController
ComponentInterfacingController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ILogger< ComponentInterfacingController > logger, IInstanceManager instanceManager, IApiHeadersProvider apiHeaders, bool useInstanceRequestHeader)
Initializes a new instance of the ComponentInterfacingController class.
override async ValueTask< IActionResult?> ValidateRequest (CancellationToken cancellationToken)
Performs validation a request.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in an appropriate IActionResult on validation failure, null otherwise.
bool ValidateInstanceOnlineStatus (Api.Models.Instance metadata)
Corrects discrepencies between the Api.Models.Instance.Online status of IInstances in the database vs the service.
async ValueTask< IActionResult?> WithComponentInstanceNullable (Func< IInstanceCore, ValueTask< IActionResult?> > action, Models.Instance? instance=null)
Run a given action with the relevant IInstance.
async ValueTask< IActionResult > WithComponentInstance (Func< IInstanceCore, ValueTask< IActionResult > > action, Models.Instance? instance=null)
Run a given action with the relevant IInstance.
Protected Member Functions inherited from Tgstation.Server.Host.Controllers.ApiController
ApiController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, IApiHeadersProvider apiHeadersProvider, ILogger< ApiController > logger, bool requireHeaders)
Initializes a new instance of the ApiController class.
override async ValueTask< IActionResult?> HookExecuteAction (Func< Task > executeAction, CancellationToken cancellationToken)
Hook for executing a request.
Parameters
executeAction A Func<TResult> that should be invoked and its response awaited to continue normal execution of the request. Should NOT be called if this method returns a non-null value.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in an IActionResult that, if not null, is executed.
new NotFoundObjectResult NotFound ()
Generic 404 response.
StatusCodeResult StatusCode (HttpStatusCode statusCode)
Strongly type calls to ControllerBase.StatusCode(int).
ObjectResult RateLimit (RateLimitExceededException rateLimitException)
429 response for a given rateLimitException .
IActionResult HeadersIssue (HeadersException headersException)
Response for missing/Invalid headers.
ValueTask< IActionResult > Paginated< TModel > (Func< ValueTask< PaginatableResult< TModel > > > queryGenerator, Func< TModel, ValueTask >? resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
ValueTask< IActionResult > Paginated< TModel, TApiModel > (Func< ValueTask< PaginatableResult< TModel > > > queryGenerator, Func< TApiModel, ValueTask >? resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
Properties inherited from Tgstation.Server.Host.Controllers.InstanceRequiredController
new Models.Instance Instance [get]
The ApiController.Instance.
Models.InstancePermissionSet InstancePermissionSet [get]
The Models.InstancePermissionSet for the request.
Properties inherited from Tgstation.Server.Host.Controllers.ComponentInterfacingController
IInstanceOperations InstanceOperations [get]
Access the IInstanceOperations instance.
Properties inherited from Tgstation.Server.Host.Controllers.ApiController
ApiHeaders? ApiHeaders [get]
The Api.ApiHeaders for the operation.
IApiHeadersProvider ApiHeadersProvider [get]
The IApiHeadersProvider containing value of ApiHeaders.
IDatabaseContext DatabaseContext [get]
The IDatabaseContext for the operation.
IAuthenticationContext AuthenticationContext [get]
The IAuthenticationContext for the operation.
ILogger< ApiController > Logger [get]
The ILogger for the ApiController.
Models.? Instance Instance [get]
The Instance for the operation.
Detailed Description
ApiController for Jobs.
Definition at line 28 of file JobController.cs.
Constructor & Destructor Documentation
JobController()
Tgstation.Server.Host.Controllers.JobController.JobController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ILogger< JobController > logger, IInstanceManager instanceManager, IJobManager jobManager, IApiHeadersProvider apiHeaders)
Initializes a new instance of the JobController class.
Parameters
databaseContext The IDatabaseContext for the InstanceRequiredController.
authenticationContext The IAuthenticationContext for the InstanceRequiredController.
logger The ILogger for the InstanceRequiredController.
instanceManager The IInstanceManager for the InstanceRequiredController.
jobManager The value of jobManager.
apiHeaders The IApiHeadersProvider for the InstanceRequiredController.
Definition at line 44 of file JobController.cs.
            : base(
                  databaseContext,
                  authenticationContext,
                  logger,
                  instanceManager,
                  apiHeaders)
        {
            this.jobManager = jobManager ?? throw new ArgumentNullException(nameof(jobManager));
        }
References Tgstation.Server.Host.Controllers.JobController.jobManager, and Tgstation.Server.Host.Controllers.JobController.List().
Member Function Documentation
AddJobProgressResponseTransformer()
ValueTask Tgstation.Server.Host.Controllers.JobController.AddJobProgressResponseTransformer (JobResponse jobResponse) private
Supplements JobResponse PaginatedResponse<TModel>s with their JobResponse.Progress.
Parameters
jobResponse The JobResponse to augment.
Returns
A ValueTask representing the running operation.
Definition at line 187 of file JobController.cs.
        {
            jobManager.SetJobProgress(jobResponse);
            return ValueTask.CompletedTask;
        }
References Tgstation.Server.Host.Controllers.JobController.jobManager, Tgstation.Server.Host.Controllers.JobController.List(), and Tgstation.Server.Host.Jobs.IJobManager.SetJobProgress().
Delete()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.JobController.Delete (long id, CancellationToken cancellationToken)
Cancel a running JobResponse.
Parameters
id The EntityId.Id of the JobResponse to cancel.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the request.
<response code="202">Job cancellation requested successfully.</response> <response code="404">Job does not exist in this instance.</response> <response code="410">Job could not be found in the job manager. Has it already completed?.</response>
Definition at line 130 of file JobController.cs.
        {
            // don't care if an instance post or not at this point
            var job = await DatabaseContext
                .Jobs
                .AsQueryable()
                .Include(x => x.StartedBy)
                .Include(x => x.Instance)
                .Where(x => x.Id == id && x.Instance!.Id == Instance.Id)
                .FirstOrDefaultAsync(cancellationToken);
            if (job == default)
                return NotFound();
            if (job.StoppedAt != null)
                return Conflict(new ErrorMessageResponse(ErrorCode.JobStopped));
            if (job.CancelRight.HasValue && job.CancelRightsType.HasValue && (AuthenticationContext.GetRight(job.CancelRightsType.Value) & job.CancelRight.Value) == 0)
                return Forbid();
            var updatedJob = await jobManager.CancelJob(job, AuthenticationContext.User, false, cancellationToken);
            return updatedJob != null ? Accepted(updatedJob.ToApi()) : this.Gone();
        }
References Tgstation.Server.Host.Jobs.IJobManager.CancelJob(), Tgstation.Server.Host.Security.AuthenticationContext.GetRight(), Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Host.Controllers.JobController.jobManager, Tgstation.Server.Host.Database.DatabaseContext.Jobs, Tgstation.Server.Host.Controllers.JobController.List(), Tgstation.Server.Host.Controllers.ApiController.NotFound(), and Tgstation.Server.Host.Security.AuthenticationContext.User.
GetId()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.JobController.GetId (long id, CancellationToken cancellationToken)
Get a specific JobResponse.
Parameters
id The EntityId.Id of the JobResponse to retrieve.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the request.
<response code="200">Retrieved Job successfully.</response> <response code="404">Job does not exist in this instance.</response>
Definition at line 165 of file JobController.cs.
        {
            var job = await DatabaseContext
                .Jobs
                .AsQueryable()
                .Where(x => x.Id == id && x.Instance!.Id == Instance.Id)
                .Include(x => x.StartedBy)
                .Include(x => x.CancelledBy)
                .Include(x => x.Instance)
                .FirstOrDefaultAsync(cancellationToken);
            if (job == default)
                return NotFound();
            var api = job.ToApi();
            jobManager.SetJobProgress(api);
            return Json(api);
        }
References Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Host.Controllers.JobController.jobManager, Tgstation.Server.Host.Database.DatabaseContext.Jobs, Tgstation.Server.Host.Controllers.JobController.List(), Tgstation.Server.Host.Controllers.ApiController.NotFound(), and Tgstation.Server.Host.Jobs.IJobManager.SetJobProgress().
JobResponse() [1/2]
ValueTask< IActionResult > Tgstation.Server.Host.Controllers.JobController.JobResponse (() , ValueTask. FromResultnew PaginatableResult< Job >(DatabaseContext .Jobs .AsQueryable() .Include(x=> x.StartedBy) .Include(x=> x.CancelledBy) .Include(x=> x.Instance) .Where(x=> x.Instance!.Id==Instance.Id &&!x.StoppedAt.HasValue) .OrderByDescending(x=> x.StartedAt)), AddJobProgressResponseTransformer , page , pageSize , cancellationToken) private
JobResponse() [2/2]
ValueTask< IActionResult > Tgstation.Server.Host.Controllers.JobController.JobResponse (() , ValueTask. FromResultnew PaginatableResult< Job >(DatabaseContext .Jobs .AsQueryable() .Include(x=> x.StartedBy) .Include(x=> x.CancelledBy) .Include(x=> x.Instance) .Where(x=> x.Instance!.Id==Instance.Id) .OrderByDescending(x=> x.StartedAt)), AddJobProgressResponseTransformer , page , pageSize , cancellationToken) private
List()
ValueTask< IActionResult > Tgstation.Server.Host.Controllers.JobController.List ([FromQuery] int? page, [FromQuery] int? pageSize, CancellationToken cancellationToken)
List all JobResponse for the instance in reverse creation order.
Parameters
page The current page.
pageSize The page size.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the request.
<response code="200">Retrieved Job EntityIds successfully.</response>
Referenced by Tgstation.Server.Host.Controllers.JobController.AddJobProgressResponseTransformer(), Tgstation.Server.Host.Controllers.JobController.Delete(), Tgstation.Server.Host.Controllers.JobController.GetId(), and Tgstation.Server.Host.Controllers.JobController.JobController().
Read()
ValueTask< IActionResult > Tgstation.Server.Host.Controllers.JobController.Read ([FromQuery] int? page, [FromQuery] int? pageSize, CancellationToken cancellationToken)
Get active JobResponses for the instance.
Parameters
page The current page.
pageSize The page size.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the request.
<response code="200">Retrieved active Jobs successfully.</response>
Member Data Documentation
jobManager
readonly IJobManager Tgstation.Server.Host.Controllers.JobController.jobManager private
The IJobManager for the JobController.
Definition at line 33 of file JobController.cs.
Referenced by Tgstation.Server.Host.Controllers.JobController.AddJobProgressResponseTransformer(), Tgstation.Server.Host.Controllers.JobController.Delete(), Tgstation.Server.Host.Controllers.JobController.GetId(), and Tgstation.Server.Host.Controllers.JobController.JobController().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Controllers/JobController.cs