tgstation-server: TGCommandLine.Program Class Reference
TGCommandLine.Program Class Reference
Static Public Member Functions
static string ReadLineSecure ()
Static Private Member Functions
static Command.ExitCode RunCommandLine (IList< string > argsAsList)
static void ReplaceInterface (Interface I)
static bool BadCertificateInteractive (string message)
static int Main (string[] args)
Static Private Attributes
static Interface currentInterface
static bool SentVMMWarning = false
static string AcceptedBadCert
Detailed Description
Definition at line 10 of file Program.cs.
Member Function Documentation
static bool TGCommandLine.Program.BadCertificateInteractive (string message) static private
Definition at line 132 of file Program.cs.
Referenced by TGCommandLine.Program.Main().
         {
             if (AcceptedBadCert == message)
                 return true;
             Console.WriteLine(message);
             Console.Write("Do you wish to continue? NOT RECCOMENDED! (y/N): ");
             var result = Console.ReadLine().Trim().ToLower();
             if (result == "y" || result == "yes")
             {
                 AcceptedBadCert = message;
                 return true;
             }
             return false;
         }
static int TGCommandLine.Program.Main (string[] args) static private
Definition at line 147 of file Program.cs.
References TGServiceInterface.Interface.Authenticate(), TGCommandLine.Program.BadCertificateInteractive(), TGServiceInterface.Command.OutputProcVar, TGCommandLine.Program.ReadLineSecure(), TGCommandLine.Program.ReplaceInterface(), TGCommandLine.Program.RunCommandLine(), TGServiceInterface.Interface.SetBadCertificateHandler(), TGServiceInterface.Interface.VerifyConnection(), and TGServiceInterface.Interface.VersionMismatch().
         {
             ReplaceInterface(new Interface());
             Command.OutputProcVar.Value = Console.WriteLine;
             if (args.Length != 0)
             {
                 Interface.SetBadCertificateHandler((message) =>
                 {
                     foreach (var J in args)
                         if (J.ToLower() == "--disable-ssl-verification")    //im just not even going to document this because i hate it so much
                             return true;
                     return false;
                 });
                 return (int)RunCommandLine(new List<string>(args));
             }
             //interactive mode
             Interface.SetBadCertificateHandler(BadCertificateInteractive);
             Console.WriteLine("Type 'remote' to connect to a remote service");
             while (true)
             {
                 Console.Write("Enter command: ");
                 var NextCommand = Console.ReadLine();
                 switch (NextCommand.ToLower())
                 {
                     case "remote":
                         SentVMMWarning = false;
                         Console.Write("Enter server address: ");
                         var address = Console.ReadLine();
                         Console.Write("Enter server port: ");
                         ushort port;
                         try{
                             port = Convert.ToUInt16(Console.ReadLine());
                         }
                         catch
{
                             Console.WriteLine("Error: Bad port!");
                             break;
                         }
                         Console.Write("Enter username: ");
                         var username = Console.ReadLine();
                         Console.Write("Enter password: ");
                         var password = ReadLineSecure();
                         ReplaceInterface(new Interface(address, port, username, password));
                         var res = currentInterface.VerifyConnection();
                         if (res != null)
{
                             Console.WriteLine("Unable to connect: " + res);
                             ReplaceInterface(new Interface());
                         }
                         else if (!currentInterface.Authenticate())
{
                             Console.WriteLine("Authentication error: Username/password/windows identity is not authorized! Returning to local mode...");
                             ReplaceInterface(new Interface());
                         }
                         else
{
                             Console.WriteLine("Connected remotely");
                             if (currentInterface.VersionMismatch(out res))
{
                                 SentVMMWarning = true;
                                 Console.WriteLine(res);
                             }
                             Console.WriteLine("Type 'disconnect' to return to local mode");
                         }
                         break;
                     case "disconnect":
                         SentVMMWarning = false;
                         ReplaceInterface(new Interface());
                         Console.WriteLine("Switch to local mode");
                         break;
                     case "quit":
                     case "exit":
                         return (int)Command.ExitCode.Normal;
 #if DEBUG
                     case "debug-upgrade":
                         currentInterface.GetComponent<ITGSService>().PrepareForUpdate();
                         return (int)Command.ExitCode.Normal;
 #endif
                     default:
                         //linq voodoo to get quoted strings
                         var formattedCommand = NextCommand.Split('"')
                                            .Select((element, index) => index % 2 == 0  // If even index
                                            ? element.Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries)  // Split the item
                                            : new string[] { element })  // Keep the entire item
                                            .SelectMany(element => element).ToList();
                         formattedCommand = formattedCommand.Select(x => x.Trim()).ToList();
                         formattedCommand.Remove("");
                         RunCommandLine(formattedCommand);
                         break;
                 }
             }
         }
static string TGCommandLine.Program.ReadLineSecure () static
Definition at line 103 of file Program.cs.
Referenced by TGCommandLine.Program.Main().
         {
             string result = "";
             while (true)
             {
                 ConsoleKeyInfo i = Console.ReadKey(true);
                 if (i.Key == ConsoleKey.Enter)
                 {
                     break;
                 }
                 else if (i.Key == ConsoleKey.Backspace)
                 {
                     if (result.Length > 0)
                     {
                         result = result.Substring(0, result.Length - 1);
                         Console.Write("\b \b");
                     }
                 }
                 else
                 {
                     result += i.KeyChar;
                     Console.Write("*");
                 }
             }
             Console.WriteLine();
             return result;
         }
static void TGCommandLine.Program.ReplaceInterface (Interface I) static private
Definition at line 97 of file Program.cs.
References TGCommandLine.ConsoleCommand.Interface.
Referenced by TGCommandLine.Program.Main(), and TGCommandLine.Program.RunCommandLine().
         {
             currentInterface = I;
             ConsoleCommand.Interface = I;
         }
static Command.ExitCode TGCommandLine.Program.RunCommandLine (IList< string > argsAsList) static private
Definition at line 13 of file Program.cs.
References TGServiceInterface.Interface.Authenticate(), TGServiceInterface.Command.DoRun(), TGCommandLine.Program.ReplaceInterface(), TGCommandLine.Program.SentVMMWarning, TGServiceInterface.Interface.VerifyConnection(), and TGServiceInterface.Interface.VersionMismatch().
Referenced by TGCommandLine.Program.Main().
         {
             //first lookup the connection string
             bool badConnectionString = false;
             for (var I = 0; I < argsAsList.Count - 1; ++I) {
                 var lowerarg = argsAsList[I].ToLower();
                 if (lowerarg == "-c" || lowerarg == "--connect")
                 {
                     var connectionString = argsAsList[I + 1];
                     var splits = connectionString.Split('@');
                     var userpass = splits[0].Split(':');
                     if (splits.Length != 2 || userpass.Length != 2)
                     {
                         badConnectionString = true;
                         break;
                     }
                     var addrport = splits[1].Split(':');
                     if (addrport.Length != 2)
                     {
                         badConnectionString = true;
                         break;
                     }
                     var username = userpass[0];
                     var password = userpass[1];
                     var address = addrport[0];
                     ushort port;
                     try
                     {
                         port = Convert.ToUInt16(addrport[1]);
                     }
                     catch
                     {
                         badConnectionString = true;
                         break;
                     }
                     if(String.IsNullOrWhiteSpace(username) || String.IsNullOrWhiteSpace(password) || String.IsNullOrWhiteSpace(address))
                     {
                         badConnectionString = true;
                         break;
                     }
                     argsAsList.RemoveAt(I);
                     argsAsList.RemoveAt(I);
                     ReplaceInterface(new Interface(address, port, username, password));
                     break;
                 }
             }
             if (badConnectionString)
             {
                 Console.WriteLine("Remote connection usage: <-c/--connect> username:password@address:port");
                 return Command.ExitCode.BadCommand;
             }
             var res = currentInterface.VerifyConnection();
             if (res != null)
             {
                 Console.WriteLine("Unable to connect to service: " + res);
                 Console.WriteLine("Remote connection usage: <-c/--connect> username:password@address:port");
                 return Command.ExitCode.ConnectionError;
             }
             if (!currentInterface.Authenticate())
             {
                 Console.WriteLine("Authentication error: Username/password/windows identity is not authorized!");
                 return Command.ExitCode.ConnectionError;
             }
             if (!SentVMMWarning && currentInterface.VersionMismatch(out string error))
             {
                 SentVMMWarning = true;
                 Console.WriteLine(error);
             }
             try
             {
                 return new CLICommand(currentInterface).DoRun(argsAsList);
             }
             catch (Exception e)
             {
                 Console.WriteLine("Error: " + e.ToString());
                 return Command.ExitCode.ConnectionError;
             };
         }
Member Data Documentation
string TGCommandLine.Program.AcceptedBadCert static private
Definition at line 131 of file Program.cs.
Interface TGCommandLine.Program.currentInterface static private
Definition at line 12 of file Program.cs.
bool TGCommandLine.Program.SentVMMWarning = false static private
Definition at line 130 of file Program.cs.
Referenced by TGCommandLine.Program.RunCommandLine().
The documentation for this class was generated from the following file:
TGCommandLine/Program.cs