tgstation-server: Tgstation.Server.Host.Security.TokenFactory Class Reference
Tgstation.Server.Host.Security.TokenFactory Class Reference
Public Member Functions
Token CreateToken (Models.User user)
Create a Token for a given user
Static Public Attributes
static readonly string TokenAudience = typeof(Token).Assembly.GetName().Name
static readonly string TokenIssuer = Assembly.GetExecutingAssembly().GetName().Name
static readonly byte[] TokenSigningKey = CryptographySuite.GetSecureBytes(256)
Private Attributes
const int TokenExpiryMinutes = 15
Amount of minutes until generated Tokens expire
Detailed Description
Definition at line 12 of file TokenFactory.cs.
Member Function Documentation
Token Tgstation.Server.Host.Security.TokenFactory.CreateToken (Models.User user)
Create a Token for a given user
Implements Tgstation.Server.Host.Security.ITokenFactory.
Definition at line 24 of file TokenFactory.cs.
         {
             if (user == null)
                 throw new ArgumentNullException(nameof(user));
             var expiry = DateTimeOffset.Now.AddMinutes(TokenExpiryMinutes);
             var claims = new Claim[]
             {
                 new Claim(JwtRegisteredClaimNames.Sub, user.Id.ToString(CultureInfo.InvariantCulture)),
                 new Claim(JwtRegisteredClaimNames.Exp, $"{expiry.ToUnixTimeSeconds()}"),
                 new Claim(JwtRegisteredClaimNames.Nbf, $"{DateTimeOffset.Now.ToUnixTimeSeconds()}"),
                 new Claim(JwtRegisteredClaimNames.Iss, TokenIssuer),
                 new Claim(JwtRegisteredClaimNames.Aud, TokenAudience)
             };
             var key = new SymmetricSecurityKey(TokenSigningKey);
             var token = new JwtSecurityToken(new JwtHeader(new SigningCredentials(key, SecurityAlgorithms.HmacSha256)), new JwtPayload(claims));
             return new Token { Bearer = new JwtSecurityTokenHandler().WriteToken(token), ExpiresAt = expiry };
         }
Member Data Documentation
readonly string Tgstation.Server.Host.Security.TokenFactory.TokenAudience = typeof(Token).Assembly.GetName().Name static
Definition at line 19 of file TokenFactory.cs.
Referenced by Tgstation.Server.Host.Core.Application.ConfigureServices().
const int Tgstation.Server.Host.Security.TokenFactory.TokenExpiryMinutes = 15 private
Amount of minutes until generated Tokens expire
Definition at line 17 of file TokenFactory.cs.
readonly string Tgstation.Server.Host.Security.TokenFactory.TokenIssuer = Assembly.GetExecutingAssembly().GetName().Name static
Definition at line 20 of file TokenFactory.cs.
Referenced by Tgstation.Server.Host.Core.Application.ConfigureServices().
readonly byte [] Tgstation.Server.Host.Security.TokenFactory.TokenSigningKey = CryptographySuite.GetSecureBytes(256) static
Definition at line 21 of file TokenFactory.cs.
Referenced by Tgstation.Server.Host.Core.Application.ConfigureServices().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Security/TokenFactory.cs