tgstation-server: Tgstation.Server.Host.Authority.LoginAuthority Class Reference
Tgstation.Server.Host.Authority.LoginAuthority Class Reference sealed
Public Member Functions
LoginAuthority (IDatabaseContext databaseContext, ILogger< LoginAuthority > logger, IApiHeadersProvider apiHeadersProvider, ISystemIdentityFactory systemIdentityFactory, IOAuthProviders oAuthProviders, ITokenFactory tokenFactory, ICryptographySuite cryptographySuite, IIdentityCache identityCache, ISessionInvalidationTracker sessionInvalidationTracker, IOptionsSnapshot< SecurityConfiguration > securityConfigurationOptions)
Initializes a new instance of the LoginAuthority class.
RequirementsGated< AuthorityResponse< LoginResult > > AttemptLogin (CancellationToken cancellationToken)
Attempt to login to the server with the current Basic or OAuth credentials.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a LoginResult AuthorityResponse<TResult>.
RequirementsGated< AuthorityResponse< OAuthGatewayLoginResult > > AttemptOAuthGatewayLogin (CancellationToken cancellationToken)
Attempt to login to an OAuth service with the current OAuth credentials.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in an OAuthGatewayLoginResult AuthorityResponse<TResult>.
Private Member Functions
async ValueTask< AuthorityResponse< LoginResult > > AttemptLoginImpl (CancellationToken cancellationToken)
Login process.
async ValueTask CacheSystemIdentity (ISystemIdentity systemIdentity, User user, LoginResult loginPayload)
Add a given systemIdentity to the identityCache.
async ValueTask<(AuthorityResponse< TResult >? ErrorResponse,(string? UserID, string AccessCode)? OAuthResult)> TryOAuthenticate< TResult > (ApiHeaders headers, OAuthProvider oAuthProvider, bool forLogin, CancellationToken cancellationToken)
Attempt OAuth authentication.
Static Private Member Functions
static AuthorityResponse< TResult > GenerateHeadersExceptionResponse< TResult > (HeadersException headersException)
Generate an AuthorityResponse<TResult> for a given headersException .
static async ValueTask< User?> SelectUserInfoFromQuery (IQueryable< User > query, CancellationToken cancellationToken)
Select the details needed to generate a TokenResponse from a given query .
Private Attributes
readonly IApiHeadersProvider apiHeadersProvider
The IApiHeadersProvider for the LoginAuthority.
readonly ISystemIdentityFactory systemIdentityFactory
The ISystemIdentityFactory for the LoginAuthority.
readonly IOAuthProviders oAuthProviders
The IOAuthProviders for the LoginAuthority.
readonly ITokenFactory tokenFactory
The ITokenFactory for the LoginAuthority.
readonly ICryptographySuite cryptographySuite
The ICryptographySuite for the LoginAuthority.
readonly IIdentityCache identityCache
The IIdentityCache for the LoginAuthority.
readonly ISessionInvalidationTracker sessionInvalidationTracker
The ISessionInvalidationTracker for the LoginAuthority.
readonly IOptionsSnapshot< SecurityConfiguration > securityConfigurationOptions
The IOptionsSnapshot<TOptions> containing the SecurityConfiguration for the LoginAuthority.
Additional Inherited Members
Protected Member Functions inherited from Tgstation.Server.Host.Authority.Core.AuthorityBase
AuthorityBase (IDatabaseContext databaseContext, ILogger< AuthorityBase > logger)
Initializes a new instance of the AuthorityBase class.
AuthorityResponse< TResult > RateLimit< TResult > (RateLimitExceededException rateLimitException)
Generates a HttpFailureResponse.RateLimited type AuthorityResponse.
Static Protected Member Functions inherited from Tgstation.Server.Host.Authority.Core.AuthorityBase
static AuthorityResponse< TResult > BadRequest< TResult > (ErrorCode errorCode)
Generates a HttpFailureResponse.BadRequest type AuthorityResponse<TResult>.
static AuthorityResponse< TResult > Unauthorized< TResult > ()
Generates a HttpFailureResponse.Unauthorized type AuthorityResponse<TResult>.
static AuthorityResponse< TResult > Gone< TResult > ()
Generates a HttpFailureResponse.Forbidden type AuthorityResponse<TResult>.
static AuthorityResponse< TResult > Forbid< TResult > ()
Generates a HttpFailureResponse.Forbidden type AuthorityResponse<TResult>.
static AuthorityResponse< TResult > NotFound< TResult > ()
Generates a HttpFailureResponse.NotFound type AuthorityResponse<TResult>.
static AuthorityResponse< TResult > Conflict< TResult > (ErrorCode errorCode, string? additionalData=null)
Generates a HttpFailureResponse.Conflict type AuthorityResponse<TResult>.
static FlagRightsConditional< TRights > Flag< TRights > (TRights flag)
Helper to quickly construct a FlagRightsConditional<TRights>.
static OrRightsConditional< TRights > Or< TRights > (RightsConditional< TRights > lhs, RightsConditional< TRights > rhs)
Helper to quickly construct an OrRightsConditional<TRights>.
static AndRightsConditional< TRights > And< TRights > (RightsConditional< TRights > lhs, RightsConditional< TRights > rhs)
Helper to quickly construct an AndRightsConditional<TRights>.
Properties inherited from Tgstation.Server.Host.Authority.Core.AuthorityBase
IDatabaseContext DatabaseContext [get]
Gets the IDatabaseContext for the AuthorityBase.
ILogger< AuthorityBase > Logger [get]
Gets the ILogger for the AuthorityBase.
Detailed Description
Definition at line 27 of file LoginAuthority.cs.
Constructor & Destructor Documentation
LoginAuthority()
Tgstation.Server.Host.Authority.LoginAuthority.LoginAuthority (IDatabaseContext databaseContext, ILogger< LoginAuthority > logger, IApiHeadersProvider apiHeadersProvider, ISystemIdentityFactory systemIdentityFactory, IOAuthProviders oAuthProviders, ITokenFactory tokenFactory, ICryptographySuite cryptographySuite, IIdentityCache identityCache, ISessionInvalidationTracker sessionInvalidationTracker, IOptionsSnapshot< SecurityConfiguration > securityConfigurationOptions)
Initializes a new instance of the LoginAuthority class.
Parameters
databaseContext The IDatabaseContext to use.
logger The ILogger to use.
apiHeadersProvider The value of apiHeadersProvider.
systemIdentityFactory The value of systemIdentityFactory.
oAuthProviders The value of oAuthProviders.
tokenFactory The value of tokenFactory.
cryptographySuite The value of cryptographySuite.
identityCache The value of identityCache.
sessionInvalidationTracker The value of sessionInvalidationTracker.
securityConfigurationOptions The value of securityConfigurationOptions.
Definition at line 117 of file LoginAuthority.cs.
            : base(
                  databaseContext,
                  logger)
        {
            this.apiHeadersProvider = apiHeadersProvider ?? throw new ArgumentNullException(nameof(apiHeadersProvider));
            this.systemIdentityFactory = systemIdentityFactory ?? throw new ArgumentNullException(nameof(systemIdentityFactory));
            this.oAuthProviders = oAuthProviders ?? throw new ArgumentNullException(nameof(oAuthProviders));
            this.tokenFactory = tokenFactory ?? throw new ArgumentNullException(nameof(tokenFactory));
            this.cryptographySuite = cryptographySuite ?? throw new ArgumentNullException(nameof(cryptographySuite));
            this.identityCache = identityCache ?? throw new ArgumentNullException(nameof(identityCache));
            this.sessionInvalidationTracker = sessionInvalidationTracker ?? throw new ArgumentNullException(nameof(sessionInvalidationTracker));
            this.securityConfigurationOptions = securityConfigurationOptions ?? throw new ArgumentNullException(nameof(securityConfigurationOptions));
        }
References Tgstation.Server.Host.Authority.LoginAuthority.apiHeadersProvider, Tgstation.Server.Host.Authority.LoginAuthority.cryptographySuite, Tgstation.Server.Host.Authority.LoginAuthority.identityCache, Tgstation.Server.Host.Authority.LoginAuthority.oAuthProviders, Tgstation.Server.Host.Authority.LoginAuthority.securityConfigurationOptions, Tgstation.Server.Host.Authority.LoginAuthority.sessionInvalidationTracker, Tgstation.Server.Host.Authority.LoginAuthority.systemIdentityFactory, and Tgstation.Server.Host.Authority.LoginAuthority.tokenFactory.
Member Function Documentation
AttemptLogin()
RequirementsGated< AuthorityResponse< LoginResult > > Tgstation.Server.Host.Authority.LoginAuthority.AttemptLogin (CancellationToken cancellationToken)
Attempt to login to the server with the current Basic or OAuth credentials.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a LoginResult AuthorityResponse<TResult>.
Implements Tgstation.Server.Host.Authority.ILoginAuthority.
AttemptLoginImpl()
async ValueTask< AuthorityResponse< LoginResult > > Tgstation.Server.Host.Authority.LoginAuthority.AttemptLoginImpl (CancellationToken cancellationToken) private
Login process.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the AuthorityResponse<TResult> for the LoginResult.
Definition at line 181 of file LoginAuthority.cs.
        {
            // password and oauth logins disabled
            if (securityConfigurationOptions.Value.OidcStrictMode)
                return Unauthorized<LoginResult>();
            var headers = apiHeadersProvider.ApiHeaders;
            if (headers == null)
                return GenerateHeadersExceptionResponse<LoginResult>(apiHeadersProvider.HeadersException!);
            if (headers.IsTokenAuthentication)
                return BadRequest<LoginResult>(ErrorCode.TokenWithToken);
            var oAuthLogin = headers.OAuthProvider.HasValue;
            ISystemIdentity? systemIdentity = null;
            if (!oAuthLogin)
                try
                {
                    // trust the system over the database because a user's name can change while still having the same SID
                    systemIdentity = await systemIdentityFactory.CreateSystemIdentity(headers.Username!, headers.Password!, cancellationToken);
                }
                catch (NotImplementedException)
                {
                    // Intentionally suppressed
                }
            using (systemIdentity)
            {
                // Get the user from the database
                IQueryable<User> query = DatabaseContext.Users;
                if (oAuthLogin)
                {
                    var oAuthProvider = headers.OAuthProvider!.Value;
                    var (errorResponse, oauthResult) = await TryOAuthenticate<LoginResult>(headers, oAuthProvider, true, cancellationToken);
                    if (errorResponse != null)
                        return errorResponse;
                    query = query.Where(
                        x => x.OAuthConnections!.Any(
                            y => y.Provider == oAuthProvider
                            && y.ExternalUserId == oauthResult!.Value.UserID));
                }
                else
                {
                    var canonicalUserName = User.CanonicalizeName(headers.Username!);
                    if (canonicalUserName == User.CanonicalizeName(User.TgsSystemUserName))
                        return Unauthorized<LoginResult>();
                    if (systemIdentity == null)
                        query = query.Where(x => x.CanonicalName == canonicalUserName);
                    else
                        query = query.Where(x => x.CanonicalName == canonicalUserName || x.SystemIdentifier == systemIdentity.Uid);
                }
                var user = await SelectUserInfoFromQuery(query, cancellationToken);
                // No user? You're not allowed
                if (user == null)
                    return Unauthorized<LoginResult>();
                // A system user may have had their name AND password changed to one in our DB...
                // Or a DB user was created that had the same user/pass as a system user
                // Dumb admins...
                // FALLBACK TO THE DB USER HERE, DO NOT REVEAL A SYSTEM LOGIN!!!
                // This of course, allows system users to discover TGS users in this (HIGHLY IMPROBABLE) case but that is not our fault
                var originalHash = user.PasswordHash;
                var isLikelyDbUser = originalHash != null;
                var usingSystemIdentity = systemIdentity != null && !isLikelyDbUser;
                if (!oAuthLogin)
                    if (!usingSystemIdentity)
                    {
                        // DB User password check and update
                        if (!isLikelyDbUser || !cryptographySuite.CheckUserPassword(user, headers.Password!))
                            return Unauthorized<LoginResult>();
                        if (user.PasswordHash != originalHash)
{
                            Logger.LogDebug("User ID {userId}'s password hash needs a refresh, updating database.", user.Id);
                            var updatedUser = new User
{
                                Id = user.Id,
                            };
                            DatabaseContext.Users.Attach(updatedUser);
                            updatedUser.PasswordHash = user.PasswordHash;
                            await DatabaseContext.Save(cancellationToken);
                        }
                    }
                    else
                    {
                        var usernameMismatch = systemIdentity!.Username != user.Name;
                        if (isLikelyDbUser || usernameMismatch)
{
                            DatabaseContext.Users.Attach(user);
                            if (usernameMismatch)
{
                                // System identity username change update
                                Logger.LogDebug("User ID {userId}'s system identity needs a refresh, updating database.", user.Id);
                                user.Name = systemIdentity.Username;
                                user.CanonicalName = User.CanonicalizeName(user.Name);
                            }
                            if (isLikelyDbUser)
{
                                // cleanup from https://github.com/tgstation/tgstation-server/issues/1528
                                Logger.LogDebug("System user ID {userId}'s PasswordHash is polluted, updating database.", user.Id);
                                user.PasswordHash = null;
                                sessionInvalidationTracker.UserModifiedInvalidateSessions(user);
                            }
                            await DatabaseContext.Save(cancellationToken);
                        }
                    }
                // Now that the bookeeping is done, tell them to fuck off if necessary
                if (!user.Enabled!.Value)
                {
                    Logger.LogTrace("Not logging in disabled user {userId}.", user.Id);
                    return Forbid<LoginResult>();
                }
                var token = tokenFactory.CreateToken(user, oAuthLogin);
                var payload = new LoginResult
                {
                    Bearer = token,
                    User = ((IApiTransformable<User, GraphQL.Types.User, UserGraphQLTransformer>)user).ToApi(),
                };
                if (usingSystemIdentity)
                    await CacheSystemIdentity(systemIdentity!, user, payload);
                Logger.LogDebug("Successfully logged in user {userId}!", user.Id);
                return new AuthorityResponse<LoginResult>(payload);
            }
        }
References Tgstation.Server.Host.Utils.IApiHeadersProvider.ApiHeaders, Tgstation.Server.Host.Authority.LoginAuthority.apiHeadersProvider, Tgstation.Server.Host.Authority.LoginAuthority.CacheSystemIdentity(), Tgstation.Server.Host.Models.User.CanonicalizeName(), Tgstation.Server.Host.Security.ICryptographySuite.CheckUserPassword(), Tgstation.Server.Host.Security.ISystemIdentityFactory.CreateSystemIdentity(), Tgstation.Server.Host.Security.ITokenFactory.CreateToken(), Tgstation.Server.Host.Authority.LoginAuthority.cryptographySuite, Tgstation.Server.Host.Utils.IApiHeadersProvider.HeadersException, Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Host.Authority.Id, Tgstation.Server.Host.Authority.Core.AuthorityBase.Logger, Tgstation.Server.Host.Database.DatabaseContext.Save(), Tgstation.Server.Host.Authority.LoginAuthority.securityConfigurationOptions, Tgstation.Server.Host.Authority.LoginAuthority.SelectUserInfoFromQuery(), Tgstation.Server.Host.Authority.LoginAuthority.sessionInvalidationTracker, Tgstation.Server.Host.Authority.LoginAuthority.systemIdentityFactory, Tgstation.Server.Host.Models.User.TgsSystemUserName, Tgstation.Server.Host.Models.User.ToApi(), Tgstation.Server.Host.Authority.LoginAuthority.tokenFactory, Tgstation.Server.Host.Security.ISystemIdentity.Uid, Tgstation.Server.Host.Security.ISessionInvalidationTracker.UserModifiedInvalidateSessions(), Tgstation.Server.Host.Security.ISystemIdentity.Username, and Tgstation.Server.Host.Database.DatabaseContext.Users.
AttemptOAuthGatewayLogin()
RequirementsGated< AuthorityResponse< OAuthGatewayLoginResult > > Tgstation.Server.Host.Authority.LoginAuthority.AttemptOAuthGatewayLogin (CancellationToken cancellationToken)
Attempt to login to an OAuth service with the current OAuth credentials.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in an OAuthGatewayLoginResult AuthorityResponse<TResult>.
Implements Tgstation.Server.Host.Authority.ILoginAuthority.
References Tgstation.Server.Host.GraphQL.Mutations.Payloads.OAuthGatewayLoginResult.AccessCode, Tgstation.Server.Host.Utils.IApiHeadersProvider.ApiHeaders, Tgstation.Server.Host.Authority.LoginAuthority.apiHeadersProvider, Tgstation.Server.Host.Utils.IApiHeadersProvider.HeadersException, and Tgstation.Server.Host.Authority.Core.AuthorityBase.Logger.
CacheSystemIdentity()
async ValueTask Tgstation.Server.Host.Authority.LoginAuthority.CacheSystemIdentity (ISystemIdentity systemIdentity, User user, LoginResult loginPayload) private
Add a given systemIdentity to the identityCache.
Parameters
systemIdentity The ISystemIdentity to cache.
user The User the systemIdentity was generated for.
loginPayload The LoginResult for the successful login.
Returns
A ValueTask representing the running operation.
Definition at line 324 of file LoginAuthority.cs.
        {
            // expire the identity slightly after the auth token in case of lag
            var identExpiry = loginPayload.ToApi().ParseJwt().ValidTo;
            identExpiry += tokenFactory.ValidationParameters.ClockSkew;
            identExpiry += TimeSpan.FromSeconds(15);
            await identityCache.CacheSystemIdentity(user, systemIdentity!, identExpiry);
        }
References Tgstation.Server.Host.Security.IIdentityCache.CacheSystemIdentity(), Tgstation.Server.Host.Authority.LoginAuthority.identityCache, Tgstation.Server.Api.Models.Response.TokenResponse.ParseJwt(), Tgstation.Server.Host.GraphQL.Mutations.Payloads.LoginResult.ToApi(), Tgstation.Server.Host.Authority.LoginAuthority.tokenFactory, and Tgstation.Server.Host.Security.ITokenFactory.ValidationParameters.
Referenced by Tgstation.Server.Host.Authority.LoginAuthority.AttemptLoginImpl().
GenerateHeadersExceptionResponse< TResult >()
static AuthorityResponse< TResult > Tgstation.Server.Host.Authority.LoginAuthority.GenerateHeadersExceptionResponse< TResult > (HeadersException headersException) static private
Generate an AuthorityResponse<TResult> for a given headersException .
Template Parameters
TResult The Type of AuthorityResponse<TResult> to generate.
Parameters
headersException The HeadersException to generate a response for.
Returns
A new, errored LoginResult AuthorityResponse<TResult>.
References Tgstation.Server.Api.Models.Response.ErrorMessageResponse.Message.
SelectUserInfoFromQuery()
static async ValueTask< User?> Tgstation.Server.Host.Authority.LoginAuthority.SelectUserInfoFromQuery (IQueryable< User > query, CancellationToken cancellationToken) static private
Select the details needed to generate a TokenResponse from a given query .
Parameters
query The IQueryable<T> of Users.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the User returned after selecting, if any.
Definition at line 91 of file LoginAuthority.cs.
        {
            var users = await query
                .ToListAsync(cancellationToken);
            // Pick the DB user first
            var user = users
                .OrderByDescending(dbUser => dbUser.SystemIdentifier == null)
                .FirstOrDefault();
            return user;
        }
Referenced by Tgstation.Server.Host.Authority.LoginAuthority.AttemptLoginImpl().
TryOAuthenticate< TResult >()
async ValueTask<(AuthorityResponse< TResult >? ErrorResponse,(string? UserID, string AccessCode)? OAuthResult)> Tgstation.Server.Host.Authority.LoginAuthority.TryOAuthenticate< TResult > (ApiHeaders headers, OAuthProvider oAuthProvider, bool forLogin, CancellationToken cancellationToken) private
Attempt OAuth authentication.
Template Parameters
TResult The Type to use for errored AuthorityResponse<TResult>s.
Parameters
headers The current ApiHeaders.
oAuthProvider The OAuthProvider to use.
forLogin If this is for a server login.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in an errored AuthorityResponse<TResult> on failure or the result of the call to IOAuthValidator.ValidateResponseCode(string, bool, CancellationToken) on success.
Definition at line 342 of file LoginAuthority.cs.
        {
            (string? UserID, string AccessCode)? oauthResult;
            try
            {
                // minor special case here until its removal
#pragma warning disable CS0618 // Type or member is obsolete
                if (oAuthProvider == OAuthProvider.TGForums)
#pragma warning restore CS0618 // Type or member is obsolete
                    return (Unauthorized<TResult>(), null);
                var validator = oAuthProviders
                    .GetValidator(oAuthProvider, forLogin);
                if (validator == null)
                    return (BadRequest<TResult>(ErrorCode.OAuthProviderDisabled), null);
                oauthResult = await validator
                    .ValidateResponseCode(headers.OAuthCode!, forLogin, cancellationToken);
                Logger.LogTrace("External {oAuthProvider} UID: {externalUserId}", oAuthProvider, oauthResult);
            }
            catch (Octokit.RateLimitExceededException ex)
            {
                return (RateLimit<TResult>(ex), null);
            }
            if (!oauthResult.HasValue)
                return (Unauthorized<TResult>(), null);
            return (null, OAuthResult: oauthResult);
        }
References Tgstation.Server.Host.Authority.Core.AuthorityBase.BadRequest< TResult >(), Tgstation.Server.Host.Security.OAuth.IOAuthProviders.GetValidator(), Tgstation.Server.Host.Authority.Core.AuthorityBase.Logger, Tgstation.Server.Api.ApiHeaders.OAuthCode, Tgstation.Server.Host.Authority.LoginAuthority.oAuthProviders, Tgstation.Server.Host.Authority.Core.AuthorityBase.RateLimit< TResult >(), Tgstation.Server.Host.Authority.Core.AuthorityBase.Unauthorized< TResult >(), and Tgstation.Server.Host.Security.OAuth.IOAuthValidator.ValidateResponseCode().
Member Data Documentation
apiHeadersProvider
readonly IApiHeadersProvider Tgstation.Server.Host.Authority.LoginAuthority.apiHeadersProvider private
The IApiHeadersProvider for the LoginAuthority.
Definition at line 32 of file LoginAuthority.cs.
Referenced by Tgstation.Server.Host.Authority.LoginAuthority.AttemptLoginImpl(), Tgstation.Server.Host.Authority.LoginAuthority.AttemptOAuthGatewayLogin(), and Tgstation.Server.Host.Authority.LoginAuthority.LoginAuthority().
cryptographySuite
readonly ICryptographySuite Tgstation.Server.Host.Authority.LoginAuthority.cryptographySuite private
The ICryptographySuite for the LoginAuthority.
Definition at line 52 of file LoginAuthority.cs.
Referenced by Tgstation.Server.Host.Authority.LoginAuthority.AttemptLoginImpl(), and Tgstation.Server.Host.Authority.LoginAuthority.LoginAuthority().
identityCache
readonly IIdentityCache Tgstation.Server.Host.Authority.LoginAuthority.identityCache private
The IIdentityCache for the LoginAuthority.
Definition at line 57 of file LoginAuthority.cs.
Referenced by Tgstation.Server.Host.Authority.LoginAuthority.CacheSystemIdentity(), and Tgstation.Server.Host.Authority.LoginAuthority.LoginAuthority().
oAuthProviders
readonly IOAuthProviders Tgstation.Server.Host.Authority.LoginAuthority.oAuthProviders private
The IOAuthProviders for the LoginAuthority.
Definition at line 42 of file LoginAuthority.cs.
Referenced by Tgstation.Server.Host.Authority.LoginAuthority.LoginAuthority(), and Tgstation.Server.Host.Authority.LoginAuthority.TryOAuthenticate< TResult >().
securityConfigurationOptions
readonly IOptionsSnapshot<SecurityConfiguration> Tgstation.Server.Host.Authority.LoginAuthority.securityConfigurationOptions private
The IOptionsSnapshot<TOptions> containing the SecurityConfiguration for the LoginAuthority.
Definition at line 67 of file LoginAuthority.cs.
Referenced by Tgstation.Server.Host.Authority.LoginAuthority.AttemptLoginImpl(), and Tgstation.Server.Host.Authority.LoginAuthority.LoginAuthority().
sessionInvalidationTracker
readonly ISessionInvalidationTracker Tgstation.Server.Host.Authority.LoginAuthority.sessionInvalidationTracker private
The ISessionInvalidationTracker for the LoginAuthority.
Definition at line 62 of file LoginAuthority.cs.
Referenced by Tgstation.Server.Host.Authority.LoginAuthority.AttemptLoginImpl(), and Tgstation.Server.Host.Authority.LoginAuthority.LoginAuthority().
systemIdentityFactory
readonly ISystemIdentityFactory Tgstation.Server.Host.Authority.LoginAuthority.systemIdentityFactory private
The ISystemIdentityFactory for the LoginAuthority.
Definition at line 37 of file LoginAuthority.cs.
Referenced by Tgstation.Server.Host.Authority.LoginAuthority.AttemptLoginImpl(), and Tgstation.Server.Host.Authority.LoginAuthority.LoginAuthority().
tokenFactory
readonly ITokenFactory Tgstation.Server.Host.Authority.LoginAuthority.tokenFactory private
The ITokenFactory for the LoginAuthority.
Definition at line 47 of file LoginAuthority.cs.
Referenced by Tgstation.Server.Host.Authority.LoginAuthority.AttemptLoginImpl(), Tgstation.Server.Host.Authority.LoginAuthority.CacheSystemIdentity(), and Tgstation.Server.Host.Authority.LoginAuthority.LoginAuthority().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Authority/LoginAuthority.cs