tgstation-server: TGControlPanel.TestMergeManager Class Reference
TGControlPanel.TestMergeManager Class Reference
Public Member Functions
TestMergeManager (IInterface interfaceToUse, GitHubClient clientToUse)
Construct a TestMergeManager
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Member Functions inherited from TGControlPanel.ServerOpForm
Task WrapServerOp (Action action)
Used to wrap TGServiceInterface.IInterface calls in a non-blocking fashion while disabling the Form and enabling the wait cursor
Private Member Functions
async void LoadPullRequests ()
Populate PullRequestListBox with PullRequestInfo from github and check off ones that are currently merged. Prompts the user to login to GitHub if they hit the rate limit
void InsertPullRequest (Issue issue, bool prioritize, bool isChecked)
Format an entry for issue and insert it into PullRequestListBox
void InsertItem (string itemString, bool prioritize, bool isChecked)
Insert an itemString into PullRequestListBox
void PullRequestManager_Load (object sender, EventArgs e)
Called when the TestMergeManager is loaded. Sets repoOwner and repoName
async void GenerateChangelog (ITGRepository repo)
Calls ITGRepository.GenerateChangelog(out string) and shows the user an error prompt if it fails
async void ApplyButton_Click (object sender, EventArgs e)
Called when the ApplyButton is clicked. Calls ITGRepository.Update(bool) if necessary, merge pull requests, and call ITGCompiler.Compile(bool). Closes the TestMergeManager if appropriate
void RefreshButton_Click (object sender, EventArgs e)
Called when the RefreshButton is clicked
bool PullRequestsStringsListContainsPRNumber (CheckedListBox.ObjectCollection items, int PRNumber)
async void AddPRButton_Click (object sender, EventArgs e)
Called when the AddPRButton is clicked. Adds the PR with the number in AddPRNumericUpDown to PullRequestListBox or shows an error prompt if it doesn't/already exists
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
const string MergedPullsError = "Error retrieving currently merged pull requests: {0}"
Error message format used when ITGRepository.MergedPullRequests(out string) fails
readonly IInterface currentInterface
The IInterface connected to an ITGInstance to handle the pull requests for
readonly GitHubClient client
The GitHubClient to use to read PR lists
string repoOwner
The owner of the target Repository
string repoName
The name of the target Repository
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.CheckedListBox PullRequestListBox
System.Windows.Forms.Button ApplyButton
System.Windows.Forms.RadioButton UpdateToRemoteRadioButton
System.Windows.Forms.RadioButton UpdateToOriginRadioButton
System.Windows.Forms.RadioButton NoUpdateRadioButton
System.Windows.Forms.Button RefreshButton
System.Windows.Forms.Label ApplyingPullRequestsLabel
System.Windows.Forms.ProgressBar ApplyingPullRequestsProgressBar
System.Windows.Forms.Button AddPRButton
System.Windows.Forms.NumericUpDown AddPRNumericUpDown
Detailed Description
Definition at line 12 of file TestMergeManager.cs.
Constructor & Destructor Documentation
TGControlPanel.TestMergeManager.TestMergeManager (IInterface interfaceToUse, GitHubClient clientToUse)
Construct a TestMergeManager
Parameters
interfaceToUse The IInterface to use for managing the ITGInstance
clientToUse The GitHubClient to use for getting pull request information
Definition at line 43 of file TestMergeManager.cs.
References TGControlPanel.TestMergeManager.InitializeComponent(), TGControlPanel.TestMergeManager.PullRequestManager_Load(), and TGControlPanel.TestMergeManager.UpdateToRemoteRadioButton.
         {
             InitializeComponent();
             DialogResult = DialogResult.Cancel;
             UpdateToRemoteRadioButton.Checked = true;
             currentInterface = interfaceToUse;
             client = clientToUse;
             Load += PullRequestManager_Load;
         }
Member Function Documentation
async void TGControlPanel.TestMergeManager.AddPRButton_Click (object sender, EventArgs e) private
Called when the AddPRButton is clicked. Adds the PR with the number in AddPRNumericUpDown to PullRequestListBox or shows an error prompt if it doesn't/already exists
Parameters
sender The sender of the event
e The EventArgs
Definition at line 318 of file TestMergeManager.cs.
References TGControlPanel.TestMergeManager.AddPRNumericUpDown, TGControlPanel.TestMergeManager.InsertPullRequest(), TGServiceInterface.Components.ITGRepository.MergedPullRequests(), TGControlPanel.TestMergeManager.PullRequestListBox, and TGControlPanel.ServerOpForm.WrapServerOp().
Referenced by TGControlPanel.TestMergeManager.InitializeComponent().
         {
             Enabled = false;
             UseWaitCursor = true;
             try
             {
                 IList<PullRequestInfo> pulls = null;
                 string error = null;
                 var mergedPullsTask = WrapServerOp(() => pulls = currentInterface.GetComponent<ITGRepository>().MergedPullRequests(out error));
                 int PRNumber;
                 try
                 {
                     PRNumber = Convert.ToInt32(AddPRNumericUpDown.Value);
                 }
                 catch
                 {
                     MessageBox.Show("Invalid PR number!");
                     return;
                 }
                 var found = false;
                 var asString = PRNumber.ToString();
                 foreach (var I in PullRequestListBox.Items)
                     if (((string)I).Split(' ')[0].Substring(1) == asString)
                     {
                         found = true;
                         break;
                     }
                 if (found)
                 {
                     MessageBox.Show("That PR is already in the list!");
                     return;
                 }
                 await mergedPullsTask;
                 if (pulls == null)
                     MessageBox.Show(String.Format(MergedPullsError, error));
                 //get the PR in question
                 var PR = await client.Issue.Get(repoName, repoOwner, PRNumber);
                 if(PR == null ||PR.PullRequest == null)
                 {
                     MessageBox.Show("That doesn't seem to be a valid PR!");
                     return;
                 }
                 InsertPullRequest(PR, true, pulls == null || pulls.Any(x => x.Number == PRNumber));
             }
             finally
             {
                 UseWaitCursor = false;
                 Enabled = true;
             }
         }
async void TGControlPanel.TestMergeManager.ApplyButton_Click (object sender, EventArgs e) private
Called when the ApplyButton is clicked. Calls ITGRepository.Update(bool) if necessary, merge pull requests, and call ITGCompiler.Compile(bool). Closes the TestMergeManager if appropriate
Parameters
sender The sender of the event
e The EventArgs
Definition at line 206 of file TestMergeManager.cs.
References TGControlPanel.TestMergeManager.ApplyingPullRequestsLabel, TGControlPanel.TestMergeManager.ApplyingPullRequestsProgressBar, TGServiceInterface.Components.ITGCompiler.Compile(), TGControlPanel.TestMergeManager.GenerateChangelog(), TGControlPanel.TestMergeManager.PullRequestListBox, TGControlPanel.TestMergeManager.UpdateToOriginRadioButton, TGControlPanel.TestMergeManager.UpdateToRemoteRadioButton, and TGControlPanel.ServerOpForm.WrapServerOp().
Referenced by TGControlPanel.TestMergeManager.InitializeComponent().
         {
             Enabled = false;
             UseWaitCursor = true;
             ApplyingPullRequestsLabel.Visible = true;
             ApplyingPullRequestsProgressBar.Visible = true;
             PullRequestListBox.Visible = false;
             try
             {
                 //so first collect a list of pulls that are checked
                 var pulls = new Dictionary<int, string>();
                 foreach (var I in PullRequestListBox.CheckedItems)
                 {
                     var S = (string)I;
                     string mergedSha = null;
                     var splits = S.Split(' ');
                     if(S.Contains(" - OUTDATED: "))
                         mergedSha = splits[splits.Length - 1];
                     var key = Convert.ToInt32((splits[0].Substring(1)));
                     try
                     {
                         pulls.Add(key, mergedSha);
                     }
                     catch
                     {
                         MessageBox.Show(String.Format("Checked both keep and update option for #{0}", key), "Error");
                         return;
                     }
                 }
                 var repo = currentInterface.GetComponent<ITGRepository>();
                 string error = null;
                 //Do standard repo updates
                 if (UpdateToRemoteRadioButton.Checked)
                     await WrapServerOp(() => error = repo.Update(true));
                 else if (UpdateToOriginRadioButton.Checked)
                     await WrapServerOp(() => error = repo.Reset(true));
                 if (error != null)
                 {
                     MessageBox.Show(String.Format("Error updating repository: {0}", error));
                     return;
                 }
                 if (UpdateToRemoteRadioButton.Checked)
                 {
                     GenerateChangelog(repo);
                     await WrapServerOp(() => error = repo.SynchronizePush());
                     if (error != null)
                         MessageBox.Show(String.Format("Error sychronizing repo: {0}", error));
                 }
                 //Merge the PRs, collect errors
                 IList<string> errors = null;
                 await WrapServerOp(() =>
                 {
                     errors = new List<string>();
                     foreach (var I in pulls)
                     {
                         var res = repo.MergePullRequest(I.Key, I.Value);
                         if (res != null)
                             errors.Add(String.Format("Error merging PR #{0}: {1}", I, res));
                     }
                 });
                 //Show any errors
                 foreach (var I in errors)
                     MessageBox.Show(I);
                 if (errors.Count != 0)
                     return;
                 if (pulls.Count > 0)
                     //regen the changelog
                     GenerateChangelog(repo);
                 //Start the compile
                 if (!currentInterface.GetComponent<ITGCompiler>().Compile(pulls.Count == 1))
                     MessageBox.Show("Could not start compilation!");
                 else
                     MessageBox.Show("Test merges updated and compilation started!");
             }
             finally
             {
                 Enabled = true;
                 UseWaitCursor = false;
                 ApplyingPullRequestsLabel.Visible = false;
                 ApplyingPullRequestsProgressBar.Visible = false;
                 PullRequestListBox.Visible = true;
             }
         }
override void TGControlPanel.TestMergeManager.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file TestMergeManager.Designer.cs.
References TGControlPanel.TestMergeManager.components.
         {
             if (disposing && (components != null))
             {
                 components.Dispose();
             }
             base.Dispose(disposing);
         }
async void TGControlPanel.TestMergeManager.GenerateChangelog (ITGRepository repo) private
Calls ITGRepository.GenerateChangelog(out string) and shows the user an error prompt if it fails
Parameters
repo The ITGRepository to call ITGRepository.GenerateChangelog(out string) on
Definition at line 193 of file TestMergeManager.cs.
References TGServiceInterface.Components.ITGRepository.GenerateChangelog(), and TGControlPanel.ServerOpForm.WrapServerOp().
Referenced by TGControlPanel.TestMergeManager.ApplyButton_Click().
         {
             string error = null;
             await WrapServerOp(() => repo.GenerateChangelog(out error));
             if (error != null)
                 MessageBox.Show(String.Format("Error generating changelog: {0}", error));
         }
void TGControlPanel.TestMergeManager.InitializeComponent () private
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 29 of file TestMergeManager.Designer.cs.
References TGControlPanel.TestMergeManager.AddPRButton, TGControlPanel.TestMergeManager.AddPRButton_Click(), TGControlPanel.TestMergeManager.AddPRNumericUpDown, TGControlPanel.TestMergeManager.ApplyButton, TGControlPanel.TestMergeManager.ApplyButton_Click(), TGControlPanel.TestMergeManager.ApplyingPullRequestsLabel, TGControlPanel.TestMergeManager.ApplyingPullRequestsProgressBar, TGControlPanel.TestMergeManager.NoUpdateRadioButton, TGControlPanel.TestMergeManager.PullRequestListBox, TGControlPanel.TestMergeManager.RefreshButton, TGControlPanel.TestMergeManager.RefreshButton_Click(), TGControlPanel.TestMergeManager.UpdateToOriginRadioButton, and TGControlPanel.TestMergeManager.UpdateToRemoteRadioButton.
Referenced by TGControlPanel.TestMergeManager.TestMergeManager().
         {
             System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(TestMergeManager));
             this.PullRequestListBox = new System.Windows.Forms.CheckedListBox();
             this.ApplyButton = new System.Windows.Forms.Button();
             this.UpdateToRemoteRadioButton = new System.Windows.Forms.RadioButton();
             this.UpdateToOriginRadioButton = new System.Windows.Forms.RadioButton();
             this.NoUpdateRadioButton = new System.Windows.Forms.RadioButton();
             this.RefreshButton = new System.Windows.Forms.Button();
             this.ApplyingPullRequestsLabel = new System.Windows.Forms.Label();
             this.ApplyingPullRequestsProgressBar = new System.Windows.Forms.ProgressBar();
             this.AddPRButton = new System.Windows.Forms.Button();
             this.AddPRNumericUpDown = new System.Windows.Forms.NumericUpDown();
             ((System.ComponentModel.ISupportInitialize)(this.AddPRNumericUpDown)).BeginInit();
             this.SuspendLayout();
             //
             // PullRequestListBox
             //
             this.PullRequestListBox.CheckOnClick = true;
             this.PullRequestListBox.FormattingEnabled = true;
             this.PullRequestListBox.Location = new System.Drawing.Point(13, 13);
             this.PullRequestListBox.Name = "PullRequestListBox";
             this.PullRequestListBox.Size = new System.Drawing.Size(588, 199);
             this.PullRequestListBox.TabIndex = 0;
             this.PullRequestListBox.ThreeDCheckBoxes = true;
             this.PullRequestListBox.UseWaitCursor = true;
             //
             // ApplyButton
             //
             this.ApplyButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
             this.ApplyButton.Location = new System.Drawing.Point(544, 226);
             this.ApplyButton.Name = "ApplyButton";
             this.ApplyButton.Size = new System.Drawing.Size(57, 23);
             this.ApplyButton.TabIndex = 2;
             this.ApplyButton.Text = "Apply";
             this.ApplyButton.UseVisualStyleBackColor = true;
             this.ApplyButton.UseWaitCursor = true;
             this.ApplyButton.Click += new System.EventHandler(this.ApplyButton_Click);
             //
             // UpdateToRemoteRadioButton
             //
             this.UpdateToRemoteRadioButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
             this.UpdateToRemoteRadioButton.AutoSize = true;
             this.UpdateToRemoteRadioButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.UpdateToRemoteRadioButton.Location = new System.Drawing.Point(13, 229);
             this.UpdateToRemoteRadioButton.Name = "UpdateToRemoteRadioButton";
             this.UpdateToRemoteRadioButton.Size = new System.Drawing.Size(116, 17);
             this.UpdateToRemoteRadioButton.TabIndex = 3;
             this.UpdateToRemoteRadioButton.TabStop = true;
             this.UpdateToRemoteRadioButton.Text = "Update To Remote";
             this.UpdateToRemoteRadioButton.UseVisualStyleBackColor = true;
             this.UpdateToRemoteRadioButton.UseWaitCursor = true;
             //
             // UpdateToOriginRadioButton
             //
             this.UpdateToOriginRadioButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
             this.UpdateToOriginRadioButton.AutoSize = true;
             this.UpdateToOriginRadioButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.UpdateToOriginRadioButton.Location = new System.Drawing.Point(135, 229);
             this.UpdateToOriginRadioButton.Name = "UpdateToOriginRadioButton";
             this.UpdateToOriginRadioButton.Size = new System.Drawing.Size(106, 17);
             this.UpdateToOriginRadioButton.TabIndex = 4;
             this.UpdateToOriginRadioButton.TabStop = true;
             this.UpdateToOriginRadioButton.Text = "Update To Origin";
             this.UpdateToOriginRadioButton.UseVisualStyleBackColor = true;
             this.UpdateToOriginRadioButton.UseWaitCursor = true;
             //
             // NoUpdateRadioButton
             //
             this.NoUpdateRadioButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
             this.NoUpdateRadioButton.AutoSize = true;
             this.NoUpdateRadioButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.NoUpdateRadioButton.Location = new System.Drawing.Point(247, 229);
             this.NoUpdateRadioButton.Name = "NoUpdateRadioButton";
             this.NoUpdateRadioButton.Size = new System.Drawing.Size(77, 17);
             this.NoUpdateRadioButton.TabIndex = 5;
             this.NoUpdateRadioButton.TabStop = true;
             this.NoUpdateRadioButton.Text = "No Update";
             this.NoUpdateRadioButton.UseVisualStyleBackColor = true;
             this.NoUpdateRadioButton.UseWaitCursor = true;
             //
             // RefreshButton
             //
             this.RefreshButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
             this.RefreshButton.Location = new System.Drawing.Point(481, 226);
             this.RefreshButton.Name = "RefreshButton";
             this.RefreshButton.Size = new System.Drawing.Size(57, 23);
             this.RefreshButton.TabIndex = 6;
             this.RefreshButton.Text = "Refresh";
             this.RefreshButton.UseVisualStyleBackColor = true;
             this.RefreshButton.UseWaitCursor = true;
             this.RefreshButton.Click += new System.EventHandler(this.RefreshButton_Click);
             //
             // ApplyingPullRequestsLabel
             //
             this.ApplyingPullRequestsLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
             this.ApplyingPullRequestsLabel.AutoSize = true;
             this.ApplyingPullRequestsLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.ApplyingPullRequestsLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.ApplyingPullRequestsLabel.Location = new System.Drawing.Point(224, 92);
             this.ApplyingPullRequestsLabel.Name = "ApplyingPullRequestsLabel";
             this.ApplyingPullRequestsLabel.Size = new System.Drawing.Size(156, 16);
             this.ApplyingPullRequestsLabel.TabIndex = 8;
             this.ApplyingPullRequestsLabel.Text = "Applying Pull Requests...";
             this.ApplyingPullRequestsLabel.UseWaitCursor = true;
             this.ApplyingPullRequestsLabel.Visible = false;
             //
             // ApplyingPullRequestsProgressBar
             //
             this.ApplyingPullRequestsProgressBar.Location = new System.Drawing.Point(48, 112);
             this.ApplyingPullRequestsProgressBar.Name = "ApplyingPullRequestsProgressBar";
             this.ApplyingPullRequestsProgressBar.Size = new System.Drawing.Size(513, 23);
             this.ApplyingPullRequestsProgressBar.Style = System.Windows.Forms.ProgressBarStyle.Marquee;
             this.ApplyingPullRequestsProgressBar.TabIndex = 9;
             this.ApplyingPullRequestsProgressBar.UseWaitCursor = true;
             this.ApplyingPullRequestsProgressBar.Visible = false;
             //
             // AddPRButton
             //
             this.AddPRButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
             this.AddPRButton.Location = new System.Drawing.Point(418, 226);
             this.AddPRButton.Name = "AddPRButton";
             this.AddPRButton.Size = new System.Drawing.Size(57, 23);
             this.AddPRButton.TabIndex = 10;
             this.AddPRButton.Text = "Add PR";
             this.AddPRButton.UseVisualStyleBackColor = true;
             this.AddPRButton.UseWaitCursor = true;
             this.AddPRButton.Click += new System.EventHandler(this.AddPRButton_Click);
             //
             // AddPRNumericUpDown
             //
             this.AddPRNumericUpDown.Location = new System.Drawing.Point(331, 229);
             this.AddPRNumericUpDown.Maximum = new decimal(new int[] {
             10000000,
             0,
             0,
             0});
             this.AddPRNumericUpDown.Minimum = new decimal(new int[] {
             1,
             0,
             0,
             0});
             this.AddPRNumericUpDown.Name = "AddPRNumericUpDown";
             this.AddPRNumericUpDown.Size = new System.Drawing.Size(81, 20);
             this.AddPRNumericUpDown.TabIndex = 11;
             this.AddPRNumericUpDown.UseWaitCursor = true;
             this.AddPRNumericUpDown.Value = new decimal(new int[] {
             1,
             0,
             0,
             0});
             //
             // TestMergeManager
             //
             this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
             this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
             this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(40)))), ((int)(((byte)(34)))));
             this.ClientSize = new System.Drawing.Size(613, 261);
             this.Controls.Add(this.AddPRNumericUpDown);
             this.Controls.Add(this.AddPRButton);
             this.Controls.Add(this.ApplyingPullRequestsProgressBar);
             this.Controls.Add(this.ApplyingPullRequestsLabel);
             this.Controls.Add(this.RefreshButton);
             this.Controls.Add(this.NoUpdateRadioButton);
             this.Controls.Add(this.UpdateToOriginRadioButton);
             this.Controls.Add(this.UpdateToRemoteRadioButton);
             this.Controls.Add(this.ApplyButton);
             this.Controls.Add(this.PullRequestListBox);
             this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
             this.MaximizeBox = false;
             this.Name = "TestMergeManager";
             this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
             this.Text = "Test Merge Manager";
             this.UseWaitCursor = true;
             ((System.ComponentModel.ISupportInitialize)(this.AddPRNumericUpDown)).EndInit();
             this.ResumeLayout(false);
             this.PerformLayout();
         }
void TGControlPanel.TestMergeManager.InsertItem (string itemString, bool prioritize, bool isChecked) private
Insert an itemString into PullRequestListBox
Parameters
itemString The string to insert
prioritize If this or isChecked is , itemString will be inserted at the top of PullRequestListBox as opposed to the bottom
isChecked If the item should be checked
Definition at line 159 of file TestMergeManager.cs.
References TGControlPanel.TestMergeManager.PullRequestListBox.
Referenced by TGControlPanel.TestMergeManager.InsertPullRequest(), and TGControlPanel.TestMergeManager.LoadPullRequests().
         {
             prioritize = prioritize || isChecked;
             if (prioritize)
             {
                 PullRequestListBox.Items.Insert(0, itemString);
                 if (isChecked)
                     PullRequestListBox.SetItemChecked(0, true);
             }
             else
                 PullRequestListBox.Items.Add(itemString, isChecked);
         }
void TGControlPanel.TestMergeManager.InsertPullRequest (Issue issue, bool prioritize, bool isChecked) private
Format an entry for issue and insert it into PullRequestListBox
Parameters
issue The Issue to format, must contain a PullRequest
prioritize If this or isChecked is , issue will be inserted at the top of PullRequestListBox as opposed to the bottom
isChecked If the item should be checked
Definition at line 140 of file TestMergeManager.cs.
References TGControlPanel.TestMergeManager.InsertItem().
Referenced by TGControlPanel.TestMergeManager.AddPRButton_Click(), and TGControlPanel.TestMergeManager.LoadPullRequests().
         {
             bool needsTesting = false;
             foreach (var J in issue.Labels)
                 if (J.Name.ToLower().Contains("test"))
                 {
                     needsTesting = true;
                     break;
                 }
             var itemString = String.Format("#{0} - {1}{2}", issue.Number, issue.Title, issue.PullRequest != null && issue.PullRequest.Merged ? " - MERGED ON REMOTE" : needsTesting ? " - TESTING REQUESTED" : "");
             InsertItem(itemString, prioritize || needsTesting, isChecked);
         }
async void TGControlPanel.TestMergeManager.LoadPullRequests () private
Populate PullRequestListBox with PullRequestInfo from github and check off ones that are currently merged. Prompts the user to login to GitHub if they hit the rate limit
Definition at line 56 of file TestMergeManager.cs.
References TGControlPanel.TestMergeManager.InsertItem(), TGControlPanel.TestMergeManager.InsertPullRequest(), TGControlPanel.TestMergeManager.PullRequestListBox, TGControlPanel.Program.RateLimitPrompt(), and TGControlPanel.TestMergeManager.repoOwner.
Referenced by TGControlPanel.TestMergeManager.PullRequestManager_Load(), and TGControlPanel.TestMergeManager.RefreshButton_Click().
         {
             try
             {
                 Enabled = false;
                 UseWaitCursor = true;
                 try
                 {
                     PullRequestListBox.Items.Clear();
                     var repo = currentInterface.GetComponent<ITGRepository>();
                     string error = null;
                     List<PullRequestInfo> pulls = null;
                     //get started on this while we're processing here
                     var pullsRequest = Task.Factory.StartNew(() => pulls = repo.MergedPullRequests(out error));
                     //Search for open PRs
                     Enabled = false;
                     UseWaitCursor = true;
                     SearchIssuesResult result;
                     try
                     {
                         result = await client.Search.SearchIssues(new SearchIssuesRequest
{
                             Repos = new RepositoryCollection { { repoOwner, repoName } },
                             State = ItemState.Open,
                             Type = IssueTypeQualifier.PullRequest
                         });
                     }
                     finally
                     {
                         Enabled = true;
                         UseWaitCursor = false;
                     }
                     //now we need to know what's merged
                     await pullsRequest;
                     if (pulls == null)
                         MessageBox.Show(String.Format(MergedPullsError, error));
                     //insert the open pull requests, checking already merged once
                     foreach (var I in result.Items)
                     {
                         bool alreadyMerged = false;
                         var pull = pulls.Where(x => x.Number == I.Number).FirstOrDefault();
                         if (pull != null)
{
                             //we need the full info for this PR
                             alreadyMerged = (await client.PullRequest.Get(repoOwner, repoName, I.Number)).Head.Sha == pull.Sha;
                             if (alreadyMerged)
                                 pulls.Remove(pull);
                         }
                         InsertPullRequest(I, false, alreadyMerged);
                     }
                     //insert remaining merged pulls
                     foreach (var I in pulls)
                         InsertItem(String.Format("#{0} - {1} - OUTDATED: {2}", I.Number, I.Title, I.Sha), true, true);
                 }
                 finally
                 {
                     Enabled = true;
                     UseWaitCursor = false;
                 }
             }
             catch (ForbiddenException)
             {
                 if (client.Credentials.AuthenticationType == AuthenticationType.Anonymous)  //assume request limit hit
                 {
                     if(Program.RateLimitPrompt(client))
                         LoadPullRequests();
                 }
                 else
                     throw;
             }
         }
void TGControlPanel.TestMergeManager.PullRequestManager_Load (object sender, EventArgs e) private
Called when the TestMergeManager is loaded. Sets repoOwner and repoName
Parameters
sender The sender of the event
e The EventArgs
Definition at line 177 of file TestMergeManager.cs.
References TGControlPanel.Program.GetRepositoryRemote(), and TGControlPanel.TestMergeManager.LoadPullRequests().
Referenced by TGControlPanel.TestMergeManager.TestMergeManager().
         {
             Enabled = false;
             var repo = currentInterface.GetComponent<ITGRepository>();
             if(!Program.GetRepositoryRemote(repo, out repoOwner, out repoName))
             {
                 Close();
                 return;
             }
             LoadPullRequests();
         }
bool TGControlPanel.TestMergeManager.PullRequestsStringsListContainsPRNumber (CheckedListBox.ObjectCollection items, int PRNumber) private
Definition at line 308 of file TestMergeManager.cs.
         {
             return false;
         }
void TGControlPanel.TestMergeManager.RefreshButton_Click (object sender, EventArgs e) private
Called when the RefreshButton is clicked
Parameters
sender The sender of the event
e The EventArgs
Definition at line 303 of file TestMergeManager.cs.
References TGControlPanel.TestMergeManager.LoadPullRequests().
Referenced by TGControlPanel.TestMergeManager.InitializeComponent().
         {
             LoadPullRequests();
         }
Member Data Documentation
System.Windows.Forms.Button TGControlPanel.TestMergeManager.AddPRButton private
Definition at line 219 of file TestMergeManager.Designer.cs.
Referenced by TGControlPanel.TestMergeManager.InitializeComponent().
System.Windows.Forms.NumericUpDown TGControlPanel.TestMergeManager.AddPRNumericUpDown private
Definition at line 220 of file TestMergeManager.Designer.cs.
Referenced by TGControlPanel.TestMergeManager.AddPRButton_Click(), and TGControlPanel.TestMergeManager.InitializeComponent().
System.Windows.Forms.Button TGControlPanel.TestMergeManager.ApplyButton private
Definition at line 212 of file TestMergeManager.Designer.cs.
Referenced by TGControlPanel.TestMergeManager.InitializeComponent().
System.Windows.Forms.Label TGControlPanel.TestMergeManager.ApplyingPullRequestsLabel private
Definition at line 217 of file TestMergeManager.Designer.cs.
Referenced by TGControlPanel.TestMergeManager.ApplyButton_Click(), and TGControlPanel.TestMergeManager.InitializeComponent().
System.Windows.Forms.ProgressBar TGControlPanel.TestMergeManager.ApplyingPullRequestsProgressBar private
Definition at line 218 of file TestMergeManager.Designer.cs.
Referenced by TGControlPanel.TestMergeManager.ApplyButton_Click(), and TGControlPanel.TestMergeManager.InitializeComponent().
readonly GitHubClient TGControlPanel.TestMergeManager.client private
The GitHubClient to use to read PR lists
Definition at line 27 of file TestMergeManager.cs.
System.ComponentModel.IContainer TGControlPanel.TestMergeManager.components = null private
Required designer variable.
Definition at line 8 of file TestMergeManager.Designer.cs.
Referenced by TGControlPanel.TestMergeManager.Dispose().
readonly IInterface TGControlPanel.TestMergeManager.currentInterface private
The IInterface connected to an ITGInstance to handle the pull requests for
Definition at line 22 of file TestMergeManager.cs.
const string TGControlPanel.TestMergeManager.MergedPullsError = "Error retrieving currently merged pull requests: {0}" private
Error message format used when ITGRepository.MergedPullRequests(out string) fails
Definition at line 17 of file TestMergeManager.cs.
System.Windows.Forms.RadioButton TGControlPanel.TestMergeManager.NoUpdateRadioButton private
Definition at line 215 of file TestMergeManager.Designer.cs.
Referenced by TGControlPanel.TestMergeManager.InitializeComponent().
System.Windows.Forms.CheckedListBox TGControlPanel.TestMergeManager.PullRequestListBox private
Definition at line 211 of file TestMergeManager.Designer.cs.
Referenced by TGControlPanel.TestMergeManager.AddPRButton_Click(), TGControlPanel.TestMergeManager.ApplyButton_Click(), TGControlPanel.TestMergeManager.InitializeComponent(), TGControlPanel.TestMergeManager.InsertItem(), and TGControlPanel.TestMergeManager.LoadPullRequests().
System.Windows.Forms.Button TGControlPanel.TestMergeManager.RefreshButton private
Definition at line 216 of file TestMergeManager.Designer.cs.
Referenced by TGControlPanel.TestMergeManager.InitializeComponent().
string TGControlPanel.TestMergeManager.repoName private
The name of the target Repository
Definition at line 36 of file TestMergeManager.cs.
string TGControlPanel.TestMergeManager.repoOwner private
The owner of the target Repository
Definition at line 32 of file TestMergeManager.cs.
Referenced by TGControlPanel.TestMergeManager.LoadPullRequests().
System.Windows.Forms.RadioButton TGControlPanel.TestMergeManager.UpdateToOriginRadioButton private
Definition at line 214 of file TestMergeManager.Designer.cs.
Referenced by TGControlPanel.TestMergeManager.ApplyButton_Click(), and TGControlPanel.TestMergeManager.InitializeComponent().
System.Windows.Forms.RadioButton TGControlPanel.TestMergeManager.UpdateToRemoteRadioButton private
Definition at line 213 of file TestMergeManager.Designer.cs.
Referenced by TGControlPanel.TestMergeManager.ApplyButton_Click(), TGControlPanel.TestMergeManager.InitializeComponent(), and TGControlPanel.TestMergeManager.TestMergeManager().
The documentation for this class was generated from the following files:
TGControlPanel/TestMergeManager.cs
TGControlPanel/TestMergeManager.Designer.cs