tgstation-server: Tgstation.Server.Host.Authority.Core.GraphQLAuthorityInvoker< TAuthority > Class Template Reference
Tgstation.Server.Host.Authority.Core.GraphQLAuthorityInvoker< TAuthority > Class Template Reference sealed
Public Member Functions
GraphQLAuthorityInvoker (TAuthority authority, Security.IAuthorizationService authorizationService)
Initializes a new instance of the GraphQLAuthorityInvoker<TAuthority> class.
Public Member Functions inherited from Tgstation.Server.Host.Authority.Core.AuthorityInvokerBase< TAuthority >
AuthorityInvokerBase (TAuthority authority, Security.IAuthorizationService authorizationService)
Initializes a new instance of the AuthorityInvokerBase<TAuthority> class.
Static Public Member Functions
static TAuthorityResponse ThrowGraphQLErrorIfNecessary< TAuthorityResponse > (TAuthorityResponse authorityResponse, bool errorOnMissing)
Throws a ErrorMessageException for errored authorityResponse s.
Protected Member Functions
override void OnRequirementsFailure (AuthorizationFailure authFailure)
Called to handle generic behavior when requirements evaluation fails.
Parameters
authFailure The AuthorizationFailure.
Protected Member Functions inherited from Tgstation.Server.Host.Authority.Core.AuthorityInvokerBase< TAuthority >
async ValueTask< TResult?> ExecuteIfRequirementsSatisfied< TResult > (RequirementsGated< TResult > requirementsGate)
Unwrap a RequirementsGated<TResult> result, returning null if the requirements weren't satisfied.
Private Member Functions
async ValueTask IGraphQLAuthorityInvoker< TAuthority >. Invoke (Func< TAuthority, RequirementsGated< AuthorityResponse > > authorityInvoker)
Invoke a TAuthority method with no success result.
Parameters
authorityInvoker The TAuthority Func<T, TResult> resulting in the RequirementsGated<TResult> AuthorityResponse.
Returns
A ValueTask representing the running operation.
async ValueTask< TApiModel?> IGraphQLAuthorityInvoker< TAuthority >. InvokeAllowMissing< TResult, TApiModel > (Func< TAuthority, RequirementsGated< AuthorityResponse< TResult > > > authorityInvoker)
Invoke a TAuthority method and get the result.
Template Parameters
TResult The AuthorityResponse<TResult>.Result Type.
TApiModel The resulting Type of the return value.
Parameters
authorityInvoker The TAuthority Func<T, TResult> resulting in the RequirementsGated<TResult> AuthorityResponse<TResult>.
Returns
A ValueTask<TResult> resulting in the TApiModel generated for the resulting AuthorityResponse<TResult>.
async ValueTask< TApiModel?> IGraphQLAuthorityInvoker< TAuthority >. InvokeTransformableAllowMissing< TResult, TApiModel, TTransformer > (Func< TAuthority, RequirementsGated< AuthorityResponse< TResult > > > authorityInvoker)
Invoke a TAuthority method and get the result.
Template Parameters
TResult The AuthorityResponse<TResult>.Result Type.
TApiModel The resulting Type of the return value.
TTransformer The ITransformer<TInput, TOutput> for converting TResult s to TApiModel s.
Parameters
authorityInvoker The TAuthority Func<T, TResult> resulting in the RequirementsGated<TResult> AuthorityResponse<TResult>.
Returns
A ValueTask<TResult> resulting in the TApiModel generated for the resulting AuthorityResponse<TResult>.
async ValueTask< IQueryable< TApiModel > > IGraphQLAuthorityInvoker< TAuthority >. InvokeTransformableQueryable< TResult, TApiModel, TTransformer > (Func< TAuthority, RequirementsGated< IQueryable< TResult > > > authorityInvoker, Func< IQueryable< TResult >, IQueryable< TResult > >? preTransformer)
Invoke a TAuthority method and get the transformed result.
Template Parameters
TResult The Type returned by the TAuthority .
TApiModel The returned Type.
TTransformer The ITransformer<TInput, TOutput> for converting TResult s to TApiModel s.
Parameters
authorityInvoker The TAuthority Func<T, TResult> returning a IQueryable<T> TResult .
preTransformer Optional transformer for the IQueryable<T> run once it has been acquired.
Returns
A ValueTask<TResult> resulting in the IQueryable<T> TResult returned on success or null if the requirements weren't satisfied.
async ValueTask< Dictionary< long, AuthorityResponse< TApiModel > > > IGraphQLAuthorityInvoker< TAuthority >. ExecuteDataLoader< TResult, TApiModel, TTransformer > (Func< TAuthority, long, RequirementsGated< Projectable< TResult, TApiModel > > > authorityInvoker, IReadOnlyList< long > ids, QueryContext< AuthorityResponse< TApiModel > >? queryContext)
Execute a batch loaded call on a given authorityInvoker .
Template Parameters
TResult The queried result of the TAuthority .
TApiModel The returned Type.
TTransformer The ITransformer<TInput, TOutput> for converting TResult s to TApiModel s.
Parameters
authorityInvoker The TAuthority Func<T, TResult> returning a RequirementsGated<TResult> Projectable<TQueried, TResult> from TResult to TApiModel .
ids The list of EntityId.Ids to batch load.
queryContext The active QueryContext<TEntity> mapped to an AuthorityResponse<TResult> of the TApiModel . MUST have been wrapped with Extensions.QueryContextExtensions.AuthorityResponseWrap<TResult>(QueryContext<TResult>). This will be unwrapped so only a QueryContext<TEntity> of TApiModel will be used.
Returns
A ValueTask<TResult> resulting in a Dictionary<TKey, TValue> of loaded EntityId.Ids to AuthorityResponse<TResult>s for the loaded TApiModel s.
async ValueTask< TApiModel > IGraphQLAuthorityInvoker< TAuthority >. Invoke< TResult, TApiModel > (Func< TAuthority, RequirementsGated< AuthorityResponse< TResult > > > authorityInvoker)
Invoke a TAuthority method and get the non-nullable result.
Template Parameters
TResult The AuthorityResponse<TResult>.Result Type.
TApiModel The resulting Type of the return value.
Parameters
authorityInvoker The TAuthority Func<T, TResult> resulting in the RequirementsGated<TResult> AuthorityResponse<TResult>.
Returns
A ValueTask<TResult> resulting in the TApiModel generated for the resulting AuthorityResponse<TResult>.
async ValueTask< TApiModel > IGraphQLAuthorityInvoker< TAuthority >. TApiModel (authorityInvoker) ?? throw new InvalidOperationException("Authority invocation should have returned a non-nullable result!")
async ValueTask< TApiModel > IGraphQLAuthorityInvoker< TAuthority >. InvokeTransformable< TResult, TApiModel, TTransformer > (Func< TAuthority, RequirementsGated< AuthorityResponse< TResult > > > authorityInvoker)
Invoke a TAuthority method and get the non-nullable result.
Template Parameters
TResult The AuthorityResponse<TResult>.Result Type.
TApiModel The resulting Type of the return value.
TTransformer The ITransformer<TInput, TOutput> for converting TResult s to TApiModel s.
Parameters
authorityInvoker The TAuthority Func<T, TResult> resulting in the RequirementsGated<TResult> AuthorityResponse<TResult>.
Returns
A ValueTask<TResult> resulting in the TApiModel generated for the resulting AuthorityResponse<TResult>.
async ValueTask< TApiModel > IGraphQLAuthorityInvoker< TAuthority >. TTransformer (authorityInvoker) ?? throw new InvalidOperationException("Authority invocation should have returned a non-nullable result!")
new async ValueTask< TResult > ExecuteIfRequirementsSatisfied< TResult > (RequirementsGated< TResult > requirementsGate)
Unwrap a RequirementsGated<TResult> result, throwing a GraphQLException if they weren't met.
Private Attributes
async ValueTask< TApiModel > IGraphQLAuthorityInvoker< TAuthority >. TApiModel
Additional Inherited Members
Properties inherited from Tgstation.Server.Host.Authority.Core.AuthorityInvokerBase< TAuthority >
TAuthority Authority [get]
The IAuthority being invoked.
Detailed Description
Type Constraints
TAuthority : IAuthority
Definition at line 20 of file GraphQLAuthorityInvoker{TAuthority}.cs.
Constructor & Destructor Documentation
GraphQLAuthorityInvoker()
Tgstation.Server.Host.Authority.Core.GraphQLAuthorityInvoker< TAuthority >.GraphQLAuthorityInvoker (TAuthority authority, Security::IAuthorizationService authorizationService)
Initializes a new instance of the GraphQLAuthorityInvoker<TAuthority> class.
Parameters
authority The TAuthority .
authorizationService the authorization service to use.
Definition at line 47 of file GraphQLAuthorityInvoker{TAuthority}.cs.
            : base(authority, authorizationService)
        {
        }
Member Function Documentation
ExecuteDataLoader< TResult, TApiModel, TTransformer >()
async ValueTask< Dictionary< long, AuthorityResponse< TApiModel > > > IGraphQLAuthorityInvoker< TAuthority >. Tgstation.Server.Host.Authority.Core.GraphQLAuthorityInvoker< TAuthority >.ExecuteDataLoader< TResult, TApiModel, TTransformer > (Func< TAuthority, long, RequirementsGated< Projectable< TResult, TApiModel > > > authorityInvoker, IReadOnlyList< long > ids, QueryContext< AuthorityResponse< TApiModel > >? queryContext) private
Execute a batch loaded call on a given authorityInvoker .
Template Parameters
TResult The queried result of the TAuthority .
TApiModel The returned Type.
TTransformer The ITransformer<TInput, TOutput> for converting TResult s to TApiModel s.
Parameters
authorityInvoker The TAuthority Func<T, TResult> returning a RequirementsGated<TResult> Projectable<TQueried, TResult> from TResult to TApiModel .
ids The list of EntityId.Ids to batch load.
queryContext The active QueryContext<TEntity> mapped to an AuthorityResponse<TResult> of the TApiModel . MUST have been wrapped with Extensions.QueryContextExtensions.AuthorityResponseWrap<TResult>(QueryContext<TResult>). This will be unwrapped so only a QueryContext<TEntity> of TApiModel will be used.
Returns
A ValueTask<TResult> resulting in a Dictionary<TKey, TValue> of loaded EntityId.Ids to AuthorityResponse<TResult>s for the loaded TApiModel s.
Implements Tgstation.Server.Host.Authority.IGraphQLAuthorityInvoker< TAuthority >.
Definition at line 113 of file GraphQLAuthorityInvoker{TAuthority}.cs.
        {
            ArgumentNullException.ThrowIfNull(ids);
            var resultsTask = ValueTaskExtensions.WhenAll(
                ids.Select(
                    id =>
                    {
                        var requirementsGate = authorityInvoker(Authority, id);
                        return ExecuteIfRequirementsSatisfied(requirementsGate);
                    }),
                ids.Count);
            var unwrappedContext = queryContext?.AuthorityResponseUnwrap();
            var results = await resultsTask;
            var responses = await Projectable<TResult, TApiModel>.Combine(
                queryable => queryable
                    .Select(new TTransformer().ProjectedExpression)
                    .With(unwrappedContext),
                results);
            return responses;
        }
References Tgstation.Server.Host.Authority.Core.Projectable< TQueried, TResult >.Combine(), Tgstation.Server.Host.Authority.Core.GraphQLAuthorityInvoker< TAuthority >.TTransformer(), and Tgstation.Server.Common.Extensions.ValueTaskExtensions.WhenAll().
ExecuteIfRequirementsSatisfied< TResult >()
new async ValueTask< TResult > Tgstation.Server.Host.Authority.Core.GraphQLAuthorityInvoker< TAuthority >.ExecuteIfRequirementsSatisfied< TResult > (RequirementsGated< TResult > requirementsGate) private
Unwrap a RequirementsGated<TResult> result, throwing a GraphQLException if they weren't met.
Template Parameters
TResult The Type contained by the requirementsGate .
Parameters
requirementsGate The RequirementsGated<TResult> result.
Returns
A ValueTask<TResult> resulting in the TResult if the requirements were met.
Exceptions
GraphQLException Throw when requirements were not met.
Type Constraints
TResult : class
TResult : await
TResult : base.ExecuteIfRequirementsSatisfied
TResult : requirementsGate
Invoke()
async ValueTask IGraphQLAuthorityInvoker< TAuthority >. Tgstation.Server.Host.Authority.Core.GraphQLAuthorityInvoker< TAuthority >.Invoke (Func< TAuthority, RequirementsGated< AuthorityResponse > > authorityInvoker) private
Invoke a TAuthority method with no success result.
Parameters
authorityInvoker The TAuthority Func<T, TResult> resulting in the RequirementsGated<TResult> AuthorityResponse.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Authority.IGraphQLAuthorityInvoker< TAuthority >.
Definition at line 53 of file GraphQLAuthorityInvoker{TAuthority}.cs.
        {
            ArgumentNullException.ThrowIfNull(authorityInvoker);
            var requirementsGate = authorityInvoker(Authority);
            var authorityResponse = await ExecuteIfRequirementsSatisfied(requirementsGate);
            ThrowGraphQLErrorIfNecessary(authorityResponse, true);
        }
References Tgstation.Server.Host.Authority.Core.AuthorityInvokerBase< TAuthority >.Authority.
Invoke< TResult, TApiModel >()
async ValueTask< TApiModel > IGraphQLAuthorityInvoker< TAuthority >. Tgstation.Server.Host.Authority.Core.GraphQLAuthorityInvoker< TAuthority >.Invoke< TResult, TApiModel > (Func< TAuthority, RequirementsGated< AuthorityResponse< TResult > > > authorityInvoker) private
Invoke a TAuthority method and get the non-nullable result.
Template Parameters
TResult The AuthorityResponse<TResult>.Result Type.
TApiModel The resulting Type of the return value.
Parameters
authorityInvoker The TAuthority Func<T, TResult> resulting in the RequirementsGated<TResult> AuthorityResponse<TResult>.
Returns
A ValueTask<TResult> resulting in the TApiModel generated for the resulting AuthorityResponse<TResult>.
Implements Tgstation.Server.Host.Authority.IGraphQLAuthorityInvoker< TAuthority >.
InvokeAllowMissing< TResult, TApiModel >()
async ValueTask< TApiModel?> IGraphQLAuthorityInvoker< TAuthority >. Tgstation.Server.Host.Authority.Core.GraphQLAuthorityInvoker< TAuthority >.InvokeAllowMissing< TResult, TApiModel > (Func< TAuthority, RequirementsGated< AuthorityResponse< TResult > > > authorityInvoker) private
Invoke a TAuthority method and get the result.
Template Parameters
TResult The AuthorityResponse<TResult>.Result Type.
TApiModel The resulting Type of the return value.
Parameters
authorityInvoker The TAuthority Func<T, TResult> resulting in the RequirementsGated<TResult> AuthorityResponse<TResult>.
Returns
A ValueTask<TResult> resulting in the TApiModel generated for the resulting AuthorityResponse<TResult>.
Implements Tgstation.Server.Host.Authority.IGraphQLAuthorityInvoker< TAuthority >.
Type Constraints
TApiModel : default
Definition at line 63 of file GraphQLAuthorityInvoker{TAuthority}.cs.
                            : default
        {
            ArgumentNullException.ThrowIfNull(authorityInvoker);
            var requirementsGate = authorityInvoker(Authority);
            var authorityResponse = await ExecuteIfRequirementsSatisfied(requirementsGate);
            ThrowGraphQLErrorIfNecessary(authorityResponse, false);
            return authorityResponse.Result;
        }
References Tgstation.Server.Host.Authority.Core.AuthorityInvokerBase< TAuthority >.Authority.
InvokeTransformable< TResult, TApiModel, TTransformer >()
async ValueTask< TApiModel > IGraphQLAuthorityInvoker< TAuthority >. Tgstation.Server.Host.Authority.Core.GraphQLAuthorityInvoker< TAuthority >.InvokeTransformable< TResult, TApiModel, TTransformer > (Func< TAuthority, RequirementsGated< AuthorityResponse< TResult > > > authorityInvoker) private
Invoke a TAuthority method and get the non-nullable result.
Template Parameters
TResult The AuthorityResponse<TResult>.Result Type.
TApiModel The resulting Type of the return value.
TTransformer The ITransformer<TInput, TOutput> for converting TResult s to TApiModel s.
Parameters
authorityInvoker The TAuthority Func<T, TResult> resulting in the RequirementsGated<TResult> AuthorityResponse<TResult>.
Returns
A ValueTask<TResult> resulting in the TApiModel generated for the resulting AuthorityResponse<TResult>.
Implements Tgstation.Server.Host.Authority.IGraphQLAuthorityInvoker< TAuthority >.
InvokeTransformableAllowMissing< TResult, TApiModel, TTransformer >()
async ValueTask< TApiModel?> IGraphQLAuthorityInvoker< TAuthority >. Tgstation.Server.Host.Authority.Core.GraphQLAuthorityInvoker< TAuthority >.InvokeTransformableAllowMissing< TResult, TApiModel, TTransformer > (Func< TAuthority, RequirementsGated< AuthorityResponse< TResult > > > authorityInvoker) private
Invoke a TAuthority method and get the result.
Template Parameters
TResult The AuthorityResponse<TResult>.Result Type.
TApiModel The resulting Type of the return value.
TTransformer The ITransformer<TInput, TOutput> for converting TResult s to TApiModel s.
Parameters
authorityInvoker The TAuthority Func<T, TResult> resulting in the RequirementsGated<TResult> AuthorityResponse<TResult>.
Returns
A ValueTask<TResult> resulting in the TApiModel generated for the resulting AuthorityResponse<TResult>.
Implements Tgstation.Server.Host.Authority.IGraphQLAuthorityInvoker< TAuthority >.
Type Constraints
TApiModel : default
Definition at line 76 of file GraphQLAuthorityInvoker{TAuthority}.cs.
                            : default
        {
            ArgumentNullException.ThrowIfNull(authorityInvoker);
            var requirementsGate = authorityInvoker(Authority);
            var authorityResponse = await ExecuteIfRequirementsSatisfied(requirementsGate);
            ThrowGraphQLErrorIfNecessary(authorityResponse, false);
            var result = authorityResponse.Result;
            if (result == null)
                return default;
            return result.ToApi();
        }
References Tgstation.Server.Host.Authority.Core.AuthorityInvokerBase< TAuthority >.Authority.
InvokeTransformableQueryable< TResult, TApiModel, TTransformer >()
async ValueTask< IQueryable< TApiModel > > IGraphQLAuthorityInvoker< TAuthority >. Tgstation.Server.Host.Authority.Core.GraphQLAuthorityInvoker< TAuthority >.InvokeTransformableQueryable< TResult, TApiModel, TTransformer > (Func< TAuthority, RequirementsGated< IQueryable< TResult > > > authorityInvoker, Func< IQueryable< TResult >, IQueryable< TResult > >? preTransformer) private
Invoke a TAuthority method and get the transformed result.
Template Parameters
TResult The Type returned by the TAuthority .
TApiModel The returned Type.
TTransformer The ITransformer<TInput, TOutput> for converting TResult s to TApiModel s.
Parameters
authorityInvoker The TAuthority Func<T, TResult> returning a IQueryable<T> TResult .
preTransformer Optional transformer for the IQueryable<T> run once it has been acquired.
Returns
A ValueTask<TResult> resulting in the IQueryable<T> TResult returned on success or null if the requirements weren't satisfied.
Implements Tgstation.Server.Host.Authority.IGraphQLAuthorityInvoker< TAuthority >.
Definition at line 92 of file GraphQLAuthorityInvoker{TAuthority}.cs.
        {
            ArgumentNullException.ThrowIfNull(authorityInvoker);
            var requirementsGate = authorityInvoker(Authority);
            var queryable = await ExecuteIfRequirementsSatisfied(requirementsGate);
            if (preTransformer != null)
                queryable = preTransformer(queryable);
            if (typeof(EntityId).IsAssignableFrom(typeof(TResult)))
                queryable = queryable.OrderBy(item => ((EntityId)(object)item).Id!.Value); // order by ID to fix an EFCore warning
            var expression = new TTransformer().Expression;
            return queryable
                .Select(expression);
        }
References Tgstation.Server.Host.Authority.Core.AuthorityInvokerBase< TAuthority >.Authority, Tgstation.Server.Host.Authority.Id, and Tgstation.Server.Host.Authority.Core.GraphQLAuthorityInvoker< TAuthority >.TTransformer().
OnRequirementsFailure()
override void Tgstation.Server.Host.Authority.Core.GraphQLAuthorityInvoker< TAuthority >.OnRequirementsFailure (AuthorizationFailure authFailure) protected virtual
Called to handle generic behavior when requirements evaluation fails.
Parameters
authFailure The AuthorizationFailure.
Reimplemented from Tgstation.Server.Host.Authority.Core.AuthorityInvokerBase< TAuthority >.
TApiModel()
async ValueTask< TApiModel > IGraphQLAuthorityInvoker< TAuthority >. Tgstation.Server.Host.Authority.Core.GraphQLAuthorityInvoker< TAuthority >.TApiModel (authorityInvoker) new private
ThrowGraphQLErrorIfNecessary< TAuthorityResponse >()
static TAuthorityResponse Tgstation.Server.Host.Authority.Core.GraphQLAuthorityInvoker< TAuthority >.ThrowGraphQLErrorIfNecessary< TAuthorityResponse > (TAuthorityResponse authorityResponse, bool errorOnMissing) static
Throws a ErrorMessageException for errored authorityResponse s.
Template Parameters
TAuthorityResponse The AuthorityResponse Type being checked.
Parameters
authorityResponse The potentially errored authorityResponse or null if requirements evaluation failed.
errorOnMissing If an error should be raised for HttpFailureResponse.NotFound and HttpFailureResponse.Gone failures.
Returns
authorityResponse if an ErrorMessageException wasn't thrown.
Type Constraints
TAuthorityResponse : AuthorityResponse
Definition at line 30 of file GraphQLAuthorityInvoker{TAuthority}.cs.
                                     : AuthorityResponse
        {
            if (authorityResponse.Success
                || ((authorityResponse.FailureResponse.Value == HttpFailureResponse.NotFound
                || authorityResponse.FailureResponse.Value == HttpFailureResponse.Gone) && !errorOnMissing))
                return authorityResponse;
            var fallbackString = authorityResponse.FailureResponse.ToString()!;
            throw new ErrorMessageException(authorityResponse.ErrorMessage, fallbackString);
        }
References Tgstation.Server.Host.Authority.Core.AuthorityResponse< TResult >.FailureResponse.
TTransformer()
async ValueTask< TApiModel > IGraphQLAuthorityInvoker< TAuthority >. Tgstation.Server.Host.Authority.Core.GraphQLAuthorityInvoker< TAuthority >.TTransformer (authorityInvoker) new private
Referenced by Tgstation.Server.Host.Authority.Core.GraphQLAuthorityInvoker< TAuthority >.ExecuteDataLoader< TResult, TApiModel, TTransformer >(), and Tgstation.Server.Host.Authority.Core.GraphQLAuthorityInvoker< TAuthority >.InvokeTransformableQueryable< TResult, TApiModel, TTransformer >().
Member Data Documentation
TApiModel
async ValueTask< TApiModel > IGraphQLAuthorityInvoker< TAuthority >. Tgstation.Server.Host.Authority.Core.GraphQLAuthorityInvoker< TAuthority >.TApiModel private
Definition at line 148 of file GraphQLAuthorityInvoker{TAuthority}.cs.
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Authority/Core/GraphQLAuthorityInvoker{TAuthority}.cs