tgstation-server: Tgstation.Server.Host.Components.Repository.LibGit2RepositoryFactory Class Reference
Tgstation.Server.Host.Components.Repository.LibGit2RepositoryFactory Class Reference sealed
Public Member Functions
LibGit2RepositoryFactory (ILogger< LibGit2RepositoryFactory > logger)
Initializes a new instance of the LibGit2RepositoryFactory class.
void CreateInMemory ()
Create and destory an in-memeory LibGit2Sharp.IRepository.Used as a test of the libgit2 native library.
async ValueTask< LibGit2Sharp.IRepository > CreateFromPath (string path, CancellationToken cancellationToken)
Load a LibGit2Sharp.IRepository from a given path .
Parameters
path The full path to the LibGit2Sharp.IRepository.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the loaded LibGit2Sharp.IRepository.
Task Clone (Uri url, CloneOptions cloneOptions, string path, CancellationToken cancellationToken)
Clone a remote LibGit2Sharp.IRepository.
Parameters
url The Uri of the remote.
cloneOptions The CloneOptions.
path The full path to the cloned LibGit2Sharp.IRepository.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
CredentialsHandler GenerateCredentialsHandler (string? username, string? password)
Generate a CredentialsHandler from a given username and password .
Parameters
username The optional username to use in the CredentialsHandler.
password The optional password to use in the CredentialsHandler.
Returns
A new CredentialsHandler.
void CheckBadCredentialsException (LibGit2SharpException exception)
Rethrow the authentication failure message as a JobException if it is one.
Parameters
exception The current LibGit2SharpException.
Private Attributes
readonly ILogger< LibGit2RepositoryFactory > logger
The ILogger for the LibGit2RepositoryFactory.
Detailed Description
Definition at line 16 of file LibGit2RepositoryFactory.cs.
Constructor & Destructor Documentation
LibGit2RepositoryFactory()
Tgstation.Server.Host.Components.Repository.LibGit2RepositoryFactory.LibGit2RepositoryFactory (ILogger< LibGit2RepositoryFactory > logger)
Initializes a new instance of the LibGit2RepositoryFactory class.
Parameters
logger The value of logger.
Definition at line 27 of file LibGit2RepositoryFactory.cs.
        {
            this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }
References Tgstation.Server.Host.Components.Repository.LibGit2RepositoryFactory.logger.
Member Function Documentation
CheckBadCredentialsException()
void Tgstation.Server.Host.Components.Repository.LibGit2RepositoryFactory.CheckBadCredentialsException (LibGit2SharpException exception)
Rethrow the authentication failure message as a JobException if it is one.
Parameters
exception The current LibGit2SharpException.
Implements Tgstation.Server.Host.Components.Repository.ICredentialsProvider.
Definition at line 111 of file LibGit2RepositoryFactory.cs.
        {
            ArgumentNullException.ThrowIfNull(exception);
            if (exception.Message == "too many redirects or authentication replays")
                throw new JobException("Bad git credentials exchange!", exception);
            if (exception.Message == ErrorCode.RepoCredentialsRequired.Describe())
                throw new JobException(ErrorCode.RepoCredentialsRequired);
            // submodule recursion
            if (exception.InnerException is LibGit2SharpException innerException)
                CheckBadCredentialsException(innerException);
        }
References Tgstation.Server.Host.Components.Repository.LibGit2RepositoryFactory.CheckBadCredentialsException().
Referenced by Tgstation.Server.Host.Components.Repository.LibGit2RepositoryFactory.CheckBadCredentialsException(), and Tgstation.Server.Host.Components.Repository.LibGit2RepositoryFactory.Clone().
Clone()
Task Tgstation.Server.Host.Components.Repository.LibGit2RepositoryFactory.Clone (Uri url, CloneOptions cloneOptions, string path, CancellationToken cancellationToken)
Clone a remote LibGit2Sharp.IRepository.
Parameters
url The Uri of the remote.
cloneOptions The CloneOptions.
path The full path to the cloned LibGit2Sharp.IRepository.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implements Tgstation.Server.Host.Components.Repository.ILibGit2RepositoryFactory.
References Tgstation.Server.Host.Components.Repository.LibGit2RepositoryFactory.CheckBadCredentialsException(), and Tgstation.Server.Host.Components.Repository.LibGit2RepositoryFactory.logger.
CreateFromPath()
async ValueTask< LibGit2Sharp.IRepository > Tgstation.Server.Host.Components.Repository.LibGit2RepositoryFactory.CreateFromPath (string path, CancellationToken cancellationToken)
Load a LibGit2Sharp.IRepository from a given path .
Parameters
path The full path to the LibGit2Sharp.IRepository.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the loaded LibGit2Sharp.IRepository.
Implements Tgstation.Server.Host.Components.Repository.ILibGit2RepositoryFactory.
Definition at line 41 of file LibGit2RepositoryFactory.cs.
        {
            ArgumentNullException.ThrowIfNull(path);
            var repo = await Task.Factory.StartNew<LibGit2Sharp.IRepository>(
                () =>
                {
                    logger.LogTrace("Creating libgit2 repository at {repoPath}...", path);
                    return new LibGit2Sharp.Repository(path);
                },
                cancellationToken,
                DefaultIOManager.BlockingTaskCreationOptions,
                TaskScheduler.Current);
            return repo;
        }
References Tgstation.Server.Host.IO.DefaultIOManager.BlockingTaskCreationOptions, and Tgstation.Server.Host.Components.Repository.LibGit2RepositoryFactory.logger.
CreateInMemory()
void Tgstation.Server.Host.Components.Repository.LibGit2RepositoryFactory.CreateInMemory ()
Create and destory an in-memeory LibGit2Sharp.IRepository.Used as a test of the libgit2 native library.
Implements Tgstation.Server.Host.Components.Repository.ILibGit2RepositoryFactory.
Definition at line 33 of file LibGit2RepositoryFactory.cs.
        {
            logger.LogTrace("Creating in-memory libgit2 repository...");
            using (new LibGit2Sharp.Repository())
                logger.LogTrace("Success");
        }
References Tgstation.Server.Host.Components.Repository.LibGit2RepositoryFactory.logger.
GenerateCredentialsHandler()
CredentialsHandler Tgstation.Server.Host.Components.Repository.LibGit2RepositoryFactory.GenerateCredentialsHandler (string? username, string? password)
Generate a CredentialsHandler from a given username and password .
Parameters
username The optional username to use in the CredentialsHandler.
password The optional password to use in the CredentialsHandler.
Returns
A new CredentialsHandler.
Implements Tgstation.Server.Host.Components.Repository.ICredentialsProvider.
References Tgstation.Server.Host.Components.Repository.LibGit2RepositoryFactory.logger.
Member Data Documentation
logger
readonly ILogger<LibGit2RepositoryFactory> Tgstation.Server.Host.Components.Repository.LibGit2RepositoryFactory.logger private
The ILogger for the LibGit2RepositoryFactory.
Definition at line 21 of file LibGit2RepositoryFactory.cs.
Referenced by Tgstation.Server.Host.Components.Repository.LibGit2RepositoryFactory.Clone(), Tgstation.Server.Host.Components.Repository.LibGit2RepositoryFactory.CreateFromPath(), Tgstation.Server.Host.Components.Repository.LibGit2RepositoryFactory.CreateInMemory(), Tgstation.Server.Host.Components.Repository.LibGit2RepositoryFactory.GenerateCredentialsHandler(), and Tgstation.Server.Host.Components.Repository.LibGit2RepositoryFactory.LibGit2RepositoryFactory().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Repository/LibGit2RepositoryFactory.cs