tgstation-server: Tgstation.Server.Host.Core.JobManager Class Reference
Tgstation.Server.Host.Core.JobManager Class Reference
Public Member Functions
JobManager (IDatabaseContextFactory databaseContextFactory, ILogger< JobManager > logger)
Construct a JobManager
void Dispose ()
Task RegisterOperation (Job job, Func< Job, IDatabaseContext, Action< int >, CancellationToken, Task > operation, CancellationToken cancellationToken)
Registers a given Job and begins running it
async Task StartAsync (CancellationToken cancellationToken)
async Task StopAsync (CancellationToken cancellationToken)
async Task< bool > CancelJob (Job job, User user, bool blocking, CancellationToken cancellationToken)
Cancels a give job
int JobProgress (Job job)
Get the Api.Models.Job.Progress for a job
async Task WaitForJobCompletion (Job job, User canceller, CancellationToken jobCancellationToken, CancellationToken cancellationToken)
Wait for a given job to complete
Private Member Functions
JobHandler CheckGetJob (Job job)
Gets the JobHandler for a given job if it exists
async Task RunJob (Job job, Func< Job, IDatabaseContext, CancellationToken, Task > operation, CancellationToken cancellationToken)
Runner for JobHandlers
Private Attributes
readonly IDatabaseContextFactory databaseContextFactory
The IServiceProvider for the JobManager
readonly ILogger< JobManager > logger
The ILogger for the JobManager
readonly Dictionary< long, JobHandler > jobs
Dictionary<TKey, TValue> of Api.Models.Internal.Job.Id to running JobHandlers
Detailed Description
Definition at line 13 of file JobManager.cs.
Constructor & Destructor Documentation
Tgstation.Server.Host.Core.JobManager.JobManager (IDatabaseContextFactory databaseContextFactory, ILogger< JobManager > logger)
Construct a JobManager
Parameters
databaseContextFactory The value of databaseContextFactory
logger The value of logger
Definition at line 35 of file JobManager.cs.
         {
             this.databaseContextFactory = databaseContextFactory ?? throw new ArgumentNullException(nameof(databaseContextFactory));
             this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
             jobs = new Dictionary<long, JobHandler>();
         }
Member Function Documentation
async Task<bool> Tgstation.Server.Host.Core.JobManager.CancelJob (Job job, User user, bool blocking, CancellationToken cancellationToken)
Cancels a give job
Implements Tgstation.Server.Host.Core.IJobManager.
Definition at line 219 of file JobManager.cs.
References Tgstation.Server.Host.Core.JobHandler.Cancel(), Tgstation.Server.Host.Models.Job.CancelledBy, Tgstation.Server.Api.Models.Internal.Job.Id, Tgstation.Server.Api.Models.Internal.User.Id, and Tgstation.Server.Host.Core.JobHandler.Wait().
         {
             if (job == null)
                 throw new ArgumentNullException(nameof(job));
             if (user == null)
                 throw new ArgumentNullException(nameof(user));
             JobHandler handler;
             try
             {
                 handler = CheckGetJob(job);
             }
             catch (InvalidOperationException)
             {
                 //this is fine
                 return false;
             }
             handler.Cancel();  //this will ensure the db update is only done once
             await databaseContextFactory.UseContext(async databaseContext =>
             {
                 job = new Job { Id = job.Id };
                 databaseContext.Jobs.Attach(job);
                 user = new User { Id = user.Id };
                 databaseContext.Users.Attach(user);
                 job.CancelledBy = user;
                 //let either startup or cancellation set job.cancelled
                 await databaseContext.Save(cancellationToken).ConfigureAwait(false);
             }).ConfigureAwait(false);
             if (blocking)
                 await handler.Wait(cancellationToken).ConfigureAwait(false);
             return true;
         }
JobHandler Tgstation.Server.Host.Core.JobManager.CheckGetJob (Job job) private
Gets the JobHandler for a given job if it exists
Parameters
job The Job to get the JobHandler for
Returns
The JobHandler
Definition at line 54 of file JobManager.cs.
References Tgstation.Server.Api.Models.Internal.Job.Id.
         {
             lock (this)
             {
                 if (!jobs.TryGetValue(job.Id, out JobHandler jobHandler))
                     throw new InvalidOperationException("Job not running!");
                 return jobHandler;
             }
         }
void Tgstation.Server.Host.Core.JobManager.Dispose ()
Definition at line 43 of file JobManager.cs.
         {
             foreach (var job in jobs)
                 job.Value.Dispose();
         }
int Tgstation.Server.Host.Core.JobManager.JobProgress (Job job)
Get the Api.Models.Job.Progress for a job
Implements Tgstation.Server.Host.Core.IJobManager.
Definition at line 252 of file JobManager.cs.
References Tgstation.Server.Api.Models.Internal.Job.Id.
         {
             if (job == null)
                 throw new ArgumentNullException(nameof(job));
             lock (this)
             {
                 if (!jobs.TryGetValue(job.Id, out var handler))
                     return null;
                 return handler.Progress;
             }
         }
Task Tgstation.Server.Host.Core.JobManager.RegisterOperation (Job job, Func< Job, IDatabaseContext, Action< int >, CancellationToken, Task > operation, CancellationToken cancellationToken)
Registers a given Job and begins running it
Implements Tgstation.Server.Host.Core.IJobManager.
async Task Tgstation.Server.Host.Core.JobManager.RunJob (Job job, Func< Job, IDatabaseContext, CancellationToken, Task > operation, CancellationToken cancellationToken) private
Runner for JobHandlers
Parameters
job The Job being run
operation The operation for the job
cancellationToken The CancellationToken for the operation
Returns
A Task representing the running operation
Definition at line 71 of file JobManager.cs.
References Tgstation.Server.Api.Models.Internal.Job.Cancelled, Tgstation.Server.Api.Models.Internal.Job.Description, Tgstation.Server.Api.Models.Internal.Job.ExceptionDetails, Tgstation.Server.Api.Models.Instance.Id, Tgstation.Server.Api.Models.Internal.Job.Id, Tgstation.Server.Api.Models.Internal.User.Id, Tgstation.Server.Host.Models.Job.Instance, Tgstation.Server.Host.Models.Job.PostComplete, Tgstation.Server.Api.Models.Internal.Job.StartedAt, Tgstation.Server.Host.Models.Job.StartedBy, and Tgstation.Server.Api.Models.Internal.Job.StoppedAt.
         {
             try
             {
                 await databaseContextFactory.UseContext(async databaseContext =>
                 {
                     async Task HandleExceptions(Task task)
                     {
                         void LogRegularException() => logger.LogDebug("Job {0} exited with error! Exception: {1}", job.Id, job.ExceptionDetails);
                         try
{
                             await task.ConfigureAwait(false);
                         }
                         catch (OperationCanceledException)
{
                             logger.LogDebug("Job {0} cancelled!", job.Id);
                             job.Cancelled = true;
                         }
                         catch (JobException e)
{
                             job.ExceptionDetails = e.Message;
                             LogRegularException();
                             if (e.InnerException != null)
                                 logger.LogDebug("Inner exception for job {0}: {1}", job.Id, e.InnerException);
                         }
                         catch (Exception e)
{
                             job.ExceptionDetails = e.ToString();
                             LogRegularException();
                         }
                         finally
{
                             job.StoppedAt = DateTimeOffset.Now;
                         }
                     }
                     async Task RunJobInternal()
                     {
                         var oldJob = job;
                         job = new Job { Id = oldJob.Id };
                         databaseContext.Jobs.Attach(job);
                         await operation(job, databaseContext, cancellationToken).ConfigureAwait(false);
                         logger.LogDebug("Job {0} completed!", job.Id);
                     };
                     await HandleExceptions(RunJobInternal()).ConfigureAwait(false);
                     await databaseContext.Save(default).ConfigureAwait(false);
                     bool JobErroredOrCancelled() => job.ExceptionDetails != null || job.Cancelled == true;
                     //ok so, now it's time for the post commit step if it exists
                     if (!JobErroredOrCancelled() && job.PostComplete != null)
                     {
                         await HandleExceptions(job.PostComplete(cancellationToken)).ConfigureAwait(false);
                         if (JobErroredOrCancelled())
                             await databaseContext.Save(default).ConfigureAwait(false);
                     }
                 }).ConfigureAwait(false);
             }
             finally
             {
                 lock (this)
                 {
                     var handler = jobs[job.Id];
                     jobs.Remove(job.Id);
                     handler.Dispose();
                 }
             }
         }
async Task Tgstation.Server.Host.Core.JobManager.StartAsync (CancellationToken cancellationToken)
Definition at line 184 of file JobManager.cs.
References Tgstation.Server.Api.Models.Internal.Job.Cancelled.
         {
             logger.LogTrace("Starting job manager...");
             await databaseContextFactory.UseContext(async databaseContext =>
             {
                 //mark all jobs as cancelled
                 var badJobs = await databaseContext.Jobs.Where(y => !y.StoppedAt.HasValue).Select(y => y.Id).ToListAsync(cancellationToken).ConfigureAwait(false);
                 if (badJobs.Count > 0)
                 {
                     logger.LogTrace("Cleaning {0} unfinished jobs...", badJobs.Count);
                     foreach (var I in badJobs)
                     {
                         var job = new Job { Id = I };
                         databaseContext.Jobs.Attach(job);
                         job.Cancelled = true;
                         job.StoppedAt = DateTimeOffset.Now;
                     }
                     await databaseContext.Save(cancellationToken).ConfigureAwait(false);
                 }
             }).ConfigureAwait(false);
             logger.LogDebug("Job manager started!");
         }
async Task Tgstation.Server.Host.Core.JobManager.StopAsync (CancellationToken cancellationToken)
Definition at line 208 of file JobManager.cs.
         {
             var joinTasks = jobs.Select(x =>
             {
                 x.Value.Cancel();
                 return x.Value.Wait(cancellationToken);
             });
             await Task.WhenAll(joinTasks).ConfigureAwait(false);
         }
async Task Tgstation.Server.Host.Core.JobManager.WaitForJobCompletion (Job job, User canceller, CancellationToken jobCancellationToken, CancellationToken cancellationToken)
Wait for a given job to complete
Implements Tgstation.Server.Host.Core.IJobManager.
Definition at line 265 of file JobManager.cs.
References Tgstation.Server.Api.Models.Internal.Job.Id, and Tgstation.Server.Host.Core.JobHandler.Wait().
         {
             if (job == null)
                 throw new ArgumentNullException(nameof(job));
             if (canceller == null)
                 throw new ArgumentNullException(nameof(canceller));
             JobHandler handler;
             lock (this)
             {
                 if (!jobs.TryGetValue(job.Id, out handler))
                     return;
             }
             Task cancelTask = null;
             using (jobCancellationToken.Register(() => cancelTask = CancelJob(job, canceller, true, cancellationToken)))
                 await handler.Wait(cancellationToken).ConfigureAwait(false);
             if (cancelTask != null)
                 await cancelTask.ConfigureAwait(false);
         }
Member Data Documentation
readonly IDatabaseContextFactory Tgstation.Server.Host.Core.JobManager.databaseContextFactory private
The IServiceProvider for the JobManager
Definition at line 18 of file JobManager.cs.
readonly Dictionary<long, JobHandler> Tgstation.Server.Host.Core.JobManager.jobs private
Dictionary<TKey, TValue> of Api.Models.Internal.Job.Id to running JobHandlers
Definition at line 28 of file JobManager.cs.
readonly ILogger<JobManager> Tgstation.Server.Host.Core.JobManager.logger private
The ILogger for the JobManager
Definition at line 23 of file JobManager.cs.
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Core/JobManager.cs