tgstation-server: Tgstation.Server.Host.Extensions.FetchOptionsExtensions Class Reference
Tgstation.Server.Host.Extensions.FetchOptionsExtensions Class Reference
Extension methods for FetchOptions.
Static Public Member Functions
static FetchOptions Hydrate (this FetchOptions fetchOptions, ILogger logger, JobProgressReporter? progressReporter, CredentialsHandler credentialsHandler, CancellationToken cancellationToken)
Hydrate a given set of fetchOptions .
Static Private Member Functions
static TransferProgressHandler TransferProgressHandler (ILogger logger, JobProgressReporter? progressReporter, CancellationToken cancellationToken)
Generate a LibGit2Sharp.Handlers.TransferProgressHandler from a given progressReporter and cancellationToken .
Detailed Description
Extension methods for FetchOptions.
Definition at line 16 of file FetchOptionsExtensions.cs.
Member Function Documentation
Hydrate()
static FetchOptions Tgstation.Server.Host.Extensions.FetchOptionsExtensions.Hydrate (this FetchOptions fetchOptions, ILogger logger, JobProgressReporter? progressReporter, CredentialsHandler credentialsHandler, CancellationToken cancellationToken) static
Hydrate a given set of fetchOptions .
Parameters
fetchOptions The FetchOptions to hydrate.
logger The ILogger for the operation.
progressReporter The optional JobProgressReporter.
credentialsHandler The optional CredentialsHandler.
cancellationToken The CancellationToken for the operation.
Returns
The hydrated fetchOptions .
Definition at line 27 of file FetchOptionsExtensions.cs.
        {
            ArgumentNullException.ThrowIfNull(fetchOptions);
            ArgumentNullException.ThrowIfNull(logger);
            fetchOptions.OnProgress = _ => !cancellationToken.IsCancellationRequested;
            fetchOptions.OnTransferProgress = transferProgress =>
            {
                if (progressReporter != null)
                {
                    var percentage = ((double)transferProgress.IndexedObjects + transferProgress.ReceivedObjects) / (transferProgress.TotalObjects * 2);
                    progressReporter.ReportProgress(percentage);
                }
                return !cancellationToken.IsCancellationRequested;
            };
            fetchOptions.OnUpdateTips = (_, _, _) => !cancellationToken.IsCancellationRequested;
            fetchOptions.CredentialsProvider = credentialsHandler;
            fetchOptions.RepositoryOperationStarting = _ => !cancellationToken.IsCancellationRequested;
            fetchOptions.OnTransferProgress = TransferProgressHandler(
                logger,
                progressReporter,
                cancellationToken);
            return fetchOptions;
        }
References Tgstation.Server.Host.Jobs.JobProgressReporter.ReportProgress(), and Tgstation.Server.Host.Extensions.FetchOptionsExtensions.TransferProgressHandler().
TransferProgressHandler()
static TransferProgressHandler Tgstation.Server.Host.Extensions.FetchOptionsExtensions.TransferProgressHandler (ILogger logger, JobProgressReporter? progressReporter, CancellationToken cancellationToken) static private
Generate a LibGit2Sharp.Handlers.TransferProgressHandler from a given progressReporter and cancellationToken .
Parameters
logger The ILogger for the operation.
progressReporter The optional JobProgressReporter of the operation.
cancellationToken The CancellationToken for the operation.
Returns
A new LibGit2Sharp.Handlers.TransferProgressHandler based on progressReporter .
Referenced by Tgstation.Server.Host.Extensions.FetchOptionsExtensions.Hydrate().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Extensions/FetchOptionsExtensions.cs