tgstation-server: Tgstation.Server.Host.Core.AsyncDelayer Class Reference
Tgstation.Server.Host.Core.AsyncDelayer Class Reference
Public Member Functions
Task Delay (TimeSpan timeSpan, CancellationToken cancellationToken)
Create a Task that completes after a given timeSpan
Detailed Description
Definition at line 8 of file AsyncDelayer.cs.
Member Function Documentation
Delay()
Task Tgstation.Server.Host.Core.AsyncDelayer.Delay (TimeSpan timeSpan, CancellationToken cancellationToken)
Create a Task that completes after a given timeSpan
Implements Tgstation.Server.Host.Core.IAsyncDelayer.
Referenced by Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.InitControllers(), Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.MonitorLifetimes(), and Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.MonitorLifetimes().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Core/AsyncDelayer.cs