tgstation-server: Tgstation.Server.Host.Components.Engine.PosixByondInstaller Class Reference
Tgstation.Server.Host.Components.Engine.PosixByondInstaller Class Reference
IEngineInstaller for Posix systems.
Public Member Functions
PosixByondInstaller (IPostWriteHandler postWriteHandler, IIOManager ioManager, IFileDownloader fileDownloader, ILogger< PosixByondInstaller > logger)
Initializes a new instance of the PosixByondInstaller class.
override ValueTask Install (EngineVersion version, string path, bool deploymentPipelineProcesses, CancellationToken cancellationToken)
Does actions necessary to get an extracted installation working.
Parameters
version The EngineVersion being installed.
path The path to the installation.
deploymentPipelineProcesses If the operation should consider processes it launches to be part of the deployment pipeline.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
override ValueTask UpgradeInstallation (EngineVersion version, string path, CancellationToken cancellationToken)
Does actions necessary to get upgrade a version installed by a previous version of TGS.
Parameters
version The EngineVersion being installed.
path The path to the installation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
override ValueTask TrustDmbPath (EngineVersion version, string fullDmbPath, CancellationToken cancellationToken)
Add a given fullDmbPath to the trusted DMBs list in BYOND's config.
Parameters
version The EngineVersion being used.
fullDmbPath Full path to the .dmb that should be trusted.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Public Member Functions inherited from Tgstation.Server.Host.Components.Engine.ByondInstallerBase
override IEngineInstallation CreateInstallation (EngineVersion version, string path, Task installationTask)
Creates an IEngineInstallation for a given version .
Parameters
version The EngineVersion of the installation.
path The path to the installation.
installationTask The Task representing the installation process for the installation.
Returns
The IEngineInstallation.
override async Task CleanCache (CancellationToken cancellationToken)
Attempts to cleans the engine's cache folder for the system.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
override async ValueTask< IEngineInstallationData > DownloadVersion (EngineVersion version, JobProgressReporter? progressReporter, CancellationToken cancellationToken)
Download a given engine version .
Parameters
version The EngineVersion of the engine to download.
jobProgressReporter The optional JobProgressReporter for the operation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IEngineInstallationData for the download.
abstract IEngineInstallation CreateInstallation (EngineVersion version, string path, Task installationTask)
Creates an IEngineInstallation for a given version .
Parameters
version The EngineVersion of the installation.
path The path to the installation.
installationTask The Task representing the installation process for the installation.
Returns
The IEngineInstallation.
abstract Task CleanCache (CancellationToken cancellationToken)
Attempts to cleans the engine's cache folder for the system.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
abstract ValueTask Install (EngineVersion version, string path, bool deploymentPipelineProcesses, CancellationToken cancellationToken)
Does actions necessary to get an extracted installation working.
Parameters
version The EngineVersion being installed.
path The path to the installation.
deploymentPipelineProcesses If the operation should consider processes it launches to be part of the deployment pipeline.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
abstract ValueTask UpgradeInstallation (EngineVersion version, string path, CancellationToken cancellationToken)
Does actions necessary to get upgrade a version installed by a previous version of TGS.
Parameters
version The EngineVersion being installed.
path The path to the installation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
abstract ValueTask< IEngineInstallationData > DownloadVersion (EngineVersion version, JobProgressReporter? jobProgressReporter, CancellationToken cancellationToken)
Download a given engine version .
Parameters
version The EngineVersion of the engine to download.
jobProgressReporter The optional JobProgressReporter for the operation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IEngineInstallationData for the download.
abstract ValueTask TrustDmbPath (EngineVersion version, string fullDmbPath, CancellationToken cancellationToken)
Add a given fullDmbPath to the trusted DMBs list in BYOND's config.
Parameters
version The EngineVersion being used.
fullDmbPath Full path to the .dmb that should be trusted.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
IEngineInstallation CreateInstallation (EngineVersion version, string path, Task installationTask)
Creates an IEngineInstallation for a given version .
ValueTask< IEngineInstallationData > DownloadVersion (EngineVersion version, JobProgressReporter? jobProgressReporter, CancellationToken cancellationToken)
Download a given engine version .
ValueTask Install (EngineVersion version, string path, bool deploymentPipelineProcesses, CancellationToken cancellationToken)
Does actions necessary to get an extracted installation working.
ValueTask UpgradeInstallation (EngineVersion version, string path, CancellationToken cancellationToken)
Does actions necessary to get upgrade a version installed by a previous version of TGS.
ValueTask TrustDmbPath (EngineVersion version, string fullDmbPath, CancellationToken cancellationToken)
Add a given fullDmbPath to the trusted DMBs list in BYOND's config.
Task CleanCache (CancellationToken cancellationToken)
Attempts to cleans the engine's cache folder for the system.
Protected Member Functions
override string GetDreamDaemonName (Version byondVersion, out bool supportsCli)
Get the file name of the DreamDaemon executable.
Parameters
byondVersion The Version of BYOND to select the executable name for.
supportsCli Whether or not the returned path supports being run as a command-line application.
Returns
The file name of the DreamDaemon executable.
Protected Member Functions inherited from Tgstation.Server.Host.Components.Engine.ByondInstallerBase
ByondInstallerBase (IIOManager ioManager, ILogger< ByondInstallerBase > logger, IFileDownloader fileDownloader)
Initializes a new instance of the ByondInstallerBase class.
abstract string GetDreamDaemonName (Version byondVersion, out bool supportsCli)
Get the file name of the DreamDaemon executable.
virtual IEnumerable< string > AdditionalCacheCleanFilePaths (string configDirectory)
List off additional file paths in the configDirectory to delete.
Protected Member Functions inherited from Tgstation.Server.Host.Components.Engine.EngineInstallerBase
EngineInstallerBase (IIOManager ioManager, ILogger< EngineInstallerBase > logger)
Initializes a new instance of the EngineInstallerBase class.
void CheckVersionValidity (EngineVersion version)
Check that a given version is of type EngineType.Byond.
Properties
override string PathToUserFolder [get]
override string DreamMakerName [get]
override string ByondRevisionsUrlTemplate [get]
Properties inherited from Tgstation.Server.Host.Components.Engine.ByondInstallerBase
override EngineType TargetEngineType [get]
abstract string PathToUserFolder [get]
Path to the system user's local BYOND folder.
abstract string DreamMakerName [get]
Path to the DreamMaker executable.
abstract string ByondRevisionsUrlTemplate [get]
Gets the URL formatter string for downloading a byond version of {0:Major} {1:Minor}.
Properties inherited from Tgstation.Server.Host.Components.Engine.EngineInstallerBase
abstract EngineType TargetEngineType [get]
The EngineType the installer supports.
IIOManager IOManager [get]
Gets the IIOManager for the EngineInstallerBase.
ILogger< EngineInstallerBase > Logger [get]
Gets the ILogger for the EngineInstallerBase.
Private Attributes
readonly IPostWriteHandler postWriteHandler
The IPostWriteHandler for the PosixByondInstaller.
Static Private Attributes
const string DreamDaemonExecutableName = "DreamDaemon"
The name of the DreamDaemon binary file.
const string DreamMakerExecutableName = "DreamMaker"
The name of the DreamMaker binary file.
const string ShellScriptExtension = ".sh"
File extension for shell scripts.
Additional Inherited Members
Static Protected Attributes inherited from Tgstation.Server.Host.Components.Engine.ByondInstallerBase
const string ByondBinPath = "byond/bin"
The path to the BYOND bin folder.
const string CfgDirectoryName = "cfg"
The path to the cfg directory.
Detailed Description
IEngineInstaller for Posix systems.
Definition at line 18 of file PosixByondInstaller.cs.
Constructor & Destructor Documentation
PosixByondInstaller()
Tgstation.Server.Host.Components.Engine.PosixByondInstaller.PosixByondInstaller (IPostWriteHandler postWriteHandler, IIOManager ioManager, IFileDownloader fileDownloader, ILogger< PosixByondInstaller > logger)
Initializes a new instance of the PosixByondInstaller class.
Parameters
postWriteHandler The value of postWriteHandler.
ioManager The IIOManager for the ByondInstallerBase.
fileDownloader The IFileDownloader for the ByondInstallerBase.
logger The ILogger for the ByondInstallerBase.
Definition at line 56 of file PosixByondInstaller.cs.
            : base(ioManager, logger, fileDownloader)
        {
            this.postWriteHandler = postWriteHandler ?? throw new ArgumentNullException(nameof(postWriteHandler));
            PathToUserFolder = IOManager.ResolvePath(
                IOManager.ConcatPath(
                    Environment.GetFolderPath(
                        Environment.SpecialFolder.UserProfile,
                        Environment.SpecialFolderOption.DoNotVerify),
                    "./.byond/cache"));
        }
References Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.Components.Engine.EngineInstallerBase.IOManager, Tgstation.Server.Host.Components.Engine.PosixByondInstaller.PathToUserFolder, Tgstation.Server.Host.Components.Engine.PosixByondInstaller.postWriteHandler, and Tgstation.Server.Host.IO.IIOManager.ResolvePath().
Member Function Documentation
GetDreamDaemonName()
override string Tgstation.Server.Host.Components.Engine.PosixByondInstaller.GetDreamDaemonName (Version byondVersion, out bool supportsCli) protected virtual
Get the file name of the DreamDaemon executable.
Parameters
byondVersion The Version of BYOND to select the executable name for.
supportsCli Whether or not the returned path supports being run as a command-line application.
Returns
The file name of the DreamDaemon executable.
Implements Tgstation.Server.Host.Components.Engine.ByondInstallerBase.
Definition at line 133 of file PosixByondInstaller.cs.
        {
            supportsCli = true;
            return DreamDaemonExecutableName + ShellScriptExtension;
        }
References Tgstation.Server.Host.Components.Engine.PosixByondInstaller.DreamDaemonExecutableName, and Tgstation.Server.Host.Components.Engine.PosixByondInstaller.ShellScriptExtension.
Referenced by Tgstation.Server.Host.Components.Engine.PosixByondInstaller.Install().
Install()
override ValueTask Tgstation.Server.Host.Components.Engine.PosixByondInstaller.Install (EngineVersion version, string path, bool deploymentPipelineProcesses, CancellationToken cancellationToken) virtual
Does actions necessary to get an extracted installation working.
Parameters
version The EngineVersion being installed.
path The path to the installation.
deploymentPipelineProcesses If the operation should consider processes it launches to be part of the deployment pipeline.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Engine.EngineInstallerBase.
Definition at line 74 of file PosixByondInstaller.cs.
        {
            CheckVersionValidity(version);
            ArgumentNullException.ThrowIfNull(path);
            // write the scripts for running the ting
            // need to add $ORIGIN to LD_LIBRARY_PATH
            const string StandardScript = "#!/bin/sh\nexport LD_LIBRARY_PATH=\"\\$ORIGIN:$LD_LIBRARY_PATH\"\nBASEDIR=$(dirname \"$0\")\nexec \"$BASEDIR/{0}\" \"$@\"\n";
            var dreamDaemonScript = String.Format(CultureInfo.InvariantCulture, StandardScript, DreamDaemonExecutableName);
            var dreamMakerScript = String.Format(CultureInfo.InvariantCulture, StandardScript, DreamMakerExecutableName);
            async ValueTask WriteAndMakeExecutable(string pathToScript, string script)
            {
                Logger.LogTrace("Writing script {path}:{newLine}{scriptContents}", pathToScript, Environment.NewLine, script);
                await IOManager.WriteAllBytes(pathToScript, Encoding.ASCII.GetBytes(script), cancellationToken);
                postWriteHandler.HandleWrite(IOManager.ResolvePath(pathToScript));
            }
            var basePath = IOManager.ConcatPath(path, ByondBinPath);
            var ddTask = WriteAndMakeExecutable(
                IOManager.ConcatPath(basePath, GetDreamDaemonName(version.Version!, out _)),
                dreamDaemonScript);
            var dmTask = WriteAndMakeExecutable(
                IOManager.ConcatPath(basePath, DreamMakerName),
                dreamMakerScript);
            var task = ValueTaskExtensions.WhenAll(
                ddTask,
                dmTask);
            postWriteHandler.HandleWrite(IOManager.ConcatPath(basePath, DreamDaemonExecutableName));
            postWriteHandler.HandleWrite(IOManager.ConcatPath(basePath, DreamMakerExecutableName));
            return task;
        }
References Tgstation.Server.Host.Components.Engine.ByondInstallerBase.ByondBinPath, Tgstation.Server.Host.Components.Engine.EngineInstallerBase.CheckVersionValidity(), Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.Components.Engine.PosixByondInstaller.DreamDaemonExecutableName, Tgstation.Server.Host.Components.Engine.PosixByondInstaller.DreamMakerExecutableName, Tgstation.Server.Host.Components.Engine.PosixByondInstaller.DreamMakerName, Tgstation.Server.Host.Components.Engine.PosixByondInstaller.GetDreamDaemonName(), Tgstation.Server.Host.IO.IPostWriteHandler.HandleWrite(), Tgstation.Server.Host.Components.Engine.EngineInstallerBase.IOManager, Tgstation.Server.Host.Components.Engine.EngineInstallerBase.Logger, Tgstation.Server.Host.Components.Engine.PosixByondInstaller.postWriteHandler, Tgstation.Server.Host.IO.IIOManager.ResolvePath(), Tgstation.Server.Api.Models.EngineVersion.Version, Tgstation.Server.Common.Extensions.ValueTaskExtensions.WhenAll(), and Tgstation.Server.Host.IO.IIOManager.WriteAllBytes().
TrustDmbPath()
override ValueTask Tgstation.Server.Host.Components.Engine.PosixByondInstaller.TrustDmbPath (EngineVersion version, string fullDmbPath, CancellationToken cancellationToken) virtual
Add a given fullDmbPath to the trusted DMBs list in BYOND's config.
Parameters
version The EngineVersion being used.
fullDmbPath Full path to the .dmb that should be trusted.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Engine.EngineInstallerBase.
Definition at line 123 of file PosixByondInstaller.cs.
        {
            ArgumentNullException.ThrowIfNull(version);
            ArgumentNullException.ThrowIfNull(fullDmbPath);
            Logger.LogTrace("No need to trust .dmb path \"{path}\" on POSIX", fullDmbPath);
            return ValueTask.CompletedTask;
        }
References Tgstation.Server.Host.Components.Engine.EngineInstallerBase.Logger.
UpgradeInstallation()
override ValueTask Tgstation.Server.Host.Components.Engine.PosixByondInstaller.UpgradeInstallation (EngineVersion version, string path, CancellationToken cancellationToken) virtual
Does actions necessary to get upgrade a version installed by a previous version of TGS.
Parameters
version The EngineVersion being installed.
path The path to the installation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Engine.EngineInstallerBase.
Definition at line 114 of file PosixByondInstaller.cs.
        {
            CheckVersionValidity(version);
            ArgumentNullException.ThrowIfNull(path);
            return ValueTask.CompletedTask;
        }
References Tgstation.Server.Host.Components.Engine.EngineInstallerBase.CheckVersionValidity().
Member Data Documentation
DreamDaemonExecutableName
const string Tgstation.Server.Host.Components.Engine.PosixByondInstaller.DreamDaemonExecutableName = "DreamDaemon" static private
The name of the DreamDaemon binary file.
Definition at line 23 of file PosixByondInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Engine.PosixByondInstaller.GetDreamDaemonName(), and Tgstation.Server.Host.Components.Engine.PosixByondInstaller.Install().
DreamMakerExecutableName
const string Tgstation.Server.Host.Components.Engine.PosixByondInstaller.DreamMakerExecutableName = "DreamMaker" static private
The name of the DreamMaker binary file.
Definition at line 28 of file PosixByondInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Engine.PosixByondInstaller.Install().
postWriteHandler
readonly IPostWriteHandler Tgstation.Server.Host.Components.Engine.PosixByondInstaller.postWriteHandler private
The IPostWriteHandler for the PosixByondInstaller.
Definition at line 47 of file PosixByondInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Engine.PosixByondInstaller.Install(), and Tgstation.Server.Host.Components.Engine.PosixByondInstaller.PosixByondInstaller().
ShellScriptExtension
const string Tgstation.Server.Host.Components.Engine.PosixByondInstaller.ShellScriptExtension = ".sh" static private
File extension for shell scripts.
Definition at line 33 of file PosixByondInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Engine.PosixByondInstaller.GetDreamDaemonName().
Property Documentation
ByondRevisionsUrlTemplate
override string Tgstation.Server.Host.Components.Engine.PosixByondInstaller.ByondRevisionsUrlTemplate get protected
Definition at line 42 of file PosixByondInstaller.cs.
DreamMakerName
override string Tgstation.Server.Host.Components.Engine.PosixByondInstaller.DreamMakerName get protected
Definition at line 39 of file PosixByondInstaller.cs.
Referenced by Tgstation.Server.Host.Components.Engine.PosixByondInstaller.Install().
PathToUserFolder
override string Tgstation.Server.Host.Components.Engine.PosixByondInstaller.PathToUserFolder get protected
Definition at line 36 of file PosixByondInstaller.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Engine.PosixByondInstaller.PosixByondInstaller().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Engine/PosixByondInstaller.cs