tgstation-server: TGS.Installer.UI.Main Class Reference
TGS.Installer.UI.Main Class Reference
Public Member Functions
Main ()
Construct an installer form
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Types
enum PKillType { PKillType.Killed, PKillType.Aborted, PKillType.NoneFound }
Private Member Functions
void SetupTempDir ()
void CleanTempDir ()
void CheckForExistingVersion ()
bool ConfirmDangerousUpgrade ()
bool TellServiceWereComingForThem ()
void Main_FormClosing (object sender, FormClosingEventArgs e)
PKillType PromptKillProcesses (string name)
bool HandleNoConfigMigration (ServerConfig sc)
bool AttemptMigrationOfNetSettings ()
Migrate to the new ServerConfig since the Server.Server won't know about it until it's upgraded
async void DoInstall ()
MessageResult OnUIUpdate (InstallMessage messageType, string message, MessageButtons buttons, MessageIcon icon, MessageDefaultButton defaultButton)
void InstallButton_Click (object sender, EventArgs e)
void SelectPathButton_Click (object sender, EventArgs e)
void CancelButton_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Static Private Member Functions
static string TextPrompt (string caption, string text)
Private Attributes
const string DefaultInstallDir = "TG Station Server"
string tempDir
bool installing = false
bool cancelled = false
bool pathIsDefault = true
bool attemptNetSettingsMigration = false
If we should attempt to make a ServerConfig for the new install
IServerInterface Interface
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.ProgressBar ProgressBar
System.Windows.Forms.CheckBox DeskShortcutsCheckbox
System.Windows.Forms.CheckBox StartShortcutsCheckbox
System.Windows.Forms.Label InstallingLabel
System.Windows.Forms.TextBox PathTextBox
System.Windows.Forms.Button SelectPathButton
System.Windows.Forms.Label label1
System.Windows.Forms.Label VersionLabel
System.Windows.Forms.Button InstallButton
System.Windows.Forms.CheckBox ShowLogCheckbox
System.Windows.Forms.Label TargetVersionLabel
System.Windows.Forms.Button InstallCancelButton
Detailed Description
Definition at line 16 of file Main.cs.
Member Enumeration Documentation
enum TGS.Installer.UI.Main.PKillType strong private
Enumerator
Killed
Aborted
NoneFound
Definition at line 126 of file Main.cs.
         {
             Killed,
             Aborted,
             NoneFound,
         }
Constructor & Destructor Documentation
TGS.Installer.UI.Main.Main ()
Construct an installer form
Definition at line 34 of file Main.cs.
         {
             InitializeComponent();
             SetupTempDir();
             CheckForExistingVersion();
             PathTextBox.Text = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86), DefaultInstallDir);
         }
Member Function Documentation
bool TGS.Installer.UI.Main.AttemptMigrationOfNetSettings () private
Migrate to the new ServerConfig since the Server.Server won't know about it until it's upgraded
Definition at line 192 of file Main.cs.
References TGS.Interface.Components.ITGLanding.ListInstances(), TGS.Server.InstanceConfig.Load(), TGS.Server.IInstanceConfig.Save(), TGS.Server.InstanceConfig.Save(), and TGS.Server.Server.Server().
         {
             if (!attemptNetSettingsMigration)
                 return true;
             var sc = new ServerConfig();
             try
             {
                 sc.PythonPath = Interface.GetServiceComponent<ITGSService>().PythonPath();
             }
             catch { }
             try
             {
                 sc.RemoteAccessPort = Interface.GetServiceComponent<ITGSService>().RemoteAccessPort();
             }
             catch { }
             try
             {
                 foreach (var I in Interface.GetServiceComponent<ITGLanding>().ListInstances())
                     sc.InstancePaths.Add(I.Path);
             }
             catch { }
             try
             {
                 if (sc.InstancePaths.Count > 0) //nice suprise, this is uneeded
                     return true;
                 //stopping the service here is MANDATORY to get the correct reattach values
                 using (var controller = new ServiceController("TG Station Server"))
                 {
                     controller.Stop();
                     controller.WaitForStatus(ServiceControllerStatus.Stopped);
                     //we need to find the old user.config
                     //check wow64 first
                     var path = @"C:\Windows\SysWOW64\config\systemprofile\AppData\Local\TGServerService";
                     if (!Directory.Exists(path))
                     {
                         //ok... check the System32 path
                         path = @"C:\Windows\System32\config\systemprofile\AppData\Local\TGServerService";
                         if (!Directory.Exists(path))
{
                             //well, i'm out of ideas, just use the default location
                             var res = HandleNoConfigMigration(sc);
                             if(!res)
{
                                 controller.Start();
                                 return false;
                             }
                         }
                     }
                     //now who knows wtf windows calls the damn folder
                     //take our best guess based on last modified time
                     DirectoryInfo lastModified = null;
                     foreach (var D in new DirectoryInfo(path).GetDirectories())
                         if (lastModified == null || D.LastWriteTime > lastModified.LastWriteTime)
                             lastModified = D;
                     if (lastModified == null)
                     {
                         //well, i'm out of ideas, just use the default location
                         var res = HandleNoConfigMigration(sc);
                         if (!res)
{
                             controller.Start();
                             return false;
                         }
                     }
                     var next = lastModified;
                     lastModified = null;
                     foreach (var D in next.GetDirectories())
                         if (lastModified == null || D.LastWriteTime > lastModified.LastWriteTime)
                             lastModified = D;
                     if (lastModified == null)
                     {
                         //well, i'm out of ideas, just use the default location
                         var res = HandleNoConfigMigration(sc);
                         if (!res)
{
                             controller.Start();
                             return false;
                         }
                     }
                     path = Path.Combine(tempDir, "user.config");
                     var netConfigPath = Path.Combine(lastModified.FullName, "user.config");
                     File.Copy(netConfigPath, path, true);
                     new InstanceConfig(tempDir).Save();
                     var instanceConfigPath = Path.Combine(tempDir, "Instance.json");
                     if (MessageBox.Show(String.Format("The 3.2 settings migration is a manual process, please open \"{0}\" with your favorite text editor and copy the values under TGServerService.Properties.Settings to the relevent fields at \"{1}\". If something in the original config appears wrong to you, correct it in the new config, but do not modify the \"Version\", \"Enabled\", or \"Name\" fields at all. See field mappings here: https://github.com/tgstation/tgstation-server/blob/a372b22fd3367dd60ee0cbebd9210f4b072c952d/TGServerService/DeprecatedInstanceConfig.cs#L23-L39", path, instanceConfigPath), "Manual Migration Required", MessageBoxButtons.OKCancel) != DialogResult.OK)
                     {
                         controller.Start();
                         return false;
                     }
                     var name = TextPrompt("Set Instance Directory", String.Format("Please enter the ServerDirectory entry from the original config here.{0}Use backslashes and uppercase letters. Leave this blank if it is not present.", Environment.NewLine));
                     if (name == null)
                     {
                         controller.Start();
                         return false;
                     }
                     if (String.IsNullOrWhiteSpace(name))
                         name = @"C:\TGSTATION-SERVER-3";
                     sc.InstancePaths.Add(name);
                     if (MessageBox.Show(String.Format("Please confirm you have finished copying settings from \"{0}\" to \"{1}\"!", path, instanceConfigPath), "Last Confirmation", MessageBoxButtons.OKCancel) != DialogResult.OK)
                     {
                         controller.Start();
                         return false;
                     }
                     //validate it for good measure
                     try
                     {
                         InstanceConfig.Load(tempDir);
                     }
                     catch (Exception e)
                     {
                         MessageBox.Show(String.Format("JSON Validation Error: {0}", e.Message));
                         controller.Start();
                         return false;
                     }
                     File.Copy(instanceConfigPath, Path.Combine(name, "Instance.json"), true);
                     return true;
                 }
             }
             finally
             {
                 Directory.CreateDirectory(Server.Server.MigrationConfigDirectory);
                 sc.Save(Server.Server.MigrationConfigDirectory);
             }
         }
void TGS.Installer.UI.Main.CancelButton_Click (object sender, EventArgs e) private
Definition at line 455 of file Main.cs.
         {
             cancelled = true;
             InstallCancelButton.Enabled = false;
         }
void TGS.Installer.UI.Main.CheckForExistingVersion () private
Definition at line 77 of file Main.cs.
References TGS.Interface.IServerInterface.ConnectionStatus().
{
             Interface = new ServerInterface();
             var verifiedConnection = Interface.ConnectionStatus().HasFlag(ConnectivityLevel.Administrator);
             try
             {
                 VersionLabel.Text = Interface.GetServiceComponent<ITGSService>().Version();
                 var splits = VersionLabel.Text.Split(' ');
                 var realVersion = new Version(splits[splits.Length - 1].Substring(1));
                 var isV0 = realVersion < new Version(3, 1, 0, 0);
                 if (isV0) //OH GOD!!!!
                     MessageBox.Show("Upgrading from version 3.0 may trigger a bug that can delete /config and /data. IT IS STRONGLY RECCOMMENDED THAT YOU BACKUP THESE FOLDERS BEFORE UPDATING!", "Warning");
                 var isUnderV2 = isV0 || realVersion < new Version(3, 2, 0, 0);
                 if (isUnderV2)
                     //Friendly reminger
                     MessageBox.Show("Upgrading to service version 3.2 will break the 3.1 DMAPI. It is recommended you update your game to the 3.2 API before updating the servive to avoid having to trigger hard restarts.", "Note");
                 attemptNetSettingsMigration = isUnderV2;
             }
             catch
             {
                 if (verifiedConnection)
                     VersionLabel.Text = "< v3.0.85.0 (Missing ITGService.Version())";
             }
         }
void TGS.Installer.UI.Main.CleanTempDir () private
Definition at line 68 of file Main.cs.
{
             if(tempDir != null)
                 try
                 {
                     Directory.Delete(tempDir, true);
                 }
                 catch { }
         }
bool TGS.Installer.UI.Main.ConfirmDangerousUpgrade () private
Definition at line 101 of file Main.cs.
         {
             return MessageBox.Show("Unable connect to service! Existing DreamDaemon instances will be terminated. Continue?", "Warning", MessageBoxButtons.YesNo) == DialogResult.Yes;
         }
override void TGS.Installer.UI.Main.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 18 of file Main.Designer.cs.
         {
             if (disposing && (components != null))
             {
                 components.Dispose();
                 CleanTempDir();
             }
             base.Dispose(disposing);
         }
async void TGS.Installer.UI.Main.DoInstall () private
Definition at line 330 of file Main.cs.
         {
             string logfile = null;
             try
             {
                 while (true)
                 {
                     var res = PromptKillProcesses("TGCommandLine");
                     if (res == PKillType.Aborted)
                         return;
                     else if (res == PKillType.Killed)
                         continue;
                     res = PromptKillProcesses("TGControlPanel");
                     if (res == PKillType.Aborted)
                         return;
                     else if (res == PKillType.Killed)
                         continue;
                     break;
                 }
                 if (!TellServiceWereComingForThem())
                     return;
                 if (!AttemptMigrationOfNetSettings())
                     return;
                 var args = new List<string>();
                 if (!pathIsDefault)
                     args.Add(String.Format("INSTALLFOLDER=\"{0}\"", PathTextBox.Text));
                 if (StartShortcutsCheckbox.Checked)
                     args.Add("INSTALLSHORTCUTSTART=1");
                 if (DeskShortcutsCheckbox.Checked)
                     args.Add("INSTALLSHORTCUTDESK=1");
                 args.Add("REBOOT=R");
                 SelectPathButton.Enabled = false;
                 PathTextBox.Enabled = false;
                 DeskShortcutsCheckbox.Enabled = false;
                 StartShortcutsCheckbox.Enabled = false;
                 InstallButton.Enabled = false;
                 ShowLogCheckbox.Enabled = false;
                 InstallButton.Text = "Installing...";
                 var msipath = Path.Combine(tempDir, "TGS.Installer.msi");
                 File.WriteAllBytes(msipath, Properties.Resources.TGSInstaller);
                 File.WriteAllBytes(Path.Combine(tempDir, "cab1.cab"), Properties.Resources.cab1);
                 ProgressBar.Style = ProgressBarStyle.Marquee;
                 InstallCancelButton.Enabled = true;
                 if (ShowLogCheckbox.Checked)
                 {
                     logfile = Path.Combine(tempDir, "tgsinstall.log");
                     Microsoft.Deployment.WindowsInstaller.Installer.EnableLog(InstallLogModes.Verbose | InstallLogModes.PropertyDump, logfile);
                 }
                 var cl = String.Join(" ", args);
                 Microsoft.Deployment.WindowsInstaller.Installer.SetInternalUI(InstallUIOptions.Silent);
                 Microsoft.Deployment.WindowsInstaller.Installer.SetExternalUI(OnUIUpdate, InstallLogModes.Progress);
                 await Task.Factory.StartNew(() => Microsoft.Deployment.WindowsInstaller.Installer.InstallProduct(msipath, cl));
                 if (cancelled)
                 {
                     MessageBox.Show("Operation cancelled!");
                     return;
                 }
             }
             catch (Exception ex)
             {
                 MessageBox.Show("Error: " + ex.ToString());
                 return;
             }
             finally
             {
                 InstallCancelButton.Enabled = false;
                 ShowLogCheckbox.Enabled = true;
                 SelectPathButton.Enabled = true;
                 PathTextBox.Enabled = true;
                 DeskShortcutsCheckbox.Enabled = true;
                 StartShortcutsCheckbox.Enabled = true;
                 ProgressBar.Style = ProgressBarStyle.Blocks;
                 InstallButton.Enabled = true;
                 InstallButton.Text = "Install";
                 installing = false;
                 cancelled = false;
                 if (ShowLogCheckbox.Checked && logfile != null)
                     try
                     {
                         Process.Start(logfile).WaitForInputIdle();
                     }
                     catch { }
             }
             MessageBox.Show("Success!");
             Application.Exit();
         }
bool TGS.Installer.UI.Main.HandleNoConfigMigration (ServerConfig sc) private
Definition at line 178 of file Main.cs.
References TGS.Server.ServerConfig.InstancePaths, and TGS.Server.InstanceConfig.Save().
         {
             var path = @"C:\TGSTATION-SERVER-3";
             if (Directory.Exists(path)) {
                 sc.InstancePaths.Add(path);
                 new InstanceConfig(path).Save();
                 return MessageBox.Show(String.Format("Unable to migrate settings, default config created at {0}. You will need to reconfigure your server instance. Continue with installation?", path), "Migration Error", MessageBoxButtons.YesNo) == DialogResult.Yes;
             }
             return MessageBox.Show("All config migrations have failed. You will need to fully recreate your server. Continue with installation?", "Migration Failure", MessageBoxButtons.YesNo) == DialogResult.Yes;
         }
void TGS.Installer.UI.Main.InitializeComponent () private
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 34 of file Main.Designer.cs.
         {
             System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Main));
             this.ProgressBar = new System.Windows.Forms.ProgressBar();
             this.DeskShortcutsCheckbox = new System.Windows.Forms.CheckBox();
             this.StartShortcutsCheckbox = new System.Windows.Forms.CheckBox();
             this.InstallingLabel = new System.Windows.Forms.Label();
             this.PathTextBox = new System.Windows.Forms.TextBox();
             this.SelectPathButton = new System.Windows.Forms.Button();
             this.label1 = new System.Windows.Forms.Label();
             this.VersionLabel = new System.Windows.Forms.Label();
             this.InstallButton = new System.Windows.Forms.Button();
             this.ShowLogCheckbox = new System.Windows.Forms.CheckBox();
             this.TargetVersionLabel = new System.Windows.Forms.Label();
             this.InstallCancelButton = new System.Windows.Forms.Button();
             this.SuspendLayout();
             //
             // ProgressBar
             //
             this.ProgressBar.Location = new System.Drawing.Point(11, 119);
             this.ProgressBar.Name = "ProgressBar";
             this.ProgressBar.Size = new System.Drawing.Size(386, 22);
             this.ProgressBar.TabIndex = 0;
             //
             // DeskShortcutsCheckbox
             //
             this.DeskShortcutsCheckbox.AutoSize = true;
             this.DeskShortcutsCheckbox.Checked = true;
             this.DeskShortcutsCheckbox.CheckState = System.Windows.Forms.CheckState.Checked;
             this.DeskShortcutsCheckbox.Font = new System.Drawing.Font("Verdana", 12F);
             this.DeskShortcutsCheckbox.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.DeskShortcutsCheckbox.Location = new System.Drawing.Point(12, 61);
             this.DeskShortcutsCheckbox.Name = "DeskShortcutsCheckbox";
             this.DeskShortcutsCheckbox.Size = new System.Drawing.Size(214, 22);
             this.DeskShortcutsCheckbox.TabIndex = 2;
             this.DeskShortcutsCheckbox.Text = "Add Desktop Shortcuts";
             this.DeskShortcutsCheckbox.UseVisualStyleBackColor = true;
             //
             // StartShortcutsCheckbox
             //
             this.StartShortcutsCheckbox.AutoSize = true;
             this.StartShortcutsCheckbox.Checked = true;
             this.StartShortcutsCheckbox.CheckState = System.Windows.Forms.CheckState.Checked;
             this.StartShortcutsCheckbox.Font = new System.Drawing.Font("Verdana", 12F);
             this.StartShortcutsCheckbox.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.StartShortcutsCheckbox.Location = new System.Drawing.Point(289, 61);
             this.StartShortcutsCheckbox.Name = "StartShortcutsCheckbox";
             this.StartShortcutsCheckbox.Size = new System.Drawing.Size(236, 22);
             this.StartShortcutsCheckbox.TabIndex = 3;
             this.StartShortcutsCheckbox.Text = "Add Start Menu Shortcuts";
             this.StartShortcutsCheckbox.UseVisualStyleBackColor = true;
             //
             // InstallingLabel
             //
             this.InstallingLabel.AutoSize = true;
             this.InstallingLabel.Font = new System.Drawing.Font("Verdana", 12F);
             this.InstallingLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.InstallingLabel.Location = new System.Drawing.Point(8, 37);
             this.InstallingLabel.Name = "InstallingLabel";
             this.InstallingLabel.Size = new System.Drawing.Size(52, 18);
             this.InstallingLabel.TabIndex = 1;
             this.InstallingLabel.Text = "Path:";
             //
             // PathTextBox
             //
             this.PathTextBox.Location = new System.Drawing.Point(66, 35);
             this.PathTextBox.Name = "PathTextBox";
             this.PathTextBox.ReadOnly = true;
             this.PathTextBox.Size = new System.Drawing.Size(413, 20);
             this.PathTextBox.TabIndex = 4;
             //
             // SelectPathButton
             //
             this.SelectPathButton.Location = new System.Drawing.Point(485, 35);
             this.SelectPathButton.Name = "SelectPathButton";
             this.SelectPathButton.Size = new System.Drawing.Size(40, 20);
             this.SelectPathButton.TabIndex = 6;
             this.SelectPathButton.Text = "...";
             this.SelectPathButton.UseVisualStyleBackColor = true;
             this.SelectPathButton.Click += new System.EventHandler(this.SelectPathButton_Click);
             //
             // label1
             //
             this.label1.AutoSize = true;
             this.label1.Font = new System.Drawing.Font("Verdana", 12F);
             this.label1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.label1.Location = new System.Drawing.Point(8, 9);
             this.label1.Name = "label1";
             this.label1.Size = new System.Drawing.Size(155, 18);
             this.label1.TabIndex = 7;
             this.label1.Text = "Detected Version:";
             //
             // VersionLabel
             //
             this.VersionLabel.AutoSize = true;
             this.VersionLabel.Font = new System.Drawing.Font("Verdana", 12F);
             this.VersionLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.VersionLabel.Location = new System.Drawing.Point(169, 9);
             this.VersionLabel.Name = "VersionLabel";
             this.VersionLabel.Size = new System.Drawing.Size(228, 18);
             this.VersionLabel.TabIndex = 8;
             this.VersionLabel.Text = "Unknown (No service running)";
             //
             // InstallButton
             //
             this.InstallButton.Location = new System.Drawing.Point(400, 89);
             this.InstallButton.Name = "InstallButton";
             this.InstallButton.Size = new System.Drawing.Size(125, 22);
             this.InstallButton.TabIndex = 9;
             this.InstallButton.Text = "Install";
             this.InstallButton.UseVisualStyleBackColor = true;
             this.InstallButton.Click += new System.EventHandler(this.InstallButton_Click);
             //
             // ShowLogCheckbox
             //
             this.ShowLogCheckbox.AutoSize = true;
             this.ShowLogCheckbox.Font = new System.Drawing.Font("Verdana", 12F);
             this.ShowLogCheckbox.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.ShowLogCheckbox.Location = new System.Drawing.Point(289, 90);
             this.ShowLogCheckbox.Name = "ShowLogCheckbox";
             this.ShowLogCheckbox.Size = new System.Drawing.Size(105, 22);
             this.ShowLogCheckbox.TabIndex = 10;
             this.ShowLogCheckbox.Text = "Show Log";
             this.ShowLogCheckbox.UseVisualStyleBackColor = true;
             //
             // TargetVersionLabel
             //
             this.TargetVersionLabel.AutoSize = true;
             this.TargetVersionLabel.Font = new System.Drawing.Font("Verdana", 12F);
             this.TargetVersionLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.TargetVersionLabel.Location = new System.Drawing.Point(8, 90);
             this.TargetVersionLabel.Name = "TargetVersionLabel";
             this.TargetVersionLabel.Size = new System.Drawing.Size(132, 18);
             this.TargetVersionLabel.TabIndex = 11;
             this.TargetVersionLabel.Text = "Target Version: v" + FileVersionInfo.GetVersionInfo(Assembly.GetExecutingAssembly().Location).FileVersion;
             //
             // InstallCancelButton
             //
             this.InstallCancelButton.Enabled = false;
             this.InstallCancelButton.Location = new System.Drawing.Point(400, 119);
             this.InstallCancelButton.Name = "InstallCancelButton";
             this.InstallCancelButton.Size = new System.Drawing.Size(125, 22);
             this.InstallCancelButton.TabIndex = 12;
             this.InstallCancelButton.Text = "Cancel";
             this.InstallCancelButton.UseVisualStyleBackColor = true;
             this.InstallCancelButton.Click += new System.EventHandler(this.CancelButton_Click);
             //
             // Main
             //
             this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
             this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
             this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(40)))), ((int)(((byte)(34)))));
             this.ClientSize = new System.Drawing.Size(537, 153);
             this.FormClosing += Main_FormClosing;
             this.Controls.Add(this.InstallCancelButton);
             this.Controls.Add(this.TargetVersionLabel);
             this.Controls.Add(this.ShowLogCheckbox);
             this.Controls.Add(this.InstallButton);
             this.Controls.Add(this.VersionLabel);
             this.Controls.Add(this.label1);
             this.Controls.Add(this.SelectPathButton);
             this.Controls.Add(this.PathTextBox);
             this.Controls.Add(this.StartShortcutsCheckbox);
             this.Controls.Add(this.DeskShortcutsCheckbox);
             this.Controls.Add(this.InstallingLabel);
             this.Controls.Add(this.ProgressBar);
             this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
             this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
             this.MaximizeBox = false;
             this.MinimizeBox = false;
             this.Name = "Main";
             this.Text = "/tg/station Server Installer";
             this.ResumeLayout(false);
             this.PerformLayout();
         }
void TGS.Installer.UI.Main.InstallButton_Click (object sender, EventArgs e) private
Definition at line 437 of file Main.cs.
         {
             DoInstall();
         }
void TGS.Installer.UI.Main.Main_FormClosing (object sender, FormClosingEventArgs e) private
Definition at line 121 of file Main.cs.
         {
             e.Cancel = installing;  //not allowed, nununu
         }
MessageResult TGS.Installer.UI.Main.OnUIUpdate (InstallMessage messageType, string message, MessageButtons buttons, MessageIcon icon, MessageDefaultButton defaultButton) private
Definition at line 427 of file Main.cs.
         {
             if (cancelled && installing)
             {
                 installing = false;
                 return MessageResult.Cancel;
             }
             return MessageResult.OK;
         }
PKillType TGS.Installer.UI.Main.PromptKillProcesses (string name) private
Definition at line 133 of file Main.cs.
         {
             var processes = new List<Process>(Process.GetProcessesByName(name));
             processes.RemoveAll(x => x.HasExited);
             if(processes.Count > 0)
             {
                 if (MessageBox.Show(String.Format("Found {1} running instance{2} of {0}.exe! Shall I terminate {3}?", name, processes.Count, processes.Count > 1 ? "s" : "", processes.Count > 1 ? "them" : "it"), "Warning", MessageBoxButtons.YesNo) != DialogResult.Yes)
                     return PKillType.Aborted;
                 foreach (var P in processes)
                 {
                     if (!P.HasExited)
                     {
                         P.Kill();
                         P.WaitForExit();
                     }
                     P.Dispose();
                 }
                 return PKillType.Killed;
             }
             return PKillType.NoneFound;
         }
void TGS.Installer.UI.Main.SelectPathButton_Click (object sender, EventArgs e) private
Definition at line 442 of file Main.cs.
         {
             var fbd = new FolderBrowserDialog()
             {
                 Description = "Select where you would like to install the service executables. This isn't where an actual server instance is created.",
                 ShowNewFolderButton = true
             };
             if (fbd.ShowDialog() != DialogResult.OK)
                 return;
             pathIsDefault = false;
             PathTextBox.Text = fbd.SelectedPath + Path.DirectorySeparatorChar + DefaultInstallDir;
         }
void TGS.Installer.UI.Main.SetupTempDir () private
Definition at line 42 of file Main.cs.
         {
             tempDir = Path.Combine(Path.GetTempPath(), "TGS3InstallerTempDir");
             try
             {
                 if (File.Exists(tempDir))
                     File.Delete(tempDir);
                 else if (Directory.Exists(tempDir))
                     Directory.Delete(tempDir, true);
             }
             catch { }
             if (File.Exists(tempDir) || Directory.Exists(tempDir))
             {
                 tempDir = Path.GetTempFileName();
                 File.Delete(tempDir);  //we want a dir not a file
             }
             try
             {
                 Directory.CreateDirectory(tempDir);
             }
             catch
             {
                 tempDir = null;
             }
         }
bool TGS.Installer.UI.Main.TellServiceWereComingForThem () private
Definition at line 106 of file Main.cs.
References TGS.Interface.IServerInterface.ConnectionStatus().
         {
             var connectionVerified = Interface.ConnectionStatus().HasFlag(ConnectivityLevel.Administrator);
             try
             {
                 Interface.GetServiceComponent<ITGSService>().PrepareForUpdate();
                 Thread.Sleep(3000); //chat messages
                 return true;
             }
             catch
             {
                 return ConfirmDangerousUpgrade();
             }
         }
static string TGS.Installer.UI.Main.TextPrompt (string caption, string text) static private
Definition at line 154 of file Main.cs.
         {
             Form prompt = new Form()
             {
                 Width = 500,
                 Height = 150,
                 FormBorderStyle = FormBorderStyle.FixedDialog,
                 Text = caption,
                 StartPosition = FormStartPosition.CenterScreen,
                 MaximizeBox = false,
                 MinimizeBox = false,
             };
             Label textLabel = new Label() { Left = 50, Top = 20, Text = text, AutoSize = true };
             TextBox textBox = new TextBox() { Left = 50, Top = 50, Width = 400 };
             Button confirmation = new Button() { Text = "Ok", Left = 350, Width = 100, Top = 70, DialogResult = DialogResult.OK };
             confirmation.Click += (sender, e) => { prompt.Close(); };
             prompt.Controls.Add(textBox);
             prompt.Controls.Add(confirmation);
             prompt.Controls.Add(textLabel);
             prompt.AcceptButton = confirmation;
             return prompt.ShowDialog() == DialogResult.OK ? textBox.Text : null;
         }
Member Data Documentation
bool TGS.Installer.UI.Main.attemptNetSettingsMigration = false private
If we should attempt to make a ServerConfig for the new install
Definition at line 27 of file Main.cs.
bool TGS.Installer.UI.Main.cancelled = false private
Definition at line 22 of file Main.cs.
System.ComponentModel.IContainer TGS.Installer.UI.Main.components = null private
Required designer variable.
Definition at line 12 of file Main.Designer.cs.
const string TGS.Installer.UI.Main.DefaultInstallDir = "TG Station Server" private
Definition at line 18 of file Main.cs.
System.Windows.Forms.CheckBox TGS.Installer.UI.Main.DeskShortcutsCheckbox private
Definition at line 214 of file Main.Designer.cs.
System.Windows.Forms.Button TGS.Installer.UI.Main.InstallButton private
Definition at line 221 of file Main.Designer.cs.
System.Windows.Forms.Button TGS.Installer.UI.Main.InstallCancelButton private
Definition at line 224 of file Main.Designer.cs.
bool TGS.Installer.UI.Main.installing = false private
Definition at line 21 of file Main.cs.
System.Windows.Forms.Label TGS.Installer.UI.Main.InstallingLabel private
Definition at line 216 of file Main.Designer.cs.
IServerInterface TGS.Installer.UI.Main.Interface private
Definition at line 29 of file Main.cs.
System.Windows.Forms.Label TGS.Installer.UI.Main.label1 private
Definition at line 219 of file Main.Designer.cs.
bool TGS.Installer.UI.Main.pathIsDefault = true private
Definition at line 23 of file Main.cs.
System.Windows.Forms.TextBox TGS.Installer.UI.Main.PathTextBox private
Definition at line 217 of file Main.Designer.cs.
System.Windows.Forms.ProgressBar TGS.Installer.UI.Main.ProgressBar private
Definition at line 213 of file Main.Designer.cs.
System.Windows.Forms.Button TGS.Installer.UI.Main.SelectPathButton private
Definition at line 218 of file Main.Designer.cs.
System.Windows.Forms.CheckBox TGS.Installer.UI.Main.ShowLogCheckbox private
Definition at line 222 of file Main.Designer.cs.
System.Windows.Forms.CheckBox TGS.Installer.UI.Main.StartShortcutsCheckbox private
Definition at line 215 of file Main.Designer.cs.
System.Windows.Forms.Label TGS.Installer.UI.Main.TargetVersionLabel private
Definition at line 223 of file Main.Designer.cs.
string TGS.Installer.UI.Main.tempDir private
Definition at line 20 of file Main.cs.
System.Windows.Forms.Label TGS.Installer.UI.Main.VersionLabel private
Definition at line 220 of file Main.Designer.cs.
The documentation for this class was generated from the following files:
TGS.Installer.UI/Main.cs
TGS.Installer.UI/Main.Designer.cs