tgstation-server: Tgstation.Server.Host.Tests.TestServerFactory Class Reference
Tgstation.Server.Host.Tests.TestServerFactory Class Reference
Tests for ServerFactory
Public Member Functions
void TestContructor ()
async Task TestWorksWithoutUpdatePath ()
async Task TestWorksWithUpdatePath ()
Detailed Description
Tests for ServerFactory
Definition at line 15 of file TestServerFactory.cs.
Member Function Documentation
TestContructor()
void Tgstation.Server.Host.Tests.TestServerFactory.TestContructor ()
Definition at line 18 of file TestServerFactory.cs.
         {
             Assert.ThrowsException<ArgumentNullException>(() => new ServerFactory(null, null));
             IAssemblyInformationProvider assemblyInformationProvider = Mock.Of<IAssemblyInformationProvider>();
             Assert.ThrowsException<ArgumentNullException>(() => new ServerFactory(assemblyInformationProvider, null));
             IIOManager ioManager = Mock.Of<IIOManager>();
             new ServerFactory(assemblyInformationProvider, ioManager);
         }
TestWorksWithoutUpdatePath()
async Task Tgstation.Server.Host.Tests.TestServerFactory.TestWorksWithoutUpdatePath ()
Definition at line 28 of file TestServerFactory.cs.
         {
             var factory = Application.CreateDefaultServerFactory();
             await Assert.ThrowsExceptionAsync<ArgumentNullException>(() => factory.CreateServer(null, null, default));
             await factory.CreateServer(new[] { "General:SetupWizardMode=Never" }, null, default);
         }
References Tgstation.Server.Host.Core.Application.CreateDefaultServerFactory(), and Tgstation.Server.Host.IServerFactory.CreateServer().
TestWorksWithUpdatePath()
async Task Tgstation.Server.Host.Tests.TestServerFactory.TestWorksWithUpdatePath ()
Definition at line 37 of file TestServerFactory.cs.
         {
             var factory = Application.CreateDefaultServerFactory();
             const string Path = "/test";
             await Assert.ThrowsExceptionAsync<ArgumentNullException>(() => factory.CreateServer(null, null, default));
             await Assert.ThrowsExceptionAsync<ArgumentNullException>(() => factory.CreateServer(null, Path, default));
             await factory.CreateServer(new[] { "General:SetupWizardMode=Never" }, Path, default);
         }
References Tgstation.Server.Host.Core.Application.CreateDefaultServerFactory(), and Tgstation.Server.Host.IServerFactory.CreateServer().
The documentation for this class was generated from the following file:
tests/Tgstation.Server.Host.Tests/TestServerFactory.cs