tgstation-server: Tgstation.Server.Host.Controllers.InstanceController Class Reference
Tgstation.Server.Host.Controllers.InstanceController Class Reference sealed
ApiController for managing Components.Instances.
Public Member Functions
InstanceController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ILogger< InstanceController > logger, IInstanceManager instanceManager, IJobManager jobManager, IIOManager ioManager, IPlatformIdentifier platformIdentifier, IPortAllocator portAllocator, IPermissionsUpdateNotifyee permissionsUpdateNotifyee, IOptions< SwarmConfiguration > swarmConfigurationOptions, IOptionsSnapshot< GeneralConfiguration > generalConfigurationOptions, IApiHeadersProvider apiHeaders)
Initializes a new instance of the InstanceController class.
async ValueTask< IActionResult > Create ([FromBody] InstanceCreateRequest model, CancellationToken cancellationToken)
Create or attach an Api.Models.Instance.
async ValueTask< IActionResult > Delete (long id, CancellationToken cancellationToken)
Detach an Api.Models.Instance with the given id .
async ValueTask< IActionResult > Update ([FromBody] InstanceUpdateRequest model, CancellationToken cancellationToken)
Modify an Api.Models.Instance's settings.
async ValueTask< IActionResult > List ([FromQuery] int? page, [FromQuery] int? pageSize, CancellationToken cancellationToken)
List Api.Models.Instances.
async ValueTask< IActionResult > GetId (long id, CancellationToken cancellationToken)
Get a specific Api.Models.Instance.
async ValueTask< IActionResult > GrantPermissions (long id, CancellationToken cancellationToken)
Gives the current user full permissions on a given instance id .
Public Member Functions inherited from Tgstation.Server.Host.Controllers.ApiControllerBase
override async Task OnActionExecutionAsync (ActionExecutingContext context, ActionExecutionDelegate next)
Static Public Attributes
const string InstanceAttachFileName = "TGS4_ALLOW_INSTANCE_ATTACH"
File name to allow attaching instances.
Static Public Attributes inherited from Tgstation.Server.Host.Controllers.ApiController
const ushort DefaultPageSize = 10
Default size of Paginated<TModel> results.
const ushort MaximumPageSize = 100
Maximum size of Paginated<TModel> results.
Private Member Functions
async ValueTask< Models.Instance?> CreateDefaultInstance (InstanceCreateRequest initialSettings, CancellationToken cancellationToken)
Creates a default Models.Instance from initialSettings .
InstancePermissionSet InstanceAdminPermissionSet (InstancePermissionSet? permissionSetToModify)
Generate an InstancePermissionSet with full rights.
string? NormalizePath (string? path)
Normalize a given path for an instance.
async ValueTask CheckAccessible (InstanceResponse instanceResponse, CancellationToken cancellationToken)
Populate the InstanceResponse.Accessible property of a given instanceResponse .
BadRequestObjectResult? ValidateCronSetting (Api.Models.Instance instance)
Validates a given instance 's Api.Models.Instance.AutoUpdateCron setting.
Private Attributes
readonly IJobManager jobManager
The IJobManager for the InstanceController.
readonly IIOManager ioManager
The IIOManager for the InstanceController.
readonly IPlatformIdentifier platformIdentifier
The IPlatformIdentifier for the InstanceController.
readonly IPortAllocator portAllocator
The IPortAllocator for the InstanceController.
readonly IOptions< SwarmConfiguration > swarmConfigurationOptions
The IOptions<TOptions> of SwarmConfiguration for the InstanceController.
readonly IOptionsSnapshot< GeneralConfiguration > generalConfigurationOptions
The IOptionsSnapshot<TOptions> of GeneralConfiguration for the InstanceController.
readonly IPermissionsUpdateNotifyee permissionsUpdateNotifyee
The IPermissionsUpdateNotifyee for the InstanceController.
Additional Inherited Members
Protected Member Functions inherited from Tgstation.Server.Host.Controllers.ComponentInterfacingController
ComponentInterfacingController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ILogger< ComponentInterfacingController > logger, IInstanceManager instanceManager, IApiHeadersProvider apiHeaders, bool useInstanceRequestHeader)
Initializes a new instance of the ComponentInterfacingController class.
override async ValueTask< IActionResult?> ValidateRequest (CancellationToken cancellationToken)
Performs validation a request.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in an appropriate IActionResult on validation failure, null otherwise.
bool ValidateInstanceOnlineStatus (Api.Models.Instance metadata)
Corrects discrepencies between the Api.Models.Instance.Online status of IInstances in the database vs the service.
async ValueTask< IActionResult?> WithComponentInstanceNullable (Func< IInstanceCore, ValueTask< IActionResult?> > action, Models.Instance? instance=null)
Run a given action with the relevant IInstance.
async ValueTask< IActionResult > WithComponentInstance (Func< IInstanceCore, ValueTask< IActionResult > > action, Models.Instance? instance=null)
Run a given action with the relevant IInstance.
Protected Member Functions inherited from Tgstation.Server.Host.Controllers.ApiController
ApiController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, IApiHeadersProvider apiHeadersProvider, ILogger< ApiController > logger, bool requireHeaders)
Initializes a new instance of the ApiController class.
override async ValueTask< IActionResult?> HookExecuteAction (Func< Task > executeAction, CancellationToken cancellationToken)
Hook for executing a request.
Parameters
executeAction A Func<TResult> that should be invoked and its response awaited to continue normal execution of the request. Should NOT be called if this method returns a non-null value.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in an IActionResult that, if not null, is executed.
new NotFoundObjectResult NotFound ()
Generic 404 response.
StatusCodeResult StatusCode (HttpStatusCode statusCode)
Strongly type calls to ControllerBase.StatusCode(int).
ObjectResult RateLimit (RateLimitExceededException rateLimitException)
429 response for a given rateLimitException .
IActionResult HeadersIssue (HeadersException headersException)
Response for missing/Invalid headers.
ValueTask< IActionResult > Paginated< TModel > (Func< ValueTask< PaginatableResult< TModel >?> > queryGenerator, Func< TModel, ValueTask >? resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
ValueTask< IActionResult > Paginated< TModel, TApiModel > (Func< ValueTask< PaginatableResult< TModel >?> > queryGenerator, Func< TApiModel, ValueTask >? resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
Properties inherited from Tgstation.Server.Host.Controllers.ComponentInterfacingController
IInstanceOperations InstanceOperations [get]
Access the IInstanceOperations instance.
Properties inherited from Tgstation.Server.Host.Controllers.ApiController
ApiHeaders? ApiHeaders [get]
The Api.ApiHeaders for the operation.
IApiHeadersProvider ApiHeadersProvider [get]
The IApiHeadersProvider containing value of ApiHeaders.
IDatabaseContext DatabaseContext [get]
The IDatabaseContext for the operation.
IAuthenticationContext AuthenticationContext [get]
The IAuthenticationContext for the operation.
ILogger< ApiController > Logger [get]
The ILogger for the ApiController.
Models.? Instance Instance [get]
The Instance for the operation.
Detailed Description
ApiController for managing Components.Instances.
Definition at line 43 of file InstanceController.cs.
Constructor & Destructor Documentation
InstanceController()
Tgstation.Server.Host.Controllers.InstanceController.InstanceController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ILogger< InstanceController > logger, IInstanceManager instanceManager, IJobManager jobManager, IIOManager ioManager, IPlatformIdentifier platformIdentifier, IPortAllocator portAllocator, IPermissionsUpdateNotifyee permissionsUpdateNotifyee, IOptions< SwarmConfiguration > swarmConfigurationOptions, IOptionsSnapshot< GeneralConfiguration > generalConfigurationOptions, IApiHeadersProvider apiHeaders)
Initializes a new instance of the InstanceController class.
Parameters
databaseContext The IDatabaseContext for the ComponentInterfacingController.
authenticationContext The IAuthenticationContext for the ComponentInterfacingController.
logger The ILogger for the ComponentInterfacingController.
instanceManager The IInstanceManager for the ComponentInterfacingController.
jobManager The value of jobManager.
ioManager The value of ioManager.
platformIdentifier The value of platformIdentifier.
portAllocator The value of portAllocator.
permissionsUpdateNotifyee The value of permissionsUpdateNotifyee.
swarmConfigurationOptions The value of swarmConfigurationOptions.
generalConfigurationOptions The value of generalConfigurationOptions.
apiHeaders The IApiHeadersProvider for the ComponentInterfacingController.
Definition at line 100 of file InstanceController.cs.
            : base(
                  databaseContext,
                  authenticationContext,
                  logger,
                  instanceManager,
                  apiHeaders,
                  false)
        {
            this.jobManager = jobManager ?? throw new ArgumentNullException(nameof(jobManager));
            this.ioManager = ioManager ?? throw new ArgumentNullException(nameof(ioManager));
            this.platformIdentifier = platformIdentifier ?? throw new ArgumentNullException(nameof(platformIdentifier));
            this.portAllocator = portAllocator ?? throw new ArgumentNullException(nameof(portAllocator));
            this.permissionsUpdateNotifyee = permissionsUpdateNotifyee ?? throw new ArgumentNullException(nameof(permissionsUpdateNotifyee));
            this.swarmConfigurationOptions = swarmConfigurationOptions ?? throw new ArgumentNullException(nameof(swarmConfigurationOptions));
            this.generalConfigurationOptions = generalConfigurationOptions ?? throw new ArgumentNullException(nameof(generalConfigurationOptions));
        }
References Tgstation.Server.Host.Controllers.InstanceController.generalConfigurationOptions, Tgstation.Server.Host.Controllers.InstanceController.ioManager, Tgstation.Server.Host.Controllers.InstanceController.jobManager, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Controllers.InstanceController.permissionsUpdateNotifyee, Tgstation.Server.Host.Controllers.InstanceController.platformIdentifier, Tgstation.Server.Host.Controllers.InstanceController.portAllocator, and Tgstation.Server.Host.Controllers.InstanceController.swarmConfigurationOptions.
Member Function Documentation
CheckAccessible()
async ValueTask Tgstation.Server.Host.Controllers.InstanceController.CheckAccessible (InstanceResponse instanceResponse, CancellationToken cancellationToken) private
Populate the InstanceResponse.Accessible property of a given instanceResponse .
Parameters
instanceResponse The InstanceResponse to populate.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Definition at line 861 of file InstanceController.cs.
        {
            instanceResponse.Accessible = await DatabaseContext
                .InstancePermissionSets
                .Where(x => x.InstanceId == instanceResponse.Id && x.PermissionSetId == AuthenticationContext.PermissionSet.Id)
                .AnyAsync(cancellationToken);
        }
References Tgstation.Server.Api.Models.PermissionSet.Id, Tgstation.Server.Host.Database.DatabaseContext.InstancePermissionSets, Tgstation.Server.Api.Rights.List, and Tgstation.Server.Host.Security.AuthenticationContext.PermissionSet.
Referenced by Tgstation.Server.Host.Controllers.InstanceController.GetId(), Tgstation.Server.Host.Controllers.InstanceController.List(), and Tgstation.Server.Host.Controllers.InstanceController.Update().
Create()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.InstanceController.Create ([FromBody] InstanceCreateRequest model, CancellationToken cancellationToken)
Create or attach an Api.Models.Instance.
Parameters
model The InstanceCreateRequest.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the request.
<response code="200">Instance attached successfully.</response> <response code="201">Instance created successfully.</response>
Definition at line 143 of file InstanceController.cs.
        {
            ArgumentNullException.ThrowIfNull(model);
            if (String.IsNullOrWhiteSpace(model.Name) || String.IsNullOrWhiteSpace(model.Path))
                return BadRequest(new ErrorMessageResponse(ErrorCode.InstanceWhitespaceNameOrPath));
            IActionResult? earlyOut = ValidateCronSetting(model);
            if (earlyOut != null)
                return earlyOut;
            var targetInstancePath = NormalizePath(model.Path!);
            model.Path = targetInstancePath;
            var installationDirectoryPath = DefaultIOManager.CurrentDirectory;
            if (await ioManager.PathIsChildOf(installationDirectoryPath, targetInstancePath, cancellationToken))
                return Conflict(new ErrorMessageResponse(ErrorCode.InstanceAtConflictingPath));
            // Validate it's not a child of any other instance
            var instancePaths = await DatabaseContext
                .Instances
                .Where(x => x.SwarmIdentifer == swarmConfigurationOptions.Value.Identifier)
                .Select(x => new Models.Instance
                {
                    Path = x.Path,
                })
                .ToListAsync(cancellationToken);
            var generalConfiguration = generalConfigurationOptions.Value;
            if ((instancePaths.Count + 1) >= generalConfiguration.InstanceLimit)
                return Conflict(new ErrorMessageResponse(ErrorCode.InstanceLimitReached));
            var instancePathChecks = instancePaths
                .Select(otherInstance => ioManager.PathIsChildOf(otherInstance.Path!, targetInstancePath, cancellationToken))
                .ToArray();
            await Task.WhenAll(instancePathChecks);
            if (instancePathChecks.Any(task => task.Result))
                return Conflict(new ErrorMessageResponse(ErrorCode.InstanceAtConflictingPath));
            // Last test, ensure it's in the list of valid paths
            var pathChecks = generalConfiguration.ValidInstancePaths?
                .Select(path => ioManager.PathIsChildOf(path, targetInstancePath, cancellationToken))
                .ToArray()
                ?? Enumerable.Empty<Task<bool>>();
            await Task.WhenAll(pathChecks);
            if (!pathChecks.All(task => task.Result))
                return BadRequest(new ErrorMessageResponse(ErrorCode.InstanceNotAtWhitelistedPath));
            async ValueTask<bool> DirExistsAndIsNotEmpty()
            {
                if (!await ioManager.DirectoryExists(targetInstancePath, cancellationToken))
                    return false;
                var filesTask = ioManager.GetFiles(targetInstancePath, cancellationToken);
                var dirsTask = ioManager.GetDirectories(targetInstancePath, cancellationToken);
                var files = await filesTask;
                var dirs = await dirsTask;
                return files.Concat(dirs).Any();
            }
            var dirExistsTask = DirExistsAndIsNotEmpty();
            bool attached = false;
            if (await ioManager.FileExists(targetInstancePath, cancellationToken) || await dirExistsTask)
                if (!await ioManager.FileExists(ioManager.ConcatPath(targetInstancePath, InstanceAttachFileName), cancellationToken))
                    return Conflict(new ErrorMessageResponse(ErrorCode.InstanceAtExistingPath));
                else
                    attached = true;
            var newInstance = await CreateDefaultInstance(model, cancellationToken);
            if (newInstance == null)
                return Conflict(new ErrorMessageResponse(ErrorCode.NoPortsAvailable));
            DatabaseContext.Instances.Add(newInstance);
            try
            {
                await DatabaseContext.Save(cancellationToken);
                try
                {
                    // actually reserve it now
                    await ioManager.CreateDirectory(targetInstancePath, cancellationToken);
                    await ioManager.DeleteFile(ioManager.ConcatPath(targetInstancePath, InstanceAttachFileName), cancellationToken);
                }
                catch
                {
                    // oh shit delete the model
                    DatabaseContext.Instances.Remove(newInstance);
                    // DCT: Operation must always run
                    await DatabaseContext.Save(CancellationToken.None);
                    throw;
                }
            }
            catch (IOException e)
            {
                return Conflict(new ErrorMessageResponse(ErrorCode.IOError)
                {
                    AdditionalData = e.Message,
                });
            }
            Logger.LogInformation(
                "{userName} {attachedOrCreated} instance {instanceName}: {instanceId} ({instancePath})",
                AuthenticationContext.User.Name,
                attached ? "attached" : "created",
                newInstance.Name,
                newInstance.Id,
                newInstance.Path);
            await permissionsUpdateNotifyee.InstancePermissionSetCreated(
                newInstance.InstancePermissionSets.First(),
                cancellationToken);
            var api = newInstance.ToApi();
            api.Accessible = true; // instances are always accessible by their creator
            return attached ? Json(api) : this.Created(api);
        }
References Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.Controllers.InstanceController.CreateDefaultInstance(), Tgstation.Server.Host.IO.IIOManager.CreateDirectory(), Tgstation.Server.Host.IO.DefaultIOManager.CurrentDirectory, Tgstation.Server.Host.IO.IIOManager.DeleteFile(), Tgstation.Server.Host.IO.IIOManager.DirectoryExists(), Tgstation.Server.Host.IO.IIOManager.FileExists(), Tgstation.Server.Host.Controllers.InstanceController.generalConfigurationOptions, Tgstation.Server.Host.IO.IIOManager.GetDirectories(), Tgstation.Server.Host.IO.IIOManager.GetFiles(), Tgstation.Server.Host.Controllers.InstanceController.InstanceAttachFileName, Tgstation.Server.Host.Security.IPermissionsUpdateNotifyee.InstancePermissionSetCreated(), Tgstation.Server.Host.Database.DatabaseContext.Instances, Tgstation.Server.Host.Controllers.InstanceController.ioManager, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Controllers.ApiController.Logger, Tgstation.Server.Api.Models.UserName.Name, Tgstation.Server.Host.Controllers.InstanceController.NormalizePath(), Tgstation.Server.Host.IO.IIOManager.PathIsChildOf(), Tgstation.Server.Host.Controllers.InstanceController.permissionsUpdateNotifyee, Tgstation.Server.Host.Database.DatabaseContext.Save(), Tgstation.Server.Host.Controllers.InstanceController.swarmConfigurationOptions, Tgstation.Server.Host.Security.AuthenticationContext.User, and Tgstation.Server.Host.Controllers.InstanceController.ValidateCronSetting().
CreateDefaultInstance()
async ValueTask< Models.Instance?> Tgstation.Server.Host.Controllers.InstanceController.CreateDefaultInstance (InstanceCreateRequest initialSettings, CancellationToken cancellationToken) private
Creates a default Models.Instance from initialSettings .
Parameters
initialSettings The InstanceCreateRequest.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the new Models.Instance or null if ports could not be allocated.
Definition at line 735 of file InstanceController.cs.
        {
            var ddPort = await portAllocator.GetAvailablePort(1024, false, cancellationToken);
            if (!ddPort.HasValue)
                return null;
            // try to use the old default if possible
            const ushort DefaultDreamDaemonPort = 1337;
            if (ddPort.Value < DefaultDreamDaemonPort)
                ddPort = await portAllocator.GetAvailablePort(DefaultDreamDaemonPort, false, cancellationToken) ?? ddPort;
            const ushort DefaultApiValidationPort = 1339;
            var dmPort = await portAllocator
                .GetAvailablePort(
                    Math.Min((ushort)(ddPort.Value + 1), DefaultApiValidationPort),
                    false,
                    cancellationToken);
            if (!dmPort.HasValue)
                return null;
            // try to use the old default if possible
            if (dmPort < DefaultApiValidationPort)
                dmPort = await portAllocator.GetAvailablePort(DefaultApiValidationPort, false, cancellationToken) ?? dmPort;
            return new Models.Instance
            {
                ConfigurationType = initialSettings.ConfigurationType ?? ConfigurationType.Disallowed,
                DreamDaemonSettings = new DreamDaemonSettings
                {
                    AllowWebClient = false,
                    AutoStart = false,
                    Port = ddPort,
                    OpenDreamTopicPort = 0,
                    SecurityLevel = DreamDaemonSecurity.Safe,
                    Visibility = DreamDaemonVisibility.Public,
                    StartupTimeout = 60,
                    HealthCheckSeconds = 60,
                    DumpOnHealthCheckRestart = false,
                    TopicRequestTimeout = generalConfigurationOptions.Value.ByondTopicTimeout,
                    AdditionalParameters = String.Empty,
                    StartProfiler = false,
                    LogOutput = false,
                    MapThreads = 0,
                    Minidumps = true,
                },
                DreamMakerSettings = new DreamMakerSettings
                {
                    ApiValidationPort = dmPort,
                    ApiValidationSecurityLevel = DreamDaemonSecurity.Safe,
                    DMApiValidationMode = DMApiValidationMode.Required,
                    Timeout = TimeSpan.FromHours(1),
                    CompilerAdditionalArguments = null,
                },
                Name = initialSettings.Name,
                Online = false,
                Path = initialSettings.Path,
                AutoUpdateInterval = initialSettings.AutoUpdateInterval ?? 0,
                AutoUpdateCron = initialSettings.AutoUpdateCron ?? String.Empty,
                AutoStartCron = initialSettings.AutoStartCron ?? String.Empty,
                AutoStopCron = initialSettings.AutoStopCron ?? String.Empty,
                ChatBotLimit = initialSettings.ChatBotLimit ?? Models.Instance.DefaultChatBotLimit,
                RepositorySettings = new Models.RepositorySettings
                {
                    CommitterEmail = Components.Repository.Repository.DefaultCommitterEmail,
                    CommitterName = Components.Repository.Repository.DefaultCommitterName,
                    PushTestMergeCommits = false,
                    ShowTestMergeCommitters = false,
                    AutoUpdatesKeepTestMerges = false,
                    AutoUpdatesSynchronize = false,
                    PostTestMergeComment = false,
                    CreateGitHubDeployments = false,
                    UpdateSubmodules = true,
                },
                InstancePermissionSets = new List<InstancePermissionSet> // give this user full privileges on the instance
                {
                    InstanceAdminPermissionSet(null),
                },
                SwarmIdentifer = swarmConfigurationOptions.Value.Identifier,
            };
        }
References Tgstation.Server.Host.Models.Instance.DefaultChatBotLimit, Tgstation.Server.Host.Controllers.InstanceController.generalConfigurationOptions, Tgstation.Server.Host.Utils.IPortAllocator.GetAvailablePort(), Tgstation.Server.Host.Models.DreamMakerSettings.Instance, Tgstation.Server.Host.Controllers.InstanceController.InstanceAdminPermissionSet(), Tgstation.Server.Api.Rights.List, Tgstation.Server.Api.Models.Online, Tgstation.Server.Host.Controllers.InstanceController.portAllocator, and Tgstation.Server.Host.Controllers.InstanceController.swarmConfigurationOptions.
Referenced by Tgstation.Server.Host.Controllers.InstanceController.Create().
Delete()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.InstanceController.Delete (long id, CancellationToken cancellationToken)
Detach an Api.Models.Instance with the given id .
Parameters
id The EntityId.Id of the instance to detach.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the request.
<response code="204">Instance detatched successfully.</response> <response code="410">The database entity for the requested instance could not be retrieved. The instance was likely detached.</response>
Definition at line 277 of file InstanceController.cs.
        {
            var originalModel = await DatabaseContext
                .Instances
                .Where(x => x.Id == id && x.SwarmIdentifer == swarmConfigurationOptions.Value.Identifier)
                .FirstOrDefaultAsync(cancellationToken);
            if (originalModel == default)
                return this.Gone();
            if (originalModel.Online!.Value)
                return Conflict(new ErrorMessageResponse(ErrorCode.InstanceDetachOnline));
            var originalPath = originalModel.Path!;
            var attachFileName = ioManager.ConcatPath(originalPath, InstanceAttachFileName);
            try
            {
                if (await ioManager.DirectoryExists(originalPath, cancellationToken))
                    await ioManager.WriteAllBytes(attachFileName, Array.Empty<byte>(), cancellationToken);
            }
            catch (OperationCanceledException)
            {
                // DCT: Operation must always run
                await ioManager.DeleteFile(attachFileName, CancellationToken.None);
                throw;
            }
            try
            {
                // yes this is racy af. I hate it
                // there's a bug where removing the root instance doesn't work sometimes
                await DatabaseContext
                    .CompileJobs
                    .Where(x => x.Job!.Instance!.Id == id)
                    .ExecuteDeleteAsync(cancellationToken);
                await DatabaseContext
                    .RevInfoTestMerges
                    .Where(x => x.RevisionInformation.InstanceId == id)
                    .ExecuteDeleteAsync(cancellationToken);
                await DatabaseContext
                    .RevisionInformations
                    .Where(x => x.InstanceId == id)
                    .ExecuteDeleteAsync(cancellationToken);
                DatabaseContext.Instances.Remove(originalModel);
                await DatabaseContext.Save(cancellationToken); // cascades everything else
            }
            catch
            {
                await ioManager.DeleteFile(attachFileName, CancellationToken.None); // DCT: Shouldn't be cancelled
                throw;
            }
            return NoContent();
        }
References Tgstation.Server.Host.Database.DatabaseContext.CompileJobs, Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.IO.IIOManager.DeleteFile(), Tgstation.Server.Host.IO.IIOManager.DirectoryExists(), Tgstation.Server.Host.Controllers.InstanceController.InstanceAttachFileName, Tgstation.Server.Host.Database.DatabaseContext.Instances, Tgstation.Server.Host.Controllers.InstanceController.ioManager, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Database.DatabaseContext.RevInfoTestMerges, Tgstation.Server.Host.Database.DatabaseContext.RevisionInformations, Tgstation.Server.Host.Database.DatabaseContext.Save(), Tgstation.Server.Host.Controllers.InstanceController.swarmConfigurationOptions, and Tgstation.Server.Host.IO.IIOManager.WriteAllBytes().
GetId()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.InstanceController.GetId (long id, CancellationToken cancellationToken)
Get a specific Api.Models.Instance.
Parameters
id The instance EntityId.Id to retrieve.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the request.
<response code="200">Retrieved Api.Models.Instance successfully.</response> <response code="410">The database entity for the requested instance could not be retrieved. The instance was likely detached.</response>
Definition at line 640 of file InstanceController.cs.
        {
            var cantList = !AuthenticationContext.PermissionSet.InstanceManagerRights!.Value.HasFlag(InstanceManagerRights.List);
            IQueryable<Models.Instance> QueryForUser()
            {
                var query = DatabaseContext
                    .Instances
                    .Where(x => x.Id == id && x.SwarmIdentifer == swarmConfigurationOptions.Value.Identifier);
                if (cantList)
                    query = query.Include(x => x.InstancePermissionSets);
                return query;
            }
            var instance = await QueryForUser().FirstOrDefaultAsync(cancellationToken);
            if (instance == null)
                return this.Gone();
            if (ValidateInstanceOnlineStatus(instance))
                await DatabaseContext.Save(cancellationToken);
            if (cantList && !instance.InstancePermissionSets.Any(instanceUser => instanceUser.PermissionSetId == AuthenticationContext.PermissionSet.Require(x => x.Id)
                && (instanceUser.RepositoryRights != RepositoryRights.None ||
                instanceUser.EngineRights != EngineRights.None ||
                instanceUser.ChatBotRights != ChatBotRights.None ||
                instanceUser.ConfigurationRights != ConfigurationRights.None ||
                instanceUser.DreamDaemonRights != DreamDaemonRights.None ||
                instanceUser.DreamMakerRights != DreamMakerRights.None ||
                instanceUser.InstancePermissionSetRights != InstancePermissionSetRights.None)))
                return Forbid();
            var api = instance.ToApi();
            var moveJob = await QueryForUser()
                .SelectMany(x => x.Jobs)
                .Where(x => !x.StoppedAt.HasValue && x.JobCode == JobCode.Move)
                .Include(x => x.StartedBy!)
                    .ThenInclude(x => x.CreatedBy)
                .Include(x => x.Instance)
                .FirstOrDefaultAsync(cancellationToken);
            api.MoveJob = moveJob?.ToApi();
            await CheckAccessible(api, cancellationToken);
            return Json(api);
        }
References Tgstation.Server.Host.Controllers.InstanceController.CheckAccessible(), Tgstation.Server.Api.Models.PermissionSet.InstanceManagerRights, Tgstation.Server.Host.Database.DatabaseContext.Instances, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Security.AuthenticationContext.PermissionSet, Tgstation.Server.Host.Database.DatabaseContext.Save(), Tgstation.Server.Host.Controllers.InstanceController.swarmConfigurationOptions, and Tgstation.Server.Host.Controllers.ComponentInterfacingController.ValidateInstanceOnlineStatus().
GrantPermissions()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.InstanceController.GrantPermissions (long id, CancellationToken cancellationToken)
Gives the current user full permissions on a given instance id .
Parameters
id The instance EntityId.Id to give permissions on.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the request.
<response code="204">Granted permissions successfully.</response>
Definition at line 697 of file InstanceController.cs.
        {
            IQueryable<Models.Instance> BaseQuery() => DatabaseContext
                .Instances
                .Where(x => x.Id == id && x.SwarmIdentifer == swarmConfigurationOptions.Value.Identifier);
            // ensure the current user has write privilege on the instance
            var usersInstancePermissionSet = await BaseQuery()
                .SelectMany(x => x.InstancePermissionSets)
                .Where(x => x.PermissionSetId == AuthenticationContext.PermissionSet.Id)
                .FirstOrDefaultAsync(cancellationToken);
            if (usersInstancePermissionSet == default)
            {
                // does the instance actually exist?
                var instanceExists = await BaseQuery()
                    .AnyAsync(cancellationToken);
                if (!instanceExists)
                    return this.Gone();
                var instanceAdminUser = InstanceAdminPermissionSet(null);
                instanceAdminUser.InstanceId = id;
                DatabaseContext.InstancePermissionSets.Add(instanceAdminUser);
            }
            else
                InstanceAdminPermissionSet(usersInstancePermissionSet);
            await DatabaseContext.Save(cancellationToken);
            return NoContent();
        }
References Tgstation.Server.Api.Models.PermissionSet.Id, Tgstation.Server.Host.Controllers.InstanceController.InstanceAdminPermissionSet(), Tgstation.Server.Host.Database.DatabaseContext.InstancePermissionSets, Tgstation.Server.Host.Database.DatabaseContext.Instances, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Security.AuthenticationContext.PermissionSet, Tgstation.Server.Host.Database.DatabaseContext.Save(), and Tgstation.Server.Host.Controllers.InstanceController.swarmConfigurationOptions.
InstanceAdminPermissionSet()
InstancePermissionSet Tgstation.Server.Host.Controllers.InstanceController.InstanceAdminPermissionSet (InstancePermissionSet? permissionSetToModify) private
Generate an InstancePermissionSet with full rights.
Parameters
permissionSetToModify An optional existing InstancePermissionSet to update.
Returns
permissionSetToModify or a new InstancePermissionSet with full rights.
Definition at line 821 of file InstanceController.cs.
        {
            permissionSetToModify ??= new InstancePermissionSet()
            {
                PermissionSet = AuthenticationContext.PermissionSet,
                PermissionSetId = AuthenticationContext.PermissionSet.Require(x => x.Id),
            };
            permissionSetToModify.EngineRights = RightsHelper.AllRights<EngineRights>();
            permissionSetToModify.ChatBotRights = RightsHelper.AllRights<ChatBotRights>();
            permissionSetToModify.ConfigurationRights = RightsHelper.AllRights<ConfigurationRights>();
            permissionSetToModify.DreamDaemonRights = RightsHelper.AllRights<DreamDaemonRights>();
            permissionSetToModify.DreamMakerRights = RightsHelper.AllRights<DreamMakerRights>();
            permissionSetToModify.RepositoryRights = RightsHelper.AllRights<RepositoryRights>();
            permissionSetToModify.InstancePermissionSetRights = RightsHelper.AllRights<InstancePermissionSetRights>();
            return permissionSetToModify;
        }
References Tgstation.Server.Api.Rights.List, and Tgstation.Server.Host.Security.AuthenticationContext.PermissionSet.
Referenced by Tgstation.Server.Host.Controllers.InstanceController.CreateDefaultInstance(), and Tgstation.Server.Host.Controllers.InstanceController.GrantPermissions().
List()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.InstanceController.List ([FromQuery] int? page, [FromQuery] int? pageSize, CancellationToken cancellationToken)
List Api.Models.Instances.
Parameters
page The current page.
pageSize The page size.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the request.
<response code="200">Retrieved Api.Models.Instances successfully.</response>
Definition at line 573 of file InstanceController.cs.
        {
            IQueryable<Models.Instance> GetBaseQuery()
            {
                var query = DatabaseContext
                    .Instances
                    .Where(x => x.SwarmIdentifer == swarmConfigurationOptions.Value.Identifier);
                if (!AuthenticationContext.PermissionSet.InstanceManagerRights!.Value.HasFlag(InstanceManagerRights.List))
                    query = query
                        .Where(x => x.InstancePermissionSets.Any(y => y.PermissionSetId == AuthenticationContext.PermissionSet.Id))
                        .Where(x => x.InstancePermissionSets.Any(instanceUser =>
                            instanceUser.EngineRights != EngineRights.None ||
                            instanceUser.ChatBotRights != ChatBotRights.None ||
                            instanceUser.ConfigurationRights != ConfigurationRights.None ||
                            instanceUser.DreamDaemonRights != DreamDaemonRights.None ||
                            instanceUser.DreamMakerRights != DreamMakerRights.None ||
                            instanceUser.InstancePermissionSetRights != InstancePermissionSetRights.None));
                // Hack for EF IAsyncEnumerable BS
                return query.Select(x => x);
            }
            var moveJobs = await GetBaseQuery()
                .SelectMany(x => x.Jobs)
                .Where(x => !x.StoppedAt.HasValue && x.JobCode == JobCode.Move)
                .Include(x => x.StartedBy!)
                    .ThenInclude(x => x.CreatedBy)
                .Include(x => x.Instance)
                .ToListAsync(cancellationToken);
            var needsUpdate = false;
            var result = await Paginated<Models.Instance, InstanceResponse>(
                () => ValueTask.FromResult<PaginatableResult<Models.Instance>?>(
                    new PaginatableResult<Models.Instance>(
                        GetBaseQuery()
                            .OrderBy(x => x.Id))),
                async instance =>
                {
                    needsUpdate |= ValidateInstanceOnlineStatus(instance);
                    instance.MoveJob = moveJobs.FirstOrDefault(x => x.Instance!.Id == instance.Id)?.ToApi();
                    await CheckAccessible(instance, cancellationToken);
                },
                page,
                pageSize,
                cancellationToken);
            if (needsUpdate)
                await DatabaseContext.Save(cancellationToken);
            return result;
        }
References Tgstation.Server.Host.Controllers.InstanceController.CheckAccessible(), Tgstation.Server.Api.Models.PermissionSet.Id, Tgstation.Server.Api.Models.PermissionSet.InstanceManagerRights, Tgstation.Server.Host.Database.DatabaseContext.Instances, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Security.AuthenticationContext.PermissionSet, Tgstation.Server.Host.Database.DatabaseContext.Save(), Tgstation.Server.Host.Controllers.InstanceController.swarmConfigurationOptions, and Tgstation.Server.Host.Controllers.ComponentInterfacingController.ValidateInstanceOnlineStatus().
NormalizePath()
string? Tgstation.Server.Host.Controllers.InstanceController.NormalizePath (string? path) private
Normalize a given path for an instance.
Parameters
path The path to normalize.
Returns
The normalized path .
Definition at line 844 of file InstanceController.cs.
        {
            if (path == null)
                return null;
            path = ioManager.ResolvePath(path);
            path = platformIdentifier.NormalizePath(path);
            return path;
        }
References Tgstation.Server.Host.Controllers.InstanceController.ioManager, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.System.IPlatformIdentifier.NormalizePath(), Tgstation.Server.Host.Controllers.InstanceController.platformIdentifier, and Tgstation.Server.Host.IO.IIOManager.ResolvePath().
Referenced by Tgstation.Server.Host.Controllers.InstanceController.Create(), and Tgstation.Server.Host.Controllers.InstanceController.Update().
Update()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.InstanceController.Update ([FromBody] InstanceUpdateRequest model, CancellationToken cancellationToken)
Modify an Api.Models.Instance's settings.
Parameters
model The updated Api.Models.Instance settings.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the request.
<response code="200">Instance updated successfully.</response> <response code="202">Instance updated successfully and relocation job created.</response> <response code="410">The database entity for the requested instance could not be retrieved. The instance was likely detached.</response>
Definition at line 354 of file InstanceController.cs.
        {
            ArgumentNullException.ThrowIfNull(model);
            IQueryable<Models.Instance> InstanceQuery() => DatabaseContext
                .Instances
                .Where(x => x.Id == model.Id && x.SwarmIdentifer == swarmConfigurationOptions.Value.Identifier);
            var moveJob = await InstanceQuery()
                .SelectMany(x => x.Jobs)
                .Where(x => !x.StoppedAt.HasValue && x.JobCode == JobCode.Move)
                .Select(x => new Job(x.Id!.Value))
                .FirstOrDefaultAsync(cancellationToken);
            if (moveJob != null)
            {
                // don't allow them to cancel it if they can't start it.
                if (!AuthenticationContext.PermissionSet.InstanceManagerRights!.Value.HasFlag(InstanceManagerRights.Relocate))
                    return Forbid();
                await jobManager.CancelJob(moveJob, AuthenticationContext.User, true, cancellationToken); // cancel it now
            }
            var originalModel = await InstanceQuery()
                .Include(x => x.RepositorySettings)
                .Include(x => x.ChatSettings)
                    .ThenInclude(x => x.Channels)
                .Include(x => x.DreamDaemonSettings) // need these for onlining
                .FirstOrDefaultAsync(cancellationToken);
            if (originalModel == default(Models.Instance))
                return this.Gone();
            if (ValidateInstanceOnlineStatus(originalModel))
                await DatabaseContext.Save(cancellationToken);
            var userRights = (InstanceManagerRights)AuthenticationContext.GetRight(RightsType.InstanceManager);
            bool CheckModified<T>(Expression<Func<Api.Models.Instance, T>> expression, InstanceManagerRights requiredRight)
            {
                var memberSelectorExpression = (MemberExpression)expression.Body;
                var property = (PropertyInfo)memberSelectorExpression.Member;
                var newVal = property.GetValue(model);
                if (newVal == null)
                    return false;
                if (!userRights.HasFlag(requiredRight) && property.GetValue(originalModel) != newVal)
                    return true;
                property.SetValue(originalModel, newVal);
                return false;
            }
            string? originalModelPath = null;
            string? normalizedPath = null;
            var originalOnline = originalModel.Online!.Value;
            if (model.Path != null)
            {
                normalizedPath = NormalizePath(model.Path);
                if (normalizedPath != originalModel.Path)
                {
                    if (!userRights.HasFlag(InstanceManagerRights.Relocate))
                        return Forbid();
                    if (originalOnline && model.Online != true)
                        return Conflict(new ErrorMessageResponse(ErrorCode.InstanceRelocateOnline));
                    var dirExistsTask = ioManager.DirectoryExists(model.Path, cancellationToken);
                    if (await ioManager.FileExists(model.Path, cancellationToken) || await dirExistsTask)
                        return Conflict(new ErrorMessageResponse(ErrorCode.InstanceAtExistingPath));
                    originalModelPath = originalModel.Path;
                    originalModel.Path = normalizedPath;
                }
            }
            var oldAutoUpdateInterval = originalModel.AutoUpdateInterval!.Value;
            var oldAutoUpdateCron = originalModel.AutoUpdateCron;
            var oldAutoStartCron = originalModel.AutoStartCron;
            var oldAutoStopCron = originalModel.AutoStopCron;
            var earlyOut = ValidateCronSetting(model);
            if (earlyOut != null)
                return earlyOut;
            var changedAutoUpdateInterval = model.AutoUpdateInterval.HasValue && oldAutoUpdateInterval != model.AutoUpdateInterval;
            var changedAutoUpdateCron = model.AutoUpdateCron != null && oldAutoUpdateCron != model.AutoUpdateCron;
            var changedAutoStart = model.AutoStartCron != null && oldAutoStartCron != model.AutoStartCron;
            var changedAutoStop = model.AutoStopCron != null && oldAutoStopCron != model.AutoStopCron;
            var renamed = model.Name != null && originalModel.Name != model.Name;
            if (CheckModified(x => x.AutoUpdateInterval, InstanceManagerRights.SetAutoUpdate)
                || CheckModified(x => x.AutoUpdateCron, InstanceManagerRights.SetAutoUpdate)
                || CheckModified(x => x.ConfigurationType, InstanceManagerRights.SetConfiguration)
                || CheckModified(x => x.Name, InstanceManagerRights.Rename)
                || CheckModified(x => x.Online, InstanceManagerRights.SetOnline)
                || CheckModified(x => x.ChatBotLimit, InstanceManagerRights.SetChatBotLimit)
                || CheckModified(x => x.AutoStartCron, InstanceManagerRights.SetAutoStart)
                || CheckModified(x => x.AutoStopCron, InstanceManagerRights.SetAutoStop))
                return Forbid();
            if (model.ChatBotLimit.HasValue)
            {
                var countOfExistingChatBots = await DatabaseContext
                    .ChatBots
                    .Where(x => x.InstanceId == originalModel.Id)
                    .CountAsync(cancellationToken);
                if (countOfExistingChatBots > model.ChatBotLimit.Value)
                    return Conflict(new ErrorMessageResponse(ErrorCode.ChatBotMax));
            }
            if (changedAutoUpdateCron)
                model.AutoUpdateInterval = 0;
            else if (changedAutoUpdateInterval)
                model.AutoUpdateCron = String.Empty;
            await DatabaseContext.Save(cancellationToken);
            if (renamed)
            {
                // ignoring retval because we don't care if it's offline
                await WithComponentInstanceNullable(
                    async componentInstance =>
                    {
                        await componentInstance.InstanceRenamed(originalModel.Name!, cancellationToken);
                        return null;
                    },
                    originalModel);
            }
            var oldAutoStart = originalModel.DreamDaemonSettings!.AutoStart;
            try
            {
                if (originalOnline && model.Online == false)
                    await InstanceOperations.OfflineInstance(originalModel, AuthenticationContext.User, cancellationToken);
                else if (!originalOnline && model.Online == true)
                {
                    // force autostart false here because we don't want any long running jobs right now
                    // remember to document this
                    originalModel.DreamDaemonSettings.AutoStart = false;
                    await InstanceOperations.OnlineInstance(originalModel, cancellationToken);
                }
            }
            catch (Exception e)
            {
                if (e is not OperationCanceledException)
                    Logger.LogError(e, "Error changing instance online state!");
                originalModel.Online = originalOnline;
                originalModel.DreamDaemonSettings.AutoStart = oldAutoStart;
                if (originalModelPath != null)
                    originalModel.Path = originalModelPath;
                // DCT: Operation must always run
                await DatabaseContext.Save(CancellationToken.None);
                throw;
            }
            var api = (AuthenticationContext.GetRight(RightsType.InstanceManager) & (ulong)InstanceManagerRights.Read) != 0 ? originalModel.ToApi() : new InstanceResponse
            {
                Id = originalModel.Id,
            };
            var moving = originalModelPath != null;
            if (moving)
            {
                var description = $"Move instance ID {originalModel.Id} from {originalModelPath} to {normalizedPath}";
                var job = Job.Create(JobCode.Move, AuthenticationContext.User, originalModel, InstanceManagerRights.Relocate);
                job.Description = description;
                await jobManager.RegisterOperation(
                    job,
                    (core, databaseContextFactory, paramJob, progressHandler, ct) // core will be null here since the instance is offline
                        => InstanceOperations.MoveInstance(originalModel, originalModelPath!, ct),
                    cancellationToken);
                api.MoveJob = job.ToApi();
            }
            var changedAutoUpdate = changedAutoUpdateInterval || changedAutoUpdateCron;
            if (changedAutoUpdate || changedAutoStart || changedAutoStop)
            {
                // ignoring retval because we don't care if it's offline
                await WithComponentInstanceNullable(
                    async componentInstance =>
                    {
                        var autoUpdateTask = changedAutoUpdate
                            ? componentInstance.ScheduleAutoUpdate(model.AutoUpdateInterval!.Value, model.AutoUpdateCron)
                            : ValueTask.CompletedTask;
                        var autoStartTask = changedAutoStart
                            ? componentInstance.ScheduleServerStart(model.AutoStartCron)
                            : ValueTask.CompletedTask;
                        var autoStopTask = changedAutoStop
                            ? componentInstance.ScheduleServerStop(model.AutoStopCron)
                            : ValueTask.CompletedTask;
                        await ValueTaskExtensions.WhenAll(autoUpdateTask, autoStartTask, autoStopTask);
                        return null;
                    },
                    originalModel);
            }
            await CheckAccessible(api, cancellationToken);
            return moving ? Accepted(api) : Json(api);
        }
References Tgstation.Server.Host.Jobs.IJobManager.CancelJob(), Tgstation.Server.Host.Database.DatabaseContext.ChatBots, Tgstation.Server.Host.Controllers.InstanceController.CheckAccessible(), Tgstation.Server.Host.Models.Job.Create(), Tgstation.Server.Host.IO.IIOManager.DirectoryExists(), Tgstation.Server.Host.IO.IIOManager.FileExists(), Tgstation.Server.Host.Security.AuthenticationContext.GetRight(), Tgstation.Server.Api.Models.PermissionSet.InstanceManagerRights, Tgstation.Server.Host.Controllers.ComponentInterfacingController.InstanceOperations, Tgstation.Server.Host.Database.DatabaseContext.Instances, Tgstation.Server.Host.Controllers.InstanceController.ioManager, Tgstation.Server.Host.Controllers.InstanceController.jobManager, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Controllers.ApiController.Logger, Tgstation.Server.Host.Components.IInstanceOperations.MoveInstance(), Tgstation.Server.Host.Controllers.InstanceController.NormalizePath(), Tgstation.Server.Host.Components.IInstanceOperations.OfflineInstance(), Tgstation.Server.Host.Components.IInstanceOperations.OnlineInstance(), Tgstation.Server.Host.Security.AuthenticationContext.PermissionSet, Tgstation.Server.Host.Jobs.IJobManager.RegisterOperation(), Tgstation.Server.Host.Database.DatabaseContext.Save(), Tgstation.Server.Host.Controllers.InstanceController.swarmConfigurationOptions, Tgstation.Server.Host.Security.AuthenticationContext.User, Tgstation.Server.Host.Controllers.InstanceController.ValidateCronSetting(), Tgstation.Server.Host.Controllers.ComponentInterfacingController.ValidateInstanceOnlineStatus(), Tgstation.Server.Common.Extensions.ValueTaskExtensions.WhenAll(), and Tgstation.Server.Host.Controllers.ComponentInterfacingController.WithComponentInstanceNullable().
ValidateCronSetting()
BadRequestObjectResult? Tgstation.Server.Host.Controllers.InstanceController.ValidateCronSetting (Api::Models::Instance instance) private
Validates a given instance 's Api.Models.Instance.AutoUpdateCron setting.
Parameters
instance The Api.Models.Instance to validate.
Returns
null if instance has a valid Api.Models.Instance.AutoUpdateCron setting, a BadRequestObjectResult otherwise.
Definition at line 874 of file InstanceController.cs.
        {
            if (!String.IsNullOrWhiteSpace(instance.AutoUpdateCron))
            {
                if ((instance.AutoUpdateInterval.HasValue && instance.AutoUpdateInterval.Value != 0)
                   || (CrontabSchedule.TryParse(
                       instance.AutoUpdateCron,
                       new CrontabSchedule.ParseOptions
                       {
                           IncludingSeconds = true,
                       }) == null))
                    return BadRequest(new ErrorMessageResponse(ErrorCode.ModelValidationFailure));
                instance.AutoUpdateInterval = 0;
            }
            else
                instance.AutoUpdateCron = String.Empty;
            return null;
        }
References Tgstation.Server.Api.Api, and Tgstation.Server.Api.Rights.List.
Referenced by Tgstation.Server.Host.Controllers.InstanceController.Create(), and Tgstation.Server.Host.Controllers.InstanceController.Update().
Member Data Documentation
generalConfigurationOptions
readonly IOptionsSnapshot<GeneralConfiguration> Tgstation.Server.Host.Controllers.InstanceController.generalConfigurationOptions private
The IOptionsSnapshot<TOptions> of GeneralConfiguration for the InstanceController.
Definition at line 78 of file InstanceController.cs.
Referenced by Tgstation.Server.Host.Controllers.InstanceController.Create(), Tgstation.Server.Host.Controllers.InstanceController.CreateDefaultInstance(), and Tgstation.Server.Host.Controllers.InstanceController.InstanceController().
InstanceAttachFileName
const string Tgstation.Server.Host.Controllers.InstanceController.InstanceAttachFileName = "TGS4_ALLOW_INSTANCE_ATTACH" static
File name to allow attaching instances.
Definition at line 48 of file InstanceController.cs.
Referenced by Tgstation.Server.Host.Controllers.InstanceController.Create(), Tgstation.Server.Host.Controllers.InstanceController.Delete(), and Tgstation.Server.Host.Components.InstanceManager.MoveInstance().
ioManager
readonly IIOManager Tgstation.Server.Host.Controllers.InstanceController.ioManager private
The IIOManager for the InstanceController.
Definition at line 58 of file InstanceController.cs.
Referenced by Tgstation.Server.Host.Controllers.InstanceController.Create(), Tgstation.Server.Host.Controllers.InstanceController.Delete(), Tgstation.Server.Host.Controllers.InstanceController.InstanceController(), Tgstation.Server.Host.Controllers.InstanceController.NormalizePath(), and Tgstation.Server.Host.Controllers.InstanceController.Update().
jobManager
readonly IJobManager Tgstation.Server.Host.Controllers.InstanceController.jobManager private
The IJobManager for the InstanceController.
Definition at line 53 of file InstanceController.cs.
Referenced by Tgstation.Server.Host.Controllers.InstanceController.InstanceController(), and Tgstation.Server.Host.Controllers.InstanceController.Update().
permissionsUpdateNotifyee
readonly IPermissionsUpdateNotifyee Tgstation.Server.Host.Controllers.InstanceController.permissionsUpdateNotifyee private
The IPermissionsUpdateNotifyee for the InstanceController.
Definition at line 83 of file InstanceController.cs.
Referenced by Tgstation.Server.Host.Controllers.InstanceController.Create(), and Tgstation.Server.Host.Controllers.InstanceController.InstanceController().
platformIdentifier
readonly IPlatformIdentifier Tgstation.Server.Host.Controllers.InstanceController.platformIdentifier private
The IPlatformIdentifier for the InstanceController.
Definition at line 63 of file InstanceController.cs.
Referenced by Tgstation.Server.Host.Controllers.InstanceController.InstanceController(), and Tgstation.Server.Host.Controllers.InstanceController.NormalizePath().
portAllocator
readonly IPortAllocator Tgstation.Server.Host.Controllers.InstanceController.portAllocator private
The IPortAllocator for the InstanceController.
Definition at line 68 of file InstanceController.cs.
Referenced by Tgstation.Server.Host.Controllers.InstanceController.CreateDefaultInstance(), and Tgstation.Server.Host.Controllers.InstanceController.InstanceController().
swarmConfigurationOptions
readonly IOptions<SwarmConfiguration> Tgstation.Server.Host.Controllers.InstanceController.swarmConfigurationOptions private
The IOptions<TOptions> of SwarmConfiguration for the InstanceController.
Definition at line 73 of file InstanceController.cs.
Referenced by Tgstation.Server.Host.Controllers.InstanceController.Create(), Tgstation.Server.Host.Controllers.InstanceController.CreateDefaultInstance(), Tgstation.Server.Host.Controllers.InstanceController.Delete(), Tgstation.Server.Host.Controllers.InstanceController.GetId(), Tgstation.Server.Host.Controllers.InstanceController.GrantPermissions(), Tgstation.Server.Host.Controllers.InstanceController.InstanceController(), Tgstation.Server.Host.Controllers.InstanceController.List(), and Tgstation.Server.Host.Controllers.InstanceController.Update().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Controllers/InstanceController.cs