tgstation-server: Tgstation.Server.Host.Controllers.HomeController Class Reference
Tgstation.Server.Host.Controllers.HomeController Class Reference
Root ApiController for the Application.
Public Member Functions
HomeController (IDatabaseContext databaseContext, IAuthenticationContextFactory authenticationContextFactory, ITokenFactory tokenFactory, ISystemIdentityFactory systemIdentityFactory, ICryptographySuite cryptographySuite, IAssemblyInformationProvider assemblyInformationProvider, IIdentityCache identityCache, IOAuthProviders oAuthProviders, IPlatformIdentifier platformIdentifier, ISwarmService swarmService, IServerControl serverControl, IOptions< GeneralConfiguration > generalConfigurationOptions, IOptions< ControlPanelConfiguration > controlPanelConfigurationOptions, ILogger< HomeController > logger)
Initializes a new instance of the HomeController class.
async Task< IActionResult > Home (CancellationToken cancellationToken)
Main page of the Application.
async Task< IActionResult > CreateToken (CancellationToken cancellationToken)
Attempt to authenticate a User using ApiController.ApiHeaders.
Public Member Functions inherited from Tgstation.Server.Host.Controllers.ApiController
override async Task OnActionExecutionAsync (ActionExecutingContext context, ActionExecutionDelegate next)
Private Attributes
readonly ITokenFactory tokenFactory
The ITokenFactory for the HomeController.
readonly ISystemIdentityFactory systemIdentityFactory
The ISystemIdentityFactory for the HomeController.
readonly ICryptographySuite cryptographySuite
The ICryptographySuite for the HomeController.
readonly IAssemblyInformationProvider assemblyInformationProvider
The IAssemblyInformationProvider for the HomeController.
readonly IIdentityCache identityCache
The IIdentityCache for the HomeController.
readonly IOAuthProviders oAuthProviders
The IOAuthProviders for the HomeController.
readonly IPlatformIdentifier platformIdentifier
The IPlatformIdentifier for the HomeController.
readonly ISwarmService swarmService
The ISwarmService for the HomeController.
readonly IServerControl serverControl
The IServerControl for the HomeController.
readonly GeneralConfiguration generalConfiguration
The GeneralConfiguration for the HomeController.
readonly ControlPanelConfiguration controlPanelConfiguration
The ControlPanelConfiguration for the HomeController.
Additional Inherited Members
Protected Member Functions inherited from Tgstation.Server.Host.Controllers.ApiController
ApiController (IDatabaseContext databaseContext, IAuthenticationContextFactory authenticationContextFactory, ILogger< ApiController > logger, bool requireHeaders)
Initializes a new instance of the ApiController class.
ObjectResult Gone ()
Generic 410 response.
new NotFoundObjectResult NotFound ()
Generic 404 response.
ObjectResult RequiresPosixSystemIdentity ()
Generic 501 response.
StatusCodeResult StatusCode (HttpStatusCode statusCode)
Strongly type calls to ControllerBase.StatusCode(int).
ObjectResult StatusCode (HttpStatusCode statusCode, object errorMessage)
Strongly type calls to ControllerBase.StatusCode(int, object).
ObjectResult Created (object payload)
Generic 201 response with a given payload .
ObjectResult RateLimit (RateLimitExceededException rateLimitException)
429 response for a given rateLimitException .
virtual Task< IActionResult > ValidateRequest (CancellationToken cancellationToken)
Performs validation a request.
IActionResult HeadersIssue (bool ignoreMissingAuth)
Response for missing/Invalid headers.
Task< IActionResult > Paginated< TModel > (Func< Task< PaginatableResult< TModel > > > queryGenerator, Func< TModel, Task > resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
Task< IActionResult > Paginated< TModel, TApiModel > (Func< Task< PaginatableResult< TModel > > > queryGenerator, Func< TApiModel, Task > resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
Properties inherited from Tgstation.Server.Host.Controllers.ApiController
ApiHeaders ApiHeaders [get, private set]
The Api.ApiHeaders for the operation.
IDatabaseContext DatabaseContext [get]
The IDatabaseContext for the operation.
IAuthenticationContext AuthenticationContext [get]
The IAuthenticationContext for the operation.
ILogger< ApiController > Logger [get]
The ILogger for the ApiController.
Models.Instance Instance [get]
The Instance for the operation.
Detailed Description
Root ApiController for the Application.
Definition at line 36 of file HomeController.cs.
Constructor & Destructor Documentation
HomeController()
Tgstation.Server.Host.Controllers.HomeController.HomeController (IDatabaseContext databaseContext, IAuthenticationContextFactory authenticationContextFactory, ITokenFactory tokenFactory, ISystemIdentityFactory systemIdentityFactory, ICryptographySuite cryptographySuite, IAssemblyInformationProvider assemblyInformationProvider, IIdentityCache identityCache, IOAuthProviders oAuthProviders, IPlatformIdentifier platformIdentifier, ISwarmService swarmService, IServerControl serverControl, IOptions< GeneralConfiguration > generalConfigurationOptions, IOptions< ControlPanelConfiguration > controlPanelConfigurationOptions, ILogger< HomeController > logger)
Initializes a new instance of the HomeController class.
Parameters
databaseContext The IDatabaseContext for the ApiController.
authenticationContextFactory The IAuthenticationContextFactory for the ApiController.
tokenFactory The value of tokenFactory.
systemIdentityFactory The value of systemIdentityFactory.
cryptographySuite The value of cryptographySuite.
assemblyInformationProvider The value of assemblyInformationProvider.
identityCache The value of identityCache.
oAuthProviders The value of oAuthProviders.
platformIdentifier The value of platformIdentifier.
swarmService The value of swarmService.
serverControl The value of serverControl.
generalConfigurationOptions The IOptions<TOptions> containing the value of generalConfiguration.
controlPanelConfigurationOptions The IOptions<TOptions> containing the value of controlPanelConfiguration.
logger The ILogger for the ApiController.
Definition at line 110 of file HomeController.cs.
            : base(
                  databaseContext,
                  authenticationContextFactory,
                  logger,
                  false)
        {
            this.tokenFactory = tokenFactory ?? throw new ArgumentNullException(nameof(tokenFactory));
            this.systemIdentityFactory = systemIdentityFactory ?? throw new ArgumentNullException(nameof(systemIdentityFactory));
            this.cryptographySuite = cryptographySuite ?? throw new ArgumentNullException(nameof(cryptographySuite));
            this.assemblyInformationProvider = assemblyInformationProvider ?? throw new ArgumentNullException(nameof(assemblyInformationProvider));
            this.identityCache = identityCache ?? throw new ArgumentNullException(nameof(identityCache));
            this.platformIdentifier = platformIdentifier ?? throw new ArgumentNullException(nameof(platformIdentifier));
            this.oAuthProviders = oAuthProviders ?? throw new ArgumentNullException(nameof(oAuthProviders));
            this.swarmService = swarmService ?? throw new ArgumentNullException(nameof(swarmService));
            this.serverControl = serverControl ?? throw new ArgumentNullException(nameof(serverControl));
            generalConfiguration = generalConfigurationOptions?.Value ?? throw new ArgumentNullException(nameof(generalConfigurationOptions));
            controlPanelConfiguration = controlPanelConfigurationOptions?.Value ?? throw new ArgumentNullException(nameof(controlPanelConfigurationOptions));
        }
References Tgstation.Server.Host.Controllers.HomeController.assemblyInformationProvider, Tgstation.Server.Host.Controllers.HomeController.controlPanelConfiguration, Tgstation.Server.Host.Controllers.HomeController.cryptographySuite, Tgstation.Server.Host.Controllers.HomeController.generalConfiguration, Tgstation.Server.Host.Controllers.HomeController.identityCache, Tgstation.Server.Host.Controllers.HomeController.oAuthProviders, Tgstation.Server.Host.Controllers.HomeController.platformIdentifier, Tgstation.Server.Host.Controllers.HomeController.serverControl, Tgstation.Server.Host.Controllers.HomeController.swarmService, Tgstation.Server.Host.Controllers.HomeController.systemIdentityFactory, and Tgstation.Server.Host.Controllers.HomeController.tokenFactory.
Member Function Documentation
CreateToken()
async Task< IActionResult > Tgstation.Server.Host.Controllers.HomeController.CreateToken (CancellationToken cancellationToken)
Attempt to authenticate a User using ApiController.ApiHeaders.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the IActionResult of the operation.
<response code="200">User logged in and TokenResponse generated successfully.</response> <response code="401">User authentication failed.</response> <response code="403">User authenticated but is disabled by an administrator.</response> <response code="429">OAuth authentication failed due to rate limiting.</response>
Definition at line 217 of file HomeController.cs.
        {
            if (ApiHeaders == null)
            {
                Response.Headers.Add(HeaderNames.WWWAuthenticate, new StringValues("basic realm=\"Create TGS bearer token\""));
                return HeadersIssue(false);
            }
            if (ApiHeaders.IsTokenAuthentication)
                return BadRequest(new ErrorMessageResponse(ErrorCode.TokenWithToken));
            var oAuthLogin = ApiHeaders.OAuthProvider.HasValue;
            ISystemIdentity systemIdentity = null;
            if (!oAuthLogin)
                try
                {
                    // trust the system over the database because a user's name can change while still having the same SID
                    systemIdentity = await systemIdentityFactory.CreateSystemIdentity(ApiHeaders.Username, ApiHeaders.Password, cancellationToken).ConfigureAwait(false);
                }
                catch (NotImplementedException ex)
                {
                    Logger.LogTrace(ex, "System identities not implemented!");
                }
            using (systemIdentity)
            {
                // Get the user from the database
                IQueryable<Models.User> query = DatabaseContext.Users.AsQueryable();
                if (oAuthLogin)
                {
                    var oAuthProvider = ApiHeaders.OAuthProvider.Value;
                    string externalUserId;
                    try
                    {
                        var validator = oAuthProviders
                            .GetValidator(oAuthProvider);
                        if (validator == null)
                            return BadRequest(new ErrorMessageResponse(ErrorCode.OAuthProviderDisabled));
                        externalUserId = await validator
                            .ValidateResponseCode(ApiHeaders.Token, cancellationToken)
                            .ConfigureAwait(false);
                        Logger.LogTrace("External {0} UID: {1}", oAuthProvider, externalUserId);
                    }
                    catch (RateLimitExceededException ex)
                    {
                        return RateLimit(ex);
                    }
                    if (externalUserId == null)
                        return Unauthorized();
                    query = query.Where(
                        x => x.OAuthConnections.Any(
                            y => y.Provider == oAuthProvider
                            && y.ExternalUserId == externalUserId));
                }
                else
                {
                    var canonicalUserName = Models.User.CanonicalizeName(ApiHeaders.Username);
                    if (canonicalUserName == Models.User.CanonicalizeName(Models.User.TgsSystemUserName))
                        return Unauthorized();
                    if (systemIdentity == null)
                        query = query.Where(x => x.CanonicalName == canonicalUserName);
                    else
                        query = query.Where(x => x.CanonicalName == canonicalUserName || x.SystemIdentifier == systemIdentity.Uid);
                }
                var users = await query
                    .Select(x => new Models.User
                    {
                        Id = x.Id,
                        PasswordHash = x.PasswordHash,
                        Enabled = x.Enabled,
                        Name = x.Name,
                    })
                    .ToListAsync(cancellationToken)
                    .ConfigureAwait(false);
                // Pick the DB user first
                var user = users
                    .OrderByDescending(dbUser => dbUser.SystemIdentifier == null)
                    .FirstOrDefault();
                // No user? You're not allowed
                if (user == null)
                    return Unauthorized();
                // A system user may have had their name AND password changed to one in our DB...
                // Or a DB user was created that had the same user/pass as a system user
                // Dumb admins...
                // FALLBACK TO THE DB USER HERE, DO NOT REVEAL A SYSTEM LOGIN!!!
                // This of course, allows system users to discover TGS users in this (HIGHLY IMPROBABLE) case but that is not our fault
                var originalHash = user.PasswordHash;
                var isDbUser = originalHash != null;
                bool usingSystemIdentity = systemIdentity != null && !isDbUser;
                if (!oAuthLogin)
                    if (!usingSystemIdentity)
                    {
                        // DB User password check and update
                        if (!cryptographySuite.CheckUserPassword(user, ApiHeaders.Password))
                            return Unauthorized();
                        if (user.PasswordHash != originalHash)
{
                            Logger.LogDebug("User ID {0}'s password hash needs a refresh, updating database.", user.Id);
                            var updatedUser = new Models.User
{
                                Id = user.Id,
                            };
                            DatabaseContext.Users.Attach(updatedUser);
                            updatedUser.PasswordHash = user.PasswordHash;
                            await DatabaseContext.Save(cancellationToken).ConfigureAwait(false);
                        }
                    }
                    else if (systemIdentity.Username != user.Name)
                    {
                        // System identity username change update
                        Logger.LogDebug("User ID {0}'s system identity needs a refresh, updating database.", user.Id);
                        DatabaseContext.Users.Attach(user);
                        user.Name = systemIdentity.Username;
                        user.CanonicalName = Models.User.CanonicalizeName(user.Name);
                        await DatabaseContext.Save(cancellationToken).ConfigureAwait(false);
                    }
                // Now that the bookeeping is done, tell them to fuck off if necessary
                if (!user.Enabled.Value)
                {
                    Logger.LogTrace("Not logging in disabled user {0}.", user.Id);
                    return Forbid();
                }
                var token = await tokenFactory.CreateToken(user, oAuthLogin, cancellationToken).ConfigureAwait(false);
                if (usingSystemIdentity)
                {
                    // expire the identity slightly after the auth token in case of lag
                    var identExpiry = token.ExpiresAt;
                    identExpiry += tokenFactory.ValidationParameters.ClockSkew;
                    identExpiry += TimeSpan.FromSeconds(15);
                    identityCache.CacheSystemIdentity(user, systemIdentity, identExpiry);
                }
                Logger.LogDebug("Successfully logged in user {0}!", user.Id);
                return Json(token);
            }
        }
References Tgstation.Server.Host.Security.IIdentityCache.CacheSystemIdentity(), Tgstation.Server.Host.Security.ICryptographySuite.CheckUserPassword(), Tgstation.Server.Host.Security.ISystemIdentityFactory.CreateSystemIdentity(), Tgstation.Server.Host.Security.ITokenFactory.CreateToken(), Tgstation.Server.Host.Controllers.HomeController.cryptographySuite, Tgstation.Server.Host.Security.OAuth.IOAuthProviders.GetValidator(), Tgstation.Server.Host.Controllers.ApiController.HeadersIssue(), Tgstation.Server.Host.Controllers.HomeController.identityCache, Tgstation.Server.Api.ApiHeaders.IsTokenAuthentication, Tgstation.Server.Host.Controllers.ApiController.Logger, Tgstation.Server.Api.ApiHeaders.OAuthProvider, Tgstation.Server.Host.Controllers.HomeController.oAuthProviders, Tgstation.Server.Api.ApiHeaders.Password, Tgstation.Server.Host.Controllers.ApiController.RateLimit(), Tgstation.Server.Host.Database.DatabaseContext.Save(), Tgstation.Server.Host.Controllers.HomeController.systemIdentityFactory, Tgstation.Server.Api.ApiHeaders.Token, Tgstation.Server.Host.Controllers.HomeController.tokenFactory, Tgstation.Server.Host.Security.ISystemIdentity.Uid, Tgstation.Server.Host.Swarm.Unauthorized, Tgstation.Server.Api.ApiHeaders.Username, Tgstation.Server.Host.Security.ISystemIdentity.Username, Tgstation.Server.Host.Database.DatabaseContext.Users, and Tgstation.Server.Host.Security.ITokenFactory.ValidationParameters.
Referenced by Tgstation.Server.Host.Core.SwaggerConfiguration.Apply().
Home()
async Task< IActionResult > Tgstation.Server.Host.Controllers.HomeController.Home (CancellationToken cancellationToken)
Main page of the Application.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resuting in the JsonResult containing ServerInformationResponse of the Application if a properly authenticated API request, the web control panel if on a browser and enabled, UnauthorizedResult otherwise.
<response code="200">ServerInformationResponse retrieved successfully.</response>
Definition at line 156 of file HomeController.cs.
        {
            if (controlPanelConfiguration.Enable)
                Response.Headers.Add(
                    HeaderNames.Vary,
                    new StringValues(ApiHeaders.ApiVersionHeader));
            if (ApiHeaders == null)
            {
                if (controlPanelConfiguration.Enable && !Request.Headers.TryGetValue(ApiHeaders.ApiVersionHeader, out _))
                {
                    Logger.LogDebug("No API headers on request, redirecting to control panel...");
                    return Redirect(ControlPanelController.ControlPanelRoute);
                }
                try
                {
                    // we only allow authorization header issues
                    var headers = new ApiHeaders(Request.GetTypedHeaders(), true);
                    if (!headers.Compatible())
                        return StatusCode(
                            HttpStatusCode.UpgradeRequired,
                            new ErrorMessageResponse(ErrorCode.ApiMismatch));
                }
                catch (HeadersException)
                {
                    return HeadersIssue(true);
                }
            }
            return Json(new ServerInformationResponse
            {
                Version = assemblyInformationProvider.Version,
                ApiVersion = ApiHeaders.Version,
                DMApiVersion = DMApiConstants.InteropVersion,
                MinimumPasswordLength = generalConfiguration.MinimumPasswordLength,
                InstanceLimit = generalConfiguration.InstanceLimit,
                UserLimit = generalConfiguration.UserLimit,
                UserGroupLimit = generalConfiguration.UserGroupLimit,
                ValidInstancePaths = generalConfiguration.ValidInstancePaths,
                WindowsHost = platformIdentifier.IsWindows,
                SwarmServers = swarmService.GetSwarmServers(),
                OAuthProviderInfos = await oAuthProviders.ProviderInfos(cancellationToken).ConfigureAwait(false),
                UpdateInProgress = serverControl.UpdateInProgress,
            });
        }
References Tgstation.Server.Host.Controllers.ApiController.ApiHeaders, Tgstation.Server.Api.ApiHeaders.ApiVersionHeader, Tgstation.Server.Host.Controllers.HomeController.assemblyInformationProvider, Tgstation.Server.Host.Controllers.HomeController.controlPanelConfiguration, Tgstation.Server.Host.Controllers.ControlPanelController.ControlPanelRoute, Tgstation.Server.Host.Configuration.ControlPanelConfiguration.Enable, Tgstation.Server.Host.Controllers.HomeController.generalConfiguration, Tgstation.Server.Host.Swarm.ISwarmService.GetSwarmServers(), Tgstation.Server.Host.Controllers.ApiController.HeadersIssue(), Tgstation.Server.Api.Models.Internal.ServerInformationBase.InstanceLimit, Tgstation.Server.Host.Components.Interop.DMApiConstants.InteropVersion, Tgstation.Server.Host.System.IPlatformIdentifier.IsWindows, Tgstation.Server.Host.Controllers.ApiController.Logger, Tgstation.Server.Api.Models.Internal.ServerInformationBase.MinimumPasswordLength, Tgstation.Server.Host.Controllers.HomeController.oAuthProviders, Tgstation.Server.Host.Controllers.HomeController.platformIdentifier, Tgstation.Server.Host.Security.OAuth.IOAuthProviders.ProviderInfos(), Tgstation.Server.Host.Controllers.HomeController.serverControl, Tgstation.Server.Host.Controllers.ApiController.StatusCode(), Tgstation.Server.Host.Controllers.HomeController.swarmService, Tgstation.Server.Host.Core.IServerControl.UpdateInProgress, Tgstation.Server.Host.Core.UpdateInProgress, Tgstation.Server.Api.Models.Internal.ServerInformationBase.UserGroupLimit, Tgstation.Server.Api.Models.Internal.ServerInformationBase.UserLimit, Tgstation.Server.Api.Models.Internal.ServerInformationBase.ValidInstancePaths, Tgstation.Server.Api.ApiHeaders.Version, and Tgstation.Server.Host.System.IAssemblyInformationProvider.Version.
Member Data Documentation
assemblyInformationProvider
readonly IAssemblyInformationProvider Tgstation.Server.Host.Controllers.HomeController.assemblyInformationProvider private
The IAssemblyInformationProvider for the HomeController.
Definition at line 56 of file HomeController.cs.
Referenced by Tgstation.Server.Host.Controllers.HomeController.Home(), and Tgstation.Server.Host.Controllers.HomeController.HomeController().
controlPanelConfiguration
readonly ControlPanelConfiguration Tgstation.Server.Host.Controllers.HomeController.controlPanelConfiguration private
The ControlPanelConfiguration for the HomeController.
Definition at line 91 of file HomeController.cs.
Referenced by Tgstation.Server.Host.Controllers.HomeController.Home(), and Tgstation.Server.Host.Controllers.HomeController.HomeController().
cryptographySuite
readonly ICryptographySuite Tgstation.Server.Host.Controllers.HomeController.cryptographySuite private
The ICryptographySuite for the HomeController.
Definition at line 51 of file HomeController.cs.
Referenced by Tgstation.Server.Host.Controllers.HomeController.CreateToken(), and Tgstation.Server.Host.Controllers.HomeController.HomeController().
generalConfiguration
readonly GeneralConfiguration Tgstation.Server.Host.Controllers.HomeController.generalConfiguration private
The GeneralConfiguration for the HomeController.
Definition at line 86 of file HomeController.cs.
Referenced by Tgstation.Server.Host.Controllers.HomeController.Home(), and Tgstation.Server.Host.Controllers.HomeController.HomeController().
identityCache
readonly IIdentityCache Tgstation.Server.Host.Controllers.HomeController.identityCache private
The IIdentityCache for the HomeController.
Definition at line 61 of file HomeController.cs.
Referenced by Tgstation.Server.Host.Controllers.HomeController.CreateToken(), and Tgstation.Server.Host.Controllers.HomeController.HomeController().
oAuthProviders
readonly IOAuthProviders Tgstation.Server.Host.Controllers.HomeController.oAuthProviders private
The IOAuthProviders for the HomeController.
Definition at line 66 of file HomeController.cs.
Referenced by Tgstation.Server.Host.Controllers.HomeController.CreateToken(), Tgstation.Server.Host.Controllers.HomeController.Home(), and Tgstation.Server.Host.Controllers.HomeController.HomeController().
platformIdentifier
readonly IPlatformIdentifier Tgstation.Server.Host.Controllers.HomeController.platformIdentifier private
The IPlatformIdentifier for the HomeController.
Definition at line 71 of file HomeController.cs.
Referenced by Tgstation.Server.Host.Controllers.HomeController.Home(), and Tgstation.Server.Host.Controllers.HomeController.HomeController().
serverControl
readonly IServerControl Tgstation.Server.Host.Controllers.HomeController.serverControl private
The IServerControl for the HomeController.
Definition at line 81 of file HomeController.cs.
Referenced by Tgstation.Server.Host.Controllers.HomeController.Home(), and Tgstation.Server.Host.Controllers.HomeController.HomeController().
swarmService
readonly ISwarmService Tgstation.Server.Host.Controllers.HomeController.swarmService private
The ISwarmService for the HomeController.
Definition at line 76 of file HomeController.cs.
Referenced by Tgstation.Server.Host.Controllers.HomeController.Home(), and Tgstation.Server.Host.Controllers.HomeController.HomeController().
systemIdentityFactory
readonly ISystemIdentityFactory Tgstation.Server.Host.Controllers.HomeController.systemIdentityFactory private
The ISystemIdentityFactory for the HomeController.
Definition at line 46 of file HomeController.cs.
Referenced by Tgstation.Server.Host.Controllers.HomeController.CreateToken(), and Tgstation.Server.Host.Controllers.HomeController.HomeController().
tokenFactory
readonly ITokenFactory Tgstation.Server.Host.Controllers.HomeController.tokenFactory private
The ITokenFactory for the HomeController.
Definition at line 41 of file HomeController.cs.
Referenced by Tgstation.Server.Host.Controllers.HomeController.CreateToken(), and Tgstation.Server.Host.Controllers.HomeController.HomeController().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Controllers/HomeController.cs