tgstation-server: Tgstation.Server.Host.Service.Program Class Reference
Tgstation.Server.Host.Service.Program Class Reference
Contains the entrypoint for the application.
Public Member Functions
async Task OnExecuteAsync ()
Command line handler, always runs.
Properties
bool Uninstall [get]
The –uninstall or -u option.
bool Detach [get]
The –detach or -x option. Valid only with Install.
bool Restart [get]
The –restart or -r option.
bool Install [get, set]
The –install or -i option.
bool Force [get, set]
The –force or -f option.
bool Silent [get, set]
The –silent or -s option.
bool Configure [get, set]
The –configure or -c option.
string? PassthroughArgs [get, set]
The –passthroughargs or -p option.
Private Member Functions
void InvokeSC (string? serviceToUninstall)
Runs sc.exe to either uninstall a given serviceToUninstall or install the running ServerService.
Static Private Member Functions
static Task< int > Main (string[] args)
Entrypoint for the application.
Detailed Description
Contains the entrypoint for the application.
Definition at line 25 of file Program.cs.
Member Function Documentation
InvokeSC()
void Tgstation.Server.Host.Service.Program.InvokeSC (string? serviceToUninstall) private
Runs sc.exe to either uninstall a given serviceToUninstall or install the running ServerService.
Parameters
serviceToUninstall The name of a service to uninstall.
Definition at line 160 of file Program.cs.
        {
            using var installer = new ServiceInstaller();
            if (serviceToUninstall != null)
            {
                installer.Context = new InstallContext($"old-{serviceToUninstall}-uninstall.log", null);
                installer.ServiceName = serviceToUninstall;
                installer.Uninstall(null);
                return;
            }
            var fullPathToAssembly = Path.GetFullPath(
                Assembly.GetExecutingAssembly().Location);
            var assemblyDirectory = Path.GetDirectoryName(fullPathToAssembly);
            if (assemblyDirectory == null)
                throw new InvalidOperationException($"Failed to resolve directory name of {assemblyDirectory}");
            var assemblyNameWithoutExtension = Path.GetFileNameWithoutExtension(fullPathToAssembly);
            var exePath = Path.Combine(assemblyDirectory, $"{assemblyNameWithoutExtension}.exe");
            var programDataDirectory = Path.Combine(
                Environment.GetFolderPath(
                    Environment.SpecialFolder.CommonApplicationData,
                    Environment.SpecialFolderOption.DoNotVerify),
                Server.Common.Constants.CanonicalPackageName);
            using var processInstaller = new ServiceProcessInstaller();
            processInstaller.Account = ServiceAccount.LocalSystem;
            // Mimicing Tgstation.Server.Host.Service.Wix here, which is the source of truth for this data
            installer.Context = new InstallContext(
                Path.Combine(programDataDirectory, $"tgs-install-{Guid.NewGuid()}.log"),
                new[]
                {
                    $"assemblypath=\"{exePath}\"{(String.IsNullOrWhiteSpace(PassthroughArgs) ? String.Empty : $" -p=\"{PassthroughArgs}\"")}",
                });
            installer.Description = $"{Server.Common.Constants.CanonicalPackageName} running as a Windows service.";
            installer.DisplayName = Server.Common.Constants.CanonicalPackageName;
            installer.StartType = ServiceStartMode.Automatic;
            installer.ServicesDependedOn = new string[] { "Tcpip", "Dhcp", "Dnscache" };
            installer.ServiceName = ServerService.Name;
            installer.Parent = processInstaller;
            var state = new ListDictionary();
            try
            {
                installer.Install(state);
                installer.Commit(state);
            }
            catch
            {
                installer.Rollback(state);
                throw;
            }
        }
        bool RunServiceInstall()
        {
            // First check if the service already exists
            bool serviceStopped = false;
            if (Force || !WindowsServiceHelpers.IsWindowsService())
                foreach (ServiceController sc in ServiceController.GetServices())
                    using (sc)
                    {
                        var serviceName = sc.ServiceName;
                        if (serviceName == ServerService.Name || serviceName == "tgstation-server-4")
{
                            NativeMethods.DialogResult result = !Force
                                ? NativeMethods.MessageBox(
                                    default,
                                    $"You already have another TGS service installed ({sc.ServiceName}). Would you like to uninstall it now? Pressing \"No\" will cancel this install.",
                                    "TGS Service",
                                    NativeMethods.MessageBoxButtons.YesNo)
                                : NativeMethods.DialogResult.Yes;
                            if (result != NativeMethods.DialogResult.Yes)
                                return false; // is this needed after exit?
                            // Stop it first to give it some cleanup time
                            RestartService(sc);
                            // And remove it
                            InvokeSC(sc.ServiceName);
                        }
References Tgstation.Server.Host.Service.Program.InvokeSC(), and RestartService().
Referenced by Tgstation.Server.Host.Service.Program.InvokeSC(), and Tgstation.Server.Host.Service.Program.OnExecuteAsync().
Main()
static Task< int > Tgstation.Server.Host.Service.Program.Main (string[] args) static private
Entrypoint for the application.
Parameters
args The application arguments.
Returns
A Task resulting in the Program's exit code.
OnExecuteAsync()
async Task Tgstation.Server.Host.Service.Program.OnExecuteAsync ()
Command line handler, always runs.
Returns
A Task representing the running operation.
Definition at line 93 of file Program.cs.
        {
            var standardRun = !Install && !Uninstall && !Configure;
            if (standardRun)
                if (!Silent && !WindowsServiceHelpers.IsWindowsService())
                {
                    var result = NativeMethods.MessageBox(
                        default,
                        "You are running the TGS windows service executable directly. It should only be run by the service control manager. Would you like to install and configure the service in this location?",
                        "TGS Service",
                        NativeMethods.MessageBoxButtons.YesNo);
                    if (result != NativeMethods.DialogResult.Yes)
                        return;
                    Install = true;
                    Configure = true;
                }
                else
                    using (var service = new ServerService(WatchdogFactory, GetPassthroughArgs(), LogLevel.Trace))
                    {
                        service.Run();
                        return;
                    }
            if (Configure)
                await RunConfigure(CancellationToken.None); // DCT: None available
            bool stopped = false;
            if (Uninstall)
            {
                foreach (ServiceController sc in ServiceController.GetServices())
                {
                    bool match;
                    using (sc)
                    {
                        match = sc.ServiceName == ServerService.Name;
                        if (match)
                            RestartService(sc);
                    }
                    if (match)
                        InvokeSC(ServerService.Name);
                }
                stopped = true;
            }
            if (Install)
                stopped |= RunServiceInstall();
            if (Restart)
                foreach (ServiceController sc in ServiceController.GetServices())
                    using (sc)
                        if (sc.ServiceName == ServerService.Name)
{
                            if (!stopped)
                                RestartService(sc);
                            sc.Start();
                        }
        }
References Tgstation.Server.Host.Service.Program.Configure, GetPassthroughArgs(), Tgstation.Server.Host.Service.Program.Install, Tgstation.Server.Host.Service.Program.InvokeSC(), Tgstation.Server.Host.Service.NativeMethods.MessageBox(), Tgstation.Server.Host.Service.ServerService.Name, Tgstation.Server.Host.Service.Program.Restart, RestartService(), RunConfigure(), Tgstation.Server.Host.Service.Program.Silent, and Tgstation.Server.Host.Service.Program.Uninstall.
Property Documentation
Configure
bool Tgstation.Server.Host.Service.Program.Configure get set
The –configure or -c option.
Definition at line 74 of file Program.cs.
{ get; set; }
Referenced by Tgstation.Server.Host.Service.Program.OnExecuteAsync().
Detach
bool Tgstation.Server.Host.Service.Program.Detach get
The –detach or -x option. Valid only with Install.
Definition at line 44 of file Program.cs.
{ get; }
Force
bool Tgstation.Server.Host.Service.Program.Force get set
The –force or -f option.
Definition at line 62 of file Program.cs.
{ get; set; }
Install
bool Tgstation.Server.Host.Service.Program.Install get set
The –install or -i option.
Definition at line 56 of file Program.cs.
{ get; set; }
Referenced by Tgstation.Server.Host.Service.Program.OnExecuteAsync().
PassthroughArgs
string? Tgstation.Server.Host.Service.Program.PassthroughArgs get set
The –passthroughargs or -p option.
Definition at line 80 of file Program.cs.
{ get; set; }
Restart
bool Tgstation.Server.Host.Service.Program.Restart get
The –restart or -r option.
Definition at line 50 of file Program.cs.
{ get; }
Referenced by Tgstation.Server.Host.Service.Program.OnExecuteAsync().
Silent
bool Tgstation.Server.Host.Service.Program.Silent get set
The –silent or -s option.
Definition at line 68 of file Program.cs.
{ get; set; }
Referenced by Tgstation.Server.Host.Service.Program.OnExecuteAsync().
Uninstall
bool Tgstation.Server.Host.Service.Program.Uninstall get
The –uninstall or -u option.
Definition at line 38 of file Program.cs.
{ get; }
Referenced by Tgstation.Server.Host.Service.Program.OnExecuteAsync().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host.Service/Program.cs