tgstation-server: Tgstation.Server.Host.Models.User Class Reference
Tgstation.Server.Host.Models.User Class Reference sealed
Public Member Functions
UserResponse ToApi ()
Public Member Functions inherited from Tgstation.Server.Api.Models.UserName
UserName CreateUserName ()
Create a copy of the UserName.
Public Member Functions inherited from Tgstation.Server.Host.Models.ILegacyApiTransformable< UserResponse >
TApiModel ToApi ()
Convert the ILegacyApiTransformable<TApiModel> to it's TApiModel .
Public Member Functions inherited from Tgstation.Server.Host.Models.IApiTransformable< User, GraphQL.Types.User, UserGraphQLTransformer >
TApiModel ToApi ()
Convert the IApiTransformable<TModel, TApiModel, TApiTransformer> to it's TApiModel .
Public Member Functions inherited from Tgstation.Server.Host.Models.IApiTransformable< User, GraphQL.Types.UserName, UserNameGraphQLTransformer >
TApiModel ToApi ()
Convert the IApiTransformable<TModel, TApiModel, TApiTransformer> to it's TApiModel .
Static Public Member Functions
static string CanonicalizeName (string name)
Change a UserName.Name into a CanonicalName.
Static Public Attributes
const string TgsSystemUserName = "TGS"
Username used when creating jobs automatically.
Properties
string? PasswordHash [get, set]
The hash of the user's password.
User? CreatedBy [get, set]
See UserResponse.
long? CreatedById [get, set]
The EntityId.Id of the User's CreatedBy User.
UserGroup? Group [get, set]
The UserGroup the User belongs to, if any.
long? GroupId [get, set]
The EntityId.Id of the User's Group.
PermissionSet? PermissionSet [get, set]
The PermissionSet the User has, if any.
string? CanonicalName [get, set]
The uppercase invariant of UserName.Name.
DateTimeOffset? LastPasswordUpdate [get, set]
When PasswordHash was last changed.
ICollection< User >? CreatedUsers [get, set]
Users created by this User.
ICollection< TestMerge >? TestMerges [get, set]
The TestMerges made by the User.
ICollection< OAuthConnection >? OAuthConnections [get, set]
The OAuthConnections for the User.
ICollection< OidcConnection >? OidcConnections [get, set]
The OidcConnections for the User.
Properties inherited from Tgstation.Server.Api.Models.Internal.UserModelBase
bool? Enabled [get, set]
If the UserModelBase is enabled since users cannot be deleted. System users cannot be disabled.
DateTimeOffset? CreatedAt [get, set]
When the UserModelBase was created.
string? SystemIdentifier [get, set]
The SID/UID of the UserModelBase on Windows/POSIX respectively.
Properties inherited from Tgstation.Server.Api.Models.UserName
override? string Name [get, set]
Properties inherited from Tgstation.Server.Api.Models.NamedEntity
virtual ? string Name [get, set]
The name of the entity represented by the NamedEntity.
Properties inherited from Tgstation.Server.Api.Models.EntityId
virtual ? long Id [get, set]
The ID of the entity.
Private Member Functions
UserResponse CreateUserResponse (bool recursive)
Generate a UserResponse from this.
Additional Inherited Members
Protected Member Functions inherited from Tgstation.Server.Api.Models.UserName
virtual TResultType CreateUserName< TResultType > ()
Create a copy of the UserName as a given TResultType .
Detailed Description
Definition at line 13 of file User.cs.
Member Function Documentation
CanonicalizeName()
static string Tgstation.Server.Host.Models.User.CanonicalizeName (string name) static
Change a UserName.Name into a CanonicalName.
Parameters
name The UserName.Name.
Returns
The CanonicalName.
Referenced by Tgstation.Server.Host.Authority.LoginAuthority.AttemptLogin(), Tgstation.Server.Host.Authority.UserAuthority.Create(), Tgstation.Server.Host.Database.DatabaseSeeder.GetAdminUser(), Tgstation.Server.Host.Authority.UserAuthority.GetId(), Tgstation.Server.Host.Extensions.DatabaseCollectionExtensions.GetTgsUser< TResult >(), Tgstation.Server.Host.Authority.UserAuthority.Queryable(), Tgstation.Server.Host.Database.DatabaseSeeder.SanitizeDatabase(), Tgstation.Server.Host.Database.DatabaseSeeder.SeedAdminUser(), Tgstation.Server.Host.Database.DatabaseSeeder.SeedSystemUser(), Tgstation.Server.Host.Authority.UserAuthority.Update(), and Tgstation.Server.Host.Security.AuthenticationContextFactory.ValidateOidcToken().
CreateUserResponse()
UserResponse Tgstation.Server.Host.Models.User.CreateUserResponse (bool recursive) private
Generate a UserResponse from this.
Parameters
recursive If we should recurse on CreatedBy.
Returns
A new UserResponse.
Definition at line 100 of file User.cs.
        {
            var result = CreateUserName<UserResponse>();
            if (recursive)
                result.CreatedBy = CreatedBy?.CreateUserName<UserName>();
            result.CreatedAt = CreatedAt;
            result.Enabled = Enabled;
            result.SystemIdentifier = SystemIdentifier;
            result.OAuthConnections = OAuthConnections
                ?.Select(x => x.ToApi())
                .ToList();
            result.OidcConnections = OidcConnections
                ?.Select(x => x.ToApi())
                .ToList();
            result.Group = Group?.ToApi(false);
            result.PermissionSet = PermissionSet?.ToApi();
            return result;
        }
References Tgstation.Server.Api.Models.Internal.UserModelBase.CreatedAt, Tgstation.Server.Host.Models.User.CreatedBy, Tgstation.Server.Api.Models.UserName.CreateUserName(), Tgstation.Server.Api.Models.Internal.UserModelBase.Enabled, Tgstation.Server.Host.Models.User.Group, Tgstation.Server.Host.Models.User.OAuthConnections, Tgstation.Server.Host.Models.User.OidcConnections, Tgstation.Server.Api.Models.Internal.UserModelBase.SystemIdentifier, Tgstation.Server.Host.Models.PermissionSet.ToApi(), and Tgstation.Server.Host.Models.UserGroup.ToApi().
ToApi()
UserResponse Tgstation.Server.Host.Models.User.ToApi ()
Referenced by Tgstation.Server.Host.Authority.LoginAuthority.AttemptLogin().
Member Data Documentation
TgsSystemUserName
const string Tgstation.Server.Host.Models.User.TgsSystemUserName = "TGS" static
Username used when creating jobs automatically.
Definition at line 21 of file User.cs.
Referenced by Tgstation.Server.Host.Authority.LoginAuthority.AttemptLogin(), Tgstation.Server.Host.Authority.UserAuthority.GetId(), Tgstation.Server.Host.Extensions.DatabaseCollectionExtensions.GetTgsUser< TResult >(), Tgstation.Server.Host.Authority.UserAuthority.Queryable(), Tgstation.Server.Host.Database.DatabaseSeeder.SanitizeDatabase(), Tgstation.Server.Host.Database.DatabaseSeeder.SeedSystemUser(), and Tgstation.Server.Host.Authority.UserAuthority.Update().
Property Documentation
CanonicalName
string? Tgstation.Server.Host.Models.User.CanonicalName get set
The uppercase invariant of UserName.Name.
Definition at line 58 of file User.cs.
{ get; set; }
Referenced by Tgstation.Server.Host.Authority.UserAuthority.GetId().
CreatedBy
User? Tgstation.Server.Host.Models.User.CreatedBy get set
See UserResponse.
Definition at line 31 of file User.cs.
{ get; set; }
Referenced by Tgstation.Server.Host.Models.User.CreateUserResponse().
CreatedById
long? Tgstation.Server.Host.Models.User.CreatedById get set
The EntityId.Id of the User's CreatedBy User.
Definition at line 36 of file User.cs.
{ get; set; }
CreatedUsers
ICollection<User>? Tgstation.Server.Host.Models.User.CreatedUsers get set
Users created by this User.
Definition at line 68 of file User.cs.
{ get; set; }
Group
UserGroup? Tgstation.Server.Host.Models.User.Group get set
The UserGroup the User belongs to, if any.
Definition at line 41 of file User.cs.
{ get; set; }
Referenced by Tgstation.Server.Host.Models.User.CreateUserResponse(), Tgstation.Server.Host.Security.AuthenticationContext.Initialize(), and Tgstation.Server.Host.Authority.UserGroupAuthority.Read().
GroupId
long? Tgstation.Server.Host.Models.User.GroupId get set
The EntityId.Id of the User's Group.
Definition at line 46 of file User.cs.
{ get; set; }
Referenced by Tgstation.Server.Host.Authority.UserGroupAuthority.GetId().
LastPasswordUpdate
DateTimeOffset? Tgstation.Server.Host.Models.User.LastPasswordUpdate get set
When PasswordHash was last changed.
Definition at line 63 of file User.cs.
{ get; set; }
Referenced by Tgstation.Server.Host.Security.TokenFactory.CreateToken().
OAuthConnections
ICollection<OAuthConnection>? Tgstation.Server.Host.Models.User.OAuthConnections get set
The OAuthConnections for the User.
Definition at line 78 of file User.cs.
{ get; set; }
Referenced by Tgstation.Server.Host.Models.User.CreateUserResponse().
OidcConnections
ICollection<OidcConnection>? Tgstation.Server.Host.Models.User.OidcConnections get set
The OidcConnections for the User.
Definition at line 83 of file User.cs.
{ get; set; }
Referenced by Tgstation.Server.Host.Models.User.CreateUserResponse().
PasswordHash
string? Tgstation.Server.Host.Models.User.PasswordHash get set
The hash of the user's password.
Definition at line 26 of file User.cs.
{ get; set; }
Referenced by Tgstation.Server.Host.Security.CryptographySuite.CheckUserPassword().
PermissionSet
PermissionSet? Tgstation.Server.Host.Models.User.PermissionSet get set
The PermissionSet the User has, if any.
Definition at line 51 of file User.cs.
{ get; set; }
Referenced by Tgstation.Server.Host.Security.AuthenticationContextFactory.ValidateOidcToken().
TestMerges
ICollection<TestMerge>? Tgstation.Server.Host.Models.User.TestMerges get set
The TestMerges made by the User.
Definition at line 73 of file User.cs.
{ get; set; }
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Models/User.cs