tgstation-server: Tgstation.Server.Host.System.WindowsProcessFeatures Class Reference
Tgstation.Server.Host.System.WindowsProcessFeatures Class Reference
Public Member Functions
WindowsProcessFeatures (ILogger< WindowsProcessFeatures > logger)
Initializes a new instance of the WindowsProcessFeatures class.
void ResumeProcess (global::System.Diagnostics.Process process)
Resume a given suspended global::System.Diagnostics.Process.
Parameters
process The Process to suspended.
void SuspendProcess (global::System.Diagnostics.Process process)
Suspend a given process .
Parameters
process The global::System.Diagnostics.Process to suspend.
string GetExecutingUsername (global::System.Diagnostics.Process process)
Get the name of the user executing a given process .
Parameters
process The global::System.Diagnostics.Process.
Returns
The name of the user executing process .
async ValueTask CreateDump (global::System.Diagnostics.Process process, string outputFile, bool minidump, CancellationToken cancellationToken)
Create a dump file for a given process .
Parameters
process The global::System.Diagnostics.Process to dump.
outputFile The full path to the output file.
minidump If a minidump should be taken as opposed to a full dump.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
ValueTask< int > HandleProcessStart (global::System.Diagnostics.Process process, CancellationToken cancellationToken)
Run events on starting a process.
Parameters
process The global::System.Diagnostics.Process that was started.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the process ID.
string GetExecutingUsername (global::System.Diagnostics.Process process)
Get the name of the user executing a given process .
void SuspendProcess (global::System.Diagnostics.Process process)
Suspend a given process .
void ResumeProcess (global::System.Diagnostics.Process process)
Resume a given suspended global::System.Diagnostics.Process.
ValueTask CreateDump (global::System.Diagnostics.Process process, string outputFile, bool minidump, CancellationToken cancellationToken)
Create a dump file for a given process .
ValueTask< int > HandleProcessStart (global::System.Diagnostics.Process process, CancellationToken cancellationToken)
Run events on starting a process.
Private Attributes
readonly ILogger< WindowsProcessFeatures > logger
The ILogger for the WindowsProcessFeatures.
Detailed Description
Definition at line 22 of file WindowsProcessFeatures.cs.
Constructor & Destructor Documentation
WindowsProcessFeatures()
Tgstation.Server.Host.System.WindowsProcessFeatures.WindowsProcessFeatures (ILogger< WindowsProcessFeatures > logger)
Initializes a new instance of the WindowsProcessFeatures class.
Parameters
logger The value of logger.
Definition at line 33 of file WindowsProcessFeatures.cs.
        {
            this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }
References Tgstation.Server.Host.System.WindowsProcessFeatures.logger.
Member Function Documentation
CreateDump()
async ValueTask Tgstation.Server.Host.System.WindowsProcessFeatures.CreateDump (global::System.Diagnostics.Process process, string outputFile, bool minidump, CancellationToken cancellationToken)
Create a dump file for a given process .
Parameters
process The global::System.Diagnostics.Process to dump.
outputFile The full path to the output file.
minidump If a minidump should be taken as opposed to a full dump.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.System.IProcessFeatures.
Definition at line 136 of file WindowsProcessFeatures.cs.
        {
            try
            {
                if (process.HasExited)
                    throw new JobException(ErrorCode.GameServerOffline);
            }
            catch (InvalidOperationException ex)
            {
                throw new JobException(ErrorCode.GameServerOffline, ex);
            }
            await using var fileStream = new FileStream(outputFile, FileMode.CreateNew);
            await Task.Factory.StartNew(
                () =>
                {
                    var flags = NativeMethods.MiniDumpType.WithHandleData
                        | NativeMethods.MiniDumpType.WithThreadInfo
                        | NativeMethods.MiniDumpType.WithUnloadedModules;
                    if (!minidump)
                        flags |= NativeMethods.MiniDumpType.WithDataSegs
                            | NativeMethods.MiniDumpType.WithFullMemory;
                    if (!NativeMethods.MiniDumpWriteDump(
                        process.Handle,
                        (uint)process.Id,
                        fileStream.SafeFileHandle,
                        flags,
                        IntPtr.Zero,
                        IntPtr.Zero,
                        IntPtr.Zero))
                        throw new Win32Exception();
                },
                cancellationToken,
                DefaultIOManager.BlockingTaskCreationOptions,
                TaskScheduler.Current);
        }
References Tgstation.Server.Host.IO.DefaultIOManager.BlockingTaskCreationOptions, and Tgstation.Server.Host.System.NativeMethods.MiniDumpWriteDump().
GetExecutingUsername()
string Tgstation.Server.Host.System.WindowsProcessFeatures.GetExecutingUsername (global::System.Diagnostics.Process process)
Get the name of the user executing a given process .
Parameters
process The global::System.Diagnostics.Process.
Returns
The name of the user executing process .
Implements Tgstation.Server.Host.System.IProcessFeatures.
Definition at line 109 of file WindowsProcessFeatures.cs.
        {
            string query = $"SELECT * FROM Win32_Process WHERE ProcessId = {process?.Id ?? throw new ArgumentNullException(nameof(process))}";
            using var searcher = new ManagementObjectSearcher(query);
            foreach (var obj in searcher.Get().Cast<ManagementObject>())
            {
                var argList = new string[] { String.Empty, String.Empty };
                var returnString = obj.InvokeMethod(
                    "GetOwner",
                    argList)
                    ?.ToString();
                if (!Int32.TryParse(returnString, out var returnVal))
                    return $"BAD RETURN PARSE: {returnString}";
                if (returnVal == 0)
                {
                    // return DOMAIN\user
                    string owner = argList.Last() + "\\" + argList.First();
                    return owner;
                }
            }
            return "NO OWNER";
        }
HandleProcessStart()
ValueTask< int > Tgstation.Server.Host.System.WindowsProcessFeatures.HandleProcessStart (global::System.Diagnostics.Process process, CancellationToken cancellationToken)
Run events on starting a process.
Parameters
process The global::System.Diagnostics.Process that was started.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the process ID.
Implements Tgstation.Server.Host.System.IProcessFeatures.
ResumeProcess()
void Tgstation.Server.Host.System.WindowsProcessFeatures.ResumeProcess (global::System.Diagnostics.Process process)
Resume a given suspended global::System.Diagnostics.Process.
Parameters
process The Process to suspended.
Implements Tgstation.Server.Host.System.IProcessFeatures.
Definition at line 39 of file WindowsProcessFeatures.cs.
        {
            ArgumentNullException.ThrowIfNull(process);
            process.Refresh();
            foreach (ProcessThread thread in process.Threads)
            {
                var threadId = (uint)thread.Id;
                logger.LogTrace("Resuming thread {threadId}...", threadId);
                var pOpenThread = NativeMethods.OpenThread(NativeMethods.ThreadAccess.SuspendResume, false, threadId);
                if (pOpenThread == IntPtr.Zero)
                {
                    logger.LogDebug(new Win32Exception(), "Failed to open thread {threadId}!", threadId);
                    continue;
                }
                try
                {
                    if (NativeMethods.ResumeThread(pOpenThread) == UInt32.MaxValue)
                        throw new Win32Exception();
                }
                finally
                {
                    NativeMethods.CloseHandle(pOpenThread);
                }
            }
        }
References Tgstation.Server.Host.System.NativeMethods.CloseHandle(), Tgstation.Server.Host.System.WindowsProcessFeatures.logger, Tgstation.Server.Host.System.NativeMethods.OpenThread(), and Tgstation.Server.Host.System.NativeMethods.ResumeThread().
SuspendProcess()
void Tgstation.Server.Host.System.WindowsProcessFeatures.SuspendProcess (global::System.Diagnostics.Process process)
Suspend a given process .
Parameters
process The global::System.Diagnostics.Process to suspend.
Implements Tgstation.Server.Host.System.IProcessFeatures.
Definition at line 68 of file WindowsProcessFeatures.cs.
        {
            ArgumentNullException.ThrowIfNull(process);
            var suspendedThreadIds = new HashSet<uint>();
            bool suspendedNewThreads;
            do
            {
                suspendedNewThreads = false;
                process.Refresh();
                foreach (ProcessThread thread in process.Threads)
                {
                    var threadId = (uint)thread.Id;
                    if (!suspendedThreadIds.Add(threadId))
                        continue;
                    suspendedNewThreads = true;
                    logger.LogTrace("Suspending thread {threadId}...", threadId);
                    var pOpenThread = NativeMethods.OpenThread(NativeMethods.ThreadAccess.SuspendResume, false, threadId);
                    if (pOpenThread == IntPtr.Zero)
                    {
                        logger.LogDebug(new Win32Exception(), "Failed to open thread {threadId}!", threadId);
                        continue;
                    }
                    try
                    {
                        if (NativeMethods.SuspendThread(pOpenThread) == UInt32.MaxValue)
                            throw new Win32Exception();
                    }
                    finally
                    {
                        NativeMethods.CloseHandle(pOpenThread);
                    }
                }
            }
            while (suspendedNewThreads);
        }
References Tgstation.Server.Host.System.NativeMethods.CloseHandle(), Tgstation.Server.Host.System.WindowsProcessFeatures.logger, Tgstation.Server.Host.System.NativeMethods.OpenThread(), and Tgstation.Server.Host.System.NativeMethods.SuspendThread().
Member Data Documentation
logger
readonly ILogger<WindowsProcessFeatures> Tgstation.Server.Host.System.WindowsProcessFeatures.logger private
The ILogger for the WindowsProcessFeatures.
Definition at line 27 of file WindowsProcessFeatures.cs.
Referenced by Tgstation.Server.Host.System.WindowsProcessFeatures.ResumeProcess(), Tgstation.Server.Host.System.WindowsProcessFeatures.SuspendProcess(), and Tgstation.Server.Host.System.WindowsProcessFeatures.WindowsProcessFeatures().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/System/WindowsProcessFeatures.cs