tgstation-server: Tgstation.Server.Host.Core.OpenApiEnumVarNamesExtension Class Reference
Tgstation.Server.Host.Core.OpenApiEnumVarNamesExtension Class Reference
Implements the "x-enum-varnames" OpenAPI 3.0 extension.
Public Member Functions
void Write (IOpenApiWriter writer, OpenApiSpecVersion specVersion)
Static Public Member Functions
static void Apply (OpenApiSchema openApiSchema, Type enumType)
Applies the extension to a give openApiSchema .
Private Member Functions
OpenApiEnumVarNamesExtension (Type enumType)
Initializes a new instance of the OpenApiEnumVarNamesExtension class.
Private Attributes
readonly Type enumType
The Type of the Enum being described.
Detailed Description
Implements the "x-enum-varnames" OpenAPI 3.0 extension.
Definition at line 13 of file OpenApiEnumVarNamesExtension.cs.
Constructor & Destructor Documentation
OpenApiEnumVarNamesExtension()
Tgstation.Server.Host.Core.OpenApiEnumVarNamesExtension.OpenApiEnumVarNamesExtension (Type enumType) private
Initializes a new instance of the OpenApiEnumVarNamesExtension class.
Parameters
enumType The value of enumType,.
Definition at line 24 of file OpenApiEnumVarNamesExtension.cs.
        {
            this.enumType = enumType ?? throw new ArgumentNullException(nameof(enumType));
        }
References Tgstation.Server.Host.Core.OpenApiEnumVarNamesExtension.enumType.
Referenced by Tgstation.Server.Host.Core.OpenApiEnumVarNamesExtension.Apply().
Member Function Documentation
Apply()
static void Tgstation.Server.Host.Core.OpenApiEnumVarNamesExtension.Apply (OpenApiSchema openApiSchema, Type enumType) static
Applies the extension to a give openApiSchema .
Parameters
openApiSchema The OpenApiSchema to apply to.
enumType The Type of the Enum being described.
Definition at line 34 of file OpenApiEnumVarNamesExtension.cs.
        {
            if (openApiSchema == null)
                throw new ArgumentNullException(nameof(openApiSchema));
            openApiSchema.Extensions.Add("x-enum-varnames", new OpenApiEnumVarNamesExtension(enumType));
        }
References Tgstation.Server.Host.Core.OpenApiEnumVarNamesExtension.enumType, and Tgstation.Server.Host.Core.OpenApiEnumVarNamesExtension.OpenApiEnumVarNamesExtension().
Referenced by Tgstation.Server.Host.Core.SwaggerConfiguration.Apply().
Write()
void Tgstation.Server.Host.Core.OpenApiEnumVarNamesExtension.Write (IOpenApiWriter writer, OpenApiSpecVersion specVersion)
Definition at line 43 of file OpenApiEnumVarNamesExtension.cs.
        {
            if (writer == null)
                throw new ArgumentNullException(nameof(writer));
            if (specVersion != OpenApiSpecVersion.OpenApi3_0)
                throw new InvalidOperationException("This extension only applies to OpenAPI 3.0!");
            writer.WriteStartArray();
            foreach (var enumValue in Enum.GetValues(enumType))
            {
                var enumName = enumValue.ToString();
                var field = enumType.GetField(enumName);
                if (field.IsDefined(typeof(ObsoleteAttribute), false))
                    enumName = $"DEPRECATED_{enumName}";
                writer.WriteValue(enumName);
            }
            writer.WriteEndArray();
        }
References Tgstation.Server.Host.Core.OpenApiEnumVarNamesExtension.enumType.
Member Data Documentation
enumType
readonly Type Tgstation.Server.Host.Core.OpenApiEnumVarNamesExtension.enumType private
The Type of the Enum being described.
Definition at line 18 of file OpenApiEnumVarNamesExtension.cs.
Referenced by Tgstation.Server.Host.Core.OpenApiEnumVarNamesExtension.Apply(), Tgstation.Server.Host.Core.OpenApiEnumVarNamesExtension.OpenApiEnumVarNamesExtension(), and Tgstation.Server.Host.Core.OpenApiEnumVarNamesExtension.Write().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Core/OpenApiEnumVarNamesExtension.cs