tgstation-server: Tgstation.Server.Host.Database.Design.DesignTimeDbContextFactoryHelpers Class Reference
Tgstation.Server.Host.Database.Design.DesignTimeDbContextFactoryHelpers Class Reference
Contains helpers for creating design time DatabaseContexts
Static Public Member Functions
static IOptions< DatabaseConfiguration > GetDatabaseConfiguration (DatabaseType databaseType, string connectionString)
Get the IOptions<TOptions> for the DatabaseConfiguration
Detailed Description
Contains helpers for creating design time DatabaseContexts
Definition at line 9 of file DesignTimeDbContextFactoryHelpers.cs.
Member Function Documentation
static IOptions<DatabaseConfiguration> Tgstation.Server.Host.Database.Design.DesignTimeDbContextFactoryHelpers.GetDatabaseConfiguration (DatabaseType databaseType, string connectionString) static
Get the IOptions<TOptions> for the DatabaseConfiguration
Parameters
databaseType The DatabaseConfiguration.DatabaseType.
connectionString The DatabaseConfiguration.ConnectionString.
Returns
The IOptions<TOptions> for the DatabaseConfiguration
Definition at line 17 of file DesignTimeDbContextFactoryHelpers.cs.
Referenced by Tgstation.Server.Host.Database.Design.PostgresSqlDesignTimeDbContextFactory.CreateDbContext(), Tgstation.Server.Host.Database.Design.SqlServerDesignTimeDbContextFactory.CreateDbContext(), Tgstation.Server.Host.Database.Design.SqliteDesignTimeDbContextFactory.CreateDbContext(), and Tgstation.Server.Host.Database.Design.MySqlDesignTimeDbContextFactory.CreateDbContext().
         {
             var dbConfig = new DatabaseConfiguration
             {
                 DesignTime = true,
                 DatabaseType = databaseType,
                 ConnectionString = connectionString
             };
             return Options.Create(dbConfig);
         }
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Database/Design/DesignTimeDbContextFactoryHelpers.cs