tgstation-server: Tgstation.Server.Host.Console.Program Class Reference
Tgstation.Server.Host.Console.Program Class Reference
Contains the entrypoint for the application
Properties
static internal IWatchdogFactory WatchdogFactory = new WatchdogFactory() [get, set]
The IWatchdogFactory for the Program
Static Private Member Functions
static internal async Task Main (string[] args)
Entrypoint for the application
Detailed Description
Contains the entrypoint for the application
Definition at line 13 of file Program.cs.
Member Function Documentation
Main()
static internal async Task Tgstation.Server.Host.Console.Program.Main (string [] args) static private
Entrypoint for the application
Parameters
args The arguments for the Program
Returns
A Task representing the running operation
Definition at line 25 of file Program.cs.
         {
             using (var loggerFactory = new LoggerFactory())
             {
                 var arguments = new List<string>(args);
                 var trace = arguments.Remove("--trace-host-watchdog");
                 var debug = arguments.Remove("--debug-host-watchdog");
 #pragma warning disable CS0618 // Type or member is obsolete
                 loggerFactory.AddConsole(trace ? LogLevel.Trace : debug ? LogLevel.Debug : LogLevel.Information, true);
 #pragma warning restore CS0618 // Type or member is obsolete
                 if (trace && debug)
                 {
                     loggerFactory.CreateLogger(nameof(Program)).LogCritical("Please specify only 1 of --trace-host-watchdog or --debug-host-watchdog!");
                     return;
                 }
                 using (var cts = new CancellationTokenSource())
                 {
                     void AppDomainHandler(object a, EventArgs b) => cts.Cancel();
                     AppDomain.CurrentDomain.ProcessExit += AppDomainHandler;
                     try
                     {
                         System.Console.CancelKeyPress += (a, b) =>
{
                             b.Cancel = true;
                             cts.Cancel();
                         };
                         await WatchdogFactory.CreateWatchdog(loggerFactory).RunAsync(false, arguments.ToArray(), cts.Token).ConfigureAwait(false);
                     }
                     finally
                     {
                         AppDomain.CurrentDomain.ProcessExit -= AppDomainHandler;
                     }
                 }
             }
         }
References Tgstation.Server.Host.Watchdog.WatchdogFactory.CreateWatchdog(), and Tgstation.Server.Host.Watchdog.IWatchdog.RunAsync().
Referenced by Tgstation.Server.Host.Console.Tests.TestProgram.TestProgramRuns().
Property Documentation
WatchdogFactory
internal IWatchdogFactory Tgstation.Server.Host.Console.Program.WatchdogFactory = new WatchdogFactory() static get set private
The IWatchdogFactory for the Program
Definition at line 18 of file Program.cs.
 { get; set; } = new WatchdogFactory();
Referenced by Tgstation.Server.Host.Console.Tests.TestProgram.TestProgramRuns().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host.Console/Program.cs