tgstation-server: TGServerService.ChatProviders.IRCChatProvider Class Reference
TGServerService.ChatProviders.IRCChatProvider Class Reference
IChatProvider for internet relay chat
Public Member Functions
ChatSetupInfo ProviderInfo ()
Gets the info of the provider
IRCChatProvider (ChatSetupInfo info)
Construct a IRCChatProvider
string SendMessageDirect (string message, string channel)
Send a message to a channel
string SetProviderInfo (ChatSetupInfo info)
Sets info for the provider
string Connect ()
Connects the chat provider if it's enabled
string Reconnect ()
Forces a reconnection of the chat provider if it's enabled
void Disconnect ()
Disconnects the chat provider
bool Connected ()
Checks if the chat provider is connected
void SendMessage (string message, MessageType mt)
Broadcast a message to appropriate channels based on the message type
void Dispose ()
Implements the IDisposable pattern
Events
OnChatMessage OnChatMessage
Events inherited from TGServerService.ChatProviders.IChatProvider
OnChatMessage OnChatMessage
Called with chat message info
Private Member Functions
bool CheckAdmin (IrcMessageData e)
Checks if a message is considered sent from a chat admin
void Irc_OnQueryMessage (object sender, IrcEventArgs e)
Called when the bot recieves a query message
void Irc_OnChannelMessage (object sender, IrcEventArgs e)
Called when a channel the bot is in recieves a message
void JoinChannels ()
Joins all channels specified in IRCConfig
void Login ()
Sends a login query to IRCSetupInfo.AuthTarget with message IRCSetupInfo.AuthMessage
void IRCListen ()
Runs the irc listener in a safe loop
void Dispose (bool disposing)
Implements the IDisposable pattern. Calls Disconnect and sets irc to
Private Attributes
const string PrivateMessageMarker = "---PRIVATE-MSG---"
Header used to mark that a channel is actually a query message
IrcFeatures irc
The irc client
object IRCLock = new object()
Used for multithreading safety
IRCSetupInfo IRCConfig
The setup info for the provider
bool disposedValue = false
To detect redundant Dispose() calls
Detailed Description
IChatProvider for internet relay chat
Definition at line 12 of file IRCChatProvider.cs.
Constructor & Destructor Documentation
TGServerService.ChatProviders.IRCChatProvider.IRCChatProvider (ChatSetupInfo info)
Construct a IRCChatProvider
Parameters
info The ChatSetupInfo
Definition at line 45 of file IRCChatProvider.cs.
References TGServerService.Service.Version.
         {
             IRCConfig = new IRCSetupInfo(info);
             irc = new IrcFeatures()
             {
                 SupportNonRfc = true,
                 CtcpUserInfo = Service.Version,
                 AutoRejoin = true,
                 AutoRejoinOnKick = true,
                 AutoRelogin = true,
                 AutoRetry = true,
                 AutoRetryLimit = 5,
                 AutoRetryDelay = 5,
                 ActiveChannelSyncing = true,
             };
             irc.OnChannelMessage += Irc_OnChannelMessage;
             irc.OnQueryMessage += Irc_OnQueryMessage;
         }
Member Function Documentation
bool TGServerService.ChatProviders.IRCChatProvider.CheckAdmin (IrcMessageData e) private
Checks if a message is considered sent from a chat admin
Parameters
e The IrcMessageData
Returns
if e was sent by a chat admin, otherwise
Definition at line 112 of file IRCChatProvider.cs.
References TGServiceInterface.ChatSetupInfo.AdminList, TGServiceInterface.ChatSetupInfo.AdminsAreSpecial, and TGServiceInterface.IRCSetupInfo.AuthLevel.
         {
             if (IRCConfig.AdminsAreSpecial)
             {
                 if (e.Channel == null)
                     return false;
                 var user = (NonRfcChannelUser)irc.GetChannelUser(e.Channel, e.Nick);
                 if (user != null)
                     switch (IRCConfig.AuthLevel)
                     {
                         case IRCMode.Voice:
                             if (user.IsVoice)
                                 return true;
                             goto case IRCMode.Halfop;
                         case IRCMode.Halfop:
                             if (user.IsHalfop)
                                 return true;
                             goto case IRCMode.Op;
                         case IRCMode.Op:
                             if (user.IsOp)
                                 return true;
                             goto case IRCMode.Owner;
                         case IRCMode.Owner:
                             if (user.IsOwner)
                                 return true;
                             break;
                     }
             }
             else
             {
                 var lowerNick = e.Nick.ToLower();
                 foreach (var I in IRCConfig.AdminList)
                     if (lowerNick == I.ToLower())
                         return true;
             }
             return false;
         }
string TGServerService.ChatProviders.IRCChatProvider.Connect ()
Connects the chat provider if it's enabled
Implements TGServerService.ChatProviders.IChatProvider.
Definition at line 218 of file IRCChatProvider.cs.
References TGServiceInterface.ChatSetupInfo.Enabled, TGServiceInterface.IRCSetupInfo.Nickname, TGServiceInterface.IRCSetupInfo.Port, and TGServiceInterface.IRCSetupInfo.URL.
         {
             if (Connected() || !IRCConfig.Enabled)
                 return null;
             lock (IRCLock)
             {
                 try
                 {
                     try
                     {
                         irc.Connect(IRCConfig.URL, IRCConfig.Port);
                     }
                     catch (Exception e)
                     {
                         return "IRC server unreachable: " + e.ToString();
                     }
                     try
                     {
                         irc.Login(IRCConfig.Nickname, IRCConfig.Nickname);
                     }
                     catch (Exception e)
                     {
                         return "Bot name is already taken: " + e.ToString();
                     }
                     Login();
                     JoinChannels();
                     new Thread(new ThreadStart(IRCListen)) { IsBackground = true }.Start();
                     return null;
                 }
                 catch (Exception e)
                 {
                     return e.ToString();
                 }
             }
         }
bool TGServerService.ChatProviders.IRCChatProvider.Connected ()
Checks if the chat provider is connected
Implements TGServerService.ChatProviders.IChatProvider.
Definition at line 296 of file IRCChatProvider.cs.
         {
             lock (IRCLock)
             {
                 return irc != null && irc.IsConnected;
             }
         }
void TGServerService.ChatProviders.IRCChatProvider.Disconnect ()
Disconnects the chat provider
Implements TGServerService.ChatProviders.IChatProvider.
Definition at line 277 of file IRCChatProvider.cs.
References TGServerService.Service.WriteError().
         {
             try
             {
                 lock (IRCLock)
                 {
                     if (irc.IsConnected)
                     {
                         irc.RfcQuit("Twas meant to be...");
                         irc.Disconnect();
                     }
                 }
             }
             catch (Exception e)
             {
                 Service.WriteError("IRC failed QnD: " + e.ToString(), EventID.ChatDisconnectFail);
             }
         }
void TGServerService.ChatProviders.IRCChatProvider.Dispose (bool disposing) private
Implements the IDisposable pattern. Calls Disconnect and sets irc to
Parameters
disposing if Dispose() was called manually, if it was from the finalizer
Definition at line 336 of file IRCChatProvider.cs.
         {
             if (!disposedValue)
             {
                 if (disposing)
                 {
                     // TODO: dispose managed state (managed objects).
                     Disconnect();
                     irc = null;
                 }
                 // TODO: free unmanaged resources (unmanaged objects) and override a finalizer below.
                 // TODO: set large fields to null.
                 disposedValue = true;
             }
         }
void TGServerService.ChatProviders.IRCChatProvider.Dispose ()
Implements the IDisposable pattern
Definition at line 364 of file IRCChatProvider.cs.
         {
             // Do not change this code. Put cleanup code in Dispose(bool disposing) above.
             Dispose(true);
             // TODO: uncomment the following line if the finalizer is overridden above.
             // GC.SuppressFinalize(this);
         }
void TGServerService.ChatProviders.IRCChatProvider.Irc_OnChannelMessage (object sender, IrcEventArgs e) private
Called when a channel the bot is in recieves a message
Parameters
sender The sender of the event (usually irc)
e The IrcEventArgs
Definition at line 165 of file IRCChatProvider.cs.
References TGServiceInterface.ChatSetupInfo.AdminChannels, and TGServerService.ChatProviders.OnChatMessage().
         {
             var formattedMessage = e.Data.Message.Trim();
             var splits = new List<string>(formattedMessage.Split(' '));
             var test = splits[0];
             if (test.Length > 1 && (test[test.Length - 1] == ':' || test[test.Length - 1] == ','))
                 test = test.Substring(0, test.Length - 1);
             if (test.ToLower() != irc.Nickname.ToLower())
                 return;
             splits.RemoveAt(0);
             formattedMessage = String.Join(" ", splits);
             OnChatMessage(this, e.Data.Nick, e.Data.Channel, formattedMessage, CheckAdmin(e.Data), IRCConfig.AdminChannels.Contains(e.Data.Channel.ToLower()));
         }
void TGServerService.ChatProviders.IRCChatProvider.Irc_OnQueryMessage (object sender, IrcEventArgs e) private
Called when the bot recieves a query message
Parameters
sender The sender of the event (usually irc)
e The IrcEventArgs
Definition at line 155 of file IRCChatProvider.cs.
References TGServerService.ChatProviders.OnChatMessage().
         {
             OnChatMessage(this, e.Data.Nick, e.Data.Nick + PrivateMessageMarker, e.Data.Message, CheckAdmin(e.Data), true);
         }
void TGServerService.ChatProviders.IRCChatProvider.IRCListen () private
Runs the irc listener in a safe loop
Definition at line 259 of file IRCChatProvider.cs.
         {
             while (irc != null && Connected())
                 try
                 {
                     irc.Listen();
                 }
                 catch { }
         }
void TGServerService.ChatProviders.IRCChatProvider.JoinChannels () private
Joins all channels specified in IRCConfig
Definition at line 185 of file IRCChatProvider.cs.
References TGServiceInterface.ChatSetupInfo.AdminChannels, TGServiceInterface.ChatSetupInfo.DevChannels, TGServiceInterface.ChatSetupInfo.GameChannels, and TGServiceInterface.ChatSetupInfo.WatchdogChannels.
         {
             var hs = new HashSet<string>(); //for unique inserts
             foreach (var I in IRCConfig.AdminChannels)
                 hs.Add(I);
             foreach (var I in IRCConfig.DevChannels)
                 hs.Add(I);
             foreach (var I in IRCConfig.GameChannels)
                 hs.Add(I);
             foreach (var I in IRCConfig.WatchdogChannels)
                 hs.Add(I);
             var ToPart = new List<string>();
             foreach (var I in irc.JoinedChannels)
                 if (!hs.Remove(I))
                     ToPart.Add(I);
             foreach (var I in ToPart)
                 irc.RfcPart(I);
             foreach (var I in hs)
                 irc.RfcJoin(I);
         }
void TGServerService.ChatProviders.IRCChatProvider.Login () private
Sends a login query to IRCSetupInfo.AuthTarget with message IRCSetupInfo.AuthMessage
Definition at line 209 of file IRCChatProvider.cs.
References TGServiceInterface.IRCSetupInfo.AuthMessage, and TGServiceInterface.IRCSetupInfo.AuthTarget.
         {
             lock (IRCLock)
             {
                 if (IRCConfig.AuthTarget != null)
                     irc.SendMessage(SendType.Message, IRCConfig.AuthTarget, IRCConfig.AuthMessage);
             }
         }
ChatSetupInfo TGServerService.ChatProviders.IRCChatProvider.ProviderInfo ()
Gets the info of the provider
Implements TGServerService.ChatProviders.IChatProvider.
Definition at line 36 of file IRCChatProvider.cs.
         {
             return IRCConfig;
         }
string TGServerService.ChatProviders.IRCChatProvider.Reconnect ()
Forces a reconnection of the chat provider if it's enabled
Implements TGServerService.ChatProviders.IChatProvider.
Definition at line 270 of file IRCChatProvider.cs.
         {
             Disconnect();
             return Connect();
         }
void TGServerService.ChatProviders.IRCChatProvider.SendMessage (string message, MessageType mt)
Broadcast a message to appropriate channels based on the message type
Implements TGServerService.ChatProviders.IChatProvider.
Definition at line 304 of file IRCChatProvider.cs.
References TGServiceInterface.ChatSetupInfo.AdminChannels, TGServiceInterface.ChatSetupInfo.DevChannels, TGServiceInterface.ChatSetupInfo.GameChannels, and TGServiceInterface.ChatSetupInfo.WatchdogChannels.
         {
             if (!Connected())
                 return;
             lock (IRCLock)
             {
                 string cids = "";
                 for (var I = 0; I < irc.JoinedChannels.Count; ++I)
                 {
                     var cid = irc.JoinedChannels[I];
                     bool SendToThisChannel = (mt.HasFlag(MessageType.AdminInfo) && IRCConfig.AdminChannels.Contains(cid))
                         || (mt.HasFlag(MessageType.DeveloperInfo) && IRCConfig.DevChannels.Contains(cid))
                         || (mt.HasFlag(MessageType.GameInfo) && IRCConfig.GameChannels.Contains(cid))
                         || (mt.HasFlag(MessageType.WatchdogInfo) && IRCConfig.WatchdogChannels.Contains(cid));
                     if (SendToThisChannel)
                         cids += I > 0 ? ',' + cid : cid;
                 }
                 irc.SendMessage(SendType.Message, cids, message);
             }
         }
string TGServerService.ChatProviders.IRCChatProvider.SendMessageDirect (string message, string channel)
Send a message to a channel
Implements TGServerService.ChatProviders.IChatProvider.
Definition at line 65 of file IRCChatProvider.cs.
References TGServerService.Service.WriteInfo().
         {
             try
             {
                 if (!Connected())
                     return "Disconnected.";
                 lock (IRCLock)
                 {
                     if (channel.Contains(PrivateMessageMarker))
                         channel = channel.Replace(PrivateMessageMarker, "");
                     irc.SendMessage(SendType.Message, channel, message);
                 }
                 Service.WriteInfo(String.Format("IRC Send ({0}): {1}", channel, message), EventID.ChatSend);
                 return null;
             }
             catch (Exception e)
             {
                 return e.ToString();
             }
         }
string TGServerService.ChatProviders.IRCChatProvider.SetProviderInfo (ChatSetupInfo info)
Sets info for the provider
Implements TGServerService.ChatProviders.IChatProvider.
Definition at line 87 of file IRCChatProvider.cs.
References TGServiceInterface.ChatSetupInfo.Enabled, TGServiceInterface.IRCSetupInfo.Nickname, TGServiceInterface.IRCSetupInfo.Port, and TGServiceInterface.IRCSetupInfo.URL.
         {
             var convertedInfo = (IRCSetupInfo)info;
             var serverChange = convertedInfo.URL != IRCConfig.URL || convertedInfo.Port != IRCConfig.Port;
             IRCConfig = convertedInfo;
             if (!IRCConfig.Enabled)
             {
                 Disconnect();
                 return null;
             }
             else if (serverChange || !Connected())
                 return Reconnect();
             if (IRCConfig.Nickname != irc.Nickname)
                 irc.RfcNick(convertedInfo.Nickname);
             Login();
             JoinChannels();
             return null;
         }
Member Data Documentation
bool TGServerService.ChatProviders.IRCChatProvider.disposedValue = false private
To detect redundant Dispose() calls
Definition at line 330 of file IRCChatProvider.cs.
IrcFeatures TGServerService.ChatProviders.IRCChatProvider.irc private
The irc client
Definition at line 21 of file IRCChatProvider.cs.
IRCSetupInfo TGServerService.ChatProviders.IRCChatProvider.IRCConfig private
The setup info for the provider
Definition at line 30 of file IRCChatProvider.cs.
object TGServerService.ChatProviders.IRCChatProvider.IRCLock = new object() private
Used for multithreading safety
Definition at line 25 of file IRCChatProvider.cs.
const string TGServerService.ChatProviders.IRCChatProvider.PrivateMessageMarker = "---PRIVATE-MSG---" private
Header used to mark that a channel is actually a query message
Definition at line 17 of file IRCChatProvider.cs.
Event Documentation
OnChatMessage TGServerService.ChatProviders.IRCChatProvider.OnChatMessage
Definition at line 33 of file IRCChatProvider.cs.
The documentation for this class was generated from the following file:
TGServerService/ChatProviders/IRCChatProvider.cs