tgstation-server: Tgstation.Server.Host.IO.Tests.TestSymlinkFactory Class Reference
Tgstation.Server.Host.IO.Tests.TestSymlinkFactory Class Reference
Public Member Functions
void SelectFactory ()
async Task TestFileWorks ()
async Task TestDirectoryWorks ()
async Task TestFailsProperly ()
Static Public Member Functions
static bool HasPermissionToMakeSymlinks ()
Private Attributes
ISymlinkFactory symlinkFactory
Detailed Description
Definition at line 11 of file TestSymlinkFactory.cs.
Member Function Documentation
HasPermissionToMakeSymlinks()
static bool Tgstation.Server.Host.IO.Tests.TestSymlinkFactory.HasPermissionToMakeSymlinks () static
Definition at line 24 of file TestSymlinkFactory.cs.
         {
             if (!RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
                 return true;
             var identity = WindowsIdentity.GetCurrent();
             var principal = new WindowsPrincipal(identity);
             return principal.IsInRole(WindowsBuiltInRole.Administrator);
         }
Referenced by Tgstation.Server.Host.IO.Tests.TestSymlinkFactory.TestDirectoryWorks(), and Tgstation.Server.Host.IO.Tests.TestSymlinkFactory.TestFileWorks().
SelectFactory()
void Tgstation.Server.Host.IO.Tests.TestSymlinkFactory.SelectFactory ()
Definition at line 16 of file TestSymlinkFactory.cs.
         {
             if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
                 symlinkFactory = new WindowsSymlinkFactory();
             else
                 symlinkFactory = new PosixSymlinkFactory();
         }
References Tgstation.Server.Host.IO.Tests.TestSymlinkFactory.symlinkFactory.
TestDirectoryWorks()
async Task Tgstation.Server.Host.IO.Tests.TestSymlinkFactory.TestDirectoryWorks ()
Definition at line 63 of file TestSymlinkFactory.cs.
         {
             if (!HasPermissionToMakeSymlinks())
                 Assert.Inconclusive("Current user does not have permission to create symlinks!");
             const string FileName = "TestFile.txt";
             const string Text = "Hello world";
             string f2 = null;
             var f1 = Path.GetTempFileName();
             File.Delete(f1);
             Directory.CreateDirectory(f1);
             try
             {
                 f2 = f1 + ".linked";
                 var p1 = Path.Combine(f1, FileName);
                 File.WriteAllText(p1, Text);
                 await Assert.ThrowsExceptionAsync<ArgumentNullException>(() => symlinkFactory.CreateSymbolicLink(null, null, default)).ConfigureAwait(false);
                 await Assert.ThrowsExceptionAsync<ArgumentNullException>(() => symlinkFactory.CreateSymbolicLink(f1, null, default)).ConfigureAwait(false);
                 await symlinkFactory.CreateSymbolicLink(f1, f2, default).ConfigureAwait(false);
                 var p2 = Path.Combine(f2, FileName);
                 Assert.IsTrue(File.Exists(p2));
                 var f2Contents = File.ReadAllText(p2);
                 Assert.AreEqual(Text, f2Contents);
                 File.Delete(p2);
                 Assert.IsFalse(File.Exists(p1));
             }
             finally
             {
                 Directory.Delete(f2, true);
                 Directory.Delete(f1, true);
             }
         }
References Tgstation.Server.Host.IO.ISymlinkFactory.CreateSymbolicLink(), Tgstation.Server.Host.IO.Tests.TestSymlinkFactory.HasPermissionToMakeSymlinks(), and Tgstation.Server.Host.IO.Tests.TestSymlinkFactory.symlinkFactory.
TestFailsProperly()
async Task Tgstation.Server.Host.IO.Tests.TestSymlinkFactory.TestFailsProperly ()
Definition at line 101 of file TestSymlinkFactory.cs.
         {
             const string BadPath = "/../../?>!@#$%^&*()O(UF+}P{{??>/////";
             try
             {
                 await symlinkFactory.CreateSymbolicLink(BadPath, BadPath, default).ConfigureAwait(false);
                 Assert.Fail("No exception thrown!");
             }
             catch { }
         }
References Tgstation.Server.Host.IO.ISymlinkFactory.CreateSymbolicLink(), and Tgstation.Server.Host.IO.Tests.TestSymlinkFactory.symlinkFactory.
TestFileWorks()
async Task Tgstation.Server.Host.IO.Tests.TestSymlinkFactory.TestFileWorks ()
Definition at line 34 of file TestSymlinkFactory.cs.
         {
             if (!HasPermissionToMakeSymlinks())
                 Assert.Inconclusive("Current user does not have permission to create symlinks!");
             const string Text = "Hello world";
             string f2 = null;
             var f1 = Path.GetTempFileName();
             try
             {
                 f2 = f1 + ".linked";
                 File.WriteAllText(f1, Text);
                 await Assert.ThrowsExceptionAsync<ArgumentNullException>(() => symlinkFactory.CreateSymbolicLink(null, null, default)).ConfigureAwait(false);
                 await Assert.ThrowsExceptionAsync<ArgumentNullException>(() => symlinkFactory.CreateSymbolicLink(f1, null, default)).ConfigureAwait(false);
                 await symlinkFactory.CreateSymbolicLink(f1, f2, default).ConfigureAwait(false);
                 Assert.IsTrue(File.Exists(f2));
                 var f2Contents = File.ReadAllText(f2);
                 Assert.AreEqual(Text, f2Contents);
             }
             finally
             {
                 File.Delete(f2);
                 File.Delete(f1);
             }
         }
References Tgstation.Server.Host.IO.ISymlinkFactory.CreateSymbolicLink(), Tgstation.Server.Host.IO.Tests.TestSymlinkFactory.HasPermissionToMakeSymlinks(), and Tgstation.Server.Host.IO.Tests.TestSymlinkFactory.symlinkFactory.
Member Data Documentation
symlinkFactory
ISymlinkFactory Tgstation.Server.Host.IO.Tests.TestSymlinkFactory.symlinkFactory private
Definition at line 13 of file TestSymlinkFactory.cs.
Referenced by Tgstation.Server.Host.IO.Tests.TestSymlinkFactory.SelectFactory(), Tgstation.Server.Host.IO.Tests.TestSymlinkFactory.TestDirectoryWorks(), Tgstation.Server.Host.IO.Tests.TestSymlinkFactory.TestFailsProperly(), and Tgstation.Server.Host.IO.Tests.TestSymlinkFactory.TestFileWorks().
The documentation for this class was generated from the following file:
tests/Tgstation.Server.Host.Tests/IO/TestSymlinkFactory.cs