tgstation-server: Tgstation.Server.Host.Jobs.JobsHubGroupMapper Class Reference
Tgstation.Server.Host.Jobs.JobsHubGroupMapper Class Reference
Handles mapping groups for the JobsHub.
Public Member Functions
JobsHubGroupMapper (IConnectionMappedHubContext< JobsHub, IJobsHub > hub, IDatabaseContextFactory databaseContextFactory, IJobsHubUpdater jobsHubUpdater, ILogger< JobsHubGroupMapper > logger)
Initializes a new instance of the JobsHubGroupMapper class.
ValueTask InstancePermissionSetCreated (InstancePermissionSet instancePermissionSet, CancellationToken cancellationToken)
Called when a given instancePermissionSet is successfully created.
Parameters
instancePermissionSet The InstancePermissionSet. InstancePermissionSet.PermissionSet must be populated.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
ValueTask UserDisabled (User user, CancellationToken cancellationToken)
Called when a given User is successfully disabled.
Parameters
user The User that was disabled.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
ValueTask InstancePermissionSetDeleted (PermissionSet permissionSet, CancellationToken cancellationToken)
Called when an InstancePermissionSet is successfully deleted.
Parameters
permissionSet The PermissionSet of the deleted InstancePermissionSet.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Task StartAsync (CancellationToken cancellationToken)
Task StopAsync (CancellationToken cancellationToken)
ValueTask InstancePermissionSetCreated (InstancePermissionSet instancePermissionSet, CancellationToken cancellationToken)
Called when a given instancePermissionSet is successfully created.
ValueTask InstancePermissionSetDeleted (PermissionSet permissionSet, CancellationToken cancellationToken)
Called when an InstancePermissionSet is successfully deleted.
ValueTask UserDisabled (User user, CancellationToken cancellationToken)
Called when a given User is successfully disabled.
Private Member Functions
async ValueTask MapConnectionGroups (IAuthenticationContext authenticationContext, Func< IEnumerable< string >, Task > mappingFunc, CancellationToken cancellationToken)
Implementation of IConnectionMappedHubContext<THub, THubMethods>.OnConnectionMapGroups.
ValueTask RefreshHubGroups (long permissionSetId, CancellationToken cancellationToken)
Refresh the hub Hub.Groups for clients associated with a given permissionSetId .
Private Attributes
readonly IConnectionMappedHubContext< JobsHub, IJobsHub > hub
The IHubContext for the JobsHub.
readonly IDatabaseContextFactory databaseContextFactory
The IDatabaseContextFactory for the JobService.
readonly IJobsHubUpdater jobsHubUpdater
The IJobsHubUpdater for the JobService.
readonly ILogger< JobsHubGroupMapper > logger
The ILogger for the JobService.
Detailed Description
Handles mapping groups for the JobsHub.
Definition at line 23 of file JobsHubGroupMapper.cs.
Constructor & Destructor Documentation
JobsHubGroupMapper()
Tgstation.Server.Host.Jobs.JobsHubGroupMapper.JobsHubGroupMapper (IConnectionMappedHubContext< JobsHub, IJobsHub > hub, IDatabaseContextFactory databaseContextFactory, IJobsHubUpdater jobsHubUpdater, ILogger< JobsHubGroupMapper > logger)
Initializes a new instance of the JobsHubGroupMapper class.
Parameters
hub The value of hub.
databaseContextFactory The value of databaseContextFactory.
jobsHubUpdater The value of jobsHubUpdater.
logger The value of logger.
Definition at line 52 of file JobsHubGroupMapper.cs.
        {
            this.hub = hub ?? throw new ArgumentNullException(nameof(hub));
            this.databaseContextFactory = databaseContextFactory ?? throw new ArgumentNullException(nameof(databaseContextFactory));
            this.jobsHubUpdater = jobsHubUpdater ?? throw new ArgumentNullException(nameof(jobsHubUpdater));
            this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
            hub.OnConnectionMapGroups += MapConnectionGroups;
        }
References Tgstation.Server.Host.Jobs.JobsHubGroupMapper.databaseContextFactory, Tgstation.Server.Host.Jobs.JobsHubGroupMapper.hub, Tgstation.Server.Host.Jobs.JobsHubGroupMapper.jobsHubUpdater, Tgstation.Server.Host.Jobs.JobsHubGroupMapper.logger, and Tgstation.Server.Host.Jobs.JobsHubGroupMapper.MapConnectionGroups().
Member Function Documentation
InstancePermissionSetCreated()
ValueTask Tgstation.Server.Host.Jobs.JobsHubGroupMapper.InstancePermissionSetCreated (InstancePermissionSet instancePermissionSet, CancellationToken cancellationToken)
Called when a given instancePermissionSet is successfully created.
Parameters
instancePermissionSet The InstancePermissionSet. InstancePermissionSet.PermissionSet must be populated.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Security.IPermissionsUpdateNotifyee.
Definition at line 67 of file JobsHubGroupMapper.cs.
        {
            ArgumentNullException.ThrowIfNull(instancePermissionSet);
            var permissionSetId = instancePermissionSet.PermissionSetId;
            logger.LogTrace("InstancePermissionSetCreated");
            return RefreshHubGroups(
                permissionSetId,
                cancellationToken);
        }
References Tgstation.Server.Host.Jobs.JobsHubGroupMapper.logger, Tgstation.Server.Api.Models.Internal.InstancePermissionSet.PermissionSetId, and Tgstation.Server.Host.Jobs.JobsHubGroupMapper.RefreshHubGroups().
InstancePermissionSetDeleted()
ValueTask Tgstation.Server.Host.Jobs.JobsHubGroupMapper.InstancePermissionSetDeleted (PermissionSet permissionSet, CancellationToken cancellationToken)
Called when an InstancePermissionSet is successfully deleted.
Parameters
permissionSet The PermissionSet of the deleted InstancePermissionSet.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Security.IPermissionsUpdateNotifyee.
Definition at line 91 of file JobsHubGroupMapper.cs.
        {
            ArgumentNullException.ThrowIfNull(permissionSet);
            logger.LogTrace("InstancePermissionSetDeleted");
            return RefreshHubGroups(
                permissionSet.Id ?? throw new InvalidOperationException("permissionSet?.Id was null!"),
                cancellationToken);
        }
References Tgstation.Server.Api.Models.PermissionSet.Id, Tgstation.Server.Host.Jobs.JobsHubGroupMapper.logger, and Tgstation.Server.Host.Jobs.JobsHubGroupMapper.RefreshHubGroups().
MapConnectionGroups()
async ValueTask Tgstation.Server.Host.Jobs.JobsHubGroupMapper.MapConnectionGroups (IAuthenticationContext authenticationContext, Func< IEnumerable< string >, Task > mappingFunc, CancellationToken cancellationToken) private
Implementation of IConnectionMappedHubContext<THub, THubMethods>.OnConnectionMapGroups.
Parameters
authenticationContext The IAuthenticationContext to map the groups for.
mappingFunc The Func<T, TResult> taking the mapped group names as an IEnumerable<T> of string resulting in a ValueTask to be awaited.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in an IEnumerable<T> of the JobsHub group names the user belongs in.
Definition at line 113 of file JobsHubGroupMapper.cs.
        {
            ArgumentNullException.ThrowIfNull(authenticationContext);
            var pid = authenticationContext.PermissionSet.Require(x => x.Id);
            logger.LogTrace(
                "MapConnectionGroups UID: {uid} PID: {pid}",
                authenticationContext.User.Require(x => x.Id),
                pid);
            List<long>? permedInstanceIds = null;
            await databaseContextFactory.UseContext(
                async databaseContext =>
                    permedInstanceIds = await databaseContext
                        .InstancePermissionSets
                        .AsQueryable()
                        .Where(ips => ips.PermissionSetId == pid)
                        .Select(ips => ips.InstanceId)
                        .ToListAsync(cancellationToken));
            await mappingFunc(
                permedInstanceIds!.Select(
                    JobsHub.HubGroupName));
            jobsHubUpdater.QueueActiveJobUpdates();
        }
References Tgstation.Server.Host.Jobs.JobsHubGroupMapper.databaseContextFactory, Tgstation.Server.Host.Jobs.JobsHub.HubGroupName(), Tgstation.Server.Host.Jobs.JobsHubGroupMapper.jobsHubUpdater, Tgstation.Server.Host.Jobs.JobsHubGroupMapper.logger, Tgstation.Server.Host.Security.IAuthenticationContext.PermissionSet, Tgstation.Server.Host.Jobs.IJobsHubUpdater.QueueActiveJobUpdates(), Tgstation.Server.Host.Database.IDatabaseContextFactory.UseContext(), and Tgstation.Server.Host.Security.IAuthenticationContext.User.
Referenced by Tgstation.Server.Host.Jobs.JobsHubGroupMapper.JobsHubGroupMapper().
RefreshHubGroups()
ValueTask Tgstation.Server.Host.Jobs.JobsHubGroupMapper.RefreshHubGroups (long permissionSetId, CancellationToken cancellationToken) private
Refresh the hub Hub.Groups for clients associated with a given permissionSetId .
Parameters
permissionSetId The Api.Models.EntityId.Id of the PermissionSet who's users need updating.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
References Tgstation.Server.Host.Jobs.JobsHubGroupMapper.hub, Tgstation.Server.Host.Jobs.JobsHub.HubGroupName(), and Tgstation.Server.Host.Jobs.JobsHubGroupMapper.logger.
Referenced by Tgstation.Server.Host.Jobs.JobsHubGroupMapper.InstancePermissionSetCreated(), and Tgstation.Server.Host.Jobs.JobsHubGroupMapper.InstancePermissionSetDeleted().
StartAsync()
Task Tgstation.Server.Host.Jobs.JobsHubGroupMapper.StartAsync (CancellationToken cancellationToken)
StopAsync()
Task Tgstation.Server.Host.Jobs.JobsHubGroupMapper.StopAsync (CancellationToken cancellationToken)
UserDisabled()
ValueTask Tgstation.Server.Host.Jobs.JobsHubGroupMapper.UserDisabled (User user, CancellationToken cancellationToken)
Called when a given User is successfully disabled.
Parameters
user The User that was disabled.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Security.IPermissionsUpdateNotifyee.
Definition at line 79 of file JobsHubGroupMapper.cs.
        {
            ArgumentNullException.ThrowIfNull(user);
            if (!user.Id.HasValue)
                throw new InvalidOperationException("user.Id was null!");
            logger.LogTrace("UserDisabled");
            hub.AbortUnauthedConnections(user);
            return ValueTask.CompletedTask;
        }
References Tgstation.Server.Host.Jobs.JobsHubGroupMapper.hub, Tgstation.Server.Api.Models.EntityId.Id, and Tgstation.Server.Host.Jobs.JobsHubGroupMapper.logger.
Member Data Documentation
databaseContextFactory
readonly IDatabaseContextFactory Tgstation.Server.Host.Jobs.JobsHubGroupMapper.databaseContextFactory private
The IDatabaseContextFactory for the JobService.
Definition at line 33 of file JobsHubGroupMapper.cs.
Referenced by Tgstation.Server.Host.Jobs.JobsHubGroupMapper.JobsHubGroupMapper(), and Tgstation.Server.Host.Jobs.JobsHubGroupMapper.MapConnectionGroups().
hub
readonly IConnectionMappedHubContext<JobsHub, IJobsHub> Tgstation.Server.Host.Jobs.JobsHubGroupMapper.hub private
The IHubContext for the JobsHub.
Definition at line 28 of file JobsHubGroupMapper.cs.
Referenced by Tgstation.Server.Host.Jobs.JobsHubGroupMapper.JobsHubGroupMapper(), Tgstation.Server.Host.Jobs.JobsHubGroupMapper.RefreshHubGroups(), and Tgstation.Server.Host.Jobs.JobsHubGroupMapper.UserDisabled().
jobsHubUpdater
readonly IJobsHubUpdater Tgstation.Server.Host.Jobs.JobsHubGroupMapper.jobsHubUpdater private
The IJobsHubUpdater for the JobService.
Definition at line 38 of file JobsHubGroupMapper.cs.
Referenced by Tgstation.Server.Host.Jobs.JobsHubGroupMapper.JobsHubGroupMapper(), and Tgstation.Server.Host.Jobs.JobsHubGroupMapper.MapConnectionGroups().
logger
readonly ILogger<JobsHubGroupMapper> Tgstation.Server.Host.Jobs.JobsHubGroupMapper.logger private
The ILogger for the JobService.
Definition at line 43 of file JobsHubGroupMapper.cs.
Referenced by Tgstation.Server.Host.Jobs.JobsHubGroupMapper.InstancePermissionSetCreated(), Tgstation.Server.Host.Jobs.JobsHubGroupMapper.InstancePermissionSetDeleted(), Tgstation.Server.Host.Jobs.JobsHubGroupMapper.JobsHubGroupMapper(), Tgstation.Server.Host.Jobs.JobsHubGroupMapper.MapConnectionGroups(), Tgstation.Server.Host.Jobs.JobsHubGroupMapper.RefreshHubGroups(), and Tgstation.Server.Host.Jobs.JobsHubGroupMapper.UserDisabled().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Jobs/JobsHubGroupMapper.cs