tgstation-server: TGS.Interface.Instance Class Reference
TGS.Interface.Instance Class Reference
Public Member Functions
Instance (Client _serverInterface, InstanceMetadata _metadata)
Construct an Instance
string ServerDirectory ()
Return the directory of the server on the host machine
string Version ()
Retrieve's the service's version
override string ToString ()
Get a string representation of the Instance
Public Attributes
ITGAdministration Administration => UserIsAdministrator ? serverInterface.GetComponent<ITGAdministration>(metadata.Name) : null
ITGByond Byond => serverInterface.GetComponent<ITGByond>(metadata.Name)
ITGChat Chat => serverInterface.GetComponent<ITGChat>(metadata.Name)
ITGCompiler Compiler => serverInterface.GetComponent<ITGCompiler>(metadata.Name)
ITGConfig Config => serverInterface.GetComponent<ITGConfig>(metadata.Name)
ITGDreamDaemon DreamDaemon => serverInterface.GetComponent<ITGDreamDaemon>(metadata.Name)
ITGInterop Interop => serverInterface.GetComponent<ITGInterop>(metadata.Name)
ITGRepository Repository => serverInterface.GetComponent<ITGRepository>(metadata.Name)
Properties
InstanceMetadata Metadata [get]
bool UserIsAdministrator [get]
Whether or not the current user is known to be an administrator of the IInstance
Properties inherited from TGS.Interface.IInstance
InstanceMetadata Metadata [get]
Get the InstanceMetadata for the IInstance
ITGAdministration Administration [get]
The ITGAdministration component. Will be if the connected user is not an administrator of the IInstance
ITGByond Byond [get]
The ITGByond component
ITGChat Chat [get]
The ITGChat component
ITGCompiler Compiler [get]
The ITGCompiler component
ITGConfig Config [get]
The ITGConfig component
ITGDreamDaemon DreamDaemon [get]
The ITGDreamDaemon component
ITGInterop Interop [get]
The ITGInterop component
ITGRepository Repository [get]
The ITGRepository component
Private Attributes
readonly Client serverInterface
The backing Client
InstanceMetadata metadata
The name of the IInstance
bool isAdministrator
Backing field for UserIsAdministrator
Detailed Description
Definition at line 8 of file Instance.cs.
Constructor & Destructor Documentation
TGS.Interface.Instance.Instance (Client _serverInterface, InstanceMetadata _metadata)
Construct an Instance
Parameters
_serverInterface The Client to use
_metadata The InstanceMetadata for the IInstance
Definition at line 65 of file Instance.cs.
References TGS.Interface.InstanceMetadata.Enabled, and TGS.Interface.InstanceMetadata.Name.
         {
             serverInterface = _serverInterface;
             metadata = _metadata;
             if (metadata.Enabled)
                 //run a connectivity check
                 serverInterface.GetComponent<ITGConnectivity>(metadata.Name).VerifyConnection();
         }
Member Function Documentation
string TGS.Interface.Instance.ServerDirectory ()
Return the directory of the server on the host machine
Implements TGS.Interface.Components.ITGInstance.
Definition at line 99 of file Instance.cs.
References TGS.Interface.InstanceMetadata.Name.
Referenced by TGS.ControlPanel.ControlPanel.LoadServerPage(), and TGS.CommandLine.ConfigServerDirectoryCommand.Run().
         {
             return serverInterface.GetComponent<ITGInstance>(metadata.Name).ServerDirectory();
         }
override string TGS.Interface.Instance.ToString ()
Get a string representation of the Instance
Returns
A string representation of the Instance
Definition at line 114 of file Instance.cs.
References TGS.Interface.InstanceMetadata.Enabled, TGS.Interface.InstanceMetadata.LoggingID, TGS.Interface.InstanceMetadata.Name, and TGS.Interface.InstanceMetadata.Path.
         {
             return String.Format("{0}: {1} - {2} - {3}", metadata.LoggingID, metadata.Name, metadata.Path, metadata.Enabled ? "ONLINE" : "OFFLINE");
         }
string TGS.Interface.Instance.Version ()
Retrieve's the service's version
Implements TGS.Interface.Components.ITGInstance.
Definition at line 105 of file Instance.cs.
References TGS.Interface.InstanceMetadata.Name.
         {
             return serverInterface.GetComponent<ITGInstance>(metadata.Name).Version();
         }
Member Data Documentation
ITGAdministration TGS.Interface.Instance.Administration => UserIsAdministrator ? serverInterface.GetComponent<ITGAdministration>(metadata.Name) : null
Definition at line 75 of file Instance.cs.
Referenced by TGS.ControlPanel.ControlPanel.InitStaticPage(), TGS.ControlPanel.ControlPanel.RecreateStaticButton_Click(), TGS.CommandLine.AdminRecreateStaticCommand.Run(), TGS.CommandLine.AdminViewGroupCommand.Run(), TGS.CommandLine.AdminSetGroupCommand.Run(), and TGS.CommandLine.AdminClearGroupCommand.Run().
ITGByond TGS.Interface.Instance.Byond => serverInterface.GetComponent<ITGByond>(metadata.Name)
Definition at line 78 of file Instance.cs.
Referenced by TGS.ControlPanel.ControlPanel.InitBYONDPage(), TGS.CommandLine.BYONDVersionCommand.Run(), TGS.CommandLine.DMCompileCommand.Run(), TGS.CommandLine.BYONDStatusCommand.Run(), TGS.CommandLine.BYONDUpdateCommand.Run(), TGS.ControlPanel.ControlPanel.UpdateButton_Click(), and TGS.ControlPanel.ControlPanel.UpdateBYONDButtons().
ITGChat TGS.Interface.Instance.Chat => serverInterface.GetComponent<ITGChat>(metadata.Name)
Definition at line 81 of file Instance.cs.
Referenced by TGS.ControlPanel.ControlPanel.ChatApplyButton_Click(), TGS.ControlPanel.ControlPanel.ChatReconnectButton_Click(), TGS.ControlPanel.ControlPanel.LoadChatPage(), TGS.CommandLine.IRCNickCommand.Run(), TGS.CommandLine.ChatJoinCommand.Run(), TGS.CommandLine.ChatPartCommand.Run(), TGS.CommandLine.ChatListAdminsCommand.Run(), TGS.CommandLine.ChatReconnectCommand.Run(), TGS.CommandLine.ChatAddminCommand.Run(), TGS.CommandLine.IRCAuthModeCommand.Run(), TGS.CommandLine.DiscordAuthModeCommand.Run(), TGS.CommandLine.IRCAuthLevelCommand.Run(), TGS.CommandLine.ChatDeadminCommand.Run(), TGS.CommandLine.IRCAuthCommand.Run(), TGS.CommandLine.IRCDisableAuthCommand.Run(), TGS.CommandLine.ChatStatusCommand.Run(), TGS.CommandLine.ChatEnableCommand.Run(), TGS.CommandLine.ChatDisableCommand.Run(), TGS.CommandLine.IRCServerCommand.Run(), TGS.CommandLine.DiscordSetTokenCommand.Run(), and TGS.ControlPanel.ControlPanel.SetAdminsAreSpecial().
ITGCompiler TGS.Interface.Instance.Compiler => serverInterface.GetComponent<ITGCompiler>(metadata.Name)
Definition at line 84 of file Instance.cs.
Referenced by TGS.ControlPanel.ControlPanel.CompileButton_Click(), TGS.ControlPanel.ControlPanel.CompileCancelButton_Click(), TGS.ControlPanel.ControlPanel.InitializeButton_Click(), TGS.ControlPanel.ControlPanel.LoadServerPage(), TGS.ControlPanel.ControlPanel.RemoveAllTestMergesButton_Click(), TGS.CommandLine.DMCompileCommand.Run(), TGS.CommandLine.UpdateCommand.Run(), TGS.CommandLine.DMStatusCommand.Run(), TGS.CommandLine.DMSetProjectNameCommand.Run(), TGS.CommandLine.TestmergeCommand.Run(), TGS.CommandLine.DMInitializeCommand.Run(), TGS.CommandLine.DMCancelCommand.Run(), TGS.CommandLine.DMStatusCommand.ShowError(), TGS.ControlPanel.ControlPanel.UpdateProjectName(), and TGS.ControlPanel.ControlPanel.UpdateServer().
ITGConfig TGS.Interface.Instance.Config => serverInterface.GetComponent<ITGConfig>(metadata.Name)
Definition at line 87 of file Instance.cs.
Referenced by TGS.ControlPanel.ControlPanel.BuildFileList(), TGS.ControlPanel.ControlPanel.LoadServerPage(), TGS.CommandLine.ConfigDeleteCommand.Run(), TGS.CommandLine.ConfigListCommand.Run(), TGS.CommandLine.ConfigDownloadCommand.Run(), TGS.CommandLine.ConfigUploadCommand.Run(), TGS.ControlPanel.ControlPanel.StaticFileCreateButton_Click(), TGS.ControlPanel.ControlPanel.StaticFileDeleteButton_Click(), TGS.ControlPanel.ControlPanel.StaticFileDownloadButton_Click(), TGS.ControlPanel.ControlPanel.StaticFileSaveButton_Click(), TGS.ControlPanel.ControlPanel.StaticFileUploadButton_Click(), and TGS.ControlPanel.ControlPanel.UpdateEditText().
ITGDreamDaemon TGS.Interface.Instance.DreamDaemon => serverInterface.GetComponent<ITGDreamDaemon>(metadata.Name)
Definition at line 90 of file Instance.cs.
Referenced by TGS.ControlPanel.ControlPanel.AutostartCheckbox_CheckedChanged(), TGS.ControlPanel.ControlPanel.LoadServerPage(), TGS.ControlPanel.ControlPanel.PortSelector_ValueChanged(), TGS.CommandLine.DDWorldAnnounceCommand.Run(), TGS.CommandLine.DDStartCommand.Run(), TGS.CommandLine.DDStopCommand.Run(), TGS.CommandLine.DDRestartCommand.Run(), TGS.CommandLine.DDStatusCommand.Run(), TGS.CommandLine.DDAutostartCommand.Run(), TGS.CommandLine.DDWebclientCommand.Run(), TGS.CommandLine.DDPortCommand.Run(), TGS.CommandLine.DDSecurityCommand.Run(), TGS.ControlPanel.ControlPanel.SecuritySelector_SelectedIndexChanged(), TGS.ControlPanel.ControlPanel.ServerGRestartButton_Click(), TGS.ControlPanel.ControlPanel.ServerGStopButton_Checked(), TGS.ControlPanel.ControlPanel.ServerRestartButton_Click(), TGS.ControlPanel.ControlPanel.ServerStartBGW_DoWork(), TGS.ControlPanel.ControlPanel.ServerStopButton_Click(), TGS.ControlPanel.ControlPanel.WebclientCheckBox_CheckedChanged(), and TGS.ControlPanel.ControlPanel.WorldAnnounceButton_Click().
ITGInterop TGS.Interface.Instance.Interop => serverInterface.GetComponent<ITGInterop>(metadata.Name)
Definition at line 93 of file Instance.cs.
bool TGS.Interface.Instance.isAdministrator private
Backing field for UserIsAdministrator
Definition at line 58 of file Instance.cs.
InstanceMetadata TGS.Interface.Instance.metadata private
The name of the IInstance
Definition at line 54 of file Instance.cs.
ITGRepository TGS.Interface.Instance.Repository => serverInterface.GetComponent<ITGRepository>(metadata.Name)
Definition at line 96 of file Instance.cs.
Referenced by TGS.ControlPanel.ControlPanel.AutoUpdateCheckbox_CheckedChanged(), TGS.ControlPanel.ControlPanel.AutoUpdateInterval_ValueChanged(), TGS.ControlPanel.ControlPanel.LoadServerPage(), TGS.ControlPanel.ControlPanel.PopulateRepoFields(), TGS.ControlPanel.ControlPanel.RemoveAllTestMergesButton_Click(), TGS.ControlPanel.ControlPanel.RepoApplyButton_Click(), TGS.ControlPanel.ControlPanel.RepoBGW_DoWork(), TGS.ControlPanel.ControlPanel.RepoBusyCheck(), TGS.CommandLine.RepoSetPushTestmergeCommitsCommand.Run(), TGS.CommandLine.AutoUpdateCommand.Run(), TGS.CommandLine.SetAutoUpdateCommand.Run(), TGS.CommandLine.RepoUpdateJsonCommand.Run(), TGS.CommandLine.RepoSetupCommand.Run(), TGS.CommandLine.UpdateCommand.Run(), TGS.CommandLine.RepoStatusCommand.Run(), TGS.CommandLine.TestmergeCommand.Run(), TGS.CommandLine.RepoResetCommand.Run(), TGS.CommandLine.RepoUpdateCommand.Run(), TGS.CommandLine.RepoGenChangelogCommand.Run(), TGS.CommandLine.RepoPushChangelogCommand.Run(), TGS.CommandLine.RepoSetEmailCommand.Run(), TGS.CommandLine.RepoSetNameCommand.Run(), TGS.CommandLine.RepoMergePRCommand.Run(), TGS.CommandLine.RepoListPRsCommand.Run(), TGS.CommandLine.RepoListBackupsCommand.Run(), TGS.CommandLine.RepoCheckoutCommand.Run(), TGS.ControlPanel.ControlPanel.TGSJsonUpdate_Click(), and TGS.ControlPanel.ControlPanel.UpdateServer().
readonly Client TGS.Interface.Instance.serverInterface private
The backing Client
Definition at line 50 of file Instance.cs.
Property Documentation
InstanceMetadata TGS.Interface.Instance.Metadata get
Definition at line 12 of file Instance.cs.
bool TGS.Interface.Instance.UserIsAdministrator get private
Whether or not the current user is known to be an administrator of the IInstance
Definition at line 26 of file Instance.cs.
The documentation for this class was generated from the following file:
TGS.Interface/Instance.cs