tgstation-server: TGS.Server.InstanceConfig Class Reference
TGS.Server.InstanceConfig Class Reference
Public Member Functions
InstanceConfig (string path)
Construct a InstanceConfig for a Instance at path
void Save ()
Saves the IInstanceConfig to it's Instance Directory
Static Public Member Functions
static IInstanceConfig Load (string path)
Loads and migrates an IInstanceConfig from a Instance at path
Public Attributes
const string JSONFilename = "Instance.json"
The name the file is saved as in the Directory
Protected Attributes
const ulong CurrentVersion = 1
The current version of the config
Properties
string Directory [get, private set]
ulong Version [get, protected set]
string Name = CurrentVersion [get, set]
bool Enabled = "TG Station Server" [get, set]
string ProjectName = true [get, set]
ushort Port = "tgstation" [get, set]
DreamDaemonSecurity Security = 1337 [get, set]
bool Autostart = DreamDaemonSecurity.Trusted [get, set]
bool Webclient = false [get, set]
string CommitterName = false [get, set]
string CommitterEmail = "tgstation-server" [get, set]
string ChatProviderData = "tgstation-server@tgstation13.org" [get, set]
string ChatProviderEntropy = Instance.UninitializedString [get, set]
bool ReattachRequired [get, set]
int ReattachProcessID = false [get, set]
ushort ReattachPort [get, set]
string ReattachCommsKey [get, set]
string ReattachAPIVersion [get, set]
string AuthorizedUserGroupSID [get, set]
ulong AutoUpdateInterval = null [get, set]
bool PushTestmergeCommits = 0 [get, set]
int ServerStartupTimeout = false [get, set]
Properties inherited from TGS.Server.IInstanceConfig
string Directory [get]
The Instance directory this IInstanceConfig is for
ulong Version [get]
Actual version of the IInstanceConfig. Migrated up via DeprecatedInstanceConfig
string Name [get, set]
The name of the Instance
bool Enabled [get, set]
If the Instance is active
string ProjectName [get, set]
The name of the .dme/.dmb the Instance uses
ushort Port [get, set]
The port the Instance runs on
DreamDaemonSecurity Security [get, set]
The DreamDaemonSecurity level for the Instance
bool Autostart [get, set]
Whether or not the Instance should immediately start DreamDaemon when activated
bool Webclient [get, set]
Whether or not DreamDaemon allows connections from webclients
string CommitterName [get, set]
Author and committer name for synchronize commits
string CommitterEmail [get, set]
Author and committer e-mail for synchronize commits
string ChatProviderData [get, set]
Encrypted serialized ChatSetupInfos
string ChatProviderEntropy [get, set]
Entropy for ChatProviderData
bool ReattachRequired [get, set]
If the Instance should reattach to a running DreamDaemon System.Diagnostics.Process
int ReattachProcessID [get, set]
The System.Diagnostics.Process.Id of the runnning DreamDaemon System.Diagnostics.Process
ushort ReattachPort [get, set]
The port the runnning DreamDaemon System.Diagnostics.Process was launched on
string ReattachCommsKey [get, set]
The serviceCommsKey the runnning DreamDaemon System.Diagnostics.Process was launched on
string ReattachAPIVersion [get, set]
The API version of the runnning DreamDaemon System.Diagnostics.Process
string AuthorizedUserGroupSID [get, set]
The user group allowed to use the Instance
ulong AutoUpdateInterval [get, set]
The auto update interval for the Instance
bool PushTestmergeCommits [get, set]
Whether or not testmerge commits are published to a temporary remote branch
int ServerStartupTimeout [get, set]
Time in seconds before DD is considered dead in the water
Detailed Description
Definition at line 128 of file InstanceConfig.cs.
Constructor & Destructor Documentation
TGS.Server.InstanceConfig.InstanceConfig (string path)
Construct a InstanceConfig for a Instance at path
Parameters
path The path to the Instance
Definition at line 213 of file InstanceConfig.cs.
         {
             Directory = path;
         }
Member Function Documentation
static IInstanceConfig TGS.Server.InstanceConfig.Load (string path) static
Loads and migrates an IInstanceConfig from a Instance at path
Parameters
path The path to the Instance directory
Returns
The migrated IInstanceConfig
Definition at line 231 of file InstanceConfig.cs.
References TGS.Server.InstanceConfig.Directory.
Referenced by TGS.Installer.UI.Main.AttemptMigrationOfNetSettings(), TGS.Server.Server.GetInstanceConfigs(), and TGS.Server.Server.ImportInstance().
         {
             var configtext = File.ReadAllText(Path.Combine(path, JSONFilename));
             var res = JsonConvert.DeserializeObject<DeprecatedInstanceConfig>(configtext);
             res.Directory = path;
             res.MigrateToCurrentVersion();
             return res;
         }
void TGS.Server.InstanceConfig.Save ()
Saves the IInstanceConfig to it's Instance Directory
Implements TGS.Server.IInstanceConfig.
Definition at line 219 of file InstanceConfig.cs.
Referenced by TGS.Installer.UI.Main.AttemptMigrationOfNetSettings(), and TGS.Installer.UI.Main.HandleNoConfigMigration().
         {
             var data = JsonConvert.SerializeObject(this, Formatting.Indented);
             var path = Path.Combine(Directory, JSONFilename);
             File.WriteAllText(path, data);
         }
Member Data Documentation
const ulong TGS.Server.InstanceConfig.CurrentVersion = 1 protected
The current version of the config
Definition at line 140 of file InstanceConfig.cs.
const string TGS.Server.InstanceConfig.JSONFilename = "Instance.json"
The name the file is saved as in the Directory
Definition at line 134 of file InstanceConfig.cs.
Property Documentation
string TGS.Server.InstanceConfig.AuthorizedUserGroupSID get set
Definition at line 198 of file InstanceConfig.cs.
bool TGS.Server.InstanceConfig.Autostart = DreamDaemonSecurity.Trusted get set
Definition at line 165 of file InstanceConfig.cs.
ulong TGS.Server.InstanceConfig.AutoUpdateInterval = null get set
Definition at line 201 of file InstanceConfig.cs.
string TGS.Server.InstanceConfig.ChatProviderData = "tgstation-server@tgstation13.org" get set
Definition at line 177 of file InstanceConfig.cs.
string TGS.Server.InstanceConfig.ChatProviderEntropy = Instance.UninitializedString get set
Definition at line 180 of file InstanceConfig.cs.
string TGS.Server.InstanceConfig.CommitterEmail = "tgstation-server" get set
Definition at line 174 of file InstanceConfig.cs.
string TGS.Server.InstanceConfig.CommitterName = false get set
Definition at line 171 of file InstanceConfig.cs.
string TGS.Server.InstanceConfig.Directory get private set
Definition at line 144 of file InstanceConfig.cs.
Referenced by TGS.Server.InstanceConfig.Load().
bool TGS.Server.InstanceConfig.Enabled = "TG Station Server" get set
Definition at line 153 of file InstanceConfig.cs.
string TGS.Server.InstanceConfig.Name = CurrentVersion get set
Definition at line 150 of file InstanceConfig.cs.
ushort TGS.Server.InstanceConfig.Port = "tgstation" get set
Definition at line 159 of file InstanceConfig.cs.
string TGS.Server.InstanceConfig.ProjectName = true get set
Definition at line 156 of file InstanceConfig.cs.
bool TGS.Server.InstanceConfig.PushTestmergeCommits = 0 get set
Definition at line 204 of file InstanceConfig.cs.
string TGS.Server.InstanceConfig.ReattachAPIVersion get set
Definition at line 195 of file InstanceConfig.cs.
string TGS.Server.InstanceConfig.ReattachCommsKey get set
Definition at line 192 of file InstanceConfig.cs.
ushort TGS.Server.InstanceConfig.ReattachPort get set
Definition at line 189 of file InstanceConfig.cs.
int TGS.Server.InstanceConfig.ReattachProcessID = false get set
Definition at line 186 of file InstanceConfig.cs.
bool TGS.Server.InstanceConfig.ReattachRequired get set
Definition at line 183 of file InstanceConfig.cs.
DreamDaemonSecurity TGS.Server.InstanceConfig.Security = 1337 get set
Definition at line 162 of file InstanceConfig.cs.
int TGS.Server.InstanceConfig.ServerStartupTimeout = false get set
Definition at line 207 of file InstanceConfig.cs.
ulong TGS.Server.InstanceConfig.Version get protected set
Definition at line 147 of file InstanceConfig.cs.
bool TGS.Server.InstanceConfig.Webclient = false get set
Definition at line 168 of file InstanceConfig.cs.
The documentation for this class was generated from the following file:
TGS.Server/InstanceConfig.cs