tgstation-server: Tgstation.Server.Host.ServerFactory Class Reference
Tgstation.Server.Host.ServerFactory Class Reference
Implementation of IServerFactory.
Public Member Functions
async Task< IServer > CreateServer (string[] args, string updatePath, CancellationToken cancellationToken)
Create a IServer.
Parameters
args The arguments for the IServer.
updatePath The directory in which to install server updates.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in a new IServer if it should be run, null otherwise.
Task< IServer > CreateServer (string[] args, string updatePath, CancellationToken cancellationToken)
Create a IServer.
Properties
IIOManager IOManager [get]
The IIOManager for the IServerFactory.
Properties inherited from Tgstation.Server.Host.IServerFactory
IIOManager IOManager [get]
The IIOManager for the IServerFactory.
Private Attributes
readonly IAssemblyInformationProvider assemblyInformationProvider
The IAssemblyInformationProvider for the ServerFactory.
Detailed Description
Implementation of IServerFactory.
Definition at line 23 of file ServerFactory.cs.
Member Function Documentation
CreateServer()
async Task< IServer > Tgstation.Server.Host.ServerFactory.CreateServer (string[] args, string updatePath, CancellationToken cancellationToken)
Create a IServer.
Parameters
args The arguments for the IServer.
updatePath The directory in which to install server updates.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in a new IServer if it should be run, null otherwise.
Implements Tgstation.Server.Host.IServerFactory.
Definition at line 47 of file ServerFactory.cs.
        {
            if (args == null)
                throw new ArgumentNullException(nameof(args));
            var basePath = IOManager.ResolvePath();
            IHostBuilder CreateDefaultBuilder() => Microsoft.Extensions.Hosting.Host.CreateDefaultBuilder(args)
                .ConfigureAppConfiguration((context, builder) =>
                {
                    builder.SetBasePath(basePath);
                    builder.AddYamlFile("appsettings.yml", optional: true, reloadOnChange: true)
                        .AddYamlFile($"appsettings.{context.HostingEnvironment.EnvironmentName}.yml", optional: true, reloadOnChange: true);
                    // reorganize the builder so our yaml configs don't override the env/cmdline configs
                    // values obtained via debugger
                    var environmentJsonConfig = builder.Sources[2];
                    var envConfig = builder.Sources[3];
                    // CURSED
                    // https://github.com/dotnet/runtime/blob/30dc7e7aedb7aab085c7d9702afeae5bc5a43133/src/libraries/Microsoft.Extensions.Hosting/src/HostingHostBuilderExtensions.cs#L246-L249
                    IConfigurationSource cmdLineConfig, baseYmlConfig, environmentYmlConfig;
                    if (args.Length == 0)
                    {
                        cmdLineConfig = null;
                        baseYmlConfig = builder.Sources[4];
                        environmentYmlConfig = builder.Sources[5];
                    }
                    else
                    {
                        cmdLineConfig = builder.Sources[4];
                        baseYmlConfig = builder.Sources[5];
                        environmentYmlConfig = builder.Sources[6];
                    }
                    builder.Sources[2] = baseYmlConfig;
                    builder.Sources[3] = environmentJsonConfig;
                    builder.Sources[4] = environmentYmlConfig;
                    builder.Sources[5] = envConfig;
                    if (cmdLineConfig != null)
                    {
                        builder.Sources[6] = cmdLineConfig;
                    }
                });
            var setupWizardHostBuilder = CreateDefaultBuilder()
                .UseSetupApplication();
            IPostSetupServices<ServerFactory> postSetupServices;
            using (var setupHost = setupWizardHostBuilder.Build())
            {
                postSetupServices = setupHost.Services.GetRequiredService<IPostSetupServices<ServerFactory>>();
                await setupHost.RunAsync(cancellationToken);
                if (postSetupServices.GeneralConfiguration.SetupWizardMode == SetupWizardMode.Only)
                {
                    postSetupServices.Logger.LogInformation("Shutting down due to only running setup wizard.");
                    return null;
                }
            }
            var hostBuilder = CreateDefaultBuilder()
                .ConfigureWebHost(webHostBuilder =>
                    webHostBuilder
                        .UseKestrel(kestrelOptions =>
{
                            var serverPortProvider = kestrelOptions.ApplicationServices.GetRequiredService<IServerPortProvider>();
                            kestrelOptions.ListenAnyIP(
                                serverPortProvider.HttpApiPort,
                                listenOptions => listenOptions.Protocols = HttpProtocols.Http1AndHttp2);
                        })
                        .UseIIS()
                        .UseIISIntegration()
                        .UseApplication(postSetupServices)
                        .SuppressStatusMessages(true)
                        .UseShutdownTimeout(TimeSpan.FromMinutes(postSetupServices.GeneralConfiguration.RestartTimeoutMinutes)));
            if (updatePath != null)
                hostBuilder.UseContentRoot(
                    IOManager.ResolvePath(
                        IOManager.GetDirectoryName(assemblyInformationProvider.Path)));
            return new Server(hostBuilder, updatePath);
        }
References Tgstation.Server.Host.ServerFactory.assemblyInformationProvider, Tgstation.Server.Host.Setup.IPostSetupServices< TLoggerType >.GeneralConfiguration, Tgstation.Server.Host.IO.IIOManager.GetDirectoryName(), Tgstation.Server.Host.ServerFactory.IOManager, Tgstation.Server.Host.Setup.IPostSetupServices< TLoggerType >.Logger, Tgstation.Server.Host.System.IAssemblyInformationProvider.Path, and Tgstation.Server.Host.IO.IIOManager.ResolvePath().
Referenced by Tgstation.Server.Host.Program.Main().
Member Data Documentation
assemblyInformationProvider
readonly IAssemblyInformationProvider Tgstation.Server.Host.ServerFactory.assemblyInformationProvider private
The IAssemblyInformationProvider for the ServerFactory.
Definition at line 28 of file ServerFactory.cs.
Referenced by Tgstation.Server.Host.ServerFactory.CreateServer().
Property Documentation
IOManager
IIOManager Tgstation.Server.Host.ServerFactory.IOManager get
The IIOManager for the IServerFactory.
Implements Tgstation.Server.Host.IServerFactory.
Definition at line 31 of file ServerFactory.cs.
{ get; }
Referenced by Tgstation.Server.Host.ServerFactory.CreateServer(), and Tgstation.Server.Host.Program.Main().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/ServerFactory.cs