tgstation-server: Tgstation.Server.Host.Models.DatabaseSeeder Class Reference
Tgstation.Server.Host.Models.DatabaseSeeder Class Reference
Public Member Functions
DatabaseSeeder (ICryptographySuite cryptographySuite)
Construct a DatabaseSeeder
async Task SeedDatabase (IDatabaseContext databaseContext, CancellationToken cancellationToken)
Initially seed a given databaseContext
async Task ResetAdminPassword (IDatabaseContext databaseContext, CancellationToken cancellationToken)
Changes the admin password in IDatabaseContext back to it's default and enables the account
Private Member Functions
void SeedAdminUser (IDatabaseContext databaseContext)
Add a default admin User to a given databaseContext
Private Attributes
readonly ICryptographySuite cryptographySuite
The ICryptographySuite for the DatabaseContext<TParentContext>
Detailed Description
Definition at line 12 of file DatabaseSeeder.cs.
Constructor & Destructor Documentation
DatabaseSeeder()
Tgstation.Server.Host.Models.DatabaseSeeder.DatabaseSeeder (ICryptographySuite cryptographySuite)
Construct a DatabaseSeeder
Parameters
cryptographySuite The value of cryptographySuite
Member Function Documentation
ResetAdminPassword()
async Task Tgstation.Server.Host.Models.DatabaseSeeder.ResetAdminPassword (IDatabaseContext databaseContext, CancellationToken cancellationToken)
Changes the admin password in IDatabaseContext back to it's default and enables the account
Implements Tgstation.Server.Host.Models.IDatabaseSeeder.
Definition at line 52 of file DatabaseSeeder.cs.
         {
             var admin = await databaseContext.Users.Where(x => x.CanonicalName == Api.Models.User.AdminName.ToUpperInvariant()).FirstOrDefaultAsync(cancellationToken).ConfigureAwait(false);
             if (admin == default)
                 SeedAdminUser(databaseContext);
             else
             {
                 admin.Enabled = true;
                 cryptographySuite.SetUserPassword(admin, Api.Models.User.DefaultAdminPassword, false);
             }
             await databaseContext.Save(cancellationToken).ConfigureAwait(false);
         }
References Tgstation.Server.Host.Models.DatabaseSeeder.cryptographySuite, Tgstation.Server.Host.Models.IDatabaseContext.Save(), Tgstation.Server.Host.Models.DatabaseSeeder.SeedAdminUser(), Tgstation.Server.Host.Security.ICryptographySuite.SetUserPassword(), and Tgstation.Server.Host.Models.IDatabaseContext.Users.
SeedAdminUser()
void Tgstation.Server.Host.Models.DatabaseSeeder.SeedAdminUser (IDatabaseContext databaseContext) private
Add a default admin User to a given databaseContext
Parameters
databaseContext The IDatabaseContext to add an admin User to
Definition at line 29 of file DatabaseSeeder.cs.
         {
             var admin = new User
             {
                 AdministrationRights = (AdministrationRights)~0U,
                 CreatedAt = DateTimeOffset.Now,
                 InstanceManagerRights = (InstanceManagerRights)~0U,
                 Name = Api.Models.User.AdminName,
                 CanonicalName = Api.Models.User.AdminName.ToUpperInvariant(),
                 Enabled = true,
             };
             cryptographySuite.SetUserPassword(admin, Api.Models.User.DefaultAdminPassword, true);
             databaseContext.Users.Add(admin);
         }
References Tgstation.Server.Host.Models.DatabaseSeeder.cryptographySuite, Tgstation.Server.Host.Security.ICryptographySuite.SetUserPassword(), and Tgstation.Server.Host.Models.IDatabaseContext.Users.
Referenced by Tgstation.Server.Host.Models.DatabaseSeeder.ResetAdminPassword(), and Tgstation.Server.Host.Models.DatabaseSeeder.SeedDatabase().
SeedDatabase()
async Task Tgstation.Server.Host.Models.DatabaseSeeder.SeedDatabase (IDatabaseContext databaseContext, CancellationToken cancellationToken)
Initially seed a given databaseContext
Implements Tgstation.Server.Host.Models.IDatabaseSeeder.
Definition at line 45 of file DatabaseSeeder.cs.
         {
             SeedAdminUser(databaseContext);
             await databaseContext.Save(cancellationToken).ConfigureAwait(false);
         }
References Tgstation.Server.Host.Models.IDatabaseContext.Save(), and Tgstation.Server.Host.Models.DatabaseSeeder.SeedAdminUser().
Member Data Documentation
cryptographySuite
readonly ICryptographySuite Tgstation.Server.Host.Models.DatabaseSeeder.cryptographySuite private
The ICryptographySuite for the DatabaseContext<TParentContext>
Definition at line 17 of file DatabaseSeeder.cs.
Referenced by Tgstation.Server.Host.Models.DatabaseSeeder.ResetAdminPassword(), and Tgstation.Server.Host.Models.DatabaseSeeder.SeedAdminUser().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Models/DatabaseSeeder.cs