tgstation-server: Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory Class Reference
Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory Class Reference
Public Member Functions
SessionControllerFactory (IProcessExecutor processExecutor, IByondManager byond, ITopicClient byondTopicSender, ICryptographySuite cryptographySuite, IAssemblyInformationProvider assemblyInformationProvider, IIOManager ioManager, IChatManager chat, INetworkPromptReaper networkPromptReaper, IPlatformIdentifier platformIdentifier, IBridgeRegistrar bridgeRegistrar, IServerPortProvider serverPortProvider, ILoggerFactory loggerFactory, Api.Models.Instance instance)
Construct a SessionControllerFactory
async Task< ISessionController > LaunchNew (IDmbProvider dmbProvider, IByondExecutableLock currentByondLock, DreamDaemonLaunchParameters launchParameters, bool primaryPort, bool primaryDirectory, bool apiValidate, CancellationToken cancellationToken)
Create a ISessionController from a freshly launch DreamDaemon instance
async Task< ISessionController > Reattach (ReattachInformation reattachInformation, CancellationToken cancellationToken)
Create a ISessionController from an existing DreamDaemon instance
ISessionController CreateDeadSession (IDmbProvider dmbProvider)
Creates a ISessionController that appears to have started and died with exit code -1
Private Member Functions
RuntimeInformation CreateRuntimeInformation (IDmbProvider dmbProvider, IChatTrackingContext chatTrackingContext, DreamDaemonSecurity? securityLevel, bool apiValidateOnly)
Create RuntimeInformation.
Static Private Member Functions
static string SecurityWord (DreamDaemonSecurity securityLevel)
Change a given securityLevel into the appropriate DreamDaemon command line word
Private Attributes
readonly IProcessExecutor processExecutor
The IProcessExecutor for the SessionControllerFactory
readonly IByondManager byond
The IByondManager for the SessionControllerFactory
readonly ITopicClient byondTopicSender
The ITopicClient for the SessionControllerFactory
readonly ICryptographySuite cryptographySuite
The ICryptographySuite for the SessionControllerFactory
readonly IAssemblyInformationProvider assemblyInformationProvider
The IAssemblyInformationProvider for the SessionControllerFactory
readonly IIOManager ioManager
The IIOManager for the SessionControllerFactory
readonly IChatManager chat
The IChatManager for the SessionControllerFactory
readonly INetworkPromptReaper networkPromptReaper
The INetworkPromptReaper for the SessionControllerFactory
readonly IPlatformIdentifier platformIdentifier
The IPlatformIdentifier for the SessionControllerFactory
readonly IBridgeRegistrar bridgeRegistrar
The IBridgeRegistrar for the SessionControllerFactory.
readonly IServerPortProvider serverPortProvider
The IServerPortProvider for the SessionControllerFactory.
readonly ILoggerFactory loggerFactory
The ILoggerFactory for the SessionControllerFactory
readonly Api.Models.Instance instance
The Api.Models.Instance for the SessionControllerFactory
Detailed Description
Definition at line 24 of file SessionControllerFactory.cs.
Constructor & Destructor Documentation
SessionControllerFactory()
Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.SessionControllerFactory (IProcessExecutor processExecutor, IByondManager byond, ITopicClient byondTopicSender, ICryptographySuite cryptographySuite, IAssemblyInformationProvider assemblyInformationProvider, IIOManager ioManager, IChatManager chat, INetworkPromptReaper networkPromptReaper, IPlatformIdentifier platformIdentifier, IBridgeRegistrar bridgeRegistrar, IServerPortProvider serverPortProvider, ILoggerFactory loggerFactory, Api.Models.Instance instance)
Construct a SessionControllerFactory
Parameters
processExecutor The value of processExecutor
byond The value of byond
byondTopicSender The value of byondTopicSender
cryptographySuite The value of cryptographySuite
assemblyInformationProvider The value of assemblyInformationProvider
instance The value of instance
ioManager The value of ioManager
chat The value of chat
networkPromptReaper The value of networkPromptReaper
platformIdentifier The value of platformIdentifier
bridgeRegistrar The value of bridgeRegistrar.
serverPortProvider The value of serverPortProvider.
loggerFactory The value of loggerFactory
Definition at line 123 of file SessionControllerFactory.cs.
         {
             this.processExecutor = processExecutor ?? throw new ArgumentNullException(nameof(processExecutor));
             this.byond = byond ?? throw new ArgumentNullException(nameof(byond));
             this.byondTopicSender = byondTopicSender ?? throw new ArgumentNullException(nameof(byondTopicSender));
             this.cryptographySuite = cryptographySuite ?? throw new ArgumentNullException(nameof(cryptographySuite));
             this.assemblyInformationProvider = assemblyInformationProvider ?? throw new ArgumentNullException(nameof(assemblyInformationProvider));
             this.instance = instance ?? throw new ArgumentNullException(nameof(instance));
             this.ioManager = ioManager ?? throw new ArgumentNullException(nameof(ioManager));
             this.chat = chat ?? throw new ArgumentNullException(nameof(chat));
             this.networkPromptReaper = networkPromptReaper ?? throw new ArgumentNullException(nameof(networkPromptReaper));
             this.platformIdentifier = platformIdentifier ?? throw new ArgumentNullException(nameof(platformIdentifier));
             this.bridgeRegistrar = bridgeRegistrar ?? throw new ArgumentNullException(nameof(bridgeRegistrar));
             this.serverPortProvider = serverPortProvider ?? throw new ArgumentNullException(nameof(serverPortProvider));
             this.loggerFactory = loggerFactory ?? throw new ArgumentNullException(nameof(loggerFactory));
         }
References Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.assemblyInformationProvider, Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.bridgeRegistrar, Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.byond, Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.byondTopicSender, Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.chat, Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.cryptographySuite, Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.instance, Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.ioManager, Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.loggerFactory, Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.networkPromptReaper, Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.platformIdentifier, Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.processExecutor, and Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.serverPortProvider.
Member Function Documentation
CreateDeadSession()
ISessionController Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.CreateDeadSession (IDmbProvider dmbProvider)
Creates a ISessionController that appears to have started and died with exit code -1
Implements Tgstation.Server.Host.Components.Watchdog.ISessionControllerFactory.
Referenced by Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.InitControllers().
CreateRuntimeInformation()
RuntimeInformation Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.CreateRuntimeInformation (IDmbProvider dmbProvider, IChatTrackingContext chatTrackingContext, DreamDaemonSecurity? securityLevel, bool apiValidateOnly) private
Create RuntimeInformation.
Parameters
dmbProvider The IDmbProvider.
chatTrackingContext The IChatTrackingContext.
securityLevel The DreamDaemonSecurity level if any.
apiValidateOnly The value of RuntimeInformation.ApiValidateOnly.
Returns
A new RuntimeInformation class.
Definition at line 344 of file SessionControllerFactory.cs.
         {
             var revisionInfo = new Api.Models.Internal.RevisionInformation
             {
                 CommitSha = dmbProvider.CompileJob.RevisionInformation.CommitSha,
                 OriginCommitSha = dmbProvider.CompileJob.RevisionInformation.OriginCommitSha
             };
             var testMerges = dmbProvider
                 .CompileJob
                 .RevisionInformation
                 .ActiveTestMerges
                 .Select(x => x.TestMerge)
                 .Select(x => new TestMergeInformation(x, revisionInfo));
             return new RuntimeInformation(
                 assemblyInformationProvider,
                 serverPortProvider,
                 testMerges,
                 chatTrackingContext.Channels,
                 instance,
                 revisionInfo,
                 securityLevel,
                 apiValidateOnly);
         }
References Tgstation.Server.Api.Models.RevisionInformation.ActiveTestMerges, Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.assemblyInformationProvider, Tgstation.Server.Host.Components.Chat.IChatTrackingContext.Channels, Tgstation.Server.Api.Models.Internal.RevisionInformation.CommitSha, Tgstation.Server.Host.Components.Deployment.IDmbProvider.CompileJob, Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.instance, Tgstation.Server.Api.Models.Internal.RevisionInformation.OriginCommitSha, Tgstation.Server.Api.Models.CompileJob.RevisionInformation, and Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.serverPortProvider.
Referenced by Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.LaunchNew(), and Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.Reattach().
LaunchNew()
async Task<ISessionController> Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.LaunchNew (IDmbProvider dmbProvider, IByondExecutableLock currentByondLock, DreamDaemonLaunchParameters launchParameters, bool primaryPort, bool primaryDirectory, bool apiValidate, CancellationToken cancellationToken)
Create a ISessionController from a freshly launch DreamDaemon instance
Implements Tgstation.Server.Host.Components.Watchdog.ISessionControllerFactory.
Definition at line 155 of file SessionControllerFactory.cs.
         {
             var portToUse = primaryPort ? launchParameters.PrimaryPort : launchParameters.SecondaryPort;
             if (!portToUse.HasValue)
                 throw new InvalidOperationException("Given port is null!");
             var basePath = primaryDirectory ? dmbProvider.PrimaryDirectory : dmbProvider.SecondaryDirectory;
             switch (dmbProvider.CompileJob.MinimumSecurityLevel)
             {
                 case DreamDaemonSecurity.Ultrasafe:
                     break;
                 case DreamDaemonSecurity.Safe:
                     if (launchParameters.SecurityLevel == DreamDaemonSecurity.Ultrasafe)
                         launchParameters.SecurityLevel = DreamDaemonSecurity.Safe;
                     break;
                 case DreamDaemonSecurity.Trusted:
                     launchParameters.SecurityLevel = DreamDaemonSecurity.Trusted;
                     break;
                 default:
                     throw new InvalidOperationException(String.Format(CultureInfo.InvariantCulture, "Invalid DreamDaemonSecurity value: {0}", dmbProvider.CompileJob.MinimumSecurityLevel));
             }
             var chatTrackingContext = chat.CreateTrackingContext();
             try
             {
                 // get the byond lock
                 var byondLock = currentByondLock ?? await byond.UseExecutables(Version.Parse(dmbProvider.CompileJob.ByondVersion), cancellationToken).ConfigureAwait(false);
                 try
                 {
                     if (launchParameters.SecurityLevel == DreamDaemonSecurity.Trusted)
                         await byondLock.TrustDmbPath(ioManager.ConcatPath(basePath, dmbProvider.DmbName), cancellationToken).ConfigureAwait(false);
                     var accessIdentifier = cryptographySuite.GetSecureString();
                     // set command line options
                     // more sanitization here cause it uses the same scheme
                     var parameters = $"{DMApiConstants.ParamApiVersion}={byondTopicSender.SanitizeString(DMApiConstants.Version.Semver().ToString())}&{byondTopicSender.SanitizeString(DMApiConstants.ParamServerPort)}={serverPortProvider.HttpApiPort}&{byondTopicSender.SanitizeString(DMApiConstants.ParamAccessIdentifier)}={byondTopicSender.SanitizeString(accessIdentifier)}";
                     var visibility = apiValidate ? "invisible" : "public";
                     // important to run on all ports to allow port changing
                     var arguments = String.Format(CultureInfo.InvariantCulture, "{0} -port {1} -ports 1-65535 {2}-close -{3} -{4} -public -params \"{5}\"",
                         dmbProvider.DmbName,
                         primaryPort ? launchParameters.PrimaryPort : launchParameters.SecondaryPort,
                         launchParameters.AllowWebClient.Value ? "-webclient " : String.Empty,
                         SecurityWord(launchParameters.SecurityLevel.Value),
                         visibility,
                         parameters);
                     // See https://github.com/tgstation/tgstation-server/issues/719
                     var noShellExecute = !platformIdentifier.IsWindows;
                     // launch dd
                     var process = processExecutor.LaunchProcess(byondLock.DreamDaemonPath, basePath, arguments, noShellExecute: noShellExecute);
                     try
                     {
                         networkPromptReaper.RegisterProcess(process);
                         var runtimeInformation = CreateRuntimeInformation(
                             dmbProvider,
                             chatTrackingContext,
                             launchParameters.SecurityLevel.Value,
                             apiValidate);
                         var reattachInformation = new ReattachInformation(
                             dmbProvider,
                             process,
                             runtimeInformation,
                             accessIdentifier,
                             portToUse.Value,
                             primaryDirectory);
                         var sessionController = new SessionController(
                             reattachInformation,
                             process,
                             byondLock,
                             byondTopicSender,
                             chatTrackingContext,
                             bridgeRegistrar,
                             chat,
                             loggerFactory.CreateLogger<SessionController>(),
                             launchParameters.StartupTimeout,
                             false);
                         return sessionController;
                     }
                     catch
                     {
                         process.Terminate();
                         process.Dispose();
                         throw;
                     }
                 }
                 catch
                 {
                     if (currentByondLock == null)
                         byondLock.Dispose();
                     throw;
                 }
             }
             catch
             {
                 chatTrackingContext.Dispose();
                 throw;
             }
         }
References Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.AllowWebClient, Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.bridgeRegistrar, Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.byond, Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.byondTopicSender, Tgstation.Server.Api.Models.CompileJob.ByondVersion, Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.chat, Tgstation.Server.Host.Components.Deployment.IDmbProvider.CompileJob, Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.CreateRuntimeInformation(), Tgstation.Server.Host.Components.Chat.IChatManager.CreateTrackingContext(), Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.cryptographySuite, Tgstation.Server.Host.Components.Deployment.IDmbProvider.DmbName, Tgstation.Server.Host.Security.ICryptographySuite.GetSecureString(), Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.ioManager, Tgstation.Server.Host.System.IPlatformIdentifier.IsWindows, Tgstation.Server.Host.System.IProcessExecutor.LaunchProcess(), Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.loggerFactory, Tgstation.Server.Api.Models.Internal.CompileJob.MinimumSecurityLevel, Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.networkPromptReaper, Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.platformIdentifier, Tgstation.Server.Host.Components.Deployment.IDmbProvider.PrimaryDirectory, Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.PrimaryPort, Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.processExecutor, Tgstation.Server.Host.System.INetworkPromptReaper.RegisterProcess(), Tgstation.Server.Host.Components.Deployment.IDmbProvider.SecondaryDirectory, Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.SecondaryPort, Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.SecurityLevel, Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.SecurityWord(), Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.StartupTimeout, and Tgstation.Server.Host.Components.Byond.IByondManager.UseExecutables().
Referenced by Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.HandlerMonitorWakeup(), Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.InitControllers(), and Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.InitControllers().
Reattach()
async Task<ISessionController> Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.Reattach (ReattachInformation reattachInformation, CancellationToken cancellationToken)
Create a ISessionController from an existing DreamDaemon instance
Implements Tgstation.Server.Host.Components.Watchdog.ISessionControllerFactory.
Definition at line 272 of file SessionControllerFactory.cs.
         {
             if (reattachInformation == null)
                 throw new ArgumentNullException(nameof(reattachInformation));
             var chatTrackingContext = chat.CreateTrackingContext();
             try
             {
                 var byondLock = await byond.UseExecutables(Version.Parse(reattachInformation.Dmb.CompileJob.ByondVersion), cancellationToken).ConfigureAwait(false);
                 try
                 {
                     var process = processExecutor.GetProcess(reattachInformation.ProcessId);
                     if (process == null)
                         return null;
                     try
                     {
                         networkPromptReaper.RegisterProcess(process);
                         var runtimeInformation = CreateRuntimeInformation(
                             reattachInformation.Dmb,
                             chatTrackingContext,
                             null,
                             false);
                         reattachInformation.SetRuntimeInformation(runtimeInformation);
                         var controller = new SessionController(
                             reattachInformation,
                             process,
                             byondLock,
                             byondTopicSender,
                             chatTrackingContext,
                             bridgeRegistrar,
                             chat,
                             loggerFactory.CreateLogger<SessionController>(),
                             null,
                             true);
                         process = null;
                         byondLock = null;
                         chatTrackingContext = null;
                         return controller;
                     }
                     finally
                     {
                         process?.Dispose();
                     }
                 }
                 finally
                 {
                     byondLock?.Dispose();
                 }
             }
             finally
             {
                 chatTrackingContext?.Dispose();
             }
         }
References Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.bridgeRegistrar, Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.byond, Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.byondTopicSender, Tgstation.Server.Api.Models.CompileJob.ByondVersion, Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.chat, Tgstation.Server.Host.Components.Deployment.IDmbProvider.CompileJob, Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.CreateRuntimeInformation(), Tgstation.Server.Host.Components.Chat.IChatManager.CreateTrackingContext(), Tgstation.Server.Host.Components.Watchdog.ReattachInformation.Dmb, Tgstation.Server.Host.System.IProcessExecutor.GetProcess(), Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.loggerFactory, Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.networkPromptReaper, Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.processExecutor, Tgstation.Server.Host.Models.ReattachInformationBase.ProcessId, Tgstation.Server.Host.System.INetworkPromptReaper.RegisterProcess(), Tgstation.Server.Host.Components.Watchdog.ReattachInformation.SetRuntimeInformation(), and Tgstation.Server.Host.Components.Byond.IByondManager.UseExecutables().
Referenced by Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.InitControllers(), and Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.InitControllers().
SecurityWord()
static string Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.SecurityWord (DreamDaemonSecurity securityLevel) static private
Change a given securityLevel into the appropriate DreamDaemon command line word
Parameters
securityLevel The DreamDaemonSecurity level to change
Returns
A string representation of the command line parameter
Definition at line 96 of file SessionControllerFactory.cs.
         {
             return securityLevel switch
             {
                 DreamDaemonSecurity.Safe => "safe",
                 DreamDaemonSecurity.Trusted => "trusted",
                 DreamDaemonSecurity.Ultrasafe => "ultrasafe",
                 _ => throw new ArgumentOutOfRangeException(nameof(securityLevel), securityLevel, String.Format(CultureInfo.InvariantCulture, "Bad DreamDaemon security level: {0}", securityLevel)),
             };
         }
Referenced by Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.LaunchNew().
Member Data Documentation
assemblyInformationProvider
readonly IAssemblyInformationProvider Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.assemblyInformationProvider private
The IAssemblyInformationProvider for the SessionControllerFactory
Definition at line 49 of file SessionControllerFactory.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.CreateRuntimeInformation(), and Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.SessionControllerFactory().
bridgeRegistrar
readonly IBridgeRegistrar Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.bridgeRegistrar private
The IBridgeRegistrar for the SessionControllerFactory.
Definition at line 74 of file SessionControllerFactory.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.LaunchNew(), Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.Reattach(), and Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.SessionControllerFactory().
byond
readonly IByondManager Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.byond private
The IByondManager for the SessionControllerFactory
Definition at line 34 of file SessionControllerFactory.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.LaunchNew(), Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.Reattach(), and Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.SessionControllerFactory().
byondTopicSender
readonly ITopicClient Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.byondTopicSender private
The ITopicClient for the SessionControllerFactory
Definition at line 39 of file SessionControllerFactory.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.LaunchNew(), Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.Reattach(), and Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.SessionControllerFactory().
chat
readonly IChatManager Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.chat private
The IChatManager for the SessionControllerFactory
Definition at line 59 of file SessionControllerFactory.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.LaunchNew(), Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.Reattach(), and Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.SessionControllerFactory().
cryptographySuite
readonly ICryptographySuite Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.cryptographySuite private
The ICryptographySuite for the SessionControllerFactory
Definition at line 44 of file SessionControllerFactory.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.LaunchNew(), and Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.SessionControllerFactory().
instance
readonly Api.Models.Instance Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.instance private
The Api.Models.Instance for the SessionControllerFactory
Definition at line 89 of file SessionControllerFactory.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.CreateRuntimeInformation(), and Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.SessionControllerFactory().
ioManager
readonly IIOManager Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.ioManager private
The IIOManager for the SessionControllerFactory
Definition at line 54 of file SessionControllerFactory.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.LaunchNew(), and Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.SessionControllerFactory().
loggerFactory
readonly ILoggerFactory Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.loggerFactory private
The ILoggerFactory for the SessionControllerFactory
Definition at line 84 of file SessionControllerFactory.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.LaunchNew(), Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.Reattach(), and Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.SessionControllerFactory().
networkPromptReaper
readonly INetworkPromptReaper Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.networkPromptReaper private
The INetworkPromptReaper for the SessionControllerFactory
Definition at line 64 of file SessionControllerFactory.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.LaunchNew(), Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.Reattach(), and Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.SessionControllerFactory().
platformIdentifier
readonly IPlatformIdentifier Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.platformIdentifier private
The IPlatformIdentifier for the SessionControllerFactory
Definition at line 69 of file SessionControllerFactory.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.LaunchNew(), and Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.SessionControllerFactory().
processExecutor
readonly IProcessExecutor Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.processExecutor private
The IProcessExecutor for the SessionControllerFactory
Definition at line 29 of file SessionControllerFactory.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.LaunchNew(), Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.Reattach(), and Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.SessionControllerFactory().
serverPortProvider
readonly IServerPortProvider Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.serverPortProvider private
The IServerPortProvider for the SessionControllerFactory.
Definition at line 79 of file SessionControllerFactory.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.CreateRuntimeInformation(), and Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.SessionControllerFactory().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Watchdog/SessionControllerFactory.cs