tgstation-server: Tgstation.Server.Host.Authority.UserAuthority Class Reference
Tgstation.Server.Host.Authority.UserAuthority Class Reference sealed
Public Member Functions
UserAuthority (IAuthenticationContext authenticationContext, IDatabaseContext databaseContext, ILogger< UserAuthority > logger, IUsersDataLoader usersDataLoader, IOAuthConnectionsDataLoader oAuthConnectionsDataLoader, IOidcConnectionsDataLoader oidcConnectionsDataLoader, ISystemIdentityFactory systemIdentityFactory, IPermissionsUpdateNotifyee permissionsUpdateNotifyee, ICryptographySuite cryptographySuite, ISessionInvalidationTracker sessionInvalidationTracker, ITopicEventSender topicEventSender, IOptionsSnapshot< GeneralConfiguration > generalConfigurationOptions, IOptions< SecurityConfiguration > securityConfigurationOptions)
Initializes a new instance of the UserAuthority class.
ValueTask< AuthorityResponse< User > > Read (CancellationToken cancellationToken)
Gets the currently authenticated user.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a User AuthorityResponse<TResult>.
async ValueTask< AuthorityResponse< User > > GetId (long id, bool includeJoins, bool allowSystemUser, CancellationToken cancellationToken)
Gets the User with a given id .
Parameters
id The EntityId.Id of the User.
includeJoins If related entities should be loaded.
allowSystemUser If the User.TgsSystemUserName may be returned.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a User AuthorityResponse<TResult>.
IQueryable< User > Queryable (bool includeJoins)
Gets all registered Users.
Parameters
includeJoins If related entities should be loaded.
Returns
A IQueryable<T> of Users.
async ValueTask< AuthorityResponse< GraphQL.Types.OAuth.OAuthConnection[]> > OAuthConnections (long userId, CancellationToken cancellationToken)
Gets the GraphQL.Types.OAuth.OAuthConnections for the User with a given userId .
Parameters
userId The EntityId.Id of the User.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in an global::System.Array of GraphQL.Types.OAuth.OAuthConnection AuthorityResponse<TResult>.
async ValueTask< AuthorityResponse< GraphQL.Types.OAuth.OidcConnection[]> > OidcConnections (long userId, CancellationToken cancellationToken)
Gets the GraphQL.Types.OAuth.OidcConnections for the User with a given userId .
Parameters
userId The EntityId.Id of the User.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in an global::System.Array of GraphQL.Types.OAuth.OidcConnection AuthorityResponse<TResult>.
async ValueTask< AuthorityResponse< User > > Create (UserCreateRequest createRequest, bool? needZeroLengthPasswordWithOAuthConnections, CancellationToken cancellationToken)
Creates a User.
Parameters
createRequest The UserCreateRequest.
needZeroLengthPasswordWithOAuthConnections If a zero-length UserUpdateRequest.Password indicates and OAuth only user.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in am AuthorityResponse<TResult> for the created User.
async ValueTask< AuthorityResponse< User > > Update (UserUpdateRequest model, CancellationToken cancellationToken)
Updates a User.
Parameters
updateRequest The UserUpdateRequest.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in am AuthorityResponse<TResult> for the created User.
Static Public Member Functions
static Task< Dictionary< long, User > > GetUsers (IReadOnlyList< long > ids, IDatabaseContext databaseContext, CancellationToken cancellationToken)
Implements the usersDataLoader.
static async ValueTask< ILookup< long, GraphQL.Types.OAuth.OAuthConnection > > GetOAuthConnections (IReadOnlyList< long > userIds, IDatabaseContext databaseContext, CancellationToken cancellationToken)
Implements the oAuthConnectionsDataLoader.
static async ValueTask< ILookup< long, GraphQL.Types.OAuth.OidcConnection > > GetOidcConnections (IReadOnlyList< long > userIds, IDatabaseContext databaseContext, CancellationToken cancellationToken)
Implements the oidcConnectionsDataLoader.
Private Member Functions
ValueTask SendUserUpdatedTopics (User user)
Send topics through the topicEventSender indicating a given user was created or updated.
IQueryable< User > Queryable (bool includeJoins, bool allowSystemUser)
Gets all registered Users.
async ValueTask< User > CreateNewUserFromModel (Api.Models.Internal.UserApiBase model, CancellationToken cancellationToken)
Creates a new User from a given model .
AuthorityResponse< User >? TrySetPassword (User dbUser, string newPassword, bool newUser)
Attempt to change the password of a given dbUser .
Static Private Member Functions
static ? AuthorityResponse< User > CheckValidName (UserUpdateRequest model, bool newUser)
Check if a given model has a valid UserName.Name specified.
static bool BadCreateRequestChecks (UserCreateRequest createRequest, bool? needZeroLengthPasswordWithOAuthConnections, [NotNullWhen(true)] out AuthorityResponse< User >? failResponse)
Checks if a createRequest should return a bad request AuthorityResponse<TResult>.
Private Attributes
readonly IUsersDataLoader usersDataLoader
The IUsersDataLoader for the UserAuthority.
readonly IOAuthConnectionsDataLoader oAuthConnectionsDataLoader
The IOAuthConnectionsDataLoader for the UserAuthority.
readonly IOidcConnectionsDataLoader oidcConnectionsDataLoader
The IOidcConnectionsDataLoader for the UserAuthority.
readonly ISystemIdentityFactory systemIdentityFactory
The ISystemIdentityFactory for the UserAuthority.
readonly IPermissionsUpdateNotifyee permissionsUpdateNotifyee
The IPermissionsUpdateNotifyee for the UserAuthority.
readonly ICryptographySuite cryptographySuite
The ICryptographySuite for the UserAuthority.
readonly ISessionInvalidationTracker sessionInvalidationTracker
The ISessionInvalidationTracker for the UserAuthority.
readonly ITopicEventSender topicEventSender
The ITopicEventSender for the UserAuthority.
readonly IOptionsSnapshot< GeneralConfiguration > generalConfigurationOptions
The IOptionsSnapshot<TOptions> of GeneralConfiguration for the UserAuthority.
readonly IOptions< SecurityConfiguration > securityConfigurationOptions
The IOptions<TOptions> of SecurityConfiguration for the UserAuthority.
Additional Inherited Members
Protected Member Functions inherited from Tgstation.Server.Host.Authority.Core.AuthorityBase
AuthorityBase (IAuthenticationContext authenticationContext, IDatabaseContext databaseContext, ILogger< AuthorityBase > logger)
Initializes a new instance of the AuthorityBase class.
AuthorityResponse< TResult > RateLimit< TResult > (RateLimitExceededException rateLimitException)
Generates a HttpFailureResponse.RateLimited type AuthorityResponse.
Static Protected Member Functions inherited from Tgstation.Server.Host.Authority.Core.AuthorityBase
static AuthorityResponse< TResult > BadRequest< TResult > (ErrorCode errorCode)
Generates a HttpFailureResponse.BadRequest type AuthorityResponse<TResult>.
static AuthorityResponse< TResult > Unauthorized< TResult > ()
Generates a HttpFailureResponse.Unauthorized type AuthorityResponse<TResult>.
static AuthorityResponse< TResult > Gone< TResult > ()
Generates a HttpFailureResponse.Forbidden type AuthorityResponse<TResult>.
static AuthorityResponse< TResult > Forbid< TResult > ()
Generates a HttpFailureResponse.Forbidden type AuthorityResponse<TResult>.
static AuthorityResponse< TResult > NotFound< TResult > ()
Generates a HttpFailureResponse.NotFound type AuthorityResponse<TResult>.
static AuthorityResponse< TResult > Conflict< TResult > (ErrorCode errorCode)
Generates a HttpFailureResponse.Conflict type AuthorityResponse<TResult>.
Properties inherited from Tgstation.Server.Host.Authority.Core.AuthorityBase
IAuthenticationContext AuthenticationContext [get]
Gets the IAuthenticationContext for the AuthorityBase.
IDatabaseContext DatabaseContext [get]
Gets the IDatabaseContext for the AuthorityBase.
ILogger< AuthorityBase > Logger [get]
Gets the ILogger for the AuthorityBase.
Detailed Description
Definition at line 32 of file UserAuthority.cs.
Constructor & Destructor Documentation
UserAuthority()
Tgstation.Server.Host.Authority.UserAuthority.UserAuthority (IAuthenticationContext authenticationContext, IDatabaseContext databaseContext, ILogger< UserAuthority > logger, IUsersDataLoader usersDataLoader, IOAuthConnectionsDataLoader oAuthConnectionsDataLoader, IOidcConnectionsDataLoader oidcConnectionsDataLoader, ISystemIdentityFactory systemIdentityFactory, IPermissionsUpdateNotifyee permissionsUpdateNotifyee, ICryptographySuite cryptographySuite, ISessionInvalidationTracker sessionInvalidationTracker, ITopicEventSender topicEventSender, IOptionsSnapshot< GeneralConfiguration > generalConfigurationOptions, IOptions< SecurityConfiguration > securityConfigurationOptions)
Initializes a new instance of the UserAuthority class.
Parameters
authenticationContext The IAuthenticationContext to use.
databaseContext The IDatabaseContext to use.
logger The ILogger to use.
usersDataLoader The value of usersDataLoader.
oAuthConnectionsDataLoader The value of oAuthConnectionsDataLoader.
oidcConnectionsDataLoader The value of oidcConnectionsDataLoader.
systemIdentityFactory The value of systemIdentityFactory.
permissionsUpdateNotifyee The value of permissionsUpdateNotifyee.
cryptographySuite The value of cryptographySuite.
sessionInvalidationTracker The value of sessionInvalidationTracker.
topicEventSender The value of topicEventSender.
generalConfigurationOptions The value of generalConfigurationOptions.
securityConfigurationOptions The value of securityConfigurationOptions.
Definition at line 195 of file UserAuthority.cs.
            : base(
                  authenticationContext,
                  databaseContext,
                  logger)
        {
            this.usersDataLoader = usersDataLoader ?? throw new ArgumentNullException(nameof(usersDataLoader));
            this.oAuthConnectionsDataLoader = oAuthConnectionsDataLoader ?? throw new ArgumentNullException(nameof(oAuthConnectionsDataLoader));
            this.oidcConnectionsDataLoader = oidcConnectionsDataLoader ?? throw new ArgumentNullException(nameof(oidcConnectionsDataLoader));
            this.systemIdentityFactory = systemIdentityFactory ?? throw new ArgumentNullException(nameof(systemIdentityFactory));
            this.permissionsUpdateNotifyee = permissionsUpdateNotifyee ?? throw new ArgumentNullException(nameof(permissionsUpdateNotifyee));
            this.cryptographySuite = cryptographySuite ?? throw new ArgumentNullException(nameof(cryptographySuite));
            this.sessionInvalidationTracker = sessionInvalidationTracker ?? throw new ArgumentNullException(nameof(sessionInvalidationTracker));
            this.topicEventSender = topicEventSender ?? throw new ArgumentNullException(nameof(topicEventSender));
            this.generalConfigurationOptions = generalConfigurationOptions ?? throw new ArgumentNullException(nameof(generalConfigurationOptions));
            this.securityConfigurationOptions = securityConfigurationOptions ?? throw new ArgumentNullException(nameof(securityConfigurationOptions));
        }
References Tgstation.Server.Host.Authority.UserAuthority.cryptographySuite, Tgstation.Server.Host.Authority.UserAuthority.generalConfigurationOptions, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Authority.UserAuthority.oAuthConnectionsDataLoader, Tgstation.Server.Host.Authority.UserAuthority.oidcConnectionsDataLoader, Tgstation.Server.Host.Authority.UserAuthority.permissionsUpdateNotifyee, Tgstation.Server.Host.Authority.UserAuthority.securityConfigurationOptions, Tgstation.Server.Host.Authority.UserAuthority.sessionInvalidationTracker, Tgstation.Server.Host.Authority.UserAuthority.systemIdentityFactory, Tgstation.Server.Host.Authority.UserAuthority.topicEventSender, and Tgstation.Server.Host.Authority.UserAuthority.usersDataLoader.
Member Function Documentation
BadCreateRequestChecks()
static bool Tgstation.Server.Host.Authority.UserAuthority.BadCreateRequestChecks (UserCreateRequest createRequest, bool? needZeroLengthPasswordWithOAuthConnections, [NotNullWhen(true)] out AuthorityResponse< User >? failResponse) static private
Checks if a createRequest should return a bad request AuthorityResponse<TResult>.
Parameters
createRequest The UserCreateRequest to check.
needZeroLengthPasswordWithOAuthConnections If a zero-length UserUpdateRequest.Password indicates and OAuth only user.
failResponse The output failing AuthorityResponse<TResult>, if any.
Returns
true if checks failed and failResponse was populated, false otherwise.
Definition at line 233 of file UserAuthority.cs.
        {
            if (createRequest.OAuthConnections?.Any(x => x == null) == true)
            {
                failResponse = BadRequest<User>(ErrorCode.ModelValidationFailure);
                return true;
            }
            var hasNonNullPassword = createRequest.Password != null;
            var hasNonNullSystemIdentifier = createRequest.SystemIdentifier != null;
            var hasOAuthConnections = (createRequest.OAuthConnections?.Count > 0) == true;
            if ((hasNonNullPassword && hasNonNullSystemIdentifier)
                || (!hasNonNullPassword && !hasNonNullSystemIdentifier && !hasOAuthConnections))
            {
                failResponse = BadRequest<User>(ErrorCode.UserMismatchPasswordSid);
                return true;
            }
            var hasZeroLengthPassword = createRequest.Password?.Length == 0;
            if (needZeroLengthPasswordWithOAuthConnections.HasValue)
            {
                if (needZeroLengthPasswordWithOAuthConnections.Value)
                {
                    if (createRequest.OAuthConnections == null)
                        throw new InvalidOperationException($"Expected {nameof(UserCreateRequest.OAuthConnections)} to be set here!");
                    if (createRequest.OAuthConnections.Count == 0)
                    {
                        failResponse = BadRequest<User>(ErrorCode.ModelValidationFailure);
                        return true;
                    }
                }
                else if (hasZeroLengthPassword)
                {
                    failResponse = BadRequest<User>(ErrorCode.ModelValidationFailure);
                    return true;
                }
            }
            if (createRequest.Group != null && createRequest.PermissionSet != null)
            {
                failResponse = BadRequest<User>(ErrorCode.UserGroupAndPermissionSet);
                return true;
            }
            createRequest.Name = createRequest.Name?.Trim();
            if (createRequest.Name?.Length == 0)
                createRequest.Name = null;
            if (!(createRequest.Name == null ^ createRequest.SystemIdentifier == null))
            {
                failResponse = BadRequest<User>(ErrorCode.UserMismatchNameSid);
                return true;
            }
            failResponse = CheckValidName(createRequest, true);
            return failResponse != null;
        }
References Tgstation.Server.Host.Authority.UserAuthority.CheckValidName(), and Tgstation.Server.Api.Rights.List.
Referenced by Tgstation.Server.Host.Authority.UserAuthority.Create().
CheckValidName()
static ? AuthorityResponse< User > Tgstation.Server.Host.Authority.UserAuthority.CheckValidName (UserUpdateRequest model, bool newUser) static private
Check if a given model has a valid UserName.Name specified.
Parameters
model The UserUpdateRequest to check.
newUser If this is a new User.
Returns
null if model is valid, an AuthorityResponse<TResult> errored otherwise.
Definition at line 167 of file UserAuthority.cs.
        {
            var userInvalidWithNullName = newUser && model.Name == null && model.SystemIdentifier == null;
            if (userInvalidWithNullName || (model.Name != null && String.IsNullOrWhiteSpace(model.Name)))
                return BadRequest<User>(ErrorCode.UserMissingName);
            model.Name = model.Name?.Trim();
            if (model.Name != null && model.Name.Contains(':', StringComparison.InvariantCulture))
                return BadRequest<User>(ErrorCode.UserColonInName);
            return null;
        }
References Tgstation.Server.Api.Rights.List.
Referenced by Tgstation.Server.Host.Authority.UserAuthority.BadCreateRequestChecks(), and Tgstation.Server.Host.Authority.UserAuthority.Update().
Create()
async ValueTask< AuthorityResponse< User > > Tgstation.Server.Host.Authority.UserAuthority.Create (UserCreateRequest createRequest, bool? needZeroLengthPasswordWithOAuthConnections, CancellationToken cancellationToken)
Creates a User.
Parameters
createRequest The UserCreateRequest.
needZeroLengthPasswordWithOAuthConnections If a zero-length UserUpdateRequest.Password indicates and OAuth only user.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in am AuthorityResponse<TResult> for the created User.
Implements Tgstation.Server.Host.Authority.IUserAuthority.
Definition at line 341 of file UserAuthority.cs.
        {
            ArgumentNullException.ThrowIfNull(createRequest);
            if (BadCreateRequestChecks(createRequest, needZeroLengthPasswordWithOAuthConnections, out var failResponse))
                return failResponse;
            var totalUsers = await DatabaseContext
                .Users
                .AsQueryable()
                .CountAsync(cancellationToken);
            if (totalUsers >= generalConfigurationOptions.Value.UserLimit)
                return Conflict<User>(ErrorCode.UserLimitReached);
            var dbUser = await CreateNewUserFromModel(createRequest, cancellationToken);
            if (dbUser == null)
                return Gone<User>();
            if (createRequest.SystemIdentifier != null)
                try
                {
                    using var sysIdentity = await systemIdentityFactory.CreateSystemIdentity(dbUser, cancellationToken);
                    if (sysIdentity == null)
                        return Gone<User>();
                    dbUser.Name = sysIdentity.Username;
                    dbUser.SystemIdentifier = sysIdentity.Uid;
                }
                catch (NotImplementedException ex)
                {
                    Logger.LogTrace(ex, "System identities not implemented!");
                    return new AuthorityResponse<User>(
                        new ErrorMessageResponse(ErrorCode.RequiresPosixSystemIdentity),
                        HttpFailureResponse.NotImplemented);
                }
            else
            {
                var hasZeroLengthPassword = createRequest.Password?.Length == 0;
                var hasOAuthConnections = (createRequest.OAuthConnections?.Count > 0) == true;
                // special case allow PasswordHash to be null by setting Password to "" if OAuthConnections are set
                if (!(needZeroLengthPasswordWithOAuthConnections != false && hasZeroLengthPassword && hasOAuthConnections))
                {
                    var result = TrySetPassword(dbUser, createRequest.Password!, true);
                    if (result != null)
                        return result;
                }
            }
            dbUser.CanonicalName = User.CanonicalizeName(dbUser.Name!);
            DatabaseContext.Users.Add(dbUser);
            await DatabaseContext.Save(cancellationToken);
            Logger.LogInformation("Created new user {name} ({id})", dbUser.Name, dbUser.Id);
            await SendUserUpdatedTopics(dbUser);
            return new AuthorityResponse<User>(dbUser, HttpSuccessResponse.Created);
        }
References Tgstation.Server.Host.Authority.UserAuthority.BadCreateRequestChecks(), Tgstation.Server.Host.Models.User.CanonicalizeName(), Tgstation.Server.Host.Authority.UserAuthority.CreateNewUserFromModel(), Tgstation.Server.Host.Security.ISystemIdentityFactory.CreateSystemIdentity(), Tgstation.Server.Host.Authority.UserAuthority.generalConfigurationOptions, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Authority.Core.AuthorityBase.Logger, Tgstation.Server.Host.Database.DatabaseContext.Save(), Tgstation.Server.Host.Authority.UserAuthority.SendUserUpdatedTopics(), Tgstation.Server.Host.Authority.UserAuthority.systemIdentityFactory, Tgstation.Server.Host.Authority.UserAuthority.TrySetPassword(), and Tgstation.Server.Host.Database.DatabaseContext.Users.
CreateNewUserFromModel()
async ValueTask< User > Tgstation.Server.Host.Authority.UserAuthority.CreateNewUserFromModel (Api::Models::Internal::UserApiBase model, CancellationToken cancellationToken) private
Creates a new User from a given model .
Parameters
model The Api.Models.Internal.UserApiBase to use as a template.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a new User on success, null if the requested UserGroup did not exist.
Definition at line 657 of file UserAuthority.cs.
        {
            Models.PermissionSet? permissionSet = null;
            UserGroup? group = null;
            if (model.Group != null)
                group = await DatabaseContext
                    .Groups
                    .AsQueryable()
                    .Where(x => x.Id == model.Group.Id)
                    .Include(x => x.PermissionSet)
                    .FirstOrDefaultAsync(cancellationToken);
            else
                permissionSet = new Models.PermissionSet
                {
                    AdministrationRights = model.PermissionSet?.AdministrationRights ?? AdministrationRights.None,
                    InstanceManagerRights = model.PermissionSet?.InstanceManagerRights ?? InstanceManagerRights.None,
                };
            return new User
            {
                CreatedAt = DateTimeOffset.UtcNow,
                CreatedBy = AuthenticationContext.User,
                Enabled = model.Enabled ?? false,
                PermissionSet = permissionSet,
                Group = group,
                Name = model.Name,
                SystemIdentifier = model.SystemIdentifier,
                OAuthConnections = model
                    .OAuthConnections
                    ?.Select(x => new Models.OAuthConnection
                    {
                        Provider = x.Provider,
                        ExternalUserId = x.ExternalUserId,
                    })
                    .ToList()
                    ?? new List<Models.OAuthConnection>(),
                OidcConnections = model
                    .OidcConnections
                    ?.Select(x => new Models.OidcConnection
                    {
                        SchemeKey = x.SchemeKey,
                        ExternalUserId = x.ExternalUserId,
                    })
                    .ToList()
                    ?? new List<Models.OidcConnection>(),
            };
        }
References Tgstation.Server.Api.Models.PermissionSet.AdministrationRights, Tgstation.Server.Api.Api, Tgstation.Server.Host.Enabled, Tgstation.Server.Host.Database.DatabaseContext.Groups, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Authority.UserAuthority.OAuthConnections(), Tgstation.Server.Host.Authority.UserAuthority.OidcConnections(), and Tgstation.Server.Host.Security.AuthenticationContext.User.
Referenced by Tgstation.Server.Host.Authority.UserAuthority.Create().
GetId()
async ValueTask< AuthorityResponse< User > > Tgstation.Server.Host.Authority.UserAuthority.GetId (long id, bool includeJoins, bool allowSystemUser, CancellationToken cancellationToken)
Gets the User with a given id .
Parameters
id The EntityId.Id of the User.
includeJoins If related entities should be loaded.
allowSystemUser If the User.TgsSystemUserName may be returned.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a User AuthorityResponse<TResult>.
Implements Tgstation.Server.Host.Authority.IUserAuthority.
Definition at line 300 of file UserAuthority.cs.
        {
            if (id != AuthenticationContext.User.Id && !((AdministrationRights)AuthenticationContext.GetRight(RightsType.Administration)).HasFlag(AdministrationRights.ReadUsers))
                return Forbid<User>();
            User? user;
            if (includeJoins)
            {
                var queryable = Queryable(true, true);
                user = await queryable.FirstOrDefaultAsync(
                    dbModel => dbModel.Id == id,
                    cancellationToken);
            }
            else
                user = await usersDataLoader.LoadAsync(id, cancellationToken);
            if (user == default)
                return NotFound<User>();
            if (!allowSystemUser && user.CanonicalName == User.CanonicalizeName(User.TgsSystemUserName))
                return Forbid<User>();
            return new AuthorityResponse<User>(user);
        }
References Tgstation.Server.Host.Models.User.CanonicalizeName(), Tgstation.Server.Host.Models.User.CanonicalName, Tgstation.Server.Host.Security.AuthenticationContext.GetRight(), Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Authority.UserAuthority.Queryable(), Tgstation.Server.Host.Models.User.TgsSystemUserName, Tgstation.Server.Host.Security.AuthenticationContext.User, and Tgstation.Server.Host.Authority.UserAuthority.usersDataLoader.
GetOAuthConnections()
static async ValueTask< ILookup< long, GraphQL.Types.OAuth.OAuthConnection > > Tgstation.Server.Host.Authority.UserAuthority.GetOAuthConnections (IReadOnlyList< long > userIds, IDatabaseContext databaseContext, CancellationToken cancellationToken) static
Implements the oAuthConnectionsDataLoader.
Parameters
userIds The IReadOnlyCollection<T> of User EntityId.Ids to load the OAuthConnections for.
databaseContext The IDatabaseContext to load from.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a Dictionary<TKey, TValue> of the requested Users.
Definition at line 115 of file UserAuthority.cs.
        {
            ArgumentNullException.ThrowIfNull(userIds);
            ArgumentNullException.ThrowIfNull(databaseContext);
            var list = await databaseContext
                .OAuthConnections
                .AsQueryable()
                .Where(x => userIds.Contains(x.User!.Id!.Value))
                .ToListAsync(cancellationToken);
            return list.ToLookup(
                oAuthConnection => oAuthConnection.UserId,
                x => new GraphQL.Types.OAuth.OAuthConnection(x.ExternalUserId!, x.Provider));
        }
References Tgstation.Server.Api.Rights.List, and Tgstation.Server.Host.Database.IDatabaseContext.OAuthConnections.
GetOidcConnections()
static async ValueTask< ILookup< long, GraphQL.Types.OAuth.OidcConnection > > Tgstation.Server.Host.Authority.UserAuthority.GetOidcConnections (IReadOnlyList< long > userIds, IDatabaseContext databaseContext, CancellationToken cancellationToken) static
Implements the oidcConnectionsDataLoader.
Parameters
userIds The IReadOnlyCollection<T> of User EntityId.Ids to load the OidcConnections for.
databaseContext The IDatabaseContext to load from.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a Dictionary<TKey, TValue> of the requested Users.
Definition at line 142 of file UserAuthority.cs.
        {
            ArgumentNullException.ThrowIfNull(userIds);
            ArgumentNullException.ThrowIfNull(databaseContext);
            var list = await databaseContext
                .OidcConnections
                .AsQueryable()
                .Where(x => userIds.Contains(x.User!.Id!.Value))
                .ToListAsync(cancellationToken);
            return list.ToLookup(
                oidcConnection => oidcConnection.UserId,
                x => new GraphQL.Types.OAuth.OidcConnection(x.ExternalUserId!, x.SchemeKey!));
        }
References Tgstation.Server.Api.Rights.List, and Tgstation.Server.Host.Database.IDatabaseContext.OidcConnections.
GetUsers()
static Task< Dictionary< long, User > > Tgstation.Server.Host.Authority.UserAuthority.GetUsers (IReadOnlyList< long > ids, IDatabaseContext databaseContext, CancellationToken cancellationToken) static
Implements the usersDataLoader.
Parameters
ids The IReadOnlyList<T> of User EntityId.Ids to load.
databaseContext The IDatabaseContext to load from.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a Dictionary<TKey, TValue> of the requested Users.
Definition at line 92 of file UserAuthority.cs.
        {
            ArgumentNullException.ThrowIfNull(ids);
            ArgumentNullException.ThrowIfNull(databaseContext);
            return databaseContext
                .Users
                .AsQueryable()
                .Where(x => ids.Contains(x.Id!.Value))
                .ToDictionaryAsync(user => user.Id!.Value, cancellationToken);
        }
References Tgstation.Server.Api.Rights.List, and Tgstation.Server.Host.Database.IDatabaseContext.Users.
OAuthConnections()
async ValueTask< AuthorityResponse< GraphQL.Types.OAuth.OAuthConnection[]> > Tgstation.Server.Host.Authority.UserAuthority.OAuthConnections (long userId, CancellationToken cancellationToken)
Gets the GraphQL.Types.OAuth.OAuthConnections for the User with a given userId .
Parameters
userId The EntityId.Id of the User.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in an global::System.Array of GraphQL.Types.OAuth.OAuthConnection AuthorityResponse<TResult>.
Implements Tgstation.Server.Host.Authority.IUserAuthority.
Referenced by Tgstation.Server.Host.Authority.UserAuthority.CreateNewUserFromModel().
OidcConnections()
async ValueTask< AuthorityResponse< GraphQL.Types.OAuth.OidcConnection[]> > Tgstation.Server.Host.Authority.UserAuthority.OidcConnections (long userId, CancellationToken cancellationToken)
Gets the GraphQL.Types.OAuth.OidcConnections for the User with a given userId .
Parameters
userId The EntityId.Id of the User.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in an global::System.Array of GraphQL.Types.OAuth.OidcConnection AuthorityResponse<TResult>.
Implements Tgstation.Server.Host.Authority.IUserAuthority.
Referenced by Tgstation.Server.Host.Authority.UserAuthority.CreateNewUserFromModel().
Queryable() [1/2]
IQueryable< User > Tgstation.Server.Host.Authority.UserAuthority.Queryable (bool includeJoins)
Gets all registered Users.
Parameters
includeJoins If related entities should be loaded.
Returns
A IQueryable<T> of Users.
Implements Tgstation.Server.Host.Authority.IUserAuthority.
Referenced by Tgstation.Server.Host.Authority.UserAuthority.GetId().
Queryable() [2/2]
IQueryable< User > Tgstation.Server.Host.Authority.UserAuthority.Queryable (bool includeJoins, bool allowSystemUser) private
Gets all registered Users.
Parameters
includeJoins If related entities should be loaded.
allowSystemUser If the User with the User.TgsSystemUserName should be included in results.
Returns
A IQueryable<T> of Users.
Definition at line 628 of file UserAuthority.cs.
        {
            var tgsUserCanonicalName = User.CanonicalizeName(User.TgsSystemUserName);
            var queryable = DatabaseContext
                .Users
                .AsQueryable();
            if (!allowSystemUser)
                queryable = queryable
                    .Where(user => user.CanonicalName != tgsUserCanonicalName);
            if (includeJoins)
                queryable = queryable
                    .Include(x => x.CreatedBy)
                    .Include(x => x.OAuthConnections)
                    .Include(x => x.OidcConnections)
                    .Include(x => x.Group!)
                        .ThenInclude(x => x.PermissionSet)
                    .Include(x => x.PermissionSet);
            return queryable;
        }
References Tgstation.Server.Host.Models.User.CanonicalizeName(), Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Models.User.TgsSystemUserName, and Tgstation.Server.Host.Database.DatabaseContext.Users.
Read()
ValueTask< AuthorityResponse< User > > Tgstation.Server.Host.Authority.UserAuthority.Read (CancellationToken cancellationToken)
Gets the currently authenticated user.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a User AuthorityResponse<TResult>.
Implements Tgstation.Server.Host.Authority.IUserAuthority.
SendUserUpdatedTopics()
ValueTask Tgstation.Server.Host.Authority.UserAuthority.SendUserUpdatedTopics (User user) private
Send topics through the topicEventSender indicating a given user was created or updated.
Parameters
user The User that was created or updated.
Returns
A ValueTask representing the running operation.
Referenced by Tgstation.Server.Host.Authority.UserAuthority.Create(), and Tgstation.Server.Host.Authority.UserAuthority.Update().
TrySetPassword()
AuthorityResponse< User >? Tgstation.Server.Host.Authority.UserAuthority.TrySetPassword (User dbUser, string newPassword, bool newUser) private
Attempt to change the password of a given dbUser .
Parameters
dbUser The user to update.
newPassword The new password.
newUser If this is for a new UserResponse.
Returns
null on success, an errored AuthorityResponse<TResult> if newPassword is too short.
Definition at line 712 of file UserAuthority.cs.
        {
            newPassword ??= String.Empty;
            if (newPassword.Length < generalConfigurationOptions.Value.MinimumPasswordLength)
                return new AuthorityResponse<User>(
                    new ErrorMessageResponse(ErrorCode.UserPasswordLength)
                    {
                        AdditionalData = $"Required password length: {generalConfigurationOptions.Value.MinimumPasswordLength}",
                    },
                    HttpFailureResponse.BadRequest);
            cryptographySuite.SetUserPassword(dbUser, newPassword, newUser);
            return null;
        }
References Tgstation.Server.Api.Rights.List.
Referenced by Tgstation.Server.Host.Authority.UserAuthority.Create(), and Tgstation.Server.Host.Authority.UserAuthority.Update().
Update()
async ValueTask< AuthorityResponse< User > > Tgstation.Server.Host.Authority.UserAuthority.Update (UserUpdateRequest model, CancellationToken cancellationToken)
Updates a User.
Parameters
updateRequest The UserUpdateRequest.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in am AuthorityResponse<TResult> for the created User.
Implements Tgstation.Server.Host.Authority.IUserAuthority.
Definition at line 408 of file UserAuthority.cs.
        {
            ArgumentNullException.ThrowIfNull(model);
            if (!model.Id.HasValue || model.OAuthConnections?.Any(x => x == null) == true)
                return BadRequest<User>(ErrorCode.ModelValidationFailure);
            if (model.Group != null && model.PermissionSet != null)
                return BadRequest<User>(ErrorCode.UserGroupAndPermissionSet);
            var callerAdministrationRights = (AdministrationRights)AuthenticationContext.GetRight(RightsType.Administration);
            var canEditAllUsers = callerAdministrationRights.HasFlag(AdministrationRights.WriteUsers);
            var passwordEdit = canEditAllUsers || callerAdministrationRights.HasFlag(AdministrationRights.EditOwnPassword);
            var oAuthEdit = canEditAllUsers || callerAdministrationRights.HasFlag(AdministrationRights.EditOwnServiceConnections);
            var originalUser = !canEditAllUsers
                ? AuthenticationContext.User
                : await DatabaseContext
                    .Users
                    .AsQueryable()
                    .Where(x => x.Id == model.Id)
                    .Include(x => x.CreatedBy)
                    .Include(x => x.OAuthConnections)
                    .Include(x => x.OidcConnections)
                    .Include(x => x.Group!)
                        .ThenInclude(x => x.PermissionSet)
                    .Include(x => x.PermissionSet)
                    .FirstOrDefaultAsync(cancellationToken);
            if (originalUser == default)
                return NotFound<User>();
            if (originalUser.CanonicalName == User.CanonicalizeName(User.TgsSystemUserName))
                return Forbid<User>();
            // Ensure they are only trying to edit things they have perms for (system identity change will trigger a bad request)
            if ((!canEditAllUsers
                && (model.Id != originalUser.Id
                || model.Enabled.HasValue
                || model.Group != null
                || model.PermissionSet != null
                || model.Name != null))
                || (!passwordEdit && model.Password != null)
                || (!oAuthEdit && model.OAuthConnections != null))
                return Forbid<User>();
            var originalUserHasSid = originalUser.SystemIdentifier != null;
            var invalidateSessions = false;
            if (originalUserHasSid && originalUser.PasswordHash != null)
            {
                // cleanup from https://github.com/tgstation/tgstation-server/issues/1528
                Logger.LogDebug("System user ID {userId}'s PasswordHash is polluted, updating database.", originalUser.Id);
                originalUser.PasswordHash = null;
                invalidateSessions = true;
            }
            if (model.SystemIdentifier != null && model.SystemIdentifier != originalUser.SystemIdentifier)
                return BadRequest<User>(ErrorCode.UserSidChange);
            if (model.Password != null)
            {
                if (originalUserHasSid)
                    return BadRequest<User>(ErrorCode.UserMismatchPasswordSid);
                var result = TrySetPassword(originalUser, model.Password, false);
                if (result != null)
                    return result;
                invalidateSessions = true;
            }
            if (model.Name != null && User.CanonicalizeName(model.Name) != originalUser.CanonicalName)
                return BadRequest<User>(ErrorCode.UserNameChange);
            if (model.OAuthConnections != null
                && (model.OAuthConnections.Count != originalUser.OAuthConnections!.Count
                || !model.OAuthConnections.All(x => originalUser.OAuthConnections.Any(y => y.Provider == x.Provider && y.ExternalUserId == x.ExternalUserId))))
            {
                if (securityConfigurationOptions.Value.OidcStrictMode)
                    return BadRequest<User>(ErrorCode.BadUserEditDueToOidcStrictMode);
                if (originalUser.CanonicalName == User.CanonicalizeName(DefaultCredentials.AdminUserName))
                    return BadRequest<User>(ErrorCode.AdminUserCannotHaveServiceConnection);
                if (model.OAuthConnections.Count == 0 && originalUser.PasswordHash == null && originalUser.SystemIdentifier == null)
                    return BadRequest<User>(ErrorCode.CannotRemoveLastAuthenticationOption);
                DatabaseContext.OAuthConnections.RemoveRange(originalUser.OAuthConnections);
                originalUser.OAuthConnections.Clear();
                foreach (var updatedConnection in model.OAuthConnections)
                    originalUser.OAuthConnections.Add(new Models.OAuthConnection
                    {
                        Provider = updatedConnection.Provider,
                        ExternalUserId = updatedConnection.ExternalUserId,
                    });
            }
            if (model.OidcConnections != null
                && (model.OidcConnections.Count != originalUser.OidcConnections!.Count
                || !model.OidcConnections.All(x => originalUser.OidcConnections.Any(y => y.SchemeKey == x.SchemeKey && y.ExternalUserId == x.ExternalUserId))))
            {
                if (securityConfigurationOptions.Value.OidcStrictMode)
                    return BadRequest<User>(ErrorCode.BadUserEditDueToOidcStrictMode);
                if (originalUser.CanonicalName == User.CanonicalizeName(DefaultCredentials.AdminUserName))
                    return BadRequest<User>(ErrorCode.AdminUserCannotHaveServiceConnection);
                if (model.OidcConnections.Count == 0 && originalUser.PasswordHash == null && originalUser.SystemIdentifier == null)
                    return BadRequest<User>(ErrorCode.CannotRemoveLastAuthenticationOption);
                DatabaseContext.OidcConnections.RemoveRange(originalUser.OidcConnections);
                originalUser.OidcConnections.Clear();
                foreach (var updatedConnection in model.OidcConnections)
                    originalUser.OidcConnections.Add(new Models.OidcConnection
                    {
                        SchemeKey = updatedConnection.SchemeKey,
                        ExternalUserId = updatedConnection.ExternalUserId,
                    });
            }
            if (model.Group != null)
            {
                if (securityConfigurationOptions.Value.OidcStrictMode)
                    return BadRequest<User>(ErrorCode.BadUserEditDueToOidcStrictMode);
                originalUser.Group = await DatabaseContext
                    .Groups
                    .AsQueryable()
                    .Where(x => x.Id == model.Group.Id)
                    .Include(x => x.PermissionSet)
                    .FirstOrDefaultAsync(cancellationToken);
                if (originalUser.Group == default)
                    return Gone<User>();
                DatabaseContext.Groups.Attach(originalUser.Group);
                if (originalUser.PermissionSet != null)
                {
                    Logger.LogInformation("Deleting permission set {permissionSetId}...", originalUser.PermissionSet.Id);
                    DatabaseContext.PermissionSets.Remove(originalUser.PermissionSet);
                    originalUser.PermissionSet = null;
                }
            }
            else if (model.PermissionSet != null)
            {
                if (securityConfigurationOptions.Value.OidcStrictMode)
                    return BadRequest<User>(ErrorCode.BadUserEditDueToOidcStrictMode);
                if (originalUser.PermissionSet == null)
                {
                    Logger.LogTrace("Creating new permission set...");
                    originalUser.PermissionSet = new Models.PermissionSet();
                }
                originalUser.PermissionSet.AdministrationRights = model.PermissionSet.AdministrationRights ?? AdministrationRights.None;
                originalUser.PermissionSet.InstanceManagerRights = model.PermissionSet.InstanceManagerRights ?? InstanceManagerRights.None;
                originalUser.Group = null;
                originalUser.GroupId = null;
            }
            var fail = CheckValidName(model, false);
            if (fail != null)
                return fail;
            originalUser.Name = model.Name ?? originalUser.Name;
            if (model.Enabled.HasValue)
            {
                if (securityConfigurationOptions.Value.OidcStrictMode)
                    return BadRequest<User>(ErrorCode.BadUserEditDueToOidcStrictMode);
                invalidateSessions = originalUser.Require(x => x.Enabled) && !model.Enabled.Value;
                originalUser.Enabled = model.Enabled.Value;
            }
            if (invalidateSessions)
                sessionInvalidationTracker.UserModifiedInvalidateSessions(originalUser);
            await DatabaseContext.Save(cancellationToken);
            Logger.LogInformation("Updated user {userName} ({userId})", originalUser.Name, originalUser.Id);
            if (invalidateSessions)
                await permissionsUpdateNotifyee.UserDisabled(originalUser, cancellationToken);
            await SendUserUpdatedTopics(originalUser);
            // return id only if not a self update and cannot read users
            var canReadBack = AuthenticationContext.User.Id == originalUser.Id
                || callerAdministrationRights.HasFlag(AdministrationRights.ReadUsers);
            return canReadBack
                ? new AuthorityResponse<User>(originalUser)
                : new AuthorityResponse<User>();
        }
References Tgstation.Server.Api.DefaultCredentials.AdminUserName, Tgstation.Server.Host.Models.User.CanonicalizeName(), Tgstation.Server.Host.Authority.UserAuthority.CheckValidName(), Tgstation.Server.Host.Security.AuthenticationContext.GetRight(), Tgstation.Server.Host.Database.DatabaseContext.Groups, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Authority.Core.AuthorityBase.Logger, Tgstation.Server.Host.Database.DatabaseContext.OAuthConnections, Tgstation.Server.Host.Database.DatabaseContext.OidcConnections, Tgstation.Server.Host.Database.DatabaseContext.PermissionSets, Tgstation.Server.Host.Authority.UserAuthority.permissionsUpdateNotifyee, Tgstation.Server.Host.Database.DatabaseContext.Save(), Tgstation.Server.Host.Authority.UserAuthority.securityConfigurationOptions, Tgstation.Server.Host.Authority.UserAuthority.SendUserUpdatedTopics(), Tgstation.Server.Host.Authority.UserAuthority.sessionInvalidationTracker, Tgstation.Server.Host.Models.User.TgsSystemUserName, Tgstation.Server.Host.Authority.UserAuthority.TrySetPassword(), Tgstation.Server.Host.Security.IPermissionsUpdateNotifyee.UserDisabled(), Tgstation.Server.Host.Security.ISessionInvalidationTracker.UserModifiedInvalidateSessions(), and Tgstation.Server.Host.Database.DatabaseContext.Users.
Member Data Documentation
cryptographySuite
readonly ICryptographySuite Tgstation.Server.Host.Authority.UserAuthority.cryptographySuite private
The ICryptographySuite for the UserAuthority.
Definition at line 62 of file UserAuthority.cs.
Referenced by Tgstation.Server.Host.Authority.UserAuthority.UserAuthority().
generalConfigurationOptions
readonly IOptionsSnapshot<GeneralConfiguration> Tgstation.Server.Host.Authority.UserAuthority.generalConfigurationOptions private
The IOptionsSnapshot<TOptions> of GeneralConfiguration for the UserAuthority.
Definition at line 77 of file UserAuthority.cs.
Referenced by Tgstation.Server.Host.Authority.UserAuthority.Create(), and Tgstation.Server.Host.Authority.UserAuthority.UserAuthority().
oAuthConnectionsDataLoader
readonly IOAuthConnectionsDataLoader Tgstation.Server.Host.Authority.UserAuthority.oAuthConnectionsDataLoader private
The IOAuthConnectionsDataLoader for the UserAuthority.
Definition at line 42 of file UserAuthority.cs.
Referenced by Tgstation.Server.Host.Authority.UserAuthority.UserAuthority().
oidcConnectionsDataLoader
readonly IOidcConnectionsDataLoader Tgstation.Server.Host.Authority.UserAuthority.oidcConnectionsDataLoader private
The IOidcConnectionsDataLoader for the UserAuthority.
Definition at line 47 of file UserAuthority.cs.
Referenced by Tgstation.Server.Host.Authority.UserAuthority.UserAuthority().
permissionsUpdateNotifyee
readonly IPermissionsUpdateNotifyee Tgstation.Server.Host.Authority.UserAuthority.permissionsUpdateNotifyee private
The IPermissionsUpdateNotifyee for the UserAuthority.
Definition at line 57 of file UserAuthority.cs.
Referenced by Tgstation.Server.Host.Authority.UserAuthority.Update(), and Tgstation.Server.Host.Authority.UserAuthority.UserAuthority().
securityConfigurationOptions
readonly IOptions<SecurityConfiguration> Tgstation.Server.Host.Authority.UserAuthority.securityConfigurationOptions private
The IOptions<TOptions> of SecurityConfiguration for the UserAuthority.
Definition at line 82 of file UserAuthority.cs.
Referenced by Tgstation.Server.Host.Authority.UserAuthority.Update(), and Tgstation.Server.Host.Authority.UserAuthority.UserAuthority().
sessionInvalidationTracker
readonly ISessionInvalidationTracker Tgstation.Server.Host.Authority.UserAuthority.sessionInvalidationTracker private
The ISessionInvalidationTracker for the UserAuthority.
Definition at line 67 of file UserAuthority.cs.
Referenced by Tgstation.Server.Host.Authority.UserAuthority.Update(), and Tgstation.Server.Host.Authority.UserAuthority.UserAuthority().
systemIdentityFactory
readonly ISystemIdentityFactory Tgstation.Server.Host.Authority.UserAuthority.systemIdentityFactory private
The ISystemIdentityFactory for the UserAuthority.
Definition at line 52 of file UserAuthority.cs.
Referenced by Tgstation.Server.Host.Authority.UserAuthority.Create(), and Tgstation.Server.Host.Authority.UserAuthority.UserAuthority().
topicEventSender
readonly ITopicEventSender Tgstation.Server.Host.Authority.UserAuthority.topicEventSender private
The ITopicEventSender for the UserAuthority.
Definition at line 72 of file UserAuthority.cs.
Referenced by Tgstation.Server.Host.Authority.UserAuthority.UserAuthority().
usersDataLoader
readonly IUsersDataLoader Tgstation.Server.Host.Authority.UserAuthority.usersDataLoader private
The IUsersDataLoader for the UserAuthority.
Definition at line 37 of file UserAuthority.cs.
Referenced by Tgstation.Server.Host.Authority.UserAuthority.GetId(), and Tgstation.Server.Host.Authority.UserAuthority.UserAuthority().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Authority/UserAuthority.cs