tgstation-server: Tgstation.Server.Host.Extensions.SocketExtensions Class Reference
Tgstation.Server.Host.Extensions.SocketExtensions Class Reference
Extension methods for the Socket class.
Static Public Member Functions
static void BindTest (IPlatformIdentifier platformIdentifier, ushort port, bool includeIPv6, bool udp)
Attempt to exclusively bind to a given port .
Detailed Description
Extension methods for the Socket class.
Definition at line 12 of file SocketExtensions.cs.
Member Function Documentation
BindTest()
static void Tgstation.Server.Host.Extensions.SocketExtensions.BindTest (IPlatformIdentifier platformIdentifier, ushort port, bool includeIPv6, bool udp) static
Attempt to exclusively bind to a given port .
Parameters
platformIdentifier The PlatformIdentifier to use.
port The port number to bind to.
includeIPv6 If IPV6 should be tested as well.
udp If we're bind testing for UDP. If false TCP will be checked.
Definition at line 21 of file SocketExtensions.cs.
        {
            ArgumentNullException.ThrowIfNull(platformIdentifier);
            ProcessExecutor.WithProcessLaunchExclusivity(() =>
            {
                using var socket = new Socket(
                    includeIPv6
                        ? AddressFamily.InterNetworkV6
                        : AddressFamily.InterNetwork,
                    udp
                        ? SocketType.Dgram
                        : SocketType.Stream,
                    udp
                        ? ProtocolType.Udp
                        : ProtocolType.Tcp);
                socket.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ExclusiveAddressUse, true);
                socket.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ReuseAddress, false);
                if (!udp && platformIdentifier.IsWindows)
                    socket.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.DontLinger, true);
                if (includeIPv6)
                    socket.DualMode = true;
                socket.Bind(
                    new IPEndPoint(
                        includeIPv6
                            ? IPAddress.IPv6Any
                            : IPAddress.Any,
                        port));
            });
        }
References Tgstation.Server.Host.System.IPlatformIdentifier.IsWindows, and Tgstation.Server.Host.System.ProcessExecutor.WithProcessLaunchExclusivity().
Referenced by Tgstation.Server.Host.Components.InstanceManager.CheckSystemCompatibility(), Tgstation.Server.Host.Utils.PortAllocator.GetAvailablePort(), and Tgstation.Server.Host.Components.Session.SessionControllerFactory.PortBindTest().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Extensions/SocketExtensions.cs