tgstation-server: Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager Class Reference
Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager Class Reference
IRemoteDeploymentManager for GitHub.com.
Public Member Functions
GitHubRemoteDeploymentManager (IDatabaseContextFactory databaseContextFactory, IGitHubServiceFactory gitHubServiceFactory, ILogger< GitHubRemoteDeploymentManager > logger, Api.Models.Instance metadata, ConcurrentDictionary< long, Action< bool > > activationCallbacks)
Initializes a new instance of the GitHubRemoteDeploymentManager class.
override async ValueTask StartDeployment (Api.Models.Internal.IGitRemoteInformation remoteInformation, CompileJob compileJob, CancellationToken cancellationToken)
Start a deployment for a given compileJob .
Parameters
remoteInformation The Api.Models.Internal.IGitRemoteInformation of the repository being deployed.
compileJob The active CompileJob.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
override ValueTask FailDeployment (CompileJob compileJob, string errorMessage, CancellationToken cancellationToken)
Fail a deployment for a given compileJob .
Parameters
compileJob The failed CompileJob.
errorMessage The error message.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
override async ValueTask< IReadOnlyCollection< TestMerge > > RemoveMergedTestMerges (IRepository repository, RepositorySettings repositorySettings, RevisionInformation revisionInformation, CancellationToken cancellationToken)
Get the updated list of TestMerges for an origin merge.
Parameters
repository The IRepository to use.
repositorySettings The RepositorySettings.
revisionInformation The current RevisionInformation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IReadOnlyCollection<T> of TestMerges that should remain the new RevisionInformation.
Public Member Functions inherited from Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager
async ValueTask PostDeploymentComments (CompileJob compileJob, RevisionInformation? previousRevisionInformation, RepositorySettings repositorySettings, string? repoOwner, string? repoName, CancellationToken cancellationToken)
Post deployment comments to the test merge ticket.
Parameters
compileJob The deployed CompileJob.
previousRevisionInformation The optional RevisionInformation of the previous deployment.
repositorySettings The RepositorySettings.
repoOwner The remote repostiory owner.
repoName The remote repostiory name.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
ValueTask ApplyDeployment (CompileJob compileJob, CancellationToken cancellationToken)
Stage a given compileJob 's deployment.
Parameters
compileJob The CompileJob being applied.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
abstract ValueTask FailDeployment (CompileJob compileJob, string errorMessage, CancellationToken cancellationToken)
Fail a deployment for a given compileJob .
Parameters
compileJob The failed CompileJob.
errorMessage The error message.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
ValueTask MarkInactive (CompileJob compileJob, CancellationToken cancellationToken)
Mark the deplotment for a given compileJob as inactive.
Parameters
compileJob The inactive CompileJob.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
abstract ValueTask< IReadOnlyCollection< TestMerge > > RemoveMergedTestMerges (IRepository repository, RepositorySettings repositorySettings, RevisionInformation revisionInformation, CancellationToken cancellationToken)
Get the updated list of TestMerges for an origin merge.
Parameters
repository The IRepository to use.
repositorySettings The RepositorySettings.
revisionInformation The current RevisionInformation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IReadOnlyCollection<T> of TestMerges that should remain the new RevisionInformation.
ValueTask StageDeployment (CompileJob compileJob, Action< bool >? activationCallback, CancellationToken cancellationToken)
Stage a given compileJob 's deployment.
Parameters
compileJob The staged CompileJob.
activationCallback An optional Action<T1> to be called when the CompileJob becomes active or is discarded with true or false respectively.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
abstract ValueTask StartDeployment (Api.Models.Internal.IGitRemoteInformation remoteInformation, CompileJob compileJob, CancellationToken cancellationToken)
Start a deployment for a given compileJob .
Parameters
remoteInformation The Api.Models.Internal.IGitRemoteInformation of the repository being deployed.
compileJob The active CompileJob.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
ValueTask StartDeployment (Api.Models.Internal.IGitRemoteInformation remoteInformation, CompileJob compileJob, CancellationToken cancellationToken)
Start a deployment for a given compileJob .
ValueTask StageDeployment (CompileJob compileJob, Action< bool >? activationCallback, CancellationToken cancellationToken)
Stage a given compileJob 's deployment.
ValueTask ApplyDeployment (CompileJob compileJob, CancellationToken cancellationToken)
Stage a given compileJob 's deployment.
ValueTask FailDeployment (CompileJob compileJob, string errorMessage, CancellationToken cancellationToken)
Fail a deployment for a given compileJob .
ValueTask MarkInactive (CompileJob compileJob, CancellationToken cancellationToken)
Mark the deplotment for a given compileJob as inactive.
ValueTask PostDeploymentComments (CompileJob compileJob, RevisionInformation? previousRevisionInformation, RepositorySettings repositorySettings, string? repoOwner, string? repoName, CancellationToken cancellationToken)
Post deployment comments to the test merge ticket.
ValueTask< IReadOnlyCollection< TestMerge > > RemoveMergedTestMerges (IRepository repository, RepositorySettings repositorySettings, RevisionInformation revisionInformation, CancellationToken cancellationToken)
Get the updated list of TestMerges for an origin merge.
Protected Member Functions
override ValueTask StageDeploymentImpl (CompileJob compileJob, CancellationToken cancellationToken)
Implementation of StageDeployment(CompileJob, Action<bool>, CancellationToken).
Parameters
compileJob The staged CompileJob.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
override ValueTask ApplyDeploymentImpl (CompileJob compileJob, CancellationToken cancellationToken)
Implementation of ApplyDeployment(CompileJob, CancellationToken).
Parameters
compileJob The CompileJob being applied.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
override ValueTask MarkInactiveImpl (CompileJob compileJob, CancellationToken cancellationToken)
Implementation of MarkInactive(CompileJob, CancellationToken).
Parameters
compileJob The inactive CompileJob.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
override async ValueTask CommentOnTestMergeSource (RepositorySettings repositorySettings, string remoteRepositoryOwner, string remoteRepositoryName, string comment, int testMergeNumber, CancellationToken cancellationToken)
Create a comment of a given testMergeNumber 's source.
Parameters
repositorySettings The RepositorySettings to use.
remoteRepositoryOwner The Api.Models.Internal.IGitRemoteInformation.RemoteRepositoryOwner.
remoteRepositoryName The Api.Models.Internal.IGitRemoteInformation.RemoteRepositoryName.
comment The comment to post.
testMergeNumber The Api.Models.TestMergeParameters.Number.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
override string FormatTestMerge (RepositorySettings repositorySettings, CompileJob compileJob, TestMerge testMerge, string remoteRepositoryOwner, string remoteRepositoryName, bool updated)
Formats a comment for a given testMerge .
Parameters
repositorySettings The RepositorySettings to use.
compileJob The test merge's CompileJob.
testMerge The TestMerge.
remoteRepositoryOwner The Api.Models.Internal.IGitRemoteInformation.RemoteRepositoryOwner.
remoteRepositoryName The Api.Models.Internal.IGitRemoteInformation.RemoteRepositoryName.
updated If false testMerge is new, otherwise it has been updated to a different Api.Models.TestMergeParameters.TargetCommitSha.
Returns
A formatted string for posting a informative comment about the testMerge .
Protected Member Functions inherited from Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager
BaseRemoteDeploymentManager (ILogger< BaseRemoteDeploymentManager > logger, Api.Models.Instance metadata, ConcurrentDictionary< long, Action< bool > > activationCallbacks)
Initializes a new instance of the BaseRemoteDeploymentManager class.
abstract ValueTask StageDeploymentImpl (CompileJob compileJob, CancellationToken cancellationToken)
Implementation of StageDeployment(CompileJob, Action<bool>, CancellationToken).
abstract ValueTask ApplyDeploymentImpl (CompileJob compileJob, CancellationToken cancellationToken)
Implementation of ApplyDeployment(CompileJob, CancellationToken).
abstract ValueTask MarkInactiveImpl (CompileJob compileJob, CancellationToken cancellationToken)
Implementation of MarkInactive(CompileJob, CancellationToken).
abstract string FormatTestMerge (RepositorySettings repositorySettings, CompileJob compileJob, TestMerge testMerge, string remoteRepositoryOwner, string remoteRepositoryName, bool updated)
Formats a comment for a given testMerge .
abstract ValueTask CommentOnTestMergeSource (RepositorySettings repositorySettings, string remoteRepositoryOwner, string remoteRepositoryName, string comment, int testMergeNumber, CancellationToken cancellationToken)
Create a comment of a given testMergeNumber 's source.
Private Member Functions
async ValueTask UpdateDeployment (CompileJob compileJob, string description, DeploymentState deploymentState, CancellationToken cancellationToken)
Update the deployment for a given compileJob .
Private Attributes
readonly IDatabaseContextFactory databaseContextFactory
The IDatabaseContextFactory for the GitHubRemoteDeploymentManager.
readonly IGitHubServiceFactory gitHubServiceFactory
The IGitHubServiceFactory for the GitHubRemoteDeploymentManager.
Additional Inherited Members
Properties inherited from Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager
Api.Models.Instance Metadata [get]
The Api.Models.Instance for the BaseRemoteDeploymentManager.
ILogger< BaseRemoteDeploymentManager > Logger [get]
The ILogger for the BaseRemoteDeploymentManager.
Detailed Description
IRemoteDeploymentManager for GitHub.com.
Definition at line 25 of file GitHubRemoteDeploymentManager.cs.
Constructor & Destructor Documentation
GitHubRemoteDeploymentManager()
Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.GitHubRemoteDeploymentManager (IDatabaseContextFactory databaseContextFactory, IGitHubServiceFactory gitHubServiceFactory, ILogger< GitHubRemoteDeploymentManager > logger, Api.Models.Instance metadata, ConcurrentDictionary< long, Action< bool > > activationCallbacks)
Initializes a new instance of the GitHubRemoteDeploymentManager class.
Parameters
databaseContextFactory The value of databaseContextFactory.
gitHubServiceFactory The value of gitHubServiceFactory.
logger The ILogger for the BaseRemoteDeploymentManager.
metadata The Api.Models.Instance for the BaseRemoteDeploymentManager.
activationCallbacks The activation callback ConcurrentDictionary<TKey, TValue> for the BaseRemoteDeploymentManager.
Definition at line 45 of file GitHubRemoteDeploymentManager.cs.
            : base(logger, metadata, activationCallbacks)
        {
            this.databaseContextFactory = databaseContextFactory ?? throw new ArgumentNullException(nameof(databaseContextFactory));
            this.gitHubServiceFactory = gitHubServiceFactory ?? throw new ArgumentNullException(nameof(gitHubServiceFactory));
        }
References Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.databaseContextFactory, and Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.gitHubServiceFactory.
Member Function Documentation
ApplyDeploymentImpl()
override ValueTask Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.ApplyDeploymentImpl (CompileJob compileJob, CancellationToken cancellationToken) protected virtual
Implementation of ApplyDeployment(CompileJob, CancellationToken).
Parameters
compileJob The CompileJob being applied.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.
CommentOnTestMergeSource()
override async ValueTask Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.CommentOnTestMergeSource (RepositorySettings repositorySettings, string remoteRepositoryOwner, string remoteRepositoryName, string comment, int testMergeNumber, CancellationToken cancellationToken) protected virtual
Create a comment of a given testMergeNumber 's source.
Parameters
repositorySettings The RepositorySettings to use.
remoteRepositoryOwner The Api.Models.Internal.IGitRemoteInformation.RemoteRepositoryOwner.
remoteRepositoryName The Api.Models.Internal.IGitRemoteInformation.RemoteRepositoryName.
comment The comment to post.
testMergeNumber The Api.Models.TestMergeParameters.Number.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.
Definition at line 250 of file GitHubRemoteDeploymentManager.cs.
        {
            var gitHubService = gitHubServiceFactory.CreateService(repositorySettings.AccessToken!);
            try
            {
                await gitHubService.CommentOnIssue(remoteRepositoryOwner, remoteRepositoryName, comment, testMergeNumber, cancellationToken);
            }
            catch (Exception ex) when (ex is not OperationCanceledException)
            {
                Logger.LogWarning(ex, "Error posting GitHub comment!");
            }
        }
References Tgstation.Server.Api.Models.Internal.RepositorySettings.AccessToken, Tgstation.Server.Host.Utils.GitHub.IGitHubServiceFactory.CreateService(), Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.gitHubServiceFactory, and Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.Logger.
FailDeployment()
override ValueTask Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.FailDeployment (CompileJob compileJob, string errorMessage, CancellationToken cancellationToken) virtual
Fail a deployment for a given compileJob .
Parameters
compileJob The failed CompileJob.
errorMessage The error message.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.
FormatTestMerge()
override string Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.FormatTestMerge (RepositorySettings repositorySettings, CompileJob compileJob, TestMerge testMerge, string remoteRepositoryOwner, string remoteRepositoryName, bool updated) protected virtual
Formats a comment for a given testMerge .
Parameters
repositorySettings The RepositorySettings to use.
compileJob The test merge's CompileJob.
testMerge The TestMerge.
remoteRepositoryOwner The Api.Models.Internal.IGitRemoteInformation.RemoteRepositoryOwner.
remoteRepositoryName The Api.Models.Internal.IGitRemoteInformation.RemoteRepositoryName.
updated If false testMerge is new, otherwise it has been updated to a different Api.Models.TestMergeParameters.TargetCommitSha.
Returns
A formatted string for posting a informative comment about the testMerge .
Implements Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.
MarkInactiveImpl()
override ValueTask Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.MarkInactiveImpl (CompileJob compileJob, CancellationToken cancellationToken) protected virtual
Implementation of MarkInactive(CompileJob, CancellationToken).
Parameters
compileJob The inactive CompileJob.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.
RemoveMergedTestMerges()
override async ValueTask< IReadOnlyCollection< TestMerge > > Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.RemoveMergedTestMerges (IRepository repository, RepositorySettings repositorySettings, RevisionInformation revisionInformation, CancellationToken cancellationToken) virtual
Get the updated list of TestMerges for an origin merge.
Parameters
repository The IRepository to use.
repositorySettings The RepositorySettings.
revisionInformation The current RevisionInformation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IReadOnlyCollection<T> of TestMerges that should remain the new RevisionInformation.
Implements Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.
Definition at line 161 of file GitHubRemoteDeploymentManager.cs.
        {
            ArgumentNullException.ThrowIfNull(repository);
            ArgumentNullException.ThrowIfNull(repositorySettings);
            ArgumentNullException.ThrowIfNull(revisionInformation);
            if ((revisionInformation.ActiveTestMerges?.Count > 0) != true)
            {
                Logger.LogTrace("No test merges to remove.");
                return Array.Empty<TestMerge>();
            }
            var gitHubService = repositorySettings.AccessToken != null
                ? gitHubServiceFactory.CreateService(repositorySettings.AccessToken)
                : gitHubServiceFactory.CreateService();
            var tasks = revisionInformation
                .ActiveTestMerges
                .Select(x => gitHubService.GetPullRequest(
                    repository.RemoteRepositoryOwner!,
                    repository.RemoteRepositoryName!,
                    x.TestMerge.Number,
                    cancellationToken));
            try
            {
                await Task.WhenAll(tasks);
            }
            catch (Exception ex) when (ex is not OperationCanceledException)
            {
                Logger.LogWarning(ex, "Pull requests update check failed!");
            }
            var newList = revisionInformation.ActiveTestMerges.Select(x => x.TestMerge).ToList();
            PullRequest? lastMerged = null;
            async ValueTask CheckRemovePR(Task<PullRequest> task)
            {
                var pr = await task;
                if (!pr.Merged)
                    return;
                // We don't just assume, actually check the repo contains the merge commit.
                if (await repository.CommittishIsParent(pr.MergeCommitSha, cancellationToken))
                {
                    if (lastMerged == null || lastMerged.MergedAt < pr.MergedAt)
                        lastMerged = pr;
                    newList.Remove(
                        newList.First(
                            potential => potential.Number == pr.Number));
                }
            }
            foreach (var prTask in tasks)
                await CheckRemovePR(prTask);
            return newList;
        }
References Tgstation.Server.Api.Models.Internal.RepositorySettings.AccessToken, Tgstation.Server.Host.Models.RevisionInformation.ActiveTestMerges, Tgstation.Server.Host.Components.Repository.IRepository.CommittishIsParent(), Tgstation.Server.Host.Utils.GitHub.IGitHubServiceFactory.CreateService(), Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.gitHubServiceFactory, Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.Logger, Tgstation.Server.Api.Models.Internal.IGitRemoteInformation.RemoteRepositoryName, and Tgstation.Server.Api.Models.Internal.IGitRemoteInformation.RemoteRepositoryOwner.
StageDeploymentImpl()
override ValueTask Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.StageDeploymentImpl (CompileJob compileJob, CancellationToken cancellationToken) protected virtual
Implementation of StageDeployment(CompileJob, Action<bool>, CancellationToken).
Parameters
compileJob The staged CompileJob.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.
StartDeployment()
override async ValueTask Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.StartDeployment (Api.Models.Internal.IGitRemoteInformation remoteInformation, CompileJob compileJob, CancellationToken cancellationToken) virtual
Start a deployment for a given compileJob .
Parameters
remoteInformation The Api.Models.Internal.IGitRemoteInformation of the repository being deployed.
compileJob The active CompileJob.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.
Definition at line 58 of file GitHubRemoteDeploymentManager.cs.
        {
            ArgumentNullException.ThrowIfNull(remoteInformation);
            ArgumentNullException.ThrowIfNull(compileJob);
            Logger.LogTrace("Starting deployment...");
            RepositorySettings? repositorySettings = null;
            await databaseContextFactory.UseContext(
                async databaseContext =>
                    repositorySettings = await databaseContext
                        .RepositorySettings
                        .AsQueryable()
                        .Where(x => x.InstanceId == Metadata.Id)
                        .FirstAsync(cancellationToken));
            var instanceAuthenticated = repositorySettings!.AccessToken != null;
            IAuthenticatedGitHubService? authenticatedGitHubService;
            IGitHubService gitHubService;
            if (instanceAuthenticated)
            {
                authenticatedGitHubService = gitHubServiceFactory.CreateService(repositorySettings.AccessToken!);
                gitHubService = authenticatedGitHubService;
            }
            else
            {
                authenticatedGitHubService = null;
                gitHubService = gitHubServiceFactory.CreateService();
            }
            var repoOwner = remoteInformation.RemoteRepositoryOwner!;
            var repoName = remoteInformation.RemoteRepositoryName!;
            var repositoryIdTask = gitHubService.GetRepositoryId(
                repoOwner,
                repoName,
                cancellationToken);
            if (!repositorySettings.CreateGitHubDeployments!.Value)
                Logger.LogTrace("Not creating deployment");
            else if (!instanceAuthenticated)
                Logger.LogWarning("Can't create GitHub deployment as no access token is set for repository!");
            else
            {
                Logger.LogTrace("Creating deployment...");
                try
                {
                    compileJob.GitHubDeploymentId = await authenticatedGitHubService!.CreateDeployment(
                        new NewDeployment(compileJob.RevisionInformation.CommitSha)
{
                            AutoMerge = false,
                            Description = "TGS Game Deployment",
                            Environment = $"TGS: {Metadata.Name}",
                            ProductionEnvironment = true,
                            RequiredContexts = new Collection<string>(),
                        },
                        repoOwner,
                        repoName,
                        cancellationToken);
                    Logger.LogDebug("Created deployment ID {deploymentId}", compileJob.GitHubDeploymentId);
                    await authenticatedGitHubService.CreateDeploymentStatus(
                        new NewDeploymentStatus(DeploymentState.InProgress)
{
                            Description = "The project is being deployed",
                            AutoInactive = false,
                        },
                        repoOwner,
                        repoName,
                        compileJob.GitHubDeploymentId.Value,
                        cancellationToken);
                    Logger.LogTrace("In-progress deployment status created");
                }
                catch (Exception ex) when (ex is not OperationCanceledException)
                {
                    Logger.LogWarning(ex, "Unable to create GitHub deployment!");
                }
            }
            try
            {
                compileJob.GitHubRepoId = await repositoryIdTask;
                Logger.LogTrace("Set GitHub ID as {gitHubRepoId}", compileJob.GitHubRepoId);
            }
            catch (Exception ex) when (ex is not OperationCanceledException)
            {
                Logger.LogWarning(ex, "Unable to set compile job repository ID!");
            }
        }
References Tgstation.Server.Api.Models.Internal.RepositorySettings.AccessToken, Tgstation.Server.Api.Models.Internal.RevisionInformation.CommitSha, Tgstation.Server.Host.Utils.GitHub.IAuthenticatedGitHubService.CreateDeployment(), Tgstation.Server.Host.Utils.GitHub.IAuthenticatedGitHubService.CreateDeploymentStatus(), Tgstation.Server.Api.Models.Internal.RepositorySettings.CreateGitHubDeployments, Tgstation.Server.Host.Utils.GitHub.IGitHubServiceFactory.CreateService(), Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.databaseContextFactory, Tgstation.Server.Host.Utils.GitHub.IGitHubService.GetRepositoryId(), Tgstation.Server.Host.Models.CompileJob.GitHubDeploymentId, Tgstation.Server.Host.Models.CompileJob.GitHubRepoId, Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.gitHubServiceFactory, Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.Logger, Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.Metadata, Tgstation.Server.Host.Models.CompileJob.RevisionInformation, and Tgstation.Server.Host.Database.IDatabaseContextFactory.UseContext().
UpdateDeployment()
async ValueTask Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.UpdateDeployment (CompileJob compileJob, string description, DeploymentState deploymentState, CancellationToken cancellationToken) private
Update the deployment for a given compileJob .
Parameters
compileJob The CompileJob.
description A description of the update.
deploymentState The new DeploymentState.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Definition at line 312 of file GitHubRemoteDeploymentManager.cs.
        {
            ArgumentNullException.ThrowIfNull(compileJob);
            if (!compileJob.GitHubRepoId.HasValue || !compileJob.GitHubDeploymentId.HasValue)
            {
                Logger.LogTrace("Not updating deployment as it is missing a repo ID or deployment ID.");
                return;
            }
            Logger.LogTrace("Updating deployment {gitHubDeploymentId} to {deploymentState}...", compileJob.GitHubDeploymentId.Value, deploymentState);
            string? gitHubAccessToken = null;
            await databaseContextFactory.UseContext(
                async databaseContext =>
                    gitHubAccessToken = await databaseContext
                        .RepositorySettings
                        .AsQueryable()
                        .Where(x => x.InstanceId == Metadata.Id)
                        .Select(x => x.AccessToken)
                        .FirstAsync(cancellationToken));
            if (gitHubAccessToken == null)
            {
                Logger.LogWarning(
                    "GitHub access token disappeared during deployment, can't update to {deploymentState}!",
                    deploymentState);
                return;
            }
            var gitHubService = gitHubServiceFactory.CreateService(gitHubAccessToken);
            try
            {
                await gitHubService.CreateDeploymentStatus(
                    new NewDeploymentStatus(deploymentState)
                    {
                        Description = description,
                    },
                    compileJob.GitHubRepoId.Value,
                    compileJob.GitHubDeploymentId.Value,
                    cancellationToken);
            }
            catch (Exception ex) when (ex is not OperationCanceledException)
            {
                Logger.LogWarning(ex, "Error updating GitHub deployment!");
            }
        }
References Tgstation.Server.Host.Utils.GitHub.IGitHubServiceFactory.CreateService(), Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.databaseContextFactory, Tgstation.Server.Host.Models.CompileJob.GitHubDeploymentId, Tgstation.Server.Host.Models.CompileJob.GitHubRepoId, Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.gitHubServiceFactory, Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.Logger, Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.Metadata, and Tgstation.Server.Host.Database.IDatabaseContextFactory.UseContext().
Member Data Documentation
databaseContextFactory
readonly IDatabaseContextFactory Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.databaseContextFactory private
The IDatabaseContextFactory for the GitHubRemoteDeploymentManager.
Definition at line 30 of file GitHubRemoteDeploymentManager.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.GitHubRemoteDeploymentManager(), Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.StartDeployment(), and Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.UpdateDeployment().
gitHubServiceFactory
readonly IGitHubServiceFactory Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.gitHubServiceFactory private
The IGitHubServiceFactory for the GitHubRemoteDeploymentManager.
Definition at line 35 of file GitHubRemoteDeploymentManager.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.CommentOnTestMergeSource(), Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.GitHubRemoteDeploymentManager(), Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.RemoveMergedTestMerges(), Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.StartDeployment(), and Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.UpdateDeployment().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Deployment/Remote/GitHubRemoteDeploymentManager.cs