tgstation-server: Tgstation.Server.Host.Configuration.FileLoggingConfiguration Class Reference
Tgstation.Server.Host.Configuration.FileLoggingConfiguration Class Reference
File logging configuration options
Public Member Functions
string GetFullLogDirectory (IIOManager ioManager, IAssemblyInformationProvider assemblyInformationProvider, IPlatformIdentifier platformIdentifier)
Gets the evaluated log Directory.
Static Public Attributes
const string Section = "FileLogging"
The key for the Microsoft.Extensions.Configuration.IConfigurationSection the FileLoggingConfiguration resides in
Properties
string Directory [get, set]
Where log files are stored
bool Disable [get, set]
If file logging is disabled
LogLevel LogLevel = DefaultLogLevel [get, set]
The minimum Microsoft.Extensions.Logging.LogLevel to display in logs
LogLevel MicrosoftLogLevel = DefaultMicrosoftLogLevel [get, set]
The minimum Microsoft.Extensions.Logging.LogLevel to display in logs for Microsoft library sources
Static Private Attributes
const LogLevel DefaultLogLevel = LogLevel.Debug
Default value for LogLevel
const LogLevel DefaultMicrosoftLogLevel = LogLevel.Warning
Default value for MicrosoftLogLevel
Detailed Description
File logging configuration options
Definition at line 13 of file FileLoggingConfiguration.cs.
Member Function Documentation
GetFullLogDirectory()
string Tgstation.Server.Host.Configuration.FileLoggingConfiguration.GetFullLogDirectory (IIOManager ioManager, IAssemblyInformationProvider assemblyInformationProvider, IPlatformIdentifier platformIdentifier)
Gets the evaluated log Directory.
Parameters
ioManager The IIOManager to use.
assemblyInformationProvider The IAssemblyInformationProvider to use.
platformIdentifier The IPlatformIdentifier to use
Returns
The evaluated log Directory.
Definition at line 59 of file FileLoggingConfiguration.cs.
         {
             if (ioManager == null)
                 throw new ArgumentNullException(nameof(ioManager));
             if (assemblyInformationProvider == null)
                 throw new ArgumentNullException(nameof(assemblyInformationProvider));
             if (platformIdentifier == null)
                 throw new ArgumentNullException(nameof(platformIdentifier));
             var directoryToUse = platformIdentifier.IsWindows
                 ? Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData) // C:/ProgramData
                 : "/var/log"; // :pain:
             return !String.IsNullOrEmpty(Directory)
                 ? Directory
                 : ioManager.ConcatPath(
                     directoryToUse,
                     assemblyInformationProvider.VersionPrefix);
         }
References Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.Configuration.FileLoggingConfiguration.Directory, Tgstation.Server.Host.System.IPlatformIdentifier.IsWindows, and Tgstation.Server.Host.System.IAssemblyInformationProvider.VersionPrefix.
Referenced by Tgstation.Server.Host.Core.Application.ConfigureServices(), Tgstation.Server.Host.Controllers.AdministrationController.GetLog(), and Tgstation.Server.Host.Controllers.AdministrationController.ListLogs().
Member Data Documentation
DefaultLogLevel
const LogLevel Tgstation.Server.Host.Configuration.FileLoggingConfiguration.DefaultLogLevel = LogLevel.Debug static private
Default value for LogLevel
Definition at line 23 of file FileLoggingConfiguration.cs.
DefaultMicrosoftLogLevel
const LogLevel Tgstation.Server.Host.Configuration.FileLoggingConfiguration.DefaultMicrosoftLogLevel = LogLevel.Warning static private
Default value for MicrosoftLogLevel
Definition at line 28 of file FileLoggingConfiguration.cs.
Section
const string Tgstation.Server.Host.Configuration.FileLoggingConfiguration.Section = "FileLogging" static
The key for the Microsoft.Extensions.Configuration.IConfigurationSection the FileLoggingConfiguration resides in
Definition at line 18 of file FileLoggingConfiguration.cs.
Referenced by Tgstation.Server.Host.Setup.SetupWizard.SaveConfiguration().
Property Documentation
Directory
string Tgstation.Server.Host.Configuration.FileLoggingConfiguration.Directory get set
Where log files are stored
Definition at line 33 of file FileLoggingConfiguration.cs.
 { get; set; }
Referenced by Tgstation.Server.Host.Configuration.FileLoggingConfiguration.GetFullLogDirectory().
Disable
bool Tgstation.Server.Host.Configuration.FileLoggingConfiguration.Disable get set
If file logging is disabled
Definition at line 38 of file FileLoggingConfiguration.cs.
 { get; set; }
Referenced by Tgstation.Server.Host.Core.Application.ConfigureServices().
LogLevel
LogLevel Tgstation.Server.Host.Configuration.FileLoggingConfiguration.LogLevel = DefaultLogLevel get set
The minimum Microsoft.Extensions.Logging.LogLevel to display in logs
Definition at line 44 of file FileLoggingConfiguration.cs.
 { get; set; } = DefaultLogLevel;
Referenced by Tgstation.Server.Host.Core.Application.ConfigureServices().
MicrosoftLogLevel
LogLevel Tgstation.Server.Host.Configuration.FileLoggingConfiguration.MicrosoftLogLevel = DefaultMicrosoftLogLevel get set
The minimum Microsoft.Extensions.Logging.LogLevel to display in logs for Microsoft library sources
Definition at line 50 of file FileLoggingConfiguration.cs.
 { get; set; } = DefaultMicrosoftLogLevel;
Referenced by Tgstation.Server.Host.Core.Application.ConfigureServices().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Configuration/FileLoggingConfiguration.cs