tgstation-server: TGS.Interface.Helpers Class Reference
TGS.Interface.Helpers Class Reference
Helper functions used across the server suite
Static Public Member Functions
static string EncryptData (string cleartext, out string entropy)
Takes some cleartext and returns an encrypted version along with the entropy required to decrypt it
static string DecryptData (string ciphertext, string entropy)
Takes ciphertext and entropy from EncryptData(string, out string) and returns the cleartext. Note that this only works if the OS user of the program is the same one that called EncryptData(string, out string)
Detailed Description
Helper functions used across the server suite
Definition at line 10 of file Helpers.cs.
Member Function Documentation
static string TGS.Interface.Helpers.DecryptData (string ciphertext, string entropy) static
Takes ciphertext and entropy from EncryptData(string, out string) and returns the cleartext. Note that this only works if the OS user of the program is the same one that called EncryptData(string, out string)
Parameters
ciphertext A return value from a previous call to EncryptData(string, out string)
entropy The entropy parameter from the previous call to EncryptData(string, out string) that returned ciphertext
Returns
The decrypted string on sucess or on failure
Definition at line 37 of file Helpers.cs.
Referenced by TGS.ControlPanel.ControlPanel.InitServerPage(), TGS.Interface.RemoteLoginInfo.RemoteLoginInfo(), and TGS.Interface.Tests.TestHelpers.TestDecryptDataWorks().
         {
             try
             {
                 return Encoding.UTF8.GetString(ProtectedData.Unprotect(Convert.FromBase64String(ciphertext), Convert.FromBase64String(entropy), DataProtectionScope.CurrentUser));
             }
             catch
             {
                 return null;
             }
         }
static string TGS.Interface.Helpers.EncryptData (string cleartext, out string entropy) static
Takes some cleartext and returns an encrypted version along with the entropy required to decrypt it
Parameters
cleartext The string to encrypt
entropy The entropy required the decrypt the ciphertext
Returns
Ciphertext for the cleartext
Definition at line 18 of file Helpers.cs.
Referenced by TGS.Interface.Tests.TestHelpers.AssertEncryptData(), TGS.ControlPanel.GitHubLoginPrompt.LoginButton_Click(), and TGS.Interface.RemoteLoginInfo.ToJSON().
         {
             // Generate additional entropy (will be used as the Initialization vector)
             byte[] bentropy = new byte[20];
             using (var rng = new RNGCryptoServiceProvider())
                 rng.GetBytes(bentropy);
             byte[] ciphertext = ProtectedData.Protect(Encoding.UTF8.GetBytes(cleartext), bentropy, DataProtectionScope.CurrentUser);
             entropy = Convert.ToBase64String(bentropy, 0, bentropy.Length);
             return Convert.ToBase64String(ciphertext, 0, ciphertext.Length);
         }
The documentation for this class was generated from the following file:
TGS.Interface/Helpers.cs