tgstation-server: Tgstation.Server.Host.Components.Watchdog.BasicWatchdog Class Reference
Tgstation.Server.Host.Components.Watchdog.BasicWatchdog Class Reference
A IWatchdog that manages one server.
Public Member Functions
BasicWatchdog (IChatManager chat, ISessionControllerFactory sessionControllerFactory, IDmbFactory dmbFactory, ISessionPersistor sessionPersistor, IJobManager jobManager, IServerControl serverControl, IAsyncDelayer asyncDelayer, IIOManager diagnosticsIOManager, IEventConsumer eventConsumer, IRemoteDeploymentManagerFactory remoteDeploymentManagerFactory, IIOManager gameIOManager, ILogger< BasicWatchdog > logger, DreamDaemonLaunchParameters initialLaunchParameters, Api.Models.Instance instance, bool autoStart)
Initializes a new instance of the BasicWatchdog class.
override ValueTask ResetRebootState (CancellationToken cancellationToken)
Cancels pending graceful actions.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
sealed override ValueTask InstanceRenamed (string newInstanceName, CancellationToken cancellationToken)
Called when the owning Instance is renamed.
Parameters
newInstanceName The new Api.Models.NamedEntity.Name.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Public Member Functions inherited from Tgstation.Server.Host.Components.Watchdog.WatchdogBase
async ValueTask DisposeAsync ()
async ValueTask< bool > ChangeSettings (DreamDaemonLaunchParameters launchParameters, CancellationToken cancellationToken)
Changes the ActiveLaunchParameters. If currently running, may trigger a graceful restart.
Parameters
launchParameters The new DreamDaemonLaunchParameters. May be modified.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in true if a reboot is required, false otherwise.
async ValueTask< MessageContent > HandleChatCommand (string commandName, string arguments, ChatUser sender, CancellationToken cancellationToken)
Handle a chat command.
Parameters
commandName The command name.
arguments Everything typed after commandName minus leading spaces.
sender The sending ChatUser.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the MessageContent text to send back.
async ValueTask Launch (CancellationToken cancellationToken)
Start the IWatchdog.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
virtual async ValueTask ResetRebootState (CancellationToken cancellationToken)
Cancels pending graceful actions.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
async ValueTask Restart (bool graceful, CancellationToken cancellationToken)
Restarts the watchdog.
Parameters
graceful If true the restart will be delayed until a reboot is detected in the active server's DMAPI and this function will retrun immediately.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
async Task StartAsync (CancellationToken cancellationToken)
async Task StopAsync (CancellationToken cancellationToken)
async ValueTask Terminate (bool graceful, CancellationToken cancellationToken)
Stops the watchdog.
Parameters
graceful If true the termination will be delayed until a reboot is detected in the active server's DMAPI and this function will return immediately.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
async ValueTask HandleRestart (Version? updateVersion, bool handlerMayDelayShutdownWithExtremelyLongRunningTasks, CancellationToken cancellationToken)
Handle a restart of the server.
Parameters
updateVersion The Version being updated to, null if not being changed.
handlerMayDelayShutdownWithExtremelyLongRunningTasks If false the IRestartHandler should aim to complete the Task returned from this function ASAP.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
abstract ValueTask InstanceRenamed (string newInstanceName, CancellationToken cancellationToken)
Called when the owning Instance is renamed.
Parameters
newInstanceName The new Api.Models.NamedEntity.Name.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
async ValueTask CreateDump (CancellationToken cancellationToken)
Attempt to create a process dump for DreamDaemon.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
async ValueTask< bool > Broadcast (string message, CancellationToken cancellationToken)
Send a broadcast message to the DMAPI.
Parameters
message The message to broadcast.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in true if the broadcast succeeded., false otherwise.
ValueTask Launch (CancellationToken cancellationToken)
Start the IWatchdog.
ValueTask< bool > ChangeSettings (DreamDaemonLaunchParameters launchParameters, CancellationToken cancellationToken)
Changes the ActiveLaunchParameters. If currently running, may trigger a graceful restart.
ValueTask Restart (bool graceful, CancellationToken cancellationToken)
Restarts the watchdog.
ValueTask Terminate (bool graceful, CancellationToken cancellationToken)
Stops the watchdog.
ValueTask ResetRebootState (CancellationToken cancellationToken)
Cancels pending graceful actions.
ValueTask CreateDump (CancellationToken cancellationToken)
Attempt to create a process dump for DreamDaemon.
ValueTask< bool > Broadcast (string message, CancellationToken cancellationToken)
Send a broadcast message to the DMAPI.
ValueTask HandleEvent (EventType eventType, IEnumerable< string?> parameters, bool deploymentPipeline, CancellationToken cancellationToken)
Handle a given eventType .
ValueTask? HandleCustomEvent (string eventName, IEnumerable< string?> parameters, CancellationToken cancellationToken)
Handles a given custom event.
ValueTask InstanceRenamed (string newInstanceName, CancellationToken cancellationToken)
Called when the owning Instance is renamed.
ValueTask< MessageContent > HandleChatCommand (string commandName, string arguments, ChatUser sender, CancellationToken cancellationToken)
Handle a chat command.
ValueTask HandleRestart (Version? updateVersion, bool handlerMayDelayShutdownWithExtremelyLongRunningTasks, CancellationToken cancellationToken)
Handle a restart of the server.
Protected Member Functions
override async ValueTask< MonitorAction > HandleMonitorWakeup (MonitorActivationReason reason, CancellationToken cancellationToken)
Handles the actions to take when the monitor has to "wake up".
Parameters
activationReason The MonitorActivationReason that caused the invocation. Will never be MonitorActivationReason.HealthCheck.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the MonitorAction to take.
override async ValueTask DisposeAndNullControllersImpl ()
Call IDisposable.Dispose and null the fields for all ISessionControllers.
Returns
A ValueTask representing the running operation.
sealed override? ISessionController GetActiveController ()
Get the active ISessionController.
Returns
The active ISessionController, if any.
override async ValueTask InitController (ValueTask eventTask, ReattachInformation? reattachInfo, CancellationToken cancellationToken)
Starts all ISessionControllers.
Parameters
eventTask A, possibly active, Task for an event that's running.
reattachInfo ReattachInformation to use, if any.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
virtual ValueTask SessionStartupPersist (CancellationToken cancellationToken)
Called to save the current Server into the WatchdogBase.SessionPersistor when initially launched.
virtual ValueTask< MonitorAction > HandleNormalReboot (CancellationToken cancellationToken)
Handler for MonitorActivationReason.ActiveServerRebooted when the RebootState is RebootState.Normal.
virtual async ValueTask HandleNewDmbAvailable (CancellationToken cancellationToken)
Handler for MonitorActivationReason.NewDmbAvailable.
virtual ValueTask< IDmbProvider > PrepServerForLaunch (IDmbProvider dmbToUse, CancellationToken cancellationToken)
Prepare the server to launch a new instance with the WatchdogBase.ActiveLaunchParameters and a given dmbToUse .
Protected Member Functions inherited from Tgstation.Server.Host.Components.Watchdog.WatchdogBase
WatchdogBase (IChatManager chat, ISessionControllerFactory sessionControllerFactory, IDmbFactory dmbFactory, ISessionPersistor sessionPersistor, IJobManager jobManager, IServerControl serverControl, IAsyncDelayer asyncDelayer, IIOManager diagnosticsIOManager, IEventConsumer eventConsumer, IRemoteDeploymentManagerFactory remoteDeploymentManagerFactory, IIOManager gameIOManager, ILogger< WatchdogBase > logger, DreamDaemonLaunchParameters initialLaunchParameters, Api.Models.Instance metadata, bool autoStart)
Initializes a new instance of the WatchdogBase class.
abstract ValueTask InitController (ValueTask eventTask, ReattachInformation? reattachInfo, CancellationToken cancellationToken)
Starts all ISessionControllers.
async ValueTask LaunchNoLock (bool startMonitor, bool announce, bool announceFailure, ReattachInformation? reattachInfo, CancellationToken cancellationToken)
Launches the watchdog.
async ValueTask< bool > StopMonitor ()
Stops MonitorLifetimes(CancellationToken). Doesn't kill the servers.
async ValueTask CheckLaunchResult (ISessionController controller, string serverName, CancellationToken cancellationToken)
Check the LaunchResult of a given controller for errors and throw a JobException if any are detected.
async ValueTask ReattachFailure (CancellationToken cancellationToken)
Call from InitController(ValueTask, ReattachInformation, CancellationToken) when a reattach operation fails to attempt a fresh start.
abstract ValueTask DisposeAndNullControllersImpl ()
Call IDisposable.Dispose and null the fields for all ISessionControllers.
async ValueTask DisposeAndNullControllers (CancellationToken cancellationToken)
Wrapper for DisposeAndNullControllersImpl under a locked context.
abstract ? ISessionController GetActiveController ()
Get the active ISessionController.
abstract ValueTask< MonitorAction > HandleMonitorWakeup (MonitorActivationReason activationReason, CancellationToken cancellationToken)
Handles the actions to take when the monitor has to "wake up".
async ValueTask BeforeApplyDmb (Models.CompileJob newCompileJob, CancellationToken cancellationToken)
To be called before a given newCompileJob goes live.
async ValueTask HandleEventImpl (EventType eventType, IEnumerable< string > parameters, bool relayToSession, CancellationToken cancellationToken)
Handle a given eventType without re-throwing errors.
Properties
sealed override bool AlphaIsActive [get]
If the alpha server is the active server.
sealed override? RebootState RebootState [get]
The Session.RebootState of the active server.
ISessionController? Server [get, private set]
The single ISessionController.
Properties inherited from Tgstation.Server.Host.Components.Watchdog.WatchdogBase
long? SessionId [get]
An incrementing ID for representing current server execution.
WatchdogStatus Status [get, protected set]
The current WatchdogStatus.
abstract bool AlphaIsActive [get]
If the alpha server is the active server.
DreamDaemonLaunchParameters ActiveLaunchParameters [get, protected set]
The DreamDaemonLaunchParameters to be applied.
DreamDaemonLaunchParameters? LastLaunchParameters [get, protected set]
The DreamDaemonLaunchParameters the active server is using. This may not be the exact same as ActiveLaunchParameters but still be associated with the same session.
Models.? CompileJob ActiveCompileJob [get]
Retrieves the Models.CompileJob currently running on the server.
abstract ? RebootState RebootState [get]
The Session.RebootState of the active server.
ISessionPersistor SessionPersistor [get]
The ISessionPersistor for the WatchdogBase.
ILogger< WatchdogBase > Logger [get]
The ILogger for the WatchdogBase.
IChatManager Chat [get]
The IChatManager for the WatchdogBase.
ISessionControllerFactory SessionControllerFactory [get]
The ISessionControllerFactory for the WatchdogBase.
IDmbFactory DmbFactory [get]
The IDmbFactory for the WatchdogBase.
IAsyncDelayer AsyncDelayer [get]
The IAsyncDelayer for the WatchdogBase.
IIOManager GameIOManager [get]
The IIOManager for the WatchdogBase pointing to the Game directory.
Properties inherited from Tgstation.Server.Host.Components.Watchdog.IWatchdog
long? SessionId [get]
An incrementing ID for representing current server execution.
WatchdogStatus Status [get]
The current WatchdogStatus.
bool AlphaIsActive [get]
If the alpha server is the active server.
Models.? CompileJob ActiveCompileJob [get]
Retrieves the Models.CompileJob currently running on the server.
DreamDaemonLaunchParameters ActiveLaunchParameters [get]
The DreamDaemonLaunchParameters to be applied.
DreamDaemonLaunchParameters? LastLaunchParameters [get]
The DreamDaemonLaunchParameters the active server is using.
RebootState? RebootState [get]
The Session.RebootState of the active server.
Private Attributes
bool gracefulRebootRequired
If the server is set to gracefully reboot due to a pending dmb or settings change.
Detailed Description
A IWatchdog that manages one server.
Definition at line 25 of file BasicWatchdog.cs.
Constructor & Destructor Documentation
BasicWatchdog()
Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.BasicWatchdog (IChatManager chat, ISessionControllerFactory sessionControllerFactory, IDmbFactory dmbFactory, ISessionPersistor sessionPersistor, IJobManager jobManager, IServerControl serverControl, IAsyncDelayer asyncDelayer, IIOManager diagnosticsIOManager, IEventConsumer eventConsumer, IRemoteDeploymentManagerFactory remoteDeploymentManagerFactory, IIOManager gameIOManager, ILogger< BasicWatchdog > logger, DreamDaemonLaunchParameters initialLaunchParameters, Api.Models.Instance instance, bool autoStart)
Initializes a new instance of the BasicWatchdog class.
Parameters
chat The IChatManager for the WatchdogBase.
sessionControllerFactory The ISessionControllerFactory for the WatchdogBase.
dmbFactory The IDmbFactory for the WatchdogBase.
sessionPersistor The ISessionPersistor for the WatchdogBase.
jobManager The IJobManager for the WatchdogBase.
serverControl The IServerControl for the WatchdogBase.
asyncDelayer The IAsyncDelayer for the WatchdogBase.
diagnosticsIOManager The 'Diagnostics' IIOManager for the WatchdogBase.
eventConsumer The IEventConsumer for the WatchdogBase.
remoteDeploymentManagerFactory The IRemoteDeploymentManagerFactory for the WatchdogBase.
gameIOManager The 'Game' IIOManager for the WatchdogBase.
logger The ILogger for the WatchdogBase.
initialLaunchParameters The DreamDaemonLaunchParameters for the WatchdogBase.
instance The Api.Models.Instance for the WatchdogBase.
autoStart The autostart value for the WatchdogBase.
Definition at line 61 of file BasicWatchdog.cs.
            : base(
                 chat,
                 sessionControllerFactory,
                 dmbFactory,
                 sessionPersistor,
                 jobManager,
                 serverControl,
                 asyncDelayer,
                 diagnosticsIOManager,
                 eventConsumer,
                 remoteDeploymentManagerFactory,
                 gameIOManager,
                 logger,
                 initialLaunchParameters,
                 instance,
                 autoStart)
        {
        }
Member Function Documentation
DisposeAndNullControllersImpl()
override async ValueTask Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.DisposeAndNullControllersImpl () protected virtual
Call IDisposable.Dispose and null the fields for all ISessionControllers.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Watchdog.WatchdogBase.
Definition at line 195 of file BasicWatchdog.cs.
        {
            var disposeTask = Server?.DisposeAsync();
            gracefulRebootRequired = false;
            if (!disposeTask.HasValue)
                return;
            await disposeTask.Value;
            Server = null;
        }
References Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.gracefulRebootRequired.
GetActiveController()
sealed override? ISessionController Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.GetActiveController () protected virtual
Get the active ISessionController.
Returns
The active ISessionController, if any.
Implements Tgstation.Server.Host.Components.Watchdog.WatchdogBase.
HandleMonitorWakeup()
override async ValueTask< MonitorAction > Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.HandleMonitorWakeup (MonitorActivationReason reason, CancellationToken cancellationToken) protected virtual
Handles the actions to take when the monitor has to "wake up".
Parameters
activationReason The MonitorActivationReason that caused the invocation. Will never be MonitorActivationReason.HealthCheck.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the MonitorAction to take.
Implements Tgstation.Server.Host.Components.Watchdog.WatchdogBase.
Definition at line 110 of file BasicWatchdog.cs.
        {
            var controller = Server!;
            switch (reason)
            {
                case MonitorActivationReason.ActiveServerCrashed:
                    var eventType = controller.TerminationWasIntentional
                        ? EventType.WorldEndProcess
                        : EventType.WatchdogCrash;
                    await HandleEventImpl(eventType, Enumerable.Empty<string>(), false, cancellationToken);
                    var exitWord = controller.TerminationWasIntentional ? "exited" : "crashed";
                    if (controller.RebootState == Session.RebootState.Shutdown)
                    {
                        // the time for graceful shutdown is now
                        Chat.QueueWatchdogMessage(
                            String.Format(
                                CultureInfo.InvariantCulture,
                                "Server {0}! Shutting down due to graceful termination request...",
                                exitWord));
                        return MonitorAction.Exit;
                    }
                    Chat.QueueWatchdogMessage(
                        String.Format(
                            CultureInfo.InvariantCulture,
                            "Server {0}! Rebooting...",
                            exitWord));
                    return MonitorAction.Restart;
                case MonitorActivationReason.ActiveServerRebooted:
                    var rebootState = controller.RebootState;
                    if (gracefulRebootRequired && rebootState == Session.RebootState.Normal)
                    {
                        Logger.LogError("Watchdog reached normal reboot state with gracefulRebootRequired set!");
                        rebootState = Session.RebootState.Restart;
                    }
                    gracefulRebootRequired = false;
                    controller.ResetRebootState();
                    var eventTask = HandleEventImpl(EventType.WorldReboot, Enumerable.Empty<string>(), false, cancellationToken);
                    try
                    {
                        switch (rebootState)
{
                            case Session.RebootState.Normal:
                                return await HandleNormalReboot(cancellationToken);
                            case Session.RebootState.Restart:
                                return MonitorAction.Restart;
                            case Session.RebootState.Shutdown:
                                // graceful shutdown time
                                Chat.QueueWatchdogMessage(
                                    "Active server rebooted! Shutting down due to graceful termination request...");
                                return MonitorAction.Exit;
                            default:
                                throw new InvalidOperationException($"Invalid reboot state: {rebootState}");
                        }
                    }
                    finally
                    {
                        await eventTask;
                    }
                case MonitorActivationReason.ActiveLaunchParametersUpdated:
                    await controller.SetRebootState(Session.RebootState.Restart, cancellationToken);
                    gracefulRebootRequired = true;
                    break;
                case MonitorActivationReason.NewDmbAvailable:
                    await HandleNewDmbAvailable(cancellationToken);
                    break;
                case MonitorActivationReason.ActiveServerPrimed:
                    await HandleEventImpl(EventType.WorldPrime, Enumerable.Empty<string>(), false, cancellationToken);
                    break;
                case MonitorActivationReason.ActiveServerStartup:
                    Status = Api.Models.WatchdogStatus.Online;
                    break;
                case MonitorActivationReason.HealthCheck:
                default:
                    throw new InvalidOperationException($"Invalid activation reason: {reason}");
            }
            return MonitorAction.Continue;
        }
References Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Chat, Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.gracefulRebootRequired, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleEventImpl(), Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.HandleNewDmbAvailable(), Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.HandleNormalReboot(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Logger, Tgstation.Server.Host.Components.Chat.IChatManager.QueueWatchdogMessage(), and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Status.
HandleNewDmbAvailable()
virtual async ValueTask Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.HandleNewDmbAvailable (CancellationToken cancellationToken) protected virtual
Handler for MonitorActivationReason.NewDmbAvailable.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Reimplemented in Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.
Definition at line 312 of file BasicWatchdog.cs.
        {
            gracefulRebootRequired = true;
            if (Server!.CompileJob.DMApiVersion == null)
            {
                Chat.QueueWatchdogMessage(
                    "A new deployment has been made but cannot be applied automatically as the currently running server has no DMAPI. Please manually reboot the server to apply the update.");
                return;
            }
            await Server.SetRebootState(Session.RebootState.Restart, cancellationToken);
        }
References Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Chat, Tgstation.Server.Api.Models.Internal.CompileJob.DMApiVersion, Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.gracefulRebootRequired, and Tgstation.Server.Host.Components.Chat.IChatManager.QueueWatchdogMessage().
Referenced by Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.HandleMonitorWakeup().
HandleNormalReboot()
virtual ValueTask< MonitorAction > Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.HandleNormalReboot (CancellationToken cancellationToken) protected virtual
Handler for MonitorActivationReason.ActiveServerRebooted when the RebootState is RebootState.Normal.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the MonitorAction to take.
Reimplemented in Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.
Definition at line 299 of file BasicWatchdog.cs.
        {
            if (Server!.CompileJob.DMApiVersion != null)
                Status = Api.Models.WatchdogStatus.Restoring;
            return ValueTask.FromResult(MonitorAction.Continue);
        }
References Tgstation.Server.Api.Models.Internal.CompileJob.DMApiVersion, and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Status.
Referenced by Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.HandleMonitorWakeup().
InitController()
override async ValueTask Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.InitController (ValueTask eventTask, ReattachInformation? reattachInfo, CancellationToken cancellationToken) protected virtual
Starts all ISessionControllers.
Parameters
eventTask A, possibly active, Task for an event that's running.
reattachInfo ReattachInformation to use, if any.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implements Tgstation.Server.Host.Components.Watchdog.WatchdogBase.
Definition at line 210 of file BasicWatchdog.cs.
        {
            // don't need a new dmb if reattaching
            var reattachInProgress = reattachInfo != null;
            var dmbToUse = reattachInProgress ? null : DmbFactory.LockNextDmb("Watchdog initialization");
            // if this try catches something, both servers are killed
            try
            {
                // start the alpha server task, either by launch a new process or attaching to an existing one
                // The tasks returned are mainly for writing interop files to the directories among other things and should generally never fail
                // The tasks pertaining to server startup times are in the ISessionControllers
                if (!reattachInProgress)
                {
                    Logger.LogTrace("Initializing controller with CompileJob {compileJobId}...", dmbToUse!.CompileJob.Id);
                    await BeforeApplyDmb(dmbToUse.CompileJob, cancellationToken);
                    dmbToUse = await PrepServerForLaunch(dmbToUse, cancellationToken);
                    await eventTask;
                    Server = await SessionControllerFactory.LaunchNew(
                        dmbToUse,
                        null,
                        ActiveLaunchParameters,
                        false,
                        cancellationToken);
                }
                else
                {
                    await eventTask;
                    Server = await SessionControllerFactory.Reattach(reattachInfo!, cancellationToken);
                }
                // possiblity of null servers due to failed reattaches
                if (Server == null)
                {
                    await ReattachFailure(
                        cancellationToken);
                    return;
                }
                if (!reattachInProgress)
                    await SessionStartupPersist(cancellationToken);
                if (!SessionId.HasValue)
                    Logger.LogError("Server should have a session ID allocated by now but it doesn't!");
                else
                    Logger.LogInformation("Watchdog starting session ID {id}", SessionId.Value);
                await CheckLaunchResult(Server, "Server", cancellationToken);
                // persist again, because the DMAPI can say we need a different topic port (Original OD behavior)
                // kinda hacky imo, but at least we can safely forget about this
                if (!reattachInProgress)
                    await SessionPersistor.Update(Server.ReattachInformation, cancellationToken);
            }
            catch (Exception ex)
            {
                Logger.LogTrace(ex, "Controller initialization failure!");
                // kill the controllers
                bool serverWasActive = Server != null;
                // DCT: Operation must always run
                await DisposeAndNullControllers(CancellationToken.None);
                // server didn't get control of this dmb
                if (dmbToUse != null && !serverWasActive)
                    await dmbToUse.DisposeAsync();
                throw;
            }
        }
References Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ActiveLaunchParameters, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.BeforeApplyDmb(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.CheckLaunchResult(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.DisposeAndNullControllers(), Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Host.Components.Session.SessionControllerFactory.LaunchNew(), Tgstation.Server.Host.Components.Deployment.DmbFactory.LockNextDmb(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Logger, Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.PrepServerForLaunch(), Tgstation.Server.Host.Components.Session.SessionControllerFactory.Reattach(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ReattachFailure(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.SessionId, Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.SessionStartupPersist(), and Tgstation.Server.Host.Components.Session.SessionPersistor.Update().
InstanceRenamed()
sealed override ValueTask Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.InstanceRenamed (string newInstanceName, CancellationToken cancellationToken) virtual
Called when the owning Instance is renamed.
Parameters
newInstanceName The new Api.Models.NamedEntity.Name.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Watchdog.WatchdogBase.
PrepServerForLaunch()
virtual ValueTask< IDmbProvider > Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.PrepServerForLaunch (IDmbProvider dmbToUse, CancellationToken cancellationToken) protected virtual
Prepare the server to launch a new instance with the WatchdogBase.ActiveLaunchParameters and a given dmbToUse .
Parameters
dmbToUse The IDmbProvider to be launched. Will not be disposed by this function.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the modified IDmbProvider to be used.
Reimplemented in Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.
Referenced by Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.InitController().
ResetRebootState()
override ValueTask Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.ResetRebootState (CancellationToken cancellationToken) virtual
Cancels pending graceful actions.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Reimplemented from Tgstation.Server.Host.Components.Watchdog.WatchdogBase.
Definition at line 97 of file BasicWatchdog.cs.
        {
            if (!gracefulRebootRequired)
                return base.ResetRebootState(cancellationToken);
            return Restart(true, cancellationToken);
        }
References Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.gracefulRebootRequired, and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Restart().
SessionStartupPersist()
virtual ValueTask Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.SessionStartupPersist (CancellationToken cancellationToken) protected virtual
Called to save the current Server into the WatchdogBase.SessionPersistor when initially launched.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Reimplemented in Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.
Referenced by Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.InitController().
Member Data Documentation
gracefulRebootRequired
bool Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.gracefulRebootRequired private
If the server is set to gracefully reboot due to a pending dmb or settings change.
Definition at line 41 of file BasicWatchdog.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.DisposeAndNullControllersImpl(), Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.HandleMonitorWakeup(), Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.HandleNewDmbAvailable(), and Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.ResetRebootState().
Property Documentation
AlphaIsActive
sealed override bool Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.AlphaIsActive get
If the alpha server is the active server.
Implements Tgstation.Server.Host.Components.Watchdog.IWatchdog.
Definition at line 28 of file BasicWatchdog.cs.
RebootState
sealed override? RebootState Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.RebootState get
The Session.RebootState of the active server.
Implements Tgstation.Server.Host.Components.Watchdog.IWatchdog.
Definition at line 31 of file BasicWatchdog.cs.
Server
ISessionController? Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.Server get private set protected
The single ISessionController.
Definition at line 36 of file BasicWatchdog.cs.
{ get; private set; }
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Watchdog/BasicWatchdog.cs