tgstation-server: TGS.Interface.Command Class Reference
TGS.Interface.Command Class Reference abstract
Helper for creating a text Command tree
Public Types
enum ExitCode : int { ExitCode.Normal = 0, ExitCode.ConnectionError = 1, ExitCode.BadCommand = 2, ExitCode.ServerError = 3 }
Exit codes for Commands
Public Member Functions
virtual ExitCode DoRun (IList< string > parameters)
Caller of Run(IList<string>), can be used to modify the root behaviour of the Command
virtual void PrintHelp ()
Prints usage text of the Command to the invoker
virtual string GetArgumentString ()
Override to add argument text to the Command Format is <required> <arguments> [optional] [arguments]
abstract string GetHelpText ()
Override to add usage text to the Command
Static Public Attributes
static ThreadLocal< Action< string > > OutputProcVar = new ThreadLocal<Action<string>>()
Proc that will show a message to the Command invoker. Do not call directly, use OutputProc(string) instead
Protected Member Functions
abstract ExitCode Run (IList< string > parameters)
Override to do the actions of the Command
Static Protected Member Functions
static void OutputProc (string message)
Write output to the Command invoker
Properties
string Keyword [get, protected set]
The text that invokes this Command. Set in constructor
int RequiredParameters [get, protected set]
The number of parameters this Command requires. Set in Constructor
Detailed Description
Helper for creating a text Command tree
Definition at line 10 of file Command.cs.
Member Enumeration Documentation
enum TGS.Interface.Command.ExitCode : int strong
Exit codes for Commands
Enumerator
Normal
The Command ran successfully
ConnectionError
The connection to the service was interrupted during the Command
BadCommand
Invalid parameters for Command
ServerError
The command failed due to conditions on the service
Definition at line 15 of file Command.cs.
                              : int
         {
             Normal = 0,
             ConnectionError = 1,
             BadCommand = 2,
             ServerError = 3,
         }
Member Function Documentation
virtual ExitCode TGS.Interface.Command.DoRun (IList< string > parameters) virtual
Caller of Run(IList<string>), can be used to modify the root behaviour of the Command
Parameters
parameters List of parameters passed to the Command
Returns
An ExitCode describing the execution of the Command
Reimplemented in TGS.Server.ChatCommands.ChatCommand.
Definition at line 59 of file Command.cs.
Referenced by TGS.Server.Instance.ChatProvider_OnChatMessage(), and TGS.CommandLine.Program.RunCommandLine().
         {
             return Run(parameters);
         }
virtual string TGS.Interface.Command.GetArgumentString () virtual
Override to add argument text to the Command Format is <required> <arguments> [optional] [arguments]
Returns
Formatted argument text for the Command
Reimplemented in TGS.CommandLine.DiscordSetTokenCommand, TGS.CommandLine.IRCServerCommand, TGS.CommandLine.IRCAuthCommand, TGS.CommandLine.ChatDeadminCommand, TGS.CommandLine.IRCAuthLevelCommand, TGS.CommandLine.ServiceRenameInstanceCommand, TGS.CommandLine.DiscordAuthModeCommand, TGS.CommandLine.ServiceSetRemoteAccessPortCommand, TGS.CommandLine.IRCAuthModeCommand, TGS.CommandLine.RepoMergePRCommand, TGS.CommandLine.DDSecurityCommand, TGS.CommandLine.ChatAddminCommand, TGS.CommandLine.ServiceDisableInstanceCommand, TGS.CommandLine.RepoSetNameCommand, TGS.CommandLine.RepoSetEmailCommand, TGS.CommandLine.DDPortCommand, TGS.CommandLine.ServiceEnableInstanceCommand, TGS.CommandLine.ServiceSetPythonPathCommand, TGS.CommandLine.DDWebclientCommand, TGS.CommandLine.RepoUpdateCommand, TGS.CommandLine.DDAutostartCommand, TGS.CommandLine.TestmergeCommand, TGS.CommandLine.RepoResetCommand, TGS.CommandLine.ConfigUploadCommand, TGS.CommandLine.DMInitializeCommand, TGS.CommandLine.ServiceImportInstanceCommand, TGS.CommandLine.ChatPartCommand, TGS.CommandLine.UpdateCommand, TGS.CommandLine.DMSetProjectNameCommand, TGS.CommandLine.BYONDUpdateCommand, TGS.CommandLine.ConfigDownloadCommand, TGS.CommandLine.ServiceDetachInstanceCommand, TGS.CommandLine.DDRestartCommand, TGS.CommandLine.RepoSetupCommand, TGS.CommandLine.DDStopCommand, TGS.CommandLine.AdminSetGroupCommand, TGS.CommandLine.ChatJoinCommand, TGS.CommandLine.DMCompileCommand, TGS.CommandLine.ConfigListCommand, TGS.CommandLine.SetAutoUpdateCommand, TGS.CommandLine.ServiceCreateInstanceCommand, TGS.CommandLine.IRCNickCommand, TGS.Server.ChatCommands.ByondCommand, TGS.CommandLine.BYONDVersionCommand, TGS.CommandLine.ConfigDeleteCommand, TGS.CommandLine.DDWorldAnnounceCommand, and TGS.CommandLine.RepoSetPushTestmergeCommitsCommand.
Definition at line 82 of file Command.cs.
         {
             return "";
         }
abstract string TGS.Interface.Command.GetHelpText () pure virtual
Override to add usage text to the Command
Returns
Formatted usage text for the Command
Implemented in TGS.CommandLine.DiscordSetTokenCommand, TGS.CommandLine.IRCServerCommand, TGS.CommandLine.ChatDisableCommand, TGS.CommandLine.ChatEnableCommand, TGS.CommandLine.ChatStatusCommand, TGS.CommandLine.IRCDisableAuthCommand, TGS.CommandLine.IRCAuthCommand, TGS.CommandLine.ChatDeadminCommand, TGS.CommandLine.IRCAuthLevelCommand, TGS.CommandLine.ServiceRenameInstanceCommand, TGS.CommandLine.RepoCheckoutCommand, TGS.CommandLine.DiscordAuthModeCommand, TGS.CommandLine.RepoListBackupsCommand, TGS.CommandLine.ServiceSetRemoteAccessPortCommand, TGS.CommandLine.IRCAuthModeCommand, TGS.CommandLine.RepoListPRsCommand, TGS.CommandLine.ServiceRemoteAccessPortCommand, TGS.CommandLine.RepoMergePRCommand, TGS.CommandLine.DDSecurityCommand, TGS.CommandLine.ChatAddminCommand, TGS.CommandLine.RepoSetNameCommand, TGS.CommandLine.ServiceDisableInstanceCommand, TGS.CommandLine.ChatReconnectCommand, TGS.CommandLine.RepoSetEmailCommand, TGS.CommandLine.DDPortCommand, TGS.CommandLine.ServiceEnableInstanceCommand, TGS.CommandLine.RepoPushChangelogCommand, TGS.CommandLine.RepoGenChangelogCommand, TGS.CommandLine.DDWebclientCommand, TGS.CommandLine.ServiceSetPythonPathCommand, TGS.CommandLine.ChatListAdminsCommand, TGS.CommandLine.DMCancelCommand, TGS.CommandLine.RepoUpdateCommand, TGS.CommandLine.DDAutostartCommand, TGS.CommandLine.ServicePythonPathCommand, TGS.CommandLine.TestmergeCommand, TGS.CommandLine.RepoResetCommand, TGS.CommandLine.ConfigUploadCommand, TGS.CommandLine.DMInitializeCommand, TGS.CommandLine.RepoStatusCommand, TGS.CommandLine.ChatPartCommand, TGS.CommandLine.ServiceImportInstanceCommand, TGS.CommandLine.DDStatusCommand, TGS.CommandLine.UpdateCommand, TGS.CommandLine.DMSetProjectNameCommand, TGS.CommandLine.BYONDUpdateCommand, TGS.CommandLine.ConfigDownloadCommand, TGS.CommandLine.DDRestartCommand, TGS.CommandLine.DMStatusCommand, TGS.CommandLine.ServiceDetachInstanceCommand, TGS.CommandLine.RepoSetupCommand, TGS.Interface.RootCommand, TGS.CommandLine.AdminClearGroupCommand, TGS.CommandLine.ConfigServerDirectoryCommand, TGS.CommandLine.BYONDStatusCommand, TGS.CommandLine.ServiceListInstancesCommand, TGS.CommandLine.DDStopCommand, TGS.CommandLine.ChatJoinCommand, TGS.CommandLine.DMCompileCommand, TGS.CommandLine.AdminSetGroupCommand, TGS.CommandLine.RepoUpdateJsonCommand, TGS.CommandLine.SetAutoUpdateCommand, TGS.CommandLine.ConfigListCommand, TGS.CommandLine.DDStartCommand, TGS.CommandLine.AdminViewGroupCommand, TGS.CommandLine.ServiceCreateInstanceCommand, TGS.CommandLine.BYONDVersionCommand, TGS.CommandLine.IRCNickCommand, TGS.CommandLine.ConfigDeleteCommand, TGS.Server.ChatCommands.PullRequestsCommand, TGS.CommandLine.AdminRecreateStaticCommand, TGS.Server.ChatCommands.ByondCommand, TGS.CommandLine.AutoUpdateCommand, TGS.Server.ChatCommands.RevisionCommand, TGS.Server.ChatCommands.ServerChatCommand, TGS.CommandLine.DDWorldAnnounceCommand, TGS.CommandLine.RepoSetPushTestmergeCommitsCommand, TGS.CommandLine.DiscordCommand, TGS.Server.ChatCommands.KekCommand, TGS.Server.ChatCommands.VersionCommand, TGS.CommandLine.ServiceCommand, TGS.CommandLine.BYONDCommand, TGS.CommandLine.ConfigCommand, TGS.CommandLine.DMCommand, TGS.CommandLine.IRCCommand, TGS.CommandLine.DDCommand, TGS.CommandLine.RepoCommand, and TGS.CommandLine.AdminCommand.
static void TGS.Interface.Command.OutputProc (string message) static protected
Write output to the Command invoker
Parameters
message The output to display
Definition at line 42 of file Command.cs.
         {
             OutputProcVar.Value(message);
         }
virtual void TGS.Interface.Command.PrintHelp () virtual
Prints usage text of the Command to the invoker
Reimplemented in TGS.Interface.RootCommand, and TGS.CommandLine.CLICommand.
Definition at line 72 of file Command.cs.
         {
             var argstr = GetArgumentString();
             OutputProc(String.Format("{0} {1}- {2}", Keyword, argstr.Length > 0 ? argstr + " " : "", GetHelpText()));
         }
abstract ExitCode TGS.Interface.Command.Run (IList< string > parameters) protected pure virtual
Override to do the actions of the Command
Parameters
parameters List of string parameters passed to the Command. Guaranteed to have at least RequiredParameters non-empty/whitespace entries
Returns
An ExitCode describing the execution of the Command
Implemented in TGS.CommandLine.DiscordSetTokenCommand, TGS.CommandLine.IRCServerCommand, TGS.CommandLine.ChatDisableCommand, TGS.CommandLine.ChatEnableCommand, TGS.CommandLine.ChatStatusCommand, TGS.CommandLine.IRCDisableAuthCommand, TGS.CommandLine.IRCAuthCommand, TGS.CommandLine.ChatDeadminCommand, TGS.CommandLine.IRCAuthLevelCommand, TGS.CommandLine.ServiceRenameInstanceCommand, TGS.CommandLine.RepoCheckoutCommand, TGS.CommandLine.DiscordAuthModeCommand, TGS.CommandLine.RepoListBackupsCommand, TGS.CommandLine.ServiceSetRemoteAccessPortCommand, TGS.CommandLine.IRCAuthModeCommand, TGS.CommandLine.RepoListPRsCommand, TGS.CommandLine.ServiceRemoteAccessPortCommand, TGS.CommandLine.ChatAddminCommand, TGS.CommandLine.RepoMergePRCommand, TGS.CommandLine.ServiceDisableInstanceCommand, TGS.CommandLine.RepoSetNameCommand, TGS.CommandLine.ChatReconnectCommand, TGS.CommandLine.DDSecurityCommand, TGS.CommandLine.ServiceEnableInstanceCommand, TGS.CommandLine.RepoSetEmailCommand, TGS.CommandLine.DDPortCommand, TGS.CommandLine.RepoPushChangelogCommand, TGS.CommandLine.ServiceSetPythonPathCommand, TGS.CommandLine.RepoGenChangelogCommand, TGS.CommandLine.ChatListAdminsCommand, TGS.CommandLine.DMCancelCommand, TGS.CommandLine.DDWebclientCommand, TGS.CommandLine.ServicePythonPathCommand, TGS.CommandLine.RepoUpdateCommand, TGS.CommandLine.DDAutostartCommand, TGS.CommandLine.RepoResetCommand, TGS.CommandLine.DMInitializeCommand, TGS.CommandLine.ServiceImportInstanceCommand, TGS.CommandLine.ChatPartCommand, TGS.CommandLine.TestmergeCommand, TGS.CommandLine.ConfigUploadCommand, TGS.CommandLine.DDStatusCommand, TGS.CommandLine.DMSetProjectNameCommand, TGS.CommandLine.ServiceDetachInstanceCommand, TGS.CommandLine.RepoStatusCommand, TGS.CommandLine.DDRestartCommand, TGS.CommandLine.ConfigDownloadCommand, TGS.CommandLine.AdminClearGroupCommand, TGS.CommandLine.BYONDUpdateCommand, TGS.CommandLine.DMStatusCommand, TGS.CommandLine.UpdateCommand, TGS.CommandLine.ConfigServerDirectoryCommand, TGS.CommandLine.ServiceListInstancesCommand, TGS.CommandLine.RepoSetupCommand, TGS.CommandLine.DDStopCommand, TGS.CommandLine.ChatJoinCommand, TGS.CommandLine.AdminSetGroupCommand, TGS.CommandLine.RepoUpdateJsonCommand, TGS.CommandLine.ConfigListCommand, TGS.CommandLine.SetAutoUpdateCommand, TGS.CommandLine.DDStartCommand, TGS.CommandLine.BYONDStatusCommand, TGS.CommandLine.ServiceCreateInstanceCommand, TGS.CommandLine.AdminViewGroupCommand, TGS.CommandLine.IRCNickCommand, TGS.CommandLine.DDWorldAnnounceCommand, TGS.Server.ChatCommands.ServerChatCommand, TGS.CommandLine.RepoSetPushTestmergeCommitsCommand, TGS.CommandLine.AutoUpdateCommand, TGS.CommandLine.ConfigDeleteCommand, TGS.CommandLine.DMCompileCommand, TGS.CommandLine.BYONDVersionCommand, TGS.CommandLine.AdminRecreateStaticCommand, TGS.Interface.RootCommand, TGS.Server.ChatCommands.ByondCommand, TGS.Server.ChatCommands.KekCommand, TGS.Server.ChatCommands.PullRequestsCommand, TGS.Server.ChatCommands.RevisionCommand, and TGS.Server.ChatCommands.VersionCommand.
Member Data Documentation
ThreadLocal<Action<string> > TGS.Interface.Command.OutputProcVar = new ThreadLocal<Action<string>>() static
Proc that will show a message to the Command invoker. Do not call directly, use OutputProc(string) instead
Definition at line 37 of file Command.cs.
Referenced by TGS.Server.Instance.ChatProvider_OnChatMessage(), TGS.CommandLine.Program.Main(), and TGServiceTests.OutputProcOverriderTest.Setup().
Property Documentation
string TGS.Interface.Command.Keyword get protected set
The text that invokes this Command. Set in constructor
Definition at line 49 of file Command.cs.
int TGS.Interface.Command.RequiredParameters get protected set
The number of parameters this Command requires. Set in Constructor
Definition at line 53 of file Command.cs.
The documentation for this class was generated from the following file:
TGS.Interface/Command.cs