tgstation-server: TGServerService.ServerInstance Class Reference
TGServerService.ServerInstance Class Reference
The class which holds all interface components. There are no safeguards for call race conditions so these must be guarded against internally
Public Member Functions
string GetCurrentAuthorizedGroup ()
Returns the name of the windows group allowed to use the service other than administrator
string SetAuthorizedGroup (string groupName)
Searches the windows machine for the group named groupName , sets it as the authorized group if it's found
string RecreateStaticFolder ()
Renames the current static folder to a backup name and recreates is from the current repo using TGS3.json
ByondStatus CurrentStatus ()
Gets the current status of any BYOND updates
string GetError ()
Check the last update error. Checking this will clear the value
string GetVersion (ByondVersion type)
Get the currently installed version as a string formatted as Major.Minor
void UpdateToVersionImpl (object param)
Downloads and unzips a BYOND revision. Calls ApplyStagedUpdate afterwards if the ServerInstance isn't running, otherwise, calls RequestRestart. Sets lastError on failure
bool UpdateToVersion (int major, int minor)
updates the used byond version to that of version major .minor . The change won't take place until DD reboots. Calls ITGDreamDaemon.RequestRestart if blocked by a running DD instance. Runs asyncronously, use CurrentStatus to check progress
void InitChat ()
Set up the ChatProviders for the ServerInstance
IList< ChatSetupInfo > ProviderInfos ()
Returns ChatSetupInfo for all ChatProviders
string SetProviderInfo (ChatSetupInfo info)
Sets a chat provider info
bool Connected (ChatProvider providerType)
Checks connection status
string Reconnect (ChatProvider providerType)
Reconnect a specific providerType to it's chat service
void SendMessage (string msg, MessageType mt)
Broadcast a message to appropriate channels based on the message type
CompilerStatus GetStatus ()
Returns the current compiler status
string CompileError ()
Returns the error message of the last operation. Reading this will clear the stored value
bool Initialize ()
Sets up the symlinks for hotswapping game code. This will reset everything in the Game folder. Requires the repository to be set up and locks it once the compilation stage starts. Runs asyncronously from this call
void InitializeImpl ()
bool Compile (bool silent=false)
Does all the necessary actions to take the revision currently in the repository and compile it to be run on the next server reboot. Requires BYOND to be set up and the GetStatus to return CompilerStatus.Initialized. Runs asyncronously
string ProjectName ()
Returns the relative path of the dme the compiler will look for without the .dme part
void SetProjectName (string projectName)
Sets the relative path of the dme the compiler will look for without the .dme part
string Cancel ()
Cancels the current compilation
string ReadText (string staticRelativePath, bool repo, out string error, out bool unauthorized)
Read from a static file
string WriteText (string staticRelativePath, string data, out bool unauthorized)
Write to a static file
string DeleteFile (string staticRelativePath, out bool unauthorized)
Deletes the target static file
IList< string > ListStaticDirectory (string subDir, out string error, out bool unauthorized)
Returns the file contents of the specified server directory Subdirectories will be prefixed with '/'
DreamDaemonStatus DaemonStatus ()
Gets the status of DreamDaemon
void RequestRestart ()
Restart the server after the currently running world reboots. Has no effect if the server isn't running
void RequestStop ()
Stop the server after the currently running world reboots. Has no effect if the server isn't running
string Stop ()
Immediately kills the server
void SetPort (ushort new_port)
Set the port to host DD on. Requires reboot to apply. Calls RequestRestart.
void KillMe ()
string Restart ()
Immediately kills and restarts the server
string CanStart ()
Check if a call to Start will fail. Of course, be aware of race conditions with other interfaces
string Start ()
Starts the server if it isn't running
DreamDaemonSecurity SecurityLevel ()
Get the configured (not necessarily running) security level
bool SetSecurityLevel (DreamDaemonSecurity level)
Sets the security level of the server. Requires server reboot to apply. Calls RequestRestart. Note that anything higher than Trusted will disable interop from DD
bool Autostart ()
Check if the watchdog will start when the service starts
void SetAutostart (bool on)
Set the autostart config
string StatusString (bool includeMetaInfo)
Returns a human readable string of the current server status
ushort Port ()
Get the configured port. Not necessarily the running port if it has since changed
bool ShutdownInProgress ()
Checks if a server stop has been requested
string WorldAnnounce (string message)
Sends a message to everyone on the server
bool Webclient ()
Check if the BYOND webclient is currently enabled for the server
void SetWebclient (bool on)
Set the webclient config. Calls RequestRestart
string SendCommand (string cmd)
int PlayerCount ()
Returns the number of connected players. Requires game to use API version >= 3.1.0.1
bool InteropMessage (string command)
Called from /world/ExportService(command)
bool PrecompileHook ()
Run the "precompile" event
bool PostcompileHook ()
Run the "postcompile" event
bool OperationInProgress ()
If the repo is currently undergoing an operation
int CheckoutProgress ()
Gets the progress of repository operations, not all operations are supported
bool Exists ()
Check if the repository is valid, if not Setup(string, string) must be called
string UpdateTGS3Json ()
Updates the CachedTGS3SettingsPath with the RepoTGS3SettingsPath
string Setup (string RepoURL, string BranchName)
Deletes whatever may be left over and clones the repo at remote and checks out branch . Will move config and data dirs to a backup location if they exist. Runs asyncronously
string GetHead (bool useTracked, out string error)
Gets the sha of the current HEAD
string GetBranch (out string error)
Gets the name of the current branch
string GetRemote (out string error)
Gets the url of the current origin
string Checkout (string sha)
Hard checks out the passed object name
string Update (bool reset)
Fetches the origin and merges it into the current branch
IDictionary< string, string > ListBackups (out string error)
Lists tags in the repository created by the ServerInstance
string Reset (bool trackedBranch)
Runs git reset –hard
string MergePullRequest (int PRNumber)
Merges the target pull request into the current branch if the remote is a github repository
IList< PullRequestInfo > MergedPullRequests (out string error)
Get the currently merged pull requests. Note that switching branches will delete this list and switching back won't restore it
string GetCommitterName ()
Gets the name of the configured git committer
void SetCommitterName (string newName)
Sets the name of the configured git committer
string GetCommitterEmail ()
Gets the email of the configured git committer
void SetCommitterEmail (string newEmail)
Sets the email of the configured git committer
string SynchronizePush ()
Pushes the paths listed in TGS3.json to the currentl git remote. No other commit differences may exist for this function to succeed
string GenerateChangelog (out string error)
Updates the html changelog
string GenerateChangelogImpl (out string error, bool recurse=false)
Updates the html changelog
void SetAutoUpdateInterval (ulong newInterval)
(De)Activate and set the interval for the automatic server updater
ulong AutoUpdateInterval ()
Get the current autoupdate interval
string LiveSha ()
Gets the current staged or live commit SHA
bool PushTestmergeCommits ()
Check if we push a temporary branch to the remote when we make testmerge commits
void SetPushTestmergeCommits (bool newValue)
Set if we push a temporary branch to the remote when we make testmerge commits
ServerInstance (IInstanceConfig config, byte logID)
Constructs and a ServerInstance
string Version ()
Retrieve's the service's version
void VerifyConnection ()
Does nothing on the server end, but if the call completes, you can be sure you are connected. WCF won't throw until you try until you actually use the API
void Reattach (bool silent)
string ServerDirectory ()
Return the directory of the server on the host machine
void Offline ()
Sets InstanceConfig.Enabled of Config to
void Dispose ()
Implements the IDisposable pattern
Public Attributes
const string UninitializedString = "NEEDS INITIALIZING"
Used for indicating unintialized encrypted data
readonly byte LoggingID
Used to assign the instance to event IDs
Protected Member Functions
override bool CheckAccessCore (OperationContext operationContext)
Called by WCF whenever a component call is made. Checks to see that the supplied user account has access to the requested component
Private Types
enum SymbolicLink { SymbolicLink.File = 0, SymbolicLink.Directory = 1 }
enum ShutdownRequestPhase { ShutdownRequestPhase.None, ShutdownRequestPhase.Requested, ShutdownRequestPhase.Pinged }
Private Member Functions
string FindTheDroidsWereLookingFor (string search=null, bool useDomain=false)
Set TheDroidsWereLookingFor based off either an search ed name or a string SecurityIdentifier from the config
void DisposeAdministration ()
Cleans up the ITGAdministration component
void InitByond ()
Called when the ServerInstance is setup. Prepares the BYOND updater
void CleanByondStaging ()
Cleans the BYOND staging directory
void DisposeByond ()
Called when the ServerInstance is shutdown
bool BusyCheck ()
Checks if the updater is considered busy
bool ApplyStagedUpdate ()
Attempts to move the staged update from StagingDirectory to ByondDirectory. Sets lastError on failure
void ChatProvider_OnChatMessage (IChatProvider ChatProvider, string speaker, string channel, string message, bool isAdmin, bool isAdminChannel)
Implementation of OnChatMessage that recieves messages from all channels of all connected ChatProviders
void DisposeChat ()
Properly shuts down all ChatProviders
IList< ChatSetupInfo > InitProviderInfos ()
Returns a list of ChatSetupInfos loaded from the config or the defaults if none are set
void ChatConnectivityCheck ()
Reconnect servers that are enabled and disconnected. Checked every time DreamDaemon reboots
static bool CreateSymbolicLink (string lpSymlinkFileName, string lpTargetFileName, SymbolicLink dwFlags)
void InitCompiler ()
void DisposeCompiler ()
bool CompilerIdleNoLock ()
CompilerStatus IsInitialized ()
void CleanGameFolder ()
string GetStagingDir ()
string InvertDirectory (string gameDirectory)
void CompileImpl ()
void InitDreamDaemon ()
Setup or reattach the watchdog, depending on InstanceConfig.ReattachRequired of Config, and create the DiagnosticsDir
void DisposeDreamDaemon ()
Either let go of Proc for reattachment or terminate it, depending on InstanceConfig.ReattachRequired of Config
void WriteCurrentDDLog (string message)
Write a message to the CurrentDDLog. A timestamp will be prepended to it
void Watchdog ()
Threaded loop that keeps DreamDaemon from unintentionally stopping
void MemTrackTimer_Elapsed (object sender, ElapsedEventArgs e)
Called every five seconds while DreamDaemon is running to log it's current state to the DiagnosticsDir
string SecurityWord (bool starting=false)
Translate the configured DreamDaemonSecurity level into a byond command line param
void UpdateBridgeDll (bool overwrite)
Copies BridgeDLLName from the program directory to the the ServerInstance directory
string StartImpl (bool watchdog)
Clears the current GameAPIVersion, calls UpdateBridgeDll(bool) with a parameter, and attempts to start the DreamDaemon Proc
void LoadServerChatCommands ()
void HandleCommand (string cmd)
bool CheckAPIVersionConstraints ()
string SendTopic (string topicdata, ushort port)
void GenCommsKey ()
void InitEventHandlers ()
Creates the EventFolder
string GetEventPath (string eventName)
Gets the path of an event given an eventName
bool EventHandlerExists (string eventName)
Check if an event handler for eventName exists
bool HandleEvent (string eventName)
Runs an event named eventName if it exists
void InitRepo ()
Initializes the repository
bool RepoConfigsMatch ()
Checks if the CachedTGS3SettingsPath and RepoTGS3SettingsPath json files match.
RepoConfig GetCachedRepoConfig ()
Gets the RepoConfig for CachedTGS3SettingsPath
string LoadRepo ()
Initializes Repo
void DisposeRepo ()
Cleans up Repo
bool HandleTransferProgress (TransferProgress progress)
Updates currentProgress with the progess of the current Repo transfer operation
void HandleCheckoutProgress (string path, int completedSteps, int totalSteps)
Updates currentProgress with the progess of the current Repo checkout operation
void Clone (object twostrings)
Backups up the StaticDirs and deletes the current RepoPath if they exist. Clones the given branch of the given remote. Sets up new StaticDirs
void DisableGarbageCollectionNoLock ()
Turns off the gc.auto git config setting
void BackupAndDeleteStaticDirectory ()
Copies the Static directory to the first available Static_BACKUP path in the ServerInstance then deleted the old directory
void InitialConfigureRepository ()
Initial setup for the StaticDirs and CachedTGS3SettingsPath
string GetShaOrBranch (out string error, bool branch, bool tracked)
Gets the SHA or branch name of the Repo's HEAD
string ResetNoLock (Branch targetBranch)
Equivalent of running git reset --hard on the repository. Requires RepoLock
string MergeBranch (string committish, string mergeMessage)
Merges given committish into the current branch
void PushTestmergeCommit ()
string UpdateImpl (bool reset, bool successOnUpToDate)
Fetches the origin and merges it into the current branch
void UpdateSubmodules ()
Properly updates any git submodules in the repository
string CreateBackup ()
Creates a date and timestamped tag of the current HEAD
Signature MakeSig ()
Creates a commit LibGit2Sharp.Signature based off of the configured name and e-mail
void DeletePRList ()
Deletes the ServerInstance's PRJobFile
IDictionary< string, IDictionary< string, string > > GetCurrentPRList ()
Deserializes the PRJobFile
void SetCurrentPRList (IDictionary< string, IDictionary< string, string >> list)
Serializes pull request info into PRJobFile
FetchOptions GenerateFetchOptions ()
Create FetchOptions that Prune and have the appropriate credentials and progress handler
string Fetch ()
Fetches origin
bool LocalIsRemote ()
Check if the current HEAD matches the tracked remote branch HEAD
string Commit (RepoConfig Config)
Create a commit based on a Config
string Push ()
bool SSHAuth ()
Check if the ServerInstance is configured for SSH pushing
Credentials GenerateGitCredentials (string url, string usernameFromUrl, SupportedCredentialTypes types)
SSH credentials callback. Properly sets up SSH keys for an authorization operation
void AutoUpdateTimer_Elapsed (object sender, System.Timers.ElapsedEventArgs e)
Runs on the configured InstanceConfig.AutoUpdateInterval of Config and tries to Update(bool) and Compile(bool) the ServerInstance
void UpdateLiveSha (string newSha)
Updates LiveTrackingBranch with the staged Compile(bool)'s SHA
void RunDisposals ()
Cleans up the ServerInstance
void WriteInfo (string message, EventID id)
Writes information to the Windows event log
void WriteError (string message, EventID id)
Writes an error to the Windows event log
void WriteWarning (string message, EventID id)
Writes a warning to the Windows event log
void WriteAccess (string username, bool authSuccess)
Writes an access event to the Windows event log
string RelativePath (string path)
Converts relative paths to full ServerInstance directory paths
void Dispose (bool disposing)
Implements the IDisposable pattern. Calls RunDisposals
Static Private Member Functions
static void CreateSymlink (string link, string target)
Private Attributes
SecurityIdentifier TheDroidsWereLookingFor
The SecurityIdentifier of the Windows group authorized to access the ServerInstance
object authLock = new object()
Used for multithreading safety
string LastSeenUser
The WindowsIdentity.Name of the last WindowsIdentity to attempt to access the ServerInstance
readonly SecurityIdentifier ServiceSID = WindowsIdentity.GetCurrent().User
The SecurityIdentifier of the account the Service is running as
const string ByondDirectory = "BYOND"
The instance directory to store the BYOND installation
const string StagingDirectory = "BYOND_staged"
The instance directory to use when updating the BYOND installation
const string StagingDirectoryInner = StagingDirectory + "/byond"
Path to the actual BYOND installation within the StagingDirectory
const string RevisionDownloadPath = "BYONDRevision.zip"
The path in the instance directory to store the downloaded BYOND revision
const string VersionFile = "/byond_version.dat"
The location of the BYOND version data of an installation
const string ByondRevisionsURL = "https://secure.byond.com/download/build/{0}/{0}.{1}_byond.zip"
The URL format string for getting BYOND version {0}.{1} zipfile
const string ByondLatestURL = "https://secure.byond.com/download/build/LATEST/"
The URL for getting the latest BYOND version zipfile
const string ByondConfigDir = StagingDirectory + "/BYOND/cfg"
The instance directory to modify the BYOND cfg before installation
const string ByondDDConfig = ByondConfigDir + "/daemon.txt"
BYOND's DreamDaemon config file in the cfg modification directory
const string ByondNoPromptTrustedMode = "trusted-check 0"
Setting to add to ByondDDConfig to suppress an invisible user prompt for running a trusted mode .dmb
ByondStatus updateStat = ByondStatus.Idle
The status of the BYOND updater
object ByondLock = new object()
Used for multithreading safety
string lastError
The last error the BYOND updater encountered
Thread RevisionStaging
Thread used for staging BYOND revisions
IList< IChatProvider > ChatProviders
List of IChatProviders for the ServerInstance
object ChatLock = new object()
Used for multithreading safety
const string StaticDirs = "Static"
const string StaticBackupDir = "Static_BACKUP"
const string GameDir = "Game"
const string GameDirA = GameDir + "/A"
const string GameDirB = GameDir + "/B"
const string GameDirLive = GameDir + "/Live"
const string LiveFile = "/TestLive.lk"
const string ADirTest = GameDirA + LiveFile
const string BDirTest = GameDirB + LiveFile
const string LiveDirTest = GameDirLive + LiveFile
object CompilerLock = new object()
CompilerStatus compilerCurrentStatus
string lastCompilerError
Thread CompilerThread
bool compilationCancellationRequestation = false
bool canCancelCompilation = false
bool silentCompile = false
bool UpdateStaged = false
object configLock = new object()
Used for multithreading safety
const string DiagnosticsDir = "Diagnostics"
Directory for storing DreamDaemon diagnostic files
const string ResourceDiagnosticsDir = DiagnosticsDir + "/Resources"
Directory for storing DreamDaemon ResourceUsage files
const int DDHangStartTime = 60
Time until DD is considered DOA on startup
const int DDBadStartTime = 10
If DreamDaemon crashes before this time it is considered a bad startup
Process Proc
The DreamDaemon process
PerformanceCounter pcpu
CPU performance information for Proc
object watchdogLock = new object()
Used for multithreading safety
Thread DDWatchdog
The thread that monitors the status of DreamDaemon
DreamDaemonStatus currentStatus
The DreamDaemonStatus of Proc
string CurrentDDLog
Current logfile in use in ResourceDiagnosticsDir
ushort currentPort = 0
Current port DreamDaemon is running on
object restartLock = new object()
Used for multithreading safety
bool RestartInProgress = false
Used to indicate if an intentional restart is in progress on the watchdog. Requires restartLock to access
bool ReattachInsteadOfRestart = false
Used to indicate if an service restart is in progress on the watchdog. Requires restartLock to access
DreamDaemonSecurity StartingSecurity
Current DreamDaemonSecurity level of DreamDaemon
ShutdownRequestPhase AwaitingShutdown
Indicator of progress on a RequestRestart or RequestStop operation
object topicLock = new object()
const int CommsKeyLen = 64
string serviceCommsKey
const int AllowedMajorAPIVersion = 2
Version GameAPIVersion
const string SPInstanceName = "server_instance"
const string SCHardReboot = "hard_reboot"
const string SCGracefulShutdown = "graceful_shutdown"
const string SCWorldAnnounce = "world_announce"
const string SCListCustomCommands = "list_custom_commands"
const string SCAPICompat = "api_compat"
const string SCPlayerCount = "client_count"
const string SRetSuccess = "SUCCESS"
String returned when a command completes successfully with no output
const string SRKillProcess = "killme"
const string SRIRCBroadcast = "irc"
const string SRIRCAdminChannelMessage = "send2irc"
const string SRWorldReboot = "worldreboot"
const string SRAPIVersion = "api_ver"
const string CCPHelpText = "help_text"
const string CCPAdminOnly = "admin_only"
const string CCPRequiredParameters = "required_parameters"
const string BridgeDLLName = "TGDreamDaemonBridge.dll"
The file name of the .dll that contains the ITGInterop bridge class
const string DreamDaemonBridgeNamespace = "TGDreamDaemonBridge"
The namespace that contains the ITGInterop bridge class. Used for reflection
const string DreamDaemonBridgeType = DreamDaemonBridgeNamespace + ".DreamDaemonBridge"
The ITGInterop bridge class. Used for reflection
List< Command > ServerChatCommands
const string EventFolder = "EventHandlers/"
The instance directory for Preaction handlers
const string RepoPath = "Repository"
The ServerInstance directory for the repository
const string RemoteTempBranchName = "___TGS3TempBranch"
The branch name used for publishing testmerge commits
const string RepoTGS3SettingsPath = RepoPath + "/TGS3.json"
The path to the Repository's RepoConfig json
const string CachedTGS3SettingsPath = "TGS3.json"
Path to the ServerInstance's RepoConfig json
const string RepoErrorUpToDate = "Already up to date!"
Error message for when a merge operation fails due to the target branch already having the source branch's commits
const string SSHPushRemote = "ssh_push_target"
Git remote for push operations
const string RepoKeyDir = "RepoKey/"
The ServerInstance directory for the repository SSH keys
const string PrivateKeyPath = RepoKeyDir + "private_key.txt"
The path to the private ssh-rsa key file
const string PublicKeyPath = RepoKeyDir + "public_key.txt"
The path to the public ssh-rsa key file
const string PRJobFile = "prtestjob.json"
File name for monitoring which github pull requests are currently test merged
const string LiveTrackingBranch = "___TGSLiveCommitTrackingBranch"
The branch that points to the current commit that is live or staged to be live in DreamDaemon
const string CommitMessage = "Automatic changelog compile, [ci skip]"
Commit message for RepoConfig.PathsToStage
object RepoLock = new object()
Used in conjunction with RepoBusy for multithreading safety
bool RepoBusy = false
Used in conjunction with RepoLock for multithreading safety
bool Cloning = false
Whether or not a git clone operation is in progress
Repository Repo
The repository object
int currentProgress = -1
Used for reporting operation progress to the TGServiceInterface
System.Timers.Timer autoUpdateTimer
Used for automatically updating the ServerInstance
readonly IInstanceConfig Config
The configuration settings for the instance
bool disposedValue = false
To detect redundant Dispose() calls
Detailed Description
The class which holds all interface components. There are no safeguards for call race conditions so these must be guarded against internally
Definition at line 13 of file Administration.cs.
Member Enumeration Documentation
enum TGServerService.ServerInstance.ShutdownRequestPhase strong private
Enumerator
None
Requested
Pinged
Definition at line 17 of file DreamDaemon.cs.
         {
             None,
             Requested,
             Pinged,
         }
enum TGServerService.ServerInstance.SymbolicLink strong private
Enumerator
File
Directory
Definition at line 18 of file Compiler.cs.
         {
             File = 0,
             Directory = 1
         }
Constructor & Destructor Documentation
TGServerService.ServerInstance.ServerInstance (IInstanceConfig config, byte logID)
Constructs and a ServerInstance
Definition at line 31 of file ServerInstance.cs.
References TGServerService.ServerInstance.FindTheDroidsWereLookingFor(), TGServerService.ServerInstance.InitByond(), TGServerService.ServerInstance.InitChat(), TGServerService.ServerInstance.InitCompiler(), TGServerService.ServerInstance.InitDreamDaemon(), TGServerService.ServerInstance.InitEventHandlers(), and TGServerService.ServerInstance.InitRepo().
         {
             LoggingID = logID;
             Config = config;
             FindTheDroidsWereLookingFor();
             InitEventHandlers();
             InitChat();
             InitRepo();
             InitByond();
             InitCompiler();
             InitDreamDaemon();
         }
Member Function Documentation
bool TGServerService.ServerInstance.ApplyStagedUpdate () private
Attempts to move the staged update from StagingDirectory to ByondDirectory. Sets lastError on failure
Returns
on success, on failure
Definition at line 314 of file Byond.cs.
References TGServerService.ServerInstance.compilerCurrentStatus, TGServerService.ServerInstance.CompilerLock, TGServerService.Program.DeleteDirectory(), TGServerService.ServerInstance.GetVersion(), TGServerService.ServerInstance.RelativePath(), TGServerService.ServerInstance.SendMessage(), TGServerService.ServerInstance.WriteError(), and TGServerService.ServerInstance.WriteInfo().
Referenced by TGServerService.ServerInstance.Start(), and TGServerService.ServerInstance.UpdateToVersionImpl().
         {
             lock (CompilerLock)
             {
                 if (compilerCurrentStatus == CompilerStatus.Compiling)
                     return false;
                 lock (ByondLock)
                 {
                     if (updateStat != ByondStatus.Staged)
                         return false;
                     updateStat = ByondStatus.Updating;
                 }
                 try
                 {
                     var rbd = RelativePath(ByondDirectory);
                     Program.DeleteDirectory(rbd);
                     Directory.Move(RelativePath(StagingDirectoryInner), rbd);
                     Program.DeleteDirectory(RelativePath(StagingDirectory));
                     lastError = null;
                     SendMessage("BYOND: Update completed!", MessageType.DeveloperInfo);
                     WriteInfo(String.Format("BYOND update {0} completed!", GetVersion(ByondVersion.Installed)), EventID.BYONDUpdateComplete);
                     return true;
                 }
                 catch (Exception e)
                 {
                     lastError = e.ToString();
                     SendMessage("BYOND: Update failed!", MessageType.DeveloperInfo);
                     WriteError("BYOND update failed! Error: " + e.ToString(), EventID.BYONDUpdateFail);
                     return false;
                 }
                 finally
                 {
                     lock(ByondLock) {
                         updateStat = ByondStatus.Idle;
                     }
                 }
             }
         }
bool TGServerService.ServerInstance.Autostart ()
Check if the watchdog will start when the service starts
Implements TGServiceInterface.Components.ITGDreamDaemon.
Definition at line 660 of file DreamDaemon.cs.
References TGServerService.IInstanceConfig.Autostart, and TGServerService.ServerInstance.Config.
         {
             return Config.Autostart;
         }
ulong TGServerService.ServerInstance.AutoUpdateInterval ()
Get the current autoupdate interval
Implements TGServiceInterface.Components.ITGRepository.
Definition at line 1345 of file Repository.cs.
References TGServerService.IInstanceConfig.AutoUpdateInterval, and TGServerService.ServerInstance.Config.
         {
             return Config.AutoUpdateInterval;
         }
void TGServerService.ServerInstance.AutoUpdateTimer_Elapsed (object sender, System.Timers.ElapsedEventArgs e) private
Runs on the configured InstanceConfig.AutoUpdateInterval of Config and tries to Update(bool) and Compile(bool) the ServerInstance
Parameters
sender A System.Timers.Timer
e The event arguments
Definition at line 1355 of file Repository.cs.
References TGServerService.ServerInstance.Compile(), and TGServerService.ServerInstance.UpdateImpl().
Referenced by TGServerService.ServerInstance.InitRepo().
         {
             if (UpdateImpl(true, false) == null)
             {
                 Compile(true);
             }
         }
void TGServerService.ServerInstance.BackupAndDeleteStaticDirectory () private
Copies the Static directory to the first available Static_BACKUP path in the ServerInstance then deleted the old directory
Definition at line 297 of file Repository.cs.
References TGServerService.Program.CopyDirectory(), TGServerService.Program.DeleteDirectory(), TGServerService.ServerInstance.RelativePath(), TGServerService.ServerInstance.StaticBackupDir, and TGServerService.ServerInstance.StaticDirs.
Referenced by TGServerService.ServerInstance.Clone(), and TGServerService.ServerInstance.RecreateStaticFolder().
         {
             var rsd = RelativePath(StaticDirs);
             if (Directory.Exists(rsd))
             {
                 int count = 1;
                 var rsbd = RelativePath(StaticBackupDir);
                 string path = Path.GetDirectoryName(rsbd);
                 string newFullPath = rsbd;
                 while (File.Exists(newFullPath) || Directory.Exists(newFullPath))
                 {
                     string tempDirName = string.Format("{0}({1})", rsbd, count++);
                     newFullPath = Path.Combine(path, tempDirName);
                 }
                 Program.CopyDirectory(rsd, newFullPath);
             }
             Program.DeleteDirectory(rsd);
         }
bool TGServerService.ServerInstance.BusyCheck () private
Checks if the updater is considered busy
Returns
if the updater is considered busy, otherwise
Definition at line 111 of file Byond.cs.
Referenced by TGServerService.ServerInstance.UpdateToVersion().
         {
             lock (ByondLock)
                 switch (updateStat)
                 {
                     default:
                     case ByondStatus.Starting:
                     case ByondStatus.Downloading:
                     case ByondStatus.Staging:
                     case ByondStatus.Updating:
                         return true;
                     case ByondStatus.Idle:
                     case ByondStatus.Staged:
                         return false;
                 }
         }
string TGServerService.ServerInstance.Cancel ()
Cancels the current compilation
Returns
on success, error message on failure
Implements TGServiceInterface.Components.ITGCompiler.
Definition at line 596 of file Compiler.cs.
         {
             lock (CompilerLock)
             {
                 if (compilerCurrentStatus != CompilerStatus.Compiling)
                     return "Invalid state for cancellation!";
                 compilationCancellationRequestation = true;
                 if (canCancelCompilation)
                     CompilerThread.Abort();
                 else
                     return "Compilation will be cancelled when the repo copy is complete";
                 return null;
             }
         }
string TGServerService.ServerInstance.CanStart ()
Check if a call to Start will fail. Of course, be aware of race conditions with other interfaces
Implements TGServiceInterface.Components.ITGDreamDaemon.
Definition at line 468 of file DreamDaemon.cs.
References TGServerService.ServerInstance.Config, TGServerService.ServerInstance.GameDirLive, TGServerService.ServerInstance.GetVersion(), TGServerService.IInstanceConfig.ProjectName, and TGServerService.ServerInstance.RelativePath().
Referenced by TGServerService.ServerInstance.Start(), and TGServerService.ServerInstance.StartImpl().
         {
             if (GetVersion(ByondVersion.Installed) == null)
                 return "Byond is not installed!";
             var DMB = RelativePath(GameDirLive + "/" + Config.ProjectName + ".dmb");
             if (!File.Exists(DMB))
                 return String.Format("Unable to find {0}!", DMB);
             return null;
         }
void TGServerService.ServerInstance.ChatConnectivityCheck () private
Reconnect servers that are enabled and disconnected. Checked every time DreamDaemon reboots
Definition at line 211 of file Chat.cs.
References TGServerService.ServerInstance.Connected(), and TGServerService.ServerInstance.Reconnect().
Referenced by TGServerService.ServerInstance.HandleCommand().
         {
             foreach (ChatProvider I in Enum.GetValues(typeof(ChatProvider)))
                 if(!Connected(I))
                     Reconnect(I);
         }
void TGServerService.ServerInstance.ChatProvider_OnChatMessage (IChatProvider ChatProvider, string speaker, string channel, string message, bool isAdmin, bool isAdminChannel) private
Implementation of OnChatMessage that recieves messages from all channels of all connected ChatProviders
Parameters
ChatProvider The IChatProvider that heard the message
speaker The user who wrote the message
channel The channel the message is from
message The recieved message
isAdmin if speaker is considered a chat admin, otherwise
isAdminChannel if channel is an admin channel, otherwise
Definition at line 75 of file Chat.cs.
References TGServerService.ChatCommands.ChatCommand.CommandInfo, TGServiceInterface.Command.DoRun(), TGServerService.ServerInstance.LoadServerChatCommands(), TGServiceInterface.Command.OutputProcVar, TGServerService.ChatProviders.IChatProvider.SendMessageDirect(), TGServerService.ServerInstance.ServerChatCommands, and TGServerService.ServerInstance.WriteInfo().
Referenced by TGServerService.ServerInstance.InitChat().
         {
             var splits = message.Trim().Split(' ');
             if (splits.Length == 1 && splits[0] == "")
             {
                 ChatProvider.SendMessageDirect("Hi!", channel);
                 return;
             }
             var asList = new List<string>(splits);
             Command.OutputProcVar.Value = (m) => ChatProvider.SendMessageDirect(m, channel);
             ChatCommand.CommandInfo.Value = new CommandInfo()
             {
                 IsAdmin = isAdmin,
                 IsAdminChannel = isAdminChannel,
                 Speaker = speaker,
                 Server = this,
             };
             WriteInfo(String.Format("Chat Command from {0} ({2}): {1}", speaker, String.Join(" ", asList), channel), EventID.ChatCommand);
             if (ServerChatCommands == null)
                 LoadServerChatCommands();
             new RootChatCommand(ServerChatCommands).DoRun(asList);
         }
override bool TGServerService.ServerInstance.CheckAccessCore (OperationContext operationContext) protected
Called by WCF whenever a component call is made. Checks to see that the supplied user account has access to the requested component
Parameters
operationContext Various parameters about the operation supplied by WCF
Returns
if the supplied user account may use the requested component, otherwise
Definition at line 113 of file Administration.cs.
References TGServerService.IInstanceConfig.AuthorizedUserGroupSID, TGServerService.ServerInstance.Config, TGServerService.ServerInstance.ServiceSID, and TGServerService.ServerInstance.WriteAccess().
         {
             var contract = operationContext.EndpointDispatcher.ContractName;
             if (contract == typeof(ITGConnectivity).Name)   //always allow connectivity checks
                 return true;
             var windowsIdent = operationContext.ServiceSecurityContext.WindowsIdentity;
             if (contract == typeof(ITGInterop).Name)
             {
                 //only allow the same user the service is running as to use interop, because that's what DD is running as, and don't spam the logs with it unless it fails
                 var result = windowsIdent.User == ServiceSID;
                 if(!result)
                     WriteAccess(windowsIdent.Name, false);
                 return result;
             }
             var wp = new WindowsPrincipal(windowsIdent);
             //first allow admins
             var authSuccess = wp.IsInRole(WindowsBuiltInRole.Administrator);
             //if we're not an admin, check that we aren't trying to access the admin interface
             if (!authSuccess && operationContext.EndpointDispatcher.ContractName != typeof(ITGAdministration).Name && TheDroidsWereLookingFor != null)
                 authSuccess = wp.IsInRole(new SecurityIdentifier(Config.AuthorizedUserGroupSID));
             lock (authLock)
             {
                 var user = windowsIdent.Name;
                 if (LastSeenUser != user)
                 {
                     LastSeenUser = user;
                     WriteAccess(user, authSuccess);
                 }
             }
             return authSuccess;
         }
bool TGServerService.ServerInstance.CheckAPIVersionConstraints () private
Definition at line 174 of file Interop.cs.
References TGServerService.ServerInstance.AllowedMajorAPIVersion.
Referenced by TGServerService.ServerInstance.HandleCommand(), and TGServerService.ServerInstance.SendTopic().
         {
             //major will never change for all of TGS3
             //we treat minor as major, build as minor, and revision as patch
             return !(GameAPIVersion == null || GameAPIVersion.Minor != AllowedMajorAPIVersion);
         }
string TGServerService.ServerInstance.Checkout (string sha)
Hard checks out the passed object name
Implements TGServiceInterface.Components.ITGRepository.
Definition at line 498 of file Repository.cs.
References TGServerService.ServerInstance.DeletePRList(), TGServerService.ServerInstance.Fetch(), TGServerService.ServerInstance.HandleCheckoutProgress(), TGServerService.ServerInstance.LoadRepo(), TGServerService.ServerInstance.ResetNoLock(), TGServerService.ServerInstance.SendMessage(), TGServerService.ServerInstance.UpdateSubmodules(), TGServerService.ServerInstance.WriteInfo(), and TGServerService.ServerInstance.WriteWarning().
         {
             if (sha == LiveTrackingBranch)
                 return "I'm sorry Dave, I'm afraid I can't do that...";
             lock (RepoLock)
             {
                 var result = LoadRepo();
                 if (result != null)
                     return result;
                 SendMessage("REPO: Checking out object: " + sha, MessageType.DeveloperInfo);
                 try
                 {
                     if (Repo.Branches[sha] == null)
                     {
                         //see if origin has the branch
                         result = Fetch();
                         var trackedBranch = Repo.Branches[String.Format("origin/{0}", sha)];
                         if (trackedBranch != null)
{
                             var newBranch = Repo.CreateBranch(sha, trackedBranch.Tip);
                             //track it
                             Repo.Branches.Update(newBranch, b => b.TrackedBranch = trackedBranch.CanonicalName);
                         }
                         else if (result != null)
                             return result;
                     }
                     //if this is a tracked branch, we need to reset to remote first and delete the PR list
                     ResetNoLock(Repo.Head.TrackedBranch ?? Repo.Head);
                     DeletePRList();
                     var Opts = new CheckoutOptions()
                     {
                         CheckoutModifiers = CheckoutModifiers.Force,
                         OnCheckoutProgress = HandleCheckoutProgress,
                     };
                     Commands.Checkout(Repo, sha, Opts);
                     var res = ResetNoLock(null);
                     UpdateSubmodules();
                     SendMessage("REPO: Checkout complete!", MessageType.DeveloperInfo);
                     WriteInfo("Repo checked out " + sha, EventID.RepoCheckout);
                     return res;
                 }
                 catch (Exception e)
                 {
                     SendMessage("REPO: Checkout failed!", MessageType.DeveloperInfo);
                     WriteWarning(String.Format("Repo checkout of {0} failed: {1}", sha, e.ToString()), EventID.RepoCheckoutFail);
                     return e.ToString();
                 }
             }
         }
int TGServerService.ServerInstance.CheckoutProgress ()
Gets the progress of repository operations, not all operations are supported
Implements TGServiceInterface.Components.ITGRepository.
Definition at line 149 of file Repository.cs.
References TGServerService.ServerInstance.currentProgress.
         {
             return currentProgress;
         }
void TGServerService.ServerInstance.CleanByondStaging () private
Cleans the BYOND staging directory
Definition at line 85 of file Byond.cs.
References TGServerService.Program.DeleteDirectory(), and TGServerService.ServerInstance.RelativePath().
Referenced by TGServerService.ServerInstance.DisposeByond(), TGServerService.ServerInstance.InitByond(), and TGServerService.ServerInstance.UpdateToVersionImpl().
         {
             var rrdp = RelativePath(RevisionDownloadPath);
             //linger not
             if (File.Exists(rrdp))
                 File.Delete(rrdp);
             Program.DeleteDirectory(RelativePath(StagingDirectory));
         }
void TGServerService.ServerInstance.CleanGameFolder () private
Definition at line 127 of file Compiler.cs.
References TGServerService.ServerInstance.BridgeDLLName, and TGServerService.ServerInstance.RelativePath().
Referenced by TGServerService.ServerInstance.InitializeImpl().
         {
             var GameDirABridge = RelativePath(Path.Combine(GameDirA, BridgeDLLName));
             if (Directory.Exists(GameDirABridge))
                 Directory.Delete(GameDirABridge);
             var GameDirBBridge = RelativePath(Path.Combine(GameDirB, BridgeDLLName));
             if (Directory.Exists(GameDirBBridge))
                 Directory.Delete(GameDirBBridge);
             var rgdl = RelativePath(GameDirLive);
             if (Directory.Exists(rgdl))
                 Directory.Delete(rgdl);
         }
void TGServerService.ServerInstance.Clone (object twostrings) private
Backups up the StaticDirs and deletes the current RepoPath if they exist. Clones the given branch of the given remote. Sets up new StaticDirs
Parameters
twostrings Remote and branch name, seperated by a ' '
Definition at line 222 of file Repository.cs.
References TGServerService.ServerInstance.BackupAndDeleteStaticDirectory(), TGServerService.ServerInstance.configLock, TGServerService.Program.DeleteDirectory(), TGServerService.ServerInstance.DeletePRList(), TGServerService.ServerInstance.DisableGarbageCollectionNoLock(), TGServerService.ServerInstance.DisposeRepo(), TGServerService.ServerInstance.GenerateGitCredentials(), TGServerService.ServerInstance.HandleCheckoutProgress(), TGServerService.ServerInstance.HandleTransferProgress(), TGServerService.ServerInstance.InitialConfigureRepository(), TGServerService.ServerInstance.LoadRepo(), TGServerService.ServerInstance.RelativePath(), TGServerService.ServerInstance.SendMessage(), TGServerService.ServerInstance.WriteInfo(), and TGServerService.ServerInstance.WriteWarning().
Referenced by TGServerService.ServerInstance.Setup().
         {
             //busy flag set by caller
             var ts = ((string)twostrings).Split(' ');
             var RepoURL = ts[0];
             var BranchName = ts[1];
             try
             {
                 SendMessage(String.Format("REPO: {2} started: Cloning {0} branch of {1} ...", BranchName, RepoURL, Repository.IsValid(RepoPath) ? "Full reset" : "Setup"), MessageType.DeveloperInfo);
                 try
                 {
                     DisposeRepo();
                     Program.DeleteDirectory(RelativePath(RepoPath));
                     DeletePRList();
                     lock (configLock)
                     {
                         BackupAndDeleteStaticDirectory();
                     }
                     var Opts = new CloneOptions()
                     {
                         BranchName = BranchName,
                         RecurseSubmodules = true,
                         OnTransferProgress = HandleTransferProgress,
                         OnCheckoutProgress = HandleCheckoutProgress,
                         CredentialsProvider = GenerateGitCredentials,
                     };
                     Repository.Clone(RepoURL, RelativePath(RepoPath), Opts);
                     currentProgress = -1;
                     LoadRepo();
                     DisableGarbageCollectionNoLock();
                     //create an ssh remote for pushing
                     Repo.Network.Remotes.Add(SSHPushRemote, RepoURL.Replace("git://", "ssh://").Replace("https://", "ssh://"));
                     InitialConfigureRepository();
                     SendMessage("REPO: Clone complete!", MessageType.DeveloperInfo);
                     WriteInfo("Repository {0}:{1} successfully cloned", EventID.RepoClone);
                 }
                 finally
                 {
                     currentProgress = -1;
                 }
             }
             catch (Exception e)
             {
                 SendMessage("REPO: Setup failed!", MessageType.DeveloperInfo);
                 WriteWarning(String.Format("Failed to clone {2}:{0}: {1}", BranchName, e.ToString(), RepoURL), EventID.RepoCloneFail);
             }
             finally
             {
                 lock (RepoLock)
                 {
                     RepoBusy = false;
                     Cloning = false;
                 }
             }
         }
string TGServerService.ServerInstance.Commit (RepoConfig Config) private
Create a commit based on a Config
Parameters
Config A RepoConfig with RepoConfig.PathsToStage
Returns
on success, error message on failure
Definition at line 1115 of file Repository.cs.
References TGServerService.ServerInstance.DeletePRList(), TGServerService.ServerInstance.LoadRepo(), TGServerService.ServerInstance.MakeSig(), TGServerService.RepoConfig.PathsToStage, TGServerService.ServerInstance.WriteInfo(), and TGServerService.ServerInstance.WriteWarning().
Referenced by TGServerService.ServerInstance.SynchronizePush().
         {
             lock (RepoLock)
             {
                 var result = LoadRepo();
                 if (result != null)
                     return result;
                 try
                 {
                     // Stage the file
                     foreach(var I in Config.PathsToStage)
                         Commands.Stage(Repo, I);
                     if (Repo.RetrieveStatus().Staged.Count() == 0)   //nothing to commit
                         return null;
                     // Create the committer's signature and commit
                     var authorandcommitter = MakeSig();
                     // Commit to the repository
                     WriteInfo(String.Format("Commit {0} created from changelogs", Repo.Commit(CommitMessage, authorandcommitter, authorandcommitter)), EventID.RepoCommit);
                     DeletePRList();
                     return null;
                 }
                 catch (Exception e)
                 {
                     WriteWarning("Repo commit failed: " + e.ToString(), EventID.RepoCommitFail);
                     return e.ToString();
                 }
             }
         }
bool TGServerService.ServerInstance.Compile (bool silent = false)
Does all the necessary actions to take the revision currently in the repository and compile it to be run on the next server reboot. Requires BYOND to be set up and the GetStatus to return CompilerStatus.Initialized. Runs asyncronously
Implements TGServiceInterface.Components.ITGCompiler.
Definition at line 563 of file Compiler.cs.
References TGServerService.ServerInstance.CompileImpl().
Referenced by TGServerService.ServerInstance.AutoUpdateTimer_Elapsed().
         {
             lock (CompilerLock)
             {
                 if (compilerCurrentStatus != CompilerStatus.Initialized)
                     return false;
                 silentCompile = silent;
                 lastCompilerError = null;
                 compilerCurrentStatus = CompilerStatus.Compiling;
                 CompilerThread = new Thread(new ThreadStart(CompileImpl));
                 CompilerThread.Start();
             }
             return true;
         }
string TGServerService.ServerInstance.CompileError ()
Returns the error message of the last operation. Reading this will clear the stored value
Implements TGServiceInterface.Components.ITGCompiler.
Definition at line 68 of file Compiler.cs.
References TGServerService.ServerInstance.lastCompilerError.
         {
             lock (CompilerLock)
             {
                 var err = lastCompilerError;
                 lastCompilerError = null;
                 return err;
             }
         }
void TGServerService.ServerInstance.CompileImpl () private
Definition at line 287 of file Compiler.cs.
References TGServerService.ServerInstance.BridgeDLLName, TGServerService.ServerInstance.ByondDirectory, TGServerService.ServerInstance.Config, TGServerService.Program.CopyDirectory(), TGServerService.ServerInstance.CreateBackup(), TGServerService.ServerInstance.CreateSymlink(), TGServerService.ServerInstance.currentStatus, TGServerService.ServerInstance.DaemonStatus(), TGServerService.Program.DeleteDirectory(), TGServerService.ServerInstance.GetCachedRepoConfig(), TGServerService.ServerInstance.GetHead(), TGServerService.ServerInstance.GetStagingDir(), TGServerService.ServerInstance.GetVersion(), TGServerService.ServerInstance.IsInitialized(), TGServerService.ServerInstance.PostcompileHook(), TGServerService.ServerInstance.PrecompileHook(), TGServerService.ServerInstance.PRJobFile, TGServerService.ServerInstance.Proc, TGServerService.ServerInstance.ProjectName(), TGServerService.ServerInstance.RelativePath(), TGServerService.ServerInstance.RepoBusy, TGServerService.ServerInstance.RepoConfigsMatch(), TGServerService.ServerInstance.RepoLock, TGServerService.ServerInstance.RepoPath, TGServerService.ServerInstance.SendMessage(), TGServerService.ServerInstance.silentCompile, TGServerService.ServerInstance.UpdateLiveSha(), TGServerService.ServerInstance.watchdogLock, TGServerService.ServerInstance.WriteError(), TGServerService.ServerInstance.WriteInfo(), and TGServerService.ServerInstance.WriteWarning().
Referenced by TGServerService.ServerInstance.Compile(), and TGServerService.ServerInstance.InitializeImpl().
         {
             try
             {
                 if (GetVersion(ByondVersion.Installed) == null)
                 {
                     lock (CompilerLock)
                     {
                         lastCompilerError = "BYOND not installed!";
                         compilerCurrentStatus = CompilerStatus.Initialized;
                         return;
                     }
                 }
                 if (!RepoConfigsMatch())
                 {
                     lock (CompilerLock)
                     {
                         lastCompilerError = "Repository TGS3.json does not match cached version! Please update the config appropriately!";
                         compilerCurrentStatus = IsInitialized();
                         return;
                     }
                 }
                 string resurrectee;
                 bool repobusy_check = false;
                 if (!Monitor.TryEnter(RepoLock))
                     repobusy_check = true;
                 if (!repobusy_check)
                 {
                     if (RepoBusy)
                         repobusy_check = true;
                     else
                         RepoBusy = true;
                     Monitor.Exit(RepoLock);
                 }
                 if (repobusy_check)
                 {
                     SendMessage("DM: Copy aborted, repo locked!", MessageType.DeveloperInfo);
                     lock (CompilerLock)
                     {
                         lastCompilerError = "The repo could not be locked for copying";
                         compilerCurrentStatus = CompilerStatus.Initialized;   //still fairly valid
                         return;
                     }
                 }
                 string CurrentSha;
                 try
                 {
                     bool silent;
                     lock (CompilerLock)
                     {
                         silent = silentCompile;
                         silentCompile = false;
                     }
                     if (!silent)
                         SendMessage("DM: Compiling...", MessageType.DeveloperInfo);
                     resurrectee = GetStagingDir();  //non-relative
                     var Config = GetCachedRepoConfig();
                     var deleteExcludeList = new List<string> { BridgeDLLName };
                     deleteExcludeList.AddRange(Config.StaticDirectoryPaths);
                     deleteExcludeList.AddRange(Config.DLLPaths);
                     Program.DeleteDirectory(resurrectee, true, deleteExcludeList);
                     Directory.CreateDirectory(resurrectee + "/.git/logs");
                     foreach (var I in Config.StaticDirectoryPaths)
                     {
                         var the_path = Path.Combine(resurrectee, I);
                         if (!Directory.Exists(the_path))
                             CreateSymlink(Path.Combine(resurrectee, I), RelativePath(Path.Combine(StaticDirs, I)));
                     }
                     foreach (var I in Config.DLLPaths)
                     {
                         var the_path = Path.Combine(resurrectee, I);
                         if (!File.Exists(the_path))
                             CreateSymlink(the_path, RelativePath(Path.Combine(StaticDirs, I)));
                     }
                     if (!File.Exists(Path.Combine(resurrectee, BridgeDLLName)))
                         CreateSymlink(Path.Combine(resurrectee, BridgeDLLName), RelativePath(BridgeDLLName));
                     deleteExcludeList.Add(".git");
                     Program.CopyDirectory(RelativePath(RepoPath), resurrectee, deleteExcludeList);
                     CurrentSha = GetHead(false, out string error);
                     //just the tip
                     const string GitLogsDir = "/.git/logs";
                     Program.CopyDirectory(RelativePath(RepoPath + GitLogsDir), resurrectee + GitLogsDir);
                     try
                     {
                         File.Copy(RelativePath(PRJobFile), Path.Combine(resurrectee, PRJobFile));
                     }
                     catch { }
                 }
                 finally
                 {
                     lock (RepoLock)
                     {
                         RepoBusy = false;
                     }
                 }
                 var res = CreateBackup();
                 if (res != null)
                     lock (CompilerLock)
                     {
                         lastCompilerError = res;
                         compilerCurrentStatus = CompilerStatus.Initialized;
                         return;
                     }
                 var dmeName = ProjectName() + ".dme";
                 var dmePath = resurrectee + "/" + dmeName;
                 if (!File.Exists(dmePath))
                 {
                     var errorMsg = String.Format("Could not find {0}!", dmeName);
                     SendMessage("DM: " + errorMsg, MessageType.DeveloperInfo);
                     WriteError(errorMsg, EventID.DMCompileCrash);
                     lock (CompilerLock)
                     {
                         lastCompilerError = errorMsg;
                         compilerCurrentStatus = CompilerStatus.Initialized;
                         return;
                     }
                 }
                 if (!PrecompileHook())
                 {
                     lastCompilerError = "The precompile hook failed";
                     compilerCurrentStatus = CompilerStatus.Initialized;   //still fairly valid
                     WriteWarning("Precompile hook failed!", EventID.DMCompileError);
                     return;
                 }
                 using (var DM = new Process())  //will kill the process if the thread is terminated
                 {
                     DM.StartInfo.FileName = RelativePath(ByondDirectory + "/bin/dm.exe");
                     DM.StartInfo.Arguments = String.Format("-clean {0}", dmePath);
                     DM.StartInfo.RedirectStandardOutput = true;
                     DM.StartInfo.UseShellExecute = false;
                     var OutputList = new StringBuilder();
                     DM.OutputDataReceived += new DataReceivedEventHandler(
                         delegate (object sender, DataReceivedEventArgs e)
{
                             OutputList.Append(Environment.NewLine);
                             OutputList.Append(e.Data);
                         }
                     );
                     try
                     {
                         lock (CompilerLock)
{
                             if (compilationCancellationRequestation)
                                 return;
                             canCancelCompilation = true;
                         }
                         DM.Start();
                         DM.BeginOutputReadLine();
                         while (!DM.HasExited)
                             DM.WaitForExit(100);
                         DM.CancelOutputRead();
                         lock (CompilerLock)
{
                             canCancelCompilation = false;
                             compilationCancellationRequestation = false;
                         }
                     }
                     catch
                     {
                         if (!DM.HasExited)
{
                             DM.Kill();
                             DM.WaitForExit();
                         }
                         throw;
                     }
                     finally
                     {
                         lock (CompilerLock)
{
                             canCancelCompilation = false;
                         }
                     }
                     if (DM.ExitCode == 0)
                     {
                         lock (watchdogLock)
{
                             //gotta go fast
                             var online = currentStatus == DreamDaemonStatus.Online;
                             if (online)
                                 Proc.Suspend();
                             try
{
                                 var rgdl = RelativePath(GameDirLive);
                                 if (Directory.Exists(rgdl))
                                     //these next two lines should be atomic but this is the best we can do
                                     Directory.Delete(rgdl);
                                 CreateSymlink(rgdl, resurrectee);
                             }
                             finally
{
                                 if (online && !Proc.HasExited)
                                     Proc.Resume();
                             }
                         }
                         var staged = DaemonStatus() != DreamDaemonStatus.Offline;
                         if (!PostcompileHook())
{
                             lastCompilerError = "The postcompile hook failed";
                             compilerCurrentStatus = CompilerStatus.Initialized;   //still fairly valid
                             WriteWarning("Postcompile hook failed!", EventID.DMCompileError);
                             return;
                         }
                         UpdateLiveSha(CurrentSha);
                         var msg = String.Format("Compile complete!{0}", !staged ? "" : " Server will update next round.");
                         SendMessage("DM: " + msg, MessageType.DeveloperInfo);
                         WriteInfo(msg, EventID.DMCompileSuccess);
                         lock (CompilerLock)
{
                             if (staged)
                                 UpdateStaged = true;
                             lastCompilerError = null;
                             compilerCurrentStatus = CompilerStatus.Initialized;   //still fairly valid
                         }
                     }
                     else
                     {
                         SendMessage("DM: Compile failed!", MessageType.DeveloperInfo); //Also happens for warnings
                         WriteWarning("Compile error: " + OutputList.ToString(), EventID.DMCompileError);
                         lock (CompilerLock)
{
                             lastCompilerError = "DM compile failure";
                             compilerCurrentStatus = CompilerStatus.Initialized;
                         }
                     }
                 }
             }
             catch (ThreadAbortException)
             {
                 return;
             }
             catch (Exception e)
             {
                 SendMessage("DM: Compiler thread crashed!", MessageType.DeveloperInfo);
                 WriteError("Compile manager errror: " + e.ToString(), EventID.DMCompileCrash);
                 lock (CompilerLock)
                 {
                     lastCompilerError = e.ToString();
                     compilerCurrentStatus = CompilerStatus.Initialized;   //still fairly valid
                 }
             }
             finally
             {
                 lock (CompilerLock)
                 {
                     canCancelCompilation = false;
                     if (compilationCancellationRequestation)
                     {
                         compilerCurrentStatus = CompilerStatus.Initialized;
                         compilationCancellationRequestation = false;
                         SendMessage("DM: Compile cancelled!", MessageType.DeveloperInfo);
                         WriteInfo("Compilation cancelled", EventID.DMCompileCancel);
                     }
                 }
             }
         }
bool TGServerService.ServerInstance.CompilerIdleNoLock () private
Definition at line 98 of file Compiler.cs.
Referenced by TGServerService.ServerInstance.Initialize(), and TGServerService.ServerInstance.Setup().
         {
             return compilerCurrentStatus == CompilerStatus.Uninitialized || compilerCurrentStatus == CompilerStatus.Initialized;
         }
bool TGServerService.ServerInstance.Connected (ChatProvider providerType)
Checks connection status
Implements TGServiceInterface.Components.ITGChat.
Definition at line 200 of file Chat.cs.
Referenced by TGServerService.ServerInstance.ChatConnectivityCheck().
         {
             foreach (var I in ChatProviders)
                 if (I.ProviderInfo().Provider == providerType)
                     return I.Connected();
             return false;
         }
string TGServerService.ServerInstance.CreateBackup () private
Creates a date and timestamped tag of the current HEAD
Returns
on success, error message on failure
Definition at line 737 of file Repository.cs.
References TGServerService.ServerInstance.LoadRepo(), TGServerService.ServerInstance.WriteInfo(), and TGServerService.ServerInstance.WriteWarning().
Referenced by TGServerService.ServerInstance.CompileImpl().
         {
             try
             {
                 lock (RepoLock)
                 {
                     var res = LoadRepo();
                     if (res != null)
                         return res;
                     //Make sure we don't already have a backup at this commit
                     var HEAD = Repo.Head.Tip.Sha;
                     foreach (var T in Repo.Tags)
                         if (T.Target.Sha == HEAD)
                             return null;
                     var tagName = "TGS-Compile-Backup-" + DateTime.Now.ToString("yyyy-MM-dd--HH.mm.ss");
                     var tag = Repo.ApplyTag(tagName);
                     if (tag != null)
                     {
                         WriteInfo("Repo backup created at tag: " + tagName + " commit: " + HEAD, EventID.RepoBackupTag);
                         return null;
                     }
                     throw new Exception("Tag creation failed!");
                 }
             }
             catch (Exception e)
             {
                 WriteWarning(String.Format("Failed backup tag creation at commit {0}!", Repo.Head.Tip.Sha), EventID.RepoBackupTagFail);
                 return e.ToString();
             }
         }
static bool TGServerService.ServerInstance.CreateSymbolicLink (string lpSymlinkFileName, string lpTargetFileName, SymbolicLink dwFlags) private
Referenced by TGServerService.ServerInstance.CreateSymlink().
static void TGServerService.ServerInstance.CreateSymlink (string link, string target) static private
Definition at line 91 of file Compiler.cs.
References TGServerService.ServerInstance.CreateSymbolicLink().
Referenced by TGServerService.ServerInstance.CompileImpl(), TGServerService.ServerInstance.GetStagingDir(), and TGServerService.ServerInstance.InitializeImpl().
         {
             if (!CreateSymbolicLink(new DirectoryInfo(link).FullName, new DirectoryInfo(target).FullName, File.Exists(target) ? SymbolicLink.File : SymbolicLink.Directory))
                 throw new Exception(String.Format("Failed to create symlink from {0} to {1}! Error: {2}", target, link, Marshal.GetLastWin32Error()));
         }
ByondStatus TGServerService.ServerInstance.CurrentStatus ()
Gets the current status of any BYOND updates
Implements TGServiceInterface.Components.ITGByond.
Definition at line 129 of file Byond.cs.
References TGServerService.ServerInstance.updateStat.
Referenced by TGServerService.ServerInstance.Start().
         {
             lock (ByondLock)
             {
                 return updateStat;
             }
         }
DreamDaemonStatus TGServerService.ServerInstance.DaemonStatus ()
Gets the status of DreamDaemon
Implements TGServiceInterface.Components.ITGDreamDaemon.
Definition at line 193 of file DreamDaemon.cs.
References TGServerService.ServerInstance.currentStatus.
Referenced by TGServerService.ServerInstance.CompileImpl(), TGServerService.ServerInstance.DisposeDreamDaemon(), TGServerService.ServerInstance.InitializeImpl(), TGServerService.ServerInstance.LoadServerChatCommands(), TGServerService.ServerInstance.Restart(), TGServerService.ServerInstance.SetSecurityLevel(), TGServerService.ServerInstance.Setup(), TGServerService.ServerInstance.StatusString(), and TGServerService.ServerInstance.UpdateToVersionImpl().
         {
             lock (watchdogLock)
             {
                 return currentStatus;
             }
         }
string TGServerService.ServerInstance.DeleteFile (string staticRelativePath, out bool unauthorized)
Deletes the target static file
Implements TGServiceInterface.Components.ITGConfig.
Definition at line 156 of file Config.cs.
References TGServerService.Service.CancelImpersonation(), TGServerService.Program.DeleteDirectory(), TGServerService.ServerInstance.RelativePath(), TGServerService.ServerInstance.StaticDirs, TGServerService.ServerInstance.WriteInfo(), and TGServerService.ServerInstance.WriteWarning().
         {
             var path = RelativePath(StaticDirs + '/' + staticRelativePath);   //do not use path.combine or it will try and take the root
             try
             {
                 lock (configLock)
                 {
                     var di1 = new DirectoryInfo(RelativePath(StaticDirs));
                     var fi = new FileInfo(path);
                     var di2 = new DirectoryInfo(fi.Directory.FullName);
                     var good = false;
                     while (di2 != null)
                     {
                         if (di2.FullName == di1.FullName)
{
                             good = true;
                             break;
                         }
                         else di2 = di2.Parent;
                     }
                     if (!good)
                     {
                         unauthorized = false;
                         return "Cannot delete above static directories!";
                     }
                     if (fi.Exists)
                         File.Delete(path);
                     else if (Directory.Exists(path))
                         Program.DeleteDirectory(path);
                     Service.CancelImpersonation();
                     WriteInfo("Delete of " + path, EventID.StaticDelete);
                     unauthorized = false;
                     return null;
                 }
             }
             catch (UnauthorizedAccessException e)
             {
                 //no need for the full stacktrace
                 unauthorized = true;
                 return e.Message;
             }
             catch (Exception e)
             {
                 unauthorized = false;
                 Service.CancelImpersonation();
                 WriteWarning(String.Format("Delete of {0} failed! Error: {1}", path, e.ToString()), EventID.StaticRead);
                 return e.ToString();
             }
         }
void TGServerService.ServerInstance.DeletePRList () private
Deletes the ServerInstance's PRJobFile
Definition at line 831 of file Repository.cs.
References TGServerService.ServerInstance.RelativePath(), and TGServerService.ServerInstance.WriteError().
Referenced by TGServerService.ServerInstance.Checkout(), TGServerService.ServerInstance.Clone(), TGServerService.ServerInstance.Commit(), TGServerService.ServerInstance.Reset(), and TGServerService.ServerInstance.UpdateImpl().
         {
             if (File.Exists(RelativePath(PRJobFile)))
                 try
                 {
                     File.Delete(RelativePath(PRJobFile));
                 }
                 catch (Exception e)
                 {
                     WriteError("Failed to delete PR list: " + e.ToString(), EventID.RepoPRListError);
                 }
         }
void TGServerService.ServerInstance.DisableGarbageCollectionNoLock () private
Turns off the gc.auto git config setting
Definition at line 289 of file Repository.cs.
Referenced by TGServerService.ServerInstance.Clone(), and TGServerService.ServerInstance.InitRepo().
         {
             Repo.Config.Set("gc.auto", false);
         }
void TGServerService.ServerInstance.Dispose (bool disposing) private
Implements the IDisposable pattern. Calls RunDisposals
Parameters
disposing if Dispose() was called manually, if it was from the finalizer
Definition at line 150 of file ServerInstance.cs.
References TGServerService.ServerInstance.RunDisposals().
Referenced by TGServerService.Tests.TestServerInstance.TestBasicInstantiation().
         {
             if (!disposedValue)
             {
                 if (disposing)
                 {
                     RunDisposals();
                     // TODO: dispose managed state (managed objects).
                 }
                 // TODO: free unmanaged resources (unmanaged objects) and override a finalizer below.
                 // TODO: set large fields to null.
                 disposedValue = true;
             }
         }
void TGServerService.ServerInstance.Dispose ()
Implements the IDisposable pattern
Definition at line 177 of file ServerInstance.cs.
         {
             // Do not change this code. Put cleanup code in Dispose(bool disposing) above.
             Dispose(true);
             // TODO: uncomment the following line if the finalizer is overridden above.
             // GC.SuppressFinalize(this);
         }
void TGServerService.ServerInstance.DisposeAdministration () private
Cleans up the ITGAdministration component
Definition at line 103 of file Administration.cs.
References TGServerService.RootAuthorizationManager.InstanceAuthManagers.
Referenced by TGServerService.ServerInstance.RunDisposals().
         {
             RootAuthorizationManager.InstanceAuthManagers.Remove(this);
         }
void TGServerService.ServerInstance.DisposeByond () private
Called when the ServerInstance is shutdown
Definition at line 97 of file Byond.cs.
References TGServerService.ServerInstance.CleanByondStaging().
Referenced by TGServerService.ServerInstance.RunDisposals().
         {
             lock (ByondLock)
             {
                 if (RevisionStaging != null)
                     RevisionStaging.Abort();
                 CleanByondStaging();
             }
         }
void TGServerService.ServerInstance.DisposeChat () private
Properly shuts down all ChatProviders
Definition at line 104 of file Chat.cs.
References TGServerService.IInstanceConfig.ChatProviderData, TGServerService.IInstanceConfig.ChatProviderEntropy, TGServerService.ServerInstance.Config, and TGServiceInterface.Helpers.EncryptData().
Referenced by TGServerService.ServerInstance.RunDisposals().
         {
             var infosList = new List<IList<string>>();
             foreach (var ChatProvider in ChatProviders)
             {
                 infosList.Add(ChatProvider.ProviderInfo().DataFields);
                 ChatProvider.Dispose();
             }
             ChatProviders = null;
             var rawdata = new JavaScriptSerializer().Serialize(infosList);
             Config.ChatProviderData = Helpers.EncryptData(rawdata, out string entrp);
             Config.ChatProviderEntropy = entrp;
         }
void TGServerService.ServerInstance.DisposeCompiler () private
Definition at line 79 of file Compiler.cs.
References TGServerService.ServerInstance.InitCompiler().
Referenced by TGServerService.ServerInstance.RunDisposals().
         {
             lock (CompilerLock)
             {
                 if (CompilerThread == null || !CompilerThread.IsAlive)
                     return;
                 CompilerThread.Abort(); //this will safely kill dm
                 InitCompiler(); //also cleanup
             }
         }
void TGServerService.ServerInstance.DisposeDreamDaemon () private
Either let go of Proc for reattachment or terminate it, depending on InstanceConfig.ReattachRequired of Config
Definition at line 160 of file DreamDaemon.cs.
References TGServerService.ServerInstance.Config, TGServerService.ServerInstance.DaemonStatus(), TGServerService.IInstanceConfig.ReattachRequired, TGServerService.ServerInstance.RelativePath(), TGServerService.ServerInstance.SendMessage(), TGServerService.ServerInstance.Stop(), TGServerService.ServerInstance.WorldAnnounce(), and TGServerService.ServerInstance.WriteCurrentDDLog().
Referenced by TGServerService.ServerInstance.RunDisposals().
         {
             var Detach = Config.ReattachRequired;
             bool RenameLog = false;
             if (DaemonStatus() == DreamDaemonStatus.Online)
             {
                 if (!Detach)
                 {
                     WorldAnnounce("Server service stopped");
                     Thread.Sleep(1000);
                 }
                 else
                 {
                     RenameLog = CurrentDDLog != null;
                     SendMessage("DD: Detaching watch dog for update!", MessageType.WatchdogInfo);
                     WriteCurrentDDLog("Service updating! Splitting diagnostics...");
                 }
             }
             else if (Detach)
                 Config.ReattachRequired = false;
             Stop();
             if (pcpu != null)
                 pcpu.Dispose();
             if (RenameLog)
                 try
                 {
                     var rrdd = RelativePath(ResourceDiagnosticsDir);
                     File.Move(Path.Combine(rrdd, CurrentDDLog), Path.Combine(rrdd, "SU-" + CurrentDDLog));
                 }
                 catch { }
         }
void TGServerService.ServerInstance.DisposeRepo () private
Cleans up Repo
Definition at line 178 of file Repository.cs.
Referenced by TGServerService.ServerInstance.Clone(), and TGServerService.ServerInstance.RunDisposals().
         {
             if (Repo != null)
             {
                 Repo.Dispose();
                 Repo = null;
             }
         }
bool TGServerService.ServerInstance.EventHandlerExists (string eventName) private
Check if an event handler for eventName exists
Parameters
eventName The name of the event
Returns
if the event handler exists, otherwise
Definition at line 38 of file PreactionHandler.cs.
References TGServerService.ServerInstance.GetEventPath().
Referenced by TGServerService.ServerInstance.HandleEvent().
         {
             return File.Exists(GetEventPath(eventName));
         }
bool TGServerService.ServerInstance.Exists ()
Check if the repository is valid, if not Setup(string, string) must be called
Implements TGServiceInterface.Components.ITGRepository.
Definition at line 188 of file Repository.cs.
References TGServerService.ServerInstance.RelativePath().
Referenced by TGServerService.ServerInstance.GenerateChangelogImpl(), TGServerService.ServerInstance.InitializeImpl(), and TGServerService.ServerInstance.InitRepo().
         {
             lock (RepoLock)
             {
                 return !Cloning && Repository.IsValid(RelativePath(RepoPath));
             }
         }
string TGServerService.ServerInstance.Fetch () private
Fetches origin
Returns
null on success, error message on failure
Definition at line 1071 of file Repository.cs.
References TGServerService.ServerInstance.GenerateFetchOptions().
Referenced by TGServerService.ServerInstance.Checkout(), TGServerService.ServerInstance.LocalIsRemote(), and TGServerService.ServerInstance.UpdateImpl().
         {
             try
             {
                 string logMessage = "";
                 var R = Repo.Network.Remotes["origin"];
                 IEnumerable<string> refSpecs = R.FetchRefSpecs.Select(X => X.Specification);
                 Commands.Fetch(Repo, R.Name, refSpecs, GenerateFetchOptions(), logMessage);
                 return null;
             }
             catch (Exception e)
             {
                 return e.ToString();
             }
         }
string TGServerService.ServerInstance.FindTheDroidsWereLookingFor (string search = null, bool useDomain = false) private
Set TheDroidsWereLookingFor based off either an search ed name or a string SecurityIdentifier from the config
Parameters
search The name of the group to search for
useDomain Recursive parameter used to check for the group using ContextType.Domain instead of ContextType.Machine
Returns
The name of the group allowed to access the ServerInstance if it could be found, otherwise
Definition at line 74 of file Administration.cs.
References TGServerService.IInstanceConfig.AuthorizedUserGroupSID, TGServerService.ServerInstance.Config, TGServerService.RootAuthorizationManager.InstanceAuthManagers, and TGServerService.IInstanceConfig.Save().
Referenced by TGServerService.ServerInstance.ServerInstance(), and TGServerService.ServerInstance.SetAuthorizedGroup().
         {
             RootAuthorizationManager.InstanceAuthManagers.Add(this);
             //find the group that is authorized to use the tools
             var pc = new PrincipalContext(useDomain ? ContextType.Domain : ContextType.Machine);
             var groupName = search ?? Config.AuthorizedUserGroupSID;
             if (String.IsNullOrWhiteSpace(groupName))
                 return null;
             var gp = GroupPrincipal.FindByIdentity(pc, search != null ? IdentityType.Name : IdentityType.Sid, groupName);
             if (gp == null)
             {
                 if (search != null)
                     //try again with all types
                     gp = GroupPrincipal.FindByIdentity(pc, search);
                 if (gp == null)
                     return useDomain ? null : FindTheDroidsWereLookingFor(search, true);
             }
             TheDroidsWereLookingFor = gp.Sid;
             if (search != null)
             {
                 Config.AuthorizedUserGroupSID = TheDroidsWereLookingFor.Value;
                 Config.Save();
             }
             return gp.Name;
         }
void TGServerService.ServerInstance.GenCommsKey () private
Definition at line 240 of file Interop.cs.
References TGServerService.ServerInstance.WriteInfo().
Referenced by TGServerService.ServerInstance.StartImpl().
         {
             var charsToRemove = new string[] { "!", "@", "#", "$", "%", "^", "&", "*", "(", ")", "_", "-", "+", "=", "[", "{", "]", "}", ";", ":", "<", ">", "|", ".", "/", "?" };
             serviceCommsKey = String.Empty;
             do {
                 var tmp = Membership.GeneratePassword(CommsKeyLen, 0);
                 foreach (var c in charsToRemove)
                     tmp = tmp.Replace(c, String.Empty);
                 serviceCommsKey += tmp;
             } while (serviceCommsKey.Length < CommsKeyLen);
             serviceCommsKey = serviceCommsKey.Substring(0, CommsKeyLen);
             WriteInfo("Service Comms Key set to: " + serviceCommsKey, EventID.CommsKeySet);
         }
string TGServerService.ServerInstance.GenerateChangelog (out string error)
Updates the html changelog
Implements TGServiceInterface.Components.ITGRepository.
Definition at line 1212 of file Repository.cs.
References TGServerService.ServerInstance.GenerateChangelogImpl().
         {
             return GenerateChangelogImpl(out error);
         }
string TGServerService.ServerInstance.GenerateChangelogImpl (out string error, bool recurse = false)
Updates the html changelog
Parameters
error on success, error on failure
recurse If , prevents a recursive call to this function after updating pip dependencies
Returns
The output of the python script
Definition at line 1223 of file Repository.cs.
References TGServerService.ServerInstance.Config, TGServerService.ServerInstance.Exists(), TGServerService.ServerInstance.GetCachedRepoConfig(), TGServerService.ServerInstance.RelativePath(), TGServerService.ServerInstance.WriteInfo(), and TGServerService.ServerInstance.WriteWarning().
Referenced by TGServerService.ServerInstance.GenerateChangelog().
         {
             var RConfig = GetCachedRepoConfig();
             if (RConfig == null)
             {
                 error = null;
                 return "Error loading changelog config!";
             }
             if (!RConfig.ChangelogSupport)
             {
                 error = null;
                 return null;
             }
             string ChangelogPy = RConfig.PathToChangelogPy;
             if (!Exists())
             {
                 error = "Repo does not exist!";
                 return null;
             }
             lock (RepoLock)
             {
                 if (RepoBusy)
                 {
                     error = "Repo is busy!";
                     return null;
                 }
                 if (!File.Exists(Path.Combine(RelativePath(RepoPath), ChangelogPy)))
                 {
                     error = "Missing changelog generation script!";
                     return null;
                 }
                 var Config = Properties.Settings.Default;
                 var PythonFile = Path.Combine(Config.PythonPath, "python.exe");
                 if (!File.Exists(PythonFile))
                 {
                     error = "Cannot locate python!";
                     return null;
                 }
                 try
                 {
                     string result;
                     int exitCode;
                     using (var python = new Process())
                     {
                         python.StartInfo.FileName = PythonFile;
                         python.StartInfo.Arguments = String.Format("{0} {1}", ChangelogPy, RConfig.ChangelogPyArguments);
                         python.StartInfo.UseShellExecute = false;
                         python.StartInfo.WorkingDirectory = new DirectoryInfo(RelativePath(RepoPath)).FullName;
                         python.StartInfo.RedirectStandardOutput = true;
                         python.Start();
                         using (StreamReader reader = python.StandardOutput)
{
                             result = reader.ReadToEnd();
                         }
                         python.WaitForExit();
                         exitCode = python.ExitCode;
                     }
                     if (exitCode != 0)
                     {
                         if (recurse || RConfig.PipDependancies.Count == 0)
{
                             error = "Script failed!";
                             return result;
                         }
                         //update pip deps and try again
                         string PipFile = Config.PythonPath + "/scripts/pip.exe";
                         foreach(var I in RConfig.PipDependancies)
                             using (var pip = new Process())
{
                                 pip.StartInfo.FileName = PipFile;
                                 pip.StartInfo.Arguments = "install " + I;
                                 pip.StartInfo.UseShellExecute = false;
                                 pip.StartInfo.RedirectStandardOutput = true;
                                 pip.Start();
                                 using (StreamReader reader = pip.StandardOutput)
{
                                     result += "\r\n---BEGIN-PIP-OUTPUT---\r\n" + reader.ReadToEnd();
                                 }
                                 pip.WaitForExit();
                                 if (pip.ExitCode != 0)
{
                                     error = "Script and pip failed!";
                                     return result;
                                 }
                             }
                         //and recurse
                         return GenerateChangelogImpl(out error, true);
                     }
                     error = null;
                     WriteInfo("Changelog generated" + error, EventID.RepoChangelog);
                     return result;
                 }
                 catch (Exception e)
                 {
                     error = e.ToString();
                     WriteWarning("Changelog generation failed: " + error, EventID.RepoChangelogFail);
                     return null;
                 }
             }
         }
FetchOptions TGServerService.ServerInstance.GenerateFetchOptions () private
Create FetchOptions that Prune and have the appropriate credentials and progress handler
Returns
Properly configured FetchOptions
Definition at line 1057 of file Repository.cs.
References TGServerService.ServerInstance.GenerateGitCredentials(), and TGServerService.ServerInstance.HandleTransferProgress().
Referenced by TGServerService.ServerInstance.Fetch(), and TGServerService.ServerInstance.MergePullRequest().
         {
             return new FetchOptions()
             {
                 CredentialsProvider = GenerateGitCredentials,
                 OnTransferProgress = HandleTransferProgress,
                 Prune = true,
             };
         }
Credentials TGServerService.ServerInstance.GenerateGitCredentials (string url, string usernameFromUrl, SupportedCredentialTypes types) private
SSH credentials callback. Properly sets up SSH keys for an authorization operation
Parameters
url Ignored
usernameFromUrl The username to use for the operation
types The SupportedCredentialTypes for the operation
Returns
The proper Credentials for the operation
Definition at line 1194 of file Repository.cs.
References TGServerService.ServerInstance.RelativePath().
Referenced by TGServerService.ServerInstance.Clone(), TGServerService.ServerInstance.GenerateFetchOptions(), TGServerService.ServerInstance.Push(), and TGServerService.ServerInstance.PushTestmergeCommit().
         {
             var user = usernameFromUrl ?? "git";
             if (types == SupportedCredentialTypes.UsernameQuery)
                 return new UsernameQueryCredentials()
                 {
                     Username = user,
                 };
             return new SshUserKeyCredentials()
             {
                 Username = user,
                 PrivateKey = RelativePath(PrivateKeyPath),
                 PublicKey = RelativePath(PublicKeyPath),
                 Passphrase = "",
             };
         }
string TGServerService.ServerInstance.GetBranch (out string error)
Gets the name of the current branch
Implements TGServiceInterface.Components.ITGRepository.
Definition at line 450 of file Repository.cs.
References TGServerService.ServerInstance.GetShaOrBranch().
         {
             return GetShaOrBranch(out error, true, false);
         }
RepoConfig TGServerService.ServerInstance.GetCachedRepoConfig () private
Gets the RepoConfig for CachedTGS3SettingsPath
Returns
The RepoConfig for CachedTGS3SettingsPath
Definition at line 134 of file Repository.cs.
References TGServerService.ServerInstance.RelativePath().
Referenced by TGServerService.ServerInstance.CompileImpl(), TGServerService.ServerInstance.GenerateChangelogImpl(), TGServerService.ServerInstance.InitialConfigureRepository(), TGServerService.ServerInstance.InitializeImpl(), TGServerService.ServerInstance.ReadText(), TGServerService.ServerInstance.RepoConfigsMatch(), and TGServerService.ServerInstance.SynchronizePush().
         {
             return new RepoConfig(RelativePath(CachedTGS3SettingsPath));
         }
string TGServerService.ServerInstance.GetCommitterEmail ()
Gets the email of the configured git committer
Implements TGServiceInterface.Components.ITGRepository.
Definition at line 1025 of file Repository.cs.
References TGServerService.IInstanceConfig.CommitterEmail, and TGServerService.ServerInstance.Config.
         {
             lock (RepoLock)
             {
                 return Config.CommitterEmail;
             }
         }
string TGServerService.ServerInstance.GetCommitterName ()
Gets the name of the configured git committer
Implements TGServiceInterface.Components.ITGRepository.
Definition at line 1007 of file Repository.cs.
References TGServerService.IInstanceConfig.CommitterName, and TGServerService.ServerInstance.Config.
         {
             lock (RepoLock)
             {
                 return Config.CommitterName;
             }
         }
string TGServerService.ServerInstance.GetCurrentAuthorizedGroup ()
Returns the name of the windows group allowed to use the service other than administrator
Implements TGServiceInterface.Components.ITGAdministration.
Definition at line 34 of file Administration.cs.
         {
             try
             {
                 if (TheDroidsWereLookingFor == null)
                     return "ADMIN";
                 string res = null;
                 try
                 {
                     res = GroupPrincipal.FindByIdentity(new PrincipalContext(ContextType.Machine), IdentityType.Sid, TheDroidsWereLookingFor.Value).Name;
                 }
                 catch { }
                 return res ?? GroupPrincipal.FindByIdentity(new PrincipalContext(ContextType.Domain), IdentityType.Sid, TheDroidsWereLookingFor.Value).Name;
             }
             catch
             {
                 return null;
             }
         }
IDictionary<string, IDictionary<string, string> > TGServerService.ServerInstance.GetCurrentPRList () private
Deserializes the PRJobFile
Returns
A IDictionary<TKey, TValue> of IDictionary<TKey, TValue>. The outer one is keyed by PR# the inner one is keyed by internal strings
Definition at line 848 of file Repository.cs.
References TGServerService.ServerInstance.RelativePath().
Referenced by TGServerService.ServerInstance.MergedPullRequests(), and TGServerService.ServerInstance.MergePullRequest().
         {
             if (!File.Exists(RelativePath(PRJobFile)))
                 return new Dictionary<string, IDictionary<string, string>>();
             var rawdata = File.ReadAllText(RelativePath(PRJobFile));
             var Deserializer = new JavaScriptSerializer();
             return Deserializer.Deserialize<IDictionary<string, IDictionary<string, string>>>(rawdata);
         }
string TGServerService.ServerInstance.GetError ()
Check the last update error. Checking this will clear the value
Implements TGServiceInterface.Components.ITGByond.
Definition at line 138 of file Byond.cs.
References TGServerService.ServerInstance.lastError.
         {
             lock (ByondLock)
             {
                 var error = lastError;
                 lastError = null;
                 return error;
             }
         }
string TGServerService.ServerInstance.GetEventPath (string eventName) private
Gets the path of an event given an eventName
Parameters
eventName The name of the event
Returns
The path to the event handler
Definition at line 28 of file PreactionHandler.cs.
References TGServerService.ServerInstance.RelativePath().
Referenced by TGServerService.ServerInstance.EventHandlerExists(), and TGServerService.ServerInstance.HandleEvent().
         {
             return string.Format("{0}{1}.bat", RelativePath(EventFolder), eventName);
         }
string TGServerService.ServerInstance.GetHead (bool useTracked, out string error)
Gets the sha of the current HEAD
Implements TGServiceInterface.Components.ITGRepository.
Definition at line 444 of file Repository.cs.
References TGServerService.ServerInstance.GetShaOrBranch().
Referenced by TGServerService.ServerInstance.CompileImpl().
         {
             return GetShaOrBranch(out error, false, useTracked);
         }
string TGServerService.ServerInstance.GetRemote (out string error)
Gets the url of the current origin
Implements TGServiceInterface.Components.ITGRepository.
Definition at line 456 of file Repository.cs.
References TGServerService.ServerInstance.LoadRepo().
         {
             try
             {
                 var res = LoadRepo();
                 if (res != null)
                 {
                     error = res;
                     return null;
                 }
                 error = null;
                 return Repo.Network.Remotes["origin"].Url;
             }
             catch (Exception e)
             {
                 error = e.ToString();
                 return null;
             }
         }
string TGServerService.ServerInstance.GetShaOrBranch (out string error, bool branch, bool tracked) private
Gets the SHA or branch name of the Repo's HEAD
Parameters
error on success, error message on failure
branch If , returns the branch name instead of the SHA
tracked If , returns the tracked branch SHA and ignores branch
Returns
The SHA or branch name of the Repo's HEAD
Definition at line 417 of file Repository.cs.
References TGServerService.ServerInstance.LoadRepo().
Referenced by TGServerService.ServerInstance.GetBranch(), and TGServerService.ServerInstance.GetHead().
         {
             lock (RepoLock)
             {
                 var result = LoadRepo();
                 if (result != null)
                 {
                     error = result;
                     return null;
                 }
                 try
                 {
                     error = null;
                     if (tracked && Repo.Head.TrackedBranch != null)
                         return Repo.Head.TrackedBranch.Tip.Sha;
                     return branch ? Repo.Head.FriendlyName : Repo.Head.Tip.Sha;
                 }
                 catch (Exception e)
                 {
                     error = e.ToString();
                     return null;
                 }
             }
         }
string TGServerService.ServerInstance.GetStagingDir () private
Definition at line 230 of file Compiler.cs.
References TGServerService.ServerInstance.Config, TGServerService.ServerInstance.CreateSymlink(), TGServerService.ServerInstance.InvertDirectory(), TGServerService.IInstanceConfig.ProjectName, and TGServerService.ServerInstance.RelativePath().
Referenced by TGServerService.ServerInstance.CompileImpl().
         {
             string TheDir;
             if (!Directory.Exists(RelativePath(GameDirLive)))
                 TheDir = GameDirA;
             else
             {
                 File.Create(RelativePath(LiveDirTest)).Close();
                 try
                 {
                     if (File.Exists(RelativePath(ADirTest)))
                         TheDir = GameDirA;
                     else if (File.Exists(RelativePath(BDirTest)))
                         TheDir = GameDirB;
                     else
                         throw new Exception("Unable to determine current live directory!");
                 }
                 finally
                 {
                     File.Delete(RelativePath(LiveDirTest));
                 }
                 TheDir = InvertDirectory(TheDir);
             }
             //So TheDir is what the Live folder is NOT pointing to
             //Now we need to check if DD is running that folder and swap it if necessary
             var rsclock = RelativePath(TheDir + "/" + Config.ProjectName + ".rsc.lk");
             if (File.Exists(rsclock))
             {
                 try
                 {
                     File.Delete(rsclock);
                 }
                 catch   //held open by byond
                 {
                     //This means there is a staged update waiting to be applied, we have to unstage it before we can work
                     Directory.Delete(RelativePath(GameDirLive));
                     CreateSymlink(RelativePath(GameDirLive), TheDir);
                     return RelativePath(InvertDirectory(TheDir));
                 }
             }
             return RelativePath(TheDir);
         }
CompilerStatus TGServerService.ServerInstance.GetStatus ()
Returns the current compiler status
Implements TGServiceInterface.Components.ITGCompiler.
Definition at line 59 of file Compiler.cs.
References TGServerService.ServerInstance.compilerCurrentStatus.
         {
             lock (CompilerLock)
             {
                 return compilerCurrentStatus;
             }
         }
string TGServerService.ServerInstance.GetVersion (ByondVersion type)
Get the currently installed version as a string formatted as Major.Minor
Implements TGServiceInterface.Components.ITGByond.
Definition at line 149 of file Byond.cs.
References TGServerService.ServerInstance.RelativePath(), and TGServerService.ServerInstance.VersionFile.
Referenced by TGServerService.ServerInstance.ApplyStagedUpdate(), TGServerService.ServerInstance.CanStart(), and TGServerService.ServerInstance.CompileImpl().
         {
             try
             {
                 lock (ByondLock)
                 {
                     if (type == ByondVersion.Latest)
                     {
                         //get the latest version from the website
                         HttpWebRequest request = (HttpWebRequest)WebRequest.Create(ByondLatestURL);
                         var results = new List<string>();
                         using (HttpWebResponse response = (HttpWebResponse)request.GetResponse())
{
                             using (StreamReader reader = new StreamReader(response.GetResponseStream()))
{
                                 string html = reader.ReadToEnd();
                                 Regex regex = new Regex("\\\"([^\"]*)\\\"");
                                 MatchCollection matches = regex.Matches(html);
                                 foreach (Match match in matches)
                                     if (match.Success && match.Value.Contains("_byond.exe"))
                                         results.Add(match.Value.Replace("\"", "").Replace("_byond.exe", ""));
                             }
                         }
                         results.Sort();
                         results.Reverse();
                         return results.Count > 0 ? results[0] : null;
                     }
                     else
                     {
                         string DirToUse = RelativePath(type == ByondVersion.Staged ? StagingDirectoryInner : ByondDirectory);
                         if (Directory.Exists(DirToUse))
{
                             string file = DirToUse + VersionFile;
                             if (File.Exists(file))
                                 return File.ReadAllText(file);
                         }
                     }
                     return null;
                 }
             }
             catch (Exception e)
             {
                 return "Error: " + e.ToString();
             }
         }
void TGServerService.ServerInstance.HandleCheckoutProgress (string path, int completedSteps, int totalSteps) private
Updates currentProgress with the progess of the current Repo checkout operation
Parameters
path Ignored
completedSteps Dividend for progress calculation
totalSteps Divisor for progress calculation
Definition at line 213 of file Repository.cs.
Referenced by TGServerService.ServerInstance.Checkout(), TGServerService.ServerInstance.Clone(), and TGServerService.ServerInstance.MergeBranch().
         {
             currentProgress = (int)(((float)completedSteps / totalSteps) * 100);
         }
void TGServerService.ServerInstance.HandleCommand (string cmd) private
Definition at line 85 of file Interop.cs.
References TGServerService.ServerInstance.ChatConnectivityCheck(), TGServerService.ServerInstance.CheckAPIVersionConstraints(), TGServerService.ServerInstance.CompilerLock, TGServerService.ServerInstance.KillMe(), TGServerService.ServerInstance.SendCommand(), TGServerService.ServerInstance.SendMessage(), TGServerService.ServerInstance.UpdateStaged, TGServerService.ServerInstance.Version(), TGServerService.ServerInstance.WriteCurrentDDLog(), TGServerService.ServerInstance.WriteInfo(), and TGServerService.ServerInstance.WriteWarning().
Referenced by TGServerService.ServerInstance.InteropMessage().
         {
             var splits = new List<string>(cmd.Split(' '));
             cmd = splits[0];
             splits.RemoveAt(0);
             bool APIValid;
             lock (topicLock)
             {
                 APIValid = CheckAPIVersionConstraints();
             }
             if (!APIValid && cmd != SRAPIVersion)
                 return; //SPEAK THE LANGUAGE!!!
             switch (cmd)
             {
                 case SRIRCBroadcast:
                     SendMessage("GAME: " + String.Join(" ", splits), MessageType.GameInfo);
                     break;
                 case SRKillProcess:
                     KillMe();
                     break;
                 case SRIRCAdminChannelMessage:
                     SendMessage("RELAY: " + String.Join(" ", splits), MessageType.AdminInfo);
                     break;
                 case SRWorldReboot:
                     WriteInfo("World Rebooted", EventID.WorldReboot);
                     WriteCurrentDDLog("World rebooted");
                     ServerChatCommands = null;
                     ChatConnectivityCheck();
                     lock (CompilerLock)
                     {
                         if (UpdateStaged)
{
                             UpdateStaged = false;
                             lock (topicLock)
{
                                 GameAPIVersion = null;  //needs updating
                             }
                             WriteInfo("Staged update applied", EventID.ServerUpdateApplied);
                         }
                     }
                     break;
                 case SRAPIVersion:
                     lock (topicLock)
                     {
                         try
{
                             GameAPIVersion = new Version(splits[0]);
                             if (!CheckAPIVersionConstraints())
                                 throw new Exception();
                         }
                         catch
{
                             WriteWarning(String.Format("API version of the game ({0}) is incompatible with the current supported API versions (3.{2}.x.x). Interop disabled.", splits.Count > 1 ? splits[1] : "NULL", AllowedMajorAPIVersion), EventID.APIVersionMismatch);
                             GameAPIVersion = null;
                             break;
                         }
                     }
                     //This needs to be done asyncronously otherwise DD won't be able to process it, because it's waiting for THIS THREAD to return
                     ThreadPool.QueueUserWorkItem(_ => SendCommand(SCAPICompat));
                     break;
             }
         }
bool TGServerService.ServerInstance.HandleEvent (string eventName) private
Runs an event named eventName if it exists
Parameters
eventName The name of the event
Returns
if the event handler exists and failed to run, otherwise
Definition at line 48 of file PreactionHandler.cs.
References TGServerService.ServerInstance.EventHandlerExists(), TGServerService.ServerInstance.GetEventPath(), TGServerService.ServerInstance.WriteInfo(), and TGServerService.ServerInstance.WriteWarning().
Referenced by TGServerService.ServerInstance.PostcompileHook(), and TGServerService.ServerInstance.PrecompileHook().
         {
             if (!EventHandlerExists(eventName))
             {
                 // We don't need a handler, so let's just fail silently.
                 return true;
             }
             var process = new Process
             {
                 StartInfo = new ProcessStartInfo
                 {
                     FileName = GetEventPath(eventName),
                     UseShellExecute = false,
                     RedirectStandardOutput = true,
                     RedirectStandardError = true,
                     CreateNoWindow = true
                 }
             };
             process.Start();
             process.WaitForExit();
             var stdout = process.StandardOutput.ReadToEnd();
             var stderr = process.StandardError.ReadToEnd();
             var success = process.ExitCode == 0;
             var eventData = String.Format("Preaction Event: {0} @ {1} ran. Stdout:\n{2}\nStderr:\n{3}", eventName, GetEventPath(eventName), stdout, stderr);
             if (success)
                 WriteInfo(eventData, EventID.PreactionEvent);
             else
                 WriteWarning(eventData, EventID.PreactionFail);
             return success;
         }
bool TGServerService.ServerInstance.HandleTransferProgress (TransferProgress progress) private
Updates currentProgress with the progess of the current Repo transfer operation
Parameters
progress The TransferProgress of the current Repo transfer operation
Returns
Definition at line 201 of file Repository.cs.
Referenced by TGServerService.ServerInstance.Clone(), and TGServerService.ServerInstance.GenerateFetchOptions().
         {
             currentProgress = ((int)(((float)progress.ReceivedObjects / progress.TotalObjects) * 100) / 2) +( (int)(((float)progress.IndexedObjects / progress.TotalObjects) * 100) / 2);
             return true;
         }
void TGServerService.ServerInstance.InitByond () private
Called when the ServerInstance is setup. Prepares the BYOND updater
Definition at line 77 of file Byond.cs.
References TGServerService.ServerInstance.CleanByondStaging().
Referenced by TGServerService.ServerInstance.ServerInstance().
         {
             CleanByondStaging();
         }
void TGServerService.ServerInstance.InitChat ()
Set up the ChatProviders for the ServerInstance
Definition at line 31 of file Chat.cs.
References TGServerService.ServerInstance.ChatProvider_OnChatMessage(), TGServerService.ChatProviders.IChatProvider.Connect(), TGServerService.ServerInstance.InitProviderInfos(), TGServerService.ChatProviders.IChatProvider.OnChatMessage, TGServerService.ServerInstance.WriteError(), and TGServerService.ServerInstance.WriteWarning().
Referenced by TGServerService.ServerInstance.ServerInstance().
         {
             var infos = InitProviderInfos();
             ChatProviders = new List<IChatProvider>(infos.Count);
             foreach (var info in infos)
             {
                 IChatProvider chatProvider;
                 try
                 {
                     switch (info.Provider)
                     {
                         case ChatProvider.Discord:
                             chatProvider = new DiscordChatProvider(info);
                             break;
                         case ChatProvider.IRC:
                             chatProvider = new IRCChatProvider(info);
                             break;
                         default:
                             WriteError(String.Format("Invalid chat provider: {0}", info.Provider), EventID.InvalidChatProvider);
                             continue;
                     }
                 }
                 catch (Exception e)
                 {
                     WriteError(String.Format("Failed to start chat provider {0}! Error: {1}", info.Provider, e.ToString()), EventID.ChatProviderStartFail);
                     continue;
                 }
                 chatProvider.OnChatMessage += ChatProvider_OnChatMessage;
                 var res = chatProvider.Connect();
                 if (res != null)
                     WriteWarning(String.Format("Unable to connect to chat! Provider {0}, Error: {1}", chatProvider.GetType().ToString(), res), EventID.ChatConnectFail);
                 ChatProviders.Add(chatProvider);
             }
         }
void TGServerService.ServerInstance.InitCompiler () private
Definition at line 50 of file Compiler.cs.
References TGServerService.ServerInstance.IsInitialized(), and TGServerService.ServerInstance.RelativePath().
Referenced by TGServerService.ServerInstance.DisposeCompiler(), and TGServerService.ServerInstance.ServerInstance().
         {
             var rldt = RelativePath(LiveDirTest);
             if (File.Exists(rldt))
                 File.Delete(rldt);
             compilerCurrentStatus = IsInitialized();
         }
void TGServerService.ServerInstance.InitDreamDaemon () private
Setup or reattach the watchdog, depending on InstanceConfig.ReattachRequired of Config, and create the DiagnosticsDir
Definition at line 97 of file DreamDaemon.cs.
References TGServerService.IInstanceConfig.Autostart, TGServerService.ServerInstance.ByondDirectory, TGServerService.ServerInstance.Config, TGServerService.ServerInstance.GameAPIVersion, TGServerService.ServerInstance.Reattach(), TGServerService.IInstanceConfig.ReattachAPIVersion, TGServerService.IInstanceConfig.ReattachCommsKey, TGServerService.IInstanceConfig.ReattachPort, TGServerService.IInstanceConfig.ReattachProcessID, TGServerService.IInstanceConfig.ReattachRequired, TGServerService.ServerInstance.RelativePath(), TGServerService.IInstanceConfig.Save(), TGServerService.ServerInstance.SendMessage(), TGServerService.ServerInstance.serviceCommsKey, TGServerService.ServerInstance.Start(), TGServerService.ServerInstance.Version(), TGServerService.ServerInstance.Watchdog(), TGServerService.ServerInstance.WriteError(), and TGServerService.ServerInstance.WriteInfo().
Referenced by TGServerService.ServerInstance.ServerInstance().
         {
             Directory.CreateDirectory(RelativePath(DiagnosticsDir));
             Directory.CreateDirectory(RelativePath(ResourceDiagnosticsDir));
             var Reattach = Config.ReattachRequired;
             if (Reattach)
                 try
                 {
                     Proc = Process.GetProcessById(Config.ReattachProcessID);
                     if (Proc == null)
                         throw new Exception("GetProcessById returned null!");
                     WriteInfo("Reattached to running DD process!", EventID.DDReattachSuccess);
                     ThreadPool.QueueUserWorkItem(_ =>
                     {
                         Thread.Sleep(5000);
                         SendMessage("DD: Update complete. Watch dog reactivated...", MessageType.WatchdogInfo);
                     });
                     //start wd
                     lock (restartLock)
                     {
                         RestartInProgress = true;
                         ReattachInsteadOfRestart = true;
                     }
                     currentPort = Config.ReattachPort;
                     serviceCommsKey = Config.ReattachCommsKey;
                     try
                     {
                         GameAPIVersion = new Version(Config.ReattachAPIVersion);
                     }
                     catch { }
                     currentStatus = DreamDaemonStatus.Online;
                     DDWatchdog = new Thread(new ThreadStart(Watchdog));
                     DDWatchdog.Start();
                 }
                 catch (Exception e)
                 {
                     WriteError(String.Format("Failed to reattach to DreamDaemon! PID: {0}. Exception: {1}", Config.ReattachProcessID, e.ToString()), EventID.DDReattachFail);
                 }
                 finally
                 {
                     Config.ReattachRequired = false;
                     Config.Save();
                 }
             if (Proc == null)
                 Proc = new Process();
             Proc.StartInfo.FileName = RelativePath(ByondDirectory + "/bin/dreamdaemon.exe");
             Proc.StartInfo.UseShellExecute = false;
             if (Reattach)
                 return;
             //autostart the server
             if (Config.Autostart)
                 //break this off so we don't hold up starting the service
                 ThreadPool.QueueUserWorkItem(_ => { Start(); });
         }
void TGServerService.ServerInstance.InitEventHandlers () private
Creates the EventFolder
Definition at line 18 of file PreactionHandler.cs.
References TGServerService.ServerInstance.RelativePath().
Referenced by TGServerService.ServerInstance.ServerInstance().
         {
             Directory.CreateDirectory(RelativePath(EventFolder));
         }
void TGServerService.ServerInstance.InitialConfigureRepository () private
Initial setup for the StaticDirs and CachedTGS3SettingsPath
Definition at line 342 of file Repository.cs.
References TGServerService.ServerInstance.Config, TGServerService.Program.CopyDirectory(), TGServerService.Program.CopyFileForceDirectories(), TGServerService.ServerInstance.GetCachedRepoConfig(), TGServerService.ServerInstance.RelativePath(), TGServerService.ServerInstance.StaticDirs, TGServerService.ServerInstance.UpdateBridgeDll(), TGServerService.ServerInstance.UpdateTGS3Json(), TGServerService.ServerInstance.WriteError(), and TGServerService.ServerInstance.WriteWarning().
Referenced by TGServerService.ServerInstance.Clone(), and TGServerService.ServerInstance.RecreateStaticFolder().
         {
             Directory.CreateDirectory(RelativePath(StaticDirs));
             UpdateBridgeDll(false);
             UpdateTGS3Json();
             var Config = GetCachedRepoConfig(); //RepoBusy is set if we're here
             foreach(var I in Config.StaticDirectoryPaths)
             {
                 try
                 {
                     var source = Path.Combine(RelativePath(RepoPath), I);
                     var dest = Path.Combine(RelativePath(StaticDirs), I);
                     if (Directory.Exists(source))
                         Program.CopyDirectory(source, dest);
                     else
                         Directory.CreateDirectory(dest);
                 }
                 catch
                 {
                     WriteError("Could not setup static directory: " + I, EventID.RepoConfigurationFail);
                 }
             }
             foreach(var I in Config.DLLPaths)
             {
                 try
                 {
                     var source = Path.Combine(RelativePath(RepoPath), I);
                     if (!File.Exists(source))
                     {
                         WriteWarning("Could not find DLL: " + I, EventID.RepoConfigurationFail);
                         continue;
                     }
                     var dest = Path.Combine(RelativePath(StaticDirs), I);
                     Program.CopyFileForceDirectories(source, dest, false);
                 }
                 catch
                 {
                     WriteError("Could not setup static DLL: " + I, EventID.RepoConfigurationFail);
                 }
             }
         }
bool TGServerService.ServerInstance.Initialize ()
Sets up the symlinks for hotswapping game code. This will reset everything in the Game folder. Requires the repository to be set up and locks it once the compilation stage starts. Runs asyncronously from this call
Implements TGServiceInterface.Components.ITGCompiler.
Definition at line 104 of file Compiler.cs.
References TGServerService.ServerInstance.CompilerIdleNoLock(), and TGServerService.ServerInstance.InitializeImpl().
         {
             lock (CompilerLock)
             {
                 if (!CompilerIdleNoLock())
                     return false;
                 lastCompilerError = null;
                 compilerCurrentStatus = CompilerStatus.Initializing;
                 CompilerThread = new Thread(new ThreadStart(InitializeImpl));
                 CompilerThread.Start();
                 return true;
             }
         }
void TGServerService.ServerInstance.InitializeImpl ()
Definition at line 143 of file Compiler.cs.
References TGServerService.ServerInstance.BridgeDLLName, TGServerService.ServerInstance.CleanGameFolder(), TGServerService.ServerInstance.CompileImpl(), TGServerService.ServerInstance.CreateSymlink(), TGServerService.ServerInstance.DaemonStatus(), TGServerService.Program.DeleteDirectory(), TGServerService.ServerInstance.Exists(), TGServerService.ServerInstance.GetCachedRepoConfig(), TGServerService.ServerInstance.IsInitialized(), TGServerService.ServerInstance.RelativePath(), TGServerService.ServerInstance.RepoConfigsMatch(), TGServerService.ServerInstance.SendMessage(), and TGServerService.ServerInstance.WriteError().
Referenced by TGServerService.ServerInstance.Initialize().
         {
             try
             {
                 if (DaemonStatus() != DreamDaemonStatus.Offline)
                 {
                     lock (CompilerLock)
                     {
                         lastCompilerError = "Dream daemon must not be running";
                         compilerCurrentStatus = IsInitialized();
                         return;
                     }
                 }
                 if (!Exists()) //repo
                 {
                     lock (CompilerLock)
                     {
                         lastCompilerError = "Repository is not setup!";
                         compilerCurrentStatus = IsInitialized();
                         return;
                     }
                 }
                 if (!RepoConfigsMatch())
                 {
                     lock (CompilerLock)
                     {
                         lastCompilerError = "Repository TGS3.json does not match cached version! Please update the config appropriately!";
                         compilerCurrentStatus = IsInitialized();
                         return;
                     }
                 }
                 try
                 {
                     SendMessage("DM: Setting up symlinks...", MessageType.DeveloperInfo);
                     CleanGameFolder();
                     Program.DeleteDirectory(RelativePath(GameDir));
                     Directory.CreateDirectory(RelativePath(GameDirA));
                     Directory.CreateDirectory(RelativePath(GameDirB));
                     var rep_config = GetCachedRepoConfig();
                     if (rep_config != null) {
                         foreach (var I in rep_config.StaticDirectoryPaths)
                             CreateSymlink(RelativePath(Path.Combine(GameDirA, I)), RelativePath(Path.Combine(StaticDirs, I)));
                         foreach (var I in rep_config.DLLPaths)
                             CreateSymlink(RelativePath(Path.Combine(GameDirA, I)), RelativePath(Path.Combine(StaticDirs, I)));
                     }
                     var rbdlln = RelativePath(BridgeDLLName);
                     CreateSymlink(RelativePath(Path.Combine(GameDirA, BridgeDLLName)), rbdlln);
                     CreateSymlink(RelativePath(Path.Combine(GameDirB, BridgeDLLName)), rbdlln);
                     CreateSymlink(RelativePath(GameDirLive), RelativePath(GameDirA));
                     lock (CompilerLock)
                     {
                         compilerCurrentStatus = CompilerStatus.Compiling;
                         silentCompile = true;
                     }
                 }
                 catch (ThreadAbortException)
                 {
                     return;
                 }
                 catch (Exception e)
                 {
                     lock (CompilerLock)
                     {
                         SendMessage("DM: Setup failed!", MessageType.DeveloperInfo);
                         WriteError("Compiler Initialization Error: " + e.ToString(), EventID.DMInitializeCrash);
                         lastCompilerError = e.ToString();
                         compilerCurrentStatus = CompilerStatus.Uninitialized;
                         return;
                     }
                 }
             }
             catch (ThreadAbortException)
             {
                 return;
             }
             CompileImpl();
         }
IList<ChatSetupInfo> TGServerService.ServerInstance.InitProviderInfos () private
Returns a list of ChatSetupInfos loaded from the config or the defaults if none are set
Returns
A list of ChatSetupInfos loaded from the config or the defaults if none are set
Definition at line 134 of file Chat.cs.
References TGServerService.IInstanceConfig.ChatProviderData, TGServerService.IInstanceConfig.ChatProviderEntropy, TGServerService.ServerInstance.Config, TGServiceInterface.Helpers.DecryptData(), TGServerService.IInstanceConfig.Name, and TGServerService.ServerInstance.UninitializedString.
Referenced by TGServerService.ServerInstance.InitChat().
         {
             lock (ChatLock)
             {
                 var rawdata = Config.ChatProviderData;
                 if (rawdata == UninitializedString)
                     return new List<ChatSetupInfo>() { new IRCSetupInfo() { Nickname = Config.Name }, new DiscordSetupInfo() };
                 string plaintext;
                 try
                 {
                     plaintext = Helpers.DecryptData(rawdata, Config.ChatProviderEntropy);
                     var lists = new JavaScriptSerializer().Deserialize<List<List<string>>>(plaintext);
                     var output = new List<ChatSetupInfo>(lists.Count);
                     var foundirc = 0;
                     var founddiscord = 0;
                     foreach (var l in lists)
                     {
                         var info = new ChatSetupInfo(l);
                         if (info.Provider == ChatProvider.Discord)
                             ++founddiscord;
                         else if (info.Provider == ChatProvider.IRC)
                             ++foundirc;
                         output.Add(info);
                     }
                     if (foundirc != 1 || founddiscord != 1)
                         throw new Exception();
                     return output;
                 }
                 catch
                 {
                     Config.ChatProviderData = UninitializedString;
                 }
             }
             //if we get here we want to retry
             return InitProviderInfos();
         }
void TGServerService.ServerInstance.InitRepo () private
Initializes the repository
Definition at line 99 of file Repository.cs.
References TGServerService.IInstanceConfig.AutoUpdateInterval, TGServerService.ServerInstance.autoUpdateTimer, TGServerService.ServerInstance.AutoUpdateTimer_Elapsed(), TGServerService.ServerInstance.Config, TGServerService.ServerInstance.DisableGarbageCollectionNoLock(), TGServerService.ServerInstance.Exists(), TGServerService.ServerInstance.LoadRepo(), TGServerService.ServerInstance.RelativePath(), TGServerService.ServerInstance.SetAutoUpdateInterval(), and TGServerService.ServerInstance.UpdateBridgeDll().
Referenced by TGServerService.ServerInstance.ServerInstance().
         {
             Directory.CreateDirectory(RelativePath(RepoKeyDir));
             if(Exists())
                 UpdateBridgeDll(false);
             if(LoadRepo() == null)
                 DisableGarbageCollectionNoLock();
             //start the autoupdate timer
             autoUpdateTimer.Elapsed += AutoUpdateTimer_Elapsed;
             SetAutoUpdateInterval(Config.AutoUpdateInterval);
         }
bool TGServerService.ServerInstance.InteropMessage (string command)
Called from /world/ExportService(command)
Implements TGServiceInterface.Components.ITGInterop.
Definition at line 255 of file Interop.cs.
References TGServerService.ServerInstance.HandleCommand(), and TGServerService.ServerInstance.WriteWarning().
         {
             try
             {
                 HandleCommand(command);
                 return true;
             }
             catch(Exception e)
             {
                 WriteWarning(String.Format("Handle command for \"{0}\" failed: {1}", command, e.ToString()), EventID.InteropCallException);
                 return false;
             }
         }
string TGServerService.ServerInstance.InvertDirectory (string gameDirectory) private
Definition at line 278 of file Compiler.cs.
References TGServerService.ServerInstance.GameDirA, and TGServerService.ServerInstance.GameDirB.
Referenced by TGServerService.ServerInstance.GetStagingDir().
         {
             if (gameDirectory == GameDirA)
                 return GameDirB;
             else
                 return GameDirA;
         }
CompilerStatus TGServerService.ServerInstance.IsInitialized () private
Definition at line 119 of file Compiler.cs.
References TGServerService.ServerInstance.BridgeDLLName, and TGServerService.ServerInstance.RelativePath().
Referenced by TGServerService.ServerInstance.CompileImpl(), TGServerService.ServerInstance.InitCompiler(), and TGServerService.ServerInstance.InitializeImpl().
         {
             if (File.Exists(RelativePath(Path.Combine(GameDirLive, BridgeDLLName))))    //its a good tell, jim
                 return CompilerStatus.Initialized;
             return CompilerStatus.Uninitialized;
         }
void TGServerService.ServerInstance.KillMe ()
Definition at line 249 of file DreamDaemon.cs.
References TGServerService.ServerInstance.Restart(), and TGServerService.ServerInstance.Stop().
Referenced by TGServerService.ServerInstance.HandleCommand().
         {
             bool DoRestart;
             lock (watchdogLock)
             {
                 DoRestart = AwaitingShutdown == ShutdownRequestPhase.None;
                 if (!DoRestart)
                     AwaitingShutdown = ShutdownRequestPhase.Pinged;
             }
             //Do this is a seperate thread or we'll kill this thread in the middle of rebooting
             if (DoRestart)
                 ThreadPool.QueueUserWorkItem(_ => { Restart(); });
             else
                 ThreadPool.QueueUserWorkItem(_ => { Stop(); });
         }
IDictionary<string, string> TGServerService.ServerInstance.ListBackups (out string error)
Lists tags in the repository created by the ServerInstance
Parameters
error on success, error message on failure
Returns
A dictionary of tag title -> commit SHA on success, on failure
Implements TGServiceInterface.Components.ITGRepository.
Definition at line 776 of file Repository.cs.
References TGServerService.ServerInstance.LoadRepo().
         {
             try
             {
                 lock (RepoLock)
                 {
                     error = LoadRepo();
                     if (error != null)
                         return null;
                     var res = new Dictionary<string, string>();
                     foreach (var T in Repo.Tags)
                         if (T.FriendlyName.Contains("TGS"))
                             res.Add(T.FriendlyName, T.Target.Sha);
                     return res;
                 }
             }
             catch (Exception e)
             {
                 error = e.ToString();
                 return null;
             }
         }
IList<string> TGServerService.ServerInstance.ListStaticDirectory (string subDir, out string error, out bool unauthorized)
Returns the file contents of the specified server directory Subdirectories will be prefixed with '/'
Implements TGServiceInterface.Components.ITGConfig.
Definition at line 211 of file Config.cs.
References TGServerService.ServerInstance.RelativePath(), and TGServerService.ServerInstance.StaticDirs.
         {
             try
             {
                 if (!Directory.Exists(RelativePath(StaticDirs)))
                 {
                     error = null;
                     unauthorized = false;
                     return new List<string>();
                 }
                 DirectoryInfo dirToEnum = new DirectoryInfo(RelativePath(StaticDirs) + '/' + subDir ?? ""); //do not use path.combine or it will try and take the root
                 var result = new List<string>();
                 foreach (var I in dirToEnum.GetFiles())
                     result.Add(I.Name);
                 foreach (var I in dirToEnum.GetDirectories())
                     result.Add('/' + I.Name);
                 error = null;
                 unauthorized = false;
                 return result;
             }
             catch (UnauthorizedAccessException e)
             {
                 //no need for the full stacktrace
                 error = e.Message;
                 unauthorized = true;
                 return null;
             }
             catch (Exception e)
             {
                 error = e.ToString();
                 unauthorized = false;
                 return null;
             }
         }
string TGServerService.ServerInstance.LiveSha ()
Gets the current staged or live commit SHA
Returns
The current staged or live commit SHA
Definition at line 1381 of file Repository.cs.
References TGServerService.ServerInstance.LiveTrackingBranch.
         {
             var B = Repo.Branches[LiveTrackingBranch];
             return B != null ? B.Tip.Sha : "UNKNOWN";
         }
string TGServerService.ServerInstance.LoadRepo () private
Initializes Repo
Returns
on success, error message on failure
Definition at line 158 of file Repository.cs.
References TGServerService.ServerInstance.RelativePath().
Referenced by TGServerService.ServerInstance.Checkout(), TGServerService.ServerInstance.Clone(), TGServerService.ServerInstance.Commit(), TGServerService.ServerInstance.CreateBackup(), TGServerService.ServerInstance.GetRemote(), TGServerService.ServerInstance.GetShaOrBranch(), TGServerService.ServerInstance.InitRepo(), TGServerService.ServerInstance.ListBackups(), TGServerService.ServerInstance.LocalIsRemote(), TGServerService.ServerInstance.MergedPullRequests(), TGServerService.ServerInstance.MergePullRequest(), TGServerService.ServerInstance.Push(), TGServerService.ServerInstance.RepoConfigsMatch(), TGServerService.ServerInstance.Reset(), TGServerService.ServerInstance.UpdateImpl(), and TGServerService.ServerInstance.UpdateLiveSha().
         {
             if (Repo != null)
                 return null;
             if (!Repository.IsValid(RelativePath(RepoPath)))
                 return "Repository does not exist";
             try
             {
                 Repo = new Repository(RelativePath(RepoPath));
             }
             catch (Exception e)
             {
                 return e.ToString();
             }
             return null;
         }
void TGServerService.ServerInstance.LoadServerChatCommands () private
Definition at line 67 of file Interop.cs.
References TGServerService.ServerInstance.DaemonStatus(), and TGServerService.ServerInstance.SendCommand().
Referenced by TGServerService.ServerInstance.ChatProvider_OnChatMessage().
         {
             if (DaemonStatus() != DreamDaemonStatus.Online)
                 return;
             var json = SendCommand(SCListCustomCommands);
             if (String.IsNullOrWhiteSpace(json))
                 return;
             List<Command> tmp = new List<Command>();
             try
             {
                 foreach(var I in new JavaScriptSerializer().Deserialize<IDictionary<string, IDictionary<string, object>>>(json))
                     tmp.Add(new ServerChatCommand(I.Key, (string)I.Value[CCPHelpText], ((int)I.Value[CCPAdminOnly]) == 1, (int)I.Value[CCPRequiredParameters]));
                 ServerChatCommands = tmp;
             }
             catch { }
         }
bool TGServerService.ServerInstance.LocalIsRemote () private
Check if the current HEAD matches the tracked remote branch HEAD
Returns
if the current HEAD matches the tracked remote branch HEAD, otherwise
Definition at line 1091 of file Repository.cs.
References TGServerService.ServerInstance.Fetch(), and TGServerService.ServerInstance.LoadRepo().
Referenced by TGServerService.ServerInstance.Push(), TGServerService.ServerInstance.SynchronizePush(), and TGServerService.ServerInstance.UpdateImpl().
         {
             lock (RepoLock)
             {
                 if (LoadRepo() != null)
                     return false;
                 if (Fetch() != null)
                     return false;
                 try
                 {
                     return Repo.Head.IsTracking && Repo.Head.TrackedBranch.Tip.Sha == Repo.Head.Tip.Sha;
                 }
                 catch
                 {
                     return false;
                 }
             }
         }
Signature TGServerService.ServerInstance.MakeSig () private
Creates a commit LibGit2Sharp.Signature based off of the configured name and e-mail
Returns
The created LibGit2Sharp.Signature
Definition at line 823 of file Repository.cs.
References TGServerService.IInstanceConfig.CommitterEmail, TGServerService.IInstanceConfig.CommitterName, and TGServerService.ServerInstance.Config.
Referenced by TGServerService.ServerInstance.Commit(), and TGServerService.ServerInstance.MergeBranch().
         {
             return new Signature(new Identity(Config.CommitterName, Config.CommitterEmail), DateTimeOffset.Now);
         }
void TGServerService.ServerInstance.MemTrackTimer_Elapsed (object sender, ElapsedEventArgs e) private
Called every five seconds while DreamDaemon is running to log it's current state to the DiagnosticsDir
Parameters
sender The event sender, an instance of System.Timers.Timer
e The ElapsedEventArgs
Definition at line 453 of file DreamDaemon.cs.
References TGServerService.ServerInstance.WriteCurrentDDLog().
Referenced by TGServerService.ServerInstance.Watchdog().
         {
             ulong megamem;
             float cputime;
             lock (watchdogLock)
             {
                 cputime = pcpu.NextValue();
                 using (var pcm = new PerformanceCounter("Process", "Working Set - Private", Proc.ProcessName, true))
                     megamem = Convert.ToUInt64(pcm.NextValue()) / 1024;
             }
             var PercentCpuTime = (int)Math.Round((Decimal)cputime);
             WriteCurrentDDLog(String.Format("CPU: {1}% Memory: {0}MB", megamem, PercentCpuTime.ToString("D3")));
         }
string TGServerService.ServerInstance.MergeBranch (string committish, string mergeMessage) private
Merges given committish into the current branch
Parameters
committish The sha/branch/tag to merge
mergeMessage The commit message for the merge commit
Returns
on success, error message on failure
Definition at line 556 of file Repository.cs.
References TGServerService.ServerInstance.HandleCheckoutProgress(), TGServerService.ServerInstance.MakeSig(), TGServerService.ServerInstance.RepoErrorUpToDate, TGServerService.ServerInstance.ResetNoLock(), and TGServerService.ServerInstance.SendMessage().
Referenced by TGServerService.ServerInstance.MergePullRequest(), and TGServerService.ServerInstance.UpdateImpl().
         {
             var mo = new MergeOptions()
             {
                 OnCheckoutProgress = HandleCheckoutProgress
             };
             if (mergeMessage != null)
             {
                 mo.CommitOnSuccess = false;
                 mo.FastForwardStrategy = FastForwardStrategy.NoFastForward;
             }
             var sig = MakeSig();
             var Result = Repo.Merge(committish, sig, mo);
             currentProgress = -1;
             switch (Result.Status)
             {
                 case MergeStatus.Conflicts:
                     ResetNoLock(null);
                     SendMessage("REPO: Merge conflicted, aborted.", MessageType.DeveloperInfo);
                     return "Merge conflict occurred.";
                 case MergeStatus.UpToDate:
                     return RepoErrorUpToDate;
             }
             if(mergeMessage != null)
                 Repo.Commit(mergeMessage, sig, sig);
             return null;
         }
IList<PullRequestInfo> TGServerService.ServerInstance.MergedPullRequests (out string error)
Get the currently merged pull requests. Note that switching branches will delete this list and switching back won't restore it
Implements TGServiceInterface.Components.ITGRepository.
Definition at line 979 of file Repository.cs.
References TGServerService.ServerInstance.GetCurrentPRList(), and TGServerService.ServerInstance.LoadRepo().
         {
             lock (RepoLock)
             {
                 var result = LoadRepo();
                 if (result != null)
                 {
                     error = result;
                     return null;
                 }
                 try
                 {
                     var PRRawData = GetCurrentPRList();
                     IList<PullRequestInfo> output = new List<PullRequestInfo>();
                     foreach (var I in GetCurrentPRList())
                         output.Add(new PullRequestInfo(Convert.ToInt32(I.Key), I.Value["author"], I.Value["title"], I.Value["commit"]));
                     error = null;
                     return output;
                 }
                 catch (Exception e)
                 {
                     error = e.ToString();
                     return null;
                 }
             }
         }
string TGServerService.ServerInstance.MergePullRequest (int PRNumber)
Merges the target pull request into the current branch if the remote is a github repository
Implements TGServiceInterface.Components.ITGRepository.
Definition at line 869 of file Repository.cs.
References TGServerService.ServerInstance.Config, TGServerService.ServerInstance.GenerateFetchOptions(), TGServerService.ServerInstance.GetCurrentPRList(), TGServerService.ServerInstance.LoadRepo(), TGServerService.ServerInstance.MergeBranch(), TGServerService.ServerInstance.PushTestmergeCommit(), TGServerService.ServerInstance.ResetNoLock(), TGServerService.ServerInstance.SendMessage(), TGServerService.ServerInstance.SetCurrentPRList(), TGServerService.ServerInstance.UpdateSubmodules(), TGServerService.ServerInstance.WriteError(), TGServerService.ServerInstance.WriteInfo(), and TGServerService.ServerInstance.WriteWarning().
         {
             lock (RepoLock)
             {
                 var result = LoadRepo();
                 if (result != null)
                     return result;
                 SendMessage(String.Format("REPO: Merging PR #{0}...", PRNumber), MessageType.DeveloperInfo);
                 result = ResetNoLock(null);
                 if (result != null)
                     return result;
                 try
                 {
                     //only supported with github
                     var remoteUrl = Repo.Network.Remotes["origin"].Url;
                     if (!remoteUrl.Contains("github.com"))
                         return "Only supported with Github based repositories.";
                     var Refspec = new List<string>();
                     var PRBranchName = String.Format("pr-{0}", PRNumber);
                     var LocalBranchName = String.Format("pull/{0}/headrefs/heads/{1}", PRNumber, PRBranchName);
                     Refspec.Add(String.Format("pull/{0}/head:{1}", PRNumber, PRBranchName));
                     var logMessage = "";
                     var branch = Repo.Branches[LocalBranchName];
                     if (branch != null)
                         //Need to delete the branch first in case of rebase
                         Repo.Branches.Remove(branch);
                     Commands.Fetch(Repo, "origin", Refspec, GenerateFetchOptions(), logMessage);  //shitty api has no failure state for this
                     currentProgress = -1;
                     var Config = Properties.Settings.Default;
                     branch = Repo.Branches[LocalBranchName];
                     if (branch == null)
                     {
                         SendMessage("REPO: PR could not be fetched. Does it exist?", MessageType.DeveloperInfo);
                         return String.Format("PR #{0} could not be fetched. Does it exist?", PRNumber);
                     }
                     //so we'll know if this fails
                     var Result = MergeBranch(LocalBranchName, String.Format("Testmerge commit for pull request #{0}", PRNumber));
                     if (Result == null)
                         try
{
                             UpdateSubmodules();
                         }
                         catch (Exception e)
{
                             Result = e.ToString();
                         }
                     if (Result == null)
                     {
                         WriteInfo(String.Format("Merged pull request #{0}", PRNumber), EventID.RepoPRMerge);
                         try
{
                             var CurrentPRs = GetCurrentPRList();
                             var PRNumberString = PRNumber.ToString();
                             CurrentPRs.Remove(PRNumberString);
                             var newPR = new Dictionary<string, string>();
                             //do some excellent remote fuckery here to get the api page
                             var prAPI = remoteUrl;
                             prAPI = prAPI.Replace("/.git", "");
                             prAPI = prAPI.Replace(".git", "");
                             prAPI = prAPI.Replace("github.com", "api.github.com/repos");
                             prAPI += "/pulls/" + PRNumberString + ".json";
                             string json;
                             using (var wc = new WebClient())
{
                                 wc.Headers.Add("user-agent", "TGStationServerService");
                                 json = wc.DownloadString(prAPI);
                             }
                             var Deserializer = new JavaScriptSerializer();
                             var dick = Deserializer.DeserializeObject(json) as IDictionary<string, object>;
                             var user = dick["user"] as IDictionary<string, object>;
                             newPR.Add("commit", branch.Tip.Sha);
                             newPR.Add("author", (string)user["login"]);
                             newPR.Add("title", (string)dick["title"]);
                             CurrentPRs.Add(PRNumberString, newPR);
                             SetCurrentPRList(CurrentPRs);
                         }
                         catch (Exception e)
{
                             WriteError("Failed to update PR list", EventID.RepoPRListError);
                             return "PR Merged, JSON update failed: " + e.ToString();
                         }
                         PushTestmergeCommit();
                     }
                     return Result;
                 }
                 catch (Exception E)
                 {
                     SendMessage("REPO: PR merge failed!", MessageType.DeveloperInfo);
                     WriteWarning(String.Format("Failed to merge pull request #{0}: {1}", PRNumber, E.ToString()), EventID.RepoPRMergeFail);
                     return E.ToString();
                 }
             }
         }
void TGServerService.ServerInstance.Offline ()
Sets InstanceConfig.Enabled of Config to
Definition at line 133 of file ServerInstance.cs.
References TGServerService.ServerInstance.disposedValue.
         {
             Config.Enabled = false;
         }
bool TGServerService.ServerInstance.OperationInProgress ()
If the repo is currently undergoing an operation
Implements TGServiceInterface.Components.ITGRepository.
Definition at line 140 of file Repository.cs.
References TGServerService.ServerInstance.RepoBusy.
         {
             lock (RepoLock)
             {
                 return RepoBusy;
             }
         }
int TGServerService.ServerInstance.PlayerCount ()
Returns the number of connected players. Requires game to use API version >= 3.1.0.1
Returns
The number of connected players or -1 on error
Implements TGServiceInterface.Components.ITGDreamDaemon.
Definition at line 161 of file Interop.cs.
References TGServerService.ServerInstance.SendCommand().
         {
             try
             {
                 return Convert.ToInt32(SendCommand(SCPlayerCount));
             }
             catch
             {
                 return -1;
             }
         }
ushort TGServerService.ServerInstance.Port ()
Get the configured port. Not necessarily the running port if it has since changed
Implements TGServiceInterface.Components.ITGDreamDaemon.
Definition at line 707 of file DreamDaemon.cs.
References TGServerService.ServerInstance.Config, and TGServerService.IInstanceConfig.Port.
         {
             return Config.Port;
         }
bool TGServerService.ServerInstance.PostcompileHook ()
Run the "postcompile" event
Returns
if the event handler exists and failed to run, otherwise
Definition at line 97 of file PreactionHandler.cs.
References TGServerService.ServerInstance.HandleEvent().
Referenced by TGServerService.ServerInstance.CompileImpl().
         {
             return HandleEvent("postcompile");
         }
bool TGServerService.ServerInstance.PrecompileHook ()
Run the "precompile" event
Returns
if the event handler exists and failed to run, otherwise
Definition at line 88 of file PreactionHandler.cs.
References TGServerService.ServerInstance.HandleEvent().
Referenced by TGServerService.ServerInstance.CompileImpl().
         {
             return HandleEvent("precompile");
         }
string TGServerService.ServerInstance.ProjectName ()
Returns the relative path of the dme the compiler will look for without the .dme part
Implements TGServiceInterface.Components.ITGCompiler.
Definition at line 579 of file Compiler.cs.
References TGServerService.ServerInstance.Config, and TGServerService.IInstanceConfig.ProjectName.
Referenced by TGServerService.ServerInstance.CompileImpl().
         {
             lock (CompilerLock)
             {
                 return Config.ProjectName;
             }
         }
IList<ChatSetupInfo> TGServerService.ServerInstance.ProviderInfos ()
Returns ChatSetupInfo for all ChatProviders
Implements TGServiceInterface.Components.ITGChat.
Definition at line 122 of file Chat.cs.
         {
             var infosList = new List<ChatSetupInfo>();
             foreach (var chatProvider in ChatProviders)
                 infosList.Add(chatProvider.ProviderInfo());
             return infosList;
         }
string TGServerService.ServerInstance.Push () private
Definition at line 1148 of file Repository.cs.
References TGServerService.ServerInstance.GenerateGitCredentials(), TGServerService.ServerInstance.LoadRepo(), TGServerService.ServerInstance.LocalIsRemote(), TGServerService.ServerInstance.SSHAuth(), TGServerService.ServerInstance.WriteInfo(), and TGServerService.ServerInstance.WriteWarning().
Referenced by TGServerService.ServerInstance.SynchronizePush().
         {
             if (LocalIsRemote())    //nothing to push
                 return null;
             lock (RepoLock)
             {
                 var result = LoadRepo();
                 if (result != null)
                     return result;
                 try
                 {
                     if (!SSHAuth())
                         return String.Format("Either {0} or {1} is missing from the server directory. Unable to push!", PrivateKeyPath, PublicKeyPath);
                     var options = new PushOptions()
                     {
                         CredentialsProvider = GenerateGitCredentials,
                     };
                     Repo.Network.Push(Repo.Network.Remotes[SSHPushRemote], Repo.Head.CanonicalName, options);
                     WriteInfo("Repo pushed up to commit: " + Repo.Head.Tip.Sha, EventID.RepoPush);
                     return null;
                 }
                 catch (Exception e)
                 {
                     WriteWarning("Repo push failed: " + e.ToString(), EventID.RepoPushFail);
                     return e.ToString();
                 }
             }
         }
void TGServerService.ServerInstance.PushTestmergeCommit () private
Definition at line 584 of file Repository.cs.
References TGServerService.ServerInstance.Config, TGServerService.ServerInstance.GenerateGitCredentials(), TGServerService.IInstanceConfig.PushTestmergeCommits, TGServerService.ServerInstance.SSHAuth(), TGServerService.ServerInstance.SSHPushRemote, TGServerService.ServerInstance.WriteInfo(), and TGServerService.ServerInstance.WriteWarning().
Referenced by TGServerService.ServerInstance.MergePullRequest(), and TGServerService.ServerInstance.UpdateImpl().
         {
             if (Config.PushTestmergeCommits && SSHAuth())
             {
                 string NewB = null;
                 var targetRemote = Repo.Network.Remotes[SSHPushRemote];
                 var options = new PushOptions()
                 {
                     CredentialsProvider = GenerateGitCredentials
                 };
                 try
                 {
                     //now try and push the commit to the remote so they can be referenced
                     NewB = Repo.CreateBranch(RemoteTempBranchName).CanonicalName;
                     Repo.Network.Push(targetRemote, NewB, options); //push the branch
                     Repo.Branches.Remove(NewB);
                     var removalString = String.Format(":{0}", NewB);
                     NewB = null;
                     //we need to delay the second operation a LOT otherwise we get ssh errors
                     Thread.Sleep(10000);
                     Repo.Network.Push(targetRemote, removalString, options);   //delete the branch
                     WriteInfo("Pushed reference commit: " + Repo.Head.Tip.Sha, EventID.ReferencePush);
                 }
                 catch (Exception e)
                 {
                     WriteWarning(String.Format("Failed to push reference commit: {0}. Error: {1}", Repo.Head.Tip.Sha, e.ToString()), EventID.ReferencePush);
                 }
                 finally
                 {
                     if (NewB != null)
                     {
                         //Try to delete the branches regardless
                         try
{
                             Repo.Branches.Remove(NewB);
                         }
                         catch { }
                         try
{
                             Repo.Network.Push(targetRemote, String.Format(":{0}", NewB), options);
                         }
                         catch { }
                     }
                 }
             }
         }
bool TGServerService.ServerInstance.PushTestmergeCommits ()
Check if we push a temporary branch to the remote when we make testmerge commits
Implements TGServiceInterface.Components.ITGRepository.
Definition at line 1388 of file Repository.cs.
References TGServerService.ServerInstance.Config, and TGServerService.IInstanceConfig.PushTestmergeCommits.
         {
             return Config.PushTestmergeCommits;
         }
string TGServerService.ServerInstance.ReadText (string staticRelativePath, bool repo, out string error, out bool unauthorized)
Read from a static file
Implements TGServiceInterface.Components.ITGConfig.
Definition at line 19 of file Config.cs.
References TGServerService.Service.CancelImpersonation(), TGServerService.ServerInstance.Config, TGServerService.ServerInstance.GetCachedRepoConfig(), TGServerService.ServerInstance.RelativePath(), TGServerService.ServerInstance.RepoPath, TGServerService.ServerInstance.StaticDirs, TGServerService.ServerInstance.WriteInfo(), and TGServerService.ServerInstance.WriteWarning().
         {
             string path = null;
             try
             {
                 var configDir = RelativePath(repo ? RepoPath : StaticDirs);
                 path = configDir + '/' + staticRelativePath;   //do not use path.combine or it will try and take the root
                 lock (configLock)
                 {
                     var di1 = new DirectoryInfo(configDir);
                     if (repo)
                     {
                         //ensure we aren't trying to read anything outside the static dirs
                         var Config = GetCachedRepoConfig();
                         if (Config == null)
{
                             error = "Unable to load static directory configuration";
                             unauthorized = false;
                             return null;
                         }
                         var Found = false;
                         foreach (var I in Config.StaticDirectoryPaths)
{
                             if (di1.FullName == new DirectoryInfo(Path.Combine(RelativePath(RepoPath), I)).FullName)
{
                                 Found = true;
                                 break;
                             }
                         }
                         if (!Found)
{
                             error = "File is not in a configured static directory!";
                             unauthorized = false;
                             return null;
                         }
                     }
                     var di2 = new DirectoryInfo(new FileInfo(path).Directory.FullName);
                     var good = false;
                     while (di2 != null)
                     {
                         if (di2.FullName == di1.FullName)
{
                             good = true;
                             break;
                         }
                         else di2 = di2.Parent;
                     }
                     if (!good)
                     {
                         error = "Cannot read above static directories!";
                         unauthorized = false;
                         return null;
                     }
                     var output = File.ReadAllText(path);
                     Service.CancelImpersonation();
                     WriteInfo("Read of " + path, EventID.StaticRead);
                     error = null;
                     unauthorized = false;
                     return output;
                 }
             }
             catch (UnauthorizedAccessException e)
             {
                 //no need for the full stacktrace
                 error = e.Message;
                 unauthorized = true;
                 return null;
             }
             catch (Exception e)
             {
                 error = e.ToString();
                 Service.CancelImpersonation();
                 WriteWarning(String.Format("Read of {0} failed! Error: {1}", path, e.ToString()), EventID.StaticRead);
                 unauthorized = false;
                 return null;
             }
         }
void TGServerService.ServerInstance.Reattach (bool silent)
Definition at line 117 of file ServerInstance.cs.
References TGServerService.ServerInstance.SendMessage().
Referenced by TGServerService.ServerInstance.InitDreamDaemon().
         {
             Config.ReattachRequired = true;
             if(!silent)
                 SendMessage("SERVICE: Update started...", MessageType.DeveloperInfo);
         }
string TGServerService.ServerInstance.Reconnect (ChatProvider providerType)
Reconnect a specific providerType to it's chat service
Implements TGServiceInterface.Components.ITGChat.
Definition at line 219 of file Chat.cs.
Referenced by TGServerService.ServerInstance.ChatConnectivityCheck().
         {
             foreach (var I in ChatProviders)
                 if (I.ProviderInfo().Provider == providerType)
                     return I.Reconnect();
             return "Could not find specified provider!";
         }
string TGServerService.ServerInstance.RecreateStaticFolder ()
Renames the current static folder to a backup name and recreates is from the current repo using TGS3.json
Returns
on success, error message on failure
Implements TGServiceInterface.Components.ITGAdministration.
Definition at line 151 of file Administration.cs.
References TGServerService.ServerInstance.BackupAndDeleteStaticDirectory(), TGServerService.ServerInstance.configLock, TGServerService.ServerInstance.currentStatus, TGServerService.ServerInstance.InitialConfigureRepository(), TGServerService.ServerInstance.RepoLock, and TGServerService.ServerInstance.watchdogLock.
         {
             if (!Monitor.TryEnter(RepoLock))
                 return "Repo locked!";
             try
             {
                 if (!Monitor.TryEnter(watchdogLock))
                     return "Watchdog locked!";
                 try
                 {
                     if (!Monitor.TryEnter(configLock))
                         return "Static dir locked!";
                     try
                     {
                         if (currentStatus != DreamDaemonStatus.Offline)
                             return "Watchdog running!";
                         BackupAndDeleteStaticDirectory();
                         InitialConfigureRepository();
                     }
                     finally
                     {
                         Monitor.Exit(configLock);
                     }
                 }
                 finally
                 {
                     Monitor.Exit(watchdogLock);
                 }
             }
             catch(Exception e)
             {
                 return e.ToString();
             }
             finally
             {
                 Monitor.Exit(RepoLock);
             }
             return null;
         }
string TGServerService.ServerInstance.RelativePath (string path) private
Converts relative paths to full ServerInstance directory paths
Returns
Definition at line 102 of file ServerInstance.cs.
Referenced by TGServerService.ServerInstance.ApplyStagedUpdate(), TGServerService.ServerInstance.BackupAndDeleteStaticDirectory(), TGServerService.ServerInstance.CanStart(), TGServerService.ServerInstance.CleanByondStaging(), TGServerService.ServerInstance.CleanGameFolder(), TGServerService.ServerInstance.Clone(), TGServerService.ServerInstance.CompileImpl(), TGServerService.ServerInstance.DeleteFile(), TGServerService.ServerInstance.DeletePRList(), TGServerService.ServerInstance.DisposeDreamDaemon(), TGServerService.ServerInstance.Exists(), TGServerService.ServerInstance.GenerateChangelogImpl(), TGServerService.ServerInstance.GenerateGitCredentials(), TGServerService.ServerInstance.GetCachedRepoConfig(), TGServerService.ServerInstance.GetCurrentPRList(), TGServerService.ServerInstance.GetEventPath(), TGServerService.ServerInstance.GetStagingDir(), TGServerService.ServerInstance.GetVersion(), TGServerService.ServerInstance.InitCompiler(), TGServerService.ServerInstance.InitDreamDaemon(), TGServerService.ServerInstance.InitEventHandlers(), TGServerService.ServerInstance.InitialConfigureRepository(), TGServerService.ServerInstance.InitializeImpl(), TGServerService.ServerInstance.InitRepo(), TGServerService.ServerInstance.IsInitialized(), TGServerService.ServerInstance.ListStaticDirectory(), TGServerService.ServerInstance.LoadRepo(), TGServerService.ServerInstance.ReadText(), TGServerService.ServerInstance.RepoConfigsMatch(), TGServerService.ServerInstance.SetCurrentPRList(), TGServerService.ServerInstance.SSHAuth(), TGServerService.ServerInstance.StartImpl(), TGServerService.ServerInstance.UpdateBridgeDll(), TGServerService.ServerInstance.UpdateTGS3Json(), TGServerService.ServerInstance.UpdateToVersionImpl(), TGServerService.ServerInstance.WriteCurrentDDLog(), and TGServerService.ServerInstance.WriteText().
         {
             return Path.Combine(Config.Directory, path);
         }
bool TGServerService.ServerInstance.RepoConfigsMatch () private
Checks if the CachedTGS3SettingsPath and RepoTGS3SettingsPath json files match.
Returns
if the jsons match, otherwise
Definition at line 115 of file Repository.cs.
References TGServerService.ServerInstance.GetCachedRepoConfig(), TGServerService.ServerInstance.LoadRepo(), and TGServerService.ServerInstance.RelativePath().
Referenced by TGServerService.ServerInstance.CompileImpl(), and TGServerService.ServerInstance.InitializeImpl().
         {
             //this should never be called while the repo is busy
             RepoConfig I = null;
             lock (RepoLock)
             {
                 if (!RepoBusy && LoadRepo() == null)
                     I = new RepoConfig(RelativePath(RepoTGS3SettingsPath));
             }
             if (I == null)
                 throw new Exception("Unable to load TGS3.json from repo!");
             var J = GetCachedRepoConfig();
             return I == J;
         }
void TGServerService.ServerInstance.RequestRestart ()
Restart the server after the currently running world reboots. Has no effect if the server isn't running
Implements TGServiceInterface.Components.ITGDreamDaemon.
Definition at line 202 of file DreamDaemon.cs.
References TGServerService.ServerInstance.SCHardReboot, and TGServerService.ServerInstance.SendCommand().
Referenced by TGServerService.ServerInstance.SetPort(), TGServerService.ServerInstance.SetSecurityLevel(), TGServerService.ServerInstance.SetWebclient(), and TGServerService.ServerInstance.UpdateToVersionImpl().
         {
             SendCommand(SCHardReboot);
         }
void TGServerService.ServerInstance.RequestStop ()
Stop the server after the currently running world reboots. Has no effect if the server isn't running
Implements TGServiceInterface.Components.ITGDreamDaemon.
Definition at line 208 of file DreamDaemon.cs.
References TGServerService.ServerInstance.SCGracefulShutdown, and TGServerService.ServerInstance.SendCommand().
         {
             lock (watchdogLock)
             {
                 if (currentStatus != DreamDaemonStatus.Online || AwaitingShutdown != ShutdownRequestPhase.None)
                     return;
                 AwaitingShutdown = ShutdownRequestPhase.Pinged;
             }
             SendCommand(SCGracefulShutdown);
         }
string TGServerService.ServerInstance.Reset (bool trackedBranch)
Runs git reset –hard
Implements TGServiceInterface.Components.ITGRepository.
Definition at line 801 of file Repository.cs.
References TGServerService.ServerInstance.DeletePRList(), TGServerService.ServerInstance.LoadRepo(), TGServerService.ServerInstance.ResetNoLock(), TGServerService.ServerInstance.SendMessage(), TGServerService.ServerInstance.WriteInfo(), and TGServerService.ServerInstance.WriteWarning().
         {
             lock (RepoLock)
             {
                 var res = LoadRepo() ?? ResetNoLock(trackedBranch ? (Repo.Head.TrackedBranch ?? Repo.Head) : Repo.Head);
                 if (res == null)
                 {
                     SendMessage(String.Format("REPO: Hard reset to {0}branch", trackedBranch ? "tracked " : ""), MessageType.DeveloperInfo);
                     if (trackedBranch)
                         DeletePRList();
                     WriteInfo(String.Format("Repo branch reset{0}", trackedBranch ? " to tracked branch" : ""), trackedBranch ? EventID.RepoResetTracked : EventID.RepoReset);
                     return null;
                 }
                 WriteWarning(String.Format("Failed to reset{0}: {1}", trackedBranch ? " to tracked branch" : "", res), trackedBranch ? EventID.RepoResetTrackedFail : EventID.RepoResetFail);
                 return res;
             }
         }
string TGServerService.ServerInstance.ResetNoLock (Branch targetBranch) private
Equivalent of running git reset --hard on the repository. Requires RepoLock
Parameters
targetBranch If not , reset to this branch instead of HEAD
Returns
on success, error message on failure
Definition at line 481 of file Repository.cs.
Referenced by TGServerService.ServerInstance.Checkout(), TGServerService.ServerInstance.MergeBranch(), TGServerService.ServerInstance.MergePullRequest(), TGServerService.ServerInstance.Reset(), and TGServerService.ServerInstance.UpdateImpl().
         {
             try
             {
                 if (targetBranch != null)
                     Repo.Reset(ResetMode.Hard, targetBranch.Tip);
                 else
                     Repo.Reset(ResetMode.Hard);
                 return null;
             }
             catch (Exception e)
             {
                 return e.ToString();
             }
         }
string TGServerService.ServerInstance.Restart ()
Immediately kills and restarts the server
Implements TGServiceInterface.Components.ITGDreamDaemon.
Definition at line 266 of file DreamDaemon.cs.
References TGServerService.ServerInstance.DaemonStatus(), TGServerService.ServerInstance.SendMessage(), TGServerService.ServerInstance.Start(), and TGServerService.ServerInstance.Stop().
Referenced by TGServerService.ServerInstance.KillMe().
         {
             if (DaemonStatus() == DreamDaemonStatus.Offline)
                 return Start();
             lock (restartLock)
             {
                 if (RestartInProgress)
                     return "Restart already in progress";
                 RestartInProgress = true;
             }
             SendMessage("DD: Hard restart triggered", MessageType.WatchdogInfo);
             Stop();
             var res = Start();
             if (res != null)
                 lock (restartLock)
                 {
                     RestartInProgress = false;
                 }
             return res;
         }
void TGServerService.ServerInstance.RunDisposals () private
Cleans up the ServerInstance
Definition at line 47 of file ServerInstance.cs.
References TGServerService.ServerInstance.DisposeAdministration(), TGServerService.ServerInstance.DisposeByond(), TGServerService.ServerInstance.DisposeChat(), TGServerService.ServerInstance.DisposeCompiler(), TGServerService.ServerInstance.DisposeDreamDaemon(), and TGServerService.ServerInstance.DisposeRepo().
Referenced by TGServerService.ServerInstance.Dispose().
         {
             DisposeDreamDaemon();
             DisposeCompiler();
             DisposeByond();
             DisposeRepo();
             DisposeChat();
             DisposeAdministration();
             Config.Save();
         }
DreamDaemonSecurity TGServerService.ServerInstance.SecurityLevel ()
Get the configured (not necessarily running) security level
Implements TGServiceInterface.Components.ITGDreamDaemon.
Definition at line 637 of file DreamDaemon.cs.
References TGServerService.ServerInstance.Config, and TGServerService.IInstanceConfig.Security.
         {
             lock (watchdogLock)
             {
                 return Config.Security;
             }
         }
string TGServerService.ServerInstance.SecurityWord (bool starting = false) private
Translate the configured DreamDaemonSecurity level into a byond command line param
Parameters
starting If bases it's result on StartingSecurity, uses InstanceConfig.Security of Config otherwise
Returns
"safe", "trusted", or "ultrasafe" depending on the DreamDaemonSecurity it checks
Definition at line 505 of file DreamDaemon.cs.
References TGServerService.ServerInstance.Config, and TGServerService.IInstanceConfig.Security.
Referenced by TGServerService.ServerInstance.StartImpl(), and TGServerService.ServerInstance.StatusString().
         {
             var level = starting ? StartingSecurity : Config.Security;
             switch (level)
             {
                 case DreamDaemonSecurity.Safe:
                     return "safe";
                 case DreamDaemonSecurity.Trusted:
                     return "trusted";
                 case DreamDaemonSecurity.Ultrasafe:
                     return "ultrasafe";
                 default:
                     throw new Exception(String.Format("Bad DreamDaemon security level: {0}", level));
             }
         }
string TGServerService.ServerInstance.SendCommand (string cmd)
Definition at line 151 of file Interop.cs.
References TGServerService.ServerInstance.currentPort, TGServerService.ServerInstance.currentStatus, TGServerService.ServerInstance.SendTopic(), and TGServerService.ServerInstance.watchdogLock.
Referenced by TGServerService.ServerInstance.HandleCommand(), TGServerService.ServerInstance.LoadServerChatCommands(), TGServerService.ServerInstance.PlayerCount(), TGServerService.ServerInstance.RequestRestart(), TGServerService.ServerInstance.RequestStop(), TGServerService.ServerInstance.Watchdog(), and TGServerService.ServerInstance.WorldAnnounce().
         {
             lock (watchdogLock)
             {
                 if (currentStatus != DreamDaemonStatus.Online)
                     return "Error: Server Offline!";
                 return SendTopic(String.Format("serviceCommsKey={0};command={1}", serviceCommsKey, cmd), currentPort);
             }
         }
void TGServerService.ServerInstance.SendMessage (string msg, MessageType mt)
Broadcast a message to appropriate channels based on the message type
Parameters
msg The message to send
mt The message type
Definition at line 232 of file Chat.cs.
References TGServerService.ServerInstance.WriteWarning().
Referenced by TGServerService.ServerInstance.ApplyStagedUpdate(), TGServerService.ServerInstance.Checkout(), TGServerService.ServerInstance.Clone(), TGServerService.ServerInstance.CompileImpl(), TGServerService.ServerInstance.DisposeDreamDaemon(), TGServerService.ServerInstance.HandleCommand(), TGServerService.ServerInstance.InitDreamDaemon(), TGServerService.ServerInstance.InitializeImpl(), TGServerService.ServerInstance.MergeBranch(), TGServerService.ServerInstance.MergePullRequest(), TGServerService.ServerInstance.Reattach(), TGServerService.ServerInstance.Reset(), TGServerService.ServerInstance.Restart(), TGServerService.ServerInstance.UpdateImpl(), TGServerService.ServerInstance.UpdateSubmodules(), TGServerService.ServerInstance.UpdateToVersionImpl(), and TGServerService.ServerInstance.Watchdog().
         {
             lock (ChatLock)
             {
                 foreach (var ChatProvider in ChatProviders)
                     try
                     {
                         ChatProvider.SendMessage(msg, mt);
                     }
                     catch (Exception e)
                     {
                         WriteWarning(String.Format("Chat broadcast failed (Provider: {3}) (Flags: {0}) (Message: {1}): {2}", mt, msg, e.ToString(), ChatProvider.ProviderInfo().Provider), EventID.ChatBroadcastFail);
                     }
             }
         }
string TGServerService.ServerInstance.SendTopic (string topicdata, ushort port) private
Definition at line 182 of file Interop.cs.
References TGServerService.ServerInstance.CheckAPIVersionConstraints().
Referenced by TGServerService.ServerInstance.SendCommand().
         {
             //santize the escape characters in accordance with http://www.byond.com/docs/ref/info.html#/proc/params2list
             lock (topicLock) {
                 if (!CheckAPIVersionConstraints())
                     return "Incompatible API!";
                 StringBuilder stringPacket = new StringBuilder();
                 stringPacket.Append((char)'\x00', 8);
                 stringPacket.Append('?' + topicdata);
                 stringPacket.Append((char)'\x00');
                 string fullString = stringPacket.ToString();
                 var packet = Encoding.ASCII.GetBytes(fullString);
                 packet[1] = 0x83;
                 var FinalLength = packet.Length - 4;
                 if (FinalLength > UInt16.MaxValue)
                     return "Error: Topic too long";
                 var lengthBytes = BitConverter.GetBytes((ushort)FinalLength);
                 packet[2] = lengthBytes[1]; //fucking endianess
                 packet[3] = lengthBytes[0];
                 var returnedString = "NULL";
                 var returnedData = new byte[UInt16.MaxValue];
                 using (var topicSender = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp) { SendTimeout = 5000, ReceiveTimeout = 5000 })
                     try
                     {
                         topicSender.Connect(IPAddress.Loopback, port);
                         topicSender.Send(packet);
                         try
{
                             topicSender.Receive(returnedData);
                             var raw_string = Encoding.ASCII.GetString(returnedData).TrimEnd(new char[] { (char)0 }).Trim();
                             if (raw_string.Length > 6)
                                 returnedString = raw_string.Substring(5, raw_string.Length - 5).Trim();
                         }
                         catch
{
                             returnedString = "Topic recieve error!";
                         }
                         finally
{
                             topicSender.Shutdown(SocketShutdown.Both);
                         }
                     }
                     catch
                     {
                         return "Topic delivery failed!";
                     }
                 return returnedString;
             }
         }
string TGServerService.ServerInstance.ServerDirectory ()
Return the directory of the server on the host machine
Implements TGServiceInterface.Components.ITGInstance.
Definition at line 125 of file ServerInstance.cs.
         {
             return Config.Directory;
         }
string TGServerService.ServerInstance.SetAuthorizedGroup (string groupName)
Searches the windows machine for the group named groupName , sets it as the authorized group if it's found
Implements TGServiceInterface.Components.ITGAdministration.
Definition at line 56 of file Administration.cs.
References TGServerService.IInstanceConfig.AuthorizedUserGroupSID, TGServerService.ServerInstance.Config, TGServerService.ServerInstance.FindTheDroidsWereLookingFor(), and TGServerService.IInstanceConfig.Save().
         {
             if (groupName == null)
             {
                 TheDroidsWereLookingFor = null;
                 Config.AuthorizedUserGroupSID = null;
                 Config.Save();
                 return "ADMIN";
             }
             return FindTheDroidsWereLookingFor(groupName);
         }
void TGServerService.ServerInstance.SetAutostart (bool on)
Set the autostart config
Implements TGServiceInterface.Components.ITGDreamDaemon.
Definition at line 666 of file DreamDaemon.cs.
References TGServerService.IInstanceConfig.Autostart, and TGServerService.ServerInstance.Config.
         {
             Config.Autostart = on;
         }
void TGServerService.ServerInstance.SetAutoUpdateInterval (ulong newInterval)
(De)Activate and set the interval for the automatic server updater
Implements TGServiceInterface.Components.ITGRepository.
Definition at line 1331 of file Repository.cs.
References TGServerService.IInstanceConfig.AutoUpdateInterval, TGServerService.ServerInstance.autoUpdateTimer, and TGServerService.ServerInstance.Config.
Referenced by TGServerService.ServerInstance.InitRepo().
         {
             lock (autoUpdateTimer)
             {
                 autoUpdateTimer.Stop();
                 if (newInterval > 0) {
                     autoUpdateTimer.Interval = newInterval * 60 * 1000; //convert from minutes to ms
                     autoUpdateTimer.Start();
                 }
             }
             Config.AutoUpdateInterval = newInterval;
         }
void TGServerService.ServerInstance.SetCommitterEmail (string newEmail)
Sets the email of the configured git committer
Implements TGServiceInterface.Components.ITGRepository.
Definition at line 1034 of file Repository.cs.
References TGServerService.IInstanceConfig.CommitterEmail, and TGServerService.ServerInstance.Config.
         {
             lock (RepoLock)
             {
                 Config.CommitterEmail = newEmail;
             }
         }
void TGServerService.ServerInstance.SetCommitterName (string newName)
Sets the name of the configured git committer
Implements TGServiceInterface.Components.ITGRepository.
Definition at line 1016 of file Repository.cs.
References TGServerService.IInstanceConfig.CommitterName, and TGServerService.ServerInstance.Config.
         {
             lock (RepoLock)
             {
                 Config.CommitterName = newName;
             }
         }
void TGServerService.ServerInstance.SetCurrentPRList (IDictionary< string, IDictionary< string, string >> list) private
Serializes pull request info into PRJobFile
Parameters
list
Definition at line 861 of file Repository.cs.
References TGServerService.ServerInstance.RelativePath().
Referenced by TGServerService.ServerInstance.MergePullRequest().
         {
             var Serializer = new JavaScriptSerializer();
             var rawdata = Serializer.Serialize(list);
             File.WriteAllText(RelativePath(PRJobFile), rawdata);
         }
void TGServerService.ServerInstance.SetPort (ushort new_port)
Set the port to host DD on. Requires reboot to apply. Calls RequestRestart.
Implements TGServiceInterface.Components.ITGDreamDaemon.
Definition at line 239 of file DreamDaemon.cs.
References TGServerService.ServerInstance.Config, TGServerService.IInstanceConfig.Port, and TGServerService.ServerInstance.RequestRestart().
         {
             lock (watchdogLock)
             {
                 Config.Port = new_port;
                 RequestRestart();
             }
         }
void TGServerService.ServerInstance.SetProjectName (string projectName)
Sets the relative path of the dme the compiler will look for without the .dme part
Implements TGServiceInterface.Components.ITGCompiler.
Definition at line 588 of file Compiler.cs.
References TGServerService.ServerInstance.Config, and TGServerService.IInstanceConfig.ProjectName.
         {
             lock (CompilerLock)
             {
                 Config.ProjectName = projectName;
             }
         }
string TGServerService.ServerInstance.SetProviderInfo (ChatSetupInfo info)
Sets a chat provider info
Implements TGServiceInterface.Components.ITGChat.
Definition at line 176 of file Chat.cs.
References TGServiceInterface.ChatSetupInfo.AdminChannels, TGServiceInterface.ChatSetupInfo.AdminList, TGServiceInterface.ChatSetupInfo.DevChannels, TGServiceInterface.ChatSetupInfo.GameChannels, TGServiceInterface.ChatSetupInfo.Provider, and TGServiceInterface.ChatSetupInfo.WatchdogChannels.
         {
             info.AdminList.RemoveAll(x => String.IsNullOrWhiteSpace(x));
             info.AdminChannels.RemoveAll(x => String.IsNullOrWhiteSpace(x));
             info.GameChannels.RemoveAll(x => String.IsNullOrWhiteSpace(x));
             info.DevChannels.RemoveAll(x => String.IsNullOrWhiteSpace(x));
             info.WatchdogChannels.RemoveAll(x => String.IsNullOrWhiteSpace(x));
             try
             {
                 lock (ChatLock)
                 {
                     foreach (var ChatProvider in ChatProviders)
                         if (info.Provider == ChatProvider.ProviderInfo().Provider)
                             return ChatProvider.SetProviderInfo(info);
                     return "Error: Invalid provider: " + info.Provider.ToString();
                 }
             }
             catch (Exception e)
             {
                 return e.ToString();
             }
         }
void TGServerService.ServerInstance.SetPushTestmergeCommits (bool newValue)
Set if we push a temporary branch to the remote when we make testmerge commits
Implements TGServiceInterface.Components.ITGRepository.
Definition at line 1394 of file Repository.cs.
References TGServerService.ServerInstance.Config, and TGServerService.IInstanceConfig.PushTestmergeCommits.
         {
             Config.PushTestmergeCommits = newValue;
         }
bool TGServerService.ServerInstance.SetSecurityLevel (DreamDaemonSecurity level)
Sets the security level of the server. Requires server reboot to apply. Calls RequestRestart. Note that anything higher than Trusted will disable interop from DD
Implements TGServiceInterface.Components.ITGDreamDaemon.
Definition at line 646 of file DreamDaemon.cs.
References TGServerService.ServerInstance.Config, TGServerService.ServerInstance.DaemonStatus(), TGServerService.ServerInstance.RequestRestart(), and TGServerService.IInstanceConfig.Security.
         {
             bool needReboot;
             lock (watchdogLock)
             {
                 needReboot = Config.Security != level;
                 Config.Security = level;
             }
             if (needReboot)
                 RequestRestart();
             return DaemonStatus() != DreamDaemonStatus.Online;
         }
string TGServerService.ServerInstance.Setup (string RepoURL, string BranchName)
Deletes whatever may be left over and clones the repo at remote and checks out branch . Will move config and data dirs to a backup location if they exist. Runs asyncronously
Implements TGServiceInterface.Components.ITGRepository.
Definition at line 385 of file Repository.cs.
References TGServerService.ServerInstance.Clone(), TGServerService.ServerInstance.CompilerIdleNoLock(), TGServerService.ServerInstance.CompilerLock, TGServerService.ServerInstance.DaemonStatus(), and TGServerService.ServerInstance.SSHAuth().
         {
             lock (RepoLock)
             {
                 if (RepoBusy)
                     return "Repo is busy!";
                 lock (CompilerLock)
                 {
                     if (!CompilerIdleNoLock())
                         return "Compiler is running!";
                 }
                 if (DaemonStatus() != DreamDaemonStatus.Offline)
                     return "DreamDaemon is running!";
                 if (RepoURL.Contains("ssh://") && !SSHAuth())
                     return String.Format("SSH url specified but either {0} or {1} does not exist in the server directory!", PrivateKeyPath, PublicKeyPath);
                 RepoBusy = true;
                 Cloning = true;
                 new Thread(new ParameterizedThreadStart(Clone))
                 {
                     IsBackground = true //make sure we don't hold up shutdown
                 }.Start(RepoURL + ' ' + BranchName);
                 return null;
             }
         }
void TGServerService.ServerInstance.SetWebclient (bool on)
Set the webclient config. Calls RequestRestart
Implements TGServiceInterface.Components.ITGDreamDaemon.
Definition at line 737 of file DreamDaemon.cs.
References TGServerService.ServerInstance.Config, TGServerService.ServerInstance.RequestRestart(), and TGServerService.IInstanceConfig.Webclient.
         {
             lock (watchdogLock)
             {
                 var diff = on != Config.Webclient;
                 if (diff)
                 {
                     Config.Webclient = on;
                     RequestRestart();
                 }
             }
         }
bool TGServerService.ServerInstance.ShutdownInProgress ()
Checks if a server stop has been requested
Implements TGServiceInterface.Components.ITGDreamDaemon.
Definition at line 713 of file DreamDaemon.cs.
         {
             lock (watchdogLock)
             {
                 return AwaitingShutdown != ShutdownRequestPhase.None;
             }
         }
bool TGServerService.ServerInstance.SSHAuth () private
Check if the ServerInstance is configured for SSH pushing
Returns
if the see cref="ServerInstance"/> is configured for SSH pushing, otherwise
Definition at line 1182 of file Repository.cs.
References TGServerService.ServerInstance.RelativePath().
Referenced by TGServerService.ServerInstance.Push(), TGServerService.ServerInstance.PushTestmergeCommit(), TGServerService.ServerInstance.Setup(), and TGServerService.ServerInstance.SynchronizePush().
         {
             return File.Exists(RelativePath(PrivateKeyPath)) && File.Exists(RelativePath(PublicKeyPath));
         }
string TGServerService.ServerInstance.Start ()
Starts the server if it isn't running
Implements TGServiceInterface.Components.ITGDreamDaemon.
Definition at line 479 of file DreamDaemon.cs.
References TGServerService.ServerInstance.ApplyStagedUpdate(), TGServerService.ServerInstance.CanStart(), TGServerService.ServerInstance.CurrentStatus(), and TGServerService.ServerInstance.StartImpl().
Referenced by TGServerService.ServerInstance.InitDreamDaemon(), and TGServerService.ServerInstance.Restart().
         {
             if (CurrentStatus() == ByondStatus.Staged)
             {
                 //IMPORTANT: SLEEP FOR A MOMENT OR WONDOWS WON'T RELEASE THE FUCKING BYOND DLL HANDLES!!!! REEEEEEE
                 Thread.Sleep(3000);
                 ApplyStagedUpdate();
             }
             lock (watchdogLock)
             {
                 if (currentStatus != DreamDaemonStatus.Offline)
                     return "Server already running";
                 var res = CanStart();
                 if (res != null)
                     return res;
                 currentPort = 0;
                 currentStatus = DreamDaemonStatus.HardRebooting;
             }
             return StartImpl(false);
         }
string TGServerService.ServerInstance.StartImpl (bool watchdog) private
Clears the current GameAPIVersion, calls UpdateBridgeDll(bool) with a parameter, and attempts to start the DreamDaemon Proc
Parameters
watchdog If , sets DDWatchdog to a new Thread pointing to Watchdog and starts it
Returns
on success, error message on failure
Definition at line 587 of file DreamDaemon.cs.
References TGServerService.ServerInstance.CanStart(), TGServerService.ServerInstance.Config, TGServerService.ServerInstance.GameAPIVersion, TGServerService.ServerInstance.GameDirLive, TGServerService.ServerInstance.GenCommsKey(), TGServerService.IInstanceConfig.Name, TGServerService.IInstanceConfig.Port, TGServerService.IInstanceConfig.ProjectName, TGServerService.ServerInstance.RelativePath(), TGServerService.IInstanceConfig.Security, TGServerService.ServerInstance.SecurityWord(), TGServerService.ServerInstance.serviceCommsKey, TGServerService.ServerInstance.SPInstanceName, TGServerService.ServerInstance.topicLock, TGServerService.ServerInstance.UpdateBridgeDll(), TGServerService.ServerInstance.Version(), TGServerService.ServerInstance.Watchdog(), and TGServerService.IInstanceConfig.Webclient.
Referenced by TGServerService.ServerInstance.Start(), and TGServerService.ServerInstance.Watchdog().
         {
             try
             {
                 lock (watchdogLock)
                 {
                     var res = CanStart();
                     if (res != null)
                         return res;
                     var DMB = RelativePath(GameDirLive + "/" + Config.ProjectName + ".dmb");
                     GenCommsKey();
                     StartingSecurity = Config.Security;
                     Proc.StartInfo.Arguments = String.Format("{0} -port {1} {5}-close -verbose -params \"server_service={3}&server_service_version={4}&{6}={7}\" -{2} -public", DMB, Config.Port, SecurityWord(), serviceCommsKey, Version(), Config.Webclient ? "-webclient " : "", SPInstanceName, Config.Name);
                     UpdateBridgeDll(true);
                     lock (topicLock)
                     {
                         GameAPIVersion = null;  //needs updating
                     }
                     Proc.Start();
                     Proc.PriorityClass = ProcessPriorityClass.AboveNormal;
                     if (!Proc.WaitForInputIdle(DDHangStartTime * 1000))
                     {
                         Proc.Kill();
                         Proc.WaitForExit();
                         Proc.Close();
                         currentStatus = DreamDaemonStatus.Offline;
                         currentPort = 0;
                         return String.Format("Server start is taking more than {0}s! Aborting!", DDHangStartTime);
                     }
                     currentPort = Config.Port;
                     currentStatus = DreamDaemonStatus.Online;
                     if (!watchdog)
                     {
                         DDWatchdog = new Thread(new ThreadStart(Watchdog));
                         DDWatchdog.Start();
                     }
                     return null;
                 }
             }
             catch (Exception e)
             {
                 currentStatus = DreamDaemonStatus.Offline;
                 return e.ToString();
             }
         }
string TGServerService.ServerInstance.StatusString (bool includeMetaInfo)
Returns a human readable string of the current server status
Implements TGServiceInterface.Components.ITGDreamDaemon.
Definition at line 672 of file DreamDaemon.cs.
References TGServerService.ServerInstance.DaemonStatus(), and TGServerService.ServerInstance.SecurityWord().
         {
             const string visSecStr = " (Sec: {0})";
             string res;
             var ds = DaemonStatus();
             switch (ds)
             {
                 case DreamDaemonStatus.Offline:
                     res = "OFFLINE";
                     break;
                 case DreamDaemonStatus.HardRebooting:
                     res = "REBOOTING";
                     break;
                 case DreamDaemonStatus.Online:
                     res = "ONLINE";
                     if (includeMetaInfo)
                     {
                         string secandvis;
                         lock (watchdogLock)
{
                             secandvis = String.Format(visSecStr, SecurityWord(true));
                         }
                         res += secandvis;
                     }
                     break;
                 default:
                     res = "NULL AND ERRORS";
                     break;
             }
             if (includeMetaInfo && ds != DreamDaemonStatus.Online)
                 res += String.Format(visSecStr, SecurityWord());
             return res;
         }
string TGServerService.ServerInstance.Stop ()
Immediately kills the server
Implements TGServiceInterface.Components.ITGDreamDaemon.
Definition at line 220 of file DreamDaemon.cs.
References TGServerService.ServerInstance.DDWatchdog.
Referenced by TGServerService.ServerInstance.DisposeDreamDaemon(), TGServerService.ServerInstance.KillMe(), and TGServerService.ServerInstance.Restart().
         {
             Thread t;
             lock (watchdogLock)
             {
                 t = DDWatchdog;
                 DDWatchdog = null;
             }
             if (t != null && t.IsAlive)
             {
                 t.Abort();
                 t.Join();
                 return null;
             }
             else
                 return "Server not running";
         }
string TGServerService.ServerInstance.SynchronizePush ()
Pushes the paths listed in TGS3.json to the currentl git remote. No other commit differences may exist for this function to succeed
Implements TGServiceInterface.Components.ITGRepository.
Definition at line 1043 of file Repository.cs.
References TGServerService.ServerInstance.Commit(), TGServerService.ServerInstance.Config, TGServerService.ServerInstance.GetCachedRepoConfig(), TGServerService.ServerInstance.LocalIsRemote(), TGServerService.ServerInstance.Push(), and TGServerService.ServerInstance.SSHAuth().
         {
             var Config = GetCachedRepoConfig();
             if (Config == null)
                 return "Error reading changelog configuration";
             if(!Config.ChangelogSupport || !SSHAuth())
                 return null;
             return LocalIsRemote() ? Commit(Config) ?? Push() : "Can't push changelog: HEAD does not match tracked remote branch";
         }
string TGServerService.ServerInstance.Update (bool reset)
Fetches the origin and merges it into the current branch
Implements TGServiceInterface.Components.ITGRepository.
Definition at line 632 of file Repository.cs.
References TGServerService.ServerInstance.UpdateImpl().
         {
             return UpdateImpl(reset, true);
         }
void TGServerService.ServerInstance.UpdateBridgeDll (bool overwrite) private
Copies BridgeDLLName from the program directory to the the ServerInstance directory
Parameters
overwrite If , overwrites the ServerInstance's current interface .dll if it exists
Definition at line 525 of file DreamDaemon.cs.
References TGServerService.ServerInstance.BridgeDLLName, TGServerService.ServerInstance.DreamDaemonBridgeType, TGServerService.ServerInstance.RelativePath(), TGServerService.ServerInstance.WriteError(), and TGServerService.ServerInstance.WriteInfo().
Referenced by TGServerService.ServerInstance.InitialConfigureRepository(), TGServerService.ServerInstance.InitRepo(), and TGServerService.ServerInstance.StartImpl().
         {
             var rbdlln = RelativePath(BridgeDLLName);
             var FileExists = File.Exists(rbdlln);
             if (FileExists && !overwrite)
                 return;
             //Copy the interface dll to the static dir
             var InterfacePath = Assembly.GetAssembly(typeof(IInterface)).Location;
             //bridge is installed next to the interface
             var BridgePath = Path.Combine(Path.GetDirectoryName(InterfacePath), BridgeDLLName);
 #if DEBUG
             //We could be debugging from the project directory
             if (!File.Exists(BridgePath))
                 //A little hackish debug mode doctoring never hurt anyone
                 BridgePath = Path.Combine(Path.GetDirectoryName(Path.GetDirectoryName(Path.GetDirectoryName(Path.GetDirectoryName(InterfacePath)))), "TGDreamDaemonBridge/bin/x86/Debug", BridgeDLLName);
 #endif
             try
             {
                 //Use reflection to ensure these are the droids we're looking for
                 Assembly.ReflectionOnlyLoadFrom(BridgePath).GetType(DreamDaemonBridgeType, true);
             }
             catch (Exception e)
             {
                 WriteError(String.Format("Unable to locate {0}! Error: {1}", BridgeDLLName, e.ToString()), EventID.BridgeDLLUpdateFail);
                 return;
             }
             try
             {
                 if (FileExists)
                 {
                     var Old = File.ReadAllBytes(rbdlln);
                     var New = File.ReadAllBytes(BridgePath);
                     if (Old.SequenceEqual(New))
                         return; //no need
                 }
                 File.Copy(BridgePath, rbdlln, overwrite);
             }
             catch
             {
                 try
                 {
                     //ok the things being stupid and hasn't released the dll yet, try ONCE more
                     Thread.Sleep(1000);
                     File.Copy(BridgePath, rbdlln, overwrite);
                 }
                 catch (Exception e)
                 {
                     //intentionally using the fi
                     WriteError("Failed to update bridge DLL! Error: " + e.ToString(), EventID.BridgeDLLUpdateFail);
                     return;
                 }
             }
             WriteInfo("Updated interface DLL", EventID.BridgeDLLUpdated);
         }
string TGServerService.ServerInstance.UpdateImpl (bool reset, bool successOnUpToDate) private
Fetches the origin and merges it into the current branch
Parameters
reset If , the operation will perform a hard reset instead of a merge
successOnUpToDate If , a return value of RepoErrorUpToDate will be changed to
Returns
on success, error message on failure
Definition at line 643 of file Repository.cs.
References TGServerService.ServerInstance.DeletePRList(), TGServerService.ServerInstance.Fetch(), TGServerService.ServerInstance.LoadRepo(), TGServerService.ServerInstance.LocalIsRemote(), TGServerService.ServerInstance.MergeBranch(), TGServerService.ServerInstance.PushTestmergeCommit(), TGServerService.ServerInstance.RepoErrorUpToDate, TGServerService.ServerInstance.ResetNoLock(), TGServerService.ServerInstance.SendMessage(), TGServerService.ServerInstance.UpdateSubmodules(), TGServerService.ServerInstance.WriteInfo(), and TGServerService.ServerInstance.WriteWarning().
Referenced by TGServerService.ServerInstance.AutoUpdateTimer_Elapsed(), and TGServerService.ServerInstance.Update().
         {
             lock (RepoLock)
             {
                 var result = LoadRepo();
                 if (result != null)
                     return result;
                 try
                 {
                     if (Repo.Head == null || !Repo.Head.IsTracking)
                         return "Cannot update while not on a tracked branch";
                     var res = Fetch();
                     if (res != null)
                         return res;
                     var originBranch = Repo.Head.TrackedBranch;
                     if (!successOnUpToDate && Repo.Head.Tip.Sha == originBranch.Tip.Sha)
                         return RepoErrorUpToDate;
                     SendMessage(String.Format("REPO: Updating origin branch...({0})", reset ? "Hard Reset" : "Merge"), MessageType.DeveloperInfo);
                     if (reset)
                     {
                         var error = ResetNoLock(Repo.Head.TrackedBranch);
                         UpdateSubmodules();
                         if (error != null)
                             throw new Exception(error);
                         DeletePRList();
                         WriteInfo("Repo hard updated to " + originBranch.Tip.Sha, EventID.RepoHardUpdate);
                         return error;
                     }
                     res = MergeBranch(originBranch.FriendlyName, "Merge origin into current testmerge");
                     if (!LocalIsRemote())   //might be fast forward
                         PushTestmergeCommit();
                     if (res != null)
                         throw new Exception(res);
                     UpdateSubmodules();
                     WriteInfo("Repo merge updated to " + originBranch.Tip.Sha, EventID.RepoMergeUpdate);
                     return null;
                 }
                 catch (Exception E)
                 {
                     SendMessage("REPO: Update failed!", MessageType.DeveloperInfo);
                     WriteWarning(String.Format("Repo{0} update failed", reset ? " hard" : ""), reset ? EventID.RepoHardUpdateFail : EventID.RepoMergeUpdateFail);
                     return E.ToString();
                 }
             }
         }
void TGServerService.ServerInstance.UpdateLiveSha (string newSha) private
Updates LiveTrackingBranch with the staged Compile(bool)'s SHA
Parameters
newSha The commit SHA that was staged
Definition at line 1367 of file Repository.cs.
References TGServerService.ServerInstance.LiveTrackingBranch, and TGServerService.ServerInstance.LoadRepo().
Referenced by TGServerService.ServerInstance.CompileImpl().
         {
             if (LoadRepo() != null)
                 return;
             var B = Repo.Branches[LiveTrackingBranch];
             if (B != null)
                 Repo.Branches.Remove(B);
             Repo.CreateBranch(LiveTrackingBranch, newSha);
         }
void TGServerService.ServerInstance.UpdateSubmodules () private
Properly updates any git submodules in the repository
Definition at line 696 of file Repository.cs.
References TGServerService.Program.DeleteDirectory(), TGServerService.ServerInstance.SendMessage(), TGServerService.ServerInstance.WriteError(), and TGServerService.ServerInstance.WriteWarning().
Referenced by TGServerService.ServerInstance.Checkout(), TGServerService.ServerInstance.MergePullRequest(), and TGServerService.ServerInstance.UpdateImpl().
         {
             var suo = new SubmoduleUpdateOptions
             {
                 Init = true
             };
             foreach (var I in Repo.Submodules)
                 try
                 {
                     Repo.Submodules.Update(I.Name, suo);
                 }
                 catch (Exception e)
                 {
                     try
                     {
                         //workaround for https://github.com/libgit2/libgit2/issues/3820
                         //kill off the modules/ folder in .git and try again
                         try
{
                             Program.DeleteDirectory(String.Format("{0}/.git/modules/{1}", RepoPath, I.Path));
                         }
                         catch
{
                             throw e;
                         }
                         Repo.Submodules.Update(I.Name, suo);
                         var msg = String.Format("I had to reclone submodule {0}. If this is happening a lot find a better hack or fix https://github.com/libgit2/libgit2/issues/3820!", I.Name);
                         SendMessage(String.Format("REPO: {0}", msg), MessageType.DeveloperInfo);
                         WriteWarning(msg, EventID.Submodule);
                     }
                     catch (Exception ex)
                     {
                         WriteError(String.Format("Failed to update submodule {0}! Error: {1}", I.Name, ex.ToString()), EventID.Submodule);
                     }
                 }
         }
string TGServerService.ServerInstance.UpdateTGS3Json ()
Updates the CachedTGS3SettingsPath with the RepoTGS3SettingsPath
Returns
on success, error message on failure
Implements TGServiceInterface.Components.ITGRepository.
Definition at line 323 of file Repository.cs.
References TGServerService.ServerInstance.RelativePath().
Referenced by TGServerService.ServerInstance.InitialConfigureRepository().
         {
             try
             {
                 if (File.Exists(RelativePath(RepoTGS3SettingsPath)))
                     File.Copy(RelativePath(RepoTGS3SettingsPath), RelativePath(CachedTGS3SettingsPath), true);
                 else if (File.Exists(RelativePath(CachedTGS3SettingsPath)))
                     File.Delete(RelativePath(CachedTGS3SettingsPath));
             }
             catch(Exception e)
             {
                 return e.ToString();
             }
             return null;
         }
bool TGServerService.ServerInstance.UpdateToVersion (int major, int minor)
updates the used byond version to that of version major .minor . The change won't take place until DD reboots. Calls ITGDreamDaemon.RequestRestart if blocked by a running DD instance. Runs asyncronously, use CurrentStatus to check progress
Implements TGServiceInterface.Components.ITGByond.
Definition at line 292 of file Byond.cs.
References TGServerService.ServerInstance.BusyCheck(), and TGServerService.ServerInstance.UpdateToVersionImpl().
         {
             lock (ByondLock)
             {
                 if (!BusyCheck())
                 {
                     updateStat = ByondStatus.Starting;
                     RevisionStaging = new Thread(new ParameterizedThreadStart(UpdateToVersionImpl))
                     {
                         IsBackground = true //don't slow me down
                     };
                     RevisionStaging.Start(String.Format("{0}.{1}", major, minor));
                     return true;
                 }
                 return false;
             }
         }
void TGServerService.ServerInstance.UpdateToVersionImpl (object param)
Downloads and unzips a BYOND revision. Calls ApplyStagedUpdate afterwards if the ServerInstance isn't running, otherwise, calls RequestRestart. Sets lastError on failure
Parameters
param Stringified BYOND revision
Definition at line 200 of file Byond.cs.
References TGServerService.ServerInstance.ApplyStagedUpdate(), TGServerService.ServerInstance.CleanByondStaging(), TGServerService.ServerInstance.DaemonStatus(), TGServerService.ServerInstance.RelativePath(), TGServerService.ServerInstance.RequestRestart(), TGServerService.ServerInstance.SendMessage(), TGServerService.ServerInstance.WriteError(), TGServerService.ServerInstance.WriteInfo(), and TGServerService.ServerInstance.WriteWarning().
Referenced by TGServerService.ServerInstance.UpdateToVersion().
         {
             lock (ByondLock) {
                 if (updateStat != ByondStatus.Starting)
                     return;
                 updateStat = ByondStatus.Downloading;
             }
             try
             {
                 CleanByondStaging();
                 var vi = ((string)param).Split('.');
                 var major = Convert.ToInt32(vi[0]);
                 var minor = Convert.ToInt32(vi[1]);
                 var rrdp = RelativePath(RevisionDownloadPath);
                 using (var client = new WebClient())
                 {
                     SendMessage(String.Format("BYOND: Updating to version {0}.{1}...", major, minor), MessageType.DeveloperInfo);
                     //DOWNLOADING
                     try
                     {
                         client.DownloadFile(String.Format(ByondRevisionsURL, major, minor), rrdp);
                     }
                     catch
                     {
                         SendMessage("BYOND: Update download failed. Does the specified version exist?", MessageType.DeveloperInfo);
                         lastError = String.Format("Download of BYOND version {0}.{1} failed! Does it exist?", major, minor);
                         WriteWarning(String.Format("Failed to update BYOND to version {0}.{1}!", major, minor), EventID.BYONDUpdateFail);
                         lock (ByondLock)
{
                             updateStat = ByondStatus.Idle;
                         }
                         return;
                     }
                 }
                 lock (ByondLock)
                 {
                     updateStat = ByondStatus.Staging;
                 }
                 //STAGING
                 ZipFile.ExtractToDirectory(rrdp, RelativePath(StagingDirectory));
                 lock (ByondLock)
                 {
                     File.WriteAllText(RelativePath(StagingDirectoryInner + VersionFile), String.Format("{0}.{1}", major, minor));
                     //IMPORTANT: SET THE BYOND CONFIG TO NOT PROMPT FOR TRUSTED MODE REEE
                     Directory.CreateDirectory(RelativePath(ByondConfigDir));
                     File.WriteAllText(RelativePath(ByondDDConfig), ByondNoPromptTrustedMode);
                 }
                 File.Delete(RevisionDownloadPath);
                 lock (ByondLock)
                 {
                     updateStat = ByondStatus.Staged;
                 }
                 switch (DaemonStatus())
                 {
                     case DreamDaemonStatus.Offline:
                         if(ApplyStagedUpdate())
                             lastError = null;
                         else
                             lastError = "Failed to apply update!";
                         break;
                     default:
                         RequestRestart();
                         lastError = "Update staged. Awaiting server restart...";
                         SendMessage(String.Format("BYOND: Staging complete. Awaiting server restart...", major, minor), MessageType.DeveloperInfo);
                         WriteInfo(String.Format("BYOND update {0}.{1} staged", major, minor), EventID.BYONDUpdateStaged);
                         break;
                 }
             }
             catch (ThreadAbortException)
             {
                 return;
             }
             catch (Exception e)
             {
                 WriteError("Revision staging errror: " + e.ToString(), EventID.BYONDUpdateFail);
                 lock (ByondLock)
                 {
                     updateStat = ByondStatus.Idle;
                     lastError = e.ToString();
                     RevisionStaging = null;
                 }
             }
         }
void TGServerService.ServerInstance.VerifyConnection ()
Does nothing on the server end, but if the call completes, you can be sure you are connected. WCF won't throw until you try until you actually use the API
Implements TGServiceInterface.Components.ITGConnectivity.
Definition at line 114 of file ServerInstance.cs.
 { }
string TGServerService.ServerInstance.Version ()
Retrieve's the service's version
Implements TGServiceInterface.Components.ITGInstance.
Definition at line 108 of file ServerInstance.cs.
References TGServerService.Service.VersionString.
Referenced by TGServerService.ServerInstance.HandleCommand(), TGServerService.ServerInstance.InitDreamDaemon(), and TGServerService.ServerInstance.StartImpl().
         {
             return Service.VersionString;
         }
void TGServerService.ServerInstance.Watchdog () private
Threaded loop that keeps DreamDaemon from unintentionally stopping
Definition at line 304 of file DreamDaemon.cs.
References TGServerService.ServerInstance.Config, TGServerService.ServerInstance.currentPort, TGServerService.ServerInstance.MemTrackTimer_Elapsed(), TGServerService.IInstanceConfig.ReattachCommsKey, TGServerService.IInstanceConfig.ReattachPort, TGServerService.IInstanceConfig.ReattachProcessID, TGServerService.IInstanceConfig.ReattachRequired, TGServerService.ServerInstance.SCGracefulShutdown, TGServerService.ServerInstance.SendCommand(), TGServerService.ServerInstance.SendMessage(), TGServerService.ServerInstance.serviceCommsKey, TGServerService.ServerInstance.StartImpl(), TGServerService.ServerInstance.WriteCurrentDDLog(), TGServerService.ServerInstance.WriteError(), TGServerService.ServerInstance.WriteInfo(), and TGServerService.ServerInstance.WriteWarning().
Referenced by TGServerService.ServerInstance.InitDreamDaemon(), and TGServerService.ServerInstance.StartImpl().
         {
             try
             {
                 lock (restartLock)
                 {
                     if (!RestartInProgress)
                     {
                         SendMessage("DD: Server started, watchdog active...", MessageType.WatchdogInfo);
                         WriteInfo("Watchdog started", EventID.DDWatchdogStarted);
                     }
                     else
                     {
                         RestartInProgress = false;
                         if (!ReattachInsteadOfRestart)
                             WriteInfo("Watchdog restarted", EventID.DDWatchdogRestarted);
                         else
                             ReattachInsteadOfRestart = false;
                     }
                 }
                 var retries = 0;
                 var MemTrackTimer = new System.Timers.Timer
                 {
                     AutoReset = true,
                     Interval = 5000 //every 5 seconds
                 };
                 MemTrackTimer.Elapsed += MemTrackTimer_Elapsed;
                 while (true)
                 {
                     var starttime = DateTime.Now;
                     lock (watchdogLock)
                     {
                         if (AwaitingShutdown == ShutdownRequestPhase.Requested)
                             SendCommand(SCGracefulShutdown);
                     }
                     //all good to go, let's start monitoring
                     var Now = DateTime.Now;
                     lock (watchdogLock)
                     {
                         CurrentDDLog = DateTime.UtcNow.ToString("yyyy-MM-ddTHH-mm-ssZ");
                         WriteCurrentDDLog("Starting monitoring...");
                     }
                     pcpu = new PerformanceCounter("Process", "% Processor Time", Proc.ProcessName, true);
                     MemTrackTimer.Start();
                     try
                     {
                         Proc.WaitForExit();
                     }
                     finally
                     {
                         lock (watchdogLock) //synchronize
{
                             MemTrackTimer.Stop();
                             pcpu.Dispose();
                         }
                     }
                     WriteCurrentDDLog("Crash detected!");
                     lock (watchdogLock)
                     {
                         currentStatus = DreamDaemonStatus.HardRebooting;
                         currentPort = 0;
                         Proc.Close();
                         if (AwaitingShutdown == ShutdownRequestPhase.Pinged)
                             return;
                         var BadStart = (DateTime.Now - starttime).TotalSeconds < DDBadStartTime;
                         if (BadStart)
{
                             ++retries;
                             var sleep_time = (int)Math.Min(Math.Pow(2, retries), 3600); //max of one hour
                             SendMessage(String.Format("DD: Watchdog server startup failed! Retrying in {0} seconds...", sleep_time), MessageType.WatchdogInfo);
                             Thread.Sleep(sleep_time * 1000);
                         }
                         else
{
                             retries = 0;
                             var msg = "DD: DreamDaemon crashed! Watchdog rebooting DD...";
                             SendMessage(msg, MessageType.WatchdogInfo);
                             WriteWarning(msg, EventID.DDWatchdogRebootingServer);
                         }
                     }
                     var res = StartImpl(true);
                     if (res != null)
                         throw new Exception("Hard restart failed: " + res);
                 }
             }
             catch (ThreadAbortException)
             {
                 //No Mr bond, I expect you to die
                 try
                 {
                     if (!Config.ReattachRequired)
                     {
                         Proc.Kill();
                         Proc.WaitForExit();
                     }
                     else
                     {
                         Config.ReattachProcessID = Proc.Id;
                         Config.ReattachPort = currentPort;
                         Config.ReattachCommsKey = serviceCommsKey;
                         lock (restartLock)
{
                             RestartInProgress = true;
                         }
                     }
                     Proc.Close();
                 }
                 catch
                 { }
             }
             catch (Exception e)
             {
                 SendMessage("DD: Watchdog thread crashed!", MessageType.WatchdogInfo);
                 WriteError("Watch dog thread crashed: " + e.ToString(), EventID.DDWatchdogCrash);
             }
             finally
             {
                 lock (watchdogLock)
                 {
                     currentStatus = DreamDaemonStatus.Offline;
                     currentPort = 0;
                     AwaitingShutdown = ShutdownRequestPhase.None;
                     lock (restartLock)
                     {
                         if (!RestartInProgress)
{
                             if (!Config.ReattachRequired)
                                 SendMessage("DD: Server stopped, watchdog exiting...", MessageType.WatchdogInfo);
                             WriteInfo("Watch dog exited", EventID.DDWatchdogExit);
                         }
                         else
                             WriteInfo("Watch dog restarting...", EventID.DDWatchdogRestart);
                     }
                 }
             }
         }
bool TGServerService.ServerInstance.Webclient ()
Check if the BYOND webclient is currently enabled for the server
Implements TGServiceInterface.Components.ITGDreamDaemon.
Definition at line 731 of file DreamDaemon.cs.
References TGServerService.ServerInstance.Config, and TGServerService.IInstanceConfig.Webclient.
         {
             return Config.Webclient;
         }
string TGServerService.ServerInstance.WorldAnnounce (string message)
Sends a message to everyone on the server
Implements TGServiceInterface.Components.ITGDreamDaemon.
Definition at line 722 of file DreamDaemon.cs.
References TGServerService.Program.SanitizeTopicString(), TGServerService.ServerInstance.SCWorldAnnounce, and TGServerService.ServerInstance.SendCommand().
Referenced by TGServerService.ServerInstance.DisposeDreamDaemon().
         {
             var res = SendCommand(SCWorldAnnounce + ";message=" + Program.SanitizeTopicString(message));
             if (res == "SUCCESS")
                 return null;
             return res;
         }
void TGServerService.ServerInstance.WriteAccess (string username, bool authSuccess) private
Writes an access event to the Windows event log
Parameters
username The (un)authenticated Windows user's name
authSuccess if username authenticated sucessfully, otherwise
Definition at line 93 of file ServerInstance.cs.
References TGServerService.ServerInstance.LoggingID, and TGServerService.Service.WriteEntry().
Referenced by TGServerService.ServerInstance.CheckAccessCore().
         {
             Service.WriteEntry(String.Format("Access from: {0}", username), EventID.Authentication, authSuccess ? EventLogEntryType.SuccessAudit : EventLogEntryType.FailureAudit, LoggingID);
         }
void TGServerService.ServerInstance.WriteCurrentDDLog (string message) private
Write a message to the CurrentDDLog. A timestamp will be prepended to it
Parameters
message The message to log
Definition at line 291 of file DreamDaemon.cs.
References TGServerService.ServerInstance.RelativePath().
Referenced by TGServerService.ServerInstance.DisposeDreamDaemon(), TGServerService.ServerInstance.HandleCommand(), TGServerService.ServerInstance.MemTrackTimer_Elapsed(), and TGServerService.ServerInstance.Watchdog().
         {
             lock (watchdogLock)
             {
                 if (currentStatus != DreamDaemonStatus.Online || CurrentDDLog == null)
                     return;
                 File.AppendAllText(Path.Combine(RelativePath(ResourceDiagnosticsDir), CurrentDDLog), String.Format("[{0}]: {1}\n", DateTime.Now.ToLongTimeString(), message));
             }
         }
void TGServerService.ServerInstance.WriteError (string message, EventID id) private
Writes an error to the Windows event log
Parameters
message The log message
id The EventID of the message
Definition at line 73 of file ServerInstance.cs.
References TGServerService.Service.WriteEntry().
Referenced by TGServerService.ServerInstance.ApplyStagedUpdate(), TGServerService.ServerInstance.CompileImpl(), TGServerService.ServerInstance.DeletePRList(), TGServerService.ServerInstance.InitChat(), TGServerService.ServerInstance.InitDreamDaemon(), TGServerService.ServerInstance.InitialConfigureRepository(), TGServerService.ServerInstance.InitializeImpl(), TGServerService.ServerInstance.MergePullRequest(), TGServerService.ServerInstance.UpdateBridgeDll(), TGServerService.ServerInstance.UpdateSubmodules(), TGServerService.ServerInstance.UpdateToVersionImpl(), and TGServerService.ServerInstance.Watchdog().
         {
             Service.WriteEntry(message, id, EventLogEntryType.Error, LoggingID);
         }
void TGServerService.ServerInstance.WriteInfo (string message, EventID id) private
Writes information to the Windows event log
Parameters
message The log message
id The EventID of the message
Definition at line 63 of file ServerInstance.cs.
References TGServerService.Service.WriteEntry().
Referenced by TGServerService.ServerInstance.ApplyStagedUpdate(), TGServerService.ServerInstance.ChatProvider_OnChatMessage(), TGServerService.ServerInstance.Checkout(), TGServerService.ServerInstance.Clone(), TGServerService.ServerInstance.Commit(), TGServerService.ServerInstance.CompileImpl(), TGServerService.ServerInstance.CreateBackup(), TGServerService.ServerInstance.DeleteFile(), TGServerService.ServerInstance.GenCommsKey(), TGServerService.ServerInstance.GenerateChangelogImpl(), TGServerService.ServerInstance.HandleCommand(), TGServerService.ServerInstance.HandleEvent(), TGServerService.ServerInstance.InitDreamDaemon(), TGServerService.ServerInstance.MergePullRequest(), TGServerService.ServerInstance.Push(), TGServerService.ServerInstance.PushTestmergeCommit(), TGServerService.ServerInstance.ReadText(), TGServerService.ServerInstance.Reset(), TGServerService.ServerInstance.UpdateBridgeDll(), TGServerService.ServerInstance.UpdateImpl(), TGServerService.ServerInstance.UpdateToVersionImpl(), TGServerService.ServerInstance.Watchdog(), and TGServerService.ServerInstance.WriteText().
         {
             Service.WriteEntry(message, id, EventLogEntryType.Information, LoggingID);
         }
string TGServerService.ServerInstance.WriteText (string staticRelativePath, string data, out bool unauthorized)
Write to a static file
Implements TGServiceInterface.Components.ITGConfig.
Definition at line 104 of file Config.cs.
References TGServerService.Service.CancelImpersonation(), TGServerService.ServerInstance.RelativePath(), TGServerService.ServerInstance.StaticDirs, TGServerService.ServerInstance.WriteInfo(), and TGServerService.ServerInstance.WriteWarning().
         {
             var path = RelativePath(StaticDirs) + '/' + staticRelativePath;   //do not use path.combine or it will try and take the root
             try
             {
                 lock (configLock)
                 {
                     var di1 = new DirectoryInfo(RelativePath(StaticDirs));
                     var destdir = new FileInfo(path).Directory.FullName;
                     var di2 = new DirectoryInfo(destdir);
                     var good = false;
                     while (di2 != null)
                     {
                         if (di2.FullName == di1.FullName)
{
                             good = true;
                             break;
                         }
                         else di2 = di2.Parent;
                     }
                     if (!good)
                     {
                         unauthorized = false;
                         return "Cannot write above static directories!";
                     }
                     Directory.CreateDirectory(destdir);
                     File.WriteAllText(path, data);
                     Service.CancelImpersonation();
                     WriteInfo("Write to " + path, EventID.StaticWrite);
                     unauthorized = false;
                     return null;
                 }
             }
             catch (UnauthorizedAccessException e)
             {
                 //no need for the full stacktrace
                 unauthorized = true;
                 return e.Message;
             }
             catch (Exception e)
             {
                 unauthorized = false;
                 Service.CancelImpersonation();
                 WriteWarning(String.Format("Write of {0} failed! Error: {1}", path, e.ToString()), EventID.StaticRead);
                 return e.ToString();
             }
         }
void TGServerService.ServerInstance.WriteWarning (string message, EventID id) private
Writes a warning to the Windows event log
Parameters
message The log message
id The EventID of the message
Definition at line 83 of file ServerInstance.cs.
References TGServerService.Service.WriteEntry().
Referenced by TGServerService.ServerInstance.Checkout(), TGServerService.ServerInstance.Clone(), TGServerService.ServerInstance.Commit(), TGServerService.ServerInstance.CompileImpl(), TGServerService.ServerInstance.CreateBackup(), TGServerService.ServerInstance.DeleteFile(), TGServerService.ServerInstance.GenerateChangelogImpl(), TGServerService.ServerInstance.HandleCommand(), TGServerService.ServerInstance.HandleEvent(), TGServerService.ServerInstance.InitChat(), TGServerService.ServerInstance.InitialConfigureRepository(), TGServerService.ServerInstance.InteropMessage(), TGServerService.ServerInstance.MergePullRequest(), TGServerService.ServerInstance.Push(), TGServerService.ServerInstance.PushTestmergeCommit(), TGServerService.ServerInstance.ReadText(), TGServerService.ServerInstance.Reset(), TGServerService.ServerInstance.SendMessage(), TGServerService.ServerInstance.UpdateImpl(), TGServerService.ServerInstance.UpdateSubmodules(), TGServerService.ServerInstance.UpdateToVersionImpl(), TGServerService.ServerInstance.Watchdog(), and TGServerService.ServerInstance.WriteText().
         {
             Service.WriteEntry(message, id, EventLogEntryType.Warning, LoggingID);
         }
Member Data Documentation
const string TGServerService.ServerInstance.ADirTest = GameDirA + LiveFile private
Definition at line 34 of file Compiler.cs.
const int TGServerService.ServerInstance.AllowedMajorAPIVersion = 2 private
Definition at line 24 of file Interop.cs.
Referenced by TGServerService.ServerInstance.CheckAPIVersionConstraints().
object TGServerService.ServerInstance.authLock = new object() private
Used for multithreading safety
Definition at line 22 of file Administration.cs.
System.Timers.Timer TGServerService.ServerInstance.autoUpdateTimer private
Initial value:
= new System.Timers.Timer()
        {
            AutoReset = true
        }
Used for automatically updating the ServerInstance
Definition at line 91 of file Repository.cs.
Referenced by TGServerService.ServerInstance.InitRepo(), and TGServerService.ServerInstance.SetAutoUpdateInterval().
ShutdownRequestPhase TGServerService.ServerInstance.AwaitingShutdown private
Indicator of progress on a RequestRestart or RequestStop operation
Definition at line 92 of file DreamDaemon.cs.
const string TGServerService.ServerInstance.BDirTest = GameDirB + LiveFile private
Definition at line 35 of file Compiler.cs.
const string TGServerService.ServerInstance.BridgeDLLName = "TGDreamDaemonBridge.dll" private
The file name of the .dll that contains the ITGInterop bridge class
Definition at line 55 of file Interop.cs.
Referenced by TGServerService.ServerInstance.CleanGameFolder(), TGServerService.ServerInstance.CompileImpl(), TGServerService.ServerInstance.InitializeImpl(), TGServerService.ServerInstance.IsInitialized(), and TGServerService.ServerInstance.UpdateBridgeDll().
const string TGServerService.ServerInstance.ByondConfigDir = StagingDirectory + "/BYOND/cfg" private
The instance directory to modify the BYOND cfg before installation
Definition at line 46 of file Byond.cs.
const string TGServerService.ServerInstance.ByondDDConfig = ByondConfigDir + "/daemon.txt" private
BYOND's DreamDaemon config file in the cfg modification directory
Definition at line 50 of file Byond.cs.
const string TGServerService.ServerInstance.ByondDirectory = "BYOND" private
The instance directory to store the BYOND installation
Definition at line 18 of file Byond.cs.
Referenced by TGServerService.ServerInstance.CompileImpl(), and TGServerService.ServerInstance.InitDreamDaemon().
const string TGServerService.ServerInstance.ByondLatestURL = "https://secure.byond.com/download/build/LATEST/" private
The URL for getting the latest BYOND version zipfile
Definition at line 42 of file Byond.cs.
object TGServerService.ServerInstance.ByondLock = new object() private
Used for multithreading safety
Definition at line 64 of file Byond.cs.
const string TGServerService.ServerInstance.ByondNoPromptTrustedMode = "trusted-check 0" private
Setting to add to ByondDDConfig to suppress an invisible user prompt for running a trusted mode .dmb
Definition at line 54 of file Byond.cs.
const string TGServerService.ServerInstance.ByondRevisionsURL = "https://secure.byond.com/download/build/{0}/{0}.{1}_byond.zip" private
The URL format string for getting BYOND version {0}.{1} zipfile
Definition at line 38 of file Byond.cs.
const string TGServerService.ServerInstance.CachedTGS3SettingsPath = "TGS3.json" private
Path to the ServerInstance's RepoConfig json
Definition at line 32 of file Repository.cs.
bool TGServerService.ServerInstance.canCancelCompilation = false private
Definition at line 44 of file Compiler.cs.
const string TGServerService.ServerInstance.CCPAdminOnly = "admin_only" private
Definition at line 49 of file Interop.cs.
const string TGServerService.ServerInstance.CCPHelpText = "help_text" private
Definition at line 48 of file Interop.cs.
const string TGServerService.ServerInstance.CCPRequiredParameters = "required_parameters" private
Definition at line 50 of file Interop.cs.
object TGServerService.ServerInstance.ChatLock = new object() private
Used for multithreading safety
Definition at line 26 of file Chat.cs.
IList<IChatProvider> TGServerService.ServerInstance.ChatProviders private
List of IChatProviders for the ServerInstance
Definition at line 22 of file Chat.cs.
bool TGServerService.ServerInstance.Cloning = false private
Whether or not a git clone operation is in progress
Definition at line 77 of file Repository.cs.
const string TGServerService.ServerInstance.CommitMessage = "Automatic changelog compile, [ci skip]" private
Commit message for RepoConfig.PathsToStage
Definition at line 64 of file Repository.cs.
const int TGServerService.ServerInstance.CommsKeyLen = 64 private
Definition at line 20 of file Interop.cs.
bool TGServerService.ServerInstance.compilationCancellationRequestation = false private
Definition at line 43 of file Compiler.cs.
CompilerStatus TGServerService.ServerInstance.compilerCurrentStatus private
Definition at line 39 of file Compiler.cs.
Referenced by TGServerService.ServerInstance.ApplyStagedUpdate(), and TGServerService.ServerInstance.GetStatus().
object TGServerService.ServerInstance.CompilerLock = new object() private
Definition at line 38 of file Compiler.cs.
Referenced by TGServerService.ServerInstance.ApplyStagedUpdate(), TGServerService.ServerInstance.HandleCommand(), and TGServerService.ServerInstance.Setup().
Thread TGServerService.ServerInstance.CompilerThread private
Definition at line 42 of file Compiler.cs.
readonly IInstanceConfig TGServerService.ServerInstance.Config private
The configuration settings for the instance
Definition at line 27 of file ServerInstance.cs.
Referenced by TGServerService.ServerInstance.Autostart(), TGServerService.ServerInstance.AutoUpdateInterval(), TGServerService.ServerInstance.CanStart(), TGServerService.ServerInstance.CheckAccessCore(), TGServerService.ServerInstance.CompileImpl(), TGServerService.ServerInstance.DisposeChat(), TGServerService.ServerInstance.DisposeDreamDaemon(), TGServerService.ServerInstance.FindTheDroidsWereLookingFor(), TGServerService.ServerInstance.GenerateChangelogImpl(), TGServerService.ServerInstance.GetCommitterEmail(), TGServerService.ServerInstance.GetCommitterName(), TGServerService.ServerInstance.GetStagingDir(), TGServerService.ServerInstance.InitDreamDaemon(), TGServerService.ServerInstance.InitialConfigureRepository(), TGServerService.ServerInstance.InitProviderInfos(), TGServerService.ServerInstance.InitRepo(), TGServerService.ServerInstance.MakeSig(), TGServerService.ServerInstance.MergePullRequest(), TGServerService.ServerInstance.Port(), TGServerService.ServerInstance.ProjectName(), TGServerService.ServerInstance.PushTestmergeCommit(), TGServerService.ServerInstance.PushTestmergeCommits(), TGServerService.ServerInstance.ReadText(), TGServerService.ServerInstance.SecurityLevel(), TGServerService.ServerInstance.SecurityWord(), TGServerService.ServerInstance.SetAuthorizedGroup(), TGServerService.ServerInstance.SetAutostart(), TGServerService.ServerInstance.SetAutoUpdateInterval(), TGServerService.ServerInstance.SetCommitterEmail(), TGServerService.ServerInstance.SetCommitterName(), TGServerService.ServerInstance.SetPort(), TGServerService.ServerInstance.SetProjectName(), TGServerService.ServerInstance.SetPushTestmergeCommits(), TGServerService.ServerInstance.SetSecurityLevel(), TGServerService.ServerInstance.SetWebclient(), TGServerService.ServerInstance.StartImpl(), TGServerService.ServerInstance.SynchronizePush(), TGServerService.ServerInstance.Watchdog(), and TGServerService.ServerInstance.Webclient().
object TGServerService.ServerInstance.configLock = new object() private
Used for multithreading safety
Definition at line 15 of file Config.cs.
Referenced by TGServerService.ServerInstance.Clone(), and TGServerService.ServerInstance.RecreateStaticFolder().
string TGServerService.ServerInstance.CurrentDDLog private
Current logfile in use in ResourceDiagnosticsDir
Definition at line 65 of file DreamDaemon.cs.
ushort TGServerService.ServerInstance.currentPort = 0 private
Current port DreamDaemon is running on
Definition at line 69 of file DreamDaemon.cs.
Referenced by TGServerService.ServerInstance.SendCommand(), and TGServerService.ServerInstance.Watchdog().
int TGServerService.ServerInstance.currentProgress = -1 private
Used for reporting operation progress to the TGServiceInterface
Definition at line 86 of file Repository.cs.
Referenced by TGServerService.ServerInstance.CheckoutProgress().
DreamDaemonStatus TGServerService.ServerInstance.currentStatus private
The DreamDaemonStatus of Proc
Definition at line 61 of file DreamDaemon.cs.
Referenced by TGServerService.ServerInstance.CompileImpl(), TGServerService.ServerInstance.DaemonStatus(), TGServerService.ServerInstance.RecreateStaticFolder(), and TGServerService.ServerInstance.SendCommand().
const int TGServerService.ServerInstance.DDBadStartTime = 10 private
If DreamDaemon crashes before this time it is considered a bad startup
Definition at line 39 of file DreamDaemon.cs.
const int TGServerService.ServerInstance.DDHangStartTime = 60 private
Time until DD is considered DOA on startup
Definition at line 35 of file DreamDaemon.cs.
Thread TGServerService.ServerInstance.DDWatchdog private
The thread that monitors the status of DreamDaemon
Definition at line 57 of file DreamDaemon.cs.
Referenced by TGServerService.ServerInstance.Stop().
const string TGServerService.ServerInstance.DiagnosticsDir = "Diagnostics" private
Directory for storing DreamDaemon diagnostic files
Definition at line 27 of file DreamDaemon.cs.
bool TGServerService.ServerInstance.disposedValue = false private
To detect redundant Dispose() calls
Definition at line 144 of file ServerInstance.cs.
Referenced by TGServerService.ServerInstance.Offline().
const string TGServerService.ServerInstance.DreamDaemonBridgeNamespace = "TGDreamDaemonBridge" private
The namespace that contains the ITGInterop bridge class. Used for reflection
Definition at line 59 of file Interop.cs.
const string TGServerService.ServerInstance.DreamDaemonBridgeType = DreamDaemonBridgeNamespace + ".DreamDaemonBridge" private
The ITGInterop bridge class. Used for reflection
Definition at line 63 of file Interop.cs.
Referenced by TGServerService.ServerInstance.UpdateBridgeDll().
const string TGServerService.ServerInstance.EventFolder = "EventHandlers/" private
The instance directory for Preaction handlers
Definition at line 13 of file PreactionHandler.cs.
Version TGServerService.ServerInstance.GameAPIVersion private
Definition at line 25 of file Interop.cs.
Referenced by TGServerService.ServerInstance.InitDreamDaemon(), and TGServerService.ServerInstance.StartImpl().
const string TGServerService.ServerInstance.GameDir = "Game" private
Definition at line 28 of file Compiler.cs.
const string TGServerService.ServerInstance.GameDirA = GameDir + "/A" private
Definition at line 29 of file Compiler.cs.
Referenced by TGServerService.ServerInstance.InvertDirectory().
const string TGServerService.ServerInstance.GameDirB = GameDir + "/B" private
Definition at line 30 of file Compiler.cs.
Referenced by TGServerService.ServerInstance.InvertDirectory().
const string TGServerService.ServerInstance.GameDirLive = GameDir + "/Live" private
Definition at line 31 of file Compiler.cs.
Referenced by TGServerService.ServerInstance.CanStart(), and TGServerService.ServerInstance.StartImpl().
string TGServerService.ServerInstance.lastCompilerError private
Definition at line 40 of file Compiler.cs.
Referenced by TGServerService.ServerInstance.CompileError().
string TGServerService.ServerInstance.lastError private
The last error the BYOND updater encountered
Definition at line 68 of file Byond.cs.
Referenced by TGServerService.ServerInstance.GetError().
string TGServerService.ServerInstance.LastSeenUser private
The WindowsIdentity.Name of the last WindowsIdentity to attempt to access the ServerInstance
Definition at line 26 of file Administration.cs.
const string TGServerService.ServerInstance.LiveDirTest = GameDirLive + LiveFile private
Definition at line 36 of file Compiler.cs.
const string TGServerService.ServerInstance.LiveFile = "/TestLive.lk" private
Definition at line 33 of file Compiler.cs.
const string TGServerService.ServerInstance.LiveTrackingBranch = "___TGSLiveCommitTrackingBranch" private
The branch that points to the current commit that is live or staged to be live in DreamDaemon
Definition at line 60 of file Repository.cs.
Referenced by TGServerService.ServerInstance.LiveSha(), and TGServerService.ServerInstance.UpdateLiveSha().
readonly byte TGServerService.ServerInstance.LoggingID
Used to assign the instance to event IDs
Definition at line 23 of file ServerInstance.cs.
Referenced by TGServerService.ServerInstance.WriteAccess().
PerformanceCounter TGServerService.ServerInstance.pcpu private
CPU performance information for Proc
Definition at line 48 of file DreamDaemon.cs.
const string TGServerService.ServerInstance.PrivateKeyPath = RepoKeyDir + "private_key.txt" private
The path to the private ssh-rsa key file
Definition at line 48 of file Repository.cs.
const string TGServerService.ServerInstance.PRJobFile = "prtestjob.json" private
File name for monitoring which github pull requests are currently test merged
Definition at line 56 of file Repository.cs.
Referenced by TGServerService.ServerInstance.CompileImpl().
Process TGServerService.ServerInstance.Proc private
The DreamDaemon process
Definition at line 44 of file DreamDaemon.cs.
Referenced by TGServerService.ServerInstance.CompileImpl().
const string TGServerService.ServerInstance.PublicKeyPath = RepoKeyDir + "public_key.txt" private
The path to the public ssh-rsa key file
Definition at line 52 of file Repository.cs.
bool TGServerService.ServerInstance.ReattachInsteadOfRestart = false private
Used to indicate if an service restart is in progress on the watchdog. Requires restartLock to access
Definition at line 82 of file DreamDaemon.cs.
const string TGServerService.ServerInstance.RemoteTempBranchName = "___TGS3TempBranch" private
The branch name used for publishing testmerge commits
Definition at line 24 of file Repository.cs.
Repository TGServerService.ServerInstance.Repo private
The repository object
Definition at line 82 of file Repository.cs.
bool TGServerService.ServerInstance.RepoBusy = false private
Used in conjunction with RepoLock for multithreading safety
Definition at line 73 of file Repository.cs.
Referenced by TGServerService.ServerInstance.CompileImpl(), and TGServerService.ServerInstance.OperationInProgress().
const string TGServerService.ServerInstance.RepoErrorUpToDate = "Already up to date!" private
Error message for when a merge operation fails due to the target branch already having the source branch's commits
Definition at line 36 of file Repository.cs.
Referenced by TGServerService.ServerInstance.MergeBranch(), and TGServerService.ServerInstance.UpdateImpl().
const string TGServerService.ServerInstance.RepoKeyDir = "RepoKey/" private
The ServerInstance directory for the repository SSH keys
Definition at line 44 of file Repository.cs.
object TGServerService.ServerInstance.RepoLock = new object() private
Used in conjunction with RepoBusy for multithreading safety
Definition at line 69 of file Repository.cs.
Referenced by TGServerService.ServerInstance.CompileImpl(), and TGServerService.ServerInstance.RecreateStaticFolder().
const string TGServerService.ServerInstance.RepoPath = "Repository" private
The ServerInstance directory for the repository
Definition at line 20 of file Repository.cs.
Referenced by TGServerService.ServerInstance.CompileImpl(), and TGServerService.ServerInstance.ReadText().
const string TGServerService.ServerInstance.RepoTGS3SettingsPath = RepoPath + "/TGS3.json" private
The path to the Repository's RepoConfig json
Definition at line 28 of file Repository.cs.
const string TGServerService.ServerInstance.ResourceDiagnosticsDir = DiagnosticsDir + "/Resources" private
Directory for storing DreamDaemon ResourceUsage files
Definition at line 31 of file DreamDaemon.cs.
bool TGServerService.ServerInstance.RestartInProgress = false private
Used to indicate if an intentional restart is in progress on the watchdog. Requires restartLock to access
Definition at line 78 of file DreamDaemon.cs.
object TGServerService.ServerInstance.restartLock = new object() private
Used for multithreading safety
Definition at line 74 of file DreamDaemon.cs.
const string TGServerService.ServerInstance.RevisionDownloadPath = "BYONDRevision.zip" private
The path in the instance directory to store the downloaded BYOND revision
Definition at line 30 of file Byond.cs.
Thread TGServerService.ServerInstance.RevisionStaging private
Thread used for staging BYOND revisions
Definition at line 72 of file Byond.cs.
const string TGServerService.ServerInstance.SCAPICompat = "api_compat" private
Definition at line 34 of file Interop.cs.
const string TGServerService.ServerInstance.SCGracefulShutdown = "graceful_shutdown" private
Definition at line 31 of file Interop.cs.
Referenced by TGServerService.ServerInstance.RequestStop(), and TGServerService.ServerInstance.Watchdog().
const string TGServerService.ServerInstance.SCHardReboot = "hard_reboot" private
Definition at line 30 of file Interop.cs.
Referenced by TGServerService.ServerInstance.RequestRestart().
const string TGServerService.ServerInstance.SCListCustomCommands = "list_custom_commands" private
Definition at line 33 of file Interop.cs.
const string TGServerService.ServerInstance.SCPlayerCount = "client_count" private
Definition at line 35 of file Interop.cs.
const string TGServerService.ServerInstance.SCWorldAnnounce = "world_announce" private
Definition at line 32 of file Interop.cs.
Referenced by TGServerService.ServerInstance.WorldAnnounce().
List<Command> TGServerService.ServerInstance.ServerChatCommands private
Definition at line 65 of file Interop.cs.
Referenced by TGServerService.ServerInstance.ChatProvider_OnChatMessage().
string TGServerService.ServerInstance.serviceCommsKey private
Definition at line 21 of file Interop.cs.
Referenced by TGServerService.ServerInstance.InitDreamDaemon(), TGServerService.ServerInstance.StartImpl(), and TGServerService.ServerInstance.Watchdog().
readonly SecurityIdentifier TGServerService.ServerInstance.ServiceSID = WindowsIdentity.GetCurrent().User private
The SecurityIdentifier of the account the Service is running as
Definition at line 31 of file Administration.cs.
Referenced by TGServerService.ServerInstance.CheckAccessCore().
bool TGServerService.ServerInstance.silentCompile = false private
Definition at line 45 of file Compiler.cs.
Referenced by TGServerService.ServerInstance.CompileImpl().
const string TGServerService.ServerInstance.SPInstanceName = "server_instance" private
Definition at line 27 of file Interop.cs.
Referenced by TGServerService.ServerInstance.StartImpl().
const string TGServerService.ServerInstance.SRAPIVersion = "api_ver" private
Definition at line 46 of file Interop.cs.
const string TGServerService.ServerInstance.SRetSuccess = "SUCCESS" private
String returned when a command completes successfully with no output
Definition at line 40 of file Interop.cs.
const string TGServerService.ServerInstance.SRIRCAdminChannelMessage = "send2irc" private
Definition at line 44 of file Interop.cs.
const string TGServerService.ServerInstance.SRIRCBroadcast = "irc" private
Definition at line 43 of file Interop.cs.
const string TGServerService.ServerInstance.SRKillProcess = "killme" private
Definition at line 42 of file Interop.cs.
const string TGServerService.ServerInstance.SRWorldReboot = "worldreboot" private
Definition at line 45 of file Interop.cs.
const string TGServerService.ServerInstance.SSHPushRemote = "ssh_push_target" private
Git remote for push operations
Definition at line 40 of file Repository.cs.
Referenced by TGServerService.ServerInstance.PushTestmergeCommit().
const string TGServerService.ServerInstance.StagingDirectory = "BYOND_staged" private
The instance directory to use when updating the BYOND installation
Definition at line 22 of file Byond.cs.
const string TGServerService.ServerInstance.StagingDirectoryInner = StagingDirectory + "/byond" private
Path to the actual BYOND installation within the StagingDirectory
Definition at line 26 of file Byond.cs.
DreamDaemonSecurity TGServerService.ServerInstance.StartingSecurity private
Current DreamDaemonSecurity level of DreamDaemon
Definition at line 87 of file DreamDaemon.cs.
const string TGServerService.ServerInstance.StaticBackupDir = "Static_BACKUP" private
Definition at line 26 of file Compiler.cs.
Referenced by TGServerService.ServerInstance.BackupAndDeleteStaticDirectory().
const string TGServerService.ServerInstance.StaticDirs = "Static" private
Definition at line 25 of file Compiler.cs.
Referenced by TGServerService.ServerInstance.BackupAndDeleteStaticDirectory(), TGServerService.ServerInstance.DeleteFile(), TGServerService.ServerInstance.InitialConfigureRepository(), TGServerService.ServerInstance.ListStaticDirectory(), TGServerService.ServerInstance.ReadText(), and TGServerService.ServerInstance.WriteText().
SecurityIdentifier TGServerService.ServerInstance.TheDroidsWereLookingFor private
The SecurityIdentifier of the Windows group authorized to access the ServerInstance
Definition at line 18 of file Administration.cs.
object TGServerService.ServerInstance.topicLock = new object() private
Definition at line 19 of file Interop.cs.
Referenced by TGServerService.ServerInstance.StartImpl().
const string TGServerService.ServerInstance.UninitializedString = "NEEDS INITIALIZING"
Used for indicating unintialized encrypted data
Definition at line 17 of file Chat.cs.
Referenced by TGServerService.ServerInstance.InitProviderInfos().
bool TGServerService.ServerInstance.UpdateStaged = false private
Definition at line 47 of file Compiler.cs.
Referenced by TGServerService.ServerInstance.HandleCommand().
ByondStatus TGServerService.ServerInstance.updateStat = ByondStatus.Idle private
The status of the BYOND updater
Definition at line 59 of file Byond.cs.
Referenced by TGServerService.ServerInstance.CurrentStatus().
const string TGServerService.ServerInstance.VersionFile = "/byond_version.dat" private
The location of the BYOND version data of an installation
Definition at line 34 of file Byond.cs.
Referenced by TGServerService.ServerInstance.GetVersion().
object TGServerService.ServerInstance.watchdogLock = new object() private
Used for multithreading safety
Definition at line 53 of file DreamDaemon.cs.
Referenced by TGServerService.ServerInstance.CompileImpl(), TGServerService.ServerInstance.RecreateStaticFolder(), and TGServerService.ServerInstance.SendCommand().
The documentation for this class was generated from the following files:
TGServerService/ServerInstance/Administration.cs
TGServerService/ServerInstance/Byond.cs
TGServerService/ServerInstance/Chat.cs
TGServerService/ServerInstance/Compiler.cs
TGServerService/ServerInstance/Config.cs
TGServerService/ServerInstance/DreamDaemon.cs
TGServerService/ServerInstance/Interop.cs
TGServerService/ServerInstance/PreactionHandler.cs
TGServerService/ServerInstance/Repository.cs
TGServerService/ServerInstance/ServerInstance.cs