tgstation-server: Tgstation.Server.Host.Database.DatabaseSeeder Class Reference
Tgstation.Server.Host.Database.DatabaseSeeder Class Reference sealed
Public Member Functions
DatabaseSeeder (ICryptographySuite cryptographySuite, IPlatformIdentifier platformIdentifier, IOptions< GeneralConfiguration > generalConfigurationOptions, IOptions< DatabaseConfiguration > databaseConfigurationOptions, IOptions< SwarmConfiguration > swarmConfigurationOptions, ILogger< DatabaseContext > databaseLogger, ILogger< DatabaseSeeder > logger)
Initializes a new instance of the DatabaseSeeder class.
async ValueTask Initialize (IDatabaseContext databaseContext, CancellationToken cancellationToken)
Setup up a given databaseContext .
Parameters
databaseContext The IDatabaseContext to setup.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
ValueTask Downgrade (IDatabaseContext databaseContext, Version downgradeVersion, CancellationToken cancellationToken)
Migrate a given databaseContext down.
Parameters
databaseContext The IDatabaseContext to downgrade.
downgradeVersion The migration Version to downgrade the databaseContext to.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Private Member Functions
User SeedAdminUser (IDatabaseContext databaseContext)
Add a default admin User to a given databaseContext .
async ValueTask SeedDatabase (IDatabaseContext databaseContext, CancellationToken cancellationToken)
Initially seed a given databaseContext .
async ValueTask SanitizeDatabase (IDatabaseContext databaseContext, CancellationToken cancellationToken)
Correct invalid database data caused by previous versions (NOT user fuckery).
async ValueTask ResetAdminPassword (IDatabaseContext databaseContext, CancellationToken cancellationToken)
Changes the admin password in IDatabaseContext back to it's default, enables the account, and gives it AdministrationRights.WriteUsers access.
async ValueTask< User?> GetAdminUser (IDatabaseContext databaseContext, CancellationToken cancellationToken)
Get or create the admin User.
Static Private Member Functions
static User SeedSystemUser (IDatabaseContext databaseContext, User? tgsUser=null)
Add a default system User to a given databaseContext .
Private Attributes
readonly ICryptographySuite cryptographySuite
The ICryptographySuite for the DatabaseSeeder.
readonly IPlatformIdentifier platformIdentifier
The IPlatformIdentifier for the DatabaseSeeder.
readonly ILogger< DatabaseContext > databaseLogger
The ILogger used for IDatabaseContexts.
readonly ILogger< DatabaseSeeder > logger
The ILogger for the DatabaseSeeder.
readonly GeneralConfiguration generalConfiguration
The GeneralConfiguration for the DatabaseSeeder.
readonly DatabaseConfiguration databaseConfiguration
The DatabaseConfiguration for the DatabaseSeeder.
readonly SwarmConfiguration swarmConfiguration
The SwarmConfiguration for the DatabaseSeeder.
Detailed Description
Definition at line 20 of file DatabaseSeeder.cs.
Constructor & Destructor Documentation
DatabaseSeeder()
Tgstation.Server.Host.Database.DatabaseSeeder.DatabaseSeeder (ICryptographySuite cryptographySuite, IPlatformIdentifier platformIdentifier, IOptions< GeneralConfiguration > generalConfigurationOptions, IOptions< DatabaseConfiguration > databaseConfigurationOptions, IOptions< SwarmConfiguration > swarmConfigurationOptions, ILogger< DatabaseContext > databaseLogger, ILogger< DatabaseSeeder > logger)
Initializes a new instance of the DatabaseSeeder class.
Parameters
cryptographySuite The value of cryptographySuite.
platformIdentifier The value of platformIdentifier.
generalConfigurationOptions The IOptions<TOptions> containing the value of generalConfiguration.
databaseConfigurationOptions The IOptions<TOptions> containing the value of databaseConfiguration.
swarmConfigurationOptions The IOptions<TOptions> containing the value of swarmConfiguration.
databaseLogger The value of databaseLogger.
logger The value of logger.
Definition at line 92 of file DatabaseSeeder.cs.
        {
            this.cryptographySuite = cryptographySuite ?? throw new ArgumentNullException(nameof(cryptographySuite));
            this.platformIdentifier = platformIdentifier ?? throw new ArgumentNullException(nameof(platformIdentifier));
            databaseConfiguration = databaseConfigurationOptions?.Value ?? throw new ArgumentNullException(nameof(databaseConfigurationOptions));
            generalConfiguration = generalConfigurationOptions?.Value ?? throw new ArgumentNullException(nameof(generalConfigurationOptions));
            swarmConfiguration = swarmConfigurationOptions?.Value ?? throw new ArgumentNullException(nameof(swarmConfigurationOptions));
            this.databaseLogger = databaseLogger ?? throw new ArgumentNullException(nameof(databaseLogger));
            this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }
References Tgstation.Server.Host.Database.DatabaseSeeder.cryptographySuite, Tgstation.Server.Host.Database.DatabaseSeeder.databaseConfiguration, Tgstation.Server.Host.Database.DatabaseSeeder.databaseLogger, Tgstation.Server.Host.Database.DatabaseSeeder.generalConfiguration, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Database.DatabaseSeeder.logger, Tgstation.Server.Host.Database.DatabaseSeeder.platformIdentifier, and Tgstation.Server.Host.Database.DatabaseSeeder.swarmConfiguration.
Member Function Documentation
Downgrade()
ValueTask Tgstation.Server.Host.Database.DatabaseSeeder.Downgrade (IDatabaseContext databaseContext, Version downgradeVersion, CancellationToken cancellationToken)
Migrate a given databaseContext down.
Parameters
databaseContext The IDatabaseContext to downgrade.
downgradeVersion The migration Version to downgrade the databaseContext to.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Database.IDatabaseSeeder.
Definition at line 140 of file DatabaseSeeder.cs.
        {
            ArgumentNullException.ThrowIfNull(databaseContext);
            ArgumentNullException.ThrowIfNull(downgradeVersion);
            return databaseContext.SchemaDowngradeForServerVersion(
                databaseLogger,
                downgradeVersion,
                databaseConfiguration.DatabaseType,
                cancellationToken);
        }
References Tgstation.Server.Host.Database.DatabaseSeeder.databaseConfiguration, Tgstation.Server.Host.Database.DatabaseSeeder.databaseLogger, Tgstation.Server.Host.Configuration.DatabaseConfiguration.DatabaseType, Tgstation.Server.Api.Rights.List, and Tgstation.Server.Host.Database.IDatabaseContext.SchemaDowngradeForServerVersion().
GetAdminUser()
async ValueTask< User?> Tgstation.Server.Host.Database.DatabaseSeeder.GetAdminUser (IDatabaseContext databaseContext, CancellationToken cancellationToken) private
Get or create the admin User.
Parameters
databaseContext The IDatabaseContext to use.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the admin User or null. If null, IDatabaseContext.Save(CancellationToken) must be called on databaseContext .
Definition at line 310 of file DatabaseSeeder.cs.
        {
            var admin = await databaseContext
                .Users
                .AsQueryable()
                .Where(x => x.CanonicalName == User.CanonicalizeName(DefaultCredentials.AdminUserName))
                .Include(x => x.CreatedBy)
                .Include(x => x.PermissionSet)
                .Include(x => x.Group)
                .FirstOrDefaultAsync(cancellationToken);
            if (admin == default)
                SeedAdminUser(databaseContext);
            return admin;
        }
References Tgstation.Server.Api.DefaultCredentials.AdminUserName, Tgstation.Server.Host.Models.User.CanonicalizeName(), Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Database.DatabaseSeeder.SeedAdminUser(), and Tgstation.Server.Host.Database.IDatabaseContext.Users.
Referenced by Tgstation.Server.Host.Database.DatabaseSeeder.ResetAdminPassword(), and Tgstation.Server.Host.Database.DatabaseSeeder.SanitizeDatabase().
Initialize()
async ValueTask Tgstation.Server.Host.Database.DatabaseSeeder.Initialize (IDatabaseContext databaseContext, CancellationToken cancellationToken)
Setup up a given databaseContext .
Parameters
databaseContext The IDatabaseContext to setup.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Database.IDatabaseSeeder.
Definition at line 111 of file DatabaseSeeder.cs.
        {
            ArgumentNullException.ThrowIfNull(databaseContext);
            if (databaseConfiguration.DropDatabase)
            {
                logger.LogCritical("DropDatabase configuration option set! Dropping any existing database...");
                await databaseContext.Drop(cancellationToken);
            }
            var wasEmpty = await databaseContext.Migrate(databaseLogger, cancellationToken);
            if (wasEmpty)
            {
                logger.LogInformation("Seeding database...");
                await SeedDatabase(databaseContext, cancellationToken);
            }
            else
            {
                if (databaseConfiguration.ResetAdminPassword)
                {
                    logger.LogWarning("Enabling and resetting admin password due to configuration!");
                    await ResetAdminPassword(databaseContext, cancellationToken);
                }
                await SanitizeDatabase(databaseContext, cancellationToken);
            }
        }
References Tgstation.Server.Host.Database.DatabaseSeeder.databaseConfiguration, Tgstation.Server.Host.Database.DatabaseSeeder.databaseLogger, Tgstation.Server.Host.Database.IDatabaseContext.Drop(), Tgstation.Server.Host.Configuration.DatabaseConfiguration.DropDatabase, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Database.DatabaseSeeder.logger, Tgstation.Server.Host.Database.IDatabaseContext.Migrate(), Tgstation.Server.Host.Configuration.DatabaseConfiguration.ResetAdminPassword, Tgstation.Server.Host.Database.DatabaseSeeder.ResetAdminPassword(), Tgstation.Server.Host.Database.DatabaseSeeder.SanitizeDatabase(), and Tgstation.Server.Host.Database.DatabaseSeeder.SeedDatabase().
ResetAdminPassword()
async ValueTask Tgstation.Server.Host.Database.DatabaseSeeder.ResetAdminPassword (IDatabaseContext databaseContext, CancellationToken cancellationToken) private
Changes the admin password in IDatabaseContext back to it's default, enables the account, and gives it AdministrationRights.WriteUsers access.
Parameters
databaseContext The IDatabaseContext to reset the admin password for.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Definition at line 278 of file DatabaseSeeder.cs.
        {
            var admin = await GetAdminUser(databaseContext, cancellationToken);
            if (admin != null)
            {
                admin.Enabled = true;
                // force the user out of any groups
                if (admin.PermissionSet == null)
                {
                    admin.Group = null;
                    admin.GroupId = null;
                    admin.PermissionSet = new PermissionSet
                    {
                        InstanceManagerRights = InstanceManagerRights.None,
                        AdministrationRights = AdministrationRights.WriteUsers,
                    };
                }
                else
                    admin.PermissionSet.AdministrationRights |= AdministrationRights.WriteUsers;
                cryptographySuite.SetUserPassword(admin, DefaultCredentials.DefaultAdminUserPassword, false);
            }
            await databaseContext.Save(cancellationToken);
        }
References Tgstation.Server.Host.Database.DatabaseSeeder.cryptographySuite, Tgstation.Server.Api.DefaultCredentials.DefaultAdminUserPassword, Tgstation.Server.Host.Database.DatabaseSeeder.GetAdminUser(), Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Database.IDatabaseContext.Save(), and Tgstation.Server.Host.Security.ICryptographySuite.SetUserPassword().
Referenced by Tgstation.Server.Host.Database.DatabaseSeeder.Initialize().
SanitizeDatabase()
async ValueTask Tgstation.Server.Host.Database.DatabaseSeeder.SanitizeDatabase (IDatabaseContext databaseContext, CancellationToken cancellationToken) private
Correct invalid database data caused by previous versions (NOT user fuckery).
Parameters
databaseContext The IDatabaseContext to sanitize.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Definition at line 201 of file DatabaseSeeder.cs.
        {
            var admin = await GetAdminUser(databaseContext, cancellationToken);
            if (admin != null)
            {
                if (admin.PermissionSet != null)
                {
                    // Fix the issue with ulong enums
                    // https://github.com/tgstation/tgstation-server/commit/db341d43b3dab74fe3681f5172ca9bfeaafa6b6d#diff-09f06ec4584665cf89bb77b97f5ccfb9R36-R39
                    // https://github.com/JamesNK/Newtonsoft.Json/issues/2301
                    admin.PermissionSet.AdministrationRights &= RightsHelper.AllRights<AdministrationRights>();
                    admin.PermissionSet.InstanceManagerRights &= RightsHelper.AllRights<InstanceManagerRights>();
                }
                if (admin.CreatedBy == null)
                {
                    var tgsUser = await databaseContext
                        .Users
                        .AsQueryable()
                        .Where(x => x.CanonicalName == User.CanonicalizeName(User.TgsSystemUserName))
                        .FirstOrDefaultAsync(cancellationToken);
                    if (tgsUser != null)
                        logger.LogError(
                            "A user named TGS (Canonically) exists but isn't marked as the admin's creator. This may be because it was created manually. This user is going to be adapted to use as the starter of system jobs.");
                    tgsUser = SeedSystemUser(databaseContext, tgsUser);
                    admin.CreatedBy = tgsUser;
                }
            }
            // normalize backslashes to forward slashes
            var allInstances = await databaseContext
                .Instances
                .AsQueryable()
                .Where(instance => instance.SwarmIdentifer == swarmConfiguration.Identifier)
                .ToListAsync(cancellationToken);
            foreach (var instance in allInstances)
                instance.Path = platformIdentifier.NormalizePath(instance.Path!.Replace('\\', '/'));
            if (generalConfiguration.ByondTopicTimeout != 0)
            {
                var ids = await databaseContext
                    .DreamDaemonSettings
                    .AsQueryable()
                    .Where(x => x.TopicRequestTimeout == 0)
                    .Select(x => x.Id)
                    .ToListAsync(cancellationToken);
                var rowsUpdated = ids.Count;
                foreach (var id in ids)
                {
                    var newDDSettings = new DreamDaemonSettings
                    {
                        Id = id,
                    };
                    databaseContext.DreamDaemonSettings.Attach(newDDSettings);
                    newDDSettings.TopicRequestTimeout = generalConfiguration.ByondTopicTimeout;
                }
                if (rowsUpdated > 0)
                    logger.LogInformation(
                        "Updated {count} instances to use database backed BYOND topic timeouts from configuration setting of {timeout}",
                        rowsUpdated,
                        generalConfiguration.ByondTopicTimeout);
            }
            await databaseContext.Save(cancellationToken);
        }
References Tgstation.Server.Host.Configuration.GeneralConfiguration.ByondTopicTimeout, Tgstation.Server.Host.Models.User.CanonicalizeName(), Tgstation.Server.Host.Database.DatabaseSeeder.generalConfiguration, Tgstation.Server.Host.Database.DatabaseSeeder.GetAdminUser(), Tgstation.Server.Api.Models.Internal.SwarmServer.Identifier, Tgstation.Server.Host.Database.IDatabaseContext.Instances, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Database.DatabaseSeeder.logger, Tgstation.Server.Host.System.IPlatformIdentifier.NormalizePath(), Tgstation.Server.Host.Database.DatabaseSeeder.platformIdentifier, Tgstation.Server.Host.Database.DatabaseSeeder.SeedSystemUser(), Tgstation.Server.Host.Database.DatabaseSeeder.swarmConfiguration, Tgstation.Server.Host.Models.User.TgsSystemUserName, and Tgstation.Server.Host.Database.IDatabaseContext.Users.
Referenced by Tgstation.Server.Host.Database.DatabaseSeeder.Initialize().
SeedAdminUser()
User Tgstation.Server.Host.Database.DatabaseSeeder.SeedAdminUser (IDatabaseContext databaseContext) private
Add a default admin User to a given databaseContext .
Parameters
databaseContext The IDatabaseContext to add an admin User to.
Returns
The created admin User.
Definition at line 157 of file DatabaseSeeder.cs.
        {
            var admin = new User
            {
                PermissionSet = new PermissionSet
                {
                    AdministrationRights = RightsHelper.AllRights<AdministrationRights>(),
                    InstanceManagerRights = RightsHelper.AllRights<InstanceManagerRights>(),
                },
                CreatedAt = DateTimeOffset.UtcNow,
                Name = DefaultCredentials.AdminUserName,
                CanonicalName = User.CanonicalizeName(DefaultCredentials.AdminUserName),
                Enabled = true,
            };
            cryptographySuite.SetUserPassword(admin, DefaultCredentials.DefaultAdminUserPassword, true);
            databaseContext.Users.Add(admin);
            return admin;
        }
References Tgstation.Server.Host.Database.IDatabaseCollection< TModel >.Add(), Tgstation.Server.Api.DefaultCredentials.AdminUserName, Tgstation.Server.Host.Models.User.CanonicalizeName(), Tgstation.Server.Host.Database.DatabaseSeeder.cryptographySuite, Tgstation.Server.Api.DefaultCredentials.DefaultAdminUserPassword, Tgstation.Server.Host.Enabled, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Security.ICryptographySuite.SetUserPassword(), and Tgstation.Server.Host.Database.IDatabaseContext.Users.
Referenced by Tgstation.Server.Host.Database.DatabaseSeeder.GetAdminUser(), and Tgstation.Server.Host.Database.DatabaseSeeder.SeedDatabase().
SeedDatabase()
async ValueTask Tgstation.Server.Host.Database.DatabaseSeeder.SeedDatabase (IDatabaseContext databaseContext, CancellationToken cancellationToken) private
Initially seed a given databaseContext .
Parameters
databaseContext The IDatabaseContext to seed.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Definition at line 182 of file DatabaseSeeder.cs.
        {
            var adminUser = SeedAdminUser(databaseContext);
            // Save here because we want admin to have the first DB Id
            // The system user isn't shown in the API except by references in the admin user and jobs
            await databaseContext.Save(cancellationToken);
            var tgsUser = SeedSystemUser(databaseContext);
            adminUser.CreatedBy = tgsUser;
            await databaseContext.Save(cancellationToken);
        }
References Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Database.IDatabaseContext.Save(), Tgstation.Server.Host.Database.DatabaseSeeder.SeedAdminUser(), and Tgstation.Server.Host.Database.DatabaseSeeder.SeedSystemUser().
Referenced by Tgstation.Server.Host.Database.DatabaseSeeder.Initialize().
SeedSystemUser()
static User Tgstation.Server.Host.Database.DatabaseSeeder.SeedSystemUser (IDatabaseContext databaseContext, User? tgsUser = null) static private
Add a default system User to a given databaseContext .
Parameters
databaseContext The IDatabaseContext to add a system User to.
tgsUser An existing User, if any.
Returns
The created system User.
Definition at line 63 of file DatabaseSeeder.cs.
        {
            bool alreadyExists = tgsUser != null;
            tgsUser ??= new User()
            {
                CreatedAt = DateTimeOffset.UtcNow,
                CanonicalName = User.CanonicalizeName(User.TgsSystemUserName),
            };
            // intentionally not giving a group or permissionset
            tgsUser.Name = User.TgsSystemUserName;
            tgsUser.PasswordHash = "_"; // This can't be hashed
            tgsUser.Enabled = false;
            if (!alreadyExists)
                databaseContext.Users.Add(tgsUser);
            return tgsUser;
        }
References Tgstation.Server.Host.Database.IDatabaseCollection< TModel >.Add(), Tgstation.Server.Host.Models.User.CanonicalizeName(), Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Models.User.TgsSystemUserName, and Tgstation.Server.Host.Database.IDatabaseContext.Users.
Referenced by Tgstation.Server.Host.Database.DatabaseSeeder.SanitizeDatabase(), and Tgstation.Server.Host.Database.DatabaseSeeder.SeedDatabase().
Member Data Documentation
cryptographySuite
readonly ICryptographySuite Tgstation.Server.Host.Database.DatabaseSeeder.cryptographySuite private
The ICryptographySuite for the DatabaseSeeder.
Definition at line 25 of file DatabaseSeeder.cs.
Referenced by Tgstation.Server.Host.Database.DatabaseSeeder.DatabaseSeeder(), Tgstation.Server.Host.Database.DatabaseSeeder.ResetAdminPassword(), and Tgstation.Server.Host.Database.DatabaseSeeder.SeedAdminUser().
databaseConfiguration
readonly DatabaseConfiguration Tgstation.Server.Host.Database.DatabaseSeeder.databaseConfiguration private
The DatabaseConfiguration for the DatabaseSeeder.
Definition at line 50 of file DatabaseSeeder.cs.
Referenced by Tgstation.Server.Host.Database.DatabaseSeeder.DatabaseSeeder(), Tgstation.Server.Host.Database.DatabaseSeeder.Downgrade(), and Tgstation.Server.Host.Database.DatabaseSeeder.Initialize().
databaseLogger
readonly ILogger<DatabaseContext> Tgstation.Server.Host.Database.DatabaseSeeder.databaseLogger private
The ILogger used for IDatabaseContexts.
Definition at line 35 of file DatabaseSeeder.cs.
Referenced by Tgstation.Server.Host.Database.DatabaseSeeder.DatabaseSeeder(), Tgstation.Server.Host.Database.DatabaseSeeder.Downgrade(), and Tgstation.Server.Host.Database.DatabaseSeeder.Initialize().
generalConfiguration
readonly GeneralConfiguration Tgstation.Server.Host.Database.DatabaseSeeder.generalConfiguration private
The GeneralConfiguration for the DatabaseSeeder.
Definition at line 45 of file DatabaseSeeder.cs.
Referenced by Tgstation.Server.Host.Database.DatabaseSeeder.DatabaseSeeder(), and Tgstation.Server.Host.Database.DatabaseSeeder.SanitizeDatabase().
logger
readonly ILogger<DatabaseSeeder> Tgstation.Server.Host.Database.DatabaseSeeder.logger private
The ILogger for the DatabaseSeeder.
Definition at line 40 of file DatabaseSeeder.cs.
Referenced by Tgstation.Server.Host.Database.DatabaseSeeder.DatabaseSeeder(), Tgstation.Server.Host.Database.DatabaseSeeder.Initialize(), and Tgstation.Server.Host.Database.DatabaseSeeder.SanitizeDatabase().
platformIdentifier
readonly IPlatformIdentifier Tgstation.Server.Host.Database.DatabaseSeeder.platformIdentifier private
The IPlatformIdentifier for the DatabaseSeeder.
Definition at line 30 of file DatabaseSeeder.cs.
Referenced by Tgstation.Server.Host.Database.DatabaseSeeder.DatabaseSeeder(), and Tgstation.Server.Host.Database.DatabaseSeeder.SanitizeDatabase().
swarmConfiguration
readonly SwarmConfiguration Tgstation.Server.Host.Database.DatabaseSeeder.swarmConfiguration private
The SwarmConfiguration for the DatabaseSeeder.
Definition at line 55 of file DatabaseSeeder.cs.
Referenced by Tgstation.Server.Host.Database.DatabaseSeeder.DatabaseSeeder(), and Tgstation.Server.Host.Database.DatabaseSeeder.SanitizeDatabase().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Database/DatabaseSeeder.cs