tgstation-server: Tgstation.Server.Host.Security.OAuth.TGForumsOAuthValidator Class Reference
Tgstation.Server.Host.Security.OAuth.TGForumsOAuthValidator Class Reference
IOAuthValidator for /tg/ forums.
Public Member Functions
TGForumsOAuthValidator (IHttpClientFactory httpClientFactory, IAssemblyInformationProvider assemblyInformationProvider, ILogger< TGForumsOAuthValidator > logger, OAuthConfiguration oAuthConfiguration)
Initializes a new instance of the TGForumsOAuthValidator class.
override async Task< OAuthProviderInfo > GetProviderInfo (CancellationToken cancellationToken)
Gets the OAuthProvider of validator.
override async Task< string > ValidateResponseCode (string code, CancellationToken cancellationToken)
Validate a given OAuth response code .
Public Member Functions inherited from Tgstation.Server.Host.Security.OAuth.BaseOAuthValidator
BaseOAuthValidator (IHttpClientFactory httpClientFactory, IAssemblyInformationProvider assemblyInformationProvider, ILogger< BaseOAuthValidator > logger, OAuthConfiguration oAuthConfiguration)
Initializes a new instance of the GenericOAuthValidator class.
Properties
override OAuthProvider Provider [get]
Properties inherited from Tgstation.Server.Host.Security.OAuth.BaseOAuthValidator
abstract OAuthProvider Provider [get]
ILogger< BaseOAuthValidator > Logger [get]
The ILogger for the BaseOAuthValidator.
OAuthConfiguration OAuthConfiguration [get]
The OAuthConfiguration for the BaseOAuthValidator.
Properties inherited from Tgstation.Server.Host.Security.OAuth.IOAuthValidator
OAuthProvider Provider [get]
The OAuthProvider this validator is for.
Private Attributes
readonly List< Tuple< TGCreateSessionResponse, DateTimeOffset > > sessions
The active session.
Static Private Attributes
const uint SessionRetentionMinutes = 10
Amount of minutes until unused sessions that were created are forgotten.
Additional Inherited Members
Protected Member Functions inherited from Tgstation.Server.Host.Security.OAuth.BaseOAuthValidator
HttpClient CreateHttpClient ()
Create a new configured HttpClient.
Static Protected Member Functions inherited from Tgstation.Server.Host.Security.OAuth.BaseOAuthValidator
static JsonSerializerSettings SerializerSettings ()
Gets JsonSerializerSettings that should be used.
Detailed Description
IOAuthValidator for /tg/ forums.
Definition at line 20 of file TGForumsOAuthValidator.cs.
Constructor & Destructor Documentation
TGForumsOAuthValidator()
Tgstation.Server.Host.Security.OAuth.TGForumsOAuthValidator.TGForumsOAuthValidator (IHttpClientFactory httpClientFactory, IAssemblyInformationProvider assemblyInformationProvider, ILogger< TGForumsOAuthValidator > logger, OAuthConfiguration oAuthConfiguration)
Initializes a new instance of the TGForumsOAuthValidator class.
Parameters
httpClientFactory The IHttpClientFactory for the BaseOAuthValidator
assemblyInformationProvider The IAssemblyInformationProvider for the BaseOAuthValidator
logger The ILogger for the BaseOAuthValidator
oAuthConfiguration The OAuthConfiguration for the BaseOAuthValidator.
Definition at line 42 of file TGForumsOAuthValidator.cs.
             : base(
                  httpClientFactory,
                  assemblyInformationProvider,
                  logger,
                  oAuthConfiguration)
         {
             sessions = new List<Tuple<TGCreateSessionResponse, DateTimeOffset>>();
         }
References Tgstation.Server.Host.Security.OAuth.TGForumsOAuthValidator.sessions.
Member Function Documentation
GetProviderInfo()
override async Task<OAuthProviderInfo> Tgstation.Server.Host.Security.OAuth.TGForumsOAuthValidator.GetProviderInfo (CancellationToken cancellationToken) virtual
Gets the OAuthProvider of validator.
Implements Tgstation.Server.Host.Security.OAuth.BaseOAuthValidator.
Definition at line 57 of file TGForumsOAuthValidator.cs.
         {
             var expiredSessions = sessions.RemoveAll(x => x.Item2.AddMinutes(SessionRetentionMinutes) < DateTimeOffset.UtcNow);
             if (expiredSessions > 0)
                 Logger.LogTrace("Expired {0} sessions", expiredSessions);
             Logger.LogTrace("Creating new session...");
             try
             {
                 UriBuilder builder = new UriBuilder("https://tgstation13.org/phpBB/oauth_create_session.php")
                 {
                     Query = $"site_private_token={HttpUtility.UrlEncode(Convert.ToBase64String(Encoding.UTF8.GetBytes(OAuthConfiguration.ClientSecret)))}&return_uri={HttpUtility.UrlEncode(OAuthConfiguration.RedirectUrl.ToString())}"
                 };
                 using var request = new HttpRequestMessage(HttpMethod.Get, builder.Uri);
                 using var httpClient = CreateHttpClient();
                 using var response = await httpClient.SendAsync(request, cancellationToken).ConfigureAwait(false);
                 response.EnsureSuccessStatusCode();
                 var json = await response.Content.ReadAsStringAsync().ConfigureAwait(false);
                 var newSession = JsonConvert.DeserializeObject<TGCreateSessionResponse>(json, SerializerSettings());
                 if (newSession.Status != TGBaseResponse.OkStatus)
                 {
                     Logger.LogWarning("Invalid status from /tg/ API! Status: {0}, Error: {1}", newSession.Status, newSession.Error);
                     return null;
                 }
                 sessions.Add(
                     Tuple.Create(
                         newSession,
                         DateTimeOffset.UtcNow));
                 return new OAuthProviderInfo
                 {
                     ClientId = newSession.SessionPublicToken,
                     RedirectUri = OAuthConfiguration.RedirectUrl
                 };
             }
             catch (Exception ex)
             {
                 Logger.LogWarning(ex, "Failed to create TG Forums session!");
                 return null;
             }
         }
References Tgstation.Server.Host.Security.OAuth.BaseOAuthValidator.CreateHttpClient(), Tgstation.Server.Host.Security.OAuth.BaseOAuthValidator.Logger, Tgstation.Server.Host.Security.OAuth.TGBaseResponse.OkStatus, Tgstation.Server.Host.Configuration.OAuthConfiguration.RedirectUrl, Tgstation.Server.Host.Security.OAuth.BaseOAuthValidator.SerializerSettings(), Tgstation.Server.Host.Security.OAuth.TGForumsOAuthValidator.SessionRetentionMinutes, and Tgstation.Server.Host.Security.OAuth.TGForumsOAuthValidator.sessions.
ValidateResponseCode()
override async Task<string> Tgstation.Server.Host.Security.OAuth.TGForumsOAuthValidator.ValidateResponseCode (string code, CancellationToken cancellationToken) virtual
Validate a given OAuth response code .
Implements Tgstation.Server.Host.Security.OAuth.BaseOAuthValidator.
Definition at line 104 of file TGForumsOAuthValidator.cs.
         {
             try
             {
                 var sessionTuple = sessions.FirstOrDefault(x => x.Item1.SessionPublicToken == code);
                 if(sessionTuple == null)
                 {
                     Logger.LogWarning("No known session with this code active!");
                     return null;
                 }
                 Logger.LogTrace("Validating session...");
                 UriBuilder builder = new UriBuilder("https://tgstation13.org/phpBB/oauth_get_session_info.php")
                 {
                     Query = $"site_private_token={HttpUtility.UrlEncode(Convert.ToBase64String(Encoding.UTF8.GetBytes(OAuthConfiguration.ClientSecret)))}&session_private_token={HttpUtility.UrlEncode(sessionTuple.Item1.SessionPrivateToken)}"
                 };
                 using var request = new HttpRequestMessage(HttpMethod.Get, builder.Uri);
                 using var httpClient = CreateHttpClient();
                 using var response = await httpClient.SendAsync(request, cancellationToken).ConfigureAwait(false);
                 response.EnsureSuccessStatusCode();
                 var json = await response.Content.ReadAsStringAsync().ConfigureAwait(false);
                 var sessionInfo = JsonConvert.DeserializeObject<TGGetSessionInfoResponse>(json, SerializerSettings());
                 if (sessionInfo.Status != TGBaseResponse.OkStatus)
                 {
                     Logger.LogWarning("Invalid status from /tg/ API! Status: {0}, Error: {1}", sessionInfo.Status, sessionInfo.Error);
                     return null;
                 }
                 sessions.Remove(sessionTuple);
                 return sessionInfo.PhpbbUsername;
             }
             catch (Exception ex)
             {
                 Logger.LogWarning(ex, "Failed to create TG Forums session!");
                 return null;
             }
         }
References Tgstation.Server.Host.Security.OAuth.BaseOAuthValidator.CreateHttpClient(), Tgstation.Server.Host.Security.OAuth.BaseOAuthValidator.Logger, Tgstation.Server.Host.Security.OAuth.TGBaseResponse.OkStatus, Tgstation.Server.Host.Security.OAuth.BaseOAuthValidator.SerializerSettings(), and Tgstation.Server.Host.Security.OAuth.TGForumsOAuthValidator.sessions.
Member Data Documentation
SessionRetentionMinutes
const uint Tgstation.Server.Host.Security.OAuth.TGForumsOAuthValidator.SessionRetentionMinutes = 10 static private
Amount of minutes until unused sessions that were created are forgotten.
Definition at line 25 of file TGForumsOAuthValidator.cs.
Referenced by Tgstation.Server.Host.Security.OAuth.TGForumsOAuthValidator.GetProviderInfo().
sessions
readonly List<Tuple<TGCreateSessionResponse, DateTimeOffset> > Tgstation.Server.Host.Security.OAuth.TGForumsOAuthValidator.sessions private
The active session.
Definition at line 33 of file TGForumsOAuthValidator.cs.
Referenced by Tgstation.Server.Host.Security.OAuth.TGForumsOAuthValidator.GetProviderInfo(), Tgstation.Server.Host.Security.OAuth.TGForumsOAuthValidator.TGForumsOAuthValidator(), and Tgstation.Server.Host.Security.OAuth.TGForumsOAuthValidator.ValidateResponseCode().
Property Documentation
Provider
override OAuthProvider Tgstation.Server.Host.Security.OAuth.TGForumsOAuthValidator.Provider get
Definition at line 28 of file TGForumsOAuthValidator.cs.
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Security/OAuth/TGForumsOAuthValidator.cs