tgstation-server: Tgstation.Server.Host.Components.Watchdog.Watchdog Class Reference
Tgstation.Server.Host.Components.Watchdog.Watchdog Class Reference
Public Member Functions
Watchdog (IChat chat, ISessionControllerFactory sessionControllerFactory, IDmbFactory dmbFactory, IServerControl serverUpdater, ILogger< Watchdog > logger, IReattachInfoHandler reattachInfoHandler, IDatabaseContextFactory databaseContextFactory, IByondTopicSender byondTopicSender, IEventConsumer eventConsumer, DreamDaemonLaunchParameters initialLaunchParameters, Api.Models.Instance instance, bool autoStart)
Construct a IWatchdog
void Dispose ()
async Task ChangeSettings (DreamDaemonLaunchParameters launchParameters, CancellationToken cancellationToken)
Changes the ActiveLaunchParameters. If currently Running triggers a graceful restart
async Task< WatchdogLaunchResult > Launch (CancellationToken cancellationToken)
Start the IWatchdog
async Task< WatchdogLaunchResult > Restart (bool graceful, CancellationToken cancellationToken)
Restarts the watchdog
async Task Terminate (bool graceful, CancellationToken cancellationToken)
Stops the watchdog
async Task StartAsync (CancellationToken cancellationToken)
async Task StopAsync (CancellationToken cancellationToken)
async Task< bool > HandleEvent (EventType eventType, IEnumerable< string > parameters, CancellationToken cancellationToken)
Handle a given eventType
async Task< string > HandleChatCommand (string commandName, string arguments, Chat.User sender, CancellationToken cancellationToken)
Public Member Functions inherited from Tgstation.Server.Host.Components.Chat.ICustomCommandHandler
Task< string > HandleChatCommand (string commandName, string arguments, User sender, CancellationToken cancellationToken)
Handle a chat command
Public Attributes
Models.CompileJob ActiveCompileJob => (AlphaIsActive ? alphaServer : bravoServer)?.Dmb.CompileJob
RebootState RebootState => Running ? (AlphaIsActive ? alphaServer?.RebootState : bravoServer?.RebootState) : null
Properties
bool Running [get, private set]
bool AlphaIsActive [get, private set]
LaunchResult LastLaunchResult [get, private set]
DreamDaemonLaunchParameters ActiveLaunchParameters [get, private set]
DreamDaemonLaunchParameters LastLaunchParameters [get, private set]
Properties inherited from Tgstation.Server.Host.Components.Watchdog.IWatchdog
bool Running [get]
If the watchdog is running
bool AlphaIsActive [get]
If the alpha server is the active server
Models.CompileJob ActiveCompileJob [get]
The CompileJob currently running on the server
LaunchResult LastLaunchResult [get]
The latest LaunchResult of the twin servers
DreamDaemonLaunchParameters ActiveLaunchParameters [get]
The DreamDaemonLaunchParameters the active server is using
DreamDaemonLaunchParameters LastLaunchParameters [get]
The DreamDaemonLaunchParameters to be applied
RebootState RebootState [get]
The Components.Watchdog.RebootState of the active server
Private Member Functions
void DisposeAndNullControllers ()
Call IDisposable.Dispose on alphaServer and bravoServer and set them to
async Task TerminateNoLock (bool graceful, bool announce, CancellationToken cancellationToken)
Implementation of Terminate(bool, CancellationToken). Does not lock semaphore
async Task HandlerMonitorWakeup (MonitorActivationReason activationReason, MonitorState monitorState, CancellationToken cancellationToken)
Handles the actions to take when the monitor has to "wake up"
async Task MonitorLifetimes (CancellationToken cancellationToken)
The loop that watches the watchdog
async Task< bool > StopMonitor ()
async Task< WatchdogLaunchResult > LaunchNoLock (bool startMonitor, bool announce, bool doReattach, CancellationToken cancellationToken)
Private Attributes
const int AlphaBravoStartupSeperationInterval = 10
The time in seconds to wait from starting alphaServer to start bravoServer. Does not take responsiveness into account
readonly IChat chat
The IChat for the Watchdog
readonly ISessionControllerFactory sessionControllerFactory
The ISessionControllerFactory for the Watchdog
readonly IDmbFactory dmbFactory
The IDmbFactory for the Watchdog
readonly ILogger< Watchdog > logger
The ILogger<TCategoryName> for the Watchdog
readonly IReattachInfoHandler reattachInfoHandler
The IReattachInfoHandler for the Watchdog
readonly IDatabaseContextFactory databaseContextFactory
The IDatabaseContextFactory for the Watchdog
readonly IByondTopicSender byondTopicSender
The IByondTopicSender for the Watchdog
readonly IEventConsumer eventConsumer
The IEventConsumer for the Watchdog
readonly SemaphoreSlim semaphore
The SemaphoreSlim for the Watchdog
readonly Api.Models.Instance instance
The Api.Models.Instance for the Watchdog
readonly bool autoStart
If the Watchdog should LaunchNoLock(bool, bool, bool, CancellationToken) in StartAsync(CancellationToken)
CancellationTokenSource monitorCts
The CancellationTokenSource for the monitor loop
Task monitorTask
The Task running the monitor loop
TaskCompletionSource< object > activeParametersUpdated
TaskCompletionSource<TResult> that completes when ActiveLaunchParameters are changed and we are Running
ISessionController alphaServer
Server designation alpha
ISessionController bravoServer
Server designation bravo
bool releaseServers
If the servers should be released instead of shutdown
Detailed Description
Definition at line 21 of file Watchdog.cs.
Constructor & Destructor Documentation
Tgstation.Server.Host.Components.Watchdog.Watchdog.Watchdog (IChat chat, ISessionControllerFactory sessionControllerFactory, IDmbFactory dmbFactory, IServerControl serverUpdater, ILogger< Watchdog > logger, IReattachInfoHandler reattachInfoHandler, IDatabaseContextFactory databaseContextFactory, IByondTopicSender byondTopicSender, IEventConsumer eventConsumer, DreamDaemonLaunchParameters initialLaunchParameters, Api.Models.Instance instance, bool autoStart)
Construct a IWatchdog
Parameters
chat The value of chat
sessionControllerFactory The value of sessionControllerFactory
dmbFactory The value of dmbFactory
serverUpdater The IServerControl for the Watchdog
logger The value of logger
reattachInfoHandler The value of reattachInfoHandler
databaseContextFactory The value of databaseContextFactory
byondTopicSender The value of byondTopicSender
initialLaunchParameters The initial value of ActiveLaunchParameters
instance The value of instance
autoStart The value of autoStart
eventConsumer The value of eventConsumer
Definition at line 148 of file Watchdog.cs.
References Tgstation.Server.Host.Components.Chat.IChat.RegisterCommandHandler(), and Tgstation.Server.Host.Core.IServerControl.RegisterForRestart().
         {
             this.chat = chat ?? throw new ArgumentNullException(nameof(chat));
             this.sessionControllerFactory = sessionControllerFactory ?? throw new ArgumentNullException(nameof(sessionControllerFactory));
             this.dmbFactory = dmbFactory ?? throw new ArgumentNullException(nameof(dmbFactory));
             this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
             this.reattachInfoHandler = reattachInfoHandler ?? throw new ArgumentNullException(nameof(reattachInfoHandler));
             this.databaseContextFactory = databaseContextFactory ?? throw new ArgumentNullException(nameof(databaseContextFactory));
             this.byondTopicSender = byondTopicSender ?? throw new ArgumentNullException(nameof(byondTopicSender));
             this.eventConsumer = eventConsumer ?? throw new ArgumentNullException(nameof(eventConsumer));
             this.instance = instance ?? throw new ArgumentNullException(nameof(instance));
             this.autoStart = autoStart;
             if (serverUpdater == null)
                 throw new ArgumentNullException(nameof(serverUpdater));
             serverUpdater.RegisterForRestart(() => releaseServers = true);
             chat.RegisterCommandHandler(this);
             AlphaIsActive = true;
             ActiveLaunchParameters = initialLaunchParameters;
             releaseServers = false;
             semaphore = new SemaphoreSlim(1);
             activeParametersUpdated = new TaskCompletionSource<object>();
         }
Member Function Documentation
async Task Tgstation.Server.Host.Components.Watchdog.Watchdog.ChangeSettings (DreamDaemonLaunchParameters launchParameters, CancellationToken cancellationToken)
Changes the ActiveLaunchParameters. If currently Running triggers a graceful restart
Implements Tgstation.Server.Host.Components.Watchdog.IWatchdog.
Definition at line 606 of file Watchdog.cs.
References Tgstation.Server.Host.Core.SemaphoreSlimContext.Lock().
         {
             using (await SemaphoreSlimContext.Lock(semaphore, cancellationToken).ConfigureAwait(false))
             {
                 ActiveLaunchParameters = launchParameters;
                 if (Running)
                     //queue an update
                     activeParametersUpdated.TrySetResult(null);
             }
         }
void Tgstation.Server.Host.Components.Watchdog.Watchdog.Dispose ()
Definition at line 176 of file Watchdog.cs.
Referenced by Tgstation.Server.Host.Components.Instance.Dispose().
         {
             DisposeAndNullControllers();
             semaphore.Dispose();
         }
void Tgstation.Server.Host.Components.Watchdog.Watchdog.DisposeAndNullControllers () private
Call IDisposable.Dispose on alphaServer and bravoServer and set them to
Definition at line 185 of file Watchdog.cs.
         {
             alphaServer?.Dispose();
             alphaServer = null;
             bravoServer?.Dispose();
             bravoServer = null;
             Running = false;
         }
async Task<string> Tgstation.Server.Host.Components.Watchdog.Watchdog.HandleChatCommand (string commandName, string arguments, Chat.User sender, CancellationToken cancellationToken)
Definition at line 855 of file Watchdog.cs.
References Tgstation.Server.Host.Components.Interop.Constants.DMParameterData, Tgstation.Server.Host.Components.Interop.Constants.DMTopicChatCommand, Tgstation.Server.Host.Core.SemaphoreSlimContext.Lock(), and Tgstation.Server.Host.Components.Watchdog.ISessionController.SendCommand().
         {
             using (await SemaphoreSlimContext.Lock(semaphore, cancellationToken).ConfigureAwait(false))
             {
                 if (!Running)
                     return "ERROR: Server offline!";
                 var commandObject = new ChatCommand
                 {
                     Command = commandName,
                     Parameters = arguments,
                     User = sender
                 };
                 var json = JsonConvert.SerializeObject(arguments, new JsonSerializerSettings
                 {
                     ContractResolver = new CamelCasePropertyNamesContractResolver()
                 });
                 var command = String.Format(CultureInfo.InvariantCulture, "{0}&{1}={2}", byondTopicSender.SanitizeString(Constants.DMTopicChatCommand), byondTopicSender.SanitizeString(Constants.DMParameterData), byondTopicSender.SanitizeString(json));
                 var activeServer = AlphaIsActive ? alphaServer : bravoServer;
                 return await activeServer.SendCommand(command, cancellationToken).ConfigureAwait(false) ?? "ERROR: Bad topic exchange!";
             }
         }
async Task<bool> Tgstation.Server.Host.Components.Watchdog.Watchdog.HandleEvent (EventType eventType, IEnumerable< string > parameters, CancellationToken cancellationToken)
Handle a given eventType
Implements Tgstation.Server.Host.Components.IEventConsumer.
Definition at line 813 of file Watchdog.cs.
References Tgstation.Server.Host.Components.Interop.Constants.DMResponseSuccess, Tgstation.Server.Host.Components.Interop.Constants.DMTopicEvent, Tgstation.Server.Host.Core.SemaphoreSlimContext.Lock(), and Tgstation.Server.Host.Components.Watchdog.ISessionController.SendCommand().
         {
             string results;
             using (await SemaphoreSlimContext.Lock(semaphore, cancellationToken).ConfigureAwait(false))
             {
                 if (!Running)
                     return true;
                 var builder = new StringBuilder(Constants.DMTopicEvent);
                 builder.Append("&");
                 var notification = new EventNotification
                 {
                     Type = eventType,
                     Parameters = parameters
                 };
                 var json = JsonConvert.SerializeObject(notification);
                 builder.Append(byondTopicSender.SanitizeString(json));
                 var activeServer = AlphaIsActive ? alphaServer : bravoServer;
                 results = await activeServer.SendCommand(builder.ToString(), cancellationToken).ConfigureAwait(false);
             }
             if (results == Constants.DMResponseSuccess)
                 return true;
             List<Response> responses;
             try
             {
                 responses = JsonConvert.DeserializeObject<List<Response>>(results);
             }
             catch
             {
                 logger.LogInformation("Recieved invalid response from DD when parsing event {0}:{1}{2}", eventType, Environment.NewLine, results);
                 return true;
             }
             await Task.WhenAll(responses.Select(x => chat.SendMessage(x.Message, x.ChannelIds, cancellationToken))).ConfigureAwait(false);
             return true;
         }
async Task Tgstation.Server.Host.Components.Watchdog.Watchdog.HandlerMonitorWakeup (MonitorActivationReason activationReason, MonitorState monitorState, CancellationToken cancellationToken) private
Handles the actions to take when the monitor has to "wake up"
Parameters
activationReason The MonitorActivationReason that caused the invocation
monitorState The current MonitorState. Will be modified upon retrn
cancellationToken The CancellationToken for the operation
Returns
A Task representing the running operation
Definition at line 225 of file Watchdog.cs.
References Tgstation.Server.Host.Components.Watchdog.MonitorState.ActiveServer, Tgstation.Server.Host.Components.Watchdog.ISessionController.ClosePortOnReboot, Tgstation.Server.Host.Components.IDmbProvider.CompileJob, Tgstation.Server.Host.Components.Watchdog.ISessionController.Dmb, Tgstation.Server.Api.Models.Internal.CompileJob.Id, Tgstation.Server.Host.Components.Watchdog.MonitorState.InactiveServer, Tgstation.Server.Host.Components.Watchdog.MonitorState.InactiveServerCritFail, Tgstation.Server.Host.Components.Watchdog.MonitorState.InactiveServerHasStagedDmb, Tgstation.Server.Host.Components.Watchdog.ISessionController.IsPrimary, Tgstation.Server.Host.Components.Watchdog.MonitorState.NextAction, Tgstation.Server.Host.Components.Watchdog.MonitorState.RebootingInactiveServer, Tgstation.Server.Host.Components.Watchdog.ISessionController.RebootState, Tgstation.Server.Host.Components.Watchdog.ISessionController.ResetRebootState(), Tgstation.Server.Host.Components.Watchdog.ISessionController.SetPort(), and Tgstation.Server.Host.Components.Watchdog.ISessionController.TerminationWasRequested.
         {
             logger.LogDebug("Monitor activation. Reason: {0}", activationReason);
             //returns true if the inactive server can't be used immediately
             bool FullRestartDeadInactive()
             {
                 if (monitorState.RebootingInactiveServer || monitorState.InactiveServerCritFail)
                 {
                     logger.LogInformation("Inactive server is {0}! Restarting monitor...", monitorState.InactiveServerCritFail ? "critically failed" : "still rebooting");
                     monitorState.NextAction = MonitorAction.Restart;    //will dispose server
                     return true;
                 }
                 return false;
             };
             //trys to set inactive server's port to the public port
             //doesn't handle closing active server's port
             async Task<bool> MakeInactiveActive()
             {
                 logger.LogDebug("Setting inactive server to port {0}...", ActiveLaunchParameters.PrimaryPort.Value);
                 var result = await monitorState.InactiveServer.SetPort(ActiveLaunchParameters.PrimaryPort.Value, cancellationToken).ConfigureAwait(false);
                 if (!result)
                 {
                     logger.LogWarning("Failed to activate inactive server! Restarting monitor...");
                     monitorState.NextAction = MonitorAction.Restart;    //will dispose server
                     return false;
                 }
                 //inactive server should always be using active launch parameters
                 LastLaunchParameters = ActiveLaunchParameters;
                 var tmp = monitorState.ActiveServer;
                 monitorState.ActiveServer = monitorState.InactiveServer;
                 monitorState.InactiveServer = tmp;
                 AlphaIsActive = !AlphaIsActive;
                 return true;
             }
             // Tries to load inactive server with latest dmb, falling back to current dmb on failure. Requires a lock on <see cref="semaphore"/>
             async Task<bool> RestartInactiveServer()
             {
                 logger.LogInformation("Rebooting inactive server...");
                 var newDmb = dmbFactory.LockNextDmb(1);
                 bool usedMostRecentDmb;
                 try
                 {
                     monitorState.InactiveServer = await sessionControllerFactory.LaunchNew(ActiveLaunchParameters, newDmb, null, false, !monitorState.ActiveServer.IsPrimary, false, cancellationToken).ConfigureAwait(false);
                     usedMostRecentDmb = true;
                 }
                 catch (OperationCanceledException)
                 {
                     throw;
                 }
                 catch (Exception e)
                 {
                     logger.LogError("Error occurred while recreating server! Attempting backup strategy of running DMB of running server! Exception: {0}", e.ToString());
                     //ahh jeez, what do we do here?
                     //this is our fault, so it should never happen but
                     //idk maybe a database error while handling the newest dmb?
                     //either way try to start it using the active server's dmb as a backup
                     try
                     {
                         var dmbBackup = await dmbFactory.FromCompileJob(monitorState.ActiveServer.Dmb.CompileJob, cancellationToken).ConfigureAwait(false);
                         if (dmbBackup == null)  //NANI!?
                             //just give up, if THAT compile job is failing then the ActiveServer is gonna crash soon too or already has
                             throw new JobException("Creating backup DMB provider failed!");
                         monitorState.InactiveServer = await sessionControllerFactory.LaunchNew(ActiveLaunchParameters, dmbBackup, null, false, !monitorState.ActiveServer.IsPrimary, false, cancellationToken).ConfigureAwait(false);
                         usedMostRecentDmb = false;
                         await chat.SendWatchdogMessage("Staging newest DMB on inactive server failed: {0} Falling back to previous dmb...", cancellationToken).ConfigureAwait(false);
                     }
                     catch (OperationCanceledException)
                     {
                         throw;
                     }
                     catch (Exception e2)
                     {
                         //fuuuuucckkk
                         logger.LogError("Backup strategy failed! Monitor will restart when active server reboots! Exception: {0}", e2.ToString());
                         monitorState.InactiveServerCritFail = true;
                         await chat.SendWatchdogMessage("Attempted reboot of inactive server failed. Watchdog will reset when active server fails or exits", cancellationToken).ConfigureAwait(false);
                         return true;    //we didn't use the old dmb
                     }
                 }
                 logger.LogInformation("Successfully relaunched inactive server!");
                 monitorState.RebootingInactiveServer = true;
                 return usedMostRecentDmb;
             }
             async Task UpdateAndRestartInactiveServer(bool breakAfter)
             {
                 //replace the notification tcs here so that the next loop will read a fresh one
                 activeParametersUpdated = new TaskCompletionSource<object>();
                 monitorState.InactiveServer.Dispose();  //kill or recycle it
                 monitorState.NextAction = breakAfter ? MonitorAction.Break : MonitorAction.Continue;
                 var usedLatestDmb = await RestartInactiveServer().ConfigureAwait(false);
                 if (monitorState.NextAction == (breakAfter ? MonitorAction.Break : MonitorAction.Continue))
                 {
                     monitorState.ActiveServer.ClosePortOnReboot = false;
                     if (monitorState.InactiveServerHasStagedDmb && !usedLatestDmb)
                         monitorState.InactiveServerHasStagedDmb = false;    //don't try to load it again though
                 }
             };
             string ExitWord(ISessionController controller) => controller.TerminationWasRequested ? "exited" : "crashed";
             //reason handling
             switch (activationReason)
             {
                 case MonitorActivationReason.ActiveServerCrashed:
                     if(monitorState.ActiveServer.RebootState == Components.Watchdog.RebootState.Shutdown)
                     {
                         await chat.SendWatchdogMessage(String.Format(CultureInfo.InvariantCulture, "Active server {0}! Exiting due to graceful termination request...", ExitWord(monitorState.ActiveServer)), cancellationToken).ConfigureAwait(false);
                         monitorState.NextAction = MonitorAction.Exit;
                         break;
                     }
                     if (FullRestartDeadInactive())
                     {
                         await chat.SendWatchdogMessage(String.Format(CultureInfo.InvariantCulture, "Active server {0}! Inactive server unable to online!", ExitWord(monitorState.ActiveServer)), cancellationToken).ConfigureAwait(false);
                         break;
                     }
                     await chat.SendWatchdogMessage(String.Format(CultureInfo.InvariantCulture, "Active server {0}! Onlining inactive server...", ExitWord(monitorState.ActiveServer)), cancellationToken).ConfigureAwait(false);
                     if (!await MakeInactiveActive().ConfigureAwait(false))
                         break;
                     await UpdateAndRestartInactiveServer(true).ConfigureAwait(false);
                     break;
                 case MonitorActivationReason.InactiveServerCrashed:
                     await chat.SendWatchdogMessage(String.Format(CultureInfo.InvariantCulture, "Inactive server {0}! Rebooting...", ExitWord(monitorState.InactiveServer)), cancellationToken).ConfigureAwait(false);
                     await UpdateAndRestartInactiveServer(false).ConfigureAwait(false);
                     break;
                 case MonitorActivationReason.ActiveServerRebooted:
                     if (FullRestartDeadInactive())
                         break;
                     //what matters here is the RebootState
                     bool restartOnceSwapped = false;
                     var rebootState = monitorState.ActiveServer.RebootState;
                     monitorState.ActiveServer.ResetRebootState();   //the DMAPI has already done this internally
                     switch (rebootState)
                     {
                         case Components.Watchdog.RebootState.Normal:
                             break;
                         case Components.Watchdog.RebootState.Restart:
                             restartOnceSwapped = true;
                             break;
                         case Components.Watchdog.RebootState.Shutdown:
                             await chat.SendWatchdogMessage("Active server rebooted! Exiting due to graceful termination request...", cancellationToken).ConfigureAwait(false);
                             DisposeAndNullControllers();
                             monitorState.NextAction = MonitorAction.Exit;
                             return;
                     }
                     var sameCompileJob = monitorState.InactiveServer.Dmb.CompileJob.Id == monitorState.ActiveServer.Dmb.CompileJob.Id;
                     if (sameCompileJob && monitorState.InactiveServerHasStagedDmb)
                         //both servers up to date
                         monitorState.InactiveServerHasStagedDmb = false;
                     if (!sameCompileJob || ActiveLaunchParameters != LastLaunchParameters)
                         //need a new launch in ActiveServer
                         restartOnceSwapped = true;
                     if (restartOnceSwapped && !monitorState.ActiveServer.ClosePortOnReboot)
                         //we need to manually restart active server
                         //it won't listen to us right now so just kill it
                         monitorState.ActiveServer.Dispose();
                     if ((!restartOnceSwapped && !monitorState.ActiveServer.ClosePortOnReboot) || !await MakeInactiveActive().ConfigureAwait(false))
                         break;
                     monitorState.ActiveServer.ClosePortOnReboot = true;
                     if (!restartOnceSwapped)
                     {
                         monitorState.InactiveServer.ClosePortOnReboot = false;
                         //try to reopen inactive server on the private port so it's not pinging all the time
                         //failing that, just reboot it
                         restartOnceSwapped = !await monitorState.InactiveServer.SetPort(ActiveLaunchParameters.SecondaryPort.Value, cancellationToken).ConfigureAwait(false);
                     }
                     if (restartOnceSwapped) //for one reason or another
                         await UpdateAndRestartInactiveServer(true).ConfigureAwait(false);   //break because worse case, active server is still booting
                     else
                     {
                         monitorState.InactiveServer.ClosePortOnReboot = false;
                         monitorState.NextAction = MonitorAction.Break;
                     }
                     break;
                 case MonitorActivationReason.InactiveServerRebooted:
                     monitorState.RebootingInactiveServer = true;
                     monitorState.InactiveServer.ResetRebootState();
                     monitorState.ActiveServer.ClosePortOnReboot = false;
                     monitorState.NextAction = MonitorAction.Continue;
                     break;
                 case MonitorActivationReason.InactiveServerStartupComplete:
                     //eziest case of my life
                     monitorState.RebootingInactiveServer = false;
                     monitorState.ActiveServer.ClosePortOnReboot = true;
                     monitorState.NextAction = MonitorAction.Continue;
                     break;
                 case MonitorActivationReason.NewDmbAvailable:
                     monitorState.InactiveServerHasStagedDmb = true;
                     await UpdateAndRestartInactiveServer(true).ConfigureAwait(false);   //next case does same thing
                     break;
                 case MonitorActivationReason.ActiveLaunchParametersUpdated:
                     await UpdateAndRestartInactiveServer(false).ConfigureAwait(false);
                     break;
             }
         }
async Task<WatchdogLaunchResult> Tgstation.Server.Host.Components.Watchdog.Watchdog.Launch (CancellationToken cancellationToken)
Start the IWatchdog
Implements Tgstation.Server.Host.Components.Watchdog.IWatchdog.
Definition at line 745 of file Watchdog.cs.
References Tgstation.Server.Host.Core.SemaphoreSlimContext.Lock().
         {
             using (await SemaphoreSlimContext.Lock(semaphore, cancellationToken).ConfigureAwait(false))
                 return await LaunchNoLock(true, true, false, cancellationToken).ConfigureAwait(false);
         }
async Task<WatchdogLaunchResult> Tgstation.Server.Host.Components.Watchdog.Watchdog.LaunchNoLock (bool startMonitor, bool announce, bool doReattach, CancellationToken cancellationToken) private
Definition at line 617 of file Watchdog.cs.
References Tgstation.Server.Host.Components.Watchdog.ISessionController.LaunchResult, and Tgstation.Server.Host.Core.IProcessBase.SetHighPriority().
         {
             logger.LogTrace("Begin LaunchNoLock");
             using (var alphaStartCts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken))
             {
                 if (Running)
                 {
                     logger.LogTrace("Aborted due to already running!");
                     return null;
                 }
                 Task chatTask;
                 //this is necessary, the monitor could be in it's sleep loop trying to restart
                 if (startMonitor && await StopMonitor().ConfigureAwait(false))
                     chatTask = chat.SendWatchdogMessage("Automatic retry sequence cancelled by manual launch. Restarting...", cancellationToken);
                 else if (announce)
                     chatTask = chat.SendWatchdogMessage("Starting...", cancellationToken);
                 else
                     chatTask = Task.CompletedTask;
                 //start both servers
                 LastLaunchParameters = ActiveLaunchParameters;
                 try
                 {
                     //good ole sanity
                     if (alphaServer != null || bravoServer != null)
                         throw new InvalidOperationException("Entered LaunchNoLock with one or more of the servers not being null!");
                     var reattachInfo = doReattach ? await reattachInfoHandler.Load(cancellationToken).ConfigureAwait(false) : null;
                     var doesntNeedNewDmb = doReattach && reattachInfo.Alpha != null && reattachInfo.Bravo != null;
                     var dmbToUse = doesntNeedNewDmb ? null : dmbFactory.LockNextDmb(2);
                     try
                     {
                         Task<ISessionController> alphaServerTask;
                         if (!doesntNeedNewDmb)
                             alphaServerTask = sessionControllerFactory.LaunchNew(ActiveLaunchParameters, dmbToUse, null, true, true, false, alphaStartCts.Token);
                         else
                             alphaServerTask = sessionControllerFactory.Reattach(reattachInfo.Alpha, cancellationToken);
                         //wait until this boy officially starts so as not to confuse the servers as to who came first
                         var startTime = DateTimeOffset.Now;
                         alphaServer = await alphaServerTask.ConfigureAwait(false);
                         alphaServer.SetHighPriority();
                         //extra delay for total ordering
                         var now = DateTimeOffset.Now;
                         var delay = now - startTime;
                         if (delay.TotalSeconds < AlphaBravoStartupSeperationInterval)
                             await Task.Delay(startTime.AddSeconds(AlphaBravoStartupSeperationInterval) - now, cancellationToken).ConfigureAwait(false);
                         Task<ISessionController> bravoServerTask;
                         if (!doesntNeedNewDmb)
                             bravoServerTask = sessionControllerFactory.LaunchNew(ActiveLaunchParameters, dmbToUse, null, false, false, false, cancellationToken);
                         else
                             bravoServerTask = sessionControllerFactory.Reattach(reattachInfo.Bravo, cancellationToken);
                         bravoServer = await bravoServerTask.ConfigureAwait(false);
                         bravoServer.SetHighPriority();
                         async Task<LaunchResult> CheckLaunch(ISessionController controller, string serverName)
{
                             var launch = await controller.LaunchResult.ConfigureAwait(false);
                             if (launch.ExitCode.HasValue)
                                 //you killed us ray...
                                 throw new JobException(String.Format(CultureInfo.InvariantCulture, "{1} server failed to start: {0}", launch.ToString(), serverName));
                             if (!launch.StartupTime.HasValue)
                                 throw new JobException(String.Format(CultureInfo.InvariantCulture, "{1} server timed out on startup: {0}s", launch.ToString(), ActiveLaunchParameters.StartupTimeout.Value));
                             return launch;
                         }
                         var alphaLrt = CheckLaunch(alphaServer, "Alpha");
                         var bravoLrt = CheckLaunch(bravoServer, "Bravo");
                         //now we have two booting servers, get them up and running
                         var allTask = Task.WhenAll(alphaLrt, bravoLrt);
                         //don't forget about the cancelationToken
                         var cancelTcs = new TaskCompletionSource<object>();
                         using (cancellationToken.Register(() => cancelTcs.SetCanceled()))
                             await Task.WhenAny(allTask, cancelTcs.Task).ConfigureAwait(false);
                         cancellationToken.ThrowIfCancellationRequested();
                         //both servers are now running, alpha is the active server, huzzah
                         AlphaIsActive = doReattach ? reattachInfo.AlphaIsActive : true;
                         LastLaunchResult = alphaLrt.Result;
                         logger.LogInformation("Launched servers successfully");
                         Running = true;
                         if (startMonitor)
{
                             await StopMonitor().ConfigureAwait(false);
                             monitorCts = new CancellationTokenSource();
                             monitorTask = MonitorLifetimes(monitorCts.Token);
                         }
                         return new WatchdogLaunchResult
{
                             Alpha = alphaLrt.Result,
                             Bravo = bravoLrt.Result
                         };
                     }
                     catch
                     {
                         if (!doesntNeedNewDmb && (alphaServer == null && bravoServer == null))
{
                             dmbToUse.Dispose(); //guaranteed to not be null here
                             dmbToUse.Dispose(); //yes, dispose it twice. See the definition of IDmbFactory.LockNextDmb(), we called it with 2 locks
                         }
                         DisposeAndNullControllers();
                         throw;
                     }
                 }
                 catch (Exception e)
                 {
                     logger.LogWarning("Failed to start watchdog: {0}", e.ToString());
                     throw;
                 }
                 finally
                 {
                     try
                     {
                         await chatTask.ConfigureAwait(false);
                     }
                     catch (OperationCanceledException) { }
                 }
             }
         }
async Task Tgstation.Server.Host.Components.Watchdog.Watchdog.MonitorLifetimes (CancellationToken cancellationToken) private
The loop that watches the watchdog
Parameters
cancellationToken The CancellationToken for the operation
Returns
A Task representing the running operation
Definition at line 448 of file Watchdog.cs.
References Tgstation.Server.Host.Components.Watchdog.WatchdogLaunchResult.Alpha, Tgstation.Server.Host.Components.Watchdog.WatchdogLaunchResult.Bravo, Tgstation.Server.Host.Core.IProcessBase.Lifetime, Tgstation.Server.Host.Core.SemaphoreSlimContext.Lock(), Tgstation.Server.Host.Components.Watchdog.MonitorState.NextAction, and Tgstation.Server.Host.Components.Watchdog.LaunchResult.ToString().
         {
             logger.LogTrace("Entered MonitorLifetimes");
             var iteration = 1;
             for(var monitorState = new MonitorState(); monitorState.NextAction != MonitorAction.Exit; ++iteration)
             {
                 monitorState.NextAction = MonitorAction.Continue;
                 logger.LogDebug("Iteration {0} of monitor loop", iteration);
                 try
                 {
                     if(AlphaIsActive)
                         logger.LogDebug("Alpha is the active server");
                     else
                         logger.LogDebug("Bravo is the active server");
                     if(monitorState.InactiveServerHasStagedDmb)
                         logger.LogDebug("Inactive server has staged .dmb");
                     if (monitorState.RebootingInactiveServer)
                         logger.LogDebug("Inactive server is rebooting");
                     monitorState.ActiveServer = AlphaIsActive ? alphaServer : bravoServer;
                     monitorState.InactiveServer = AlphaIsActive ? bravoServer : alphaServer;
                     if (monitorState.ActiveServer.ClosePortOnReboot)
                         logger.LogDebug("Active server will close port on reboot");
                     if (monitorState.InactiveServer.ClosePortOnReboot)
                         logger.LogDebug("Inactive server will close port on reboot");
                     var activeServerLifetime = monitorState.ActiveServer.Lifetime;
                     var inactiveServerLifetime = monitorState.InactiveServer.Lifetime;
                     var activeServerReboot = monitorState.ActiveServer.OnReboot;
                     var inactiveServerReboot = monitorState.InactiveServer.OnReboot;
                     var inactiveServerStartup = monitorState.RebootingInactiveServer ? monitorState.InactiveServer.LaunchResult : null;
                     var activeLaunchParametersChanged = activeParametersUpdated.Task;
                     var newDmbAvailable = dmbFactory.OnNewerDmb;
                     var cancelTcs = new TaskCompletionSource<object>();
                     using (cancellationToken.Register(() => cancelTcs.SetCanceled()))
                     {
                         var toWaitOn = Task.WhenAny(activeServerLifetime, inactiveServerLifetime, activeServerReboot, inactiveServerReboot, newDmbAvailable, cancelTcs.Task, activeLaunchParametersChanged);
                         if (monitorState.RebootingInactiveServer)
                             toWaitOn = Task.WhenAny(toWaitOn, inactiveServerStartup);
                         await toWaitOn.ConfigureAwait(false);
                         cancellationToken.ThrowIfCancellationRequested();
                     }
                     var chatTask = Task.CompletedTask;
                     using (await SemaphoreSlimContext.Lock(semaphore, cancellationToken).ConfigureAwait(false))
                     {
                         MonitorActivationReason activationReason = default;
                         //multiple things may have happened, handle them one at a time
                         for (var moreActivationsToProcess = true; moreActivationsToProcess && monitorState.NextAction == MonitorAction.Continue; )
{
                             if (activeServerLifetime?.IsCompleted == true)
{
                                 activationReason = MonitorActivationReason.ActiveServerCrashed;
                                 activeServerLifetime = null;
                             }
                             else if (inactiveServerLifetime?.IsCompleted == true)
{
                                 activationReason = MonitorActivationReason.InactiveServerCrashed;
                                 inactiveServerLifetime = null;
                             }
                             else if (activeServerReboot?.IsCompleted == true)
{
                                 activationReason = MonitorActivationReason.ActiveServerRebooted;
                                 activeServerReboot = null;
                             }
                             else if (inactiveServerReboot?.IsCompleted == true)
{
                                 activationReason = MonitorActivationReason.InactiveServerRebooted;
                                 inactiveServerReboot = null;
                             }
                             else if (inactiveServerStartup?.IsCompleted == true)
{
                                 activationReason = MonitorActivationReason.InactiveServerStartupComplete;
                                 inactiveServerStartup = null;
                             }
                             else if (newDmbAvailable?.IsCompleted == true)
{
                                 activationReason = MonitorActivationReason.NewDmbAvailable;
                                 newDmbAvailable = null;
                             }
                             else if(activeLaunchParametersChanged?.IsCompleted == true)
{
                                 activationReason = MonitorActivationReason.ActiveLaunchParametersUpdated;
                                 activeLaunchParametersChanged = null;
                             }
                             else
                                 moreActivationsToProcess = false;
                             if(moreActivationsToProcess)
                                 await HandlerMonitorWakeup(activationReason, monitorState, cancellationToken).ConfigureAwait(false);
                         }
                         //writeback alphaServer and bravoServer
                         alphaServer = AlphaIsActive ? monitorState.ActiveServer : monitorState.InactiveServer;
                         bravoServer = !AlphaIsActive ? monitorState.ActiveServer : monitorState.InactiveServer;
                     }
                     //full reboot required
                     if (monitorState.NextAction == MonitorAction.Restart)
                     {
                         logger.LogDebug("Next state action is to restart");
                         DisposeAndNullControllers();
                         chatTask = chat.SendWatchdogMessage("Restarting entirely due to complications...", cancellationToken);
                         for (var retryAttempts = 1; monitorState.NextAction == MonitorAction.Restart; ++retryAttempts)
{
                             WatchdogLaunchResult result;
                             using (await SemaphoreSlimContext.Lock(semaphore, cancellationToken).ConfigureAwait(false))
{
                                 result = await LaunchNoLock(false, false, false, cancellationToken).ConfigureAwait(false);
                                 if (Running)
{
                                     logger.LogDebug("Relaunch successful, resetting monitor state...");
                                     monitorState = new MonitorState();  //clean the slate
                                 }
                             }
                             await chatTask.ConfigureAwait(false);
                             if (!Running)
{
                                 logger.LogWarning("Failed to automatically restart the watchdog! Alpha: {0}; Bravo: {1}", result.Alpha.ToString(), result.Bravo.ToString());
                                 var retryDelay = Math.Min(Math.Pow(2, retryAttempts), 3600); //max of one hour
                                 chatTask = chat.SendWatchdogMessage(String.Format(CultureInfo.InvariantCulture, "Failed to restart watchdog (Attempt: {0}), retrying in {1} seconds...", retryAttempts, retryDelay), cancellationToken);
                                 await Task.WhenAll(Task.Delay((int)retryDelay, cancellationToken), chatTask).ConfigureAwait(false);
                             }
                         }
                     }
                 }
                 catch (OperationCanceledException)
                 {
                     logger.LogDebug("Monitor cancelled");
                     break;
                 }
                 catch (Exception e)
                 {
                     logger.LogError("Monitor crashed! Iteration: {0}, State: {1}", iteration, JsonConvert.SerializeObject(monitorState));
                     await chat.SendWatchdogMessage(String.Format(CultureInfo.InvariantCulture, "Monitor crashed, this should NEVER happen! Please report this, full details in logs! Restarting monitor... Error: {0}", e.Message), cancellationToken).ConfigureAwait(false);
                 }
             }
         }
async Task<WatchdogLaunchResult> Tgstation.Server.Host.Components.Watchdog.Watchdog.Restart (bool graceful, CancellationToken cancellationToken)
Restarts the watchdog
Implements Tgstation.Server.Host.Components.Watchdog.IWatchdog.
Definition at line 752 of file Watchdog.cs.
References Tgstation.Server.Host.Core.SemaphoreSlimContext.Lock().
         {
             using (await SemaphoreSlimContext.Lock(semaphore, cancellationToken).ConfigureAwait(false))
             {
                 if (!graceful || !Running)
                 {
                     Task chatTask;
                     if (Running)
                     {
                         chatTask = chat.SendWatchdogMessage("Manual restart triggered...", cancellationToken);
                         await TerminateNoLock(false, false, cancellationToken).ConfigureAwait(false);
                     }
                     else
                         chatTask = Task.CompletedTask;
                     var result = await LaunchNoLock(true, !Running, false, cancellationToken).ConfigureAwait(false);
                     await chatTask.ConfigureAwait(false);
                     return result;
                 }
                 var toReboot = AlphaIsActive ? alphaServer : bravoServer;
                 var other = AlphaIsActive ? bravoServer : alphaServer;
                 if (toReboot != null)
                 {
                     if (!await toReboot.SetRebootState(Components.Watchdog.RebootState.Restart, cancellationToken).ConfigureAwait(false))
                         logger.LogWarning("Unable to send reboot state change event!");
                 }
                 return null;
             }
         }
async Task Tgstation.Server.Host.Components.Watchdog.Watchdog.StartAsync (CancellationToken cancellationToken)
Definition at line 790 of file Watchdog.cs.
Referenced by Tgstation.Server.Host.Components.Instance.StartAsync().
         {
             if (autoStart)
                 await LaunchNoLock(true, true, true, cancellationToken).ConfigureAwait(false);
         }
async Task Tgstation.Server.Host.Components.Watchdog.Watchdog.StopAsync (CancellationToken cancellationToken)
Definition at line 797 of file Watchdog.cs.
References Tgstation.Server.Host.Components.Watchdog.WatchdogReattachInformation.Alpha, and Tgstation.Server.Host.Components.Watchdog.ISessionController.Release().
Referenced by Tgstation.Server.Host.Components.Instance.StartAsync().
         {
             if (releaseServers && Running)
             {
                 var reattachInformation = new WatchdogReattachInformation
                 {
                     AlphaIsActive = AlphaIsActive
                 };
                 reattachInformation.Alpha = alphaServer?.Release();
                 reattachInformation.Bravo = bravoServer?.Release();
                 await reattachInfoHandler.Save(reattachInformation, cancellationToken).ConfigureAwait(false);
             }
             await Terminate(false, cancellationToken).ConfigureAwait(false);
         }
async Task<bool> Tgstation.Server.Host.Components.Watchdog.Watchdog.StopMonitor () private
Definition at line 592 of file Watchdog.cs.
         {
             logger.LogTrace("StopMonitor");
             if (monitorTask == null)
                 return false;
             monitorCts.Cancel();
             await monitorTask.ConfigureAwait(false);
             monitorCts.Dispose();
             monitorTask = null;
             return true;
         }
async Task Tgstation.Server.Host.Components.Watchdog.Watchdog.Terminate (bool graceful, CancellationToken cancellationToken)
Stops the watchdog
Implements Tgstation.Server.Host.Components.Watchdog.IWatchdog.
Definition at line 783 of file Watchdog.cs.
References Tgstation.Server.Host.Core.SemaphoreSlimContext.Lock().
         {
             using (await SemaphoreSlimContext.Lock(semaphore, cancellationToken).ConfigureAwait(false))
                 await TerminateNoLock(graceful, true, cancellationToken).ConfigureAwait(false);
         }
async Task Tgstation.Server.Host.Components.Watchdog.Watchdog.TerminateNoLock (bool graceful, bool announce, CancellationToken cancellationToken) private
Implementation of Terminate(bool, CancellationToken). Does not lock semaphore
Parameters
graceful If the termination will be delayed until a reboot is detected in the active server's DMAPI and this function will return immediately
announce If the termination will be announced using chat
cancellationToken The CancellationToken for the operation
Definition at line 200 of file Watchdog.cs.
References Tgstation.Server.Host.Components.Watchdog.ISessionController.SetRebootState().
         {
             if (!Running)
                 return;
             if (!graceful)
             {
                 var chatTask = announce ? chat.SendWatchdogMessage("Terminating...", cancellationToken) : Task.CompletedTask;
                 await StopMonitor().ConfigureAwait(false);
                 DisposeAndNullControllers();
                 await chatTask.ConfigureAwait(false);
                 return;
             }
             var toKill = AlphaIsActive ? alphaServer : bravoServer;
             var other = AlphaIsActive ? bravoServer : alphaServer;
             if (toKill != null)
                 await toKill.SetRebootState(Components.Watchdog.RebootState.Shutdown, cancellationToken).ConfigureAwait(false);
         }
Member Data Documentation
Models.CompileJob Tgstation.Server.Host.Components.Watchdog.Watchdog.ActiveCompileJob => (AlphaIsActive ? alphaServer : bravoServer)?.Dmb.CompileJob
Definition at line 35 of file Watchdog.cs.
TaskCompletionSource<object> Tgstation.Server.Host.Components.Watchdog.Watchdog.activeParametersUpdated private
TaskCompletionSource<TResult> that completes when ActiveLaunchParameters are changed and we are Running
Definition at line 117 of file Watchdog.cs.
const int Tgstation.Server.Host.Components.Watchdog.Watchdog.AlphaBravoStartupSeperationInterval = 10 private
The time in seconds to wait from starting alphaServer to start bravoServer. Does not take responsiveness into account
Definition at line 26 of file Watchdog.cs.
ISessionController Tgstation.Server.Host.Components.Watchdog.Watchdog.alphaServer private
Server designation alpha
Definition at line 122 of file Watchdog.cs.
readonly bool Tgstation.Server.Host.Components.Watchdog.Watchdog.autoStart private
If the Watchdog should LaunchNoLock(bool, bool, bool, CancellationToken) in StartAsync(CancellationToken)
Definition at line 102 of file Watchdog.cs.
ISessionController Tgstation.Server.Host.Components.Watchdog.Watchdog.bravoServer private
Server designation bravo
Definition at line 126 of file Watchdog.cs.
readonly IByondTopicSender Tgstation.Server.Host.Components.Watchdog.Watchdog.byondTopicSender private
The IByondTopicSender for the Watchdog
Definition at line 82 of file Watchdog.cs.
readonly IChat Tgstation.Server.Host.Components.Watchdog.Watchdog.chat private
The IChat for the Watchdog
Definition at line 52 of file Watchdog.cs.
readonly IDatabaseContextFactory Tgstation.Server.Host.Components.Watchdog.Watchdog.databaseContextFactory private
The IDatabaseContextFactory for the Watchdog
Definition at line 77 of file Watchdog.cs.
readonly IDmbFactory Tgstation.Server.Host.Components.Watchdog.Watchdog.dmbFactory private
The IDmbFactory for the Watchdog
Definition at line 62 of file Watchdog.cs.
readonly IEventConsumer Tgstation.Server.Host.Components.Watchdog.Watchdog.eventConsumer private
The IEventConsumer for the Watchdog
Definition at line 87 of file Watchdog.cs.
readonly Api.Models.Instance Tgstation.Server.Host.Components.Watchdog.Watchdog.instance private
The Api.Models.Instance for the Watchdog
Definition at line 97 of file Watchdog.cs.
readonly ILogger<Watchdog> Tgstation.Server.Host.Components.Watchdog.Watchdog.logger private
The ILogger<TCategoryName> for the Watchdog
Definition at line 67 of file Watchdog.cs.
CancellationTokenSource Tgstation.Server.Host.Components.Watchdog.Watchdog.monitorCts private
The CancellationTokenSource for the monitor loop
Definition at line 107 of file Watchdog.cs.
Task Tgstation.Server.Host.Components.Watchdog.Watchdog.monitorTask private
The Task running the monitor loop
Definition at line 112 of file Watchdog.cs.
readonly IReattachInfoHandler Tgstation.Server.Host.Components.Watchdog.Watchdog.reattachInfoHandler private
The IReattachInfoHandler for the Watchdog
Definition at line 72 of file Watchdog.cs.
RebootState Tgstation.Server.Host.Components.Watchdog.Watchdog.RebootState => Running ? (AlphaIsActive ? alphaServer?.RebootState : bravoServer?.RebootState) : null
Definition at line 47 of file Watchdog.cs.
bool Tgstation.Server.Host.Components.Watchdog.Watchdog.releaseServers private
If the servers should be released instead of shutdown
Definition at line 131 of file Watchdog.cs.
readonly SemaphoreSlim Tgstation.Server.Host.Components.Watchdog.Watchdog.semaphore private
The SemaphoreSlim for the Watchdog
Definition at line 92 of file Watchdog.cs.
readonly ISessionControllerFactory Tgstation.Server.Host.Components.Watchdog.Watchdog.sessionControllerFactory private
The ISessionControllerFactory for the Watchdog
Definition at line 57 of file Watchdog.cs.
Property Documentation
DreamDaemonLaunchParameters Tgstation.Server.Host.Components.Watchdog.Watchdog.ActiveLaunchParameters get private set
Definition at line 41 of file Watchdog.cs.
bool Tgstation.Server.Host.Components.Watchdog.Watchdog.AlphaIsActive get private set
Definition at line 32 of file Watchdog.cs.
DreamDaemonLaunchParameters Tgstation.Server.Host.Components.Watchdog.Watchdog.LastLaunchParameters get private set
Definition at line 44 of file Watchdog.cs.
LaunchResult Tgstation.Server.Host.Components.Watchdog.Watchdog.LastLaunchResult get private set
Definition at line 38 of file Watchdog.cs.
bool Tgstation.Server.Host.Components.Watchdog.Watchdog.Running get private set
Definition at line 29 of file Watchdog.cs.
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Watchdog/Watchdog.cs