tgstation-server: TGServiceInterface.Command Class Reference
TGServiceInterface.Command Class Reference abstract
Helper for creating a text Command tree
Public Types
enum ExitCode : int { ExitCode.Normal = 0, ExitCode.ConnectionError = 1, ExitCode.BadCommand = 2, ExitCode.ServerError = 3 }
Exit codes for Commands
Public Member Functions
virtual ExitCode DoRun (IList< string > parameters)
Caller of Run(IList<string>), can be used to modify the root behaviour of the Command
virtual void PrintHelp ()
Prints usage text of the Command to the invoker
virtual string GetArgumentString ()
Override to add argument text to the Command Format is <required> <arguments> [optional] [arguments]
abstract string GetHelpText ()
Override to add usage text to the Command
Static Public Attributes
static ThreadLocal< Action< string > > OutputProcVar = new ThreadLocal<Action<string>>()
Proc that will show a message to the Command invoker. Do not call directly, use OutputProc(string) instead
Protected Member Functions
abstract ExitCode Run (IList< string > parameters)
Override to do the actions of the Command
Static Protected Member Functions
static void OutputProc (string message)
Write output to the Command invoker
Properties
string Keyword [get, protected set]
The text that invokes this Command. Set in constructor
int RequiredParameters [get, protected set]
The number of parameters this Command requires. Set in Constructor
Detailed Description
Helper for creating a text Command tree
Definition at line 10 of file Command.cs.
Member Enumeration Documentation
enum TGServiceInterface.Command.ExitCode : int strong
Exit codes for Commands
Enumerator
Normal
The Command ran successfully
ConnectionError
The connection to the service was interrupted during the Command
BadCommand
Invalid parameters for Command
ServerError
The command failed due to conditions on the service
Definition at line 15 of file Command.cs.
                              : int
         {
             Normal = 0,
             ConnectionError = 1,
             BadCommand = 2,
             ServerError = 3,
         }
Member Function Documentation
virtual ExitCode TGServiceInterface.Command.DoRun (IList< string > parameters) virtual
Caller of Run(IList<string>), can be used to modify the root behaviour of the Command
Parameters
parameters List of parameters passed to the Command
Returns
An ExitCode describing the execution of the Command
Reimplemented in TGServerService.ChatCommands.ChatCommand, and TGCommandLine.InstanceRootCommand.
Definition at line 59 of file Command.cs.
References TGServiceInterface.Command.Run().
Referenced by TGServerService.ServerInstance.ChatProvider_OnChatMessage(), and TGCommandLine.Program.RunCommandLine().
         {
             return Run(parameters);
         }
virtual string TGServiceInterface.Command.GetArgumentString () virtual
Override to add argument text to the Command Format is <required> <arguments> [optional] [arguments]
Returns
Formatted argument text for the Command
Reimplemented in TGCommandLine.DiscordSetTokenCommand, TGCommandLine.IRCServerCommand, TGCommandLine.IRCAuthCommand, TGCommandLine.ChatDeadminCommand, TGCommandLine.IRCAuthLevelCommand, TGCommandLine.ServiceRenameInstanceCommand, TGCommandLine.DiscordAuthModeCommand, TGCommandLine.ServiceSetRemoteAccessPortCommand, TGCommandLine.IRCAuthModeCommand, TGCommandLine.DDSecurityCommand, TGCommandLine.ChatAddminCommand, TGCommandLine.ServiceDisableInstanceCommand, TGCommandLine.RepoMergePRCommand, TGCommandLine.DDPortCommand, TGCommandLine.ServiceEnableInstanceCommand, TGCommandLine.RepoSetNameCommand, TGCommandLine.RepoSetEmailCommand, TGCommandLine.DDWebclientCommand, TGCommandLine.ServiceSetPythonPathCommand, TGCommandLine.DDAutostartCommand, TGCommandLine.TestmergeCommand, TGCommandLine.RepoUpdateCommand, TGCommandLine.ConfigUploadCommand, TGCommandLine.DMInitializeCommand, TGCommandLine.ServiceImportInstanceCommand, TGCommandLine.ChatPartCommand, TGCommandLine.RepoResetCommand, TGCommandLine.UpdateCommand, TGCommandLine.DMSetProjectNameCommand, TGCommandLine.BYONDUpdateCommand, TGCommandLine.ConfigDownloadCommand, TGCommandLine.ServiceDetachInstanceCommand, TGCommandLine.DDRestartCommand, TGCommandLine.DDStopCommand, TGCommandLine.AdminSetGroupCommand, TGCommandLine.ChatJoinCommand, TGCommandLine.DMCompileCommand, TGCommandLine.RepoSetupCommand, TGCommandLine.ConfigListCommand, TGCommandLine.SetAutoUpdateCommand, TGCommandLine.ServiceCreateInstanceCommand, TGCommandLine.IRCNickCommand, TGCommandLine.BYONDVersionCommand, TGCommandLine.ConfigDeleteCommand, TGServerService.ChatCommands.ByondCommand, and TGCommandLine.DDWorldAnnounceCommand.
Definition at line 82 of file Command.cs.
References TGServiceInterface.Command.GetHelpText().
Referenced by TGServiceInterface.Command.PrintHelp().
         {
             return "";
         }
abstract string TGServiceInterface.Command.GetHelpText () pure virtual
Override to add usage text to the Command
Returns
Formatted usage text for the Command
Implemented in TGCommandLine.DiscordSetTokenCommand, TGCommandLine.IRCServerCommand, TGCommandLine.ChatDisableCommand, TGCommandLine.ChatEnableCommand, TGCommandLine.ChatStatusCommand, TGCommandLine.IRCDisableAuthCommand, TGCommandLine.IRCAuthCommand, TGCommandLine.ChatDeadminCommand, TGCommandLine.IRCAuthLevelCommand, TGCommandLine.ServiceRenameInstanceCommand, TGCommandLine.DiscordAuthModeCommand, TGCommandLine.RepoCheckoutCommand, TGCommandLine.ServiceSetRemoteAccessPortCommand, TGCommandLine.IRCAuthModeCommand, TGCommandLine.RepoListBackupsCommand, TGCommandLine.ServiceRemoteAccessPortCommand, TGCommandLine.DDSecurityCommand, TGCommandLine.ChatAddminCommand, TGCommandLine.RepoListPRsCommand, TGCommandLine.RepoMergePRCommand, TGCommandLine.ServiceDisableInstanceCommand, TGCommandLine.ChatReconnectCommand, TGCommandLine.DDPortCommand, TGCommandLine.RepoSetNameCommand, TGCommandLine.ServiceEnableInstanceCommand, TGCommandLine.RepoSetEmailCommand, TGCommandLine.DDWebclientCommand, TGCommandLine.ServiceSetPythonPathCommand, TGCommandLine.ChatListAdminsCommand, TGCommandLine.RepoPushChangelogCommand, TGCommandLine.DMCancelCommand, TGCommandLine.RepoGenChangelogCommand, TGCommandLine.DDAutostartCommand, TGCommandLine.TestmergeCommand, TGCommandLine.ServicePythonPathCommand, TGCommandLine.RepoUpdateCommand, TGCommandLine.ConfigUploadCommand, TGCommandLine.DMInitializeCommand, TGCommandLine.ChatPartCommand, TGCommandLine.ServiceImportInstanceCommand, TGCommandLine.DDStatusCommand, TGCommandLine.RepoResetCommand, TGCommandLine.UpdateCommand, TGCommandLine.DMSetProjectNameCommand, TGCommandLine.BYONDUpdateCommand, TGCommandLine.ConfigDownloadCommand, TGCommandLine.DDRestartCommand, TGCommandLine.DMStatusCommand, TGCommandLine.RepoStatusCommand, TGCommandLine.ServiceDetachInstanceCommand, TGServiceInterface.RootCommand, TGCommandLine.AdminClearGroupCommand, TGCommandLine.ConfigServerDirectoryCommand, TGCommandLine.BYONDStatusCommand, TGCommandLine.ServiceListInstancesCommand, TGCommandLine.DDStopCommand, TGCommandLine.ChatJoinCommand, TGCommandLine.DMCompileCommand, TGCommandLine.AdminSetGroupCommand, TGCommandLine.RepoSetupCommand, TGCommandLine.SetAutoUpdateCommand, TGCommandLine.ConfigListCommand, TGCommandLine.DDStartCommand, TGCommandLine.AdminViewGroupCommand, TGCommandLine.BYONDVersionCommand, TGCommandLine.IRCNickCommand, TGCommandLine.ConfigDeleteCommand, TGCommandLine.ServiceCreateInstanceCommand, TGServerService.ChatCommands.PullRequestsCommand, TGCommandLine.AdminRecreateStaticCommand, TGCommandLine.AutoUpdateCommand, TGServerService.ChatCommands.ByondCommand, TGServerService.ChatCommands.RevisionCommand, TGServerService.ChatCommands.ServerChatCommand, TGCommandLine.DDWorldAnnounceCommand, TGCommandLine.RepoUpdateJsonCommand, TGCommandLine.DiscordCommand, TGServerService.ChatCommands.KekCommand, TGServerService.ChatCommands.VersionCommand, TGCommandLine.ServiceCommand, TGCommandLine.BYONDCommand, TGCommandLine.ConfigCommand, TGCommandLine.DMCommand, TGCommandLine.IRCCommand, TGCommandLine.DDCommand, TGCommandLine.RepoCommand, and TGCommandLine.AdminCommand.
Referenced by TGServiceInterface.Command.GetArgumentString(), and TGServiceInterface.Command.PrintHelp().
static void TGServiceInterface.Command.OutputProc (string message) static protected
Write output to the Command invoker
Parameters
message The output to display
Definition at line 42 of file Command.cs.
Referenced by TGCommandLine.InstanceRootCommand.DoRun(), TGCommandLine.CLICommand.PrintHelp(), TGServiceInterface.RootCommand.PrintHelp(), TGServiceInterface.Command.PrintHelp(), TGServiceInterface.RootCommand.Run(), TGCommandLine.AdminRecreateStaticCommand.Run(), TGCommandLine.BYONDVersionCommand.Run(), TGCommandLine.DMCompileCommand.Run(), TGCommandLine.ConfigDeleteCommand.Run(), TGCommandLine.RepoUpdateJsonCommand.Run(), TGCommandLine.AutoUpdateCommand.Run(), TGCommandLine.DDWorldAnnounceCommand.Run(), TGCommandLine.AdminViewGroupCommand.Run(), TGCommandLine.RepoSetupCommand.Run(), TGCommandLine.ServiceCreateInstanceCommand.Run(), TGCommandLine.BYONDStatusCommand.Run(), TGCommandLine.DDStartCommand.Run(), TGCommandLine.SetAutoUpdateCommand.Run(), TGCommandLine.ConfigListCommand.Run(), TGCommandLine.AdminSetGroupCommand.Run(), TGCommandLine.ChatJoinCommand.Run(), TGCommandLine.RepoStatusCommand.Run(), TGCommandLine.DDStopCommand.Run(), TGCommandLine.ServiceListInstancesCommand.Run(), TGCommandLine.ConfigServerDirectoryCommand.Run(), TGCommandLine.UpdateCommand.Run(), TGCommandLine.DMStatusCommand.Run(), TGCommandLine.BYONDUpdateCommand.Run(), TGCommandLine.AdminClearGroupCommand.Run(), TGCommandLine.ConfigDownloadCommand.Run(), TGCommandLine.DDRestartCommand.Run(), TGCommandLine.ServiceDetachInstanceCommand.Run(), TGCommandLine.RepoResetCommand.Run(), TGCommandLine.ConfigUploadCommand.Run(), TGCommandLine.DDStatusCommand.Run(), TGCommandLine.TestmergeCommand.Run(), TGCommandLine.RepoUpdateCommand.Run(), TGCommandLine.ChatPartCommand.Run(), TGCommandLine.ServiceImportInstanceCommand.Run(), TGCommandLine.DMInitializeCommand.Run(), TGCommandLine.DDAutostartCommand.Run(), TGCommandLine.RepoGenChangelogCommand.Run(), TGCommandLine.ServicePythonPathCommand.Run(), TGCommandLine.DDWebclientCommand.Run(), TGCommandLine.DMCancelCommand.Run(), TGCommandLine.RepoPushChangelogCommand.Run(), TGCommandLine.ChatListAdminsCommand.Run(), TGCommandLine.DDPortCommand.Run(), TGCommandLine.ServiceEnableInstanceCommand.Run(), TGCommandLine.RepoMergePRCommand.Run(), TGCommandLine.DDSecurityCommand.Run(), TGCommandLine.ChatReconnectCommand.Run(), TGCommandLine.ServiceDisableInstanceCommand.Run(), TGCommandLine.ChatAddminCommand.Run(), TGCommandLine.RepoListPRsCommand.Run(), TGCommandLine.ServiceRemoteAccessPortCommand.Run(), TGCommandLine.RepoListBackupsCommand.Run(), TGCommandLine.IRCAuthModeCommand.Run(), TGCommandLine.RepoCheckoutCommand.Run(), TGCommandLine.ServiceSetRemoteAccessPortCommand.Run(), TGCommandLine.DiscordAuthModeCommand.Run(), TGCommandLine.ServiceRenameInstanceCommand.Run(), TGCommandLine.IRCAuthLevelCommand.Run(), TGCommandLine.ChatDeadminCommand.Run(), TGCommandLine.ChatStatusCommand.Run(), TGCommandLine.ChatEnableCommand.Run(), TGCommandLine.ChatDisableCommand.Run(), TGCommandLine.IRCServerCommand.Run(), TGCommandLine.DiscordSetTokenCommand.Run(), and TGCommandLine.DMStatusCommand.ShowError().
         {
             OutputProcVar.Value(message);
         }
virtual void TGServiceInterface.Command.PrintHelp () virtual
Prints usage text of the Command to the invoker
Reimplemented in TGServiceInterface.RootCommand, and TGCommandLine.CLICommand.
Definition at line 72 of file Command.cs.
References TGServiceInterface.Command.GetArgumentString(), TGServiceInterface.Command.GetHelpText(), TGServiceInterface.Command.Keyword, and TGServiceInterface.Command.OutputProc().
         {
             var argstr = GetArgumentString();
             OutputProc(String.Format("{0} {1}- {2}", Keyword, argstr.Length > 0 ? argstr + " " : "", GetHelpText()));
         }
abstract ExitCode TGServiceInterface.Command.Run (IList< string > parameters) protected pure virtual
Override to do the actions of the Command
Parameters
parameters List of string parameters passed to the Command. Guaranteed to have at least RequiredParameters non-empty/whitespace entries
Returns
An ExitCode describing the execution of the Command
Implemented in TGCommandLine.DiscordSetTokenCommand, TGCommandLine.IRCServerCommand, TGCommandLine.ChatDisableCommand, TGCommandLine.ChatEnableCommand, TGCommandLine.ChatStatusCommand, TGCommandLine.IRCDisableAuthCommand, TGCommandLine.IRCAuthCommand, TGCommandLine.ChatDeadminCommand, TGCommandLine.IRCAuthLevelCommand, TGCommandLine.ServiceRenameInstanceCommand, TGCommandLine.DiscordAuthModeCommand, TGCommandLine.ServiceSetRemoteAccessPortCommand, TGCommandLine.RepoCheckoutCommand, TGCommandLine.IRCAuthModeCommand, TGCommandLine.RepoListBackupsCommand, TGCommandLine.ServiceRemoteAccessPortCommand, TGCommandLine.ChatAddminCommand, TGCommandLine.RepoListPRsCommand, TGCommandLine.ServiceDisableInstanceCommand, TGCommandLine.ChatReconnectCommand, TGCommandLine.DDSecurityCommand, TGCommandLine.RepoMergePRCommand, TGCommandLine.ServiceEnableInstanceCommand, TGCommandLine.RepoSetNameCommand, TGCommandLine.DDPortCommand, TGCommandLine.ServiceSetPythonPathCommand, TGCommandLine.RepoSetEmailCommand, TGCommandLine.ChatListAdminsCommand, TGCommandLine.RepoPushChangelogCommand, TGCommandLine.DMCancelCommand, TGCommandLine.DDWebclientCommand, TGCommandLine.ServicePythonPathCommand, TGCommandLine.RepoGenChangelogCommand, TGCommandLine.DDAutostartCommand, TGCommandLine.DMInitializeCommand, TGCommandLine.ServiceImportInstanceCommand, TGCommandLine.ChatPartCommand, TGCommandLine.RepoUpdateCommand, TGCommandLine.TestmergeCommand, TGCommandLine.ConfigUploadCommand, TGCommandLine.DDStatusCommand, TGCommandLine.DMSetProjectNameCommand, TGCommandLine.RepoResetCommand, TGCommandLine.ServiceDetachInstanceCommand, TGCommandLine.DDRestartCommand, TGCommandLine.ConfigDownloadCommand, TGCommandLine.AdminClearGroupCommand, TGCommandLine.BYONDUpdateCommand, TGCommandLine.DMStatusCommand, TGCommandLine.UpdateCommand, TGCommandLine.ConfigServerDirectoryCommand, TGCommandLine.ServiceListInstancesCommand, TGCommandLine.DDStopCommand, TGCommandLine.ChatJoinCommand, TGCommandLine.RepoStatusCommand, TGCommandLine.AdminSetGroupCommand, TGCommandLine.ConfigListCommand, TGCommandLine.SetAutoUpdateCommand, TGCommandLine.DDStartCommand, TGCommandLine.BYONDStatusCommand, TGCommandLine.ServiceCreateInstanceCommand, TGCommandLine.RepoSetupCommand, TGCommandLine.AdminViewGroupCommand, TGCommandLine.IRCNickCommand, TGCommandLine.DDWorldAnnounceCommand, TGCommandLine.AutoUpdateCommand, TGServerService.ChatCommands.ServerChatCommand, TGCommandLine.RepoUpdateJsonCommand, TGCommandLine.ConfigDeleteCommand, TGCommandLine.DMCompileCommand, TGCommandLine.BYONDVersionCommand, TGCommandLine.AdminRecreateStaticCommand, TGServiceInterface.RootCommand, TGServerService.ChatCommands.ByondCommand, TGServerService.ChatCommands.KekCommand, TGServerService.ChatCommands.PullRequestsCommand, TGServerService.ChatCommands.RevisionCommand, and TGServerService.ChatCommands.VersionCommand.
Referenced by TGServiceInterface.Command.DoRun().
Member Data Documentation
ThreadLocal<Action<string> > TGServiceInterface.Command.OutputProcVar = new ThreadLocal<Action<string>>() static
Proc that will show a message to the Command invoker. Do not call directly, use OutputProc(string) instead
Definition at line 37 of file Command.cs.
Referenced by TGServerService.ServerInstance.ChatProvider_OnChatMessage(), and TGCommandLine.Program.Main().
Property Documentation
string TGServiceInterface.Command.Keyword get protected set
The text that invokes this Command. Set in constructor
Definition at line 49 of file Command.cs.
Referenced by TGCommandLine.AdminClearGroupCommand.AdminClearGroupCommand(), TGCommandLine.AdminCommand.AdminCommand(), TGCommandLine.AdminRecreateStaticCommand.AdminRecreateStaticCommand(), TGCommandLine.AdminSetGroupCommand.AdminSetGroupCommand(), TGCommandLine.AdminViewGroupCommand.AdminViewGroupCommand(), TGCommandLine.AutoUpdateCommand.AutoUpdateCommand(), TGCommandLine.BYONDCommand.BYONDCommand(), TGCommandLine.BYONDStatusCommand.BYONDStatusCommand(), TGCommandLine.BYONDUpdateCommand.BYONDUpdateCommand(), TGCommandLine.BYONDVersionCommand.BYONDVersionCommand(), TGCommandLine.ChatAddminCommand.ChatAddminCommand(), TGCommandLine.ChatDeadminCommand.ChatDeadminCommand(), TGCommandLine.ChatDisableCommand.ChatDisableCommand(), TGCommandLine.ChatEnableCommand.ChatEnableCommand(), TGCommandLine.ChatJoinCommand.ChatJoinCommand(), TGCommandLine.ChatListAdminsCommand.ChatListAdminsCommand(), TGCommandLine.ChatPartCommand.ChatPartCommand(), TGCommandLine.ChatReconnectCommand.ChatReconnectCommand(), TGCommandLine.ChatStatusCommand.ChatStatusCommand(), TGCommandLine.ConfigCommand.ConfigCommand(), TGCommandLine.ConfigDeleteCommand.ConfigDeleteCommand(), TGCommandLine.ConfigDownloadCommand.ConfigDownloadCommand(), TGCommandLine.ConfigListCommand.ConfigListCommand(), TGCommandLine.ConfigServerDirectoryCommand.ConfigServerDirectoryCommand(), TGCommandLine.ConfigUploadCommand.ConfigUploadCommand(), TGCommandLine.DDAutostartCommand.DDAutostartCommand(), TGCommandLine.DDCommand.DDCommand(), TGCommandLine.DDPortCommand.DDPortCommand(), TGCommandLine.DDRestartCommand.DDRestartCommand(), TGCommandLine.DDSecurityCommand.DDSecurityCommand(), TGCommandLine.DDStartCommand.DDStartCommand(), TGCommandLine.DDStatusCommand.DDStatusCommand(), TGCommandLine.DDStopCommand.DDStopCommand(), TGCommandLine.DDWebclientCommand.DDWebclientCommand(), TGCommandLine.DDWorldAnnounceCommand.DDWorldAnnounceCommand(), TGCommandLine.DiscordAuthModeCommand.DiscordAuthModeCommand(), TGCommandLine.DiscordCommand.DiscordCommand(), TGCommandLine.DiscordSetTokenCommand.DiscordSetTokenCommand(), TGCommandLine.DMCancelCommand.DMCancelCommand(), TGCommandLine.DMCommand.DMCommand(), TGCommandLine.DMCompileCommand.DMCompileCommand(), TGCommandLine.DMInitializeCommand.DMInitializeCommand(), TGCommandLine.DMSetProjectNameCommand.DMSetProjectNameCommand(), TGCommandLine.DMStatusCommand.DMStatusCommand(), TGCommandLine.IRCAuthCommand.IRCAuthCommand(), TGCommandLine.IRCAuthLevelCommand.IRCAuthLevelCommand(), TGCommandLine.IRCAuthModeCommand.IRCAuthModeCommand(), TGCommandLine.IRCCommand.IRCCommand(), TGCommandLine.IRCDisableAuthCommand.IRCDisableAuthCommand(), TGCommandLine.IRCNickCommand.IRCNickCommand(), TGCommandLine.IRCServerCommand.IRCServerCommand(), TGServiceInterface.Command.PrintHelp(), TGCommandLine.RepoCheckoutCommand.RepoCheckoutCommand(), TGCommandLine.RepoCommand.RepoCommand(), TGCommandLine.RepoGenChangelogCommand.RepoGenChangelogCommand(), TGCommandLine.RepoListBackupsCommand.RepoListBackupsCommand(), TGCommandLine.RepoListPRsCommand.RepoListPRsCommand(), TGCommandLine.RepoMergePRCommand.RepoMergePRCommand(), TGCommandLine.RepoPushChangelogCommand.RepoPushChangelogCommand(), TGCommandLine.RepoResetCommand.RepoResetCommand(), TGCommandLine.RepoSetEmailCommand.RepoSetEmailCommand(), TGCommandLine.RepoSetNameCommand.RepoSetNameCommand(), TGCommandLine.RepoSetupCommand.RepoSetupCommand(), TGCommandLine.RepoStatusCommand.RepoStatusCommand(), TGCommandLine.RepoUpdateCommand.RepoUpdateCommand(), TGCommandLine.RepoUpdateJsonCommand.RepoUpdateJsonCommand(), TGServiceInterface.RootCommand.Run(), TGCommandLine.ServiceCommand.ServiceCommand(), TGCommandLine.ServiceCreateInstanceCommand.ServiceCreateInstanceCommand(), TGCommandLine.ServiceDetachInstanceCommand.ServiceDetachInstanceCommand(), TGCommandLine.ServiceDisableInstanceCommand.ServiceDisableInstanceCommand(), TGCommandLine.ServiceEnableInstanceCommand.ServiceEnableInstanceCommand(), TGCommandLine.ServiceImportInstanceCommand.ServiceImportInstanceCommand(), TGCommandLine.ServiceListInstancesCommand.ServiceListInstancesCommand(), TGCommandLine.ServicePythonPathCommand.ServicePythonPathCommand(), TGCommandLine.ServiceRemoteAccessPortCommand.ServiceRemoteAccessPortCommand(), TGCommandLine.ServiceRenameInstanceCommand.ServiceRenameInstanceCommand(), TGCommandLine.ServiceSetPythonPathCommand.ServiceSetPythonPathCommand(), TGCommandLine.ServiceSetRemoteAccessPortCommand.ServiceSetRemoteAccessPortCommand(), TGCommandLine.SetAutoUpdateCommand.SetAutoUpdateCommand(), TGCommandLine.TestmergeCommand.TestmergeCommand(), and TGCommandLine.UpdateCommand.UpdateCommand().
int TGServiceInterface.Command.RequiredParameters get protected set
The number of parameters this Command requires. Set in Constructor
Definition at line 53 of file Command.cs.
Referenced by TGCommandLine.AdminSetGroupCommand.AdminSetGroupCommand(), TGCommandLine.BYONDUpdateCommand.BYONDUpdateCommand(), TGCommandLine.ChatAddminCommand.ChatAddminCommand(), TGCommandLine.ChatDeadminCommand.ChatDeadminCommand(), TGCommandLine.ChatJoinCommand.ChatJoinCommand(), TGCommandLine.ChatPartCommand.ChatPartCommand(), TGCommandLine.ConfigDeleteCommand.ConfigDeleteCommand(), TGCommandLine.ConfigDownloadCommand.ConfigDownloadCommand(), TGCommandLine.ConfigUploadCommand.ConfigUploadCommand(), TGCommandLine.DDAutostartCommand.DDAutostartCommand(), TGCommandLine.DDPortCommand.DDPortCommand(), TGCommandLine.DDSecurityCommand.DDSecurityCommand(), TGCommandLine.DDWebclientCommand.DDWebclientCommand(), TGCommandLine.DDWorldAnnounceCommand.DDWorldAnnounceCommand(), TGCommandLine.DiscordAuthModeCommand.DiscordAuthModeCommand(), TGCommandLine.DiscordSetTokenCommand.DiscordSetTokenCommand(), TGCommandLine.DMSetProjectNameCommand.DMSetProjectNameCommand(), TGCommandLine.IRCAuthCommand.IRCAuthCommand(), TGCommandLine.IRCAuthLevelCommand.IRCAuthLevelCommand(), TGCommandLine.IRCAuthModeCommand.IRCAuthModeCommand(), TGCommandLine.IRCNickCommand.IRCNickCommand(), TGCommandLine.IRCServerCommand.IRCServerCommand(), TGCommandLine.RepoCheckoutCommand.RepoCheckoutCommand(), TGCommandLine.RepoMergePRCommand.RepoMergePRCommand(), TGCommandLine.RepoSetEmailCommand.RepoSetEmailCommand(), TGCommandLine.RepoSetNameCommand.RepoSetNameCommand(), TGCommandLine.RepoSetupCommand.RepoSetupCommand(), TGCommandLine.RepoUpdateCommand.RepoUpdateCommand(), TGCommandLine.ServiceCreateInstanceCommand.ServiceCreateInstanceCommand(), TGCommandLine.ServiceDetachInstanceCommand.ServiceDetachInstanceCommand(), TGCommandLine.ServiceDisableInstanceCommand.ServiceDisableInstanceCommand(), TGCommandLine.ServiceEnableInstanceCommand.ServiceEnableInstanceCommand(), TGCommandLine.ServiceImportInstanceCommand.ServiceImportInstanceCommand(), TGCommandLine.ServiceRenameInstanceCommand.ServiceRenameInstanceCommand(), TGCommandLine.ServiceSetPythonPathCommand.ServiceSetPythonPathCommand(), TGCommandLine.ServiceSetRemoteAccessPortCommand.ServiceSetRemoteAccessPortCommand(), TGCommandLine.SetAutoUpdateCommand.SetAutoUpdateCommand(), TGCommandLine.TestmergeCommand.TestmergeCommand(), and TGCommandLine.UpdateCommand.UpdateCommand().
The documentation for this class was generated from the following file:
TGServiceInterface/Command.cs