tgstation-server: Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider Class Reference
Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider Class Reference
A IDmbProvider that uses hard links.
Public Member Functions
HardLinkDmbProvider (IDmbProvider baseProvider, IIOManager ioManager, IFilesystemLinkFactory linkFactory, ILogger logger, GeneralConfiguration generalConfiguration, DreamDaemonSecurity securityLevel)
Initializes a new instance of the HardLinkDmbProvider class.
override async ValueTask DisposeAsync ()
override Task FinishActivationPreparation (CancellationToken cancellationToken)
Should be awaited. before calling MakeActive(CancellationToken) to ensure the SwappableDmbProvider is ready to instantly swap. Can be called multiple times.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the preparation process.
Public Member Functions inherited from Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider
SwappableDmbProvider (IDmbProvider baseProvider, IIOManager ioManager, IFilesystemLinkFactory symlinkFactory)
Initializes a new instance of the SwappableDmbProvider class.
virtual ValueTask DisposeAsync ()
void KeepAlive ()
Disposing the IDmbProvider won't cause a cleanup of the working directory.
ValueTask MakeActive (CancellationToken cancellationToken)
Make the SwappableDmbProvider active by replacing the live link with our CompileJob.
abstract Task FinishActivationPreparation (CancellationToken cancellationToken)
Should be awaited. before calling MakeActive(CancellationToken) to ensure the SwappableDmbProvider is ready to instantly swap. Can be called multiple times.
void KeepAlive ()
Disposing the IDmbProvider won't cause a cleanup of the working directory.
Protected Member Functions
override async ValueTask DoSwap (CancellationToken cancellationToken)
Perform the swapping action.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
abstract ValueTask DoSwap (CancellationToken cancellationToken)
Perform the swapping action.
Private Member Functions
async Task< string?> MirrorSourceDirectory (int? taskThrottle, DreamDaemonSecurity securityLevel, CancellationToken cancellationToken)
Mirror the Models.CompileJob.
IEnumerable< Task > MirrorDirectoryImpl (string src, string dest, SemaphoreSlim? semaphore, DreamDaemonSecurity securityLevel, CancellationToken cancellationToken)
Recursively create tasks to create a hard link directory mirror of src to dest .
Private Attributes
readonly CancellationTokenSource cancellationTokenSource
The CancellationTokenSource for mirroringTask.
readonly Task< string?> mirroringTask
The Task representing the base provider mirroring operation.
readonly ILogger logger
The ILogger for the HardLinkDmbProvider.
Additional Inherited Members
Static Public Attributes inherited from Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider
const string LiveGameDirectory = "Live"
The directory where the BaseProvider is symlinked to.
Properties inherited from Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider
string DmbName [get]
The file name of the .dmb.
string Directory [get]
The primary game directory.
Models.CompileJob CompileJob [get]
The CompileJob of the .dmb.
EngineVersion EngineVersion [get]
The Api.Models.EngineVersion used to build the .dmb.
bool Swapped [get]
If MakeActive(CancellationToken) has been run.
IDmbProvider BaseProvider [get]
The IDmbProvider we are swapping for.
IIOManager IOManager [get]
The IIOManager to use.
IFilesystemLinkFactory LinkFactory [get]
The IFilesystemLinkFactory to use.
Properties inherited from Tgstation.Server.Host.Components.Deployment.IDmbProvider
string DmbName [get]
The file name of the .dmb.
string Directory [get]
The primary game directory.
Models.CompileJob CompileJob [get]
The CompileJob of the .dmb.
EngineVersion EngineVersion [get]
The Api.Models.EngineVersion used to build the .dmb.
Detailed Description
A IDmbProvider that uses hard links.
Definition at line 24 of file HardLinkDmbProvider.cs.
Constructor & Destructor Documentation
HardLinkDmbProvider()
Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.HardLinkDmbProvider (IDmbProvider baseProvider, IIOManager ioManager, IFilesystemLinkFactory linkFactory, ILogger logger, GeneralConfiguration generalConfiguration, DreamDaemonSecurity securityLevel)
Initializes a new instance of the HardLinkDmbProvider class.
Parameters
baseProvider The IDmbProvider for the SwappableDmbProvider.
ioManager The IIOManager for the SwappableDmbProvider.
linkFactory The IFilesystemLinkFactory for the SwappableDmbProvider.
logger The value of logger.
generalConfiguration The GeneralConfiguration for the HardLinkDmbProvider.
securityLevel The launch DreamDaemonSecurity level.
Definition at line 50 of file HardLinkDmbProvider.cs.
            : base(
                 baseProvider,
                 ioManager,
                 linkFactory)
        {
            this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
            cancellationTokenSource = new CancellationTokenSource();
            try
            {
                mirroringTask = MirrorSourceDirectory(generalConfiguration.GetCopyDirectoryTaskThrottle(), securityLevel, cancellationTokenSource.Token);
            }
            catch
            {
                cancellationTokenSource.Dispose();
                throw;
            }
        }
References Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.cancellationTokenSource, Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.logger, Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.mirroringTask, and Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.MirrorSourceDirectory().
Member Function Documentation
DisposeAsync()
override async ValueTask Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.DisposeAsync () virtual
Reimplemented from Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.
Definition at line 76 of file HardLinkDmbProvider.cs.
        {
            cancellationTokenSource.Cancel();
            cancellationTokenSource.Dispose();
            var mirroredDir = await mirroringTask;
            if (mirroredDir != null && !Swapped)
            {
                logger.LogDebug("Cancelled mirroring task, we must cleanup!");
                // We shouldn't be doing long running I/O ops because this could be under an HTTP request (DELETE /api/DreamDaemon)
                // dirty shit to follow:
                async void AsyncCleanup()
                {
                    try
                    {
                        await IOManager.DeleteDirectory(mirroredDir, CancellationToken.None); // DCT: None available
                        logger.LogTrace("Completed async cleanup of unused mirror directory: {mirroredDir}", mirroredDir);
                    }
                    catch (Exception ex)
                    {
                        logger.LogError(ex, "Error cleaning up mirrored directory {mirroredDir}!", mirroredDir);
                    }
                }
                AsyncCleanup();
            }
            await base.DisposeAsync();
        }
References Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.cancellationTokenSource, Tgstation.Server.Host.IO.IIOManager.DeleteDirectory(), Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.IOManager, Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.logger, Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.mirroringTask, and Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.Swapped.
DoSwap()
override async ValueTask Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.DoSwap (CancellationToken cancellationToken) protected virtual
Perform the swapping action.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.
Definition at line 116 of file HardLinkDmbProvider.cs.
        {
            logger.LogTrace("Begin DoSwap, mirroring task complete: {complete}...", mirroringTask.IsCompleted);
            var mirroredDir = await mirroringTask.WaitAsync(cancellationToken);
            if (mirroredDir == null)
            {
                // huh, how?
                cancellationToken.ThrowIfCancellationRequested();
                throw new InvalidOperationException("mirroringTask was cancelled without us being cancelled?");
            }
            var goAheadTcs = new TaskCompletionSource();
            // I feel dirty...
            async void DisposeOfOldDirectory()
            {
                var directoryMoved = false;
                var disposeGuid = Guid.NewGuid();
                var disposePath = disposeGuid.ToString();
                logger.LogTrace("Moving Live directory to {path} for deletion...", disposeGuid);
                try
                {
                    await IOManager.MoveDirectory(LiveGameDirectory, disposePath, cancellationToken);
                    directoryMoved = true;
                    goAheadTcs.SetResult();
                    logger.LogTrace("Deleting old Live directory {path}...", disposePath);
                    await IOManager.DeleteDirectory(disposePath, CancellationToken.None); // DCT: We're detached at this point
                    logger.LogTrace("Completed async cleanup of old Live directory: {disposePath}", disposePath);
                }
                catch (DirectoryNotFoundException ex)
                {
                    logger.LogDebug(ex, "Live directory appears to not exist");
                    if (!directoryMoved)
                        goAheadTcs.SetResult();
                }
                catch (Exception ex)
                {
                    logger.LogWarning(ex, "Failed to delete hard linked directory: {disposePath}", disposePath);
                    if (!directoryMoved)
                        goAheadTcs.SetException(ex);
                }
            }
            DisposeOfOldDirectory();
            await goAheadTcs.Task;
            logger.LogTrace("Moving mirror directory {path} to Live...", mirroredDir);
            await IOManager.MoveDirectory(mirroredDir, LiveGameDirectory, cancellationToken);
            logger.LogTrace("Swap complete!");
        }
References Tgstation.Server.Host.IO.IIOManager.DeleteDirectory(), Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.IOManager, Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.LiveGameDirectory, Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.logger, Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.mirroringTask, and Tgstation.Server.Host.IO.IIOManager.MoveDirectory().
FinishActivationPreparation()
override Task Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.FinishActivationPreparation (CancellationToken cancellationToken) virtual
Should be awaited. before calling MakeActive(CancellationToken) to ensure the SwappableDmbProvider is ready to instantly swap. Can be called multiple times.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the preparation process.
Implements Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.
Definition at line 107 of file HardLinkDmbProvider.cs.
        {
            if (!mirroringTask.IsCompleted)
                logger.LogTrace("Waiting for mirroring to complete...");
            return mirroringTask.WaitAsync(cancellationToken);
        }
References Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.logger, and Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.mirroringTask.
MirrorDirectoryImpl()
IEnumerable< Task > Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.MirrorDirectoryImpl (string src, string dest, SemaphoreSlim? semaphore, DreamDaemonSecurity securityLevel, CancellationToken cancellationToken) private
Recursively create tasks to create a hard link directory mirror of src to dest .
Parameters
src The source directory path.
dest The destination directory path.
semaphore Optional SemaphoreSlim used to limit degree of parallelism.
securityLevel The launch DreamDaemonSecurity level.
cancellationToken The CancellationToken for the operation.
Returns
A IEnumerable<T> of Tasks representing the running operations. The first Task returned is always the necessary call to IIOManager.CreateDirectory(string, CancellationToken).
I genuinely don't know how this will work with symlinked files. Waiting for the issue report I guess.
Definition at line 240 of file HardLinkDmbProvider.cs.
        {
            var dir = new DirectoryInfo(src);
            Task? subdirCreationTask = null;
            var dreamDaemonWillAcceptOutOfDirectorySymlinks = securityLevel == DreamDaemonSecurity.Trusted;
            foreach (var subDirectory in dir.EnumerateDirectories())
            {
                var mirroredName = Path.Combine(dest, subDirectory.Name);
                // check if we are a symbolic link
                if (subDirectory.Attributes.HasFlag(FileAttributes.ReparsePoint))
                    if (dreamDaemonWillAcceptOutOfDirectorySymlinks)
                    {
                        var target = subDirectory.ResolveLinkTarget(false)
                            ?? throw new InvalidOperationException($"\"{subDirectory.FullName}\" was incorrectly identified as a symlinked directory!");
                        logger.LogDebug("Recreating directory {name} as symlink to {target}", subDirectory.Name, target);
                        if (subdirCreationTask == null)
{
                            subdirCreationTask = IOManager.CreateDirectory(dest, cancellationToken);
                            yield return subdirCreationTask;
                        }
                        async Task CopyLink()
{
                            await subdirCreationTask.WaitAsync(cancellationToken);
                            using var lockContext = semaphore != null
                                ? await SemaphoreSlimContext.Lock(semaphore, cancellationToken)
                                : null;
                            await LinkFactory.CreateSymbolicLink(target.FullName, mirroredName, cancellationToken);
                        }
                        yield return CopyLink();
                        continue;
                    }
                    else
                        logger.LogDebug("Recreating symlinked directory {name} as hard links...", subDirectory.Name);
                var checkingSubdirCreationTask = true;
                foreach (var copyTask in MirrorDirectoryImpl(subDirectory.FullName, mirroredName, semaphore, securityLevel, cancellationToken))
                {
                    if (subdirCreationTask == null)
                    {
                        subdirCreationTask = copyTask;
                        yield return subdirCreationTask;
                    }
                    else if (!checkingSubdirCreationTask)
                        yield return copyTask;
                    checkingSubdirCreationTask = false;
                }
            }
            foreach (var fileInfo in dir.EnumerateFiles())
            {
                if (subdirCreationTask == null)
                {
                    subdirCreationTask = IOManager.CreateDirectory(dest, cancellationToken);
                    yield return subdirCreationTask;
                }
                var sourceFile = fileInfo.FullName;
                var destFile = IOManager.ConcatPath(dest, fileInfo.Name);
                async Task LinkThisFile()
                {
                    await subdirCreationTask.WaitAsync(cancellationToken);
                    using var lockContext = semaphore != null
                        ? await SemaphoreSlimContext.Lock(semaphore, cancellationToken)
                        : null;
                    if (fileInfo.Attributes.HasFlag(FileAttributes.ReparsePoint))
                    {
                        // AHHHHHHHHHHHHH
                        var target = fileInfo.ResolveLinkTarget(!dreamDaemonWillAcceptOutOfDirectorySymlinks)
                            ?? throw new InvalidOperationException($"\"{fileInfo.FullName}\" was incorrectly identified as a symlinked file!");
                        if (dreamDaemonWillAcceptOutOfDirectorySymlinks)
{
                            logger.LogDebug("Recreating symlinked file {name} as symlink to {target}", fileInfo.Name, target.FullName);
                            await LinkFactory.CreateSymbolicLink(target.FullName, destFile, cancellationToken);
                        }
                        else
{
                            logger.LogDebug("Recreating symlinked file {name} as hard link to {target}", fileInfo.Name, target.FullName);
                            await LinkFactory.CreateHardLink(target.FullName, destFile, cancellationToken);
                        }
                    }
                    else
                        await LinkFactory.CreateHardLink(sourceFile, destFile, cancellationToken);
                }
                yield return LinkThisFile();
            }
        }
References Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.IO.IIOManager.CreateDirectory(), Tgstation.Server.Host.IO.IFilesystemLinkFactory.CreateHardLink(), Tgstation.Server.Host.IO.IFilesystemLinkFactory.CreateSymbolicLink(), Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.IOManager, Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.LinkFactory, Tgstation.Server.Host.Utils.SemaphoreSlimContext.Lock(), Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.logger, and Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.MirrorDirectoryImpl().
Referenced by Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.MirrorDirectoryImpl(), and Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.MirrorSourceDirectory().
MirrorSourceDirectory()
async Task< string?> Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.MirrorSourceDirectory (int? taskThrottle, DreamDaemonSecurity securityLevel, CancellationToken cancellationToken) private
Mirror the Models.CompileJob.
Parameters
taskThrottle The optional maximum number of simultaneous tasks allowed to execute.
securityLevel The launch DreamDaemonSecurity level.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the full path to the mirrored directory.
Definition at line 173 of file HardLinkDmbProvider.cs.
        {
            if (taskThrottle.HasValue && taskThrottle < 1)
                throw new ArgumentOutOfRangeException(nameof(taskThrottle), taskThrottle, "taskThrottle must be at least 1!");
            string? dest = null;
            try
            {
                var stopwatch = Stopwatch.StartNew();
                var mirrorGuid = Guid.NewGuid();
                logger.LogDebug("Starting to mirror {sourceDir} as hard links to {mirrorGuid}...", CompileJob.DirectoryName, mirrorGuid);
                var src = IOManager.ResolvePath(CompileJob.DirectoryName!.Value.ToString());
                dest = IOManager.ResolvePath(mirrorGuid.ToString());
                using var semaphore = taskThrottle.HasValue ? new SemaphoreSlim(taskThrottle.Value) : null;
                await Task.WhenAll(MirrorDirectoryImpl(
                    src,
                    dest,
                    semaphore,
                    securityLevel,
                    cancellationToken));
                stopwatch.Stop();
                logger.LogDebug(
                    "Finished mirror of {sourceDir} to {mirrorGuid} in {seconds}s...",
                    CompileJob.DirectoryName,
                    mirrorGuid,
                    stopwatch.Elapsed.TotalSeconds.ToString("0.##", CultureInfo.InvariantCulture));
            }
            catch (OperationCanceledException ex)
            {
                logger.LogDebug(ex, "Cancelled while mirroring");
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Could not mirror!");
                if (dest != null)
                    try
                    {
                        logger.LogDebug("Cleaning up mirror attempt: {dest}", dest);
                        await IOManager.DeleteDirectory(dest, cancellationToken);
                    }
                    catch (OperationCanceledException ex2)
                    {
                        logger.LogDebug(ex2, "Errored cleanup cancellation edge case!");
                        return dest;
                    }
                return null;
            }
            return dest;
        }
References Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.CompileJob, Tgstation.Server.Host.IO.IIOManager.DeleteDirectory(), Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.IOManager, Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.logger, Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.MirrorDirectoryImpl(), and Tgstation.Server.Host.IO.IIOManager.ResolvePath().
Referenced by Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.HardLinkDmbProvider().
Member Data Documentation
cancellationTokenSource
readonly CancellationTokenSource Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.cancellationTokenSource private
The CancellationTokenSource for mirroringTask.
Definition at line 29 of file HardLinkDmbProvider.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.DisposeAsync(), and Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.HardLinkDmbProvider().
logger
readonly ILogger Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.logger private
The ILogger for the HardLinkDmbProvider.
Definition at line 39 of file HardLinkDmbProvider.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.DisposeAsync(), Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.DoSwap(), Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.FinishActivationPreparation(), Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.HardLinkDmbProvider(), Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.MirrorDirectoryImpl(), and Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.MirrorSourceDirectory().
mirroringTask
readonly Task<string?> Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.mirroringTask private
The Task representing the base provider mirroring operation.
Definition at line 34 of file HardLinkDmbProvider.cs.
Referenced by Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.DisposeAsync(), Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.DoSwap(), Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.FinishActivationPreparation(), and Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.HardLinkDmbProvider().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Deployment/HardLinkDmbProvider.cs