tgstation-server: Tgstation.Server.Host.Authority.Core.RestAuthorityInvoker< TAuthority > Class Template Reference
Tgstation.Server.Host.Authority.Core.RestAuthorityInvoker< TAuthority > Class Template Reference sealed
Public Member Functions
RestAuthorityInvoker (TAuthority authority, IAuthorizationService authorizationService)
Initializes a new instance of the RestAuthorityInvoker<TAuthority> class.
Public Member Functions inherited from Tgstation.Server.Host.Authority.Core.AuthorityInvokerBase< TAuthority >
AuthorityInvokerBase (TAuthority authority, Security.IAuthorizationService authorizationService)
Initializes a new instance of the AuthorityInvokerBase<TAuthority> class.
Private Member Functions
async ValueTask< IActionResult > IRestAuthorityInvoker< TAuthority >. Invoke (ApiController controller, Func< TAuthority, RequirementsGated< AuthorityResponse > > authorityInvoker)
Invoke a TAuthority method with no success result.
Parameters
controller The ApiController invoking the TAuthority .
authorityInvoker The TAuthority Func<T, TResult> resulting in the RequirementsGated<TResult> AuthorityResponse.
Returns
A ValueTask<TResult> resulting in the IActionResult generated for the resulting AuthorityResponse.
async ValueTask< IActionResult > IRestAuthorityInvoker< TAuthority >. Invoke< TResult, TApiModel > (ApiController controller, Func< TAuthority, RequirementsGated< AuthorityResponse< TResult > > > authorityInvoker)
Invoke a TAuthority method and get the result.
Template Parameters
TResult The AuthorityResponse<TResult>.Result Type.
TApiModel The resulting Type of the IActionResult.
Parameters
controller The ApiController invoking the TAuthority .
authorityInvoker The TAuthority Func<T, TResult> resulting in the RequirementsGated<TResult> AuthorityResponse<TResult>.
Returns
A ValueTask<TResult> resulting in the IActionResult generated for the resulting AuthorityResponse<TResult>.
async ValueTask< IActionResult > IRestAuthorityInvoker< TAuthority >. InvokeTransformable< TResult, TApiModel > (ApiController controller, Func< TAuthority, RequirementsGated< AuthorityResponse< TResult > > > authorityInvoker)
Invoke a TAuthority method and get the result.
Template Parameters
TResult The AuthorityResponse<TResult>.Result Type.
TApiModel The returned REST Type.
Parameters
controller The ApiController invoking the TAuthority .
authorityInvoker The TAuthority Func<T, TResult> resulting in the RequirementsGated<TResult> AuthorityResponse<TResult>.
Returns
A ValueTask<TResult> resulting in the IActionResult generated for the resulting AuthorityResponse<TResult>.
Static Private Member Functions
static IActionResult CreateSuccessfulActionResult< TResult, TApiModel > (ApiController controller, Func< TResult, TApiModel > resultTransformer, AuthorityResponse< TResult > authorityResponse)
Create an IActionResult for a given successfulyauthorityResponse .
static ? IActionResult CreateErroredActionResult (ApiController controller, AuthorityResponse? authorityResponse)
Create an IActionResult for a given authorityResponse if it is erroring.
Additional Inherited Members
Protected Member Functions inherited from Tgstation.Server.Host.Authority.Core.AuthorityInvokerBase< TAuthority >
async ValueTask< TResult?> ExecuteIfRequirementsSatisfied< TResult > (RequirementsGated< TResult > requirementsGate)
Unwrap a RequirementsGated<TResult> result, returning null if the requirements weren't satisfied.
virtual void OnRequirementsFailure (AuthorizationFailure authFailure)
Called to handle generic behavior when requirements evaluation fails.
Properties inherited from Tgstation.Server.Host.Authority.Core.AuthorityInvokerBase< TAuthority >
TAuthority Authority [get]
The IAuthority being invoked.
Detailed Description
Type Constraints
TAuthority : IAuthority
Definition at line 14 of file RestAuthorityInvoker{TAuthority}.cs.
Constructor & Destructor Documentation
RestAuthorityInvoker()
Tgstation.Server.Host.Authority.Core.RestAuthorityInvoker< TAuthority >.RestAuthorityInvoker (TAuthority authority, IAuthorizationService authorizationService)
Initializes a new instance of the RestAuthorityInvoker<TAuthority> class.
Parameters
authority The TAuthority .
authorizationService The IAuthorizationService to use.
Definition at line 87 of file RestAuthorityInvoker{TAuthority}.cs.
            : base(authority, authorizationService)
        {
        }
Member Function Documentation
CreateErroredActionResult()
static ? IActionResult Tgstation.Server.Host.Authority.Core.RestAuthorityInvoker< TAuthority >.CreateErroredActionResult (ApiController controller, AuthorityResponse? authorityResponse) static private
Create an IActionResult for a given authorityResponse if it is erroring.
Parameters
controller The ApiController to use.
authorityResponse The AuthorityResponse.
Returns
An IActionResult if the authorityResponse is not successful, null otherwise. If null is returned, authorityResponse is not null.
Definition at line 52 of file RestAuthorityInvoker{TAuthority}.cs.
        {
            if (authorityResponse == null)
                return controller.Forbid();
            if (authorityResponse.Success)
                return null;
            var errorMessage = authorityResponse.ErrorMessage;
            var failureResponse = authorityResponse.FailureResponse;
            return failureResponse switch
            {
                HttpFailureResponse.BadRequest => controller.BadRequest(errorMessage),
                HttpFailureResponse.Unauthorized => controller.Unauthorized(),
                HttpFailureResponse.Forbidden => controller.Forbid(),
                HttpFailureResponse.NotFound => controller.NotFound(errorMessage),
                HttpFailureResponse.NotAcceptable => controller.StatusCode(HttpStatusCode.NotAcceptable, errorMessage),
                HttpFailureResponse.Conflict => controller.Conflict(errorMessage),
                HttpFailureResponse.Gone => controller.StatusCode(HttpStatusCode.Gone, errorMessage),
                HttpFailureResponse.UnprocessableEntity => controller.UnprocessableEntity(errorMessage),
                HttpFailureResponse.FailedDependency => controller.StatusCode(HttpStatusCode.FailedDependency, errorMessage),
                HttpFailureResponse.RateLimited => controller.StatusCode(HttpStatusCode.TooManyRequests, errorMessage),
                HttpFailureResponse.NotImplemented => controller.StatusCode(HttpStatusCode.NotImplemented, errorMessage),
                HttpFailureResponse.ServiceUnavailable => controller.StatusCode(HttpStatusCode.ServiceUnavailable, errorMessage),
                _ => throw new InvalidOperationException($"Invalid {nameof(HttpFailureResponse)}: {failureResponse}"),
            };
        }
References Tgstation.Server.Host.Authority.Core.AuthorityResponse< TResult >.ErrorMessage, Tgstation.Server.Host.Authority.Core.AuthorityResponse< TResult >.FailureResponse, Tgstation.Server.Host.Controllers.ApiController.NotFound(), Tgstation.Server.Host.Controllers.ApiController.StatusCode(), and Tgstation.Server.Host.Authority.Core.AuthorityResponse< TResult >.Success.
Referenced by Tgstation.Server.Host.Authority.Core.RestAuthorityInvoker< TAuthority >.Invoke(), Tgstation.Server.Host.Authority.Core.RestAuthorityInvoker< TAuthority >.Invoke< TResult, TApiModel >(), and Tgstation.Server.Host.Authority.Core.RestAuthorityInvoker< TAuthority >.InvokeTransformable< TResult, TApiModel >().
CreateSuccessfulActionResult< TResult, TApiModel >()
static IActionResult Tgstation.Server.Host.Authority.Core.RestAuthorityInvoker< TAuthority >.CreateSuccessfulActionResult< TResult, TApiModel > (ApiController controller, Func< TResult, TApiModel > resultTransformer, AuthorityResponse< TResult > authorityResponse) static private
Create an IActionResult for a given successfulyauthorityResponse .
Parameters
controller The ApiController to use.
resultTransformer A Func<T, TResult> transforming the TResult from the authorityResponse into the TApiModel .
authorityResponse The AuthorityResponse<TResult>.
Returns
An IActionResult for the authorityResponse .
Template Parameters
TResult The result Type returned in the authorityResponse .
TApiModel The REST API result model built from authorityResponse .
Type Constraints
TApiModel : notnull
Definition at line 26 of file RestAuthorityInvoker{TAuthority}.cs.
                            : notnull
        {
            if (authorityResponse.IsNoContent!.Value)
                return controller.NoContent();
            var successResponse = authorityResponse.SuccessResponse;
            var result = resultTransformer(authorityResponse.Result!);
            return successResponse switch
            {
                HttpSuccessResponse.Ok => controller.Json(result),
                HttpSuccessResponse.Created => controller.Created(result),
                HttpSuccessResponse.Accepted => controller.Accepted(result),
                _ => throw new InvalidOperationException($"Invalid {nameof(HttpSuccessResponse)}: {successResponse}"),
            };
        }
Invoke()
async ValueTask< IActionResult > IRestAuthorityInvoker< TAuthority >. Tgstation.Server.Host.Authority.Core.RestAuthorityInvoker< TAuthority >.Invoke (ApiController controller, Func< TAuthority, RequirementsGated< AuthorityResponse > > authorityInvoker) private
Invoke a TAuthority method with no success result.
Parameters
controller The ApiController invoking the TAuthority .
authorityInvoker The TAuthority Func<T, TResult> resulting in the RequirementsGated<TResult> AuthorityResponse.
Returns
A ValueTask<TResult> resulting in the IActionResult generated for the resulting AuthorityResponse.
Implements Tgstation.Server.Host.Authority.IRestAuthorityInvoker< TAuthority >.
Definition at line 93 of file RestAuthorityInvoker{TAuthority}.cs.
        {
            ArgumentNullException.ThrowIfNull(controller);
            ArgumentNullException.ThrowIfNull(authorityInvoker);
            var requirementsGate = authorityInvoker(Authority);
            var authorityResponse = await ExecuteIfRequirementsSatisfied(requirementsGate);
            return CreateErroredActionResult(controller, authorityResponse) ?? controller.NoContent();
        }
References Tgstation.Server.Host.Authority.Core.AuthorityInvokerBase< TAuthority >.Authority, and Tgstation.Server.Host.Authority.Core.RestAuthorityInvoker< TAuthority >.CreateErroredActionResult().
Invoke< TResult, TApiModel >()
async ValueTask< IActionResult > IRestAuthorityInvoker< TAuthority >. Tgstation.Server.Host.Authority.Core.RestAuthorityInvoker< TAuthority >.Invoke< TResult, TApiModel > (ApiController controller, Func< TAuthority, RequirementsGated< AuthorityResponse< TResult > > > authorityInvoker) private
Invoke a TAuthority method and get the result.
Template Parameters
TResult The AuthorityResponse<TResult>.Result Type.
TApiModel The resulting Type of the IActionResult.
Parameters
controller The ApiController invoking the TAuthority .
authorityInvoker The TAuthority Func<T, TResult> resulting in the RequirementsGated<TResult> AuthorityResponse<TResult>.
Returns
A ValueTask<TResult> resulting in the IActionResult generated for the resulting AuthorityResponse<TResult>.
Implements Tgstation.Server.Host.Authority.IRestAuthorityInvoker< TAuthority >.
Definition at line 104 of file RestAuthorityInvoker{TAuthority}.cs.
        {
            ArgumentNullException.ThrowIfNull(controller);
            ArgumentNullException.ThrowIfNull(authorityInvoker);
            var requirementsGate = authorityInvoker(Authority);
            var authorityResponse = await ExecuteIfRequirementsSatisfied(requirementsGate);
            var erroredResult = CreateErroredActionResult(controller, authorityResponse);
            if (erroredResult != null)
                return erroredResult;
            return CreateSuccessfulActionResult(controller, result => result, authorityResponse!);
        }
References Tgstation.Server.Host.Authority.Core.AuthorityInvokerBase< TAuthority >.Authority, and Tgstation.Server.Host.Authority.Core.RestAuthorityInvoker< TAuthority >.CreateErroredActionResult().
InvokeTransformable< TResult, TApiModel >()
async ValueTask< IActionResult > IRestAuthorityInvoker< TAuthority >. Tgstation.Server.Host.Authority.Core.RestAuthorityInvoker< TAuthority >.InvokeTransformable< TResult, TApiModel > (ApiController controller, Func< TAuthority, RequirementsGated< AuthorityResponse< TResult > > > authorityInvoker) private
Invoke a TAuthority method and get the result.
Template Parameters
TResult The AuthorityResponse<TResult>.Result Type.
TApiModel The returned REST Type.
Parameters
controller The ApiController invoking the TAuthority .
authorityInvoker The TAuthority Func<T, TResult> resulting in the RequirementsGated<TResult> AuthorityResponse<TResult>.
Returns
A ValueTask<TResult> resulting in the IActionResult generated for the resulting AuthorityResponse<TResult>.
Implements Tgstation.Server.Host.Authority.IRestAuthorityInvoker< TAuthority >.
Definition at line 119 of file RestAuthorityInvoker{TAuthority}.cs.
        {
            ArgumentNullException.ThrowIfNull(controller);
            ArgumentNullException.ThrowIfNull(authorityInvoker);
            var requirementsGate = authorityInvoker(Authority);
            var authorityResponse = await ExecuteIfRequirementsSatisfied(requirementsGate);
            var erroredResult = CreateErroredActionResult(controller, authorityResponse);
            if (erroredResult != null)
                return erroredResult;
            return CreateSuccessfulActionResult(controller, result => result.ToApi(), authorityResponse!);
        }
References Tgstation.Server.Host.Authority.Core.AuthorityInvokerBase< TAuthority >.Authority, and Tgstation.Server.Host.Authority.Core.RestAuthorityInvoker< TAuthority >.CreateErroredActionResult().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Authority/Core/RestAuthorityInvoker{TAuthority}.cs