tgstation-server: Tgstation.Server.Tests.Instance.ConfigurationTest Class Reference
Tgstation.Server.Tests.Instance.ConfigurationTest Class Reference
Public Member Functions
ConfigurationTest (IConfigurationClient configurationClient, Api.Models.Instance instance)
async Task Run (CancellationToken cancellationToken)
Private Member Functions
bool FileExists (ConfigurationFile file)
async Task TestDeleteDirectory (CancellationToken cancellationToken)
Private Attributes
readonly IConfigurationClient configurationClient
readonly Api.Models.Instance instance
Detailed Description
Definition at line 13 of file ConfigurationTest.cs.
Constructor & Destructor Documentation
ConfigurationTest()
Tgstation.Server.Tests.Instance.ConfigurationTest.ConfigurationTest (IConfigurationClient configurationClient, Api.Models.Instance instance)
Definition at line 18 of file ConfigurationTest.cs.
         {
             this.configurationClient = configurationClient ?? throw new ArgumentNullException(nameof(configurationClient));
             this.instance = instance ?? throw new ArgumentNullException(nameof(instance));
         }
References Tgstation.Server.Tests.Instance.ConfigurationTest.configurationClient, and Tgstation.Server.Tests.Instance.ConfigurationTest.instance.
Member Function Documentation
FileExists()
bool Tgstation.Server.Tests.Instance.ConfigurationTest.FileExists (ConfigurationFile file) private
Definition at line 24 of file ConfigurationTest.cs.
         {
             var tmp = (file.Path?.StartsWith('/') ?? false) ? '.' + file.Path : file.Path;
             var path = Path.Combine(instance.Path, "Configuration", tmp);
             return File.Exists(path);
         }
References Tgstation.Server.Tests.Instance.ConfigurationTest.instance, Tgstation.Server.Api.Models.ConfigurationFile.Path, and Tgstation.Server.Api.Models.Instance.Path.
Referenced by Tgstation.Server.Tests.Instance.ConfigurationTest.TestDeleteDirectory().
Run()
async Task Tgstation.Server.Tests.Instance.ConfigurationTest.Run (CancellationToken cancellationToken)
Definition at line 58 of file ConfigurationTest.cs.
         {
             await TestDeleteDirectory(cancellationToken).ConfigureAwait(false);
         }
References Tgstation.Server.Tests.Instance.ConfigurationTest.TestDeleteDirectory().
TestDeleteDirectory()
async Task Tgstation.Server.Tests.Instance.ConfigurationTest.TestDeleteDirectory (CancellationToken cancellationToken) private
Definition at line 31 of file ConfigurationTest.cs.
         {
             //try to delete non-existent
             var TestDir = new ConfigurationFile
             {
                 Path = "/TestDeleteDir"
             };
             await configurationClient.DeleteEmptyDirectory(TestDir, cancellationToken).ConfigureAwait(false);
             //try to delete non-empty
             var file = await configurationClient.Write(new ConfigurationFile
             {
                 Content = Encoding.UTF8.GetBytes("Hello world!"),
                 Path = TestDir.Path + "/test.txt"
             }, cancellationToken).ConfigureAwait(false);
             Assert.IsTrue(FileExists(file));
             await Assert.ThrowsExceptionAsync<ConflictException>(() => configurationClient.DeleteEmptyDirectory(TestDir, cancellationToken)).ConfigureAwait(false);
             file.Content = null;
             await configurationClient.Write(file, cancellationToken).ConfigureAwait(false);
             await configurationClient.DeleteEmptyDirectory(TestDir, cancellationToken).ConfigureAwait(false);
         }
References Tgstation.Server.Tests.Instance.ConfigurationTest.configurationClient, Tgstation.Server.Client.Components.IConfigurationClient.DeleteEmptyDirectory(), Tgstation.Server.Tests.Instance.ConfigurationTest.FileExists(), Tgstation.Server.Api.Models.ConfigurationFile.Path, and Tgstation.Server.Client.Components.IConfigurationClient.Write().
Referenced by Tgstation.Server.Tests.Instance.ConfigurationTest.Run().
Member Data Documentation
configurationClient
readonly IConfigurationClient Tgstation.Server.Tests.Instance.ConfigurationTest.configurationClient private
Definition at line 15 of file ConfigurationTest.cs.
Referenced by Tgstation.Server.Tests.Instance.ConfigurationTest.ConfigurationTest(), and Tgstation.Server.Tests.Instance.ConfigurationTest.TestDeleteDirectory().
instance
readonly Api.Models.Instance Tgstation.Server.Tests.Instance.ConfigurationTest.instance private
Definition at line 16 of file ConfigurationTest.cs.
Referenced by Tgstation.Server.Tests.Instance.ConfigurationTest.ConfigurationTest(), and Tgstation.Server.Tests.Instance.ConfigurationTest.FileExists().
The documentation for this class was generated from the following file:
tests/Tgstation.Server.Tests/Instance/ConfigurationTest.cs