tgstation-server: Tgstation.Server.Host.Program Class Reference
Tgstation.Server.Host.Program Class Reference sealed
Entrypoint for the Process.
Public Member Functions
Program ()
Initializes a new instance of the Program class.
Static Public Member Functions
static async Task< int > Main (string[] args)
Entrypoint for the Program.
Static Private Member Functions
static ? string TopLevelArgsParse (ref string[] args)
Parse Program top level args .
Detailed Description
Entrypoint for the Process.
Definition at line 19 of file Program.cs.
Constructor & Destructor Documentation
Program()
Tgstation.Server.Host.Program.Program ()
Initializes a new instance of the Program class.
Definition at line 34 of file Program.cs.
        {
            ServerFactory = Application.CreateDefaultServerFactory();
        }
Referenced by Tgstation.Server.Host.Program.Main().
Member Function Documentation
Main()
static async Task< int > Tgstation.Server.Host.Program.Main (string[] args) static
Entrypoint for the Program.
Parameters
args The command line arguments.
Returns
A Task resulting in the global::System.Diagnostics.Process.ExitCode.
Definition at line 44 of file Program.cs.
        {
            // first arg is 100% always the update path, starting it otherwise is solely for debugging purposes
            var updatePath = TopLevelArgsParse(ref args);
            var program = new Program();
            return (int)await program.Main(args, updatePath);
        }
References Tgstation.Server.Host.Program.Program(), and Tgstation.Server.Host.Program.TopLevelArgsParse().
TopLevelArgsParse()
static ? string Tgstation.Server.Host.Program.TopLevelArgsParse (ref string[] args) static private
Parse Program top level args .
Parameters
args The arguments Array which may be changed.
Returns
The update path for the server, if present.
Definition at line 58 of file Program.cs.
        {
            if (args.Length == 0)
                return null;
            var potentialUpdatePath = args[0];
            if (potentialUpdatePath.Equals("cli", StringComparison.OrdinalIgnoreCase))
                return null;
            var listArgs = new List<string>(args);
            listArgs.RemoveAt(0);
            // second arg should be host watchdog version
            if (listArgs.Count > 0)
            {
                var expectedHostWatchdogVersion = HostWatchdogVersion;
                if (Version.TryParse(listArgs.First(), out var actualHostWatchdogVersion)
                    && actualHostWatchdogVersion.Major != expectedHostWatchdogVersion.Major)
                    throw new InvalidOperationException(
                        $"Incompatible host watchdog version ({actualHostWatchdogVersion}) for server ({expectedHostWatchdogVersion})! A major update was released and a full restart will be required. Please manually offline your servers!");
            }
            if (listArgs.Remove("--attach-debugger"))
                Debugger.Launch();
            args = [.. listArgs];
            return potentialUpdatePath;
        }
Referenced by Tgstation.Server.Host.Program.Main().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Program.cs