tgstation-server: Tgstation.Server.Host.Controllers.DreamMakerController Class Reference
Tgstation.Server.Host.Controllers.DreamMakerController Class Reference sealed
ApiController for managing the deployment system.
Public Member Functions
DreamMakerController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ILogger< DreamMakerController > logger, IInstanceManager instanceManager, IJobManager jobManager, IPortAllocator portAllocator, IApiHeadersProvider apiHeaders)
Initializes a new instance of the DreamMakerController class.
async ValueTask< IActionResult > Read (CancellationToken cancellationToken)
Read current deployment settings.
async ValueTask< IActionResult > GetId (long id, CancellationToken cancellationToken)
Get a CompileJob specified by a given id .
ValueTask< IActionResult > List ([FromQuery] int? page, [FromQuery] int? pageSize, CancellationToken cancellationToken)
List all CompileJob EntityIds for the instance.
async ValueTask< IActionResult > Create (CancellationToken cancellationToken)
Begin deploying repository code.
async ValueTask< IActionResult > Update ([FromBody] DreamMakerRequest model, CancellationToken cancellationToken)
Update deployment settings.
Public Member Functions inherited from Tgstation.Server.Host.Controllers.ApiControllerBase
override async Task OnActionExecutionAsync (ActionExecutingContext context, ActionExecutionDelegate next)
Private Member Functions
ValueTask< IActionResult > CompileJobResponse (()=> ValueTask.FromResult(new PaginatableResult< CompileJob >(BaseCompileJobsQuery() .OrderByDescending(x=> x.Job.StoppedAt))), null, page, pageSize, cancellationToken)
IQueryable< CompileJob > BaseCompileJobsQuery ()
Base query for pulling in all required CompileJob fields.
Private Attributes
readonly IJobManager jobManager
The IJobManager for the DreamMakerController.
readonly IPortAllocator portAllocator
The IPortAllocator for the DreamMakerController.
Additional Inherited Members
Protected Member Functions inherited from Tgstation.Server.Host.Controllers.InstanceRequiredController
InstanceRequiredController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ILogger< InstanceRequiredController > logger, IInstanceManager instanceManager, IApiHeadersProvider apiHeaders)
Initializes a new instance of the InstanceRequiredController class.
Protected Member Functions inherited from Tgstation.Server.Host.Controllers.ComponentInterfacingController
ComponentInterfacingController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ILogger< ComponentInterfacingController > logger, IInstanceManager instanceManager, IApiHeadersProvider apiHeaders, bool useInstanceRequestHeader)
Initializes a new instance of the ComponentInterfacingController class.
override async ValueTask< IActionResult?> ValidateRequest (CancellationToken cancellationToken)
Performs validation a request.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in an appropriate IActionResult on validation failure, null otherwise.
bool ValidateInstanceOnlineStatus (Api.Models.Instance metadata)
Corrects discrepencies between the Api.Models.Instance.Online status of IInstances in the database vs the service.
async ValueTask< IActionResult?> WithComponentInstanceNullable (Func< IInstanceCore, ValueTask< IActionResult?> > action, Models.Instance? instance=null)
Run a given action with the relevant IInstance.
async ValueTask< IActionResult > WithComponentInstance (Func< IInstanceCore, ValueTask< IActionResult > > action, Models.Instance? instance=null)
Run a given action with the relevant IInstance.
Protected Member Functions inherited from Tgstation.Server.Host.Controllers.ApiController
ApiController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, IApiHeadersProvider apiHeadersProvider, ILogger< ApiController > logger, bool requireHeaders)
Initializes a new instance of the ApiController class.
override async ValueTask< IActionResult?> HookExecuteAction (Func< Task > executeAction, CancellationToken cancellationToken)
Hook for executing a request.
Parameters
executeAction A Func<TResult> that should be invoked and its response awaited to continue normal execution of the request. Should NOT be called if this method returns a non-null value.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in an IActionResult that, if not null, is executed.
new NotFoundObjectResult NotFound ()
Generic 404 response.
new ObjectResult Unauthorized ()
Generic 401 response.
ObjectResult RequiresPosixSystemIdentity (NotImplementedException ex)
Generic 501 response.
StatusCodeResult StatusCode (HttpStatusCode statusCode)
Strongly type calls to ControllerBase.StatusCode(int).
ObjectResult Created (object payload)
Generic 201 response with a given payload .
ObjectResult RateLimit (RateLimitExceededException rateLimitException)
429 response for a given rateLimitException .
IActionResult HeadersIssue (HeadersException headersException)
Response for missing/Invalid headers.
ValueTask< IActionResult > Paginated< TModel > (Func< ValueTask< PaginatableResult< TModel > > > queryGenerator, Func< TModel, ValueTask >? resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
ValueTask< IActionResult > Paginated< TModel, TApiModel > (Func< ValueTask< PaginatableResult< TModel > > > queryGenerator, Func< TApiModel, ValueTask >? resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
Properties inherited from Tgstation.Server.Host.Controllers.InstanceRequiredController
new Models.Instance Instance [get]
The ApiController.Instance.
Models.InstancePermissionSet InstancePermissionSet [get]
The Models.InstancePermissionSet for the request.
Properties inherited from Tgstation.Server.Host.Controllers.ComponentInterfacingController
IInstanceOperations InstanceOperations [get]
Access the IInstanceOperations instance.
Properties inherited from Tgstation.Server.Host.Controllers.ApiController
ApiHeaders? ApiHeaders [get]
The Api.ApiHeaders for the operation.
IApiHeadersProvider ApiHeadersProvider [get]
The IApiHeadersProvider containing value of ApiHeaders.
IDatabaseContext DatabaseContext [get]
The IDatabaseContext for the operation.
IAuthenticationContext AuthenticationContext [get]
The IAuthenticationContext for the operation.
ILogger< ApiController > Logger [get]
The ILogger for the ApiController.
Models.? Instance Instance [get]
The Instance for the operation.
Detailed Description
ApiController for managing the deployment system.
Definition at line 30 of file DreamMakerController.cs.
Constructor & Destructor Documentation
DreamMakerController()
Tgstation.Server.Host.Controllers.DreamMakerController.DreamMakerController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ILogger< DreamMakerController > logger, IInstanceManager instanceManager, IJobManager jobManager, IPortAllocator portAllocator, IApiHeadersProvider apiHeaders)
Initializes a new instance of the DreamMakerController class.
Parameters
databaseContext The IDatabaseContext for the InstanceRequiredController.
authenticationContext The IAuthenticationContext for the InstanceRequiredController.
logger The ILogger for the InstanceRequiredController.
instanceManager The IInstanceManager for the InstanceRequiredController.
jobManager The value of jobManager.
portAllocator The value of IPortAllocator.
apiHeaders The IApiHeadersProvider for the InstanceRequiredController.
Definition at line 52 of file DreamMakerController.cs.
            : base(
                  databaseContext,
                  authenticationContext,
                  logger,
                  instanceManager,
                  apiHeaders)
        {
            this.jobManager = jobManager ?? throw new ArgumentNullException(nameof(jobManager));
            this.portAllocator = portAllocator ?? throw new ArgumentNullException(nameof(portAllocator));
        }
References Tgstation.Server.Host.Controllers.DreamMakerController.jobManager, Tgstation.Server.Api.Rights.List, and Tgstation.Server.Host.Controllers.DreamMakerController.portAllocator.
Member Function Documentation
BaseCompileJobsQuery()
IQueryable< CompileJob > Tgstation.Server.Host.Controllers.DreamMakerController.BaseCompileJobsQuery () private
Base query for pulling in all required CompileJob fields.
Returns
An IQueryable<T> of CompileJob with all the inclusions.
Referenced by Tgstation.Server.Host.Controllers.DreamMakerController.GetId().
CompileJobResponse()
ValueTask< IActionResult > Tgstation.Server.Host.Controllers.DreamMakerController.CompileJobResponse (() , ValueTask. FromResultnew PaginatableResult< CompileJob >(BaseCompileJobsQuery() .OrderByDescending(x=> x.Job.StoppedAt)), null , page , pageSize , cancellationToken) private
Create()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.DreamMakerController.Create (CancellationToken cancellationToken)
Begin deploying repository code.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the request.
<response code="202">Created deployment JobResponse successfully.</response>
Definition at line 147 of file DreamMakerController.cs.
        {
            var job = Job.Create(JobCode.Deployment, AuthenticationContext.User, Instance, DreamMakerRights.CancelCompile);
            await jobManager.RegisterOperation(
                job,
                (core, databaseContextFactory, paramJob, progressReporter, jobCancellationToken)
                    => core!.DreamMaker.DeploymentProcess(paramJob, databaseContextFactory, progressReporter, jobCancellationToken),
                cancellationToken);
            return Accepted(job.ToApi());
        }
References Tgstation.Server.Host.Models.Job.Create(), Tgstation.Server.Api.Rights.DreamMaker, Tgstation.Server.Host.Controllers.DreamMakerController.jobManager, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Jobs.IJobManager.RegisterOperation(), and Tgstation.Server.Host.Security.AuthenticationContext.User.
GetId()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.DreamMakerController.GetId (long id, CancellationToken cancellationToken)
Get a CompileJob specified by a given id .
Parameters
id The EntityId.Id.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the request.
<response code="200">CompileJob retrieved successfully.</response> <response code="404">Specified CompileJob ID does not exist in this instance.</response>
Definition at line 106 of file DreamMakerController.cs.
        {
            var compileJob = await BaseCompileJobsQuery()
                .Where(x => x.Id == id)
                .FirstOrDefaultAsync(cancellationToken);
            if (compileJob == default)
                return NotFound();
            return Json(compileJob.ToApi());
        }
References Tgstation.Server.Host.Controllers.DreamMakerController.BaseCompileJobsQuery(), Tgstation.Server.Api.Rights.List, and Tgstation.Server.Host.Controllers.ApiController.NotFound().
List()
ValueTask< IActionResult > Tgstation.Server.Host.Controllers.DreamMakerController.List ([FromQuery] int? page, [FromQuery] int? pageSize, CancellationToken cancellationToken)
List all CompileJob EntityIds for the instance.
Parameters
page The current page.
pageSize The page size.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the request.
<response code="200">Retrieved EntityIds successfully.</response>
Read()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.DreamMakerController.Read (CancellationToken cancellationToken)
Read current deployment settings.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the request.
<response code="200">Read deployment settings successfully.</response>
Definition at line 80 of file DreamMakerController.cs.
        {
            var dreamMakerSettings = await DatabaseContext
                .DreamMakerSettings
                .AsQueryable()
                .Where(x => x.InstanceId == Instance.Id)
                .FirstOrDefaultAsync(cancellationToken);
            if (dreamMakerSettings == null)
                return this.Gone();
            return Json(dreamMakerSettings.ToApi());
        }
References Tgstation.Server.Host.Database.DatabaseContext.DreamMakerSettings, Tgstation.Server.Api.Models.EntityId.Id, and Tgstation.Server.Api.Rights.List.
Update()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.DreamMakerController.Update ([FromBody] DreamMakerRequest model, CancellationToken cancellationToken)
Update deployment settings.
Parameters
model The DreamMakerRequest.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the request.
<response code="200">Changes applied successfully. The updated DreamMakerSettings will be returned.</response> <response code="204">Changes applied successfully. The updated DreamMakerSettings will be not be returned due to permissions.</response> <response code="410">The database entity for the requested instance could not be retrieved. The instance was likely detached.</response>
Definition at line 180 of file DreamMakerController.cs.
        {
            ArgumentNullException.ThrowIfNull(model);
            if (model.ApiValidationPort == 0)
                throw new InvalidOperationException("ApiValidationPort cannot be 0!");
            var hostModel = await DatabaseContext
                .DreamMakerSettings
                .AsQueryable()
                .Where(x => x.InstanceId == Instance.Id)
                .FirstOrDefaultAsync(cancellationToken);
            if (hostModel == null)
                return this.Gone();
            var dreamMakerRights = InstancePermissionSet.DreamMakerRights!.Value;
            if (model.ProjectName != null)
            {
                if (!dreamMakerRights.HasFlag(DreamMakerRights.SetDme))
                    return Forbid();
                if (model.ProjectName.Length == 0) // can't use isnullorwhitespace because linux memes
                    hostModel.ProjectName = null;
                else
                    hostModel.ProjectName = model.ProjectName;
            }
            if (model.ApiValidationPort.HasValue)
            {
                if (!dreamMakerRights.HasFlag(DreamMakerRights.SetApiValidationPort))
                    return Forbid();
                if (model.ApiValidationPort.Value != hostModel.ApiValidationPort!.Value)
                {
                    Logger.LogTrace(
                        "Triggering port allocator for DM-I:{instanceId} because model port {modelPort} doesn't match DB port {dbPort}...",
                        Instance.Id,
                        model.ApiValidationPort,
                        hostModel.ApiValidationPort);
                    var verifiedPort = await portAllocator
                        .GetAvailablePort(
                            model.ApiValidationPort.Value,
                            true,
                            cancellationToken);
                    if (verifiedPort != model.ApiValidationPort)
                        return Conflict(new ErrorMessageResponse(ErrorCode.PortNotAvailable));
                    hostModel.ApiValidationPort = model.ApiValidationPort;
                }
            }
            if (model.ApiValidationSecurityLevel.HasValue)
            {
                if (!dreamMakerRights.HasFlag(DreamMakerRights.SetSecurityLevel))
                    return Forbid();
                hostModel.ApiValidationSecurityLevel = model.ApiValidationSecurityLevel;
            }
            if (model.RequireDMApiValidation.HasValue)
            {
                if (!dreamMakerRights.HasFlag(DreamMakerRights.SetApiValidationRequirement))
                    return Forbid();
                hostModel.RequireDMApiValidation = model.RequireDMApiValidation;
            }
            if (model.Timeout.HasValue)
            {
                if (!dreamMakerRights.HasFlag(DreamMakerRights.SetTimeout))
                    return Forbid();
                hostModel.Timeout = model.Timeout;
            }
            if (model.CompilerAdditionalArguments != null)
            {
                if (!dreamMakerRights.HasFlag(DreamMakerRights.SetCompilerArguments))
                    return Forbid();
                var sanitizedArguments = model.CompilerAdditionalArguments.Trim();
                if (sanitizedArguments.Length == 0)
                    hostModel.CompilerAdditionalArguments = null;
                else
                    hostModel.CompilerAdditionalArguments = sanitizedArguments;
            }
            await DatabaseContext.Save(cancellationToken);
            if (!dreamMakerRights.HasFlag(DreamMakerRights.Read))
                return NoContent();
            return await Read(cancellationToken);
        }
References Tgstation.Server.Api.Models.Internal.InstancePermissionSet.DreamMakerRights, Tgstation.Server.Host.Database.DatabaseContext.DreamMakerSettings, Tgstation.Server.Host.Utils.IPortAllocator.GetAvailablePort(), Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Controllers.ApiController.Logger, Tgstation.Server.Host.Controllers.DreamMakerController.portAllocator, Tgstation.Server.Api.Rights.Read, and Tgstation.Server.Host.Database.DatabaseContext.Save().
Member Data Documentation
jobManager
readonly IJobManager Tgstation.Server.Host.Controllers.DreamMakerController.jobManager private
The IJobManager for the DreamMakerController.
Definition at line 35 of file DreamMakerController.cs.
Referenced by Tgstation.Server.Host.Controllers.DreamMakerController.Create(), and Tgstation.Server.Host.Controllers.DreamMakerController.DreamMakerController().
portAllocator
readonly IPortAllocator Tgstation.Server.Host.Controllers.DreamMakerController.portAllocator private
The IPortAllocator for the DreamMakerController.
Definition at line 40 of file DreamMakerController.cs.
Referenced by Tgstation.Server.Host.Controllers.DreamMakerController.DreamMakerController(), and Tgstation.Server.Host.Controllers.DreamMakerController.Update().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Controllers/DreamMakerController.cs