tgstation-server: Tgstation.Server.Host.Components.Repository.Tests.TestRepositoryFactory Class Reference
Tgstation.Server.Host.Components.Repository.Tests.TestRepositoryFactory Class Reference
Tests for LibGit2RepositoryFactory.
Public Member Functions
void TestConstructionThrows ()
void TestInMemoryRepoCreation ()
async Task TestCloning ()
Static Private Member Functions
static ILibGit2RepositoryFactory CreateFactory ()
static Task< LibGit2Sharp.IRepository > TestRepoLoading (string path, ILibGit2RepositoryFactory repositoryFactory=null)
Detailed Description
Tests for LibGit2RepositoryFactory.
Definition at line 15 of file TestRepositoryFactory.cs.
Member Function Documentation
CreateFactory()
static ILibGit2RepositoryFactory Tgstation.Server.Host.Components.Repository.Tests.TestRepositoryFactory.CreateFactory () static private
Referenced by Tgstation.Server.Host.Components.Repository.Tests.TestRepositoryFactory.TestCloning().
TestCloning()
async Task Tgstation.Server.Host.Components.Repository.Tests.TestRepositoryFactory.TestCloning ()
Definition at line 35 of file TestRepositoryFactory.cs.
         {
             var tempDir = Path.GetTempFileName();
             File.Delete(tempDir);
             try
             {
                 var factory = CreateFactory();
                 await factory.Clone(
                     new Uri("https://github.com/Cyberboss/Test"),
                     new CloneOptions
                     {
                         CredentialsProvider = factory.GenerateCredentialsHandler(null, null)
                     },
                     tempDir,
                     default);
                 using (var repo = await TestRepoLoading(tempDir))
                 {
                     var gitObject = repo.Lookup("f636418bf47d238d33b0e4a34f0072b23a8aad0e");
                     Assert.IsNotNull(gitObject);
                     var commit = gitObject.Peel<Commit>();
                     Assert.AreEqual("Update Test.md", commit.Message);
                 }
             }
             finally
             {
                 // Takes a while to release the repo handle sometimes...
                 for (var i = 0; i < 5; ++i)
                 {
                     try
                     {
                         Directory.Delete(tempDir, true);
                         break;
                     }
                     catch (UnauthorizedAccessException)
                     {
                         await Task.Delay(TimeSpan.FromSeconds(3)).ConfigureAwait(false);
                     }
                 }
             }
         }
References Tgstation.Server.Host.Components.Repository.Tests.TestRepositoryFactory.CreateFactory(), and Tgstation.Server.Host.Components.Repository.Tests.TestRepositoryFactory.TestRepoLoading().
TestConstructionThrows()
void Tgstation.Server.Host.Components.Repository.Tests.TestRepositoryFactory.TestConstructionThrows ()
TestInMemoryRepoCreation()
void Tgstation.Server.Host.Components.Repository.Tests.TestRepositoryFactory.TestInMemoryRepoCreation ()
Definition at line 29 of file TestRepositoryFactory.cs.
         {
             new LibGit2RepositoryFactory(Mock.Of<ILogger<LibGit2RepositoryFactory>>()).CreateInMemory().Dispose();
         }
References Tgstation.Server.Host.Components.Repository.LibGit2RepositoryFactory.CreateInMemory().
TestRepoLoading()
static Task<LibGit2Sharp.IRepository> Tgstation.Server.Host.Components.Repository.Tests.TestRepositoryFactory.TestRepoLoading (string path, ILibGit2RepositoryFactory repositoryFactory = null) static private
Referenced by Tgstation.Server.Host.Components.Repository.Tests.TestRepositoryFactory.TestCloning().
The documentation for this class was generated from the following file:
tests/Tgstation.Server.Host.Tests/Components/Repository/TestRepositoryFactory.cs