tgstation-server: Tgstation.Server.Host.Controllers.EngineController Class Reference
Tgstation.Server.Host.Controllers.EngineController Class Reference sealed
Controller for managing engine installations.
Public Member Functions
EngineController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ILogger< EngineController > logger, IInstanceManager instanceManager, IJobManager jobManager, IFileTransferTicketProvider fileTransferService, IApiHeadersProvider apiHeadersProvider)
Initializes a new instance of the EngineController class.
ValueTask< IActionResult > Read ()
Gets the active EngineVersion.
ValueTask< IActionResult > List ([FromQuery] int? page, [FromQuery] int? pageSize, CancellationToken cancellationToken)
Lists installed EngineVersions.
async ValueTask< IActionResult > Update ([FromBody] EngineVersionRequest model, CancellationToken cancellationToken)
Changes the active engine version to the one specified in a given model .
async ValueTask< IActionResult > Delete ([FromBody] EngineVersionDeleteRequest model, CancellationToken cancellationToken)
Attempts to delete the BYOND version specified in a given model from the instance.
Public Member Functions inherited from Tgstation.Server.Host.Controllers.ApiControllerBase
override async Task OnActionExecutionAsync (ActionExecutingContext context, ActionExecutionDelegate next)
Private Member Functions
BadRequestObjectResult? ValidateEngineVersion (EngineVersion? version)
Validate and normalize a given version .
Static Private Member Functions
static Version NormalizeByondVersion (Version version)
Remove the Version.Build from a given version if present.
Private Attributes
readonly IJobManager jobManager
The IJobManager for the EngineController.
readonly IFileTransferTicketProvider fileTransferService
The IFileTransferTicketProvider for the EngineController.
Additional Inherited Members
Protected Member Functions inherited from Tgstation.Server.Host.Controllers.InstanceRequiredController
InstanceRequiredController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ILogger< InstanceRequiredController > logger, IInstanceManager instanceManager, IApiHeadersProvider apiHeaders)
Initializes a new instance of the InstanceRequiredController class.
Protected Member Functions inherited from Tgstation.Server.Host.Controllers.ComponentInterfacingController
ComponentInterfacingController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ILogger< ComponentInterfacingController > logger, IInstanceManager instanceManager, IApiHeadersProvider apiHeaders, bool useInstanceRequestHeader)
Initializes a new instance of the ComponentInterfacingController class.
override async ValueTask< IActionResult?> ValidateRequest (CancellationToken cancellationToken)
Performs validation a request.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in an appropriate IActionResult on validation failure, null otherwise.
bool ValidateInstanceOnlineStatus (Api.Models.Instance metadata)
Corrects discrepencies between the Api.Models.Instance.Online status of IInstances in the database vs the service.
async ValueTask< IActionResult?> WithComponentInstanceNullable (Func< IInstanceCore, ValueTask< IActionResult?> > action, Models.Instance? instance=null)
Run a given action with the relevant IInstance.
async ValueTask< IActionResult > WithComponentInstance (Func< IInstanceCore, ValueTask< IActionResult > > action, Models.Instance? instance=null)
Run a given action with the relevant IInstance.
Protected Member Functions inherited from Tgstation.Server.Host.Controllers.ApiController
ApiController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, IApiHeadersProvider apiHeadersProvider, ILogger< ApiController > logger, bool requireHeaders)
Initializes a new instance of the ApiController class.
override async ValueTask< IActionResult?> HookExecuteAction (Func< Task > executeAction, CancellationToken cancellationToken)
Hook for executing a request.
Parameters
executeAction A Func<TResult> that should be invoked and its response awaited to continue normal execution of the request. Should NOT be called if this method returns a non-null value.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in an IActionResult that, if not null, is executed.
new NotFoundObjectResult NotFound ()
Generic 404 response.
new ObjectResult Unauthorized ()
Generic 401 response.
ObjectResult RequiresPosixSystemIdentity (NotImplementedException ex)
Generic 501 response.
StatusCodeResult StatusCode (HttpStatusCode statusCode)
Strongly type calls to ControllerBase.StatusCode(int).
ObjectResult Created (object payload)
Generic 201 response with a given payload .
ObjectResult RateLimit (RateLimitExceededException rateLimitException)
429 response for a given rateLimitException .
IActionResult HeadersIssue (HeadersException headersException)
Response for missing/Invalid headers.
ValueTask< IActionResult > Paginated< TModel > (Func< ValueTask< PaginatableResult< TModel > > > queryGenerator, Func< TModel, ValueTask >? resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
ValueTask< IActionResult > Paginated< TModel, TApiModel > (Func< ValueTask< PaginatableResult< TModel > > > queryGenerator, Func< TApiModel, ValueTask >? resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
Properties inherited from Tgstation.Server.Host.Controllers.InstanceRequiredController
new Models.Instance Instance [get]
The ApiController.Instance.
Models.InstancePermissionSet InstancePermissionSet [get]
The Models.InstancePermissionSet for the request.
Properties inherited from Tgstation.Server.Host.Controllers.ComponentInterfacingController
IInstanceOperations InstanceOperations [get]
Access the IInstanceOperations instance.
Properties inherited from Tgstation.Server.Host.Controllers.ApiController
ApiHeaders? ApiHeaders [get]
The Api.ApiHeaders for the operation.
IApiHeadersProvider ApiHeadersProvider [get]
The IApiHeadersProvider containing value of ApiHeaders.
IDatabaseContext DatabaseContext [get]
The IDatabaseContext for the operation.
IAuthenticationContext AuthenticationContext [get]
The IAuthenticationContext for the operation.
ILogger< ApiController > Logger [get]
The ILogger for the ApiController.
Models.? Instance Instance [get]
The Instance for the operation.
Detailed Description
Controller for managing engine installations.
Definition at line 32 of file EngineController.cs.
Constructor & Destructor Documentation
EngineController()
Tgstation.Server.Host.Controllers.EngineController.EngineController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ILogger< EngineController > logger, IInstanceManager instanceManager, IJobManager jobManager, IFileTransferTicketProvider fileTransferService, IApiHeadersProvider apiHeadersProvider)
Initializes a new instance of the EngineController class.
Parameters
databaseContext The IDatabaseContext for the InstanceRequiredController.
authenticationContext The IAuthenticationContext for the InstanceRequiredController.
logger The ILogger for the InstanceRequiredController.
instanceManager The IInstanceManager for the InstanceRequiredController.
jobManager The value of jobManager.
fileTransferService The value of fileTransferService.
apiHeadersProvider The IApiHeadersProvider for the InstanceRequiredController.
Definition at line 61 of file EngineController.cs.
            : base(
                  databaseContext,
                  authenticationContext,
                  logger,
                  instanceManager,
                  apiHeadersProvider)
        {
            this.jobManager = jobManager ?? throw new ArgumentNullException(nameof(jobManager));
            this.fileTransferService = fileTransferService ?? throw new ArgumentNullException(nameof(fileTransferService));
        }
References Tgstation.Server.Host.Controllers.EngineController.fileTransferService, Tgstation.Server.Host.Controllers.EngineController.jobManager, and Tgstation.Server.Api.Rights.List.
Member Function Documentation
Delete()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.EngineController.Delete ([FromBody] EngineVersionDeleteRequest model, CancellationToken cancellationToken)
Attempts to delete the BYOND version specified in a given model from the instance.
Parameters
model The EngineVersionDeleteRequest containing the Version to delete.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult for the operation.
<response code="202">Created Job to delete target version successfully.</response> <response code="409">Attempted to delete the active BYOND Version.</response> <response code="410">The EngineVersion specified was not installed.</response>
Definition at line 288 of file EngineController.cs.
        {
            ArgumentNullException.ThrowIfNull(model);
            var earlyOut = ValidateEngineVersion(model.EngineVersion);
            if (earlyOut != null)
                return earlyOut;
            var engineVersion = model.EngineVersion!;
            var notInstalledResponse = await WithComponentInstanceNullable(
                instance =>
                {
                    var byondManager = instance.EngineManager;
                    var activeVersion = byondManager.ActiveVersion;
                    if (activeVersion != null && engineVersion.Equals(activeVersion))
                        return ValueTask.FromResult<IActionResult?>(
                            Conflict(new ErrorMessageResponse(ErrorCode.EngineCannotDeleteActiveVersion)));
                    var versionNotInstalled = !byondManager.InstalledVersions.Any(x => x.Equals(engineVersion));
                    return ValueTask.FromResult<IActionResult?>(
                        versionNotInstalled
                            ? this.Gone()
                            : null);
                });
            if (notInstalledResponse != null)
                return notInstalledResponse;
            var isByondVersion = engineVersion.Engine!.Value == EngineType.Byond;
            // run the install through the job manager
            var cancelRight = isByondVersion
                ? engineVersion.CustomIteration.HasValue
                    ? EngineRights.InstallCustomByondVersion
                    : EngineRights.InstallOfficialOrChangeActiveByondVersion
                : engineVersion.CustomIteration.HasValue
                    ? EngineRights.InstallOfficialOrChangeActiveOpenDreamVersion
                    : EngineRights.InstallCustomOpenDreamVersion;
            var job = Models.Job.Create(JobCode.EngineDelete, AuthenticationContext.User, Instance, cancelRight);
            job.Description += $" {engineVersion}";
            await jobManager.RegisterOperation(
                job,
                (instanceCore, databaseContextFactory, job, progressReporter, jobCancellationToken)
                    => instanceCore!.EngineManager.DeleteVersion(progressReporter, engineVersion, jobCancellationToken),
                cancellationToken);
            var apiResponse = job.ToApi();
            return Accepted(apiResponse);
        }
References Tgstation.Server.Host.Controllers.EngineController.jobManager, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Jobs.IJobManager.RegisterOperation(), Tgstation.Server.Host.Security.AuthenticationContext.User, Tgstation.Server.Host.Controllers.EngineController.ValidateEngineVersion(), and Tgstation.Server.Host.Controllers.ComponentInterfacingController.WithComponentInstanceNullable().
List()
ValueTask< IActionResult > Tgstation.Server.Host.Controllers.EngineController.List ([FromQuery] int? page, [FromQuery] int? pageSize, CancellationToken cancellationToken)
Lists installed EngineVersions.
Parameters
page The current page.
pageSize The page size.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult for the operation.
<response code="200">Retrieved version information successfully.</response>
NormalizeByondVersion()
static Version Tgstation.Server.Host.Controllers.EngineController.NormalizeByondVersion (Version version) static private
Remove the Version.Build from a given version if present.
Parameters
version The Version to normalize.
Returns
The normalized Version. May be a reference to version .
Referenced by Tgstation.Server.Host.Controllers.EngineController.ValidateEngineVersion().
Read()
ValueTask< IActionResult > Tgstation.Server.Host.Controllers.EngineController.Read ()
Gets the active EngineVersion.
Returns
A ValueTask<TResult> resulting in the IActionResult for the operation.
<response code="200">Retrieved version information successfully.</response> <response code="409">No engine versions installed.</response>
Update()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.EngineController.Update ([FromBody] EngineVersionRequest model, CancellationToken cancellationToken)
Changes the active engine version to the one specified in a given model .
Parameters
model The EngineVersionRequest containing the Version to switch to.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult for the operation.
<response code="200">Switched active engine version successfully.</response> <response code="202">Created Job to install and switch active engine version successfully.</response>
Definition at line 147 of file EngineController.cs.
        {
            ArgumentNullException.ThrowIfNull(model);
            var earlyOut = ValidateEngineVersion(model.EngineVersion);
            if (earlyOut != null)
                return earlyOut;
            var uploadingZip = model.UploadCustomZip == true;
            var engineRights = InstancePermissionSet.EngineRights!.Value;
            var isByondEngine = model.EngineVersion!.Engine!.Value == EngineType.Byond;
            var officialPerm = isByondEngine
                ? EngineRights.InstallOfficialOrChangeActiveByondVersion
                : EngineRights.InstallOfficialOrChangeActiveOpenDreamVersion;
            var customPerm = isByondEngine
                ? EngineRights.InstallCustomByondVersion
                : EngineRights.InstallCustomOpenDreamVersion;
            if ((!engineRights.HasFlag(officialPerm) && !uploadingZip)
                || (!engineRights.HasFlag(customPerm) && uploadingZip))
                return Forbid();
            // remove cruff fields
            var result = new EngineInstallResponse();
            return await WithComponentInstance(
                async instance =>
                {
                    var byondManager = instance.EngineManager;
                    var versionAlreadyInstalled = !uploadingZip && byondManager.InstalledVersions.Any(x => x.Equals(model.EngineVersion));
                    if (versionAlreadyInstalled)
                    {
                        Logger.LogInformation(
                            "User ID {userId} changing instance ID {instanceId} engine to {newByondVersion}",
                            AuthenticationContext.User.Id,
                            Instance.Id,
                            model);
                        try
{
                            using var progressReporter = new JobProgressReporter();
                            await byondManager.ChangeVersion(progressReporter, model.EngineVersion, null, false, cancellationToken);
                        }
                        catch (InvalidOperationException ex)
{
                            Logger.LogDebug(
                                ex,
                                "Race condition: Engine {version} uninstalled before we could switch to it. Creating install job instead...",
                                model);
                            versionAlreadyInstalled = false;
                        }
                    }
                    if (!versionAlreadyInstalled)
                    {
                        if (model.EngineVersion.CustomIteration.HasValue)
                            return BadRequest(new ErrorMessageResponse(ErrorCode.EngineNonExistentCustomVersion));
                        Logger.LogInformation(
                            "User ID {userId} installing engine version {newByondVersion} on instance ID {instanceId}",
                            AuthenticationContext.User.Id,
                            model,
                            Instance.Id);
                        // run the install through the job manager
                        var job = Models.Job.Create(
                            uploadingZip
                                ? JobCode.EngineCustomInstall
                                : JobCode.EngineOfficialInstall,
                            AuthenticationContext.User,
                            Instance,
                            EngineRights.CancelInstall);
                        job.Description += $" {model.EngineVersion}";
                        IFileUploadTicket? fileUploadTicket = null;
                        if (uploadingZip)
                            fileUploadTicket = fileTransferService.CreateUpload(FileUploadStreamKind.None);
                        try
{
                            await jobManager.RegisterOperation(
                                job,
                                async (core, databaseContextFactory, paramJob, progressHandler, jobCancellationToken) =>
{
                                    MemoryStream? zipFileStream = null;
                                    if (fileUploadTicket != null)
                                        await using (fileUploadTicket)
{
                                            var uploadStream = await fileUploadTicket.GetResult(jobCancellationToken) ?? throw new JobException(ErrorCode.FileUploadExpired);
                                            zipFileStream = new MemoryStream();
                                            try
{
                                                await uploadStream.CopyToAsync(zipFileStream, jobCancellationToken);
                                            }
                                            catch
{
                                                await zipFileStream.DisposeAsync();
                                                throw;
                                            }
                                        }
                                    await using (zipFileStream)
                                        await core!.EngineManager.ChangeVersion(
                                            progressHandler,
                                            model.EngineVersion,
                                            zipFileStream,
                                            true,
                                            jobCancellationToken);
                                },
                                cancellationToken);
                            result.InstallJob = job.ToApi();
                            result.FileTicket = fileUploadTicket?.Ticket.FileTicket;
                        }
                        catch
{
                            if (fileUploadTicket != null)
                                await fileUploadTicket.DisposeAsync();
                            throw;
                        }
                    }
                    return result.InstallJob != null ? Accepted(result) : Json(result);
                });
        }
References Tgstation.Server.Host.Transfer.IFileTransferTicketProvider.CreateUpload(), Tgstation.Server.Api.Models.Internal.InstancePermissionSet.EngineRights, Tgstation.Server.Host.Controllers.EngineController.fileTransferService, Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Host.Controllers.InstanceRequiredController.Instance, Tgstation.Server.Host.Controllers.EngineController.jobManager, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Controllers.ApiController.Logger, Tgstation.Server.Host.Jobs.IJobManager.RegisterOperation(), Tgstation.Server.Host.Security.AuthenticationContext.User, Tgstation.Server.Host.Controllers.EngineController.ValidateEngineVersion(), and Tgstation.Server.Host.Controllers.ComponentInterfacingController.WithComponentInstance().
ValidateEngineVersion()
BadRequestObjectResult? Tgstation.Server.Host.Controllers.EngineController.ValidateEngineVersion (EngineVersion? version) private
Validate and normalize a given version .
Parameters
version The EngineVersion to validate and normalize.
Returns
The BadRequestObjectResult to return, if any. null otherwise.
Definition at line 345 of file EngineController.cs.
        {
            if (version == null || !version.Engine.HasValue)
                return BadRequest(new ErrorMessageResponse(ErrorCode.ModelValidationFailure));
            var isByond = version.Engine.Value == EngineType.Byond;
            var validSha = version.SourceSHA?.Length == Limits.MaximumCommitShaLength;
            if ((isByond
                && (version.Version == null
                || validSha))
                || (version.Engine.Value == EngineType.OpenDream &&
                ((version.SourceSHA == null && version.Version == null)
                || (version.Version != null && (version.Version.Revision != -1 || validSha)))))
                return BadRequest(new ErrorMessageResponse(ErrorCode.ModelValidationFailure));
            if (isByond)
            {
                version.Version = NormalizeByondVersion(version.Version!);
                if (version.Version.Build != -1)
                    return BadRequest(new ErrorMessageResponse(ErrorCode.ModelValidationFailure));
            }
            return null;
        }
References Tgstation.Server.Api.Rights.List, Tgstation.Server.Api.Models.Limits.MaximumCommitShaLength, and Tgstation.Server.Host.Controllers.EngineController.NormalizeByondVersion().
Referenced by Tgstation.Server.Host.Controllers.EngineController.Delete(), and Tgstation.Server.Host.Controllers.EngineController.Update().
Member Data Documentation
fileTransferService
readonly IFileTransferTicketProvider Tgstation.Server.Host.Controllers.EngineController.fileTransferService private
The IFileTransferTicketProvider for the EngineController.
Definition at line 42 of file EngineController.cs.
Referenced by Tgstation.Server.Host.Controllers.EngineController.EngineController(), and Tgstation.Server.Host.Controllers.EngineController.Update().
jobManager
readonly IJobManager Tgstation.Server.Host.Controllers.EngineController.jobManager private
The IJobManager for the EngineController.
Definition at line 37 of file EngineController.cs.
Referenced by Tgstation.Server.Host.Controllers.EngineController.Delete(), Tgstation.Server.Host.Controllers.EngineController.EngineController(), and Tgstation.Server.Host.Controllers.EngineController.Update().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Controllers/EngineController.cs