tgstation-server: Tgstation.Server.Host.Models.UserGroup Class Reference
Tgstation.Server.Host.Models.UserGroup Class Reference sealed
Represents a group of Users.
Public Member Functions
UserGroupResponse ToApi (bool showUsers)
Convert the UserGroup to it's API form.
UserGroupResponse ToApi ()
Public Member Functions inherited from Tgstation.Server.Host.Models.ILegacyApiTransformable< UserGroupResponse >
TApiModel ToApi ()
Convert the ILegacyApiTransformable<TApiModel> to it's TApiModel .
Public Member Functions inherited from Tgstation.Server.Host.Models.IApiTransformable< UserGroup, GraphQL.Types.UserGroup, UserGroupGraphQLTransformer >
TApiModel ToApi ()
Convert the IApiTransformable<TModel, TApiModel, TApiTransformer> to it's TApiModel .
Properties
PermissionSet? PermissionSet [get, set]
The Models.PermissionSet the UserGroup has.
ICollection< User >? Users [get, set]
The Users the UserGroup has.
Properties inherited from Tgstation.Server.Api.Models.NamedEntity
virtual ? string Name [get, set]
The name of the entity represented by the NamedEntity.
Properties inherited from Tgstation.Server.Api.Models.EntityId
virtual ? long Id [get, set]
The ID of the entity.
Detailed Description
Represents a group of Users.
Definition at line 15 of file UserGroup.cs.
Member Function Documentation
ToApi() [1/2]
UserGroupResponse Tgstation.Server.Host.Models.UserGroup.ToApi ()
Referenced by Tgstation.Server.Host.Models.UserGroup.ToApi().
ToApi() [2/2]
UserGroupResponse Tgstation.Server.Host.Models.UserGroup.ToApi (bool showUsers)
Convert the UserGroup to it's API form.
Parameters
showUsers If UserGroupResponse.Users should be populated.
Returns
A new UserGroupResponse.
References Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Api.Models.NamedEntity.Name, Tgstation.Server.Host.Models.UserGroup.ToApi(), and Tgstation.Server.Host.Models.UserGroup.Users.
Referenced by Tgstation.Server.Host.Models.User.CreateUserResponse().
Property Documentation
PermissionSet
PermissionSet? Tgstation.Server.Host.Models.UserGroup.PermissionSet get set
The Models.PermissionSet the UserGroup has.
Definition at line 21 of file UserGroup.cs.
{ get; set; }
Referenced by Tgstation.Server.Host.Security.AuthenticationContext.Initialize().
Users
ICollection<User>? Tgstation.Server.Host.Models.UserGroup.Users get set
The Users the UserGroup has.
Definition at line 26 of file UserGroup.cs.
{ get; set; }
Referenced by Tgstation.Server.Host.Models.UserGroup.ToApi().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Models/UserGroup.cs