tgstation-server: Tgstation.Server.Host.Security.AuthorizationHandler Class Reference
Tgstation.Server.Host.Security.AuthorizationHandler Class Reference sealed
IAuthorizationHandler for RightsConditional<TRights>s and UserSessionValidRequirements.
Public Member Functions
AuthorizationHandler (IDatabaseContextFactory databaseContextFactory, IApiHeadersProvider apiHeadersProvider)
Initializes a new instance of the AuthorizationHandler class.
Task HandleAsync (AuthorizationHandlerContext context)
Private Member Functions
IEnumerable< ValueTask > InvokeHandleRightsConditionalRequirement< TRights > (AuthorizationHandlerContext context, CancellationToken cancellationToken)
Handle invoking HandleRightsConditionalRequirement<TRights>(AuthorizationHandlerContext, RightsConditional<TRights>, CancellationToken) for given TRights .
ValueTask HandleSessionValidRequirement (AuthorizationHandlerContext context, UserSessionValidRequirement requirement, CancellationToken cancellationToken)
Handle UserSessionValidRequirement authorization requirements.
ValueTask HandleRightsConditionalRequirement< TRights > (AuthorizationHandlerContext context, RightsConditional< TRights > requirement, CancellationToken cancellationToken)
Handle RightsConditional<TRights> authorization requirements.
Private Attributes
readonly IDatabaseContextFactory databaseContextFactory
The IDatabaseContextFactory for the AuthorizationHandler.
readonly IApiHeadersProvider apiHeadersProvider
The IApiHeadersProvider for the AuthorizationHandler.
Detailed Description
IAuthorizationHandler for RightsConditional<TRights>s and UserSessionValidRequirements.
Definition at line 25 of file AuthorizationHandler.cs.
Constructor & Destructor Documentation
AuthorizationHandler()
Tgstation.Server.Host.Security.AuthorizationHandler.AuthorizationHandler (IDatabaseContextFactory databaseContextFactory, IApiHeadersProvider apiHeadersProvider)
Initializes a new instance of the AuthorizationHandler class.
Parameters
databaseContextFactory The value of databaseContextFactory.
apiHeadersProvider The value of apiHeadersProvider.
Definition at line 42 of file AuthorizationHandler.cs.
        {
            this.databaseContextFactory = databaseContextFactory ?? throw new ArgumentNullException(nameof(databaseContextFactory));
            this.apiHeadersProvider = apiHeadersProvider ?? throw new ArgumentNullException(nameof(apiHeadersProvider));
        }
References Tgstation.Server.Host.Security.AuthorizationHandler.apiHeadersProvider, Tgstation.Server.Host.Security.AuthorizationHandler.databaseContextFactory, and Tgstation.Server.Api.Rights.List.
Member Function Documentation
HandleAsync()
Task Tgstation.Server.Host.Security.AuthorizationHandler.HandleAsync (AuthorizationHandlerContext context)
Definition at line 49 of file AuthorizationHandler.cs.
        {
            // https://github.com/dotnet/aspnetcore/issues/56272
            CancellationToken cancellationToken = CancellationToken.None;
            ArgumentNullException.ThrowIfNull(context);
            // all the requirements we process require authentication
            if (context.User.Identity?.IsAuthenticated != true)
            {
                context.Fail(
                    new AuthorizationFailureReason(this, "User is not authenticated!"));
                return Task.CompletedTask;
            }
            List<ValueTask> processingRequirements = new List<ValueTask>();
            foreach (var req in context.Requirements.OfType<UserSessionValidRequirement>())
                processingRequirements.Add(
                    HandleSessionValidRequirement(context, req, cancellationToken));
            var method = GetType().GetMethod(nameof(InvokeHandleRightsConditionalRequirement), BindingFlags.NonPublic | BindingFlags.Instance)
                ?? throw new InvalidOperationException("Failed to locate rights handler function!");
            foreach (var rightType in RightsHelper.AllRightTypes())
            {
                var genericMethod = method.MakeGenericMethod(rightType);
                processingRequirements.AddRange((IEnumerable<ValueTask>)genericMethod.Invoke(this, [context, cancellationToken])!);
            }
            return ValueTaskExtensions.WhenAll(processingRequirements).AsTask();
        }
References Tgstation.Server.Api.Rights.RightsHelper.AllRightTypes(), Tgstation.Server.Host.Security.AuthorizationHandler.HandleSessionValidRequirement(), Tgstation.Server.Api.Rights.List, and Tgstation.Server.Common.Extensions.ValueTaskExtensions.WhenAll().
HandleRightsConditionalRequirement< TRights >()
ValueTask Tgstation.Server.Host.Security.AuthorizationHandler.HandleRightsConditionalRequirement< TRights > (AuthorizationHandlerContext context, RightsConditional< TRights > requirement, CancellationToken cancellationToken) private
Handle RightsConditional<TRights> authorization requirements.
Template Parameters
TRights The Type of right to invoke the requirement handler for.
Parameters
context The shared AuthorizationHandlerContext.
requirement The RightsConditional<TRights> requirment to evaluate.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Type Constraints
TRights : Enum
Definition at line 143 of file AuthorizationHandler.cs.
                          : Enum
        {
            var rightsType = RightsHelper.TypeToRight<TRights>();
            var isInstance = RightsHelper.IsInstanceRight(rightsType);
            var userId = context.User.GetTgsUserId();
            return databaseContextFactory.UseContext(async databaseContext =>
            {
                var queryableUsers = databaseContext
                    .Users;
                var matchingUniquePermissionSetIds = queryableUsers
                    .Where(user => user.Id == userId && user.PermissionSet != null)
                    .Select(user => user.PermissionSet!.Id);
                var matchingGroupPermissionSetIds = queryableUsers
                    .Where(user => user.Id == userId && user.Group != null)
                    .Select(user => user.Group!.PermissionSet!.Id);
                object? permissionSet;
                if (isInstance)
                {
                    if (context.Resource is not long instanceId)
                        throw new InvalidOperationException("Instance ID should have been passed in as authorization resource!");
                    permissionSet = await databaseContext
                        .InstancePermissionSets
                        .Where(ips => ips.InstanceId == instanceId
                            && (matchingUniquePermissionSetIds.Contains(ips.PermissionSetId) || matchingGroupPermissionSetIds.Contains(ips.PermissionSetId)))
                        .TagWith("rights_authorization_handler_instance_permission_set")
                        .FirstOrDefaultAsync(cancellationToken);
                }
                else
                    permissionSet = await databaseContext
                        .PermissionSets
                        .Where(permissionSet => matchingUniquePermissionSetIds.Contains(permissionSet.Id) || matchingGroupPermissionSetIds.Contains(permissionSet.Id))
                        .TagWith("rights_authorization_handler_permission_set")
                        .FirstOrDefaultAsync(cancellationToken);
                if (permissionSet == null)
                {
                    context.Fail(
                        new AuthorizationFailureReason(this, $"Unable to find {(isInstance ? "instance " : String.Empty)}permission set for user."));
                    return;
                }
                // use the api versions because they're the ones that contain the actual properties
                var requiredPermissionSetType = isInstance ? typeof(InstancePermissionSet) : typeof(PermissionSet);
                var rightsClrType = typeof(TRights);
                var nullableRightsType = typeof(Nullable<>).MakeGenericType(rightsClrType);
                var rightPropertyInfo = requiredPermissionSetType
                    .GetProperties()
                    .Where(propertyInfo => propertyInfo.PropertyType == nullableRightsType && propertyInfo.CanRead)
                    .Single();
                var rightPropertyGetMethod = rightPropertyInfo.GetMethod;
                if (rightPropertyGetMethod == null)
                    throw new InvalidOperationException($"Rights property {rightPropertyInfo.Name} on {rightsClrType.FullName} has no getter!");
                var right = rightPropertyGetMethod.Invoke(
                    permissionSet,
                    Array.Empty<object>())
                    ?? throw new InvalidOperationException("A user right was null!");
                var result = requirement.Evaluate((TRights)right);
                lock (context)
                {
                    if (result)
                        context.Succeed(requirement);
                    else
                        context.Fail(
                            new AuthorizationFailureReason(this, $"Failed to successfully evaluate rights requirement: {requirement}"));
                }
            });
        }
References Tgstation.Server.Host.Security.AuthorizationHandler.databaseContextFactory, Tgstation.Server.Api.Rights.RightsHelper.IsInstanceRight(), Tgstation.Server.Api.Rights.List, and Tgstation.Server.Host.Database.IDatabaseContextFactory.UseContext().
HandleSessionValidRequirement()
ValueTask Tgstation.Server.Host.Security.AuthorizationHandler.HandleSessionValidRequirement (AuthorizationHandlerContext context, UserSessionValidRequirement requirement, CancellationToken cancellationToken) private
Handle UserSessionValidRequirement authorization requirements.
Parameters
context The shared AuthorizationHandlerContext.
requirement The UserSessionValidRequirement requirment to evaluate.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Definition at line 99 of file AuthorizationHandler.cs.
        {
            var userId = context.User.GetTgsUserId();
            var nbf = context.User.ParseTime(JwtRegisteredClaimNames.Nbf);
            return databaseContextFactory.UseContext(async databaseContext =>
            {
                var sessionData = await databaseContext
                    .Users
                    .Where(user => user.Id == userId)
                    .Select(user => new
                    {
                        Enabled = user.Enabled!.Value,
                        user.LastPasswordUpdate,
                    })
                    .TagWith("user_session_validation")
                    .FirstOrDefaultAsync(cancellationToken);
                lock (context)
                {
                    if (sessionData == null)
                        context.Fail(
                            new AuthorizationFailureReason(this, $"Unable to retrieve user {userId}!"));
                    else if (!sessionData.Enabled)
                        context.Fail(
                            new AuthorizationFailureReason(this, "User is disabled!"));
                    else if (sessionData.LastPasswordUpdate >= nbf)
                        context.Fail(
                            new AuthorizationFailureReason(this, "User has been modified since logging in!"));
                    else
                        context.Succeed(requirement);
                }
            });
        }
References Tgstation.Server.Host.Security.AuthorizationHandler.databaseContextFactory, Tgstation.Server.Api.Rights.List, and Tgstation.Server.Host.Database.IDatabaseContextFactory.UseContext().
Referenced by Tgstation.Server.Host.Security.AuthorizationHandler.HandleAsync().
InvokeHandleRightsConditionalRequirement< TRights >()
IEnumerable< ValueTask > Tgstation.Server.Host.Security.AuthorizationHandler.InvokeHandleRightsConditionalRequirement< TRights > (AuthorizationHandlerContext context, CancellationToken cancellationToken) private
Handle invoking HandleRightsConditionalRequirement<TRights>(AuthorizationHandlerContext, RightsConditional<TRights>, CancellationToken) for given TRights .
Template Parameters
TRights The Type of right to invoke the requirement handler for.
Parameters
context The shared AuthorizationHandlerContext.
cancellationToken The CancellationToken for the operation.
Returns
An IEnumerable<T> of ValueTasks representing the running operation.
Type Constraints
TRights : Enum
TRights : context.Requirements.OfType
TRights : RightsConditional<TRights>
TRights : Select
TRights : requirement
TRights : HandleRightsConditionalRequirement
TRights : context
TRights : requirement
TRights : cancellationToken
Member Data Documentation
apiHeadersProvider
readonly IApiHeadersProvider Tgstation.Server.Host.Security.AuthorizationHandler.apiHeadersProvider private
The IApiHeadersProvider for the AuthorizationHandler.
Definition at line 35 of file AuthorizationHandler.cs.
Referenced by Tgstation.Server.Host.Security.AuthorizationHandler.AuthorizationHandler().
databaseContextFactory
readonly IDatabaseContextFactory Tgstation.Server.Host.Security.AuthorizationHandler.databaseContextFactory private
The IDatabaseContextFactory for the AuthorizationHandler.
Definition at line 30 of file AuthorizationHandler.cs.
Referenced by Tgstation.Server.Host.Security.AuthorizationHandler.AuthorizationHandler(), Tgstation.Server.Host.Security.AuthorizationHandler.HandleRightsConditionalRequirement< TRights >(), and Tgstation.Server.Host.Security.AuthorizationHandler.HandleSessionValidRequirement().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Security/AuthorizationHandler.cs