tgstation-server: Tgstation.Server.Host.Controllers.UserController Class Reference
Tgstation.Server.Host.Controllers.UserController Class Reference
ApiController for managing Users.
Public Member Functions
UserController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ISystemIdentityFactory systemIdentityFactory, ICryptographySuite cryptographySuite, IPermissionsUpdateNotifyee permissionsUpdateNotifyee, ILogger< UserController > logger, IOptions< GeneralConfiguration > generalConfigurationOptions, IApiHeadersProvider apiHeaders)
Initializes a new instance of the UserController class.
async ValueTask< IActionResult > Create ([FromBody] UserCreateRequest model, CancellationToken cancellationToken)
Create a new User.
async ValueTask< IActionResult > Update ([FromBody] UserUpdateRequest model, CancellationToken cancellationToken)
Update a User.
IActionResult Read ()
Get information about the current User.
ValueTask< IActionResult > List ([FromQuery] int? page, [FromQuery] int? pageSize, CancellationToken cancellationToken)
List all Users in the server.
async ValueTask< IActionResult > GetId (long id, CancellationToken cancellationToken)
Get a specific User.
Public Member Functions inherited from Tgstation.Server.Host.Controllers.ApiControllerBase
sealed override async Task OnActionExecutionAsync (ActionExecutingContext context, ActionExecutionDelegate next)
Private Member Functions
ValueTask< IActionResult > UserResponse (()=> ValueTask.FromResult(new PaginatableResult< User >(DatabaseContext .Users .AsQueryable() .Where(x=> x.CanonicalName !=Models.User.CanonicalizeName(Models.User.TgsSystemUserName)) .Include(x=> x.CreatedBy) .Include(x=> x.PermissionSet) .Include(x=> x.OAuthConnections) .Include(x=> x.Group!) .ThenInclude(x=> x.PermissionSet) .OrderBy(x=> x.Id))), null, page, pageSize, cancellationToken)
async ValueTask< User > CreateNewUserFromModel (Api.Models.Internal.UserApiBase model, CancellationToken cancellationToken)
Creates a new User from a given model .
BadRequestObjectResult? CheckValidName (UserUpdateRequest model, bool newUser)
Check if a given model has a valid UserName.Name specified.
BadRequestObjectResult? TrySetPassword (User dbUser, string newPassword, bool newUser)
Attempt to change the password of a given dbUser .
Private Attributes
readonly ISystemIdentityFactory systemIdentityFactory
The ISystemIdentityFactory for the UserController.
readonly ICryptographySuite cryptographySuite
The ICryptographySuite for the UserController.
readonly IPermissionsUpdateNotifyee permissionsUpdateNotifyee
The IPermissionsUpdateNotifyee for the UserController.
readonly GeneralConfiguration generalConfiguration
The GeneralConfiguration for the UserController.
Additional Inherited Members
Protected Member Functions inherited from Tgstation.Server.Host.Controllers.ApiController
ApiController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, IApiHeadersProvider apiHeadersProvider, ILogger< ApiController > logger, bool requireHeaders)
Initializes a new instance of the ApiController class.
override async ValueTask< IActionResult?> HookExecuteAction (Func< Task > executeAction, CancellationToken cancellationToken)
Hook for executing a request.
Parameters
executeAction A Func<TResult> that should be invoked and its response awaited to continue normal execution of the request. Should NOT be called if this method returns a non-null value.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in an IActionResult that, if not null, is executed.
new NotFoundObjectResult NotFound ()
Generic 404 response.
new ObjectResult Unauthorized ()
Generic 401 response.
ObjectResult RequiresPosixSystemIdentity (NotImplementedException ex)
Generic 501 response.
StatusCodeResult StatusCode (HttpStatusCode statusCode)
Strongly type calls to ControllerBase.StatusCode(int).
ObjectResult Created (object payload)
Generic 201 response with a given payload .
ObjectResult RateLimit (RateLimitExceededException rateLimitException)
429 response for a given rateLimitException .
virtual ValueTask< IActionResult?> ValidateRequest (CancellationToken cancellationToken)
Performs validation a request.
IActionResult HeadersIssue (HeadersException headersException)
Response for missing/Invalid headers.
ValueTask< IActionResult > Paginated< TModel > (Func< ValueTask< PaginatableResult< TModel > > > queryGenerator, Func< TModel, ValueTask >? resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
ValueTask< IActionResult > Paginated< TModel, TApiModel > (Func< ValueTask< PaginatableResult< TModel > > > queryGenerator, Func< TApiModel, ValueTask >? resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
virtual async ValueTask< IActionResult?> HookExecuteAction (Func< Task > executeAction, CancellationToken cancellationToken)
Hook for executing a request.
Properties inherited from Tgstation.Server.Host.Controllers.ApiController
ApiHeaders? ApiHeaders [get]
The Api.ApiHeaders for the operation.
IApiHeadersProvider ApiHeadersProvider [get]
The IApiHeadersProvider containing value of ApiHeaders.
IDatabaseContext DatabaseContext [get]
The IDatabaseContext for the operation.
IAuthenticationContext AuthenticationContext [get]
The IAuthenticationContext for the operation.
ILogger< ApiController > Logger [get]
The ILogger for the ApiController.
Models.? Instance Instance [get]
The Instance for the operation.
Detailed Description
ApiController for managing Users.
Definition at line 31 of file UserController.cs.
Constructor & Destructor Documentation
UserController()
Tgstation.Server.Host.Controllers.UserController.UserController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ISystemIdentityFactory systemIdentityFactory, ICryptographySuite cryptographySuite, IPermissionsUpdateNotifyee permissionsUpdateNotifyee, ILogger< UserController > logger, IOptions< GeneralConfiguration > generalConfigurationOptions, IApiHeadersProvider apiHeaders)
Initializes a new instance of the UserController class.
Parameters
databaseContext The IDatabaseContext for the ApiController.
authenticationContext The IAuthenticationContext for the ApiController.
systemIdentityFactory The value of systemIdentityFactory.
cryptographySuite The value of cryptographySuite.
permissionsUpdateNotifyee The value of permissionsUpdateNotifyee.
logger The ILogger for the ApiController.
generalConfigurationOptions The IOptions<TOptions> containing the value of generalConfiguration.
apiHeaders The IApiHeadersProvider for the ApiController.
Definition at line 64 of file UserController.cs.
            : base(
                  databaseContext,
                  authenticationContext,
                  apiHeaders,
                  logger,
                  true)
        {
            this.systemIdentityFactory = systemIdentityFactory ?? throw new ArgumentNullException(nameof(systemIdentityFactory));
            this.cryptographySuite = cryptographySuite ?? throw new ArgumentNullException(nameof(cryptographySuite));
            this.permissionsUpdateNotifyee = permissionsUpdateNotifyee ?? throw new ArgumentNullException(nameof(permissionsUpdateNotifyee));
            generalConfiguration = generalConfigurationOptions?.Value ?? throw new ArgumentNullException(nameof(generalConfigurationOptions));
        }
References Tgstation.Server.Host.Controllers.UserController.cryptographySuite, Tgstation.Server.Host.Controllers.UserController.generalConfiguration, Tgstation.Server.Host.Controllers.UserController.permissionsUpdateNotifyee, and Tgstation.Server.Host.Controllers.UserController.systemIdentityFactory.
Member Function Documentation
CheckValidName()
BadRequestObjectResult? Tgstation.Server.Host.Controllers.UserController.CheckValidName (UserUpdateRequest model, bool newUser) private
Check if a given model has a valid UserName.Name specified.
Parameters
model The UserUpdateRequest to check.
newUser If this is a new UserResponse.
Returns
null if model is valid, a BadRequestObjectResult otherwise.
Definition at line 472 of file UserController.cs.
        {
            var userInvalidWithNullName = newUser && model.Name == null && model.SystemIdentifier == null;
            if (userInvalidWithNullName || (model.Name != null && String.IsNullOrWhiteSpace(model.Name)))
                return BadRequest(new ErrorMessageResponse(ErrorCode.UserMissingName));
            model.Name = model.Name?.Trim();
            if (model.Name != null && model.Name.Contains(':', StringComparison.InvariantCulture))
                return BadRequest(new ErrorMessageResponse(ErrorCode.UserColonInName));
            return null;
        }
References Tgstation.Server.Api.Models.UserName.Name.
Referenced by Tgstation.Server.Host.Controllers.UserController.Create(), and Tgstation.Server.Host.Controllers.UserController.Update().
Create()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.UserController.Create ([FromBody] UserCreateRequest model, CancellationToken cancellationToken)
Create a new User.
Parameters
model The UserCreateRequest.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the operation.
<response code="201">User created successfully.</response> <response code="410">The requested system identifier could not be found.</response>
Definition at line 98 of file UserController.cs.
        {
            ArgumentNullException.ThrowIfNull(model);
            if (model.OAuthConnections?.Any(x => x == null) == true)
                return BadRequest(new ErrorMessageResponse(ErrorCode.ModelValidationFailure));
            if ((model.Password != null && model.SystemIdentifier != null)
                || (model.Password == null && model.SystemIdentifier == null && (model.OAuthConnections?.Count > 0) != true))
                return BadRequest(new ErrorMessageResponse(ErrorCode.UserMismatchPasswordSid));
            if (model.Group != null && model.PermissionSet != null)
                return BadRequest(new ErrorMessageResponse(ErrorCode.UserGroupAndPermissionSet));
            model.Name = model.Name?.Trim();
            if (model.Name?.Length == 0)
                model.Name = null;
            if (!(model.Name == null ^ model.SystemIdentifier == null))
                return BadRequest(new ErrorMessageResponse(ErrorCode.UserMismatchNameSid));
            var fail = CheckValidName(model, true);
            if (fail != null)
                return fail;
            var totalUsers = await DatabaseContext
                .Users
                .AsQueryable()
                .CountAsync(cancellationToken);
            if (totalUsers >= generalConfiguration.UserLimit)
                return Conflict(new ErrorMessageResponse(ErrorCode.UserLimitReached));
            var dbUser = await CreateNewUserFromModel(model, cancellationToken);
            if (dbUser == null)
                return this.Gone();
            if (model.SystemIdentifier != null)
                try
                {
                    using var sysIdentity = await systemIdentityFactory.CreateSystemIdentity(dbUser, cancellationToken);
                    if (sysIdentity == null)
                        return this.Gone();
                    dbUser.Name = sysIdentity.Username;
                    dbUser.SystemIdentifier = sysIdentity.Uid;
                }
                catch (NotImplementedException ex)
                {
                    return RequiresPosixSystemIdentity(ex);
                }
            else if (!(model.Password?.Length == 0 && (model.OAuthConnections?.Count > 0) == true))
            {
                var result = TrySetPassword(dbUser, model.Password!, true);
                if (result != null)
                    return result;
            }
            dbUser.CanonicalName = Models.User.CanonicalizeName(dbUser.Name!);
            DatabaseContext.Users.Add(dbUser);
            await DatabaseContext.Save(cancellationToken);
            Logger.LogInformation("Created new user {name} ({id})", dbUser.Name, dbUser.Id);
            return Created(dbUser.ToApi());
        }
References Tgstation.Server.Host.Controllers.UserController.CheckValidName(), Tgstation.Server.Host.Controllers.ApiController.Created(), Tgstation.Server.Host.Controllers.UserController.CreateNewUserFromModel(), Tgstation.Server.Host.Security.ISystemIdentityFactory.CreateSystemIdentity(), Tgstation.Server.Host.Controllers.UserController.generalConfiguration, Tgstation.Server.Host.Controllers.ApiController.Logger, Tgstation.Server.Host.Controllers.ApiController.RequiresPosixSystemIdentity(), Tgstation.Server.Host.Database.DatabaseContext.Save(), Tgstation.Server.Host.Controllers.UserController.systemIdentityFactory, Tgstation.Server.Host.Controllers.UserController.TrySetPassword(), Tgstation.Server.Api.Models.Internal.ServerInformationBase.UserLimit, and Tgstation.Server.Host.Database.DatabaseContext.Users.
CreateNewUserFromModel()
async ValueTask< User > Tgstation.Server.Host.Controllers.UserController.CreateNewUserFromModel (Api.Models.Internal.UserApiBase model, CancellationToken cancellationToken) private
Creates a new User from a given model .
Parameters
model The Api.Models.Internal.UserApiBase to use as a template.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a new User on success, null if the requested UserGroup did not exist.
Definition at line 427 of file UserController.cs.
        {
            Models.PermissionSet? permissionSet = null;
            UserGroup? group = null;
            if (model.Group != null)
                group = await DatabaseContext
                    .Groups
                    .AsQueryable()
                    .Where(x => x.Id == model.Group.Id)
                    .Include(x => x.PermissionSet)
                    .FirstOrDefaultAsync(cancellationToken);
            else
                permissionSet = new Models.PermissionSet
                {
                    AdministrationRights = model.PermissionSet?.AdministrationRights ?? AdministrationRights.None,
                    InstanceManagerRights = model.PermissionSet?.InstanceManagerRights ?? InstanceManagerRights.None,
                };
            return new User
            {
                CreatedAt = DateTimeOffset.UtcNow,
                CreatedBy = AuthenticationContext.User,
                Enabled = model.Enabled ?? false,
                PermissionSet = permissionSet,
                Group = group,
                Name = model.Name,
                SystemIdentifier = model.SystemIdentifier,
                OAuthConnections = model
                    .OAuthConnections
                    ?.Select(x => new Models.OAuthConnection
                    {
                        Provider = x.Provider,
                        ExternalUserId = x.ExternalUserId,
                    })
                    .ToList()
                    ?? new List<Models.OAuthConnection>(),
            };
        }
References Tgstation.Server.Api.Models.PermissionSet.AdministrationRights, Tgstation.Server.Host.Database.DatabaseContext.Groups, Tgstation.Server.Host.Controllers.UserController.List(), Tgstation.Server.Api.Models.NamedEntity.Name, and Tgstation.Server.Host.Security.AuthenticationContext.User.
Referenced by Tgstation.Server.Host.Controllers.UserController.Create().
GetId()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.UserController.GetId (long id, CancellationToken cancellationToken)
Get a specific User.
Parameters
id The EntityId.Id to retrieve.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the operation.
<response code="200">The User was retrieved successfully.</response> <response code="404">The User does not exist.</response>
Definition at line 395 of file UserController.cs.
        {
            if (id == AuthenticationContext.User.Id)
                return Read();
            if (!((AdministrationRights)AuthenticationContext.GetRight(RightsType.Administration)).HasFlag(AdministrationRights.ReadUsers))
                return Forbid();
            var user = await DatabaseContext.Users
                .AsQueryable()
                .Where(x => x.Id == id)
                .Include(x => x.CreatedBy)
                .Include(x => x.OAuthConnections)
                .Include(x => x.Group!)
                    .ThenInclude(x => x.PermissionSet)
                .Include(x => x.PermissionSet)
                .FirstOrDefaultAsync(cancellationToken);
            if (user == default)
                return NotFound();
            if (user.CanonicalName == Models.User.CanonicalizeName(Models.User.TgsSystemUserName))
                return Forbid();
            return Json(user.ToApi());
        }
References Tgstation.Server.Host.Security.AuthenticationContext.GetRight(), Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Host.Controllers.ApiController.NotFound(), Tgstation.Server.Host.Controllers.UserController.Read(), and Tgstation.Server.Host.Security.AuthenticationContext.User.
List()
ValueTask< IActionResult > Tgstation.Server.Host.Controllers.UserController.List ([FromQuery] int? page, [FromQuery] int? pageSize, CancellationToken cancellationToken)
List all Users in the server.
Parameters
page The current page.
pageSize The page size.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the operation.
<response code="200">Retrieved Users successfully.</response>
Referenced by Tgstation.Server.Host.Controllers.UserController.CreateNewUserFromModel().
Read()
IActionResult Tgstation.Server.Host.Controllers.UserController.Read ()
Get information about the current User.
Returns
The IActionResult of the operation.
<response code="200">The User was retrieved successfully.</response>
Referenced by Tgstation.Server.Host.Controllers.UserController.GetId().
TrySetPassword()
BadRequestObjectResult? Tgstation.Server.Host.Controllers.UserController.TrySetPassword (User dbUser, string newPassword, bool newUser) private
Attempt to change the password of a given dbUser .
Parameters
dbUser The user to update.
newPassword The new password.
newUser If this is for a new UserResponse.
Returns
null on success, BadRequestObjectResult if newPassword is too short.
Definition at line 491 of file UserController.cs.
        {
            newPassword ??= String.Empty;
            if (newPassword.Length < generalConfiguration.MinimumPasswordLength)
                return BadRequest(new ErrorMessageResponse(ErrorCode.UserPasswordLength)
                {
                    AdditionalData = $"Required password length: {generalConfiguration.MinimumPasswordLength}",
                });
            cryptographySuite.SetUserPassword(dbUser, newPassword, newUser);
            return null;
        }
References Tgstation.Server.Host.Controllers.UserController.cryptographySuite, Tgstation.Server.Host.Controllers.UserController.generalConfiguration, Tgstation.Server.Api.Models.Internal.ServerInformationBase.MinimumPasswordLength, and Tgstation.Server.Host.Security.ICryptographySuite.SetUserPassword().
Referenced by Tgstation.Server.Host.Controllers.UserController.Create(), and Tgstation.Server.Host.Controllers.UserController.Update().
Update()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.UserController.Update ([FromBody] UserUpdateRequest model, CancellationToken cancellationToken)
Update a User.
Parameters
model The UserResponse to update.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IActionResult of the operation.
<response code="200">User updated successfully.</response> <response code="200">User updated successfully. Not returned due to lack of permissions.</response> <response code="404">Requested EntityId.Id does not exist.</response> <response code="410">Requested Api.Models.Internal.UserApiBase.Group does not exist.</response>
Definition at line 184 of file UserController.cs.
        {
            ArgumentNullException.ThrowIfNull(model);
            if (!model.Id.HasValue || model.OAuthConnections?.Any(x => x == null) == true)
                return BadRequest(new ErrorMessageResponse(ErrorCode.ModelValidationFailure));
            if (model.Group != null && model.PermissionSet != null)
                return BadRequest(new ErrorMessageResponse(ErrorCode.UserGroupAndPermissionSet));
            var callerAdministrationRights = (AdministrationRights)AuthenticationContext.GetRight(RightsType.Administration);
            var canEditAllUsers = callerAdministrationRights.HasFlag(AdministrationRights.WriteUsers);
            var passwordEdit = canEditAllUsers || callerAdministrationRights.HasFlag(AdministrationRights.EditOwnPassword);
            var oAuthEdit = canEditAllUsers || callerAdministrationRights.HasFlag(AdministrationRights.EditOwnOAuthConnections);
            var originalUser = !canEditAllUsers
                ? AuthenticationContext.User
                : await DatabaseContext
                    .Users
                    .AsQueryable()
                    .Where(x => x.Id == model.Id)
                    .Include(x => x.CreatedBy)
                    .Include(x => x.OAuthConnections)
                    .Include(x => x.Group!)
                        .ThenInclude(x => x.PermissionSet)
                    .Include(x => x.PermissionSet)
                    .FirstOrDefaultAsync(cancellationToken);
            if (originalUser == default)
                return NotFound();
            if (originalUser.CanonicalName == Models.User.CanonicalizeName(Models.User.TgsSystemUserName))
                return Forbid();
            // Ensure they are only trying to edit things they have perms for (system identity change will trigger a bad request)
            if ((!canEditAllUsers
                && (model.Id != originalUser.Id
                || model.Enabled.HasValue
                || model.Group != null
                || model.PermissionSet != null
                || model.Name != null))
                || (!passwordEdit && model.Password != null)
                || (!oAuthEdit && model.OAuthConnections != null))
                return Forbid();
            var originalUserHasSid = originalUser.SystemIdentifier != null;
            if (originalUserHasSid && originalUser.PasswordHash != null)
            {
                // cleanup from https://github.com/tgstation/tgstation-server/issues/1528
                Logger.LogDebug("System user ID {userId}'s PasswordHash is polluted, updating database.", originalUser.Id);
                originalUser.PasswordHash = null;
                originalUser.LastPasswordUpdate = DateTimeOffset.UtcNow;
            }
            if (model.SystemIdentifier != null && model.SystemIdentifier != originalUser.SystemIdentifier)
                return BadRequest(new ErrorMessageResponse(ErrorCode.UserSidChange));
            if (model.Password != null)
            {
                if (originalUserHasSid)
                    return BadRequest(new ErrorMessageResponse(ErrorCode.UserMismatchPasswordSid));
                var result = TrySetPassword(originalUser, model.Password, false);
                if (result != null)
                    return result;
            }
            if (model.Name != null && Models.User.CanonicalizeName(model.Name) != originalUser.CanonicalName)
                return BadRequest(new ErrorMessageResponse(ErrorCode.UserNameChange));
            bool userWasDisabled;
            if (model.Enabled.HasValue)
            {
                userWasDisabled = originalUser.Require(x => x.Enabled) && !model.Enabled.Value;
                if (userWasDisabled)
                    originalUser.LastPasswordUpdate = DateTimeOffset.UtcNow;
                originalUser.Enabled = model.Enabled.Value;
            }
            else
                userWasDisabled = false;
            if (model.OAuthConnections != null
                && (model.OAuthConnections.Count != originalUser.OAuthConnections!.Count
                || !model.OAuthConnections.All(x => originalUser.OAuthConnections.Any(y => y.Provider == x.Provider && y.ExternalUserId == x.ExternalUserId))))
            {
                if (originalUser.CanonicalName == Models.User.CanonicalizeName(DefaultCredentials.AdminUserName))
                    return BadRequest(new ErrorMessageResponse(ErrorCode.AdminUserCannotOAuth));
                if (model.OAuthConnections.Count == 0 && originalUser.PasswordHash == null && originalUser.SystemIdentifier == null)
                    return BadRequest(new ErrorMessageResponse(ErrorCode.CannotRemoveLastAuthenticationOption));
                originalUser.OAuthConnections.Clear();
                foreach (var updatedConnection in model.OAuthConnections)
                    originalUser.OAuthConnections.Add(new Models.OAuthConnection
                    {
                        Provider = updatedConnection.Provider,
                        ExternalUserId = updatedConnection.ExternalUserId,
                    });
            }
            if (model.Group != null)
            {
                originalUser.Group = await DatabaseContext
                    .Groups
                    .AsQueryable()
                    .Where(x => x.Id == model.Group.Id)
                    .Include(x => x.PermissionSet)
                    .FirstOrDefaultAsync(cancellationToken);
                if (originalUser.Group == default)
                    return this.Gone();
                DatabaseContext.Groups.Attach(originalUser.Group);
                if (originalUser.PermissionSet != null)
                {
                    Logger.LogInformation("Deleting permission set {permissionSetId}...", originalUser.PermissionSet.Id);
                    DatabaseContext.PermissionSets.Remove(originalUser.PermissionSet);
                    originalUser.PermissionSet = null;
                }
            }
            else if (model.PermissionSet != null)
            {
                if (originalUser.PermissionSet == null)
                {
                    Logger.LogTrace("Creating new permission set...");
                    originalUser.PermissionSet = new Models.PermissionSet();
                }
                originalUser.PermissionSet.AdministrationRights = model.PermissionSet.AdministrationRights ?? AdministrationRights.None;
                originalUser.PermissionSet.InstanceManagerRights = model.PermissionSet.InstanceManagerRights ?? InstanceManagerRights.None;
                originalUser.Group = null;
                originalUser.GroupId = null;
            }
            var fail = CheckValidName(model, false);
            if (fail != null)
                return fail;
            originalUser.Name = model.Name ?? originalUser.Name;
            await DatabaseContext.Save(cancellationToken);
            Logger.LogInformation("Updated user {userName} ({userId})", originalUser.Name, originalUser.Id);
            if (userWasDisabled)
                await permissionsUpdateNotifyee.UserDisabled(originalUser, cancellationToken);
            // return id only if not a self update and cannot read users
            var canReadBack = AuthenticationContext.User.Id == originalUser.Id
                || callerAdministrationRights.HasFlag(AdministrationRights.ReadUsers);
            return canReadBack
                ? Json(originalUser.ToApi())
                : NoContent();
        }
References Tgstation.Server.Api.DefaultCredentials.AdminUserName, Tgstation.Server.Host.Controllers.UserController.CheckValidName(), Tgstation.Server.Host.Security.AuthenticationContext.GetRight(), Tgstation.Server.Host.Database.DatabaseContext.Groups, Tgstation.Server.Host.Controllers.ApiController.Logger, Tgstation.Server.Host.Controllers.ApiController.NotFound(), Tgstation.Server.Host.Database.DatabaseContext.PermissionSets, Tgstation.Server.Host.Controllers.UserController.permissionsUpdateNotifyee, Tgstation.Server.Host.Database.DatabaseContext.Save(), Tgstation.Server.Host.Controllers.UserController.TrySetPassword(), Tgstation.Server.Host.Security.IPermissionsUpdateNotifyee.UserDisabled(), and Tgstation.Server.Host.Database.DatabaseContext.Users.
UserResponse()
ValueTask< IActionResult > Tgstation.Server.Host.Controllers.UserController.UserResponse (() , ValueTask. FromResultnew PaginatableResult< User >(DatabaseContext .Users .AsQueryable() .Where(x=> x.CanonicalName !=Models.User.CanonicalizeName(Models.User.TgsSystemUserName)) .Include(x=> x.CreatedBy) .Include(x=> x.PermissionSet) .Include(x=> x.OAuthConnections) .Include(x=> x.Group!) .ThenInclude(x=> x.PermissionSet) .OrderBy(x=> x.Id)), null , page , pageSize , cancellationToken) private
Member Data Documentation
cryptographySuite
readonly ICryptographySuite Tgstation.Server.Host.Controllers.UserController.cryptographySuite private
The ICryptographySuite for the UserController.
Definition at line 41 of file UserController.cs.
Referenced by Tgstation.Server.Host.Controllers.UserController.TrySetPassword(), and Tgstation.Server.Host.Controllers.UserController.UserController().
generalConfiguration
readonly GeneralConfiguration Tgstation.Server.Host.Controllers.UserController.generalConfiguration private
The GeneralConfiguration for the UserController.
Definition at line 51 of file UserController.cs.
Referenced by Tgstation.Server.Host.Controllers.UserController.Create(), Tgstation.Server.Host.Controllers.UserController.TrySetPassword(), and Tgstation.Server.Host.Controllers.UserController.UserController().
permissionsUpdateNotifyee
readonly IPermissionsUpdateNotifyee Tgstation.Server.Host.Controllers.UserController.permissionsUpdateNotifyee private
The IPermissionsUpdateNotifyee for the UserController.
Definition at line 46 of file UserController.cs.
Referenced by Tgstation.Server.Host.Controllers.UserController.Update(), and Tgstation.Server.Host.Controllers.UserController.UserController().
systemIdentityFactory
readonly ISystemIdentityFactory Tgstation.Server.Host.Controllers.UserController.systemIdentityFactory private
The ISystemIdentityFactory for the UserController.
Definition at line 36 of file UserController.cs.
Referenced by Tgstation.Server.Host.Controllers.UserController.Create(), and Tgstation.Server.Host.Controllers.UserController.UserController().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Controllers/UserController.cs