tgstation-server: Tgstation.Server.Host.Components.Chat.Chat Class Reference
Tgstation.Server.Host.Components.Chat.Chat Class Reference
Public Member Functions
Chat (IProviderFactory providerFactory, IIOManager ioManager, ICommandFactory commandFactory, ILogger< Chat > logger, IEnumerable< Models.ChatBot > initialChatBots)
Construct a Chat
void Dispose ()
async Task ChangeChannels (long connectionId, IEnumerable< Api.Models.ChatChannel > newChannels, CancellationToken cancellationToken)
Change chat channels
async Task ChangeSettings (ChatBot newSettings, CancellationToken cancellationToken)
Change chat settings. If the ChatBot.Id is not currently in use, a new connection will be made instead
Task SendMessage (string message, IEnumerable< ulong > channelIds, CancellationToken cancellationToken)
Send a chat message to a given set of channelIds
Task SendWatchdogMessage (string message, CancellationToken cancellationToken)
Send a chat message to configured watchdog channels
Task SendUpdateMessage (string message, CancellationToken cancellationToken)
Send a chat message to configured update channels
async Task StartAsync (CancellationToken cancellationToken)
async Task StopAsync (CancellationToken cancellationToken)
async Task< IJsonTrackingContext > TrackJsons (string basePath, string channelsJsonName, string commandsJsonName, CancellationToken cancellationToken)
Start tracking json files for commands and channels
bool Connected (long connectionId)
If a given set of ChatBot is connected
void RegisterCommandHandler (ICustomCommandHandler customCommandHandler)
Registers a customCommandHandler to use
async Task DeleteConnection (long connectionId, CancellationToken cancellationToken)
Disconnects and deletes a given connection
Task SendBroadcast (string message, CancellationToken cancellationToken)
Send a chat to all channels
Private Member Functions
async Task< IProvider > RemoveProvider (long connectionId, bool updateTrackings, CancellationToken cancellationToken)
Remove a IProvider from providers and mappedChannels optionally updating the trackingContexts as well
async Task ProcessMessage (IProvider provider, Message message, CancellationToken cancellationToken)
Processes a message
async Task MonitorMessages (CancellationToken cancellationToken)
Monitors active providers for new Messages
Private Attributes
const string CommonMention = "!tgs"
readonly IProviderFactory providerFactory
The IProviderFactory for the Chat
readonly IIOManager ioManager
The IIOManager for the Chat
readonly ICommandFactory commandFactory
The ICommandFactory for the Chat
readonly ILogger< Chat > logger
The ILogger for the Chat
readonly Dictionary< string, ICommand > builtinCommands
Unchanging ICommands in the Chat mapped by ICommand.Name
readonly Dictionary< long, IProvider > providers
Map of IProviders in use, keyed by ChatBot.Id
readonly Dictionary< ulong, ChannelMapping > mappedChannels
Map of Channel.RealIds to ChannelMappings
readonly List< IJsonTrackingContext > trackingContexts
The active IJsonTrackingContexts for the Chat
readonly CancellationTokenSource handlerCts
The CancellationTokenSource for chatHandler
readonly List< Models.ChatBot > initialChatBots
The initial Models.ChatBot for the Chat
ICustomCommandHandler customCommandHandler
The ICustomCommandHandler for the ChangeChannels(long, IEnumerable<Api.Models.ChatChannel>, CancellationToken)
Task chatHandler
The Task that monitors incoming chat messages
TaskCompletionSource< object > connectionsUpdated
The TaskCompletionSource<TResult> that completes when ChatBots change
ulong channelIdCounter
Used for remapping Channel.RealIds
bool started
If StartAsync(CancellationToken) has been called
Detailed Description
Definition at line 17 of file Chat.cs.
Constructor & Destructor Documentation
Tgstation.Server.Host.Components.Chat.Chat.Chat (IProviderFactory providerFactory, IIOManager ioManager, ICommandFactory commandFactory, ILogger< Chat > logger, IEnumerable< Models.ChatBot > initialChatBots)
Construct a Chat
Parameters
providerFactory The value of providerFactory
ioManager The value of ioManager
logger The value of logger
commandFactory The value of commandFactory
initialChatBots The IEnumerable<T> used to populate initialChatBots
Definition at line 104 of file Chat.cs.
         {
             this.providerFactory = providerFactory ?? throw new ArgumentNullException(nameof(providerFactory));
             this.ioManager = ioManager ?? throw new ArgumentNullException(nameof(ioManager));
             this.commandFactory = commandFactory ?? throw new ArgumentNullException(nameof(commandFactory));
             this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
             this.initialChatBots = initialChatBots?.ToList() ?? throw new ArgumentNullException(nameof(initialChatBots));
             builtinCommands = new Dictionary<string, ICommand>();
             providers = new Dictionary<long, IProvider>();
             mappedChannels = new Dictionary<ulong, ChannelMapping>();
             trackingContexts = new List<IJsonTrackingContext>();
             handlerCts = new CancellationTokenSource();
             connectionsUpdated = new TaskCompletionSource<object>();
             channelIdCounter = 1;
         }
Member Function Documentation
async Task Tgstation.Server.Host.Components.Chat.Chat.ChangeChannels (long connectionId, IEnumerable< Api.Models.ChatChannel > newChannels, CancellationToken cancellationToken)
Change chat channels
Implements Tgstation.Server.Host.Components.Chat.IChat.
Definition at line 349 of file Chat.cs.
References Tgstation.Server.Host.Components.Chat.ChannelMapping.IsWatchdogChannel.
         {
             if (newChannels == null)
                 throw new ArgumentNullException(nameof(newChannels));
             var provider = await RemoveProvider(connectionId, false, cancellationToken).ConfigureAwait(false);
             if (provider == null)
                 return;
             var results = await provider.MapChannels(newChannels, cancellationToken).ConfigureAwait(false);
             if (results == null)    //aborted
                 return;
             var mappings = Enumerable.Zip(newChannels, results, (x, y) => new ChannelMapping
             {
                 IsWatchdogChannel = x.IsWatchdogChannel == true,
                 IsUpdatesChannel = x.IsUpdatesChannel == true,
                 ProviderChannelId = y.RealId,
                 ProviderId = connectionId,
                 Channel = y
             });
             ulong baseId;
             lock (this)
             {
                 baseId = channelIdCounter;
                 channelIdCounter += (ulong)results.Count;
             }
             Task task;
             lock (mappedChannels)
             {
                 lock (providers)
                     if (!providers.TryGetValue(connectionId, out IProvider verify) || verify != provider)   //aborted again
                         return;
                 foreach (var I in mappings)
                 {
                     var newId = baseId++;
                     mappedChannels.Add(newId, I);
                     I.Channel.RealId = newId;
                 }
                 lock (trackingContexts)
                     task = Task.WhenAll(trackingContexts.Select(x => x.SetChannels(mappedChannels.Select(y => y.Value.Channel), cancellationToken)));
             }
             await task.ConfigureAwait(false);
         }
async Task Tgstation.Server.Host.Components.Chat.Chat.ChangeSettings (ChatBot newSettings, CancellationToken cancellationToken)
Change chat settings. If the ChatBot.Id is not currently in use, a new connection will be made instead
Implements Tgstation.Server.Host.Components.Chat.IChat.
Definition at line 395 of file Chat.cs.
References Tgstation.Server.Host.Components.Chat.Providers.IProvider.Disconnect(), Tgstation.Server.Api.Models.Internal.ChatBot.Enabled, and Tgstation.Server.Api.Models.Internal.ChatBot.Id.
         {
             if (newSettings == null)
                 throw new ArgumentNullException(nameof(newSettings));
             IProvider provider;
             async Task DisconnectProvider(IProvider p)
             {
                 try
                 {
                     await p.Disconnect(cancellationToken).ConfigureAwait(false);
                 }
                 finally
                 {
                     p.Dispose();
                 }
             }
             Task disconnectTask;
             lock (providers)
             {
                 //raw settings changes forces a rebuild of the provider
                 if (providers.TryGetValue(newSettings.Id, out provider))
                 {
                     providers.Remove(newSettings.Id);
                     disconnectTask = DisconnectProvider(provider);
                 }
                 else
                     disconnectTask = Task.CompletedTask;
                 if (newSettings.Enabled.Value)
                 {
                     provider = providerFactory.CreateProvider(newSettings);
                     providers.Add(newSettings.Id, provider);
                 }
             }
             lock (mappedChannels)
                 foreach (var I in mappedChannels.Where(x => x.Value.ProviderId == newSettings.Id).Select(x => x.Key).ToList())
                     mappedChannels.Remove(I);
             await disconnectTask.ConfigureAwait(false);
             if (started)
             {
                 if (newSettings.Enabled.Value)
                     await provider.Connect(cancellationToken).ConfigureAwait(false);
                 lock (this)
                 {
                     //same thread shennanigans
                     var oldOne = connectionsUpdated;
                     connectionsUpdated = new TaskCompletionSource<object>();
                     oldOne.SetResult(null);
                 }
             }
         }
bool Tgstation.Server.Host.Components.Chat.Chat.Connected (long connectionId)
If a given set of ChatBot is connected
Implements Tgstation.Server.Host.Components.Chat.IChat.
Definition at line 536 of file Chat.cs.
         {
             lock (providers)
                 return providers.TryGetValue(connectionId, out var provider) && provider.Connected;
         }
async Task Tgstation.Server.Host.Components.Chat.Chat.DeleteConnection (long connectionId, CancellationToken cancellationToken)
Disconnects and deletes a given connection
Implements Tgstation.Server.Host.Components.Chat.IChat.
Definition at line 551 of file Chat.cs.
         {
             var provider = await RemoveProvider(connectionId, true, cancellationToken).ConfigureAwait(false);
             if (provider != null)
                 try
                 {
                     await provider.Disconnect(cancellationToken).ConfigureAwait(false);
                 }
                 finally
                 {
                     provider.Dispose();
                 }
         }
void Tgstation.Server.Host.Components.Chat.Chat.Dispose ()
Definition at line 122 of file Chat.cs.
Referenced by Tgstation.Server.Host.Components.Instance.Dispose().
         {
             handlerCts.Dispose();
             foreach (var I in providers)
                 I.Value.Dispose();
         }
async Task Tgstation.Server.Host.Components.Chat.Chat.MonitorMessages (CancellationToken cancellationToken) private
Monitors active providers for new Messages
Parameters
cancellationToken The CancellationToken for the operation
Returns
A Task representing the running operation
Definition at line 301 of file Chat.cs.
         {
             var messageTasks = new Dictionary<IProvider, Task<Message>>();
             try
             {
                 while (!cancellationToken.IsCancellationRequested)
                 {
                     //prune disconnected providers
                     foreach (var I in messageTasks.Where(x => !x.Key.Connected).ToList())
                         messageTasks.Remove(I.Key);
                     //add new ones
                     Task updatedTask;
                     lock (this)
                         updatedTask = connectionsUpdated.Task;
                     lock (providers)
                         foreach (var I in providers)
                             if (I.Value.Connected && !messageTasks.ContainsKey(I.Value))
                                 messageTasks.Add(I.Value, I.Value.NextMessage(cancellationToken));
                     if (messageTasks.Count == 0)
                     {
                         await Task.Delay(1000, cancellationToken).ConfigureAwait(false);
                         continue;
                     }
                     //wait for a message
                     await Task.WhenAny(updatedTask, Task.WhenAny(messageTasks.Select(x => x.Value))).ConfigureAwait(false);
                     //process completed ones
                     foreach (var I in messageTasks.Where(x => x.Value.IsCompleted).ToList())
                     {
                         var message = await I.Value.ConfigureAwait(false);
                         await ProcessMessage(I.Key, message, cancellationToken).ConfigureAwait(false);
                         messageTasks.Remove(I.Key);
                     }
                 }
             }
             catch (OperationCanceledException) { }
             catch (Exception e)
             {
                 logger.LogError("Message monitor crashed!: Exception: {0}", e);
             }
         }
async Task Tgstation.Server.Host.Components.Chat.Chat.ProcessMessage (IProvider provider, Message message, CancellationToken cancellationToken) private
Processes a message
Parameters
provider The IProvider who recevied message
message The Message to process
cancellationToken The CancellationToken for the operation
Returns
A Task representing the running operation
Definition at line 165 of file Chat.cs.
References Tgstation.Server.Host.Components.Chat.Providers.IProvider.BotMention, Tgstation.Server.Host.Components.Chat.User.Channel, Tgstation.Server.Host.Components.Chat.Providers.IProvider.Connected, Tgstation.Server.Host.Components.Chat.Providers.Message.Content, Tgstation.Server.Host.Components.Chat.Channel.IsAdmin, Tgstation.Server.Host.Components.Chat.Channel.IsPrivate, Tgstation.Server.Host.Components.Chat.Channel.RealId, Tgstation.Server.Host.Components.Chat.Channel.Tag, and Tgstation.Server.Host.Components.Chat.Providers.Message.User.
         {
             //map the channel if it's private and we haven't seen it
             lock (providers)
             {
                 var providerId = providers.Where(x => x.Value == provider).Select(x => x.Key).First();
                 var enumerable = mappedChannels.Where(x => x.Value.ProviderId == providerId && x.Value.ProviderChannelId == message.User.Channel.RealId);
                 if (message.User.Channel.IsPrivate)
                     lock (mappedChannels)
                     {
                         if (!provider.Connected)
                             return;
                         if (!enumerable.Any())
{
                             ulong newId;
                             lock (this)
                                 newId = channelIdCounter++;
                             mappedChannels.Add(newId, new ChannelMapping
{
                                 IsWatchdogChannel = false,
                                 ProviderChannelId = message.User.Channel.RealId,
                                 ProviderId = providerId,
                                 Channel = message.User.Channel
                             });
                             message.User.Channel.RealId = newId;
                         }
                         else
                             message.User.Channel.RealId = enumerable.First().Key;
                     }
                 else
                 {
                     //need to add tag and isAdminChannel
                     var mapping = enumerable.First().Value;
                     message.User.Channel.Tag = mapping.Channel.Tag;
                     message.User.Channel.IsAdmin = mapping.Channel.IsAdmin;
                 }
             }
             var splits = new List<string>(message.Content.Trim().Split(' '));
             var address = splits[0];
             if (address.Length > 1 && (address[address.Length - 1] == ':' || address[address.Length - 1] == ','))
                 address = address.Substring(0, address.Length - 1);
             address = address.ToUpperInvariant();
             var addressed = address == CommonMention.ToUpperInvariant() || address == provider.BotMention.ToUpperInvariant();
             if (!addressed && !message.User.Channel.IsPrivate)
                 //no mention
                 return;
             logger.LogTrace("Chat command: {0}. User (True provider Id): {1}", message.Content, JsonConvert.SerializeObject(message.User));
             if (addressed)
                 splits.RemoveAt(0);
             if (splits.Count == 0)
             {
                 //just a mention
                 await SendMessage("Hi!", new List<ulong> { message.User.Channel.RealId }, cancellationToken).ConfigureAwait(false);
                 return;
             }
             var command = splits[0].ToUpperInvariant();
             splits.RemoveAt(0);
             var arguments = String.Join(" ", splits);
             try
             {
                 async Task<ICommand> GetCommand(string commandName)
                 {
                     if (!builtinCommands.TryGetValue(commandName, out var handler))
                     {
                         var tasks = trackingContexts.Select(x => x.GetCustomCommands(cancellationToken));
                         await Task.WhenAll(tasks).ConfigureAwait(false);
                         handler = tasks.SelectMany(x => x.Result).Where(x => x.Name.ToUpperInvariant() == commandName).FirstOrDefault();
                     }
                     return handler;
                 };
                 const string UnknownCommandMessage = "Unknown command! Type '?' or 'help' for available commands.";
                 if (command == "HELP" || command == "?")
                 {
                     string helpText;
                     if (splits.Count == 0)
                     {
                         var allCommands = builtinCommands.Select(x => x.Value).ToList();
                         var tasks = trackingContexts.Select(x => x.GetCustomCommands(cancellationToken));
                         await Task.WhenAll(tasks).ConfigureAwait(false);
                         allCommands.AddRange(tasks.SelectMany(x => x.Result));
                         helpText = String.Format(CultureInfo.InvariantCulture, "Available commands (Type '?' or 'help' and then a command name for more details): {0}", String.Join(", ", allCommands.Select(x => x.Name)));
                     }
                     else
                     {
                         var helpHandler = await GetCommand(splits[0].ToUpperInvariant()).ConfigureAwait(false);
                         if (helpHandler != default)
                             helpText = String.Format(CultureInfo.InvariantCulture, "{0}: {1}{2}", helpHandler.Name, helpHandler.HelpText, helpHandler.AdminOnly ? " - May only be used in admin channels" : String.Empty);
                         else
                             helpText = UnknownCommandMessage;
                     }
                     await SendMessage(helpText, new List<ulong> { message.User.Channel.RealId }, cancellationToken).ConfigureAwait(false);
                     return;
                 }
                 var commandHandler = await GetCommand(command).ConfigureAwait(false);
                 if (commandHandler.AdminOnly && !message.User.Channel.IsAdmin)
                 {
                     await SendMessage("Use this command in an admin channel!", new List<ulong> { message.User.Channel.RealId }, cancellationToken).ConfigureAwait(false);
                     return;
                 }
                 if (commandHandler == default)
                 {
                     await SendMessage(UnknownCommandMessage, new List<ulong> { message.User.Channel.RealId }, cancellationToken).ConfigureAwait(false);
                     return;
                 }
                 var result = await commandHandler.Invoke(arguments, message.User, cancellationToken).ConfigureAwait(false);
                 if (result != null)
                     await SendMessage(result, new List<ulong> { message.User.Channel.RealId }, cancellationToken).ConfigureAwait(false);
             }
             catch (Exception e)
             {
                 //error bc custom commands should reply about why it failed
                 logger.LogError("Error processing chat command: {0}", e);
                 await SendMessage("Internal error processing command!", new List<ulong> { message.User.Channel.RealId }, cancellationToken).ConfigureAwait(false);
             }
         }
void Tgstation.Server.Host.Components.Chat.Chat.RegisterCommandHandler (ICustomCommandHandler customCommandHandler)
Registers a customCommandHandler to use
Implements Tgstation.Server.Host.Components.Chat.IChat.
Definition at line 543 of file Chat.cs.
         {
             if (this.customCommandHandler != null)
                 throw new InvalidOperationException("RegisterCommandHandler() already called!");
             this.customCommandHandler = customCommandHandler ?? throw new ArgumentNullException(nameof(customCommandHandler));
         }
async Task<IProvider> Tgstation.Server.Host.Components.Chat.Chat.RemoveProvider (long connectionId, bool updateTrackings, CancellationToken cancellationToken) private
Remove a IProvider from providers and mappedChannels optionally updating the trackingContexts as well
Parameters
connectionId The ChatBot.Id of the IProvider to delete
updateTrackings If trackingContexts should be update
cancellationToken The CancellationToken for the operation
Returns
A Task<TResult> resulting in the IProvider being removed if it exists, otherwise
Definition at line 136 of file Chat.cs.
         {
             IProvider provider;
             lock (providers)
                 if (!providers.TryGetValue(connectionId, out provider))
                     return null;
             Task task;
             lock (mappedChannels)
             {
                 foreach (var I in mappedChannels.Where(x => x.Value.ProviderId == connectionId).Select(x => x.Key).ToList())
                     mappedChannels.Remove(I);
                 if (updateTrackings)
                     lock (trackingContexts)
                         task = Task.WhenAll(trackingContexts.Select(x => x.SetChannels(mappedChannels.Select(y => y.Value.Channel), cancellationToken)));
                 else
                     task = Task.CompletedTask;
             }
             await task.ConfigureAwait(false);
             return provider;
         }
Task Tgstation.Server.Host.Components.Chat.Chat.SendBroadcast (string message, CancellationToken cancellationToken)
Send a chat to all channels
Implements Tgstation.Server.Host.Components.Chat.IChat.
Definition at line 566 of file Chat.cs.
         {
             List<ulong> wdChannels;
             lock (mappedChannels)   //so it doesn't change while we're using it
                 wdChannels = mappedChannels.Select(x => x.Key).ToList();
             return SendMessage(message, wdChannels, cancellationToken);
         }
Task Tgstation.Server.Host.Components.Chat.Chat.SendMessage (string message, IEnumerable< ulong > channelIds, CancellationToken cancellationToken)
Send a chat message to a given set of channelIds
Implements Tgstation.Server.Host.Components.Chat.IChat.
Definition at line 452 of file Chat.cs.
         {
             if (message == null)
                 throw new ArgumentNullException(nameof(message));
             if (channelIds == null)
                 throw new ArgumentNullException(nameof(channelIds));
             return Task.WhenAll(channelIds.Select(x =>
             {
                 ChannelMapping channelMapping;
                 lock (mappedChannels)
                     if (!mappedChannels.TryGetValue(x, out channelMapping))
                         return Task.CompletedTask;
                 IProvider provider;
                 lock (providers)
                     if (!providers.TryGetValue(channelMapping.ProviderId, out provider))
                         return Task.CompletedTask;
                 return provider.SendMessage(channelMapping.ProviderChannelId, message, cancellationToken);
             }));
         }
Task Tgstation.Server.Host.Components.Chat.Chat.SendUpdateMessage (string message, CancellationToken cancellationToken)
Send a chat message to configured update channels
Implements Tgstation.Server.Host.Components.Chat.IChat.
Definition at line 484 of file Chat.cs.
         {
             List<ulong> wdChannels;
             message = String.Format(CultureInfo.InvariantCulture, "DM: {0}", message);
             lock (mappedChannels)   //so it doesn't change while we're using it
                 wdChannels = mappedChannels.Where(x => x.Value.IsUpdatesChannel).Select(x => x.Key).ToList();
             return SendMessage(message, wdChannels, cancellationToken);
         }
Task Tgstation.Server.Host.Components.Chat.Chat.SendWatchdogMessage (string message, CancellationToken cancellationToken)
Send a chat message to configured watchdog channels
Implements Tgstation.Server.Host.Components.Chat.IChat.
Definition at line 474 of file Chat.cs.
         {
             List<ulong> wdChannels;
             message = String.Format(CultureInfo.InvariantCulture, "WD: {0}", message);
             lock (mappedChannels)   //so it doesn't change while we're using it
                 wdChannels = mappedChannels.Where(x => x.Value.IsWatchdogChannel).Select(x => x.Key).ToList();
             return SendMessage(message, wdChannels, cancellationToken);
         }
async Task Tgstation.Server.Host.Components.Chat.Chat.StartAsync (CancellationToken cancellationToken)
Definition at line 494 of file Chat.cs.
Referenced by Tgstation.Server.Host.Components.Instance.StartAsync().
         {
             foreach (var I in commandFactory.GenerateCommands())
                 builtinCommands.Add(I.Name.ToUpperInvariant(), I);
             await Task.WhenAll(initialChatBots.Select(x => ChangeSettings(x, cancellationToken))).ConfigureAwait(false);
             await Task.WhenAll(providers.Select(x => x.Value).Select(x => x.Connect(cancellationToken))).ConfigureAwait(false);
             await Task.WhenAll(initialChatBots.Select(x => ChangeChannels(x.Id, x.Channels, cancellationToken))).ConfigureAwait(false);
             chatHandler = MonitorMessages(handlerCts.Token);
             started = true;
         }
async Task Tgstation.Server.Host.Components.Chat.Chat.StopAsync (CancellationToken cancellationToken)
Definition at line 506 of file Chat.cs.
Referenced by Tgstation.Server.Host.Components.Instance.StartAsync().
         {
             handlerCts.Cancel();
             await chatHandler.ConfigureAwait(false);
             await Task.WhenAll(providers.Select(x => x.Value).Select(x => x.Disconnect(cancellationToken))).ConfigureAwait(false);
         }
async Task<IJsonTrackingContext> Tgstation.Server.Host.Components.Chat.Chat.TrackJsons (string basePath, string channelsJsonName, string commandsJsonName, CancellationToken cancellationToken)
Start tracking json files for commands and channels
Implements Tgstation.Server.Host.Components.Chat.IChat.
Definition at line 514 of file Chat.cs.
         {
             if (customCommandHandler == null)
                 throw new InvalidOperationException("RegisterCommandHandler() hasn't been called!");
             JsonTrackingContext context = null;
             context = new JsonTrackingContext(ioManager, customCommandHandler, () =>
             {
                 lock (trackingContexts)
                     trackingContexts.Remove(context);
             }, ioManager.ConcatPath(basePath, commandsJsonName), ioManager.ConcatPath(basePath, channelsJsonName));
             Task task;
             lock (trackingContexts)
             {
                 trackingContexts.Add(context);
                 lock (mappedChannels)
                     task = Task.WhenAll(trackingContexts.Select(x => x.SetChannels(mappedChannels.Select(y => y.Value.Channel), cancellationToken)));
             }
             await task.ConfigureAwait(false);
             return context;
         }
Member Data Documentation
readonly Dictionary<string, ICommand> Tgstation.Server.Host.Components.Chat.Chat.builtinCommands private
Unchanging ICommands in the Chat mapped by ICommand.Name
Definition at line 44 of file Chat.cs.
ulong Tgstation.Server.Host.Components.Chat.Chat.channelIdCounter private
Used for remapping Channel.RealIds
Definition at line 89 of file Chat.cs.
Task Tgstation.Server.Host.Components.Chat.Chat.chatHandler private
The Task that monitors incoming chat messages
Definition at line 79 of file Chat.cs.
readonly ICommandFactory Tgstation.Server.Host.Components.Chat.Chat.commandFactory private
The ICommandFactory for the Chat
Definition at line 34 of file Chat.cs.
const string Tgstation.Server.Host.Components.Chat.Chat.CommonMention = "!tgs" private
Definition at line 19 of file Chat.cs.
TaskCompletionSource<object> Tgstation.Server.Host.Components.Chat.Chat.connectionsUpdated private
The TaskCompletionSource<TResult> that completes when ChatBots change
Definition at line 84 of file Chat.cs.
ICustomCommandHandler Tgstation.Server.Host.Components.Chat.Chat.customCommandHandler private
The ICustomCommandHandler for the ChangeChannels(long, IEnumerable<Api.Models.ChatChannel>, CancellationToken)
Definition at line 74 of file Chat.cs.
readonly CancellationTokenSource Tgstation.Server.Host.Components.Chat.Chat.handlerCts private
The CancellationTokenSource for chatHandler
Definition at line 64 of file Chat.cs.
readonly List<Models.ChatBot> Tgstation.Server.Host.Components.Chat.Chat.initialChatBots private
The initial Models.ChatBot for the Chat
Definition at line 69 of file Chat.cs.
readonly IIOManager Tgstation.Server.Host.Components.Chat.Chat.ioManager private
The IIOManager for the Chat
Definition at line 29 of file Chat.cs.
readonly ILogger<Chat> Tgstation.Server.Host.Components.Chat.Chat.logger private
The ILogger for the Chat
Definition at line 39 of file Chat.cs.
readonly Dictionary<ulong, ChannelMapping> Tgstation.Server.Host.Components.Chat.Chat.mappedChannels private
Map of Channel.RealIds to ChannelMappings
Definition at line 54 of file Chat.cs.
readonly IProviderFactory Tgstation.Server.Host.Components.Chat.Chat.providerFactory private
The IProviderFactory for the Chat
Definition at line 24 of file Chat.cs.
readonly Dictionary<long, IProvider> Tgstation.Server.Host.Components.Chat.Chat.providers private
Map of IProviders in use, keyed by ChatBot.Id
Definition at line 49 of file Chat.cs.
bool Tgstation.Server.Host.Components.Chat.Chat.started private
If StartAsync(CancellationToken) has been called
Definition at line 94 of file Chat.cs.
readonly List<IJsonTrackingContext> Tgstation.Server.Host.Components.Chat.Chat.trackingContexts private
The active IJsonTrackingContexts for the Chat
Definition at line 59 of file Chat.cs.
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Chat/Chat.cs