tgstation-server: Tgstation.Server.Client.Extensions.HubConnectionExtensions Class Reference
Tgstation.Server.Client.Extensions.HubConnectionExtensions Class Reference
Extension methods for the HubConnection class.
Static Public Member Functions
static void ProxyOn< TClientProxy > (this HubConnection hubConnection, TClientProxy proxy)
Apply a given proxy to a given hubConnection .
Static Private Member Functions
static void ProxyOn (this HubConnection hubConnection, Type proxyType, object proxyObject)
Apply a given proxyObject to a given hubConnection .
Detailed Description
Extension methods for the HubConnection class.
Definition at line 13 of file HubConnectionExtensions.cs.
Member Function Documentation
ProxyOn()
static void Tgstation.Server.Client.Extensions.HubConnectionExtensions.ProxyOn (this HubConnection hubConnection, Type proxyType, object proxyObject) static private
Apply a given proxyObject to a given hubConnection .
Parameters
hubConnection The HubConnection to proxy on.
proxyType The Type of proxyObject .
proxyObject The object to forward operations to.
Definition at line 39 of file HubConnectionExtensions.cs.
        {
            var clientMethods = proxyType.GetMethods();
            var cancellationTokenType = typeof(CancellationToken);
            foreach (var clientMethod in clientMethods)
            {
                var parametersList = clientMethod
                    .GetParameters()
                    .Select(parameterInfo => parameterInfo.ParameterType)
                    .ToList();
                var cancellationTokenIndex = parametersList.IndexOf(cancellationTokenType);
                if (cancellationTokenIndex != -1)
                {
                    parametersList.RemoveAt(cancellationTokenIndex);
#if DEBUG
                    if (parametersList.IndexOf(cancellationTokenType) != -1)
                        throw new InvalidOperationException("Cannot ProxyOn a method with multiple CancellationToken parameters!");
#endif
                }
                var parameters = parametersList.ToArray();
                object?[] AddCancellationTokenToParametersArray(object?[] parametersArray)
                {
                    if (cancellationTokenIndex == -1)
                        return parametersArray;
                    var newList = parametersArray.ToList();
                    newList.Insert(cancellationTokenIndex, CancellationToken.None);
                    return newList.ToArray();
                }
                var returnType = clientMethod.ReturnType;
                if (returnType != typeof(Task))
                {
                    if (returnType.BaseType != typeof(Task))
                        throw new InvalidOperationException($"Return type {returnType} of {proxyType.FullName}.{clientMethod.Name} is not supported! Only Task and derivatives are supported.");
                    var resultProperty = returnType.GetProperty(nameof(Task<object>.Result));
                    hubConnection.On(
                        clientMethod.Name,
                        parameters,
                        async (parameterArray, _) =>
{
                            var task = (Task)clientMethod.Invoke(proxyObject, AddCancellationTokenToParametersArray(parameterArray));
                            await task;
                            return resultProperty.GetValue(task);
                        },
                        hubConnection);
                }
                else
                    hubConnection.On(
                        clientMethod.Name,
                        parameters,
                        (parameterArray) =>
{
                            return (Task)clientMethod.Invoke(proxyObject, AddCancellationTokenToParametersArray(parameterArray));
                        });
            }
            foreach (var inheritedInterface in proxyType.GetInterfaces())
                ProxyOn(hubConnection, inheritedInterface, proxyObject);
        }
References Tgstation.Server.Client.Extensions.HubConnectionExtensions.ProxyOn().
Referenced by Tgstation.Server.Client.Extensions.HubConnectionExtensions.ProxyOn(), and Tgstation.Server.Client.Extensions.HubConnectionExtensions.ProxyOn< TClientProxy >().
ProxyOn< TClientProxy >()
static void Tgstation.Server.Client.Extensions.HubConnectionExtensions.ProxyOn< TClientProxy > (this HubConnection hubConnection, TClientProxy proxy) static
Apply a given proxy to a given hubConnection .
Template Parameters
TClientProxy The strongly typed client proxy.
Parameters
hubConnection The HubConnection to proxy on.
proxy The TClientProxy to forward operations to.
Type Constraints
TClientProxy : class
Definition at line 21 of file HubConnectionExtensions.cs.
                               : class
        {
            if (hubConnection == null)
                throw new ArgumentNullException(nameof(hubConnection));
            if (proxy == null)
                throw new ArgumentNullException(nameof(proxy));
            ProxyOn(hubConnection, typeof(TClientProxy), proxy);
        }
References Tgstation.Server.Client.Extensions.HubConnectionExtensions.ProxyOn().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Client/Extensions/HubConnectionExtensions.cs