tgstation-server: Tgstation.Server.Host.System.ProcessExecutor Class Reference
Tgstation.Server.Host.System.ProcessExecutor Class Reference sealed
Public Member Functions
ProcessExecutor (IProcessFeatures processFeatures, IIOManager ioManager, ILogger< ProcessExecutor > logger, ILoggerFactory loggerFactory)
Initializes a new instance of the ProcessExecutor class.
IProcess? GetProcess (int id)
Get a IProcess by id .
Parameters
id The IProcess.Id.
Returns
The IProcess represented by id on success, null on failure.
IProcess GetCurrentProcess ()
Get a IProcess representing the running executable.
Returns
The current IProcess.
async ValueTask< IProcess > LaunchProcess (string fileName, string workingDirectory, string arguments, CancellationToken cancellationToken, IReadOnlyDictionary< string, string >? environment, string? fileRedirect, bool readStandardHandles, bool noShellExecute)
Launch a IProcess.
Parameters
fileName The full path to the executable file.
workingDirectory The working directory for the IProcess.
arguments The arguments for the IProcess.
cancellationToken The CancellationToken for the operation.
environment A IReadOnlyDictionary<TKey, TValue> of environment variables to set.
fileRedirect File to write process output and error streams to. Requires readStandardHandles to be true.
readStandardHandles If the process output and error streams should be read.
noShellExecute If shell execute should not be used. Must be set if readStandardHandles is set.
Returns
A ValueTask<TResult> resulting in the new IProcess.
IProcess? GetProcessByName (string name)
Get a IProcess with a given name .
Parameters
name The name of the process executable without the extension.
Returns
The IProcess represented by name on success, null on failure.
Static Public Member Functions
static void WithProcessLaunchExclusivity (Action action)
Runs a given action making sure to not launch any processes while its running.
Private Member Functions
async Task< string?> ConsumeReaders (global::System.Diagnostics.Process handle, Task< int > startupAndPid, string? fileRedirect, CancellationToken cancellationToken)
Consume the stdout/stderr streams into a Task.
Process CreateFromExistingHandle (global::System.Diagnostics.Process handle)
Create a IProcess given an existing handle .
Private Attributes
readonly IProcessFeatures processFeatures
The IProcessFeatures for the ProcessExecutor.
readonly IIOManager ioManager
The IIOManager for the ProcessExecutor.
readonly ILogger< ProcessExecutor > logger
The ILogger for the ProcessExecutor.
readonly ILoggerFactory loggerFactory
The ILoggerFactory for the ProcessExecutor.
Static Private Attributes
static readonly ReaderWriterLockSlim ExclusiveProcessLaunchLock = new()
ReaderWriterLockSlim for WithProcessLaunchExclusivity(Action).
Detailed Description
Definition at line 18 of file ProcessExecutor.cs.
Constructor & Destructor Documentation
ProcessExecutor()
Tgstation.Server.Host.System.ProcessExecutor.ProcessExecutor (IProcessFeatures processFeatures, IIOManager ioManager, ILogger< ProcessExecutor > logger, ILoggerFactory loggerFactory)
Initializes a new instance of the ProcessExecutor class.
Parameters
processFeatures The value of processFeatures.
ioManager The value of ioManager.
logger The value of logger.
loggerFactory The value of loggerFactory.
Definition at line 69 of file ProcessExecutor.cs.
        {
            this.processFeatures = processFeatures ?? throw new ArgumentNullException(nameof(processFeatures));
            this.ioManager = ioManager ?? throw new ArgumentNullException(nameof(ioManager));
            this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
            this.loggerFactory = loggerFactory ?? throw new ArgumentNullException(nameof(loggerFactory));
        }
References Tgstation.Server.Host.System.ProcessExecutor.ioManager, Tgstation.Server.Host.System.ProcessExecutor.logger, Tgstation.Server.Host.System.ProcessExecutor.loggerFactory, and Tgstation.Server.Host.System.ProcessExecutor.processFeatures.
Member Function Documentation
ConsumeReaders()
async Task< string?> Tgstation.Server.Host.System.ProcessExecutor.ConsumeReaders (global::System::Diagnostics::Process handle, Task< int > startupAndPid, string? fileRedirect, CancellationToken cancellationToken) private
Consume the stdout/stderr streams into a Task.
Parameters
handle The global::System.Diagnostics.Process.
startupAndPid The Task<TResult> resulting in the global::System.Diagnostics.Process.Id of the started process.
fileRedirect The optional path to redirect the streams to.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the program's output/error text if fileRedirect is null, null otherwise.
Definition at line 248 of file ProcessExecutor.cs.
        {
            handle.StartInfo.RedirectStandardOutput = true;
            handle.StartInfo.RedirectStandardError = true;
            bool writingToFile;
            await using var fileStream = (writingToFile = fileRedirect != null) ? ioManager.CreateAsyncSequentialWriteStream(fileRedirect!) : null;
            await using var fileWriter = fileStream != null ? new StreamWriter(fileStream) : null;
            var stringBuilder = fileStream == null ? new StringBuilder() : null;
            var dataChannel = Channel.CreateUnbounded<string>(
                new UnboundedChannelOptions
                {
                    AllowSynchronousContinuations = !writingToFile,
                    SingleReader = true,
                    SingleWriter = false,
                });
            var handlesOpen = 2;
            async void DataReceivedHandler(object sender, DataReceivedEventArgs eventArgs)
            {
                var line = eventArgs.Data;
                if (line == null)
                {
                    var handlesRemaining = Interlocked.Decrement(ref handlesOpen);
                    if (handlesRemaining == 0)
                        dataChannel.Writer.Complete();
                    return;
                }
                try
                {
                    await dataChannel.Writer.WriteAsync(line, cancellationToken);
                }
                catch (OperationCanceledException ex)
                {
                    logger.LogWarning(ex, "Handle channel write interrupted!");
                }
            }
            handle.OutputDataReceived += DataReceivedHandler;
            handle.ErrorDataReceived += DataReceivedHandler;
            async ValueTask OutputWriter()
            {
                var enumerable = dataChannel.Reader.ReadAllAsync(cancellationToken);
                if (writingToFile)
                {
                    var enumerator = enumerable.GetAsyncEnumerator(cancellationToken);
                    var nextEnumeration = enumerator.MoveNextAsync();
                    while (await nextEnumeration)
                    {
                        var text = enumerator.Current;
                        nextEnumeration = enumerator.MoveNextAsync();
                        await fileWriter!.WriteLineAsync(text.AsMemory(), cancellationToken);
                        if (!nextEnumeration.IsCompleted)
                            await fileWriter.FlushAsync(cancellationToken);
                    }
                }
                else
                    await foreach (var text in enumerable)
                        stringBuilder!.AppendLine(text);
            }
            var pid = await startupAndPid;
            logger.LogTrace("Starting read for PID {pid}...", pid);
            using (cancellationToken.Register(() => dataChannel.Writer.TryComplete()))
            {
                handle.BeginOutputReadLine();
                using (cancellationToken.Register(handle.CancelOutputRead))
                {
                    handle.BeginErrorReadLine();
                    using (cancellationToken.Register(handle.CancelErrorRead))
                    {
                        try
{
                            await OutputWriter();
                            logger.LogTrace("Finished read for PID {pid}", pid);
                        }
                        catch (OperationCanceledException ex)
{
                            logger.LogWarning(ex, "PID {pid} stream reading interrupted!", pid);
                            if (writingToFile)
                                await fileWriter!.WriteLineAsync("-- Process detached, log truncated. This is likely due a to TGS restart --");
                        }
                    }
                }
            }
            return stringBuilder?.ToString();
        }
References Tgstation.Server.Host.IO.IIOManager.CreateAsyncSequentialWriteStream(), Tgstation.Server.Host.System.ProcessExecutor.ioManager, and Tgstation.Server.Host.System.ProcessExecutor.logger.
Referenced by Tgstation.Server.Host.System.ProcessExecutor.LaunchProcess().
CreateFromExistingHandle()
Process Tgstation.Server.Host.System.ProcessExecutor.CreateFromExistingHandle (global::System::Diagnostics::Process handle) private
Create a IProcess given an existing handle .
Parameters
handle The global::System.Diagnostics.Process to create a IProcess from.
Returns
The IProcess based on handle .
Definition at line 350 of file ProcessExecutor.cs.
        {
            try
            {
                var pid = handle.Id;
                return new Process(
                    processFeatures,
                    handle,
                    null,
                    null,
                    loggerFactory.CreateLogger<Process>(),
                    true);
            }
            catch
            {
                handle.Dispose();
                throw;
            }
        }
References Tgstation.Server.Host.System.Process.Id, Tgstation.Server.Host.System.ProcessExecutor.loggerFactory, and Tgstation.Server.Host.System.ProcessExecutor.processFeatures.
Referenced by Tgstation.Server.Host.System.ProcessExecutor.GetCurrentProcess(), Tgstation.Server.Host.System.ProcessExecutor.GetProcess(), and Tgstation.Server.Host.System.ProcessExecutor.GetProcessByName().
GetCurrentProcess()
IProcess Tgstation.Server.Host.System.ProcessExecutor.GetCurrentProcess ()
Get a IProcess representing the running executable.
Returns
The current IProcess.
Implements Tgstation.Server.Host.System.IProcessExecutor.
Definition at line 100 of file ProcessExecutor.cs.
        {
            logger.LogTrace("Getting current process...");
            var handle = global::System.Diagnostics.Process.GetCurrentProcess();
            return CreateFromExistingHandle(handle);
        }
References Tgstation.Server.Host.System.ProcessExecutor.CreateFromExistingHandle(), and Tgstation.Server.Host.System.ProcessExecutor.logger.
GetProcess()
IProcess? Tgstation.Server.Host.System.ProcessExecutor.GetProcess (int id)
Get a IProcess by id .
Parameters
id The IProcess.Id.
Returns
The IProcess represented by id on success, null on failure.
Implements Tgstation.Server.Host.System.IProcessExecutor.
Definition at line 82 of file ProcessExecutor.cs.
        {
            logger.LogDebug("Attaching to process {pid}...", id);
            global::System.Diagnostics.Process handle;
            try
            {
                handle = global::System.Diagnostics.Process.GetProcessById(id);
            }
            catch (Exception e)
            {
                logger.LogDebug(e, "Unable to get process {pid}!", id);
                return null;
            }
            return CreateFromExistingHandle(handle);
        }
References Tgstation.Server.Host.System.ProcessExecutor.CreateFromExistingHandle(), and Tgstation.Server.Host.System.ProcessExecutor.logger.
GetProcessByName()
IProcess? Tgstation.Server.Host.System.ProcessExecutor.GetProcessByName (string name)
Get a IProcess with a given name .
Parameters
name The name of the process executable without the extension.
Returns
The IProcess represented by name on success, null on failure.
Implements Tgstation.Server.Host.System.IProcessExecutor.
Definition at line 220 of file ProcessExecutor.cs.
        {
            logger.LogTrace("GetProcessByName: {processName}...", name ?? throw new ArgumentNullException(nameof(name)));
            var procs = global::System.Diagnostics.Process.GetProcessesByName(name);
            global::System.Diagnostics.Process? handle = null;
            foreach (var proc in procs)
                if (handle == null)
                    handle = proc;
                else
                {
                    logger.LogTrace("Disposing extra found PID: {pid}...", proc.Id);
                    proc.Dispose();
                }
            if (handle == null)
                return null;
            return CreateFromExistingHandle(handle);
        }
References Tgstation.Server.Host.System.ProcessExecutor.CreateFromExistingHandle(), and Tgstation.Server.Host.System.ProcessExecutor.logger.
LaunchProcess()
async ValueTask< IProcess > Tgstation.Server.Host.System.ProcessExecutor.LaunchProcess (string fileName, string workingDirectory, string arguments, CancellationToken cancellationToken, IReadOnlyDictionary< string, string >? environment, string? fileRedirect, bool readStandardHandles, bool noShellExecute)
Launch a IProcess.
Parameters
fileName The full path to the executable file.
workingDirectory The working directory for the IProcess.
arguments The arguments for the IProcess.
cancellationToken The CancellationToken for the operation.
environment A IReadOnlyDictionary<TKey, TValue> of environment variables to set.
fileRedirect File to write process output and error streams to. Requires readStandardHandles to be true.
readStandardHandles If the process output and error streams should be read.
noShellExecute If shell execute should not be used. Must be set if readStandardHandles is set.
Returns
A ValueTask<TResult> resulting in the new IProcess.
Implements Tgstation.Server.Host.System.IProcessExecutor.
Definition at line 108 of file ProcessExecutor.cs.
        {
            ArgumentNullException.ThrowIfNull(fileName);
            ArgumentNullException.ThrowIfNull(workingDirectory);
            ArgumentNullException.ThrowIfNull(arguments);
            var enviromentLogLines = environment == null
                ? String.Empty
                : String.Concat(environment.Select(kvp => $"{Environment.NewLine}\t- {kvp.Key}={kvp.Value}"));
            if (noShellExecute)
                logger.LogDebug(
                "Launching process in {workingDirectory}: {exe} {arguments}{environment}",
                workingDirectory,
                fileName,
                arguments,
                enviromentLogLines);
            else
                logger.LogDebug(
                "Shell launching process in {workingDirectory}: {exe} {arguments}{environment}",
                workingDirectory,
                fileName,
                arguments,
                enviromentLogLines);
            var handle = new global::System.Diagnostics.Process();
            try
            {
                handle.StartInfo.FileName = fileName;
                handle.StartInfo.Arguments = arguments;
                if (environment != null)
                    foreach (var kvp in environment)
                        handle.StartInfo.Environment.Add(kvp!);
                handle.StartInfo.WorkingDirectory = workingDirectory;
                handle.StartInfo.UseShellExecute = !noShellExecute;
                Task<string?>? readTask = null;
                CancellationTokenSource? disposeCts = null;
                try
                {
                    TaskCompletionSource<int>? processStartTcs = null;
                    if (readStandardHandles)
                    {
                        processStartTcs = new TaskCompletionSource<int>();
                        disposeCts = new CancellationTokenSource();
                        readTask = ConsumeReaders(handle, processStartTcs.Task, fileRedirect, disposeCts.Token);
                    }
                    int pid;
                    try
                    {
                        ExclusiveProcessLaunchLock.EnterReadLock();
                        try
{
                            handle.Start();
                        }
                        finally
{
                            ExclusiveProcessLaunchLock.ExitReadLock();
                        }
                        try
{
                            pid = await processFeatures.HandleProcessStart(handle, cancellationToken);
                        }
                        catch
{
                            handle.Kill();
                            throw;
                        }
                        processStartTcs?.SetResult(pid);
                    }
                    catch (Exception ex)
                    {
                        processStartTcs?.SetException(ex);
                        throw;
                    }
                    var process = new Process(
                        processFeatures,
                        handle,
                        disposeCts,
                        readTask,
                        loggerFactory.CreateLogger<Process>(),
                        false);
                    return process;
                }
                catch
                {
                    disposeCts?.Dispose();
                    throw;
                }
            }
            catch
            {
                handle.Dispose();
                throw;
            }
        }
References Tgstation.Server.Host.System.ProcessExecutor.ConsumeReaders(), Tgstation.Server.Host.System.ProcessExecutor.ExclusiveProcessLaunchLock, Tgstation.Server.Host.System.IProcessFeatures.HandleProcessStart(), Tgstation.Server.Host.System.ProcessExecutor.logger, Tgstation.Server.Host.System.ProcessExecutor.loggerFactory, and Tgstation.Server.Host.System.ProcessExecutor.processFeatures.
Referenced by Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.Install().
WithProcessLaunchExclusivity()
static void Tgstation.Server.Host.System.ProcessExecutor.WithProcessLaunchExclusivity (Action action) static
Runs a given action making sure to not launch any processes while its running.
Parameters
action The Action to execute.
Definition at line 49 of file ProcessExecutor.cs.
        {
            ExclusiveProcessLaunchLock.EnterWriteLock();
            try
            {
                action();
            }
            finally
            {
                ExclusiveProcessLaunchLock.ExitWriteLock();
            }
        }
References Tgstation.Server.Host.System.ProcessExecutor.ExclusiveProcessLaunchLock.
Referenced by Tgstation.Server.Host.Extensions.SocketExtensions.BindTest().
Member Data Documentation
ExclusiveProcessLaunchLock
readonly ReaderWriterLockSlim Tgstation.Server.Host.System.ProcessExecutor.ExclusiveProcessLaunchLock = new() static private
ReaderWriterLockSlim for WithProcessLaunchExclusivity(Action).
Definition at line 23 of file ProcessExecutor.cs.
Referenced by Tgstation.Server.Host.System.ProcessExecutor.LaunchProcess(), and Tgstation.Server.Host.System.ProcessExecutor.WithProcessLaunchExclusivity().
ioManager
readonly IIOManager Tgstation.Server.Host.System.ProcessExecutor.ioManager private
The IIOManager for the ProcessExecutor.
Definition at line 33 of file ProcessExecutor.cs.
Referenced by Tgstation.Server.Host.System.ProcessExecutor.ConsumeReaders(), and Tgstation.Server.Host.System.ProcessExecutor.ProcessExecutor().
logger
readonly ILogger<ProcessExecutor> Tgstation.Server.Host.System.ProcessExecutor.logger private
The ILogger for the ProcessExecutor.
Definition at line 38 of file ProcessExecutor.cs.
Referenced by Tgstation.Server.Host.System.ProcessExecutor.ConsumeReaders(), Tgstation.Server.Host.System.ProcessExecutor.GetCurrentProcess(), Tgstation.Server.Host.System.ProcessExecutor.GetProcess(), Tgstation.Server.Host.System.ProcessExecutor.GetProcessByName(), Tgstation.Server.Host.System.ProcessExecutor.LaunchProcess(), and Tgstation.Server.Host.System.ProcessExecutor.ProcessExecutor().
loggerFactory
readonly ILoggerFactory Tgstation.Server.Host.System.ProcessExecutor.loggerFactory private
The ILoggerFactory for the ProcessExecutor.
Definition at line 43 of file ProcessExecutor.cs.
Referenced by Tgstation.Server.Host.System.ProcessExecutor.CreateFromExistingHandle(), Tgstation.Server.Host.System.ProcessExecutor.LaunchProcess(), and Tgstation.Server.Host.System.ProcessExecutor.ProcessExecutor().
processFeatures
readonly IProcessFeatures Tgstation.Server.Host.System.ProcessExecutor.processFeatures private
The IProcessFeatures for the ProcessExecutor.
Definition at line 28 of file ProcessExecutor.cs.
Referenced by Tgstation.Server.Host.System.ProcessExecutor.CreateFromExistingHandle(), Tgstation.Server.Host.System.ProcessExecutor.LaunchProcess(), and Tgstation.Server.Host.System.ProcessExecutor.ProcessExecutor().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/System/ProcessExecutor.cs