tgstation-server: Tgstation.Server.Client.Components.ConfigurationClient Class Reference
Tgstation.Server.Client.Components.ConfigurationClient Class Reference
Public Member Functions
ConfigurationClient (IApiClient apiClient, Instance instance)
Initializes a new instance of the ConfigurationClient class.
ValueTask DeleteEmptyDirectory (IConfigurationFile directory, CancellationToken cancellationToken)
Delete an empty directory .
Parameters
directory The IConfigurationFile representing the directory to delete.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
ValueTask< ConfigurationFileResponse > CreateDirectory (IConfigurationFile directory, CancellationToken cancellationToken)
Creates an empty directory .
Parameters
directory The IConfigurationFile representing the directory to create.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the new ConfigurationFileResponse.
ValueTask< List< ConfigurationFileResponse > > List (PaginationSettings? paginationSettings, string directory, CancellationToken cancellationToken)
List configuration files.
Parameters
paginationSettings The optional PaginationSettings for the operation.
directory The path to the directory to list files in.
cancellationToken The CancellationToken for the operation.
Returns
A List<T> of ConfigurationFileResponses in the directory .
async ValueTask< Tuple< ConfigurationFileResponse, Stream > > Read (IConfigurationFile file, CancellationToken cancellationToken)
Read a file .
Parameters
file The IConfigurationFile file to read.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask resulting in a Tuple<T1, T2> containing the ConfigurationFileResponse and downloaded FileTicketResponse Stream.
async ValueTask< ConfigurationFileResponse > Write (ConfigurationFileRequest file, Stream uploadStream, CancellationToken cancellationToken)
Overwrite a file .
Parameters
file The ConfigurationFileRequest.
uploadStream The Stream of uploaded data. If null, a delete will be attempted.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the new ConfigurationFileResponse.
Public Member Functions inherited from Tgstation.Server.Client.PaginatedClient
PaginatedClient (IApiClient apiClient)
Initializes a new instance of the PaginatedClient class.
ValueTask< List< ConfigurationFileResponse > > List (PaginationSettings? paginationSettings, string directory, CancellationToken cancellationToken)
List configuration files.
ValueTask< Tuple< ConfigurationFileResponse, Stream > > Read (IConfigurationFile file, CancellationToken cancellationToken)
Read a file .
ValueTask< ConfigurationFileResponse > Write (ConfigurationFileRequest file, Stream uploadStream, CancellationToken cancellationToken)
Overwrite a file .
ValueTask DeleteEmptyDirectory (IConfigurationFile directory, CancellationToken cancellationToken)
Delete an empty directory .
ValueTask< ConfigurationFileResponse > CreateDirectory (IConfigurationFile directory, CancellationToken cancellationToken)
Creates an empty directory .
Private Member Functions
ValueTask< ConfigurationFileResponse > ConfigurationFileResponse (Routes.Configuration, directory, instance.Id!.Value, cancellationToken)
Private Attributes
readonly Instance instance
The Instance for the ConfigurationClient.
Additional Inherited Members
Protected Member Functions inherited from Tgstation.Server.Client.PaginatedClient
async ValueTask< List< TModel > > ReadPaged< TModel > (PaginationSettings? paginationSettings, string route, long? instanceId, CancellationToken cancellationToken)
Reads a given route with paged results.
Properties inherited from Tgstation.Server.Client.PaginatedClient
IApiClient ApiClient [get]
The IApiClient for the PaginatedClient.
Detailed Description
Definition at line 15 of file ConfigurationClient.cs.
Constructor & Destructor Documentation
ConfigurationClient()
Tgstation.Server.Client.Components.ConfigurationClient.ConfigurationClient (IApiClient apiClient, Instance instance)
Initializes a new instance of the ConfigurationClient class.
Parameters
apiClient The IApiClient for the PaginatedClient.
instance The value of instance.
Definition at line 27 of file ConfigurationClient.cs.
            : base(apiClient)
        {
            this.instance = instance ?? throw new ArgumentNullException(nameof(instance));
        }
References Tgstation.Server.Client.Components.ConfigurationClient.instance.
Member Function Documentation
ConfigurationFileResponse()
ValueTask< ConfigurationFileResponse > Tgstation.Server.Client.Components.ConfigurationClient.ConfigurationFileResponse (Routes. Configuration, directory , instance.Id!. Value, cancellationToken) private
CreateDirectory()
ValueTask< ConfigurationFileResponse > Tgstation.Server.Client.Components.ConfigurationClient.CreateDirectory (IConfigurationFile directory, CancellationToken cancellationToken)
Creates an empty directory .
Parameters
directory The IConfigurationFile representing the directory to create.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the new ConfigurationFileResponse.
Implements Tgstation.Server.Client.Components.IConfigurationClient.
DeleteEmptyDirectory()
ValueTask Tgstation.Server.Client.Components.ConfigurationClient.DeleteEmptyDirectory (IConfigurationFile directory, CancellationToken cancellationToken)
Delete an empty directory .
Parameters
directory The IConfigurationFile representing the directory to delete.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Client.Components.IConfigurationClient.
List()
ValueTask< List< ConfigurationFileResponse > > Tgstation.Server.Client.Components.ConfigurationClient.List (PaginationSettings? paginationSettings, string directory, CancellationToken cancellationToken)
List configuration files.
Parameters
paginationSettings The optional PaginationSettings for the operation.
directory The path to the directory to list files in.
cancellationToken The CancellationToken for the operation.
Returns
A List<T> of ConfigurationFileResponses in the directory .
Implements Tgstation.Server.Client.Components.IConfigurationClient.
Read()
async ValueTask< Tuple< ConfigurationFileResponse, Stream > > Tgstation.Server.Client.Components.ConfigurationClient.Read (IConfigurationFile file, CancellationToken cancellationToken)
Read a file .
Parameters
file The IConfigurationFile file to read.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask resulting in a Tuple<T1, T2> containing the ConfigurationFileResponse and downloaded FileTicketResponse Stream.
Implements Tgstation.Server.Client.Components.IConfigurationClient.
Definition at line 51 of file ConfigurationClient.cs.
        {
            if (file == null)
                throw new ArgumentNullException(nameof(file));
            var configFile = await ApiClient.Read<ConfigurationFileResponse>(
                Routes.ConfigurationFile + Routes.SanitizeGetPath(file.Path ?? throw new InvalidOperationException("file.Path should not be null!")),
                instance.Id!.Value,
                cancellationToken)
                .ConfigureAwait(false);
            var downloadStream = await ApiClient.Download(configFile, cancellationToken).ConfigureAwait(false);
            try
            {
                return Tuple.Create(configFile, downloadStream);
            }
            catch
            {
                downloadStream.Dispose();
                throw;
            }
        }
References Tgstation.Server.Client.ApiClient.Download(), Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Client.Components.ConfigurationClient.instance, Tgstation.Server.Api.Models.IConfigurationFile.Path, and Tgstation.Server.Api.Routes.SanitizeGetPath().
Write()
async ValueTask< ConfigurationFileResponse > Tgstation.Server.Client.Components.ConfigurationClient.Write (ConfigurationFileRequest file, Stream uploadStream, CancellationToken cancellationToken)
Overwrite a file .
Parameters
file The ConfigurationFileRequest.
uploadStream The Stream of uploaded data. If null, a delete will be attempted.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the new ConfigurationFileResponse.
Implements Tgstation.Server.Client.Components.IConfigurationClient.
Definition at line 73 of file ConfigurationClient.cs.
        {
            long initialStreamPosition = 0;
            MemoryStream? memoryStream = null;
            if (uploadStream?.CanSeek == false)
                memoryStream = new MemoryStream();
            else if (uploadStream != null)
                initialStreamPosition = uploadStream.Position;
            using (memoryStream)
            {
                var configFileTask = ApiClient.Update<ConfigurationFileRequest, ConfigurationFileResponse>(
                    Routes.Configuration,
                    file ?? throw new ArgumentNullException(nameof(file)),
                    instance.Id!.Value,
                    cancellationToken);
                if (memoryStream != null)
                    await uploadStream!.CopyToAsync(memoryStream).ConfigureAwait(false);
                var configFile = await configFileTask.ConfigureAwait(false);
                var streamUsed = memoryStream ?? uploadStream;
                streamUsed?.Seek(initialStreamPosition, SeekOrigin.Begin);
                await ApiClient.Upload(configFile, streamUsed, cancellationToken).ConfigureAwait(false);
                return configFile;
            }
        }
References Tgstation.Server.Api.Routes.Configuration, Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Client.Components.ConfigurationClient.instance, and Tgstation.Server.Client.ApiClient.Upload().
Member Data Documentation
instance
readonly Instance Tgstation.Server.Client.Components.ConfigurationClient.instance private
The Instance for the ConfigurationClient.
Definition at line 20 of file ConfigurationClient.cs.
Referenced by Tgstation.Server.Client.Components.ConfigurationClient.ConfigurationClient(), Tgstation.Server.Client.Components.ConfigurationClient.Read(), and Tgstation.Server.Client.Components.ConfigurationClient.Write().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Client/Components/ConfigurationClient.cs