tgstation-server: TGCommandLine.DMCompileCommand Class Reference
TGCommandLine.DMCompileCommand Class Reference
Public Member Functions
DMCompileCommand ()
override string GetArgumentString ()
Override to add argument text to the Command Format is <required> <arguments> [optional] [arguments]
override string GetHelpText ()
Override to add usage text to the Command
Public Member Functions inherited from TGServiceInterface.Command
virtual ExitCode DoRun (IList< string > parameters)
Caller of Run(IList<string>), can be used to modify the root behaviour of the Command
virtual void PrintHelp ()
Prints usage text of the Command to the invoker
Protected Member Functions
override ExitCode Run (IList< string > parameters)
Override to do the actions of the Command
Additional Inherited Members
Static Public Attributes inherited from TGServiceInterface.Command
static ThreadLocal< Action< string > > OutputProcVar = new ThreadLocal<Action<string>>()
Proc that will show a message to the Command invoker. Do not call directly, use OutputProc(string) instead
Static Protected Member Functions inherited from TGServiceInterface.Command
static void OutputProc (string message)
Write output to the Command invoker
Properties inherited from TGServiceInterface.Command
string Keyword [get, protected set]
The text that invokes this Command. Set in constructor
int RequiredParameters [get, protected set]
The number of parameters this Command requires. Set in Constructor
Detailed Description
Definition at line 21 of file DMCommands.cs.
Constructor & Destructor Documentation
TGCommandLine.DMCompileCommand.DMCompileCommand ()
Definition at line 23 of file DMCommands.cs.
References TGServiceInterface.Command.Keyword.
         {
             Keyword = "compile";
         }
Member Function Documentation
override string TGCommandLine.DMCompileCommand.GetArgumentString () virtual
Override to add argument text to the Command Format is <required> <arguments> [optional] [arguments]
Returns
Formatted argument text for the Command
Reimplemented from TGServiceInterface.Command.
Definition at line 67 of file DMCommands.cs.
         {
             return "[--wait]";
         }
override string TGCommandLine.DMCompileCommand.GetHelpText () virtual
Override to add usage text to the Command
Returns
Formatted usage text for the Command
Implements TGServiceInterface.Command.
Definition at line 72 of file DMCommands.cs.
         {
             return "Starts a compile/update job optionally waiting for completion";
         }
override ExitCode TGCommandLine.DMCompileCommand.Run (IList< string > parameters) protected virtual
Override to do the actions of the Command
Parameters
parameters List of string parameters passed to the Command. Guaranteed to have at least RequiredParameters non-empty/whitespace entries
Returns
An ExitCode describing the execution of the Command
Implements TGServiceInterface.Command.
Definition at line 28 of file DMCommands.cs.
References TGServiceInterface.ITGCompiler.GetStatus(), TGServiceInterface.ITGByond.GetVersion(), and TGServiceInterface.Command.OutputProc().
         {
             var DM = Server.GetComponent<ITGCompiler>();
             var stat = DM.GetStatus();
             if (stat != TGCompilerStatus.Initialized)
             {
                 OutputProc("Error: Compiler is " + ((stat == TGCompilerStatus.Uninitialized) ? "unintialized!" : "busy with another task!"));
                 return ExitCode.ServerError;
             }
             if (Server.GetComponent<ITGByond>().GetVersion(TGByondVersion.Installed) == null)
             {
                 Console.Write("Error: BYOND is not installed!");
                 return ExitCode.ServerError;
             }
             if (!DM.Compile())
             {
                 OutputProc("Error: Unable to start compilation!");
                 var err = DM.CompileError();
                 if (err != null)
                     OutputProc(err);
                 return ExitCode.ServerError;
             }
             OutputProc("Compile job started");
             if (parameters.Count > 0 && parameters[0] == "--wait")
             {
                 do
                 {
                     Thread.Sleep(1000);
                 } while (DM.GetStatus() == TGCompilerStatus.Compiling);
                 var res = DM.CompileError();
                 OutputProc(res ?? "Compilation successful");
                 if (res != null)
                     return ExitCode.ServerError;
             }
             return ExitCode.Normal;
         }
The documentation for this class was generated from the following file:
TGCommandLine/DMCommands.cs