tgstation-server: Tgstation.Server.Host.Extensions.ResultExtensions Class Reference
Tgstation.Server.Host.Extensions.ResultExtensions Class Reference
Extensions for IResult.
Static Public Member Functions
static string LogFormat (this IResult result, uint level=0)
Converts a given result into a log entry string.
Static Private Member Functions
static void FormatErrorDetails (IPropertyErrorDetails propertyErrorDetails, StringBuilder stringBuilder)
Formats given propertyErrorDetails into a given stringBuilder .
static void FormatErrorDetails (IEnumerable< IErrorDetails >? errorDetails, StringBuilder stringBuilder)
Formats given errorDetails into a given stringBuilder .
Detailed Description
Extensions for IResult.
Definition at line 15 of file ResultExtensions.cs.
Member Function Documentation
FormatErrorDetails() [1/2]
static void Tgstation.Server.Host.Extensions.ResultExtensions.FormatErrorDetails (IEnumerable< IErrorDetails >? errorDetails, StringBuilder stringBuilder) static private
Formats given errorDetails into a given stringBuilder .
Parameters
errorDetails The IEnumerable<T> of IErrorDetails.
stringBuilder The StringBuilder to mutate.
Definition at line 119 of file ResultExtensions.cs.
        {
            if (errorDetails == null)
                return;
            stringBuilder.Append('[');
            foreach (var error in errorDetails)
            {
                stringBuilder.Append(error.Code);
                stringBuilder.Append(':');
                stringBuilder.Append(error.Message);
                stringBuilder.Append(',');
            }
            stringBuilder.Remove(stringBuilder.Length - 1, 1);
            stringBuilder.Append(']');
        }
FormatErrorDetails() [2/2]
static void Tgstation.Server.Host.Extensions.ResultExtensions.FormatErrorDetails (IPropertyErrorDetails propertyErrorDetails, StringBuilder stringBuilder) static private
Formats given propertyErrorDetails into a given stringBuilder .
Parameters
propertyErrorDetails The IPropertyErrorDetails.
stringBuilder The StringBuilder to mutate.
Definition at line 86 of file ResultExtensions.cs.
        {
            if (propertyErrorDetails == null)
                return;
            FormatErrorDetails(propertyErrorDetails.Errors, stringBuilder);
            if (propertyErrorDetails.Errors != null && propertyErrorDetails.MemberErrors != null)
            {
                stringBuilder.Append(',');
            }
            if (propertyErrorDetails.MemberErrors != null)
            {
                stringBuilder.Append('{');
                foreach (var error in propertyErrorDetails.MemberErrors)
                {
                    stringBuilder.Append(error.Key);
                    stringBuilder.Append(':');
                    FormatErrorDetails(error.Value, stringBuilder);
                    stringBuilder.Append(',');
                }
                stringBuilder.Remove(stringBuilder.Length - 1, 1);
                stringBuilder.Append('}');
            }
        }
References Tgstation.Server.Host.Extensions.ResultExtensions.FormatErrorDetails().
Referenced by Tgstation.Server.Host.Extensions.ResultExtensions.FormatErrorDetails(), and Tgstation.Server.Host.Extensions.ResultExtensions.LogFormat().
LogFormat()
static string Tgstation.Server.Host.Extensions.ResultExtensions.LogFormat (this IResult result, uint level = 0) static
Converts a given result into a log entry string.
Parameters
result The IResult to convert.
level Used internally for nesting.
Returns
The string formatted result .
Definition at line 23 of file ResultExtensions.cs.
        {
            ArgumentNullException.ThrowIfNull(result);
            if (result.IsSuccess)
                return "SUCCESS?";
            var stringBuilder = new StringBuilder();
            if (result.Error != null)
            {
                stringBuilder.Append(result.Error.Message);
                if (result.Error is RestResultError<RestError> restError)
                {
                    stringBuilder.Append(" (");
                    if (restError.Error != null)
                    {
                        stringBuilder.Append(restError.Error.Code);
                        stringBuilder.Append(": ");
                        stringBuilder.Append(restError.Error.Message);
                        stringBuilder.Append('|');
                    }
                    stringBuilder.Append(restError.Message);
                    if ((restError.Error?.Errors.HasValue ?? false) && restError.Error.Errors.Value.Count > 0)
                    {
                        stringBuilder.Append(" (");
                        foreach (var error in restError.Error.Errors.Value)
{
                            stringBuilder.Append(error.Key);
                            stringBuilder.Append(':');
                            if (error.Value.IsT0)
{
                                FormatErrorDetails(error.Value.AsT0, stringBuilder);
                            }
                            else
                                FormatErrorDetails(error.Value.AsT1, stringBuilder);
                            stringBuilder.Append(',');
                        }
                        stringBuilder.Remove(stringBuilder.Length - 1, 1);
                    }
                    stringBuilder.Append(')');
                }
            }
            if (result.Inner != null)
            {
                stringBuilder.Append(Environment.NewLine);
                ++level;
                for (var i = 0; i < level; ++i)
                    stringBuilder.Append('\t');
                stringBuilder.Append(result.Inner.LogFormat(level));
            }
            return stringBuilder.ToString();
        }
References Tgstation.Server.Host.Extensions.ResultExtensions.FormatErrorDetails().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Extensions/ResultExtensions.cs