tgstation-server: Tgstation.Server.Host.Components.Watchdog.PosixWatchdog Class Reference
Tgstation.Server.Host.Components.Watchdog.PosixWatchdog Class Reference
A variant of the WindowsWatchdog that works on POSIX systems.
Public Member Functions
PosixWatchdog (IChatManager chat, ISessionControllerFactory sessionControllerFactory, IDmbFactory dmbFactory, ISessionPersistor sessionPersistor, IJobManager jobManager, IServerControl serverControl, IAsyncDelayer asyncDelayer, IIOManager diagnosticsIOManager, IEventConsumer eventConsumer, IRemoteDeploymentManagerFactory remoteDeploymentManagerFactory, IIOManager gameIOManager, ISymlinkFactory symlinkFactory, ILogger< PosixWatchdog > logger, DreamDaemonLaunchParameters initialLaunchParameters, Api.Models.Instance instance, bool autoStart)
Initializes a new instance of the PosixWatchdog class.
Public Member Functions inherited from Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog
WindowsWatchdog (IChatManager chat, ISessionControllerFactory sessionControllerFactory, IDmbFactory dmbFactory, ISessionPersistor sessionPersistor, IJobManager jobManager, IServerControl serverControl, IAsyncDelayer asyncDelayer, IIOManager diagnosticsIOManager, IEventConsumer eventConsumer, IRemoteDeploymentManagerFactory remoteDeploymentManagerFactory, IIOManager gameIOManager, ISymlinkFactory symlinkFactory, ILogger< WindowsWatchdog > logger, DreamDaemonLaunchParameters initialLaunchParameters, Api.Models.Instance instance, bool autoStart)
Initializes a new instance of the WindowsWatchdog class.
Public Member Functions inherited from Tgstation.Server.Host.Components.Watchdog.BasicWatchdog
BasicWatchdog (IChatManager chat, ISessionControllerFactory sessionControllerFactory, IDmbFactory dmbFactory, ISessionPersistor sessionPersistor, IJobManager jobManager, IServerControl serverControl, IAsyncDelayer asyncDelayer, IIOManager diagnosticsIOManager, IEventConsumer eventConsumer, IRemoteDeploymentManagerFactory remoteDeploymentManagerFactory, ILogger< BasicWatchdog > logger, DreamDaemonLaunchParameters initialLaunchParameters, Api.Models.Instance instance, bool autoStart)
Initializes a new instance of the BasicWatchdog class.
override Task ResetRebootState (CancellationToken cancellationToken)
Cancels pending graceful actions.
sealed override Task InstanceRenamed (string newInstanceName, CancellationToken cancellationToken)
Called when the owning Instance is renamed.
Public Member Functions inherited from Tgstation.Server.Host.Components.Watchdog.WatchdogBase
async ValueTask DisposeAsync ()
async Task ChangeSettings (DreamDaemonLaunchParameters launchParameters, CancellationToken cancellationToken)
Changes the ActiveLaunchParameters. If currently running, may trigger a graceful restart.
async Task< string > HandleChatCommand (string commandName, string arguments, ChatUser sender, CancellationToken cancellationToken)
Handle a chat command.
async Task Launch (CancellationToken cancellationToken)
Start the IWatchdog.
virtual async Task ResetRebootState (CancellationToken cancellationToken)
Cancels pending graceful actions.
async Task Restart (bool graceful, CancellationToken cancellationToken)
Restarts the watchdog.
async Task StartAsync (CancellationToken cancellationToken)
Task StopAsync (CancellationToken cancellationToken)
async Task Terminate (bool graceful, CancellationToken cancellationToken)
Stops the watchdog.
async Task HandleRestart (Version updateVersion, bool graceful, CancellationToken cancellationToken)
Handle a restart of the server.
abstract Task InstanceRenamed (string newInstanceName, CancellationToken cancellationToken)
Called when the owning Instance is renamed.
async Task CreateDump (CancellationToken cancellationToken)
Attempt to create a process dump for DreamDaemon.
Task Launch (CancellationToken cancellationToken)
Start the IWatchdog.
Task ChangeSettings (DreamDaemonLaunchParameters launchParameters, CancellationToken cancellationToken)
Changes the ActiveLaunchParameters. If currently running, may trigger a graceful restart.
Task Restart (bool graceful, CancellationToken cancellationToken)
Restarts the watchdog.
Task Terminate (bool graceful, CancellationToken cancellationToken)
Stops the watchdog.
Task ResetRebootState (CancellationToken cancellationToken)
Cancels pending graceful actions.
Task CreateDump (CancellationToken cancellationToken)
Attempt to create a process dump for DreamDaemon.
Task HandleEvent (EventType eventType, IEnumerable< string > parameters, CancellationToken cancellationToken)
Handle a given eventType .
Task InstanceRenamed (string newInstanceName, CancellationToken cancellationToken)
Called when the owning Instance is renamed.
Task< string > HandleChatCommand (string commandName, string arguments, ChatUser sender, CancellationToken cancellationToken)
Handle a chat command.
Task HandleRestart (Version updateVersion, bool graceful, CancellationToken cancellationToken)
Handle a restart of the server.
Protected Member Functions
override async Task InitialLink (CancellationToken cancellationToken)
Create the initial link to the live game directory using ActiveSwappable.
override async Task InitController (Task chatTask, ReattachInformation reattachInfo, CancellationToken cancellationToken)
Starts all ISessionControllers.
Protected Member Functions inherited from Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog
override async Task DisposeAndNullControllersImpl ()
Call IDisposable.Dispose and null the fields for all ISessionControllers.
override async Task< MonitorAction > HandleNormalReboot (CancellationToken cancellationToken)
Handler for MonitorActivationReason.ActiveServerRebooted when the RebootState is RebootState.Normal.
override async Task HandleNewDmbAvailable (CancellationToken cancellationToken)
Handler for MonitorActivationReason.NewDmbAvailable.
sealed override async Task< IDmbProvider > PrepServerForLaunch (IDmbProvider dmbToUse, CancellationToken cancellationToken)
Prepare the server to launch a new instance with the WatchdogBase.ActiveLaunchParameters and a given dmbToUse .
virtual Task InitialLink (CancellationToken cancellationToken)
Create the initial link to the live game directory using ActiveSwappable.
Protected Member Functions inherited from Tgstation.Server.Host.Components.Watchdog.BasicWatchdog
override async Task< MonitorAction > HandleMonitorWakeup (MonitorActivationReason reason, CancellationToken cancellationToken)
Handles the actions to take when the monitor has to "wake up".
override async Task DisposeAndNullControllersImpl ()
Call IDisposable.Dispose and null the fields for all ISessionControllers.
sealed override ISessionController GetActiveController ()
Get the active ISessionController.
override async Task InitController (Task chatTask, ReattachInformation reattachInfo, CancellationToken cancellationToken)
Starts all ISessionControllers.
virtual Task< MonitorAction > HandleNormalReboot (CancellationToken cancellationToken)
Handler for MonitorActivationReason.ActiveServerRebooted when the RebootState is RebootState.Normal.
virtual Task HandleNewDmbAvailable (CancellationToken cancellationToken)
Handler for MonitorActivationReason.NewDmbAvailable.
virtual Task< IDmbProvider > PrepServerForLaunch (IDmbProvider dmbToUse, CancellationToken cancellationToken)
Prepare the server to launch a new instance with the WatchdogBase.ActiveLaunchParameters and a given dmbToUse .
Protected Member Functions inherited from Tgstation.Server.Host.Components.Watchdog.WatchdogBase
WatchdogBase (IChatManager chat, ISessionControllerFactory sessionControllerFactory, IDmbFactory dmbFactory, ISessionPersistor sessionPersistor, IJobManager jobManager, IServerControl serverControl, IAsyncDelayer asyncDelayer, IIOManager diagnosticsIOManager, IEventConsumer eventConsumer, IRemoteDeploymentManagerFactory remoteDeploymentManagerFactory, ILogger< WatchdogBase > logger, DreamDaemonLaunchParameters initialLaunchParameters, Api.Models.Instance metadata, bool autoStart)
Initializes a new instance of the WatchdogBase class.
abstract Task InitController (Task chatTask, ReattachInformation reattachInfo, CancellationToken cancellationToken)
Starts all ISessionControllers.
async Task LaunchNoLock (bool startMonitor, bool announce, bool announceFailure, ReattachInformation reattachInfo, CancellationToken cancellationToken)
Launches the watchdog.
async Task< bool > StopMonitor ()
Stops MonitorLifetimes(CancellationToken). Doesn't kill the servers.
async Task CheckLaunchResult (ISessionController controller, string serverName, CancellationToken cancellationToken)
Check the LaunchResult of a given controller for errors and throw a JobException if any are detected.
async Task ReattachFailure (CancellationToken cancellationToken)
Call from InitController(Task, ReattachInformation, CancellationToken) when a reattach operation fails to attempt a fresh start.
abstract Task DisposeAndNullControllersImpl ()
Call IDisposable.Dispose and null the fields for all ISessionControllers.
async Task DisposeAndNullControllers (CancellationToken cancellationToken)
Wrapper for DisposeAndNullControllersImpl under a locked context.
abstract ISessionController GetActiveController ()
Get the active ISessionController.
abstract Task< MonitorAction > HandleMonitorWakeup (MonitorActivationReason activationReason, CancellationToken cancellationToken)
Handles the actions to take when the monitor has to "wake up".
Task BeforeApplyDmb (Models.CompileJob newCompileJob, CancellationToken cancellationToken)
To be called before a given newCompileJob goes live.
async Task HandleNonRelayedEvent (EventType eventType, IEnumerable< string > parameters, CancellationToken cancellationToken)
Handle a given eventType without re-throwing errors.
Private Attributes
IDmbProvider hardLinkedDmb
If the swappable game directory is currently a rename of the compile job.
Additional Inherited Members
Properties inherited from Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog
SwappableDmbProvider ActiveSwappable [get, private set]
The SwappableDmbProvider for WatchdogBase.LastLaunchParameters.
IIOManager GameIOManager [get]
The IIOManager for the WindowsWatchdog pointing to the Game directory.
Properties inherited from Tgstation.Server.Host.Components.Watchdog.BasicWatchdog
sealed override bool AlphaIsActive [get]
If the alpha server is the active server.
sealed override? RebootState RebootState [get]
The Session.RebootState of the active server.
ISessionController Server [get, private set]
The single ISessionController.
Properties inherited from Tgstation.Server.Host.Components.Watchdog.WatchdogBase
WatchdogStatus Status [get, set]
The current WatchdogStatus.
abstract bool AlphaIsActive [get]
If the alpha server is the active server.
DreamDaemonLaunchParameters ActiveLaunchParameters [get, protected set]
The DreamDaemonLaunchParameters to be applied.
DreamDaemonLaunchParameters LastLaunchParameters [get, protected set]
The DreamDaemonLaunchParameters the active server is using.
Models.CompileJob ActiveCompileJob [get]
Retrieves the Models.CompileJob currently running on the server.
abstract ? RebootState RebootState [get]
The Session.RebootState of the active server.
TaskCompletionSource< object > ActiveParametersUpdated [get, set]
TaskCompletionSource<TResult> that completes when ActiveLaunchParameters are changed and we are running.
ISessionPersistor SessionPersistor [get]
The ISessionPersistor for the WatchdogBase.
ILogger< WatchdogBase > Logger [get]
The ILogger for the WatchdogBase.
IChatManager Chat [get]
The IChatManager for the WatchdogBase.
ISessionControllerFactory SessionControllerFactory [get]
The ISessionControllerFactory for the WatchdogBase.
IDmbFactory DmbFactory [get]
The IDmbFactory for the WatchdogBase.
IAsyncDelayer AsyncDelayer [get]
The IAsyncDelayer for the WatchdogBase.
Properties inherited from Tgstation.Server.Host.Components.Watchdog.IWatchdog
WatchdogStatus Status [get]
The current WatchdogStatus.
bool AlphaIsActive [get]
If the alpha server is the active server.
Models.CompileJob ActiveCompileJob [get]
Retrieves the Models.CompileJob currently running on the server.
DreamDaemonLaunchParameters ActiveLaunchParameters [get]
The DreamDaemonLaunchParameters to be applied.
DreamDaemonLaunchParameters LastLaunchParameters [get]
The DreamDaemonLaunchParameters the active server is using.
RebootState? RebootState [get]
The Session.RebootState of the active server.
Detailed Description
A variant of the WindowsWatchdog that works on POSIX systems.
Definition at line 22 of file PosixWatchdog.cs.
Constructor & Destructor Documentation
PosixWatchdog()
Tgstation.Server.Host.Components.Watchdog.PosixWatchdog.PosixWatchdog (IChatManager chat, ISessionControllerFactory sessionControllerFactory, IDmbFactory dmbFactory, ISessionPersistor sessionPersistor, IJobManager jobManager, IServerControl serverControl, IAsyncDelayer asyncDelayer, IIOManager diagnosticsIOManager, IEventConsumer eventConsumer, IRemoteDeploymentManagerFactory remoteDeploymentManagerFactory, IIOManager gameIOManager, ISymlinkFactory symlinkFactory, ILogger< PosixWatchdog > logger, DreamDaemonLaunchParameters initialLaunchParameters, Api.Models.Instance instance, bool autoStart)
Initializes a new instance of the PosixWatchdog class.
Parameters
chat The IChatManager for the WatchdogBase.
sessionControllerFactory The ISessionControllerFactory for the WatchdogBase.
dmbFactory The IDmbFactory for the WatchdogBase.
sessionPersistor The ISessionPersistor for the WatchdogBase.
jobManager The IJobManager for the WatchdogBase.
serverControl The IServerControl for the WatchdogBase.
asyncDelayer The IAsyncDelayer for the WatchdogBase.
diagnosticsIOManager The IIOManager for the WatchdogBase.
eventConsumer The IEventConsumer for the WatchdogBase.
remoteDeploymentManagerFactory The IRemoteDeploymentManagerFactory for the WatchdogBase.
gameIOManager The IIOManager pointing to the game directory for the WindowsWatchdog..
symlinkFactory The ISymlinkFactory for the WindowsWatchdog.
logger The ILogger for the WatchdogBase.
initialLaunchParameters The DreamDaemonLaunchParameters for the WatchdogBase.
instance The Api.Models.Instance for the WatchdogBase.
autoStart The autostart value for the WatchdogBase.
Definition at line 48 of file PosixWatchdog.cs.
            : base(
                  chat,
                  sessionControllerFactory,
                  dmbFactory,
                  sessionPersistor,
                  jobManager,
                  serverControl,
                  asyncDelayer,
                  diagnosticsIOManager,
                  eventConsumer,
                  remoteDeploymentManagerFactory,
                  gameIOManager,
                  symlinkFactory,
                  logger,
                  initialLaunchParameters,
                  instance,
                  autoStart)
        {
        }
Member Function Documentation
InitController()
override async Task Tgstation.Server.Host.Components.Watchdog.PosixWatchdog.InitController (Task chatTask, ReattachInformation reattachInfo, CancellationToken cancellationToken) protected virtual
Starts all ISessionControllers.
Reimplemented from Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.
Definition at line 108 of file PosixWatchdog.cs.
        {
            try
            {
                await base.InitController(chatTask, reattachInfo, cancellationToken).ConfigureAwait(false);
            }
            finally
            {
                // Then we move it back and apply the symlink
                if (hardLinkedDmb != null)
                {
                    try
                    {
                        Logger.LogTrace("Unhardlinking compile job...");
                        Server?.Suspend();
                        var hardLink = hardLinkedDmb.Directory;
                        var originalPosition = hardLinkedDmb.CompileJob.DirectoryName.ToString();
                        await GameIOManager.MoveDirectory(
                            hardLink,
                            originalPosition,
                            default)
                            .ConfigureAwait(false);
                    }
                    catch (Exception ex)
                    {
                        Logger.LogError(
                            ex,
                            "Failed to un-hard link compile job #{0} ({1})",
                            hardLinkedDmb.CompileJob.Id,
                            hardLinkedDmb.CompileJob.DirectoryName);
                    }
                    hardLinkedDmb = null;
                }
            }
            if (reattachInfo != null)
            {
                Logger.LogTrace("Skipping symlink due to reattach");
                return;
            }
            Logger.LogTrace("Symlinking compile job...");
            await ActiveSwappable.MakeActive(cancellationToken).ConfigureAwait(false);
            Server.Resume();
        }
References Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.ActiveSwappable, Tgstation.Server.Host.Components.Deployment.IDmbProvider.CompileJob, Tgstation.Server.Host.Components.Deployment.IDmbProvider.Directory, Tgstation.Server.Api.Models.Internal.CompileJob.DirectoryName, Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.GameIOManager, Tgstation.Server.Host.Components.Watchdog.PosixWatchdog.hardLinkedDmb, Tgstation.Server.Api.Models.EntityId.Id, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Logger, Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.MakeActive(), and Tgstation.Server.Host.IO.IIOManager.MoveDirectory().
InitialLink()
override async Task Tgstation.Server.Host.Components.Watchdog.PosixWatchdog.InitialLink (CancellationToken cancellationToken) protected virtual
Create the initial link to the live game directory using ActiveSwappable.
Reimplemented from Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.
Definition at line 86 of file PosixWatchdog.cs.
        {
            // The logic to check for an active live directory is in SwappableDmbProvider, so we just do it again here for safety
            Logger.LogTrace("Hard linking compile job...");
            // Symlinks are counted as a file on linux??
            if (await GameIOManager.DirectoryExists(ActiveSwappable.Directory, cancellationToken).ConfigureAwait(false))
                await GameIOManager.DeleteDirectory(ActiveSwappable.Directory, cancellationToken).ConfigureAwait(false);
            else
                await GameIOManager.DeleteFile(ActiveSwappable.Directory, cancellationToken).ConfigureAwait(false);
            // Instead of symlinking to begin with we actually rename the directory
            await GameIOManager.MoveDirectory(
                ActiveSwappable.CompileJob.DirectoryName.ToString(),
                ActiveSwappable.Directory,
                cancellationToken)
                .ConfigureAwait(false);
            hardLinkedDmb = ActiveSwappable;
        }
References Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.ActiveSwappable, Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.CompileJob, Tgstation.Server.Host.IO.IIOManager.DeleteDirectory(), Tgstation.Server.Host.IO.IIOManager.DeleteFile(), Tgstation.Server.Host.Components.Deployment.SwappableDmbProvider.Directory, Tgstation.Server.Host.IO.IIOManager.DirectoryExists(), Tgstation.Server.Api.Models.Internal.CompileJob.DirectoryName, Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog.GameIOManager, Tgstation.Server.Host.Components.Watchdog.PosixWatchdog.hardLinkedDmb, Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Logger, and Tgstation.Server.Host.IO.IIOManager.MoveDirectory().
Member Data Documentation
hardLinkedDmb
IDmbProvider Tgstation.Server.Host.Components.Watchdog.PosixWatchdog.hardLinkedDmb private
If the swappable game directory is currently a rename of the compile job.
Definition at line 27 of file PosixWatchdog.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.PosixWatchdog.InitController(), and Tgstation.Server.Host.Components.Watchdog.PosixWatchdog.InitialLink().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Watchdog/PosixWatchdog.cs