tgstation-server: Tgstation.Server.Common.Extensions.ValueTaskExtensions Class Reference
Tgstation.Server.Common.Extensions.ValueTaskExtensions Class Reference
Extension methods for the ValueTask and ValueTask<TResult> classes.
Static Public Member Functions
static async ValueTask< T[]> WhenAll< T > (IEnumerable< ValueTask< T > > tasks, int totalTasks)
Fully await a given list of tasks .
static async ValueTask< T[]> WhenAll< T > (IReadOnlyList< ValueTask< T > > tasks)
Fully await a given list of tasks .
static ValueTask< T[]> WhenAll< T > (params ValueTask< T >[] tasks)
Fully await a given list of tasks .
static async ValueTask WhenAll (IEnumerable< ValueTask > tasks)
Fully await a given list of tasks .
static async ValueTask WhenAll (IReadOnlyList< ValueTask > tasks)
Fully await a given list of tasks .
static ValueTask WhenAll (params ValueTask[] tasks)
Fully await a given list of tasks .
Detailed Description
Extension methods for the ValueTask and ValueTask<TResult> classes.
Definition at line 11 of file ValueTaskExtensions.cs.
Member Function Documentation
WhenAll() [1/3]
static async ValueTask Tgstation.Server.Common.Extensions.ValueTaskExtensions.WhenAll (IEnumerable< ValueTask > tasks) static
Fully await a given list of tasks .
Parameters
tasks An IEnumerable<T> of ValueTasks.
Returns
A ValueTask representing the combined await.
Definition at line 99 of file ValueTaskExtensions.cs.
        {
            if (tasks == null)
                throw new ArgumentNullException(nameof(tasks));
            // We don't allocate the list if no task throws
            Exception? exception = null;
            foreach (var task in tasks)
                try
                {
                    await task.ConfigureAwait(false);
                }
                catch (Exception ex)
                {
                    exception ??= ex;
                }
            if (exception != null)
                throw exception;
        }
Referenced by Tgstation.Server.Host.Components.Deployment.DmbFactory.CleanRegisteredCompileJob(), Tgstation.Server.Host.Components.Deployment.DmbFactory.CleanUnusedCompileJobs(), Tgstation.Server.Host.Components.Deployment.DreamMaker.CleanupFailedCompile(), Tgstation.Server.Host.Swarm.SwarmService.CommitUpdate(), Tgstation.Server.Host.Components.Deployment.DreamMaker.DeploymentProcess(), Tgstation.Server.Client.ApiClient.DisposeAsync(), Tgstation.Server.Host.Security.IdentityCache.DisposeAsync(), Tgstation.Server.Host.Components.StaticFiles.Configuration.EnsureDirectories(), Tgstation.Server.Host.Authority.Core.GraphQLAuthorityInvoker< TAuthority >.ExecuteDataLoader< TResult, TApiModel, TTransformer >(), Tgstation.Server.Host.Components.StaticFiles.Configuration.ExecuteEventScripts(), Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.GetAllAccessibleTextChannels(), Tgstation.Server.Host.Security.AuthorizationHandler.HandleAsync(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleEventImpl(), Tgstation.Server.Host.Swarm.SwarmService.HealthCheckNodes(), Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.InstallImpl(), Tgstation.Server.Host.Components.Engine.WindowsOpenDreamInstaller.InstallImpl(), Tgstation.Server.Host.Components.Engine.PosixByondInstaller.InstallImpl(), Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.InstallImpl(), Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.MapChannelsImpl(), Tgstation.Server.Host.Components.InstanceManager.OfflineInstance(), Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager.PostDeploymentComments(), Tgstation.Server.Host.Swarm.SwarmService.RemoteAbortUpdate(), Tgstation.Server.Host.Components.Chat.ChatManager.RemoveProviderChannels(), Tgstation.Server.Host.Server.RestartImpl(), Tgstation.Server.Client.ApiClient.RunRequest< TResult >(), Tgstation.Server.Host.Components.Chat.ChatManager.SendMessage(), Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.SendMessage(), Tgstation.Server.Host.Swarm.SwarmService.SendUpdatedServerListToNodes(), Tgstation.Server.Host.Swarm.SwarmService.Shutdown(), Tgstation.Server.Host.Components.Chat.ChatManager.StartAsync(), Tgstation.Server.Host.Components.Engine.EngineManager.StartAsync(), Tgstation.Server.Host.Components.InstanceManager.StopAsync(), Tgstation.Server.Host.Jobs.JobService.StopAsync(), Tgstation.Server.Host.Components.StaticFiles.Configuration.SymlinkStaticFilesTo(), and Tgstation.Server.Host.Controllers.InstanceController.Update().
WhenAll() [2/3]
static async ValueTask Tgstation.Server.Common.Extensions.ValueTaskExtensions.WhenAll (IReadOnlyList< ValueTask > tasks) static
Fully await a given list of tasks .
Parameters
tasks An IReadOnlyList<T> of ValueTasks.
Returns
A ValueTask representing the combined await.
Exceptions
AggregateException An AggregateException containing any Exceptions thrown by the tasks .
Definition at line 126 of file ValueTaskExtensions.cs.
        {
            if (tasks == null)
                throw new ArgumentNullException(nameof(tasks));
            // We don't allocate the list if no task throws
            List<Exception>? exceptions = null;
            for (var i = 0; i < tasks.Count; ++i)
                try
                {
                    var task = tasks[i];
                    await task.ConfigureAwait(false);
                }
                catch (Exception ex)
                {
                    exceptions ??= new(tasks.Count - i);
                    exceptions.Add(ex);
                }
            if (exceptions != null)
                throw new AggregateException(exceptions);
        }
WhenAll() [3/3]
static ValueTask Tgstation.Server.Common.Extensions.ValueTaskExtensions.WhenAll (params ValueTask[] tasks) static
Fully await a given list of tasks .
Parameters
tasks An Array of ValueTasks.
Returns
A ValueTask representing the combined await.
Exceptions
AggregateException An AggregateException containing any Exceptions thrown by the tasks .
WhenAll< T >() [1/3]
static async ValueTask< T[]> Tgstation.Server.Common.Extensions.ValueTaskExtensions.WhenAll< T > (IEnumerable< ValueTask< T > > tasks, int totalTasks) static
Fully await a given list of tasks .
Template Parameters
T The ValueTask<TResult>.Result type.
Parameters
tasks An IEnumerable<T> of ValueTask<TResult>s.
totalTasks The number of elements in tasks .
Returns
A ValueTask representing the combined await.
Definition at line 20 of file ValueTaskExtensions.cs.
        {
            if (tasks == null)
                throw new ArgumentNullException(nameof(tasks));
            // We don't allocate the list if no task throws
            Exception? exception = null;
            int i = 0;
            var results = new T[totalTasks];
            foreach (var task in tasks)
            {
                try
                {
                    results[i] = await task.ConfigureAwait(false);
                }
                catch (Exception ex)
                {
                    exception ??= ex;
                }
                ++i;
            }
            Debug.Assert(i == totalTasks, "Incorrect totalTasks specified!");
            if (exception != null)
                throw exception;
            return results;
        }
WhenAll< T >() [2/3]
static async ValueTask< T[]> Tgstation.Server.Common.Extensions.ValueTaskExtensions.WhenAll< T > (IReadOnlyList< ValueTask< T > > tasks) static
Fully await a given list of tasks .
Template Parameters
T The ValueTask<TResult>.Result type.
Parameters
tasks An IReadOnlyList<T> of ValueTask<TResult>s.
Returns
A ValueTask<TResult> containing the Array of results based on tasks .
Exceptions
AggregateException An AggregateException containing any Exceptions thrown by the tasks .
Definition at line 58 of file ValueTaskExtensions.cs.
        {
            if (tasks == null)
                throw new ArgumentNullException(nameof(tasks));
            var totalTasks = tasks.Count;
            if (totalTasks == 0)
                return Array.Empty<T>();
            // We don't allocate the list if no task throws
            Exception? exception = null;
            var results = new T[totalTasks];
            for (var i = 0; i < totalTasks; i++)
                try
                {
                    results[i] = await tasks[i].ConfigureAwait(false);
                }
                catch (Exception ex)
                {
                    exception ??= ex;
                }
            if (exception != null)
                throw exception;
            return results;
        }
WhenAll< T >() [3/3]
static ValueTask< T[]> Tgstation.Server.Common.Extensions.ValueTaskExtensions.WhenAll< T > (params ValueTask< T >[] tasks) static
Fully await a given list of tasks .
Template Parameters
T The ValueTask<TResult>.Result type.
Parameters
tasks An Array of ValueTask<TResult>s.
Returns
A ValueTask<TResult> containing the Array of results based on tasks .
The documentation for this class was generated from the following file:
src/Tgstation.Server.Common/Extensions/ValueTaskExtensions.cs