tgstation-server: Tgstation.Server.Host.Components.Session.SessionPersistor Class Reference
Tgstation.Server.Host.Components.Session.SessionPersistor Class Reference sealed
Public Member Functions
SessionPersistor (IDatabaseContextFactory databaseContextFactory, IDmbFactory dmbFactory, IProcessExecutor processExecutor, ILogger< SessionPersistor > logger, Api.Models.Instance metadata)
Initializes a new instance of the SessionPersistor class.
ValueTask Save (ReattachInformation reattachInformation, CancellationToken cancellationToken)
Save some reattachInformation .
Parameters
reattachInformation The ReattachInformation to save. Models.ReattachInformationBase.Id will be written back into it.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
ValueTask Update (ReattachInformation reattachInformation, CancellationToken cancellationToken)
Update some reattachInformation .
Parameters
reattachInformation The ReattachInformation to update. Requires Save(ReattachInformation, CancellationToken) to have been called on it previously or it was retrieved from Load(CancellationToken).
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
async ValueTask< ReattachInformation?> Load (CancellationToken cancellationToken)
Load a saved ReattachInformation.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the stored ReattachInformation if any.
ValueTask Clear (CancellationToken cancellationToken)
Clear any stored ReattachInformation.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Private Member Functions
async ValueTask ClearImpl (IDatabaseContext databaseContext, bool instant, CancellationToken cancellationToken)
Clear any stored ReattachInformation.
Private Attributes
readonly IDatabaseContextFactory databaseContextFactory
The IDatabaseContextFactory for the SessionPersistor.
readonly IDmbFactory dmbFactory
The IDmbFactory for the SessionPersistor.
readonly IProcessExecutor processExecutor
The IProcessExecutor for the SessionPersistor.
readonly ILogger< SessionPersistor > logger
The ILogger for the SessionPersistor.
readonly Api.Models.Instance metadata
The Api.Models.Instance for the SessionPersistor.
Detailed Description
Definition at line 17 of file SessionPersistor.cs.
Constructor & Destructor Documentation
SessionPersistor()
Tgstation.Server.Host.Components.Session.SessionPersistor.SessionPersistor (IDatabaseContextFactory databaseContextFactory, IDmbFactory dmbFactory, IProcessExecutor processExecutor, ILogger< SessionPersistor > logger, Api::Models::Instance metadata)
Initializes a new instance of the SessionPersistor class.
Parameters
databaseContextFactory The value of databaseContextFactory.
dmbFactory The value of dmbFactory.
processExecutor The value of processExecutor.
logger The value of logger.
metadata The value of metadata.
Definition at line 52 of file SessionPersistor.cs.
        {
            this.databaseContextFactory = databaseContextFactory ?? throw new ArgumentNullException(nameof(databaseContextFactory));
            this.dmbFactory = dmbFactory ?? throw new ArgumentNullException(nameof(dmbFactory));
            this.processExecutor = processExecutor ?? throw new ArgumentNullException(nameof(processExecutor));
            this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
            this.metadata = metadata ?? throw new ArgumentNullException(nameof(metadata));
        }
References Tgstation.Server.Host.Components.Session.SessionPersistor.databaseContextFactory, Tgstation.Server.Host.Components.Session.SessionPersistor.dmbFactory, Tgstation.Server.Host.Components.Session.SessionPersistor.logger, Tgstation.Server.Host.Components.Session.SessionPersistor.metadata, and Tgstation.Server.Host.Components.Session.SessionPersistor.processExecutor.
Member Function Documentation
Clear()
ValueTask Tgstation.Server.Host.Components.Session.SessionPersistor.Clear (CancellationToken cancellationToken)
Clear any stored ReattachInformation.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Session.ISessionPersistor.
References Tgstation.Server.Host.Components.Session.SessionPersistor.ClearImpl(), and Tgstation.Server.Host.Components.Session.SessionPersistor.logger.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.DisposeAndNullControllers().
ClearImpl()
async ValueTask Tgstation.Server.Host.Components.Session.SessionPersistor.ClearImpl (IDatabaseContext databaseContext, bool instant, CancellationToken cancellationToken) private
Clear any stored ReattachInformation.
Parameters
databaseContext The IDatabaseContext to use.
instant If an SQL DELETE WHERE command should be used rather than an Entity Framework transaction.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Definition at line 263 of file SessionPersistor.cs.
        {
            var baseQuery = databaseContext
                .ReattachInformations
                .AsQueryable()
                .Where(x => x.CompileJob!.Job.Instance!.Id == metadata.Id);
            if (instant)
                await baseQuery
                    .ExecuteDeleteAsync(cancellationToken);
            else
            {
                var results = await baseQuery.ToListAsync(cancellationToken);
                foreach (var result in results)
                    databaseContext.ReattachInformations.Remove(result);
            }
        }
References Tgstation.Server.Host.Components.Session.SessionPersistor.metadata, Tgstation.Server.Host.Database.IDatabaseContext.ReattachInformations, and Tgstation.Server.Host.Database.IDatabaseCollection< TModel >.Remove().
Referenced by Tgstation.Server.Host.Components.Session.SessionPersistor.Clear(), and Tgstation.Server.Host.Components.Session.SessionPersistor.Save().
Load()
async ValueTask< ReattachInformation?> Tgstation.Server.Host.Components.Session.SessionPersistor.Load (CancellationToken cancellationToken)
Load a saved ReattachInformation.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the stored ReattachInformation if any.
Implements Tgstation.Server.Host.Components.Session.ISessionPersistor.
Definition at line 126 of file SessionPersistor.cs.
        {
            Models.ReattachInformation? result = null;
            TimeSpan? topicTimeout = null;
            async ValueTask KillProcess(Models.ReattachInformation reattachInfo)
            {
                try
                {
                    await using var process = processExecutor.GetProcess(reattachInfo.ProcessId);
                    if (process != null)
                    {
                        if (reattachInfo == result)
{
                            logger.LogWarning("Killing PID {pid} associated with CompileJob-less reattach information...", reattachInfo.ProcessId);
                        }
                        else
{
                            logger.LogWarning("Killing PID {pid} associated with extra reattach information...", reattachInfo.ProcessId);
                        }
                        process.Terminate();
                        await process.Lifetime;
                    }
                }
                catch (Exception ex)
                {
                    logger.LogWarning(ex, "Failed to kill process!");
                }
            }
            await databaseContextFactory.UseContext(async (db) =>
            {
                var dbReattachInfos = await db
                    .ReattachInformations
                    .AsQueryable()
                    .Where(x => x.CompileJob!.Job.Instance!.Id == metadata.Id)
                    .Include(x => x.CompileJob)
                    .Include(x => x.InitialCompileJob)
                    .ToListAsync(cancellationToken);
                result = dbReattachInfos.FirstOrDefault();
                if (result == null)
                    return;
                var timeoutMilliseconds = await db
                    .Instances
                    .AsQueryable()
                    .Where(x => x.Id == metadata.Id)
                    .Select(x => x.DreamDaemonSettings!.TopicRequestTimeout)
                    .FirstOrDefaultAsync(cancellationToken);
                if (timeoutMilliseconds == default)
                {
                    logger.LogCritical("Missing TopicRequestTimeout!");
                    return;
                }
                topicTimeout = TimeSpan.FromMilliseconds(timeoutMilliseconds.Value);
                bool first = true;
                foreach (var reattachInfo in dbReattachInfos)
                {
                    if (first)
                    {
                        first = false;
                        continue;
                    }
                    await KillProcess(reattachInfo);
                    db.ReattachInformations.Remove(reattachInfo);
                    logger.LogTrace("Deleting ReattachInformation {id}...", reattachInfo.Id);
                }
                await db.Save(cancellationToken);
            });
            if (!topicTimeout.HasValue)
            {
                logger.LogDebug("Reattach information not found!");
                return null;
            }
            var dmb = await dmbFactory.FromCompileJob(result!.CompileJob!, "Session Loading Main Deployment", cancellationToken);
            if (dmb == null)
            {
                logger.LogError("Unable to reattach! Could not load .dmb!");
                await KillProcess(result);
                await databaseContextFactory.UseContext(async db =>
                {
                    logger.LogTrace("Deleting ReattachInformation {id}...", result.Id);
                    await db
                        .ReattachInformations
                        .AsQueryable()
                        .Where(x => x.Id == result.Id)
                        .ExecuteDeleteAsync(cancellationToken);
                });
                return null;
            }
            IDmbProvider? initialDmb = null;
            if (result.InitialCompileJob != null)
            {
                logger.LogTrace("Loading initial compile job...");
                initialDmb = await dmbFactory.FromCompileJob(result.InitialCompileJob, "Session Loading Initial Deployment", cancellationToken);
            }
            logger.LogTrace("Retrieved ReattachInformation");
            var info = new ReattachInformation(
                result,
                dmb,
                initialDmb,
                topicTimeout.Value);
            logger.LogDebug("Reattach information loaded: {info}", info);
            return info;
        }
References Tgstation.Server.Host.Components.Session.SessionPersistor.databaseContextFactory, Tgstation.Server.Host.Components.Session.SessionPersistor.dmbFactory, Tgstation.Server.Host.Components.Deployment.IDmbFactory.FromCompileJob(), Tgstation.Server.Host.System.IProcessExecutor.GetProcess(), Tgstation.Server.Host.Components.Session.SessionPersistor.logger, Tgstation.Server.Host.Components.Session.SessionPersistor.metadata, Tgstation.Server.Host.Components.Session.SessionPersistor.processExecutor, Tgstation.Server.Host.System.IProcess.Terminate(), and Tgstation.Server.Host.Database.IDatabaseContextFactory.UseContext().
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.StartAsync().
Save()
ValueTask Tgstation.Server.Host.Components.Session.SessionPersistor.Save (ReattachInformation reattachInformation, CancellationToken cancellationToken)
Save some reattachInformation .
Parameters
reattachInformation The ReattachInformation to save. Models.ReattachInformationBase.Id will be written back into it.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Session.ISessionPersistor.
References Tgstation.Server.Host.Components.Session.SessionPersistor.ClearImpl(), and Tgstation.Server.Host.Components.Session.SessionPersistor.logger.
Update()
ValueTask Tgstation.Server.Host.Components.Session.SessionPersistor.Update (ReattachInformation reattachInformation, CancellationToken cancellationToken)
Update some reattachInformation .
Parameters
reattachInformation The ReattachInformation to update. Requires Save(ReattachInformation, CancellationToken) to have been called on it previously or it was retrieved from Load(CancellationToken).
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Session.ISessionPersistor.
References Tgstation.Server.Host.Components.Session.SessionPersistor.logger.
Referenced by Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.HandleNormalReboot(), and Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.InitController().
Member Data Documentation
databaseContextFactory
readonly IDatabaseContextFactory Tgstation.Server.Host.Components.Session.SessionPersistor.databaseContextFactory private
The IDatabaseContextFactory for the SessionPersistor.
Definition at line 22 of file SessionPersistor.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionPersistor.Load(), and Tgstation.Server.Host.Components.Session.SessionPersistor.SessionPersistor().
dmbFactory
readonly IDmbFactory Tgstation.Server.Host.Components.Session.SessionPersistor.dmbFactory private
The IDmbFactory for the SessionPersistor.
Definition at line 27 of file SessionPersistor.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionPersistor.Load(), and Tgstation.Server.Host.Components.Session.SessionPersistor.SessionPersistor().
logger
readonly ILogger<SessionPersistor> Tgstation.Server.Host.Components.Session.SessionPersistor.logger private
The ILogger for the SessionPersistor.
Definition at line 37 of file SessionPersistor.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionPersistor.Clear(), Tgstation.Server.Host.Components.Session.SessionPersistor.Load(), Tgstation.Server.Host.Components.Session.SessionPersistor.Save(), Tgstation.Server.Host.Components.Session.SessionPersistor.SessionPersistor(), and Tgstation.Server.Host.Components.Session.SessionPersistor.Update().
metadata
readonly Api.Models.Instance Tgstation.Server.Host.Components.Session.SessionPersistor.metadata private
The Api.Models.Instance for the SessionPersistor.
Definition at line 42 of file SessionPersistor.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionPersistor.ClearImpl(), Tgstation.Server.Host.Components.Session.SessionPersistor.Load(), and Tgstation.Server.Host.Components.Session.SessionPersistor.SessionPersistor().
processExecutor
readonly IProcessExecutor Tgstation.Server.Host.Components.Session.SessionPersistor.processExecutor private
The IProcessExecutor for the SessionPersistor.
Definition at line 32 of file SessionPersistor.cs.
Referenced by Tgstation.Server.Host.Components.Session.SessionPersistor.Load(), and Tgstation.Server.Host.Components.Session.SessionPersistor.SessionPersistor().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Session/SessionPersistor.cs