tgstation-server: Tgstation.Server.Host.Components.StaticFiles.Configuration Class Reference
Tgstation.Server.Host.Components.StaticFiles.Configuration Class Reference sealed
Public Member Functions
Configuration (IIOManager ioManager, ISynchronousIOManager synchronousIOManager, IFilesystemLinkFactory linkFactory, IProcessExecutor processExecutor, IPostWriteHandler postWriteHandler, IPlatformIdentifier platformIdentifier, IFileTransferTicketProvider fileTransferService, IOptionsMonitor< GeneralConfiguration > generalConfigurationOptions, IOptionsMonitor< SessionConfiguration > sessionConfigurationOptions, ILogger< Configuration > logger, Models.Instance metadata)
Initializes a new instance of the Configuration class.
void Dispose ()
async ValueTask< ServerSideModifications?> CopyDMFilesTo (string dmeFile, string destination, CancellationToken cancellationToken)
Copies all files in the CodeModifications directory to destination .
Parameters
dmeFile The .dme file being compiled.
destination Path to the destination folder.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the ServerSideModifications if any.
async ValueTask< IOrderedQueryable< ConfigurationFileResponse >?> ListDirectory (string? configurationRelativePath, ISystemIdentity? systemIdentity, CancellationToken cancellationToken)
Get ConfigurationFileResponses for all items in a given configurationRelativePath .
Parameters
configurationRelativePath The relative path in the Configuration directory.
systemIdentity The ISystemIdentity for the operation. If null, the operation will be performed as the user of the Core.Application.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in an IOrderedQueryable<T> of the ConfigurationFileResponses for the items in the directory. FileTicketResponse.FileTicket and IConfigurationFile.LastReadHash will both be null. null will be returned if the operation failed due to access contention.
async ValueTask< ConfigurationFileResponse?> Read (string configurationRelativePath, ISystemIdentity? systemIdentity, CancellationToken cancellationToken)
Reads a given configurationRelativePath .
Parameters
configurationRelativePath The relative path in the Configuration directory.
systemIdentity The ISystemIdentity for the operation. If null, the operation will be performed as the user of the Core.Application.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the ConfigurationFileResponse of the file. null will be returned if the operation failed due to access contention.
async ValueTask SymlinkStaticFilesTo (string destination, CancellationToken cancellationToken)
Symlinks all directories in the GameData directory to destination .
Parameters
destination Path to the destination folder.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
async ValueTask< ConfigurationFileResponse?> Write (string configurationRelativePath, ISystemIdentity? systemIdentity, string? previousHash, CancellationToken cancellationToken)
Writes to a given configurationRelativePath .
Parameters
configurationRelativePath The relative path in the Configuration directory.
systemIdentity The ISystemIdentity for the operation. If null, the operation will be performed as the user of the Core.Application.
previousHash The hash any existing file must match in order for the write to succeed.
cancellationToken The CancellationToken for the operation. Usage may result in partial writes.
Returns
A ValueTask<TResult> resulting in the updated ConfigurationFileResponse and associated writing FileTicketResponse. null will be returned if the operation failed due to access contention.
async ValueTask< bool?> CreateDirectory (string configurationRelativePath, ISystemIdentity? systemIdentity, CancellationToken cancellationToken)
Create an empty directory at configurationRelativePath .
Parameters
configurationRelativePath The relative path in the Configuration directory.
systemIdentity The ISystemIdentity for the operation. If null, the operation will be performed as the user of the Core.Application.
cancellationToken The CancellationToken for the operation. Usage may result in partial writes.
Returns
A ValueTask<TResult> resulting in true if the directory already existed, false otherwise. null will be returned if the operation failed due to access contention.
Task StartAsync (CancellationToken cancellationToken)
async Task StopAsync (CancellationToken cancellationToken)
ValueTask HandleEvent (EventType eventType, IEnumerable< string?> parameters, bool sensitiveParameters, bool deploymentPipeline, CancellationToken cancellationToken)
Handle a given eventType .
Parameters
eventType The EventType.
parameters An IEnumerable<T> of string parameters for eventType .
sensitiveParameters If parameters are considered sensitive and should not be logged.
deploymentPipeline If this event is part of the deployment pipeline.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
ValueTask? HandleCustomEvent (string scriptName, IEnumerable< string?> parameters, CancellationToken cancellationToken)
Handles a given custom event.
Parameters
eventName The name of the event.
parameters An IEnumerable<T> of string parameters for the event.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation if the event was triggered successfully, null if it matched a TGS event and wasn't executed.
async ValueTask< bool?> DeleteDirectory (string configurationRelativePath, ISystemIdentity? systemIdentity, CancellationToken cancellationToken)
Attempt to delete an empty directory at configurationRelativePath .
Parameters
configurationRelativePath The path of the empty directory to delete.
systemIdentity The ISystemIdentity for the operation. If null, the operation will be performed as the user of the Core.Application.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in true if the directory was empty and deleted, false otherwise. null will be returned if the operation failed due to access contention.
Properties
static IReadOnlyDictionary< EventType, string[]> EventTypeScriptFileNameMap [get]
Map of EventTypes to the filename of the event scripts they trigger.
Private Member Functions
string StaticIgnorePath ()
Get the proper path to StaticIgnoreFile.
Task EnsureDirectories (CancellationToken cancellationToken)
Ensures standard configuration directories exist.
string ValidateConfigRelativePath (string? configurationRelativePath)
Resolve a given configurationRelativePath to it's full path or throw an InvalidOperationException if it violates rules.
async ValueTask ExecuteEventScripts (IEnumerable< string?> parameters, bool sensitiveParameters, bool deploymentPipeline, CancellationToken cancellationToken, params string[] scriptNames)
Execute a set of given scriptNames .
Private Attributes
readonly IIOManager ioManager
The IIOManager for Configuration.
readonly ISynchronousIOManager synchronousIOManager
The ISynchronousIOManager for Configuration.
readonly IFilesystemLinkFactory linkFactory
The IFilesystemLinkFactory for Configuration.
readonly IProcessExecutor processExecutor
The IProcessExecutor for Configuration.
readonly IPostWriteHandler postWriteHandler
The IPostWriteHandler for Configuration.
readonly IPlatformIdentifier platformIdentifier
The IPlatformIdentifier for Configuration.
readonly IFileTransferTicketProvider fileTransferService
The IFileTransferTicketProvider for Configuration.
readonly IOptionsMonitor< GeneralConfiguration > generalConfigurationOptions
The IOptionsMonitor<TOptions> of GeneralConfiguration for Configuration.
readonly IOptionsMonitor< SessionConfiguration > sessionConfigurationOptions
The IOptionsMonitor<TOptions> of SessionConfiguration for Configuration.
readonly ILogger< Configuration > logger
The ILogger for Configuration.
readonly Models.Instance metadata
The Api.Models.Instance the Configuration belongs to.
readonly SemaphoreSlim semaphore
The SemaphoreSlim for Configuration. Also used as a lock object.
readonly CancellationTokenSource stoppingCts
The CancellationTokenSource that is triggered when StopAsync(CancellationToken) is called.
Task uploadTasks
The culmination of all upload file transfer callbacks.
Static Private Attributes
const string CodeModificationsSubdirectory = "CodeModifications"
The CodeModifications directory name.
const string EventScriptsSubdirectory = "EventScripts"
The EventScripts directory name.
const string GameStaticFilesSubdirectory = "GameStaticFiles"
The GameStaticFiles directory name.
const string StaticIgnoreFile = ".tgsignore"
Name of the ignore file in GameStaticFilesSubdirectory.
const string CodeModificationsHeadFile = "HeadInclude.dm"
The HeadInclude.dm filename.
const string CodeModificationsTailFile = "TailInclude.dm"
The TailInclude.dm filename.
static readonly string DefaultHeadInclude = @$"//TGSUTOGENERTEHeadInclude.dm{Environment.NewLine}//ThisfilewillbeincludedBEFOREallcodeinyour.dmeIFareplacement.dmedoesnotexistinthisdirectory{Environment.NewLine}//PleasenotethatchangesneedtobemadeavailableifyouarehostinganGPLlicensedcodebase{Environment.NewLine}//Thepresencefileinitsdefaultstatedoesnotconstituteacodechangethatneedstobepublishedbylicensingstandards{Environment.NewLine}"
Default contents of CodeModificationsHeadFile.
static readonly string DefaultTailInclude = @$"//TGSUTOGENERTETailInclude.dm{Environment.NewLine}//ThisfilewillbeincludedFTERallcodeinyour.dmeIFareplacement.dmedoesnotexistinthisdirectory{Environment.NewLine}//PleasenotethatchangesneedtobemadeavailableifyouarehostinganGPLlicensedcodebase{Environment.NewLine}//Thepresencefileinitsdefaultstatedoesnotconstituteacodechangethatneedstobepublishedbylicensingstandards{Environment.NewLine}"
Default contents of CodeModificationsHeadFile.
Detailed Description
Definition at line 30 of file Configuration.cs.
Constructor & Destructor Documentation
Configuration()
Tgstation.Server.Host.Components.StaticFiles.Configuration.Configuration (IIOManager ioManager, ISynchronousIOManager synchronousIOManager, IFilesystemLinkFactory linkFactory, IProcessExecutor processExecutor, IPostWriteHandler postWriteHandler, IPlatformIdentifier platformIdentifier, IFileTransferTicketProvider fileTransferService, IOptionsMonitor< GeneralConfiguration > generalConfigurationOptions, IOptionsMonitor< SessionConfiguration > sessionConfigurationOptions, ILogger< Configuration > logger, Models::Instance metadata)
Initializes a new instance of the Configuration class.
Parameters
ioManager The value of ioManager.
synchronousIOManager The value of synchronousIOManager.
linkFactory The value of linkFactory.
processExecutor The value of processExecutor.
postWriteHandler The value of postWriteHandler.
platformIdentifier The value of platformIdentifier.
fileTransferService The value of fileTransferService.
metadata The value of metadata.
logger The value of logger.
generalConfigurationOptions The value of generalConfigurationOptions.
sessionConfigurationOptions The value of sessionConfigurationOptions.
Definition at line 172 of file Configuration.cs.
        {
            this.ioManager = ioManager ?? throw new ArgumentNullException(nameof(ioManager));
            this.synchronousIOManager = synchronousIOManager ?? throw new ArgumentNullException(nameof(synchronousIOManager));
            this.linkFactory = linkFactory ?? throw new ArgumentNullException(nameof(linkFactory));
            this.processExecutor = processExecutor ?? throw new ArgumentNullException(nameof(processExecutor));
            this.postWriteHandler = postWriteHandler ?? throw new ArgumentNullException(nameof(postWriteHandler));
            this.platformIdentifier = platformIdentifier ?? throw new ArgumentNullException(nameof(platformIdentifier));
            this.fileTransferService = fileTransferService ?? throw new ArgumentNullException(nameof(fileTransferService));
            this.generalConfigurationOptions = generalConfigurationOptions ?? throw new ArgumentNullException(nameof(generalConfigurationOptions));
            this.sessionConfigurationOptions = sessionConfigurationOptions ?? throw new ArgumentNullException(nameof(sessionConfigurationOptions));
            this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
            this.metadata = metadata ?? throw new ArgumentNullException(nameof(metadata));
            semaphore = new SemaphoreSlim(1, 1);
            stoppingCts = new CancellationTokenSource();
            uploadTasks = Task.CompletedTask;
        }
References Tgstation.Server.Host.Components.StaticFiles.Configuration.fileTransferService, Tgstation.Server.Host.Components.StaticFiles.Configuration.generalConfigurationOptions, Tgstation.Server.Host.Components.StaticFiles.Configuration.ioManager, Tgstation.Server.Host.Components.StaticFiles.Configuration.linkFactory, Tgstation.Server.Host.Components.StaticFiles.Configuration.logger, Tgstation.Server.Host.Components.StaticFiles.Configuration.metadata, Tgstation.Server.Host.Components.StaticFiles.Configuration.platformIdentifier, Tgstation.Server.Host.Components.StaticFiles.Configuration.postWriteHandler, Tgstation.Server.Host.Components.StaticFiles.Configuration.processExecutor, Tgstation.Server.Host.Components.StaticFiles.Configuration.semaphore, Tgstation.Server.Host.Components.StaticFiles.Configuration.sessionConfigurationOptions, Tgstation.Server.Host.Components.StaticFiles.Configuration.stoppingCts, Tgstation.Server.Host.Components.StaticFiles.Configuration.synchronousIOManager, and Tgstation.Server.Host.Components.StaticFiles.Configuration.uploadTasks.
Member Function Documentation
CopyDMFilesTo()
async ValueTask< ServerSideModifications?> Tgstation.Server.Host.Components.StaticFiles.Configuration.CopyDMFilesTo (string dmeFile, string destination, CancellationToken cancellationToken)
Copies all files in the CodeModifications directory to destination .
Parameters
dmeFile The .dme file being compiled.
destination Path to the destination folder.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the ServerSideModifications if any.
Implements Tgstation.Server.Host.Components.StaticFiles.IConfiguration.
Definition at line 210 of file Configuration.cs.
        {
            using (await SemaphoreSlimContext.Lock(semaphore, cancellationToken, logger))
            {
                var ensureDirectoriesTask = EnsureDirectories(cancellationToken);
                // just assume no other fs race conditions here
                var dmeExistsTask = ioManager.FileExists(ioManager.ConcatPath(CodeModificationsSubdirectory, dmeFile), cancellationToken);
                var headFileExistsTask = ioManager.FileExists(ioManager.ConcatPath(CodeModificationsSubdirectory, CodeModificationsHeadFile), cancellationToken);
                var tailFileExistsTask = ioManager.FileExists(ioManager.ConcatPath(CodeModificationsSubdirectory, CodeModificationsTailFile), cancellationToken);
                await ensureDirectoriesTask;
                var copyTask = ioManager.CopyDirectory(
                    null,
                    null,
                    CodeModificationsSubdirectory,
                    destination,
                    generalConfigurationOptions.CurrentValue.GetCopyDirectoryTaskThrottle(),
                    cancellationToken);
                await Task.WhenAll(dmeExistsTask, headFileExistsTask, tailFileExistsTask, copyTask.AsTask());
                if (!dmeExistsTask.Result && !headFileExistsTask.Result && !tailFileExistsTask.Result)
                    return null;
                if (dmeExistsTask.Result)
                    return new ServerSideModifications(null, null, true);
                if (!headFileExistsTask.Result && !tailFileExistsTask.Result)
                    return null;
                static string IncludeLine(string filePath) => String.Format(CultureInfo.InvariantCulture, "#include \"{0}\"", filePath);
                return new ServerSideModifications(
                    headFileExistsTask.Result
                        ? IncludeLine(CodeModificationsHeadFile)
                        : null,
                    tailFileExistsTask.Result
                        ? IncludeLine(CodeModificationsTailFile)
                        : null,
                    false);
            }
        }
References Tgstation.Server.Host.Components.StaticFiles.Configuration.CodeModificationsHeadFile, Tgstation.Server.Host.Components.StaticFiles.Configuration.CodeModificationsSubdirectory, Tgstation.Server.Host.Components.StaticFiles.Configuration.CodeModificationsTailFile, Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.IO.IIOManager.CopyDirectory(), Tgstation.Server.Host.Components.StaticFiles.Configuration.EnsureDirectories(), Tgstation.Server.Host.IO.IIOManager.FileExists(), Tgstation.Server.Host.Components.StaticFiles.Configuration.generalConfigurationOptions, Tgstation.Server.Host.Components.StaticFiles.Configuration.ioManager, Tgstation.Server.Host.Utils.SemaphoreSlimContext.Lock(), Tgstation.Server.Host.Components.StaticFiles.Configuration.logger, and Tgstation.Server.Host.Components.StaticFiles.Configuration.semaphore.
CreateDirectory()
async ValueTask< bool?> Tgstation.Server.Host.Components.StaticFiles.Configuration.CreateDirectory (string configurationRelativePath, ISystemIdentity? systemIdentity, CancellationToken cancellationToken)
Create an empty directory at configurationRelativePath .
Parameters
configurationRelativePath The relative path in the Configuration directory.
systemIdentity The ISystemIdentity for the operation. If null, the operation will be performed as the user of the Core.Application.
cancellationToken The CancellationToken for the operation. Usage may result in partial writes.
Returns
A ValueTask<TResult> resulting in true if the directory already existed, false otherwise. null will be returned if the operation failed due to access contention.
Implements Tgstation.Server.Host.Components.StaticFiles.IConfiguration.
Definition at line 607 of file Configuration.cs.
        {
            await EnsureDirectories(cancellationToken);
            var path = ValidateConfigRelativePath(configurationRelativePath);
            bool? result = null;
            void DoCreate() => result = synchronousIOManager.CreateDirectory(path, cancellationToken);
            using (SemaphoreSlimContext.TryLock(semaphore, logger, out var locked))
            {
                if (!locked)
                {
                    logger.LogDebug("Contention when attempting to create directory!");
                    return null;
                }
                if (systemIdentity == null)
                    await Task.Factory.StartNew(DoCreate, cancellationToken, DefaultIOManager.BlockingTaskCreationOptions, TaskScheduler.Current);
                else
                    await systemIdentity.RunImpersonated(DoCreate, cancellationToken);
            }
            return result!.Value;
        }
References Tgstation.Server.Host.IO.DefaultIOManager.BlockingTaskCreationOptions, Tgstation.Server.Host.Security.ISystemIdentity.RunImpersonated(), and Tgstation.Server.Host.Utils.SemaphoreSlimContext.TryLock().
DeleteDirectory()
async ValueTask< bool?> Tgstation.Server.Host.Components.StaticFiles.Configuration.DeleteDirectory (string configurationRelativePath, ISystemIdentity? systemIdentity, CancellationToken cancellationToken)
Attempt to delete an empty directory at configurationRelativePath .
Parameters
configurationRelativePath The path of the empty directory to delete.
systemIdentity The ISystemIdentity for the operation. If null, the operation will be performed as the user of the Core.Application.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in true if the directory was empty and deleted, false otherwise. null will be returned if the operation failed due to access contention.
Implements Tgstation.Server.Host.Components.StaticFiles.IConfiguration.
Definition at line 692 of file Configuration.cs.
        {
            await EnsureDirectories(cancellationToken);
            var path = ValidateConfigRelativePath(configurationRelativePath);
            var result = false;
            using (SemaphoreSlimContext.TryLock(semaphore, logger, out var locked))
            {
                if (!locked)
                {
                    logger.LogDebug("Contention when attempting to enumerate directory!");
                    return null;
                }
                void CheckDeleteImpl() => result = synchronousIOManager.DeleteDirectory(path);
                if (systemIdentity != null)
                    await systemIdentity.RunImpersonated(CheckDeleteImpl, cancellationToken);
                else
                    CheckDeleteImpl();
            }
            return result;
        }
References Tgstation.Server.Host.Security.ISystemIdentity.RunImpersonated(), and Tgstation.Server.Host.Utils.SemaphoreSlimContext.TryLock().
Dispose()
void Tgstation.Server.Host.Components.StaticFiles.Configuration.Dispose ()
Definition at line 203 of file Configuration.cs.
        {
            semaphore.Dispose();
            stoppingCts.Dispose();
        }
References Tgstation.Server.Host.Components.StaticFiles.Configuration.semaphore, and Tgstation.Server.Host.Components.StaticFiles.Configuration.stoppingCts.
EnsureDirectories()
Task Tgstation.Server.Host.Components.StaticFiles.Configuration.EnsureDirectories (CancellationToken cancellationToken) private
Ensures standard configuration directories exist.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Definition at line 728 of file Configuration.cs.
        {
            async Task ValidateStaticFolder()
            {
                await ioManager.CreateDirectory(GameStaticFilesSubdirectory, cancellationToken);
                var staticIgnorePath = StaticIgnorePath();
                if (!await ioManager.FileExists(staticIgnorePath, cancellationToken))
                    await ioManager.WriteAllBytes(staticIgnorePath, Array.Empty<byte>(), cancellationToken);
            }
            async Task ValidateCodeModsFolder()
            {
                if (await ioManager.DirectoryExists(CodeModificationsSubdirectory, cancellationToken))
                    return;
                await ioManager.CreateDirectory(CodeModificationsSubdirectory, cancellationToken);
                var headWriteTask = ioManager.WriteAllBytes(
                    ioManager.ConcatPath(
                        CodeModificationsSubdirectory,
                        CodeModificationsHeadFile),
                    Encoding.UTF8.GetBytes(DefaultHeadInclude),
                    cancellationToken);
                var tailWriteTask = ioManager.WriteAllBytes(
                    ioManager.ConcatPath(
                        CodeModificationsSubdirectory,
                        CodeModificationsTailFile),
                    Encoding.UTF8.GetBytes(DefaultTailInclude),
                    cancellationToken);
                await ValueTaskExtensions.WhenAll(headWriteTask, tailWriteTask);
            }
            return Task.WhenAll(
                ValidateCodeModsFolder(),
                ioManager.CreateDirectory(EventScriptsSubdirectory, cancellationToken),
                ValidateStaticFolder());
        }
References Tgstation.Server.Common.Extensions.ValueTaskExtensions.WhenAll().
Referenced by Tgstation.Server.Host.Components.StaticFiles.Configuration.CopyDMFilesTo(), Tgstation.Server.Host.Components.StaticFiles.Configuration.ListDirectory(), and Tgstation.Server.Host.Components.StaticFiles.Configuration.Read().
ExecuteEventScripts()
async ValueTask Tgstation.Server.Host.Components.StaticFiles.Configuration.ExecuteEventScripts (IEnumerable< string?> parameters, bool sensitiveParameters, bool deploymentPipeline, CancellationToken cancellationToken, params string[] scriptNames) private
Execute a set of given scriptNames .
Parameters
parameters An IEnumerable<T> of string parameters for the scriptNames .
sensitiveParameters If parameters are considered sensitive and should not be logged.
deploymentPipeline If this event is part of the deployment pipeline.
cancellationToken The CancellationToken for the operation.
scriptNames The names of the scripts to execute.
Returns
A ValueTask representing the running operation.
Definition at line 793 of file Configuration.cs.
        {
            await EnsureDirectories(cancellationToken);
            // always execute in serial
            using (await SemaphoreSlimContext.Lock(semaphore, cancellationToken, logger))
            {
                var sessionConfiguration = sessionConfigurationOptions.CurrentValue;
                var directories = generalConfigurationOptions.CurrentValue.AdditionalEventScriptsDirectories?.ToList() ?? new List<string>();
                directories.Add(EventScriptsSubdirectory);
                var allScripts = new List<string>();
                var tasks = directories.Select<string, ValueTask>(
                    async scriptDirectory =>
                    {
                        var resolvedScriptsDir = ioManager.ResolvePath(scriptDirectory);
                        logger.LogTrace("Checking for scripts in {directory}...", scriptDirectory);
                        var files = await ioManager.GetFilesWithExtension(scriptDirectory, platformIdentifier.ScriptFileExtension, false, cancellationToken);
                        var scriptFiles = files
                            .Select(ioManager.GetFileName)
                            .Where(x => scriptNames.Any(
                                scriptName => x.StartsWith(scriptName, StringComparison.Ordinal)))
                            .Select(x =>
{
                                var fullScriptPath = ioManager.ConcatPath(resolvedScriptsDir, x);
                                logger.LogTrace("Found matching script: {scriptPath}", fullScriptPath);
                                return fullScriptPath;
                            });
                        lock (allScripts)
                            allScripts.AddRange(scriptFiles);
                    })
                    .ToList();
                await ValueTaskExtensions.WhenAll(tasks);
                if (allScripts.Count == 0)
                {
                    logger.LogTrace("No event scripts starting with \"{scriptName}\" detected", String.Join("\" or \"", scriptNames));
                    return;
                }
                var resolvedInstanceScriptsDir = ioManager.ResolvePath(EventScriptsSubdirectory);
                foreach (var scriptFile in allScripts.OrderBy(ioManager.GetFileName))
                {
                    logger.LogTrace("Running event script {scriptFile}...", scriptFile);
                    await using (var script = await processExecutor.LaunchProcess(
                        scriptFile,
                        resolvedInstanceScriptsDir,
                        String.Join(
                            ' ',
                            parameters.Select(arg =>
{
                                if (arg == null)
                                    return "(NULL)";
                                if (!arg.Contains(' ', StringComparison.Ordinal))
                                    return arg;
                                arg = arg.Replace("\"", "\\\"", StringComparison.Ordinal);
                                return $"\"{arg}\"";
                            })),
                        cancellationToken,
                        new Dictionary<string, string>
{
                            { "TGS_INSTANCE_ROOT", metadata.Path! },
                        },
                        readStandardHandles: true,
                        noShellExecute: true,
                        doNotLogArguments: sensitiveParameters))
                    using (cancellationToken.Register(() => script.Terminate()))
                    {
                        if (sessionConfiguration.LowPriorityDeploymentProcesses && deploymentPipeline)
                            script.AdjustPriority(false);
                        var exitCode = await script.Lifetime;
                        cancellationToken.ThrowIfCancellationRequested();
                        var scriptOutput = await script.GetCombinedOutput(cancellationToken);
                        if (exitCode != 0)
                            throw new JobException($"Script {scriptFile} exited with code {exitCode}:{Environment.NewLine}{scriptOutput}");
                        else
                            logger.LogDebug("Script output:{newLine}{scriptOutput}", Environment.NewLine, scriptOutput);
                    }
                }
            }
        }
References Tgstation.Server.Host.Utils.SemaphoreSlimContext.Lock(), and Tgstation.Server.Common.Extensions.ValueTaskExtensions.WhenAll().
HandleCustomEvent()
ValueTask? Tgstation.Server.Host.Components.StaticFiles.Configuration.HandleCustomEvent (string scriptName, IEnumerable< string?> parameters, CancellationToken cancellationToken)
Handles a given custom event.
Parameters
eventName The name of the event.
parameters An IEnumerable<T> of string parameters for the event.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation if the event was triggered successfully, null if it matched a TGS event and wasn't executed.
Implements Tgstation.Server.Host.Components.Events.IEventConsumer.
Definition at line 670 of file Configuration.cs.
        {
            var scriptNameIsTgsEventName = EventTypeScriptFileNameMap
                .Values
                .SelectMany(scriptNames => scriptNames)
                .Any(tgsScriptName => tgsScriptName.Equals(
                    scriptName,
                    platformIdentifier.IsWindows
                        ? StringComparison.OrdinalIgnoreCase
                        : StringComparison.Ordinal));
            if (scriptNameIsTgsEventName)
            {
                logger.LogWarning("DMAPI attempted to execute TGS reserved event: {eventName}", scriptName);
                return null;
            }
#pragma warning disable CA2012 // Use ValueTasks correctly
            return ExecuteEventScripts(parameters, false, false, cancellationToken, scriptName);
#pragma warning restore CA2012 // Use ValueTasks correctly
        }
HandleEvent()
ValueTask Tgstation.Server.Host.Components.StaticFiles.Configuration.HandleEvent (EventType eventType, IEnumerable< string?> parameters, bool sensitiveParameters, bool deploymentPipeline, CancellationToken cancellationToken)
Handle a given eventType .
Parameters
eventType The EventType.
parameters An IEnumerable<T> of string parameters for eventType .
sensitiveParameters If parameters are considered sensitive and should not be logged.
deploymentPipeline If this event is part of the deployment pipeline.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.Events.IEventConsumer.
Definition at line 656 of file Configuration.cs.
        {
            ArgumentNullException.ThrowIfNull(parameters);
            if (!EventTypeScriptFileNameMap.TryGetValue(eventType, out var scriptNames))
            {
                logger.LogTrace("No event script for event {event}!", eventType);
                return ValueTask.CompletedTask;
            }
            return ExecuteEventScripts(parameters, sensitiveParameters, deploymentPipeline, cancellationToken, scriptNames);
        }
ListDirectory()
async ValueTask< IOrderedQueryable< ConfigurationFileResponse >?> Tgstation.Server.Host.Components.StaticFiles.Configuration.ListDirectory (string? configurationRelativePath, ISystemIdentity? systemIdentity, CancellationToken cancellationToken)
Get ConfigurationFileResponses for all items in a given configurationRelativePath .
Parameters
configurationRelativePath The relative path in the Configuration directory.
systemIdentity The ISystemIdentity for the operation. If null, the operation will be performed as the user of the Core.Application.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in an IOrderedQueryable<T> of the ConfigurationFileResponses for the items in the directory. FileTicketResponse.FileTicket and IConfigurationFile.LastReadHash will both be null. null will be returned if the operation failed due to access contention.
Implements Tgstation.Server.Host.Components.StaticFiles.IConfiguration.
Definition at line 255 of file Configuration.cs.
        {
            await EnsureDirectories(cancellationToken);
            var path = ValidateConfigRelativePath(configurationRelativePath);
            configurationRelativePath ??= "/";
            var result = new List<ConfigurationFileResponse>();
            void ListImpl()
            {
                var enumerator = synchronousIOManager.GetDirectories(path, cancellationToken);
                result.AddRange(enumerator.Select(x => new ConfigurationFileResponse
                {
                    IsDirectory = true,
                    Path = ioManager.ConcatPath(configurationRelativePath, x),
                }));
                enumerator = synchronousIOManager.GetFiles(path, cancellationToken);
                result.AddRange(enumerator.Select(x => new ConfigurationFileResponse
                {
                    IsDirectory = false,
                    Path = ioManager.ConcatPath(configurationRelativePath, x),
                }));
            }
            using (SemaphoreSlimContext.TryLock(semaphore, logger, out var locked))
            {
                if (!locked)
                {
                    logger.LogDebug("Contention when attempting to enumerate directory!");
                    return null;
                }
                if (systemIdentity == null)
                    ListImpl();
                else
                    await systemIdentity.RunImpersonated(ListImpl, cancellationToken);
            }
            return result
                .AsQueryable()
                .OrderBy(configFile => !configFile.IsDirectory)
                .ThenBy(configFile => configFile.Path);
        }
References Tgstation.Server.Host.Components.StaticFiles.Configuration.EnsureDirectories(), Tgstation.Server.Host.IO.ISynchronousIOManager.GetDirectories(), Tgstation.Server.Host.IO.ISynchronousIOManager.GetFiles(), Tgstation.Server.Host.Components.StaticFiles.Configuration.logger, Tgstation.Server.Host.Security.ISystemIdentity.RunImpersonated(), Tgstation.Server.Host.Components.StaticFiles.Configuration.semaphore, Tgstation.Server.Host.Components.StaticFiles.Configuration.synchronousIOManager, Tgstation.Server.Host.Utils.SemaphoreSlimContext.TryLock(), and Tgstation.Server.Host.Components.StaticFiles.Configuration.ValidateConfigRelativePath().
Read()
async ValueTask< ConfigurationFileResponse?> Tgstation.Server.Host.Components.StaticFiles.Configuration.Read (string configurationRelativePath, ISystemIdentity? systemIdentity, CancellationToken cancellationToken)
Reads a given configurationRelativePath .
Parameters
configurationRelativePath The relative path in the Configuration directory.
systemIdentity The ISystemIdentity for the operation. If null, the operation will be performed as the user of the Core.Application.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the ConfigurationFileResponse of the file. null will be returned if the operation failed due to access contention.
Implements Tgstation.Server.Host.Components.StaticFiles.IConfiguration.
Definition at line 302 of file Configuration.cs.
        {
            await EnsureDirectories(cancellationToken);
            var path = ValidateConfigRelativePath(configurationRelativePath);
            ConfigurationFileResponse? result = null;
            void ReadImpl()
            {
                try
                {
                    string GetFileSha()
                    {
                        var content = synchronousIOManager.ReadFile(path);
                        return String.Join(String.Empty, SHA1.HashData(content).Select(b => b.ToString("x2", CultureInfo.InvariantCulture)));
                    }
                    var originalSha = GetFileSha();
                    var disposeToken = stoppingCts.Token;
                    var fileTicket = fileTransferService.CreateDownload(
                        new FileDownloadProvider(
                            () =>
{
                                if (disposeToken.IsCancellationRequested)
                                    return ErrorCode.InstanceOffline;
                                var newSha = GetFileSha();
                                if (newSha != originalSha)
                                    return ErrorCode.ConfigurationFileUpdated;
                                return null;
                            },
                            async cancellationToken =>
{
                                Stream? result = null;
                                void GetFileStream()
{
                                    result = synchronousIOManager.GetFileStream(path);
                                }
                                if (systemIdentity == null)
                                    await Task.Factory.StartNew(GetFileStream, cancellationToken, DefaultIOManager.BlockingTaskCreationOptions, TaskScheduler.Current);
                                else
                                    await systemIdentity.RunImpersonated(GetFileStream, cancellationToken);
                                return result!;
                            },
                            path,
                            false));
                    result = new ConfigurationFileResponse
                    {
                        FileTicket = fileTicket.FileTicket,
                        IsDirectory = false,
                        LastReadHash = originalSha,
                        AccessDenied = false,
                        Path = configurationRelativePath,
                    };
                }
                catch (UnauthorizedAccessException)
                {
                    // this happens on windows, dunno about linux
                    bool isDirectory;
                    try
                    {
                        isDirectory = synchronousIOManager.IsDirectory(path);
                    }
                    catch (Exception ex)
                    {
                        logger.LogDebug(ex, "IsDirectory exception!");
                        isDirectory = false;
                    }
                    result = new ConfigurationFileResponse
                    {
                        Path = configurationRelativePath,
                    };
                    if (!isDirectory)
                        result.AccessDenied = true;
                    result.IsDirectory = isDirectory;
                }
            }
            using (SemaphoreSlimContext.TryLock(semaphore, logger, out var locked))
            {
                if (!locked)
                {
                    logger.LogDebug("Contention when attempting to read file!");
                    return null;
                }
                if (systemIdentity == null)
                    await Task.Factory.StartNew(ReadImpl, cancellationToken, DefaultIOManager.BlockingTaskCreationOptions, TaskScheduler.Current);
                else
                    await systemIdentity.RunImpersonated(ReadImpl, cancellationToken);
            }
            return result;
        }
References Tgstation.Server.Host.IO.DefaultIOManager.BlockingTaskCreationOptions, Tgstation.Server.Host.Transfer.IFileTransferTicketProvider.CreateDownload(), Tgstation.Server.Host.Components.StaticFiles.Configuration.EnsureDirectories(), Tgstation.Server.Api.Models.Response.FileTicketResponse.FileTicket, Tgstation.Server.Host.Components.StaticFiles.Configuration.fileTransferService, Tgstation.Server.Host.IO.ISynchronousIOManager.GetFileStream(), Tgstation.Server.Host.IO.ISynchronousIOManager.IsDirectory(), Tgstation.Server.Host.Components.StaticFiles.Configuration.logger, Tgstation.Server.Host.IO.ISynchronousIOManager.ReadFile(), Tgstation.Server.Host.Security.ISystemIdentity.RunImpersonated(), Tgstation.Server.Host.Components.StaticFiles.Configuration.semaphore, Tgstation.Server.Host.Components.StaticFiles.Configuration.stoppingCts, Tgstation.Server.Host.Components.StaticFiles.Configuration.synchronousIOManager, Tgstation.Server.Host.Utils.SemaphoreSlimContext.TryLock(), and Tgstation.Server.Host.Components.StaticFiles.Configuration.ValidateConfigRelativePath().
StartAsync()
Task Tgstation.Server.Host.Components.StaticFiles.Configuration.StartAsync (CancellationToken cancellationToken)
StaticIgnorePath()
string Tgstation.Server.Host.Components.StaticFiles.Configuration.StaticIgnorePath () private
Get the proper path to StaticIgnoreFile.
Returns
The ioManager relative path to StaticIgnoreFile.
StopAsync()
async Task Tgstation.Server.Host.Components.StaticFiles.Configuration.StopAsync (CancellationToken cancellationToken)
Definition at line 636 of file Configuration.cs.
        {
            await EnsureDirectories(cancellationToken);
            stoppingCts.Cancel();
            try
            {
                await uploadTasks;
            }
            catch (OperationCanceledException ex)
            {
                logger.LogDebug(ex, "One or more uploads/downloads were aborted!");
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Error awaiting upload tasks!");
            }
        }
SymlinkStaticFilesTo()
async ValueTask Tgstation.Server.Host.Components.StaticFiles.Configuration.SymlinkStaticFilesTo (string destination, CancellationToken cancellationToken)
Symlinks all directories in the GameData directory to destination .
Parameters
destination Path to the destination folder.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Components.StaticFiles.IConfiguration.
Definition at line 405 of file Configuration.cs.
        {
            List<string> ignoreFiles;
            async ValueTask SymlinkBase(bool files)
            {
                Task<IReadOnlyList<string>> task;
                if (files)
                    task = ioManager.GetFiles(GameStaticFilesSubdirectory, cancellationToken);
                else
                    task = ioManager.GetDirectories(GameStaticFilesSubdirectory, cancellationToken);
                var entries = await task;
                await ValueTaskExtensions.WhenAll(entries.Select<string, ValueTask>(async file =>
                {
                    var fileName = ioManager.GetFileName(file);
                    // need to normalize
                    var fileComparison = platformIdentifier.IsWindows
                        ? StringComparison.OrdinalIgnoreCase
                        : StringComparison.Ordinal;
                    var ignored = ignoreFiles.Any(y => fileName.Equals(y, fileComparison));
                    if (ignored)
                    {
                        logger.LogTrace("Ignoring static file {fileName}...", fileName);
                        return;
                    }
                    var destPath = ioManager.ConcatPath(destination, fileName);
                    logger.LogTrace("Symlinking {filePath} to {destPath}...", file, destPath);
                    var fileExistsTask = ioManager.FileExists(destPath, cancellationToken);
                    if (await ioManager.DirectoryExists(destPath, cancellationToken))
                        await ioManager.DeleteDirectory(destPath, cancellationToken);
                    var fileExists = await fileExistsTask;
                    if (fileExists)
                        await ioManager.DeleteFile(destPath, cancellationToken);
                    await linkFactory.CreateSymbolicLink(ioManager.ResolvePath(file), ioManager.ResolvePath(destPath), cancellationToken);
                }));
            }
            using (await SemaphoreSlimContext.Lock(semaphore, cancellationToken, logger))
            {
                await EnsureDirectories(cancellationToken);
                var ignoreFileBytes = await ioManager.ReadAllBytes(StaticIgnorePath(), cancellationToken);
                var ignoreFileText = Encoding.UTF8.GetString(ignoreFileBytes);
                ignoreFiles = new List<string> { StaticIgnoreFile };
                // we don't want to lose trailing whitespace on linux
                using (var reader = new StringReader(ignoreFileText))
                {
                    cancellationToken.ThrowIfCancellationRequested();
                    var line = await reader.ReadLineAsync(cancellationToken);
                    if (!String.IsNullOrEmpty(line))
                        ignoreFiles.Add(line);
                }
                var filesSymlinkTask = SymlinkBase(true);
                var dirsSymlinkTask = SymlinkBase(false);
                await ValueTaskExtensions.WhenAll(filesSymlinkTask, dirsSymlinkTask);
            }
        }
References Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.IO.IFilesystemLinkFactory.CreateSymbolicLink(), Tgstation.Server.Host.IO.IIOManager.DeleteDirectory(), Tgstation.Server.Host.IO.IIOManager.DeleteFile(), Tgstation.Server.Host.IO.IIOManager.DirectoryExists(), Tgstation.Server.Host.IO.IIOManager.FileExists(), Tgstation.Server.Host.Components.StaticFiles.Configuration.GameStaticFilesSubdirectory, Tgstation.Server.Host.IO.IIOManager.GetDirectories(), Tgstation.Server.Host.IO.IIOManager.GetFiles(), Tgstation.Server.Host.Components.StaticFiles.Configuration.ioManager, Tgstation.Server.Host.Components.StaticFiles.Configuration.linkFactory, Tgstation.Server.Host.Components.StaticFiles.Configuration.logger, Tgstation.Server.Host.IO.IIOManager.ResolvePath(), and Tgstation.Server.Common.Extensions.ValueTaskExtensions.WhenAll().
ValidateConfigRelativePath()
string Tgstation.Server.Host.Components.StaticFiles.Configuration.ValidateConfigRelativePath (string? configurationRelativePath) private
Resolve a given configurationRelativePath to it's full path or throw an InvalidOperationException if it violates rules.
Parameters
configurationRelativePath A relative path in the instance's configuration directory.
Returns
The full on-disk path of configurationRelativePath .
Definition at line 770 of file Configuration.cs.
        {
            var nullOrEmptyCheck = String.IsNullOrEmpty(configurationRelativePath);
            if (nullOrEmptyCheck)
                configurationRelativePath = DefaultIOManager.CurrentDirectory;
            if (configurationRelativePath![0] == ioManager.DirectorySeparatorChar || configurationRelativePath[0] == ioManager.AltDirectorySeparatorChar)
                configurationRelativePath = DefaultIOManager.CurrentDirectory + configurationRelativePath;
            var resolved = ioManager.ResolvePath(configurationRelativePath);
            var local = !nullOrEmptyCheck ? ioManager.ResolvePath() : null;
            if (!nullOrEmptyCheck && resolved.Length < local!.Length) // .. fuccbois
                throw new InvalidOperationException("Attempted to access file outside of configuration manager!");
            return resolved;
        }
References Tgstation.Server.Host.IO.DefaultIOManager.CurrentDirectory.
Referenced by Tgstation.Server.Host.Components.StaticFiles.Configuration.ListDirectory(), and Tgstation.Server.Host.Components.StaticFiles.Configuration.Read().
Write()
async ValueTask< ConfigurationFileResponse?> Tgstation.Server.Host.Components.StaticFiles.Configuration.Write (string configurationRelativePath, ISystemIdentity? systemIdentity, string? previousHash, CancellationToken cancellationToken)
Writes to a given configurationRelativePath .
Parameters
configurationRelativePath The relative path in the Configuration directory.
systemIdentity The ISystemIdentity for the operation. If null, the operation will be performed as the user of the Core.Application.
previousHash The hash any existing file must match in order for the write to succeed.
cancellationToken The CancellationToken for the operation. Usage may result in partial writes.
Returns
A ValueTask<TResult> resulting in the updated ConfigurationFileResponse and associated writing FileTicketResponse. null will be returned if the operation failed due to access contention.
Implements Tgstation.Server.Host.Components.StaticFiles.IConfiguration.
Definition at line 469 of file Configuration.cs.
        {
            await EnsureDirectories(cancellationToken);
            var path = ValidateConfigRelativePath(configurationRelativePath);
            logger.LogTrace("Starting write to {path}", path);
            ConfigurationFileResponse? result = null;
            void WriteImpl()
            {
                try
                {
                    var fileTicket = fileTransferService.CreateUpload(FileUploadStreamKind.ForSynchronousIO);
                    var uploadCancellationToken = stoppingCts.Token;
                    async Task UploadHandler()
                    {
                        await using (fileTicket)
{
                            var fileHash = previousHash;
                            logger.LogTrace("Write to {path} waiting for upload stream", path);
                            var uploadStream = await fileTicket.GetResult(uploadCancellationToken);
                            if (uploadStream == null)
{
                                logger.LogTrace("Write to {path} expired", path);
                                return; // expired
                            }
                            logger.LogTrace("Write to {path} received stream of length {length}...", path, uploadStream.Length);
                            bool success = false;
                            void WriteCallback()
{
                                logger.LogTrace("Running synchronous write...");
                                success = synchronousIOManager.WriteFileChecked(path, uploadStream, ref fileHash, uploadCancellationToken);
                                logger.LogTrace("Finished write {un}successfully!", success ? String.Empty : "un");
                            }
                            if (fileTicket == null)
{
                                logger.LogDebug("File upload ticket for {path} expired!", path);
                                return;
                            }
                            using (SemaphoreSlimContext.TryLock(semaphore, logger, out var locked))
{
                                if (!locked)
{
                                    fileTicket.SetError(ErrorCode.ConfigurationContendedAccess, null);
                                    return;
                                }
                                logger.LogTrace("Kicking off write callback");
                                if (systemIdentity == null)
                                    await Task.Factory.StartNew(WriteCallback, uploadCancellationToken, DefaultIOManager.BlockingTaskCreationOptions, TaskScheduler.Current);
                                else
                                    await systemIdentity.RunImpersonated(WriteCallback, uploadCancellationToken);
                            }
                            if (!success)
                                fileTicket.SetError(ErrorCode.ConfigurationFileUpdated, fileHash);
                            else if (uploadStream.Length > 0)
                                postWriteHandler.HandleWrite(path);
                            else
                                logger.LogTrace("Write complete");
                        }
                    }
                    result = new ConfigurationFileResponse
                    {
                        FileTicket = fileTicket.Ticket.FileTicket,
                        LastReadHash = previousHash,
                        IsDirectory = false,
                        AccessDenied = false,
                        Path = configurationRelativePath,
                    };
                    lock (stoppingCts)
                    {
                        async Task ChainUploadTasks()
{
                            var oldUploadTask = uploadTasks;
                            var newUploadTask = UploadHandler();
                            try
{
                                await oldUploadTask;
                            }
                            finally
{
                                await newUploadTask;
                            }
                        }
                        uploadTasks = ChainUploadTasks();
                    }
                }
                catch (UnauthorizedAccessException)
                {
                    // this happens on windows, dunno about linux
                    bool isDirectory;
                    try
                    {
                        isDirectory = synchronousIOManager.IsDirectory(path);
                    }
                    catch (Exception ex)
                    {
                        logger.LogDebug(ex, "IsDirectory exception!");
                        isDirectory = false;
                    }
                    result = new ConfigurationFileResponse
                    {
                        Path = configurationRelativePath,
                    };
                    if (!isDirectory)
                        result.AccessDenied = true;
                    result.IsDirectory = isDirectory;
                }
            }
            using (SemaphoreSlimContext.TryLock(semaphore, logger, out var locked))
            {
                if (!locked)
                {
                    logger.LogDebug("Contention when attempting to write file!");
                    return null;
                }
                if (systemIdentity == null)
                    await Task.Factory.StartNew(WriteImpl, cancellationToken, DefaultIOManager.BlockingTaskCreationOptions, TaskScheduler.Current);
                else
                    await systemIdentity.RunImpersonated(WriteImpl, cancellationToken);
            }
            return result;
        }
References Tgstation.Server.Host.IO.DefaultIOManager.BlockingTaskCreationOptions, Tgstation.Server.Api.Models.Response.FileTicketResponse.FileTicket, Tgstation.Server.Host.Security.ISystemIdentity.RunImpersonated(), and Tgstation.Server.Host.Utils.SemaphoreSlimContext.TryLock().
Member Data Documentation
CodeModificationsHeadFile
const string Tgstation.Server.Host.Components.StaticFiles.Configuration.CodeModificationsHeadFile = "HeadInclude.dm" static private
The HeadInclude.dm filename.
Definition at line 55 of file Configuration.cs.
Referenced by Tgstation.Server.Host.Components.StaticFiles.Configuration.CopyDMFilesTo().
CodeModificationsSubdirectory
const string Tgstation.Server.Host.Components.StaticFiles.Configuration.CodeModificationsSubdirectory = "CodeModifications" static private
The CodeModifications directory name.
Definition at line 35 of file Configuration.cs.
Referenced by Tgstation.Server.Host.Components.StaticFiles.Configuration.CopyDMFilesTo().
CodeModificationsTailFile
const string Tgstation.Server.Host.Components.StaticFiles.Configuration.CodeModificationsTailFile = "TailInclude.dm" static private
The TailInclude.dm filename.
Definition at line 60 of file Configuration.cs.
Referenced by Tgstation.Server.Host.Components.StaticFiles.Configuration.CopyDMFilesTo().
DefaultHeadInclude
readonly string Tgstation.Server.Host.Components.StaticFiles.Configuration.DefaultHeadInclude = @$"//TGSUTOGENERTEHeadInclude.dm{Environment.NewLine}//ThisfilewillbeincludedBEFOREallcodeinyour.dmeIFareplacement.dmedoesnotexistinthisdirectory{Environment.NewLine}//PleasenotethatchangesneedtobemadeavailableifyouarehostinganGPLlicensedcodebase{Environment.NewLine}//Thepresencefileinitsdefaultstatedoesnotconstituteacodechangethatneedstobepublishedbylicensingstandards{Environment.NewLine}" static private
Default contents of CodeModificationsHeadFile.
Definition at line 65 of file Configuration.cs.
DefaultTailInclude
readonly string Tgstation.Server.Host.Components.StaticFiles.Configuration.DefaultTailInclude = @$"//TGSUTOGENERTETailInclude.dm{Environment.NewLine}//ThisfilewillbeincludedFTERallcodeinyour.dmeIFareplacement.dmedoesnotexistinthisdirectory{Environment.NewLine}//PleasenotethatchangesneedtobemadeavailableifyouarehostinganGPLlicensedcodebase{Environment.NewLine}//Thepresencefileinitsdefaultstatedoesnotconstituteacodechangethatneedstobepublishedbylicensingstandards{Environment.NewLine}" static private
Default contents of CodeModificationsHeadFile.
Definition at line 70 of file Configuration.cs.
EventScriptsSubdirectory
const string Tgstation.Server.Host.Components.StaticFiles.Configuration.EventScriptsSubdirectory = "EventScripts" static private
The EventScripts directory name.
Definition at line 40 of file Configuration.cs.
fileTransferService
readonly IFileTransferTicketProvider Tgstation.Server.Host.Components.StaticFiles.Configuration.fileTransferService private
The IFileTransferTicketProvider for Configuration.
>
Definition at line 121 of file Configuration.cs.
Referenced by Tgstation.Server.Host.Components.StaticFiles.Configuration.Configuration(), and Tgstation.Server.Host.Components.StaticFiles.Configuration.Read().
GameStaticFilesSubdirectory
const string Tgstation.Server.Host.Components.StaticFiles.Configuration.GameStaticFilesSubdirectory = "GameStaticFiles" static private
The GameStaticFiles directory name.
Definition at line 45 of file Configuration.cs.
Referenced by Tgstation.Server.Host.Components.StaticFiles.Configuration.SymlinkStaticFilesTo().
generalConfigurationOptions
readonly IOptionsMonitor<GeneralConfiguration> Tgstation.Server.Host.Components.StaticFiles.Configuration.generalConfigurationOptions private
The IOptionsMonitor<TOptions> of GeneralConfiguration for Configuration.
Definition at line 126 of file Configuration.cs.
Referenced by Tgstation.Server.Host.Components.StaticFiles.Configuration.Configuration(), and Tgstation.Server.Host.Components.StaticFiles.Configuration.CopyDMFilesTo().
ioManager
readonly IIOManager Tgstation.Server.Host.Components.StaticFiles.Configuration.ioManager private
The IIOManager for Configuration.
Definition at line 91 of file Configuration.cs.
Referenced by Tgstation.Server.Host.Components.StaticFiles.Configuration.Configuration(), Tgstation.Server.Host.Components.StaticFiles.Configuration.CopyDMFilesTo(), and Tgstation.Server.Host.Components.StaticFiles.Configuration.SymlinkStaticFilesTo().
linkFactory
readonly IFilesystemLinkFactory Tgstation.Server.Host.Components.StaticFiles.Configuration.linkFactory private
The IFilesystemLinkFactory for Configuration.
Definition at line 101 of file Configuration.cs.
Referenced by Tgstation.Server.Host.Components.StaticFiles.Configuration.Configuration(), and Tgstation.Server.Host.Components.StaticFiles.Configuration.SymlinkStaticFilesTo().
logger
readonly ILogger<Configuration> Tgstation.Server.Host.Components.StaticFiles.Configuration.logger private
The ILogger for Configuration.
Definition at line 136 of file Configuration.cs.
Referenced by Tgstation.Server.Host.Components.StaticFiles.Configuration.Configuration(), Tgstation.Server.Host.Components.StaticFiles.Configuration.CopyDMFilesTo(), Tgstation.Server.Host.Components.StaticFiles.Configuration.ListDirectory(), Tgstation.Server.Host.Components.StaticFiles.Configuration.Read(), and Tgstation.Server.Host.Components.StaticFiles.Configuration.SymlinkStaticFilesTo().
metadata
readonly Models.Instance Tgstation.Server.Host.Components.StaticFiles.Configuration.metadata private
The Api.Models.Instance the Configuration belongs to.
Definition at line 141 of file Configuration.cs.
Referenced by Tgstation.Server.Host.Components.StaticFiles.Configuration.Configuration().
platformIdentifier
readonly IPlatformIdentifier Tgstation.Server.Host.Components.StaticFiles.Configuration.platformIdentifier private
The IPlatformIdentifier for Configuration.
Definition at line 116 of file Configuration.cs.
Referenced by Tgstation.Server.Host.Components.StaticFiles.Configuration.Configuration().
postWriteHandler
readonly IPostWriteHandler Tgstation.Server.Host.Components.StaticFiles.Configuration.postWriteHandler private
The IPostWriteHandler for Configuration.
Definition at line 111 of file Configuration.cs.
Referenced by Tgstation.Server.Host.Components.StaticFiles.Configuration.Configuration().
processExecutor
readonly IProcessExecutor Tgstation.Server.Host.Components.StaticFiles.Configuration.processExecutor private
The IProcessExecutor for Configuration.
Definition at line 106 of file Configuration.cs.
Referenced by Tgstation.Server.Host.Components.StaticFiles.Configuration.Configuration().
semaphore
readonly SemaphoreSlim Tgstation.Server.Host.Components.StaticFiles.Configuration.semaphore private
The SemaphoreSlim for Configuration. Also used as a lock object.
Definition at line 146 of file Configuration.cs.
Referenced by Tgstation.Server.Host.Components.StaticFiles.Configuration.Configuration(), Tgstation.Server.Host.Components.StaticFiles.Configuration.CopyDMFilesTo(), Tgstation.Server.Host.Components.StaticFiles.Configuration.Dispose(), Tgstation.Server.Host.Components.StaticFiles.Configuration.ListDirectory(), and Tgstation.Server.Host.Components.StaticFiles.Configuration.Read().
sessionConfigurationOptions
readonly IOptionsMonitor<SessionConfiguration> Tgstation.Server.Host.Components.StaticFiles.Configuration.sessionConfigurationOptions private
The IOptionsMonitor<TOptions> of SessionConfiguration for Configuration.
Definition at line 131 of file Configuration.cs.
Referenced by Tgstation.Server.Host.Components.StaticFiles.Configuration.Configuration().
StaticIgnoreFile
const string Tgstation.Server.Host.Components.StaticFiles.Configuration.StaticIgnoreFile = ".tgsignore" static private
Name of the ignore file in GameStaticFilesSubdirectory.
Definition at line 50 of file Configuration.cs.
stoppingCts
readonly CancellationTokenSource Tgstation.Server.Host.Components.StaticFiles.Configuration.stoppingCts private
The CancellationTokenSource that is triggered when StopAsync(CancellationToken) is called.
Definition at line 151 of file Configuration.cs.
Referenced by Tgstation.Server.Host.Components.StaticFiles.Configuration.Configuration(), Tgstation.Server.Host.Components.StaticFiles.Configuration.Dispose(), and Tgstation.Server.Host.Components.StaticFiles.Configuration.Read().
synchronousIOManager
readonly ISynchronousIOManager Tgstation.Server.Host.Components.StaticFiles.Configuration.synchronousIOManager private
The ISynchronousIOManager for Configuration.
Definition at line 96 of file Configuration.cs.
Referenced by Tgstation.Server.Host.Components.StaticFiles.Configuration.Configuration(), Tgstation.Server.Host.Components.StaticFiles.Configuration.ListDirectory(), and Tgstation.Server.Host.Components.StaticFiles.Configuration.Read().
uploadTasks
Task Tgstation.Server.Host.Components.StaticFiles.Configuration.uploadTasks private
The culmination of all upload file transfer callbacks.
Definition at line 156 of file Configuration.cs.
Referenced by Tgstation.Server.Host.Components.StaticFiles.Configuration.Configuration().
Property Documentation
EventTypeScriptFileNameMap
IReadOnlyDictionary<EventType, string[]> Tgstation.Server.Host.Components.StaticFiles.Configuration.EventTypeScriptFileNameMap static get
Initial value:
= new Dictionary<EventType, string[]>(
            Enum.GetValues(typeof(EventType))
                .Cast<EventType>()
                .Select(
                    eventType => new KeyValuePair<EventType, string[]>(
                        eventType,
                        typeof(EventType)
                            .GetField(eventType.ToString())!
                            .GetCustomAttributes(false)
                            .OfType<EventScriptAttribute>()
                            .First()
                            .ScriptNames)))
Map of EventTypes to the filename of the event scripts they trigger.
Definition at line 75 of file Configuration.cs.
{ get; } = new Dictionary<EventType, string[]>(
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/StaticFiles/Configuration.cs