tgstation-server: TGS.ControlPanel.Login Class Reference
TGS.ControlPanel.Login Class Reference
Public Member Functions
Login ()
Construct a Login
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void ClearFields (int start=1)
void IPComboBox_SelectedIndexChanged (object sender, EventArgs e)
void RemoteLoginButton_Click (object sender, EventArgs e)
void LocalLoginButton_Click (object sender, EventArgs e)
bool VerifyAndConnect (IClient I)
Attempts a connection on a given IClient
void SavePasswordCheckBox_CheckedChanged (object sender, EventArgs e)
void DeleteLoginButton_Click (object sender, EventArgs e)
Removes the selected item from IPComboBox
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
RemoteLoginInfo currentLoginInfo
Currently selected saved RemoteLoginInfo
bool updatingFields
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.Button LocalLoginButton
System.Windows.Forms.Label CurrentRevisionTitle
System.Windows.Forms.TextBox UsernameTextBox
System.Windows.Forms.TextBox PasswordTextBox
System.Windows.Forms.Button RemoteLoginButton
System.Windows.Forms.Label AddressLabel
System.Windows.Forms.Label label2
System.Windows.Forms.Label label3
System.Windows.Forms.Label label4
System.Windows.Forms.NumericUpDown PortSelector
System.Windows.Forms.CheckBox SavePasswordCheckBox
System.Windows.Forms.ComboBox IPComboBox
System.Windows.Forms.Button DeleteLoginButton
Detailed Description
Definition at line 8 of file Login.cs.
Constructor & Destructor Documentation
TGS.ControlPanel.Login.Login ()
Construct a Login
Definition at line 20 of file Login.cs.
         {
             InitializeComponent();
             var Config = Properties.Settings.Default;
             AcceptButton = RemoteLoginButton;
             if(Config.RemoteDefault)
                 RemoteLoginButton.TabIndex = 0; //make this the first thing selected when loading
             IPComboBox.SelectedIndexChanged += IPComboBox_SelectedIndexChanged;
             var loginInfo = Config.RemoteLoginInfo;
             if (loginInfo != null)
             {
                 foreach(var I in loginInfo)
                     IPComboBox.Items.Add(new RemoteLoginInfo(I));
                 if (IPComboBox.Items.Count > 0)
                     IPComboBox.SelectedIndex = 0;
             }
             IPComboBox.TextChanged += (a, b) => ClearFields(2);
             PortSelector.ValueChanged += (a, b) => ClearFields(3);
             UsernameTextBox.TextChanged += (a, b) => ClearFields(4);
         }
Member Function Documentation
void TGS.ControlPanel.Login.ClearFields (int start = 1) private
Definition at line 44 of file Login.cs.
References TGS.Interface.RemoteLoginInfo.HasPassword.
         {
             if (updatingFields || currentLoginInfo == null)
                 return;
             updatingFields = true;
             currentLoginInfo = null;
             switch (start) {
                 case 1:
                     IPComboBox.Text = "";
                     goto case 2;
                 case 2:
                     PortSelector.Value = 38607;
                     goto case 3;
                 case 3:
                     UsernameTextBox.Text = "";
                     goto case 4;
                 case 4:
                     if (currentLoginInfo.HasPassword)
                         PasswordTextBox.Text = "";
                     break;
             }
             updatingFields = false;
         }
void TGS.ControlPanel.Login.DeleteLoginButton_Click (object sender, EventArgs e) private
Removes the selected item from IPComboBox
Parameters
sender The sender of the event
e The EventArgs
Definition at line 182 of file Login.cs.
         {
             //make sure we're trying to delete a real item
             if (IPComboBox.SelectedItem as RemoteLoginInfo == null)
                 return;
             IPComboBox.Items.RemoveAt(IPComboBox.SelectedIndex);
         }
override void TGS.ControlPanel.Login.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file Login.Designer.cs.
         {
             if (disposing && (components != null))
             {
                 components.Dispose();
             }
             base.Dispose(disposing);
         }
void TGS.ControlPanel.Login.InitializeComponent () private
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 29 of file Login.Designer.cs.
         {
             System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Login));
             this.LocalLoginButton = new System.Windows.Forms.Button();
             this.CurrentRevisionTitle = new System.Windows.Forms.Label();
             this.UsernameTextBox = new System.Windows.Forms.TextBox();
             this.PasswordTextBox = new System.Windows.Forms.TextBox();
             this.RemoteLoginButton = new System.Windows.Forms.Button();
             this.AddressLabel = new System.Windows.Forms.Label();
             this.label2 = new System.Windows.Forms.Label();
             this.label3 = new System.Windows.Forms.Label();
             this.label4 = new System.Windows.Forms.Label();
             this.PortSelector = new System.Windows.Forms.NumericUpDown();
             this.SavePasswordCheckBox = new System.Windows.Forms.CheckBox();
             this.IPComboBox = new System.Windows.Forms.ComboBox();
             this.DeleteLoginButton = new System.Windows.Forms.Button();
             ((System.ComponentModel.ISupportInitialize)(this.PortSelector)).BeginInit();
             this.SuspendLayout();
             //
             // LocalLoginButton
             //
             this.LocalLoginButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
             this.LocalLoginButton.Location = new System.Drawing.Point(102, 12);
             this.LocalLoginButton.Name = "LocalLoginButton";
             this.LocalLoginButton.Size = new System.Drawing.Size(157, 25);
             this.LocalLoginButton.TabIndex = 1;
             this.LocalLoginButton.Text = "Connect to Local Service";
             this.LocalLoginButton.UseVisualStyleBackColor = true;
             this.LocalLoginButton.Click += new System.EventHandler(this.LocalLoginButton_Click);
             //
             // CurrentRevisionTitle
             //
             this.CurrentRevisionTitle.AutoSize = true;
             this.CurrentRevisionTitle.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.CurrentRevisionTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.CurrentRevisionTitle.Location = new System.Drawing.Point(116, 69);
             this.CurrentRevisionTitle.Name = "CurrentRevisionTitle";
             this.CurrentRevisionTitle.Size = new System.Drawing.Size(128, 18);
             this.CurrentRevisionTitle.TabIndex = 14;
             this.CurrentRevisionTitle.Text = "Remote Login:";
             this.CurrentRevisionTitle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // UsernameTextBox
             //
             this.UsernameTextBox.Location = new System.Drawing.Point(129, 132);
             this.UsernameTextBox.Name = "UsernameTextBox";
             this.UsernameTextBox.Size = new System.Drawing.Size(233, 20);
             this.UsernameTextBox.TabIndex = 16;
             //
             // PasswordTextBox
             //
             this.PasswordTextBox.Location = new System.Drawing.Point(129, 164);
             this.PasswordTextBox.Name = "PasswordTextBox";
             this.PasswordTextBox.Size = new System.Drawing.Size(233, 20);
             this.PasswordTextBox.TabIndex = 17;
             this.PasswordTextBox.UseSystemPasswordChar = true;
             //
             // RemoteLoginButton
             //
             this.RemoteLoginButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
             this.RemoteLoginButton.Location = new System.Drawing.Point(102, 200);
             this.RemoteLoginButton.Name = "RemoteLoginButton";
             this.RemoteLoginButton.Size = new System.Drawing.Size(157, 25);
             this.RemoteLoginButton.TabIndex = 18;
             this.RemoteLoginButton.Text = "Connect to Remote Service";
             this.RemoteLoginButton.UseVisualStyleBackColor = true;
             this.RemoteLoginButton.Click += new System.EventHandler(this.RemoteLoginButton_Click);
             //
             // AddressLabel
             //
             this.AddressLabel.AutoSize = true;
             this.AddressLabel.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.AddressLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.AddressLabel.Location = new System.Drawing.Point(9, 99);
             this.AddressLabel.Name = "AddressLabel";
             this.AddressLabel.Size = new System.Drawing.Size(80, 18);
             this.AddressLabel.TabIndex = 19;
             this.AddressLabel.Text = "Address:";
             this.AddressLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // label2
             //
             this.label2.AutoSize = true;
             this.label2.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.label2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.label2.Location = new System.Drawing.Point(9, 132);
             this.label2.Name = "label2";
             this.label2.Size = new System.Drawing.Size(97, 18);
             this.label2.TabIndex = 20;
             this.label2.Text = "Username:";
             this.label2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // label3
             //
             this.label3.AutoSize = true;
             this.label3.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.label3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.label3.Location = new System.Drawing.Point(9, 164);
             this.label3.Name = "label3";
             this.label3.Size = new System.Drawing.Size(92, 18);
             this.label3.TabIndex = 21;
             this.label3.Text = "Password:";
             this.label3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // label4
             //
             this.label4.AutoSize = true;
             this.label4.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
             this.label4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.label4.Location = new System.Drawing.Point(-19, 40);
             this.label4.Name = "label4";
             this.label4.Size = new System.Drawing.Size(468, 18);
             this.label4.TabIndex = 22;
             this.label4.Text = "______________________________________________";
             this.label4.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
             //
             // PortSelector
             //
             this.PortSelector.Location = new System.Drawing.Point(282, 99);
             this.PortSelector.Maximum = new decimal(new int[] {
             65535,
             0,
             0,
             0});
             this.PortSelector.Minimum = new decimal(new int[] {
             1,
             0,
             0,
             0});
             this.PortSelector.Name = "PortSelector";
             this.PortSelector.Size = new System.Drawing.Size(80, 20);
             this.PortSelector.TabIndex = 16;
             this.PortSelector.Value = new decimal(new int[] {
             38607,
             0,
             0,
             0});
             //
             // SavePasswordCheckBox
             //
             this.SavePasswordCheckBox.AutoSize = true;
             this.SavePasswordCheckBox.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(242)))));
             this.SavePasswordCheckBox.Location = new System.Drawing.Point(265, 205);
             this.SavePasswordCheckBox.Name = "SavePasswordCheckBox";
             this.SavePasswordCheckBox.Size = new System.Drawing.Size(100, 17);
             this.SavePasswordCheckBox.TabIndex = 23;
             this.SavePasswordCheckBox.Text = "Save Password";
             this.SavePasswordCheckBox.UseVisualStyleBackColor = true;
             this.SavePasswordCheckBox.CheckedChanged += new System.EventHandler(this.SavePasswordCheckBox_CheckedChanged);
             //
             // IPComboBox
             //
             this.IPComboBox.FormattingEnabled = true;
             this.IPComboBox.Location = new System.Drawing.Point(130, 98);
             this.IPComboBox.Name = "IPComboBox";
             this.IPComboBox.Size = new System.Drawing.Size(146, 21);
             this.IPComboBox.TabIndex = 24;
             //
             // DeleteLoginButton
             //
             this.DeleteLoginButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
             this.DeleteLoginButton.Location = new System.Drawing.Point(105, 98);
             this.DeleteLoginButton.Name = "DeleteLoginButton";
             this.DeleteLoginButton.Size = new System.Drawing.Size(19, 19);
             this.DeleteLoginButton.TabIndex = 25;
             this.DeleteLoginButton.Text = "x";
             this.DeleteLoginButton.UseVisualStyleBackColor = true;
             this.DeleteLoginButton.Click += new System.EventHandler(this.DeleteLoginButton_Click);
             //
             // Login
             //
             this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
             this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
             this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(40)))), ((int)(((byte)(34)))));
             this.ClientSize = new System.Drawing.Size(374, 237);
             this.Controls.Add(this.DeleteLoginButton);
             this.Controls.Add(this.IPComboBox);
             this.Controls.Add(this.SavePasswordCheckBox);
             this.Controls.Add(this.PortSelector);
             this.Controls.Add(this.label4);
             this.Controls.Add(this.label3);
             this.Controls.Add(this.label2);
             this.Controls.Add(this.AddressLabel);
             this.Controls.Add(this.RemoteLoginButton);
             this.Controls.Add(this.PasswordTextBox);
             this.Controls.Add(this.UsernameTextBox);
             this.Controls.Add(this.CurrentRevisionTitle);
             this.Controls.Add(this.LocalLoginButton);
             this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
             this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
             this.MaximizeBox = false;
             this.Name = "Login";
             this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
             this.Text = "Login";
             ((System.ComponentModel.ISupportInitialize)(this.PortSelector)).EndInit();
             this.ResumeLayout(false);
             this.PerformLayout();
         }
void TGS.ControlPanel.Login.IPComboBox_SelectedIndexChanged (object sender, EventArgs e) private
Definition at line 68 of file Login.cs.
References TGS.Interface.RemoteLoginInfo.HasPassword, TGS.Interface.RemoteLoginInfo.IP, TGS.Interface.RemoteLoginInfo.Port, and TGS.Interface.RemoteLoginInfo.Username.
         {
             RemoteLoginInfo newLoginInfo = IPComboBox.SelectedItem as RemoteLoginInfo;
             //new thing
             if (newLoginInfo == null)
             {
                 ClearFields();
                 currentLoginInfo = newLoginInfo;
                 return;
             }
             updatingFields = true;
             currentLoginInfo = newLoginInfo;
             IPComboBox.Text = currentLoginInfo.IP;
             PortSelector.Value = currentLoginInfo.Port;
             UsernameTextBox.Text = currentLoginInfo.Username;
             SavePasswordCheckBox.Checked = currentLoginInfo.HasPassword;
             if (currentLoginInfo.HasPassword)
                 PasswordTextBox.Text = "************";
             else
                 PasswordTextBox.Text = "";
             updatingFields = false;
         }
void TGS.ControlPanel.Login.LocalLoginButton_Click (object sender, EventArgs e) private
Definition at line 127 of file Login.cs.
         {
             Properties.Settings.Default.RemoteDefault = false;
             VerifyAndConnect(new Client());
         }
void TGS.ControlPanel.Login.RemoteLoginButton_Click (object sender, EventArgs e) private
Definition at line 91 of file Login.cs.
References TGS.Interface.RemoteLoginInfo.Equals(), TGS.Interface.RemoteLoginInfo.HasPassword, TGS.Interface.RemoteLoginInfo.Password, and TGS.Interface.RemoteLoginInfo.ToJSON().
         {
             if (String.IsNullOrWhiteSpace(PasswordTextBox.Text) || String.IsNullOrWhiteSpace(UsernameTextBox.Text) || String.IsNullOrWhiteSpace(IPComboBox.Text) || PortSelector.Value == 0)
                 return;
             RemoteLoginInfo loginInfo;
             if (currentLoginInfo == null)
             {
                 loginInfo = new RemoteLoginInfo(IPComboBox.Text, (ushort)PortSelector.Value, UsernameTextBox.Text.Trim(), PasswordTextBox.Text);
             }
             else
             {
                 loginInfo = (RemoteLoginInfo)IPComboBox.SelectedItem;
                 if (!loginInfo.HasPassword)
                     loginInfo.Password = PasswordTextBox.Text;
             }
             var I = new Client(loginInfo);
             var Config = Properties.Settings.Default;
             //This needs to be read here because V&C Closing us will corrupt the data
             var savePassword = SavePasswordCheckBox.Checked;
             if (VerifyAndConnect(I))
             {
                 Config.RemoteDefault = true;
                 if (!savePassword)
                     loginInfo.Password = null;
                 Config.RemoteLoginInfo = new StringCollection { loginInfo.ToJSON() };
                 foreach (RemoteLoginInfo info in IPComboBox.Items)
                     if (!info.Equals(loginInfo))
                         Config.RemoteLoginInfo.Add(info.ToJSON());
             }
         }
void TGS.ControlPanel.Login.SavePasswordCheckBox_CheckedChanged (object sender, EventArgs e) private
Definition at line 168 of file Login.cs.
         {
             if (!updatingFields && !SavePasswordCheckBox.Checked && currentLoginInfo != null)
             {
                 currentLoginInfo = null;
                 PasswordTextBox.Text = "";
             }
         }
bool TGS.ControlPanel.Login.VerifyAndConnect (IClient I) private
Attempts a connection on a given IClient
Parameters
I The IClient to attempt a connection on
Returns
if the connection was made and authenticated, otherwise
Definition at line 138 of file Login.cs.
References TGS.Interface.IClient.ConnectionStatus(), TGS.ControlPanel.Program.ServerInterface, and TGS.Interface.IClient.VersionMismatch().
         {
             try
             {
                 var res = I.ConnectionStatus(out string error);
                 if (!res.HasFlag(ConnectivityLevel.Connected))
                 {
                     MessageBox.Show("Unable to connect to service! Error: " + error);
                     return false;
                 }
                 if (!res.HasFlag(ConnectivityLevel.Authenticated))
                 {
                     MessageBox.Show("Authentication error: Username/password/windows identity is not authorized! Ensure you are a system administrator or in the correct Windows group on the service machine.");
                     return false;
                 }
                 if (I.VersionMismatch(out error) && MessageBox.Show(error, "Warning", MessageBoxButtons.OKCancel) == DialogResult.Cancel)
                     return true;
                 Close();
                 Program.ServerInterface = I;
                 return true;
             }
             catch
             {
                 I.Dispose();
                 throw;
             }
         }
Member Data Documentation
System.Windows.Forms.Label TGS.ControlPanel.Login.AddressLabel private
Definition at line 236 of file Login.Designer.cs.
System.ComponentModel.IContainer TGS.ControlPanel.Login.components = null private
Required designer variable.
Definition at line 8 of file Login.Designer.cs.
RemoteLoginInfo TGS.ControlPanel.Login.currentLoginInfo private
Currently selected saved RemoteLoginInfo
Definition at line 13 of file Login.cs.
System.Windows.Forms.Label TGS.ControlPanel.Login.CurrentRevisionTitle private
Definition at line 232 of file Login.Designer.cs.
System.Windows.Forms.Button TGS.ControlPanel.Login.DeleteLoginButton private
Definition at line 243 of file Login.Designer.cs.
System.Windows.Forms.ComboBox TGS.ControlPanel.Login.IPComboBox private
Definition at line 242 of file Login.Designer.cs.
System.Windows.Forms.Label TGS.ControlPanel.Login.label2 private
Definition at line 237 of file Login.Designer.cs.
System.Windows.Forms.Label TGS.ControlPanel.Login.label3 private
Definition at line 238 of file Login.Designer.cs.
System.Windows.Forms.Label TGS.ControlPanel.Login.label4 private
Definition at line 239 of file Login.Designer.cs.
System.Windows.Forms.Button TGS.ControlPanel.Login.LocalLoginButton private
Definition at line 231 of file Login.Designer.cs.
System.Windows.Forms.TextBox TGS.ControlPanel.Login.PasswordTextBox private
Definition at line 234 of file Login.Designer.cs.
System.Windows.Forms.NumericUpDown TGS.ControlPanel.Login.PortSelector private
Definition at line 240 of file Login.Designer.cs.
System.Windows.Forms.Button TGS.ControlPanel.Login.RemoteLoginButton private
Definition at line 235 of file Login.Designer.cs.
System.Windows.Forms.CheckBox TGS.ControlPanel.Login.SavePasswordCheckBox private
Definition at line 241 of file Login.Designer.cs.
bool TGS.ControlPanel.Login.updatingFields private
Definition at line 15 of file Login.cs.
System.Windows.Forms.TextBox TGS.ControlPanel.Login.UsernameTextBox private
Definition at line 233 of file Login.Designer.cs.
The documentation for this class was generated from the following files:
TGS.ControlPanel/Login.cs
TGS.ControlPanel/Login.Designer.cs