tgstation-server: Tgstation.Server.Host.Components.Events.EventConsumer Class Reference
Tgstation.Server.Host.Components.Events.EventConsumer Class Reference
Public Member Functions
EventConsumer (IConfiguration configuration)
Construct an IEventConsumer
async Task HandleEvent (EventType eventType, IEnumerable< string > parameters, CancellationToken cancellationToken)
Handle a given eventType
void SetWatchdog (IWatchdog watchdog)
Set the watchdog for the EventConsumer
Private Attributes
readonly IConfiguration configuration
The IConfiguration for the EventConsumer
IWatchdog watchdog
The IWatchdog for the EventConsumer
Detailed Description
Definition at line 11 of file EventConsumer.cs.
Constructor & Destructor Documentation
EventConsumer()
Tgstation.Server.Host.Components.Events.EventConsumer.EventConsumer (IConfiguration configuration)
Construct an IEventConsumer
Parameters
configuration The value of configuration
Definition at line 27 of file EventConsumer.cs.
         {
             this.configuration = configuration ?? throw new ArgumentNullException(nameof(configuration));
         }
References Tgstation.Server.Host.Components.Events.EventConsumer.configuration.
Member Function Documentation
HandleEvent()
async Task Tgstation.Server.Host.Components.Events.EventConsumer.HandleEvent (EventType eventType, IEnumerable< string > parameters, CancellationToken cancellationToken)
Handle a given eventType
Implements Tgstation.Server.Host.Components.Events.IEventConsumer.
Definition at line 33 of file EventConsumer.cs.
         {
             if (watchdog == null)
                 throw new InvalidOperationException("EventConsumer used without watchdog set!");
             await configuration.HandleEvent(eventType, parameters, cancellationToken).ConfigureAwait(false);
             await watchdog.HandleEvent(eventType, parameters, cancellationToken).ConfigureAwait(false);
         }
References Tgstation.Server.Host.Components.Events.EventConsumer.configuration, Tgstation.Server.Host.Components.Events.IEventConsumer.HandleEvent(), and Tgstation.Server.Host.Components.Events.EventConsumer.watchdog.
Referenced by Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.HandleMonitorWakeup(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.LaunchNoLock(), and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.TerminateNoLock().
SetWatchdog()
void Tgstation.Server.Host.Components.Events.EventConsumer.SetWatchdog (IWatchdog watchdog)
Set the watchdog for the EventConsumer
Parameters
watchdog The value of watchdog
Definition at line 46 of file EventConsumer.cs.
         {
 #pragma warning disable IDE0016 // Use 'throw' expression
             if (watchdog == null)
                 throw new ArgumentNullException(nameof(watchdog));
 #pragma warning restore IDE0016 // Use 'throw' expression
             if (this.watchdog != null)
                 throw new InvalidOperationException("watchdog already set!");
             this.watchdog = watchdog;
         }
References Tgstation.Server.Host.Components.Events.EventConsumer.watchdog.
Member Data Documentation
configuration
readonly IConfiguration Tgstation.Server.Host.Components.Events.EventConsumer.configuration private
The IConfiguration for the EventConsumer
Definition at line 16 of file EventConsumer.cs.
Referenced by Tgstation.Server.Host.Components.Events.EventConsumer.EventConsumer(), and Tgstation.Server.Host.Components.Events.EventConsumer.HandleEvent().
watchdog
IWatchdog Tgstation.Server.Host.Components.Events.EventConsumer.watchdog private
The IWatchdog for the EventConsumer
Definition at line 21 of file EventConsumer.cs.
Referenced by Tgstation.Server.Host.Components.Events.EventConsumer.HandleEvent(), and Tgstation.Server.Host.Components.Events.EventConsumer.SetWatchdog().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Events/EventConsumer.cs