tgstation-server: Tgstation.Server.Host.Controllers.ComponentInterfacingController Class Reference
Tgstation.Server.Host.Controllers.ComponentInterfacingController Class Reference abstract
ApiController for operations on IInstanceCores.
Protected Member Functions
ComponentInterfacingController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ILogger< ComponentInterfacingController > logger, IInstanceManager instanceManager, IApiHeadersProvider apiHeaders, bool useInstanceRequestHeader)
Initializes a new instance of the ComponentInterfacingController class.
override async ValueTask< IActionResult?> ValidateRequest (CancellationToken cancellationToken)
Performs validation a request.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in an appropriate IActionResult on validation failure, null otherwise.
bool ValidateInstanceOnlineStatus (Api.Models.Instance metadata)
Corrects discrepencies between the Api.Models.Instance.Online status of IInstances in the database vs the service.
async ValueTask< IActionResult?> WithComponentInstanceNullable (Func< IInstanceCore, ValueTask< IActionResult?> > action, Models.Instance? instance=null)
Run a given action with the relevant IInstance.
async ValueTask< IActionResult > WithComponentInstance (Func< IInstanceCore, ValueTask< IActionResult > > action, Models.Instance? instance=null)
Run a given action with the relevant IInstance.
Protected Member Functions inherited from Tgstation.Server.Host.Controllers.ApiController
ApiController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, IApiHeadersProvider apiHeadersProvider, ILogger< ApiController > logger, bool requireHeaders)
Initializes a new instance of the ApiController class.
override async ValueTask< IActionResult?> HookExecuteAction (Func< Task > executeAction, CancellationToken cancellationToken)
Hook for executing a request.
Parameters
executeAction A Func<TResult> that should be invoked and its response awaited to continue normal execution of the request. Should NOT be called if this method returns a non-null value.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in an IActionResult that, if not null, is executed.
new NotFoundObjectResult NotFound ()
Generic 404 response.
StatusCodeResult StatusCode (HttpStatusCode statusCode)
Strongly type calls to ControllerBase.StatusCode(int).
ObjectResult RateLimit (RateLimitExceededException rateLimitException)
429 response for a given rateLimitException .
IActionResult HeadersIssue (HeadersException headersException)
Response for missing/Invalid headers.
ValueTask< IActionResult > Paginated< TModel > (Func< ValueTask< PaginatableResult< TModel >?> > queryGenerator, Func< TModel, ValueTask >? resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
ValueTask< IActionResult > Paginated< TModel, TApiModel > (Func< ValueTask< PaginatableResult< TModel >?> > queryGenerator, Func< TApiModel, ValueTask >? resultTransformer, int? pageQuery, int? pageSizeQuery, CancellationToken cancellationToken)
Generates a paginated response.
Properties
IInstanceOperations InstanceOperations [get]
Access the IInstanceOperations instance.
Properties inherited from Tgstation.Server.Host.Controllers.ApiController
ApiHeaders? ApiHeaders [get]
The Api.ApiHeaders for the operation.
IApiHeadersProvider ApiHeadersProvider [get]
The IApiHeadersProvider containing value of ApiHeaders.
IDatabaseContext DatabaseContext [get]
The IDatabaseContext for the operation.
IAuthenticationContext AuthenticationContext [get]
The IAuthenticationContext for the operation.
ILogger< ApiController > Logger [get]
The ILogger for the ApiController.
Models.? Instance Instance [get]
The Instance for the operation.
Private Attributes
readonly IInstanceManager instanceManager
The IInstanceManager for the ComponentInterfacingController.
readonly bool useInstanceRequestHeader
If the Api.ApiHeaders.InstanceId header should be checked and used to perform validation for every request.
Additional Inherited Members
Public Member Functions inherited from Tgstation.Server.Host.Controllers.ApiControllerBase
override async Task OnActionExecutionAsync (ActionExecutingContext context, ActionExecutionDelegate next)
Static Public Attributes inherited from Tgstation.Server.Host.Controllers.ApiController
const ushort DefaultPageSize = 10
Default size of Paginated<TModel> results.
const ushort MaximumPageSize = 100
Maximum size of Paginated<TModel> results.
Detailed Description
ApiController for operations on IInstanceCores.
Definition at line 23 of file ComponentInterfacingController.cs.
Constructor & Destructor Documentation
ComponentInterfacingController()
Tgstation.Server.Host.Controllers.ComponentInterfacingController.ComponentInterfacingController (IDatabaseContext databaseContext, IAuthenticationContext authenticationContext, ILogger< ComponentInterfacingController > logger, IInstanceManager instanceManager, IApiHeadersProvider apiHeaders, bool useInstanceRequestHeader) protected
Initializes a new instance of the ComponentInterfacingController class.
Parameters
instanceManager The value of instanceManager.
databaseContext The IDatabaseContext for the ApiController.
authenticationContext The IAuthenticationContext for the ApiController.
logger The ILogger for the ApiController.
apiHeaders The IApiHeadersProvider for the ApiController.
useInstanceRequestHeader The value of useInstanceRequestHeader.
Definition at line 49 of file ComponentInterfacingController.cs.
            : base(
                  databaseContext,
                  authenticationContext,
                  apiHeaders,
                  logger,
                  true)
        {
            this.instanceManager = instanceManager ?? throw new ArgumentNullException(nameof(instanceManager));
            this.useInstanceRequestHeader = useInstanceRequestHeader;
        }
References Tgstation.Server.Host.Controllers.ComponentInterfacingController.instanceManager, and Tgstation.Server.Host.Controllers.ComponentInterfacingController.useInstanceRequestHeader.
Member Function Documentation
ValidateInstanceOnlineStatus()
bool Tgstation.Server.Host.Controllers.ComponentInterfacingController.ValidateInstanceOnlineStatus (Api::Models::Instance metadata) protected
Corrects discrepencies between the Api.Models.Instance.Online status of IInstances in the database vs the service.
Parameters
metadata The Api.Models.Instance to check.
Returns
true if an unsaved DB update was made, false otherwise.
Definition at line 95 of file ComponentInterfacingController.cs.
        {
            ArgumentNullException.ThrowIfNull(metadata);
            bool online;
            using (var instanceReferenceCheck = instanceManager.GetInstanceReference(metadata))
                online = instanceReferenceCheck != null;
            if (metadata.Require(x => x.Online) == online)
                return false;
            const string OfflineWord = "offline";
            const string OnlineWord = "online";
            Logger.LogWarning(
                "Instance {instanceId} is says it's {databaseState} in the database, but it is actually {serviceState} in the service. Updating the database to reflect this...",
                metadata.Id,
                online ? OfflineWord : OnlineWord,
                online ? OnlineWord : OfflineWord);
            metadata.Online = online;
            return true;
        }
References Tgstation.Server.Host.Components.IInstanceManager.GetInstanceReference(), Tgstation.Server.Host.Controllers.ComponentInterfacingController.instanceManager, and Tgstation.Server.Host.Controllers.ApiController.Logger.
Referenced by Tgstation.Server.Host.Controllers.InstanceController.GetId(), Tgstation.Server.Host.Controllers.InstanceController.List(), Tgstation.Server.Host.Controllers.InstanceController.Update(), and Tgstation.Server.Host.Controllers.ComponentInterfacingController.ValidateRequest().
ValidateRequest()
override async ValueTask< IActionResult?> Tgstation.Server.Host.Controllers.ComponentInterfacingController.ValidateRequest (CancellationToken cancellationToken) protected virtual
Performs validation a request.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in an appropriate IActionResult on validation failure, null otherwise.
Reimplemented from Tgstation.Server.Host.Controllers.ApiController.
Definition at line 68 of file ComponentInterfacingController.cs.
        {
            if (!useInstanceRequestHeader)
                return null;
            if (!ApiHeaders!.InstanceId.HasValue)
                return BadRequest(new ErrorMessageResponse(ErrorCode.InstanceHeaderRequired));
            if (AuthenticationContext.InstancePermissionSet == null)
                return Forbid();
            var instance = Instance!;
            if (ValidateInstanceOnlineStatus(instance))
                await DatabaseContext.Save(cancellationToken);
            using var instanceReferenceCheck = instanceManager.GetInstanceReference(instance);
            if (instanceReferenceCheck == null)
                return Conflict(new ErrorMessageResponse(ErrorCode.InstanceOffline));
            return null;
        }
References Tgstation.Server.Host.Components.IInstanceManager.GetInstanceReference(), Tgstation.Server.Host.Controllers.ComponentInterfacingController.instanceManager, Tgstation.Server.Host.Security.AuthenticationContext.InstancePermissionSet, Tgstation.Server.Host.Database.DatabaseContext.Save(), Tgstation.Server.Host.Controllers.ComponentInterfacingController.useInstanceRequestHeader, and Tgstation.Server.Host.Controllers.ComponentInterfacingController.ValidateInstanceOnlineStatus().
WithComponentInstance()
async ValueTask< IActionResult > Tgstation.Server.Host.Controllers.ComponentInterfacingController.WithComponentInstance (Func< IInstanceCore, ValueTask< IActionResult > > action, Models.Instance? instance = null) protected
Run a given action with the relevant IInstance.
Parameters
action A Func<T, TResult> accepting the IInstance and returning a ValueTask<TResult> with the IActionResult.
instance The Models.Instance to grab. If null, ApiController.Instance will be used.
Returns
A ValueTask<TResult> resulting in the IActionResult that should be returned.
The context of action should be as small as possible so as to avoid race conditions. This function can return a ConflictResult if the requested instance was offline.
Referenced by Tgstation.Server.Host.Controllers.RepositoryController.Create(), Tgstation.Server.Host.Controllers.ConfigurationController.CreateDirectory(), Tgstation.Server.Host.Controllers.ConfigurationController.DeleteDirectory(), Tgstation.Server.Host.Controllers.ConfigurationController.File(), Tgstation.Server.Host.Controllers.RepositoryController.Read(), Tgstation.Server.Host.Controllers.ConfigurationController.Update(), Tgstation.Server.Host.Controllers.DreamDaemonController.Update(), and Tgstation.Server.Host.Controllers.EngineController.Update().
WithComponentInstanceNullable()
async ValueTask< IActionResult?> Tgstation.Server.Host.Controllers.ComponentInterfacingController.WithComponentInstanceNullable (Func< IInstanceCore, ValueTask< IActionResult?> > action, Models::Instance? instance = null) protected
Run a given action with the relevant IInstance.
Parameters
action A Func<T, TResult> accepting the IInstance and returning a ValueTask<TResult> with the IActionResult.
instance The Models.Instance to grab. If null, ApiController.Instance will be used.
Returns
A ValueTask<TResult> resulting in the IActionResult that should be returned.
The context of action should be as small as possible so as to avoid race conditions. This function can return a ConflictResult if the requested instance was offline.
Definition at line 126 of file ComponentInterfacingController.cs.
        {
            ArgumentNullException.ThrowIfNull(action);
            instance ??= Instance ?? throw new InvalidOperationException("ComponentInterfacingController has no Instance!");
            using var instanceReference = instanceManager.GetInstanceReference(instance);
            using (LogContext.PushProperty(SerilogContextHelper.InstanceReferenceContextProperty, instanceReference?.Uid))
            {
                if (instanceReference == null)
                    return Conflict(new ErrorMessageResponse(ErrorCode.InstanceOffline));
                return await action(instanceReference);
            }
        }
References Tgstation.Server.Host.Components.IInstanceManager.GetInstanceReference(), Tgstation.Server.Host.Controllers.ComponentInterfacingController.instanceManager, and Tgstation.Server.Host.Utils.SerilogContextHelper.InstanceReferenceContextProperty.
Referenced by Tgstation.Server.Host.Controllers.EngineController.Delete(), Tgstation.Server.Host.Controllers.ChatController.Update(), Tgstation.Server.Host.Controllers.InstanceController.Update(), and Tgstation.Server.Host.Controllers.RepositoryController.Update().
Member Data Documentation
instanceManager
readonly IInstanceManager Tgstation.Server.Host.Controllers.ComponentInterfacingController.instanceManager private
The IInstanceManager for the ComponentInterfacingController.
Definition at line 33 of file ComponentInterfacingController.cs.
Referenced by Tgstation.Server.Host.Controllers.ComponentInterfacingController.ComponentInterfacingController(), Tgstation.Server.Host.Controllers.ComponentInterfacingController.ValidateInstanceOnlineStatus(), Tgstation.Server.Host.Controllers.ComponentInterfacingController.ValidateRequest(), and Tgstation.Server.Host.Controllers.ComponentInterfacingController.WithComponentInstanceNullable().
useInstanceRequestHeader
readonly bool Tgstation.Server.Host.Controllers.ComponentInterfacingController.useInstanceRequestHeader private
If the Api.ApiHeaders.InstanceId header should be checked and used to perform validation for every request.
Definition at line 38 of file ComponentInterfacingController.cs.
Referenced by Tgstation.Server.Host.Controllers.ComponentInterfacingController.ComponentInterfacingController(), and Tgstation.Server.Host.Controllers.ComponentInterfacingController.ValidateRequest().
Property Documentation
InstanceOperations
IInstanceOperations Tgstation.Server.Host.Controllers.ComponentInterfacingController.InstanceOperations get
Access the IInstanceOperations instance.
Definition at line 28 of file ComponentInterfacingController.cs.
Referenced by Tgstation.Server.Host.Controllers.InstanceController.Update().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Controllers/ComponentInterfacingController.cs