tgstation-server: Tgstation.Server.Host.Authority.UserGroupAuthority Class Reference
Tgstation.Server.Host.Authority.UserGroupAuthority Class Reference sealed
Public Member Functions
UserGroupAuthority (IAuthenticationContext authenticationContext, IDatabaseContext databaseContext, ILogger< UserGroupAuthority > logger, IUserGroupsDataLoader userGroupsDataLoader, IOptionsSnapshot< GeneralConfiguration > generalConfigurationOptions)
Initializes a new instance of the UserGroupAuthority class.
async ValueTask< AuthorityResponse< UserGroup > > GetId (long id, bool includeJoins, CancellationToken cancellationToken)
Gets the UserGroup with a given id .
Parameters
id The Api.Models.EntityId.Id of the UserGroup.
includeJoins If related entities should be loaded.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a User AuthorityResponse<TResult>.
ValueTask< AuthorityResponse< UserGroup > > Read ()
Gets the current UserGroup.
Returns
A ValueTask<TResult> resulting in a UserGroup AuthorityResponse<TResult>.
IQueryable< UserGroup > Queryable (bool includeJoins)
Gets all registered UserGroups.
Parameters
includeJoins If related entities should be loaded.
Returns
A IQueryable<T> of UserGroups.
async ValueTask< AuthorityResponse< UserGroup > > Create (string name, Models.PermissionSet? permissionSet, CancellationToken cancellationToken)
Create a UserGroup.
Parameters
name The created UserGroup's Api.Models.NamedEntity.Name.
permissionSet The created UserGroup's UserGroup.PermissionSet.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a UserGroup AuthorityResponse<TResult>.
async ValueTask< AuthorityResponse< UserGroup > > Update (long id, string? newName, Models.PermissionSet? newPermissionSet, CancellationToken cancellationToken)
Updates a UserGroup.
Parameters
id The Api.Models.EntityId.Id of the UserGroup to update.
newName The optional new Api.Models.NamedEntity.Name for the UserGroup.
newPermissionSet The optional new UserGroup.PermissionSet for the UserGroup.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a UserGroup AuthorityResponse<TResult>.
async ValueTask< AuthorityResponse > DeleteEmpty (long id, CancellationToken cancellationToken)
Deletes an empty UserGroup.
Parameters
id The Api.Models.EntityId.Id of the UserGroup to delete.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Static Public Member Functions
static Task< Dictionary< long, UserGroup > > GetUserGroups (IReadOnlyList< long > ids, IDatabaseContext databaseContext, CancellationToken cancellationToken)
Implements the userGroupsDataLoader.
Private Attributes
readonly IUserGroupsDataLoader userGroupsDataLoader
The IUserGroupsDataLoader for the UserGroupAuthority.
readonly IOptionsSnapshot< GeneralConfiguration > generalConfigurationOptions
The IOptionsSnapshot<TOptions> of the GeneralConfiguration.
Additional Inherited Members
Protected Member Functions inherited from Tgstation.Server.Host.Authority.Core.AuthorityBase
AuthorityBase (IAuthenticationContext authenticationContext, IDatabaseContext databaseContext, ILogger< AuthorityBase > logger)
Initializes a new instance of the AuthorityBase class.
AuthorityResponse< TResult > RateLimit< TResult > (RateLimitExceededException rateLimitException)
Generates a HttpFailureResponse.RateLimited type AuthorityResponse.
Static Protected Member Functions inherited from Tgstation.Server.Host.Authority.Core.AuthorityBase
static AuthorityResponse< TResult > BadRequest< TResult > (ErrorCode errorCode)
Generates a HttpFailureResponse.BadRequest type AuthorityResponse<TResult>.
static AuthorityResponse< TResult > Unauthorized< TResult > ()
Generates a HttpFailureResponse.Unauthorized type AuthorityResponse<TResult>.
static AuthorityResponse< TResult > Gone< TResult > ()
Generates a HttpFailureResponse.Forbidden type AuthorityResponse<TResult>.
static AuthorityResponse< TResult > Forbid< TResult > ()
Generates a HttpFailureResponse.Forbidden type AuthorityResponse<TResult>.
static AuthorityResponse< TResult > NotFound< TResult > ()
Generates a HttpFailureResponse.NotFound type AuthorityResponse<TResult>.
static AuthorityResponse< TResult > Conflict< TResult > (ErrorCode errorCode)
Generates a HttpFailureResponse.Conflict type AuthorityResponse<TResult>.
Properties inherited from Tgstation.Server.Host.Authority.Core.AuthorityBase
IAuthenticationContext AuthenticationContext [get]
Gets the IAuthenticationContext for the AuthorityBase.
IDatabaseContext DatabaseContext [get]
Gets the IDatabaseContext for the AuthorityBase.
ILogger< AuthorityBase > Logger [get]
Gets the ILogger for the AuthorityBase.
Detailed Description
Definition at line 25 of file UserGroupAuthority.cs.
Constructor & Destructor Documentation
UserGroupAuthority()
Tgstation.Server.Host.Authority.UserGroupAuthority.UserGroupAuthority (IAuthenticationContext authenticationContext, IDatabaseContext databaseContext, ILogger< UserGroupAuthority > logger, IUserGroupsDataLoader userGroupsDataLoader, IOptionsSnapshot< GeneralConfiguration > generalConfigurationOptions)
Initializes a new instance of the UserGroupAuthority class.
Parameters
authenticationContext The IAuthenticationContext to use.
databaseContext The IDatabaseContext to use.
logger The ILogger to use.
userGroupsDataLoader The value of userGroupsDataLoader.
generalConfigurationOptions The value of generalConfigurationOptions.
Definition at line 67 of file UserGroupAuthority.cs.
            : base(
                  authenticationContext,
                  databaseContext,
                  logger)
        {
            this.userGroupsDataLoader = userGroupsDataLoader ?? throw new ArgumentNullException(nameof(userGroupsDataLoader));
            this.generalConfigurationOptions = generalConfigurationOptions ?? throw new ArgumentNullException(nameof(generalConfigurationOptions));
        }
References Tgstation.Server.Host.Authority.UserGroupAuthority.generalConfigurationOptions, Tgstation.Server.Api.Rights.List, and Tgstation.Server.Host.Authority.UserGroupAuthority.userGroupsDataLoader.
Member Function Documentation
Create()
async ValueTask< AuthorityResponse< UserGroup > > Tgstation.Server.Host.Authority.UserGroupAuthority.Create (string name, Models::PermissionSet? permissionSet, CancellationToken cancellationToken)
Create a UserGroup.
Parameters
name The created UserGroup's Api.Models.NamedEntity.Name.
permissionSet The created UserGroup's UserGroup.PermissionSet.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a UserGroup AuthorityResponse<TResult>.
Implements Tgstation.Server.Host.Authority.IUserGroupAuthority.
Definition at line 128 of file UserGroupAuthority.cs.
        {
            ArgumentNullException.ThrowIfNull(name);
            var totalGroups = await DatabaseContext
                .Groups
                .AsQueryable()
                .CountAsync(cancellationToken);
            if (totalGroups >= generalConfigurationOptions.Value.UserGroupLimit)
                return Conflict<UserGroup>(ErrorCode.UserGroupLimitReached);
            var modelPermissionSet = new Models.PermissionSet
            {
                AdministrationRights = permissionSet?.AdministrationRights ?? AdministrationRights.None,
                InstanceManagerRights = permissionSet?.InstanceManagerRights ?? InstanceManagerRights.None,
            };
            var dbGroup = new UserGroup
            {
                Name = name,
                PermissionSet = modelPermissionSet,
            };
            DatabaseContext.Groups.Add(dbGroup);
            await DatabaseContext.Save(cancellationToken);
            Logger.LogInformation("Created new user group {groupName} ({groupId})", dbGroup.Name, dbGroup.Id);
            return new AuthorityResponse<UserGroup>(
                dbGroup,
                HttpSuccessResponse.Created);
        }
References Tgstation.Server.Api.Models.PermissionSet.AdministrationRights, Tgstation.Server.Host.Authority.UserGroupAuthority.generalConfigurationOptions, Tgstation.Server.Host.Database.DatabaseContext.Groups, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Authority.Core.AuthorityBase.Logger, and Tgstation.Server.Host.Database.DatabaseContext.Save().
DeleteEmpty()
async ValueTask< AuthorityResponse > Tgstation.Server.Host.Authority.UserGroupAuthority.DeleteEmpty (long id, CancellationToken cancellationToken)
Deletes an empty UserGroup.
Parameters
id The Api.Models.EntityId.Id of the UserGroup to delete.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implements Tgstation.Server.Host.Authority.IUserGroupAuthority.
Definition at line 187 of file UserGroupAuthority.cs.
        {
            var numDeleted = await DatabaseContext
                .Groups
                .AsQueryable()
                .Where(x => x.Id == id && x.Users!.Count == 0)
                .ExecuteDeleteAsync(cancellationToken);
            if (numDeleted > 0)
                return new();
            // find out how we failed
            var groupExists = await DatabaseContext
                .Groups
                .AsQueryable()
                .Where(x => x.Id == id)
                .AnyAsync(cancellationToken);
            return new(
                groupExists
                    ? new ErrorMessageResponse(ErrorCode.UserGroupNotEmpty)
                    : new ErrorMessageResponse(),
                groupExists
                    ? HttpFailureResponse.Conflict
                    : HttpFailureResponse.Gone);
        }
References Tgstation.Server.Host.Database.DatabaseContext.Groups, and Tgstation.Server.Api.Rights.List.
GetId()
async ValueTask< AuthorityResponse< UserGroup > > Tgstation.Server.Host.Authority.UserGroupAuthority.GetId (long id, bool includeJoins, CancellationToken cancellationToken)
Gets the UserGroup with a given id .
Parameters
id The Api.Models.EntityId.Id of the UserGroup.
includeJoins If related entities should be loaded.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a User AuthorityResponse<TResult>.
Implements Tgstation.Server.Host.Authority.IUserGroupAuthority.
Definition at line 83 of file UserGroupAuthority.cs.
        {
            if (id != AuthenticationContext.User.GroupId && !((AdministrationRights)AuthenticationContext.GetRight(RightsType.Administration)).HasFlag(AdministrationRights.ReadUsers))
                return Forbid<UserGroup>();
            UserGroup? userGroup;
            if (includeJoins)
                userGroup = await Queryable(true)
                    .Where(x => x.Id == id)
                    .FirstOrDefaultAsync(cancellationToken);
            else
                userGroup = await userGroupsDataLoader.LoadAsync(id, cancellationToken);
            if (userGroup == null)
                return Gone<UserGroup>();
            return new AuthorityResponse<UserGroup>(userGroup);
        }
References Tgstation.Server.Host.Security.AuthenticationContext.GetRight(), Tgstation.Server.Host.Models.User.GroupId, Tgstation.Server.Api.Rights.List, Tgstation.Server.Host.Authority.UserGroupAuthority.Queryable(), Tgstation.Server.Host.Security.AuthenticationContext.User, and Tgstation.Server.Host.Authority.UserGroupAuthority.userGroupsDataLoader.
GetUserGroups()
static Task< Dictionary< long, UserGroup > > Tgstation.Server.Host.Authority.UserGroupAuthority.GetUserGroups (IReadOnlyList< long > ids, IDatabaseContext databaseContext, CancellationToken cancellationToken) static
Implements the userGroupsDataLoader.
Parameters
ids The IReadOnlyList<T> of UserGroup EntityId.Ids to load.
databaseContext The IDatabaseContext to load from.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a Dictionary<TKey, TValue> of the requested UserGroups.
Definition at line 45 of file UserGroupAuthority.cs.
        {
            ArgumentNullException.ThrowIfNull(ids);
            ArgumentNullException.ThrowIfNull(databaseContext);
            return databaseContext
                .Groups
                .Where(group => ids.Contains(group.Id!.Value))
                .ToDictionaryAsync(userGroup => userGroup.Id!.Value, cancellationToken);
        }
References Tgstation.Server.Host.Database.IDatabaseContext.Groups, and Tgstation.Server.Api.Rights.List.
Queryable()
IQueryable< UserGroup > Tgstation.Server.Host.Authority.UserGroupAuthority.Queryable (bool includeJoins)
Gets all registered UserGroups.
Parameters
includeJoins If related entities should be loaded.
Returns
A IQueryable<T> of UserGroups.
Implements Tgstation.Server.Host.Authority.IUserGroupAuthority.
Definition at line 113 of file UserGroupAuthority.cs.
        {
            var queryable = DatabaseContext
                .Groups
                .AsQueryable();
            if (includeJoins)
                queryable = queryable
                    .Include(x => x.Users)
                    .Include(x => x.PermissionSet);
            return queryable;
        }
References Tgstation.Server.Host.Database.DatabaseContext.Groups, and Tgstation.Server.Api.Rights.List.
Referenced by Tgstation.Server.Host.Authority.UserGroupAuthority.GetId().
Read()
ValueTask< AuthorityResponse< UserGroup > > Tgstation.Server.Host.Authority.UserGroupAuthority.Read ()
Gets the current UserGroup.
Returns
A ValueTask<TResult> resulting in a UserGroup AuthorityResponse<TResult>.
Implements Tgstation.Server.Host.Authority.IUserGroupAuthority.
Definition at line 103 of file UserGroupAuthority.cs.
        {
            var group = AuthenticationContext.User!.Group;
            if (group == null)
                return ValueTask.FromResult(Gone<UserGroup>());
            return ValueTask.FromResult(new AuthorityResponse<UserGroup>(group));
        }
References Tgstation.Server.Host.Models.User.Group, Tgstation.Server.Api.Rights.List, and Tgstation.Server.Host.Security.AuthenticationContext.User.
Update()
async ValueTask< AuthorityResponse< UserGroup > > Tgstation.Server.Host.Authority.UserGroupAuthority.Update (long id, string? newName, Models::PermissionSet? newPermissionSet, CancellationToken cancellationToken)
Updates a UserGroup.
Parameters
id The Api.Models.EntityId.Id of the UserGroup to update.
newName The optional new Api.Models.NamedEntity.Name for the UserGroup.
newPermissionSet The optional new UserGroup.PermissionSet for the UserGroup.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a UserGroup AuthorityResponse<TResult>.
Implements Tgstation.Server.Host.Authority.IUserGroupAuthority.
Definition at line 161 of file UserGroupAuthority.cs.
        {
            var currentGroup = await DatabaseContext
                .Groups
                .AsQueryable()
                .Where(x => x.Id == id)
                .Include(x => x.PermissionSet)
                .FirstOrDefaultAsync(cancellationToken);
            if (currentGroup == default)
                return Gone<UserGroup>();
            if (newPermissionSet != null)
            {
                currentGroup.PermissionSet!.AdministrationRights = newPermissionSet.AdministrationRights ?? currentGroup.PermissionSet.AdministrationRights;
                currentGroup.PermissionSet.InstanceManagerRights = newPermissionSet.InstanceManagerRights ?? currentGroup.PermissionSet.InstanceManagerRights;
            }
            currentGroup.Name = newName ?? currentGroup.Name;
            await DatabaseContext.Save(cancellationToken);
            return new AuthorityResponse<UserGroup>(currentGroup);
        }
References Tgstation.Server.Host.Database.DatabaseContext.Groups, Tgstation.Server.Api.Rights.List, and Tgstation.Server.Host.Database.DatabaseContext.Save().
Member Data Documentation
generalConfigurationOptions
readonly IOptionsSnapshot<GeneralConfiguration> Tgstation.Server.Host.Authority.UserGroupAuthority.generalConfigurationOptions private
The IOptionsSnapshot<TOptions> of the GeneralConfiguration.
Definition at line 35 of file UserGroupAuthority.cs.
Referenced by Tgstation.Server.Host.Authority.UserGroupAuthority.Create(), and Tgstation.Server.Host.Authority.UserGroupAuthority.UserGroupAuthority().
userGroupsDataLoader
readonly IUserGroupsDataLoader Tgstation.Server.Host.Authority.UserGroupAuthority.userGroupsDataLoader private
The IUserGroupsDataLoader for the UserGroupAuthority.
Definition at line 30 of file UserGroupAuthority.cs.
Referenced by Tgstation.Server.Host.Authority.UserGroupAuthority.GetId(), and Tgstation.Server.Host.Authority.UserGroupAuthority.UserGroupAuthority().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Authority/UserGroupAuthority.cs