tgstation-server: Tgstation.Server.Host.Components.Instance Class Reference
Tgstation.Server.Host.Components.Instance Class Reference
Public Member Functions
Instance (Api.Models.Instance metadata, IRepositoryManager repositoryManager, IByondManager byondManager, IDreamMaker dreamMaker, IWatchdog watchdog, IChatManager chat, StaticFiles.IConfiguration configuration, ICompileJobConsumer compileJobConsumer, IDatabaseContextFactory databaseContextFactory, IDmbFactory dmbFactory, IJobManager jobManager, IEventConsumer eventConsumer, IGitHubClientFactory gitHubClientFactory, ILogger< Instance > logger)
Construct an Instance
void Dispose ()
async Task CompileProcess (Job job, IDatabaseContext databaseContext, Action< int > progressReporter, CancellationToken cancellationToken)
Run the compile job and insert it into the database. Meant to be called by a Jobs.IJobManager
void Rename (string newName)
Rename the IInstance
async Task StartAsync (CancellationToken cancellationToken)
async Task StopAsync (CancellationToken cancellationToken)
async Task SetAutoUpdateInterval (uint newInterval)
Change the Api.Models.Instance.AutoUpdateInterval for the IInstance
CompileJob LatestCompileJob ()
The latest staged CompileJob
Properties
IRepositoryManager RepositoryManager [get]
IByondManager ByondManager [get]
IWatchdog Watchdog [get]
IChatManager Chat [get]
StaticFiles.IConfiguration Configuration [get]
Properties inherited from Tgstation.Server.Host.Components.IInstance
IRepositoryManager RepositoryManager [get]
The IRepositoryManager for the IInstance
IByondManager ByondManager [get]
The IByondManager for the IInstance
IWatchdog Watchdog [get]
The IWatchdog for the IInstance
IChatManager Chat [get]
The IChatManager for the IInstance
IConfiguration Configuration [get]
The IConfiguration for the IInstance
Private Member Functions
async Task PostDeploymentComments (CompileJob compileJob, RepositorySettings repositorySettings, string repoOwner, string repoName)
Post deployment GitHub comments.
async Task TimerLoop (uint minutes, CancellationToken cancellationToken)
Pull the repository and compile for every set of given minutes
Private Attributes
readonly IDreamMaker dreamMaker
The IDreamMaker for the Instance
readonly ICompileJobConsumer compileJobConsumer
The ICompileJobConsumer for the Instance
readonly IDatabaseContextFactory databaseContextFactory
The IDatabaseContextFactory for the Instance
readonly IDmbFactory dmbFactory
The IDmbFactory for the Instance
readonly IJobManager jobManager
The IJobManager for the Instance
readonly IEventConsumer eventConsumer
The IEventConsumer for the Instance
readonly IGitHubClientFactory gitHubClientFactory
The IGitHubClientFactory for the Instance
readonly ILogger< Instance > logger
The ILogger for the Instance
readonly Api.Models.Instance metadata
The Api.Models.Instance for the Instance
readonly object timerLock
lock object for timerCts and timerTask.
Task timerTask
The auto update Task
CancellationTokenSource timerCts
CancellationTokenSource for timerTask
Detailed Description
Definition at line 26 of file Instance.cs.
Constructor & Destructor Documentation
Instance()
Tgstation.Server.Host.Components.Instance.Instance (Api.Models.Instance metadata, IRepositoryManager repositoryManager, IByondManager byondManager, IDreamMaker dreamMaker, IWatchdog watchdog, IChatManager chat, StaticFiles.IConfiguration configuration, ICompileJobConsumer compileJobConsumer, IDatabaseContextFactory databaseContextFactory, IDmbFactory dmbFactory, IJobManager jobManager, IEventConsumer eventConsumer, IGitHubClientFactory gitHubClientFactory, ILogger< Instance > logger)
Construct an Instance
Parameters
metadata The value of metadata
repositoryManager The value of RepositoryManager
byondManager The value of ByondManager
dreamMaker The value of dreamMaker
watchdog The value of Watchdog
chat The value of Chat
configuration The value of Configuration
compileJobConsumer The value of compileJobConsumer
databaseContextFactory The value of databaseContextFactory
dmbFactory The value of dmbFactory
jobManager The value of jobManager
eventConsumer The value of eventConsumer
gitHubClientFactory The value of gitHubClientFactory
logger The value of logger
Definition at line 120 of file Instance.cs.
         {
             this.metadata = metadata ?? throw new ArgumentNullException(nameof(metadata));
             RepositoryManager = repositoryManager ?? throw new ArgumentNullException(nameof(repositoryManager));
             ByondManager = byondManager ?? throw new ArgumentNullException(nameof(byondManager));
             this.dreamMaker = dreamMaker ?? throw new ArgumentNullException(nameof(dreamMaker));
             Watchdog = watchdog ?? throw new ArgumentNullException(nameof(watchdog));
             Chat = chat ?? throw new ArgumentNullException(nameof(chat));
             Configuration = configuration ?? throw new ArgumentNullException(nameof(configuration));
             this.compileJobConsumer = compileJobConsumer ?? throw new ArgumentNullException(nameof(compileJobConsumer));
             this.databaseContextFactory = databaseContextFactory ?? throw new ArgumentNullException(nameof(databaseContextFactory));
             this.dmbFactory = dmbFactory ?? throw new ArgumentNullException(nameof(dmbFactory));
             this.jobManager = jobManager ?? throw new ArgumentNullException(nameof(jobManager));
             this.eventConsumer = eventConsumer ?? throw new ArgumentNullException(nameof(eventConsumer));
             this.gitHubClientFactory = gitHubClientFactory ?? throw new ArgumentNullException(nameof(gitHubClientFactory));
             this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
             timerLock = new object();
         }
References Tgstation.Server.Host.Components.Instance.Chat, Tgstation.Server.Host.Components.Instance.compileJobConsumer, Tgstation.Server.Host.Components.Instance.Configuration, Tgstation.Server.Host.Components.Instance.databaseContextFactory, Tgstation.Server.Host.Components.Instance.dmbFactory, Tgstation.Server.Host.Components.Instance.dreamMaker, Tgstation.Server.Host.Components.Instance.eventConsumer, Tgstation.Server.Host.Components.Instance.gitHubClientFactory, Tgstation.Server.Host.Components.Instance.jobManager, Tgstation.Server.Host.Components.Instance.logger, Tgstation.Server.Host.Components.Instance.metadata, Tgstation.Server.Host.Components.Instance.timerLock, and Tgstation.Server.Host.Components.Instance.Watchdog.
Referenced by Tgstation.Server.Host.Components.Instance.CompileProcess(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.StartAsync(), and Tgstation.Server.Host.Components.Instance.TimerLoop().
Member Function Documentation
CompileProcess()
async Task Tgstation.Server.Host.Components.Instance.CompileProcess (Job job, IDatabaseContext databaseContext, Action< int > progressReporter, CancellationToken cancellationToken)
Run the compile job and insert it into the database. Meant to be called by a Jobs.IJobManager
Implements Tgstation.Server.Host.Components.IInstance.
Definition at line 167 of file Instance.cs.
         {
 #pragma warning disable IDE0016 // Use 'throw' expression
             if (job == null)
                 throw new ArgumentNullException(nameof(job));
 #pragma warning restore IDE0016 // Use 'throw' expression
             if (databaseContext == null)
                 throw new ArgumentNullException(nameof(databaseContext));
             if (progressReporter == null)
                 throw new ArgumentNullException(nameof(progressReporter));
             var ddSettings = await databaseContext.DreamDaemonSettings.Where(x => x.InstanceId == metadata.Id).Select(x => new DreamDaemonSettings
             {
                 StartupTimeout = x.StartupTimeout,
             })
                 .FirstOrDefaultAsync(cancellationToken)
                 .ConfigureAwait(false);
             if (ddSettings == default)
                 throw new JobException(Api.Models.ErrorCode.InstanceMissingDreamDaemonSettings);
             var previousCompileJobs = await databaseContext.CompileJobs
                 .Where(x => x.Job.Instance.Id == metadata.Id)
                 .OrderByDescending(x => x.Job.StoppedAt)
                 .Select(x => new Job
                 {
                     StoppedAt = x.Job.StoppedAt,
                     StartedAt = x.Job.StartedAt
                 })
                 .Take(10)
                 .ToListAsync(cancellationToken)
                 .ConfigureAwait(false);
             var dreamMakerSettings = await databaseContext.DreamMakerSettings.Where(x => x.InstanceId == metadata.Id).FirstAsync(cancellationToken).ConfigureAwait(false);
             if (dreamMakerSettings == default)
                 throw new JobException(Api.Models.ErrorCode.InstanceMissingDreamMakerSettings);
             RepositorySettings repositorySettings = null;
             string repoOwner = null;
             string repoName = null;
             CompileJob compileJob;
             RevisionInformation revInfo;
             using (var repo = await RepositoryManager.LoadRepository(cancellationToken).ConfigureAwait(false))
             {
                 if (repo == null)
                     throw new JobException(Api.Models.ErrorCode.RepoMissing);
                 if (repo.IsGitHubRepository)
                 {
                     repoOwner = repo.GitHubOwner;
                     repoName = repo.GitHubRepoName;
                     repositorySettings = await databaseContext
                         .RepositorySettings
                         .Where(x => x.InstanceId == metadata.Id)
                         .Select(x => new RepositorySettings
{
                             AccessToken = x.AccessToken,
                             ShowTestMergeCommitters = x.ShowTestMergeCommitters,
                             PushTestMergeCommits = x.PushTestMergeCommits,
                             PostTestMergeComment = x.PostTestMergeComment
                         })
                         .FirstOrDefaultAsync(cancellationToken)
                         .ConfigureAwait(false);
                     if (repositorySettings == default)
                         throw new JobException(Api.Models.ErrorCode.InstanceMissingRepositorySettings);
                 }
                 var repoSha = repo.Head;
                 revInfo = await databaseContext.RevisionInformations.Where(x => x.CommitSha == repoSha && x.Instance.Id == metadata.Id).Include(x => x.ActiveTestMerges).ThenInclude(x => x.TestMerge).ThenInclude(x => x.MergedBy).FirstOrDefaultAsync().ConfigureAwait(false);
                 if (revInfo == default)
                 {
                     revInfo = new RevisionInformation
                     {
                         CommitSha = repoSha,
                         OriginCommitSha = repoSha,
                         Instance = new Models.Instance
{
                             Id = metadata.Id
                         }
                     };
                     logger.LogWarning(Repository.Repository.OriginTrackingErrorTemplate, repoSha);
                     databaseContext.Instances.Attach(revInfo.Instance);
                 }
                 TimeSpan? averageSpan = null;
                 if (previousCompileJobs.Count != 0)
                 {
                     var totalSpan = TimeSpan.Zero;
                     foreach (var I in previousCompileJobs)
                         totalSpan += I.StoppedAt.Value - I.StartedAt.Value;
                     averageSpan = totalSpan / previousCompileJobs.Count;
                 }
                 compileJob = await dreamMaker.Compile(revInfo, dreamMakerSettings, ddSettings.StartupTimeout.Value, repo, progressReporter, averageSpan, cancellationToken).ConfigureAwait(false);
             }
             compileJob.Job = job;
             databaseContext.CompileJobs.Add(compileJob);
             await PostDeploymentComments(compileJob, repositorySettings, repoOwner, repoName).ConfigureAwait(false);
             // The difficulty with compile jobs is they have a two part commit
             await databaseContext.Save(cancellationToken).ConfigureAwait(false);
             try
             {
                 await compileJobConsumer.LoadCompileJob(compileJob, cancellationToken).ConfigureAwait(false);
             }
             catch
             {
                 // So we need to un-commit the compile job if the above throws
                 databaseContext.CompileJobs.Remove(compileJob);
                 await databaseContext.Save(default).ConfigureAwait(false);
                 throw;
             }
             await eventConsumer.HandleEvent(EventType.DeploymentComplete, null, cancellationToken).ConfigureAwait(false);
         }
References Tgstation.Server.Api.Models.Internal.RepositorySettings.AccessToken, Tgstation.Server.Host.Database.IDatabaseCollection< TModel >.Add(), Tgstation.Server.Host.Database.IDatabaseCollection< TModel >.Attach(), Tgstation.Server.Host.Components.Deployment.IDreamMaker.Compile(), Tgstation.Server.Host.Components.Instance.compileJobConsumer, Tgstation.Server.Host.Database.IDatabaseContext.CompileJobs, Tgstation.Server.Host.Database.IDatabaseContext.DreamDaemonSettings, Tgstation.Server.Host.Components.Instance.dreamMaker, Tgstation.Server.Host.Database.IDatabaseContext.DreamMakerSettings, Tgstation.Server.Host.Components.Instance.eventConsumer, Tgstation.Server.Host.Components.IEventConsumer.HandleEvent(), Tgstation.Server.Host.Models.RevisionInformation.Instance, Tgstation.Server.Host.Components.Instance.Instance(), Tgstation.Server.Host.Database.IDatabaseContext.Instances, Tgstation.Server.Host.Models.CompileJob.Job, Tgstation.Server.Host.Components.Deployment.ICompileJobConsumer.LoadCompileJob(), Tgstation.Server.Host.Components.Repository.RepositoryManager.LoadRepository(), Tgstation.Server.Host.Components.Instance.logger, Tgstation.Server.Host.Components.Instance.metadata, Tgstation.Server.Host.Components.Instance.PostDeploymentComments(), Tgstation.Server.Host.Database.IDatabaseCollection< TModel >.Remove(), Tgstation.Server.Host.Components.Repository.Repository.Repository(), Tgstation.Server.Host.Database.IDatabaseContext.RepositorySettings, Tgstation.Server.Host.Database.IDatabaseContext.RevisionInformations, Tgstation.Server.Host.Database.IDatabaseContext.Save(), Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.StartupTimeout, Tgstation.Server.Api.Models.Internal.Job.StoppedAt, and Tgstation.Server.Host.Database.IDatabaseCollection< TModel >.ToListAsync().
Referenced by Tgstation.Server.Host.Components.Instance.TimerLoop().
Dispose()
void Tgstation.Server.Host.Components.Instance.Dispose ()
Definition at line 156 of file Instance.cs.
         {
             timerCts?.Dispose();
             compileJobConsumer.Dispose();
             Configuration.Dispose();
             Chat.Dispose();
             Watchdog.Dispose();
             RepositoryManager.Dispose();
         }
References Tgstation.Server.Host.Components.Instance.Chat, Tgstation.Server.Host.Components.Instance.compileJobConsumer, Tgstation.Server.Host.Components.Instance.Configuration, Tgstation.Server.Host.Components.Repository.RepositoryManager.Dispose(), Tgstation.Server.Host.Components.Instance.timerCts, and Tgstation.Server.Host.Components.Instance.Watchdog.
LatestCompileJob()
CompileJob Tgstation.Server.Host.Components.Instance.LatestCompileJob ()
The latest staged CompileJob
Implements Tgstation.Server.Host.Components.IInstance.
Definition at line 677 of file Instance.cs.
         {
             if (!dmbFactory.DmbAvailable)
                 return null;
             return dmbFactory.LockNextDmb(0)?.CompileJob;
         }
References Tgstation.Server.Host.Components.Deployment.IDmbProvider.CompileJob, Tgstation.Server.Host.Components.Deployment.IDmbFactory.DmbAvailable, Tgstation.Server.Host.Components.Instance.dmbFactory, and Tgstation.Server.Host.Components.Deployment.IDmbFactory.LockNextDmb().
Referenced by Tgstation.Server.Host.Components.Instance.PostDeploymentComments(), and Tgstation.Server.Host.Components.Instance.TimerLoop().
PostDeploymentComments()
async Task Tgstation.Server.Host.Components.Instance.PostDeploymentComments (CompileJob compileJob, RepositorySettings repositorySettings, string repoOwner, string repoName) private
Post deployment GitHub comments.
Parameters
compileJob The deployed CompileJob.
repositorySettings The RepositorySettings.
repoOwner The GitHub repostiory owner.
repoName The GitHub repostiory name.
Returns
A Task representing the running operation.
Definition at line 294 of file Instance.cs.
         {
             if (repositorySettings?.AccessToken == null)
                 return;
             // potential for commenting on a test merge change
             var outgoingCompileJob = LatestCompileJob();
             if ((outgoingCompileJob != null && outgoingCompileJob.RevisionInformation.CommitSha == compileJob.RevisionInformation.CommitSha) || !repositorySettings.PostTestMergeComment.Value)
                 return;
             outgoingCompileJob ??= new CompileJob
             {
                 RevisionInformation = new RevisionInformation
                 {
                     ActiveTestMerges = new List<RevInfoTestMerge>()
                 }
             };
             var gitHubClient = gitHubClientFactory.CreateClient(repositorySettings.AccessToken);
             async Task CommentOnPR(int prNumber, string comment)
             {
                 try
                 {
                     await gitHubClient.Issue.Comment.Create(repoOwner, repoName, prNumber, comment).ConfigureAwait(false);
                 }
                 catch (ApiException e)
                 {
                     logger.LogWarning("Error posting GitHub comment! Exception: {0}", e);
                 }
             }
             var tasks = new List<Task>();
             string FormatTestMerge(TestMerge testMerge, bool updated) => String.Format(CultureInfo.InvariantCulture, "#### Test Merge {4}{0}{0}##### Server Instance{0}{5}{1}{0}{0}##### Revision{0}Origin: {6}{0}Pull Request: {2}{0}Server: {7}{3}",
                 Environment.NewLine,
                 repositorySettings.ShowTestMergeCommitters.Value ? String.Format(CultureInfo.InvariantCulture, "{0}{0}##### Merged By{0}{1}", Environment.NewLine, testMerge.MergedBy.Name) : String.Empty,
                 testMerge.PullRequestRevision,
                 testMerge.Comment != null ? String.Format(CultureInfo.InvariantCulture, "{0}{0}##### Comment{0}{1}", Environment.NewLine, testMerge.Comment) : String.Empty,
                 updated ? "Updated" : "Deployed",
                 metadata.Name,
                 compileJob.RevisionInformation.OriginCommitSha,
                 compileJob.RevisionInformation.CommitSha);
             // added prs
             foreach (var I in compileJob
                 .RevisionInformation
                 .ActiveTestMerges
                 .Select(x => x.TestMerge)
                 .Where(x => !outgoingCompileJob
                     .RevisionInformation
                     .ActiveTestMerges
                     .Any(y => y.TestMerge.Number == x.Number)))
                 tasks.Add(CommentOnPR(I.Number, FormatTestMerge(I, false)));
             // removed prs
             foreach (var I in outgoingCompileJob
                 .RevisionInformation
                 .ActiveTestMerges
                 .Select(x => x.TestMerge)
                     .Where(x => !compileJob
                     .RevisionInformation
                     .ActiveTestMerges
                     .Any(y => y.TestMerge.Number == x.Number)))
                 tasks.Add(CommentOnPR(I.Number, "#### Test Merge Removed"));
             // updated prs
             foreach (var I in compileJob
                 .RevisionInformation
                 .ActiveTestMerges
                 .Select(x => x.TestMerge)
                 .Where(x => outgoingCompileJob
                     .RevisionInformation
                     .ActiveTestMerges
                     .Any(y => y.TestMerge.Number == x.Number)))
                 tasks.Add(CommentOnPR(I.Number, FormatTestMerge(I, true)));
             if (tasks.Any())
                 await Task.WhenAll(tasks).ConfigureAwait(false);
         }
References Tgstation.Server.Api.Models.Internal.RepositorySettings.AccessToken, Tgstation.Server.Api.Models.TestMergeParameters.Comment, Tgstation.Server.Api.Models.Internal.RevisionInformation.CommitSha, Tgstation.Server.Host.Core.IGitHubClientFactory.CreateClient(), Tgstation.Server.Host.Components.Instance.gitHubClientFactory, Tgstation.Server.Host.Components.Instance.LatestCompileJob(), Tgstation.Server.Host.Components.Instance.logger, Tgstation.Server.Host.Models.TestMerge.MergedBy, Tgstation.Server.Host.Components.Instance.metadata, Tgstation.Server.Api.Models.Internal.User.Name, Tgstation.Server.Api.Models.Internal.RevisionInformation.OriginCommitSha, Tgstation.Server.Api.Models.Internal.RepositorySettings.PostTestMergeComment, Tgstation.Server.Api.Models.TestMergeParameters.PullRequestRevision, Tgstation.Server.Host.Models.CompileJob.RevisionInformation, and Tgstation.Server.Api.Models.Internal.RepositorySettings.ShowTestMergeCommitters.
Referenced by Tgstation.Server.Host.Components.Instance.CompileProcess().
Rename()
void Tgstation.Server.Host.Components.Instance.Rename (string newName)
Rename the IInstance
Implements Tgstation.Server.Host.Components.IInstance.
Definition at line 611 of file Instance.cs.
         {
             if (String.IsNullOrWhiteSpace(newName))
                 throw new ArgumentNullException(nameof(newName));
             metadata.Name = newName;
         }
References Tgstation.Server.Host.Components.Instance.metadata.
SetAutoUpdateInterval()
async Task Tgstation.Server.Host.Components.Instance.SetAutoUpdateInterval (uint newInterval)
Change the Api.Models.Instance.AutoUpdateInterval for the IInstance
Implements Tgstation.Server.Host.Components.IInstance.
Definition at line 648 of file Instance.cs.
         {
             Task toWait;
             lock (timerLock)
             {
                 if (timerTask != null)
                 {
                     timerCts.Cancel();
                     toWait = timerTask;
                 }
                 else
                     toWait = Task.CompletedTask;
             }
             await toWait.ConfigureAwait(false);
             if (newInterval == 0)
                 return;
             lock (timerLock)
             {
                 // race condition, just quit
                 if (timerTask != null)
                     return;
                 timerCts?.Dispose();
                 timerCts = new CancellationTokenSource();
                 timerTask = TimerLoop(newInterval, timerCts.Token);
             }
         }
References Tgstation.Server.Host.Components.Instance.timerCts, Tgstation.Server.Host.Components.Instance.timerLock, Tgstation.Server.Host.Components.Instance.TimerLoop(), and Tgstation.Server.Host.Components.Instance.timerTask.
Referenced by Tgstation.Server.Host.Components.Instance.StartAsync(), and Tgstation.Server.Host.Components.Instance.StopAsync().
StartAsync()
async Task Tgstation.Server.Host.Components.Instance.StartAsync (CancellationToken cancellationToken)
Definition at line 619 of file Instance.cs.
         {
             await Task.WhenAll(SetAutoUpdateInterval(metadata.AutoUpdateInterval.Value), Configuration.StartAsync(cancellationToken), ByondManager.StartAsync(cancellationToken), Chat.StartAsync(cancellationToken), compileJobConsumer.StartAsync(cancellationToken)).ConfigureAwait(false);
             // dependent on so many things, its just safer this way
             await Watchdog.StartAsync(cancellationToken).ConfigureAwait(false);
             CompileJob latestCompileJob = null;
             await databaseContextFactory.UseContext(async db =>
             {
                 latestCompileJob = await db.MostRecentCompletedCompileJobOrDefault(metadata, cancellationToken).ConfigureAwait(false);
             }).ConfigureAwait(false);
             await dmbFactory.CleanUnusedCompileJobs(latestCompileJob, cancellationToken).ConfigureAwait(false);
         }
References Tgstation.Server.Host.Components.Instance.Chat, Tgstation.Server.Host.Components.Deployment.IDmbFactory.CleanUnusedCompileJobs(), Tgstation.Server.Host.Components.Instance.compileJobConsumer, Tgstation.Server.Host.Components.Instance.Configuration, Tgstation.Server.Host.Components.Instance.databaseContextFactory, Tgstation.Server.Host.Components.Instance.dmbFactory, Tgstation.Server.Host.Components.Instance.metadata, Tgstation.Server.Host.Components.Instance.SetAutoUpdateInterval(), Tgstation.Server.Host.Components.Byond.ByondManager.StartAsync(), Tgstation.Server.Host.Database.IDatabaseContextFactory.UseContext(), and Tgstation.Server.Host.Components.Instance.Watchdog.
StopAsync()
async Task Tgstation.Server.Host.Components.Instance.StopAsync (CancellationToken cancellationToken)
Definition at line 635 of file Instance.cs.
         {
             await SetAutoUpdateInterval(0).ConfigureAwait(false);
             await Watchdog.StopAsync(cancellationToken).ConfigureAwait(false);
             await Task.WhenAll(
                 Configuration.StopAsync(cancellationToken),
                 ByondManager.StopAsync(cancellationToken),
                 Chat.StopAsync(cancellationToken),
                 compileJobConsumer.StopAsync(cancellationToken))
                 .ConfigureAwait(false);
         }
References Tgstation.Server.Host.Components.Instance.Chat, Tgstation.Server.Host.Components.Instance.compileJobConsumer, Tgstation.Server.Host.Components.Instance.Configuration, Tgstation.Server.Host.Components.Instance.SetAutoUpdateInterval(), Tgstation.Server.Host.Components.Byond.ByondManager.StopAsync(), and Tgstation.Server.Host.Components.Instance.Watchdog.
TimerLoop()
async Task Tgstation.Server.Host.Components.Instance.TimerLoop (uint minutes, CancellationToken cancellationToken) private
Pull the repository and compile for every set of given minutes
Parameters
minutes How many minutes the operation should repeat. Does not include running time
cancellationToken The CancellationToken for the operation
Returns
A Task representing the running operation
Definition at line 387 of file Instance.cs.
         {
             while (true)
                 try
                 {
                     await Task.Delay(TimeSpan.FromMinutes(minutes > Int32.MaxValue ? Int32.MaxValue : (int)minutes), cancellationToken).ConfigureAwait(false);
                     logger.LogInformation("Beginning auto update...");
                     await eventConsumer.HandleEvent(EventType.InstanceAutoUpdateStart, new List<string>(), cancellationToken).ConfigureAwait(false);
                     try
                     {
                         Models.User user = null;
                         await databaseContextFactory.UseContext(
                             async (db) => user = await db
                                 .Users
                                 .Where(x => x.CanonicalName == Models.User.CanonicalizeName(Api.Models.User.AdminName))
                                 .FirstAsync(cancellationToken)
                                 .ConfigureAwait(false))
                             .ConfigureAwait(false);
                         var repositoryUpdateJob = new Job
{
                             Instance = new Models.Instance
{
                                 Id = metadata.Id
                             },
                             Description = "Scheduled repository update",
                             CancelRightsType = RightsType.Repository,
                             CancelRight = (ulong)RepositoryRights.CancelPendingChanges,
                             StartedBy = user
                         };
                         string deploySha = null;
                         await jobManager.RegisterOperation(repositoryUpdateJob, async (paramJob, databaseContext, progressReporter, jobCancellationToken) =>
{
                             var repositorySettingsTask = databaseContext.RepositorySettings.Where(x => x.InstanceId == metadata.Id).FirstAsync(jobCancellationToken);
                             // assume 5 steps with synchronize
                             const int ProgressSections = 7;
                             const int ProgressStep = 100 / ProgressSections;
                             const int NumSteps = 3;
                             var doneSteps = 0;
                             Action<int> NextProgressReporter()
{
                                 var tmpDoneSteps = doneSteps;
                                 ++doneSteps;
                                 return progress => progressReporter((progress + (100 * tmpDoneSteps)) / NumSteps);
                             }
                             using var repo = await RepositoryManager.LoadRepository(jobCancellationToken).ConfigureAwait(false);
                             if (repo == null)
{
                                 logger.LogTrace("Aborting repo update, no repository!");
                                 return;
                             }
                             var startSha = repo.Head;
                             if (!repo.Tracking)
{
                                 logger.LogTrace("Aborting repo update, active ref not tracking any remote branch!");
                                 deploySha = startSha;
                                 return;
                             }
                             var repositorySettings = await repositorySettingsTask.ConfigureAwait(false);
                             // the main point of auto update is to pull the remote
                             await repo.FetchOrigin(repositorySettings.AccessUser, repositorySettings.AccessToken, NextProgressReporter(), jobCancellationToken).ConfigureAwait(false);
                             RevisionInformation currentRevInfo = null;
                             bool hasDbChanges = false;
                             Task<RevisionInformation> LoadRevInfo() => databaseContext.RevisionInformations
                                     .Where(x => x.CommitSha == startSha && x.Instance.Id == metadata.Id)
                                     .Include(x => x.ActiveTestMerges).ThenInclude(x => x.TestMerge)
                                     .FirstOrDefaultAsync(cancellationToken);
                             async Task UpdateRevInfo(string currentHead, bool onOrigin)
{
                                 if (currentRevInfo == null)
                                     currentRevInfo = await LoadRevInfo().ConfigureAwait(false);
                                 if (currentRevInfo == default)
{
                                     logger.LogWarning(Repository.Repository.OriginTrackingErrorTemplate, currentHead);
                                     onOrigin = true;
                                 }
                                 var attachedInstance = new Models.Instance
{
                                     Id = metadata.Id
                                 };
                                 var oldRevInfo = currentRevInfo;
                                 currentRevInfo = new RevisionInformation
{
                                     CommitSha = currentHead,
                                     OriginCommitSha = onOrigin ? currentHead : oldRevInfo.OriginCommitSha,
                                     Instance = attachedInstance
                                 };
                                 if (!onOrigin)
                                     currentRevInfo.ActiveTestMerges = new List<RevInfoTestMerge>(oldRevInfo.ActiveTestMerges);
                                 databaseContext.Instances.Attach(attachedInstance);
                                 databaseContext.RevisionInformations.Add(currentRevInfo);
                                 hasDbChanges = true;
                             }
                             // take appropriate auto update actions
                             bool shouldSyncTracked;
                             if (repositorySettings.AutoUpdatesKeepTestMerges.Value)
{
                                 logger.LogTrace("Preserving test merges...");
                                 var currentRevInfoTask = LoadRevInfo();
                                 var result = await repo.MergeOrigin(repositorySettings.CommitterName, repositorySettings.CommitterEmail, NextProgressReporter(), jobCancellationToken).ConfigureAwait(false);
                                 if (!result.HasValue)
                                     throw new JobException(Api.Models.ErrorCode.InstanceUpdateTestMergeConflict);
                                 currentRevInfo = await currentRevInfoTask.ConfigureAwait(false);
                                 var lastRevInfoWasOriginCommit = currentRevInfo == default || currentRevInfo.CommitSha == currentRevInfo.OriginCommitSha;
                                 var stillOnOrigin = result.Value && lastRevInfoWasOriginCommit;
                                 var currentHead = repo.Head;
                                 if (currentHead != startSha)
{
                                     await UpdateRevInfo(currentHead, stillOnOrigin).ConfigureAwait(false);
                                     shouldSyncTracked = stillOnOrigin;
                                 }
                                 else
                                     shouldSyncTracked = false;
                             }
                             else
{
                                 logger.LogTrace("Not preserving test merges...");
                                 await repo.ResetToOrigin(NextProgressReporter(), jobCancellationToken).ConfigureAwait(false);
                                 var currentHead = repo.Head;
                                 currentRevInfo = await databaseContext.RevisionInformations
                                 .Where(x => x.CommitSha == currentHead && x.Instance.Id == metadata.Id)
                                 .FirstOrDefaultAsync(jobCancellationToken).ConfigureAwait(false);
                                 if (currentHead != startSha && currentRevInfo != default)
                                     await UpdateRevInfo(currentHead, true).ConfigureAwait(false);
                                 shouldSyncTracked = true;
                             }
                             // synch if necessary
                             if (repositorySettings.AutoUpdatesSynchronize.Value && startSha != repo.Head)
{
                                 var pushedOrigin = await repo.Sychronize(repositorySettings.AccessUser, repositorySettings.AccessToken, repositorySettings.CommitterName, repositorySettings.CommitterEmail, NextProgressReporter(), shouldSyncTracked, jobCancellationToken).ConfigureAwait(false);
                                 var currentHead = repo.Head;
                                 if (currentHead != currentRevInfo.CommitSha)
                                     await UpdateRevInfo(currentHead, pushedOrigin).ConfigureAwait(false);
                             }
                             if (hasDbChanges)
                                 try
{
                                     await databaseContext.Save(cancellationToken).ConfigureAwait(false);
                                 }
                                 catch
{
                                     await repo.ResetToSha(startSha, progressReporter, default).ConfigureAwait(false);
                                     throw;
                                 }
                             progressReporter(5 * ProgressStep);
                             deploySha = repo.Head;
                         }, cancellationToken).ConfigureAwait(false);
                         await jobManager.WaitForJobCompletion(repositoryUpdateJob, user, cancellationToken, default).ConfigureAwait(false);
                         if (deploySha == null)
{
                             logger.LogTrace("Aborting auto update, repository error!");
                             continue;
                         }
                         if(deploySha == LatestCompileJob()?.RevisionInformation.CommitSha)
{
                             logger.LogTrace("Aborting auto update, same revision as latest CompileJob");
                             continue;
                         }
                         // finally set up the job
                         var compileProcessJob = new Job
{
                             StartedBy = user,
                             Instance = repositoryUpdateJob.Instance,
                             Description = "Scheduled code deployment",
                             CancelRightsType = RightsType.DreamMaker,
                             CancelRight = (ulong)DreamMakerRights.CancelCompile
                         };
                         await jobManager.RegisterOperation(compileProcessJob, CompileProcess, cancellationToken).ConfigureAwait(false);
                         await jobManager.WaitForJobCompletion(compileProcessJob, user, cancellationToken, default).ConfigureAwait(false);
                     }
                     catch (OperationCanceledException)
                     {
                         logger.LogDebug("Cancelled auto update job!");
                         throw;
                     }
                     catch (Exception e)
                     {
                         logger.LogWarning("Error in auto update loop! Exception: {0}", e);
                         continue;
                     }
                 }
                 catch (OperationCanceledException)
                 {
                     break;
                 }
             logger.LogTrace("Leaving auto update loop...");
         }
References Tgstation.Server.Host.Models.RevisionInformation.ActiveTestMerges, Tgstation.Server.Api.Models.Internal.RevisionInformation.CommitSha, Tgstation.Server.Host.Components.Instance.CompileProcess(), Tgstation.Server.Host.Components.Instance.databaseContextFactory, Tgstation.Server.Host.Components.Instance.eventConsumer, Tgstation.Server.Host.Components.IEventConsumer.HandleEvent(), Tgstation.Server.Host.Components.Instance.Instance(), Tgstation.Server.Host.Components.Instance.jobManager, Tgstation.Server.Host.Components.Instance.LatestCompileJob(), Tgstation.Server.Host.Components.Repository.RepositoryManager.LoadRepository(), Tgstation.Server.Host.Components.Instance.logger, Tgstation.Server.Host.Components.Instance.metadata, Tgstation.Server.Api.Models.Internal.RevisionInformation.OriginCommitSha, Tgstation.Server.Host.Jobs.IJobManager.RegisterOperation(), Tgstation.Server.Host.Components.Repository.Repository.Repository(), Tgstation.Server.Host.Models.CompileJob.RevisionInformation, Tgstation.Server.Host.Database.IDatabaseContextFactory.UseContext(), and Tgstation.Server.Host.Jobs.IJobManager.WaitForJobCompletion().
Referenced by Tgstation.Server.Host.Components.Instance.SetAutoUpdateInterval().
Member Data Documentation
compileJobConsumer
readonly ICompileJobConsumer Tgstation.Server.Host.Components.Instance.compileJobConsumer private
The ICompileJobConsumer for the Instance
Definition at line 51 of file Instance.cs.
Referenced by Tgstation.Server.Host.Components.Instance.CompileProcess(), Tgstation.Server.Host.Components.Instance.Dispose(), Tgstation.Server.Host.Components.Instance.Instance(), Tgstation.Server.Host.Components.Instance.StartAsync(), and Tgstation.Server.Host.Components.Instance.StopAsync().
databaseContextFactory
readonly IDatabaseContextFactory Tgstation.Server.Host.Components.Instance.databaseContextFactory private
The IDatabaseContextFactory for the Instance
Definition at line 56 of file Instance.cs.
Referenced by Tgstation.Server.Host.Components.Instance.Instance(), Tgstation.Server.Host.Components.Instance.StartAsync(), and Tgstation.Server.Host.Components.Instance.TimerLoop().
dmbFactory
readonly IDmbFactory Tgstation.Server.Host.Components.Instance.dmbFactory private
The IDmbFactory for the Instance
Definition at line 61 of file Instance.cs.
Referenced by Tgstation.Server.Host.Components.Instance.Instance(), Tgstation.Server.Host.Components.Instance.LatestCompileJob(), and Tgstation.Server.Host.Components.Instance.StartAsync().
dreamMaker
readonly IDreamMaker Tgstation.Server.Host.Components.Instance.dreamMaker private
The IDreamMaker for the Instance
Definition at line 46 of file Instance.cs.
Referenced by Tgstation.Server.Host.Components.Instance.CompileProcess(), and Tgstation.Server.Host.Components.Instance.Instance().
eventConsumer
readonly IEventConsumer Tgstation.Server.Host.Components.Instance.eventConsumer private
The IEventConsumer for the Instance
Definition at line 71 of file Instance.cs.
Referenced by Tgstation.Server.Host.Components.Instance.CompileProcess(), Tgstation.Server.Host.Components.Instance.Instance(), and Tgstation.Server.Host.Components.Instance.TimerLoop().
gitHubClientFactory
readonly IGitHubClientFactory Tgstation.Server.Host.Components.Instance.gitHubClientFactory private
The IGitHubClientFactory for the Instance
Definition at line 76 of file Instance.cs.
Referenced by Tgstation.Server.Host.Components.Instance.Instance(), and Tgstation.Server.Host.Components.Instance.PostDeploymentComments().
jobManager
readonly IJobManager Tgstation.Server.Host.Components.Instance.jobManager private
The IJobManager for the Instance
Definition at line 66 of file Instance.cs.
Referenced by Tgstation.Server.Host.Components.Instance.Instance(), and Tgstation.Server.Host.Components.Instance.TimerLoop().
logger
readonly ILogger<Instance> Tgstation.Server.Host.Components.Instance.logger private
The ILogger for the Instance
Definition at line 81 of file Instance.cs.
Referenced by Tgstation.Server.Host.Components.Instance.CompileProcess(), Tgstation.Server.Host.Components.Instance.Instance(), Tgstation.Server.Host.Components.Instance.PostDeploymentComments(), and Tgstation.Server.Host.Components.Instance.TimerLoop().
metadata
readonly Api.Models.Instance Tgstation.Server.Host.Components.Instance.metadata private
The Api.Models.Instance for the Instance
Definition at line 86 of file Instance.cs.
Referenced by Tgstation.Server.Host.Components.Instance.CompileProcess(), Tgstation.Server.Host.Components.Instance.Instance(), Tgstation.Server.Host.Components.Instance.PostDeploymentComments(), Tgstation.Server.Host.Components.Instance.Rename(), Tgstation.Server.Host.Components.Instance.StartAsync(), and Tgstation.Server.Host.Components.Instance.TimerLoop().
timerCts
CancellationTokenSource Tgstation.Server.Host.Components.Instance.timerCts private
CancellationTokenSource for timerTask
Definition at line 101 of file Instance.cs.
Referenced by Tgstation.Server.Host.Components.Instance.Dispose(), and Tgstation.Server.Host.Components.Instance.SetAutoUpdateInterval().
timerLock
readonly object Tgstation.Server.Host.Components.Instance.timerLock private
lock object for timerCts and timerTask.
Definition at line 91 of file Instance.cs.
Referenced by Tgstation.Server.Host.Components.Instance.Instance(), and Tgstation.Server.Host.Components.Instance.SetAutoUpdateInterval().
timerTask
Task Tgstation.Server.Host.Components.Instance.timerTask private
The auto update Task
Definition at line 96 of file Instance.cs.
Referenced by Tgstation.Server.Host.Components.Instance.SetAutoUpdateInterval().
Property Documentation
ByondManager
IByondManager Tgstation.Server.Host.Components.Instance.ByondManager get
Definition at line 32 of file Instance.cs.
 { get; }
Chat
IChatManager Tgstation.Server.Host.Components.Instance.Chat get
Definition at line 38 of file Instance.cs.
 { get; }
Referenced by Tgstation.Server.Host.Components.Instance.Dispose(), Tgstation.Server.Host.Components.Instance.Instance(), Tgstation.Server.Host.Components.Instance.StartAsync(), and Tgstation.Server.Host.Components.Instance.StopAsync().
Configuration
StaticFiles.IConfiguration Tgstation.Server.Host.Components.Instance.Configuration get
Definition at line 41 of file Instance.cs.
 { get; }
Referenced by Tgstation.Server.Host.Components.Instance.Dispose(), Tgstation.Server.Host.Components.Instance.Instance(), Tgstation.Server.Host.Components.Instance.StartAsync(), and Tgstation.Server.Host.Components.Instance.StopAsync().
RepositoryManager
IRepositoryManager Tgstation.Server.Host.Components.Instance.RepositoryManager get
Definition at line 29 of file Instance.cs.
 { get; }
Watchdog
IWatchdog Tgstation.Server.Host.Components.Instance.Watchdog get
Definition at line 35 of file Instance.cs.
 { get; }
Referenced by Tgstation.Server.Host.Components.Instance.Dispose(), Tgstation.Server.Host.Components.Instance.Instance(), Tgstation.Server.Host.Components.Instance.StartAsync(), and Tgstation.Server.Host.Components.Instance.StopAsync().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Instance.cs