tgstation-server: Tgstation.Server.Host.Components.Engine.ByondInstallation Class Reference
Tgstation.Server.Host.Components.Engine.ByondInstallation Class Reference sealed
Implementation of IEngineInstallation for EngineType.Byond.
Public Member Functions
ByondInstallation (IIOManager installationIOManager, Task installationTask, EngineVersion version, string dreamDaemonPath, string dreamMakerPath, bool supportsCli, bool supportsMapThreads)
Initializes a new instance of the ByondInstallation class.
override string FormatServerArguments (IDmbProvider dmbProvider, IReadOnlyDictionary< string, string > parameters, DreamDaemonLaunchParameters launchParameters, string? logFilePath)
Return the command line arguments for launching with given launchParameters .
Parameters
dmbProvider The IDmbProvider.
parameters The map of parameter strings as a IReadOnlyDictionary<TKey, TValue>. MUST include Interop.DMApiConstants.ParamAccessIdentifier. Should NOT include the DreamDaemonLaunchParameters.AdditionalParameters of launchParameters .
launchParameters The DreamDaemonLaunchParameters.
logFilePath The full path to the log file, if any.
Returns
The formatted arguments string.
override string FormatCompilerArguments (string dmePath, string? additionalArguments)
Return the command line arguments for compiling a given dmePath if compilation is necessary.
Parameters
dmePath The full path to the .dme to compile.
additionalArguments Optional additional arguments provided to the compiler.
Returns
The formatted arguments string.
Public Member Functions inherited from Tgstation.Server.Host.Components.Engine.EngineInstallationBase
EngineInstallationBase (IIOManager installationIOManager)
Initializes a new instance of the EngineInstallationBase class.
string FormatCompilerArguments (string dmePath, string? additionalArguments)
Return the command line arguments for compiling a given dmePath if compilation is necessary.
Parameters
dmePath The full path to the .dme to compile.
additionalArguments Optional additional arguments provided to the compiler.
Returns
The formatted arguments string.
string FormatServerArguments (IDmbProvider dmbProvider, IReadOnlyDictionary< string, string > parameters, DreamDaemonLaunchParameters launchParameters, string? logFilePath)
Return the command line arguments for launching with given launchParameters .
Parameters
dmbProvider The IDmbProvider.
parameters The map of parameter strings as a IReadOnlyDictionary<TKey, TValue>. MUST include Interop.DMApiConstants.ParamAccessIdentifier. Should NOT include the DreamDaemonLaunchParameters.AdditionalParameters of launchParameters .
launchParameters The DreamDaemonLaunchParameters.
logFilePath The full path to the log file, if any.
Returns
The formatted arguments string.
virtual async ValueTask StopServerProcess (ILogger logger, IProcess process, string accessIdentifier, ushort port, CancellationToken cancellationToken)
Kills a given engine server process .
Parameters
logger The ILogger to write to.
process The IProcess to be terminated.
accessIdentifier The Interop.DMApiParameters.AccessIdentifier of the session.
port The port the server is running on.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
async ValueTask< Dictionary< string, string >?> LoadEnv (ILogger logger, bool forCompiler, CancellationToken cancellationToken)
Loads the environment settings for either the server or compiler.
Parameters
logger The ILogger to write to.
forCompiler If false server.env will be loaded. If true compiler.env will be loaded.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the environment Dictionary<TKey, TValue> or null if the target environment file doesn't exist.
Properties
override EngineVersion Version [get]
The EngineVersion of the IEngineInstallation.
override string ServerExePath [get]
The full path to the game server executable.
override string CompilerExePath [get]
The full path to the dm/DreamMaker executable.
override bool PromptsForNetworkAccess [get]
If ServerExePath may create network prompts.
override bool HasStandardOutput [get]
If ServerExePath supports being run as a command-line application and outputs log information to be captured.
override bool PreferFileLogging [get]
If HasStandardOutput is set, this indicates that the engine server has good file logging that should be preferred to ours.
override bool UseDotnetDump [get]
If dotnet-dump should be used to create process dumps for this installation.
override Task InstallationTask [get]
The Task that completes when the BYOND version finished installing.
Properties inherited from Tgstation.Server.Host.Components.Engine.EngineInstallationBase
EngineVersion Version [get]
The EngineVersion of the IEngineInstallation.
string ServerExePath [get]
The full path to the game server executable.
string CompilerExePath [get]
The full path to the dm/DreamMaker executable.
bool HasStandardOutput [get]
If ServerExePath supports being run as a command-line application and outputs log information to be captured.
bool PreferFileLogging [get]
If HasStandardOutput is set, this indicates that the engine server has good file logging that should be preferred to ours.
bool PromptsForNetworkAccess [get]
If ServerExePath may create network prompts.
bool UseDotnetDump [get]
If dotnet-dump should be used to create process dumps for this installation.
Task InstallationTask [get]
The Task that completes when the BYOND version finished installing.
IIOManager InstallationIOManager [get]
The IIOManager pointing to the installation directory.
Properties inherited from Tgstation.Server.Host.Components.Engine.IEngineInstallation
Static Private Member Functions
static string SecurityWord (DreamDaemonSecurity securityLevel)
Change a given securityLevel into the appropriate DreamDaemon command line word.
static string VisibilityWord (DreamDaemonVisibility visibility)
Change a given visibility into the appropriate DreamDaemon command line word.
Private Attributes
readonly bool supportsMapThreads
If map threads are supported by the Version.
Additional Inherited Members
Static Protected Member Functions inherited from Tgstation.Server.Host.Components.Engine.EngineInstallationBase
static string EncodeParameters (IReadOnlyDictionary< string, string > parameters, DreamDaemonLaunchParameters launchParameters)
Encode given parameters for passing as world.params on the command line.
Detailed Description
Implementation of IEngineInstallation for EngineType.Byond.
Definition at line 16 of file ByondInstallation.cs.
Constructor & Destructor Documentation
ByondInstallation()
Tgstation.Server.Host.Components.Engine.ByondInstallation.ByondInstallation (IIOManager installationIOManager, Task installationTask, EngineVersion version, string dreamDaemonPath, string dreamMakerPath, bool supportsCli, bool supportsMapThreads)
Initializes a new instance of the ByondInstallation class.
Parameters
installationIOManager The IIOManager for the EngineInstallationBase.
installationTask The value of InstallationTask.
version The value of Version.
dreamDaemonPath The value of ServerExePath.
dreamMakerPath The value of CompilerExePath.
supportsCli If a CLI application is being used.
supportsMapThreads The value of supportsMapThreads.
Definition at line 89 of file ByondInstallation.cs.
            : base(installationIOManager)
        {
            InstallationTask = installationTask ?? throw new ArgumentNullException(nameof(installationTask));
            ArgumentNullException.ThrowIfNull(version);
            if (version.Engine != EngineType.Byond)
                throw new ArgumentException($"Invalid EngineType: {version.Engine}", nameof(version));
            Version = version ?? throw new ArgumentNullException(nameof(version));
            ServerExePath = dreamDaemonPath ?? throw new ArgumentNullException(nameof(dreamDaemonPath));
            CompilerExePath = dreamMakerPath ?? throw new ArgumentNullException(nameof(dreamMakerPath));
            HasStandardOutput = supportsCli;
            PromptsForNetworkAccess = !supportsCli;
            this.supportsMapThreads = supportsMapThreads;
        }
References Tgstation.Server.Host.Components.Engine.ByondInstallation.CompilerExePath, Tgstation.Server.Api.Models.EngineVersion.Engine, Tgstation.Server.Host.Components.Engine.ByondInstallation.HasStandardOutput, Tgstation.Server.Host.Components.Engine.ByondInstallation.InstallationTask, Tgstation.Server.Host.Components.Engine.ByondInstallation.PromptsForNetworkAccess, Tgstation.Server.Host.Components.Engine.ByondInstallation.ServerExePath, Tgstation.Server.Host.Components.Engine.ByondInstallation.supportsMapThreads, and Tgstation.Server.Host.Components.Engine.ByondInstallation.Version.
Member Function Documentation
FormatCompilerArguments()
override string Tgstation.Server.Host.Components.Engine.ByondInstallation.FormatCompilerArguments (string dmePath, string? additionalArguments)
Return the command line arguments for compiling a given dmePath if compilation is necessary.
Parameters
dmePath The full path to the .dme to compile.
additionalArguments Optional additional arguments provided to the compiler.
Returns
The formatted arguments string.
Implements Tgstation.Server.Host.Components.Engine.IEngineInstallation.
Definition at line 150 of file ByondInstallation.cs.
        {
            if (String.IsNullOrWhiteSpace(additionalArguments))
                additionalArguments = String.Empty;
            else
                additionalArguments = $"{additionalArguments.Trim()} ";
            return $"-clean {additionalArguments}\"{dmePath ?? throw new ArgumentNullException(nameof(dmePath))}\"";
        }
FormatServerArguments()
override string Tgstation.Server.Host.Components.Engine.ByondInstallation.FormatServerArguments (IDmbProvider dmbProvider, IReadOnlyDictionary< string, string > parameters, DreamDaemonLaunchParameters launchParameters, string? logFilePath)
Return the command line arguments for launching with given launchParameters .
Parameters
dmbProvider The IDmbProvider.
parameters The map of parameter strings as a IReadOnlyDictionary<TKey, TValue>. MUST include Interop.DMApiConstants.ParamAccessIdentifier. Should NOT include the DreamDaemonLaunchParameters.AdditionalParameters of launchParameters .
launchParameters The DreamDaemonLaunchParameters.
logFilePath The full path to the log file, if any.
Returns
The formatted arguments string.
Implements Tgstation.Server.Host.Components.Engine.IEngineInstallation.
Definition at line 114 of file ByondInstallation.cs.
        {
            ArgumentNullException.ThrowIfNull(dmbProvider);
            ArgumentNullException.ThrowIfNull(parameters);
            ArgumentNullException.ThrowIfNull(launchParameters);
            var parametersString = EncodeParameters(parameters, launchParameters);
            var arguments = String.Format(
                CultureInfo.InvariantCulture,
                "\"{0}\" -port {1} -ports 1-65535 {2}-close -verbose -{3} -{4}{5}{6}{7} -params \"{8}\"",
                dmbProvider.DmbName,
                launchParameters.Port!.Value,
                launchParameters.AllowWebClient!.Value
                    ? "-webclient "
                    : String.Empty,
                SecurityWord(launchParameters.SecurityLevel!.Value),
                VisibilityWord(launchParameters.Visibility!.Value),
                logFilePath != null
                    ? $" -logself -log {logFilePath}"
                    : String.Empty, // DD doesn't output anything if -logself is set???
                launchParameters.StartProfiler!.Value
                    ? " -profile"
                    : String.Empty,
                supportsMapThreads && launchParameters.MapThreads!.Value != 0
                    ? $" -map-threads {launchParameters.MapThreads.Value}"
                    : String.Empty,
                parametersString);
            return arguments;
        }
References Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.AllowWebClient, Tgstation.Server.Host.Components.Deployment.IDmbProvider.DmbName, Tgstation.Server.Host.Components.Engine.EngineInstallationBase.EncodeParameters(), Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.MapThreads, Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.Port, Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.SecurityLevel, Tgstation.Server.Host.Components.Engine.ByondInstallation.SecurityWord(), Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.StartProfiler, Tgstation.Server.Host.Components.Engine.ByondInstallation.supportsMapThreads, Tgstation.Server.Api.Models.Internal.DreamDaemonLaunchParameters.Visibility, and Tgstation.Server.Host.Components.Engine.ByondInstallation.VisibilityWord().
SecurityWord()
static string Tgstation.Server.Host.Components.Engine.ByondInstallation.SecurityWord (DreamDaemonSecurity securityLevel) static private
Change a given securityLevel into the appropriate DreamDaemon command line word.
Parameters
securityLevel The DreamDaemonSecurity level to change.
Returns
A string representation of the command line parameter.
Definition at line 52 of file ByondInstallation.cs.
        {
            return securityLevel switch
            {
                DreamDaemonSecurity.Safe => "safe",
                DreamDaemonSecurity.Trusted => "trusted",
                DreamDaemonSecurity.Ultrasafe => "ultrasafe",
                _ => throw new ArgumentOutOfRangeException(nameof(securityLevel), securityLevel, String.Format(CultureInfo.InvariantCulture, "Bad DreamDaemon security level: {0}", securityLevel)),
            };
        }
Referenced by Tgstation.Server.Host.Components.Engine.ByondInstallation.FormatServerArguments().
VisibilityWord()
static string Tgstation.Server.Host.Components.Engine.ByondInstallation.VisibilityWord (DreamDaemonVisibility visibility) static private
Change a given visibility into the appropriate DreamDaemon command line word.
Parameters
visibility The DreamDaemonVisibility level to change.
Returns
A string representation of the command line parameter.
Definition at line 68 of file ByondInstallation.cs.
        {
            return visibility switch
            {
                DreamDaemonVisibility.Public => "public",
                DreamDaemonVisibility.Private => "private",
                DreamDaemonVisibility.Invisible => "invisible",
                _ => throw new ArgumentOutOfRangeException(nameof(visibility), visibility, String.Format(CultureInfo.InvariantCulture, "Bad DreamDaemon visibility level: {0}", visibility)),
            };
        }
Referenced by Tgstation.Server.Host.Components.Engine.ByondInstallation.FormatServerArguments().
Member Data Documentation
supportsMapThreads
readonly bool Tgstation.Server.Host.Components.Engine.ByondInstallation.supportsMapThreads private
If map threads are supported by the Version.
Definition at line 45 of file ByondInstallation.cs.
Referenced by Tgstation.Server.Host.Components.Engine.ByondInstallation.ByondInstallation(), and Tgstation.Server.Host.Components.Engine.ByondInstallation.FormatServerArguments().
Property Documentation
CompilerExePath
override string Tgstation.Server.Host.Components.Engine.ByondInstallation.CompilerExePath get
The full path to the dm/DreamMaker executable.
Implements Tgstation.Server.Host.Components.Engine.IEngineInstallation.
Definition at line 25 of file ByondInstallation.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Engine.ByondInstallation.ByondInstallation().
HasStandardOutput
override bool Tgstation.Server.Host.Components.Engine.ByondInstallation.HasStandardOutput get
If ServerExePath supports being run as a command-line application and outputs log information to be captured.
Implements Tgstation.Server.Host.Components.Engine.IEngineInstallation.
Definition at line 31 of file ByondInstallation.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Engine.ByondInstallation.ByondInstallation().
InstallationTask
override Task Tgstation.Server.Host.Components.Engine.ByondInstallation.InstallationTask get
The Task that completes when the BYOND version finished installing.
Implements Tgstation.Server.Host.Components.Engine.IEngineInstallation.
Definition at line 40 of file ByondInstallation.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Engine.ByondInstallation.ByondInstallation().
PreferFileLogging
override bool Tgstation.Server.Host.Components.Engine.ByondInstallation.PreferFileLogging get
If HasStandardOutput is set, this indicates that the engine server has good file logging that should be preferred to ours.
Implements Tgstation.Server.Host.Components.Engine.IEngineInstallation.
Definition at line 34 of file ByondInstallation.cs.
PromptsForNetworkAccess
override bool Tgstation.Server.Host.Components.Engine.ByondInstallation.PromptsForNetworkAccess get
If ServerExePath may create network prompts.
Implements Tgstation.Server.Host.Components.Engine.IEngineInstallation.
Definition at line 28 of file ByondInstallation.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Engine.ByondInstallation.ByondInstallation().
ServerExePath
override string Tgstation.Server.Host.Components.Engine.ByondInstallation.ServerExePath get
The full path to the game server executable.
Implements Tgstation.Server.Host.Components.Engine.IEngineInstallation.
Definition at line 22 of file ByondInstallation.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Engine.ByondInstallation.ByondInstallation().
UseDotnetDump
override bool Tgstation.Server.Host.Components.Engine.ByondInstallation.UseDotnetDump get
If dotnet-dump should be used to create process dumps for this installation.
Implements Tgstation.Server.Host.Components.Engine.IEngineInstallation.
Definition at line 37 of file ByondInstallation.cs.
Version
override EngineVersion Tgstation.Server.Host.Components.Engine.ByondInstallation.Version get
The EngineVersion of the IEngineInstallation.
Implements Tgstation.Server.Host.Components.Engine.IEngineInstallation.
Definition at line 19 of file ByondInstallation.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Engine.ByondInstallation.ByondInstallation().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Components/Engine/ByondInstallation.cs