tgstation-server: Tgstation.Server.Host.Utils.GitHub.GitHubServiceFactory Class Reference
Tgstation.Server.Host.Utils.GitHub.GitHubServiceFactory Class Reference sealed
Public Member Functions
GitHubServiceFactory (IGitHubClientFactory gitHubClientFactory, ILoggerFactory loggerFactory, IOptionsMonitor< UpdatesConfiguration > updatesConfigurationOptions)
Initializes a new instance of the GitHubServiceFactory class.
async ValueTask< IGitHubService > CreateService (CancellationToken cancellationToken)
Create a IGitHubService.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a new IGitHubService.
async ValueTask< IAuthenticatedGitHubService > CreateService (string accessToken, CancellationToken cancellationToken)
Create an IAuthenticatedGitHubService.
Parameters
accessToken The access token to use for communication with GitHub.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a new IAuthenticatedGitHubService.
async ValueTask< IAuthenticatedGitHubService?> CreateService (string accessString, RepositoryIdentifier repositoryIdentifier, CancellationToken cancellationToken)
Create an IAuthenticatedGitHubService.
Parameters
accessString The access token to use for communication with GitHub.
repositoryIdentifier The RepositoryIdentifier for the repository the service will be talking with.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a new IAuthenticatedGitHubService.
Private Member Functions
GitHubService CreateServiceImpl (IGitHubClient gitHubClient)
Create a GitHubService.
Private Attributes
readonly IGitHubClientFactory gitHubClientFactory
The IGitHubClientFactory for the GitHubServiceFactory.
readonly ILoggerFactory loggerFactory
The ILoggerFactory for the GitHubServiceFactory.
readonly IOptionsMonitor< UpdatesConfiguration > updatesConfigurationOptions
The UpdatesConfiguration for the GitHubServiceFactory.
Detailed Description
Definition at line 15 of file GitHubServiceFactory.cs.
Constructor & Destructor Documentation
GitHubServiceFactory()
Tgstation.Server.Host.Utils.GitHub.GitHubServiceFactory.GitHubServiceFactory (IGitHubClientFactory gitHubClientFactory, ILoggerFactory loggerFactory, IOptionsMonitor< UpdatesConfiguration > updatesConfigurationOptions)
Initializes a new instance of the GitHubServiceFactory class.
Parameters
gitHubClientFactory The value of gitHubClientFactory.
loggerFactory The value of loggerFactory.
updatesConfigurationOptions The value of updatesConfigurationOptions.
Definition at line 38 of file GitHubServiceFactory.cs.
        {
            this.gitHubClientFactory = gitHubClientFactory ?? throw new ArgumentNullException(nameof(gitHubClientFactory));
            this.loggerFactory = loggerFactory ?? throw new ArgumentNullException(nameof(loggerFactory));
            this.updatesConfigurationOptions = updatesConfigurationOptions ?? throw new ArgumentNullException(nameof(updatesConfigurationOptions));
        }
References Tgstation.Server.Host.Utils.GitHub.GitHubServiceFactory.gitHubClientFactory, Tgstation.Server.Host.Utils.GitHub.GitHubServiceFactory.loggerFactory, and Tgstation.Server.Host.Utils.GitHub.GitHubServiceFactory.updatesConfigurationOptions.
Member Function Documentation
CreateService() [1/3]
async ValueTask< IGitHubService > Tgstation.Server.Host.Utils.GitHub.GitHubServiceFactory.CreateService (CancellationToken cancellationToken)
Create a IGitHubService.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a new IGitHubService.
Implements Tgstation.Server.Host.Utils.GitHub.IGitHubServiceFactory.
CreateService() [2/3]
async ValueTask< IAuthenticatedGitHubService?> Tgstation.Server.Host.Utils.GitHub.GitHubServiceFactory.CreateService (string accessString, RepositoryIdentifier repositoryIdentifier, CancellationToken cancellationToken)
Create an IAuthenticatedGitHubService.
Parameters
accessString The access token to use for communication with GitHub.
repositoryIdentifier The RepositoryIdentifier for the repository the service will be talking with.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a new IAuthenticatedGitHubService.
Implements Tgstation.Server.Host.Utils.GitHub.IGitHubServiceFactory.
Definition at line 61 of file GitHubServiceFactory.cs.
        {
            var client = await gitHubClientFactory.CreateClientForRepository(
                accessString ?? throw new ArgumentNullException(nameof(accessString)),
                repositoryIdentifier,
                cancellationToken);
            if (client == null)
                return null;
            return CreateServiceImpl(client);
        }
References Tgstation.Server.Host.Utils.GitHub.IGitHubClientFactory.CreateClientForRepository(), Tgstation.Server.Host.Utils.GitHub.GitHubServiceFactory.CreateServiceImpl(), and Tgstation.Server.Host.Utils.GitHub.GitHubServiceFactory.gitHubClientFactory.
CreateService() [3/3]
async ValueTask< IAuthenticatedGitHubService > Tgstation.Server.Host.Utils.GitHub.GitHubServiceFactory.CreateService (string accessToken, CancellationToken cancellationToken)
Create an IAuthenticatedGitHubService.
Parameters
accessToken The access token to use for communication with GitHub.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a new IAuthenticatedGitHubService.
Implements Tgstation.Server.Host.Utils.GitHub.IGitHubServiceFactory.
CreateServiceImpl()
GitHubService Tgstation.Server.Host.Utils.GitHub.GitHubServiceFactory.CreateServiceImpl (IGitHubClient gitHubClient) private
Create a GitHubService.
Parameters
gitHubClient The IGitHubClient for the GitHubService.
Returns
A new GitHubService.
Referenced by Tgstation.Server.Host.Utils.GitHub.GitHubServiceFactory.CreateService().
Member Data Documentation
gitHubClientFactory
readonly IGitHubClientFactory Tgstation.Server.Host.Utils.GitHub.GitHubServiceFactory.gitHubClientFactory private
The IGitHubClientFactory for the GitHubServiceFactory.
Definition at line 20 of file GitHubServiceFactory.cs.
Referenced by Tgstation.Server.Host.Utils.GitHub.GitHubServiceFactory.CreateService(), and Tgstation.Server.Host.Utils.GitHub.GitHubServiceFactory.GitHubServiceFactory().
loggerFactory
readonly ILoggerFactory Tgstation.Server.Host.Utils.GitHub.GitHubServiceFactory.loggerFactory private
The ILoggerFactory for the GitHubServiceFactory.
Definition at line 25 of file GitHubServiceFactory.cs.
Referenced by Tgstation.Server.Host.Utils.GitHub.GitHubServiceFactory.GitHubServiceFactory().
updatesConfigurationOptions
readonly IOptionsMonitor<UpdatesConfiguration> Tgstation.Server.Host.Utils.GitHub.GitHubServiceFactory.updatesConfigurationOptions private
The UpdatesConfiguration for the GitHubServiceFactory.
Definition at line 30 of file GitHubServiceFactory.cs.
Referenced by Tgstation.Server.Host.Utils.GitHub.GitHubServiceFactory.GitHubServiceFactory().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Utils/GitHub/GitHubServiceFactory.cs