tgstation-server: Tgstation.Server.Client.ApiClientTokenRefreshRetryPolicy Class Reference
Tgstation.Server.Client.ApiClientTokenRefreshRetryPolicy Class Reference sealed
A IRetryPolicy that attempts to refresh a given apiClient's token on the first disconnect.
Public Member Functions
ApiClientTokenRefreshRetryPolicy (ApiClient apiClient, IRetryPolicy wrappedPolicy)
Initializes a new instance of the ApiClientTokenRefreshRetryPolicy class.
TimeSpan? NextRetryDelay (RetryContext retryContext)
Private Member Functions
async void AttemptTokenRefresh ()
Attempt to refresh the apiClients token asynchronously.
Private Attributes
readonly ApiClient apiClient
The backing ApiClient.
readonly IRetryPolicy wrappedPolicy
The wrapped IRetryPolicy.
Detailed Description
A IRetryPolicy that attempts to refresh a given apiClient's token on the first disconnect.
Definition at line 11 of file ApiClientTokenRefreshRetryPolicy.cs.
Constructor & Destructor Documentation
ApiClientTokenRefreshRetryPolicy()
Tgstation.Server.Client.ApiClientTokenRefreshRetryPolicy.ApiClientTokenRefreshRetryPolicy (ApiClient apiClient, IRetryPolicy wrappedPolicy)
Initializes a new instance of the ApiClientTokenRefreshRetryPolicy class.
Parameters
apiClient The value of apiClient.
wrappedPolicy The value of wrappedPolicy.
Definition at line 28 of file ApiClientTokenRefreshRetryPolicy.cs.
        {
            this.apiClient = apiClient ?? throw new ArgumentNullException(nameof(apiClient));
            this.wrappedPolicy = wrappedPolicy ?? throw new ArgumentNullException(nameof(wrappedPolicy));
        }
References Tgstation.Server.Client.ApiClientTokenRefreshRetryPolicy.apiClient, and Tgstation.Server.Client.ApiClientTokenRefreshRetryPolicy.wrappedPolicy.
Member Function Documentation
AttemptTokenRefresh()
async void Tgstation.Server.Client.ApiClientTokenRefreshRetryPolicy.AttemptTokenRefresh () private
Attempt to refresh the apiClients token asynchronously.
Definition at line 49 of file ApiClientTokenRefreshRetryPolicy.cs.
        {
            try
            {
                await apiClient.RefreshToken(CancellationToken.None);
            }
            catch
            {
                // intentionally ignored
            }
        }
References Tgstation.Server.Client.ApiClientTokenRefreshRetryPolicy.apiClient, and Tgstation.Server.Client.ApiClient.RefreshToken().
Referenced by Tgstation.Server.Client.ApiClientTokenRefreshRetryPolicy.NextRetryDelay().
NextRetryDelay()
TimeSpan? Tgstation.Server.Client.ApiClientTokenRefreshRetryPolicy.NextRetryDelay (RetryContext retryContext)
Definition at line 35 of file ApiClientTokenRefreshRetryPolicy.cs.
        {
            if (retryContext == null)
                throw new ArgumentNullException(nameof(retryContext));
            if (retryContext.PreviousRetryCount == 0)
                AttemptTokenRefresh();
            return wrappedPolicy.NextRetryDelay(retryContext);
        }
References Tgstation.Server.Client.ApiClientTokenRefreshRetryPolicy.AttemptTokenRefresh(), and Tgstation.Server.Client.ApiClientTokenRefreshRetryPolicy.wrappedPolicy.
Member Data Documentation
apiClient
readonly ApiClient Tgstation.Server.Client.ApiClientTokenRefreshRetryPolicy.apiClient private
The backing ApiClient.
Definition at line 16 of file ApiClientTokenRefreshRetryPolicy.cs.
Referenced by Tgstation.Server.Client.ApiClientTokenRefreshRetryPolicy.ApiClientTokenRefreshRetryPolicy(), and Tgstation.Server.Client.ApiClientTokenRefreshRetryPolicy.AttemptTokenRefresh().
wrappedPolicy
readonly IRetryPolicy Tgstation.Server.Client.ApiClientTokenRefreshRetryPolicy.wrappedPolicy private
The wrapped IRetryPolicy.
Definition at line 21 of file ApiClientTokenRefreshRetryPolicy.cs.
Referenced by Tgstation.Server.Client.ApiClientTokenRefreshRetryPolicy.ApiClientTokenRefreshRetryPolicy(), and Tgstation.Server.Client.ApiClientTokenRefreshRetryPolicy.NextRetryDelay().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Client/ApiClientTokenRefreshRetryPolicy.cs