tgstation-server: Tgstation.Server.Host.Core.VersionReportingService Class Reference
Tgstation.Server.Host.Core.VersionReportingService Class Reference sealed
Handles TGS version reporting, if enabled.
Public Member Functions
VersionReportingService (IGitHubClientFactory gitHubClientFactory, IIOManager ioManager, IAsyncDelayer asyncDelayer, IAssemblyInformationProvider assemblyInformationProvider, IOptions< TelemetryConfiguration > telemetryConfigurationOptions, ILogger< VersionReportingService > logger)
Initializes a new instance of the VersionReportingService class.
override Task StopAsync (CancellationToken cancellationToken)
Protected Member Functions
override async Task ExecuteAsync (CancellationToken stoppingToken)
Private Member Functions
async ValueTask< bool > TryReportVersion (Guid telemetryId, string serializedPem, long repositoryId, bool shutdown, CancellationToken cancellationToken)
Make an attempt to report the current IAssemblyInformationProvider.Version to the configured GitHub repository.
Private Attributes
readonly IGitHubClientFactory gitHubClientFactory
The IGitHubClientFactory for the VersionReportingService.
readonly IIOManager ioManager
The IIOManager for the VersionReportingService.
readonly IAsyncDelayer asyncDelayer
The IAsyncDelayer for the VersionReportingService.
readonly IAssemblyInformationProvider assemblyInformationProvider
The IAssemblyInformationProvider for the VersionReportingService.
readonly ILogger< VersionReportingService > logger
The ILogger for the VersionReportingService.
readonly TelemetryConfiguration telemetryConfiguration
The TelemetryConfiguration for the VersionReportingService.
CancellationToken shutdownCancellationToken
The CancellationToken passed to StopAsync(CancellationToken).
Detailed Description
Handles TGS version reporting, if enabled.
Definition at line 27 of file VersionReportingService.cs.
Constructor & Destructor Documentation
VersionReportingService()
Tgstation.Server.Host.Core.VersionReportingService.VersionReportingService (IGitHubClientFactory gitHubClientFactory, IIOManager ioManager, IAsyncDelayer asyncDelayer, IAssemblyInformationProvider assemblyInformationProvider, IOptions< TelemetryConfiguration > telemetryConfigurationOptions, ILogger< VersionReportingService > logger)
Initializes a new instance of the VersionReportingService class.
Parameters
gitHubClientFactory The value of gitHubClientFactory.
ioManager The value of ioManager.
asyncDelayer The value of asyncDelayer.
assemblyInformationProvider The value of assemblyInformationProvider.
telemetryConfigurationOptions The IOptions<TOptions> containing the value of telemetryConfiguration.
logger The value of logger.
Definition at line 73 of file VersionReportingService.cs.
        {
            this.gitHubClientFactory = gitHubClientFactory ?? throw new ArgumentNullException(nameof(gitHubClientFactory));
            this.ioManager = ioManager ?? throw new ArgumentNullException(nameof(ioManager));
            this.asyncDelayer = asyncDelayer ?? throw new ArgumentNullException(nameof(asyncDelayer));
            this.assemblyInformationProvider = assemblyInformationProvider ?? throw new ArgumentNullException(nameof(assemblyInformationProvider));
            telemetryConfiguration = telemetryConfigurationOptions?.Value ?? throw new ArgumentNullException(nameof(telemetryConfigurationOptions));
            this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }
References Tgstation.Server.Host.Core.VersionReportingService.assemblyInformationProvider, Tgstation.Server.Host.Core.VersionReportingService.asyncDelayer, Tgstation.Server.Host.Core.VersionReportingService.gitHubClientFactory, Tgstation.Server.Host.Core.VersionReportingService.ioManager, Tgstation.Server.Host.Core.VersionReportingService.logger, and Tgstation.Server.Host.Core.VersionReportingService.telemetryConfiguration.
Member Function Documentation
ExecuteAsync()
override async Task Tgstation.Server.Host.Core.VersionReportingService.ExecuteAsync (CancellationToken stoppingToken) protected
Definition at line 97 of file VersionReportingService.cs.
        {
            if (telemetryConfiguration.DisableVersionReporting)
            {
                logger.LogDebug("Version telemetry disabled");
                return;
            }
            if (!telemetryConfiguration.VersionReportingRepositoryId.HasValue)
            {
                logger.LogError("Version reporting repository is misconfigured. Telemetry cannot be sent!");
                return;
            }
            var attribute = TelemetryAppSerializedKeyAttribute.Instance;
            if (attribute == null)
            {
                logger.LogDebug("TGS build configuration does not allow for version telemetry");
                return;
            }
            logger.LogDebug("Starting...");
            try
            {
                var telemetryIdDirectory = ioManager.GetPathInLocalDirectory(assemblyInformationProvider);
                var telemetryIdFile = ioManager.ResolvePath(
                    ioManager.ConcatPath(
                        telemetryIdDirectory,
                        "telemetry.id"));
                Guid telemetryId;
                if (!await ioManager.FileExists(telemetryIdFile, stoppingToken))
                {
                    telemetryId = Guid.NewGuid();
                    await ioManager.CreateDirectory(telemetryIdDirectory, stoppingToken);
                    await ioManager.WriteAllBytes(telemetryIdFile, Encoding.UTF8.GetBytes(telemetryId.ToString()), stoppingToken);
                    logger.LogInformation("Generated telemetry ID {telemetryId} and wrote to {file}", telemetryId, telemetryIdFile);
                }
                else
                {
                    var contents = await ioManager.ReadAllBytes(telemetryIdFile, stoppingToken);
                    string guidStr;
                    try
                    {
                        guidStr = Encoding.UTF8.GetString(contents);
                    }
                    catch (Exception ex)
                    {
                        logger.LogError(ex, "Cannot decode telemetry ID from installation file ({path}). Telemetry will not be sent!", telemetryIdFile);
                        return;
                    }
                    if (!Guid.TryParse(guidStr, out telemetryId))
                    {
                        logger.LogError("Cannot parse telemetry ID from installation file ({path}). Telemetry will not be sent!", telemetryIdFile);
                        return;
                    }
                }
                try
                {
                    while (!stoppingToken.IsCancellationRequested)
                    {
                        var nextDelayHours = await TryReportVersion(
                            telemetryId,
                            attribute.SerializedKey,
                            telemetryConfiguration.VersionReportingRepositoryId.Value,
                            false,
                            stoppingToken)
                            ? 24
                            : 1;
                        logger.LogDebug("Next version report in {hours} hours", nextDelayHours);
                        await asyncDelayer.Delay(TimeSpan.FromHours(nextDelayHours), stoppingToken);
                    }
                }
                catch (OperationCanceledException ex)
                {
                    logger.LogTrace(ex, "Inner cancellation");
                }
                shutdownCancellationToken.ThrowIfCancellationRequested();
                logger.LogDebug("Sending shutdown telemetry");
                await TryReportVersion(
                    telemetryId,
                    attribute.SerializedKey,
                    telemetryConfiguration.VersionReportingRepositoryId.Value,
                    true,
                    shutdownCancellationToken);
            }
            catch (OperationCanceledException ex)
            {
                logger.LogTrace(ex, "Exiting due to outer cancellation...");
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Crashed!");
            }
        }
References Tgstation.Server.Host.Core.VersionReportingService.assemblyInformationProvider, Tgstation.Server.Host.Core.VersionReportingService.asyncDelayer, Tgstation.Server.Host.IO.IIOManager.ConcatPath(), Tgstation.Server.Host.IO.IIOManager.CreateDirectory(), Tgstation.Server.Host.Utils.IAsyncDelayer.Delay(), Tgstation.Server.Host.Configuration.TelemetryConfiguration.DisableVersionReporting, Tgstation.Server.Host.IO.IIOManager.FileExists(), Tgstation.Server.Host.Properties.TelemetryAppSerializedKeyAttribute.Instance, Tgstation.Server.Host.Core.VersionReportingService.ioManager, Tgstation.Server.Host.Core.VersionReportingService.logger, Tgstation.Server.Host.IO.IIOManager.ReadAllBytes(), Tgstation.Server.Host.IO.IIOManager.ResolvePath(), Tgstation.Server.Host.Core.VersionReportingService.shutdownCancellationToken, Tgstation.Server.Host.Core.VersionReportingService.telemetryConfiguration, Tgstation.Server.Host.Core.VersionReportingService.TryReportVersion(), Tgstation.Server.Host.Configuration.TelemetryConfiguration.VersionReportingRepositoryId, and Tgstation.Server.Host.IO.IIOManager.WriteAllBytes().
StopAsync()
override Task Tgstation.Server.Host.Core.VersionReportingService.StopAsync (CancellationToken cancellationToken)
Definition at line 90 of file VersionReportingService.cs.
        {
            shutdownCancellationToken = cancellationToken;
            return base.StopAsync(cancellationToken);
        }
References Tgstation.Server.Host.Core.VersionReportingService.shutdownCancellationToken.
TryReportVersion()
async ValueTask< bool > Tgstation.Server.Host.Core.VersionReportingService.TryReportVersion (Guid telemetryId, string serializedPem, long repositoryId, bool shutdown, CancellationToken cancellationToken) private
Make an attempt to report the current IAssemblyInformationProvider.Version to the configured GitHub repository.
Parameters
telemetryId The telemetry Guid for the installation.
serializedPem The serialized authentication string for the gitHubClientFactory.
repositoryId The ID of the repository to send telemetry to.
shutdown If this is shutdown telemetry.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in true if telemetry was reported successfully, false otherwise.
Definition at line 209 of file VersionReportingService.cs.
        {
            logger.LogDebug("Sending version telemetry...");
            var serverFriendlyName = telemetryConfiguration.ServerFriendlyName;
            if (String.IsNullOrWhiteSpace(serverFriendlyName))
                serverFriendlyName = null;
            logger.LogTrace(
                 "Repository ID: {repoId}, Server friendly name: {friendlyName}",
                 repositoryId,
                 serverFriendlyName == null
                    ? "(null)"
                    : $"\"{serverFriendlyName}\"");
            try
            {
                var gitHubClient = await gitHubClientFactory.CreateClientForRepository(
                    serializedPem,
                    new RepositoryIdentifier(repositoryId),
                    cancellationToken);
                if (gitHubClient == null)
                {
                    logger.LogWarning("Could not create GitHub client to connect to repository ID {repoId}!", repositoryId);
                    return false;
                }
                // remove this lookup once https://github.com/octokit/octokit.net/pull/2960 is merged and released
                var repository = await gitHubClient.Repository.Get(repositoryId);
                logger.LogTrace("Repository ID {id} resolved to {owner}/{name}", repositoryId, repository.Owner.Name, repository.Name);
                var inputs = new Dictionary<string, object>
                {
                    { "telemetry_id", telemetryId.ToString() },
                    { "tgs_semver", assemblyInformationProvider.Version.Semver().ToString() },
                    { "shutdown", shutdown ? "true" : "false" },
                };
                if (serverFriendlyName != null)
                    inputs.Add("server_friendly_name", serverFriendlyName);
                await gitHubClient.Actions.Workflows.CreateDispatch(
                    repository.Owner.Login,
                    repository.Name,
                    ".github/workflows/tgs_deployments_telemetry.yml",
                    new CreateWorkflowDispatch("main")
                    {
                        Inputs = inputs,
                    });
                logger.LogTrace("Telemetry sent successfully");
                return true;
            }
            catch (Exception ex)
            {
                logger.LogWarning(ex, "Failed to report version!");
                return false;
            }
        }
References Tgstation.Server.Host.Core.VersionReportingService.assemblyInformationProvider, Tgstation.Server.Host.Utils.GitHub.IGitHubClientFactory.CreateClientForRepository(), Tgstation.Server.Host.Core.VersionReportingService.gitHubClientFactory, Tgstation.Server.Host.Core.VersionReportingService.logger, Tgstation.Server.Host.Configuration.TelemetryConfiguration.ServerFriendlyName, Tgstation.Server.Host.Core.VersionReportingService.telemetryConfiguration, and Tgstation.Server.Host.System.IAssemblyInformationProvider.Version.
Referenced by Tgstation.Server.Host.Core.VersionReportingService.ExecuteAsync().
Member Data Documentation
assemblyInformationProvider
readonly IAssemblyInformationProvider Tgstation.Server.Host.Core.VersionReportingService.assemblyInformationProvider private
The IAssemblyInformationProvider for the VersionReportingService.
Definition at line 47 of file VersionReportingService.cs.
Referenced by Tgstation.Server.Host.Core.VersionReportingService.ExecuteAsync(), Tgstation.Server.Host.Core.VersionReportingService.TryReportVersion(), and Tgstation.Server.Host.Core.VersionReportingService.VersionReportingService().
asyncDelayer
readonly IAsyncDelayer Tgstation.Server.Host.Core.VersionReportingService.asyncDelayer private
The IAsyncDelayer for the VersionReportingService.
Definition at line 42 of file VersionReportingService.cs.
Referenced by Tgstation.Server.Host.Core.VersionReportingService.ExecuteAsync(), and Tgstation.Server.Host.Core.VersionReportingService.VersionReportingService().
gitHubClientFactory
readonly IGitHubClientFactory Tgstation.Server.Host.Core.VersionReportingService.gitHubClientFactory private
The IGitHubClientFactory for the VersionReportingService.
Definition at line 32 of file VersionReportingService.cs.
Referenced by Tgstation.Server.Host.Core.VersionReportingService.TryReportVersion(), and Tgstation.Server.Host.Core.VersionReportingService.VersionReportingService().
ioManager
readonly IIOManager Tgstation.Server.Host.Core.VersionReportingService.ioManager private
The IIOManager for the VersionReportingService.
Definition at line 37 of file VersionReportingService.cs.
Referenced by Tgstation.Server.Host.Core.VersionReportingService.ExecuteAsync(), and Tgstation.Server.Host.Core.VersionReportingService.VersionReportingService().
logger
readonly ILogger<VersionReportingService> Tgstation.Server.Host.Core.VersionReportingService.logger private
The ILogger for the VersionReportingService.
Definition at line 52 of file VersionReportingService.cs.
Referenced by Tgstation.Server.Host.Core.VersionReportingService.ExecuteAsync(), Tgstation.Server.Host.Core.VersionReportingService.TryReportVersion(), and Tgstation.Server.Host.Core.VersionReportingService.VersionReportingService().
shutdownCancellationToken
CancellationToken Tgstation.Server.Host.Core.VersionReportingService.shutdownCancellationToken private
The CancellationToken passed to StopAsync(CancellationToken).
Definition at line 62 of file VersionReportingService.cs.
Referenced by Tgstation.Server.Host.Core.VersionReportingService.ExecuteAsync(), and Tgstation.Server.Host.Core.VersionReportingService.StopAsync().
telemetryConfiguration
readonly TelemetryConfiguration Tgstation.Server.Host.Core.VersionReportingService.telemetryConfiguration private
The TelemetryConfiguration for the VersionReportingService.
Definition at line 57 of file VersionReportingService.cs.
Referenced by Tgstation.Server.Host.Core.VersionReportingService.ExecuteAsync(), Tgstation.Server.Host.Core.VersionReportingService.TryReportVersion(), and Tgstation.Server.Host.Core.VersionReportingService.VersionReportingService().
The documentation for this class was generated from the following file:
src/Tgstation.Server.Host/Core/VersionReportingService.cs