tgstation-server: Tgstation.Server.Host.Components.Byond.IByondInstaller Interface Reference
Tgstation.Server.Host.Components.Byond.IByondInstaller Interface Reference
For downloading and installing BYOND extractions for a given system.
Public Member Functions
string GetDreamDaemonName (Version version, out bool supportsCli, out bool supportsMapThreads)
Get the file name of the DreamDaemon executable.
ValueTask< MemoryStream > DownloadVersion (Version version, CancellationToken cancellationToken)
Download a given BYOND version .
ValueTask InstallByond (Version version, string path, CancellationToken cancellationToken)
Does actions necessary to get an extracted BYOND installation working.
ValueTask UpgradeInstallation (Version version, string path, CancellationToken cancellationToken)
Does actions necessary to get upgrade a BYOND version installed by a previous version of TGS.
Task CleanCache (CancellationToken cancellationToken)
Attempts to cleans the BYOND cache folder for the system.
Properties
string DreamMakerName [get]
Get the file name of the DreamMaker executable.
string PathToUserByondFolder [get]
The path to the BYOND folder for the user.
Detailed Description
For downloading and installing BYOND extractions for a given system.
Definition at line 11 of file IByondInstaller.cs.
Member Function Documentation
CleanCache()
Task Tgstation.Server.Host.Components.Byond.IByondInstaller.CleanCache (CancellationToken cancellationToken)
Attempts to cleans the BYOND cache folder for the system.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.Components.Byond.ByondInstallerBase.
Referenced by Tgstation.Server.Host.Components.InstanceFactory.StartAsync().
DownloadVersion()
ValueTask< MemoryStream > Tgstation.Server.Host.Components.Byond.IByondInstaller.DownloadVersion (Version version, CancellationToken cancellationToken)
Download a given BYOND version .
Parameters
version The Version of BYOND to download.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a MemoryStream of the zipfile.
Implemented in Tgstation.Server.Host.Components.Byond.ByondInstallerBase.
Referenced by Tgstation.Server.Host.Components.Byond.ByondManager.InstallVersionFiles().
GetDreamDaemonName()
string Tgstation.Server.Host.Components.Byond.IByondInstaller.GetDreamDaemonName (Version version, out bool supportsCli, out bool supportsMapThreads)
Get the file name of the DreamDaemon executable.
Parameters
version The Version of BYOND to select the executable name for.
supportsCli Whether or not the returned path supports being run as a command-line application.
supportsMapThreads Whether or not the returned path supports the '-map-threads' parameter.
Returns
The file name of the DreamDaemon executable.
Implemented in Tgstation.Server.Host.Components.Byond.ByondInstallerBase, Tgstation.Server.Host.Components.Byond.PosixByondInstaller, and Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.
Referenced by Tgstation.Server.Host.Components.Byond.ByondManager.AddInstallationContainer().
InstallByond()
ValueTask Tgstation.Server.Host.Components.Byond.IByondInstaller.InstallByond (Version version, string path, CancellationToken cancellationToken)
Does actions necessary to get an extracted BYOND installation working.
Parameters
version The Version of BYOND being installed.
path The path to the BYOND installation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implemented in Tgstation.Server.Host.Components.Byond.ByondInstallerBase, Tgstation.Server.Host.Components.Byond.PosixByondInstaller, and Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.
Referenced by Tgstation.Server.Host.Components.Byond.ByondManager.InstallVersionFiles().
UpgradeInstallation()
ValueTask Tgstation.Server.Host.Components.Byond.IByondInstaller.UpgradeInstallation (Version version, string path, CancellationToken cancellationToken)
Does actions necessary to get upgrade a BYOND version installed by a previous version of TGS.
Parameters
version The Version of BYOND being installed.
path The path to the BYOND installation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implemented in Tgstation.Server.Host.Components.Byond.ByondInstallerBase, Tgstation.Server.Host.Components.Byond.PosixByondInstaller, and Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.
Referenced by Tgstation.Server.Host.Components.Byond.ByondManager.StartAsync().
Property Documentation
DreamMakerName
string Tgstation.Server.Host.Components.Byond.IByondInstaller.DreamMakerName get
Get the file name of the DreamMaker executable.
Implemented in Tgstation.Server.Host.Components.Byond.ByondInstallerBase, Tgstation.Server.Host.Components.Byond.PosixByondInstaller, and Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.
Definition at line 16 of file IByondInstaller.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Byond.ByondManager.AddInstallationContainer().
PathToUserByondFolder
string Tgstation.Server.Host.Components.Byond.IByondInstaller.PathToUserByondFolder get
The path to the BYOND folder for the user.
Implemented in Tgstation.Server.Host.Components.Byond.ByondInstallerBase, Tgstation.Server.Host.Components.Byond.PosixByondInstaller, and Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.
Definition at line 21 of file IByondInstaller.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Byond.ByondManager.StartAsync(), and Tgstation.Server.Host.Components.Byond.ByondManager.TrustDmbPath().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Components/Byond/IByondInstaller.cs