tgstation-server: Tgstation.Server.Host.Components.Session.ISessionController Interface Reference
Tgstation.Server.Host.Components.Session.ISessionController Interface Reference
Handles communication with a DreamDaemon IProcess
Public Member Functions
ReattachInformation Release ()
Releases the IProcess without terminating it. Also calls IDisposable.Dispose
Task< CombinedTopicResponse > SendCommand (TopicParameters parameters, CancellationToken cancellationToken)
Sends a command to DreamDaemon through /world/Topic()
Task< bool > SetPort (ushort newPort, CancellationToken cancellatonToken)
Causes the world to start listening on a newPort
Task< bool > SetRebootState (RebootState newRebootState, CancellationToken cancellationToken)
Attempts to change the current RebootState to newRebootState
void ResetRebootState ()
Changes RebootState to RebootState.Normal without telling the DMAPI
void EnableCustomChatCommands ()
Enables the reading of custom chat commands from the ISessionController
void ReplaceDmbProvider (IDmbProvider newProvider)
Replace Dmb with a given newProvider , disposing the old one.
Public Member Functions inherited from Tgstation.Server.Host.System.IProcessBase
void SetHighPriority ()
Set's the owned global::System.Diagnostics.Process.PriorityClass to global::System.Diagnostics.ProcessPriorityClass.AboveNormal
void Suspend ()
Suspends the process.
void Resume ()
Resumes the process.
Properties
Task< LaunchResult > LaunchResult [get]
A Task that completes when DreamDaemon starts pumping the windows message queue after loading a .dmb or when it crashes
bool IsPrimary [get]
If the IDmbProvider.PrimaryDirectory of Dmb is being used
bool TerminationWasRequested [get]
If the DreamDaemon instance sent a
ApiValidationStatus ApiValidationStatus [get]
The DMAPI Session.ApiValidationStatus
Version DMApiVersion [get]
The DMAPI Version.
IDmbProvider Dmb [get]
The IDmbProvider being used
ushort Port [get]
The current port DreamDaemon is listening on
bool ClosePortOnReboot [get, set]
If the port should be rotated off when the world reboots
RebootState RebootState [get]
The current RebootState
Task OnReboot [get]
A Task that completes when the server calls /world/Reboot()
Task OnPrime [get]
A Task that completes when the server calls /world/TgsInitializationsComplete()
Properties inherited from Tgstation.Server.Host.System.IProcessBase
Task< int > Lifetime [get]
The Task<TResult> resulting in the exit code of the process
Detailed Description
Handles communication with a DreamDaemon IProcess
Definition at line 13 of file ISessionController.cs.
Member Function Documentation
void Tgstation.Server.Host.Components.Session.ISessionController.EnableCustomChatCommands ()
Enables the reading of custom chat commands from the ISessionController
Implemented in Tgstation.Server.Host.Components.Session.SessionController, and Tgstation.Server.Host.Components.Session.DeadSessionController.
Referenced by Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.HandleMonitorWakeup(), Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.InitControllers(), and Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.InitControllers().
ReattachInformation Tgstation.Server.Host.Components.Session.ISessionController.Release ()
Releases the IProcess without terminating it. Also calls IDisposable.Dispose
Returns
ReattachInformation which can be used to create a new ISessionController similar to this one
Implemented in Tgstation.Server.Host.Components.Session.SessionController, and Tgstation.Server.Host.Components.Session.DeadSessionController.
Referenced by Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.InitControllers().
void Tgstation.Server.Host.Components.Session.ISessionController.ReplaceDmbProvider (IDmbProvider newProvider)
Replace Dmb with a given newProvider , disposing the old one.
Parameters
newProvider The new IDmbProvider.
Implemented in Tgstation.Server.Host.Components.Session.SessionController, and Tgstation.Server.Host.Components.Session.DeadSessionController.
void Tgstation.Server.Host.Components.Session.ISessionController.ResetRebootState ()
Changes RebootState to RebootState.Normal without telling the DMAPI
Implemented in Tgstation.Server.Host.Components.Session.SessionController, and Tgstation.Server.Host.Components.Session.DeadSessionController.
Referenced by Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.HandleMonitorWakeup().
Task<CombinedTopicResponse> Tgstation.Server.Host.Components.Session.ISessionController.SendCommand (TopicParameters parameters, CancellationToken cancellationToken)
Sends a command to DreamDaemon through /world/Topic()
Parameters
parameters The TopicParameters to send.
cancellationToken The CancellationToken for the operation
Returns
A Task<TResult> resulting in the TopicResponse of /world/Topic()
Implemented in Tgstation.Server.Host.Components.Session.SessionController, and Tgstation.Server.Host.Components.Session.DeadSessionController.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleHeartbeat().
Task<bool> Tgstation.Server.Host.Components.Session.ISessionController.SetPort (ushort newPort, CancellationToken cancellatonToken)
Causes the world to start listening on a newPort
Parameters
newPort The port to change to
cancellatonToken The CancellationToken for the operation
Returns
A Task<TResult> resulting in if the operation succeeded, otherwise
Implemented in Tgstation.Server.Host.Components.Session.SessionController, and Tgstation.Server.Host.Components.Session.DeadSessionController.
Referenced by Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.HandleMonitorWakeup().
Task<bool> Tgstation.Server.Host.Components.Session.ISessionController.SetRebootState (RebootState newRebootState, CancellationToken cancellationToken)
Attempts to change the current RebootState to newRebootState
Parameters
newRebootState The new RebootState
cancellationToken The CancellationToken for the operation
Returns
A Task<TResult> resulting in if the operation succeeded, otherwise
Implemented in Tgstation.Server.Host.Components.Session.SessionController, and Tgstation.Server.Host.Components.Session.DeadSessionController.
Property Documentation
ApiValidationStatus Tgstation.Server.Host.Components.Session.ISessionController.ApiValidationStatus get
The DMAPI Session.ApiValidationStatus
Definition at line 33 of file ISessionController.cs.
bool Tgstation.Server.Host.Components.Session.ISessionController.ClosePortOnReboot get set
If the port should be rotated off when the world reboots
Definition at line 53 of file ISessionController.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.GetMonitoredServerTasks(), and Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.HandleMonitorWakeup().
Version Tgstation.Server.Host.Components.Session.ISessionController.DMApiVersion get
The DMAPI Version.
Definition at line 38 of file ISessionController.cs.
IDmbProvider Tgstation.Server.Host.Components.Session.ISessionController.Dmb get
The IDmbProvider being used
Definition at line 43 of file ISessionController.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.GetMonitoredServerTasks(), and Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.HandleMonitorWakeup().
bool Tgstation.Server.Host.Components.Session.ISessionController.IsPrimary get
If the IDmbProvider.PrimaryDirectory of Dmb is being used
Definition at line 23 of file ISessionController.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.HandleMonitorWakeup().
Task<LaunchResult> Tgstation.Server.Host.Components.Session.ISessionController.LaunchResult get
A Task that completes when DreamDaemon starts pumping the windows message queue after loading a .dmb or when it crashes
Definition at line 18 of file ISessionController.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.CheckLaunchResult().
Task Tgstation.Server.Host.Components.Session.ISessionController.OnPrime get
A Task that completes when the server calls /world/TgsInitializationsComplete()
Definition at line 68 of file ISessionController.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.GetMonitoredServerTasks().
Task Tgstation.Server.Host.Components.Session.ISessionController.OnReboot get
A Task that completes when the server calls /world/Reboot()
Definition at line 63 of file ISessionController.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.GetMonitoredServerTasks().
ushort Tgstation.Server.Host.Components.Session.ISessionController.Port get
The current port DreamDaemon is listening on
Definition at line 48 of file ISessionController.cs.
RebootState Tgstation.Server.Host.Components.Session.ISessionController.RebootState get
The current RebootState
Definition at line 58 of file ISessionController.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleHeartbeat(), and Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.HandleMonitorWakeup().
bool Tgstation.Server.Host.Components.Session.ISessionController.TerminationWasRequested get
If the DreamDaemon instance sent a
Definition at line 28 of file ISessionController.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.HandleMonitorWakeup().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Components/Session/ISessionController.cs