tgstation-server: TGS.Interface.Components.ITGSService Interface Reference
TGS.Interface.Components.ITGSService Interface Reference
Interface for managing the service
Public Member Functions
void PrepareForUpdate ()
Next stop of the service will not close DD and sets a flag for it to reattach once it restarts
ushort RemoteAccessPort ()
Get the port used for remote operation
string SetRemoteAccessPort (ushort port)
Set the port used for remote operation Requires a service restart to take effect
string Version ()
Retrieve's the service's version
bool SetPythonPath (string path)
Sets the path to the python 2.7 installation
string PythonPath ()
Gets the path to the python 2.7 installation
Detailed Description
Interface for managing the service
Definition at line 10 of file Service.cs.
Member Function Documentation
void TGS.Interface.Components.ITGSService.PrepareForUpdate ()
Next stop of the service will not close DD and sets a flag for it to reattach once it restarts
Implemented in TGS.Server.Server.
Referenced by TGS.CommandLine.Program.Main(), and TGS.Installer.UI.Main.TellServiceWereComingForThem().
string TGS.Interface.Components.ITGSService.PythonPath ()
Gets the path to the python 2.7 installation
Returns
The path to the python 2.7 installation
Implemented in TGS.Server.Server.
Referenced by TGS.Installer.UI.Main.AttemptMigrationOfNetSettings(), and TGS.CommandLine.ServicePythonPathCommand.Run().
ushort TGS.Interface.Components.ITGSService.RemoteAccessPort ()
Get the port used for remote operation
Returns
The port used for remote operation
Implemented in TGS.Server.Server.
Referenced by TGS.Installer.UI.Main.AttemptMigrationOfNetSettings(), and TGS.CommandLine.ServiceRemoteAccessPortCommand.Run().
bool TGS.Interface.Components.ITGSService.SetPythonPath (string path)
Sets the path to the python 2.7 installation
Parameters
path The new path
Returns
if the path exists, otherwise
Implemented in TGS.Server.Server.
Referenced by TGS.CommandLine.ServiceSetPythonPathCommand.Run().
string TGS.Interface.Components.ITGSService.SetRemoteAccessPort (ushort port)
Set the port used for remote operation Requires a service restart to take effect
Parameters
port The new port to use for remote operation
Returns
null on success, error message on failure
Implemented in TGS.Server.Server.
Referenced by TGS.CommandLine.ServiceSetRemoteAccessPortCommand.Run().
string TGS.Interface.Components.ITGSService.Version ()
Retrieve's the service's version
Returns
The service's version
Implemented in TGS.Server.Server.
The documentation for this interface was generated from the following file:
TGS.Interface/Components/Service.cs