tgstation-server: Tgstation.Server.Host.Components.Deployment.IDmbFactory Interface Reference
Tgstation.Server.Host.Components.Deployment.IDmbFactory Interface Reference
Factory for IDmbProviders
Public Member Functions
IDmbProvider LockNextDmb (int lockCount)
Gets the next IDmbProvider
Task< IDmbProvider > FromCompileJob (CompileJob compileJob, CancellationToken cancellationToken)
Gets a IDmbProvider for a given CompileJob
Task CleanUnusedCompileJobs (CompileJob exceptThisOne, CancellationToken cancellationToken)
Deletes all compile jobs that are inactive in the Game folder exceptThisOne
Properties
Task OnNewerDmb [get]
Get a Task that completes when the result of a call to LockNextDmb will be different than the previous call if any
bool DmbAvailable [get]
If LockNextDmb will succeed
Detailed Description
Factory for IDmbProviders
Definition at line 11 of file IDmbFactory.cs.
Member Function Documentation
CleanUnusedCompileJobs()
Task Tgstation.Server.Host.Components.Deployment.IDmbFactory.CleanUnusedCompileJobs (CompileJob exceptThisOne, CancellationToken cancellationToken)
Deletes all compile jobs that are inactive in the Game folder exceptThisOne
Parameters
exceptThisOne An optional compile job to not delete
cancellationToken The CancellationToken for the operation
Returns
A Task representing the running operation
Implemented in Tgstation.Server.Host.Components.Deployment.DmbFactory.
Referenced by Tgstation.Server.Host.Components.Instance.StartAsync().
FromCompileJob()
Task<IDmbProvider> Tgstation.Server.Host.Components.Deployment.IDmbFactory.FromCompileJob (CompileJob compileJob, CancellationToken cancellationToken)
Gets a IDmbProvider for a given CompileJob
Parameters
compileJob The CompileJob to make the IDmbProvider for
cancellationToken The CancellationToken for the operation
Returns
A Task<TResult> resulting in a new IDmbProvider representing the CompileJob on success, null on failure
Implemented in Tgstation.Server.Host.Components.Deployment.DmbFactory.
Referenced by Tgstation.Server.Host.Components.ReattachInfoHandler.Load().
LockNextDmb()
IDmbProvider Tgstation.Server.Host.Components.Deployment.IDmbFactory.LockNextDmb (int lockCount)
Gets the next IDmbProvider
Parameters
lockCount The amount of locks to give the resulting IDmbProvider. It's IDisposable.Dispose must be called this many times to properly clean the job
Returns
A new IDmbProvider
Implemented in Tgstation.Server.Host.Components.Deployment.DmbFactory.
Referenced by Tgstation.Server.Host.Components.Instance.LatestCompileJob().
Property Documentation
DmbAvailable
bool Tgstation.Server.Host.Components.Deployment.IDmbFactory.DmbAvailable get
If LockNextDmb will succeed
Definition at line 22 of file IDmbFactory.cs.
 { get; }
Referenced by Tgstation.Server.Host.Components.Instance.LatestCompileJob().
OnNewerDmb
Task Tgstation.Server.Host.Components.Deployment.IDmbFactory.OnNewerDmb get
Get a Task that completes when the result of a call to LockNextDmb will be different than the previous call if any
Returns
A Task representing the running operation
Definition at line 17 of file IDmbFactory.cs.
 { get; }
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Components/Deployment/IDmbFactory.cs