tgstation-server: TGS.Interface.Components.ITGDreamDaemon Interface Reference
TGS.Interface.Components.ITGDreamDaemon Interface Reference
Interface for managing the actual BYOND game server
Public Member Functions
DreamDaemonStatus DaemonStatus ()
Gets the status of DreamDaemon
string StatusString (bool includeMetaInfo)
Returns a human readable string of the current server status
string CanStart ()
Check if a call to Start will fail. Of course, be aware of race conditions with other interfaces
string Start ()
Starts the server if it isn't running
string Stop ()
Immediately kills the server
string Restart ()
Immediately kills and restarts the server
void RequestRestart ()
Restart the server after the currently running world reboots. Has no effect if the server isn't running
void RequestStop ()
Stop the server after the currently running world reboots. Has no effect if the server isn't running
DreamDaemonSecurity SecurityLevel ()
Get the configured (not necessarily running) security level
bool SetSecurityLevel (DreamDaemonSecurity level)
Sets the security level of the server. Requires server reboot to apply. Calls RequestRestart. Note that anything higher than Trusted will disable interop from DD
ushort Port ()
Get the configured port. Not necessarily the running port if it has since changed
void SetPort (ushort new_port)
Set the port to host DD on. Requires reboot to apply. Calls RequestRestart.
bool Autostart ()
Check if the watchdog will start when the service starts
void SetAutostart (bool on)
Set the autostart config
bool Webclient ()
Check if the BYOND webclient is currently enabled for the server
void SetWebclient (bool on)
Set the webclient config. Calls RequestRestart
bool ShutdownInProgress ()
Checks if a server stop has been requested
string WorldAnnounce (string msg)
Sends a message to everyone on the server
int PlayerCount ()
Returns the number of connected players. Requires game to use API version >= 3.1.0.1
Detailed Description
Interface for managing the actual BYOND game server
Definition at line 10 of file DreamDaemon.cs.
Member Function Documentation
bool TGS.Interface.Components.ITGDreamDaemon.Autostart ()
Check if the watchdog will start when the service starts
Returns
if autostart is enabled, otherwise
Implemented in TGS.Server.Instance.
string TGS.Interface.Components.ITGDreamDaemon.CanStart ()
Check if a call to Start will fail. Of course, be aware of race conditions with other interfaces
Returns
The error that would occur, otherwise
Implemented in TGS.Server.Instance.
DreamDaemonStatus TGS.Interface.Components.ITGDreamDaemon.DaemonStatus ()
Gets the status of DreamDaemon
Returns
The appropriate DreamDaemonStatus
Implemented in TGS.Server.Instance.
int TGS.Interface.Components.ITGDreamDaemon.PlayerCount ()
Returns the number of connected players. Requires game to use API version >= 3.1.0.1
Returns
The number of connected players or -1 on error
Implemented in TGS.Server.Instance.
ushort TGS.Interface.Components.ITGDreamDaemon.Port ()
Get the configured port. Not necessarily the running port if it has since changed
Returns
The configured port
Implemented in TGS.Server.Instance.
void TGS.Interface.Components.ITGDreamDaemon.RequestRestart ()
Restart the server after the currently running world reboots. Has no effect if the server isn't running
Implemented in TGS.Server.Instance.
Referenced by TGS.ControlPanel.ControlPanel.ServerGRestartButton_Click().
void TGS.Interface.Components.ITGDreamDaemon.RequestStop ()
Stop the server after the currently running world reboots. Has no effect if the server isn't running
Implemented in TGS.Server.Instance.
Referenced by TGS.ControlPanel.ControlPanel.ServerGStopButton_Checked().
string TGS.Interface.Components.ITGDreamDaemon.Restart ()
Immediately kills and restarts the server
Returns
on success or error message on failure
Implemented in TGS.Server.Instance.
Referenced by TGS.ControlPanel.ControlPanel.ServerRestartButton_Click().
DreamDaemonSecurity TGS.Interface.Components.ITGDreamDaemon.SecurityLevel ()
Get the configured (not necessarily running) security level
Returns
The configured (not necessarily running) DreamDaemonSecurity
Implemented in TGS.Server.Instance.
void TGS.Interface.Components.ITGDreamDaemon.SetAutostart (bool on)
Set the autostart config
Parameters
on to start the watchdog with the service, to disable that functionality
Implemented in TGS.Server.Instance.
Referenced by TGS.ControlPanel.ControlPanel.AutostartCheckbox_CheckedChanged().
void TGS.Interface.Components.ITGDreamDaemon.SetPort (ushort new_port)
Set the port to host DD on. Requires reboot to apply. Calls RequestRestart.
Parameters
new_port The new port
Implemented in TGS.Server.Instance.
Referenced by TGS.ControlPanel.ControlPanel.PortSelector_ValueChanged().
bool TGS.Interface.Components.ITGDreamDaemon.SetSecurityLevel (DreamDaemonSecurity level)
Sets the security level of the server. Requires server reboot to apply. Calls RequestRestart. Note that anything higher than Trusted will disable interop from DD
Parameters
level The new security level
Returns
if the change was immediately applied, otherwise and a call to RequestRestart was made
Implemented in TGS.Server.Instance.
Referenced by TGS.ControlPanel.ControlPanel.SecuritySelector_SelectedIndexChanged().
void TGS.Interface.Components.ITGDreamDaemon.SetWebclient (bool on)
Set the webclient config. Calls RequestRestart
Parameters
on to enable the byond webclient for the server, otherwise
Implemented in TGS.Server.Instance.
Referenced by TGS.ControlPanel.ControlPanel.WebclientCheckBox_CheckedChanged().
bool TGS.Interface.Components.ITGDreamDaemon.ShutdownInProgress ()
Checks if a server stop has been requested
Returns
if RequestStop has been called since the last server start, otherwise
Implemented in TGS.Server.Instance.
string TGS.Interface.Components.ITGDreamDaemon.Start ()
Starts the server if it isn't running
Returns
on success or error message on failure
Implemented in TGS.Server.Instance.
Referenced by TGS.ControlPanel.ControlPanel.ServerStartBGW_DoWork().
string TGS.Interface.Components.ITGDreamDaemon.StatusString (bool includeMetaInfo)
Returns a human readable string of the current server status
Parameters
includeMetaInfo If , the status will include the server's current visibility and security levels
Returns
A human readable string of the current server status
Implemented in TGS.Server.Instance.
string TGS.Interface.Components.ITGDreamDaemon.Stop ()
Immediately kills the server
Returns
on success or error message on failure
Implemented in TGS.Server.Instance.
Referenced by TGS.ControlPanel.ControlPanel.ServerStopButton_Click().
bool TGS.Interface.Components.ITGDreamDaemon.Webclient ()
Check if the BYOND webclient is currently enabled for the server
Returns
if the webclient is enabled, otherwise
Implemented in TGS.Server.Instance.
string TGS.Interface.Components.ITGDreamDaemon.WorldAnnounce (string msg)
Sends a message to everyone on the server
Parameters
msg The message to send
Returns
on success, error message on failure
Implemented in TGS.Server.Instance.
Referenced by TGS.ControlPanel.ControlPanel.WorldAnnounceButton_Click().
The documentation for this interface was generated from the following file:
TGS.Interface/Components/DreamDaemon.cs