tgstation-server: TGS.Server.IInstanceConfig Interface Reference
TGS.Server.IInstanceConfig Interface Reference
Configuration settings for a Instance
Public Member Functions
void Save ()
Saves the IInstanceConfig to it's Instance Directory
Properties
string Directory [get]
The Instance directory this IInstanceConfig is for
ulong Version [get]
Actual version of the IInstanceConfig. Migrated up via DeprecatedInstanceConfig
string Name [get, set]
The name of the Instance
bool Enabled [get, set]
If the Instance is active
string ProjectName [get, set]
The name of the .dme/.dmb the Instance uses
ushort Port [get, set]
The port the Instance runs on
DreamDaemonSecurity Security [get, set]
The DreamDaemonSecurity level for the Instance
bool Autostart [get, set]
Whether or not the Instance should immediately start DreamDaemon when activated
bool Webclient [get, set]
Whether or not DreamDaemon allows connections from webclients
string CommitterName [get, set]
Author and committer name for synchronize commits
string CommitterEmail [get, set]
Author and committer e-mail for synchronize commits
string ChatProviderData [get, set]
Encrypted serialized ChatSetupInfos
string ChatProviderEntropy [get, set]
Entropy for ChatProviderData
bool ReattachRequired [get, set]
If the Instance should reattach to a running DreamDaemon System.Diagnostics.Process
int ReattachProcessID [get, set]
The System.Diagnostics.Process.Id of the runnning DreamDaemon System.Diagnostics.Process
ushort ReattachPort [get, set]
The port the runnning DreamDaemon System.Diagnostics.Process was launched on
string ReattachCommsKey [get, set]
The serviceCommsKey the runnning DreamDaemon System.Diagnostics.Process was launched on
string ReattachAPIVersion [get, set]
The API version of the runnning DreamDaemon System.Diagnostics.Process
string AuthorizedUserGroupSID [get, set]
The user group allowed to use the Instance
ulong AutoUpdateInterval [get, set]
The auto update interval for the Instance
bool PushTestmergeCommits [get, set]
Whether or not testmerge commits are published to a temporary remote branch
int ServerStartupTimeout [get, set]
Time in seconds before DD is considered dead in the water
Detailed Description
Configuration settings for a Instance
Definition at line 10 of file InstanceConfig.cs.
Member Function Documentation
void TGS.Server.IInstanceConfig.Save ()
Saves the IInstanceConfig to it's Instance Directory
Implemented in TGS.Server.InstanceConfig.
Referenced by TGS.Installer.UI.Main.AttemptMigrationOfNetSettings(), TGS.Server.Server.CreateInstance(), and TGS.Server.Server.ImportInstance().
Property Documentation
string TGS.Server.IInstanceConfig.AuthorizedUserGroupSID get set
The user group allowed to use the Instance
Definition at line 104 of file InstanceConfig.cs.
bool TGS.Server.IInstanceConfig.Autostart get set
Whether or not the Instance should immediately start DreamDaemon when activated
Definition at line 50 of file InstanceConfig.cs.
ulong TGS.Server.IInstanceConfig.AutoUpdateInterval get set
The auto update interval for the Instance
Definition at line 109 of file InstanceConfig.cs.
string TGS.Server.IInstanceConfig.ChatProviderData get set
Encrypted serialized ChatSetupInfos
Definition at line 69 of file InstanceConfig.cs.
string TGS.Server.IInstanceConfig.ChatProviderEntropy get set
Entropy for ChatProviderData
Definition at line 74 of file InstanceConfig.cs.
string TGS.Server.IInstanceConfig.CommitterEmail get set
Author and committer e-mail for synchronize commits
Definition at line 64 of file InstanceConfig.cs.
string TGS.Server.IInstanceConfig.CommitterName get set
Author and committer name for synchronize commits
Definition at line 60 of file InstanceConfig.cs.
string TGS.Server.IInstanceConfig.Directory get
The Instance directory this IInstanceConfig is for
Definition at line 15 of file InstanceConfig.cs.
Referenced by TGS.Server.Server.SetupInstance(), and TGS.Server.Server.SetupOneInstance().
bool TGS.Server.IInstanceConfig.Enabled get set
If the Instance is active
Definition at line 30 of file InstanceConfig.cs.
Referenced by TGS.Server.Server.SetupInstance(), and TGS.Server.Server.SetupOneInstance().
string TGS.Server.IInstanceConfig.Name get set
The name of the Instance
Definition at line 25 of file InstanceConfig.cs.
Referenced by TGS.Server.Server.ImportInstance(), and TGS.Server.Server.SetupInstance().
ushort TGS.Server.IInstanceConfig.Port get set
The port the Instance runs on
Definition at line 40 of file InstanceConfig.cs.
string TGS.Server.IInstanceConfig.ProjectName get set
The name of the .dme/.dmb the Instance uses
Definition at line 35 of file InstanceConfig.cs.
bool TGS.Server.IInstanceConfig.PushTestmergeCommits get set
Whether or not testmerge commits are published to a temporary remote branch
Definition at line 114 of file InstanceConfig.cs.
string TGS.Server.IInstanceConfig.ReattachAPIVersion get set
The API version of the runnning DreamDaemon System.Diagnostics.Process
Definition at line 99 of file InstanceConfig.cs.
string TGS.Server.IInstanceConfig.ReattachCommsKey get set
The serviceCommsKey the runnning DreamDaemon System.Diagnostics.Process was launched on
Definition at line 94 of file InstanceConfig.cs.
ushort TGS.Server.IInstanceConfig.ReattachPort get set
The port the runnning DreamDaemon System.Diagnostics.Process was launched on
Definition at line 89 of file InstanceConfig.cs.
int TGS.Server.IInstanceConfig.ReattachProcessID get set
The System.Diagnostics.Process.Id of the runnning DreamDaemon System.Diagnostics.Process
Definition at line 84 of file InstanceConfig.cs.
bool TGS.Server.IInstanceConfig.ReattachRequired get set
If the Instance should reattach to a running DreamDaemon System.Diagnostics.Process
Definition at line 79 of file InstanceConfig.cs.
DreamDaemonSecurity TGS.Server.IInstanceConfig.Security get set
The DreamDaemonSecurity level for the Instance
Definition at line 45 of file InstanceConfig.cs.
int TGS.Server.IInstanceConfig.ServerStartupTimeout get set
Time in seconds before DD is considered dead in the water
Definition at line 119 of file InstanceConfig.cs.
ulong TGS.Server.IInstanceConfig.Version get
Actual version of the IInstanceConfig. Migrated up via DeprecatedInstanceConfig
Definition at line 20 of file InstanceConfig.cs.
bool TGS.Server.IInstanceConfig.Webclient get set
Whether or not DreamDaemon allows connections from webclients
Definition at line 55 of file InstanceConfig.cs.
The documentation for this interface was generated from the following file:
TGS.Server/InstanceConfig.cs