tgstation-server: TGServiceInterface.IInterface Interface Reference
TGServiceInterface.IInterface Interface Reference
Main for communicating the ITGSService
Public Member Functions
ConnectivityLevel ConnectToInstance (string instanceName=null, bool skipChecks=false)
Targets instanceName as the instance to use with GetComponent<T>. Closes all connections to any previous instance
bool VersionMismatch (out string errorMessage)
Returns if the IInterface interface being used to connect to a service does not have the same release version as the service
T GetComponent< T > ()
Returns the requested IInterface component for the instance InstanceName. This does not guarantee a successful connection. ChannelFactory<TChannel>s created this way are recycled for minimum latency and bandwidth usage
ITGSService GetService ()
Returns the ITGSService component for the service
ConnectivityLevel ConnectionStatus ()
Used to test if the ITGSService is avaiable on the target machine. Note that state can change at any time and any call into the may throw an exception because of communcation errors
ConnectivityLevel ConnectionStatus (out string error)
Used to test if the ITGSService is avaiable on the target machine. Note that state can change at any time and any call into the may throw an exception because of communcation errors
Properties
string InstanceName [get]
The name of the current instance in use. Defaults to
string HTTPSURL [get]
If this is set, we will try and connect to an HTTPS server running at this address
ushort HTTPSPort [get]
The port used to connect to the ITGSService
bool IsRemoteConnection [get]
Checks if the IInterface is setup for a remote connection
Detailed Description
Main for communicating the ITGSService
Definition at line 17 of file Interface.cs.
Member Function Documentation
ConnectivityLevel TGServiceInterface.IInterface.ConnectionStatus ()
Used to test if the ITGSService is avaiable on the target machine. Note that state can change at any time and any call into the may throw an exception because of communcation errors
Returns
on successful connection, error message string on failure
Implemented in TGServiceInterface.Interface.
Referenced by TGInstallerWrapper.Main.CheckForExistingVersion(), TGCommandLine.CLICommand.CLICommand(), TGServiceInterface.Interface.ConnectionStatus(), TGServiceInterface.Interface.ConnectToInstance(), TGCommandLine.Program.Main(), TGCommandLine.Program.RunCommandLine(), TGInstallerWrapper.Main.TellServiceWereComingForThem(), and TGControlPanel.Login.VerifyAndConnect().
ConnectivityLevel TGServiceInterface.IInterface.ConnectionStatus (out string error)
Used to test if the ITGSService is avaiable on the target machine. Note that state can change at any time and any call into the may throw an exception because of communcation errors
Parameters
error String of the error that prevented an elevated connectivity level
Returns
The apporopriate ConnectivityLevel
Implemented in TGServiceInterface.Interface.
ConnectivityLevel TGServiceInterface.IInterface.ConnectToInstance (string instanceName = null, bool skipChecks = false)
Targets instanceName as the instance to use with GetComponent<T>. Closes all connections to any previous instance
Parameters
instanceName The name of the instance to connect to
skipChecks If set to , skips the connectivity and authentication checks, sets InstanceName, and returns ConnectivityLevel.Connected
Returns
The apporopriate ConnectivityLevel
Implemented in TGServiceInterface.Interface.
Referenced by TGCommandLine.Program.CheckInstanceConnectivity(), TGCommandLine.CLICommand.CLICommand(), TGCommandLine.InstanceRootCommand.DoRun(), and TGControlPanel.Login.VerifyAndConnect().
T TGServiceInterface.IInterface.GetComponent< T > ()
Returns the requested IInterface component for the instance InstanceName. This does not guarantee a successful connection. ChannelFactory<TChannel>s created this way are recycled for minimum latency and bandwidth usage
Template Parameters
T The component to retrieve
Returns
The correct component
Implemented in TGServiceInterface.Interface.
ITGSService TGServiceInterface.IInterface.GetService ()
Returns the ITGSService component for the service
Returns
The ITGSService component for the service
Implemented in TGServiceInterface.Interface.
Referenced by TGInstallerWrapper.Main.CheckForExistingVersion(), TGServiceInterface.Interface.ConnectionStatus(), TGCommandLine.Program.RunCommandLine(), TGInstallerWrapper.Main.TellServiceWereComingForThem(), and TGServiceInterface.Interface.VersionMismatch().
bool TGServiceInterface.IInterface.VersionMismatch (out string errorMessage)
Returns if the IInterface interface being used to connect to a service does not have the same release version as the service
Parameters
errorMessage An error message to display to the user should this function return
Returns
if the IInterface interface being used to connect to a service does not have the same release version as the service
Implemented in TGServiceInterface.Interface.
Referenced by TGCommandLine.Program.Main(), and TGCommandLine.Program.RunCommandLine().
Property Documentation
ushort TGServiceInterface.IInterface.HTTPSPort get
The port used to connect to the ITGSService
Definition at line 32 of file Interface.cs.
Referenced by TGServiceInterface.Interface.CreateChannel< T >().
string TGServiceInterface.IInterface.HTTPSURL get
If this is set, we will try and connect to an HTTPS server running at this address
Definition at line 27 of file Interface.cs.
Referenced by TGServiceInterface.Interface.CreateChannel< T >().
string TGServiceInterface.IInterface.InstanceName get
The name of the current instance in use. Defaults to
Definition at line 22 of file Interface.cs.
Referenced by TGServiceInterface.Interface.ConnectToInstance(), TGControlPanel.ControlPanel.ControlPanel(), TGCommandLine.InstanceRootCommand.DoRun(), and TGServiceInterface.Interface.GetComponentImpl< T >().
bool TGServiceInterface.IInterface.IsRemoteConnection get
Checks if the IInterface is setup for a remote connection
Definition at line 37 of file Interface.cs.
Referenced by TGServiceInterface.Interface.CreateChannel< T >().
The documentation for this interface was generated from the following file:
TGServiceInterface/Interface.cs