tgstation-server: Tgstation.Server.Host.Transfer.IFileTransferTicketProvider Interface Reference
Tgstation.Server.Host.Transfer.IFileTransferTicketProvider Interface Reference
Service for temporarily storing files to be downloaded or uploaded.
Public Member Functions
FileTicketResponse CreateDownload (FileDownloadProvider fileDownloadProvider)
Create a FileTicketResponse for a download.
IFileUploadTicket CreateUpload (FileUploadStreamKind streamKind)
Create a IFileUploadTicket.
Detailed Description
Service for temporarily storing files to be downloaded or uploaded.
Definition at line 8 of file IFileTransferTicketProvider.cs.
Member Function Documentation
CreateDownload()
FileTicketResponse Tgstation.Server.Host.Transfer.IFileTransferTicketProvider.CreateDownload (FileDownloadProvider fileDownloadProvider)
Create a FileTicketResponse for a download.
Parameters
fileDownloadProvider The FileDownloadProvider.
Returns
A new FileTicketResponse for a download.
Implemented in Tgstation.Server.Host.Transfer.FileTransferService.
Referenced by Tgstation.Server.Host.Controllers.AdministrationController.GetLog(), and Tgstation.Server.Host.Components.StaticFiles.Configuration.Read().
CreateUpload()
IFileUploadTicket Tgstation.Server.Host.Transfer.IFileTransferTicketProvider.CreateUpload (FileUploadStreamKind streamKind)
Create a IFileUploadTicket.
Parameters
streamKind The FileUploadStreamKind to use.
Returns
A new IFileUploadTicket.
Implemented in Tgstation.Server.Host.Transfer.FileTransferService.
Referenced by Tgstation.Server.Host.Controllers.AdministrationController.AttemptInitiateUpdate(), and Tgstation.Server.Host.Controllers.EngineController.Update().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Transfer/IFileTransferTicketProvider.cs