tgstation-server: Tgstation.Server.Host.System.IProcessBase Interface Reference
Tgstation.Server.Host.System.IProcessBase Interface Reference
Represents process lifetime
Public Member Functions
void SetHighPriority ()
Set's the owned global::System.Diagnostics.Process.PriorityClass to global::System.Diagnostics.ProcessPriorityClass.AboveNormal
void Suspend ()
Suspends the process.
void Resume ()
Resumes the process.
Properties
Task< int > Lifetime [get]
The Task<TResult> resulting in the exit code of the process
Detailed Description
Represents process lifetime
Definition at line 9 of file IProcessBase.cs.
Member Function Documentation
void Tgstation.Server.Host.System.IProcessBase.Resume ()
Resumes the process.
Implemented in Tgstation.Server.Host.Components.Session.SessionController, Tgstation.Server.Host.System.Process, and Tgstation.Server.Host.Components.Session.DeadSessionController.
void Tgstation.Server.Host.System.IProcessBase.SetHighPriority ()
Set's the owned global::System.Diagnostics.Process.PriorityClass to global::System.Diagnostics.ProcessPriorityClass.AboveNormal
Implemented in Tgstation.Server.Host.Components.Session.SessionController, Tgstation.Server.Host.System.Process, and Tgstation.Server.Host.Components.Session.DeadSessionController.
Referenced by Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.HandleMonitorWakeup(), Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.InitControllers(), and Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.InitControllers().
void Tgstation.Server.Host.System.IProcessBase.Suspend ()
Suspends the process.
Implemented in Tgstation.Server.Host.Components.Session.SessionController, Tgstation.Server.Host.System.Process, and Tgstation.Server.Host.Components.Session.DeadSessionController.
Property Documentation
Task<int> Tgstation.Server.Host.System.IProcessBase.Lifetime get
The Task<TResult> resulting in the exit code of the process
Definition at line 14 of file IProcessBase.cs.
Referenced by Tgstation.Server.Host.Components.Watchdog.ExperimentalWatchdog.GetMonitoredServerTasks(), Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.InstallByond(), Tgstation.Server.Host.System.WindowsNetworkPromptReaper.RegisterProcess(), and Tgstation.Server.Host.Components.Session.SessionController.SessionController().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/System/IProcessBase.cs