tgstation-server: TGServiceInterface.ITGRepository Interface Reference
TGServiceInterface.ITGRepository Interface Reference
Interface for managing the code repository
Public Member Functions
bool OperationInProgress ()
If the repo is currently undergoing an operation
int CheckoutProgress ()
Gets the progress of repository operations, not all operations are supported
bool Exists ()
Check if the repository is valid, if not Setup(string, string) must be called
string Setup (string remote, string branch="master")
Deletes whatever may be left over and clones the repo at remote and checks out branch . Will move config and data dirs to a backup location if they exist. Runs asyncronously
string GetHead (bool useTracked, out string error)
Gets the sha of the current HEAD
string GetBranch (out string error)
Gets the name of the current branch
string GetRemote (out string error)
Gets the url of the current origin
string Checkout (string objectName)
Hard checks out the passed object name
string Update (bool reset)
Fetches the origin and merges it into the current branch
string Reset (bool tracked)
Runs git reset –hard
string MergePullRequest (int PRnumber)
Merges the target pull request into the current branch if the remote is a github repository
IList< PullRequestInfo > MergedPullRequests (out string error)
Get the currently merged pull requests. Note that switching branches will delete this list and switching back won't restore it
string GetCommitterName ()
Gets the name of the configured git committer
void SetCommitterName (string newName)
Sets the name of the configured git committer
string GetCommitterEmail ()
Gets the email of the configured git committer
void SetCommitterEmail (string newEmail)
Sets the email of the configured git committer
string GenerateChangelog (out string error)
Updates the html changelog
string SynchronizePush ()
Pushes the paths listed in TGS3.json to the currentl git remote. No other commit differences may exist for this function to succeed
bool SetPythonPath (string path)
Sets the path to the python 2.7 installation
string PythonPath ()
Gets the path to the python 2.7 installation
IDictionary< string, string > ListBackups (out string error)
List the tagged commits of the repo at which compiles took place
string UpdateTGS3Json ()
Updates the cached TGS3.json to the repo's version. Compiles will not succeed if these two to not match
void SetAutoUpdateInterval (ulong newInterval)
(De)Activate and set the interval for the automatic server updater
ulong AutoUpdateInterval ()
Get the current autoupdate interval
Detailed Description
Interface for managing the code repository
Definition at line 53 of file Repository.cs.
Member Function Documentation
ulong TGServiceInterface.ITGRepository.AutoUpdateInterval ()
Get the current autoupdate interval
Returns
The current auto update interval or 0 if it's disabled
Implemented in TGServerService.TGStationServer.
string TGServiceInterface.ITGRepository.Checkout (string objectName)
Hard checks out the passed object name
Parameters
objectName The branch, commit, or tag to checkout
Returns
on success, error message on failure
Implemented in TGServerService.TGStationServer.
int TGServiceInterface.ITGRepository.CheckoutProgress ()
Gets the progress of repository operations, not all operations are supported
Returns
A value between 0 and 100 inclusive representing the progress of the current operation or -1 if the operation cannot be monitored
Implemented in TGServerService.TGStationServer.
bool TGServiceInterface.ITGRepository.Exists ()
Check if the repository is valid, if not Setup(string, string) must be called
Returns
if the repository is valid, otherwise
Implemented in TGServerService.TGStationServer.
string TGServiceInterface.ITGRepository.GenerateChangelog (out string error)
Updates the html changelog
Parameters
error on success, error on failure
Returns
The output of the python script
Implemented in TGServerService.TGStationServer.
string TGServiceInterface.ITGRepository.GetBranch (out string error)
Gets the name of the current branch
Parameters
error on success, error message on failure
Returns
The name of the current branch on success, on failure
Implemented in TGServerService.TGStationServer.
string TGServiceInterface.ITGRepository.GetCommitterEmail ()
Gets the email of the configured git committer
Returns
The email of the configured git committer
Implemented in TGServerService.TGStationServer.
string TGServiceInterface.ITGRepository.GetCommitterName ()
Gets the name of the configured git committer
Returns
The name of the configured git committer
Implemented in TGServerService.TGStationServer.
string TGServiceInterface.ITGRepository.GetHead (bool useTracked, out string error)
Gets the sha of the current HEAD
Parameters
useTracked If set to true and HEAD is currently a branch, will instead return the sha of the tracked remote branch if it exists
error on success, error message on failure
Returns
The sha of the current HEAD on success, on failure
Implemented in TGServerService.TGStationServer.
string TGServiceInterface.ITGRepository.GetRemote (out string error)
Gets the url of the current origin
Parameters
error on success, error message on failure
Returns
The url of the current origin on success, on failure
Implemented in TGServerService.TGStationServer.
Referenced by TGControlPanel.Main.RepoApplyButton_Click().
IDictionary<string, string> TGServiceInterface.ITGRepository.ListBackups (out string error)
List the tagged commits of the repo at which compiles took place
Parameters
error on success, error message on failure
Returns
A IDictionary<TKey, TValue> of tag name -> commit on success, on failure
Implemented in TGServerService.TGStationServer.
IList<PullRequestInfo> TGServiceInterface.ITGRepository.MergedPullRequests (out string error)
Get the currently merged pull requests. Note that switching branches will delete this list and switching back won't restore it
Parameters
error on success, error message on failure
Returns
A IList<T> of PullRequestInfo
Implemented in TGServerService.TGStationServer.
string TGServiceInterface.ITGRepository.MergePullRequest (int PRnumber)
Merges the target pull request into the current branch if the remote is a github repository
Parameters
PRnumber The github pull request number in the remote repository
Returns
on success, error message on failure
Implemented in TGServerService.TGStationServer.
Referenced by TGCommandLine.TestmergeCommand.Run().
bool TGServiceInterface.ITGRepository.OperationInProgress ()
If the repo is currently undergoing an operation
Returns
if the repo is busy, otherwise
Implemented in TGServerService.TGStationServer.
Referenced by TGControlPanel.Main.RepoBusyCheck(), and TGCommandLine.RepoStatusCommand.Run().
string TGServiceInterface.ITGRepository.PythonPath ()
Gets the path to the python 2.7 installation
Returns
The path to the python 2.7 installation
Implemented in TGServerService.TGStationServer.
string TGServiceInterface.ITGRepository.Reset (bool tracked)
Runs git reset –hard
Parameters
tracked Changes command to git reset –hard origin/branch_name if
Returns
on success, error message on failure
Implemented in TGServerService.TGStationServer.
void TGServiceInterface.ITGRepository.SetAutoUpdateInterval (ulong newInterval)
(De)Activate and set the interval for the automatic server updater
Parameters
newInterval Interval to check for updates in minutes, disables if 0
Implemented in TGServerService.TGStationServer.
void TGServiceInterface.ITGRepository.SetCommitterEmail (string newEmail)
Sets the email of the configured git committer
Parameters
newEmail The email to set
Implemented in TGServerService.TGStationServer.
void TGServiceInterface.ITGRepository.SetCommitterName (string newName)
Sets the name of the configured git committer
Parameters
newName The name to set
Implemented in TGServerService.TGStationServer.
bool TGServiceInterface.ITGRepository.SetPythonPath (string path)
Sets the path to the python 2.7 installation
Parameters
path The new path
Returns
if the path exists, otherwise
Implemented in TGServerService.TGStationServer.
Referenced by TGControlPanel.Main.UpdatePythonPath().
string TGServiceInterface.ITGRepository.Setup (string remote, string branch = "master")
Deletes whatever may be left over and clones the repo at remote and checks out branch . Will move config and data dirs to a backup location if they exist. Runs asyncronously
Parameters
remote The address of the repo to clone. If ssh protocol is used, private_key.txt and public_key.txt must exist in the server RepoKey directory.
branch The branch of the repo to checkout
Returns
on success, error message on failure
Implemented in TGServerService.TGStationServer.
Referenced by TGControlPanel.Main.RepoBGW_DoWork().
string TGServiceInterface.ITGRepository.SynchronizePush ()
Pushes the paths listed in TGS3.json to the currentl git remote. No other commit differences may exist for this function to succeed
Returns
on success, error on failure
Implemented in TGServerService.TGStationServer.
string TGServiceInterface.ITGRepository.Update (bool reset)
Fetches the origin and merges it into the current branch
Parameters
reset If , the operation will perform a hard reset instead of a merge
Returns
on success, error message on failure
Implemented in TGServerService.TGStationServer.
Referenced by TGCommandLine.UpdateCommand.Run().
string TGServiceInterface.ITGRepository.UpdateTGS3Json ()
Updates the cached TGS3.json to the repo's version. Compiles will not succeed if these two to not match
Returns
on success, error message on failure
Implemented in TGServerService.TGStationServer.
The documentation for this interface was generated from the following file:
TGServiceInterface/Repository.cs