tgstation-server: Tgstation.Server.Host.Swarm.ISwarmService Interface Reference
Tgstation.Server.Host.Swarm.ISwarmService Interface Reference
Used for swarm operations. Functions may be no-op based on configuration.
Public Member Functions
Task< SwarmRegistrationResult > Initialize (CancellationToken cancellationToken)
Attempt to register with the swarm controller if not one, sets up the database otherwise.
Task Shutdown (CancellationToken cancellationToken)
Deregister with the swarm controller or put clients into querying state.
Task< bool > PrepareUpdate (Version version, CancellationToken cancellationToken)
Signal to the swarm that an update is requested.
Task< bool > CommitUpdate (CancellationToken cancellationToken)
Signal to the swarm that an update is ready to be applied.
ICollection< SwarmServerResponse > GetSwarmServers ()
Gets the list of SwarmServerResponses in the swarm, including the current one.
Task AbortUpdate (CancellationToken cancellationToken)
Abort an uncommitted update.
Detailed Description
Used for swarm operations. Functions may be no-op based on configuration.
Definition at line 13 of file ISwarmService.cs.
Member Function Documentation
AbortUpdate()
Task Tgstation.Server.Host.Swarm.ISwarmService.AbortUpdate (CancellationToken cancellationToken)
Abort an uncommitted update.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.Swarm.SwarmService.
Referenced by Tgstation.Server.Host.Server.ApplyUpdate().
CommitUpdate()
Task< bool > Tgstation.Server.Host.Swarm.ISwarmService.CommitUpdate (CancellationToken cancellationToken)
Signal to the swarm that an update is ready to be applied.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in true if the update should proceed, false otherwise.
Implemented in Tgstation.Server.Host.Swarm.SwarmService.
Referenced by Tgstation.Server.Host.Server.ApplyUpdate().
GetSwarmServers()
ICollection< SwarmServerResponse > Tgstation.Server.Host.Swarm.ISwarmService.GetSwarmServers ()
Gets the list of SwarmServerResponses in the swarm, including the current one.
Returns
A List<T> of SwarmServerResponses in the swarm. If the server is not part of a swarm, null will be returned.
Implemented in Tgstation.Server.Host.Swarm.SwarmService.
Referenced by Tgstation.Server.Host.Controllers.HomeController.Home().
Initialize()
Task< SwarmRegistrationResult > Tgstation.Server.Host.Swarm.ISwarmService.Initialize (CancellationToken cancellationToken)
Attempt to register with the swarm controller if not one, sets up the database otherwise.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the SwarmRegistrationResult.
Implemented in Tgstation.Server.Host.Swarm.SwarmService.
Referenced by Tgstation.Server.Host.Components.InstanceManager.InitializeSwarm().
PrepareUpdate()
Task< bool > Tgstation.Server.Host.Swarm.ISwarmService.PrepareUpdate (Version version, CancellationToken cancellationToken)
Signal to the swarm that an update is requested.
Parameters
version The Version to update to.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in true if the update should proceed, false otherwise.
Implemented in Tgstation.Server.Host.Swarm.SwarmService.
Referenced by Tgstation.Server.Host.Server.ApplyUpdate().
Shutdown()
Task Tgstation.Server.Host.Swarm.ISwarmService.Shutdown (CancellationToken cancellationToken)
Deregister with the swarm controller or put clients into querying state.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.Swarm.SwarmService.
Referenced by Tgstation.Server.Host.Components.InstanceManager.StopAsync().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Swarm/ISwarmService.cs