tgstation-server: Tgstation.Server.Host.Components.IInstanceOperations Interface Reference
Tgstation.Server.Host.Components.IInstanceOperations Interface Reference
Operations that can be performed on a given Models.Instance.
Public Member Functions
ValueTask OnlineInstance (Models.Instance metadata, CancellationToken cancellationToken)
Online an IInstance.
ValueTask OfflineInstance (Models.Instance metadata, User user, CancellationToken cancellationToken)
Offline an IInstance.
ValueTask MoveInstance (Models.Instance metadata, string oldPath, CancellationToken cancellationToken)
Move an IInstance.
Detailed Description
Operations that can be performed on a given Models.Instance.
Definition at line 11 of file IInstanceOperations.cs.
Member Function Documentation
MoveInstance()
ValueTask Tgstation.Server.Host.Components.IInstanceOperations.MoveInstance (Models.Instance metadata, string oldPath, CancellationToken cancellationToken)
Move an IInstance.
Parameters
metadata The Models.Instance of the desired IInstance with the updated path.
oldPath The old path of the IInstance. metadata will have this set on Api.Models.Instance.Path if the operation fails.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implemented in Tgstation.Server.Host.Components.InstanceManager.
Referenced by Tgstation.Server.Host.Controllers.InstanceController.Update().
OfflineInstance()
ValueTask Tgstation.Server.Host.Components.IInstanceOperations.OfflineInstance (Models.Instance metadata, User user, CancellationToken cancellationToken)
Offline an IInstance.
Parameters
metadata The Models.Instance of the desired IInstance.
user The User performing the operation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implemented in Tgstation.Server.Host.Components.InstanceManager.
Referenced by Tgstation.Server.Host.Controllers.InstanceController.Update().
OnlineInstance()
ValueTask Tgstation.Server.Host.Components.IInstanceOperations.OnlineInstance (Models.Instance metadata, CancellationToken cancellationToken)
Online an IInstance.
Parameters
metadata The Models.Instance of the desired IInstance.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implemented in Tgstation.Server.Host.Components.InstanceManager.
Referenced by Tgstation.Server.Host.Controllers.InstanceController.Update().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Components/IInstanceOperations.cs