tgstation-server: Tgstation.Server.Client.GraphQL.IGraphQLServerClient Interface Reference
Tgstation.Server.Client.GraphQL.IGraphQLServerClient Interface Reference
Wrapper for using a TGS IGraphQLClient.
Public Member Functions
ValueTask< IOperationResult< TResultData > > RunOperationAsync< TResultData > (Func< IGraphQLClient, ValueTask< IOperationResult< TResultData > > > operationExecutor, CancellationToken cancellationToken)
Runs a given operationExecutor . It may be invoked multiple times depending on the behavior of the IGraphQLServerClient if reauthentication is required.
ValueTask< IOperationResult< TResultData > > RunOperation< TResultData > (Func< IGraphQLClient, Task< IOperationResult< TResultData > > > operationExecutor, CancellationToken cancellationToken)
Runs a given operationExecutor . It may be invoked multiple times depending on the behavior of the IGraphQLServerClient if reauthentication is required.
ValueTask< IDisposable > Subscribe< TResultData > (Func< IGraphQLClient, IObservable< IOperationResult< TResultData > > > operationExecutor, IObserver< IOperationResult< TResultData > > observer, CancellationToken cancellationToken)
Subcribes to the GraphQL subscription indicated by operationExecutor .
Detailed Description
Wrapper for using a TGS IGraphQLClient.
Definition at line 12 of file IGraphQLServerClient.cs.
Member Function Documentation
RunOperation< TResultData >()
ValueTask< IOperationResult< TResultData > > Tgstation.Server.Client.GraphQL.IGraphQLServerClient.RunOperation< TResultData > (Func< IGraphQLClient, Task< IOperationResult< TResultData > > > operationExecutor, CancellationToken cancellationToken)
Runs a given operationExecutor . It may be invoked multiple times depending on the behavior of the IGraphQLServerClient if reauthentication is required.
Template Parameters
TResultData The Type of the IOperationResult<TResultData>'s IOperationResult<TResultData>.Data.
Parameters
operationExecutor A Func<T, TResult> which executes a single query on a given IGraphQLClient and returns a ValueTask<TResult> resulting in the TResultData IOperationResult<TResultData>.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IOperationResult<TResultData>.
Exceptions
AuthenticationException Thrown when automatic reauthentication fails.
Implemented in Tgstation.Server.Client.GraphQL.GraphQLServerClient.
Type Constraints
TResultData : class
References Tgstation.Server.Client.GraphQL.IGraphQLServerClient.RunOperation< TResultData >(), Tgstation.Server.Client.GraphQL.IGraphQLServerClient.RunOperationAsync< TResultData >(), and Tgstation.Server.Client.GraphQL.IGraphQLServerClient.Subscribe< TResultData >().
Referenced by Tgstation.Server.Client.GraphQL.IGraphQLServerClient.RunOperation< TResultData >().
RunOperationAsync< TResultData >()
ValueTask< IOperationResult< TResultData > > Tgstation.Server.Client.GraphQL.IGraphQLServerClient.RunOperationAsync< TResultData > (Func< IGraphQLClient, ValueTask< IOperationResult< TResultData > > > operationExecutor, CancellationToken cancellationToken)
Runs a given operationExecutor . It may be invoked multiple times depending on the behavior of the IGraphQLServerClient if reauthentication is required.
Template Parameters
TResultData The Type of the IOperationResult<TResultData>'s IOperationResult<TResultData>.Data.
Parameters
operationExecutor A Func<T, TResult> which executes a single query on a given IGraphQLClient and returns a ValueTask<TResult> resulting in the TResultData IOperationResult<TResultData>.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IOperationResult<TResultData>.
Exceptions
AuthenticationException Thrown when automatic reauthentication fails.
Implemented in Tgstation.Server.Client.GraphQL.GraphQLServerClient.
Type Constraints
TResultData : class
Referenced by Tgstation.Server.Client.GraphQL.IGraphQLServerClient.RunOperation< TResultData >().
Subscribe< TResultData >()
ValueTask< IDisposable > Tgstation.Server.Client.GraphQL.IGraphQLServerClient.Subscribe< TResultData > (Func< IGraphQLClient, IObservable< IOperationResult< TResultData > > > operationExecutor, IObserver< IOperationResult< TResultData > > observer, CancellationToken cancellationToken)
Subcribes to the GraphQL subscription indicated by operationExecutor .
Template Parameters
TResultData The Type of the IOperationResult<TResultData>'s IOperationResult<TResultData>.Data.
Parameters
operationExecutor A Func<T, TResult> which initiates a single subscription on a given IGraphQLClient and returns a ValueTask<TResult> resulting in the TResultData IOperationResult<TResultData> IObservable<T>.
observer The IObserver<T> for TResultData IOperationResult<TResultData>s.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IDisposable representing the lifetime of the subscription.
Implemented in Tgstation.Server.Client.GraphQL.GraphQLServerClient.
Type Constraints
TResultData : class
Referenced by Tgstation.Server.Client.GraphQL.IGraphQLServerClient.RunOperation< TResultData >().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Client.GraphQL/IGraphQLServerClient.cs