tgstation-server: Tgstation.Server.Host.Database.IDatabaseCollection< TModel > Interface Template Reference
Tgstation.Server.Host.Database.IDatabaseCollection< TModel > Interface Template Reference
Represents a database table.
Public Member Functions
void Add (TModel model)
Add a given model to the the working set.
void Remove (TModel model)
Remove a given model from the the working set.
void Attach (TModel model)
Attach a given model to the the working set.
void AddRange (IEnumerable< TModel > models)
Add a range of models to the IDatabaseCollection<TModel>.
void RemoveRange (IEnumerable< TModel > models)
Remove a range of models from the IDatabaseCollection<TModel>.
Task ForEachAsync (Action< TModel > action, CancellationToken cancellationToken)
Asyncronously run a given action on the IDatabaseCollection<TModel>.
Task< List< TModel > > ToListAsync (CancellationToken cancellationToken)
Retrieve all the TModel s in the table.
Properties
IEnumerable< TModel > Local [get]
An IEnumerable<T> of TModel s prioritizing in the working set.
Detailed Description
Represents a database table.
Template Parameters
TModel The type of model.
Definition at line 13 of file IDatabaseCollection.cs.
Member Function Documentation
Add()
void Tgstation.Server.Host.Database.IDatabaseCollection< TModel >.Add (TModel model)
Add a given model to the the working set.
Parameters
model The TModel model to add.
Implemented in Tgstation.Server.Host.Database.DatabaseCollection< TModel >.
Referenced by Tgstation.Server.Host.Components.Instance.CompileProcess(), Tgstation.Server.Host.Controllers.RepositoryController.LoadRevisionInformation(), and Tgstation.Server.Host.Database.DatabaseSeeder.SeedAdminUser().
AddRange()
void Tgstation.Server.Host.Database.IDatabaseCollection< TModel >.AddRange (IEnumerable< TModel > models)
Add a range of models to the IDatabaseCollection<TModel>.
Parameters
models An IEnumerable<T> of TModel s to add.
Implemented in Tgstation.Server.Host.Database.DatabaseCollection< TModel >.
Attach()
void Tgstation.Server.Host.Database.IDatabaseCollection< TModel >.Attach (TModel model)
Attach a given model to the the working set.
Parameters
model The TModel model to add.
Implemented in Tgstation.Server.Host.Database.DatabaseCollection< TModel >.
Referenced by Tgstation.Server.Host.Components.Instance.CompileProcess().
ForEachAsync()
Task Tgstation.Server.Host.Database.IDatabaseCollection< TModel >.ForEachAsync (Action< TModel > action, CancellationToken cancellationToken)
Asyncronously run a given action on the IDatabaseCollection<TModel>.
Parameters
action The Action<T> to run.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.Database.DatabaseCollection< TModel >.
Remove()
void Tgstation.Server.Host.Database.IDatabaseCollection< TModel >.Remove (TModel model)
Remove a given model from the the working set.
Parameters
model The TModel model to remove.
Implemented in Tgstation.Server.Host.Database.DatabaseCollection< TModel >.
Referenced by Tgstation.Server.Host.Components.Instance.CompileProcess().
RemoveRange()
void Tgstation.Server.Host.Database.IDatabaseCollection< TModel >.RemoveRange (IEnumerable< TModel > models)
Remove a range of models from the IDatabaseCollection<TModel>.
Parameters
models An IEnumerable<T> of TModel s to remove.
Implemented in Tgstation.Server.Host.Database.DatabaseCollection< TModel >.
ToListAsync()
Task<List<TModel> > Tgstation.Server.Host.Database.IDatabaseCollection< TModel >.ToListAsync (CancellationToken cancellationToken)
Retrieve all the TModel s in the table.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in a List<T> of all TModel in the table.
Implemented in Tgstation.Server.Host.Database.DatabaseCollection< TModel >.
Referenced by Tgstation.Server.Host.Components.Instance.CompileProcess(), and Tgstation.Server.Host.Database.DatabaseSeeder.SanitizeDatabase().
Property Documentation
Local
IEnumerable<TModel> Tgstation.Server.Host.Database.IDatabaseCollection< TModel >.Local get
An IEnumerable<T> of TModel s prioritizing in the working set.
Definition at line 18 of file IDatabaseCollection.cs.
 { get; }
Referenced by Tgstation.Server.Host.Controllers.RepositoryController.LoadRevisionInformation().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Database/IDatabaseCollection.cs