tgstation-server: Tgstation.Server.Host.Security.OAuth.IOAuthProviders Interface Reference
Tgstation.Server.Host.Security.OAuth.IOAuthProviders Interface Reference
Contains IOAuthValidators.
Public Member Functions
IOAuthValidator? GetValidator (OAuthProvider oAuthProvider)
Gets the IOAuthValidator for a given oAuthProvider .
Dictionary< OAuthProvider, OAuthProviderInfo > ProviderInfos ()
Gets a Dictionary<TKey, TValue> of the provider client IDs.
Detailed Description
Contains IOAuthValidators.
Definition at line 10 of file IOAuthProviders.cs.
Member Function Documentation
GetValidator()
IOAuthValidator? Tgstation.Server.Host.Security.OAuth.IOAuthProviders.GetValidator (OAuthProvider oAuthProvider)
Gets the IOAuthValidator for a given oAuthProvider .
Parameters
oAuthProvider The OAuthProvider to get the validator for.
Returns
The IOAuthValidator for oAuthProvider .
Implemented in Tgstation.Server.Host.Security.OAuth.OAuthProviders.
Referenced by Tgstation.Server.Host.Authority.LoginAuthority.AttemptLogin().
ProviderInfos()
Dictionary< OAuthProvider, OAuthProviderInfo > Tgstation.Server.Host.Security.OAuth.IOAuthProviders.ProviderInfos ()
Gets a Dictionary<TKey, TValue> of the provider client IDs.
Returns
A new Dictionary<TKey, TValue> of the active OAuthProviderInfos.
Implemented in Tgstation.Server.Host.Security.OAuth.OAuthProviders.
Referenced by Tgstation.Server.Host.GraphQL.Types.OAuth.OAuthProviderInfos.OAuthProviderInfos(), and Tgstation.Server.Host.Controllers.ApiRootController.ServerInfo().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Security/OAuth/IOAuthProviders.cs