tgstation-server: Tgstation.Server.Host.IO.IIOManager Interface Reference
Tgstation.Server.Host.IO.IIOManager Interface Reference
Interface for using filesystems.
Public Member Functions
IIOManager CreateResolverForSubdirectory (string subdirectoryPath)
Create a new IIOManager that resolves paths to the specified subdirectoryPath .
string ResolvePath ()
Retrieve the full path of the current working directory.
string ResolvePath (string path)
Retrieve the full path of some path given a relative path. Must be used before passing relative paths to other APIs. All other operations in this interface call this internally on given paths.
string GetFileName (string path)
Gets the file name portion of a path .
string GetFileNameWithoutExtension (string path)
Gets the file name portion of a path with.
bool PathContainsParentAccess (string path)
Check if a path contains the '..' parent directory accessor.
Task< bool > PathIsChildOf (string parentPath, string childPath, CancellationToken cancellationToken)
Check if a given parentPath is a parent of a given parentPath .
ValueTask CopyDirectory (IEnumerable< string >? ignore, Func< string, string, ValueTask >? postCopyCallback, string src, string dest, int? taskThrottle, CancellationToken cancellationToken)
Copies a directory from src to dest .
Task< bool > FileExists (string path, CancellationToken cancellationToken)
Check that the file at path exists.
Task< bool > DirectoryExists (string path, CancellationToken cancellationToken)
Check that the directory at path exists.
ValueTask< byte[]> ReadAllBytes (string path, CancellationToken cancellationToken)
Returns all the contents of a file at path as a byte array.
Task< IReadOnlyList< string > > GetDirectories (string path, CancellationToken cancellationToken)
Returns full directory names in a given path .
Task< IReadOnlyList< string > > GetFiles (string path, CancellationToken cancellationToken)
Returns full file names in a given path .
Stream CreateAsyncSequentialWriteStream (string path)
Creates an asynchronous FileStream for sequential writing.
Stream CreateAsyncReadStream (string path, bool sequential, bool shareWrite)
Creates an asynchronous FileStream for sequential reading.
ValueTask WriteAllBytes (string path, byte[] contents, CancellationToken cancellationToken)
Writes some contents to a file at path overwriting previous content.
ValueTask CopyFile (string src, string dest, CancellationToken cancellationToken)
Copy a file from src to dest .
string GetDirectoryName (string path)
Gets the directory portion of a given path .
Task< List< string > > GetFilesWithExtension (string path, string extension, bool recursive, CancellationToken cancellationToken)
Gets a list of files in path with the given extension .
Task DeleteFile (string path, CancellationToken cancellationToken)
Deletes a file at path .
Task CreateDirectory (string path, CancellationToken cancellationToken)
Create a directory at path .
Task DeleteDirectory (string path, CancellationToken cancellationToken)
Recursively delete a directory, removes and does not enter any symlinks encounterd.
string ConcatPath (params string[] paths)
Combines an array of strings into a path.
Task MoveFile (string source, string destination, CancellationToken cancellationToken)
Moves a file at source to destination .
Task MoveDirectory (string source, string destination, CancellationToken cancellationToken)
Moves a directory at source to destination .
Task ZipToDirectory (string path, Stream zipFile, CancellationToken cancellationToken)
Extract a set of zipFile to a given path .
Task< DateTimeOffset > GetLastModified (string path, CancellationToken cancellationToken)
Get the DateTimeOffset of when a given path was last modified.
Task< IDirectoryInfo > DirectoryInfo (string path, CancellationToken cancellationToken)
Gets a IDirectoryInfo for the given path .
bool IsPathRooted (string path)
Check if a given path is at the root level of the filesystem.
Properties
char DirectorySeparatorChar [get]
Gets the primary directory separator character.
char AltDirectorySeparatorChar [get]
Gets the alternative directory separator character.
Detailed Description
Interface for using filesystems.
Definition at line 13 of file IIOManager.cs.
Member Function Documentation
ConcatPath()
string Tgstation.Server.Host.IO.IIOManager.ConcatPath (params string[] paths)
Combines an array of strings into a path.
Parameters
paths The paths to combine.
Returns
The combined path.
Implemented in Tgstation.Server.Host.IO.DefaultIOManager.
Referenced by Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.AddDreamDaemonToFirewall(), Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.AdditionalCacheCleanFilePaths(), Tgstation.Server.Host.Components.Engine.ByondInstallerBase.CleanCache(), Tgstation.Server.Host.Components.StaticFiles.Configuration.CopyDMFilesTo(), Tgstation.Server.Host.Controllers.InstanceController.Create(), Tgstation.Server.Host.Controllers.InstanceController.Delete(), Tgstation.Server.Host.Components.Engine.EngineManager.DeleteVersion(), Tgstation.Server.Host.Core.VersionReportingService.ExecuteAsync(), Tgstation.Server.Host.Components.Deployment.DmbFactory.FromCompileJobInternal(), Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.GetExecutablePaths(), Tgstation.Server.Host.Configuration.FileLoggingConfiguration.GetFullLogDirectory(), Tgstation.Server.Host.Controllers.AdministrationController.GetLog(), Tgstation.Server.Host.Extensions.IOManagerExtensions.GetPathInLocalDirectory(), Tgstation.Server.Host.System.PosixProcessFeatures.GetPotentialGCorePaths(), Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.Install(), Tgstation.Server.Host.Components.Engine.PosixByondInstaller.Install(), Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.InstallDirectX(), Tgstation.Server.Host.Components.Engine.EngineManager.InstallVersionFiles(), Tgstation.Server.Host.Components.Session.SessionControllerFactory.LaunchNew(), Tgstation.Server.Host.Controllers.AdministrationController.ListLogs(), Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.MirrorDirectoryImpl(), Tgstation.Server.Host.Components.InstanceManager.MoveInstance(), Tgstation.Server.Host.Components.Engine.PosixByondInstaller.PosixByondInstaller(), Tgstation.Server.Host.Components.Deployment.DreamMaker.RunCompileJob(), Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.SetNoPromptTrusted(), Tgstation.Server.Host.Components.Engine.EngineManager.StartAsync(), Tgstation.Server.Host.Components.StaticFiles.Configuration.SymlinkStaticFilesTo(), Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.TrustDmbPath(), Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.UpgradeInstallation(), Tgstation.Server.Host.Setup.SetupWizard.ValidateNonExistantSqliteDBName(), and Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.WindowsByondInstaller().
CopyDirectory()
ValueTask Tgstation.Server.Host.IO.IIOManager.CopyDirectory (IEnumerable< string >? ignore, Func< string, string, ValueTask >? postCopyCallback, string src, string dest, int? taskThrottle, CancellationToken cancellationToken)
Copies a directory from src to dest .
Parameters
ignore Files and folders to ignore at the root level.
postCopyCallback The optional callback called for each source/dest file pair post copy.
src The source directory path.
dest The destination directory path.
taskThrottle The optional maximum number of simultaneous tasks allowed to execute.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implemented in Tgstation.Server.Host.IO.DefaultIOManager.
Referenced by Tgstation.Server.Host.Components.StaticFiles.Configuration.CopyDMFilesTo(), and Tgstation.Server.Host.Components.Repository.Repository.CopyTo().
CopyFile()
ValueTask Tgstation.Server.Host.IO.IIOManager.CopyFile (string src, string dest, CancellationToken cancellationToken)
Copy a file from src to dest .
Parameters
src The source file to copy.
dest The destination path.
cancellationToken A CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implemented in Tgstation.Server.Host.IO.DefaultIOManager.
CreateAsyncReadStream()
Stream Tgstation.Server.Host.IO.IIOManager.CreateAsyncReadStream (string path, bool sequential, bool shareWrite)
Creates an asynchronous FileStream for sequential reading.
Parameters
path The path of the file to write, will be truncated.
sequential If the sequential read flag should be added.
shareWrite If FileShare.Write should be used.
Returns
The open Stream.
Implemented in Tgstation.Server.Host.IO.DefaultIOManager.
Referenced by Tgstation.Server.Host.Transfer.FileTransferService.RetrieveDownloadStream(), and Tgstation.Server.Host.System.PosixProcessFeatures.StartAsync().
CreateAsyncSequentialWriteStream()
Stream Tgstation.Server.Host.IO.IIOManager.CreateAsyncSequentialWriteStream (string path)
Creates an asynchronous FileStream for sequential writing.
Parameters
path The path of the file to write, will be truncated.
Returns
The open Stream.
Implemented in Tgstation.Server.Host.IO.DefaultIOManager.
Referenced by Tgstation.Server.Host.System.ProcessExecutor.ConsumeReaders().
CreateDirectory()
Task Tgstation.Server.Host.IO.IIOManager.CreateDirectory (string path, CancellationToken cancellationToken)
Create a directory at path .
Parameters
path The path of the directory to create.
cancellationToken A CancellationToken for the operation.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.IO.DefaultIOManager.
Referenced by Tgstation.Server.Host.Components.Engine.ByondInstallerBase.CleanCache(), Tgstation.Server.Host.Components.Deployment.DmbFactory.CleanUnusedCompileJobs(), Tgstation.Server.Host.Controllers.InstanceController.Create(), Tgstation.Server.Host.Core.VersionReportingService.ExecuteAsync(), Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.Install(), Tgstation.Server.Host.Components.Engine.EngineManager.InstallVersionFiles(), Tgstation.Server.Host.Components.Session.SessionControllerFactory.LaunchNew(), Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.MirrorDirectoryImpl(), Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.SetNoPromptTrusted(), Tgstation.Server.Host.Components.Engine.EngineManager.StartAsync(), Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.TrustDmbPath(), and Tgstation.Server.Host.Setup.SetupWizard.ValidateNonExistantSqliteDBName().
CreateResolverForSubdirectory()
IIOManager Tgstation.Server.Host.IO.IIOManager.CreateResolverForSubdirectory (string subdirectoryPath)
Create a new IIOManager that resolves paths to the specified subdirectoryPath .
Parameters
subdirectoryPath A relative or absolute path that the new IIOManager will resolve as its current directory.
Returns
A new IIOManager.
Implemented in Tgstation.Server.Host.IO.DefaultIOManager.
Referenced by Tgstation.Server.Host.Components.Engine.ByondInstallerBase.CreateInstallation(), and Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.CreateInstallation().
DeleteDirectory()
Task Tgstation.Server.Host.IO.IIOManager.DeleteDirectory (string path, CancellationToken cancellationToken)
Recursively delete a directory, removes and does not enter any symlinks encounterd.
Parameters
path The path to the directory to delete.
cancellationToken A CancellationToken for the operation.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.IO.DefaultIOManager.
Referenced by Tgstation.Server.Host.Components.Engine.EngineManager.AssertAndLockVersion(), Tgstation.Server.Host.Components.Engine.ByondInstallerBase.CleanCache(), Tgstation.Server.Host.Components.Repository.RepositoryManager.CloneRepository(), Tgstation.Server.Host.Components.Deployment.DmbFactory.DeleteCompileJobContent(), Tgstation.Server.Host.Components.Repository.RepositoryManager.DeleteRepository(), Tgstation.Server.Host.Components.Engine.EngineManager.DeleteVersion(), Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.DisposeAsync(), Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.DoSwap(), Tgstation.Server.Host.Components.Deployment.SymlinkDmbProvider.DoSwap(), Tgstation.Server.Host.Core.ServerUpdater.ExecuteUpdate(), Tgstation.Server.Host.Components.Engine.WindowsOpenDreamInstaller.HandleExtremelyLongPathOperation(), Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.Install(), Tgstation.Server.Host.Components.Engine.EngineManager.InstallVersionFiles(), Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.MirrorSourceDirectory(), Tgstation.Server.Host.Components.InstanceManager.MoveInstance(), Tgstation.Server.Host.Core.ServerUpdater.PrepareUpdateClearStagingAndBufferStream(), Tgstation.Server.Host.Components.Engine.EngineManager.StartAsync(), Tgstation.Server.Host.Components.StaticFiles.Configuration.SymlinkStaticFilesTo(), and Tgstation.Server.Host.Setup.SetupWizard.ValidateNonExistantSqliteDBName().
DeleteFile()
Task Tgstation.Server.Host.IO.IIOManager.DeleteFile (string path, CancellationToken cancellationToken)
Deletes a file at path .
Parameters
path The path of the file to delete.
cancellationToken A CancellationToken for the operation.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.IO.DefaultIOManager.
Referenced by Tgstation.Server.Host.Components.Engine.ByondInstallerBase.CleanCache(), Tgstation.Server.Host.Controllers.InstanceController.Create(), Tgstation.Server.Host.Controllers.InstanceController.Delete(), Tgstation.Server.Host.Components.Engine.EngineManager.DeleteVersion(), Tgstation.Server.Host.Components.Deployment.SymlinkDmbProvider.DoSwap(), Tgstation.Server.Host.Components.Session.SessionControllerFactory.LogDDOutput(), Tgstation.Server.Host.Components.Engine.EngineManager.StartAsync(), Tgstation.Server.Host.Components.StaticFiles.Configuration.SymlinkStaticFilesTo(), Tgstation.Server.Host.Setup.SetupWizard.TestDatabaseConnection(), and Tgstation.Server.Host.Setup.SetupWizard.ValidateNonExistantSqliteDBName().
DirectoryExists()
Task< bool > Tgstation.Server.Host.IO.IIOManager.DirectoryExists (string path, CancellationToken cancellationToken)
Check that the directory at path exists.
Parameters
path The directory to check for existence.
cancellationToken The CancellationToken for the operation.
Returns
A Task resulting in true if the directory at path exists, false otherwise.
Implemented in Tgstation.Server.Host.IO.DefaultIOManager.
Referenced by Tgstation.Server.Host.Components.Repository.RepositoryManager.CloneRepository(), Tgstation.Server.Host.Controllers.InstanceController.Create(), Tgstation.Server.Host.Controllers.InstanceController.Delete(), Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.Install(), Tgstation.Server.Host.Components.StaticFiles.Configuration.SymlinkStaticFilesTo(), Tgstation.Server.Host.Controllers.InstanceController.Update(), and Tgstation.Server.Host.Setup.SetupWizard.ValidateNonExistantSqliteDBName().
DirectoryInfo()
Task< IDirectoryInfo > Tgstation.Server.Host.IO.IIOManager.DirectoryInfo (string path, CancellationToken cancellationToken)
Gets a IDirectoryInfo for the given path .
Parameters
path The path to get IDirectoryInfo for.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the IDirectoryInfo of the path .
Implemented in Tgstation.Server.Host.IO.DefaultIOManager.
Referenced by Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.MirrorSourceDirectory().
FileExists()
Task< bool > Tgstation.Server.Host.IO.IIOManager.FileExists (string path, CancellationToken cancellationToken)
Check that the file at path exists.
Parameters
path The file to check for existence.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in true if the file at path exists, false otherwise.
Implemented in Tgstation.Server.Host.IO.DefaultIOManager.
Referenced by Tgstation.Server.Host.Components.StaticFiles.Configuration.CopyDMFilesTo(), Tgstation.Server.Host.Controllers.InstanceController.Create(), Tgstation.Server.Host.System.PosixProcessFeatures.CreateDump(), Tgstation.Server.Host.Core.VersionReportingService.ExecuteAsync(), Tgstation.Server.Host.Components.Deployment.DmbFactory.FromCompileJobInternal(), Tgstation.Server.Host.System.DotnetHelper.GetDotnetPath(), Tgstation.Server.Host.Components.Engine.EngineInstallationBase.LoadEnv(), Tgstation.Server.Host.Components.Deployment.DreamMaker.RunCompileJob(), Tgstation.Server.Host.Components.Engine.EngineManager.StartAsync(), Tgstation.Server.Host.Components.StaticFiles.Configuration.SymlinkStaticFilesTo(), Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.TrustDmbPath(), Tgstation.Server.Host.Controllers.InstanceController.Update(), and Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.UpgradeInstallation().
GetDirectories()
Task< IReadOnlyList< string > > Tgstation.Server.Host.IO.IIOManager.GetDirectories (string path, CancellationToken cancellationToken)
Returns full directory names in a given path .
Parameters
path The path to search for directories.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the directories in path .
Implemented in Tgstation.Server.Host.IO.DefaultIOManager.
Referenced by Tgstation.Server.Host.Components.Deployment.DmbFactory.CleanUnusedCompileJobs(), Tgstation.Server.Host.Controllers.InstanceController.Create(), Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.Install(), Tgstation.Server.Host.Components.Engine.EngineManager.StartAsync(), and Tgstation.Server.Host.Components.StaticFiles.Configuration.SymlinkStaticFilesTo().
GetDirectoryName()
string Tgstation.Server.Host.IO.IIOManager.GetDirectoryName (string path)
Gets the directory portion of a given path .
Parameters
path A path to check.
Returns
The directory portion of the given path .
Exceptions
InvalidOperationException If path is rooted.
Implemented in Tgstation.Server.Host.IO.DefaultIOManager.
Referenced by Tgstation.Server.Host.ServerFactory.CreateServer(), and Tgstation.Server.Host.Setup.SetupWizard.ValidateNonExistantSqliteDBName().
GetFileName()
string Tgstation.Server.Host.IO.IIOManager.GetFileName (string path)
Gets the file name portion of a path .
Parameters
path The path to get the file name of.
Returns
The file name portion of path .
Implemented in Tgstation.Server.Host.IO.DefaultIOManager.
Referenced by Tgstation.Server.Host.Components.Deployment.DmbFactory.CleanUnusedCompileJobs(), Tgstation.Server.Host.Controllers.AdministrationController.GetLog(), Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.Install(), and Tgstation.Server.Host.Controllers.AdministrationController.ListLogs().
GetFileNameWithoutExtension()
string Tgstation.Server.Host.IO.IIOManager.GetFileNameWithoutExtension (string path)
Gets the file name portion of a path with.
Parameters
path The path to get the file name of.
Returns
The file name portion of path .
Implemented in Tgstation.Server.Host.IO.DefaultIOManager.
GetFiles()
Task< IReadOnlyList< string > > Tgstation.Server.Host.IO.IIOManager.GetFiles (string path, CancellationToken cancellationToken)
Returns full file names in a given path .
Parameters
path The path to search for files.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the files in path .
Implemented in Tgstation.Server.Host.IO.DefaultIOManager.
Referenced by Tgstation.Server.Host.Controllers.InstanceController.Create(), Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.Install(), Tgstation.Server.Host.Controllers.AdministrationController.ListLogs(), and Tgstation.Server.Host.Components.StaticFiles.Configuration.SymlinkStaticFilesTo().
GetFilesWithExtension()
Task< List< string > > Tgstation.Server.Host.IO.IIOManager.GetFilesWithExtension (string path, string extension, bool recursive, CancellationToken cancellationToken)
Gets a list of files in path with the given extension .
Parameters
path The directory which contains the files.
extension The extension to look for without the preceeding ".".
recursive If the search should be recursive.
cancellationToken A CancellationToken for the operation.
Returns
A Task resulting in a list of paths to files in path with the given extension .
Implemented in Tgstation.Server.Host.IO.DefaultIOManager.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.RunCompileJob().
GetLastModified()
Task< DateTimeOffset > Tgstation.Server.Host.IO.IIOManager.GetLastModified (string path, CancellationToken cancellationToken)
Get the DateTimeOffset of when a given path was last modified.
Parameters
path The path to get metadata for.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the DateTimeOffset of when the file was last modified.
Implemented in Tgstation.Server.Host.IO.DefaultIOManager.
Referenced by Tgstation.Server.Host.Controllers.AdministrationController.GetLog().
IsPathRooted()
bool Tgstation.Server.Host.IO.IIOManager.IsPathRooted (string path)
Check if a given path is at the root level of the filesystem.
Parameters
path The path to check.
Returns
true if the path is rooted, false otherwise.
Implemented in Tgstation.Server.Host.IO.DefaultIOManager.
Referenced by Tgstation.Server.Host.Configuration.GeneralConfiguration.CheckCompatibility(), and Tgstation.Server.Host.Setup.SetupWizard.ValidateNonExistantSqliteDBName().
MoveDirectory()
Task Tgstation.Server.Host.IO.IIOManager.MoveDirectory (string source, string destination, CancellationToken cancellationToken)
Moves a directory at source to destination .
Parameters
source The source directory path.
destination The destination path.
cancellationToken A CancellationToken for the operation.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.IO.DefaultIOManager.
Referenced by Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.DoSwap(), Tgstation.Server.Host.Core.ServerUpdater.ExecuteUpdate(), Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.Install(), and Tgstation.Server.Host.Components.InstanceManager.MoveInstance().
MoveFile()
Task Tgstation.Server.Host.IO.IIOManager.MoveFile (string source, string destination, CancellationToken cancellationToken)
Moves a file at source to destination .
Parameters
source The source file path.
destination The destination path.
cancellationToken A CancellationToken for the operation.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.IO.DefaultIOManager.
Referenced by Tgstation.Server.Host.System.PosixProcessFeatures.CreateDump(), and Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.Install().
PathContainsParentAccess()
bool Tgstation.Server.Host.IO.IIOManager.PathContainsParentAccess (string path)
Check if a path contains the '..' parent directory accessor.
Parameters
path The path to check.
Returns
true if path contains a '..' accessor, false otherwise.
Implemented in Tgstation.Server.Host.IO.DefaultIOManager.
Referenced by Tgstation.Server.Host.Controllers.ConfigurationController.ForbidDueToModeConflicts().
PathIsChildOf()
Task< bool > Tgstation.Server.Host.IO.IIOManager.PathIsChildOf (string parentPath, string childPath, CancellationToken cancellationToken)
Check if a given parentPath is a parent of a given parentPath .
Parameters
parentPath The parent path.
childPath The child path.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in true if childPath is a child of parentPath or they are equivalent.
Implemented in Tgstation.Server.Host.IO.DefaultIOManager.
Referenced by Tgstation.Server.Host.Controllers.InstanceController.Create(), and Tgstation.Server.Host.Components.Deployment.DreamMaker.RunCompileJob().
ReadAllBytes()
ValueTask< byte[]> Tgstation.Server.Host.IO.IIOManager.ReadAllBytes (string path, CancellationToken cancellationToken)
Returns all the contents of a file at path as a byte array.
Parameters
path The path of the file to read.
cancellationToken A CancellationToken for the operation.
Returns
A ValueTask that results in the contents of a file at path .
This function will fail to read files from the /proc filesystem on Linux.
Implemented in Tgstation.Server.Host.IO.DefaultIOManager.
Referenced by Tgstation.Server.Host.Core.VersionReportingService.ExecuteAsync(), Tgstation.Server.Host.Components.Engine.EngineInstallationBase.LoadEnv(), Tgstation.Server.Host.Components.Session.SessionControllerFactory.LogDDOutput(), Tgstation.Server.Host.Components.Engine.EngineManager.StartAsync(), and Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.TrustDmbPath().
ResolvePath() [1/2]
string Tgstation.Server.Host.IO.IIOManager.ResolvePath ()
Retrieve the full path of the current working directory.
Returns
The full path of the current working directory.
Implemented in Tgstation.Server.Host.IO.DefaultIOManager.
Referenced by Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.AddDreamDaemonToFirewall(), Tgstation.Server.Host.Components.Engine.EngineManager.AssertAndLockVersion(), Tgstation.Server.Host.Components.Deployment.DmbFactory.CleanUnusedCompileJobs(), Tgstation.Server.Host.Components.Repository.RepositoryManager.CloneRepository(), Tgstation.Server.Host.Components.Repository.Repository.CopyTo(), Tgstation.Server.Host.ServerFactory.CreateServer(), Tgstation.Server.Host.Components.Repository.RepositoryManager.DeleteRepository(), Tgstation.Server.Host.Components.Deployment.SymlinkDmbProvider.DoSwap(), Tgstation.Server.Host.Core.VersionReportingService.ExecuteAsync(), Tgstation.Server.Host.Components.Engine.PosixByondInstaller.Install(), Tgstation.Server.Host.Components.Engine.EngineManager.InstallVersionFiles(), Tgstation.Server.Host.Components.Session.SessionControllerFactory.LaunchNew(), Tgstation.Server.Host.Components.Repository.RepositoryManager.LoadRepository(), Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.MirrorSourceDirectory(), Tgstation.Server.Host.Controllers.InstanceController.NormalizePath(), Tgstation.Server.Host.Components.Engine.PosixByondInstaller.PosixByondInstaller(), Tgstation.Server.Host.Components.Deployment.DreamMaker.RunCompileJob(), Tgstation.Server.Host.Components.Engine.EngineManager.StartAsync(), Tgstation.Server.Host.Components.StaticFiles.Configuration.SymlinkStaticFilesTo(), Tgstation.Server.Host.Setup.SetupWizard.ValidateNonExistantSqliteDBName(), and Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.WindowsByondInstaller().
ResolvePath() [2/2]
string Tgstation.Server.Host.IO.IIOManager.ResolvePath (string path)
Retrieve the full path of some path given a relative path. Must be used before passing relative paths to other APIs. All other operations in this interface call this internally on given paths.
Parameters
path Some path to retrieve the full path of.
Returns
path as a full path.
Implemented in Tgstation.Server.Host.IO.DefaultIOManager, and Tgstation.Server.Host.IO.ResolvingIOManager.
WriteAllBytes()
ValueTask Tgstation.Server.Host.IO.IIOManager.WriteAllBytes (string path, byte[] contents, CancellationToken cancellationToken)
Writes some contents to a file at path overwriting previous content.
Parameters
path The path of the file to write.
contents The contents of the file.
cancellationToken A CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implemented in Tgstation.Server.Host.IO.DefaultIOManager.
Referenced by Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.AddDreamDaemonToFirewall(), Tgstation.Server.Host.System.PosixProcessFeatures.AdjustOutOfMemoryScore(), Tgstation.Server.Host.Components.Engine.EngineManager.ChangeVersion(), Tgstation.Server.Host.Controllers.InstanceController.Delete(), Tgstation.Server.Host.Server.DumpGraphQLSchemaIfRequested(), Tgstation.Server.Host.Core.VersionReportingService.ExecuteAsync(), Tgstation.Server.Host.Components.Engine.PosixByondInstaller.Install(), Tgstation.Server.Host.Components.Engine.EngineManager.InstallVersionFiles(), Tgstation.Server.Host.Components.InstanceManager.MoveInstance(), Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.SetNoPromptTrusted(), Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.TrustDmbPath(), and Tgstation.Server.Host.Setup.SetupWizard.ValidateNonExistantSqliteDBName().
ZipToDirectory()
Task Tgstation.Server.Host.IO.IIOManager.ZipToDirectory (string path, Stream zipFile, CancellationToken cancellationToken)
Extract a set of zipFile to a given path .
Parameters
path The path to unzip to.
zipFile The Stream of the global::System.IO.Compression.ZipArchive. Must have Stream.CanSeek set to true. Will be read completely and left open. Stream.Position will be indeterminate.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.IO.DefaultIOManager.
Referenced by Tgstation.Server.Host.Core.ServerUpdater.ExecuteUpdate().
Property Documentation
AltDirectorySeparatorChar
char Tgstation.Server.Host.IO.IIOManager.AltDirectorySeparatorChar get
Gets the alternative directory separator character.
Implemented in Tgstation.Server.Host.IO.DefaultIOManager.
Definition at line 23 of file IIOManager.cs.
{ get; }
DirectorySeparatorChar
char Tgstation.Server.Host.IO.IIOManager.DirectorySeparatorChar get
Gets the primary directory separator character.
Implemented in Tgstation.Server.Host.IO.DefaultIOManager.
Definition at line 18 of file IIOManager.cs.
{ get; }
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/IO/IIOManager.cs