tgstation-server: Tgstation.Server.Host.System.IProcessFeatures Interface Reference
Tgstation.Server.Host.System.IProcessFeatures Interface Reference
Abstraction for suspending and resuming processes.
Public Member Functions
string GetExecutingUsername (global::System.Diagnostics.Process process)
Get the name of the user executing a given process .
void SuspendProcess (global::System.Diagnostics.Process process)
Suspend a given process .
void ResumeProcess (global::System.Diagnostics.Process process)
Resume a given suspended global::System.Diagnostics.Process.
ValueTask CreateDump (global::System.Diagnostics.Process process, string outputFile, bool minidump, CancellationToken cancellationToken)
Create a dump file for a given process .
ValueTask< int > HandleProcessStart (global::System.Diagnostics.Process process, CancellationToken cancellationToken)
Run events on starting a process.
Detailed Description
Abstraction for suspending and resuming processes.
Definition at line 9 of file IProcessFeatures.cs.
Member Function Documentation
CreateDump()
ValueTask Tgstation.Server.Host.System.IProcessFeatures.CreateDump (global::System.Diagnostics.Process process, string outputFile, bool minidump, CancellationToken cancellationToken)
Create a dump file for a given process .
Parameters
process The global::System.Diagnostics.Process to dump.
outputFile The full path to the output file.
minidump If a minidump should be taken as opposed to a full dump.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implemented in Tgstation.Server.Host.System.PosixProcessFeatures, and Tgstation.Server.Host.System.WindowsProcessFeatures.
Referenced by Tgstation.Server.Host.System.Process.CreateDump().
GetExecutingUsername()
string Tgstation.Server.Host.System.IProcessFeatures.GetExecutingUsername (global::System.Diagnostics.Process process)
Get the name of the user executing a given process .
Parameters
process The global::System.Diagnostics.Process.
Returns
The name of the user executing process .
Implemented in Tgstation.Server.Host.System.PosixProcessFeatures, and Tgstation.Server.Host.System.WindowsProcessFeatures.
Referenced by Tgstation.Server.Host.System.Process.GetExecutingUsername().
HandleProcessStart()
ValueTask< int > Tgstation.Server.Host.System.IProcessFeatures.HandleProcessStart (global::System.Diagnostics.Process process, CancellationToken cancellationToken)
Run events on starting a process.
Parameters
process The global::System.Diagnostics.Process that was started.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the process ID.
Implemented in Tgstation.Server.Host.System.PosixProcessFeatures, and Tgstation.Server.Host.System.WindowsProcessFeatures.
Referenced by Tgstation.Server.Host.System.ProcessExecutor.LaunchProcess().
ResumeProcess()
void Tgstation.Server.Host.System.IProcessFeatures.ResumeProcess (global::System.Diagnostics.Process process)
Resume a given suspended global::System.Diagnostics.Process.
Parameters
process The Process to suspended.
Implemented in Tgstation.Server.Host.System.PosixProcessFeatures, and Tgstation.Server.Host.System.WindowsProcessFeatures.
Referenced by Tgstation.Server.Host.System.Process.ResumeProcess().
SuspendProcess()
void Tgstation.Server.Host.System.IProcessFeatures.SuspendProcess (global::System.Diagnostics.Process process)
Suspend a given process .
Parameters
process The global::System.Diagnostics.Process to suspend.
Implemented in Tgstation.Server.Host.System.PosixProcessFeatures, and Tgstation.Server.Host.System.WindowsProcessFeatures.
Referenced by Tgstation.Server.Host.System.Process.SuspendProcess().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/System/IProcessFeatures.cs