tgstation-server: Tgstation.Server.Host.Components.Engine.IEngineInstaller Interface Reference
Tgstation.Server.Host.Components.Engine.IEngineInstaller Interface Reference
For downloading and installing game engines for a given system.
Public Member Functions
ValueTask< IEngineInstallation > CreateInstallation (EngineVersion version, string path, Task installationTask, CancellationToken cancellationToken)
Creates an IEngineInstallation for a given version .
ValueTask< IEngineInstallationData > DownloadVersion (EngineVersion version, JobProgressReporter jobProgressReporter, CancellationToken cancellationToken)
Download a given engine version .
ValueTask Install (EngineVersion version, string path, bool deploymentPipelineProcesses, CancellationToken cancellationToken)
Does actions necessary to get an extracted installation working.
ValueTask UpgradeInstallation (EngineVersion version, string path, CancellationToken cancellationToken)
Does actions necessary to get upgrade a version installed by a previous version of TGS.
ValueTask TrustDmbPath (EngineVersion version, string fullDmbPath, CancellationToken cancellationToken)
Add a given fullDmbPath to the trusted DMBs list in BYOND's config.
Task CleanCache (CancellationToken cancellationToken)
Attempts to cleans the engine's cache folder for the system.
Detailed Description
For downloading and installing game engines for a given system.
Definition at line 12 of file IEngineInstaller.cs.
Member Function Documentation
CleanCache()
Task Tgstation.Server.Host.Components.Engine.IEngineInstaller.CleanCache (CancellationToken cancellationToken)
Attempts to cleans the engine's cache folder for the system.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.Components.Engine.ByondInstallerBase, Tgstation.Server.Host.Components.Engine.DelegatingEngineInstaller, Tgstation.Server.Host.Components.Engine.EngineInstallerBase, and Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.
CreateInstallation()
ValueTask< IEngineInstallation > Tgstation.Server.Host.Components.Engine.IEngineInstaller.CreateInstallation (EngineVersion version, string path, Task installationTask, CancellationToken cancellationToken)
Creates an IEngineInstallation for a given version .
Parameters
version The EngineVersion of the installation.
path The path to the installation.
installationTask The Task representing the installation process for the installation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IEngineInstallation.
Implemented in Tgstation.Server.Host.Components.Engine.ByondInstallerBase, Tgstation.Server.Host.Components.Engine.DelegatingEngineInstaller, Tgstation.Server.Host.Components.Engine.EngineInstallerBase, and Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.
Referenced by Tgstation.Server.Host.Components.Engine.EngineManager.AssertAndLockVersion(), and Tgstation.Server.Host.Components.Engine.EngineManager.StartAsync().
DownloadVersion()
ValueTask< IEngineInstallationData > Tgstation.Server.Host.Components.Engine.IEngineInstaller.DownloadVersion (EngineVersion version, JobProgressReporter jobProgressReporter, CancellationToken cancellationToken)
Download a given engine version .
Parameters
version The EngineVersion of the engine to download.
jobProgressReporter The JobProgressReporter for the operation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the IEngineInstallationData for the download.
Implemented in Tgstation.Server.Host.Components.Engine.DelegatingEngineInstaller, Tgstation.Server.Host.Components.Engine.EngineInstallerBase, Tgstation.Server.Host.Components.Engine.OpenDreamInstaller, and Tgstation.Server.Host.Components.Engine.ByondInstallerBase.
Referenced by Tgstation.Server.Host.Components.Engine.EngineManager.InstallVersionFiles().
Install()
ValueTask Tgstation.Server.Host.Components.Engine.IEngineInstaller.Install (EngineVersion version, string path, bool deploymentPipelineProcesses, CancellationToken cancellationToken)
Does actions necessary to get an extracted installation working.
Parameters
version The EngineVersion being installed.
path The path to the installation.
deploymentPipelineProcesses If the operation should consider processes it launches to be part of the deployment pipeline.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implemented in Tgstation.Server.Host.Components.Engine.OpenDreamInstaller, Tgstation.Server.Host.Components.Engine.WindowsOpenDreamInstaller, Tgstation.Server.Host.Components.Engine.DelegatingEngineInstaller, Tgstation.Server.Host.Components.Engine.EngineInstallerBase, Tgstation.Server.Host.Components.Engine.PosixByondInstaller, and Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.
Referenced by Tgstation.Server.Host.Components.Engine.EngineManager.InstallVersionFiles().
TrustDmbPath()
ValueTask Tgstation.Server.Host.Components.Engine.IEngineInstaller.TrustDmbPath (EngineVersion version, string fullDmbPath, CancellationToken cancellationToken)
Add a given fullDmbPath to the trusted DMBs list in BYOND's config.
Parameters
version The EngineVersion being used.
fullDmbPath Full path to the .dmb that should be trusted.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implemented in Tgstation.Server.Host.Components.Engine.OpenDreamInstaller, Tgstation.Server.Host.Components.Engine.DelegatingEngineInstaller, Tgstation.Server.Host.Components.Engine.EngineInstallerBase, Tgstation.Server.Host.Components.Engine.PosixByondInstaller, and Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.
Referenced by Tgstation.Server.Host.Components.Engine.EngineManager.UseExecutables().
UpgradeInstallation()
ValueTask Tgstation.Server.Host.Components.Engine.IEngineInstaller.UpgradeInstallation (EngineVersion version, string path, CancellationToken cancellationToken)
Does actions necessary to get upgrade a version installed by a previous version of TGS.
Parameters
version The EngineVersion being installed.
path The path to the installation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implemented in Tgstation.Server.Host.Components.Engine.DelegatingEngineInstaller, Tgstation.Server.Host.Components.Engine.EngineInstallerBase, Tgstation.Server.Host.Components.Engine.OpenDreamInstaller, Tgstation.Server.Host.Components.Engine.PosixByondInstaller, and Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.
Referenced by Tgstation.Server.Host.Components.Engine.EngineManager.StartAsync().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Components/Engine/IEngineInstaller.cs