tgstation-server: Tgstation.Server.Host.Components.Chat.IChatManager Interface Reference
Tgstation.Server.Host.Components.Chat.IChatManager Interface Reference
For managing connected chat services.
Public Member Functions
void RegisterCommandHandler (ICustomCommandHandler customCommandHandler)
Registers a customCommandHandler to use.
ValueTask ChangeSettings (Models.ChatBot newSettings, CancellationToken cancellationToken)
Change chat settings. If the Api.Models.EntityId.Id is not currently in use, a new connection will be made instead.
Task DeleteConnection (long connectionId, CancellationToken cancellationToken)
Disconnects and deletes a given connection.
ValueTask ChangeChannels (long connectionId, IEnumerable< Models.ChatChannel > newChannels, CancellationToken cancellationToken)
Change chat channels.
void QueueMessage (MessageContent message, IEnumerable< ulong > channelIds)
Queue a chat message to a given set of channelIds .
void QueueWatchdogMessage (string message)
Queue a chat message to configured watchdog channels.
Func< string?, string, Action< bool > > QueueDeploymentMessage (Models.RevisionInformation revisionInformation, Api.Models.EngineVersion engineVersion, DateTimeOffset? estimatedCompletionTime, string? gitHubOwner, string? gitHubRepo, bool localCommitPushed)
Send the message for a deployment to configured deployment channels.
IChatTrackingContext CreateTrackingContext ()
Start tracking Commands.CustomCommands and ChannelRepresentations.
ValueTask UpdateTrackingContexts (CancellationToken cancellationToken)
Force an update with the active channels on all active IChatTrackingContexts.
Detailed Description
For managing connected chat services.
Definition at line 14 of file IChatManager.cs.
Member Function Documentation
ChangeChannels()
ValueTask Tgstation.Server.Host.Components.Chat.IChatManager.ChangeChannels (long connectionId, IEnumerable< Models.ChatChannel > newChannels, CancellationToken cancellationToken)
Change chat channels.
Parameters
connectionId The Api.Models.EntityId.Id of the connection.
newChannels An IEnumerable<T> of the new list of Models.ChatChannels.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
ChangeSettings()
ValueTask Tgstation.Server.Host.Components.Chat.IChatManager.ChangeSettings (Models.ChatBot newSettings, CancellationToken cancellationToken)
Change chat settings. If the Api.Models.EntityId.Id is not currently in use, a new connection will be made instead.
Parameters
newSettings The new Models.ChatBot.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation. Will complete immediately if the ChatBotSettings.Enabled property of newSettings is false.
Implemented in Tgstation.Server.Host.Components.Chat.ChatManager.
CreateTrackingContext()
IChatTrackingContext Tgstation.Server.Host.Components.Chat.IChatManager.CreateTrackingContext ()
Start tracking Commands.CustomCommands and ChannelRepresentations.
Returns
A new IChatTrackingContext.
Implemented in Tgstation.Server.Host.Components.Chat.ChatManager.
Referenced by Tgstation.Server.Host.Components.Session.SessionControllerFactory.LaunchNew(), and Tgstation.Server.Host.Components.Session.SessionControllerFactory.Reattach().
DeleteConnection()
Task Tgstation.Server.Host.Components.Chat.IChatManager.DeleteConnection (long connectionId, CancellationToken cancellationToken)
Disconnects and deletes a given connection.
Parameters
connectionId The Api.Models.EntityId.Id of the connection.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.Components.Chat.ChatManager.
QueueDeploymentMessage()
Func< string?, string, Action< bool > > Tgstation.Server.Host.Components.Chat.IChatManager.QueueDeploymentMessage (Models.RevisionInformation revisionInformation, Api.Models.EngineVersion engineVersion, DateTimeOffset? estimatedCompletionTime, string? gitHubOwner, string? gitHubRepo, bool localCommitPushed)
Send the message for a deployment to configured deployment channels.
Parameters
revisionInformation The RevisionInformation of the deployment.
engineVersion The Api.Models.EngineVersion of the deployment.
estimatedCompletionTime The optional DateTimeOffset the deployment is expected to be completed at.
gitHubOwner The repository GitHub owner, if any.
gitHubRepo The repository GitHub name, if any.
localCommitPushed true if the local deployment commit was pushed to the remote repository.
Returns
A Func<T1, T2, TResult> to call to update the message at the deployment's conclusion. Parameters: Error message if any, DreamMaker output if any. Returns an Action to call to mark the deployment as active/inactive. Parameter: If the deployment is being activated or inactivated.
Implemented in Tgstation.Server.Host.Components.Chat.ChatManager.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.Compile().
QueueMessage()
void Tgstation.Server.Host.Components.Chat.IChatManager.QueueMessage (MessageContent message, IEnumerable< ulong > channelIds)
Queue a chat message to a given set of channelIds .
Parameters
message The MessageContent being sent.
channelIds The Models.ChatChannel.Ids of the Models.ChatChannels to send to.
Implemented in Tgstation.Server.Host.Components.Chat.ChatManager.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleChatResponses(), and Tgstation.Server.Host.Components.Session.SessionController.ProcessBridgeCommand().
QueueWatchdogMessage()
void Tgstation.Server.Host.Components.Chat.IChatManager.QueueWatchdogMessage (string message)
Queue a chat message to configured watchdog channels.
Parameters
message The message being sent.
Implemented in Tgstation.Server.Host.Components.Chat.ChatManager.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleHealthCheck(), Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.HandleMonitorWakeup(), Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.HandleNewDmbAvailable(), Tgstation.Server.Host.Components.Watchdog.AdvancedWatchdog.HandleNormalReboot(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleRestart(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.LaunchNoLock(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.MonitorLifetimes(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.MonitorRestart(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.ReattachFailure(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.Restart(), and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.TerminateNoLock().
RegisterCommandHandler()
void Tgstation.Server.Host.Components.Chat.IChatManager.RegisterCommandHandler (ICustomCommandHandler customCommandHandler)
Registers a customCommandHandler to use.
Parameters
customCommandHandler A ICustomCommandHandler.
Implemented in Tgstation.Server.Host.Components.Chat.ChatManager.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.WatchdogBase().
UpdateTrackingContexts()
ValueTask Tgstation.Server.Host.Components.Chat.IChatManager.UpdateTrackingContexts (CancellationToken cancellationToken)
Force an update with the active channels on all active IChatTrackingContexts.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implemented in Tgstation.Server.Host.Components.Chat.ChatManager.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.StartAsync().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Components/Chat/IChatManager.cs