tgstation-server: Tgstation.Server.Host.Components.IInstanceManager Interface Reference
Tgstation.Server.Host.Components.IInstanceManager Interface Reference
For managing IInstances
Public Member Functions
IInstance GetInstance (Models.Instance metadata)
Get the IInstance associated with given metadata
Task OnlineInstance (Models.Instance metadata, CancellationToken cancellationToken)
Online an IInstance
Task OfflineInstance (Models.Instance metadata, User user, CancellationToken cancellationToken)
Offline an IInstance
Task MoveInstance (Models.Instance metadata, string newPath, CancellationToken cancellationToken)
Move an IInstance
Public Member Functions inherited from Tgstation.Server.Host.Components.Interop.IBridgeDispatcher
Task< BridgeResponse > ProcessBridgeRequest (BridgeParameters parameters, CancellationToken cancellationToken)
Handle a set of bridge parameters .
Detailed Description
For managing IInstances
Definition at line 11 of file IInstanceManager.cs.
Member Function Documentation
GetInstance()
IInstance Tgstation.Server.Host.Components.IInstanceManager.GetInstance (Models.Instance metadata)
Get the IInstance associated with given metadata
Parameters
metadata The Models.Instance of the desired IInstance
Returns
The IInstance associated with the given metadata
Implemented in Tgstation.Server.Host.Components.InstanceManager.
Referenced by Tgstation.Server.Host.Controllers.DreamDaemonController.Create(), Tgstation.Server.Host.Controllers.ChatController.Create(), Tgstation.Server.Host.Controllers.DreamMakerController.Create(), Tgstation.Server.Host.Controllers.RepositoryController.Create(), Tgstation.Server.Host.Controllers.ConfigurationController.Create(), Tgstation.Server.Host.Controllers.ChatController.Delete(), Tgstation.Server.Host.Controllers.DreamDaemonController.Delete(), Tgstation.Server.Host.Controllers.RepositoryController.Delete(), Tgstation.Server.Host.Controllers.ConfigurationController.Delete(), Tgstation.Server.Host.Controllers.ConfigurationController.Directory(), Tgstation.Server.Host.Controllers.ConfigurationController.File(), Tgstation.Server.Host.Controllers.DreamMakerController.Read(), Tgstation.Server.Host.Controllers.RepositoryController.Read(), Tgstation.Server.Host.Controllers.DreamDaemonController.ReadImpl(), Tgstation.Server.Host.Controllers.DreamDaemonController.Restart(), Tgstation.Server.Host.Controllers.ConfigurationController.Update(), Tgstation.Server.Host.Controllers.ByondController.Update(), Tgstation.Server.Host.Controllers.DreamDaemonController.Update(), Tgstation.Server.Host.Controllers.ChatController.Update(), Tgstation.Server.Host.Controllers.RepositoryController.Update(), and Tgstation.Server.Host.Controllers.InstanceController.Update().
MoveInstance()
Task Tgstation.Server.Host.Components.IInstanceManager.MoveInstance (Models.Instance metadata, string newPath, CancellationToken cancellationToken)
Move an IInstance
Parameters
metadata The Models.Instance of the desired IInstance
newPath The new path of the IInstance. metadata will have this set on Api.Models.Instance.Path if the operation completes successfully
cancellationToken The CancellationToken for the operation
Returns
A Task representing the running operation
Implemented in Tgstation.Server.Host.Components.InstanceManager.
Referenced by Tgstation.Server.Host.Controllers.InstanceController.Update().
OfflineInstance()
Task Tgstation.Server.Host.Components.IInstanceManager.OfflineInstance (Models.Instance metadata, User user, CancellationToken cancellationToken)
Offline an IInstance
Parameters
metadata The Models.Instance of the desired IInstance
user The User performing the operation
cancellationToken The CancellationToken for the operation
Returns
A Task representing the running operation
Referenced by Tgstation.Server.Host.Controllers.InstanceController.Update().
OnlineInstance()
Task Tgstation.Server.Host.Components.IInstanceManager.OnlineInstance (Models.Instance metadata, CancellationToken cancellationToken)
Online an IInstance
Parameters
metadata The Models.Instance of the desired IInstance
cancellationToken The CancellationToken for the operation
Returns
A Task representing the running operation
Implemented in Tgstation.Server.Host.Components.InstanceManager.
Referenced by Tgstation.Server.Host.Controllers.InstanceController.Update().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Components/IInstanceManager.cs