tgstation-server: Tgstation.Server.Host.Core.IJobManager Interface Reference
Tgstation.Server.Host.Core.IJobManager Interface Reference
Manages the runtime of Jobs
Public Member Functions
int? JobProgress (Job job)
Get the Api.Models.Job.Progress for a job
Task RegisterOperation (Job job, Func< Job, IDatabaseContext, Action< int >, CancellationToken, Task > operation, CancellationToken cancellationToken)
Registers a given Job and begins running it
Task WaitForJobCompletion (Job job, User canceller, CancellationToken jobCancellationToken, CancellationToken cancellationToken)
Wait for a given job to complete
Task< bool > CancelJob (Job job, User user, bool blocking, CancellationToken cancellationToken)
Cancels a give job
Detailed Description
Manages the runtime of Jobs
Definition at line 12 of file IJobManager.cs.
Member Function Documentation
CancelJob()
Task<bool> Tgstation.Server.Host.Core.IJobManager.CancelJob (Job job, User user, bool blocking, CancellationToken cancellationToken)
Cancels a give job
Parameters
job The Job to cancel
user The User who cancelled the job
blocking If the operation should wait until the job exits before completing
cancellationToken The CancellationToken for the operation
Returns
A Task<TResult> resulting in true if the job was cancelled, false if it couldn't be found
Implemented in Tgstation.Server.Host.Core.JobManager.
Referenced by Tgstation.Server.Host.Controllers.JobController.Delete(), and Tgstation.Server.Host.Components.InstanceManager.OfflineInstance().
JobProgress()
int? Tgstation.Server.Host.Core.IJobManager.JobProgress (Job job)
Get the Api.Models.Job.Progress for a job
Parameters
job The Job to get Api.Models.Job.Progress for
Returns
The Api.Models.Job.Progress of job
Implemented in Tgstation.Server.Host.Core.JobManager.
Referenced by Tgstation.Server.Host.Controllers.JobController.GetId().
RegisterOperation()
Task Tgstation.Server.Host.Core.IJobManager.RegisterOperation (Job job, Func< Job, IDatabaseContext, Action< int >, CancellationToken, Task > operation, CancellationToken cancellationToken)
Registers a given Job and begins running it
Parameters
job The Job
operation The operation to run taking the started Job, a IDatabaseContext, progress reporter Action<T1> and a CancellationToken
cancellationToken The CancellationToken for the operation
Returns
A Task representing a running operation
Implemented in Tgstation.Server.Host.Core.JobManager.
Referenced by Tgstation.Server.Host.Controllers.DreamDaemonController.Create(), Tgstation.Server.Host.Controllers.DreamMakerController.Create(), Tgstation.Server.Host.Controllers.RepositoryController.Create(), Tgstation.Server.Host.Controllers.RepositoryController.Delete(), Tgstation.Server.Host.Controllers.DreamDaemonController.Restart(), Tgstation.Server.Host.Components.Instance.TimerLoop(), Tgstation.Server.Host.Controllers.ByondController.Update(), and Tgstation.Server.Host.Controllers.RepositoryController.Update().
WaitForJobCompletion()
Task Tgstation.Server.Host.Core.IJobManager.WaitForJobCompletion (Job job, User canceller, CancellationToken jobCancellationToken, CancellationToken cancellationToken)
Wait for a given job to complete
Parameters
job The Job to wait for
canceller The User to cancel the job
jobCancellationToken A CancellationToken that will cancel the job
cancellationToken The CancellationToken for the operation
Returns
A Task representing the Job
Implemented in Tgstation.Server.Host.Core.JobManager.
Referenced by Tgstation.Server.Host.Components.Instance.TimerLoop().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Core/IJobManager.cs