tgstation-server: Tgstation.Server.Common.Http.IAbstractHttpClientFactory Interface Reference
Tgstation.Server.Common.Http.IAbstractHttpClientFactory Interface Reference
Creates IHttpClients.
Public Member Functions
IHttpClient CreateClient ()
Create a IHttpClient.
Detailed Description
Creates IHttpClients.
Definition at line 6 of file IAbstractHttpClientFactory.cs.
Member Function Documentation
CreateClient()
IHttpClient Tgstation.Server.Common.Http.IAbstractHttpClientFactory.CreateClient ()
Create a IHttpClient.
Returns
A new IHttpClient.
Implemented in Tgstation.Server.Common.Http.HttpClientFactory, and Tgstation.Server.Host.Utils.AbstractHttpClientFactory.
Referenced by Tgstation.Server.Host.Swarm.SwarmService.CommitUpdate(), Tgstation.Server.Host.Swarm.SwarmService.ControllerDistributedPrepareUpdate(), Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.CreateHttpClient(), Tgstation.Server.Host.Swarm.SwarmService.CreateUpdateStreamProvider(), Tgstation.Server.Host.IO.FileDownloader.DownloadFile(), Tgstation.Server.Host.Swarm.SwarmService.PrepareUpdateImpl(), Tgstation.Server.Host.Swarm.SwarmService.RemoteAbortUpdate(), and Tgstation.Server.Host.Swarm.SwarmService.Shutdown().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Common/Http/IAbstractHttpClientFactory.cs