tgstation-server: Tgstation.Server.Host.Utils.GitHub.IGitHubClientFactory Interface Reference
Tgstation.Server.Host.Utils.GitHub.IGitHubClientFactory Interface Reference
For creating IGitHubClients.
Public Member Functions
ValueTask< IGitHubClient > CreateClient (CancellationToken cancellationToken)
Create a IGitHubClient client. Low rate limit unless the server's GitHubAccessToken is set to bypass it.
ValueTask< IGitHubClient > CreateClient (string accessToken, CancellationToken cancellationToken)
Create a client with authentication using a personal access token.
ValueTask< IGitHubClient?> CreateClientForRepository (string accessString, RepositoryIdentifier repositoryIdentifier, CancellationToken cancellationToken)
Creates a GitHub client that will only be used for a given repositoryIdentifier .
IGitHubClient? CreateAppClient (string tgsEncodedAppPrivateKey)
Create an App (not installation) authenticated IGitHubClient.
Detailed Description
For creating IGitHubClients.
Definition at line 11 of file IGitHubClientFactory.cs.
Member Function Documentation
CreateAppClient()
IGitHubClient? Tgstation.Server.Host.Utils.GitHub.IGitHubClientFactory.CreateAppClient (string tgsEncodedAppPrivateKey)
Create an App (not installation) authenticated IGitHubClient.
Parameters
tgsEncodedAppPrivateKey The TGS encoded app private key string.
Returns
A new app auth IGitHubClient for the given tgsEncodedAppPrivateKey on success null on failure.
Implemented in Tgstation.Server.Host.Utils.GitHub.GitHubClientFactory.
Referenced by Tgstation.Server.Host.Controllers.RepositoryController.ValidateCredentials().
CreateClient() [1/2]
ValueTask< IGitHubClient > Tgstation.Server.Host.Utils.GitHub.IGitHubClientFactory.CreateClient (CancellationToken cancellationToken)
Create a IGitHubClient client. Low rate limit unless the server's GitHubAccessToken is set to bypass it.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A new IGitHubClient.
Implemented in Tgstation.Server.Host.Utils.GitHub.GitHubClientFactory.
CreateClient() [2/2]
ValueTask< IGitHubClient > Tgstation.Server.Host.Utils.GitHub.IGitHubClientFactory.CreateClient (string accessToken, CancellationToken cancellationToken)
Create a client with authentication using a personal access token.
Parameters
accessToken The GitHub personal access token.
cancellationToken The CancellationToken for the operation.
Returns
A new IGitHubClient.
Implemented in Tgstation.Server.Host.Utils.GitHub.GitHubClientFactory.
CreateClientForRepository()
ValueTask< IGitHubClient?> Tgstation.Server.Host.Utils.GitHub.IGitHubClientFactory.CreateClientForRepository (string accessString, RepositoryIdentifier repositoryIdentifier, CancellationToken cancellationToken)
Creates a GitHub client that will only be used for a given repositoryIdentifier .
Parameters
accessString The GitHub personal access token or TGS encoded app private key string.
repositoryIdentifier The RepositoryIdentifier for the GitHub ID that the client will be used to connect to.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a new IGitHubClient for the given repositoryIdentifier or null if authentication failed.
Implemented in Tgstation.Server.Host.Utils.GitHub.GitHubClientFactory.
Referenced by Tgstation.Server.Host.Utils.GitHub.GitHubServiceFactory.CreateService(), Tgstation.Server.Host.Core.VersionReportingService.TryReportVersion(), and Tgstation.Server.Host.Controllers.RepositoryController.ValidateCredentials().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Utils/GitHub/IGitHubClientFactory.cs