tgstation-server: TGServiceInterface.Components.ITGConfig Interface Reference
TGServiceInterface.Components.ITGConfig Interface Reference
For modifying the in game config Most if not all of these will not apply until the next server reboot
Public Member Functions
string ServerDirectory ()
Return the directory of the server on the host machine
IList< string > ListStaticDirectory (string subpath, out string error, out bool unauthorized)
Returns the file contents of the specified server directory Subdirectories will be prefixed with '/'
string ReadText (string staticRelativePath, bool repo, out string error, out bool unauthorized)
Read from a static file
string WriteText (string staticRelativePath, string data, out bool unauthorized)
Write to a static file
string DeleteFile (string staticRelativePath, out bool unauthorized)
Deletes the target static file
Detailed Description
For modifying the in game config Most if not all of these will not apply until the next server reboot
Definition at line 11 of file Config.cs.
Member Function Documentation
string TGServiceInterface.Components.ITGConfig.DeleteFile (string staticRelativePath, out bool unauthorized)
Deletes the target static file
Parameters
staticRelativePath The path from the Static dir. E.g. config/config.txt
unauthorized This will be true if error is set to a message that indicates the current user does not have access to the specified file
Returns
null on success, error message on failure
Implemented in TGServerService.ServerInstance.
IList<string> TGServiceInterface.Components.ITGConfig.ListStaticDirectory (string subpath, out string error, out bool unauthorized)
Returns the file contents of the specified server directory Subdirectories will be prefixed with '/'
Parameters
subpath Subdirectory to enumerate, enumerates the root directory if null
error null on success, error message on failure
unauthorized This will be true if error is set to a message that indicates the current user does not have access to the specified file
Returns
A list of files in the enumerated static directory on success, null on failure
Implemented in TGServerService.ServerInstance.
Referenced by TGControlPanel.ControlPanel.EnumeratePath().
string TGServiceInterface.Components.ITGConfig.ReadText (string staticRelativePath, bool repo, out string error, out bool unauthorized)
Read from a static file
Parameters
staticRelativePath The path from the Static dir. E.g. config/config.txt
repo if true, the file will be read from the repository instead of the static dir
error null on success, error message on failure
unauthorized This will be true if error is set to a message that indicates the current user does not have access to the specified file
Returns
The full text of the file on success, null on failure
Exceptions
CommunicationException Along with implied disconnect exceptions, if the file exceeds transfer limits
Implemented in TGServerService.ServerInstance.
string TGServiceInterface.Components.ITGConfig.ServerDirectory ()
Return the directory of the server on the host machine
Returns
The path to the directory on success, null on failure
Implemented in TGServerService.ServerInstance.
Referenced by TGCommandLine.ConfigServerDirectoryCommand.Run().
string TGServiceInterface.Components.ITGConfig.WriteText (string staticRelativePath, string data, out bool unauthorized)
Write to a static file
Parameters
staticRelativePath The path from the Static dir. E.g. config/config.txt
data The full text of the config file
unauthorized This will be true if error is set to a message that indicates the current user does not have access to the specified file
Returns
null on success, error message on failure
Exceptions
CommunicationException Along with implied disconnect exceptions, if the file exceeds transfer limits
Implemented in TGServerService.ServerInstance.
Referenced by TGControlPanel.ControlPanel.StaticFileCreateButton_Click().
The documentation for this interface was generated from the following file:
TGServiceInterface/Components/Config.cs