tgstation-server: Tgstation.Server.Host.IO.IConsole Interface Reference
Tgstation.Server.Host.IO.IConsole Interface Reference
Abstraction for global::System.Console.
Public Member Functions
Task WriteAsync (string text, bool newLine, CancellationToken cancellationToken)
Write some text to the IConsole.
Task PressAnyKeyAsync (CancellationToken cancellationToken)
Wait for a key press on the IConsole.
Task< string > ReadLineAsync (bool usePasswordChar, CancellationToken cancellationToken)
Read a line from the IConsole.
Properties
bool Available [get]
If the IConsole is visible to the user.
CancellationToken CancelKeyPress [get]
Gets a CancellationToken that triggers if Crtl+C or an equivalent is pressed.
Detailed Description
Abstraction for global::System.Console.
Definition at line 9 of file IConsole.cs.
Member Function Documentation
PressAnyKeyAsync()
Task Tgstation.Server.Host.IO.IConsole.PressAnyKeyAsync (CancellationToken cancellationToken)
Wait for a key press on the IConsole.
Parameters
cancellationToken The CancellationToken for the operations.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.IO.Console.
Referenced by Tgstation.Server.Host.Setup.SetupWizard.SaveConfiguration(), and Tgstation.Server.Host.Setup.SetupWizard.TestDatabaseConnection().
ReadLineAsync()
Task<string> Tgstation.Server.Host.IO.IConsole.ReadLineAsync (bool usePasswordChar, CancellationToken cancellationToken)
Read a line from the IConsole.
Parameters
usePasswordChar If the input should be retrieved using the '*' character.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the string read by the IConsole.
Implemented in Tgstation.Server.Host.IO.Console.
Referenced by Tgstation.Server.Host.Setup.SetupWizard.ConfigureControlPanel(), Tgstation.Server.Host.Setup.SetupWizard.ConfigureDatabase(), Tgstation.Server.Host.Setup.SetupWizard.ConfigureElasticsearch(), Tgstation.Server.Host.Setup.SetupWizard.ConfigureGeneral(), Tgstation.Server.Host.Setup.SetupWizard.ConfigureLogging(), Tgstation.Server.Host.Setup.SetupWizard.ConfigureSwarm(), Tgstation.Server.Host.Setup.SetupWizard.PromptDatabaseType(), Tgstation.Server.Host.Setup.SetupWizard.PromptForHostingPort(), and Tgstation.Server.Host.Setup.SetupWizard.PromptYesNo().
WriteAsync()
Task Tgstation.Server.Host.IO.IConsole.WriteAsync (string text, bool newLine, CancellationToken cancellationToken)
Write some text to the IConsole.
Parameters
text The string to write.
newLine If there should be a new line after the text .
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.IO.Console.
Referenced by Tgstation.Server.Host.Setup.SetupWizard.CheckRunWizard(), Tgstation.Server.Host.Setup.SetupWizard.ConfigureControlPanel(), Tgstation.Server.Host.Setup.SetupWizard.ConfigureDatabase(), Tgstation.Server.Host.Setup.SetupWizard.ConfigureElasticsearch(), Tgstation.Server.Host.Setup.SetupWizard.ConfigureGeneral(), Tgstation.Server.Host.Setup.SetupWizard.ConfigureLogging(), Tgstation.Server.Host.Setup.SetupWizard.ConfigureSwarm(), Tgstation.Server.Host.Setup.SetupWizard.PromptDatabaseType(), Tgstation.Server.Host.Setup.SetupWizard.PromptForHostingPort(), Tgstation.Server.Host.Setup.SetupWizard.PromptYesNo(), Tgstation.Server.Host.Setup.SetupWizard.RunWizard(), Tgstation.Server.Host.Setup.SetupWizard.SaveConfiguration(), Tgstation.Server.Host.Setup.SetupWizard.TestDatabaseConnection(), and Tgstation.Server.Host.Setup.SetupWizard.ValidateNonExistantSqliteDBName().
Property Documentation
Available
bool Tgstation.Server.Host.IO.IConsole.Available get
If the IConsole is visible to the user.
Definition at line 14 of file IConsole.cs.
 { get; }
Referenced by Tgstation.Server.Host.Setup.SetupWizard.CheckRunWizard().
CancelKeyPress
CancellationToken Tgstation.Server.Host.IO.IConsole.CancelKeyPress get
Gets a CancellationToken that triggers if Crtl+C or an equivalent is pressed.
Definition at line 19 of file IConsole.cs.
 { get; }
Referenced by Tgstation.Server.Host.Setup.SetupWizard.CheckRunWizard().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/IO/IConsole.cs