tgstation-server: Tgstation.Server.Host.Components.Deployment.IGitHubDeploymentManager Interface Reference
Tgstation.Server.Host.Components.Deployment.IGitHubDeploymentManager Interface Reference
Creates and updates GitHub deployments.
Public Member Functions
Task StartDeployment (IRepository repository, CompileJob compileJob, CancellationToken cancellationToken)
Start a deployment for a given compileJob .
Task StageDeployment (CompileJob compileJob, CancellationToken cancellationToken)
Stage a given compileJob 's deployment.
Task ApplyDeployment (CompileJob compileJob, CompileJob oldCompileJob, CancellationToken cancellationToken)
Stage a given compileJob 's deployment.
Task FailDeployment (CompileJob compileJob, string errorMessage, CancellationToken cancellationToken)
Fail a deployment for a given compileJob .
Task MarkInactive (CompileJob compileJob, CancellationToken cancellationToken)
Mark the deplotment for a given compileJob as inactive.
Detailed Description
Creates and updates GitHub deployments.
Definition at line 11 of file IGitHubDeploymentManager.cs.
Member Function Documentation
ApplyDeployment()
Task Tgstation.Server.Host.Components.Deployment.IGitHubDeploymentManager.ApplyDeployment (CompileJob compileJob, CompileJob oldCompileJob, CancellationToken cancellationToken)
Stage a given compileJob 's deployment.
Parameters
compileJob The CompileJob being applied.
oldCompileJob The currently active CompileJob, if any.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.Components.Deployment.GitHubDeploymentManager.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.BeforeApplyDmb().
FailDeployment()
Task Tgstation.Server.Host.Components.Deployment.IGitHubDeploymentManager.FailDeployment (CompileJob compileJob, string errorMessage, CancellationToken cancellationToken)
Fail a deployment for a given compileJob .
Parameters
compileJob The failed CompileJob.
errorMessage The error message.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.Components.Deployment.GitHubDeploymentManager.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.CleanupFailedCompile().
MarkInactive()
Task Tgstation.Server.Host.Components.Deployment.IGitHubDeploymentManager.MarkInactive (CompileJob compileJob, CancellationToken cancellationToken)
Mark the deplotment for a given compileJob as inactive.
Parameters
compileJob The inactive CompileJob.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.Components.Deployment.GitHubDeploymentManager.
Referenced by Tgstation.Server.Host.Components.Deployment.DmbFactory.CleanJob().
StageDeployment()
Task Tgstation.Server.Host.Components.Deployment.IGitHubDeploymentManager.StageDeployment (CompileJob compileJob, CancellationToken cancellationToken)
Stage a given compileJob 's deployment.
Parameters
compileJob The staged CompileJob.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.Components.Deployment.GitHubDeploymentManager.
Referenced by Tgstation.Server.Host.Components.Deployment.DmbFactory.LoadCompileJob().
StartDeployment()
Task Tgstation.Server.Host.Components.Deployment.IGitHubDeploymentManager.StartDeployment (IRepository repository, CompileJob compileJob, CancellationToken cancellationToken)
Start a deployment for a given compileJob .
Parameters
repository The IRepository being deployed.
compileJob The active CompileJob.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.Components.Deployment.GitHubDeploymentManager.
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Components/Deployment/IGitHubDeploymentManager.cs