tgstation-server: Tgstation.Server.Host.Core.IGitHubClientFactory Interface Reference
Tgstation.Server.Host.Core.IGitHubClientFactory Interface Reference
For creating IGitHubClients.
Public Member Functions
IGitHubClient CreateClient ()
Create a IGitHubClient client. Low rate limit unless the server's GitHubAccessToken is set to bypass it.
IGitHubClient CreateClient (string accessToken)
Create a client with authentication using a personal access token.
Detailed Description
For creating IGitHubClients.
Definition at line 8 of file IGitHubClientFactory.cs.
Member Function Documentation
CreateClient() [1/2]
IGitHubClient Tgstation.Server.Host.Core.IGitHubClientFactory.CreateClient ()
Create a IGitHubClient client. Low rate limit unless the server's GitHubAccessToken is set to bypass it.
Returns
A new IGitHubClient.
Implemented in Tgstation.Server.Host.Core.GitHubClientFactory.
Referenced by Tgstation.Server.Host.Core.ServerUpdateInitiator.BeginUpdate(), Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.CommentOnTestMergeSource(), Tgstation.Server.Host.Components.Repository.GitHubRemoteFeatures.GetTestMergeImpl(), Tgstation.Server.Host.Controllers.AdministrationController.Read(), Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.RemoveMergedTestMerges(), Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.StartDeployment(), Tgstation.Server.Host.Controllers.RepositoryController.Update(), Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.UpdateDeployment(), and Tgstation.Server.Host.Security.OAuth.GitHubOAuthValidator.ValidateResponseCode().
CreateClient() [2/2]
IGitHubClient Tgstation.Server.Host.Core.IGitHubClientFactory.CreateClient (string accessToken)
Create a client with authentication using a personal access token.
Parameters
accessToken The GitHub personal access token.
Returns
A new IGitHubClient.
Implemented in Tgstation.Server.Host.Core.GitHubClientFactory.
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Core/IGitHubClientFactory.cs