tgstation-server: Tgstation.Server.Host.Components.Repository.IRepositoryManager Interface Reference
Tgstation.Server.Host.Components.Repository.IRepositoryManager Interface Reference
Factory for creating and loading IRepositorys.
Public Member Functions
ValueTask< IRepository?> LoadRepository (CancellationToken cancellationToken)
Attempt to load the IRepository from the default location.
ValueTask< IRepository?> CloneRepository (Uri url, string? initialBranch, string? username, string? password, JobProgressReporter progressReporter, bool recurseSubmodules, CancellationToken cancellationToken)
Clone the repository at url .
ValueTask DeleteRepository (CancellationToken cancellationToken)
Delete the current repository.
Properties
bool InUse [get]
If something is holding a lock on the repository.
bool CloneInProgress [get]
If a CloneRepository(Uri, string, string, string, JobProgressReporter, bool, CancellationToken) operation is in progress.
Detailed Description
Factory for creating and loading IRepositorys.
Definition at line 12 of file IRepositoryManager.cs.
Member Function Documentation
CloneRepository()
ValueTask< IRepository?> Tgstation.Server.Host.Components.Repository.IRepositoryManager.CloneRepository (Uri url, string? initialBranch, string? username, string? password, JobProgressReporter progressReporter, bool recurseSubmodules, CancellationToken cancellationToken)
Clone the repository at url .
Parameters
url The Uri of the remote repository to clone.
initialBranch The optional branch to clone.
username The optional username to clone from url .
password The optional password to clone from url .
progressReporter The JobProgressReporter for progress of the clone.
recurseSubmodules If submodules should be recusively cloned and initialized.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting i the newly cloned IRepository, null if one already exists.
Implemented in Tgstation.Server.Host.Components.Repository.RepositoryManager.
Referenced by Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.DownloadVersion().
DeleteRepository()
ValueTask Tgstation.Server.Host.Components.Repository.IRepositoryManager.DeleteRepository (CancellationToken cancellationToken)
Delete the current repository.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implemented in Tgstation.Server.Host.Components.Repository.RepositoryManager.
LoadRepository()
ValueTask< IRepository?> Tgstation.Server.Host.Components.Repository.IRepositoryManager.LoadRepository (CancellationToken cancellationToken)
Attempt to load the IRepository from the default location.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the loaded IRepository if it exists, null otherwise.
Implemented in Tgstation.Server.Host.Components.Repository.RepositoryManager.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.DeploymentProcess(), Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.DownloadVersion(), Tgstation.Server.Host.Components.Chat.Commands.PullRequestsCommand.Invoke(), and Tgstation.Server.Host.Components.Chat.Commands.RevisionCommand.Invoke().
Property Documentation
CloneInProgress
bool Tgstation.Server.Host.Components.Repository.IRepositoryManager.CloneInProgress get
If a CloneRepository(Uri, string, string, string, JobProgressReporter, bool, CancellationToken) operation is in progress.
Implemented in Tgstation.Server.Host.Components.Repository.RepositoryManager.
Definition at line 22 of file IRepositoryManager.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Chat.Commands.PullRequestsCommand.Invoke(), and Tgstation.Server.Host.Components.Chat.Commands.RevisionCommand.Invoke().
InUse
bool Tgstation.Server.Host.Components.Repository.IRepositoryManager.InUse get
If something is holding a lock on the repository.
Implemented in Tgstation.Server.Host.Components.Repository.RepositoryManager.
Definition at line 17 of file IRepositoryManager.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Chat.Commands.PullRequestsCommand.Invoke(), and Tgstation.Server.Host.Components.Chat.Commands.RevisionCommand.Invoke().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Components/Repository/IRepositoryManager.cs