tgstation-server: Tgstation.Server.Host.Utils.GitHub.IGitHubService Interface Reference
Tgstation.Server.Host.Utils.GitHub.IGitHubService Interface Reference
Service for interacting with the GitHub API.
Public Member Functions
Task< Uri > GetUpdatesRepositoryUrl (CancellationToken cancellationToken)
Gets the Uri of the repository designated as the updates repository.
Task< Dictionary< Version, Release > > GetTgsReleases (CancellationToken cancellationToken)
Get all valid TGS Releases from the configured update source.
Task< string > CreateOAuthAccessToken (OAuthConfiguration oAuthConfiguration, string code, CancellationToken cancellationToken)
Attempt to get an OAuth token from a given code .
Task< long > GetRepositoryId (string repoOwner, string repoName, CancellationToken cancellationToken)
Get a target repostiory's ID.
Task< int > GetCurrentUserId (CancellationToken cancellationToken)
Get the current user's ID.
Task< PullRequest > GetPullRequest (string repoOwner, string repoName, int pullRequestNumber, CancellationToken cancellationToken)
Get a given pullRequestNumber .
Detailed Description
Service for interacting with the GitHub API.
Definition at line 15 of file IGitHubService.cs.
Member Function Documentation
CreateOAuthAccessToken()
Task< string > Tgstation.Server.Host.Utils.GitHub.IGitHubService.CreateOAuthAccessToken (OAuthConfiguration oAuthConfiguration, string code, CancellationToken cancellationToken)
Attempt to get an OAuth token from a given code .
Parameters
oAuthConfiguration The OAuthConfiguration. Must have OAuthConfiguration.RedirectUrl, OAuthConfigurationBase.ClientId and OAuthConfigurationBase.ClientSecret set.
code The OAuth response code.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in a string representing the returned OAuth code from GitHub on success, null otherwise.
Implemented in Tgstation.Server.Host.Utils.GitHub.GitHubService.
Referenced by Tgstation.Server.Host.Security.OAuth.GitHubOAuthValidator.ValidateResponseCode().
GetCurrentUserId()
Task< int > Tgstation.Server.Host.Utils.GitHub.IGitHubService.GetCurrentUserId (CancellationToken cancellationToken)
Get the current user's ID.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the current user's ID.
Implemented in Tgstation.Server.Host.Utils.GitHub.GitHubService.
GetPullRequest()
Task< PullRequest > Tgstation.Server.Host.Utils.GitHub.IGitHubService.GetPullRequest (string repoOwner, string repoName, int pullRequestNumber, CancellationToken cancellationToken)
Get a given pullRequestNumber .
Parameters
repoOwner The owner of the target repository.
repoName The name of the target repository.
pullRequestNumber The target PullRequest.Number.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the target PullRequest.
Implemented in Tgstation.Server.Host.Utils.GitHub.GitHubService.
Referenced by Tgstation.Server.Host.Components.Repository.GitHubRemoteFeatures.GetTestMergeImpl().
GetRepositoryId()
Task< long > Tgstation.Server.Host.Utils.GitHub.IGitHubService.GetRepositoryId (string repoOwner, string repoName, CancellationToken cancellationToken)
Get a target repostiory's ID.
Parameters
repoOwner The owner of the target repository.
repoName The name of the target repository.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the target repository's ID.
Implemented in Tgstation.Server.Host.Utils.GitHub.GitHubService.
Referenced by Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.StartDeployment().
GetTgsReleases()
Task< Dictionary< Version, Release > > Tgstation.Server.Host.Utils.GitHub.IGitHubService.GetTgsReleases (CancellationToken cancellationToken)
Get all valid TGS Releases from the configured update source.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in a Dictionary<TKey, TValue> of TGS Releases keyed by their Version.
GitHub has been known to return incomplete results from the API with this call.
Implemented in Tgstation.Server.Host.Utils.GitHub.GitHubService.
Referenced by Tgstation.Server.Host.Core.ServerUpdater.BeginUpdateImpl(), and Tgstation.Server.Host.Controllers.AdministrationController.Read().
GetUpdatesRepositoryUrl()
Task< Uri > Tgstation.Server.Host.Utils.GitHub.IGitHubService.GetUpdatesRepositoryUrl (CancellationToken cancellationToken)
Gets the Uri of the repository designated as the updates repository.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the Uri of the designated updates repository.
Implemented in Tgstation.Server.Host.Utils.GitHub.GitHubService.
Referenced by Tgstation.Server.Host.Controllers.AdministrationController.Read().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Utils/GitHub/IGitHubService.cs