tgstation-server: Tgstation.Server.Host.Components.Repository.IGitRemoteFeaturesFactory Interface Reference
Tgstation.Server.Host.Components.Repository.IGitRemoteFeaturesFactory Interface Reference
Factory for creating IGitRemoteFeatures.
Public Member Functions
IGitRemoteFeatures CreateGitRemoteFeatures (IRepository repository)
Create the IGitRemoteFeatures for a given repository .
IGitRemoteFeatures CreateGitRemoteFeatures (Uri origin)
Create the IGitRemoteFeatures for a given origin .
RemoteGitProvider ParseRemoteGitProviderFromOrigin (Uri origin)
Gets the RemoteGitProvider for a given origin .
Detailed Description
Factory for creating IGitRemoteFeatures.
Definition at line 10 of file IGitRemoteFeaturesFactory.cs.
Member Function Documentation
CreateGitRemoteFeatures() [1/2]
IGitRemoteFeatures Tgstation.Server.Host.Components.Repository.IGitRemoteFeaturesFactory.CreateGitRemoteFeatures (IRepository repository)
Create the IGitRemoteFeatures for a given repository .
Parameters
repository The IRepository containing the IRepository.Origin to create IGitRemoteFeatures for.
Returns
A new IGitRemoteFeatures instance.
Implemented in Tgstation.Server.Host.Components.Repository.GitRemoteFeaturesFactory.
Referenced by Tgstation.Server.Host.Components.Repository.Repository.Repository(), and Tgstation.Server.Host.Controllers.RepositoryController.ValidateCredentials().
CreateGitRemoteFeatures() [2/2]
IGitRemoteFeatures Tgstation.Server.Host.Components.Repository.IGitRemoteFeaturesFactory.CreateGitRemoteFeatures (Uri origin)
Create the IGitRemoteFeatures for a given origin .
Parameters
origin The Uri of the IGitRemoteFeatures origing URL.
Returns
A new IGitRemoteFeatures instance.
Implemented in Tgstation.Server.Host.Components.Repository.GitRemoteFeaturesFactory.
ParseRemoteGitProviderFromOrigin()
RemoteGitProvider Tgstation.Server.Host.Components.Repository.IGitRemoteFeaturesFactory.ParseRemoteGitProviderFromOrigin (Uri origin)
Gets the RemoteGitProvider for a given origin .
Parameters
origin The Uri of the origin.
Returns
The RemoteGitProvider of the origin .
Implemented in Tgstation.Server.Host.Components.Repository.GitRemoteFeaturesFactory.
Referenced by Tgstation.Server.Host.Components.Deployment.Remote.RemoteDeploymentManagerFactory.CreateRemoteDeploymentManager().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Components/Repository/IGitRemoteFeaturesFactory.cs