tgstation-server: Tgstation.Server.Host.Security.ISystemIdentityFactory Interface Reference
Tgstation.Server.Host.Security.ISystemIdentityFactory Interface Reference
Factory for ISystemIdentitys.
Public Member Functions
ISystemIdentity GetCurrent ()
Retrieves a ISystemIdentity representing the user executing tgstation-server.
Task< ISystemIdentity?> CreateSystemIdentity (User user, CancellationToken cancellationToken)
Create a ISystemIdentity for a given user .
Task< ISystemIdentity?> CreateSystemIdentity (string username, string password, CancellationToken cancellationToken)
Create a ISystemIdentity for a given username and password.
Detailed Description
Factory for ISystemIdentitys.
Definition at line 11 of file ISystemIdentityFactory.cs.
Member Function Documentation
CreateSystemIdentity() [1/2]
Task< ISystemIdentity?> Tgstation.Server.Host.Security.ISystemIdentityFactory.CreateSystemIdentity (string username, string password, CancellationToken cancellationToken)
Create a ISystemIdentity for a given username and password.
Parameters
username The username of the user.
password The password of the user.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in a new ISystemIdentity based on the given credentials on success, null on failure.
Implemented in Tgstation.Server.Host.Security.PosixSystemIdentityFactory, and Tgstation.Server.Host.Security.WindowsSystemIdentityFactory.
CreateSystemIdentity() [2/2]
Task< ISystemIdentity?> Tgstation.Server.Host.Security.ISystemIdentityFactory.CreateSystemIdentity (User user, CancellationToken cancellationToken)
Create a ISystemIdentity for a given user .
Parameters
user The user to create a ISystemIdentity for.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in a new ISystemIdentity based on the given user or null if the user has no ISystemIdentity.
Implemented in Tgstation.Server.Host.Security.PosixSystemIdentityFactory, and Tgstation.Server.Host.Security.WindowsSystemIdentityFactory.
Referenced by Tgstation.Server.Host.Controllers.UserController.Create(), and Tgstation.Server.Host.Controllers.ApiRootController.CreateToken().
GetCurrent()
ISystemIdentity Tgstation.Server.Host.Security.ISystemIdentityFactory.GetCurrent ()
Retrieves a ISystemIdentity representing the user executing tgstation-server.
Returns
A ISystemIdentity representing the user executing tgstation-server.
Implemented in Tgstation.Server.Host.Security.PosixSystemIdentityFactory, and Tgstation.Server.Host.Security.WindowsSystemIdentityFactory.
Referenced by Tgstation.Server.Host.Components.InstanceManager.CheckSystemCompatibility().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Security/ISystemIdentityFactory.cs