tgstation-server: Tgstation.Server.Host.Core.IServerControl Interface Reference
Tgstation.Server.Host.Core.IServerControl Interface Reference
Represents a service that may take an updated Host assembly and run it, stopping the current assembly in the process.
Public Member Functions
bool TryStartUpdate (IServerUpdateExecutor updateExecutor, Version newVersion)
Attempt to update with a given updateExecutor .
IRestartRegistration RegisterForRestart (IRestartHandler handler)
Register a given handler to run before stopping the server for a restart.
ValueTask Restart ()
Restarts the Host.
ValueTask GracefulShutdown (bool detach)
Gracefully shutsdown the Host.
ValueTask Die (Exception? exception)
Kill the server with a fatal exception.
Properties
bool WatchdogPresent [get]
true if live updates are supported, false. TryStartUpdate(IServerUpdateExecutor, Version) and Restart will fail if this is false.
bool UpdateInProgress [get]
Whether or not the server is currently updating.
Detailed Description
Represents a service that may take an updated Host assembly and run it, stopping the current assembly in the process.
Definition at line 9 of file IServerControl.cs.
Member Function Documentation
Die()
ValueTask Tgstation.Server.Host.Core.IServerControl.Die (Exception? exception)
Kill the server with a fatal exception.
Parameters
exception The Exception to propagate to the watchdog if any.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.Server.
Referenced by Tgstation.Server.Host.Core.CommandPipeManager.ExecuteAsync(), and Tgstation.Server.Host.Components.InstanceManager.Initialize().
GracefulShutdown()
ValueTask Tgstation.Server.Host.Core.IServerControl.GracefulShutdown (bool detach)
Gracefully shutsdown the Host.
Parameters
detach If the graceful shutdown should detach any running watchdog. If false the server will wait for the next TgsReboot() or world exit before shutting down.
Returns
A ValueTask representing the running operation.
Implemented in Tgstation.Server.Host.Server.
Referenced by Tgstation.Server.Host.Core.CommandPipeManager.ExecuteAsync(), and Tgstation.Server.Host.System.PosixSignalHandler.SignalChecker().
RegisterForRestart()
IRestartRegistration Tgstation.Server.Host.Core.IServerControl.RegisterForRestart (IRestartHandler handler)
Register a given handler to run before stopping the server for a restart.
Parameters
handler The IRestartHandler to register.
Returns
A new IRestartRegistration representing the scope of the registration.
Implemented in Tgstation.Server.Host.Server.
Referenced by Tgstation.Server.Host.Components.Chat.ChatManager.ChatManager(), Tgstation.Server.Host.System.SystemDManager.SystemDManager(), and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.WatchdogBase().
Restart()
ValueTask Tgstation.Server.Host.Core.IServerControl.Restart ()
Restarts the Host.
Returns
A ValueTask representing the running operation.
Implemented in Tgstation.Server.Host.Server.
Referenced by Tgstation.Server.Host.Authority.AdministrationAuthority.TriggerServerRestart().
TryStartUpdate()
bool Tgstation.Server.Host.Core.IServerControl.TryStartUpdate (IServerUpdateExecutor updateExecutor, Version newVersion)
Attempt to update with a given updateExecutor .
Parameters
updateExecutor The IServerUpdateExecutor to use for the update.
newVersion The Version the IServerControl is updating to.
Returns
true if the update started successfully, false if there was another update in progress.
Implemented in Tgstation.Server.Host.Server.
Referenced by Tgstation.Server.Host.Core.ServerUpdater.BeginUpdateImpl().
Property Documentation
UpdateInProgress
bool Tgstation.Server.Host.Core.IServerControl.UpdateInProgress get
Whether or not the server is currently updating.
Implemented in Tgstation.Server.Host.Server.
Definition at line 19 of file IServerControl.cs.
{ get; }
Referenced by Tgstation.Server.Host.Controllers.ApiRootController.ServerInfo().
WatchdogPresent
bool Tgstation.Server.Host.Core.IServerControl.WatchdogPresent get
true if live updates are supported, false. TryStartUpdate(IServerUpdateExecutor, Version) and Restart will fail if this is false.
Implemented in Tgstation.Server.Host.Server.
Definition at line 14 of file IServerControl.cs.
{ get; }
Referenced by Tgstation.Server.Host.Authority.AdministrationAuthority.TriggerServerRestart(), and Tgstation.Server.Host.Authority.AdministrationAuthority.TriggerServerVersionChange().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Core/IServerControl.cs