tgstation-server: TGServiceInterface.ITGChat Interface Reference
TGServiceInterface.ITGChat Interface Reference
Interface for handling chat bot
Public Member Functions
string SetProviderInfo (TGChatSetupInfo info)
Sets a chat provider info
IList< TGChatSetupInfo > ProviderInfos ()
Returns TGChatSetupInfo for all TGChatProviders
bool Connected (TGChatProvider providerType)
Checks connection status
string Reconnect (TGChatProvider providerType)
Reconnect a specific providerType to it's chat service
Detailed Description
Interface for handling chat bot
Definition at line 10 of file Chat.cs.
Member Function Documentation
bool TGServiceInterface.ITGChat.Connected (TGChatProvider providerType)
Checks connection status
Parameters
providerType The type of provider to check if connected
Returns
if connected, otherwise
Implemented in TGServerService.TGStationServer.
IList<TGChatSetupInfo> TGServiceInterface.ITGChat.ProviderInfos ()
Returns TGChatSetupInfo for all TGChatProviders
Returns
A list of all TGChatSetupInfos
Implemented in TGServerService.TGStationServer.
Referenced by TGControlPanel.Main.LoadChatPage(), TGCommandLine.ChatJoinCommand.Run(), TGCommandLine.ChatPartCommand.Run(), TGCommandLine.ChatAddminCommand.Run(), TGCommandLine.IRCAuthModeCommand.Run(), TGCommandLine.DiscordAuthModeCommand.Run(), TGCommandLine.ChatDeadminCommand.Run(), TGCommandLine.ChatStatusCommand.Run(), TGCommandLine.ChatEnableCommand.Run(), TGCommandLine.ChatDisableCommand.Run(), and TGControlPanel.Main.SetAdminsAreSpecial().
string TGServiceInterface.ITGChat.Reconnect (TGChatProvider providerType)
Reconnect a specific providerType to it's chat service
Parameters
providerType The type of provider to reconnect
Returns
on success, error message string on failure
Implemented in TGServerService.TGStationServer.
string TGServiceInterface.ITGChat.SetProviderInfo (TGChatSetupInfo info)
Sets a chat provider info
Parameters
info The info to set
Implemented in TGServerService.TGStationServer.
Referenced by TGCommandLine.IRCNickCommand.Run(), TGCommandLine.IRCAuthCommand.Run(), TGCommandLine.IRCDisableAuthCommand.Run(), and TGCommandLine.DiscordSetTokenCommand.Run().
The documentation for this interface was generated from the following file:
TGServiceInterface/Chat.cs