tgstation-server: Tgstation.Server.Host.Utils.IPortAllocator Interface Reference
Tgstation.Server.Host.Utils.IPortAllocator Interface Reference
Gets unassigned ports for use by TGS.
Public Member Functions
ValueTask< ushort?> GetAvailablePort (ushort basePort, bool checkOne, CancellationToken cancellationToken)
Gets a port not currently in use by TGS.
Detailed Description
Gets unassigned ports for use by TGS.
Definition at line 9 of file IPortAllocator.cs.
Member Function Documentation
GetAvailablePort()
ValueTask< ushort?> Tgstation.Server.Host.Utils.IPortAllocator.GetAvailablePort (ushort basePort, bool checkOne, CancellationToken cancellationToken)
Gets a port not currently in use by TGS.
Parameters
basePort The port to check first. Will not allocate a port lower than this.
checkOne If only basePort should be checked and no others.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the first available port on success, null on failure.
Implemented in Tgstation.Server.Host.Utils.PortAllocator.
Referenced by Tgstation.Server.Host.Controllers.InstanceController.CreateDefaultInstance(), Tgstation.Server.Host.Controllers.DreamDaemonController.Update(), and Tgstation.Server.Host.Controllers.DreamMakerController.Update().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Utils/IPortAllocator.cs