tgstation-server: Tgstation.Server.Host.System.IProcess Interface Reference
Tgstation.Server.Host.System.IProcess Interface Reference
Abstraction over a global::System.Diagnostics.Process.
Public Member Functions
Task< string > GetErrorOutput (CancellationToken cancellationToken)
Get the stderr output of the IProcess.
Task< string > GetStandardOutput (CancellationToken cancellationToken)
Get the stdout output of the IProcess.
Task< string > GetCombinedOutput (CancellationToken cancellationToken)
Get the stderr and stdout output of the IProcess.
void Terminate ()
Asycnhronously terminates the process.
Task< string > GetExecutingUsername (CancellationToken cancellationToken)
Get the name of the account executing the IProcess.
Public Member Functions inherited from Tgstation.Server.Host.System.IProcessBase
void AdjustPriority (bool higher)
Set's the owned global::System.Diagnostics.Process.PriorityClass to a non-normal value.
void Suspend ()
Suspends the process.
void Resume ()
Resumes the process.
Task CreateDump (string outputFile, CancellationToken cancellationToken)
Create a dump file of the process.
Properties
int Id [get]
The IProcess' ID.
Task Startup [get]
The Task representing the time until the IProcess becomes "idle".
Properties inherited from Tgstation.Server.Host.System.IProcessBase
Task< int > Lifetime [get]
The Task<TResult> resulting in the exit code of the process.
Detailed Description
Abstraction over a global::System.Diagnostics.Process.
Definition at line 10 of file IProcess.cs.
Member Function Documentation
GetCombinedOutput()
Task< string > Tgstation.Server.Host.System.IProcess.GetCombinedOutput (CancellationToken cancellationToken)
Get the stderr and stdout output of the IProcess.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the stderr and stdout output of the IProcess.
Implemented in Tgstation.Server.Host.System.Process.
Referenced by Tgstation.Server.Host.Components.Session.SessionControllerFactory.LaunchNew().
GetErrorOutput()
Task< string > Tgstation.Server.Host.System.IProcess.GetErrorOutput (CancellationToken cancellationToken)
Get the stderr output of the IProcess.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the stderr output of the IProcess.
Implemented in Tgstation.Server.Host.System.Process.
GetExecutingUsername()
Task< string > Tgstation.Server.Host.System.IProcess.GetExecutingUsername (CancellationToken cancellationToken)
Get the name of the account executing the IProcess.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the name of the account executing the IProcess.
Implemented in Tgstation.Server.Host.System.Process.
Referenced by Tgstation.Server.Host.Components.Session.SessionControllerFactory.CheckPagerIsNotRunning().
GetStandardOutput()
Task< string > Tgstation.Server.Host.System.IProcess.GetStandardOutput (CancellationToken cancellationToken)
Get the stdout output of the IProcess.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the stdout output of the IProcess.
Implemented in Tgstation.Server.Host.System.Process.
Terminate()
void Tgstation.Server.Host.System.IProcess.Terminate ()
Asycnhronously terminates the process.
To ensure the IProcess has ended, use the IProcessBase.Lifetime Task<TResult>.
Implemented in Tgstation.Server.Host.System.Process.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.DisposeAsync(), and Tgstation.Server.Host.Components.Session.SessionController.ProcessBridgeRequest().
Property Documentation
Id
int Tgstation.Server.Host.System.IProcess.Id get
The IProcess' ID.
Implemented in Tgstation.Server.Host.System.Process.
Definition at line 15 of file IProcess.cs.
{ get; }
Referenced by Tgstation.Server.Host.System.ProcessExecutor.CreateFromExistingHandle(), and Tgstation.Server.Host.System.WindowsNetworkPromptReaper.RegisterProcess().
Startup
Task Tgstation.Server.Host.System.IProcess.Startup get
The Task representing the time until the IProcess becomes "idle".
Implemented in Tgstation.Server.Host.System.Process.
Definition at line 20 of file IProcess.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Session.SessionController.GetLaunchResult().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/System/IProcess.cs