tgstation-server: Tgstation.Server.Host.Authority.Core.IAuthorityInvoker< TAuthority > Interface Template Reference
Tgstation.Server.Host.Authority.Core.IAuthorityInvoker< TAuthority > Interface Template Reference
Invokes TAuthority s.
Public Member Functions
IQueryable< TResult > InvokeQueryable< TResult > (Func< TAuthority, IQueryable< TResult > > authorityInvoker)
Invoke a TAuthority method and get the result.
IQueryable< TApiModel > InvokeTransformableQueryable< TResult, TApiModel, TTransformer > (Func< TAuthority, IQueryable< TResult > > authorityInvoker)
Invoke a TAuthority method and get the transformed result.
Detailed Description
Invokes TAuthority s.
Template Parameters
TAuthority The IAuthority invoked.
Type Constraints
TAuthority : IAuthority
Definition at line 12 of file IAuthorityInvoker{TAuthority}.cs.
Member Function Documentation
InvokeQueryable< TResult >()
IQueryable< TResult > Tgstation.Server.Host.Authority.Core.IAuthorityInvoker< TAuthority >.InvokeQueryable< TResult > (Func< TAuthority, IQueryable< TResult > > authorityInvoker)
Invoke a TAuthority method and get the result.
Template Parameters
TResult The returned Type.
Parameters
authorityInvoker The TAuthority Func<T, TResult> returning a IQueryable<T> TResult .
Returns
A IQueryable<T> TResult returned.
Implemented in Tgstation.Server.Host.Authority.Core.AuthorityInvokerBase< TAuthority >.
References Tgstation.Server.Host.Authority.Core.IAuthorityInvoker< TAuthority >.InvokeQueryable< TResult >(), and Tgstation.Server.Host.Authority.Core.IAuthorityInvoker< TAuthority >.InvokeTransformableQueryable< TResult, TApiModel, TTransformer >().
Referenced by Tgstation.Server.Host.Authority.Core.IAuthorityInvoker< TAuthority >.InvokeQueryable< TResult >().
InvokeTransformableQueryable< TResult, TApiModel, TTransformer >()
IQueryable< TApiModel > Tgstation.Server.Host.Authority.Core.IAuthorityInvoker< TAuthority >.InvokeTransformableQueryable< TResult, TApiModel, TTransformer > (Func< TAuthority, IQueryable< TResult > > authorityInvoker)
Invoke a TAuthority method and get the transformed result.
Template Parameters
TResult The Type returned by the TAuthority .
TApiModel The returned Type.
TTransformer The ITransformer<TInput, TOutput> for converting TResult s to TApiModel s.
Parameters
authorityInvoker The TAuthority Func<T, TResult> returning a IQueryable<T> TResult .
Returns
A IQueryable<T> TResult returned.
Implemented in Tgstation.Server.Host.Authority.Core.AuthorityInvokerBase< TAuthority >.
Type Constraints
TResult : IApiTransformable
TResult : TResult
TResult : TApiModel
TResult : TTransformer
TApiModel : notnull
TTransformer : ITransformer
TTransformer : TResult
TTransformer : TApiModel
TTransformer : new()
Referenced by Tgstation.Server.Host.Authority.Core.IAuthorityInvoker< TAuthority >.InvokeQueryable< TResult >().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Authority/Core/IAuthorityInvoker{TAuthority}.cs