tgstation-server: Tgstation.Server.Host.Components.Deployment.Remote.IRemoteDeploymentManagerFactory Interface Reference
Tgstation.Server.Host.Components.Deployment.Remote.IRemoteDeploymentManagerFactory Interface Reference
Factory for creating IRemoteDeploymentManagers.
Public Member Functions
IRemoteDeploymentManager CreateRemoteDeploymentManager (Api.Models.Instance metadata, RemoteGitProvider remoteGitProvider)
Creates a IRemoteDeploymentManager for a given remoteGitProvider .
IRemoteDeploymentManager CreateRemoteDeploymentManager (Api.Models.Instance metadata, Models.CompileJob compileJob)
Create a IRemoteDeploymentManager for a given compileJob .
void ForgetLocalStateForCompileJobs (IEnumerable< long > compileJobsIds)
Cause the IRemoteDeploymentManagerFactory to drop any local state is has for the given compileJobsIds .
Detailed Description
Factory for creating IRemoteDeploymentManagers.
Definition at line 10 of file IRemoteDeploymentManagerFactory.cs.
Member Function Documentation
CreateRemoteDeploymentManager() [1/2]
IRemoteDeploymentManager Tgstation.Server.Host.Components.Deployment.Remote.IRemoteDeploymentManagerFactory.CreateRemoteDeploymentManager (Api.Models.Instance metadata, Models.CompileJob compileJob)
Create a IRemoteDeploymentManager for a given compileJob .
Parameters
metadata Current Api.Models.Instance metadata.
compileJob The Models.CompileJob containing the Api.Models.Response.CompileJobResponse.RepositoryOrigin to use.
Returns
A new IRemoteDeploymentManager.
Implemented in Tgstation.Server.Host.Components.Deployment.Remote.RemoteDeploymentManagerFactory.
CreateRemoteDeploymentManager() [2/2]
IRemoteDeploymentManager Tgstation.Server.Host.Components.Deployment.Remote.IRemoteDeploymentManagerFactory.CreateRemoteDeploymentManager (Api.Models.Instance metadata, RemoteGitProvider remoteGitProvider)
Creates a IRemoteDeploymentManager for a given remoteGitProvider .
Parameters
metadata Current Api.Models.Instance metadata.
remoteGitProvider The RemoteGitProvider in use.
Returns
A new IRemoteDeploymentManager based on the remoteGitProvider .
Implemented in Tgstation.Server.Host.Components.Deployment.Remote.RemoteDeploymentManagerFactory.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.BeforeApplyDmb(), Tgstation.Server.Host.Components.Deployment.DmbFactory.CleanRegisteredCompileJob(), Tgstation.Server.Host.Components.Deployment.DreamMaker.DeploymentProcess(), Tgstation.Server.Host.Components.Deployment.DmbFactory.LoadCompileJob(), and Tgstation.Server.Host.Components.Instance.RepositoryAutoUpdateJob().
ForgetLocalStateForCompileJobs()
void Tgstation.Server.Host.Components.Deployment.Remote.IRemoteDeploymentManagerFactory.ForgetLocalStateForCompileJobs (IEnumerable< long > compileJobsIds)
Cause the IRemoteDeploymentManagerFactory to drop any local state is has for the given compileJobsIds .
Parameters
compileJobsIds An IEnumerable<T> of Models.CompileJob EntityId.Ids.
Implemented in Tgstation.Server.Host.Components.Deployment.Remote.RemoteDeploymentManagerFactory.
Referenced by Tgstation.Server.Host.Components.Deployment.DmbFactory.StopAsync().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Components/Deployment/Remote/IRemoteDeploymentManagerFactory.cs