tgstation-server: Tgstation.Server.Common.IAbstractHttpClientFactory Interface Reference
Tgstation.Server.Common.IAbstractHttpClientFactory Interface Reference
Creates IHttpClients.
Public Member Functions
IHttpClient CreateClient ()
Create a IHttpClient.
Detailed Description
Creates IHttpClients.
Definition at line 6 of file IAbstractHttpClientFactory.cs.
Member Function Documentation
CreateClient()
IHttpClient Tgstation.Server.Common.IAbstractHttpClientFactory.CreateClient ()
Create a IHttpClient.
Returns
A new IHttpClient.
Implemented in Tgstation.Server.Common.HttpClientFactory, and Tgstation.Server.Host.Utils.AbstractHttpClientFactory.
Referenced by Tgstation.Server.Host.Swarm.SwarmService.AbortUpdate(), Tgstation.Server.Host.Swarm.SwarmService.CommitUpdate(), Tgstation.Server.Host.Security.OAuth.GenericOAuthValidator.CreateHttpClient(), Tgstation.Server.Host.IO.FileDownloader.DownloadFile(), Tgstation.Server.Host.Swarm.SwarmService.HealthCheckController(), Tgstation.Server.Host.Swarm.SwarmService.HealthCheckNodes(), Tgstation.Server.Host.Swarm.SwarmService.PrepareUpdateImpl(), Tgstation.Server.Host.Swarm.SwarmService.RegisterWithController(), Tgstation.Server.Host.Swarm.SwarmService.SendUpdatedServerListToNodes(), and Tgstation.Server.Host.Swarm.SwarmService.Shutdown().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Common/IAbstractHttpClientFactory.cs