tgstation-server: Tgstation.Server.Host.Core.IProcessExecutor Interface Reference
Tgstation.Server.Host.Core.IProcessExecutor Interface Reference
For launching IProcess'
Public Member Functions
IProcess LaunchProcess (string fileName, string workingDirectory, string arguments=null, bool readOutput=false, bool readError=false, bool noShellExecute=false)
Launch a IProcess
IProcess GetProcess (int id)
Get a IProcess by id
Detailed Description
For launching IProcess'
Definition at line 6 of file IProcessExecutor.cs.
Member Function Documentation
GetProcess()
IProcess Tgstation.Server.Host.Core.IProcessExecutor.GetProcess (int id)
Get a IProcess by id
Parameters
id The IProcess.Id
Returns
The IProcess represented by id on success, null on failure
Implemented in Tgstation.Server.Host.Core.ProcessExecutor.
Referenced by Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.Reattach().
LaunchProcess()
IProcess Tgstation.Server.Host.Core.IProcessExecutor.LaunchProcess (string fileName, string workingDirectory, string arguments = null, bool readOutput = false, bool readError = false, bool noShellExecute = false)
Launch a IProcess
Parameters
fileName The full path to the executable file
workingDirectory The working directory for the IProcess
arguments The arguments for the IProcess
readOutput If standard output should be read
readError If standard error should be read
noShellExecute If shell execute should not be used. Ignored if readError or readOutput are set
Returns
A new IProcess
Implemented in Tgstation.Server.Host.Core.ProcessExecutor.
Referenced by Tgstation.Server.Host.Components.Byond.WindowsByondInstaller.InstallByond(), Tgstation.Server.Host.Components.Watchdog.SessionControllerFactory.LaunchNew(), and Tgstation.Server.Host.Components.Compiler.DreamMaker.RunDreamMaker().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Core/IProcessExecutor.cs