tgstation-server: TGS.Server.ILogger Interface Reference
TGS.Server.ILogger Interface Reference
Used for writing logs to a provider
Public Member Functions
void WriteInfo (string message, EventID id, byte loggingID)
Writes information to the log
void WriteError (string message, EventID id, byte loggingID)
Writes an error to the log
void WriteWarning (string message, EventID id, byte loggingID)
Writes a warning to the log
void WriteAccess (string username, bool authSuccess, byte loggingID)
Writes an access event to the log
Detailed Description
Used for writing logs to a provider
Definition at line 6 of file ILogger.cs.
Member Function Documentation
void TGS.Server.ILogger.WriteAccess (string username, bool authSuccess, byte loggingID)
Writes an access event to the log
Parameters
username The (un)authenticated Windows user's name
authSuccess if username authenticated sucessfully, otherwise
loggingID The 0-99 ID of the log source
Implemented in TGS.Server.Console.Console, and TGS.Server.Service.Service.
Referenced by TGS.Server.Security.RootAuthorizationManager.CheckAccessCore(), and TGS.Server.Instance.WriteAccess().
void TGS.Server.ILogger.WriteError (string message, EventID id, byte loggingID)
Writes an error to the log
Parameters
message The log message
id The EventID of the message
loggingID The 0-99 ID of the log source
Implemented in TGS.Server.Console.Console, and TGS.Server.Service.Service.
Referenced by TGS.Server.Instance.WriteError().
void TGS.Server.ILogger.WriteInfo (string message, EventID id, byte loggingID)
Writes information to the log
Parameters
message The log message
id The EventID of the message
loggingID The 0-99 ID of the log source
Implemented in TGS.Server.Console.Console, and TGS.Server.Service.Service.
Referenced by TGS.Server.Instance.WriteInfo().
void TGS.Server.ILogger.WriteWarning (string message, EventID id, byte loggingID)
Writes a warning to the log
Parameters
message The log message
id The EventID of the message
loggingID The 0-99 ID of the log source
Implemented in TGS.Server.Console.Console, and TGS.Server.Service.Service.
Referenced by TGS.Server.Instance.WriteWarning().
The documentation for this interface was generated from the following file:
TGS.Server/ILogger.cs