tgstation-server: TGServiceInterface.Components.ITGChat Interface Reference
TGServiceInterface.Components.ITGChat Interface Reference
Interface for handling chat bot
Public Member Functions
string SetProviderInfo (ChatSetupInfo info)
Sets a chat provider info
IList< ChatSetupInfo > ProviderInfos ()
Returns ChatSetupInfo for all ChatProviders
bool Connected (ChatProvider providerType)
Checks connection status
string Reconnect (ChatProvider providerType)
Reconnect a specific providerType to it's chat service
Detailed Description
Interface for handling chat bot
Definition at line 10 of file Chat.cs.
Member Function Documentation
bool TGServiceInterface.Components.ITGChat.Connected (ChatProvider providerType)
Checks connection status
Parameters
providerType The type of provider to check if connected
Returns
if connected, otherwise
Implemented in TGServerService.ServerInstance.
IList<ChatSetupInfo> TGServiceInterface.Components.ITGChat.ProviderInfos ()
Returns ChatSetupInfo for all ChatProviders
Returns
A list of all ChatSetupInfos
Implemented in TGServerService.ServerInstance.
Referenced by TGControlPanel.ControlPanel.LoadChatPage(), TGCommandLine.ChatJoinCommand.Run(), TGCommandLine.ChatPartCommand.Run(), TGCommandLine.ChatAddminCommand.Run(), TGCommandLine.IRCAuthModeCommand.Run(), TGCommandLine.DiscordAuthModeCommand.Run(), TGCommandLine.ChatDeadminCommand.Run(), TGCommandLine.ChatStatusCommand.Run(), TGCommandLine.ChatEnableCommand.Run(), TGCommandLine.ChatDisableCommand.Run(), and TGControlPanel.ControlPanel.SetAdminsAreSpecial().
string TGServiceInterface.Components.ITGChat.Reconnect (ChatProvider providerType)
Reconnect a specific providerType to it's chat service
Parameters
providerType The type of provider to reconnect
Returns
on success, error message string on failure
Implemented in TGServerService.ServerInstance.
string TGServiceInterface.Components.ITGChat.SetProviderInfo (ChatSetupInfo info)
Sets a chat provider info
Parameters
info The info to set
Implemented in TGServerService.ServerInstance.
Referenced by TGCommandLine.IRCNickCommand.Run(), TGCommandLine.IRCAuthCommand.Run(), TGCommandLine.IRCDisableAuthCommand.Run(), and TGCommandLine.DiscordSetTokenCommand.Run().
The documentation for this interface was generated from the following file:
TGServiceInterface/Components/Chat.cs