tgstation-server: TGServiceInterface.Components.ITGInstanceManager Interface Reference
TGServiceInterface.Components.ITGInstanceManager Interface Reference
Used for managing ITGInstances
Public Member Functions
string CreateInstance (string Name, string path)
Creates a new ITGInstance
string ImportInstance (string path)
Registers an existing server instance
bool InstanceEnabled (string Name)
Checks if an instance is online
string SetInstanceEnabled (string Name, bool enabled)
Sets an instance's enabled status
string RenameInstance (string name, string new_name)
Renames an instance, this will restart the instance if it is enabled
string DetachInstance (string name)
Disables and unregisters an instance, allowing the folder and data to be manipulated manually
Detailed Description
Used for managing ITGInstances
Definition at line 9 of file InstanceManager.cs.
Member Function Documentation
string TGServiceInterface.Components.ITGInstanceManager.CreateInstance (string Name, string path)
Creates a new ITGInstance
Parameters
Name The name of the instance
path The path to the instance
Returns
on success, error message on failure
Implemented in TGServerService.Service.
Referenced by TGControlPanel.InstanceSelector.CreateInstanceButton_Click().
string TGServiceInterface.Components.ITGInstanceManager.DetachInstance (string name)
Disables and unregisters an instance, allowing the folder and data to be manipulated manually
Parameters
name The instance to detach
Returns
on success, error message on failure
Implemented in TGServerService.Service.
Referenced by TGControlPanel.InstanceSelector.DetachInstanceButton_Click().
string TGServiceInterface.Components.ITGInstanceManager.ImportInstance (string path)
Registers an existing server instance
Parameters
path The path to the instance
Returns
on success, error message on failure
Implemented in TGServerService.Service.
Referenced by TGControlPanel.InstanceSelector.ImportInstanceButton_Click().
bool TGServiceInterface.Components.ITGInstanceManager.InstanceEnabled (string Name)
Checks if an instance is online
Parameters
Name The name of the instance
Returns
if the Instance exists and is online, otherwise
Implemented in TGServerService.Service.
string TGServiceInterface.Components.ITGInstanceManager.RenameInstance (string name, string new_name)
Renames an instance, this will restart the instance if it is enabled
Parameters
name The current name of the instance
new_name The new name of the instance
Returns
on success, error message on failure
Implemented in TGServerService.Service.
Referenced by TGControlPanel.InstanceSelector.RenameInstanceButton_Click().
string TGServiceInterface.Components.ITGInstanceManager.SetInstanceEnabled (string Name, bool enabled)
Sets an instance's enabled status
Parameters
Name The instance whom's status should be changed
enabled to enable the instance, to disable it
Returns
on success, error message on failure
Implemented in TGServerService.Service.
Referenced by TGControlPanel.InstanceSelector.EnabledCheckBox_CheckedChanged().
The documentation for this interface was generated from the following file:
TGServiceInterface/Components/InstanceManager.cs