tgstation-server: Tgstation.Server.Host.Database.IDatabaseContextFactory Interface Reference
Tgstation.Server.Host.Database.IDatabaseContextFactory Interface Reference
Factory for scoping usage of IDatabaseContexts. Meant for use by Components.
Public Member Functions
ValueTask UseContext (Func< IDatabaseContext, ValueTask > operation)
Run an operation in the scope of an IDatabaseContext.
ValueTask UseContextTaskReturn (Func< IDatabaseContext, Task > operation)
Run an operation in the scope of an IDatabaseContext.
Detailed Description
Factory for scoping usage of IDatabaseContexts. Meant for use by Components.
Definition at line 9 of file IDatabaseContextFactory.cs.
Member Function Documentation
UseContext()
ValueTask Tgstation.Server.Host.Database.IDatabaseContextFactory.UseContext (Func< IDatabaseContext, ValueTask > operation)
Run an operation in the scope of an IDatabaseContext.
Parameters
operation The operation to run.
Returns
A ValueTask representing the running operation .
Implemented in Tgstation.Server.Host.Database.DatabaseContextFactory.
Referenced by Tgstation.Server.Host.Jobs.JobService.CancelJob(), Tgstation.Server.Host.Components.Deployment.DmbFactory.CleanUnusedCompileJobs(), Tgstation.Server.Host.Components.Deployment.DreamMaker.DeploymentProcess(), Tgstation.Server.Host.Components.Deployment.DmbFactory.FromCompileJobInternal(), Tgstation.Server.Host.Utils.PortAllocator.GetAvailablePort(), Tgstation.Server.Host.Security.AuthorizationHandler.HandleRightsConditionalRequirement< TRights >(), Tgstation.Server.Host.Security.AuthorizationHandler.HandleSessionValidRequirement(), Tgstation.Server.Host.Components.InstanceManager.Initialize(), Tgstation.Server.Host.Swarm.SwarmService.Initialize(), Tgstation.Server.Host.Components.Chat.Commands.PullRequestsCommand.Invoke(), Tgstation.Server.Host.Components.Session.SessionPersistor.Load(), Tgstation.Server.Host.Jobs.JobsHubGroupMapper.MapConnectionGroups(), Tgstation.Server.Host.Components.InstanceManager.OfflineInstance(), Tgstation.Server.Host.Jobs.JobService.RegisterOperation(), Tgstation.Server.Host.Jobs.JobService.RunJob(), Tgstation.Server.Host.Swarm.SwarmService.Shutdown(), Tgstation.Server.Host.Components.Deployment.DmbFactory.StartAsync(), Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.StartDeployment(), and Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.UpdateDeployment().
UseContextTaskReturn()
ValueTask Tgstation.Server.Host.Database.IDatabaseContextFactory.UseContextTaskReturn (Func< IDatabaseContext, Task > operation)
Run an operation in the scope of an IDatabaseContext.
Parameters
operation The operation to run.
Returns
A ValueTask representing the running operation .
Implemented in Tgstation.Server.Host.Database.DatabaseContextFactory.
Referenced by Tgstation.Server.Host.Components.InstanceManager.MoveInstance().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Database/IDatabaseContextFactory.cs