tgstation-server: Tgstation.Server.Host.Components.Byond.IByondManager Interface Reference
Tgstation.Server.Host.Components.Byond.IByondManager Interface Reference
For managing the BYOND installation.
Public Member Functions
ValueTask ChangeVersion (JobProgressReporter progressReporter, Version version, Stream customVersionStream, bool allowInstallation, CancellationToken cancellationToken)
Change the active BYOND version.
ValueTask DeleteVersion (JobProgressReporter progressReporter, Version version, CancellationToken cancellationToken)
Deletes a given BYOND version from the disk.
ValueTask< IByondExecutableLock > UseExecutables (Version requiredVersion, string trustDmbFullPath, CancellationToken cancellationToken)
Lock the current installation's location and return a IByondExecutableLock.
Properties
Version ActiveVersion [get]
The currently active BYOND version.
IReadOnlyList< Version > InstalledVersions [get]
The installed BYOND versions.
Detailed Description
For managing the BYOND installation.
When passing in Versions, ensure they are BYOND format versions unless referring to a custom version. This means Version.Build should NEVER be 0.
Definition at line 15 of file IByondManager.cs.
Member Function Documentation
ChangeVersion()
ValueTask Tgstation.Server.Host.Components.Byond.IByondManager.ChangeVersion (JobProgressReporter progressReporter, Version version, Stream customVersionStream, bool allowInstallation, CancellationToken cancellationToken)
Change the active BYOND version.
Parameters
progressReporter The optional JobProgressReporter for the operation.
version The new Version.
customVersionStream Optional Stream of a custom BYOND version zip file.
allowInstallation If an installation should be performed if the version is not installed. If false and an installation is required an InvalidOperationException will be thrown.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implemented in Tgstation.Server.Host.Components.Byond.ByondManager.
DeleteVersion()
ValueTask Tgstation.Server.Host.Components.Byond.IByondManager.DeleteVersion (JobProgressReporter progressReporter, Version version, CancellationToken cancellationToken)
Deletes a given BYOND version from the disk.
Parameters
progressReporter The JobProgressReporter for the operation.
version The Version to delete.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implemented in Tgstation.Server.Host.Components.Byond.ByondManager.
UseExecutables()
ValueTask< IByondExecutableLock > Tgstation.Server.Host.Components.Byond.IByondManager.UseExecutables (Version requiredVersion, string trustDmbFullPath, CancellationToken cancellationToken)
Lock the current installation's location and return a IByondExecutableLock.
Parameters
requiredVersion The BYOND Version required.
trustDmbFullPath The optional full path to .dmb to trust while using the executables.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the requested IByondExecutableLock.
Implemented in Tgstation.Server.Host.Components.Byond.ByondManager.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.Compile(), Tgstation.Server.Host.Components.Session.SessionControllerFactory.LaunchNew(), and Tgstation.Server.Host.Components.Session.SessionControllerFactory.Reattach().
Property Documentation
ActiveVersion
Version Tgstation.Server.Host.Components.Byond.IByondManager.ActiveVersion get
The currently active BYOND version.
Implemented in Tgstation.Server.Host.Components.Byond.ByondManager.
Definition at line 20 of file IByondManager.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Chat.Commands.ByondCommand.Invoke().
InstalledVersions
IReadOnlyList<Version> Tgstation.Server.Host.Components.Byond.IByondManager.InstalledVersions get
The installed BYOND versions.
Implemented in Tgstation.Server.Host.Components.Byond.ByondManager.
Definition at line 25 of file IByondManager.cs.
{ get; }
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Components/Byond/IByondManager.cs