tgstation-server: Tgstation.Server.Host.IServerFactory Interface Reference
Tgstation.Server.Host.IServerFactory Interface Reference
For creating IServers
Public Member Functions
IServer CreateServer (string[] args, string updatePath)
Create a IServer
Detailed Description
For creating IServers
Definition at line 6 of file IServerFactory.cs.
Member Function Documentation
CreateServer()
IServer Tgstation.Server.Host.IServerFactory.CreateServer (string [] args, string updatePath)
Create a IServer
Parameters
args The arguments for the IServer
updatePath The directory in which to install server updates
Returns
A new IServer
Implemented in Tgstation.Server.Host.ServerFactory.
Referenced by Tgstation.Server.Tests.TestingServer.TestingServer(), Tgstation.Server.Host.Tests.TestServerFactory.TestWorksWithoutUpdatePath(), and Tgstation.Server.Host.Tests.TestServerFactory.TestWorksWithUpdatePath().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/IServerFactory.cs