tgstation-server: Tgstation.Server.Host.Security.ISystemIdentity Interface Reference
Tgstation.Server.Host.Security.ISystemIdentity Interface Reference
Represents a user on the current global::System.Runtime.InteropServices.OSPlatform.
Public Member Functions
ISystemIdentity Clone ()
Clone the ISystemIdentity creating another copy that must have IDisposable.Dispose called on it.
Task RunImpersonated (Action action, CancellationToken cancellationToken)
Runs a given action in the context of the ISystemIdentity.
Properties
string Uid [get]
A unique identifier for the user.
string Username [get]
The user's name.
bool CanCreateSymlinks [get]
If this system identity has permissions to create symlinks.
bool IsSuperUser [get]
Is this identity a SuperUser for the OS. See Administrator on Windows or root on Linux.
Detailed Description
Represents a user on the current global::System.Runtime.InteropServices.OSPlatform.
Definition at line 10 of file ISystemIdentity.cs.
Member Function Documentation
Clone()
ISystemIdentity Tgstation.Server.Host.Security.ISystemIdentity.Clone ()
Clone the ISystemIdentity creating another copy that must have IDisposable.Dispose called on it.
Returns
A new ISystemIdentity mirroring the current one.
Implemented in Tgstation.Server.Host.Security.PosixSystemIdentity, and Tgstation.Server.Host.Security.WindowsSystemIdentity.
Referenced by Tgstation.Server.Host.Security.IdentityCache.CacheSystemIdentity().
RunImpersonated()
Task Tgstation.Server.Host.Security.ISystemIdentity.RunImpersonated (Action action, CancellationToken cancellationToken)
Runs a given action in the context of the ISystemIdentity.
Parameters
action The Action to perform, should be simple and not use any Tasks or threading.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.Security.PosixSystemIdentity, and Tgstation.Server.Host.Security.WindowsSystemIdentity.
Referenced by Tgstation.Server.Host.Components.StaticFiles.Configuration.CreateDirectory(), Tgstation.Server.Host.Components.StaticFiles.Configuration.DeleteDirectory(), Tgstation.Server.Host.Components.StaticFiles.Configuration.ListDirectory(), Tgstation.Server.Host.Components.StaticFiles.Configuration.Read(), and Tgstation.Server.Host.Components.StaticFiles.Configuration.Write().
Property Documentation
CanCreateSymlinks
bool Tgstation.Server.Host.Security.ISystemIdentity.CanCreateSymlinks get
If this system identity has permissions to create symlinks.
Implemented in Tgstation.Server.Host.Security.PosixSystemIdentity, and Tgstation.Server.Host.Security.WindowsSystemIdentity.
Definition at line 25 of file ISystemIdentity.cs.
{ get; }
IsSuperUser
bool Tgstation.Server.Host.Security.ISystemIdentity.IsSuperUser get
Is this identity a SuperUser for the OS. See Administrator on Windows or root on Linux.
Implemented in Tgstation.Server.Host.Security.PosixSystemIdentity, and Tgstation.Server.Host.Security.WindowsSystemIdentity.
Definition at line 31 of file ISystemIdentity.cs.
{ get; }
Uid
string Tgstation.Server.Host.Security.ISystemIdentity.Uid get
A unique identifier for the user.
Implemented in Tgstation.Server.Host.Security.PosixSystemIdentity, and Tgstation.Server.Host.Security.WindowsSystemIdentity.
Definition at line 15 of file ISystemIdentity.cs.
{ get; }
Referenced by Tgstation.Server.Host.Authority.LoginAuthority.AttemptLogin(), and Tgstation.Server.Host.Security.IdentityCache.CacheSystemIdentity().
Username
string Tgstation.Server.Host.Security.ISystemIdentity.Username get
The user's name.
Implemented in Tgstation.Server.Host.Security.PosixSystemIdentity, and Tgstation.Server.Host.Security.WindowsSystemIdentity.
Definition at line 20 of file ISystemIdentity.cs.
{ get; }
Referenced by Tgstation.Server.Host.Authority.LoginAuthority.AttemptLogin().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Security/ISystemIdentity.cs