tgstation-server: Tgstation.Server.Host.Utils.GitHub.IGitHubServiceFactory Interface Reference
Tgstation.Server.Host.Utils.GitHub.IGitHubServiceFactory Interface Reference
Factory for IGitHubServices.
Public Member Functions
ValueTask< IGitHubService > CreateService (CancellationToken cancellationToken)
Create a IGitHubService.
ValueTask< IAuthenticatedGitHubService > CreateService (string accessToken, CancellationToken cancellationToken)
Create an IAuthenticatedGitHubService.
ValueTask< IAuthenticatedGitHubService?> CreateService (string accessString, RepositoryIdentifier repositoryIdentifier, CancellationToken cancellationToken)
Create an IAuthenticatedGitHubService.
Detailed Description
Factory for IGitHubServices.
Definition at line 9 of file IGitHubServiceFactory.cs.
Member Function Documentation
CreateService() [1/3]
ValueTask< IGitHubService > Tgstation.Server.Host.Utils.GitHub.IGitHubServiceFactory.CreateService (CancellationToken cancellationToken)
Create a IGitHubService.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a new IGitHubService.
Implemented in Tgstation.Server.Host.Utils.GitHub.GitHubServiceFactory.
Referenced by Tgstation.Server.Host.Core.ServerUpdater.BeginUpdateImpl(), Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.CommentOnTestMergeSource(), Tgstation.Server.Host.Components.Repository.GitHubRemoteFeatures.GetTestMergeImpl(), Tgstation.Server.Host.Authority.AdministrationAuthority.GetUpdateInformation(), Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.RemoveMergedTestMerges(), Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.StartDeployment(), Tgstation.Server.Host.Components.Repository.GitHubRemoteFeatures.TransformRepositoryPassword(), Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.UpdateDeployment(), and Tgstation.Server.Host.Security.OAuth.GitHubOAuthValidator.ValidateResponseCode().
CreateService() [2/3]
ValueTask< IAuthenticatedGitHubService?> Tgstation.Server.Host.Utils.GitHub.IGitHubServiceFactory.CreateService (string accessString, RepositoryIdentifier repositoryIdentifier, CancellationToken cancellationToken)
Create an IAuthenticatedGitHubService.
Parameters
accessString The access token to use for communication with GitHub.
repositoryIdentifier The RepositoryIdentifier for the repository the service will be talking with.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a new IAuthenticatedGitHubService.
Implemented in Tgstation.Server.Host.Utils.GitHub.GitHubServiceFactory.
CreateService() [3/3]
ValueTask< IAuthenticatedGitHubService > Tgstation.Server.Host.Utils.GitHub.IGitHubServiceFactory.CreateService (string accessToken, CancellationToken cancellationToken)
Create an IAuthenticatedGitHubService.
Parameters
accessToken The access token to use for communication with GitHub.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a new IAuthenticatedGitHubService.
Implemented in Tgstation.Server.Host.Utils.GitHub.GitHubServiceFactory.
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Utils/GitHub/IGitHubServiceFactory.cs