tgstation-server: Tgstation.Server.Host.Components.Deployment.Remote.IRemoteDeploymentManager Interface Reference
Tgstation.Server.Host.Components.Deployment.Remote.IRemoteDeploymentManager Interface Reference
Creates and updates remote deployments.
Public Member Functions
Task StartDeployment (Api.Models.Internal.IGitRemoteInformation remoteInformation, CompileJob compileJob, CancellationToken cancellationToken)
Start a deployment for a given compileJob .
Task StageDeployment (CompileJob compileJob, CancellationToken cancellationToken)
Stage a given compileJob 's deployment.
Task ApplyDeployment (CompileJob compileJob, CompileJob oldCompileJob, CancellationToken cancellationToken)
Stage a given compileJob 's deployment.
Task FailDeployment (CompileJob compileJob, string errorMessage, CancellationToken cancellationToken)
Fail a deployment for a given compileJob .
Task MarkInactive (CompileJob compileJob, CancellationToken cancellationToken)
Mark the deplotment for a given compileJob as inactive.
Task PostDeploymentComments (CompileJob compileJob, RevisionInformation previousRevisionInformation, RepositorySettings repositorySettings, string repoOwner, string repoName, CancellationToken cancellationToken)
Post deployment comments to the test merge ticket.
Task< IReadOnlyCollection< TestMerge > > RemoveMergedTestMerges (IRepository repository, RepositorySettings repositorySettings, RevisionInformation revisionInformation, CancellationToken cancellationToken)
Get the updated list of TestMerges for an origin merge.
Detailed Description
Creates and updates remote deployments.
Definition at line 13 of file IRemoteDeploymentManager.cs.
Member Function Documentation
ApplyDeployment()
Task Tgstation.Server.Host.Components.Deployment.Remote.IRemoteDeploymentManager.ApplyDeployment (CompileJob compileJob, CompileJob oldCompileJob, CancellationToken cancellationToken)
Stage a given compileJob 's deployment.
Parameters
compileJob The CompileJob being applied.
oldCompileJob The currently active CompileJob, if any.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager, Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager, Tgstation.Server.Host.Components.Deployment.Remote.GitLabRemoteDeploymentManager, and Tgstation.Server.Host.Components.Deployment.Remote.NoOpRemoteDeploymentManager.
Referenced by Tgstation.Server.Host.Components.Watchdog.WatchdogBase.BeforeApplyDmb().
FailDeployment()
Task Tgstation.Server.Host.Components.Deployment.Remote.IRemoteDeploymentManager.FailDeployment (CompileJob compileJob, string errorMessage, CancellationToken cancellationToken)
Fail a deployment for a given compileJob .
Parameters
compileJob The failed CompileJob.
errorMessage The error message.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager, Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager, Tgstation.Server.Host.Components.Deployment.Remote.GitLabRemoteDeploymentManager, and Tgstation.Server.Host.Components.Deployment.Remote.NoOpRemoteDeploymentManager.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.CleanupFailedCompile().
MarkInactive()
Task Tgstation.Server.Host.Components.Deployment.Remote.IRemoteDeploymentManager.MarkInactive (CompileJob compileJob, CancellationToken cancellationToken)
Mark the deplotment for a given compileJob as inactive.
Parameters
compileJob The inactive CompileJob.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager, Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager, Tgstation.Server.Host.Components.Deployment.Remote.GitLabRemoteDeploymentManager, and Tgstation.Server.Host.Components.Deployment.Remote.NoOpRemoteDeploymentManager.
Referenced by Tgstation.Server.Host.Components.Deployment.DmbFactory.CleanRegisteredCompileJob().
PostDeploymentComments()
Task Tgstation.Server.Host.Components.Deployment.Remote.IRemoteDeploymentManager.PostDeploymentComments (CompileJob compileJob, RevisionInformation previousRevisionInformation, RepositorySettings repositorySettings, string repoOwner, string repoName, CancellationToken cancellationToken)
Post deployment comments to the test merge ticket.
Parameters
compileJob The deployed CompileJob.
previousRevisionInformation The RevisionInformation of the previous deployment.
repositorySettings The RepositorySettings.
repoOwner The GitHub repostiory owner.
repoName The GitHub repostiory name.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager, and Tgstation.Server.Host.Components.Deployment.Remote.NoOpRemoteDeploymentManager.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.DeploymentProcess().
RemoveMergedTestMerges()
Task< IReadOnlyCollection< TestMerge > > Tgstation.Server.Host.Components.Deployment.Remote.IRemoteDeploymentManager.RemoveMergedTestMerges (IRepository repository, RepositorySettings repositorySettings, RevisionInformation revisionInformation, CancellationToken cancellationToken)
Get the updated list of TestMerges for an origin merge.
Parameters
repository The IRepository to use.
repositorySettings The RepositorySettings.
revisionInformation The current RevisionInformation.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the IReadOnlyCollection<T> of TestMerges that should remain the new RevisionInformation.
Implemented in Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager, Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager, Tgstation.Server.Host.Components.Deployment.Remote.GitLabRemoteDeploymentManager, and Tgstation.Server.Host.Components.Deployment.Remote.NoOpRemoteDeploymentManager.
Referenced by Tgstation.Server.Host.Components.Instance.RepositoryAutoUpdateJob().
StageDeployment()
Task Tgstation.Server.Host.Components.Deployment.Remote.IRemoteDeploymentManager.StageDeployment (CompileJob compileJob, CancellationToken cancellationToken)
Stage a given compileJob 's deployment.
Parameters
compileJob The staged CompileJob.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager, Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager, Tgstation.Server.Host.Components.Deployment.Remote.GitLabRemoteDeploymentManager, and Tgstation.Server.Host.Components.Deployment.Remote.NoOpRemoteDeploymentManager.
Referenced by Tgstation.Server.Host.Components.Deployment.DmbFactory.LoadCompileJob().
StartDeployment()
Task Tgstation.Server.Host.Components.Deployment.Remote.IRemoteDeploymentManager.StartDeployment (Api.Models.Internal.IGitRemoteInformation remoteInformation, CompileJob compileJob, CancellationToken cancellationToken)
Start a deployment for a given compileJob .
Parameters
remoteInformation The Api.Models.Internal.IGitRemoteInformation of the repository being deployed.
compileJob The active CompileJob.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.Components.Deployment.Remote.BaseRemoteDeploymentManager, Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager, Tgstation.Server.Host.Components.Deployment.Remote.GitLabRemoteDeploymentManager, and Tgstation.Server.Host.Components.Deployment.Remote.NoOpRemoteDeploymentManager.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.Compile().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Components/Deployment/Remote/IRemoteDeploymentManager.cs