tgstation-server: TGS.Interface.Components.ITGLanding Interface Reference
TGS.Interface.Components.ITGLanding Interface Reference
Used for general authentication and listing ITGInstances
Public Member Functions
string Version ()
Retrieve's the service's version
IList< InstanceMetadata > ListInstances ()
List instances that the caller can access
Detailed Description
Used for general authentication and listing ITGInstances
Definition at line 10 of file Landing.cs.
Member Function Documentation
IList<InstanceMetadata> TGS.Interface.Components.ITGLanding.ListInstances ()
List instances that the caller can access
Returns
A IDictionary<TKey, TValue> of instance names relating to their paths
Implemented in TGS.Server.Server.
Referenced by TGS.Installer.UI.Main.AttemptMigrationOfNetSettings(), and TGS.CommandLine.ServiceListInstancesCommand.Run().
string TGS.Interface.Components.ITGLanding.Version ()
Retrieve's the service's version
Returns
The service's version
Implemented in TGS.Server.Server.
Referenced by TGS.CommandLine.Program.RunCommandLine().
The documentation for this interface was generated from the following file:
TGS.Interface/Components/Landing.cs