tgstation-server: Tgstation.Server.Host.IO.IPostWriteHandler Interface Reference
Tgstation.Server.Host.IO.IPostWriteHandler Interface Reference
Handles changing file modes/permissions after writing.
Public Member Functions
bool NeedsPostWrite (string sourceFilePath)
Check if a given sourceFilePath will need HandleWrite(string) called on a copy of it.
void HandleWrite (string filePath)
For handling system specific necessities after a write.
Detailed Description
Handles changing file modes/permissions after writing.
Definition at line 6 of file IPostWriteHandler.cs.
Member Function Documentation
HandleWrite()
void Tgstation.Server.Host.IO.IPostWriteHandler.HandleWrite (string filePath)
For handling system specific necessities after a write.
Parameters
filePath The full path to the file that was written.
Implemented in Tgstation.Server.Host.IO.PosixPostWriteHandler, and Tgstation.Server.Host.IO.WindowsPostWriteHandler.
Referenced by Tgstation.Server.Host.Components.Repository.Repository.CopyTo(), and Tgstation.Server.Host.Components.Engine.PosixByondInstaller.Install().
NeedsPostWrite()
bool Tgstation.Server.Host.IO.IPostWriteHandler.NeedsPostWrite (string sourceFilePath)
Check if a given sourceFilePath will need HandleWrite(string) called on a copy of it.
Parameters
sourceFilePath The path of the source file to check.
Returns
true if HandleWrite(string) should be called on copies of sourceFilePath , false otherwise.
Implemented in Tgstation.Server.Host.IO.PosixPostWriteHandler, and Tgstation.Server.Host.IO.WindowsPostWriteHandler.
Referenced by Tgstation.Server.Host.Components.Repository.Repository.CopyTo().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/IO/IPostWriteHandler.cs