tgstation-server: Tgstation.Server.Host.Components.Repository.IRepository Interface Reference
Tgstation.Server.Host.Components.Repository.IRepository Interface Reference
Represents an on-disk git repository.
Public Member Functions
Task< bool > IsSha (string committish, CancellationToken cancellationToken)
Checks if a given committish is a sha.
ValueTask CheckoutObject (string committish, string? username, string? password, bool updateSubmodules, bool moveCurrentReference, JobProgressReporter progressReporter, CancellationToken cancellationToken)
Checks out a given committish .
ValueTask< TestMergeResult > AddTestMerge (TestMergeParameters testMergeParameters, string committerName, string committerEmail, string? username, string? password, bool updateSubmodules, JobProgressReporter progressReporter, CancellationToken cancellationToken)
Attempt to merge the revision specified by a given set of testMergeParameters into HEAD.
ValueTask FetchOrigin (JobProgressReporter progressReporter, string? username, string? password, bool deploymentPipeline, CancellationToken cancellationToken)
Fetch commits from the origin repository.
ValueTask ResetToOrigin (JobProgressReporter progressReporter, string? username, string? password, bool updateSubmodules, bool deploymentPipeline, CancellationToken cancellationToken)
Requires the current HEAD to be a tracked reference. Hard resets the reference to what it tracks on the origin repository.
Task ResetToSha (string sha, JobProgressReporter progressReporter, CancellationToken cancellationToken)
Requires the current HEAD to be a reference. Hard resets the reference to the given sha.
ValueTask< bool?> MergeOrigin (JobProgressReporter progressReporter, string committerName, string committerEmail, bool deploymentPipeline, CancellationToken cancellationToken)
Requires the current HEAD to be a tracked reference. Merges the reference to what it tracks on the origin repository.
ValueTask< bool > Synchronize (JobProgressReporter progressReporter, string? username, string? password, string committerName, string committerEmail, bool synchronizeTrackedBranch, bool deploymentPipeline, CancellationToken cancellationToken)
Runs the synchronize event script and attempts to push any changes made to the IRepository if on a tracked branch.
ValueTask CopyTo (string path, CancellationToken cancellationToken)
Copies the current working directory to a given path .
Task< bool > CommittishIsParent (string committish, CancellationToken cancellationToken)
Check if a given committish is a parent of the current Head.
Task< string > GetOriginSha (CancellationToken cancellationToken)
Get the tracked reference's current SHA.
Task< DateTimeOffset > TimestampCommit (string sha, CancellationToken cancellationToken)
Gets the DateTimeOffset a given sha was created on.
Public Member Functions inherited from Tgstation.Server.Host.Components.Repository.IGitRemoteAdditionalInformation
ValueTask< Models.TestMerge > GetTestMerge (TestMergeParameters parameters, RepositorySettings repositorySettings, CancellationToken cancellationToken)
Retrieve the Models.TestMerge representation of given test merge parameters .
Properties
bool Tracking [get]
If Reference tracks an upstream branch.
string Head [get]
The SHA of the IRepository HEAD.
string Reference [get]
The current reference the IRepository HEAD is using. This can be a branch or tag.
Uri Origin [get]
The current origin remote the IRepository is using.
Properties inherited from Tgstation.Server.Api.Models.Internal.IGitRemoteInformation
RemoteGitProvider? RemoteGitProvider [get]
The Models.RemoteGitProvider in use by the repository.
string? RemoteRepositoryOwner [get]
If RemoteGitProvider is not RemoteGitProvider.Unknown this will be set with the owner of the repository.
string? RemoteRepositoryName [get]
If RemoteGitProvider is not RemoteGitProvider.Unknown this will be set with the name of the repository.
Detailed Description
Represents an on-disk git repository.
Definition at line 13 of file IRepository.cs.
Member Function Documentation
AddTestMerge()
ValueTask< TestMergeResult > Tgstation.Server.Host.Components.Repository.IRepository.AddTestMerge (TestMergeParameters testMergeParameters, string committerName, string committerEmail, string? username, string? password, bool updateSubmodules, JobProgressReporter progressReporter, CancellationToken cancellationToken)
Attempt to merge the revision specified by a given set of testMergeParameters into HEAD.
Parameters
testMergeParameters The TestMergeParameters of the pull request.
committerName The name of the merge committer.
committerEmail The e-mail of the merge committer.
username The optional username used to fetch from the origin and submodule repositories.
password The optional password used to fetch from the origin and submodule repositories.
updateSubmodules If a submodule update should be attempted after the merge.
progressReporter The JobProgressReporter to report progress of the operation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the TestMergeResult.
Implemented in Tgstation.Server.Host.Components.Repository.Repository.
CheckoutObject()
ValueTask Tgstation.Server.Host.Components.Repository.IRepository.CheckoutObject (string committish, string? username, string? password, bool updateSubmodules, bool moveCurrentReference, JobProgressReporter progressReporter, CancellationToken cancellationToken)
Checks out a given committish .
Parameters
committish The sha or reference to checkout.
username The optional username used for fetching from submodule repositories.
password The optional password used for fetching from submodule repositories.
updateSubmodules If a submodule update should be attempted after the merge.
moveCurrentReference If a hard reset to the target committish should be performed instead of a checkout.
progressReporter The JobProgressReporter to report progress of the operation.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implemented in Tgstation.Server.Host.Components.Repository.Repository.
Referenced by Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.DownloadVersion().
CommittishIsParent()
Task< bool > Tgstation.Server.Host.Components.Repository.IRepository.CommittishIsParent (string committish, CancellationToken cancellationToken)
Check if a given committish is a parent of the current Head.
Parameters
committish The committish of the SHA to check.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in true if committish is a parent of Head, false otherwise.
This function is NOT reentrant.
Implemented in Tgstation.Server.Host.Components.Repository.Repository.
Referenced by Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.DownloadVersion(), Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager.RemoveMergedTestMerges(), and Tgstation.Server.Host.Components.Deployment.Remote.GitLabRemoteDeploymentManager.RemoveMergedTestMerges().
CopyTo()
ValueTask Tgstation.Server.Host.Components.Repository.IRepository.CopyTo (string path, CancellationToken cancellationToken)
Copies the current working directory to a given path .
Parameters
path The path to copy repository contents to.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implemented in Tgstation.Server.Host.Components.Repository.Repository.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.RunCompileJob().
FetchOrigin()
ValueTask Tgstation.Server.Host.Components.Repository.IRepository.FetchOrigin (JobProgressReporter progressReporter, string? username, string? password, bool deploymentPipeline, CancellationToken cancellationToken)
Fetch commits from the origin repository.
Parameters
progressReporter The JobProgressReporter to report progress of the operation.
username The optional username to fetch from the origin repository.
password The optional password to fetch from the origin repository.
deploymentPipeline If any events created should be marked as part of the deployment pipeline.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implemented in Tgstation.Server.Host.Components.Repository.Repository.
Referenced by Tgstation.Server.Host.Components.Engine.OpenDreamInstaller.DownloadVersion().
GetOriginSha()
Task< string > Tgstation.Server.Host.Components.Repository.IRepository.GetOriginSha (CancellationToken cancellationToken)
Get the tracked reference's current SHA.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the tracked origin reference's SHA.
Implemented in Tgstation.Server.Host.Components.Repository.Repository.
IsSha()
Task< bool > Tgstation.Server.Host.Components.Repository.IRepository.IsSha (string committish, CancellationToken cancellationToken)
Checks if a given committish is a sha.
Parameters
committish The git object to check.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in true if committish is a sha, false otherwise.
Implemented in Tgstation.Server.Host.Components.Repository.Repository.
MergeOrigin()
ValueTask< bool?> Tgstation.Server.Host.Components.Repository.IRepository.MergeOrigin (JobProgressReporter progressReporter, string committerName, string committerEmail, bool deploymentPipeline, CancellationToken cancellationToken)
Requires the current HEAD to be a tracked reference. Merges the reference to what it tracks on the origin repository.
Parameters
progressReporter The JobProgressReporter to report progress of the operation.
committerName The name of the merge committer.
committerEmail The e-mail of the merge committer.
deploymentPipeline If any events created should be marked as part of the deployment pipeline.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in a Nullable<T> bool representing the merge result that is true after a fast forward, false on a merge or up to date, null on a conflict.
Implemented in Tgstation.Server.Host.Components.Repository.Repository.
ResetToOrigin()
ValueTask Tgstation.Server.Host.Components.Repository.IRepository.ResetToOrigin (JobProgressReporter progressReporter, string? username, string? password, bool updateSubmodules, bool deploymentPipeline, CancellationToken cancellationToken)
Requires the current HEAD to be a tracked reference. Hard resets the reference to what it tracks on the origin repository.
Parameters
progressReporter The JobProgressReporter to report progress of the operation.
username The optional username used for fetching from submodule repositories.
password The optional password used for fetching from submodule repositories.
updateSubmodules If a submodule update should be attempted after the merge.
deploymentPipeline If any events created should be marked as part of the deployment pipeline.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the SHA of the new HEAD.
Implemented in Tgstation.Server.Host.Components.Repository.Repository.
ResetToSha()
Task Tgstation.Server.Host.Components.Repository.IRepository.ResetToSha (string sha, JobProgressReporter progressReporter, CancellationToken cancellationToken)
Requires the current HEAD to be a reference. Hard resets the reference to the given sha.
Parameters
sha The sha hash to reset to.
progressReporter The JobProgressReporter to report progress of the operation.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the SHA of the new HEAD.
Implemented in Tgstation.Server.Host.Components.Repository.Repository.
Synchronize()
ValueTask< bool > Tgstation.Server.Host.Components.Repository.IRepository.Synchronize (JobProgressReporter progressReporter, string? username, string? password, string committerName, string committerEmail, bool synchronizeTrackedBranch, bool deploymentPipeline, CancellationToken cancellationToken)
Runs the synchronize event script and attempts to push any changes made to the IRepository if on a tracked branch.
Parameters
progressReporter The JobProgressReporter to report progress of the operation.
username The username to fetch from the origin repository.
password The password to fetch from the origin repository.
committerName The name of the potential committer.
committerEmail The e-mail of the potential committer.
synchronizeTrackedBranch If the synchronizations should be made to the tracked reference as opposed to a temporary branch.
deploymentPipeline If any events created should be marked as part of the deployment pipeline.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in true if commits were pushed to the tracked origin reference, false otherwise.
Implemented in Tgstation.Server.Host.Components.Repository.Repository.
TimestampCommit()
Task< DateTimeOffset > Tgstation.Server.Host.Components.Repository.IRepository.TimestampCommit (string sha, CancellationToken cancellationToken)
Gets the DateTimeOffset a given sha was created on.
Parameters
sha The SHA to timestamp.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the DateTimeOffset that sha was created on.
Implemented in Tgstation.Server.Host.Components.Repository.Repository.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.DeploymentProcess().
Property Documentation
Head
string Tgstation.Server.Host.Components.Repository.IRepository.Head get
The SHA of the IRepository HEAD.
Implemented in Tgstation.Server.Host.Components.Repository.Repository.
Definition at line 23 of file IRepository.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Repository.Repository.AddTestMerge(), Tgstation.Server.Host.Components.Deployment.DreamMaker.DeploymentProcess(), Tgstation.Server.Host.Components.Repository.Repository.GetOriginSha(), Tgstation.Server.Host.Components.Repository.Repository.MergeOrigin(), and Tgstation.Server.Host.Components.Repository.Repository.ResetToOrigin().
Origin
Uri Tgstation.Server.Host.Components.Repository.IRepository.Origin get
The current origin remote the IRepository is using.
Implemented in Tgstation.Server.Host.Components.Repository.Repository.
Definition at line 33 of file IRepository.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.Compile(), Tgstation.Server.Host.Components.Repository.GitRemoteFeaturesFactory.CreateGitRemoteFeatures(), Tgstation.Server.Host.Controllers.RepositoryController.PopulateApi(), and Tgstation.Server.Host.Components.Deployment.DreamMaker.RunCompileJob().
Reference
string Tgstation.Server.Host.Components.Repository.IRepository.Reference get
The current reference the IRepository HEAD is using. This can be a branch or tag.
Implemented in Tgstation.Server.Host.Components.Repository.Repository.
Definition at line 28 of file IRepository.cs.
{ get; }
Referenced by Tgstation.Server.Host.Controllers.RepositoryController.PopulateApi(), and Tgstation.Server.Host.Components.Deployment.DreamMaker.RunCompileJob().
Tracking
bool Tgstation.Server.Host.Components.Repository.IRepository.Tracking get
If Reference tracks an upstream branch.
Implemented in Tgstation.Server.Host.Components.Repository.Repository.
Definition at line 18 of file IRepository.cs.
{ get; }
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Components/Repository/IRepository.cs