tgstation-server: Tgstation.Server.Host.Security.ICryptographySuite Interface Reference
Tgstation.Server.Host.Security.ICryptographySuite Interface Reference
Contains various cryptographic functions.
Public Member Functions
byte[] GetSecureBytes (uint amount)
Generates a secure set of bytes.
void SetUserPassword (User user, string newPassword, bool newUser)
Sets a User.PasswordHash for a given user .
bool CheckUserPassword (User user, string password)
Checks a given password matches a given user 's User.PasswordHash. This may result in User.PasswordHash being modified and this should be persisted.
string GetSecureString ()
Generates a 40-length secure ascii string.
Detailed Description
Contains various cryptographic functions.
Definition at line 8 of file ICryptographySuite.cs.
Member Function Documentation
CheckUserPassword()
bool Tgstation.Server.Host.Security.ICryptographySuite.CheckUserPassword (User user, string password)
Checks a given password matches a given user 's User.PasswordHash. This may result in User.PasswordHash being modified and this should be persisted.
Parameters
user The User to check.
password The password to check.
Returns
true if password matches the hash, false otherwise.
Implemented in Tgstation.Server.Host.Security.CryptographySuite.
Referenced by Tgstation.Server.Host.Controllers.ApiRootController.CreateToken().
GetSecureBytes()
byte[] Tgstation.Server.Host.Security.ICryptographySuite.GetSecureBytes (uint amount)
Generates a secure set of bytes.
Parameters
amount The amount of bytes to generate.
Returns
A secure set of bytes.
Implemented in Tgstation.Server.Host.Security.CryptographySuite.
Referenced by Tgstation.Server.Host.Security.TokenFactory.TokenFactory().
GetSecureString()
string Tgstation.Server.Host.Security.ICryptographySuite.GetSecureString ()
Generates a 40-length secure ascii string.
Returns
A 40-length secure ascii string.
Implemented in Tgstation.Server.Host.Security.CryptographySuite.
Referenced by Tgstation.Server.Host.Transfer.FileTransferService.CreateDownload(), Tgstation.Server.Host.Transfer.FileTransferService.CreateUpload(), and Tgstation.Server.Host.Components.Session.SessionControllerFactory.LaunchNew().
SetUserPassword()
void Tgstation.Server.Host.Security.ICryptographySuite.SetUserPassword (User user, string newPassword, bool newUser)
Sets a User.PasswordHash for a given user .
Parameters
user The User whos User.PasswordHash is to be set.
newPassword The new password for the User.
newUser If the user is just being created.
Implemented in Tgstation.Server.Host.Security.CryptographySuite.
Referenced by Tgstation.Server.Host.Database.DatabaseSeeder.ResetAdminPassword(), Tgstation.Server.Host.Database.DatabaseSeeder.SeedAdminUser(), and Tgstation.Server.Host.Controllers.UserController.TrySetPassword().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Security/ICryptographySuite.cs