tgstation-server: Tgstation.Server.Host.IO.IFilesystemLinkFactory Interface Reference
Tgstation.Server.Host.IO.IFilesystemLinkFactory Interface Reference
For creating filesystem symbolic links.
Public Member Functions
Task CreateSymbolicLink (string targetPath, string linkPath, CancellationToken cancellationToken)
Create a symbolic link.
Task CreateHardLink (string targetPath, string linkPath, CancellationToken cancellationToken)
Creates a hard link.
Properties
bool SymlinkedDirectoriesAreDeletedAsFiles [get]
If directory symlinks must be deleted as files would in the current environment.
Detailed Description
For creating filesystem symbolic links.
Definition at line 9 of file IFilesystemLinkFactory.cs.
Member Function Documentation
CreateHardLink()
Task Tgstation.Server.Host.IO.IFilesystemLinkFactory.CreateHardLink (string targetPath, string linkPath, CancellationToken cancellationToken)
Creates a hard link.
Parameters
targetPath The path to the hard target.
linkPath The path to the link.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.IO.PosixFilesystemLinkFactory, and Tgstation.Server.Host.IO.WindowsFilesystemLinkFactory.
Referenced by Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.MirrorDirectoryImpl().
CreateSymbolicLink()
Task Tgstation.Server.Host.IO.IFilesystemLinkFactory.CreateSymbolicLink (string targetPath, string linkPath, CancellationToken cancellationToken)
Create a symbolic link.
Parameters
targetPath The path to the hard target.
linkPath The path to the link.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.IO.PosixFilesystemLinkFactory, and Tgstation.Server.Host.IO.WindowsFilesystemLinkFactory.
Referenced by Tgstation.Server.Host.Components.Deployment.SymlinkDmbProvider.DoSwap(), Tgstation.Server.Host.Components.Engine.WindowsOpenDreamInstaller.HandleExtremelyLongPathOperation(), Tgstation.Server.Host.Components.Deployment.HardLinkDmbProvider.MirrorDirectoryImpl(), and Tgstation.Server.Host.Components.StaticFiles.Configuration.SymlinkStaticFilesTo().
Property Documentation
SymlinkedDirectoriesAreDeletedAsFiles
bool Tgstation.Server.Host.IO.IFilesystemLinkFactory.SymlinkedDirectoriesAreDeletedAsFiles get
If directory symlinks must be deleted as files would in the current environment.
This is because Linux symlinked directories must be deleted with global::System.IO.File.Delete(string).
Implemented in Tgstation.Server.Host.IO.PosixFilesystemLinkFactory, and Tgstation.Server.Host.IO.WindowsFilesystemLinkFactory.
Definition at line 15 of file IFilesystemLinkFactory.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Deployment.SymlinkDmbProvider.DoSwap().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/IO/IFilesystemLinkFactory.cs