tgstation-server: TGS.Interface.IServerInterface Interface Reference
TGS.Interface.IServerInterface Interface Reference
Main for communicating the ITGSService
Public Member Functions
ConnectivityLevel ConnectToInstance (string instanceName=null, bool skipChecks=false)
Targets instanceName as the instance to use with GetComponent<T>. Closes all connections to any previous instance
bool VersionMismatch (out string errorMessage)
Returns if the IServerInterface interface being used to connect to a service does not have the same release version as the service
T GetComponent< T > ()
Returns the requested IServerInterface component for the instance InstanceName. This does not guarantee a successful connection.
T GetServiceComponent< T > ()
Returns a root service component
ConnectivityLevel ConnectionStatus ()
Used to test if the ITGSService is avaiable on the target machine. Note that state can change at any time and any call into the may throw an exception because of communcation errors
ConnectivityLevel ConnectionStatus (out string error)
Used to test if the ITGSService is avaiable on the target machine. Note that state can change at any time and any call into the may throw an exception because of communcation errors
Properties
Version ServerVersion [get]
The Version of the connected ITGSService
string InstanceName [get]
The name of the current instance in use. Defaults to
RemoteLoginInfo LoginInfo [get]
The RemoteLoginInfo for the IServerInterface. Is for local connections
bool IsRemoteConnection [get]
Checks if the IServerInterface is setup for a remote connection
Detailed Description
Main for communicating the ITGSService
Definition at line 18 of file ServerInterface.cs.
Member Function Documentation
ConnectivityLevel TGS.Interface.IServerInterface.ConnectionStatus ()
Used to test if the ITGSService is avaiable on the target machine. Note that state can change at any time and any call into the may throw an exception because of communcation errors
Returns
on successful connection, error message string on failure
Implemented in TGS.Interface.ServerInterface.
Referenced by TGS.Installer.UI.Main.CheckForExistingVersion(), TGS.CommandLine.CLICommand.CLICommand(), TGS.CommandLine.Program.Main(), TGS.CommandLine.Program.RunCommandLine(), TGS.Installer.UI.Main.TellServiceWereComingForThem(), and TGS.ControlPanel.Login.VerifyAndConnect().
ConnectivityLevel TGS.Interface.IServerInterface.ConnectionStatus (out string error)
Used to test if the ITGSService is avaiable on the target machine. Note that state can change at any time and any call into the may throw an exception because of communcation errors
Parameters
error String of the error that prevented an elevated connectivity level
Returns
The apporopriate ConnectivityLevel
Implemented in TGS.Interface.ServerInterface.
ConnectivityLevel TGS.Interface.IServerInterface.ConnectToInstance (string instanceName = null, bool skipChecks = false)
Targets instanceName as the instance to use with GetComponent<T>. Closes all connections to any previous instance
Parameters
instanceName The name of the instance to connect to
skipChecks If set to , skips the connectivity and authentication checks, sets InstanceName, and returns ConnectivityLevel.Connected
Returns
The apporopriate ConnectivityLevel
Implemented in TGS.Interface.ServerInterface.
Referenced by TGS.CommandLine.Program.CheckInstanceConnectivity(), TGS.CommandLine.CLICommand.CLICommand(), and TGS.CommandLine.InstanceRootCommand.DoRun().
T TGS.Interface.IServerInterface.GetComponent< T > ()
Returns the requested IServerInterface component for the instance InstanceName. This does not guarantee a successful connection.
Template Parameters
T The component to retrieve
Returns
The correct component
Implemented in TGS.Interface.ServerInterface.
T TGS.Interface.IServerInterface.GetServiceComponent< T > ()
Returns a root service component
Returns
The ITGSService component for the service
Implemented in TGS.Interface.ServerInterface.
bool TGS.Interface.IServerInterface.VersionMismatch (out string errorMessage)
Returns if the IServerInterface interface being used to connect to a service does not have the same release version as the service
Parameters
errorMessage An error message to display to the user should this function return
Returns
if the IServerInterface interface being used to connect to a service does not have the same release version as the service
Implemented in TGS.Interface.ServerInterface.
Referenced by TGS.CommandLine.Program.Main(), TGS.CommandLine.Program.RunCommandLine(), and TGS.ControlPanel.Login.VerifyAndConnect().
Property Documentation
string TGS.Interface.IServerInterface.InstanceName get
The name of the current instance in use. Defaults to
Definition at line 28 of file ServerInterface.cs.
Referenced by TGS.ControlPanel.ControlPanel.ControlPanel(), and TGS.CommandLine.InstanceRootCommand.DoRun().
bool TGS.Interface.IServerInterface.IsRemoteConnection get
Checks if the IServerInterface is setup for a remote connection
Definition at line 38 of file ServerInterface.cs.
RemoteLoginInfo TGS.Interface.IServerInterface.LoginInfo get
The RemoteLoginInfo for the IServerInterface. Is for local connections
Definition at line 33 of file ServerInterface.cs.
Version TGS.Interface.IServerInterface.ServerVersion get
The Version of the connected ITGSService
Definition at line 23 of file ServerInterface.cs.
Referenced by TGS.Installer.UI.Main.CheckForExistingVersion().
The documentation for this interface was generated from the following file:
TGS.Interface/ServerInterface.cs