tgstation-server: TGS.Interface.Components.ITGRepository Interface Reference
TGS.Interface.Components.ITGRepository Interface Reference
Interface for managing the code repository
Public Member Functions
bool OperationInProgress ()
If the repo is currently undergoing an operation
int CheckoutProgress ()
Gets the progress of repository operations, not all operations are supported
bool Exists ()
Check if the repository is valid, if not Setup(string, string) must be called
string Setup (string remote, string branch="master")
Deletes whatever may be left over and clones the repo at remote and checks out branch . Will move config and data dirs to a backup location if they exist. Runs asyncronously
string GetHead (bool useTracked, out string error)
Gets the sha of the current HEAD
string GetBranch (out string error)
Gets the name of the current branch
string GetRemote (out string error)
Gets the url of the current origin
string Checkout (string objectName)
Hard checks out the passed object name
string Update (bool reset)
Fetches the origin and merges it into the current branch
string Reset (bool tracked)
Runs git reset –hard
string MergePullRequest (int PRnumber, string atSHA=null, bool silent=false)
Merges the target pull request into the current branch if the remote is a github repository
IEnumerable< string > MergePullRequests (IEnumerable< PullRequestInfo > pullRequestInfos, bool silent=false)
Merges the target pull requests into the current branch if the remote is a github repository
List< PullRequestInfo > MergedPullRequests (out string error)
Get the currently merged pull requests. Note that switching branches will delete this list and switching back won't restore it
string GetCommitterName ()
Gets the name of the configured git committer
void SetCommitterName (string newName)
Sets the name of the configured git committer
string GetCommitterEmail ()
Gets the email of the configured git committer
void SetCommitterEmail (string newEmail)
Sets the email of the configured git committer
string GenerateChangelog (out string error)
Updates the html changelog
string SynchronizePush ()
Pushes the paths listed in TGS3.json to the currentl git remote. No other commit differences may exist for this function to succeed
IDictionary< string, string > ListBackups (out string error)
List the tagged commits of the repo at which compiles took place
string UpdateTGS3Json ()
Updates the cached TGS3.json to the repo's version. Compiles will not succeed if these two to not match
void SetAutoUpdateInterval (ulong newInterval)
(De)Activate and set the interval for the automatic server updater
ulong AutoUpdateInterval ()
Get the current autoupdate interval
bool PushTestmergeCommits ()
Check if we push a temporary branch to the remote when we make testmerge commits
void SetPushTestmergeCommits (bool newValue)
Set if we push a temporary branch to the remote when we make testmerge commits
Detailed Description
Interface for managing the code repository
Definition at line 10 of file Repository.cs.
Member Function Documentation
ulong TGS.Interface.Components.ITGRepository.AutoUpdateInterval ()
Get the current autoupdate interval
Returns
The current auto update interval or 0 if it's disabled
Implemented in TGS.Server.Instance.
string TGS.Interface.Components.ITGRepository.Checkout (string objectName)
Hard checks out the passed object name
Parameters
objectName The branch, commit, or tag to checkout
Returns
on success, error message on failure
Implemented in TGS.Server.Instance.
int TGS.Interface.Components.ITGRepository.CheckoutProgress ()
Gets the progress of repository operations, not all operations are supported
Returns
A value between 0 and 100 inclusive representing the progress of the current operation or -1 if the operation cannot be monitored
Implemented in TGS.Server.Instance.
bool TGS.Interface.Components.ITGRepository.Exists ()
Check if the repository is valid, if not Setup(string, string) must be called
Returns
if the repository is valid, otherwise
Implemented in TGS.Server.Instance.
string TGS.Interface.Components.ITGRepository.GenerateChangelog (out string error)
Updates the html changelog
Parameters
error on success, error on failure
Returns
The output of the python script
Implemented in TGS.Server.Instance.
Referenced by TGS.ControlPanel.TestMergeManager.GenerateChangelog().
string TGS.Interface.Components.ITGRepository.GetBranch (out string error)
Gets the name of the current branch
Parameters
error on success, error message on failure
Returns
The name of the current branch on success, on failure
Implemented in TGS.Server.Instance.
string TGS.Interface.Components.ITGRepository.GetCommitterEmail ()
Gets the email of the configured git committer
Returns
The email of the configured git committer
Implemented in TGS.Server.Instance.
string TGS.Interface.Components.ITGRepository.GetCommitterName ()
Gets the name of the configured git committer
Returns
The name of the configured git committer
Implemented in TGS.Server.Instance.
string TGS.Interface.Components.ITGRepository.GetHead (bool useTracked, out string error)
Gets the sha of the current HEAD
Parameters
useTracked If set to true and HEAD is currently a branch, will instead return the sha of the tracked remote branch if it exists
error on success, error message on failure
Returns
The sha of the current HEAD on success, on failure
Implemented in TGS.Server.Instance.
string TGS.Interface.Components.ITGRepository.GetRemote (out string error)
Gets the url of the current origin
Parameters
error on success, error message on failure
Returns
The url of the current origin on success, on failure
Implemented in TGS.Server.Instance.
Referenced by TGS.ControlPanel.Program.GetRepositoryRemote(), and TGS.ControlPanel.ControlPanel.RepoApplyButton_Click().
IDictionary<string, string> TGS.Interface.Components.ITGRepository.ListBackups (out string error)
List the tagged commits of the repo at which compiles took place
Parameters
error on success, error message on failure
Returns
A IDictionary<TKey, TValue> of tag name -> commit on success, on failure
Implemented in TGS.Server.Instance.
List<PullRequestInfo> TGS.Interface.Components.ITGRepository.MergedPullRequests (out string error)
Get the currently merged pull requests. Note that switching branches will delete this list and switching back won't restore it
Parameters
error on success, error message on failure
Returns
A IList<T> of PullRequestInfo
Implemented in TGS.Server.Instance.
Referenced by TGS.ControlPanel.TestMergeManager.AddPRButton_Click().
string TGS.Interface.Components.ITGRepository.MergePullRequest (int PRnumber, string atSHA = null, bool silent = false)
Merges the target pull request into the current branch if the remote is a github repository
Parameters
PRnumber The github pull request number in the remote repository
atSHA The SHA of the pull request to merge
silent Suppresses chat messages if
Returns
on success, error message on failure
Implemented in TGS.Server.Instance.
Referenced by TGS.CommandLine.TestmergeCommand.Run().
IEnumerable<string> TGS.Interface.Components.ITGRepository.MergePullRequests (IEnumerable< PullRequestInfo > pullRequestInfos, bool silent = false)
Merges the target pull requests into the current branch if the remote is a github repository
Parameters
pullRequestInfos IEnumerable<T> of PullRequestInfos containing pull request numbers and shas in the remote repository
silent Suppresses chat messages if
Returns
on success, list of error messages if any fail failure. Those with indexes of those that succeed will have null entries
Implemented in TGS.Server.Instance.
bool TGS.Interface.Components.ITGRepository.OperationInProgress ()
If the repo is currently undergoing an operation
Returns
if the repo is busy, otherwise
Implemented in TGS.Server.Instance.
Referenced by TGS.ControlPanel.ControlPanel.RepoBusyCheck(), and TGS.CommandLine.RepoStatusCommand.Run().
bool TGS.Interface.Components.ITGRepository.PushTestmergeCommits ()
Check if we push a temporary branch to the remote when we make testmerge commits
Returns
if we publish testmerge commits to the remote, otherwise
Implemented in TGS.Server.Instance.
Referenced by TGS.ControlPanel.ControlPanel.PopulateRepoFields().
string TGS.Interface.Components.ITGRepository.Reset (bool tracked)
Runs git reset –hard
Parameters
tracked Changes command to git reset –hard origin/branch_name if
Returns
on success, error message on failure
Implemented in TGS.Server.Instance.
void TGS.Interface.Components.ITGRepository.SetAutoUpdateInterval (ulong newInterval)
(De)Activate and set the interval for the automatic server updater
Parameters
newInterval Interval to check for updates in minutes, disables if 0
Implemented in TGS.Server.Instance.
void TGS.Interface.Components.ITGRepository.SetCommitterEmail (string newEmail)
Sets the email of the configured git committer
Parameters
newEmail The email to set
Implemented in TGS.Server.Instance.
void TGS.Interface.Components.ITGRepository.SetCommitterName (string newName)
Sets the name of the configured git committer
Parameters
newName The name to set
Implemented in TGS.Server.Instance.
void TGS.Interface.Components.ITGRepository.SetPushTestmergeCommits (bool newValue)
Set if we push a temporary branch to the remote when we make testmerge commits
Parameters
newValue if we testmerge commits should be published to the remote, otherwise
Implemented in TGS.Server.Instance.
string TGS.Interface.Components.ITGRepository.Setup (string remote, string branch = "master")
Deletes whatever may be left over and clones the repo at remote and checks out branch . Will move config and data dirs to a backup location if they exist. Runs asyncronously
Parameters
remote The address of the repo to clone. If ssh protocol is used, private_key.txt and public_key.txt must exist in the server RepoKey directory.
branch The branch of the repo to checkout
Returns
on success, error message on failure
Implemented in TGS.Server.Instance.
Referenced by TGS.ControlPanel.ControlPanel.RepoBGW_DoWork().
string TGS.Interface.Components.ITGRepository.SynchronizePush ()
Pushes the paths listed in TGS3.json to the currentl git remote. No other commit differences may exist for this function to succeed
Returns
on success, error on failure
Implemented in TGS.Server.Instance.
string TGS.Interface.Components.ITGRepository.Update (bool reset)
Fetches the origin and merges it into the current branch
Parameters
reset If , the operation will perform a hard reset instead of a merge
Returns
on success, error message on failure
Implemented in TGS.Server.Instance.
Referenced by TGS.CommandLine.UpdateCommand.Run().
string TGS.Interface.Components.ITGRepository.UpdateTGS3Json ()
Updates the cached TGS3.json to the repo's version. Compiles will not succeed if these two to not match
Returns
on success, error message on failure
Implemented in TGS.Server.Instance.
The documentation for this interface was generated from the following file:
TGS.Interface/Components/Repository.cs