tgstation-server: Tgstation.Server.Host.Database.IDatabaseContext Interface Reference
Tgstation.Server.Host.Database.IDatabaseContext Interface Reference
Represents the database.
Public Member Functions
Task Save (CancellationToken cancellationToken)
Saves changes made to the IDatabaseContext
Task Drop (CancellationToken cancellationToken)
Attempts to delete all tables and drop the database in use.
Task< bool > Migrate (ILogger< DatabaseContext > logger, CancellationToken cancellationToken)
Creates and migrates the IDatabaseContext
Task SchemaDowngradeForServerVersion (ILogger< DatabaseContext > logger, Version version, DatabaseType currentDatabaseType, CancellationToken cancellationToken)
Attempt to downgrade the schema to the migration used for a given server version
Properties
IDatabaseCollection< User > Users [get]
The Users in the IDatabaseContext
IDatabaseCollection< Instance > Instances [get]
The Instances in the IDatabaseContext
IDatabaseCollection< InstanceUser > InstanceUsers [get]
The InstanceUsers in the IDatabaseContext
IDatabaseCollection< Job > Jobs [get]
The Jobs in the IDatabaseContext
IDatabaseCollection< CompileJob > CompileJobs [get]
The CompileJobs in the IDatabaseContext
IDatabaseCollection< RevisionInformation > RevisionInformations [get]
The RevisionInformations in the IDatabaseContext
IDatabaseCollection< DreamMakerSettings > DreamMakerSettings [get]
The Models.DreamMakerSettings in the IDatabaseContext
IDatabaseCollection< DreamDaemonSettings > DreamDaemonSettings [get]
The Models.DreamDaemonSettings in the IDatabaseContext
IDatabaseCollection< ChatBot > ChatBots [get]
The ChatBots in the IDatabaseContext
IDatabaseCollection< ChatChannel > ChatChannels [get]
The ChatChannel in the IDatabaseContext
IDatabaseCollection< RepositorySettings > RepositorySettings [get]
The Models.RepositorySettings in the IDatabaseContext
IDatabaseCollection< ReattachInformation > ReattachInformations [get]
The DbSet<TEntity> for ReattachInformations
Detailed Description
Represents the database.
Definition at line 14 of file IDatabaseContext.cs.
Member Function Documentation
Drop()
Task Tgstation.Server.Host.Database.IDatabaseContext.Drop (CancellationToken cancellationToken)
Attempts to delete all tables and drop the database in use.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.Database.DatabaseContext.
Referenced by Tgstation.Server.Host.Database.DatabaseSeeder.Initialize().
Migrate()
Task<bool> Tgstation.Server.Host.Database.IDatabaseContext.Migrate (ILogger< DatabaseContext > logger, CancellationToken cancellationToken)
Creates and migrates the IDatabaseContext
Parameters
logger The DatabaseContext ILogger to use.
cancellationToken The CancellationToken for the operation
Returns
A Task<TResult> resulting in true if the database should be seeded, false otherwise.
Implemented in Tgstation.Server.Host.Database.DatabaseContext.
Referenced by Tgstation.Server.Host.Database.DatabaseSeeder.Initialize().
Save()
Task Tgstation.Server.Host.Database.IDatabaseContext.Save (CancellationToken cancellationToken)
Saves changes made to the IDatabaseContext
Parameters
cancellationToken The CancellationToken for the operation
Returns
A Task representing the running operation
Implemented in Tgstation.Server.Host.Database.DatabaseContext.
Referenced by Tgstation.Server.Host.Database.DatabaseSeeder.ResetAdminPassword(), Tgstation.Server.Host.Database.DatabaseSeeder.SanitizeDatabase(), and Tgstation.Server.Host.Database.DatabaseSeeder.SeedDatabase().
SchemaDowngradeForServerVersion()
Task Tgstation.Server.Host.Database.IDatabaseContext.SchemaDowngradeForServerVersion (ILogger< DatabaseContext > logger, Version version, DatabaseType currentDatabaseType, CancellationToken cancellationToken)
Attempt to downgrade the schema to the migration used for a given server version
Parameters
logger The DatabaseContext ILogger to use.
version The tgstation-server Version that the schema should downgrade for
currentDatabaseType The DatabaseType in use.
cancellationToken The CancellationToken for the operation
Returns
A Task representing the running operation
Implemented in Tgstation.Server.Host.Database.DatabaseContext.
Referenced by Tgstation.Server.Host.Database.DatabaseSeeder.Downgrade().
Property Documentation
ChatBots
IDatabaseCollection<ChatBot> Tgstation.Server.Host.Database.IDatabaseContext.ChatBots get
The ChatBots in the IDatabaseContext
Definition at line 59 of file IDatabaseContext.cs.
 { get; }
ChatChannels
IDatabaseCollection<ChatChannel> Tgstation.Server.Host.Database.IDatabaseContext.ChatChannels get
The ChatChannel in the IDatabaseContext
Definition at line 64 of file IDatabaseContext.cs.
 { get; }
CompileJobs
IDatabaseCollection<CompileJob> Tgstation.Server.Host.Database.IDatabaseContext.CompileJobs get
The CompileJobs in the IDatabaseContext
Definition at line 39 of file IDatabaseContext.cs.
 { get; }
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.CalculateExpectedDeploymentTime().
DreamDaemonSettings
IDatabaseCollection<DreamDaemonSettings> Tgstation.Server.Host.Database.IDatabaseContext.DreamDaemonSettings get
The Models.DreamDaemonSettings in the IDatabaseContext
Definition at line 54 of file IDatabaseContext.cs.
 { get; }
Referenced by Tgstation.Server.Host.Core.PortAllocator.GetAvailablePort(), and Tgstation.Server.Host.Database.DatabaseSeeder.SanitizeDatabase().
DreamMakerSettings
IDatabaseCollection<DreamMakerSettings> Tgstation.Server.Host.Database.IDatabaseContext.DreamMakerSettings get
The Models.DreamMakerSettings in the IDatabaseContext
Definition at line 49 of file IDatabaseContext.cs.
 { get; }
Referenced by Tgstation.Server.Host.Core.PortAllocator.GetAvailablePort().
Instances
IDatabaseCollection<Instance> Tgstation.Server.Host.Database.IDatabaseContext.Instances get
The Instances in the IDatabaseContext
Definition at line 24 of file IDatabaseContext.cs.
 { get; }
Referenced by Tgstation.Server.Host.Database.DatabaseSeeder.SanitizeDatabase().
InstanceUsers
IDatabaseCollection<InstanceUser> Tgstation.Server.Host.Database.IDatabaseContext.InstanceUsers get
The InstanceUsers in the IDatabaseContext
Definition at line 29 of file IDatabaseContext.cs.
 { get; }
Referenced by Tgstation.Server.Host.Security.AuthenticationContextFactory.CreateAuthenticationContext().
Jobs
IDatabaseCollection<Job> Tgstation.Server.Host.Database.IDatabaseContext.Jobs get
The Jobs in the IDatabaseContext
Definition at line 34 of file IDatabaseContext.cs.
 { get; }
ReattachInformations
IDatabaseCollection<ReattachInformation> Tgstation.Server.Host.Database.IDatabaseContext.ReattachInformations get
The DbSet<TEntity> for ReattachInformations
Definition at line 74 of file IDatabaseContext.cs.
 { get; }
RepositorySettings
IDatabaseCollection<RepositorySettings> Tgstation.Server.Host.Database.IDatabaseContext.RepositorySettings get
The Models.RepositorySettings in the IDatabaseContext
Definition at line 69 of file IDatabaseContext.cs.
 { get; }
RevisionInformations
IDatabaseCollection<RevisionInformation> Tgstation.Server.Host.Database.IDatabaseContext.RevisionInformations get
The RevisionInformations in the IDatabaseContext
Definition at line 44 of file IDatabaseContext.cs.
 { get; }
Referenced by Tgstation.Server.Host.Controllers.RepositoryController.LoadRevisionInformation().
Users
IDatabaseCollection<User> Tgstation.Server.Host.Database.IDatabaseContext.Users get
The Users in the IDatabaseContext
Definition at line 19 of file IDatabaseContext.cs.
 { get; }
Referenced by Tgstation.Server.Host.Security.AuthenticationContextFactory.CreateAuthenticationContext(), Tgstation.Server.Host.Database.DatabaseSeeder.GetAdminUser(), Tgstation.Server.Host.Database.DatabaseSeeder.SanitizeDatabase(), Tgstation.Server.Host.Database.DatabaseSeeder.SeedAdminUser(), and Tgstation.Server.Host.Database.DatabaseSeeder.SeedSystemUser().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Database/IDatabaseContext.cs