tgstation-server: Tgstation.Server.Host.Components.Repository.ICredentialsProvider Interface Reference
Tgstation.Server.Host.Components.Repository.ICredentialsProvider Interface Reference
For generating CredentialsHandlers.
Public Member Functions
CredentialsHandler GenerateCredentialsHandler (string? username, string? password)
Generate a CredentialsHandler from a given username and password .
void CheckBadCredentialsException (LibGit2SharpException exception)
Rethrow the authentication failure message as a JobException if it is one.
Detailed Description
For generating CredentialsHandlers.
Definition at line 11 of file ICredentialsProvider.cs.
Member Function Documentation
CheckBadCredentialsException()
void Tgstation.Server.Host.Components.Repository.ICredentialsProvider.CheckBadCredentialsException (LibGit2SharpException exception)
Rethrow the authentication failure message as a JobException if it is one.
Parameters
exception The current LibGit2SharpException.
Implemented in Tgstation.Server.Host.Components.Repository.LibGit2RepositoryFactory.
Referenced by Tgstation.Server.Host.Components.Repository.Repository.AddTestMerge(), and Tgstation.Server.Host.Components.Repository.Repository.FetchOrigin().
GenerateCredentialsHandler()
CredentialsHandler Tgstation.Server.Host.Components.Repository.ICredentialsProvider.GenerateCredentialsHandler (string? username, string? password)
Generate a CredentialsHandler from a given username and password .
Parameters
username The optional username to use in the CredentialsHandler.
password The optional password to use in the CredentialsHandler.
Returns
A new CredentialsHandler.
Implemented in Tgstation.Server.Host.Components.Repository.LibGit2RepositoryFactory.
Referenced by Tgstation.Server.Host.Components.Repository.Repository.AddTestMerge(), Tgstation.Server.Host.Components.Repository.RepositoryManager.CloneRepository(), and Tgstation.Server.Host.Components.Repository.Repository.FetchOrigin().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Components/Repository/ICredentialsProvider.cs