tgstation-server: Tgstation.Server.Host.Utils.IAsyncDelayer Interface Reference
Tgstation.Server.Host.Utils.IAsyncDelayer Interface Reference
For waiting asynchronously.
Public Member Functions
Task Delay (TimeSpan timeSpan, CancellationToken cancellationToken)
Create a Task that completes after a given timeSpan .
Detailed Description
For waiting asynchronously.
Definition at line 10 of file IAsyncDelayer.cs.
Member Function Documentation
Delay()
Task Tgstation.Server.Host.Utils.IAsyncDelayer.Delay (TimeSpan timeSpan, CancellationToken cancellationToken)
Create a Task that completes after a given timeSpan .
Parameters
timeSpan The TimeSpan that must elapse.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.Utils.AsyncDelayer.
Referenced by Tgstation.Server.Host.Swarm.SwarmService.CommitUpdate(), Tgstation.Server.Host.System.WindowsNetworkPromptReaper.ExecuteAsync(), Tgstation.Server.Host.Core.VersionReportingService.ExecuteAsync(), Tgstation.Server.Host.Components.Session.SessionController.GetLaunchResult(), Tgstation.Server.Host.Security.IdentityCacheObject.IdentityCacheObject(), Tgstation.Server.Host.Components.InstanceManager.InitializeSwarm(), Tgstation.Server.Host.Components.Deployment.DmbFactory.LogLockStates(), Tgstation.Server.Host.Components.Session.SessionControllerFactory.PortBindTest(), Tgstation.Server.Host.Components.Session.SessionController.PostValidationShutdown(), Tgstation.Server.Host.Components.InstanceManager.ProcessBridgeRequest(), Tgstation.Server.Host.Transfer.FileTransferService.QueueExpiry(), Tgstation.Server.Host.Extensions.TopicClientExtensions.SendWithOptionalPriority(), Tgstation.Server.Host.System.PosixSignalHandler.SignalChecker(), and Tgstation.Server.Host.Components.Instance.TimerLoop().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Utils/IAsyncDelayer.cs