tgstation-server: TGS.Interface.Components.ITGChat Interface Reference
TGS.Interface.Components.ITGChat Interface Reference
Interface for handling chat bot
Public Member Functions
string SetProviderInfo (ChatSetupInfo info)
Sets a chat provider info
IList< ChatSetupInfo > ProviderInfos ()
Returns ChatSetupInfo for all ChatProviders
bool Connected (ChatProvider providerType)
Checks connection status
string Reconnect (ChatProvider providerType)
Reconnect a specific providerType to it's chat service
Detailed Description
Interface for handling chat bot
Definition at line 10 of file Chat.cs.
Member Function Documentation
bool TGS.Interface.Components.ITGChat.Connected (ChatProvider providerType)
Checks connection status
Parameters
providerType The type of provider to check if connected
Returns
if connected, otherwise
Implemented in TGS.Server.Instance.
IList<ChatSetupInfo> TGS.Interface.Components.ITGChat.ProviderInfos ()
Returns ChatSetupInfo for all ChatProviders
Returns
A list of all ChatSetupInfos
Implemented in TGS.Server.Instance.
Referenced by TGS.ControlPanel.ControlPanel.LoadChatPage(), and TGS.ControlPanel.ControlPanel.SetAdminsAreSpecial().
string TGS.Interface.Components.ITGChat.Reconnect (ChatProvider providerType)
Reconnect a specific providerType to it's chat service
Parameters
providerType The type of provider to reconnect
Returns
on success, error message string on failure
Implemented in TGS.Server.Instance.
Referenced by TGS.ControlPanel.ControlPanel.ChatReconnectButton_Click().
string TGS.Interface.Components.ITGChat.SetProviderInfo (ChatSetupInfo info)
Sets a chat provider info
Parameters
info The info to set
Implemented in TGS.Server.Instance.
Referenced by TGS.ControlPanel.ControlPanel.ChatApplyButton_Click().
The documentation for this interface was generated from the following file:
TGS.Interface/Components/Chat.cs