tgstation-server: TGS.Interface.Components.ITGCompiler Interface Reference
TGS.Interface.Components.ITGCompiler Interface Reference
For managing the Game A/B/Live folders, compiling, and hotswapping them
Public Member Functions
bool Initialize ()
Sets up the symlinks for hotswapping game code. This will reset everything in the Game folder. Requires the repository to be set up and locks it once the compilation stage starts. Runs asyncronously from this call
bool Compile (bool silent=false)
Does all the necessary actions to take the revision currently in the repository and compile it to be run on the next server reboot. Requires BYOND to be set up and the GetStatus to return CompilerStatus.Initialized. Runs asyncronously
string Cancel ()
Cancels the current compilation
CompilerStatus GetStatus ()
Returns the current compiler status
string CompileError ()
Returns the error message of the last operation. Reading this will clear the stored value
string ProjectName ()
Returns the relative path of the dme the compiler will look for without the .dme part
void SetProjectName (string projectName)
Sets the relative path of the dme the compiler will look for without the .dme part
Detailed Description
For managing the Game A/B/Live folders, compiling, and hotswapping them
Definition at line 9 of file Compiler.cs.
Member Function Documentation
string TGS.Interface.Components.ITGCompiler.Cancel ()
Cancels the current compilation
Returns
on success, error message on failure
Implemented in TGS.Server.Instance.
bool TGS.Interface.Components.ITGCompiler.Compile (bool silent = false)
Does all the necessary actions to take the revision currently in the repository and compile it to be run on the next server reboot. Requires BYOND to be set up and the GetStatus to return CompilerStatus.Initialized. Runs asyncronously
Parameters
silent If no message for compilation start will be printed
Returns
if the operation began, if it could not start
Implemented in TGS.Server.Instance.
Referenced by TGS.ControlPanel.TestMergeManager.ApplyButton_Click(), TGS.ControlPanel.ControlPanel.CompileButton_Click(), TGS.ControlPanel.ControlPanel.RemoveAllTestMergesButton_Click(), and TGS.ControlPanel.ControlPanel.UpdateServer().
string TGS.Interface.Components.ITGCompiler.CompileError ()
Returns the error message of the last operation. Reading this will clear the stored value
Returns
the error message of the last operation if it failed or if it succeeded
Implemented in TGS.Server.Instance.
CompilerStatus TGS.Interface.Components.ITGCompiler.GetStatus ()
Returns the current compiler status
Returns
The current compiler status
Implemented in TGS.Server.Instance.
Referenced by TGS.CommandLine.DMCompileCommand.Run(), and TGS.CommandLine.DMInitializeCommand.Run().
bool TGS.Interface.Components.ITGCompiler.Initialize ()
Sets up the symlinks for hotswapping game code. This will reset everything in the Game folder. Requires the repository to be set up and locks it once the compilation stage starts. Runs asyncronously from this call
Returns
if the operation began, if it could not start
Implemented in TGS.Server.Instance.
Referenced by TGS.ControlPanel.ControlPanel.InitializeButton_Click().
string TGS.Interface.Components.ITGCompiler.ProjectName ()
Returns the relative path of the dme the compiler will look for without the .dme part
Returns
The relative path of the dme the compiler will look for without the .dme part
Implemented in TGS.Server.Instance.
void TGS.Interface.Components.ITGCompiler.SetProjectName (string projectName)
Sets the relative path of the dme the compiler will look for without the .dme part
Parameters
projectName The relative path of the dme the compiler will look for without the .dme part
Implemented in TGS.Server.Instance.
The documentation for this interface was generated from the following file:
TGS.Interface/Components/Compiler.cs