tgstation-server: Tgstation.Server.Host.Components.Engine.IEngineManager Interface Reference
Tgstation.Server.Host.Components.Engine.IEngineManager Interface Reference
For managing the engine installations.
Public Member Functions
ValueTask ChangeVersion (JobProgressReporter? progressReporter, EngineVersion version, Stream? customVersionStream, bool allowInstallation, CancellationToken cancellationToken)
Change the active EngineVersion.
ValueTask DeleteVersion (JobProgressReporter progressReporter, EngineVersion version, CancellationToken cancellationToken)
Deletes a given version from the disk.
ValueTask< IEngineExecutableLock > UseExecutables (EngineVersion? requiredVersion, string? trustDmbFullPath, CancellationToken cancellationToken)
Lock the current installation's location and return a IEngineExecutableLock.
Properties
EngineVersion? ActiveVersion [get]
The currently active EngineVersion.
IReadOnlyList< EngineVersion > InstalledVersions [get]
The installed EngineVersions.
Detailed Description
For managing the engine installations.
When passing in EngineVersion.Versions for EngineType.Byond, ensure they are BYOND format versions unless referring to a custom version. This means Version.Build should NEVER be 0.
Definition at line 16 of file IEngineManager.cs.
Member Function Documentation
ChangeVersion()
ValueTask Tgstation.Server.Host.Components.Engine.IEngineManager.ChangeVersion (JobProgressReporter? progressReporter, EngineVersion version, Stream? customVersionStream, bool allowInstallation, CancellationToken cancellationToken)
Change the active EngineVersion.
Parameters
progressReporter The optional JobProgressReporter for the operation.
version The new EngineVersion.
customVersionStream Optional Stream of a custom BYOND version zip file.
allowInstallation If an installation should be performed if the version is not installed. If false and an installation is required an InvalidOperationException will be thrown.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implemented in Tgstation.Server.Host.Components.Engine.EngineManager.
DeleteVersion()
ValueTask Tgstation.Server.Host.Components.Engine.IEngineManager.DeleteVersion (JobProgressReporter progressReporter, EngineVersion version, CancellationToken cancellationToken)
Deletes a given version from the disk.
Parameters
progressReporter The JobProgressReporter for the operation.
version The EngineVersion to delete.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.Components.Engine.EngineManager.
UseExecutables()
ValueTask< IEngineExecutableLock > Tgstation.Server.Host.Components.Engine.IEngineManager.UseExecutables (EngineVersion? requiredVersion, string? trustDmbFullPath, CancellationToken cancellationToken)
Lock the current installation's location and return a IEngineExecutableLock.
Parameters
requiredVersion The EngineVersion required.
trustDmbFullPath The optional full path to .dmb to trust while using the executables.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the requested IEngineExecutableLock.
Implemented in Tgstation.Server.Host.Components.Engine.EngineManager.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.Compile(), Tgstation.Server.Host.Components.Session.SessionControllerFactory.LaunchNew(), and Tgstation.Server.Host.Components.Session.SessionControllerFactory.Reattach().
Property Documentation
ActiveVersion
EngineVersion? Tgstation.Server.Host.Components.Engine.IEngineManager.ActiveVersion get
The currently active EngineVersion.
Implemented in Tgstation.Server.Host.Components.Engine.EngineManager.
Definition at line 21 of file IEngineManager.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Chat.Commands.EngineCommand.Invoke().
InstalledVersions
IReadOnlyList<EngineVersion> Tgstation.Server.Host.Components.Engine.IEngineManager.InstalledVersions get
The installed EngineVersions.
Implemented in Tgstation.Server.Host.Components.Engine.EngineManager.
Definition at line 26 of file IEngineManager.cs.
{ get; }
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Components/Engine/IEngineManager.cs