tgstation-server: Tgstation.Server.Host.Components.Engine.IEngineInstallation Interface Reference
Tgstation.Server.Host.Components.Engine.IEngineInstallation Interface Reference
Represents a BYOND installation.
Public Member Functions
string FormatServerArguments (IDmbProvider dmbProvider, IReadOnlyDictionary< string, string > parameters, DreamDaemonLaunchParameters launchParameters, string? logFilePath)
Return the command line arguments for launching with given launchParameters .
string FormatCompilerArguments (string dmePath, string? additionalArguments)
Return the command line arguments for compiling a given dmePath if compilation is necessary.
ValueTask StopServerProcess (ILogger logger, IProcess process, string accessIdentifier, ushort port, CancellationToken cancellationToken)
Kills a given engine server process .
ValueTask< Dictionary< string, string >?> LoadEnv (ILogger logger, bool forCompiler, CancellationToken cancellationToken)
Loads the environment settings for either the server or compiler.
Properties
EngineVersion Version [get]
The EngineVersion of the IEngineInstallation.
string ServerExePath [get]
The full path to the game server executable.
string CompilerExePath [get]
The full path to the dm/DreamMaker executable.
bool HasStandardOutput [get]
If ServerExePath supports being run as a command-line application and outputs log information to be captured.
bool PromptsForNetworkAccess [get]
If ServerExePath may create network prompts.
bool PreferFileLogging [get]
If HasStandardOutput is set, this indicates that the engine server has good file logging that should be preferred to ours.
bool UseDotnetDump [get]
If dotnet-dump should be used to create process dumps for this installation.
Task InstallationTask [get]
The Task that completes when the BYOND version finished installing.
Detailed Description
Represents a BYOND installation.
Definition at line 17 of file IEngineInstallation.cs.
Member Function Documentation
FormatCompilerArguments()
string Tgstation.Server.Host.Components.Engine.IEngineInstallation.FormatCompilerArguments (string dmePath, string? additionalArguments)
Return the command line arguments for compiling a given dmePath if compilation is necessary.
Parameters
dmePath The full path to the .dme to compile.
additionalArguments Optional additional arguments provided to the compiler.
Returns
The formatted arguments string.
Implemented in Tgstation.Server.Host.Components.Engine.ByondInstallation, Tgstation.Server.Host.Components.Engine.EngineExecutableLock, Tgstation.Server.Host.Components.Engine.EngineInstallationBase, and Tgstation.Server.Host.Components.Engine.OpenDreamInstallation.
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.RunDreamMaker().
FormatServerArguments()
string Tgstation.Server.Host.Components.Engine.IEngineInstallation.FormatServerArguments (IDmbProvider dmbProvider, IReadOnlyDictionary< string, string > parameters, DreamDaemonLaunchParameters launchParameters, string? logFilePath)
Return the command line arguments for launching with given launchParameters .
Parameters
dmbProvider The IDmbProvider.
parameters The map of parameter strings as a IReadOnlyDictionary<TKey, TValue>. MUST include Interop.DMApiConstants.ParamAccessIdentifier. Should NOT include the DreamDaemonLaunchParameters.AdditionalParameters of launchParameters .
launchParameters The DreamDaemonLaunchParameters.
logFilePath The full path to the log file, if any.
Returns
The formatted arguments string.
Implemented in Tgstation.Server.Host.Components.Engine.ByondInstallation, Tgstation.Server.Host.Components.Engine.EngineExecutableLock, Tgstation.Server.Host.Components.Engine.EngineInstallationBase, and Tgstation.Server.Host.Components.Engine.OpenDreamInstallation.
Referenced by Tgstation.Server.Host.Components.Session.SessionControllerFactory.CreateGameServerProcess().
LoadEnv()
ValueTask< Dictionary< string, string >?> Tgstation.Server.Host.Components.Engine.IEngineInstallation.LoadEnv (ILogger logger, bool forCompiler, CancellationToken cancellationToken)
Loads the environment settings for either the server or compiler.
Parameters
logger The ILogger to write to.
forCompiler If false server.env will be loaded. If true compiler.env will be loaded.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask<TResult> resulting in the environment Dictionary<TKey, TValue> or null if the target environment file doesn't exist.
Implemented in Tgstation.Server.Host.Components.Engine.EngineExecutableLock, and Tgstation.Server.Host.Components.Engine.EngineInstallationBase.
Referenced by Tgstation.Server.Host.Components.Session.SessionControllerFactory.CreateGameServerProcess(), and Tgstation.Server.Host.Components.Deployment.DreamMaker.RunDreamMaker().
StopServerProcess()
ValueTask Tgstation.Server.Host.Components.Engine.IEngineInstallation.StopServerProcess (ILogger logger, IProcess process, string accessIdentifier, ushort port, CancellationToken cancellationToken)
Kills a given engine server process .
Parameters
logger The ILogger to write to.
process The IProcess to be terminated.
accessIdentifier The Interop.DMApiParameters.AccessIdentifier of the session.
port The port the server is running on.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implemented in Tgstation.Server.Host.Components.Engine.EngineExecutableLock, Tgstation.Server.Host.Components.Engine.EngineInstallationBase, and Tgstation.Server.Host.Components.Engine.OpenDreamInstallation.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.DisposeAsync().
Property Documentation
CompilerExePath
string Tgstation.Server.Host.Components.Engine.IEngineInstallation.CompilerExePath get
The full path to the dm/DreamMaker executable.
Implemented in Tgstation.Server.Host.Components.Engine.ByondInstallation, Tgstation.Server.Host.Components.Engine.EngineExecutableLock, Tgstation.Server.Host.Components.Engine.EngineInstallationBase, and Tgstation.Server.Host.Components.Engine.OpenDreamInstallation.
Definition at line 32 of file IEngineInstallation.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Deployment.DreamMaker.RunDreamMaker().
HasStandardOutput
bool Tgstation.Server.Host.Components.Engine.IEngineInstallation.HasStandardOutput get
If ServerExePath supports being run as a command-line application and outputs log information to be captured.
Implemented in Tgstation.Server.Host.Components.Engine.ByondInstallation, Tgstation.Server.Host.Components.Engine.EngineExecutableLock, Tgstation.Server.Host.Components.Engine.EngineInstallationBase, and Tgstation.Server.Host.Components.Engine.OpenDreamInstallation.
Definition at line 37 of file IEngineInstallation.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Session.SessionControllerFactory.CreateGameServerProcess().
InstallationTask
Task Tgstation.Server.Host.Components.Engine.IEngineInstallation.InstallationTask get
The Task that completes when the BYOND version finished installing.
Implemented in Tgstation.Server.Host.Components.Engine.ByondInstallation, Tgstation.Server.Host.Components.Engine.EngineExecutableLock, Tgstation.Server.Host.Components.Engine.EngineInstallationBase, and Tgstation.Server.Host.Components.Engine.OpenDreamInstallation.
Definition at line 57 of file IEngineInstallation.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Engine.EngineManager.AssertAndLockVersion().
PreferFileLogging
bool Tgstation.Server.Host.Components.Engine.IEngineInstallation.PreferFileLogging get
If HasStandardOutput is set, this indicates that the engine server has good file logging that should be preferred to ours.
Implemented in Tgstation.Server.Host.Components.Engine.ByondInstallation, Tgstation.Server.Host.Components.Engine.EngineExecutableLock, Tgstation.Server.Host.Components.Engine.EngineInstallationBase, and Tgstation.Server.Host.Components.Engine.OpenDreamInstallation.
Definition at line 47 of file IEngineInstallation.cs.
{ get; }
PromptsForNetworkAccess
bool Tgstation.Server.Host.Components.Engine.IEngineInstallation.PromptsForNetworkAccess get
If ServerExePath may create network prompts.
Implemented in Tgstation.Server.Host.Components.Engine.ByondInstallation, Tgstation.Server.Host.Components.Engine.EngineExecutableLock, Tgstation.Server.Host.Components.Engine.EngineInstallationBase, and Tgstation.Server.Host.Components.Engine.OpenDreamInstallation.
Definition at line 42 of file IEngineInstallation.cs.
{ get; }
ServerExePath
string Tgstation.Server.Host.Components.Engine.IEngineInstallation.ServerExePath get
The full path to the game server executable.
Implemented in Tgstation.Server.Host.Components.Engine.ByondInstallation, Tgstation.Server.Host.Components.Engine.EngineExecutableLock, Tgstation.Server.Host.Components.Engine.EngineInstallationBase, and Tgstation.Server.Host.Components.Engine.OpenDreamInstallation.
Definition at line 27 of file IEngineInstallation.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Session.SessionControllerFactory.CreateGameServerProcess().
UseDotnetDump
bool Tgstation.Server.Host.Components.Engine.IEngineInstallation.UseDotnetDump get
If dotnet-dump should be used to create process dumps for this installation.
Implemented in Tgstation.Server.Host.Components.Engine.ByondInstallation, Tgstation.Server.Host.Components.Engine.EngineExecutableLock, Tgstation.Server.Host.Components.Engine.EngineInstallationBase, and Tgstation.Server.Host.Components.Engine.OpenDreamInstallation.
Definition at line 52 of file IEngineInstallation.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Session.SessionController.CreateDump().
Version
EngineVersion Tgstation.Server.Host.Components.Engine.IEngineInstallation.Version get
The EngineVersion of the IEngineInstallation.
Implemented in Tgstation.Server.Host.Components.Engine.ByondInstallation, Tgstation.Server.Host.Components.Engine.EngineExecutableLock, Tgstation.Server.Host.Components.Engine.EngineInstallationBase, and Tgstation.Server.Host.Components.Engine.OpenDreamInstallation.
Definition at line 22 of file IEngineInstallation.cs.
{ get; }
Referenced by Tgstation.Server.Host.Components.Engine.EngineManager.AddInstallationContainer(), Tgstation.Server.Host.Components.Deployment.DreamMaker.RunCompileJob(), and Tgstation.Server.Host.Components.Deployment.DreamMaker.VerifyApi().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Components/Engine/IEngineInstallation.cs