tgstation-server: Tgstation.Server.Host.Components.Chat.Providers.IProvider Interface Reference
Tgstation.Server.Host.Components.Chat.Providers.IProvider Interface Reference
For interacting with a chat service
Public Member Functions
Task< Message > NextMessage (CancellationToken cancellationToken)
Get a Task<TResult> resulting in the next Message the IProvider recieves or null on a disconnect
Task Disconnect (CancellationToken cancellationToken)
Gracefully disconnects the provider. Permanently stops the reconnection timer.
Task< IReadOnlyCollection< ChannelRepresentation > > MapChannels (IEnumerable< Api.Models.ChatChannel > channels, CancellationToken cancellationToken)
Get the ChannelRepresentations for given channels
Task SendMessage (ulong channelId, string message, CancellationToken cancellationToken)
Send a message to the IProvider
Task SetReconnectInterval (uint reconnectInterval, bool connectNow)
Set the interval at which the provider starts jobs to try to reconnect.
Task< Func< string, string, Task > > SendUpdateMessage (RevisionInformation revisionInformation, Version byondVersion, DateTimeOffset? estimatedCompletionTime, string gitHubOwner, string gitHubRepo, ulong channelId, bool localCommitPushed, CancellationToken cancellationToken)
Send the message for a deployment.
Properties
bool Connected [get]
If the IProvider is currently connected.
bool Disposed [get]
If the IProvider was disposed.
string BotMention [get]
The string that indicates the IProvider was mentioned
Task InitialConnectionJob [get]
A Task that completes once the IProvider finishes it's first connection attempt regardless of success.
Detailed Description
For interacting with a chat service
Definition at line 12 of file IProvider.cs.
Member Function Documentation
Disconnect()
Task Tgstation.Server.Host.Components.Chat.Providers.IProvider.Disconnect (CancellationToken cancellationToken)
Gracefully disconnects the provider. Permanently stops the reconnection timer.
Parameters
cancellationToken The CancellationToken for the operation
Returns
A Task representing the running operation
Implemented in Tgstation.Server.Host.Components.Chat.Providers.Provider.
Referenced by Tgstation.Server.Host.Components.Chat.ChatManager.ChangeSettings(), and Tgstation.Server.Host.Components.Chat.ChatManager.DeleteConnection().
MapChannels()
Task<IReadOnlyCollection<ChannelRepresentation> > Tgstation.Server.Host.Components.Chat.Providers.IProvider.MapChannels (IEnumerable< Api.Models.ChatChannel > channels, CancellationToken cancellationToken)
Get the ChannelRepresentations for given channels
Parameters
channels The Api.Models.ChatChannels to map
cancellationToken The CancellationToken for the operation
Returns
A Task<TResult> resulting in a IReadOnlyCollection<T> of the ChannelRepresentations representing channels
Implemented in Tgstation.Server.Host.Components.Chat.Providers.Provider.
NextMessage()
Task<Message> Tgstation.Server.Host.Components.Chat.Providers.IProvider.NextMessage (CancellationToken cancellationToken)
Get a Task<TResult> resulting in the next Message the IProvider recieves or null on a disconnect
Parameters
cancellationToken The CancellationToken for the operation
Returns
A Task<TResult> resulting in the next available Message or null if the IProvider needed to reconnect.
Note that private messages will come in the form of ChannelRepresentations not returned in MapChannels(IEnumerable<Api.Models.ChatChannel>, CancellationToken). Do not IDisposable.Dispose the IProvider on continuations run from the returned Task.
Implemented in Tgstation.Server.Host.Components.Chat.Providers.Provider.
SendMessage()
Task Tgstation.Server.Host.Components.Chat.Providers.IProvider.SendMessage (ulong channelId, string message, CancellationToken cancellationToken)
Send a message to the IProvider
Parameters
channelId The ChannelRepresentation.RealId to send to
message The message contents
cancellationToken The CancellationToken for the operation
Returns
A Task representing the running operation
Implemented in Tgstation.Server.Host.Components.Chat.Providers.Provider, Tgstation.Server.Host.Components.Chat.Providers.IrcProvider, and Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.
SendUpdateMessage()
Task<Func<string, string, Task> > Tgstation.Server.Host.Components.Chat.Providers.IProvider.SendUpdateMessage (RevisionInformation revisionInformation, Version byondVersion, DateTimeOffset? estimatedCompletionTime, string gitHubOwner, string gitHubRepo, ulong channelId, bool localCommitPushed, CancellationToken cancellationToken)
Send the message for a deployment.
Parameters
revisionInformation The RevisionInformation of the deployment.
byondVersion The BYOND Version of the deployment.
estimatedCompletionTime The optional DateTimeOffset the deployment is expected to be completed at.
gitHubOwner The repository GitHub owner, if any.
gitHubRepo The repository GitHub name, if any.
channelId The ChannelRepresentation.RealId to send to
localCommitPushed true if the local deployment commit was pushed to the remote repository.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in a Func<T1, T2, TResult> to call to update the message at the deployment's conclusion. Parameters: Error message if any, DreamMaker output if any.
Implemented in Tgstation.Server.Host.Components.Chat.Providers.Provider.
SetReconnectInterval()
Task Tgstation.Server.Host.Components.Chat.Providers.IProvider.SetReconnectInterval (uint reconnectInterval, bool connectNow)
Set the interval at which the provider starts jobs to try to reconnect.
Parameters
reconnectInterval The reconnection interval in minutes.
connectNow If a connection attempt should be made now.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.Components.Chat.Providers.Provider.
Referenced by Tgstation.Server.Host.Components.Chat.ChatManager.ChangeSettings().
Property Documentation
BotMention
string Tgstation.Server.Host.Components.Chat.Providers.IProvider.BotMention get
The string that indicates the IProvider was mentioned
Definition at line 27 of file IProvider.cs.
 { get; }
Referenced by Tgstation.Server.Host.Components.Chat.ChatManager.ProcessMessage().
Connected
bool Tgstation.Server.Host.Components.Chat.Providers.IProvider.Connected get
If the IProvider is currently connected.
Definition at line 17 of file IProvider.cs.
 { get; }
Referenced by Tgstation.Server.Host.Components.Chat.ChatManager.ProcessMessage().
Disposed
bool Tgstation.Server.Host.Components.Chat.Providers.IProvider.Disposed get
If the IProvider was disposed.
Definition at line 22 of file IProvider.cs.
 { get; }
InitialConnectionJob
Task Tgstation.Server.Host.Components.Chat.Providers.IProvider.InitialConnectionJob get
A Task that completes once the IProvider finishes it's first connection attempt regardless of success.
Definition at line 32 of file IProvider.cs.
 { get; }
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Components/Chat/Providers/IProvider.cs