tgstation-server: Tgstation.Server.Host.Models.IDatabaseContext Interface Reference
Tgstation.Server.Host.Models.IDatabaseContext Interface Reference
Represents the database
Public Member Functions
Task Save (CancellationToken cancellationToken)
Saves changes made to the IDatabaseContext
Task Initialize (CancellationToken cancellationToken)
Creates and migrates the IDatabaseContext
Properties
DbSet< User > Users [get]
The Users in the IDatabaseContext
DbSet< Instance > Instances [get]
The Instances in the IDatabaseContext
DbSet< InstanceUser > InstanceUsers [get]
The InstanceUsers in the IDatabaseContext
DbSet< Job > Jobs [get]
The Jobs in the IDatabaseContext
DbSet< CompileJob > CompileJobs [get]
The CompileJobs in the IDatabaseContext
DbSet< RevisionInformation > RevisionInformations [get]
The RevisionInformations in the IDatabaseContext
DbSet< DreamMakerSettings > DreamMakerSettings [get, set]
The Models.DreamMakerSettings in the IDatabaseContext
DbSet< DreamDaemonSettings > DreamDaemonSettings [get, set]
The Models.DreamDaemonSettings in the IDatabaseContext
DbSet< ChatBot > ChatBots [get, set]
The Models.ChatBot in the IDatabaseContext
DbSet< ChatChannel > ChatChannels [get, set]
The ChatChannel in the IDatabaseContext
DbSet< RepositorySettings > RepositorySettings [get, set]
The Models.RepositorySettings in the IDatabaseContext
DbSet< ReattachInformation > ReattachInformations [get, set]
The DbSet<TEntity> for Models.ReattachInformations
DbSet< WatchdogReattachInformation > WatchdogReattachInformations [get, set]
The DbSet<TEntity> for Models.WatchdogReattachInformations
Detailed Description
Represents the database
Definition at line 10 of file IDatabaseContext.cs.
Member Function Documentation
Task Tgstation.Server.Host.Models.IDatabaseContext.Initialize (CancellationToken cancellationToken)
Creates and migrates the IDatabaseContext
Parameters
cancellationToken The CancellationToken for the operation
Returns
A Task representing the running operation
Implemented in Tgstation.Server.Host.Models.DatabaseContext< TParentContext >.
Task Tgstation.Server.Host.Models.IDatabaseContext.Save (CancellationToken cancellationToken)
Saves changes made to the IDatabaseContext
Parameters
cancellationToken The CancellationToken for the operation
Returns
A Task representing the running operation
Implemented in Tgstation.Server.Host.Models.DatabaseContext< TParentContext >.
Referenced by Tgstation.Server.Host.Controllers.RepositoryController.Create(), Tgstation.Server.Host.Models.DatabaseSeeder.ResetAdminPassword(), Tgstation.Server.Host.Core.JobManager.RunJob(), and Tgstation.Server.Host.Models.DatabaseSeeder.SeedDatabase().
Property Documentation
DbSet<ChatBot> Tgstation.Server.Host.Models.IDatabaseContext.ChatBots get set
The Models.ChatBot in the IDatabaseContext
Definition at line 55 of file IDatabaseContext.cs.
DbSet<ChatChannel> Tgstation.Server.Host.Models.IDatabaseContext.ChatChannels get set
The ChatChannel in the IDatabaseContext
Definition at line 60 of file IDatabaseContext.cs.
DbSet<CompileJob> Tgstation.Server.Host.Models.IDatabaseContext.CompileJobs get
The CompileJobs in the IDatabaseContext
Definition at line 35 of file IDatabaseContext.cs.
DbSet<DreamDaemonSettings> Tgstation.Server.Host.Models.IDatabaseContext.DreamDaemonSettings get set
The Models.DreamDaemonSettings in the IDatabaseContext
Definition at line 50 of file IDatabaseContext.cs.
Referenced by Tgstation.Server.Host.Controllers.DreamMakerController.RunCompile().
DbSet<DreamMakerSettings> Tgstation.Server.Host.Models.IDatabaseContext.DreamMakerSettings get set
The Models.DreamMakerSettings in the IDatabaseContext
Definition at line 45 of file IDatabaseContext.cs.
DbSet<Instance> Tgstation.Server.Host.Models.IDatabaseContext.Instances get
The Instances in the IDatabaseContext
Definition at line 20 of file IDatabaseContext.cs.
DbSet<InstanceUser> Tgstation.Server.Host.Models.IDatabaseContext.InstanceUsers get
The InstanceUsers in the IDatabaseContext
Definition at line 25 of file IDatabaseContext.cs.
DbSet<Job> Tgstation.Server.Host.Models.IDatabaseContext.Jobs get
The Jobs in the IDatabaseContext
Definition at line 30 of file IDatabaseContext.cs.
Referenced by Tgstation.Server.Host.Core.JobManager.CancelJob(), Tgstation.Server.Host.Core.JobManager.RunJob(), and Tgstation.Server.Host.Core.JobManager.StartAsync().
DbSet<ReattachInformation> Tgstation.Server.Host.Models.IDatabaseContext.ReattachInformations get set
The DbSet<TEntity> for Models.ReattachInformations
Definition at line 70 of file IDatabaseContext.cs.
DbSet<RepositorySettings> Tgstation.Server.Host.Models.IDatabaseContext.RepositorySettings get set
The Models.RepositorySettings in the IDatabaseContext
Definition at line 65 of file IDatabaseContext.cs.
DbSet<RevisionInformation> Tgstation.Server.Host.Models.IDatabaseContext.RevisionInformations get
The RevisionInformations in the IDatabaseContext
Definition at line 40 of file IDatabaseContext.cs.
Referenced by Tgstation.Server.Host.Controllers.RepositoryController.LoadRevisionInformation().
DbSet<User> Tgstation.Server.Host.Models.IDatabaseContext.Users get
The Users in the IDatabaseContext
Definition at line 15 of file IDatabaseContext.cs.
Referenced by Tgstation.Server.Host.Models.DatabaseSeeder.ResetAdminPassword(), and Tgstation.Server.Host.Models.DatabaseSeeder.SeedAdminUser().
DbSet<WatchdogReattachInformation> Tgstation.Server.Host.Models.IDatabaseContext.WatchdogReattachInformations get set
The DbSet<TEntity> for Models.WatchdogReattachInformations
Definition at line 75 of file IDatabaseContext.cs.
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Models/IDatabaseContext.cs