tgstation-server: Tgstation.Server.Client.Components.IDreamDaemonClient Interface Reference
Tgstation.Server.Client.Components.IDreamDaemonClient Interface Reference
For managing DreamDaemon
Public Member Functions
Task< DreamDaemon > Read (CancellationToken cancellationToken)
Get the DreamDaemon represented by the IDreamDaemonClient
Task< Job > Start (CancellationToken cancellationToken)
Start DreamDaemon
Task< Job > Restart (CancellationToken cancellationToken)
Restart DreamDaemon
Task Shutdown (CancellationToken cancellationToken)
Shutdown DreamDaemon
Task< DreamDaemon > Update (DreamDaemon dreamDaemon, CancellationToken cancellationToken)
Update DreamDaemon. This may trigger Api.Models.Internal.DreamDaemonSettings.SoftRestart
Detailed Description
For managing DreamDaemon
Definition at line 10 of file IDreamDaemonClient.cs.
Member Function Documentation
Read()
Task<DreamDaemon> Tgstation.Server.Client.Components.IDreamDaemonClient.Read (CancellationToken cancellationToken)
Get the DreamDaemon represented by the IDreamDaemonClient
Parameters
cancellationToken The CancellationToken for the operation
Returns
A Task<TResult> resulting in the DreamDaemon information
Implemented in Tgstation.Server.Client.Components.DreamDaemonClient.
Referenced by Tgstation.Server.Tests.Instance.WatchdogTest.DeployTestDme(), Tgstation.Server.Tests.Instance.WatchdogTest.GracefulWatchdogShutdown(), Tgstation.Server.Tests.Instance.WatchdogTest.RunBasicTest(), Tgstation.Server.Tests.Instance.WatchdogTest.RunLongRunningTestThenUpdate(), and Tgstation.Server.Tests.Instance.WatchdogTest.RunLongRunningTestThenUpdateWithByondVersionSwitch().
Restart()
Task<Job> Tgstation.Server.Client.Components.IDreamDaemonClient.Restart (CancellationToken cancellationToken)
Restart DreamDaemon
Parameters
cancellationToken The CancellationToken for the operation
Returns
A Task<TResult> resulting in the Job of the running operation
Implemented in Tgstation.Server.Client.Components.DreamDaemonClient.
Shutdown()
Task Tgstation.Server.Client.Components.IDreamDaemonClient.Shutdown (CancellationToken cancellationToken)
Shutdown DreamDaemon
Parameters
cancellationToken The CancellationToken for the operation
Returns
A Task<TResult> resulting in the DreamDaemon information
Implemented in Tgstation.Server.Client.Components.DreamDaemonClient.
Referenced by Tgstation.Server.Tests.Instance.WatchdogTest.RunLongRunningTestThenUpdate(), and Tgstation.Server.Tests.Instance.WatchdogTest.RunLongRunningTestThenUpdateWithByondVersionSwitch().
Start()
Task<Job> Tgstation.Server.Client.Components.IDreamDaemonClient.Start (CancellationToken cancellationToken)
Start DreamDaemon
Parameters
cancellationToken The CancellationToken for the operation
Returns
A Task<TResult> resulting in the Job of the running operation
Implemented in Tgstation.Server.Client.Components.DreamDaemonClient.
Referenced by Tgstation.Server.Tests.Instance.WatchdogTest.RunBasicTest(), Tgstation.Server.Tests.Instance.WatchdogTest.RunLongRunningTestThenUpdate(), Tgstation.Server.Tests.Instance.WatchdogTest.RunLongRunningTestThenUpdateWithByondVersionSwitch(), and Tgstation.Server.Tests.Instance.WatchdogTest.StartAndLeaveRunning().
Update()
Task<DreamDaemon> Tgstation.Server.Client.Components.IDreamDaemonClient.Update (DreamDaemon dreamDaemon, CancellationToken cancellationToken)
Update DreamDaemon. This may trigger Api.Models.Internal.DreamDaemonSettings.SoftRestart
Parameters
dreamDaemon The DreamDaemon to update
cancellationToken The CancellationToken for the operation
Returns
A Task<TResult> resulting in the DreamDaemon information
Implemented in Tgstation.Server.Client.Components.DreamDaemonClient.
Referenced by Tgstation.Server.Tests.Instance.WatchdogTest.GracefulWatchdogShutdown(), and Tgstation.Server.Tests.Instance.WatchdogTest.Run().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Client/Components/IDreamDaemonClient.cs