tgstation-server: Tgstation.Server.Host.Components.Events.IEventConsumer Interface Reference
Tgstation.Server.Host.Components.Events.IEventConsumer Interface Reference
Consumes EventTypes and takes the appropriate actions.
Public Member Functions
ValueTask HandleEvent (EventType eventType, IEnumerable< string?> parameters, bool deploymentPipeline, CancellationToken cancellationToken)
Handle a given eventType .
ValueTask? HandleCustomEvent (string eventName, IEnumerable< string?> parameters, CancellationToken cancellationToken)
Handles a given custom event.
Detailed Description
Consumes EventTypes and takes the appropriate actions.
Definition at line 10 of file IEventConsumer.cs.
Member Function Documentation
HandleCustomEvent()
ValueTask? Tgstation.Server.Host.Components.Events.IEventConsumer.HandleCustomEvent (string eventName, IEnumerable< string?> parameters, CancellationToken cancellationToken)
Handles a given custom event.
Parameters
eventName The name of the event.
parameters An IEnumerable<T> of string parameters for the event.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation if the event was triggered successfully, null if it matched a TGS event and wasn't executed.
Implemented in Tgstation.Server.Host.Components.Events.EventConsumer, Tgstation.Server.Host.Components.Events.NoopEventConsumer, Tgstation.Server.Host.Components.Watchdog.WatchdogBase, and Tgstation.Server.Host.Components.StaticFiles.Configuration.
Referenced by Tgstation.Server.Host.Components.Session.SessionController.TriggerCustomEvent().
HandleEvent()
ValueTask Tgstation.Server.Host.Components.Events.IEventConsumer.HandleEvent (EventType eventType, IEnumerable< string?> parameters, bool deploymentPipeline, CancellationToken cancellationToken)
Handle a given eventType .
Parameters
eventType The EventType.
parameters An IEnumerable<T> of string parameters for eventType .
deploymentPipeline If this event is part of the deployment pipeline.
cancellationToken The CancellationToken for the operation.
Returns
A ValueTask representing the running operation.
Implemented in Tgstation.Server.Host.Components.Events.EventConsumer, Tgstation.Server.Host.Components.Events.NoopEventConsumer, Tgstation.Server.Host.Components.StaticFiles.Configuration, and Tgstation.Server.Host.Components.Watchdog.WatchdogBase.
Referenced by Tgstation.Server.Host.Components.Repository.Repository.AddTestMerge(), Tgstation.Server.Host.Components.Engine.EngineManager.AssertAndLockVersion(), Tgstation.Server.Host.Components.Instance.AutoUpdateAction(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.BeforeApplyDmb(), Tgstation.Server.Host.Components.Engine.EngineManager.ChangeVersion(), Tgstation.Server.Host.Components.Repository.Repository.CheckoutObject(), Tgstation.Server.Host.Components.Deployment.DreamMaker.Compile(), Tgstation.Server.Host.Components.Session.SessionControllerFactory.CreateGameServerProcess(), Tgstation.Server.Host.Components.Deployment.DmbFactory.DeleteCompileJobContent(), Tgstation.Server.Host.Components.Deployment.DreamMaker.DeploymentProcess(), Tgstation.Server.Host.Components.Repository.Repository.FetchOrigin(), Tgstation.Server.Host.Components.Events.EventConsumer.HandleEvent(), Tgstation.Server.Host.Components.Watchdog.WatchdogBase.HandleEventImpl(), Tgstation.Server.Host.Components.Repository.Repository.MergeOrigin(), Tgstation.Server.Host.Components.Repository.Repository.ResetToOrigin(), and Tgstation.Server.Host.Components.Deployment.DreamMaker.RunCompileJob().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Components/Events/IEventConsumer.cs