tgstation-server: Tgstation.Server.Host.IO.ISynchronousIOManager Interface Reference
Tgstation.Server.Host.IO.ISynchronousIOManager Interface Reference
For accessing the disk in a synchronous manner.
Public Member Functions
IEnumerable< string > GetFiles (string path, CancellationToken cancellationToken)
Enumerate files in a given path .
IEnumerable< string > GetDirectories (string path, CancellationToken cancellationToken)
Enumerate directories in a given path .
bool CreateDirectory (string path, CancellationToken cancellationToken)
Create an empty directory at path .
byte[] ReadFile (string path)
Read the bytes of a file at a given path .
bool DeleteDirectory (string path)
Deletes a directory at path if it's empty.
bool WriteFileChecked (string path, Stream data, ref string? sha1InOut, CancellationToken cancellationToken)
Write data to a file at a given path .
bool IsDirectory (string path)
Checks if a given path is a directory.
Detailed Description
For accessing the disk in a synchronous manner.
Definition at line 10 of file ISynchronousIOManager.cs.
Member Function Documentation
CreateDirectory()
bool Tgstation.Server.Host.IO.ISynchronousIOManager.CreateDirectory (string path, CancellationToken cancellationToken)
Create an empty directory at path .
Parameters
path The path to create.
cancellationToken The CancellationToken for the operation. Usage may result in partial writes.
Returns
true if the directory already existed, false otherwise.
Implemented in Tgstation.Server.Host.IO.SynchronousIOManager.
DeleteDirectory()
bool Tgstation.Server.Host.IO.ISynchronousIOManager.DeleteDirectory (string path)
Deletes a directory at path if it's empty.
Parameters
path The path of the directory to delete.
Returns
true if the directory does not exist or is empty and was deleted. false otherwise.
Implemented in Tgstation.Server.Host.IO.SynchronousIOManager.
GetDirectories()
IEnumerable< string > Tgstation.Server.Host.IO.ISynchronousIOManager.GetDirectories (string path, CancellationToken cancellationToken)
Enumerate directories in a given path .
Parameters
path The path to look for directories in.
cancellationToken The CancellationToken for the operation.
Returns
A IEnumerable<T> of directory names in path .
Implemented in Tgstation.Server.Host.IO.SynchronousIOManager.
Referenced by Tgstation.Server.Host.Components.StaticFiles.Configuration.ListDirectory().
GetFiles()
IEnumerable< string > Tgstation.Server.Host.IO.ISynchronousIOManager.GetFiles (string path, CancellationToken cancellationToken)
Enumerate files in a given path .
Parameters
path The path to look for files in.
cancellationToken The CancellationToken for the operation.
Returns
A IEnumerable<T> of file names in path .
Implemented in Tgstation.Server.Host.IO.SynchronousIOManager.
Referenced by Tgstation.Server.Host.Components.StaticFiles.Configuration.ListDirectory().
IsDirectory()
bool Tgstation.Server.Host.IO.ISynchronousIOManager.IsDirectory (string path)
Checks if a given path is a directory.
Parameters
path The path to check.
Returns
true if path is a directory, false otherwise.
Implemented in Tgstation.Server.Host.IO.SynchronousIOManager.
Referenced by Tgstation.Server.Host.Components.StaticFiles.Configuration.Read().
ReadFile()
byte[] Tgstation.Server.Host.IO.ISynchronousIOManager.ReadFile (string path)
Read the bytes of a file at a given path .
Parameters
path The path of the file to read.
Returns
A byte array representing the contents of the file at path .
Implemented in Tgstation.Server.Host.IO.SynchronousIOManager.
Referenced by Tgstation.Server.Host.Components.StaticFiles.Configuration.Read().
WriteFileChecked()
bool Tgstation.Server.Host.IO.ISynchronousIOManager.WriteFileChecked (string path, Stream data, ref string? sha1InOut, CancellationToken cancellationToken)
Write data to a file at a given path .
Parameters
path The path to the file to write.
data A Stream containing the new contents of the file.
sha1InOut The function only succeeds if this parameter matches the SHA-1 hash of the contents of the current file. Contains the SHA1 of the file on disk once the function returns.
cancellationToken The CancellationToken for the operation.
Returns
true on success, false if the operation failed due to sha1InOut not matching the file's contents.
Implemented in Tgstation.Server.Host.IO.SynchronousIOManager.
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/IO/ISynchronousIOManager.cs