tgstation-server: TGServiceInterface.Components.ITGByond Interface Reference
TGServiceInterface.Components.ITGByond Interface Reference
For managing the BYOND installation the server runs
Public Member Functions
ByondStatus CurrentStatus ()
Gets the current status of any BYOND updates
bool UpdateToVersion (int major, int minor)
updates the used byond version to that of version major .minor . The change won't take place until DD reboots. Calls ITGDreamDaemon.RequestRestart if blocked by a running DD instance. Runs asyncronously, use CurrentStatus to check progress
string GetError ()
Check the last update error. Checking this will clear the value
string GetVersion (ByondVersion type)
Get the currently installed version as a string formatted as Major.Minor
Detailed Description
For managing the BYOND installation the server runs
Definition at line 10 of file Byond.cs.
Member Function Documentation
ByondStatus TGServiceInterface.Components.ITGByond.CurrentStatus ()
Gets the current status of any BYOND updates
Returns
The current status of the byond updater
Implemented in TGServerService.ServerInstance.
Referenced by TGCommandLine.BYONDStatusCommand.Run().
string TGServiceInterface.Components.ITGByond.GetError ()
Check the last update error. Checking this will clear the value
Returns
The last update error, if any. otherwise.
Implemented in TGServerService.ServerInstance.
string TGServiceInterface.Components.ITGByond.GetVersion (ByondVersion type)
Get the currently installed version as a string formatted as Major.Minor
Parameters
type The type of version to retrieve
Returns
if no version is detected, the version string otherwise
Implemented in TGServerService.ServerInstance.
Referenced by TGControlPanel.ControlPanel.InitBYONDPage(), TGCommandLine.BYONDVersionCommand.Run(), and TGCommandLine.DMCompileCommand.Run().
bool TGServiceInterface.Components.ITGByond.UpdateToVersion (int major, int minor)
updates the used byond version to that of version major .minor . The change won't take place until DD reboots. Calls ITGDreamDaemon.RequestRestart if blocked by a running DD instance. Runs asyncronously, use CurrentStatus to check progress
Parameters
major Major BYOND version. E.g. 511
minor Minor BYOND version. E.g. 1381
Returns
if the update started, if another operation was in progress or DreamDaemon is running
Implemented in TGServerService.ServerInstance.
Referenced by TGControlPanel.ControlPanel.UpdateButton_Click().
The documentation for this interface was generated from the following file:
TGServiceInterface/Components/Byond.cs