tgstation-server: Tgstation.Server.Host.System.IProcessExecutor Interface Reference
Tgstation.Server.Host.System.IProcessExecutor Interface Reference
For launching IProcess'.
Public Member Functions
ValueTask< IProcess > LaunchProcess (string fileName, string workingDirectory, string arguments, CancellationToken cancellationToken, IReadOnlyDictionary< string, string >? environment=null, string? fileRedirect=null, bool readStandardHandles=false, bool noShellExecute=false)
Launch a IProcess.
IProcess GetCurrentProcess ()
Get a IProcess representing the running executable.
IProcess? GetProcess (int id)
Get a IProcess by id .
IProcess? GetProcessByName (string name)
Get a IProcess with a given name .
Detailed Description
For launching IProcess'.
Definition at line 10 of file IProcessExecutor.cs.
Member Function Documentation
GetCurrentProcess()
IProcess Tgstation.Server.Host.System.IProcessExecutor.GetCurrentProcess ()
Get a IProcess representing the running executable.
Returns
The current IProcess.
Implemented in Tgstation.Server.Host.System.ProcessExecutor.
Referenced by Tgstation.Server.Host.Components.Session.SessionControllerFactory.CheckPagerIsNotRunning().
GetProcess()
IProcess? Tgstation.Server.Host.System.IProcessExecutor.GetProcess (int id)
Get a IProcess by id .
Parameters
id The IProcess.Id.
Returns
The IProcess represented by id on success, null on failure.
Implemented in Tgstation.Server.Host.System.ProcessExecutor.
Referenced by Tgstation.Server.Host.Components.Session.SessionPersistor.Load(), and Tgstation.Server.Host.Components.Session.SessionControllerFactory.Reattach().
GetProcessByName()
IProcess? Tgstation.Server.Host.System.IProcessExecutor.GetProcessByName (string name)
Get a IProcess with a given name .
Parameters
name The name of the process executable without the extension.
Returns
The IProcess represented by name on success, null on failure.
Implemented in Tgstation.Server.Host.System.ProcessExecutor.
Referenced by Tgstation.Server.Host.Components.Session.SessionControllerFactory.CheckPagerIsNotRunning().
LaunchProcess()
ValueTask< IProcess > Tgstation.Server.Host.System.IProcessExecutor.LaunchProcess (string fileName, string workingDirectory, string arguments, CancellationToken cancellationToken, IReadOnlyDictionary< string, string >? environment = null, string? fileRedirect = null, bool readStandardHandles = false, bool noShellExecute = false)
Launch a IProcess.
Parameters
fileName The full path to the executable file.
workingDirectory The working directory for the IProcess.
arguments The arguments for the IProcess.
cancellationToken The CancellationToken for the operation.
environment A IReadOnlyDictionary<TKey, TValue> of environment variables to set.
fileRedirect File to write process output and error streams to. Requires readStandardHandles to be true.
readStandardHandles If the process output and error streams should be read.
noShellExecute If shell execute should not be used. Must be set if readStandardHandles is set.
Returns
A ValueTask<TResult> resulting in the new IProcess.
Implemented in Tgstation.Server.Host.System.ProcessExecutor.
Referenced by Tgstation.Server.Host.System.WindowsFirewallHelper.AddFirewallException(), Tgstation.Server.Host.Components.Session.SessionControllerFactory.CreateGameServerProcess(), and Tgstation.Server.Host.Components.Engine.WindowsByondInstaller.InstallDirectX().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/System/IProcessExecutor.cs