tgstation-server: TGServerService.ITGChatProvider Interface Reference
TGServerService.ITGChatProvider Interface Reference
Public Member Functions
string SetProviderInfo (TGChatSetupInfo info)
Sets info for the provider
TGChatSetupInfo ProviderInfo ()
Gets the info of the provider
string Connect ()
Connects the chat provider if it's enabled
string Reconnect ()
Forces a reconnection of the chat provider if it's enabled
bool Connected ()
Checks if the chat provider is connected
void Disconnect ()
Disconnects the chat provider
string SendMessageDirect (string message, string channel)
Send a message to a channel
void SendMessage (string msg, ChatMessageType mt)
Broadcast a message to appropriate channels based on the message type
Events
OnChatMessage OnChatMessage
Called with chat message info
Detailed Description
Definition at line 20 of file Chat.cs.
Member Function Documentation
string TGServerService.ITGChatProvider.Connect ()
Connects the chat provider if it's enabled
Returns
null on success, error message on failure
Implemented in TGServerService.TGIRCChatProvider, and TGServerService.TGDiscordChatProvider.
Referenced by TGServerService.TGStationServer.InitChat().
bool TGServerService.ITGChatProvider.Connected ()
Checks if the chat provider is connected
Returns
true if the provider is connected, false otherwise
Implemented in TGServerService.TGIRCChatProvider, and TGServerService.TGDiscordChatProvider.
Referenced by TGServerService.TGStationServer.ChatConnectivityCheck().
void TGServerService.ITGChatProvider.Disconnect ()
Disconnects the chat provider
Implemented in TGServerService.TGIRCChatProvider, and TGServerService.TGDiscordChatProvider.
TGChatSetupInfo TGServerService.ITGChatProvider.ProviderInfo ()
Gets the info of the provider
Returns
The info for the chat provider
Implemented in TGServerService.TGDiscordChatProvider, and TGServerService.TGIRCChatProvider.
string TGServerService.ITGChatProvider.Reconnect ()
Forces a reconnection of the chat provider if it's enabled
Returns
null on success, error message on failure
Implemented in TGServerService.TGIRCChatProvider, and TGServerService.TGDiscordChatProvider.
Referenced by TGServerService.TGStationServer.ChatConnectivityCheck().
void TGServerService.ITGChatProvider.SendMessage (string msg, ChatMessageType mt)
Broadcast a message to appropriate channels based on the message type
Parameters
msg The message to send
mt The message type
Implemented in TGServerService.TGIRCChatProvider, and TGServerService.TGDiscordChatProvider.
string TGServerService.ITGChatProvider.SendMessageDirect (string message, string channel)
Send a message to a channel
Parameters
message The message to send
channel The channel to send to
Returns
null on success, error message on failure
Implemented in TGServerService.TGDiscordChatProvider, and TGServerService.TGIRCChatProvider.
Referenced by TGServerService.TGStationServer.ChatProvider_OnChatMessage().
string TGServerService.ITGChatProvider.SetProviderInfo (TGChatSetupInfo info)
Sets info for the provider
Parameters
info The info to set
Returns
null on success, error message on failure
Implemented in TGServerService.TGDiscordChatProvider, and TGServerService.TGIRCChatProvider.
Event Documentation
OnChatMessage TGServerService.ITGChatProvider.OnChatMessage
Called with chat message info
Definition at line 38 of file Chat.cs.
Referenced by TGServerService.TGStationServer.InitChat().
The documentation for this interface was generated from the following file:
TGServerService/Chat.cs