tgstation-server: TGServiceInterface.Components.ITGCompiler Interface Reference
TGServiceInterface.Components.ITGCompiler Interface Reference
For managing the Game A/B/Live folders, compiling, and hotswapping them
Public Member Functions
bool Initialize ()
Sets up the symlinks for hotswapping game code. This will reset everything in the Game folder. Requires the repository to be set up and locks it once the compilation stage starts. Runs asyncronously from this call
bool Compile (bool silent=false)
Does all the necessary actions to take the revision currently in the repository and compile it to be run on the next server reboot. Requires BYOND to be set up and the GetStatus to return CompilerStatus.Initialized. Runs asyncronously
string Cancel ()
Cancels the current compilation
CompilerStatus GetStatus ()
Returns the current compiler status
string CompileError ()
Returns the error message of the last operation. Reading this will clear the stored value
string ProjectName ()
Returns the relative path of the dme the compiler will look for without the .dme part
void SetProjectName (string projectName)
Sets the relative path of the dme the compiler will look for without the .dme part
Detailed Description
For managing the Game A/B/Live folders, compiling, and hotswapping them
Definition at line 9 of file Compiler.cs.
Member Function Documentation
string TGServiceInterface.Components.ITGCompiler.Cancel ()
Cancels the current compilation
Returns
on success, error message on failure
Implemented in TGServerService.ServerInstance.
bool TGServiceInterface.Components.ITGCompiler.Compile (bool silent = false)
Does all the necessary actions to take the revision currently in the repository and compile it to be run on the next server reboot. Requires BYOND to be set up and the GetStatus to return CompilerStatus.Initialized. Runs asyncronously
Parameters
silent If no message for compilation start will be printed
Returns
if the operation began, if it could not start
Implemented in TGServerService.ServerInstance.
Referenced by TGControlPanel.ControlPanel.CompileButton_Click(), and TGControlPanel.ControlPanel.FullUpdateWorker_DoWork().
string TGServiceInterface.Components.ITGCompiler.CompileError ()
Returns the error message of the last operation. Reading this will clear the stored value
Returns
the error message of the last operation if it failed or if it succeeded
Implemented in TGServerService.ServerInstance.
CompilerStatus TGServiceInterface.Components.ITGCompiler.GetStatus ()
Returns the current compiler status
Returns
The current compiler status
Implemented in TGServerService.ServerInstance.
Referenced by TGCommandLine.DMCompileCommand.Run(), and TGCommandLine.DMInitializeCommand.Run().
bool TGServiceInterface.Components.ITGCompiler.Initialize ()
Sets up the symlinks for hotswapping game code. This will reset everything in the Game folder. Requires the repository to be set up and locks it once the compilation stage starts. Runs asyncronously from this call
Returns
if the operation began, if it could not start
Implemented in TGServerService.ServerInstance.
Referenced by TGControlPanel.ControlPanel.InitializeButton_Click().
string TGServiceInterface.Components.ITGCompiler.ProjectName ()
Returns the relative path of the dme the compiler will look for without the .dme part
Returns
The relative path of the dme the compiler will look for without the .dme part
Implemented in TGServerService.ServerInstance.
void TGServiceInterface.Components.ITGCompiler.SetProjectName (string projectName)
Sets the relative path of the dme the compiler will look for without the .dme part
Parameters
projectName The relative path of the dme the compiler will look for without the .dme part
Implemented in TGServerService.ServerInstance.
The documentation for this interface was generated from the following file:
TGServiceInterface/Components/Compiler.cs