tgstation-server: Tgstation.Server.Host.Core.IAsyncDelayer Interface Reference
Tgstation.Server.Host.Core.IAsyncDelayer Interface Reference
For waiting asynchronously.
Public Member Functions
Task Delay (TimeSpan timeSpan, CancellationToken cancellationToken)
Create a Task that completes after a given timeSpan .
Detailed Description
For waiting asynchronously.
Definition at line 10 of file IAsyncDelayer.cs.
Member Function Documentation
Delay()
Task Tgstation.Server.Host.Core.IAsyncDelayer.Delay (TimeSpan timeSpan, CancellationToken cancellationToken)
Create a Task that completes after a given timeSpan .
Parameters
timeSpan The TimeSpan that must elapse.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.Core.AsyncDelayer.
Referenced by Tgstation.Server.Host.Setup.SetupWizard.CheckRunWizard(), Tgstation.Server.Host.Swarm.SwarmService.CommitUpdate(), Tgstation.Server.Host.Security.TokenFactory.CreateToken(), Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.HardDisconnect(), Tgstation.Server.Host.Swarm.SwarmService.HealthCheckController(), Tgstation.Server.Host.Swarm.SwarmService.HealthCheckLoop(), Tgstation.Server.Host.Security.IdentityCacheObject.IdentityCacheObject(), Tgstation.Server.Host.Components.InstanceManager.InitializeSwarm(), Tgstation.Server.Host.Components.InstanceManager.ProcessBridgeRequest(), Tgstation.Server.Host.Setup.SetupWizard.PromptDatabaseType(), Tgstation.Server.Host.Transfer.FileTransferService.QueueExpiry(), Tgstation.Server.Host.System.WindowsNetworkPromptReaper.Run(), Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.SaslAuthenticate(), and Tgstation.Server.Host.System.PosixSignalHandler.SignalChecker().
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Core/IAsyncDelayer.cs