tgstation-server: Tgstation.Server.Host.Swarm.ISwarmOperations Interface Reference
Tgstation.Server.Host.Swarm.ISwarmOperations Interface Reference
Swarm service operations for the Controllers.SwarmController.
Public Member Functions
void UpdateSwarmServersList (IEnumerable< SwarmServerResponse > swarmServers)
Pass in an updated list of swarmServers to the node.
Task< bool > PrepareUpdateFromController (Version version, CancellationToken cancellationToken)
Notify the node of an update request from the controller.
bool ValidateRegistration (Guid registrationId)
Validate a given registrationId .
bool RegisterNode (Api.Models.Internal.SwarmServer node, Guid registrationId)
Attempt to register a given node with the controller.
Task UnregisterNode (Guid registrationId, CancellationToken cancellationToken)
Attempt to unregister a node with a given registrationId with the controller.
Task< bool > RemoteCommitRecieved (Guid registrationId, CancellationToken cancellationToken)
Notify the controller that the node with the given registrationId is ready to commit or notify the node of the controller telling it to commit.
Task RemoteAbortUpdate (CancellationToken cancellationToken)
Remotely abort an uncommitted update.
Detailed Description
Swarm service operations for the Controllers.SwarmController.
Definition at line 13 of file ISwarmOperations.cs.
Member Function Documentation
PrepareUpdateFromController()
Task< bool > Tgstation.Server.Host.Swarm.ISwarmOperations.PrepareUpdateFromController (Version version, CancellationToken cancellationToken)
Notify the node of an update request from the controller.
Parameters
version The Version of TGS to update to.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in true if the node is able to update, false otherwise.
Implemented in Tgstation.Server.Host.Swarm.SwarmService.
Referenced by Tgstation.Server.Host.Controllers.SwarmController.PrepareUpdate().
RegisterNode()
bool Tgstation.Server.Host.Swarm.ISwarmOperations.RegisterNode (Api.Models.Internal.SwarmServer node, Guid registrationId)
Attempt to register a given node with the controller.
Parameters
node The SwarmServerResponse that is registering.
registrationId The registration Guid.
Returns
true if the registration was successful, false otherwise.
Implemented in Tgstation.Server.Host.Swarm.SwarmService.
Referenced by Tgstation.Server.Host.Controllers.SwarmController.Register().
RemoteAbortUpdate()
Task Tgstation.Server.Host.Swarm.ISwarmOperations.RemoteAbortUpdate (CancellationToken cancellationToken)
Remotely abort an uncommitted update.
Parameters
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.Swarm.SwarmService.
Referenced by Tgstation.Server.Host.Controllers.SwarmController.AbortUpdate().
RemoteCommitRecieved()
Task< bool > Tgstation.Server.Host.Swarm.ISwarmOperations.RemoteCommitRecieved (Guid registrationId, CancellationToken cancellationToken)
Notify the controller that the node with the given registrationId is ready to commit or notify the node of the controller telling it to commit.
Parameters
registrationId The registration Guid.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.Swarm.SwarmService.
Referenced by Tgstation.Server.Host.Controllers.SwarmController.CommitUpdate().
UnregisterNode()
Task Tgstation.Server.Host.Swarm.ISwarmOperations.UnregisterNode (Guid registrationId, CancellationToken cancellationToken)
Attempt to unregister a node with a given registrationId with the controller.
Parameters
registrationId The registration Guid.
cancellationToken The CancellationToken for the operation.
Returns
A Task representing the running operation.
Implemented in Tgstation.Server.Host.Swarm.SwarmService.
Referenced by Tgstation.Server.Host.Controllers.SwarmController.UnregisterNode().
UpdateSwarmServersList()
void Tgstation.Server.Host.Swarm.ISwarmOperations.UpdateSwarmServersList (IEnumerable< SwarmServerResponse > swarmServers)
Pass in an updated list of swarmServers to the node.
Parameters
swarmServers An IEnumerable<T> of the updated SwarmServerResponses.
Implemented in Tgstation.Server.Host.Swarm.SwarmService.
Referenced by Tgstation.Server.Host.Controllers.SwarmController.UpdateNodeList().
ValidateRegistration()
bool Tgstation.Server.Host.Swarm.ISwarmOperations.ValidateRegistration (Guid registrationId)
Validate a given registrationId .
Parameters
registrationId The registration Guid to validate.
Returns
true if the registration is valid, false otherwise.
Implemented in Tgstation.Server.Host.Swarm.SwarmService.
The documentation for this interface was generated from the following file:
src/Tgstation.Server.Host/Swarm/ISwarmOperations.cs