tgstation-server: TGServiceInterface.ITGDreamDaemon Interface Reference
TGServiceInterface.ITGDreamDaemon Interface Reference
Interface for managing the actual BYOND game server
Public Member Functions
TGDreamDaemonStatus DaemonStatus ()
Gets the status of DreamDaemon
string StatusString (bool includeMetaInfo)
Returns a human readable string of the current server status
string CanStart ()
Check if a call to Start will fail. Of course, be aware of race conditions with other interfaces
string Start ()
Starts the server if it isn't running
string Stop ()
Immediately kills the server
string Restart ()
Immediately kills and restarts the server
void RequestRestart ()
Restart the server after the currently running world reboots. Has no effect if the server isn't running
void RequestStop ()
Stop the server after the currently running world reboots. Has no effect if the server isn't running
TGDreamDaemonSecurity SecurityLevel ()
Get the configured (not necessarily running) security level
bool SetSecurityLevel (TGDreamDaemonSecurity level)
Sets the security level of the server. Requires server reboot to apply. Calls RequestRestart. Note that anything higher than Trusted will disable interop from DD
ushort Port ()
Get the configured port. Not necessarily the running port if it has since changed
void SetPort (ushort new_port)
Set the port to host DD on. Requires reboot to apply. Calls RequestRestart.
bool Autostart ()
Check if the watchdog will start when the service starts
void SetAutostart (bool on)
Set the autostart config
bool Webclient ()
Check if the BYOND webclient is currently enabled for the server
void SetWebclient (bool on)
Set the webclient config. Calls RequestRestart
bool ShutdownInProgress ()
Checks if a server stop has been requested
string WorldAnnounce (string msg)
Sends a message to everyone on the server
int PlayerCount ()
Returns the number of connected players. Requires game to use API version >= 3.1.0.1
Detailed Description
Interface for managing the actual BYOND game server
Definition at line 47 of file DreamDaemon.cs.
Member Function Documentation
bool TGServiceInterface.ITGDreamDaemon.Autostart ()
Check if the watchdog will start when the service starts
Returns
if autostart is enabled, otherwise
Implemented in TGServerService.TGStationServer.
string TGServiceInterface.ITGDreamDaemon.CanStart ()
Check if a call to Start will fail. Of course, be aware of race conditions with other interfaces
Returns
The error that would occur, otherwise
Implemented in TGServerService.TGStationServer.
TGDreamDaemonStatus TGServiceInterface.ITGDreamDaemon.DaemonStatus ()
Gets the status of DreamDaemon
Returns
The appropriate TGDreamDaemonStatus
Implemented in TGServerService.TGStationServer.
int TGServiceInterface.ITGDreamDaemon.PlayerCount ()
Returns the number of connected players. Requires game to use API version >= 3.1.0.1
Returns
The number of connected players or -1 on error
Implemented in TGServerService.TGStationServer.
ushort TGServiceInterface.ITGDreamDaemon.Port ()
Get the configured port. Not necessarily the running port if it has since changed
Returns
The configured port
Implemented in TGServerService.TGStationServer.
void TGServiceInterface.ITGDreamDaemon.RequestRestart ()
Restart the server after the currently running world reboots. Has no effect if the server isn't running
Implemented in TGServerService.TGStationServer.
void TGServiceInterface.ITGDreamDaemon.RequestStop ()
Stop the server after the currently running world reboots. Has no effect if the server isn't running
Implemented in TGServerService.TGStationServer.
string TGServiceInterface.ITGDreamDaemon.Restart ()
Immediately kills and restarts the server
Returns
on success or error message on failure
Implemented in TGServerService.TGStationServer.
TGDreamDaemonSecurity TGServiceInterface.ITGDreamDaemon.SecurityLevel ()
Get the configured (not necessarily running) security level
Returns
The configured (not necessarily running) TGDreamDaemonSecurity
Implemented in TGServerService.TGStationServer.
void TGServiceInterface.ITGDreamDaemon.SetAutostart (bool on)
Set the autostart config
Parameters
on to start the watchdog with the service, to disable that functionality
Implemented in TGServerService.TGStationServer.
Referenced by TGCommandLine.DDAutostartCommand.Run().
void TGServiceInterface.ITGDreamDaemon.SetPort (ushort new_port)
Set the port to host DD on. Requires reboot to apply. Calls RequestRestart.
Parameters
new_port The new port
Implemented in TGServerService.TGStationServer.
bool TGServiceInterface.ITGDreamDaemon.SetSecurityLevel (TGDreamDaemonSecurity level)
Sets the security level of the server. Requires server reboot to apply. Calls RequestRestart. Note that anything higher than Trusted will disable interop from DD
Parameters
level The new security level
Returns
if the change was immediately applied, otherwise and a call to RequestRestart was made
Implemented in TGServerService.TGStationServer.
Referenced by TGControlPanel.Main.SecuritySelector_SelectedIndexChanged().
void TGServiceInterface.ITGDreamDaemon.SetWebclient (bool on)
Set the webclient config. Calls RequestRestart
Parameters
on to enable the byond webclient for the server, otherwise
Implemented in TGServerService.TGStationServer.
Referenced by TGCommandLine.DDWebclientCommand.Run().
bool TGServiceInterface.ITGDreamDaemon.ShutdownInProgress ()
Checks if a server stop has been requested
Returns
if RequestStop has been called since the last server start, otherwise
Implemented in TGServerService.TGStationServer.
string TGServiceInterface.ITGDreamDaemon.Start ()
Starts the server if it isn't running
Returns
on success or error message on failure
Implemented in TGServerService.TGStationServer.
string TGServiceInterface.ITGDreamDaemon.StatusString (bool includeMetaInfo)
Returns a human readable string of the current server status
Parameters
includeMetaInfo If , the status will include the server's current visibility and security levels
Returns
A human readable string of the current server status
Implemented in TGServerService.TGStationServer.
string TGServiceInterface.ITGDreamDaemon.Stop ()
Immediately kills the server
Returns
on success or error message on failure
Implemented in TGServerService.TGStationServer.
bool TGServiceInterface.ITGDreamDaemon.Webclient ()
Check if the BYOND webclient is currently enabled for the server
Returns
if the webclient is enabled, otherwise
Implemented in TGServerService.TGStationServer.
string TGServiceInterface.ITGDreamDaemon.WorldAnnounce (string msg)
Sends a message to everyone on the server
Parameters
msg The message to send
Returns
on success, error message on failure
Implemented in TGServerService.TGStationServer.
The documentation for this interface was generated from the following file:
TGServiceInterface/DreamDaemon.cs