tgstation-server: TGS.Interface.IClient Interface Reference
TGS.Interface.IClient Interface Reference
Main for communicating the Components.ITGSService
Public Member Functions
bool VersionMismatch (out string errorMessage)
Returns if the IClient interface being used to connect to a service does not have the same release version as the service
ConnectivityLevel ConnectionStatus ()
See ConnectionStatus(out string) without the error argument
ConnectivityLevel ConnectionStatus (out string error)
Used to test if the Components.ITGSService is avaiable on the target machine. Note that state can change at any time and any call into the may throw an exception because of communcation errors
Properties
IServer Server [get]
The IServer the IClient connects to
RemoteLoginInfo LoginInfo [get]
The RemoteLoginInfo for the IClient. Is for local connections
bool IsRemoteConnection [get]
Checks if the IClient is setup for a remote connection
Detailed Description
Main for communicating the Components.ITGSService
Definition at line 8 of file IClient.cs.
Member Function Documentation
ConnectivityLevel TGS.Interface.IClient.ConnectionStatus ()
See ConnectionStatus(out string) without the error argument
Implemented in TGS.Interface.Client.
Referenced by TGS.Installer.UI.Main.CheckForExistingVersion(), TGS.CommandLine.Program.Main(), TGS.CommandLine.Program.RunCommandLine(), TGS.Installer.UI.Main.TellServiceWereComingForThem(), and TGS.ControlPanel.Login.VerifyAndConnect().
ConnectivityLevel TGS.Interface.IClient.ConnectionStatus (out string error)
Used to test if the Components.ITGSService is avaiable on the target machine. Note that state can change at any time and any call into the may throw an exception because of communcation errors
Parameters
error String of the error that prevented an elevated connectivity level
Returns
The apporopriate ConnectivityLevel
Implemented in TGS.Interface.Client.
bool TGS.Interface.IClient.VersionMismatch (out string errorMessage)
Returns if the IClient interface being used to connect to a service does not have the same release version as the service
Parameters
errorMessage An error message to display to the user should this function return
Returns
if the IClient interface being used to connect to a service does not have the same release version as the service
Implemented in TGS.Interface.Client.
Referenced by TGS.CommandLine.Program.Main(), TGS.CommandLine.Program.RunCommandLine(), and TGS.ControlPanel.Login.VerifyAndConnect().
Property Documentation
bool TGS.Interface.IClient.IsRemoteConnection get
Checks if the IClient is setup for a remote connection
Definition at line 23 of file IClient.cs.
RemoteLoginInfo TGS.Interface.IClient.LoginInfo get
The RemoteLoginInfo for the IClient. Is for local connections
Definition at line 18 of file IClient.cs.
IServer TGS.Interface.IClient.Server get
The IServer the IClient connects to
Definition at line 13 of file IClient.cs.
Referenced by TGS.Installer.UI.Main.AttemptMigrationOfNetSettings(), TGS.Installer.UI.Main.CheckForExistingVersion(), TGS.CommandLine.Program.CheckInstanceConnectivity(), TGS.ControlPanel.Program.Main(), TGS.CommandLine.Program.Main(), TGS.CommandLine.Program.ReplaceInterface(), TGS.CommandLine.Program.RunCommandLine(), and TGS.Installer.UI.Main.TellServiceWereComingForThem().
The documentation for this interface was generated from the following file:
TGS.Interface/IClient.cs