tgstation-server: TGServerService.ChatProviders Namespace Reference
TGServerService.ChatProviders Namespace Reference
Classes
class DiscordChatProvider
IChatProvider for Discord: https://discordapp.com/
interface IChatProvider
Interface for a chat provder service
class IRCChatProvider
IChatProvider for internet relay chat
Functions
delegate void OnChatMessage (IChatProvider ChatProvider, string speaker, string channel, string message, bool isAdmin, bool isAdminChannel)
Callback for the chat provider recieving a message
Function Documentation
delegate void TGServerService.ChatProviders.OnChatMessage (IChatProvider ChatProvider, string speaker, string channel, string message, bool isAdmin, bool isAdminChannel)
Callback for the chat provider recieving a message
Parameters
ChatProvider The chat provider the message came from
speaker The username of the speaker
channel The name of the channel
message The message text
isAdmin if speaker is considered a chat admin, otherwise
isAdminChannel if channel is an admin chat channel, otherwise
Referenced by TGServerService.ChatProviders.DiscordChatProvider.Client_MessageReceived(), TGServerService.ChatProviders.IRCChatProvider.Irc_OnChannelMessage(), and TGServerService.ChatProviders.IRCChatProvider.Irc_OnQueryMessage().