var searchData=
[
  ['iadministrationclient_2203',['IAdministrationClient',['../interface_tgstation_1_1_server_1_1_client_1_1_i_administration_client.html',1,'Tgstation::Server::Client']]],
  ['iapiclient_2204',['IApiClient',['../interface_tgstation_1_1_server_1_1_client_1_1_i_api_client.html',1,'Tgstation::Server::Client']]],
  ['iapiclientfactory_2205',['IApiClientFactory',['../interface_tgstation_1_1_server_1_1_client_1_1_i_api_client_factory.html',1,'Tgstation::Server::Client']]],
  ['iassemblyinformationprovider_2206',['IAssemblyInformationProvider',['../interface_tgstation_1_1_server_1_1_host_1_1_system_1_1_i_assembly_information_provider.html',1,'Tgstation::Server::Host::System']]],
  ['iasyncdelayer_2207',['IAsyncDelayer',['../interface_tgstation_1_1_server_1_1_host_1_1_core_1_1_i_async_delayer.html',1,'Tgstation::Server::Host::Core']]],
  ['iauthenticationcontext_2208',['IAuthenticationContext',['../interface_tgstation_1_1_server_1_1_host_1_1_security_1_1_i_authentication_context.html',1,'Tgstation::Server::Host::Security']]],
  ['iauthenticationcontextfactory_2209',['IAuthenticationContextFactory',['../interface_tgstation_1_1_server_1_1_host_1_1_security_1_1_i_authentication_context_factory.html',1,'Tgstation::Server::Host::Security']]],
  ['ibridgedispatcher_2210',['IBridgeDispatcher',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_interop_1_1_i_bridge_dispatcher.html',1,'Tgstation::Server::Host::Components::Interop']]],
  ['ibridgehandler_2211',['IBridgeHandler',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_interop_1_1_i_bridge_handler.html',1,'Tgstation::Server::Host::Components::Interop']]],
  ['ibridgeregistrar_2212',['IBridgeRegistrar',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_interop_1_1_i_bridge_registrar.html',1,'Tgstation::Server::Host::Components::Interop']]],
  ['ibridgeregistration_2213',['IBridgeRegistration',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_interop_1_1_i_bridge_registration.html',1,'Tgstation::Server::Host::Components::Interop']]],
  ['ibyondclient_2214',['IByondClient',['../interface_tgstation_1_1_server_1_1_client_1_1_components_1_1_i_byond_client.html',1,'Tgstation::Server::Client::Components']]],
  ['ibyondexecutablelock_2215',['IByondExecutableLock',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_byond_1_1_i_byond_executable_lock.html',1,'Tgstation::Server::Host::Components::Byond']]],
  ['ibyondinstaller_2216',['IByondInstaller',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_byond_1_1_i_byond_installer.html',1,'Tgstation::Server::Host::Components::Byond']]],
  ['ibyondmanager_2217',['IByondManager',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_byond_1_1_i_byond_manager.html',1,'Tgstation::Server::Host::Components::Byond']]],
  ['ichannelsink_2218',['IChannelSink',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_chat_1_1_i_channel_sink.html',1,'Tgstation::Server::Host::Components::Chat']]],
  ['ichatbotsclient_2219',['IChatBotsClient',['../interface_tgstation_1_1_server_1_1_client_1_1_components_1_1_i_chat_bots_client.html',1,'Tgstation::Server::Client::Components']]],
  ['ichatmanager_2220',['IChatManager',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_chat_1_1_i_chat_manager.html',1,'Tgstation::Server::Host::Components::Chat']]],
  ['ichatmanagerfactory_2221',['IChatManagerFactory',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_chat_1_1_i_chat_manager_factory.html',1,'Tgstation::Server::Host::Components::Chat']]],
  ['ichattrackingcontext_2222',['IChatTrackingContext',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_chat_1_1_i_chat_tracking_context.html',1,'Tgstation::Server::Host::Components::Chat']]],
  ['iclaimsinjector_2223',['IClaimsInjector',['../interface_tgstation_1_1_server_1_1_host_1_1_security_1_1_i_claims_injector.html',1,'Tgstation::Server::Host::Security']]],
  ['icommand_2224',['ICommand',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_chat_1_1_commands_1_1_i_command.html',1,'Tgstation::Server::Host::Components::Chat::Commands']]],
  ['icommandfactory_2225',['ICommandFactory',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_chat_1_1_commands_1_1_i_command_factory.html',1,'Tgstation::Server::Host::Components::Chat::Commands']]],
  ['icompilejobconsumer_2226',['ICompileJobConsumer',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_deployment_1_1_i_compile_job_consumer.html',1,'Tgstation::Server::Host::Components::Deployment']]],
  ['iconfiguration_2227',['IConfiguration',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_static_files_1_1_i_configuration.html',1,'Tgstation::Server::Host::Components::StaticFiles']]],
  ['iconfigurationclient_2228',['IConfigurationClient',['../interface_tgstation_1_1_server_1_1_client_1_1_components_1_1_i_configuration_client.html',1,'Tgstation::Server::Client::Components']]],
  ['iconsole_2229',['IConsole',['../interface_tgstation_1_1_server_1_1_host_1_1_i_o_1_1_i_console.html',1,'Tgstation::Server::Host::IO']]],
  ['icredentialsprovider_2230',['ICredentialsProvider',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_repository_1_1_i_credentials_provider.html',1,'Tgstation::Server::Host::Components::Repository']]],
  ['icryptographysuite_2231',['ICryptographySuite',['../interface_tgstation_1_1_server_1_1_host_1_1_security_1_1_i_cryptography_suite.html',1,'Tgstation::Server::Host::Security']]],
  ['icustomcommandhandler_2232',['ICustomCommandHandler',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_chat_1_1_i_custom_command_handler.html',1,'Tgstation::Server::Host::Components::Chat']]],
  ['idatabasecollection_2233',['IDatabaseCollection',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_collection.html',1,'Tgstation::Server::Host::Database']]],
  ['idatabasecollection_3c_20chatbot_20_3e_2234',['IDatabaseCollection&lt; ChatBot &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_collection.html',1,'Tgstation::Server::Host::Database']]],
  ['idatabasecollection_3c_20chatchannel_20_3e_2235',['IDatabaseCollection&lt; ChatChannel &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_collection.html',1,'Tgstation::Server::Host::Database']]],
  ['idatabasecollection_3c_20compilejob_20_3e_2236',['IDatabaseCollection&lt; CompileJob &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_collection.html',1,'Tgstation::Server::Host::Database']]],
  ['idatabasecollection_3c_20dreamdaemonsettings_20_3e_2237',['IDatabaseCollection&lt; DreamDaemonSettings &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_collection.html',1,'Tgstation::Server::Host::Database']]],
  ['idatabasecollection_3c_20dreammakersettings_20_3e_2238',['IDatabaseCollection&lt; DreamMakerSettings &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_collection.html',1,'Tgstation::Server::Host::Database']]],
  ['idatabasecollection_3c_20instance_20_3e_2239',['IDatabaseCollection&lt; Instance &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_collection.html',1,'Tgstation::Server::Host::Database']]],
  ['idatabasecollection_3c_20instanceuser_20_3e_2240',['IDatabaseCollection&lt; InstanceUser &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_collection.html',1,'Tgstation::Server::Host::Database']]],
  ['idatabasecollection_3c_20job_20_3e_2241',['IDatabaseCollection&lt; Job &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_collection.html',1,'Tgstation::Server::Host::Database']]],
  ['idatabasecollection_3c_20reattachinformation_20_3e_2242',['IDatabaseCollection&lt; ReattachInformation &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_collection.html',1,'Tgstation::Server::Host::Database']]],
  ['idatabasecollection_3c_20repositorysettings_20_3e_2243',['IDatabaseCollection&lt; RepositorySettings &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_collection.html',1,'Tgstation::Server::Host::Database']]],
  ['idatabasecollection_3c_20revisioninformation_20_3e_2244',['IDatabaseCollection&lt; RevisionInformation &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_collection.html',1,'Tgstation::Server::Host::Database']]],
  ['idatabasecollection_3c_20user_20_3e_2245',['IDatabaseCollection&lt; User &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_collection.html',1,'Tgstation::Server::Host::Database']]],
  ['idatabasecollection_3c_20watchdogreattachinformation_20_3e_2246',['IDatabaseCollection&lt; WatchdogReattachInformation &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_collection.html',1,'Tgstation::Server::Host::Database']]],
  ['idatabaseconnectionfactory_2247',['IDatabaseConnectionFactory',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_connection_factory.html',1,'Tgstation::Server::Host::Database']]],
  ['idatabasecontext_2248',['IDatabaseContext',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_context.html',1,'Tgstation::Server::Host::Database']]],
  ['idatabasecontextfactory_2249',['IDatabaseContextFactory',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_context_factory.html',1,'Tgstation::Server::Host::Database']]],
  ['idatabaseseeder_2250',['IDatabaseSeeder',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_seeder.html',1,'Tgstation::Server::Host::Database']]],
  ['identitycache_2251',['IdentityCache',['../class_tgstation_1_1_server_1_1_host_1_1_security_1_1_identity_cache.html',1,'Tgstation::Server::Host::Security']]],
  ['identitycacheobject_2252',['IdentityCacheObject',['../class_tgstation_1_1_server_1_1_host_1_1_security_1_1_identity_cache_object.html',1,'Tgstation::Server::Host::Security']]],
  ['idesigntimedbcontextfactory_2253',['IDesignTimeDbContextFactory',['../class_i_design_time_db_context_factory.html',1,'']]],
  ['idisposable_2254',['IDisposable',['../class_i_disposable.html',1,'']]],
  ['idmbfactory_2255',['IDmbFactory',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_deployment_1_1_i_dmb_factory.html',1,'Tgstation::Server::Host::Components::Deployment']]],
  ['idmbprovider_2256',['IDmbProvider',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_deployment_1_1_i_dmb_provider.html',1,'Tgstation::Server::Host::Components::Deployment']]],
  ['idocumentfilter_2257',['IDocumentFilter',['../class_i_document_filter.html',1,'']]],
  ['idreamdaemonclient_2258',['IDreamDaemonClient',['../interface_tgstation_1_1_server_1_1_client_1_1_components_1_1_i_dream_daemon_client.html',1,'Tgstation::Server::Client::Components']]],
  ['idreammaker_2259',['IDreamMaker',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_deployment_1_1_i_dream_maker.html',1,'Tgstation::Server::Host::Components::Deployment']]],
  ['idreammakerclient_2260',['IDreamMakerClient',['../interface_tgstation_1_1_server_1_1_client_1_1_components_1_1_i_dream_maker_client.html',1,'Tgstation::Server::Client::Components']]],
  ['ieventconsumer_2261',['IEventConsumer',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_i_event_consumer.html',1,'Tgstation::Server::Host::Components']]],
  ['igithubclientfactory_2262',['IGitHubClientFactory',['../interface_tgstation_1_1_server_1_1_host_1_1_core_1_1_i_git_hub_client_factory.html',1,'Tgstation::Server::Host::Core']]],
  ['ihostapplicationlifetime_2263',['IHostApplicationLifetime',['../class_i_host_application_lifetime.html',1,'']]],
  ['ihostedservice_2264',['IHostedService',['../class_i_hosted_service.html',1,'']]],
  ['ihttpclient_2265',['IHttpClient',['../interface_tgstation_1_1_server_1_1_client_1_1_i_http_client.html',1,'Tgstation::Server::Client']]],
  ['iidentitycache_2266',['IIdentityCache',['../interface_tgstation_1_1_server_1_1_host_1_1_security_1_1_i_identity_cache.html',1,'Tgstation::Server::Host::Security']]],
  ['iinstance_2267',['IInstance',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_i_instance.html',1,'Tgstation::Server::Host::Components']]],
  ['iinstanceclient_2268',['IInstanceClient',['../interface_tgstation_1_1_server_1_1_client_1_1_components_1_1_i_instance_client.html',1,'Tgstation::Server::Client::Components']]],
  ['iinstancefactory_2269',['IInstanceFactory',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_i_instance_factory.html',1,'Tgstation::Server::Host::Components']]],
  ['iinstancemanager_2270',['IInstanceManager',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_i_instance_manager.html',1,'Tgstation::Server::Host::Components']]],
  ['iinstancemanagerclient_2271',['IInstanceManagerClient',['../interface_tgstation_1_1_server_1_1_client_1_1_i_instance_manager_client.html',1,'Tgstation::Server::Client']]],
  ['iinstanceuserclient_2272',['IInstanceUserClient',['../interface_tgstation_1_1_server_1_1_client_1_1_components_1_1_i_instance_user_client.html',1,'Tgstation::Server::Client::Components']]],
  ['iiomanager_2273',['IIOManager',['../interface_tgstation_1_1_server_1_1_host_1_1_i_o_1_1_i_i_o_manager.html',1,'Tgstation::Server::Host::IO']]],
  ['ijobmanager_2274',['IJobManager',['../interface_tgstation_1_1_server_1_1_host_1_1_jobs_1_1_i_job_manager.html',1,'Tgstation::Server::Host::Jobs']]],
  ['ijobsclient_2275',['IJobsClient',['../interface_tgstation_1_1_server_1_1_client_1_1_components_1_1_i_jobs_client.html',1,'Tgstation::Server::Client::Components']]],
  ['ilibgit2commands_2276',['ILibGit2Commands',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_repository_1_1_i_lib_git2_commands.html',1,'Tgstation::Server::Host::Components::Repository']]],
  ['ilibgit2repositoryfactory_2277',['ILibGit2RepositoryFactory',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_repository_1_1_i_lib_git2_repository_factory.html',1,'Tgstation::Server::Host::Components::Repository']]],
  ['inetworkpromptreaper_2278',['INetworkPromptReaper',['../interface_tgstation_1_1_server_1_1_host_1_1_system_1_1_i_network_prompt_reaper.html',1,'Tgstation::Server::Host::System']]],
  ['instance_2279',['Instance',['../class_tgstation_1_1_server_1_1_host_1_1_components_1_1_instance.html',1,'Tgstation.Server.Host.Components.Instance'],['../class_tgstation_1_1_server_1_1_host_1_1_models_1_1_instance.html',1,'Tgstation.Server.Host.Models.Instance'],['../class_tgstation_1_1_server_1_1_api_1_1_models_1_1_instance.html',1,'Tgstation.Server.Api.Models.Instance']]],
  ['instanceclient_2280',['InstanceClient',['../class_tgstation_1_1_server_1_1_client_1_1_components_1_1_instance_client.html',1,'Tgstation::Server::Client::Components']]],
  ['instancecontroller_2281',['InstanceController',['../class_tgstation_1_1_server_1_1_host_1_1_controllers_1_1_instance_controller.html',1,'Tgstation::Server::Host::Controllers']]],
  ['instancefactory_2282',['InstanceFactory',['../class_tgstation_1_1_server_1_1_host_1_1_components_1_1_instance_factory.html',1,'Tgstation::Server::Host::Components']]],
  ['instancemanager_2283',['InstanceManager',['../class_tgstation_1_1_server_1_1_host_1_1_components_1_1_instance_manager.html',1,'Tgstation::Server::Host::Components']]],
  ['instancemanagerclient_2284',['InstanceManagerClient',['../class_tgstation_1_1_server_1_1_client_1_1_instance_manager_client.html',1,'Tgstation::Server::Client']]],
  ['instancemanagertest_2285',['InstanceManagerTest',['../class_tgstation_1_1_server_1_1_tests_1_1_instance_manager_test.html',1,'Tgstation::Server::Tests']]],
  ['instancetest_2286',['InstanceTest',['../class_tgstation_1_1_server_1_1_tests_1_1_instance_1_1_instance_test.html',1,'Tgstation::Server::Tests::Instance']]],
  ['instanceuser_2287',['InstanceUser',['../class_tgstation_1_1_server_1_1_host_1_1_models_1_1_instance_user.html',1,'Tgstation.Server.Host.Models.InstanceUser'],['../class_tgstation_1_1_server_1_1_api_1_1_models_1_1_instance_user.html',1,'Tgstation.Server.Api.Models.InstanceUser']]],
  ['instanceuserclient_2288',['InstanceUserClient',['../class_tgstation_1_1_server_1_1_client_1_1_components_1_1_instance_user_client.html',1,'Tgstation::Server::Client::Components']]],
  ['instanceusercontroller_2289',['InstanceUserController',['../class_tgstation_1_1_server_1_1_host_1_1_controllers_1_1_instance_user_controller.html',1,'Tgstation::Server::Host::Controllers']]],
  ['insufficientpermissionsexception_2290',['InsufficientPermissionsException',['../class_tgstation_1_1_server_1_1_client_1_1_insufficient_permissions_exception.html',1,'Tgstation::Server::Client']]],
  ['integrationtest_2291',['IntegrationTest',['../class_tgstation_1_1_server_1_1_tests_1_1_integration_test.html',1,'Tgstation::Server::Tests']]],
  ['iopenapiextension_2292',['IOpenApiExtension',['../class_i_open_api_extension.html',1,'']]],
  ['ioperationfilter_2293',['IOperationFilter',['../class_i_operation_filter.html',1,'']]],
  ['iplatformidentifier_2294',['IPlatformIdentifier',['../interface_tgstation_1_1_server_1_1_host_1_1_system_1_1_i_platform_identifier.html',1,'Tgstation::Server::Host::System']]],
  ['ipostsetupservices_2295',['IPostSetupServices',['../interface_tgstation_1_1_server_1_1_host_1_1_setup_1_1_i_post_setup_services.html',1,'Tgstation::Server::Host::Setup']]],
  ['ipostwritehandler_2296',['IPostWriteHandler',['../interface_tgstation_1_1_server_1_1_host_1_1_i_o_1_1_i_post_write_handler.html',1,'Tgstation::Server::Host::IO']]],
  ['iprocess_2297',['IProcess',['../interface_tgstation_1_1_server_1_1_host_1_1_system_1_1_i_process.html',1,'Tgstation::Server::Host::System']]],
  ['iprocessbase_2298',['IProcessBase',['../interface_tgstation_1_1_server_1_1_host_1_1_system_1_1_i_process_base.html',1,'Tgstation::Server::Host::System']]],
  ['iprocessexecutor_2299',['IProcessExecutor',['../interface_tgstation_1_1_server_1_1_host_1_1_system_1_1_i_process_executor.html',1,'Tgstation::Server::Host::System']]],
  ['iprovider_2300',['IProvider',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_chat_1_1_providers_1_1_i_provider.html',1,'Tgstation::Server::Host::Components::Chat::Providers']]],
  ['iproviderfactory_2301',['IProviderFactory',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_chat_1_1_providers_1_1_i_provider_factory.html',1,'Tgstation::Server::Host::Components::Chat::Providers']]],
  ['iqueryable_2302',['IQueryable',['../class_i_queryable.html',1,'']]],
  ['ircconnectionstringbuilder_2303',['IrcConnectionStringBuilder',['../class_tgstation_1_1_server_1_1_api_1_1_models_1_1_irc_connection_string_builder.html',1,'Tgstation::Server::Api::Models']]],
  ['ircprovider_2304',['IrcProvider',['../class_tgstation_1_1_server_1_1_host_1_1_components_1_1_chat_1_1_providers_1_1_irc_provider.html',1,'Tgstation::Server::Host::Components::Chat::Providers']]],
  ['ireattachinfohandler_2305',['IReattachInfoHandler',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_watchdog_1_1_i_reattach_info_handler.html',1,'Tgstation::Server::Host::Components::Watchdog']]],
  ['irepository_2306',['IRepository',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_repository_1_1_i_repository.html',1,'Tgstation::Server::Host::Components::Repository']]],
  ['irepositoryclient_2307',['IRepositoryClient',['../interface_tgstation_1_1_server_1_1_client_1_1_components_1_1_i_repository_client.html',1,'Tgstation::Server::Client::Components']]],
  ['irepositorymanager_2308',['IRepositoryManager',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_repository_1_1_i_repository_manager.html',1,'Tgstation::Server::Host::Components::Repository']]],
  ['irequestlogger_2309',['IRequestLogger',['../interface_tgstation_1_1_server_1_1_client_1_1_i_request_logger.html',1,'Tgstation::Server::Client']]],
  ['irestarthandler_2310',['IRestartHandler',['../interface_tgstation_1_1_server_1_1_host_1_1_core_1_1_i_restart_handler.html',1,'Tgstation::Server::Host::Core']]],
  ['irestartregistration_2311',['IRestartRegistration',['../interface_tgstation_1_1_server_1_1_host_1_1_core_1_1_i_restart_registration.html',1,'Tgstation::Server::Host::Core']]],
  ['ischemafilter_2312',['ISchemaFilter',['../class_i_schema_filter.html',1,'']]],
  ['iserver_2313',['IServer',['../interface_tgstation_1_1_server_1_1_host_1_1_i_server.html',1,'Tgstation::Server::Host']]],
  ['iserverclient_2314',['IServerClient',['../interface_tgstation_1_1_server_1_1_client_1_1_i_server_client.html',1,'Tgstation::Server::Client']]],
  ['iserverclientfactory_2315',['IServerClientFactory',['../interface_tgstation_1_1_server_1_1_client_1_1_i_server_client_factory.html',1,'Tgstation::Server::Client']]],
  ['iservercontrol_2316',['IServerControl',['../interface_tgstation_1_1_server_1_1_host_1_1_core_1_1_i_server_control.html',1,'Tgstation::Server::Host::Core']]],
  ['iserverfactory_2317',['IServerFactory',['../interface_tgstation_1_1_server_1_1_host_1_1_i_server_factory.html',1,'Tgstation::Server::Host']]],
  ['iserverportprovider_2318',['IServerPortProvider',['../interface_tgstation_1_1_server_1_1_host_1_1_core_1_1_i_server_port_provider.html',1,'Tgstation::Server::Host::Core']]],
  ['isessioncontroller_2319',['ISessionController',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_watchdog_1_1_i_session_controller.html',1,'Tgstation::Server::Host::Components::Watchdog']]],
  ['isessioncontrollerfactory_2320',['ISessionControllerFactory',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_watchdog_1_1_i_session_controller_factory.html',1,'Tgstation::Server::Host::Components::Watchdog']]],
  ['isymlinkfactory_2321',['ISymlinkFactory',['../interface_tgstation_1_1_server_1_1_host_1_1_i_o_1_1_i_symlink_factory.html',1,'Tgstation::Server::Host::IO']]],
  ['isynchronousiomanager_2322',['ISynchronousIOManager',['../interface_tgstation_1_1_server_1_1_host_1_1_i_o_1_1_i_synchronous_i_o_manager.html',1,'Tgstation::Server::Host::IO']]],
  ['isystemidentity_2323',['ISystemIdentity',['../interface_tgstation_1_1_server_1_1_host_1_1_security_1_1_i_system_identity.html',1,'Tgstation::Server::Host::Security']]],
  ['isystemidentityfactory_2324',['ISystemIdentityFactory',['../interface_tgstation_1_1_server_1_1_host_1_1_security_1_1_i_system_identity_factory.html',1,'Tgstation::Server::Host::Security']]],
  ['itokenfactory_2325',['ITokenFactory',['../interface_tgstation_1_1_server_1_1_host_1_1_security_1_1_i_token_factory.html',1,'Tgstation::Server::Host::Security']]],
  ['iusersclient_2326',['IUsersClient',['../interface_tgstation_1_1_server_1_1_client_1_1_i_users_client.html',1,'Tgstation::Server::Client']]],
  ['iwatchdog_2327',['IWatchdog',['../interface_tgstation_1_1_server_1_1_host_1_1_watchdog_1_1_i_watchdog.html',1,'Tgstation.Server.Host.Watchdog.IWatchdog'],['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_watchdog_1_1_i_watchdog.html',1,'Tgstation.Server.Host.Components.Watchdog.IWatchdog']]],
  ['iwatchdogfactory_2328',['IWatchdogFactory',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_watchdog_1_1_i_watchdog_factory.html',1,'Tgstation.Server.Host.Components.Watchdog.IWatchdogFactory'],['../interface_tgstation_1_1_server_1_1_host_1_1_watchdog_1_1_i_watchdog_factory.html',1,'Tgstation.Server.Host.Watchdog.IWatchdogFactory']]]
];
