var searchData=
[
  ['scriptexecutor',['ScriptExecutor',['../class_tgstation_1_1_server_1_1_host_1_1_components_1_1_static_files_1_1_script_executor.html',1,'Tgstation::Server::Host::Components::StaticFiles']]],
  ['semaphoreslimcontext',['SemaphoreSlimContext',['../class_tgstation_1_1_server_1_1_host_1_1_core_1_1_semaphore_slim_context.html',1,'Tgstation::Server::Host::Core']]],
  ['server',['Server',['../class_tgstation_1_1_server_1_1_host_1_1_server.html',1,'Tgstation::Server::Host']]],
  ['serverclientfactory',['ServerClientFactory',['../class_tgstation_1_1_server_1_1_client_1_1_server_client_factory.html',1,'Tgstation::Server::Client']]],
  ['serverfactory',['ServerFactory',['../class_tgstation_1_1_server_1_1_host_1_1_server_factory.html',1,'Tgstation::Server::Host']]],
  ['serverservice',['ServerService',['../class_tgstation_1_1_server_1_1_host_1_1_service_1_1_server_service.html',1,'Tgstation::Server::Host::Service']]],
  ['serversidemodifications',['ServerSideModifications',['../class_tgstation_1_1_server_1_1_host_1_1_components_1_1_static_files_1_1_server_side_modifications.html',1,'Tgstation::Server::Host::Components::StaticFiles']]],
  ['servicebase',['ServiceBase',['../class_service_base.html',1,'']]],
  ['session',['Session',['../class_tgstation_1_1_server_1_1_host_1_1_components_1_1_watchdog_1_1_session.html',1,'Tgstation::Server::Host::Components::Watchdog']]],
  ['sessioncontroller',['SessionController',['../class_tgstation_1_1_server_1_1_host_1_1_components_1_1_watchdog_1_1_session_controller.html',1,'Tgstation::Server::Host::Components::Watchdog']]],
  ['sessioncontrollerfactory',['SessionControllerFactory',['../class_tgstation_1_1_server_1_1_host_1_1_components_1_1_watchdog_1_1_session_controller_factory.html',1,'Tgstation::Server::Host::Components::Watchdog']]],
  ['sqlitedatabasecontext',['SqliteDatabaseContext',['../class_tgstation_1_1_server_1_1_host_1_1_models_1_1_sqlite_database_context.html',1,'Tgstation::Server::Host::Models']]],
  ['sqlitedesigntimedbcontextfactory',['SqliteDesignTimeDbContextFactory',['../class_tgstation_1_1_server_1_1_host_1_1_models_1_1_migrations_1_1_sqlite_design_time_db_context_factory.html',1,'Tgstation::Server::Host::Models::Migrations']]],
  ['sqlserverdatabasecontext',['SqlServerDatabaseContext',['../class_tgstation_1_1_server_1_1_host_1_1_models_1_1_sql_server_database_context.html',1,'Tgstation::Server::Host::Models']]],
  ['sqlserverdesigntimedbcontextfactory',['SqlServerDesignTimeDbContextFactory',['../class_tgstation_1_1_server_1_1_host_1_1_models_1_1_migrations_1_1_sql_server_design_time_db_context_factory.html',1,'Tgstation::Server::Host::Models::Migrations']]],
  ['synchronousiomanager',['SynchronousIOManager',['../class_tgstation_1_1_server_1_1_host_1_1_i_o_1_1_synchronous_i_o_manager.html',1,'Tgstation::Server::Host::IO']]]
];
