var searchData=
[
  ['iabstracthttpclientfactory_0',['IAbstractHttpClientFactory',['../interface_tgstation_1_1_server_1_1_common_1_1_http_1_1_i_abstract_http_client_factory.html',1,'Tgstation::Server::Common::Http']]],
  ['iactionresultexecutor_1',['IActionResultExecutor',['../class_i_action_result_executor.html',1,'']]],
  ['iadministrationclient_2',['IAdministrationClient',['../interface_tgstation_1_1_server_1_1_client_1_1_i_administration_client.html',1,'Tgstation::Server::Client']]],
  ['iapiclient_3',['IApiClient',['../interface_tgstation_1_1_server_1_1_client_1_1_i_api_client.html',1,'Tgstation::Server::Client']]],
  ['iapiclientfactory_4',['IApiClientFactory',['../interface_tgstation_1_1_server_1_1_client_1_1_i_api_client_factory.html',1,'Tgstation::Server::Client']]],
  ['iapiheadersprovider_5',['IApiHeadersProvider',['../interface_tgstation_1_1_server_1_1_host_1_1_utils_1_1_i_api_headers_provider.html',1,'Tgstation::Server::Host::Utils']]],
  ['iapitransformable_6',['IApiTransformable',['../interface_tgstation_1_1_server_1_1_host_1_1_models_1_1_i_api_transformable.html',1,'Tgstation::Server::Host::Models']]],
  ['iapitransformable_3c_20api_2emodels_2eoauthconnection_20_3e_7',['IApiTransformable&lt; Api.Models.OAuthConnection &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_models_1_1_i_api_transformable.html',1,'Tgstation::Server::Host::Models']]],
  ['iapitransformable_3c_20api_2emodels_2erevisioninformation_20_3e_8',['IApiTransformable&lt; Api.Models.RevisionInformation &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_models_1_1_i_api_transformable.html',1,'Tgstation::Server::Host::Models']]],
  ['iapitransformable_3c_20api_2emodels_2etestmerge_20_3e_9',['IApiTransformable&lt; Api.Models.TestMerge &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_models_1_1_i_api_transformable.html',1,'Tgstation::Server::Host::Models']]],
  ['iapitransformable_3c_20chatbotresponse_20_3e_10',['IApiTransformable&lt; ChatBotResponse &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_models_1_1_i_api_transformable.html',1,'Tgstation::Server::Host::Models']]],
  ['iapitransformable_3c_20compilejobresponse_20_3e_11',['IApiTransformable&lt; CompileJobResponse &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_models_1_1_i_api_transformable.html',1,'Tgstation::Server::Host::Models']]],
  ['iapitransformable_3c_20dreammakerresponse_20_3e_12',['IApiTransformable&lt; DreamMakerResponse &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_models_1_1_i_api_transformable.html',1,'Tgstation::Server::Host::Models']]],
  ['iapitransformable_3c_20instancepermissionsetresponse_20_3e_13',['IApiTransformable&lt; InstancePermissionSetResponse &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_models_1_1_i_api_transformable.html',1,'Tgstation::Server::Host::Models']]],
  ['iapitransformable_3c_20instanceresponse_20_3e_14',['IApiTransformable&lt; InstanceResponse &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_models_1_1_i_api_transformable.html',1,'Tgstation::Server::Host::Models']]],
  ['iapitransformable_3c_20jobresponse_20_3e_15',['IApiTransformable&lt; JobResponse &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_models_1_1_i_api_transformable.html',1,'Tgstation::Server::Host::Models']]],
  ['iapitransformable_3c_20repositoryresponse_20_3e_16',['IApiTransformable&lt; RepositoryResponse &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_models_1_1_i_api_transformable.html',1,'Tgstation::Server::Host::Models']]],
  ['iapitransformable_3c_20usergroupresponse_20_3e_17',['IApiTransformable&lt; UserGroupResponse &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_models_1_1_i_api_transformable.html',1,'Tgstation::Server::Host::Models']]],
  ['iapitransformable_3c_20userresponse_20_3e_18',['IApiTransformable&lt; UserResponse &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_models_1_1_i_api_transformable.html',1,'Tgstation::Server::Host::Models']]],
  ['iassemblyinformationprovider_19',['IAssemblyInformationProvider',['../interface_tgstation_1_1_server_1_1_host_1_1_system_1_1_i_assembly_information_provider.html',1,'Tgstation::Server::Host::System']]],
  ['iasyncdelayer_20',['IAsyncDelayer',['../interface_tgstation_1_1_server_1_1_host_1_1_utils_1_1_i_async_delayer.html',1,'Tgstation::Server::Host::Utils']]],
  ['iasyncdisposable_21',['IAsyncDisposable',['../class_i_async_disposable.html',1,'']]],
  ['iasyncenumerable_22',['IAsyncEnumerable',['../class_i_async_enumerable.html',1,'']]],
  ['iauthenticatedgithubservice_23',['IAuthenticatedGitHubService',['../interface_tgstation_1_1_server_1_1_host_1_1_utils_1_1_git_hub_1_1_i_authenticated_git_hub_service.html',1,'Tgstation::Server::Host::Utils::GitHub']]],
  ['iauthenticationcontext_24',['IAuthenticationContext',['../interface_tgstation_1_1_server_1_1_host_1_1_security_1_1_i_authentication_context.html',1,'Tgstation::Server::Host::Security']]],
  ['iauthenticationcontextfactory_25',['IAuthenticationContextFactory',['../interface_tgstation_1_1_server_1_1_host_1_1_security_1_1_i_authentication_context_factory.html',1,'Tgstation::Server::Host::Security']]],
  ['iauthorizationfilter_26',['IAuthorizationFilter',['../class_i_authorization_filter.html',1,'']]],
  ['ibridgedispatcher_27',['IBridgeDispatcher',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_interop_1_1_bridge_1_1_i_bridge_dispatcher.html',1,'Tgstation::Server::Host::Components::Interop::Bridge']]],
  ['ibridgehandler_28',['IBridgeHandler',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_interop_1_1_bridge_1_1_i_bridge_handler.html',1,'Tgstation::Server::Host::Components::Interop::Bridge']]],
  ['ibridgeregistrar_29',['IBridgeRegistrar',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_interop_1_1_bridge_1_1_i_bridge_registrar.html',1,'Tgstation::Server::Host::Components::Interop::Bridge']]],
  ['ibridgeregistration_30',['IBridgeRegistration',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_interop_1_1_bridge_1_1_i_bridge_registration.html',1,'Tgstation::Server::Host::Components::Interop::Bridge']]],
  ['ichannelsink_31',['IChannelSink',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_chat_1_1_i_channel_sink.html',1,'Tgstation::Server::Host::Components::Chat']]],
  ['ichatbotsclient_32',['IChatBotsClient',['../interface_tgstation_1_1_server_1_1_client_1_1_components_1_1_i_chat_bots_client.html',1,'Tgstation::Server::Client::Components']]],
  ['ichatmanager_33',['IChatManager',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_chat_1_1_i_chat_manager.html',1,'Tgstation::Server::Host::Components::Chat']]],
  ['ichatmanagerfactory_34',['IChatManagerFactory',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_chat_1_1_i_chat_manager_factory.html',1,'Tgstation::Server::Host::Components::Chat']]],
  ['ichattrackingcontext_35',['IChatTrackingContext',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_chat_1_1_i_chat_tracking_context.html',1,'Tgstation::Server::Host::Components::Chat']]],
  ['ichunkpayloadid_36',['IChunkPayloadId',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_interop_1_1_i_chunk_payload_id.html',1,'Tgstation::Server::Host::Components::Interop']]],
  ['iclaimstransformation_37',['IClaimsTransformation',['../class_i_claims_transformation.html',1,'']]],
  ['icommand_38',['ICommand',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_chat_1_1_commands_1_1_i_command.html',1,'Tgstation::Server::Host::Components::Chat::Commands']]],
  ['icommandfactory_39',['ICommandFactory',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_chat_1_1_commands_1_1_i_command_factory.html',1,'Tgstation::Server::Host::Components::Chat::Commands']]],
  ['icompilejobsink_40',['ICompileJobSink',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_deployment_1_1_i_compile_job_sink.html',1,'Tgstation::Server::Host::Components::Deployment']]],
  ['icomponentservice_41',['IComponentService',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_i_component_service.html',1,'Tgstation::Server::Host::Components']]],
  ['iconfiguration_42',['IConfiguration',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_static_files_1_1_i_configuration.html',1,'Tgstation::Server::Host::Components::StaticFiles']]],
  ['iconfigurationclient_43',['IConfigurationClient',['../interface_tgstation_1_1_server_1_1_client_1_1_components_1_1_i_configuration_client.html',1,'Tgstation::Server::Client::Components']]],
  ['iconfigurationfile_44',['IConfigurationFile',['../interface_tgstation_1_1_server_1_1_api_1_1_models_1_1_i_configuration_file.html',1,'Tgstation::Server::Api::Models']]],
  ['iconnectionmappedhubcontext_45',['IConnectionMappedHubContext',['../interface_tgstation_1_1_server_1_1_host_1_1_utils_1_1_signal_r_1_1_i_connection_mapped_hub_context.html',1,'Tgstation::Server::Host::Utils::SignalR']]],
  ['iconnectionmappedhubcontext_3c_20tgstation_3a_3aserver_3a_3ahost_3a_3ajobs_3a_3ajobshub_2c_20ijobshub_20_3e_46',['IConnectionMappedHubContext&lt; Tgstation::Server::Host::Jobs::JobsHub, IJobsHub &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_utils_1_1_signal_r_1_1_i_connection_mapped_hub_context.html',1,'Tgstation::Server::Host::Utils::SignalR']]],
  ['iconsole_47',['IConsole',['../interface_tgstation_1_1_server_1_1_host_1_1_i_o_1_1_i_console.html',1,'Tgstation::Server::Host::IO']]],
  ['icredentialsprovider_48',['ICredentialsProvider',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_repository_1_1_i_credentials_provider.html',1,'Tgstation::Server::Host::Components::Repository']]],
  ['icryptographysuite_49',['ICryptographySuite',['../interface_tgstation_1_1_server_1_1_host_1_1_security_1_1_i_cryptography_suite.html',1,'Tgstation::Server::Host::Security']]],
  ['icustomcommandhandler_50',['ICustomCommandHandler',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_chat_1_1_i_custom_command_handler.html',1,'Tgstation::Server::Host::Components::Chat']]],
  ['idatabasecollection_51',['IDatabaseCollection',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_collection.html',1,'Tgstation::Server::Host::Database']]],
  ['idatabasecollection_3c_20chatbot_20_3e_52',['IDatabaseCollection&lt; ChatBot &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_collection.html',1,'Tgstation::Server::Host::Database']]],
  ['idatabasecollection_3c_20chatchannel_20_3e_53',['IDatabaseCollection&lt; ChatChannel &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_collection.html',1,'Tgstation::Server::Host::Database']]],
  ['idatabasecollection_3c_20compilejob_20_3e_54',['IDatabaseCollection&lt; CompileJob &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_collection.html',1,'Tgstation::Server::Host::Database']]],
  ['idatabasecollection_3c_20dreamdaemonsettings_20_3e_55',['IDatabaseCollection&lt; DreamDaemonSettings &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_collection.html',1,'Tgstation::Server::Host::Database']]],
  ['idatabasecollection_3c_20dreammakersettings_20_3e_56',['IDatabaseCollection&lt; DreamMakerSettings &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_collection.html',1,'Tgstation::Server::Host::Database']]],
  ['idatabasecollection_3c_20instance_20_3e_57',['IDatabaseCollection&lt; Instance &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_collection.html',1,'Tgstation::Server::Host::Database']]],
  ['idatabasecollection_3c_20instancepermissionset_20_3e_58',['IDatabaseCollection&lt; InstancePermissionSet &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_collection.html',1,'Tgstation::Server::Host::Database']]],
  ['idatabasecollection_3c_20job_20_3e_59',['IDatabaseCollection&lt; Job &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_collection.html',1,'Tgstation::Server::Host::Database']]],
  ['idatabasecollection_3c_20oauthconnection_20_3e_60',['IDatabaseCollection&lt; OAuthConnection &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_collection.html',1,'Tgstation::Server::Host::Database']]],
  ['idatabasecollection_3c_20permissionset_20_3e_61',['IDatabaseCollection&lt; PermissionSet &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_collection.html',1,'Tgstation::Server::Host::Database']]],
  ['idatabasecollection_3c_20reattachinformation_20_3e_62',['IDatabaseCollection&lt; ReattachInformation &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_collection.html',1,'Tgstation::Server::Host::Database']]],
  ['idatabasecollection_3c_20repositorysettings_20_3e_63',['IDatabaseCollection&lt; RepositorySettings &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_collection.html',1,'Tgstation::Server::Host::Database']]],
  ['idatabasecollection_3c_20revinfotestmerge_20_3e_64',['IDatabaseCollection&lt; RevInfoTestMerge &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_collection.html',1,'Tgstation::Server::Host::Database']]],
  ['idatabasecollection_3c_20revisioninformation_20_3e_65',['IDatabaseCollection&lt; RevisionInformation &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_collection.html',1,'Tgstation::Server::Host::Database']]],
  ['idatabasecollection_3c_20testmerge_20_3e_66',['IDatabaseCollection&lt; TestMerge &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_collection.html',1,'Tgstation::Server::Host::Database']]],
  ['idatabasecollection_3c_20user_20_3e_67',['IDatabaseCollection&lt; User &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_collection.html',1,'Tgstation::Server::Host::Database']]],
  ['idatabasecollection_3c_20usergroup_20_3e_68',['IDatabaseCollection&lt; UserGroup &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_collection.html',1,'Tgstation::Server::Host::Database']]],
  ['idatabaseconnectionfactory_69',['IDatabaseConnectionFactory',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_connection_factory.html',1,'Tgstation::Server::Host::Database']]],
  ['idatabasecontext_70',['IDatabaseContext',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_context.html',1,'Tgstation::Server::Host::Database']]],
  ['idatabasecontextfactory_71',['IDatabaseContextFactory',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_context_factory.html',1,'Tgstation::Server::Host::Database']]],
  ['idatabaseseeder_72',['IDatabaseSeeder',['../interface_tgstation_1_1_server_1_1_host_1_1_database_1_1_i_database_seeder.html',1,'Tgstation::Server::Host::Database']]],
  ['identitycache_73',['IdentityCache',['../class_tgstation_1_1_server_1_1_host_1_1_security_1_1_identity_cache.html',1,'Tgstation::Server::Host::Security']]],
  ['identitycacheobject_74',['IdentityCacheObject',['../class_tgstation_1_1_server_1_1_host_1_1_security_1_1_identity_cache_object.html',1,'Tgstation::Server::Host::Security']]],
  ['idesigntimedbcontextfactory_75',['IDesignTimeDbContextFactory',['../class_i_design_time_db_context_factory.html',1,'']]],
  ['idiscordresponders_76',['IDiscordResponders',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_chat_1_1_providers_1_1_i_discord_responders.html',1,'Tgstation::Server::Host::Components::Chat::Providers']]],
  ['idisposable_77',['IDisposable',['../class_i_disposable.html',1,'']]],
  ['idmbfactory_78',['IDmbFactory',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_deployment_1_1_i_dmb_factory.html',1,'Tgstation::Server::Host::Components::Deployment']]],
  ['idmbprovider_79',['IDmbProvider',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_deployment_1_1_i_dmb_provider.html',1,'Tgstation::Server::Host::Components::Deployment']]],
  ['idocumentfilter_80',['IDocumentFilter',['../class_i_document_filter.html',1,'']]],
  ['idotnetdumpservice_81',['IDotnetDumpService',['../interface_tgstation_1_1_server_1_1_host_1_1_system_1_1_i_dotnet_dump_service.html',1,'Tgstation::Server::Host::System']]],
  ['idreamdaemonclient_82',['IDreamDaemonClient',['../interface_tgstation_1_1_server_1_1_client_1_1_components_1_1_i_dream_daemon_client.html',1,'Tgstation::Server::Client::Components']]],
  ['idreammaker_83',['IDreamMaker',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_deployment_1_1_i_dream_maker.html',1,'Tgstation::Server::Host::Components::Deployment']]],
  ['idreammakerclient_84',['IDreamMakerClient',['../interface_tgstation_1_1_server_1_1_client_1_1_components_1_1_i_dream_maker_client.html',1,'Tgstation::Server::Client::Components']]],
  ['iengineclient_85',['IEngineClient',['../interface_tgstation_1_1_server_1_1_client_1_1_components_1_1_i_engine_client.html',1,'Tgstation::Server::Client::Components']]],
  ['iengineexecutablelock_86',['IEngineExecutableLock',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_engine_1_1_i_engine_executable_lock.html',1,'Tgstation::Server::Host::Components::Engine']]],
  ['iengineinstallation_87',['IEngineInstallation',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_engine_1_1_i_engine_installation.html',1,'Tgstation::Server::Host::Components::Engine']]],
  ['iengineinstallationdata_88',['IEngineInstallationData',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_engine_1_1_i_engine_installation_data.html',1,'Tgstation::Server::Host::Components::Engine']]],
  ['iengineinstaller_89',['IEngineInstaller',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_engine_1_1_i_engine_installer.html',1,'Tgstation::Server::Host::Components::Engine']]],
  ['ienginemanager_90',['IEngineManager',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_engine_1_1_i_engine_manager.html',1,'Tgstation::Server::Host::Components::Engine']]],
  ['iequatable_91',['IEquatable',['../class_i_equatable.html',1,'']]],
  ['ieventconsumer_92',['IEventConsumer',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_events_1_1_i_event_consumer.html',1,'Tgstation::Server::Host::Components::Events']]],
  ['ifiledownloader_93',['IFileDownloader',['../interface_tgstation_1_1_server_1_1_host_1_1_i_o_1_1_i_file_downloader.html',1,'Tgstation::Server::Host::IO']]],
  ['ifilestreamprovider_94',['IFileStreamProvider',['../interface_tgstation_1_1_server_1_1_host_1_1_i_o_1_1_i_file_stream_provider.html',1,'Tgstation::Server::Host::IO']]],
  ['ifilesystemlinkfactory_95',['IFilesystemLinkFactory',['../interface_tgstation_1_1_server_1_1_host_1_1_i_o_1_1_i_filesystem_link_factory.html',1,'Tgstation::Server::Host::IO']]],
  ['ifiletransferstreamhandler_96',['IFileTransferStreamHandler',['../interface_tgstation_1_1_server_1_1_host_1_1_transfer_1_1_i_file_transfer_stream_handler.html',1,'Tgstation::Server::Host::Transfer']]],
  ['ifiletransferticketprovider_97',['IFileTransferTicketProvider',['../interface_tgstation_1_1_server_1_1_host_1_1_transfer_1_1_i_file_transfer_ticket_provider.html',1,'Tgstation::Server::Host::Transfer']]],
  ['ifileuploadticket_98',['IFileUploadTicket',['../interface_tgstation_1_1_server_1_1_host_1_1_transfer_1_1_i_file_upload_ticket.html',1,'Tgstation::Server::Host::Transfer']]],
  ['igithubclientfactory_99',['IGitHubClientFactory',['../interface_tgstation_1_1_server_1_1_host_1_1_utils_1_1_git_hub_1_1_i_git_hub_client_factory.html',1,'Tgstation::Server::Host::Utils::GitHub']]],
  ['igithubservice_100',['IGitHubService',['../interface_tgstation_1_1_server_1_1_host_1_1_utils_1_1_git_hub_1_1_i_git_hub_service.html',1,'Tgstation::Server::Host::Utils::GitHub']]],
  ['igithubservicefactory_101',['IGitHubServiceFactory',['../interface_tgstation_1_1_server_1_1_host_1_1_utils_1_1_git_hub_1_1_i_git_hub_service_factory.html',1,'Tgstation::Server::Host::Utils::GitHub']]],
  ['igitremoteadditionalinformation_102',['IGitRemoteAdditionalInformation',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_repository_1_1_i_git_remote_additional_information.html',1,'Tgstation::Server::Host::Components::Repository']]],
  ['igitremotefeatures_103',['IGitRemoteFeatures',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_repository_1_1_i_git_remote_features.html',1,'Tgstation::Server::Host::Components::Repository']]],
  ['igitremotefeaturesfactory_104',['IGitRemoteFeaturesFactory',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_repository_1_1_i_git_remote_features_factory.html',1,'Tgstation::Server::Host::Components::Repository']]],
  ['igitremoteinformation_105',['IGitRemoteInformation',['../interface_tgstation_1_1_server_1_1_api_1_1_models_1_1_internal_1_1_i_git_remote_information.html',1,'Tgstation::Server::Api::Models::Internal']]],
  ['ihostedservice_106',['IHostedService',['../class_i_hosted_service.html',1,'']]],
  ['ihttpclient_107',['IHttpClient',['../interface_tgstation_1_1_server_1_1_common_1_1_http_1_1_i_http_client.html',1,'Tgstation::Server::Common::Http']]],
  ['ihubconnectionmapper_108',['IHubConnectionMapper',['../interface_tgstation_1_1_server_1_1_host_1_1_utils_1_1_signal_r_1_1_i_hub_connection_mapper.html',1,'Tgstation::Server::Host::Utils::SignalR']]],
  ['ihubconnectionmapper_3c_20tchildhub_2c_20thubmethods_20_3e_109',['IHubConnectionMapper&lt; TChildHub, THubMethods &gt;',['../interface_tgstation_1_1_server_1_1_host_1_1_utils_1_1_signal_r_1_1_i_hub_connection_mapper.html',1,'Tgstation::Server::Host::Utils::SignalR']]],
  ['ihubcontext_110',['IHubContext',['../class_i_hub_context.html',1,'']]],
  ['ihubfilter_111',['IHubFilter',['../class_i_hub_filter.html',1,'']]],
  ['iidentitycache_112',['IIdentityCache',['../interface_tgstation_1_1_server_1_1_host_1_1_security_1_1_i_identity_cache.html',1,'Tgstation::Server::Host::Security']]],
  ['iinstance_113',['IInstance',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_i_instance.html',1,'Tgstation::Server::Host::Components']]],
  ['iinstanceclient_114',['IInstanceClient',['../interface_tgstation_1_1_server_1_1_client_1_1_components_1_1_i_instance_client.html',1,'Tgstation::Server::Client::Components']]],
  ['iinstancecore_115',['IInstanceCore',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_i_instance_core.html',1,'Tgstation::Server::Host::Components']]],
  ['iinstancecoreprovider_116',['IInstanceCoreProvider',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_i_instance_core_provider.html',1,'Tgstation::Server::Host::Components']]],
  ['iinstancefactory_117',['IInstanceFactory',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_i_instance_factory.html',1,'Tgstation::Server::Host::Components']]],
  ['iinstancemanager_118',['IInstanceManager',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_i_instance_manager.html',1,'Tgstation::Server::Host::Components']]],
  ['iinstancemanagerclient_119',['IInstanceManagerClient',['../interface_tgstation_1_1_server_1_1_client_1_1_i_instance_manager_client.html',1,'Tgstation::Server::Client']]],
  ['iinstanceoperations_120',['IInstanceOperations',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_i_instance_operations.html',1,'Tgstation::Server::Host::Components']]],
  ['iinstancepermissionsetclient_121',['IInstancePermissionSetClient',['../interface_tgstation_1_1_server_1_1_client_1_1_components_1_1_i_instance_permission_set_client.html',1,'Tgstation::Server::Client::Components']]],
  ['iinstancereference_122',['IInstanceReference',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_i_instance_reference.html',1,'Tgstation::Server::Host::Components']]],
  ['iiomanager_123',['IIOManager',['../interface_tgstation_1_1_server_1_1_host_1_1_i_o_1_1_i_i_o_manager.html',1,'Tgstation::Server::Host::IO']]],
  ['ijobmanager_124',['IJobManager',['../interface_tgstation_1_1_server_1_1_host_1_1_jobs_1_1_i_job_manager.html',1,'Tgstation::Server::Host::Jobs']]],
  ['ijobsclient_125',['IJobsClient',['../interface_tgstation_1_1_server_1_1_client_1_1_components_1_1_i_jobs_client.html',1,'Tgstation::Server::Client::Components']]],
  ['ijobservice_126',['IJobService',['../interface_tgstation_1_1_server_1_1_host_1_1_jobs_1_1_i_job_service.html',1,'Tgstation::Server::Host::Jobs']]],
  ['ijobshub_127',['IJobsHub',['../interface_tgstation_1_1_server_1_1_api_1_1_hubs_1_1_i_jobs_hub.html',1,'Tgstation::Server::Api::Hubs']]],
  ['ijobshubupdater_128',['IJobsHubUpdater',['../interface_tgstation_1_1_server_1_1_host_1_1_jobs_1_1_i_jobs_hub_updater.html',1,'Tgstation::Server::Host::Jobs']]],
  ['ilatestcompilejobprovider_129',['ILatestCompileJobProvider',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_deployment_1_1_i_latest_compile_job_provider.html',1,'Tgstation::Server::Host::Components::Deployment']]],
  ['ilibgit2commands_130',['ILibGit2Commands',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_repository_1_1_i_lib_git2_commands.html',1,'Tgstation::Server::Host::Components::Repository']]],
  ['ilibgit2repositoryfactory_131',['ILibGit2RepositoryFactory',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_repository_1_1_i_lib_git2_repository_factory.html',1,'Tgstation::Server::Host::Components::Repository']]],
  ['imissingpayloadscommunication_132',['IMissingPayloadsCommunication',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_interop_1_1_i_missing_payloads_communication.html',1,'Tgstation::Server::Host::Components::Interop']]],
  ['inetworkpromptreaper_133',['INetworkPromptReaper',['../interface_tgstation_1_1_server_1_1_host_1_1_system_1_1_i_network_prompt_reaper.html',1,'Tgstation::Server::Host::System']]],
  ['infinitethirtysecondmaxretrypolicy_134',['InfiniteThirtySecondMaxRetryPolicy',['../class_tgstation_1_1_server_1_1_client_1_1_infinite_thirty_second_max_retry_policy.html',1,'Tgstation::Server::Client']]],
  ['installationextensions_135',['InstallationExtensions',['../class_tgstation_1_1_server_1_1_host_1_1_service_1_1_wix_1_1_extensions_1_1_installation_extensions.html',1,'Tgstation::Server::Host::Service::Wix::Extensions']]],
  ['instance_136',['instance',['../class_tgstation_1_1_server_1_1_api_1_1_models_1_1_instance.html',1,'Tgstation.Server.Api.Models.Instance'],['../class_tgstation_1_1_server_1_1_host_1_1_components_1_1_instance.html',1,'Tgstation.Server.Host.Components.Instance'],['../class_tgstation_1_1_server_1_1_host_1_1_models_1_1_instance.html',1,'Tgstation.Server.Host.Models.Instance']]],
  ['instanceclient_137',['InstanceClient',['../class_tgstation_1_1_server_1_1_client_1_1_components_1_1_instance_client.html',1,'Tgstation::Server::Client::Components']]],
  ['instancecontroller_138',['InstanceController',['../class_tgstation_1_1_server_1_1_host_1_1_controllers_1_1_instance_controller.html',1,'Tgstation::Server::Host::Controllers']]],
  ['instancecreaterequest_139',['InstanceCreateRequest',['../class_tgstation_1_1_server_1_1_api_1_1_models_1_1_request_1_1_instance_create_request.html',1,'Tgstation::Server::Api::Models::Request']]],
  ['instancefactory_140',['InstanceFactory',['../class_tgstation_1_1_server_1_1_host_1_1_components_1_1_instance_factory.html',1,'Tgstation::Server::Host::Components']]],
  ['instancemanager_141',['InstanceManager',['../class_tgstation_1_1_server_1_1_host_1_1_components_1_1_instance_manager.html',1,'Tgstation::Server::Host::Components']]],
  ['instancemanagerclient_142',['InstanceManagerClient',['../class_tgstation_1_1_server_1_1_client_1_1_instance_manager_client.html',1,'Tgstation::Server::Client']]],
  ['instancepermissionset_143',['instancepermissionset',['../class_tgstation_1_1_server_1_1_api_1_1_models_1_1_internal_1_1_instance_permission_set.html',1,'Tgstation.Server.Api.Models.Internal.InstancePermissionSet'],['../class_tgstation_1_1_server_1_1_host_1_1_models_1_1_instance_permission_set.html',1,'Tgstation.Server.Host.Models.InstancePermissionSet']]],
  ['instancepermissionsetclient_144',['InstancePermissionSetClient',['../class_tgstation_1_1_server_1_1_client_1_1_components_1_1_instance_permission_set_client.html',1,'Tgstation::Server::Client::Components']]],
  ['instancepermissionsetcontroller_145',['InstancePermissionSetController',['../class_tgstation_1_1_server_1_1_host_1_1_controllers_1_1_instance_permission_set_controller.html',1,'Tgstation::Server::Host::Controllers']]],
  ['instancepermissionsetrequest_146',['InstancePermissionSetRequest',['../class_tgstation_1_1_server_1_1_api_1_1_models_1_1_request_1_1_instance_permission_set_request.html',1,'Tgstation::Server::Api::Models::Request']]],
  ['instancepermissionsetresponse_147',['InstancePermissionSetResponse',['../class_tgstation_1_1_server_1_1_api_1_1_models_1_1_response_1_1_instance_permission_set_response.html',1,'Tgstation::Server::Api::Models::Response']]],
  ['instancerequiredcontroller_148',['InstanceRequiredController',['../class_tgstation_1_1_server_1_1_host_1_1_controllers_1_1_instance_required_controller.html',1,'Tgstation::Server::Host::Controllers']]],
  ['instanceresponse_149',['InstanceResponse',['../class_tgstation_1_1_server_1_1_api_1_1_models_1_1_response_1_1_instance_response.html',1,'Tgstation::Server::Api::Models::Response']]],
  ['instanceupdaterequest_150',['InstanceUpdateRequest',['../class_tgstation_1_1_server_1_1_api_1_1_models_1_1_request_1_1_instance_update_request.html',1,'Tgstation::Server::Api::Models::Request']]],
  ['instancewrapper_151',['InstanceWrapper',['../class_tgstation_1_1_server_1_1_host_1_1_components_1_1_instance_wrapper.html',1,'Tgstation::Server::Host::Components']]],
  ['insufficientpermissionsexception_152',['InsufficientPermissionsException',['../class_tgstation_1_1_server_1_1_client_1_1_insufficient_permissions_exception.html',1,'Tgstation::Server::Client']]],
  ['internalconfiguration_153',['InternalConfiguration',['../class_tgstation_1_1_server_1_1_host_1_1_configuration_1_1_internal_configuration.html',1,'Tgstation::Server::Host::Configuration']]],
  ['invisioncommunityoauthvalidator_154',['InvisionCommunityOAuthValidator',['../class_tgstation_1_1_server_1_1_host_1_1_security_1_1_o_auth_1_1_invision_community_o_auth_validator.html',1,'Tgstation::Server::Host::Security::OAuth']]],
  ['ioauthproviders_155',['IOAuthProviders',['../interface_tgstation_1_1_server_1_1_host_1_1_security_1_1_o_auth_1_1_i_o_auth_providers.html',1,'Tgstation::Server::Host::Security::OAuth']]],
  ['ioauthvalidator_156',['IOAuthValidator',['../interface_tgstation_1_1_server_1_1_host_1_1_security_1_1_o_auth_1_1_i_o_auth_validator.html',1,'Tgstation::Server::Host::Security::OAuth']]],
  ['iomanagerextensions_157',['IOManagerExtensions',['../class_tgstation_1_1_server_1_1_host_1_1_extensions_1_1_i_o_manager_extensions.html',1,'Tgstation::Server::Host::Extensions']]],
  ['iopenapiextension_158',['IOpenApiExtension',['../class_i_open_api_extension.html',1,'']]],
  ['ioperationfilter_159',['IOperationFilter',['../class_i_operation_filter.html',1,'']]],
  ['ipermissionsupdatenotifyee_160',['IPermissionsUpdateNotifyee',['../interface_tgstation_1_1_server_1_1_host_1_1_security_1_1_i_permissions_update_notifyee.html',1,'Tgstation::Server::Host::Security']]],
  ['iplatformidentifier_161',['IPlatformIdentifier',['../interface_tgstation_1_1_server_1_1_host_1_1_system_1_1_i_platform_identifier.html',1,'Tgstation::Server::Host::System']]],
  ['iportallocator_162',['IPortAllocator',['../interface_tgstation_1_1_server_1_1_host_1_1_utils_1_1_i_port_allocator.html',1,'Tgstation::Server::Host::Utils']]],
  ['ipostsetupservices_163',['IPostSetupServices',['../interface_tgstation_1_1_server_1_1_host_1_1_setup_1_1_i_post_setup_services.html',1,'Tgstation::Server::Host::Setup']]],
  ['ipostwritehandler_164',['IPostWriteHandler',['../interface_tgstation_1_1_server_1_1_host_1_1_i_o_1_1_i_post_write_handler.html',1,'Tgstation::Server::Host::IO']]],
  ['iprocess_165',['IProcess',['../interface_tgstation_1_1_server_1_1_host_1_1_system_1_1_i_process.html',1,'Tgstation::Server::Host::System']]],
  ['iprocessbase_166',['IProcessBase',['../interface_tgstation_1_1_server_1_1_host_1_1_system_1_1_i_process_base.html',1,'Tgstation::Server::Host::System']]],
  ['iprocessexecutor_167',['IProcessExecutor',['../interface_tgstation_1_1_server_1_1_host_1_1_system_1_1_i_process_executor.html',1,'Tgstation::Server::Host::System']]],
  ['iprocessfeatures_168',['IProcessFeatures',['../interface_tgstation_1_1_server_1_1_host_1_1_system_1_1_i_process_features.html',1,'Tgstation::Server::Host::System']]],
  ['iprovider_169',['IProvider',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_chat_1_1_providers_1_1_i_provider.html',1,'Tgstation::Server::Host::Components::Chat::Providers']]],
  ['iproviderfactory_170',['IProviderFactory',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_chat_1_1_providers_1_1_i_provider_factory.html',1,'Tgstation::Server::Host::Components::Chat::Providers']]],
  ['iqueryable_171',['IQueryable',['../class_i_queryable.html',1,'']]],
  ['ircconnectionstringbuilder_172',['IrcConnectionStringBuilder',['../class_tgstation_1_1_server_1_1_api_1_1_models_1_1_irc_connection_string_builder.html',1,'Tgstation::Server::Api::Models']]],
  ['ircprovider_173',['IrcProvider',['../class_tgstation_1_1_server_1_1_host_1_1_components_1_1_chat_1_1_providers_1_1_irc_provider.html',1,'Tgstation::Server::Host::Components::Chat::Providers']]],
  ['iremotedeploymentmanager_174',['IRemoteDeploymentManager',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_deployment_1_1_remote_1_1_i_remote_deployment_manager.html',1,'Tgstation::Server::Host::Components::Deployment::Remote']]],
  ['iremotedeploymentmanagerfactory_175',['IRemoteDeploymentManagerFactory',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_deployment_1_1_remote_1_1_i_remote_deployment_manager_factory.html',1,'Tgstation::Server::Host::Components::Deployment::Remote']]],
  ['irenamenotifyee_176',['IRenameNotifyee',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_i_rename_notifyee.html',1,'Tgstation::Server::Host::Components']]],
  ['irepository_177',['IRepository',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_repository_1_1_i_repository.html',1,'Tgstation::Server::Host::Components::Repository']]],
  ['irepositoryclient_178',['IRepositoryClient',['../interface_tgstation_1_1_server_1_1_client_1_1_components_1_1_i_repository_client.html',1,'Tgstation::Server::Client::Components']]],
  ['irepositorymanager_179',['IRepositoryManager',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_repository_1_1_i_repository_manager.html',1,'Tgstation::Server::Host::Components::Repository']]],
  ['irepositorymanagerfactory_180',['IRepositoryManagerFactory',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_repository_1_1_i_repository_manager_factory.html',1,'Tgstation::Server::Host::Components::Repository']]],
  ['irequestbodyfilter_181',['IRequestBodyFilter',['../class_i_request_body_filter.html',1,'']]],
  ['irequestlogger_182',['IRequestLogger',['../interface_tgstation_1_1_server_1_1_client_1_1_i_request_logger.html',1,'Tgstation::Server::Client']]],
  ['iresponder_183',['IResponder',['../class_i_responder.html',1,'']]],
  ['irestarthandler_184',['IRestartHandler',['../interface_tgstation_1_1_server_1_1_host_1_1_core_1_1_i_restart_handler.html',1,'Tgstation::Server::Host::Core']]],
  ['irestartregistration_185',['IRestartRegistration',['../interface_tgstation_1_1_server_1_1_host_1_1_core_1_1_i_restart_registration.html',1,'Tgstation::Server::Host::Core']]],
  ['iretrypolicy_186',['IRetryPolicy',['../class_i_retry_policy.html',1,'']]],
  ['ischemafilter_187',['ISchemaFilter',['../class_i_schema_filter.html',1,'']]],
  ['iseekablefilestreamprovider_188',['ISeekableFileStreamProvider',['../interface_tgstation_1_1_server_1_1_host_1_1_i_o_1_1_i_seekable_file_stream_provider.html',1,'Tgstation::Server::Host::IO']]],
  ['iserver_189',['IServer',['../interface_tgstation_1_1_server_1_1_host_1_1_i_server.html',1,'Tgstation::Server::Host']]],
  ['iserverclient_190',['IServerClient',['../interface_tgstation_1_1_server_1_1_client_1_1_i_server_client.html',1,'Tgstation::Server::Client']]],
  ['iserverclientfactory_191',['IServerClientFactory',['../interface_tgstation_1_1_server_1_1_client_1_1_i_server_client_factory.html',1,'Tgstation::Server::Client']]],
  ['iservercontrol_192',['IServerControl',['../interface_tgstation_1_1_server_1_1_host_1_1_core_1_1_i_server_control.html',1,'Tgstation::Server::Host::Core']]],
  ['iserverfactory_193',['IServerFactory',['../interface_tgstation_1_1_server_1_1_host_1_1_i_server_factory.html',1,'Tgstation::Server::Host']]],
  ['iserverportprovider_194',['IServerPortProvider',['../interface_tgstation_1_1_server_1_1_host_1_1_core_1_1_i_server_port_provider.html',1,'Tgstation::Server::Host::Core']]],
  ['iserverupdateexecutor_195',['IServerUpdateExecutor',['../interface_tgstation_1_1_server_1_1_host_1_1_core_1_1_i_server_update_executor.html',1,'Tgstation::Server::Host::Core']]],
  ['iserverupdateinitiator_196',['IServerUpdateInitiator',['../interface_tgstation_1_1_server_1_1_host_1_1_core_1_1_i_server_update_initiator.html',1,'Tgstation::Server::Host::Core']]],
  ['iserverupdater_197',['IServerUpdater',['../interface_tgstation_1_1_server_1_1_host_1_1_core_1_1_i_server_updater.html',1,'Tgstation::Server::Host::Core']]],
  ['isessioncontroller_198',['ISessionController',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_session_1_1_i_session_controller.html',1,'Tgstation::Server::Host::Components::Session']]],
  ['isessioncontrollerfactory_199',['ISessionControllerFactory',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_session_1_1_i_session_controller_factory.html',1,'Tgstation::Server::Host::Components::Session']]],
  ['isessionpersistor_200',['ISessionPersistor',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_session_1_1_i_session_persistor.html',1,'Tgstation::Server::Host::Components::Session']]],
  ['isignalchecker_201',['ISignalChecker',['../interface_tgstation_1_1_server_1_1_host_1_1_watchdog_1_1_i_signal_checker.html',1,'Tgstation::Server::Host::Watchdog']]],
  ['iswarmoperations_202',['ISwarmOperations',['../interface_tgstation_1_1_server_1_1_host_1_1_swarm_1_1_i_swarm_operations.html',1,'Tgstation::Server::Host::Swarm']]],
  ['iswarmservice_203',['ISwarmService',['../interface_tgstation_1_1_server_1_1_host_1_1_swarm_1_1_i_swarm_service.html',1,'Tgstation::Server::Host::Swarm']]],
  ['iswarmservicecontroller_204',['ISwarmServiceController',['../interface_tgstation_1_1_server_1_1_host_1_1_swarm_1_1_i_swarm_service_controller.html',1,'Tgstation::Server::Host::Swarm']]],
  ['iswarmupdateaborter_205',['ISwarmUpdateAborter',['../interface_tgstation_1_1_server_1_1_host_1_1_swarm_1_1_i_swarm_update_aborter.html',1,'Tgstation::Server::Host::Swarm']]],
  ['isynchronousiomanager_206',['ISynchronousIOManager',['../interface_tgstation_1_1_server_1_1_host_1_1_i_o_1_1_i_synchronous_i_o_manager.html',1,'Tgstation::Server::Host::IO']]],
  ['isystemidentity_207',['ISystemIdentity',['../interface_tgstation_1_1_server_1_1_host_1_1_security_1_1_i_system_identity.html',1,'Tgstation::Server::Host::Security']]],
  ['isystemidentityfactory_208',['ISystemIdentityFactory',['../interface_tgstation_1_1_server_1_1_host_1_1_security_1_1_i_system_identity_factory.html',1,'Tgstation::Server::Host::Security']]],
  ['itokenfactory_209',['ITokenFactory',['../interface_tgstation_1_1_server_1_1_host_1_1_security_1_1_i_token_factory.html',1,'Tgstation::Server::Host::Security']]],
  ['itopicclientfactory_210',['ITopicClientFactory',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_session_1_1_i_topic_client_factory.html',1,'Tgstation::Server::Host::Components::Session']]],
  ['iusergroupsclient_211',['IUserGroupsClient',['../interface_tgstation_1_1_server_1_1_client_1_1_i_user_groups_client.html',1,'Tgstation::Server::Client']]],
  ['iusersclient_212',['IUsersClient',['../interface_tgstation_1_1_server_1_1_client_1_1_i_users_client.html',1,'Tgstation::Server::Client']]],
  ['iwatchdog_213',['iwatchdog',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_watchdog_1_1_i_watchdog.html',1,'Tgstation.Server.Host.Components.Watchdog.IWatchdog'],['../interface_tgstation_1_1_server_1_1_host_1_1_watchdog_1_1_i_watchdog.html',1,'Tgstation.Server.Host.Watchdog.IWatchdog']]],
  ['iwatchdogfactory_214',['iwatchdogfactory',['../interface_tgstation_1_1_server_1_1_host_1_1_components_1_1_watchdog_1_1_i_watchdog_factory.html',1,'Tgstation.Server.Host.Components.Watchdog.IWatchdogFactory'],['../interface_tgstation_1_1_server_1_1_host_1_1_watchdog_1_1_i_watchdog_factory.html',1,'Tgstation.Server.Host.Watchdog.IWatchdogFactory']]],
  ['iyamltypeconverter_215',['IYamlTypeConverter',['../class_i_yaml_type_converter.html',1,'']]]
];
