//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGS.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGS.Tests.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 3.2 Final//EN&quot;&gt;
        ///&lt;html&gt;
        /// &lt;head&gt;
        ///  &lt;title&gt;Index of /download/build/LATEST&lt;/title&gt;
        /// &lt;/head&gt;
        /// &lt;body&gt;
        ///&lt;h1&gt;Index of /download/build/LATEST&lt;/h1&gt;
        ///&lt;pre&gt;&lt;img src=&quot;/icons/blank.gif&quot; alt=&quot;Icon &quot;&gt; &lt;a href=&quot;?C=N;O=D&quot;&gt;Name&lt;/a&gt;                       &lt;a href=&quot;?C=M;O=A&quot;&gt;Last modified&lt;/a&gt;      &lt;a href=&quot;?C=S;O=A&quot;&gt;Size&lt;/a&gt;  &lt;a href=&quot;?C=D;O=A&quot;&gt;Description&lt;/a&gt;&lt;hr&gt;&lt;img src=&quot;/icons/back.gif&quot; alt=&quot;[DIR]&quot;&gt; &lt;a href=&quot;/download/build/&quot;&gt;Parent Directory&lt;/a&gt;                                -   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleBYONDBuildPage {
            get {
                return ResourceManager.GetString("SampleBYONDBuildPage", resourceCulture);
            }
        }
    }
}
