#define DMAPI5_PARAM_DEPLOYMENT_INFORMATION_FILE "tgs_json"
#define DMAPI5_TOPIC_DATA "data"

#define DMAPI5_BRIDGE_COMMAND_NEW_PORT 0
#define DMAPI5_BRIDGE_COMMAND_VALIDATE 1
#define DMAPI5_BRIDGE_COMMAND_PRIME 2
#define DMAPI5_BRIDGE_COMMAND_REBOOT 3
#define DMAPI5_BRIDGE_COMMAND_KILL 4
#define DMAPI5_BRIDGE_COMMAND_CHAT_SEND 5

#define DMAPI5_BRIDGE_PARAMETER_COMMAND "commandType"
#define DMAPI5_BRIDGE_PARAMETER_NEW_PORT "newPort"
#define DMAPI5_BRIDGE_PARAMETER_VERSION "version"
#define DMAPI5_BRIDGE_PARAMETER_CHAT_MESSAGE "chatMessage"
#define DMAPI5_BRIDGE_PARAMETER_MINIMUM_SECURITY_LEVEL "minimumSecurityLevel"

#define DMAPI5_BRIDGE_RESPONSE_ERROR_MESSAGE "errorMessage"
#define DMAPI5_BRIDGE_RESPONSE_ERROR_NEW_PORT "newPort"
#de