compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

logFilters:
  - code: YN0004
    level: discard
  - code: YN0062
    level: discard

nodeLinker: node-modules

preferInteractive: true
